### ISSUE TITLE
slow type-checking for functions with many clauses

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1034]
```
The attached file takes rather a long time (about 9 seconds) to check on my 
machine.  In discussion of this example on the Agda mailing list January 24-27, 
2014, Andreas wrote:

> >   * eps: Most of the time is spent type-checking individual clauses.
>
> There is definitely a source for quadratic behavior here:  Each clause 
> is checked individually, starting with variables for the function 
> arguments and splitting them according to the patterns of this clause. 
> If you have a datatype with n cases, and consequently a function with n 
> clauses, Agda does n splits generating n reference clauses (lhss) each 
> time. 

I am attaching a simplified version of the test file, slow.agda.

I encountered this problem with Agda 2.3.2 on Ubuntu 12.04 Linux.

Aaron Stump
```

Original issue reported on code.google.com by `aaron.st...@gmail.com` on 28 Jan 2014 at 2:26

Attachments:
- [slow.agda](https://storage.googleapis.com/google-code-attachments/agda/issue-1034/comment-0/slow.agda)

**Comment by UlfNorell** [comment]
Updated test case here: https://gist.github.com/UlfNorell/b0c15dc7690bb448f95afb9c3a1164ae

It does seem like the problem has been fixed though. The file checks in 3s on my machine, of which 1.5s is type checking and almost all of that time is spent on the right-hand sides of `eps`.

@astump reopen if necessary.
