### ISSUE TITLE
Inlined Agda code in LaTeX backend

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1054]
It would be nice if the LaTeX backend could also type set inlined Agda code in the La-TeXt, which is not really part of the Agda code.  This is probably not easy to do, but seems vital for literate programming.  Currently, one has to use the \AgdaSomething{} macros and commit to the agda --latex backend, while otherwise one could switch to verbatim (or lhs2TeX) easily.

Maybe Agda's type inference could be called on these snippets to get coloring, or even the approximate coloring from the parser/scope checker could be sufficient?

Original issue reported on code.google.com by `andreas....@gmail.com` on 10 Feb 2014 at 9:15

**Comment by UlfNorell** [comment]
No complaints about @stevana's solution in 4 years. Closing.

**Comment by nad** [comment]
I'd prefer an integrated solution that could handle identifiers from other modules and overloaded identifiers and would allow things like hyperlinking in the Emacs mode. However, I have no plans to work on this right now.

**Comment by andreasabel** [comment]
> No complaints about @stevana's solution in 4 years. Closing.

Live from AIM XXXVIII Swansea: @txa is complaining loudly about not having an easy solution like in lhs2TeX
