### ISSUE TITLE
While type-checking emacs-mode opens *Agda info* buffer in current frame

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1061]
If Agda is still type-checking while I switch to a different emacs frame, it 
will open a window with the Agda info buffer as soon as it has to to print the 
next message (like "Finshed BLA" or "Checking BLA").

That is certainly naughtly misbehavior, playing itself into the center of 
attention all the times.  It is also annoying.

I am using
GNU Emacs 23.3.1 (x86_64-pc-linux-gnu, GTK+ Version 2.24.10)
 of 2013-05-17 on panlong, modified by Debian

Original issue reported on code.google.com by `andreas....@gmail.com` on 15 Feb 2014 at 4:28

**Comment by nad** [comment]
Andreas, do my latest changes fix your problems?

I think this commit should be tested under Aquamacs.

**Comment by andreasabel** [comment]
Works for me on emacs24, it seems.  Thanks!

**Comment by andreasabel** [comment]
Actually, at a closer look, the current behavior is not right either.  If I have to choose, I want the previous behavior back; but maybe this can be fixed without the new undesired effect:
Now, if an AgdaInfo window is already defined in another frame, C-c C-l (or any other command) does not open an AgdaInfo window in the current frame anymore.  
I only wanted to fix that Agda opens an AgdaInfo window in each frame I switch to when Agda is still outputting info during type-checking,without the user having issued a command.

**Comment by nad** [comment]
@andreasabel, is the new implementation more to your liking?

**Comment by UlfNorell** [comment]
Reopen if not.
