### ISSUE TITLE
Freeze metas in module telescope after checking the module?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1063]
```
This is on  Development Agda of February 6, 2014.
For

------------------------------------------------------------------
module _ {α α= β} {A : Setoid α α=}
  where
  open Setoid A 
  open IsEquivalence isEquivalence using (sym)

  negatedRespects : (P : Carrier → Set β) → P Respects _≈_ →
                                                         (¬_ ∘ P) Respects _≈_
  negatedRespects P P-resps x=y ¬Px =  ¬Px ∘ P-resps (sym x=y)
------------------------------------------------------------------

the checker does not solve about  β. 
Must it?

Moving  β  from `module' to the signature of  negatedRespects  does make it 
type-checked.
But the first version looks better.

```

Original issue reported on code.google.com by `mech...@botik.ru` on 18 Feb 2014 at 12:27

**Comment by UlfNorell** [comment]
The current situation is actually that we freeze metas after the first declaration in the module:

```agda
module _ where

module M (A : _) where

  y = Set -- type of A is solved if this is removed

  x : Set
  x = A
```
This is not a sensible behaviour. Two options:
- (easy) freeze metas after checking the module parameters
- (hard) leave module parameter metas unfrozen

The latter solution would require refactoring the way we freeze metas. At the moment we freeze all metas when freezing, but in this case we'd need to freeze metas from the declarations inside the module, but leave the parameter metas unfrozen. This might also lead to some unpredictable behaviour when there are dependencies between parameter metas and local metas.

I'd lean towards the easy solution.

**Comment by jespercockx** [comment]
I also vote for freezing metas from the module parameters right away. The alternative just seems to unpredictable/brittle.

**Comment by andreasabel** [comment]
I vote for a more fine-grained freezing.  Modules should behave similarly to the corresponding record types, which can have metas in their telescope which are resolved by the fields and definitions in the record.

**Comment by UlfNorell** [comment]
How do you propose to deal with the unpredictability/brittleness concerns in this case? Or are you saying we shouldn't freeze any metas inside modules (not even the top-level module?)? This is, I believe, how record types work at the moment.

**Comment by jespercockx** [comment]
Actually @divipp already implemented the second alternative in https://github.com/agda/agda/commit/32220e0415c38ef5e85c493bba3eab6ace298e97#diff-74c7bcc666176816c0d565cbaf6ef7c1R181 (without advertising it). So this issue has been fixed for 7 months already. I now feel stupid for wasting my Sunday on implementing the alternative solution, but I'm also happy I don't have to implement it myself.

**Comment by nad** [comment]
> (without advertising it).

I suggest that we document the change. When are module parameter metas frozen?

**Comment by jespercockx** [comment]
Modules are treated the same as other declarations in this respect, so any metas created while checking a module telescope are frozen at the end of that module. I'll add something to the changelog.
