### ISSUE TITLE
JS back-end hangs when compiling Data.Conat

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1072]
```
agda --js -i ~/src/agda/agda-stdlib/src -i . Main.agda
```

gets to `Data.Conat` and hangs forever

happens on 2.3.2 and current darcs head.

Original issue reported on code.google.com by `t...@dysinger.net` on 1 Mar 2014 at 8:04

**Comment by asr** [comment]
In maint-2.4.2.4, this example hangs

``` Agda
module Test where

open import Data.Conat
```

but in master, the error is

``` bash
$ agda-stdlib --js Test.agda
Not implemented: Compilation of copatterns
```

**Comment by phile314** [comment]
Could be related to Coinduction which is not (yet) implemented in the JS backend.

**Comment by phile314** [comment]
The problem is related to coinduction, but the actual problem lies elsewhere. The JS backend tries to get all definitions in def-before-use order, but code using coinduction (correctly) generates mutually recursive functions. The reorder function just loops forever in that case.

**Comment by phile314** [comment]
Could not reproduce this, appears to be fixed by now.
