### ISSUE TITLE
MAlonzo foreign *export* missing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1081]
The MAlonzo FFI currently seems to be missing a foreign *export* functionality. 
 Concretely, I would like to be able to write something like this:
```agda
  module Test where

  id : ∀ {A : Set} → A → A
  id x = x

  {-# COMPILED_EXPORT id myId #-}
```
and then be able to write Haskell code that imports the MAlonzo generated Haskell file and calls the compiled function under the name myId:
```haskell
  module UseTest where

  import Test

  invokeMyId :: a -> a
  invokeMyId = myId ()
```
Attached is a patch that adds the functionality as described above.  I can add some test cases and release notes about this if the patch is deemed potentially acceptable.

Original issue reported on code.google.com by `dominique.devriese@gmail.com` on 13 Mar 2014 at 11:56

Attachments:
- [Agda-foreign-export.dpatch](https://storage.googleapis.com/google-code-attachments/agda/issue-1081/comment-0/Agda-foreign-export.dpatch)

**Comment by UlfNorell** [comment]
Not sure why this is still open.
