### ISSUE TITLE
Make absurd patterns not needed at toplevel

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1086]
It would be very convenient if we could do without toplevel (as in not under a constructor) absurd patterns, e.g. allowing
```agda
  test : ∀ a b → a ∧ b ≡ true → a ≡ true
  test true true refl = refl
```
instead of
```agda
  test : ∀ a b → a ∧ b ≡ true → a ≡ true
  test true  true  refl = refl
  test false false ()
  test false true  ()
```
The coverage checker would have to check if any argument's type is empty before reporting a missing case.

Are there known bad consequences of this?

Original issue reported on code.google.com by `sanzhi...@gmail.com` on 20 Mar 2014 at 2:57

**Comment by andreasabel** [comment]
Fixed by @jespercockx in https://github.com/agda/agda/commit/242684bca62fabe43e125aefae7526be4b26a135
