### ISSUE TITLE
Serialization takes too long

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1091]
This is to continue the discussion on serialization started in issue #1089.

An idea to reduce serialization time (and size of interface files) that Andrea and I discussed yesterday:
Before serializing the Signature, kill all ranges except for 'nameBindingSite'. 
After type checking is completed, ranges should be irrelevant (except for definition sites, to jump to definition).

Is this already done?  

What would be the side effects of preserving 'nameBindingSite' in KillRange?

Original issue reported on code.google.com by `andreas....@gmail.com` on 30 Mar 2014 at 1:35

**Comment by andreasabel** [comment]
In the context of #2649, definition sites are now preserved.

There is no more active work going on in the serializer, thus, I am closing this.
