### ISSUE TITLE
Level mismatch in a complicated expression.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1095]
What's the problem? Cut-and-pasted program examples are preferred over
attachments (if reasonably short).

Attached.

What version of Agda are you using? On what operating system (if relevant)?

2.3.2.2

Original issue reported on code.google.com by `flickyfr...@gmail.com` on 6 Apr 2014 at 3:15

Attachments:
- [lambda.7z](https://storage.googleapis.com/google-code-attachments/agda/issue-1095/comment-0/lambda.7z)

**Comment by UlfNorell** [comment]
Merging with #1079.
