### ISSUE TITLE
Allow record patterns in lambda-bound positions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1097]
```
Is this intended that   \lambda (x , _) -> f x
is not parsed?
It is better to write than  f ∘ proj₁  if some mnemonic is used instead of  
x.
Also there may be  \lambda ((_ , foo) , _).
```

Original issue reported on code.google.com by `mech...@botik.ru` on 10 Apr 2014 at 8:10

**Comment by UlfNorell** [comment]
Lambda-where and do-notation take care of the problems in the OP, but it's worth keeping the issue for the more general proposal of allowing record patterns in any binding position.

**Comment by nad** [comment]
It seems as if do-notation is still translated to pattern-matching lambdas when regular lambdas with record patterns would work.

**Comment by nad** [comment]
I suppose that the following code should be changed:
https://github.com/agda/agda/blob/037b495bebe2e6aa6746e846cf460b67671fdb11/src/full/Agda/Syntax/DoNotation.hs#L76-L91

**Comment by gallais** [comment]
I think it would have to come much later in the pipeline, as an optimisation
when type-checking pattern-matching lambdas. Indeed in the scope-checking phase
we may not be able to tell whether an overloaded constructor is used as a record
or a datatype constructor.

**Comment by andreasabel** [comment]
> It seems as if do-notation is still translated to pattern-matching lambdas when regular lambdas with record patterns would work.

Please open a new issue for this part.
