### ISSUE TITLE
Overloaded record projections

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1098]
I think it would be a good idea to open coinductive records (or rather their 
corresponding modules) by default. This would make it the same as for datatypes.

I often forget to do this:

``` agda
record Stream (A : Set) : Set where
  coinductive
  field hd : A
        tl : Stream A

open import Data.Nat

ones : Stream ℕ
hd ones = 1
tl ones = ones
```

leading to the error:

```
/Users/james/repos/contnorm/talk.agda:13,1-8
Could not parse the left-hand side hd ones
when scope checking the left-hand side hd ones in the definition of ones
```

Original issue reported on code.google.com by `jmchap...@gmail.com` on 10 Apr 2014 at 4:59

**Comment by andreasabel** [comment]
In #1944 I am implementing overloaded projections.  However, bringing the fields of a record module into scope automatically is problematic as it is not compatible with the use of a record as a type class dictionary.

``` agda
record Show (A : Set) : Set where
  field show : A -> String
open Show {{...}}
```

If the record was opened automatically as well, we would have projections

``` agda
show : {A : Set} -> Show A -> A -> String
show : {A : Set}{{ _ : Show A}} -> A -> String
```

and if the user then writes `show x` is it not clear which one is meant.

**Comment by andreasabel** [comment]
Currently no plans to do more than what has been done for #1944.  Reopen if you want to discuss more.
