### ISSUE TITLE
TERMINATING ignored for local functions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1137]
With the development version of Agda from May 9,  the following is not accepted:

``` Agda
-------
module NoTermCheck where

postulate A : Set

-- {-# NO_TERMINATION_CHECK #-}   -- enabling this works
f : A
f = g
  where
    h : A
    {-# NO_TERMINATION_CHECK #-}
    -- Termination checking fails with only this pragma
    h = h
    g : A
    g = h
----------
```

(In any case, I would expect more information about the pragma placement in the Release Notes than there is now. I had to hunt down the test files...)

Wolfram

```

Original issue reported on code.google.com by `k...@cas.mcmaster.ca` on 21 May 2014 at 3:01
* Blocking: #1195
```

**Comment by asr** [comment]
Since the termination check is (correctly) done in mutual blocks, it is not possible to  analyse the termination and the terminating pragmas of each function in a where clause. For fixing this issue, I suggest to ban the use of the terminating pragmas  inside a where clause. Are you agree?

**Comment by andreasabel** [comment]
Why do we have to ban it?  Couldn't the semantics be that it applies to the whole mutual block?

**Comment by asr** [comment]
> Couldn't the semantics be that it applies to the whole mutual block?

Yes and this is the current semantics. For this reason in

``` agda
postulate
  A : Set
  a : A

foo : A
foo = bar
  where
  {-# TERMINATING #-}
  bar : A
  bar = bar
```

the `bar` function is _correctly_ rejected by the termination checker.

In this example, Agda correctly is ignoring the `{-# TERMINATING #-}` pragma associated to the function inside the where clause. This is the reason for my proposal:

> I suggest to ban the use of the terminating pragmas inside a where clause

**Comment by asr** [comment]
@andreasabel should we ban the use of the terminating pragmas inside a where clause?

**Comment by andreasabel** [comment]
Ah, yes, maybe this is a solution for now.  We can always make it more liberal later, in case we find a good intuitive meaning of a local termination pragma.
