### ISSUE TITLE
Commented goals in literate agda

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1144]
```
Problem : After loading the code below, the commented goal in H₀ displays 
while the second one in H₁ doesn't.

Agda version: 2.3.3 (downloaded using darcs in 08 Apr 2014)

Operating system : Scientific Linux 6.5

================== code ==================

--\begin{code}

H₀ : Set
H₀ = {!!}

--\end{code}

The following goal doesn't show properly

\begin{code}

H₁ : Set
H₁ = {!!}

\end{code}

================== code ==================


```

Original issue reported on code.google.com by `xcjst...@msn.com` on 23 May 2014 at 10:03

Attachments:
- [goal-bug.lagda](https://storage.googleapis.com/google-code-attachments/agda/issue-1144/comment-0/goal-bug.lagda)

**Comment by nad** [comment]
Why should it be possible to comment out LaTeX code using Agda comment notation? If LaTeX comment characters (`%`) are used instead of `--`, then the code in the OP is handled correctly with the most recent development version of Agda.
