### ISSUE TITLE
Missing support for mtl 2.2.* and transformers 0.4.*

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1156]
What the summary says.

Original issue reported on code.google.com by `andres.s...@gmail.com` on 28 May 2014 at 7:23

**Comment by asr** [comment]
The compilation with GHC 7.8.4 and transformers 0.3.0.0 fails after the commit 1d0984e64037520f3aa745d7c6e20bdd87502f3c.

**Comment by asr** [comment]
> transformers is a GHC-included package (at least since 7.8) which makes it difficult for distributions to upgrade, so likely this means that Debian won’t get new Agda versions until 7.10 comes out and reaches Debian.

@nomeata, can we drop support for transformers 0.3.0.0?

**Comment by asr** [comment]
> transformers is a GHC-included package (at least since 7.8) which makes it difficult for distributions to upgrade, so likely this means that Debian won’t get new Agda versions until 7.10 comes out and reaches Debian.

Since the version of Agda in Debian stable is a version from two and half years (Agda 2.4.0.2) and since GHC 8.0.1 reached Debian testing,  I'll remove support for transformers 0.3.0.0.
