### ISSUE TITLE
Unresolved overloaded constructor: improve error message

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1159]
Consider the following situation:

``` agda
postulate
  e : {X : Set} (f : X → X) → X

record A : Set where
  constructor cons

record B : Set where
  constructor cons

Hom-eqv : A
Hom-eqv = e (λ {cons → cons})
```

Agda (dev. version) cannot resolve the overloaded constructor name, returning:

```
Type mismatch
when checking that the pattern cons has type _X_4
```

Could this error message be improved to indicate that it is actually due to a 
failure of overload resolution?

Original issue reported on code.google.com by `sattler.christian` on 29 May 2014 at 9:23
- Merged into: #480

**Comment by andreasabel** [comment]
I figure the local branch has withered!?

**Comment by UlfNorell** [comment]
If I remember correctly I did merge some small refactorings but didn't make much progress on fixing the issue.
