### ISSUE TITLE
Auto fails with non-terminating function

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1169]
Auto in hole `?0` raises a typing error:

```agda
(zero ∷ L) != L of type (List ℕ)
when checking that the expression x₁ has type (foo L)
```

It seems that auto is reducing one-step a non-terminating function whereas this is blocked in the type checker.

```agda
module Bug where

open import Data.List
open import Data.Nat
open import Data.Empty

foo : List ℕ → Set
foo [] = ⊥
foo (zero ∷ L) = foo L
foo (suc N ∷ L) = foo (suc N ∷ L)

bar : (L : List ℕ) → (foo L) → List ℕ
bar [] x = []
bar (zero ∷ L) x₁ = bar L ?0
bar (suc x ∷ L) x₁ = ?1
```

Original issue reported on code.google.com by `fafounet@gmail.com` on 4 Jun 2014 at 11:38

**Comment by gallais** [comment]
Can't reproduce: Agsy simply fails to produce any solution and returns in 0ms.

**Comment by asr** [comment]
Removed use of the standard library from the test case:

```agda
module Issue1169 where

open import Agda.Builtin.List
open import Agda.Builtin.Nat

data ⊥ : Set where

foo : List Nat → Set
foo []          = ⊥
foo (zero ∷ L)  = foo L
foo (suc N ∷ L) = foo (suc N ∷ L)

bar : (L : List Nat) → (foo L) → List Nat
bar [] x = []
bar (zero ∷ L) x₁ = bar L {!!}
bar (suc x ∷ L) x₁ = {!!}
```

**Comment by asr** [comment]
By replacing the above `foo` function by

```agda
postulate foo : List Nat → Set
```

I got in the `*Auto*` buffer the output
```
No solution found
```

@gallais, did you get the above message without replacing the `foo` function? I didn't get any output.

**Comment by gallais** [comment]
In 2.5.2 with the definition of `foo`, I get nothing for the first hole (fails immediately) and a "No solution found after timeout (5s)" for the second one.

In 2.5.2 with the `postulate`, I get a "No solution found" for the first and `L` for the second one.

In both 2.5.3 and 2.6.0 with the definition of `foo`, I get nothing for both holes (the first one fails immediately, the second one takes until timeout).

In both 2.5.3 and 2.6.0 with the `postulate`, I get nothing for the first (fails immediately) and `L` for the second one.

**Comment by asr** [comment]
I added the above test case to the `release-2.5.4` branch.
