### ISSUE TITLE
Internal Error in Auto

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1175]
```
In this repository https://github.com/fafounet/multiljf/blob/mfocus in the file 
FocProps, line 157 a call to auto in the unique hole gives the following 
internal error:

An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/Auto/Typecheck.hs:360

```

Original issue reported on code.google.com by `fafounet@gmail.com` on 5 Jun 2014 at 10:11

**Comment by gallais** [comment]
Updated test case: https://github.com/gallais/multiljf/tree/bug_auto

Can't reproduce the internal error (Agsy just doesn't produce any result).

**Comment by fafounet** [comment]
I'm not involved in this project anymore and I can't thus provide more information.

**Comment by gallais** [comment]
Ok, thanks for the update @fafounet. I suppose we can close this issue then.
