### ISSUE TITLE
Add WITH_K pragma for declarations

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1195]
Sometimes I want/need to type-check various modules using the `--without-K` flag. Right now, I need to add the flag to each module.

Using the new `--with-K` flag, I can use something like

``` bash
$ agda --without-K Everything.agda
```

and to enable K where I need it.

Original issue reported on code.google.com by `andres.s...@gmail.com` on 13 Jun 2014 at 9:40
- Blocked on: #1137

Attachments:
- [with-K.dpatch](https://storage.googleapis.com/google-code-attachments/agda/issue-1195/comment-0/with-K.dpatch)

**Comment by asr** [comment]
@jespercockx after some testing it seems the `WITH_K` pragma should be implemented on function clauses like the `CATCHALL` pragma.  Do you know some reason for implementing the pragma on function definitions instead?

**Comment by jespercockx** [comment]
The unifier is called from two different locations: once from the LHS checker (i.e. for each individual clause) and once from the coverage checker (once for the complete function). So even if you put WITH_K on a single clause, there will still be an error in the coverage checker.

**Comment by asr** [comment]
Thanks!

**Comment by asr** [comment]
I'm not planning to implement this feature.

**Comment by andreasabel** [comment]
This feature hasn't seen lots of demand for a couple of years now, so I am closing the feature request now.
