### ISSUE TITLE
Guardedness checker inconsistency with copatterns

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1209]
Bug found by Dmitriy Traytel.

``` agda
{-# OPTIONS --sized-types --copatterns #-}
module False where

open import Size

record Stream (A : Set) : Set where
  coinductive
  field
    shd : A
    stl : Stream A
open Stream public

map : ∀ {A B : Set} → (A → B) → Stream A → Stream B
shd (map f a) = f (shd a)
stl (map f a) = map f (stl a)

data Mu-Stream : Size → Set where
  inn : ∀ {i} → Stream (Mu-Stream i) → Mu-Stream (↑ i)

iter : ∀ {A} → (Stream A → A) → ∀ {i} → Mu-Stream i → A
iter s (inn t) = s (map (iter s) t)

wit : Stream (Mu-Stream ∞)
shd wit = inn wit  -- SHOULD BE REJECTED
stl wit = wit

data ⊥ : Set where

false : ⊥
false = iter shd (inn wit)
```

 It is a bug in the untyped guardedness check.

``` agda
  wit : Stream (Mu-Stream ∞)
  shd wit = inn wit
  stl wit = wit
```

Since (shd wit) is not a recursive position for streams, the recursive call to 
wit should be banned here.  Only (stl wit) is a recursive position.

Original issue reported on code.google.com by `andreas....@gmail.com` on 19 Jun 2014 at 6:46

**Comment by jespercockx** [comment]
I guess this deserves the false label?

**Comment by nad** [comment]
> Maybe we should just make inductive constructors not guardedness-preserving.
> Only that then copatterns are in general only usable with sizes.

Perhaps we could hide the old guardedness machinery under a flag:
```
           --guardedness                               enable constructor-based guarded corecursion (inconsistent with --sized-types)
           --guardedness-preserving-type-constructors  treat type constructors as inductive constructors when checking productivity, implies --guardedness
           --sized-types                               use sized types (default, inconsistent with --guardedness)
           --no-sized-types                            disable sized types
```
We should reject the combination of `--guardedness` and `--sized-types` (or the absence of `--no-sized-types`) when `--safe` is active. Perhaps other combinations should also be rejected.

**Comment by jespercockx** [comment]
I agree, the combination of `--guardedness`, `--sized-types`, and `--safe` should be rejected. Maybe we should also make `--sized-types` imply `--no-guardedness` by default (but still allow the user to override it with an explicit `--guardedness` flag).

**Comment by nad** [comment]
I think the default should be something that we believe is safe, to avoid leading people astray.

**Comment by nad** [comment]
Blocked by #3451.

**Comment by nad** [comment]
I tried to fix this by (basically) replacing `guardedness` with `Order.Unknown` in the following line when `--guardedness` is not active:

https://github.com/agda/agda/blob/94b9736c430fb1fe6ad124aedac8f662c2f69328/src/full/Agda/Termination/TermCheck.hs#L1048

Is this all that is needed? The test suite points to a potential problem. For instance, take [`Issue1375.agda`](https://github.com/agda/agda/blob/94b9736c430fb1fe6ad124aedac8f662c2f69328/test/Fail/Issue1375.agda). The following is the previous error message:

https://github.com/agda/agda/blob/94b9736c430fb1fe6ad124aedac8f662c2f69328/test/Fail/Issue1375.err#L1-L14

The new error message does not include the problematic call to `type`. Does anyone know why?

**Comment by nad** [comment]
@andreasabel?

**Comment by nad** [comment]
The standard library mixes the two forms of corecursion. For instance, `Codata.Conat` provides conversions to and from `Codata.Musical.Conat.Coℕ`. @MatthewDaggitt and @gallais, how would you like to address this? It is possible to activate both constructor-based guarded corecursion and corecursion based on sized types in one module, but not if `--safe` is active.

**Comment by nad** [comment]
Note also that `--sized-types` and `--guardedness` will presumably both become infective (#2487).

**Comment by nad** [comment]
Some further questions:

* Should the musical builtins be available when `--guardedness` is not active?

* Should it be possible to define coinductive records that do not use sized types without turning on `--guardedness`? (In that case: Is there a correct way to "use sized types"?)

* Should both `--sized-types` and `--guardedness` be off by default?

  Given that we plan to fix the problems with sized types I suggest that we let sized types be on by default unless `--safe` is used, in which case neither option is activated. Later we can perhaps make `--sized-types` the default also when `--safe` is in use.

**Comment by gallais** [comment]
> @MatthewDaggitt and @gallais, how would you like to address this?

We could move the conversion functions to the `Codata.Musical.*` modules. They exist
solely because the (unsafe) IO currently uses old-style coinduction and we want to be
able to write programs using the new-style one.

**Comment by nad** [comment]
I've pushed a fix now. Some notes:

* I moved the conversion functions to the `Musical` modules. I also changed `Data.Container.ν` so that it uses the sized variant of `M`. I pushed these changes to the `experimental` branch.

* I did not address the [further questions](https://github.com/agda/agda/issues/1209#issuecomment-448205454) above.

* I discussed the matter of missing problematic calls with @andreasabel, and I got the impression that he did not think that this is a sign of a (new) hole in the termination checker.

**Comment by nad** [comment]
> Blocked by #3451.

Instead of waiting for a fix I pushed a test case to `test/Succeed` instead of `test/Fail`.

**Comment by nad** [comment]
@andreasabel, consider the following code:
```agda
Type : Set

postulate
  type : Type
  Term : Type → Set

Type = Term type
```
When I run Agda with `-vterm.found.call:20` I get the following output:
```
found call from Type to type
found call from Type to Term
found call from type to type
found call from type to Term
found call from Term to Type
```
This looks strange to me. Why are there calls from `type` to `type`/`Term`, but no call from `type` to `Type`?

**Comment by nad** [comment]
I'm moving the discussion of the potential problem discussed in the previous comment to #1556.

**Comment by andreasabel** [comment]
Your fix as described in https://github.com/agda/agda/issues/1209#issuecomment-447142035 LGTM, @nad.
