### ISSUE TITLE
Strange metavariable behaviour when the first argument comparison is stuck

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1258]
Sorry about the poor title, see Bug.agda.

I ran into this while investigating how equality works when comparing neutral terms, specifically when we want to proceed comparing the rest of the eliminators even when the heads of the eliminator lists can't be proved equal yet.  I suspect that code is wrong, although I'm not sure this bug is related.   Specifically, when Agda does operations like (in Conversion.hs)

``` haskell
          pid <- newProblem_ $ compareType cmp a1 a2
          dom <- if dependent
                 then Dom i1 <$> blockTypeOnProblem a1 pid
                 else return dom1
          addContext (name, dom) $ compareTel t1 t2 cmp (absBody tel1) (absBody tel2)
          stealConstraints pid
```

I think we can run into trouble because after `stealConstraints pid` pid is solved according to `isProblemSolved`, and thus the generated metavariable will be instantiated with `a1`.  However the `compareTel` invocation might be stuck too and resumed later, under false assumptions.

I don't really understand how the constraints handling works so I might be wrong, but I seem to be seeing this behaviour in some examples.

Original issue reported on code.google.com by `f...@mazzo.li` on 22 Aug 2014 at 2:18

Attachments:
- [Bug.agda](https://storage.googleapis.com/google-code-attachments/agda/issue-1258/comment-0/Bug.agda)

**Comment by vlopezj** [comment]
This issue was fixed in commit fb2a8fe1. See also issue #2296.
