### ISSUE TITLE
Fields should be declarable as instances

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1273]
Same example as for issue 1272.-- Andreas, 2014-09-04 regression wrt. Agda 2.4.0

``` agda
module _ where

record FunctorOps (F : Set → Set) : Set₁ where
  field map : ∀ {A B} → (A → B) → F A → F B

open FunctorOps {{...}}

record IsFunctor (F : Set → Set) : Set₁ where
  constructor isFunctor
  field ops : FunctorOps  F

-- Id is a functor.

mutual
 instance
  idIsFunctor : IsFunctor (λ A → A)
  idIsFunctor   = record { ops  = idFunctorOps }
  idFunctorOps  = record { map = λ f → f }

-- Functors compose.

instance
  compIsFunctor : ∀ {F G} → {{F! : IsFunctor F}} → {{G! : IsFunctor G}} → IsFunctor (λ A → F (G A))
  compIsFunctor {{F!}} {{G!}} = record
    { ops  = record { map    = λ h → map (map h) }
    }
    where
      -- This should bring some instances into scope, but does not!
      open module F = IsFunctor F! using (ops)
      open module G = IsFunctor G! using (ops)

-- .F (.G .A) !=< .A of type Set
-- when checking that the expression map (map h) has type
-- .F (.G .A) → .F (.G .B)
```

As F! is in scope and it is eta-equal to pattern 

  record { ops = f }

f should be considered when searching for instances of FunctorOps.  (Same for 
IsFunctor.ops G!).

Otherwise we are inconsistent with the semantics of record patterns, which 
should behave as their translation to projections, but in this case they would 
not.

In comparison, this gives yellow (no instances found, which is a regression to 
Agda 2.4.0):

``` agda
instance
  compIsFunctor : ∀ {F G} → {{F! : IsFunctor F}} → {{G! : IsFunctor G}} → IsFunctor (λ A → F (G A))
  compIsFunctor {{isFunctor f}} {{isFunctor g}} = record
    { ops  = record { map    = λ h → map (map h) }
    }
```

Original issue reported on code.google.com by `andreas....@gmail.com` on 4 Sep 2014 at 8:25
- Blocked on: #1540

**Comment by nad** [comment]
Is the idea that the argument marked with `instance` should be treated as an instance argument? In that case I think the notation should be `{{eq}} : Eq set`, in order to match the notation `{eq} : Eq set`.

**Comment by andreasabel** [comment]
Yes, your suggestion would be the first logical thing todo.  
But then, we could also optionally allow the `instance` keyword, like for declarations.

**Comment by UlfNorell** [comment]
Both make sense but would do different things:

``` agda
field {{x}} : A
```

makes the `x` argument to the constructor an instance argument (and so will be filled in by instance search).

``` agda
field instance x : A
```

makes the projection function `x` an instance (of the class `A`).
