### ISSUE TITLE
.#modulename-number in goals of open imported parameterised modules

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1278]
I see strange printing of internal names when I open import a parameterised module in a different file, using the latest git version of Agda. To reproduce, create the following files:

``` agda
-------------- A.agda --------------
module A (X : Set1) where

  data D : Set where
    d : D
------------------------------------

-------------- B.agda --------------
module B where 

open import A Set

open import Relation.Binary.PropositionalEquality

test : (c : D) -> (c ≡ c)
test d = {!!} -- goal ".#A-60005532.d ≡ .#A-60005532.d"
------------------------------------
```

If I change "open import A Set" into

``` agda
import A
open A Set
```

then the printing problem disappears. It also does not occur if A is not parameterised.

Original issue reported on code.google.com by `fredrik....@gmail.com` on 8 Sep 2014 at 9:20

**Comment by asr** [comment]
> Note that with
> 
> ``` agda
> open import A Set
> ```
> 
> A is not in scope, so the expected goal would be
> 
> ``` agda
> .A.d == .A.d
> ```

@andreasabel, the goal in upstream is

``` agda
?0 : d ≡ d
```

isn't it the expected behaviour?

**Comment by andreasabel** [comment]
That looks fine.  I guess we can add the test case and close this issue.

**Comment by asr** [comment]
I'll do it.
