### ISSUE TITLE
cpphs issue: lexical error at character '\n'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1285]
Jan Stolarek reported (see https://lists.chalmers.se/pipermail/agda/2014/006975.html) the following issue trying to install Agda:

```
$ cabal update
$ cabal get Agda
$ cd Agda-2.4.2
$ cabal install
...

src/full/Agda/Syntax/Parser/Lexer.x:0:2:
    lexical error at character '\n'
```

Jan has the same issue using master.

Original issue reported on code.google.com by `andres.s...@gmail.com` on 28 Sep 2014 at 2:06

**Comment by asr** [comment]
@jstolarek reported the following error using the master branch:

```
$ cabal build
Building Agda-2.6.0...
Preprocessing library Agda-2.6.0...

src/full/Agda/Auto/Auto.hs:0:2: error:
   lexical error at character '\n'
```

```
$ cpphs --version
cpphs 1.20.2
```

```
$ locale
LANG=pl_PL.UTF-8
LANGUAGE=
LC_CTYPE="pl_PL.UTF-8"
LC_NUMERIC="pl_PL.UTF-8"
LC_TIME="pl_PL.UTF-8"
LC_COLLATE="pl_PL.UTF-8"
LC_MONETARY="pl_PL.UTF-8"
LC_MESSAGES="pl_PL.UTF-8"
LC_PAPER="pl_PL.UTF-8"
LC_NAME="pl_PL.UTF-8"
LC_ADDRESS="pl_PL.UTF-8"
LC_TELEPHONE="pl_PL.UTF-8"
LC_MEASUREMENT="pl_PL.UTF-8"
LC_IDENTIFICATION="pl_PL.UTF-8"
LC_ALL=
```

I noticed that the error in the OP was reported in the `src/full/Agda/Syntax/Parser/Lexer.x` file. Now the error is reported in a different file.

As I mentioned before, @jstolarek has no problems using cpp instead of cpphs.

**Comment by asr** [comment]
@jstolarek which is the output of

```
$ ghc -cpp -pgmPcpphs -optP--cpp Test.hs
```

``` haskell
$ cat Test.hs
module Main where

#define FOO 1

#ifdef FOO
foo = 42
#endif

main = print foo
```

?

**Comment by jstolarek** [comment]
```
[killy@GLaDOS : ~] ghc -cpp -pgmPcpphs -optP--cpp Test.hs

Test.hs:0:2: error: lexical error at character '\n'
```

**Comment by asr** [comment]
This isn't an Agda issue. I filed https://github.com/malcolmwallace/cpphs/issues/7.

**Comment by UlfNorell** [comment]
Closing since the conclusion over at cpphs was that it's a problem in ghc and no one filed a ghc ticket.
