### ISSUE TITLE
Task: Better test suite driver

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1289]
To increase productivity, we need a better test suite driver.  Let's start with one for test/succeed.  

Currently, there is a simple Makefile that will run Agda on all the *.agda and *.lagda files in random order and then stop at the first failing test.

What I envision is a small Haskell program that 
* runs Agda on all the test cases, 
* prints a line containing the name of the test and whether it passed or failed, and 
* in the end gives me a summary:  OK if everything passed, or a list of tests that failed.

The exit code should be (as usual)
* 0 when everything was OK, and 
* 1 else.

The order in which the test cases are run could also be smart, like the newest cases first, or the ones that failed last time first.  Unfortunately git has no respect for time stamps, so "newest first" might often not be very meaningful.

No knowledge of Agda internal required.

Original issue reported on code.google.com by `andreas....@gmail.com` on 30 Sep 2014 at 8:04

**Comment by UlfNorell** [comment]
We have this now.
