### ISSUE TITLE
Unification doesn't handle record types correctly

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1316]
The unifier tries to expand uncurry metavariables (by generating an inversion 
that will project the fields) and eta-expand variables in the context to remove 
projected variables, but the two don't compose -- see the attached file.

We can solve this by projecting variables nested in record data constructors, 
not only top-level ones.

Original issue reported on code.google.com by `f...@mazzo.li` on 18 Oct 2014 at 12:16

Attachments:
- [NestedProjections.agda](https://storage.googleapis.com/google-code-attachments/agda/issue-1316/comment-0/NestedProjections.agda)

**Comment by andreasabel** [comment]
These test cases pass on maint but not on master.  (Looking for where this was fixed in maint, and where broken in master...)

**Comment by andreasabel** [comment]
It passes on maint because of the underscores (test _ _) which are eta-expanded into record patterns.  If we give variables instead, it does not pass, neither on maint nor on master!

``` agda
open import Common.Product
open import Common.Equality

module _ (A : Set) where

mutual
  X : A × A → A
  X = _

  test : (x y : A × A) → X (proj₁ x , proj₁ y) ≡ proj₁ x
  test x y = refl

verify : ∀{p} → X p ≡ proj₁ p
verify = refl
```

**Comment by andreasabel** [comment]
Implemented the original suggestion to fix this issue.
