### ISSUE TITLE
Typechecking loops on data definition

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1375]
```agda
open import Common.Equality

mutual
  Type : Set
  postulate 
    type : Type
    Term : Type → Set

  Type = Term type

  weakenType : Type → Type → Type
  weaken : (ty ty' : Type) → Term ty → Term (weakenType ty' ty)

  weakenType ty ty' = subst Term {!!} (weaken type {!!} ty)
  weaken ty ty' t = {!!}

data Test : Type → Set where
  test : Test (weakenType type type)
```
Checking this file without the definition of `Test` works fine (termination checker doesn't complain), but adding `Test` (which is NOT in the mutual block) causes Agda to loop. This is on the master branch.

Original issue reported on code.google.com by `jesper.c...@gmail.com` on 1 Dec 2014 at 11:22

**Comment by andreasabel** [comment]
See also #1556.  Note: While reverting the fix of #1556, the error messages on this issue change from termination errors to unsolved metas (bogus error).
