### ISSUE TITLE
Agda input mode: \long...arrow binds to wrong unicode symbol

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1376]
```
\longrightarrow etc. seem to bind just to \rightarrow aka \->, instead of to 
\-->.

Todo: check the \longarrow and \Longarrow bindings and fix them.
```

Original issue reported on code.google.com by `andreas....@gmail.com` on 1 Dec 2014 at 4:56

**Comment by ghost** [comment]
Is it even desirable to mess with the TeX input method?

**Comment by nad** [comment]
> Is it even desirable to mess with the TeX input method?

The Agda input method code does not mess with the TeX input method.

**Comment by nad** [comment]
@andreasabel, I suggest that you file an Emacs bug report.

**Comment by andreasabel** [comment]
I sent an email to bug-gnu-emacs@gnu.org with the following content:

```
\longrightarrow should bind to

  character: ⟶ (displayed as ⟶) (codepoint 10230, #o23766, #x27f6)

However, it produces

  character: → (displayed as →) (codepoint 8594, #o20622, #x2192)

which is a short arrow.

I guess the other \long...arrow bindings should also be fixed.
```
