### ISSUE TITLE
Termination checker rejects function with with-clause

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1381]
The termination checker reject the following fairly simple function. Is this known/expected?

Consider the following code:

```agda
--------------------------------------
data Unit : Set where
  unit : Unit

data Maybe (A : Set) : Set where
  nothing : Maybe A
  just : A → Maybe A

data Test : Set where
  map : (Unit → Maybe Test) → Test

-- Accepted:
foo : Test → Unit
foo-aux : Maybe Test → Unit
foo (map f) = foo-aux (f unit)
foo-aux nothing = unit
foo-aux (just x) = foo x

-- Termination checker complains:
test : Test → Unit
test (map f) with f unit
test (map f) | nothing = unit
test (map f) | just x = test x
--------------------------------------
```

It would of course be nice if the function `test` would pass the termination checker.

Tested on release 2.4.0.1 (OS X 10.9.2) and on the developer branch (Arch Linux).

Original issue reported on code.google.com by `peter.br...@gmail.com` on 4 Dec 2014 at 4:47

**Comment by jespercockx** [comment]
Another reason to remove the current implementation of with-inlining.
