### ISSUE TITLE
Formulas with instance arguments sometimes displayed incorrectly

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1385]
```
Agda version 2.4.2.2. In the interactive mode, formulas with instance arguments 
are sometimes displayed incorrectly. Minimal example:

  postulate A : Set
  postulate a : A

  record Eq : Set1 where
    field eq : (a : A) -> Set

  open Eq {{...}} public

  instance postulate e : Eq

  test1 : (p : eq {{e}} a) -> A
  test1 p = ?

In the hole, the hypothesis p is incorrectely displayed as 

  p : Eq.eq e a

where it should be

  p : Eq.eq a

or maybe at best

  p : Eq.eq {{e}} a

This is especially confusing in the case where we have a binary infix operator 
instead of eq. In this case, we get e.g.

  p : (e Eq.=== a) b

when it should be

  p : a Eq.=== b

```

Original issue reported on code.google.com by `selinger...@gmail.com` on 6 Dec 2014 at 3:51

**Comment by UlfNorell** [comment]
The current behaviour is not incorrect. `Eq.eq` has type `Eq → A → Set` so displaying `Eq.eq e a` is correct even if it's not the most convenient (which would be `eq a` in this case).

The problem with displaying `Eq.eq e a` as `eq a` is that this is only correct in situations where the instance argument to `eq` would indeed be solved with `e`. It would be quite misleading if `Eq.eq e' a` displayed as `eq a` for some `e'` that's not an instance. If you, knowing the pitfalls, still want  this behaviour you can introduce a display form:
```agda
{-# DISPLAY Eq.eq _ = eq #-}
```
> The current semantics of  open R {{...}}  is problematic and should be improved.

Do you have any suggestions for a better design?
