### ISSUE TITLE
Copatterns and instance arguments don't play nice together

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1413]
The code below causes an internal error at 
src/full/Agda/TypeChecking/Rules/LHS/Split.hs:107.

``` agda
{-# OPTIONS --copatterns #-}

record Foo (A : Set) : Set where
  field
    foo : A

open Foo {{...}} public

record ⊤ : Set where

instance
  Foo⊤ : Foo ⊤
  foo Foo⊤ = {!!}
```

If possible, I'd like to be able to write the following:

```
instance
  Foo⊤ : Foo ⊤
  foo {{Foo⊤}} = tt
```

but a proper error message would be a good start as well.

Original issue reported on code.google.com by `jesper.c...@gmail.com` on 23 Jan 2015 at 3:38

**Comment by ice1000** [comment]
Oh! This is very nice, should we document it somewhere?

**Comment by jespercockx** [comment]
Yes, we should.
