### ISSUE TITLE
Inherited dot patterns in with functions are not checked

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#142]
What steps will reproduce the problem?

Read the following code.

What is the expected output? What do you see instead?

In the last line, it should be type checked only if 
```
fun .n | i .n | i n = 0
```
but the following code also works,
```
fun .0 | i .n | i n = 0 or anything else.
```
What version of the product are you using? On what operating system?

2.2.1, Linux 2.6.26

Please provide any additional information below.
```agda
open import Data.Nat
data Nat : ℕ → Set where
  i : (k : ℕ) → Nat k

toNat : (n : ℕ) → Nat n
toNat n = i n

fun : (n : ℕ) → ℕ
fun n with toNat n
fun .n | i n with toNat n
fun .0 | i .n | i n = 0
```

Original issue reported on code.google.com by `xcycl.xoo` on 30 Mar 2009 at 8:12

Attachments:
- [Parity.agda](https://storage.googleapis.com/google-code-attachments/agda/issue-142/comment-0/Parity.agda)

**Comment by andreasabel** [comment]
See `With.hs`, do something in `stripWithClausePatterns` in case `I.DotP / A.DotP`:
```haskell
        DotP v  -> case namedArg p of
          A.DotP _ _    -> ok p
          A.WildP _     -> ok p
          -- Ulf, 2016-05-30: dot patterns are no longer mandatory so a parent
          -- dot pattern can appear as a variable in the child clause. Indeed
          -- this happens if you use a variable in the parent and '...' in the
          -- child. In this case we need to remember the the binding, so we can
          -- insert a let for it.
          A.VarP x -> do
            (a, _) <- mustBePi t
            tell [A.NamedDot x v (unDom a)]
            ok p
```
similar to the `tell [ A.NamedDot ...`.

**Comment by UlfNorell** [comment]
@andreasabel: Fixed as suggested.

**Comment by asr** [comment]
Is a consequence of this fix that the current master of the standard library is not compatible with the RC for 2.5.3?

**Comment by asr** [comment]
Self-answer: The master branch of the standard library continues being compatible with the RC.

**Comment by UlfNorell** [comment]
Indeed. After the fix Agda is more picky, so if it checks with current stable it also checks with the RC (at least wrt this fix).

**Comment by asr** [comment]
For preparing the release of 2.5.3 next week I'm planning to use the stable branch on that week, so I added the 2.5.3 milestone to this issue.
