### ISSUE TITLE
Instances with relevant recursive instance arguments are not considered in irrelevant positions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1425]
Minimal example:
```agda
postulate 
  A B : Set
  C : .{{_ : B}} → Set
  instance
    f : {{_ : A}} → B
  test : (x : A) → C
```
Instance search should infer the argument {{f {{x}}}} of C, but it doesn't. 
Making the argument to C relevant OR the argument to f irrelevant fixes the problem.

Original issue reported on code.google.com by `jesper.c...@gmail.com` on 10 Feb 2015 at 1:43

**Comment by UlfNorell** [comment]
Seems to work now (if you make the `A` argument to `test` an instance argument):

```agda
postulate
  A B : Set
  C : .{{_ : B}} → Set
  instance
    f : {{_ : A}} → B
  test : {{x : A}} → C
```

**Comment by asr** [comment]
I added the above test case to the `release-2.5.4` branch.
