### ISSUE TITLE
Support for making an implicit argument explicit and vice versa

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#146]
Wouter's description: "Select an implicit argument in the type signature, hit some emacs commands, and the argument gets made explicit (in the type signature) and an additional argument gets added on the left-hand side of the definitions. There's a similar operation to turn explicit arguments into implicit ones. At the moment, when I'm not sure which arguments can be left out, I tend to make things overly explicit and refine my definitions later. It be nice if there was a bit more support for this kind of development."

Original issue reported on code.google.com by `nils.anders.danielsson` on 8 Apr 2009 at 11:57

**Comment by andreasabel** [comment]
We can dream about this for another 7 years.

There is limited support for making hidden arguments visible for splitting in #2466.
