### ISSUE TITLE
Performance regression

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1469]
Test case (the RTS options work on my 32-bit setup):
```
  darcs get http://www.cse.chalmers.se/~nad/repos/equality/
  cd equality
  agda Univalence-axiom/Isomorphism-is-equality/More/Examples.agda +RTS -M2G -K40M
```
Offending commit:
- [ Issue #1454 ] Fixed by normalization.
   https://github.com/agda/agda/commit/d706940eed5e7bba997b1c9185a1f6968622071c

Original issue reported on code.google.com by `nils.anders.danielsson` on 25 Mar 2015 at 7:51

**Comment by andreasabel** [comment]
This issue produced no regression test.
