### ISSUE TITLE
Agda is not part of Stackage

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1479]
Hi,

Stackage LTS is a nice curated set of compatible Haskell packages; I’d like Debian to follow it more closely. Unfortuantely, Agda is currently (2.4.2.2) incompatible with it, due to hashtables (>=1.0 && <1.2).

Please consider uploading a version of Agda that is compatible with stackage LTS 2.0.

Furthermore, live becomes easier if Agda is part of Stackage; this will give you more testing and early warnings about incorrect bounds, and better user experiences for those building Agda. See http://www.stackage.org/authors for the steps to get Agda included.

Thanks,
Joachim

Original issue reported on code.google.com by `nome...@gmail.com` on 2 Apr 2015 at 10:38

**Comment by asr** [comment]
I added Agda to Stackage for the reasons pointed out in https://github.com/agda/agda/issues/1479#issue-99824959. At the moment, Agda (and other packages) are blocking that haskell-src-exts 1.17.0 is in Stackage (see https://github.com/fpco/stackage/issues/981).

In https://github.com/fpco/stackage/issues/981#issuecomment-162243104, Stackage's maintainers agreement was reminded

> As per the [maintainers agreement](https://github.com/fpco/stackage/wiki/Maintainers-Agreement#major-breaking-changes), I think the agreement is that people have a week to upgrade to the new version of HSE, or a month if you interpret this as a "significant change".

To be honest, I didn't read the maintainers agreement before adding Agda to Stackage. Anyway, one-month time window for realising a new version of Agda is unrealistic for us, so I'll remove Agda from Stackage.

Any opinion?

Pinging @nomeata and @juhp.

**Comment by juhp** [comment]
I would say please wait a little more: I feel your response in fpco/stackage#981 is sufficient for now.

**Comment by asr** [comment]
> I would say please wait a little more: I feel your response in #981 is sufficient for now.

(I guess you meant https://github.com/fpco/stackage/issues/981).

OK. Thanks for the feedback.

**Comment by juhp** [comment]
> (I guess you meant fpco/stackage#981).

Yep sorry (fixed with an edit).

**Comment by asr** [comment]
For the record, my answer in https://github.com/fpco/stackage/issues/981 is in https://github.com/fpco/stackage/issues/981#issuecomment-162252518.

**Comment by asr** [comment]
FYI, In https://github.com/fpco/stackage/issues/981#issuecomment-162421312, @juhp asked:

> @asr Is there any chance of a backport release 2.4.2.4.1 of Agda in the meantime with say just the haskell-src-exts-1.17 changes (like from a 2.4.2.4 branch)?
> 
> 4bfe1b5

**Comment by asr** [comment]
> @asr Is there any chance of a backport release 2.4.2.4.1 of Agda in the meantime with say just the haskell-src-exts-1.17 changes (like from a 2.4.2.4 branch)?
> 
> 4bfe1b5

The regression in #1701 was introduced in Agda 2.4.2.3, so a backport release 2.4.2.4.1 is not an option.

**Comment by WolframKahl** [comment]
On Mon, Dec 07, 2015 at 07:00:53AM -0800, Andrés Sicard-Ramírez wrote:

> The regression in #1701 was introduced in Agda 2.4.2.3, so a backport release 2.4.2.4.1 is not an option.

Since it was already in a maintenance release, as far as I am concerned, not fixing it would be an option.
(As I mentioned elsewhere, I am unlikely to use the next maintenance release anyways.)

Wolfram

**Comment by asr** [comment]
@WolframKahl Thanks for the feedback. Ulf also thinks that a maintenance release without fixing the regression is an option (https://github.com/agda/agda/issues/1727#issuecomment-161678261):

> The regression has already been released in 2.4.2.3 and 2.4.2.4 hasn't it, so I don't see a huge problem with leaving it also in 2.4.2.5?

@andreasabel   What do you think?

**Comment by andreasabel** [comment]
I agree, we can release the maintenance version as often as we want.  I does not have to fix all known regressions.  
We should be confident it does not introduce new regressions.  But in the end, one never knows.

**Comment by asr** [comment]
I'll start the release procedure of Agda 2.4.2.5 on Thursday.

**Comment by andreasabel** [comment]
Good.
