### ISSUE TITLE
Remove the Epic backend

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1481]
```
I'll wait a possible answer to the poll in 
https://lists.chalmers.se/pipermail/agda/2015/007634.html until 2015-04-15 
before removing the Epic back-end.
```

Original issue reported on code.google.com by `andres.s...@gmail.com` on 6 Apr 2015 at 3:46

**Comment by asr** [comment]
> completely purge the Epic backend

Really? Grepping by 'Epic' or 'epic' I found some Epic stuff (e.g. the `src/data/EpicInclude` directory).
