### ISSUE TITLE
Compilation with GHC 7.6.3/7.8.4 fails in Travis

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1520]
See the issue in https://travis-ci.org/agda/agda/jobs/63765899.

Original issue reported on code.google.com by `andres.s...@gmail.com` on 23 May 2015 at 1:51

**Comment by asr** [comment]
After the commit 1d0984e64037520f3aa745d7c6e20bdd87502f3c the Travis builds are failing because we use the `--avoid-reinstalls` option.
