### ISSUE TITLE
Travis test for compiling with GHC 7.8.4 using transformers 0.3.0.0 doesn't work 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1539]
Travis doesn't report the problem fixed by https://github.com/agda/agda/commit/703916048b6a7aa669e16a106d323071b9bd4cb8.

Original issue reported on code.google.com by `andres.s...@gmail.com` on 3 Jun 2015 at 2:00

**Comment by asr** [comment]
This Travis build is failing after the commit 1d0984e64037520f3aa745d7c6e20bdd87502f3c.

**Comment by asr** [comment]
Arggg... while testing in Travis the unordered-containers-0.2.6.0 library was released and it added the error "Ambiguous occurrence ‘mapMaybe’"...

**Comment by asr** [comment]
Fixed by 021cc1390a83407d8196246657dd15c67fe6eaa7.
