### ISSUE TITLE
Positivity polymorphism needed for compositional positivity analysis

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1544]
The test case is not quite minimal (when trying to minimize it, the issue just went away) so I've pushed it on a specific branch:

https://github.com/gallais/agdARGS/tree/positivity-issue

The specific issue is explained in this file:

https://github.com/gallais/agdARGS/blob/positivity-issue/agdARGS/System/Console/CLI2.agda

Original issue reported on code.google.com by `g.x.all...@gmail.com` on 4 Jun 2015 at 9:33

**Comment by andreasabel** [comment]
Inlining non-recursive functions could still be non-terminating, or a performance killer, see https://github.com/agda/agda/issues/1899#issuecomment-269910492
The fix for #1899 fixed the test case above.
