### ISSUE TITLE
Pragma to switch off positivity checker for data definitions and mutual blocks

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1614]
Similar as for the termination checker, there should be pragmas for muting the positivity checker for individual declararations:

``` Agda
{-# NON_POSITIVITY_CHECK #-}
data D : Set where
  lam : (D -> D) -> D
```

Original issue reported on code.google.com by `andreas....@gmail.com` on 22 Jul 2015 at 1:57

**Comment by andreasabel** [comment]
Andres, are you making progress on this issue or are you stuck on something I could help with?

**Comment by asr** [comment]
I haven't had time for starting...

Maybe it is not related, but I would like to see #1137 closed before working on this issue and #1195.

**Comment by asr** [comment]
Blocked on #1755.

**Comment by asr** [comment]
Can I get the mutual block information (i.e. [MutualInfo](https://github.com/agda/agda/blob/master/src/full/Agda/Syntax/Info.hs#L165-L169)) inside the [checkStrictlyPositive](https://github.com/agda/agda/blob/master/src/full/Agda/TypeChecking/Positivity.hs#L61) function? How?

Remark: I could get the mutual block information from the first argument (i.e. `Info.MutualInfo`) of [mutualChecks](https://github.com/agda/agda/blob/master/src/full/Agda/TypeChecking/Rules/Decl.hs#L226-L248), but I realised that currently this argument is unnecessary.

**Comment by asr** [comment]
I finished the implementation of the pragma for data definitions and mutual blocks. Although I have no implemented the pragma for records yet, I'll push my implementation.

Is there some nice example of mutually non-strictly positive data types? I need this example for the CHANGELOG.

**Comment by asr** [comment]
TODO: Rename `NO_POSITIVITY_CHECK` to `STRICTLY_POSITIVE`.

**Comment by asr** [comment]
~~TODO: Rename NO_POSITIVITY_CHECK to STRICTLY_POSITIVE.~~ We'll continue the discussion on #1767.
