### ISSUE TITLE
Record fields highlighted as functions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1619]
```
The `a` record field of `Pack` is identified as a function
(coloured blue, put in a \AgdaFunction in the LaTeX backend)
when it should be coloured pink.
The problem does not show up when dropping the second record
type or removing the module declaration.

==========================================================

module recordColour where

record Pack (A : Set) : Set where
  field
    a : A

record Packed {A : Set} (P : Pack A) : Set where
  module PP = Pack P

module Synchronised {A : Set} {P : Pack A} (rel : Packed P) where
  open Packed rel
```

Original issue reported on code.google.com by `g.x.all...@gmail.com` on 30 Jul 2015 at 2:52

Attachments:
- [recordColour.agda](https://storage.googleapis.com/google-code-attachments/agda/issue-1619/comment-0/recordColour.agda)
- [recordColour.png](https://storage.googleapis.com/google-code-attachments/agda/issue-1619/comment-0/recordColour.png)

**Comment by andreasabel** [comment]
First, field `a` is colored pink (from the tokens), in the second highlighting phase it is colored blue.  One can observe this by introducing a type error, like

``` agda
  open Packed P  -- instead of rel
```

**Comment by andreasabel** [comment]
Fixed by https://github.com/agda/agda/commit/bdd7e5cdcb8f407d7082a74c617b19e5a7519b84
