### ISSUE TITLE
unnatural cost of type-checking `open'

### ISSUE THREAD

**Issue by mechvel** [agda/agda#1630]
Please, download the code from 
http://www.botik.ru/pub/local/Mechveliani/agdaNotes/bugRep-aug18-2015.zip 

This of on the  type checker of  Agda 2.4.2.3,  ghc-7.10.2.

The computer has  16 Gb RAM,  3.3 GHz processor (amd-64),
it is under Debian Linux (for amd-64).

The problem is of the type-check cost of `open'.

  unzip bugRep-aug18-2015.zip

The project has about 20 .agda files:
    Foo1.agda, ..., Foo19.agda, OverIntegralRing-01.agda.

Type checking is by
  `agda -i $agdaStLib -i . +RTS -K100m -M13200m -H13200m -A1G -RTS   OverIntegralRing-01.agda'

Here  13200m  is the 13.2 Gb heap restriction, it is the maximal value under which swapping does not happen on this machine.
First type-check all the files except the last. This takes, may be, about 15 minutes.
1. After this, type-checking  OverIntegralRing-01.agda
   takes about 13 minutes and breaks reporting that  13200 MB heap is not sufficient.

But this module contains only an  import - `open' prelude.
It needs to define further some data types and functions which use this prelude.
And type-checking this very environment does not fit into the memory space (which is quite large).
1. Comment out the code part after  "--- 3".
   Then it is type-checked in  437 sec, and the .agai file is of 11.3 Mb.
2. Comment out the code part after  "--- 2".    Then it is type-checked in  387 sec.
3. Comment out the code part after  "--- 1".
   Then it is type-checked in  200 sec, and the .agai file is of 5.1 Mb.

This shows that the result of `open' costs too much for type checker.
And I am stuck, do not know how to continue the project.

Please, advise.

---

Sergei

**Comment by UlfNorell** [comment]
Closing as the code in the OP is no longer available.
