### ISSUE TITLE
Parse `forall {x (z : P x) y} -> ...`

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#1636]
Not a very good example, but it would be nice to put a type annotation into a hidden quantification without closing and reopening the braces.

``` agda
test : ∀ {A : Set} (P : A → Set) {x (y : P x)} → Set
```

**Comment by UlfNorell** [comment]
I find that quite hard to read, and it's not even saving you any characters:
```agda
test : ∀ {A : Set} (P : A → Set) {x (y : P x)} → Set  -- weird
test : ∀ {A : Set} (P : A → Set) {x} {y : P x} → Set  -- nice
```

**Comment by andreasabel** [comment]
Well, the use case is if you have a list of hidden arguments already, but then need to refine one with a type annotation.  My hand naturally lead me to something like `test` but then it does not parse. 
I do not think it is hard to read. It is the cosituation to `(x {y z} : A)` which is also not hard to read.

**Comment by UlfNorell** [comment]
What about `{x (y {z} : P x)} → Set`?

**Comment by andreasabel** [comment]
That gives the information that `z` is hidden twice.  Should give an error in the scope checker.

**Comment by nad** [comment]
I suspect that the meaning of the suggested syntax is not sufficiently obvious.

**Comment by andreasabel** [comment]
Braces `{ }` around something declare this thing hidden, but ordinary parentheses `( )` are just for disambiguation (otherwise you could not write `{(arg)}` as a hidden argument in an application).
What  is the problem?

**Comment by UlfNorell** [comment]
The problem is that it's introducing complications in the syntax without making any easier for the user. Or are you seriously suggesting that
```agda
test : ∀ {x (y : P x)} → Set
```
is easier to read than
```agda
test : ∀ {x} {y : P x} → Set
```
?
