### ISSUE TITLE
Disable force push on master/maint

### ISSUE THREAD

**Issue by phile314** [agda/agda#1638]
Github finally implemented the feature to disable forced pushes.

I don't see any value in allowing forced pushes on master/maint, and would prefer if those are disabled. This needs repo admin rights to do, and may not yet be available for the Agda repo right now.

See:
https://github.com/blog/2051-protected-branches-and-required-status-checks

**Comment by andreasabel** [comment]
Agreed, we should make use of this feature as soon as it is out.

**Comment by asr** [comment]
Done!
