### ISSUE TITLE
ConcreteToAbstract internal error

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#1639]
I'm using Agda 2.4.3. Here is my code:

``` agda

open import Level

data Example {ℓ} (t : Set ℓ) : Set ℓ where
    field
      x : t

```

I receive this message: `An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs:1440`

EDIT: The problem in the code above is that it uses `data` instead of `record`, which causes the compiler to become confused and crash.

**Comment by asr** [comment]
I could reproduce the issue using Agda 2.4.3 (master).

Using maint and Agda 2.4.2.3, I _correctly_ got the error

``` bash
$ agda-stdlib Issue1639.agda
/tmp/Issue1639.agda:4,5-5
/tmp/Issue1639.agda:4,5: Parse error
field<ERROR>

      x : t
...
```

**Comment by andreasabel** [comment]
Import-free test case:

``` agda
data D : Set1 where
  field
    A : Set
```

My suspicion is that this bug was introduced by a relaxation of declaration parsing, e.g., https://github.com/agda/agda/commit/7ca60fd60aec1b73d9f14aaa6e1aeef184bcca79
