### ISSUE TITLE
Allow heterogeneous rewrite rules

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#1641]
Is there a particular reason why the rewrite relation has to be homogeneous (of type {A : Set} -> A -> A instead of {A B : Set} -> A -> B)?
Rewrite rules are already completely unsafe, it wouldn’t make it worse to allow heterogeneous rewrite rules and it’s useful for instance when you want to assume two rewrite rules where the well-typedness of the second one depends on the first one (both "rewrite rules" are the arguments of a function, so I can’t use {-# REWRITE #-} there).

**Comment by andreasabel** [comment]
Can you post a meaningful example here?

**Comment by guillaumebrunerie** [comment]
My example was the following: I want to postulate an "eta"-rule to the higher inductive type `Circle` which says that if we have two functions `f g : Circle -> A` such that `f base === g base` (definitional/strict/rewriting equality) and `ap f loop === ap g loop`, then for every `x : Circle` we have `f x === g x`.

But `ap f loop` and `ap g loop` have the same type only under the condition that `f base` and `g base` are seen as definitionally equal by Agda, so with an homogeneous rewriting relation I cannot state it.

``` agda
{-# OPTIONS --without-K --rewriting #-}

open import Agda.Primitive

-- Heterogeneous rewriting relation
postulate
  _↦h_ : ∀ {i j} {A : Set i} {B : Set j} → A → B → Set (i ⊔ j)
{-# BUILTIN REWRITE _↦h_ #-}

-- Homogeneous rewriting relation (to help Agda with unification when the types are the same)
_↦_ : ∀ {i} {A : Set i} → A → A → Set i
_↦_ = _↦h_

-- Path type
data _==_ {i} {A : Set i} (a : A) : A → Set i where
  idp : a == a

ap : ∀ {i j} {A : Set i} {B : Set j} (f : A → B) {x y : A}
  → (x == y → f x == f y)
ap f idp = idp


postulate
  Circle : Set
  base : Circle
  loop : base == base

postulate
  Circle-η : ∀ {i} {A : Set i} (f g : Circle → A)
    (base* : f base ↦ g base)
    (loop* : ap f loop ↦h ap g loop)
    → (x : Circle) → (f x ↦ g x)
```

But now that I’m thinking about it, I should probably instead separate the type of rewrite rules and the type of strict equalities (allowing only strict equalities to be heterogeneous), it would be cleaner and would remove the need for heterogeneous rewrite rules.

**Comment by andreasabel** [comment]
Do you still want heterogeneous rewrite rules or can I close this issue?

**Comment by guillaumebrunerie** [comment]
I don’t need them anymore.
