### ISSUE TITLE
Odd rewriting fail

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#1648]
The following code doesn’t typecheck but it should. I have no idea what’s going on.

Replacing the definition of `PathOver-rewr` by a question mark and asking for full normalisation of the goal (C-u C-u C-c C-t), I obtain `HetEq idp u v == (u == v)`, so it seems that the term `PathOver (λ _ → B) p u v)` is rewritten as `HetEq idp u v` using `ap-cst` (as expected), but then for some reason `HetEq idp u v` isn’t reduced to `u == v`.

``` agda
{-# OPTIONS --rewriting #-}

data _==_ {i} {A : Set i} (a : A) : A → Set where
  idp : a == a
{-# BUILTIN REWRITE _==_ #-}

ap : ∀ {i j} {A : Set i} {B : Set j} (f : A → B) {x y : A}
  → x == y → f x == f y
ap f idp = idp

ap-cst : {A B : Set} (b : B) {x y : A} (p : x == y)
  → ap (λ _ → b) p == idp
ap-cst b idp = idp
{-# REWRITE ap-cst #-}

HetEq : {A B : Set} (e : A == B) (a : A) (b : B) → Set
HetEq idp a b = (a == b)

PathOver : {A : Set} (B : A → Set)
  {x y : A} (p : x == y) (u : B x) (v : B y) → Set
PathOver B p u v = HetEq (ap B p) u v

PathOver-rewr : {A B : Set} {x y : A} (p : x == y) (u v : B)
  → (PathOver (λ _ → B) p u v) == (u == v)
PathOver-rewr p u v = idp

-- HetEq (ap (λ _ → .B) p) u v != u == v of type Set
-- when checking that the expression idp has type
-- PathOver (λ _ → .B) p u v == (u == v)
```

**Comment by andreasabel** [comment]
It seems as this rewriting happens in a subterm, it is only triggered by full normalization, not by the head reduction during type checking.

**Comment by andreasabel** [comment]
When matching `ap (λ _ → B) p` against `idp` in the reduction of `HetEq (ap (λ _ → B) p) u v`,
[see `CompiledClause.Match`]

``` haskell
            -- get the reduced form of @e0@
            eb :: Blocked Elim <- do
                  case red of
                    Reduced b  -> return $ e0 <$ b
                    NotReduced -> unfoldCorecursionE e0
```

it only tries an `unfoldDefinition` on `ap (λ _ → B) p`, not a rewriting step:

``` haskell
unfoldCorecursion :: Term -> ReduceM (Blocked Term)
unfoldCorecursion v = do
  v <- instantiate' v
  case v of
    Def f es -> unfoldDefinitionE True unfoldCorecursion (Def f []) f es
    Shared{} -> fmap shared <$> unfoldCorecursion (ignoreSharing v) -- don't update when unfolding corecursion!
    _          -> reduceB' v
```

Thus, the rewrite rule is not triggered.  Needs some refactoring of the Reducer, sigh.

Changing the reducer is an extremely unpleasant task due to its complicated control-flow via the `keepGoing` continuation.  A first step is to rewrite it to direct style (no CPS), then changes are reasonably implementable.

**Comment by guillaumebrunerie** [comment]
Thanks, a workaround for now is to replace the definition of `HetEq` by the following "explicit" definition:

``` agda
postulate
  HetEq : {A B : Set} (e : A == B) (a : A) (b : B) → Set
  HetEq-rewr : {A : Set} (a b : A) → HetEq idp a b == (a == b)
  {-# REWRITE HetEq-rewr #-}
```
