### ISSUE TITLE
Agda-2.4.2.3.20150913 type check report differs from 2.4.2.3

### ISSUE THREAD

**Issue by mechvel** [agda/agda#1649]
Please, look into
http://www.botik.ru/pub/local/Mechveliani/agdaNotes/question-sep15-2015.zip
(see  README.agda  there).
1. Agda-2.4.2.3.20150913 issues different type check reports for the two variants of  FtMonoid1.agda
   described in README,
   and Agda-2.4.2.3 issues the same report of "unsolved metas".
   Which checker is more correct?
2. (this concerns both Agda versions)
   I wonder how to fix "unsolved metas" in the last file,
   for it looks like all implicit things are already named.

**Comment by asr** [comment]
It is difficult type-check your [MWE](https://en.wikipedia.org/wiki/Minimal_Working_Example) :-) in my computer with 6GB of memory. Please reduce your example.

**Comment by asr** [comment]
@mechvel I'm closing the issue.  Please reopen it if necessary.

**Comment by andreasabel** [comment]
I could reproduce Sergey's issue with 16GB of main memory.  Agda is deadly slow when all the modules from Sergey's case are loaded, so I could not debug it.  We need a smaller test case.

**Comment by mechvel** [comment]
Please, download it from the same place. It is now smaller.
With the candidate Agda, it suffices  5 Gb to type-check (probably, 2 Gb will be enough). 
Agda-2.4.2.3 will probably take at least 9 Gb.
I was silent because I tried (with pauses)  to get it to a real minimum, may be I shall do this, but I doubt.
Can you please, look into it now?

**Comment by mechvel** [comment]
Please see README.agda again  (the goal is now  Foo.agda).

**Comment by mechvel** [comment]
May be, interactive type check will show more precisely the location of unsolved thing.
I fail with the type check under emacs, because  ctrl-C ctrl-l  reports  now
"another command is currently in progress
(if a command has been aborted you may want to restart Agda)
".
And when an .agda  file is taken in emacs, no command is in progress.
In old Agda-s I did type check under emacs, and now, it looks like something is broken  in settings.

**Comment by mechvel** [comment]
Certain simplified version is on 
http://www.botik.ru/pub/local/Mechveliani/agdaNotes/question-sep21-2015.zip
(see README.agda).
There  Foo.agda    ends with

  foo : (ks : List Associated) → InjectiveOnList ks fromAsd  
  foo =  injective→injectiveOnList fromAsd  (\ {x} {y} → fromAsd-injective {x} {y})

  foo2 : (ks : List Associated) → InjectiveOnList ks fromAsd  
  foo2 ks =  injective→injectiveOnList fromAsd (\ {x} {y} → fromAsd-injective {x} {y}) ks

In the candidate Agda, 
foo  is type-checked,  foo2 is said as "unsolved metas".

Is this a bug ?

**Comment by asr** [comment]
> It is difficult for me to test this, because I wonder, how to switch
> between the two versions after the new one is installed
> (where reside old Agda and old library?).

You can use a different directory for installing each version of Agda and each version of the standard library.

So, if you need to use Agda version X:

``` bash
$ cd agda-version-x
$ cabal install

$ agda -i <path-standard-library-for-version-x> ...
```

Similar if you need to use Agda version Y.

**Comment by UlfNorell** [comment]
I would recommend using the --program-suffix flag to cabal install to keep
track of the different version of agda. You would then have agda-dev,
agda-2.4.2.2, agda-2.4.2.4-rc1, etc. For the standard library you can
simply keep separate copies of the library for each version.

/ Ulf

**Comment by asr** [comment]
> I would recommend using the --program-suffix flag to cabal install to keep track of the different version of agda. You would then have agda-dev, agda-2.4.2.2, agda-2.4.2.4-rc1, etc.

Without thinking in the standard library yet, how do you use the Emacs interface in this approach?

**Comment by asr** [comment]
> 1) The line  "debug (2)"  is local in the function which is later than 
>    "debug (1)".  And uncommenting returns the `unsolved' report for the
>    line "debug (1)".
>    This looks strange.

I could confirm this behaviour using Agda 2.4.2.4 RC1 (i.e. Agda 2.4.2.3.20150913). This is weird.

**Comment by asr** [comment]
> Certain simplified version is on
> http://www.botik.ru/pub/local/Mechveliani/agdaNotes/question-sep21-2015.zip
> (see README.agda).
> There Foo.agda ends with
> 
> foo : (ks : List Associated) → InjectiveOnList ks fromAsd
> 
> foo = injective→injectiveOnList fromAsd (\ {x} {y} → fromAsd-injective {x} {y})
> 
> foo2 : (ks : List Associated) → InjectiveOnList ks fromAsd
> 
> foo2 ks = injective→injectiveOnList fromAsd (\ {x} {y} → fromAsd-injective {x} {y}) ks
> 
> In the candidate Agda,
> foo is type-checked, foo2 is said as "unsolved metas".

I got the same problem with Agda 2.4.2.3.

Does using `fromAsd-Injective` instead of `fromAsd-injective` in `foo` and adding their implicit arguments fix the problem? That is, adding the implicit arguments in

``` agda
  foo : (ks : List Associated) → InjectiveOnList ks fromAsd          -- (1)
  foo =  injective→injectiveOnList fromAsd (fromAsd-Injective {{!!}} {{!!}})
```

fix the problem?

**Comment by UlfNorell** [comment]
On Wed, Sep 23, 2015 at 2:14 PM, Andrés Sicard-Ramírez <
notifications@github.com> wrote:

> I would recommend using the --program-suffix flag to cabal install to keep
> track of the different version of agda. You would then have agda-dev,
> agda-2.4.2.2, agda-2.4.2.4-rc1, etc.
> 
> Without thinking in the standard library yet, how do you use the Emacs
> interface in this approach?
> 
> agda-mode-x.y.z setup ?

I typically only run old versions of Agda from the command line, and if I
have to use the emacs mode I symlink agda-mode to agda-mode-x.y.z. There
might be better ways.

/ Ulf

**Comment by mechvel** [comment]
> Does in foo using fromAsd-Injective instead of fromAsd-injective and adding their implicit 
> arguments fix the problem? That is, adding the implicit arguments in
> 
>  foo : (ks : List Associated) → InjectiveOnList ks fromAsd          -- (1)
>  foo =  injective→injectiveOnList fromAsd (fromAsd-Injective {{!!}} {{!!}})
> 
>  fix the problem?

(1) How can it?  
 foo   is already type-checked. And  foo2  is not. And they differ only in naming an argument  
(f = g   --vs-->  f x = g x).

My question was:   does the type check fail on  foo2  present a bug in Agda ?

(2) I am stuck with  
http://www.botik.ru/pub/local/Mechveliani/agdaNotes/question-sep15-2015.zip

(5 Gb is sufficient to type-check it with the Candidate Agda).

My problem is:  how to fix "unsolved metas"  there in  Foo.agda (in the candidate Agda).
For it looks like all implicit things are already named.

So:  the last example with  foo -- foo2  pretends to report a bug  for Agda,
and (2) presents my problem, and a question on Agda.

**Comment by asr** [comment]
You shouldn't use the same issue for reporting different problems...

Let's talk about (2) and *Agda 2.4.2.3*:

I got unsolved metas for `foo2` and `foo` type-checks.

Replacing `fromAsd-injective` by `fromAsd-Injective` in `foo`, that is

```agda
foo : (ks : List Associated) → InjectiveOnList ks fromAsd          -- (1)
foo =  injective→injectiveOnList fromAsd fromAsd-Injective
```
I also got unsolved metas for `foo`.

Can you fix the unsolved metas in `foo` by adding the implicit arguments for `fromAsd-Injective` in

```agda
foo : (ks : List Associated) → InjectiveOnList ks fromAsd          -- (1)
foo =  injective→injectiveOnList fromAsd (fromAsd-Injective {{!!}} {{!!}})
```

?

**Comment by asr** [comment]
> So: the last example with foo -- foo2 pretends to report a bug for Agda,

Please open a new issue for this problem and let's use the current issue for (2).
