### ISSUE TITLE
Rewriting with only the type signature

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#1651]
Is it intended that the following works?

``` agda
{-# OPTIONS --rewriting #-}

data _==_ {A : Set} (a : A) : A → Set where
  idp : a == a
{-# BUILTIN REWRITE _==_ #-}

postulate
  A : Set
  a b : A

-- Works (!)
r : a == b
{-# REWRITE r #-}
r = idp
```

Maybe it should be forbidden to declare type signatures as rewrite rules (unless it’s a postulate).

**Comment by andreasabel** [comment]
You mean the user intended to add the rewrite rule AFTER the body has been checked?  Makes sense.
