### ISSUE TITLE
Rewrite rules are considered to hold in previous goals for C-c C-Space

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#1654]
Consider the following code:

``` agda
{-# OPTIONS --rewriting #-}

data _==_ {A : Set} (a : A) : A → Set where
  idp : a == a
{-# BUILTIN REWRITE _==_ #-}

postulate
  A : Set
  a b : A

r : a == b
r = ?
{-# REWRITE r #-}
```

If you try to give `idp` in the goal, it will be accepted (probably because it considers that `r` is already a rewrite rule), but then it won’t be accepted again by C-c C-l (of course).

**Comment by andreasabel** [comment]
This is a new instance of an old issue, #118.
