### ISSUE TITLE
Missing license?

### ISSUE THREAD

**Issue by nad** [agda/agda#1655]
Agda.Utils.Maybe.Strict contains the following text:

```
License   :  BSD-style (see the file LICENSE)
```

The file LICENSE contains the main Agda license, plus one license that only (?) applies to src/full/Agda/Utils/Parser/ReadP.hs. Does the latter license also apply to Agda.Utils.Maybe.Strict? In that case this should be documented, and otherwise the actual license should be included in LICENSE.

**Comment by andreasabel** [comment]
Let someone who cares about the licencing fix this.

**Comment by nad** [comment]
If we're using code that other people have written, then I think we should respect their wishes.

I've fixed this now.

**Comment by asr** [comment]
Fixed in master by https://github.com/agda/agda/commit/9fe82ed096ee8b10b2a3915922315a969a7807c8.

**Comment by asr** [comment]
@nad Please cherry-pick the commit https://github.com/agda/agda/commit/9fe82ed096ee8b10b2a3915922315a969a7807c8 into maint.

**Comment by andreasabel** [comment]
Just for the record: I emailed with Simon Meier that I want to copy his code and he told me "to do what I want" with the code of Maybe.Strict.  But I do not oppose proper handling of licences, I am just not motivated to do anything in this case.

**Comment by asr** [comment]
@nad This is the only open issue blocking the release of Agda 2.4.2.4. Please fix it.

**Comment by nad** [comment]
On 2015-09-24 16:52, Andrés Sicard-Ramírez wrote:

> @nad https://github.com/nad This is the only open issue blocking the
> release of Agda 2.4.2.4. Please fix it.

Fixed.

## 

/NAD

**Comment by asr** [comment]
Thanks!
