### ISSUE TITLE
Task: get rid of colors

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#1656]
They're not used for anything and it doesn't seem that they will be used for anything in the future, so we should get rid of them.

**Comment by andreasabel** [comment]
Did you give Guilhem a last chance to contradict?  At least, it should happen in a single patch so it can be reverted easily on a branch.

**Comment by UlfNorell** [comment]
There are other reasons for making a single patch (like why would you not?). I fully endorse getting rid of the colours. Nothing has been done with them in years so I don't think anyone can make any credible objections to their removal.
