### ISSUE TITLE
library-test broken on master

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#1657]
```
   Finished Data.Integer.Multiplication.Properties.
/home/abel/agda-schemes/std-lib/src/Data/Integer/Properties.agda:20,36-37
Ambiguous module name ℕ. It could refer to any one of
  Data.Nat.ℕ (datatype module)
  Data.Nat.Properties
(hint: Use C-c C-w (in Emacs) if you want to know why)
when scope checking the declaration
  open ℕ using (_*-mono_)
```

See
https://travis-ci.org/agda/agda/jobs/81081483

**Comment by andreasabel** [comment]
https://github.com/agda/agda/commit/e6cb239e9090e8a1798609f407bce4e3af36fbd3 to blame?!  Or the fix of #836?

**Comment by andreasabel** [comment]
I probably forgot to pull the std-lib.

**Comment by UlfNorell** [comment]
Someone, I don't know who, must have forgotten to push the changes to the standard library. They seem to be there now though.
