### ISSUE TITLE
Another instance of rewriting which doesn’t go through completely

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#1660]
The code below doesn’t compile but it should.
The term `P (λ x y → f (x , y))` should first be rewritten to `P (λ x y → g x y)` by definition of `f`, and then to `res` using the rewrite rule `rew`.
Asking for the normal form of `P (λ x y → f (x , y))` gives `P (λ x y → g x y)`, and then asking for the normal form of `P (λ x y → g x y)` gives `res`, so the normal form of `P (λ x y → f (x , y))` should be directly `res`.

``` agda
{-# OPTIONS --rewriting #-}

postulate
  _↦_ : {A : Set} → A → A → Set
  idr : {A : Set} {a : A} → a ↦ a
{-# BUILTIN REWRITE _↦_ #-}

record _×_ (A B : Set) : Set where
  constructor _,_
  field
    fst : A
    snd : B


postulate
  A B C : Set
  g : A → B → C

f : A × B → C
f (x , y) = g x y


postulate
  D : Set
  P : (A → B → C) → D
  res : D
  rew : P (λ x y → g x y) ↦ res
  {-# REWRITE rew #-}

test : P (λ x y → f (x , y)) ↦ res
test = idr
```

**Comment by andreasabel** [comment]
The problem here is that the rewrite rule is stored in its eta-contracted form, `P g --> res`.  To succeed matching against `P \ x y -> f (x , y)` we need to _head_-normalize (i.e. weak-head normalize under lambdas) to P `\ x y -> g x y` and then eta-contract to `P g`.

**Comment by guillaumebrunerie** [comment]
Thanks, I could temporarily fix it (in my local version) by changing the `instantiateFull'` to `normalise'` in the middle of the function `rewrite` (I don't know if there is a function doing only head normalization), but it does seem to affect performance.

**Comment by jespercockx** [comment]
Fixed by https://github.com/agda/agda/commit/1fada8f1ddddd2261bc63735295256e166dcd5d2 and https://github.com/agda/agda/commit/7226f8ef0ae7868b1db6a7024e45e45fb2ed3f30.
