### ISSUE TITLE
"Failed to solve the following constraints" on module application

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#1662]
```
data Unit : Set where
  ∗ : Unit

record R (x : Unit) : Set where
  inductive
  constructor r

module M₁
  (a : R ∗)
  where

module M₂
  (let --a : R ∗
       a = r)
  where

  Foo : Set₁
  Foo = Set

  open M₁ a
```

produces the following error:

```
Failed to solve the following constraints:
  [7] _6 := r [blocked on problem 8]
when checking the module application module _ = M₁ a
```

Either uncommenting the type signature for `a` or commenting out the definition of Foo causes the error to disappear.

**Comment by jespercockx** [comment]
We discussed this, and we came to the conclusion there should be a freezeMetas after checking a module telescope. Now metas are only frozen after the first definition in the module.

**Comment by UlfNorell** [comment]
See #1063.
