### ISSUE TITLE
Add Reflection primitives to expose precedence and fixity

### ISSUE THREAD

**Issue by wenkokke** [agda/agda#1664]
Currently, Agda's Reflection module does not expose precedence and fixity information. This makes it impossible to write e.g. a satisfactory pretty printer for the Term data-type.

**Comment by UlfNorell** [comment]
I suppose a sensible refactoring would be to change the `AGDADEFINITION` type to be closer to what we have internally: a top-level record that has some information common to all things (type, precedence/fixity, etc) and what's currently mapped to `AGDADEFINITION` inside.

**Comment by wenkokke** [comment]
I suppose the easiest way to implement a feature such as this would be to expose something like `primQNamePrec` and `primQNameFixity`. Do you foresee any problems with such a solution?

**Comment by UlfNorell** [comment]
I would probably go for

``` agda
data Associativity : Set where
  left-assoc right-assoc non-assoc : Associativity

data Precedence : Set where
  unrelated : Precedence
  related : Int → Precedence

data Fixity : Set where
  fixity : Associativity → Precedence → Fixity

getFixity : Name → TC Fixity
```

Having it in the TC monad rather than as a primitive means we don't have to worry about keeping the fixity information around at run-time.

**Comment by UlfNorell** [comment]
On the other hand, having it in the monad makes it hard to write a satisfactory pretty printer for `Term`s, so it would probably make more sense to make it pure and keep the fixity information around at runtime.

**Comment by UlfNorell** [comment]
`primQNameFixity` is now working at compile time and in the GHC backend.

I tried to add it to the UHC backend (8a0b4eb) but failed for mysterious reasons. (@phile314: Help!)

I didn't touch the JS backend because it represents names as strings (which is wrong since it doesn't match the compile-time semantics) and would require some moderate refactorings to support fixity.

**Comment by UlfNorell** [comment]
I reverted 8a0b4eb, since it made Travis fail (local tests passed without problems). It didn't do the right thing anyway...

**Comment by phile314** [comment]
The UHC Core target language internally uses integer Constructor Tags to distinguish different constructors. I assume the Agda UHC backend produces the wrong constructor tags. Will investigate.

**Comment by phile314** [comment]
This now works for the JS backend too. I am closing this issue, for the corresponding uhc backend issue see https://github.com/agda/agda-uhc/issues/6 .
