### ISSUE TITLE
Naming an argument leads to "unsolved metas"

### ISSUE THREAD

**Issue by mechvel** [agda/agda#1665]
This is on  Agda 2.4.2.3.20150913  (ghc-7.10.1).

Please, download it from 
http://www.botik.ru/pub/local/Mechveliani/agdaNotes/question-sep23-2015.zip

This is on  Agda 2.4.2.3.20150913  (ghc-7.10.1).

> unzip ...

Foo.agda  ends with

  foo : (ks : List Associated) → InjectiveOnList ks fromAsd          -- (1)  
  foo =  injective→injectiveOnList fromAsd (\ {x} {y} → fromAsd-injective {x} {y})

  foo2 : (ks : List Associated) → InjectiveOnList ks fromAsd         -- (2)  
  foo2 ks =  injective→injectiveOnList fromAsd  (\ {x} {y} → fromAsd-injective {x} {y}) ks

The command

> agda $agdaLibOpt +RTS -M4G -RTS Foo.agda

type-checks  foo  
and reports  "unsolved metas"  for  foo2.

Is this "unsolved metas" for  foo2  a bug in Agda ?

**Comment by mechvel** [comment]
Andrés Sicard-Ramírez writes

> You shouldn't use the same issue for reporting different problems...

This problem has appeared as a reduction of the initial  problem.
But all right. I have split the thing into the two new issues, and closed the initial one.

> Let's talk about (2) and Agda 2.4.2.3:

I report now on Agda 2.4.2.3.20150913.
But, all right, let us try  Agda 2.4.2.3, as you suggest.

> I got unsolved metas for foo2 and foo type-checks.

Well, I observe that   foo   is type-checked in my report, and  foo2  is not.

> Replacing fromAsd-injective by fromAsd-Injective in foo, that is
> 
> foo : (ks : List Associated) → InjectiveOnList ks fromAsd          -- (1)
> foo =  injective→injectiveOnList fromAsd fromAsd-Injective
> I also got unsolved metas for foo.

I also do -- if I add    fromAsd-Injective  to the `using' part in    "open  OfAssociated ..."
(fromAsd-Injective can be imported, but the initial report uses instead the local
 definition  fromAsd-injective, they are two different names, this is by occasion).

> Can you fix the unsolved metas in foo by adding the implicit arguments for fromAsd-Injective in
> 
> foo : (ks : List Associated) → InjectiveOnList ks fromAsd          -- (1)
> foo =  injective→injectiveOnList fromAsd (fromAsd-Injective {{!!}} {{!!}})
> ?

This way it is type-checked:
  foo =  injective→injectiveOnList fromAsd  (\ {x} {y} → fromAsd-Injective {x} {y})

And without the prefix  of   "\ {x} {y} →",  
I think, this must not type-check.
Because   module OfCongMap  has 
Injective : (A → B) → Set _  
Injective f =  {x y : A} → f x =b f y → x =a y  
,
Foo   `uses'  renaming (Injective to Injective-from)  from  OfCongMap,  where  A = Associated,
B = C,
and Foo declares  fromAsd-Injective : Injective-from fromAsd.                                

(I do not guess of what relation this your question may have to my report).

**Comment by asr** [comment]
The issue is not related to the release candidate so I'll rename it.

**Comment by UlfNorell** [comment]
Eta-expanding a definition can absolutely lead to unsolved metas for perfectly good reasons. Here's a simple example

``` agda
postulate
  T : Nat → Set
  g : (B : Nat → Set) → ∀ n → B n

foo : ∀ n → T n
foo = g _
-- Unique solution for meta: λ x → T x

foo₂ : ∀ n → T n
foo₂ n = g _ n
-- Two possible solutions:
--    (1)  λ x → T x
--    (2)  λ _ → T n
```

**Comment by asr** [comment]
Interesting...

Is there a similar situation in Haskell?

**Comment by UlfNorell** [comment]
Yes, but for a completely unrelated reason. In Haskell, the ["monomorphism restriction"](https://wiki.haskell.org/Monomorphism_restriction) means that a top-level value won't get an overloaded inferred type. For instance,

``` haskell
-- Inferred type: f1 :: (Show x) => x -> String
f1 x = show x

-- Type error: No instance for (Show a0)
f2 = \x -> show x
```
