### ISSUE TITLE
Proposal: syntax for local declarations compatible with copatterns

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#1667]
The current best practise (afaik) for having local declarations for a definition by copatterns is to use an anonymous module. For instance, given

``` agda
foo : ∀ Γ → R
proj₁ (foo Γ) = .. e Γ ..
proj₂ (foo Γ) = .. e Γ ..
```

you can write the following if you want a local definition for `e Γ`

``` agda
module _ Γ where
  private
    x : A
    x = e Γ
  foo : R
  proj₁ foo = .. x ..
  proj₂ foo = .. x ..
```

This is a bit clunky, so I offer the following syntactic sugar for consideration:

``` agda
foo Γ : R where
  x : A
  x = e Γ
  proj₁ foo = .. x ..
  proj₂ foo = .. x ..
```

This would of course not be restricted to definitions by copatterns. Getting this through the happy parser might be a challenge, but let's not worry about that for now.

**Comment by jespercockx** [comment]
See also https://github.com/agda/agda/issues/1542. This proposal would already take us halfway:

```agda
record Foo (A : Set) : Set where
  field
    foo : A

open Foo {{...}} public

record ⊤ : Set where
  constructor tt

instance Foo⊤ : Foo ⊤ where
  foo {{Foo⊤}} = tt

instance Foo× (A B : Set) {{_ : Foo A}} {{_ : Foo B}} : Foo (A × B) where
  foo {{Foo×}} = foo , foo
```

**Comment by andreasabel** [comment]
I have been thinking about the problem of rhs-repetitions in definitions by copatterns.  Having `where` declarations that stretch over several clauses would solve the problem.  Here is a possible syntax to indicate over which clauses a `where` block stretches. 

``` agda
foo : (x : A) -> R x
clauses
  fst (foo x) = ... e ...
  snd (foo x) = ... e ...
where
  e = ... x ...
```

In the where block you can refer to the common variables of its associated clauses that match in their types.

**Comment by UlfNorell** [comment]
I think that the "match in their types" criterion is a little vague and it's not obvious to me how it desugars. An advantage of my proposal is that variables have unique binding sites, which I feel is a very good thing to have.

**Comment by UlfNorell** [comment]
I feel that copattern lambdas gets you far enough here, that it's not worth adding some complicated new piece of syntax:
```agda
foo Γ = λ where .proj₁ → .. x ..
                .proj₂ → .. x ..
  where
    x = e Γ
```
