### ISSUE TITLE
CHANGELOG vs CHANGELOG.agda

### ISSUE THREAD

**Issue by mechvel** [agda/agda#1668]
In the distribution versions up to Agda 2.4.2.4,  changes are listed in the file  CHANGELOG.
May be it is better to rename it to   CHANGELOG.agda,  
because is contains specific UTF symbols to be shown under agda-mode.

**Comment by asr** [comment]
The CHANGELOG file is not an Agda file, so it shouldn't have the .agda extension.

Note that you can use the Agda mode in Emacs with non-Agda files (see http://stackoverflow.com/questions/25340687/use-agdas-input-method-in-other-emacs-mode/25341375).
