### ISSUE TITLE
Add proper Agda manual

### ISSUE THREAD

**Issue by phile314** [agda/agda#1669]
Currently Agda documentation is not the most easy to find. There is the CHANGELOG, but there it is not always clear if the documentation is still relevant for the current Agda release. Also it is structured by version and not by topic, which makes it harder than necessary to find all documentation belonging to a certain topic.

There is also some documentation in the Wiki, but there it's even less clear if the documentation still applies to the current Agda version.

I think we should do something like the GHC or Idris manual:
https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/
http://idris.readthedocs.org/en/latest/

This would also mean adding this documentation to the Agda repository, which would make sure that we always keep documentation & Agda version in sync.

I quite like the Idris documentation, and GHC seems to also switch to the ReStructuredText format (https://mail.haskell.org/pipermail/ghc-devs/2015-September/010001.html), so I think that may be a good option.

Obviously creating such a manual will take quite a lot of time. I think a reasonable plan would be to set up the infrastructure first, and then move over the documentation step-by-step over a longer time.

**Comment by UlfNorell** [comment]
I think that's a good idea. The Idris docs look nice, and one of the problems I have with writing stuff on the wiki is that it always looks terrible, which for me is very demotivating.

**Comment by asr** [comment]
I also think that is a good idea.

> This would also mean adding this documentation to the Agda repository,

This would be very convenient.

> which would make sure that we always keep documentation & Agda version in sync.

Keeping documentation in sync is not a trivial task...

> I quite like the Idris documentation, and GHC seems to also switch to the ReStructuredText format 

I'm unfamiliar with the ReStructuredText format. Has this format a strong support for Unicode?

**Comment by phile314** [comment]
So I just tried it out, and it works quite nicely. I just took some snippets from the Changelog, and made an incomplete (and outdated) chapter about reflection. Online version:

http://agda.readthedocs.org/en/latest/

**Comment by phile314** [comment]
Can someone with Admin permissions on the Agda repository please setup the commit hook for readthedocs.org? This makes sure that docs are automatically built when a commit is pushed.

Instructions see:
http://read-the-docs.readthedocs.org/en/latest/webhooks.html#github

**Comment by UlfNorell** [comment]
Done

**Comment by phile314** [comment]
Currently only I have admin access to the readthedocs.org Agda project. I would prefer to also give some other people admin access (@UlfNorell  @asr  ?).

You need to make a readthedocs.org account and tell me your username, and I will add you.

**Comment by asr** [comment]
My user name is asr.

**Comment by asr** [comment]
In addition to @UlfNorell, @nad and @andreasabel should also have admin access.

**Comment by andreasabel** [comment]
I am andreasabel on readthedocs.org now, please add me as admin.

**Comment by andreasabel** [comment]
Can I generate the documentation offline, to check it before pushing my commit?
We currently do not check the Agda code snippets in the documentation automatically, do we? That would be great, maybe we need another literate Agda backend.

**Comment by phile314** [comment]
You can generate the documentation offline, but the following packages need to be installed:
- Sphinx http://sphinx-doc.org/tutorial.html
  <pre>pip install Sphinx</pre>
- Sphinx RTD theme
  <pre>pip install sphinx_rtd_theme</pre>
- Latex

After that, doing a "make html" inside doc/user-manual should build the html documentation.

Currently, Agda code inside rst files is not checked. Creating a basic literate Agda mode for rst files should be easy. Another option is to create a Sphinx plugin, e.g. there is already a Sphinx plugin to test python snippets in rst files (http://sphinx-doc.org/ext/doctest.html).

**Comment by phile314** [comment]
Btw, currently I, asr and andreasabel have admin access on readthedocs.org.

**Comment by phile314** [comment]
We now have an Agda manual (http://agda.readthedocs.org/en/latest/), so I will close this. Mind you, the manual is still incomplete but coming along nicely. Please open a new issue if there is a concrete, actionable problem with the new manual.

**Comment by andreasabel** [comment]
Thanks @phile314 now I am trying to compile the docs.  I think the vanilla

```
sudo apt-get install python-pip
pip install Sphinx
pip install sphinx_rtd_theme
```

did not work.

```
sphinx-build: Command not found
```

I am googling for solutions...

**Comment by andreasabel** [comment]
Ok, back 17 minutes later:  I also need

```
sudo apt-get install dvipng
export PATH="$HOME/.local/bin:$PATH"
```

To install `pip`, I did this more complete procedure (but I don't know whether it was necessary in the end):

```
sudo apt-get install python-pip python-dev build-essential 
sudo pip install --upgrade pip 
sudo pip install --upgrade virtualenv 
```

**Comment by phile314** [comment]
I'm a bit surprised myself, but part of this is actually already documented :-) :
https://github.com/agda/agda/blob/master/HACKING#L314-L323

I also often find it useful to look at what travis does to install the dependencies.

**Comment by asr** [comment]
I just removed the unnecessary information:

```
The installation of sphinx-rtd-theme also installs Sphinx.
```
