### ISSUE TITLE
Question: zipWithAll

### ISSUE THREAD

**Issue by mechvel** [agda/agda#1673]
Has Standard library an analogue of zip for the pair   `xs ,  allPxs : All P xs`
?
I write  
`
  zipWithAll : ∀ {p} → {P : A → Set p} → (xs : List A) → All P xs → List (Σ A P)
  zipWithAll []           _                 =  []
  zipWithAll (x ∷ xs) (Px ∷a Pxs) =  (x , Px) ∷ zipWithAll xs Pxs
`

but wonder of whether Standard library has something related.

**Comment by asr** [comment]
Please use the Agda users mailing list for this kind of questions.
