### ISSUE TITLE
Internal error in src/full/Agda/Syntax/Internal.hs:339

### ISSUE THREAD

**Issue by asr** [agda/agda#1674]
After [fixing](https://github.com/agda/agda/commit/74ace569835205fd840c137e4985d4f18322cdf2) the compilation with GHC 7.8.4 and transformers 0.3.0.0, I got the error

``` bash
$ make install-bin CABAL_OPTS='--constraint=transformers==0.3.0.0'
$ make test
===================== Suite of successfull tests =====================
HigherOrderRewriting.agda
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/Syntax/Internal.hs:339
```

I wrote the instance in the above line for fixing https://github.com/agda/agda/issues/1573. I don't know what should I use instead of `__IMPOSSIBLE__`.

**Comment by UlfNorell** [comment]
It should be `mempty` (see the [`Monoid` instance](https://github.com/agda/agda/blob/master/src/full/Agda/Syntax/Internal.hs#L330-L334) right above your `Error` instance). The `ExceptT` transformer replaced the `Error` constraint from `ErrorT` by a `Monoid` constraint.

**Comment by asr** [comment]
Thanks!

**Comment by asr** [comment]
(I don't know why the Travis test [ghc-7.8.4-transformers-0.3.0.0](https://travis-ci.org/agda/agda/builds/83250001) didn't fail.)
