### ISSUE TITLE
latex-html-test fails in Travis

### ISSUE THREAD

**Issue by asr** [agda/agda#1675]
In master, the [latex-html-test](https://travis-ci.org/agda/agda/jobs/83292606) is failing in Travis. Sometimes just restarting the Travis job fix the issue but I don't know why.

Travis is using TeX Live 2012. I couldn't reproduce the issue using TeX Live 2015.

Could someone reproduce the issue by running `make latex-html-test` with TeX Live 2012, 2013 or 2014?

I need to know if it is necessary to upgrade the TeX Live version used by Travis.

**Comment by phile314** [comment]
XeTeX only produces the following output (edit: this is from the linked Travis build log above, not my local machine!):

<pre>
ret > ExitFailure (-9)
out > This is XeTeX, Version 3.1415926-2.4-0.9998 (TeX Live 2012/Debian)
out >  restricted \write18 enabled.
</pre>

This looks like XeTeX crashes for some reason, maybe out of memory?

**Comment by asr** [comment]
Thanks. I see that you are using TeX Live 2012.

Could someone reproduce the issue with TeX Live 2013 or 2014?

**Comment by phile314** [comment]
That was not what I meant, maybe I should have written that a bit more clear, sorry. The output in my previous message is the _full_ XeTeX output on travis.

If I execute it on my machine, all tests succeed. My TeX version:

<pre>
XeTeX 3.14159265-2.6-0.99991 (TeX Live 2014)
</pre>

But on travis, we don't get any latex error messages, just the crash with exit code -9. So XeTex crashes for some reason.

**Comment by asr** [comment]
Oh, I see. So it seems latex-html-test works with TeX Live 2014 and 2015.

Could someone reproduce the issue with TeX Live 2012 or 2013?

**Comment by asr** [comment]
> But on travis, we don't get any latex error messages,

@phile314 Since we are using a new test infrastructure, could we get the error messages from LaTeX? (see https://github.com/agda/agda/issues/1286).

**Comment by phile314** [comment]
There are no LaTeX error messages in the travis run. The test runner reports _all_ stdout and stderr output
if a test case fails. This is the _full_ XeLaTeX output on travis, including stdout and stderr:

<pre>
ret > ExitFailure (-9)
out > This is XeTeX, Version 3.1415926-2.4-0.9998 (TeX Live 2012/Debian)
out >  restricted \write18 enabled.
</pre>

**Comment by phile314** [comment]
So the tests pass the "-interaction=batchmode" flag to XeLaTeX. Seems that this causes that error messages from XeLaTeX are not printed to stdout/stderr.

**Comment by asr** [comment]
@phile314 I saw that you pushed https://github.com/agda/agda/commit/225d8d7de173e80e4ba807c07f984e4c3c4dd231. Please let's continue the discussion about the LaTeX error messages in https://github.com/agda/agda/issues/1286.

**Comment by asr** [comment]
The Travis build is green again, so I'm closing the issue.

**Comment by phile314** [comment]
And it is back again: https://travis-ci.org/agda/agda/jobs/83471586

The error message also contains the wrong log (see #1286).

**Comment by asr** [comment]
I don't want to use in Travis a recent version of TeX Live because usually the Linux distributions ship old versions of TeX Live.

Could someone reproduce the issue with TeX Live 2012 or 2013?

**Comment by phile314** [comment]
On travis, the error seems to randomly disappear and come back again. To me, that looks like it likely is a problem with not enough memory/disk-space/cpu or something like that, and depending on how busy travis is we run into these problems or not.

**Comment by phile314** [comment]
I'm not really sure what we should do about the Travis latex test failures. It seems that the tests work better if Travis is fast and more resources are available.

I'm pretty confident by now that this is a resource problem (memory, cpu, etc..), as the test errors come and go somewhat randomly. We already run all tests and the latex compilers in sequence, so they don't have to compete for memory. Disabling the latex tests is probably not a good idea, because then we don't notice when the Latex backend breaks.

Not sure if there is anything else we can do? Ideas?

**Comment by UlfNorell** [comment]
Do we really need to run latex on the generated code? Couldn't we just compare the tex file against a golden value and make do with that?

**Comment by phile314** [comment]
That sounds like a reasonable plan. Let's not run latex on Travis, but keep it enabled by default in the makefile for "make latex-test".

**Comment by asr** [comment]
The current Travis tests are

```
env:
  - TEST=non-require-stdlib
  - TEST=require-stdlib
  - TEST=latex-html-test
  - TEST=ghc-7.8.4-transformers-0.3.0.0
  - TEST=cpp
```

I used a different test for LaTeX (i.e. `TEST=latex-html-test`) because the installation of TeX Live 2012 in https://github.com/agda/agda/blob/master/.travis.yml#L140-L155 was _very_ expensive. I guess this installation is causing the random resource problem. Since we won't run LaTeX, the installation of TeX Live should be removed.

**Comment by np** [comment]
Same here, I don't see the point running latex all the time.

On 10/13/2015 12:05 PM, Ulf Norell wrote:

> Do we really need to run latex on the generated code? Couldn't we just
> compare the tex file against a golden value and make do with that?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/agda/agda/issues/1675#issuecomment-147669289.

## 

Best regards,
-- NP

**Comment by asr** [comment]
It seems that the LaTeX back-end needs (some part) of TeX Live installed:

``` bash
$ agda --latex Foo.lagda 
...
Checking if agda.sty is found by the LaTeX environment.

Calling: kpsewhich --path=latex agda.sty
kpsewhich: createProcess: runInteractiveProcess: exec: does not
exist (No such file or directory)
```

**Comment by asr** [comment]
Writing the patch...

**Comment by asr** [comment]
The new `latex-html-test` test only required 33 seconds (see https://travis-ci.org/agda/agda/jobs/85219901#L1225), so it isn't necessary to keep a separate test for the LaTeX back-end. I'll merge `latex-html-test` into the `non-require-stdlib` test.

**Comment by asr** [comment]
> That sounds like a reasonable plan. Let's not run latex on Travis, but keep it enabled by default in the makefile for "make latex-test".

@phile314, after removing `pdflatex` from my computer, by running `make latex-html-test` I would expect a fail in every file in `test/LaTeXAndHTML/succeed/` but I only found a fail in the following files:

```
$ make latex-html-test
all
  LaTeXAndHTML
    Issue982_LaTeX:                       FAIL
                                          Exception: pdflatex: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
    Links_LaTeX:                          FAIL
                                          Exception: pdflatex: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
    UnicodeDeclare_LaTeX:                 FAIL
                                          Exception: pdflatex: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

Why the other files didn't fail? I see this is related to the existence of a `.compile` file...

**Comment by phile314** [comment]
Yes, according to the code, that's whats happening. See https://github.com/agda/agda/blob/master/test/LaTeXAndHTML/Tests.hs#L93-L108 .

It was quite some time ago, but I think the .compile files were already used by the old Makefile-based test runner.

**Comment by asr** [comment]
I updated the OP  of #2392 pointed out this problem.
