### ISSUE TITLE
Missing universe level in a data definition.

### ISSUE THREAD

**Issue by effectfully** [agda/agda#1676]
This code is accepted:

```
open import Data.List

data All {a p} {A : Set a} (P : A → Set p) : List A → Set p where
  []  : All P []
  _∷_ : ∀ {x xs} (px : P x) (pxs : All P xs) → All P (x ∷ xs)
```

`All` lies in `Set p`, while it should be in `a ⊔ p`.

Agda version 2.4.3.

**Comment by Saizan** [comment]
The 'x' and 'xs' arguments are "forced" out of the constructor, so they do not need to count for universe checking.

You would get the same by defining All by recursion on the list.

**Comment by ma82** [comment]
I thought @andreasabel had shown this behaviour to be anticlassical...
May I ask you in which commit this was changed again?
Please also let me know if asking questions like this here is OK. :-)

**Comment by andreasabel** [comment]
Ah, yes, this is the place for discussion of a particular issue!  
You are probably referring to #1406.  This was fixed by a change to the unifier, not by categorically disallowing big forced indices.

**Comment by ma82** [comment]
Ah nice!
It's good to know that what I petitioned for in Tallinn does not necessarily contradict EM.
Thanks for the fix and for restoring this mechanism! :-)
