### ISSUE TITLE
`abstract' on `case'  is not type-checked

### ISSUE THREAD

**Issue by mechvel** [agda/agda#1677]
This is on  Agda 2.4.2.4. The  code 
http://www.botik.ru/pub/local/Mechveliani/agdaNotes/BugRep-oct4-2015.agda
presents a small example of an Agda program. The last function there is not type checked:

``` agda
abstract
  half-n=n-div-2 : ∀ n → half n ≡ (n div 2)
  half-n=n-div-2 n =
   case
       rN ≟ 0
   of \
   { (yes rN=0) → let  n=q*2 = PE.trans n=rN+q*2 (+cong₁ rN=0)
                  in
                  ≡begin  half n         ≡[ PE.cong half n=q*2 ]
                          half (q * 2)   ≡[ half-n*2 q ]
                          q              ≡[ q=n-div-2 ]
                          n div 2
                  ≡end
     ; ...
   }
   ...
```

If it is not under `abstract', then it is type checked.

**Comment by jespercockx** [comment]
Here is a minimal testcase of a definition that's accepted without `abstract` but rejected with it:

``` agda
abstract 
  foo : Set₁
  foo = f Set
    where
      AbstractSet₁ : Set₂
      AbstractSet₁ = Set₁
      f : Set₁ → AbstractSet₁
      f = λ { x → x }
```

**Comment by andreasabel** [comment]
The `AbstractDef` is not propagated into the extended lambda's `DefInfo`.  I guess no one tried abstract extended lambdas before.
