### ISSUE TITLE
{-# OPTIONS --safe #-} is not accepted

### ISSUE THREAD

**Issue by mietek** [agda/agda#1678]
```
Unrecognized option: --safe
```

Note the [Pragmas](http://wiki.portal.chalmers.se/agda/pmwiki.php?n=ReferenceManual.Pragmas) manual page lists `--safe` as one of the options that can be given in `.agda` files in the `{-# OPTIONS ... #-}` form.

**Comment by gallais** [comment]
Turns out #2442 was a duplicate of this one. Which we can now close.
