### ISSUE TITLE
`-_`  mixed with `_-_` in Agda-oct8-2015

### ISSUE THREAD

**Issue by mechvel** [agda/agda#1682]
This is on  Development Agda of october 8, 2015.

The below    `Injective  -_`
is not type-checked, probably, because Agda confuses  `-_`  with `_-_` imported from another module.  
If the import of (2) is removed, then it is type-checked.

`------------------------------------------------------------------------`
`module Bug-oct8-2015 where`
`open import Algebra using (CommutativeRing; module CommutativeRing)`
`open import Relation.Binary using (module DecSetoid)`
`open import Relation.Binary.PropositionalEquality as PE using (_≡_)`
`open import Data.Integer.Properties as IntProp using ()`
`open import Data.Integer as Int using (ℤ; -_)                             -- (1)`  
`--------------------------------------------------------------------`  
`open DecSetoid Int.decSetoid using () renaming (setoid to intSetoid)`
`intCRing = IntProp.commutativeRing`
`open CommutativeRing intCRing using (_-_)                            -- (2)`

`Injective : (ℤ → ℤ) → Set`
`Injective f =  ∀ {x y} → f x ≡ f y → x ≡ y`

`postulate`
`lemma1        :  (x : ℤ) → - (- x) ≡ x`
`neg-injective :  Injective -_                                              -- (3)`  
`-----------------------------------------------------------------------------------`

**Comment by mechvel** [comment]
The editor has deleted the indentation after `postulate`.
It deletes blanks inside the `...` construct.

**Comment by asr** [comment]
> The editor has deleted the indentation after postulate.

See the code examples in https://guides.github.com/features/mastering-markdown/ for fixing the problem.

**Comment by UlfNorell** [comment]
There is a new [operator section feature](https://github.com/agda/agda/blob/master/doc/release-notes/2-4-4.txt#L380), which means that `Injective -_` could mean either
  `_-_ Injective` or
  `Injective (-_)`
