### ISSUE TITLE
Unexpected Emacs error from the library management

### ISSUE THREAD

**Issue by asr** [agda/agda#1684]
An invalid path in `.agda/libraries` generates the following Emacs error when opening any Agda file:

```
File mode specification error: (error "The Agda mode's version (2.4.3) does not match that of agda (unknown).")
```

**Comment by andreas-roehler** [comment]
Got a related error, PR follows

Debugger entered--Lisp error: (error "The Agda mode’s version (2.4.3) does not match that of agda (2.3.2.2).")
  signal(error ("The Agda mode’s version (2.4.3) does not match that of agda (2.3.2.2)."))
  error("The Agda mode's version (%s) does not match that of %s (%s)." "2.4.3" "agda" "2.3.2.2")
  (if (equal version agda2-version) nil (error "The Agda mode's version (%s) does not match that of %s (%s)." agda2-version agda2-program-name (or version "unknown")))

**Comment by UlfNorell** [comment]
Looks like Emacs is finding the wrong Agda version. Check your paths (what does `which agda` tell you?). You can also specify the particular agda binary to run from `M-x customize-group agda2` and set `Agda Program Name`.

**Comment by andreas-roehler** [comment]
Does it make sense tying an Emacs mode with an executable? Editing some Agda stuff at computers where no Agda is installed - will that work?

**Comment by UlfNorell** [comment]
No. It's the executable that takes care of highlighting and the interactive editing/type checking stuff.

**Comment by andreas-roehler** [comment]
Hmm, reflected that WRT python-mode and finally abondoned that idea, because that would require some kind of validity of sources - which isn't garanted when in progress. Maybe things are different here?

**Comment by UlfNorell** [comment]
Yes. The emacs mode and the Agda executable are distributed together so there's no problem keeping them in sync.
