### ISSUE TITLE
Only comments fontified

### ISSUE THREAD

**Issue by andreas-roehler** [agda/agda#1686]
As comments are fontified, the basics seems to work regardless of the versions issue.

Bug might reside in agda2-highlight-setup, which does a setq only.
Missing function-call here?

Thanks,

Andreas

**Comment by UlfNorell** [comment]
What is the problem?

**Comment by andreas-roehler** [comment]
Maybe keywords should be fontified too?

**Comment by andreasabel** [comment]
This is most probably a configuration problem on your side.  I had this behavior sometimes, it was always resolved by proper installation of the agda emacs mode and restart of emacs.  

If your problem should persists, please come back and reopen, but include all the details about your system, like .emacs, pathes, installed Agda versions etc.
