### ISSUE TITLE
`--sharing ' causes errors

### ISSUE THREAD

**Issue by mechvel** [agda/agda#1688]
This is on  Development Agda of October 17, 2015.
The code is on 
    http://www.botik.ru/pub/local/Mechveliani/agdaNotes/costRep-oct8-2015.zip 
1. It presents inefficiency of the type checker: too much space is needed.
   But `agda`  is called without  --sharing.
2.  Then, I try to call it as 
                     `agda $agdaLibOpt +RTS -M,,, -RTS  --sharing  Goal.agda`  

And it reports an error for the  module   Nat0.agda   for the function  `≤0→≡`.
It is easy to change its implementation  (of 1 line) so that this function  is type-checked.
But then, the type checker runs into a certain  "Internal error".

The whole program has many modules, but unlucky  reports for "--sharing" concern (so far) only the first 3 modules needed for  Nat0.agda.

The whole program (Goal.agda) is type-checked without "--sharing".

Can you, please, debug  Agda on this example so that  Goal.agda  to be  type-checked under "--sharing" 
(wheh  `agda` is called from the command line) ?

**Comment by asr** [comment]
> But then, the type checker runs into a certain "Internal error".

Which is the internal error?

**Comment by mechvel** [comment]
```
  `> agda $agdaLibOpt --sharing Nat0.agda`
```

reports

---

...
Finished OfShow.
An internal error has occurred. Please report this as a bug.

## Location of the error: src/full/Agda/TypeChecking/CompiledClause/Match.hs:189

Here  Nat0.agda  imports only the files DPrelude.agda and OfShow.agda.

And this import is so trivial that we can remove it, with a slight change.
So that there will remain a reduced example consisting only of a small single module of
Nat0.agda.

But after this bug is fixed for Nat0, I doubt greatly of that the whole  Goal.agda will be type-checked
(under "--sharing").
This is why I suggest that you make this clear with Nat0, and then continue with other modules
(because without "--sharing" it is type-checked).

Need I to prepare a separate small example of  Nat0.agda ?

**Comment by asr** [comment]
> Need I to prepare a separate small example of Nat0.agda ?

Yes, a very very small example, please.

**Comment by asr** [comment]
> This is why I suggest that you make this clear with Nat0, and then continue with other modules

I don't understand. How can I do it?

**Comment by mechvel** [comment]
All right.
See a small example on Internal error in  Issue 1691.

**Comment by asr** [comment]
> Issue 1691.

Issue https://github.com/agda/agda/issues/1691. (You can use links for the issues).

**Comment by andreasabel** [comment]
After fixing #1691, the abovementioned Goal.agda passes with --sharing.  So this seems to be fixed.
