### ISSUE TITLE
stripRTS should presumably handle --RTS as well

### ISSUE THREAD

**Issue by nad** [agda/agda#1694]
I'm not quite sure what the purpose of `Agda.Interaction.Options.stripRTS` is (because RTS options are not returned by `getArgs`), but I guess that this function should handle the [`--RTS`](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/runtime-control.html#rts-opts-cmdline) flag, not just `+RTS` and `-RTS`.

**Comment by UlfNorell** [comment]
Aren't people passing RTS options using `agda-program-args`, or can you not do that?

**Comment by nad** [comment]
You can do that.

**Comment by andreasabel** [comment]
The linked docu page says: "If you absolutely positively want all the rest of the options in a command line to go to the program (and not the RTS), use a --RTS. "
So I am a bit puzzled by the implementation

``` hs
stripRTS ("--RTS" : argv) = stripRTS argv
```
1. Shouldn't that return the empty list instead?
2. Is it possible to test this in our current test framework?

**Comment by UlfNorell** [comment]
Oops you're right that it's wrong. It should be

``` haskell
stripRTS ("--RTS" : argv) = argv
```

I don't want to spend time testing this since it's a pointless flag to support.

**Comment by andreasabel** [comment]
I meant `... = []`.

**Comment by UlfNorell** [comment]
Yes I understood that, but that would be wrong. All the options after `--RTS` should go to the program according to the documentation. Your version would throw them all away.

**Comment by andreasabel** [comment]
Ah, my bad, I pasted the docu, but did not read it properly.  `--RTS` behaves very unlike other options, but makes sense.  Sorry.
