### ISSUE TITLE
Misleading error message: A postulate block can only contain type signatures or instance blocks

### ISSUE THREAD

**Issue by asr** [agda/agda#1698]
By writing `=` instead of `:` I got the following misleading error message:

``` agda
data Foo : Set where
  foo = Foo

-- Error message:
-- A postulate block can only contain type signatures or instance
-- blocks
```

**Comment by andreasabel** [comment]
On maint, this is a parse error.  The reason this is not directly a parse error on master is that

``` agda
data D : Set where
  instance
    d : D
```

is now legal syntax, thus, data declarations enjoy a more relaxed parsing.
