### ISSUE TITLE
Rewriting rule in parametrised module ignored

### ISSUE THREAD

**Issue by nad** [agda/agda#1705]
The following code is accepted by Agda 2.4.2.4, but not by the current development version:

```
{-# OPTIONS --rewriting #-}

module Bug where

infix 4 _≡_

data _≡_ {A : Set} (x : A) : A → Set where
  refl : x ≡ x

{-# BUILTIN REWRITE _≡_ #-}

postulate
  A  : Set
  id : A → A

module _ (x : A) where

  postulate
    r : id x ≡ x

  {-# REWRITE r #-}

broken : ∀ x → id x ≡ x
broken _ = refl
```

The code is accepted if the `REWRITE` pragma is moved out of the anonymous module.

The problem seems to have been introduced in the following series of commits: 6d13c91a3c05a81bef97b5947273d6e627d33260, 94373a2221bc1ee6e3b4a8a46b8201b5a4b6e267, ea642c139ad465159bc0a1020fb96679c0de75a7.

**Comment by UlfNorell** [comment]
If you want me to look at this you need a test case that doesn't use `REWRITE`.

**Comment by UlfNorell** [comment]
Also those commits are doing things with the library system, so I think git bisect is messing with you there.

**Comment by jespercockx** [comment]
This is actually a change in the semantics of rewrite rules in parametrized modules, see https://github.com/agda/agda/commit/e5b647be9462b4457846306c10703f28a9502ef0. If you want your test case to work, you should put the {-# REWRITE r #-} pragma outside of the module (i.e. unindent it).

**Comment by jespercockx** [comment]
I added the following to the release notes:
- The semantics of {-# REWRITE r #-} pragmas in parametrized modules has
  changed (see Issue 1652).
  
  Rewrite rules are no longer lifted to the top context. Instead, they now only
  apply to terms in (extensions of) the module context. If you want the old
  behaviour, you should put the {-# REWRITE r #-} pragma outside of the module
  (i.e. unindent it).

**Comment by nad** [comment]
> Also those commits are doing things with the library system, so I think git bisect is messing with you there.

Weird... The code was accepted in the commit immediately preceding this series of commits.

**Comment by nad** [comment]
Not so weird after all: The code was rejected, but not because of the change to the rewriting machinery, but because the (old) library management code complained about something.
