### ISSUE TITLE
istalling Development Agda of October 29

### ISSUE THREAD

**Issue by mechvel** [agda/agda#1708]
For  Development Agda of October 29 2015,
ghc-7.8.3, Debian Liux

> cabal update
> cabal install 

reports

---

...
[282 of 327] Compiling Agda.TypeChecking.Primitive ( src/full/Agda/TypeChecking/Primitive.hs, dist/build/Agda/TypeChecking/Primitive.o )

src/full/Agda/TypeChecking/Primitive.hs:71:21:
    Not in scope: ‘mempty’
    Perhaps you meant one of these:
      ‘empty’ (imported from Control.Applicative),
      ‘Map.empty’ (imported from Data.Map)

**Comment by UlfNorell** [comment]
Fixed by 23399f0.

**Comment by mechvel** [comment]
On Thu, 2015-10-29 at 04:53 -0700, Ulf Norell wrote:

> Fixed by 23399f0.
> 
> —
> Reply to this email directly or view it on GitHub.

What does this mean this 23399f0 ?
Please, where to download the fixed version from?

---

Sergei

**Comment by mechvel** [comment]
On Thu, 2015-10-29 at 04:53 -0700, Ulf Norell wrote:

> Fixed by 23399f0.
> 
> —
> Reply to this email directly or view it on GitHub.

All right, I have downloaded Development once more, and it is installed.

**Comment by UlfNorell** [comment]
It's a commit hash. If you look at the issue on github you can click the hash to view the commit. When we say an issue has been fixed it always means it's fixed in the master branch (and occasionally it is also fixed in the maintenance branch).
