### ISSUE TITLE
Feedback Request: Using the CPS'd version of WriterT

### ISSUE THREAD

**Issue by gallais** [agda/agda#1709]
Based on [this thread](https://mail.haskell.org/pipermail/libraries/2013-March/019528.html), it looks like we could benefit from using the CPS'd
version of `WriterT`. I have added a `Agda.Utils.CPSWriter` module
implementing this behaviour and have ported all the usages of `WriterT`
in the codebase to this new definition.

This looks faster on my computer but the stats obtained when running
`library-test` have been varying quite a bit during the afternoon so I'm
not sure whether it's worth merging in master.

Any opinions? It's all sitting on this branch:
https://github.com/agda/agda/tree/CPSWriter

**Comment by andreasabel** [comment]
I guess only a little of Agda's performance depends on `WriterT`, it is not used that much.  However, I have no objections against merging this, except:  Please do the refactoring on maint, and then merge it into master.  Otherwise, we get more an more divergence between these branches.

**Comment by UlfNorell** [comment]
I'm guessing that this branch no longer merges cleanly with `stable-2.5`... Might still be worth updating it and doing some performance measurements though.
