### ISSUE TITLE
With-clause error with nested copatterns and dependent records

### ISSUE THREAD

**Issue by vejkse** [agda/agda#1710]
I got a message with Agda 2.4.2.4:

```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/With.hs:250
```

I reduced the code as much as I could and got this useless but errorfull fragment:

```
record wrap (A : Set) : Set where
  field
    out : A
open wrap public

record MapsFrom (A : Set) : Set₁ where
  field
    cod : Set
    map : A → cod
open MapsFrom public

wrapped : (A : Set) → MapsFrom A
cod (wrapped A) = wrap A
out (map (wrapped A) a) with a
... | _ = a
```

There is no problem if
- I just put `= a` instead of the with-clause.
- or: I remove the `cod` field and set `map : A → wrap A`.
- or: The second clause of `wrapped` is replaced by 

```
map (wrapped A) a with a
... | _ = record { out = a }
```

**Comment by andreasabel** [comment]
Thanks for the report and the reduced test case!  
The cause of this bug was a misconception in the implementation of with clauses with copatterns.
