### ISSUE TITLE
2.4.3-candidate extra record module import

### ISSUE THREAD

**Issue by mechvel** [agda/agda#1717]
## The program

`module ... (upIR : UpIntegralRing) ...`
                  `(open OverIntegralRing-0 upIR _∣?_ using (GCDRing; GCD)`
                  `(gcdR : GCDRing)`
   where
   `open UpIntegralRing upIR using (...)`
   `open GCDRing gcdR using (gcd)`
##   ...

uses the record   GCDRing   as a module in the last line with  `open'.
Agda 2.4.2.4   reports that``module GCDRing``  is not found.
And   Agda 2.4.3-candidate of  October 20, 2015   type-checks this silently.

Is this a deliberate change in the language?

**Comment by UlfNorell** [comment]
Yes. See https://github.com/agda/agda/blob/master/doc/release-notes/2-4-4.txt#L346.

Also please don't use the issue tracker for questions better suited for the mailing list.
