### ISSUE TITLE
Rewriting and imports do not seem to go along very well

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#1719]
I’m having some strange issues with rewriting and I’m not really sure where they come from, but I finally managed to isolate something in a not-so-big example, and it seems related to imports.
Consider the following four files:

`Common.agda`

``` agda
{-# OPTIONS --without-K --rewriting #-}

ofType : ∀ {i} (A : Set i) → A → A
ofType A x = x

syntax ofType A x = x :> A

infixr 3 ofType

postulate
  _↦_ : ∀ {i} {A : Set i} → A → A → Set i
  idr : ∀ {i} {A : Set i} {a : A} → a ↦ a
{-# BUILTIN REWRITE _↦_ #-}

infixr 3 _==_

data _==_ {i} {A : Set i} (a : A) : A → Set i where
  idp : a == a

HetEq : ∀ {i} {A B : Set i} (e : A == B) (a : A) (b : B) → Set i
HetEq idp a b = (a == b)

PathOver : ∀ {i j} {A : Set i} (B : A → Set j)
  {x y : A} (p : x == y) (u : B x) (v : B y) → Set j
PathOver B idp u v = (u == v)

syntax PathOver B p u v =
  u == v [ B ↓ p ]

postulate
  PathOver-rewr : ∀ {i j} {A : Set i} {B : Set j} {x y : A} (p : x == y) (u v : B) →
    (PathOver (λ _ → B) p u v) ↦ (u == v)
  {-# REWRITE PathOver-rewr #-}

-- Note that this is both [ap] and [apd], as a [PathOver] in a constant family
-- reduces to the usual identity type.
ap : ∀ {i j} {A : Set i} {B : A → Set j} (f : (a : A) → B a) {x y : A}
  → (p : x == y) → PathOver B p (f x) (f y)
ap f idp = idp

postulate
  ap-cst : ∀ {i j} {A : Set i} {B : Set j} (b : B) {x y : A} (p : x == y) →
    ap (λ _ → b) p ↦ idp
  {-# REWRITE ap-cst #-}
```

`Spans.agda`

``` agda
{-# OPTIONS --without-K --rewriting #-}

open import Common

record Span : Set₁ where
  constructor span
  field
    A B C : Set
    f : C → A
    g : C → B
open Span public
```

`Pushouts.agda`

``` agda
{-# OPTIONS --without-K --rewriting #-}

open import Common
open import Spans

postulate
  Pushout : (d : Span) → Set
  left : {d : Span} → (Span.A d) → Pushout d
  right : {d : Span} → (Span.B d) → Pushout d
  glue : {d : Span} → (c : Span.C d) → left (Span.f d c) == right (Span.g d c) :> Pushout d

module _ {d : Span} {l} {P : Pushout d → Set l}
  (left* : (a : Span.A d) → P (left a))
  (right* : (b : Span.B d) → P (right b))
  (glue* : (c : Span.C d) → left* (Span.f d c) == right* (Span.g d c) [ P ↓ glue c ]) where

  postulate
    Pushout-elim : (x : Pushout d) → P x
    Pushout-left-β : (a : Span.A d) → Pushout-elim (left a) ↦ left* a
    {-# REWRITE Pushout-left-β #-}
    Pushout-right-β : (b : Span.B d) → Pushout-elim (right b) ↦ right* b
    {-# REWRITE Pushout-right-β #-}
    Pushout-glue-β : (c : Span.C d) → ap Pushout-elim (glue c) ↦ glue* c
    {-# REWRITE Pushout-glue-β #-}
```

`Test.agda`

``` agda
{-# OPTIONS --without-K --rewriting #-}

open import Common
open import Spans
open import Pushouts

module _ {d : Span} {l} {P : Pushout d → Set l}
  (left* : (a : Span.A d) → P (left a))
  (right* : (b : Span.B d) → P (right b))
  (glue* : (c : Span.C d) → left* (Span.f d c) == right* (Span.g d c) [ P ↓ glue c ]) where

  test : (a : Span.A d) → Pushout-elim {P = P} left* right* glue* (left a) ↦ left* a
  test a = {!idr!}
```

We notice the following:
- In the last line, C-u C-u C-t does not reduce the goal and the term `idr` is not accepted, whereas it should just be the application of `Pushout-left-β`
- If we inline `Test.agda` at the end of `Pushouts.agda`, then C-u C-u C-t shows the expected normal form (`left* a ↦ left* a`) and `idr` is accepted
- And the strangest thing is that if we inline `Spans.agda` at the beginning of `Pushouts.agda` (but do not inline `Test.agda`), then `idr` is accepted in the goal, but C-u C-u C-t does not show the expected normal form, it only shows `Pushout-elim left* right* glue* (left a) ↦ left* a`

**Comment by guillaumebrunerie** [comment]
Now that I’m thinking about it, it’s probably because `Pushout-left-β` is defined using the `Span` imported in `Pushouts.agda` and in `Test.agda` we reimport `Spans.agda` so Agda considers it as something different hence the rewrite rule does not apply. I’m still not really sure why C-u C-u C-t does not work when we inlining `Spans.agda`, though.

Is that the expected behaviour? It’s not very intuitive… On the other hand, maybe there are cases in which it would make more sense.

@andreasabel ?

**Comment by jespercockx** [comment]
Looking at the debug output, something very strange seems to be going on: in the rewrite rule `Pushout-left-β`, the variable `l` has CtxId 6, but when it is applied om the `Test.agda` file, the variable `right*` has the same CtxId 6. My code for rewrite rules in parametrized modules assumes that this is something that never happens. CtxId's should be unique _globally_, but apparently this is not the case when importing files. Maybe the stPostFreshCtxId gets reset to 0 at the start of each file? I don't know enough about the import system to be sure. @UlfNorell ?

**Comment by andreasabel** [comment]
Yes, it gets reset, as it is not part of the persistent state.
It might be difficult to get globally unique CtxIds, but you might be satisfied with less maybe?  Consider module C which imports A and B.  Say you run agda on A first, then restart agda on B, and finally restart agda on C.  Clearly, the imported modules will have overlapping CtxIds, maybe even with C.

**Comment by jespercockx** [comment]
Ok, I changed it so CtxId's only have to be unique on a per-file basis: https://github.com/agda/agda/commit/bd9766c32b76f761184ec18a14c6781d3c39efa9 Hopefully this is ok.
