### ISSUE TITLE
Bug with open public in parameterised module

### ISSUE THREAD

**Issue by asr** [agda/agda#1726]
From https://github.com/agda/agda/issues/892#issuecomment-161320255:

The new semantics would be (which strangely was the semantics of 2.4.2.2, but not 2.4.0 or 2.4.2.5):

``` agda
postulate
  U V W X Y Z : Set
  u : U
  v : V
  w : W
  x : X
  y : Y
  z : Z

module Top (u : U) where
  module A (v : V) where
    module M (w : W) where
      module O (x : X) where
  module B (y : Y) where
    open A public

module ShouldFail0 where
  module C = Top.B u y
  module D = C.M.O u v w x  -- u should not be there

module ShouldFail1 where
  module C (i g n o r i n g m e : Z) = Top.B u y
  module D = C.M.O u v w x  -- u should be 10*z

module ShouldFail2 where
  module C (y : Y) = Top.B u y
  module D = C.M.O u v w x -- u should be y

module ShouldSucceed where
  module C (z : Z) = Top.B u y
  module D = C.M.O z v w x -- Z !=< U of type Set
```

**Comment by asr** [comment]
This also was the semantics in Agda 2.4.2.3.

**Comment by asr** [comment]
`git bisect` points out that the issue was introduced by 9cf7dd6f2958df114525e926054ea4ab8a4f5539.

**Comment by andreasabel** [comment]
According to Ulf, the current behavior is what he intended with `open public`.  However, he agreed it can be confusing, and it will be changed to the "new semantics" I hinted at in the examples above.

Strictly speaking, this is a regression towards the intended behavior which was broken for at least 2.4.2.2 to 2.4.2.4.

This is a duplicate of what is left to do for #892.

**Comment by UlfNorell** [comment]
Here's an example showing that something is clearly not as it should be. The outer `f` gets applied to `u` in the module application, but the module `M` doesn't.

``` agda
postulate
  U V : Set
  u : U
  v : V

module Top (u : U) where
  module A where
    module M where
      postulate f : V
    postulate f : V
  module B where
    open A public

module C = Top.B u

ok : V
ok = C.f

not-ok : U → V
not-ok = C.M.f
```

**Comment by UlfNorell** [comment]
@WolframKahl Can you check your code with this change?

This might break people's code so we need an RC2 for this one (#1845).

**Comment by WolframKahl** [comment]
With Agda at  b0aaf8841badf5b843acba56582d6d53cb5ad083 pulled 2016-02-22,
compiled with ghc-7.10.3; with standard library pulled as sub-module at
f05064fc8e4afd1373bf532fe074dfe8a706049e 

```
 Finished Categoric.FinColimits.CoCone2.
/export/home/tmp/kahl/svn/A/RATH-Agda/trunk/AContext-2.1/Categoric/FinColimits/Pushout.lagda:226,20-232,20
Cannot add recursive display form for Categoric.FinColimits.CoCone2.CoCone2Univ.univMor
when checking the module application
module _
  = CoCone2Univ
    (isPO₂.universal {Z} {R′} {.Categoric.FinColimits.Pushout._._._.S″}
     (≈-sym .Categoric.FinColimits.Pushout._._._.R₁⨾S″≈F₂⨾R′))
```

This happens already with the versions in http://relmics.mcmaster.ca/RATH-Agda/AContext-2.1.tar.gz .

I am not consciously doing anything about display forms.

**Comment by UlfNorell** [comment]
The display form error is from #1644 (6374fee). It should only trigger when you use explicit `DISPLAY` pragmas so that looks like a bug. I filed #1870.

**Comment by UlfNorell** [comment]
@WolframKahl: fixed #1870.

**Comment by WolframKahl** [comment]
With Agda at 221c621e54e8a3f59c4c0b9df80a088530aa7e50, with the standard library still at f05064fc8e4afd1373bf532fe074dfe8a706049e but type-checked again, again  in http://relmics.mcmaster.ca/RATH-Agda/AContext-2.1.tar.gz:

```
$ time agda -v profile:7 +RTS -S -K256M -H11G -M11G -A1G -RTS -i . -i $(agdalib) Categoric/SGFunctor/Core.lagda
[...]
 Finished Categoric.SGFunctor.Setup.
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Monad/Signature.hs:211
[...]
real    0m8.958s
```

**Comment by UlfNorell** [comment]
I filed #1874.

**Comment by asr** [comment]
> This might break people's code so we need an RC2 for this one 

I couldn't find any related information to the fix of this issue in CHANGELOG. @UlfNorell could you add the missing information, please.

Blocking #1845.

**Comment by UlfNorell** [comment]
I'm not sure what you want me to write. Despite what the title previously said this was just a simple bug fix. We're not documenting every single bug fix in the CHANGELOG are we?

**Comment by asr** [comment]
> We're not documenting every single bug fix in the CHANGELOG are we?

No. I thought it was a regression, sorry.
