### ISSUE TITLE
To define a work-flow for releasing the new version

### ISSUE THREAD

**Issue by asr** [agda/agda#1727]
At the moment, we cannot release a new version from
- the maint-2.4.2 branch because there was a regression (#1701) which only was fixed in the master branch (because the reason given in https://github.com/agda/agda/issues/1701#issuecomment-161228673).
- the master branch because this branch is not "stable"

**Comment by asr** [comment]
Andreas' suggested (see https://github.com/agda/agda/issues/1701#issuecomment-161535123):

> I meant that if we cannot release master now as 2.4.4, we can pick some stable feature onto the maint branch and release it as 2.4.4, and continue developing master as 2.4.5 (which will then be released as 2.4.6 or 2.5.0).

**Comment by asr** [comment]
> we can pick some stable feature onto the maint branch and release it as 2.4.4

Both branches have diverged too much, so I think this option would be very difficult. I propose:
- Stop developing in the maint-2.4.2 branch
- Create the maint-2.4.4 branch from the master branch
  
  After seeing the issues with milestone 2.4.4, for releasing a new version we need:
  
  *\* To fix the regressions in #1679 and #1712
  
  *\* To remove the new `DISPLAY` feature due to #1644 
  
  *\* To remove the new `macro` feature due to #1538 
  
  We can keep the new `exact split` feature because the issue in #1383 doesn't seem a common user case.

**Comment by UlfNorell** [comment]
Neither #1644 or #1536 are critical bugs, certainly not sever enough to warrant removing `DISPLAY` and `macro` from a 2.4.4 release. Why don't we just release maintenance like usual, and make a proper 2.4.4 release later?

**Comment by asr** [comment]
> Neither #1644 or #1536 are critical bugs, certainly not sever enough to warrant removing DISPLAY and macro from a 2.4.4 release.

OK.

> Why don't we just release maintenance like usual...

Because #1701 is a _regression_ only fixed in master.

**Comment by UlfNorell** [comment]
The regression has already been released in 2.4.2.3 and 2.4.2.4 hasn't it, so I don't see a huge problem with leaving it also in 2.4.2.5? If that's totally unacceptable, I'm pretty sure it's a lot less work fixing #1701 also on maint than it is to start cutting features out of master.

**Comment by asr** [comment]
Unfortunately I find myself in an awkward position, I think we _shouldn't_ make a release with a regression known but I don't how to fix #1701. Could you fix this issue in maint?

**Comment by UlfNorell** [comment]
Unless Andreas fixes it first, I'll look at it on Wednesday.

**Comment by asr** [comment]
Great!

**Comment by WolframKahl** [comment]
Since #1701 was motivated from my code base: I am hoping for a release of 2.4.4, and I am highly  unlikely to use 2.4.2.5, since at least parts of my code already use new features.

**Comment by asr** [comment]
Since #1701 hopefully will be fixed on the maintenance branch, I'm closing this issue.
