### ISSUE TITLE
Broken installation of UHC with GHC 7.10.2 following Agda documentation

### ISSUE THREAD

**Issue by asr** [agda/agda#1728]
http://agda.readthedocs.org/en/latest/tools/compilers.html#uhc-backend says

> To install UHC, the following commands can be used:
> 
> ``` bash
> git clone https://github.com/UU-ComputerScience/uhc.git
> cd uhc
> git checkout 82149a515aa0cbc492d8aa3f1ff10850a9cbe8d8
> cd EHC
> ./configure
> make
> make install
> ```

By running `make` with GHC 7.10.2 I got the following error:

``` bash
$ make
[ 16 of 253] Compiling UHC.Compiler.Base.Debug ( UHC/Compiler/Base/Debug.hs, dist/build/UHC/Compiler/Base/Debug.o )

src/ehc/Base/Debug.chs:22:34:
    Ambiguous occurrence ‘showPP’
    It could refer to either ‘UHC.Compiler.Base.Debug.showPP’,
                             defined at src/ehc/Base/Debug.chs:19:1
                          or ‘UHC.Util.Pretty.showPP’,
                             imported from ‘UHC.Util.Pretty’ at UHC/Compiler/Base/Debug.hs:5:1-22

src/ehc/Base/Debug.chs:28:32:
    Ambiguous occurrence ‘showPP’
    It could refer to either ‘UHC.Compiler.Base.Debug.showPP’,
                             defined at src/ehc/Base/Debug.chs:19:1
                          or ‘UHC.Util.Pretty.showPP’,
                             imported from ‘UHC.Util.Pretty’ at UHC/Compiler/Base/Debug.hs:5:1-22
```

In https://github.com/agda/agda/issues/1475#issuecomment-129030996 Philipp wrote:

> UHC does not yet support GHC 7.10, but we are working on it:https://github.com/UU-ComputerScience/uhc/issues/54

Since https://github.com/UU-ComputerScience/uhc/issues/54 is fixed I don't if there is an error in the Agda documentation or in UHC.

**Comment by phile314** [comment]
UHC should work now with GHC 7.10. I will update the Agda UHC installation instructions.

**Comment by asr** [comment]
Note also that the documentation in  http://agda.readthedocs.org/en/latest/tools/compilers.html#uhc-backend says

> This version of Agda has been tested with UHC 1.1.9.0, using other UHC versions may cause problems

but running `./configure` says

``` bash
$ ./configure
...
Version : 1.1.9.1
```
