### ISSUE TITLE
Fixing an issue which requires to change the semantics and breaks people's code

### ISSUE THREAD

**Issue by asr** [agda/agda#1730]
Which should be the work-flow for fixing an issue which requires to change the semantics and breaks people's code?

In a previous issue I asked?

> Why #836 wasn't fixed in maint?

Ulf's answer was (https://github.com/agda/agda/issues/1701#issuecomment-161292012):

> The reason the fix to #836 isn't on maintenance is that it changes the semantics of using/hiding, and consequently breaks people's code.

I agree that changes in the semantics breaking people's code shouldn't be pushed in the maintenance branch, but these changes neither should be pushed in the master branch.

Let's suppose we have the current master and maint-2.4.2 branches. If the fix of issue XYZ requires changes in the semantics breaking people's code, I propose the following work-flow:
- Stop developing in the maint-2.4.2 branch
- Create a maint-2.4.4 branch from the maint-2.4.2 branch
- Bump the Agda version in maint-2.4.4 to 2.4.3
- Bump the Agda version in master to 2.4.5
- Fix the issue XYZ in the new maint-2.4.4 branch
- Continue fixing old a new issues in the maint-2.4.4 branch

In this way, the next release (Agda 2.4.4) would have the previous issues fixed in the maintenance branch + the fix to the issue XYZ. In addition, the cool and experimental features in master won't interfere with the next release.

Opinions?

**Comment by UlfNorell** [comment]
#836 is a bad example, since that was a request to change the semantics, and not a bug that required a change of semantics to fix. Even so, I guess it might make sense to give more room for semantics changes in the maintenance branch. My suggestion would be to change the policy for the version numbers as follows:

If current released version is Agda `2.X.Y.Z`, master will be `2.(X+1)`. Pure bug fixes are released as `2.X.Y.(Z+1)` as before, but minor semantics changes can be released on maintenance as `2.X.(Y+1)`. Master will then be released as `2.(X+1).1` with corresponding maintenance branches and then bumped to `2.(X+2)`.

So, for the current situation we would have
- master: version 2.5
- maint-2.4: version 2.4.2.5 with option to release 2.4.2.5 or 2.4.3

**Comment by asr** [comment]
I agree. I will change the versions and create the required branches later.

**Comment by asr** [comment]
Fixed by eeabf71 and ccd01fb.

**Comment by andreasabel** [comment]
Doesn't this fundamental change in versioning policy warrant a broader discussion among the developers!?

Maybe having the master at 2.5 is fine, but we should reserve the option to still release it as 2.4.X.

I do not know the implication of renaming a git branch, but a priori I am a bit hesitant to applaude. At least now I do not see the need for such a renaming, this would have sufficed at the next release (where developers will be on guard as major changes on the repo are expected).

**Comment by asr** [comment]
> Doesn't this fundamental change in versioning policy warrant a broader discussion among the developers!?

You are right, I should wait a broader discussion. As I previously mentioned, I agree with Ulf's proposal. 

Before renaming maint-2.4.2:
- I couldn't find any problem with renaming a branch and
- I created a safety copy of this branch in https://github.com/agda/agda/tree/safety-copy-of-maint-2.4.2.

**Comment by asr** [comment]
> Maybe having the master at 2.5 is fine, but we should reserve the option to still release it as 2.4.X.

Supposing that renaming a branch has not implications (I couldn't find any problem), we still have this option after "closing" the maint-2.4 branch.

**Comment by asr** [comment]
> At least now I do not see the need for such a renaming, this would have sufficed at the next release (where developers will be on guard as major changes on the repo are expected).

Since, as pointed out by Ulf, in maint-2.4 we have the option to release 2.4.2.5 or 2.4.3, I didn't see any reason for wait.
