### ISSUE TITLE
UHC back-end and Windows

### ISSUE THREAD

**Issue by asr** [agda/agda#1731]
From [UHC - WebHome](https://wiki.haskell.org/UHC), UHC runs under Windows (cygwin). Has someone tested the UHC back-end on Windows?

**Comment by phile314** [comment]
Neither the UHC backend nor UHC itself are currently supported on Windows.

I updated the user manual: https://github.com/agda/agda/commit/8a36de430c7d594a1af976b95f04ed034c4ca5b0
