### ISSUE TITLE
How to add a command-line option to a particular test suite?

### ISSUE THREAD

**Issue by asr** [agda/agda#1733]
I want to run the suite of successfully tests (i.e. `make succeed`) using Agda with the `--exact-split` command-line option. Where can I add this option?

**Comment by phile314** [comment]
Currently, that's only possible for the compiler-tests. Will fix this in a sec.

**Comment by phile314** [comment]
Fixed in commit https://github.com/agda/agda/commit/c3a8e9a205791f5eca3b8fd91febb95da3f117d9. You can now use the AGDA_ARGS env variable to pass additional arguments to Agda.

**Comment by asr** [comment]
Thanks!
