### ISSUE TITLE
Clause compiler skrews up with catch-alls

### ISSUE THREAD

**Issue by pigworker** [agda/agda#1734]
Here's some trouble, distilled down from an exercise I was preparing for my class. I'm using version 2.4.2.4 (so that I can compile programs which use copatterns).

I need a few basics: 

```
record One : Set where constructor <>

data Two : Set where tt ff : Two

record Sg (S : Set)(T : S -> Set) : Set where
  constructor _,_
  field
    fst : S
    snd : T fst
open Sg public

_+_ : Set -> Set -> Set
S + T = Sg Two \ { tt -> S ; ff -> T }
```

Now, I define the singletons over `Two`.

```
data Twoey : Two -> Set where
  ffey  : Twoey ff
  ttey  : Twoey tt
```

I'll be pattern matching on a later `Twoey` to learn about an earlier `Two`.

Next, I need some actual payload. Doesn't matter what.

```
postulate Thingy : Set
```

Sometimes we have payload and sometimes not. A Boolean value tells whether we have some.

```
ThingyIf : Two -> Set
ThingyIf tt = Thingy
ThingyIf ff = One
```

I should be able to extract payload, but not necessarily all the time.

```
thingy? : (b : Two) -> ThingyIf b -> Twoey b + One -> Thingy + One
thingy? .ff <> (tt , ffey) = ff , <>
thingy? .tt x  (tt , ttey) = tt , x
thingy? _ _ _ = ff , <>

oops = \ x -> thingy? tt x (tt , ttey)
```

The trouble is that, normalizing,

```
oops = \ x -> tt , <>  -- the <> should be the payload x
```

It's weird. I couldn't make it happen with `Twoey b` alone: I needed `Twoey b + One`.

I also checked that reordering the arguments made it go away. This...

```
thygni? : (b : Two) -> Twoey b + One -> ThingyIf b -> Thingy + One
thygni? .ff (tt , ffey) <> = ff , <>
thygni? .tt (tt , ttey) x  = tt , x
thygni? _ _ _ = ff , <>

spoo = \ x -> thygni? tt (tt , ttey) x
```

...gives

```
spoo = \ x -> tt , x
```

Moreover, replacing the gratuitous `<>` pattern by a variable...

```
hingy? : (b : Two) -> ThingyIf b -> Twoey b + One -> Thingy + One
hingy? .ff x  (tt , ffey) = ff , <>
hingy? .tt x  (tt , ttey) = tt , x
hingy? _ _ _ = ff , <>
```

...gives...

```
ops = \ x -> hingy? tt x (tt , ttey)
```

...and it has to be a variable: an `_` gives the same outcome as `<>`.

Sadly, I discovered this problem as part of a larger system, where a `Thingy` was a file handle. The compiled code segfaulted gloriously. But it looks like the problem starts before compilation.

I have a workaround, which is to use a postulated unit type in `ThingyIf`, preventing the excessive pattern matching. So I've stopped panicking. I'm afraid I can't really change the order of the arguments so easily, as it arises by instantiating a more general definition. I'd post the broader context, but it's a specimen solution to a "live" homework problem.

**Comment by andreasabel** [comment]
For cut-and-pasting an automated test case:

``` agda
infix 4 _≡_

data _≡_ {A : Set} (x : A) : A → Set where
  refl : x ≡ x

record One : Set where constructor <>

data Two : Set where tt ff : Two

record Sg (S : Set)(T : S -> Set) : Set where
  constructor _,_
  field
    fst : S
    snd : T fst
open Sg public

_+_ : Set -> Set -> Set
S + T = Sg Two \ { tt -> S ; ff -> T }

data Twoey : Two -> Set where
  ffey  : Twoey ff
  ttey  : Twoey tt

postulate Thingy : Set

ThingyIf : Two -> Set
ThingyIf tt = Thingy
ThingyIf ff = One

thingy? : (b : Two) -> ThingyIf b -> Twoey b + One -> Thingy + One
thingy? .ff <> (tt , ffey) = ff , <>
thingy? .tt x  (tt , ttey) = tt , x
thingy? _ _ _ = ff , <>

test1 : ∀ x → thingy? tt x (tt , ttey) ≡ tt , x
test1 = λ x → refl  -- should pass, but FAILS
```

This should succeed, but fails with:

``` agda
<> != x of type Thingy
when checking that the expression refl has type
thingy? tt x (tt , ttey) ≡ tt , x
```

Funnily, for 2.4.0 up to an including 2.4.2.3, we get another error:

```
ff != tt of type Two
when checking that the expression refl has type
thingy? tt x (tt , ttey) ≡ tt , x
```

**Comment by andreasabel** [comment]
The split tree for thingy? is correct:

```
split at 2
|
`- Issue1734.Sg._,_ -> split at 2
   |
   +- Issue1734.Two.tt -> split at 2
   |  |
   |  +- Issue1734.Twoey.ffey -> split at 1
   |  |  |
   |  |  `- Issue1734.One.<> -> done, 0 bindings
   |  |
   |  `- Issue1734.Twoey.ttey -> done, 1 bindings
   |
   `- Issue1734.Two.ff -> done, 3 bindings
```

But the clause compiler produces the following case tree:

``` haskell
thingy? b x p =
  case p of (y , z) ->
    case y of
      tt -> case x of
              <> -> case z of
                      ffey -> ff , <>
                      ttey -> tt , <>
              _  -> case z of
                      ttey -> tt , x
      _  -> ff , <>
```

It somehow deviates from the plan (the splittree) and decides to split on x before z.

**Comment by andreasabel** [comment]
The clause compiler discards the splittree at the point it encounters a catch-all, and then tries on its own and skrews up.  You can work around the problem by reducing the catch-alls.  E.g. the following works:

``` agda
thingy? .ff <> (tt , ffey) = ff , <>
thingy? .tt x  (tt , ttey) = tt , x
thingy? _   _  (ff , _   ) = ff , <>
```

I replaced the last `_` in the last line by `(ff , _)`.

**Comment by andreasabel** [comment]
The fix was not hard: just be more corageous and follow the split tree even when there are catch-alls and literals.  Seems to work.  I guess originally I just did not know what to do in these cases.

I speculate this test case never worked properly with the clause compiler.
