### ISSUE TITLE
how to run a hello world example

### ISSUE THREAD

**Issue by hoyeunglee** [agda/agda#1736]
I downloaded Agda tar file from wiki, and after unzip, I install with cabal install, then

i follow http://stackoverflow.com/questions/9692445/agda-as-a-programming-language

then installed https://github.com/agda/agda-stdlib

but after load it , it got error

Main> :l ag.agda
The name of the top level module does not match the file name. The
module hello should be defined in one of the following files:
  /home/martin/adga2/hello.agda
  /home/martin/adga2/hello.lagda
  /home/martin/.cabal/share/i386-linux-ghc-7.10.1/Agda-2.4.2.3/lib/prim/hello.agda
  /home/martin/.cabal/share/i386-linux-ghc-7.10.1/Agda-2.4.2.3/lib/prim/hello.lagda
Failed.

**Comment by UlfNorell** [comment]
This: **The name of the top level module does not match the file name.**
