### ISSUE TITLE
how to create a basic function and test it agda?

### ISSUE THREAD

**Issue by hoyeunglee** [agda/agda#1737]
i googled example below, it has many symbol such as all and arrow
is there a complete example about which library needed to be imported and how to 
test these basic function?

Rel : Set → Set₁
Rel X = X → X → Set

Decidable : ∀ {X} → Rel X → Set
Decidable R = ∀ x y → Either (R x y) (¬ (R x y))

record Equivalence {X} (_≈_ : Rel X) : Set₁ where
  field
    refl  : ∀ {x}     → x ≈ x
    sym   : ∀ {x y}   → x ≈ y → y ≈ x
    trans : ∀ {x y z} → x ≈ y → y ≈ z → x ≈ z

**Comment by UlfNorell** [comment]
Please post questions like this to the mailing list: https://lists.chalmers.se/mailman/listinfo/agda.
