### ISSUE TITLE
how to run a helloworld example 2

### ISSUE THREAD

**Issue by hoyeunglee** [agda/agda#1738]
last time i copy the wrong file in a hurry, actually i know the filename error, 

this error is the latest error 

The interactive mode is no longer supported. Don't complain if it doesn't work.
Main> :l ag.agda
Checking ag (/home/martin/adga2/ag.agda).
/home/martin/adga2/ag.agda:3,13-25
Failed to find source of module IO.Primitive in any of the
following locations:
  /home/martin/adga2/IO/Primitive.agda
  /home/martin/adga2/IO/Primitive.lagda
  /home/martin/.cabal/share/i386-linux-ghc-7.10.1/Agda-2.4.2.3/lib/prim/IO/Primitive.agda
  /home/martin/.cabal/share/i386-linux-ghc-7.10.1/Agda-2.4.2.3/lib/prim/IO/Primitive.lagda
when scope checking the declaration
  open import IO.Primitive using (IO; putStrLn)
Failed.
Main> 

module ag where

open import IO.Primitive using (IO; putStrLn)
open import Data.String using (toCostring; String)
open import Foreign.Haskell using (Unit)

main : IO Unit
main = putStrLn (toCostring "Hello, Agda!")

after install tar from wiki and install std-lib, confused about this example,

why use open import, but not import

which syntax is correct?

**Comment by UlfNorell** [comment]
Please post these kinds of questions to the mailing list. The issue tracker is for bug reports. (The problem in this case is that you're missing an include path to the standard library).
