### ISSUE TITLE
agda-mode for Atom editor : IOTCM communication problem?

### ISSUE THREAD

**Issue by sylvainnahas** [agda/agda#1739]
I am using Agda installed with:
$git clone
$cabal install

$ agda --version
Agda version 2.4.3

When loading an Agda file in the Atom editor and trying to "Load" the Agda mode, I get the error message: "Chose at most one: input file or --interaction"

The command sent by the Atom code to Agda (started with --interaction) is:
IOTCM "/home/sylvain/Documents/Agda/exos.agda" NonInteractive Direct ( Cmd_load "/home/sylvain/Documents/Agda/exos.agda" ["."] )

When I input the same command to Agda directly in a console, it outputs:
Agda2> IOTCM "/home/sylvain/Documents/Agda/exos.agda" NonInteractive Direct ( Cmd_load "/home/sylvain/Documents/Agda/exos.agda" ["."] )
(agda2-info-action "_Error_" "Choose at most one: input file or --interaction." nil)
(agda2-highlight-add-annotations)
(agda2-status-action "")

When I specify a path to a directory containing the agda-std library:
Agda2> IOTCM "/home/sylvain/Documents/Agda/exos.agda" NonInteractive Direct ( Cmd_load "/home/sylvain/Documents/Agda/exos.agda" [".", "/home/sylvain/workspace/agda-stdlib/src"] )
(agda2-info-action "_Error_" "only one input file allowed" nil)
(agda2-highlight-add-annotations)
(agda2-status-action "")

So, what's wrong with the IOTCM commands above? 
What should I do to fix it?

Thanks.

**Comment by banacorn** [comment]
Accidentally stumbled upon this thread ... Hi, I'm the developer of [agda-mode](https://github.com/banacorn/agda-mode) for Atom.

Looks like this is a problem of agda-mode, not Agda. 

The library management system in Agda 2.5 is different from the one in Agda 2.4, which would cause some trouble if you were using Agda 2.5 (fixed!)

But I can't seem to find the version of 2.4.3, did you mean 2.4.2.3?

It would be nice if you could try to install the latest version of agda-mode on Atom, and report this issue at [here](https://github.com/banacorn/agda-mode/issues) if the problem still persists. Thanks!

**Comment by asr** [comment]
@banacorn thanks for answering this issue. I suggest to add some information about the agda-mode for Atom in Agda's [README.md](https://github.com/agda/agda/blob/master/README.md) (via a pull request).
