### ISSUE TITLE
Rewrite on reflexive equality should not be a no-op

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#1740]
Sometimes you use `rewrite` to prove something about a function defined by `rewrite`. For instance,

``` agda
open import Common.Equality
open import Common.Bool

T : Bool → Set
T true  = Bool
T false = true ≡ false

foo : (a b : Bool) → a ≡ b → T a → T b
foo a b eq x rewrite eq = x

data _≅_ {A : Set} (x : A) : {B : Set} → B → Set where
  refl : x ≅ x

works : ∀ a b (eq : a ≡ b) (t : T a) → foo a b eq t ≅ t
works a b eq t rewrite eq = refl

fails : ∀ a (eq : a ≡ a) (t : T a) → foo a a eq t ≡ t
fails a eq t rewrite eq = refl
-- Error:
-- foo a a eq t | a | eq != t of type T a
-- when checking that the expression refl has type foo a a eq t ≡ t
```

With the change where wildcards no longer need to be dotted (#1605), the fix to #1110 (d6fcedb1) should be much simpler (just desugar rewrite to use a wildcard for the left-hand side).

**Comment by andreasabel** [comment]
The naive fix does not work, though, see test case for #1402:

``` agda
postulate eq : Set1 ≡ Set1

test : Set1
test rewrite eq = Set
```

This fails then with error:

```
Set₁ !=< .w of type Set₂
when checking that the expression Set has type .w
```

The generated auxiliary function is:

```
test-aux : (w : Set2) (eq : w ≡ w) → w
test-aux _ refl = Set
```

I guess we have to first fix #520, then we can fix this.

**Comment by UlfNorell** [comment]
I think it perfectly fine that the above example fails. We may or may not want to do something about #520, but I don't think it's relevant here.

**Comment by andreasabel** [comment]
Well, if I rewrite Set1 to Set1 I expect to get Set1 and not w.  At least the intuitive understanding of rewrite breaks here.

**Comment by UlfNorell** [comment]
Sure, but that's #520 and not this one. Think about it like this: if we hadn't already changed reflexive rewrite to be a no-op and I suggested I could fix #520 in the special case of `x ≡ x`, but it would make some useful rewriting of reflexive equations break, would you think that was a good idea.

**Comment by andreasabel** [comment]
After the fix of #520, reverting the fix of #1110 does not longer fix this (#1740).  However, the example is a bit weak, as we can directly match `eq` against `refl` to get where we want.

``` agda
fails : ∀ a (eq : a ≡ a) (t : T a) → foo a a eq t ≡ t
fails a refl t = refl
```

I need a more convincing example to get active.
Even if `eq` is not a function argument, but a more complicated term, a simple `with eq` and then matching on `refl` is sufficient.

I am closing this, please reopen if there is a better motivation for doing something.

**Comment by UlfNorell** [comment]
It's more the principle that you should be able to use the same recursion patterns when proving something about a function. Had `eq` not been a variable, you would've been forced to do a `with`. I'm curious, why will fixing #520 make this not work?

**Comment by andreasabel** [comment]
Only "rewrite refl" is still a no-op now. 

``` agda
  bla ps rewrite (eq : a == a) = rhs
```

is desugared as

``` agda
  bla ps with eq
  ... | refl = rhs
```
