### ISSUE TITLE
Please add support for haskell-src-exts 1.17.1

### ISSUE THREAD

**Issue by peti** [agda/agda#1741]
Stackage has update to the latest version of `haskell-src-exts`, which unfortunately breaks the current Agda build: http://packdeps.haskellers.com/feed?needle=exact:Agda

**Comment by peti** [comment]
FYI: A complete build log that shows the compiler error when trying to build with the latest version (ignoring the Cabal constraints) is available at http://hydra.cryp.to/build/1411721/log/raw.

**Comment by asr** [comment]
Thanks for reporting the problem which was pointed out in https://github.com/fpco/stackage/issues/981. We'll release a new version of Agda fixing this issue soon.

**Comment by asr** [comment]
FYI, the issue was fixed in the maint-2.4 branch three weeks ago (see #1721).

**Comment by asr** [comment]
Since I started the release procedure in #1742, I'm closing this issue.

**Comment by asr** [comment]
Agda 2.4.2.5 was released which supports haskell-src-exts 1.17.1. I'll make a pull request for including Agda in Stackage later.

**Comment by asr** [comment]
The pull request was merged in Stackage (https://github.com/fpco/stackage/commit/74bd03efc4156b84f070d3ce7e5d89e6f2ab2efd).

**Comment by asr** [comment]
Agda 2.4.2.5 is in the [Stackage Nightly 2015-12-21](https://www.stackage.org/nightly-2015-12-21).

**Comment by andreasabel** [comment]
Thanks.
