### ISSUE TITLE
Replacing CHANGELOG for a 'Release notes for X' section in the documentation

### ISSUE THREAD

**Issue by asr** [agda/agda#1744]
In the master branch, what about if we stop using the CHANGELOG file and we start adding the changes in a 'Release notes for X' section in the [documentation](http://agda.readthedocs.org/en/latest/index.html)? That is, we should move https://github.com/agda/agda/blob/master/doc/release-notes/2-5-1.txt into the documentation.

Since Hackage uses the CHANGELOG file, we can add a link to the release notes section and we can keep the old release notes in this file.

**Comment by asr** [comment]
I realised that keeping the old release notes in CHANGELOG has a drawback: We need grepping in _two_ files when searching for a change.

**Comment by andreasabel** [comment]
The documentation has to be kept up-to-date, meaning that any changes merged into master need to be followed by an update of the documentation.
However, I see this independent of the CHANGELOG or release notes, which gives you the diff on what is new.

**Comment by asr** [comment]
> The documentation has to be kept up-to-date, meaning that any changes merged into master need to be followed by an update of the documentation.

I agree, of course

> However, I see this independent of the CHANGELOG or release notes, which gives you the diff on what is new.

So do I.

My proposal is related to the CHANGELOG or release notes. I propose to follow the GHC approach. AFAIK, GHC doesn't use a CHANGELOG but a release notes section on its user manual, for example, [Release notes for version 7.10.1](https://downloads.haskell.org/~ghc/7.10.1/docs/html/users_guide/release-7-10-1.html).

**Comment by asr** [comment]
No enough discussion, so I'm closing the issue.
