### ISSUE TITLE
Agda Wiki: NixOS installation

### ISSUE THREAD

**Issue by sindikat** [agda/agda#1745]
On http://wiki.portal.chalmers.se/agda/agda.php?n=Main.Linux it says that command to install Agda in NixOS is:

```
nix-env -i Agda-executable
```

But this doesn't work anymore. I installed Agda using this command:

```
nix-env -f "<nixpkgs>" -iA haskellPackages.Agda
```

See also:
- https://github.com/NixOS/nixpkgs/pull/7172
- http://nixos.org/nixpkgs/manual/#users-guide-to-the-haskell-infrastructure

**Comment by phile314** [comment]
Wiki links to user manual now.
