### ISSUE TITLE
Error when using two positional pragmas before the `mutual` keyword

### ISSUE THREAD

**Issue by asr** [agda/agda#1755]
I started to think in the implementation of the `{-# NON_POSITIVITY_CHECK #-}` pragma (#1614). 

At the moment, Agda has the following positional (i.e. they have no associated an entity when they are used) pragmas: `{-# NON_TERMINATING #-}`,  `{-# TERMINATING #-}` and `{-# CATCHALL #-}`.

The positional pragmas are handled by the [nice](https://github.com/agda/agda/blob/master/src/full/Agda/Syntax/Concrete/Definitions.hs#L584-L687) function. I know I can add new equations to this function for handling the `{-# NON_POSITIVITY_CHECK #-}` pragma, however I think the approach of using positional pragmas is not easily scalable. For example, how many equations we would need to add to the `nice` function if we add a new positional pragma (e.g. #1195) applicable to the same kind of entity that an existing positional pragma?

In consequence, I propose to eliminate some positional pragmas, that is, I propose the following replaces:

`{-# NON_TERMINATING #-}` -> `{-# NON_TERMINATING name #-}`

`{-# TERMINATING #-}` -> `{-# TERMINATING name #-}`

`{-# NON_POSITIVITY_CHECK #-}` -> `{-# NON_POSITIVITY_CHECK name #-}`

I didn't include the `{-# CATCHALL #-}` pragma in my proposal because this pragma is applied on clauses which have no a name.

 Comments?

**Comment by UlfNorell** [comment]
I agree that it's a little strange that we have both named and positional pragmas, but from a user point of view I prefer the positional ones. Also, you couldn't implement the pragmas above in the same way as other named pragmas, since they affect the checking of a definition. You would have to do something like the handling of fixity declarations, so I don't think it would actually simplify anything.

I think a much better solution would be to refactor the `nice` function to make it easier to add new positional pragmas.

**Comment by asr** [comment]
> ...but from a user point of view I prefer the positional ones

Just out curiosity, has GHC some positional pragma? (I'm considering the `LANGUAGE` and the `OPTIONS_GHC` pragmas as named ones)

**Comment by asr** [comment]
> Just out curiosity, has GHC some positional pragma?

Yes. For example the `{-# UNPACK #-}` and `{-# NOUNPACK #-}` pragmas.

**Comment by asr** [comment]
After adding the `NO_POSITIVITY_CHECK` pragma in #1614, the following example should type-check:

``` agda
{-# NO_POSITIVITY_CHECK #-}
{-# NON_TERMINATING #-}
mutual
  data D : Set where
    lam : (D → D) → D

  f : Set
  f = f
```

Right now, we get the following error:

``` bash
No positivity checking pragmas can only precede a mutual block or a
data definition.
```

I'll fix 'manually' the issue, but we need the refactoring suggested by Ulf: 

> I think a much better solution would be to refactor the nice function to make it easier to add new positional pragmas.
