### ISSUE TITLE
LINE and MEASURE pragmas

### ISSUE THREAD

**Issue by asr** [agda/agda#1756]
Will be the [LINE](https://github.com/agda/agda/blob/master/src/full/Agda/Syntax/Parser/Lexer.x#L112) and [MEASURE](https://github.com/agda/agda/blob/master/src/full/Agda/Syntax/Parser/Lexer.x#L110) pragmas used for something?

**Comment by UlfNorell** [comment]
I guess they're not used at the moment (@andreasabel?). `FILE` and `LINE` pragmas would maybe be nice to have for generated code, although they might mess up the emacs mode.

**Comment by andreasabel** [comment]
MEASURE is work-in-progress.
