### ISSUE TITLE
Hiding of record parameters leads to hiding mismatch in checkInternal

### ISSUE THREAD

**Issue by mechvel** [agda/agda#1759]
This is on the  Development Agda type checker  of December 18, 2015,
                      ghc-7.8.3.

Please, download the archive from
http://www.botik.ru/pub/local/Mechveliani/agdaNotes/bug-dec28-2015.zip 
and see  README.agda.
(I have reduced the example many times, but probably it can be reduced several times further).

FtMonoid.agda  presents a certain combination of the two parametric modules and nested records in them.

(1)
`> agda $agdaLibOpt FtMonoid.agda`

reports

```
  /home/mechvel/doconA/0.04/reports/dec25-2015/FtMonoid.agda:150,15-40
Expected a visible argument, but found a hidden argument
when checking that the expression `UpMonoid.ε∙ asdUpMonoid Q` has
type 
`asd ε ∙`' Monoid-pack.Multiplicity.quot
(UFM-id.mtForPrime (asd a) (asd p) (toAsdFactorization a ft-a)
 `(proj₁ (IsPrime←→IsPrime-asd p) prime-p))`
='
Monoid-pack.Multiplicity.quot
(UFM-id.mtForPrime (asd a) (asd p) (toAsdFactorization a ft-a)
 `(proj₁ (IsPrime←→IsPrime-asd p) prime-p))`
```

But the operation    `Monoid.ε∙ M  (same as  UpMonoid.ε∙ upM)`
gives a witness for
                                          `ε ∙ x ≈ x`
for any  x  in any Monoid.
So that the result must not depend on the origin of Q in the equation e1.

And Agda makes difference:  if in  mtForPrime  of previous module the value    b
is defined as depending on  ft-a
(for example, if it checks the emptiness of the list),
then a strange error report appears for  e1  in the end of the second module.

If instead  b  is defined as  b = a,  or  `b = ε`,

  Or if  it is put   mStruc' = anything   (so that Q occurs `anything'),

then FtMonoid.agda is type-checked.

Is this a bug in Agda ?
See also the two minor questions in  README.agda

**Comment by mechvel** [comment]
I am almost sure that this is a bug in Agda. So, I have decided to report to the bug tracker.
If it is my error, then I am sorry.

**Comment by asr** [comment]
> Expected a visible argument, but found a hidden argument
> when checking that the expression

Isn't this error related to the error in #1666?

P.S. You can use the [markdown](https://guides.github.com/features/mastering-markdown/) language when reporting issues.

**Comment by mechvel** [comment]
Currently I run Agda only from the command line
(because I fail with setting adda-mode for emacs).
As I recall, the matter with #1666 was that a certain case of  "unsolved metas" was shown in emacs but was not reported by the command line type checker.

Probably, this effect itself is a bug. Is not it?
Can the Agda developers make the command line checker  to agree with the interactive checker? 
(to report all things that are hightlighted as "unsolved metas"  in the interactive checker).

**Comment by asr** [comment]
> Currently I run Agda only from the command line
> (because I fail with setting adda-mode for emacs).

I suggest to ask in the mailing list about this problem. Maybe someone using the master branch of the developing version can help you.

**Comment by andreasabel** [comment]
``` agda
        A : Associated
        A = 
...
        Q : Associated
        Q = {! Multiplicity'.quot mStruc' !}

        e0 :  (asd ε) ∙' A =' A
        e0 =  UpMonoid.ε∙ asdUpMonoid A

        e1 :  (asd ε) ∙' Q  =' Q
        e1 =  UpMonoid.ε∙ asdUpMonoid Q    -- ** here is the error report
```

If `Q` remains a meta, `e1` is accepted, otherwise not.
I'd say this is a bug.

**Comment by mechvel** [comment]
Thanks for looking into this!
This bug is going to stuck my project.

**Comment by mechvel** [comment]
asr   commented  Dec 29, 2015

> >   Expected a visible argument, but found a hidden argument
> >  when checking that the expression
> 
> Isn't this error related to the error in #1666?

It occurs that it is not related. Because the interactive Agda does not highlight anything before the reported place.
It looks like a real bug.

**Comment by andreasabel** [comment]
Here is a an analysis of the situation:

``` agda
-- With hidden parameter, things work

module Works0 {A : Set} where

  postulate
    P : (a : A) → Set

  record Works (a : A) : Set where

    f : P a → Set
    f p with p
    ... | _ = A

-- With visible parameter, the error is triggered
-- because it is turned hidden inside the record section

module Fails (A : Set) where

  postulate
    P : (a : A) → Set

  -- Modules do not touch visibility of parameters, so things work.
  module Works (a : A) where

    f : P a → Set
    f p with p
    ... | _ = A

  -- Records have some magic to make record parameters hidden
  -- in record section.
  -- This leads to an error in @checkInternal@.

  record Fails (a : A) : Set where

    f : P a → Set
    f p with p
    ... | _ = A

-- Expected a visible argument, but found a hidden argument
-- when checking that the type (w p : P a) → Set of the
-- generated with function is well-formed
```

**Comment by mechvel** [comment]
This is strange that this effect has not been discussed years ago.
Because probably people often write modules similar to

``` agda
module Fails (A : Set) where
  postulate
     P : (a : A) → Set

  record Fails (a : A) : Set where
     f : P a → Set
     f p with p
     ... | _ = A
```

I understand your analysis so that the type checker needs to be somehow fixed in this point.

**Comment by andreasabel** [comment]
Working on a fix of both #1815 and this issue, I realize that this also needs to work:

``` agda
module _ (A : Set) where

  record R : Set where
    postulate
      P : (a : A) → Set

  -- Records have some magic to make record parameters hidden
  -- in record section.
  -- This leads to an error in @checkInternal@.
  -- Also the parent parameters should be hidden in the record section.

  record Fails (a : A) : Set where

    T = (w p : R.P _ a) → Set -- well-formed

    f : R.P _ a → Set
    f p with p
    ... | _ = A

-- ERROR:
-- Expected a hidden argument, but found a visible argument
-- when checking that the type (w p : R.P _ a) → Set of the generated
-- with function is well-formed
```

**Comment by mechvel** [comment]
My large program is type-checked by  Development Agda of January 19, 2016 
(this needs 17 Gb).
And it  has parameterized modules and records of various kinds, sometimes parameters are hidden with `{}'. 
On the other hand, I do not know, may be this is a bug that it is type-checked. 
Also I do not understand these record`magic' matters.
If the language developers formulate some clear restriction on the record parameter usage, then the programmers could see of whether they are able to express what they need, and discuss the subject.
For example, you restricted the usage of `with' as related to variables, and the programmers  have accomodated to this.
Probably the above example needs first to be discussed between several experts in the area of dependent types.

**Comment by mechvel** [comment]
Concerning

  `T = (w p : R.P _ a) → Set` 

:

`R.P`  is declared as having 1 argument, and  `R.P _ a`

gives  it two arguments. Am I missing something?

**Comment by andreasabel** [comment]
Since `P` is declared in a `record`, it gets as additional argument the record value.  In this case the record value is `_`, which eta-expands into `record{}`.  Note that `R` has no fields.

**Comment by UlfNorell** [comment]
@WolframKahl This fix might affect some of your code.

``` agda
module _ (A : Set) where
  record R (B : Set) : Set where
-- Before:
-- module M = R Nat {B = Bool} -- explicit A
-- Now:
module M = R {A = Nat} {B = Bool}
```

**Comment by UlfNorell** [comment]
cc #1845

**Comment by WolframKahl** [comment]
@UlfNorell: Thanks! Indeed I somewhere had the comment

```
Since we want the |base| parameter to be explicit for the |record| types,
but implicit for the associated modules,
we cannot just re-export the modules directly from |InUSLCat|.
```

followed by re-defining those modules with implicit parameters ─ I don't have to jump through these hoops anymore, thank you!
(Since I had mostly avoided defining records inside parameterised modules for that reason, the changes required were limited to 64 modules, involving fewer than 20 record types.)
