### ISSUE TITLE
UHC, uhc-light and GHC <> 7.10.*

### ISSUE THREAD

**Issue by asr** [agda/agda#1761]
I installed UHC using GHC 7.10.3. After switching to GHC 7.8.4, I got the following error:

``` bash
$ make install-bin
...
Preprocessing library uhc-light-1.1.9.1...
[ 76 of 248] Compiling UHC.Light.Compiler.Core ( src/UHC/Light/Compiler/Core.hs, dist-2.5/build/UHC/Light/Compiler/Core.o )

src/UHC/Light/Compiler/Core.hs:435:58:
    Overlapping instances for AppLike Ty Ty
      arising from a use of ‘appCon’
    Matching instances:
      instance AppLike Ty Ty
        -- Defined at src/UHC/Light/Compiler/Ty.hs:715:31
      instance AbstractCore
                 e m b bound boundmeta bcat mbind t p pr pf a =>
               AppLike e boundmeta
        -- Defined at src/ehc/AbstractCore.chs:323:32
    In the second argument of ‘($)’, namely
      ‘appCon (ehcOptBuiltin o ehbnDataBool)’
    In the expression:
      acoreTy2ty o $ appCon (ehcOptBuiltin o ehbnDataBool)
    In an equation for ‘acoreTyBool’:
        acoreTyBool o
          = acoreTy2ty o $ appCon (ehcOptBuiltin o ehbnDataBool)
Failed to install uhc-light-1.1.9.1
```

Agda shouldn't install uhc-light if GHC < 7.10.*.

**Comment by asr** [comment]
Thanks!

**Comment by asr** [comment]
@phile314 Please take ownership of this issue.

**Comment by phile314** [comment]
Just to be clear, this is a closed issue and I'm not going to do anything about it.

@asr By the way, you can assign issues to anyone by clicking on the small cog icon, you don't need to ask.

**Comment by asr** [comment]
> By the way, you can assign issues to anyone by clicking on the small cog icon, you don't need to ask.

Since we don't get notifications related to the issues assigned, we can 

i) assign the issue and notify the person or
ii) ask the person to take ownership of this issue.

I follow ii).

**Comment by asr** [comment]
I have a similar issue to the original one when using GHC 8.0.1 RC 2.
