### ISSUE TITLE
Positivity check: Renaming pragma

### ISSUE THREAD

**Issue by asr** [agda/agda#1767]
I want to make the following renaming:

`--no-positivity-check` -> `--no-strict-positivity-check` (in master)

`NO_POSITIVITY_CHECK` -> `NO_STRICT_POSITIVITY_CHECK` (in master and maint-2.4)

Motivation: I would like to add an option for experimenting with positive but not-strictly positive types in the future.

Any objection?

**Comment by andreasabel** [comment]
I think such a renaming has to wait until there is truly need for it.
Also, I think `NO_POSITIVITY_CHECK` is already on the long side and should not get longer.  One could think of a shorter pragma `STRICTLY_POSITIVE`, analogously to `TERMINATING`.

**Comment by asr** [comment]
> Also, I think NO_POSITIVITY_CHECK is already on the long side and should not get longer. One could think of a shorter pragma STRICTLY_POSITIVE, analogously to TERMINATING.

I agree with the shorter pragma.

**Comment by andreasabel** [comment]
Currently, we do not need to rename anything or?  NO_POSITIVITY_CHECK will simply turn off any check, be it positivity or strict positivity.  A pragma like STRICTLY_POSITIVE should only be used on things that are strictly positive, but Agda's checker fails to see it.  But there might be proper negative things on which a pragma like NO_POSTIVITY_CHECK is more meaningful.

In contrast to TERMINATING and NON_TERMINATING, which have different semantics, pragmas like POSITIVE, STRICTLY_POSITIVE, NON_POSITIVE would all just be aliases for NO_POSITIVITY_CHECK.

Also, before changing anything in a non-backwards compatible way, there should be a broader discussion.

**Comment by asr** [comment]
I thought you proposed the `STRICTLY_POSITIVE` pragma in the same way that (from the CHANGELOG)

> New pragma `{-# TERMINATING #-}` replacing `{-# NO_TERMINATION_CHECK #-}`

Anyway, let's continue the discussion...

After your comment, I think we are talking about to different issues:
1. The name of pragma for turning off the positivity and strict positivity check.
2. Possible new pragmas like `POSITIVE`, `STRICTLY_POSITIVE` or `NON_POSITIVE`.

For simplify the discussion, I'll only write about (1).

> NO_POSITIVITY_CHECK will simply turn off any check, be it positivity or strict positivity.

I think it's imprecise to use the name 'NO_POSITIVITY_CHECK' for turning off the _strict_ positivity check. We should use the name 'NO_STRICT_POSITIVITY_CHECK' instead.

> Also, before changing anything in a non-backwards compatible way, there should be a broader discussion.

Please keep in mind that there isn't a released version of Agda using the `NO_POSITIVITY_CHECK` pragma.

**Comment by andreasabel** [comment]
Ah, right, NO_POSITIVITY_CHECK is a new pragma.  Maybe I got confused because you also proposed to rename the option --no-positivity-check, which has been there for a long time.

As strict positivity implies positivity, if you turn off the positivity check (which is a precondition for strict positivity), you will also not check for strict positivity. A new pragram NO_STRICT_POSITIVITY_CHECK could be used for checking positivity but not strict positivity, but this is not what the current NO_POSITIVITY_CHECK does.  Thus, the proposed renaming sounds illogical to me.

**Comment by asr** [comment]
> As strict positivity implies positivity, if you turn off the positivity check (which is a precondition for strict positivity), you will also not check for strict positivity. A new pragram NO_STRICT_POSITIVITY_CHECK could be used for checking positivity but not strict positivity, but this is not what the current NO_POSITIVITY_CHECK does.  Thus, the proposed renaming sounds illogical to me.

You are right.
