### ISSUE TITLE
Record pattern elimination loses hiding information

### ISSUE THREAD

**Issue by mechvel** [agda/agda#1778]
Please, download the code from 
http://www.botik.ru/pub/local/Mechveliani/agdaNotes/bugJan14-2016.zip
and see there README.agda.

This is on the type checker of Development Agda of January 14, 2016, 
ghc-7.10.2.

Probably this is a bug in Agda. And it looks like it has the same origin
as the bug of
   "Expected a hidden argument, but found a visible argument"
which the Agda developers were dealing with several days ago.

(this bug is probably going to stuck my project).

The example has been reduced many times.
Also it can be reduced further.

```
  agda $agdaLibOpt Goal.agda
```

reports

```
 Finished Structures4.
/home/mechvel/doconA/0.04/reports/jan12-2016/Goal.agda:65,3-66,48
Expected a hidden argument, but found a visible argument
when checking that the type
(p x
 : Relation.Binary.DecSetoid.Carrier
...
< about 20 page print-out >
...
    ∣? p)))
≡ 0
of the generated with function is well-formed
```

The responsible part consists of the fragments "Fails" and "Simple" in Goal.agda.

If the  "Fails"   fragment is commented out
and the "Simple"  fragment is uncommented,
then Goal.agda is type-checked.

"Simple" uses the constructor of  OfAssocClasses.Associated.
"Fails"  uses the composition of the constructors
     of "nonzero" (in the module  OverIntegralRing-0)  and  OfAssocClasses.Associated.

mty  is similar to searching a key in a list of pairs.
In the "Fails" variant, each key has a composed structure of
"asd over a nonzero", as written above.

Reducing the example has taken 3 days of me.
If Agda issued warnings about  unused import and "defined but not used values",
then it would be considerably easier to reduce examples.

**Comment by mechvel** [comment]
> And it looks like it has the same origin as the bug of
> "Expected a hidden argument, but found a visible argument"
> which the Agda developers were dealing with several days ago.

I recall,  I mean  "Closed #1759 via 9c64919".
The Development version of January 14 type-checks  #1759, but does not type-check this example.

**Comment by asr** [comment]
> (this bug is probably going to stuck my project).

I don't know what you expect by writing this kind of comments.

**Comment by andreasabel** [comment]
Here is a short test case:

``` agda
module _ (A : Set) (let T = ⊤ → {p : A × A} → A) (f : T) where

swap : T → T
swap f _ {x , y} = f _ {y , x}
-- becomes by record pattern elimination
-- IS: swap f _ xy = f _ {proj₂ xy , proj₁ xy}
-- SHOULD BE: swap f _ {xy} = f _ {proj₂ xy , proj₁ xy}

test : f ≡ swap (swap f)
test with Set -- triggers internal checking of type
test | _ = refl
```

gives error

```
Expected a hidden argument, but found a visible argument
when checking that the type
(w : Set₁) → f ≡ (λ _ xy → f (record {})) of the generated with
function is well-formed
```

The issue can be fixed by makeing record pattern translation faithful to hiding and other arg info.

**Comment by andreasabel** [comment]
@mechvel: maybe your test case was not quite minimal yet ;-), but a minimal test case is hard to get from black box testing only...
Thanks for your report!

**Comment by mechvel** [comment]
On Mon, 2016-01-18 at 08:47 -0800, Andreas Abel wrote:

> @mechvel: maybe your test case was not quite minimal yet ;-), but a
> minimal test case is hard to get from black box testing only...
> Thanks for your report!
> 
> —
> Reply to this email directly or view it on GitHub.

Thank you very much for fixing it.
