### ISSUE TITLE
Missing support for unordered-containers 0.2.6 and remove Utils.HashMap

### ISSUE THREAD

**Issue by asr** [agda/agda#1779]
The new unordered-containers 0.2.6 added the functions in Utils.HashMap, so I'll bump the lower bound for this library and I'll comment out Utils.HashMap.

**Comment by asr** [comment]
Removed support for unordered-containers 0.2.6 in Hackage.

**Comment by ghost** [comment]
Instead of bumping lower version bound I would prefer to keep compatibility with older `unordered-containers` versions. IMHO this amounts to turning `Utils.HashMap` into a kind of compatibility module using some simple CPP tinkering: for versions < 0.2.6 it provides the functions missing from `Data.HashMap.Strict` (as it does at the moment); and for versions >= 0.2.6 it simply reexports `Data.HashMap.Strict`.  The following patch would do this:

``` diff
diff --git a/Agda.cabal b/Agda.cabal
index cbfe633..9ec3b46 100644
--- a/Agda.cabal
+++ b/Agda.cabal
@@ -129,7 +129,7 @@ library
     -- transformers 0.4.0.0 was deprecated.
     , transformers >= 0.3 && < 0.4 || >= 0.4.1.0 && < 0.6
     , transformers-compat >= 0.3.3.3 && < 0.6
-    , unordered-containers >= 0.2.5.0 && < 0.2.6
+    , unordered-containers >= 0.2.5.0 && < 0.3
     , xhtml >= 3000.2.1 && < 3000.3

   if impl(ghc < 7.8)
diff --git a/src/full/Agda/Utils/HashMap.hs b/src/full/Agda/Utils/HashMap.hs
index 5e1da8b..d5936a6 100644
--- a/src/full/Agda/Utils/HashMap.hs
+++ b/src/full/Agda/Utils/HashMap.hs
@@ -1,7 +1,11 @@
+{-# LANGUAGE CPP #-}
+
 module Agda.Utils.HashMap
   ( module HashMap
+#if !MIN_VERSION_unordered_containers(0,2,6)
   , mapMaybe
   , alter
+#endif
   ) where

 import Data.Hashable
@@ -13,6 +17,8 @@ import qualified Data.Maybe as Maybe
 -- This code has not been benchmarked. Other implementations may be
 -- more efficient.

+#if !MIN_VERSION_unordered_containers(0,2,6)
+
 mapMaybe :: (a -> Maybe b) -> HashMap k a -> HashMap k b
 mapMaybe f = fmap Maybe.fromJust . HashMap.filter Maybe.isJust . fmap f

@@ -27,3 +33,5 @@ alter f k m = case HashMap.lookup k m of
   Just v  -> case f (Just v) of
     Nothing -> HashMap.delete k m
     Just v  -> HashMap.insert k v m
+
+#endif
```

**Comment by asr** [comment]
The functions in Utils.HashMap currently are not used, so I removed them, kept the support for older versions of unordered-containers and added support for unordered-containers < 0.3.

**Comment by asr** [comment]
> Instead of bumping lower version bound I would prefer to keep compatibility with older unordered-containers versions.

Just out curiosity, have you a particular reason in mind?
