### ISSUE TITLE
MAlonzo/GHC cannot compile Relation.Binary on maint

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#1786]
MAlonzo creates a lambda abstraction with 9221 variables, which just sends GHC into infinite thinking.

**Comment by UlfNorell** [comment]
Is it only on maint or also master?

**Comment by andreasabel** [comment]
Worked on master.

**Comment by asr** [comment]
Please write down your test case. I couldn't reproduce the issue.

**Comment by andreasabel** [comment]
I couldn't either now.
