### ISSUE TITLE
Testsuite destroys FFI package installations!?

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#1788]
I had the feeling that I needed to reinstall the FFI components of the standard library all the time recently.  It seems that the testsuite destroys my FFI installation:

```
$ ghc-pkg check

There are problems in package agda-tests-ffi-0.0.1:
  Warning: library-dirs: /home/abel/agda-master/exec-test-pkgs17795/lib/x86_64-linux-ghc-7.8.4/agda-tests-ffi-0.0.1 doesn't exist or isn't a directory
...
  import-dirs: /home/abel/agda-master/exec-test-pkgs17795/lib/x86_64-linux-ghc-7.8.4/agda-tests-ffi-0.0.1 doesn't exist or isn't a directory
  cannot find any of ["Common/FFI.hi","Common/FFI.p_hi","Common/FFI.dyn_hi"]
  cannot find any of ["libHSagda-tests-ffi-0.0.1.a","libHSagda-tests-ffi-0.0.1.p_a","libHSagda-tests-ffi-0.0.1-ghc7.8.4.so","libHSagda-tests-ffi-0.0.1-ghc7.8.4.dylib","HSagda-tests-ffi-0.0.1-ghc7.8.4.dll"] on library path

There are problems in package agda-lib-ffi-0.11:
  Warning: library-dirs: /home/abel/agda-master/exec-test-pkgs17796/lib/x86_64-linux-ghc-7.8.4/agda-lib-ffi-0.11 doesn't exist or isn't a directory
...
  import-dirs: /home/abel/agda-master/exec-test-pkgs17796/lib/x86_64-linux-ghc-7.8.4/agda-lib-ffi-0.11 doesn't exist or isn't a directory
  cannot find any of ["Data/FFI.hi","Data/FFI.p_hi","Data/FFI.dyn_hi"]
  cannot find any of ["IO/FFI.hi","IO/FFI.p_hi","IO/FFI.dyn_hi"]
  cannot find any of ["libHSagda-lib-ffi-0.11.a","libHSagda-lib-ffi-0.11.p_a","libHSagda-lib-ffi-0.11-ghc7.8.4.so","libHSagda-lib-ffi-0.11-ghc7.8.4
```

Somehow the compiler test (?) reinstalls the FFI packages into a temporary directory like `exec-test-pkgsXXXXX` which is then deleted.

That's bad.

**Comment by UlfNorell** [comment]
I think it would make more sense if the test suite didn't install the package at all, but just passed the required Haskell modules as dependencies to ghc using `--ghc-flag`.

**Comment by phile314** [comment]
Currently, the compiler tests (try to) create a temporary ghc package db in the exec-test-pkkgsXXX directories. However, that seems to fail for some reason.

I like Ulfs suggestion, it's probably easier to just pass the HS include directories to GHC using --ghc-flag.

**Comment by phile314** [comment]
This should be fixed now for all enabled compiler tests (simple + special).

**Comment by andreasabel** [comment]
Thanks for the quick fix!
