### ISSUE TITLE
Agsy generates ill-typed terms referring to shadowed variables

### ISSUE THREAD

**Issue by gallais** [agda/agda#1789]
The problem is that agsy does not notice that a variable it wants to use
has been shadowed and that the typechecker will therefore reject the 
generated term as ill-typed.

```
argh : (X : Set) → X → Set
argh = λ x x → ? -- Here C-c C-a yields "x"
```

Credits to @pigworker for highlighting that the machine being able to
generate valid names for shadowed variables is crucial for a smooth
interactive programming experience.

We can either patch agsy so that it refuses to produce a term in such
situations or add a way to refer to shadowed variables (e.g. "x^n" would
mean "the nth x in scope"). The latter solution would also yield a fix for
a similar problem when solving unification problems automatically:

```
argh₂ : (X : Set) (f : (A : Set) → A → Set) →
        (Y : Set) (X : X) → f ? X -- Here C-c C-s yields "X"
argh₂ = {!!} 
```

**Comment by andreasabel** [comment]
I think `C-c C-s` does the right thing here: it fills the whole and then giving fails.  This gives the user a chance to analyse the problem.
Agsy should do the same: instead of filling in the solution directly, go via "give".

**Comment by andreasabel** [comment]
My plan is not trivial to implement, as Agsy instantiates the metas directly instead just computing their solution. Fredrik might work this year on a new Agsy.

**Comment by UlfNorell** [comment]
See also #572.

**Comment by andreasabel** [comment]
Since Agsy is gone, this issue has become irrelevant.  Closing as "not-planned".
