### ISSUE TITLE
Preparation for supporting GHC 8.0.1

### ISSUE THREAD

**Issue by asr** [agda/agda#1799]
Last edit: 2016-05-01
GHC version: 8.0.1-rc4 

Current issues related to support GHC 8.0.1:
- pqueue (see https://github.com/lspitzner/pqueue/issues/2) which is required by uhc-util
- uhc-light (see https://github.com/UU-ComputerScience/uhc/issues/71)
  
  From https://github.com/UU-ComputerScience/uhc/issues/73#issuecomment-187059603, the support for GHC 8.0.1 by uch-light requires that UHC supports GHC 8.0.1.
- uhc-util (see https://github.com/UU-ComputerScience/uhc-util/issues/8) which is required by uhc-light
- ~~fclabels (see https://github.com/sebastiaanvisser/fclabels/issues/27)~~
- ~~geniplate-mirror (see https://github.com/danr/geniplate/pull/4)~~
- ~~hashtables (see https://github.com/gregorycollins/hashtables/issues/29)~~
- ~~logict-state (see https://github.com/atzedijkstra/logict-state/pull/1) which is required by uhc-util~~
- ~~murmur-hash (see https://github.com/nominolo/murmur-hash/issues/11)~~

**Comment by asr** [comment]
I updated the OP.

**Comment by asr** [comment]
I updated the OP.

**Comment by asr** [comment]
I updated the OP.

**Comment by mietek** [comment]
There appears to be an issue with compiling `agda-mode` using GHC 8.0.1-rc3, as reported in https://github.com/Homebrew/homebrew-core/pull/440#issuecomment-212501561 by @ilovezfs:

```
==> /usr/local/Cellar/agda/2.5.1/bin/agda-mode compile
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Unable to compile the following Emacs Lisp files:
  /usr/local/Cellar/agda/2.5.1/share/x86_64-osx-ghc-8.0.0.20160411/Agda-2.5.1/emacs-mode/agda2-abbrevs.el
  /usr/local/Cellar/agda/2.5.1/share/x86_64-osx-ghc-8.0.0.20160411/Agda-2.5.1/emacs-mode/annotation.el
  /usr/local/Cellar/agda/2.5.1/share/x86_64-osx-ghc-8.0.0.20160411/Agda-2.5.1/emacs-mode/agda2-queue.el
  /usr/local/Cellar/agda/2.5.1/share/x86_64-osx-ghc-8.0.0.20160411/Agda-2.5.1/emacs-mode/eri.el
  /usr/local/Cellar/agda/2.5.1/share/x86_64-osx-ghc-8.0.0.20160411/Agda-2.5.1/emacs-mode/agda2.el
  /usr/local/Cellar/agda/2.5.1/share/x86_64-osx-ghc-8.0.0.20160411/Agda-2.5.1/emacs-mode/agda-input.el
  /usr/local/Cellar/agda/2.5.1/share/x86_64-osx-ghc-8.0.0.20160411/Agda-2.5.1/emacs-mode/agda2-highlight.el
  /usr/local/Cellar/agda/2.5.1/share/x86_64-osx-ghc-8.0.0.20160411/Agda-2.5.1/emacs-mode/agda2-mode.el
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: /usr/local/Cellar/agda/2.5.1/bin/agda-mode compile
```

**Comment by ilovezfs** [comment]
@mietek Thank you for reporting this in the right place!

**Comment by asr** [comment]
@mietek I couldn't reproduce the issue with GNU Emacs 24.5.1. As it was [mentioned](https://github.com/Homebrew/homebrew-core/pull/440#issuecomment-212516110) by @zmwangx, the issue doesn't depend on GHC 8.0.1-rc3.

**Comment by ilovezfs** [comment]
The formula for agda only requires

```
 depends_on :emacs => ["21.1", :recommended]
```

The version that ships on El Capitan is 22.1.1.

@asr Given that the issue does not occur when using agda 2.5.1 + ghc-7.10.3b + emacs 22.1.1, and it does occur when using agda 2.5.1 + ghc 8.0.1-rc3 + emacs 22.1.1, there's clearly some sort of difference.

**Comment by zmwangx** [comment]
Emacs 22.1.1 from 2007 doesn't seem to have `byte-compile-disable-warning`. I'm surprised that it worked at all.

Anyway, assuming that agda2-mode is supported on 22.1.1 (I doubt it, because even some big name packages like magit have long since moved on), we can safely ignore the error, because the only difference between byte compiling or not is speed.

**Comment by ilovezfs** [comment]
@zmwangx well that would mean the bug is with 7.10.3b not failing. Also it means that if the formula is going to have an emacs option it should be requiring a higher version if 22.1.1 is not sufficient.

**Comment by asr** [comment]
I filed #1945 for continuing the discussion with the issue with `agda-mode`.

**Comment by ilovezfs** [comment]
Apparently discussion will have to continue here since you proceeded to close the issue after filing it.

**Comment by ilovezfs** [comment]
@zmwangx Yep you were right. The issue is that --build-bottle fulfills the requirement `:emacs => ["21.1", :recommended]` with brew's emacs, which is 24.5, whereas --build-from-source fulfills the same requirement with the system emacs, which is 22.1.1. Despite the error, do the compiled agda emacs bindings from the bottle work with 21.1.1 at all? If not we really should raise that requirement to whatever is the minimum that does actually work.

**Comment by asr** [comment]
Since Agda compiles with GHC 8.0.1-rc3 and I didn't find any problem running `make test` I'm closing this issue. I'll open new issues for other problems known.

**Comment by asr** [comment]
Agda doesn't compile with GHC 8.0.1-rc4. I updated the OP.

**Comment by asr** [comment]
The murmur-hash issue was fixed, I updated the OP.

**Comment by asr** [comment]
GHC 8.0.1 (source tarball) was released, so I'm closing this issue. Please use #1971 for reporting new issues related to this version of GHC.
