### ISSUE TITLE
The `Aspects` data type doesn't satisfy the monoid properties

### ISSUE THREAD

**Issue by asr** [agda/agda#1801]
In [Precise.hs](https://github.com/agda/agda/blob/maint-2.4/src/full/Agda/Interaction/Highlighting/Precise.hs) is defined the instance

```
instance Monoid Aspects
...
```

but `Aspects` doesn't satisfy any of the three monoid properties in accordance with QuickCheck (see below). I guess some possible reasons are
1. In Agda source code _no_ every instance of `Monoid` must be an actual monoid.
2. The `mappend` function is buggy
3. The `Monoid` instance of `Aspects` is buggy
4. The `Arbitrary` instance of `Aspects` is buggy

Do we agree that every instance of `Monoid` should be an actual monoid?

This simple code shows that `Aspects` doesn't satisfy the right identity law.

``` haskell
import Data.Monoid
import Test.QuickCheck

import Agda.Interaction.Highlighting.Precise

monoidAssocProp :: (Eq m, Monoid m) => m -> m -> m -> Bool
monoidAssocProp x y z = (x <> (y <> z)) == ((x <> y) <> z)

monoidRightIdProp :: (Eq m, Monoid m) => m -> Bool
monoidRightIdProp x = x == (x <> mempty)

monoidLeftIdProp :: (Eq m, Monoid m) => m -> Bool
monoidLeftIdProp x = (mempty <> x) == x

test :: IO ()
test = quickCheck (monoidRightIdProp :: Aspects -> Bool)
```

```
GHCi> test
*** Failed! Falsifiable (after 7 tests and 4 shrinks): 
Aspects {aspect = Nothing, otherAspects = [TypeChecks,TypeChecks], note = Nothing, definitionSite = Nothing}
```

**Comment by UlfNorell** [comment]
From a quick glance it looks like the Arbitrary instance is to blame.

**Comment by nad** [comment]
Do the properties hold if you treat `otherAspects` as a set, and ignore the `note`?

**Comment by UlfNorell** [comment]
Yes.
