### ISSUE TITLE
Reflected meta literals

### ISSUE THREAD

**Issue by m0davis** [agda/agda#1802]
Location of the error: src/full/Agda/TypeChecking/Quote.hs:138

Sample code is pasted [here](http://lpaste.net/5020540722885951488). Sorry I couldn't figure out how to shorten it!

**Comment by UlfNorell** [comment]
The offending `__IMPOSSIBLE__` comes with a comment

``` hs
-- not impossible, just TODO
```

There should be a constructor in the reflected literal type for metavariables.

**Comment by UlfNorell** [comment]
Fixed by 4633731.

**Comment by asr** [comment]
I added the bug label and the 2.4.4 milestone.
