### ISSUE TITLE
maint installs cpphs as cpphs-2.4.2.6

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#1808]
On a fresh Mac OS X El Capitan, with ghc-7.10 installed with homebrew, `make` fails for maint-2.4 with error:

```
setup: The program 'cpphs' version >=1.19 && <1.20 is required but it could not be found.
```

However, I got a `cpphs-2.4.2.6` on my system, which I suspects comes from this failed install attempt. ;-)

**Comment by asr** [comment]
I could reproduce the problem.

**Comment by asr** [comment]
The cabal-install program is doing the right thing. The problem is because cpphs (the library) and cpphs (the program) use the same .cabal file. I'll talk with @malcolmwallace (cpphs' author) about it.

**Comment by malcolmwallace** [comment]
Is there a different way to use cabal that has separate files for library vs executable?

**Comment by asr** [comment]
> Is there a different way to use cabal that has separate files for library vs executable?

No.

@malcolmwallace  Independently of this issue, cpphs has two different and _independent_ uses: the library and the program. For example, Agda uses the program but not the library, and haskell-src-exts uses the library but not the program. In fact, there are different Cabal fields for representing the different uses: `build-depends` for the library and `build-tools` for the program. I suggest to split cpphs in the cpphs-library and the cpphs-program.

**Comment by asr** [comment]
For the discussion related to split cpphs, I filed https://github.com/malcolmwallace/cpphs/issues/1.

**Comment by asr** [comment]
After removing the dependency on `haskell-src-exts` (thanks @UlfNorell), this issue disappeared because cpphs should be installed before compiling Agda.
