### ISSUE TITLE
Instance arguments search regression?

### ISSUE THREAD

**Issue by liamoc** [agda/agda#1810]
I typechecked an old paper of mine (previously developed with Agda 2.4 or 2.3, I can't remember) with the latest revision ( 9081bb1 ) of Agda (I wanted to use the libraries feature, and a few other things) and a bunch of instance arguments can no longer be found. I think this is a bug.

I boiled it down into a minimal working example, found in this gist.

https://gist.github.com/liamoc/4e7981de3c406dc90579

**Comment by UlfNorell** [comment]
That does indeed look like a bug. If you look at the constraints (`C-c C-=`) there isn't even an instance constraint for the unsolved meta.

**Comment by andreasabel** [comment]
Works on maint (2.4.2.6), but fails on master.  This is a release blocker.

**Comment by UlfNorell** [comment]
I introduced this bug with 711bc27e. Working on a fix.

Here's a self-contained test case:

``` agda
postulate
  Bool : Set
  D    : Bool → Set
  f    : (a : Bool) → D a
  ⟦_⟧  : ∀ {a} → D a → Bool

record State : Set where
  field bool : Bool

open State {{...}}

postulate
  guard : {S : Set} → (S → Bool) → S

test : State
test = guard (λ σ → ⟦ f bool ⟧) -- doesn't work, used to work in agda 2.4
```

**Comment by liamoc** [comment]
Thanks Ulf!
