### ISSUE TITLE
Relocate the standalone program for testing size constraint solver

### ISSUE THREAD

**Issue by asr** [agda/agda#1812]
See https://github.com/agda/agda/commit/f2a865b9aee0a19c946e3d7985f694004aacf0dc#commitcomment-15806770.

**Comment by andreasabel** [comment]
I had to compile the size solver to test something, so I took the opportunity to relocate it into `src/size-solver` and remove it from `src/full/Agda`.

TODOs:
- make it Agda version specific (currently hard-wired to 2.4.2.6)
- make it part of the test suite.

**Comment by asr** [comment]
> I had to compile the size solver to test something, so I took the opportunity to relocate it into src/size-solver and remove it from src/full/Agda.

Thanks!

> TODOs:
> 
>    make it Agda version specific (currently hard-wired to 2.4.2.6)

I filed #1823.

>    make it part of the test suite.

I filed #1822
