### ISSUE TITLE
Codec.Compression.Zlib: premature end of compressed data stream

### ISSUE THREAD

**Issue by asr** [agda/agda#1814]
I have seen the error

> agda: Codec.Compression.Zlib: premature end of compressed data stream

associated with different files in some Travis builds. After restarting the builds, the error disappears.

Right now, the error is in https://travis-ci.org/agda/agda/jobs/106551279.

Do we need to pay attention to this problem? (self-question)

**Comment by asr** [comment]
Cabal also generates the same error (see https://github.com/haskell/cabal/issues/2001).

**Comment by andreasabel** [comment]
Mmh, I wondered myself what is the cause.  Could it be that too many files are open on travis, so it refuses to open one more instance of Common/Prelude.agda or what ever it is?  Are the tests in the testsuite run in parallel?  (Just a shot in the dark.)

**Comment by asr** [comment]
> Are the tests in the testsuite run in parallel?

Yes.

**Comment by asr** [comment]
After ea1438139819fda6aced3ac8aa98f6687683563b I'm closing the issue.

If it is necessary to reopen the issue, please report the test-suite (succeed, fail, etc.) where the issue occurred again.
