### ISSUE TITLE
Case splitting should preserve existing names

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#1820]
``` agda
data Nat : Set where
  zero : Nat
  suc : (n : Nat) → Nat

test : (n : Nat) → Nat
test n with zero
... | n = {!n!}
```

Loading reports:

```
Repeated variables in pattern: n
when scope checking the left-hand side test n in the definition of test
```

**Comment by WolframKahl** [comment]
Why should ellipsis should not report `Repeated variables on left-hand side` when there are indeed repeated variables on the left-hand side?

I understand `... |` to _add_ additional matching against the `with` arguments, but the previously matched pattern variables remain in scope, and shadowing is, in my opinion, at least dangerous.

**Comment by UlfNorell** [comment]
I agree with Wolfram here. Are you saying that the error message should be better?

**Comment by andreasabel** [comment]
The annoying thing is in the following workflow:

``` agda
data N : Set where

data Nat : Set where
  zero : Nat
  suc : (n : N) → Nat

test : (n : Nat) → Nat
test n with zero
... | x = {!x!}
```

Splitting on `x` gives:

``` agda
test n with zero
test n | zero = {!!}
test n₁ | suc n = {!!}
```

When I then reintroduce the ellipsis

``` agda
test n with zero
... | zero = {!!}
... | suc n = {!!}
```

I get the error.
Somehow Agda shamelessly renames `n` to make space for the `n` in `suc n` when expanding the ellipsis, but does not accept it when the ellipsis is still in place.

**Comment by WolframKahl** [comment]
Then perhaps that interactive mechanism should be fixed, instead of changing the language...

**Comment by UlfNorell** [comment]
Indeed. See #573.

**Comment by andreasabel** [comment]
It is perfectly fine to change variable names in with-clauses; manually I could also write

``` agda
test _ | suc n = ?
```

I think it is consistent to interpret the ellipsis as choosing variable names that do not conflict with the variable names written by the user in the additional patterns.  The safe option, which makes most sense, is to choose `_` in ellipsis expansion for names that are shadowed by the with-patterns.

If I am looking at the binding site of a variable, I will start from the closest binders, e.g., in.

``` agda
long-function many args n manymoreargs  with e
... | lots = ?
... | of = ?
... | crap = ?
... | many = ?
... | more = ?
... | pages = ?
... | offo = ?
... | crappo = ?
... | c n = i am here
```

I will find the binding of `n` in the with-pattern and not look up to the original clause pages above.

**Comment by WolframKahl** [comment]
On Wed, Feb 10, 2016 at 12:53:55AM -0800, Andreas Abel wrote:

> I think it is consistent to interpret the ellipsis as choosing variable names that do not conflict with the variable names written by the user in the additional patterns.

I still do not like that: If I (succeed to) use ellipsis, I want to keep the original matching.

I typically named these variables consciously, and I am using almost all of them in almost all clauses. Being able to accidentally shadow them would be dangerous. And if you are thinking about pages: The shadowing binding may also be pages away from the actual use...

If I want a different matching, I don't use ellipsis.
(More frequently I actually cannot use ellipsis because I have to use a different matching.)

Wolfram

**Comment by andreasabel** [comment]
Ok, we cannot agree on this one.  I am fine to postpone.

However, then we should change the case splitting tactics to not shadow any pattern variables in what was the ellipsis.
Splitting on `x` should give me:

``` agda
test n with zero
test n | zero = {!!}
test n | suc n₁ = {!!}
```

**Comment by andreasabel** [comment]
I think the current behavior is due to the left-to-right name reification, combined with the fact that the internal order is different than the printed order due to the with-displayform.  Internally, the second clause probably looks:

```
  test-with (suc n) n = ?
```

and when reifying these name suggestions we get

```
  test-with (suc n) n₁ = ?
```

which is then printed as

```
  test n₁ | suc n = ?
```

thanks to the with-displayform.

```
```

**Comment by mietek** [comment]
This issue seems to have been misrenamed.  It doesn’t seem to be about case splitting in the sense of the user-accessible operation triggered by `C-c C-c`, is it?

**Comment by jespercockx** [comment]
The original issue isn't, but the problem described by @andreasabel in comment 4 is:
```agda
data N : Set where

data Nat : Set where
  zero : Nat
  suc : (n : N) → Nat

test : (n : Nat) → Nat
test n with zero
... | x = {!x!}
```
The current behaviour of Agda when case splitting is to produce the following:
```agda
test : (n : Nat) → Nat
test n with zero
test n | zero = {!!}
test n | suc x = {!!}
```
which is what one would expect.

Also, in a more tricky situation, Agda still seems to know what to do:
```agda
data Tree : Set where
  leaf : Tree
  node : Tree → Tree → Tree

test₂ : (n : Tree) → Tree
test₂ n₁ with leaf
... | n = {!n!}
```
Case splitting on n produces this:
```agda
test₂ : (n : Tree) → Tree
test₂ n₁ with leaf
test₂ n₁ | leaf = {!!}
test₂ n₁ | node n n₂ = {!!}
```

**Comment by andreasabel** [comment]
See #4704.  I am finally fixing the OP in #4709.
