### ISSUE TITLE
Allow syntax {let x = t} and {open M} in telescopes

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#1824]
So far, only `(let x = t)` and `(open M)` are allowed, but since the let-bound identifiers are neither visible nor hidden, braces should be as good as parentheses.

Why is this useful?  Less editing when specializing a binding {x : A} to {let x = t}. 
Also, suggesting "hidden" makes more sense than suggesting "visible" for these let bindings.

**Comment by np** [comment]
Agreed. This should still be clearly stated that both forms are equivalent.

**Comment by andreasabel** [comment]
I am tempted to fix this on maint-2.4.

**Comment by nad** [comment]
I'm opposed to this change. What's next? Support for `{{let x = t}}` as well?

Andreas, if you want to edit less, then I suggest that you implement an Emacs macro or function that does what you want.

**Comment by andreasabel** [comment]
Na.  The brace syntax is more natural than the parentheses syntax, but double braces make little sense.
If you are opposed, do you have a different, smooth semantics for `{let x = t}` you would like to see?  That would be a reason to save this syntax for later.

**Comment by UlfNorell** [comment]
If you think the brace syntax is more natural, it would be better to change the syntax. Having both forms just leads to confusion. Personally I find the parens more natural though. Also, I don't see why your argument for introducing the new syntax doesn't apply equally to double braces.

**Comment by andreasabel** [comment]
It does, but I would be less surprised if `{{let x = t}}` does not work as I was when I found that `{let x = t}` does not.

**Comment by UlfNorell** [comment]
Closing this. There doesn't seem to be enough value to make up for the potential confusion.
