### ISSUE TITLE
Reloading consumes linear memory with caching enabled

### ISSUE THREAD

**Issue by Saizan** [agda/agda#1829]
Reloading the following module with --caching consumes linear memory rather than constant as it should:

```
module _ where

q : ?
q = Set
```

**Comment by Saizan** [comment]
Debugged this one with the direction of @nad : retainer profiling was actually helpful this time, among other things it pointed to "use", which we just made stricter.

**Comment by andreasabel** [comment]
Mmh, this test case takes a bit long.  Can we have it shorter or relocated to benchmarks or some later phase of the test suite?

**Comment by nad** [comment]
If I recall correctly the test case was set up in such a way that Agda crashed if the memory consumption was too high, both on 32-bit and on 64-bit systems. I think it would be good if this property was preserved.

**Comment by andreasabel** [comment]
Ok, then ...or relocated to benchmarks or some later phase of the test suite?

**Comment by nad** [comment]
I don't understand what you mean by "or". It's fine with me if you relocate the test case _and_ preserve the property that I mentioned above.

**Comment by UlfNorell** [comment]
> Can we have it shorter **or** relocated to benchmarks or some later phase of the test suite?

**Comment by nad** [comment]
Shorter: With my current setup (32-bit GHC 8.0.1) I need 382 lines in `Issue1829.in` to trigger the `Heap exhausted` error (after reverting 2fd39d4246b00be243103a438691f76775dd112c). Currently the file contains 1000 lines, so perhaps it could be made shorter. However, I think we should include some margin to allow for differences between different versions of GHC.

**Comment by andreasabel** [comment]
Recent travis failures under 8.6.5:
- https://travis-ci.org/agda/agda/jobs/569248603 
- https://travis-ci.org/agda/agda/jobs/569346144
- https://travis-ci.org/agda/agda/jobs/569538566
- https://travis-ci.org/agda/agda/jobs/572291102
- https://travis-ci.org/agda/agda/jobs/572672173 (build 6066)

4M heap exhausted.

Failure under 8.4.4:
- https://travis-ci.org/agda/agda/jobs/572672174 (build 6066)
- https://travis-ci.org/agda/agda/jobs/573504878 (build 6085)

Failure under 8.2:
- https://travis-ci.org/agda/agda/jobs/572672175 (build 6066)

Failure under 8.0:
- https://travis-ci.org/agda/agda/jobs/572672176 (build 6066)

**Comment by andreasabel** [comment]
@UlfNorell @nad @Saizan : While working on #1346, I made the following innocuous refactoring:  I made a custom lens 
```haskell
scopeFixitiesAndPolarities :: Lens' (C.Fixities, C.Polarities) ScopeInfo
```
that accesses two fields of `ScopeInfo` at the same time and used it in `computeFixitiesAndPolarities` instead of both of the lenses `scopeFixities` and `scopePolarities`.  This change causes the test case to fail (see e.g. above, travis build 6066).  Apparently, introduces a space leak.  However, I fail to see what is going on.

Here is the full diff:
```diff
Unstaged changes:
	Modified   src/full/Agda/Syntax/Scope/Base.hs
diff --git a/src/full/Agda/Syntax/Scope/Base.hs b/src/full/Agda/Syntax/Scope/Base.hs
index af293f161..488cf0d9c 100644
--- a/src/full/Agda/Syntax/Scope/Base.hs
+++ b/src/full/Agda/Syntax/Scope/Base.hs
@@ -226,6 +226,12 @@ scopePolarities f s =
   f (_scopePolarities s) <&>
   \x -> s { _scopePolarities = x }
 
+scopeFixitiesAndPolarities :: Lens' (C.Fixities, C.Polarities) ScopeInfo
+scopeFixitiesAndPolarities f s =
+  f (_scopeFixities s, _scopePolarities s) <&>
+  \ (fixs, pols) -> s { _scopeFixities = fixs, _scopePolarities = pols }
+
+
 -- | Lens for 'scopeVarsToBind'.
 updateVarsToBind :: (LocalVars -> LocalVars) -> ScopeInfo -> ScopeInfo
 updateVarsToBind = over scopeVarsToBind
	Modified   src/full/Agda/Syntax/Scope/Monad.hs
diff --git a/src/full/Agda/Syntax/Scope/Monad.hs b/src/full/Agda/Syntax/Scope/Monad.hs
index b2a47752a..fbc035699 100644
--- a/src/full/Agda/Syntax/Scope/Monad.hs
+++ b/src/full/Agda/Syntax/Scope/Monad.hs
@@ -331,13 +331,18 @@ instance MonadFixityError ScopeM where
 -- | Collect the fixity/syntax declarations and polarity pragmas from the list
 --   of declarations and store them in the scope.
 computeFixitiesAndPolarities :: DoWarn -> [C.Declaration] -> ScopeM a -> ScopeM a
-computeFixitiesAndPolarities warn ds ret = do
-  (fixs0, pols0) <- (,) <$> useScope scopeFixities <*> useScope scopePolarities
-  (fixs, pols)   <- fixitiesAndPolarities warn ds
-  modifyScope $ set scopeFixities fixs . set scopePolarities pols
-  x <- ret
-  modifyScope $ set scopeFixities fixs0 . set scopePolarities pols0
+computeFixitiesAndPolarities warn ds cont = do
+  fp <- fixitiesAndPolarities warn ds
+  fp0 <- useScope scopeFixitiesAndPolarities
+  modifyScope $ set scopeFixitiesAndPolarities fp
+  x <- cont
+  modifyScope $ set scopeFixitiesAndPolarities fp0
   return x
```

**Comment by Saizan** [comment]
`useScope` (because of `useR`) forces the result of projecting the lens, this usually prevents retaining the whole structure when we only need a field, however your combined lens adds an extra layer of laziness with the pairs, so the actual projections remain unforced.

I guess `scopeFixitiesAndPolarities` could add some strictness when building the pair?

**Comment by andreasabel** [comment]
Thanks @Saizan.  Your explanation is consistent with my findings by trial-and-error.
> I guess scopeFixitiesAndPolarities could add some strictness when building the pair?

Interestingly, forcing the components of the _old_ value `fp0` is sufficient.
I am currently testing the following version of the lens:
```haskell
scopeFixitiesAndPolarities :: Lens' (C.Fixities, C.Polarities) ScopeInfo
scopeFixitiesAndPolarities f s =
  f' (_scopeFixities s) (_scopePolarities s) <&>
  \ (fixs, pols) -> s { _scopeFixities = fixs, _scopePolarities = pols }
  where
  f' !fixs !pols = f (fixs, pols)
```

**Comment by nad** [comment]
Perhaps it also makes sense to make the second argument to `<&>` strict in the pair.

**Comment by andreasabel** [comment]
> Perhaps it also makes sense to make the second argument to `<&>` strict in the pair.

What do you suggest? The following?
```haskell
\ !(fixs, pols) -> s { _scopeFixities = fixs, _scopePolarities = pols }
```
What is the rationale?  (Andrea's explanation was that projections from the state need to be forced.)

**Comment by nad** [comment]
> The following?

Yes.

> What is the rationale?

This might make the code more strict. (The fields of `s` are not strict.)

**Comment by Saizan** [comment]
`f' !fixs !pols = f (fixs, pols)` is what I was thinking of.

About the second argument:

A bang here is not making things stricter `\ !(fixs, pols) -> ...`, there's already a constructor match.

Bangs here do  `\ (!fixs, !pols) -> ...`.

**Comment by nad** [comment]
Right, I was thinking of the special treatment of pattern bindings in Haskell (they are by default lazy), but that does not apply here. And I don't think forcing the pair constructor makes much of a difference anyway. Forcing the components might have some effect, but in that case it is perhaps better to make the fields strict.
