### ISSUE TITLE
Release Agda 2.5.1 release candidate 1

### ISSUE THREAD

**Issue by asr** [agda/agda#1831]
I'll release Agda 2.5.1 release candidate from the master branch.

**Comment by andreasabel** [comment]
I need to fix #1821 before the release.

**Comment by asr** [comment]
@andreasabel some objection to release a _release candidate_ without fixing #1821?

**Comment by andreasabel** [comment]
No objections.  As sized types are used by only a few people, the rest of the community can test their developments with this RC.

**Comment by phile314** [comment]
I just read up on how readthedocs.org handles releases [1].

According to the Agda release instructions, we create a git tag for a new release. Readthedocs should handle this fine and should add a version "2.5.1" documentation release without any manual intervention.

[1] http://docs.readthedocs.org/en/latest/versions.html

**Comment by asr** [comment]
I merged the 2.4.2.6 milestone into the 2.5.1 milestone.

**Comment by asr** [comment]
I started the preparation of the RC from the current master branch.

You can continue pushing in master, but stop pushing in the maintenance branch.

**Comment by asr** [comment]
I have tested the installation of release candidate [Agda-2.5.0.20160212.tar.gz](http://www1.eafit.edu.co/asr/tmp/Agda-2.5.0.20160212.tar.gz) in Ubuntu 12.04 64-bits with:
- GHC 7.6.3, 7.8.4 and 7.10.3, and
- GHC 7.10.3 and the `uhc` flag

Could someone test the installation of the release candidate on Windows and/or Mac OS using the following instructions:

```
  $ tar xzf Agda-2.5.0.20160212.tar.gz
  $ cd Agda-2.5.0.20160212
  $ cabal install
```

If you use Mac OS and GHC 7.10.*, please also test

```
$ cabal install -f uhc
```

**Comment by UlfNorell** [comment]
I can build with `-fuhc` on Mac OS 10.10 and GHC 7.10.3, but I can't run the compiler tests. Trying to compile the master branch of uhc I get
`src/ehc/files1.mk:468: *** multiple target patterns.  Stop.`

**Comment by asr** [comment]
I didn't install UHC from its master branch. I followed the instructions in [UHC Backend](http://agda.readthedocs.org/en/latest/tools/compilers.html#backends):

```
cabal install uhc-util-0.1.6.3 uulib-0.9.21
wget https://github.com/UU-ComputerScience/uhc/archive/v1.1.9.2.tar.gz
tar -xf v1.1.9.2.tar.gz
cd uhc-1.1.9.2/EHC
./configure
make
make install
```

**Comment by UlfNorell** [comment]
Compiled RC on Windows 8.1 / ghc-7.10.3.

**Comment by UlfNorell** [comment]
I managed to install uhc-1.1.9.2 but all compiler tests fail with exit code -11.

**Comment by asr** [comment]
How are you running the compiler tests?

**Comment by UlfNorell** [comment]
`make compiler-test`

Something is wrong with my uhc though. I get segmentation fault trying to run any compiled program.

``` haskell
main = return ()
```

```
$ uhc Hello.hs
[1/1] Compiling Haskell                  Hello                  (Hello.hs)
$ ./Hello
Segmentation fault: 11
```

**Comment by asr** [comment]
Keep in mind we cannot run the test-suite with the RC because I removed the Cabal `test-suite` section from Agda.cabal (it is not necessary for the user). Now I'm thinking it is a good idea to keep the Cabal test-suite because:
- we can run the test-suite from the repository and
- it shouldn't be a problem for the user because she doesn't use the `--enable-test` option when installing Agda.

I'll generate a new RC.

**Comment by asr** [comment]
> make compiler-test

After `make clean` you should got

```
$ make compiler-test
bash: /home/asr/tmp-asr/agda.release/dist-2.5.0.20160212/build/agda-tests/agda-tests: No such file or directory
make: *** [compiler-test] Error 127
```

**Comment by asr** [comment]
The new RC Agda-2.5.0.20160213 is [here](http://www1.eafit.edu.co/asr/tmp/Agda-2.5.0.20160213.tar.gz).

**Comment by phile314** [comment]
@UlfNorell I wouldn't recommend using the UHC master branch.
Can you compile Hello.hs again using "uhc -v3 Hello.hs". Last line of debug output should be the call to the C compiler. Which compiler and version is that? If you are using GCC 4.9 or newer, you may hit this bug: https://github.com/UU-ComputerScience/uhc/issues/32

**Comment by phile314** [comment]
Note that if you want to execute the test suite you will have to set the AGDA_BIN environment variable to point to the Agda executable. See also https://github.com/agda/agda/issues/1837 .

I can build Agda on Fedora 23 Linux 64bit. The tests sadly don't work because the *.agda files are missing, e.g. test/Succeed/ contains only Tests.hs but no *.agda files. This is probably because we don't include the test Agda files in the data-files section in Agda.cabal, . Not sure if that's worth doing?

**Comment by UlfNorell** [comment]
> Keep in mind we cannot run the test-suite with the RC because I removed the Cabal test-suite section from Agda.cabal

Of course. I used the master branch to try the test suite.

> Which compiler and version is that? If you are using GCC 4.9 or newer, you may hit this bug: UU-ComputerScience/uhc#32

Yeah, that's most likely it.

**Comment by asr** [comment]
> The tests sadly don't work because the *.agda files are missing, e.g. test/Succeed/ contains only Tests.hs but no *.agda files. This is probably because we don't include the test Agda files in the data-files section in Agda.cabal, . Not sure if that's worth doing?

I included the Cabal test-suite section in Agda.cabal for testing the RC from the master branch. We don't need to run the test-suite outside of the master branch.

**Comment by asr** [comment]
I realised we have a wrong work-flow. How can you run the test-suite from the master branch using the RC/release if I have not pushed the commits related to the RC/release?

So far, when I have asked for testing a RC/realease I only asked for testing the _installation_ of the RC/release on different platforms.

Do we also want to run the test-suite with the RC/release on different platforms or is it enough only to test the installation of the RC/release?

I think to test only the installation is enough. Why? Because we've had no problems following this approach. Opinions?

**Comment by UlfNorell** [comment]
I don't think we need to run the test suite for the release. As you say we haven't really had any problems with releases compiling but not working. I ran `compiler-test` on the master branch since I assumed there weren't any differences when it comes to the uhc backend. I did compile the release candidate though.

**Comment by asr** [comment]
> I don't think we need to run the test suite for the release. As you say we haven't really had any problems with releases compiling but not working.

OK. I'll push the RC.

> I ran compiler-test on the master branch since I assumed there weren't any differences when it comes to the uhc backend.

You are right.

**Comment by asr** [comment]
Done.
