### ISSUE TITLE
Copattern matching: order of clauses should not matter here

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#1834]
``` agda
open import Common.Bool
open import Common.Equality

data Answer : Bool → Set where
  dunno : ∀ b → Answer b
  yes   : Answer true

record R (b : Bool) : Set where
  field p : Answer b → Bool

boj : ∀ b → R b
R.p (boj b)    (dunno .b) = false
R.p (boj true) yes        = true

obj : ∀ b → R b
R.p (obj true) yes        = true
R.p (obj b)    (dunno .b) = false

works : ∀ b → R.p (boj b) (dunno b) ≡ false
works b = refl

test : ∀ b → R.p (obj b) (dunno b) ≡ false
test b = refl
```

Agda complains

```
R.p (obj b) (dunno b) != false of type Bool
when checking that the expression refl has type
R.p (obj b) (dunno b) ≡ false
```

However, the split heuristics should split on the result first, not on the boolean, since the column `true - b` has a catch-all, whereas the result splitting on projection R.p is complete.

**Comment by andreasabel** [comment]
To fix this, we probably need to join the `Block` and `BlockP` case in `Coverage.Match`.  Currently, a blocking variable overrides a blocking result, see `choice`.

**Comment by andreasabel** [comment]
Here is a simpler example:

``` agda
open import Common.Equality
open import Common.Prelude
open import Common.Product

thing : Bool → Bool × Bool
proj₁ (thing true) = false
proj₁ (thing false) = true
proj₂ (thing b) = b

test : ∀ b → proj₂ (thing b) ≡ b
test b = refl
```

**Comment by andreasabel** [comment]
Jesper's `--exact-split` appropriately warns me here, though.

**Comment by asr** [comment]
> andreasabel added this to the 2.5.2 milestone

Why you didn't use the 2.5.1.1 milestone?

**Comment by andreasabel** [comment]
Because I was not sure when to fix this.  I thought 2.5.1.1 is for the next bug fix release.

**Comment by asr** [comment]
I think 2.5.1.1 is for the next stable release.

**Comment by UlfNorell** [comment]
No, we only release 2.5.1.1 if there aren't any compatibility breaking changes--something that seems exceedingly unlikely with the new branch policy. We did make room in the version numbers to allow 2.5.2 to be released from stable for this very reason.

**Comment by WolframKahl** [comment]
On Mon, Apr 18, 2016 at 11:41:25AM -0700, Andrés Sicard-Ramírez wrote:

> I think 2.5.1.1 is for the next stable release.

That forces me to have quite horribly long version numbers for all the intermediate development versions until then: 2.5.1.0.1, 2.5.1.0.2, ...

**Comment by andreasabel** [comment]
No, only 2.5.1.1, 2.5.1.2, etc.

**Comment by WolframKahl** [comment]
I was referring to my own versions, that is, every time I install the current development version. Right now, `Agda.cabal` says:

```
name:            Agda
version:         2.6.0
```

But since that won't be changing at least until the next release, and since `2.5.1 < 2.6.0 ≮ 2.5.1.1`, using that version number for anything can only be misleading. So the next time I install the current development version, I will call it 2.5.1.0.1, since `2.5.1 < 2.5.1.0.1 < 2.5.1.1`, and there is ample space for more installations before the next release, which, according to the previous posts here, may well come out with number 2.5.1.1.

In this state I actually would consider it more natural if the `master` branch used a prefix that falls between the previous release and the lexically-least envisaged next release, that is:

```
name:            Agda
version:         2.5.1.0
```

**Comment by asr** [comment]
I filed #1941 for continuing the discussion on version numbers.

**Comment by andreasabel** [comment]
This is nothing copattern specific:
```agda
noR : ∀ b → Answer b → Bool
noR true yes = true
noR b (dunno .b) = false

test-noR : ∀ b → noR b (dunno b) ≡ false
test-noR b = refl
```
This fails as well.

Thus, I consider this issue fixed.
