### ISSUE TITLE
Travis timeout with GHC 7.8.4 but not with GHC 7.6.3

### ISSUE THREAD

**Issue by asr** [agda/agda#1835]
Andreas wrote:

> The script for ghc-7.8 calls it with -j32 while ghc-7.6 is not called
> with any -j option, am I right here?

I wrote:

> In the script for building Agda we are not using explicitly the -j option, but
> it seems GHC 7.6.3 and 7.8.4 have a different default behaviour related to this option. Testing...

**Comment by asr** [comment]
The `-j` option was added in GHC 7.8.1 ([Release notes for version 7.8.1](https://downloads.haskell.org/~ghc/7.8.1/docs/html/users_guide/release-7-8-1.html)):

> GHC now has a parallel compilation driver... you may also specify -jN in order to compile N modules in parallel.

**Comment by andreasabel** [comment]
From the first build for ghc 7.8 which did not complete in 2h (build 636) https://travis-ci.org/agda/agda/jobs/106969287, the command travis executes starts with

```
/usr/local/ghc/7.8.4/bin/ghc --make -fbuilding-cabal-package -O -j32 -static -dynamic-too 
```

When it still just took over one hour (build 634) https://travis-ci.org/agda/agda/jobs/106821668, it said

```
/usr/local/ghc/7.8.4/bin/ghc --make -fbuilding-cabal-package -O -j16 -static -dynamic-too
```

Unluckily, the build 636 hit your harmless patch "fixing compilation with ghc 7.10.3".

Maybe if we succeed to put `-j3` or something like that, it will build really fast, haha.

**Comment by asr** [comment]
> Maybe if we succeed to put -j3 or something like that, it will build really fast, haha.

Yes. I'm testing in my own repository. Right now I getting faster builds with `-j1` than `-j4`. I guess it is related to the 4GB of memory available.

**Comment by WolframKahl** [comment]
Try adding `+RTS -S -M3.5G -RTS`?

**Comment by asr** [comment]
@WolframKahl thanks for the advice. Using `-j2` we have very good building times on Travis, so I did not plan to make new tests. If you get better times, please let me know.

**Comment by andreasabel** [comment]
@asr: Thanks for fixing this!  Yes, now the times look very good, it is better than before it stopped working!

Are you in contact with travis?  You could let them know how we fixed the problem, and that the -j ncpus of cabal is not a good default.  They might then know next time someone complains how to give good advice..

**Comment by asr** [comment]
Yes, I told Travis about the problem and the solution. I also asked them to restore the default timeout for Agda. I'm waiting their answer.

**Comment by asr** [comment]
> it is better than before it stopped working!

Yep!
