### ISSUE TITLE
UHC back-end: Wrong documentation in Agda.cabal?

### ISSUE THREAD

**Issue by asr** [agda/agda#1836]
Agda.cabal says:

```
  -- required to make the code compile, as the EH library is not present when the uhc backend is disabled
  if flag(uhc)
    cpp-options:    -DUHC_BACKEND
```

I don't understand the mix of `when the uhc backend is disabled` and `if flag(uhc)`. In addtion, after some tests I don't know when the `-DUHC_BACKEND` option is necessary.

Also note that
- `cpp-options:    -DUHC_BACKEND` is duplicated and
- the documentation for the `uhc` flag says `requires GHC 7.6 or newer`.

**Comment by phile314** [comment]
@asr I can push in master, right?

**Comment by asr** [comment]
Right.
