### ISSUE TITLE
Cease hostilities between libraries

### ISSUE THREAD

**Issue by m0davis** [agda/agda#1838]
When libraries conflict, Jeff Bezos wins.

As Ulf mentioned [here](https://lists.chalmers.se/pipermail/agda/2016/008380.html), the agda-stdlib and agda-prelude libraries are incompatible because of the duplication of BUILTIN declarations. Yet another reason for incompatibility is due to duplication of module names (e.g. Data.Nat.Properties).

As for BUILTIN duplication, may I take it that there are already plans to fix this? I read in the [TODO for maint-2.4](https://github.com/agda/agda/blob/maint-2.4/TODO) that the following features are planned:
- unify primitive and {-# BUILTIN #-}
- handle clashing builtin things

Could we also have a feature to handle clashing module names?

**Comment by UlfNorell** [comment]
The current thinking is that we should pull out the builtins into a core library, possibly putting that in the same place as `Agda.Primitive`. Not sure what to do about the module clashes. The simplest thing would be to just agree on names that don't clash.

**Comment by andreasabel** [comment]
@m0davis Since you mentioned a TODO file, I checked upon it.  It was last modified in Nov 2007.  But it is an interesting historic document.  Some issues mentioned there have not progressed in the last 8 years. (smile)

**Comment by phile314** [comment]
I think reserving the Agda.\* namespace for builtin/core libraries should be fine.

I assume this would be a separate file from Agda.Primitive, e.g. Agda.Core?

**Comment by m0davis** [comment]
Lol about the TODO. I did not check the date.

The mentioned solution for builtins sounds fine to me.

As for module name clashes, I suggest that there be an optional prefix supplied with --library. E.g., for a project that mostly uses agda-prelude but sometimes wants modules from agda-stdlib, we could have:

```
{-# OPTIONS --library=Standard;agda-stdlib #-}
{-# OPTIONS --library=agda-prelude #-}

import Data.Nat.Properties
import Standard.Data.Nat.Properties
```

**Comment by UlfNorell** [comment]
I put all the builtins in `Agda.Builtin.*` (83b3922 and subsequent commits) and updated standard library and test suite. Working on fixing agda-prelude.

The problem with clashing module names still remains.

**Comment by np** [comment]
Should we have something such as PackageImports in GHC?

**Comment by UlfNorell** [comment]
Fixed agda-prelude as well.

Package imports would be one way to go, but would require some design work (and implementation work). I still haven't given up hope on simply renaming the offending modules though. Currently the clashing modules are
- `Data.List`
- `Data.List.Properties`
- `Data.Nat.DivMod`
- `Data.Nat.GCD`
- `Data.Nat.Properties`
- `Data.Rational`

Does anyone have an alternative to `Data`?

**Comment by np** [comment]
I would say that more often than not we could simply remove the 'Data.' prefix.
However Nat and Rational could go under a Num or Numeric.

**Comment by UlfNorell** [comment]
How about
- `Numeric`
  - `Nat`
  - `Rational`
- `Container`
  - `List`
  - `Foldable`
  - `Traversable`
- `Structure`
  - `Monoid`
  - `Smashed`

and just leave `Data.TreeRep` in `Data`?
