### ISSUE TITLE
Re-enable Agda in Stackage (unordered-containers 0.2.6)

### ISSUE THREAD

**Issue by asr** [agda/agda#1840]
I removed Agda 2.4.2.5 from Stackage because it doesn't support unordered-containers 0.2.6 (see https://github.com/fpco/stackage/issues/1222). This problem was fixed in #1779, so I will re-enable Agda after realising 2.5.1.

**Comment by DanBurton** [comment]
When Agda is ready to be re-enabled, please also request that we re-enable agda-snippets, too. Thanks!

**Comment by asr** [comment]
OK.

**Comment by asr** [comment]
> When Agda is ready to be re-enabled, please also request that we re-enable agda-snippets, too. Thanks!

@DanBurton I wrote the PR https://github.com/fpco/stackage/pull/1369 for re-enabling Agda. After the PR be merged, please re-enable agda-snippets.

**Comment by asr** [comment]
The PR was merged, so I'm closing the issue.
