### ISSUE TITLE
Agda warns of changed operator treatment even when no operators used

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#1841]
``` agda
module _ (A : Set) where

record R : Set where
  field f : A

test : A → R
f (test x) = x
```

reports

```
Could not parse the left-hand side f (test x)
Operators used in the grammar:
  None
(the treatment of operators has changed, so code that used to parse
may have to be changed)
when scope checking the left-hand side f (test x) in the definition
of test
```

The warning should not be issued when no operators are used anyway.
Further, the warning should include Agda version numbers (changed between which versions)...
@nad

**Comment by nad** [comment]
> Further, the warning should include Agda version numbers (changed between which versions)...

I think this rather annoying warning should only be included in 2.5.1, and then removed. Do you agree? In that case I don't see the point of including version numbers.

**Comment by asr** [comment]
> I think this rather annoying warning should only be included in 2.5.1, and then removed. 

I disagree. A previous user could use Agda > 2.5.1 without using Agda 2.5.1.

**Comment by asr** [comment]
> Further, the warning should include Agda version numbers (changed between which versions)...

Only the version where the change was made it is necessary.

**Comment by nad** [comment]
> I disagree. A previous user could use Agda > 2.5.1 without using Agda 2.5.1.

The warning is rather noisy, so I'd prefer to remove it as soon as possible. I guess it would be fine to keep it in bug-fix releases (Agda 2.5.1.x?).

**Comment by andreasabel** [comment]
I guess the non-controversial part is not to print

```
Operators used in the grammar:
  None
(the treatment of operators has changed, so code that used to parse
may have to be changed)
```

if there are no operators in use.
Maybe this part could be implemented and then bike-shed the rest of my request?

**Comment by andreasabel** [comment]
Thanks!
