### ISSUE TITLE
internal error  in compilation, src/full/Agda/TypeChecking/Reduce/Monad.hs:174

### ISSUE THREAD

**Issue by mechvel** [agda/agda#1843]
Please, download the code from
http://www.botik.ru/pub/local/Mechveliani/agdaNotes/bugFeb14-2016.zip
(3 Kb).
This is on  Agda-2.5.0.20160213   (Agda 2.5.1 candidate),
ghc-7.10.2,  MAlonzo,  Debian Linux.

`> agda -c -i . -i $agdaStLib Main.agda`

reports

---

...
Compiling Structures1 in /home/mechvel/agda/tosave/bugs/feb14-2016/Structures1.agdai to
/home/mechvel/agda/tosave/bugs/feb14-2016/MAlonzo/Code/Structures1.hs

Unbound name: Structures1.OfMonoidHomo.recCon-NOT-PRINTED [209]@263218534
An internal error has occurred. Please report this as a bug.
## Location of the error: src/full/Agda/TypeChecking/Reduce/Monad.hs:174

If  Main.agda  is merged to  Structures1.agda,  then it is compiled.

**Comment by UlfNorell** [comment]
This was already reported as #1839 and fixed by f575d9a.

**Comment by asr** [comment]
Thanks for adding the `duplicate` label. I plan to add this label and remove the other labels on duplicate issues.

**Comment by mechvel** [comment]
On Mon, 2016-02-15 at 04:40 -0800, Ulf Norell wrote:

> This was already reported as #1839 and fixed by f575d9a. 
> 
> —
> Reply to this email directly or view it on GitHub.

What does this mean  
f575d9a ?  where to find it ?

Does the to-day Development version fix this bug?

Regards,

---

Sergei

**Comment by UlfNorell** [comment]
It's a hash referring to a particular commit. You should be able to click on it if you view this issue on github. It is included in the current master branch.
