### ISSUE TITLE
Missing UHC-backend tests using the standard library

### ISSUE THREAD

**Issue by asr** [agda/agda#1844]
We had a full MAlonzo test for the standard library (I couldn't find it) but it was disabled because it was too slow.

Right now, the compilers tests (UHC and MAlonzo) using the standard library are disabled for the same reason (test/Compiler/Tests.hs):

```
-- The Compiler tests using the standard library are horribly
-- slow at the moment (1min or more per test case).
-- Disable them by default for now.
```

Since we have very good building times on Travis, we should at least to add the MAlonzo test for the standard library on Travis.

**Comment by andreasabel** [comment]
I strongly agree.

**Comment by UlfNorell** [comment]
They don't have to be that slow. If we could make sure to
- use the interface files created during library-test
- share the MAlonzo directory between the different tests

it shouldn't be too bad. On my machine it's 10s to read interfaces, 7s to generate Haskell code and another 1m20s to run ghc. I guess you'd need to not run the tests in parallel if they're sharing the Haskell code though, but on the other hand only the first test would have to compile anything.

**Comment by phile314** [comment]
Yep, the main problem has been that all test cases compiled the stdlib from scratch.

The stdlib Haskell FFI code also needs to be fixed prior to re-enabling those tests: https://github.com/agda/agda/issues/1788 .

**Comment by asr** [comment]
I'll add a test case for testing MAlonzo on all the standard library.

**Comment by asr** [comment]
From the commit message of 96c196d5c978859fae7c16a3b22d3ce8a856bdd1:

> The stdlib tests are disabled anyway, I am commenting them out for now as their presence alone caused some unnecessary setup work involving GHC package databases to be performed.

@phile314 After reverting the above commit, I found that the disabled tests

```
RFInclude "Compiler/.*/with-stdlib"
```

are ignored, that is, `make compiler-tests` runs those tests. Is this problem the "unnecessary setup work" you are talking about?

**Comment by phile314** [comment]
I think the stdlib no longer requires any cabal ffi package to be installed, so this might be as easy as removing the ffi setup code from the tests. Will take a look.

**Comment by UlfNorell** [comment]
Yes, I removed the ffi package dependency.

**Comment by asr** [comment]
In addition to the current compilers tests (`simple`, `special` and `with-stdlib`), we could add a new `stdlib` test using the `AllStdLib.agda` file. In this case, the MAlonzo files could be generated in the `stdlib` directory and they could be used by the `with-stdlib` tests.

**Comment by phile314** [comment]
Done for MAlonzo, blocked on https://github.com/agda/agda/issues/1866 for UHC.

**Comment by asr** [comment]
Philipp fixed ~~#1866~~, blocked on #1879.

**Comment by asr** [comment]
I'm keeping this issue for the missing UHC-backend tests. For the performance of the GHC-backend tests I filed #1907.

**Comment by asr** [comment]
I changed the milestone to 2.5.2.

**Comment by UlfNorell** [comment]
Moved to agda-uhc.
