### ISSUE TITLE
Release Agda 2.5.1 release candidate 2

### ISSUE THREAD

**Issue by asr** [agda/agda#1845]
I'm using this issue for keeping track of _some_ changes related to RC 2.

Last update: 2016-02-23
- Fixed regressions
  - #1770
  - #1839
  - #1847
- Incompatibilities
  - Addition of the Agda.Builtin modules
  - Fix of #1726
  - Fix of #1759

**Comment by asr** [comment]
I think we can release RC 2. Any objection?

I would like release 2.5.1 before the next Agda meeting.

**Comment by UlfNorell** [comment]
Yes I agree. I don't think any of the still open issues tagged with 2.5.1 are super serious and we could very well bump them to the next release.

**Comment by asr** [comment]
Blocked on #1928.

**Comment by asr** [comment]
Starting...

**Comment by asr** [comment]
I have tested the installation of the second RC [Agda-2.5.0.20160412.tar.gz](http://www1.eafit.edu.co/asr/tmp/Agda-2.5.0.20160412.tar.gz) in Ubuntu 12.04.5 64-bits with:
- GHC 7.6.3, 7.8.4 and 7.10.3, and
- GHC 7.10.3 and the `uhc` flag

Could someone test the installation of the second RC on Windows and/or Mac OS using the following instructions:

```
  $ tar xzf Agda-2.5.0.20160412.tar.gz
  $ cd Agda-2.5.0.20160412
  $ cabal install
```

If you have Mac OS and GHC 7.10.*, please also test

```
$ cabal install -f uhc
```

**Comment by UlfNorell** [comment]
- [x] Windows 8.1, ghc-7.10.3
- [x] Mac OS X 10.10, ghc-7.10.3
- [x] Mac OS X 10.10, ghc-7.10.3 -f uhc

**Comment by UlfNorell** [comment]
All good.

**Comment by asr** [comment]
Done.
