### ISSUE TITLE
Remove MAlonzo pragmas from Primitive.agda

### ISSUE THREAD

**Issue by asr** [agda/agda#1846]
I asked:

> Why aren't UHC pragmas in Primitive.agda?

Ulf wrote:

> I'm pretty sure we don't actually need the MAlonzo pragmas for levels.

**Comment by UlfNorell** [comment]
Turns out you can't remove the `COMPILED_TYPE` or you can't map level polymorphic to Haskell functions.

**Comment by asr** [comment]
It almost seems that the issues are being fixed _before_ I report them... Great!
