### ISSUE TITLE
Unnamed variable missing from context

### ISSUE THREAD

**Issue by nad** [agda/agda#1848]
``` agda
postulate
  A : Set

data D : Set where
  c : D → D

postulate
  P : D → Set

foo : (x : D) → P x
foo _ = {!!}

-- The unnamed variable is part of the context:

-- Goal: P .x
-- ————————————————————————————————————————————————————————————
-- .x : D

bar : (x : D) → P x
bar (c _) = {!!}

-- The unnamed variable is not part of the context:

-- Goal: P (c _)
-- ————————————————————————————————————————————————————————————

-- This can, in more complicated situations, make the goal type harder
-- to understand.
```

This problem seems to go back at least to Agda 2.3.2. I've given this issue a high priority, because the inconsistent treatment of the different underscores suggests to me that something is broken.

**Comment by andreasabel** [comment]
Well, in the second case there is no source for a name for the variable `_`.  The constructor has type `(_ : D) -> D`, and the pattern gives name `_` to it, so it stays `_`.  The context printer drops variables that have no name (for whatever reason).  In the first case, the name `x` comes from the type of `foo`.  It is not entirely surprising what happens here, and nothing seems particularly broken.  Maybe we are lacking a special case for a nameless variable, and have to invent a name for it.
