### ISSUE TITLE
Version number in the documentation

### ISSUE THREAD

**Issue by asr** [agda/agda#1849]
In https://github.com/agda/agda/issues/1831#issuecomment-183365106 @phile314 wrote:

> I just read up on how readthedocs.org handles releases [1].
> 
> According to the Agda release instructions, we create a git tag for a new release. Readthedocs should handle this fine and should add a version "2.5.1" documentation release without any manual intervention.
> 
> [1] http://docs.readthedocs.org/en/latest/versions.html

It isn't working. I created a Git tag for Agda 2.5.1 RC 1, so the stable documentation should show the version number 2.5.0.20160213, but the version number showed [here](http://readthedocs.org/projects/agda/downloads/pdf/stable/) is 2.5.0.

Note that in doc/user-manual/conf.py we have the version number hard-wired

```
# The short X.Y version.
version = '2.5.0'
# The full version, including alpha/beta/rc tags.
release = version
```

I don't know if it is causing this issue.

**Comment by phile314** [comment]
I assume that the documentation always uses the version hard-wired in doc/user-manual/conf.py in the generated html pages/pdfs.

What surprises me more is that one cannot explicitly select version 2.5.0.20160213 on readthedocs (press on "v:latest" in bottom left corner to see the menu).  If you compare this with the Idris documentation, you can select all the different versions in Idris, e.g. http://docs.idris-lang.org/en/v0.10/ .

**Comment by asr** [comment]
> What surprises me more is that one cannot explicitly select version 2.5.0.20160213 on readthedocs

I didn't change the version number in the `version` field of the conf.py file in the RC. This should explain the above problem.
