### ISSUE TITLE
Broken type-checking of the standard library with Agda 2.5.1 RC 1

### ISSUE THREAD

**Issue by asr** [agda/agda#1852]
After the addition of the new `Agda.Builtin.*` (see https://github.com/agda/agda/issues/1838#issuecomment-184754304) the master branch of the standard library doesn't type-check with Agda 2.5.1 RC 1.

I think the addition of  the `Agda.Builtin.*` was untimely because we are in a middle of a release process and we don't need additional problems (e.g. were the  `Agda.Builtin.\* tested with the UHC backend, Windows, cpp, Agsy, etc). 

Anyway, for fixing this issue we can (in my order of preference):
1. Revert the addition of the `Agda.Builtin.*`, or
2. Create a 2.5.0.20160213 branch in the standard library compatible with Agda 2.5.1 RC 1 and announce this new branch in the mailing lists, or
3. Release a second RC.

**Comment by UlfNorell** [comment]
We are releasing a second RC anyway aren't we? There's been quite a few fixes since RC 1.

**Comment by asr** [comment]
RC 1 was released three days ago. I was waiting for additional feedback before taking a decision about release a second RC (see #1845).

**Comment by UlfNorell** [comment]
The `Agda.Builtin` stuff needs to go in the release, so I think it would be good if we released a candidate with it (and all the other changes).

**Comment by UlfNorell** [comment]
It would make sense to create a `2.5.0.20160213` tag in the standard library though, so we don't have to rush out RC 2. There are still some pending changes (like #1759) that would be good to include in the new candidate.

**Comment by asr** [comment]
OK. I'll release RC 2.

**Comment by asr** [comment]
> It would make sense to create a 2.5.0.20160213 tag in the standard library though, so we don't have to rush out RC 2.

I was writing the same...
