### ISSUE TITLE
UHC backend can't handle renamed identifiers

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#1855]
The UHC backend uses concrete names when picking names in the compiled code. This breaks when you rename things. Example:

``` agda
open import Common.Prelude renaming (return to foo)

main : IO Unit
main = foo unit
```

```
Compilation error:
Grin to ByteCode
(Internal) GRIN ByteCode location names not in scope:
  Agda.Common.IO.foo_8_@FFE_@nl.uu.agda.top-level-def
```

For reasons I don't understand, this only triggers with `--ignore-interfaces`. If you compile again everything is fine.

**Comment by phile314** [comment]
We should replace all renamed symbols by their original QName during the translation to Treeless.

**Comment by phile314** [comment]
Related GHC backend problem: https://github.com/agda/agda/issues/728

**Comment by UlfNorell** [comment]
I'd rather not mess with the `QName`s during treeless translation. They make perfect sense as they are. The problem is the UHC backend relying on the concrete name instead of the `NameId`. If you really must have the concrete name it was defined as it would probably work to do

``` haskell
getConcreteName q = nameConcrete . defName <$> getConstInfo q
```

It would make most sense to put that at the point where you generate the name for the backend.

**Comment by phile314** [comment]
Technically, I could also use the nameIds, but this leads to very cryptic code, see e.g. the MAlonzo generated code.

If I just put it in ToTreeless, all tests go through and renaming works in both the GHC/UHC backend. See https://github.com/phile314/agda/commit/e93c9a60d7c79723acf56252f92cee6c7283b9e7 . I don't care where this ends up in the Treeless pipeline, I could also add it as a final transformation.

Having this in Treeless makes it much easier for the backends to do the right thing.

**Comment by phile314** [comment]
@UlfNorell Are you strongly against adding this to Treeless? I haven't yet pushed anything to the Agda repo, but I really think adding this is the right way of solving this issue once and for all.

**Comment by UlfNorell** [comment]
I don't like it since it adds an extra invariant to Treeless (namely that the `nameConcrete` fields are consistent for all `QName`s). We would need to take care to maintain this when changing things around. To me it feels much more natural to add a function that gives you a stable name hint for a `QName`, and use that when generating the names. That way when you look at the name generation code it's clear what's going on.
