### ISSUE TITLE
UHC prints floats with too low precision

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#1856]
``` agda
open import Common.Prelude
open import Agda.Builtin.Float

main = putStrLn (primShowFloat (primFloatSqrt 2.0))
```

With GHC backend: `1.414213562373095`
With UHC backend: `1.414214`

I guess this isn't super important, but it complicates testing since we assume identical output from GHC and UHC backends.

**Comment by asr** [comment]
After the fix of https://github.com/UU-ComputerScience/uhc/issues/87, UHC prints doubles with better precision, however UHC's precision is still lower than GHC's precision. For example,

``` agda
main = putStrLn (primShowFloat (primFloatSqrt 2.0))
```

GHC (8.0.1): `1.4142135623730951`
UHC (https://github.com/UU-ComputerScience/uhc/commit/cdd8252b06771f07c001fa4ab335dfffadf59820): `1.414213562373095`

I closed the issue by adding a test case which only is enabled for the UHC backend.
