### ISSUE TITLE
Add UHC backend Unicode support

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#1857]
``` agda
open import Common.Prelude

main = putStrLn "BEFORE ∀ AFTER"
```

Output: `BEFORE`

**Comment by asr** [comment]
This is an UHC issue (see https://github.com/UU-ComputerScience/uhc/issues/72).

**Comment by phile314** [comment]
UHC is not getting unicode support for the time being:

>  atzedijkstra commented 4 hours ago
> 
> Currently (indeed) other source code changes have higher priority, for the time being there will be no unicode support (unless somebody else will work on this :-))

**Comment by WolframKahl** [comment]
On http://agda.readthedocs.org/en/latest/tools/compilers.html#uhc-backend it says:

```
The UHC backend currently does not support Unicode strings. See issue 1857 for details.
```

However, there are no details here, either, and from the UHC github pages I also find no link to documentation.

What does “does not support Unicode strings” mean exactly? What is the specification of the UHC-Haskell datatypes `Char` and `String` that UHC implements?

**Comment by phile314** [comment]
ASCII for sure, probably also 8bit encodings like ISO-8859-1.

To be perfectly clear, this only applies to string values, not to identifier/symbol names. Agda Unicode identifiers are supported.

**Comment by atzedijkstra** [comment]
I have added to UHC (github head) support for the given failing test case, see comments at uhc github

**Comment by asr** [comment]
@atzedijkstra, I confirm this is working on UHC master:

```
$ uhc --version
ehc-1.1.9.5, revision master@f98b70d786, timestamp 20161127 -0500 153715

$ cat Test.hs
main :: IO ()
main = putStrLn "BEFORE ∀ AFTER"

$ uhc Test.hs
./Test
BEFORE ∀ AFTER
```

Could you release UHC 1.1.9.5, please.

**Comment by atzedijkstra** [comment]
I have update the lib/runtime (backaned bc only) to also read unicode correctly and released (to hackage) 1.1.9.5.

cheers,
Atze

**Comment by asr** [comment]
> I have update the lib/runtime (backaned bc only) to also read unicode correctly and released (to hackage) 1.1.9.5.

Thanks!

Did you forget to push the tag (ie. `git push --follow-tags`) in GitHub? I don't see 1.1.9.5 [here](https://github.com/UU-ComputerScience/uhc/releases).

**Comment by atzedijkstra** [comment]
I did forget actually :-), should be ok now.

A

**Comment by asr** [comment]
It is ok now. Thanks!
