### ISSUE TITLE
[emacs] agda2-display-implicit-arguments should be sticky and invokable before a file is loaded

### ISSUE THREAD

**Issue by m0davis** [agda/agda#1858]
agda2-display-implicit-arguments a.k.a. C-c C-x C-h defaults back to hiding implicit arguments whenever a file is loaded. Trying to turn this mode on before a file is loaded results in "Error: First load the file."

When debugging tactics, this is especially a problem because of a catch-22: an error may occur in a tactic and we would like to view the implicits in the error message, but we can't because the file hasn't been loaded ... because it has an error.

We should be able to set the display of implicits and have it stick.

**Comment by andreasabel** [comment]
Suggested workaround: How about adding

``` agda
{-# OPTIONS --show-implicit #-}
```

to the top of your file?  This is how I do it, I don't use C-c C-x C-h.

**Comment by m0davis** [comment]
@andreasabel Thanks, that works for me.
