### ISSUE TITLE
Replace 'MAlonzo' by 'GHC backend' in the --help option

### ISSUE THREAD

**Issue by asr** [agda/agda#1859]
```
$ agda --help | grep MAlonzo
  -c      --compile, --ghc                            compile program using the MAlonzo backend (experimental)
          --ghc-flag=GHC-FLAG                         give the flag GHC-FLAG to GHC when compiling using MAlonzo
          --no-main                                   when compiling using the MAlonzo or UHC backend (experimental), do not treat the requested module as the main module of a program
```

**Comment by phile314** [comment]
Looks like someone else is also reading the [Agda reddit](https://www.reddit.com/r/agda/comments/46dwg7/malonzo/) ;-)

Maybe add an entry to the changelog about the name change?

**Comment by asr** [comment]
> Looks like someone else is also reading the Agda reddit ;-)

It was a coincidence. BTW, Andreas wrote (private communication): "MAlonzo is the "Monadic Alonzo" as far as I know."

> Maybe add an entry to the changelog about the name change?

We are moving to rename 'MAlonzo' by 'GHC backend'. The entry in the CHANGELOG will be added after finishing  this renaming.

**Comment by asr** [comment]
I forgot to mention that I changed the 'MAlonzo' label by 'ghc-backend' in the bug tracker.
