### ISSUE TITLE
Update to UHC 1.1.9.3

### ISSUE THREAD

**Issue by phile314** [agda/agda#1864]
@asr Should this go into 2.5.0 or not? I don't have a strong opinion on it, but I suggest to wait until after the 2.5.0 release.

**Comment by asr** [comment]
> Should this go into 2.5.0 or not?

Yes, please.

**Comment by asr** [comment]
I could install UHC 1.1.9.3 without problems, so I'll make the update.

**Comment by UlfNorell** [comment]
I'm also running UHC 1.1.9.3.

**Comment by asr** [comment]
> I'm also running UHC 1.1.9.3.

Great!

**Comment by asr** [comment]
It only was necessary to update the documentation. I kept the support for UHC 1.1.9.2 for testing purpose (e.g. performance testing).
