### ISSUE TITLE
Better documentation of DISPLAY

### ISSUE THREAD

**Issue by nad** [agda/agda#1876]
I've received an error message referring to recursive display forms. This suggests to me that the thing on the right-hand side of a DISPLAY pragma can be subjected to further rewriting. Is this the case? Please make the documentation in the CHANGELOG more precise.

**Comment by UlfNorell** [comment]
It'd take you five seconds to find out by trying it. Feel free to update the change log when you figure it out.

The recursive display form error is from #1644.
