### ISSUE TITLE
agda2-show-context can misreport the type of variables brought into context by 'let'

### ISSUE THREAD

**Issue by m0davis** [agda/agda#1878]
The type of `A≡A` (as reported by `agda2-show-context`) is incorrect in the hole of `baz`.

```
open import Agda.Builtin.Equality

postulate
  foo : (A : Set) → A ≡ A

helper : {W : Set} (A : Set) → W → W ≡ A → (A → Set) → Set
helper A w refl f = f w

bar : (A : Set) → A → Set
bar A a = let A≡A = foo A in helper A a (foo A) {!!} -- A≡A : A ≡ A

baz : (A : Set) → A → Set
baz A a = let A≡A = foo A in helper A a (foo A) (λ a' → {!!}) -- A≡A : a ≡ a
```

**Comment by andreasabel** [comment]
Seems like the fix for #1112 was not complete.  (See also #888 where this functionality was added.)

**Comment by UlfNorell** [comment]
Here's a simpler example:

``` agda
f : (A : Set) → A → Set → Set
f A x = let y = x in λ B → {!!} -- y : x
```

The problem is that the code that adds the let bindings completely ignores the context in which they were defined. Fix incoming.

**Comment by andreasabel** [comment]
Mmh, I am also fixing this...  Should have taken ownership.  Usually there was not such eagerness on bug fixing... :)
Ok, I can step back.  You fix with 'getOpen' seems to be more principled.
