### ISSUE TITLE
Missing custom per-user file for setting the number of parallel tests

### ISSUE THREAD

**Issue by asr** [agda/agda#1881]
The `--ghc-flag=-j3` option was introduced in 7f608f0.

It seems this option is unnecessary (is the option been ignored?). For example, in my four processors machine

```
$ getconf _NPROCESSORS_ONLN
4
```

running `make compiler-test` reports the following figures:

| `AGDA_TESTS_OPTIONS` value | Time compiling `AllStdLib` |
| --- | --- |
| `-i -j $(shell getconf _NPROCESSORS_ONLN)` (default) | 400s |
| `-i -j3` | 103s |
| `-i -j2` | 79s |
| `-i -j1` | 61s |

From the above table, we could replace the `--ghc-flag=-j3` option using the `AGDA_TESTS_OPTIONS` variable.

In addition, the `3` value shouldn't be hard-wired.

I propose to define `AGDA_TESTS_OPTIONS` using something like

```
AGDA_TESTS_OPTIONS?=-i -j$(JOBS)
```

where `JOBS` is a variable defined by _each_ user in a file outside Git control.

**Comment by phile314** [comment]
Note that the "-j" flag in AGDA_TESTS_OPTIONS specifies how many tests are run in parallel, whereas the "ghc -j" flag specifies if GHC should use parallel compilation for that specific test case.

AGDA_TESTS_OPTIONS influences all tests using the Haskell test runner (compiler, latex, fail, succeed).

Adding an optional file for custom per-user settings is fine with me, but we should provide some sensible defaults.

**Comment by asr** [comment]
> Note that the "-j" flag in AGDA_TESTS_OPTIONS specifies how many tests are run in parallel, whereas the "ghc -j" flag specifies if GHC should use parallel compilation for that specific test case.
> 
> AGDA_TESTS_OPTIONS influences all tests using the Haskell test runner (compiler, latex, fail, succeed).

Thanks for the explanation.

> Adding an optional file for custom per-user settings is fine with me, but we should provide some sensible defaults.

What about the half of `getconf _NPROCESSORS_ONLN`?

**Comment by UlfNorell** [comment]
Looking at the time reported by the test suite for individual tests is very misleading. For instance with `-j8` I get 5.7s reported for the first `MAlonzo/simple/Arith`, but with `-j1` it reports 1.4s.

On my machine (your mileage may vary of course) I get

| `-jN` | `--ghc-flag=-jM` | AllStdLib | Total |
| --- | --- | --- | --- |
| 8 | 3 | 2m6s | 2m35s |
| 8 | 1 | 1m30s | 2m59s |

As you can see the time reported for AllStdLib is not a good predictor for the actual time taken by the tests.

**Comment by asr** [comment]
> Looking at the time reported by the test suite for individual tests is very misleading. For instance with -j8 I get 5.7s reported for the first MAlonzo/simple/Arith, but with -j1 it reports 1.4s.

It doesn't seem misleading. I got the following times for MAlonzo/simple/Arith:

| `-jN` | time |
| --- | --- |
| 4 | 4.01s |
| 3 | 2.08s |
| 2 | 1.84s |
| 1 | 1.77s |

**Comment by UlfNorell** [comment]
What I mean is that it's hard to tell what the actual runtime of the tests are from the individual reported numbers (as you can clearly see from the AllStdLib case). For instance given your table for Arith, which `N` would you say is best?

**Comment by phile314** [comment]
Total running time != sum of runtime of each test. (except for -j1)

If you enable parallel test runs, the individual test cases tend to get slower, but as they are executed in parallel total running time of all tests often still gets better.

| -jN | time (compiler-test including UHC) |
| --- | --- |
| 1 | 13m19.701s |
| 4 | 4m22.433s |
| 6 | 4m13.189s |
| 7 | 2m57.451s |
| 8 | 2m55.975s |

I have run all tests with "--ghc-flag=-j3" on an eight core machine.

**Comment by asr** [comment]
Thanks for the explanations.

After c563c54, we can use the `mk/parallel-tests.mk` file for setting the number of
parallel tests, e.g.

```
PARALLEL_TESTS = 4
```
