### ISSUE TITLE
Split the compiler tests

### ISSUE THREAD

**Issue by asr** [agda/agda#1882]
@phile314 can we split the compilers by type (i.e. simple, special and with-stdlib) and backend (i.e. GHC and UHC)?

I don't want to wait for _all_ the tests when I'm testing a concrete type with a concrete backend.

**Comment by UlfNorell** [comment]
You can run specific tests with the `-p` option:

`make compiler-test AGDA_TESTS_OPTIONS="-p MAlonzo/simple"`

**Comment by asr** [comment]
Thanks!
