### ISSUE TITLE
Emacs agda-mode graphical glitch on ⟫ character (double angle bracket)

### ISSUE THREAD

**Issue by karljs** [agda/agda#1883]
Using the ⟫ character (achievable with `\>>`) in an Agda file seems to cause some unusual highlighting bugs.  It appears with the colors inverted as if the cursor were on it and also causes curly braces to exhibit the same effect.

You can see what I mean in the following screenshot, showing some code I copied from an online discussion.

<img width="353" alt="screen shot 2016-02-29 at 23 31 54" src="https://cloud.githubusercontent.com/assets/317063/13420697/3987949c-df3d-11e5-8eae-a153e8b66902.png">

A few notes that might be helpful: 
- If I copy the character into another buffer, it displays normally there
- The cascading effects on the curly brackets affect the entire rest of the buffer
- Emacs' `describe-char` function doesn't show anything unusual, but reads `character: ⟫ (displayed as ⟫)` where the first occurrence looks normal and the second is inverted as in my screenshot.
- While I am using the `default-faces` option for `agda2-highlight-face-groups`, this seems unrelated.  Using the defaults causes the same issue.

**Comment by andreasabel** [comment]
Cannot confirm this on my emacs.

```
GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.16.6)
 of 2015-09-18 on lgw01-52, modified by Debian
Copyright (C) 2015 Free Software Foundation, Inc.
```

Can you research which emacs version / fonts / operating systems this concerns?

**Comment by karljs** [comment]
I can confirm that this is something peculiar to my setup or some packages.  I moved my `.emacs.d` directory and trimmed my config down so that only Agda is being loaded and it seems to be fine.

I will have to do a binary search of my config/packages to figure out what's causing this, but it's likely not a bug here.

**Comment by karljs** [comment]
For anyone who might encounter this in the future, it seems to be caused by the rainbow-delimiters package.  The right double angle bracket is recognized as a mismatched closing delimiter, and so the inverted colors emphasize this.

I was eventually able to fix this by configuring Emacs' default syntax table to treat those characters as part of words rather than as matched delimiters.

**Comment by andreasabel** [comment]
Thanks for documenting your solution here!
