### ISSUE TITLE
what is the format of the libraries and defaults files

### ISSUE THREAD

**Issue by cartazio** [agda/agda#1884]
The new documentation doesn't seem to specify whether the defaults and libraries files have the same or different formats than the project level libraries files.

based on looking at the source code it looks like the libraries file is the absolute paths TO the root dir library files of a each respective library, at least if i'm reading the code in 
https://github.com/agda/agda/blob/df96c95caf5831e09f27b2c2554c2c0f1dac892a/src/full/Agda/Interaction/Library.hs#L94-L107 correctly 

```
getLibrariesFile :: Maybe FilePath -> IO FilePath
getLibrariesFile overrideLibFile = do
  agdaDir <- getAgdaAppDir
  return $ fromMaybe (agdaDir </> libraryFile) overrideLibFile

getInstalledLibraries :: Maybe FilePath -> LibM [AgdaLibFile]
getInstalledLibraries overrideLibFile = mkLibM [] $ do
    file <- getLibrariesFile overrideLibFile
    ifM (doesFileExist file) (do
      ls    <- stripCommentLines <$> readFile file
      files <- sequence [ (i, ) <$> expandEnvironmentVariables s | (i, s) <- ls ]
      parseLibFiles (Just file) files
      ) {- else -} (return ([], []))
  `catchIO` \e -> return ([], [OtherError $ "Failed to read installed libraries.\n" ++ show e])
```

**Comment by cartazio** [comment]
basic experimenting suggests 

defaults file lists library names

libraries file lists absolute (after env var expansion) paths to those libraries

**Comment by UlfNorell** [comment]
From the [documentation](http://agda.readthedocs.org/en/latest/tools/package-system.html):

> To be found by Agda a library file has to be listed (with its full path) in the file `AGDA_DIR/libraries`

and

> The `defaults` file should contain a list of library names, each on a separate line.

Do you have suggestions for making this more clear?

**Comment by cartazio** [comment]
Something like the following should in its own paragraph / subsection about
file format
Each line of the libraries file shall be the absolute file system path to
the root of a library
Each line of the defaults file shall be the name of a library resolvable
using the paths listed in the libraries file.

Possible with a two line example of each file.

I hope that helps!
It's an excitign and big improvement in agda userNess, so it'd be nice to
make sure that it doesn't get lost in the weeds

**Comment by cartazio** [comment]
I'm happy to pr such an edit if that would help.

A lot of the work and ideas in Agda (and ghc )are guiding the engineering
for a now open source language I'm doing as part of work.  So the least I
can do is try to upstream improvements in small ways :)

**Comment by UlfNorell** [comment]
If you're up for it a PR would be great.

**Comment by andreasabel** [comment]
After 19 months, the probability of arrival of a PR within Agda's lifetime was estimated to 10^-19.  
Thus, I fixed this myself.

**Comment by cartazio** [comment]
My bad 😅

Many thanks!
