### ISSUE TITLE
Problem with NO_POSITIVITY_CHECK and mutual definition (new style)

### ISSUE THREAD

**Issue by nad** [agda/agda#1885]
```
{-# NO_POSITIVITY_CHECK #-}

data D : Set

data D where
```

Result:

```
List of parameters does not match previous signature for D
```

The CHANGELOG explains that the pragma should be present both before the declaration and the definition of `D`. Why? Ease of implementation? I suggest that we drop this requirement, it should suffice to write the pragma once.

I've labelled this as a bug, because the current error message is not very helpful.

**Comment by asr** [comment]
> Ease of implementation?

Yes.

> I've labelled this as a bug, because the current error message is not very helpful.

I agree.

**Comment by asr** [comment]
Thanks for fixing this issue. I'll modify the previous test cases and update the CHANGELOG and the documentation.

**Comment by asr** [comment]
> I'll modify the previous test cases and update the CHANGELOG and the documentation.

Done. I'm closing the issue.
