### ISSUE TITLE
Second copies of telescopes not checked?

### ISSUE THREAD

**Issue by nad** [agda/agda#1886]
The following code is accepted:

```agda
data D (X : Set) : Set

data D (Y : Set Set) where
```

There are two problems here: The two telescopes don't match, and the code `Set Set` is not type-correct.

**Comment by UlfNorell** [comment]
I guess you don't mean `X /= Y`, but `Set /= Set Set`. The two options are
1. forbid typed parameters in data definitions
2. check that the two telescopes are equal

Option 2 would let you add the types as documentation closer to the constructors, but on the other hand we don't support that for function definitions, so I don't know.

**Comment by nad** [comment]
> I guess you don't mean X /= Y, but Set /= Set Set.

Both. The names of the parameters are significant (because we have named arguments), so they should be consistent.

I think that we should check that the telescopes match.

**Comment by UlfNorell** [comment]
The names would be taken from the type signature obviously. We don't require that names match in types and left-hand sides for functions. I suppose that would be more clear if we go for solution 1. Also I would like to allow (it isn't at the moment, I found out)

``` agda
data List {a} (A : Set a) : Set a

data List A where -- skip the {a} here
  []  : List A
  _∷_ : A → List A → List A
```

**Comment by nad** [comment]
> The names would be taken from the type signature obviously. We don't require that names match in types and left-hand sides for functions.

OK.

If we change the syntax so that the telescope is only given once (Option 1), then the parameters might be bound very far from their use sites.

**Comment by UlfNorell** [comment]
Not at all. You would still need to give the parameters in the definition, just not the types. See the List example above where you need to give the `A` since it's explicit.

**Comment by UlfNorell** [comment]
Your example would be (with a constructor)

``` agda
data D (X : Set) : Set

data D Y where
  d : Y → D Y
```

**Comment by andreasabel** [comment]
I think we wanted to allow the repetition of types in the second binding of parameters as option to document the types of parameters close to the constructors.  This should be legal:

``` agda
data D (X : Set) : Set

data D (Y : Set) where
  d : Y → D Y
```

But, of course, we should check that the types match (up to definitional equality).

**Comment by andreasabel** [comment]
> The names would be taken from the type signature obviously.
```agda
data List {b} (B : Set b) : Set b

data List A where -- skip the {b} here
  []  : List A
  _∷_ : A → List A → List A
```
It seems unnatural that the data type signature should dictate the name of the hidden arguments of the constructors, since it might be far away from the constructors.
Would it then give the names for those parameters that have been omitted by the data type definition?
```
  [] : {b : Level} {A : Set b} -> List A
```
I think we have less trouble if we require names and types to match, but we could allow hidden arguments to be omitted in the data type definitions.

See also #555.

**Comment by andreasabel** [comment]
I implemented my proposal (given in the previous comment).

**Comment by UlfNorell** [comment]
With generalizable parameters, I think we should treat parameters in definitions more like left-hand sides. That is,
- disallow repeating the type
- allow named implicits
- allow giving different names in signature and definition
