### ISSUE TITLE
The customised/* failing tests are not included in the Haskell test runner

### ISSUE THREAD

**Issue by asr** [agda/agda#1888]
After changing `foo` by `bar` in test/Fail/customised/FFI.err, by running `make fail` I would expect an error message and  the message

```
Golden value differs from actual value.
Accept actual value as new golden value? [yn] 
```

However, the current behaviour is

```
$ make fail
...
customised/NestedProjectRoots.agda
customised/FFI.agda
customised/FFI.err.tmp.2 customised/FFI.err.tmp.3 differ: byte 66, line 1
== Old error ===
Compilation error:

customised/MAlonzo/Code/FFI.hs
    Not in scope: 'bar'

customised/MAlonzo/Code/FFI.hs
    Not in scope: 'bar'

== New error ===
Compilation error:

customised/MAlonzo/Code/FFI.hs
    Not in scope: 'foo'

customised/MAlonzo/Code/FFI.hs
    Not in scope: 'foo'
```

that is, `agda-tests` didn't ask for accepting the new the golden value.

**Comment by phile314** [comment]
A few of the Fail tests are still defined using a Makefile, see https://github.com/agda/agda/blob/master/test/Fail/Makefile . To get consistent behaviour, this tests need to be ported to the Haskell test runner.

**Comment by asr** [comment]
You are right, of course.

**Comment by phile314** [comment]
Fixed by https://github.com/agda/agda/commit/bedd36e7189825c4a058a90353c8f78502df88bc .
