### ISSUE TITLE
quoting and unquoting do not agree on module parameters

### ISSUE THREAD

**Issue by m0davis** [agda/agda#1890]
This is similar to issue #1833. The code below shows that one needs to know the current module context when defining a function that refers to the record `R`. When within the anonymous module, it needs to have no arguments, but outside, it needs the module's argument. I believe that the intended design is to define all functions in an empty context. I.e. `mac₁` should succeed in both cases.

```
  open import Prelude
  open import Tactic.Reflection

  module _ (A : Set) where
    record R : Set where

    `R₀ : Type
    `R₀ = def₀ (quote R)

    `R₁ : Term → Type
    `R₁ = def₁ (quote R)

    `Nat : Type
    `Nat = def₀ (quote Nat)

    helper-type₀ : Type
    helper-type₀ = `R₀ `→ `R₀

    helper-type₁ : Type
    helper-type₁ = `R₁ `Nat `→ `R₁ `Nat

    helper-term : Term
    helper-term = var₀ 0

    helper-patterns : List (Arg Pattern)
    helper-patterns = vArg (var "_") ∷
                      []

    macro
      mac₀ : Tactic
      mac₀ hole =
        n ← freshName "n" -|
        define (vArg n) helper-type₀ (clause helper-patterns helper-term ∷ []) ~|
        typeError [ strErr "definition succeeded" ]

      mac₁ : Tactic
      mac₁ hole =
        n ← freshName "n" -|
        define (vArg n) helper-type₁ (clause helper-patterns helper-term ∷ []) ~|
        typeError [ strErr "definition succeeded" ]

    within-module-succeeds₀ : Set
    within-module-succeeds₀ = {!mac₀!}

    within-module-fails₁ : Set
    within-module-fails₁ = {!mac₁!}

  outside-module-fails₀ : Set
  outside-module-fails₀ = {!mac₀ Nat!}

  outside-module-succeeds₁ : Set
  outside-module-succeeds₁ = {!mac₁ Nat!}
```

**Comment by m0davis** [comment]
Related to #1363?

**Comment by m0davis** [comment]
To make the point a bit more clear, here's another example of the same problem. `trust-the-doppelganger` tries to define a function with a type copied from the current context and goal, using `trustMe` as a proof. In the case where the current context is partly from a parameterised module, the definition fails because `define` (wrongly) expects us to refer to types within the current module without specifying the parameters, even though `getContext` (rightly) gives us those types with parameters fully specified.

```
open import Prelude
open import Tactic.Reflection

postulate
  trustMe : ∀ {α} {A : Set α} → A

macro
  trust-the-doppelganger : Tactic
  trust-the-doppelganger hole = do
    telescope ← reverse <$> getContext -|
    goal ← inferType hole -|
    nameₕ ← freshName "nameₕ" -|
    catchTC
      (define (vArg nameₕ) (telPi telescope goal) [ clause (telePat telescope) (def₀ (quote trustMe)) ])
      (typeError (strErr "failed defining a function with type" ∷ termErr (telPi telescope goal) ∷ []))
      ~|
    unify hole (def nameₕ (teleArgs telescope))

module M₀ where
  postulate
    P : Set

  no-param-succeeds : P
  no-param-succeeds = trust-the-doppelganger

module M₁ (A : Set) where
  postulate
    P : Set

  inside-M₁-fails : P
  inside-M₁-fails = trust-the-doppelganger -- failed defining a function with type (A₁ : Set) → P A₁

outside-M₁-succeeds : (A : Set) → M₁.P A
outside-M₁-succeeds = trust-the-doppelganger
```

**Comment by m0davis** [comment]
@UlfNorell I suspect this issue may have fallen between the cracks. Care to comment?

**Comment by UlfNorell** [comment]
I'm sorry, I'm a bit busy at the moment. How does this relate to #1363?

**Comment by m0davis** [comment]
Actually, it doesn't! I had (earlier) suspected that it did due to a similarity in problems related module parameters, but as [my latest example](https://github.com/agda/agda/issues/1890#issuecomment-196102513) shows, this issue is actually quite different from #1363. Importantly, this one is also tougher for me to work around than #1363.

**Comment by UlfNorell** [comment]
I can't reproduce the original issue. I get `mac₀` failing and `mac₁` succeeding (as expected) both inside and outside the module. There is a problem though, and it doesn't seem to have anything to do with `defineFun`: When quoting a term it includes the module parameters, but when unquoting it expects them to not be there. Simplified doppelganger example:

``` agda
postulate
  pick : (A : Set) → A

macro
  cheat : Tactic
  cheat hole =
    do goal ← inferType hole
    -| unify hole (def₁ (quote pick) goal)

module M (A : Set) where
  postulate P : Set

  fail : P
  fail = cheat  -- quoted goal type: P A
```

**Comment by UlfNorell** [comment]
Or even simpler

``` agda
macro
  round-trip : Term → Tactic
  round-trip v hole = unify v hole

module M (A : Set) where
  data D : Set where

  fail : Set
  fail = round-trip D
```

**Comment by UlfNorell** [comment]
Oh never mind, I can reproduce the original problem. I was looking at a modified version of the code... I think the problem is the same though.

**Comment by UlfNorell** [comment]
Upon further review I believe the original example is working as intended. Inside the anonymous module you really are supposed to refer to `R` without the argument, as you do in normal code. Putting the macro and its use in different modules makes `mac₀` fail and `mac₁` pass as expected.
