### ISSUE TITLE
agda2-refine is broken

### ISSUE THREAD

**Issue by m0davis** [agda/agda#1892]
```
data D : Set where
  d : D

foo : D
foo = {!!} -- C-c C-r gives me a weird-looking '0'
```

my ~/.emacs

```
(load-file (let ((coding-system-for-read 'utf-8))
                (shell-command-to-string "agda-mode locate")))
```

GNU Emacs 24.5.1
Linux, 4.3.3-gnu-1

I'm using the latest of agda/master and have run `agda-mode compile`.

**Comment by UlfNorell** [comment]
Most likely introduced by e9d338d, but I can't quite see how at the moment.

**Comment by andreasabel** [comment]
This bit me during my Agda tutorial at FLOPS, so I had to downgrade to 2.4.2.6 during the tutorial.
