### ISSUE TITLE
agda-ghc-names does not pick up du* identifiers

### ISSUE THREAD

**Issue by WolframKahl** [agda/agda#1893]
After a long hiatus, I tried profiling again, and discovered that, in the code generated by the GHC backend, there are now `du*` identifiers  which apparently typically are functions being passed only the relevant arguments by the corresponding `d*` identifiers.

@UlfNorell, is this correct? (Are they new?)

Do I need to know anything else to do the right thing in agda-ghc-names?

**Comment by WolframKahl** [comment]
Under the assumptions stated in the OP, this should be fixed by 8333bde4a4e8d0c9edeed692d52a8cda0107e56d.

**Comment by UlfNorell** [comment]
That's correct. They were introduced in 6c965ef.
