### ISSUE TITLE
Agda stderr should be reported in Emacs

### ISSUE THREAD

**Issue by WolframKahl** [agda/agda#1898]
There are two cases where I sorely miss Agda's `stderr` output when using the Emacs interface:
- When Agda crashes, I don't know whether it was a spurious segmentation fault (which I tend to get not too rarely, but not reproducibly), or because it ran out of heap.
- When Agda is unresponsive, I do not know whether it is actually doing work, or only garbage collecting. Since I included `-S` in the RTS arguments in the Agda program arguments, the information to discern this is there on `stderr`, but does not show up in any Emacs buffer I can find.

When I run Agda from the commandline, with `+RTS -S ... -RTS`, all this information is there, but for modules with holes, the command-line does not help with the holes...

I don't have particular demands where that information is made accessible; I only want it accessible somewhere. Ideally it would be in the `*Agda information*` buffer during typechecking, **and** in the `*agda2*` buffer for ex-post analysis, but just having it scrolling through a status line would probably also be acceptable.

(I know this is closely related to the original issue in #637, but at the time there still was a `*ghci*` buffer.)

**Comment by nad** [comment]
Is there some part of the stderr output that is not echoed to the *agda2* buffer?

The documentation of `agda2-output-filter` claims that 'All commands are echoed to the *agda2* buffer, with the exception of commands of the form "(agda2-highlight-... ...)"'. However, the documentation also states the following: 'This filter function assumes that every line contains either some kind of error message (which cannot be parsed as a list), or exactly one command. Incomplete lines are stored in a buffer (agda2-output-chunk-incomplete).'

**Comment by WolframKahl** [comment]
Agda sends “Skipping ...” to stdout, not to stderr ─ I am actually not aware of anything sent to stderr by Agda itself: Even error messages go to stdout.

The output of +RTS -S -RTS goes to stderr, and is not visible anywhere in Emacs.

After a crash of the agda process, the error message for that crash is not visible anywhere in Emacs, while in a terminal I see, so far, either a segmantation fault message or an out-of-heap message, and it is useful to know which kind of crash it was.

**Comment by nad** [comment]
I realised now that, even though many _commands_ are echoed to the *agda2* buffer, this only applies to commands. I changed the code so that complete lines that are not recognised as commands are echoed (if the filter function is invoked).

**Comment by nad** [comment]
> Since I included -S in the RTS arguments in the Agda program arguments, the information to discern this is there on stderr, but does not show up in any Emacs buffer I can find.

Note that if you mess with Agda's output, then strange things may happen. The Emacs command `start-process` merges stdout and stderr, so some commands from the backend may be garbled. (I have observed this with `-S`.)

**Comment by nad** [comment]
If you really want to use `-S`, then I suggest that you direct the output to a file (`-S<file>`).

**Comment by WolframKahl** [comment]
I had not been aware of the possibility to pass a file to `-S` ─ thank you!

(Now I need to keep two terminal windows in view while working with Agda interactively: One for htop, to see whether Agda is still busy, and one with `tail -f AgdaRTS.log` to see how busy Agda really is while htop shows it busy...)
