### ISSUE TITLE
include spelling / scoping based suggestions when reporting a variable out of scope

### ISSUE THREAD

**Issue by cartazio** [agda/agda#1903]
ran into this in my build of agda master, and its likely true of older agdas pre 2.5 rc too :) 

it took me about 10 minutes to realize whats going on because i was bit tired and hit this yesterday evening (because the type error didn't do a "maybe you meant"), a mini example would be such as the following 

```
module Example where 
import Data.Nat 
open import Data.CoNat


data MonoList : Set where
  MonoNil : MonoList
  MonoCons : ℕ  -> MonoList -> MonoList
```

the error I get is 

```
Not in scope:
  ℕ
  at /Users/carter/local-dev/hopper/models/agda/HBound.agda:14,14-15
when scope checking ℕ
```

and in the error handling code one could imagine instead collecting a set of "possible matches" that have a similar but differently spelled name or same name but in the `Data.Nat` name space

in which case you could imagine the error being something like 

```
Not in scope:
  ℕ
  at /Users/carter/local-dev/hopper/models/agda/HBound.agda:14,14-15
when scope checking ℕ
  perhaps you meant one of:
     Data.Nat.ℕ from import Data.Nat
     coℕ  from open import Data.CoNat 
```

or something along those lines.
I imagine this wouldn't require any deep surgery (hopefully), but its one of those localized improvements that can have a HUGE impact on users of all level! (at least the analogous error reporting in ghc is incredibly helpful)

**Comment by andreasabel** [comment]
+1.  At least looking for all qualified names that match the unqualified name would be something easy and systematic to do.

**Comment by UlfNorell** [comment]
Lists things where the `editDistance` is less or equal to a third of the length (after stripping underscores and ignoring case).

**Comment by cartazio** [comment]
just built master to try it out! Its pretty nice, many thanks
