### ISSUE TITLE
Possible performance problem

### ISSUE THREAD

**Issue by goerch** [agda/agda#1906]
Running the attached file with the definition

```
∨-cong {x₁} {x₂} {y₁} {y₂} (mk x₁→x₂ , mk x₂→x₁) (mk y₁→y₂ , mk y₂→y₁) = mk lemma₁ , mk lemma₂ where
  lemma₁ : x₁ ∨ y₁ →  x₂ ∨ y₂
  lemma₁ (∨-inl x₁) = ∨-inl (x₁→x₂ x₁)
  lemma₁ (∨-inr y₁) = ∨-inr (y₁→y₂ y₁)
  lemma₂ : x₂ ∨ y₂ →  x₁ ∨ y₁
  lemma₂ (∨-inl x₂) = ∨-inl (x₂→x₁ x₂)
  lemma₂ (∨-inr y₂) = ∨-inr (y₂→y₁ y₂)
```

results in 

Total                        34,211ms
Miscellaneous                    15ms
Parsing.Operators               156ms
Deserialization                   0ms
Scoping                          46ms
Scoping.InverseScopeLookup   18,657ms
Typing                        3,088ms
Typing.OccursCheck              468ms
Typing.CheckLHS               5,662ms
Typing.CheckLHS.UnifyIndices    436ms
Termination                       0ms
Termination.RecCheck            265ms
Positivity                    1,326ms
Injectivity                       0ms
ProjectionLikeness               31ms
Coverage                        327ms
Highlighting                     15ms
Serialization                 1,528ms
Serialization.Sort               15ms
Serialization.BinaryEncode      187ms
Serialization.Compress            0ms
DeadCode                      1,981ms

Changing the definition to

```
∨-cong {x₁} {x₂} {y₁} {y₂} (x₁⇒x₂ , x₂⇒x₁) (y₁⇒y₂ , y₂⇒y₁) = mk lemma₁ , mk lemma₂ where
  lemma₁ : x₁ ∨ y₁ →  x₂ ∨ y₂
  lemma₁ (∨-inl x₁) = ∨-inl (⇒-fst x₁⇒x₂ x₁)
  lemma₁ (∨-inr y₁) = ∨-inr (⇒-fst y₁⇒y₂ y₁)
  lemma₂ : x₂ ∨ y₂ →  x₁ ∨ y₁
  lemma₂ (∨-inl x₂) = ∨-inl (⇒-fst x₂⇒x₁ x₂)
  lemma₂ (∨-inr y₂) = ∨-inr (⇒-fst y₂⇒y₁ y₂)
```

changes the profile to

Total                        149,963ms
Miscellaneous                     15ms
Parsing.Operators                140ms
Deserialization                    0ms
Scoping                           62ms
Scoping.InverseScopeLookup    18,922ms
Typing                        22,058ms
Typing.OccursCheck            17,799ms
Typing.CheckLHS               30,778ms
Typing.CheckLHS.UnifyIndices   2,386ms
Termination                        0ms
Termination.RecCheck           4,071ms
Positivity                    19,172ms
Injectivity                        0ms
ProjectionLikeness                31ms
Coverage                       2,215ms
Highlighting                      15ms
Serialization                  3,010ms
Serialization.Sort                15ms
Serialization.BinaryEncode       218ms
Serialization.Compress             0ms
DeadCode                      29,047ms

When using

```
∨-cong {x₁} {x₂} {y₁} {y₂} x₁≈x₂ y₁≈y₂ = mk lemma₁ , mk lemma₂ where
  lemma₁ : x₁ ∨ y₁ →  x₂ ∨ y₂
  lemma₁ (∨-inl x₁) = ∨-inl (⇒-fst (⇔-fst x₁≈x₂) x₁)
  lemma₁ (∨-inr y₁) = ∨-inr (⇒-fst (⇔-fst y₁≈y₂) y₁)
  lemma₂ : x₂ ∨ y₂ →  x₁ ∨ y₁
  lemma₂ (∨-inl x₂) = ∨-inl (⇒-fst (⇔-snd x₁≈x₂) x₂)
  lemma₂ (∨-inr y₂) = ∨-inr (⇒-fst (⇔-snd y₁≈y₂) y₂)
```

instead the profile changes to

Total                        1,143,471ms
Miscellaneous                        0ms
Parsing.Operators                  140ms
Deserialization                      0ms
Scoping                             78ms
Scoping.InverseScopeLookup      18,907ms
Typing                         261,395ms
Typing.OccursCheck               7,534ms
Typing.CheckLHS                313,421ms
Typing.CheckLHS.UnifyIndices        31ms
Termination                          0ms
Termination.RecCheck            66,175ms
Positivity                     212,551ms
Injectivity                         15ms
ProjectionLikeness                   0ms
Coverage                            15ms
Highlighting                         0ms
Serialization                    1,482ms
Serialization.Sort                 124ms
Serialization.BinaryEncode         124ms
Serialization.Compress               0ms
DeadCode                       261,473ms

Checked with todays master. Is this expected behaviour?

[heyting.agda.txt](https://github.com/agda/agda/files/175645/heyting.agda.txt)

**Comment by nad** [comment]
> Is this expected behaviour?

Here's a cut-down and modified version of your code:

```agda
open import Agda.Primitive

record Relation {a b} (A : Set a) (B : Set b) c : Set (a ⊔ b ⊔ lsuc c) where
  constructor mk
  field
    _∼_ : A → B → Set c

record Setoid a c : Set (lsuc (a ⊔ c)) where
  constructor mk
  field
    carrier  : Set a
    relation : Relation carrier carrier c

  open Relation relation public renaming (_∼_ to _≈_)

record HeytingAlgebra {a c}
         (setoid : Setoid a c)
         (_∧_ _∨_ : let open Setoid setoid in
                    carrier → carrier → carrier) :
         Set (a ⊔ c) where
  constructor laws
  open Setoid setoid

  field
    ∧-cong : ∀ {x₁ x₂ y₁ y₂} → x₁ ≈ x₂ → y₁ ≈ y₂ → (x₁ ∧ y₁) ≈ (x₂ ∧ y₂)
    ∨-cong : ∀ {x₁ x₂ y₁ y₂} → x₁ ≈ x₂ → y₁ ≈ y₂ → (x₁ ∨ y₁) ≈ (x₂ ∨ y₂)

infix 0 _⇒_

record _⇒_ {a b} (A : Set a) (B : Set b) : Set (a ⊔ b) where
  constructor mk
  field
    ⇒-fst : A → B

open _⇒_ public

infix 0 _⇔_
infixr 0 _,_

record _⇔_ {a b} (A : Set a) (B : Set b) : Set (a ⊔ b) where
  constructor _,_
  field
    ⇔-fst : A ⇒ B
    ⇔-snd : B ⇒ A

open _⇔_ public

⇔-relation : ∀ {a b} → Relation (Set a) (Set b) (a ⊔ b)
⇔-relation = mk _⇔_

⇔-setoid : ∀ c → Setoid (lsuc c) c
⇔-setoid c = mk (Set c) ⇔-relation

infix 0 _∧_

record _∧_ {a b} (A : Set a) (B : Set b) : Set (a ⊔ b) where
  constructor _,_
  field
    ∧-fst : A
    ∧-snd : B

open _∧_ public

infix 0 _∨_

data _∨_ {a b} (A : Set a) (B : Set b) : Set (a ⊔ b) where
  ∨-inl : A → (A ∨ B)
  ∨-inr : B → (A ∨ B)

heyting-algebra : ∀ {a} → HeytingAlgebra (⇔-setoid a) _∧_ (_∨_ {a})
heyting-algebra {a} = laws ∧-cong ∨-cong
  where
  open Setoid (⇔-setoid _)

  ∧-cong : ∀ {x₁ x₂ y₁ y₂} → x₁ ≈ x₂ → y₁ ≈ y₂ → (x₁ ∧ y₁) ≈ (x₂ ∧ y₂)
  ∧-cong x₁≈x₂ y₁≈y₂ =
    mk (λ x₁∧y₁ → ⇒-fst (⇔-fst x₁≈x₂) (∧-fst x₁∧y₁) , ⇒-fst (⇔-fst y₁≈y₂) (∧-snd x₁∧y₁)) ,
    mk (λ x₂∧y₂ → ⇒-fst (⇔-snd x₁≈x₂) (∧-fst x₂∧y₂) , ⇒-fst (⇔-snd y₁≈y₂) (∧-snd x₂∧y₂))

  ∨-cong : ∀ {x₁ x₂ y₁ y₂} → x₁ ≈ x₂ → y₁ ≈ y₂ → (x₁ ∨ y₁) ≈ (x₂ ∨ y₂)

  ∨-cong {x₁} {x₂} {y₁} {y₂} x₁≈x₂ y₁≈y₂ =
    mk lemma₁ , mk lemma₂
    where
    lemma₁ : x₁ ∨ y₁ →  x₂ ∨ y₂
    lemma₁ (∨-inl x₁) = ∨-inl (⇒-fst (⇔-fst x₁≈x₂) x₁)
    lemma₁ (∨-inr y₁) = ∨-inr (⇒-fst (⇔-fst y₁≈y₂) y₁)
    lemma₂ : x₂ ∨ y₂ →  x₁ ∨ y₁
    lemma₂ (∨-inl x₂) = ∨-inl (⇒-fst (⇔-snd x₁≈x₂) x₂)
    lemma₂ (∨-inr y₂) = ∨-inr (⇒-fst (⇔-snd y₁≈y₂) y₂)

  -- ∨-cong {x₁} {x₂} {y₁} {y₂} (x₁⇒x₂ , x₂⇒x₁) (y₁⇒y₂ , y₂⇒y₁) =
  --   mk lemma₁ , mk lemma₂
  --   where
  --   lemma₁ : x₁ ∨ y₁ →  x₂ ∨ y₂
  --   lemma₁ (∨-inl x₁) = ∨-inl (⇒-fst x₁⇒x₂ x₁)
  --   lemma₁ (∨-inr y₁) = ∨-inr (⇒-fst y₁⇒y₂ y₁)
  --   lemma₂ : x₂ ∨ y₂ →  x₁ ∨ y₁
  --   lemma₂ (∨-inl x₂) = ∨-inl (⇒-fst x₂⇒x₁ x₂)
  --   lemma₂ (∨-inr y₂) = ∨-inr (⇒-fst y₂⇒y₁ y₂)

  -- ∨-cong {x₁} {x₂} {y₁} {y₂} (mk x₁→x₂ , mk x₂→x₁) (mk y₁→y₂ , mk y₂→y₁) =
  --   mk lemma₁ , mk lemma₂
  --   where
  --   lemma₁ : x₁ ∨ y₁ →  x₂ ∨ y₂
  --   lemma₁ (∨-inl x₁) = ∨-inl (x₁→x₂ x₁)
  --   lemma₁ (∨-inr y₁) = ∨-inr (y₁→y₂ y₁)
  --   lemma₂ : x₂ ∨ y₂ →  x₁ ∨ y₁
  --   lemma₂ (∨-inl x₂) = ∨-inl (x₂→x₁ x₂)
  --   lemma₂ (∨-inr y₂) = ∨-inr (y₂→y₁ y₂)
```

If the line `open Setoid (⇔-setoid _)` is replaced by `open Setoid (⇔-setoid a)`, then the code type-checks quickly, with all three versions of `∨-cong`.

I'm not sure if this should be classified as a bug or not.

**Comment by goerch** [comment]
Cool!

Is there a way for me to see when it is useful to specify such (implicit) arguments?

**Comment by nad** [comment]
> Is there a way for me to see when it is useful to specify such (implicit) arguments?

In this case it is a bit tricky. The meta-variable is solved, but rather late, and I suspect it is this that leads to the poor performance.

In this case the `open` statement would be highlighted (typically in yellow) if you omitted, say, the right-hand side of `heyting-algebra`, the entire definition of `∨-cong`, and the right-hand side of `∧-cong`. If you included the right-hand side of `∧-cong`, then a subexpression in this right-hand side would be highlighted instead.

@vlopezj, does [`tog`](https://github.com/bitonic/tog) handle this example in a better way? I'm thinking that more careful tracking of meta-variable dependencies could be beneficial.

**Comment by vlopezj** [comment]
@nad and I have been looking at this during the past week. 

 Here's an example that shares some performance characteristics with your example: [Issue_1906_branch.agda](https://gist.github.com/vlopezj/d3f51e5ba1941b527b801904eb271c9f). 
The role of  `⊔` is taken by `xor`.

```
Finished Issue1906_branch.
Total                        11,485ms
Parsing                           6ms
Parsing.Operators                 5ms
Import                            0ms
Deserialization                   0ms
Scoping                           6ms
Typing                          360ms
Typing.OccursCheck            1,313ms
Typing.CheckLHS                 417ms
Typing.CheckLHS.UnifyIndices      0ms
Termination                       0ms
Termination.RecCheck          1,265ms
Positivity                    6,654ms
Injectivity                       0ms
ProjectionLikeness                0ms
Coverage                          1ms
Highlighting                      2ms
Serialization                    34ms
Serialization.Sort                0ms
Serialization.BinaryEncode        3ms
Serialization.Compress            0ms
DeadCode                      1,405ms
ModuleName                        2ms
```

![graph](https://cloud.githubusercontent.com/assets/1593773/14181934/7123ec68-f769-11e5-8873-1315052d7a73.png)

For both this and @goerch's example, more detailed profiling points to `instantiateFull'` as a big cost center. It seems that, as each metavariable `_i` is recursively instantiated to `xor _(i-1) _(i-2)`, the sizes of the terms involved grow exponentially. I think this will be hard to fix without a term representation that preserves sharing.

**Comment by andreasabel** [comment]
Maybe we should never instantiateFull, but keep the meta-variables and their instantiations in the internal syntax. (Or only instantiate linearly used meta-variables.)  Meta-variables **are** a way of sharing terms.

**Comment by UlfNorell** [comment]
The example in the OP now checks (on my machine) in 2.5s/6.0s/8.1s and @nad's cut down example in 0.4s/1.1s/3.0s. @vlopezj's example seems to be different after all: this checks in a similar time as before (7.2s).

I filed a new issue (#3094) for the `instantiateFull` discussion and closed this since the problem in the OP seems fixed.
