### ISSUE TITLE
Git and GitHub first commits are different

### ISSUE THREAD

**Issue by asr** [agda/agda#1910]
Does anyone understand why the Git first commit

```
$ git log | tail -n 5
commit fe850770ea4b4d04a466e768de6a0b5a0cf969be
Author: ulfn <ulfn@cs.chalmers.se>
Date:   Fri Sep 9 09:26:49 2005 +0000

    meeting notes
```

is different to the GitHub [first](https://github.com/agda/agda/commits/master?page=100) commit?

**Comment by JasonGross** [comment]
For whatever reason, GitHub decided to disable the "Older" button on that
page.  If you manually edit the URL to go to page 101, then you can keep
clicking older, and you get to the first commit on page 309
https://github.com/agda/agda/commits/master?page=309, which matches the
first git commit.  Maybe GitHub has a bug?

**Comment by JasonGross** [comment]
This seems to be a GitHub bug, inasmuch as it's also disabled on page 100
(but not 101 nor 200 nor 10 nor 1000) for coq/coq and torvalds/linux
and mozilla/firefox-ios, to take a small sample.  I've contacted them about
it.

**Comment by asr** [comment]
Thanks!

**Comment by asr** [comment]
AFAIK, GitHub has no a bug tracker. For reporting issues I contact them and I file an issue in https://github.com/isaacs/github.
