### ISSUE TITLE
Names that are not in scope can sometimes be candidates for instance resolution

### ISSUE THREAD

**Issue by nad** [agda/agda#1913]
The following code type-checks:

```agda
module _ where

module M where

  data D : Set where
    d : D

  private
    instance
      x : D
      x = d

! : ⦃ _ : M.D ⦄ → M.D
! ⦃ x ⦄ = x

y : M.D
y = !
```

Let's move `M` to a separate file:

```agda
module M where

  data D : Set where
    d : D

  private
    instance
      x : D
      x = d
```

The following code is rejected:

```agda
module _ where

import M

! : ⦃ _ : M.D ⦄ → M.D
! ⦃ x ⦄ = x

y : M.D
y = !
```

Error message:

```
No instance of type M.D was found in scope.
when checking that the expression ! has type M.D
```

Is this the intended behaviour? It seems reasonable to me to reject the second example, because `x` is not in scope. However, `x` is not in scope in the first example either.

The [instance argument documention](http://agda.readthedocs.org/en/latest/language/instance-arguments.html) currently includes the following passage:

> In the second stage we compute a set of candidates. Let-bound variables and top-level definitions are candidates if they are defined in an instance block. [...]

If we assume that the first example above should be rejected, then the text can be reformulated in the following way:

> In the second stage we compute a set of candidates. This set is a subset of the names that are in scope. Let-bound variables and top-level definitions are candidates iff they are defined in an instance block. [...]

I've labelled this as a bug, because I think that we should either change the implementation or the documentation (or both).

**Comment by UlfNorell** [comment]
See some discussion in #1265. Your suggested reformulation of the documentation is not good since it suggests that lambda bound instances also need to be in scope, which absolutely must not be required.

**Comment by nad** [comment]
@UlfNorell, you wrote "only consider top-level instances if they are in scope". Here is a variant of `test/Fail/Issue1913.agda` in which an instance that is not in scope is used:

```agda
module M where

data D : Set where
  d : D
```

```agda
module I where

open import M

instance
  x : D
  x = d
```

```agda
module _ where

import M

module _ where

  import I

  accepted₁ : M.D
  accepted₁ = I.x

! : ⦃ _ : M.D ⦄ → M.D
! ⦃ x ⦄ = x

accepted₂ : M.D
accepted₂ = !

rejected : M.D
rejected = I.x
```

**Comment by jespercockx** [comment]
Maybe all things brought into scope by `import I` (without `public`) should be automatically considered `private`? That way they wouldn't be considered by instance search outside of the module containing the import statement.

**Comment by nad** [comment]
> Maybe all things brought into scope by `import I` (without `public`) should be automatically considered `private`?

What do you mean by `private`? The names introduced by `import I` are never (or at least should not be) exported.

**Comment by jespercockx** [comment]
Exactly, I just mean we should mark them as if they were defined as `private` by the user, because this will prevent them from being considered as candidates by the instance resolution.
