### ISSUE TITLE
Agda claims that consistent constraints are inconsistent

### ISSUE THREAD

**Issue by nad** [agda/agda#1914]
The following code is rejected by Agda:

``` agda
open import Agda.Builtin.Size using (Size; Size<_)

postulate
  A : Set

record R (i : Size) (x : A) : Set where
  coinductive
  field
    force : (j : Size< i) → R j x

postulate
  P : (A → Set) → Set
  f : (Q : A → Set) (x : A) ⦃ c : P Q ⦄ → Q x → Q x
  g : (i : Size) (x : A) → R i x → R i x

  instance
    c : {i : Size} → P (R i)

accepted rejected : A → (x : A) (i : Size) → R i x → R i x

accepted y x i r = g _ _ (f _ _ r)

rejected y x i r = g _ _ (f _ x r)
```

Error message:

```
Cannot solve size constraints
i ≤ _36 y x i r
_i_42 x i ≤ i
_36 y x i r ≤ _i_42 x i
Reason: Inconsistent constraints
when checking the definition of rejected
```

As far as I can tell these constraints are not inconsistent. Is the error message incorrect? Should the code be accepted?

**Comment by andreasabel** [comment]
Because of this false claim of inconsistency, WW1 broke out.

**Comment by andreasabel** [comment]
The size constraint solver apparently messes up in the presence of pruned metas such as _i_42 (which are not applied to all variables in the context).  This happens probably when converting terms with metas into size expressions with size metas.  I need to investigate this!

**Comment by andreasabel** [comment]
Beyond WW1, I also caused WW2 (#1939).  Fate of a German... :D
