### ISSUE TITLE
Lack of documentation of breaking change

### ISSUE THREAD

**Issue by nad** [agda/agda#1916]
Consider the following code, which is accepted by Agda 2.4.2.5:

```
postulate
  A B : Set
  a   : A

record R (X Y : Set) : Set where
  field
    r : X → Y

open R ⦃ ... ⦄

instance
  postulate
    aa : R A A
    bb : R B B

x : A
x = r (r a)
```

The current development version of Agda rejects this code, because instance resolution gives too many candidates:

```
Resolve instance argument _r_8 : R _X_6 A.
  Candidates:
    [ bb : R B B
    , aa : R A A ]
Resolve instance argument _r_11 : R A _X_6.
  Candidates:
    [ bb : R B B
    , aa : R A A ]
```

I find it annoying that `bb` can be a candidate, because the types don't match. I guess this is related to the following comment due to @guillaumebrunerie (c84e4a3a2d861db7260e0fb05dc7c18d3cbd36b0) that I found in `Agda.TypeChecking.InstanceArguments`:

> If one of the arguments of the typeclass is a meta which is not rigidly constrained, then don’t do anything because it may loop.

I'm not sure if Agda's rejection of the code above is appropriate, but this breaking change should at least be documented (and perhaps also explained) in the manual and in the changelog.

**Comment by nad** [comment]
> The current development version of Agda rejects this code, because instance resolution gives too many candidates:

In fact, if `bb` is removed, then Agda still refuses to attempt to use `aa`:

```
Resolve instance argument _r_7 : R _X_5 A.
  Candidates:
    [ aa : R A A ]
Resolve instance argument _r_10 : R A _X_5.
  Candidates:
    [ aa : R A A ]
```

The documentation states, incorrectly, that "If there is a single solution we use it to solve the goal".

**Comment by nad** [comment]
What could go wrong if `_X_5` were unified with `A`? I found some discussion in [[Agda] Recursive instance search](https://lists.chalmers.se/pipermail/agda/2014/006859.html) (sent by @guillaumebrunerie on 2014-07-11). This message includes the following comment:

> As a special case, if none of the instances declared for that type is recursive, then instance search is attempted as usual even if there are unsolved metas (no risk of looping here).

There are no recursive instances in the code above, so I guess the comment above no longer applies.

**Comment by nad** [comment]
The special case was removed in b428d1db4464c3b42d265554112ea65f3c183fb5, without any explanation. I tried to re-enable the special case. Outcome:
- The code above is accepted, with or without `bb`.
- `Issue723.agda` and `NonRigidlyConstrained.agda` in `test/Fail` are accepted, all other test cases pass.
- The time required to check the code above with `bb` present and the body of `x` replaced by `r (r (r (...(r a)...)))` seems to be at least exponential in the number of occurrences of `r`. I don't know exactly what's going on, but I can see that `checkCandidates` calls itself recursively via `solveConstraint`.

**Comment by UlfNorell** [comment]
There are two reasons for the non-rigidly constrained check:
- non-termination and/or exponential behaviour for recursive instance search
- strange unintended solutions

An example of the second case is instantiating an unconstrained regular meta to `Nat` (say) just because the only visible instance of some class is for `Nat`.

**Comment by UlfNorell** [comment]
The documentation is fine. It has a whole paragraph about this under [Instance resolution](http://agda.readthedocs.org/en/latest/language/instance-arguments.html#instance-resolution) (Verify the goal). Obviously the /single solution/ quote only applies if it is in fact a valid solution.

**Comment by UlfNorell** [comment]
An instance of the problem (if not the original one) is in #1532.
