### ISSUE TITLE
Type displayed in context is incorrect

### ISSUE THREAD

**Issue by halfaya** [agda/agda#1919]
Using Agda  2.5.0.20160213 and agda-stdlib that goes with it (I'm not sure of the version, but just after 0.11 according to the CHANGELOG).  Consider the following example (sorry I don't know of a simpler one):

``` agda
module Bug where

open import Data.List using (List; _∷_; [])
open import Data.Product using (Σ; ∃; _,_; Σ-syntax)
open import Relation.Binary.PropositionalEquality using (_≡_; refl; sym; trans; cong)

data ⊥ : Set where

data _∨_ (P Q : Set) : Set where
 ∨-intro₁ : P → P ∨ Q
 ∨-intro₂ : Q → P ∨ Q

∨-elim : {P Q R : Set} → (P → R) → (Q → R) → P ∨ Q → R
∨-elim f g (∨-intro₁ p) = f p
∨-elim f g (∨-intro₂ q) = g q

data _∧_ (P Q : Set) : Set where
 ∧-intro : P → Q → P ∧ Q

∧-elim₁ : {P Q : Set} → P ∧ Q → P
∧-elim₁ (∧-intro p q) = p

∧-elim₂ : {P Q : Set} → P ∧ Q → Q
∧-elim₂ (∧-intro p q) = q

map : {A B : Set} → (f : A → B) → List A → List B
map f []       = []
map f (x ∷ xs) = f x ∷ map f xs

_∈_ : {A : Set} → (x : A) → List A → Set
a ∈ []       = ⊥
a ∈ (x ∷ xs) = (a ≡ x) ∨ (a ∈ xs)

inMap← : (A B : Set) → (f : A → B) → (as : List A) → (b : B) → Σ[ a ∈ A ] ((a ∈ as) ∧ (f a ≡ b)) → b ∈ map f as
inMap← A B f [] b h = let y , k = h in ∧-elim₁ k
inMap← A B f (a ∷ as) b h =
  let y , k = h
      l = ∧-elim₁ k
      r = ∧-elim₂ k
      g : y ≡ a  → (b ≡ f a) ∨ (b ∈ map f as) ; g x = ∨-intro₁ (sym (trans (cong f (sym x)) r))
      m : y ∈ as → (b ≡ f a) ∨ (b ∈ map f as) ; m x = ∨-intro₂ (inMap← A B f as b (y , ∧-intro x r))
  in ∨-elim g m l
```

This code typechecks.  Now replace the "r" at the end of the line that starts "g : y ≡ a" with a ?, type C-c C-l, go to the hole and type C-c C-, .  The following goal and context are displayed:

``` agda
Goal: f (Σ.proj₁ h) ≡ b
————————————————————————————————————————————————————————————
r  : a (Σ.proj₁ x) ≡ h
l  : (Σ.proj₁ x ≡ as) ∨ (Σ.proj₁ x ∈ b)
k  : ((Σ.proj₁ x ≡ as) ∨ (Σ.proj₁ x ∈ b)) ∧ (a (Σ.proj₁ x) ≡ h)
y  : B
x  : Σ.proj₁ h ≡ a
h  : Σ-syntax A (λ a₁ → ((a₁ ≡ a) ∨ (a₁ ∈ as)) ∧ (f a₁ ≡ b))
b  : B
as : List A
a  : A
f  : A → B
B  : Set
A  : Set
```

Note that the type of r is completely wrong and makes no sense (at least to me).  Its correct type is that of the goal, f (Σ.proj₁ h) ≡ b (or equivalently f y ≡ b; y should have type A, not B, which also seems to be an error), as can be seen from the second clause of ∧ in h from which it derives (note that the type of k, intermediate between h and r, is also incorrect).  Different levels of normalization (using C-u prefixes) give the same result.  Even though the displayed types are wrong the typechecker still seems to be working properly since r does in fact satisfy the goal.

Note also that if I retain the r but, for example, turn the final "l" in "∨-elim g m l" into a hole then all the types, including for r, k and y, seem to display correctly.  Making both "r"s (in the g: and m: lines) into holes on the other hand still fails.  Removing the g: and m: lines completely and finishing with "in ?" results in correct types.

**Comment by WolframKahl** [comment]
In the goal and context display, the variables are somehow permuted (or possibly just a subset of the variables is shifted ─ I haven't tried yet to make sense of that). I only had far more complicated instances of that so far, and unfortunately no time to try to cut it down.

**Comment by nad** [comment]
I get the following output (using more or less the most recent development version of Agda):

```
Goal: f (Σ.proj₁ h) ≡ b
————————————————————————————————————————————————————————————
r  : f (Σ.proj₁ h) ≡ b
l  : (Σ.proj₁ h ≡ a) ∨ (Σ.proj₁ h ∈ as)
k  : ((Σ.proj₁ h ≡ a) ∨ (Σ.proj₁ h ∈ as)) ∧ (f (Σ.proj₁ h) ≡ b)
y  : A
x  : Σ.proj₁ h ≡ a
h  : Σ-syntax A (λ a₁ → ((a₁ ≡ a) ∨ (a₁ ∈ as)) ∧ (f a₁ ≡ b))
b  : B
as : List A
a  : A
f  : A → B
B  : Set
A  : Set
```

Perhaps the problem has already been fixed. I'm closing this issue, feel free to reopen it if you encounter a similar problem with a more recent version of Agda.

**Comment by halfaya** [comment]
I just downloaded the latest development version and tried it out--it does work now.  Thank you very much.
