### ISSUE TITLE
Type information about the argument is lost in a pattern-matching lambda

### ISSUE THREAD

**Issue by yoricksijsling** [agda/agda#1922]
This part works as expected:

```
s : ∀ n → (f : (k : Fin n) → Bool) → Fin (suc n)
s n f = 0
t1 : Fin 2
t1 = s 1 (λ { zero → true ; (suc ()) })
```

But Agda is not able to infer the `1` in this case:

```
t2 : Fin 2
t2 = s _ (λ { zero → true ; (suc ()) })

Warning:
_142 : Nat
```

The problem gets worse when i add arguments to the `t2` function. This gives an error:

```
t3 : Set → Fin 2
t3 A = s _ (λ { zero → true ; (suc ()) })

Error:
Fin .n should be empty, but the following constructor patterns are
valid:
  zero {_}
  suc {_} _
when checking that the clause .extendedlambda1 (suc ()) has type
Fin (suc @1) → Bool
```

The interactive mode does tell me that (k : Fin 1) in the following case, it only goes wrong after the case split:

```
ok : Set → Fin 2
ok A = s _ (λ {k → ?})
```

I'm using the latest development version of Agda, commit 33f5bbf.

**Comment by andreasabel** [comment]
This type checks fine with Agda 2.4.2.6, but not with master. 
@jespercockx: Could this be a problem of the new unifier?

**Comment by andreasabel** [comment]
Here is a standalone version of the test case:

``` agda
data Bool : Set where
  true false : Bool

data Nat : Set where
  zero : Nat
  suc : Nat → Nat

one : Nat
one = suc zero

two : Nat
two = suc one

data Fin : Nat → Set where
  zero : ∀{n} → Fin (suc n)
  suc  : ∀{n} (i : Fin n) → Fin (suc n)

--This part works as expected:

s : ∀ n → (f : (k : Fin n) → Bool) → Fin (suc n)
s n f = zero

t1 : Fin two
t1 = s one (λ { zero → true ; (suc ()) })

-- But Agda is not able to infer the 1 in this case:

ttwo : Fin two
ttwo = s _ (λ { zero → true ; (suc ()) })

-- Warning:
-- _142 : Nat

-- The problem gets worse when i add arguments to the ttwo function. This gives an error:

t3 : Set → Fin two
t3 A = s _ (λ { zero → true ; (suc ()) })
```

**Comment by UlfNorell** [comment]
It does seem to be a problem with the new unifier and not related to pattern lambdas. Here's a variant:

``` agda
ttwo : Fin two

X Y : Nat
X = _   -- Yellow, but evaluating X returns suc zero
Y = _

plam : Fin X → Bool
plam zero = true
plam (suc ())

ttwo = s Y plam
```

It looks like the unifier is creating a dangling metavariable that's not connected to the other constraints.

**Comment by UlfNorell** [comment]
Fixed the problem with the dangling meta in 4d64b5e (but messed up the commit message). The `t3` problem still remains.

**Comment by jespercockx** [comment]
The unifier itself seems to be doing its job correctly, it just happens to get a unification problem with metas in it. It's possible that I introduced the problem when changing the LHS checker in order to make it work with the new unifier, however. Looking into it...

**Comment by jespercockx** [comment]
Turned out the problem came from the new unifier after all: the new metas generated as constructor arguments were generated in the wrong context, causing them to depend on the wrong variables and causing all kinds of havoc. Should now be fixed by https://github.com/agda/agda/commit/1bde75fdf8e4f91ecf6f6257bbf777b216c55f68.
