### ISSUE TITLE
Normalise applications of qualified names, coming from modules that are not in scope, when printing?

### ISSUE THREAD

**Issue by nad** [agda/agda#1924]
I debugged this issue together with @UlfNorell.

Consider the following four Agda files:

```
module A where

postulate
  F : Set → Set
  A : Set
  a : A
```

```
open import A

module B (a : A) where

postulate
  B : Set
```

```
open import A

module C (a : A) where

import B

-- "Working" variant:

open B a

-- "Broken" variant:

-- private
--   open module M = B a

postulate
  c : F B
```

```
module D where

open import A
open import B a
open import C

postulate
  foo : (A : Set) → A → A → A

Foo : F B
Foo = foo _ (c a) ?
```

If the "working" variant is used, then the goal type given by Agda is `F B` (with or without normalisation/simplification). If the "broken" variant is used, then the goal type is `F (.C.M.B a)` if the goal is not normalised, and `F B` if it is. The reason for this discrepancy seems to be that [some code in `InternalToAbstract`](https://github.com/agda/agda/blob/4d64b5eaf3f83d4428f999b6966a17e5a3fab04b/src/full/Agda/Syntax/Translation/InternalToAbstract.hs#L425-447) sometimes normalises applications of names coming from anonymous modules. Perhaps it would be a good idea to extend this code to also trigger for module names that are not in scope.

**Comment by UlfNorell** [comment]
Fixed by 7816e21 (attributed commit to #721).
