### ISSUE TITLE
Funny error context for C-c C-o (show module contents)

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#1925]
``` agda
module _ (A : Set) where

record R : Set where
  field f : A

test : R → R
test r = {!r!}
```

`C-c C-o` gives error

```
No such module r when checking that the expression ? has type R
```

I guess the `when checking...` is not accurate.

**Comment by andreasabel** [comment]
Fixed this to print "when retrieving the contents of a module" instead.

**Comment by asr** [comment]
Thanks for adding the 2.5.1 milestone when closing the issue.
