### ISSUE TITLE
Just the usual lack of subject reduction?

### ISSUE THREAD

**Issue by nad** [agda/agda#1931]
Consider the following code:

```
{-# OPTIONS --rewriting #-}

postulate
  C  : Set

  D  : Set → Set
  d₁ : (A : Set) → D A
  d₂ : (A : Set) → (C → D A) → D A

  E  : (A : Set) → A → A → Set
  e₁ : (A : Set) (j₁ j₂ : C → D A) →
       ((c : C) → E (D A) (j₁ c) (j₂ c)) →
       (y : D A) →
       E (D A) (d₂ A j₁) y

  f  : (A B : Set) → D A → D B
  f₁ : (A B : Set) → E (D B) (f A B (d₁ A)) (d₁ B)
  f₂ : (A B : Set) (j : C → D A) →
       E (D B) (f A B (d₂ A j)) (d₂ B (λ c → f A B (j c)))

  g  : (A : Set) (Q : D A → Set) →
       Q (d₁ A) →
       ((j : C → D A) → ((c : C) → Q (j c)) → Q (d₂ A j)) →
       (c : D A) → Q c

{-# BUILTIN REWRITE E #-}
{-# REWRITE f₁        #-}
{-# REWRITE f₂        #-}

h : (A B : Set)
    (i : D A → D B) →
    E (D B) (d₁ B) (i (d₁ A)) →
    (d : D A) → E (D B) (f A B d) (i d)
h A B i e₂ = g
  A
  (λ (d : D A) → E (D B) {!f A B d!} (i d))
  e₂
  (λ j q → e₁ B (λ c → f A B (j c)) (λ c → i (j c)) q (i (d₂ A j)))
```

(The example is partly based on some code that I wrote together with Thorsten Altenkirch, but it has been shrunk and obfuscated.)

The code is rejected with the following error message:

```
(d₁ B) != (f A B (j c)) of type (D B)
when checking that the expression q has type
(c : C) → E (D B) (f A B (j c)) (i (j c))
```

However, if the hole above is instantiated with the expression contained in it, then the code is accepted. The code is also accepted if the third argument to `g` is replaced by a hole, and given after the module has been loaded.

I don't know if the problem illustrated above is a genuine bug, or just an instance of the rewrite machinery's lack of subject reduction (#1445).

**Comment by andreasabel** [comment]
Thanks!  Was this fixed by https://github.com/agda/agda/commit/f21aa28c1a5b8cad06b0f220fb6a630e4130783e ?

**Comment by jespercockx** [comment]
Yes, both problems turned out to be caused by the lies that there were no blocking metas.
