### ISSUE TITLE
Release Agda 2.5.1

### ISSUE THREAD

**Issue by asr** [agda/agda#1933]
I just realised that  [AIM XXIII](http://wiki.portal.chalmers.se/agda/pmwiki.php?n=Main.AIMXXIII) will start on 20 April (I thought it would start on 26 April), so if we want to release 2.5.1 before AIM XXIII  we don't have much time available.

Do we need to rush for releasing 2.5.1? What do you think?

What about the regressions labelled with the 2.5.1 milestone, i.e. #1523, #1775 and #1821?

**Comment by jespercockx** [comment]
I'm quite certain I won't be able to fix #1775 before the start of AIM next week. I have some ideas on how to fix it, but they require a non-trivial amount of implementation. Maybe during or after AIM I'll fix it.

**Comment by UlfNorell** [comment]
In my opinion none of those issues are release blocking. I think it would be good if we could get the release out, but of course if people find new problems with the release candidate that's not going to happen. At the very least I think it's important to have the new maintenance branch structure set up before the meeting.

**Comment by asr** [comment]
> I'm quite certain I won't be able to fix #1775 before the start of AIM next week. I have some ideas on how to fix it, but they require a non-trivial amount of implementation. Maybe during or after AIM I'll fix it.

Thanks for the feedback. It is perfectly understandable.

**Comment by asr** [comment]
> In my opinion none of those issues are release blocking.

I changed the milestone of #1775 to 2.5.2.

@andreasabel what about #1523 and #1821?

> At the very least I think it's important to have the new maintenance branch structure set up before the meeting.

I absolutely agree.

**Comment by WolframKahl** [comment]
FWIW, I encountered no problems when doing my routine measurements on essentially all my active material with 7ba987b9870173a6a362b59fa6488222239a4eb7, which, according to `git log`, is for my purposes identical with 2.5.1-rc2 (so that I don't bother to install the latter).

**Comment by asr** [comment]
Great! Thanks!

**Comment by andreasabel** [comment]
I am mostly done fixing #1821.  I pushed a patch, but need to add the test case etc.
This is to say please do not release without this fix.  Thanks!

**Comment by andreasabel** [comment]
I am done with the work on #1821 and removed the milestone for #1523.  From my perspective, we can release.

**Comment by asr** [comment]
Great! Thanks!

**Comment by asr** [comment]
Starting...

**Comment by asr** [comment]
I have tested the installation of  [Agda-2.5.1.tar.gz](http://www1.eafit.edu.co/asr/tmp/Agda-2.5.1.tar.gz) in Ubuntu 12.04.5 64-bits with:
- GHC 7.6.3, 7.8.4 and 7.10.3, and
- GHC 7.10.3 and the `uhc` flag

Could someone test the installation of 2.5.1 on Windows and/or Mac OS using the following instructions:

```
  $ tar xzf Agda-2.5.1.tar.gz
  $ cd Agda-2.5.1
  $ cabal install
```

If you have Mac OS and GHC 7.10.*, please also test

```
$ cabal install -f uhc
```

**Comment by asr** [comment]
I'm waiting the above tests for adding a tag into the repository...

**Comment by jespercockx** [comment]
Installation of agda and agda-mode worked for me on Windows 10 using GHC
7.10.3 and Emacs 25, and I was able to check the master branch of the
standard library (84ad2bf)

Jesper

**Comment by asr** [comment]
Thanks!

**Comment by asr** [comment]
FYI, I renamed the 2.5.2 milestone. The new name is 2.5.1.1.

**Comment by asr** [comment]
Done.

**Comment by UlfNorell** [comment]
Thanks Andrés. Well done!

**Comment by asr** [comment]
> Installation of agda and agda-mode worked for me on Windows 10 using GHC 7.10.3 and Emacs 25

@jespercockx which Linux-like environment for Windows (e.g. Cygwin) and version did you use for testing 2.5.1 on Windows 10?

**Comment by UlfNorell** [comment]
I tested it on Windows 10 with the Haskell Platform that has ghc-7.10.3 and MinGW (unknown version).

**Comment by jespercockx** [comment]
I didn't use any linux-like environment, I just installed agda using the Haskell platform for windows and Aaron Stump's installer for emacs (as linked in the readme). It seemed to me that Aaron's installer also installed an older version of Agda automatically, but just removing the old version and keeping the emacs installation worked for me.

**Comment by UlfNorell** [comment]
I should say that I have no idea if having MinGW installed was necessary.
