### ISSUE TITLE
Strange error in rewrite & pattern matching involving functions with implicit arguments

### ISSUE THREAD

**Issue by ghost** [agda/agda#1934]
http://pastebin.com/tTDuAaRV
In the function id-lem-left:
It doesn't accept "rewrite id-lem-right {a}", and gives the strange error:
"""
Function does not accept argument {r = _}
when checking that {r = a} is a valid argument to a function of
type {a : G} → G
"""

even if I change it to 

  id-lem-left : {a : G} -> (a op e {a}) ≡ a
  id-lem-left {a} with id-lem-right {a}
  ...                           | refl = {!!}
It give me the error that "a != fst id op a of type G"

Seems that this problem is related to the implicit argument by the discussions on #agda @ freenode
Changing the implicit argument of e to explicit does not help

**Comment by UlfNorell** [comment]
Agda-2.5.1 accepts the rewrite happily (of course there's nothing to rewrite, but also no error).

``` agda
id-lem-left : {a : G} -> (a op e {a}) ≡ a
id-lem-left {a} with id-lem-right {a}
... | refl = {!!}
```

is not the proper desugaring of the rewrite and should not type check. See http://agda.readthedocs.org/en/latest/language/with-abstraction.html#rewrite.

**Comment by asr** [comment]
I could reproduce the issue with Agda 2.4.2.5. I added a successful test case.

**Comment by ghost** [comment]
wonders which change/commit in Agda fixed this bug

**Comment by asr** [comment]
I added the new `already-fixed` label to this issue.

**Comment by asr** [comment]
> wonders which change/commit in Agda fixed this bug

I couldn't reproduce the issue in maint-2.4. Bisection indicates that the bug was fixed by b2c11d7.

**Comment by andreasabel** [comment]
Good!

**Comment by asr** [comment]
@andreasabel For a while I asked myself why did you continue pushing to maint-2.4. The information required by this issue gave me one answer. Thanks for pushing to maint-2.4.
