### ISSUE TITLE
Notify on user manual build failures

### ISSUE THREAD

**Issue by phile314** [agda/agda#1936]
Issue https://github.com/agda/agda/issues/1935 happend without anybody noticing. This shouldn't happen again.

Maybe readthedocs.org itself or travis can notify us on build failures?

**Comment by phile314** [comment]
@asr Travis builds the documentation as well, right? So normally it should catch user manual build problems?

Because the problem was that RTD.org had a too old Sphinx version, there was no way travis could catch that. Adding a comment to .travis.yml and doc/user-manual/requirements.txt that the Sphinx version should be kept in sync should be good enough I think.

**Comment by asr** [comment]
> @asr Travis builds the documentation as well, right?

Yes.

> So normally it should catch user manual build problems?

Yes.

> Because the problem was that RTD.org had a too old Sphinx version, there was no way travis could catch that. Adding a comment to .travis.yml and doc/user-manual/requirements.txt that the Sphinx version should be kept in sync should be good enough I think.

I think so. Please add the documentation and close the issue.
