### ISSUE TITLE
`--no-default-libraries` doesn't use project local `.agda-lib`

### ISSUE THREAD

**Issue by adamse** [agda/agda#1937]
It seems that when I use `--no-default-libraries` also ignores project local `.agda-lib` files, I would expect that option to only exclude the `defaults` file.

(This is in Agda 2.5.1)

**Comment by Blaisorblade** [comment]
Confirmed:
- the docs document what you'd expect: http://agda.readthedocs.io/en/latest/tools/package-system.html
- the sources implement the behavior you actually observe:
  https://github.com/agda/agda/blob/fcc5f586ae0d9ee80f2fce9d143da682987dbede/src/full/Agda/TypeChecking/Monad/Options.hs#L106
  EDIT: Source commentary: with `--no-default-libraries`, `optDefaultLibs o` is false, so `addDefaultLibraries` returns `o` unchanged with `pure o`.

**Comment by nad** [comment]
I used to use `--no-default-libraries` to ensure that all `.agda-lib` files were ignored (see `HACKING` for one example). Now this no longer works. Perhaps we should add a flag (`--no-libraries`?) that works like `--no-default-libraries` used to work.
