### ISSUE TITLE
Hackage reports "Build status unknown [no reports yet]" for 2.4.2.1, 2.4.2.2, 2.4.2.5 and 2.5.1

### ISSUE THREAD

**Issue by asr** [agda/agda#1938]
I'll will report the issue on Hackage.

**Comment by andreasabel** [comment]
Also, there are no docs since 2.4.2.3.

**Comment by asr** [comment]
> I'll will report the issue on Hackage.

Done. https://github.com/haskell/hackage-server/issues/489.

**Comment by asr** [comment]
> Also, there are no docs since 2.4.2.3.

It seems that (see [2.4.2.2](http://hackage.haskell.org/package/Agda-2.4.2.2)) the unknown build status and the missing documentation are different issues. I filed #1940 for the docs.

**Comment by asr** [comment]
The unknown build status implies the missing documentation. Since I closed #1940, I'm closing this issue.
