### ISSUE TITLE
Missing documentation on Hackage since 2.4.2.3

### ISSUE THREAD

**Issue by asr** [agda/agda#1940]

**Comment by asr** [comment]
I'll will report the issue on Hackage.

**Comment by andreasabel** [comment]
There are logs (for building the documentation) saying something about the wrong version of cpphs, so I guess it is partially our fault.

**Comment by asr** [comment]
I uploaded the documentation for [2.4.2.3](https://hackage.haskell.org/package/Agda-2.4.2.3), [2.4.2.4](https://hackage.haskell.org/package/Agda-2.4.2.4), [2.4.2.5](https://hackage.haskell.org/package/Agda-2.4.2.5) and [2.5.1](https://hackage.haskell.org/package/Agda-2.5.1) using the [neil](https://hackage.haskell.org/package/neil) program.

**Comment by andreasabel** [comment]
Thanks!
