### ISSUE TITLE
Version numbers

### ISSUE THREAD

**Issue by asr** [agda/agda#1941]
@asr [wrote](https://github.com/agda/agda/issues/1834#issuecomment-211520606): I think 2.5.1.1 is for the next stable release.

@UlfNorell [wrote](https://github.com/agda/agda/issues/1834#issuecomment-211573984): No, we only release 2.5.1.1 if there aren't any compatibility breaking changes--something that seems exceedingly unlikely with the new branch policy. We did make room in the version numbers to allow 2.5.2 to be released from stable for this very reason.

@WolframKahl [wrote](https://github.com/agda/agda/issues/1834#issuecomment-211666911): That forces me to have quite horribly long version numbers for all the intermediate development versions until then: 2.5.1.0.1, 2.5.1.0.2, ...

@andreasabel [wrote](https://github.com/agda/agda/issues/1834#issuecomment-211825793): No, only 2.5.1.1, 2.5.1.2, etc.

@WolframKahl [wrote](https://github.com/agda/agda/issues/1834#issuecomment-211968256): I was referring to my own versions, that is, every time I install the current development version. Right now, `Agda.cabal` says:

```
name:            Agda
version:         2.6.0
```

But since that won't be changing at least until the next release, and since `2.5.1 < 2.6.0 ≮ 2.5.1.1`, using that version number for anything can only be misleading. So the next time I install the current development version, I will call it 2.5.1.0.1, since `2.5.1 < 2.5.1.0.1 < 2.5.1.1`, and there is ample space for more installations before the next release, which, according to the previous posts here, may well come out with number 2.5.1.1.

**Comment by UlfNorell** [comment]
Here's what I think we should do:
- bump the version of stable to `2.5.2`, and when we release it will be `2.5.2.1`
- if needed, release `2.5.1.1` by cherry-picking important bug fixes to a stand-alone `maint-2.5.1` branch

This way there aren't any version clashes between actual releases and snapshots of the repository. It's a little odd that current stable is `2.5.1.1` when we might release a `2.5.1.1` with fewer features.

**Comment by asr** [comment]
I agree with bumping the version of stable to 2.5.2.

> bump the version of stable to 2.5.2, and when we release it will be 2.5.2.1

I suggest to use 2.5.2 for the release and after the release to bump the version of stable to 2.5.3.

**Comment by UlfNorell** [comment]
The advantage of releasing it as 2.5.2.1 is that there's no confusion between the release and a snapshot of stable.

**Comment by asr** [comment]
I see. I'll bump the version of stable.

**Comment by asr** [comment]
I merged the milestone 2.5.1.1 into the milestone 2.5.2.

**Comment by UlfNorell** [comment]
I guess it would make sense to keep the 2.5.1.1 milestone for critical bugs.

**Comment by asr** [comment]
Anyone with enough permissions can create the milestone if necessary.

**Comment by asr** [comment]
> I'll bump the version of stable.

Done.

**Comment by Blaisorblade** [comment]
@asr is there anything still to do here, or can this be closed?

**Comment by UlfNorell** [comment]
> The advantage of releasing it as 2.5.2.1 is that there's no confusion between the release and a snapshot of stable.

Since we now include commit hashes in `--version` output, this argument no longer applies.
