### ISSUE TITLE
agda-mode: Symbol's function definition is void: byte-compile-disable-warning

### ISSUE THREAD

**Issue by asr** [agda/agda#1945]
@mietek [wrote](https://github.com/agda/agda/issues/1799#issuecomment-212512137):

There appears to be an issue with compiling `agda-mode` using GHC 8.0.1-rc3, as reported in https://github.com/Homebrew/homebrew-core/pull/440#issuecomment-212501561 by @ilovezfs:

```
==> /usr/local/Cellar/agda/2.5.1/bin/agda-mode compile
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Unable to compile the following Emacs Lisp files:
  /usr/local/Cellar/agda/2.5.1/share/x86_64-osx-ghc-8.0.0.20160411/Agda-2.5.1/emacs-mode/agda2-abbrevs.el
  /usr/local/Cellar/agda/2.5.1/share/x86_64-osx-ghc-8.0.0.20160411/Agda-2.5.1/emacs-mode/annotation.el
  /usr/local/Cellar/agda/2.5.1/share/x86_64-osx-ghc-8.0.0.20160411/Agda-2.5.1/emacs-mode/agda2-queue.el
  /usr/local/Cellar/agda/2.5.1/share/x86_64-osx-ghc-8.0.0.20160411/Agda-2.5.1/emacs-mode/eri.el
  /usr/local/Cellar/agda/2.5.1/share/x86_64-osx-ghc-8.0.0.20160411/Agda-2.5.1/emacs-mode/agda2.el
  /usr/local/Cellar/agda/2.5.1/share/x86_64-osx-ghc-8.0.0.20160411/Agda-2.5.1/emacs-mode/agda-input.el
  /usr/local/Cellar/agda/2.5.1/share/x86_64-osx-ghc-8.0.0.20160411/Agda-2.5.1/emacs-mode/agda2-highlight.el
  /usr/local/Cellar/agda/2.5.1/share/x86_64-osx-ghc-8.0.0.20160411/Agda-2.5.1/emacs-mode/agda2-mode.el
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: /usr/local/Cellar/agda/2.5.1/bin/agda-mode compile
```

**Comment by asr** [comment]
@asr [wrote](https://github.com/agda/agda/issues/1799#issuecomment-212535152): @mietek I couldn't reproduce the issue with GNU Emacs 24.5.1

**Comment by asr** [comment]
@ilovezfs [wrote](https://github.com/agda/agda/issues/1799#issuecomment-212772770): @asr Given that the issue does not occur when using agda 2.5.1 + ghc-7.10.3b + emacs 22.1.1, and it does occur when using agda 2.5.1 + ghc 8.0.1-rc3 + emacs 22.1.1, there's clearly some sort of difference.

**Comment by asr** [comment]
I didn't see any difference using Agda 2.5.1, GNU Emacs 22.1.1 and  GHC 8.0.1-rc3 or GHC 7.10.3., that is, `agda-mode compile` generates the error reported in the OP.

**Comment by ilovezfs** [comment]
It's a build-time failure when agda-mode compile is run.

**Comment by asr** [comment]
Did you mean it's not an Agda issue?

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-core/blob/master/Formula/agda.rb#L71-L75

I mean that fails, so the whole thing fails.

**Comment by ilovezfs** [comment]
`agda-mode compile` fails, which causes the entire `brew install --build-from-source agda` to fail. This doesn't happen if the GHC is 7.10.3.

**Comment by asr** [comment]
As I said, I could reproduce the issue with both GHC 8.0.1-rc3 and 7.10.3, so I'm closing the issue.

**Comment by ilovezfs** [comment]
Can you explain what you mean by "with both GHC 8.0.1-rc3 and 7.10.3"? Where are you testing this?

**Comment by asr** [comment]
I installed `agda-mode` from Agda 2.5.1 with both versions of GHC. Using GNU Emacs 22.1.1, I got the following errors:
- GHC 7.10.3

```
$ agda-mode compile
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Unable to compile the following Emacs Lisp files:
  /home/asr/.cabal/share/x86_64-linux-ghc-7.10.3/Agda-2.5.1/emacs-mode/agda2-abbrevs.el
  /home/asr/.cabal/share/x86_64-linux-ghc-7.10.3/Agda-2.5.1/emacs-mode/annotation.el
  /home/asr/.cabal/share/x86_64-linux-ghc-7.10.3/Agda-2.5.1/emacs-mode/agda2-queue.el
  /home/asr/.cabal/share/x86_64-linux-ghc-7.10.3/Agda-2.5.1/emacs-mode/eri.el
  /home/asr/.cabal/share/x86_64-linux-ghc-7.10.3/Agda-2.5.1/emacs-mode/agda2.el
  /home/asr/.cabal/share/x86_64-linux-ghc-7.10.3/Agda-2.5.1/emacs-mode/agda-input.el
  /home/asr/.cabal/share/x86_64-linux-ghc-7.10.3/Agda-2.5.1/emacs-mode/agda2-highlight.el
  /home/asr/.cabal/share/x86_64-linux-ghc-7.10.3/Agda-2.5.1/emacs-mode/agda2-mode.el
```
- GHC 8.0.1-rc3

```
$ agda-mode compile
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Unable to compile the following Emacs Lisp files:
  /home/asr/.cabal/share/x86_64-linux-ghc-8.0.0.20160411/Agda-2.5.1/emacs-mode/agda2-abbrevs.el
  /home/asr/.cabal/share/x86_64-linux-ghc-8.0.0.20160411/Agda-2.5.1/emacs-mode/annotation.el
  /home/asr/.cabal/share/x86_64-linux-ghc-8.0.0.20160411/Agda-2.5.1/emacs-mode/agda2-queue.el
  /home/asr/.cabal/share/x86_64-linux-ghc-8.0.0.20160411/Agda-2.5.1/emacs-mode/eri.el
  /home/asr/.cabal/share/x86_64-linux-ghc-8.0.0.20160411/Agda-2.5.1/emacs-mode/agda2.el
  /home/asr/.cabal/share/x86_64-linux-ghc-8.0.0.20160411/Agda-2.5.1/emacs-mode/agda-input.el
  /home/asr/.cabal/share/x86_64-linux-ghc-8.0.0.20160411/Agda-2.5.1/emacs-mode/agda2-highlight.el
  /home/asr/.cabal/share/x86_64-linux-ghc-8.0.0.20160411/Agda-2.5.1/emacs-mode/agda2-mode.el
```

**Comment by asr** [comment]
For the record, to install GNU Emacs 22.1.1 in my Ubuntu 12.04.5 I followed [these](http://stackoverflow.com/questions/16124763/emacs-22-3-does-not-compile-on-ubuntu-12-04) instructions.

**Comment by ilovezfs** [comment]
OK, so not on OS X 10.11. Thanks for clarifying.

Is the exit code the same in both cases? That's my top suspicion right now. That it differs.

**Comment by ilovezfs** [comment]
Ah I see what's going on now. When brew does --build-bottle it's installing the newer emacs along the way which means it doesn't trip over this, and you're right that it's not a problem specific to the new ghc, just a difference between --build-bottle and --build-from-source. Thanks for checking.

**Comment by ilovezfs** [comment]
@asr Do you know the minimum emacs the compiled bindings actually do work with?

**Comment by asr** [comment]
No.

**Comment by ilovezfs** [comment]
@asr hmm OK. I will investigate further so that brew's --build-from-source actually works for agda even if the user only has the system emacs.

**Comment by asr** [comment]
Thanks!

**Comment by zmwangx** [comment]
@ilovezfs 

To respond to [your earlier question in another thread](https://github.com/agda/agda/issues/1799#issuecomment-212945179):

> Despite the error, do the compiled agda emacs bindings from the bottle work with 21.1.1 at all?

No. Here are the steps to reproduce the error:
1. `/usr/bin/emacs -Q`;
2. `M-: (load-file (let ((coding-system-for-read 'utf-8)) (shell-command-to-string "agda-mode locate"))) RET`;
3. `M-x agda2-mode`.

At this point you get an error:

```
`/usr/local/Cellar/agda/2.5.1/share/x86_64-osx-ghc-7.10.3/Agda-2.5.1/emacs-mode/agda2-mode.elc' was compiled for Emacs 23 or later
```

**Comment by mietek** [comment]
> Despite the error, do the compiled agda emacs bindings from the bottle work with 21.1.1 at all? If not we really should raise that requirement to whatever is the minimum that does actually work.

@ilovezfs: The existing minimum is completely arbitrary. @xu-cheng added it simply because there was no minimum before, and there is no reason for sticking specifically with 21.1. Feel free to raise it.

See the commit here: https://github.com/Homebrew/legacy-homebrew/commit/4c764c70bac9a3f6691c5de51d7b404c321812c2

**Comment by zmwangx** [comment]
I would say any Emacs user worth their salt shouldn't be using system Emacs 21, so it's pretty safe to raise the minimum. But whether Emacs should remain `:recommended` is debatable if we require a newer version.

**Comment by mietek** [comment]
See also the brief discussion on the matter here: https://github.com/Homebrew/legacy-homebrew/pull/45327#discussion_r43578621

**Comment by mietek** [comment]
@zmwangx: Emacs should remain `:recommended` because Emacs is the primary mode of interaction with Agda.

**Comment by ilovezfs** [comment]
@mietek Yeah, there was a bug at the time that he was working around. The bug has since been fixed, but the workarounds remain.

@zmwangx Right now the consequence of having it as recommended is that brew emacs is actually forced on the user when you install from a bottle:

```
iMac-TMP:~ joe$ brew install agda
==> Installing dependencies for agda: emacs
==> Installing agda dependency: emacs
==> Downloading https://homebrew.bintray.com/bottles/emacs-24.5.el_capitan.bottle.2.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/emacs-24.5.el_capitan.bottle.2.tar.gz
==> Pouring emacs-24.5.el_capitan.bottle.2.tar.gz
^C
```

**Comment by zmwangx** [comment]
> Right now the consequence of having it as recommended is that brew emacs is actually forced on the user when you install from a bottle

Hmm interesting. Then no objection to raising the minimum AND keeping it recommended.

**Comment by ilovezfs** [comment]
@zmwangx Yeah, it's probably better to just get the appropriate minimum in there rather than require people to figure out they need to do `agda-mode compile` on their own.

**Comment by zmwangx** [comment]
> rather than require people to figure out they need to do agda-mode compile on their own.

Byte compiling is not really required. Emacs can run code from Elisp source files (`.el`) just fine (but `agda2-mode` first needs to support 22.1.1, which I doubt). Byte compiling to `.elc` just makes it faster.

**Comment by ilovezfs** [comment]
Here's the counterargument to making it recommended:

```
Josephs-MacBook-Pro:Formula joe$ ag "depends_on" | grep emacs | grep -v emacs.rb
agda.rb:47:  depends_on :emacs => ["21.1", :recommended]
cask.rb:10:  depends_on :emacs => ["24", :run]
doxymacs.rb:21:  depends_on :emacs => "20.7.1"
emacs-clang-complete-async.rb:22:  depends_on "llvm" => "with-clang"
mu.rb:26:  depends_on :emacs => ["23", :optional]
nesc.rb:10:  depends_on :emacs => :build
notmuch.rb:16:  depends_on :emacs => ["21.1", :optional]
proof-general.rb:21:  depends_on :emacs => "22.3"
Josephs-MacBook-Pro:Formula joe$
```

**Comment by zmwangx** [comment]
I have no strong preference either way. To me `/usr/bin/emacs` is just a joke (damn GPLv3).

By the way, what is `ag`? An alias of `grep -rIn`?

**Comment by ilovezfs** [comment]
`ag` is a pun on `ack`. It's the command name for `the_silver_searcher`. There's now also `the_platinum_searcher`, the command for which is, of course, `pt`.

https://github.com/ggreer/the_silver_searcher (written in C)
https://github.com/monochromegane/the_platinum_searcher (written in Go)

You can `brew install the_silver_searcher` or `brew install ag`.

**Comment by zmwangx** [comment]
Interesting, bookmarked. (I'll probably keep on sticking with good ol' grep though. I've got `ack` bookmarked for probably years but I've been too lazy to ever take a serious look... 😜 GNU grep + general grep alias ignoring VCS and stuff like .tox + a few dedicated grep aliases/wrappers served me very well.)

**Comment by ilovezfs** [comment]
@zmwangx You should really try it vs. grep. The speed difference is absurd especially with source code.

**Comment by zmwangx** [comment]
Sure, will try. I `grep -rI` all the time and never felt slow though... (By the way, sorry for being off-topic.)

**Comment by ilovezfs** [comment]
It's probably not appropriate to install emacs just because someone is using bottled agda, especially since you said it's not necessary to byte compile it (sorry for my ignorance - I only use vi).

The only ones with non-optional dependencies on emacs appear to be `cask`, `doxymacs`, and `proof-general`, all of which are emacs specific formulae.

**Comment by zmwangx** [comment]
`agda2-mode` isn't just a bunch of font-lock definitions; it seems to pack much interactivity and tightly integrates with the compiler (see [docs](http://wiki.portal.chalmers.se/agda/pmwiki.php?n=Docs.EmacsModeKeyCombinations)). The facts that
- Emacs integration is prominent in README;
- `agda` ships three binaries, one of them being `agda-mode`;

all seem to suggest Emacs's special position for Agda.

So I'd say it's okay to recommend Emacs in the formula.

**Comment by ilovezfs** [comment]
@zmwangx It looks like @mietek already litigated this so it's fine: https://github.com/Homebrew/legacy-homebrew/pull/45327

A correct minimum version should be sufficient to put the issue to rest.

**Comment by zmwangx** [comment]
I just tried to mess around with `agda2-mode` in system Emacs (byte-recompiled first), and didn't encounter any obvious issues (I couldn't get ahold of any code with "goals", so no messing around with goal-related functions), so I have no idea if it is broken in 22.1.1.

By the way, this is no longer an Agda issue and an issue/PR should be created in Homebrew rather than tagging along in this thread. @mietek Could you please open an issue?

**Comment by ilovezfs** [comment]
I fixed this in https://github.com/Homebrew/homebrew-core/pull/3193 since it finally bit a user, at least one who reported it.

**Comment by asr** [comment]
@ilovezfs from http://git.savannah.gnu.org/cgit/emacs.git/tree/etc/NEWS.23#n1910, the `byte-compile-disable-warning` function was added in Emacs 23.1. Had you any particular reason to raise the Emacs requirement to 23.4 instead of 23.1?

**Comment by ysharoda** [comment]
I have the exact same problem. I run Mac OS Sierra, Emacs 24.5 and Agda 2.5.4. 
I installed agda using homebrew, but emacs cannot load the agda-mode. 

Here is the error that I get on emacs: 
> File error: Cannot open load file, no such file or directory, /bin/bash: agda-mode: command not found

Here is the error that I get when I run "agda-mode compile" 
> Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Unable to compile the following Emacs Lisp files:
  /usr/local/Cellar/agda/2.5.4/share/x86_64-osx-ghc-8.4.3/Agda-2.5.4/emacs-mode/agda2-abbrevs.el
  /usr/local/Cellar/agda/2.5.4/share/x86_64-osx-ghc-8.4.3/Agda-2.5.4/emacs-mode/annotation.el
  /usr/local/Cellar/agda/2.5.4/share/x86_64-osx-ghc-8.4.3/Agda-2.5.4/emacs-mode/agda2-queue.el
  /usr/local/Cellar/agda/2.5.4/share/x86_64-osx-ghc-8.4.3/Agda-2.5.4/emacs-mode/eri.el
  /usr/local/Cellar/agda/2.5.4/share/x86_64-osx-ghc-8.4.3/Agda-2.5.4/emacs-mode/agda2.el
  /usr/local/Cellar/agda/2.5.4/share/x86_64-osx-ghc-8.4.3/Agda-2.5.4/emacs-mode/agda-input.el
  /usr/local/Cellar/agda/2.5.4/share/x86_64-osx-ghc-8.4.3/Agda-2.5.4/emacs-mode/agda2-highlight.el
  /usr/local/Cellar/agda/2.5.4/share/x86_64-osx-ghc-8.4.3/Agda-2.5.4/emacs-mode/agda2-mode.el

Any idea how to fix this?

**Comment by nad** [comment]
> > /bin/bash: agda-mode: command not found

It seems as if agda-mode was not installed on your PATH.

**Comment by ilovezfs** [comment]
Note the Hombrew formula does install agda-mode.
```
iMac-TMP:~ joe$ ls /usr/local/Cellar/agda/2.5.4/bin/
agda		agda-mode
iMac-TMP:~ joe$ mdutil -t `which agda-mode`
/usr/local/Cellar/agda/2.5.4/bin/agda-mode
iMac-TMP:~ joe$ which agda-mode
/usr/local/bin/agda-mode
iMac-TMP:~ joe$ 
```

**Comment by ysharoda** [comment]
agda-mode is in the PATH. 
I can actually run 
`> agda-mode locate`
`/usr/local/Cellar/agda/2.5.4/share/x86_64-osx-ghc-8.4.3/Agda-2.5.4/emacs-mode/agda2.el`
and 
`> agda-mode setup`
`The .emacs file used: /Users/ymmagdi/.emacs`
`It seems as if setup has already been performed.`
But I still get the error when I run `agda-mode compile` 

Is the error related to compiling the .el files using the `byte-compile-disable-warning` function?

**Comment by ilovezfs** [comment]
Which emacs is in your PATH?
```
iMac-TMP:~ joe$ agda-mode compile
Loading quail/latin-ltx...


iMac-TMP:~ joe$ brew unlink emacs
Unlinking /usr/local/Cellar/emacs/26.1_1... 3913 symlinks removed
iMac-TMP:~ joe$ agda-mode compile
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Symbol's function definition is void: byte-compile-disable-warning
Unable to compile the following Emacs Lisp files:
  /usr/local/Cellar/agda/2.5.4/share/x86_64-osx-ghc-8.4.3/Agda-2.5.4/emacs-mode/agda2-abbrevs.el
  /usr/local/Cellar/agda/2.5.4/share/x86_64-osx-ghc-8.4.3/Agda-2.5.4/emacs-mode/annotation.el
  /usr/local/Cellar/agda/2.5.4/share/x86_64-osx-ghc-8.4.3/Agda-2.5.4/emacs-mode/agda2-queue.el
  /usr/local/Cellar/agda/2.5.4/share/x86_64-osx-ghc-8.4.3/Agda-2.5.4/emacs-mode/eri.el
  /usr/local/Cellar/agda/2.5.4/share/x86_64-osx-ghc-8.4.3/Agda-2.5.4/emacs-mode/agda2.el
  /usr/local/Cellar/agda/2.5.4/share/x86_64-osx-ghc-8.4.3/Agda-2.5.4/emacs-mode/agda-input.el
  /usr/local/Cellar/agda/2.5.4/share/x86_64-osx-ghc-8.4.3/Agda-2.5.4/emacs-mode/agda2-highlight.el
  /usr/local/Cellar/agda/2.5.4/share/x86_64-osx-ghc-8.4.3/Agda-2.5.4/emacs-mode/agda2-mode.el
iMac-TMP:~ joe$ 
```

**Comment by ysharoda** [comment]
/usr/bin/emacs
After I added these three lines to PATH, Aquamacs is working in agda-mode, but not emacs !! 

`export PATH=/usr/local/bin/agda-mode:$PATH`
`export PATH=/usr/local/Cellar/agda/2.5.4/bin/agda-mode:$PATH`
`export PATH=/usr/local/Cellar/agda/2.5.4/share/x86_64-osx-ghc-8.4.3/Agda-2.5.4/emacs-mode/:$PATH
`

**Comment by ilovezfs** [comment]
`/usr/bin/emacs` is the system emacs. The Homebrew `agda` formula depends on the Homebrew `emacs` formula, which you seem to have uninstalled or unlinked.

```
brew reinstall emacs
```

and `which emacs` should point to `/usr/local/bin/emacs`.

**Comment by ysharoda** [comment]
I did `brew reinstall emacs` then `which emacs`, got the same path 

`/usr/bin/emacs`

**Comment by ilovezfs** [comment]
What's the output of
```
echo $PATH
brew unlink emacs
brew link emacs
hash -r
ls -l /usr/local/bin/emacs
which emacs
```
