### ISSUE TITLE
Mixfix binders no longer supported in 'syntax'

### ISSUE THREAD

**Issue by davdar** [agda/agda#1951]
I just upgraded to Agda 2.5.1 and it appears mixfix binders are no longer supported in 'syntax' pattern binders. Example below. I believe `doesn't-parse₁` and `doesn't-parse₂` worked just fine in Agda 2.4.2.5. The only difference is their binders have underscores and are therefore mixfix identifiers. Was this change intentional or is it a bug?

```
module Bug where

-- setup, to be self contained --
data _≡_ {A : Set} (x : A) : A → Set where
  refl : x ≡ x

data ℕ : Set where
  Zero : ℕ
  Succ : ℕ

-- a dependent sum datatype
data Σ (A : Set) (P : A → Set) : Set where
  ⟨_,_⟩ : ∀ (x : A) → P x → Σ A P

-- syntax for dependent sum
syntax Σ A (λ x → P) = ∃ x ⦂ A 𝑠𝑡 P

-- these work
does-parse₁ : ∃ ⟦⟧ ⦂ (ℕ → ℕ) 𝑠𝑡 (∀ n → ⟦⟧ n ≡ n)
does-parse₁ = ⟨ (λ x → x) , (λ n → refl) ⟩

does-parse₂ : ∃ ⟦⟧ ⦂ (ℕ → ℕ) 𝑠𝑡 let ⟦_⟧ = ⟦⟧ in (∀ n → ⟦ n ⟧ ≡ n)
does-parse₂ = ⟨ (λ x → x) , (λ n → refl) ⟩

-- these don't parse, because they use underscores in binders
doesn't-parse₁ : ∃ ⟦_⟧ ⦂ (ℕ → ℕ) 𝑠𝑡 (∀ n → ⟦ n ⟧ ≡ n)
doesn't-parse₁ = {!!}

doesn't-parse₂ : ∃ _+_ ⦂ (ℕ → ℕ) 𝑠𝑡 (Zero + Zero) ≡ Zero
doesn't-parse₂ = {!!}
```

**Comment by andreasabel** [comment]
@nad Could you please have a look at this?

**Comment by nad** [comment]
Bisection points to the following commit (95d4470c4ce1f00f7425a3faf045876eed74105d): "[ Issue 1109, Issue 1436 ] New default precedence level: unrelated."

**Comment by UlfNorell** [comment]
Didn't we roll back that one?

**Comment by nad** [comment]
The current problem is unrelated to that commit, but rather related to the way we parse sections (by splitting up names with multiple name parts). This should be straightforward to fix.

**Comment by nad** [comment]
I've partially fixed this issue. If a suitable fixity is declared for `_≡_`, then David's code parses.

I'm aware of one remaining regression, see the commit comment above. I think I prefer the new behaviour to the old one, so I'm leaning towards not fixing this regression. Are there any objections to this?
