### ISSUE TITLE
Instance resolution slow in presence of implicit arguments

### ISSUE THREAD

**Issue by mjustus** [agda/agda#1952]
Trying out the new 2.5.1 release, I have hit a performance regression related to, I believe, instance resolution. The slow-down is caused by the last line in the following test case

``` agda
    module Slow where

      record Structure : Set1 where
        infixl 20 _×_
        infix   8 _⟶_
        infixl 20 _,_
        infixr 40 _∘_

        infix 5 _~_

        field
          Type : Set
          _×_  : Type → Type → Type

          _⟶_ : Type → Type → Set
          _∘_ : ∀ {X Y Z} → Y ⟶ Z → X ⟶ Y → X ⟶ Z
          _,_ : ∀ {X A B} → X ⟶ A → X ⟶ B → X ⟶ A × B
          π₁  : ∀ {A B} → A × B ⟶ A
          π₂  : ∀ {A B} → A × B ⟶ B
          Op3 : ∀ {X} → X × X × X ⟶ X

          _~_ : ∀ {X Y} → X ⟶ Y → X ⟶ Y → Set

      record Map {{C : Structure}} {{D : Structure}} : Set1 where
        open Structure {{...}}
        field
          Ty⟦_⟧ : Structure.Type C → Structure.Type D
          Tm⟦_⟧ : ∀ {X A} → X ⟶ A → Ty⟦ X ⟧ ⟶ Ty⟦ A ⟧

          ×-inv : ∀ {X A} → Ty⟦ X ⟧ × Ty⟦ A ⟧ ⟶ Ty⟦ X × A ⟧

          ⟦Op3⟧ : ∀ {X} → Tm⟦ Op3 {X = X} ⟧ ∘ ×-inv ∘ (×-inv ∘ (π₁ ∘ π₁ , π₂ ∘ π₁) , π₂) ~ Op3
```

The time needed to process the file measured via

```
agda -i . -vprofile:10 --ignore-interfaces Slow.agda
```

jumps from less than one second in 2.4.2.6 (latest commit in branch `maint-2.4`) to roughly 6 minutes in the 2.5.1 release. See the table below for detailed timings.

In this particular case, adding a type annotation in the right place

```
⟦Op3⟧ : ∀ {X} → Tm⟦ Op3 {X = X} ⟧ ∘ ×-inv ∘ (×-inv ∘ (π₁ {A = Ty⟦ X ⟧} ∘ π₁ , π₂ ∘ π₁) , π₂) ~ Op3
```

or providing an explicit instance

```
⟦Op3⟧ : ∀ {X} → Tm⟦ Op3 {X = X} ⟧ ∘ ×-inv ∘ (×-inv ∘ (Structure.π₁ D ∘ π₁ , π₂ ∘ π₁) , π₂) ~ Op3
```

dramatically speeds up type-checking.

```
Category                   | base (2.4.2.6) | base (2.5.1) | annotated  | explicit instance
---|--:|--:|--:|--:
Total                      | 320ms | 364,176ms | 1,652ms | 1,488ms
Parsing                    |   4ms |       8ms |    12ms |     8ms
Parsing.Operators          |   8ms |       0ms |    16ms |     8ms
Import                     |   0ms |       0ms |     0ms |     0ms
Deserialization            |   0ms |       0ms |     0ms |     0ms
Scoping                    |  12ms |      12ms |     4ms |     4ms
Scoping.InverseScopeLookup |   0ms |  23,196ms |    48ms |    80ms
Typing                     | 188ms | 279,652ms | 1,276ms | 1,116ms
Typing.OccursCheck         |  20ms |  61,236ms |   216ms |   196ms
Termination                |   0ms |       0ms |     0ms |     0ms
Positivity                 |   0ms |       0ms |     4ms |     8ms
Injectivity                |   0ms |       0ms |     0ms |     0ms
ProjectionLikeness         |   0ms |       0ms |     0ms |     0ms
Highlighting               |   0ms |      12ms |     8ms |     4ms
Serialization              |  56ms |      28ms |    36ms |    28ms
Serialization.Sort         |   0ms |       0ms |     0ms |     0ms
Serialization.BinaryEncode |   8ms |       8ms |    12ms |    12ms
Serialization.Compress     |   0ms |       0ms |     0ms |     0ms
DeadCode                   |       |      12ms |     4ms |     4ms
ModuleName                 |  24ms |      12ms |    16ms |    20ms
```

**Comment by mjustus** [comment]
I did some detective work with `git bisect`. The majority of the additional time spent on type-checking appears to be due to commit 85716a62899fd032073240f2915923b130adfb3a. I re-ran the test case from above using a recent, unmodified copy of master (db021bec38daafa3c95f4c6325592b18cc3ffa1d) and the same version but with commit 85716a62899fd032073240f2915923b130adfb3a manually reverted:

|  | db021bec38daafa3c95f4c6325592b18cc3ffa1d | db021bec38daafa3c95f4c6325592b18cc3ffa1d without 85716a62899fd032073240f2915923b130adfb3a |
| :-- | --: | --: |
| Total | 365,204ms | 30,572ms |
| Parsing | 0ms | 0ms |
| Parsing.Operators | 8ms | 12ms |
| Import | 0ms | 0ms |
| Deserialization | 0ms | 0ms |
| Scoping | 12ms | 12ms |
| Scoping.InverseScopeLookup | 22,648ms | 1,792ms |
| Typing | 281,220ms | 23,132ms |
| Typing.OccursCheck | 61,264ms | 5,584ms |
| Termination | 0ms | 0ms |
| Positivity | 0ms | 0ms |
| Injectivity | 0ms | 0ms |
| ProjectionLikeness | 0ms | 0ms |
| Highlighting | 4ms | 0ms |
| Serialization | 24ms | 28ms |
| Serialization.BuildInterface | 4ms | 4ms |
| Serialization.Sort | 0ms | 0ms |
| Serialization.BinaryEncode | 8ms | 4ms |
| Serialization.Compress | 0ms | 0ms |
| DeadCode | 8ms | 4ms |
| ModuleName | 4ms | 0ms |

**Comment by UlfNorell** [comment]
That means that some thinking will be required to fix this. 85716a6 fixes an obvious bug where instance constraints were simply forgotten. It seems clear that we need to be more careful about when we try to solve instance constraints.
