### ISSUE TITLE
Unable to run Lambda.agda

### ISSUE THREAD

**Issue by arey0pushpa** [agda/agda#1956]
I'm following your OPLSS 2015 lectures and have setup things like it should according to the https://github.com/UlfNorell/agda-summer-school.

   Agda2 Include Dirs:
INS DEL Directory: .
INS DEL Directory: /home/mokambo/src/agda/lib/src
INS DEL Directory: /home/mokambo/agda-prelude/src
INS 

Error while type checking showing  : 

/media/mokambo/Pablo Naruda/ORAGON/AGDA/agda-summer-school/lectures/Lambda.agda:8,6-6
/media/mokambo/Pablo Naruda/ORAGON/AGDA/agda-summer-school/lectures/Lambda.agda:8,6: Parse error
import < ERROR >
 Term.Show
open import Lists

...

Why it should it giving parse error  or import error?

**Comment by UlfNorell** [comment]
Please file this issue on the summer school repo instead. Most likely cause is that you are using versions of agda and the summer school code that are incompatible.

**Comment by arey0pushpa** [comment]
Thanks professor. Will do that.
