### ISSUE TITLE
Case splitter produces unreachable clauses

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#1958]
``` agda
open import Common.Prelude

test : Nat → Nat
test zero = 0
test (suc zero) = 1
test (suc n) = {!n!}
-- Splitting on n produces an unreachable clause
-- test (suc zero) = ?
```

**Comment by UlfNorell** [comment]
This isn't a bug per se. The case-splitting warranty is void if you write some cases by hand.

**Comment by andreasabel** [comment]
The situation arises when I already have a completely defined function by pattern matching, but then change the representation of my data-type and may have to do some deeper matching in some cases.

Ideal Agda would only produce code it can parse back in, so this is why I labelled it as bug.  But fair enough, could rather be seen as enhancement.

**Comment by jespercockx** [comment]
I'll take a shot at fixing/enhancing this.
