### ISSUE TITLE
The GHC backend should not generate (as many) unused imports

### ISSUE THREAD

**Issue by WolframKahl** [agda/agda#1961]
Currently, the GHC backend generates many unused imports: In the 367 Haskell modules (including many from the standard library) my running example compiles to, there are 3904 unused import warnings when calling GHC with `-fwarn-unused-imports`, referring to 194 different modules, both from the standard library and built-ins, and from my application.

**Comment by WolframKahl** [comment]
From a black-box perspective, this is an enhancement suggestion. From a white-box perspective, I see that the mechanism for dealing with this is already there, “the `xqual` trick” in `Agda.Compiler.MAlonzo.Compiler.Misc`, but it is not being trusted.

The following patch improves the situation considerably:

```
diff --git a/src/full/Agda/Compiler/MAlonzo/Compiler.hs b/src/full/Agda/Compiler/MAlonzo/Compiler.hs
index 7e5eb79..2bc2bc6 100644
--- a/src/full/Agda/Compiler/MAlonzo/Compiler.hs
+++ b/src/full/Agda/Compiler/MAlonzo/Compiler.hs
@@ -127,14 +127,14 @@ imports = (++) <$> hsImps <*> imps where

   imps :: TCM [HS.ImportDecl]
   imps = List.map decl . uniq <$>
-           ((++) <$> importsForPrim <*> (List.map mazMod <$> mnames))
+           ({- (++) <$> importsForPrim <*> -} (List.map mazMod <$> mnames))

   decl :: HS.ModuleName -> HS.ImportDecl
   decl m = HS.ImportDecl dummy m True False False Nothing Nothing Nothing

   mnames :: TCM [ModuleName]
-  mnames = (++) <$> (Set.elems <$> use stImportedModules)
-                <*> (List.map fst . iImportedModules <$> curIF)
+  mnames = {- (++) <$> -} (Set.elems <$> use stImportedModules)
+                -- <*> (List.map fst . iImportedModules <$> curIF)

   uniq :: [HS.ModuleName] -> [HS.ModuleName]
   uniq = List.map head . List.group . List.sort
```

The second of these two changes alone, namely just throwing out `iImportedModules curIF`, reduces the redundant imports to 2098, of the following 14 different kinds:

```
 $ grep redundant /var/tmp/kahl/agda/Agda-2.5.1.0.4_1/ghc-log | sort -u
    The import of ‘GHC.Prim’ is redundant
    The import of ‘MAlonzo.RTE’ is redundant
    The import of ‘coe’ from module ‘MAlonzo.RTE’ is redundant
    The import of ‘erased’ from module ‘MAlonzo.RTE’ is redundant
    The qualified import of ‘Control.Exception’ is redundant
    The qualified import of ‘Data.Char’ is redundant
    The qualified import of ‘Data.Text.IO’ is redundant
    The qualified import of ‘Data.Text’ is redundant
    The qualified import of ‘MAlonzo.Code.Agda.Builtin.Char’ is redundant
    The qualified import of ‘MAlonzo.Code.Agda.Builtin.String’ is redundant
    The qualified import of ‘MAlonzo.Code.Agda.Primitive’ is redundant
    The qualified import of ‘MAlonzo.Code.Foreign.Haskell’ is redundant
    The qualified import of ‘MAlonzo.RTE’ is redundant
    The qualified import of ‘System.IO’ is redundant
```

This change also brings the number of modules GHC has to compile down to 324, and thus reduces the executable size by over 3%.

Removing also `importsForPrim` from `imps` further reduces the number of redundant imports to 1772, of the same 14 different kinds of above. I blame `getHaskellImports` in `hsImps` for those, but more work would be required to trim those down precisely ─ if I try to just remove all of  `getHaskellImports`, I get:

```
[...]
[ 12 of 324] Compiling MAlonzo.Code.Data.Sum ( /var/tmp/kahl/agda/Agda-2.5.1.0.4_3/MAlonzo/Code/Data/Sum.hs, /var/tmp/kahl/agda/Agda-2.5.1.0.4_3/MAlonzo/Code/Data/Sum.o )

/var/tmp/kahl/agda/Agda-2.5.1.0.4_3/MAlonzo/Code/Data/Sum.hs:6:1: Warning:
    The qualified import of ‘MAlonzo.Code.Agda.Primitive’ is redundant
      except perhaps to import instances from ‘MAlonzo.Code.Agda.Primitive’
    To import instances alone, use: import MAlonzo.Code.Agda.Primitive()
[ 13 of 324] Compiling MAlonzo.Code.Level ( /var/tmp/kahl/agda/Agda-2.5.1.0.4_3/MAlonzo/Code/Level.hs, /var/tmp/kahl/agda/Agda-2.5.1.0.4_3/MAlonzo/Code/Level.o )

/var/tmp/kahl/agda/Agda-2.5.1.0.4_3/MAlonzo/Code/Level.hs:4:1: Warning:
    The import of ‘erased’ from module ‘MAlonzo.RTE’ is redundant
[ 14 of 324] Compiling MAlonzo.Code.Agda.Builtin.Char ( /var/tmp/kahl/agda/Agda-2.5.1.0.4_3/MAlonzo/Code/Agda/Builtin/Char.hs, /var/tmp/kahl/agda/Agda-2.5.1.0.4_3/MAlonzo/Code/Agda/Builtin/Char.o )

/var/tmp/kahl/agda/Agda-2.5.1.0.4_3/MAlonzo/Code/Agda/Builtin/Char.hs:11:6:
    Not in scope: ‘Data.Char.isLower’

/var/tmp/kahl/agda/Agda-2.5.1.0.4_3/MAlonzo/Code/Agda/Builtin/Char.hs:13:7:
    Not in scope: ‘Data.Char.isDigit’

/var/tmp/kahl/agda/Agda-2.5.1.0.4_3/MAlonzo/Code/Agda/Builtin/Char.hs:15:7:
    Not in scope: ‘Data.Char.isAlpha’

/var/tmp/kahl/agda/Agda-2.5.1.0.4_3/MAlonzo/Code/Agda/Builtin/Char.hs:17:7:
    Not in scope: ‘Data.Char.isSpace’

/var/tmp/kahl/agda/Agda-2.5.1.0.4_3/MAlonzo/Code/Agda/Builtin/Char.hs:19:7:
    Not in scope: ‘Data.Char.isAscii’

/var/tmp/kahl/agda/Agda-2.5.1.0.4_3/MAlonzo/Code/Agda/Builtin/Char.hs:21:7:
    Not in scope: ‘Data.Char.isLatin1’

/var/tmp/kahl/agda/Agda-2.5.1.0.4_3/MAlonzo/Code/Agda/Builtin/Char.hs:23:7:
    Not in scope: ‘Data.Char.isPrint’

/var/tmp/kahl/agda/Agda-2.5.1.0.4_3/MAlonzo/Code/Agda/Builtin/Char.hs:25:7:
    Not in scope: ‘Data.Char.isHexDigit’

/var/tmp/kahl/agda/Agda-2.5.1.0.4_3/MAlonzo/Code/Agda/Builtin/Char.hs:27:7:
    Not in scope: ‘Data.Char.toUpper’

/var/tmp/kahl/agda/Agda-2.5.1.0.4_3/MAlonzo/Code/Agda/Builtin/Char.hs:29:7:
    Not in scope: ‘Data.Char.toLower’
[...]
```

I desist from committing my patch, since I do not know whether you want to keep commented traces of the things I am removing in the code.

**Comment by UlfNorell** [comment]
I would just remove the code. If we need to know what was removed I'm pretty sure git keeps track :).

From a quick glance at the code it looks like the problem with `getHaskellImports` is that they are inherited from imported modules. I'm not sure why we would need that. You could try to remove the `stHaskellImports` line from `Agda.Interaction.Imports.addImportedThings`.

**Comment by phile314** [comment]
I'm not sure, but I think the HaskellImports are inherited because of the ffi foreign datatype bindings. I believe we do not re-export Haskell datatypes/constructors used by FFI bindings. E.g.:

<pre>
module A where
{-# HS_IMPORT MY_BOOL_MOD #-}
data Bool : Set where
  ...
{-# COMPILED_DATA Bool MY_HS_BOOL HS_CON_1 HS_CON_2 #-}
</pre>

I guess we do not re-export the HS_\* datatype/constructors in the generated Haskell code for module A. Instead, we import MY_BOOL_MOD in all dependent modules and just use the original Haskell names.

**Comment by UlfNorell** [comment]
Ah, that sounds right. That might be hard to fix, since we don't know which Haskell import exports the constructors.

**Comment by phile314** [comment]
Re-exporting datatypes could also be problematic if there are two FFI bindings in the same Agda module targeting two different Haskell datatypes of the same name. E.g. Data.Maybe and MyModule.Maybe.

**Comment by WolframKahl** [comment]
Sorry, I should have been clearer about that: I actually do not think it is urgent to precisely restrict `getHaskellImports` so that it produces only needed imports. That's why I have the “(as many)” in the issue title ─ getting down to no unused imports may not be worth while.

I think the real question is whether `importsForPrim` can ever produce something that is not produced by `xqual`, to decide whether to implement that change.

In any case, I strongly hope that the removal of `iImportedModules curIF` makes it into master soon: Many imports necessary on the Agda side only end up exporting things of types that are erased by compilation; since these will not be referred to by `xqual`, there is no point importing those modules.

**Comment by UlfNorell** [comment]
> In any case, I strongly hope that the removal of iImportedModules curIF makes it into master soon

I believe you have the power to make that happen.

**Comment by asr** [comment]
> In any case, I strongly hope that the removal of iImportedModules curIF makes it into master soon

I guess you meant 'into stable soon'.

Too late, I saw your pushed your commit only in master. Please, back-port your commit into stable.

**Comment by WolframKahl** [comment]
@asr, how do you want this done? From initial investigation, it looks like one of `git rebase --onto stable` or `git cherry-pick` might be part of it, or possibly `git merge`, but I could not discern what “the right way” to do this backporting might be. I have not yet done anything of this complexity in git, so if you really want me to do it, giving me precise instructions would be safest.

On the other hand, to cite Ulf, “I believe you have the power to make that happen.”, and I would be grateful if you were to do it.

In any case, if my next commit looks like it should be going into stable, how will that work? The file `HACKING` does not mention `stable`, but says:

```
For new features replace maint-$VERSION with master above.
```

So I'd guess that would be `stable-$VERSION` for me.

If my next change is going to be a single commit again (possibly the other two lines of the patch above), is there a way of doing this without a new branch, or should I still follow the procedure in `HACKING` by “generously” creating a new branch for that single two-line commit?

**Comment by WolframKahl** [comment]
By the way, the answer to my previous question

> whether `mportsForPrim` can ever produce something that is not produced by `xqual`

is yes, as `make compiler-test` immediately reveals.

**Comment by asr** [comment]
> I have not yet done anything of this complexity in git, so if you really want me to do it, giving me precise instructions would be safest.

I'm writing the instructions in `HACKING`...

**Comment by asr** [comment]
I pushed the instructions in d37cf03.

**Comment by asr** [comment]
> if my next change is going to be a single commit again (possibly the other two lines of the patch above), is there a way of doing this without a new branch

Yes. Just push your commit in stable and merge stable into master.

**Comment by asr** [comment]
> The file `HACKING` does not mention `stable`

I updated the file `HACKING`. It mentions `stable` now.

**Comment by WolframKahl** [comment]
Thank you, @asr! Done. (Your second change to `HACKING` came right in the middle of the procedure, so now there are probably even more “Merge” messages in `git log` than originally necessary ─ sorry!)

**Comment by WolframKahl** [comment]
To summarise: In `Agda.Compiler.MAlonzo.Compiler.imports`, both `importsForPrim` in

```
   imps :: TCM [HS.ImportDecl]
   imps = List.map decl . uniq <$>
           ((++) <$> importsForPrim <*> (List.map mazMod <$> mnames))
```

and `getHaskellImports` in

```
  hsImps :: TCM [HS.ImportDecl]
  hsImps = ((unqualRTE :) . List.map decl . Set.toList .
            Set.insert mazRTE . Set.map HS.ModuleName) <$>
             getHaskellImports
```

contribute qualified imports that are, at least in some cases, needed, but not produced by the `xqual` trick.

This leaves the following 10 qualified imports that are superfluous in many modules:

```
    The qualified import of ‘Control.Exception’ is redundant
    The qualified import of ‘Data.Char’ is redundant
    The qualified import of ‘Data.Text.IO’ is redundant
    The qualified import of ‘Data.Text’ is redundant
    The qualified import of ‘MAlonzo.Code.Agda.Builtin.Char’ is redundant
    The qualified import of ‘MAlonzo.Code.Agda.Builtin.String’ is redundant
    The qualified import of ‘MAlonzo.Code.Agda.Primitive’ is redundant
    The qualified import of ‘MAlonzo.Code.Foreign.Haskell’ is redundant
    The qualified import of ‘MAlonzo.RTE’ is redundant
    The qualified import of ‘System.IO’ is redundant
```

As such, these have a minor impact on GHC compilation time, but otherwise present no problem.

The removal of `iImportedModules curIF` from `mnames` solved the real problen, namely that unnecessary application (and standard library) modules were included in GHC compilation. I therefore close this issue.

**Comment by asr** [comment]
> Done.

Thanks for cherry-picking your commit into stable-2.5.

> (Your second change to HACKING came right in the middle of the procedure, so now there are probably even more “Merge” messages in git log than originally necessary ─ sorry!)

Since we require stable be a subset of master, sometimes these "collisions" happens. I don't what work-flow we should use for avoiding this situation.

Before pushing, I first merge the local repositories to minimize the risk of "collisions" (among other things).
