### ISSUE TITLE
Agda install 2.6.0

### ISSUE THREAD

**Issue by arey0pushpa** [agda/agda#1962]
While installing agda 2.6.0 : 
1. agda2-include-dirs variable is not present after doing customize-group in emacs how then to change the Agda search path.
1. How to version manage agda . I want to install two versions that i want to work with. One which is developmental and one which is stable is there any way just to switch the one which you want to use while running emacs / command. for example : In javaScript Node.js we use to say $ Package-manager ---use node-1.0.1

Thanks

**Comment by UlfNorell** [comment]
Please send questions like this to the [mailing list](https://lists.chalmers.se/mailman/listinfo/agda). The bug tracker is for reporting bugs and other issues.

That said,
- Since 2.5.1 search paths are managed using the new [library system](http://agda.readthedocs.io/en/latest/tools/package-system.html).
- Managing different versions of Agda could be done setting up some symbolic links and writing a simple script to change what they point to. Someone on the mailing list might have this already set up in Emacs.

**Comment by arey0pushpa** [comment]
I think its become a pain just to start quick. It should not have to be like this.

**Comment by UlfNorell** [comment]
Can you be more specific. Managing multiple versions of Agda isn't required to "start quick". If you don't want to use the library system (although you should because it saves you from the fiddly emacs settings), you can use the `agda2-program-args` instead (and pass `-i PATH`).

**Comment by nad** [comment]
Perhaps you can use `agda2-set-program-version`:

```
agda2-set-program-version is an interactive compiled Lisp function in
`agda2-mode.el'.

It is bound to <menu-bar> <Agda> <Switch to another version of Agda>.
(agda2-set-program-version VERSION)

Tries to switch to Agda version VERSION.

This command assumes that the agda and agda-mode executables for
Agda version VERSION are called agda-VERSION and
agda-mode-VERSION, and that they are located on the PATH. (If
VERSION is empty, then agda and agda-mode are used instead.)
```

**Comment by arey0pushpa** [comment]
Updated version to agda Agda version 2.6.0

Warning (agda2): Note that the variable agda2-include-dirs is
no longer used. You may want to update your configuration. You
have at least two choices:
- Use the library management system.
- Set the include path using agda2-program-args.

One way to avoid seeing this warning is to make sure that
agda2-include-dirs is not bound.

??? what to do now. 

tried from http://wiki.portal.chalmers.se/agda/pmwiki.php?n=Libraries.StandardLibrary

Its not clear  — ?? what's that  a - or -- or nothing ??  

In the development version under git one needs instead to look for the option Agda2 Program Args. Insert for each path element —include-path=path where path is your path. One path element should be the current directory, ., and one should be the location of the standard-library DIR/src.

Thanks

**Comment by UlfNorell** [comment]
In `~/.agda` create two files, `libraries` and `defaults`, with the following content:

```
$ cat libraries
/path/to/agda/stdlib/standard-library.agda-lib
$ cat defaults
standard-library
```

(But replace `/path/to/agda/stdlib` with the actual path to where you have the standard library)

**Comment by arey0pushpa** [comment]
bash: cd: /home/mokambo/.agda: No such file or directory
Installed agda version 2.6.0 from git repo. like stated.  

mokambo 12:50 PM ~/ agda --version 
                                     Agda version 2.6.0

**Comment by UlfNorell** [comment]
`mkdir ~/.agda`?

**Comment by arey0pushpa** [comment]
No use. Same Report / warning in emacs .

Warning (agda2): Note that the variable agda2-include-dirs is
no longer used. You may want to update your configuration. You
have at least two choices:
- Use the library management system.
- Set the include path using agda2-program-args.

One way to avoid seeing this warning is to make sure that
agda2-include-dirs is not bound.

**Comment by arey0pushpa** [comment]
previously there was just problem of compatibility btw the summer agda-lib and version of summer school code.  Now after new agda install things got worse. 

Should i undo the " Agda2 Program Args " : 

It looks like this now

INS DEL String: —include-path=.
INS DEL String: —include-path=/home/mokambo/agda-stdlib-0.12/src
INS DEL String: include-path=/home/mokambo/agda-stdlib-0.12/src
INS DEL String: -include-path=/home/mokambo/agda-stdlib-0.12/src
INS DEL String: --include-path=/home/mokambo/agda-stdlib-0.12/src

Was not sure of wht is -- so did all possible versions.

**Comment by UlfNorell** [comment]
My suggestion was to use the library system to avoid having to mess with include paths (but flags start with double dash, as you can see if you do `agda --help`).

**Comment by arey0pushpa** [comment]
Okay, At least its loading now... Still few prob during compiling .   Now i understand what u have suggested besides changing the include path. Still One issue to run my agda program 

File saved as Babe.agda :

module Babe where
import Level

test : {T : Set} → T → T
test = λ x → x

After compilation :  
    The IO action ‘main’ is not defined in module ‘MAlonzo.Code.Babe’

??? Searching internet does't help as much as it should..

**Comment by UlfNorell** [comment]
You need a main function if you want a runnable program. With `agda-prelude`:

``` agda
open import Prelude

main : IO ⊤
main = putStrLn "Hello World"
```
