### ISSUE TITLE
Implement postfix projections

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#1963]
At AIM XXIII it was strongly suggested to allow projections to be written postfix.

``` agda
module Prod where

  record Σ (A : Set) (B : A → Set) : Set where
    field fst : A
          snd : B fst

  open Σ

  test : ∀{A} → A → Σ A λ _ → A
  test = λ where
    x .fst → x
    x .snd → x
```

(Currently you cannot result-split in an extended lambda, that would be fixed.)

Here is a larger example:

``` agda
module Stream where

  record Stream (A : Set) : Set where
    coinductive
    field head : A
          tail : Stream A

  open Stream

  repeat : ∀{A} (a : A) → Stream A
  repeat a .head = a
  repeat a. tail = repeat a

  zipWith : ∀{A B C} (f : A → B → C) (s : Stream A) (t : Stream B) → Stream C
  zipWith f s t .head = f (s .head) (t .head)
  zipWith f s t .tail = zipWith f (s .tail) (t .tail)

  module Fib (Nat : Set) (zero one : Nat) (plus : Nat → Nat → Nat) where

    {-# TERMINATING #-}
    fib : Stream Nat
    fib .head = zero
    fib .tail .head = one
    fib .tail .tail = zipWith plus fib (fib .tail)
```

**Comment by andreasabel** [comment]
My implementation is now testable, please have a look at branch `postfix-projections`.

**Comment by nad** [comment]
Can you please document the reason for adding postfix projections?

All other applications in Agda are prefix (if you do not use operators or syntax declarations). Why did you decide to use postfix notation for projections? (My guess: Because then the clause starts with the defined symbol.)

Isn't the grammar (more) ambiguous now? How do you distinguish between postfix projections and dot patterns?

**Comment by andreasabel** [comment]
Reasons for postfix projections:
1. Postfix projections (as copatterns) work nicely with extended-lambda notation, prefix projections do not fit there.
2. Postfix projections are prevailing in programming languages (e.g. the whole OO-world, but also Pascal, ML, ...).
3. Postfix projections harmonize with the flow of type information in bidirectional type-checking (and correspond to Agda's internal handling of projections).

I was worried about ambiguity with dot patterns, but it turned out my worries were unfounded, as the type distinguishes the two cases in a non-overlapping way:
1. Dot patterns eliminate a function type.
2. Postfix projection patterns eliminate a record type.

There is no ambiguity, this is why it was so easy to implement.

**Comment by andreasabel** [comment]
Agda should show postfix projections for goal type here:

``` agda
{-# OPTIONS --postfix-projections #-}

record R : Set₁ where
  field
    A : Set

open R {{...}}

postulate
  r : R
  a : A {{ r }}

test : let instance i = r in A
test = {! a !}
```

Currently C-c C-. shows us:

```
Goal: R.A r
Have: R.A r
```

But I'd like to see

```
Goal: r .R.A 
Have: r .R.A 
```

**Comment by andreasabel** [comment]
I think the problem is that `A {{r}}` is a `ProjPrefix` projection, internally `Def r [Proj ProjPrefix A]`, and this is printed as `R.A r`.
(See `Rules.Term.inferHead`).

**Comment by nad** [comment]
Now the prefix dot is used, ambiguously, both for postfix projections and for names that are not in scope. If you want to use the prefix dot for postfix projections, then I suggest that names that are not in scope should be printed in a different way.

**Comment by UlfNorell** [comment]
@andreasabel I think it's fair to say that postfix projections have been implemented, so maybe we can close this issue and open a fresh one for the problem in https://github.com/agda/agda/issues/1963#issuecomment-235687606.

**Comment by andreasabel** [comment]
We could (except that I know this issue number by heart already).  Maybe the remaining problem here is an instance of #2801.
