### ISSUE TITLE
Primitives in types of patterns cause internal error

### ISSUE THREAD

**Issue by Saizan** [agda/agda#1969]
Taking primForce as an example of a primitive that can return a type, the following code causes and internal error:

```
primitive
  primForce : _

test : (A : Set) -> A → primForce A (\ _ → A) → A
test A x y = x
```

```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Rules/LHS.hs:294
```

**Comment by andreasabel** [comment]
The prime force...
I don't even know what `primForce` is good for... :D

**Comment by UlfNorell** [comment]
It's `seq`. With call-by-name compile time evaluation controlling strictness can be quite important. Also run-time of course.
