### ISSUE TITLE
Missing support for GHC 8.0.1

### ISSUE THREAD

**Issue by asr** [agda/agda#1971]
Last edit: 2016-05-21

Known issues:
- Travis test for Haddock fails
- ~~Missing Travis test when building using the `-f uhc` option~~

Issues related to the UHC backend:
- ~~pqueue (see https://github.com/lspitzner/pqueue/issues/2) which is required by uhc-util~~
- ~~uhc-light (see https://github.com/UU-ComputerScience/uhc/issues/71)~~
  
  ~~From https://github.com/UU-ComputerScience/uhc/issues/73#issuecomment-187059603, the support for GHC 8.0.1 by uch-light requires that UHC supports GHC 8.0.1.~~
- ~~uhc-util (see https://github.com/UU-ComputerScience/uhc-util/issues/8) which is required by uhc-light~~

**Comment by nad** [comment]
See also https://github.com/danr/geniplate/issues/5.

**Comment by asr** [comment]
I fixed that geniplate issue in https://github.com/danr/geniplate/pull/4.

**Comment by asr** [comment]
The uhc-util issue https://github.com/UU-ComputerScience/uhc-util/issues/8 was fixed in version 0.1.6.6 and the uhc-light issue https://github.com/UU-ComputerScience/uhc/issues/71 was fixed in version 1.1.9.4. I'm testing the UHC backend with UHC 1.1.9.4.

**Comment by asr** [comment]
The pqueue issue lspitzner/pqueue#2 was fixed in version 1.3.1.1.

**Comment by asr** [comment]
I updated the OP.

**Comment by asr** [comment]
> Travis test for Haddock fails

I filed #1992 for this problem.
