### ISSUE TITLE
Remove support for GHC 7.6.3

### ISSUE THREAD

**Issue by asr** [agda/agda#1972]
Since we are supporting GHC 8.0.1 (with exception of the UHC backend), I'll remove the support for GHC 7.6.3.

**Comment by nad** [comment]
What does this mean? Are you changing Agda so that it does not compile using GHC 7.6.3, or are you no longer testing Agda under GHC 7.6.3?

**Comment by asr** [comment]
The first one.

**Comment by nad** [comment]
I don't see the point of this. I don't think we should go to extra lengths to support old versions of GHC or other dependencies, but spending time actively removing support seems counterproductive to me.

**Comment by andreasabel** [comment]
I tend to agree with Nisse.  Some folks do not update their GHC frequently.  I remember Guillaume Brunerie working with a ghc 7.0 still two years ago or so. 

It would be sufficient to drop support for ghc 7.6 once it causes us extra work.  

Ubuntu 14.04 LTS is still on ghc 7.6, and 16.04 LTS has just been released.  I have not upgraded to 16.04 yet as it is a bit fresh and others might be postponing as well.
  http://packages.ubuntu.com/search?keywords=ghc

If you are eager to remove support for 7.6, maybe a poll would be in order, as we have done in the past, see

  Dec 2014
  [Agda] Poll: maintain support for ghc-7.0 ?! 

  Jun 2015
  [Agda-dev] Removing support for GHC 7.4.2

so people have a chance to object.

@UlfNorell opinion?

**Comment by jmchapman** [comment]
I think we should also keep in mind that Agda gets installed on lab machines/servers at universities. Of course you can install ghc yourself locally but this makes the installation even more complicated.

For reference/example I talked to our IT support here who use ubuntu:
For lab machines they do upgrades in the summer, so will move from 14.04 to 16.04 then, in that sense it is not enough to just support the current LTS as it is not always possible to install it straight away.

Servers are last but they make sure that they get upgraded before support runs out.

I think supporting the ghc that comes with the current LTS is not enough. Supporting the last two would be good (this would work here for labs for example) or ideally supporting each LTS until it expires.

So, I would argue that 7.6 should be supported until for the next 2-3 years.

**Comment by UlfNorell** [comment]
For me It comes down to whether people are still using 7.6. If there are distributions that come with 7.6 we should of course try to support it. Once reasonable people can be expected to have moved to 7.8, actively removing 7.6 support is simplifying the code base quite a bit.

**Comment by nad** [comment]
I can imagine that it can be harder to run `git bisect` if we remove support too aggressively. For instance, when I run `git bisect` I often use a script that removes the version bound for `cpphs`, and I would not want to complicate things even further.

**Comment by jmchapman** [comment]
@UlfNorell: Concretely, at my institution we will still be using 7.6 until the middle of September 2016. I expect that others might be slower than this.

**Comment by asr** [comment]
I thought we are only supporting the last _three_ major versions of GHC. I'll reverse the commits.

**Comment by asr** [comment]
> For instance, when I run `git bisect` I often use a script that removes the version bound for `cpphs`

You can use the `-f -cpphs` cabal option instead in recent versions.

**Comment by asr** [comment]
I reverted the commits.

**Comment by andreasabel** [comment]
Thanks!

**Comment by andreasabel** [comment]
We should keep support for ubuntu 14.04, and I guess this is for ghc 7.6?

Quoting an email conversation with Martin Escardo:


On 28/03/17 14:27, G. Allais wrote:
> Debian stable is still on 7.6 (altough backports make it
> possible to upgrade to 7.10):
>
> https://packages.debian.org/search?keywords=ghc&searchon=names&suite=all&section=all

If it is not much trouble, I would like Agda to run in Ubuntu 14.04, for
several reasons (a machine I use for teaching needs 14.04 as some
software I need is broken in 16.04 (yes, we do teach Agda here), a
lightweight netbook I use for travelling doesn't like 16.04, and I tend
to use Agda for in-flight entertainment  )

Martin


>
> On 28/03/17 14:34, Andreas Abel wrote:
>> Ubuntu 16.04 LTS has ghc-7.10, maybe we can phase out the support of ghc
>> 7.8 as a platform to compile Agda on?!
>>
>> If you wish for support of 7.8 still, please raise your voice and give a
>> reason.
>>
>> Best,
>> Andreas

**Comment by asr** [comment]
> We should keep support for ubuntu 14.04, and I guess this is for ghc 7.6?

Yes, Ubuntu 14.04 has GHC 7.6.3.

**Comment by gallais** [comment]
It looks like [this refactoring](https://github.com/agda/agda/commit/b9cf2f9417e654e33f0e41e819dd3ab4c16262e8) will have to be reverted if we want to keep supporting 7.6: I'm getting [a parse error](https://travis-ci.org/agda/agda/jobs/232510156#L3434) on travis because apparently closed type families were added in 7.8.

**Comment by andreasabel** [comment]
Aha. Ah yes, that would be a pity.  
Not clear what to do.  Save that refactoring for next year when ubuntu 18.04 is out? 
I have no clue how easy it is to install 7.8 on ubuntu 14.04.

**Comment by asr** [comment]
> because apparently closed type families were added in 7.8.

Right, they were added on 7.8.

What about of using the open ones?

**Comment by asr** [comment]
> I have no clue how easy it is to install 7.8 on ubuntu 14.04.

[Here](https://launchpad.net/~hvr/+archive/ubuntu/ghc/) are the GHC backports for Ubuntu including 7.8 and newer.

**Comment by gallais** [comment]
> What about of using the open ones?

I'd guess they are order independent like typeclasses in which case I don't see a way of writing [IsBase](https://github.com/agda/agda/blob/350259501aaa910157e2f92b4a8f2e7677a4a99e/src/full/Agda/Utils/TypeLevel.hs#L77) which is inherently overlapping. :/

**Comment by asr** [comment]
> I'd guess they are order independent like typeclasses in which case I don't see a way of writing [IsBase](https://github.com/agda/agda/blob/350259501aaa910157e2f92b4a8f2e7677a4a99e/src/full/Agda/Utils/TypeLevel.hs#L77) which is inherently overlapping. :/

Right. I couldn't rewrite `isBase` using open type families.

**Comment by asr** [comment]
Right now stable doesn't support GHC 7.6.3, so I guess we will remove the support for this version of GHC in Agda 2.5.3. If so, I suggest to remove GHC 7.6.3 from the code base.

**Comment by andreasabel** [comment]
Good, you bring this up @asr! I think code related to GHC 7.6 can be removed now.  In the CHANGELOG, we could add a reference to the GHC backports to Ubuntu 14.04.

What do the others think?

**Comment by asr** [comment]
In the above commit, I removed the code related to GHC 7.6.3 but I didn't add references to the GHC back-ports.
