### ISSUE TITLE
Type-incorrect instantiated projection accepted in pattern

### ISSUE THREAD

**Issue by nad** [agda/agda#1976]
```agda
postulate
  A B : Set

module M (_ : Set) where

  record R : Set₂ where
    field
      F : Set₁

  open R public

open M A

-- Correctly-rejected : M.R B → Set₁
-- Correctly-rejected = F

incorrectly-accepted : M.R B
F incorrectly-accepted = Set
```

See also #1975.

**Comment by andreasabel** [comment]
In the bidirectional world, a projection does not have any parameters.  Only if you use a projection as a function then it makes sense to assign it a type that fixes its parameters.
I know we are not fully consistent with this view of things, but this is the direction in which I would like to move.  
I hold a similar view on constructors (#1975).  As constructors they are always polymorphic, as functions, they might get a monomorphic type.  Alas, we do not have means to syntactically distinguish a constructor from the function with the same name, so things are muddled up.

**Comment by nad** [comment]
We should at least treat constructors and projections in the same way.

**Comment by andreasabel** [comment]
I am fixing this according to @nad's suggestion.  I added a check for the parameters, similar to the one for constructors.
