### ISSUE TITLE
Out-of-scope operators sometimes included in operator grammar?

### ISSUE THREAD

**Issue by nad** [agda/agda#1977]
Consider the following code:

```agda
module Bug where

module M where

  postulate
    [_] : Set₁ → Set

Foo = [ M.undefined ]
```

Agda correctly rejects this code, but I think the error message is strange:

```
Could not parse the application [ M.undefined ]
Operators used in the grammar:
  [_] (closed operator) [[_] (.../Bug.agda:6,5-8)]
```

Why is `[_]` (claimed to be?) included in the grammar? If `M.undefined` is replaced by `Set`, then the error message is more reasonable:

```
Not in scope:
  [ at .../Bug.agda:8,7-8
```

**Comment by nad** [comment]
The operator `[_]` is only included in the grammar in the qualified form `M.[_]`. I've fixed the problem by printing `M.[_]` instead of `[_]` in the error message. However, one might also want to consider excluding the operator from the grammar, to make grammars smaller and error messages shorter. Currently the operator is included because `flattenScope` includes every name that is qualified by `M`.

**Comment by andreasabel** [comment]
Seems like #8079 properly fixes this issue:
- #8079
