### ISSUE TITLE
Expansion of "~/" in the library listing

### ISSUE THREAD

**Issue by favonia** [agda/agda#1978]
This is a feature request. I think it would be useful to support path expansion `~/` in the listing of `.agda-lib` files.

**Comment by UlfNorell** [comment]
Not sure what you're asking. Environment variables are expanded in `~/.agda/libraries`, which is the only place where there should be any absolute paths.

**Comment by favonia** [comment]
@UlfNorell You are right. I made a mistake. However `~/` is still not expanded. The description and the title are updated.

**Comment by UlfNorell** [comment]
Feel free to submit a PR. For now you can always use `$HOME` instead of `~`.

**Comment by Blaisorblade** [comment]
@favonia I hope it's no problem if I beat you to it. Testing it now, but that commit has a couple thinkos I gotta fix — I need to add support for escaping `~`.

**Comment by favonia** [comment]
@Blaisorblade Thanks for your commit! I haven't found time to dig into the Agda code. At first glance it seems `~` is expanded wherever it appears, but it should only be expanded at the beginning. I was referring to a simplified version of http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_01 where no login names are taken into consideration. (That is, we can only refer to the home directory of the current user.)

**Comment by asr** [comment]
@Blaisorblade please add the 2.5.2 milestone and self-assign this issue.

**Comment by favonia** [comment]
Sorry I was busy this weekend. I didn't test so I remained silent, otherwise it looks good to me. :smiley:
