### ISSUE TITLE
Arguments of rewrite rules don't have to be bound

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#1980]
Currently, it is allowed to declare rewrite rules that have arguments that are not bound by the left-hand side. In particular, by adding an absurd argument this allows the creation of arbitrary rewrite rules without actually having an element of the rewrite relation. For example:

```
{-# OPTIONS --rewriting #-}

open import Agda.Builtin.Bool
open import Agda.Builtin.Equality

{-# BUILTIN REWRITE _≡_ #-}

funny : true ≡ false → true ≡ false
funny x = x

{-# REWRITE funny #-}
```

Maybe we should require that all arguments of the rewrite rule are bound in the left-hand side? Or alternatively, we could require this for explicit arguments only and resolve implicit arguments and instance arguments in the usual way? I'm not really sure.

**Comment by jespercockx** [comment]
It's not possible to call the constraint solver or instance machinery from the ReduceM, so the second option is not really feasible (and we probably shouldn't have reduction depend on the constraint solver anyway). So I'd say we just have to go for the first option: require all variables to be bound by the LHS. I don't think this will break too many things, but I could be wrong...

**Comment by andreasabel** [comment]
I agree, we should only allow relevant bindings (in the sense of lambda-I calculus). This is your option 1.  Option 2 would correspond to conditional rewriting which is a whole new story.

**Comment by jespercockx** [comment]
I have a fix, but this breaks https://github.com/agda/agda/blob/master/test/Succeed/Issue1652-2.agda:

```
module _ (A : Set) where

  postulate
    plus0p :  ∀{x} → (x + zero) ≡ x

  {-# REWRITE plus0p #-}
```

gives `plus0p  is not a legal rewrite rule, since the following variables are not bound by the left hand side:  A`. I guess this is to be expected?

**Comment by jespercockx** [comment]
Now I'm just requiring _all_ variables to be bound in the LHS. Maybe it's enough to do this only for all variables that are used in the definition of the rewrite rule.

**Comment by andreasabel** [comment]
Here is a variant of your example:

``` agda
{-# OPTIONS --rewriting #-}

open import Agda.Builtin.Bool
open import Agda.Builtin.Equality

{-# BUILTIN REWRITE _≡_ #-}

module _ (x : true ≡ false) where
  funny : true ≡ false
  funny = x

{-# REWRITE funny #-}
```

`x` is not ``used in the definition of the rewrite rule'', I suppose?
So to prevent your paradoxical example, probably the strict checking is the safe variant.

**Comment by jespercockx** [comment]
It is used in the body of `funny`, which is what I would check (in addition to checking whether it is used in the RHS, which we do already).

**Comment by andreasabel** [comment]
Ok. Sounds plausible.
