### ISSUE TITLE
Internal error due to new unifier?

### ISSUE THREAD

**Issue by mietek** [agda/agda#1982]
> An internal error has occurred. Please report this as a bug.
> Location of the error: src/full/Agda/TypeChecking/Telescope.hs:71

Here’s a somewhat minimised test case:

``` agda
module TelescopeBug where

data ℕ : Set where
  zero : ℕ
  suc : ℕ → ℕ

data Tm : ℕ → Set where
  UP : ∀ {n} → Tm n → Tm n

!_ : ∀ {n} → Tm n → Tm (suc n)
! UP t = UP (! t)

data Ty : ℕ → Set where
  ⊥ : ∀ {n} → Ty n
  _∶_ : ∀ {n} → Tm n → Ty n → Ty (suc n)

data Cx : Set where
  ∅ : Cx
  _,_ : ∀ {n} → Cx → Ty n → Cx

data _⊇_ : Cx → Cx → Set where
  base : ∅ ⊇ ∅
  weak : ∀ {Γ Γ′ n} {A : Ty n} → Γ′ ⊇ Γ → (Γ′ , A) ⊇ Γ
  lift : ∀ {Γ Γ′ n} {A : Ty n} → Γ′ ⊇ Γ → (Γ′ , A) ⊇ (Γ , A)

data True (Γ : Cx) : ∀ {n} → Ty n → Set where
  up : ∀ {n} {t : Tm n} {A : Ty n} → True Γ (t ∶ A) → True Γ ((! t) ∶ (t ∶ A))

ren-true--pass : ∀ {n Γ Γ′} {A : Ty n} → Γ′ ⊇ Γ → True Γ A → True Γ′ A
ren-true--pass η (up j) = up (ren-true--pass η j)

ren-true--fail : ∀ {Γ Γ′ A} → Γ′ ⊇ Γ → True Γ A → True Γ′ A
ren-true--fail η (up j) = up (ren-true--fail η j)
```

`ren-true--pass` works as intended.  I would have expected to have to declare the type of `A`, but I accidentally tried to typecheck `ren-true--fail`, which triggers the error.

**Comment by andreasabel** [comment]
No internal error raised with Agda 2.4.2.6.

**Comment by andreasabel** [comment]
@jespercockx Could that be due to the new unifier?  With verbosity `tc:30`, one of the last messages of Agda is

```
new unifyState: UnifyState   variable tel:   {Γ : Cx} {Γ′ : Cx}
                                             {A : Ty (suc _100)} (η : Γ′ ⊇ Γ) {n : ℕ} {t : Tm n}
                                             {A = A₁ : Ty n} (j : True Γ (t ∶ A₁))
                             flexible vars:  [7, 6, 5, 3, 2, 1]
                             equation tel:   (z : ℕ) (_ : Ty (suc z))
                             equations:      suc n =?= _100, (! t) ∶ (t ∶ A₁) =?= A
...
term _100 := suc _101
...
preparing to instantiate:  suc _101
```

Then Agda crashes.

**Comment by mietek** [comment]
This was in Agda 2.5.1.

**Comment by andreasabel** [comment]
Indeed, the current version has this problem, but not the last, so I labeled it as "regression".

**Comment by jespercockx** [comment]
This took quite some time to debug, but in the end the problem turned out to be that the result of `getContextTelescope` is not yet fully instantiated, so I had to add a `instantiateFull`. This problem was invisible in the debug output since prettyTCM _does_ instantiate the term before printing. In order to avoid problems like this in the future, I think we should either instantiate all metas in `getContextTelescope` (and possibly other functions as well), or not instantiate metas when printing the term.

**Comment by andreasabel** [comment]
Ah, yes, that is unfortunate.  For the paranoid, you can also add debug messages that simply `show` a `Term`.  These messages should have a verbosity level of >=60 (so that you usually do not have to look at Agda's vomit).

**Comment by andreasabel** [comment]
Thanks for fixing!
To whether `getContextTelescope` should be instantiated or not: One way of deciding this is too look at all current uses of it.  However, in general I would like to move away from `instantiateFull` (expensive?) and rather instantiate on demand only.  Most code sits in the TCM monad and does not rely on metas already instantiated.
