### ISSUE TITLE
Regression with open public

### ISSUE THREAD

**Issue by Blaisorblade** [agda/agda#1985]
Hi! 
Just tried Agda 2.5.1 on my infamous inc-lc/ilc-agda codebase, which you might remember from #1712. This time, I only got _two_ seemingly distinct substitution bugs, and one looks like minimizable. I'm first building stable-2.5 to check if the bug is still there, I'll try minimizing later.

https://github.com/inc-lc/ilc-agda/commit/d43fb2f89ef473dccaa4c9fcc455c8cbc9963bd5

```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Substitute.hs:183
```

Here's the offending Agda code. It seems to be about application to an empty telescope: https://github.com/agda/agda/blob/2.5.1/src/full/Agda/TypeChecking/Substitute.hs#L183

**Comment by Blaisorblade** [comment]
I reproduced this on the `stable-2.5` branch, and minimized this to the following.
My further attempts at minimization fail.

Required ingredients:
- have an `open import SomeModule public` inside a parameterized module `Foo`.
- rename `Foo` to `Bar` (this was originally, IIRC, an `import Foo as Bar`).
- apply `Bar` to a type-correct argument.

The bug can produce errors in different locations, so also #1712 might be a symptom of this issue. That's because it creates different corrupted expressions, depending on the exact shape of the signatures of `SomeModule`; and each kind of corrupted expression triggers an error at a different location.

This sort of pattern appears everywhere in `ilc-agda`, possibly explaining many further bugs.

Bug1985.agda:

``` agda
module Bug1985 where

module Foo (ConstParam : Set) where
  -- the Const parameter is crucial

  -- Now we need a public import:
  open import Agda.Primitive public
  --open import Level public
  {-
  piApply t = El {_getSort = Type (Max []), unEl = Def Agda.Primitive.Level []}
    args = [r(Def Bug1985.Const [])]
  An internal error has occurred. Please report this as a bug.
  Location of the error: src/full/Agda/TypeChecking/Substitute.hs:398
  -}

  -- Data.Unit gives a bigger error:
  --open import Data.Unit public
  {-
  piApply t = El {_getSort = Type (Max []), unEl = Def Relation.Binary.Consequences.Total [Apply r{Level (Max [])},Apply r{Level (Max [])},Apply r{Def Agda.Builtin.Unit.⊤ []},Apply r(Def Data.Unit.Base._≤_ [])]}
    args = [r(Def Bug1985.Const [])]
  An internal error has occurred. Please report this as a bug.
  Location of the error: src/full/Agda/TypeChecking/Substitute.hs:398
  -}

  --open import Data.List.All public
  {-
  An internal error has occurred. Please report this as a bug.
  Location of the error: src/full/Agda/TypeChecking/Substitute.hs:183
  -}

-- Let's define some argument.

data ConstArg : Set where
open Foo ConstArg
--this application works.

module Bar = Foo
-- this renaming step is crucial

open Bar ConstArg
-- applying to Const is where this all explodes
```

EDIT: smaller version — down to 7 lines:

``` agda
module Bug1985 where
module Foo (ConstParam : Set) where
  open import Agda.Primitive public
data ConstArg : Set where
open Foo ConstArg
module Bar = Foo
open Bar ConstArg
```

**Comment by andreasabel** [comment]
Thanks for the test case!  
The external `import` is not needed, also not the final `open`.  Here is another shrinkage:

``` agda
module Issue1985 where

module Def where
  postulate A : Set

module Par (B : Set₁) where
  open Def public

module Ren = Par
module App = Ren Set
```

This is a regression since at least 2.4.2.2.  It works fine with 2.3.2.

**Comment by andreasabel** [comment]
@UlfNorell seems we are not done with the "open public" series of bugs.

**Comment by Blaisorblade** [comment]
@andreasabel 
Thanks for the further shrinkage!

I just confirmed your reduced example also works with 2.4.0.2 and fails with 2.4.2 (if the prebuilt Agdas I have have the correct version). This is consistent with the versions where `ilc-agda` could be ported to, and (IIRC) with the source of the other `open public` bugs.
I'm trying to bisect the bug down to the source.

But to state the obvious (and then I'll let you to this): one should ensure the fix works with multiple variants of `module Def`. To that end, one _could_ require testing with multiple variants... or with imports from the standard library.

Below's the error with 2.4.2:

```
$ ~/Library/Haskell/bin/agda-2.4.2 Issue1985.agda
Checking Issue1985 (/Users/pgiarrusso/AeroFS/Repos/ilc-agda-tatooine/Issue1985.agda).
piApply t = El {getSort = Type (Max [ClosedLevel 1]), unEl = Sort (Type (Max []))}
  args = [[]r(Sort (Type (Max [])))]
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Substitute.hs:337
```

**Comment by Blaisorblade** [comment]
FWIW, I managed to `git bisect` this all the way down to 7d3036bb9640720973f7acf94302babb339dd90c, the original fix mentioned in https://github.com/agda/agda/issues/892#issuecomment-129026286.

**Comment by andreasabel** [comment]
Ah that infamous monster patch.

**Comment by andreasabel** [comment]
`argsToUse` fails to compute the right amount of applications for this example.

``` agda
{-# OPTIONS -v tc.mod.apply:80 #-}

module Issue1985 where

module Def where
  postulate A : Set

module Par (B : Set₁) where
  open Def public

module Works where
  module Ren B = Par B
  module App = Ren Set

module Fails where
  module Ren = Par
  -- Agda expects Ren to contain
  --   A : (B : Set) → Set
  --   A B = Par.A B
  -- but actually it just contains
  --   A : Set
  --   A = Par.A
  module App = Ren Set
```

I don't understand `open public` in parametrized modules, and neither does Agda.

**Comment by UlfNorell** [comment]
Well clearly this is a bug. I think the best (and easiest) solution is to eta expand the application in `Fails`.

**Comment by Blaisorblade** [comment]
Thanks for the fix!
1. Would it be possible to backport it to 2.5.2?
2. FWIW, while all my minimizations work, https://github.com/inc-lc/ilc-agda/commit/d43fb2f89ef473dccaa4c9fcc455c8cbc9963bd5 still crashes on the same line. Message:

```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Substitute.hs:184
```

The offending line is indeed the same as before.

Now:
https://github.com/agda/agda/blob/fc1c191ea0fdf94c082d5647f9d07b0fea55a49e/src/full/Agda/TypeChecking/Substitute.hs#L184
Before:
https://github.com/agda/agda/blob/2.5.1/src/full/Agda/TypeChecking/Substitute.hs#L183

I'll try to minimize this again.

**Comment by UlfNorell** [comment]
The fix is already on `stable-2.5` (2.5.2).

**Comment by Blaisorblade** [comment]
Here's a new minimized (and self-contained) version, done on top of master (fc1c191ea0fdf94c082d5647f9d07b0fea55a49e). It seems I needed two nested parameterized modules, but maybe yet more shrinking elsewhere is possible. I also got a crash on https://github.com/agda/agda/blob/fc1c191ea0fdf94c082d5647f9d07b0fea55a49e/src/full/Agda/TypeChecking/Substitute.hs#L400, though I assume the source of the bug is still elsewhere and probably still with open public.

``` agda
module Issue1985V2 where

-- We use either one of Def1 and Def2, and can remove the other.
module Def1 where
  postulate A : Set

module Def2 where
  data ⊥ : Set where

module Par1 (B : Set₁) where
  module Par2 (C : Set₁) where
    -- We can crash on line 400 or 184.
    --For line 400:
    --open Def1 public
    --open import Level public
    {-
    An internal error has occurred. Please report this as a bug.
    Location of the error: src/full/Agda/TypeChecking/Substitute.hs:400
    -}

    --For line 184:
    --open import Data.List.All public
    open Def2 public
    {-
    An internal error has occurred. Please report this as a bug.
    Location of the error: src/full/Agda/TypeChecking/Substitute.hs:184
    -}
    --open import Data.Nat.Base public
    --open import Relation.Binary.Core public
    --open import Relation.Nullary public
    --open import Data.Empty public

    --Working ones:
    --open import Data.Product public
    --open import Function public

--open Par1.Par2 Set Set --Works, even with fewer arguments

--module Bar = Par1 Set
--open Bar.Par2 --works
--open Bar.Par2 Set --fails, even with the rest disabled.

module Baz = Par1
--open Baz.Par2 -- works
open Baz.Par2 Set -- fails!
--open Baz.Par2 Set Set --fails
```

> The fix is already on stable-2.5 (2.5.2).

Ah sorry, I trusted GitHub which suggested otherwise. Thanks for that too!

**Comment by asr** [comment]
> Ah sorry, I trusted GitHub which suggested otherwise. Thanks for that too!

Where GitHub suggested otherwise?

**Comment by Blaisorblade** [comment]
@asr:
Uh, I was (semi-)wrong, sorry for the noise. Anyway, I was referring to `master` here.

![image](https://cloud.githubusercontent.com/assets/289960/15905863/c3d4b19e-2db6-11e6-835a-dc91b7c3a9a6.png)

I assumed that place list branches containing the commit, but that's not true for commits on the default branch (here `master`): https://help.github.com/articles/commit-branch-and-tag-labels/

**Comment by nad** [comment]
> `module Issue1985V2 where`

I used the new script `agda-bisect` to find the commit that introduced this regression, and it seems to be the same one as before. (Due to build failures the following commits were suggested: 988fae3a26f4f1adb9edc6e1685317888285f789, ac60cf95b19fec2bd38419a6040d3ab7538cc4c6, e9030d7fd094fa9cd0070398ee7bbff8cffb6c4e, 7d3036bb9640720973f7acf94302babb339dd90c.)

**Comment by Blaisorblade** [comment]
@nad Thanks for investigating, makes sense—should you want to re-review that diff, I built back then a splitout version separating the refactorings:
https://github.com/Blaisorblade/agda/commits/topic/refix-892

**Comment by andreasabel** [comment]
Good you fixed this one!
