### ISSUE TITLE
MAlonzo crashes when compiling Agda.Builtin.Equality

### ISSUE THREAD

**Issue by laMudri** [agda/agda#1988]
I'm trying to fix the Hackage-derived `Agda-2.5.1` package for Nix. All of the `.agdai` files need to be built from the `.agda` files in `lib/prim/Agda/`, which I am doing using

```
for f in $out/share/*-ghc-*/Agda-*/lib/prim/Agda/{Primitive.agda,Builtin/*.agda}
do
  $out/bin/agda -c --no-main $f
done
```

where `$out` is a bit like the root directory. This compiles the first few files correctly, but gets stuck at `lib/prim/Agda/Builtin/Equality.agda`, with the following error.

```
Checking Agda.Builtin.Equality (/nix/store/92x448yj14g7lm9xydpp5hlmdh24xkp9-Agda-2.5.1/share/x86_64-linux-ghc-7.10.3/Agda-2.5.1/lib/prim/Agda/Builtin/Equality.agda).
Finished Agda.Builtin.Equality.
Agda.Primitive : no compilation is needed.
Compiling Agda.Builtin.Equality in /nix/store/92x448yj14g7lm9xydpp5hlmdh24xkp9-Agda-2.5.1/share/x86_64-linux-ghc-7.10.3/Agda-2.5.1/lib/prim/Agda/Builtin/Equality.agdai to /nix/store/92x448yj14g7lm9xydpp5hlmdh24xkp9-Agda-2.5.1/share/x86_64-linux-ghc-7.10.3/Agda-2.5.1/lib/prim/MAlonzo/Code/Agda/Builtin/Equality.hs
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/Compiler/MAlonzo/Primitives.hs:96
builder for ‘/nix/store/97ml7dnq11lqf4gvyz1kgqffg8fxarq8-Agda-2.5.1.drv’ failed with exit code 1
error: build of ‘/nix/store/97ml7dnq11lqf4gvyz1kgqffg8fxarq8-Agda-2.5.1.drv’ failed
```

**Comment by andreasabel** [comment]
It looks a bit dangerous to just call `agda` to compile stuff in `Agda-*/lib`.  Are you sure the Agda versions match?

**Comment by UlfNorell** [comment]
That's clearly a bug, but like Andreas I don't quite understand what you are trying to do.

If all you need is the `.agdai` file then you don't need `-c`. Also is there a reason you can't use `Setup.hs` which does create the `.agdai` files when you `cabal install` Agda?

If you really do need the compiled code (.hs and .o) then a workaround is to first type check and then compile:

```
  $out/bin/agda $f
  $out/bin/agda -c --no-main $f
```

**Comment by laMudri** [comment]
The build is done in isolation, so there are no other Agda versions (or `Agda-*/` subdirectories) in sight. The `$out` directory from a previous successful build looks like this (truncated to a level of 4):

```
$ tree -L 4 result
result
├── bin
│   ├── agda
│   ├── agda-ghc-names
│   └── agda-mode
├── lib
│   └── ghc-7.10.3
│       ├── Agda-2.5.1
│       │   ├── Agda
│       │   ├── libHSAgda-2.5.1-LlBacZbtVEdAJn2v2JNyrs.a
│       │   ├── libHSAgda-2.5.1-LlBacZbtVEdAJn2v2JNyrs-ghc7.10.3.so
│       │   ├── Paths_Agda.dyn_hi
│       │   └── Paths_Agda.hi
│       └── package.conf.d
│           └── Agda-2.5.1-1024db4ba7ec4f3a664377a2d13cdf85.conf
├── nix-support
│   └── propagated-native-build-inputs
└── share
    ├── doc
    │   └── x86_64-linux-ghc-7.10.3
    │       └── Agda-2.5.1
    └── x86_64-linux-ghc-7.10.3
        └── Agda-2.5.1
            ├── Agda.css
            ├── agda.sty
            ├── emacs-mode
            ├── lib
            ├── MAlonzo
            ├── postprocess-latex.pl
            └── uhc-agda-base

17 directories, 12 files
```

**Comment by laMudri** [comment]
Ulf, I'll take a look at some of those options. I was taking the approach I was because that's what was done for previous versions. All I need is to have everything built so that I never have to write to the `$out` directory again.

**Comment by laMudri** [comment]
Indeed, checking all of the files before compiling any of them means that everything will compile successfully. It's a workaround, I think, so the issue still stands.

**Comment by asr** [comment]
I could reproduce the issue:

``` agda
{-# OPTIONS --without-K #-}

module Bug where

infix 4 _≡_
data _≡_ {a} {A : Set a} (x : A) : A → Set a where
  instance refl : x ≡ x

{-# BUILTIN EQUALITY _≡_ #-}
{-# BUILTIN REFL refl #-}
```

Works:

```
$ agda --ignore-interfaces Bug.agda && agda -c --no-main Bug.agda
```

Doesn't work:

```
$ agda --ignore-interfaces -c --no-main Bug.agda
Checking Bug (/tmp/Bug.agda).
Finished Bug.
Compiling Agda.Primitive in /home/asr/.cabal/share/x86_64-linux-ghc-8.0.1/Agda-2.5.2/lib/prim/Agda/Primitive.agdai to /tmp/MAlonzo/Code/Agda/Primitive.hs
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/Compiler/MAlonzo/Primitives.hs:96
```

**Comment by asr** [comment]
I fixed the above example.

**Comment by asr** [comment]
I guess there are two issues/questions here: Why the built-ins are removed when creating the interface files and why the built-ins aren't handled by the GHC backend.  I'll have a look at it.
