### ISSUE TITLE
Warning when final arguments of rewrite relation are hidden?

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#1990]
Since we can have a heterogeneous rewrite relation now, you'd think you can use standard heterogeneous equality as the rewrite relation. However, this does not work as expected:

```agda
data _≅_ {ℓ} {A : Set ℓ} (x : A) : {B : Set ℓ} → B → Set where
  refl : x ≅ x

{-# BUILTIN REWRITE _≅_ #-}
```

Adding a rewrite rule of this type rewrites the type B to an element of that type, which is almost certainly not what's intended (though you never know...). Instead, you need the following version:

```agda
data _≅_ {ℓ} {A : Set ℓ} : {B : Set ℓ} → A → B → Set where
  refl : {x : A} → x ≅ x

{-# BUILTIN REWRITE _≅_ #-}
```

Maybe we could give a warning or an error if one or both of the final two arguments of the rewrite relation are hidden?

**Comment by andreasabel** [comment]
An error seems fine for the moment.  We can wait for the complaints if that should be too restrictive.
