### ISSUE TITLE
Travis test for Haddock fails using GHC 8.0.1

### ISSUE THREAD

**Issue by asr** [agda/agda#1992]
Haddock in GHC 8.0.1 requires too much memory so Travis is killing the process.

**Comment by asr** [comment]
The build is working now. Please reopen the issue if necessary.

**Comment by UlfNorell** [comment]
It failed again for me (https://travis-ci.org/agda/agda/jobs/179387692). What did you do to fix it?

**Comment by asr** [comment]
> What did you do to fix it?

Nothing. I did some tests on the weekend and it worked. I reverted the changes.

**Comment by UlfNorell** [comment]
I guess you didn't mean to close the issue with the revert :P

**Comment by UlfNorell** [comment]
Github should really have ignored everything inside Revert "..." when looking for closing tags.
