### ISSUE TITLE
Regression on datatype injectivity on 2.5.1 (?)

### ISSUE THREAD

**Issue by Blaisorblade** [agda/agda#1993]
Are there untracked known issues with HeterogeneousEquality (--with-K) under Agda 2.5.1?

I’m having trouble with code that worked before, and found nothing on the bug-tracker (modulo mentions of a new unifier by @jespercockx).

In particular, it _seems_ a _datatype_ I have is no more considered injective, so I need the blanket  --injective-type-constructors to get previously working code to be accepted.

The issue, luckily, was on a small file. It's mostly a rather boring implementation of STLC with typed De Brujin indices. Original:
https://github.com/Blaisorblade/Agda-playground/blob/master/CaiSeminar/TypedDeBrujin.agda#L184

Cutting out irrelevant stuff (but not minimized):

``` agda
module BugReport1993 where

open import Data.List
open import Relation.Binary.HeterogeneousEquality

data Type : Set where
  Nat : Type
  _⇒_ : (σ : Type) → (τ : Type) → Type

Context : Set
Context = List Type

data Var : Context → Type → Set where
  this : ∀ {Γ τ} → Var (τ ∷ Γ) τ
  that : ∀ {σ Γ τ} → Var Γ τ → Var (σ ∷ Γ) τ

lemma-that-injective-≅ : ∀ {Γ σ₀ σ τ} {x₁ : Var Γ σ} {x₂ : Var Γ τ} → that {σ₀} x₁ ≅ that {σ₀} x₂ → x₁ ≅ x₂
lemma-that-injective-≅ refl = refl
```

Error on the match of `lemma-that-injective-≅`:

```
/Users/pgiarrusso/AeroFS/Repos/agda-playground-bluevelvet/BugReport1993.agda:18,24-28
σ != τ of type Type
when checking that the pattern refl has type that x₁ ≅ that x₂
```

**Comment by jespercockx** [comment]
This is working as intended: previously you could prove injectivity of the `Var` type constructor, now you have to enable `--injective-type-constructors` explicitly. Maybe you want a way to enable injective type constructors only for specific types?

**Comment by jespercockx** [comment]
See also issue #1406. In particular: 

> This change might break developments using heterogeneous equality, as did the fix of issue #292.

**Comment by Blaisorblade** [comment]
I've looked at #1406 and #292, and again at the original thread from 2010 in Chung Kil Hur.

What I know is that my Var type seems much less dangerous than his example or the one in #1406 (parameterized by functions on Set!). And maybe I do want injective type constructors only for specific types.
- Thorsten Altenkirch argued earlier that at least List should be (provable to be) injective...
  https://lists.chalmers.se/pipermail/agda/2010/001531.html
- #292 debated whether to allow proving that Bool ≢ Fin 2, which seems closer to my case (since my variables are gloried deBrujin indexes), especially if variables "don't store their indices" in the intended set-theoretic semantics (ahem, forgive this sloppiness).
  That's incompatible with univalence, but I'm not using that.
- Regardless, shouldn't 
  "This change might break developments using heterogeneous equality, as did the fix of issue #292."
  be mentioned in the changelog?

Also, could the intended behavior be documented? I mean, for all I know maybe my code worked but was misguided. I could even try contributing documentation, but I'm afraid I don't understand well enough the intended behavior.

**Comment by jespercockx** [comment]
Yes, I'm sorry for the short response. You're right that this should definitely be documented somewhere.

>  Thorsten Altenkirch argued earlier that at least List should be (provable to be) injective...
>     https://lists.chalmers.se/pipermail/agda/2010/001531.html

Currently, Agda has no way to detect type constructors that are injective, nor a way to mark specific type constructors as such. So the fact that this example used to work in older versions of Agda was by accident, as it relies on injectivity of `Var`.

> That's incompatible with univalence, but I'm not using that.

I understand, however I believe it is a general goal of Agda to be compatible with all possible extensions of MLTT. 

> Regardless, shouldn't "This change might break developments using heterogeneous equality, as did the fix of issue #292." be mentioned in the changelog?

Yes, I will add something as soon as I think of something sensible to say.

> Also, could the intended behavior be documented? I mean, for all I know maybe my code worked but was misguided. I could even try contributing documentation, but I'm afraid I don't understand well enough the intended behavior.

The intended behaviour is that definitions by pattern matching can _in principle_ be translated to datatype eliminators (plus the K axiom in case `--without-K` is not enabled). This is not the case for your example, unless you rely on the fact that the `Var` type is injective. But currently Agda has no way to detect that.

**Comment by Blaisorblade** [comment]
Thanks for your supportive answer!

> I understand, however I believe it is a general goal of Agda to be compatible with all possible extensions of MLTT.

Makes sense, thanks. If implementable, something that is compatible with LEM but not with univalence would be an interesting option. In case autodetecting types that are injective is hard (as I assume), a "way to enable injective type constructors only for specific types", as you proposed, could be cool.

Regarding possible workarounds (which one might mention in some documentation).

However, it turns out the general workaround is just to always carry around a proof that the indices (σ and τ) are equal — that's how McBride designed HetEq originally. (I'd consider documenting that somewhere, maybe belongs to the Het..Eq module). This is mildly annoying but at least robust.

Detecting injective datatypes automatically would be cool, but I guess hard.

In this piece of code that is best achieved through a custom datatype of variable equality proofs (as in "Hereditary Substitutions for Simple Types, Formalized"), but that seems a bit too clever (and potentially boilerplatey) to work in general.

**Comment by jespercockx** [comment]
I added a new pragma to mark a specific datatype as injective in https://github.com/agda/agda/commit/6e65e6f1c9d029bc361fcf845fa76c183eb621b4

**Comment by Blaisorblade** [comment]
Guessing this can be closed, not sure there's anything else actionable here. Thanks for the help!
