### ISSUE TITLE
Correct names in goal types after multiple renaming imports.

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda#1995]
When importing a module multiple times and renaming the same term,  the goal types involving those terms aren't aware of which renaming to look for. For example:

```
open import Data.Bool renaming (Bool to Bar)
open import Data.Bool renaming (Bool to Foo)

t : Bar
t = {!!}
```

gives the goal  as `?0 : Foo` whereas you'd probably expect it to give `?0 : Bar`.

In the trivial example above it isn't a problem as the type `Bar` and `Foo` are actually identical. However it is a problem when combining the above scenario with parametrised modules. If the module is parametrised then the types `Bar` and `Foo` won't actually be of the same type, and yet it will still ask for something of type `Foo` even though it will only actually accept something of type `Bar`. In much bigger examples this can be _very_ confusing. [Agda 2.5.1]

**Comment by andreasabel** [comment]
With the current architecture, this is hard to fix.  Currently Agda's scope checker translates the concrete name `Bar` into the abstract qualified name (`A.QName`) `Data.Bool.Bool`, which has two concrete names associated to it (`Bar` and `Foo`).  In the internal syntax, only `A.QName`s are present.  Upon printing internal syntax, the "best" concretization of names is chosen.  In this case, the best concretization, in Agda's view, is the last one, which is `Foo`.

**Comment by UlfNorell** [comment]
Do you have a test case for the actual problem? In the scenario with parameterised modules Agda is supposed to pick the right name. For instance,
```agda
module _ where

module M (X : Set) where
  postulate D : Set

postulate
  A B : Set

open M A renaming (D to DA)
open M B renaming (D to DB)

goal₁ : DA
goal₁ = {!!} -- Goal: DA

goal₂ : DB
goal₂ = {!!} -- Goal: DB
```

**Comment by andreasabel** [comment]
Maybe this was an instance of #2067 ?

**Comment by UlfNorell** [comment]
Perhaps. Closing provisionally. Reopen as needed.
