### ISSUE TITLE
Case splitting instantiates implicit function

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#1996]
Case splitting can instantiate variables that have an implicit function type, even though the result is not type-correct. This even happens when a different instantiation would produce a valid result:

```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Equality

test : (x : Nat) (f : {n : Nat} → Nat) → f {0} ≡ x → Nat
test x f p = {!p!}
```

Case splitting on p results in the following:

```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Equality

test : (x : Nat) (f : {n : Nat} → Nat) → f {0} ≡ x → Nat
test f .f refl = ?
```

Error message:

```
f₁ != f of type Nat
when checking that the pattern refl has type f₁ ≡ f
```

**Comment by andreasabel** [comment]
It looks a bit fishy also that Agda chooses `f` as name for pattern `x`.

**Comment by jespercockx** [comment]
It seems that the case splitter was producing the correct pattern, but it gets mangled up by the `shuffleDots` function in InternalToAbstract. I'm wondering if we actually need this function, if I just remove it then this test goes through fine. However, it causes some problems in the test cases for issues #800 and #811. I'm investigating further...

**Comment by andreasabel** [comment]
Thanks!
