### ISSUE TITLE
Confused error message when incorrectly duplicating a rewrite rule

### ISSUE THREAD

**Issue by asr** [agda/agda#1997]
By incorrectly duplicate `{-# REWRITE plus0 #-}`, I got the confused error message below:

``` agda
{-# OPTIONS --rewriting #-}

infix  4 _≡_
infixl 6 _+_

data _≡_ {a} {A : Set a} (x : A) : A → Set a where
  refl : x ≡ x

{-# BUILTIN REWRITE _≡_ #-}

cong : ∀ {a b} {A : Set a} {B : Set b}
       (f : A → B) {x y} → x ≡ y → f x ≡ f y
cong f refl = refl

data ℕ : Set where
  zero : ℕ
  suc  : (n : ℕ) → ℕ

_+_ : ℕ → ℕ → ℕ
zero  + m = m
suc n + m = suc (n + m)

plus0 : (x : ℕ ) → x + zero ≡ x
plus0 zero    = refl
plus0 (suc x) = cong suc (plus0 x)

{-# REWRITE plus0 #-}
{-# REWRITE plus0 #-}

-- Error message:

-- Bug.agda:28,1-22
-- plus0  is not a legal rewrite rule, since the left-hand side
-- x + zero  reduces to  x
-- when checking the pragma REWRITE plus0
```

**Comment by jespercockx** [comment]
What's confusing about the error message? Once you've added the rule the first time, the left-hand side is no longer neutral, so you cannot add another rewrite rule with the same type.

**Comment by andreasabel** [comment]
I guess in case the user accidentially adds the same rule twice, we could give a simpler error message, like: "you already added this rewrite rule".  Or we could simply ignore it as redundant pragma.  Probably the former is better (error).

**Comment by asr** [comment]
> I guess in case the user accidentially adds the same rule twice, we could give a simpler error message, like: "you already added this rewrite rule".

+1

**Comment by asr** [comment]
Thanks!
