### ISSUE TITLE
Agda hardly builds out-of-the-box, according to the build matrix

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2000]
http://matrix.hackage.haskell.org/package/Agda

**Comment by asr** [comment]
The latest released version (2.5.1) supports  GHC 7.6.3, 7.8.4 and 7.10.3, so I will remove the labels related to other versions of GHC.

**Comment by asr** [comment]
Recent versions of Alex and Happy don't build with the versions of cabal shipped with GHC 7.6.3 or 7.8.4, so the problem associated to Edison is not a "real" problem. In other words, the user needs a recent version of cabal for installing Agda.
