### ISSUE TITLE
Spaces should separate pathes in library file

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2002]
Often I write in my `.lib` file

```
include: a b
```

and then Agda looks for stuff in directory `a b` instead of in `a` and `b`.
I propose to treat a space as separator here.  Spaces in path names should be escaped.

**Comment by Blaisorblade** [comment]
Makes sense. If one just forbids spaces, the change seems to be just:

``` diff
diff --git a/src/full/Agda/Interaction/Library/Parse.hs b/src/full/Agda/Interaction/Library/Parse.hs
index 1ad97f2..c1bfe2b 100644
--- a/src/full/Agda/Interaction/Library/Parse.hs
+++ b/src/full/Agda/Interaction/Library/Parse.hs
@@ -31,7 +31,7 @@ data Field = forall a. Field
 agdaLibFields :: [Field]
 agdaLibFields =
   [ Field "name"    False parseName                      $ \ name l -> l { libName     = name }
-  , Field "include" True  pure                           $ \ inc  l -> l { libIncludes = inc }
+  , Field "include" True  (pure . concatMap words)       $ \ inc  l -> l { libIncludes = inc }
   , Field "depend"  True  (pure . concatMap splitCommas) $ \ ds   l -> l { libDepends  = ds }
   ]
   where
```

**Comment by Blaisorblade** [comment]
I've committed that it in 4f9c04ad4fc110a4657e7a9f9bec6eb6f1497720, and it appears to work as expected in minimal testing on one testcase. It seems easy enough and I didn't find a testsuite to extend; if you prefer adding a testsuite this would take more time.

**Comment by andreasabel** [comment]
I guess we do not need a testsuite for this.
Thanks a lot!
Is this already on stable and master?

**Comment by Blaisorblade** [comment]
Now it is :-)
