### ISSUE TITLE
Set detection is not a conservative extension of MLTT

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#2003]
When --without-K is enabled, Agda currently tries to detect datatypes that do satisfy K (such as `Nat`) in order to reintroduce the deletion rule on a more limited basis. For example, this ensures that the following code is accepted:

```
{-# OPTIONS --without-K #-}

open import Agda.Builtin.Nat
open import Agda.Builtin.Equality

UIP-Nat : (m n : Nat) → (p q : m ≡ n) → p ≡ q
UIP-Nat m .m refl refl = refl
```

Without this feature, it is still possible to construct UIP by induction on `m`:

```
cong : {A B : Set} (f : A → B) {x y : A} → x ≡ y → f x ≡ f y
cong f refl = refl

UIP-Nat' : (m n : Nat) → (p q : m ≡ n) → p ≡ q
UIP-Nat' zero .0 refl refl = refl
UIP-Nat' (suc m) .(suc m) refl q = step m m (_≡_ refl) (λ e → cong (cong suc) (UIP-Nat' m m refl e)) q
  where
    step : (m n : Nat) (P : suc m ≡ suc n → Set) (p : (e : m ≡ n) → P (cong suc e)) → (e : suc m ≡ suc n) → P e
    step m .m P p refl = p refl
```

This is probably not the nicest way to do it, but at least you can verify that it never uses the deletion rule (= K) by checking the debug output of `-v tc.lhs.unify:50`. However, there is an important difference with the first version: `UIP-Nat m m refl refl` reduces to `refl` for arbitrary neutral terms `m`, while `UIP-Nat' m m refl refl` does not (it only reduces for closed m).

In general, there is no way to construct UIP-Nat from eliminators in a way that satisfies this reduction behaviour. This means that Agda --without-K is not conservative over standart MLTT. On the other hand, I don't see _any_ way in which this could possibly lead to problems, but that does not mean it is impossible.

**Comment by jespercockx** [comment]
A few possible solutions:
- remove the set-detection feature of the unification algorithm
- make definitions like UIP-Nat be _strict_ in their arguments `m` and `n`, i.e. only reduce if these are closed terms
- ignore it and wait until someone finds a way in which this is actually incompatible with some extension of MLTT, then see what we can do to fix that issue

**Comment by andreasabel** [comment]
I would ignore this for now.  So far, the HoTT people have little interest in definitional equality.

**Comment by nad** [comment]
I suggest that set detection should only be enabled if the user asks for it using a flag. Should this flag be safe or unsafe?

**Comment by jespercockx** [comment]
I would probably mark it as unsafe for now, as the computational consequences of it haven't really been grasped yet. We could also allow users to mark specific (data)types as sets themselves with a pragma, e.g. `{-# HSET Nat #-}`.

**Comment by jespercockx** [comment]
I've thought about this some more and come to the conclusion that the feature as it is now is quite ill-conceived, so I've disabled it for now. Hopefully higher-dimensional unification should cover some cases where set-detection was useful. If there is interest in it, I can maybe implement a better version of set detection in the future.

**Comment by favonia** [comment]
Hi, I think I count as a “HoTT” person and I do care about judgmental equality. However, I also understand the hesitation here. It will be great if this is implemented as an option.

**Comment by gallais** [comment]
> Without this feature, it is still possible to construct UIP by induction on m:

Should we, following the coq stdlib, add properties about UIP to agda-stdlib to make it easier for users to prove these? E.g. something like this:

https://gist.github.com/gallais/9f017c51100c63cdc199fe60dc902b82

**Comment by andreasabel** [comment]
> Should we, following the coq stdlib, add properties about UIP to agda-stdlib

Ah, yes, this could go somewhere under Relation/Binary/PropositionalEquality/

**Comment by nad** [comment]
The standard library does not (or at least did not use to) use `--without-K`. However, I would not be surprised if this flag could be enabled in many modules.

**Comment by jespercockx** [comment]
Some time ago, I did an experiment to enable --without-K on the std-lib. Here is a list of the offending functions I found back then:
```
Relation.Binary.HeterogeneousEquality.Core  ≅-to-≡
Relation.Binary.PropositionalEquality       proof-irrelevance
Algebra.RingSolver                          _≟H_
Algebra.RingSolver                          _≟N_
Data.Fin.Properties                         drop-suc
Data.Vec.Equality                           trans
Data.Vec.Equality                           _≟_
Relation.Binary.HeterogeneousEquality       subst
Relation.Binary.HeterogeneousEquality       subst₂
Relation.Binary.HeterogeneousEquality       cong
Relation.Binary.HeterogeneousEquality       cong₂
Relation.Binary.HeterogeneousEquality       proof-irrelevance
Data.Vec.Properties                         ∷-injective
Data.Vec.Properties                         proof-irrelevance-[]=
Data.Vec.Properties                         []≔-minimal
Relation.Binary.Vec.Pointwise               head
Relation.Binary.Vec.Pointwise               tail
Data.Fin.Subset.Properties                  drop-there
Data.Fin.Subset.Properties                  ∉⊥
Data.Fin.Subset.Properties                  x∈⁅y⁆⇔x≡y
Data.Fin.Subset.Properties                  ∪⇔⊎
Data.Fin.Subset.Properties                  orders-equivalent
Data.Fin.Dec                                _∈?_
Data.Colist                                 Any-cong
Data.Colist                                 ⊑-Poset 
Relation.Binary.Sigma.Pointwise             Rel↔≡
Relation.Binary.Sigma.Pointwise             inverse
Data.Container.Indexed                      setoid
Data.Container.Indexed                      natural
Data.Container.Indexed                      ∘-correct
Data.Covec                                  setoid
Data.List.Any.BagAndSetEquality             drop-cons
Data.List.Countdown                         drop-suc
Data.Star.Decoration                        gmapAll
Data.Star.Decoration                        _◅◅◅_ 
Data.Star.Pointer                           lookup
```
Most of them are the ones you'd expect, like heterogeneous equality and proof irrelevance. It definitely seems to be worthwhile to have a (version of the) std-lib that can be used without-K, perhaps with the K-specific functions in separate files.
