### ISSUE TITLE
`DISPLAY` should be more pragmatic

### ISSUE THREAD

**Issue by mietek** [agda/agda#2004]
I’d like to use `Data.List.Any` from the standard library _and_ have readable goals.  I tried the following, but was rebuked:

``` agda
{-# DISPLAY Any (_≡_ x) Y = x ∈ Y #-}
```

> Could not parse the left-hand side `Any (_≡_ x) Y`
> Operators used in the grammar:
>   `None`
> when scope checking the left-hand side `Any (_≡_ x) Y` in the
> definition of `Any`

The only [documentation for `DISPLAY`](https://github.com/agda/agda/blob/ab65a0ad66a23561da35a32c235ff8051940d313/CHANGELOG#L203) says lambdas are not allowed. I’m not sure if `(_≡_ x)` qualifies as a lambda; it seems like a partially-applied defined function to me.

**Comment by andreasabel** [comment]
I like the pun.

I think display forms are probably not allowing nested function symbols. Not even this simple thing works.

``` agda
postulate
  A : Set
  f : A → A
  g : A → A

{-# DISPLAY f (g x) = x #-}
```

The error message is trash, of course.  (If you ask me, the whole feature is ... (censored).)

**Comment by UlfNorell** [comment]
Indeed display pragmas are a little bit limited. The left-hand side of a display pragma is scope checked as a function definition left-hand side, so you can use variables (and wildcards) and constructor patterns.

The main use case is to display specialised calls to overloaded functions using the overloaded names, as you can see in the documentation.

Feel free to suggest a design for (or implement) a better mechanism.

**Comment by andreasabel** [comment]
I bumped into this issue again when I tried to add a DISPLAY rewrite rule for nested projections:
```agda
{-# OPTIONS --postfix-projections #-}

postulate
  A : Set
  P : A → Set

record Eq (a : A) : Set where
  field
    v : A
    p : a ≡ v
open Eq

record S : Set1 where
  field
    u : A
    e : Eq u
  open Eq e public
open S

{-# DISPLAY Eq.v (x .e) = Eq.v x #-}
```
Since display form lhss need not be patterns, I do not understand why they are parsed and scope checked as patterns.

**Comment by jespercockx** [comment]
Putting this in the `icebox` until someone actually comes up with a concrete idea of how DISPLAY should work.

**Comment by andreasabel** [comment]
@mietek The OP should be fixed by:
- #7543
