### ISSUE TITLE
CI main build for GHC 7.8.4 segfaults

### ISSUE THREAD

**Issue by vlopezj** [agda/agda#2013]
The job https://travis-ci.org/agda/agda/jobs/136407817 segfaulted when installing dependencies. All other tasks in [the build](https://travis-ci.org/agda/agda/builds/136407810) seem to work fine.

Strangely enough, my commit https://github.com/agda/agda/compare/e3472d7c1441...b43e3ae21a0d does not touch any files related to Cabal.

~~It might to be related to the zlib issue (https://github.com/agda/agda/issues/1518).~~ Any ideas?

**Comment by asr** [comment]
Just restart the job.

**Comment by andreasabel** [comment]
This can be a coincidence, did it happen persistently or just once.

**Comment by asr** [comment]
This issue and #1518 are not related.

**Comment by UlfNorell** [comment]
This happens about every other run. It's quite annoying.

**Comment by andreasabel** [comment]
Well, it is a free service.  We do not pay, so cannot complain a lot.  Surprisingly, complaining to travis still works sometimes (@asr did so successfully once).

**Comment by asr** [comment]
The job in the OP is running, so I'm closing the issue.

**Comment by vlopezj** [comment]
Both master and stable-2.5 build now without segmentation faults. Thanks for all the help.
