### ISSUE TITLE
Internal error when compiling literate Agda

### ISSUE THREAD

**Issue by radams78** [agda/agda#2019]
Compiling the attached code with agda --latex crashes with the message:

An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/Interaction/Highlighting/LaTeX.hs:495

The problem is somewhere in the last 15 lines.  If the definition of botsub3-Rep\up3, the file compiles.
[Botsub.txt](https://github.com/agda/agda/files/309000/Botsub.txt)

**Comment by andreasabel** [comment]
Thanks for reporting! 
Please provide a self-contained test case, ideally a MWE (minimal working example).

**Comment by andreasabel** [comment]
Actually. I could reproduce the problem.  There must be a non-standard space somewhere in your file, like a non-breaking space (BACKSLASH SPACE) or some other esoteric space, e.g. BACKSLASH SEMICOLON.

**Comment by asr** [comment]
I also could reproduce the example using the [Univalence](https://github.com/radams78/Univalence) repo.

@radams78  the non-standard space is your OP example is in the line 182

```
≡⟨⟨ sub-compSR
```

The space between `≡⟨⟨`and `sub-compSR` is a NARROW NO-BREAK SPACE' (U+202F).

**Comment by asr** [comment]
@andreasabel Did you start to work on this issue? I'm asking because you self-assigned the issue but I also can fix it.

**Comment by andreasabel** [comment]
@asr Please go ahead. I guess a fix would mean to generalize the check against `' '` to a more unicode compatible check near the offending location.
