### ISSUE TITLE
lambda-where crashes on case split in emacs-mode

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2020]
``` agda
open import Common.Bool

test : Bool -> Bool
test = \ where
  b -> ?
```

Splitting `b` fails in the emacs mode with 

```
error in process filter: Search failed: "\\([^!]}\\)\\|;"
```

It gets even better! 
Consider the file extended with some commented out extended lambda, like:

``` agda
open import Common.Bool

extlam-where : Bool → Bool
extlam-where = λ where
  b → {!b!}

-- extlam : Bool → Bool
-- extlam = λ
--   { b → {!b!}
--   }
```

Case splitting `b` will now "succeed", yielding

``` agda
open import Common.Bool

extlam-where : Bool → Bool
extlam-where = λ where
  b → {!b!}

-- extlam : Bool → Bool
-- extlam = λ
--   { false → ? ; true → ? }
```

Yes, your eyes do not fail you: The case splitting happened in the commented out code!!

**Comment by andreasabel** [comment]
@UlfNorell After all one line of code at the AIM breakfast was not enough. Too bad!

**Comment by UlfNorell** [comment]
Ah, I guess it was too good to be true. I'll try to limit the emacs mode patch to a one liner though.

**Comment by andreasabel** [comment]
Maybe I missed something, but this does not seem to work:

``` agda
data Bool : Set where
  true false : Bool

test : Bool → Bool
test x = f x
  where
  f : Bool → Bool
  f = λ where
    x → {!x!}  -- splitting fails

-- I get one of these errors:

-- error in process filter: agda2-make-case-action-extendlam: Search failed: "\\([^!]}\\)\\|;"
-- error in process filter: Search failed: "\\([^!]}\\)\\|;"

-- error in process filter: eval: Beginning of buffer
-- error in process filter: Beginning of buffer
```

I am using
GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.16.6)
 of 2015-09-17 on lgw01-52, modified by Debian

**Comment by UlfNorell** [comment]
That's weird. Works without problems for me:

``` agda
test : Bool → Bool
test x = f x
  where
  f : Bool → Bool
  f = λ where
    true → {!!}
    false → {!!}  -- splitting fails
```

**Comment by UlfNorell** [comment]
@andreasabel: Your example still works for me. Reopen as required.

**Comment by andreasabel** [comment]
Indeed, works now! Thx.
