### ISSUE TITLE
Panic: Unbound name

### ISSUE THREAD

**Issue by mietek** [agda/agda#2024]
> Panic: Unbound name: `Example.Foo` [0,2]@136524753
> when checking that the expression `Foo` has type `Set _0`

``` agda
data Foo : Foo → Set where
```

Admittedly, this is a rather silly thing to do, but there’s no reason to panic.

**Comment by asr** [comment]
The original name `Aczel77.Foo` was more interesting :-)

**Comment by andreasabel** [comment]
Scope checking is done out of order here.
A related problem may be

``` agda
pattern c = c

test : Set → Set
test c = c -- LOOPS
```

which looks non-sensical (and dangerous) to me.

**Comment by andreasabel** [comment]
Continuing the pattern synonym issue on #2027.

**Comment by mietek** [comment]
I’m still on 2.5.1.1.  Is this the same issue?

> Panic: Unbound name: `Panic.Tm` [0,14]@256367450
> when checking that the expression `Tm ? ? ?` has type `Set`

``` agda
module Panic where

data Cx (U : Set) : Set where
  ⌀   : Cx U
  _,_ : Cx U → U → Cx U

data Ty : Set where

-- NOTE: Agda allows the hole to be filled, but fails on next reload.
data Tm : Cx Ty → Cx {!Tm ? ? ?!} → Ty → Set where
```

**Comment by andreasabel** [comment]
Agda 2.5.2 does not allow to fill the hole, it complains about `Tm` not in scope.
