### ISSUE TITLE
Bug fix release 2.5.1.1

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#2026]
We might want to consider a `2.5.1.1` bug fix release. I just fixed a serious performance bug with instance arguments: #1952 and #1998 (and the related #1955 and #2025).

I'll create a `release-2.5.1` branch and cherry pick the relevant commits. Are there any other serious bug fixes we might want to include?

**Comment by UlfNorell** [comment]
> I'll create a release-2.5.1 branch and cherry pick the relevant commits.

Done.

**Comment by asr** [comment]
> Are there any other serious bug fixes we might want to include?

I could mention some _closed_ regressions related to Agda <= 2.4.2.6, but I'll ask a different question. Are there issues stopping us from releasing the current stable-2.5? I have no objections in release the current stable-2.5.

**Comment by UlfNorell** [comment]
There have been quite a lot of new developments on stable. I'd prefer to give them a few weeks of testing before considering a release.

**Comment by asr** [comment]
Our recent final releases were one or two weeks after the release of their RCs. I don't see any problem in releasing a final release a few weeks (or months) after its RC.

Moreover, we can use Hackage [package candidates](http://hackage.haskell.org/packages/candidates/) feature for announcing the RC.

**Comment by UlfNorell** [comment]
The thing is the bug I fixed is really crippling 2.5.1, making instance arguments all but useless in some situations. I'd rather not wait a few months before getting that fix released. If we rush out 2.5.2 it will (likely) contain serious bugs in the new features.

**Comment by mietek** [comment]
Could we also get the new layout syntax for pattern-matching lambdas?

**Comment by UlfNorell** [comment]
No. That will have to wait for the 2.5.2. Also, #2020.

**Comment by UlfNorell** [comment]
> If we rush out 2.5.2 it will (likely) contain serious bugs in the new features.

Not to mention that we have 27 open issues for milestone:2.5.2.

**Comment by UlfNorell** [comment]
> I could mention some closed regressions related to Agda <= 2.4.2.6

Those are exactly the kind of issues I was thinking of.

**Comment by asr** [comment]
The fixed regressions related to Agda <= 2.4.2.6 are #1950, #1951 and #1982.

**Comment by UlfNorell** [comment]
I'll see if I can cherry-pick the fixes to `release-2.5.1`.

**Comment by WolframKahl** [comment]
How about commit a87578f1c874a4b0498fcc2f078db8602d438c12 (which “Removed killRange call”), another performance improvement?

**Comment by Blaisorblade** [comment]
Personally, I'd love the partial fix to #1985 a06c2095c7668a34406c4c7f4c8f4be1ee17af86 to get in, if you agree — though that's a regression from earlier and the fix is not complete, it even changes semantics for working cases, and a new fix might change them again...

I'm using a snapshot either way, so I can also live without that fix in a release for now.

**Comment by UlfNorell** [comment]
Added #1950, #1951, #1982, and a87578f to `release-2.5.1`. The case for #1985 isn't clear-cut so I think it's better to leave that out.

**Comment by WolframKahl** [comment]
The language change
- Projection parameters [Issue #1954]

means that, for now, I won't be able to test master or even stable as long as I want to be compatible with a released version...

Is there already a timing goal or estimate for 2.5.2?

**Comment by UlfNorell** [comment]
Nothing concrete, but hopefully not too long after summer.

**Comment by UlfNorell** [comment]
Added fix to #1967 to `2.5.1.1`.

**Comment by UlfNorell** [comment]
And #1974.

**Comment by asr** [comment]
> There have been quite a lot of new developments on stable. I'd prefer to give them a few weeks of testing before considering a release. 

It seems then that stable is not really stable (whatever it means). We are approaching in the stable branch to a situation similar to the one before 2.5.1, where it was difficult to release from the master branch because is was too experimental.

**Comment by UlfNorell** [comment]
I wouldn't say that. It's reasonably stable, but not so stable that I'd be comfortable releasing it at the drop of a hat. There aren't any experimental features on it that are not suitable for release, it's just that we put a lot of new features on it very recently so now is the best time to release.

You can't have both _"always ready to release"_ and _"has new features"_. Any new features, however stable, will need a short time to settle.

If you really want to release `2.5.2` during the summer I guess that would be fine. I'd like to get a release candidate (if not the release) for `2.5.1.1` out this week though.

**Comment by Blaisorblade** [comment]
> You can't have both "always ready to release" and "has new features". Any new features, however stable, will need a short time to settle.

I don't mean to "well, actually" you (OK, I am), but that's not entirely true, if you have (quite) some resources to invest (but no, I'm not volunteering those :-) ). You _can_ do (much) better. The idea behind continuous integration and TDD is that it is worthwhile to do exactly that. But since I'm sure you don't want to spend your lives on testing, maybe you want to look more at _fuzzing_ — which helps testing new features without requiring massive work on writing testcases.

Of course it's not _easy_, but quite some research suggests it can be _feasible_.

A bit more concretely: I do believe that clever use of fuzz-testing could _both_  produce research papers _and_ generate this testcase https://github.com/agda/agda/issues/1985#issuecomment-220246037. It has 6 distinct identifiers and no fancy types.
I'm aware that src/full/Agda/TypeChecking/Test/Generators.hs and src/full/Agda/TypeChecking/Tests.hs exist.

I believe this could be novel enough for a paper: [a 2015 paper](https://www.cs.ucsb.edu/~benh/research/papers/dewey15fuzzing.pdf) boasts generating well-typed terms for testing Rust's typechecker; you already have Agsy for that! 
Searching for related work found a few more papers I could post, including from [Dybjer](http://www.cse.chalmers.se/~peterd/papers/testingproving.html) in your team, but not applied to Agda itself but to programs in Agda). Since Agda is an especially agile proof assistant and doesn't have a small core (compared with Coq), I think randomized testing would be especially relevant.

Further relevant links include http://dl.acm.org/citation.cfm?id=2103691 (POPL'12) and http://www.cs.utah.edu/~regehr/papers/pldi11-preprint.pdf (PLDI'11).

**Comment by mietek** [comment]
This seems off-topic, so I’ll be brief. [afl](http://lcamtuf.coredump.cx/afl/) is a great example of the practical application of fuzzing in the industry.

**Comment by UlfNorell** [comment]
Random testing might work quite well to catch internal errors in the module system, but it would be a non-trivial research project to generate random programs that would have any chance of hitting the interesting corners of type checking or unification. Not to mention that many (most) bugs are of the form "_This should type check but doesn't_" or "_This shouldn't type check_" which would require a formal specification to test for.

Anyway, I still think there's a need for bug fix releases even if we could release `2.5.2` today. As @WolframKahl mentions `2.5.1` and `2.5.2` are not compatible and some people might prefer to stay on `2.5.1` for a while.

**Comment by UlfNorell** [comment]
Added #2034.

Once the Travis job completes I'll start the release procedure.

**Comment by asr** [comment]
There are guides for the releases process (master/stable and RC/final) in the notes directory.

**Comment by UlfNorell** [comment]
Yeah, I found them. Since it's just a few bug fixes I was thinking we could skip the release candidate and go straight for hackage.

**Comment by asr** [comment]
I disagree in skipping the RC.

**Comment by asr** [comment]
I could build both 2.5.1 and 2.5.1.1 with GHC 8.0.1.

**Comment by asr** [comment]
I found the following error on a fresh release-2.5.1 branch:

```
$ make test
fix-agda-whitespace --check
Whitespace violation detected in .../doc/user-manual/language/coinduction.rst.
Whitespace violation detected in .../doc/user-manual/language/data-types.rst.
Whitespace violation detected in .../doc/user-manual/language/rewriting.rst.
```

**Comment by UlfNorell** [comment]
> I disagree in skipping the RC.

Fair enough.

> I found the following error on a fresh release-2.5.1 branch:
> `...Whitespace violation...`

That's weird. I don't:

```
$ git clone --single-branch --branch release-2.5.1 git@github.com:agda/agda tmp
Cloning into 'tmp'...
Checking connectivity... done.
$ cd tmp
$ fix-agda-whitespace --check
$
```

**Comment by asr** [comment]
I guess we are using different "versions" of `fix-agda-whitesapace`.

**Comment by asr** [comment]
The latest commit (https://github.com/agda/agda/commit/56c46b34ada7e3bde0a4a4eaa166aee12de7a12e) modifying `FixWhitespace.hs` added the .rst files.

**Comment by UlfNorell** [comment]
Right. Since it works with the `fix-agda-whitespace` that's actually in the `2.5.1.1` release I see no reason to take action.

**Comment by asr** [comment]
I agree.

**Comment by asr** [comment]
I saw you pushed https://github.com/agda/agda/commit/7b0da97a53b2ef5e3799565a07b56285c1242f03. Are you planning to add the "new" support for GHC 8.0.1 in the CHANGELOG?

**Comment by UlfNorell** [comment]
I hadn't crossed my mind, do we usually do that?

I announced the release candidate, so I'll guess we'll give it a few days before pushing it to Hackage.

**Comment by asr** [comment]
> do we usually do that?

Yes.

**Comment by UlfNorell** [comment]
Ok, fixing...

Done (a927b9c74a89d35037295d3287052d8724206338).

**Comment by UlfNorell** [comment]
RC tested with
- Mac OS X (10.10) and ghc 7.6.3, 7.8.3, 7.10.3, and 8.0.1
- Windows 10 and ghc 7.10.3.

**Comment by asr** [comment]
Also tested on Ubuntu 12.04 and GHC 7.10.3, 7.8.4 and 7.6.3 via Travis.

**Comment by asr** [comment]
I just run the test-suite without problems using GHC 8.0.1. I will add this version of GHC to Travis.

**Comment by UlfNorell** [comment]
You'll need to revert c00995d0bc (remove test-suite from cabal file) to get the Travis build to pass again.

**Comment by asr** [comment]
Please do it. I'm fixing hTags with GHC 8.0.1 on this branch.

**Comment by UlfNorell** [comment]
Ok, done. I cancelled your Travis job.

**Comment by asr** [comment]
Thanks!

**Comment by asr** [comment]
The Travis tests using GHC 8.0.1 are running.

**Comment by UlfNorell** [comment]
Since no one has complained about the RC I guess we can go ahead and release. @asr, do you want me to do it or will you?

**Comment by asr** [comment]
I'll make the release.

**Comment by asr** [comment]
> RC tested with
> - Mac OS X (10.10) and ghc 7.6.3, 7.8.3, 7.10.3, and 8.0.1
> - Windows 10 and ghc 7.10.3.

Could someone test the installation of the RC on Windows and GHC 8.0.1.

**Comment by Blaisorblade** [comment]
Just noticed stack support is not in, and I guess it's too late for that, right?

I just checked that Agda does build with the same stack file as `stable-2.5`, but I assume this is not enough testing, so this should better wait for 2.5.2.

**Comment by asr** [comment]
> Just noticed stack support is not in, and I guess it's too late for that, right?

Right.

**Comment by Blaisorblade** [comment]
Just noticed that the `release-2.5.1` branch has both `CHANGELOG` and a dummy `doc/release-notes/2-5-2.txt`: https://github.com/agda/agda/blob/f1c9c33643316d899d94c91674a2eb8955d90a72/doc/release-notes/2-5-2.txt

**Comment by asr** [comment]
We are using a _new_ work-flow for releasing 2.5.1.1, i.e. we will release from a branch which won't be merged into stable/master after the release.  @UlfNorell it was your plan, right?

**Comment by asr** [comment]
> Just noticed that the `release-2.5.1` branch has both `CHANGELOG` and a dummy `doc/release-notes/2-5-2.txt`: https://github.com/agda/agda/blob/f1c9c33643316d899d94c91674a2eb8955d90a72/doc/release-notes/2-5-2.txt

After releasing 2.5.1 the version in stable was 2.5.1.1, so I created that file. Since we are realising  from the 2.5.1 tag, I will keep that file.

**Comment by Blaisorblade** [comment]
@asr I'm confused. Why should a user see release notes for 2.5.2 in the 2.5.1.1 release? I only see the old workflow would make it a bit harder to remove the file, not impossible.

Separately, I'm also confused why there's both CHANGELOG and release-notes, and how they're kept in line — I guess the 2.5.1.1 release notes should later be reflected in the `CHANGELOG` in `stable-2.5` and `master`, right? Is that done by hand?

**Comment by asr** [comment]
> Why should a user see release notes for 2.5.2 in the 2.5.1.1 release?

These release notes aren't included in the tarball released on Hackage.

**Comment by asr** [comment]
> I'm also confused why there's both CHANGELOG and release-notes

We use the release-notes for future versions and the CHANGELOG for the version that will be released.

**Comment by asr** [comment]
> I guess the 2.5.1.1 release notes should later be reflected in the `CHANGELOG` in `stable-2.5` and `master`, right?

Right.

Right now the CHANGELOGs in `stable` and `master` should be synchronised respect to the `CHANGELOG` in `release-2.5.1`.

> Is that done by hand?

Yes (on this new work-flow)

**Comment by UlfNorell** [comment]
> we will release from a branch which won't be merged into stable/master after the release

Correct.

**Comment by UlfNorell** [comment]
> Could someone test the installation of the RC on Windows and GHC 8.0.1.

Done.

**Comment by asr** [comment]
FYI, I removed the 2.5.1.1-candidates milestone.

**Comment by asr** [comment]
The release was done.

**Comment by UlfNorell** [comment]
Thanks!

**Comment by asr** [comment]
@UlfNorell did you use the Haskell Platform for testing the installation with Windows and GHC 8.0.1?

**Comment by UlfNorell** [comment]
No, I didn't know they had a platform out already. I just got the ghc binary distribution. I checked, and `old-time` did install no problems for me.
