### ISSUE TITLE
Free variables in pattern synonym (WAS: Recursive pattern synonym)

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2027]
``` agda
pattern c = c

test : Set → Set
test c = c -- LOOPS
```

**Comment by andreasabel** [comment]
At least I removed the loop.  But still this is accepted probably because `c` becomes a variable.

**Comment by UlfNorell** [comment]
It would not be unreasonable to require variables in pattern synonyms to be bound by the left-hand side. Here's a quiz:

``` agda
open import Agda.Builtin.Nat

pattern hm = x

quiz₁ : Nat → Nat → Nat
quiz₁ hm hm = hm

quiz₂ : Nat → Nat
quiz₂ x = hm

quiz₃ : Nat → Nat
quiz₃ hm = x
```

**Comment by andreasabel** [comment]
Indeed, I was thinking along the same lines, so I opened this issue.  Where is the original discussion about pattern synonyms?  I wonder what the original designers had in mind by allowing free variables on the rhs...

Seems like the free variable issue was never discussed in the original proposal at #495.

**Comment by UlfNorell** [comment]
My best guess is that it's an oversight.

**Comment by andreasabel** [comment]
What currently is happening for a pattern synonym

``` agda
pattern s xs = p
```

is that first `p` is scope-checked, adding binding for all free names in `p` as pattern variables.  Then the variables `xs` are checked in this scope.  An unbound variable here is an error `Unused variable in pattern synonym`.  

The other direction is never checked.  I wonder if this is a feature in combination with hidden arguments or dot patterns?

**Comment by andreasabel** [comment]
Now the pattern variables of lhs and rhs of a pattern synonym declaration have to match exactly (no unbound variables in either direction).
