### ISSUE TITLE
.travis.yml don't use pre-built versions of Alex or Happy

### ISSUE THREAD

**Issue by Blaisorblade** [agda/agda#2029]
Starting from 22df2d6c952b97fd95725f9feb60e8d0c56de88c, `.travis.yml` installs old cabal-install versions using `multi-ghc-travis`, then runs `cabal install cabal-install`. It looks odd and I don't get why — @asr, do we need to keep this?

Finally, compiling `cabal-install` takes precious time on Travis — the same holds for `alex` and `happy` BTW. For all these tools, we should be able to use precompiled versions from hvr's PPA.

**Comment by asr** [comment]
There were some problems using some versions of Cabal with recent versions of Alex and Happy (see for example [this](http://stackoverflow.com/questions/25104367/ghc-incompatibility-installing-haskell-src-exts-via-cabal/25138529#25138529)  question/answer) some time ago. I don't know if install the latest version of Cabal is currently necessary.

Which was the Travis output for https://github.com/Blaisorblade/agda/commit/e38429f9ff3bdda5a3b5cafdf3cada21369a1696 and https://github.com/Blaisorblade/agda/commit/cf616ae6a7edbb20a39bdb847ee2014f5663fc46 ?

**Comment by Blaisorblade** [comment]
Those are both still building on Travis (actually, they haven't yet started, I seem to have flooded Travis). In particular, 
https://github.com/Blaisorblade/agda/pull/3 maps to https://travis-ci.org/Blaisorblade/agda/builds/136984930 and https://github.com/Blaisorblade/agda/pull/4 maps to https://travis-ci.org/Blaisorblade/agda/builds/136987701.

I see why those links recommend the newest Happy and Alex — in those branches I've picked the earliest versions allowed by the bounds and available, and I had tested them locally with GHC 7.6.3; alternatively, one could use `HAPPYVER` and `ALEXVER` to pick appropriate versions (I've just seen an example in http://docs.haskellstack.org/en/latest/GUIDE/#travis-with-caching), or just pick the latest ones everywhere. (I'm unaware of problems after https://ro-che.info/articles/2014-03-08-happy-alex-ghc-7.8.html).

Either way the issue doesn't seem to be current. And since those bugs come from the tools themselves, not from Agda, testing the tools on each commit might be a suboptimal tradeoff (given the slow Travis turnaround).

BTW, from the PR I have a link and it should be visible for you too — if not I can investigate. (I created PRs in my repos to avoid notifying you till I get enough testing done, I don't want to flood you with silly experiments).

**Comment by asr** [comment]
Please push these commits if the Travis builds are successful.

> BTW, from the PR I have a link and it should be visible for you too.

I saw it.

**Comment by Blaisorblade** [comment]
Using Alex and Happy was not a problem.

But the build fails with GHC 7.6.3 and cabal-install 1.18: https://travis-ci.org/Blaisorblade/agda/jobs/136982131
The failure is consistent but I didn't manage to reproduce it yet — reproducing a similar environment leads to a successful build. Leaving that alone for now.

**Comment by Blaisorblade** [comment]
Given the amount of current issues, when I come back to Travis I plan to try (elsewhere) to just always use the latest cabal-install (1.24). Apparently the one we built uses the latest version of the Cabal library, so just installing 1.24 should work.

What's annoying is that, in fact, the build seems to work with an old cabal, just not on Travis 😞

**Comment by asr** [comment]
> Given the amount of current issues, when I come back to Travis I plan to try (elsewhere) to just always use the latest cabal-install (1.24).

So, I renamed the issue and I'm closing it.
