### ISSUE TITLE
An instance arguments related internal error.

### ISSUE THREAD

**Issue by effectfully** [agda/agda#2034]
I'm doing some generic programming stuff and stumbled upon an internal error. It appears on trying to type check `fail` at the bottom of [this](https://github.com/effectfully/Generic/blob/master/Examples/Fail.agda) file. The error is

```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/InstanceArguments.hs:276
```

Agda version 2.5.1 (from Hackage).

I don't know how to minimalize the example. Should I attach an archive with files or is the link above enough?

**Comment by Blaisorblade** [comment]
Can't comment on the bug, but let's press <kbd>y</kbd> on that page to get a [permalink](https://github.com/effectfully/Generic/blob/120d1a7bc518bc944ab08e2bc054ceefc4d10323/Examples/Fail.agda), and then no archive should be needed (unless you plan to wipe out the repo, but I guess not?)

**Comment by effectfully** [comment]
@Blaisorblade, no, I don't plan.

**Comment by nad** [comment]
Is this issue related to #1322?

**Comment by effectfully** [comment]
@nad, there is [a higher-order instance](https://github.com/effectfully/Generic/blob/120d1a7bc518bc944ab08e2bc054ceefc4d10323/Property/Eq.agda#L12):

```
ExtendEq (pi b P) = transform P λ A D -> Eq A × ∀ x -> ExtendEq (D x)

... {{eqD : ExtendEq D}} ...
```

but changing it to

```
ExtendEq (pi b P) = transform P λ A D -> Eq A × ∀ {x} -> ExtendEq (D x)
```

doesn't affect the error. I can update the repo if this may help.

**Comment by UlfNorell** [comment]
Making `x` implicit shouldn't affect things so that's no surprise. As far as I can tell it is the same problem as #1322. Or rather, it's the same scenario, but the difference is that your example should actually work. 

When faced with an instance problem `(x : A) -> B`, the solver should stick `x` in the context and try to find an instance for `B`. This is what you need in this example and what's giving the slightly confusing error message in #1322. Sometimes this doesn't work though, and you hit the `__IMPOSSIBLE__` instead.

**Comment by UlfNorell** [comment]
I believe the problem has to do with the instance goal being unknown the first time we look at the problem. Here's a scaled down test case (similar to the one in https://github.com/agda/agda/issues/1322#issuecomment-155737183):

``` agda
open import Agda.Builtin.Nat

postulate
  T : Set
  C₁ : Set
  instance I₁ : C₁

  C₂ : Nat → Set
  instance I₂ : ∀ {n} → C₂ n

it : {A : Set} {{_ : A}} → A
it {{x}} = x

postulate
  f₁ : {{_ : Nat → C₁}} → T
  f₂ : {{_ : ∀ n → C₂ n}} → T

works₁ : T
works₁ = f₁         -- f₁ {{λ _ → I₁}}

fails₁ : T
fails₁ = f₁ {{it}}  -- internal error

works₂ : T
works₂ = f₂         -- f₂ {{λ n → I₂ {n}}}

fails₂ : T
fails₂ = f₂ {{it}}  -- internal error
```
