### ISSUE TITLE
Matching on string causes solver to fail with internal error

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#2035]
``` haskell
open import Data.Unit
open import Data.String

break : String → ⊤
break "" = ?
break _ = tt

```

Go to the hole and execute `C-c C-a` to solve. Agda says `An internal error has occurred. Please report this as a bug. Location of the error: src/full/Agda/Auto/Convert.hs:624`

**Comment by asr** [comment]
@gallais, I added the 2.5.3 milestone.

**Comment by gallais** [comment]
Thanks!
