### ISSUE TITLE
Make stable-2.5 the default branch

### ISSUE THREAD

**Issue by Blaisorblade** [agda/agda#2037]
Could we consider making `stable-2.5` the current default branch? Then PRs would be opened against that automatically. The only possible downside is IIRC that issues would be marked as fixed by GitHub as soon as their bugfix (annotated as such) lands in `stable-2.5`, while now you merge to merge into `master` — but neither will ensure the bugfix is in both branches.

By now I can deal with that (though I have to pay attention), but for contributors this comes up often — the latest example is e.g. https://github.com/agda/agda/pull/2033. However, I guess one could document the workflow in issue templates and contribution instructions.

Opinions? @asr, what do you think? Note this must be done by an admin, so not by me.

**Comment by andreasabel** [comment]
I think the rationale behind leaving `master` the default is to have people beta-test the latest features.
However, now, do we have anything on `master` at all which is not on `stable`?

**Comment by UlfNorell** [comment]
Right now `master` and `stable` are pretty much the same, but that might not be true in the future. Aside from the fact that fewer people would use `master`, a problem I see with making `stable` the default is that if there's an issue on `master` it won't auto close since the commit will never end up on `stable`.

**Comment by Blaisorblade** [comment]
Fair enough — I had missed that the default branch is also the one shown to users. If people have ideas we can keep discussing, but I guess I should close for now.
