### ISSUE TITLE
Try reducing use of TemplateHaskell?

### ISSUE THREAD

**Issue by Blaisorblade** [agda/agda#2038]
Since @asr has various concerns about using TemplateHaskell, and it does not play nice with other tools, I thought the discussion about it should have a proper place.
1. It seems that reducing use of TemplateHaskell has advantages, whether it's removed completely or not. If so, one could gradually reduce
2. TemplateHaskell slows compilation. OTOH, Agda uses TemplateHaskell for test discovery _inside the library itself_, sometimes in the same files. That seems at odds with reducing compile times, and it might increase the binary size.
   Also, hspec uses a different approach to test discovery (http://hspec.github.io/hspec-discover.html, https://github.com/hspec/hspec-example), though I don't necessarily assume it avoids all problems with TemplateHaskell.
3. @asr explains that TemplateHaskell conflicts with `-fno-code`. https://github.com/agda/agda/issues/2023#issuecomment-225646168
   As a possible workaround, https://github.com/flycheck/flycheck-haskell/issues/6 suggests getting some of the gains with `-no-link -O0`. But limiting the use of TemplateHaskell might at least allow checking _more_ code quickly.
4. There's Geniplate-related use of TemplateHaskell. That seems more worthwhile, but I agree with Stephen Diehl that other approaches exist. I'm not sure if they have downsides (say, be slower). But that's only 

src/full/Agda/Utils/Geniplate.hs
src/full/Agda/Compiler/MAlonzo/Pretty.hs
src/full/Agda/Syntax/Internal.hs
src/full/Agda/Syntax/Abstract.hs
1. Then, we're considering TemplateHaskell for #2023, and @asr seems unhappy. If Agda reduces its use of TemplateHaskell, it makes sense to consider alternatives there, too.

**Comment by andreasabel** [comment]
I am all for removing/reducing TemplateHaskell.

**Comment by asr** [comment]
@Blaisorblade thanks for bring up it to discussion.

**Comment by asr** [comment]
> I am all for removing/reducing TemplateHaskell.

How ironic coming from the person who started using Template Haskell for 2) in the OP :-)

**Comment by andreasabel** [comment]
Ah, indeed. :-) 

Maybe we should move all tests outside of the Agda library, then the Agda library does not depend on TH just for creating boilerplate quickcheck test collections.

The problem with moving the tests to the outside is that we then have to export all functions we want to test (even if they are just for internal use).  Seems to be a limitation of Haskell's module system that there are no "friend" modules who can see beyond the abstraction layer.

**Comment by Blaisorblade** [comment]
> Maybe we should move all tests outside of the Agda library, then the Agda library does not depend on TH just for creating boilerplate quickcheck test collections.

+1.

> The problem with moving the tests to the outside is that we then have to export all functions we want to test (even if they are just for internal use). Seems to be a limitation of Haskell's module system that there are no "friend" modules who can see beyond the abstraction layer.

Ah, that's a good point, and I think that could be _one_ reason for all the `Internal` modules around Hackage. (Disclaimer: I am _not_ an expert on the Haskell ecosystem though).
Documenting them as `Internal` is considered acceptable IIUC, though it's certainly not perfect. Also, it seems using `Agda` as a library for external clients is not the current primary use case — and `Internal` modules would not be a major issue there I guess?

> Seems to be a limitation of Haskell's module system that there are no "friend" modules who can see beyond the abstraction layer.

Good point. Let me answer though I'm slightly OT: Hierarchical modules (à la ML, or even Scala core) could help a bit addressing this, but you'd need the "tests" module and the "library-internal" module to be in the same bigger module, and then link clients against this bigger module.

Amazingly, the JVM fares somewhat better: you just declare stuff to be package-private and put tests in the same "package" as the tested code. OTOH package-private is not really private — usually, anybody can add code to that package; nevertheless, it's the first upside I see for the JVM over (modern) ML modules, so color me impressed.

**Comment by phile314** [comment]
If the tests were moved to the testsuite, the QuickCheck dependency could also be moved from the library to the testsuite. This would speed up the build for people who just want to install Agda.

About a year ago, I was also considering integrating the QuickCheck tests with the tasty test runner using https://hackage.haskell.org/package/tasty-quickcheck , but this only makes sense if the tests are moved outside of the library.

**Comment by andreasabel** [comment]
A bit of a summary:
So, we would want to move the tests outside of the Agda library for the following reasons:
- reduce the dependency on TH
- remove the dependency on QuickCheck
- slightly faster build

The downsides are:
1. we have to drop the export lists (not a big downside maybe, they mostly annoy me)
2. we will get a lot of crap in the haddockumentation

Re 2.: At the moment, we have no nice API for Agda, so this point might not be a big obstacle actually. A nice API would be a separate library reexporting or nicely wrapping things from the Agda library.  But here we might hit the limits of haddock.

I filed an issue for haddock: https://github.com/haskell/haddock/issues/529

**Comment by Blaisorblade** [comment]
Note part of the reexporting can be done in the same library, with Foo
reexporting stuff from Foo.Internal; most users should not look at its
Haddock page, only at Foo's one. IIRC Haddock repeats docs for reexports.
This would prevent the regression in the Haddock output at a modest cost.
I agree with everything else.

(EDIT: remove misformatted quote).

EDIT2: ah, just seen your Haddock issue. Examples of the hack I mentioned are http://hayoo.fh-wedel.de/?query=internal, for instance http://hackage.haskell.org/package/text-1.2.2.1/docs/Data-Text-Internal.html fits the bill.

EDIT 3: while I just observed the pattern and guessed, here are explicit descriptions of the `Internal` pattern. [It is a common way to address this issue with test suite](http://stackoverflow.com/q/14379185/53974), and [it is more generally useful](http://stackoverflow.com/q/9190638/53974). But I'm not sure you can write tests against modules that are hidden by being placed in `other-modules` — maybe they can be just hidden in Haddock as you propose (asked here in a comment: http://stackoverflow.com/questions/14379185/function-privacy-and-unit-testing-haskell#comment63131545_14379521).

**Comment by asr** [comment]
> we have to drop the export lists (not a big downside maybe, they mostly annoy me)

Instead of drop the export lists, we should add the required entities.

**Comment by asr** [comment]
While working in #2083, I realised a nice feature of using `TemplateHaskell` in the internal test-suite: The name of the tested property is shown, for example,

```
InternalTests.Utils.Favorites
=== prop_compareWithFavorites from test/InternalTests/Utils/Favorites.hs:36 ===
+++ OK, passed 100 tests.

=== prop_fromList_after_toList from test/InternalTests/Utils/Favorites.hs:45 ===
+++ OK, passed 100 tests.

=== prop_union_union2 from test/InternalTests/Utils/Favorites.hs:50 ===
+++ OK, passed 100 tests.
```

If `TemplateHaskell` is not used, we don't see the name of the property:

```
InternalTests.Utils.Favorites
+++ OK, passed 100 tests.
+++ OK, passed 100 tests.
+++ OK, passed 100 tests.
```

Before removing `TemplateHaskell` from the internal test-suite, I'll see if I can print the name of property without using  it.

**Comment by andreasabel** [comment]
This is one of the reasons why I favored the TemplateHaskell solution: less to maintain, more informative output.

**Comment by asr** [comment]
> ~~Before removing `TemplateHaskell` from the internal test-suite, I'll see if I can print the name of property without using it.~~

I have no objections for using `TemplateHaskell` in the internal test-suite.

**Comment by nad** [comment]
There might be a case for reducing or eliminating the use of `universeBi` in `Agda.Interaction.Highlighting.Generate`:
* The code appears to be hard to understand. (The function `universeBi` basically traverses a value and finds every subexpression of a given type. Perhaps I should have written this in a comment in `Agda.Interaction.Highlighting.Generate`.)
* The local definition called `theRest` now involves 16 calls to `universeBi`. I suspect that we could speed up the code a little by replacing this with a single traversal. Profiling information (for the standard library) suggests that this could be worthwhile:
  ```
  Total                        440,357ms
  …
  Highlighting                  22,219ms
  ```
* I'm not sure if the code is easier to maintain with a single traversal or using `universeBi`. When `universeBi` is used every subexpression of the right type will be found (with some exceptions listed in [`Agda.Utils.Geniplate`](https://github.com/agda/agda/blob/7fbc85e6db3362624e7c3f22cb9a21b79ff8a639/src/full/Agda/Utils/Geniplate.hs#L23-L38)); there is no such guarantee for a manually implemented traversal. However, with a single traversal there is perhaps a higher chance that GHC will complain if some data type is changed (especially compared to the current implementation, which uses catch-all patterns).

For anyone who wants to try this:
* Test that the changes do not affect the HTML that is generated for the standard library. (I doubt that we have test cases for the highlighting of every kind of Agda syntax.)
* Benchmark Agda using `make library-test`.

**Comment by andreasabel** [comment]
After removing geniplate (PR #4574), the only use of TemplateHaskell will be in `Agda.VersionCommit`!  
It should not be too hard to find a solution here so that we can set up a `fno-code` type-checking option for the Agda source.  Presumably, one could pass a `#define` flag from the Makefile that can be checked using some `#ifdef` to disable the TemplateHaskell stuff there.

**Comment by andreasabel** [comment]
> It should not be too hard to find a solution here so that we can set up a `fno-code` type-checking option for the Agda source.

I found that this works without further changes.  Horray!

AD: Soon coming to the computer in your office:
```
make type-check
```
Type-check the Agda source in a few seconds!
