### ISSUE TITLE
Missing &&s on Travis

### ISSUE THREAD

**Issue by asr** [agda/agda#2039]
Something is wrong with Travis, [this](https://travis-ci.org/agda/agda/jobs/137199404#L542) error had to stop the job.

It is necessary to add the missing `&&`s. I also suggest don't use the multiline YAML string `|`  (see https://github.com/agda/agda/commit/7b39b0ac74750dd93e24cd73153d3f38d46b682a#commitcomment-17838999)  for keeping simple the configuration file.

@Blaisorblade I assigned you this issue.

**Comment by Blaisorblade** [comment]
Thanks. Testing https://github.com/Blaisorblade/agda/pull/6 for this.

**Comment by asr** [comment]
Great! Thanks!

**Comment by Blaisorblade** [comment]
#2039 (4479b621ebbf93b36892c03cbf814bb090765d61) is merged, now also in master, so this can be closed.
