### ISSUE TITLE
Documentation on refining module parameters

### ISSUE THREAD

**Issue by asr** [agda/agda#2048]
I couldn't type-check [this](https://github.com/agda/agda/blob/decf1b037d0ec76c7bae79f1dae01500957866d6/doc/release-notes/2-5-2.txt#L89-L101) example given in the CHANGELOG, instead I got the following error:

``` agda
module Test where

data Nat : Set where
  zero : Nat
  suc  : Nat → Nat

data Vec (A : Set) : Nat → Set where
  []  : Vec A zero
  _∷_ : ∀ {n} → A → Vec A n → Vec A (suc n)

module Foo {A : Set} {n : Nat} where

  f : Vec A n → Vec A n
  f []       = []
  f (x ∷ xs) = x ∷ f xs

-- Error:
-- /tmp/Test.agda:15,22-24
-- .n != (suc .n) of type Nat
-- when checking that the expression xs has type Vec A (suc .n)
```

**Comment by UlfNorell** [comment]
Yeah, that's a bug in the changelog.

**Comment by asr** [comment]
Which is the bug in the CHANGELOG?

**Comment by identicalsnowflake** [comment]
The `n` is already bound when `f` is defined, so it can't make a recursive call on a vector with `n - 1`. There is no `f` defined for any natural except `n`. To make it compile, add a forall n when defining f (which defeats the point of the example?) or remove the recursive call in the second clause.
