### ISSUE TITLE
Case splitting removes content of clause rhs

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2051]
``` agda
data D : Set where
  c : D

test : (x : D) → D
test x = let y = c in {!x!}  -- C-c C-c

-- Case splitting replaces entire RHS by hole
--   test c = ?
```

Before the fix of #289, Agda would simply refuse to split.  Now it can split, but is not very gentle with the existing content of the rhs.
Desired behavior: preserve rhs (as much as possible).

**Comment by andreasabel** [comment]
Tried to fix this by reifying the rhs of the internal clause with the question mark to abstract syntax and put it back with the new clause(s).  However, this does not work well. For instance:
- let-bindings are still dropped (they do not exist in internal syntax)
- if an interaction meta has been replace by an ordinary meta (e.g. by pruning), reification spits out something like `_11 x1` instead of `?`.

In general, I think internal syntax does not keep enough info to be accurately reified back to abstract syntax.  Another approach would be:
- save the AST clause rhs together with the internal clause
- put it back after case-splitting into the generated AST clauses

This will lose changes the user has done on interaction metas in the clause after the last reload.  We have to remember which interaction points are "dirty" e.g. modified since the last reload.  If a clause has a dirty interaction point, it should not be split.  The user should be warned that a split might lose changes to his code.  He might override this warning with `C-u C-c C-c`.

**Comment by andreasabel** [comment]
Using AST still does not work, I think we need to fall back to concrete syntax.  For instance, the names in let-bindings are printed wrongly when using AST.

**Comment by Blaisorblade** [comment]
@andreasabel: While you're at it, can I mention that Agda is also not so gentle with the content of the LHS? After splitting a bit, sometimes I add to it implicit arguments, or change the qualification of constructors (because, well, the pretty-printing is sometimes questionable), but if I split again that's all lost.
Should I create a new issue for that?

**Comment by andreasabel** [comment]
We are aware that case splitting is not very gentle with the user effort, however, it is not easy to change with the current infrastructure.  A new issue is not necessary I think.
Maybe you find your issue in this list: https://github.com/agda/agda/labels/case-splitting

**Comment by andreasabel** [comment]
Using AST still does not work, I think we need to fall back to concrete syntax.  For instance, the names in let-bindings are printed wrongly when using AST.

**Comment by jespercockx** [comment]
FYI: I just pushed a change that should make Agda much gentler with the contents of the LHS when case splitting. This still only takes into account the changes up to the last reload, though.

**Comment by andreasabel** [comment]
Which commit is that? 5e71c3d6bb10cfa43d464ca21e58523645f17e96..a3f7eaf3411f09f1faea30551bd8310f6292591e

**Comment by jespercockx** [comment]
Mostly d7c56d9a0ed73a999ee088c67f7b19cd6f8a9f72, though it makes use of the Origin tags introduced in 5e71c3d6bb10cfa43d464ca21e58523645f17e96, c19daeb79f5598178d4d46a77a5850bd3da21ba5, 64f712f6eeef3d51890e54890d3d17fb0b96bcae, 0aeba755387a5639fea22672437a2dd45948f488.
