### ISSUE TITLE
Add documentation for abstract blocks

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda#2055]
I know the new docs are a work in progress, but they don't currently have even a stub for abstract blocks. For such an incredibly useful feature, the documentation is almost non-existent.

I just discovered it after months of 30 second+ type checking times, and only found it because of stumbling upon this 8 year old [page](http://wiki.portal.chalmers.se/agda/pmwiki.php?n=Main.AgdaLanguageReview). The only mention I can find of what it does is the one example [here](http://wiki.portal.chalmers.se/agda/pmwiki.php?n=Main.PerformanceTips).

**Comment by andreasabel** [comment]
I agree!

On 21.06.2016 11:54, MatthewDaggitt wrote:

> I know the new docs are a work in progress, but they don't currently
> have even a stub for abstract blocks. For such an incredibly useful
> feature (just discovered it after months of putting up with 30 second+
> checking times), the existing documentation is almost non-existent! I
> only found it because of stumbling upon this 8 year old page
> http://wiki.portal.chalmers.se/agda/pmwiki.php?n=Main.AgdaLanguageReview,
> and the only mention of what it does I can find is the one example here
> http://wiki.portal.chalmers.se/agda/pmwiki.php?n=Main.PerformanceTips.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/agda/agda/issues/2055, or mute the thread
> https://github.com/notifications/unsubscribe/ABGgkrEaNd0Yzlj8VDaZ0VZqCXE_rEr_ks5qN7S-gaJpZM4I6jWs.

## 

Andreas Abel  <><      Du bist der geliebte Mensch.

Department of Computer Science and Engineering
Chalmers and Gothenburg University, Sweden

andreas.abel@gu.se
http://www2.tcs.ifi.lmu.de/~abel/

**Comment by andreasabel** [comment]
Here you go!  (I learned the rules of `abstract` through fixing #2101.)

Some of the genesis of the current semantics of `abstract` is documented at issue #278.

**Comment by MatthewDaggitt** [comment]
Thanks, that explains a lot. I'd worked out there was something weird going
on between abstract and private, but that clears it up!
Thanks,
Matthew
