### ISSUE TITLE
Problem with underapplied display form, surfaced with parameter refinement

### ISSUE THREAD

**Issue by nad** [agda/agda#2057]
The following code triggers an internal error (`src/full/Agda/TypeChecking/Substitute.hs:680`):

``` agda
record R (A : Set) : Set₁ where
  field
    P : A → Set
    p : (x : A) → P x

module M (r : (A : Set) → R A) where

  open module R′ {A : Set} = R (r A) public

postulate
  r : (A : Set) → R A
  A : Set

open M r

internal-error : (x : A) → P x
internal-error _ = p
```

The error can also be triggered by replacing the last definition with

```
Internal-error : Set
Internal-error = ?
```

and inferring the type of `p` in the hole.

This is a regression. Bisection points to @UlfNorell's commit "[ refine param ] allow module parameters to be refined by pattern matching" (943e9bee0a1fc58575b8e292e28d03c0ba98bbc8).

**Comment by UlfNorell** [comment]
The problem was actually there already in `2.5.1`. It's just that after my changes we are more sensitive to deBruijn indices being nonsense. Note that in `2.5.1` you get the error message

``` agda
(x : _A_9 .x) → R.P (r (_A_9 .x)) x !=< R.P (r A) .x
```

with a broken display form for `P`. After the fix you get the correct error:

``` agda
(x : _A_9 .x) → P x !=< P .x
```

**Comment by andreasabel** [comment]
See the line note at https://github.com/agda/agda/commit/d88a00858d0296eb2e836bf2bb8d30f27c99578d

**Comment by andreasabel** [comment]
Ah, forget my comment, mea culpa.

**Comment by UlfNorell** [comment]
No it looks like you are right. I'm opening a new issue for it though.
