### ISSUE TITLE
Missing continuous integration with Windows 

### ISSUE THREAD

**Issue by asr** [agda/agda#2058]
A continuous integration with Windows is very convenient. You can see an example in the `README.md` file of the [hlint](https://github.com/ndmitchell/hlint) repository.

**Comment by asr** [comment]
Even Idris is using [AppVeyor](https://ci.appveyor.com/project/idrislang/idris-dev) for its CI on Windows :-). Any volunteer?

**Comment by gallais** [comment]
I started looking into this on https://github.com/gallais/agda/tree/appveyor. It looks like I'm on the path of getting [something very basic working](https://ci.appveyor.com/project/gallais/agda/build/1.0.10). However one of the big limitations of appveyor is that we only get **1 build** running at any time.

They nonetheless have one neat feature which can be activated in the `Settings` tab of a project: rolling builds. This automatically cancels queued builds whenever someone pushes to the same branch.

**Comment by favonia** [comment]
@gallais FYI: travis also has the "auto cancellation" feature, if Agda devs want it.

**Comment by nad** [comment]
I turned on auto cancellation for "branch builds".

**Comment by asr** [comment]
> I started looking into this on https://github.com/gallais/agda/tree/appveyor. It looks like I'm on the path of getting [something very basic working](https://ci.appveyor.com/project/gallais/agda/build/1.0.10). However one of the big limitations of appveyor is that we only get **1 build** running at any time.

@gallais Can I see the output of building the current stable-2.5 branch on Windows?

**Comment by gallais** [comment]
I have launched [a new build](https://ci.appveyor.com/project/gallais/agda/build/1.0.17) with the current stable-2.5. If this goes through I'll turn on builds for agda/agda.

Edit: okay, I've tracked down the issue with 7.10.3: [the package itself is broken](https://chocolatey.org/packages/ghc/7.10.3). I'm trying [a new build](https://ci.appveyor.com/project/gallais/agda/build/1.0.18) with [ghc-7.10.3.2](https://chocolatey.org/packages/ghc/7.10.3.2) instead.

**Comment by nad** [comment]
If your build does not include d33216b65c409dad038a7bc898fbe7d37ac58ec1, then you might want to cancel it (assuming that you run the test suite).

**Comment by gallais** [comment]
The current build is not running any tests (I have yet to learn how to get `make` to work on windows).

**Comment by gallais** [comment]
I don't know why appveyor doesn't automatically start a build when I push. It worked fine on my branch and the tokens I have generated do give them access to the organisation's repos. :/

Edit: nevermind, it just started. It just takes a few minutes for the website to notice the push apparently.

**Comment by gallais** [comment]
It looks like only my commits trigger a build. I'm guessing that's because I created the project with my credentials. Can an owner (@ulfnorell? @andreasabel?) create an account for the organisation agda on appveyor?

Here is the process you need to follow:
https://www.appveyor.com/docs/team-setup/#setting-up-appveyor-account-for-github-organization

Additionally, once you've added the agda/agda project you want to go to Settings/General and tick:
* Skip branches without appveyor.yml
* Rolling builds (+￼ Do not cancel running builds)

And then go to Settings/Badges and update the url for the appveyor badges in the READMEs on the branches master & stable-2.5 with the ones given there.

Cheers!

**Comment by UlfNorell** [comment]
I'm attempting to follow the instructions from the link but I'm confused about this step:

> On the same page authorize AppVeyor to access GitHub. A new OAuth token will be generated and used for accessing organization’s repositories and teams on behalf of your GitHub user.

When I click the `Authorize GitHub` button it wants access to my personal GitHub account (and thus all my organisations). I don't see where how the AppVeyor account gets linked to a particular organisation. In fact, how does any of the steps described differ from setting up a personal AppVeyor account?

**Comment by gallais** [comment]
> In fact, how does any of the steps described differ from setting up a personal AppVeyor account?

I guess the main difference is that you have to go through the picking a name / email process when you could just create your personal account in one click based on your github profile. Not sure indeed that they are intrinsically different notion on Appveyor's side.

**Comment by UlfNorell** [comment]
So do we have any reason to believe that it will start jobs on commits other than mine if I go through with the process?

**Comment by UlfNorell** [comment]
I'm also reluctant to add everyone in the Agda organisation as collaborators to an AppVeyor account with access to my personal GitHub account.

**Comment by gallais** [comment]
I have just learned that Travis has had support for windows builds for a little
while. So we now have an AppVeyor-free alternative:

https://docs.travis-ci.com/user/reference/windows/

**Comment by gallais** [comment]
I believe this has been fixed now that we have a github action for windows.
