### ISSUE TITLE
Add installation instructions for OS X

### ISSUE THREAD

**Issue by mietek** [agda/agda#2060]
[Homebrew](http://brew.sh) provides prebuilt packages for OS X.  To install:

```
brew install agda
```

This should take less than a minute, and install Agda together with the Emacs mode and the standard library.

By default, the standard library is installed in `/usr/local/lib/agda`.  To use the standard library, it is convenient to add `/usr/local/lib/agda/standard-library.agda-lib` to `~/.agda/libraries`, and specify `standard-library` in `~/.agda/defaults`.  Note this is not performed automatically.

It is also possible to install `--without-stdlib`, `--without-ghc`, or from `--HEAD`.  Note this will require building Agda from source.

For more information, refer to the [Homebrew documentation](http://git.io/brew-docs).

---

I’ve been taking care of the [Agda formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/agda.rb) for a while, and I’m happy to continue doing so.
- [Agda 2.5.1.1](https://github.com/Homebrew/homebrew-core/pull/2248)
- [Agda 2.5.1](https://github.com/Homebrew/homebrew-core/pull/440)
- [Agda 2.4.2.5](https://github.com/Homebrew/legacy-homebrew/pull/47237)
- [Agda: Fix non-standard library location](https://github.com/Homebrew/legacy-homebrew/pull/47199)
- [Agda: Tweak layout; bump revision](https://github.com/Homebrew/legacy-homebrew/pull/47190)
- [Agda: Combo fix](https://github.com/Homebrew/legacy-homebrew/pull/45327)
- [Agda 2.4.2.4](https://github.com/Homebrew/legacy-homebrew/pull/45287)

Perhaps a note can be added to the documentation?

**Comment by asr** [comment]
Thanks for taking care of the Agda formula.

> Perhaps a note can be added to the documentation?

Sure. Please create a PR using the _stable-2.5_ branch and adding the documentation to the [installation.rst](https://github.com/agda/agda/blob/stable-2.5/doc/user-manual/getting-started/installation.rst) file.

**Comment by mietek** [comment]
Thanks.

**Comment by pnlph** [comment]
@mietek If the standard version of Agda was installed with `brew`, what would be the best way of installing the developer version of Agda being possible to switch between both of them? Thanks!
