### ISSUE TITLE
Change in the internal syntax representation after parameter refinement

### ISSUE THREAD

**Issue by asr** [agda/agda#2061]
Given the following code

``` agda
postulate
  ℕ : Set
  P : ℕ → Set

foo : (n : ℕ) → P n → Set
foo n Pn = A
  where
  A : Set
  A = ℕ
```

before the parameter-refinement commit 943e9bee0a1fc58575b8e292e28d03c0ba98bbc8, the internal syntax representation of the type of `A` was

```
El {_getSort = Type (Max [ClosedLevel 1]), unEl = Pi k(El {_getSort = Type (Max []), unEl = Def Test.ℕ []}) (Abs "n" El {_getSort = Type (Max [ClosedLevel 1]), unEl = Pi k(El {_getSort = Type (Max []), unEl = Def Test.P [Apply r(Var 0 [])]}) (Abs "Pn" El {_getSort = Type (Max [ClosedLevel 1]), unEl = Sort (Type (Max []))})})}`
```

and after that commit (and also with the current stable), it is

```
El {_getSort = Type (Max [ClosedLevel 1]), unEl = Pi k(El {_getSort = Type (Max []), unEl = Def Test.ℕ []}) (Abs "n" El {_getSort = Type (Max [ClosedLevel 1]), unEl = Pi k(El {_getSort = Type (Max []), unEl = Def Test.P [Apply r(Var 0 [])]}) (NoAbs "Pn" El {_getSort = Type (Max [ClosedLevel 1]), unEl = Sort (Type (Max []))})})}
```

Note that `Abs "Pn"` changed to `NoAbs "Pn"`. Was this change intentional?

I also noticed some changes in the internal representation of the clauses.

**Comment by UlfNorell** [comment]
I don't know about intentional, but it certainly seems harmless. Why are you looking at this?

**Comment by andreasabel** [comment]
I am not sure what the issue here is, so I am closing it, please feel free to reopen if you want to continue the discussion.
