### ISSUE TITLE
Copattern matching: Hyvernat termination would succeed

### ISSUE THREAD

**Issue by anuyts** [agda/agda#2068]
There is a problem in how copattern matching interacts with type checking and resolving implicit arguments.
- When creating a dependent record using copattern matching, the type of a dependent field may contain references to the record under construction. (This is in itself unpractical when you want to split up the record's definition, e.g. when you want to say field5 = myField5 and define myField5 above the copattern matching definition.)
- When resolving implicit arguments, this self-reference may sneak into the term.
- Havoc ensues when the termination checker does not realize that the self-reference is legitimate.

An example can be found below. There is currently a tedious workaround:
- Put holes for the problematic implicit arguments.
- Let agda fill out the holes (c-c c-s).
- Manually unfold the self-reference.

I suggest:
- To automatically unfold self-references in the type (this also solves the inconvenience with predefining fields).
- Maybe also to make the termination checker aware of legitimate self-references.

``` agda
module tests.RecordFieldTypes where

data _==_ {A : Set} : A → A → Set where
  refl : {a : A} → a == a

data Bool : Set where
  tt : Bool
  ff : Bool

record TwoEqualFunctions : Set₁ where
  field
    A : Set
    B : Set
    f : A → B
    g : A → B
    p : f == g

postulate funext : {A B : Set} → {f g : A → B} → ((a : A) → f a == g a) → f == g

--does not work
identities : TwoEqualFunctions
TwoEqualFunctions.A identities = Bool
TwoEqualFunctions.B identities = Bool
TwoEqualFunctions.f identities x = x
TwoEqualFunctions.g identities = λ{tt → tt ; ff → ff}
TwoEqualFunctions.p identities = funext (λ{tt → refl ; ff → refl})

{-
--Bool is manually filled out
--TwoEqualFunctions.f/g identities tt/ff is Agda's suggestion
--does not work
identities : TwoEqualFunctions
TwoEqualFunctions.A identities = Bool
TwoEqualFunctions.B identities = Bool
TwoEqualFunctions.f identities x = x
TwoEqualFunctions.g identities = λ{tt → tt ; ff → ff}
TwoEqualFunctions.p identities = funext (λ{tt → refl{Bool}{TwoEqualFunctions.f identities tt} ; ff → refl{Bool}{TwoEqualFunctions.f identities ff}})
-}

{-
--Works. But this is just obtained by unfolding everything until it doesn't contain a reference to 'identities'. Agda could do this automatically.
identities : TwoEqualFunctions
TwoEqualFunctions.A identities = Bool
TwoEqualFunctions.B identities = Bool
TwoEqualFunctions.f identities x = x
TwoEqualFunctions.g identities = λ{tt → tt ; ff → ff}
TwoEqualFunctions.p identities = funext λ{tt → refl{_}{tt} ; ff → refl{_}{ff}}
-}
```

I use Agda version 2.5.0.20160213.

**Comment by andreasabel** [comment]
Simplified test case:

``` agda
data _==_ {A : Set} : (a : A) → A → Set where
  refl : (a : A) → a == a

data Unit : Set where
  unit : Unit

record R : Set₁ where
  field
    f : Unit → Unit
    p : f == λ x → x

postulate
  extId : (f : Unit → Unit) → (∀ a → f a == a) → f == λ x → x

-- {-# TERMINATING #-}

test : R
R.f test = λ{unit → unit}
R.p test = extId {! R.f test !} λ{unit → refl {! R.f test unit !}} -- Termination error
```

The content of the holes is inferred by unification.  Error:

```
Termination checking failed for the following functions:
  test
Problematic calls:
  R.f test unit
    (at /home/abel/agda/test/bugs/Issue2068.agda:20,5-9)
  R.f test
    (at /home/abel/agda/test/bugs/Issue2068.agda:20,5-9)
  λ { unit → refl (R.f test unit) }
    (at /home/abel/agda/test/bugs/Issue2068.agda:20,33-67)
```

See also #906 and #942.

**Comment by andreasabel** [comment]
What we could do here is to simplify the rhss of the clauses with non-recursive other clauses from the mutual block.  However, this could also lead to removal of diverging subterms.

``` agda
  record _×_ (A B : Set) : Set where
    field fst : A
          snd : B
  open _×_

  test : ∀{A} (a : A) → (A → A) × (A → A)
  fst (test a) x = a
  snd (test a) x = fst (test a) (snd (test a) x)
```

In this case, if we simplify with the first equation, the second one becomes

```
  snd (test a) x = a
```

and the loop is removed.  Thus, we only get weak normalization from the termination checker.  However, Agda might rely on strong normalization, i.e. that no subterm diverges.

Can you try to express your suggestions rigorously?  Like exactly under which conditions should self-references (aka recursive occurrences) be unfolded?  Note that before termination checking, we have to proceed carefully, we could easily get into a loop, e.g. if the user writes non-terminating definitions.

**Comment by anuyts** [comment]
Let's forget about my second suggestion for now. Then your last example would (1) probably not be accepted (I don't have Agda around right now) even if you replace the second clause with e.g.
`snd (test a) x = fst (test a) x`
and (2) not be relevant, because `B` does not refer to `fst`.

My other suggestion is to remove self-references in the fields' _types_ before type-checking and inferring implicit arguments. Moving to your simplified test case:
- The field `f` has a non-dependent type. Nothing interesting here.
- After defining `f` as `\{unit -> unit}`, the type of the field `p` unfolds to `\{unit -> unit} == \ x -> x`; that is, `f` gets replaced with its definition. No further unfolding is done, we just replace the copattern with its definition. The definition of `f` does not contain references to `test` as this is not currently accepted by the termination checker (†) and can therefore be used to infer holes.

(†) Yes, this is all happening before termination checking. But if self-references are unfolded just once and not iteratively, then everything should work in the sense that you have automatized the workaround I mentioned.

If you want to make the termination-checker more intelligent, then maybe we could define a legitimate self-reference as a reference to a co-pattern that is higher up in the definition? Perhaps internally, it is useful to immediately unfold such things?

**Comment by anuyts** [comment]
It does work for record expressions:

``` agda
identities : TwoEqualFunctions
identities = record
  { A = Bool
  ; B = Bool
  ; f = λ x → x
  ; g = λ{tt → tt ; ff → ff}
  ; p = funext λ{tt → refl ; ff → refl}
  }
```

type-checks fine.

**Comment by andreasabel** [comment]
For this issue, Pierre Hyvernat's termination checker would help.  It would find a call
```
test .p --> test .f
```
but no recursive call.  This would give immediate termination.

**Comment by UlfNorell** [comment]
See also the actual Hyvernat ticket: #1390.

**Comment by jespercockx** [comment]
@andreasabel Why did you change the milestone to 2.6.1? We're (hopefully) still planning to release soon, no?
