### ISSUE TITLE
Missing documentation for the `debug` flag

### ISSUE THREAD

**Issue by asr** [agda/agda#2071]
A `debug` flag was added to install Agda in 21b3938. There isn't documentation (CHANGELOG and manual) for this flag. @nad I assigned you this issue.

**Comment by nad** [comment]
As long as there is no documentation of the various `-v` options I don't see the point of adding more documentation for this flag. The `.cabal` file currently includes the following line: "Enable debugging features that may slow Agda down." We could decide to not include this flag in released versions of Agda, to reduce the risk of confusing users.

**Comment by asr** [comment]
I only was talking about the flag, no the `-v` options. I'll reopen the issue if we include the flag in the next release.
