### ISSUE TITLE
Reflecting literals in patterns causes problems

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#2072]
``` haskell
open import Reflection
open import Data.String
open import Data.Unit
open import Data.List

_-<_ = bindTC

pw : String → String
pw "password1" = "correct" -- comment this line and all ok
pw x = "incorrect"

defToTerm : Definition → Term
defToTerm (function cs) = pat-lam cs []
defToTerm _ = unknown

getDefinition' : Term → TC Term
getDefinition' (def f _) = getDefinition f -< λ x → returnTC (defToTerm x)
getDefinition' x = returnTC x

macro
  m : ∀ {ℓ} {t : Set ℓ} → t → Term → TC ⊤
  m f t = quoteTC f -< λ d → getDefinition' d -< λ x → unify t x

x : String → String
x = m pw

```

Comment/uncomment line 9 to see the strange behavior. String literals work as expected when they only appear in the body, but when they appear in a pattern, Agda complains `Cannot unquote non-canonical literal "password1"`.

Possibly related: there is some additionally odd but less wrong behavior with other literals -- in particular, when I pattern match on Nat literals, it works, but it doesn't give me a reflected `lit` in the pattern; rather, it immediately decodes the literal into `suc`'s and `zero` and gives me that in the reflected pattern. This is not what happens in the body -- in body terms, nat literals appear as expected, still in literal form.

**Comment by UlfNorell** [comment]
The problem is that literal patterns are quoted incorrectly. Instead of `lit (string "password1")` the pattern is quoted to just `lit "password1"`, which is of course not correct.

**Comment by UlfNorell** [comment]
The behaviour of nat literals is intended. That is in fact how literal nat patterns are represented internally in order to make pattern coverage checking easier.
