### ISSUE TITLE
Solving metas in the pattern matching unifier leads to non-unique solutions

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#2074]
Currently, the pattern matching unifier has two places where it can solve a metavariable:
1. When it encounters an equation of the form `c xs =?= _1` where `c` is a constructor, it tries to instantiate `_1` to `c` applied to fresh metas.
2. When it cannot solve an equation `u =?= v` by the regular rules, it tries to force `u` to be equal to `v` by instantiating metas (through a call to `equalTerm`).

However, 2. can lead to non-unique solutions of metavariables. For example:

``` agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Equality

f : Nat → Nat
f zero = zero
f (suc x) = suc (f x)

test : {n : Nat} → zero ≡ _ → f n ≡ zero → Nat
test refl refl = {!!}
```

gives an error: `f n != zero of type Nat`, but replacing the underscore by `n` allows the code to typecheck.

Disallowing rule 2. causes two problems in the test suite: in #199 and #314. #314 contains a genuine case of a non-unique solution, but #199 doesn't.

**Comment by andreasabel** [comment]
A situation where you would want non-unique solutions is in local definitions (where-blocks), wouldn't you?  (See flag `envCheckingWhere`.)

**Comment by jespercockx** [comment]
I don't see why checking definitions in a where block should behave any different from top-level ones. Can you explain?

**Comment by andreasabel** [comment]
This would be an example:

``` agda
postulate
  List : Set → Set
  nil : ∀ A → List A

-- Succeeds:

test : ∀{A} → List A
test = myNil
  module Local where
    myNil : _
    myNil = nil _

-- Fails:

module Test {A : Set} where
  myNil : _
  myNil = nil _ -- yellow

testM : ∀{A} → List A
testM = Test.myNil -- yellow
```

We don't freeze metas after checking a `where` block.  But we do for a similar external module.

**Comment by jespercockx** [comment]
Well, but not freezing metas is not the same thing as solving them with a non-unique solution. I agree that we may want to do the former, but the latter goes against (my image of) the philosophy of Agda.

**Comment by jespercockx** [comment]
Since there are no more reactions on this issue, I went ahead and pushed my proposed (and very simple) fix. Please let me know if this causes any trouble.
