### ISSUE TITLE
Computed implicit arguments are introduced too early.

### ISSUE THREAD

**Issue by effectfully** [agda/agda#2080]
The following code doesn't type check:

``` agda
open import Data.List.Base

Fold : List Set -> Set -> Set
Fold  []      B = B
Fold (A ∷ As) B = {x : A} -> Fold As B

fold : ∀ {B} As -> Fold As B -> Fold As B
fold  []      y = y
fold (A ∷ As) f = λ {x} -> fold As (f {x})

-- {x : _11 A As f} → _13 A As f !=< Fold As .B of type
-- dLub (Set (_10 A As f)) (λ x → Set (_12 A As f))
-- when checking that the expression λ {x} → fold As (f {x}) has type
-- Fold As .B
```

If I write `fold (A ∷ As) f = {!!}`, then I see that implicitly bound `x` is already in scope. `fold (A ∷ As) f {x} = fold As (f {x})` type checks fine.

I don't know whether this is a bug or a feature, but it broke some my code, so here is a report. Agda version 2.6.0

**Comment by andreasabel** [comment]
This is an intended change by Ulf. See issues #2001 and #679.
It is already documented in the release notes for 2.5.2.
No further action intended, but reopen this issue if you have a suggestion.
