### ISSUE TITLE
Where module inside private block not private

### ISSUE THREAD

**Issue by nad** [agda/agda#2081]
Is there a good reason for making `Public.Public` visible in the definition of `Works` below, but not `Private`?

``` agda
module Bug where

module M where

  private

    Private : Set₁
    Private = Set
      module Public where
        Public : Set₁
        Public = Set

open M public

Works : Set₁
Works = Public.Public

Fails : Set₁
Fails = Private
```

Agda 2.2.10 handles this correctly (in my opinion), and complains about both of the last two definitions. However, Agda 2.3.0.1 accepts `Works`.

**Comment by andreasabel** [comment]
Looks like a bug to me.

**Comment by andreasabel** [comment]
In fact, the `where`-module `Public` should be `private`, we should propagate this modifier to the names of `where`-modules.
