### ISSUE TITLE
The internal test-suite doesn't report if a test failed

### ISSUE THREAD

**Issue by asr** [agda/agda#2085]
When an internal test doesn't use QuickCheck, the internal test-suite doesn't report if the test failed.

For example, if I replace  `Agda.Interaction.Options.prop_defaultOptions` by

``` haskell
prop_defaultOptions :: IO Bool
prop_defaultOptions = return False
```

and run

```
make tests
```

I only get the following information:

```
======================================================================
======================== Internal test suite =========================
======================================================================
/tmp/agda/dist-2.5.2/build/agda/agda --test +RTS -M1g
QuickCheck test suite:
Agda.TypeChecking.Free.Tests
=== prop_FlexRig_order from src/full/Agda/TypeChecking/Free/Tests.hs:41 ===
+++ OK, passed 100 tests.
...
Agda.Interaction.Options
Agda.Syntax.Parser.Parser
...
make: *** [tests] Error 1
```

that is, I don't know if a test failed in `Agda.Interaction.Options`.

**Comment by phile314** [comment]
Hm, but shouldn't the  "make tests" target now call the new cabal test suite instead of "agda --test"?

**Comment by asr** [comment]
While working on this issue I noticed that the internal test-suite isn't reporting any failed test.

**Comment by asr** [comment]
The OP was wrong. I fixed the issue reported in the new title.
