### ISSUE TITLE
Refactor clauseBody to be relative to the clause telescope

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#2086]
(following the discussion in #2047)

**Comment by jespercockx** [comment]
Whew, this took a lot more effort than I initially thought it would take, but it was definitely worth it. See 6771d807d6b3e6274535439d9c3b732d37382347 for all the changes. I managed to remove a lot of old and dusty code in the process.

**Comment by andreasabel** [comment]
Ah, yes, I was going to inquire how things are with this issue.  Great you finished!!

**Comment by jespercockx** [comment]
Hm, according to travis I broke something, but I'm not sure what. The failing build can be found at https://travis-ci.org/agda/agda/jobs/148365525. Can someone figure out what's going wrong?

**Comment by asr** [comment]
You can reproduce the problem on Travis running

```
make install-bin CABAL_OPTS='-f -cpphs'
```

and you can fix this particular problem removing the apostrophe from `u'`.

**Comment by andreasabel** [comment]
I pushed a small patch after reviewing your big refactoring.

**Comment by andreasabel** [comment]
I pushed a patch fixing the CPP error (renamed `u'` to `u1`).

**Comment by andreasabel** [comment]
Mmh, there are more CPP failures...  Ok, this time I wait for 

```
make install CABAL_OPTS="-f -cpphs"
```

to complete.  (Takes a while since it compiles everything from scratch.)

@asr: Maybe I should make this the default!?  Or are there other errors that might come when not using these flags?

**Comment by asr** [comment]
We are using `cpphs` as the default because `cpp` generates some problems in Mac.

**Comment by asr** [comment]
Due to the apostrophe, `cpp` (but no `cpphs`) generates an error of compilation in equations of the form

```
foo' = ... __IMPOSSIBLE__ ...
```

Replacing `foo'` by something like `foo''`, `foo1` or `foo_` fix the problem.

**Comment by asr** [comment]
The above issue is an [open issue](https://ghc.haskell.org/trac/ghc/ticket/860) in GHC from 10 years ago.
