### ISSUE TITLE
''No such module'' is a rude error message for private modules

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2089]
``` agda
module _ where

module M where
  private module Private where

module ShouldFail = M.Private
```

The error is `No such module M.Private` which is a lie.  More polite would be `M.Private is not scope because it is declared private` or something similar.

**Comment by UlfNorell** [comment]
This should be fairly straightforward to do for local modules. For imported modules we don't keep the private namespace around, and it's not clear that it's worth the trouble or even desirable to expose private names of library modules in error messages.

**Comment by andreasabel** [comment]
Maybe it is sufficient to change the wording to `module M.Private not in scope`.

**Comment by UlfNorell** [comment]
That would indeed be the cheapest solution 👍
