### ISSUE TITLE
GHC 8.0.1 doesn't report unrecognised warning flags

### ISSUE THREAD

**Issue by asr** [agda/agda#2094]
What the title says.

Following @andreasabel suggestion (can you find  his suggestion in GitHub?), I'm opening a new issue, commenting on this issue and tagging this issue. I will submit a no-one-line patch and close the issue later (feeling sarcastic too).

**Comment by andreasabel** [comment]
Good that is not a one-liner, otherwise the issue might have been wasted. :D
