### ISSUE TITLE
Fillable size hole not filling

### ISSUE THREAD

**Issue by mietek** [agda/agda#2095]
> `m != ω` of type `Size`
> when checking that the expression `↑ (↑ (↑ (↑ m)))` has type `Size`

Agda 2.5.1.1 refuses to fill the hole in `ccont′`, despite having found the code acceptable just two lines earlier, in `ccont`.

``` agda
module SizeBug1 where

open import Agda.Builtin.Size

data Cx (U : Set) : Set where
  ⌀   : Cx U
  _,_ : Cx U → U → Cx U

data _∈_ {U : Set} (A : U) : Cx U → Set where
  top : ∀ {Γ} → A ∈ (Γ , A)
  pop : ∀ {C Γ} → A ∈ Γ → A ∈ (Γ , C)

infixr 3 _⊃_
data Ty : Set where
  ι   : Ty
  _⊃_ : Ty → Ty → Ty

infix 1 _⊢⟨_⟩_
data _⊢⟨_⟩_ (Γ : Cx Ty) : Size → Ty → Set where
  var : ∀ {m A}                     → A ∈ Γ → Γ ⊢⟨ m ⟩ A
  lam : ∀ {m A B} {m′ : Size< m}    → Γ , A ⊢⟨ m′ ⟩ B → Γ ⊢⟨ m ⟩ A ⊃ B
  app : ∀ {m A B} {m′ m″ : Size< m} → Γ ⊢⟨ m′ ⟩ A ⊃ B → Γ ⊢⟨ m″ ⟩ A → Γ ⊢⟨ m ⟩ B

ccont : ∀ {m A B Γ} → Γ ⊢⟨ ↑ ↑ ↑ ↑ m ⟩ (A ⊃ A ⊃ B) ⊃ A ⊃ B
ccont = lam (lam (app (app (var (pop top)) (var top)) (var top)))

ccont′ : ∀ {m A B Γ} → Γ ⊢⟨ {!↑ ↑ ↑ ↑ m!} ⟩ (A ⊃ A ⊃ B) ⊃ A ⊃ B
ccont′ = lam (lam (app (app (var (pop top)) (var top)) (var top)))
```

**Comment by andreasabel** [comment]
Agda has already solved this meta with infinity.  You can see that with `C-c C-=` and substantiate it with `C-c C-s`.  However, it should not have done so.  Somehow the mechanism from preventing it is failing here.  I need to investigate.

**Comment by andreasabel** [comment]
This required some refactoring in the size-solver, to keep track of which interaction metas are constrained and thus should not be solved by infinity (even if the solver did not find a solution).
