### ISSUE TITLE
`abstract` and `where`

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2101]
Question raised by Serge Mechveliani, see http://comments.gmane.org/gmane.comp.lang.agda/8721
If a definition has a `where` block, we cannot simply make it `abstract`:

``` agda
record Wrap (A : Set) : Set where
  field unwrap : A

postulate
  P : ∀{A : Set} → A → Set

abstract
  f : (A : Set) → Set
  f A = A
    module M where
    B : Set
    B = Wrap A

    postulate
      b : B
      test : P (Wrap.unwrap b) -- fails, but should succeed?
```

The reason is that abstract definitions are not translucent in type signature, no matter whether we are in an abstract block or not.  Thus, the definition of `B` is opaque in the type signature for `test`.

However, would not the following invariant be desirable?

  If a function type-checks, I can make it abstract and it still type-checks.  

(Of course, other functions are then allowed to fail type-checking.)

**Comment by andreasabel** [comment]
See also discussion at issue #1485.

**Comment by andreasabel** [comment]
Private type signatures can see through abstract definitions.  Thus, I fixed this issue by making `where`-declarations private automatically.  They can anyway not be accessed from outside.
The situation is different for the form `module M where` of the where-block.  Here, declarations will not be private by default. Thus, one will still get the error for the example above.
However, this works now:

``` agda
record Wrap (A : Set) : Set where
  field unwrap : A

postulate
  P : ∀{A : Set} → A → Set

abstract
  f : (A : Set) → Set
  f A = A
    where
    B : Set
    B = Wrap A

    postulate
      b : B
      test : P (Wrap.unwrap b) 
```

**Comment by UlfNorell** [comment]
Note that the decision in #418 to make private, abstract type signatures not see through abstract makes this (deliberately) no longer work.
