### ISSUE TITLE
Internal error in positivity checker

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#2108]
Here is a minimized example (maybe further minimization is possible):

``` agda
open import Agda.Primitive
open import Agda.Builtin.Equality

lone = lsuc lzero

record Level-zero-or-one : Set where
  field
    level : Level
    is-lower : level ⊔ lone ≡ lone

open Level-zero-or-one public

Coerce : ∀ {a} → a ≡ lone → Set₁
Coerce refl = Set

data Test : Set₁ where
  test : Coerce (is-lower _) → Test
```

This results in the following error:

```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Positivity.hs:507
```

**Comment by andreasabel** [comment]
On a first glance, it looks like we reach a projection despite `unSpine` because it has no effect on level expressions.  We could either also call `reallyUnLevelView` before `unSpine` or deal with projections in `occurrences` (needs investigation).

**Comment by jespercockx** [comment]
Thanks!
