### ISSUE TITLE
Build fails using cpphs in some locale environments

### ISSUE THREAD

**Issue by ghost** [agda/agda#2112]
On Ubuntu, with GHC 7.10.3, `cabal install Agda` fails with:

```
Resolving dependencies...
Downloading Agda-2.5.1.1...
Configuring Agda-2.5.1.1...
Building Agda-2.5.1.1...
Failed to install Agda-2.5.1.1
Build log ( /home/tom/.cabal/logs/Agda-2.5.1.1.log ):
[1 of 1] Compiling Main             ( /tmp/cabal-tmp-10744/Agda-2.5.1.1/dist/setup/setup.hs, /tmp/cabal-tmp-10744/Agda-2.5.1.1/dist/setup/Main.o )
Linking /tmp/cabal-tmp-10744/Agda-2.5.1.1/dist/setup/setup ...
Configuring Agda-2.5.1.1...
Building Agda-2.5.1.1...
Preprocessing library Agda-2.5.1.1...
cpphs: src/full/Agda/Auto/Auto.hs: hGetContents: invalid argument (invalid byte sequence)
cabal: Error: some packages failed to install:
Agda-2.5.1.1 failed during the building phase. The exception was:
ExitFailure 1
```

This is the same with and without the addition to `.cabal/config` suggested in the README under "Note on GHC's CPP language extension".

Thanks for any help.

**Comment by jespercockx** [comment]
I had the same problem but I thought it was something specific to my system. I solved the problem by changing the locale (locally) to C.UTF-8 by running the command `LANG=C.UTF-8`. 

Since there's now at least two people with this problem we should probably investigate why cpphs doesn't like other locales.

**Comment by ghost** [comment]
That also works for me!  Thanks a lot.

I should say that I'm running a [chroot](https://github.com/dnschneid/crouton/), which might mean I have a funny setup or something.  My locales are `en_GB.UTF-8` normally.

**Comment by asr** [comment]
@tswilkinson and @jespercockx using your default locale and removing `cpphs` works? That is, could you install Agda using

```
cabal install -f -cpphs Agda
```

?

**Comment by asr** [comment]
No feedback and I couldn't reproduce the issue using `LANG=en_GB.UTF-8`. Please reopen if necessary.

**Comment by nad** [comment]
```
$ file src/full/Agda/Auto/Auto.hs
src/full/Agda/Auto/Auto.hs: C source, UTF-8 Unicode text
$ LC_CTYPE=sv_SE.UTF-8 cpphs -Isrc/full src/full/Agda/Auto/Auto.hs > /dev/null
$ LC_CTYPE=C cpphs -Isrc/full src/full/Agda/Auto/Auto.hs > /dev/null
cpphs: src/full/Agda/Auto/Auto.hs: hGetContents: invalid argument (invalid byte sequence)
```

I guess that `cpphs` uses the standard, locale-aware methods to read files. I think all of our source files use the UTF-8 character encoding, so the problem can perhaps be solved by setting `LC_CTYPE` to `<something>.UTF-8` before invoking `cpphs`, for some locale `<something>.UTF-8` that is installed. However, I would not be surprised if it is impossible to do this in a system-independent way. Perhaps it would be better to add a `--utf8` flag to `cpphs`.

**Comment by asr** [comment]
A smaller test case:

```
$ cat Test.hs
module Main where

main = putStrLn "∀"
```

```
$ LC_CTYPE=C cpphs Test.hs > /dev/null
cpphs: Test.hs: hGetContents: invalid argument (invalid byte sequence)
```

**Comment by asr** [comment]
I just filed [this](https://github.com/malcolmwallace/cpphs/issues/6) cpphs issue.
