### ISSUE TITLE
Rendering of agda code in user-manual

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2113]
It would be nice if the Agda-processed code blocks in the rst files of the user manual would be highlighted with the Agda LaTeX backend.

To this end, parametrize the html backend to generate .html.rst.  Rst knows raw html code in this form

```
.. raw: html

  <indented html code>
```

Then, when running the user-manual-test we also generate this .html.rst, and use this as input to Sphinx.

Also, we need to distinguish Comment coming from non-code blocks and Comment coming from comments inside code blocks.

**Comment by vlopezj** [comment]
Keeping in mind that we also want to generate documentation in other formats (at least `.pdf`), I see two ways of going at it.

## Embed raw HTML, LaTeX, etc...

This involves adding a raw block for each supported back end, with an additional "catch-all". For example, one for HTML, one for LaTeX, and one for the rest, with a hacky way of hiding it from both the HTML and the LaTeX back ends.

_Input_

```
.. code:: agda

   data Bool : Set where 
     true false : Bool
```

_Output_

```
..raw:: html
  <!-- generated by Agda compiler -->
  <pre>
    <span class="kw">data</span> <span class="ty">Bool</span> …
  </pre>

..raw:: latex
  %% generated by Agda compiler
  \begin{code}
   \kw{data}  \ty{Bool} \kw{:} …
  \end{code}

..raw:: html
  <div style="display: none">

..raw:: latex
  \begin{hidden}

.. code:: agda

   data Bool : Set where 
     true false : Bool

..raw:: html
  </div>

..raw:: latex
  \end{hidden}
```

## Use a native parsed-literal block

  Another option is to use Sphinx's [inline roles](http://stackoverflow.com/questions/9698702/custom-css-styles-in-sphinx) inside a [parsed-literal](http://docutils.sourceforge.net/docs/ref/rst/directives.html#parsed-literal-block) block.

  _Input:_

```
  .. code-block: agda

     data Bool : Set where 
       true false : Bool
```

  _Output:_

```
  .. parsed-literal:

     :kw:`data` :ty:`Bool` :kw:`:` :ty:`Set` …
```

This requires a way of generating RST from Agda, including escaping possibly conflicting characters from the code.  

# Client- vs server-side rendering

At the moment the documentation is generated both by Travis and by the `readthedocs.org` servers. If we complicate the syntax-highlighting process, we will need to submit the modified files to `readthedocs.org` somehow. We have discussed two possible ways.
1. Have the contributor generate the files locally and commit them to the repo. The Travis integration build would check that the submitted files actually correspond to the source files (similar to a regression test). This is easy to implement, but has the disadvantage that writing the documentation requires the user to be to build and run the latest version of Agda on their computer; even for fixing a single typographic error.
2. Have the Travis build generate the files on each integration build and push them to a separate repo. It saves the user from compiling locally at the cost of some delay (1-2h) between the repo and the user manual. The key for Travis to upload the generated documentation to the separate repo would be  [encrypted](https://docs.travis-ci.com/user/encryption-keys/).

**Comment by phile314** [comment]
The raw-\* approach would make sure that we always get exactly the same highlighting as with the Agda backend itself, right? I assume this would be harder to ensure for the parsed literal approach?

For rendering, requiring people to locally compile the source files sounds unhandy. Also, this would make it much harder to do pull requests for new contributors. Using Travis for that sounds much better/practical. We also don't necessarily have to use Readthedocs.org, e.g. Github pages would also be a possibility.

**Comment by andreasabel** [comment]
Changing the documentation does anyway require to run

```
make user-manual-test
```

thus, the documentor needs to have a source installation of Agda.  
Maybe not for fixing a single typographic error.  (But that one could be fixed in the generated file manually also, when it comes down to it.)

**Comment by vlopezj** [comment]
@andreasabel Yes. But right now one can simply make a pull request and have Travis run  `make user-manual-test`, without having to install the source version locally.

@phile314 
It is possible to match the highlighting style by using the same stylesheet/TeX sty macro files with some modifications:
- For HTML, the classes must be `lower-case-names-with-dashes` instead of `CamelCase`. 
- For TeX, the commands are of the form  `\DUroleagda-xxxxx` instead of `\AgdaXxxxx`.

Here's a more careful comparison:

## Original code

``` agda
  -- Natural number type                                                        

  data ℕ : Set where                                                            
    zero : ℕ                                                                    
    suc  : ℕ → ℕ        
```

## RST `parsed-literal` encoding

``` rst
   .. role:: agda-comment                                                          
   .. role:: agda-keyword                                                          
   .. role:: agda-symbol                                                           
   .. role:: agda-primitive-type                                                   
   .. role:: agda-datatype                                                         
   .. role:: agda-inductive-constructor  
   :agda-comment:`-- Natural number type`                                       

   :agda-keyword:`data` :agda-datatype:`ℕ` :agda-symbol:`:` :agda-primitive-type:`Set` :agda-keyword:`where`
     :agda-inductive-constructor:`zero` :agda-symbol:`:` :agda-datatype:`ℕ`     
     :agda-inductive-constructor:`suc`  :agda-symbol:`:` :agda-datatype:`ℕ` :agda-symbol:`→` :agda-datatype:`ℕ`
```

~                                   

## HTML from `parsed-literal`

``` html
<pre class="literal-block">
<span class="agda-comment">-- Natural number type</span>

<span class="agda-keyword">data</span> <span class="agda-datatype">ℕ</span> <span class="agda-symbol">:</span> <span class="agda-primitive-type">Set</span> <span class="agda-keyword">where</span>
  <span class="agda-inductive-constructor">zero</span> <span class="agda-symbol">:</span> <span class="agda-datatype">ℕ</span>
  <span class="agda-inductive-constructor">suc</span>  <span class="agda-symbol">:</span> <span class="agda-datatype">ℕ</span> <span class="agda-symbol">→</span> <span class="agda-datatype">ℕ</span>
</pre>
```

## HTML from Agda backend

``` html
    <pre><a id="1" name=
    "1">\begin{code}                                                             
  </a><a class="Comment" id="16" name="16">-- Natural number type</a><a id="38"
name=
"38">                                                                         

  </a><a class="Keyword" id="42" name="42">data</a><a id="46" name=
"46"> </a><a class="Datatype" href="sandbox-latex.html#47" id="47" name=
"47">&#8469;</a><a id="48" name="48"> </a><a class="Symbol" id="49" name=
"49">:</a><a id="50" name="50"> </a><a class="PrimitiveType" id="51" name=
"51">Set</a><a id="54" name="54"> </a><a class="Keyword" id="55" name=
"55">where</a><a id="60" name=
"60">                                                                         
    </a><a class="InductiveConstructor" href="sandbox-latex.html#65" id="65"
name="65">zero</a><a id="69" name="69"> </a><a class="Symbol" id="70" name=
"70">:</a><a id="71" name="71"> </a><a class="Datatype" href=
"sandbox-latex.html#47" id="72" name="72">&#8469;</a><a id="73" name=
"73">                                                                         
    </a><a class="InductiveConstructor" href="sandbox-latex.html#78" id="78"
name="78">suc</a><a id="81" name="81">  </a><a class="Symbol" id="83" name=
"83">:</a><a id="84" name="84"> </a><a class="Datatype" href=
"sandbox-latex.html#47" id="85" name="85">&#8469;</a><a id="86" name=
"86"> </a><a class="Symbol" id="87" name="87">&#8594;</a><a id="88" name=
"88"> </a><a class="Datatype" href="sandbox-latex.html#47" id="89" name=
"89">&#8469;</a><a id="90" name=
"90">                                                                         
\end{code}                                                                      
</a></pre>
```

## TeX from `parsed-literal`

``` tex
\begin{alltt}
\DUrole{agda-comment}{-- Natural number type}

\DUrole{agda-keyword}{data} \DUrole{agda-datatype}{ℕ} \DUrole{agda-symbol}{:} \DUrole{agda-primitive-type}{Set} \DUrole{agda-keyword}{where}
  \DUrole{agda-inductive-constructor}{zero} \DUrole{agda-symbol}{:} \DUrole{agda-datatype}{ℕ}
  \DUrole{agda-inductive-constructor}{suc}  \DUrole{agda-symbol}{:} \DUrole{agda-datatype}{ℕ} \DUrole{agda-symbol}{\(\rightarrow\)} \DUrole{agda-datatype}{ℕ}
\end{alltt}
```

## TeX from Agda backend

``` tex
\begin{code}%                                                                   
\>[0]\AgdaIndent{2}{}\<[2]%                                                     
\>[2]\AgdaComment{-- Natural number type}\<%                                    
\\                                                                              
%                                                                               
\\                                                                              
\>[0]\AgdaIndent{2}{}\<[2]%                                                     
\>[2]\AgdaKeyword{data} \AgdaDatatype{ℕ} \AgdaSymbol{:} \AgdaPrimitiveType{Set} \AgdaKeyword{where}\<%
\\                                                                              
\>[2]\AgdaIndent{4}{}\<[4]%                                                     
\>[4]\AgdaInductiveConstructor{zero} \AgdaSymbol{:} \AgdaDatatype{ℕ}\<%         
\\                                                                              
\>[2]\AgdaIndent{4}{}\<[4]%                                                     
\>[4]\AgdaInductiveConstructor{suc} \<[9]%                                      
\>[9]\AgdaSymbol{:} \AgdaDatatype{ℕ} \AgdaSymbol{→} \AgdaDatatype{ℕ}\<%         
\end{code}
```

**Comment by asr** [comment]
Generally speaking to solve a problem locally it's more easy than to solve a problem in Travis. Moreover, the local installation shouldn't _too_ complicate and we can help if necessary.
