### ISSUE TITLE
Generated implicit lambdas don't line up with implicit function types.

### ISSUE THREAD

**Issue by effectfully** [agda/agda#2118]
```
open import Reflection

id : {A : Set} -> A -> A
id x = x

macro
  m₁ : Term -> TC _
  m₁ = unify (quoteTerm id)

id₁ : {A : Set} -> A -> A
id₁ = m₁
-- This results in unsolved metas.
-- Sort _9
-- _A_12 : Set _9

macro
  m₂ : Term -> TC _
  m₂ ?r = unify ?r (quoteTerm id)

id₂ : {A : Set} -> A -> A
id₂ = m₂
-- This is an error.
-- Found an implicit lambda where an explicit lambda was expected
-- when checking that the expression λ {A} → λ x → x has type .A → .A
```

Agda version 2.6.0

**Comment by UlfNorell** [comment]
The reason for the different behaviours is that `unify` is not commutative. It will infer the type of the first argument and then check the second argument against that type. You can demonstrate the different behaviours without using reflection:

``` agda
m₁ = λ {A} x → x

id₁ : {A : Set} → A → A
id₁ = m₁  -- unsolved metas

id₂ : {A : Set} → A → A
id₂ = λ {A} x → x -- error
```

**Comment by effectfully** [comment]
I meant to say it's strange for me that quoting-unquoting is not an identity transformation: `id₁ = id` type checks, but `id₁ = m₁` doesn't despite `m₁` being essentially `id`.

**Comment by UlfNorell** [comment]
I guess it's the normalisation that gets in the way again. `id₁ = id` means `id₁ {A} = id {A}`, but when you say `id₁ = m₁` you get `id₁ {A} = λ {A} x → x` which is an error.
