### ISSUE TITLE
Missing support for haskell-src-exts 1.18

### ISSUE THREAD

**Issue by asr** [agda/agda#2121]
I'm working on this issue...

In haskell-src-exts (HSE) < 1.18 there are annotated and non-annotated modules. In HSE 1.18, the non-annotated modules were _replaced_ by the annotated ones which were removed.

Agda uses the non-annotated modules.

For supporting HSE 1.18, we need 

i) to use the annotated types instead of the non-annotated ones

and for supporting both "versions" of HSE, we need

ii) to use some CPP conditionals.

For step i) I'm writing a wrapper module where I define the annotated types using a dummy type. For example with HSE 1.17 , I define the `Exp` type in this way

``` haskell
module Agda.Compiler.MAlonzo.HSE
  ( Dummy
  , Exp
  ) where

import qualified Language.Haskell.Exts.Annotated.Syntax as HSE

type Dummy = String
type Exp   = HSE.Exp Dummy
```

Since we _cannot_ define type synonymous for data constructors, I cannot use the above approach on them.

Any ideas for defining and exporting the data constructors of `Exp` parametrised with the  `Dummy` type?

**Comment by phile314** [comment]
Do we need to support HSE 1.17? HSE 1.18 didn't introduce any new dependencies as far as I can see, so why not just bump the lower bound? That way we don't need any CPP.

**Comment by asr** [comment]
I no see any reason for supporting HSE 1.17. The support for this version of HSE would be handle in the step ii) in the OP. That is, a solution to the question in the OP it is necessary even if we don't support HSE 1.17.

**Comment by phile314** [comment]
Ah yes, I missed that, thanks.

(Bidirectional) Pattern Synonyms could be an elegant solution for the data constructor problem? The only problem is that they are not available in GHC 7.6.

**Comment by asr** [comment]
From a previous discussion (see #1972),  it seems we will support GHC 7.6 for a while.

**Comment by asr** [comment]
For more clarity, I edited the OP.

**Comment by asr** [comment]
A nice solution could be to use the new [haskell-src-exts-simple](https://hackage.haskell.org/package/haskell-src-exts-simple) library. Unfortunately, this library [doesn't support GHC < 7.10](https://github.com/int-e/haskell-src-exts-simple/blob/2353fefc16508458225f8e45c4da3a46eb633603/COMPATIBILITY.md#ghc-versions).

**Comment by asr** [comment]
FYI, Agda has been disabled from Stackage nightly due to this issue.

**Comment by nad** [comment]
> ```
> type Dummy = String
> type Exp   = HSE.Exp Dummy
> ```

Why not simply `type Exp = HSE.Exp ()`?

> Any ideas for defining and exporting the data constructors of `Exp` parametrised with the `Dummy` type?

We can define wrappers: `var = HSE.Var ()`. This won't work in patterns, but there we can insert underscores.

**Comment by asr** [comment]
Thanks! The commits fixing this issue should be released with 2.5.1.2. I'll  cherry-pick them into release-2.5.1.

**Comment by UlfNorell** [comment]
Might be some tricky merging, but that sounds like a good idea. Do we need to do anything to get stackage nightly to pick us up again?

**Comment by asr** [comment]
> Do we need to do anything to get stackage nightly to pick us up again?

The only option is to make the release because Stackage only picks up packages for Hackage.

**Comment by asr** [comment]
I'll close the issue after merging.

**Comment by asr** [comment]
2.5.1.2 won't support Stackage, so merging it's not necessary.
