### ISSUE TITLE
Segmentation fault at run-time in Agda 2.5.1.1

### ISSUE THREAD

**Issue by mechvel** [agda/agda#2123]
This is on  Agda 2.5.1.1, ghc-7.10.2, MAlonzo, Debian Linux (64 bit).
Please, download this small program from 

http://www.botik.ru/pub/local/Mechveliani/agdaNotes/bug-jul28-2016.zip 

`main' prints to string and to output a certain data element  [0].
Instead ,the commands

> agda -c $agdaLibOpt Main.agda
> ./Main

yield
  Segmentation fault

**Comment by mechvel** [comment]
Here is a smaller example:

http://www.botik.ru/pub/local/Mechveliani/agdaNotes/bug-jul30-2016.zip

**Comment by UlfNorell** [comment]
Minimized test case:

``` agda
open import Agda.Builtin.Nat
open import Agda.Builtin.String
open import Agda.Builtin.IO
open import Agda.Builtin.Unit

data ⊥ : Set where

record Pair : Set where
  constructor _,_
  field fst snd : String

open Pair

record ERing : Set where
  field divRem : (⊥ → ⊥) → Pair

open ERing

eRing : ERing
eRing = record{ divRem = λ _ → "fst" , "snd" }

test : String
test = snd (divRem eRing (λ ()))

postulate
  putStrLn : String → IO ⊤
{-# IMPORT Data.Text.IO #-}
{-# COMPILED putStrLn Data.Text.IO.putStrLn #-}

main : IO ⊤
main = putStrLn test
```

**Comment by UlfNorell** [comment]
For some mysterious reason the compiler thinks that the `Pair` type is erasable. Investigating...
