### ISSUE TITLE
Cannot split when defining irrelevant function (+ bad error message)

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#2126]
An example:

```
open import Agda.Builtin.Bool

.test : Bool → Bool
test x = {!x!}
```

Trying to split on x gives the following error message:

```
Right hand side must be a single hole when making a case
distinction
when checking that the expression ? has type Bool
```

I would expect the splitting to succeed (manually doing the split works), or at least an error message that makes more sense.

**Comment by andreasabel** [comment]
This simply works for me both on 2.6.0 and 2.5.2, cannot reproduce...

**Comment by jespercockx** [comment]
Sorry, this must've been a result of not cleaning up properly after an experiment. Recompiling Agda fixed it for me.
