### ISSUE TITLE
internal error at src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs:1356

### ISSUE THREAD

**Issue by ghost** [agda/agda#2127]
```
data Test : Set where
  field
    a : a
    b : b
```

This illegal data type declaration triggers an internal error in Agda 2.5.1:
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs:1356

**Comment by andreasabel** [comment]
Once upon a time, the parser ensured that inside a `data` declaration there can only be type-signatures.  In the mean time, the parser has been relaxed (for `instance`), but the scope checker still relied on this invariant.

Fixed, should give a proper error now.
