### ISSUE TITLE
`quoteTerm` loses information.

### ISSUE THREAD

**Issue by effectfully** [agda/agda#2133]
```
open import Data.List.Base
open import Reflection

data D₁ : Set where
  C₁ : D₁

data D₂ {c₁ : D₁} : Set where
  C₂ : D₂ {c₁}

d₂ : D₂ {C₁}
d₂ = C₂

qd₂ = quoteTerm d₂
```

`qd₂` evaluates to `con (quote C₂) (arg (arg-info hidden relevant) unknown ∷ [])` instead of `con (quote C₂) (arg (arg-info hidden relevant) (con (quote C₁) []) ∷ [])`.

**Comment by andreasabel** [comment]
You will have to try to get @UlfNorell 's attention to fix the reflection bugs...

**Comment by UlfNorell** [comment]
This one is working as intended as far as I can see. Data constructors don't store the data type parameters and the only reason you get the any argument at all is to make sure that any implicit proper arguments to the constructor get the correct position (since we don't have named implicits in the reflected syntax).

It would be possible to reconstruct the parameters, but not without a potential exponential blowup of the reflected terms.

**Comment by effectfully** [comment]
> This one is working as intended as far as I can see.

I spent two hours trying to understand "where the hell this unsolved meta comes from", so, as a user, I would characterize this behaviour as at least surprising. Maybe it's worth adding a line somewhere in the documentation that says that `inferType d₂` doesn't return the type of `d₂`.

**Comment by UlfNorell** [comment]
Yeah. The problem is that terms are normalised before being reflected so `inferType d₂` is the same as `inferType C₂` without the argument to `C₂`.

I'll add a note to the reflection documentation.

**Comment by UlfNorell** [comment]
Also note that `inferType (quoteTerm d₂)` gives yellow, but `inferType (def (quote d₂) [])` does infer the correct type.

**Comment by mietek** [comment]
> The problem is that terms are normalised before being reflected

This is surprising, given the purpose of `QUOTE` in Lisp.  Could you explain the rationale for this design decision?

**Comment by UlfNorell** [comment]
The purpose is to make the result stable under minor changes to the order of type checking. Depending on the order in which metavariables are solved you might end up with syntactically different solutions to a particular meta, but which nevertheless normalise to the same term.

**Comment by mietek** [comment]
@UlfNorell: Thank you for the answer. Could you clarify whether is it at all possible to use Agda’s reflection facilities to distinguish between two terms that have the same normal form?

For comparison, here’s what happens in Idris:

``` idris
> `((\n => 1 + 2) : Nat -> Nat) == `((\n => 3) : Nat -> Nat) 
False : Bool
```

**Comment by UlfNorell** [comment]
> Could you clarify whether is it at all possible to use Agda’s reflection facilities to distinguish between two terms that have the same normal form?

No, I don't believe so. Can you explain what it is you want to do when you need this?

**Comment by mietek** [comment]
@UlfNorell: Thanks.  Right now, my question is mostly out of curiosity.  I don’t have a concrete use case yet.  I’m looking into type theories which would allow such things.

**Comment by andreasabel** [comment]
http://repository.cmu.edu/cgi/viewcontent.cgi?article=2236&context=compsci
That would be a type theory which treats quoted code only up to alpha-equality, not beta.

**Comment by mietek** [comment]
It seems that this issue has been fixed at [AIMXXIV](http://wiki.portal.chalmers.se/agda/pmwiki.php?n=Main.AIMXXIV):

> NAD/UN: Don’t normalize before quoting. (1h code sprint) — Done! Turned out to require some parameterization on whether we should normalize or not.

When can we expect this fix to make its way to a release?

**Comment by UlfNorell** [comment]
The plan is to release stable in the semi-near future. No dates set or anything though.

**Comment by L-TChen** [comment]
> http://repository.cmu.edu/cgi/viewcontent.cgi?article=2236&context=compsci
> That would be a type theory which treats quoted code only up to alpha-equality, not beta.

Hi, @andreasabel do you remember to which paper you were referring? The link is invalid. Given my knowledge, it might be something about staged computation, contextual (modal) type theory, or both? 

I am using Agda's reflection framework to implement a typed meta-language for Agda, but elaborator reflection does not seem well-understood type-theoretically yet. 

(We may have another issue ticket on the semantics-side of this if it is the case.)

**Comment by mietek** [comment]
@L-TChen, that was Frank Pfenning’s [“Intensionality, Extensionality, and Proof Irrelevance in Modal Type Theory”](https://www.cs.cmu.edu/~fp/papers/lics01.pdf).

It would be interesting to exchange notes.  Join us in [##dependent](https://www.irccloud.com/invite?channel=%23%23dependent&hostname=irc.freenode.net&port=6697&ssl=1) on Freenode IRC?
