### ISSUE TITLE
Question: _+-mono_ for Integer

### ISSUE THREAD

**Issue by mechvel** [agda/agda#2139]
Nat and Bin are supplied with a proof for  _+-mono_,  
but  I do not find such for Integer.
(?)

**Comment by UlfNorell** [comment]
Did you mean to file this on the standard library repository?

**Comment by mechvel** [comment]
On Fri, 2016-08-12 at 03:26 -0700, Ulf Norell wrote:

> Did you mean to file this on the standard library repository?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

I mean a suggestion for Standard library.
If it has not  _+-mono_  for Integer, it would is very natural to add it
there.
Because  Nat and Bin  have such.

---

Sergei

**Comment by UlfNorell** [comment]
Feel free to submit a pull request to the [standard library repo](https://github.com/agda/agda-stdlib). This is the repo for the Agda implementation.
