### ISSUE TITLE
agda-mode: Highlight operators in fixity declarations

### ISSUE THREAD

**Issue by ghost** [agda/agda#2140]
_∧_ : 𝔹 → 𝔹 → 𝔹
infixr 6 _∧_
tt ∧ b = tt
ff ∧ b = ff

The _∧_ in the fixity declaration will not be highlighted like an operator.

Near as I can tell, the highlight code just figures out that infixr is a keyword, and that 6 is a number, before going -_o_\- at the actual operator.

**Comment by andreasabel** [comment]
For Agda, the name `+` is different from the name `_+_`.  The latter can be used infix, but not the former.  Here you go:

``` agda
data 𝔹 : Set where tt ff : 𝔹

_∧_ : 𝔹 → 𝔹 → 𝔹
infixr 6 _∧_
tt ∧ b = tt
ff ∧ b = ff
```

Agreed, Agda could be a bit more helpful here in its error message.

Agreed II, the operator should be highlighted.

**Comment by ghost** [comment]
I'm sorry, this was simply a paste gone wrong -- the paste should have been precisely what you wrote. I don't know how that went wrong.

The only issue I wanted to report was the operator highlighting issue.

**Comment by andreasabel** [comment]
Ah, ok.
Yes, some markup uses underscores for underline or bold, so things could have become muddled up by cut-and-paste.

**Comment by andreasabel** [comment]
To fix this problem, the `Fixity` constructor should also store the `Range` of the operator name. Then, the highlighter can extract the necessary information when walking over `Syntax.Abstract.Declarations`.

**Comment by ghost** [comment]
I would be willing (and interested!) to work on this if someone could give me some pointers. Could we talk on IRC, XMPP, or similar? If not, and if you have the time, any pointers in here would be helpful. I assume you are talking about adding operatorRange :: Range to the data Fixity of src/full/Agda/Syntax/Fixity.hs, and then doing something to Abstract.hs -- but I haven't done anything with the Agda src yet.

**Comment by andreasabel** [comment]
Good!  On the way from `Syntax.Concrete` (from the `Parser.y`) to `Syntax.Abstract`, fixity declarations are distributed into `NiceDeclarations` (see `Syntax.Concrete.Definitions`).  Then in `Syntax.Translation.ConcreteToAbstract` the declarations are processed into the `Abstract` declarations, which are later processed in `Interaction.Highlighting.Generate` to extract highlighting information to name.  I guess when looking at an abstract declaration, we could also look at its `Fixity` to extract a second range for the identifier which should be highlighted.
(I am not on IRC etc. and I will be busy next week at the ESSLLI summer school, but maybe this is some initial information that could get you started!? Feel free to ask more questions here.)

**Comment by andreasabel** [comment]
Are you working on this?  If yes, you should assign yourself.  I assume "no".

**Comment by ghost** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On 05/09/16 18:55, Andreas Abel wrote:

> Are you working on this?  If yes, you should assign yourself.  I 
> assume "no".
> Unfortunately, real life intervened, as it has a nasty habit of doing. I
> will look at it when I get the time, but I won't be saddened if someone
> fixes it before me. ;-)
> 
> ---
> 
> Alexander
> alexander@plaimi.net
> https://secure.plaimi.net/~alexander
> -----BEGIN PGP SIGNATURE-----
> Version: GnuPG v2

iQIcBAEBCgAGBQJXzaOyAAoJENQqWdRUGk8B94MP/jLHR8pSntKdIx8D3uhsfh6x
7ejpJJP2/8WwBAStKA3O2sGIpDLuwmA2yG/758HlnmZlUXMONbLLxxcgb1A1MblI
6R1sVzsHr/c939sMIyALoHUc4Ntm89qRCwn8pIAedM/Vb9FLr617qsjLe+goQ80Q
FAmYVromoimSxygp1brCfXg+DrKIbXNl7CahtRP6aEcO0CGKc9dxMwT98AnmDlGc
7hDDxQ5dv0YsCG+LQZWDnnQMRcyfzIPknsLCRMS0eI3esoRXBeIt3P41NvGYRmWf
TRUBnvZbauNXkzUyiXiMwJMjByKiI94rUpdS2ue7szGvOnQZqMPWq+PHUEFXIDP7
OQDD8/GhsP8h4lSaQpyZXnFTzxH7ogmTou4FsCFR5fClh14kGkEnnCLCHML4sWSX
BrUSreb774VvhifFYb/sBOzWtoWHEPchzpscJUhFr6JcsrNr4oZvJYAza80wFUTZ
7YLbBcCglv9+nNe74S3a5jzjj1Kwvbb4cSEWclhaDfeBaFjmikeMEb66ryRMZDXg
adhzCNSjGEkX80ahNVAx1wwx6TAMFNOb4IDevh+4qsl1VZH9MGgT808wQgLrNR2k
1XlqOmH4w0WwfxLL2mqIc6DxYBwdmmbA/i2IrBveACy9E+G/E9Fh2lr1bv1a4Xsw
BY0uaG4V4TmZAXoVPX5M
=arfz
-----END PGP SIGNATURE-----

**Comment by andreasabel** [comment]
In the end, I followed through with the plan, but there are some things I do not understand, like why ranges of names in fixity declarations get imported if they are not serialized.  

Maybe it is good you did not work on this issue after all, with the slightly obscure information flow involved here...

**Comment by ghost** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On 08/09/16 11:19, Andreas Abel wrote:

> Maybe it is good you did not work on this issue after all, with
> the slightly obscure information flow involved here...
> I did have a go, one weekend, but I found it quite difficult to follow
> the Agda src. So most of my time was spent just trying to figure out
> where stuff was.

It would be tremendously valuable if we had a wiki that explains the
overview and layout of the compiler, like GHC does. Something like The
Glasgow Haskell Compiler entry for The Architecture of Open Source
Applications would also be useful.

Anyway, thank you for working on this.

---

Alexander
alexander@plaimi.net
https://secure.plaimi.net/~alexander
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCgAGBQJX0UBEAAoJENQqWdRUGk8BvOcP/Ro2r6TfRW4fb0pq6FJRzRZM
VYzNVnJ+nQIsM1lyj7O6Hn6HcAy7YiUBJTkt4ZJXSFyztX2R/nLJPMExs/kj6fvH
zBZa8SB9wONk2Pjy4ZZQ0VHqXm7UUJmc9pvFASa+5rvRNl3IV5FEK8MWH8oqUAh1
RQUyOpyDV9+1y65UJHPQ7btgSexJkM7GDf3xV4zHULl5SCgpxCs8yJYWshBGWDBw
E5K9iYZ2srl0h3h7xBiKZCR+vcxgO+6FNFfnUTNvI5BzXWj63c+qUnU5FQwYwtki
x8xE+IJ9VRg71fH94h4VHOtPrWZtT9N+uxft1kfQjibAzzPN4EhO6Q3yySQntF6n
kgeHT6mlP5zWgjmg+YXTbro2soCX5dRjbFDypv8m6PLXf0X216N4/Qr2RJjgW205
Thex92LKbA7uhvPVEUIDn1JN9LqRZntnSUMlWlE0J8Sz3NTRtFEXD50aMykjDU5J
qMFvFK0RRadHNPKtsH3OWq326Yg7+O0nnab9ukYTPULvf6dz7hLncQ0+5e06GGmL
/hSqHJxa5vLL+WbPJdW09kwHK58RiNa5kkxjFc74wB9GGaSwIhiSKrmQmQgHrQo6
EG4QZW+/BDEH9FxdOeKe/KsmzNHMNdkSBUzc9+CMMN5TTby606OMKhX+V9buTUB+
/O8+jv4GNkGRibugb+kC
=DySu
-----END PGP SIGNATURE-----
