### ISSUE TITLE
Bad interaction between agda-mode and fill-column-indicator

### ISSUE THREAD

**Issue by ghost** [agda/agda#2142]
Currently C-c C-a is pretty stupid. Install fill-column-indicator, and add the following somewhere:

```
(require 'fill-column-indicator)
(setq fci-rule-color "darkred")
(setq fci-always-use-textual-rule t)

(add-hook 'agda2-mode-hook (lambda ()
                   (fci-mode 1)
                   (setq fci-rule-column 78)
                   (setq-default fill-column 78)
                   'turn-on-auto-fill
                   ))
```

Now you may observe how C-l C-a puts its suggestions on column 79. This is Somewhat Suboptimal.

**Comment by andreasabel** [comment]
Sorry, I don't understand, could you elaborate, please?  `C-l C-a` does nothing Agda-specific on my installation. I am not sure what `C-l` does, but `C-a` just jumps to the first column.

**Comment by ghost** [comment]
Sorry for the lack of info. I also had a typo -- which I have now edited out of my original post. I meant C-c C-a, not C-l C-a. I.e. I am referring to Agsy.

As an example, try:

id : {A : Set} → A → A
id = ?

Now C-c C-l will give you 'id = { }0', and C-c C-a on that will insert 'λ {A} z → z'. If you have the fill-column-indicator configuration I posted in the original post, it will be inserted to the right of the column indicator, rather than exactly in the hole.

**Comment by UlfNorell** [comment]
Is this only `C-c C-a`? Does `C-c C-spc` (give) on `λ {A} z → z` do the right thing? Or `C-c C-r`?

**Comment by andreasabel** [comment]
Issue is stale.
