### ISSUE TITLE
Remembering results of previous "with" statements

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda#2144]
Consider the following minimal example:

```
  open import Algebra.FunctionProperties using (Associative)
  open import Data.Nat using (ℕ; suc; zero; _≟_; _≤?_)
  open import Relation.Binary.PropositionalEquality using (_≡_)
  open import Relation.Nullary using (yes; no)

  _⊔_ : ℕ → ℕ → ℕ
  x ⊔ y with x ≤? y
  ... | yes _ = x
  ... | no  _ = y

  ⊔-assoc : Associative _≡_ _⊔_
  ⊔-assoc x y z with x ≤? y | y ≤? z
  ⊔-assoc x y z | yes _ | yes _ = {!!}
  ⊔-assoc x y z | yes _ | no  _ = {!!}
  ⊔-assoc x y z | no  _ | no  _ = {!!}
  ⊔-assoc x y z | no  _ | yes _ = {!!}
```

To prove `⊔-assoc` it is necessary to prove that `x ⊔ (y ⊔ z) = (x ⊔ y) ⊔ z`. In the first hole, Agda has established that `x ⊔ y = x` and `y ⊔ z = y` and therefore we need to prove that `x ⊔ y = x ⊔ z`.

At this point it feels like that Agda should remember that we've already tested `x ≤? y` and therefore should automatically be able to reduce `x ⊔ y = x ⊔ z` to `x = x ⊔ z`. However at the moment it doesn't seem to do this and in order to complete the proof we have to test `x ≤? y` a second time. 

In more complicated associativity proofs this results in a massive blow-up in the size of the proof and many lines of the form `contradiction x≤y x≰y` where the same test has returned contradictory results.

**Comment by andreasabel** [comment]
Have you already tried the Inspect Pattern?

**Comment by MatthewDaggitt** [comment]
Apologies, I'm not quite sure how you would use the "Inspect Pattern" in this instance. As in?

```
  open import Relation.Binary.PropositionalEquality using (_≡_; inspect; [_])

  ⊔-assoc : Associative _≡_ _⊔_
  ⊔-assoc x y z with x ≤? y | y ≤? z | inspect (x ≤?_) y
  ⊔-assoc x y z | yes _ | yes _ | [ x≤y ] = {!!}
  ⊔-assoc x y z | yes _ | no  _ | _       = {!!}
  ⊔-assoc x y z | no  _ | no  _ | _       = {!!}
  ⊔-assoc x y z | no  _ | yes _ | _       = {!!}
```

Still doesn't pick up on it...

**Comment by andreasabel** [comment]
No, but it gives you an equality **proof** you can use for further rewriting.

**Comment by MatthewDaggitt** [comment]
Ah as in:

```
  ⊔-assoc : Associative _≡_ _⊔_
  ⊔-assoc x y z with x ≤? y | y ≤? z | inspect (x ≤?_) y
  ⊔-assoc x y z | yes _ | yes _ | [ x≤y ] rewrite x≤y = {!!}
  ⊔-assoc x y z | yes _ | no  _ | _       = {!!}
  ⊔-assoc x y z | no  _ | no  _ | _       = {!!}
  ⊔-assoc x y z | no  _ | yes _ | _       = {!!}
```

Thanks! That cuts down on the number of lines (albeit at the cost of making the remaining lines a lot longer) but it definitely makes the proof more intuitive to read! 

I realise that I know almost zilch about the innards of Agda, and I'm sure it's incredibly complicated, but it still feels like intuitively it should be able to remember the results of previous with statements, making proofs like these much cleaner. Maybe its just wishful thinking though!

**Comment by andreasabel** [comment]
I guess `with` is very confusing if you do not understand what it desugars to.  People expect it to work like "smart case" (see #239).  But the wished-for smart case lacks a theoretical foundation...
