### ISSUE TITLE
Unicode syntax for instance arguments

### ISSUE THREAD

**Issue by mietek** [agda/agda#2146]
The documentation states:

> Instance arguments are enclosed in double curly braces `{{ }}`, or their unicode equivalent `⦃ ⦄` (`U+2983` and `U+2984`, which can be typed as `\{{` and `\}}` in the Emacs mode).

Unfortunately, `⦃ ⦄`  is not exactly equivalent to `{{ }}`, because while we are allowed to write `{{F : Foo}}`, we are required to add spaces and write `⦃ F : Foo ⦄`.

Writing `⦃F : Foo⦄` seems more consistent with `(B : Bar)` and `{B : Baz}`.  Can we make these spaces optional?

**Comment by nad** [comment]
> Unfortunately, `⦃ ⦄` is not exactly equivalent to `{{ }}`

I think this was intentional. Another example: Currently Agda parses `\x → e` as a λ-expression, but not `λx → e`.

**Comment by mietek** [comment]
> Currently Agda parses `\x → e` as a λ-expression, but not `λx → e`.

Indeed. I would also like this fixed.

**Comment by WolframKahl** [comment]
On Sat, Aug 20, 2016 at 09:26:18AM -0700, Miëtek Bak wrote:

> > Currently Agda parses `\x → e` as a λ-expression, but not `λx → e`.
> 
> Indeed. I would also like this fixed.

In my opinion, if there is anything that needs fixing here,
then it definitely is the fact that

> Currently Agda parses `\x → e` as a λ-expression

Agda is designed for use with predominantly multi-symbol (including multi-letter)
identifiers (and mixfix operator name parts), and in such a context,
I consider it healthy to put spaces between tokens almost everywhere,
just as Agda demands.
(Many mathematical notational conventions grew in a context of
 ONLY single-symbol identifiers, and in my opinion just do not scale
 to a setting with multi-symbol identifiers.
 And even with Unicode, a restriction to single-symbol identifiers
 does not scale to the kinds of uses we have for Agda.
)

However, I have so far never felt tempted to use backslash in a name part in Agda,
so I probably won't notice if this is fixed, nor if this remains unfixed.

 ;-)

Wolfram

**Comment by andreasabel** [comment]
Yes, I think the exception for `\x -> e` should not have been there in the first place.

**Comment by mietek** [comment]
This reminds me: could we have `@` available for use?

**Comment by UlfNorell** [comment]
`@` is used for [as-patterns](http://agda.readthedocs.io/en/latest/language/function-definitions.html#as-patterns).

**Comment by andreasabel** [comment]
I close this one.  The only thing one could pursue here is change the parsing of `\x -> e`.  If someone wishes to do this, he can reuse this issue and change the title, or open a new one.

**Comment by nad** [comment]
> The only thing one could pursue here is change the parsing of `\x -> e`.

I don't think we should do this, because it might break existing code.

**Comment by mietek** [comment]
So, that’s a no on making `⦃F : Foo⦄` more consistent with `(B : Bar)` and `{B : Baz}`?

**Comment by andreasabel** [comment]
@nad Why did you think this difference is intentional?

**Comment by nad** [comment]
> So, that’s a no on making `⦃F : Foo⦄` more consistent with `(B : Bar)` and `{B : Baz}`?

Yes.

> Why did you think this difference is intentional?

I don't know whether it was intentional or not, but given that lambdas are treated in an analogous way I suspect that it was.

**Comment by UlfNorell** [comment]
The difference is intentional. We're trying to keep the number of reserved characters (i.e. characters that cannot be part of a name) to a minimum. I believe they are `(){};.@`. By requiring space around the unicode instance brackets we don't have to add them to the list.

The special treatment of `\` was a mistake, I was seduced by an unwillingness to offend Haskell programmers. I think it's too late to fix that now though.

**Comment by xekoukou** [comment]
Given that the parser does not give a good error message, people can be confused with the difference between ```\{{``` and ```{{```. It should definitely be put in the documentation on the instance arguments section.
