### ISSUE TITLE
Option to use use `stack exec` for GHC backend

### ISSUE THREAD

**Issue by CarstenKoenig** [agda/agda#2148]
as far as I can tell you use `ghc` for the Haskell (MAlonzo?) backend right now (https://github.com/agda/agda/blob/ffe322de865ec2388ec72d0f37ffd00fcfcde6fb/src/full/Agda/Compiler/MAlonzo/Compiler.hs)

Now when I want to try [Ulf Norells summer school examples](https://github.com/UlfNorell/agda-summer-school) (using 2.4.2.4) I have to grab and install the `agda-ffi` [here](https://github.com/UlfNorell/agda-prelude/tree/compat-2.4.2) into the global package repository (`cabal install ...`).

Now it would be nice if I could just install this using `stack` but of course that will only work if the backend would compile the files with something like `stack exec -- ghc ...` instead (assuming correct `stack.yaml` etc.)

Maybe instead of the fixed `compiler = "ghc"` in the file I linked above we could have a configurable (emacs agda2-group?) value instead?

**Comment by UlfNorell** [comment]
FWIW you no longer need `agda-ffi` (since Agda-2.5.1).

A flag to customize the call to ghc would make sense though.

**Comment by gallais** [comment]
I think this was solved at the same time as #3840.
