### ISSUE TITLE
Add TC primitive to check left-hand side

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#2151]
What are the requirements on `normalise` in the reflection API? It seems to behave extremely strangely. I'm not crafting any terms myself directly, just using stuff already obtained from reflection, and using `normalise` on these terms sometimes works and sometimes causes all sorts of strange errors--everything from complaining about dubruijn indexes not being in scope to unsolved metas to stuff that looks like regular type errors.

It's strange to me that this happens, since these are all terms or subterms of code which Agda happily compiles.

What I need is just some way to beta reduce terms, choosing high-value names to inline. I thought that's what `normalise` would help me do, but I'm having a lot of issues with it.

For what it's worth, the vast majority of issues seem to be coming from `pat-lam` clauses. The bodies there seem to be in odd shapes compared to terms elsewhere.

**Comment by UlfNorell** [comment]
Can you give some concrete examples?

Some problems are likely due to the fact that normalise needs to infer the type of the term to be normalised. You can use `checkType` instead, which also returns the normal form but takes the expected type as an argument.

**Comment by identicalsnowflake** [comment]
Ok, I didn't know I could use `checkType` like that. I think I always have the types handy, so this should work fine.

As for examples, I can at least give you a partial example which will demonstrate my issue. Look at these two definitions:

``` agda
nicelyReduces : Maybe (List ⊤)
nicelyReduces = pure nothing >>= id

pathological : Bool → Maybe (List ⊤)
pathological true = nothing
pathological b = pure nothing >>= id
```

When I reflect `nicelyReduces`, the result I get is already normalised (I don't even need to pass it through `normalise`) -- all the fancy implicits and "typeclass" resolution via instance arguments, etc., is correctly absent in the reflected term. The term is maybe 40 characters long total.

But `pathological` has the same definition in its second clause, and a trivial first clause, and yet when I reflect it, the term I get is enormous -- over 500 lines in my emacs buffer!

Perhaps this is this issue already--perhaps `pathological` is supposed to be normalised when it's reflected just like `nicelyReduces`?

But in any case, my reaction was "well that's ridiculous, let me just pass it through normalise!" So I just tack on a `>>= normalise` to my reflection macro. I get an error, something about constraints, but thanks to your above recommendation to use `checkType`, I'll try that instead!

And hey, no error! Buuut... I get the same term back. Still 500+ lines of stuff, no reduction.

**Comment by UlfNorell** [comment]
> But pathological has the same definition in its second clause, and a trivial first clause, and yet when I reflect it, the term I get is enormous -- over 500 lines in my emacs buffer!

How exactly are you reflecting it? When I use `getDefinition` on `pathological` I get a definition with a sensible (but not normalised) right-hand side. Calling normalise on the right-hand side works as expected.

**Comment by identicalsnowflake** [comment]
When I say I'm "reflecting a term", I'm doing this:

``` agda

defToTerm : Name → Definition → List (Arg Term) → Term
defToTerm _ (function cs) as = pat-lam cs as
defToTerm _ (constructor′ d) as = con d as
defToTerm _ _ _ = unknown

derefImmediate : Term → TC Term
derefImmediate (def f args) = getDefinition f >>= λ f' → pure (defToTerm f f' args)
derefImmediate x = pure x

reflectTerm : TC Term
reflectTerm = (quoteTC (Bool → Maybe (List ⊤))) >>= λ ty → quoteTC pathological >>= derefImmediate >>= λ x → checkType x ty

macro
  reflect : Term → TC ⊤
  reflect a = reflectTerm >>= quoteTC >>= unify a

result : Term
result = reflect

```

> When I use getDefinition on pathological I get a definition with a sensible (but not normalised) right-hand side.

Sensible, yes: it's not corrupting the term or anything. But why does `nicelyReduces` reduce to normal form when the exact same expression in `pathological` does not? And for me, my `pure` and `>>=` entail proofs of all the laws, so this unreduced form is enormous!

> Calling normalise on the right-hand side works as expected.

You mean on the resulting `pat-lam`? For me it doesn't change the term at all. If you mean breaking apart the clauses, reducing the bodies, and putting them back together, trying to get that to work is what caused me to create this issue in the first place :)

Here's how I'm trying to do that:

``` agda
reduceClause : Clause → TC Clause
reduceClause (clause ps t) = clause ps <$> normalise t
reduceClause (absurd-clause ps) = pure (absurd-clause ps)

reducePatLam : Term → TC Term
reducePatLam (pat-lam cs args) = sequence (reduceClause <$> cs) >>= λ cs' → pure (pat-lam cs' args)
reducePatLam t = pure t
```

But when I reflect `pathological` and bind it to `reducePatLam`, the type checker complains (in this case, something about Sort _663, but it can be practically anything).

It's frustrating because I _know_ this term can be reduced without any extra information because it's already being done in `nicelyReduces`.

**Comment by UlfNorell** [comment]
Ah, I see now. Pattern lambdas don't reduce. This is not a reflection problem, but just the way they are handled internally. If you define

``` agda
pathological : Bool → Maybe (List ⊤)
pathological = λ where
  true → nothing
  b    → pure nothing >>= id
```

and try to normalise with `C-c C-n pathological`, you get

``` agda
λ { true → nothing ; b → pure nothing >>= id }
```

> ``` agda
> reduceClause : Clause → TC Clause
> reduceClause (clause ps t) = clause ps <$> normalise t
> reduceClause (absurd-clause ps) = pure (absurd-clause ps)
> ```

A potential problem here is that you normalise `t` in the wrong context. Getting the right context could be a bit fiddly though.

To avoid enormous dictionaries you can define instances using copatterns instead of as record expressions.

**Comment by identicalsnowflake** [comment]
> A potential problem here is that you normalise t in the wrong context. Getting the right context could be a bit fiddly though.

Yeah I tried to do that. My strategy to do that for a clause body was to knock out unusued dubruijn indexes, then wrap that result term in `lam`s for each used var, normalise this, then reify back to the original db indexes by flipping the first map.

It actually does work somewhat--at least it worked in a lot more cases than simply trying `normalise` on the body, but it still fails a lot when it can't infer the type, and extracting that information out of the patterns and the original type is hard.

Do you already have machinery for doing some of this? If so, can you expose it? I feel like executing these algorithms in native code would be a good idea anyway, since there's definitely a lot of computation involved.

**Comment by UlfNorell** [comment]
I might be able to get you something like

``` agda
checkLHS : Type → List (Arg Pattern) → (Type → TC A) → TC A
```

where you give a function type and a list of patterns and the continuation gets passed the expected type of the right-hand side and runs in the context computed by the patterns.

**Comment by identicalsnowflake** [comment]
So if I break apart a definition and get a `pat-lam`, I could do `checkLHS topLevelSignature pattern1 (checkType clauseBody1)`? Awesome!

**Comment by UlfNorell** [comment]
That's the idea. I haven't added it yet though :).

**Comment by jespercockx** [comment]
This would be a very nice feature.

**Comment by ghost** [comment]
> Ah, I see now. Pattern lambdas don't reduce. This is not a reflection problem, but just the way they are handled internally. If you define
> 
> ```agda
> pathological : Bool → Maybe (List ⊤)
> pathological = λ where
>   true → nothing
>   b    → pure nothing >>= id
> ```
> 
> and try to normalise with `C-c C-n pathological`, you get
> 
> ```agda
> λ { true → nothing ; b → pure nothing >>= id }
> ```
> 
> > ```agda
> > reduceClause : Clause → TC Clause
> > reduceClause (clause ps t) = clause ps <$> normalise t
> > reduceClause (absurd-clause ps) = pure (absurd-clause ps)
> > ```
> 
> A potential problem here is that you normalise `t` in the wrong context. Getting the right context could be a bit fiddly though.
> 
> To avoid enormous dictionaries you can define instances using copatterns instead of as record expressions.

What's the context that should be used to typecheck/normalize the `t` here?

**Comment by jespercockx** [comment]
We discussed this today at the Agda meeting and another thing that would be very useful would be to *change* the current representation of clauses to include the telescope of the clause, and include debruijn-indices in the pattern variables.

**Comment by jespercockx** [comment]
Is there still a need for a primitive to check the left-hand side or can we close this issue now that we get the clause telescope?

**Comment by UlfNorell** [comment]
I guess so. Reopen otherwise.
