### ISSUE TITLE
PDF version of Language Documentation on readthedocs lacks most Unicode characters

### ISSUE THREAD

**Issue by Araneidae** [agda/agda#2153]
The PDF version of the language documentation available on [readthedocs](https://media.readthedocs.org/pdf/agda/latest/agda.pdf) seems to lack nearly all Unicode characters, for example the code and accompanying narrative on page 6 (for Release 2.6.0) looks extremely odd.

As the [wiki](http://wiki.portal.chalmers.se/agda/ReferenceManual.TOC) directs me straight to [readthedocs](http://agda.readthedocs.org/en/latest) for the language reference, I presume it's the canonical reference point for the documentation...

**Comment by gallais** [comment]
[This seems relevant](https://github.com/rtfd/readthedocs.org/issues/416#issuecomment-61596994). We can maybe generate such a preambule from the list in `agda-input.el`?

**Comment by asr** [comment]
At the moment (by using `XeLaTeX` instead of `LaTeX`) you can _locally_ generated a PDF with very few missing Unicode characters running

```
$ cd doc/user-manual
$ make latexpdf PDFLATEX=xelatex
```

**Comment by asr** [comment]
Blocked by https://github.com/rtfd/readthedocs.org/issues/1556.

**Comment by ice1000** [comment]
https://github.com/rtfd/readthedocs.org/issues/1556#issuecomment-278544075
https://github.com/rtfd/readthedocs.org/issues/1556#issuecomment-282535827

**Comment by nad** [comment]
What is the use case for the PDF document? Perhaps the HTML manual suffices.

If you really think that we should have a PDF manual, then I suggest that we include `\tracinglostchars=2` in the document's preamble, and check that there are no warnings about problematic characters.

**Comment by asr** [comment]
Please note as mentioned in the above commit (764038cf20dae68b463801fd049113011b4ade03) that the installation of Sphinx must use `pip3` instead of `pip`. You can install Sphinx and sphinx-rtd-theme by running

```
pip3 install --user -r doc/user-manual/requirements.txt
```

**Comment by asr** [comment]
Back-ported into 2.5.4.3.
