### ISSUE TITLE
Travis failure

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#2154]
Travis is currently not building due to a change in `optparse-applicative`.

`tasty-silver-3.1.8.1` is expecting `<>` to be exported from `Options.Applicative`, which it was in `optparse-applicative-0.12.1`. In `0.13.0.0` this is no longer the case.

I'm not sure what the best course of action is, but I can think of a couple of alternatives:
- exclude `optparse-applicative-0.13.0.0`
- notify the tasty silver maintainers and wait for them to fix the problem on their end

I suppose we could do both.

**Comment by phile314** [comment]
This should already be fixed:
https://github.com/phile314/tasty-silver/issues/10
http://hackage.haskell.org/package/tasty-silver-3.1.9/changelog

Let me know if there is still a problem.

**Comment by UlfNorell** [comment]
Yep, looks like travis is building now.
