### ISSUE TITLE
Improve documentation of NaN == NaN

### ISSUE THREAD

**Issue by phile314** [agda/agda#2155]
Following code compiled with GHC backend says `NaN == NaN` is true, which is incorrect:

<pre>
module _ where

open import Agda.Builtin.Float
open import Common.Prelude hiding (_+_; _*_)

print : Float → IO Unit
print x = putStrLn (primShowFloat x)

printB : Bool → IO Unit
printB true  = putStrLn "true"
printB false = putStrLn "false"

_/_ = primFloatDiv
_==_ = primFloatEquality

NaN : Float
NaN = 0.0 / 0.0

main : IO Unit
main =
  -- returns true, but should be false.
  putStr "NaN == NaN = " ,, printB (NaN == NaN) ,,
  return unit
</pre>

See also test/Compiler/simple/Floats.agda

**Comment by nad** [comment]
If you normalise `NaN == NaN` you also get `true`:

```
open import Common.Equality
open import Common.Prelude

NaN : Float
NaN = primFloatDiv 0.0 0.0

wrong? : primFloatEquality NaN NaN ≡ true
wrong? = refl
```

Some code from `Agda.TypeChecking.Primitive`:

```
floatEq :: Double -> Double -> Bool
floatEq x y | isNaN x && isNaN y = True
            | otherwise          = x == y
```

Some code from `Agda.Compiler.MAlonzo.Primitives`:

```
  , "primFloatEquality"     |-> return "((\\ x y -> if isNaN x && isNaN y then True else x == y) :: Double -> Double -> Bool)"
```

**Comment by phile314** [comment]
I find this surprising. Normally, `NaN /= NaN`. Does anybody know why equality is implemented this way?

**Comment by UlfNorell** [comment]
Subject reduction. You can prove `NaN ≡ NaN` using congruence, so having equality return false would mean we couldn't have decidable equality on `Float`.

**Comment by WolframKahl** [comment]
On Tue, Aug 30, 2016 at 01:09:32PM -0700, Philipp Hausmann wrote:

> I find this surprising. Normally, `NaN /= NaN`. Does anybody know why equality is implemented this way?

If NaN is a data constructor, then, propositionally, unavoidably, NaN == NaN.
The attitude behind `NaN /= NaN'' probably corresponds to an
`equality semidecision procedure'' point of view ``FPType -> FPType -> Maybe Bool'',
and the re-use of the operator names == and /= for that is unfortunate...
(Equality on floating point representations is best avoided anyways.)

**Comment by phile314** [comment]
That sounds reasonable. This probably should be documented a bit better, because it's surprising coming from Haskell/Javascript/C etc..

**Comment by UlfNorell** [comment]
[It is documented](http://agda.readthedocs.io/en/latest/language/built-ins.html#floats). What improvements are you suggesting?

**Comment by asr** [comment]
Note that the discussion in the OP continues on #2194.
