### ISSUE TITLE
Mismatch between Float and Double?

### ISSUE THREAD

**Issue by nad** [agda/agda#2156]
`Agda.Builtin.Float` contains the following line:

```
{-# BUILTIN FLOAT Float #-}
```

However, `Agda.Compiler.MAlonzo.Primitives` uses `Double` in the implementation of many (all?) `Float` primitives. Is this intended? Correct?

**Comment by phile314** [comment]
This code is correct. This binds the Agda Float datatype to the builtin Agda FLOAT datatype, which is implemented using Double in MAlonzo.

**Comment by nad** [comment]
Right, I was thinking of `COMPILED_TYPE`.
