### ISSUE TITLE
Panic: Unbound name, take two

### ISSUE THREAD

**Issue by mietek** [agda/agda#2158]
> Panic: Unbound name: `Panic.Tm` [0,50]@256367450
> when checking that the expression `Tm Γ Δ A` has type `Set (_b_28 Γ Δ)`

``` agda
module Panic where

open import Agda.Primitive

record Σ {a b} (A : Set a) (B : A → Set b) : Set (a ⊔ b) where
  constructor _,_
  field
    proj₁ : A
    proj₂ : B proj₁

open Σ public

∃ : ∀ {a b} {A : Set a} → (A → Set b) → Set (a ⊔ b)
∃ = Σ _

data Cx (U : Set) : Set where
  ⌀   : Cx U
  _,_ : Cx U → U → Cx U

data Ty : Set where

data Tm : Cx Ty → Cx (∃ (λ Γ → ∃ (λ Δ → ∃ (λ A → Tm Γ Δ A)))) → Ty → Set where
```

This might be a duplicate of https://github.com/agda/agda/issues/2024, but seems serious enough to deserve a report of its own.

This is Agda 2.5.2.1.

**Comment by mietek** [comment]
Compare:

``` agda
module NoPanic where

data Cx (U : Set) : Set where
  ⌀   : Cx U
  _,_ : Cx U → U → Cx U

data Ty : Set where

mutual
  record Rec : Set where
    inductive
    field
      Γ : Cx Ty
      Δ : Cx Rec
      A : Ty
      t : Tm Γ Δ A

  data Tm : Cx Ty → Cx Rec → Ty → Set where
```

**Comment by andreasabel** [comment]
Agda 2.5.2 complains about `Tm` not in scope.  Maybe you should try also the development version before reporting...

**Comment by nad** [comment]
> Maybe you should try also the development version before reporting...

I don't think we should require that users install the development version before reporting a bug.

**Comment by UlfNorell** [comment]
I think it's fair in this case since a very similar bug was already reported and fixed.

**Comment by mietek** [comment]
Thanks, and apologies. I will do better next time.
