### ISSUE TITLE
(another) Memory hogging in tail recursion

### ISSUE THREAD

**Issue by m0davis** [agda/agda#2159]
Similar to #2147, Agda uses (much) more memory than required when it typechecks the below code.

```
open import Agda.Builtin.Equality
open import Agda.Builtin.Nat

data AB : Set where
  A B : AB

foo : Nat → AB → AB
foo 0 t = A
foo (suc n) t = foo n A -- NB tail-recursive

test : foo 10000000 A ≡ A
test = refl -- memory blows up here
```

**Comment by UlfNorell** [comment]
Thank you for finding these issues!

The problem here is that substitution is too lazy so we build up a huge thunk in the second argument. It's easy enough to fix but not without a pretty bad performance hit in other places.

I'll poke around a bit...

**Comment by nad** [comment]
This program reminds me of [LateMetaVariableInstantiation.agda](https://github.com/agda/agda/blob/b0eaa5bdb2bc3b30ee7d6e2072b3bc568b54f4fb/benchmark/misc/LateMetaVariableInstantiation.agda).

**Comment by UlfNorell** [comment]
Yeah, it's the same problem but building Haskell thunks instead of Agda "thunks".

I believe I have managed to make things strict enough to avoid the memory leak without compromising performance in other places. Commit forthcoming...
