### ISSUE TITLE
Put Agda 2.5.1.1 on Stackage

### ISSUE THREAD

**Issue by scott-fleischman** [agda/agda#2160]
Stackage only has Agda 2.5.1. https://www.stackage.org/package/Agda

It looks like they disabled Agda on Stackage after the release of GHC 8. Now that Agda builds with GHC 8, it would be great to enable it again.

**Comment by asr** [comment]
I created this [PR](https://github.com/fpco/stackage/pull/1841) on Stackage for enabling Agda 2.5.1.1.

**Comment by asr** [comment]
The above PR was merged, so I'm closing the issue.
