### ISSUE TITLE
(yet another) Memory hogging in tail recursion

### ISSUE THREAD

**Issue by m0davis** [agda/agda#2161]
Similar to #2147 and #2159, Agda uses (much) more memory than required when it typechecks the below code. NB I am drawing this (and the prior two) simple examples from a more complicated case, https://github.com/m0davis/scratch/blob/569a75668ab72263b1c56c756edb779ebcfbc739/Snowflake/AgdaIssue2159-mod2.agda, which tries to rearrange a list of four unique elements.

```
open import Agda.Builtin.Equality
open import Agda.Builtin.Nat

data AB : Set where
  A B : AB

bar : AB → AB
bar A = A
bar B = A

foo : Nat → AB → AB
foo 0 t = bar t
foo (suc n) t = foo n (bar t) -- NB tail-recursive

test : foo 100000000 A ≡ A
test = refl -- memory blows up here
```

**Comment by UlfNorell** [comment]
This one is on you, I'm afraid. Agda uses non-strict evaluation, and this is a perfect example of a space leak. You'll get the same memory behavior if you do the example in Haskell.

To fix it you need to make it strict in the second argument (either by matching or using primSeq).

**Comment by m0davis** [comment]
Can you provide a definiton of primSeq in Agda? I don't find it in the agda-stdlib or agda-prelude (or hoogle).

**Comment by UlfNorell** [comment]
It's a builtin defined in one of the `Agda.Builtin` modules. Look at the builtin section in the manual.

**Comment by m0davis** [comment]
I see. Fwiw, here's the worked-out (non-memory-hogging) example using Ulf's recommendation from the docs (https://agda.readthedocs.io/en/latest/language/built-ins.html#strictness)

```
open import Agda.Builtin.Equality
open import Agda.Builtin.Nat
open import Agda.Builtin.Strict

data AB : Set where
  A B : AB

bar : AB → AB
bar A = A
bar B = A

infixr 0 _$!_
_$!_ : ∀ {a b} {A : Set a} {B : A → Set b} → (∀ x → B x) → ∀ x → B x
f $! x = primForce x f

foo : Nat → AB → AB
foo 0 t = bar t
foo (suc n) t = foo n $! bar t -- NB tail-recursive

test : foo 10000000 A ≡ A
test = primForceLemma 9999999 (λ n → foo n A) -- memory doesn't blow up here!
```
