### ISSUE TITLE
The Travis job for stack is failing

### ISSUE THREAD

**Issue by asr** [agda/agda#2164]
The job is [failing](https://travis-ci.org/agda/agda/jobs/157689906) because we are requiring the latest version (1.20.2) of cpphs which is not included in the latest LTS.

I guess cpphs 1.20.2 will be included in LTS in a couple of days. Meanwhile, I'll allow the failure of this job in Travis.

**Comment by asr** [comment]
@Blaisorblade currently Travis is using LTS 6.2. How can I configure Travis for using a different version of LTS?

**Comment by Blaisorblade** [comment]
On my phone, but the LTS version should be named in stack.yaml. I'll take a look today if you'd like.

**Comment by asr** [comment]
> On my phone, but the LTS version should be named in stack.yaml.

You are right. Thanks!

> I'll take a look today if you'd like.

It isn't necessary.
