### ISSUE TITLE
case-split introduces wrong variable name for implicit argument

### ISSUE THREAD

**Issue by m0davis** [agda/agda#2166]
Case-splitting on 'y'...

``` agda
{-# OPTIONS --show-implicit #-}
data D : Set where
  d : {x : D} → D

f : D → Set
f y = {!y!}
```

...yields an error:

``` agda
f (d {y = y}) = ?

--Unexpected implicit argument
--when checking that the pattern d {y = y} has type D
```

Notice that the name of the implicit is wrong ('y' instead of 'x'). Case-splitting should have yielded something like this:

``` agda
f (d {x = whatever}) = ?
```

**Comment by andreasabel** [comment]
I think this error is due to the use of `teleNamedArgs` in `Coverage.hs`:

``` haskell
      let conp    = ConP con noConPatternInfo $ applySubst rho2 $
                      map (setOrigin Inserted) $ teleNamedArgs gamma
```

`teleNamedArgs` just takes the variable names as argument names, which is wrong in general.

**Comment by andreasabel** [comment]
@m0davis: Thanks for reporting!  This bug may well be 4.5 years old!
