### ISSUE TITLE
Can't return an irrelevant type: Agda loops.

### ISSUE THREAD

**Issue by effectfully** [agda/agda#2167]
This eats all the memory on my machine and then I kill agda.exe:

```
loop : Set₁
loop = .Set
```

Agda version 2.6.0.

For my use case I need to return irrelevant types (wrapping them in a record is not a solution in my case), does it make sense to allow such thing and could this feature be added, if it's not already there?

**Comment by andreasabel** [comment]
Currently, irrelevance is not a first-class type constructor, but just a modality for the function space.  The former is more complicated, especially to determine when something is of irrelevant type.

``` agda
test : let X : Set1; X = _ in .X -> X
test x = x
```

Currently Agda refuses this, but with irrelevant types this could not be refused until the value of `X` is known. 
Without a type-theory in the background (that also has a story for meta-variables) I am not thinking about adding such a feature.

**Comment by jespercockx** [comment]
If this is an unsupported feature, shouldn't Agda at least give an error message instead of looping?

**Comment by andreasabel** [comment]
It does now.

**Comment by WolframKahl** [comment]
> This eats all the memory on my machine and then I kill agda.exe:

@effectfully: Consider making it a habit to never run agda without a maximum
heap setting, e.g., on a machine with 16G of RAM that you are also using
to run a web browser and other stuff:

```
+RTS -M11G -RTS
```

Then the GHC RTS will take care of killing it for you...
