### ISSUE TITLE
Float 0.0 == -0.0 makes Agda inconsistent

### ISSUE THREAD

**Issue by phile314** [agda/agda#2169]
``` agda
module Test where

open import Agda.Builtin.Float
open import Agda.Builtin.Equality
open import Agda.Builtin.Bool

data ⊥ : Set where

_/_ = primFloatDiv
_<_ = primFloatLess

cong : {A B : Set} {x y : A} (f : A → B) → x ≡ y → f x ≡ f y
cong f refl = refl

0eq : 0.0 ≡ -0.0
0eq = refl

bug : ⊥
bug = f (cong (λ x → (1.0 / x) < 0.0) 0eq)
  where
    f : false ≡ true → ⊥
    f ()
```

I discovered this due to a similar issue discussed in the Idris bug tracker, the proof comes also from there:
https://github.com/idris-lang/Idris-dev/issues/2609

The proper solution is to use bitwise equality.

**Comment by UlfNorell** [comment]
When fixing, remember to also fix `primFloatEquality` (both compile-time and the various runtimes).

**Comment by asr** [comment]
The `primFloatEquality` primitive can be fixed replacing in `Agda.TypeChecking.Primitive`

``` haskell
floatEq :: Double -> Double -> Bool
floatEq x y | isNaN x && isNaN y = True
            | otherwise          = x == y
```

by

``` haskell
import Numeric.IEEE ( IEEE(identicalIEEE) )

floatEq :: Double -> Double -> Bool
floatEq = identicalIEEE
```

 and adding the `ieee754` dependency in Agda.cabal

**Comment by UlfNorell** [comment]
> Where I need to look for fixing the definitional equality?

For definitional equality you need to change the `Eq` instance for `Literal`.

**Comment by asr** [comment]
> For definitional equality you need to change the `Eq` instance for `Literal`.

That works. Thanks!

**Comment by UlfNorell** [comment]
Check list:
- [x] Definitional equality (`Eq Literal`) [06335a4]
- [x] `primFloatEquality` [06335a4]
- [ ] `primFloatLess` (needs `-0.0 < 0.0 == true` to get a total order)
- [ ] `primShowFloat` (show `-0.0` as `"-0.0"`)
- [ ] Backends (all prim ops)
  - [ ] GHC
  - [ ] UHC
  - [ ] JS

**Comment by UlfNorell** [comment]
Looking at the code I noticed that `primFloatLess NaN NaN == true`, which is not good. That should be fixed when changing it for `-0.0`.

**Comment by asr** [comment]
@phile314 for fixing `primFloatEquality` on the UHC backend, I need to use the function `identicalIEEE` from the [ieee746](http://hackage.haskell.org/package/ieee754) package. How can I use this function on UHC?

Right now, I'm getting the following error:

``` haskell
$ cat Test.hs
module Main where

import Numeric.IEEE ( IEEE(identicalIEEE) )

main :: IO ()
main = do
  print (0.0 == (-0.0 :: Double))
  print (identicalIEEE 0.0 (-0.0 :: Double))
```

```
$ uhc Test.hs
File not found:
  file name         : Numeric/IEEE
  searched locations: " (directory)"
                      " (package database)"
  attempted suffixes: hs, lhs, eh, hi, tcr, bcr, c, o
```

```
$ uhc --version

uhc --version
ehc-1.1.9.4, revision @, timestamp 20160521 -0500 114916
```

**Comment by phile314** [comment]
Good question. UHC support in Cabal in UHC has been unmaintained and is most likely not working at the moment. Maybe we could use something like Storable to create our own identicalIEEE, if Storable is supported by UHC.

**Comment by UlfNorell** [comment]
I suppose you could also implement it using `isNegativeZero` and friends instead of bitwise equality. Something like

``` haskell
primFloatEquality x y =
  isNaN x && isNaN y ||
  (x, isNegativeZero x) == (y, isNegativeZero y) 
```

**Comment by nad** [comment]
If you don't use bitwise equality, then you need to be careful so that no other operation distinguishes values that should be treated as equal. With bitwise equality there is no such risk.

**Comment by UlfNorell** [comment]
Do you know if there are other values that are equal according to the `Eq` instance, but not bitwise equal?

**Comment by WolframKahl** [comment]
On Wed, Sep 14, 2016 at 11:07:14PM -0700, Philipp Hausmann wrote:

> Good question. UHC support in Cabal in UHC has been unmaintained and is most likely not working at the moment.

Just curious: Is UHC currently striving to be a compiler, or is it just used as a compiler development framework experiment?

(Last time I looked (roughly half a year ago), my impression was that it was the latter, and I could not discern any serious aspirations to make it actually useful, that is, generate efficient code. Since then, I compile Agda without `-f uhc`.)

**Comment by phile314** [comment]
I consider the Agda UHC backend mature and mostly stable, the remaining issues are mostly related to UHC.

As to where UHC is heading, @atzedijkstra can probably answer this better. As far as I know, it would be nice if UHC would be a production-ready compiler, it's just that that would take a lot of work. So being realistic, I personally expect that UHC stays a compiler development experiment for the time being, but I could be wrong?

I also don't mind if features are missing in the Agda UHC backend, I'm fine with just disabling the Float tests for UHC.

**Comment by WolframKahl** [comment]
On Thu, Sep 15, 2016 at 08:51:58AM -0700, Philipp Hausmann wrote:

> I consider the Agda UHC backend mature and mostly stable, the remaining issues are mostly related to UHC.
> 
> As to where UHC is heading, @atzedijkstra can probably answer this better. As far as I know, it would be nice if UHC would be a production-ready compiler, it's just that that would take a lot of work. So being realistic, I personally expect that UHC stays a compiler development experiment for the time being, but I could be wrong?

That exactly matches my impression and understanding.

Thank you!

**Comment by atzedijkstra** [comment]
Hi all,

Yes, as much as would like otherwise, I currently only keep UHC in a maintained state so it can be used as it is. There are many ideas for further development but (as so very often) it is lack of time (nonacademic day job) which keeps me from implementing them. In some way that might be good news, stuff will not break because I change stuff :-). I try to fix reported issues occasionally as time permits, so from Agda's perspective it is probably worthwhile to at least report where UHC breaks or fails.

All the best,
Atze

## 

Atze Dijkstra

**Comment by asr** [comment]
> I suppose you could also implement it using `isNegativeZero` and friends instead of bitwise equality. Something like
> 
> ``` haskell
> primFloatEquality x y =
>  isNaN x && isNaN y ||
>  (x, isNegativeZero x) == (y, isNegativeZero y) 
> ```

I used this function on the UHC backend.

**Comment by asr** [comment]
Check list (edited on 2016-09-30):
- Definitional equality (`Eq Literal`)  ✓
- `primFloatEquality` (`0.0` not equal to `-0.0`)
  Agda compiler  ✓
  GHC backend  ✓
  JS backend  ✓
  UHC backend  ✓
- `primShowFloat` (show `-0.0` as `"-0.0"`)
  Agda compiler  ✓
  GHC backend  ✓
  JS backend  ✓
  UHC backend  ✓
- `primFloatLess` (needs `-0.0 < 0.0 == true` to get a total order)
  Agda compiler  ✓
  GHC backend  ✓
  JS backend  ✓
  UHC backend  ✓

**Comment by phile314** [comment]
I think there can be NaN values with different bit patterns. As Floats can/could be used in the FFI, any difference in the bit patterns can be easily observed and lead to inconsistency.

IEEE754 defines a total order, it might be best to use that. [1] No idea though how to get that total order in Haskell, doesn't seem to be present in the ieee754 package.

[1] https://en.wikipedia.org/wiki/IEEE_floating_point#Total-ordering_predicate

**Comment by nad** [comment]
> I used this function on the UHC backend.

But bitwise equality elsewhere?

**Comment by asr** [comment]
> But bitwise equality elsewhere?

Yes (module the JS backend which I have no modified).

**Comment by nad** [comment]
I can imagine that this can lead to problems (like segfaults).

**Comment by asr** [comment]
> Looking at the code I noticed that `primFloatLess NaN NaN == true`, which is not good. That should be fixed when changing it for `-0.0`.

I filed #2208 for addressing this issue.

**Comment by asr** [comment]
The current status is shown in [this](https://github.com/agda/agda/issues/2169#issuecomment-247510821) check list. In consequence, I'll remove the 2.5.2 milestone.

**Comment by asr** [comment]
After 84baac4d273c8321c39f85cf6a8e2b60f84314d8,  I updated the [check list](https://github.com/agda/agda/issues/2169#issuecomment-247510821).

**Comment by andreasabel** [comment]
Is it important that float 0 prints as 0.0, not just 0?  More generally, speaks anything against printing nnnn.0 as just nnnn?

**Comment by JacquesCarette** [comment]
It's important in that it tells you that you're playing with fire, something 0 doesn't signify. Because IEEE arithmetic is unsound, it's good to relentlessly signal that you're playing with floats.
