### ISSUE TITLE
Instance search fails when instance meta is exposed

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2172]
It makes a difference whether we leave out an instance argument entirely or whether we give an underscore or question mark for it:

``` agda
postulate
  id : {t : Set} → t → t
  _≡_ : {t : Set} → t → t → Set
  ⊤ : Set

record FunctorOp (F : Set → Set) : Set₁ where
  field
    map : ∀{A B} → (A → B) → F A → F B

record FunctorLaws (F : Set → Set) {{O : FunctorOp F}} : Set₁ where
  field
    map-id : ∀{A : Set} → O .FunctorOp.map (id {A}) ≡ (id {F A})

record ApplyOp (A : Set → Set) {{O : FunctorOp A}} {{L : FunctorLaws A}} : Set₁ where
  field
    iapply : ∀ {t₁ t₂} → A (t₁ → t₂) → A t₁ → A t₂

record ApplyLaws (A : Set → Set) {{O : FunctorOp A}} {{L : FunctorLaws A}} {{i : ApplyOp A}} : Set₁ where

  open ApplyOp {{...}}
  field
    works  : ∀ (f : A (⊤ → ⊤)) → (x : A ⊤) → (iapply f x) ≡ x
    fails0 : ∀ (f : A (⊤ → ⊤)) → (x : A ⊤) → (iapply {{L₁ = _}} f x) ≡ x
    fails  : ∀ (f : A (⊤ → ⊤)) → (x : A ⊤) → (iapply {{L₁ = {!L!}}} f x) ≡ x
```

Note also the clever renaming of instance argument `L` to `L_1` that Agda performs (see #2018).

**Comment by andreasabel** [comment]
I think the metas created here should inherit the "instance" attribute.

**Comment by UlfNorell** [comment]
Yeah, that would make sense. We need to be careful only to apply it to metas that sit immediately inside an instance argument though.

**Comment by andreasabel** [comment]
This can be fixed as follows (see file `TC.Rules.Term`): In `checkApplication`, replace `checkExpr (namedThing e) a` by `checkNamedArg arg a` where `checkNamedArg` is a new function that does something special if the arg is an `Instance` and calls `checkExpr` otherwise.  Also, the code for cases `A.QuestionMark` and `A.Underscore` in `checkExpr` should be moved into helper functions which are called from `checkNamedArg` to avoid duplication.

**Comment by andreasabel** [comment]
Due to the mysteries of `ScopedExpr`, this took me about 2 days... sigh.

**Comment by andreasabel** [comment]
How to make an instance argument solved by unification instead:

``` agda
data D : Set where
  instance
    c : D

wallop : {{_ : D}} → D
wallop {{x}} = x

inst : D
inst = wallop {{_}}  -- works since 2.5.2

-- Use hid if you want to turn an instance meta into a ordinary meta
hid : ∀{a}{A : Set a}{x : A} → A
hid {x = x} = x

unif : D
unif = wallop {{hid}} -- yellow
```

**Comment by UlfNorell** [comment]
I've come to think this was a bad idea. With the current behaviour you can't easily give an instance argument explicitly, since you get an "no instance" error on the interaction meta.

I don't feel the change was really properly motivated to begin with. It's not very counterintuitive to have

- `?` - filled in by hand
- `_` - filled in by unificiation
- if you want explicitly filled in by instance search you define `it : ∀ {a} {A : Set a} {{x : A}} → A`

**Comment by andreasabel** [comment]
> since you get an "no instance" error on the interaction meta.

Well, you should not get one.

Anyway, why do you get errors on unresolved instance arguments, and only yellow on unresolved hidden arguments?  Something is amiss, maybe we should first make Agda consistent here.

**Comment by UlfNorell** [comment]
That's certainly worthwhile. I still think this change should be rolled back though.

**Comment by andreasabel** [comment]
But the role of a meta (solved by unification, solved by instance search) depends on its __position__, not on whether it is `?` or `_`.  It is the argument decoration that determines what should happen with the meta.  Completely omitting a hidden/instance meta should not be a semantic-changing action.  

Your story of `?` filled in by hand is not completely accurate.  `?`-metas are also solved internally, only the solution is held back.  I think the same semantics should carry over for instance metas (and auto metas, and oracle metas, and ask-the-Gods metas, etc... which me might add in the future).

**Comment by UlfNorell** [comment]
The problem with the current fix is that it's very syntactic, and thus brittle. Consider the following variants:

```agda
f : {{x : A}} → B → C

f b  -- instance search
f {{_}} b -- under debate
let X = _ in f {{X}} b -- unification
f {{id _}} b -- unification
f {{
```

I think treating `_` as always being solved by unification is the more principled thing to do.

Anyway, I rolled this back at least until we change the instance error to a warning.

**Comment by jespercockx** [comment]
For what it's worth, I think it's also more intuitive if an argument given as `{{_}}` is solved by unification rather than instance search: the `{{ }}` says "please don't use instance search, I want to give this argument myself" and the `_` says "please insert a new metavariable here and solve it by unification". So composing these two means "please don't use instance search but use regular unification instead".

**Comment by andreasabel** [comment]
@jespercockx:  Your story does not scale, just consider `{_}`.

`_` is the notation for a meta that is solved automatically the method depends on the `ArgInfo`.  
`?` is the notation for a meta that is solved manually (but can be constrained by the automatic search).

If that is not the case what is the notation for a meta that is solved by instance search?  Do you want a new notation for each way of solving a meta?  That is contrary to efforts like #2513.

**Comment by andreasabel** [comment]
Also with disabling instance search for `{{?}}` you do not have an easy way to put a resolved instance into your code.  With `{{?}}` you get a constrained meta which you can insert with `C-c C-s`.

**Comment by jespercockx** [comment]
If you want to solve an argument by instance search, you can use `it`. Similarly, we don't actually need special syntax for `_`, you can just use your `hid` instead. I imagine you can define similar functions if we add other ways to solve implicit arguments besides unification and instance search.

For your other remark, maybe we need a way to invoke instance search to solve a particular interaction hole *regardless* of whether you're giving an instance argument or not? That seems like it could be a useful feature to have.

**Comment by UlfNorell** [comment]
> @jespercockx: Your story does not scale, just consider {_}.

That's consistent with Jesper's story. Here you're saying, "I want to fill this argument myself" and then "please insert a unification metavariable here".

> For your other remark, maybe we need a way to invoke instance search to solve a particular interaction hole regardless of whether you're giving an instance argument or not? That seems like it could be a useful feature to have.

That's exactly what `it` does. I don't think we need special support for it.

**Comment by UlfNorell** [comment]
Oh, nevermind the last comment. I see what you're after.

Maybe the command should be *"Check term against current goal and normalise"*. Then you could invoke it with `it` in the hole. Anyway, I agree with Jesper that this seem like a useful feature regardless of whether you're sitting immediately inside `{{ }}`.

**Comment by andreasabel** [comment]
> "please insert a unification metavariable here".

Ah, ok, that is when a visible argument is replaced by `_`.  True. 

But still we are missing a way to bring an instance solution to the light.  For a unification solution we put `{?}` and then solve.  For instance solution we would put  `{{?}}` and then solve.  That was the symmetry I was after.

Also, as `{_}` is a no-op (making a unification meta explicit and solving it automatically), I turned `{{_}}` into the same no-op (making an instance meta explicit and solving it automatically).

Btw, I think that `{{_}}` after the revert is quite useless.  In instance positions we usually do not have something that is solvable by unification.  (Why would we then have an instance argument in the first place?)

**Comment by UlfNorell** [comment]
> But still we are missing a way to bring an instance solution to the light.

What about my suggested normalisation command. I must admit I don't quite understand the use case. If it's solvable by instance search why would you want to put the instance in the code explicitly?

> Btw, I think that `{{_}}` after the revert is quite useless.

Sure, in the same way that `{it}` or `{_ : A} → B` are quite useless; in a predictable way.

**Comment by andreasabel** [comment]
> If it's solvable by instance search why would you want to put the instance in the code explicitly?

Well, for exploration, understanding what is going wrong etc.  
I often make hidden values explicit by `{?}` and `C-c C-s`.

**Comment by UlfNorell** [comment]
So having a command like the one I suggested above would be sufficient for you?

**Comment by andreasabel** [comment]
Couldn't hurt, no?

**Comment by andreasabel** [comment]
Nothing urgent about this issue (current behavior is the one of 2.5.2), thus I upped the milestone to 2.5.4.

**Comment by asr** [comment]
> thus I upped the milestone to 2.5.4.

So, I removed the 2.5.5 milestone.

**Comment by UlfNorell** [comment]
I filed #2700 for the new command, so closing this issue.

**Comment by asr** [comment]
and changing the milestone.

**Comment by UlfNorell** [comment]
You probably don't want to put this one in the release notes though, since we closed it with "working-is-intended".

**Comment by asr** [comment]
Re-labelled.

**Comment by nad** [comment]
I guess you mean "working *as* intended".

**Comment by andreasabel** [comment]
I renamed the label to "status: working-as-intended".

**Comment by andreasabel** [comment]
Mixed up #2712 with #2172.
