### ISSUE TITLE
Goalification is broken

### ISSUE THREAD

**Issue by nad** [agda/agda#2174]
Consider the following code:

```agda
postulate
  F : Set → Set

G : Set
G = {!F ?!}
```

Infer the type of the expression in the goal, and then give the expression. Result:

```agda
postulate
  F : Set → Set

G : Set
G = F ?
```

Note that Agda has not "goalified" the question mark.

This is a regression, the example is handled correctly by Agda 2.5.1.1. I think the bug was introduced by @andreasabel in 3a6dea615c9b8f160c7d190a65b0ce0e63cdab53:

```
$ cat Bug.agda
postulate
  F : Set → Set

G : Set
G = {!F ?!}
$ cat script
#!/bin/sh

AGDA=$1

$AGDA --interaction --ignore-interfaces <<EOF
IOTCM "Bug.agda" None Indirect (Cmd_load "Bug.agda" [])
IOTCM "Bug.agda" None Indirect (Cmd_infer Instantiated 0 (intervalsToRange (Just (mkAbsolute "$PWD/Bug.agda")) [Interval (Pn () 42 5 7) (Pn () 45 5 10)]) "F ?")
IOTCM "Bug.agda" None Indirect (Cmd_give 0 (intervalsToRange (Just (mkAbsolute "$PWD/Bug.agda")) [Interval (Pn () 42 5 7) (Pn () 45 5 10)]) "F ?")
EOF
$ agda-bisect --good v2.5.1.1 --bad HEAD --script ./script --must-not-output "(agda2-goals-action '())"
[...]
3a6dea615c9b8f160c7d190a65b0ce0e63cdab53 is the first bad commit
commit 3a6dea615c9b8f160c7d190a65b0ce0e63cdab53
Author: Andreas Abel <andreas.abel@ifi.lmu.de>
Date:   Fri Jul 29 19:48:48 2016 +0200

    Fixed #1720: no longer create two interaction points in record decl.

    A bit hackish: we try to see whether we added already the interaction
    point by comparing the range of the new IP with the ranges of the
    existing IPs.

    Workaround for issue #424.

[...]
```

**Comment by andreasabel** [comment]
Maybe `Cmd_infer` should not change the state, should it?  What happens anyway with the meta-variables it creates, do they linger on in the meta store? Looks like a memory leak to me.

**Comment by UlfNorell** [comment]
They go away as soon as you reload, so as memory leaks go it's not very serious. It would of course be better to not have it change the state at all.

**Comment by andreasabel** [comment]
I am in the process of changing the interaction commands to preserve the state.

**Comment by andreasabel** [comment]
Fixed this by taking care that the state is preserved by (most) interaction commands.

Once record declaration checking is properly implemented, my workaround https://github.com/agda/agda/commit/3a6dea615c9b8f160c7d190a65b0ce0e63cdab53 can be rolled back, of course.

**Comment by nad** [comment]
Here's a very similar problem. Consider the following code:

``` agda
postulate
  F : Set → Set → Set

G : Set
G = ?
```

First try to give `F ?`, and then give `F ? ?`. (In both cases the text should be entered in the goal, not in the minibuffer.) Result:

``` agda
postulate
  F : Set → Set → Set

G : Set
G = F {!!} ?
```

Note that Agda has not "goalified" the final question mark.

This is a regression, the example is handled correctly by Agda 2.5.1.1. Bisection suggests that the bug was introduced by the commit that introduced the bug above:

```
$ cat Bug.agda
postulate
  F : Set → Set → Set

G : Set
G = ?
$ cat script
#!/bin/sh

AGDA=$1

$AGDA --interaction --ignore-interfaces <<EOF
IOTCM "Bug.agda" None Indirect (Cmd_load "Bug.agda" [])
IOTCM "Bug.agda" None Indirect (Cmd_give 0 (intervalsToRange (Just (mkAbsolute "$PWD/Bug.agda")) [Interval (Pn () 1 1 1) (Pn () 1 1 1)]) "F ?")
IOTCM "Bug.agda" None Indirect (Cmd_give 0 (intervalsToRange (Just (mkAbsolute "$PWD/Bug.agda")) [Interval (Pn () 1 1 1) (Pn () 1 1 1)]) "F ? ?")
EOF
$ agda-bisect --bad HEAD --good v2.5.1.1 --must-output "(agda2-goals-action '(2 3))" --script ./script --log log
[...]
3a6dea615c9b8f160c7d190a65b0ce0e63cdab53 is the first bad commit
commit 3a6dea615c9b8f160c7d190a65b0ce0e63cdab53
Author: Andreas Abel <andreas.abel@ifi.lmu.de>
Date:   Fri Jul 29 19:48:48 2016 +0200

    Fixed #1720: no longer create two interaction points in record decl.

    A bit hackish: we try to see whether we added already the interaction
    point by comparing the range of the new IP with the ranges of the
    existing IPs.

    Workaround for issue #424.

[...]
```

**Comment by nad** [comment]
I get bitten by this bug (or something similar) quite a lot: When I try to give something in a hole I sometimes get weird error messages, because Agda has messed up the assignment of goal numbers to holes.

**Comment by guillaumebrunerie** [comment]
Same here.
Here is an interesting variant:

Load (`C-c C-l`) a file containing the line `B = ?`, then add the line `A = ?` before (but do not reload the file). Then do `C-c C-t` in the goal for `B`: the two goals get exchanged.

**Comment by andreasabel** [comment]
Seems correct if C-c C-t is for "transpose goals" :D. 
Actually, I think your problem @guillaumebrunerie is unrelated, it exists already in 2.5.1.1.  This should be a new issue.  It is more a problem of the emacs mode, which does not get told by Agda where the goals are, but finds them by grepping through the buffer.  If you added new question marks, the emacs mode will think these were part of the original goals.

**Comment by andreasabel** [comment]
@nad I had another try on this, recovering the TCState after a failed command.  Please check if things work to your satisfaction now.  (And possibly reopen this issue.)
