### ISSUE TITLE
Allow qualification in using/renaming/hiding.

### ISSUE THREAD

**Issue by effectfully** [agda/agda#2175]
```agda
module hiding-ambiguous where

module M where
  data D₁ : Set where
    d : D₁

  data D₂ : Set where
    d : D₂
open M hiding (D₂.d)
-- Parse error
-- D₂.d<ERROR>
-- )
-- ...
```

Would be good to get `D₂.d` parsed. Is it currently possible to open `M` such that only `D₁.d` is brought in scope?

**Comment by andreasabel** [comment]
Yes, it is, like this:

``` agda
module Issue2175 where

module M where
  data D₁ : Set where
    d : D₁

  data D₂ : Set where
    d : D₂

open M using (D₁; D₂) hiding (module D₂)
open D₁

test-d : {!!}  -- solved as D₁
test-d = d  -- non-ambiguous

test-D₁ = D₁
test-D₂ = D₂
```

**Comment by effectfully** [comment]
@andreasabel, thanks. But it interacts with `open public` strangely:

``` agda
module hiding-module-public where

module M1 where
  module M2 where
    data D : Set where
      d : D
  open M2 hiding (module D) public
open M1

t : D
t = d
```

Should I open a separate issue?

**Comment by andreasabel** [comment]
What is strange here?  Can you elaborate?
If you write

``` agda
 open M2 using (D) hiding (module D) public
```

instead, then `d` is not exported.

**Comment by effectfully** [comment]
Ah, sorry, I decided that `hiding (module D₂)` in your `Issue2175` is needed to hide the constructor of `D₂`, but this is achieved via `using (D₁; D₂)`.

**Comment by andreasabel** [comment]
Do you still want to pursue the original issue?  (I feel there should be more evidence for its usefulness to further pursue it.)  There are 3 options.
1. Do nothing on this issue.
2. Parse qualified names, but still give an error.
3. Fully support qualified names in import directives.

**Comment by effectfully** [comment]
My issue was that I couldn't write

```agda
open import Reflection renaming (Pattern.var to patVar; Term.var to appVar)
```

But after getting your help I can now write

```agda
open import Reflection hiding (var)
open Pattern renaming (var to patVar)
open Term    renaming (var to appVar)
```

It seems a bit less nice, but still looks pretty good. So for me all three options are satisfying.

Here is another example:

```
open import Data.List.Base hiding ([])
open List
open InitLast renaming ([] to []ⁱˡ)
```

instead of

```
open import Data.List.Base renaming (InitLast.[] to []ⁱˡ)
```

**Comment by andreasabel** [comment]
We can leave it open as a feature request.  Maybe @UlfNorell or @nad have an opinion about it.  For, it seems useful, but there are more urgent things for me to work on.

**Comment by andreasabel** [comment]
I started to implement 2, but ran out of steam.  There is too much to refactor for too little gain.  
In general, we should avoid reporting `Parse error` where we can.  But this should be solved systematically, by introducing a `Parsed` syntax before the `Concrete` syntax and a preprocessing phase which tightens the syntax and gives nice error message.  Modifying `Concrete` to cater for `QName`s where we actually want `Name`s makes things too messy.
