### ISSUE TITLE
Why `primShowFloat` returns `0.0` on negative zero?

### ISSUE THREAD

**Issue by asr** [agda/agda#2180]
This is correctly [documented](http://agda.readthedocs.io/en/latest/language/built-ins.html#floats) that `primShowFloat` returns `0.0` on negative zero. Why?

**Comment by UlfNorell** [comment]
Before #2169 it was necessary since `0.0` and `-0.0` were equal and thus should not behave differently. Once #2169 is fixed we can have negative zero show as `"-0.0"`.

**Comment by UlfNorell** [comment]
Closing this as it's really part of #2169.
