### ISSUE TITLE
`getType` treats macroses as regular functions

### ISSUE THREAD

**Issue by effectfully** [agda/agda#2182]
```
macro
  TypeOf : Name -> Term -> TC _
  TypeOf n ?r = bindTC (getType n) (unify ?r)

test : Set
test = TypeOf TypeOf
```

`test` equals `Name -> Term -> TC _` as one might expect,  however I think it's incorrect. `TypeOf` is not a proper function — it's a macro and when it's used it receives only one argument. When it's used it also doesn't return a `TC _`, it returns something else, depending on what `?r` was unified with.

Currently `getType TypeOf` returns (wrapped in the `TC` monad)

```
pi (arg (arg-info visible relevant) (def (quote Name) []))
(abs "_"
 (pi (arg (arg-info visible relevant) (def (quote Term) []))
  (abs "_"
   (def (quote TC)
    (arg (arg-info hidden relevant) (def (quote zero) []) ∷
     arg (arg-info visible relevant) (def (quote ⊤) []) ∷ [])))))
```

I think it should return

```
pi (arg (arg-info visible relevant) unknown) (abs "_" unknown)
```

i.e. the final `Term -> TC _` should be collapsed into `unknown`, because that's what you get when you actually use a macro. And all `Name` and `Term` arguments should be `unknown` too, while others should remain untouched.

I'm asking, because I have a generic machinery that handles functions/constructors/data types properly, but fails on macroses, because they are treated like regular functions which they are not.

**Comment by UlfNorell** [comment]
I think that `getType` does the right thing, but `getDefinition` should indicate in some way that the name refers to a macro. Either as through a new constructor in the `Definition` type, or with an extra bit in the function case.

**Comment by effectfully** [comment]
> `getDefinition` should indicate in some way that the name refers to a macro.

And with that I can implement `getType` as I want it to be. But that change would break existing code most of which doesn't care about reflected macroses. Maybe add a separate `isMacro : Name -> TC Bool`?

**Comment by UlfNorell** [comment]
Yes, that might be a nice backwards-compatible solution.
