### ISSUE TITLE
Allow splitting on dotted variables

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#2183]
Since you can now leave dotted patterns as named variables, it would make sense to allow splitting on them when they refer to variables from the module telescope. For instance, in the example below, `m` is really `.n`.

``` agda
module _ (n : Nat) where

  foo : (m : Nat) → n ≡ m → Nat
  foo m refl = {!m!} -- not a splittable var: m
```

Allowing this would require moving the dot to the `n` instead.

A complication is that with-functions don't necessarily take the module parameters as their first arguments so it's hard to tell which argument pattern is the module parameter when moving the dots around.

This came up when fixing #2181.

**Comment by andreasabel** [comment]
Added milestone because of #2517.

**Comment by jespercockx** [comment]
A cheap fix to this issue would be to make the unifier prefer instantiating module parameters to instantiating user-written variables.

**Comment by UlfNorell** [comment]
Can you have a go at it?

**Comment by jespercockx** [comment]
The problem seems to be not in the unifier at all but rather in `MakeCase.hs` where we use a wrong method to determine whether a variable is bound as a module parameter or a pattern variable. I'm almost finished with a fix...
