### ISSUE TITLE
 Parse error
 NO_SMASHING<ERROR>  in Agda of September 13, 2016

### ISSUE THREAD

**Issue by mechvel** [agda/agda#2184]
I try to use Development Agda of September 13, 2016
on ghc-7.10.2, Debian Linux.

Installing looks successful.
Then
            `agda $agdaLibOpt  ... myProgram.agda`
## reports 

...
       Finished Algebra.Operations.
       Checking Relation.Binary.Reflection (/home/mechvel/agda/stLib/0.12/src/Relation/Binary/Reflection.agda).
        Checking Data.Vec.N-ary (/home/mechvel/agda/stLib/0.12/src/Data/Vec/N-ary.agda).
/home/mechvel/agda/stLib/0.12/src/Data/Vec/N-ary.agda:52,5-5
/home/mechvel/agda/stLib/0.12/src/Data/Vec/N-ary.agda:52,5: Parse error
NO_SMASHING<ERROR>
##  ∀ⁿ #-}

Before type-checking my code, it type-checks Standard library,  and it seems to fail when parsing something in it.

**Comment by UlfNorell** [comment]
The development version of Agda needs the development version of the standard library (at https://github.com/agda/agda-stdlib).
