### ISSUE TITLE
Idiom brackets should require inner whitespace

### ISSUE THREAD

**Issue by mechvel** [agda/agda#2186]
`( |xs|  +  |ys| )`
is parsed in Agda-2.5.1.1 and is not parsed in Development Agda of September 13, 2016.
Probably, this is something about  the character sequences   `( |`  and  `| )`.
Which version is better?

**Comment by mechvel** [comment]
Here   `( |`  and  `| )'   need to be  written without blanks
(I have an impression that the editor has inserted blanks here).

**Comment by mechvel** [comment]
One more attempt:

`(|xs| + |ys|)`

**Comment by andreasabel** [comment]
My guess is that `(|` and `|)` are now reserved for idiomatic application (idiom brackets).  See the release notes for Agda 2.5.2.

**Comment by andreasabel** [comment]
We should limit parsing of idiom brackets to a flag `--idiom-brackets`.   I am doubting a wide-spread adaptation of the idiom brackets feature.  
(I also find the implementation a hacky, it violates our current philosophy of specifying all concrete names with meaning by a BUILTIN pragma.)

**Comment by UlfNorell** [comment]
Indeed. In particular [here](https://github.com/agda/agda/blob/master/doc/release-notes/2-5-2.txt#L144-L169).

The parser should however not treat your example as an idiom bracket application since there is no whitespace between the `(|` and the `xs`.

**Comment by UlfNorell** [comment]
> We should limit parsing of idiom brackets to a flag --idiom-brackets. I am doubting a wide-spread adaptation of the idiom brackets feature.

Hiding it under a flag would certainly prevent wide-spread adaptation...

I'm using idiom brackets to make applicative uses of mixfix operators look not horrible. I suppose there could be some form of builtin declaration to decide which names to use, but for now I think it's enough to make it not conflict with existing code.

**Comment by andreasabel** [comment]
Ok, that is fine with me.
