### ISSUE TITLE
Speed up some Travis jobs

### ISSUE THREAD

**Issue by asr** [agda/agda#2188]
We should use Stackage for speeding up some Travis tests (e.g. `cpp-and-debug`, `haddock` and `ghc-7.8.4-transformers-0.3.0.0`).

**Comment by andreasabel** [comment]
Andor Penzes suggested one could also use docker images for speeding up travis.  Such a docker image would cointain a ghc-installation with all the hackage packages Agda depends on.  However, we would have to keep track of dependency changes to decide when we need to build a new docker image.

**Comment by asr** [comment]
After the above commit (eb96c42), we don't use the `stack.yaml` file but the `stack-GHC-version.yaml` files. If you need/want continue using the `stack.yaml` file, you can create a symlink from the news .yaml files.

**Comment by asr** [comment]
I used stack on the following tests: `CPP_AND_DEBUG`, `ghc-7.8.4-transformers-0.3.0.0`, `STACK` and `UHC`. I got a speed up of approx 50% on those tests.

**Comment by asr** [comment]
I reverted the use of stack on the `UHC` test (see fff1f59).
