### ISSUE TITLE
with abstracts now also in arguments of parent function

### ISSUE THREAD

**Issue by mechvel** [agda/agda#2190]
This is on  Development Agda of September 16, 2016,  ghc-7.10.2,  
Debian Linux.  
Please, download 

http://www.botik.ru/pub/local/Mechveliani/agdaNotes/Bug-sep16-2016.agda 

It is a small program.
There the argument   `sm<mty-p'ps`  
 has type 
`sm < mty (p' ∷ ps)`

But the type checker does not find this.
And it improves when it is set  
`debug =  sm<mty-p'ps`
instead of `sm<mty-p'ps`,
with setting for `debug`  the signature  
`sm < mty (p' ∷ ps)`

**Comment by andreasabel** [comment]
I guess this discrepancy arises since `with` abstracts `k ≟ k'` in the type of variable `sm<mty-p'ps` which is a function argument of a parent function, but not in `debug` which is a local definition.

Is this a regression wrt. Agda-2.5.1.1, i.e., did this check fine in Agda-2.5.1.1?

**Comment by andreasabel** [comment]
Here is a short test case.  This checked with Agda-2.5.1.1, but fails with Agda-2.5.2:

``` agda
postulate
  A : Set
  a : A
  P : A → Set

parent : (p : P a) → Set
parent p = A
  where
  expect-p : P a → Set
  expect-p _ = A

  accept-p = expect-p p

  test : Set
  test with a
  ... | w = expect-p p
```

**Comment by andreasabel** [comment]
With all these regressions, I this parameter-refinement was too much of a change to go on stable, it should have gone on master.  We are in a similar situation as in 2014: new experimental features are blocking the release.

**Comment by mechvel** [comment]
On Sat, 2016-09-17 at 01:48 -0700, Andreas Abel wrote:

> I guess this discrepancy arises since with abstracts k ≟ k' in the
> type of variable sm<mty-p'ps which is a function argument of a parent
> function, but not in debug which is a local definition.
> 
> Is this a regression wrt. Agda-2.5.1.1, i.e., did this check fine in
> Agda-2.5.1.1?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

This is a reduction of the example which was type-checked Agda-2.5.1.1
and was not type-checked in Development Agda.

---

Sergei

**Comment by UlfNorell** [comment]
Why is this blocking the release? Parameter refinement did change the semantics here (to the better), but we're not promising complete backwards compatibility between `2.5.1` and `2.5.2`.

**Comment by andreasabel** [comment]
I just checked the release notes, they do not alert the user of a changed semantics of `with`.  There should be a sections detailing the new behavior of `with` including some examples of things that work now but did not before and things that did work but work no longer.

Also, whether the change of a heuristics is "to the better" is always up to taste. People write their code to work with the heuristics. If it changes, they may have to rewrite their code. "To the better" would be indisputable with it was backwards-compatible.

**Comment by mechvel** [comment]
On Sat, 2016-09-17 at 03:46 -0700, Ulf Norell wrote:

> Why is this blocking the release? Parameter refinement did change the
> semantics here (to the better), but we're not promising complete
> backwards compatibility between 2.5.1 and 2.5.2.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

Probably, people will agree that backwards compatibility is not
necessary in general, so far, because probably the language does not
look stable, so far.  
But at least, this my particular example needs to be type-checked. 
It will be unnatural if it is not type-checked. Will it?

**Comment by UlfNorell** [comment]
> But at least, this my particular example needs to be type-checked. It will be unnatural if it is not type-checked. Will it?

Not without modifications. With-abstraction now abstracts also over variables bound outside the function, like module parameters or parent function arguments. When that's not desirable you can do what you did and define an alias (`debug` in your case) to hide it from abstraction, or simply not use a 'with'.

**Comment by mechvel** [comment]
On Sat, 2016-09-17 at 10:32 -0700, Ulf Norell wrote:

> ```
>     But at least, this my particular example needs to be
>     type-checked. It will be unnatural if it is not type-checked.
>     Will it?
> ```
> 
> Not without modifications. With-abstraction now abstracts also over
> variables bound outside the function, like module parameters or parent
> function arguments. When that's not desirable you can do what you did
> and define an alias (debug in your case) to hide it from abstraction,
> or simply not use a 'with'.

With this new language, one will need, for example, to write

```agda
postulate f : {x y : ℕ} → x < y → ℕ

g : (x y : ℕ) → x < y → ℕ
g x y x<y
      with x ≟ y
... | yes _ =  x
... | no _  =  f as-x<y 
  where 
  as-x<y : x < y     -- (1)
  as-x<y = x<y       --
```
And in Agda 2.5.1.1 it is sufficient to write

```agda
... | no _  =  f x<y                          -- (2)  
```

instead of (1).  
(2) looks natural, and (1) looks odd.

And you write that there are some benefits of the new language that cost this drawback.
I do not know. May be there are clear examples when the new language feature allows better programs. 

((2) is also type-checked by the new type checker, but we have observed somewhat a similar example which is not type-checked).
