### ISSUE TITLE
JS backend prints `1.0` as `1`

### ISSUE THREAD

**Issue by asr** [agda/agda#2192]
``` agda
open import Common.Prelude

main : IO Unit
main = putStrLn (primShowFloat 1.0)
```

With GHC backend: `1.0`
With UHC backend: `1.0`
With JS backend: `1`

Blocking #2169.

**Comment by identicalsnowflake** [comment]
Well in any case, it's consistent with how JS displays floats. `console.log(1.0)` prints `1`, not `1.0`.

**Comment by UlfNorell** [comment]
The problem is that any discrepancy between compile time and runtime semantics will lead to non-type safety in a dependently typed language.

In this case since you can prove that `primShowFloat 1.0 ≡ "1.0"` that had better hold at runtime as well.

**Comment by identicalsnowflake** [comment]
Hmm, yeah I can see how that causes inconsistency. In fact, this could potentially have caused me future pain, because I remember writing code to remove the ".0" at one point, which obviously would have caused problems if the runtime show didn't have the ".0"!

**Comment by asr** [comment]
The fix requires Node.js 0.11.X but Travis has Node.js 0.10.36, so I reverted it. I'll upgrade the version of Node.js on Travis later.

**Comment by asr** [comment]
Or I'm missing something very obvious or the Node.js/JavaScript/v8/ECMAScript versions are a mess.  How I know which is the minor version of Node.js including the `Number.isInteger` function?

**Comment by L-TChen** [comment]
I wonder if the change to Travis is still relevant. Currently the pre-installed Node.js versions on Travis include

```
v4.8.6
v6.12.0
v6.12.1
v8.9
v8.9.1
```

and if I understand it right v8.9.1 should work fine ...?
