### ISSUE TITLE
`primFloatEquality NaN -NaN` should return `false` on the JS backend

### ISSUE THREAD

**Issue by asr** [agda/agda#2194]
``` agda
open import Common.Prelude

printB : Bool → IO Unit
printB true  = putStrLn "true"
printB false = putStrLn "false"

_/_ = primFloatDiv
_==_ = primFloatEquality

NaN : Float
NaN = 0.0 / 0.0

main : IO Unit
main = printB (NaN == NaN)
```

On the above code the backends return as follows:

GHC: `true`
UHC: `true`
JS: `false`

The JS backend also should returns `true` (see #2155).

**Comment by phile314** [comment]
But should `NaN == NaN` ever return true? There are different types of NaN [1], and if we want to return true we have to be sure that this difference can _never_ be observed. While we can enforce that at compile time, at runtime this gets much more difficult due to the FFI. Why do we not just use `identicalIEEE` (bitwise equality) without any additional special casing?

[1] https://en.wikipedia.org/wiki/NaN#Encoding

**Comment by UlfNorell** [comment]
The question is what to do when bitwise equality is not readily available, like in the UHC and JS backends. FWIW I haven't been able to construct any of the different NaN encodings using standard Haskell functions.

**Comment by phile314** [comment]
Bitwise equality in JS should be possible by going via the byte representation[1].

I didn't actually try to construct different NaNs in Haskell. I am mostly worried about the FFI/binary serialization. If Floats are encoded/decoded e.g. from binary files or network protocols, you could get different kinds of NaN.

[1] http://stackoverflow.com/a/14379836/6231928

**Comment by asr** [comment]
It seems we should use the [Object.is](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is) function, but it requires a recent version of Node.js.

Could someone confirm that

``` js
console.log(Object.is(NaN, NaN))
```

prints `true`. If so, what version of Node.js are you using?

**Comment by asr** [comment]
I confirm the above behaviour using Node.js 4.5.0.

**Comment by asr** [comment]
I'm not familiar with the versions of Node.js. Any idea which is the first version that supported the `Object.is` function?

**Comment by asr** [comment]
Never mind. The version of Node.js pre-installed on Travis supports the `Object.is` function.

**Comment by phile314** [comment]
I still think treating different NaNs as equal is dangerous.

<pre>
-- Assuming conversion of floats to word64
encode : Float -> Bytes
-- We can easily proof that encoding two equal float values should yield the same
-- bit pattern. However, if we treat different nan's as equal, this proof here is inconsistent.
proof : (x y : Float) -> x == y -> encode x == encode y
proof = cong encode
</pre>

To be clear, this is only a problem if different kinds of NaN values can be produced. In Haskell/Agda itself, this seems impossible according to Ulfs experiment and my own google searches. However, such a NaN could still be introduced by something outside of Agdas control via IO or the FFI.

As float equality is mostly useless for numerical computations anyway, I would propose to make it use bitwise comparisons and to provide the usual floating point comparisons as a separate set of primitives:

<pre>
-- Bitwise equality. Suitable for producing Equality witnesses using trustMe
primFloatEqualityBitwise : Float -> Float -> Bool
-- The "normal" numerical comparison functions.
primFloatEquality : Float -> Float -> Bool
primFloatLess : Float -> Float -> Bool
</pre>

**Comment by andreasabel** [comment]
Just a naive question from a spectator:  Why providing an equality for floats at all in Agda?  
It seems to encourage better programming practice to rather provide a library function that tests whether to floats are less than a threshold apart, i.e., that tests whether |x-y|<epsilon.

**Comment by UlfNorell** [comment]
Without decidable equality on floats you can't have decidable equality on any structures containing floats. For instance, reflected terms.

**Comment by WolframKahl** [comment]
I guess this means “decidable propositional equality”.

Especially in the context of floats, where something called “equality” is defined in a standard, one has to be very careful with wording...

Perhaps we should outlaw the use of plain “equality” in this discussion, and always use “propositional equality” respectively  “IEEE-equality”.

The total order based on bitwise representations could be called “technical order” or “bitwise order”, and the relation defined in that standard “IEEE-order”.

I think much of the confusion in this discussion goes back to an occasional lack of precision in separating these two worlds:
1. The Agda propositional equality view, with its predefined semantics. A total order in this view would be used for technical applications, for example for keys in finite maps, and needs to be a total order _relative to propositional equality_, but does not need to have any relation with the real-number semantics of floating-point representations. (How much sense uses of this order make is a different question.)
2. The real-number semantics view as approximated by the IEEE standard, which introduces relations I propose to call “IEEE-equality” and “IEEE-order”, which are, as far as I know, not an equivalence relation respectively not an order relation, but still may have some uses in the world of applications of floating-point representations...

**Comment by identicalsnowflake** [comment]
After glancing over the `Object.is()` documentation on MDN, I think this seems reasonable. You can even use a (shortened) version of their polyfill to alleviate compatibility concerns:

``` javascript
function(x,y){
  return x===y || (x!==x && y!==y)
}
```

EDIT: actually my function is different than their polyfill. They treat -0 and +0 as distinct, while the above says they're equal. Not sure what the desired behavior is.

**Comment by UlfNorell** [comment]
`-0.0` and `0.0` need to be distinct. See #2169.

**Comment by asr** [comment]
> To be clear, this is only a problem if different kinds of NaN values can be produced. In Haskell/Agda itself, this seems impossible according to Ulfs experiment and my own google searches. 

From Equations (9), (10) or (11) of [this](http://ezproxy.eafit.edu.co:2144/article/10.1007/s10817-014-9317-x) paper (free version [here](https://hal.inria.fr/hal-00862689)), it is possible to produce different kinds of NaN values using the `identicalIEEE` function. For example:

``` haskell
import Numeric.IEEE ( IEEE(identicalIEEE) )

nan1 :: Double
nan1 = 0.0/0.0

nan2 :: Double
nan2 = 42 - (-nan1)

GHCi> identicalIEEE nan1 nan2
False
```

**Comment by UlfNorell** [comment]
This is intriguing:

``` haskell
GHCi> let nan = 0.0/0.0 :: Double
GHCi> identicalIEEE (0 - nan) (-nan)
False
```

**Comment by asr** [comment]
I guess that happens because `nan` and `-nan` are different

``` haskell
GHCi> let nan = 0.0/0.0 :: Double
GHCi> identicalIEEE nan (-nan)
False
```

**Comment by UlfNorell** [comment]
Well yeah, I was just surprised that `0.0 - x` and `-x` was not the same thing.

I wrote a little Haskell program to search for different `NaN` values and it only found `-nan`. It did find a couple of ways to construct it though:

```
nan1 = asin -pi
     = asin -Infinity
     = - nan
```

It's also preserved by most operations of course.

**Comment by asr** [comment]
Since we are using Agda propositional equality on the compiler and the GHC backend, `primFloatEquality NaN -NaN` correctly will return `false` (I wrote 'will' because a `negate` function is not defined). On the other hand, it is necessary to fix the behaviour of `primFloatEquality NaN -NaN` on the JS and UHC backends.

**Comment by asr** [comment]
> The real-number semantics view as approximated by the IEEE standard, which introduces relations I propose to call “IEEE-equality” and “IEEE-order”, which are, as far as I know, not an equivalence relation respectively not an order relation, but still may have some uses in the world of applications of floating-point representations...

Could you show an example why the IEEE-equality is not an equivalence relation?

**Comment by UlfNorell** [comment]
Um, `NaN != NaN`?

**Comment by asr** [comment]
I meant using `identicalIEEE`.

**Comment by phile314** [comment]
I think @WolframKahl meant IEEE-equality to mean the "usual" numerical float equality, e.g. like Haskells Float Eq instance:

Propositional Equality View = bitwise Equality = `identicalIEEE`
Real Number Equality = Haskell Float Equality (NaN != NaN, -0.0 == 0.0) = IEEE-equality

The name of the Haskell `identicalIEEE` function is a bit confusing for this discussion....

**Comment by WolframKahl** [comment]
On Tue, Sep 20, 2016 at 01:04:25PM -0700, Andrés Sicard-Ramírez wrote:

> > The real-number semantics view as approximated by the IEEE standard, which introduces relations I propose to call “IEEE-equality” and “IEEE-order”, which are, as far as I know, not an equivalence relation respectively not an order relation, but still may have some uses in the world of applications of floating-point representations...
> 
> Could you show an example why the IEEE-equality is not an equivalence relation?

Off the bat, I believe that

  NaN != NaN

, that is, no reflexivity.

No time to look things up right now, sorry!

Wolfram

**Comment by asr** [comment]
For testing that `primFloatEquality NaN -NaN` returns `false`, I'm implementing `primFloatNegate`. Right now, I'm testing the implementation.

**Comment by asr** [comment]
- JS backend: 
  
  > Bitwise equality in JS should be possible by going via the byte representation[1].
  > 
  > [1] http://stackoverflow.com/a/14379836/6231928
  
  I couldn't distinguish `NaN` from `-NaN` using [1]. In addition, "to ECMAScript code, all NaN values are indistinguishable from each other" [2].
  
  [2] http://www.ecma-international.org/ecma-262/6.0/#sec-ecmascript-language-types-number-type
- GHC backend:
  
  @phile314 will disable the float equality primitive in the UHC backend

**Comment by phile314** [comment]
I did investigate this a bit more;-)

GHC uses the x86 change sign instruction `fchs` and does no special handling as far as I can see [1]. The `fchs` instruction seems to change the bit pattern according to my experiments. Test program:

```
#include <stdio.h>

void main() {

  double dst;
  double src = 0.0/0.0;
  asm("fldl %1;" // load
      "fchs;"   // change sign
      "fstl %0;"  //store
     : "=m" (dst)
     : "m" (src));
  printf("%f\n", src);
  printf("%f\n", dst);
  printf("%llx\n", *((unsigned long long int*)&src));
  printf("%llx\n", *((unsigned long long int*)&dst));
}
```

Output:

<pre>
-nan
nan
fff8000000000000
7ff8000000000000
</pre>

So it seems that Javascript is the outlier here.

[1] https://github.com/ghc/ghc/blob/b2c5e4ce5c44a7be7c2b81c2600cae40c5b225ad/compiler/nativeGen/X86/Ppr.hs#L844

**Comment by phile314** [comment]
This is actually unsolvable on JS. I don't have much time right now, will try to write this up in more detail this evening.

**Comment by asr** [comment]
Blocking #2208.

**Comment by asr** [comment]
> This is actually unsolvable on JS

Just out curiosity. Isn't it possible to call/use a C function as we did on the UHC backend?

**Comment by phile314** [comment]
Depends. On NodeJS it might be possible, but at least in the browser it wouldn't work. Not that I know of anybody using Agda to create client-side JavaScript.

**Comment by WolframKahl** [comment]
On Mon, Oct 03, 2016 at 09:59:15AM -0700, Philipp Hausmann wrote:

> Depends. On NodeJS it might be possible, but at least in the browser it wouldn't work. Not that I know of anybody using Agda to create client-side JavaScript.

Alan Jeffrey did.

I will most likely want to do that in the future --- currently I'm using Haste.

(But I will probably not need fully IEEE-conformant FP,
 and if I need FP at all, I will probably be happy with a more restrictive interface.)

Wolfram

**Comment by phile314** [comment]
So now here the more detailed answer. The whole Float story is a bit complicated, so let's start with a list of the goals of Agdas Float Support:

 I. All operations have to be (observationally) deterministic
 II. Operations should be fast <=> map more or less directly to hardware
 III. Floats should have decidable Equality
 IV. Floats can be used in the FFI to C/Javascript/etc..
 V. Floats can be used for serialization (e.g. network protocols)
 VI. Floats should be "roundtrip-safe". E.g. assuming we have a decode + encode function, it would be nice if `forall x . decode(encode(x)) = x` holds.

Now we can easily implement this for all float values except NaNs. The ieee standard specifies a whole range of NaN values which will be treated equal by all numerical operations. But we also have to keep the FFI and IO in mind. So here are some of the restrictions of our target hardware/languages:
1. x64 cpus produce two NaN values, NaN and -NaN
2. x64 native code can store any NaN values in memory
3. Javascript has exactly one NaN value. All other NaN values are normalized to one canonical NaN. This also applies to WebAssembly. [1, 2]
4. ARM always returns exactly the same NaN value [3].

I see two possible solutions:
1. Have only one logical NaN value. We loose roundtrip-safety (goal VI) that way. We can still allow FFI calls, but the FFI calls must yield the same result for all NaN values. For serialization, one would need to normalize the NaN values on encode and/or decode.
2. Have multiple NaN values. This is easy to do on x64. We cannot implement this on JS, but we could
   remove float equality (III) in the JS backend to work around that. We would also loose roundtrip-safety(VI) in the JS backend. Other CPUs might also be problematic as they produce different NaNs than x64, e.g. ARM.

I think proposal 1 fits nicer into Agda as that one should work equally well on all our current compiler targets and is more future-proof. It also makes for a seamless experience inside Agda itself and only imposes some costs when doing IO/FFI. Note that it would still be possible to implement an additional Float64 type with the x64 float semantics.

Any thoughts?

[1] https://wingolog.org/archives/2011/05/18/value-representation-in-javascript-implementations
[2] https://github.com/WebAssembly/design/pull/716/files
[3] http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0274h/Chdiibig.html

**Comment by identicalsnowflake** [comment]
> Not that I know of anybody using Agda to create client-side JavaScript.

I do!

I've been thinking about Float behavior some, since I'm using Floats a lot in WebGL geometries, so it matters to me.

How about a different paradigm: promise Floats will behave nicely in Agda so long as you only use them in ways which Floats model approximate computations of rational numbers. No support for undefined domains (divide by zero, tan of pi/2, etc.). Drop any regard for Nan and Infinity as they are explicitly not part of approximating calculations on rationals.

Bring back 0 = -0. `Float` is for use in real-world engineering, not rigorous constructive mathematics, and 0 != -0 is antithetical to that purpose (I've already undone this for myself).

In any case, whatever is decided, I think real-world use should trump formal consistency with `Float`. Allow the inconsistency with un-rational operations (divide by zero, etc) and ban Floats from Safe Agda.

**Comment by phile314** [comment]
> >    Not that I know of anybody using Agda to create client-side JavaScript.
> 
> I do!

Good to know :+1:

About float equality, do you actually need decidable propositional equality on floats or would an additional more real-wordy equality function suffice? E.g.:

```
-- returns true for 0 == -0, could also return false for NaN == NaN
-- Do not use this to construct equality proofs using trustMe!
primFloatNumericalEquality : Float -> Float -> Bool
```

This way you would still get a "reasonable" real-world comparison function without making Agda inconsistent.

**Comment by identicalsnowflake** [comment]
> do you actually need decidable propositional equality on floats or would an additional more real-wordy equality function suffice?... This way you would still get a "reasonable" real-world comparison function without making Agda inconsistent.

Sure, that sounds fine. It may make pattern matching on floats a bit surprising, though (ohno forgot to match on negative zero!). Also the same question comes up for less than (which I use far more often than equality): which equality does it respect? Usually you want `a ≤ b -> b ≤ a -> a = b`.

**Comment by nad** [comment]
>  It may make pattern matching on floats a bit surprising, though (ohno forgot to match on negative zero!).

Why would you want to pattern match on floating point values? (And why does Agda provide support for that?)

**Comment by identicalsnowflake** [comment]
> Why would you want to pattern match on floating point values?

Well "if x isn't zero, divide y by x` is pretty common in normal programming languages, even where "normal" means Haskell! [First Google result for Haskell gamma function](https://hackage.haskell.org/package/gamma-0.9.0.2/docs/src/Math-Gamma.html#gamma) pattern matches on floats!

> And why does Agda provide support for that?

I'm in favor of removing it if there's any ambiguity about which equality it's using.

**Comment by nad** [comment]
I don't think we should encourage people to divide by "not quite zero, but very close to zero", unless they know what they are doing.

**Comment by identicalsnowflake** [comment]
> I don't think we should encourage people to divide by "not quite zero, but very close to zero"

[Indeed!](https://github.com/agda/agda-stdlib/commit/96a9dc1f895113dae3e1771049e54e96b16608c7#diff-242b2552b8d597f44ad702b8c5bb0d6bR44)

**Comment by nad** [comment]
When they are using floats...

**Comment by identicalsnowflake** [comment]
@nad well that's kinda my point: I should be able to reason about Float using the same classical Algebra we all learned in secondary school with mostly good results.

Anyway, here are my contentions about Float equality and the place of Float in Agda in general:

### 1. Practical trumps theoretical for Float

None of us is using Float for its deep algebraic insight. Trading practical utility (0 = -0) to maintain theoretical rigor on divide by zero behavior is counterproductive. The point using dependent types is to avoid hitting the divide by zero case, not to distinguish between positive and negative zero. Why allow a case we intend to be unconstructable dictate policy and disrupt utility everywhere else? 

### 2. Float is useful in Agda, despite its lack of rigorous algebraic properties

But theoretical rigor is Agda's cup of tea, right? Can't those annoying Float users go play somewhere else? Do they even want what we're selling?

Yes! Dependent types allow me to maintain values in interval domains. For example, I was able to write `scale : ]0,∞[ → Geometry → Geometry`. I cannot write that in mainstream (Haskell) languages! Here is another example: I needed to convert between Spherical and Cartesian coordinates, and getting those formulas right is painful. So I just wrote this sanity check at the bottom while I tried to hack away at the definitions:

```
assertTinyError : [0,1]
assertTinyError = # (10000000.0 * sum errorΔs)
  where
    -- generate a point in each quadrant
    points : List ◼Point
    points = sequence $ repeat 3 (-1.0 ∷ 1.0 ∷ [])

    errorΔs : List Float
    errorΔs = (λ x → δ (●→◼ (◼→● x)) x) <$> points
```

Agda will now refuse to type check if my conversions don't satisfy that sanity check. This is not a proof, but it is useful and cheap! Dependent types enable this workflow.

## Summary

The utility of dependent types when working with Floats is totally independent of any mathematical rigor on `Float`. Trading some of this utility to preserve rigor in the divide by 0 case is counterproductive, because avoiding that case in the first place is why we're here.

**Comment by phile314** [comment]
I agree that `0.0 != -0.0` is not that useful in practice for doing any computations, but it is necessary to avoid making Agda inconsistent [ #2169 ]. Wolfram explained the same problem for primFloatLess quite nicely in https://github.com/agda/agda/issues/2194#issuecomment-247859528 .

I think the way forward is to have two equality primitives, a bitwise one for propositional equality and a numerical one which implements `0.0 == -0.0`.

Can you please take a look at this pull request, does that solve your problem:
https://github.com/agda/agda/pull/2237/files

**Comment by identicalsnowflake** [comment]
Sure, that looks fine. I have very few actual branching procedures on Float and they're all inside the same module, so pattern matching respecting the other equality won't bother me.

That being said, I think it needs to be made abundantly clear to new people that pattern matching uses an unintuitive equality, because it's normal for people even with Haskell backgrounds to pattern match on `0.0` (see that gamma lib I linked above).

In fact, if we have both equalities available, then I'm with @nad: pattern matching on Float literals should simply be disallowed entirely. Doing so will force users to be aware that there are two notions of equality and allow them to choose the one they want.

EDIT: Alternatively, instead of removing pattern matching entirely, you could simply force sign annotation on the pattern, so pattern matching on `0.0` would be an error, but `+0.0` and `-0.0` would be valid patterns.

**Comment by phile314** [comment]
This is Haskells take on it:

```
   let f x = case x of -0.0 -> -0.0; 0.0 -> 0.0
   -- f 0.0 == -0.0
   -- f (-0.0) == -0.0
```

I'm starting to agree that pattern matching on float literals might not be the best idea.

**Comment by UlfNorell** [comment]
Worth noting is that GHC **does not** give you an overlapping patterns warning for the code above.

**Comment by asr** [comment]
Also note that 

```
f 1.0 = True
f 1.0 = False
```

is accepted by Agda (GHC generates an overlapping-patterns warning).

**Comment by phile314** [comment]
There is only a single `NaN` value now in Agda, so this issue is obsolete.
