### ISSUE TITLE
Dot pattern regression(?)

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#2196]
Discovered by Sergei Meshveliani.

``` agda
data _≡_ {A : Set} (x : A) : A → Set where
  refl : x ≡ x

record _×_ (A B : Set) : Set where
  constructor _,_
  field fst : A
        snd : B
open _×_

EqP₁ : ∀ {A B} (p q : A × B) → Set
EqP₁ (x , y) (z , w) = (x ≡ z) × (y ≡ w)

EqP₂ : ∀ {A B} (p q : A × B) → Set
EqP₂ p q = (fst p ≡ fst q) × (snd p ≡ snd q)

works : {A : Set} (p q : A × A) → EqP₁ p q → Set₁
works (x , y) .(x , y) (refl , refl) = Set

fails : {A : Set} (p q : A × A) → EqP₂ p q → Set₁
fails (x , y) .(x , y) (refl , refl) = Set
-- Failed to infer the value of dotted pattern
-- when checking that the pattern .(x , y) has type .A × .A
```

Both works with `2.5.1.1`, neither with `2.4.2.5`. Personally I'm surprised either works, but it is a bit strange that there's a difference between `EqP₁` and `EqP₂`. @jespercockx ?

**Comment by andreasabel** [comment]
After record pattern translation, `EqP1` should be the same as `EqP2`.  Indeed, `C-c C-n` on `EqP1` gives

```
λ {A} {B} xy zw →
  (_×_.fst xy ≡ _×_.fst zw) × (_×_.snd xy ≡ _×_.snd zw)
```

as expected.

**Comment by mechvel** [comment]
Andreas asked for a self-contained example.
Try this:
`open import Relation.Binary using (Setoid; DecSetoid; DecTotalOrder)`
`open import Relation.Binary.PropositionalEquality as PE using (_≡_)`
`open import Data.Product                      using (_×_; _,_)`
`open import Relation.Binary.Product.Pointwise using (_×-setoid_)`
`open import Data.Nat                          using (ℕ; decTotalOrder)`

`natDecSetoid = DecTotalOrder.Eq.decSetoid decTotalOrder`
`natSetoid    = DecSetoid.setoid natDecSetoid`

`-- (by the way, it is desirable to have a shorter access to the  Setoid instance for ℕ)`  
`pSetoid  = natSetoid ×-setoid natSetoid`
`open Setoid pSetoid using () renaming (_≈_ to _=p_)`
`Pair = ℕ × ℕ`

`f :  {p1 p2 : Pair} → p1 =p p2 → ℕ`
`f {(m , n)} {.(m , n)} (PE.refl , PE.refl) =  0`

1) It is rejected by Development vesrion  of September 16, 2016.
2) The variant with `{(.m , .n)}` is type-checked.
3) I expect the Agda 2.5.1.1 will type-check both variants 
   (currently I have not 2.5.1.1 installed, but it type-checked a certain similar real example).

**Comment by andreasabel** [comment]
Ah, this was a stupid bug I must have introduced when adding postfix-projections.  ProjOrigin was not ignored in an equality test and lead to the different results.
