### ISSUE TITLE
The LaTeX backend messes up indentation

### ISSUE THREAD

**Issue by nad** [agda/agda#2198]
Consider the following literate Agda code:

```latex
\documentclass{article}

\usepackage{agda}

\begin{document}

A paragraph.

Some code:
\begin{code}
  postulate
    A : Set
\end{code}
The rest of the paragraph.

A third paragraph.

\end{document}
```

This code gets turned into the following document:
![bug](https://cloud.githubusercontent.com/assets/293222/18665650/7ece8f48-7f28-11e6-8663-dc7b67a85397.png)

There are several issues here:
- The start of the second paragraph is indented too much. (A bug.)
- The Agda code does not start on a line of its own. (A bug.)
- I think there should be some vertical space around the code.

lhs2TeX gets this right:

```
\documentclass{article}

%include polycode.fmt

\begin{document}

A paragraph.

Some code:
\begin{code}
  postulate
    A : Set
\end{code}
The rest of the paragraph.

A third paragraph.

\end{document}
```

When I preprocessed the code above using `lhs2TeX --agda --poly` and then compiled it I got the following result:
![bug](https://cloud.githubusercontent.com/assets/293222/18665828/494bd780-7f29-11e6-8827-fd6dfa6ec40e.png)

**Comment by andreasabel** [comment]
You need to add more empty lines.  This gives the output you expect:

``` latex
\documentclass{article}

\usepackage{latex/agda}

\begin{document}

A paragraph.

Some code:

\begin{code}

  postulate
    A : Set

\end{code}
The rest of the paragraph.

A third paragraph.

\end{document}
```

[Issue2198.pdf](https://github.com/agda/agda/files/482570/Issue2198.pdf)

**Comment by nad** [comment]
You can do this, but "empty line" in LaTeX means "new paragraph". I think that we should support idiomatic LaTeX code.

**Comment by andreasabel** [comment]
Seems like the discussion at #954 seems relevant here.

**Comment by nad** [comment]
I fixed the two bugs (by using lhs2TeX code written by @kosmikus). Extra vertical space is now inserted by default, but one can choose to omit this extra space. (See the [release notes](https://github.com/agda/agda/blob/c9065360ab8695bf71956ba75db2985b8c78634e/doc/release-notes/2-5-2.txt#L657-L672) for a little more information.)

@andreasabel and @stevana: Are you OK with the new implementation?

**Comment by stevana** [comment]
Fine by me, thanks for fixing it!
