### ISSUE TITLE
Add some more builtin trigonometric primitives

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#2200]
Currently the only builtin trig primitive I see is `primSin`. I'm trying to do some 3D coordinate computations, and I really need the rest of the trig functions -- especially the inverse trig functions, since I can't define those nicely in terms of `sin`.

**Comment by phile314** [comment]
Do you need these trig functions to reduce during type checking? If not, you can just use the FFI to import the corresponding Haskell functions. It would still be good to add them to the agda-stdlib/agda-prelude, but that's a separate issue.

**Comment by identicalsnowflake** [comment]
> Do you need these trig functions to reduce during type checking? 

Almost. I do a _lot_ of `C c C n` to quick-check computations, and postulating foreign bindings, compiling, and running is at least an order of magnitude slower workflow.

But no, I don't actually make my types dependent on floating point trig computations. I'm not _that_ dirty =)

**Comment by phile314** [comment]
Good point. This should be rather simple to add. Feel free to give it a go, these are the places one would need to change:
https://github.com/agda/agda/blob/0ee62a0171e6242d868e1c299d37e9ce07d52b43/src/full/Agda/TypeChecking/Primitive.hs#L725
https://github.com/agda/agda/blob/0ee62a0171e6242d868e1c299d37e9ce07d52b43/src/full/Agda/Compiler/MAlonzo/Primitives.hs#L174

Or if you don't want to do it yourself, could you post a list of the primitives which should be added?

**Comment by identicalsnowflake** [comment]
Ok nice, I'll try adding them there and see if I can get it to work.
