### ISSUE TITLE
Internal error when quoting

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#2203]
Using the same reflection scaffolding as before (in #2165), Agda throws an internal error when trying to reflect this `renderBuffer` function:

```
Point = Vec Float 3

renderBuffer : List Point → List Float
renderBuffer [] = []
renderBuffer ((x ∷ y ∷ z ∷ []) ∷ xs) = x ∷ y ∷ z ∷ renderBuffer xs
```

Message: `An internal error has occurred. Please report this as a bug. Location of the error: src/full/Agda/TypeChecking/Quote.hs:178`

**Comment by andreasabel** [comment]
Maybe the reflection framework could be changed such that quoted clauses also use de Bruijn patterns now (like the internal syntax).

**Comment by UlfNorell** [comment]
That would indeed make quoting simpler. I'm hoping this issue can fixed without it though, and save such a big change to the next release.

**Comment by identicalsnowflake** [comment]
> Maybe the reflection framework could be changed such that quoted clauses also use de Bruijn patterns now

What might this mean for me as a user? Is the `Term` or `Clause` structure going to change soon?

**Comment by UlfNorell** [comment]
If we did switch to deBruijn patterns it would mean changing the type of the `var` constructor in `Pattern` to also carry a deBruijn index in addition to the variable name. It won't happen in `2.5.2`.
