### ISSUE TITLE
Propose: To use markdown format in the CHANGELOG and the releases notes

### ISSUE THREAD

**Issue by asr** [agda/agda#2204]
I think it is unnecessary to mention the advantages. Anyone against this change?

**Comment by UlfNorell** [comment]
What's a quick way to check that you didn't mess up the markdown when adding things?

**Comment by asr** [comment]
You can use gitk on 31c6097.

**Comment by UlfNorell** [comment]
Sorry, by "you" I meant "me". Do you have a nice markdown viewer that you use to look at the changelog/release notes before pushing?

**Comment by andreasabel** [comment]
I try to remember... I think I used a browser plugin to view `.md` files.

**Comment by asr** [comment]
I couldn't find an off-line viewer with _exactly_ the same behaviour than GitHub.

I edited the file on Emacs using [markdown-mode](http://jblevins.org/projects/markdown-mode/) version 2.1. I also used this [on-line editor](https://jbt.github.io/markdown-editor/).

**Comment by nad** [comment]
> Do you have a nice markdown viewer that you use to look at the changelog/release notes before pushing?

I just discovered [Grip](https://github.com/joeyespo/grip), which seems to work well (`grip -b doc/release-notes/2-5-2.md`).
