### ISSUE TITLE
Parameter inference behaving strangely?

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#2206]
```
open import Agda.Builtin.Unit
open import Agda.Builtin.Nat

Interval : (a b : Nat) → Set
Interval a b = ⊤

example : Interval 0 1
example = tt

myFunction : ∀ {a b} → Interval a b → ⊤
myFunction _ = tt

badInference : ⊤
badInference = myFunction example
```

`badInference` should have all the information it needs, but yet Agda still complains that it can't figure out the `{a b}` to `myFunction`.

**Comment by nad** [comment]
You've given `example` the type `Interval 0 1`, but this type is definitionally equal to `Interval m n` for arbitrary `m` and `n`.

**Comment by identicalsnowflake** [comment]
Huh, well that's enlightening. It's amusing how much code I've written without properly understanding something as fundamental as parameter application 😄
