### ISSUE TITLE
Abstract is not treated correctly in anonymous local modules

### ISSUE THREAD

**Issue by nad** [agda/agda#2207]
The following code is incorrectly accepted by Agda:

```agda
module _ where

module _ where

  abstract

    A : Set₁
    A = Set

    F : A → Set
    F X = X

abstract

  G : Set → Set
  G = F
```

The code above should (according to the documentation of anonymous modules in the CHANGELOG) be equivalent to the code below, which is (correctly) rejected by Agda:

```agda
module _ where

private

  module <Fresh> where

    abstract

      A : Set₁
      A = Set

      F : A → Set
      F X = X

open <Fresh> public

abstract

  G : Set → Set
  G = F
```

This is a regression that was introduced in Agda 2.4.2.4. Bisection suggests that the bug was introduced by @andreasabel in 5fcb6e36fbfa7c8622aabda44dbff92facc61b42: [ Issue1366b ] Fixed by including abstract local defs in mutual injectivity check.

**Comment by UlfNorell** [comment]
As far as I can tell this is the intended behaviour. The fix to #1366 was precisely to make anonymous modules not have separate `abstract` spaces.

**Comment by nad** [comment]
That fix was intended for where modules. Now I have to (?) jump through hoops if I want to have multiple independent abstract blocks in a file:
```
private
  module Dummy₁ where
    abstract

      …

open Dummy₁ public

private
  module Dummy₂ where
    abstract

      …

open Dummy₂ public

abstract

  …
```

**Comment by nad** [comment]
I can see why the following code should be accepted (Agda 2.4.2.3 rejects it):
```
abstract

  A : Set₂
  A = B
    where
    B : Set₂
    B = Set₁

  C : A
  C = Set
```
However, it's less clear to me that the following code should be accepted:
```
A : Set₂
A = B
  where
  abstract
    B : Set₂
    B = Set₁

abstract

  C : A
  C = Set
```

**Comment by UlfNorell** [comment]
I think the current behaviour is the right one: anonymous modules and where-modules don't have separate abstract spaces. If you want separate spaces use named modules.

**Comment by nad** [comment]
OK, but in that case the documentation should be updated.
