### ISSUE TITLE
`primFloatLess` on `NaN`s

### ISSUE THREAD

**Issue by asr** [agda/agda#2208]
@UlfNorell  [wrote](https://github.com/agda/agda/issues/2169#issuecomment-246261081): 

> Looking at the code I noticed that `primFloatLess NaN NaN == true`, which is not good. That should be fixed...

The behaviour should be:

``` agda
primFloatLess NaN  NaN  ≡ false
primFloatLess -NaN -NaN ≡ false
primFloatLess NaN  -NaN ≡ false
primFloatLess -NaN  NaN ≡ true
```

**Comment by UlfNorell** [comment]
I suppose we should really handle the different kinds of NaNs here as well.

**Comment by asr** [comment]
Yes. Note that as @phile314 wrote:

> IEEE754 defines a total order, it might be best to use that. [1] No idea though how to get that total order in Haskell, doesn't seem to be present in the ieee754 package.
> 
> [1] https://en.wikipedia.org/wiki/IEEE_floating_point#Total-ordering_predicate

The above link points out  §5.10 of "IEEE Computer Society (August 29, 2008). IEEE Standard for Floating-Point Arithmetic". After glimpsing that section, I noticed we need fix?/add some comparisons.

**Comment by UlfNorell** [comment]
`-NaN < NaN` fails on JS backend.

**Comment by asr** [comment]
After editing the OP, the current status is
- `primFloatLess NaN NaN ≡ primFloatLess -NaN -NaN ≡ primFloatLess NaN -NaN ≡ false`
  
  Agda compiler ✓
  GHC backend ✓
  JS backend ✓
  UHC backend ✓
- `primFloatLess -NaN NaN ≡ true`
  
  Agda compiler ✓
  GHC backend ✓
  JS backend x
  UHC backend ✓

**Comment by asr** [comment]
Blocked by #2194.

**Comment by phile314** [comment]
@asr Is there a reason we treat `NaN` as greater than `-Infinity` currently? If we would treat `NaN` as less than `-Infinity`, we could use Haskells Ord instance directly without any special cases.

**Comment by UlfNorell** [comment]
No, I was just reluctant to put anything below negative infinity. Feel free to change it.

**Comment by asr** [comment]
> @asr Is there a reason we treat `NaN` as greater than `-Infinity` currently?

Item d.2 of §5.10 in [1] says:

> totalOrder(x, +NaN) is true where +NaN represents a NaN with positive sign bit and x is a
> floating-point number.

[1] IEEE Computer Society (August 29, 2008). IEEE Standard for Floating-Point Arithmetic.  §5.11, p. 29.
