### ISSUE TITLE
Possibly intended regression related to η-equality

### ISSUE THREAD

**Issue by nad** [agda/agda#2209]
The following code is accepted by Agda 2.5.1.1, but not by Agda 14b9fbb11264a136f6b1e92373ee4a9149d006e4:

``` agda
postulate
  A : Set
  a : A

data _≡_ (x : A) : A → Set where
  refl : x ≡ x

cong : (f : A → A) (x y : A) → x ≡ y → f x ≡ f y
cong f x .x refl = refl

record R : Set where
  field
    f : A → A → A
    g : A → A

  h : f a a ≡ a → f (f a a) (g a) ≡ f a (g a)
  h = cong (λ y → f y _) (f a a) a
```

Bisection suggests that this change in behaviour was introduced by @andreasabel in bb4e5b79e59a0cc24cfb723ef808214695f6c8cd: "Fixed #2197.  Turn eta on only after positivity checking."

If η-equality for `R` is turned off, then the code above is rejected by Agda 2.5.1.1. However, I fail to see why the result should be affected by the presence or absence of η-equality. Unsolved constraints:

```
  [49] _16 (f a a) = g a : A
  [49] _16 a = g a : A
  [0] _17 := λ → cong (λ y → f y (_16 y)) (f a a) a
        [blocked on problem 49]
```

Can someone enlighten me? Or is this a bug?

**Comment by UlfNorell** [comment]
Without looking too closely I suspect this is the key constraint:

```
[49] _16 (f a a) = g a : A
```

It's really `_16 r (f r a a) = g r a : A` but with η-equality it can be simplified to `_16 (f r) (g r) (f r a a) = g r a : A`, which after some pruning can be solved with `_16 := λ _ x _ → x a`.

**Comment by nad** [comment]
OK. This regression might affect other users as well, so perhaps we should warn them. However, I see that it is already documented in the release notes, and I don't think we need to do more.
