### ISSUE TITLE
Get rid of mvPermutation

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2212]
As I can see, the `mvPermutation` is only different from the identity permutation when we prune a meta.  The new meta (with pruned arguments) is created in the same context as the old meta (without the pruning).  The `mvPermutation` makes up for this.  Instead, we could create the new meta in the pruned context, getting rid of the `mvPermutation`.

**Comment by andreasabel** [comment]
Mmh, a meta carries the whole `TCEnv`.  Thus we would not only have to update the `envContext` but also possibly the `envLetBindings`!?

**Comment by UlfNorell** [comment]
I don't see how the meta could rely on the let bindings though. There's no way to refer to a let-bound value in internal syntax.

**Comment by andreasabel** [comment]
I am not motivated to do this in the near future.
