### ISSUE TITLE
GHC backend error

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#2216]
```
private
  absv : Float → Float
  absv x with x <? 0.0
  absv x | yes _ = -1.0 * x
  absv x | no _ = x

mean : ∀ {n} → Vec Float (ℕ.suc n) → Float
mean xs = primFloatDiv (foldl _+_ 0.0 xs) (primNatToFloat (length xs))

standardDeviation : ∀ {n} → Vec Float (ℕ.suc n) → Float
standardDeviation xs = let μ = mean xs in mean ((λ x → absv (primFloatMinus x μ)) <$> xs)

z-score : (μ σ x : Float) → Float
z-score μ 0.0 x = 0.0
z-score μ σ x = primFloatDiv (primFloatMinus x μ) σ
```

The above code type checks, but when I try to compile it I get `An internal error has occurred. Please report this as a bug. Location of the error: src/full/Agda/Compiler/ToTreeless.hs:194`.

The problem seems to be in `z-score` (probably the pattern match on `0.0`), because when I comment it out, the error goes away.

**Comment by nad** [comment]
Please provide self-contained code.

**Comment by UlfNorell** [comment]
That's not necessary. It's quite obvious what the problem is. But here's one if you're extremely curious

``` agda
open import Agda.Builtin.Float

foo : Float → Float
foo 0.0 = 1.0
foo x = x
```

**Comment by UlfNorell** [comment]
Travis tests are failing for the JS backend. The generated code looks ok to me, so maybe someone that knows about JS can have a look.

**Comment by identicalsnowflake** [comment]
Here's the `isZero` generated code for me:

``` js
exports["isZero"] = function (x0) {
    if ((agdaRTS.primFloatEquality)(0.0, x0)) {
      return "pos";
    } else {
      return "nonzero";
    }
  };
```

I think there's two problems: first, [primFloatEquality](https://github.com/agda/agda/blob/master/src/data/JS/agda-rts.js#L61) is curried in the RTS, but this `isZero` function is performing a normal two-parameter function application. Second, and probably the harder one, I don't even see a branch in the generated code for "neg" at all.

**Comment by UlfNorell** [comment]
I get the negative case on my machine. Fixed the currying problem and letting Travis have a go.

**Comment by asr** [comment]
~~Note that in the last line of the test case~~

~~out >  inf  -inf   nan  -nan  |  x~~
~~out >    x     -     -     -  |  Infinity~~
~~out >    -     x     -     -  |  -Infinity~~
~~out >    -     -     x     -  |  NaN~~
~~out >    -     -     -     x  |  NaN~~

~~`NaN` should be `-NaN` (I filed #2221 for this issue).~~

**Comment by asr** [comment]
Oops, the above comment belongs to a different issue.

**Comment by UlfNorell** [comment]
You know you can delete comments right?

**Comment by asr** [comment]
Right.
