### ISSUE TITLE
Abort Agda without losing state

### ISSUE THREAD

**Issue by nad** [agda/agda#2217]
I think it would be nice to be able to abort the current command in the Emacs mode, without having to reload interfaces from disk, or lose the --caching cache.

**Comment by nad** [comment]
I've implemented an abort command. When a command is aborted the previous persistent state and the previous options are restored. One might want to take this a step further by preserving some of the changes to the persistent state inflicted by the aborted computation.

**Comment by asr** [comment]
@nad, I added the missing milestone.

**Comment by nad** [comment]
I thought milestones were targets: "We intend to resolve this issue before this version is released, or at least make an active choice to not do so".

**Comment by asr** [comment]
Some of us are using them as TODO/DONE lists.

**Comment by andreasabel** [comment]
A milestone should list the issues fixed for this release (or possible fixed unnoticed before).
I used the milestone to extract a list of fixed bugs for the CHANGELOG, see https://github.com/agda/agda/blob/master/src/issues/ClosedIssuesForMilestone.hs .
