### ISSUE TITLE
`primShowFloat -NaN` should return `"-NaN"` 

### ISSUE THREAD

**Issue by asr** [agda/agda#2221]
``` agda
open import Agda.Builtin.Equality
open import Agda.Builtin.Float

NaN : Float
NaN = primFloatDiv 0.0 0.0

-NaN : Float
-NaN = primFloatNegate NaN

primShowPositiveNaN : primShowFloat NaN ≡ "NaN"
primShowPositiveNaN = refl

primShowNegativeNaN : primShowFloat -NaN ≡ "-NaN"
primShowNegativeNaN = refl

-- Test.agda:14,23-27
-- "NaN" != "-NaN" of type .Agda.Builtin.String.String
-- when checking that the expression refl has type
-- primShowFloat -NaN ≡ "-NaN"
```

The issue should be fixed in:
- [ ] Agda compiler
- [ ] GHC backend
- [ ] JS backend
- [ ] UHC backend

**Comment by UlfNorell** [comment]
This isn't really a bug. One can argue whether we want the show function to be as precise as possible, but I worry what we would then do when (if) we discover ways to construct other NaN values. I think having all NaNs show as `"NaN"` is perfectly respectable.

**Comment by phile314** [comment]
There is no `-NaN` value anymore, so this issue is obsolete.
