### ISSUE TITLE
LaTeX backend + XeLaTeX/LuaLaTeX ⇒ no lambda

### ISSUE THREAD

**Issue by nad** [agda/agda#2225]
Consider the following code:

```latex
\documentclass{article}

\usepackage{agda}

\begin{document}

\begin{code}
  id : Set → Set
  id = λ A → A
\end{code}

\end{document}
```

If this document is compiled using `agda --latex` and XeLaTeX or LuaLaTeX, then (with my current setup) the lambda character is not rendered. The problem is that the font chosen by `agda.sty` does not support λ:

```
Missing character: There is no λ in font cmss10!
```

The same problem applies to lots of other characters as well, for instance ℕ.

I can work around this problem in the following way:

```
% XITS Math does not appear to contain a sans serif version of λ, so I
% use the serif glyph instead.
\usepackage{newunicodechar}
\newunicodechar{λ}{\ensuremath{\mathrm{λ}}}
```

However, I think it would be good if the default settings worked better.

**Comment by gallais** [comment]
We (@pigworker and @jmchapman) have encountered the same issue recently. We noticed that it went away when using an older version of texlive (2014.20141024-2 on debian stable in particular).

**Comment by nad** [comment]
Have you figured out what the difference is between the two versions of TeX Live? Does the older one employ some kind of workaround? Have glyphs been removed from the XITS Math font?

**Comment by gallais** [comment]
I looked into it some more. From my (extremely limited) understanding, the problem is that some XITS styles (is that the proper term?) may not be available and xelatex defaults to the basic font (cmss10).

Seeing that ℕ was typeset properly in running text and omitted in Agda code, I tried to get the running text's style used for Agda code. Basically more or less what you were doing already with `\newunicodechar` but at the level of agda.sty. 

So this is a candidate for a patch. If that's indeed fixing your problem, I'll push it.

````diff
153c153
<   \newcommand{\AgdaFontStyle}[1]{\ensuremath{\mathsf{#1}}}
---
>   \newcommand{\AgdaFontStyle}[1]{\ensuremath{\textrm{#1}}}
157c157
<       \newcommand{\AgdaKeywordFontStyle}[1]{\ensuremath{\mathsf{#1}}}
---
>       \newcommand{\AgdaKeywordFontStyle}[1]{\ensuremath{\textrm{#1}}}
````

You can apply it by saving it as `agda.sty.patch` and running `patch agda.sty agda.sty.patch`.

**Comment by gallais** [comment]
It'd be nicer to have a sans serif font for the code but unless there's been some new developments since last year, it looks like [that's not really a thing](http://tex.stackexchange.com/questions/224144/is-there-any-sans-serif-font-that-fully-supports-unicode-math).

**Comment by gallais** [comment]
Alternatively we can set a Sans font which has more unicode characters!

````diff
40a41
>     \setsansfont[Scale=MatchLowercase]{DejaVuSansMono.ttf}
48d48
< 
````

**Comment by asr** [comment]
+1.

I have had very few problems using DejaVuSansMono.ttf. In fact, this is the font I chose for the version of PDF + XeLaTeX of the documentation:

```
$ cd doc/user-manual
$ make latexpdf PDFLATEX=xelatex
```

using

```latex
\ifxetex
  \usepackage{fontspec}

  \setmonofont
    [ BoldFont       = DejaVuSansMono-Bold.ttf,
      ItalicFont     = DejaVuSansMono-Oblique.ttf,
      BoldItalicFont = DejaVuSansMono-BoldOblique.ttf,
      Scale          = MatchLowercase,
    ]
    {DejaVuSansMono.ttf}
\fi
```

**Comment by nad** [comment]
I tried using Deja Vu Sans and Deja Vu Sans Mono, but in my opinion this made some of the rendered documents uglier. Is it possible to use these fonts only for missing glyphs?

**Comment by nad** [comment]
> It'd be nicer to have a sans serif font for the code but unless there's been some new developments since last year, it looks like [that's not really a thing](http://tex.stackexchange.com/questions/224144/is-there-any-sans-serif-font-that-fully-supports-unicode-math).

There seems to be [work in progress](https://tex.stackexchange.com/questions/374250/are-there-opentype-sans-math-fonts-under-development).

**Comment by nad** [comment]
In the light of the action taken in relation to #3224 I'm closing this issue now.
