### ISSUE TITLE
open {{...}} gets hiding wrong

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#2226]
```agda

open import Agda.Builtin.Float
open import Reflection
open import Data.List hiding (_++_)
open import Data.Unit

-- Reflection overhead

infixl 6 _>>=_
_>>=_ = bindTC

defToTerm : Name → Definition → List (Arg Term) → Term
defToTerm _ (function cs) as = pat-lam cs as
defToTerm _ (constructor′ d) as = con d as
defToTerm _ _ _ = unknown

derefImmediate : Term → TC Term
derefImmediate (def f args) = getDefinition f >>= λ f' → returnTC (defToTerm f f' args)
derefImmediate x = returnTC x

reflectTerm : Name → TC Term
reflectTerm n = getType n >>= λ ty → getDefinition n >>= λ x → derefImmediate (defToTerm n x []) >>= λ x → checkType x ty

macro
  reflect : Name → Term → TC ⊤
  reflect n a = reflectTerm n >>= quoteTC >>= unify a

{- Define typeclass Semigroup a => Plus a -}

record SemigroupLaws {ℓ} (t : Set ℓ) : Set ℓ where
  infixr 5 _++_
  field
    _++_ : t → t → t
    -- associative : ∀ {a b c} → (a ++ b) ++ c ≡ a ++ b ++ c

record PlusOp {ℓ} (t : Set ℓ) : Set ℓ where
  field
    semigroup : SemigroupLaws t

  infixr 6 _+_
  _+_ = SemigroupLaws._++_ semigroup

instance
  floatPlus : PlusOp Float
  floatPlus = record { semigroup = record { _++_ = Agda.Builtin.Float.primFloatPlus } }

open PlusOp {{...}}

-- The issue:

works : Float
works = PlusOp._+_ floatPlus 3.0 5.0

resultWorks : Term
resultWorks = reflect works

fails : Float
fails = 3.0 + 5.0

resultFails : Term
resultFails = reflect fails
```

Consider the conflict above between `works/resultWorks` and `fails/resultFails`. Either `checkType` or the initial reflection process is conflating information about how instance arguments are handled.

EDIT: The error in `resultFails` is `Found an implicit application where an explicit application was
expected`

**Comment by UlfNorell** [comment]
Bisection points to 888f616 (my first use of `agda-bisect`!), so it looks like it not a reflection issue but rather a problem with `open M {{...}}`.

The body of `fails` is `PlusOp._+_ {{plusOp semigroupLaws}} 3.0 5.0`, which is not right.

**Comment by UlfNorell** [comment]
Here's a simplified example with some more information:

``` agda
open import Agda.Builtin.Float
open import Agda.Builtin.Reflection
open import Agda.Builtin.List
open import Agda.Builtin.Unit
open import Agda.Builtin.Equality

infixl 6 _>>=_
_>>=_ = bindTC

macro
  getDef : Name → Term → TC ⊤
  getDef x a = getDefinition x >>= quoteTC >>= unify a

record Foo (A : Set) : Set where
  constructor mkFoo
  field foo : A
  foo₁ : A
  foo₁ = foo

open module FooI = Foo {{...}}

postulate
  A : Set
  instance FooA : Foo A

bar : A
bar = foo

bar₁ : A
bar₁ = foo₁

pattern rArg v x = arg (arg-info v relevant) x
pattern vArg x = rArg visible x
pattern hArg x = rArg hidden  x
pattern iArg x = rArg instance′ x
pattern `? = hArg unknown

pattern fun₀ b = function (clause [] b ∷ [])
pattern fun₁ p b = function (clause (p ∷ []) b ∷ [])

-- foo {{r}} = Foo.foo {_} r
foo-def : getDef foo ≡ fun₁ (iArg (var "r")) (def (quote Foo.foo) (`? ∷ vArg (var 0 []) ∷ []))
foo-def = refl

-- foo₁ {{r}} = Foo.foo₁ {_} r
foo₁-def : getDef foo₁ ≡ fun₁ (iArg (var "r")) (def (quote Foo.foo₁) (`? ∷ vArg (var 0 []) ∷ []))
foo₁-def = refl

-- bar = Foo.foo {_} FooA
bar-def : getDef bar ≡ fun₀ (def (quote Foo.foo) (`? ∷ vArg (def (quote FooA) []) ∷ []))
bar-def = refl

-- bar₁ = Foo.foo₁ {_} {{FooA}}  -- wrong!
bar₁-def : getDef bar₁ ≡ fun₀ (def (quote Foo.foo₁) (`? ∷ iArg (def (quote FooA) []) ∷ []))
bar₁-def = refl                                       --  ^^^^
```

I'm surprised that `bar` and `bar₁` are calling `Foo` directly, instead of `FooI`.

**Comment by andreasabel** [comment]
Mmh, https://github.com/agda/agda/commit/888f6166fcb3dca42fc2f80b57d02fbd3d5bc414 looks rather like a harmless refactoring, splitting `projProper :: Maybe QName` into `projProper :: Bool` and `projOrig :: QName`.  
Maybe someone can spot an error that sneaked in.  
Are you sure about the bisect result?

**Comment by UlfNorell** [comment]
Yes. It checks with the commit just before (f8c8f04).

**Comment by identicalsnowflake** [comment]
@UlfNorell by checks you mean not checks, right? Your example type checks for me on current master, and it's supposed to fail, right?

Also, I question that bisect result as well: I can confirm your example doesn't build on https://github.com/agda/agda/commit/f8c8f049497d929973b36bed7c71ed3ceec7bf64, but I then tried it on https://github.com/agda/agda/commit/888f6166fcb3dca42fc2f80b57d02fbd3d5bc414 and it also did not build, so unless I made a mistake switching between checkouts (more than possible: Agda binaries don't include their commit hash in --version), https://github.com/agda/agda/commit/888f6166fcb3dca42fc2f80b57d02fbd3d5bc414 did not introduce this.

**Comment by asr** [comment]
> Agda binaries don't include their commit hash in --version

Right. See #2023.

**Comment by UlfNorell** [comment]
Yeah my example succeeds when the bug is present. I used the code in the OP for the bisection.

Here's what I'm getting on the code in the OP:

```
$ agda-f8c8f04 Issue2226.agda -v0 --ignore-interfaces
$ agda-888f616 Issue2226.agda -v0 --ignore-interfaces
Issue2226.agda:66,15-28
Function does not accept argument
{{plusOp {_} {_} (semigroupLaws {_} {_} primFloatPlus)}}
when checking that
{{plusOp {_} {_} (semigroupLaws {_} {_} primFloatPlus)}} 3.0 5.0
are valid arguments to a function of type
{ℓ : .Agda.Primitive.Level} {t : Set ℓ} (r : PlusOp t) → t → t → t
```

**Comment by identicalsnowflake** [comment]
Ah, I did the opposite. I tested yours but not mine (since I was having trouble with the standard library on old versions, for some inexplicable reason).

Anyway that means our two examples may be hitting two different problems.

**Comment by UlfNorell** [comment]
Use these imports for the OP instead of the stdlib ones:

``` agda
open import Agda.Builtin.Float
open import Agda.Builtin.Reflection
open import Agda.Builtin.List
open import Agda.Builtin.Unit
```

My code doesn't check with older versions because we've made some minor changes to how parameters to projections are reflected. It should be simple to adapt it to hit the issue in the OP also for the older commits though.

**Comment by UlfNorell** [comment]
What changed in 888f616 is that the type checker always returns the normalised projection when inferring a head application of a projection (`projDropParsApply` no longer takes the name of the projection). In most cases this is fine since they only differ in parameters and those aren't
stored anyway. It breaks down for instance modules (`open M {{...}}`) however, since there the hiding of the principal argument is changed.

Naively trying to go back to the old behaviour doesn't work since we seem to rely on the fact that projections are normalised (`TypeChecking.Substitute.conApp` can't handle non-normalised projections). I'll try to make the type checker return the normalised projection, but with correct hiding for instance modules.

**Comment by identicalsnowflake** [comment]
@UlfNorell Awesome! I'm so glad to hear this, since this is an important issue for me. I'm definitely not using the reflection APIs to cross-compile code (because that would be ridiculous), but if I were, I'd say that solving this issue would be an *amazing* productivity boost.

**Comment by andreasabel** [comment]
Previous milestone: 2.5.2.

This issue needs attention again, in my fix for #2963 I had to update the test case.

**Comment by UlfNorell** [comment]
Are you giving it the attention it needs or are you expecting me to do something (if so what)?

**Comment by andreasabel** [comment]
I am not very familiar with the reflection machinery.  Could you please review https://github.com/agda/agda/blob/86a3caca18a130f57dcd33caf935aee8542f9203/test/Succeed/Issue2226.agda#L59-L62 and check whether the new behavior is acceptable?

**Comment by UlfNorell** [comment]
That actually looks more correct than what we got before. You changed
```agda
foo₁ {{r}} = Foo.foo₁ {_} r
```
to
```agda
foo₁ {A} {{r}} = Foo.foo₁ {A} r
```
which to me makes a lot more sense.

**Comment by andreasabel** [comment]
Ok, thanks, I removed the TODOs in 553b281098741aa45fdd81f77f169e80ec8ec606 .
