### ISSUE TITLE
Performance regression in 2.5.1.1

### ISSUE THREAD

**Issue by nad** [agda/agda#2228]
I have some code which takes a lot longer to type-check using Agda 2.5.1.1 (or the current development version) than with Agda 2.4.2.5. Bisection first pointed me to 3c9ee59d16de305fe075a773fe0a710151ae8239: "[ sharing ] resurrected pointer term representation". However, sharing was not turned on by default in 2.5.1.1, so I doubt that this commit is responsible for the current slowdown. Unfortunately the problem exists also when I use 3a1184677e20a26ae993a91efe7e25f423e91242 ("[ issue 1457 ] added options --sharing and --no-sharing") and turn off sharing. (Agda is slow with sharing turned off, and even slower with sharing turned on.)

I don't currently have a small test case, but my big test case ends with code of the following shape:

```
X : Set₁
X = Set
  where

  <A corecursive definition, defined using copatterns.>

  <An /unrelated/ definition that matches on a record constructor.>
```

If I use the current development version of Agda and comment out either one of these definitions, then `X` type-checks almost instantly, and otherwise it takes perhaps 30 seconds to type-check.

When trying to produce a small test case I observed that the time required to check `X` can go down if I replace an abstract definition by a postulate. Does this hint provide enough information, or do you need an actual test case?

**Comment by UlfNorell** [comment]
> Does this hint provide enough information, or do you need an actual test case?

I guess that depends on whether you were going to track down the problem yourself, or if you want someone else to do it...

**Comment by nad** [comment]
I was hoping (but not expecting) that you would immediately understand that the problem is <something>, fix that, and construct a corresponding, small test case.

**Comment by nad** [comment]
OK, here is a test case. `Imports.agda`:

```
module Imports where

open import Prelude public
  using (lzero; ∃; _×_; _,_)

open import Equality.Propositional
  using (_≡_; equality-with-J)
open Equality.Propositional public
  using (_≡_)

open import H-level equality-with-J public
  using (Is-proposition; Proposition)
open import H-level.Closure equality-with-J public
  using (Π-closure; ×-closure)
```

`Bug.agda`:

```
open import Imports

postulate
  ext        : {A : Set} {B : A → Set} {f g : (x : A) → B x} →
               (∀ x → f x ≡ g x) → f ≡ g
  ∥_∥        : Set → Set
  ∥∥-is-prop : {A : Set} → Is-proposition ∥ A ∥
  _/_        : (A : Set) → (A → A → Proposition lzero) → Set
  box        : {A : Set} (R : A → A → Proposition lzero) → A → A / R
  A          : Set

abstract

  _⁻¹_ : (A → A) → A → Set
  f ⁻¹ y = ∥ (∃ λ n → f n ≡ y) ∥

  R : (A → A) → (A → A) → Set
  R f g = ∀ x → f ⁻¹ x → g ⁻¹ x

  R-propositional : ∀ f g → Is-proposition (R f g)
  R-propositional _ _ =
    Π-closure ext 1 λ _ →
    Π-closure ext 1 λ _ →
    ∥∥-is-prop

  S : (A → A) → (A → A) → Set
  S f g = R f g × R g f

  S-propositional : ∀ f g → Is-proposition (S f g)
  S-propositional f g =
    ×-closure 1 (R-propositional f g) (R-propositional g f)

  T : (A → A) → (A → A) → Proposition lzero
  T f g = S f g , S-propositional f g

record Unit : Set where
  coinductive
  field
    force : Unit

X : Set₁
X = Set
  where

  f : Unit → Unit
  Unit.force (f x) = f (Unit.force x)

  P : (g : A → A → A) (x : (A → A) / T) →
      ∃ (λ n → box T (g n) ≡ x) → Set₁
  P _ _ (_ , _) = Set
```

Test script, using [context.txt](https://github.com/agda/agda/files/502317/context.txt):

```
$ darcs get --context context.txt http://www.cse.chalmers.se/~nad/repos/equality
[...]
$ agda --no-libraries -i. -iequality/src Imports.agda
[...]
$ time agda --no-libraries -i. -iequality/src Bug.agda
[...]
real    0m31.745s
user    0m31.428s
sys     0m0.356s
```

If the abstract definitions in `Bug.agda` are replaced by one postulate (`T`):

```
$ time agda --no-libraries -i. -iequality/src Bug.agda
[...]
real    0m1.423s
user    0m1.372s
sys     0m0.048s
```

If `P` is commented out:

```
$ time agda --no-libraries -i. -iequality/src Bug.agda
[...] 
real    0m1.461s
user    0m1.432s
sys     0m0.028s
```

If `f` is commented out:

```
$ time agda --no-libraries -i. -iequality/src Bug.agda
[...]
real    0m1.491s
user    0m1.448s
sys     0m0.044s
```

**Comment by UlfNorell** [comment]
Where does `-v profile:10` claim the time goes?

**Comment by nad** [comment]
With imported modules already type-checked:

```
Total                        32,376ms           
Miscellaneous                    12ms           
Parsing                           4ms      (8ms)
Parsing.Operators                 4ms           
Import                            0ms           
Deserialization               1,384ms           
Scoping                           0ms      (0ms)
Scoping.InverseScopeLookup        0ms           
Typing                            4ms     (32ms)
Typing.With                       0ms           
Typing.OccursCheck                0ms           
Typing.CheckLHS                   0ms           
Typing.CheckRHS                  16ms           
Typing.TypeSig                   12ms           
Termination                  30,928ms (30,928ms)
Termination.Graph                 0ms           
Termination.RecCheck              0ms           
Termination.Compare               0ms           
Positivity                        0ms           
Injectivity                       0ms           
ProjectionLikeness                0ms           
Coverage                          0ms           
Highlighting                      0ms           
Serialization                     4ms      (8ms)
Serialization.BuildInterface      0ms           
Serialization.Sort                4ms           
Serialization.BinaryEncode        0ms           
Serialization.Compress            0ms           
DeadCode                          0ms           
ModuleName                        4ms           
```

Interesting. The termination checker uses `ignoreAbstractMode`, so that part of the puzzle makes sense.

The slowness is caused by a [call to `normalise`](https://github.com/agda/agda/blob/42f28f1a2d87fa4449beea067166f7ccc4104e1f/src/full/Agda/Termination/TermCheck.hs#L583) in `termClause'`. There is no documentation of why we use `normalise` there, but this call was introduced by @UlfNorell in 68c350baadb75e57f30705517ab98035c0e9331b ("normalise dot patterns when using them for termination (fixes issue 53)").

I have not tried to figure out why we only get the slowdown when we have two unrelated definitions in the where block.

(As an aside, if I use `-vterm.check.clause:25`, then I get `Panic: de Bruijn index out of scope: 3 in context []`.)

**Comment by UlfNorell** [comment]
Link to #53.

I believe we only use dot patterns for termination if termination checking fails without them?

**Comment by andreasabel** [comment]
There is a superfluous and unconditional call to `normalise` (executed even when we do not use the dot patterns).  If that is removed, the termination checking times goes down from 30000ms to 0ms.

**Comment by andreasabel** [comment]
I fixed the issue by removing that superfluous call to `normalise`, but there will be no regression test unless we integrate Nisse's equality library into the Agda test suite.

**Comment by nad** [comment]
> I fixed the issue by removing that superfluous call to `normalise`, but there will be no regression test unless we integrate Nisse's equality library into the Agda test suite.

Isn't it possible to construct a small test case?

**Comment by UlfNorell** [comment]
Of course it's possible. Feel free to give a go.

**Comment by nad** [comment]
The following code checks quickly with the new version of Agda, but not with the old one:

```agda
open import Agda.Builtin.Equality
open import Agda.Builtin.Nat

F : Nat → Set₁
F zero    = Set
F (suc n) = F n

abstract

  A : Set₁
  A = F 10000000000000000000000

G : (X : Set₁) → X ≡ A → Nat → Set₁
G .A refl zero    = Set
G .A refl (suc n) = G A refl n
```

However, in the light of #2231 I guess we should have a test case that does not rely on `abstract`.

I had guessed that the following code would be checked quickly, but it isn't. Is it necessary for Agda to reduce `A` when checking the constructor `refl`?

```agda
open import Agda.Builtin.Equality
open import Agda.Builtin.Nat

F : Nat → Set₁
F zero    = Set
F (suc n) = F n

A : Set₁
A = F 10000000000000000000000

G : (X : Set₁) → X ≡ A → Set₁
G ._ refl = Set
```

Replacing `X ≡ A` with `A ≡ X` does not help.
