### ISSUE TITLE
Enable bitwise equality on the UHC backend

### ISSUE THREAD

**Issue by asr** [agda/agda#2230]
The `identicalIEEE` function from the [ieee754](http://hackage.haskell.org/package/ieee754) package is implemented via a `*.c` file.

From the discussion on https://github.com/UU-ComputerScience/uhc/issues/86, UHC requires explicitly specified on the command-line invocation the `*.c` and `*.h` files.

I'll copy the required bits (including the LICENSE) from the ieee754 package.

**Comment by UlfNorell** [comment]
Couldn't you write the C code yourself and skip the huge license text?

**Comment by asr** [comment]
I wrote the `foreign import` but I copied the `identicalIEEE` function [here](https://github.com/agda/agda/blob/d4936b99bff4606b66563d00bf3c9b9977ec95a9/src/data/uhc-agda-base/src/UHC/Agda/Builtins.hs#L111-L116). If I rewrite the C code, do we need to include the licence text anyway?

**Comment by UlfNorell** [comment]
It's a trivial piece of code. I'm pretty sure you're in the clear as long as you don't copy it verbatim.
