### ISSUE TITLE
Sort inference fails for abstract data types

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2234]
``` agda
module Works where
  data D A : Set where
    c : A → D A

abstract
  data D A : Set where
    c : A → D A
```

For the `abstract` definition, the `A` is yellow.
See #418.

**Comment by nad** [comment]
> For the `abstract` definition, the `A` is yellow.

Isn't this correct behaviour? Without looking at the implementation you don't even know that `A` is a type.

**Comment by andreasabel** [comment]
I don't think we ever intended to support modules that export

```
D : _ -> Set
```

with an undetermined part `_` in the type signature.  What would that be good for?  How would you use `D`?

**Comment by UlfNorell** [comment]
I don't know about data types, but for functions the worry is that we infer something that is not a valid type outside the abstract block.

**Comment by nad** [comment]
@andreasabel, I don't understand what you mean. There is an unsolved meta-variable. Do we need special support for this kind of unsolved meta?

**Comment by andreasabel** [comment]
Ah, let's forget about it.
