### ISSUE TITLE
Case splitting while in record hole generates invalid syntax

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#2239]
``` agda
record Wrap (t : Set) : Set where
  field
    value : t

private
  wmap : ∀ {t₁ : Set} {t₂ : Set} (f : t₁ → t₂) → Wrap t₁ → Wrap t₂
  wmap f x = record { value = ? }
```

Case splitting on `x` above generates invalid syntax:

```
private
  wmap : ∀ {ℓ₁ ℓ₂} {t₁ : Set ℓ₁} {t₂ : Set ℓ₂} (f : t₁ → t₂) → Wrap t₁ → Wrap t₂
  wmap f record { value = value } = record { value = ? } }
```

**Comment by identicalsnowflake** [comment]
Possibly related -- the following yields an incorrect error:

``` agda
record Wrap (t : Set) : Set where
  field
    value : ⊤ → t

private
  wmap : ∀ {t₁ : Set} {t₂ : Set} (f : t₁ → t₂) → Wrap t₁ → Wrap t₂
  wmap f x = record { value = λ m → ? }
```

Attempting to case split on `x` here gives the error `Cannot pattern match on non-datatype t₁ → t₂`, but `x` doesn't even have type `t₁ → t₂` -- it has type `Wrap t₁`.

**Comment by andreasabel** [comment]
The first problem is a bug in either the emacs mode or the regions communicated to the emacs mode.  Before the fix of #2051, the rhs of a clause would be a hole when case splitting, in particular, nothing would come after the hole on the line.  Thus, the existing clause is only cut away to the end of the hole and replaced by the new clause.  This leads to syntax errors.  A more drastic example is 

``` agda
wmap f x = let y = {! x !} in {!!} -- comment to keep
```

which splits to

``` agda
wmap f record { value = value } = let y = ? in ? in {!!} -- comment to keep
```

**Comment by andreasabel** [comment]
The second problem seems to be very different.  Some de Bruijn index is off because we have been disregarding the lambda-bound variables on the rhs.  
I fixed this by subtracting the number of locals from the split index.

**Comment by andreasabel** [comment]
The first problem is caused by this elisp-code in `agda2-mode.el`:

``` elisp
(defun agda2-make-case-action (newcls)
  "Replace the line at point with new clauses NEWCLS and reload."
  (agda2-forget-all-goals);; we reload later anyway.
  (let* ((p0 (point))
         ;; (p1 (goto-char (agda2-decl-beginning)))
         (p1 (goto-char (+ (current-indentation) (line-beginning-position))))
         (indent (current-column))
         cl)
    (goto-char p0)
    (re-search-forward "!}" (line-end-position) 'noerr)
    (delete-region p1 (point))
    (while (setq cl (pop newcls))
      (insert cl)
      (if newcls (insert "\n" (make-string indent ?  ))))
    (goto-char p1))
  (agda2-load))
```

The end of the to-delete text is considered to be the next "!}".  This is no longer correct.

**Comment by andreasabel** [comment]
See also #2340 and #2628 and #2672.

**Comment by andreasabel** [comment]
And #2800.

**Comment by UlfNorell** [comment]
Merging with #2628.
