### ISSUE TITLE
Sphinx (1.4.8) complains about malformed table for Unicode subscript k, m and n

### ISSUE THREAD

**Issue by asr** [agda/agda#2244]
Using Sphinx 1.4.8, @UlfNorell reported [this](https://github.com/agda/agda/commit/a65696fb2a0705a574502dea51a32ca02aa5c692#commitcomment-19340139) issue. Travis and I couldn't reproduce it. Could someone confirm/disconfirm the issue? Which OS are you using? 

The issue:

```
$ git fetch
$ git checkout --track origin/doc
$ cd doc/user-manual/
$ make clean
$ make html
sphinx-build -b html -E -W -d _build/doctrees   . _build/html
Running Sphinx v1.4.8
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 47 source files that are out of date
updating environment: 47 added, 0 changed, 0 removed
reading sources... [100%] tools/package-system                                                                                                                                

Warning, treated as error:
/Users/ulfn/research/Agda/doc/user-manual/tools/emacs-mode.rst:207: ERROR: Malformed table.

+----------+-----------+-------------------+-------------+
| Hex code | Character | Short key-binding | TeX command |
+==========+===========+===================+=============+
| 2081     | ``\u2081``     | ``\_1``           |             |
+----------+-----------+-------------------+-------------+
| 2082     | ``\u2082``     | ``\_2``           |             |
+----------+-----------+-------------------+-------------+
| 2083     | ``\u2083``     | ``\_3``           |             |
+----------+-----------+-------------------+-------------+
| 2084     | ``\u2084``     | ``\_4``           |             |
+----------+-----------+-------------------+-------------+
| 2096     | ``\u2096``     | ``\_k``           |             |
+----------+-----------+-------------------+-------------+
| 2098     | ``\u2098``     | ``\_m``           |             |
+----------+-----------+-------------------+-------------+
| 2099     | ``\u2099``     | ``\_n``           |             |
+----------+-----------+-------------------+-------------+

make: *** [html] Error 1
```

**Comment by asr** [comment]
From Sphinx [documentation](http://www.sphinx-doc.org/en/stable/rest.html#tables), I realised we can/should use simple tables instead of grid tables.

@UlfNorell, replacing the offending table by the following one fix the problem?

```
========  =========  =================  ===========
Hex code  Character  Short key-binding  TeX command
========  =========  =================  ===========
2081      ``₁``      ``\_1``
2082      ``₂``      ``\_2``
2083      ``₃``      ``\_3``
2084      ``₄``      ``\_4``
2096      ``ₖ``      ``\_k``
2098      ``ₘ``      ``\_m``
2099      ``ₙ``      ``\_n``
========  =========  =================  ===========
```

**Comment by UlfNorell** [comment]
Yes it does. I suppose it got the character width wrong for the subscripts.

Will you replace the tables with the simpler syntax?

**Comment by asr** [comment]
> Will you replace the tables with the simpler syntax?

I did. I will add the missing symbols.

**Comment by UlfNorell** [comment]
Thanks.

**Comment by XachaB** [comment]
I think I am facing a similar issue. I get an error for a  table with combining unicode characters, such as õ  and ã:

    Running Sphinx v1.7.5
    
    [...]
    
    WARNING: Malformed table.
    +-----+
    | õ   |
    +=====+
    | ã   |
    +-----+

But not for a table without combining characters, such as:

    +-----+
    | o   |
    +=====+
    | a   |
    +-----+

I can't use another style of tables, as these are generated from markdown notebooks with nbconvert.

**Comment by asr** [comment]
@XachaB, are you having the issue when building the Agda user guide? Please note this isn't the bug-tracker for Sphinx.

**Comment by XachaB** [comment]
Oops, I was lost, indeed ! I apologize for the inconvenience. Should I delete the message ?
