### ISSUE TITLE
Case split produces invalid names when open import anonymous parametrised modules.

### ISSUE THREAD

**Issue by marco-vassena** [agda/agda#2245]
Pattern matching on a data type defined in a parametrised module and imported in another and opened anonymously, produces an invalid name (e.g. `.A.Foo.F`)

See attached code.

[qualified-import.zip](https://github.com/agda/agda/files/519148/qualified-import.zip)

Agda version 2.4.2.5

**Comment by asr** [comment]
Thanks for reporting the issue. I could reproduce the problem using the upstream version. The unzipped MVE is:

``` agda
$ cat A.agda
module A (𝓛 : Set) where

data Foo : Set where
  F : Foo
```

``` agda
$ cat B.agda
module B (𝓛 : Set) where

open import A 𝓛

foo : Foo -> Set
foo x = {!!}

{-
splitting on x produces:

foo .A.Foo.F = ?

Expected:

foo F = ?
-}
```

**Comment by andreasabel** [comment]
Thanks for the MVE.
It can't be a bug introduced by parameter-refinement as parameter-refinement did not exist in Agda 2.4.2.5.

**Comment by andreasabel** [comment]
Possibly related: #1278.

**Comment by UlfNorell** [comment]
You can see the problem without the import (although the import makes it more severe):
```agda
module _ where

module A (X : Set) where
  data Foo : Set where
    F : Foo

module B (X : Set) where
  open A X

  foo : Foo → Set
  foo x = {!x!} -- C-c C-c produces `foo A.F = ?`
```

**Comment by andreasabel** [comment]
Isn't this just and instance of #1932 ?

**Comment by UlfNorell** [comment]
Yes indeed. Closing as duplicate and taking #1932 out of the icebox.
