### ISSUE TITLE
Internal error with modules

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#2247]
Running `agda2-compute-normalized` in the goal gives the error message
`An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Substitute.hs:800`

Note that the module `M` is not used anywhere, but removing its definition makes the issue go away.

``` agda
module MM1 (A : Set) where
  postulate
    a0 : A

  module M1 (a : A) where
    postulate
      x : A

  module M2 (a : A) where
    x : A
    x = M1.x a

  module M = M1 a0

module MM2 (A : Set) where

  open MM1 A
  t : A
  t = {!M2.x!}
```

**Comment by nad** [comment]
Bisection suggests that the bug was introduced by @UlfNorell in f915b1e4ad3d41baa359b09e9e99a0b84f392dc7: "[ fixed #2210 ] display form bug in parameterised module".

**Comment by nad** [comment]
I have some code which triggers an internal error on `src/full/Agda/TypeChecking/Substitute.hs:802`. If the fix for the bug reported above does not solve my problem, then I can provide more details.

**Comment by nad** [comment]
My problem was also solved.
