### ISSUE TITLE
Superfluous parentheses when giving argument to prefix operator

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#2249]
When giving the argument `f a` in the goal below, parentheses are added around it. But `f f a` type-checks, so I don’t think the parentheses should be added.

``` agda
postulate
  A : Set
  a : A
  f_ : A → A

x : A
x = f {!f a!}
```

**Comment by andreasabel** [comment]
The current behavior goes back to at least 2.4.2.2.
The extra parentheses are not inserted if you define `f_` as `infixr`, e.g.

``` agda
infixr 30 f_
```

resulting in a `scopePrecedence` for the meta of

```
RightOperandCtx (Fixity {fixityRange = ..., fixityLevel = Related 30, fixityAssoc = RightAssoc})
```

The default (no fixity decl) is

```
RightOperandCtx (Fixity {fixityRange = , fixityLevel = Unrelated, fixityAssoc = NonAssoc})
```

The decision of whether to insert parentheses is done in `Fixity.opBrackets`.

The last reworking of operator parsing was done by @nad, so he might be able to tell you whether this can be fixed or not.

**Comment by nad** [comment]
As far as I recall I didn't make any major changes to the printing machinery.

**Comment by andreasabel** [comment]
The question here is whether `f_` should be assumed to be right-associative by default and related to itself.

**Comment by nad** [comment]
When it comes to parsing there is no difference between marking prefix (or postfix) operators `infix`, `infixl` or `infixr`, the associativity is ignored.

**Comment by UlfNorell** [comment]
So it would make sense for printing to behave the same way.

**Comment by guillaumebrunerie** [comment]
Duplicate of #737.
