### ISSUE TITLE
Instance resolution behaves inconsistently between type and body

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#2267]
```
record Eq (t : Set) : Set₁ where
  infix 1 _≡_
  field
    _≡_ : t → t → Set

open Eq {{...}}

record Semigroup (t : Set) : Set₁ where
  field
    _<>_ : t → t → t
    {{eq}} : Eq t

  field
    associative : ∀ {a b c} → (a <> b) <> c ≡ a <> (b <> c)

open Semigroup {{...}}

prf : ∀ {t : Set} {{s : Semigroup t}} → {a b c : t} → (a <> b) <> c ≡ a <> (b <> c)
prf = ? -- associative
```

Here you can see that Agda is happy and properly resolves the `<>` operator and even the `≡` from the superclass. However, write in `associative` for that hole and Agda will complain. Yet, manually pattern matching on the instance `{{s}}` and applying it to `associative` works.

It seems to be resolving `≡` from the same place top and bottom, but also forgetting that it resolved them from the same place and then complaining. (This is supported by the fact that removing `Eq` entirely and just hardcoding the builtin equality everywhere doesn't seem to have this issue.)

**Comment by UlfNorell** [comment]
It's not really inconsistent behaviour. The instance search problem you're trying to solve in the body is completely different from the one in the type. Solving the same problem works as expected with nothing unsolved:

``` agda
postulate
  bla : (t : Set) {any : Set} → any

prf : ∀ {t : Set} {{s : Semigroup t}} → {a b c : t} → (a <> b) <> c ≡ a <> (b <> c)
prf {a = a} {b} {c} = bla ((a <> b) <> c ≡ a <> (b <> c))
```

The problem is that there's nothing determining the type argument `t` to `associative`. Given a goal `Semigroup _X` for some metavariable `_X`, instance search will block, waiting for `_X` to be resolved before proceeding. If we didn't instance search would risk looping, for instance, instantiating `_X` to `List _Y` and applying a list instance `Semigroup t → Semigroup (List t)` to get a new goal `Semigroup _Y`. See the [user manual](http://agda.readthedocs.io/en/latest/language/instance-arguments.html#instance-resolution) for more details.

You can work around this by wrapping the equality in a datatype. This ensures that the type can be read off the goal:

``` agda
record Eq (t : Set) : Set₁ where
  field
    _≡_ : t → t → Set

infix 1 _≡_
data _≡_ {t : Set} {{eqt : Eq t}} (x y : t) : Set where
  wrapEq : Eq._≡_ eqt x y → x ≡ y
```

**Comment by identicalsnowflake** [comment]
Ok, I didn't understand your explanation at first, but I think I got it now: associative is _only_ seeing the goal `(a <> b) <> c = a <> b <> c` and from those _terms_ alone, there is no information about the type of `a`, `b`, and `c`, right? It is not "seeing" the `{a b c : t}`.

Hmm.

My fix then is definitely just to change `{a b c : t}` to `(a b c : t)`. And I now realize this isn't the first time I've hit this bump and reported it (sorry!).

That being said, I think what bothers me is that Agda doesn't "pair" the types I declare with the variables I declare--`a <> .... = ... c` is probably `def "<>" [var 0,var 1] ...` internally with no actual information about the type of those vars, right? But from my perspective as a user, I didn't just declare `var 0`, I declared `var 0` _of type t_, and when I reason about my code, I'm reasoning about it with that "of type t" in mind--which causes a bump when interfacing with Agda's reasoning because it doesn't retain that "of type t" everywhere.

Am I on the right track?

**Comment by UlfNorell** [comment]
No it knows the types of `a b c`, the problem is that there could be a different type `t'` with elements `a' b' c'` whose `Semigroup` instance also resulted in an `associative` of the right type. For instance,

``` agda
data Wrap (t : Set) : Set where
  wrap : t → Wrap t

instance
  EqWrap : {t : Set} {{_ : Eq t}} → Eq (Wrap t)
  _≡_ {{EqWrap}} (wrap x) (wrap y) = x ≡ y

  SemigroupWrap : {t : Set} {{_ : Semigroup t}} → Semigroup (Wrap t)
  _<>_ {{SemigroupWrap}} (wrap x) (wrap y) = wrap (x <> y)
  eq   {{SemigroupWrap}} = EqWrap
  associative {{SemigroupWrap}} {wrap x} {wrap y} {wrap z} = associative {a = x} {y} {z}

prf : ∀ {t : Set} {{s : Semigroup t}} → {a b c : t} → (a <> b) <> c ≡ a <> (b <> c)
prf {t} {a} {b} {c} = associative {t = Wrap t} {wrap a} {wrap b} {wrap c}
```

This is what I meant when I said there is nothing determining the type `t`.

**Comment by identicalsnowflake** [comment]
Wow, that definitely makes me rethink some of my APIs. Managing that in general could be challenging. Thanks for the example -- blows my mind!
