### ISSUE TITLE
Instance search loops on unconstrained module parameter

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#2269]
``` agda
data ⊤ : Set where
  tt : ⊤

data ⊥ : Set where

record Eq (t : Set) : Set₁ where
  field
    _≡_ : t → t → Set

open Eq {{...}}


module M {t₁ : Set} (t₂ : Set) where

  instance
    postulate
      weaken : ∀ {{i : Eq t₂}} → Eq t₁

open M ⊥

postulate
  _ : tt ≡ tt
```

Agda hangs indefinitely when attempting to type check the above.

**Comment by UlfNorell** [comment]
Here's a simplified version:

``` agda
data ⊥ : Set where

it : {A : Set} {{_ : A}} → A
it {{x}} = x

postulate Eq : Set → Set

instance
  postulate weaken : Eq ⊥ → Eq _

loop : Eq ⊥
loop = it
```

We don't have a termination checker for instances (#1743), so it is possible to make instance search loop. In this case Agda tries to apply the `weaken` instance and goes looking for an argument `Eq ⊥` instance even though it couldn't conclusively match the goal type.

**Comment by identicalsnowflake** [comment]
Well the pain point is the experience: when I hit this issue, it wasn't obvious to me that the type check loop was even related to instances at all.

I think it would be helpful even just saying "Instance search failed to find a result after 10s," if not an error maybe just a log entry. This makes it clear to me as a user that there is something pathological happening related to instance resolution and I need to investigate.

This addresses the user experience problem while avoiding the hard technical problem of deciding exactly how/when instance resolution would terminate (probably some nightmare related to fixed points?)

**Comment by UlfNorell** [comment]
I agree. I'm thinking the best solution is to put a depth limit on instance search to prevent loops.
