### ISSUE TITLE
C-c C-s should put new goals instead of underscores for unknown subterms

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#2273]
Doing `C-c C-s` in the following file replaces the goal by `_ == _` which is a bit strange. Underscores are supposed to represent values which are uniquely determined, which is not the case here. It would be nice if it replaced the goal by `? == ?` instead.

``` agda
postulate
  _==_ : {A : Set} (a b : A) → Set
  P : Set → Set
  f : {A : Set} {a : A} {b : A} → P (a == b)

x : P ?
x = f
```

**Comment by jespercockx** [comment]
In this case, the values of the arguments of `_==_` are uniquely determined, their unique values just happen to be the implicit arguments `a` and `b` of f, which are unsolved metas themselves. So I don't really see the problem with this behaviour, as solving the metas in the definition of `x` will also solve the inserted underscores.

**Comment by guillaumebrunerie** [comment]
Note that if I write instead

``` agda
x : P (? == ?)
x = f
```

then `C-c C-s` does not "solve" the two goals by underscores, so at least the behaviour seems inconsistent.

You’re right that the arguments of `_==_` are the implicit arguments of `f`, but those two terms can be given either in the term or in the type and here I would like to give them in the type and to use `C-c C-s` to solve constraints as much as possible but giving goals for what hasn’t yet been solved (at least from a user point of view).
My actual use case is as follows. I want to prove some equation `u == v` where typically `u` and `v` are complicated compositions of various paths/squares/cubes. I then write

``` agda
eq : (p : ?) […] (q : ?) -> u == v
eq = ?
```

where `p`, …, `q` are the variables appearing in `u` and `v`, and then I run `C-c C-s` to automatically deduce which of the arguments are paths, squares, and so on. I can then add additional arguments as needed, typically the endpoints of the various paths, using `C-c C-s` again to make sure constraints are satisfied (for instance if the composition of `p` and `q` appears somewhere in `u`, then they should be composable) until I get a complete type.
Right now, the types of the `p`, …, `q` are usually all instantiated to something like `_ == _` or `Square _ _ _ _` which is not what I would expect.

**Comment by guillaumebrunerie** [comment]
Note also that in

``` agda
x : P ?
x = f {a = ?} {b = ?}
```

then `C-c C-s` replaces the goal in `P` by `? == ?`, with two new goals.

**Comment by jespercockx** [comment]
You're right, that seems to be very weird behavior. As far as I know there's no formal description of what goals should be solved by C-c C-s, other than that they should be marked as solved internally. I can see at least two consistent specifications:
1. C-c C-s only solves goals if the solution contains no more metavariables, and keeps doing so until no more holes can be solved (this seems to be the closest to the current behavior).
2. C-c C-s solves all holes, but unsolved metavariables in solutions are replaced by new holes (this seems to be what you want).

Maybe we should have two separate commands for these two options?

**Comment by guillaumebrunerie** [comment]
I’m not sure I understand 1, do you mean that in my first example `C-c C-s` should do nothing at all given that `a` and `b` are metavariables? If so, it seems to me that 2 is strictly better than 1, do you have an example where you would want the behaviour of 1?

**Comment by jespercockx** [comment]
Well, right now C-c C-s solves all holes, not just the currently selected one. I use it often as a sanity check to see whether any of the holes I have left are unnecessary, but I wouldn't want it to touch the others. For a hypothetical variant of C-c C-s that works only on a single hole, I agree that 2 is strictly superior to 1.

**Comment by andreasabel** [comment]
See #1343.

**Comment by andreasabel** [comment]
I think the current behavior is consistent but arguably not very useful.

Guillaume, can one summarize your proposal as: !?

  If the user invokes C-c C-s then all unsolved meta-variables that are printed by this command should be turned into interaction metas.

**Comment by UlfNorell** [comment]
Here's my suggestion:
- In a goal: use instantiation for current meta, and replace unsolved metas with `?`
- At top-level: solve all goals that have been fully instantiated (i.e. no unsolved metas left)

**Comment by guillaumebrunerie** [comment]
It seems to me that there are two different uses of `C-c C-s`.

Either you want to use it to help you write terms, in which case it seems better to solve goals as much as possible and turn unsolved metas into interaction metas, as I’m proposing (whether in a goal or at the top-level).

Or you want to use it to check whether some goals are unnecessary, in which case
- goals with unsolved metas should be left alone,
- goals without unsolved metas should be replaced by underscores.

Maybe I’m missing something, but it seems to me that if you don’t want to partially solve goals which are not yet fully instantiated, then you don’t want to fully solve goals either. It seems sufficient to replace them by underscores.

Therefore my suggestion would be to have two different commands, as Jesper proposed, with the following behaviour:

The first one (`C-c C-s`)
- At top-level would solve all goals and turn unsolved meta-variables into interaction metas.
- In a goal, would do the same but only for the current goal

The second one (maybe `C-c C-u`, for "unnecessary") would replace all goals that have been fully instantiated by underscores and would not touch the others.

**Comment by jespercockx** [comment]
I think we should revisit this issue before the next release.

I agree with the proposal by @guillaumebrunerie that there should be two variants of the 'solve constraints'. The first one (C-c C-s) should turn all unsolved non-interaction metas into interaction holes, and vice versa also turn all interaction metas into underscores (since they already have a place in the source code for the user to interact with, they shouldn't be duplicated).

**Comment by jespercockx** [comment]
Here is a small example:
```agda
open import Agda.Builtin.Equality

postulate
  F : Set → Set
  A : Set

test : Set
eq : test ≡ F {!!}

test = {!!}
eq = refl
```
Using C-c C-s in the second hole currently solves the hole with `F {!!}`, thus creating a new interaction meta where none is needed. Instead, it should produce `F _`.
