### ISSUE TITLE
Solve C-c C-s drops regular meta variable arguments

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2280]
If you have a meta-variable of function type appearing in a solution to another meta, `C-c C-s` drops its arguments.  (This is because the implementation simply drops all meta arguments, even those which are not the "module" parameters of the meta.)

``` agda
open import Common.Equality

data Bool : Set where
  true false : Bool

postulate
  not : Bool → Bool

data D (f : Bool → Bool) : Set where
  c : ∀ x → x ≡ not (f true) → D f

test : D {!!}
test = c {!!} refl

-- C-c C-= says
-- ?1 := not (?0 true)

-- But C-c C-s solves
-- ?1 := not ?
```

**Comment by UlfNorell** [comment]
Isn't that better though? In this case you're getting a fresh meta anyway, so having it be applied to arguments will just make it harder to solve.

**Comment by andreasabel** [comment]
Ok, maybe you have a point here.  The new meta will again be constrained by `?1 := ?0 true`, but then solve does not do anything anymore, since the solution has a meta in the head.

However, if the dropping of all arguments is the blessed behavior, should not we also drop projections? 

Anyway, for projections, things go somehow wrong:

``` agda
data E (p : Bool × Bool) : Set where
  c : ∀ x → x ≡ not (proj₁ p) → E p

test2 : E {!!}
test2 = c {!!} refl
```

Constraint is

```
?3 := not (proj₁ ?2)
```

C-c C-s gives me

``` agda
test2 = c (not (proj₁ {!!})) refl
```

with new constraint

```
?5 := proj₁ ?2 , _38
```

Here, I can do `C-c C-s` again, getting

```
test2 = c (not (proj₁ (proj₁ {!!} , _))) refl
```

with new constraint

```
?6 := proj₁ ?2 , _46
```

etc. pp.

I think I will implement the "blessed behavior" consistently, i.e., dropping all arguments and all projections from the new interaction meta.
