### ISSUE TITLE
Provide a way to re-export qualified instance arguments

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#2281]
Motivating case:

``` agda
module Weakening {ℓ₁ ℓ₂} {t₁ : Set ℓ₁} (t₂ : Set ℓ₂) (f : t₁ → t₂) where

  instance
    eq : ∀ {ℓ'} {{_ : Eq {ℓ'} t₂}} → Eq t₁
    eq = weakenEq f

    decEq : ∀ {ℓ'} {{_ : Eq {ℓ'} t₂}} {{_ : DecEq t₂}} → DecEq t₁
    decEq = weakenDecEq f
    -- ... etc etc
```

I'm starting to generate a lot of my instances "automatically" via transport modules like the above. It's used like this:

```
-- free Char instances!
open Weakening N primCharToNat
```

It works great up through my `MyPrelude.agda` file, where I run into problems: I can import lots of files with instances generated this way, and I can avoid the name conflicts by only importing the file but not actually opening it, i.e., `import Instances.String` and `import Instances.Char` will allow instances from both to be resolved `MyPrelude.agda` without name conflicts.

The problem is I can't re-export them from `MyPrelude.agda` because I have no way of saying `import Instances.String public`, which would make the full qualified names (and hence, instances) available whenever someone imports my `MyPrelude`.

**Comment by andreasabel** [comment]
Can't you use just

``` agda
module CharInstances = Weakening N primCharToNat
```

in `MyPrelude`?  This will not open `Weakening`, but should still create the instances.

If I misunderstood you, please provide a self-contained example for experimentation.

**Comment by identicalsnowflake** [comment]
This is exactly what I needed, thanks! I had tried this before, but I had written `charInstances = Weakening N primCharToNat`. I hadn't realized I needed to prefix that declaration with the `module` keyword.

**Comment by andreasabel** [comment]
Good.  Maybe you found a design pattern here for collecting instances.  It might be worthwhile to write a blog article or add something to the Agda documentation.

**Comment by identicalsnowflake** [comment]
Hmm maybe. I need to figure what I'm actually doing. My stuff is all scatterbrained prototyping and experimenting right now. I don't even know if "weakening" is even a good word, or exactly which instances should be "inherited" there, whether requesting more parameters up front creates other interesting inheritance shapes, etc. etc.
