### ISSUE TITLE
An option to disable detection of datatypes satisfying K?

### ISSUE THREAD

**Issue by favonia** [agda/agda#2282]
I realized newer versions of Agda introduced some features that break our hacks for higher-inductive types, and found that the automatic detection of datatypes satisfying the axiom K might be the cause. I wonder if there's an option to disable it? This is crucial for higher inductive types to postulate paths after the definition, as follows: (The code is not self-contained; it depends on the `lib.Base` module in http://github.com/HoTT/HoTT-Agda)

``` agda
{-# OPTIONS --without-K #-}

open import lib.Base

module fail.Test2 where

module _ where

  private
    data #I-aux : Type₀ where
      #zero : #I-aux
      #one : #I-aux

    data #I : Type₀ where
      #i : #I-aux → (Unit → Unit) → #I

  I : Type₀
  I = #I

  zero : I
  zero = #i #zero _

  one : I
  one = #i #one _

  postulate
    seg : zero == one

absurd : zero ≠ one
absurd ()  -- fails
```

**Comment by jespercockx** [comment]
This feature has already been removed completely from the current stable because of a different issue (#2003). I'm still thinking of a better way to include it again in the future, but I'll try to remember testing any future versions against HoTT-Agda before pushing.

**Comment by favonia** [comment]
Sorry I did not realize it was removed. How should I help the testing? This feature only permits more proofs so checking the entire HoTT-Agda (which is very CPU/memory-demanding) is not helpful. Also I am not sure if supporting HIT hacks is part of the Agda goal. We do have some testing files in https://github.com/HoTT/HoTT-Agda/tree/master/test to test whether our current HIT hacks are likely to work.

**Comment by jespercockx** [comment]
I don't know how you can currently help testing this feature, as I'm not even really sure how to specify it (see the other issue I mentioned). I can however notify you if I get an idea for the new version.

The 'officially supported' way to hack HITs in Agda is with rewrite pragmas.
