### ISSUE TITLE
Disallow duplicate bound variable in lambda and pi

### ISSUE THREAD

**Issue by asr** [agda/agda#2284]
Agda should complain about duplicate bounded variables in

``` agda
bad : Set → Set → Set
bad = λ x x → x
```

(GHC correctly rejects that function).

**Comment by andreasabel** [comment]
See #359 for an entry point about shadowing discussions.

I think GHC's behavior is the right one.  It seems really stupid to abstract over `x` twice **in the same lambda**.

**Comment by asr** [comment]
> See #359 for an entry point about shadowing discussions.

Thanks. Reading the examples in that issue (and the merged ones) was illustrative.

> I think GHC's behavior is the right one.  It seems really stupid to abstract over `x` twice **in the same lambda**.

I edited the OP. Now, It only points out this situation.

**Comment by UlfNorell** [comment]
Fixing this would make normal lambdas behave more like pattern lambdas, which, like left-hand sides, don't allow shadowing.

If we fix this we should also make sure the same rules apply to pi types:
```agda
postulate
  bad₁ : (A A : Set) → Set
  bad₂ : (A : Set) (A : A) → Set
  ok : (A : Set) → (A : A) → Set
```

**Comment by jespercockx** [comment]
When refactoring the LHS checker this winter, I introduced a field `scopeVarsToBind` to the `ScopeInfo` that keeps track of a bunch of variables that should be bound but cannot contain any shadowing. Maybe this could be used as well for checking lambda's and pi's binding multiple variables?

EDIT: actually in the LHS they *can* contain multiple equal names, in which case all but one are treated as dot patterns. I guess for lambda and pi it makes more sense to throw the error during scope checking already.

**Comment by andreasabel** [comment]
See #3989 for some work in this direction.
