### ISSUE TITLE
Refining a hole with a non structurally smaller expr makes Agda loop

### ISSUE THREAD

**Issue by carlostome** [agda/agda#2286]
``` agda
module Example2 where

data Nat : Set where
  zero : Nat
  succ : Nat → Nat

data _==_ {A : Set} (x : A) : A → Set where
  refl : x == x

add : Nat -> Nat -> Nat
add x y = {!add x x!}

p1 : (n : Nat) -> add zero n == n
p1 n = refl
```

If we try to input the expression in the hole, Agda will fall in a loop. I guess the problem lies in Agda not passing the termination checker to the expression in the hole before trying to actually typecheck the module.

Also this other issue might be related: #42

**Comment by jespercockx** [comment]
See also #118

**Comment by andreasabel** [comment]
When giving `add x x` and before solving any constraints, we should redo the termination check for `add`.  Working on this...
