### ISSUE TITLE
Make it possible to leave out instance fields for copattern matches

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#2288]
When writing instance for complex hierarchies you get a lot of code like

```agda
instance
  InstA : SomeClass A
  f {{InstA}} = ...
  super₁ InstA = it
  super₂ InstA = it
```

where `f` is a member function and `super₁` and `super₂` are super class projections (and `it` solves a goal using instance search). It would make things a lot nicer if you could leave out the super class clauses.

It should be quite possible to do this: at the point where the coverage checker figures out that there is a case missing we have an `ArgInfo` telling us the hiding of the right-hand side. If it's `Instance`, we could simply add the missing clause with an instance meta as the right-hand side.

**Why only instance arguments and not implicits as well?**

That would make sense, but it looks like it would be much harder. Implicit fields typically appear in the types of later fields, which means we need to introduce the metas for implicit right-hand sides **before** checking the later clauses. When we find out in the coverage checker that a clause is missing, it's too late.

**Comment by jespercockx** [comment]
Nice!

**Comment by UlfNorell** [comment]
Not quite working yet. Looks like the context gets messed up

``` agda
record Functor (F : Set → Set) : Set₁ where
  field
    fmap : ∀ {A} → F A → F A

record Alternative (F : Set → Set) : Set₁ where
  field
    plus : ∀ {A} → F A → F A → F A
    overlap {{super}} : Functor F

open Functor {{...}}
open Alternative {{...}}

postulate
  T : Set → (Set → Set) → Set → Set

module _ {S : Set} {F : Set → Set} where

  instance
    FunctorT : {{FunF : Functor F}} → Functor (T S F)
    fmap {{FunctorT}} x = x

    AlternativeT : {{AltF : Alternative F}} → Alternative (T S F)
    plus {{AlternativeT}} x y = x
    --- No instance Functor (T S F)
```

Debug output from instance search:

```
  target: Functor (T S F)
  candidates
  - AltF : Alternative F
  - overlap Alternative.super AltF : Functor F
  - FunctorT : {{FunF : Functor AltF}} → Functor (T F AltF)
```

The type of `FunctorT` is not taking into account the `AltF` in the context.
