### ISSUE TITLE
internal error at src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs:1172

### ISSUE THREAD

**Issue by Aerate** [agda/agda#2291]
When calling the type of helper function (C-c C-h) and using an expression with an implicit argument (appearing by itself):
```agda
record Foo : Set where
  coinductive
  field
    one : Bool
 
someFoo : Foo
Foo.one someFoo = {!!}
```
`{R} -> Foo.one R`

yields

> An internal error has occurred. Please report this as a bug.
> Location of the error: src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs:1172

**Comment by andreasabel** [comment]
Well, `{R} -> Foo.one R` is not valid syntax.  Can you tell what you put in the hole before hitting C-c C-h?

**Comment by Aerate** [comment]
The hole was empty as in the given example before hitting C-c C-h , I then entered the (invalid) expression where emacs-mode asks for it.
I understand this is invalid syntax (forgotten quantifier); I am still learning and was just trying things out, so unfortunately I can't provide more contextual information that might help. Still, I would have expected something like a parse error but instead got the internal error message above.

**Comment by andreasabel** [comment]
Ah, ok, I get it now.

``` agda
record Foo : Set where
  coinductive
  field one : Foo
open Foo

someFoo : Foo
someFoo .one = {!{R} -> Foo.one R!}

-- C-c C-h gives:
-- An internal error has occurred. Please report this as a bug.
-- Location of the error: src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs:1248
```

**Comment by andreasabel** [comment]
Simplified test case:

``` agda
test = let {_} = _ in _
```

**Comment by andreasabel** [comment]
Thanks for reporting.
