### ISSUE TITLE
Parser should allow stacking of layout keywords

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2294]
The parser rejects
```agda
private abstract
  test : Set1
  test = Set
```
However, this could be made to parse and would be a sensible extension.

**Comment by UlfNorell** [comment]
Would (could) you also allow

``` agda
private module M where
  test = Set
```

?

**Comment by andreasabel** [comment]
Yes, that would make sense.

**Comment by guillaumebrunerie** [comment]
We wanted to do that with Favonia a few years ago, but we gave up as we weren’t really sure what the rules should be, see #1145.

**Comment by andreasabel** [comment]
Maybe we should continue the discussion at #1145 then.
