### ISSUE TITLE
Problem related to parameter refinement and with

### ISSUE THREAD

**Issue by nad** [agda/agda#2297]
The following code is rejected by `2.6.0-99eb1a3`, but I think it should be accepted:
```agda
record R : Set₁ where
  field
    A : Set

module _ (r : R) where

  open R r

  data D : Set where
    c : A → D

  data P : D → Set where
    d : (x : A) → P (c x)

  postulate
    f : D → A

  g : (x : D) → P x → D
  g x (d y) with Set
  g x (d y) | _ = x
```
If I infer the type of `x` in the final right-hand side I get `D`, and the goal type is also `D`. However, Agda complains:
```
y !=< r of type R
when checking that the expression x has type D
```

**Comment by andreasabel** [comment]
Agda infers that `x` has type `D[y/r]`, but it here something of type `D[r/r]` is required.
Internally `x = c y` because it should be a dot-pattern, but the type of `x` seems messed up.

**Comment by UlfNorell** [comment]
There's also something funning going on with `x` showing up twice in the context. One occurrence is the dot pattern variable from before the `with`, which isn't actually in scope.

**Comment by UlfNorell** [comment]
Test case now passes, but there's still the issue of the two `x`s.

**Comment by UlfNorell** [comment]
That seems to be a general problem with `@`-patterns and `with`. I'm opening a separate issue.
