### ISSUE TITLE
Support for multi-line string literals in the LaTeX backend

### ISSUE THREAD

**Issue by gallais** [agda/agda#2304]
Using a multi-line string literal leads to a broken TeX file. Here is an example:

````agda
\documentclass{article}
\usepackage{agda}
\begin{document}
\begin{code}
open import Data.String

argh =  "Hello, 
\       \World!"
\end{code}
\end{document}
````

leads to (focusing on the important part):

````latex
\>\AgdaFunction{argh} \AgdaSymbol{=} \<[8]%
\>[8]\AgdaString{"Hello, \<\\
\>\textbackslash{}       \textbackslash{}World!"}\<%
````

I guess a possible fix would be to close `\AgdaString` before a newline, reopen it afterwards and repeating the process until a non-escaped quotation mark is found?

**Comment by andreasabel** [comment]
Please add the above test case to the test suite (test/LaTeXandHTML).
