### ISSUE TITLE
Commands in the emacs-mode get confused if we add question marks to the file

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#2306]
Originally reported in issue #2174.

Load (C-c C-l) a file containing the line B = ?, then add the line A = ? before (but do not reload the file). Then do C-c C-t in the goal for B: the two goals get exchanged.

**Comment by andreasabel** [comment]
``` agda
-- A = ? -- uncomment me after loading

B : Set
B = ?  -- do some interactive command after the uncommenting, like C-c C-t or C-c C-,
```

**Comment by nad** [comment]
My fix changes the code so that certain commands (for instance infer and normalise) no longer mess with the goals. Others, like give and refine, still do.
