### ISSUE TITLE
Rewrite rules are broken in combination with normal reduction

### ISSUE THREAD

**Issue by twanvl** [agda/agda#2328]
Consider this example:
```agda
    {-# OPTIONS --rewriting #-}
    module _ where

    open import Function
    open import Relation.Binary.PropositionalEquality
    {-# BUILTIN REWRITE _≡_ #-}

    postulate M : Set → Set
    postulate pure : ∀ {A} → A → M A
    postulate _>>=_ : ∀ {A B} → M A → (A → M B) → M B
    postulate bind-assoc : ∀ {A B C mx} {my : A → M B} {mz : B → M C} → (mx >>= my) >>= mz  ≡  mx >>= \x → my x >>= mz
    {-# REWRITE bind-assoc #-}

    _<*>_ : ∀ {A B} → M (A → B) → M A → M B
    mf <*> mx = mf >>= \f → mx >>= (pure ∘ f)

    shouldWork : ∀ {A B} (mx : M A) (my : M B)
      → (mx >>= (pure ∘ const)) <*> my
      ≡ (mx >>= (pure ∘ const)) >>= (\f → my >>= (pure ∘ f))
    shouldWork mx my = refl
```
In `shouldWork` I have just expanded the definition of `_<*>_`, so clearly the two sides are equal. But instead, at the `refl` we get the error `.B → .A != .A of type Set`. The RHS of _≡_ gets rewritten by the rewrite rule, but the LHS does not.

If you remove the `REWRITE bind-assoc` pragma, then the code typechecks (of course).

As far as I could figure out there is no way to prove `shouldWork` once the rewrite rule has been declared.

**Comment by gallais** [comment]
You can see where the error comes from by toggling the display of implicit arguments: the first `_>>=_`'s implicit arguments get resolved to 2 different things on each side of the equality sign. Adding type annotations using `Function`'s `_ ∋_` seems to fix the problem:
```agda
    doesWork : ∀ {A B} (mx : M A) (my : M B)
      → (M (B → A) ∋ mx >>= (pure ∘ const)) <*> my
      ≡ (M (B → A) ∋ mx >>= (pure ∘ const)) >>= (\f → my >>= (pure ∘ f))
    doesWork mx my = refl
```

**Comment by twanvl** [comment]
> You can see where the error comes from by toggling the display of implicit arguments: _>>=_'s implicit arguments get resolved to 2 different things on each side of the equality sign. 

If I write

    doesWork : ∀ {A B} (mx : M A) (my : M B)
      → (M _ ∋ mx >>= (pure ∘ const)) <*> my
      ≡ (M _ ∋ mx >>= (pure ∘ const)) >>= (\f → my >>= (pure ∘ f))
    doesWork mx my = refl

Then agda shows that the two underscores both get unified with `(B → A)`, so this is not the cause of the error. And if it was, then the type inference would be wrong, because `B → A` is the only valid value for this implicit argument. The reason that adding these type annotations 'solve' the problem is because with a type annotation, the rewrite rule no longer triggers for the RHS (which is arguably an instance of the same bug).

Here is another variant which gives the same error, but which works if the rewrite rule is disabled:

    alsoDoesn'tWork  : ∀ {A B} (mx : M A) (my : M B)
      → (M (B → A) ∋ mx >>= (pure ∘ const)) <*> my
      ≡ (M (B → A) ∋ mx >>= (pure ∘ \x _ → x)) >>= (\f → my >>= (pure ∘ f))
    alsoDoesn'tWork mx my = refl

Or:

    alsoDoesn'tWork2  : ∀ {A B} (mx : M A) (my : M B)
      → (M (B → A) ∋ mx >>= (pure ∘ const)) >>= (\f → my >>= (pure ∘ f))
      ≡ (M (B → A) ∋ mx >>= (pure ∘ \x _ → x)) >>= (\f → my >>= (pure ∘ f))
    alsoDoesn'tWork2 mx my = refl

**Comment by jespercockx** [comment]
Looking at the debug output suggests that there is a mismatch between the relevances of two function types `B → A`: the first time it is `Relevant`, the next time its `UnusedArg`. The matcher really has no business here comparing the relevances, but so far it has been relying on the build-in equality check on terms.

**Comment by jespercockx** [comment]
The low-cost option here is to simply ignore the relevance tags when comparing two `Dom`s (as we already do for `Arg`s). This doesn't seem to break anything in the test suite, but it still doesn't feel 100% safe to me. @andreasabel , do you think this would be ok? Otherwise the fix for this issue will have to wait until I (finally) implement the type-directed equality checker in the ReduceM.

**Comment by andreasabel** [comment]
I think in general, the relevance tags cannot be ignored, as the irrelevant function space`.A -> B` is not equal to the relevant one `A -> B`.  However, the inferred relevances `UnusedArg` and `Forced` are unreliable and should be ignored (keeping fingers crossed).
