### ISSUE TITLE
Size solver does not use type `Size< i` to gain the necessary information

### ISSUE THREAD

**Issue by nad** [agda/agda#2329]
The following code is accepted by Agda:
```agda
open import Agda.Builtin.Size

record R (A : Size → Set) (i : Size) : Set where
  field
    j : Size< i
    x : A j
    y : A i

postulate
  A : Size → Set
  f : ∀ {i} → A i → R A i

record Σ[Size<_] (i : Size) (A : Size → Set) : Set where
  constructor [_]
  field
    {size} : Size< i
    value  : A size

open Σ[Size<_]

ok : ∀ {i} → A i → Σ[Size< i ] A
size  (ok x) = R.j (f x)
value (ok x) = R.x (f x)
```
However, if the *unused* `y` field of `R` is commented out, then the code is rejected:
```
Failed to solve the following constraints:
  [35] ↑ R.j (f x) =< .i : Size
```
Is this intended?

The code is also rejected if the definition of `ok` is replaced by the following one:
```agda
not-ok : ∀ {i} → A i → Σ[Size< i ] A
not-ok x = [ R.x (f x) ]
```
Error message:
```
Failed to solve the following constraints:
  ↑ R.j (f x) =< .i : Size
```

**Comment by andreasabel** [comment]
The presence of the unused field, referencing size `i` in its type, must help the incomplete size solver somehow.  If you change its type to `y : A ω`, you get the same unsolved constraint.
Agda does not use the type of `R.j (f x)` to solve this constraint, the solver is incomplete in this case.

**Comment by andreasabel** [comment]
Here is a simplified version:
```agda
record R (i : Size) : Set where
  field
    j : Size< i

postulate
  f : ∀ i → R i

test : ∀ i → R i
R.j (test i) = R.j (f i)
```

**Comment by andreasabel** [comment]
Putting a meta for the rhs,
```agda
R.j (test i) = ?
```
fails with error
```
Cannot solve size constraints
[i] ↑ ?0 i ≤ i
Reason: inconsistent upper bound for 12
when checking that the expression ? has type Size< i
```
The better behavior would be to postpone the constraints.

But, to some extend it is pathological to expect a function to generate a size < i...
```agda
postulate
  pred : ∀ i → Size< i

works : ∀ i → Size< i
works i = pred i

test : ∀ i → Size< i
test i = {!!}
```
See #1428 why this is anyway inconsistent.

**Comment by nad** [comment]
You closed this ticket, but neither of the two examples that I reported are accepted. Was this what you intended?

**Comment by andreasabel** [comment]
Mmh, my Agda accepts your original example both with and without field `y`.
But I did not investigate the `not-ok`.

**Comment by andreasabel** [comment]
The postulate `f` makes Agda inconsistent. (See #1428). 
Do you have an example for this issue which does not rely on such a postulate?

**Comment by nad** [comment]
> Mmh, my Agda accepts your original example both with and without field `y`.

Sorry, I managed to test using the wrong version of Agda.

> Do you have an example for this issue which does not rely on such a postulate?

I don't remember.

**Comment by UlfNorell** [comment]
> Sorry, I managed to test using the wrong version of Agda.

Closing this as fixed then.
