### ISSUE TITLE
Release 2.5.2

### ISSUE THREAD

**Issue by asr** [agda/agda#2337]
It seems we are ready for realising 2.5.2 (and a new version of the standard library). I'll prepare the RC.

What about the support for GHC 8.0.2? After one week of announcing the RC, I'll make the release (if nothing blocks it). If GHC 8.0.2 is released on this time window, I'll include it. If not, we can make a point release later, if necessary.

**Comment by UlfNorell** [comment]
Thanks.

I'd be surprised if there were any 8.0.2 issues since 8.0.2-rc1 works without problems.

**Comment by nad** [comment]
In an attempt to help me @andreasabel introduced a new problem: #2331. If we're releasing now, then I guess that 7ade242857cad746837158c8e1143b4a84336d14 should not be included.

**Comment by nad** [comment]
If we're releasing 2.5.2, then I suggest that we remove the text
```
(the treatment of operators was changed in Agda 2.5.1, so code that
used to parse may have to be changed)
```
from error messages first. Do you agree?

**Comment by andreasabel** [comment]
Yes to both: don't release 7ade242 and remove that alert.

**Comment by nad** [comment]
I'll remove the alert.

**Comment by WolframKahl** [comment]
On Tue, Dec 13, 2016 at 01:23:28AM -0800, Nils Anders Danielsson wrote:
> If we're releasing 2.5.2, then I suggest that we remove the text
> ```
> (the treatment of operators was changed in Agda 2.5.1, so code that
> used to parse may have to be changed)
> ```
> from error messages first. Do you agree?

Perhaps not yet. Not all Agda users enjoy the luxury of being able to
follow all releases, or even of using Agda all the time without
interruptions of several months...

**Comment by asr** [comment]
> Perhaps not yet. Not all Agda users enjoy the luxury of being able to follow all releases, or even of using Agda all the time without interruptions of several months...

I agree. I'll not include the commit removing the alert.

**Comment by asr** [comment]
> don't release 7ade242

OK.

**Comment by asr** [comment]
I created the release-2.5.2 branch which will be the base for the release.

**Comment by asr** [comment]
I have tested the installation of  [2.5.2 RC 1](http://www1.eafit.edu.co/asr/tmp/Agda-2.5.1.2.20161216.tar.gz) on Ubuntu.

Could someone test the installation on Windows and Mac OS using the following instructions:

```
  $ tar xzf Agda-2.5.1.2.20161216.tar.gz
  $ cd Agda-2.5.1.2.20161216
  $ cabal install
```

**Comment by UlfNorell** [comment]
- [x] MacOS X 10.10, ghc-8.0.2-rc1
- [x] Windows 10, ghc-8.0.1

**Comment by asr** [comment]
While preparing the RC, I saw [this](https://github.com/agda/agda-stdlib/commit/e3893da0ebca8f80ca2919426529b544503d2010) commit on the standard library. In which Agda commit was the `NO_SMASHING` pragma removed? Why this changed wasn't documented on the release notes?

**Comment by UlfNorell** [comment]
The `NO_SMASHING` pragma was removed by ee35abc. I didn't see a need to mention it in the release notes since the introduction of the pragma was never mentioned and it never actually did anything.

**Comment by asr** [comment]
I'm preparing the release, so the release-2.5.2 branch is frozen.

**Comment by asr** [comment]
Done!

**Comment by andreasabel** [comment]
Thanks @asr Andres!
