### ISSUE TITLE
Case split generates invalid syntax in pattern lambda which contains instance argument

### ISSUE THREAD

**Issue by m0davis** [agda/agda#2347]
```
record ⊤ : Set where

data ⊥ : Set where

foo : ⦃ _ : ⊤ ⦄ → ⊥ → Set
foo = λ {x → {!x!}}
```
Case spltting (C-c C-c) in the above generates invalid syntax:
```
foo = λ { }
{-
Found an implicit lambda where an explicit lambda was expected
when checking that the expression λ {} has type ⊥ → Set
-}
```
Better, of course, would have been `foo = λ {()}`. NB this problem also arises when splitting a non-impossible case, such as if `⊥` were replaced by `data D : Set where c : D`.

**Comment by m0davis** [comment]
I notice that by invoking `agda2-display-implicit-arguments` or setting `{-# OPTIONS --show-implicit #-}`, Agda behaves properly.

**Comment by andreasabel** [comment]
@asr: cherry pick onto 2.5.2?

**Comment by asr** [comment]
> @asr: cherry pick onto 2.5.2?

Done in 34eb4c33fc234e301818f4abe31a0ad445581832 and 2bb8e46a0c5741b1b6fb4a06825f323ea208bbf9.
