### ISSUE TITLE
expose noConstraints to reflection framework

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#2351]
```agda
open import Agda.Builtin.Reflection
open import Agda.Builtin.Unit
open import Agda.Builtin.String
open import Agda.Builtin.List

id : ∀ {t : Set} → t → t
id x = x

program : ⊤ → ⊤
program = id


infixl 5 _>>=_
_>>=_ = bindTC
pure = returnTC

fumble : Term → TC Term
fumble t = catchTC (normalise t) (pure t)


defToTerm : Name → Definition → List (Arg Term) → Term
defToTerm _ (function cs) as = pat-lam cs as
defToTerm _ (data-cons d) as = con d as
defToTerm _ _ _ = unknown

derefImmediate : Term → TC Term
derefImmediate (def f args) = getDefinition f >>= λ f' → pure (defToTerm f f' args)
derefImmediate x = pure x

macro
  reflect : ∀ {ℓ} {t : Set ℓ} → t → Type → TC ⊤
  reflect {_} {t} x ty = quoteTC x >>= derefImmediate >>= λ x' → quoteTC t >>= checkType x' >>= fumble >>= quoteTC >>= unify ty

example : Term
example = reflect program
```

I tried to write `fumble`, which attempts to reduce a term, and if it can't, just uses the unreduced version, but it seems `catchTC` is unable to actually catch the constraint error thrown by `normalise`.

**Comment by andreasabel** [comment]
Unsolved constraints are not reported immediately via the error mechanism, this is why you cannot catch them.  In the Agda type checker, there is a function `noConstraints` that turns left-over constraints into an error.  The TC functions as defined in `Unquote.hs` do not use `noConstraints`.

As I am unsure about the design of the Reflection features, I will not mess with it, but @UlfNorell , would it make sense to either expose `noConstraints` or bake it into the TC functions?

**Comment by UlfNorell** [comment]
Exposing `noConstraint` is the reasonable thing to do. Keep backwards compatibility and I think there are certainly situations where you want to allow constraints.

**Comment by nad** [comment]
Perhaps it would also be useful to be able to figure out if some computation led to the introduction of new, unsolved constraints (see https://github.com/agda/agda/issues/3462#issuecomment-449359505).

**Comment by UlfNorell** [comment]
You can implement that with `noConstraints` (at a small cost):
```agda
constraints? : {A : Set} → TC A → TC (A × Bool)
constraints? m =
  ((_, false) <$> noConstraints m) <|>
  ((_, true)  <$> m)
```

**Comment by nad** [comment]
Aha, `noConstraints` only looks at the constraints created by a certain computation. That sounds more useful to me than something that looks at *all* left-over constraints.

**Comment by nad** [comment]
I tried to expose `noConstraints` by using the "copy similar code and tweak it until there are no type errors" methodology, but for some unfathomable reason my implementation does not seem to work. The key lines from `Agda.TypeChecking.Unquote`:
```haskell
    I.Def f [l, a, u] ->

             , (f `isDef` primAgdaTCMNoConstraints, tcNoConstraints (unElim u))

    tcNoConstraints :: Term -> UnquoteM Term
    tcNoConstraints m = liftU1 noConstraints (evalTCM m)
```
Can someone suggest a better implementation?

Here is my test case:
```agda
open import Agda.Builtin.List
open import Agda.Builtin.Reflection
open import Agda.Builtin.Unit

postulate
  P : {A : Set} → A → Set

create-constraint : TC Set
create-constraint =
  unquoteTC (def (quote P) (arg (arg-info visible relevant)
                                (lam visible (abs "_" unknown)) ∷ []))

macro

  should-fail : Term → TC ⊤
  should-fail _ =
    bindTC (noConstraints create-constraint) λ _ →
    returnTC tt

test : ⊤
test = should-fail
```
The problem is that I get an unsolved constraint instead of a type error.

**Comment by nad** [comment]
A clarification: I do get a type error, but a non-fatal one. I get the same type error if `noConstraints` is removed from the code.

Some testing suggests that the Haskell command `noConstraints` is executed, but that no new, unsolved constraints are detected. Is there something wrong with my test case?

**Comment by nad** [comment]
@jespercockx gave me some help. It turns out that `noConstraints` only works for ["blocking"](https://github.com/agda/agda/blob/4900ef5fc61776381f3a5e9c94ef776375e9e1f1/src/full/Agda/TypeChecking/Monad/Constraints.hs#L160-L174) constraints. Why is there a distinction between blocking and non-blocking constraints?
