### ISSUE TITLE
LaTeX backend: double space should only serve for alignment, not for extra space

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2353]
The LaTeX backend recognizes columns and aligns when they are separated by more than one space.  Thus, two spaces are needed at least to get alignment.  However, putting two spaces have at the same time the meaning of a larger separator.  This means I cannot get alignment without larger separation.

Enhancement request: two spaces should only separate as one space does, but serve as alignment indicater.  Three spaces should spearate as two spaces, etc.

**Comment by nad** [comment]
> Three spaces should spearate as two spaces, etc.

What does this mean? I suggest that we follow lhs2TeX with the `--poly` option, and stick to two categories: "one space" and "two spaces or more".

**Comment by andreasabel** [comment]
Indeed, what I said about "Three spaces..." does not make a lot of sense.

**Comment by nad** [comment]
Perhaps you can achieve what you ask for by adding the following line after the import of the `agda` package:
```
\defaultcolumn{@{}l@{ }}
```
I tried this, and noticed that in some cases I want larger spacing: when using equational reasoning I want extra space between the terms and the equality signs. When lhs2TeX is used one can insert an invisible token to increase the spacing, or use a `%format` directive, but those approaches are currently not available when `agda --latex` is used.

**Comment by nad** [comment]
Perhaps one can add extra spacing by adding a special case to `\AgdaFunction` (say).

**Comment by nad** [comment]
> Perhaps one can add extra spacing by adding a special case to `\AgdaFunction` (say).

Yes: 11039b4ac1ee6dcc494029b46eb31f13e3c0c2be.
