### ISSUE TITLE
UHC backend when using UHC 1.1.9.5 prints `1.0` as `1`

### ISSUE THREAD

**Issue by asr** [agda/agda#2359]
``` agda
open import Common.Prelude

main : IO Unit
main = putStrLn (primShowFloat 1.0)
```

GHC (8.0.1) backend:    `1.0`
UHC (1.1.9.4) backend: `1.0`
UHC (1.1.9.5) backend: `1`

Note that UHC 1.1.9.5 was required when fixing #1857.

Blocked by https://github.com/UU-ComputerScience/uhc/issues/89.

**Comment by UlfNorell** [comment]
Moved to agda-uhc.
