### ISSUE TITLE
Allow support for pattern matching function binders

### ISSUE THREAD

**Issue by ahmadsalim** [agda/agda#2361]
Currently, defining functions which depend on a specific sub-component of a record element requires a bit of work.

Either you have to use the record projections explicitly each time you need a subcomponent, like so:

```agda
(a,b : Σ[ a ∈ A ] B) → P (proj₁ a,b)
```

Or you need to have a pattern matching let in the function signature, like so:

```agda
(a,b : Σ[ a ∈ A ] B) → let (a , b) = a,b in  P a
```

It would be nice if it was possible to have an in-line way of pattern matching for records in function binders, like so:
```agda
((a , b) : Σ[ a ∈ A ] B) → P a
```

Note: It seems that the following already parses but has a different semantics (where it declares three elements of the same product type):
```agda
(a , b : Σ[ a ∈ A ] B) → P a
```

**Comment by andreasabel** [comment]
Coq 8.6 has this feature now, so it would be good if we followed suit.
The question is whether we should make the parentheses around each non-refutable pattern mandatory, but I think, this would be safest (and fully backwards compatible).  Consider
```agda
record R (A : Set) : Set where
  constructor c
  field f : A

postulate
  p : ((c x) : R) → _
  q : (c x : R) → _
  r : (c : R) → _
```
`p` is the new feature.  `q` now means to bind two variables `c` and `x` of type `R`, but I think we should throw an error now that the binding of `c` shadows a record constructor.  `r` would then fail as well. (See #297.)

**Comment by m0davis** [comment]
@andreasabel, why do you say it would be "fully backwards compatible" when `q` and `r` would now fail? (Also, unimportantly, note that the example you gave would have a type error in each of the postulates, since `R` is `Set → Set`. ...but I know what you meant.)

**Comment by m0davis** [comment]
How about we abuse the `let` keyword? Following the [example above](https://github.com/agda/agda/issues/2361#issuecomment-269464717),
```
postulate
  p : (let c x : R) → _
  p₂ : (let c x let c y : R) → _
  p₃ : ((let c x) (let c y) z : R) → _
  q : (c x : R) → _
  r : (c : R) → _
  r₂ : (c let c x : R) → _
```
`p` is the new feature. `p₂` is the same but binds `x` and `y`. `p₃` is like `p₂` but also binds `z` in way we all have come to love. `q` and `r` work as they do now (fully backwards compatible!). In `r₂`, `c` would be shadowed, and so would fail.

**Comment by m0davis** [comment]
This issue might overlap some with #2298. Just saying.

**Comment by andreasabel** [comment]
Ok, not fully backwards compatible, but compatible when we include the change contemplated in #297. 
Mmh, the `let` does not look good here (defies aesthetics, in my eyes).

**Comment by UlfNorell** [comment]
Duplicate of #1097.

**Comment by ahmadsalim** [comment]
@UlfNorell As far as I understand, my issue is different than #1097, since mine concern function types, not lambdas. But maybe you want to handle them both in some parser extension.

**Comment by UlfNorell** [comment]
Variables bound in function types are considered *lambda bound* even though there isn't an actual lambda involved.
