### ISSUE TITLE
Matching against negative literal

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2365]
```agda
open import Agda.Builtin.Nat

lit : Nat → Set
lit -20 = Nat
lit _ = Nat
```
reports
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Patterns/Abstract.hs:37
```

**Comment by andreasabel** [comment]
Fixed the crash (pushing soon).  Ideally, we would be able to type check this:
```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Int
open import Agda.Builtin.Equality

fromNeg : Nat → Int
fromNeg zero    = pos 0
fromNeg (suc x) = negsuc x

{-# BUILTIN FROMNEG fromNeg #-}

-- A negative number

neg : Int
neg = -20

-- Matching against negative numbers

lit : Int → Nat
lit -20 = 0  -- Error thrown here
lit _   = 1

-- Testing reduction rules

test0 : lit -20 ≡ 0
test0 = refl

test1 : lit -2 ≡ 1
test1 = refl
```
but we get a
```
Type mismatch when checking that the pattern -20 has type Int
```

**Comment by andreasabel** [comment]
The original test case now passes the type checker, which is not intended, I guess. `-20` just is not a natural number.

However, the infrastructure for negative literals seems underdeveloped as of now.
```haskell
litType :: Literal -> TCM Type
litType l = case l of
  LitNat _ n    -> do
    _ <- primZero
    when (n > 0) $ void $ primSuc
    el <$> primNat
```
Negative literals pass as `Nat`.  @UlfNorell: What _is_ the intended type of a negative literal?

**Comment by UlfNorell** [comment]
> @UlfNorell: What is the intended type of a negative literal?

In right-hand sides `-20` desugars to `FROMNEG 20`. There's no support for negative literals in left-hand sides at the moment. I suggest to fix this issue by giving the proper error message (negative literals not supported in patterns, or some such), and opening a new feature request for negative literal patterns.

**Comment by andreasabel** [comment]
Ok, I close this then, and leave it to someone who is interested in negative pattern literals to open a feature request.
