### ISSUE TITLE
Shadowed module parameter crashes interaction

### ISSUE THREAD

**Issue by subttle** [agda/agda#2371]
Good day,

I have narrowed this error down to being reproducible for me with a 2-line file, test.agda.
```
module test  (Σ : Set) where
open import Data.Product
```
Then asking for the normal form of, for example, `true`, I get the following error:

> An internal error has occurred. Please report this as a bug.
> 
> Location of the error: src/full/Agda/Utils/List.hs:344

I'm using OS X 10.11.6, Agda 2.5.1.1, and agda-stdlib 0.12. As a work around, I've just renamed the Σ in my project.

For quick reference, here is the code being imported.

https://github.com/agda/agda-stdlib/blob/master/src/Data/Product.agda

**Comment by andreasabel** [comment]
I can confirm this for the current development version.
```agda
module Issue2371 (Nat : Set) where

open import Agda.Builtin.Nat

-- C-c C-n true RET
-- An internal error has occurred. Please report this as a bug.
-- Location of the error: src/full/Agda/Utils/List.hs:304
```

**Comment by andreasabel** [comment]
There was some buggy code dealing with a shadowed module parameters when preparing the context for the execution of top-level interaction commands. I fixed it.

In general, it is not good to shadow a module parameter by an import. Both the parameter and the imported symbol will be considered ambiguous.

@subttle: I suggest to place the import outside of the module (or to use the `hiding` directive to avoid shadowing)
```
open import Data.Product
module M (Σ : Set) where
test = Σ
```
