### ISSUE TITLE
problems when instances are declared with inferred types

### ISSUE THREAD

**Issue by m0davis** [agda/agda#2372]
Agda properly complains that `Terms marked as eligible for instance search should end with a name`, but the error message can come come too late, confusing the user. This happens when the invalid instance declaration's type is inferred.
```agda
postulate D : Set

instance i = D 
  -- If the type of `i` were given explicitly, Agda would display the error here

record R : Set₁ where
  field
    r : Set

open R {{ ... }} public

f : r → Set₁ -- Here, confusingly, is where Agda registers its complaint
f = {!!}
```

**Comment by m0davis** [comment]
Probably related: Agda doesn't find the instance when it's declared in a separate file.

M1.agda
```agda
postulate D : Set

record R : Set₁ where
  field
    r : Set

open R {{ ... }} public

instance iR = record { r = D }
```
M2.agda
```agda
open import M1

f : r → Set₁ -- No instance of type R was found in scope.
f = {!!}
```

**Comment by andreasabel** [comment]
I fixed this by keeping track in aliases like `i` and `iR` that they are instances.  Before, this information was only in the type signature `FunSig` not in the definition `FunDef`.  Handling of aliases was thus broken.
