### ISSUE TITLE
Parse {{...}} in module applications

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2373]
```agda
postulate
  A : Set

module M (A : Set) where

  record R : Set₂ where
    field
      F : Set₁

-- Accepted:
module RA = M.R {A = A}
open RA {{...}}

-- Rejected:
open M.R {A = A} {{...}}
```
The last statement gives a parse error, but it would make sense to parse this.

**Comment by UlfNorell** [comment]
I'm not convinced this makes sense. Currently

```agda
module M' = M {{...}}
```
is roughly equivalent to
```agda
module M' {Γ} {{r : R Γ}} = M {Γ} r
```
It's not at all obvious how this would generalise to allow arbitrary arguments mixed in with the `{{...}}`.
