### ISSUE TITLE
Case spliting and parametrised modules

### ISSUE THREAD

**Issue by asr** [agda/agda#2378]
```agda
postulate B : Set

module Test where

  module Foo (A : Set) where

    data Bool : Set where
      false true : Bool

  module Bar where

    open Foo B

    bar : Bool → Bool
    bar b = {!!}
```

When case splitting (C-c C-c) on `b` Agda generates

```agda
  bar : Bool → Bool
  bar Foo.false = {!!}
  bar Foo.true = {!!}
```

Note that the `Bool` data constructors are qualified with the module `Foo`.

Now, If I remove the parameter `(n : Nat)` from the module `Foo`, case split on `b` generates

```agda
  bar : Bool → Bool
  bar false = {!!}
  bar true = {!!}
```

That is, the `Bool` data constructors aren't qualified.

Is this behaviour (qualified the data constructors) of case splitting on parametrised modules expected?

CC'ing @jonaprieto.

**Comment by andreasabel** [comment]
No, this is not intended, it is known as issues #1932 and #2245.

Display forms are so far only used for terms, not for patterns.  I started working on making terms remember more information that only patterns remember now (see e.g. #2326).  The goal is, in `Syntax.Translation.InternalToAbstract`, to convert patterns to terms, use the display form machinery there, and convert back to patterns.

**Comment by asr** [comment]
Duplicate of #1932.
