### ISSUE TITLE
C-u C-u C-c C-n broken; “Not in scope: show at 1,1-5 when scope checking show”

### ISSUE THREAD

**Issue by mietek** [agda/agda#2382]
In Agda 2.5.2, attempting to normalise any term results in an error.

```
Not in scope:
  show at 1,1-5
when scope checking show
```

### Example

```
module NormalBug where
postulate A : Set
```

| Command | Input | Output |
| -- | -- | -- |
| `C-c C-n` | `A` | `A` |
| `C-u C-c C-n` | `A` | `A` |
| `C-u C-u C-c C-n` | `A` | error |

**Comment by mietek** [comment]
Sorry, this is my mistake.  The documentation for [Emacs mode](http://agda.readthedocs.io/en/latest/tools/emacs-mode.html#global-commands) lists `C-c C-n` as the normalise command, while `C-u C-u C-c C-n` is a newly-introduced command that expects `show` to be in scope.

The reason for my confusion is simple: I’ve trained myself to use the `C-u C-u` prefix whenever I wish to see a normalised term, because using the prefix is necessary with the `C-c C-,` command.

**Comment by UlfNorell** [comment]
Mislabeled the above commit.

**Comment by andreasabel** [comment]
I think the error message could be nicer instead of just a scope error on `show`.
