### ISSUE TITLE
More fine-grained blocking in constraint solver

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2384]
Martin Escardo reports that the hole was automatically solved in 2.5.1.1, but no longer in 2.5.2:
```agda
open import Agda.Builtin.Nat renaming (Nat to ℕ)
open import Agda.Builtin.Equality

postulate
  funext : {X : Set} {Y : X → Set} {f g : (x : X) → Y x} → (∀ x → f x ≡ g x) → f ≡ g

_∶∶_ : {X : ℕ → Set} → X 0 → ((n : ℕ) → X (suc n)) → ((n : ℕ) → X n)
(x ∶∶ α) 0 = x
(x ∶∶ α) (suc n) = α n

hd : {X : ℕ → Set} → ((n : ℕ) → X n) → X 0
hd α = α 0

tl : {X : ℕ → Set} → ((n : ℕ) → X n) → ((n : ℕ) → X (suc n))
tl α n = α(suc n)

-- Needed to add the implicit arguments for funext in Agda 2.5.2:

hd-tl-eta : (X : ℕ → Set) {α : (n : ℕ) → X n} → (hd α ∶∶ tl α) ≡ α
hd-tl-eta X = funext {Y = {!X!}} lemma
 where
  lemma : ∀ {α} → ∀ i → (hd α ∶∶ tl α) i ≡ α i
  lemma 0 = refl
  lemma (suc i) = refl
```

**Comment by nad** [comment]
Bisection suggests that this regression was introduced by @fredrikNordvallForsberg and @gallais in "Add warnings machinery" (56c804c51a22de785c6465a66564f4b363e99118). However, I think this is a false positive. I looked at this commit, and didn't see anything that could trigger the problem reported above. This version of Agda does reject the code above:
```
Unsolved interaction metas at the following locations:
  [...]/Bug.agda:20,27-32
```
However, when I load `Bug.agda` in Emacs I see that the meta-variable is solved.

**Comment by nad** [comment]
Another attempt:
```
$ cat script
#!/bin/sh

AGDA=$1

$AGDA --interaction --ignore-interfaces <<EOF
IOTCM "Bug.agda" None Indirect (Cmd_load "Bug.agda" [])
IOTCM "Bug.agda" None Indirect (Cmd_constraints)
EOF
$ agda-bisect --log log --bad v2.5.2 --good 56c804c --script ./script --must-output '"?0 := λ z → X z\n"'
[...]
fb2a8fe10e3e688ac1deabd075269bf6276ae875 is the first bad commit
commit fb2a8fe10e3e688ac1deabd075269bf6276ae875
Author: Ulf Norell <ulf.norell@gmail.com>
Date:   Mon Nov 14 11:46:42 2016 +0100

    [ fixed #2296 ] don't lose constraint dependencies when failing to solve a constraint

    When readding a constraint after an unsuccessful attempt we threw away all but
    the top problem id associated with the constraint. This meant that constraints blocked
    on one of the discarded problem ids would unblock prematurely.
[...]
```
Perhaps this meta-variable *shouldn't* have been solved. @UlfNorell, do you want to take a look?

**Comment by UlfNorell** [comment]
The proper blocking of constraints is indeed what makes the difference in this case. In `2.5.2` we get

```
  [88, 90] _X_64 X x x = X x : Set
  [88] _65 := λ X {α} → (x : ℕ) → _X_64 X x x [blocked on problem 90]
```

In `2.5.1` the dependency on problem 90 is lost and `_65` is solved, which happens to solve the Gordian constraint bundle in this case.

However, in this particular case we're blocking too much. `_65` arises from a failure to solve

```
(x : ℕ) → _X_54 X {α} x x = (n : ℕ) → X n : Set
```
Since the domains are equal there is no reason to block the entire function type. This would allow progress for this example.

**Comment by andreasabel** [comment]
I would like to see more test cases that use the new `antiUnify` tactic in the conversion checker.
The test cases should address these questions:

- [ ] Do we need to eta-expand during anti-unification (like in the conversion checker)? If not, why not?
- [ ] The current code (2017-07-26) seems to assume constructors are fully applied (precondition of `getConType`), but without eta, this is not guaranteed.  (I will change this to a safe use of `getConType`).

Can we have tests please that cover all cases of antiUnify?

**Comment by UlfNorell** [comment]
> Do we need to eta-expand during anti-unification (like in the conversion checker)? If not, why not?

We don't *need* to do anything, failure of anti-unification results in the worst case in unsolved metas. Is it possible to construct a test case where eta-expansion in `antiUnify` would make a difference? Maybe.

> Can we have tests please that cover all cases of antiUnify?

No. It's really hard constructing *any* test cases where anti-unification makes a difference. You need quite subtle interactions between constraints and engineering examples exhibiting these is a bit of a black art.
