### ISSUE TITLE
Relax requirements of BUILTIN EQUALITY

### ISSUE THREAD

**Issue by m0davis** [agda/agda#2386]
The current requirement of a BUILTIN EQUALITY is for a universe-polymorphic one in the same universe as the equated type:
```agda
data ≡-any-in-same {ℓ} {A : Set ℓ} (x : A) : A → Set ℓ where 
  refl : ≡-any-in-same x x
```
@andreasabel suggests [here](https://lists.chalmers.se/pipermail/agda/2017/009186.html) that the requirement should be relaxed to allow for universe-polymorphic in Set₀ or for Set₀ in Set₀:
```agda
data ≡-any-in-0 {ℓ} {A : Set ℓ} (x : A) : A → Set₀ where 
  refl : ≡-any-in-0 x x

data ≡-0-in-0 {A : Set₀} (x : A) : A → Set₀ where 
  refl : ≡-0-in-0 x x
```
It occurs to me that some or all of the following variants might also be allowable:
```agda
--Setₙ in Setₘ
data ≡-4-in-2 {A : Set₄} (x : A) : A → Set₂ where 
  refl : ≡-4-in-2 x x

data ≡-2-in-4 {A : Set₂} (x : A) : A → Set₄ where 
  refl : ≡-2-in-4 x x

--universe-polymorphic in universe-polymorphic
data ≡-any-in-any {ℓ} {A : Set ℓ} (x : A) {ℓ′} : A → Set ℓ′ where 
  refl : ≡-any-in-any x x
data ≡-any-in-any' {ℓ′} {ℓ} {A : Set ℓ} (x : A) : A → Set ℓ′ where 
  refl : ≡-any-in-any' x x

--using two indices instead of one
data ≡-indexed {ℓ} {A : Set ℓ} : A → A → Set ℓ where 
  refl : ∀ {x} → ≡-indexed x x

--using postulated levels
open import Agda.Primitive
postulate
  ℓ : Level
  ℓ′ : Level

data ≡-using-postulated-levels {A : Set ℓ} (x : A) : A → Set ℓ′ where 
  refl : ≡-using-postulated-levels x x
```

**Comment by andreasabel** [comment]
I think we only need equality `Eq` to be a relation, i.e., of type `{xs:As} (x y : B) -> Set l` for some `As`,`B`,`l`, and `refl` to be the diagonal, i.e., `{xs:Cs} -> Eq xi xi`.

**Comment by nad** [comment]
Is this sufficient for `primTrustMe`? What if `refl` is a definition that computes to something else?

**Comment by andreasabel** [comment]
The type of `primTrustMe` should be `{xs:As} {x y : B} -> Eq {xs} x y`.  `refl` is a constructor of `Eq` with full type `{xs:As}{x:B} -> Eq {xs} x x`. This should work.

**Comment by andreasabel** [comment]
I am implementing a relaxation that will allow all of the suggested forms of equality above except `≡-any-in-any` which separates the two main arguments (by a level).  That particular one, with a hidden level `l'` for the universe of the equality type would be a pain to use anyway, as this level can usually not be inferred.

**Comment by andreasabel** [comment]
@m0davis: I pushed my fix, please evaluate whether it fits your needs.

**Comment by m0davis** [comment]
@andreasabel, I'm sure it's fine for my purposes. I'm not well-versed in type theory and my [original, newbie question](https://lists.chalmers.se/pipermail/agda/2017/009180.html) was just out of curiosity.

**Comment by andreasabel** [comment]
I see.  Maybe there was no pressing need then.  Anyway, I wanted the non-universe polymorphic one for my own pleasure.
