### ISSUE TITLE
LaTeX-backend is not tested on some test cases of the latex-html test suite

### ISSUE THREAD

**Issue by asr** [agda/agda#2392]
See https://github.com/agda/agda/issues/1675#issuecomment-271475660 and https://github.com/agda/agda/issues/1675#issuecomment-271955029.

**Comment by asr** [comment]
The latex compilers in Travis were disable in #1675, so I'll continue the discussion there.

**Comment by asr** [comment]
@vlopezj, why you added `*.lagda.md` and `*.lagda.rts` test cases to the latex-html test suite?

**Comment by vlopezj** [comment]
@asr I want to check whether each part of the file is parsed as code or comments, and checking the HTML rendering of the syntax highlighting is a quite straightforward way to achieve this.

If there's a test suite that just checks parser output I could move those cases there (?)



"Andrés Sicard-Ramírez" <notifications@github.com> skrev: (12 januari 2017 17:19:51 CET)

**Comment by asr** [comment]
> @asr I want to check whether each part of the file is parsed as code or comments, and checking the HTML rendering of the syntax highlighting is a quite straightforward way to achieve this.

I see. Thanks!

**Comment by asr** [comment]
I'm thinking that merge of the LaTeX and HTML test suites was not a good idea. I know they share some code, but now with the different literates formats supported (`*.lagda`, `*.lagda.md`, `*.lagda.rts`, `*.lagda.tex`), the three supported LaTeX compilers (pdflatex, xelatex and lualatex) and the latex-html test suite requiring *.tex and *.html golden files for every test case, we are adding unnecessary golden files and creating unnecessary tests.

**Comment by asr** [comment]
I will split the latex-html test suite.

**Comment by asr** [comment]
I was worried about of requiring `.compile` files for *every* LaTeX-backend test case, but I figured out  how to use these files only for removing some LaTeX compilers. So I won't split the test.
