### ISSUE TITLE
Master branch was merged into the stable branch

### ISSUE THREAD

**Issue by asr** [agda/agda#2394]
@vlopezj, the PR #2393 was based on the master branch and you merged it.

I see the commit in that  PR in the stable-2.5 branch too. How did you "move" the commit from the master branch to the stable-2.5 one? I'm asking because the commit has the *same* hash (5703d8bc86849669c4cc2df0889c7eb0f37ffdf4) in both branches. This should not happen if the commit was cherry-picked from the mater branch into the stable-2.5 branch.

**Comment by asr** [comment]
NO merge stable-2.5 in your local repository.

**Comment by vlopez** [comment]
I think you mean @vlopezj

**Comment by asr** [comment]
I don't know what happened. Even I don't know if I am the the culprit. Anyway, I see two options to fix the problem:

We erase stable-2.5 and

1. Someone with a good stable-2.5 push it in GitHub or

2. Since the current difference between master and stable-2.5 is small, we create the new stable-2.5 from master.

In any case, after the fix, everyone should remove your local copy of stable-2.5 and pull a new one copy from GitHub.

**Comment by asr** [comment]
> I think you mean @vlopezj

Oops, sorry. You are right.

**Comment by nad** [comment]
> In any case, after the fix, everyone should remove your local copy of stable-2.5 and pull a new one copy from GitHub.

Please don't force everyone to do this. Can't you just add some kind of rollback commit?

**Comment by vlopezj** [comment]
@asr It was almost certainly my fault. See [log_2017_01_10.txt](https://github.com/agda/agda/files/698534/log_2017_01_10.txt). 
The difference was small and it was a fast-forward commit, so I assumed everything was all right (it wasn't).

Here's what stable-2.5 looked like before I messed up:
https://github.com/agda/agda/tree/good-2017-01-10-stable-2.5

**Comment by asr** [comment]
> Can't you just add some kind of rollback commit?

Yes. Starting...

**Comment by andreasabel** [comment]
This seems relevant: http://stackoverflow.com/questions/7099833/how-to-revert-a-merge-commit-thats-already-pushed-to-remote-branch

**Comment by andreasabel** [comment]
@vlopezj: Latest here you alarms should have gone off:
> Din gren ligger före "origin/stable-2.5" med 743 incheckningar.
>   (använd "git push" för att publicera dina lokala incheckningar)

**Comment by asr** [comment]
After pulling the current stable-2.5, you can continue with your usual work-flow.
