### ISSUE TITLE
On Windows, Agda2 Program Args gives error with -i, is fine with --includepath

### ISSUE THREAD

**Issue by astump** [agda/agda#2397]
On Windows, it seems that setting Agda2 Program Args from the emacs customize-group section for Agda2 does not work correctly with -i.  The Agda backend does not interpret the path correctly.  It seems to view an absolute path as a local path.  Surprisingly, using --includepath with the exact same absolute path works fine.

**Comment by nad** [comment]
Have you entered `-i...` as one string, or two? I use one string (`-i.`), and this works fine on my Linux setup.

**Comment by astump** [comment]
I just enter

-i PATH

in one text entry box in the emacs customization for Agda2 Program Args 
on Windows, and this leads to the problem.  Writing

--includepath=PATH

instead works fine, for the same value of PATH.

It is not a problem for me, since I found a way to solve it with 
--includepath.  I'm just bringing it to your attention since it was 
weird and hard to debug until I tried --includepath.

Aaron

**Comment by nad** [comment]
Do you mean `--include-path`, with an extra dash?

**Comment by astump** [comment]
Must have been.

**Comment by nad** [comment]
Does it work if you write `-iPATH` without a space in between? If you write `-i PATH`, then I think that the path that is used starts with a space character.

**Comment by astump** [comment]
That could be it.  I did not try this, but it would make sense.
Aaron

**Comment by nad** [comment]
OK, then I'm closing this issue now.
