### ISSUE TITLE
removeLink: permission denied

### ISSUE THREAD

**Issue by rgrinberg** [agda/agda#2398]
Agda 2.5.2 (installed with pacman) is giving me the following error when loading any file in Emacs:

```
/usr/share/agda/lib/prim/Function.agda:9,13-18
/usr/share/agda/lib/prim/Level.agdai: removeLink: permission denied
(Permission denied)
```

**Comment by nad** [comment]
Let me guess:
* You installed the standard library when using an older version of Agda.
* The standard library is installed in a location which is not writable by the user running the Agda program.
* Now you have upgraded to a newer version of Agda (but you did not upgrade the standard library, or at least you did not rebuild its interface files).
* As the interface file format has changed Agda tries to remove the old `.agdai` files, and fails.

**Comment by rgrinberg** [comment]
That seems very likely. Seems like the agda and agda-stdlib version in Archlinux aren't compatible:

```
community/agda 2.5.2-1
    A dependently typed functional programming language and proof assistant
community/agda-stdlib 0.12-1
    Agda standard libraries
```

**Comment by asr** [comment]
> Seems like the agda and agda-stdlib version in Archlinux aren't compatible:

Yes. With Agda 2.5.2 you need standard library 0.13.

Cannot you install a local version of the standard library using these [instructions](http://agda.readthedocs.io/en/latest/tools/package-system.html)?

**Comment by rgrinberg** [comment]
It works quite well now, thanks.
