### ISSUE TITLE
LaTeX backend error on LaTeX comments

### ISSUE THREAD

**Issue by asr** [agda/agda#2400]
```latex
\documentclass{article}

\usepackage{agda}

\begin{document}

% \begin{code}
% postulate A : Set
% \end{code}

\end{document}
```

```
$ agda --latex Bug.lagda
$ cd latex
$ pdflatex Bug.tex
! Missing $ inserted.
<inserted text> 
                $
l.8 \>
      \AgdaComment{\<\\
```

In relation to this error, @vlopezj [wrote](https://github.com/agda/agda/issues/2355#issuecomment-272246219):

> After some digging I see that the problem you report is not with the literate parser, but with the LaTeX back-end. In this case it starts a new code-block from commented-out `\begin{code}`, which is wrong.

> However, I think the real problem is having two different implementations for finding `\begin{code}` and `\end{code}` macros: one in `Agda.Syntax.Parser.Literate.literateTeX` and one in `Agda.Interaction.Highlighting.LaTeX.nextToken'`. I believe the LaTeX back-end should reuse the literate parser implementation.

**Comment by nad** [comment]
Here is a similar example:
```latex
\begin{code} text \end{code}
```
The parser does not treat this as a code block, but the LaTeX backend does.

**Comment by nad** [comment]
@vlopezj, can this issue be closed now (once test cases have been added)?
