### ISSUE TITLE
LaTeX backend error

### ISSUE THREAD

**Issue by asr** [agda/agda#2401]
While working on #2392 I found the following problem:

```agda
\documentclass{article}

\usepackage{agda}

\begin{document}

av
\begin{code}
  module Bug where

    data Bool : Set where
      true  : Bool
      false : Bool
      dunno : Bool
      aa    : {- \end{code} -} Bool

\end{code}
bleh

\end{document}
```

```
$ agda --latex Bug.lagda
$ cd latex
$ pdflatex Bug.tex
! Too many }'s.
l.30 \end{code} -}
                   Bool
```

**Comment by nad** [comment]
This issue was not fixed by "[ latex ] Make latex frontend and backend consistent" (1d20dbb331d515f5c8af614f16a3c47bed36c802).

**Comment by nad** [comment]
The example in the OP is now handled correctly. I wonder if the underlying problem has been fixed properly.

**Comment by nad** [comment]
> This issue was not fixed by "[ latex ] Make latex frontend and backend consistent" (1d20dbb331d515f5c8af614f16a3c47bed36c802).

Bisection suggests that the statement above is incorrect.
