### ISSUE TITLE
Termination checker should reduce arguments in structural order check

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2403]
Coq accepts this:
```coq
Variable P : nat -> Type.
Variable f  : forall n, P n -> P (pred n).

Fixpoint test (n : nat) : P n -> Type :=
  match n with
  | O   => fun p => nat
  | S m => fun p => test _ (f _ p)
  end.
```
Agda does not:
```agda
open import Common.Nat

postulate
  P : Nat → Set
  f : ∀{n} → P n → P (pred n)

test : ∀ n → P n → Set
test zero    p = Nat
test (suc n) p = test _ (f p)

-- The meta-variable is solved to (pred (suc n))
-- Termination checking fails.
-- If the termination checker evaluated the argument, it would pass.
```

**Comment by asr** [comment]
Which option(s) did you use for getting that error message?

**Comment by gallais** [comment]
Coq is famously not SN because it normalises a `Fixpoint`'s body before guard-checking it. As showcased by this example:

````Coq
Fixpoint F (n : nat) := let x := F n in O.
````

Does this patch make Agda not SN anymore?

**Comment by andreasabel** [comment]
No, this patch does not change the situation of SN.  Agda already accepts
```agda
f : Nat
f = let x = f in 0
```
The internal representation of the body of `f` is `[f/x]0` which is simply `0`.  Internal syntax does not keep beta-redexes and lets.

**Comment by andreasabel** [comment]
Since with-inlining destroys well-typedness, we should not do this in combination with with-inlining.  Could be causing #2458.  At least if we switch off normalization if we inlined with-functions, #2458 no longer loops.

**Comment by andreasabel** [comment]
It turns out that normalization of call arguments is too expensive in general.  See #2495.  I cut this down to only unfold non-recursive functions during normalization.

**Comment by nad** [comment]
I have some code that takes several minutes longer to type check when this feature is active. Without the feature:
```
Termination                      984ms   (2,748ms)
Termination.Graph                856ms
Termination.Compare              832ms
Termination.RecCheck              40ms
Termination.Reduce                36ms
```
With the feature:
```
Termination                    1,060ms (171,620ms)
Termination.Reduce           168,744ms
Termination.Compare              916ms
Termination.Graph                868ms
Termination.RecCheck              32ms
```
Please revert it.
