### ISSUE TITLE
agda-bisect: sed on OS X does not accept option `-r`

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2406]
agda-bisect: sed on OS X does not accept option `-r`

**Comment by nad** [comment]
I suggest that the call to sed is replaced by some Haskell code, in which case the following part of the `--help` text should be edited:
```
You should install suitable versions of the following commands before running
the script (in addition to any programs invoked by cabal install):
  cabal git sed
```

**Comment by UlfNorell** [comment]
You can also install GNU `sed` with `brew install gnu-sed`.
