### ISSUE TITLE
DLub sorts are not serialized

### ISSUE THREAD

**Issue by gallais** [agda/agda#2408]
I have a pretty gnarly module in which I compute quite a lot of `Level`s, then `Set`s of the corresponding `Level`s and ultimately values inhabiting them. It triggers an internal error on current stable (but also 2.5.1.1 and 2.5.2 AFAICT).

I've tried to reduce the example but it's still pretty big (there's a lot of boiler plate at the beginning). See the attached file: [InternalError.agda.txt](https://github.com/agda/agda/files/706026/InternalError.agda.txt)

**Comment by andreasabel** [comment]
The serializer seems to assume that there are no `DLub` sorts left (dependent least upper bound) and crashes when encountering one.  I do not know why such an assumption is justified. @UlfNorell?

**Comment by UlfNorell** [comment]
`DLub`s can (should) only appear if you have unsolved metas. Since we don't allow unsolved metas in interfaces the serialiser assumes there are no `DLub`s.

**Comment by andreasabel** [comment]
I challenge this theory.
```agda
dLub s1 b@(Abs _ s2) = case occurrence 0 s2 of
  Flexible _    -> DLub s1 b
  Irrelevantly  -> DLub s1 b
  NoOccurrence  -> sLub s1 (noabsApp __IMPOSSIBLE__ b)
--  Free.Unused   -> sLub s1 (absApp b __IMPOSSIBLE__) -- triggers Issue784
  Free.Unused   -> DLub s1 b
  StronglyRigid -> Inf
  Unguarded     -> Inf
  WeaklyRigid   -> Inf
```
There are other reasons for `DLub`s to remain.

**Comment by UlfNorell** [comment]
Obviously. But that was the case in the beginning. `Flexible` only happens if you have metas and `Irrelevantly` and `Free.Unused` are newer inventiontions.

**Comment by UlfNorell** [comment]
Would it not make sense to change the `Irrelevantly` and `Free.Unused` cases to `sLub s1 (noabsApp (mkType 0) b)`? In both cases the actual level should not matter.

**Comment by andreasabel** [comment]
I guess you meant `sLub s1 (absApp b (mkType 0)`?
We can try, but I would not bet any money on it.
Most likely, the current test case chokes because of an `Unused` level.  It would be worthwhile shrinking it to the point we can see what is going on.

**Comment by andreasabel** [comment]
Here is a MWE:
```agda
open import Agda.Primitive

postulate
  A : Set
  insertLevel : .(a : A) → Level
  FinsertT    : .(a : A) → Set (insertLevel a)
```
@gallais: you have not tried hard enough! :)

**Comment by andreasabel** [comment]
> I guess you meant `sLub s1 (absApp b (mkType 0)`?
After shrinking, it is clear this does not work either, it is ill-typed.  We cannot pull an element of `A` out of the hat.

If we do not want to serialize `DLub`s then we can only assign sort `Inf` to `FInsertT`.  But why not simply serialize `DLub`s, what is so bad about it?!

**Comment by UlfNorell** [comment]
No that's the easy solution to this problem. Having `DLub`s around will make things hard on the level constraint solver, but I guess there's nothing to be done about that.

**Comment by andreasabel** [comment]
Well, we can still abuse `Sort Prop` for a value that is `inert` and only equal to itself, and inhabits any type, but only when in irrelevant context.
```haskell
  sLub s1 (absApp b (sort Prop))
```
Or better, use `__IMPOSSIBLE_TERM__`.

**Comment by andreasabel** [comment]
Here is a similar case for unused argument in a level function:
```agda
data ⊥ : Set where

data Unit : Set where
  unit : Unit

-- Argument a is unused in l
l : (u : Unit) (a : ⊥) → Level
l unit a = lzero

postulate
  u : Unit
  F : (a : ⊥) → Set (l u a)

-- checked type signature
--   F : (a : ⊥) → Set (l u a)
--   of sort  dLub Set (λ a → Set (lsuc (l u a)))
```
If we hack something with `Prop` or `__IMPOSSIBLE_TERM__`, we will have ill-typed sorts. I am not sure this is a good idea for the future, even though it seems to be logically consistent.
It might be very disturbing if `Prop` shows up in error messages, which can be triggered (at least at will).

I now think that serializing `DLub`s is the only clean solution here.

**Comment by jespercockx** [comment]
Before this change, `DLub` was just a function on sorts, i.e. a placeholder for when we do not yet know the sort (it could be either `Inf` or `Type i`). After this change, `DLub` has become a normal form in case the second sort depends irrelevantly on the first, so we have extended the sort system of Agda with these new 'exotic' sorts. 

Is this really what we want? It seems it would be more conservative to return `Inf` instead. This changes nothing in the test suite, except the error message for `Issue2408-error.agda` changes. So maybe this would be a simpler way to fix the problem? I'm asking because I'm currently working on revamping the sort system of Agda a bit.
