### ISSUE TITLE
subtyping inductive sized types

### ISSUE THREAD

**Issue by bixuanzju** [agda/agda#2411]
I was playing around Datatype a la carte with sized types in Agda, and came across this problem (bug?) in subtyping sized types:

```agda
open import Size

data NatF (a : Set) : Set where
  zeroF : NatF a
  succF : a → NatF a

{-# NO_POSITIVITY_CHECK #-}
data μ {i : Size} (F : Set → Set) : Set where
  In : {j : Size< i} → F (μ {j} F) → μ {i} F

pred' : ∀ {i} → μ {i} NatF → μ {i} NatF
pred' (In zeroF) = In zeroF
pred' (In (succF x)) = {!cannot type check with x!}
```

However the following will type check

```agda

data Nat {i : Size}  : Set where
  In : {j : Size< i} → NatF (Nat {j}) → Nat {i}

pred : ∀ {i} → Nat {i} → Nat {i}
pred (In zeroF) = In zeroF
pred (In (succF x)) = x
```

Any pointers would be appreciated!

**Comment by andreasabel** [comment]
The positivity check determines about whether subtyping is admissible.  For `Nat`, it is admissible, since `NatF` is monotone.  For `\mu`, it is not admissible since `F` is arbitrary.  

The positivity check runs on a data type when you define it, but what you would need is a delayed positivity check that runs per-instantiation of a data type.  This is, however, unlikely to become a feature of Agda.

I guess you would like to have `\mu` only for monotone `F`, 
```agda
data μ {i : Size} (F : Set {+}→ Set) : Set where
  In : {j : Size< i} → F (μ {j} F) → μ {i} F
```
this is the feature request in #570.

**Comment by bixuanzju** [comment]
@andreasabel Yes, exactly. Thanks for your explanations!

**Comment by bixuanzju** [comment]
@andreasabel Also I am not clear when subtyping of sized types is admissible, how it relates to the monotonicity of `F`. Is this paper http://www2.tcs.ifi.lmu.de/~abel/mscs06.pdf of yours relevant?

Many thanks!

**Comment by andreasabel** [comment]
Yes, this is relevant, but Agda does not have explicit polarity annotations, it can only use what it infers.  Clearly for negative F like `F X = X -> Bool` subtyping is not admissible for `\mu {i} F`, you could not even program the corresponding cast function yourself!

**Comment by UlfNorell** [comment]
The way you typically solve this is to build a universe of positive functors. Something like

```agda
data Fun : Set where
  F0 F1 Id : Fun
  _+_ _*_ : Fun → Fun → Fun

fun : Fun → Set → Set
fun F0 _ = ⊥
fun F1 _ = ⊤
fun Id X = X
fun (F + G) X = fun F X ⊎ fun G X
fun (F * G) X = fun F X × fun G X

-- Passes positivity check
data μ {i : Size} F : Set where
  In : {j : Size< i} → fun F (μ {j} F) → μ F

NatF : Fun
NatF = F1 + Id

pattern zero   = In (inj₁ tt)
pattern succ n = In (inj₂ n)

-- Passes termination check
pred : ∀ {i} → μ {i} NatF → μ {i} NatF
pred zero     = zero
pred (succ n) = n
```

**Comment by bixuanzju** [comment]
@UlfNorell Thanks! I am aware of the approach you mentioned. My point is that it's more convenient to write conventional datatypes instead of decomposing into base functors. Anyway you can close it since polarity annotation is unlikely to be implemented.

**Comment by andreasabel** [comment]
Maybe also a question for the mailing list.
