### ISSUE TITLE
Problem with checking  with sized types

### ISSUE THREAD

**Issue by bixuanzju** [agda/agda#2412]
I was experimenting the following code, basically I was trying to write the induction principle for the sized type `Arith`

```agda
data ArithF (a : Set) : Set where
  Lit : ℕ → ArithF a
  Add : a → a → ArithF a

data Arith {i : Size} : Set where
  In : {j : Size< i} → ArithF (Arith {j}) → Arith {i}

indA : (p : ∀ {l} → Arith {l} → Set)
       (hl : ∀ {k} {j : Size< k} n → p (In {k} {j} (Lit n))) →
       (ha : ∀ {k} {j : Size< k} {x y : Arith {j}} → p x → p y → p (In {k} {j} (Add x y))) →
       ∀ {i} (t : Arith {i}) → p {i} t
indA p hl ha (In (Lit x)) = hl x
indA p hl ha (In (Add a b)) = ha (indA p {!why hl doesn't fit?!} {!!} a) (indA p {!!} {!!} b)
```

As far as I see, the type of `hl` exactly matches what the first hole requires, but Agda rejects saying 
>Possibly empty type of sizes  (Size< .k)
when checking that the expression (λ {.j₁} → hl) has type
({j : Size< .k} (n : ℕ) → p (In (Lit n)))

I also tried to eta-expand `hl`, but still doesn't work.

Thanks for any help!

**Comment by andreasabel** [comment]
The trick is to _prevent_ eta-expansion by making `k` visible:
```agda
indA : (P : ∀ {l} → Arith l → Set)
       (hl : ∀ k {j : Size< k} n → P (In {k} {j} (Lit n))) →
       (ha : ∀ k {j : Size< k} {x y : Arith j} → P x → P y → P (In {k} {j} (Add x y))) →
       ∀ {i} (t : Arith i) → P {i} t
indA P hl ha (In (Lit x)) = hl _ x
indA P hl ha (In (Add a b)) = ha _ (indA P hl ha a) (indA P hl ha b)
```
For soundness reasons, Agda does not like assumptions like `j : Size< k` in the typing context if there is no evidence that such a `j` always exists.  Unfortunately, Agda by defaults inserts hidden lambdas eagerly (like `λ {.j₁} → hl`), and, in this case, you have to prevent her from doing so. See #1079.

**Comment by andreasabel** [comment]
Thanks for your interest in sized types. Please consider asking such questions on the agda-list first, we'd like to keep the issue tracker for actual bugs.  One can always later file a bug in case there is a (new) problem with Agda.

**Comment by bixuanzju** [comment]
@andreasabel noted, sorry for any inconvenience. Next time I will ask in the mailing list.

**Comment by andreasabel** [comment]
Actually, I thought about it again and managed to improve the type-checker such that your example works.
Here is a simplified example:
```agda
open import Agda.Builtin.Size

data Nat i : Set where
  zero : Nat i
  suc  : {j : Size< i} (n : Nat j) → Nat i

recNat : (P : (i : Size) (n : Nat i) → Set)
  → (fz : ∀{i} → P i zero)
  → (fs : ∀{i}{j : Size< i} (n : Nat j) → P j n → P i (suc n))
  → ∀{i} (n : Nat i) → P i n
recNat P fz fs zero = fz
recNat P fz fs (suc n) = fs n (recNat P fz fs n)
```

**Comment by andreasabel** [comment]
Fixed this as a belated Christmas present. ;-)

@bixuanzju : Thanks for the alert!

**Comment by bixuanzju** [comment]
@andreasabel you rock! 👍
