### ISSUE TITLE
Interaction prefix for show implicit arguments

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2417]
Often I just want to see the implicit arguments once for the result of a specific interaction command.  For instance, I would like to see a goal with implicit arguments printed.  A prefix like `C-u` (for the amount of normalization) would be nice here.

**Comment by m0davis** [comment]
My recommendation: add a family of functions starting with `C-c C-i`, e.g. `C-c C-i C-t` for `agda2-implicit-goal-type`. It seems to me that would be better than either adding another prefix to `C-c` (b/c it's more likely conflict with some other emacs package) or overloading `C-u` (b/c that would mean yet more keystrokes---and I take it the point is to save on keystrokes).  

P.s. Prolly you know this, but you can already do this with 6 extra keystrokes (`C-c C-x C-h` <your-command> `C-c C-x C-h`).

**Comment by andreasabel** [comment]
I realized when Agda reloads, it turns printing implicits off.  Thus, it is fine to C-c C-x C-h C-c C-c RET to introduce all function arguments, including implicits.

However, for just viewing a goal with implicits, I do not want to type C-c C-x C-h C-c C-, C-c C-x C-h, especially I do not want to have to remember to turn implicits off again.  I want no `State` change, so to say, but a `local` modification of the state.

`C-u` is the emacs convention for supplying (numerical) parameters to a command.  We could utilize this.

**Comment by WolframKahl** [comment]
> I realized when Agda reloads, it turns printing implicits off.

Ah! It would be nice if it didn't, so that one can see implicits on load errors.
(That has frustrated me quite a few times...)

**Comment by m0davis** [comment]
@WolframKahl, I believe you can see implicits on load errors by putting {#- OPTIONS --show-implicit #-} at the top of your file.

**Comment by UlfNorell** [comment]
I think the current state of affairs is adequate.

I have enough trouble remembering what number of `C-u`s mean what thing as it is. Typing `C-c C-x C-h` (even if twice) is not that terrible of a burden to warrant a whole new set of commands.
