### ISSUE TITLE
"renamingAll" construct

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda#2418]
One feature that would be an enormous time saver is an addition to the `renaming`/`hiding`/`using` syntax along the lines of `renamingAll`.

For example imagine you're working with two different equivalences:
```
≈₁-isEq : IsEquivalence _≈₁_
≈₂-isEq : IsEquivalence _≈₂_
```
At the moment if you want to open them and use the records within both of them you have to write something along the lines of:
```
open IsEquivalence ≈₁-isEq renaming (
      refl to ≈₁-refl;
      sym to ≈₁-sym;
      trans to ≈₁-trans
    )

  open IsEquivalence ≈₂-isEq renaming (
      refl to ≈₂-refl;
      sym to ≈₂-sym;
      trans to ≈₂-trans
    )
```
An enormous time saver would be to be able to write something which would have the equivalent effect along the following lines:
```
open IsEquivalence ≈₁-isEq renamingAll (≈₁-)
open IsEquivalence ≈₂-isEq renamingAll (≈₂-)
```
If you wanted to add more power to the syntax, you could add a special character * (or some other suitable reserved character) which allows you to specify where to place the original name. For example `renamingAll (≈₁-*)` would result in `≈₁-refl` while `renamingAll (*-≈₁)` would result in `refl-≈₁`.

Obviously one of the questions (among many I'm sure) is how it interacts with misfix notation. I would envisage it working as expected, for example `_#_x_` would become `_≈₁-#_x_` after using `renamingAll (≈₁-*)`. 

Other than that there might be some questions about how it would interact with `using` but hopefully nothing insurmountable?

**Comment by guillaumebrunerie** [comment]
Does the following answer your question?

You can do:

module ≈₁ = IsEquivalence ≈₁-isEq
module ≈₂ = IsEquivalence ≈₂-isEq

and then use ≈₁.refl, ≈₁.sym, ≈₁.trans, ≈₂.refl, ≈₂.sym, ≈₂.trans (it uses
a dot instead of an hyphen, but I think that’s the only difference with
what you are proposing).

**Comment by MatthewDaggitt** [comment]
That would certainly work for plain names, but it doesn't interact well with misfix notation right? If you had for example `_+_` in your module you would have to write `≈₁._+_ a b` instead of `a ≈₁-+ b`?

**Comment by guillaumebrunerie** [comment]
No, I think you can write `a ≈₁.+ b`.

**Comment by MatthewDaggitt** [comment]
Oh you're right, my apologies. Thank you very much for your help!
