### ISSUE TITLE
After emacs starts up, Agda does not process file without restart of Agda

### ISSUE THREAD

**Issue by astump** [agda/agda#2421]
Since I upgraded to Agda 2.5.2, I have been encountering some strange behavior loading Agda files in emacs.  Generally, if I do Control-c Control-l in a buffer where an existing .agda file is open, Agda complains that "Another command is currently in progress".  I have to do Control-c Control-x Control-r to restart Agda, and then I can load the file.  Sometimes this does not happen, but mostly it does.  I am on Ubuntu 16.04, Emacs 24.5.1.  See screenshot for an example of what I see (and what the *agda2* buffer shows in that case).
![screenshot from 2017-01-20 21-19-58](https://cloud.githubusercontent.com/assets/911061/22171560/46e23556-df56-11e6-867a-5170b76943f6.png)

**Comment by m0davis** [comment]
I dunno if this will help but it's the first thing I would try: quit emacs, run "agda-mode compile", restart emacs.

**Comment by astump** [comment]
Thanks for this suggestion. I tried it, but the behavior was the same.

**Comment by andreasabel** [comment]
I think I experience the same sometimes, also when changing the Agda version with `agda2-set-program-version`.  I do know where this comes from.

**Comment by nad** [comment]
Don't?

I've also experienced similar problems, but not consistently.

If anyone can construct a reproducible test case, please report it here.

**Comment by andreasabel** [comment]
> Don't?

Don't.

**Comment by nad** [comment]
I don't think I've experienced this problem in a while now. Can we close this issue?

**Comment by astump** [comment]
I do still regularly experience this issue.  The workaround to restart agda
within emacs is ok.

**Comment by nad** [comment]
> I do still regularly experience this issue.

Are you using the development version of Agda?

**Comment by astump** [comment]
2.5.2 -- so maybe you fixed it in 2.5.3 or later?

**Comment by nad** [comment]
That's what I'm hoping.

**Comment by andreasabel** [comment]
Probably fixed.  Please reopen if you experience this problem again.

**Comment by andreasabel** [comment]
I am having this problem on Mac OS X with 
- GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511)) of 2018-05-31.
- Agda version 2.6.0-03d1720-dirty (current master)

I am experience it for instance after restarting Emacs which does a `desktop-read`; also complains about `selecting deleted buffer`. (See #2698.)
```
error in process filter: Selecting deleted buffer [70 times]
```

**Comment by nad** [comment]
Please provide a self-contained test case.

**Comment by asr** [comment]
label `regression` and milestone `icebox`?

**Comment by nad** [comment]
This is (presumably) an already released regression, without any detailed instructions for reproducing it.

**Comment by jespercockx** [comment]
I'm closing this due to the lack of a reproducible test case.
