### ISSUE TITLE
Inherited projection on lhs

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2423]
```agda
postulate
  A : Set

record R : Set where
  field f : A

record S : Set where
  field r : R
  open R r public

open R -- without this we get the better error: 
  -- Not a valid projection for a copattern: .f
open S

match : S → S
match s .f = s .f
```
reports
```
Cannot eliminate type S with pattern .f (did you supply too many arguments?)
```

**Comment by andreasabel** [comment]
What is happening here is that from the two candidates `S.f` and `R.f` found by the scope checker, `S.f` is silently discarded as it is not a projection for the type checker (see #2422) as it is a composition of projections.  The splitter then only considers `R.f` which has the wrong type.  The resulting error message is not very helpful, as the disambiguation is not reflected.  The cleanest solution would be to correct errors for all possible disambiguations and list all of them.  I think I will for now only improve the present error message.

**Comment by jespercockx** [comment]
Damn I got the wrong issue number, sorry

**Comment by andreasabel** [comment]
:-) Which is the correct one?  Ok, it is #2432.
