### ISSUE TITLE
Do not reload after refine.

### ISSUE THREAD

**Issue by xekoukou** [agda/agda#2425]
Is it possible to not reload after we refine? 

In many cases, the hole is removed and the remaining holes are not affected by the change, so there is no need to reload.

**Comment by andreasabel** [comment]
If you mean `C-c C-r` (refine), then yes, you do not have to reload.  
Agda reloads only after `C-c C-c` (case split), doesn't it?

**Comment by xekoukou** [comment]
I think you are right.
