### ISSUE TITLE
On just warning about missing cases

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2426]
@gallais: Let's discuss the consequences of allowing incomplete definitions!
There are some interactions with pruning
```agda
open import Common.Equality
open import Common.Product

data Bool : Set where
  true false : Bool

f : (x y : Bool) → Bool
f true y     = y
-- f false x = true  -- Missing case

test : let
     X : Bool → Bool → Bool
     X = {! f !}
  in (∀{x y} → X (f false x) y ≡ y) × (X false false ≡ true)
test = refl , refl

-- *Error* buffer
-- /home/abel/tmp/agda-issue-2327/test/bugs/IncompleteOverlapping.agda:15,15-19
-- false != true of type Bool
-- when checking that the expression refl has type false ≡ true
-- /home/abel/tmp/agda-issue-2327/test/bugs/IncompleteOverlapping.agda:8,1-9
-- Incomplete pattern matching for f. Missing cases:
--   f false _
-- when checking the definition of f
```
Since `f false x` is absurd (can never reduce), `x` is rigid, and hence the first argument to meta `X` is removed and Agda solves `X x y = y`.  However, this contradicts the second equation.

If we add the missing clause `f false x = true`, then `X` has for instance solution `f`.

The added default clause in case of missing clauses should maybe rather have as body a non-instantiable (frozen) meta variable!?

**Comment by gallais** [comment]
> The added default clause in case of missing clauses should maybe rather have as body a non-instantiable (frozen) meta variable!?

Ah! That was my first idea too except that I didn't know about freezing and my metas kept getting solved / leaking all over the "unsolved metas / constraints" error messages. When the version with `Nothing` for a body went through all the test cases, I assumed it was alright.

I'll work on the change later today in the train.

**Comment by jespercockx** [comment]
But if we make the missing clauses reduce to a metavariable, then the user will see a metavariable instead of the term for which there is no reduction rule. Maybe it would be better to add a new Blocking tag for when there are missing clauses That way we can prevent the pruning without losing the information in the left-hand side.

**Comment by gallais** [comment]
Good point. How about replacing `Maybe Term` for the right-hand side with `Either BlockedBecause Term`? The reduction machinery can be kept morally the same and the pruning made to work only in the case where we have `Left AbsurdClause`.

**Comment by andreasabel** [comment]
There is already a `MissingClauses` tag for `NotBlocked`, 
```haskell
-- | Even if we are not stuck on a meta during reduction
--   we can fail to reduce a definition by pattern matching
--   for another reason.
data NotBlocked
...
  | AbsurdMatch
    -- ^ We matched an absurd clause, results in a neutral 'Def'.
  | MissingClauses
    -- ^ We ran out of clauses, all considered clauses
    --   produced an actual mismatch.
    --   This can happen when try to reduce a function application
    --   but we are still missing some function clauses.
    --   See "Agda.TypeChecking.Patterns.Match".
...
```
which is handled correctly by the occurs check.
```haskell
-- | Check whether a term @Def f es@ is finally stuck.
--   Currently, we give only a crude approximation.
isNeutral :: MonadTCM tcm => Blocked t -> QName -> Elims -> tcm Bool
...
    Function{} -> case b of
      NotBlocked StuckOn{}   _ -> yes
      NotBlocked AbsurdMatch _ -> yes
      _                        -> no
    _          -> no
```
However, the clause compiler/matcher does not seem to use `MissingClauses` as the clause compiler assumed covering clauses so far...

**Comment by jespercockx** [comment]
An alternative solution would be to *not* insert a catchall clause for an incomplete definition and instead replace the `__IMPOSSIBLE__` in the reduce function by a `return MissingClauses`. However, this would also mean we don't get the `__IMPOSSIBLE__` when there would actually be a bug in the coverage checker.

**Comment by andreasabel** [comment]
This would not be a problem if we could make the warning strict, i.e., an error, on demand.  

It is the usual absurdity: we recently removed the option 
```
$ agda --no-coverage-check
Error: the --no-coverage-check option has been removed
```
now @gallais brings it back, in a better incarnation.

It is time to think about controlling warnings from the command-line in a systematic fashion!
1. suppressing warnings
2. making warnings fatal (for interaction / for success (serialization))
3. making warnings non-fatal (for interaction / for success (serialization))

At that point, we might also think about structuring our command-line options into categories:
1. Operation (`--interactive`, `--html`, `--compile` ...)
2. Parameters (`--termination-depth`)
3. Language extensions (`--rewriting`,...)
4. Warnings / check deactivations... (`no-termination-check`, ...)

**Comment by UlfNorell** [comment]
> 1. Operation (--interactive, --html, --compile ...)

I'm doing something along this line with the new backend API. Compiler backend options will soon be listed in their own sections in `--help`.

**Comment by jespercockx** [comment]
> This would not be a problem if we could make the warning strict, i.e., an error, on demand.

Do you mean the warning would become an error as soon as Agda reaches a missing case during evaluation? That would indeed be another viable option.

**Comment by gallais** [comment]
> instead replace the `__IMPOSSIBLE__` in the reduce function by a return MissingClauses

This seems to do the trick. Should I push it?

> Do you mean the warning would become an error as soon as Agda reaches a missing case during evaluation?

There should probably be a semantic distinction between an "assert total" which crashes during evaluation and a "strict coverage" which would fail upon finding a partial cover in `Typechecking/Coverage.hs`.

**Comment by jespercockx** [comment]
Maybe you can do something like `unless (coverageWarningPresent) __IMPOSSIBLE__` before returning the `MissingClauses`? That way we keep the current behaviour in case the coverage checking passed.

**Comment by andreasabel** [comment]
@jespercockx: sounds good!

> This would not be a problem if we could make the warning strict, i.e., an error, on demand.

I meant if we have an option for strict coverage checking (turning the warning into an error).  Then, encountering missing clauses would be `__IMPOSSIBLE__` and we'd want to crash, like it is currently.

But Jesper's suggestion would work as-is.

**Comment by nad** [comment]
If anyone is planning a major overhaul of the options handling, then I suggest switching to optparse-applicative, like in agda-bisect.

**Comment by andreasabel** [comment]
Sorry for hijacking this issue for a discussion about options which should take place on a new issue.
The original issue seems to be addressed properly but @gallais last commits.
