### ISSUE TITLE
Interaction testsuite: .out files are not updated when changing .agda or .in

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2438]
Interaction testsuite: `.out` files are not updated when changing `.agda` or `.in`.

Possibly introduced by f3ef2f6e72cd98ed17c4879bbd1b8f69aabe42de.

**Comment by andreasabel** [comment]
@asr: My apology, I am now also reporting every little issue.  This gives a forum for discussion and documentation, and the issue number allows automatic cross-references.

**Comment by asr** [comment]
I was waiting that you give me the reason :smile:

Documentation and cross-references are convenient for every one.
