### ISSUE TITLE
Incorrect alignement in latex using the new ACM format

### ISSUE THREAD

**Issue by gallais** [agda/agda#2441]
The alignment method in the LaTeX backend is somehow incompatible with the new `acmart` format. The following small document behaves differently whether compiled using `article` or `acmart`.

acmart:
![incorrect-alignment](https://cloud.githubusercontent.com/assets/1094905/22469399/2c3e9b26-e7cc-11e6-90a3-965d6978aa35.png)

article:
![correct-alignment](https://cloud.githubusercontent.com/assets/1094905/22469402/303ea9dc-e7cc-11e6-9b7a-f1676f14642d.png)

````latex
%\documentclass[acmlarge]{acmart}\settopmatter{printfolios=true}
\documentclass{article}
\usepackage{agda}

\begin{document}

\begin{code}%
\>\AgdaKeyword{data} \AgdaDatatype{Bool} \AgdaSymbol{:} \AgdaPrimitiveType{Set} \AgdaKeyword{where}\<%
\\
\>[0]\AgdaIndent{2}{}\<[2]%
\>[2]\AgdaInductiveConstructor{T} \AgdaSymbol{:} \<[7]%
\>[7]\AgdaDatatype{Bool} \AgdaSymbol{→} \<[15]%
\>[15]\AgdaDatatype{Bool}\<%
\\
\>[0]\AgdaIndent{2}{}\<[2]%
\>[2]\AgdaInductiveConstructor{F} \AgdaSymbol{:} \<[15]%
\>[15]\AgdaDatatype{Bool}\<%
\end{code}
\end{document}
````

**Comment by gallais** [comment]
@kosmikus may know what's going on in this example. I'm not sure it's a polytable problem: lhs2TeX seems to behave properly on a similar input even when using `acmart`.

**Comment by gallais** [comment]
Changing `\defaultcolumn{@{~}l@{~}}` to `\defaultcolumn{@{ }l@{ }}` in `agda.sty` solves the issue for me. Not sure how backwards compatible that change is.

**Comment by nad** [comment]
With `article`:
![With article.](https://cloud.githubusercontent.com/assets/293222/22648534/6a1d1396-ec77-11e6-831b-696d27529c8e.png)

With `acmart`:
![With acmart.](https://cloud.githubusercontent.com/assets/293222/22648548/7b3ce246-ec77-11e6-9365-d703ca25196e.png)

**Comment by nad** [comment]
> Changing `\defaultcolumn{@{~}l@{~}}` to `\defaultcolumn{@{ }l@{ }}` in `agda.sty` solves the issue for me. Not sure how backwards compatible that change is.

I just suggested a similar change (#2353).

**Comment by gallais** [comment]
Thank you!
