### ISSUE TITLE
Request: Being able to use --safe in the OPTIONS pragma

### ISSUE THREAD

**Issue by gallais** [agda/agda#2442]
It is currently not possible to specify that a file should only use the `--safe` subset of the language in its `OPTIONS` pragma.

````agda
{-# OPTIONS --safe #-}
module Safe where
````

yields

> Unrecognized option: --safe

**Comment by gallais** [comment]
I suppose incompatibilities between `--safe` and other features should be non-fatal errors so that it's still possible to edit the file interactively to fix the issue.

There should also be an additional check when typechecking a module that the `OPTIONS` are consistent. [My naïve patch](https://github.com/gallais/agda/commit/2715040840ab472714933346eb1f080a51d30290) turning `--safe` into a `PragmaOptions` does not currently disallow the combined use of `--safe` and `--no-termination-check` which is problematic (see unexpected success in `test/Fail/Issue2442-conflicting.agda`).

**Comment by andreasabel** [comment]
Thanks for your work on this!

I think there is a problem with test/Fail/Issue639-2.agda (see my comments to your patch).

**Comment by gallais** [comment]
I did notice it but forgot to mention this issue's number in the commit fixing the module's name: https://github.com/agda/agda/commit/a87c7ee46b6a7e6763f484c64bd493596ae18d90
