### ISSUE TITLE
Generalising compiler pragmas

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#2444]
Continuing the discussion started in #2431.

One obstacle to stand-alone compiler backends is the way that compiler pragmas are handled at the moment. Basically each backend has a set of pragmas hard-wired into the guts of Agda (parser, scope checker and type checker). It would make much more sense if we could shift the work of dealing with these pragmas to the backend in question.

Currently there are two kinds of compiler pragmas:
- those that attach to a definition (`COMPILED`, `COMPILED_DATA`, `COMPILED_TYPE` and `COMPILED_EXPORT` for the GHC backend)
- those that are global to the current file (`IMPORT` and `HASKELL`)

I propose to simplify this to only two pragmas, one for each kind, with the following syntax

```agda
{-# COMPILE <backend> <qname> <text> #-}
{-# COMPILED_CODE <backend> <text> #-}
```

Each backend would then be responsible for making sense of its own pragmas. For instance, for the GHC backend we might replace

```agda
{-# COMPILED _>>=_ \ _ _ _ _ -> (>>=) #-}
{-# COMPILED_TYPE IO AgdaIO #-}
{-# COMPILED_DATA Maybe Maybe Nothing Just #-}
{-# COMPILED_EXPORT foo agdaFoo #-}
```

with something like

```agda
{-# COMPILE GHC _>>=_ = \ _ _ _ _ -> (>>=)    #-}
{-# COMPILE GHC IO    = type AgdaIO #-}
{-# COMPILE GHC Maybe = data Maybe (Nothing | Just) #-}
{-# COMPILE GHC foo  as agdaFoo #-}
```

`IMPORT` pragmas could be replaced by inline code (the compiler would take care to put it at the top of the file):

```agda
{-# IMPORT Some.Haskell.Module #-} -- becomes
{-# COMPILED_CODE import qualified Some.Haskell.Module #-}
```

A nice side effect of this is that we would get rid of the `COMPILED_DECLARE_DATA` pragma, which only exists because we are too eager when checking the `COMPILED_DATA` pragmas make sense. If we leave it to the GHC backend that problem goes away.

**Comment by nad** [comment]
You missed one instance of `GHC` in the example above:
> ```
> {-# COMPILED_CODE import qualified Some.Haskell.Module #-}
> ```

**Comment by phile314** [comment]
Maybe we can also improve on the pragma names? I think ``COMPILE`` and ``COMPILED_CODE`` are not entirely self-explaining. What about ``COMPILED_DEF`` and ``COMPILE`` instead?

**Comment by nad** [comment]
I suggest that we avoid abbreviations like `DEF`.

**Comment by UlfNorell** [comment]
> Maybe we can also improve on the pragma names? I think COMPILE and COMPILED_CODE are not entirely self-explaining. What about COMPILED_DEF and COMPILE instead?

My reading of the pragma names were: `{-# COMPILE <backend> <name> <text> #-}` means _**compile**_ `<name>` using the information in `<text>`, and `{-# COMPILED_CODE <backend> <text> #-}` means `<text>` is some (already _**compiled**_) _**code**_ in the backend's target language that should get included in the compiled output.

**Comment by UlfNorell** [comment]
A minor consideration is that the new pragmas don't conflict with the old ones, since I'd like to leave the old ones in there for a version or two (with deprecation warnings).

**Comment by andreasabel** [comment]
Instead of `COMPILED_CODE` we could have `EMBED` or `FOREIGN`.
It is not really "already compiled code", it is just embedded code from a foreign (=not Agda) language.

**Comment by UlfNorell** [comment]
I like `FOREIGN`.

**Comment by gallais** [comment]
@UlfNorell Is there a way to turn some language extensions on in the generated code from inside Agda? E.g. I'd like `PackageImports`. If I use:

```agda
module Example where

{-# FOREIGN GHC {-# LANGUAGE PackageImports #-} #-}
```

then I get

```haskell
{-# LANGUAGE EmptyDataDecls, ExistentialQuantification,
             ScopedTypeVariables, NoMonomorphismRestriction, Rank2Types,
             PatternSynonyms #-}
module MAlonzo.Code.Example where

import MAlonzo.RTE (coe, erased, addInt, subInt, mulInt, quotInt,
                    remInt, geqInt, ltInt, eqInt, eqFloat)
import qualified MAlonzo.RTE
import qualified Data.Text

{-# LANGUAGE PackageImports #-}
```

and the `LANGUAGE` pragma is just ignored by ghc.

**Comment by nad** [comment]
@gallais, I suggest that you open a new issue for this question.
