### ISSUE TITLE
The LaTeX backend is slow

### ISSUE THREAD

**Issue by nad** [agda/agda#2445]
The LaTeX backend is very slow (at least for one set of examples). I suspect that the LaTeX backend uses some quadratic algorithm.

Consider modules of the following kind:
```
\documentclass{article}

\begin{document}

\begin{code}
module _ where
module _ where
module _ where
module _ where
\end{code}

\end{document}
```
With 100 `module _ where` lines:
```
$ time agda --ignore-interfaces Slow.lagda.tex
Checking Slow (/tmp/Slow.lagda.tex).
Finished Slow.

real    0m0.074s
user    0m0.072s
sys     0m0.000s
$ time agda --latex Slow.lagda.tex 
Skipping Slow (/tmp/Slow.agdai).

Checking if agda.sty is found by the LaTeX environment.

Calling: kpsewhich --path=latex agda.sty
latex/agda.sty

real    0m0.106s
user    0m0.104s
sys     0m0.000s
```
With 200 `module _ where` lines:
```
$ time agda --ignore-interfaces Slow.lagda.tex
Checking Slow (/tmp/Slow.lagda.tex).
Finished Slow.

real    0m0.105s
user    0m0.100s
sys     0m0.004s
$ time agda --latex Slow.lagda.tex 
Skipping Slow (/tmp/Slow.agdai).

Checking if agda.sty is found by the LaTeX environment.

Calling: kpsewhich --path=latex agda.sty
latex/agda.sty

real    0m0.332s
user    0m0.324s
sys     0m0.004s
```
With 400 `module _ where` lines:
```
$ time agda --ignore-interfaces Slow.lagda.tex
Checking Slow (/tmp/Slow.lagda.tex).
Finished Slow.

real    0m0.185s
user    0m0.176s
sys     0m0.008s
$ time agda --latex Slow.lagda.tex 
Skipping Slow (/tmp/Slow.agdai).

Checking if agda.sty is found by the LaTeX environment.

Calling: kpsewhich --path=latex agda.sty
latex/agda.sty

real    0m1.202s
user    0m1.192s
sys     0m0.008s
```

**Comment by nad** [comment]
Profiling indicates that most of the time is spent in the `code` function in `Agda.Interaction.Highlighting.LaTeX`. In some cases this function calls itself recursively twice:
```haskell
  when (isSpaces tok) $ do
    spaces $ T.group tok
    code

  case aspect (info tok') of
    Nothing -> output $ escape tok
    Just a  -> output $ cmdPrefix <+> T.pack (cmd a) <+> cmdArg (escape tok)

  code
```
@stevana, is this intended? Should `when` be replaced by if-then-else?

**Comment by andreasabel** [comment]
You could try if it still works with if-then-else... (you are probably trying already).

**Comment by nad** [comment]
This seems to have been intended. The code uses an exception monad, and a non-local exit is used when there is no more input to process.

I found the problem causing the poor performance: The monoid instance of Text was used, repeatedly, to construct a Text value.

**Comment by nad** [comment]
By the way, the time profile was somewhat confusing:
```
[...]
                                                                                                                                                                                                                                             individual      inherited
COST CENTRE                                                                          MODULE                                             SRC                                                                             no.       entries  %time %alloc   %time %alloc
[...]
            code                                                                     Agda.Interaction.Highlighting.LaTeX                src/full/Agda/Interaction/Highlighting/LaTeX.hs:(320,1)-(383,38)                28387          0   77.9   83.6    79.1   91.5
             append                                                                  Data.Text                                          Data/Text.hs:(455,1)-(467,18)                                                   28498      33600    0.0    0.0     0.6    7.5
              run                                                                    Data.Text.Array                                    Data/Text/Array.hs:178:1-34                                                     28509      10400    0.5    7.5     0.5    7.5
[...]
```
I guess most of the time was spent in `append` and `run`, but the `%time` and `%alloc` columns put the blame on `code`. However, note the `entries` column: there are zero entries for `code`, but lots for the other two functions.

**Comment by nad** [comment]
Why did you assign me a closed issue?

**Comment by andreasabel** [comment]
Because you fixed it, thus it is your issue.  This was the practice we had, at least on google code.

**Comment by UlfNorell** [comment]
Tbh I also find it annoying when I get emails about old closed issues. Is there a use case where having someone assigned to a closed issue matters? If the issue reappears it's not that hard to see who fixed it.

**Comment by andreasabel** [comment]
Matters maybe only for statistical purposes, when you want to argue with Peter about your salary increase. :)  I can stop assigning you guys...

**Comment by asr** [comment]
You can use the assignation information for searching purposes. Sometimes I only can remember who was assigned to an issue I'm looking for.
