### ISSUE TITLE
Make sure cubical additions to Agda.Primitive are consistent with other features.

### ISSUE THREAD

**Issue by Saizan** [agda/agda#2446]
Several cubical-related primitives are in Agda.Primitive so that for every datatype or record declaration we can derive the reduction rules for primComp.

The primitives there are not enough to prove univalence so they should in principle be consistent with --with-K.

A issue remains with parametrized modules, which allows to derive "unsafe" versions of primPOr and primComp which do not check their preconditions.

**Comment by Saizan** [comment]
`--cubical` implies `--without-K` so we are fine wrt consistency.

Also 14179ae prevents the binding of unsafe versions of the primitives, so that's also handled now.

**Comment by nad** [comment]
Please add one or more test cases.
