### ISSUE TITLE
Cache loaded interfaces even if a type error is encountered

### ISSUE THREAD

**Issue by nad** [agda/agda#2447]
Consider the following modules:
* `M` is empty.
* The following module imports `M`, and contains a type error:
  ```
  import M

  Rejected : Set
  Rejected = Set
  ```
If the latter module is loaded using the Emacs mode, then `M` is checked or skipped. If the module is then reloaded, then the interface file for `M` is read again, because the interface has not been cached.

For modules with lots of dependencies it can take a fair amount of time to read all the interface files, so I suggest that interfaces should be cached even if a type error is encountered.

**Comment by nad** [comment]
A test case:
```
$ cat Issue2447/M.agda
module Issue2447.M where
$ cat Issue2447.agda 
import Issue2447.M

Rejected : Set
Rejected = Set
$ cat Issue2447.sh 
#!/bin/sh

AGDA=$1

$AGDA --interaction <<EOF
IOTCM "Issue2447.agda" None Indirect (Cmd_load "Issue2447.agda" ["--ignore-interfaces"])
IOTCM "Issue2447.agda" None Indirect (Cmd_load "Issue2447.agda" [])
EOF
```
Current output (partial):
```
$ ./Issue2447.sh agda
[...]
(agda2-info-action "*Type-checking*" "Checking Issue2447 ([...]).\n" t)
(agda2-info-action "*Type-checking*" " Checking Issue2447.M ([...]).\n" t)
(agda2-info-action "*Type-checking*" " Finished Issue2447.M.\n" t)
[...]
(agda2-info-action "*Type-checking*" "Checking Issue2447 ([...]).\n" t)
(agda2-info-action "*Type-checking*" " Skipping Issue2447.M ([...]).\n" t)
```
The line containing `Skipping Issue2447.M` should not be part of the output.

**Comment by nad** [comment]
The problem was that `Agda.Interaction.InteractionTop.handleCommand` reset the state (also the persistent state) if an error was encountered. Perhaps this problem was introduced by the fix for #2174.

**Comment by nad** [comment]
There is also a similar problem if an error is encountered in an imported module.

The function `freshTCM` is used when imported modules are typechecked. This function does not preserve all of the persistent state, only the `stBenchmark` and `stAccumStatistics` components. @andreasabel, you introduced this function, can you explain why some parts of the persistent state are more persistent than others?

**Comment by nad** [comment]
I changed the function so that the persistent state is preserved (unless if certain errors are encountered). Hopefully this did not break anything.

**Comment by andreasabel** [comment]
> The function freshTCM is used when imported modules are typechecked. This function does not preserve all of the persistent state, only the stBenchmark and stAccumStatistics components. @andreasabel, you introduced this function, can you explain why some parts of the persistent state are more persistent than others?

As far as I remember, I just factored out some code from `Interaction.Imports` and called it `freshTCM`.
