### ISSUE TITLE
Agda depends on additional C library icu

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2449]
Agda seems to depend on more libraries, this should be documented (amongst others?) in the CHANGELOG and the prerequisites in the README.
```
Configuring text-icu-0.7.0.1...
cabal: Missing dependencies on foreign libraries:
* Missing C libraries: icuuc, icui18n, icudata
```
On my system, I can fix this with
```
sudo apt-get install libicu-dev
```

**Comment by identicalsnowflake** [comment]
I didn't notice anything on my Linux build (it seems I already had this installed), but on my OSX machine I had to: `brew install icu4c` and then manually `brew link icu4c --force`.

**Comment by nad** [comment]
I added a dependency on `text-icu` in order to count extended grapheme clusters rather than code points in the LaTeX backend. However, I raised the possibility to revert this commit (#1832), so we can delay updating the documentation until we've decided what to do.

**Comment by nad** [comment]
I don't think the commit will be reverted.

**Comment by UlfNorell** [comment]
What's the impact on Windows users? I'd rather not make Agda a nightmare to install on Windows just to fix obscure unicode/latex interactions.

**Comment by nad** [comment]
There seems to be a [Windows installer](http://site.icu-project.org/download/58#TOC-ICU4C-Download) for ICU. The page contains a note about how "There are known issues building on IBM z/OS", so I imagine that cross-platform support is a priority for this project.

**Comment by nad** [comment]
An alternative would be to use a native Haskell implementation of the algorithm. I found a [Haskell implementation](https://github.com/rde1024/hs-unicode-algs), but this implementation does not seem to be available on Hackage, it depends on a Unicode data file, and I think it is based on an older version of the Unicode standard.

**Comment by UlfNorell** [comment]
We might also consider adding a cabal flag for the dependency so that it's possible to install Agda without it. Is it possible to have cabal issue a warning but proceed with the installation if ICU is missing?

**Comment by nad** [comment]
> Is it possible to have cabal issue a warning but proceed with the installation if ICU is missing?

I am not aware of such a feature.

**Comment by nad** [comment]
@UlfNorell and I discussed this. I think it makes sense to add a Cabal flag for the dependency on `text-icu`.

I do not think that the LaTeX backend should have different semantics depending on whether `text-icu` is available or not. One option would be to only include the LaTeX backend if `text-icu` is available. Another would be to activate extended grapheme cluster counting with a flag that gives an error message in the absence of `text-icu`. What do you think?

**Comment by UlfNorell** [comment]
The flag seems like the best option. People have been using the LaTeX backend without extended grapheme whatsit in the past, so it would make sense to keep that possibility open.

**Comment by andreasabel** [comment]
This should be done soon, so we are able to release.

**Comment by asr** [comment]
I renamed some labels for avoiding confusion. The new labels are `release-blocker`, `blocking-issue` and `blocked-by-issue`.

**Comment by jmchapman** [comment]
'brew link icu4c --force' doesn't seem to fix it for me.

It works when I do 'cabal install' but not when I do 'make install', which I want to do so I can run the test suite.

**Comment by asr** [comment]
Does this command work for you

```
$ make install CABAL_OPTS='-f -enable-cluster-counting'
```

?

**Comment by jmchapman** [comment]
no, i get the same error message

**Comment by asr** [comment]
It seems we cannot disable an enabled flag from the command-line options...

Anyway, does removing `-fenable-cluster-counting` from the line

```
CABAL_INSTALL_OPTS = -fenable-cluster-counting $(CABAL_OPTS)
```
in the Makefile fix your problem?

**Comment by asr** [comment]
@jmchapman, I need to freeze the stable-2.5 branch to make the release of 2.5.3. Since your problem is not a final user problem but a developer problem (i.e. `cabal install` works but `make install` doesn't) and since this issue has the milestone 2.5.3, could you close the issue and file a new issue please.

**Comment by asr** [comment]
I filed Issue #2742.
