### ISSUE TITLE
Agda panics when attempting to rewrite a typeclass Eq

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#2451]
```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Equality renaming (_≡_ to _≡≡_)

record Eq (t : Set) : Set₁ where
  field
    _≡_ : t → t → Set

open Eq {{...}}

{-# BUILTIN REWRITE _≡_ #-}

instance
  eqN : Eq Nat
  eqN = record { _≡_ = _≡≡_ }

postulate
  plus0p :  ∀{x} → (x + zero) ≡ x

{-# REWRITE plus0p #-}
```

I get `Panic: Pattern match failure in do expression at src/full/Agda/TypeChecking/Rewriting.hs:151:3-11 when checking the pragma REWRITE plus0p`.

**Comment by andreasabel** [comment]
New error will be:
```
plus0p  does not target rewrite relation
when checking the pragma REWRITE plus0p
```
This is because `plus0p` targets `_≡≡_ `, which is not the rewrite relation.

**Comment by andreasabel** [comment]
I fixed the issue in a negative way.  For a positive fix, we could extend Agda to allow several rewrite relations.  Please open a new issue if you want to request such a feature.

**Comment by identicalsnowflake** [comment]
@andreasabel 

To be honest I don't actually know what I'm looking for or whether there's enough already: I encountered this because I wanted to try some rewrite rules on `List t`, like `∀ {t} {{_ : Eq t}} (xs : List t) -> id <$> xs ≡ xs`, but this is problematic because the `Eq` for `List t` is derived from `Eq t`.

From a mathematical sense, builtin eq is "stronger" than any other valid equality, so if a theorem like `id <$> xs = xs` respects builtin eq, then it must respect any other equality too.

But I'm not sure how to say this in a way that gives me usable rewrite rules.

**Comment by identicalsnowflake** [comment]
Here is what confuses me:

```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Equality renaming (_≡_ to builtinEq)

record Eq (t : Set) : Set₁ where
  field
    _≡_ : t → t → Set

open Eq {{...}}

_≡≡_ = builtinEq

{-# BUILTIN REWRITE _≡≡_ #-}

instance
  eqN : Eq Nat
  eqN = record { _≡_ = _≡≡_ }

postulate
  plus0p :  ∀{x} → (x + zero) ≡≡ x

{-# REWRITE plus0p #-}
```

**Comment by andreasabel** [comment]
What confuses you?  This is accepted, as expected, no?

**Comment by identicalsnowflake** [comment]
oops, I apparently hadn't rebuilt. Yes, it works as expected now!
