### ISSUE TITLE
The LaTeX backend does not handle options very well

### ISSUE THREAD

**Issue by nad** [agda/agda#2452]
Consider the following code:
```
{-# OPTIONS  --no-positivity-check
             --no-termination-check #-}
```
The LaTeX backend renders this code in the following way:
![bug](https://cloud.githubusercontent.com/assets/293222/22757274/7b906f04-ee4a-11e6-95ce-8f78df0100e1.png)
There are three problems here:
* The two options are not aligned.
* The character sequence `--` is rendered as an en dash (`–`).
* I would prefer if a different font style was used for the options.

**Comment by nad** [comment]
Perhaps the second problem can be fixed by escaping dashes in the following way: `{-}`.

The third problem could be fixed rather easily if the highlighting machinery generated a (new?) `Aspect` for options.

**Comment by nad** [comment]
The comment-starting character sequence `--` is also typeset using an en dash.

**Comment by gallais** [comment]
- [x] The two options are not aligned.
- [x] The character sequence `--` is rendered as an en dash (`–`).

The alignment issue is solved by introducing a new aspect for options (so far they were just returned as raw strings): the alignment code kicks in once they're assigned this new aspect.
Your suggestion to use `{-}` seems to work fine. This is what we get:

![options-lagda](https://cloud.githubusercontent.com/assets/1094905/22806564/175ea04e-ef23-11e6-9fa3-1b84ecaee798.png)

- [ ] I would prefer if a different font style was used for the options.

At the moment `OPTIONS` is considered to be a keyword. We could either change `\AgdaKeyword` in `agda.sty` so that all-caps keywords don't look too awful or add a special case specifically detecting when the keyword in question is all-caps (`OPTIONS`, `BUILTIN`, `REWRITE`, `COMPILED`, etc.) and assign it a different aspect?

**Comment by nad** [comment]
I was referring to the options, not the keyword. The font style used above works for me.

**Comment by nad** [comment]
I suspect that your commit does not handle options like `-v 100` correctly.

**Comment by gallais** [comment]
Good point. I think I'll generate the list of all possible strings corresponding to pragma options using [this list](https://github.com/agda/agda/blob/master/src/full/Agda/Interaction/Options.hs#L550) and then test for membership.

**Comment by nad** [comment]
I suggest that you instead define a highlighting aspect corresponding to `TokString`, and use this aspect for all pragma strings. This would make alignment work also for other pragmas, right? Perhaps the aspect could be called `Pragma`, or `PragmaData`, or something like that.

**Comment by nad** [comment]
Another way to handle the problem with `--` might be to not activate TeX ligatures, but perhaps that only works when XeLaTeX and LuaLaTeX are used.

I wonder if there are also other TeX ligatures that could be problematic.

**Comment by nad** [comment]
> I wonder if there are also other TeX ligatures that could be problematic.

Some examples: `` !` `` gets turned into `¡`, `` ?` `` gets turned into `¿`, `x''` gets turned into `x”`, ``` `` ``` gets turned into `“`.

**Comment by nad** [comment]
@gallais, #3370 "fixes" a problem that is related to the discussion above. However, arguably the problem was that you did not include something like `\usepackage[T1]{fontenc}` in the document that you compiled.

I think that we should either have a complete solution for problems of this kind, or none at all. Given that the problems that we discuss [are related to fonts and font encodings](https://tex.stackexchange.com/a/192975) I am leaning towards not even trying to fix this (in line with #3224). This would involve dropping the special cases for `-`, `<`, and `>` from the `escape` function.

**Comment by gallais** [comment]
I followed [the docs](https://agda.readthedocs.io/en/latest/tools/generating-latex.html#unicode-latex) to get my document up to date and assumed that the garbled
output was a bug, especially given that it was an ascii character causing the problem.

I think we will get a lot of similar bug reports (and waste a lot of people's time because
they'll start by assuming they screwed up somewhere in LaTeX which is notoriously hard
to debug) unless we provide people with a default file which works on at least ascii-only
files (they can then write pages of `\newunicodechar` to fit their use-case).

**Comment by nad** [comment]
> I followed [the docs](https://agda.readthedocs.io/en/latest/tools/generating-latex.html#unicode-latex) to get my document up to date and assumed that the garbled
output was a bug, especially given that it was an ascii character causing the problem.

The documentation that you link to does not present a complete LaTeX document. Without knowledge of the class that is used and other settings it is hard to give complete and correct advice to users.

> I think we will get a lot of similar bug reports (and waste a lot of people's time because
they'll start by assuming they screwed up somewhere in LaTeX which is notoriously hard
to debug) unless we provide people with a default file which works on at least ascii-only
files (they can then write pages of `\newunicodechar` to fit their use-case).

The following ASCII-only file still triggers the kind of problem that you tried to fix:
```latex
\documentclass{article}

\usepackage{agda}

\begin{document}

\begin{code}
postulate
  !` ?` : Set
\end{code}

\end{document}
```
I don't think it makes sense to try to predict and fix every conceivable problem. There is also a risk that our fixes break certain setups (this was one of the main reasons for going ahead with #3224: people inadvertently submitted papers with the wrong font). However, we could provide a list with suggested fixes for frequently occurring problems, without any guarantees that the fixes work in every possible setting.

**Comment by nad** [comment]
Note that switching to math mode (like in edad5a8334e86a456fc04062897a83b255349a12) might be incorrect in some cases, because the math font glyphs and the text font glyphs might be different, and the user might want to use the text font glyphs.

**Comment by nad** [comment]
> I suggest that you instead define a highlighting aspect corresponding to `TokString`, and use this aspect for all pragma strings. This would make alignment work also for other pragmas, right? Perhaps the aspect could be called `Pragma`, or `PragmaData`, or something like that.

I've implemented this.

**Comment by nad** [comment]
> Note that switching to math mode (like in edad5a8334e86a456fc04062897a83b255349a12) might be incorrect in some cases, because the math font glyphs and the text font glyphs might be different, and the user might want to use the text font glyphs.

I have already encountered such a problem. Consider the following code:
```latex
\documentclass{article}

\usepackage{agda}

\pagestyle{empty}

\begin{document}

\begin{code}
{-# FOREIGN GHC
  f :: a -> a
  f x = x
  #-}
\end{code}

\end{document}
```
When I compile this code using XeLaTeX I get the following output:

![bug](https://user-images.githubusercontent.com/293222/48063297-e5cc2100-e1c4-11e8-9dde-b83ca4485aaa.png)

I'll get rid of the special cases for `<`, `>` and `-`.

**Comment by nad** [comment]
> However, we could provide a list with suggested fixes for frequently occurring problems, without any guarantees that the fixes work in every possible setting.

See #3371.

**Comment by gallais** [comment]
I'll install this version and try your `fontenc` suggestion.

I still think that we could provide template files to get newcomers going with a
basic project (e.g. an internship report or a draft paper in no particular style yet).
This could also declare a few unicode characters (the ones used by the core
language for instance).

Would that incur any burden on us as long as we make it clear that any extra
import / change to the class may break the build in ways we are not responsible for?
