### ISSUE TITLE
Internal error when postulating instance

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#2456]
```agda
record Class (t : Set) : Set where

postulate
  t : Set
  
  instance Class t


```
`An internal error has occurred. Please report this as a bug. Location of the error: src/full/Agda/Syntax/Concrete/Definitions.hs:319`

**Comment by andreasabel** [comment]
Probably introduced in connection with fix for #1698.

Fix: give a regular error instead of an internal error.
