### ISSUE TITLE
Internal error (irrefutable pattern failed) with overlapping copattern/noncopattern definitions

### ISSUE THREAD

**Issue by rntz** [agda/agda#2468]
The following code:

```agda
record Unit : Set where
  constructor tt

record MyRecord : Set where
  field
    fst : Unit
    snd : Unit

open MyRecord

example : MyRecord
fst example = tt
example = record { fst = tt ; snd = tt }
```

Produces the following internal error:

```src/full/Agda/Utils/List.hs:296:3-42: Irrefutable pattern failed for pattern (left, el : right)```

Expected behavior: an error message telling me that I can't simultaneously define `example` directly and using copatterns.

**Comment by asr** [comment]
Agda version?

**Comment by rntz** [comment]
```
$ agda --version
Agda version 2.4.2.5
```

**Comment by asr** [comment]
I got the expected error using Agda 2.5.2.
