### ISSUE TITLE
Overloaded number syntax

### ISSUE THREAD

**Issue by wenkokke** [agda/agda#2470]
I'm pretty sure this has come up before, but is there any reason the number syntax has to be bound to natural numbers?

If we would have numbers unfold to applications of whatever the successor and zero for naturals happen to be—but don't enforce the type—then we could use the same number syntax for various different types of number (naturals, finite types, positive naturals, etc).

E.g.

    n4 = 4 : Nat
    f7 = 7 : Fin 12
    p5 = 5 : Pos

Where `Pos` is defined as:

    data Pos : Set where suc : Nat -> Pos

Would there be any interest in this? Or would the fact that folks could get errors when the type of the number isn't entirely clear outweigh any possible benefits?

**Comment by jespercockx** [comment]
See https://github.com/agda/agda/blob/master/CHANGELOG.md#literals-and-built-ins

**Comment by wenkokke** [comment]
Thanks @jespercockx !

The fromNAT solution does address this issue, but only for types A for which there exists a total mapping from the natural numbers to A. This isn't true for finite types and it isn't true for positive naturals.

**Comment by jespercockx** [comment]
Actually you can: see https://agda.readthedocs.io/en/latest/language/literal-overloading.html on how.

**Comment by wenkokke** [comment]
Thanks! 👍

**Comment by identicalsnowflake** [comment]
^^ For what it's worth, this does seem to be missing for `Float` literals.
