### ISSUE TITLE
Corecursive records: Proving propositional equality if all fields are propositionally equal

### ISSUE THREAD

**Issue by JLimperg** [agda/agda#2471]
Greetings,

consider a coinductive record `R` with single field `force`. Currently, as far as I can tell, it is impossible to define a function of type

    (r s : R) → force r ≡ force s → r ≡ s

since one cannot deconstruct `r` and `s`. Hence the questions:

1. Am I overlooking something and such a function can be defined?
2. If not, should this be possible?

**Comment by andreasabel** [comment]
For coinductive records, you should not use propositional equality (unless you are playing with cubical Agda).  You should define equality coinductively as well. See, for instance,

  http://www.cse.chalmers.se/~abela/eptcs14.pdf

Does this help?

In general, the Agda mailing list is the right place to ask such questions, the issue tracker should be kept for actual bugs.

**Comment by JLimperg** [comment]
Apologies for asking this question in the wrong forum. I'll turn to the mailing list and add a bit more context as to why I want propositional equality rather than a bisimulation. In any case, thank you for the pointer.
