### ISSUE TITLE
Don't reread the source code without checking that it is unchanged

### ISSUE THREAD

**Issue by nad** [agda/agda#2473]
The following problems should be fixed:
- [ ] `Agda.Interaction.Imports.buildInterface` rereads the source code before hashing it. It should hash the source code as seen by the parser.

  Sometimes I edit the file while it is being type-checked, and then Agda does not do anything when I try to reload. I guess that the problem is that Agda hashes the edited code.
- [ ] `Agda.Interaction.Highlighting.HTML.generatePage` rereads the source code before generating the HTML file, and does not check the hash present in the interface.
- [ ] `Agda.Interaction.Highlighting.LaTeX.generateLaTeX` rereads the source code before generating the LaTeX file, and does not check the hash present in the interface.

  If the source code does not match the highlighting information, then the generated LaTeX code can be seriously broken.

Perhaps the last two problems can be fixed by storing the source code in the interface.

**Comment by nad** [comment]
You can (perhaps) use the following script to trick Agda into accepting a file containing invalid code:
```
#!/bin/bash

# Based on Issue1232.sh, written by Guillame Brunerie and Ulf Norell.

AGDA_BIN=$1

PIPE=bug.pipe
rm -f $PIPE
mkfifo $PIPE

# Forces the pipe to stay open.
sleep 2 > $PIPE &
SLEEP_PID=$!

$AGDA_BIN --interaction --no-libraries < $PIPE 2>&1 &

function load {
  echo "IOTCM \"Bug.agda\" None Indirect (Cmd_load \"Bug.agda\" [])" > $PIPE
}

# Write some correct code to Bug.agda.
cat > Bug.agda <<EOF
module Bug where

open import Agda.Builtin.Equality
open import Agda.Builtin.Nat

f : Nat → Nat
f zero    = zero
f (suc n) = f n

n = 10000000

slow : f n ≡ 0
slow = refl
EOF

# Load the file. This should take a little while.
load

# Make sure that Agda has finished loading (but not processing) the file.
sleep 0.1

# While the file is being loaded, replace the contents of Bug.agda.
cat > Bug.agda <<EOF
module Bug where

data Empty : Set where

bad : Empty
bad = bad
EOF

# Reload. Agda should complain, but, if things are scheduled in the "right" way, won't.
load

# Make sure that Agda has finished processing the file.
sleep 0.1

# Clean up.
rm -f $PIPE Bug.agdai

# Free the pipe to prevent errors on NFS file systems.
kill $SLEEP_PID
wait $SLEEP_PID 2> /dev/null
```

Exercise: Set things up in such a way that the highlighting looks reasonable when the invalid code is loaded in Emacs.

**Comment by asr** [comment]
@jespercockx, instead of removing the milestones modify them, please.

**Comment by UlfNorell** [comment]
Perhaps we should have a milestone for not-anytime-soon, so we can distinguish between issues that haven't been assigned a milestone and issues that we don't plan to fix anytime soon.

I suggest `icebox`.

**Comment by asr** [comment]
I was thinking in a similar milestone. Please add the `icebox` one.

**Comment by UlfNorell** [comment]
Done.

**Comment by nad** [comment]
A potential problem: `Agda.Interaction.FindFile.moduleName'` reads source files. I have not checked whether this could lead to race conditions like the ones reported above.

**Comment by nad** [comment]
I (hope that I) fixed all the issues in the OP, as well as the potential problem with `moduleName'`. As an added bonus `moduleName'` (now called `moduleName`) no longer reads or parses files.
