### ISSUE TITLE
Regression related to sized types

### ISSUE THREAD

**Issue by nad** [agda/agda#2484]
Consider the following code:
```agda
module _ (_ : Set) where

open import Agda.Builtin.Size

postulate
  I : Set

record ∃ (B : I → Set) : Set where
  constructor _,_
  field
    proj₁ : I
    proj₂ : B proj₁

module M (_ : Set₁) where

  mutual

    data P (i : Size) (x y : I) : Set where
      ⟨_⟩ : ∃ (Q i x) → P i x y

    record Q (i : Size) (x y : I) : Set where
      coinductive
      field
        force : {j : Size< i} → P j x y

open M Set

postulate
  map   : (B : I → Set) → (∀ x → B x → B x) → ∃ B → ∃ B
  lemma : ∀ x y i → Q i x y → Q i x y

p  : ∀ x i → P i x x
q′ : ∀ x i → ∃ λ y → Q i x y
q  : ∀ x i → Q i x x

q′ x i              = x , q x i
p x i               = ⟨ map _ (λ y → lemma x y _) (q′ x _) ⟩
Q.force (q x i) {j} = p _ _
```
This code is accepted by Agda 2.5.2, but rejected by Agda 2.6.0-1b0d568:
```
Termination checking failed for the following functions:
  p, q′, q
Problematic calls:
  q x₁ i
    (at [...])
  q′ x₁ ω
    (at [...])
  p x₁ j
    (at [...])
```
Note the occurrence of `ω` above.

If any of the following changes are performed, then the code is also rejected by Agda 2.5.2:
* If the last underscore is replaced by `j`.
* If the module `M` is inlined.
* If the top-level module's module parameter is removed.
* If the definition of `q` is moved before the definitions of `q′` and `p`.
* If the definition of `P` is replaced by the following code, and `⟨_⟩` is removed from the definition of `p`:
  ```
  P : Size → I → I → Set
  P i x y = ∃ (Q i x)
  ```
On the other hand, if any of the following changes are performed, then the code is accepted by both versions of Agda:
* If the definition of `q′` is placed between the definitions of `p` and `q`, or after the definition of `q`.
* If the penultimate underscore is replaced by `x`.
* If the third or fourth underscores from the end are replaced by `i`.
* If the fifth underscore from the end is replaced by `Q _ _`.

Given that these variations are accepted I guess that most or all of the rejected variations should also be accepted.

**Comment by andreasabel** [comment]
Congrats! Almost certainly you broke the hack to make the size solver work with parameter-refinement.
If you put a `?` for the offending size (which is solved by infinity),
```agda
p x i               = ⟨ map _ (λ y → lemma x y _) (q′ x {!!}) ⟩
```
you can see that Agda fails to solve a trivial constraint.
```
Failed to solve the following constraints:
  [73, 75, 78] i =< ?0 _ x i : Size
```
The solution is to implement a whole new size-solver that can deal with parametrized size metas properly.

**Comment by nad** [comment]
Agda 2.6.0-17a4b08 accepts the first example, as well as the following variants (listed above):
* If the last underscore is replaced by `j`.
* If the module `M` is inlined.
* If the top-level module's module parameter is removed.
* If the definition of `P` is replaced by the following code, and `⟨_⟩` is removed from the definition of `p`:
  ```
  P : Size → I → I → Set
  P i x y = ∃ (Q i x)
  ```
* If the definition of `q′` is placed between the definitions of `p` and `q`, or after the definition of `q`.
* If the penultimate underscore is replaced by `x`.
* If the third or fourth underscores from the end are replaced by `i`.
* If the fifth underscore from the end is replaced by `Q _ _`.

The following variant is still rejected:
* If the definition of `q` is moved before the definitions of `q′` and `p`.

This variant is also rejected if all parametrised modules are removed, so I have opened a new ticket for it (#2930).

The present issue can be closed once suitable test cases have been added.
