### ISSUE TITLE
readthedocs.org versions are branches not releases

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#2485]
I just tried to look at the documentation for 2.5.2 and found that the only two versions are `latest` and `stable-2.5`, none of which match the current release. How do we make readthedocs build keep the docs for all released versions?

**Comment by fredrikNordvallForsberg** [comment]
If I understand correctly, it should be possible to use e.g the [v2.5.2 tag](https://github.com/agda/agda/releases/tag/v2.5.2) for this: https://docs.readthedocs.io/en/latest/versions.html#how-we-envision-versions-working

**Comment by phile314** [comment]
I just tried it out, one just has to switch the active flag on the tag then it gets built. I have done that now for 2.5.2. Will update the release instructions accordingly. Note that only readthedocs Agda admins can do that (currently me, asr, andreas).

We could also switch stable-2.5 to protected, then it would not appear in the listing but you could still look at it using the direct [link](http://agda.readthedocs.io/en/stable-2.5/)? Just to avoid some name confusion?

Default version is still latest.

**Comment by fredrikNordvallForsberg** [comment]
I guess all releases should be active? Making stable-2.5 protected seems like a good idea to me.

**Comment by phile314** [comment]
I updated the release instructions:
https://github.com/agda/agda/commit/49cd0c8ed0a06d7b0aa5b65af1abf85054d3a261

Default doc version is now 2.5.2, as I think it makes more sense to default to the latest release than the current master branch.

The manual for the old versions (2.5.1 etc.) doesn't build right now, so the old ones are still inactive. I don't think this is that much of a problem, so I am going to close this issue anyway. If someone wants to take a look, feel free to reopen.

PS: If someone wants admin rights, just ping me.
