### ISSUE TITLE
Imports via FOREIGN are not transitively inherited anymore

### ISSUE THREAD

**Issue by gallais** [agda/agda#2486]
The `IMPORT` pragma used to be inherited by the modules importing the one it was in. The current `FOREIGN` replacement isn't. As a consequence, a compiled base type used in multiple modules can be handled by:

* either adding a `FOREIGN` import pragma to *all* of the modules using it
* or duplicating the data declaration code and converting between the `COMPILE`'d one and the "internal" one (cf. gallais/typing-with-leftovers@456bf35339a72eb0fb9f9ebbe866718fea91f432)

A possible solution would be to have another pragma copied to *all* of the modules depending on the module it is defined in. I suppose `HEADER` could be an appropriate name.

The problem is demonstrated by the following example (there's a self-contained set of files in the [tarball](https://github.com/agda/agda/files/818208/foreign.tar.gz)) to be compiled with the command line `agda-XXX --compile --no-main Compiled.agda` (where `XXX` is the corresponding version number: either 2-5-2 or 2-5-3) :

```agda
module Compiled where

-- open import Compiled-252 {- old version: works -}
open import Compiled-253 {- new version: out of scope error for `Compiled.URaw.Z` -}

pred : U → U
pred z     = z
pred (s t) = t
```

```agda
module Compiled-252 where

data U : Set where
  z : U
  s : U → U

{-# IMPORT Compiled.URaw #-}
{-# COMPILED_DATA U Compiled.URaw.U Compiled.URaw.Z Compiled.URaw.S #-}
```

```agda
module Compiled-253 where

data U : Set where
  z : U
  s : U → U

{-# FOREIGN GHC import qualified Compiled.URaw #-}
{-# COMPILE GHC U = data Compiled.URaw.U (Compiled.URaw.Z | Compiled.URaw.S) #-}
```

```haskell
module Compiled.URaw where

data U = Z | S U
```

**Comment by UlfNorell** [comment]
I would really like to avoid inheriting Haskell code from imported modules. Ideally we should reexport (perhaps by aliasing) the things needed from Haskell imports. For functions we already do this, and for compiled types it should be straightforward. I wonder if we could use pattern synonyms for constructors...

**Comment by andreasabel** [comment]
We (Stephan Adelsberger, Anton Setzer) are running into the same problem.  The workaround is really ugly in our case: use `MAlonzo.Code.*` qualified names for the constructors in the `{-# COMPILED GHC #-}` pragma.  

This issue should be fixed before we release the new GHC backend.

In some sense, this is a dynamic/static binding issue.  The interpretation of 
```
{-# COMPILE GHC U = data Compiled.URaw.U (Compiled.URaw.Z | Compiled.URaw.S) #-}
```
is currently dynamic in 2.5.3, i.e., the meaning of say `Compiled.URaw.Z` is determined in the context where constructor `Z` is used.  However, it should be once for all determined here, where the pragma is issued.

**Comment by andreasabel** [comment]
The dynamic binding behavior allows me to smuggle another definition of `U` in a second module without another `COMPILE` pragma.
Module `Compiled-253`:
```agda
module Compiled-253 where

data U : Set where
  z : U
  s : U → U

one : U
one = s z

{-# FOREIGN GHC
data U = Z | S U
#-}
{-# COMPILE GHC U = data U (Z | S) #-}
```
Module `Compiled`:
```agda
module Compiled where

open import Compiled-253

{-# FOREIGN GHC
data U = Z | S Empty
#-}

pred : U → U
pred z     = z
pred (s t) = t

zero : U
zero = pred one
```
Just by adding some Haskell code I silently overwrite the semantics of `U` given in module `Compiled-253`.  This should not be possible.

**Comment by phile314** [comment]
I implemented the pattern synonym approach and it works nicely. However, GHC 7.6 does not support pattern synonyms. Does Agda actually still support GHC 7.6? According to Agda.cabal it does. Anyway, I suggest that the GHC backend will require GHC 7.8 from now on. Any objections?

**Comment by gallais** [comment]
[Debian stable is still on ghc-7.6](https://packages.debian.org/search?keywords=ghc&searchon=names&suite=all&section=all) however the backports do provide 7.8 or newer. No objection from me.

**Comment by asr** [comment]
> Does Agda actually still support GHC 7.6? 

Yes. We discussed about removing support for GHC 7.6 in #1972 one year ago. I'll reopen this issue and remove the support for this version of GHC.

**Comment by phile314** [comment]
To be clear, the GHC 7.8 requirement here only applies to code generated by the GHC backend and not to Agda itself. Personally, I am in favor of dropping GHC 7.6 support for both the GHC backend and Agda itself. Might also be easier to communicate.

**Comment by andreasabel** [comment]
I recently asked about continuing support for ghc-7.6 on the mailing list and a non-empty set of people came forward in favor of keeping 7.6 support.  Thus, I'd like to keep it.

However, I see no problem that the ghc backend requires 7.8.

**Comment by asr** [comment]
> I recently asked about continuing support for ghc-7.6...

No. You asked about the support  for GHC 7.8.

**Comment by andreasabel** [comment]
Indeed, I confused this.

**Comment by gallais** [comment]
We're missing some imports still. Trying to compile:

```agda
module Issue2486 where

open import Agda.Builtin.Nat
open import Data.Maybe.Base

data BufferMode : Set where
  NoBuffering LineBuffering : BufferMode
  BlockBuffering : Maybe Nat → BufferMode

{-# FOREIGN GHC import System.IO #-}
{-# COMPILE GHC BufferMode = data BufferMode (NoBuffering | LineBuffering | BlockBuffering) #-}
```
yields the error:
```
/home/gallais/languages/agda/MAlonzo/Code/Issue2486.hs:22:5: error:
    Not in scope:
      type constructor or class ‘MAlonzo.Code.Data.Maybe.Base.AgdaMaybe’
    No module named ‘MAlonzo.Code.Data.Maybe.Base’ is imported.
```
The `Maybe` type is translated to `AgdaMaybe` via a `FOREIGN GHC` pragma in `Data.Maybe.Base` but because `MAlonzo.Code.Data.Maybe.Base` is not imported in `Issue2486.hs`, that name is out of scope. I suppose we should always `import qualified` a module whenever we are using something from it?

**Comment by phile314** [comment]
The problem is that the coverage check code generated for the ``BlockBuffering`` constructor mentions the ``MAlonzo.Code.Data.Maybe.Base.AgdaMaybe`` type. However, the compiler doesn't generate any import for the ``MAlonzo.Code.Data.Maybe.Base`` module because there is no term-level usage of the imported module in the Agda source code. E.g. adding
```
f : Maybe BufferMode
f = nothing
```
makes that error go away (there is another unrelated problem with int/integer mismatch in the example).

This is definitely an Agda bug.

**Comment by gallais** [comment]
> there is another unrelated problem with int/integer mismatch in the example

Yeah, in the [actual file](https://github.com/gallais/agda-sizedIO/blob/5b3a522aed26e0029af6caab4c5f4ed377d6ce8b/src/Sized/IO/Primitive.agda#L32) I've added some translation back and forth to get around that issue.

**Comment by phile314** [comment]
There are two problems here actually. The first is that we don't generate an import if no term-level values are used. I have fixed this on my branch and this fixes some cases, waiting for travis now.

The other issue is that ``{-# FOREIGN GHC import qualified ... #-}`` pragmas are not propagated. This means if the Haskell type is declared in another Haskell module it breaks down again. Example:
<pre>
MyHsModule.hs (exports MyData)
        /\
        ||
  FOREIGN GHC import qualified
        ||
        ||
MyModule.agda (Foreign Data Wrapper for MyData)
        /\
        ||
  normal Agda Import
        ||
        ||
Issue.agda (Another Foreign Data Decl with MyData field)
</pre>
Issue.agda will have no import for MyHsModule.hs, therefor the Haskell Type ``MyData`` will not be visible in the compiled Issue.hs and will cause compile errors.

A work-around is to define a Haskell type synonym inside MyModule.agda to enforce that the type is re-exported. Better would be if Agda generated a type synonym for each foreign data/type declaration, similar to the pattern synonyms.

**Comment by UlfNorell** [comment]
Can you give a concrete example? If `Issue.agda` is explicitly mentioning `MyData`, wouldn't you expect to have to explicitly import `MyHsModule`?

**Comment by UlfNorell** [comment]
Answering my own question: here's a possible `Issue.agda`:

```agda
open import MyModule

postulate
  myDataId : MyData → MyData

{-# COMPILE GHC myDataId = id #-}
```

This will generate a type signature for the compiled version of `myDataId` referencing the Haskell `MyData`, which is not in scope.

Adding type synonyms for compiled types seems like the right solution.

**Comment by UlfNorell** [comment]
@phile314: I'm adding the type synonyms, which I believe subsumes your change in 7d24b26. Is it ok if I just cherry-pick the additions to the test case from `ghc-imports`?

**Comment by phile314** [comment]
Sure, go ahead :-) You may want to slightly modify the test case though as it doesn't cover the case where type synonyms are really necessary.

**Comment by UlfNorell** [comment]
I'm adding the example I gave above.
