### ISSUE TITLE
Options used for different modules must be consistent with each other, and options used when loading an interface must be consistent with those used when the interface was created

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#2487]
Currently, even in a module marked `{-# OPTIONS --safe #-}`, you may still import (and use!) `primTrustMe` and postulates from other modules.

It wouldn't bother me if you could import modules not marked as --safe provided they still follow the safe rules, but it seems currently imported modules are totally exempt from these rules.

**Comment by gallais** [comment]
~~I guess it's due to the fact [it's the options in the persistent state](https://github.com/agda/agda/blob/master/src/full/Agda/Interaction/Imports.hs#L299) that get used to typecheck submodules. I don't think we want to modify the persistent state but we could grab the status of the `--safe` flag right before the call to `bracket_` and push it back in after the reset.~~

Doesn't seem to work.

**Comment by gallais** [comment]
Minimal test case:

```agda
{-# OPTIONS --safe #-}
module Issue2487 where
open import Issue2487-2
````

```agda
module Issue2487-2 where
postulate A : Set
```

**Comment by nad** [comment]
This is an instance of a more general problem: Agda does not check that options for different modules in the same project are consistent with each other. For instance, one can use `--without-K` in one module, and `--with-K` in another. I suggest that interfaces should contain information about "important" features (various options, use of unsafe features like postulates, and possibly more; perhaps we could even check whether the K rule is used, even when `--without-K` is not active). When modules are imported one can then check that the imported modules and the importing module use these features in a consistent way:
* Modules using `--safe` may only import safe modules.
* Modules using `--without-K` may only import modules that do not use the K rule.
* Other features should also be considered: `--cubical`, perhaps sized types, perhaps something else.

**Comment by nad** [comment]
As noted by @identicalsnowflake (https://github.com/agda/agda/issues/2515#issuecomment-289404113) there is an additional problem: when a `.agdai` file is loaded we don't check that the current options are consistent with those used when the file was created.

**Comment by identicalsnowflake** [comment]
There may be some logic for this already, actually, it just seems to be backwards. For example, you may have a `{-# OPTIONS --safe #-}` module depend on a `{-# OPTIONS --type-in-type #-}` and Agda will not complain; however, if you try to make a `--type-in-type` module depend on a `--safe` module, Agda will forbid it.

**Comment by nad** [comment]
I've added the "false" label, because I assume that one can currently use `--cubical` in one module, `--with-K` in another, and produce an inconsistency by combining the two.

**Comment by nad** [comment]
I guess it makes sense to fix #2783 and #2784 at the same time as (or before) this issue.

**Comment by MatthewDaggitt** [comment]
Given that this doesn't appear to be an immediate priority, an extra `Known Issue` should definitely be added at the bottom of the [Safe Agda documentation](https://agda.readthedocs.io/en/v2.5.3/language/safe-agda.html), saying you currently need to delete all `.agdai` files before running `agda --safe`. As #3029 shows, this is still tripping myself and other people up.

**Comment by jespercockx** [comment]
@fredrikNordvallForsberg do you have time to look into this issue before the release of Agda 2.6.0?

**Comment by fredrikNordvallForsberg** [comment]
@jespercockx Yes, I hope and think so!

**Comment by nad** [comment]
> * Other features should also be considered: `--cubical`, perhaps sized types, perhaps something else.

I have tried to analyse our different options, to see how they should be handled. There are a number of questions below.

Can perhaps be ignored:

* Options related to include paths and libraries: When a module is loaded we already check that none of its dependencies have changed. (This check uses a hash and can perhaps be fooled.) Note that these options cannot be set in pragmas.
* `--verbose`: I hope that this option does not have any effect on the type-checking process (except for possibly slowing it down, or in the worst case triggering internal errors).
* `--show-implicit`, `--show-irrelevant`, `--postfix-projections`, `--no-print-pattern-synonyms`: I think that these options are meant to only affect printing. If they can change the result of some tactic, then they should be moved to the following category.
* `--only-scope-checking`: No interface file is saved, so I guess this option can be ignored.
* `--caching`.

If the following options are changed, then code should be rechecked, but they can presumably be combined in arbitrary ways:

* `--termination-depth`, `--instance-search-depth`, `--inversion-max-depth`, `--no-syntactic-equality`, `--double-check`, `--no-auto-inline`, `--no-fast-reduce`: I would guess that it is consistent to use different settings in different files.
* `--exact-split`: When this option is active some definitions are disallowed. I don't think anyone relies on this option for the consistency of their development.
* `--no-eta-equality`: Just a default.
* `--no-unicode`: I suspect that this option can affect the output of tactics (via `Agda.Builtin.Reflection.freshName`).
* `--warning`.

Unsafe options (excluding sized types):

* `--allow-unsolved-metas`.
* `--no-positivity-check`.
* `--no-termination-check`.
* `--type-in-type`.
* `--omega-in-omega`.
* `--irrelevant-projections`.
* `--experimental-irrelevance`.
* `--rewriting`.
* `--injective-type-constructors`.

Other options that (possibly) affect what options should be used in other modules (an "infective" option is one that, if used in one module, must be used in all other modules that depend on this module):

* `--safe`: If this option is used, then all modules it depends on must also use `--safe`.
* `--with-K`: Infective, incompatible with `--cubical`.
* `--cubical`: Infective, implies `--without-K`, incompatible with `--with-K`.
* `--universe-polymorphism`: Presumably infective.
* `--sized-types`: Presumably infective. Note also that we will perhaps later disallow the combination of sized types and some or all kinds of constructor-based (co)recursion.
* `--prop`, `--no-forcing`, `--overlapping-instances`: Are these options (or their opposites, like the non-existent option `--forcing`) infective? Are these options compatible with all the others?
* `--copatterns`: Do definitions that use copatterns work in modules that use `--no-copatterns`? If not, then `--copatterns` should be infective. I guess `--copatterns` is incompatible with `--no-pattern-matching`.
* `--no-pattern-matching`: Do definitions that use pattern matching work in modules that use `--no-pattern-matching`? If not, then the *absence* of `--no-pattern-matching` should be infective.
* `--type-in-type`, `--omega-in-omega`, `--irrelevant-projections`, `--experimental-irrelevance`, `--rewriting`, `--injective-type-constructors`: Should these unsafe options be infective? They are already unsafe, but perhaps bad combinations of these options could lead to broken internal invariants, or something like that.

**Comment by jespercockx** [comment]
Any update on this issue? Since several issues with sized types will (very likely) not be fixed before the release, we should make `--sized-types` incompatible with `--safe`.

**Comment by fredrikNordvallForsberg** [comment]
Working on it now, in fact... I can also make `--sized-types` unsafe, or go ahead and do it now, if you want.

**Comment by nad** [comment]
> [...] we should make `--sized-types` incompatible with `--safe`.

In that case I think sized types should, by default, be turned off. Note that we have also discussed hiding the old guardedness machinery under a flag (https://github.com/agda/agda/issues/1209#issuecomment-361265001).

**Comment by nad** [comment]
However, I am not so keen on classifying sized types as unsafe. I have a fair amount of code that uses sized types and is marked as `--safe`, and first updating this code to work with 2.6.0, and then updating it again once we (hopefully) make sized types safe, sounds like a waste of time to me. Perhaps others are in a similar situation.

**Comment by jespercockx** [comment]
I don't think we should allow a feature under `--safe` in a released version of Agda if it leads to a **known** proof of false.

**Comment by nad** [comment]
It seems as if `--no-sized-types` is broken: #3451.

**Comment by fredrikNordvallForsberg** [comment]
**Edit**: I misread the importer/importee in the definition of infective. This makes us agree a lot more.

I'm close to finishing this, but there are some points to consider:
* ~~Making `--cubical` infective means that modules using it cannot import the `Agda.Builtin` modules (they cannot be declared `--cubical`, because then `--with-K` modules couldn't safely import them, as that would violate the "don't combine `--cubical` and `--with-K`" rule). Hence I think `--cubical` shouldn't be infective, but it implies `--without-K`, which should be. I don't see any problem with a cubical module importing a non-cubical without-K module (this is similar to a with-K module importing a without-K one).~~
* ~~In the same way, since `--universe-polymorphism` is an extension of `--no-universe-polymorphism`, shouldn't we rather make the latter infective?~~
* ~~Same again for `--sized-types` vs `--no-sized-types`: I think `--no-sized-types` should be infective. This should also enable the fix of #3451 as @nad suggested there: if `--no-sized-types` is infective, then no module using it will have access to the size builtins, as they would have to be declared in a `--sized-types` module, which wouldn't be importable from a `--no-sized-types` one.~~
* In #2790, @Saizan argues that `--cubical` and `--with-K` should be allowed together, as long as `--safe` is off. I'm happy to hide this check under a `--safe` flag, but we should decide one way or another.

> * `--copatterns`: Do definitions that use copatterns work in modules that use `--no-copatterns`? [...]
> * `--no-pattern-matching`: Do definitions that use pattern matching work in modules that use `--no-pattern-matching`? [...]

Both of these work, so I don't think we should make `--copatterns` or the absence of `--no-pattern-matching` infective.

**Comment by jespercockx** [comment]
> In #2790, @Saizan argues that --cubical and --with-K should be allowed together, as long as --safe is off. I'm happy to hide this check under a --safe flag, but we should decide one way or another.

The most important thing is that `--cubical` implies `--without-K` by default, as some cubical primitives are incompatible with `K`. If it's not too hard to change the default value of `--without-K` when `--cubical` is enabled while still allowing the user to provide `--with-K` explicitly, then we could allow that too, although I don't think it's very important. 

>Both of these work, so I don't think we should make --copatterns or the absence of --no-pattern-matching infective.

I agree, I don't think making them infective makes much sense.

**Comment by nad** [comment]
Elsewhere (#1209) I wrote the following:

> Note also that `--sized-types` and `--guardedness` will presumably both become infective (#2487).

Would this be too annoying? An alternative might be to keep track of which of these options have been used, and disallow `--safe` if both options have been used (even if not in the same module).

Note, however, that one possible fix for #3451 involves making `--sized-types` infective.

**Comment by nad** [comment]
I've pushed `--guardedness`, which should not be allowed at the same time as `--sized-types` if `--safe` is active.

**Comment by nad** [comment]
Consider the following scenario:
* Constructor-based guarded corecursion is used locally in one module.
* Lots of other modules that do not use any corecursion depend on this module. If we make `--guardedness` infective, then all these other modules have to activate `--guardedness`.

Similar considerations apply to other infective options.

Is this too awkward? An alternative might be to infer options in some way. However, I think this sounds worse:
* It might not be entirely clear what language is used.
* Small changes to the code might lead to, say, the K rule being inadvertently activated in a library module.
* The inference procedure might be expensive or complicated. For instance, the rules for termination checking are different depending on whether the K rule is active or not, and the constraints imposed on the target universes of inductive families are different.

**Comment by nad** [comment]
If `--sized-types` and `--guardedness` are both infective, as well as incompatible under `--safe`, then I think it makes sense to by default turn off both in safe mode, also after `--sized-types` has been made safe (if this ever happens). The alternative is to explicitly turn off sized types in safe modules that are intended to be usable by code using either kind of corecursion.

**Comment by Saizan** [comment]
@nad having `--guardedness` off by default is very confusing, as you just get a termination error for code that used to work fine, with no indication that you need a flag now.
Also if you have a coinductive record without sizes, `--guardedness` on is really the only way you can use it.

**Comment by jespercockx** [comment]
I agree with turning off both `--guardedness` and `--sized-types` by default when `--safe` is enabled (`--guardedness` should still be enabled by default if there's no `--safe`). This will essentially prevent users from writing any interesting coinductive code under `{-# OPTIONS --safe #-}`, which is good because it forces them to make a conscious decision between `--guardedness` or `--sized-types`.

**Comment by nad** [comment]
The standard library has recently embraced sized types, and I think the modules that use musical coinduction are seen as legacy code. If Agda at the same time makes old-style guarded corecursion the default, then we are sending a mixed message.

I think we should plan carefully, so that we do not needlessly break users' code. One option might be to enable both sized types and `--guardedness` by default (in "unsafe" mode) in the upcoming release. Another option might be to delay all of these changes to the next release, so that they can be evaluated thoroughly. Breaking lots of existing code is perhaps worse than shipping known inconsistencies.

**Comment by Saizan** [comment]
@nad --guardedness off also disables termination for defininitions by copatterns in general, not just musical notation. I don't think we necessarily what to phase those out.

Having both --guardedness and --sized-types on without --safe is a good default.

I wouldn't mind delaying these changes.

**Comment by nad** [comment]
> I don't think we necessarily what to phase those out.

No, the question is what the default should be.

**Comment by Saizan** [comment]
I should rephrase: I believe we want them allowed by default, as well as definitions that rely on sized types to termination check. Putting either behind a flag means discouraging their use to me.

`--guardedness` and `--sized-types` do not have to be inconsistent with each other, as opposed to e.g. univalence and `--with-K`. We want to eventually fix the bugs that make them so.

**Comment by nad** [comment]
> `--guardedness` and `--sized-types` do not have to be inconsistent with each other, as opposed to e.g. univalence and `--with-K`. We want to eventually fix the bugs that make them so.

@fredrikNordvallForsberg stated that his current implementation activates both when `--safe` is not used, but deactivates both when `--safe` is used. Does this sound reasonable to you?

Apparently the implementation also allows `--safe --sized-types`.

**Comment by Saizan** [comment]
@nad that sounds reasonable, yes.

**Comment by nad** [comment]
Thanks!
