### ISSUE TITLE
Where clauses in functions leak instances to global instance search

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#2489]
```agda
data ⊤ : Set where
  t : ⊤

data ⊤⊤ : Set where
  tt : ⊤⊤

module M (x : ⊤⊤) where

  instance
    top : ⊤
    top = t


search : ∀ {ℓ} {t : Set ℓ} {{_ : t}} → t
search {{p}} = p

-- no instance is in scope, and none is found
-- correct : ⊤
-- correct = search


someDef : ⊤
someDef = top
  where
    open M tt

-- incorrect! there should be no instance available.
leak : ⊤
leak = search
```

You can see above, the `search` in `leak` somehow finds the `top` instance even though it's not in scope -- which can be confirmed by trying to manually apply `leak = search {{top}}` which Agda does correctly reject on the grounds that `top` is not in scope.

This is bad because it causes unwanted instance collisions in global scope which would not otherwise occur.

**Comment by andreasabel** [comment]
Well, what is actually happening is that first, only this instance is in scope:
```
M.top : TT -> T
```
Instance search `correct` fails since the `TT` argument is not an instance argument, and there is no instance for `TT` anyway.
Then, the `open` adds another instance
```
_.top : T
```
which is subsequently found by instance search `leak`.
If you let `someDef` take an argument, like in
```agda

someDef : ⊤⊤ → ⊤
someDef _ = top where open M tt
```
then instance search `leak` fails as well.

But of course, you are right, in principle `open`ing a module in a `where` block should not bring anything into scope.

**Comment by UlfNorell** [comment]
Currently instance scope is only restricted at file boundaries, so instances from the current module are considered even if they are not in scope. See #1265 and #1913 for some discussion.

In general I would consider local instances to be bad practice, but that's just because of problems like this one.

**Comment by andreasabel** [comment]
Maybe the error message deserves a face-lift:
```agda
No instance of type ⊤ was found in scope.
when checking that the expression search has type ⊤
```
It could be part of the present confusion.
This is still the original error message from the Devriese implicits.  We have long departed from that.

**Comment by identicalsnowflake** [comment]
@UlfNorell After working with this some more, I see what you mean: even putting an instance in a module and never opening that module allows it to be found, despite other terms in the module not being in scope.

It would be nice if instance search respected regular scoping semantics, because from early experiments, it looks like these instance fields have a lot of potential.

**Comment by nad** [comment]
@identicalsnowflake, would you be satisfied if #1913 was fixed?

**Comment by identicalsnowflake** [comment]
@nad Well in #1913 there's also the fact that it's explicitly declared `private`. For `private`, it should only be accessible from within that `M` module.

But in this issue, I'm also interested in clarifying how instance declarations respect module boundaries in general. Behavior like this:

```agda
search : ∀ {ℓ} {t : Set ℓ} {{_ : t}} → t
search {{p}} = p

module M where
  instance
    i : Whatever

_ : Whatever
_ = search -- should fail

module _ where
  instance
    _ : Whatever
    _ = M.i
  
  _ : Whatever
  _ = search -- should succeed

_ : Whatever
_ = search -- should fail

open M

_ : Whatever
_ = search -- should succeed

```
In my mind, the declaration of `i` *as an instance* is inside of `M`, so even though you may write `M.i` to manually access this term, instance search should not find this unless you do `open M`.

For what it's worth, I imagine local `rewrite` pragmas behaving similarly.

EDIT: fixed code

**Comment by andreasabel** [comment]
> Well in #1913 there's also the fact that it's explicitly declared private. For private, it should only be accessible from within that M module.

Note that declarations in `where` blocks are private.

**Comment by identicalsnowflake** [comment]
@andreasabel it would help, but I can still get this same issue even without function where blocks:

```agda
data Red : Set where
  red : Red

data Blue : Set where
  blue : Blue

record Exists (t : Set) : Set where
  field
    exists : t

module Weaken {t₁ t₂ : Set} (f : t₁ → t₂) where

  instance
    exi : ∀ {{_ : Exists t₁}} → Exists t₂
    exi {{i}} = record { exists = f (Exists.exists i) }

module M where

  btr : Blue → Red
  btr blue = red

  open Weaken btr

  instance
    iblue : Exists Blue
    iblue = record { exists = blue }

  _ : Exists Red
  _ = search -- correct


_ : Exists Red
_ = search -- incorrect
```

This has the same issue as function where clauses with leaking local reasoning into global scope.
