### ISSUE TITLE
Record parameter not printed in field-derived goal type

### ISSUE THREAD

**Issue by mjustus** [agda/agda#2491]
The goal type in the following snippet is pretty-printed as `explicit _ r` rather than `explicit X r`.

```Agda
record R (X : Set) : Set₁ where
  field
    f : Set

explicit : ∀ X → R X → Set
explicit X = R.f

test : ∀ X (r : R X) → explicit X r
test X r = ?
```

**Comment by andreasabel** [comment]
Since `explicit` is a projection-like function, its argument is treated as a parameter and dropped.  The printer is not type-directed, thus, cannot reconstruct the parameter, and simply prints an underscore.
