### ISSUE TITLE
Limit the size of terms agsy is allowed to insert

### ISSUE THREAD

**Issue by gallais** [agda/agda#2492]
I was using the following `Singleton` datatype for tests and by force of habit made the mistake of calling agsy on the hole for the singleton corresponding to a large natural number. Needless to say, I had to prompty kill emacs. And clean up my file now mostly filled with `suc`(k)s.

I'd argue that any term with depth > 10 is probably not worth printing. A principled solution would be to make it possible to override this default by passing an option in the goal as is already the case for e.g. allowing it to do case-splitting.

```agda
open import Agda.Builtin.Nat

data Singleton {A : Set} : A → Set where
  _! : (a : A) → Singleton a

_ : Singleton 1005
_ = ? -- don't call agsy here
```

**Comment by andreasabel** [comment]
In this particular case, printing the solution as `1005 !` would probably not have raised your anger.

**Comment by gallais** [comment]
Yes, I was tempted to open another issue at the same time suggesting to pretty print literals (which I guess only means Nat at the moment).

**Comment by andreasabel** [comment]
Thanks!  
Out of curiosity: why did you place the NATURAL-folding in AbstractToConcrete rather than InternalToAbstract?

**Comment by gallais** [comment]
As far as I can tell Auto is working on Abstract terms: https://github.com/agda/agda/blob/master/src/full/Agda/Auto/Auto.hs#L325

**Comment by andreasabel** [comment]
Ah, good.

**Comment by andreasabel** [comment]
Works fine in Mimer.
