### ISSUE TITLE
Instance fields sometimes have incorrect goal types

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#2494]
```agda
record Type₁ : Set where

record Type₂ : Set where

record Aggregator : Set where
  field
    {{i₁}} : Type₁
    {{i₂}} : Type₂

postulate
  instance
    type₁ : Type₁
    type₂ : Type₂

agg : Aggregator
agg = record {
    i₂ = {!!} -- goal: Type₁
  }

```

Loading the above, Agda incorrectly states a goal of `Type₁` for solving `i₂`. It will also accept `type₁` as a valid solution if you provide it for this hole, even though the `i₂` field has type `Type₂`.

**Comment by identicalsnowflake** [comment]
I just noticed that this also occurs for pattern matching (probably the same root cause):

```agda
postulate
  Red Blue : Set

record Colors : Set where
  field
    {{red}} : Red
    {{blue}} : Blue

f : Colors → Red
f record { blue = blue } = blue
```

**Comment by andreasabel** [comment]
It seems that `insertImplicitPatternsT` inserts the instance argument in the wrong position.
```
insertImplicitPatternsT
  ps  =  [{{blue}}]
  tel =  {{red : Red}} {{blue : Blue}}
  b   =  Prop
insertImplicitPatternsT
  ps  =  []
  tel =  {{blue : Blue}}
  b   =  Prop
insertImplicitPatternsT returned {{blue}} {{_}}
```
That should be `{{_}} {{blue}}`.

**Comment by andreasabel** [comment]
I get the same problem with just hidden arguments:
```agda
record Colors : Set where
  field
    {red}  : Red
    {blue} : Blue

f : Colors → Red
f record { blue = blue } = blue
```
Should not type-check.

**Comment by andreasabel** [comment]
I think this is because when translating records to constructor applications, we do not use the `Named` info, thus, `{{blue : _}}` passes for `{{red : _}}`.  (Here the names are just variable names, not argument names.)

**Comment by andreasabel** [comment]
Bingo!
