### ISSUE TITLE
ghcversion.h setup problem?

### ISSUE THREAD

**Issue by WolframKahl** [agda/agda#2496]
With current master and stable-2.5 branches, with a fresh GSC-8.0.2 install in `/usr/local/packages/Agda` from a locally produced binary distribution, running `./Setup build` starts with a large number of messages of the following shape:
````
Warning: Can't find file "/usr/local/packages/Agda/lib/ghc-8.0.2/include/ghcversion.h" in directories

  Asked for by: src/full/Agda/Utils/Parser/MemoisedCPS.hs  at line 2 col 1
````
The file `/usr/local/packages/Agda/lib/ghc-8.0.2/include/ghcversion.h` exists and is readable.
I've never seen these messages before...

**Comment by nad** [comment]
I'm using GHC 8.0.2, and I haven't seen this kind of message. However, I don't use `Setup.hs` directly. What happens if you use cabal-install instead?

**Comment by asr** [comment]
I couldn't understand your current set up.

>... from a locally produced binary distribution

Are you talking about of a locally produced binary distribution of GHC or Agda?

>... running `./Setup build`

How did you produce the `Setup` executable?

>````
>Warning: Can't find file "/usr/local/packages/Agda/lib/ghc-8.0.2/include/ghcversion.h" in directories
> ````

 I have seen this kind of errors related to CPP. Which is your `cpphs` version?

**Comment by WolframKahl** [comment]
On Mon, Mar 13, 2017 at 04:49:35AM -0700, Andrés Sicard-Ramírez wrote:
> I couldn't understand your current set up.
> 
> >... from a locally produced binary distribution
> 
> Are you talking about of a locally produced binary distribution of GHC or Agda?

I locally created a binary distribution of GHC-8.0.2 from the GHC source,
and then used that to produce a dedicated GHC installation
for this copy of Agda.
(It is now populated with all dependencies of Agda.)


> >... running `./Setup build`
> 
> How did you produce the `Setup` executable?

ghc --make -O Setup

> 
> >````
> >Warning: Can't find file "/usr/local/packages/Agda/lib/ghc-8.0.2/include/ghcversion.h" in directories
> 
>  ````
> 
>  I have seen this kind of errors related to CPP. Which is your `cpphs` version?

cpphs 1.20.4


I am normally building in a shadow directory set up using lndir,
and remembered that that was a problem for a different project's
attempts to get git information into their version string,
but this is not the problem here --- I get the same messages
when calling `./Setup build` directly in the `git clone`d directory.

**Comment by asr** [comment]
Can you build Agda replacing cpphs by cpp?

**Comment by WolframKahl** [comment]
I haven't tried yet. These are only warning messages, and agda built fine and appears to work as expected for typechecking. (I haven't tried compiling yet.)

**Comment by asr** [comment]
> cpphs 1.20.4

I just realised you are using cpphs 1.20.4. I could reproduce the problem using this version of cpphs and `make install-bin`.

**Comment by asr** [comment]
Blocked by https://github.com/malcolmwallace/cpphs/issues/11.

**Comment by asr** [comment]
Closed because https://github.com/agda/agda/issues/2539#issuecomment-293287951.
