### ISSUE TITLE
Macros don't play nicely with abstract

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#2502]
```agda
open import Agda.Builtin.Reflection
open import Agda.Builtin.Unit

abstract
  data ⊤⊤ : Set where
    ttt : ⊤⊤

  macro
    m : Type → TC ⊤
    m ty = bindTC (quoteTC ttt) (unify ty)

_ : ⊤⊤
_ = m
```

Trying to load the above, Agda says `Cannot unquote non-canonical type checking computation`.

How macros in general should treat/respect abstract data types is probably a hard question -- but given that this macro is actually located in the same abstract block definition, I think it should have full access.

**Comment by jespercockx** [comment]
OTOH, you're *running* the (abstract) macro outside of the abstract block, so maybe the current behaviour is as expected.

**Comment by nad** [comment]
The code is accepted if the final definition is moved inside the abstract block.
