### ISSUE TITLE
Propose: Split the changelog

### ISSUE THREAD

**Issue by asr** [agda/agda#2512]
Finding in which version of Agda was introduced a change is getting tedious because the size of the changelog is incrementing. I propose to split the changelog by Agda version, that is,

```
doc/release-notes/2.5.3.md
doc/release-notes/2.5.2.md
doc/release-notes/2.5.1.2.md
...
```

Cons: It'll be necessary grepping various files when looking for a change.

**Comment by andreasabel** [comment]
Does this harmonize with hackage?

**Comment by UlfNorell** [comment]
We could generate the current `CHANGELOG` at release time by concatenating the split changelogs and include that in the hackage bundle.

**Comment by asr** [comment]
> Does this harmonize with hackage?

Yes. In Hackage for version X.Y.Z we could show only the changelog for this version.

> We could generate the current `CHANGELOG` at release time by concatenating the split changelogs and include that in the hackage bundle.

Instead of concatenating the split changelogs, we could add them to the tarball.

**Comment by andreasabel** [comment]
I am fine with experimenting different ways to manage the CHANGELOG.  We should follow the conventions, otherwise I am neutral.

**Comment by nad** [comment]
I think most changelogs that are displayed on Hackage contain changes for multiple versions of the corresponding package.

**Comment by asr** [comment]
@ice1000 [wrote](https://github.com/agda/agda/issues/4212#issuecomment-565741888):

> The CHANGELOG.md is way too big. I think it's good to split it (version-per-file or some-versions-per-file or something)

I still think we should follow the approach in the OP.

**Comment by asr** [comment]
> Does this harmonize with hackage?

The size of Agda's CHANGELOG does not "harmonize" with Hackage. Below I list the 20 biggest changelogs files in Hackage from 14395 packages.

```bash
$ find -type f -iname changes -or -iname changes.* -or -iname changelog -or -iname changelog.* -exec du -h {} + | sort -r -h | head -n 20

712K	./pandoc-2.9/changelog.md
372K	./Agda-2.6.0.1/CHANGELOG.md
84K	./dhall-1.28.0/CHANGELOG.md
64K	./diagrams-lib-1.4.3/CHANGELOG.md
56K	./idris-1.3.2/CHANGELOG.md
52K	./lens-4.18.1/CHANGELOG.markdown
48K	./reload-0.0.0.1/web/bower_components/mocha/CHANGELOG.md
48K	./matterhorn-50200.5.0/CHANGELOG.md
48K	./Cabal-3.0.0.0/ChangeLog.md
40K	./megaparsec-8.0.0/CHANGELOG.md
40K	./dejafu-2.1.0.1/CHANGELOG.rst
36K	./husk-scheme-3.19.3/ChangeLog.markdown
36K	./graphviz-2999.20.0.3/Changelog.md
36K	./c2hs-0.28.6/ChangeLog.old
36K	./brick-0.50.1/CHANGELOG.md
36K	./amazonka-1.6.1/CHANGELOG.md
32K	./LambdaHack-0.9.5.0/CHANGELOG.md
32K	./diagrams-core-1.4.2/CHANGELOG.md
32K	./clash-ghc-1.0.1/CHANGELOG.md
28K	./xmobar-0.32/changelog.md
```

As you can see we are in the second place.

> I think most changelogs that are displayed on Hackage contain changes for multiple versions of the corresponding package.

We can easily see the changes for every released version of a package in Hackage. Keeping changes for multiple versions is not necessary.

I'll split the CHANGELOG following the OP. I'll wait for objections a couple of days.

**Comment by asr** [comment]
Starting...
