### ISSUE TITLE
Performance regression (apparent non-termination) before 2.5.2

### ISSUE THREAD

**Issue by WolframKahl** [agda/agda#2516]
Originally reported under #2495:

> I also have a module (on top of a large development) that typechecked with 2.5.1 and 7c5f712aac3afefeb0a05329592b263437a40b98 in at most a few minutes, but fails to typecheck in days with 2.5.2 and current stable. (However, it typechecks quickly with @Saizan 's patch from #1625 .)

Thanks @nad for the help with setting up `agda-bisect`! There were actually two language changes (at 1432ff46aa53fd3981c2acbfb83a04d411450ce8 and 43f945ee660ddf2ccaf2435ea2d14e0bb4caada2) in the range before the relevant commit, but they affected only one place each in my code.

The module in question pulls in 248 other modules as dependencies,  including 77 from the standard library, all together typechecked in about 17 minutes. The module in question typechecks in 81 to 69 seconds at the beginning of the range; the last one with the following `-v profile:7` output:
````
  Total                        70,377ms           
  Miscellaneous                   190ms           
  Parsing                           4ms      (7ms)
  Parsing.Operators                 3ms           
  Import                           92ms           
  Deserialization              44,232ms           
  Scoping                           3ms      (3ms)
  Scoping.InverseScopeLookup        0ms           
  Typing                          115ms (25,374ms)
  Typing.With                       0ms           
  Typing.OccursCheck                0ms           
  Typing.CheckLHS                   1ms           
  Typing.CheckRHS              25,247ms           
  Typing.TypeSig                   11ms           
  Termination                       0ms      (0ms)
  Termination.RecCheck              0ms           
  Positivity                        0ms           
  Injectivity                       0ms           
  ProjectionLikeness                0ms           
  Coverage                          0ms           
  Highlighting                     38ms           
  Serialization                   299ms    (433ms)
  Serialization.BuildInterface      1ms           
  Serialization.Sort               11ms           
  Serialization.BinaryEncode      109ms           
  Serialization.Compress           13ms           
  DeadCode                          3ms           
  ModuleName                        5ms         
    55,642,285,576 bytes allocated in the heap
     5,693,755,648 bytes copied during GC
     2,576,079,000 bytes maximum residency (3 sample(s))
        73,549,808 bytes maximum slop
             10342 MB total memory in use (0 MB lost due to fragmentation)
  
                                       Tot time (elapsed)  Avg pause  Max pause
    Gen  0         7 colls,     0 par    7.346s   7.344s     1.0492s    5.1219s
    Gen  1         3 colls,     0 par   10.710s  10.707s     3.5690s    5.5311s
  
    INIT    time    0.012s  (  0.012s elapsed)
    MUT     time   52.322s  ( 52.332s elapsed)
    GC      time   18.056s  ( 18.051s elapsed)
    EXIT    time    0.048s  (  0.048s elapsed)
    Total   time   70.439s  ( 70.442s elapsed)
  
    %GC     time      25.6%  (25.6% elapsed)
  
    Alloc rate    1,063,458,090 bytes per MUT second
  
    Productivity  74.4% of total user, 74.3% of total elapsed
    
````
Then it fails to check in 10 minutes starting from 6c6d358bc0d5c5d09a79594bb810fba4e2a057f7 :
````
6c6d358bc0d5c5d09a79594bb810fba4e2a057f7 is the first bad commit
commit 6c6d358bc0d5c5d09a79594bb810fba4e2a057f7
Author: Jesper Cockx <jesper.cockx@cs.kuleuven.be>
Date:   Fri Nov 4 18:23:43 2016 +0100

    [ fixed #2059 ] Don't treat absurd matches as UnusedArg

:040000 040000 d8ae24f44d2e155a1b8c7beebe557e2c3159b16c 3d79a913ac861c9ed8e8060f07689f08302e74d4 M	src
:040000 040000 9758d0ebf59f23164f4ccad1881f728de28f7077 6b5e7a4d59d1e66ed9b4b8eb42d1ba103511ebb2 M	test
````
(The non-termination “feels” similar to those reported in #1625: Tons of generation-0 garbage collections without significant increase in “Live bytes”.)

**Comment by andreasabel** [comment]
Just yesterday I pushed the fix of #2495 which should improve performance for all big developments, the performance regression introduced by #2403.  Are your results from before or after my fix?

UPDATE: Aeh, sorry, I did not read the heading.  As the performance regression was introduced for 2.5.2 it has nothing to do with #2495.

**Comment by WolframKahl** [comment]
In `stable-2.5` at 802a28aa8374f15fe9d011ceb80317fdb1ec0949 , the effect is still there.

(Testing with `master` would be more complicated.)

**Comment by WolframKahl** [comment]
The only change made by 6c6d358bc0d5c5d09a79594bb810fba4e2a057f7 is to weaken the predicate `properlyMatching`, which is called only in three places:

- `Pos`: `src/full/Agda/TypeChecking/Positivity.hs`

- `Pol`: `src/full/Agda/TypeChecking/Polarity.hs`, line 249 at 6c6d358bc0d5c5d09a79594bb810fba4e2a057f7

- `Inj`: `src/full/Agda/TypeChecking/Injectivity.hs`

I added a copy `properlyMatching'` with the old definition, and tried replacing calls to the current definition with calls to `properlyMatching'` for all non-empty strict subsets of `{Pos, Pol, Inj}`:

- Only `{Pos, Pol}` finishes my module

- `{Pos}` and `{Pos, Inj}` trigger the `__IMPOSSIBLE__` at `Polarity.hs:249` on `Data.Empty`

- All other sets still exhibit the apparent non-termination.

(My module is tiny (two definitions) and has no absurd patterns; the modules it calls have plenty.)

This situation is unchanged in stable-2.5 at  802a28aa8374f15fe9d011ceb80317fdb1ec0949;  `{Pos, Pol}` also finishes my module. Patch attached.

[Issue2516_Pos_Pol.patch.txt](https://github.com/agda/agda/files/882587/Issue2516_Pos_Pol.patch.txt)

**Comment by andreasabel** [comment]
Mmh, but turning an absurd pattern into a proper match in the positivity checker was a deliberate design decision.  You patch reverts this (if I understood it correctly).
I can see though how treating less arguments as 'NonVariant' would increase the tasks of the conversion checker, possibly to a point where it runs too long. @jespercockx?

**Comment by WolframKahl** [comment]
On Thu, Mar 30, 2017 at 11:37:53AM -0700, Andreas Abel wrote:
> Mmh, but turning an absurd pattern into a proper match in the positivity checker was a deliberate design decision.  You patch reverts this (if I understood it correctly).
> I can see though how treating less arguments as 'NonVariant' would increase the tasks of the conversion checker, possibly to a point where it runs too long.

At one point, I left it running for three days...

If you can see how this increases the tasks of the conversion checker,
can you perhaps also see how to eliminate superfluous tasks?
Or how to integrate @Saizan's patch from #1625 in a safe way?

**Comment by WolframKahl** [comment]
It appears that the commit 6c6d358bc0d5c5d09a79594bb810fba4e2a057f7 that is making trouble for me here is motivated by a desire to improve the situation for some unsafe extension, as reported in #2059. If it should really only be serving that purpose, then I would strongly argue that this should be hidden behind the flag enabling those unsafe features, so that it does not impact safe modules.

**Comment by jespercockx** [comment]
My commit was motivated by a bug in the rewriting mechanism (the unsafe extension you mention), but it doesn't have to do anything to do with rewriting in itself. It is a change to a rather basic assumption to Agda's notion of definitional equality. Consider the NonvariantPolarity example:
```
  abort : (A : Set) → ⊥ → A
  abort A ()

  test : (x y : ⊥) → abort Bool x ≡ abort Bool y
  test x y = refl  
```
Isn't it strange that `abort Bool x` would be definitionally equal to `abort Bool y` even though they are different normal forms? At least I do not know of a published type theory that includes such a rule. 

If you really don't want the arguments to `abort` to be compared (for reasons of performance or others), you can always make the argument of type `⊥` irrelevant. Maybe we could even have a flag that does this automatically for all types that can be seen to be empty?

**Comment by WolframKahl** [comment]
> Isn't it strange that `abort Bool x` would be definitionally equal to `abort Bool y` 

only under the assumption `x y : ⊥`!

Since I consider that assumption as rather unrealistic, I have no trouble with any conclusion you draw from it...

**Comment by WolframKahl** [comment]
> If you really don't want the arguments to `abort` to be compared [...], you can always make the argument of type `⊥` irrelevant. 

Another unsafe extension that I'm avoiding. And I don't even know which absurd patterns I'd have to make of irrelevant type: The module in question only has single variables as patterns.

**Comment by jespercockx** [comment]
But this is about definitional equality, so we should care about it even with absurd assumptions in the context! For example, if we could deduce a definitional equality between the unit type and the empty type (I'm not saying we can here, but if) then we break subject reduction.

What I'm really arguing here is that the feature I removed in my patch *is* something potentially unsafe as well, so if we really want it, it should be hidden behind a flag. 

In fact, there is still an open proof of false (#2480) that makes use of the same `UnusedArg` machinery that's at play here as well. So I'm not just talking theoretical problems here. We should really rework/replace the whole `UnusedArg` machinery with something better. The problem is that we don't know yet what that `something better' is...

**Comment by jespercockx** [comment]
> Another unsafe extension that I'm avoiding.

I think irrelevance is actually one of the safer and well-understood features of Agda (at least as long as you don't enable `--experimental-irrelevance` I suppose). Of course I neither can nor want to tell you how to write your code, but for me it really helps a lot to make proofs easier as well as typechecking much faster in many cases.

**Comment by WolframKahl** [comment]
> even though they are different normal forms?

Is it really necessary to consider these as “normal forms”? Anything that ends up being covered by a rule with an absurd pattern has already been proven to be something that “never needs to be reduced”, so asking whether it can be reduced (that is, whether it is a normal form) does not make sense.

**Comment by WolframKahl** [comment]
(Irrelevance (and `abstract`) used in the source for speeding up typechecking raise “premature optimisation” warning flags for me ─ they _should_ not be needed for that purpose.)

**Comment by UlfNorell** [comment]
> At least I do not know of a published type theory that includes such a rule.

There's [Scherer, 2016, Deciding equivalence with sums and the empty type](https://arxiv.org/pdf/1610.01213.pdf), which proves decidability of βη-equality in a simply typed system with η for the empty type.

**Comment by jespercockx** [comment]
We should decide what to do here before the next release. I stand by my point that the current implementation is doing the right thing and that there is a reasonable workaround (using irrelevance), so we should simply close this issue.

**Comment by andreasabel** [comment]
At the moment, there is no clear direction what can be done about this performance problem.  In any case, we cannot revert the fixes that lead to the performance degradation, since they are required to make Agda consistent.
