### ISSUE TITLE
"Not a variable error"

### ISSUE THREAD

**Issue by xekoukou** [agda/agda#2517]
Possibly related to #2183 #2181 
When I try to case split on rll : 
```findCallGraph {ll = ll} {rll = rll} {olf = olf} (call x) if msr ms = {!!} ```

I get this:

```
/mnt/Workspace/sparrow/agda/IndexLF.agda:306,70-74
Not a variable: rll
when checking that the expression ? has type
MSetLFCRem olf (call .∞rll) × MSetLFC olf olf
```

This works fine : 
```
findCallGraph {ll = ll} {rll = call .∞rll} {olf = olf} (call {∞rll = ∞rll} x) if msr ms = {!!} 
```
Commit to reproduce error:
https://github.com/xekoukou/sparrow/blob/74de191538e421fd0a62f67344c5e83fd18f7612/agda/IndexLF.agda#L306

The error message should be improved. Certainly ```rll``` is a variable.

**Comment by andreasabel** [comment]
Confirmed that is is #2183.  
For now, I am just improving the error message.

**Comment by andreasabel** [comment]
Closing, as this is a duplicate of #2183.
