### ISSUE TITLE
CopatternReductions in TreeLess

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2518]
@UlfNorell @phile314 In `ToTreeless` I read
```haskell
casetree :: CC.CompiledClauses -> CC C.TTerm
...
    CC.Done xs v -> withContextSize (length xs) $ do
      -- Issue 2469: Body context size (`length xs`) may be smaller than current context size
      -- if some arguments are not used in the body.
      v <- lift (putAllowedReductions [ProjectionReductions, CopatternReductions] $ normalise v)
      substTerm v
```
This allows arbitrary reductions as long as the involved functions make use of copattern matching.  How is that not too blow up on complex examples?  There seems to be some assumption that definition by copattern matching are "simpler" that those without.  Maybe this is true for the limited examples you have in the test suite, but I can see no evidence that this could be the case in general.

Anyhow, during my work on #2495 I limited CopatternReductions to non-recursive functions.  Maybe this is more what you had in mind.

Please review your code and decide whether you are happy with the new semantics.

**Comment by UlfNorell** [comment]
I added that in 99b354a. I suspect it's there to specialise instance functions defined by copatterns. For instance, if you define

```agda
FunF : Functor F
FunF = record { fmap = fmapF }
```

then `fmap {{FunF}}` gets specialised to `fmapF` by `ProjectionReductions`, but if you define it with a copattern instead

```agda
FunF : Functor F
fmap {{FunF}} = fmapF
```

it doesn't. I don't think limiting this to non-recursive functions would cause any problems. It might even be the sensible thing to do.
