### ISSUE TITLE
Confused by eta-reduction when quoting record value

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#2525]
I found this issue https://github.com/agda/agda/issues/1581 today, but I actually don't think it's a syntax highlighting issue: I think the syntax highlighting is accurate. Here is a reflect macro and an example:

```agda
open import Agda.Builtin.Reflection
open import Agda.Builtin.List

infixl 5 _>>=_
_>>=_ = bindTC
pure = returnTC


defToTerm : Name → Definition → List (Arg Term) → Term
defToTerm _ (function cs) as = pat-lam cs as
defToTerm _ (data-cons d) as = con d as
defToTerm _ _ _ = unknown

derefImmediate : Term → TC Term
derefImmediate (def f args) = getDefinition f >>= λ f' → pure (defToTerm f f' args)
derefImmediate x = pure x

macro
  reflect : ∀ {ℓ} {t : Set ℓ} → t → Type → TC _
  reflect {_} {t} x ty = quoteTC x >>= derefImmediate >>= quoteTC >>= unify ty

record R (a b : Set) : Set where
  field
    f : a → b

r : ∀ {a} → (_ _ _ _ : R a a) → R a a
r r₁ r₂ r₃ r₄ =
  let
    a = R₁.f
    b = R₂.f
    c = R₃.f
    d = R₄.f
  in
  record { f = a }
  -- record { f = d }
  where
    module R₁ = R r₁
    module R₂ = R r₂
    module R₃ = R r₃
    module R₄ = R r₄
```

Use `C-c C-n` and `reflect r` to see. Compare the commented example `f = d` with the current `f = a`: one is 20 lines, the other is 10. In fact, `a`, `b`, and `c` are all 20 lines.

As far as I can see, this normalisation difference comes from their du bruijn indexes in the original `r` definition. If you add `⊤` parameter after the `(_ _ _ _ : R a a)` in the `r` definition, suddenly `d` behaves the same as all the others. Reorganizing the open modules at the bottom also seems to confirm that the behavior is indeed dependent on the original index position.

**Comment by identicalsnowflake** [comment]
Maybe I should clarify -- I don't mean to say this issue is about reflection. That macro is just what I'm using to look at the terms.

The issue is when you load the file, [look at the colors of the definitions of a, b, c, and d](https://i.imgur.com/V0F7iAT.png). `a`, `b`, and `c` are all one color (for me, green) and `d` is another color (for me, pink). I'm contending that this is not a syntax highlighter error--when you look at these terms with that reflection macro, they are, in fact, different!

**Comment by andreasabel** [comment]
Ah, sorry, I looked too briefly at the report.  

I'd say the difference you observe is due to eta-contraction.

The difference in color is because `d` is actually recovered as projection (since it `R.f` applied to de Bruijn index 0).  The others are not.

But what is your problem?

**Comment by identicalsnowflake** [comment]
I don't know the specifics of the internals -- it's possible there's a good reason for this that I as a user just can't easily see. But from my perspective, it's odd that only dubruijn index 0 is treated as a projection. It makes a big difference for me because I run a mini-compiler in the TC monad (hence, all my TC reports) to do stuff like make compiled queries where both the app-level code and the query-level code (run in the database engine) are both just regular Agda code.

In this use case, the difference between a real projection (pink) and the green ones (whatever those are called) is enormous -- it's often the difference between a primitive function call and 200 lines of imported dependencies from uninlined typeclasses.

I've long been aware of this difference between pink and green, it's just up until now I wasn't sure what exactly was causing it and tried all sorts of odd incantations to try to summon the pink ones.

**Comment by andreasabel** [comment]
The reason for the special treatment of de Bruijn index 0 is that it allows us to recover projections from module applications.  Consider
```agda
record R : Set1 where
  field f : Set

module M (r : R) where
  open R r public

test = M.f
```
You can see in Agda that `M.f` is pink, even though it is not a native projection of the record `R`.  Module `M` declares a __value__ `f = R.f r`, but by abstracting over `r` we get `M.f r = R.f r` and with eta-contraction, `M.f = R.f` becomes a projection.  This clearly does not work if `r` is not the last variable introduced.  Hope this explains the magic of de Bruijn index 0.

**Comment by identicalsnowflake** [comment]
Hmm, yeah I can see how that happens -- simple eta reduction does yield a magically better result for index 0.

That makes things so tricky, though! Especially because the difference is so non-trivial in practice:
with my prelude, `reflect ("a" <> "b")` yields 7 lines, while `reflect (1 + 1)` yields more than 300, despite the fact that both of these instances reduce to a builtin.

Anyway, thanks for helping me see why this happens. Now that I know what's happening, I can intelligently design around it, rather than stumbling around in the dark!
