### ISSUE TITLE
--ignore-interfaces should not recompile Primitive.agda

### ISSUE THREAD

**Issue by phile314** [agda/agda#2530]
``--ignore-interfaces`` currently also recompiles ``Primitive.agda``. This fails if Agda is installed in a read-only location. ``--ignore-interfaces`` should only re-typecheck the files I am currently working on and not libraries/primitives.

Maybe this could be solved via the library system, so that ``--ignore-interfaces`` would not apply to loaded libraries and making ``Primitive.agda`` a small library.

The problem also applies to the ``Agda.Builtin.*`` modules and can happen with other libraries (stdlib, agda-prelude) as well.

Example:
<pre>
agda Test.agda --ignore-interfaces
/nix/store/r8nsb8fiq8fk1rbg5cr1cl5nxhchacrs-Agda-2.5.3/share/x86_64-linux-ghc-8.0.2/Agda-2.5.3/lib/prim/Agda/Primitive.agdai:
removeLink: permission denied (Read-only file system)
</pre>

**Comment by andreasabel** [comment]
We could change the semantics of `--ignore-interfaces` that it does not include interfaces from
* Agda's primitive/builtin libraries
* Libraries the current project depends on (see field `depend` in the `.agda-lib` file)

It would still ignore interfaces coming from the included directories, either given on the command line, or via the `include` field of the `.agda-lib`.

**Comment by jespercockx** [comment]
We now no longer reload primitive modules with `--ignore-interfaces` (but you can use `--ignore-all-interfaces` if you really want to), so I'm closing this issue. Feel free to open an enhancement request for the part of your proposal to not recreate interfaces from (external) libraries.
