### ISSUE TITLE
Expose name id in reflection API

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#2535]
We have two different `where` clauses below, both named `z`:
```agda
e : Bool → Bool
e true = z
  where z = true
e false = z
  where z = false
```

If you inspect this term via the reflection API, you can properly get two distinct names (with respect to `primQNameEquality`) for these two Z's, but the problem is you have no way to actually see *how* they're different. When you use `primShowQName : Name -> String`, the resulting strings are identical.

I noticed that the JS backend does not have this problem: it seems to hash the names somehow. Is it possible to expose this functionality to the reflection API, too?

**Comment by UlfNorell** [comment]
We could quite easily add two primitives to get the name id:

```agda
primQNameModuleId : Name → Nat
primQNameNameId   : Name → Nat
```

**Comment by identicalsnowflake** [comment]
Yes, that would be perfect!

**Comment by gallais** [comment]
The effort to make reflection safe means that we now have a [primitive](https://agda.github.io/agda-stdlib/experimental/Agda.Builtin.Reflection.html#2318)

```agda
primQNameToWord64s : Name → Σ Word64 (λ _ → Word64)
```

Is that a satisfactory solution @identicalsnowflake?

**Comment by identicalsnowflake** [comment]
Yeah I think so. I haven't played around with this for a long time, but I think I was experimenting with compilation via the reflection API and I was having trouble with being unable to distinguish between colliding names. Looks like this should provide enough to distinguish variables in scope with the same name.
