### ISSUE TITLE
Split agda-tests into separate cabal file

### ISSUE THREAD

**Issue by phile314** [agda/agda#2544]
The testsuite is currently defined in the main Agda.cabal file. I would prefer if the `agda-tests` test suite would be defined in a separate cabal file.

My motivation is that I am currently playing around with the CI Hydra Nix tool (see https://hydra.314.ch/project/Agda ) and I can't run the tests easily without having a separate cabal file. `agda-tests` has no dependency on the `Agda` library and is always called through the Makefile, so having a separate cabal file should not inconvenience anybody. Also, this would make the release process slightly easier by not having to remove the testsuites ( https://github.com/agda/agda/blob/master/notes/agda-releases#L81 ).

**Comment by asr** [comment]
Since the Cabal file has too many numbers (Cabal version supported, lower and upper bounds  for the dependencies, tools versions supported, etc.) splitting `agda-test` would mean longer maintenance times.

>`agda-tests` has no dependency on the `Agda` library and is always called through the Makefile

Is still strictly necessary to use the Makefile with recent versions of Cabal? That is, IIRC you used the Makefile due to some Cabal issues. Are these issues still open?

**Comment by UlfNorell** [comment]
The test suite doesn't have the same tool and libraries dependencies so I don't see how splitting it off would add to the maintenance burden.

Is there some benefit of running the tests with cabal instead of the Makefile that I don't understand? How would I say "make succeed fail" with cabal?

**Comment by phile314** [comment]
I used the Makefile for two reasons, first some cabal bugs but also so that one could continue to use the same `make ...` commands for testing. I believe some of the cabal bugs are fixed, I haven't investigated yet in detail.

In principle you can run some of the tests directly using cabal, but the commands are less ergonomic in my opinion and would need some changes in the test runner. Example (untested):

    cabal test --test-option="--pattern /Fail/"

There are also some tests which still use the Makefile (e.g. api, interactive, interaction). They can (and maybe should) be ported to the Haskell test runner, but this would require some effort.

I am also not sure if running `cabal test` directly after `cabal build` without `cabal install` can work,  as the Setup.hs Agda custom hook is only executed on register. I will test.

**Comment by asr** [comment]
On second thought, I have no objection for splitting `agda-tests`.

**Comment by andreasabel** [comment]
I am aiming for the opposite: have the testsuite(s) in the `.cabal` file so that they can e.g. be run by `stack` in a standardized way.  The original issue is > 4 yrs old now, so I do not know whether it is still of interest.

Thus, I am closing this issue.  Reopen if there are new considerations.
