### ISSUE TITLE
Race condition in api tests

### ISSUE THREAD

**Issue by phile314** [agda/agda#2545]
The api tests are using tmp files with constant names. If the api tests are run multiple times in parallel, this leads to race conditions while accessing/writing the same tmp files. See https://github.com/agda/agda/blob/master/test/api/Makefile#L10 .

**Comment by asr** [comment]
I'll fix it.

**Comment by asr** [comment]
@phile314, I pushed the above commit. Did it fix the issue?

**Comment by phile314** [comment]
It fixes the issue, thank you for the fix :+1:
