### ISSUE TITLE
Testsuite Fail: first run tests that have no .err file yet

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2546]
Testsuite Fail: first run tests that have no .err file yet.  
For the Agda implementor's sake!
@phile314 : Do you think we could get that?

**Comment by phile314** [comment]
Shouldn't be too difficult, changing the sort order of the test cases depending on the presence of the .err/.out file should do the trick. I can take a look in the next few days.

**Comment by andreasabel** [comment]
Good!  I have been thinking about what order would fit the development best.  Something like this, maybe:
1. The testcases without .err (only applies to Fail testsuite)
2. The testcases that are less than 24 hours old, alphabetically.  This should reflect the test cases one is currently working with.
3. The remaining testcases, alphabetically.

**Comment by andreasabel** [comment]
I am taking over.  But I think I will skip the .err part, for simplicity.

**Comment by phile314** [comment]
Sorry that I couldn't get round to it, I have been quite busy the last few weeks...

**Comment by andreasabel** [comment]
No problem, wasn't that hard.  I was eager to get this feature.
