### ISSUE TITLE
Use Neil Mitchell's `extra` package

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2547]
I found that https://hackage.haskell.org/package/extra has many utility functions we also define.  
It's dependencies are modest.  It seems very well maintained, and has test cases for the functions it defines.
We could use `extra`.
We could even replace our own utilities by uses of `extra` where possible.

**Comment by UlfNorell** [comment]
I'm reluctant:
- It won't cover all of our current utilities, so it'll be harder to find things (you have to look both locally and in the `extra` package). For instance, currently I can use the tags file to jump to the definition of the latest combinator for monadically casing on a maybe.
- It would be a non-trivial amount of work.
- I don't really see any benefits at all.. maybe it defines some nice utility functions that we don't have?

**Comment by jespercockx** [comment]
I think it is better to simply extend our own Agda.Utils with any functionality from `extra` that we want to use: that way we stay in control over which functions we want or don't want (similarly, we don't import Lens but define our own lens primitives). We could even think about releasing `agda-utils` as a standalone haskell package at some point.
