### ISSUE TITLE
Move the "Old Reference Manual" to the current documentation

### ISSUE THREAD

**Issue by asr** [agda/agda#2548]
The [Old Reference Manual](http://wiki.portal.chalmers.se/agda/pmwiki.php?n=ReferenceManual.TOC) in the Wiki has some information

* which is missing in the documentation,
* which is duplicated in documentation or
* which is obsolete

I guess everyone agrees that not having centralized documentation makes it harder to use Agda.

We should remove the Wiki manual step by step by

* adding the missing information to the documentation and deleting the manual entry
* deleting the entries with duplicated information

**Comment by jespercockx** [comment]
Many people are still getting confused between the (outdated) wiki and the documentation on readthedocs (perhaps because of google linking directly to some places deep in the wiki). Ideally we should remove all outdated information before the next release.

**Comment by jespercockx** [comment]
I went over all the old wiki pages and moves the remaining information that could be useful to the user manual. I also added a disclaimer to the top of all wiki pages with a link to the new manual. We could discuss whether we should remove the information on the wiki altogether, but I don't think it matters that much (as long as the links are there on top).
