### ISSUE TITLE
Internal error in Agda.TypeChecking.Substitute

### ISSUE THREAD

**Issue by nad** [agda/agda#2550]
Consider the following code:
```agda
open import Agda.Builtin.Equality using (_≡_; refl)

record ∃ {A : Set} (B : A → Set) : Set where
  constructor _,_
  field
    proj₁ : A
    proj₂ : B proj₁

open ∃ public

uncurry : {A : Set} {B : A → Set} {C : ∃ B → Set₁} →
          ((x : A) (y : B x) → C (x , y)) →
          ((p : ∃ B) → C p)
uncurry f (x , y) = f x y

_⟶_ : {I : Set} → (I → Set) → (I → Set) → Set
A ⟶ B = ∀ {i} → A i → B i

postulate
  I   : Set
  i j : I
  R   : I → I → Set

record P : Set where
  field
    f : ∀ {k} → R i k → ∃ λ l → R k l

Q : Set
Q =
  ∃ λ (f : ∀ {j} → R i j → I) →
  (λ { (j , k) → ∃ λ (r : R i j) → f r ≡ k }) ⟶ uncurry R

to : P → Q
to f = (λ r → proj₁ (P.f f r))
     , λ { (r , refl) → proj₂ (P.f f r) }

from : Q → P
P.f (from (f , g)) r = f r , g (r , refl)

to∘from : ∀ q → to (from q) ≡ q
to∘from _ = refl
```
This code triggers an internal error in Agda 2.6.0-b1fdf1c:
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Substitute.hs:380
```
This is a regression. Bisection suggests that the bug was introduced by @UlfNorell in bf9ff1e676d51ce35d50658b6274ecdb8b60fda2 ("[ fixed #2047 ] fixed broken apply for clauses").

**Comment by andreasabel** [comment]
Nothing to do with this issue, but is there a reason why you never use the agda markdown syntax highlighting when reporting a but, @nad.  I have just been wondering, since you are a regular bug reporter... I routinely add the highlighting to your bug reports to see quicker what is going on.

**Comment by andreasabel** [comment]
@UlfNorell Since you worked on this recently, I think it is most efficient if you take a look on this issue.

**Comment by nad** [comment]
> Nothing to do with this issue, but is there a reason why you never use the agda markdown syntax highlighting when reporting a but, @nad.

Yes, the highlighting you get here is not "proper" Agda highlighting.

**Comment by UlfNorell** [comment]
The problem is that we try to reify pattern lambda clauses before record pattern translation, breaking the precondition of `apply`. Fix incoming.
