### ISSUE TITLE
Internal Error in Reduce.Fast

### ISSUE THREAD

**Issue by turion** [agda/agda#2560]
I was happily coding when suddenly I got this error:

```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Reduce/Fast.hs:534
```
It happened when refining a hole. I can supply the code if that helps (it's not public yet).
Agda version is 2.5.2.

**Comment by andreasabel** [comment]
Ah yes, please.  Ideally a MWE.  Without an example, we cannot do anything.

**Comment by turion** [comment]
You can find the offending code in https://github.com/Aerate/condatis/blob/master/Examples/TrafficLight.agda, line 238. Uncomment it, comment line 239, go into the hole in line 238 and try to refine it.

**Comment by andreasabel** [comment]
I record the commit hash of the `condatis` repo here: 082810da4361b7f825e6e482c4c987d059773bb6.
(In case this example gets changed in the future.)

**Comment by UlfNorell** [comment]
Self-contained test case:

```agda
open import Agda.Builtin.Nat

postulate
  Position : Set

Sets : Set₁
Sets = Position → Set

data FVec : (n : Nat) → Set₁ where
  FNil  : FVec 0
  FCons : ∀ {n} → Sets → FVec (suc n)

_pre_ : ∀ {m n} → FVec m → FVec (suc n) → Sets
FCons x pre keep    = x
FNil    pre FCons x = x

AG : Sets → Set
AG props = ∀ p → props p

data proofAG : {n : Nat} → FVec n → Set where
  []AG : proofAG FNil

postulate
  preAG : ∀ m n (v : FVec m) (v' : FVec (suc n)) →
            proofAG v → proofAG v' → AG (v pre v')

preAG₁ : (m n : Nat) (v : FVec m) (v' : FVec (suc n)) →
         AG (v pre v')
preAG₁ m n v v' = preAG 0 n FNil _ []AG {!!}
  -- Refine gives internal error instead of 'Cannot refine' or
  -- 'No introduction forms found'.
```

**Comment by UlfNorell** [comment]
Simplified a bit more and added a case where `C-c C-c` fails.

```agda
open import Agda.Builtin.Nat

postulate Pos : Set

data FVec : (n : Nat) → Set₁ where
  FNil  : FVec 0
  FCons : ∀ {n} → (Pos → Set) → FVec (suc n)

pre : ∀ {m n} → FVec m → FVec (suc n) → Pos → Set
pre FNil      (FCons x) = x
pre (FCons x) _         = x

data proofAG : ∀ {n} → FVec n → Set where
  []AG : proofAG FNil

postulate
  preAG : ∀ m n (v : FVec m) (v' : FVec (suc n)) →
            proofAG v → proofAG v' → ∀ p → pre v v' p
  m n : Nat
  v  : FVec m
  v' : FVec (suc n)
  p  : Pos

preAG₁ : pre v v' p
preAG₁ = preAG 0 n FNil _ []AG {!!} p
  -- Refine gives internal error instead of 'Cannot refine' or
  -- 'No introduction forms found'.

postulate Constrain : (A B : Set) → (A → B) → Set
syntax Constrain A B (λ x → y) = x ∈ A => y ∈ B

preAG₂ : (let X : FVec (suc n)
              X = _) →
         x ∈ pre FNil X p => x ∈ pre v v' p →
         proofAG X → Set
preAG₂ _ p = {!p!}
  -- Splitting on p causes the same internal error.
```

**Comment by UlfNorell** [comment]
When refining a hole of data type we simulate a case split on an argument of the goal type to figure out whether there's a single valid constructor. Thus the same code runs in both test cases above.

The problem seems to be in the unifier (cc @jespercockx). Here's an excerpt from the debug output:
```
unifyIndices
  []
  (({n = n₁ : Nat} → FVec n₁ → Set))
  [{0}, FNil]
  [{suc n}, _v'_43]
initial unifyState: UnifyState
                      variable tel:  
                      flexible vars:  []
                      equation tel:   {n = n₁ : Nat} (_ : FVec n₁)
                      equations:      {0} =?= {suc n}, FNil =?= _v'_43
Found equation at datatype  FVec  with (homogeneous) parameters  []
Trying to instantiate the meta _v'_43 with the constructor FNil applied to fresh metas
```
It looks like the unifier thinks that the constraint `FNil =?= _v'_43` is homogenous, even though the equation telescope clearly suggests otherwise.

This leads to the internal error since we have a constraint `pre FNil _v'_43 p == pre v v' p : Set`, so instantiating `_v'_43 := FNil` causes the constraint solver to try to evaluate the ill-typed `pre FNil FNil p`.

**Comment by jespercockx** [comment]
Right, the current implementation doesn't check at all that the type of the constructor matches the type of the meta, which is clearly bogus. We should first force the types to be equal (by using `equalTypes`) before instantiating the meta itself. I'll try to implement a fix.

**Comment by UlfNorell** [comment]
Is the problem really with meta instantiation? What happens if you have a flexible variable `v'` instead of `_v'_43`? If it unifies `FNil =?= v'`, won't we get the same error as before?

**Comment by jespercockx** [comment]
Instantiation of flexible variables is handled by the `basicUnifyStrategy`, which *does* check that the type is homogeneous. For equations between constructors, the new unifier actually allows the type of the equation to be heterogeneous in the indices, so homogeneity is only checked for the parameters. My fix checks that the type of the meta matches the type of the constructor applied to the fresh metas, but it doesn't restrict the type of the equation in any way.
