### ISSUE TITLE
Internal error in Agda.TypeChecking.With

### ISSUE THREAD

**Issue by laMudri** [agda/agda#2562]
Loading the following
```agda
module Scratch where
  open import Data.Product
  open import Data.Sum
  open import Data.Unit

  record Coℕ : Set where
    coinductive
    field
      force : ⊤ ⊎ Coℕ

  open Coℕ

  record Colist {a} (A : Set a) : Set a where
    coinductive
    field
      force : ⊤ ⊎ (A × Colist A)

  open Colist

  _++_ : ∀ {a} {A : Set a} → Colist A → Colist A → Colist A
  (xs ++ ys) .force with xs .Colist.force
  ... | inj₁ _ = ys .force
  ... | inj₂ (x , xs′) = inj₂ (x , xs′ ++ ys)
```
gives the error
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/With.hs:433
```
Removing the line `open Coℕ` makes the file load fine, as does changing `(xs ++ ys) .force` to `(xs ++ ys) .Colist.force`. I'm guessing it's something to do with ambiguous copattern field names.

**Comment by andreasabel** [comment]
I think this bug has been fixed already.  With the development versions (2.5.3 and 2.6.0), your file checks fine.
Which Agda version are you using?

**Comment by laMudri** [comment]
Sorry, yes, I'm using 2.5.2.

**Comment by andreasabel** [comment]
Ok, then I close this.  I hope we will release in a while, but for now, this will only work with the development versions.
