### ISSUE TITLE
Improve documentation and error reporting related to instance resolution (especially unconstrained metavariables)

### ISSUE THREAD

**Issue by m0davis** [agda/agda#2563]
The [documentation](https://agda.readthedocs.io/en/v2.5.2/language/instance-arguments.html#instance-resolution) does not say explicitly what Agda does when finding an unconstrained metavariable (UM) whilst trying to resolve an instance argument. As the following code demonstrates, what it does is fail, confusingly reporting all lambda-bound variables that are bound as instance arguments under "Candidates".
```agda
{-# OPTIONS --show-implicit #-}

record Class1 (A : Set) : Set where no-eta-equality
record Class2 : Set where no-eta-equality

module _
  {A : Set}
  where

  postulate
    instance toplevelClass2Instance : Class2

  module _
    ⦃ lambdaboundClass1Instance : Class1 A ⦄
    ⦃ lambdaboundClass2Instance : Class2 ⦄
    (f : {A' : Set} ⦃ c1' : Class1 A' ⦄ → A)
    (P : A → Set)
    where

    postulate
      test-unconstrained-metavariables-failure : P f
```
`agda2-show-constraints` shows:
```
Resolve instance argument _c1'_8 : ({A = A₁ : Set}
       {{lambdaboundClass1Instance = lambdaboundClass1Instance₁
         : Class1 A₁}}
       {{lambdaboundClass2Instance = lambdaboundClass2Instance₁ : Class2}}
       (f₁ : {A' : Set} {{c1' : Class1 A'}} → A₁) (P₁ : A₁ → Set) →
       Class1
       (_A'_7 {A₁} {{lambdaboundClass1Instance₁}}
        {{lambdaboundClass2Instance₁}} f₁ P₁)).
  Candidates:
    [ lambdaboundClass2Instance : Class2
    , lambdaboundClass1Instance : (Class1 A) ]
```
What's confusing is that these be listed as "Candidates" and yet the second stage of instance resolution ("find candidates") has not been reached. A similar error message is given when failure is due to there being no single solution, but in that case, the candidates that Agda reports are just as described in the documentation.

I'm certain that the documentation should be updated to clarify what happens when Agda encounters an UM. I'm also hoping that Agda's error message can be improved: Could Agda indicate the goal type she was trying to solve? along with a list of the UM(s)? Is the currently-reported "Candidates" list (of lambda-bound variables that are bound as instance arguments) of any relevance in this case? If not, can it be dropped?

Finally, when failure is due to no single solution, could Agda indicate the goal type (just as suggested above for the UM case)?

**Comment by UlfNorell** [comment]
The goal type is right there in the constraint:
```
Resolve instance argument _c1'_8 : (GOAL-TYPE)
```
I think the list of candidates doesn't hurt here, but we should certainly indicate that solution doesn't proceed due to UMs.

**Comment by jespercockx** [comment]
Closing this as the restriction on unconstrained metas is no longer there.
