### ISSUE TITLE
Non-exact-split highlighting makes other highlighting disappear

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#2564]
From discussion in c9458dac.

@jespercockx wrote:
> I've noticed the problem with the coloring of the terms as well, unfortunately I didn't manage to find the cause yet. I'll look further into it tomorrow.

Just to make sure this doesn't get forgotten.

**Comment by jespercockx** [comment]
Thank you for the reminder, it's definitely still on my to-do list.

**Comment by nad** [comment]
I think someone asked for a lighter shade of grey. I would also prefer this.

**Comment by gallais** [comment]
The same is true of the highlighting for incomplete coverage, postivity error or even unsolved meta variables for that matter. We probably want to use [Overlays](https://www.gnu.org/software/emacs/manual/html_node/elisp/Overlay-Properties.html) rather than distinct fonts for all of these, don't we?

**Comment by fredrikNordvallForsberg** [comment]
This was fixed by https://github.com/agda/agda/commit/6081e1bcd647c4e3c8df31bcd7473fc335ea2679.
