### ISSUE TITLE
Options for the interaction action give to keep the overloaded literals and sections?

### ISSUE THREAD

**Issue by favonia** [agda/agda#2565]
I am thinking about an option for the action `give` during interaction to keep unexpanded overloaded literals and sections. Maybe even make it the default behavior. That is, `a +_` will not be expanded to `λ section → a + section` and `n` will stay as `n` not something like `fromNat n`. (Note: maybe this is already solved in the Emacs scripts but I am not using Emacs.)

**Comment by andreasabel** [comment]
I am not aware of any Emacs hacks to preserve sections.

I think we should preserve sections when the user wrote them.  We already have `Origin`-info for arguments and projections.  We could also equip the `Def` constructor from `Syntax.Internal` with some information on where it came from (a section, or...).

**Comment by favonia** [comment]
How about the overloaded literals? I changed the title because I realized the same issue probably applies to strings as well.

**Comment by UlfNorell** [comment]
> Note: maybe this is already solved in the Emacs scripts but I am not using Emacs.

> I am not aware of any Emacs hacks to preserve sections.

The hack is [here](https://github.com/agda/agda/blob/69f6a558535338a33e145337d2f887643b62557f/src/full/Agda/Interaction/InteractionTop.hs#L1189), in the `literally` variable. For the give command (and refines that didn't add any holes) we simply have Emacs insert whatever string the user wrote in the hole.

**Comment by nad** [comment]
See also #2270.

**Comment by UlfNorell** [comment]
The section part is solved by the fix to #2270. Overloaded literals still print with their conversion function.

**Comment by asr** [comment]
The email automatically sent when this issue was closed says

> Closed #2565 via 65aec8e

but I cannot find which commit closed the issue here in the bug tracker. Is the same for you?
