### ISSUE TITLE
Instance search complains about unsolved metas depending on how a function is defined

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#2566]
Try the 3 different definitions of `_~_` below. The first two, Agda accepts with no complaint, but the third causes an unsolved meta.

```agda
open import Agda.Builtin.Equality
open import Agda.Builtin.Bool
open import Agda.Builtin.Nat renaming (Nat to ℕ)

{- Case 1 : works as expected -}
-- postulate
--   _~_ : ℕ → ℕ → ℕ

{- Case 2 : works as expected -}
-- _~_ : Bool → Bool → Bool
-- _~_ true false = true
-- _~_ _ _ = false

{- Case 3 : doesn't work -}
-- _~_ : ℕ → ℕ → ℕ
-- _~_ = _+_


postulate
  instance
    ~-com : ∀ {a b} → a ~ b ≡ b ~ a

search : {t : Set} {{_ : t}} → t
search {{i}} = i

_ : ∀ {a b} → a ~ b ≡ b ~ a
_ = search
```

Especially the discrepancy between 1 and 3 is very odd to me, since they have the same type signature, and the variables `a` and `b` are quantified so they contain no usable pattern matching information.

EDIT: Here's an even more interesting example:

```agda
_~_ : Bool → Bool → Bool -- accepted
_~_ true true = true
_~_ _ _ = false

_~_ : Bool → Bool → Bool -- rejected
_~_ true true = true
_~_ false true = false
_~_ true false = false
_~_ false false = false
```

**Comment by UlfNorell** [comment]
Case 1 works since `_~_` is a postulate, so the only way to solve `_X ~ _Y == u ~ v` is with `_X := u` and `_Y := v`.

Case 2 works because all right-hand sides of `_~_` are constructor headed, so the above holds when `u ~ v` is neutral.

In case 3 it does not hold: another solution is `_X := zero` and `_Y := u ~ v`.

**Comment by identicalsnowflake** [comment]
Huh. This seems to, at least at a meta level, disprove functional extensionality. The two definitions in my PS are provably extensionally equal, but instance search can discern between the two.

**Comment by UlfNorell** [comment]
If you couldn't "disprove functional extensionality" at the meta level, we'd have extensional type theory. Sadly we're stuck in the intentional version. For instance, the type checker happily accepts `refl : a + b ≡ a + b`, but rejects `refl : a + b ≡ b + a`, even though `a + b` and `b + a` are extensionally equal.

Also, note that instance search isn't really involved here, the difference shows up in plain old unification. In the example instance search gets stuck on an unsolved unification problem.

**Comment by identicalsnowflake** [comment]
Now that you mention it, I can see with your refl example that obviously extensional equality is not exactly aligned with intentional at the meta level.

Still, regarding the instance search - does it even need to be trying to solve the problem it's getting stuck on? The postulate example demonstrates that if only the type signature is used and no information about the definition is used, then a solution can be found immediately. It seems it's searching for more solutions using the information in the definition, then getting stuck?

Or is this basically just the same thing as requesting that the `overlap` keyword be allowed in general and not only in record fields :)

**Comment by UlfNorell** [comment]
If you look at the constraints, you'll find that it did solve the instance problem. The only thing that remains is checking that the solution is type correct. For this it needs to solve the unification problem that's only solvable in the first two cases.

**Comment by identicalsnowflake** [comment]
Oh, I see what you mean now -- yes, I can provide the instance solution `{{~-com}}` and still get the unsolved unification, so it can't be instance search's problem.

**Comment by UlfNorell** [comment]
In case it wasn't clear, here's the core problem:

```agda
postulate
  f : Nat -> Nat -> Nat

g : Nat -> Nat -> Nat
g = _+_
```

For a unification problem `f _X _Y == f u v`, the only solution is `_X := u, _Y := v`. For the problem `g _X _Y == g u v` you have two possible solutions: `_X := u, _Y := v` and `_X := zero, _Y := u + v`.

Saying that it's enough to look at the type signature amounts to giving up on the second solution. It's not too hard to construct an example where that would be the wrong thing to do.

**Comment by identicalsnowflake** [comment]
Right, I understand what you're saying now (at least I think I do) -- the problem is that instance search is finding an instance solution, but the instance it finds doesn't have a unique unifiable solution with the goal, and therefore, Agda refuses to solve it and gives an error, right?

In general, I agree with the unifier's behavior -- I don't want `_` choosing a non-unique solution. However, in the specific context of solving a unification problem generated by instance search, I'm not sure: instance search is already me as a user saying I'm happy with a solution that isn't directly findable by unification anyway. Off the top of my head, I think I'd be more than happy with it just choosing a solution it can read off the type signature and simply discarding any potential subsequent finds from the definition.

But that's definitely biased towards my current predicament and could certainly have pitfalls elsewhere I'm not seeing.

**Comment by m0davis** [comment]
@identicalsnowflake, fwiw, I notice that marking `_~_` as `abstract` also yields a unique solution. Maybe that somehow will help you out of your predicament.

**Comment by identicalsnowflake** [comment]
It does, but I can't immediately think of a way to make that useful, since the result you get is stated in terms of an abstract `~`, you can't use it later to compute anything.

Playing around a bit, it does work if you quantify over `_~_`, perform the search, then plug in `_+_` afterward, but doing this is fairly verbose and it requires you to explicitly restate the entire goal in terms of the quantified ~. But it does work:

```agda
record S {t : Set} (_~_ : t → t → t) : Set where
  field
    {{~-com}} : ∀ {a b} → a ~ b ≡ b ~ a

postulate
  +s : S _+_

eg : ∀ {a b} → a + b ≡ b + a
eg {a} {b} = go +s
  where
    go : ∀ {_~_} → S _~_ → a ~ b ≡ b ~ a
    go _ = search
```
