### ISSUE TITLE
Cpphs not installed when installing Agda on Haskell Platform

### ISSUE THREAD

**Issue by ggreif** [agda/agda#2567]
Installation of `agda-2.5.2` just failed on a freshly installed Haskell Platform 8.0.2 (full).

Maybe the dependency to `cpphs` is not correctly declared in the cabal file?

**Comment by asr** [comment]
Thanks for reporting the issue. Current versions of `cabal-install` don't install the tools listed in the `build-tools` field in the `.cabal` file, so you need to install Alex, Happy and cpphs.

**Comment by favonia** [comment]
FYI: the `stack` tool will install these dependencies for you.

**Comment by andreasabel** [comment]
It would be nice if a simple `cabal install Agda` would suffice.

We could at least get rid of the alex and happy dependencies by adding the .hs file to the released version.  
Can we do something about cpphs?

**Comment by asr** [comment]
> Can we do something about cpphs?

Yes. We can add `cpphs` as a dependency but I don't like this solution. Future versions of `cabal-install` will install the tools listed in the `build-tools` field.
