### ISSUE TITLE
agda2-infer-type-maybe-toplevel (in hole) does not respect "single-solution" requirement of instance resolution

### ISSUE THREAD

**Issue by m0davis** [agda/agda#2568]
```agda
open import Agda.Primitive

record R l : Set (lsuc l) where
  field r : Set l
  self : R l
  self = record { r = r }

open R {{ ... }}

it : ∀ {a} {A : Set a} {{x : A}} -> A
it {{x}} = x

test : ∀
  l1 {{ R1 : R l1 }}
  l2 {{ R2 : R l2 }}
  -> R l1
test l1 {{ R1 }} l2 {{ R2 }} = {!self {{ it }}!}
```
`agda2-infer-type-maybe-toplevel` (C-c C-d) should show `R l1`, but instead we get `R l2`. 

Evidently, while in the hole, Agda is resolving `it` as `R2` instead of `R1`. This seems to be a problem only in interactive mode: when the goal is refined (the hole brought to top-level), there are no type errors, so presumably, in that case, Agda resolves `it` as `R1`.

**Comment by andreasabel** [comment]
I do not really see what you want to demonstrate with this example.  `self {{ it }}` is ambiguous, thus, Agda is not wrong to show you type `R l2`.  Maybe you want to see an error instead?

**Comment by m0davis** [comment]
I now see that `self {{ it }}` is ambiguous in the sense that there are multiple instance candidates, and that this is because `agda2-infer-type-maybe-toplevel` makes no attempt (by design) to unify with the goal. I still think Agda is wrong to show `R l2`: I think the example demonstrates that Agda is arbitrarily resolving an instance argument when there are multiple non-identical solutions. I want Agda to instead leave the instance unresolved and show something like `R (_l_15 l1 l2)`, which is what I get when I replace `self {{ it }}` with `self {{ _ }}`.

**Comment by UlfNorell** [comment]
For some reason I have yet to figure out, the instance meta is deemed `irrelevant` and thus instance search happily picks whichever instance it found first (`R2` in this case).

**Comment by UlfNorell** [comment]
Also it only fails when the argument to `R` is of type `Level`. Simplified test case:

```agda
open import Agda.Primitive

A = Level -- Only fails for Level!

postulate
  R : A → Set
  self : ∀ {x} {{_ : R x}} → R x

it : ∀ {l} {A : Set l} {{x : A}} → A
it {{x}} = x

postulate
  a b : A

test : {{R1 : R a}} {{R2 : R b}} → Set
test {{R1}} {{R2}} = {!self {{it}}!}  -- C-c C-d returns R b
```

**Comment by UlfNorell** [comment]
It looks like the problem might be this code (introduced by @andreasabel in 312cf84) in `Interaction.BasicOps`:

```haskell
-- | Returns the type of the expression in the current environment
--   We wake up irrelevant variables just in case the user want to
--   invoke that command in an irrelevant context.
typeInCurrent :: Rewrite -> Expr -> TCM Expr
typeInCurrent norm e =
    do  (_,t) <- wakeIrrelevantVars $ inferExpr e
        v <- normalForm norm t
        reify v
```

`wakeIrrelevantVars` sets the relevance of the context to `Irrelevant` so any metas created will be treated as irrelevant. It doesn't explain why the problem goes away if you pick something other than `Level` for `A` though...

**Comment by UlfNorell** [comment]
It only fails for `Level` since level metas are exempt from the non-rigidly constrained meta check.

Here is a test case without levels:
```agda
postulate
  A : Set
  T : A → Set
  f : (a : A) → T a

it : {A : Set} {{x : A}} → A
it {{x}} = x

test : {{a b : A}} → Set
test {{a}} {{b}} = {!f it!} -- C-u C-u C-c C-d gives T b
```

**Comment by m0davis** [comment]
After this patch, Agda is looping endlessly in some instance-related code. Working on a simplified test case... (it may take a day or so)

**Comment by UlfNorell** [comment]
Can you check if reverting 6df6354 makes the problem go away?

**Comment by m0davis** [comment]
@UlfNorell Will do.

p.s. Ulf was responding to a post (I insanely deleted) saying that I was getting Agda looping problems after this patch

**Comment by m0davis** [comment]
@UlfNorell Yup, I verified that reverting https://github.com/agda/agda/commit/6df6354147ab1f33677f9b2678d1c7cec0221468 makes the problem go away. Still working on a simplified example... Frustratingly, I spent considerable time simplifying an example that turned out to loop even w/o the patch. Waah.

**Comment by UlfNorell** [comment]
That might be interesting too though. Instance search now has limited search depth, so it shouldn't loop regardless.
