### ISSUE TITLE
Upload Haddock generated doc to github pages

### ISSUE THREAD

**Issue by gallais** [agda/agda#2570]
Given that we generate haddock documentation on travis after each push (?), we could have it sit on https://agda.github.io/ by getting travis to push it to a repo called agda/agda.github.io. See e.g. [1] for a travis deployment script.

[1] http://www.steveklabnik.com/automatically_update_github_pages_with_travis_example/

**Comment by favonia** [comment]
The following seems better because it uses a new SSH key instead of a personal access token. This way other collaborators will not be able to steal the token.

https://gist.github.com/domenic/ec8b0fc8ab45f39403dd

**Comment by phile314** [comment]
Just FYI, if you want to take a look at the current haddocks right now, I have a job running on my own server that produces them:
https://hydra.314.ch/job/Agda/Agda-master/ghc801.x86_64-linux.haddock/latest/download/1

But using github pages is probably better,  because I can't really promise that I will keep the job running on my server forever.

**Comment by andreasabel** [comment]
Someone just contributed a github pages deployment for https://github.com/agda/agda-spec which could be adopted to publishing the haddockumentation.

**Comment by L-TChen** [comment]
I can take care of this. I have used GitHub Action to publish websites like my own website https://l-tchen.github.io and http://flolac.iis.sinica.edu.tw. The setup is pretty easy but requires the repo administrator to select a branch (and optionally a directory). 

I guess a project site is better than an organisation site (see [here](https://pages.github.com) for difference) in this case. As for the URL, how about https://agda.github.io/agda/haddock?
