### ISSUE TITLE
Handling of name collision of implicit module parameters and arguments

### ISSUE THREAD

**Issue by favonia** [agda/agda#2572]
I am slightly confused by how Agda is currently handling variable name collision. In the following code, `T.id` theoretically has three implicit arguments (badly) named as `A`. Only the second one (which I believe was a parameter of the module `S`) is renamed to `A₁`.
```agda
record Unit : Set where
  constructor unit

module S {A : Set} where
  id : {A : Set} → A → A
  id a = a

module T {A : Set} = S

id : {A : Set} → A → A
id {A = A} = T.id {A = Unit} {A₁ = Unit} {A = A}
```
The behavior I expected is one of the following:

1. everything is renamed to avoid collision, so that the final `A` is `A₂`; or
2. a warning or even an error is issued somewhere.

If the current behavior is intended, I would suggest some clarification in the documentation. Otherwise, there is probably a subtle bug.

**Comment by andreasabel** [comment]
The behavior we are aiming for is that no hidden argument name is changed by Agda.  The expected type would be
```
T.id : {A : Set} {A = A1 : Set} {A = A2 : Set} -> A2 -> A2
```
The current behavior is buggy.

**Comment by favonia** [comment]
Actually that was my original expectation, and then I found renaming or a warning could be useful after being surprised. In any case, I am fine as long as the behavior is consistent.

**Comment by nad** [comment]
See also #2018.
