### ISSUE TITLE
No link attached to module without toplevel name

### ISSUE THREAD

**Issue by gallais** [agda/agda#2574]
What it says in the title: `B.agda` loads just fine but there is no link attached to `A` in `open import A` which means that it is impossible to reach it both in emacs (via `M-.` or `click-2`) and the generated html doc.

`A.agda`:

```agda
```

`B.agda`:

```agda
open import A
```

**Comment by andreasabel** [comment]
There was no range created for anonymous module names.  I fixed this in Parser and ConcreteToAbstract.
