### ISSUE TITLE
deBruijn fail for higher order instance problem

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#2577]
```agda
postulate
  Wrap : Set → Set
  instance wrap : {A : Set} → A → Wrap A

postulate
  I : Set
  P : I → Set

HO = ∀ {i} {{p : P i}} → P i

postulate
  X : {{ho : HO}} → Set
  Y : {{ho : Wrap HO}} → Set

Works : Set
Works = X

-- not ok
-- Debug output shows messed up deBruijn indices in unwrapped target: P p
Fails : Set
Fails = Y
```

**Comment by gallais** [comment]
Shouldn't this test case be in Fail? https://github.com/agda/agda/blob/master/test/Succeed/Issue2577.agda

**Comment by UlfNorell** [comment]
No, that test case should check now.

It was actually two problems here: one deBruijn error and a separate problem with instance goals that resolve to a function type after the instance meta has been created. Previously we handled function types when creating an instance meta which didn't work if the goal was a meta variable.
