### ISSUE TITLE
Catch-all clause face used incorrectly for parent with pattern

### ISSUE THREAD

**Issue by nad** [agda/agda#2578]
Consider the following code:
```agda
data _⊎_ (A B : Set) : Set where
  inj₁ : A → A ⊎ B
  inj₂ : B → A ⊎ B

record ⊤ : Set where
  constructor tt

data ⊥ : Set where

Maybe : Set → Set
Maybe A = ⊤ ⊎ A

pattern nothing = inj₁ tt
pattern just x  = inj₂ x

Bool : Set
Bool = ⊤ ⊎ ⊤

pattern true  = inj₁ tt
pattern false = inj₂ tt

x : Maybe ⊥
x = nothing

A : Set₁
A with false
A | true = Set
A | false with x | x
... | nothing | nothing = Set
... | just () | _
... | _ | just ()
```
Agda correctly highlights the final clause with the face for catch-all clauses. However, the pattern `false` in the left-hand side `A | false` is also highlighted with this face. This highlighting goes away if the last line is replaced by `A | false | _ | just ()`.

**Comment by andreasabel** [comment]
Some ranges were not set properly in expandEllipses.
