### ISSUE TITLE
Wrong de Bruijn index introduced by absurd pattern

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#2583]
I introduced an error in a test case (https://github.com/agda/agda/blob/master/test/LibSucceed/Issue784/Values.agda) in my patch d34cfe19315e826351a8bf4e6d220066325b3bfc, for which I'm very sorry. So far, I have managed to minimize the test case to the following:
```agda
data ⊥ : Set where

data Maybe : Set where
  just : ⊥ → Maybe
  nothing : Maybe

test : Set → Set
test x with nothing
test x | just ()
test x | nothing = test x
```
This results in an internal error:
```
Panic: de Bruijn index out of scope: 2 in context [x₁,x]
```
I suspect the problem has something to do with the with-inlining done by the termination checker, but I haven't managed to locate the problem precisely.

EDIT: simplified a bit further

**Comment by andreasabel** [comment]
So only the with-inlining in the termination checker brought this de Bruijn index error to light.  Apparently, absurd patterns are nowhere used seriously after lhs-checking.

**Comment by jespercockx** [comment]
Yes, I think on the longer term we should remove the Pattern argument from AbsurdP entirely. But for now keeping the old pattern seemed to be the easiest solution that didn't break everything.
