### ISSUE TITLE
Stack complains about Agda.cabal

### ISSUE THREAD

**Issue by nad** [agda/agda#2600]
I noticed the following output from Stack on Travis:
```
Package Agda uses a custom Cabal build, but does not use a custom-setup stanza
Not using the explicit setup deps approach based on configuration
Strongly recommend fixing the package's cabal file
```

**Comment by asr** [comment]
We cannot fix the warning due to [this](https://github.com/commercialhaskell/stack/issues/3034#issuecomment-287149374) reason.

**Comment by asr** [comment]
I was wrong. From the Cabal [documentation](http://cabal.readthedocs.io/en/latest/developing-packages.html#backward-compatibility-and-custom-setup):

> Versions prior to Cabal 1.24 don’t recognise `custom-setup` stanzas, and will behave agnostic to them (except for warning about an unknown section). 

So, I'll add the missing `custom-setup` stanza.
