### ISSUE TITLE
internal error at src/full/Agda/TypeChecking/Rules/LHS.hs:496 on misspelled constructor names

### ISSUE THREAD

**Issue by florence** [agda/agda#2601]
A small example:

```
module _ where

data td : Set where
  constr : td

test : td → td
test x@(y) = {!!}
```

(note that at `x@(y)` the "constructor name" is misspelled.

My Agda version is 2.5.2

**Comment by andreasabel** [comment]
Thanks for reporting. This bug has been already been fixed in the development version.
