### ISSUE TITLE
Check that LHS of a rewrite rule doesn't reduce is too strict

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#2606]
Example by Ambrus Kaposi on the Agda mailing list:
```
{-# OPTIONS --rewriting #-}

module a where

postulate
  _~_ : {A : Set} → A → A → Set

{-# BUILTIN REWRITE _~_ #-}

module m1 (X : Set) where

  postulate
    A B : Set
    a : A
    b : B
    f : A → B

module m2 (X : Set) where

  open m1 X

  postulate
    β : f a ~ b

  {-# REWRITE β #-}
```
Results in an error:
```
β  is not a legal rewrite rule, since the left-hand side 
f a  reduces to  f a
when checking the pragma REWRITE β
```

**Comment by akaposi** [comment]
Hi Jesper, thanks, now it typechecks.

But it seems to me that Agda still does not perform the rewriting. If I add the following lines to the end of the file I think it should still typecheck:

~~~~
  postulate
    refl : {A : Set}{a : A} → a ~ a

  p : f a ~ b
  p = refl
~~~~

However when I remove the `X` parameters, it typechecks with these lines added.

**Comment by jespercockx** [comment]
I see. It seems the rewrite rule is now added to the copy of the function created by the import statement instead of to the original function.
