### ISSUE TITLE
Instance search confused when an instance argument is sourced from a record

### ISSUE THREAD

**Issue by m0davis** [agda/agda#2607]
Given some record named `Class`, the following code blocks should be equivalent and interchangeable from the point of view of instance search:

Code wherein an instance is bare:
```agda
instance
  postulate Instance : Class
```

Code wherein an instance is wrapped in a record and then subsequently made bare:
```agda
record InstanceWrapper : Set where
  no-eta-equality
  instance
    postulate Instance : Class

open InstanceWrapper record {} public
```

If that's not true, if the above code blocks are not supposed to be equivalent, then perhaps the rest of this post is moot. Continuing onwards regardless, the below code demonstrates that Agda can get confused when an instance is sourced from a record wrapper:

```agda
postulate
  Nat : Set
  Fin : Nat → Set

Finnat : Nat → Set
Finnat x = Fin x → Nat

postulate
  fortytwo : Nat
  finnatic : Finnat fortytwo
  _==_ : Finnat fortytwo → Finnat fortytwo → Set
  ==-copy : ∀ {x y : Finnat fortytwo} → x == y → x == y

record Fixer : Set where
  field fix : ∀ {x} → Finnat x → Finnat fortytwo
open Fixer ⦃ … ⦄

record Fixidentity ⦃ _ : Fixer ⦄ : Set where
  field fixidentity : ∀ {f : Finnat fortytwo} → fix f == f
open Fixidentity ⦃ … ⦄

record InstanceWrapper : Set where
  no-eta-equality
  instance
    postulate FixerInstance : Fixer

open InstanceWrapper record {}

instance
  postulate FixidentityInstance : Fixidentity

works : fix finnatic == finnatic
works = ==-copy fixidentity

fails₁ : fix finnatic == finnatic
fails₁ = ==-copy {x = fix finnatic} fixidentity

fails₂ : fix finnatic == finnatic
fails₂ = fixidentity
```
The errors are:
```
Failed to solve the following constraints:
  Resolve instance argument _45 : Fixidentity {{FixerInstance}}
  Candidates FixidentityInstance : Fixidentity {{FixerInstance}}
  Resolve instance argument _38 : (Fixidentity {{FixerInstance}})
  Candidates FixidentityInstance : (Fixidentity {{FixerInstance}})
```
Note that if the `InstanceWrapper` is repealed and replaced by the code below, no errors issue:
```agda
instance
  postulate FixerInstance : Fixer
```

**Comment by UlfNorell** [comment]
The two code blocks are not equivalent. Instances need not be 'bare' to be eligible for instance search. For instance,

```agda
postulate
  Class : Set

record InstanceWrapper : Set where
  no-eta-equality
  instance
    postulate Instance : Class

it : ∀ {a} {A : Set a} {{_ : A}} → A
it {{x}} = x

postulate
  instance InstW : InstanceWrapper

foo : Class
foo = it
```
When you open the record you get another available instance. In many cases this isn't a problem (except for performance) since the two instances are equal, but if the unapplied instance fails to resolve instance search will fail.

That said it's surprising that `works` works and `fails₁` fails since the only difference is that an implicit argument was provided.

**Comment by UlfNorell** [comment]
Something is clearly not right:

```agda
fails : Fixer.fix FixerInstance finnatic == finnatic
fails = fixidentity

works : Fixer.fix FixerInstance finnatic == finnatic
works = fixidentity {{it}}
```

**Comment by UlfNorell** [comment]
The problem seems to arise from the fact that `FixerInstance` is *irrelevant*(!) (@andreasabel?) in the `InstanceWrapper` argument. If you add a field to `InstanceWrapper` this is (thankfully) no longer the case and all the examples go through.

**Comment by andreasabel** [comment]
A record which has no relevant fields is irrelevant.  But at the time of adding this feature #392 we did not have `no-eta-equality`, maybe it should only be this way for eta-records?

**Comment by andreasabel** [comment]
I don't understand the point of this post. @m0davis if you want to wrap the instance as above, the cleaner way seems to use a module instead of a record with no fields.
```agda
module InstanceWrapper where
  instance postulate ...
open InstanceWrapper
```

**Comment by UlfNorell** [comment]
> maybe it should only be this way for eta-records?

That does seem like the sensible thing to do.

There's still something weird going on here though. The irrelevant `InstanceWrapper` argument to the non-opened instance does get solved, but somehow that solution is lost on the way. I haven't investigated, but I suspect it's got something to do with how we compare different instance solutions.

I'll try to construct an example that doesn't rely on the irrelevant record feature.

**Comment by m0davis** [comment]
@andreasabel In the original code (before I cleaned it up for reporting), the `InstanceWrapper` was parameterised and the idea was to expose instances for only certain values of the parameters.

**Comment by m0davis** [comment]
@andreasabel Umm, on second thought, I guess I could have used a module for that too. Honestly, I don't know what the point is. For my use case, I'm happy to just use a module.

**Comment by UlfNorell** [comment]
Here's the weirdness with explicit irrelevance:
```agda
postulate
  Nat : Set
  Fin : Nat → Set
  Finnat : Nat → Set
  fortytwo : Nat
  finnatic : Finnat fortytwo
  _==_ : Finnat fortytwo → Finnat fortytwo → Set

record Fixer : Set where
  field fix : ∀ {x} → Finnat x → Finnat fortytwo
open Fixer {{...}}

postulate
  Fixidentity : {{_ : Fixer}} → Set
  instance
    fixidentity : {{fx : Fixer}} {{fxi : Fixidentity}} {f : Finnat fortytwo} → fix f == f

  InstanceWrapper : Set
  iwrap : InstanceWrapper
  instance
    IrrFixerInstance : .InstanceWrapper → Fixer

instance
  FixerInstance : Fixer
  FixerInstance = IrrFixerInstance iwrap

instance
  postulate FixidentityInstance : Fixidentity

it : ∀ {a} {A : Set a} {{x : A}} → A
it {{x}} = x

fails : Fixer.fix FixerInstance finnatic == finnatic
fails = fixidentity

works : Fixer.fix FixerInstance finnatic == finnatic
works = fixidentity {{fx = it}}

works₂ : Fixer.fix FixerInstance finnatic == finnatic
works₂ = fixidentity {{fxi = it}}
```

**Comment by UlfNorell** [comment]
This seems to have been fixed at some point. Adding test case.
