### ISSUE TITLE
Build failure (2.5.2) due to outdated cpphs

### ISSUE THREAD

**Issue by cartazio** [agda/agda#2608]
src/full/Agda/Utils/Null.hs:42:10: error:
    Duplicate instance declarations:
      instance Eq Doc -- Defined at src/full/Agda/Utils/Null.hs:42:10
      instance [safe] Eq Doc -- Defined in ‘Text.PrettyPrint.HughesPJ’

I think this could be fixed by a bound somewhere, or by cutting a bugfix release ?

**Comment by cartazio** [comment]
cc @hvr @ryanGIscott for trustee wisdom

**Comment by cartazio** [comment]
it looks like its because of my local package db having some confusion that tripped up cabal... closing for now

**Comment by cartazio** [comment]
nope, it was that i had cpphs 1.20.4 installed locally, updating it fixed the problem :)

**Comment by asr** [comment]
GHC version?

**Comment by hvr** [comment]
I don't know the exact GHC version, but I assume he used GHC 8.0.2 + Cabal 1.24; the problem however was that cabal 1.24 doesn't yet solve for and build `build-tools`-dependencies; so the broken `cpphs-1.20.4` release was used which appears to have a bug (and is marked `deprecated` on hackage) re `#include` lookup. This wouldn't be any problem anymore with cabal-2.0, as cabal would have installed the latest `cpphs` release that satisfies the specified `build-tools`-version-constraints. IOW, it's not Agda's fault.

**Comment by asr** [comment]
I couldn't reproduce the issue using GHC 8.0.2 and

```
cabal --version
cabal-install version 1.24.0.2
compiled using version 1.24.2.0 of the Cabal library
```

The current cpphs constraint is

```
build-tools: cpphs >= 1.20.2
```

I'm waiting the fix of https://github.com/malcolmwallace/cpphs/issues/11 for updating the constraint.

**Comment by hvr** [comment]
@asr This could be OS-specific, I  see that http://hdiff.luite.com/cgit/cpphs/diff?id=1.20.5&id2=1.20.4 fixed something in the path-handling which makes the bug @cartazio saw plausible to me

nevermind, I just saw the cpphs#11 bug filed

**Comment by cartazio** [comment]
this was on mac osx with cpphs at the bad version @hvr mentioned, and ghc
8.0.2 and cabal install  1.24

upgrading cpphs to not be the broken version fixed it.

the real issue was adga forcing cpp to be via cpphs ;) :))

**Comment by asr** [comment]
Agda version?

**Comment by cartazio** [comment]
was 2.5.4,
but the issue was a bad cpphs

**Comment by asr** [comment]
Agda 2.5.4 doesn't exist. Did you mean 2.5.3?

**Comment by cartazio** [comment]
2.5.2. Most recent hackage release.  The point being the issue is
resolved.  The bug was a bad cpphs that no one else can get anymore and
won't matter with cabal >=2
