### ISSUE TITLE
Case split results in code that is not accepted by Agda

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#2609]
Consider the following code:
```agda
open import Common.Bool
open import Common.Nat

data cheesy : Bool → Set where
  chocolate : cheesy false
  cheese    : cheesy true
  bread     : ∀ x → cheesy x

foo : ∀ {x : Bool} → cheesy x → cheesy x → Bool
foo x chocolate = {!!}
foo x cheese = {!!}
foo x (bread false) = {!x!}
foo x (bread true) = {!!}
```
If you case split on `x` in the third clause, Agda generates the following code:
```agda
foo : ∀ {x : Bool} → cheesy x → cheesy x → Bool
foo x chocolate = {!!}
foo x cheese = {!!}
foo chocolate (bread false) = ?
foo (bread .false) (bread false) = ?
foo x (bread true) = {!!}
```
which results in an error:
```
I'm not sure if there should be a case for the constructor bread,
because I get stuck when trying to solve the following unification
problems (inferred index ≟ expected index):
  x ≟ false
when checking that the pattern bread false has type cheesy false
```
Looking at the debug output, the equation `x ≟ false` is not solved because `x` is not a flexible variable, though why is not clear to me (and certainly not to the user).

I'd guess that this wouldn't be a problem if we used the alternate splitting strategy proposed in #408.

**Comment by jespercockx** [comment]
Another possible solution (aside from changing split strategies) would be to allow some more leniency in skipping dots: if Agda allowed you to write the pattern `false` where currently it expects `.false`, then this code would be accepted. This would mean Agda would count *all* variables as flexible during LHS checking, and if a variable (say `x`) is instantiated with some value (say `u`) then Agda would have to check that `u` is equal to what the user wrote in that position.

**Comment by andreasabel** [comment]
I think your proposal makes sense, to be less bureaucratic about the dotting.  I wonder only what will happen if users drop dots maximally after your change, giving Agda more split possibilities.  Could such possibilities lead Agda into a dead end where it would not have come with dots in place?

**Comment by jespercockx** [comment]
That's a good question. If (after my proposed change) you drop all the dots in front of constructors, then that can certainly change which case tree is constructed. However, if a split fails then Agda will simply try a different one. For example, the following looks funny but is accepted with my change:
```
open import Agda.Builtin.Bool

data D : Bool → Set where
  c : D true

f : (x : Bool) → D x → Bool
f true c = true
```
Agda first tries to split on the first argument, but not all constructors are covered so Agda decides to split on the second argument instead. 

I'm not sure if there are cases where you can actually get a function to be rejected by removing dots, but I have the feeling it could be possible.

**Comment by nad** [comment]
> However, if a split fails then Agda will simply try a different one.

Do your changes make Agda slower by introducing more backtracking?

**Comment by jespercockx** [comment]
There's no actual backtracking involved as Agda commits to a case split once it has found one that succeeds. However, with this change Agda might try more different case splits before finding one that succeeds. So to answer your question: yes, this change might slow down Agda, but not exponentially so. Also note that the slowdown only happens when you don't put the dots. If you do, you will get the same performance as before.

**Comment by andreasabel** [comment]
Thanks.
I think the documentation is not accurate.

> The dot in front of an inaccessible pattern can now be skipped if the pattern is constructor-headed. 

It should say that the dot can be skipped if the pattern consists only of constructors.  The parts which have variables or other terms need still to be dotted, no?

**Comment by andreasabel** [comment]
It also works for literals (which it should).  "Constructor-headed" might not include "literal" for all readers.
```agda
open import Common.Nat

data cheesy : Nat → Set where
  chocolate : cheesy 0
  cheese    : cheesy 1
  bread     : ∀ x → cheesy x

foo : ∀ {x : Nat} → cheesy x → cheesy x → Nat
foo x         chocolate = {!!}
foo x         cheese    = {!!}
foo chocolate (bread 0) = {!!}
foo (bread 0) (bread 0) = {!!}
foo cheese    (bread 1) = {!!}
foo (bread 1) (bread 1) = {!!}
foo x         (bread n) = {!!}
```
