### ISSUE TITLE
Avoid rechecking by storing interfaces in separate directories?

### ISSUE THREAD

**Issue by nad** [agda/agda#2610]
When you switch from one version of Agda to another it is likely that Agda will ignore existing interface files. If you switch by accident, and then switch back right away, this can be fairly annoying. Perhaps we could store interface files in separate directories, and use separate directories for different versions of Agda (or different interface versions).

**Comment by andreasabel** [comment]
What is the proposed directory structure?  We could have a `_build_VERSION` directory in the project-root with subdirectories
```
agda   -- for .agdai files 
ghc    -- for generated .hs files
html   -- for generated .html files
latex  -- for generated .tex files
```
These target directories would be the default ones, but could be set by command line options to somewhere else.

We could also integrate this issue with Jonathan Prietos package manager, maybe!?

**Comment by UlfNorell** [comment]
I'd prefer `_build/VERSION` to avoid polluting the top-level directory. Different directories for different interface version seems overkill. I'd have to go around removing interface files once a week to avoid running out of disk space.

**Comment by cartazio** [comment]
is there a way to control where .agdai files are placed when doing agda-mode style development in emacs? (or is that what this ticket is about?)

**Comment by nad** [comment]
Currently interface files are stored in the same directory as source files.

**Comment by gallais** [comment]
Related to #2330

**Comment by gallais** [comment]
It was really easy to get something half-working. However the fact that source
files (that definitively exist) and interface file (that may not exist) share
the same `AbsolutePath` type means it is really easy to write code raising
exceptions.

To add to the confusion, in some places we use `FilePath` instead of
`AbsolutePath`. I guess a refactoring is in order.

**Comment by gallais** [comment]
Alright, in #3949 I have an implementation of this feature.
I am currently dumping all `.agdai` files in `_build/VERSION`
but it would be easy to adopt @andreasabel's suggestion to
have an `agda/` subdirectory to make room for `ghc/`, `latex/`, etc.
