### ISSUE TITLE
`exact-split` documentation is outdated and incomplete

### ISSUE THREAD

**Issue by asr** [agda/agda#2612]
The user manual [says](https://github.com/agda/agda/blob/master/doc/user-manual/language/function-definitions.lagda.rst#case-trees):

```
Since 2.5.1 you can have Agda warn you when a situation like this occurs by adding `{-# OPTIONS --exact-split #-}` at the top of your file.
```

After c9458dacce2cbff0db0875da9dda7f619ad619ce the warns about clauses which don't hold by definition don't require the `--exact-split` pragma.

I also noted that `CATCHALL` is not documented.

**Comment by xekoukou** [comment]
```CATCHALL``` seems unnecessary now.

**Comment by asr** [comment]
You need `CATCHALL` for removing the error (no the warning) generated by a clause which doesn't hold by definition when using the `--exact-split` pragma.
