### ISSUE TITLE
Parametrised modules, with-abstraction and termination

### ISSUE THREAD

**Issue by asr** [agda/agda#2613]
MWE of an issue reported by @jonaprieto.

Using `Agda version 2.5.3-bd94880` I'm getting the following error:

```agda
module Bug where

open import Agda.Builtin.Nat

module Prop (n : Nat) where

  data Prop : Set where
    _∧_ _∨_ : Prop → Prop → Prop

open Prop zero

data DView : Prop → Set where
  case₁ : (a b c : Prop) → DView ((a ∨ b) ∧ c)
  case₂ : (a : Prop)     → DView a

dView : (p : Prop) → DView p
dView ((a ∨ b) ∧ c) = case₁  _ _ _
dView a             = case₂ _

dist-∧ : Prop → Prop
dist-∧ p with dView p
dist-∧ .((a ∨ b) ∧ c) | case₁ a b c = dist-∧ (a ∧ c)
dist-∧ a              | case₂ .a = a

-- /tmp/Bug.agda:23,1-26,37
-- Termination checking failed for the following functions:
--   dist-∧
-- Problematic calls:
--   dist-∧ (a ∧ c)
--     (at /tmp/Bug.agda:25,38-44)
```

Two comments:

1. The example is type-checked by Agda 2.5.2.

2. By removing the parameter `(n : Nat)` from the `Prop` module, the example is type-checked by 2.5.3 (and 2.5.2).

**Comment by andreasabel** [comment]
Thanks for reporting.  Somehow this regression was introduced during fixing and unfixing #2403 and having #2458 inbetween.

**Comment by asr** [comment]
@jonaprieto, does the fix solve your real example?

**Comment by jonaprieto** [comment]
Yes, thanks! agda-prop type-checked.
