### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by asr** [agda/agda#2617]
We have instructions for installing Agda in the [Wiki](http://wiki.portal.chalmers.se/agda/pmwiki.php?n=Main.Download), the [user manual](http://agda.readthedocs.io/en/v2.5.2/getting-started/installation.html) and the [README](http://hackage.haskell.org/package/Agda-2.5.2/readme). Since the user manual is online, I suggest to move *all* instructions there. Any opinion?

**Comment by asr** [comment]
and keeping the download information on the Wiki.

**Comment by nad** [comment]
The README is displayed on Hackage. Perhaps we could keep a small number of links in this file.

**Comment by asr** [comment]
Done.
