### ISSUE TITLE
Feature request: link to `renaming` clause

### ISSUE THREAD

**Issue by joelburget** [agda/agda#2619]
Clicking `inside` or `outside` in [Data.Fin.Dec](https://agda.github.io/agda-stdlib/Data.Fin.Dec.html) links directly to `true` / `false` in [Agda.Builtin.Bool](https://agda.github.io/agda-stdlib/Agda.Builtin.Bool.html#92), which is confusing. Linking to the [renaming import](https://agda.github.io/agda-stdlib/Data.Fin.Subset.html#813) (which is in a different module) would resolve the confusion and provide a link to the definition.

**Comment by joelburget** [comment]
cc @cartazio

**Comment by nad** [comment]
This could also be useful if a module is applied to one or more arguments and then opened publicly.

**Comment by andreasabel** [comment]
I implemented this by updating the `nameBindingSite` in the abstract name belonging to the `to` concrete name in the `renaming` clause.  The new binding site is the range of the `to` concrete name.

Jump-to-definition seem to work both in emacs and in html.

> This could also be useful if a module is applied to one or more arguments and then opened publicly.

This is a related, but different feature request I do not address.  What would jump-to-definition jump to here?  The applied module?  But then I cannot jump on to the original definition, which is easy for the `renaming` case (clicking on the `from` name).

**Comment by nad** [comment]
> This is a related, but different feature request I do not address. What would jump-to-definition jump to here? The applied module?

The open public statement?

> But then I cannot jump on to the original definition, which is easy for the `renaming` case (clicking on the `from` name).

We could have two different commands (`M-.` and `C-u M-.`, say), where one jumps to the "root" and the other to the closest link (renaming, open public). However, the chain might have several links. Perhaps it would be better with a command that opened a buffer with the entire chain (including links to the source files).

**Comment by andreasabel** [comment]
@nad: for the module application, please open a new issue.
