### ISSUE TITLE
docs for auto aren't clear on how to use flags/options

### ISSUE THREAD

**Issue by cartazio** [agda/agda#2631]
how do the various flags for auto work? http://agda.readthedocs.io/en/latest/tools/auto.html

do i do something like {! -t 20 !} or whatever? theres zero clarity in the docs about how to *use* auto.

**Comment by asr** [comment]
> do i do something like {! -t 20 !}

Yes but it seems it is not working in the current development version (stable branch). Please file a new issue for the timeout problem. I'll use this issue for adding the missing documentation.

**Comment by andreasabel** [comment]
Thanks, Guillaume!

**Comment by asr** [comment]
I'm used to see the changes in the user manual reflected in the online manual. The [commit](cb0b898d668059a8e891ab9918c3086e40902828) that fixed this issue is in master, but I cannot see the changes in the [online](http://agda.readthedocs.io/en/latest/tools/auto.html) manual. Was there some change in the manual workflow?

**Comment by gallais** [comment]
Seems like [a lot of the builds fail](https://readthedocs.org/projects/agda/builds/) with "An unexpected error occurred". rtfd/readthedocs.org#3006 may be related.

Edit: at least [one of the failures](https://readthedocs.org/projects/agda/builds/5734750/) gives a Traceback and mentions a permission problem.

**Comment by gallais** [comment]
Ah! Looking at it was enough for [one build to pass](https://readthedocs.org/projects/agda/builds/5752959/) and we now have [the updated docs](https://agda.readthedocs.io/en/latest/tools/auto.html).

The very high rate of failure is still concerning though. :/

**Comment by asr** [comment]
The builds are failing again...
