### ISSUE TITLE
some flags to auto dont seem to work in current agda 2.5.2

### ISSUE THREAD

**Issue by cartazio** [agda/agda#2632]
eg  {! -t 20 !} is the random example mentioned in https://github.com/agda/agda/issues/2631#issuecomment-313733706

(nb: i have no idea how to use any of the flags, so others may or may not also wok)

**Comment by gallais** [comment]
Do you have a reproducible case? The following test (`C-c C-l` followed by `C-c C-a`) works for me with `2.5.2`, `2.5.3` (commit 173cbe1) and `2.6.0` (commit 57e568c).

```agda
module TestAuto where

goal : {A : Set} (f : A → A) → A
goal f = {!-t 5!}
```

**Comment by cartazio** [comment]
Ummm, it was claimed by the person responding to me on the original thread
... I have no idea

**Comment by cartazio** [comment]
@gallais  maybe @asr can clarify his remark:

> Yes but it seems it is not working in the current development version (stable branch). Please file a new issue for the timeout problem. I'll use this issue for adding the missing documentation.

**Comment by gallais** [comment]
Can't reproduce so closing this. Don't hesitate to reopen if you have a MWE.
