### ISSUE TITLE
Fixity declaration ignored in definitions in record

### ISSUE THREAD

**Issue by sattlerc** [agda/agda#2634]
Tested with Agda version 2.5.3-c8bffa4.

Operator syntax is not supported for definitions of operators in record scopes:
```agda
infix 50 _∼_

postulate
  A : Set
  x : A
  _∼_ : A → A → Set

record T : Set where
  infix 60 _∘_
  _∘_ : A → A → A
  -- Next line fails with following error.
  -- Could not parse the left-hand side a ∘ b
  -- Operators used in the grammar:
  -- None
  a ∘ b = x
  field
    law : x ∘ x ∼ x
```

Fixity declarations for definitions in record scopes are ignored:
```agda
infix 50 _∼_

postulate
  A : Set
  x : A
  _∼_ : A → A → Set

record T : Set where
  -- This fixity declaration is ignored.
  infix 60 _∘_
  _∘_ : A → A → A
  _∘_ _ _ = x
  field
    -- Since _∘_ has default fixity 30, the below expression
    -- is mistakenly parsed as x ∘ (x ~ x).
    law : x ∘ x ∼ x
```

**Comment by andreasabel** [comment]
Yeah, sorry about that.  It is a too long open issue: #2500 ...  
A theoretical solution is outlined in #434 ...

**Comment by Blaisorblade** [comment]
Any relation with #917?

**Comment by UlfNorell** [comment]
The second part (the ignored fixity declaration) can't really be blamed on #2500. There's no reason the scope checker shouldn't be able to use the correct fixity for the operator when checking the fields.

**Comment by UlfNorell** [comment]
The first part is still open, but since that's an instance of #2500 I'm closing this issue.

**Comment by sattlerc** [comment]
Thanks!

**Comment by UlfNorell** [comment]
The first part is actually #917.

**Comment by UlfNorell** [comment]
First part now also fixed.
