### ISSUE TITLE
Performance regression, possibly related to the size solver

### ISSUE THREAD

**Issue by nad** [agda/agda#2639]
Consider the following code:
* `DR.agda`:
  ```agda
  module DR (_ : Set) where

  open import Agda.Builtin.Size

  mutual

    data D (i : Size) : Set where
      a : D i
      b : R i → D i

    record R (i : Size) : Set where
      coinductive
      field
        force : {j : Size< i} → D j
  ```
* `Bug.agda`:
  ```agda
  module Bug (A : Set) where

  open import Agda.Builtin.Nat
  open import Agda.Builtin.Size

  open import DR A

  postulate
    P : {i : Size} → D i → Set

  F : Set₁
  F = Set
    where

    postulate
      unused : P a

    G : Nat → Set → Set₁
    G zero = λ { _ → Set }
    G (suc zero) = λ { _ → Set }
    G (suc (suc zero)) = λ { _ → Set }
    G (suc (suc (suc zero))) = λ { _ → Set }
    G (suc (suc (suc (suc _)))) = λ { _ → Set }
  ```
If `unused` is commented out, then the code is quickly accepted, but otherwise Agda 2.6.0-decf1bc spends a lot of time on it.

Note that `unused` involves an unconstrained size variable. Perhaps the size solver works really hard with this code.

This is a regression, Agda 2.5.1.1 accepts the code quickly.

**Comment by nad** [comment]
Bisection suggests that the bug was introduced by @andreasabel in 9a6128647a13b57d8a42590125af259196e9a743: "Fixed 2046 by an agreeably dirty hack (no clean up yet)".

See also #2046.

**Comment by andreasabel** [comment]
That story is consistent: Agda 2.5.1.1 still did not have parameter refinement.  For Agda 2.5.2 I had to work around the hack to scale to parameter-refinement, probably introducing the performance regression there.

**Comment by andreasabel** [comment]
The regression is: Each time the size solver fails to solve the constraints, it adds another copy of these constraints.  Each attempt doubles the number of constraints.  So we get exponential behavior.
