### ISSUE TITLE
Records with duplicate fields

### ISSUE THREAD

**Issue by favonia** [agda/agda#2642]
I feel records with duplicate fields should be rejected at their definitions. Not only their semantics are confusing, but also they are very difficult to use. To clarify, I am talking about
```agda
postulate nat : Set

record test : Set where
  constructor t
  field
    a : nat
    a : nat
```
which is currently accepted but in my opinion should be rejected or at least generates some warnings.

**Comment by andreasabel** [comment]
The following even triggers an internal error:
```agda

record R : Set₁ where
  field
    F : Set
    F : Set  -- duplicate field, should be rejected

test : Set → R
test A = record{ F = A }
```
yields
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Rules/Term.hs:687
```
