### ISSUE TITLE
Cannot build agda

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda#2647]
When running `cabal install` on a fresh version of the repository (commit 60ab017) I get the following output:
```
Building Agda-2.6.0...
Preprocessing library Agda-2.6.0...
[  3 of 323] Compiling Agda.Utils.TypeLevel ( src/full/Agda/Utils/TypeLevel.hs, dist/build/Agda/Utils/TypeLevel.o )

src/full/Agda/Utils/TypeLevel.hs:27:66:
    parse error on input `where'
Failed to install Agda-2.6.0
cabal: Error: some packages failed to install:
Agda-2.6.0 failed during the building phase. The exception was:
ExitFailure 1
```
Is this a problem with Agda or a problem with my environment?

**Comment by asr** [comment]
> Is this a problem with Agda or a problem with my environment?

The [latests](https://www.travis-ci.org/agda/agda/builds/253872931) Travis builds are OK.

**Comment by asr** [comment]
GHC version?

**Comment by andreasabel** [comment]
@MatthewDaggitt That is a weird location for GHC to fail...

**Comment by asr** [comment]
I could reproduce the error with GHC 7.6.3. @MatthewDaggitt, this version of GHC isn't supported in master nor stable.
