### ISSUE TITLE
Update benchmark with new standard library list membership

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda#2648]
As Andreas [describes](https://github.com/agda/agda-stdlib/commit/6c5b6ccd216977b12a7dcdd6d9e34256fec965b4#commitcomment-23106449) one of the benchmarks is broken by my new changes to how list membership works in the standard library. I would fix it myself, but I'm on holiday and I'm currently experiencing problems with my GHC version on my personal computer. I'll keep trying to update my GHC version and fix it myself, but in case anyone gets there first, the error is:
```
agda/benchmark/std-lib/Any.agda:36,6-22
No such module Any.Membership-≡
when scope checking the declaration
  open Any.Membership-≡
```
The full details of the changes to list membership can be found in [CHANGELOG.md](https://github.com/agda/agda-stdlib/blob/master/CHANGELOG.md). But in short, it should be easy to fix by changing any references to `Data.List.Any.Membership-≡` to `Data.List.Any.Membership.Propositional`.

**Comment by gallais** [comment]
Blocked by agda/agda-stdlib#154

I need to update the agda-stdlib submodule so I need to fix all of the compilation errors arising from the new changes. I'd like to go for the principled solution rather than e.g. renaming [this local module definition](https://github.com/agda/agda/blob/master/test/LibSucceed/Issue854/Run.lagda#L65).

**Comment by andreasabel** [comment]
Thanks!

**Comment by MatthewDaggitt** [comment]
Okay, accepted your pull request. Thanks!

**Comment by gallais** [comment]
Perfect! Preparing the patch right now.

**Comment by gallais** [comment]
Notice that the great deprivatisation leads to Auto finding [more solutions](https://github.com/agda/agda/commit/7be1e5f1c78f87484c68c1e7bddfc2e7dbe990c0#diff-676f53cfc896d3782cc2052c0d62913d) and triggering #1789
