### ISSUE TITLE
Empty list of "previous definition" in duplicate definition error

### ISSUE THREAD

**Issue by gallais** [agda/agda#2649]
While working on #2648, I've come across a weird error message:

```
/home/gallais/projects/agda/test/LibSucceed/Issue854/Run.lagda:65,10-11
Duplicate definition of module M. Previous definition of module M
at
when scope checking the declaration
  module M = RawMonad rawMonad
```

The problem arises in [this file](https://github.com/agda/agda/blob/master/test/LibSucceed/Issue854/Run.lagda#L65) from [this `module M` definition](https://github.com/agda/agda-stdlib/blob/78d9beb9c951f63471a5196fe9cdfcc5c0e22d43/src/Data/List/Any/Membership/Propositional.agda#L25) which is simply used as an anonymous "module level" lambda (and, arguably, should be a `private` definition).

**Comment by gallais** [comment]
Shrunk test case:

Issue2649-3.agda:
```agda
module Issue2649-3 where

module MyModule (A : Set) (a : A) where

  dft : A
  dft = a
```
Issue2649-2.agda:
```agda
module Issue2649-2 where

open import Issue2649-3

open module M {A : Set} {a : A} = MyModule A a public
```
Issue2649.agda:
```agda
module Issue2649 where

open import Issue2649-3
open import Issue2649-2

id : {A : Set} → A → A
id x = M.dft where module M = MyModule _ x
```

Error message:

```
/home/gallais/languages/agda/Issue2649.agda:7,27-28
Duplicate definition of module M. Previous definition of module M
at
when scope checking the declaration
  module M = MyModule _ x
```

**Comment by andreasabel** [comment]
Somehow I cannot reproduce the error message you see.  I get
```
/home/abel/tmp/agda/test/bugs/Issue2649.agda:7,29-30
Duplicate definition of module M. Previous definition of module M
at /home/abel/tmp/agda/test/bugs/Issue2649-2.agda:5,13-14
when scope checking the declaration
  module M = MyModule A x
```
Thus, Agda __is__ pointing me to the duplicate definition.

**Comment by gallais** [comment]
I think you need for the `agdai` files to already be present to reproduce the error. I do get the location when I first load the file, or if I reload it after switching to a different version of Agda (because the `agdai` are re-generated, I presume) but I don't if I simply 'kill and restart' and reload.

**Comment by andreasabel** [comment]
Ok, I get the empty list on the command line, but not in the emacs mode.

**Comment by andreasabel** [comment]
After refactoring for a whole day (#1293) to get more debug output, I can see that the `nameBindingSite` of the duplicate module has been partially removed:
- it is present for the part `Issue2649-2`
- it is absent for the interesting part `M`

**Comment by andreasabel** [comment]
I do not understand this issue: 
- not killing the nameBindingSite does not fix the issue (Abstract.Name.killRange Name)
- it could be that the serializer throws away the information via the `Name` memoization mechanism

**Comment by andreasabel** [comment]
Maybe not killing the nameBindingSite fixes the issue after all.

@gallais If this issue persists, please reopen.

**Comment by gallais** [comment]
I can't reproduce the issue anymore. Thanks!
That refactoring looks *intense*.

**Comment by andreasabel** [comment]
> That refactoring looks intense.

I will probably continue for a while.
Task #1293 was understandably not picked up by anyone in 3 years.  Grepping for `show` gives 2000 hits...
