### ISSUE TITLE
Internal error on result splitting without --postfix-projections

### ISSUE THREAD

**Issue by rntz** [agda/agda#2654]
Consider the following:
```agda
open import Data.Product
dup : ∀{A : Set}(a : A) -> A × A
dup = λ { x -> {!!}  }
```

Putting the cursor in the hole and hitting C-c C-c RET to result-split results in an error:
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/Interaction/InteractionTop.hs:814
```

Adding `{-# OPTIONS --postfix-projections #-}` at the top of the file prevents this.

I'm using Agda version 2.5.2.

**Comment by andreasabel** [comment]
Without postfix projections, the split is not possible (no syntax for it).  Thus, I guess in this case, instead of crashing, Agda should just use postfix projections automatically.

I implemented this.
