### ISSUE TITLE
test/Succeed/ImportWarnings fails sometimes

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2657]
`test/Succeed/ImportWarnings` fails sometimes after I recompile Agda and run the test suite for the first time.  The second time I run `make succeed`, the test does not fail.

**Comment by andreasabel** [comment]
test/Succeed/ImportWarnings fails sometimes (different output).

See also #2685.

**Comment by fredrikNordvallForsberg** [comment]
I think this is fixed by the above commit. Closing.
