### ISSUE TITLE
Hackage "source repository" command invalid

### ISSUE THREAD

**Issue by gallais** [agda/agda#2663]
The [Agda package](https://hackage.haskell.org/package/Agda) on hackage indicates:

```
Source repository  head: git clone https://github.com/agda/agda.git
                   this: git clone https://github.com/agda/agda/tree/v2.5.2(tag v2.5.2)
```
But running the second command `git clone https://github.com/agda/agda/tree/v2.5.2` yields the error:

```
Cloning into 'v2.5.2'...
remote: Not Found
fatal: repository 'https://github.com/agda/agda/tree/v2.5.2/' not found
```

I'm using git version 2.1.4 in case that matters.

**Comment by gallais** [comment]
This seems to be working:

```
git clone git@github.com:agda/agda --single-branch -b v2.5.2 --depth 1
```

Although maybe someone without credentials would have to use `https://github.com/agda/agda` instead of the `git@github.com:agda/agda` url?

**Comment by asr** [comment]
I also fixed the issue on [Hackage](https://hackage.haskell.org/package/Agda).

**Comment by gallais** [comment]
Thanks!
