### ISSUE TITLE
Segmentation fault with compiled programs using mutual record

### ISSUE THREAD

**Issue by csetzer** [agda/agda#2664]
In the  attached file, when we compile the file and then execute it we get segmentation fault, when using for LUniv a mutual record; if we omit the mutual record, there is no segmentation fault.

[example2.agda.txt](https://github.com/agda/agda/files/1189093/example2.agda.txt)

**Comment by UlfNorell** [comment]
Here's a smaller test case:

```agda
open import Agda.Builtin.IO
open import Agda.Builtin.String
open import Agda.Builtin.Unit
open import Agda.Builtin.Nat

mutual
  record R : Set where
    constructor mkR
    field
      dummy : Nat
      str : String

helloWorld : R
helloWorld = mkR 0 "Hello World!"

postulate
  putStrLn : String → IO ⊤

{-# FOREIGN GHC import qualified Data.Text.IO as Text #-}
{-# COMPILE GHC putStrLn = Text.putStrLn #-}

main : IO ⊤
main = putStrLn (R.str helloWorld)
```

For some reason the internal representation (`CompiledClauses`) of the projection functions are different with and without the `mutual`.

With `mutual`:
```haskell
-- compiled clauses of R.str
  done[ru("xx")] @0 .Issue2664.R.str
```

Without `mutual`:
```haskell
-- compiled clauses of R.str
  case 0 of Issue2664.R.mkR -> done[ru("x"),ru("x")] @0
```

In the `mutual` case it looks to me (and to the compiler) that the projection is given a circular definition. @andreasabel: is this a bug in the `CompiledClauses` or in the treeless compiler?

Even if it's a bug in the compiler, it's odd that adding a useless `mutual` changes how projections are represented.

**Comment by andreasabel** [comment]
It seems that if `mutual` then the projection definitions go through record pattern translation, see `Rules.Decl.revisitRecordPatternTranslation`, introduced for #2308 and #2197.
Record pattern translation for record projection definitions is counterproductive. They should be exempt.
