### ISSUE TITLE
Feature request: nullary pattern matching lambdas

### ISSUE THREAD

**Issue by sattlerc** [agda/agda#2671]
Function definitions can be nullary (have zero arguments), so why not anonymous pattern matching lambdas?

With the introduction of field pattern matching, this actually has practical use. Say inside an expression you want to define a value of record type by pattern matching. The natural way to proceed would be to introduce a pattern matching lambda λ { → ?} and then case split on the result in the hole.

**Comment by sattlerc** [comment]
I've lifted the restriction in the following pull request: https://github.com/agda/agda/pull/2673

**Comment by m0davis** [comment]
I don't see why you wouldn't simply use goal refinement, but maybe I misunderstand. Would you illustrate the practical use with a show of code before and after the case split?

**Comment by sattlerc** [comment]
There is a semantic difference between goal refinement and case splitting on the result for record types with no-eta-equality.

For an example, consider a pair type without eta equality:
```agda
record Pair (A B : Set) : Set where
  no-eta-equality
  field
    π₁ : A
    π₂ : B

open Pair
```
and suppose we want to write a function for distributing pairs over pairs:
```agda
distribute-pair : {A B C D : Set} → Pair (Pair A B) (Pair C D)
                                  → Pair (Pair A C) (Pair B D)
```
We want to implement the function in a way that avoids unnecessary term explosion, so we will not use goal refinement (C-c C-r introducing record constructors). Instead, we use co-patterns:
```agda
distribute-pair x .π₁ .π₁ = x .π₁ .π₁
distribute-pair x .π₁ .π₂ = x .π₂ .π₁
distribute-pair x .π₂ .π₁ = x .π₁ .π₂
distribute-pair x .π₂ .π₂ = x .π₂ .π₂
```
We can generate the above clauses by iteratively C-c C-c splitting on the result in the hole in `distribute-pair x = ?`.

Now suppose the preceding hole was not a top-level expression. Or suppose we wanted the clauses to share a where-declaration. Or perhaps we simply do not want the repeated clutter of `distribute-pair x [.π₁/.π₂]` (which in general could contain many arguments, some of which may additionally be case split). We can still give the definition in terms of extended lambdas:
```agda
distribute-pair x = λ where
  .π₁ → λ where
    .π₁ → x .π₁ .π₁
    .π₂ → x .π₂ .π₁
  .π₂ → λ where
    .π₁ → x .π₁ .π₂
    .π₂ → x .π₂ .π₂
```
Analogous to the previous way, we can generate the above extended lambdas by iteratively C-c C-c splitting on the result in the hole in `distribute-pair x = λ where → ?`. Or at least we could if discrimination against zero was not so widespread.
