### ISSUE TITLE
Auto fills hole with name of local function that is out of scope.

### ISSUE THREAD

**Issue by xekoukou** [agda/agda#2678]
If you ask 'auto' to fill the hole [here](https://github.com/xekoukou/sparrow/blob/0dd0444807737b1fb543e964f7e4558b35fd2654/agda/LinFunContructw.agda#L106) , it will fill it with : 
```
(.LinFunContruct.¬nho x s s₁ ieq ind ¬hob
```
which is the local function [here](https://github.com/xekoukou/sparrow/blob/0dd0444807737b1fb543e964f7e4558b35fd2654/agda/LinFunContruct.agda#L112)

instead of the body of that function : 
```
(λ x₁ → ¬hob (hitsAtLeastOnce←∧→←∧ x₁))
```

I am not sure if this is a new bug or not. It is not a big of a problem either. It just felt a bit strange to do so.

**Comment by gallais** [comment]
Sounds related to #1789: Auto will happily generate terms referring to out of scope names.
