### ISSUE TITLE
Internal error at "Typechecking/Abstract.hs:133" and "TypeChecking/Telescope.hs:68"

### ISSUE THREAD

**Issue by xekoukou** [agda/agda#2679]
I get an internal error [here](https://github.com/xekoukou/sparrow/blob/accc893b55bf3a37d7657a72ec9ac1e69f23636d/agda/LinFunContructw.agda#L116) : 

```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Abstract.hs:133
```
The error is [here](https://github.com/agda/agda/blob/master/src/full/Agda/TypeChecking/Abstract.hs#L133)

**Comment by gallais** [comment]
Does adding a type annotation for [`s` in this type signature](https://github.com/xekoukou/sparrow/blob/accc893b55bf3a37d7657a72ec9ac1e69f23636d/agda/LinFunContructw.agda#L22) make the error go away?

On shrunk test cases, it does for me and I don't have enough RAM to check the whole example myself (please consider spending some time shrinking your test cases).

Edit: I've pushed a [shrunk branch](https://github.com/gallais/sparrow/tree/shrinking-2679) based on the work I did for #2667. **It comes with another bug too** (the function [goo](https://github.com/gallais/sparrow/blob/shrinking-2679/agda/LinFunContructw.agda#L23)) which sparks:

> An internal error has occurred. Please report this as a bug.\nLocation of the error: src/full/Agda/TypeChecking/Telescope.hs:68\n"

**Comment by xekoukou** [comment]
No, it does not help if I add the type of s.

Don't ask me why but if I add a forth abstraction on the same ```with```, the error does go away.
```
  boo (s ←∧→ s₁) eq (ind ←∧) (∧→ lind) ¬hob ¬hoh ord with complLₛ s | inspect complLₛ s | complLₛ s₁ | inspect complLₛ s₁
  ... | g | t | e | q = ?
```

All four are needed to continue the proof because of the type of ord : 
```
ord  : Orderedᵢ
       (¬ho-shr-morph (s ←∧→ s₁) eq (ind ←∧) ¬hob | g | t | e)
       (¬ho-shr-morph (s ←∧→ s₁) eq (∧→ lind) ¬hoh | g | e | q)
```

**Comment by sattlerc** [comment]
Here is a self-contained test case:
```agda
postulate
  A : Set

data B (a : A) : Set where
  conB : B a → B a → B a 

data C (a : A) : B a → Set where
  conC : {bl br : B a} → C a bl → C a br → C a (conB bl br)

-- First bug.
{-
a !=<
"An internal error has occurred. Please report this as a bug.\nLocation of the error: src/full/Agda/TypeChecking/Telescope.hs:68\n"
of type A
when checking that the type
(a : A) (b : B a) (tl : C a (_16 a b)) →
C a (_16 a b) → (tr : C a (_17 a b)) → Set
of the generated with function is well-formed
-- Is there a contained error printing bug?
-}
goo : (a : A) (b : B a) (c : C a _) → Set
                                 -- giving b for _ resolves the error
goo a b (conC tl tr) with tl
... | _ = _

-- Second bug, likely same as first bug.
{-
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Abstract.hs:133
-}
data F : Set where
  conF : F

boo : (a : A) (b : B a) (c : C a _) → Set
boo a b (conC tl tr) with tr | conF
... | _ | _ = _
```

**Comment by sattlerc** [comment]
Should be labelled 'with'.

**Comment by sattlerc** [comment]
There is something seriously wrong.
```agda
postulate
  A : Set

data B (a : A) : Set where
  conB : B a → B a

data C (a : A) : B a → Set where
  conC : (b : B a) → C a (conB b)

goo : (a1 a2 a3 : A) (c : C a<n> _) → Set
goo a1 a2 a3 (conC b) = {!!}
```
For n : [1..3], the metavariable is not given type `B a<n>`, but `B a<n+2 mod 3>`.

**Comment by xekoukou** [comment]
Please, try to fix this. It keeps popping up and I do not know what to do, how to circumvent it.

**Comment by andreasabel** [comment]
Looks like a de Bruijn error in the unifier, possibly related to #2621.

In 2.4.2.6 or 2.5.1.1, I get instead an error:
```
Cannot instantiate the metavariable _10 to solution b since it
contains the variable b which is not in scope of the metavariable
or irrelevant in the metavariable but relevant in the solution
when checking that the pattern conC b has type
C a1 (conB (_10 a1 a2 a3))
```

**Comment by andreasabel** [comment]
@jespercockx : Do you have time to look at it now?

**Comment by jespercockx** [comment]
I'll take a look at it. Could have something to to with the higher-dimensional unification I added...

**Comment by jespercockx** [comment]
This is again a bug with instantiating metavariables during unification. It seems like a waste of time to try to fix this when we're planning to remove this feature (see #2621), so I'm adding a blocking tag.

**Comment by andreasabel** [comment]
The plan is to release 2.5.3 very soon now, but probably #2621 won't be fixed before the release!?  
The current behavior is a bit unsatisfactory, an error message would be better (previous behavior).
I would not like to release this bug.

**Comment by jespercockx** [comment]
How about instead going ahead with the fix for #2621 by just breaking the test case for `succeed/Issue1922.agda`? We can then continue to work on better type propagations for extended lambdas after the release.

**Comment by asr** [comment]
> I would not like to release this bug.

OK. For now I'll release a release candidate.

**Comment by jespercockx** [comment]
I finally managed to make my fix work without breaking the standard library. I pushed it to stable-2.5, so if there's still time you could add it to the release candidate (or otherwise to the actual release).

**Comment by asr** [comment]
Great! I will include the fix in the RC.
