### ISSUE TITLE
Travis fails on text-icu for ghc-7.8

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#2680]
Travis fails on `text-icu` for `ghc-7.8`. Is it possible to turn off the `enable-cluster-counting` flag for the `7.8` job?

**Comment by asr** [comment]
I couldn't reproduce the issue. Let's see if the above commit fix the problem...

Edited: Nope.

**Comment by asr** [comment]
I don't know why GHC 7.8.4 in Travis is using the wrong version of cabal-install. I'm doing some tests...

**Comment by gallais** [comment]
Is it because of this line `if [[ $CABAL_VER = "1.18" ]]; then cabal install cabal-install` that we pull in the more recent version 2.0 that was released recently and that the build fails later on?

**Comment by asr** [comment]
No, `cabal-install` 2.0.0.0 only brings up the problem.

Agda requires `cabal-install` >= 1.20 so we have

```
       export PATH=$HOME/.cabal/bin:$PATH &&
       if [[ $CABAL_VER = "1.18" ]]; then
          cabal install cabal-install &&
          cabal --version &&
       fi &&
```

Then `cabal --version` should report version 2.0.0.0 but it is reporting the initial version, i.e.
1.18.0.4. Before the release of `cabal-install` 2.0.0.0 the above situation was the same. Why the job was successful before `cabal-install` 2.0.0.0 if it is using 1.18.0.4? I don't know.
