### ISSUE TITLE
What are the rules for projections of abstract records?

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#2682]
I'm confused:
```agda
module _ where

module Abs where

  abstract
    record R : Set₁ where
      field X : Set

open Abs

works : R → Set
works r = R.X r

fails : R → Set
fails r = {!R.X r!}
-- On give:
-- Expected non-abstract record type, found R
-- when checking that the expression R.X r has type Set
```

**Comment by andreasabel** [comment]
Here, `CheckInternal`, which is invoked by `give`, catches the error that the type checker overlooks.

**Comment by andreasabel** [comment]
The question is whether fields of abstract records should be in scope outside of abstract blocks or not.  (Constructors are not in scope.)

There is some discussion at #580.  

At #759, I claimed
> Fixed. Abstract records are similar to abstract data types, i.e., constructors and fields are not in scope outside the abstract definitions.

but this either was not true or got lost over time.

**Comment by andreasabel** [comment]
In #2684, I did a refactoring of `getConstInfo` that allows for a better fix of the present issue.  We should converge on the rules for abstract projections.  There are two alternatives:

1. Treat projections like constructors, i.e., for an abstract record the projections are not in scope, like the constructors for a data type are not in scope.  (Seems to be the view taken at #759.)

2. Limit `abstract` to the constructor, i.e., only the constructor is not in scope and the record construction with `record{...}` is also forbidden.  (Seems to be the view taken at #580.)

**Comment by andreasabel** [comment]
Ah, I think we should stick to the current solution, 2.: only the constructor is abstract.
I'll fix `checkInternal`.

**Comment by nad** [comment]
Doesn't it make more sense to hide all implementation details?

**Comment by andreasabel** [comment]
Maybe the rationale for solution 2. is that abstract classes (in Java) still export their methods, even if you cannot construct objects of these classes.  Exporting the projections of an abstract record type feels similar: you cannot construct a record value, but you can get its components.

**Comment by UlfNorell** [comment]
One argument against is that projections are treated differently from ordinary functions, so if you were to change the implementation of the abstract record, making some or all projections ordinary functions, code using it might break. Most obvious breakage: copattern matching and postfix projections.

**Comment by andreasabel** [comment]
Both 1. and 2. are valid standpoints, but we are discussing things a bit in the air since we do not have any real life use cases that could guide us in the design, have we?  (I have only used `abstract` to make some definitions (like lemmata) opaque for efficiency reasons.)

**Comment by nad** [comment]
I have used `abstract` to hide implementation details, see my paper in POPL 2008.

**Comment by andreasabel** [comment]
Abstract records?  Where?

**Comment by nad** [comment]
I don't recall using abstract records, but I've used abstract to hide implementation details (rather than to improve performance).

I don't see a good argument for treating projections differently from constructors.

**Comment by andreasabel** [comment]
The actual bug has been fixed here.  Let's move the discussion to a new issue: #2715. (And a new milestone.)
