### ISSUE TITLE
test/interaction/CompilationWarnings does not run stably

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2685]
When I run the interaction testsuite, sometimes the following line is missing from the output, resulting in a (false) failure of the test case `test/interaction/CompilationWarnings`.
```
(agda2-info-action "*Type-checking*" "[1 of 2] Compiling MAlonzo.RTE ( MAlonzo/RTE.hs, MAlonzo/RTE.o ) " t)
```
Test was added by commit https://github.com/agda/agda/commit/04dfa8245bc9973f53d694de5a9e124e699a2787
CC: @fredrikNordvallForsberg 

See also #2657.

**Comment by fredrikNordvallForsberg** [comment]
Is https://github.com/agda/agda/commit/9dd886fd1048465f9ac450b03081f7f2cec2ef48 perhaps relevant here?

**Comment by andreasabel** [comment]
Yes, probably silencing the ghc output would fix this issue.

**Comment by fredrikNordvallForsberg** [comment]
We didn't delete the `MAlonzo` directory, which probably caused `MAlonzo.RTE` to not be recompiled sometimes. Can you confirm that this fixes the issue? If we still run into the problems mentioned in https://github.com/agda/agda/commit/9dd886fd1048465f9ac450b03081f7f2cec2ef48 we should maybe adopt the same solution as there.

**Comment by andreasabel** [comment]
I suppose this fixes the problem.  If I should notice the problem again, I will reopen this issue.
