### ISSUE TITLE
Travis fails on the internal-tests suite for GHC 7.8.4

### ISSUE THREAD

**Issue by asr** [agda/agda#2687]
The Travis [error]( https://www.travis-ci.org/agda/agda/jobs/263916571) is

```
[16 of 48] Compiling InternalTests.Syntax.Internal ( test/InternalTests/Syntax/Internal.hs, /home/travis/dist/build/internal-tests/internal-tests-tmp/InternalTests/Syntax/Internal.o )

test/InternalTests/Syntax/Internal.hs:61:26:

    No instance for (Eq NotBlocked) arising from a use of ‘isMonoid’
    In the expression: isMonoid
    In an equation for ‘prop_monoid_NotBlocked’:
        prop_monoid_NotBlocked = isMonoid
Failed to install Agda-2.5.3
```

I couldn't reproduce the error.

**Comment by UlfNorell** [comment]
You actually changed the `Eq` instance, ignoring the `Elim` in `StuckOn`. I'm not sure if this actually matters, but wouldn't a more conservative fix be to simply import `Agda.TypeChecking.Substitute` in `InternalTests.Syntax.Internal`?

**Comment by asr** [comment]
I considered that fix, but since my fix pass all the test and it doesn't require importing modules from the `TypeChecking` name space,  I used it.

**Comment by asr** [comment]
But you are right. I'll use the more conservative fix.

**Comment by UlfNorell** [comment]
Thank you.

**Comment by UlfNorell** [comment]
I feel a bit nit-picky, but why didn't you fix it by importing `Agda.TypeChecking.Substitute`? Now the property is using a different `Eq` instance (for `ghc > 7.8`) than the one in the actual code base.

It seems reasonable that if you want to test a property about the `Eq` and `Monoid` instances of a type, you import the modules where those instances are defined.

**Comment by asr** [comment]
I don't understand your comment because I fixed the issue by importing `Agda.TypeChecking.Substitute`. Note that the issue was fixed by 8de8380bbfc7540d289c836df5738f69b8f02a01.

**Comment by UlfNorell** [comment]
Oh, sorry. I was looking at a27b0e6, which it's telling me was the commit closing the issue.

**Comment by UlfNorell** [comment]
Oh, I see what happened. When you revert a commit with a `fixed #X` message it also closes the issue.
