### ISSUE TITLE
Missing support for version of the Win32 library shipped with GHC 8.2.1

### ISSUE THREAD

**Issue by asr** [agda/agda#2688]
The [Win32](https://hackage.haskell.org/package/Win32) library is shipped with GHC. The version of this library shipped in GHC 8.2.1 is 2.5.4.1 (see the [release notes](https://downloads.haskell.org/~ghc/8.2.1/docs/html/users_guide/8.2.1-notes.html)).

The current versions supported of this library are

```
  if os(windows)
    build-depends:  Win32 >= 2.2 && < 2.4
```

Could someone add the missing support for Win32 2.5.4.1, please.

**Comment by favonia** [comment]
~Maybe we could set up an AppVeyor CI or something to detect this. (Unfortunately I am not familiar with Windows.)~ Never mind. There is already an issue about this.

**Comment by UlfNorell** [comment]
I don't have `ghc-8.2.1` on my Windows VM, but the functions we are using from `Win32` (in `Agda.Utils.FileName`) have not changed between `Win32-2.4` and `Win32-2.5` so it's safe to simply bump the upper bound.

**Comment by asr** [comment]
> so it's safe to simply bump the upper bound.

Do it, please.

**Comment by asr** [comment]
Thanks!
