### ISSUE TITLE
`make internal-tests` is recompiling the Agda library

### ISSUE THREAD

**Issue by asr** [agda/agda#2689]
`make internal-tests` is recompiling the Agda library because this command and `make install-bin` use different Cabal flags. A principled solution is to migrate the `internal-tests` test-suite to the `agda-test` test-suite.

**Comment by andreasabel** [comment]
On my system, this does not happen (ghc-7.10, cabal-install-1.24).  Is this a feature of cabal-install-2.0?

**Comment by andreasabel** [comment]
Ah, sorry, it does:
```
cabal test internal-tests --builddir=./dist-2.5.3 -j4
Preprocessing library Agda-2.5.3...
Preprocessing test suite 'internal-tests' for Agda-2.5.3...
Running 1 test suites...
```
Depends what you mean by `recompiling`.  It is not actually recompiling anything if nothing has changed.

**Comment by asr** [comment]
By running

```
make install-bin
make internal-tests
```

I see the recompilation. You can also see the recompilation in Travis. For example, the log of [this](https://www.travis-ci.org/agda/agda/jobs/268326406) job shows the following output when running the `internal-tests` suite:

```
======================================================================
======================== Internal test suite =========================
======================================================================
cabal test internal-tests --builddir=/home/travis/dist -j2
Resolving dependencies...
Configuring Agda-2.5.3...
Preprocessing library for Agda-2.5.3..
Building library for Agda-2.5.3..
[  1 of 325] Compiling Agda.Interaction.Library.Base ( src/full/Agda/Interaction/Library/Base.hs, /home/travis/dist/build/Agda/Interaction/Library/Base.o )
[  2 of 325] Compiling Agda.Termination.CutOff ( src/full/Agda/Termination/CutOff.hs, /home/travis/dist/build/Agda/Termination/CutOff.o )
[  3 of 325] Compiling Agda.Termination.Semiring ( src/full/Agda/Termination/Semiring.hs, /home/travis/dist/build/Agda/Termination/Semiring.o )
[  4 of 325] Compiling Agda.Utils.BiMap ( src/full/Agda/Utils/BiMap.hs, /home/travis/dist/build/Agda/Utils/BiMap.o )
[  5 of 325] Compiling Agda.Utils.Char  ( src/full/Agda/Utils/Char.hs, /home/travis/dist/build/Agda/Utils/Char.o )
...
```

**Comment by nad** [comment]
With my setup the library is recompiled with profiling turned on. Perhaps Cabal decides to recompile because the configuration has changed. Can the problem be fixed by running `cabal configure` with suitable options before `cabal test` is run?
