### ISSUE TITLE
Splitting implicit variables: constructor beginning with `-`

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#269]
Integers (standard library) use a constructor of the shape `-[1+_]`. If the variable is implicit, destructing it provokes a parsing error (`{-` is the beginning of a commentary).

Fixing it by hand is only a temporary solution: the next pattern matching on a variable will undo it.

Code :
```agda
bug : ∀ {n : ℤ} → n ≡ n
bug {n} = {!!}
```
becomes :
```agda
bug : ∀ {n : ℤ} → n ≡ n
bug {-[1+ n ]} = ?
bug {+ n} = ?
```

Original issue reported on code.google.com by `sble...@gmail.com` on 13 May 2010 at 12:51

**Comment by andreasabel** [comment]
Closed by https://github.com/agda/agda/commit/8c85bb65b6e46e33f0fc8be517afaae230031b4b.
The other half of the problem (`-` last character of constructor) unearthed 8 years later (#3161).
