### ISSUE TITLE
Remove support for GHC 7.8.4

### ISSUE THREAD

**Issue by asr** [agda/agda#2692]
Agda 2.5.3 will require that users on Ubuntu 14.04 (which is shipped with GHC 7.6.3) use GHC back-ports. Since there are back-ports for GHC 7.10.3, why not also remove the support for GHC 7.8.4 in Agda 2.5.3? Note that the current Debian stable is shipped with GHC 8.0.1.

**Comment by andreasabel** [comment]
It seems like Ubuntu 16.04 (Xenial) comes with GHC 7.10.3.

But I see no advantage of removing support for GHC 7.8.4 for the imminent release of Agda 2.5.3. 
We could fade out 7.8.4 after the release.

**Comment by asr** [comment]
>  We could fade out 7.8.4 after the release.

OK.

**Comment by asr** [comment]
I could fix #2745 by fixing this issue but I want to wait at least two months for removing the support for GHC 7.8.4. I want to avoid that an user report an important regression and our bug-fix release (e.g. 2.5.3.1) requires that her use a different version of GHC.

**Comment by UlfNorell** [comment]
It's been almost 2 months now, so can we act on this?

Maintaining `7.8` compatibility is a constant pain due to the library changes in `7.10`. I count 8 commits fixing build failures on `7.8` in the last month alone.

Also, if there's a super serious regression we can always make a hot-fix release based on `2.5.3`.

**Comment by asr** [comment]
OK. I'll remove the support for GHC 7.8.4.

**Comment by andreasabel** [comment]
My take on this would have been to just disable the travis test and let the 7.8 support rot, rather than actively removing it.  But, well, ok.  (I am having a dejavu here, see #1972.)

**Comment by mietek** [comment]
Please consider that some of us are still stuck on GHC 7.8.4 because of business reasons.

**Comment by asr** [comment]
@mietek, note that you can revert f5b1b95946a8ac626ffc8fac1da0cd63ea6e6bb8 in your local repo. Are you using Ubuntu?

**Comment by mietek** [comment]
This is not a problem for my personal use, but rather a potential barrier for adoption of future Agda versions in an organisational context.  The organisation has standardised on Windows 7 and GHC 7.8.4, and it is unclear when upgrading will be possible.

I recognise that it is more important to ease future development than to support obsolete versions of GHC on obsolete operating systems.  However, I would repeat after @andreasabel that perhaps deprecating support would be sufficient.

**Comment by asr** [comment]
I don't understand how to deprecate the support would be sufficient in the organisational context. If we remove the CI for GHC 7.8.4 the next release won't support this version of GHC. Off the top of my head the first issue would be #2745.

**Comment by UlfNorell** [comment]
> The organisation has standardised on Windows 7 and GHC 7.8.4, and it is unclear when upgrading will be possible.

Why not stay on Agda 2.5.3 then? It seems strange that the organisation cannot possibly install a more recent ghc but require a bleeding edge Agda.

> I don't understand how to deprecate the support would be sufficient in the organisational context.

I agree. As soon as we stopped testing with ghc-7.8, Agda stopped building with ghc-7.8, and all the ifdefs for 7.8 were just dead code.

If you're serious about the deprecation path, I suggest you create a fork of Agda, revert f5b1b95946a8ac626ffc8fac1da0cd63ea6e6bb8, and deal with the 7.8 issues as they pop up.

**Comment by andreasabel** [comment]
> Why not stay on Agda 2.5.3 then?

This is hardly an option as we do not backport bugfixes.

I wonder whether we could keep 7.8 compatibility by building a big `Prelude` module which exports everything we need from `base` and other packages.  This module could provide the compatibility layer for things that change in `base` etc. over different `ghc` releases.
Of course, we could not use new `LANGUAGE` features of ghc.
