### ISSUE TITLE
Cubical status

### ISSUE THREAD

**Issue by asr** [agda/agda#2699]
@Saizan, is the cubical implementation ready for releasing? (I know an entry in the CHANGELOG is missing).

AFAIK the only difference between stable and master is the cubical implementation, so if cubical is ready, we can discuss about release from the master branch rather than the stable one.

**Comment by Saizan** [comment]
I would like to move some definitions from my cubical-demo repo into Agda.Builtin.* modules before releasing cubical, I plan to do that this week.

Would also be good to turn some of the demo code into Agda tests.

We should also do something about #2461 .

**Comment by UlfNorell** [comment]
Since we're trying to get this release out quickly (see the OP of #2659), I'd rather we release `2.5.3` first and then we can worry about getting cubical in shape for release.

**Comment by asr** [comment]
OK.

**Comment by andreasabel** [comment]
@Saizan : Before release, I suggest a code review session for the cubical additions, during which the following can be addressed

- [ ] source code documentation
- [ ] comprehensive regression tests covering the features of cubical

**Comment by Saizan** [comment]
@andreasabel : Sounds good, would we go over the code together, or?

**Comment by xekoukou** [comment]
Is the cubical implementation complete? 
It seems that HIT are not possible at the [moment](https://github.com/Saizan/cubical-demo/blob/master/Circle.agda#L8)

**Comment by Saizan** [comment]
@xekoukou it would still make sense to release without HITs.

However it might be that we also have HITs by that time.
