### ISSUE TITLE
Add a command to check against goal type (and normalise)

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#2700]
Use case: invoke instance search to find a solution to the current goal. You could then put `it` in the hole and invoke the command. With `it` defined as

```agda
it : ∀ {a} {A : Set a} {{x : A}} → A
it {{x}} = x
```

See #2172 for more discussion.

**Comment by gallais** [comment]
Can / should we make this part of 2.5.3?

**Comment by asr** [comment]
Yes. Please add the issue to the list of fixed issues in the CHANGELOG file and close the issue after it.
