### ISSUE TITLE
Regression: Internal error for underapplied indexed constructor

### ISSUE THREAD

**Issue by davdar** [agda/agda#2703]
Attached is the project which triggers the error. The error is in F.agda, which uses the included Core library. The reported error:

> An internal error has occurred. Please report this as a bug.
> Location of the error: src/full/Agda/TypeChecking/Datatypes.hs:76

[bug.zip](https://github.com/agda/agda/files/1232329/bug.zip)

**Comment by gallais** [comment]
Shrunk test case (I use `with` here but the original error showed up when using `rewrite`):

```agda
module _ where

module A where
  postulate a : Set

postulate
  cut : (T : Set) (P : T → Set) → (∀ t → A.a → P t) → Set

postulate T : Set
data P : T → Set where
  Var : ∀ t → A.a → P t

bug : cut T P Var
bug with _
... | _ = {!!}
```

**Comment by UlfNorell** [comment]
The code throwing the error was introduced recently by @andreasabel in 8afa335, when working on #1515 and #2384.

It looks wrong to me:

```haskell
  TelV tel t <- telView t
  -- Now @t@ lives under @tel@, we need to remove the dependency on @tel@.
  -- This will succeed if @t@ is indeed a data/record type that is the
  -- type of a constructor coming from a term
  -- (applied to at least the parameters).
  getFullyAppliedConType c $ applySubst (strengthenS __IMPOSSIBLE__ (size tel)) t
```

Here the original `t` is the type of a constructor `c`, partially or fully applied. The claim that the target type does not depend on the telescope is clearly not correct in the case of indexed data types.

We get the failure when calling `getConType` from `CheckInternal` when checking the type of the generated with-function.

**Comment by andreasabel** [comment]
Thanks @davdar @gallais @UlfNorell.  Here is a further shrunk test case:
```agda
-- Issue #2703
-- Underapplied constructor triggers internal error

postulate
  A : Set

data Sg : A → Set where
  sg : ∀ t → Sg t  -- Target type depends on constructor argument

postulate
  cut : (∀ t → Sg t) → Set

bug : cut sg  -- Underapplied constructor
bug with A
bug | _ = A
```

**Comment by andreasabel** [comment]
I wonder what is going wrong here.  Is the substitution applied eagerly?  I thought I can strengthen and only get the `__IMPOSSIBLE__` when I am actually strict on the impossible variable.

**Comment by UlfNorell** [comment]
> I thought I can strengthen and only get the __IMPOSSIBLE__ when I am actually strict on the impossible variable.

Yes, that should be the case.

**Comment by andreasabel** [comment]
Well then I don't understand the error.  All we want from the strengthened type is the datatype parameter, which should be well-scoped.  We ignore the indices which have the impossible variables.

Anyway, I am now trying to do the strengthening after the call to `getFullyAppliedConType` which is safer. 
The reason is that it is hard to debug terms with `__IMPOSSIBLE__`s inside.

**Comment by andreasabel** [comment]
I think I located the problem: It is the way we apply substitutions to `Def`s:
```haskell
instance Subst Term Term where
  applySubst rho t    = case t of
    Var i es    -> lookupS rho i `applyE` applySubst rho es
    ...
    Def f es    -> defApp f [] $ applySubst rho es

-- | @defApp f us vs@ applies @Def f us@ to further arguments @vs@,
--   eliminating top projection redexes.
--   If @us@ is not empty, we cannot have a projection redex, since
--   the record argument is the first one.
defApp :: QName -> Elims -> Elims -> Term
defApp f [] (Apply a : es) | Just v <- canProject f (unArg a)
  = argToDontCare v `applyE` es
defApp f es0 es = Def f $ es0 ++ es

-- | If $v$ is a record value, @canProject f v@
--   returns its field @f@.
canProject :: QName -> Term -> Maybe (Arg Term)
canProject f v =
  case ignoreSharing v of
    (Con (ConHead _ _ fs) _ vs) -> do
      i <- List.elemIndex f fs
      headMaybe (drop i vs)
    _ -> Nothing
```
In the particular case, `applySubst (StrengthenS...) (Def f var0)` will check whether `strengthen var0` is a record constructor with field `f`, and crashes.

Thus, my assumption about the laziness of substitution is wrong.

The workaround of my last comment fixes the present issue.  

However, to get the lazy behavior I imagined, we would have to store in `Def` whether the `QName` can be a record projection or not.  Anyway, I somehow feel that using `Def` for record and datatypes is not the best factoring.  (See also the numerous calls to `allApplyElims` we have as a consequence of the current structure.)
