### ISSUE TITLE
Interaction testcase for #983 does not run stably

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2704]
If my machine is quite busy, the test case for #983 fails.  Must be some race coditions, see the `sleep` instructions in the test script (below).  I wonder whether this test could be done without the sleep magic.
```bash
AGDA_BIN=$1
top=Issue983
bad=Issue983-Bad
lib=Issue983-Lib

pipe=$top.pipe

rm -f $pipe
mkfifo $pipe

# Forces the pipe to stay open. Otherwise it's closed by echo the first time we
# write to it.
sleep 2 > $pipe &
SLEEP_PID=$!

$AGDA_BIN --interaction < $pipe 2>&1 &

function cmd {
  echo "IOTCM \"$2.agda\" None Indirect (Cmd_$1 \"$2.agda\" $3)" > $pipe
}

# The library is empty
printf "\n" > $lib.agda

# So this won't work
printf "open import $lib\n"        > $bad.agda
printf "Bad = $lib.NonExisting\n" >> $bad.agda

# Load the library.
cmd load $lib []

# Now load $top. This jumps to the error in $bad.
cmd load $top []

# Loading the highlighting info for $bad. This looks in the moduleToSource map
# for $lib which should not cause an internal error!
cmd load_highlighting_info $bad

sleep 0.1
rm -f $pipe $lib.agda $lib.agdai $bad.agda

# Free the pipe to prevent weird errors on nfs file systems
kill $SLEEP_PID
wait $SLEEP_PID 2>/dev/null
```

**Comment by UlfNorell** [comment]
One might also ask the question whether it's worth keeping the test at all if it doesn't succeed reliably. Do we think it's likely it will catch some future bug?

**Comment by andreasabel** [comment]
It is not too bad to keep it.  If it fails, I will accept the new output and then run the testsuite again.  Usually the old output comes back then.  However, this test might also cause problems on travis.

So far we have no tool to justify the usefulness of our test cases.  We do not keep a history of failing test cases.  (This one would even distort the usefulness measure.)  Our test cases are random points which owe their existence to a previous bug.    

Even if many test cases may not prevent future bugs, it is reassuring that they keep the old bugs out.

**Comment by UlfNorell** [comment]
Of course we shouldn't throw out tests for no reason, but if it takes a continuous effort (restarting Travis builds, rerunning the test suite) to keep it, I don't think the benefits justify the costs.

**Comment by asr** [comment]
I don't recall to restart a Travis job due to this test case.

**Comment by UlfNorell** [comment]
Neither do I. Nor can I remember it failing on my machine. I'm just saying that removing it is a valid option if it's causing problems.

**Comment by andreasabel** [comment]
@nad: It seems you did work to fix this in 9bb868bc460af564b02a6e4b29e8182dc8824519 ?!

**Comment by nad** [comment]
No, I had forgotten about this issue. Is it fixed now?

**Comment by andreasabel** [comment]
Optimistically, I would assume yes, since you completely changed the code.
I close it, and reopen if I comes back.
