### ISSUE TITLE
The GHC backend might diverge in infinite file creation

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2705]
To produce this bug with Agda-2.5.3 and ghc-7.10.3:
```sh
cd $HOME/.cabal/share/x86_64-linux-ghc-7.10.3/Agda-2.5.3/MAlonzo/src/MAlonzo
touch Bla.agda
agda-2.5.3 --compile Bla.agda
```
This will attempt to copy the contents of
```
$HOME/.cabal/share/x86_64-linux-ghc-7.10.3/Agda-2.5.3/MAlonzo/src
```
into 
```
$HOME/.cabal/share/x86_64-linux-ghc-7.10.3/Agda-2.5.3/MAlonzo/src/MAlonzo
```
and, due to the implementation of `Agda.Utils.IO.Directory.copyDirContent`, produce an infinitely deep tree containing
`MAlonzo/MAlonzo/MAlonzo...`.
The problem is that `copyDirContent A A/B` exhibits this behavior; there should be a check that the source and target directories are disjoint.  (Klingeling, separation logic!) 

NB: I found this bug by haddockumenting `Agda.Utils.IO.Directory` over which I stumbled by accident.  No one in his right mind would put his Agda project in `$HOME/.cabal/share/x86_64-linux-ghc-7.10.3/Agda-2.5.3/MAlonzo/src`.  However, if that happened, the consequences could be devastating (full harddrive, unresponsible system).  I am not eager to try out. :D

**Comment by identicalsnowflake** [comment]
> due to the implementation of Agda.Utils.IO.Directory.copyDirContent, produce an infinitely deep tree containing `MAlonzo/MAlonzo/MAlonzo....`

It seems like we just need a coinductive file system.

**Comment by andreasabel** [comment]
Well, a safe implementation would first make a list of files to be copied, and then do the copying.  I looked for package on hackage, and found
* https://hackage.haskell.org/package/fsutils-0.1.2/docs/src/System-Path.html#copyDir 
  correct implementation, but package seems dead (last commit 2012)
* https://hackage.haskell.org/package/filesystem-trees
  has a `copyTo` function.  Last commit in 2015.
* https://hackage.haskell.org/package/directory-tree 
  not directly a copyDir function, but well-maintained

However, just before the release we should not depend on a new package.

**Comment by andreasabel** [comment]
I am fixing this by refactoring the existing code of `copyDirContent` into two phases:
1. Create a TODO list.
2. Execute the TODO list.

Now, we still get slightly stupid behavior of MAlonzo, but there is no risk of filling your harddrive with an infinite tree.
```sh
~/.cabal/share/x86_64-linux-ghc-7.10.3/Agda-2.5.3/MAlonzo/src/MAlonzo
$ tree
.
├── Bla.agda
├── Bla.agdai
└── RTE.hs
$ agda-2.5.3 --compile Bla.agda
...
$ tree
.
├── Bla.agda
├── Bla.agdai
├── MAlonzo
│   ├── Bla.agda
│   ├── Bla.agdai
│   ├── Code
│   │   ├── Agda
│   │   │   └── Primitive.hs
│   │   ├── Bla.hi
│   │   ├── Bla.hs
│   │   └── Bla.o
│   ├── MAlonzo
│   │   └── Code
│   │       ├── Agda
│   │       │   └── Primitive.hs
│   │       └── Bla.hs
│   ├── RTE.hi
│   ├── RTE.hs
│   └── RTE.o
└── RTE.hs
```
Things have been copied twice, but who cares, this bug is very unlikely to surface in the wild.
