### ISSUE TITLE
Bump QuickCheck to latest version (after release)

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2707]
I realized that QuickCheck-2.10 (or something > 2.8.2) has the intelligence to run a `Bool` test only once, not a 100 times.

We should bump the QuickCheck dependency after the release, it builds stably with all ghc versions >= 7.4, see https://matrix.hackage.haskell.org/package/QuickCheck .

**Comment by asr** [comment]
Since QuickCheck is only used in the `internal-tests` test-suite and the tests-suites are not included in the release, you can bump the QuickCheck dependency now.

**Comment by asr** [comment]
Please note that the comment 

```
-- QuickCheck 2.8.2 is required by the current
-- Stackage LTS (7.13).
```

in `Agda.cabal` is outdated because we are not  including the tests-suites when testing Agda on Stackage via Travis.

**Comment by UlfNorell** [comment]
Misstagged the commit. Should have been #2709.
