### ISSUE TITLE
Type checker hangs

### ISSUE THREAD

**Issue by kevinclancy** [agda/agda#2710]
When I try to load Typecheck.agda in the following project, the Agda compiler gets stuck while type checking. Uses Agda 2.5.2 and standard library 0.13.

https://github.com/kevinclancy/agda-hang

**Comment by gallais** [comment]
2.5.2 seems to spend an awful lot of time on `intT`. Maybe a type annotation could help?

2.6.0 quickly finds a type error line 284:

> /home/gallais/projects/others/agda-hang/Typecheck.agda:284,50-51
ℕ !=< (Γ (_m_1299 Γ₀)) of type Set
when checking that the expression m has type Γ (_m_1299 Γ₀)

**Comment by kevinclancy** [comment]
Thanks. I updated to 2.6.0 and continued working until running into another hang. I have pushed the new version to the agda-hang repo. Once again, type checking Typechecker.agda causes a hang.

I believe that the problem emerged after making some of the arguments of my weakenBy functions implicit.
What compiler options should I set to easily identify which pieces of code are causing type checker performance issues? Verbosity?

**Comment by gallais** [comment]
In emacs, you can type `M-x customize-group RET agda2-highlight` and pick `Interactive` in the `Agda2 Highlight Level` option. You will then see a green background move through the file as it is getting typechecked. If it spends a lot of time on a definition that's because typechecking that definition takes a lot of time.

**Comment by UlfNorell** [comment]
What happens is that the meta in the rhs of `weaken1-T` gets solved with `T↑∞ (weaken1-T Γ₀ T₀ T₁))` causing the divergence. This ought to be caught by the meta occurs check, so I'm not sure what's going wrong.

**Comment by UlfNorell** [comment]
The reason is that meta occurs check does not look inside definitions for interaction points. See #589.

Note that you can also provoke the loop by defining `weaken1-T  Γ₀ T₀ T₁ = T↑∞ (weaken1-T Γ₀ T₀ T₁))`  directly. That would be an instance of #42.

**Comment by UlfNorell** [comment]
Better solution of #589 would be to only disable the recursion check when giving/refining and not when the type checker instantiates an interaction point.
