### ISSUE TITLE
Compiler Pragma for headers

### ISSUE THREAD

**Issue by gallais** [agda/agda#2712]
Following @nad's suggestion in #2444, I open a standalone issue:

Is there a way to turn some language extensions on in the generated code from inside Agda? E.g. I'd like `PackageImports`. If I use:

```agda
module Example where

{-# FOREIGN GHC {-# LANGUAGE PackageImports #-} #-}
```

then I get

```haskell
{-# LANGUAGE EmptyDataDecls, ExistentialQuantification,
             ScopedTypeVariables, NoMonomorphismRestriction, Rank2Types,
             PatternSynonyms #-}
module MAlonzo.Code.Example where

import MAlonzo.RTE (coe, erased, addInt, subInt, mulInt, quotInt,
                    remInt, geqInt, ltInt, eqInt, eqFloat)
import qualified MAlonzo.RTE
import qualified Data.Text

{-# LANGUAGE PackageImports #-}
```

and the `LANGUAGE` pragma is just ignored by ghc.

**Comment by andreasabel** [comment]
It seems natural to try to make this work:
```agda
{-# FOREIGN GHC {-# LANGUAGE PackageImports #-} #-}

module Issue2712 where
```
which currently gives a
```
Illegal declaration(s) before top-level module
```
error.

- [ ] Allow `ForeignPragma` before module header
- [ ] Remember in `stForeignCode` which FOREIGN pragmas occured before the module header.
- [ ] Put those before the Haskell module header when generating Haskell code.

**Comment by andreasabel** [comment]
Short testcase:
```agda
{-# FOREIGN GHC {-# LANGUAGE TupleSections #-} #-}

module Issue2712 where

postulate
  Pair : (A B : Set) → Set
  pair : {A B : Set} → A → B → Pair A B

{-# COMPILE GHC Pair = (,) #-}
{-# COMPILE GHC pair = \ a b -> (a,) b #-}
```
Should not raise error:
```
Compilation error:

/home/abel/tmp/agda/test/bugs/MAlonzo/Code/Issue2712.hs:18:16:
    Illegal tuple section: use TupleSections
```

**Comment by andreasabel** [comment]
Alternatively, we could keep the old order
```agda
module Issue2712 where

{-# FOREIGN GHC {-# LANGUAGE TupleSections #-} #-}

postulate
  Pair : (A B : Set) → Set
  pair : {A B : Set} → A → B → Pair A B

{-# COMPILE GHC Pair = (,) #-}
{-# COMPILE GHC pair = \ a b -> (a,) b #-}
```
and just print the LANGUAGE pragmas in the correct position in the Haskell file.

**Comment by UlfNorell** [comment]
We already have logic like this in place for imports, which need to go at a particular place in the Haskell file. See `Agda.Compiler.MAlonzo.Pragmas.isImport` and its uses.

**Comment by andreasabel** [comment]
I looked at this.  We can do the same for _file-header pragmas_, see https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#pragmas

In general, I was a bit surprised to see that foreign code is just printed as two blobs (imports, non-imports) and not in the order and position as they appear in the Agda source.  But it seems that this is fine, as Haskell does not have context-sensitive pragmas in the way Agda has (or these are not usable anyway, since the Haskell name of an Agda function is not predictable).

**Comment by andreasabel** [comment]
The correct test case is:
```agda
module Issue2712 where

{-# FOREIGN GHC {-# LANGUAGE TupleSections #-} #-}

postulate
  Pair : (A B : Set) → Set
  pair : {A B : Set} → A → B → Pair A B

{-# COMPILE GHC Pair = type (,)            #-}
{-# COMPILE GHC pair = \ _ _ a b -> (a,) b #-}  -- Test the availability of TupleSections
```

**Comment by andreasabel** [comment]
CHANGELOG entry:
> The GHC file header pragmas `LANGUAGE`, `OPTIONS_GHC`, and `INCLUDE` inside a `FOREIGN GHC` pragma are recognized and printed correctly at the top of the generated Haskell file.

**Comment by andreasabel** [comment]
Closed by https://github.com/agda/agda/commit/49c5c7d95475cd700a02dd822217c6d65ad535bc .
