### ISSUE TITLE
Decouple the LaTeX and HTML backend tests

### ISSUE THREAD

**Issue by gallais** [agda/agda#2716]
At the moment it is impossible to run either one or the other: there is only one make target for both.

```Make
.PHONY : latex-html-test
latex-html-test :
	@echo "======================================================================"
	@echo "=========== Suite of tests for the LaTeX and HTML backends ==========="
	@echo "======================================================================"
	@AGDA_BIN=$(AGDA_BIN) $(AGDA_TESTS_BIN) $(AGDA_TESTS_OPTIONS) --regex-include all/LaTeXAndHTML
```

**Comment by andreasabel** [comment]
I think this can be solved by either:
1. defining additional `TestTree`s outside the `all` tree which then can be invoked through the `Makefile`.
2. breaking the `LaTeXAndHtml` tree into subtrees.

Option 2. would be very easy to implement, but would change the order of test.  Currently, the `HTML`, `LaTeX`, and `QuickLaTeX` test are run together per file.  For option 1. we would run first the `HTML` tests, then `LaTeX`, and then `QuickLaTeX`.

I did not design this test, thus, I do not know what the considerations were whether to order tests by kind (html, LaTeX...) or by file.

It seems we would not lose much if we reorder them by kind.  If you are interested in the results for a certain new test case only, you can break the individual test runs (html, latex) after the file has been reached.

**Comment by andreasabel** [comment]
I am going for additional test trees inside `all` with the names `HTMLOnly`, `LaTeXOnly`, and `QuickLaTeXOnly`.  It turned out the `all` tree is never used in its entirety, thus, it is fine to add groups with redundant tests there.

**Comment by andreasabel** [comment]
Done: new `Makefile` targets:
```
make html-test
make latex-test
make quicklatex-test
```
