### ISSUE TITLE
internal error at DisplayForm.hs:197

### ISSUE THREAD

**Issue by m0davis** [agda/agda#2717]
I've managed to trigger an internal error when the verbosity is set to 100.
```agda
{-# OPTIONS -v 100 #-}

module AgdaErrorDisplayForm197 (A : Set) where

module M (_ : Set) where
  data D (n : Set) : Set where
    d : D n

open M A
```
The error message is

    An internal error has occurred. Please report this as a bug.
    Location of the error: src/full/Agda/TypeChecking/DisplayForm.hs:197

The last line in the debug window is

    displayForm for AgdaErrorDisplayForm197.M.D: 
      context = [CtxId 126,CtxId 125,CtxId 26], 
      dfs = [Local AgdaErrorDisplayForm197 (Display {dfFreeVars = 0, dfPats = [Apply ru(Var 1 []),Apply ru(Var 1 [])], dfRHS = DTerm (Def AgdaErrorDisplayForm197._.D [Apply ru(Var 0 [])])})]

**Comment by andreasabel** [comment]
Works with agda-2.5.2.

**Comment by andreasabel** [comment]
Thanks for reporting!  This regression was likely introduced by the fix of #2590.

**Comment by UlfNorell** [comment]
The minimal verbosity required to trigger the error is `-v tc.display.top:100 -v tc.polarity.dep:20` if you want to reduce unnecessary output from the test case.

**Comment by andreasabel** [comment]
Ok, can please update `test/Succeed/Issue2717.agda` accordingly?  I cannot test these bounds anymore... 
(You can also zap the garbage comment at the end of the file.)

**Comment by UlfNorell** [comment]
Done.
