### ISSUE TITLE
Unreachable clauses in definition by copattern matching trip clause compiler

### ISSUE THREAD

**Issue by Saizan** [agda/agda#2723]
I guess we should get some kind of error message from a definition like ```foo```
```agda
    record Test : Set1 where
      field
	one two : Set
    open Test
    foo : Test
    foo .one = { }1
    foo = { }
    foo .two = ?
```

**Comment by andreasabel** [comment]
Related: #1986.

**Comment by andreasabel** [comment]
With `{-# OPTIONS --warning=error #-}` you get
```
Unreachable clause
when checking the definition of foo
```
Maybe a principled fix would be to mark unreachable clauses as such and leave them out of the clause compilation.

**Comment by andreasabel** [comment]
I implemented this fix (rather than making the clause compiler work correctly also in case of unreachable clauses).  Related: #424.
