### ISSUE TITLE
File names for generated HTML files

### ISSUE THREAD

**Issue by nad** [agda/agda#2725]
How should top-level module names containing non-ASCII characters be handled by the HTML backend? If we have a module called `Σ`, then we currently (using the code on the Issue2604 branch) generate proper links to a file called `Σ.html`. The generated HTML is placed in a file called `Σ.html`, but for file systems without a specified character encoding this could be problematic. I suggest that we use `Network.URI.Encode.encode` to encode the generated file names (this means that the URLs will be encoded twice). Note that this encoding does not modify `A`-`Z`, `a`-`z`, `0`-`9`, `-`, or `.`.

I don't think that we should try to accommodate case-sensitive file systems.

**Comment by nad** [comment]
I have fixed this issue, as outlined above, on the Issue2604 branch.

**Comment by UlfNorell** [comment]
Why is the Issue2604 branch not merged?

**Comment by nad** [comment]
> Why is the Issue2604 branch not merged?

Because Issue #2604 wasn't (and still isn't?) fully resolved, and it was (is?) unclear whether the new feature should be part of Agda 2.5.3 or not.
