### ISSUE TITLE
Old regression related to with

### ISSUE THREAD

**Issue by nad** [agda/agda#2726]
Consider the following code:
```agda
module Bug (A : Set) where

record R : Set where
  data D : Set where

open R (record {})

F : D → Set₃
F _ with Set₁
F _ | _ = Set₂
```
Agda 2.3.2.2 accepts this code. Agda 2.4.0.2 rejects it with the following error message:
```
Expected a hidden argument, but found a visible argument
when checking that the type Set₂ → (_ : D) → Set₃ of the generated
with function is well-formed
```
Agda 2.6.0-439fe3e rejects the code with a similar error message:
```
Expected a hidden argument, but found a visible argument
when checking that the type Set₂ → (A : Set) (x : R.D _) → Set₃ of
the generated with function is well-formed
```
Given that all three versions of Agda accept the code if `D` is moved to the top-level I assume that the code should be accepted.

**Comment by andreasabel** [comment]
It looks like this is the same problem as #2727.
