### ISSUE TITLE
Internal errors related to rewrite

### ISSUE THREAD

**Issue by nad** [agda/agda#2727]
Consider the following code:
```agda
module _ (A : Set) where

open import Agda.Builtin.Equality using (_≡_; refl)

record R : Set where
  data D : Set where

open R (record {})

postulate
  x : A

F : D → Set₁
F _ rewrite refl {x = x} = Set
```
This code triggers an internal error:
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Abstract.hs:133
```
This is a regression. Agda 2.5.2 accepts the code.

The following code, which is also accepted by Agda 2.5.2, triggers a different internal error:
```agda
open import Agda.Builtin.Equality using (_≡_; refl)

record ⊤ : Set where
  no-eta-equality
  constructor tt

data Box (A : Set) : Set where
  [_] : A → Box A

Unit : Set
Unit = Box ⊤

F : Unit → Set → Set
F [ _ ] x = x

G : {P : Unit → Set} → ((x : ⊤) → P [ x ]) → ((x : Unit) → P x)
G f [ x ] = f x

record R : Set₁ where
  no-eta-equality
  field
    f : (x : Unit) → Box (F x ⊤)

  data ⊥ : Set where

r : R
r = record { f = G [_] }

open R r

H : ⊥ → Set₁
H _ rewrite refl {x = tt} = Set
```
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Datatypes.hs:87
```

**Comment by nad** [comment]
Bisection with the first piece of code above points to @andreasabel's commit c46725e6b755cfc1fd42b916d841641d9e4ce892:
```
$ agda-bisect --bad HEAD --good v2.5.2 --log log --compiler <ghc-7.10.3> --cabal-option --cabal-lib-version=1.23.1.0 Bug.agda
[...]
c46725e6b755cfc1fd42b916d841641d9e4ce892 is the first bad commit
commit c46725e6b755cfc1fd42b916d841641d9e4ce892
Author: Andreas Abel <andreas.abel@ifi.lmu.de>
Date:   Wed Jan 11 17:04:44 2017 +0100

    Simplification for #2386, re #1110 #520 #1740: redundant test for refl-rewrite

[...]
```
My guess is that this commit did not introduce the underlying problem.

We can replace `rewrite` by `with`:
```agda
F : D → Set₁
F _ with refl {x = x}
... | _ = Set
```
In this case Agda 2.5.1 triggers an internal error. If a suitable implementation of `Agda.Builtin.Equality` is provided, then Agda 2.4.2.2 gives the following error (note the similarity to the errors listed in #2726):
```
Expected a hidden argument, but found a visible argument
when checking that the type x ≡ x → (_ : D) → Set₁ of the generated
with function is well-formed
```

A similar replacement can be performed in the second piece of code above:
```agda
H : ⊥ → Set₁
H _ with refl {x = tt}
... | _ = Set
```
In this case Agda 2.6.0-439fe3e triggers an internal error, while Agda 2.5.2 accepts the code.

**Comment by nad** [comment]
When I used the second piece of code, with `with` instead of `rewrite`, bisection pointed to @andreasabel's commit 07c52b9a43d29d3a71dbc3422a00039df76fd158:
> Re #1515 refactor checkInternal Con to not fully apply constructor
>
> There was an unnecessary detour. The optimization makes the code simpler.
>
> In practice, most constructors should be fully applied, so I do not
> expect a great impact of this refactoring.

**Comment by nad** [comment]
If this commit is reverted, then `make test` succeeds, and some of the test cases above are accepted. Status summary:
* Internal error, `Agda/TypeChecking/Abstract.hs:133` (accepted by Agda 2.5.2):

  ```agda
  module _ (A : Set) where

  open import Agda.Builtin.Equality using (_≡_; refl)

  record R : Set where
    data D : Set where

  open R (record {})

  postulate
    x : A

  F : D → Set₁
  F _ rewrite refl {x = x} = Set
  ```
* Internal error, `Agda/TypeChecking/Abstract.hs:133` (internal error also for Agda 2.5.1, Agda 2.4.2.2 gives a type error that is similar to the errors listed in Issue #2726):

  ```agda
  module _ (A : Set) where

  open import Agda.Builtin.Equality using (_≡_; refl)

  record R : Set where
    data D : Set where

  open R (record {})

  postulate
    x : A

  F : D → Set₁
  F _ with refl {x = x}
  ... | _ = Set
  ```
* Accepted:

  ```agda
  open import Agda.Builtin.Equality using (_≡_; refl)

  record ⊤ : Set where
    no-eta-equality
    constructor tt

  data Box (A : Set) : Set where
    [_] : A → Box A

  Unit : Set
  Unit = Box ⊤

  F : Unit → Set → Set
  F [ _ ] x = x

  G : {P : Unit → Set} → ((x : ⊤) → P [ x ]) → ((x : Unit) → P x)
  G f [ x ] = f x

  record R : Set₁ where
    no-eta-equality
    field
      f : (x : Unit) → Box (F x ⊤)

    data ⊥ : Set where

  r : R
  r = record { f = G [_] }

  open R r

  H : ⊥ → Set₁
  H _ rewrite refl {x = tt} = Set
  ```
* Accepted:

  ```agda
  open import Agda.Builtin.Equality using (_≡_; refl)

  record ⊤ : Set where
    no-eta-equality
    constructor tt

  data Box (A : Set) : Set where
    [_] : A → Box A

  Unit : Set
  Unit = Box ⊤

  F : Unit → Set → Set
  F [ _ ] x = x

  G : {P : Unit → Set} → ((x : ⊤) → P [ x ]) → ((x : Unit) → P x)
  G f [ x ] = f x

  record R : Set₁ where
    no-eta-equality
    field
      f : (x : Unit) → Box (F x ⊤)

    data ⊥ : Set where

  r : R
  r = record { f = G [_] }

  open R r

  H : ⊥ → Set₁
  H _ with refl {x = tt}
  ... | _ = Set
  ```

**Comment by nad** [comment]
I reverted (parts of) the commit listed above. I'm not familiar with this part of the code base, but the commit is marked as a refactoring, so I assume that it was intended to be semantics-preserving.

@andreasabel, I wonder if your commit uncovered some broken invariant, caused by a bug in another part of the code.

**Comment by nad** [comment]
The following command can perhaps be used to track down a commit that can be blamed for the internal error that was introduced in Agda 2.5.1:
```
agda-bisect --compiler <ghc-7.10.3> --cabal-option --cabal-lib-version=1.23.1.0 --log log --good 2.4.2.5 --bad 2.5.1 --must-fail --no-internal-error Bug.agda
```
`Bug.agda`:
```agda
module _ (A : Set) where

data _≡_ {A : Set} (x : A) : A → Set where
  refl : x ≡ x

record R : Set where
  data D : Set where

open R (record {})

postulate
  x : A

F : D → Set₁
F _ with refl {x = x}
... | _ = Set
```

**Comment by andreasabel** [comment]
@nad thanks for doing the analysis.  Btw: Along these lines, I also caused regression #2703.  In that case it was because strengthening with our hereditary substitutions is stricter than strengthening with ordinary substitutions. (We are more strict than necessary because of how we implement the projection reduction.)

**Comment by nad** [comment]
> The following command can perhaps be used to track down a commit that can be blamed for the internal error that was introduced in Agda 2.5.1:

It points to 4a849c4404ef78a57bfebf75516b82e8ed8df59d, committed by @UlfNorell:
> [ fixed #745 ] properly keep track of types and contexts
>
> The new type-based with-abstraction requires you to keep better
> track of types and contexts. This necessitated reverting the aggressive
> with behaviour (d8b1317).

**Comment by andreasabel** [comment]
CheckInternal is unforgiving with wrong hiding information.  It has uncovered sloppy hiding information before.  In principle, each use `defaultArg` or `defaultDom` is a suspect.  Issue #2668 could be related.

**Comment by andreasabel** [comment]
There seems to be some bug with the visibility of module parameters.  For instance, why is the following type-correct?
```agda
module _ where

module M (A : Set) where
  record R : Set where
    data D : Set where

postulate
  A : Set

open M.R {A = A} (record {})

test = M.R.D {A = A} _
```
Shouldn't both `M.R` and `M.R.D` take `A` as visible parameter?

Agda-2.4.2.5 rejects this:
```
$ agda-2.4.2.5 Issue2727-a.agda
...
The arguments to M.R do not fit the telescope
(A₁ : Set) .(: M.R A₁)
when checking the module application
module _ = M.R {A = A} (record {})
```
I thought module parameters only get abstracted hidden in constructors and fields, not in record modules and other definitions in a record module.

Maybe we changed that, but then there is clearly a ill-formed term internally (what is printed as `R.D _`):  `Def Issue2727.R.D [Apply ru(Var 0 []),Apply .u(Con (ConHead {conName = Issue2727.recCon-NOT-PRINTED, conInductive = inductive, conFields = []}) ConORec [])]})`
It must be that the type checker already screws up the internal representation of type `D`.
Indeed, `freeVarsToApply` gives for `D` a visible `var 0`, not a hidden one.

**Comment by andreasabel** [comment]
Module application seems to be buggy (hello #892 and 7d3036bb9640720973f7acf94302babb339dd90c ?):
```
adding constant Issue2727.R.D to signature
lambda-lifted definition =
  Defn {
    defName           = Issue2727.R.D
    defType           = {A : Set} -> (r : Issue2727.R @0) -> Set
adding constant Issue2727._.D to signature
lambda-lifted definition =
  Defn {
    defName           = Issue2727._.D
    defType           = (A : Set) -> Set
```
Suddenly, the hidden `A` becomes visible again.

**Comment by andreasabel** [comment]
Internally, in `checkSectionApplication'` the argument vector for module `R` is computed with the wrong hiding:
```
addSection Issue2727._ (A : Set)
applySection Issue2727._ = R A _
```
I think to blame is the call to `moduleParamsToApply`:
```haskell
    -- Get the correct parameter telescope of @m2@.
    tel <- lookupSection m2
    vs  <- moduleParamsToApply $ qnameModule $ mnameToQName m2
```
`moduleParamsToApply` should return a hidden `A` but returns a visible `A`, since it take the parameter telescope of the top-level module `Issue2727` instead of considering the necessary modification to the hiding for `Issue2727.R`.
```
computing module parameters of Issue2727
  n    = 1
  cxt  = [ru(A)]
  sub  = IdS
  args = [ru(Var 0 [])]
```
The `vs` needs to be computed differently, imho.  @UlfNorell ?

**Comment by UlfNorell** [comment]
> I thought module parameters only get abstracted hidden in constructors and fields, not in record modules and other definitions in a record module.

Also in record modules. The rationale is that it shouldn't matter if you say

```agda
record R (A : Set) : Set where ...
```
or
```agda
module _ (A : Set) where
  record R : Set where ...
```
In both cases the parameter `A` is hidden in the record module telescope. See #1759. This has been the semantics since `2.5.1`.

**Comment by UlfNorell** [comment]
> Internally, in checkSectionApplication' the argument vector for module R is computed with the wrong hiding.
> ...
> The vs needs to be computed differently, imho. @UlfNorell ?

Yes, I think that's the problem.

**Comment by andreasabel** [comment]
> See #1759. This has been the semantics since 2.5.1.

Ah, yes, remembrance comes back.  I was trying to find this information in the documentation, at http://agda.readthedocs.io/en/v2.5.2/language/module-system.html#parameterised-modules, but it does explain what the effect of module parameters is on module contents other than functions (it is different to functions for records and data now).

**Comment by UlfNorell** [comment]
```haskell
-- Get the correct parameter telescope of @m2@.
tel <- lookupSection m2
vs  <- moduleParamsToApply $ qnameModule $ mnameToQName m2
```

I think the problem is simply that we're getting the module parameters for the wrong module. The code above gets the module parameters for the *parent* of `m2`, but it should  get the parameters for `m2` itself:

```haskell
-- Get the correct parameter telescope of @m2@.
tel <- lookupSection m2
vs  <- moduleParamsToApply m2
```

That is after all the module we're applying. Test suite running now, but this at least makes the test cases above go through.

**Comment by nad** [comment]
Did your commit also fix #2726?

**Comment by UlfNorell** [comment]
Yes.

**Comment by andreasabel** [comment]
@nad: Can you partially revert ccc6da275689e3f71540fdcf181d6335f43aa593 (keeping the test case) now without breaking anything?

**Comment by andreasabel** [comment]
@UlfNorell : Can you please leave in the source an argument why you think the new computation of the module telescope is correct, including hiding info etc.?  It said before
```haskell
-- Get the correct parameter telescope of @m2@.
```
but it was not correct.  Please argue (in comments) why this is correct now.  The (internal) reasoning that lead to this code should be somehow understandable by reading the comments.

**Comment by UlfNorell** [comment]
I added a comment. There isn't really any argument to be made for the hiding information at that point though. The section telescope should (does) have the right hiding already.

The changes in ccc6da2 cannot be reverted without breaking the test cases (causes internal error at `TypeChecking.Rules.Datatypes:87`).

**Comment by andreasabel** [comment]
Ok, I will have to look at this later.
