### ISSUE TITLE
Bad interaction between caching and the warning machinery

### ISSUE THREAD

**Issue by nad** [agda/agda#2728]
Turn on caching and load the following code:
```agda
record R : Set where
  infix 0 _+_
```
Result:
```
The following names are not declared in the same scope as their
syntax or fixity declaration (i.e., either not in scope at all,
imported from another module, or declared in a super module): _+_
```
Edit the code:
```agda
record R : Set where
```
Reload:
```
The following names are not declared in the same scope as their
syntax or fixity declaration (i.e., either not in scope at all,
imported from another module, or declared in a super module): _+_
```

This is a regression. Bisection suggests that this bug was introduced by @andreasabel in 76dabd25e3d41fb0bda0b02e47a21aafddd6b6a4:
```
$ agda-bisect --bad HEAD --good v2.5.2 --log log --compiler <ghc-7.10.3> --cabal-option --cabal-lib-version=1.23.1.0 --script ./script.hs
[...]
76dabd25e3d41fb0bda0b02e47a21aafddd6b6a4 is the first bad commit
commit 76dabd25e3d41fb0bda0b02e47a21aafddd6b6a4
Author: Andreas Abel <andreas.abel@ifi.lmu.de>
Date:   Fri Jul 14 22:45:57 2017 +0100

    Re #2646: turned some nicifier errors into warnings.
    
    TODO: recover source locations of warnings.
    TODO: turn more nicifier errors into warnings.

[...]
```
The script used above:
```haskell
#!/usr/bin/env runhaskell

import Control.Monad
import Data.Char
import Data.List
import System.Environment
import System.Exit
import System.FilePath
import System.IO
import System.Process

name        = "Bug"
file        = name <.> "agda"
args        = [ "--interaction"
              , "--caching"
              , "--ignore-interfaces"
              , "--no-libraries"
              ]
command     = "IOTCM \"" ++ file ++ "\" None Indirect " ++
                "(Cmd_load \"" ++ file ++ "\" [])"
prompt      = "Agda2> "

-- Reads at most the given number of characters from the given handle.
-- Stops reading if a newline character is encountered, and in that
-- case the returned boolean is True.
--
-- Precondition: The number must be non-negative.

readAtMost :: Int -> Handle -> IO (Bool, String)
readAtMost 0 h = return (False, [])
readAtMost n h = do
  c <- hGetChar h
  if c == '\n'
    then return (True, [])
    else fmap (\(b, s) -> (b, c : s)) (readAtMost (n - 1) h)

-- Reads lines from the handle until a prompt is encountered (at the
-- start of a line). The prompt is not returned.
--
-- Precondition: The prompt must not contain newline characters.

readUntilPrompt :: Handle -> IO [String]
readUntilPrompt h = do
  (nl, s) <- readAtMost (length prompt) h
  if s == prompt then return [] else do
    line <- if nl then return s
                  else fmap (s ++) (hGetLine h)
    liftM (line :) $ readUntilPrompt h

-- Echoes lines read from the first handle on the second handle until
-- a prompt is encountered (at the start of a line). The prompt is not
-- echoed.
--
-- Precondition: The prompt must not contain newline characters.

echoUntilPrompt :: Handle -> Handle -> IO [String]
echoUntilPrompt rd wr = do
  ss <- readUntilPrompt rd
  mapM_ (hPutStrLn wr) ss
  return ss

-- Writes the given string to the given file, using the UTF-8
-- encoding.

writeUTF8File :: FilePath -> String -> IO ()
writeUTF8File f s = withFile f WriteMode $ \h -> do
  hSetEncoding h utf8
  hPutStr h s

-- Precondition: The program must be called with a single argument,
-- the path to Agda.

main :: IO ()
main = do
  -- Start Agda, allocating handles to write commands and read
  -- results.
  [agda] <- getArgs
  (Just wr, Just rd, Nothing, p) <-
    createProcess ((proc agda args) { std_in  = CreatePipe
                                    , std_out = CreatePipe
                                    })
  mapM_ (\h -> hSetEncoding h utf8) [wr, rd, stdout]
  hSetBuffering wr LineBuffering
  hSetBuffering rd NoBuffering
  let wait = echoUntilPrompt rd stdout
      load = hPutStrLn wr command

  -- Discard the first prompt.
  _ <- wait

  -- Create the file.
  writeUTF8File file "record R : Set where\n  infix 0 _+_\n"

  -- Load the file.
  load

  -- Wait for Agda to complete.
  _ <- wait

  -- Edit the file.
  writeUTF8File file "record R : Set where\n"

  -- Reload.
  load

  -- Wait for Agda to complete.
  ss <- wait

  -- Let Agda shut down gracefully.
  hClose wr
  waitForProcess p

  -- Check if the output is OK.
  if any ("_+_" `isInfixOf`) ss
    then exitFailure
    else exitSuccess
```

**Comment by andreasabel** [comment]
Sorry, in this change I was a naive user of the warning machinery.
It seems like caching keeps too many warnings...

@Saizan @fredrikNordvallForsberg What is mechanism to keep/discard warnings for caching?

**Comment by Saizan** [comment]
@andreasabel Caching is designed to care about the typechecking phase, so it starts recording the cache (and possibly invalidate it) according to what's happening after scope checking, and it logs the full "PostScopeState" part of TCState in the cache.

Warnings seem to be stored in the PostScopeState so they get cached, but if you generate them from the nicifier they won't get invalidated in most cases, because the first long entry of the cache will already have the warnings in there and that's about the module header which has not changed between reloads here.

**Comment by andreasabel** [comment]
@nad  Btw, not a regression, as we went from error to warning.

@Saizan If caching detects a file change, it now needs to clear out the warnings with a range past the change location.  Or it needs to compare the current PostScopeState to the previous one to see whether the previous one is still valid.

**Comment by nad** [comment]
> Btw, not a regression, as we went from error to warning.

I don't follow you here. Previously you could fix the error/warning and reload successfully, now you can't.

**Comment by UlfNorell** [comment]
Note that editing the file in the other direction is also problematic: start without the bad fixity declaration, adding it and reloading produces no warning.

This means that clearing out warnings with a particular range is not a valid solution, since we might need to produce new warnings.

One possible solution might be to not generate warnings during scope checking, but instead produce special warning declarations that emits the warnings when type checked.

In any case I don't think this is a sever enough regression to hold up the release (only affects `--caching` and easy to work around by changing the file above the record).

**Comment by nad** [comment]
I think we should aim to enable `--caching` by default soon.

**Comment by nad** [comment]
Here is a related problem. Load the following code (with caching turned on):
```agda
F : ⦃ _ : Set₁ ⦄ → Set₁
F ⦃ A ⦄ = A
```
Add the following code and reload:
```agda
G : Set₁
G = F ⦃ r = Set ⦄
```
This code is rejected, as expected. However, if the first line is then changed to `F : ⦃ r : Set₁ ⦄ → Set₁` and the code is reloaded, then it is still rejected.

**Comment by UlfNorell** [comment]
I get that you want to use fancy unicode braces whenever possible, but the problem exists also for plain non-instance implicit arguments.

**Comment by Saizan** [comment]
Fixed test-case 2728-2 with commit d223d2f, a bit surprising that this hasn't come up before to be honest.

Maybe equality on ```Abstract.Name``` should be even stricter, but it would be better to create a test case that requires that first.

**Comment by nad** [comment]
The caching machinery can also be used to circumvent the `--safe` flag. Here's a test case:
```
$ cat M.agda
{-# OPTIONS --safe #-}

module M where
$ cat Bug.agda 
{-# OPTIONS --safe #-}
module Bug where
open import M
postulate B : Set
$ cat script.hs 
#!/usr/bin/env runhaskell

{-# LANGUAGE RecordWildCards #-}

import System.Directory

import RunAgda

file       = "Bug.agda"
firstCode  = unlines
               [ "{-# OPTIONS --safe #-}"
               , "module Bug where"
               , "open import M"
               ]
secondCode = firstCode ++ "postulate B : Set\n"

main :: IO ()
main = runAgda ["--caching"] $ \(AgdaCommands { .. }) -> do

  -- Discard the first prompt.
  echoUntilPrompt

  -- Create the file.
  writeUTF8File file firstCode

  -- Load the file, and wait for Agda to complete.
  loadAndEcho file

  -- Edit the file.
  writeUTF8File file secondCode

  -- Reload.
  loadAndEcho file

  -- Clean up.
  removeFile $ file ++ "i"

  return ()
```

**Comment by Saizan** [comment]
Right, that's because violating safe with a postulate is also a warning.

**Comment by Saizan** [comment]
@nad I am having problems reproducing the original problem and the --safe flag problem

**Comment by nad** [comment]
A test case for the first example was already present in the repository. @andreasabel modified the output file (`test/interaction/Issue2728.out`) in a commit which changes how certain record modules are handled (2dc68ac7743452958cb7bb9571c0548180b783de).

**Comment by nad** [comment]
The script for the issue with the `--safe` flag seems to still work.

**Comment by nad** [comment]
The [problem](https://github.com/agda/agda/issues/2728#issuecomment-329112512) with implicit or instance arguments seems to still exist for both Agda 2.5.4-ffaba5 and Agda 2.6.0-c946fa.

**Comment by Saizan** [comment]
I believe that now all the problems are fixed on master.

The warnings are also fixed on stable-2.5, but the problem with named implicit/instance arguments is not (Note that Issue2728-2.out differs between master and stable-2.5

**Comment by nad** [comment]
Please add test cases for every problem that has been fixed, to reduce the risk of regressions.

**Comment by Saizan** [comment]
We were only missing one for the --safe example, and that was in my last commit.

**Comment by nad** [comment]
Oh, I had already added all the other ones. :) Thanks.

Why isn't the issue fixed on the stable branch?

**Comment by nad** [comment]
If we can fix this issue completely for the stable branch as well, then I suggest that we turn on caching by default before the next release.

**Comment by Saizan** [comment]
We would have to cherry-pick commits b7d2d3a6 a01a1cc89 from master into stable, and I'm a bit afraid of the merge conflicts.

**Comment by nad** [comment]
Can someone help @Saizan with the merging?

**Comment by nad** [comment]
Can we close this ticket now?
