### ISSUE TITLE
Avoid some uses of \AgdaIndent?

### ISSUE THREAD

**Issue by nad** [agda/agda#2733]
Consider the following code:
```agda
\begin{code}
  postulate
    A  : Set
    B  : Set →
         Set
\end{code}
```
It is typeset in the following way:

![bug](https://user-images.githubusercontent.com/293222/30110069-0a72f38c-9309-11e7-8a9d-c62d05fff164.png)

I think that the three occurrences of `Set` should be aligned.

Currently Agda generates the following LaTeX code:
```latex
\begin{code}%
\>[0][@{}l@{\AgdaIndent{0}}]%
\>[2]\AgdaKeyword{postulate}\<%
\\
\>[2][@{}l@{\AgdaIndent{0}}]%
\>[4]\AgdaPostulate{A}%
\>[7]\AgdaSymbol{:}\AgdaSpace{}%
\AgdaPrimitiveType{Set}\<%
\\
\>[2][@{}l@{\AgdaIndent{0}}]%
\>[4]\AgdaPostulate{B}%
\>[7]\AgdaSymbol{:}%
\>[1I]\AgdaPrimitiveType{Set}\AgdaSpace{}%
\AgdaSymbol{→}\<%
\\
\>[7][@{}l@{\AgdaIndent{0}}]\<[1I]%
\>[9]\AgdaPrimitiveType{Set}\<%
\end{code}
```
The problem is that the last occurrence of `\AgdaIndent{0}` is aligned with the two colon characters. Perhaps the problem can be solved by not using `\AgdaIndent` in cases like this one. However, note that `\AgdaIndent` should be emitted when the following code is processed:
```agda
\begin{code}
  postulate
    A  : Set
    B  : Set →
          Set
\end{code}
```

**Comment by gallais** [comment]
Doesn't

```agda
\begin{code}
  postulate
    A :  Set
    B :  Set →
         Set
\end{code}
```

yield the alignment you want? I think Agda's behaviour is more predictable if we have to explicitly put these two spaces to request alignment.

**Comment by nad** [comment]
No, I want to avoid the extra space between `:` and `Set`.

**Comment by nad** [comment]
To be more precise: I think that the main problem here is that we insert extra space between the second occurrence of `:` and the second occurrence of `Set`. I don't think we should insert space when aligning things, only when indenting things.
