### ISSUE TITLE
Make height of empty lines configurable

### ISSUE THREAD

**Issue by nad** [agda/agda#2734]
I would like to have some way to control the amount of vertical space emitted for empty lines in code blocks. Consider the following code:
```latex
\documentclass[acmsmall]{acmart}

\usepackage{agda}

\begin{document}

\thispagestyle{empty}

Text.
\begin{code}
  postulate
    A  : Set

    B  : Set
\end{code}
More text.

\end{document}
```
Resulting output:

![bug](https://user-images.githubusercontent.com/293222/30111623-b101d772-930e-11e7-8d2c-3941197a29bf.png)

I'd like to make the empty line between `A : Set` and `B : Set` less tall.

The amount of space before and after the code is controlled using `\abovedisplayskip` and `\belowdisplayskip`. One idea is to introduce `\AgdaEmptySkip`, use it for empty lines, and by default set it to be `\abovedisplayskip`.

**Comment by nad** [comment]
> One idea is to introduce `\AgdaEmptySkip`, use it for empty lines, and by default set it to be `\abovedisplayskip`.

I decided to make `\baselineskip` the default for `\AgdaEmptySkip`.

**Comment by UlfNorell** [comment]
I'm getting a test failure on the test case. Is `acmart` really crucial to this test or could it be something more standard?

```
LATEX_COMPILE_FAILED with lualatex

ret > ExitFailure 1
out > This is LuaTeX, Version beta-0.76.0-2013052718 (rev 4627) 
out >  restricted \write18 enabled.
out > (./Issue2734.tex
out > LaTeX2e <2011/06/27>
out > Babel <3.9f> and hyphenation patterns for 78 languages loaded.
out >
out > ! LaTeX Error: File `acmart.cls' not found.
out >
out > Type X to quit or <RETURN> to proceed,
out > or enter new name. (Default extension: cls)
out >
out > Enter file name: 
out > ! Emergency stop.
out > <read *> 
out >    
out > l.2 
out >    
out >  188 words of node memory still in use:
out >    31 glue_spec, 1 dir nodes
out >    avail lists: 2:12,3:1
out > !  ==> Fatal error occurred, no output PDF file produced!
out > Transcript written on Issue2734.log.
```

**Comment by nad** [comment]
Perhaps we shouldn't require every developer to have an up-to-date installation of TeX Live.

The first line can be replaced by `\documentclass{article}`.
