### ISSUE TITLE
Segfault using Alex 3.2.2 and cpphs

### ISSUE THREAD

**Issue by asr** [agda/agda#2736]
I'm getting a segmentation fault (core dumped) in both branches when type-checking any file.

Versions:

OS: Ubuntu 16.04.3
GHC: 8.2.1 and 8.0.2 (I haven't tested with other versions)
cabal-install: 2.0.0.0 compiled using version 2.0.0.2 of the Cabal library
Alex: 3.2.2
Happy: 1.19.7

I guess Travis isn't getting the same problem because it uses different versions:

OS: Ubuntu 14.04
cabal-install: various versions
Alex: 3.1.7
Happy: 1.19.5

Could someone reproduce the problem?

**Comment by nad** [comment]
Another thing to look into is whether this is related to the new dependencies that were introduced when the Issue2604 branch was merged, `uri-encode` and `blaze-html`. I'm using version 1.5.0.5 and 0.9.0.1, respectively.

**Comment by asr** [comment]
I could fix the problem by replacing Alex 3.2.2 by 3.2.1...

**Comment by asr** [comment]
Which version of Alex are you using?

**Comment by asr** [comment]
Note that it is necessary to run the following command before building Agda with a different version of Alex or Happy:

```
$ rm -r dist-2.5.3/build/Agda/Syntax/Parser
```

**Comment by asr** [comment]
>... `uri-encode` and `blaze-html`. I'm using version 1.5.0.5 and 0.9.0.1, respectively.

Travis and I also are using the above versions.

**Comment by asr** [comment]
I could reproduce the segmentation fault with

Agda 2.5.2,
GHC 8.0.2,
Alex 3.2.2 and
Happy 1.19.5.

**Comment by andreasabel** [comment]
Tarmo wrote to me:

> I've installed the newest Agda release, Agda 2.5.2, on a new computer.
> Ubuntu 16.04 currently has ghc 7.10.3 and cabal-install version 1.22.6.0. (using 1.22.5.0 of the Cabal library).
> The newest happy (1.19.7) from hackage didn't work at all with this ghc, I had to use 1.19.5.
> Then I managed to build Agda.
> But it segfaults immediately on the smallest agda file.

**Comment by nad** [comment]
> Which version of Alex are you using?

3.1.4.

**Comment by tarmouu** [comment]
I solved my problem thanks to Andreas's help (he pointed me here and told me that my trouble could be due to alex). 

The situation is:

With ghc 7.10.3 you cannot make happy 1.19.7, I therefore used 1.19.5 instead.

Further, Agda 2.5.2 builds successfully with alex-3.2.2, but running agda thus built segfaults immediately.

In summary the fix for me was to constrain to happy ==1.19.5 and alex ==3.2.1.

**Comment by asr** [comment]
@tarmouu, thank you for the feedback!

> With ghc 7.10.3 you cannot make happy 1.19.7, I therefore used 1.19.5 instead.

The incompatibility with Happy 1.19.6(7) was fixed in upstream (see #2731).

> he pointed me here and told me that my trouble could be due to alex

Yes, it seems that the problem is with Alex 3.2.2.

**Comment by asr** [comment]
Travis also [segfaults](https://travis-ci.org/agda/agda/builds/272764313) with Alex 3.2.2.

**Comment by asr** [comment]
It seems the problem is related to `cpphs`. Using Alex 3.2.2 I could fix the problem replacing `cpphs` with `cpp`. It would also explain why the problem hasn't been reported. The combination of using `cpphs` and Alex is not common in Hackage.

**Comment by asr** [comment]
I'm starting to think that we are getting more problems than solutions by using `cpphs`. I know that `cpphs` fix some problems related to the Haskell syntax (e.g. prime characters in identifiers) but we know how to fix them. I have also been curious why `cpphs` is not commonly used by the community. Maybe we should consider removing the use of `cpphs`.

**Comment by UlfNorell** [comment]
It would certainly be interesting to know what the actual concrete benefits of using `cpphs` are, considering all the problems.

**Comment by nad** [comment]
> It seems the problem is related to `cpphs`.

I noticed that Alex 3.2.2 uses string gaps, while Alex 3.1.4 doesn't.

I looked at the result of processing `Lexer.hs` with `cpp` (really `gcc` with various options including `-E`, `-traditional` and `-x assembler-with-cpp`) and `cpphs`. The main difference seems to be that `cpp` removes string gaps. However, when it does this it keeps one of the backslash characters. Alex 3.2.2 seems to have taken this into account, because the text after a string gap does not start with a backslash character. Here is an example:
```
alex_base = AlexA#
  "\xf7\xff\xff\xff\x6c\x00\x00\x00\xe1\x00\x00\x00\x55\x01\x00\x00\xca\x01\x00\
\x00\x3f\x02\x00\x00\xb5\x02\x00\x00\x73\x00\x00\x00\xd8\xff\xff\xff\x94\x03\
```
Note that the final line starts with `\x00`, not `\\x00`. No wonder that this code segfaults when processed with `cpphs`.

**Comment by nad** [comment]
See https://github.com/simonmar/alex/issues/84.

**Comment by asr** [comment]
@nad, while I process what you wrote, could you report our problem in the Alex bug tracker, please.

**Comment by nad** [comment]
See https://github.com/simonmar/alex/issues/116#issuecomment-327919422.

**Comment by asr** [comment]
Great! Thanks!

**Comment by nad** [comment]
> It would certainly be interesting to know what the actual concrete benefits of using `cpphs` are, considering all the problems.

It seems as if we switched because back in 2014 "Recent versions of Clang's preprocessor don't work well with Haskell": https://github.com/agda/agda/commit/943ea3cf659a31e79849bcd67683e33b679a30df#diff-04c6e90faac2675aa89e2176d2eec7d8R46.

The [release notes for GHC 7.8.1](https://downloads.haskell.org/~ghc/7.8.1/docs/html/users_guide/release-7-8-1.html) contain the following text:

> As a result of this, when using Clang as the preprocessor, some programs which previously used `-XCPP` and the preprocessor will now fail to compile. Users who wish to retain the previous behavior are better off using cpphs as an external preprocessor for the time being.

**Comment by UlfNorell** [comment]
There are no issues with `ghc-7.8` and `clang` on my machine. Note that we don't support `ghc < 7.8.4`.
```
$ gcc --version
Apple LLVM version 7.0.2 (clang-700.1.81)
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.8.4
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F2411
$ git status
On branch stable-2.5
Your branch is up-to-date with 'origin/stable-2.5'.
nothing to commit, working directory clean
$ make CABAL_OPTS+=--flags=-cpphs && make succeed
...
All 1079 tests passed
```

**Comment by UlfNorell** [comment]
Maybe the first move should be to not use `cpphs` by default, but still keep the flag if it turns out there are problematic setups that we don't know about.

**Comment by asr** [comment]
Alex 3.2.3 supporting cpphs was released. Testing...

**Comment by asr** [comment]
The current code base supports Alex 3.2.3 so I'm closing the issue.

**Comment by xekoukou** [comment]
I am a noob with regards to Cabal, but shouldn't ```Agda.cabal``` be changed to exclude alex 3.2.2?

(I am trying to build agda from github on the nixos distribution and it keeps downloading alex 3.2.2.)

**Comment by andreasabel** [comment]
Yes, of course.

**Comment by asr** [comment]
I didn't exclude Alex 3.2.2 because Agda isn't compatible with this version of Alex per se.

From the ANNOUNCE message:

> Agda 2.5.3 is not compatible with Alex 3.2.2 when using the (default)
cpphs preprocessor. You can use a different version of Alex (e.g.
3.2.1, 3.2.3, etc.) or you can use the cpp preprocessor by running the
following command:

>  `cabal install -f -cpphs`

**Comment by andreasabel** [comment]
Since Alex 3.2.3 has been released shortly after 3.2.2, I think it is ok to exclude 3.2.2, just to be on the safe side.

**Comment by Blaisorblade** [comment]
FWIW, I often check the CHANGELOG, but never the announce. Is it correct that the info on Alex is only on https://lists.chalmers.se/pipermail/agda/2017/009713.html (and in various issues), but not in the changelog, also called "release notes" on http://wiki.portal.chalmers.se/agda/pmwiki.php?n=Main.Download?

Somehow, Google even fails to find it:
https://www.google.it/search?hl=en&biw=1678&bih=860&q=agda+announce+2.5.3+site%3Alists.chalmers.se&oq=agda+announce+2.5.3+site%3Alists.chalmers.se&gs_l=psy-ab.3...2192.4109.0.4196.10.9.0.0.0.0.322.952.2-3j1.4.0....0...1.1.64.psy-ab..7.0.0.GWgdzq7_lW4

That might or might not relate to https://lists.chalmers.se/mailman/listinfo/agda giving a 403 error — to find the 2017 archives I edited the URL by hand.

**Comment by asr** [comment]
> Is it correct that the info on Alex is only on https://lists.chalmers.se/pipermail/agda/2017/009713.html (and in various issues), but not in the changelog, also called "release notes" on http://wiki.portal.chalmers.se/agda/pmwiki.php?n=Main.Download?

Yes, it is correct.

**Comment by nad** [comment]
> That might or might not relate to https://lists.chalmers.se/mailman/listinfo/agda giving a 403 error

I haven't observed any errors recently (from inside or outside the Chalmers network).

**Comment by asr** [comment]
> That might or might not relate to https://lists.chalmers.se/mailman/listinfo/agda giving a 403 error

I also see the same error.

**Comment by andreasabel** [comment]
I contacted our IT-support about this and got this reply:
> There should be no firewalls or other restrictions on this server for access pages except for administration, and some non-public parts, that is password protected (which generates a password prompt, not a 403 failure)

> We can check our logs to see if we can find anything that explains it here, but we need to know IP-adress of the one who tried and also time,date and timezone when you got this error.
> It may also help to know typ of web browser and operating system (version) on the client system.

This issue is tracked at (no external access, I am afraid):
https://service.portal.chalmers.se/issue/1904242/5daa4be225f1a817440d/

@Blaisorblade @asr Please email me your IP-addresses and browser details (and other potentially useful information) to pass on to our IT-service.

**Comment by Blaisorblade** [comment]
@andreasabel Thanks, I've sent you an email (if I decoded your address correctly).

For the record for anybody else, this is my `curl` log (included in that email).

```
$ curl -v http://lists.chalmers.se/mailman/listinfo/agda
*   Trying 129.16.222.36...
* Connected to lists.chalmers.se (129.16.222.36) port 80 (#0)
> GET /mailman/listinfo/agda HTTP/1.1
> Host: lists.chalmers.se
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Date: Mon, 11 Sep 2017 14:16:50 GMT
< Server: Apache/2.2.15 (Red Hat)
< Location: https://lists.chalmers.se/mailman/listinfo/agda
< Content-Length: 339
< Connection: close
< Content-Type: text/html; charset=iso-8859-1
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://lists.chalmers.se/mailman/listinfo/agda">here</a>.</p>
<hr>
<address>Apache/2.2.15 (Red Hat) Server at lists.chalmers.se Port 80</address>
</body></html>
* Closing connection 0
```

**Comment by andreasabel** [comment]
Looks like a `http` request is redirected to a `https` request?

What do you get for `curl -v https://lists.chalmers.se/mailman/listinfo/agda` ? (HTTPS)

**Comment by Blaisorblade** [comment]
Yes, sorry, I pasted the wrong thing here, luckily the answer is hidden in my email. Pasting here too:

```
$ curl -v https://lists.chalmers.se/mailman/listinfo/agda
*   Trying 129.16.222.36...
* Connected to lists.chalmers.se (129.16.222.36) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: lists.chalmers.se
* Server certificate: TERENA SSL CA 2
* Server certificate: USERTrust RSA Certification Authority
* Server certificate: AddTrust External CA Root
> GET /mailman/listinfo/agda HTTP/1.1
> Host: lists.chalmers.se
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 403 Forbidden
< Date: Mon, 11 Sep 2017 14:13:34 GMT
< Server: Apache/2.2.15 (Red Hat)
< Content-Length: 308
< Connection: close
< Content-Type: text/html; charset=iso-8859-1
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /mailman/listinfo/agda
on this server.</p>
<hr>
<address>Apache/2.2.15 (Red Hat) Server at lists.chalmers.se Port 443</address>
</body></html>
* Closing connection 0
```
