### ISSUE TITLE
Indenting every line of code should be a no-op

### ISSUE THREAD

**Issue by nad** [agda/agda#2740]
The following two documents, that only differ in the amount of whitespace preceding a line of code, are not rendered in the same way:
```latex
\documentclass{article}

\usepackage{agda}

\pagestyle{empty}

\begin{document}

\noindent Beginning of line.
\begin{code}
postulate A : Set
\end{code}

\end{document}
```
```latex
\documentclass{article}

\usepackage{agda}

\pagestyle{empty}

\begin{document}

\noindent Beginning of line.
\begin{code}
  postulate A : Set
\end{code}

\end{document}
```

Compare the results:

![a](https://user-images.githubusercontent.com/293222/30158745-80e6e678-93c6-11e7-92c9-1fd983995b88.png)

![b](https://user-images.githubusercontent.com/293222/30158746-80e8e248-93c6-11e7-8bf3-a4249cf3d8bc.png)

I think that these documents should be rendered in the same way.

**Comment by andreasabel** [comment]
> The following two documents, that only differ in the amount of whitespace preceding a line of code, are not rendered in the same way...

Why should they?  Indentation matters in Agda, shouldn't this be reflected in the LaTeX-rendering?
Maybe your example is not representative, with just a single code-block.

If you replace "a line of code" by "every line of code" in the quoted text, I agree.

**Comment by nad** [comment]
I don't think that the LaTeX backend should (by default) try to align code in different code blocks. I suspect that this would look strange in the rendered documents. (One could imagine having a second, different LaTeX backend that produces documents from which you can cut and paste valid Agda code, including `\begin{code}`/`\end{code}`. Perhaps that is even possible with the current backend, if PDF files allow you to separate the text that is displayed from the text that is put in the clipboard. However, that might be confusing and perhaps not very useful.)

For the example described above there were two equivalence classes: no whitespace and some whitespace. This didn't make sense to me, so I merged these equivalence classes.

**Comment by andreasabel** [comment]
Remark: See the `AgdaAlign` environment for sharing indentation over several code blocks:  https://agda.readthedocs.io/en/v2.6.1.1/tools/generating-latex.html#breaking-up-code-blocks
