### ISSUE TITLE
It should be possible to give arguments to the code environment

### ISSUE THREAD

**Issue by nad** [agda/agda#2744]
I think that it should be possible to give arguments to the `code` environment. At the moment I have one use case in mind: I'd prefer writing
```latex
\begin{code}[hide]
...
\end{code}
```
rather than the following code:
```latex
\AgdaHide{
\begin{code}
...
\end{code}}
```
Does anyone object to this?

**Comment by andreasabel** [comment]
Sounds reasonable.  How would other translators handle this, like `lhs2TeX --agda` ?

**Comment by nad** [comment]
> How would other translators handle this, like `lhs2TeX --agda` ?

If lhs2TeX 1.19 is used, then `[hide]` is treated as a variable. However, I don't see this as a major problem, `lhs2TeX --agda` and `agda --latex` already have different semantics. For instance, `agda --latex` does not support `spec` environments.

What "other translators", other than lhs2TeX, do you have in mind?

**Comment by andreasabel** [comment]
> What "other translators", other than lhs2TeX, do you have in mind?

None. A single witness is usually sufficient to establish an existential statement. ;)

My concern was whether there is some unwritten convention that the `code` environment takes no arguments, but googling around I found counterexamples to this convention.  

So, no objections from my side.  Your proposal seems very useful to make better-structured literate Agda code.

**Comment by nad** [comment]
I suggest that we change the syntax in the following way: All text after `\begin{code}`, up until the end of the line, is treated as an argument to `\begin{code}`.

**Comment by andreasabel** [comment]
That should be fine, as the rest of the line after `\begin{code}` is already not treated as Agda code:
```latex
\begin{code}postulate A : Set
\end{code}
```
Note that our parsing will not conform to TeX semantics, e.g., this would be valid Agda code:
```latex
\begin{code}
[hide] = Set
\end{code}
```

**Comment by asr** [comment]
@nad, I added the milestone 2.5.4.
