### ISSUE TITLE
Add --no-unicode cli option to Agda

### ISSUE THREAD

**Issue by gallais** [agda/agda#2749]
Recording here @bishboria's request so that I don't forget it

> is it possible to *completely* switch off unicode in agda? Eg using C-c C-r in a hole for a function always give a unicode lambda and rightarrow

**Comment by andreasabel** [comment]
Sounds more like a pragma option and/or an emacs mode customization.  But yes.  Currently Agda forces the unicode flavor, also when picking variable names during case-splitting.

**Comment by gallais** [comment]
My thinking was that you can set the option as an `Agda2 Program Args` in emacs (`M-x customize-group RET agda2 RET`) if it's a command line one. With a pragma option, you'd have to repeat it at the beginning of each file you're editing which is annoying.

**Comment by andreasabel** [comment]
Ah, yes, but pragma options can also be given at the command line.
See, e.g., #2714 where I turned a command line option into a pragma option.
Anyway, you have done this before: https://github.com/agda/agda/commit/60f240d29ce7e91a2fc6358022f8a5159ae160c8 (#2442).

**Comment by fredrikNordvallForsberg** [comment]
Wouldn't it make more sense to make this an emacs custom option? Or is there a need to also not print unicode in error messages on the command line? (I imagine the main use case would be to keep _source files_ unicode free.)

**Comment by andreasabel** [comment]
With comparable options like `--show-implicit` it is like that: they can be given at the command line and in pragmas, and turned on in the emacs mode.

(P.S.: `--postfix-projections` currently lacks the emacs mode option)

**Comment by bishboria** [comment]
Fred is correct: my specific use case is to have unicode free source files.

**Comment by gallais** [comment]
I'm really confused. I have edited [these strings](https://github.com/agda/agda/blob/master/src/full/Agda/Interaction/BasicOps.hs#L855) and refine (`C-c C-r`) still returns a unicode lambda in emacs...

Edit: wait. Is the expression created as a string, parsed, checked and then the elaborated internal representation printed?! I think I also transform the lambda in all of the pretty printers except for the pure ones (because I can't pull the config if I don't have access to `PragmaOptions`).

**Comment by UlfNorell** [comment]
Yes, the one that you really need to change is `Agda.Syntax.Concrete.Pretty`.

**Comment by gallais** [comment]
And these `Agda.Syntax.Concrete.Pretty` instances are in the `Pretty` class, not in the `PrettyTCM` one which means that they're pure rather than in the `TCM` monad i.e. you don't get to have access to the `PragmaOptions` when defining them. :/

**Comment by andreasabel** [comment]
`IORef`s and `UnsafePerformIO` are your friend to get options in a pure setting.  I use such black magic in the benchmarking facility.

**Comment by gallais** [comment]
Next up: getting rid of the indices introduced by pattern-matching (this happens in another module entirely IIRC).

**Comment by andreasabel** [comment]
Something is wrong with `test/interaction/Issue2749`.
It seems to have the wrong module name `asciionly` instead of `Issue2749`.

**Comment by andreasabel** [comment]
I think you introduced a bug in the printer:
```agda
test : {{A : Set}} → A → A
test = {!!}
```
Now `C-c C-x C-h C-c C-c RET` (split on result adding also hidden arguments) produces
```
test ⦃A⦄ x = ?
```
and error
```
Cannot eliminate type A with pattern x (did you supply too many arguments?)
when checking that the clause test ⦃A⦄ x = ? has type
⦃A : Set⦄ → A → A
```
The problem is that `⦃A⦄` is a single identifier, it should be printed as `⦃ A ⦄`.

On a related note:  Can the choice of the user (non-unicode instance brackets) be respected here?  (Would require tracking some bit from the lexer all the way to the internal syntax.)

**Comment by gallais** [comment]
Thanks for fixing the golden value!

> Now `C-c C-x C-h C-c C-c RET` (...)

That's the command I was looking for! I was trying to write a test using `C-c C-r` to introduce a lambda binding the instance argument but Agda would systematically ignore it.

> The problem is that `⦃A⦄` is a single identifier, it should be printed as `⦃ A ⦄`.

Was this choice made so that `⦃` and `⦄` wouldn't be reserved characters? I'll replicate the current behaviour but it would be nice to have a uniform treatment of `(`, `{` and `⦃`.

> Can the choice of the user (non-unicode instance brackets) be respected here?

I'd argue that this should be filed as a different issue! :D

**Comment by nad** [comment]
Please include some text in the changelog and reference manual.

**Comment by andreasabel** [comment]
>Was this choice made so that ⦃ and ⦄ wouldn't be reserved characters? 

Yes, you can still use decorations of these braces for your own identifiers.  Note that a similar choice was made for unicode lambda.
```agda
′⦃_⦄′ : Set → Set
′⦃ A ⦄′ = A  -- accepted

nouni : Set → Set
nouni = \x → x  -- accepted

uni : Set → Set
uni = λx → x  -- rejected
```
