### ISSUE TITLE
Unsolved constraints, but no highlighting

### ISSUE THREAD

**Issue by nad** [agda/agda#2751]
Consider the following code:
```agda
open import Agda.Builtin.Size

mutual

  data D (i : Size) (A : Set) : Set where
    c : D′ i A → D i A

  record D′ (i : Size) (A : Set) : Set where
    inductive
    field
      size  : Size< i
      force : D size A

open D′ public

record Map (F : Set → Set) : Set₁ where
  field
    map : {A B : Set} → (A → B) → F A → F B

open Map ⦃ … ⦄ public

mutual

  instance

    Map-D : ∀ {i} → Map (D i)
    Map.map Map-D = λ where
      f (c xs) → c (map f xs)

    Map-D′ : ∀ {i} → Map (D′ i)
    size  (Map.map  Map-D′      f t) = size t
    force (Map.map (Map-D′ {i}) f t) = map f (force t)
```
Agda rejects this code:
```
ω != size t of type Size
when checking that the expression map f (force t) has type
D (size (Map.map Map-D′ f t)) .B
```
Fine, the size solver has problems. Let's make the code more explicit, in an *incorrect* way:
```agda
    force (Map.map (Map-D′ {i}) f t) = map ⦃ r = Map-D {i = i} ⦄ f (force t)
```
Now Agda reports that some size constraints are unsolved:
```
Failed to solve the following constraints:
  [63, 64] size t =< i : Size
  [66, 67] i =< size t : Size
```
However, there is no indication of where these constraints come from: no line numbers, no highlighting of the code.

**Comment by andreasabel** [comment]
Unsolved constraints have not produced any highlighting so far, see also #689.

**Comment by andreasabel** [comment]
Here is an example with levels where unsolvable constraints are reported, but no location where they come from.
```agda
mutual
  l = _

  data D {a} (A : Set a) : Set l where
    c : A → D A

  data E (A : Set l) : Set1 where
    c : A → E A
```
Reports:
```
Failed to solve the following constraints:
  _4 =< .Agda.Primitive.lsuc .Agda.Primitive.lzero
  a =< _4
```
The error message is radically different when we use `Set` instead of `Set1`:
```
The type of the constructor does not fit in the sort of the
datatype, since Set _4 is not less or equal than Set
when checking the constructor c in the declaration of E
```
(Somehow this error does a worse job explaining what goes wrong than the one with the unsolved constraints.)

**Comment by andreasabel** [comment]
Currently only unsolved emptyness constraints get highlighted.  This could be changed, but we might get lots of confusing yellow.

**Comment by andreasabel** [comment]
I am fixing this issue by highlighting unsolved constraints.

The other issue, the problem with the size solver, should be handled in a new issue.

**Comment by nad** [comment]
> Currently only unsolved emptyness constraints get highlighted. This could be changed, but we might get lots of confusing yellow.

Perhaps unsolved constraints could be highlighted in a different way.
