### ISSUE TITLE
Warning for nonsensical higher-order instance arguments

### ISSUE THREAD

**Issue by nad** [agda/agda#2755]
The reference manual and/or the implementation is incorrect.

The reference manual states the following:

> The type of an instance argument must have the form `{Γ} → C vs`, where `C` is a bound variable or the name of a data or record type, [...]

It seems as if `C` can also be a postulated name.

The manual continues as follows:

> and {Γ} denotes an arbitrary number of (ordinary) implicit arguments [...]

However, further down it states that

> Then, given a candidate `c : Δ → A` we generate fresh metavariables `αs : Δ` for the arguments of `c`, with ordinary metavariables for implicit arguments, and instance metavariables, solved by a recursive call to instance resolution, for explicit arguments and instance arguments.

This text suggests that instance arguments (which can be candidates) can take arguments that are not implicit.

I tried this, and using instance arguments as arguments to an instance argument seems to work fine, but using explicit arguments does not seem to work:
```agda
postulate
  A          : Set
  B          : ⦃ _ : A ⦄ → Set
  C          : ⦃ _ : A ⦄ ⦃ _ : B ⦄ → Set
  Works      : ⦃ _ : {a : A}   → B ⦃ a ⦄ ⦄ ⦃ _ : A ⦄ → C → Set
  Also-works : ⦃ _ : ⦃ a : A ⦄ → B ⦃ a ⦄ ⦄ ⦃ _ : A ⦄ → C → Set
  Fails      : ⦃ _ : (a : A)   → B ⦃ a ⦄ ⦄ ⦃ _ : A ⦄ → C → Set
```

**Comment by UlfNorell** [comment]
> It seems as if C can also be a postulated name.

Indeed. Feel free to update the documentation.

> This text suggests that instance arguments (which can be candidates) can take arguments that are not implicit.

It says that *candidates* can, but not all candidates are instance arguments.

What's missing from the documentation (aside from the postulates thing) is the explanation of higher-order instance search. I don't think we have this fully locked down, so I think it's better to be conservative in the documentation.

**Comment by nad** [comment]
> It says that *candidates* can, but not all candidates are instance arguments.

That's why I wrote "suggests".

If the text claiming that instance arguments must only have implicit arguments is correct, shouldn't instance arguments that do not have this form be rejected? Now `Also-works` is accepted, and the type of `Fail`'s first argument is also accepted.

**Comment by UlfNorell** [comment]
It ought to say *should* rather than *must*. I suppose we could also add a note that having instance arguments in `Γ` works in some cases.

**Comment by nad** [comment]
> I suppose we could also add a note that having instance arguments in `Γ` works in some cases.

What do you mean by *some* cases?

(Feel free to answer by updating the documentation rather than writing something here.)

**Comment by UlfNorell** [comment]
By that I mean that, while we could document exactly how the current implementation handles higher-order instance arguments, I don't feel confident enough that this is the way it *should* handle higher-order instance arguments, so I'd rather no one relied on them working.

**Comment by nad** [comment]
I tried to interpret what you wrote, and updated the documentation. However, in order to avoid surprises for users I think that we should give an error (or at least a warning) if an instance argument that does not have the right form is declared.

**Comment by UlfNorell** [comment]
Looks good to me.

We don't want to give an error for higher-order instances, and I'm not sure about the warning. I guess we could issue a warning for the case where you have explicit arguments (`Fails` above), since there's really no way that's going to work with the current implementation.

**Comment by nad** [comment]
> I guess we could issue a warning for the case where you have explicit arguments (`Fails` above), since there's really no way that's going to work with the current implementation.

Yes.

**Comment by andreasabel** [comment]
A warning seems to be in place now (since 2.6.0):
```
Instance arguments with explicit arguments are never considered by
instance search, so having an instance argument
⦃ _ : (a : A) → B ⦃ a ⦄ ⦄ has no effect.
when checking that the expression
⦃ _ : (a : A) → B ⦃ a ⦄ ⦄ ⦃ _ : A ⦄ → C → Set is a type
```
