### ISSUE TITLE
HTML backend generates broken links

### ISSUE THREAD

**Issue by nad** [agda/agda#2756]
If HTML is generated from the following code, then the link from `M′.A` does not point to the right place:
```agda
module Bug where

module M where

  postulate A : Set

module M′ = M

B : Set
B = M′.A
```
A link is generated to `#M′.A`, rather than `#M.A`.

**Comment by nad** [comment]
Due to this bug I would advise against using Agda 2.5.3 for generating HTML intended to be read by anonymous reviewers.

**Comment by nad** [comment]
I have implemented a temporary fix: all links are numbered again. If no proper fix is implemented before the next version of Agda is released, then this change should be documented in the changelog and (if appropriate) the user manual.

**Comment by nad** [comment]
@andreasabel, some comments on commit 06c92f5f648ec669536c620346e6d414c547f1a9:
* You did not document the changes in the changelog. Is the idea that users should inspect the generated HTML code in order to find suitable anchors?
* You did not include the code above as a test case.
* You generate code of the following form:
  ```html
  <a id="A"></a><a id="19" href="%252541.html#19" class="Function">A</a>
  ```
  Note that the first `<a>` tag is not wrapped around `A`. Is this intended?

**Comment by andreasabel** [comment]
Concerning point 1: Here is the original changelog: https://github.com/agda/agda/issues/2604#issuecomment-309008789
Concerning point 2: fair enough
Concerning point 3: Anchors cannot be nested, see https://stackoverflow.com/questions/18666915/why-are-nested-anchor-tags-illegal

**Comment by andreasabel** [comment]
Added test case and changelog.
