### ISSUE TITLE
Relax instance search restriction on unconstrained metas

### ISSUE THREAD

**Issue by mjustus** [agda/agda#2760]
I find it difficult to predict whether instance search is going to succeed when working with parameterised records. Here is an example

```agda
record R (X : Set) : Set₁ where
  field
    P : X → Set
    f : ∀ {x : X} → P x → P x

open R {{…}}

test : ∀ {X} {{r : R X}} {x : X} → P x → P x
test p = f p
```

Instance search fails with the following error message

    _X_14 : Set  [ at `f` ]
    _r_15 : R (_X_14 p)  [ at `f` ]
    _x_16 : _X_14 p  [ at `f` ]
    _17 : R.P (_r_15 p) (_x_16 p)  [ at `p` ]
    _18 : R.P (_r_15 p) (_x_16 p)  [ at `p` ]
    _19 : R.P .r .x  [ at `f p` ]
    _20 : R.P .r .x  [ at `f p` ]

    ———— Errors ————————————————————————————————————————————————
    Failed to solve the following constraints:
      Resolve instance argument
        _15 :
          {.X : Set} {{.r : R .X}} {.x : .X} (p₁ : R.P .r .x) → R (_X_14 p₁)
      Candidates .r : R .X
      _19 := λ {.X} {{.r}} {.x} p → R.f (_r_15 p) (_18 p)
        [blocked on problem 19]
      [19] R.P (_r_15 p) (_x_16 p) =< R.P .r .x : Set
      _17 := (λ {.X} {{.r}} {.x} p → p) [blocked on problem 18]
      [18] (R.P .r .x) =< (R.P (_r_15 p) (_x_16 p)) : Set

Passing parameter `X` explicitly

```agda
test' : ∀ {X} {{r : R X}} {x : X} → P x → P x
test' {X} = f {X}
```

makes the error go away, but I would have expected Agda to infer `X` from `p`.

Earlier bug reports (#1272 and #2670, for example) seem to suggest that this is not a bug. However, if Agda were able to handle this example, instances would be much more useful to me.

**Comment by m0davis** [comment]
Another workaround is to pass the `x : X` (not `X : Set`) parameter explicitly:
```agda
test'' : ∀ {X} {{r : R X}} {x : X} → P x → P x
test'' {x = x} = f {x = x}
```
I think this is an issue with hidden arguments, not instances per-se. See #2099.

**Comment by m0davis** [comment]
To be clear, in your `test'` workaround, you're passing the `X : Set` parameter of `R`. Another workaround (which, anyway, gives me a fuzzier feeling that Agda is doing instance search) is to instead pass the `x : X` argument of `f`:
```agda
test'' : ∀ {X} {{r : R X}} {x : X} → P x → P x
test'' {x = x} = f {x = x}
```
p.s. Fwiw, my intuition was telling me that #2099 is related, but I'm not certain now. I didn't want to mention this and have it referenced in the linked issue, but github will forever remember me referencing it in my (now deleted) comment, so I'm including it here to reduce the confusion I created. :/

**Comment by identicalsnowflake** [comment]
Playing around with your example, I encountered this, which might be interesting:

```agda
weirdError : ∀ {X} {{r1 : R X}} {{r2 : R (X × X)}} {x : X} → P x → P x
weirdError {X} p = f {X × X} p
```

I would expect Agda to reject this as not even type correct -- and if you try to manually plug in `{{r2}}`, it does. But loading the above instead yields `No instance of type R (X × X) was found in scope.`, which is an odd error because there definitely is an instance `r2 : R (X × X)` in scope!

EDIT: I think this means that `f p` is performing instance search before taking into account the unification information it would get from applying that `p`, which in my example results in an incorrect error, and in OP results in `{X}` not being resolved before instance search takes place. If it would use the unification information available before the search, mine would be rejected before search ever takes place, and OP's example would succeed.

**Comment by mjustus** [comment]
I had a look at the instance search code and, as far as I can tell, instance resolution is aborted because of a [check](https://github.com/agda/agda/blob/c84e4a3a2d861db7260e0fb05dc7c18d3cbd36b0/src/full/Agda/TypeChecking/InstanceArguments.hs#L150) introduced in c84e4a3a2d861db7260e0fb05dc7c18d3cbd36b0 by @guillaumebrunerie in order to prevent certain collections of candidate instances from causing loops. Maybe there's a less coarse-grained check that doesn't exclude benign examples like the one above?

Edit: link to the check was pointing to the wrong line.

**Comment by UlfNorell** [comment]
Related #2563.

There are two purposes of the unconstrained meta check
- prevent loops
- prevent unpredictable behaviour

It seems to me like neither of those are a problem here. A possible relaxation might be:

When there are unconstrained metas
- proceed checking the candidates, but abort at recursive goals (preventing loops)
- if exactly one local (lambda bound) candidate fits, use it
- if the only candidate is a top-level instance, block the solution and give an informative constraint (preventing unpredictable behaviour)

**Comment by jespercockx** [comment]
This issue hit me today after a long time of not using instance arguments. I approve of Ulf's suggested solution. The question is what we should consider local candidates. I have in particular an example at the bottom of [this file](https://github.com/jespercockx/categories/blob/master/Category.agda) where I use the pattern
```agda
record R (X : A) : Set where
  instance _ = X
  field ...
```
and I'd like the instance to still be considered 'local' in this case.

**Comment by jespercockx** [comment]
I consider instance search to be broken atm because of this issue. Is there any chance of a solution before the release?

**Comment by UlfNorell** [comment]
I hope so, but I also have the generalize stuff to get done. If you want to look at it feel free :-).

**Comment by jespercockx** [comment]
This is blocking #723
