### ISSUE TITLE
Add support for Higher Inductive Types

### ISSUE THREAD

**Issue by Saizan** [agda/agda#2761]
As the title says: Add support for Higher Inductive Types!

Support can be broken down to multiple tasks:
* [x] data declarations allowing paths and higher paths, and turning off no-confusion for the datatype in that case.
* [x] `primComp` (or equivalent) should compute doing the right thing for HITs.
* [x] Make sure to check pattern matching against a HIT checks that the clauses commute with face restrictions.

**Comment by copumpkin** [comment]
Watching eagerly 😄

**Comment by martinescardo** [comment]
It would be nice to have propositional truncations to begin with, maybe as a built-in type constructor if this is easier. This is a fundamental construction needed to implement univalent logic and define a number of fundamental notions such as image, surjection and more. We need this to do any serious univalent mathematics in Cubical Agda.

**Comment by UlrikBuchholtz** [comment]
Another option would be to just have pushouts as a built-in to start with. From these, most other common HITs can be defined, including propositional truncation, and n-truncation for any n. I agree with @martinescardo that we need propositional truncation at a bare minimum.

**Comment by martinescardo** [comment]
I agree. But, pragmatically, it would be good to have propositional truncation directly, at least to begin with, because it is a serious formalization effort to derive it from pushouts.

**Comment by UlrikBuchholtz** [comment]
Well, I hereby volunteer to do the derivation :)

**Comment by Saizan** [comment]
I'm glad there's interest in this, unfortunately I haven't found a good chunk of time to work on this so far.

The current plan is to split `primComp` into a `hcomp` and a `trans` primitive as is done in "cubicaltt/hcomptrans", so that for HITs one would have `hcomp` as a constructor and only have to provide computations for `trans`.

That would enable a fairly general class of HITs to be defined with the data keyword, including pushouts.

Something quicker for just propositional truncation or pushouts could be done with the `squeeze`+`transport` formulation from the original paper. I don't quite like that because it would involve a lot of special case built-ins, and the computational behavior will not be compatible with the `hcomp`+`trans` formulation.

**Comment by Saizan** [comment]
So, I decided I would actually go for the quick solution first and provide pushouts as a builtin:

https://github.com/Saizan/cubical-demo/blob/master/src/Cubical/PushOut.agda
https://github.com/Saizan/cubical-demo/blob/master/examples/Cubical/Tests/PushOut.agda

Will you then derive prop. truncation, @UlrikBuchholtz ? :)

**Comment by martinescardo** [comment]
@UlrikBuchholtz , I am waiting for the truncations now. :-)

When this is done, I will attempt to port a 10000 line Agda development which uses truncation, funext and propext and UA as assumptions.

**Comment by martinescardo** [comment]
Many thanks, @Saizan !

**Comment by UlrikBuchholtz** [comment]
Yes, many thanks @Saizan !

@martinescardo I'll let you know when the truncations are there.

**Comment by martinescardo** [comment]
Can you do them with elimination into any universe, please?

**Comment by UlrikBuchholtz** [comment]
Sure, since the pushout eliminator takes a separate universe variable for the target, that should not be an issue.

**Comment by HuStmpHrrr** [comment]
i am almost too interested in it!

**Comment by jespercockx** [comment]
What is the current status of this issue? Are HITs fully implemented now?

**Comment by Saizan** [comment]
As of 2c4da0841d38a8c6af0083de3e635bac958168bc I would consider them implemented!

I guess we should have a label for issues about HITs now.
