### ISSUE TITLE
Automatically generate display forms to fold pattern synonyms

### ISSUE THREAD

**Issue by gallais** [agda/agda#2762]
What it says in the title. Basically I'd like to see the pretty goal `3+ n ≡ 3+ n` even without the `DISPLAY` pragma.

```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Equality

pattern 3+ n = suc (suc (suc n))
{-# DISPLAY suc (suc (suc n)) = 3+ n #-}

_ : ∀ n → 3+ n ≡ suc (suc (suc n))
_ = {!!}
```

**Comment by UlfNorell** [comment]
A minor complication: constructors in pattern synonym can be overloaded, but display forms use resolved constructors. For instance, if you had both `Nat.suc` and `Fin.suc` constructors in the example above you would need 8 different display forms.

Possible solutions:
1. generate all 8 display forms
2. use types to rule out impossible variants
3. change display forms to allow overloaded constructors
4. don't use display forms, but look at the pattern synonyms directly when printing

I'm leaning towards 4 as the most promising solution.

**Comment by gallais** [comment]
Didn't think of that! I'll throw in a:

5. Remove the ambiguity by implementing typed pattern synonyms #2069

**Comment by andreasabel** [comment]
I think #2069 should be kept out of this issue.  Typed pattern synonyms would probably not replace the current "pattern macro" mechanism, but be another mechanism.  #2069 actually contains two different proposals: overloaded pattern synoyms, and "typed pattern synonyms" which I would analyse as "functions you may use in patterns".

I would also think 4. would be the way to go.

**Comment by gallais** [comment]
Nice! Should we also have a test case making it clear what ought to happen in case the user does define a DISPLAY pragma refolding a pattern synonym (potentially to something else)? E.g.

```agda
open import Agda.Builtin.List
open import Agda.Builtin.Equality

pattern [_] x = x ∷ []

singleton : {A : Set} → A → List A
singleton x = x ∷ []

{-# DISPLAY _∷_ x [] = singleton x #-}

_ : ∀ {A} (x : A) → singleton x ≡ [ x ]
_ = {!!}
```

**Comment by UlfNorell** [comment]
I'm not sure about **should**, but display forms are applied in `InternalToAbstract` and pattern synonym folding in `AbstractToConcrete`, so it's pretty clear what **does** happen.

**Comment by gallais** [comment]
I'd argue this is the right decision (the user's explicit choices should override the automated behaviour) and it would be nice to guard against regressions.

**Comment by UlfNorell** [comment]
I have no objections if you want to add a test case :).
