### ISSUE TITLE
Sections do not work on lhs

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2764]
```agda
postulate
  A : Set
  _+_ : A → A → A

data D : Set where
  c : A → D

mapD : (A → A) → D → D
mapD f (c a) = c (f a)

_⊕_ : A → D → D
a ⊕_ = mapD (a +_)
```
throws error
```
Could not parse the left-hand side a ⊕_
Operators used in the grammar:
  None
when scope checking the left-hand side a ⊕_ in the definition of
_⊕_
```

**Comment by nad** [comment]
From the [changelog](https://github.com/agda/agda/blob/1be557429fab09b32cac2c94d07a978de7df7dff/CHANGELOG.md#operator-syntax):

> Operator sections are not supported in patterns (with the exception of dot patterns), and notations coming from syntax declarations cannot be sectioned.

**Comment by nad** [comment]
See also the [code](https://github.com/agda/agda/blob/1be557429fab09b32cac2c94d07a978de7df7dff/src/full/Agda/Syntax/Concrete/Operators.hs#L146-L151):

> -- When parsing a pattern we also disallow the use of sections, mainly
> -- because there is little need for sections in patterns. Note that
> -- sections are parsed by splitting up names into multiple tokens
> -- (@\_+\_@ is replaced by @\_@, @+@ and @\_@), and if we were to support
> -- sections in patterns, then we would have to accept certain such
> -- sequences of tokens as single pattern variables.

**Comment by UlfNorell** [comment]
Since sections desugar to lambdas, it's not that surprising that you can't use them on the left. While we could conceivably do something sensible for definitions like `a ⊕_` above, I really don't think it's worth the implementation cost.

**Comment by andreasabel** [comment]
Well, the reason that this is so hard to implement points maybe to certain design decisions that could be revised.  For instance, we separate patterns from expressions already in concrete and abstract syntax.  This might not be necessary, and fusing them would spare us of code duplication in other parts as well.  For instance, display forms do not work on the lhs #1932, simply because no one likes to implement them twice, once for expressions and once for patterns.

**Comment by UlfNorell** [comment]
Are you suggesting that if we unified patterns and expressions in abstract syntax we could allow left-hand sides like this:
```agda
λ section → section ⊕ a = mapD (_+ a)
```
If not, then the problem with implementing lhs sections is that you need a different desugaring mechanism and I don't see that you gain enough to make it worth that.

**Comment by andreasabel** [comment]
No, expansion to lambda is just one way of treating sections.  In my example, the desugaring would apply both sides to a new variable.

**Comment by UlfNorell** [comment]
That's exactly what I meant. That's a different desugaring that only applies to left-hand sides that I don't believe is worth the effort.

**Comment by andreasabel** [comment]
Ok, this would require a different representation of sections (not just desugaring).
