### ISSUE TITLE
Inferred level expressions are often "reversed"

### ISSUE THREAD

**Issue by nad** [agda/agda#2765]
Consider the following code:
```agda
open import Agda.Primitive

postulate
  F : (ℓ : Level) → Set ℓ

G : (a b c : Level) → Set {!!}
G a b c = F a → F b → F c
```
The inferred value of the goal is `c ⊔ (b ⊔ a)`. It would be convenient for me if the inferred value was `a ⊔ b ⊔ c`, because then I would not need to edit the expression inferred by Agda.

I tried to fix this by replacing `foldr1 max as` with `foldr1 (flip max) as` in [`Agda.TypeChecking.Level.unlevelWithKit`](https://github.com/agda/agda/blob/1be557429fab09b32cac2c94d07a978de7df7dff/src/full/Agda/TypeChecking/Level.hs#L104), but this broke [a reflection test case](https://github.com/agda/agda/blob/1be557429fab09b32cac2c94d07a978de7df7dff/test/Succeed/Issue1207.agda), and might also have other negative consequences.

**Comment by andreasabel** [comment]
The current behavior is easily explained by the fact that the `levelMax` uses `sort` on level expressions.
```haskell
levelMax :: [PlusLevel] -> Level
levelMax as0 = Max $ ns ++ List.sort bs
  where ...
```
and sorting of variables is by de Bruijn index, not by de Bruijn level, which is more what the user expects.  Maybe in general, the order of variables should be reversed to consider earlier variables as lower.

**Comment by andreasabel** [comment]
I changed the `Ord` instance for `Term` to sort de Bruijn indices descendingly.
