### ISSUE TITLE
Another example of how our treatment of implicit arguments is sometimes annoying

### ISSUE THREAD

**Issue by nad** [agda/agda#2766]
The following code works fine:
```agda
postulate
  X : Set

data Kind : Set where
  x : Kind

F : Kind → Set
F x = X

P : Set₁
P = {A : Set} → A

P? : Kind → Set₁
P? x = P

postulate
  f : P → X

works : P → X
works p = f p
```
Let's try to generalise `f`:
```agda
postulate
  f? : ∀ {k} → P? k → F k

fails : P → X
fails p = f? p
```
Unfortunately `fails` is rejected, and the workarounds are somewhat annoying:
```agda
workaround₁ : P → X
workaround₁ p = f? (λ {_} → p)

workaround₂ : P → X
workaround₂ p = f? {k = x} p
```
Is there anything (non-drastic) we can do about this?

**Comment by nad** [comment]
The following workaround is less annoying, but might be hard to employ if `f? p` is a subexpression of some larger term:
```agda
workaround₃ : P → X
workaround₃ = f?
```

**Comment by gallais** [comment]
Another example:

```agda
module Issue2766 where

record P (A : Set) (B : Set) : Set where
  constructor _,_
  field fst : A
        snd : B
uncurry : {A B C : Set} (f : A → B → C) (p : P A B) → C
uncurry f p = f (P.fst p) (P.snd p)

-- argh : {A B C : Set} (f : A → B → {d : C} → C → C) (p : P A B) → {d : C} → C → C
-- argh f = uncurry (λ a b c → {!!})

yeah : {A B C : Set} (f : A → B → {d : C} → C → C) (p : P A B) → {d : C} → C → C
yeah f = uncurry (λ a b {_} c → {!!})
```

`argh` leads to the error:

```agda
(c : _29 f) → _31 f c != {d : .C} → .C → .C because one is an
implicit function type and the other is an explicit function type
when checking that the expression uncurry (λ a b c → ?) has type
P .A .B → {d : .C} → .C → .C
```

**Comment by andreasabel** [comment]
@gallais : For your example, Agda gets to the point 
```
a : ?A, b :? B |- \ c -> ? :  ?C
```
and it does not know whether `?C` will expand to a hidden Pi.  At this point, it decides to infer the type of `\ c -> ?`, which yields `(c : _29 f) -> _31 f c`.  Later it discovers that the type should have been a hidden Pi, and fails in the subtyping check.  The work around is to tell Agda that it should expect a hidden Pi (as you do).

A drastical solution would be to never infer the type of a lambda, or to split into two lambdas, one for checking, and one for inference.  Once this was the case,
`\ (x : _) -> ?` would be inferred, while `\ x -> ?` was checked.  This was counterintuitive to the users, and removed a long time ago.

**Comment by UlfNorell** [comment]
This is precisely #1079 (and #2099).
