### ISSUE TITLE
Internal error with sized types

### ISSUE THREAD

**Issue by carlostome** [agda/agda#2774]
The following program gives an internal error with agda 2.5.3 when trying to load it in emacs.
```agda
module Indexed-Nat where

  data IxNat : Size -> Set where
    z  : ∀ {i} -> IxNat (↑ i)
    s  : ∀ {i} -> IxNat i     -> IxNat (↑ i)

  _+ᵢ_ : ∀ {i j} → IxNat i → IxNat j → IxNat (i ⊔ˢ j)
  x +ᵢ y = ?

  data Expr : (i : Size) -> IxNat i -> Set where
    expr : ∀ {i j} {n : IxNat i} {m : IxNat j} -> Expr (i ⊔ˢ j) (n +ᵢ m)
```
The error is:
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/MetaVars.hs:115

**Comment by nad** [comment]
Here is a cut-down example:
```agda
open import Agda.Builtin.Size

data D : Size → Set where

postulate
  f : (i : Size) → D i

data P : (i : Size) → D i → Set where
  c : (i j : Size) → P (i ⊔ˢ j) (f _)
```

This is a regression: the code is accepted by Agda 2.5.1.1, but Agda 2.5.2 triggers an internal error.

**Comment by nad** [comment]
Bisection suggests that the problem was introduced by @andreasabel in 9a6128647a13b57d8a42590125af259196e9a743 ("Fixed 2046 by an agreeably dirty hack (no clean up yet)").

**Comment by jespercockx** [comment]
@andreasabel can you take a look?

**Comment by jespercockx** [comment]
I fixed the surface cause of the error, but the underlying hack is just as horrible as it ever was.
