### ISSUE TITLE
Irrelevance to be taken into account in 'with' abstraction.

### ISSUE THREAD

**Issue by xekoukou** [agda/agda#2775]
I finally found the reason why my abstractions do not work. I had an irrelevant term.

```agda
open import Relation.Binary.PropositionalEquality

data A : Set where
  a1 : A
  a2 : A


fun : A → A
fun a1 = a2
fun a2 = a1


gun : A → .(A → A) → A
gun a1 f = a2
gun a2 f = a1


bun : (x : A) → gun x fun ≡ a1
bun x with gun x hf where
  hf : A → A
  hf a1 = a2
  hf a2 = a1
... | q = {!!}
```

**Comment by andreasabel** [comment]
@xekoukou To clarify the bug report; I suppose you expect to see goal `q == a1`, but the goal is still `gun x fun == a1`.  I.e., you expect `with`-abstraction to take irrelevance into account.
