### ISSUE TITLE
Extending Agda reflection to introduce postulates

### ISSUE THREAD

**Issue by pavenvivek** [agda/agda#2782]
I propose adding a new feature in Agda reflection library to introduce postulates. I have been working on automating the generation of boilerplate codes for higher inductive types using Agda reflection. Currently, Agda reflection does not have any interface to introduce new postulates. I implemented declarePos (similar to declareDef) interface which allows me to add new postulates using reflection. Please let me know whether this feature can be added to Agda. If yes, I will give a pull request.

**Comment by UlfNorell** [comment]
Sure, PR against `stable-2.5`. Call it `declarePostulate` though, since "pos" is usually short for position.

**Comment by nad** [comment]
Please include a test case that checks that this facility fails in `--safe` mode.

**Comment by UlfNorell** [comment]
Fixed by PR #2786.

**Comment by andreasabel** [comment]
> Please include a test case that checks that this facility fails in `--safe` mode.

@nad @UlfNorell Apparently, such a test case was not added in #2786 (and never since).  I have detected this as part of my GenericError crusade.

**Comment by andreasabel** [comment]
Er, sorry, such a test was actually added but somehow it was immediately moved to `test/Succeed` by the PR author (maybe they did not understand the architecture of our test suite).
I'll duplicate it into `test/Fail`.
