### ISSUE TITLE
Move cubical primitives to dedicated module?

### ISSUE THREAD

**Issue by nad** [agda/agda#2784]
Currently `Agda.Primitive` contains a bunch of cubical primitives. Should these primitives really be present when `--cubical` mode is not used? Perhaps it would be better to move these primitives to `Agda.Primitive.Cubical`, and load this module automatically when `--cubical` is active. I guess that this module can contain an `OPTIONS` pragma with the `--cubical` and `--without-K` flags, in anticipation of a fix of #2487.

**Comment by Saizan** [comment]
We discussed this a few times: yes they "must" be there so that we have the appropriate "QName"s when we generate the reductions of "primComp" from data or record definitions. Currently Agda does not support "late-binding" of primitives in internal syntax.

Either that or we have to add --cubical to Agda.Builtin.Nat etc. which I don't believe helps with keeping things --cubical neutral.

**Comment by nad** [comment]
I noticed that several cubical primitives in `Agda.Primitive` compute even if `--cubical` is not active.

If we change things so that these primitives do not compute when `--cubical` is not active, and furthermore the (non-computing) primitives can be implemented (up to some notion of observational equivalence) in plain Agda, then I guess it is fine to keep them in `Agda.Primitive`.

> We discussed this a few times: yes they "must" be there so that we have the appropriate "QName"s when we generate the reductions of "primComp" from data or record definitions. Currently Agda does not support "late-binding" of primitives in internal syntax.

As far as I understand it `Agda.Primitive` is currently available in every module, but the names exported from this module are not in scope unless the module is actually imported. Perhaps `Agda.Primitive.Cubical` could be treated in the same way.

**Comment by Saizan** [comment]
If we load Agda.Primitive.Cubical no matter what flags are used then ok.

I guess the point of loading without importing is that you wouldn't throw an error if Agda.Primitive.Cubical is loaded and not imported and a flag incompatible with --cubical is used?

**Comment by nad** [comment]
If a flag that is incompatible with `--cubical` is used, then there is no need to do any work related to `--cubical`, is there? If `--cubical` is not active and we are in a setting that is compatible with `--cubical`, then it may make sense to do some preliminary work in case another module imports this module and turns on `--cubical`. However, this preliminary work should not have observable effects (ignoring the reflection machinery) inside the first module.

**Comment by Saizan** [comment]
Yes, the "preliminary work" won't be observable unless you import the
cubical primitives.

So why complicate things with loading the cubical primitives only
conditionally?

**Comment by nad** [comment]
> So why complicate things with loading the cubical primitives only conditionally?

Is the extra time spent on the preliminary (but wasted) work guaranteed to be negligible?

**Comment by UlfNorell** [comment]
Yes.

**Comment by nad** [comment]
> I guess that this module can contain an `OPTIONS` pragma with the `--cubical` and `--without-K` flags, in anticipation of a fix of #2487.

I see that you did not add such a pragma. See #2788 for some related discussion.
