### ISSUE TITLE
No cubical primitives/builtins without --cubical

### ISSUE THREAD

**Issue by nad** [agda/agda#2788]
I don't think it should be possible to declare the `--cubical` builtins and primitives if `--cubical` is not active.

One complication: Now every module depends on `Agda.Primitive.Cubical`. If this issue and #2487 is fixed, then we may end up in a situation in which every module has to be compatible with `--cubical`.

See also #2784.

**Comment by Saizan** [comment]
I thought we wanted "M depends on A" and "A is loaded while M is checked" be two different notions, exactly because of #2487 ?

**Comment by nad** [comment]
Yes, but with the current implementation they are (as far as I understand) not two different notions.
