### ISSUE TITLE
Narrow and broad options

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda#2789]
This is a result of the discussion we've had at agda/agda-stdlib#143. The proposal would help fix #2783 but  would require #2487 to be fixed first.

I think it should be possible for options such as `--safe` and `--without-k` to be applied in different modes.

1. _Broad file mode_. In this mode the option applies to a file. The entire contents of the file and the set of transitively imported files must obey the provided option. This is how options would currently work if #2487 were fixed. 
_Use_: to check entire projects (for instance via `Everything.agda` files).

Of the next two, I think perhaps only one is necessary.

2. _Narrow file mode_. In this mode the entire contents of the file must obey the option. However instead of checking the entire contents of all transitively imported files, only terms that were actually depended on by the terms in the original file would be type checked.
_Use_: to check files in libraries with unsafe portions. This would get around the problem in #2487. It wouldn't matter that portions of the primitive built-in modules were unsafe, as long as you didn't use the files directly then it would still be possible to type-check the top-level file as safe.

3. _As a pragma_.  This pragma would only apply to a single term. The term would be checked, and all terms it transitively depends on would be checked.
_Use_: to check individual proofs in files/libraries with unsafe portions. This would get around the problem in #2487. It wouldn't matter that portions of the primitive built-in modules were unsafe, as long as you didn't use the unsafe terms directly then the marked terms would still be safe.

I personally think the "pragma variant" would provide finer granularity and it would be easy enough to replicate the functionality of "narrow file mode" by applying the pragma to the top-level proofs in the file.

Examples: Consider the following the file `A.agda`:
```
module A where
  postulate S : Set
```

Now when type-checking the following:
```
-- type-checking would fail because of presence of the postulated `S` in `A.agda`
{-# OPTIONS --safe-broad #-}
module B where
  open import A
```

```
-- type-checking would pass as nothing depends on the postulated `S`
{-# OPTIONS --safe-narrow #-}
module B where
  open import A
```

```
-- type-checking would fail as T depends on the postulated `S`
{-# OPTIONS --safe-narrow #-}
module B where
  open import A

  T : Set
  T = S
```

```
-- type-checking would fail as term T depends on the postulated `S`
module B where
  open import A
  
  {-# SAFE_TERM #-}
  T : Set
  T = S
```

```
-- type-checking would pass as term T does not depend on the postulated `S`
module B where
  open import A
  open import Data.Fin
  
  {-# SAFE_TERM #-}
  T : Set
  T = Fin
```

**Comment by identicalsnowflake** [comment]
I'm not bothered by `--safe` having some sort of hard-coded allowance for the builtin primitive modules included with Agda itself. It makes little sense to trust the Agda devs to write the compiler and type checker, but not trust them to decide which builtin modules they think are safe.

That being said, outside of the packaged builtin primitives, I think `safe` should be pretty strict: I'd prefer it not even allow FFI bindings, since you could do nefarious things in there that would cause compiled code to behave maliciously.

Assuming there were a hardcoded allowance for the packaged builtin modules, would there still be a need for one of the latter two modes?

**Comment by MatthewDaggitt** [comment]
> Assuming there were a hardcoded allowance for the packaged builtin modules, would there still be a need for one of the latter two modes?

Yes. For example consider having a file `C` full of postulates, and a file `D` that contains lots of useful proofs, one or two of which depend on the postulates in `C`. Without one of the latter two proposed modes, there's no way of using the useful, safe theorems in `D` without becoming unable to check for safety.

The example above sounds trivial, but the hierarchy in the standard library is quite complex and practically none of it can be checked as safe under the current regime. 

This also applies to things like `--without-k`, which only a very small subset of terms in the standard library fall foul of and those that do certainly aren't widely depended on in the rest of the library. However the files that they exist in are widely depended on and hence the small set of terms falsely pollute the rest of the library.

**Comment by identicalsnowflake** [comment]
Well a lot of the postulates in the standard library are just asserting that the builtin ops behave correctly (like decidable equality on floats, etc.). I think those could be moved into the builtin modules. `erase` could probably be moved there, too.

But yeah, I see your point with something trickier like `--without-k`.

**Comment by MatthewDaggitt** [comment]
I should also mention that adding one of the latter two modes might remove the need to add the extra "Safe" files in the standard library as described in agda/agda-stdlib#143

**Comment by MatthewDaggitt** [comment]
I'm happy that to close this issue now that @fredrikNordvallForsberg work has been merged in and that we've managed to factor out the standard library to respect the pragmas. Thanks again @fredrikNordvallForsberg !
