### ISSUE TITLE
Safe modules can sometimes not be imported from unsafe modules

### ISSUE THREAD

**Issue by nad** [agda/agda#2792]
I decided to create a separate issue for a problem mentioned by @identicalsnowflake, see https://github.com/agda/agda/issues/2487#issuecomment-290693626.

Consider the following situation:
* `Safe.agda`:
  ```agda
  {-# OPTIONS --safe #-}

  module Safe where
  ```
* `Rewriting.agda`:
  ```agda
  {-# OPTIONS --rewriting #-}

  module Rewriting where

  open import Safe
  ```
If you try to load `Rewriting.agda`, then you get the following error (even if `Safe` has already been type-checked):
```
Cannot set OPTION pragma --rewriting with safe flag.
when scope checking the declaration
  open import Safe
```
However, the code is accepted if you instead load `Everything.agda`:
```agda
module Everything where

import Safe
import Rewriting
```

**Comment by nad** [comment]
@gallais, the following line that you seem to have written looks suspicious to me:
https://github.com/agda/agda/blob/961e6d878534a3502414b1b8cf4fc3c008c990fa/src/full/Agda/TypeChecking/Monad/Options.hs#L51
There is no documentation of what this line is intended to accomplish. Can you take a look?

**Comment by gallais** [comment]
IIRC it was a way for us to get `--safe` to be used to check dependencies when it was set as a pragma rather than a command-line option. Without this, the pragma option would only get applied to the file itself and the dependencies' safety would be ignored.

**Comment by andreasabel** [comment]
Please put that explanation __into the source code__.
And ideally, make this a habit.

**Comment by nad** [comment]
> IIRC it was a way for us to get `--safe` to be used to check dependencies when it was set as a pragma rather than a command-line option. Without this, the pragma option would only get applied to the file itself and the dependencies' safety would be ignored.

The current implementation fails at this task. The following code is accepted (if `Everything.agda` is loaded):
* `Unsafe.agda`:
  ```agda
  module Unsafe where

  postulate
    useful : {A : Set} → A
  ```
* `Safe.agda`:
  ```agda
  {-# OPTIONS --safe #-}

  module Safe where

  import Unsafe
  ```
* `Everything.agda`:
  ```agda
  import Unsafe
  import Safe
  ```
Note that the module `Unsafe` is typechecked before `--safe` is activated.
