### ISSUE TITLE
Case splitting error.

### ISSUE THREAD

**Issue by xekoukou** [agda/agda#2793]
If we look at the type of ```meq``` [here](https://github.com/xekoukou/sparrow/blob/12b0f0de32345388506237a7cfc4e195bfbaafb4/agda/LinFunContructw.agda#L117) , we will see that it has type : 
```meq   : ¬∅ (∧→ s) ≡ ¬∅ .mx```

Agda is able to case split on ```meq``` but then returns an error :
```
I'm not sure if there should be a case for the constructor refl,
because I get stuck when trying to solve the following unification
problems (inferred index ≟ expected index):
  del s (lind ←∧) ell ≟ ¬∅ mx
when checking the definition of poo
``` 

But this equation is wrong. It should be : 
```
  del (∧→ s) (lind ←∧) ell ≟ ¬∅ mx
```
which reduces to : 

```meq   : ¬∅ (∧→ s) ≡ ¬∅ .mx```

When I uncomment the previous pattern cases, i do not get the error.

**Comment by xekoukou** [comment]
I do not know if it is the same error but here is a small example : 

```
open import Relation.Binary.PropositionalEquality

data A : Set where
  a1 : A
  a2 : A


fun : A → A
fun a1 = a2
fun a2 = a1


gun : A → A
gun a with fun a
gun a | a1 = a1
gun a | a2 = a2


pun : (a : A) → gun a ≡ (fun a) → A
pun a eq with fun a
pun a eq | a1 = {!!}

```

If we look at the type of eq we will see this : 

```
Goal: A
————————————————————————————————————————————————————————————
eq : a1 ≡ a1
a  : A
```

We are allowed to case split ```eq``` but afterwards , we get an error : 
```
I'm not sure if there should be a case for the constructor refl,
because I get stuck when trying to solve the following unification
problems (inferred index ≟ expected index):
  gun a | w ≟ w
Possible reason why unification failed:
  Cannot solve variable w of type A with solution gun a | w because
  the variable occurs in the solution, or in the type of one of the
  variables in the solution.
when checking the definition of with-30
```


Notice that one case is missing. In my original code, this was to reduce the 'typecheck' time.

**Comment by jespercockx** [comment]
What version of Agda are you using? On my system I don't get that error when I case split on eq and then reload (only an error for incomplete pattern matching). So probably this has already been fixed.

**Comment by xekoukou** [comment]
I am at commit [c5faf7aecc4479ba3d31a84d7cad19874a42534d](https://github.com/agda/agda/tree/c5faf7aecc4479ba3d31a84d7cad19874a42534d) .

**Comment by xekoukou** [comment]
Ok, I do not get any errors with master.
