### ISSUE TITLE
The LaTeX backend ignores the "operator" aspect

### ISSUE THREAD

**Issue by nad** [agda/agda#2798]
The HTML backend attaches the `Operator` class to operator name parts. The LaTeX backend does not generate corresponding output: the second argument to `Name` is [thrown away](https://github.com/agda/agda/blob/e12fec58047ffae17084d8a9c06a98410794ddc6/src/full/Agda/Interaction/Highlighting/LaTeX.hs#L492).

**Comment by andreasabel** [comment]
Now, operators are wrapped with the `\AgdaOperator` command, which by default is the identity.  But one could change it to print operators in bold face, for instance.
