### ISSUE TITLE
Make `--caching` a pragma option

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2810]
I want to turn on `--caching` by setting the option in the file.

**Comment by andreasabel** [comment]
I see, doing this naively breaks the test case for #2728.

If `--caching` is given on the command line, it should be treated as a persistent pragma option.  Such a category does not exist yet.

**Comment by Saizan** [comment]
I think it should be fine with my last commit, but please test it before merging.

**Comment by nad** [comment]
What is a "persistent pragma option"?

**Comment by Saizan** [comment]
We figured out we probably don't need such a thing.

**Comment by andreasabel** [comment]
Works according to my limited testing.
