### ISSUE TITLE
travis output too long

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2815]
Usually, the log generated by our builds exceeds the maximum 10000 lines allowed by travis.

One way to get a shorter log would maybe to pass option `--ghc-options=-w` to cabal when installing the dependencies. 

Another this is to shorten the output of the tasty-silver runs, but this would probably require modifying the tasty-silver package, @phile314 ?
I could imagine to just see a summary of the test run, rather than one line per test.

**Comment by gallais** [comment]
> I could imagine to just see a summary of the test run, rather than one line per test.

We need to be a bit careful: by default if something runs for more than 10 minutes without outputting anything, the job is killed. We need to explicitly mark these commands with `travis_wait`.

**Comment by phile314** [comment]
Another reason for always printing everything was that we still get the intermediate output if the test runner crashes itself (e.g. out of memory, kill by travis, bugs, etc.). However, I agree that the output is too long and it is harder than it should be to see the test errors.

**Comment by andreasabel** [comment]
Maybe there is a middle ground where the test runner, as long as tests are succeeding, prints a status every `n` tests (configurable). Then we could choose a suitable `n` for travis.

**Comment by phile314** [comment]
By the way, I just discovered that travis can fold log sections if they are marked with a begin/end marker:
https://github.com/travis-ci/travis-ci/issues/2285

I will take a look if I can shorten the output of tasty-silver, but it may take some time until I get round to it.
