### ISSUE TITLE
BUILTIN BOOL gremlin

### ISSUE THREAD

**Issue by pigworker** [agda/agda#2821]
I ran a program that fiddles with bits, which went hilariously wrong. The behaviour I expected for "true" happened for "false", and vice versa. I was using
```agda
    data Two : Set where tt ff : Two
    {-# BUILTIN BOOL Two #-}
    {-# BUILTIN FALSE ff #-}
    {-# BUILTIN TRUE tt #-}
```
I got the correct behaviour by doing this instead:
```agda
    data Two : Set where tt ff : Two
    {-# COMPILE GHC Two = data Bool (True | False) #-}
```
I also got the correct behaviour by reordering the constructors:
```agda
    data Two : Set where ff tt : Two
    {-# BUILTIN BOOL Two #-}
    {-# BUILTIN FALSE ff #-}
    {-# BUILTIN TRUE tt #-}
```
The order of BUILTIN FALSE and BUILTIN TRUE seems not to matter, but the order of ff and tt seems to be the key.

On the face of it, there would seem to be something a little astray.

**Comment by UlfNorell** [comment]
Indeed. It looks like the primitives assume that builtin booleans compile to Haskell `Bool`, but the `BUILTIN` pragmas ensure no such thing. In the example below `Two` is compiled to a new datatype and the result of `"foo" == "bar"` is unsafeCoerced from an actual boolean to the new datatype.

Complete example:
```agda
data Two : Set where tt ff : Two
{-# BUILTIN BOOL Two #-}
{-# BUILTIN FALSE ff #-}
{-# BUILTIN TRUE tt #-}

postulate
  String : Set
{-# BUILTIN STRING String #-}

primitive
  primStringEquality : String → String → Two

_==_ = primStringEquality

show : Two → String
show tt = "TRUE"
show ff = "FALSE"

record ⊤ : Set where
{-# COMPILE GHC ⊤ = data () (()) #-}

postulate IO : Set → Set
{-# BUILTIN IO IO #-}
{-# COMPILE GHC IO = type IO #-}

{-# FOREIGN GHC import qualified Data.Text.IO #-}

postulate putStrLn : String → IO ⊤
{-# COMPILE GHC putStrLn = Data.Text.IO.putStrLn #-}

-- Prints TRUE when compiled.
main : IO ⊤
main = putStrLn (show ("foo" == "bar"))
```

**Comment by pigworker** [comment]
I forgot to mention, I discovered this problem in a [somewhat open situation](https://t.co/PF0kL3nv0x).

**Comment by UlfNorell** [comment]
I gathered as much from my Twitter feed :)

**Comment by UlfNorell** [comment]
The `BUILTIN LIST` has the same problem, except in that case you get a segmentation fault.
