### ISSUE TITLE
Allow {-# BUILTIN #-} in preamble and in parametrized modules

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2824]
The following is rejected with `Illegal declaration(s) before top-level module`:
```agda
{-# OPTIONS --rewriting #-}
open import Agda.Builtin.Equality
{-# BUILTIN REWRITE _≡_ #-}
module Issue2824 (A : Set) where
```
However, if I move the `{-# BUILTIN REWRITE #-}` pragma into the module, I get the error:
```
The BUILTIN pragma cannot appear inside a bound context (for
instance, in a parameterised module or as a local declaration)
when checking the pragma BUILTIN REWRITE _≡_
```
We could also fix the latter problem; allow to bind imported things in a parametrized context.

**Comment by andreasabel** [comment]
I fixed both problems.

In principle, we could also get the following to work, but it does not seem worth the effort:
```agda
module _ {a} {A : Set a} where

  data _≡_ (x : A) : A → Set a where
    refl : x ≡ x

  {-# BUILTIN EQUALITY _≡_ #-}
```

**Comment by nad** [comment]
I find the changelog entry somewhat confusing. First it discusses `BUILTIN REWRITE`, showing code that works, and then `BUILTIN EQUALITY`, showing code that does not work. Is there a difference between the two builtins? If not, then I suggest that we use the same builtin in all the examples, and mention afterwards that the other builtin is treated in the same way. Otherwise I think we should explain what the difference between the two builtins is.

**Comment by andreasabel** [comment]
I find it perfectly clear, but if you want to change it, please go ahead.

**Comment by nad** [comment]
> I find it perfectly clear, but if you want to change it, please go ahead.

OK, please explain what it means, then I can change it.

**Comment by UlfNorell** [comment]
What specifically is unclear? I find
```
BUILTIN pragmas can now appear before the top-level module header and in parametrized modules.
```
and
```
We cannot bind a built-in which depends on module parameters whose scope we are still in.
```
to explain the change quite well.

**Comment by nad** [comment]
The unclear part was the text "Note that the following is still illegal: [...]", leading me to wonder whether there was some special restriction related to `BUILTIN EQUALITY`. I'll update the text.
