### ISSUE TITLE
Variables off in with-clauses.  Parameter refinement?

### ISSUE THREAD

**Issue by laMudri** [agda/agda#2827]
Agda 2.5.3, stable release.

Consider the following file. In the final definition, the pattern match on `inferRes e` allows the type of hole 0 (the `just` case) to be computed to a function type, while hole 1 (the `nothing` case) is computed to `Lift One`. The module parameters `dummy` and `Dummy` are unused.

```agda
module Bidirectional {c} {dummy : Set} {l'} (C : Set c) (Dummy : Set) (_≤_ : C -> C -> Set l') where

open import Agda.Primitive using (Level; lzero; lsuc; _⊔_)

data List {a} (A : Set a) : Set a where
  nil : List A
  _::_ : forall (x : A) (xs : List A) -> List A

record Lift {a l} (A : Set a) : Set (a ⊔ l) where
  constructor lift
  field
    lower : A
open Lift public

record One : Set where
  constructor <>
open One public

data Maybe {a} (A : Set a) : Set a where
  just : A -> Maybe A
  nothing : Maybe A

mapMaybe : forall {a b} {A : Set a} {B : Set b} -> (A -> B) -> Maybe A -> Maybe B
mapMaybe f (just x) = just (f x)
mapMaybe f nothing = nothing

IfJust : forall {a p A} -> Maybe {a} A -> (A -> Set p) -> Set p
IfJust (just x) P = P x
IfJust nothing P = Lift One

record Sg {a b} (A : Set a) (B : A -> Set b) : Set (a ⊔ b) where
  constructor _,_
  field
    fst : A
    snd : B fst
open Sg public
infixr 1 _,_

mapSg : forall {a a' b b'} {A : Set a} {A' : Set a'} {B : A -> Set b} {B' : A' -> Set b'}
        (fa : A -> A') -> (forall {a} -> B a -> B' (fa a)) -> Sg A B -> Sg A' B'
mapSg fa fb (a , b) = fa a , fb b

QCtx : Set c
QCtx = List C

data Term : Set c where
  [_] : (e : Term) -> Term

data _|-_ (G : QCtx) : Term -> Set (l' ⊔ c) where
  [_] : forall {e} (er : G |- e) -> G |- [ e ]

inferRes : (t : Term) -> Maybe (Sg _ \ G -> G |- t)
inferRes [ e ] = mapMaybe (mapSg (\ x -> x) [_]) (inferRes e)

inferResBest : (t : Term) -> IfJust (inferRes t) \ { (G , _) -> forall {G'} -> G' |- t -> One }
inferResBest [ e ] with inferRes e
... | just _ = {!inferResBest e!}  -- hole 0
... | nothing = {!QCtx!}           -- hole 1
```

`inferResBest e` should fill hole 0, but the application fails to type, with the error message `c != dummy`. Similarly, normalising `QCtx` in hole 0 gives the result `List Dummy`, whereas in hole 1 `QCtx` normalises to `List C`. It appears that in hole 1, some off-by-one shift has happened to the variables. Removing either of the dummy parameters will lead to the next variables along being chosen.

**Comment by laMudri** [comment]
Additionally, if we instead have the following,

```agda
inferResBest [ e ] with inferRes e | QCtx
... | just _ | foo = {!foo!}  -- hole 0
... | nothing | foo = {!QCtx!}  -- hole 1
```

the generated with function fails with `w₁ !=< List C of type Set c`.

**Comment by andreasabel** [comment]
The variable confusion first appears in Agda-2.5.2.  In Agda-2.5.1.1 you get a different error message:
```
IfJust (inferRes e)
((λ { (G , snd) → {G' : List C₁} → G' |- t → One }) e)
!=< .G' |- [ e ] → One of type Set (l' ⊔ c)
when checking that the expression inferResBest e has type
.G' |- [ e ] → One
```
Let me guess the culprit: parameter refinement?

**Comment by UlfNorell** [comment]
It looks like something goes wrong when we insert the implicit `G'` in the with clause.

Shrunk test case:

```agda
module _ (C : Set) (Dummy : Set) where

data Maybe : Set where
  nothing : Maybe

IfJust : Maybe -> Set -> Set
IfJust nothing P = P

QCtx : Set
QCtx = C

postulate
  qCtx : QCtx

postulate
  inferRes : Maybe
                             -- v-- Implicit is important here
inferResBest : IfJust inferRes ({G' : Maybe} -> QCtx)
inferResBest with inferRes
... | nothing = qCtx    -- Error: Dummy != C when checking qCtx : C
```

**Comment by UlfNorell** [comment]
> Additionally, if we instead have the following,
> 
> ```agda
> inferResBest [ e ] with inferRes e | QCtx
> ... | just _ | foo = {!foo!}  -- hole 0
> ... | nothing | foo = {!QCtx!}  -- hole 1
> ```
> the generated with function fails with w₁ !=< List C of type Set c.

This is expected. If you abstract over `w₁ = QCtx`, you end up with `forall {G' : w₁} -> G' |- t -> One`, which is not well-typed.

**Comment by UlfNorell** [comment]
I might have found the problem:

https://github.com/agda/agda/blob/2417c7db6056d0e6fb24238cf1a6b70767e555fe/src/full/Agda/TypeChecking/Rules/LHS.hs#L654-L656
