### ISSUE TITLE
The Emacs mode does not handle .lagda.tex files

### ISSUE THREAD

**Issue by nad** [agda/agda#2836]
The Emacs mode doesn't know about `.lagda.tex` files, as witnessed by the following code:
```emacs
 (defun agda2-literate-p ()
   "Is the current buffer a literate Agda buffer?"
  (equal (file-name-extension (buffer-name)) "lagda"))
```

**Comment by nad** [comment]
Note also that `buffer-name` does not necessarily give the name of the buffer's file (if any). If the buffer is associated with a file, then `buffer-file-name` can be used.

**Comment by asr** [comment]
I'm confused. The changelog for 2.5.3 says

> Files ending in `.lagda.md` will be parsed as literate Markdown files.

and the commit closing this issue says

> Now `.lagda.md` files are treated as LaTeX-based literate Agda files (instead of as non-literate Agda files).

Were or weren't the `.lagda.md` files treated/parsed as literate files?

Has the above fix some observable change for the user?

**Comment by nad** [comment]
> Were or weren't the `.lagda.md` files treated/parsed as literate files?

Agda can parse such files, but the Emacs mode's goal detection machinery can only handle LaTeX-based literate Agda files.

> Has the above fix some observable change for the user?

First, note that the Agda mode is not activated by default in `.lagda.md` (or `.lagda.tex`) files. However, it can be turned on manually.

Previously `.lagda.md` files were treated as non-literate Agda files, which I guess worked in many cases (but including a question mark in non-Agda code could presumably mess things up). Now they are treated as literate Agda files, which I guess means that in many cases no goals will be detected (because the Emacs mode will not find a single block of Agda code).

As far as I know the Emacs mode has never really supported `.lagda.md` files (#2837).
