### ISSUE TITLE
The Emacs mode only handles LaTeX-based literate Agda

### ISSUE THREAD

**Issue by nad** [agda/agda#2837]
Perhaps we should support things like `.lagda.md` in the Emacs mode.

**Comment by nad** [comment]
If highlighting of comments is handled by the backend (#2794), then the main thing left to take care of is goal detection. I'd prefer to handle this in a uniform way, without special support for different literate styles.

One option might be to let the backend inform the frontend of the positions of new goals. This is unproblematic when an entire file is loaded. If a user performs free-form editing of a file and then uses commands like "give" or "refine" (which may introduce new goals), then the backend no longer knows where the goals are, but the frontend can (and does?) inform the backend about the location of the current goal.

Another option might be to use the current state machine for goal detection (although I'd prefer to retire it), but let the backend inform the frontend about which pieces of text should be treated as comments.

**Comment by jespercockx** [comment]
This currently makes it very annoying to write literate Agda files using markdown. @nad could you try to implement one of your proposed solutions?

**Comment by nad** [comment]
This is not currently a priority for me.

**Comment by emilyhorsman** [comment]
@nad How difficult would goal detection in `.lagda.{md,org,rst}` documents be? I'd give this a shot given some direction.

**Comment by nad** [comment]
Sorry for the late response, I've been on vacation.

At the moment the backend sends the command `(agda2-goals-action `<a list of goal numbers, in the order in which they appear in the buffer>`)` to the frontend when goals should be annotated. One possibility would be to include position information in the list.

The backend currently contains a piece of state that includes the goals:

https://github.com/agda/agda/blob/8c23ea4a137a464dea86ef7bdb31ecb104be670f/src/full/Agda/Interaction/InteractionTop.hs#L112-L118

I suppose that a first step could be to change the type of this field and see what breaks. When commands like give or refine are used the backend could perhaps parse the file, extract the positions of all goals, and update this field.

**Comment by jmchapman** [comment]
This is perhaps the biggest feature I was looking forward to in 2.6. Does it make sense to release support for .lagda.md if it doesn't work in the emacs mode yet?

**Comment by nad** [comment]
> Does it make sense to release support for .lagda.md if it doesn't work in the emacs mode yet?

Agda has supported `.lagda.md` since version 2.5.3.

**Comment by jmchapman** [comment]
Ah, I see. I didn't realise that support was being added incrementally.

**Comment by jespercockx** [comment]
I added support for modes that use ` ``` ` for code blocks. If there are any other supported literate modes that use a different separator, please let me know and I'll add them too.

**Comment by martinescardo** [comment]
I installed this version of Agda and tested my .lagda.md file and it works - thanks!

At the moment I have to switch to Agda mode manually and I can live with that. Can this be fixed, too? Or is there anything I can add to my .emacs file for this to happen automatically?

**Comment by jespercockx** [comment]
You can put this in your .emacs file
```
(add-to-list 'auto-mode-alist '("\\.lagda.md\\'" . agda2-mode))
```

**Comment by ice1000** [comment]
Cool!

**Comment by nad** [comment]
> If there are any other supported literate modes that use a different separator, please let me know and I'll add them too.

RST?

**Comment by jmchapman** [comment]
I just installed the RC.

I pasted `(add-to-list 'auto-mode-alist '("\\.lagda.md\\'" . agda2-mode))` into my `.emacs`. It starts agda mode by defualt.

**Comment by jmchapman** [comment]
I have just installed the RC (Agda-2.5.4.2.20190310) and added `(add-to-list 'auto-mode-alist '("\\.lagda.md\\'" . agda2-mode))` to my .emacs. It auto starts the agda mode when I open a `*.lagda.md` file. Goals are listed in the goal buffer but they remain as question marks and I cannot go into them.

**Comment by ice1000** [comment]
@jmchapman you need to compile Agda from the newest source code to get this update

**Comment by jmchapman** [comment]
Thank you for this. I understand that now. @martinescardo just pointed me in the right direction on the #3391.
