### ISSUE TITLE
Internal error in positivity with modules/datatype definitions

### ISSUE THREAD

**Issue by wenkokke** [agda/agda#2840]
Imagine I have a module which is parameterised on some type constructor, e.g. Algebra.FunctionProperties:

```agda
module One {Fun : Set → Set} where

  Prp : Set → Set
  Prp A = Fun A
```

And imagine I want to use these properties during the constructor of some datatype. I would try to use a mutual block:

```agda
module Two where

  data A : Set where

  mutual
    open One {Dat}

    data Dat : Set → Set where
      crash : Prp A
```

This results in an error, stating that "modules are not allowed in mutual blocks". No worries, I can get around this, using implicit arguments! (In the case of Algebra.FunctionProperties, all it takes is to define an anonymous module with the `Prp` argument made implicit, using that to open Algebra.FunctionProperties. In the case of `One`, I don't have to do any such hackery.)

```agda
module Three where

  data A : Set where

  open One

  data Dat : Set → Set where
    crash : Prp A
```

This results in an error:
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Positivity.hs:599
```

**Comment by wenkokke** [comment]
Oh, btw, I'm using Agda version 2.5.3-7654ff3.

**Comment by andreasabel** [comment]
I shrank this to:
```agda
Id : (F : Set → Set) → Set → Set
Id F = F

data D (A : Set) : Set where
  c : Id _ A
```
This seems to be a regression of 2.5.3.  Up to including 2.5.2 we get instead:
```
The target of a constructor must be the datatype applied to its
parameters, _F_2 A A isn't
when checking the constructor c in the declaration of D
```

**Comment by andreasabel** [comment]
Probably I introduced this regression by 46635bda44fb6cd5372e4ff0d5410efb42952653 which allows the target of a constructor to be a meta.  This meta cannot be solved because of non-linearity and is postponed, resulting in the crash in the positivity checker.  The latter is not prepared to see a meta as target of the constructor.

**Comment by andreasabel** [comment]
Fixed by not postponing the constraint.
Also, data parameters need not be metas in the target.
