### ISSUE TITLE
Opting out of idiom brackets

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2841]
I'd like a flag to opt out of idiom bracket syntax, e.g., to reuse the banana brackets for my own purposes.
Currently, I just get this error when trying to use the banana brackets:
```
in the name ⦇_⦈ᵗ, the part ⦇ is not valid
```
Related: #2186.

Anyway, isn't it enough to reserve the ASCII syntax `(| ... |)` for idiom brackets?

**Comment by UlfNorell** [comment]
Idiom brackets initially only supported the ASCII syntax. There was an opportunity to object to reserving the unicode banana brackets in PR #2104, but it's a bit late now.

I'm sure there are other unicode brackets you can use (or call the operator `-⦇_⦈ᵗ`).

As for adding a flag, we discussed this for do-notation and concluded that adding flags to change the (lexical) syntax was a bad idea.

**Comment by andreasabel** [comment]
> There was an opportunity to object to reserving the unicode banana brackets in PR #2104, but it's a bit late now.

Seems my last comment there did not get any response.

> As for adding a flag, we discussed this for do-notation and concluded that adding flags to change the (lexical) syntax was a bad idea.

A question is of course, why are banana brackets in the lexical syntax while many other brackets are not?  Why would they get the privileged treatment while the more often used equation chains do not, for instance?  In general, matching parentheses should be respected when parsing expressions in general, not just for a few privileged cases.

Having the banana brackets in the lexical syntax allows you to write
```
  (| f \ x -> x |)
```
but the singleton list
```
  [ \ x -> x ]
```
is rejected.  Then weight the number of uses of idiom brackets against the uses of list brackets (or the same brackets used in other data types).

Something for the big front-end makeover...

**Comment by andreasabel** [comment]
I did something small to give a better parse error, and added banana brackets to the Agda input method.  They look like idiom brackets and are not taken.
