### ISSUE TITLE
A request for a symbol input in the emacs mode

### ISSUE THREAD

**Issue by jonaprieto** [agda/agda#2843]
Hi all, 

I've been writing some functions like "nameFunction-∧" or "nameFunction-∨".
But now, I would like to remove the hyphen and subscript the symbols.
In the last case, for example, I can type "\_v" (fourth option) to write, "nameFunctionᵥ".

     \_v:(1/1) 1.̬ 2.̮ 3.̺ 4.ᵥ 5.ᵥ

But with the example "nameFunction-∧" I didn't find how.
I think It's not supported. If so, any chances to add to the emacs mode?

Thanks.

**Comment by guillaumebrunerie** [comment]
If you want a superscript `∧`, you can maybe simply use the ASCII `^` symbol (obtained by typing it twice).
If you want a subscript `∧`, well, it seems there is no such character in Unicode at all, so it can’t be supported by Agda…

**Comment by asr** [comment]
I could not find an Unicode symbol either. Reopen the issue if you find it, please.

**Comment by nad** [comment]
Note also that `ᵥ` is "LATIN SUBSCRIPT SMALL LETTER V".
