### ISSUE TITLE
Panic: unbound variable

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#2856]
It seems Agda is not very well equipped to handle dot patterns in nonstandard positions.
```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Equality

data _≅_ {A : Set} (x : A) : {B : Set} → B → Set where
  refl : x ≅ x

test₁ : (A : Set) (x y : A) (z : Nat) → x ≡ y → x ≅ (suc z) → y ≅ 1 → Nat
test₁ A (suc z) (suc zero) .z refl refl refl = {!!}

test₂ : (A : Set) (x y : A) (z : Nat) → x ≡ y → x ≅ 1 → y ≅ (suc z) → Nat
test₂ A (suc zero) (suc z) .z refl refl refl = {!!}
```
Error message:
```
Panic: unbound variable z (id: 28@7211838886485154243)
when checking that the expression z has type Nat
```
What's interesting is that in the first example, the error location is on the dot pattern `.z`, while in the second one it is on the *variable pattern* `z`.

**Comment by andreasabel** [comment]
Worked fine with 2.5.2, which reports:
```
x != y of type A
when checking that the pattern refl has type x ≡ y
```

**Comment by jespercockx** [comment]
Except that this shouldn't really be an error, or?

**Comment by andreasabel** [comment]
No. It should be able to instantiate `z` to `zero`.
So, it did not work fine; only failed more gracefully.
