### ISSUE TITLE
Feature request: Interleaving mutually-defined functions & datatypes

### ISSUE THREAD

**Issue by gallais** [agda/agda#2858]
It's quite common in papers to see proofs of multiple statements by mutual induction. And it is also quite common to see all of the base cases dealt with in one go, and then all of the similar induction cases too. It'd be nice if Agda allowed this kind of didactic presentation. E.g. in normalisation by evaluation:

```agda
reify   : (σ : Type) → [ Val σ ⟶ Lam σ ]
reflect : (σ : Type) → [ Lam σ ⟶ Val σ ]

-- base case: everything matches up!
reify   α = id
reflect α = id

-- arrow case: eta expansion of lambdas!
reify   (σ ⇒ τ) = λ b → L (reify τ (b E.extend (reflect σ (V z))))
reflect (σ ⇒ τ) = λ b ρ v → reflect τ (A (ren ρ b) (reify σ v))
```

Similarly for inductive types:

```agda
data Even : Nat → Set
data Odd  : Nat → Set

data Even | Odd where

  -- base cases
  zero : Even 0
  one  : Odd 1

  -- step cases: the predecessor is of the opposite Even-ness
  succ : ∀ {n} → Odd n → Even (suc n)
  succ : ∀ {n} → Even n → Odd (suc n)
```

This could apply to IR too, I suppose. Although it's not as clear to me whether this is really readable (it would potentially lead to a limited version of the kind of solutions SHE was offering to the expression problem though):

```agda
data FreshList : Set
fresh : ℕ -> FreshList -> Set

[] : FreshList
fresh n [] = ⊤

_∷_by_ : ∀ n ns → fresh n ns → FreshList
fresh n (m ∷ ns by _) with m Nat.≟ n
... | yes p = ⊥
... | no ¬p = fresh n ns
```

**Comment by andreasabel** [comment]
Yes, but then with a `constructor` keyword, please.

```agda
data FreshList : Set
fresh : ℕ -> FreshList -> Set

constructor
  [] : FreshList
fresh n [] = ⊤

constructor
  _∷_by_ : ∀ n ns → fresh n ns → FreshList
fresh n (m ∷ ns by _) with m Nat.≟ n
... | yes p = ⊥
... | no ¬p = fresh n ns
```
This can would then also work for Even/Odd:
```agda
data Even : Nat → Set
data Odd  : Nat → Set

constructor
  -- base cases
  zero : Even 0
  one  : Odd 1

  -- step cases: the predecessor is of the opposite Even-ness
  succ : ∀ {n} → Odd n → Even (suc n)
  succ : ∀ {n} → Even n → Odd (suc n)
```

**Comment by m0davis** [comment]
What about inferring whether a type declaration is intended as a constructor or a function by checking whether it is eventually (in the same module) given a definition? The Even/Odd example then becomes even simpler:
```
data Even : Nat → Set
data Odd  : Nat → Set

-- base cases
zero : Even 0
one  : Odd 1

-- step cases: the predecessor is of the opposite Even-ness
succ : ∀ {n} → Odd n → Even (suc n)
succ : ∀ {n} → Even n → Odd (suc n)
```

**Comment by jespercockx** [comment]
That'd potentially lead to unexpected effects when you really did forget to give an implementation to a function, though.
```
data Even : Nat → Set
data Odd  : Nat → Set

[many constructors and functions here]

Even-suc-suc : ∀ {n} → Even n → Even (suc (suc n))
-- oops, forgot to write the definition of Even-suc-suc
```
Now suddenly `Even-suc-suc` becomes a constructor of `Even`!

I think Andreas' proposal makes more sense and also works better with the syntax we already have for `postulate`.

**Comment by gallais** [comment]
After working on #3196 I think I now have an idea of how to implement this in the nicifier:

* Collect all the contiguous `LoneSig`s upon finding one in [`inferMutualBlocks`](https://github.com/agda/agda/blob/5971daea3a596690e5afe42a166a41c764773a80/src/full/Agda/Syntax/Concrete/Definitions.hs#L928)

* Do not let [`untilAllDefined` add new `LoneSig`s](https://github.com/agda/agda/blob/5971daea3a596690e5afe42a166a41c764773a80/src/full/Agda/Syntax/Concrete/Definitions.hs#L948), instead consider that the mutual block has ended

* Add a notion of `LoneConstructors` block

* In `inferMutualBlock`, before [returning a `NiceMutual`](https://github.com/agda/agda/blob/master/src/full/Agda/Syntax/Concrete/Definitions.hs#L886), group all the constructors & definitions in `LoneDefs` / `LoneConstructors` blocks based on the name of the declaration they correspond to

With this solution, we do not have to go through the *entire* file to decide whether
we are done accumulating constructors / function cases.

This would however not be backwards compatible. Code like:

```agda
data A : Set
P : (a b : A) → a ≡ b → Set

data A where
  a : A
  p : P a a refl → A

data B : A → Set where
  a : B a
  p : (pr : P a a refl) → B (p pr)

P b c eq = B a
```

would need to see the declaration of `B` lifted to the beginning of the block:

```agda
data A : Set
data B : A → Set
P : (a b : A) → a ≡ b → Set

data A where
  a : A
  p : P a a refl → A

data B where
  a : B a
  p : (pr : P a a refl) → B (p pr)

P b c eq = B a
```

If they are all mutually defined, I guess it's not that big of a deal but if one of them
is just an auxiliary definition, it may be a bit annoying?

**Comment by gallais** [comment]
Btw, `inferMutualBlock` is so liberal that we can throw entire modules between the
mutual declarations and the corresponding definitions!

I am not sure this is a good idea in terms of readability. :/

```agda
open import Data.Unit

A : Set
B : A → Set

A = ⊤

module MOD where
  C : Set
  C = ⊤

B tt = ⊤
```

Edit: that being said, it's probably super useful for instantiating e.g. `RawMonad` and then opening it.

**Comment by nad** [comment]
> This would however not be backwards compatible.

Is there a good reason for breaking backwards compatibility?

**Comment by gallais** [comment]
> Is there a good reason for breaking backwards compatibility?

In the current nicifier when we find a block of `LoneDefs` we immediately [remove the
corresponding `LoneSigs`](https://github.com/agda/agda/blob/731439680a13e717bfc1bc2c5d8dea429903732d/src/full/Agda/Syntax/Concrete/Definitions.hs#L900-L901) from the environment. We consider that all the equations
should come in one block and we are done with these definitions.

As soon as we run out of `LoneSigs`, we consider that we have found a whole mutual
block and [return](https://github.com/agda/agda/blob/731439680a13e717bfc1bc2c5d8dea429903732d/src/full/Agda/Syntax/Concrete/Definitions.hs#L892-L893). If we allow users to interleave `LoneDefs` for various functions, this
is not true anymore:

```agda
even : Nat → Bool
odd  : Nat → Bool

even 0 = true
odd  0 = false
-- Here we have run out of LoneSigs

-- But there are some more LoneDefs to accumulate:
even (suc n) = odd n
odd (suc n) = even n
```

So we can't use `noLoneSigs` as a sign that we are exiting a mutual block anymore. 
What else can we do to avoid having to go through the *whole* file to decide whether
we are done or not?

One solution is to consider that if we start talking about new definitions (by using a
`LoneSig`) then we are done with the previous block of mutually-defined ones.

**Comment by nad** [comment]
> What else can we do to avoid having to go through the whole file to decide whether
we are done or not?

Perhaps we could use the coverage checker.

If it is too hard (especially for human beings) to figure out how the definitions should be grouped, then I would prefer that we required the use of a keyword (ideally `mutual`, but I'm not sure if this would break old code).

**Comment by gallais** [comment]
> Perhaps we could use the coverage checker.

Given that we would have the ability to also add constructors, I don't think that would
give us accurate results. And AFAIK coverage checking happens way later in the pipeline.

> If it is too hard (especially for human beings) to figure out how the definitions should be grouped

The solution I have in mind clarifies where the boundaries of the blocks are: you need
to be upfront about all of the names you are planning to mutually define in the block.
Any new declaration starts a new block (and we can raise warnings / errors about
missing definitions).


At the moment, you can have weird runaway mutual blocks: as long as you make sure there
is still one lone signature without an accompanying definition, you can keep adding
new declarations to the mutual block. E.g. this is one big mutual block:

```agda
R : Set
T : Set

T = R

-- because R hasn't been defined, we can chuck in some more mutual declarations
U : Set
V : Set

R = V
V = U

-- Now it's U which hasn't been defined: the mutual block is still ongoing!
W : Set

W = U
U = ⊤
```

With the change I propose, you'd get a warning at `U : Set` because `R` has not been defined and an error at `R = V` because you're attempting to redefine `R`.

**Comment by UlfNorell** [comment]
Does this not limit the expressiveness of the current (new) mutual blocks? It might be that you need an earlier definition to reduce in order to state the type of a later one. I'm sure the type-theory-in-type-theory people have lots of examples of this :P

**Comment by nad** [comment]
I wonder if we make use of the feature that @gallais wants to remove to state unification problems in the test suite.

**Comment by gallais** [comment]
> Does this not limit the expressiveness of the current (new) mutual blocks?

I don't know because of the grouping pass that would reorder the equations in name-based
blocks so that we could feed the output of the modified nicifier directly to the current setup.
These blocks could be fed in the same order as the signatures. So you would preserve the
fact that some definitions come before others when typechecking.


I think the changes would not be that big so I am more and more tempted to just implement
it on a branch, see whether it breaks any test and if it doesn't then ask the wider community
if they have code I could test it on.

**Comment by gallais** [comment]
Okay, my experiment failed: when you stop relying on `noLoneSigs` to decide where to
split the mutual blocks, you run into a _lot_ of issues. Waiting for a `LoneSig` is not enough:
you also want to break on `NiceMutual`, sometimes on `postulate` or `module`s (but
not necessarily all the time!). This is way more complicated than #3196 led me to believe.

I think @nad's suggestion to use a keyword is the way to go.

**Comment by nad** [comment]
If anyone plans to continue working on this I suggest that we try to nail down a rough design before too much time is spent on implementing things.

**Comment by jespercockx** [comment]
Maybe this would be a good discussion/code sprint for the upcoming AIM in Nottingham?

**Comment by canndrew** [comment]
Any updates on this? I've been trying to define type theory in type theory ever since I started learning type theory years ago. First I had to wait for people to invent HoTT, then I had to wait for people to make HoTT computable, then I had to wait for cubical types to make it into Agda, now it looks like the only thing holding me back is Agda's `mutual` blocks not being mutual enough.

If I fork Agda is there some slapdash change I can make that'll make interleaving constructor definitions possible? I don't care if it makes typechecking 100x slower if it works.

**Comment by txa** [comment]
I would like to reiterate the proposal. Since this is now the end of AIM XXX maybe it can be realistically tackled at the next AIM in Edinburgh. In the meantime we can use the work around by Szumi, eg. see https://bitbucket.org/akaposi/qiit/src/master/UniversalQIIT.agda

**Comment by andreasabel** [comment]
@txa writes:
I thought we were already able to split cases but it seems I was wrong:
```agda
f : Bool → Bool

f true = true

b : Bool
b = false

f false = b
``` 
doesn’t work. Was this already a feature request? I actually need it mostly for pedagogical reasons. I want to prove a theorem, ah I need a lemma, let’s prove it and then continue.

Yes, I know I could use `with` but this gets to complicated. However, splitting cases is also very useful for inductive-inductive definitions.

**Comment by andreasabel** [comment]
> ```agda
> f : Bool → Bool
> 
> f true = true
> 
> b : Bool
> b = false
> 
> f false = b
> ```

The problem of splitting cases is that it is had to tell when the definition of a function is complete (well, latest at the end of the file).  This is both a problem for implementation (think prefix copatterns) and code readability.  It seems that we would need a syntax for definitely closing a definition, like `end f` (rings MODULA).

**Comment by txa** [comment]
Functions should be complete add the end of the module. 

There are cases where it improves code explainability. You start writing a function and then you need another one. Ok, you can either use a where or you define it before. Both options are not ideal, maybe you want to use the function in more than one case or you want to use it later. Putting  it before destroys the line of thought - why is this function needed? We will only see later.

**Comment by andreasabel** [comment]
> Functions should be complete add the end of the module.

This suggest that one should use `module _ where` as replacement for the old `mutual`, see also #3246.  We could have a keyword like `section` to substitute for `module _ where` (also with parameters).  I tend to forget the `_` and often write something like `module (A : Set) where` on the first iteration.

**Comment by gallais** [comment]
Ok, I think my PR is ready. Note however that this won't magically solve all
of the requests in this thread. Thorsten's latest example for instance won't
check.

In the following code block `b : Bool` won't be in scope for `f : Bool → Bool`:

```agda
infix mutual
    f : Bool → Bool

    f true = true

    b : Bool
    b = false

    f false = b
```

Indeed, we elaborate these `infix mutual` blocks to new-style mutual blocks by:
* leaving the signatures where they are
* grouping the clauses for a function together with the first of them
* grouping the constructors for a datatype together with the first of them

So the above block elaborates to one with no forward declarations:

```agda
f : Bool → Bool
f true = true
f false = b

b : Bool
b = false
```

All of the original motivating examples are handled perfectly though.

**Comment by jespercockx** [comment]
A bit of brainstorming: in order to handle the examples that cannot be desugared to current new-style mutual blocks, we'd need to incrementalize the checking of both datatypes and function definitions: it should be possible to add constructors and clauses to any declaration in the current mutual block. This would also require moving certain checks that are currently done on the declaration-level to the end of the mutual block (in particular coverage checking).

**Comment by andreasabel** [comment]
Link to a bikeshedding discussion: https://agda.zulipchat.com/#narrow/stream/257010-aim-xxxiii/topic/Bikeshedding.20.235001
