### ISSUE TITLE
Migrate internal-tests test suite into agda-tests test-suite

### ISSUE THREAD

**Issue by asr** [agda/agda#2861]
Right now we have two cabal test-suites `agda-tests` and `internal-tests`. Since `agda-tests` is more functional, I'm working in migrate `internal-tests` into `agda-tests`.

So far the only drawback will be that we won't can to use `$quickCheckAll`, that is, the names of the QuickCheck properties must be added manually.

Are you agree in the migration with the above drawback?

**Comment by andreasabel** [comment]
Could you elaborate a bit more on the situation, what are the advantages of fusing these two test-suites that compensate the extra maintenance effort?

Also, recently, I came across the `doctest` package at https://hackage.haskell.org/package/doctest-0.13.0.
This tool allows to extract and run test cases embedded in haddock comments.  I also supports quickcheck.  One can specify the properties using the `prop>` tag in haddock comments, and doctest runs them.  

In general, I think having properties being part of the documentation is a very good idea; they serve a twofold purpose there: explaining and verifying the code.

Running doctest seems to be rather easy.  For instance, in the bnfc project there is the following entry in the .cabal file:
```
Test-suite bnfc-doctests
  type:           exitcode-stdio-1.0
  ghc-options:    -threaded
  main-is:        doctests.hs
  build-depends:  base, doctest >= 0.8
  HS-source-dirs: test
```
and then, in `test/doctests.hs`:
```haskell
import Test.DocTest
main = doctest
    [ "-isrc"
    , "-idist/build/autogen/"
    , "-idist/build/bnfc/bnfc-tmp"
    , "-XOverloadedStrings"
    , "-XFlexibleContexts"
    , "-XRecordWildCards"
    , "src/PrintBNF.hs"
    , "src/Main.hs" ]
```
This recursively collects all documentation-embedded tests and runs them.

Fazit:  If we do some refactoring on our quickcheck properties, we should consider turning them into doctests.

**Comment by asr** [comment]
> what are the advantages of fusing these two test-suites that compensate the extra maintenance effort?

It seem that using [this](https://github.com/nick8325/quickcheck/pull/192) PR, written by @Lysxia, we could use `quickCheckAll` with the Tasty framework, that is, there would be no an extra maintenance effort. I'm testing the PR.

For discussing about using `doctest` on the internal tests, I created https://github.com/agda/agda/issues/2882.

**Comment by asr** [comment]
Blocked by https://github.com/nick8325/quickcheck/pull/192.
