### ISSUE TITLE
Lexical error for \- (hyphen)

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2870]
```agda
postulate a­b : Set  -- a \- b
```
This reports a lexical error.  I think the error message should be more user-friendly.

**Comment by UlfNorell** [comment]
What's special about hyphen? Why should it be an error at all?

**Comment by andreasabel** [comment]
I am not sure.  Maybe it is not printed unless it is at the end of the line (speculating), thus, it could be confusing to allow it in identifiers.  As you can see, it is not printed by github (or it did already not survive the copy-paste).

The reason I got this error is because I typed `\ -` by accident when I wanted to type `-`, and then was a bit surprised to get a lexical error.  I don't mind to get the error, but it should be less terse.

**Comment by andreasabel** [comment]
```haskell
module Agda.Syntax.Parser.LexActions
foolAlex :: AlexInput -> AlexInput
--   Further, non-printable Unicode characters are translated to an
--   arbitrary, harmless ASCII non-printable character, @'\1'@.
```
Apparently, hyphen is a non-printable character.

**Comment by andreasabel** [comment]
Added a slightly nicer error message.

**Comment by nad** [comment]
I suspect that @andreasabel used U+00AD SOFT HYPHEN, not U+2010 HYPHEN.

**Comment by andreasabel** [comment]
Well, what ever one gets in Agda input mode when typing `\ -`.

**Comment by nad** [comment]
You can get both U+00AD SOFT HYPHEN and U+2010 HYPHEN.
