### ISSUE TITLE
Refinement problem in presence of overloaded constructors

### ISSUE THREAD

**Issue by m0davis** [agda/agda#2873]
I am running into a problem where `agda2-refine` is reporting `Cannot refine` when I would have expected it to work.

```agda
module RefineTests where

  open import Agda.Builtin.Nat

  data Vec {a} (A : Set a) : Nat → Set a where
    []  : Vec A zero
    _∷_ : ∀ {n} (x : A) (xs : Vec A n) → Vec A (suc n)

  module Fails where
    open import Agda.Builtin.List

    test : Vec Nat 1
    test = {!!} -- C-c C-r fails here

  module Succeeds where
    open import Agda.Builtin.List public

    test : Vec Nat 1
    test = {!!} -- C-c C-r succeeds here
```

In the code above, note that the `public` declaration allows refinement to go through.

For what it's worth, the problem began for me when using the `agda-prelude` in the following code:

```agda
module PreludeRefineFails where
  open import Prelude
  test : Vec Nat 1
  test = {!!} -- C-c C-r fails here
```

I found a workaround in the following manner:

```agda
module PreludeRefineSucceeds where
  open import Prelude.Vec
  open import Prelude
  test : Vec Nat 1
  test = {!!} -- C-c C-r succeeds here
```

**Comment by andreasabel** [comment]
It fails even if you put the ambiguous constructor `_::_` in the hole and then ask Agda to refine.
For some strange reason, some arbitrary disambiguation happens when Agda tries to give `(_::_) ? ?`:
``` 
giving expression ... _∷_
Con (AmbQ {unAmbQ = [Agda.Builtin.List.List._∷_,Issue2873.Vec._∷_]})

giving expression ... _∷_ ?
App (AppInfo ...) (Con (AmbQ {unAmbQ = [Agda.Builtin.List.List._∷_,Issue2873.Vec._∷_]}))...

giving expression ? ...∷ ?
App (AppInfo ...) (App (AppInfo ...) (Con (AmbQ {unAmbQ = [Agda.Builtin.List.List._∷_]}))
```
Somehow some wrong disambiguation happened here.

**Comment by andreasabel** [comment]
Not so mysterious anymore given https://github.com/agda/agda/commit/3c6e42fe4b8a133b3c4deab8f24308c15d078bca introduced an indirection which would print to concrete syntax and scope-check back to abstract syntax.  Yeah, that does not fly.  Especially not with ambiguous constructors.

**Comment by andreasabel** [comment]
Ok, I am fixing this regression by reverting the code introduced in https://github.com/agda/agda/commit/3c6e42fe4b8a133b3c4deab8f24308c15d078bca . This leaves #737 broken, unfortunately.
