### ISSUE TITLE
Include COMPILE GHC pragmas for size primitives

### ISSUE THREAD

**Issue by nad** [agda/agda#2879]
The following code can be compiled:
```agda
open import Agda.Builtin.Size

data D (i : Size) : Set where

f : ∀ {i} → D i → D i
f ()
```
However, if I try to export `f` under a specific name, then Agda complains:
```agda
{-# COMPILE GHC f as f #-}
```
```
The type Size cannot be translated to a Haskell type.
```

**Comment by andreasabel** [comment]
You get the same error if `Size` is just a postulated `Set`.

You could fix this by replacing some calls to `notAHaskellType` by `return mazAnyType`.

**Comment by UlfNorell** [comment]
Levels get special treatment when translating Agda types to Haskell. I guess it would make sense to do the same for sizes?

**Comment by andreasabel** [comment]
Yes, indeed.

**Comment by nad** [comment]
So, how should sizes be translated? The `Level` type is translated to the unit type (`()`), and I guess we could do the same for the `Size` type, but what about the operations? It seems to me as if certain level expressions are translated to `()`. What part of the code performs this translation?

**Comment by UlfNorell** [comment]
> What part of the code performs this translation?

https://github.com/agda/agda/blob/c2bf416f57f73594129141a105d35bd1c79ab7d1/src/full/Agda/Compiler/ToTreeless.hs#L400

**Comment by nad** [comment]
I have a hard time figuring out how the compiler works, there is very little documentation (that I've found, at least). It seems as if code involving sized types is currently compiled successfully in many cases, but I'm not sure if this is by design or by accident. Sizes are typically unused, so they often seem to be compiled away, and thus it may not matter that `error` is generated for things like `Size`. However, I don't know under what circumstances this happens, and as noted above one cannot use certain `GHC` pragmas.

I tried to add the following pragmas to `Agda.Builtin.Size`:
```agda
{-# COMPILE GHC Size   = ()         #-}
{-# COMPILE GHC Size<_ = \_ -> ()   #-}
{-# COMPILE GHC ↑_     = \_ -> ()   #-}
{-# COMPILE GHC ω      = ()         #-}
{-# COMPILE GHC _⊔ˢ_   = \_ _ -> () #-}
```
However, this led to problems. Now `Size< i` is compiled into `() AgdaAny`, which GHC rejects. I guess that the `COMPILE GHC` pragmas are only used for terms, not types. Why and how do the presence of pragmas change the way that types are compiled?

**Comment by UlfNorell** [comment]
> I have a hard time figuring out how the compiler works, there is very little documentation (that I've found, at least).

Did you read http://agda.readthedocs.io/en/latest/language/foreign-function-interface.html#the-compile-pragma ?

**Comment by nad** [comment]
I had missed the `type` pragma. Thanks. However, that text does not (and should not) explain how the compiler is implemented, and I don't think it answers my question about why and how term-level pragmas affect the generation of Haskell types.

**Comment by UlfNorell** [comment]
I wouldn't expect term-level pragmas to affect Haskell type generation. Can you construct an example that doesn't involve the size type formers?

**Comment by nad** [comment]
Yes. The following code can be compiled successfully:
```agda
postulate
  F : Set₁ → Set₁

record R : Set₁ where
  field
    f : F Set
```
However, if we add the following pragma, then the compiler complains:
```agda
{-# COMPILE GHC F = \_ -> () #-}
```
Error message:
```
    • Expecting one fewer arguments to ‘()’
      Expected kind ‘* -> *’, but ‘()’ has kind ‘*’
    • In the type ‘(() ())’
      In the definition of data constructor ‘C1’
      In the newtype declaration for ‘T4’
   |
17 | newtype T4 = C1 (() ())
   |                  ^^^^^
```

**Comment by nad** [comment]
I tried to give two pragmas for (for instance) `Size`:
```agda
{-# COMPILE GHC Size = type () #-}
{-# COMPILE GHC Size = ()      #-}
```
However, this does not work:
```
Conflicting GHC pragmas for Agda.Builtin.Size.Size at
[...]
```
Thus the term-level translation of `Size` is still a call to `error` (and similarly for `Size<_`):
```haskell
name8 = "Agda.Builtin.Size.Size"
type T8 = ()
d8
  = error
      "MAlonzo Runtime Error: postulate evaluated: Agda.Builtin.Size.Size"
```
Given that sizes should never be forced I suppose that this is OK.

**Comment by nad** [comment]
@UlfNorell, if the example I included [above](https://github.com/agda/agda/issues/2879#issuecomment-358735852) requires action, then we should perhaps open a new issue for it.

**Comment by UlfNorell** [comment]
It's not a critical problem, but clearly something is not right. A new issue is probably called for.
