### ISSUE TITLE
Disallow FFI binding for defined functions when --safe is used

### ISSUE THREAD

**Issue by nad** [agda/agda#2880]
Should we allow use of the FFI when `--safe` is active? My inclination would be to say no.

**Comment by UlfNorell** [comment]
What are you basing that on?

**Comment by nad** [comment]
The question is whether `--safe` should mean merely "no inconsistencies (other than via bugs)" or also "no segfaults etc.".

**Comment by UlfNorell** [comment]
The FFI doesn't let you cause segfaults etc (other than via bugs). Do you have an example.

**Comment by nad** [comment]
From the documentation:

> It is possible to give Haskell definitions to defined (non-postulate) Agda functions. In this case the Agda definition will be used at type-checking time and the Haskell definition at runtime. However, there are no checks to ensure that the Agda code and the Haskell code behave the same and discrepancies may lead to undefined behaviour.

**Comment by UlfNorell** [comment]
Right, that particular feature should not be allowed in safe mode.

**Comment by UlfNorell** [comment]
The only other way to use the FFI is for postulates, and those are already not allowed.

**Comment by gallais** [comment]
I have something mostly working. The problem being that we *do* have `COMPILE`
pragmas in `Agda.Builtin.*` modules targetting UHC / JS.

E.g. https://agda.github.io/agda-stdlib/Agda.Builtin.List.html#132

How should we deal with this?

**Comment by nad** [comment]
Now `--safe` is ignored when builtin modules are checked, right?

**Comment by gallais** [comment]
Good point. Let me merge master into my branch and have a look.

**Comment by gallais** [comment]
Still does not work. I think the problem is that `getSafeMode` does not respect the
logic of ignoring `--safe` when we are checking a `prim`. Is that a bug @fredrikNordvallForsberg?

**Comment by gallais** [comment]
Ah, I guess we're using some ad-hoc logic here:

https://github.com/agda/agda/commit/86eb792a27823946c904a93c6c1c44087fbedcfa#diff-7568965831e2a7f801464fb14d33ce43R1438

and I should use the same logic in `niceDecls`!

**Comment by fredrikNordvallForsberg** [comment]
> I think the problem is that getSafeMode does not respect the
logic of ignoring --safe when we are checking a prim. Is that a bug @fredrikNordvallForsberg?

As you've discovered in your later comment: by design, only postulates together with `--safe` are allowed in some (whitelisted) builtin modules, so no, not a bug.
