### ISSUE TITLE
Missing PDF user manual in the tarball

### ISSUE THREAD

**Issue by asr** [agda/agda#2884]
I want to to include the PDF user manual in the tarball (from the next release if possible).

**Comment by asr** [comment]
From the above commit you can run

```
$ make doc-pdf
```

for generating the user manual in PDF:

```

$ your-pdf-viewer doc/user-manual/_build/latex/Agda.pdf
```

**Comment by asr** [comment]
I made some small changes, so now running

```
make user-manual-pdf
```

generates the user manual  in `doc/user-manual.pdf`.

**Comment by andreasabel** [comment]
Thanks, very good initiative, @asr.

**Comment by asr** [comment]
I just realised that there are some missing subsections of documentation in the PDF.

**Comment by asr** [comment]
I couldn't reproduce the problem.
