### ISSUE TITLE
Add a warning for infix notations without corresponding fixity declaration

### ISSUE THREAD

**Issue by gallais** [agda/agda#2899]
I thought about this because of agda/agda-stdlib#207

**Comment by andreasabel** [comment]
Yes, thinkable, but I probably would not want this as the default.  Assigning fixities is this arduous chore I only attack if there is no way to proceed sensibly without. ;-)

**Comment by gallais** [comment]
I got the warning working and I'm currently adding a new `WarningMode`
called `AllWarnings` which is more verbose than the default (renamed
`UsualWarnings` rather than `LeaveAlone`).

**Comment by andreasabel** [comment]
Well, bracketing constructs like `[_]` or `[_,_]` do not need a fixity, in fact, since they are neither pre/post nor infix operators, a precedence or associativity value for these does not make sense.
The warning mechanism should be adapted to disregard these.

**Comment by gallais** [comment]
We should probably not warn about the ones that are not exported:
* declarations in `private` blocks
* declarations in unnamed `where` clauses

**Comment by nad** [comment]
And you shouldn't warn about bound operators. (I don't know if the current implementation warns or not.)

**Comment by gallais** [comment]
Should I leave the warning turned off by default?

**Comment by UlfNorell** [comment]
Yes please.
