### ISSUE TITLE
Case-splitting should not generate patterns containing pattern synonyms

### ISSUE THREAD

**Issue by nad** [agda/agda#2902]
Consider the following code:
```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Unit

data ⊥ : Set where

¬_ : Set → Set
¬ P = P → ⊥

data _⊎_ (A B : Set) : Set where
  inj₁ : A → A ⊎ B
  inj₂ : B → A ⊎ B

Dec : Set → Set
Dec P = P ⊎ (¬ P)

pattern yes p = inj₁ p
pattern no  p = inj₂ p

Fin : Nat → Set
Fin zero    = ⊥
Fin (suc n) = ⊤ ⊎ Fin n

pattern fzero  = inj₁ tt
pattern fsuc i = inj₂ i

Bool : Set
Bool = ⊤ ⊎ ⊤

pattern true  = inj₁ tt
pattern false = inj₂ tt
```
Now let's define a function from `Bool`:
```agda
F : Bool → Set
F b = {!b!}
```
In order to avoid some typing, let us use the case-splitting machinery. We end up with the following code:
```agda
F : Bool → Set
F (yes x) = {!!}
F (fsuc x) = {!!}
```
This is perhaps not very helpful.

A proper fix to this problem might be to associate certain pattern synonyms to certain type "abbreviations" in a principled way (yet to be designed). In the absence of a proper fix I suggest that patterns generated by the case-splitting machinery should never contain pattern synonyms.

This is a regression, Agda 2.5.3 generates the following code:
```agda
F : Bool → Set
F (inj₁ x) = {!!}
F (inj₂ x) = {!!}
```

**Comment by UlfNorell** [comment]
This is a deliberate change. See #2762. Typed pattern synonyms are #2069 (still open).

**Comment by nad** [comment]
Perhaps this is a deliberate change, but I think it is a change to the worse. I think that we should revert this change.

I don't see how typed pattern synonyms would address this problem.

**Comment by UlfNorell** [comment]
I suppose you are also suggesting to not use pattern synonyms when printing goals etc.

A compromise might be to add a pragma to declare certain pattern synonyms *write-only*.

@gallais do you want to weigh in?

**Comment by gallais** [comment]
I suppose we could abstain when the folding is ambiguous or only one constructor deep?

Edit: note that using a record (a bit like a newtype wrapper) for these defined `Set`s would prevent this.

**Comment by nad** [comment]
> I suppose you are also suggesting to not use pattern synonyms when printing goals etc.

Yes, unless pattern synonyms were used in user-written code.

> Edit: note that using a record (a bit like a newtype wrapper) for these defined `Set`s would prevent this.

The point of defining the types in this way is to make it possible to use library functions defined for the binary sum type without any syntactic overhead.

**Comment by nad** [comment]
> I suppose we could abstain when the folding is ambiguous or only one constructor deep?

Consider the following code:
```agda
{-# NO_POSITIVITY_CHECK #-}

data μ (F : Set → Set) : Set where
  In : F (μ F) → μ F

List : Set → Set
List A = μ (λ X → ⊤ ⊎ A × X)

Tree : Set → Set
Tree A = μ (λ X → ⊤ ⊎ X × A × X)

pattern leaf       = In (inj₁ tt)
pattern node l x r = In (inj₂ (l , x , r))
```
Now let's define a map function for lists. After repeated case-splitting I end up with the following code:
```agda
map : ∀ {A B} → (A → B) → List A → List B
map f leaf = {!!}
map f (In (fsuc (proj₁ , proj₂))) = {!!}
```
Your suggested fix would not address the problem with the `leaf` synonym.

**Comment by UlfNorell** [comment]
Unless you define the `nil` pattern synonym...

There are basically two kinds of pattern synonyms:
- ones used to make heavy encoding schemes more palatable (discussed here)
- ones used to make common patterns for particular data types nicer

For the former, printing pattern synonyms causes weird results as shown here, but for the latter you absolutely want them to be printed in goals and case splits.

This suggests that the write-only pragma is the way to go.

**Comment by nad** [comment]
> ones used to make common patterns for particular data types nicer

What kind of examples do you have in mind? I can think of examples involving equality, using `refl` in the pattern synonyms.

> This suggests that the write-only pragma is the way to go.

Perhaps the write-only mode should be the default.

**Comment by gallais** [comment]
> What kind of examples do you have in mind?

We now have this example in the standard library following my refactoring of Data.AVL: https://agda.github.io/agda-stdlib/Data.AVL.Height.html#349

The changes are completely transparent from the user's point of view thanks to pattern re-folding. Edit: [what used to be](https://github.com/agda/agda-stdlib/commit/f6ae4f7ffe70e9f3f9c028fe341f7af91439d3a3#diff-8e2458aa58cbbc3500f1b6fa16db3263L92)

**Comment by nad** [comment]
If you import `Data.AVL.Height`, but also use `Fin` directly, then you may not want to use these synonyms. Thus this is, in my opinion, not an example where it is clearly better to use the synonyms.

**Comment by nad** [comment]
I suggest that, if we decide to use a pragma, then the default should be the old behaviour, to minimise "breakage" of existing code (not type errors, but weird behaviour when people build on that code).

**Comment by andreasabel** [comment]
See also #3080 where the use of pattern synonym in case splitting is actually buggy.

**Comment by UlfNorell** [comment]
I added an option to turn off printing of pattern synonyms (`--no-print-pattern-synonyms`) as an interim measure.

**Comment by gallais** [comment]
Following #3879, we do not resugar the patterns which have a qualified name.
So you can avoid / control the patterns being used by putting them in a module
and only opening it in places where you want to use them.

**Comment by jespercockx** [comment]
@nad are you happy with the current solution (`--no-print-pattern-synonyms` + no resugaring of qualified patterns)?

**Comment by nad** [comment]
I wasn't aware of `--no-print-pattern-synonyms`. I've turned it on now, but I haven't tested it thoroughly yet.

**Comment by UlfNorell** [comment]
Between the `--no-pattern-synonyms` and the change in #3879 I'm marking this as fixed.
