### ISSUE TITLE
No tab completion for GHCNoMain

### ISSUE THREAD

**Issue by nad** [agda/agda#2904]
@UlfNorell, you removed "GHCNoMain" from `agda2-backends` (3bc19b0c998bf320375c7d8b064eb34fa836870a). This means that there is no tab completion for this variant of the GHC backend, even though the backend still exists. Was this an intended change?

**Comment by UlfNorell** [comment]
Ideally, I'd like to get rid of the `GHCNoMain` backend and just have the ordinary `GHC` backend handle the no-main case as well. If the loss of tab completion pains you feel free to put it back until that happens.
