### ISSUE TITLE
Missing backends in list of installed backends

### ISSUE THREAD

**Issue by nad** [agda/agda#2905]
If a non-existing compiler backend is chosen, then the Emacs mode prints "installed backends: GHC, JS". However, there are more, at least the following ones: LaTeX, QuickLaTeX, GHCNoMain. Have I missed any? Is there a reason for not including these backends in the list of backends that is printed?

**Comment by asr** [comment]
> Have I missed any?

HTML.

**Comment by nad** [comment]
There does not seem to be a backend called `HTML`:
```
No backend called 'HTML' (installed backends: GHC, JS)
```
