### ISSUE TITLE
Confusing "cannot be translated to a Haskell type" error message

### ISSUE THREAD

**Issue by nad** [agda/agda#2906]
Consider the following code:
```agda
data D : Set where

f : D → D
f ()

{-# COMPILE GHC f as f #-}
```
If I try to compile this code, then I get the following error message:
```
The type D cannot be translated to a Haskell type.
```
This looks strange to me. If the pragma is removed, then the type is compiled to a Haskell type.

See also #2879.

**Comment by UlfNorell** [comment]
This has nothing to do with the empty type. The compiler is complaining that `D` doesn't correspond to a non-generated Haskell type. It sensibly refuses to generate Haskell exports whose types contains generated names. If you actually explain which user-friendly Haskell type you want for `D` there's no problem:

```agda
data D : Set where

{-# FOREIGN GHC data D #-}
{-# COMPILE GHC D = data D () #-}

f : D → D
f ()

{-# COMPILE GHC f as f #-}
```

**Comment by nad** [comment]
I didn't claim that this problem is restricted to the empty type. My problem is that the error message states that a type that Agda knows how to translate to Haskell cannot be translated to Haskell. The error message would be more helpful if it stated that Agda refuses to compile `f` with a user-specified name because its type contains one or more compiler-generated (and thus unstable) names (assuming that this is the restriction that is imposed).

**Comment by UlfNorell** [comment]
Can we please not tag "this error message could be more helpful" with the `bug` tag?

**Comment by UlfNorell** [comment]
> I didn't claim that this problem is restricted to the empty type.

That's what the title suggests...

You get the same error for foreign imports:

```agda
data D : Set where

postulate
  f : D → D

{-# COMPILE GHC f = \ x -> x #-} -- The type D cannot be translated to a Haskell type.
```

**Comment by nad** [comment]
> Can we please not tag "this error message could be more helpful" with the `bug` tag?

I see this as a bug related to error-reporting, but I don't really care. I don't use the bug tag when searching for issues, I guess it is mainly used for statistics.

Anyway, I'd prefer a less confusing error message, and I don't know what the rules are, so it's not so easy for me to fix this myself.

**Comment by UlfNorell** [comment]
The rules are very simple: the type must translate to a Haskell type containing no generated types. In other words all data/record types must have explicit `{-# COMPILE GHC ... #-}` data or type pragmas.

**Comment by nad** [comment]
OK, then we could perhaps use error messages of the following form (where appropriate): "The type *A* will not be translated to Haskell, because it mentions the type *B*, and there is no pragma {-# COMPILE GHC *B* = ... #-}". In cases where the problem is, say, that the type contains a lambda, then this could be stated in the error message.

**Comment by UlfNorell** [comment]
Fixed. The code
```agda
data D : Set where
  zero : D
  suc  : D → D

postulate
  f : D → D

{-# COMPILE GHC f = \ x -> x #-}
```
now results in the much more helpful error message
```
The type D → D cannot be translated to a corresponding Haskell
type, because it contains D which does not have a COMPILE pragma.
Possible fix: add a pragma
  {-# COMPILE GHC D = data HsD (C1 | C2) #-}
for a suitable Haskell data type HsD.
```
Depending on `D` it suggests a suitable pragma (`data` for data and record types, and `type` for others). The name `HsD` is not derived from `D`.

**Comment by xekoukou** [comment]
Even though the new error message proposes the solution to the problem, it does not explain the reason. You can of course deduce that it needs a manually specified haskell type but it keeps you wondering.

**Comment by asr** [comment]
>> Can we please not tag "this error message could be more helpful" with the `bug` tag?

> I see this as a bug related to error-reporting, but I don't really care.

Before releasing we list in the CHANGELOG the issues tagged `bug` or `enhancement`  (except those tagged `abandoned`, `duplicated`, `wontfix`,  or `working-as-intended`).
