### ISSUE TITLE
primForce is compiled away

### ISSUE THREAD

**Issue by nad** [agda/agda#2908]
The reference manual [states](http://agda.readthedocs.io/en/v2.5.3/language/built-ins.html#strictness) that "`primForce e f` is compiled (by the GHC backend) to `let x = e in seq x (f x)`". However, that is not the case for the following code:
```agda
open import Agda.Builtin.IO
open import Agda.Builtin.Nat
open import Agda.Builtin.Strict
open import Agda.Builtin.Unit

{-# TERMINATING #-}

f : Nat → Nat
f zero    = f zero
f (suc n) = f n

postulate
  returnIO : ∀ {a} {A : Set a} → A → IO A

{-# COMPILE GHC returnIO = \_ _ -> return #-}

main : IO ⊤
main = primForce (f 0) (λ _ → returnIO tt)
```
This code is compiled into a `seq`-free program that terminates quickly.

**Comment by UlfNorell** [comment]
It *is* compiled to `let x = e in seq x (f x)`, but in your case the `seq` is then optimised away since it's pointless. Do you have an example where the compiler is actually doing something bad?

**Comment by nad** [comment]
> It *is* compiled to `let x = e in seq x (f x)`, but in your case the `seq` is then optimised away since it's pointless.

In what sense is it pointless? Please include this information in the documentation. Note that if you only care about the denotational semantics of the generated code, then `seq` can *always* be removed (ignoring `--no-termination-check`, bugs, the FFI, etc.).

> Do you have an example where the compiler is actually doing something bad?

Note that `f zero = f zero`: the code above should not terminate (successfully).

**Comment by UlfNorell** [comment]
> In what sense is it pointless?

The use case for `primSeq` is to control evaluation order, improving the memory profile of a program. In your case the term you `seq` on isn't used so forcing its evaluation will not improve anything.

> Please include this information in the documentation.

Do you have an example where this information would actually help a user? I'm reluctant to maintain documentation for all the optimisation passes in the compiler.

> Note that f zero = f zero: the code above should not terminate (successfully).

The compiler gives no promises about preserving non-termination. On the contrary it assumes your program is terminating (or productive), and thus makes no promises what-so-ever about this program.

**Comment by nad** [comment]
> Do you have an example where this information would actually help a user?

I had expected the program above to fail to terminate, so clearly the current documentation is not sufficient for me. The current explanation suggests to me that Agda preserves the denotational semantics of a Haskell expression involving `seq`, but that is not the case.

> In your case the term you `seq` on isn't used so forcing its evaluation will not improve anything.

Does Agda verify that thunks that are thrown away are not aliased? Forcing of aliased thunks is used in some of Chris Okasaki's data structures.

> I'm reluctant to maintain documentation for all the optimisation passes in the compiler.

I agree. Ideally I would like to have some kind of cost semantics for the language. At the moment it seems as we have basically zero guarantees related to performance.

**Comment by UlfNorell** [comment]
> Does Agda verify that thunks that are thrown away are not aliased?

No, you are right that the compiler would do the wrong thing in this case. I'll get rid of this particular transformation.
