### ISSUE TITLE
Agda uses newtypes incorrectly, causing wellformed programs to loop

### ISSUE THREAD

**Issue by nad** [agda/agda#2909]
Consider the following code:
```agda
open import Agda.Builtin.IO
open import Agda.Builtin.Unit
open import Agda.Builtin.Strict

record Box (A : Set) : Set where
  field
    unbox : A

open Box public

record R : Set where
  coinductive
  field
    force : Box R

open R public

r : R
unbox (force r) = r

postulate
  returnIO : ∀ {a} {A : Set a} → A → IO A

{-# COMPILE GHC returnIO = \_ _ -> return #-}

main : IO ⊤
main = primForce r (λ _ → returnIO tt)
```
The resulting program should terminate quickly. However, the GHC backend uses newtypes to compile the two record types, and the resulting program prints `<<loop>>`.

It seems as if the problem is that the compiler treats record types as being inductive. Note the two occurrences of `Inductive` below:
https://github.com/agda/agda/blob/a3c5c4340a2683c7ed5d445bacf3d3bf4aad0ca5/src/full/Agda/Compiler/MAlonzo/Compiler.hs#L358-L371
It seems as if I added the first such occurrence back in 2009 (37a08303b237e029abaf1e5959b85db264274df5), when (as far as I recall) record types could not be coinductive.

**Comment by nad** [comment]
For some reason the `R` type is compiled using `data` if `Box` is removed:
```agda
record R : Set where
  coinductive
  field
    force : R

open R public

r : R
force r = r
```
Compiled type:
```haskell
data T12 = C19
```
Does Agda somehow detect that this type is isomorphic to the unit type?

**Comment by nad** [comment]
Here is a related problem. The following program also prints `<<loop>>` when compiled using the GHC backend:
```agda
open import Agda.Builtin.Coinduction
open import Agda.Builtin.IO
open import Agda.Builtin.Unit
open import Agda.Builtin.Strict

data D : Set where
  c : ∞ D → D

d : D
d = c (♯ d)

postulate
  returnIO : ∀ {a} {A : Set a} → A → IO A

{-# COMPILE GHC returnIO = \_ _ -> return #-}

main : IO ⊤
main = primForce d (λ _ → returnIO tt)
```
The problem here is that both `D` and `∞` are compiled to newtypes.

**Comment by nad** [comment]
Currently there is a special case for `∞` in the compiler:
https://github.com/agda/agda/blob/a3c5c4340a2683c7ed5d445bacf3d3bf4aad0ca5/src/full/Agda/Compiler/MAlonzo/Compiler.hs#L273-L287
This code suggests that `∞` is compiled to (roughly) `type Tn a0 a1 = a1`. However, the actual output is (roughly) `newtype Tm = Cn AgdaAny`. This suggests to me that the special case is never triggered, and testing seems to corroborate this suspicion.

**Comment by nad** [comment]
The changelog contains the following text:
> The compiler compiles the `INFINITY` builtin to nothing (more or less), so that the use of coinduction does not get in the way of FFI declarations:
>
> ```agda
> data Colist (A : Set) : Set where
>   []  : Colist A
>   _∷_ : (x : A) (xs : ∞ (Colist A)) → Colist A
>
> {-# COMPILED_DATA Colist [] [] (:) #-}
> ```
As far as I can tell the standard library [still relies](https://github.com/agda/agda-stdlib/blob/bb0d16eee8caa9fad1c6b60a1d27a2cabfd24dda/src/Data/Colist.agda#L42-L47) on this property of `∞`.

**Comment by nad** [comment]
Here is another example that leads to `<<loop>>`:
```agda
{-# OPTIONS --guardedness-preserving-type-constructors #-}

open import Agda.Builtin.Coinduction
open import Agda.Builtin.IO
open import Agda.Builtin.Unit
open import Agda.Builtin.Strict

data Rec (A : ∞ Set) : Set where
  fold : ♭ A → Rec A

D : Set
D = Rec (♯ (∞ D))

d : D
d = fold (♯ d)

postulate
  returnIO : ∀ {a} {A : Set a} → A → IO A

{-# COMPILE GHC returnIO = \_ _ -> return #-}

main : IO ⊤
main = primForce d (λ _ → returnIO tt)
```

**Comment by nad** [comment]
I'm not quite sure how to handle the `INFINITY` builtin, because if this builtin is no longer compiled to "nothing", then we get the following problems:

* The `Colist` type in the standard library is no longer compiled to Haskell lists, and some of the IO bindings in the standard library use colists. This can be fixed by including functions that translate between the different representations, but this adds run-time overhead.
* Other developments may also be affected.

One solution might be to only use newtypes for the `INFINITY` builtin, and nothing else. However, I don't think we should optimise for this kind of coinduction. Any opinions?

Can someone answer the following questions?
* [Does Agda somehow detect that this type is isomorphic to the unit type?](https://github.com/agda/agda/issues/2909#issuecomment-358046769)
* What part of Agda turns `∞` into a record type?

**Comment by nad** [comment]
Given that `primForce` does not have the semantics I thought it had (#2908), the test cases that I have provided should perhaps be modified in some way, to make them stable under compiler optimisations. One option might be to use the FFI and `seq`.

**Comment by UlfNorell** [comment]
Answering the first question: the compiler detects that
```agda
record R : Set where
  coinductive
  field
    force : R
```
is *erasable*, and thus erases the argument to the constructor. Erasable types have at most one inhabitant. The coinduction is not important for this, the type
```agda
data Empty : Set where
  mkEmpty : Empty → Empty
```
is also compiled to a Haskell unit type.

**Comment by UlfNorell** [comment]
Second question:

https://github.com/agda/agda/blob/b8953e74d5ab7c296215aa1c025bcce43de2c493/src/full/Agda/TypeChecking/Rules/Builtin/Coinduction.hs#L70-L92

**Comment by nad** [comment]
Any opinions about what to do about the `INFINITY` builtin?

**Comment by nad** [comment]
I'm leaning towards using newtypes only for inductive/non-recursive types with a single constructor with a single argument for the time being, thus making developments using `INFINITY` potentially less efficient. However, in the future we could consider using newtypes also for coinductive types with a single constructor with a single argument (after erasure) when it is safe to do so. Here is one example:
```agda
mutual

  data Delay (A : Set) (i : Size) : Set where
    now   : A → Delay A i
    later : Delay′ A i → Delay A i

  record Delay′ (A : Set) (i : Size) : Set where
    coinductive
    field
      force : {j : Size< i} → Delay A j
```
I think it is safe to generate a newtype for `Delay′`, because `Delay` contains two constructors (and is thus not compiled to a newtype).

**Comment by nad** [comment]
I'm in the process of implementing what I suggested above (not the "in the future" part). Now I want to write a Haskell function that converts the Haskell representation of colists into Haskell lists, with colists defined in the following way:
```agda
data Colist {a} (A : Set a) : Set a where
  []  : Colist A
  _∷_ : A → ∞ (Colist A) → Colist A
```
Now, in order to give Haskell names to the colist constructors I seem to need access to the Haskell name for `INFINITY`, but the `COMPILE GHC f as g` pragma does not work for `INFINITY` (nor for `SHARP`). Would it make sense to add a `COMPILE GHC A as type B` pragma? (I don't think we should do this unless it is useful for some other purpose.)

**Comment by UlfNorell** [comment]
I think it would make more sense to special case `INFINITY` and friends. The Haskell definitions could go in `MAlonzo.RTE`.

**Comment by andreasabel** [comment]
@nad : Still using `--guardedness-preserving-type-constructors`?!  I am removing this feature in connection to #1556 which I fix by a change to the termination checker.  If there is actually still interest in this feature, I could retain it, however the prime examples are now rejected by the termination checker.

**Comment by nad** [comment]
I don't think I have any maintained code that uses this feature. The standard library mentions this option in a comment in the module `Coinduction`.
