### ISSUE TITLE
Slicing ignores as pragma?

### ISSUE THREAD

**Issue by nad** [agda/agda#2914]
The GHC backend fails to compile the following code:
```agda
open import Agda.Builtin.IO
open import Agda.Builtin.Nat
open import Agda.Builtin.Unit

private
  n : Nat
  n = 7

{-# COMPILE GHC n as n #-}

postulate
  main : IO ⊤

{-# COMPILE GHC main = print n #-}
```
Error message from GHC:
```
Variable not in scope: n
```
It seems to me as if the private variable `n` is not compiled at all. I guess that some kind of slicing is involved, and that the slicing ignores the `COMPILE GHC n as n` pragma.

**Comment by UlfNorell** [comment]
Slicing is here:

https://github.com/agda/agda/blob/ac46e756fe9a6c4d25c750d31fbd38033c1e7c1f/src/full/Agda/TypeChecking/DeadCode.hs#L2

I'm pretty sure you are right that it doesn't consider `COMPILE`-`as` pragmas.

**Comment by nad** [comment]
How should this be handled? The compiler backends are supposed to be independent of the frontend.

**Comment by UlfNorell** [comment]
The simplest solution would be to forbid compile-as for private definitions. This makes a lot of sense too, since if you're exporting the function from the compiled code, it really isn't private.

**Comment by nad** [comment]
One might think that another option is to have export lists in the generated Haskell modules, and not include private definitions in those lists. However, due to reduction and unification private definitions can be referenced from other modules. I guess that currently I would recommend people writing Haskell libraries in Agda to manually write wrapper modules that reexport exactly the names that should be available to users.

**Comment by UlfNorell** [comment]
Also it wouldn't address the current issue in any way.

**Comment by nad** [comment]
I was referring to your comment that "if you're exporting the function from the compiled code, it really isn't private".

**Comment by UlfNorell** [comment]
Dead-code elimination happens before compilation, and hence also the checking of `COMPILE` pragmas. It seems like a terrible idea to forbid *all* `COMPILE` pragmas on private definitions, so the simplest solution was to not eliminate anything with an attached `COMPILE` pragma.
