### ISSUE TITLE
The GHC backend generates code with an incorrect number of constructor arguments

### ISSUE THREAD

**Issue by nad** [agda/agda#2916]
The GHC backend fails to compile the following code:
```agda
open import Agda.Builtin.IO
open import Agda.Builtin.Unit

mutual

  record R (A : Set) : Set where
    inductive
    field
      f₁ : A
      f₂ : R′ A

  record R′ (A : Set) : Set where
    inductive
    field
      f : R A

postulate
  return : {A : Set} → A → IO A

{-# COMPILED return (\_ -> return) #-}

main : IO ⊤
main = return tt
```
The key part of the error message (from GHC):
```
    • The constructor ‘C1’ should have 2 arguments, but has been given 1
```

This is a regression, Agda 2.5.1.1 manages to compile this code.

**Comment by UlfNorell** [comment]
Can you include the relevant part of the generated code?

**Comment by nad** [comment]
Sure:
```haskell
name4 = "Bug.R"
d4 a0 = ()
data T4 = C1 AgdaAny T8
name8 = "Bug.R\8242"
d8 a0 = ()
newtype T8 = C23 T4
name16 = "Bug.R.f\8321"
d16 :: T4 -> AgdaAny
d16 v0
  = case coe v0 of
      C1 v1 -> coe v1
      _ -> MAlonzo.RTE.mazUnreachableError
name18 = "Bug.R.f\8322"
d18 :: T4 -> T8
d18 = erased
name24 = "Bug.R\8242.f"
d24 :: T8 -> T4
d24 v0
  = case coe v0 of
      C23 v1 -> coe v1
      _ -> MAlonzo.RTE.mazUnreachableError
```

Bisection points to af3ca2c3b8a9f11ab2951c1c37bc8fb73e096720 ("[ ghc-backend ] completely erase erasable constructor arguments").

**Comment by nad** [comment]
Here is a possibly related example:
```agda
open import Agda.Builtin.IO
open import Agda.Builtin.Unit

data Unit : Set where
  c : ⊤ → Unit

{-# FOREIGN GHC
  data Unit = Unit ()
  #-}

{-# COMPILE GHC Unit = data Unit (Unit) #-}

postulate
  foo : Unit → IO ⊤

{-# COMPILE GHC foo = \_ -> return () #-}

main : IO ⊤
main = foo (c _)
```
Error message:
```
The constructor ‘Unit’ should have 1 argument, but has been given none
```
Generated code:
```haskell
data Unit = Unit ()
name2 = "Test.Unit"
d2 = ()
type T2 = Unit
pattern C4 a0 = Unit a0
check4 :: (MAlonzo.Code.Agda.Builtin.Unit.T6 -> T2)
check4 = Unit
cover2 :: Unit -> ()
cover2 x
  = case x of
      Unit -> ()
```
My guess is that Agda erases the argument to `c` without taking the `data` pragma into account.

**Comment by UlfNorell** [comment]
This looks like a different issue. I think a case can be made that you want to drop erased arguments also in `COMPILE`d data. The argument against is of course that it's not obvious which arguments will get erased.

**Comment by UlfNorell** [comment]
The problem is that the erasability analysis gets confused over mutually recursive types. When analysing a recursive type we assume recursive occurrences to be erasable. In this case, when checking if `R` is erasable we assume it is and proceed to check if `R′` is erasable, which it is under the assumption that `R` is. Here is the mistake: we then mark `R′` as erasable, forgetting that this is only true under the (false) assumptions.

It's easy to fix this naively, but doing so leads to bad performance regressions (x2.5 compiling std-lib). I'll try to make a more thorough refactoring of the erasability analysis.

**Comment by UlfNorell** [comment]
Nevermind.. the performance regression seems to have been a temporary hiccup on my machine. I can't reproduce it.

**Comment by UlfNorell** [comment]
Filed the issue above for the compiled `Unit` issue.
