### ISSUE TITLE
Very slow due to unsolved size?

### ISSUE THREAD

**Issue by nad** [agda/agda#2917]
The time required to check the following code seems to be superpolynomial in the number of underscores in the last line:
```agda
open import Agda.Builtin.Size

mutual

  data Nat (i : Size) : Set where
    zero : Nat i
    suc  : Nat′ i → Nat i

  data Nat′ (i : Size) : Set where
    [_] : {j : Size< i} → Nat j → Nat′ i

size : ∀ {i} → Nat′ i → Size
size ([_] {j} _) = {!j!}

unbox : ∀ {i} (n : Nat′ i) → Nat (size n)
unbox [ n ] = n

postulate
  _ _ _ _ : Set
```

**Comment by UlfNorell** [comment]
It looks like the size constraint is being duplicated every time we attempt to solve it, causing an (doubly?) exponential number of identical constraints.
