### ISSUE TITLE
Memoisation

### ISSUE THREAD

**Issue by nad** [agda/agda#2918]
The following program is an attempt to implement memoisation, following Hinze's [Memo functions, polytypically!](http://www.cs.ox.ac.uk/ralf.hinze/publications/index.html#P11):
```agda
open import Agda.Builtin.IO
open import Agda.Builtin.Nat renaming (Nat to ℕ)
open import Agda.Builtin.Size
open import Agda.Builtin.Unit

record _×_ (A B : Set) : Set where
  constructor _,_
  field
    proj₁ : A
    proj₂ : B

open _×_ public

mutual

  data Nat (i : Size) : Set where
    zero : Nat i
    suc  : Nat′ i → Nat i

  data Nat′ (i : Size) : Set where
    [_] : {j : Size< i} → Nat j → Nat′ i

mutual

  ℕ→Nat : ℕ → Nat ω
  ℕ→Nat zero    = zero
  ℕ→Nat (suc n) = suc (ℕ→Nat′ n)

  ℕ→Nat′ : ℕ → Nat′ ω
  ℕ→Nat′ n = [ ℕ→Nat n ]

mutual

  Nat′[_]→ : Size → Set → Set
  Nat′[ i ]→ A = A × Nat′[ i ]→′ A

  record Nat′[_]→′ (i : Size) (A : Set) : Set where
    coinductive
    field
      force : {j : Size< i} → Nat′[ j ]→ A

open Nat′[_]→′ public

tabulate : ∀ {i} {A : Set} → (Nat′ i → A) → Nat′[ i ]→′ A
force (tabulate f) = f [ zero ] , tabulate (λ n → f [ suc n ])

lookup : ∀ {i} {A : Set} → Nat′[ i ]→′ A → Nat′ i → A
lookup t [ zero  ] = proj₁ (force t)
lookup t [ suc n ] = lookup (proj₂ (force t)) n

memo-fix :
  {A : Set} →
  (∀ {i} → (Nat′ i → A) → (Nat i → A)) →
  ∀ {i} → Nat′ i → A
memo-fix f [ n ] = f (lookup (tabulate (memo-fix f))) n

fib-step : ∀ {i} → (Nat′ i → ℕ) → (Nat i → ℕ)
fib-step fib zero            = 0
fib-step fib (suc [ zero ])  = 1
fib-step fib (suc [ suc n ]) = fib n + fib [ suc n ]

fib : ℕ → ℕ
fib n = memo-fix fib-step [ ℕ→Nat n ]

postulate
  return : {A : Set} → A → IO A

{-# COMPILE GHC return = \_ -> return #-}

postulate
  seq : {A B : Set} → A → B → B

{-# COMPILE GHC seq = \_ _ -> seq #-}

main : IO ⊤
main = seq (fib 33) (return tt)
```
However, the resulting program is not efficient (when compiled using the GHC backend). I can fix this by performing two changes:

1. Replace the body of `memo-fix` with the following code (to avoid allocating new memo tables all the time):
   ```agda
   memo-fix f = f (lookup (tabulate (memo-fix f))) ∘ unbox
   ```
   This change also involves marking `memo-fix` as `NON_TERMINATING` and adding the following code:
   ```agda
   size : ∀ {i} → Nat′ i → Size
   size ([_] {j} _) = j

   unbox : ∀ {i} (n : Nat′ i) → Nat (size n)
   unbox [ n ] = n

   _∘_ : {A B : Set} {C : B → Set} →
         ((y : B) → C y) → (g : A → B) →
         ((x : A) → C (g x))
   f ∘ g = λ x → f (g x)
   ```

2. Manually edit the generated Haskell code and erase the first argument of `[_]`. I don't know why this has an effect, perhaps the extra argument prevents GHC's full laziness optimisation.

I suggest that we should change Agda so that one can get good performance without these hacks. Let us start with the second point above. I guess one option is to erase all sizes entirely, but before we go down that path I wonder if there already is a way to ensure that the argument is erased completely. I tried to use irrelevance, but failed.

Here is a self-contained copy of the code with the hacked `memo-fix`:
```agda
open import Agda.Builtin.IO
open import Agda.Builtin.Nat renaming (Nat to ℕ)
open import Agda.Builtin.Size
open import Agda.Builtin.Unit

record _×_ (A B : Set) : Set where
  constructor _,_
  field
    proj₁ : A
    proj₂ : B

open _×_ public

mutual

  data Nat (i : Size) : Set where
    zero : Nat i
    suc  : Nat′ i → Nat i

  data Nat′ (i : Size) : Set where
    [_] : {j : Size< i} → Nat j → Nat′ i

size : ∀ {i} → Nat′ i → Size
size ([_] {j} _) = j

unbox : ∀ {i} (n : Nat′ i) → Nat (size n)
unbox [ n ] = n

_∘_ : {A B : Set} {C : B → Set} →
      ((y : B) → C y) → (g : A → B) →
      ((x : A) → C (g x))
f ∘ g = λ x → f (g x)

mutual

  ℕ→Nat : ℕ → Nat ω
  ℕ→Nat zero    = zero
  ℕ→Nat (suc n) = suc (ℕ→Nat′ n)

  ℕ→Nat′ : ℕ → Nat′ ω
  ℕ→Nat′ n = [ ℕ→Nat n ]

mutual

  Nat′[_]→ : Size → Set → Set
  Nat′[ i ]→ A = A × Nat′[ i ]→′ A

  record Nat′[_]→′ (i : Size) (A : Set) : Set where
    coinductive
    field
      force : {j : Size< i} → Nat′[ j ]→ A

open Nat′[_]→′ public

tabulate : ∀ {i} {A : Set} → (Nat′ i → A) → Nat′[ i ]→′ A
force (tabulate f) = f [ zero ] , tabulate (λ n → f [ suc n ])

lookup : ∀ {i} {A : Set} → Nat′[ i ]→′ A → Nat′ i → A
lookup t [ zero  ] = proj₁ (force t)
lookup t [ suc n ] = lookup (proj₂ (force t)) n

{-# NON_TERMINATING #-}

memo-fix :
  {A : Set} →
  (∀ {i} → (Nat′ i → A) → (Nat i → A)) →
  ∀ {i} → Nat′ i → A
memo-fix f = f (lookup (tabulate (memo-fix f))) ∘ unbox

fib-step : ∀ {i} → (Nat′ i → ℕ) → (Nat i → ℕ)
fib-step fib zero            = 0
fib-step fib (suc [ zero ])  = 1
fib-step fib (suc [ suc n ]) = fib n + fib [ suc n ]

fib : ℕ → ℕ
fib n = memo-fix fib-step [ ℕ→Nat n ]

postulate
  return : {A : Set} → A → IO A

{-# COMPILE GHC return = \_ -> return #-}

postulate
  seq : {A B : Set} → A → B → B

{-# COMPILE GHC seq = \_ _ -> seq #-}

main : IO ⊤
main = seq (fib 33) (return tt)
```

**Comment by nad** [comment]
I think I managed to erase the size argument. With this change in place the code now works with the usual dependently typed composition operator:
```agda
_∘_ : ∀ {a b c}
        {A : Set a} {B : A → Set b} {C : {x : A} → B x → Set c} →
      (∀ {x} (y : B x) → C y) → (g : (x : A) → B x) →
      ((x : A) → C (g x))
f ∘ g = λ x → f (g x)
```

On to the other point: How can the hack with `NON_TERMINATING` be avoided? (I also seem to recall  @andreasabel or @Saizan mentioning that functions like `size` should perhaps not be allowed.) @andreasabel suggested that we could "optimize code using single-constructor data types when compiling from Agda to Haskell". It would presumably be possible to do the transformation I did above automatically in certain cases (for instance when newtypes are involved, as in this case). However, I can imagine that this could lead to unintended space leaks in other cases. One option might be to use a pragma of some kind to direct the translation. The pragma could perhaps attach to a type, or to a definition (or even to a pattern). Any opinions?

**Comment by UlfNorell** [comment]
> Manually edit the generated Haskell code and erase the first argument of [_]. I don't know why this has an effect, perhaps the extra argument prevents GHC's full laziness optimisation.

I still get poor performance with the size argument erased (`ghc-8.2.2`). Looking at the generated Haskell code, this is not surprising:

```haskell
du102 ::
  (MAlonzo.Code.Agda.Builtin.Size.T8 ->
   (T28 -> AgdaAny) -> T24 -> AgdaAny) ->
  T28 -> AgdaAny
du102 v0 v1
  = case coe v1 of
      C40 v3
        -> coe v0 erased (du88 (coe (du78 (coe (du102 (coe v0)))))) v3
      _ -> MAlonzo.RTE.mazUnreachableError
```

GHC core:
```haskell
du102
  :: (T8 -> (T28 -> AgdaAny) -> T24 -> AgdaAny) -> T28 -> AgdaAny
du102
  = \ (v0 :: T8 -> (T28 -> AgdaAny) -> T24 -> AgdaAny) (v1 :: T28) ->
      coe
        v0
        erased
        (du88 (coe (du78 (coe (du102 (coe v0))))))
        ((coe v1) `cast` <Co:1>)
```
The memo table is constructed under the `v1` lambda in both cases.

**Comment by nad** [comment]
That's with the original code, right? As I wrote above I get good performance with the following implementation of `memo-fix`:
```agda
{-# NON_TERMINATING #-}

memo-fix :
  {A : Set} →
  (∀ {i} → (Nat′ i → A) → (Nat i → A)) →
  ∀ {i} → Nat′ i → A
memo-fix f = f (lookup (tabulate (memo-fix f))) ∘ unbox
```
Generated code:
```haskell
du150 ::
  (MAlonzo.Code.Agda.Builtin.Size.T8 ->
   (T30 -> AgdaAny) -> T26 -> AgdaAny) ->
  T30 -> AgdaAny
du150 v0
  = coe
      (du82
         (coe
            (\ v1 ->
               coe v0 erased (du136 (coe (du126 (coe (du150 (coe v0))))))))
         (coe d54))
```
Core:
```haskell
du150 [Occ=LoopBreaker]
  :: (MAlonzo.Code.Agda.Builtin.Size.T8
      -> (T30 -> AgdaAny) -> T26 -> AgdaAny)
     -> T30 -> AgdaAny

du150
  = \ (v0_a5Hl
         :: MAlonzo.Code.Agda.Builtin.Size.T8
            -> (T30 -> AgdaAny) -> T26 -> AgdaAny) ->
      let {
        lvl_s7gs [Dmd=<L,C(U)>] :: T26 -> AgdaAny
        [LclId]
        lvl_s7gs
          = v0_a5Hl
              (MAlonzo.RTE.erased1 `cast` <Co:349>)
              (let {
                 w_s7hX [Dmd=<L,U(C(U(1*U,1*U)))>] :: T104
                 [LclId]
                 w_s7hX
                   = case MAlonzo.Code.README.Short.$wdu126 (du150 v0_a5Hl) of
                     { (# ww1_s7ie #) ->
                     MAlonzo.Code.README.Short.C317 ww1_s7ie
                     } } in
               \ (w1_s7hY :: T30) ->
                 case w_s7hX of { C317 ww1_s7i1 ->
                 MAlonzo.Code.README.Short.$wdu136 ww1_s7i1 w1_s7hY
                 }) } in
      (\ (v2_a5GQ :: AgdaAny) -> lvl_s7gs (v2_a5GQ `cast` <Co:31>))
      `cast` <Co:10>
```
How do you generate the core? I used [ghc-core](https://hackage.haskell.org/package/ghc-core) along with `-dsuppress-coercions`, and I also tried [dump-core](https://hackage.haskell.org/package/dump-core), but I think you are using something else.

Anyway, my goal now is to make it possible to get good performance with the termination checker still turned on.

**Comment by nad** [comment]
By the way, one can note above that the "rank-2" size argument is still present in the core. There is room for improvement of Agda's erasure transformation.

**Comment by nad** [comment]
With `-dsuppress-coercions -dsuppress-uniques -dsuppress-idinfo -dsuppress-module-prefixes` I get the following output:
```haskell
du150
  :: (T8 -> (T30 -> AgdaAny) -> T26 -> AgdaAny) -> T30 -> AgdaAny
du150
  = \ (v0 :: T8 -> (T30 -> AgdaAny) -> T26 -> AgdaAny) ->
      let {
        lvl :: T26 -> AgdaAny
        lvl
          = v0
              (erased1 `cast` <Co:349>)
              (let {
                 w :: T104
                 w = case $wdu126 (du150 v0) of { (# ww1 #) -> C317 ww1 } } in
               \ (w1 :: T30) -> case w of { C317 ww1 -> $wdu136 ww1 w1 }) } in
      (\ (v2 :: AgdaAny) -> lvl (v2 `cast` <Co:31>)) `cast` <Co:10>
```

**Comment by nad** [comment]
> (I also seem to recall  @andreasabel or @Saizan mentioning that functions like `size` should perhaps not be allowed.)

One can avoid using `size` and `unbox`. The following code runs quickly:
```agda
wrapper : ∀ {i} {A : Set} → (Nat i → A) → (Nat′ i → A)
wrapper f [ n ] = f n

{-# NON_TERMINATING #-}

memo-fix :
  {A : Set} →
  (∀ {i} → (Nat′ i → A) → (Nat i → A)) →
  ∀ {i} → Nat′ i → A
memo-fix f = wrapper (f (lookup (tabulate (memo-fix f))))
```

**Comment by nad** [comment]
I tried to use a `COMPILE GHC` pragma to control the compilation of `memo-fix`, but this led to [a problem](https://github.com/agda/agda/issues/2916#issuecomment-359743928) involving the combination of `data` pragmas and erasure of constructor arguments.

**Comment by nad** [comment]
I managed to write Agda code that is accepted by the termination checker and compiles to fast Haskell:
```agda
memo-fix :
  {A : Set} →
  (∀ {i} → (Nat′ i → A) → (Nat i → A)) →
  ∀ {i} → Nat′ i → A
memo-fix f =
  wrapper (λ { [ n ] → f (lookup (tabulate (memo-fix f))) n })
  where
  wrapper : ∀ {i} {A : Set} → (Nat′ i → A) → (Nat′ i → A)
  wrapper f [ n ] = f [ n ]
```
Generated Haskell code for `wrapper`:
```haskell
du116 :: (T30 -> AgdaAny) -> T30 -> AgdaAny
du116 v0 v1
  = case coe v1 of
      C42 v3 -> coe v0 (coe (\ v4 v5 -> C42 v5) erased v3)
      _ -> MAlonzo.RTE.mazUnreachableError
```
And for `memo-fix`:
```haskell
du104 ::
  (MAlonzo.Code.Agda.Builtin.Size.T8 ->
   (T30 -> AgdaAny) -> T26 -> AgdaAny) ->
  T30 -> AgdaAny
du104 v0
  = coe
      (du116
         (coe
            (\ v1 ->
               case coe v1 of
                 C42 v3
                   -> coe v0 erased (du90 (coe (du80 (coe (du104 (coe v0)))))) v3
                 _ -> MAlonzo.RTE.mazUnreachableError)))
```
Generated core:
```haskell
du116 :: (T30 -> AgdaAny) -> T30 -> AgdaAny
du116 = \ (v0 :: T30 -> AgdaAny) (v1 :: T30) -> v0 v1

du104
  :: (T8 -> (T30 -> AgdaAny) -> T26 -> AgdaAny) -> T30 -> AgdaAny
du104
  = \ (v0 :: T8 -> (T30 -> AgdaAny) -> T26 -> AgdaAny) ->
      let {
        lvl :: T58
        lvl = case $wdu80 (du104 v0) of { (# ww1 #) -> C127 ww1 } } in
      let {
        lvl1 :: T30 -> AgdaAny
        lvl1 = du90 lvl } in
      \ (v1 :: T30) ->
        v0 (erased1 `cast` <Co:349>) lvl1 (v1 `cast` <Co:1>)
```
Note that one call to `f` (`v0`) is under the final lambda.

I wonder how certain one can be that GHC will perform these transformations.

**Comment by UlfNorell** [comment]
I used
```
-ddump-simpl
-dsuppress-idinfo
-dsuppress-coercions
-dsuppress-type-applications
-dsuppress-uniques
-dsuppress-module-prefixes
```

**Comment by nad** [comment]
Given that my code works with just a small wrapper I'm closing this issue now, but it can be reopened if an example for which the wrapper does not work is encountered, or if someone comes up with a design for a more principled solution.

**Comment by nad** [comment]
@Saizan, your commit 7cbb67e97067b2420a63c2a22d8029add0e57813 broke the test case for this issue. You wrote that inlining of recursive pattern-matching lambdas "caused the compiler to loop". Do you recall under what circumstances this happened? Could we allow inlining in more cases?

**Comment by Saizan** [comment]
It must have been something in the testsuite or one of the test cases we had for erased constructors.

**Comment by nad** [comment]
I tried to enable inlining again, and `make compiler-test` did not expose any problem. If we rediscover the problem, then I think we should add a small test case for it (if possible).

**Comment by Saizan** [comment]
I believe this might have been the testcase, can you try and reproduce with inlining turned on?

```agda
{-# OPTIONS --cubical #-}

module Erased-constructor-test where

open import Agda.Builtin.Char
open import Agda.Builtin.String
open import Equality.Path
import Equality.Propositional as EP
open import IO-monad
open import Prelude
open import String

open import Bag-equivalence equality-with-J as BE using (_∼[_]_; bag)
open import List equality-with-J as L
open import Monad EP.equality-with-J
open import H-level.Closure equality-with-J
open import Quotient.Erased equality-with-paths as Q

len : List Char /ᴱ _∼[ bag ]_ → ℕ
len = Q.rec λ where
  .[]ʳ                   → length
  .[]-respects-relationʳ → BE.length-cong
  .is-setʳ               → ℕ-set

total-len : List String → ℕ
total-len = sum ∘ L.map (len ∘ [_] ∘ primStringToList)

main = do
  args ← getArgs
  putStrLn (prettyℕ (total-len args))
```

**Comment by nad** [comment]
I managed to construct a small test case:
```agda
postulate
  easy : (A : Set₁) → A

record R₁ : Set₂ where
  field
    A : Set₁

record R₂ : Set₂ where
  field
    r₁ : R₁
    a  : R₁.A r₁

r₁ : R₁
r₁ .R₁.A = Set

r₂ : R₂
r₂ = λ where
  .R₂.r₁ → r₁
  .R₂.a  → easy _
```
The metavariable corresponding to the underscore is solved in the following way:
```agda
R₁.A (R₂.r₁ (λ { .R₂.r₁ → r₁; .R₂.a → easy (R₁.A (R₂.r₁ .extendedlambda0)) }))
```
If the underscore is replaced by `R₁.A r₁`, then the compiler terminates.

**Comment by nad** [comment]
I wondered why the termination checker does not reject the code above. The following code is also accepted:
```agda
r₂ : R₂
r₂ .R₂.r₁ = r₁
r₂ .R₂.a  = easy (r₂ .R₂.r₁ .R₁.A)
```
Why doesn't the termination checker reject this code? It is accepted even if `tryReduceNonRecursiveClause` is disabled. The termination checker claims that there is some measure that is decreasing strictly in several calls:
```
kept call from Bug.r₂ .Bug.R₂.a
  to Bug.r₂
  call matrix (with guardedness): 
     ?    ?
     ?   -1
     ?    ?
found call from r₂ to easy
Calls (no dot patterns): Source: 0
Target: 0
Matrix:    ?    ?
           ?   -1
           ?    ?
```

**Comment by nad** [comment]
> Could we allow inlining in more cases?

I'm guessing that we could allow inlining of recursive pattern-matching lambdas for which every recursive cycle goes via something that is not inlined. In the example above a pattern-matching lambda mentions itself in its own body.

**Comment by nad** [comment]
For the new problem, see #5153.
