### ISSUE TITLE
type synonym in agda?

### ISSUE THREAD

**Issue by doofin** [agda/agda#2920]
Not sure whether it is ok to ask there.. Recently I am experimenting with W types,is it possible to write type synonym like that in haskell : type Nat = Nat2 ?

**Comment by nad** [comment]
I suggest that you use the mailing list for questions of this kind.

You can define "type synonyms" in the following way:
```agda
Nat : Set
Nat = Nat2
```
(Assuming that `Nat2` has type `Set`.)
