### ISSUE TITLE
COMPILE data for data types with erased constructor arguments

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#2921]
Reported by @nad in a comment to #2916.

Original example

```agda
open import Agda.Builtin.IO
open import Agda.Builtin.Unit

data Unit : Set where
  c : ⊤ → Unit

{-# FOREIGN GHC
  data Unit = Unit ()
  #-}

{-# COMPILE GHC Unit = data Unit (Unit) #-}

postulate
  foo : Unit → IO ⊤

{-# COMPILE GHC foo = \_ -> return () #-}

main : IO ⊤
main = foo (c _)
```

If you try to remove the argument to the Haskell `Unit` type, i.e.
```
{-# FOREIGN GHC data Unit = Unit #-}
```
you instead get
```
    • The constructor ‘Unit’ should have no arguments, but has been given 1
    • In the pattern: Unit a0
      In the declaration for pattern synonym ‘C4’
   |
18 | pattern C4 a0 = Unit a0
   |                 ^^^^^^^
```

**Comment by UlfNorell** [comment]
There's a question here on how to handle `COMPILE`-data bindings for data types with erased constructor arguments: should we erase constructor arguments or not?

The argument against is that it's not obvious to the user which arguments will be erased, so it's hard to tailor the Haskell type to fit. The argument for is that in the case that you *can* figure out which arguments get erased, it would be really annoying if you couldn't take advantage of this.

So, given that the down-side of erasing is some potential user confusion and the down-side of not erasing is slower code with no easy work-around for the user, I'm in favour of erasure.

**Comment by andreasabel** [comment]
@UlfNorell wrote:
> it's not obvious to the user which arguments will be erased, so it's hard to tailor the Haskell type to fit. 

This is in particular the case if the Haskell-types are third party, like, in my case, generated by the BNFC Haskell/Agda backend.  See #3732.
