### ISSUE TITLE
Allow adding the same rewrite rules multiple times

### ISSUE THREAD

**Issue by mietek** [agda/agda#2925]
For reasons of code organisation, I wish `Rewrite rule  foo  has already been added` was not an error.

**Comment by jespercockx** [comment]
I guess we could turn it into a warning instead of an error. Would that satisfy your needs?

**Comment by jespercockx** [comment]
I've implemented this and it seems to be working, but when I run the test suite for some reason no .warn file is generated. Does anyone know what's the proper way to create a test case that should produce a warning? (perhaps @gallais ?)

**Comment by fredrikNordvallForsberg** [comment]
You need to `touch` the .warn file yourself; then you can accept the new golden value. (Some succeeding tests contain some (possibly changing) debug output, so we didn't want to record output for all tests.)

**Comment by jespercockx** [comment]
Ah, that works. Thanks!
