### ISSUE TITLE
Panic related to sized types

### ISSUE THREAD

**Issue by nad** [agda/agda#2927]
Code:
```agda
open import Agda.Builtin.Equality
open import Agda.Builtin.Size

postulate
  P : (A : Set₁) → A → Set₁
  p : (i : Size) (f : {_ : Size< i} → Set) (x : _) →
      P ({_ : Size< i} → Set) f
```
Error message:
```
Panic: uncaught pattern violation
```
This is a regression, Agda 2.5.2 gives a proper error message:
```
Failed to solve the following constraints:
  Is not empty type of sizes: (Size< i)
Unsolved metas at the following locations:
  [...]:6,49-50
```

**Comment by nad** [comment]
Bisection points to 7109bbb2dd34ad3f0235c0e89822e299a6909778:
> Fixed #2412: do not insert hidden lambda for a possibly empty type of sizes.

**Comment by nad** [comment]
I see "jespercockx modified the milestones: 2.5.4, 2.5.5 7 days ago" above, but the milestone is 2.5.4.

**Comment by jespercockx** [comment]
I guess I first changed the milestone to 2.5.5 and then changed it back to 2.5.4.

**Comment by jespercockx** [comment]
It seems the interface of `checkSizeNeverZero` is suboptimal: its type is `TCM Bool` but it can also throw an unguarded `PatternViolation` when it encounters a meta. I will push a fix now that simply catches the error on the outside, but I think it would be good to revisit the way we check for possibly empty size types.
