### ISSUE TITLE
Turn "missing definition" into a warning

### ISSUE THREAD

**Issue by gallais** [agda/agda#2929]
If we find a declaration without an accompanying body, we can simply raise a warning,
refuse to make it available in the scope (or do so and declare it "NON_TERMINATING"
to avoid unfolding) but let the user keep interacting with the file.

**Comment by m0davis** [comment]
Isn't this already fixed by https://github.com/agda/agda/pull/3196?

**Comment by gallais** [comment]
Indeed it is!
