### ISSUE TITLE
Internal error when too few arguments to constructor

### ISSUE THREAD

**Issue by halfaya** [agda/agda#2935]
Attempting to pattern match against a constructor with too few arguments resulted in an internal error.
The fix, courtesy Jesper Cockx, is to modify useNamesFromPattern in ProblemRest.hs to rename the variables in the telescope that correspond to the supplied patterns, but also append any remaining telescope entries (without renaming), instead of throwing them away.

**Comment by m0davis** [comment]
Reportedly fixed by a2ffadd79c77631ca15af1a70c4bc945447a1186. @halfaya I believe including `Fixed #issue-number` in the commit message lets github associate it with the issue. In your commit, you left out the `#`.

**Comment by halfaya** [comment]
Okay, thanks for letting me know. As noted, this was fixed by https://github.com/agda/agda/commit/a2ffadd79c77631ca15af1a70c4bc945447a1186.
