### ISSUE TITLE
"coinductive" record inconsistent

### ISSUE THREAD

**Issue by gallais** [agda/agda#2941]
```agda
record ⊤ : Set where constructor tt
data ⊥ : Set where

open import Agda.Builtin.Size

record Delay (F : Size → Set) (i : Size) : Set where
  coinductive
  field force : {j : Size< i} → F j
open Delay public

data Stream (A : Set) (i : Size) : Set where
 _∷_ : A → Delay (Stream A) i → Stream A i

concat : Stream ⊤ ∞ → Delay (Stream ⊥) ∞
concat (xs ∷ xss) = concat (force xss)

head : Stream ⊥ ∞ → ⊥
head (x ∷ xs) = x

units : ∀ {i} → Stream ⊤ i
units = tt ∷ λ where .force → units

false : ⊥
false = head (force (concat units))
```

**Comment by UlfNorell** [comment]
Not sure about the `not (recRecursive d)` part...

https://github.com/agda/agda/blob/93c04e838b05c029093ddf48225585a4c47ce1c4/src/full/Agda/TypeChecking/Records.hs#L344-L345

**Comment by jespercockx** [comment]
Slightly simplified testcase:
```agda
data ⊥ : Set where

open import Agda.Builtin.Size

record Delay (F : Size → Set) (i : Size) : Set where
  coinductive
  field force : {j : Size< i} → F j
open Delay public

data Inf (i : Size) : Set where
 suc : Delay Inf i → Inf i

inf : ∀ {i} → Inf i
inf = suc λ where .force → inf

unroll : Inf ∞ → ⊥
unroll (suc x) = unroll (force x)

false : ⊥
false = unroll inf
```

**Comment by gallais** [comment]
good catch @UlfNorell. The following diff seems to fix the bug:

```diff
 isInductiveRecord :: QName -> TCM Bool
-isInductiveRecord r = maybe False (\ d -> recInduction d /= Just CoInductive || not (recRecursive d)) <$> isRecord r
+isInductiveRecord r = maybe False checkInductive <$> isRecord r where
+   checkInductive d = maybe (not (recRecursive d)) (== Inductive) (recInduction d)
 
 -- | Check if a type is an eta expandable record and return the record identifier and the parameters.
 isEtaRecordType :: Type -> TCM (Maybe (QName, Args))
```

The gist of it: if the user tells you it's `coinductive`, you better believe them. If they don't tell you anything, do try to guess (as long as you do so in a uniform way across the codebase, I suppose?)

Edit: probably a bit more complicated

* This diff triggers an internal error (at  [TypeChecking/Monad/Base.hs:1640](https://github.com/agda/agda/blob/stable-2.5/src/full/Agda/TypeChecking/Monad/Base.hs#L1640)) in [1035](https://github.com/agda/agda/blob/master/test/Fail/Issue1035.agda)
* Same for [784](https://github.com/agda/agda/blob/stable-2.5/test/LibSucceed/Issue784.agda)

**Comment by WolframKahl** [comment]
On Wed, Jan 31, 2018 at 03:39:35PM -0800, G. Allais wrote:
> good catch @UlfNorell. The following diff seems to fix the bug:
> 
> ```diff
>  isInductiveRecord :: QName -> TCM Bool
> -isInductiveRecord r = maybe False (\ d -> recInduction d /= Just CoInductive || not (recRecursive d)) <$> isRecord r
> +isInductiveRecord r = maybe False checkInductive <$> isRecord r where
> +   checkInductive d = maybe (not (recRecursive d)) (== Inductive) (recInduction d)
> ```

Nano-optimisation:
```
                                                      (Inductive ==)
```
(This saves a `flip`: Better not try to rely on GHC knowing that this particular `(==)` is symmetric.)


Wolfram

**Comment by UlfNorell** [comment]
Maybe my fix was too simplistic? The test suite and the example above goes through though.
