### ISSUE TITLE
Instance record "artificial" type checking problem ?

### ISSUE THREAD

**Issue by djanin** [agda/agda#2942]
Hello, 
The following code, with a valid proof term (Agda says so), creates a type error when instantiating a record with this valid proof term. Tested both with Agda  2.5.3 and 2.6.0-0170a69-dirty with ghc 8.0.1
Though I am just beginning with Agda, this sounds like a bug does it ? 
David

[Bug0.txt](https://github.com/agda/agda/files/1685026/Bug0.txt)

```agda
module Bug0 where

open import Agda.Builtin.Nat

record True  : Set where
data False : Set where

isNat : Nat -> Set
isNat zero = True
isNat (suc x)  = isNat x

sucInNat : ∀ {x : Nat} -> (isNat x) -> (isNat  (suc x))
sucInNat p = p

record recordedProof : Set where
     field foo :  ∀ {x : Nat} -> (isNat x) -> (isNat  (suc x))

recording : recordedProof
recording = record {foo = sucInNat}
```

**Comment by djanin** [comment]
Playing a bit more with this example, I see that

recordingAlt : recordedProof
recordingAlt = record {foo = λ {x} → sucInNat {x}}

compile just fine which suggest a unification problem with implicit argument doesn't it ?

Observe that I have already met a similar problem with GHC type checker where unification sometimes must be made explicit...

**Comment by identicalsnowflake** [comment]
I think it's because there is not a unique solution to the first parameter. Consider:

```agda
recording : recordedProof
recording = record {foo = λ {i} x → sucInNat {i} x }

recording' : recordedProof
recording' = record {foo = λ {i} x → sucInNat {suc i} x }
```

**Comment by djanin** [comment]
I agree there are many proofs... yet I still don't see why 
recording : recordedProof
recording = record {foo = λ {i} x → sucInNat {i} x }
is valid while
recording'' : recordedProof
recording'' = record {foo = sucInNat}
is NOT VALID since these two parameters are eta-equivalent aren't they ?

**Comment by identicalsnowflake** [comment]
Well they are eta equivalent with respect to the visible parameter, yes - you can remove the `x`s in my examples and nothing changes.

But the curly brackets parameter means "solve this parameter by unification." If there is not a provably unique solution, Agda will complain that it doesn't know which solution you want to use. In this example, there are multiple valid solutions for the curly brackets, e.g., `{i}` and `{suc i}`.

**Comment by djanin** [comment]
Hmm. I guess I see the point though I can probably practice some more to feel it in the depth.
Thanks for the answers and my apologies for having proposed a debug question instead of a bug report indeed.
Best

**Comment by identicalsnowflake** [comment]
Yup - for what it's worth, you're right that eta expansion of the curly parameter would be a valid solution, but that's just not what Agda is doing. Curly parameters are not solved via eta expansion - they're solved via unification.

If you remove all the curly brackets from your original code and replace them with visible parameters, everything will be solved as you expect.

**Comment by djanin** [comment]
Yes, I indeed eventually checked out that the « uncurlied » version work just fine.
Thanks again
