### ISSUE TITLE
Regression, seemingly related to record expressions

### ISSUE THREAD

**Issue by nad** [agda/agda#2944]
The following code is rejected by Agda 2.6.0-17a4b08, but accepted by Agda 2.5.3:
```agda
data D : Set where
  c : D → D

record R : Set where
  field f : D

f : D → R
f (c x) = record { f = x }

postulate
  P : (A : Set) → A → Set
  g : (x : D) → P R (f x) → P D x

h : (x : D) → P R (record { f = x }) → P D (c x)
h x = g _
```
Error message:
```
R.f (f (_x_13 x)) != x of type D
when checking that the expression g _ has type
P R (record { f = x }) → P D (c x)
```
The code is accepted if the only clause of `f` is replaced by the following code:
```agda
R.f (f (c x)) = x
```

**Comment by nad** [comment]
Bisection points to 32d9df61d939cdb968092f247494c3c8801ab3a5 ("[ injectivity ] improved pattern match inversion").

**Comment by UlfNorell** [comment]
The problem exists already in 2.5.3. Here's a variant:

```agda
open import Agda.Builtin.Nat

data D : Set where
  c : D → D

record R : Set where
  constructor mkR
  field f : Nat

f : D → R
f (c x) = mkR zero

postulate
  P : (A : Set) → A → Set
  g : (x : D) → P R (f x) → P D x

h : (x : D) → P R (record { f = zero }) → P D (c x)
h x = g _
```
It fails with
```
R.f (f (_x_13 x)) != zero of type Nat
```
but manually solving the meta with `c x` makes it check.

The problem is that we shouldn't invert stuck applications that have projection eliminations.
