### ISSUE TITLE
LaTeX-backend: add option to erase (prenex) implicit arguments

### ISSUE THREAD

**Issue by gallais** [agda/agda#2946]
It's quite common to remove them by hand to lighten the presentation in papers
using the convention that free variables are assumed to be quantified universally
at the beginning of a type.

It would be nice not to have to rely on brittle `sed` scripts (e.g. I'm still using an
old version of agda to generate papers because the introduction of `\AgdaSpace`
breaks my setup).

**Comment by nad** [comment]
Do you have some design in mind? How should this feature interact with alignment?

An alternative would be to add support for omitting certain implicit argument declarations from the code. We have discussed this in the past. As far as I recall we could probably do this by adding support for arguments that can only be given by name, and marking the variables that should be implicitly declared in some way. They could for instance use a special kind of name, or we could add some directive to declare such variables.

**Comment by UlfNorell** [comment]
cc #3071

**Comment by nachivpn** [comment]
@gallais How does one hide (even if manually) the implicit parameters of a function? 

Jesper suggested module parameters, but I just wanted to check if there were other options.

The variables feature does sound very cool, but since 2.6 is not out, I'm wondering if there's a way to avoid using dev.

**Comment by gallais** [comment]
[Here is the relevant part of my sed script](https://github.com/gallais/type-scope-semantics/blob/master/doc/rules.sed#L38).

Note that it only works:

* with **Agda-2.5.2** (in 2.5.3, the latex backend's output is different)
* if your implicit telescopes have the shape `{ ... } { ... } →` (i.e. no `∀`)
* there isn't too much nesting (implicit quantifiers inside the type of implicits are hard to deal with)

**Comment by nachivpn** [comment]
Thanks!

**Comment by nad** [comment]
Here's some Haskell code I've used to remove implicit argument declarations:
```haskell
{-# LANGUAGE OverloadedStrings #-}

import qualified Data.Text.IO as T
import qualified Data.Text.ICU as T
import qualified Data.Text.ICU.Replace as T

main = T.interact $ flip (foldr (uncurry T.replaceAll)) actions

actions :: [(T.Regex, T.Replace)]
actions =
    -- Remove implicit argument declarations (from "forall" to an
    -- arrow).
  [ ( "\\\\AgdaSymbol\\{forall\\}([^→]|\n)*\
      \\\\\AgdaSymbol\\{→\\}(\\\\AgdaSpace\\{\\})?"
    , ""
    )
  ]
```
It's been a while since I used this code, but perhaps it works well enough with the latest version of Agda.
