### ISSUE TITLE
Internal error in Agda.TypeChecking.Forcing

### ISSUE THREAD

**Issue by gallais** [agda/agda#2947]
> An internal error has occurred. Please report this as a bug.
> Location of the error: src/full/Agda/TypeChecking/Forcing.hs:111

triggered by:

```agda
open import Agda.Builtin.Nat

[_] :  (Nat → Set) → Set
[ T ] = ∀ {i} → T i

data D : Nat → Nat → Set where
  c : ∀ {i} → [ D i ]
```

**Comment by UlfNorell** [comment]
Related to #2919. The fix of that issue doesn't cover this case properly.
