### ISSUE TITLE
Wrong compilation of pattern matching to Haskell

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#2952]
The code below type checks with no errors or warning, but normalizing `main` in the Agda mode gives `putStr "left"` (the expected result), whereas compiling it to Haskell and running it gives `nowhere`.

```agda
open import Data.String
open import Data.Unit
open import Agda.Builtin.IO

module Bug where

{-# FOREIGN GHC import qualified Data.Text.IO as Text #-}
postulate
  putStr : String → IO ⊤
{-# COMPILE GHC putStr = Text.putStr #-}

data Term : Set where
  Var : String → Term
  App : Term → Term → Term

test : Term → String
test (Var _) = "var"
test (App (Var "x") b) = "left"
test (App a (Var "x")) = "right"
test (App a b) = "nowhere"

main : IO ⊤
main = putStr (test (App (Var "x") (Var "a")))
```

**Comment by gallais** [comment]
I get `nowhere` with 2.5.3 but `left` with `2.5.4`

Edit: btw, loading `Data.String.Base` cuts down the dependencies dramatically

**Comment by guillaumebrunerie** [comment]
Thanks, it seems to be already fixed in the stable branch indeed.
I found a different issue while upgrading to 2.5.4 : #2953

**Comment by asr** [comment]
@guillaumebrunerie, could you add a test case, please.

(since I don't know which commit fixed the issue, I don't know if a a test case was already added).
