### ISSUE TITLE
Support for async 2.2.1

### ISSUE THREAD

**Issue by asr** [agda/agda#2957]
Using  `async` [2.2.1](https://hackage.haskell.org/package/async-2.2.1) the interaction test-suite fails (in all the versions supported of GHC):

```
$ make install-bin CABAL_OPTS='--allow-newer=async --constraint=async==2.2.1'
$ make interaction
...
Issue2217
6a7,9
> (agda2-info-action "*Error*" "AsyncCancelled" nil)
> (agda2-highlight-load-and-delete-action)
> (agda2-status-action "")
...
```

The error is due to the above three *new* lines are generated *only* when using `async` >= 2.2.1.

I don't know if the new lines can be silenced from Emacs or we should only support  `async` >= 2.2.1.

I labelled the issue with `type: bug` and `milestone:2.5.4` because `async 2.2.1` will be required by Stackage (see https://github.com/fpco/stackage/issues/3268).

Support for `async` 2.2.1 is also required by #2878.

**Comment by nad** [comment]
The async library now uses `AsyncCancelled` instead of `ThreadKilled`. I suggest that we only support new versions of async.

**Comment by asr** [comment]
@nad, thank you for self-assigned this issue. Remember you need to modify the `stack-GHC-version.yaml` files too.

**Comment by asr** [comment]
@nad, thank you for self-assigned this issue.

> I suggest that we only support new versions of async.

I agree.

Remember you need to modify the `stack-GHC-version.yaml` files too.

**Comment by asr** [comment]
In relation to https://github.com/fpco/stackage/issues/3268, I only shall bump the upper version of async on Hackage (on the contrary the released `stack-GHC-version.yaml` files would not work).

**Comment by asr** [comment]
> I only shall bump the upper version of async on Hackage 

Done via [revision](https://hackage.haskell.org/package/Agda-2.5.3/revisions/) 4.

**Comment by nad** [comment]
> Remember you need to modify the `stack-GHC-version.yaml` files too.

How? These files don't mention `async`.

**Comment by asr** [comment]
Since `async` 2.2.1 will not available in (all) the LTSs,  see [what should you do](https://docs.haskellstack.org/en/stable/faq/#i-need-to-use-a-different-version-of-a-package-than-what-is-provided-by-the-lts-haskell-snapshot-im-using-what-should-i-do).

**Comment by nad** [comment]
> Done via [revision](https://hackage.haskell.org/package/Agda-2.5.3/revisions/) 4.

What's the point of this? Agda 2.5.3 does not support async 2.2.

**Comment by nad** [comment]
I've implemented a fix, but I don't know if I handled the `.yaml` files properly.

**Comment by asr** [comment]
> What's the point of this? Agda 2.5.3 does not support async 2.2.

I didn't find any error when using Agda 2.5.3 and `async` 2.2.1. Did you?

**Comment by nad** [comment]
What about the error that you posted above?

**Comment by asr** [comment]
I thought the problem only was a different golden file. I undid the change in Hackage.

**Comment by nad** [comment]
> I've implemented a fix, but I don't know if I handled the `.yaml` files properly.

Travis doesn't complain.

**Comment by asr** [comment]
@nad, thanks!
