### ISSUE TITLE
`as` names being duplicated in buffer after `with`

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda#2958]
Consider the following code
```agda
open import Data.Nat
  
pred≤ : ∀ n → pred n ≤ n
pred≤ v@n with n
... | zero = z≤n
... | suc m with m
...   | zero  = {!!}
...   | suc o = {!!}
```
After running `c-x c-,` in either of the holes, you get the following output:
```
Goal: suc o ≤ suc (suc o)
v : ℕ
v : ℕ
n : ℕ
o : ℕ
m : ℕ
```
Every time you use another `with` statement then another `v` appears in the buffer.

Agda version: 2.6.0-0ec3407-dirty

**Comment by UlfNorell** [comment]
Seems fixed now.

**Comment by nad** [comment]
OT: Perhaps we could include test cases for (some) reported bugs in the repository. That way we might notice when they get fixed "inadvertently".

**Comment by UlfNorell** [comment]
There are already some in `test/bugs`, but we haven't gotten around to setting up a proper test suite for them.

**Comment by nad** [comment]
We could put test cases in (say) `test/Fail` along with comments noting the desired behaviour.

**Comment by asr** [comment]
Good to know what `test/bugs` was for.
