### ISSUE TITLE
Compilation error in Haskell generated code

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#296]
What's the problem? Cut-and-pasted program examples are preferred over attachments (if reasonably short).

Generating Haskell code from somebody else's code

``` haskell
module CompilationBug where

open import Category.Monad using ( RawMonad )
open import IO.Primitive using ( _>>=_ ; IO ; return )

IOMonad : RawMonad IO
IOMonad = record { return = return; _>>=_ = _>>=_ }

postulate
  Unit : Set
  main : IO Unit
```

yields a compilation error

``` bash
/tmp/MAlonzo/CompilationBug.hs:18:41:
    Cannot match a monotype with `()
                  -> forall xB. () -> IO xA -> (xA -> IO xB) -> IO xB'
    Probable cause: `MAlonzo.IO.Primitive.d7' is applied to too few arguments
    In the expression: (MAlonzo.IO.Primitive.d7)
    In the expression: (\ v2 -> (MAlonzo.IO.Primitive.d7))
```

What version of Agda are you using? On what operating system (if relevant)?

The latest development versions of Agda and of the standard library (or the standard library version 0.3). The issue doesn't show up with Agda 2.2.6 and the standard library version 0.3.

Original issue reported on code.google.com by `andres.s...@gmail.com` on 17 Aug 2010 at 3:52

**Comment by asr** [comment]
The issue was fixed by 8f99021de9e0bc6833d21af29ee7b9c75ecbf427.
