### ISSUE TITLE
Uncommenting indented lines doesn't work

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#2960]
```agda
data A : Set where
  -- a : A

```

In emacs, selecting and trying to uncomment (`M-;`) the second line above simply double-comments the line, rather than uncommenting it.

This command does work properly on un-indented (top-level) lines.

**Comment by UlfNorell** [comment]
Possible culprit (although I haven't checked): 2077af4 (partial fix for #2794). @nad?

**Comment by andreasabel** [comment]
Must be.  This is a very recent regression.  Since I have not pulled for one week, it still uncomments correctly for me.

**Comment by nad** [comment]
I have already noticed this, presumably the problem is that I changed the syntax table. This also had other unintended consequences. I'll probably restore the syntax table (more or less).
