### ISSUE TITLE
agda-mode uncomment does the opposite

### ISSUE THREAD

**Issue by fredefox** [agda/agda#2961]
When I try to remove comments (uncomment) with `comment-line` in agda-mode for emacs it just comments the lines further. Same happens with `comment-region`. It only applies to members of modules or stuff define in let/where-bindings.

Steps to reproduce:

To try remove the comments here:

```
module _ where
  -- f : Set
  -- f = {!!}
```

Expected result: Comments are removed. Actual result:

```
module _ where
  -- -- f : Set
  -- -- f = {!!}
```

Similar thing happens for where/let.

This is a regression as it used to work. I won't rule out the possibility that my computer is hexed.

I should add that switching to e.g. `haskell-mode` let's me uncomment without a hitch.

**Comment by fredefox** [comment]
Any proposed work-around is also quite welcome (something more handy than changing mode).

Manually uncommenting many lines is a bother.

Also: `agda2-comment-dwim-rest-of-buffer` works fine.

```
$ agda --version
Agda version 2.6.0-6f3203e
```

**Comment by identicalsnowflake** [comment]
It's probably #2960, since the commit hash you linked is from right before the fix was pushed.

**Comment by fredefox** [comment]
That's great. I'll have a look. Thank you so much!

**Comment by fredefox** [comment]
Jubilation! Thanks @identicalsnowflake - and sorry for not spotting that issue.

Closing. Duplicate of #2960.

**Comment by WolframKahl** [comment]
On Mon, Feb 12, 2018 at 04:37:52AM -0800, Frederik Hanghøj Iversen wrote:
> Manually uncommenting many lines is a bother.

?

In Emacs, assuming the `-- ` are nicely lined up, I use the rectangle command:

C-x C-r C-d

**Comment by andreasabel** [comment]
`M-;` should also uncomment commented lines (if all are commented out).
