### ISSUE TITLE
Copattern split with `--no-irrelevant-projections` panics

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#2971]
```agda
{-# OPTIONS --no-irrelevant-projections #-}

open import Agda.Builtin.Nat
open import Agda.Builtin.Equality

record Five : Set where
  field
    five : Nat
    .prf : five ≡ 5

best-number : Five
best-number = {!!} -- C-c C-c (on result)

-- Panic: Unbound name: NoIrrProj.Five.prf
-- [0,2,10]@5465979233139828506
-- when checking that the expression ? has type Five
```

**Comment by andreasabel** [comment]
Well, the projection is not in scope (that's how we implemented `--no-irrelevant-projections`). But I suppose I never tested this case when implemented result splitting.  I suppose there should be a better error message.

**Comment by andreasabel** [comment]
Trying to debug this with option `-v tc.cover:20` triggers #2996.

**Comment by andreasabel** [comment]
In my work on #2170, I changed the fix of this.  We can always create irrelevant projections, but may only use them on the _rhs_ if `--irrelevant-projections`.  On the lhs, they are always fine, since they are also fine as record expression field tags.
