### ISSUE TITLE
Agda inserts superfluous parentheses

### ISSUE THREAD

**Issue by nad** [agda/agda#2973]
Consider the following code:
```agda
data D : Set₁ where
  c_ : Set → D

postulate
  F : Set → Set
  A : Set

B : D
B = ?
```
If I first use `Cmd_refine_or_intro` in the hole (to introduce the constructor `c_`), and then `Cmd_give` with `F A` as the argument, then Agda inserts `c (F A)`, with superfluous parentheses. However, if I write the constructor manually, and then give `F A`, then the superfluous parentheses are not inserted.

Here is a script that can be used for testing:
```shell
#!/bin/sh

AGDA=$1

$AGDA --interaction --no-libraries --ignore-interfaces <<EOF
IOTCM "Bug.agda" None Indirect (Cmd_load "Bug.agda" [])
IOTCM "Bug.agda" None Indirect (Cmd_refine_or_intro False 0 noRange "")
IOTCM "Bug.agda" None Indirect (Cmd_give WithoutForce 1 noRange "F A")
EOF
```

**Comment by UlfNorell** [comment]
Duplicate of #737?

**Comment by nad** [comment]
Yes, perhaps.
