### ISSUE TITLE
Emacs mode reports errors in connection with highlighting comments

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2976]
Since very recently (just observing this behavior for the first time now), the emacs mode seems broken:
```agda
postulate A : Set

-- Comment

postulate B : Set
```
Emacs reports 
```
error in process filter: let*: Wrong type argument: sequencep, font-lock-comment-delimiter-face
error in process filter: Wrong type argument: sequencep, font-lock-comment-delimiter-face
```
and the part `postulate B : Set` after the comment is not highlighted.

Also, if I invoke an interactive command then, I get the error
```
progn: Another command is currently in progress
(if a command has been aborted you may want to restart Agda)
```
My versions:
```
Agda version 2.6.0-3833173-dirty
GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9)
 of 2017-09-20 on lcy01-07, modified by Debian
```
This does not seem to be a problem in stable (2.5.4).

**Comment by nad** [comment]
Did you by any chance forget to recompile the Emacs mode when reinstalling Agda? (See #2962.)

**Comment by andreasabel** [comment]
I hardly recompile the Emacs mode ever.  If the `.elc` files are outdated, emacs works with the `.el` files.  (At least this is the impression I got.)
Anyway, I ran the compilation:
```
$ agda-mode compile
Wrote /home/abel/.cabal/share/x86_64-linux-ghc-7.10.3/Agda-2.6.0/emacs-mode/agda2-abbrevs.elc
Wrote /home/abel/.cabal/share/x86_64-linux-ghc-7.10.3/Agda-2.6.0/emacs-mode/annotation.elc
Wrote /home/abel/.cabal/share/x86_64-linux-ghc-7.10.3/Agda-2.6.0/emacs-mode/agda2-queue.elc
Wrote /home/abel/.cabal/share/x86_64-linux-ghc-7.10.3/Agda-2.6.0/emacs-mode/eri.elc
Wrote /home/abel/.cabal/share/x86_64-linux-ghc-7.10.3/Agda-2.6.0/emacs-mode/agda2.elc
Wrote /home/abel/.cabal/share/x86_64-linux-ghc-7.10.3/Agda-2.6.0/emacs-mode/agda-input.elc
Wrote /home/abel/.cabal/share/x86_64-linux-ghc-7.10.3/Agda-2.6.0/emacs-mode/agda2-highlight.elc
Loading quail/latin-ltx...
Wrote /home/abel/.cabal/share/x86_64-linux-ghc-7.10.3/Agda-2.6.0/emacs-mode/agda2-mode.elc
```
But this did not fix the problem or change the observed behavior in any way.

**Comment by nad** [comment]
>  If the `.elc` files are outdated, emacs works with the `.el` files.

[Not by default](https://www.gnu.org/software/emacs/manual/html_node/emacs/Lisp-Libraries.html).

Anyway, I don't observe your problems. What happens if you reinstall from scratch?

**Comment by amakuri** [comment]
In case this helps, I seem to be having a similar issue (after updating from 1869b907d2d77c1d68de4af8ac521c8fb988b8b6 to current HEAD b7541319c09f308785e8966d734ae9a06cffc19a).

emacs output:
```
error in process filter: annotation-append-text-property: Wrong type argument: sequencep, font-lock-comment-face
error in process filter: Wrong type argument: sequencep, font-lock-comment-face
```

emacs backtrace:
```
Debugger entered--Lisp error: (wrong-type-argument sequencep font-lock-comment-face)
  union(font-lock-comment-face (font-lock-comment-face))
  annotation-append-text-property(2 9 face (font-lock-comment-face))
  annotation-annotate(2 9 (comment) nil nil)
  annotation-load("Click mouse-2 to jump to definition" (2 9 (comment) nil))
  apply(annotation-load "Click mouse-2 to jump to definition" (2 9 (comment) nil))
  agda2-highlight-apply((2 9 (comment) nil))
  apply(agda2-highlight-apply (2 9 (comment) nil))
  agda2-highlight-load("[[userpath]]\\AppData\\Local\\Temp\\agda2-mode13604-0")
  agda2-highlight-load-and-delete-action("[[userpath]]\\AppData\\Local\\Temp\\agda2-mode13604-0")
  eval((agda2-highlight-load-and-delete-action "[[userpath]]\\AppData\\Local\\Temp\\agda2-mode13604-0"))
  agda2-exec-response((agda2-highlight-load-and-delete-action "[[userpath]]\\AppData\\Local\\Temp\\agda2-mode13604-0"))
  mapc(agda2-exec-response ((agda2-status-action "") (agda2-info-action #("*Type-checking*" 0 15 (face (:weight bold))) "" nil) (agda2-highlight-clear) (agda2-highlight-load-and-delete-action "[[userpath]]\\AppData\\Local\\Temp\\agda2-mode13604-0") (agda2-status-action "Checked") (agda2-info-action "*All Done*" "" nil)))
  agda2-output-filter(#<process Agda2> "(agda2-status-action \"\")\n(agda2-info-action \"*Type-checking*\" \"\" nil)\n(agda2-highlight-clear)\n(agda2-highlight-load-and-delete-action \"[[userpath]]\\\\AppData\\\\Local\\\\Temp\\\\agda2-mode13604-0\")\n(agda2-status-action \"Checked\")\n(agda2-info-action \"*All Done*\" \"\" nil)\n((last . 1) . (agda2-goals-action '()))\nAgda2> ")
```

I don't have experience in elisp, but this is my explanation & fix:

In my case the error seems to originate in `annotation.el`, in `annotation-append-text-property`, being caused by `get-text-property` not returning a sequence, but a single value.

Defining
```elisp
(defun make-sequence (old)
  (if (sequencep old) old (list old)))
```
and calling it in `annotation-append-text-property`
```elisp
(defun annotation-append-text-property (start end prop values)
  "Merges VALUES to text property PROP between START and END."
  ;; (message "AGDA: ")
  (let ((pos start)
        mid)
    (while (< pos end)
      (setq mid (next-single-property-change pos prop nil end))
      (let* ((old-values (make-sequence (get-text-property pos prop)))
             (all-values (union old-values values)))
        (put-text-property pos mid prop all-values)
        (setq pos mid)))))
```
seems to fix my issue.

**Comment by nad** [comment]
Thanks for identifying the problem.

The implementation of `annotation-append-text-property` seems to be based on the assumption that the property `prop` is a list. However, as has been observed this is not necessarily the case. In the specific case of the `face` property [several different kinds of values are supported](https://www.gnu.org/software/emacs/manual/html_node/elisp/Special-Properties.html#index-face-codes-of-text-3409). The fix above doesn't quite work, because `sequencep` returns `t` for both lists and cons cells that are not part of a list. It seems to me as if one should perhaps be more careful, and only call `annotation-append-text-property` when this is known to be sensible. (And given that the ordering of the resulting list matters in some cases one should perhaps not use `union` as in the current implementation.)

@fredrikNordvallForsberg, you implemented `annotation-append-text-property` (6081e1bcd647c4e3c8df31bcd7473fc335ea2679). The commit message is rather spartan: "[ emacs ] merge highlighting aspects". Can you recall the motivation for doing this?

**Comment by fredrikNordvallForsberg** [comment]
The motivation was to highlight also the foreground of text that was given a background, such as the then recently introduced highlighting of unreachable clauses.

I still cannot reproduce the issue (using Agda 2.6.0-34086c) on Andreas' original file, @amakuri do you have a small test that triggers the bug?

**Comment by nad** [comment]
> @amakuri do you have a small test that triggers the bug?

Preferably using `emacs -Q`.

**Comment by amakuri** [comment]
No, not yet - I am using spacemacs, but I'm going to try to reproduce it in a "simple" environment.

**Comment by amakuri** [comment]
In my case the bug is triggered by the `hl-todo` package (https://github.com/tarsius/hl-todo).

It can be reproduced in a clean emacs installation by:
1. Adding the melpa archive
2. Installing `hl-todo`
3. Adding a prog-mode-hook
4. Adding code to load agda-mode

The `.emacs` file is thus:
```elisp
(package-initialize)

;; melpa archive
(require 'package)
(add-to-list
   'package-archives
   '("melpa" . "http://melpa.milkbox.net/packages/")
   t)

;; agda-mode
(load-file (let ((coding-system-for-read 'utf-8))
                (shell-command-to-string "agda-mode.exe locate")))

;; hl-todo
(require 'hl-todo)
(add-hook 'prog-mode-hook 'hl-todo-mode)

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages (quote (hl-todo))))
```

Example file (`test.agda`):
```agda
module _ where
--  this is a comment
```

Opening the example file and pressing `C-c C-l` should produce the following message:
```
error in process filter: annotation-append-text-property: Wrong type argument: sequencep, font-lock-comment-face
```

**Comment by gunpinyo** [comment]
I have exactly the same error message; I also can reproduce the bug in Andreas's original file.

(Agda version 2.6.0-8a7ad7f)
Note: definitely not the problem with not recompiling the Agda, as I use cabal sandbox.
(Emacs version 25.2.2)
(Spacemacs version 0.200.13)

After trying to figure the bug, this error will not occur if there is no comment in the file, which indeed makes sense with the error message above.

**Comment by nad** [comment]
Here's an easy way to trigger the bug in a non-empty Agda file:
* Type `M-x (set-text-properties 1 2 '(face font-lock-comment-face)) RET`.
* Load the file.

**Comment by gunpinyo** [comment]
@nad That is one of many possibilities that I I have tried for a whole day.
but all of them don't seem to work :(, also after removing all comments in some particular file then load again I start to get the same error message but with another face.
Don't worry, this bug doesn't occur for 2.5.2.
So I just need to roll back to and use it for a while, although 2.5.2 doesn't have cubical-agda.

**Comment by andreasabel** [comment]
I do not get the problem for 2.5.3 or 2.5.4 (stable) either; it is only with 2.6.0.

**Comment by nad** [comment]
I can trigger the bug also on the stable branch, using the procedure from my previous comment.

**Comment by asr** [comment]
> After trying to figure the bug, this error will not occur if there is no comment in the file.

Right. I just hit this issue when writing a test case for #3044 and removing the comment fixed the problem.

**Comment by nad** [comment]
This should be fixed before the next release.

**Comment by andreasabel** [comment]
Actually, for me only 2.6.0 was broken, now 2.5.4 is broken too.

**Comment by nad** [comment]
I fixed the problem reported in [a comment above](https://github.com/agda/agda/issues/2976#issuecomment-375930297), and I have no idea how to reproduce the problems you are experiencing. Please provide a detailed recipe for reproducing the problems, using `emacs -Q`.

**Comment by andreasabel** [comment]
If I revert to  8622458 (before your commits of the last 7 days), Agda 2.5.4 works again for me on emacs.
The problem is easily reproduce. Just load any Agda file. `C-c C-l` is answered by
```
agda2-abort-if-in-progress: Another command is currently in progress
(if a command has been aborted you may want to restart Agda)
```
With `emacs -Q` I experience the same problem:
The *agda2* buffer says:
```
IOTCM "/home/abel/Teaching/SRI/lec2/src/Substitution.agda" NonInteractive Indirect ( Cmd_load_highlighting_info "/home/abel/Teaching/SRI/lec2/src/Substitution.agda" )
Agda2> (agda2-status-action "")
IOTCM "/home/abel/Teaching/SRI/lec2/src/Substitution.agda" NonInteractive Indirect ( Cmd_load "/home/abel/Teaching/SRI/lec2/src/Substitution.agda" [] )
(agda2-status-action "")
(agda2-info-action "*Type-checking*" "" nil)
(agda2-info-action "*Type-checking*" "Checking Substitution (/home/abel/Teaching/SRI/lec2/src/Substitution.agda).\n" t)
(agda2-info-action "*Type-checking*" " Checking IPL (/home/abel/Teaching/SRI/lec2/src/IPL.agda).\n" t)
(agda2-status-action "Checked")
(agda2-info-action "*All Done*" "" nil)
((last . 1) . (agda2-goals-action '()))
```
(Looks ok.)

The *Messages* buffer says:
```
error in process filter: annotation-load: Wrong number of arguments: nil, 0
error in process filter: Wrong number of arguments: nil, 0
```

**Comment by nad** [comment]
If I run `emacs -Q Foo.agda`, then `Foo.agda` is opened in fundamental mode. Please provide more detailed instructions.

**Comment by UlfNorell** [comment]
FWIW I have no problems on my machine, either with Aquamacs or `emacs -Q` (and manually loading the agda mode).

**Comment by andreasabel** [comment]
Well the detailed instruction would be to install Ubuntu 16.4 LTS with the default emacs there (emacs24), start emacs -Q, do M-x load-file <agda2.el> and then load an Agda file.

**Comment by nad** [comment]
Any Agda file? Does it matter if a corresponding `.agdai` file exists?

I tried to open a previously non-existing Agda file using your recipe, but with GNU Emacs 25.2.2 on Ubuntu 18.04 LTS, and did not experience any problems. I don't have easy access to Emacs 24. Can you debug and fix this problem yourself? I think it makes sense to still support Emacs 24.

**Comment by asr** [comment]
> Well the detailed instruction would be to install Ubuntu 16.4 LTS with the default emacs there (emacs24), start emacs -Q, do M-x load-file <agda2.el> and then load an Agda file.

I followed your detailed instruction :-)

Seriously, I couldn't reproduce the issue using Ubuntu 16.04.4 LTS and both the default GNU Emacs (24.5.1) or 25.3.1.

**Comment by andreasabel** [comment]
I think my problem can be solved by `make compile-emacs-mode` (blush).
Great! I can run 2.6.0 again!

**Comment by nad** [comment]
Great.
