### ISSUE TITLE
User manual link check fails a lot on Travis

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#2980]
I'm disabling the job for now.

**Comment by UlfNorell** [comment]
After disabling that job Travis fails after 30 seconds with `rake` complaining about no `Rakefile`. I don't see how that can possibly be my fault... Any Travis experts around? @asr?

**Comment by asr** [comment]
I guess Travis cannot parse the commented-out line, so it is using some default. The above commit fix the missing `rake` problem.

**Comment by UlfNorell** [comment]
Wow. What language is the yml file written in that doesn't allow comments inside if statements?

**Comment by andreasabel** [comment]
Probably not bnfc. Haha!

**Comment by asr** [comment]
The previous broken link (http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html) is working now.

**Comment by UlfNorell** [comment]
It wasn't just that one though. I got failures on several other links (www.vim.org for instance) that I suspect were just a bit slow to respond. I guess we can wait and see if it starts failing again...

**Comment by andreasabel** [comment]
It has started failing again.

**Comment by andreasabel** [comment]
I switched it to "allowed_failures".
