### ISSUE TITLE
Internal error related to record patterns

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#2981]
The code below fails with the error 
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/RecordPatterns.hs:144
```

I am on the stable branch, and this error did not occur a few weeks ago.
Note that `f` and `R` are not used anywhere, but if you remove either of them, the error goes away.

Edit: simplified the code further.
```agda
record Unit : Set where
  constructor tt

postulate
  C : Set
  c : C

g : C

f : Unit → C
f tt = c

record R : Set where
  constructor r

g = c
```

**Comment by guillaumebrunerie** [comment]
I haven’t done a bisection, but presumably the culprit is ecf5e7fde63f96a78d9e76929bf9907c78703307.

**Comment by UlfNorell** [comment]
Yes, indeed. I assumed (without checking) that record pattern translation happened only once for each case tree. It turns out there's a function called `revisitRecordPatternTranslation`...
