### ISSUE TITLE
The termination checker accepts non-terminating code

### ISSUE THREAD

**Issue by nad** [agda/agda#2985]
The following code should not be accepted:
```agda
open import Agda.Builtin.Size

mutual

  data Unit (i : Size) : Set where
    c : Unit′ i → Unit i

  record Unit′ (i : Size) : Set where
    coinductive
    field
      force : {j : Size< i} → Unit j

open Unit′ public

tail : Unit ∞ → Unit ∞
tail (c x) = force x

u : (∀ {i} → Unit′ i → Unit i) →
    ∀ {i} → Unit i
u cons = tail (cons λ { .force → u cons })

bad : Unit ∞
bad = u c
```
The problem goes back at least to Agda 2.5.2. I suspect that one can use this bug to prove that the empty type is inhabited.

I think this is a rather serious problem. I was working on some code and realised that it should not have been accepted, and now I wonder if I have accidentally relied on this bug in other code.

**Comment by UlfNorell** [comment]
> I suspect that one can use this bug to prove that the empty type is inhabited.

Indeed:
```agda
open import Agda.Builtin.Size

data ⊥ : Set where

mutual

  data Unit (i : Size) : Set where
    c : Unit′ i → Unit i

  data Unit₁ (i : Size) : Set where
    c₁ : ⊥ → Unit i → Unit₁ i

  record Unit′ (i : Size) : Set where
    coinductive
    field
      force : {j : Size< i} → Unit₁ j

open Unit′ public

tail : Unit ∞ → Unit₁ ∞
tail (c x) = force x

u : (∀ {i} → Unit′ i → Unit i) →
    ∀ {i} → Unit₁ i
u cons = tail (cons λ { .force → u cons })

bad : Unit₁ ∞
bad = u c

refute : Unit₁ ∞ → ⊥
refute (c₁ () _)

loop : ⊥
loop = refute bad
```

**Comment by andreasabel** [comment]
Is this one different from #1946 ? (Just a hunch.)

**Comment by nad** [comment]
I don't see any similarity. There's no structural recursion in my example.

**Comment by nad** [comment]
The following variant of my example is rejected by Agda:
```agda
u : (∀ {i} → Unit′ i → Unit i) →
    ∀ {i} → Unit i
u cons = tail (cons {∞} λ { .force → u cons })
```
However, Agda accepts the following code and the goal is instantiated to `∞`:
```agda
u : (∀ {i} → Unit′ i → Unit i) →
    ∀ {i} → Unit i
u cons = tail (cons {?} λ { .force → u cons })
```

**Comment by nad** [comment]
I have not managed to trigger the bug without using a pattern-matching lambda.

Inspection of debug output suggests that the termination checker works on the code with `?` instantiated to `∞`, but if I write `∞` manually, then the termination checker complains.

**Comment by nad** [comment]
Now I'm looking at the following code:
```agda
{-# OPTIONS -vtc:20 -vterm:20 #-}

open import Agda.Builtin.Size

mutual

  data Unit (i : Size) : Set where
    c : Unit′ i → Unit i

  record Unit′ (i : Size) : Set where
    coinductive
    field
      force : (j : Size< i) → Unit j

open Unit′ public

postulate
  tail : Unit ∞ → Unit ∞
  cons : ∀ i → Unit′ i → Unit i

u : ∀ i → Unit i
u i = tail (cons _ λ { .force j → u j })
```
The debug output includes the following text:
```
kept call from Bug..extendedlambda0 i .Bug.Unit′.force j
  to Bug.u (j)
  call matrix (with guardedness): 
    -1    ?    ?    ?
     ?   -2    ?    =
```
If I replace the final underscore with `∞`, then I instead get the following output:
```
kept call from Bug..extendedlambda0 i .Bug.Unit′.force j
  to Bug.u (j)
  call matrix (with guardedness):
    -1    ?    ?    ?
     ?    ?    ?    =
```
The inferred type of `Bug..extendedlambda0` seems to be `(i : Size) → Unit′ ∞` in the former case, and `Size → Unit′ ∞` in the latter.

**Comment by nad** [comment]
I discussed this with @andreasabel, who said that `-2` might come from an uninstantiated meta-variable.

I added an assertion that the meta-variable is uninstantiated to the following code, and managed to trigger it using one of the problematic pieces of code above:
https://github.com/agda/agda/blob/a53521ba799e8a3e96ad6451ba0b2e30923f2fdd/src/full/Agda/Termination/TermCheck.hs#L1183-L1192

**Comment by nad** [comment]
Adding a call to `instantiate` seems to fix the problem. However, it seems as if the precondition of `compareTerm'` is broken by some caller:
https://github.com/agda/agda/blob/a53521ba799e8a3e96ad6451ba0b2e30923f2fdd/src/full/Agda/Termination/TermCheck.hs#L1163-L1165

**Comment by nad** [comment]
I'm implementing a temporary fix.

**Comment by andreasabel** [comment]
The `data` is not necessary for this bug:
```agda
{-# BUILTIN SIZEUNIV SizeU #-}
{-# BUILTIN SIZE     Size   #-}
{-# BUILTIN SIZELT   Size<_ #-}
{-# BUILTIN SIZEINF  ∞      #-}

record Unit (i : Size) : Set where
  coinductive
  field
    force : (j : Size< i) → Unit j

postulate
  tail : Unit ∞ → Unit ∞
  id   : ∀ i → Unit i → Unit i

u : ∀ i → Unit i
u i = tail (id _ λ { .Unit.force j → u j })
```

**Comment by andreasabel** [comment]
I am not sure there is any more to be done to your temporary fix.  The 
```
Precondition: top meta variable resolved
```
is already violated by the first recursive call I can see in `compareTerm'`.  It seems just a lie.
As we do not track invariants as such in the type system (probably this would be impossible, since we have meta-variables and state), they get easily broken by refactorings and other patches.

Maybe it used to be the case that termination checking was preceeded by an `instantiateFull`.  But this is anyway bad style.  It is safer to ensure invariants locally.  Global invariants will just evaporate during code evolution.

**Comment by nad** [comment]
I tried to remove the only (live) occurrence of `instantiateFull` from `Agda.Termination.TermCheck`:

https://github.com/agda/agda/blob/b7541319c09f308785e8966d734ae9a06cffc19a/src/full/Agda/Termination/TermCheck.hs#L778-L792

The test suite did not complain. It seems as if I added this call to `instantiateFull` back in 2007 (b2942b71d7d018ffb6cb16fcd1d739b1bee02572). Do you think it is safe to remove it? The comment discusses eta-contraction, and I don't think `instantiate` performs eta-contraction.

**Comment by andreasabel** [comment]
Well, `reduceCon` only works reliably if meta variables have been instantiated at this point.  Unless we can prove that all metas are instantiated here, it feels safer to leave the call in.

But, instead of doing it here, it would make more sense to do it closer to where the invariant (no instantiated metas, no reduceable constructors) is needed.  For instance, we could move it to `compareTerm`.

**Comment by nad** [comment]
> Well, `reduceCon` only works reliably if meta variables have been instantiated at this point.

One option might be to change `reduceCon` so that it instantiates meta-variables on demand.

**Comment by andreasabel** [comment]
And also `stripAllProjections`.

**Comment by andreasabel** [comment]
Refactoring task moved to #3041.
