### ISSUE TITLE
Agda Abstract Machine does not honor IApply

### ISSUE THREAD

**Issue by Saizan** [agda/agda#2986]
So I'm surprised I didn't have a test case for this, but the new Fast reduce kinda breaks cubical, because we get the following:
```agda
{-# OPTIONS --cubical #-}
module _ where

open import Agda.Primitive.Cubical

postulate
  PathP : ∀ {ℓ} (A : I → Set ℓ) → A i0 → A i1 → Set ℓ

{-# BUILTIN PATHP        PathP     #-}

postulate
  A : Set
  a : A
  p : PathP (\ _ → A) a a


works : ∀ {p : PathP (\ _ → A) a a} {P : A → Set} → P (p i0) → P a
works x = x

fails : ∀ {P : A → Set} → P (p i0) → P a
fails x = x
--- here  p i0 /= a, while it should
```

The problem seems to be that when evaluating a ```Closure``` the AM does not look at the spine to see if there are ```IApply``` patterns with ```i0``` or ```i1``` for their interval element, in which case it should use one of the endpoints in the ```IApply``` to reduce to, see ```reduceIApply``` in Reduce.hs.

@UlfNorell, I can make the proposed change myself, but maybe there's something more efficient that could be done?

**Comment by UlfNorell** [comment]
Why don't you make the change first and then we can see about making it more efficient. One simple optimisation would be to only do the check if `--cubical`.

**Comment by Saizan** [comment]
I guess I was wondering if the stack should worry about this, but this simple patch works fine it seems.

Checking only if ```--cubical``` would be quite confusing if you are only importing defined paths but not defining any yourself, and so not using the flag in the current module.
