### ISSUE TITLE
Incorrect Git hash

### ISSUE THREAD

**Issue by nad** [agda/agda#2988]
I realised that the Git hash that `agda --version` prints wasn't correct for some binaries that I have compiled, it pointed to some old commit. I fixed this by touching `src/full/Agda/VersionCommit.hs` before rebuilding. Has anyone else observed this?

I don't know how to reproduce this problem.

**Comment by UlfNorell** [comment]
Yes, this happens to me a lot too.

**Comment by nad** [comment]
Since this only affects the development version I guess a simple way to fix it would be to touch `src/full/Agda/VersionCommit.hs` in the makefile.

**Comment by nad** [comment]
The [gitrev](https://github.com/acfoltzer/gitrev) documentation suggests that the file should be recompiled automatically every time. Perhaps we could file a bug report. However, as I wrote above I don't know how to reproduce this problem.

**Comment by nad** [comment]
I've implemented the simple fix mentioned above.

A small correction: The problem might not only affect the development version, because we generate Git hashes whenever Agda is built from a Git repository. However, if you run `cabal install Agda`, then you do not get a Git hash.

**Comment by asr** [comment]
I cherry-picked the fix on `release-2.5.4` only because we shouldn't have *closed* bugs with milestone `2.5.5` before releasing 2.5.4.

**Comment by nad** [comment]
Why not? What if my commit inadvertently introduced a regression that could have been caught with a little more testing?

**Comment by asr** [comment]
In our current approach, if a serious<sup>1</sup> regression is introduced we'll release a bug-fix version. If you think your commit is fragile<sup>1</sup> please tell us (as you usually do).


<sup>1</sup> Whatever that means.

**Comment by andreasabel** [comment]
I do not have an opinion about the current issue, because a regression here would not be very harmful.
In general I think it is fine to fix an issue for 2.5.5 and not release it with 2.5.4.
