### ISSUE TITLE
Internal error when checking record match in let expr

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#2989]
```agda
open import Agda.Builtin.Nat renaming (Nat to ℕ)
open import Data.Product
open import Agda.Builtin.Equality

record Fin (n : ℕ) : Set where
  field
    m : ℕ
    .p : ∃ λ k → (ℕ.suc k + m) ≡ n

f : ∀ {n} → Fin n → Fin n
f {suc n} x = let record { m = m ; p = k , p } = f x in {!!}
f _ = ?

```

Loading with `C-c C-l` yields `An internal error has occurred. Please report this as a bug. Location of the error: src/full/Agda/TypeChecking/Records.hs:164`.

**Comment by nad** [comment]
Here is a test case that does not depend on the standard library:
```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Equality

record Σ (A : Set) (B : A → Set) : Set where
  constructor _,_
  field
    proj₁ : A
    proj₂ : B proj₁

open Σ public

∃ : {A : Set} → (A → Set) → Set
∃ = Σ _

record Fin (n : Nat) : Set where
  field
    m : Nat
    .p : ∃ λ k → (Nat.suc k + m) ≡ n

f : ∀ {n} → Fin n → Fin n
f {suc n} x = let record { m = m ; p = k , p } = f x in {!!}
f _ = ?
```

The problem seems to go back to Agda 2.5.2.

**Comment by scott-fleischman** [comment]
If you use a nested `let` it shows a more helpful error message:
```
f {suc n} x = let record { m = m ; p = q } = f x in let k , p = q in {!!}
```
```
Variable q is declared irrelevant, so it cannot be used here
when inferring the type of q
```

**Comment by identicalsnowflake** [comment]
@scott-fleischman ya it's a bit odd because using a `with` and matching on the same record pattern allows it to go through.

EDIT: I should clarify - I think the `with` is probably correct, as it allows the match but still only allows the pieces to be used in irrelevant contexts, which is right where I needed them.

**Comment by andreasabel** [comment]
Shrank this to:
```agda
postulate
  N : Set
  P : N → Set

record Σ (A : Set) (B : A → Set) : Set where
  constructor pair
  field
    fst : A
    snd : B fst

Σ' : (A : Set) → (A → Set) → Set
Σ' = Σ

record R : Set where
  constructor mkR
  field
    .p : Σ' N P

-- Error goes away if Σ' is replaced by Σ
-- or field is made relevant

f : R → Set
f x = let mkR (pair k p) = x in N
```

**Comment by andreasabel** [comment]
This is fixed by adding a `reduce` in `Agda.TypeChecking.Records.getRecordTypeFields` which is called from the record-pattern to projections translation in `RecordPatterns`.

Frankly, I do not understand why, because there is a `reduce` in plain sight just before the call to `getRecordTypeFields`:
https://github.com/agda/agda/blob/21536f6d5ad08d2b4258c3c4d464ded3718d152a/src/full/Agda/TypeChecking/RecordPatterns.hs#L72

@UlfNorell : is `reduce` no longer idempotent?  How to debug `reduce`?  (It is much more complicated now...)

**Comment by UlfNorell** [comment]
It’s easier now. Run with `-v tc.reduce.fast:110` to get a trace of the machine. It should be idempotent.

**Comment by andreasabel** [comment]
Ah, I found the reason.  The call to `reduce` is on `Arg Type` and because of irrelevance, it does not reduce anything.  Only after `unArg`, reduction is effective.

Best not too rely on preconditions too much...
