### ISSUE TITLE
Performance regression related to the abstract machine

### ISSUE THREAD

**Issue by nad** [agda/agda#2990]
Some code that used to check without problems started running out of memory. Bisection (unsurprisingly) points to the introduction of the abstract machine (a02895d2c897f6926fd0e9ec5bf37fd8b6d9cb3c).

To reproduce the problem:
```
mkdir bug
cd bug
(git clone http://www.cse.chalmers.se/~nad/repos/equality/ && cd equality && git checkout 398d6fe90c6f41257c2d66a5bd6e65d01e5a271a)
(git clone http://www.cse.chalmers.se/~nad/repos/delay-monad/ && cd delay-monad && git checkout 5629cc83005ce9029141be3916cc0e4a1901610d)
(git clone http://www.cse.chalmers.se/~nad/repos/up-to/ && cd up-to && git checkout 2d0ab74dcede37c590a95762f80eedad5965a2fb)
printf "$PWD/delay-monad/delay-monad.agda-lib\n$PWD/equality/equality.agda-lib\n$PWD/up-to/up-to.agda-lib\n" > libraries
cd up-to
agda --ignore-interfaces --no-default-libraries --library-file=../libraries src/Bisimilarity/CCS/Examples.agda +RTS -s
```

**Comment by UlfNorell** [comment]
The problem is the old eta contraction of meta arguments from #2907. Call-by-need makes it worse since it will cause more things to be unfolded. I "fixed" this by disabling call-by-need for the `reduceAndEtaContract` call.
