### ISSUE TITLE
Record fields and constructors treat irrelevance differently

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#2992]
I'm not sure if this is a problem or not, but it struck me as odd:

```agda
_∘_ : ∀ {A : Set} {B : Set} {C : Set} →
         (B → C) → (A → B) → (A → C)
_∘_ f g = λ z → f (g z)


data ⊥ : Set where

infixr 2 _×_

record Σ (A : Set) (B : A → Set) : Set where
  constructor _,_
  field
    proj₁ : A
    proj₂ : B proj₁

open Σ public

_×_ : ∀ (A : Set) (B : Set) → Set
a × b = Σ a λ _ → b

data Dec (t : Set) : Set where
  yes : ( p :   t) → Dec t
  -- Note the irrelevant parameter!
  no  : (¬p : ∀ .(_ : t) → ⊥) → Dec t

example : ∀ {t₁ t₂ : Set} → Dec t₁ → t₂ → Dec (t₁ × t₂)
example (yes x) y = yes (x , y)
-- example (no ¬p) _ = no (¬p ∘ proj₁)
example (no ¬p) _ = no λ { (x , _) → ¬p x }
```

Alternate commenting either of the final two lines to see that they behave differently - the latter is accepted, while the former is not. Is this an intentional discrepancy? If not, is it ok to depend on the pattern matching behavior, or should I avoid it? Also, maybe or maybe not related - Agda *only* permits matching on irrelevant record constructors. It does not permit matching on irrelevant `data` constructors, even if there is only 1 constructor.

**Comment by identicalsnowflake** [comment]
Ah, no, it's not the projection that's causing the problem - it's the `∘` not being usable on functions with irrelevant args. It still feels like there's some weirdness going on, as I can't figure out any way to annotate  `∘` to make it work.

In any case, I was mistaken about the main title issue - the pattern match/projection are respecting the same rules. My bad!

**Comment by gallais** [comment]
> I can't figure out any way to annotate ∘ to make it work.

This ought to do it:

```agda
_∘_ : ∀ {A : Set} {B : Set} {C : Set} →
         (.B → C) → (A → B) → (.A → C)
_∘_ f g = λ z → f (g z)
```

**Comment by identicalsnowflake** [comment]
Huh, ya that works. I was putting the `.` on the middle `A` as well.

**Comment by gallais** [comment]
The key idea is that you're entitled to use a relevant function on an irrelevant
argument as long as the result is used in an irrelevant fashion.

**Comment by identicalsnowflake** [comment]
Ya that's how I was trying to think about it - I think I was getting tripped up on the fact that the `proj₁` is a relevant function being supplied to `∘` where it's then used in an irrelevant way.

Anyway, I managed to finally get what I originally wanted! I've been looking for a way to recompute irrelevant computations for a long time:

```agda
open import Data.Empty
open import Relation.Nullary

recompute : ∀ {t : Set} → Dec t → .t → t
recompute (yes x) _ = x
recompute (no ¬p) x with ¬-i ¬p x
  where
    ⊥-i : ∀ .(_ : ⊥) → ⊥
    ⊥-i ()
    
    ¬-i : ∀ {t : Set} → (t → ⊥) → .t → ⊥
    ¬-i f x = ⊥-i (f x)
... | ()

```

I previously thought it was impossible - I even had it as a postulate in my code!

**Comment by gallais** [comment]
Sounds like a good candidate for inclusion in the standard library (we already
have e.g. [Data.Empty.Irrelevant](https://agda.github.io/agda-stdlib/Data.Empty.Irrelevant.html)). Would you mind submitting a PR to agda-stdlib? :D

**Comment by identicalsnowflake** [comment]
Sure, I'll look into it when I get home later. I think it's best to have a `Unique t` argument on `recompute` too, since otherwise you're not actually guaranteed that what you're recomputing is equivalent to the irrelevant computation.
