### ISSUE TITLE
Quadratic (failing) instance search

### ISSUE THREAD

**Issue by LightAndLight** [agda/agda#2993]
Agda 2.5.3 and HEAD both hang on this code:

```agda
id : forall {k}{X : Set k} -> X -> X
id x = x

_o_ : forall {i j k}
  {A : Set i}{B : A -> Set j}{C : (a : A) -> B a -> Set k} ->
  (f : {a : A}(b : B a) -> C a b) ->
  (g : (a : A) -> B a) ->
  (a : A) -> C a (g a)
f o g = \ a -> f (g a)

data List (X : Set) : Set where
  [] : List X
  _,_ : X → List X → List X

data Nat : Set where
  zero : Nat
  suc : Nat → Nat

{-# BUILTIN NATURAL Nat #-}

data Vec (X : Set) : Nat -> Set where
  [] : Vec X 0
  _,_ : { n : Nat } → X → Vec X n → Vec X (suc n)

vec : forall { n X } → X → Vec X n
vec {zero} a = []
vec {suc n} a = a , vec a

vapp : forall { n S T } → Vec (S → T) n → Vec S n → Vec T n
vapp [] [] = []
vapp (x , st) (x₁ , s) = x x₁ , vapp st s

record Applicative (F : Set → Set) : Set₁ where
  infixl 2 _⊛_
  field
    pure : forall { X } → X → F X
    _⊛_ : forall { S T } → F (S → T) → F S → F T

open Applicative {{...}} public

instance
  applicativeVec : forall { n } → Applicative (λ X → Vec X n)
  applicativeVec = record { pure = vec; _⊛_ = vapp }

instance
  applicativeComp : forall {F G} → Applicative F → Applicative G → Applicative (F o G)
  applicativeComp af ag =
    record
    { pure = λ z → Applicative.pure af (Applicative.pure ag z)
    ; _⊛_ = λ z → {!!}
    }

record Traversable (T : Set → Set) : Set1 where
  field
    traverse : forall { F A B } {{ AF : Applicative F }} → (A → F B) → T A → F (T B)

open Traversable {{...}} public

instance
  traversableVec : forall {n} → Traversable (\X → Vec X n)
  traversableVec = record { traverse = vtr } where
    vtr : forall { n F A B } {{ AF : Applicative F }} → (A → F B) → Vec A n → F (Vec B n)
    vtr {{AF}} f [] = Applicative.pure AF []
    vtr {{AF}} f (x , v) =
      Applicative._⊛_ AF (Applicative._⊛_ AF (Applicative.pure AF _,_) (f x)) (vtr f v)
```

It's something to do with `applicativeComp` and instance resolution. If I don't declare it as an instance, and just leave it as a regular top-level definition, the compiler behaves normally.

**Comment by UlfNorell** [comment]
It is indeed `applicativeComp` that is the culprit. It is a candidate for any instance goal `Applicative H` (for instance by taking `F = H` and `G = id`), so we'd expect instance search to loop in this case. It should be caught by the `--instance-search-depth`, however, and indeed it is, eventually. If you lower the search depth to 100 (from the default 500) Agda fails after a few seconds with 
```
Instance search depth exhausted (max depth: 100) for candidate AF : Applicative .F
```
There's some quadratic behaviour that's causing it to take a long time to hit the search depth. I'll poke around a bit to see if it's something that can be addressed.

**Comment by LightAndLight** [comment]
@UlfNorell Is there a better way I should write such a definition? I'm working through Conor McBride's Dependently Typed Metaprogramming, which says to implement `applicativeComp : forall {F G} → Applicative F → Applicative G → Applicative (F o G)`.

Maybe I should use a type for functor composition instead of the compose function, like

```
data Compose (F : Set → Set) (G : Set → Set) (X : Set) : Set where
  MkCompose : F (G X) → Compose F G X
```

And thank you for the response.

**Comment by UlfNorell** [comment]
If you want to use it as an instance you need the data type wrapper, yes. It might still be useful to have `applicativeComp` without the `instance` though.
