### ISSUE TITLE
Internal error in Agda.TypeChecking.Rules.LHS

### ISSUE THREAD

**Issue by nad** [agda/agda#2997]
The following code triggers an internal error (`src/full/Agda/TypeChecking/Rules/LHS.hs:1270`):
```agda
record R (A B : Set) : Set where
  constructor c₁
  field
    x : A

mutual

  T : Set
  T = R D T

  data D : Set where
    c₂ : T → D

f : T → Set
f (c₁ (c₂ x)) = f x
```
This seems to be a regression.

**Comment by nad** [comment]
Bisection points to 859a80af089d381fc27539f2d442c464f76e1965: "[ new ] Big refactoring of the LHS checker".

**Comment by andreasabel** [comment]
Would it be acceptable behavior if Agda looped?
Getting safely through
```agda
T = R D T
data D : Set where c₂ : T → D
```
is in conflict with #2901, where we would need reductions in argument types of constructors in the positivity checker.
