### ISSUE TITLE
Absurd copattern

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3006]
Make the following work:
```agda
record True : Set where

triv : True
triv ()
```
And also result splitting on an empty record type.

**Comment by andreasabel** [comment]
I realized I am not familiar with the lhs checker any more, so maybe @jespercockx could implement this more quickly.  
It seems this could be handled in a similar way than the empty type check; instead have a constraint for "this type should be the trivial record type", which is checked after all the splitting has been performed for the clause.

**Comment by nad** [comment]
The notation `triv ()` looks just like an absurd *pattern*. Did you mean `triv .()` (which I think was suggested by someone else)?

I don't think `.()` is a valid dotted pattern. (But I guess there is already some overlap between dotted patterns and postfix copatterns, so perhaps this observation is irrelevant.)

**Comment by andreasabel** [comment]
`.()` would be an alternative, stating _the type of the lhs is an empty record here_.

Reusing `()` would generalize the meaning of `()` to _the type of the lhs is trivial_: And that, either because it is a function type with an empty domain or a record type with no fields.

`.()` would give a bit more information to the reader of Agda code.

**Comment by UlfNorell** [comment]
I'm not violently opposed to this extension (with the `.()` syntax), but I am also not that annoyed by having to write
```agda
triv = _
```
instead of
```agda
triv .()
```
I suppose the latter could be allowed also for the non-eta record unit type...

**Comment by andreasabel** [comment]
Maybe the main problem currently is that if you split on result for the empty record, the clause disappears altogether.  Either we have to forbid splitting on the empty result or we have to add a syntax for the empty set of projections.  I'd say the latter alternative is nicer (and more streamlined).

**Comment by andreasabel** [comment]
The bug is:
```agda
record ⊤ : Set where

triv : ⊤
triv = {!!}  -- split on result here
```
The clause disappears and we get the error:
```
Missing definition for triv
```

**Comment by gallais** [comment]
An alternative proposition: never complain about a missing definition for
a declaration if it is trivial (i.e. either the LHS telescope is absurd or
a `_` RHS is enough).

**Comment by andreasabel** [comment]
> never complain about a missing definition for a declaration if it is trivial

Not convinced.  Especially if you _read_ code, it is very ambiguous if you just see the type signature without the definition.  After all, with new-style mutual, its definition could still be given eventually, at the end of the file.  I'd say we shouldn't go down this path.

**Comment by andreasabel** [comment]
After fixing #4536 to produce rhs @record{}@, there is even less need for absurd copatterns, I suppose, than the lack of enthusiasm on this issue demonstrates.
