### ISSUE TITLE
Internal error in Parser

### ISSUE THREAD

**Issue by bafain** [agda/agda#3007]
```
$ cat Error.agda
postulate _-- : Set → Set
$ agda --version
Agda version 2.6.0-b946192
$ agda Error.agda
An internal error has occurred. Please report this as a bug.
Location of the error: build/Agda/Syntax/Parser/Parser.hs:7056
```

**Comment by nad** [comment]
The error is triggered by the `TokEOF` case in `mkName`:

https://github.com/agda/agda/blob/b9461927b33d4b93005e723033be87ac0f01d5c8/src/full/Agda/Syntax/Parser/Parser.y#L1799-L1857

**Comment by nad** [comment]
This code was introduced recently, in c6ae4d5db2819deabe3678faed6851293a0d826c.
