### ISSUE TITLE
Field of opened record does not get highlighted

### ISSUE THREAD

**Issue by bafain** [agda/agda#3010]
In the following definition of `M.f` (line 7)

```Agda
module Issue where

record R : Set₁ where field x : Set

g : Set₁

module M where f : R → Set; f r = x where open R r

g = R
```

the field `x` of the given record `r` does not get highlighted by `Agda version 2.6.0-eeafd4b` in `--latex`, `--html`, or `--interaction` mode.

Highlighting seems to work if we declare `g` where it is defined:

```Agda
module Issue' where

record R : Set₁ where field x : Set

module M where f : R → Set; f r = x where open R r

g : Set₁
g = R
```

Highlighting also seems to work if we define `f` at the top-level:

```Agda
module Issue'' where

record R : Set₁ where field x : Set

g : Set₁

f : R → Set; f r = x where open R r

g = R
```

**Comment by andreasabel** [comment]
See also #1581.

**Comment by andreasabel** [comment]
The problem also shows in the following simplification:
```agda
record R : Set₁ where
  field x : Set

g : Set₁

module M where
  f = R.x

g = R
```
The projection `R.x` is not highlighted.

**Comment by UlfNorell** [comment]
The last test case works now (for me). The test case in the OP is still broken.
