### ISSUE TITLE
Order of Copatterns determines reducibilty.

### ISSUE THREAD

**Issue by xekoukou** [agda/agda#3011]
```agda
module bl where

open import Agda.Primitive

data Context (Role : Set) : Set where

record PF : Set₁ where
  field
    ro : Set
    ctx : Context ro

open PF 

boo : PF → PF
ctx (boo pf) = ctx pf
ro (boo pf) = ro pf

-- This works.
-- ro (boo pf) = ro pf
-- ctx (boo pf) = ctx pf
```

**Comment by UlfNorell** [comment]
This is by design. Earlier clauses evaluate when type checking later clauses, but not the other way around.

**Comment by xekoukou** [comment]
The problem here is that the error msg does not give you a hint about what
is wrong.

Is there doc anywhere that tells that copatterns "should" have a specific
order?

**Comment by UlfNorell** [comment]
It does tell you `ro pf !=< ro (boo pf)` which should give you a least a little bit of a hint. The documentation doesn't say anything about the order, but pattern-matching equations are traditionally ordered top-to-bottom, so it shouldn't come as a huge surprise.
