### ISSUE TITLE
Internal Error at : "src/full/Agda/TypeChecking/Reduce/Fast.hs:1030"

### ISSUE THREAD

**Issue by xekoukou** [agda/agda#3012]
https://github.com/xekoukou/Protocol/blob/adf95dd45920a4bceb93730c638a1ac001ea6b33/Test.agda#L69

This is tested in the master agda branch.

**Comment by UlfNorell** [comment]
The problem is that I forgot to check for partial functions before throwing an internal error on incomplete copatterns.

Here's a smaller test case:

```agda
module _ where

record _×_ (A B : Set) : Set where
  field
    fst : A
    snd : B

open _×_

partial : ∀ {A B} → A → A × B
partial x .fst = x

open import Agda.Builtin.Equality

theorem : ∀ {A} (x : A) → partial x .snd ≡ x
theorem x = refl
```
