### ISSUE TITLE
Windows and GHC 8.4.1: Missing test

### ISSUE THREAD

**Issue by asr** [agda/agda#3016]
Could someone test GHC 8.4.1 on Windows, please.

Note that the version of the  `Win32` library shipped with GHC 8.4.1 is [ backwards incompatible](https://downloads.haskell.org/~ghc/8.4.1/docs/html/users_guide/8.4.1-notes.html#win32).

**Comment by asr** [comment]
If someone fix the issue, please also remove from the CHANGELOG the line:

```
* TODO: Missing test of GHC 8.4.1 on Windows.
```

**Comment by UlfNorell** [comment]
I thought we only did this for releases. What's the reason for the extra Windows concerns?

The backwards incompatible changes to `Win32` do not affect any functions we are using (list here: https://github.com/haskell/win32/commit/73a7b785c0683f0a3354ddf54d8d5eeeca909370). We are using `findFirstFile`, `findClose`, and `getFindDataFileName`.

**Comment by UlfNorell** [comment]
Anyway, it builds fine and seems to run without problems.

**Comment by asr** [comment]
> What's the reason for the extra Windows concerns?

There is no extra *Windows* concerns.

> Anyway, it builds fine and seems to run without problems.

I'm surprised you didn't change the `Win32` upper bound in `Agda.cabal` when closing the issue. Could you build using the current `Win32` bounds, that is, using

```
  if os(windows)
    build-depends:  Win32 >= 2.3.1.0 && < 2.6
```

?

**Comment by UlfNorell** [comment]
No, I did bump the bound. Just forgot to also do it on the machine where I can actually push stuff. One second...
