### ISSUE TITLE
How is Word64 compiled to native arithmetic?

### ISSUE THREAD

**Issue by VictorTaelin** [agda/agda#3018]
From the 2.5.4 CHANGELOG,

> Basic arithmetic operations can be defined on Word64 by converting to natural numbers, peforming the corresponding operation, and then converting back. The compiler will optimise these to use 64-bit arithmetic. For instance,
>
>     addWord : Word64 → Word64 → Word64
>     addWord a b = primWord64FromNat (primWord64ToNat a + primWord64ToNat b)
>     
>     subWord : Word64 → Word64 → Word64
>     subWord a b = primWord64FromNat (primWord64ToNat a + 18446744073709551616 - primWord64ToNat b)
> 
> These compiles (in the GHC backend) to addition and subtraction on Data.Word.Word64.

That doesn't make sense to me, how it knows what function to compile to? 

I'm specifically interested in implementing a few hash functions such as Keccak on Agda. Having a full set of 64-bit arithmetic (including shifts, xor) is necessary. Could someone point me the best way to have those on Agda right now?

**Comment by UlfNorell** [comment]
Please use the [mailing list](https://lists.chalmers.se/mailman/listinfo/agda) for questions like this. The issue tracker is for bug reports and feature requests.

> That doesn't make sense to me, how it knows what function to compile to?

I'm not sure what you mean. `Nat`, `_+_`, `Word64`, `primWord64FromNat`, and `primWord64ToNat` are all primitives that the compiler knows about so very little magic is needed to optimise those two functions.

> Having a full set of 64-bit arithmetic (including shifts, xor) is necessary.

You can use the [FFI](http://agda.readthedocs.io/en/latest/language/foreign-function-interface.html) to access the Haskell bit-arithmetic functions, but these won't reduce at compile time.

If you are very very careful, you *can* give corresponding Agda definitions, but there are no checks that the Agda and Haskell definitions agree. For instance:

```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.FromNat
open import Agda.Builtin.Word renaming (primWord64ToNat to toNat)
open import Agda.Builtin.Unit
open import Agda.Builtin.IO

instance
  NumWord : Number Word64
  Number.Constraint NumWord _ = ⊤
  fromNat ⦃ NumWord ⦄ n = primWord64FromNat n

mulWord : Word64 → Word64 → Word64
mulWord a b = fromNat (toNat a * toNat b)

_^_ : Word64 → Nat → Word64
a ^ zero  = 1
a ^ suc n = mulWord a (a ^ n)

_bsl_ : Word64 → Word64 → Word64
a bsl b = mulWord a (2 ^ toNat b) -- Agda specification

{-# FOREIGN GHC import Data.Bits #-}
-- Actual run-time implementation. If this doesn't match the specification all bets are off.
{-# COMPILE GHC _bsl_ = \ a b -> shiftL a (fromIntegral b) #-}

postulate
  print : Word64 → IO ⊤

{-# COMPILE GHC print = print #-}

main : IO ⊤
main = print (1 bsl 32)
```

**Comment by VictorTaelin** [comment]
Oh, awkwardly, I interpreted as if I had to define an addition function like:

```haskell
add : Nat -> Nat -> Nat
add zero    m = m
add (suc n) m = suc (add n m)
````

And then `fromNat (add (toNat a) (toNat b))` would magically compile to a native representation. I now understand what you meant. Sorry for opening an issue, and thanks for the reply and for linking the mailing list.
