### ISSUE TITLE
Eta failure for record meta with irrelevant fields

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#3031]
This may or may not be intentional, but there has been a recent (within the past 2 weeks) change to inference:

```agda
open import Agda.Builtin.Nat renaming (Nat to ℕ) hiding (_+_)
import Agda.Builtin.Nat as N
open import Agda.Builtin.TrustMe
open import Agda.Builtin.Equality renaming (_≡_ to _≡≡_)


record Σ (A : Set) (B : A → Set) : Set where
  constructor _,_
  field
    proj₁ : A
    proj₂ : B proj₁

open Σ public

_×_ : ∀ (A : Set) (B : Set) → Set
a × b = Σ a λ _ → b

∃ : ∀ {A : Set} → (A → Set) → Set
∃ = Σ _

data ⊥ : Set where

record Fin (n : ℕ) : Set where
  field
    m : ℕ
    .p : ∃ λ k → (ℕ.suc k N.+ m) ≡≡ n


apply2 : ∀ {ℓ₁ ℓ₂} {t₁ : Set ℓ₁} {t₂ : Set ℓ₂} {a b : t₁} → (f : t₁ → t₂) → a ≡≡ b → f a ≡≡ f b
apply2 f refl = refl


private
  lem : ∀ m → .(∃ λ x → (suc (x N.+ m) ≡≡ 0)) → ⊥
  lem _ (_ , ())

pred : ℕ → ℕ
pred zero = 0
pred (suc n) = n

infixl 60 _+_
_+_ : ∀ {m n} → Fin m → Fin n → Fin (pred (m N.+ n))
_+_ {m} {n} record { m = a ; p = c₁ , p₁ } record { m = b ; p = c₂ , p₂ } = record {
    m = a N.+ b
  ; p = (c₁ N.+ c₂) , primTrustMe
  }

S : ∀ {n} → Fin n → Fin (suc n)
S = _+_ record { m = 1 ; p = zero , refl }


to : ∀ {n} → Fin n → Fin n
to record { m = zero ; p = p } = record { m = zero ; p = p }
to {zero} record { m = (suc m) ; p = p } with lem (suc m) p
... | ()
to {suc n} record { m = (suc m) ; p = (k , p) } = S (to record { m = m ; p = k , primTrustMe })

from = to

l1 : ∀ {n} (x : Fin n) → S (from x) ≡≡ from (S x)
l1 {zero} record { m = m ; p = p } with lem m p
... | ()
l1 {suc n} record { m = zero ; p = p } = refl
l1 {suc n} record { m = (suc m) ; p = k , p } = apply2 S (l1 record { m = m ; p = k , primTrustMe })

iso : ∀ {n} → (x : Fin n) → from (to x) ≡≡ x
iso {zero} record { m = m ; p = p } with lem m p
... | ()
iso {suc n} record { m = zero ; p = p } = refl
iso {suc n} record { m = (suc m) ; p = p@(k , _) } =
  let
    w : Fin n
    w = record { m = m ; p = k , primTrustMe }
    v : S (from (to w)) ≡≡ S w
    v = apply2 S (iso w)
  in
  {!!}
```

At commit 23ef599 (end of March), this is accepted, but currently, it shows some yellow inference problem in `apply2 S (iso w)`.

**Comment by UlfNorell** [comment]
It's the implicit `b` that doesn't get solved (should solve to `w`).

Note that this works(!):

```agda
    v = apply2 {b = record{ m = _; p = _ }} S (iso w)
```

What's strange is that there are no constraints on the unsolved meta, and there really should be (it has to be `w`).

**Comment by UlfNorell** [comment]
The problem seems to be that occurs check fails trying to instantiate the meta to `record{ m = m; p = k , primTrustMe }`. The reason is that the meta (`_119`) is not allowed to depend on `k`, which I believe is because `k` is irrelevant and `_119` was not created in an irrelevant context. This is why eta expanding the underscore makes the problem go away.

Anyone want to do a bisect to figure out when the problem was introduced (@nad)?

**Comment by nad** [comment]
The problem was introduced by you in e49d1ca276e5adbf2eb9f6cd33926b786cef78f7: "compare target types first when checking non-dependent applications".

**Comment by UlfNorell** [comment]
That's both unsurprising and unhelpful. That commit changes the order in which we check constraints, which in this particular case triggers the problem. I'll see if I can construct an example that's more robust against reordering of constraints...

**Comment by UlfNorell** [comment]
Here's a version that fails as far back as I could test (`2.4.0`):

```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Equality

record Fin (n : Nat) : Set where
  constructor mkFin
  field
    m  : Nat
    .p : Nat

cong : {A B : Set} {a b : A} (f : A → B) → a ≡ b → f a ≡ f b
cong f refl = refl

S : ∀ {n} → Fin n → Fin (suc n)
S (mkFin a k) = mkFin (suc a) (suc k)

postulate
  to   : ∀ {n} → Fin n → Fin n
  idem : ∀ {n} → (x : Fin n) → to (to x) ≡ x

module _ (n m : Nat) .(k : Nat) where

  w : Fin n
  w = mkFin m k

  mutual
    X : Fin n
    X = _

    -- Works on =< 2.5.3 if removing this:
    constr : S w ≡ S X
    constr = refl

    fails-to-solve-X : S (to (to w)) ≡ S w
    fails-to-solve-X = cong {b = X} S (idem w)

  works : S (to (to w)) ≡ S w
  works = cong {b = mkFin _ _} S (idem w)
```

I guess this is the point where we start up the debate over the semantics of the `regression` label again...

**Comment by UlfNorell** [comment]
Further simplified:
```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Equality

record Fin : Set where
  constructor mkFin
  field
    m  : Nat
    .p : Nat

module _ (m : Nat) .(k : Nat) where

  w : Fin
  w = mkFin m k

  mutual

    X : Fin
    X = _

    -- Works if removing this
    constr₁ : Fin.m X ≡ m
    constr₁ = refl

    constr₂ : X ≡ w
    constr₂ = refl
```
The problem seems to be that the eta-expansion that happens when we solve `constr₁` does not take into account that the second argument of `mkFin` is irrelevant. Manual eta-expansion results in

```
_p : (n m k : Nat) → Nat
```
for the second component, but the automatic eta-expansion produces
```
_p : (n m : Nat) .(k : Nat) → Nat
```

**Comment by UlfNorell** [comment]
I fixed this by applying the relevance to more things when creating metas for a telescope, but it feels like we should try to get rid of the `new*MetaCtx` functions and only create metas in the current context. I haven't checked if there are any cases where we actually use a different context.

Review request: @andreasabel.
