### ISSUE TITLE
spurious meta in dot pattern

### ISSUE THREAD

**Issue by sattlerc** [agda/agda#3032]
Tested on master.

```agda
postulate
  A : Set
  B : Set
  t : B

data C : (b : B) → Set

foo : (b : B) → C b → B

data C where
  c : (x : C t) → C (foo t x)

foo b x = {!x!}
```

Case splitting in the hole produces
```
foo .(?0 t x) (c x) = ?
```
and reports "Not in scope: ?0".

Note that the definition type checks if the dot pattern is replaced by an underscore, or more specifically `foo t x`.

**Comment by andreasabel** [comment]
Well, you are doing nasty things here.  The type of c is simplified by Agda to
```
  c : (x : C t) -> C (?0 t x)
```
(expanding the preliminary definition of foo) and if you split the telescope
```
  (b : B) (x : C b)
```
you quite logically get what Agda prints now.  The tragedy is of course that the meta variable `?0` gets destroyed by the interaction, and Agda does not take notice of this.

Would you rather expect `foo t x` in the dot pattern?  What type theory would account for a pattern matching where the function itself appears in one of its dot patterns?!  Frankly, I am not sure what this is supposed to mean.

**Comment by andreasabel** [comment]
Interestingly, Agda actually finds the termination problem in this variant:
```agda
postulate
  A : Set
  B : Set
  t : B

mutual

  data C : (b : B) → Set where
    c : (x : C t) → C (foo t bar)

  postulate
    bar : C t

  foo : (b : B) → C b → B
  foo y (c x) = y

-- Should not termination check.
-- y is actually "foo t bar" here, a potentially non-terminating recursive call.
```
(Added as `Fail/Issue3032-termination` to testsuite.)

**Comment by sattlerc** [comment]
> Would you rather expect foo t x in the dot pattern? What type theory would account for a pattern matching where the function itself appears in one of its dot patterns?! Frankly, I am not sure what this is supposed to mean.

Such situations arise quite naturally in inductive-recursive definitions. What is weird about a function itself appearing in its dot pattern? I thought dot patterns are arbitrary expressions forced by other patterns.

The above example came from reducing the (well-founded) example of defining normal forms and neutral terms mutually with their conversion functions to terms for a type theory with dependent sums, internally to presheaves over renamings:
```agda
postulate
  Ty : Set
  Tm Var : Ty → Set
  tm-var : {A : Ty} → Var A → Tm A

  subst-Ty : {A : Ty} (B : Var A → Ty) → (Tm A → Ty)

  Σ-Form : (A : Ty) (B : Var A → Ty) → Ty
  Σ-fst : {A : Ty} {B : Var A → Ty} (t : Tm (Σ-Form A B)) → Tm A
  Σ-snd : {A : Ty} {B : Var A → Ty} (t : Tm (Σ-Form A B)) → Tm (subst-Ty B (Σ-fst t))

data NF : Ty → Set
data NE : Ty → Set

tm-nf : {A : Ty} → NF A → Tm A
tm-ne : {A : Ty} → NE A → Tm A

data NF where
  nf-ne : {A : Ty} → NE A → NF A

data NE where
  ne-var : {A : Ty} (v : Var A) → NE A
  ne-fst : {A : Ty} {B : Var A → Ty} (n : NE (Σ-Form A B)) → NE A
  ne-snd : {A : Ty} {B : Var A → Ty} (n : NE (Σ-Form A B)) → NE (subst-Ty B (tm-ne (ne-fst n)))

tm-nf {A} (nf-ne x) = tm-ne x

tm-ne {.A} (ne-var {A} v) = tm-var v
tm-ne {.A} (ne-fst {A} {B} t) = Σ-fst (tm-ne t)
tm-ne {.(subst-Ty B (tm-ne (ne-fst t)))} (ne-snd {A} {B} t) = Σ-snd (tm-ne t)
```

The dot pattern in tm-ne seems perfectly natural to me. But when you just write
```agda
tm-ne {A} t = {!t!}
```
and ask Agda to split on t, one gets the invalid code
```agda
tm-ne {A} (ne-var v) = ?
tm-ne {A} (ne-fst t) = ?
tm-ne {.(subst-Ty _ (?0 (ne-fst t)))} (ne-snd t) = ?
```
as in the reduced example above.

> The tragedy is of course that the meta variable ?0 gets destroyed by the interaction, and Agda does not take notice of this.

Is that intended behaviour? It seems like an interaction bug.

**Comment by UlfNorell** [comment]
A reasonable thing to do would be to leave the variable as it is if the dot pattern contains weird stuff like interaction points or out-of-scope names.

**Comment by jespercockx** [comment]
Or we could just replace interaction points with an underscore, as we already do for out-of-scope names.
