### ISSUE TITLE
Giving and solving don't insert parenthesis for applications in dot pattern

### ISSUE THREAD

**Issue by sattlerc** [agda/agda#3033]
Probably known or duplicate of existing issue. Tested on master.

```agda
postulate
  A : Set
  B : Set
  a : A
  f : A → B

data C : B → Set where
  c : C (f a)

foo : (b : B) → C b → Set
foo .{!f a!} c = {!!}
```

Giving `f a` in or solving the first hole produces
```agda
foo .f a c = {!!}
```
failing to insert parentheses around the dot pattern.

**Comment by andreasabel** [comment]
Very low hanging fruit, when you know where to look: in `ConcreteToAbstract`, going inside dot patterns needs to enter `DotPatternCtx`.
