### ISSUE TITLE
Spurious version number v2.5.2.20170816 in the doc

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3035]
On https://agda.readthedocs.io when clicking on v2.5.3 at the bottom left in order to change the version of the doc, there is an option of looking at version v2.5.2.20170816 (in addition to v2.5.2, v2.5.3 and latest).
I guess this is not on purpose and that it should be removed.

**Comment by andreasabel** [comment]
Thanks for reporting!  I removed it.

**Comment by asr** [comment]
And I updated the releases procedures for avoiding the same issue in the future. Thanks!
