### ISSUE TITLE
Internal error in src/full/Agda/TypeChecking/Substitute/Class.hs:209

### ISSUE THREAD

**Issue by jamestmartin** [agda/agda#3044]
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Substitute/Class.hs:209

Agda version 2.5.3 via Cabal, emacs compiled agda-mode from the same source.

Minimum code required to reproduce:
```agda
    module MyModule where

    open import Agda.Primitive using (_⊔_ ; Level ; lsuc)

    record Unit {U : Level} : Set U where
    -- error still occurs with no constructors or fields in these types
      constructor unit

    record _×_ {U V : Level} (A : Set U) (B : Set V) : Set (U ⊔ V) where
      constructor _,,_
      field
        x : A
        y : B

    infixr 25 _×_

    data _⇔_ {U V : Level} : (A : Set U) → (B : Set V) → Set (U ⊔ V) where
      unitIL : {A : Set U} → A ⇔ A × Unit
```

**Comment by UlfNorell** [comment]
This is fixed on current `stable-2.5`.

**Comment by asr** [comment]
@UlfNorell, which was the original issue?

**Comment by UlfNorell** [comment]
I don't know. I guess you could do a bisect to find out.

**Comment by asr** [comment]
I asked because you labelled the issue as `status: duplicate`. Anyway, I added a test case  and removed that label.
