### ISSUE TITLE
do-notation causes parse errors in subsequent where clauses

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#3046]
```agda
data ⊤ : Set where
  tt : ⊤

data Identity (t : Set) : Set where
  MkIdentity : t → Identity t

example : Identity ⊤
example = do
  MkIdentity tt

  where
    x : ⊤
    x = tt

```

If you comment out the `where` block or simply remove the word `do`, the above is accepted, but together they cause a parse error.

**Comment by UlfNorell** [comment]
We have the same problem for `let`:

```agda
foo : ⊤
foo = let x = tt
          y = tt
          in tt   -- Parse error
```

The problem is that the parser doesn't accept trailing semis in layout blocks.

**Comment by jespercockx** [comment]
Maybe it's just me but this seems like it's working as intended, no? It seems like a reasonable requirement that you should *end* the block of `do`/`let` statements by decreasing the indentation; otherwise one might think the `where`/`in` is just another statement in the block. I'm afraid that allowing this would lead to less readable code...

**Comment by UlfNorell** [comment]
In the `let` example you'd be hard-pressed to argue that adding *or* removing a space is fine, but having the `in` on the same column is not.

In the `do` case I can think of a few arguments for allowing it:
- it's valid Haskell
- the error message (parse error) is terrible
- it makes it possible to add a `where` without reindenting the entire do-block

**Comment by jespercockx** [comment]
In the `let` example I would argue that the `in` should be at the same level as the `let` it corresponds to, so just adding or removing one space *wouldn't* be fine. Are you saying you want to allow code like
```
foo : ⊤
foo = let x = tt
          y = tt
         in tt
```
or
```
foo : ⊤
foo = let x = tt
          y = tt
           in tt
```
?

For the `do` example I didn't know this was valid Haskell, I *do* re-indent a do-block when I add a `where` (or more often indent do-blocks with 4 spaces to leave space for a 2-space where block). This can sometimes be annoying, but OTOH I still think it's important to be able to view the *structure* of the code at a glance, which you just made harder. Also, if an error message is terrible then the proper response is to improve the error message, not make the error go away!

Maybe we should collect more people's opinions before we commit to this change?

**Comment by UlfNorell** [comment]
> Are you saying you want to allow code like...

I'm saying we *do* allow that code. We also allow
```agda
foo : ⊤
foo = let x = tt
          y = tt in tt
```
There would be no way to enforce the `in` on the same column as the `let` since the `let` is not in a layout block.

**Comment by UlfNorell** [comment]
> This can sometimes be annoying, but OTOH I still think it's important to be able to view the structure of the code at a glance, which you just made harder.

Not *that* much harder, and not enough to warrant a deviation from Haskell, in my opinion.

> Maybe we should collect more people's opinions before we commit to this change?

Yes, what do you think, Mr NondecreasingIndentation (@andreasabel)? :P

**Comment by WolframKahl** [comment]
>  I do re-indent a do-block when I add a where (or more often indent do-blocks with 4 spaces to leave space for a 2-space where block). 

I follow the same practice for readability reasons, but don't see the need to enforce this everywhere.

Being close to the Haskell rules is certainly an advantage.

**Comment by nad** [comment]
I've found it annoying that you can't (couldn't?) write the following (which is valid Haskell code):
```agda
f = do
  bla
  where
  ...
```
Syntax highlighting makes it easy to spot the `where` keyword.

I do think we should have a proper discussion about making Agda Pfenning-safe (#2465).

**Comment by UlfNorell** [comment]
> I've found it annoying that you can't (couldn't?) write the following (which is valid Haskell code):
> 
> ```agda
> f = do
>   bla
>   where
>   ...
> ```
That is precisely this issue. You can now write this.

**Comment by andreasabel** [comment]
Mr. NondecreasingIndentation mostly cares for code like
```haskell
  if bar then foo else do
  if baz then boo else do
  bla
```
Haskell also allows this:
```haskell
bla :: IO Int
bla = do
  return x
  where
  x = 1
```
I am +1 on this proposal.

**Comment by UlfNorell** [comment]
> Haskell also allows this ...

Yes, this is precisely the issue at hand.
