### ISSUE TITLE
Positivity unsoundness

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#3049]
You can trick the positivity checker by hiding function types under pattern matching. The problem seems to be that the positivity analysis relies on eta-expanding function clauses, but in the presence of pattern matching *types* this is not always possible:

Test case adapted from #121:

```agda
open import Agda.Builtin.Bool

T : Bool → Set₁
T true  = Set → Set
T false = Set

bad : ∀ b → T b
bad true A = A → A   -- negative A
bad false  = Bool

F : Bool → ∀ b → T b
F true  b       = bad b  -- is not (can't be) eta-expanded
F false true  A = A
F false false   = Bool

data D : Set where
  nop : (b : Bool) → F b true D → D

data ⊥ : Set where

d : D
d = nop true (λ x → x)

!d : D → ⊥
!d (nop true  f) = !d (f d)
!d (nop false x) = !d x

loop : ⊥
loop = !d d
```

**Comment by jespercockx** [comment]
The conservative solution would be to be pessimistic instead of optimistic by default, so if we don't know the polarity of `bad` we should assume it is bad.

The principled solution would be to track positivity information at the type level, so we don't have to look inside pattern matching functions in the first place! But I'm afraid that this would make things unworkable in the absence of subtyping: we really want the type of *positive* functions to be a subtype of the *arbitrary* functions.

**Comment by UlfNorell** [comment]
> to be pessimistic instead of optimistic by default

Yes, it's a bit strange that we aren't already.

**Comment by andreasabel** [comment]
Here is a version that can be tried with Agda going back to at least 2.3.2:
```agda
module Issue3049 where

data Bool : Set where
  true false : Bool

T : Bool → Set₁
T true  = Set → Set
T false = Set

bad : ∀ b → T b
bad true   = λ A → A → A   -- negative A
bad false  = Bool

F : Bool → ∀ b → T b
F true  b       = bad b  -- is not (can't be) eta-expanded
F false true    = λ A → A
F false false   = Bool

data D : Set where
  nop : (b : Bool) → F b true D → D

data ⊥ : Set where

d : D
d = nop true (λ x → x)

!d : D → ⊥
!d (nop true  f) = !d (f d)
!d (nop false x) = !d x

loop : ⊥
loop = !d d
```
It is first accepted by Agda 2.5.3.

**Comment by UlfNorell** [comment]
Interesting. Now I'm curious to see the result of a bisect...

**Comment by andreasabel** [comment]
Hang tight! It is running...

**Comment by andreasabel** [comment]
agda-bisect blames commit 3c2c1972ad7b985f0cdbde538c5d530d204314aa

Date:   Thu Jan 5 22:46:10 2017 -0500
[ refactoring ] Eta-expansion of clauses.
After commit ab655419f2d9e0e35b153b0ab0e6cc4fb4cf12e5 there were two functions which eta-expanded one clause. I removed the incomplete one (according to the source code documentation).

Looks like a case of a refactoring gone wrong...

**Comment by UlfNorell** [comment]
Ooh, I think I see what went wrong! Before that commit, all clauses were eta expanded to the same arity, but after each clause is eta expanded individually. That means that the `F false true = λ A → A` clause contributes a positive occurrence of the third argument which I suspect gets counted as the only occurrence, since none of the other clauses have a third argument.

**Comment by UlfNorell** [comment]
Reverting 3c2c197 is not enough though. That makes the modified test case go through, where all clauses have the same arity, but the original test case with varying arities still fails (and has failed since at least `2.4.0`).

**Comment by andreasabel** [comment]
This can be easily fixed by being pessimistic about polarity of arguments beyond the formal function arity, which is the length of the initial telescope of the function type.

**Comment by andreasabel** [comment]
Why was this labeled "regression on master"?
