### ISSUE TITLE
A module can export two definitions with the same name

### ISSUE THREAD

**Issue by nad** [agda/agda#3057]
I think we should disallow the following code:
```agda
module _ where

module M where

  postulate
    A B : Set

open M public renaming (A to B)
```
Note that the top-level module contains two definitions named `B`.

The fact that Agda currently accepts code like this led to a bug in the standard library (https://github.com/agda/agda-stdlib/commit/e78e6ae028d3cc8a6416c4d30c1fa133d897cb5b).

**Comment by andreasabel** [comment]
If you try to use `B`, you get an ambiguous name error.

**Comment by nad** [comment]
> If you try to use `B`, you get an ambiguous name error.

The problem with the code above is that this error is raised too late: The person implementing this module might not notice that two instances of `B` are exported, and this could lead to problems for users of the module.
