### ISSUE TITLE
C-c C-c produces invalid pattern

### ISSUE THREAD

**Issue by gallais** [agda/agda#3058]
Looks like a de Bruijn error. Using the following module:

```agda
open import Agda.Builtin.Nat

data View : Nat → Set where
  IsZero : View zero
  IsSuc  : ∀ k → View (suc k)

view : ∀ k → View k
view zero    = IsZero
view (suc k) = IsSuc k

data ViewView : ∀ {k} → View k → Set where
  IsIsSuc : ∀ k → ViewView (IsSuc k)

viewView : ∀ k l → ViewView (view k) → ViewView (view l) → Nat
viewView k l with view k | view l
... | v₁ | v₂ = {!!}
```

`C-c C-c  v₁ v₂ RET` produces

```agda
(...)
viewView .(suc k₁) .(suc k) | IsSuc k | IsSuc k₁ = ?
```

when it should produce

```agda
viewView .(suc k) .(suc k₁) | IsSuc k | IsSuc k₁ = ?
```

**Comment by nad** [comment]
I get the latter output with a recent version (fd1e87bf45cf819ac821a27ab4e0a022d806c1aa).

**Comment by gallais** [comment]
My bad! I pulled from `master` and recompiled to test with the current dev version before
filing the issue but the name of the executable built is `agda` and not `agda-2.6.0` which
is what I was using for my tests.

Is there a way to always get `make` to build the executable with the version / branch name
suffixed? It'd be convenient when you have a bunch of different versions at the same time.

**Comment by nad** [comment]
> Is there a way to always get `make` to build the executable with the version / branch name
suffixed?

Untested:
```
make CABAL_OPTS=--program-suffix=-whatever install-bin
```
