### ISSUE TITLE
Missing installation instructions for stack

### ISSUE THREAD

**Issue by gallais** [agda/agda#3066]
I was asked whether one can use `stack` to install Agda and couldn't answer much more
than "there's a bunch of `stack-*.yaml` files on the repo and the builds are tested on travis").

It'd be nice to have a section in the manual, probably a subsection of "Installation of the
Development Version": https://agda.readthedocs.io/en/latest/getting-started/installation.html

**Comment by banacorn** [comment]
Hopes that https://github.com/agda/agda/pull/3181 could remedy the pain a bit

**Comment by hvr** [comment]
@gallais why can't you use `cabal` to install Agda?

**Comment by UlfNorell** [comment]
Using cabal is the (currently) recommended method to install Agda. This issue is about how to install using stack.

**Comment by hvr** [comment]
Sure, but what problem is stack solving here? This ticket has been referenced by #3181 which claims there was a problem that stack would solve.

**Comment by UlfNorell** [comment]
I don't think this is the right forum for asking why anyone would ever want to use stack, and as I'm not a stack user myself I don't feel qualified to answer it. Regardless of their reasons, a lot of people *are* using stack, and I can't see any reasons why we shouldn't support that.

**Comment by hvr** [comment]
That wasn't what I was asking for; I rather asked what problems were encountered with `cabal` as @banacorn put this into relation w/ #3181

**Comment by banacorn** [comment]
@hvr I'm trying to reproduce the problem I encountered with `cabal`, perhaps I should open a new issue so that it can be better addressed.

**Comment by hvr** [comment]
@banacorn thanks, that would be very helpful; if you were encountering it, it's likely other people would too, so addressing that one would certainly be desirable for the benefit of everyone.

**Comment by banacorn** [comment]
#3182
Hope that this would be helpful.

**Comment by jespercockx** [comment]
It seems this was fixed in af7c0b3be9e6631c50ab1cba070ea06a88e02f07
