### ISSUE TITLE
Predicative version of the Prop universe: Missing CHANGELOG entry and documentation

### ISSUE THREAD

**Issue by asr** [agda/agda#3070]
The predicate version of `Prop` was introduce by 7dda192 but without documentation.
@jespercockx also list the new `--enable-prop` option [here](http://agda.readthedocs.io/en/latest/tools/command-line-options.html), please.

Since I guess this new feature won't be include in 2.5.4, I just added the 2.5.5 header to the CHANGELOG.

**Comment by ice1000** [comment]
I'm very looking forward to this.

**Comment by jespercockx** [comment]
It's done. You can find the documentation here: https://github.com/agda/agda/blob/master/doc/user-manual/language/prop.lagda.rst
