### ISSUE TITLE
invalid section printing

### ISSUE THREAD

**Issue by sattlerc** [agda/agda#3072]
On master.

```agda
postulate
  S : Set
  id : S
  comp : S → S → S

module C where
  _∘_ = comp

postulate
  R : (S → S) → Set
  T : R (C._∘ id) → Set

mutual
  postulate
    bar : _

  foo : Set
  foo = T bar
```

If you print (or interactively solve) the type of bar, you will get `R (_C.∘ id)` instead of `R (C._∘ id)`.

**Comment by andreasabel** [comment]
Agda 2.5.3 prints correctly (but uglyly) `R (λ section → section C.∘ id)`.

Section recovering during printing was introduced in #2270.
