### ISSUE TITLE
Error building with GHC 7.10.2: Missing transformers library

### ISSUE THREAD

**Issue by asr** [agda/agda#3078]
@sergv reports the following error on the user mailing list when install 2.5.4 RC 1:

> the above command under  ghc-7.10.2, Debian Linux
> leads to an error which report ends with
>    "... perhaps you need to add `transformers' to  build-depends in
>    your .cabal file."

The problem is caused by the following lines in Agda.cabal:

```agda
  if impl(ghc >= 7.10.3) && impl(ghc < 8.0)
    build-depends: transformers == 0.4.2.0
```

**Comment by nad** [comment]
> `ghc >= 7.10.3`

Perhaps the bug can be fixed by dropping "`.3`".

**Comment by sergv** [comment]
It seems a different person actually reported the issue: Sergei Meshveliani <mechvel at botik.ru>.

**Comment by asr** [comment]
Oops, sorry. CC'ing @mechvel.
