### ISSUE TITLE
Emacs mode regression: a ? inserted before existing hole hijacks its interaction point

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3082]
Since I switched to the newest emacs mode on 2.5.4 (roughly 10 days old), I observe the following new buggy behavior.
Load the following file:
```agda
goal : Set
goal = {! !}
```
This marks the whole as interaction point 0.
Now insert
```
test : Set
test = {! !}
```
/before/ `goal`.  Without reloading, the interaction point 0 immediately jumps to this hole.  

This is very confusing behavior and seems to be triggered by instantaneous rehighlighting as I type.

**Comment by andreasabel** [comment]
This is probably connected to the new feature #2794.
  
I also observe now a more frequent trip-up of Agda such that I have to restart it. Could this be due to a race of the "idle highlighter" running and an interactive command I issue to Agda? 

I found the new parameter `Agda2 Highlight After Inactivity Interval`.  Maybe setting this to `0` could be make to deactivate the "idle highlighting" feature?

**Comment by nad** [comment]
> This is probably connected to the new feature #2794.

Yes, and fixing it should be easy.

> I also observe now a more frequent trip-up of Agda such that I have to restart it. Could this be due to a race of the "idle highlighter" running and an interactive command I issue to Agda?

If you issue a command while highlighting is in progress, then I imagine that you could get the `Another command is currently in progress` error message. I guess it wouldn't be too hard to fix this.

> I found the new parameter `Agda2 Highlight After Inactivity Interval`.  Maybe setting this to `0` could be make to deactivate the "idle highlighting" feature?

The customization UI includes an option to turn off this feature.

**Comment by nad** [comment]
The problem described in the OP is a (rather severe) instance of #2306.

**Comment by nad** [comment]
> If you issue a command while highlighting is in progress, then I imagine that you could get the `Another command is currently in progress` error message. I guess it wouldn't be too hard to fix this.

I'm reluctant to make the Emacs mode even more complicated. If you get this error message because highlighting is in progress, then you can simply issue the command again.

**Comment by WolframKahl** [comment]
> [...], then you can simply issue the command again.

I would like to attract attention to the fact that, although it may be simple to issue a command again, in many cases I find it highly unattractive to do so since it will involve a wait of several minutes...

**Comment by UlfNorell** [comment]
In this case it tells you another command is in progress before starting the several minute long command, so you can issue it again without waiting. (I hope you aren't saying that the background highlighting takes several minutes...)

**Comment by andreasabel** [comment]
Agda's suggestion is `you might want to restart Agda`.  Maybe this should be refined to `you might want to issue your command again or restart Agda`.

**Comment by nad** [comment]
The full text of the error message: `Another command is currently in progress (if a command has been aborted you may want to restart Agda)`.

**Comment by andreasabel** [comment]
Reading with my brain 1 (association-making) I pick out `restart Agda` as the only suggestion for solving this problem.  The message should also suggest `try again`.
