### ISSUE TITLE
Wrong hiding in module application

### ISSUE THREAD

**Issue by nad** [agda/agda#3083]
Some of my code that worked earlier this year has stopped working. When trying to create a small test case I ended up with the following code:
```agda
open import Agda.Builtin.Reflection

record R₁ : Set₁ where
  field
    A : Set

postulate
  B : Set
  P : B → Set

record R₂ (A : Set) : Set where
  field
    f : A → B

open R₂ ⦃ … ⦄ public

module M₁ (r₁ : R₁) where

  record R₃ (A : Set) : Set where
    postulate
      r₂ : R₂ A

  open R₃ ⦃ … ⦄ public

module M₂ (r₁ : R₁) where

  open R₁ r₁
  open M₁ r₁

  postulate
    r₃-A : R₃ A

  instance

    r₂-A : R₂ A
    r₂-A = R₃.r₂ r₃-A

postulate
  r₁ : R₁

open R₁ r₁
open M₂ r₁

macro

  m : Term → TC _
  m goal =
    bindTC (inferType goal) λ goal-type →
    bindTC (reduce goal-type) λ _ →
    returnTC _

g : (x : A) → P (f x)
g _ = m
```
This code is rejected. Error message:
```
R₁ !=< M₁.R₃ (_r₁_33 .x) (_A_34 .x) of type Set₁
when checking that the expression r₁ has type
M₁.R₃ (_r₁_33 .x) (_A_34 .x)
```

This is not an ideal test case, because the code is not accepted by any version of Agda that I have tried. Furthermore I am not sure if the code should be accepted or not, but the fact that the error disappears if I remove the line with `reduce` from the macro suggests to me that something is not quite right. I've included the 2.5.4 milestone, because I hope that the regression that broke my code is a combination of this bug (if it is a bug) and some other change that led to this bug being triggered.

**Comment by UlfNorell** [comment]
As before, the problem isn't with reflection. If you ask for the type of `g` you get
```agda
(x : R₁.A r₁) → P (R₂.f (M₁.R₃.r₂ r₁ {R₁.A r₁} _) x)
```
Type checking that gives exactly the error above. I haven't analysed further but it seems to be a problem with instance search picking an ill-formed solution (the error is in the instance argument of f).

**Comment by UlfNorell** [comment]
Also not instance search. Here's a shrunk example:

```agda
module _ where

module M (A : Set) where
  record R : Set where
    postulate
      B : Set

postulate
  A : Set
  r : M.R A

open M A

open import Agda.Builtin.Reflection

macro
  m : Term → TC _
  m goal =
    bindTC (inferType goal) λ goal-type →
    bindTC (normalise goal-type) λ goal-type →
    bindTC (inferType goal-type) λ _ →
    returnTC _

g : R.B r
g = m -- fails with Set !=< M.R _A_24
```
The problem is that the module application `M A` messes up the hiding of the `A` parameter of `R.B`. Since it lives in the record module, `A` should be hidden.

Since we don't care so much about hiding in internal syntax, these kinds of problems mostly show up when using reflection.

**Comment by andreasabel** [comment]
> Since we don't care so much about hiding in internal syntax, these kinds of problems mostly show up when using reflection.

... and `with`.
