### ISSUE TITLE
Showing inferred instance arguments

### ISSUE THREAD

**Issue by nad** [agda/agda#3086]
Consider the following code:
```agda
record R (A : Set) : Set where
  field
    x : A

open R ⦃ … ⦄

data D : Set where
  c : D

instance

  r : R D
  R.x r = c

d : D
d = x
```
Unless I'm missing something there is no simple way to find out which instance argument Agda infers on the final line:
* If I replace `x` with `x ⦃ ? ⦄`, then Agda does not infer any value for the question mark.
* If I turn on display of implicit arguments and normalise `d`, then I get `c`.

I think there should be an easy way to produce this information.

**Comment by UlfNorell** [comment]
This has come up before (#2172) and was solved in #2700 with the new `C-c C-;` command:

```agda
it : ∀ {a} {A : Set a} ⦃ x : A ⦄ → A
it ⦃ x ⦄ = x

d : D
d = x ⦃ {!it!} ⦄ -- C-c C-;
```
Prints
```
Goal: R D
Elaborates to: r
```
