### ISSUE TITLE
Regression caused by copattern translation

### ISSUE THREAD

**Issue by nad** [agda/agda#3088]
I have some code that seems to have been broken by ace8e0d099402a625ac460862ae0a81fcec538d4 ("[ records ] translate definitions returning record expressions to use copatterns"). I can fix the problem by giving some implicit arguments explicitly. Is this an expected consequence of this change? The commit comment includes the following text, which suggests that it is not: "For eta records the copattern definition is equivalent, so we can safely translate it behind the scenes." I suspect that this comment is overly strong, but if @UlfNorell states that this is (probably) a bug, then I can give a concrete test case.

**Comment by UlfNorell** [comment]
Constraint solving is notoriously brittle, so it's not too surprising that there are cases of metas no longer being solved. Though, feel free to give a test case if you think there might be an actual bug.
