### ISSUE TITLE
Nicer syntax for implicit @-patterns

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#3089]
Minor annoyance: @-matching currently only works on visible parameters, so

```agda
works : ℕ → ℕ
works 0 = 0
works x@(ℕ.suc _) = x

fails : ∀ {x : ℕ} → ℕ
fails {0} = 0
fails x@{ℕ.suc _} = x
```

It seems like this would be a convenient thing to allow.

EDIT: I just realized it does work if you use both parentheses and curly brackets, e.g., `{x@(ℕ.suc _)}`. Maybe this is fine - it just wasn't intuitive to me to write it that way.

**Comment by UlfNorell** [comment]
Given that we allow writing `.{p}` for dotted implicit patterns it does make sense to allow the same for as-patterns.

**Comment by MatthewDaggitt** [comment]
Seconded, got confused by this recently!
