### ISSUE TITLE
Internal error in parser when using parentheses in BUILTIN pragma

### ISSUE THREAD

**Issue by anka-213** [agda/agda#3090]
The following snippet causes Agda's parser to crash

    {-# BUILTIN NATURAL (N) #-}

with the following error

    An internal error has occurred. Please report this as a bug.
    Location of the error: dist/build/Agda/Syntax/Parser/Parser.hs:7123

**Comment by UlfNorell** [comment]
I suspect that line is this one (it's odd that it doesn't pick up the `LINE` pragmas for the internal error...):

https://github.com/agda/agda/blob/6dce3595c54f99647a05a56e0e88f6f5ba4ead1e/src/full/Agda/Syntax/Parser/Parser.y#L1858

**Comment by anka-213** [comment]
Yes. That matches line 7123 in the generated parser for my local build.

**Comment by andreasabel** [comment]
Regression introduced by fix for #2841: https://github.com/agda/agda/commit/c6ae4d5db2819deabe3678faed6851293a0d826c

**Comment by andreasabel** [comment]
I add this to the release-2.5.4 branch
