### ISSUE TITLE
Does Agda mode work on Emacs 26.1?

### ISSUE THREAD

**Issue by asr** [agda/agda#3093]
Emacs 26.1 just was [released](https://lists.gnu.org/archive/html/emacs-devel/2018-05/msg00765.html). I'll test RC 2 on this version of Emacs.

**Comment by asr** [comment]
It seems Agda mode works on Emacs 26.1 (I didn't find any problem loading a couple of files, running `agda-mode compile` or `make interaction`).

**Comment by nad** [comment]
AFAIK `make interaction` does not test Emacs.

**Comment by asr** [comment]
Right.
