### ISSUE TITLE
Would like to make hidden variable visible but it is created ambiguous

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3095]
This is shrunk from a large development with complicated nested induction and deep case splitting:
```agda
data Nat : Set where
  suc : {n : Nat} → Nat

data IsSuc : Nat → Set where
  isSuc : ∀{n} → IsSuc (suc {n})

test : ∀{n} → IsSuc n → Set
test p = aux p
  where
  aux : ∀{n} → IsSuc n → Set
  aux isSuc = {!.n!}  -- Split on .n here

-- Context:
-- p  : IsSuc .n
-- .n : Nat
-- .n : Nat

-- ERROR
-- Ambiguous variable .n
-- when checking that the expression ? has type Set
```
Here, the Agda-introduced variables `.n` are ambiguous, that's one problem.  But since on of these is from the parent function, one should nevertheless be able to split on the one introduced by the local function.

Related: #1325, #2424, #2729.

**Comment by andreasabel** [comment]
A related issue is that Agda allows `makeVisible` on a hidden variable bound in a parent clause,
but then nothing changes.
```agda
test : ∀{m} → IsSuc m → Set
test p = aux p
  where
  aux : ∀{n} → IsSuc n → Set
  aux isSuc = {!.m!}
```
Case splitting on `.m` succeeds here but prints the same clause.

**Comment by andreasabel** [comment]
Works for me, but before adding this to 2.5.4 last minute I'd like this reviewed from someone more firm with parameter-refinement. @jespercockx @UlfNorell ?

**Comment by UlfNorell** [comment]
Not quite:
```agda
open import Agda.Builtin.Equality

data Nat : Set where
  suc : (n : Nat) → Nat

data IsSuc : Nat → Set where
  isSuc : ∀{n} → IsSuc (suc n)

postulate lie : {A : Set} → A

test : ∀ m → IsSuc m → Set
test m p = aux p lie
  where
  aux : ∀{n} → IsSuc n → m ≡ suc n → Set
  aux isSuc refl = {!.n!} -- C-c C-c
  -- Expected: aux (isSuc {n}) refl = ?
  -- Get: Cannot split on module parameter .n
```
`getDefFreeVars` gives you the number of module parameters but they're not necessarily variables. I believe you want to grab `freeVarsToApply` and replace the `i < fv` check by a check if `Var i []` is in that list.

**Comment by UlfNorell** [comment]
Except `i` is not a deBruijn index is it...

**Comment by UlfNorell** [comment]
Simplified the test case
```agda
test : ∀ m → IsSuc m → Set
test m p = aux p refl
  where
  aux : ∀{n} → IsSuc n → m ≡ n → Set
  aux isSuc refl = {!.n!} -- C-c C-c
  -- Expected: aux (isSuc {n}) refl = ?
  -- Get: Cannot split on module parameter .n
```

**Comment by andreasabel** [comment]
Ok, that used to work in 2.5.3, thus, I introduced a regression.  Thanks for the review!

**Comment by andreasabel** [comment]
I can't promise to make this work until the deadline (June 3) as I am travelling right now.  Thus, I put this on 2.5.5.

**Comment by andreasabel** [comment]
Ok, for @UlfNorell 's most recent test case, splitting on `.n` gives me this debug output:
```
splitting clause:
  f       = aux
  context = {.n : Nat} (p : IsSuc (suc .n))
  tel     = {n : Nat} (p : IsSuc (suc n))
  perm    = x0,x1,x2,x3 -> x3,x1
parseVariables:
current module  = Issue3095._
current section = (m : Nat) (p : IsSuc m)
function's fvs  = 2
number of locals= 0
context         = {.n : Nat} (p₁ : IsSuc (suc .n))
checkpoints     = fromList [(0,EmptyS (error "Agda.Utils.Empty.Empty")),(19,Var 0 [] :# (Con (ConHead {conName = Issue3095.Nat.suc, conInductive = inductive, conFields = []}) ConOCon [Apply ωru(Var 1 [])] :# EmptyS (error "Agda.Utils.Empty.Empty"))),(96,IdS)]
matching names corresponding to indices [(".n",1)]
```
How do I find out from this information that I can split on `.n` which is`1` but not on `p` which is `0` ? @jespercockx ?

**Comment by jespercockx** [comment]
There's a similar problem for visible variables:
```agda
open import Agda.Builtin.Nat

foo : Nat → Nat
foo x = bar x
  where
    bar : Nat → Nat
    bar y = {!x!}
```
Splitting on `x` produces the following garbage:
```agda
foo : Nat → Nat
foo x = bar x
  where
    bar : Nat → Nat
    bar y = {!!}
    bar y = {!!}
```
Agda produces two clauses, one where `x` is `zero` and one where it is `suc x`, and then happily drops these patterns when printing the clauses.

I think maybe we should make it `__IMPOSSIBLE__` to drop any patterns that are not variables or dot patterns.

**Comment by andreasabel** [comment]
OP 2 https://github.com/agda/agda/issues/3095#issuecomment-392648294 is open again.

**Comment by jespercockx** [comment]
```agda
test : ∀{m} → IsSuc m → Set
test p = aux p
  where
  aux : ∀{n} → IsSuc n → Set
  aux isSuc = {!.m!}
```
What is the expected behaviour here? Should Agda throw an error instead?
