### ISSUE TITLE
Problem with declarePostulate

### ISSUE THREAD

**Issue by pavenvivek** [agda/agda#3097]
Consider Suspension and see the declarePostulate (which has the issue):

```agda
open import Agda.Builtin.Reflection
open import Agda.Builtin.Equality
open import Agda.Primitive
open import Data.List

pattern vArg x = arg (arg-info visible relevant) x
pattern hArg x = arg (arg-info hidden relevant) x

module Susp where

  private
    data Σₛ* (A : Set) : Set where
       N* : Σₛ* A
       S* : Σₛ* A

  Σₛ : (A : Set) → Set
  Σₛ = Σₛ*

  N : {A : Set} → Σₛ A
  N = N*

  S : {A : Set} → Σₛ A
  S = S*

  postulate
     merid : {A : Set} → (a : A) → (N {A} ≡ S {A})

  unquoteDecl merid* = declarePostulate (vArg merid*)
                        (pi (hArg (agda-sort (lit 0)))
                             (abs "A"
                        (pi (vArg (var 0 []))
                             (abs "a"
                        (def (quote _≡_)
                             (hArg (def (quote lzero) []) ∷
                              hArg (def (quote Σₛ) (vArg (var 1 []) ∷ [])) ∷
                              vArg (def (quote N) (hArg (var 1 []) ∷ [])) ∷
                              vArg (def (quote S) (hArg (var 1 []) ∷ [])) ∷ []))))))
```

`merid*` should resolve to `{A : Set} → (a : A) → (N ≡ S)` but it is resolving to `{A : Set} → (a : A) → (N* ≡ S*)`. This issue did not occur in the older development version. This happens only for types with parameters. For other types (with index or without index or params) its working fine.

**Comment by pavenvivek** [comment]
This issue is not observed in Agda 2.5.4 release version.

**Comment by asr** [comment]
I'm having problems for testing your example. Please add the missing imports.

> This issue is not observed in Agda 2.5.4 release version.

Which version are you talking about? The 2.5.4 release candidate 1 or 2?

**Comment by pavenvivek** [comment]
Release version 2.5.4 -> v2.5.3.20180526

**Comment by asr** [comment]
I'm getting a different error:

1. I used Agda syntax highlighting on your example. Please remove the `&nbsp;`s.
2. Which is the output of `agda --version`?

**Comment by pavenvivek** [comment]
Output of agda --version -> "Agda version 2.6.0-f4ad812"

**Comment by asr** [comment]
> `merid*` should resolve to `{A : Set} → (a : A) → (N ≡ S)` but it is resolving to `{A : Set} → (a : A) → (N* ≡ S*)`.

I'm getting `{A : Set} → A → .Issue3097.Susp.Σₛ*.N* ≡ .Issue3097.Susp.Σₛ*.S*` on both Agda versions (v2.5.3.20180526 and the version in the current master). How did you get the type of  `merid*`?

**Comment by pavenvivek** [comment]
I used the following macro:

```agda
  macro
    thm-prv : (C : Name) → Term → TC ⊤
    thm-prv C hole = bindTC (getType C)
                            (λ type → unify hole type)

  pf : thm-prv merid*
  pf = {!!}
```

**Comment by pavenvivek** [comment]
Its resolving to {A : Set} → (a : A) → (N* ≡ S*) in v2.5.3.20180526 as well.

**Comment by asr** [comment]
I got the error:

```
Not in scope:
  ⊤
  at <some-path>/Issue3097.agda:42,38-39
when scope checking ⊤
```

Note that you can use syntax highlighting on your examples using Markdown (see these [examples](https://guides.github.com/features/mastering-markdown/#examples)).

**Comment by asr** [comment]
> Its resolving to {A : Set} → (a : A) → (N* ≡ S*) in v2.5.3.20180526 as well.

Good.

**Comment by pavenvivek** [comment]
But its inconsistent. For types with indexes it behaves differently.

**Comment by pavenvivek** [comment]
The first version of declarePostulate (in commit -> "https://github.com/agda/agda/tree/c5f355860d5a359f863ce21d6c17f9ee4552f8b8") had a different behavior. It resolved merid* to {A : Set} → (a : A) → (N ≡ S). Is the specification for declarePostulate changed?

**Comment by UlfNorell** [comment]
The change is that `N` and `S` are getting inlined. See second and third bullet point [here](https://github.com/agda/agda/blob/0bc4648f0f22889c923acd1ba6d82cf78c1ca142/CHANGELOG.md#language).

To prevent inlining you can use the `NOINLINE` pragma:
```agda
N : {A : Set} → Σₛ A
N = N*
{-# NOINLINE N #-}

S : {A : Set} → Σₛ A
S = S*
{-# NOINLINE S #-}
```

**Comment by pavenvivek** [comment]
Got it. Thanks !
