### ISSUE TITLE
Option for double-checking terms using checkInternal

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#3099]
It would be nice to have an option `--double-check` to run `checkInternal` on all terms produced by the main Agda typechecker. Some places where we could insert this check:

- types of top-level declarations
- right-hand sides of definitions by pattern matching
- constructor and field types
- types of module parameters

Adding this option shouldn't take much effort, though dealing with all the bugs it uncovers might.

**Comment by andreasabel** [comment]
I had this for the terms produced by unification, only that it uncovered the hack where level variables were abused as sort variables.  Since you (presumably) cleaned this up, we can reactivate the double checking of solutions.

**Comment by jespercockx** [comment]
I added the new option in https://github.com/agda/agda/commit/934c1a1a44b13dc054b347fa2fbc52552eb4af94, but we're still a long way off from actually using double-checking since the option currently only uncovers all the hacks we've been using. In particular, at the moment the first problem one runs into when running the test suite with `--double-check` is that `checkInternal` doesn't work correctly for `piSort`s.

**Comment by andreasabel** [comment]
Maybe a way to go is to ignore certain problems (like wrong sorts) at first to catch more important problems, such as #2797.  Once we caught the most harmful bugs, we can deal with stuff like sorts etc.

**Comment by andreasabel** [comment]
De Bruijn bug fixed by @jespercockx  in 0f67eb82365ef4d767bbc7216473744668c752a5

**Comment by jespercockx** [comment]
As suggested to me by @nad, I enabled the `--double-check` flag in the test suite (for succeed and fail), except for the test cases where it doesn't pass (yet). That way, we make sure future patches do not make the situation worse than it is currently, and newly introduced bugs might be uncovered faster.

**Comment by jespercockx** [comment]
Note to self: currently errors from `--double-check` influence the behaviour of instance search by ruling out candidates. They should probably be their own kind of error which is not caught by instance search.

**Comment by martinescardo** [comment]
I've just learned of this option and tested it with my TypeTopology development. I get an error in a file (UF-Equiv.lagda). Should I worry? It is not clear what this option is really doing. Thanks.

**Comment by jespercockx** [comment]
No, there's no real need to worry yet. The `--double-check` flag enables Agda's `checkInternal` typechecker, which typechecks again all the results of the main typechecker. In theory, it serves a similar role to `Qed` in Coq, making sure that the result of elaborating the source code to the core type theory is indeed correct. In practice, there are still a bunch of test cases in the test suite that do not pass with this flag (see https://github.com/agda/agda/commit/354be4dd4a57dd5a8f5c81c51e5ba469f8c3a0a9#diff-9e704715c0abd2aa4b92ecb2159d9f08R121-R178), so it is currently mainly used as a tool for debugging the implementation of Agda.

**Comment by jespercockx** [comment]
I have mostly lost the motivation to investigate further why there are certain cases where the internal double-checker disagrees with the main checker. Since the flag itself has been implemented, I'm closing this as completed. Feel free to report specific errors in the double-checker as bugs if they come up.
