### ISSUE TITLE
Clean up old github branches

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#3101]
It would be nice if we could clean up some of the unused branches on Github. AFAICT, the following branches are currently in use:
- `master`
- `stable-2.5`
- `parametric`, `flat`, `hits` (assuming @Saizan will continue developing these)
- `CPSWriter` (see #1709)
- `issue2503-useless-imports` (see #2503)

I'm pretty sure we can delete the following branches since they have no patches not on master:
- `Issue2604`
- `good-2017-01-10-stable-2.5`
- `hitss`

The following branches are archived and are duplicated by a tag, so I think we can remove them too:
- `legacy-2.4.2.5`
- `legacy-2.5.5.1`
- `maint-2.4`
- `maint-2.4.0`
- `release-2.5.1`
- `release-2.5.2`
- `release-2.5.3`
- `release-2.5.4`

That leaves the rest, about which I'm not very sure:
- `NameRep`: this seems to deal with using Text instead of String in some places. @UlfNorell is this still something we want to do?
- `dedukti`: this is about translating Agda code to Dedukti. @andreasabel do you have any further plans for this project?
- `issue-1515-typed-lambda`, `issue-2556`: These issues are still open but the patches on these branches are kind of stale. @andreasabel do you still plan on integrating the changes on these branches into master?

**Comment by asr** [comment]
> The following branches are archived and are duplicated by a tag, so I think we can remove them too:
> - `legacy-2.4.2.5`
> - `legacy-2.5.5.1`
> - `maint-2.4`
> - `maint-2.4.0`
> - `release-2.5.1`
> - `release-2.5.2`
> - `release-2.5.3`
> - `release-2.5.4`

Yes, you can remove them except `release-2.5.4`. Please note I tagged this issue with `dev-op`.

**Comment by nad** [comment]
> The following branches are archived and are duplicated by a tag, so I think we can remove them too:

Are the tags, and all commits reachable from the tags, still backed up on GitHub if the branches are removed?

**Comment by UlfNorell** [comment]
The `NameRep2` branch was an attempt by  @andreasabel to speed up serialisation by using byte strings instead of strings for names.

In the final commit he writes:
> This experiment to speed up serialization by changing the name representation seems to have failed.

I think we can safely remove this.

**Comment by UlfNorell** [comment]
> Are the tags, and all commits reachable from the tags, still backed up on GitHub if the branches are removed?

Yes.

**Comment by UlfNorell** [comment]
In general I think it's a good idea to keep the main repo as clean as possible. So, if you are working on a feature branch by yourself, it's better to use your own fork.

**Comment by andreasabel** [comment]
You can delete all *my* feature branches, I forked agda anew.

However, I'd say the `legacy` branches could stay.  These are to update old Agda versions to compile with new GHCs.

**Comment by jespercockx** [comment]
I don't have permission to delete `stable-2.4` and `stable-2.4.0` myself. Could someone with more rights do this?
