### ISSUE TITLE
Proper dummy terms; remove Sort Prop hack

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3107]
Proper dummy terms; remove Sort Prop hack.

**Comment by andreasabel** [comment]
In https://github.com/agda/agda/commit/d3280e0d097814703cdc656876e587595f884d3c I introduced a new `Term` constructor `Dummy`.  Maybe I could also have introduced it in `Sort`; fewer cases to add!?  Anyhow, I think it is clearer in `Term`.

**Comment by asr** [comment]
I tagged the issue with `dev-ops`.

**Comment by UlfNorell** [comment]
Now I'm confused about what the `dev-ops` tag is used for.. The description says Travis, Makefile, test suite, etc. This is about refactoring the actual Agda implementation.

**Comment by asr** [comment]
Note that this issue isn't a bug.

We are excluding issues tagged with

`status: abandoned`,
`status: duplicated`,
`status: invalid`,
`status:  wontfix`, 
`status: working-as-intended` or
`dev-op`. 

Which tag should I use for excluding this issue from the list in the CHANGELOG?

**Comment by UlfNorell** [comment]
`type: task`? Or the absence of `bug` or `enhancement`?

**Comment by asr** [comment]
No absences please. We use `type: task` for some issues (e.g. missing documentation) we list in the CHANGELOG.

**Comment by UlfNorell** [comment]
Ok, but then `dev-ops` is not really a good name for it. Maybe it should just be `skip-changelog` if that's exactly what it means. Then we can use it for bugs that haven't been released as well, as discussed in #2875.

**Comment by asr** [comment]
Good idea!

**Comment by asr** [comment]
@andreasabel, I'm waiting your opinion on the tag name `skip-changelog`.

**Comment by andreasabel** [comment]
@asr: Sounds good, go ahead!

**Comment by nad** [comment]
I created the label `not-in-changelog` yesterday. Feel free to rename it.

**Comment by asr** [comment]
* I replaced `dev-ops` by `not-in-changelog` and
* I added the `not-in-changelog` label to the closed issues labelled `cubical` or `generalize`

**Comment by andreasabel** [comment]
See #3200: the abuse of `Prop` was not completely eradicated.  I shall also introduce a `DummyS` to remove the last abuses of `Prop` in sorts.
