### ISSUE TITLE
Are we allowed to elide the body of let-expressions?

### ISSUE THREAD

**Issue by banacorn** [agda/agda#3113]
I'm working on a [parser for syntax highlighting](https://github.com/banacorn/tree-sitter-agda) on Atom.
And I found some difficulties when parsing *let-expressions*. 

Normally we would write something like this:
```agda
f = let n = 420 in n
```

However, according to the grammar, the expression after and including the token `in` could be elided.

https://github.com/agda/agda/blob/d673f075a2d74c660f8451114f2769dbb23c5aff/src/full/Agda/Syntax/Parser/Parser.y#L678-L680

So the following syntax is also acceptable (at least for the parser):

```agda
f = let n = 420
```

But, of course, the definition above would be rejected with some error message saying "Missing body in let-expression". 

It makes me wonder, why would the grammar allow the body to be elided, creating this infamous **dangling else problem** in Agda? Is it of any use to us?

**Comment by gallais** [comment]
These are used by [do-notations](https://agda.readthedocs.io/en/latest/language/syntactic-sugar.html?highlight=do%20notation#id4)

**Comment by banacorn** [comment]
I didn't think about that! Thanks!

The nightmare of the dangling-in has become the reality.

**Comment by nad** [comment]
> I'm working on a parser for syntax highlighting on Atom.

I assume that you have some reason for not using the actual Agda parser. Let me guess:

* Atom is implemented in some language that is not Haskell, and interfacing with Haskell is non-trivial.
* The Agda library takes up tens of megabytes.
* Interfacing with the unstable Agda API requires too much work.

**Comment by banacorn** [comment]
The reason why I'm not using the actual Agda parser is *interfacing*.

I'm using [tree-sitter](https://github.com/tree-sitter/tree-sitter) to create my parser. A parser generator that was designed to target some editor-related features like syntax-highlighting and code-folding. It's not until 2017 when the humans finally discovered that they should be doing this with *context-free grammars* instead of *regular grammars* XD

And since it's developed by people from Atom, the interfacing effort is minimum (though I believe it's intended to be independent from Atom).

I know that Agda outputs highlighting instructions, but I didn't use them because I'm too lazy and I don't know what impact it may have on the performance of the editor. 
Maybe I should give it a try.

**Comment by nad** [comment]
Could Atom support the kind of interaction with the Agda backend that Emacs supports?

**Comment by banacorn** [comment]
If you are referring to interactions other than dynamic syntax highlighting, yes!

The reverse engineering took quite some effort:
https://github.com/banacorn/agda-mode/wiki/Conversations-between-Agda-&-agda-mode

I [tried](https://github.com/banacorn/agda-language-server) to implement [Language Server Protocol](https://langserver.org/) for Agda. I think it's a bit an overkill though. 

It would be nice if we can ask Agda to speak JSON instead Emacs Lisp and Haskell (yes, I'm pleading!!!)

**Comment by nad** [comment]
The Emacs Lisp part is (hopefully) isolated to `Agda.Interaction.EmacsTop`. I suppose you could add a similar module with JSON support.
