### ISSUE TITLE
Missing alpha-renaming when printing constraints

### ISSUE THREAD

**Issue by Saizan** [agda/agda#3114]
The code below generates constraints printed as

```
10 := refl [blocked by problem 12]
[12,16] (?0 a x x) = (?0 b x x) : A
```

Where the two "x" are presumably two distinct arguments, just both named "x" in the telescope.

```agda
open import Agda.Builtin.Equality

postulate
  A : Set
  a : A
  b : A

mutual
  Meta : A → A → A → A
  Meta = { }0

  _ : Meta a ≡ Meta b
  _ = refl
```

**Comment by andreasabel** [comment]
Printing is ok in 2.5.1.1.  I suppose this is the same regression as in #2522.
