### ISSUE TITLE
Documentation for generalize

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#3116]
User manual and changelog.

**Comment by divipp** [comment]
To help to close this ticket we could mention here exactly what is missing from the current documentation.

This is missing:

- documentation of irrelevantly generalized variables

**Comment by divipp** [comment]
- documentation of places where generalizable variables can be used / limitations where it cannot be used

**Comment by divipp** [comment]
[link to current changelog](https://github.com/agda/agda/blob/master/CHANGELOG.md#type-checking-and-interaction)
(The user manual should be adjusted to the CHANGELOG before closing this issue.)

**Comment by gallais** [comment]
> The user manual should be adjusted to the CHANGELOG before closing this issue

And / or the other way around too. Cf. 8e5b33d7ad6a9f7b01e79c658f07d9fb4a573b6c which fixes errors related to parsing,
out-of-scope identifiers, and conflicting generalize blocks in the user manual.

**Comment by UlfNorell** [comment]
- #3301: workaround for no sort generalization
