### ISSUE TITLE
Internal error in InstanceArguments.hs:292

### ISSUE THREAD

**Issue by timjb** [agda/agda#3125]
I got the error

```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/InstanceArguments.hs:292
```

while checking the code

```agda
      C-additive-is-equiv : is-equiv (GroupHom.f (Πᴳ-fanout (C-fmap n ∘ ⊙bwin {X = X})))
      C-additive-is-equiv = transport is-equiv
        (λ= $ Trunc-elim
          (λ _ → idp))
        ((ac (uCEl n ∘ X)) ∘ise (is-eq into out into-out out-into))
```

with Agda 2.5.4. ([Permalink to the code in context](https://github.com/HoTT/HoTT-Agda/blob/e48a16bcd719e2fcb409d79e3f7df6c6b81223bb/theorems/cohomology/SpectrumModel.agda#L226-L230), [Permalink to line in InstanceArguments](https://github.com/agda/agda/blob/v2.5.4/src/full/Agda/TypeChecking/InstanceArguments.hs#L292))

The problematic instance argument in this example is the [instance argument of Trunc-elim](https://github.com/HoTT/HoTT-Agda/blob/e48a16bcd719e2fcb409d79e3f7df6c6b81223bb/core/lib/types/Truncation.agda#L19):

```agda
  module TruncElim {n : ℕ₋₂} {A : Type i} {j} {P : Trunc n A → Type j}
    {{p : (x : Trunc n A) → has-level n (P x)}} (d : (a : A) → P [ a ]) where

    postulate  -- HIT
      f : Π (Trunc n A) P
      [_]-β : ∀ a → f [ a ] ↦ d a
{-# REWRITE [_]-β #-}
```

The error disappears when I either give the source of transport (as done in [this commit](https://github.com/HoTT/HoTT-Agda/pull/44/commits/13d4ba5270f467744320475218a87dcbbbc0d6d8))

```agda

      C-additive-is-equiv : is-equiv (GroupHom.f (Πᴳ-fanout (C-fmap n ∘ ⊙bwin {X = X})))
      C-additive-is-equiv = transport is-equiv
        {x = unchoose ∘ into}
        (λ= $ Trunc-elim
          (λ _ → idp))
        ((ac (uCEl n ∘ X)) ∘ise (is-eq into out into-out out-into))
```

and/or give the target type family of `Trunc-elim`

```agda
      C-additive-is-equiv : is-equiv (GroupHom.f (Πᴳ-fanout (C-fmap n ∘ ⊙bwin {X = X})))
      C-additive-is-equiv = transport is-equiv
        (λ= $ Trunc-elim
          {P = λ x → unchoose (into x) == GroupHom.f (Πᴳ-fanout (C-fmap n ∘ ⊙bwin {X = X})) x}
          (λ _ → idp))
        ((ac (uCEl n ∘ X)) ∘ise (is-eq into out into-out out-into))
```

explicitly. I tried reducing this to a minimal example, but failed so far (Agda succeeded typechecking all my attempts).

**Comment by asr** [comment]
I could reproduce the issue with 2.5.4 and master (2.6.0-0ad14b8).

**Comment by jespercockx** [comment]
Since this is an internal error in a part of the code that has since been removed, I strongly suspect it is no longer there. Please reopen or post a new issue if there's still a problem.
