### ISSUE TITLE
Sigma builtin not added to setup, agdai file missing.

### ISSUE THREAD

**Issue by louisswarren** [agda/agda#3128]
`Agda.Builtin.Sigma` was added in v2.5.4 (commit 707ce60), but wasn't added to `Setup.hs`, meaning the .agdai file is not generated at installation. This prevents Sigma from being imported under normal circumstances, as users invoking agda won't have permission to generate the file.

**Comment by asr** [comment]
Before releasing 2.5.4 we added the missing `Agda.Builtin.Word` (see #2923) but we didn't add `Agda.Builtin.Sigma`, argh!.

I could suggest to make a bug-fix release however the issue can be easily fixed from the user/admin side. Opinions?

**Comment by asr** [comment]
Or if cubical is ready to see the world, we can release 2.6 including a fix to this issue.

**Comment by UlfNorell** [comment]
We are not ready for 2.6.

Can't this be hotfixed on hackage without making a new release? Just uploading a new `2.5.4` with an updated `Setup.hs`?

**Comment by asr** [comment]
No, we cannot update `Setup.hs` on Hackage.

**Comment by andreasabel** [comment]
Since there is the 2.5.4 release branch, maybe making a release 2.5.4.1 isn't so much work maybe?!

**Comment by UlfNorell** [comment]
Should just be updating `Setup.hs` and the version numbers and `cabal upload` no?

**Comment by nad** [comment]
Has `Agda.Builtin.Sigma` been advertised? Does anyone need to use it? Perhaps we could just pretend that it does not exist.

**Comment by UlfNorell** [comment]
I think some people might want to use the standard library:

https://github.com/agda/agda-stdlib/blob/e3978bbe8c103ef759f45a979d47b243708f05ef/src/Data/Product.agda#L21

**[Edit]** Huh, source code rendering doesn't work for other repos :(. (That's the import of `Agda.Builtin.Sigma` in `Data.Product`.)

**Comment by MatthewDaggitt** [comment]
> Has Agda.Builtin.Sigma been advertised? Does anyone need to use it? Perhaps we could just pretend that it does not exist.

So I didn't advertise the change in implementation of `Sigma` in the standard library in the CHANGELOG in the latest release.

> I think some people might want to use the standard library: https://github.com/agda/agda-stdlib/blob/e3978bbe8c103ef759f45a979d47b243708f05ef/src/Data/Product.agda#L21

I haven't noticed any problems using `Data.Product` with Agda 2.5.4. From the sound of it above, I take it that you'd expect there would be?

**Comment by UlfNorell** [comment]
The problem is that `Agda.Builtin.Sigma` isn't compiled (type checked) when installing Agda, so if you install as administrator you might not be allowed to create the interface file as a user, meaning anything using `Data.Product` would fail.

**Comment by MatthewDaggitt** [comment]
Hmm, that's strange then. Reasonably large numbers of people have been using the `experimental` branch of the standard library for at least 3 or 4 weeks since the first 2.5.4 release candidate was announced, and I haven't received any complaints so far. Maybe everyone is installing it as a user...

**Comment by andreasabel** [comment]
> Maybe everyone is installing it as a user...

I think this is what is happening...

While we are at it, could not Setup.hs figure out the builtins from reading the directory contents, or would that be unsafe? @UlfNorell ? https://github.com/agda/agda/commit/83b392296daaca96a1c9221cbb6aefdd0d131bb6
https://github.com/agda/agda/blob/b3eb0a0852e8b7493e6ff815b9d9d8edc2f99df6/Setup.hs#L16-L29

**Comment by UlfNorell** [comment]
If someone is in a position to inject things into the `datadir`, I'm pretty sure they could also change `Setup.hs` to do arbitrary things...

**Comment by andreasabel** [comment]
Ok, then it should be fine to just run `checkPrim` on all `agda` files in `datadir dirs </> "lib" </> "prim" </> "Agda"`.

**Comment by asr** [comment]
I'll add  the missing `Agda.Builtin.Sigma` and release 2.5.4.1.

**Comment by asr** [comment]
The installation with `stack` (any GHC version) generates the following warning:

```
.../.stack-work/install/x86_64-linux/lts-12.16/8.4.4/share/x86_64-linux-ghc-8.4.4/Agda-2.6.0/lib/prim/Agda/Builtins: .../.stack-work/install/x86_64-linux/lts-12.16/8.4.4/share/x86_64-linux-ghc-8.4.4/Agda-2.6.0/lib/prim/Agda/Builtins: getSymbolicLinkStatus: does not exist (No such file or directory)
```

That means we are not generating the interface files (using both `cabal` or `stack`).

The error is due to this line in `Setup.hs`:
 https://github.com/agda/agda/blob/12afa483a6f820251edf0986a76681a418dce427/Setup.hs#L57

because `Builtins` should be `Builtin`.

Since we are not testing the generation of the interface files, this error was not detected. I'm planning fix the error, add a test and release 2.5.4.3.

**Comment by asr** [comment]
The tentative release date for 2.6.0 is in one month according to its milestone. What about if we use my stupid error above for starting to prepare the release of 2.6.0?

**Comment by asr** [comment]
After fixing the above type I realised we are not generating any interface files from `Setup.hs`. I reported this problem in #3444.

**Comment by andreasabel** [comment]
I found a small problem with the current solution.  The installation tries to build every module in the lib/prim directory in the _installed_ location.  There might be stale (or injected) files there since cabal does not seem to clean up by itself.  In my case this leads to this error for the stale file Erase.agda:
```
/Users/abel/.cabal/share/x86_64-osx-ghc-8.4.4/Agda-2.6.0/lib/prim/Agda/Builtin/Erase.agda:7,11-66
There is no primitive function called primErase
when checking that the type of the primitive function primErase is
∀ {a} {A : Set a} {x y : A} → x ≡ y → x ≡ y
WARNING: Failed to typecheck /Users/abel/.cabal/share/x86_64-osx-ghc-8.4.4/Agda-2.6.0/lib/prim/Agda/Builtin/Erase.agda!
```
Maybe we should clean out the directory during install before putting the files there again?

**Comment by nad** [comment]
> Maybe we should clean out the directory during install before putting the files there again?

That sounds potentially dangerous to me. An alternative is to compile exactly the right files.

**Comment by asr** [comment]
> I found a small problem with the current solution.  The installation tries to build every module in the lib/prim directory in the _installed_ location.  There might be stale (or injected) files there since cabal does not seem to clean up by itself.

I think I could build only the Agda files listed on the `data-files` field in the `Agda.cabal` file, but I don't see any difference from the security point of view.

> An alternative is to compile exactly the right files.

This was the previous solution but we changed to the current solution (i.e. build all the files in the installed location) because someone forgot to add a file. See the OP of this issue.


> In my case this leads to this error for the stale file Erase.agda:
>```
>/Users/abel/.cabal/share/x86_64-osx-ghc-8.4.4/Agda-2.6.0/lib/prim/Agda/Builtin>>/Erase.agda:7,11-66
>There is no primitive function called primErase
>when checking that the type of the primitive function primErase is
>∀ {a} {A : Set a} {x y : A} → x ≡ y → x ≡ y
>WARNING: Failed to typecheck /Users/abel/.cabal/share/x86_64-osx-ghc-8.4.4/Agda-2.6.0/lib/prim/Agda/Builtin/Erase.agda!
>```

In the above commit, I changed the above WARNING by an error in the installation. That is, the installation fails if if there was an error type-checking the built-ins or the primitives modules.

**Comment by asr** [comment]
The Travis job failed (only) on GHC 7.10.3 with the [error](https://travis-ci.org/agda/agda/jobs/477862506):

```
...
Linking /home/travis/dist/build/agda-tests/agda-tests ...
Generating Agda library interface files...
agda: The lib directory /home/travis/.cabal/share/x86_64-linux-ghc-7.10.3/Agda-2.6.0/lib does not exist
Error: Failed to typecheck /home/travis/.cabal/share/x86_64-linux-ghc-7.10.3/Agda-2.6.0/lib/prim/Agda/Primitive.agda!
Failed to install Agda-2.6.0
cabal: Error: some packages failed to install:
Agda-2.6.0 failed during the final install step. The exception was:
ExitFailure 1
```

I could reproduce the error.

**Comment by asr** [comment]
Back-ported into 2.5.4.3.
