### ISSUE TITLE
Usage of `test/bugs`

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3129]
I was going to suggest to remove `test/bugs` from the repo, but then I realized that @UlfNorell recently added new test cases there: https://github.com/agda/agda/commit/5118d4ebdb6a0ce1bc7dbd9b66aa9bfe5ffa08e2
Thus, I suggest to implement one of the two:
- remove `test/bugs`
- include `test/bugs` in the test suite run

The latter option could be implemented as follows:
- accept either failure or success, store result as status
- notify the developer if the status changed, asking to accept the status change `Y/N`
- if `Y`, continue test suite run
- if `N`, test suite run fails with exitcode > 0

**Comment by UlfNorell** [comment]
It would function exactly as `test/Fail` no? Since we switched to tasty silver I believe the only difference between success and failure is in the golden value.

**Comment by andreasabel** [comment]
> It would function exactly as test/Fail no? 

I suppose so.

**Comment by gallais** [comment]
I got something working. A lot of the 'bugs' now typecheck. Should I just move
them to `Succeed/`?

**Comment by andreasabel** [comment]
It seems that the `bugs` test suite is not run on travis.
Also, I think `bugs` should be run first (even before `succeed`).

**Comment by gallais** [comment]
Buried in #3984 is a bunch of changes cleaning up the golden values & output of
the bugs tests to make them more robust (e.g. to ignore the line number of the
`__IMPOSSIBLE__` encountered).

I think we should wait for this to be in before running the tests on travis.

**Comment by gallais** [comment]
I am happy with this. If someone wants to run the tests on travis,
please take over.
