### ISSUE TITLE
Conflict between dot pattern and postfix projection

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3130]
```agda
record R : Set₁ where
  field p : Set
open R

data D : (R → Set) → Set₁ where
  c : D p

test : (f : R → Set) (x : D f) → Set
test .p c = {!!}
```
yields
```
Cannot eliminate type 
(f : R → Set) → D f → Set
 with projection 
p
when checking that the clause test .p c = ? has type
(f : R → Set) → D f → Set
```
Workaround: eta-expand projection:
```agda
test .(λ x → x .p) c = {!!}
```
Maybe postfix-projection parsing should not allow parentheses.  This also fails:
```
test .(p) c = {!!}
```
We should not generate this error as a result of case splitting.

**Comment by nad** [comment]
From #1963:

>> Isn't the grammar (more) ambiguous now? How do you distinguish between postfix projections and dot patterns?

> There is no ambiguity

:)

**Comment by andreasabel** [comment]
Well, there is no ambiguity such that both a postfix projection and a dot pattern would make sense (finally), since we are either dealing with a record or a function type.  However, the disambiguation happens already in the scope checker, where not enough information is available.  Maybe the problem could be fixed in the splitter, to reinterpret a postfix projection pattern as a dot pattern in case we are dealing with a function type.

**Comment by andreasabel** [comment]
There is a related problem that a pattern variable can shadow a projection even if it comes later:
```agda
record R : Set₁ where
  field y : Set → Set
open R

fails : R
fails .y y = y
```
This reports
```
Cannot eliminate type S with pattern .y (did you supply too many arguments?)
when checking that the clause fails .y y = y has type S
```
What is going on here is that the scope checker first skips all dotted things in the lhs, binds `y` to a pattern variable, and then considers `.y`.  Because the projection `y` is now shadowed, this is interpreted as a dot pattern instead of a projection.
What the scope checker should do here is to consider "dot patterns" with a single identifier in the first pass and check whether they are projections in scope.  In this case, they should be parsed as projection patterns.

**Comment by andreasabel** [comment]
What is remains is to also print a dot pattern with parentheses if its content is a mere projection name, i.e., as `.(p)`.

**Comment by nad** [comment]
I'm not sure it's a good idea to let `.p` and `.(p)` mean different things.

**Comment by andreasabel** [comment]
The syntax of postfix projection patterns has become stricter, we no longer accept `.(p)`, `.((p))` or the like.  It has to be `.` followed by the projection identifier.  This part is uncontroversial, is it?
The other part, that `.p` could denote a dot pattern containing just a projection name is a fringe case; the present issue did not come from a real use case, just arose from discussions on the implementation of pattern matching.
In general, I agree that the `.` is too heavily overloaded, but the root for this is already in the original design of the language (and the lack of reserved characters).

**Comment by nad** [comment]
> This part is uncontroversial, is it?

Yes.

**Comment by WolframKahl** [comment]
I'm pretty sure it's not a good idea to let `.p` and `.(p)` mean different things.

**Comment by andreasabel** [comment]
It should not come as a surprise that `x .(fst)` is not a valid projection application, confer JAVA: 
```
$ javac List.java
List.java:16: error: <identifier> expected
    this.(hd) = hd;
         ^
```

**Comment by UlfNorell** [comment]
Indeed. Allowing `x .(fst)` would suggest you could also write `x .(const fst zero)`.
