### ISSUE TITLE
Missing test case for the `--no-forcing` option

### ISSUE THREAD

**Issue by gallais** [agda/agda#3131]
I would expect the following definition to be rejected but it is not.

```agda
data A : Set₁ → Set where
  C : (S : Set₁) → A S
```

Do we have a special case declaring that because `S` is forced by
the index then it's OK? Do we silently turn the index into a parameter?

**Comment by jespercockx** [comment]
Yes, Agda does a forcing analysis and ignore the sorts of the forced constructor arguments when checking that they fit in the sort of the datatype.

**Comment by asr** [comment]
Note that you can disable the forcing analysis/optimization using the `--no-forcing` option. I couldn't find any test case for this option, so I added a failing test case using the example in the OP.

**Comment by asr** [comment]
Is any particular reason why the  `no-forcing` option is not a pragma?

**Comment by UlfNorell** [comment]
I don't believe so. It should be safe to disable forcing on a per-datatype basis.
