### ISSUE TITLE
Internal errors with 'variable'

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#3134]
```
open import Agda.Builtin.Nat
open import Agda.Builtin.Equality

postulate
  ⊤ ⊥ : Set
  _&_ : Set → Set → Set
  _≤_ : Nat → Nat → Set

{-# TERMINATING #-}
_∣_ : Nat → Nat → Set
m     ∣ zero  = ⊤
zero  ∣ suc n = ⊥
suc m ∣ suc n = (suc m ≤ suc n) & (suc m ∣ (n - m))

postulate divide-to-nat : ∀ {m n} → n ∣ m → Nat

variable {m n} : Nat

divide-to-nat-correct : (e : m ∣ n) → divide-to-nat e * n ≡ m
divide-to-nat-correct = ?
```
This produces an internal error at `src/full/Agda/TypeChecking/Substitute.hs:72`. You get a different variant when you change the type signature of `divide-nat-correct` to `divide-to-nat-correct : (e : m ∣ n) → _`: internal error at `src/full/Agda/TypeChecking/Monad/MetaVars.hs:98`.

As an aside, I liked the old `generalize` keyword better than the current `variable`; the latter feels too generic/overloaded.

**Comment by asr** [comment]
Please note that we are using the `not-in-changelog` label for bugs in new features (e.g. `generalize`) which have not been released.

**Comment by UlfNorell** [comment]
This is this TODO:

https://github.com/agda/agda/blob/323f58f9b8dad239142ed1dfa0c60338ea2cb157/src/full/Agda/TypeChecking/Rules/Term.hs#L1266-L1267
