### ISSUE TITLE
Spurious module parameters printed in extended lambda in termination error

### ISSUE THREAD

**Issue by sattlerc** [agda/agda#3136]
Tested on master and 2.5.4.

```agda
{-# OPTIONS --postfix-projections #-}
module Issue3136 (A : Set) where

postulate
  any : {A : Set} → A
  x : A
  P : A → Set

record C : Set where
  field
    a : A
    b : P a

c : C
c = λ where
  .C.a → x
  .C.b → λ where
    → any
```

Running this results in the following message:
> An internal error has occurred. Please report this as a bug.
> Location of the error: src/full/Agda/Syntax/Internal.hs:978

This refers to the following Haskell function in the Agda source:
```haskell
-- | Drop 'Apply' constructor. (Unsafe!)
argFromElim :: Elim' a -> Arg a
argFromElim (Apply u) = u
argFromElim Proj{}    = __IMPOSSIBLE__
argFromElim (IApply _ _ r) = defaultArg r -- losing information
```

Curiously, the internal error vanishes if the option `--postfix-projections` is removed, resulting "merely" in a termination checking error.

**Comment by andreasabel** [comment]
A way to debug this is to replace unsafe `argFromElim` by a safe version that returns a `Maybe (Arg a)`.

**Comment by andreasabel** [comment]
It seems this is a bug in the printer.  Without `--postfix-projections`, the error is the following:
```agda
Termination checking failed for the following functions:
Problematic calls:
  C.a (λ { A .C.a → x ; A .C.b → λ { .extendedlambda1 → any } })
  λ { A → any }
```
This looks already wrong to me:
- [x] Where does the  `.extendedlambda1` come from here, or why is it not dropped by the printer?
- [ ] The module parameter `A` should be dropped.

With the option, the internal error is thrown in `applyE` for `instance Apply Clause`.  I seem to remember there was a problem with this related to parameter refinement.

**Comment by andreasabel** [comment]
I fixed the spurious `.extendedlambda1` printing.
I leave the problem with the parameter dropping to the parameter refinement experts @UlfNorell .
https://github.com/agda/agda/blob/84502aa6e996f1157f2ad811267757f47750b5f7/src/full/Agda/Syntax/Translation/InternalToAbstract.hs#L662
https://github.com/agda/agda/blob/84502aa6e996f1157f2ad811267757f47750b5f7/src/full/Agda/TypeChecking/Substitute.hs#L323-L330

**Comment by UlfNorell** [comment]
This isn't a parameter refinement issue. The problem is that the termination checker produces ill-formed "problematic calls":

https://github.com/agda/agda/blob/18743484d0a0f01e068287fe50a465d8e0044699/src/full/Agda/Termination/TermCheck.hs#L839-L842

cc #2376

**Comment by andreasabel** [comment]
Ah sorry about that.
Indeed, the internal error goes away if I only drop arguments at the end (which is anyway the correct thing to do to remove arguments appended by eta-expansion).

Now the error is:
```
Termination checking failed for the following functions:
Problematic calls:
  (λ { .C.a → x ; .C.b → λ { → any } }) .C.a
  λ { A → any }
    (at Issue3136.agda:22,10-23,10)
```
The second extended lambda still has the spurious module parameter.
