### ISSUE TITLE
Preserve Markdown as-is when outputting HTML

### ISSUE THREAD

**Issue by vlopezj** [agda/agda#3137]
@ice1000 said on issue https://github.com/agda/agda/pull/2357#issuecomment-397890105:
> Hi there, is it possible to compile the agda code blocks to html only and leave other parts of the markdown document unchanged?
> 
> When I'm compiling my lagda.md files to html, the ordinary text parts are made "Comments", preventing the markdown renderer to render it.

I think this would be a useful feature. I don't know if someone else will be interested in implementing it; but you are welcome to give it a try yourself.

To avoid changing existing behaviour, I would suggest an extra flag `--preserve-comments`, which would tell Agda to leave all non-Agda text as-is when outputting HTML. This flag would be valid for both the  `--html` and the `--latex` output modes. 

For the `--latex` mode, preserving comments is the current default behaviour. For completeness, we could also have a `--no-preserve-comments` flag.

For extra functionality, one could have the default behaviour for each mode (preserve comments or not) depend on the extension of the file.

It was @ak3n who originally implemented Markdown support… Perhaps he has some ideas or even a work-around for your use case.

**Comment by ice1000** [comment]
Created a PR that might fix this.

**Comment by ice1000** [comment]
For those who don't have patience to read the PR:

+ This should only work with the HTML backend:
  + It has something to do with the HTML header/footer
  + It's pointless to generate LaTeX/GHC/JS with comments not preserved
+ This will prevent the HTML renderer from escaping the non-Agda-code characters, so markdown symbols like `>` will be preserved as-is
+ This will remove the HTML header/footer in the generated file.

**Comment by asr** [comment]
@vlopezj, please add the 2.6.0 milestone.
