### ISSUE TITLE
Result splitter introduces pattern variable that conflicts with constructor

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3138]
```agda
open import Agda.Builtin.Bool

test : (true : Set) → Set
test = ?  -- split on result here
```
produces
```
test true = ?

Cannot split on argument of non-datatype Set
when checking that the pattern true has type Set
```
This might be confusing in situations where a library is imported that defines a constructor the user is not aware of, and (s)he shadows it by accident.

I'd expect Agda to generate pattern variable `true'` instead.
It seems that in checking for taken names when picking name variants, we should not only look into the context but also in the scope.

**Comment by nad** [comment]
Perhaps this issue can be merged with #2522.
