### ISSUE TITLE
Possible Problem with Data.Colist Compilation and the Compiler

### ISSUE THREAD

**Issue by alhassy** [agda/agda#3145]
When I attempt to compile and execute a large program, I encounter

Compilation error:

    /home/musa/trunk/MAlonzo/Code/Data/Colist.hs:295:11:
    Couldn't match type ‘MAlonzo.RTE.Inf (T48 xa xA)’ with ‘[xA]’
    Expected type: xA
                   -> MAlonzo.RTE.Infinity xa (T48 xa xA) -> T48 xa xA
      Actual type: xA -> [xA] -> [xA]
    Relevant bindings include
      check60 :: xA -> MAlonzo.RTE.Infinity xa (T48 xa xA) -> T48 xa xA
        (bound at /home/musa/trunk/MAlonzo/Code/Data/Colist.hs:295:1)
    In the expression: (:)
    In an equation for ‘check60’: check60 = (:)

As such, I went to my copy of the standard library and observed

    $ agda --compile --no-main Data/Colist.agda
    Calling: ghc -O -Werror -i/usr/local/packages/agda-stdlib/src /usr/local/packages/agda- 
    stdlib/src/MAlonzo/Code/Data/Colist.hs --make -fwarn-incomplete-patterns -fno-warn-overlapping- patterns

Okay, this is strange but I'll live with generated working Haskell code, so I simple tried `--no-main` on my large file of interest and then encountered an unexpected out of scope issue. I tracked that down and have reproduced how that issue came about:

    module Data.Nat.Fixme where   -- my personal file

    open import Data.Nat
    open import Data.Nat.Properties as NatP

    ≤′-suc-≤ : {m n : ℕ} → m ≤′ n → suc m ≤ suc n
    ≤′-suc-≤ p = s≤s (NatP.≤′⇒≤ p)

Then,

    $ NAME=Data/Nat/Fixme; time agda --compile --no-main $NAME.lagda
    Checking Data.Nat.Fixme (/home/musa/trunk/Data/Nat/Fixme.lagda).
    Compiling Data.Nat.Fixme in /home/musa/trunk/Data/Nat/Fixme.agdai to 
    /home/musa/trunk/MAlonzo/Code/Data/Nat/Fixme.hs
    Calling: ghc -O -Werror -i/home/musa/trunk /home/musa/trunk/MAlonzo/Code/Data/Nat/Fixme.hs --make -fwarn-incomplete-patterns -fno-warn-overlapping-patterns
    [55 of 55] Compiling MAlonzo.Code.Data.Nat.Fixme ( /home/musa/trunk/MAlonzo/Code/Data/Nat/Fixme.hs, /home/musa/trunk/MAlonzo/Code/Data/Nat/Fixme.o )
    Compilation error:

    /home/musa/trunk/MAlonzo/Code/Data/Nat/Fixme.hs:26:8:
        Not in scope: ‘MAlonzo.Code.Data.Nat.Properties.du1318’
        Perhaps you meant one of these:
          ‘MAlonzo.Code.Data.Nat.Properties.d1318’ (imported from MAlonzo.Code.Data.Nat.Properties),
          ‘MAlonzo.Code.Data.Nat.Properties.du1518’ (imported from MAlonzo.Code.Data.Nat.Properties),
          ‘MAlonzo.Code.Data.Nat.Properties.du1214’ (imported from MAlonzo.Code.Data.Nat.Properties)

This is very disconcerting. Have I performed something erroneous or is this an actual issue?

Thank-you.

---

I'm using Agda version 2.5.4 and as a precautionary measure I just did a `git pull` on the standard library and tried compiling `Fixme` above to only be surprised with:

    [33 of 56] Compiling MAlonzo.Code.Data.Vec ( MAlonzo/Code/Data/Vec.hs, MAlonzo/Code/Data/Vec.o )
    Compilation error:

    MAlonzo/Code/Data/Vec.hs:160:22:
        Not in scope: ‘MAlonzo.Code.Data.Product.du184’
        Perhaps you meant one of these: ...

    MAlonzo/Code/Data/Vec.hs:459:22:
        Not in scope: ‘MAlonzo.Code.Data.Product.du184’

I'm just at a loss of what's going on. Any calming words would be appreciated!

**Comment by gallais** [comment]
I can't reproduce the issue when running `agda --compile --no-main Data/Colist.agda`
with `2.5.4` and the latest `agda-stdlib` (on the `master` branch).

Your error seems to be related to the change in #2909 but the stdlib was made
compatible with https://github.com/agda/agda-stdlib/commit/05c75c6fa0c6be74103e46186e183b7938272696

**Comment by gallais** [comment]
@alhassy I've pushed a patch on agda-stdlib's master branch. Can you pull it
and check it fixes your problem?

**Comment by nad** [comment]
Would it make sense to transfer this issue to https://github.com/agda/agda-stdlib?

**Comment by gallais** [comment]
If we can reproduce the bug and make sure the error comes from the stdlib, sure.
But so far it's not clear.

The `Not in scope` error for a `dN` looks pretty suspicious IMO: these definitions
are generated by Agda, not sourced from a FOREIGN pragma. It would have to
come from a bug in the compiler (?).

**Comment by UlfNorell** [comment]
It would help with a reproducible test case. Standard library commit where `Data.Colist` fails would be sufficient.

**Comment by UlfNorell** [comment]
I'm closing this for failure to reproduce. Reopen if needed.
