### ISSUE TITLE
Should inference fail here?

### ISSUE THREAD

**Issue by SimonBoulier** [agda/agda#3146]
When compiling the following, the last line is yellow.
If I fill the underscores (by `r n (f tt)`) it compiles correctly.
Should Agda be able to infer those arguments?
The type of `r _ _` is `R n (f tt)` so it seems simple...

```
record ⊤ : Set where
  constructor tt

data ℕ : Set where
  zero : ℕ
  suc : ℕ → ℕ

-- ⊤ⁿ is ⊤ → ⊤ ... → ⊤ n times
⊤ⁿ : ℕ → Set
⊤ⁿ zero = ⊤
⊤ⁿ (suc b) = ⊤ → ⊤ⁿ b

-- R n x is in fact always ⊤
R : (n : ℕ) → ⊤ⁿ n → Set
R zero _ = ⊤
R (suc n) f = R n (f tt)

-- r a x is in fact always tt
r : (a : ℕ) → (x : ⊤ⁿ a) → R a x
r zero _ = tt
r (suc n) f = r _ _
```

(tested with Agda master 20a08f0)

**Comment by SimonBoulier** [comment]
A still simpler example:
```
-- R n x is in fact always ⊤
R : (n : ℕ) → Set
R zero = ⊤
R (suc n) = R n

-- r n is in fact always tt
r : (n : ℕ) → R n
r zero = tt
r (suc n) = r _
-- r (suc n) = r n
```

**Comment by UlfNorell** [comment]
There's nothing forcing a solution of those arguments. In the first case a possible solution is
```agda
r : (a : ℕ) → (x : ⊤ⁿ a) → R a x
r zero    _ = tt
r (suc n) f = r (suc n) f
```
This doesn't pass termination checking, but the constraint solver does not rule out solutions based on termination. The same is true in the second example.

**Comment by SimonBoulier** [comment]
Ok thank you, it far less obvious in my real use case. Maybe I simplified too much the example, I'll have a deeper look.
