### ISSUE TITLE
Non-linear as-patterns

### ISSUE THREAD

**Issue by bafain** [agda/agda#3147]
Consider the following function definition, which is accepted by `Agda version 2.6.0-20a08f0` (and `Agda version 2.5.4` but not `Agda version 2.5.3`).

```Agda
module Scratch where

open import Agda.Builtin.Equality
open import Agda.Builtin.Nat

f : Nat → Nat
f zero      = zero
f x@(suc x) = x    -- rhs context:
                   -- x : Nat
                   -- x : Nat
```

Does it define the identity function or the predecessor function?

```Agda
f-id-1 : f 1 ≡ 1
f-id-1 = {!refl!}

f-pre-1 : f 1 ≡ 0
f-pre-1 = {!refl!}
```

As expected, the definition gets rejected after inserting a dot before the second occurrence of `x`.

```Agda
f' : Nat → Nat
f' zero       = zero
f' x@(suc .x) = x    -- line 18
```
```
Scratch.agda:18,11-12
suc ;n != ;n of type Nat
when checking that the given dot pattern x matches the inferred
value ;n
```

Is this related to what @jespercockx writes [on the mailing list](https://lists.chalmers.se/pipermail/agda/2017/009840.html)

> In the current development version the implementation is still a bit too liberal [with respect to allowing to omit dots in front of variables] and allows you to write `x` in place of any dot pattern `.t`, but this will be fixed before the next release.

and [on issue #2284](https://github.com/agda/agda/issues/2284#issuecomment-392805880)

> [The LHS] can contain multiple equal names, in which case all but one are treated as dot patterns. I guess for lambda and pi it makes more sense to throw the error during scope checking already.

or desired shadowing behaviour?

P.S.: Consider also the following function definitions.

```Agda
g : Nat → Nat → Nat
g x@y x@z = x       -- rhs context as above

g-snd : ∀ {a b} → g a b ≡ b
g-snd = refl

g' : Nat → Nat → Nat
g' x@y x = x

g'-snd : ∀ {a b} → g' a b ≡ b
g'-snd = refl

g'' : Nat → Nat → Nat
g'' x x@z = x         -- the variable name shadows the as-pattern name

g''-fst : ∀ {a b} → g'' a b ≡ a
g''-fst = refl

-- g''' : Nat → Nat → Nat
-- g''' x x = x           -- error:
--                        -- x₁ != x of type Nat

g'''' : Nat → Nat → Nat
g'''' = λ x x → x       -- cf. issue #2284

g''''-snd : ∀ {a b} → g'''' a b ≡ b
g''''-snd = refl
```

**Comment by andreasabel** [comment]
It seems that as-patterns were forgotten about when the linearity check for variables on the lhs was dropped in favor of a more subtle mechanism.

UPDATE: the linearity check succeeds wrongly since the as-variable and the pattern-variable get different name ids by the scope checker and thus are regarded different by the new linearity check.
```
lhs: final checks with remaining equations
  x = suc @0 : Nat
  x = @0 : Nat
Checking linearity of pattern variables
linearity: checking pattern  x  equal to term  suc x
pattern variable x with id 4@16847632796972593596
linearity: checking pattern  x  equal to term  x
pattern variable x with id 6@16847632796972593596
```

**Comment by andreasabel** [comment]
Fixed by regarding as-bound variables just as pattern variables in the scope checker.
