### ISSUE TITLE
Option --type-in-type and NO_UNIVERSE_CHECK pragma

### ISSUE THREAD

**Issue by asr** [agda/agda#3150]
This code type-checks

```agda
{-# OPTIONS --type-in-type #-}

-- {-# NO_UNIVERSE_CHECK #-}
data U : Set

El : U → Set

data U where
  set : U

El set = Set
```

but replacing the `--type-in-type` option by the `NO_UNIVERSE_CHECK` pragma generates the error

```
Set₁ != Set
when checking that the expression Set has type Set
```

Based on [this](https://github.com/agda/agda/blob/0ad14b893cb463ddeb2e9959aba899bb67867a6b/test/Succeed/CompileTimeInlining.agda) test case.

@jespercockx, for helping with your procrastination I assigned you this issue :-).

**Comment by UlfNorell** [comment]
`NO_UNIVERSE_CHECK` only disables the size check on data and record types. It doesn't (and shouldn't) give you `Set : Set`.

**Comment by UlfNorell** [comment]
In this example you can put `El` in `Set₁`:

```agda
{-# NO_UNIVERSE_CHECK #-}
data U : Set

El : U → Set₁

data U where
  set : U
  pi : (a : U) → (El a → U) → U

El set = Set
El (pi a b) = (x : El a) → El (b x)
```

**Comment by asr** [comment]
I see. Thanks!
