### ISSUE TITLE
`give` in a do-block inserts spurious parentheses

### ISSUE THREAD

**Issue by gallais** [agda/agda#3152]
Using `give` in the following hole gets us `(f a)` instead of `f a`.

```agda
postulate
  M : Set → Set
  _>>=_ : ∀ {A B} → M A → (A → M B) → M B

expr : ∀ {A} → (A → M A) → (A → M A)
expr f a = do
  x ← {!f a!}
  f a
```

**Comment by andreasabel** [comment]
@UlfNorell : I looked at this but failed to see why Agda behaves like this.  I couldn't reproduce it with manual do-desugaring.
