### ISSUE TITLE
Type checker fails to infer missing signature of module parameter.

### ISSUE THREAD

**Issue by sstucki** [agda/agda#3153]
The following example type checks using Agda 2.6.0 but not using Agda 2.5.4:

```agda
module _ where

open import Data.Nat
open import Relation.Unary using (Pred)

data D (T : ℕ → Set) : Set where
  c : ∀ {n} (t : T n) → D T

record Foo {ℓ} (T : Pred ℕ ℓ) : Set ℓ where
  field foo : ∀ {n} → T n → T (suc n)

module M {T} (r : Foo T) where
  open Foo r public

  fooD : D T → D T
  fooD (c t) = c (foo t)
```

In 2.5.4, the type checker fails to infer the type/level of the parameter`T` of module `M`. In 2.6.0 it manages to infer the type correctly.

(Reporting this [as requested by @asr](https://github.com/agda/agda/issues/3148#issuecomment-402781412) when discussing #3148.)

**Comment by nad** [comment]
@asr, did you intend to add a test case?

**Comment by asr** [comment]
Yes.

**Comment by UlfNorell** [comment]
This failure is due to #1063, which we already have a test case for.
