### ISSUE TITLE
'make install' adds wrong agda-mode binary to .emacs

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#3154]
With the current master branch, 'make install' installs the binaries 'agda-2.6.0' and 'agda-mode-2.6.0' in .cabal/bin, but in the code added to the .emacs file it refers to 'agda-mode' instead of 'agda-mode-2.6.0', which causes emacs to fail loading the agda mode or use the wrong version.

**Comment by WolframKahl** [comment]
Perhaps installation could test whether the `bindir`already contains executables named `agda` and `agda-mode`, and if not, produce links or copies of the `*-2.6.0` executables.

(My habit is to install different versions of Agda into different prefixes; this somewhat biases my proposal...)

**Comment by jespercockx** [comment]
I don't really understand what you're proposing, shouldn't 'make install' just install agda with the configured prefix ('-2.6.0' in this case) and then configure emacs to use that version? If you want something else there is 'make install-bin' and then you can do the emacs setup yourself.

**Comment by nad** [comment]
I commented on the commit (18743484d0a0f01e068287fe50a465d8e0044699) that introduced this problem:
> We did not use a program suffix on the old master branch. If we're going to use a suffix, then I suggest that we should also set up the Emacs mode so that it uses the installed binary (I think we used to do this on the old stable branch). However, I'd prefer to drop the suffix.

**Comment by nad** [comment]
Ulf replied:
> The idea was that we should use the current master in the same way as we used stable before. The emacs mode knows about versions (`agda2-mode-set-program-version` or something), are you saying that this doesn't default to the correct version?

By default the Emacs mode uses `agda`. You can switch to another version, but I find it annoying to have to do that every time I want to use the latest development version (which I often do). Now, if you download the master branch and run `make install`, then chances are that the Emacs mode does not work, or that it uses some other version of Agda.

I suggest that we install `agda`, without a suffix, until we go back to two branches.

I wrote:
> I think we used to do this on the old stable branch

I think I was mistaken about this.

**Comment by gallais** [comment]
What's wrong with adding a symbolic link from `agda` to `agda-VERSION`?

**Comment by nad** [comment]
> What's wrong with adding a symbolic link from `agda` to `agda-VERSION`?

It could be confusing to early adopters who are used to cloning the repo and running `make install`. If we decide to change the meaning of `make install`, then this should at least be documented in the changelog. Perhaps the command itself should also print a warning:
```
WARNING: Installed agda-X.Y.Z. The Emacs mode by default uses agda.
```
However, I don't see why we should complicate things for early adopters.

**Comment by gallais** [comment]
Good points. I suppose we could have `make install` do what it used to do and e.g.
`make install-with-suffix` offer the new behaviour.

**Comment by andreasabel** [comment]
Problem originated in work on #3104.

**Comment by nad** [comment]
A related problem: I ran `make install-prof-bin` now, and the installed binary was called `agda-2.6.0`, not `agda_p` or `agda_p-2.6.0`. I think that this regression was also caused by 18743484d0a0f01e068287fe50a465d8e0044699.
