### ISSUE TITLE
Generalization should also generalize name variants

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3165]
```
variable  Γ : Cxt
```
should also generalize name variants like `Γ₁` `Γ'` etc.

**Comment by nad** [comment]
How do you define "name variants"? Is `map` a variant of `m`? I think some people want to use the same scoping rules for generalisable names as for regular definitions. In that case, should it be possible to import a name but hide a variant of it?

Without further arguments I am negative towards this change.
