### ISSUE TITLE
Regression due to Prop: X <= Set does not force X = Set

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3167]
Definitions like `Wrap` used to be fine.  But even with `--no-prop` I get yellow now:
```agda
{-# OPTIONS --no-prop #-}

data Wrap A : Set where
  wrap : A → Wrap A

-- Failed to solve the following constraints:
--   _4 =< Set
--   Has bigger sort: _4
```

**Comment by WolframKahl** [comment]
I wouldn't even have thought that that definition of `Wrap` would be legal.

I wouldn't be opposed to remove it from the language (if it is indeed currently specified as legal) and require the parameter type declaration.

**Comment by identicalsnowflake** [comment]
@WolframKahl 

Really? If the meta is constrained to where Agda can see there's only one valid solution, it should choose that solution. If you abandon that principle, how do you decide which metas Agda should solve and which ones it should force you to annotate even though it knows the solution? The tricky thing in OP is just, as I understand, that whether there is a unique solution in the example depends on whether or not you have the pragma enabled.

**Comment by jespercockx** [comment]
Well, I removed this heuristic in https://github.com/agda/agda/commit/d04e62b03c4701af3aec408c3ece74e3ca5e6471#diff-0b7812ea54e58cd0d7d4d5f8209f5557 so if you want to add it back that should be easy enough.

That being said, I think we should keep it as it is now. The old heuristic assumed that `Set0` was the *only* bottom sort, which is invalidated by `Prop`, but would *also* prevent the addition of other sorts such as `SizeUniv`, `LevelUniv`, `FibrantSet`, ... I don't think saving 8 characters is worth it not being able to add any of these (or only adding them under some flags).

**Comment by WolframKahl** [comment]
@identicalsnowflake , I'd consider my point as independent of the unique valid solution principle you raise, since you always can write `_` in such places; here it would be:
```agda
data Wrap (A : _) : Set where
  wrap : A → Wrap A
```
(Which however currently does not have a unique solution for the meta induced by the underscore.)

**Comment by nad** [comment]
> Well, I removed this heuristic in [...]

Is the change documented in the changelog?

**Comment by andreasabel** [comment]
I think backward-compatibility should not be broken needlessly.  There were already 2 dozen cases in the testsuite that used this feature, shouldn't this have raised some alarms that user code there in the wild could be affected by this regression?!

I think that if the user works in a type theory where `Set` is the only bottom sort, then `X <= Set` should solve `X` to the bottom sort.

Also, what it the point of `--no-prop` other than exactly having this feature back?

- [x] Document change of universe solver in the release notes.
- [x] Restore behavior for scenarios where `Set` is the only bottom sort.
- [x] Document `--no-prop` in the release notes.

**Comment by andreasabel** [comment]
> Well, I removed this heuristic in d04e62b#diff-0b7812ea54e58cd0d7d4d5f8209f5557 so if you want to add it back that should be easy enough.

Indeed a partial revert did the job.
