### ISSUE TITLE
Irrelevant Variables not being used for case coverage?

### ISSUE THREAD

**Issue by oisdk** [agda/agda#3168]
When I translated some code over from Haskell recently, I marked all the type parameters as irrelevant in the Agda version, as I assumed that they *had* to be irrelevant (because they'd been simple type parameters in Haskell).

When I do, though, Agda seems to not realise that some cases are impossible. Take, for instance, natural numbers and their singletons:

```agda
data ℕ : Set where
  z : ℕ
  s : ℕ → ℕ

data Nat : .ℕ → Set where
  Z : Nat z
  S : ∀ .{n} → Nat n → Nat (s n)

record ⊤ : Set where

onlyZero : Nat z → ⊤
onlyZero Z = record {}
```

I get a missing case error on the last line that I *don't* get either in the equivalent Haskell code, or when I remove the irrelevance marks. I'm pretty sure I could construct a `⊥` somewhere to eliminate that case, but it would be nicer to have it catch the case straight off.

**Comment by UlfNorell** [comment]
By marking the index as irrelevance *in the type* of `Nat` you are saying that `Nat m = Nat n` for any `n` and `m`, which is not what you intended. Indeed:

```agda
data ℕ : Set where
  z : ℕ
  s : ℕ → ℕ

data Nat : .ℕ → Set where
  Z : Nat z
  S : ∀ .{n} → Nat n → Nat (s n)

record ⊤ : Set where

notOnlyZero : Nat z
notOnlyZero = S Z
```
