### ISSUE TITLE
Doc for rewriting

### ISSUE THREAD

**Issue by gallais** [agda/agda#3169]
It seems to be a bit of a shame that we have some [nice doc about rewrite](https://agda.readthedocs.io/en/latest/language/with-abstraction.html#rewrite) but users
are [presented with a stub](https://agda.readthedocs.io/en/latest/language/rewriting.html) if they look at the wrong spot.

Can we put in place at least a link if not a redirection?

(I would have looked into it but the version of sphinx available on debian stable is too
old to be able to make the docs...)

**Comment by nad** [comment]
Perhaps the page pointed to by the first link is supposed to discuss the feature enabled by `--rewriting`, not the `rewrite` keyword. (I did not pick those names.)

**Comment by asr** [comment]
> I would have looked into it but the version of sphinx available on debian stable is too
old to be able to make the docs...)

To locally install Sphinx and sphinx-rtd-theme (from https://github.com/agda/agda/blob/master/HACKING):

       $ pip install --user -r doc/user-manual/requirements.txt

      Note that the `--user` option puts the Sphinx binaries in
      `$HOME/.local/bin`.

**Comment by gallais** [comment]
> Perhaps the page pointed to by the first link is supposed to discuss the feature enabled by --rewriting, not the rewrite keyword. (I did not pick those names.)

Now that you say it, it seems evident!

**Comment by UlfNorell** [comment]
Still, having a *"this is the stub for `--rewriting`, look here for documentation on the `rewrite` keyword"* wouldn't be a terrible idea.
