### ISSUE TITLE
Top-level commands executed in the wrong context

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#317]
```agda
module Bug (A : Set) where

postulate F : Set → Set

-- Try evaluating F A at the top-level:
--
-- 1,3-4
-- Not in scope:
--   A at 1,3-4
-- when scope checking A
--
-- OK, in that case the inferred type of F should be
-- (A : Set) → Set → Set, right? No, it isn't, it's Set → Set.
--
-- I think the parameters should be in scope when "top-level" commands
-- are executed, because these commands should behave in the same way
-- as commands executed in a top-level goal at the end of the module.
-- It seems as if the implementation of
-- Agda.Interaction.BasicOps.atTopLevel has to be modified.

```

Original issue reported on code.google.com by `nils.anders.danielsson` on 19 Sep 2010 at 11:02

**Comment by andreasabel** [comment]
Related patch: https://github.com/agda/agda/commit/e623e6e3aeb963c1352241f7b3eb1390762df86b. But I guess this is the original implementation of `atTopLevel` which got improved by this issue #317.

Patch fixing this issue: 2714d60bb536d04213589c5737407ca34d39d2de.

This fix no longer works, thanks to let-bindings in module telescopes, see #2552.
