### ISSUE TITLE
UnicodeDeclare fails with pdflatex from TeX Live 2018

### ISSUE THREAD

**Issue by nad** [agda/agda#3170]
The `UnicodeDeclare` test case is not built correctly by pdflatex when TeX Live 2018 is used:
```
! Undefined control sequence.
l.5 \DeclareUnicodeCharacter
                            {9711}{$\bigcirc$}
```

**Comment by nad** [comment]
See #3224.

**Comment by UlfNorell** [comment]
[StackExchange](https://tex.stackexchange.com/questions/161491/problem-with-defining-new-unicode-character?rq=1) suggests using [`newunicodechar`](https://ctan.org/pkg/newunicodechar?lang=en) instead of `DeclareUnicodeCharacter`.

**Comment by nad** [comment]
From the [documentation](http://mirrors.ctan.org/macros/latex/contrib/newunicodechar/newunicodechar.pdf) of newunicodechar: The package "won’t work with the utf8x option".

**Comment by UlfNorell** [comment]
I disabled the `DeclareUnicodeCharacter` tests for now.
