### ISSUE TITLE
Could not parse with pattern

### ISSUE THREAD

**Issue by ice1000** [agda/agda#3172]
Simple, minimum code to reproduce the error:

```agda
parseF : List ℂ → List Fmt
parseF [] = []
parseF (x ∷ xs) with xs | x ≟ '%'
...         | '%' ∷ xss | (yes y) = {!!}
```

The code above uses these declarations:

```agda
open import Data.List using (List; _∷_; [])
open import Data.Char renaming (Char to ℂ; show to showℂ)

data Fmt : Set where
  fmt : ℂ → Fmt
  lit : ℂ → Fmt
```

If I change `(yes y)` to `y`, the parser works. But I need to pattern match on `x ≟ '%'`, how can I do that?

**Comment by ice1000** [comment]
And of course use `C-c C-c` to do a case split on `y` causes a parse error:

```agda
parseF : List ℂ → List Fmt
parseF [] = []
parseF (x ∷ xs) with xs | x ≟ '%'
parseF (x ∷ xs) | '%' ∷ xss | .Relation.Nullary.Dec.yes p = ?
parseF (x ∷ xs) | '%' ∷ xss | .Relation.Nullary.Dec.no ¬p = ?
```

**Comment by gallais** [comment]
You need to `open import Relation.Nullary` so that `yes` is in scope. Otherwise Agda
does not know about `yes` and thinks you are trying to declare a pattern of the form
`(function argument)` which is illegal.

**Comment by ice1000** [comment]
Ok thanks

**Comment by ice1000** [comment]
@gallais And BTW why Agda complains about the termination of this function?

```agda

parseF : List ℂ → List Fmt
parseF [] = []
parseF (x ∷ xs) with xs | x ≟ '%'
...         | '%' ∷ xss | yes _ = lit '%' ∷ parseF xss
...         |  c  ∷ xss | yes _ = fmt c ∷ parseF xss
...         | [] | yes _ = lit '%' ∷ []
...         | _  | no  _ = lit x ∷ parseF xs
```

![image](https://user-images.githubusercontent.com/16398479/43678170-bc5a5292-9840-11e8-8b6b-730f1bc2b788.png)

**Comment by ice1000** [comment]
While the normal form checks:

```agda
parseF : List ℂ → List Fmt
parseF [] = []
parseF ('%' ∷ '%' ∷ cs) = lit '%' ∷ parseF cs
parseF ('%' ∷  c  ∷ cs) = fmt c ∷ parseF cs
parseF ( c  ∷  cs) = lit c ∷ parseF cs
```

**Comment by ice1000** [comment]
Moved discussion to #3173
