### ISSUE TITLE
Difference between Decidable and Equality 

### ISSUE THREAD

**Issue by ice1000** [agda/agda#3173]
With this code (which uses some declarations listed in #3172 ):

```agda

parseF : List ℂ → List Fmt
parseF [] = []
parseF (x ∷ xs) with xs | x ≟ '%'
...         | '%' ∷ xss | yes _ = lit '%' ∷ parseF xss
...         |  c  ∷ xss | yes _ = fmt c ∷ parseF xss
...         | [] | yes _ = lit '%' ∷ []
...         | _  | no  _ = lit x ∷ parseF xs
```

Agda complains about the termination of the function:

![image](https://user-images.githubusercontent.com/16398479/43678170-bc5a5292-9840-11e8-8b6b-730f1bc2b788.png)

While the one using Equality checks:

```agda
parseF : List ℂ → List Fmt
parseF [] = []
parseF ('%' ∷ '%' ∷ cs) = lit '%' ∷ parseF cs
parseF ('%' ∷  c  ∷ cs) = fmt c ∷ parseF cs
parseF ( c  ∷  cs) = lit c ∷ parseF cs
```

**Comment by gallais** [comment]
The problem is not the difference between using a pattern vs. a decision procedure for equality
but the `with xs` which adds one level of indirection between `xs` and the recursive call. This
prevents Agda from seeing that the call is legal.

A solution would be to drop `with xs` entirely (not tested):

```agda
parseF : List ℂ → List Fmt
parseF [] = []
parseF (x ∷ xs) with x ≟ '%'
parseF (x ∷ '%' ∷ xss) | yes _ = lit '%' ∷ parseF xss
parseF (x ∷ c   ∷ xss) | yes _ = fmt c ∷ parseF xss
parseF (x ∷ [])        | yes _ = lit '%' ∷ []
...                    | no  _ = lit x ∷ parseF xs
```

**Comment by gallais** [comment]
Note that issues are probably not the best place to discuss these type of things:
they are used to track bugs and them getting fixed.

For questions, the mailing list (https://lists.chalmers.se/mailman/listinfo/agda) and stackoverflow are probably more appropriate

**Comment by ice1000** [comment]
I know, I thought it's a bug. Now it's clear, thanks for your explanation.

Is it expected that there's a difference between with `with pattern` and without `with pattern`? I think this sounds strange.

**Comment by andreasabel** [comment]
`with` creates an auxiliary function, and all kinds of mangling happens.
In your case there is no reason to do `with xs`, since you can use ordinary pattern matching.

**Comment by gallais** [comment]
Let me throw in [the really good docs about with-abstraction](https://agda.readthedocs.io/en/latest/language/with-abstraction.html) which even include an
explanation of how they are elaborated away!

**Comment by ice1000** [comment]
Thanks @andreasabel @gallais
