### ISSUE TITLE
How to pass the latex-html-test?

### ISSUE THREAD

**Issue by banacorn** [agda/agda#3179]
I've managed to pass all tests listed in the Makefile
```Makefile
.PHONY : test
test : check-whitespace succeed fail interaction examples library-test interactive latex-html-test api-test internal-tests benchmark-without-logs compiler-test lib-succeed lib-interaction user-manual-test test-size-solver
```

Except for the `latex-html-test`, where I would fail all of the `_LaTex` and `_QuickLaTex` tests, with golden and actual result like this:

```bash
diff --git a/private/var/folders/h9/y58_wdxn5p34b5d76ms1f1lc0000gn/T/AccidentalSpacesAfterBeginCode_LaTeX44092-0.golden b/private/var/folders/h9/y58_wdxn5p34b5d76ms1f1lc0000gn/T/AccidentalSpacesAfterBeginCode_LaTeX44092-1.actual
index f478bcf74..6294a0e55 100644
--- a/private/var/folders/h9/y58_wdxn5p34b5d76ms1f1lc0000gn/T/AccidentalSpacesAfterBeginCode_LaTeX44092-0.golden
+++ b/private/var/folders/h9/y58_wdxn5p34b5d76ms1f1lc0000gn/T/AccidentalSpacesAfterBeginCode_LaTeX44092-1.actual
@@ -1,13 +1 @@
-\documentclass{article}
-
-\usepackage{agda}
-
-\begin{document}
-
-\begin{code}     %
-\>[0]\AgdaKeyword{module}\AgdaSpace{}%
-\AgdaModule{AccidentalSpacesAfterBeginCode}\AgdaSpace{}%
-\AgdaKeyword{where}\<%
-\end{code}
-
-\end{document}
+LATEX_COMPILE_FAILED with lualatex, xelatex, pdflatex
\ No newline at end of file
(END)
```

Is there anything I should be aware of if I'm getting `LATEX_COMPILE_FAILED with lualatex, xelatex, pdflatex`?

The version of Agda I'm testing on is  https://github.com/agda/agda/commit/67f316e0a5b52bf4043a0e1127c4ec5b7817dd1e on `master`

* LuaTeX: Version 1.0.4 (TeX Live 2017)
* XeTex: Version 3.14159265-2.6-0.99998 (TeX Live 2017)
* pdfTex: Version 3.14159265-2.6-1.40.18 (TeX Live 2017)
* GHC: 8.4.3
* System Version: macOS 10.13.6 (17G65)
* Kernel Version: Darwin 17.7.0

**Comment by andreasabel** [comment]
> Is there anything I should be aware of if I'm getting LATEX_COMPILE_FAILED with lualatex, xelatex, pdflatex?

Yes, you should try to find out why latex compilation fails.

Possibly related: #3170.

**Comment by banacorn** [comment]
I guess the test failed because it doesn't know where to find `agda.sty`.

There's a [line](https://github.com/agda/agda/blob/master/test/LaTeXAndHTML/Tests.hs#L178) in `test/LaTeXAndHTML/Tests.hs` where it would try to execute commands like this:
```
xelatex -interaction=errorstopmode PatternSynonyms.tex
```

And when I execute this command by myself, `xelatex` would halt and ask me for the path of `agda.sty`. If I add `agda.sty` manually to my system, it would ask for more `.sty` dependencies of `agda.sty`.

Is there a way of reproducing a stable testing environment so that LaTeX/XeLaTeX/LuaLaTeX would have the `.sty` file they need and we can run those tests? 

I've noticed that [LaTeX/XeLaTeX/LuaLaTeX is not ran on Travis](https://github.com/agda/agda/blob/master/.travis.yml#L336-L342), should I do the same when I'm running the tests?

**Comment by asr** [comment]
I guess the problem is a missing LaTeX/XeLaTeX/LuaLaTeX package.

Do you get any error running the following commands:

```bash
$ cp test/LaTeXAndHTML/succeed/AccidentalSpacesAfterBeginCode.lagda /tmp/
$ cd /tmp
$ agda --latex AccidentalSpacesAfterBeginCode.lagda
$ cd latex
$ pdflatex AccidentalSpacesAfterBeginCode.tex
$ xelatex AccidentalSpacesAfterBeginCode.tex
$ lualatex AccidentalSpacesAfterBeginCode.tex
```

?

**Comment by asr** [comment]
> Possibly related: #3170.

No. Issue #3170 doesn't occur with TeX Live 2017. 

> I've noticed that [LaTeX/XeLaTeX/LuaLaTeX is not ran on Travis](https://github.com/agda/agda/blob/master/.travis.yml#L336-L342), should I do the same when I'm running the tests?


The LaTeX compilers were disabled on Travis due to the TeX Live version of Ubuntu was too old. You should can run the test on your machine using your current version of TeX Live (i.e. TeX Live 2017).

**Comment by banacorn** [comment]
```shell
$ cp test/LaTeXAndHTML/succeed/AccidentalSpacesAfterBeginCode.lagda /tmp/
$ cd /tmp
$ agda --latex AccidentalSpacesAfterBeginCode.lagda

Checking AccidentalSpacesAfterBeginCode (/private/tmp/AccidentalSpacesAfterBeginCode.lagda).
Finished AccidentalSpacesAfterBeginCode.
agda.sty was not found. Copying a default version of agda.sty
into latex.

$ cd latex/
$ pdflatex AccidentalSpacesAfterBeginCode.tex

This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./AccidentalSpacesAfterBeginCode.tex
LaTeX2e <2018-04-01> patch level 2
Babel <3.18> and hyphenation patterns for 22 language(s) loaded.
(/usr/local/texlive/2018basic/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/local/texlive/2018basic/texmf-dist/tex/latex/base/size10.clo))
(./agda.sty
(/usr/local/texlive/2018basic/texmf-dist/tex/generic/ifxetex/ifxetex.sty)
(/usr/local/texlive/2018basic/texmf-dist/tex/generic/oberdiek/ifluatex.sty)

! LaTeX Error: File `xifthen.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name:
```

**Comment by asr** [comment]
You need to install the `xifthen` package from your LaTeX distribution. After installing this package I guess you will find similar errors due to other missing packages.

**Comment by banacorn** [comment]
Thanks for the heads up! 

It would be wonderful if we can get everything we need on CTAN like:
```
tlmgr install agda
```

**Comment by asr** [comment]
> ```bash
> This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=pdflatex)
> restricted \write18 enabled.
> ```

As I said before, if you use TeX Live 2018 you will hit #3170.
