### ISSUE TITLE
Remove feature `--guardedness-preserving-type-constructors`

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3180]
Remove feature `--guardedness-preserving-type-constructors`.  Reasons: 
- No semantics for this experimental feature has emerged within a decade.
- I am not aware of serious applications.  
- It is crippled by a change to the termination checker fixing #1556.

One could look into Guarded Type Theory (by the Danish crowd: Birkedal & Møgelberg) if a similar feature is wanted.

**Comment by nad** [comment]
I see several traces of this feature in the code. Is there any reason to keep this code?

**Comment by nad** [comment]
I'll see if I can get rid of it.
