### ISSUE TITLE
agdai files should be put in seperate locations

### ISSUE THREAD

**Issue by riaqn** [agda/agda#3185]
Currently the `foo.agdai` is generated in the same directory as `foo.agda`, which could be problematic because `foo.agda` might be in a directory the user has no write access to.

Alternatively, we can hash the soruce file `foo.agda` and write the binary file to `$HOME/.agdai/$HASH.agdai`, where `$HOME` is user's home directory.

**Comment by gallais** [comment]
related: #2610

**Comment by andreasabel** [comment]
> Currently the foo.agdai is generated in the same directory as foo.agda

This is the solution commonly used in the past, see LaTeX, C, GHC etc.

> Alternatively, we can hash the soruce file foo.agda and write the binary file to $HOME/.agdai/$HASH.agdai, where $HOME is user's home directory.

This will silently eat the users disk space.

However, in connection with a built system we should look into a solution where the generated files (`.agdai`) are put into a distinct location (cf. the `cabal` approach).

**Comment by ice1000** [comment]
> This will silently eat the users disk space.

We can create a command line flag for that.

**Comment by ice1000** [comment]
I really want to work on this! Hope I have time.

**Comment by ice1000** [comment]
I asked the maintainer of https://tio.run to support Agda, and he's running into problems related to permission denied with stdlib's agdai files.

**Comment by asr** [comment]
Maybe #3128?

**Comment by ice1000** [comment]
Why is it related to #3128 ? Isn't #3128 about pre-checking builtin libraries?

**Comment by xekoukou** [comment]
Maybe use something like a union mount? 
https://en.wikipedia.org/wiki/UnionFS
https://en.wikipedia.org/wiki/Union_mount

It seems that you can union two directories, one read-only and the other writable. Maybe installation that require read-only installations could use it. I haven't tested it though.

**Comment by nad** [comment]
I suggest that we close this issue and move the discussion to #2610.

**Comment by ice1000** [comment]
Agreed
