### ISSUE TITLE
Panics when serialising absolute paths

### ISSUE THREAD

**Issue by nad** [agda/agda#3199]
I'm getting errors of the following kind (using Agda 2.5.4.1):
```
Panic while serializing absolute path: [...]
The path could not be found in the dictionary:

[...]
(agda2-info-action "*Error*" "An internal error has occurred. Please report this as a bug.\nLocation of the error: src/full/Agda/TypeChecking/Serialise/Instances/Common.hs:178\n" nil)
```
However, I have trouble replicating the errors consistently. Has anyone else seen this?

**Comment by gallais** [comment]
I have too. Haven't been able to reproduce consistently either and they go away when I restart Agda.

**Comment by m-yac** [comment]
Yes, I am also seeing this – the only fix I've found is just removing all `.agdai` files in stdlib.

Is this perhaps #2592 coming back from the dead? I ended up with the same testcases just with Data.Integer instead of Data.Empty...

**Comment by HuStmpHrrr** [comment]
I keep hitting the error from #3202 and #2592 these couple days which makes adding import extremely painful. This very often happens when adding a new import. I can reproduce it from following steps:

1. `cd ~/.agda/agda-stdlib && git clean -fdx`
2. create a new project:
```sh
mkdir -p ~/projects/test/src
cat <<EOF > ~/projects/test/src/Test.agda
module Test where
EOF
```
3. in emacs, open the file above, then `C-c C-l`. Add a line of import, say `open import Data.Nat`, then `C-c C-l`. The error is produced.

The error can be wiped, by entering `Date.nat`, `C-c C-l` over there, and then resume back to `Test.agda`. However, it would only work until the next import.

```
$ agda --version
Agda version 2.5.4.1-6b1d87f
```

**Comment by nad** [comment]
I failed to reproduce the error in (roughly) this way using Agda 2.5.4.1 and version 983e1487e67d02ff9f3ee79c74e4f959e98aa799 of the standard library.

**Comment by nad** [comment]
Did you restart Emacs (or the Agda mode) before following the steps above?

**Comment by HuStmpHrrr** [comment]
Restarting agda will make this error go away, until the next import.

Restarting emacs is a good point. Since I use emacs server, it's very often not my first attempt. After restarting emacs the problem did go away and hasn't shown up yet. Let me pay attention on what I do to produce the error.

**Comment by nad** [comment]
Are you saying that you see a difference between restarting Emacs and restarting the Agda mode (C-c C-x C-r)? Unless restarting Emacs leads to the use of new code for the Agda mode (perhaps because you have reinstalled Agda) I find this unlikely.

**Comment by HuStmpHrrr** [comment]
OK, let me precisely replicate my environment here:

1. 
```sh
zs2hu@rsg-pc326:~/projects/agda$ git rev-parse HEAD
d996dc16d3a0a09f0d0b35dbc613edde706906ea
zs2hu@rsg-pc326:~/projects/agda$ cat stack.yaml
resolver: lts-12.0

# Local packages, usually specified by relative directory name
packages:
- '.'
- 'src/fix-agda-whitespace'
- 'src/size-solver'

extra-deps:
- temporary-1.2.1.1
zs2hu@rsg-pc326:~/projects/agda$ stask install
# it's done
zs2hu@rsg-pc326:~/projects/agda$ cd ~/.agda/agda-stdlib/
zs2hu@rsg-pc326:~/.agda/agda-stdlib$ git clean -fdx
zs2hu@rsg-pc326:~/.agda/agda-stdlib$ cabal sandbox init
Writing a default package environment file to
/home/zs2hu/.agda/agda-stdlib/cabal.sandbox.config
Creating a new sandbox at /home/zs2hu/.agda/agda-stdlib/.cabal-sandbox
zs2hu@rsg-pc326:~/.agda/agda-stdlib$ mkdir -p ~/projects/test/src
zs2hu@rsg-pc326:~/.agda/agda-stdlib$ cat <<EOF > ~/projects/test/src/Test.agda
> module Test where
> EOF
```

2. Inside of emacs `GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 2.24.32) of 2018-08-29`, open `~/projects/test/src/Test`, then `C-c C-l`.

3. Add a line `open import Data.Nat`, `C-c C-l`
4. Add another line `open import Relation.Binary`, `C-c C-l`.

Then I can see the error message:
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Serialise/Instances/Common.hs:178
```

**Comment by HuStmpHrrr** [comment]
I just tried with other revision, and these steps do not produce the error:

```sh
$ git rev-parse HEAD
267fb6da4bf44b7b7b23433ab2eb2554285fb09c
```

The previous revision comes from `release-2.5.4.1` branch, so I guess it has something to do with that particular release?

**Comment by nad** [comment]
If you switch to another version of Agda, then the interface file format may be different, which has roughly the same effect as deleting all `.agdai` files. Note also that the Emacs mode caches information.

It would be helpful if you could get a script like the following one to trigger the error:
```haskell
#!/usr/bin/env runhaskell

{-# LANGUAGE RecordWildCards #-}

import System.Directory
import System.Process

import RunAgda

file       = "Bug.agda"
firstCode  = "module Bug where\n"
secondCode = firstCode ++ "open import Data.Nat\n"
thirdCode  = secondCode ++ "open import Relation.Binary\n"

main :: IO ()
main = runAgda [ "--no-default-libraries"
               , "--library-file=libs"
               ] $ \(AgdaCommands { .. }) -> do

  -- Clean up.
  system "cd agda-stdlib && git clean -fdx"
  removeFile $ file ++ "i"

  -- Discard the first prompt.
  echoUntilPrompt

  -- Create the file.
  writeUTF8File file firstCode

  -- Load the file, and wait for Agda to complete.
  loadAndEcho file

  -- Edit the file.
  writeUTF8File file secondCode

  -- Reload.
  loadAndEcho file

  -- Edit the file again.
  writeUTF8File file thirdCode

  -- Reload again.
  loadAndEcho file

  return ()
```
This script should be invoked as `runhaskell <Script.hs> <suitable version of Agda>`, with the standard library installed in `agda-stdlib` and the following three files present in the current directory:
* `libs`:
  ```
  $PWD/agda-stdlib/standard-library.agda-lib
  ```
* `bug.agda-lib`:
  ```
  name: bug
  depend: standard-library
  include: .
  ```
* The [at the time of writing latest version of `test/interaction/RunAgda.hs`](https://github.com/agda/agda/blob/23426acd6ee4e6101b897bb850d679a7488de5d9/test/interaction/RunAgda.hs).

**Comment by nad** [comment]
I forgot to mention that I failed to reproduce the error using the steps you gave above (using Agda 2.5.4.1 and a later version of Agda).

**Comment by HuStmpHrrr** [comment]
I will try to create this file. I might also try to create a raw vm so that my current environment can be isolated.

> If you switch to another version of Agda, then the interface file format may be different, which has roughly the same effect as deleting all .agdai files. Note also that the Emacs mode caches information.

I did `git clean -fdx` in stdlib folder. I think this has only things to do with agda 2.5.4.1 itself. The diff is small though, which makes it suspicious. Could it be a bug from upstream library?

**Comment by nad** [comment]
I doubt that anyone will try to make use of a VM, please don't put any time into that. I've noticed this bug a number of times myself when using the standard library under Agda 2.5.4.1. It's not hard to trigger the bug, but it seems to be hard to find a simple recipe for how to trigger it starting from a clean state. I suspect that it has something to do with one or more of the following features: `open public`, libraries, and (deprecation) warnings.

**Comment by MatthewDaggitt** [comment]
> I suspect that it has something to do with one or more of the following features: open public, libraries, and (deprecation) warnings.

I too think it has something to do with deprecation warnings. Since I've added them in, I've been getting this error quite a lot when messing around them. Likewise no luck reproducing it reliably though...

**Comment by EdNutting** [comment]
Hi,
I'm seeing this error a lot too, also with the latest master branch of stdlib (on Windows and Linux with respective latest release versions of Agda (through Cabal - 2.5.4.1)/Emacs). 

This might help give some clue: 

If I get the "internal error" message in Emacs when reloading it will keep showing the error no matter how many times I reload. Usually, I fix this by restarting Agda and everything is fine again for a short while.

However, I noticed that if I run "agda [Name of file that won't load]" in a terminal, it will compile just fine. If I then attempt to reload the file in Emacs (without having closed Emacs in between and without restarting Emacs instance of Agda), then the file loads fine again. 

So to me this looks like something on-disk is going out-of-sync with whatever internal cache Agda holds. The cache is presumably 'correct' since running a separate instance of Agda fixes whatever should be on disk.

I haven't managed to create a reliable repro case for this other than just using the standard library.

Hope this helps,
Ed

**Comment by gallais** [comment]
I have pushed a branch of agda-stdlib with no `WARNING_ON_USAGE` https://github.com/agda/agda-stdlib/tree/nowarning. Let's try to use that for a few days / weeks and see whether we still get panics.

Edit: And I have patched my version of Agda to see whether it does come from there:

```diff
diff --git a/src/full/Agda/TypeChecking/Serialise/Instances.hs b/src/full/Agda/TypeChecking/Serialise/Instances.hs
index e5bb89e15..901e5777c 100644
--- a/src/full/Agda/TypeChecking/Serialise/Instances.hs
+++ b/src/full/Agda/TypeChecking/Serialise/Instances.hs
@@ -3,6 +3,8 @@
 -- Only instances exported
 module Agda.TypeChecking.Serialise.Instances () where
 
+import Control.Monad.Reader
+
 import Agda.TypeChecking.Monad.Base
 import Agda.TypeChecking.Serialise.Base
 import Agda.TypeChecking.Serialise.Instances.Abstract ()
@@ -12,8 +14,12 @@ import Agda.TypeChecking.Serialise.Instances.Highlighting ()
 import Agda.TypeChecking.Serialise.Instances.Internal ()
 import Agda.TypeChecking.Serialise.Instances.Errors ()
 
+import Agda.Utils.Impossible
+
 instance EmbPrj Interface where
-  icod_ (Interface a b c d e f g h i j k l m n) = icodeN' Interface a b c d e f g h i j k l m n
+  icod_ (Interface a b c d e f g h i j k l m n) = do
+    xs <- icodeN' Interface a b c d e f g h i j k l m n
+    liftIO $ (xs `seq` pure xs) `catchImpossible` \ _ -> fail (show n)
 
   value = vcase valu where
     valu [a, b, c, d, e, f, g, h, i, j, k, l, m, n] =
diff --git a/src/full/Agda/TypeChecking/Serialise/Instances/Errors.hs b/src/full/Agda/TypeChecking/Serialise/Instances/Errors.hs
index 7118fdf5c..733266d35 100644
--- a/src/full/Agda/TypeChecking/Serialise/Instances/Errors.hs
+++ b/src/full/Agda/TypeChecking/Serialise/Instances/Errors.hs
@@ -4,6 +4,8 @@
 
 module Agda.TypeChecking.Serialise.Instances.Errors where
 
+import Control.Monad.Reader
+
 import Agda.TypeChecking.Serialise.Base
 import Agda.TypeChecking.Serialise.Instances.Common
 import Agda.TypeChecking.Serialise.Instances.Internal ()
@@ -26,7 +28,9 @@ import Agda.Utils.Lens
 import Agda.Utils.Impossible
 
 instance EmbPrj TCWarning where
-  icod_ (TCWarning a b c d) = icodeN' TCWarning a b c d
+  icod_ (TCWarning a b c d) = do
+    xs <- icodeN' TCWarning a b c d
+    liftIO $ (xs `seq` pure xs) `catchImpossible` \ _ -> fail (render c)
 
   value = valueN TCWarning

```

Edit2: still getting the crash. Is it really coming from user warnings?

Edit3: not getting the crash on the nowarning branch of the stdlib though. So it probably is coming from them. Weird.

Edit4: it may come from the fact I didn't make any distinction between imported warnings and locally defined ones. Meaning the interface would contain not only the user warnings declared locally but also *ALL* of the ones declared in (recursively) imported modules.

**Comment by gallais** [comment]
I've been working a bit on the stdlib and regularly switching between 2.5.4.1 and #3229
and when it takes less than a minute to get a panic in 2.5.4.1, I have yet to get one in
#3229 so I think it's fixed.

It would be nice to have a test case though. :/

**Comment by nad** [comment]
> We now only put the user warnings defined locally in the interface.

Are warnings encountered in imported files still displayed to the user?

**Comment by gallais** [comment]
Yes they are: [WarningOnUsage2](https://github.com/agda/agda/blob/master/test/Succeed/WarningOnUsage2.agda) makes sure of that.

I suppose the sentence is ambiguous: I was only talking about the *directive* to raise
a warning when a name is used. The warnings themselves are still handled the same
way as before.

**Comment by ice1000** [comment]
The same thing happens to me, looking forward to 2.5.4.2
