### ISSUE TITLE
Internal Error from Emacs Interaction

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda#3202]
I was having an error from emacs in following environment:

```
 ~/.agda/agda-stdlib $ git rev-parse HEAD
af18282d2740a96b8be8ea8eb4db056f28ab890b
 ~/.agda/agda-stdlib $ agda --version
Agda version 2.5.4.1-6b1d87f
```

Error message is following:

```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Serialise/Instances/Common.hs:178
```

I have error from the following code:

```agda
open import Relation.Binary
open import Relation.Binary.Core
open import Relation.Binary.PropositionalEquality as ≡ using (_≡_)

module Algebraic.Lattice {a ℓ} {A : Set a} {_≺_ : Rel A ℓ}
  (isPreorder : IsPreorder _≡_ _≺_)
  where

preorder : Preorder _ _ _
preorder = record { isPreorder = isPreorder }

open import Relation.Binary.Properties.Preorder preorder using (InducedEquivalence)
```

Commenting out the last line removes this error. Uncommenting again produces this error again.

**Comment by gallais** [comment]
This is #3199.

We have a hard time finding a reproducible test case. I tried this one and couldn't
get the error (I run a modified version of agda-mode because of the PR I just made
but I doubt it plays a role: it doesn't touch that part of the serializer).

**Comment by HuStmpHrrr** [comment]
This error seems caused by agdai files. `make clean` fixes it.
