### ISSUE TITLE
`accessible' for  ℕ

### ISSUE THREAD

**Issue by mechvel** [agda/agda#3203]
Please how to extract 
```<-acc :  {n : ℕ} →Acc _<_```
from `` Induction.Nat`` ?

I program it by
```
<-acc {0}        =  acc (\_ ())
<-acc {suc n}  with <-acc {n}
... | acc wf = acc f
                   where ...
```
, but probably it can be somehow imported from `` Induction.Nat``.

**Comment by UlfNorell** [comment]
This is not an appropriate forum for this question. Please address it to the mailing list, or as a last resort (if you believe there's a problem with the library) to the standard library issue tracker (https://github.com/agda/agda-stdlib/issues).
