### ISSUE TITLE
Use `-fwarn-incomplete-uni-patterns`

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3213]
We have since forever the GHC option `-fwarn-incomplete-patterns` to warn about incomplete pattern matching, using `__IMPOSSIBLE__` to complete matches.  However, we allow incomplete irrefutable patterns and sometimes the user will see an error message about a match failure rather than the official error message printed by `__IMPOSSIBLE__`.
I propose to consider the use of `-fwarn-incomplete-uni-patterns` to also rule out irrefutable matches in our source code.  We can use combinators like `caseMaybe`, `caseMaybeM`, `ifNotPiType` etc. instead.

**Comment by UlfNorell** [comment]
I don't see the benefit here. I'm not too concerned about exposing users to match failure errors, I think most of our users are savvy enough to report those even without the carefully worded encouragement of the `__IMPOSSIBLE__` errors.

The main purpose of `-fwarn-incomplete-patterns` is to make GHC tell us where the missing cases are when adding constructors to a datatype. Neither irrefutable patterns or combinators are any help with that.

Further I personally find irrefutable patterns a lot easier to read than case combinators. Compare
```haskell
stuff f = do
  Just (Pi a b) <- lookupType f
  moreStuff a b
```
with
```haskell
{-# LANGUAGE NondecreasingIndentation #-}
stuff f = do
  caseMaybeM (lookupType f) __IMPOSSIBLE__ $ \ ty -> do
  ifNotPiType ty __IMPOSSIBLE__ $ \ a b -> do
  moreStuff a b
```

**Comment by andreasabel** [comment]
> Further I personally find irrefutable patterns a lot easier to read than case combinators.

My proposal is also going towards views (like `ifPiType`) rather than direct matching on constructors of `Term`.

**Comment by asr** [comment]
> Further I personally find irrefutable patterns a lot easier to read than case combinators. 
> Compare
>```haskell
>stuff f = do
>  Just (Pi a b) <- lookupType f
>  moreStuff a b
>```

Due to the [MonadFail proposal](https://prime.haskell.org/wiki/Libraries/Proposals/MonadFail), in GHC 8.6.1 the above code could generate an error like
```
Could not deduce (Control.Monad.Fail.MonadFail ...)
        arising from a do statement
        with the failable pattern ‘Just (Pi a b)’
```

Right now, using GHC 8.6.1-beta1 I'm getting the error

```
src/full/Agda/Utils/Parser/MemoisedCPS.hs:206:11: error:
    • Could not deduce (Control.Monad.Fail.MonadFail
                          Data.Functor.Identity.Identity)
        arising from a do statement
        with the failable pattern ‘Just (Value rs ks)’
      from the context: (Eq k, Hashable k, Show k)
        bound by the type signature for:
                   memoise :: (Eq k, Hashable k, Show k) =>
                              k -> Parser k r tok r -> Parser k r tok r
        at src/full/Agda/Utils/Parser/MemoisedCPS.hs:192:3-9
    • In a stmt of a 'do' block: Just (Value rs ks) <- lookupTable
      In the expression:
        do Just (Value rs ks) <- lookupTable
           insertTable (Value (alter j [] (r :) rs) ks)
           concat <$> mapM (\ k -> k j r) ks
      In the second argument of ‘($)’, namely
        ‘\ j r
           -> do Just (Value rs ks) <- lookupTable
                 insertTable (Value (alter j [] (r :) rs) ks)
                 ....’
    |
206 |           Just (Value rs ks) <- lookupTable
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

+1 on the proposal.

**Comment by andreasabel** [comment]
> Ulf: Further I personally find irrefutable patterns a lot easier to read than case combinators. Compare
```haskell
stuff f = do
  Just (Pi a b) <- lookupType f
  moreStuff a b
```

The nested pattern gives less precise information in case of a crash in comparison to
```haskell
stuff f = do
  Just ty <- lookupType f
  Pi a b <- return ty
  moreStuff a b
```
which would give the equivalent error location to the combinator version
```haskell
{-# LANGUAGE NondecreasingIndentation #-}
stuff f = do
  caseMaybeM (lookupType f) __IMPOSSIBLE__ $ \ ty -> do
  ifNotPiType ty __IMPOSSIBLE__ $ \ a b -> do
  moreStuff a b
```

@asr: Are you saying that failable matches in a monad are on their way to deprecation or customized error handling?

**Comment by UlfNorell** [comment]
> The nested pattern gives less precise information in case of a crash

Sure. You get even more information by

```haskell
stuff f = do
  Just ty <- lookupType f
  case ty of
    Pi a b -> moreStuff a b
    Var{} -> __IMPOSSIBLE__
    Def{} -> __IMPOSSIBLE__
    Con{} -> __IMPOSSIBLE__
    Lam{} -> __IMPOSSIBLE__
    ...
```
The question is how much readability one is prepared to trade off to get more precise crash diagnostics. In my experience most bugs require further instrumentation of the code anyway, so worrying about the initial crash report is pretty much pointless (as long as it gives you a source location).

**Comment by andreasabel** [comment]
The warnings about missing `MonadFail` instances can be triggered by adding `MonadFailDesugaring` to the list of language options.  However, the `Control.Monad.Fail.MonadFail` class is only available from ghc 8.0.  It seems that for a proper migration to ghc 8.6 (re #3160), where the `MonadFailDesugaring` is on by default, we need to implement a `MonadFail` instance for `TCM`.  This implies that we need to abandon ghc 7.10.

A cheap way to rid us of implementing `MonadFail` instances is to make all matches in `do`-blocks lazy, i.e. prefix them with `~`.  However, we can see this migration as a chance to improve match failure errors, by implementing the `fail` function for TCM as for instance:
```haskell
fail s = error $ "The following internal error has occurred.  Please report it as a bug.\n" ++ s
```
Instead of abadoning ghc 7.10, we could define the `MonadFail` instances under `#if`s and turn on `MonadFailDesugaring` only for ghc between 8.0 and 8.4 (from 8.6 it is on by default).

**Comment by nad** [comment]
> This implies that we need to abandon ghc 7.10.

Or use an `#ifdef`?

**Comment by asr** [comment]
> Instead of abadoning ghc 7.10, we could define the `MonadFail` instances under `#if`s 

It is not necessary. From the MonadFail [proposal](https://prime.haskell.org/wiki/Libraries/Proposals/MonadFail):

The [​fail](http://hackage.haskell.org/package/fail) library provides a forward-compatible `MonadFail` class for GHC versions prior to GHC 8.0. 

In fact, we are importing this library in `Agda.cabal`:

```haskell
  if impl(ghc < 8.0)
    -- provide/emulate `Control.Monad.Fail` and `Data.Semigroups` API
    -- for pre-GHC8
    build-depends:  fail == 4.9.*
                  , semigroups == 0.18.*
```

I added the `MonadFail` instance for `TCMT` in 5237c619083a42c1065c8f5a0c0eb2b61cdb0a99.

**Comment by asr** [comment]
> I added the `MonadFail` instance for `TCMT` in 5237c619083a42c1065c8f5a0c0eb2b61cdb0a99.

I reverted the above commit. We should add this instance *after* fixing the failable matches adding some `__IMPOSIBBLE__`s.

**Comment by asr** [comment]
Please ignore the above comment.

**Comment by andreasabel** [comment]
> Please ignore the above comment.

Which one?  (I am a bit confused.)
Note: You can easily delete a comment of yours if it should be ignored (especially if it is the last one with no references to it).

**Comment by asr** [comment]
> Which one?

This one:

> I reverted the above commit. We should add this instance *after* fixing the failable matches adding some `__IMPOSIBBLE__`s.

**Comment by andreasabel** [comment]
There wasn't any consensus on my proposal, thus, I close it.

One could have the flag on a per-file-basis for parts of the code base that do not use refutable matches.
