### ISSUE TITLE
arrows in signature

### ISSUE THREAD

**Issue by mechvel** [agda/agda#3219]
This is on Development Agda of September 7, 2018,  ghc-7.10.2, Debian Linux.
In the emacs mode, the below program reports "Internal error", if the arrow between  ``acc₁`` and
``acc₂`` is  removed.
The effect may change with 
* repeating the C-c C-l command,
* restarting the  emacs session,
* type-checking from the command line.
* switching on/off the above arrow.  

```
open import Relation.Binary using (Rel)
open import Relation.Binary.PropositionalEquality using (_≡_)
open import Induction.WellFounded using (Acc)

module WellFounded0 {a ℓ} {A : Set a} (_<_ : Rel A ℓ)
  where
  Acc< = Acc _<_

  postulate
    acc-irrel : ∀ {ℓ'} {B : Set ℓ'} (f : (x : A) → Acc< x → B)
                     {x₁ x₂ : A} → x₁ ≡ x₂ → (acc₁ : Acc< x₁) → (acc₂ : Acc< x₂) →
                     f x₁ acc₁ ≡ f x₂ acc₂
```

**Comment by gallais** [comment]
Can't reproduce. Which file & line does the internal error point to? Is it the same as in #3199?

**Comment by mechvel** [comment]
Looks like the same:
"An internal error has occurred. Please report this as a bug.
 Location of the error: src/full/Agda/TypeChecking/Serialise/Instances/Common.hs:178
".
