### ISSUE TITLE
Applying empty pattern matching

### ISSUE THREAD

**Issue by smimram** [agda/agda#3222]
I cannot seem to be able to apply the "empty pattern matching" `λ()` to anything.

For instance, I can prove the following theorem
```
absurd : {A : Set} → (false ≡ true) → A
absurd = λ ()
```
However, if I do an η-expansion
```
absurd : {A : Set} → (false ≡ true) → A
absurd p = (λ ()) p
```
I obtain the error message
```
Failed to solve the following constraints:
  _8 := (_ : _5 p) [p] :? .A
  _6 := λ () :? _5 p
```
Is there a good reason why the above should raise an error?

Ultimately, I want to be able to deduce something from absurdity, as in
```
absurd : {A : Set} → ((b : Bool) → b ≡ true) → A
absurd f = (λ ()) (f false)
```
which results in the same error as above. Is there currently a way to prove the above statement?

**Comment by smimram** [comment]
Okay, there is a way to circumvent this, but it is quite heavy to my taste:
```
absurd : {A : Set} → ((b : Bool) → b ≡ true) → A
absurd f = g (f false)
  where
  g : {A : Set} → (false ≡ true) → A
  g ()
```
I would rather use `λ()`.

**Comment by gallais** [comment]
Hi Samuel,

When I want to do something like this I typically use `case_of_` from the standard library's
[`Function` module](https://agda.github.io/agda-stdlib/Function.html#3497).

Your first example would look like:

```agda
absurd : {A : Set} → (false ≡ true) → A
absurd p = case p of λ ()
```

**Comment by smimram** [comment]
Good to know, thanks!
