### ISSUE TITLE
Switch from utf8x to utf8? Make agda.sty easier to maintain?

### ISSUE THREAD

**Issue by nad** [agda/agda#3224]
When `agda.sty` is used under pdfLaTeX it by default loads `inputenc` with the [deprecated](https://tex.stackexchange.com/questions/13067/utf8x-vs-utf8-inputenc) `utf8x` option. The `ucs` package (at least a recent version) does not make the macro `\DeclareUnicodeCharacter` available when `utf8x` is used. Perhaps we should switch from `utf8x` to `utf8`. A drawback is that fewer characters get rendered out of the box. Any opinions?

I guess the idea of `agda.sty` is to make it possible to load one package and get everything to work. However, this is not always the case. For instance, when using a publisher's LaTeX style it is rarely a good idea to change the default fonts. I typically use `agda.sty` with `nofontsetup` and `noinputencodingsetup`, and from a maintenance perspective I would prefer dropping most or all of the code dealing with fonts and input encodings. Any opinions?

**Comment by nad** [comment]
I noticed now that we recommend the use of `utf8x` together with `\DeclareUnicodeCharacter` in the [user manual](https://agda.readthedocs.io/en/v2.5.4.1/tools/generating-latex.html#complete-latex-template-for-literate-agda-with-unicode). This does not work with TeX Live 2018:
```
! Undefined control sequence.
l.24 \DeclareUnicodeCharacter
                             {8988}{\ensuremath{\ulcorner}}
```

**Comment by JacquesCarette** [comment]
I've been bitten by this. Luckily the publisher agreed to use `utf8x` for the one paper.

**Comment by nad** [comment]
> [...] from a maintenance perspective I would prefer dropping most or all of the code dealing with fonts and input encodings. Any opinions?

Are there no objections to this?

**Comment by MatthewDaggitt** [comment]
I've also just been bitten by this in the paper I'm submitting. I've upgraded to use the style file from the 2.6.0 release candidate. How do I now tell latex which symbols to use for the unicode characters? 

Obviously \DeclareUnicodeCharacter doesn't work now. I've tried using `\newunicodechar` as suggested by @Ulf in #3170 but no luck with that either. Is it covered in the updated documentation for Agda 2.6.0?

**Comment by gallais** [comment]
`\newunicodechar` worked for me: https://github.com/gallais/thesis/blob/master/doc/unicode.tex

**Comment by nad** [comment]
> Is it covered in the updated documentation for Agda 2.6.0?

The documentation [suggests](https://agda.readthedocs.io/en/latest/tools/generating-latex.html#known-pitfalls-and-issues) to use `\newunicodechar`. If this does not work for you, then it might be a good idea to edit the documentation.

**Comment by MatthewDaggitt** [comment]
Thanks @gallais and @nad! That was a huge help.

It seems like an expanded version of @gallais's file might be a valuable community resource. Just in the middle of compiling my own and it's certainly very painful to do manually. Would it even be possible to incorporate into `agda.sty` under some appropriate `if` statements?

**Comment by gallais** [comment]
May be worth opening a separate issue for this so that it doesn't get lost?

It would make sense to have a file providing bindings for all (or as many as possible)
of the unicode characters made available in the agda input mode.
