### ISSUE TITLE
Feature request: "all constructors" ellipsis in import statement

### ISSUE THREAD

**Issue by gallais** [agda/agda#3231]
In Haskell we can write `import Data.These using (These(..))` and get `These` and its
various constructors brought in scope. In Agda we currently have to manually list all of the
constructors.

**Comment by gallais** [comment]
Self-caveat: I have just realized that the `module` associated to a datatype is silently imported.
So one can already write something like:

```agda
open import Data.These using (These)
open These
```

So there is a workaround and the situation is not as bad as I was thinking.

**Comment by nad** [comment]
This is a duplicate of an issue that I opened over ten years ago (#96).
