### ISSUE TITLE
Type declarations not accompanied by a definition should be highlighted in the emacs mode

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3233]
I think that type declarations not accompanied by a definition should be highlighted in the emacs mode (in addition to the warning).
The reason is that when you have a file with many goals, the warnings appears below the goals so you can easily miss it (for instance if you have several goals in one part of the file but you’re working on a different part).

**Comment by jespercockx** [comment]
In case of code highlighting, I am of the opinion that more colors is always better.

**Comment by guillaumebrunerie** [comment]
This is not quite working, in the example below, only `A` is highlighted orange:
```agda
A : Set
B : Set
```

**Comment by jespercockx** [comment]
For some reason the range was calculated by taking the head of the list of warnings, it should be fixed now.
