### ISSUE TITLE
agda emacs mode as separate repo?

### ISSUE THREAD

**Issue by patrl** [agda/agda#3234]
This is less a specific issue, and more of a general query. Is there a good reason for the agda emacs mode to be kept in this repo and distributed with agda releases? Does it need to be built against a given version of agda? If not, it would seem to me to make sense to move the agda emacs mode source into its own repo for ease of maintenance, perhaps adding the main agda repo as a submodule if necessary. Down the road, this should make it possible to distribute the module via melpa.

Perhaps I'm barking up the wrong tree here, but I have a couple of PRs ready to go to improve the emacs mode, and find this situation quite off-putting.

**Comment by nad** [comment]
> Does it need to be built against a given version of agda?

Yes.

> I have a couple of PRs ready to go to improve the emacs mode

This sounds interesting.

**Comment by patrl** [comment]
Thanks for the quick response!

> > Does it need to be built against a given version of agda?

> 
> Yes.

Huh. As far as I can see, it's just a bunch of emacs-lisp files in `/src/data/emacs-mode`. I understand that compatibility between different versions of agda needs to be maintained, but that easy to achieve by tagging releases. If the answer is just that this is how things are done and it would be a pain to change them, then that's OK! :)

> 
> > I have a couple of PRs ready to go to improve the emacs mode
> 
> This sounds interesting.

**Comment by nad** [comment]
The interface between the Emacs mode and Agda changes now and then. When it does I prefer a single commit touching both sides to separate commits in two repositories.

Note also that the Emacs mode is bundled with the Agda program, and there is a small program that updates users' `.emacs` files. We implemented this a long time ago, probably before ELPA existed. Perhaps it would make sense to look into other alternatives, but most users don't seem to mind the current situation. For a person who is using Emacs only to write Agda programs I suspect that setting up and using MELPA is quite a bit harder than running `agda-mode setup`.

**Comment by patrl** [comment]
Thanks for the detailed explanation, I appreciate it. 

For what it's worth, I think that from the perspective of long-term maintenance, it makes sense to take advantage of the existing infrastructure for emacs package management, rather than a hacky script. The current method makes it difficult to, e.g,, lazily-load agda-mode via `use-package`, and requires manual intervention for any non-standard emacs configuration.

Anyway, i've said my piece. If there's no desire for this, then fair enough! Feel free to close this issue.

**Comment by nad** [comment]
I don't see what the issues you bring up have to do with where the Emacs mode is hosted.

If you want to make the Emacs experience smoother in some way, then that sounds good to me, as long as it doesn't create a maintenance problem for us down the road.
