### ISSUE TITLE
The test-suite is failing on GHC 8.6.1

### ISSUE THREAD

**Issue by asr** [agda/agda#3245]
For example, using GHC 8.6.1 I got,

```bash
$ cd test/Succeed/
$ agda ImportInMutual.agda
Checking ImportInMutual
(/home/asr/src/agda/agda-upstream-ghc-8.6.1/test/Succeed/ImportInMutual.agda).
```

but using GHC 8.4.3, I got

```bash
$ cd test/Succeed/
$ agda ImportInMutual.agda
Checking ImportInMutual (/.../test/Succeed/ImportInMutual.agda).
/.../test/Succeed/ImportInMutual.agda:7,10-21
Import statements are not allowed in mutual blocks

———— All done; warnings encountered ————————————————————————

/.../test/Succeed/ImportInMutual.agda:7,10-21
Import statements are not allowed in mutual blocks
```

Note that when using GHC 8.6.1 the warnings are not reported (and in consequence
the `succeed` test fails).

I have not had time to look at this problem but I am reporting it now thinking about speeding up Agda support to GHC 8.6.1.

**Comment by gallais** [comment]
Seems strange. Have you tried passing `--ignore-interfaces` to agda?

**Comment by asr** [comment]
Yes. I see the same behaviour using `--ignore-interfaces`.

**Comment by nad** [comment]
Perhaps the two binaries are compiled using different versions of libraries, and some library has changed.

**Comment by andreasabel** [comment]
> Perhaps the two binaries are compiled using different versions of libraries, and some library has changed.

Can you elaborate?  I don't understand this comment.  What binaries are you referring to?

**Comment by nad** [comment]
The two Agda binaries, one compiled using GHC 8.4.3, and one compiled using GHC 8.6.1.

**Comment by asr** [comment]
The GHC 8.6.1 test on Travis also is [failing](https://travis-ci.org/agda/agda/jobs/437647189) due to the same problem.

**Comment by UlfNorell** [comment]
The problem (discovered in #3261) seems to be the new version of `tasty`.

**Comment by asr** [comment]
Note that the example in the OP doesn't use `tasty`.

**Comment by gallais** [comment]
Looks like a bug in ghc breaks `containers` on 8.6.1 https://ghc.haskell.org/trac/ghc/ticket/15696

I now understand better why we have errors related to flags and warnings: the new machinery
is using `Set` with big enumerations (the `WarningName` datatype).

**Comment by asr** [comment]
It seems we need to wait the release of GHC 8.6.2, so I'm closing the issue.

**Comment by asr** [comment]
Back-ported to 2.5.4.3.
