### ISSUE TITLE
Max of two sizes less than i

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3248]
The code below does not typecheck with the following error (pointing at the argument `{j₁ ⊔ˢ j₂}` of the last `cons`)
```
i != ∞ of type Size
when checking that the inferred type of an application
  Size
matches the expected type
  Size< i
```

It looks like even though `j₁ : Size< i` and `j₂ : Size< i`, we do not have `j₁ ⊔ˢ j₂ : Size< i`. Is that expected?

Another related issue is that if you replace the last line by
```agda
f {i} (cons {j₁} x l1) (cons {j₂} _ l2) = cons {i} {?} x (?)
```

then C-c C-s solves the first question mark to `j₁` which is not expected as we wanted to put `j₁ ⊔ˢ j₂` there instead.

```agda
{-# BUILTIN SIZEUNIV SizeUniv #-}  --  SizeUniv : SizeUniv
{-# BUILTIN SIZE     Size     #-}  --  Size     : SizeUniv
{-# BUILTIN SIZELT   Size<_   #-}  --  Size<_   : ..Size → SizeUniv
{-# BUILTIN SIZESUC  ↑_       #-}  --  ↑_       : Size → Size
{-# BUILTIN SIZEINF  ∞        #-}  --  ∞        : Size
{-# BUILTIN SIZEMAX  _⊔ˢ_     #-}  --  _⊔ˢ_     : Size → Size → Size

postulate A : Set

data List (i : Size) : Set where
  nil : List i
  cons : {j : Size< i} → A → List j → List i

f : {i : Size} → List i → List i → List i
f nil _ = nil
f (cons _ _) nil = nil
f {i} (cons {j₁} x l1) (cons {j₂} _ l2) = cons {i} {j₁ ⊔ˢ j₂} x (f {j₁ ⊔ˢ j₂} l1 l2)
```

**Comment by gallais** [comment]
Note that for this particular case you can use either of the following types:

```agda
f : {i j : Size} → List i → List j → List i
f : {i j : Size} → List i → List j → List j
```

and then derive the type you wanted as a corollary.

**Comment by jespercockx** [comment]
Maybe this is caused by the fact that a variable `j : Size< i` is represented internally as `j : Size` together with a constraint `j < i`? So in your example it becomes `j₁ : Size` and `j₂ : Size` with `j₁ < i` and `j₂ < i`. It seems to me that something with this encoding is going wrong internally, but I'll have to investigate further.

**Comment by andreasabel** [comment]
This used to work until 2.5.3.  (Ulf's refactoring e49d1ca276e5adbf2eb9f6cd33926b786cef78f7 of the application checking seems to take the blame for this.)  
The problem is that `leqType` is insufficient when the target type is a Size<, it is necessary to invoke `coerce` then.
Related: #3039.
