### ISSUE TITLE
Reproducible internal error in automatic proof of false

### ISSUE THREAD

**Issue by cdunham** [agda/agda#3249]
>
> -- Agda version 2.5.4.1
>
> open import Data.Empty using (⊥)                                                
> open import Data.Nat.Base                                                       
>                                                                                 
> bug : 1 ≤ 0 → ⊥                                                                 
> bug p = {! -c !}                                                                
>                                                                                 
> -- C-c C-a (auto) in the hole changes definition (correctly) to "bug ()"     
> --   but also gives the following message:                                      
> -- An internal error has occurred. Please report this as a bug.                 
> -- Location of the error: src/full/Agda/TypeChecking/Serialise/Instances/Common\
.hs:178

**Comment by gallais** [comment]
I believe this is #3199. It's been fixed but we have a hard time finding a good test
case for it. Unfortunately your case doesn't seem to reliably trigger the bug either.

**Comment by cdunham** [comment]
Thanks. Seemed pretty reliable for me, but glad it's sorted.

**Comment by gallais** [comment]
> Seemed pretty reliable for me

It has to do with serialization so caching plays a role there. It's hard to get it to manifest
itself from a blank slate which is what the test suite needs. :/

The bugfix will be part of the minor release 2.5.4.2 so hopefully you won't have to suffer
from it for too long.
