### ISSUE TITLE
Ordering the constructor names at Definition.

### ISSUE THREAD

**Issue by xekoukou** [agda/agda#3258]
Is it possible to guarantee that the order of the constructor names in the [Datatype]( https://github.com/agda/agda/blob/323f58f9b8dad239142ed1dfa0c60338ea2cb157/src/full/Agda/TypeChecking/Monad/Base.hs#L1601) remains consistent with the order that the Constructors were defined?

I am trying to create a FFI with OCaml. Ocaml's internal representation of Algebraic data types depends on the order of [definition](http://caml.inria.fr/pub/docs/manual-ocaml-4.00/manual033.html#htoc264).

**Comment by UlfNorell** [comment]
They should be. Do you have an example when they're not?

**Comment by xekoukou** [comment]
I haven't checked yet. But even if they are ordered now, the behavior might change if this property is not documented and tested. Or another solution is to add a tag field in the [Constructor](https://github.com/agda/agda/blob/323f58f9b8dad239142ed1dfa0c60338ea2cb157/src/full/Agda/TypeChecking/Monad/Base.hs#L1642) definition, that indicates the order (of the definitions).

**Comment by gallais** [comment]
Correct me if I'm wrong but for these kind of definitions to make sense we need to
always preserve the order the constructors were defined in?

```agda
module VeryDependent where

mutual

  data A : Set where
    C₁ : A
    C₂ : P C₁ → A -- here C₂ needs C₁ to be known to make sense

  data P : A → Set where
    P₁ : P C₁
```
Not sure we already have a test case for these (and I have no idea how I would go
about looking for one...).

The same is true to some extent for HITs IIUC.

**Comment by andreasabel** [comment]
The order of constructors is guaranteed, otherwise the GHC backend would not work properly. See issue #3259 where this matters.
