### ISSUE TITLE
On ghc-8.2, agda with `--enable-tests` does not coexist with `pandoc`

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3261]
After (force) installing `pandoc-2.3.1` I can still install agda by `cabal install` in the agda root directory, but `make install-bin` fails.

The problem is the option `--enable-tests` which is passed to `cabal install` by `make install-bin`.

I am a bit at a loss how to interpret cabal's output; which one is the culprit that is responsible for the downgrades?
```
/agda$ make install-bin
touch src/full/Agda/VersionCommit.hs
cabal install --disable-documentation --builddir=./dist-2.6.0 --enable-tests --disable-library-profiling -fenable-cluster-counting --program-suffix=-2.6.0
Resolving dependencies...
In order, the following would be installed:
ListLike-4.6 (via: process-extras-0.7.4) (new version)
async-2.2.1 (via: Agda-2.6.0 tasty-silver-3.1.12 tasty-1.1.0.4) (reinstall)
(changes: hashable-1.2.7.0 -> 1.2.6.1)
hashtables-1.2.3.1 (via: Agda-2.6.0) (reinstall) (changes: hashable-1.2.7.0 ->
1.2.6.1)
network-uri-2.6.1.0 (via: uri-encode-1.5.0.5) (reinstall) (changes:
parsec-3.1.13.0 -> 3.1.11)
scientific-0.3.6.2 (via: aeson-1.2.4.0 attoparsec-0.13.2.2) (reinstall)
(changes: hashable-1.2.7.0 -> 1.2.6.1, text-1.2.3.1 -> 1.2.2.2)
uuid-types-1.0.3 (via: aeson-1.2.4.0) (reinstall) (changes: hashable-1.2.7.0
-> 1.2.6.1, text-1.2.3.1 -> 1.2.2.2)
process-extras-0.7.4 (via: Agda-2.6.0 tasty-silver-3.1.12) (new version)
tasty-1.1.0.4 (via: Agda-2.6.0 tasty-hunit-0.10.0.1 tasty-quickcheck-0.10
tasty-silver-3.1.12) (new version)
uri-encode-1.5.0.5 (via: Agda-2.6.0 Agda-2.6.0) (reinstall) (changes:
network-uri-2.6.1.0 removed, text-1.2.3.1 -> 1.2.2.2)
attoparsec-0.13.2.2 (via: aeson-1.2.4.0) (reinstall) (changes:
scientific-0.3.6.2 removed, text-1.2.3.1 -> 1.2.2.2)
tasty-silver-3.1.12 (via: Agda-2.6.0) (reinstall) (changes:
process-extras-0.7.2 removed, tasty-1.1.0.3 removed)
tasty-quickcheck-0.10 (via: Agda-2.6.0) (reinstall) (changes:
QuickCheck-2.12.1 -> 2.12.6.1, tasty-1.1.0.3 removed)
tasty-hunit-0.10.0.1 (via: Agda-2.6.0) (reinstall) (changes: tasty-1.1.0.3
removed)
aeson-1.2.4.0 (latest: 1.4.1.0) (via: Agda-2.6.0) (reinstall) (changes:
dlist-0.8.0.3 -> 0.8.0.5, vector-0.12.0.1 added)
Agda-2.6.0 +enable-cluster-counting *test (reinstall) (changes:
QuickCheck-2.12.6.1 added, aeson-1.4.1.0 removed, async-2.2.1 removed,
blaze-html-0.9.1.1 -> 0.9.0.1, filemanip-0.3.6.3 added, hashable-1.2.7.0 ->
1.2.6.1, hashtables-1.2.3.1 removed, regex-tdfa-1.2.3.1 -> 1.2.2,
regex-tdfa-text-1.0.0.3 added, temporary-1.2.1.1 added, text-1.2.3.1 ->
1.2.2.2, text-icu-0.7.0.1 added, unix-compat-0.4.3.1 added,
unordered-containers-0.2.9.0 -> 0.2.8.0, uri-encode-1.5.0.5 removed)
cabal: The following packages are likely to be broken by the reinstalls:
pandoc-2.3.1
hxt-9.3.1.16
skylighting-core-0.7.4
skylighting-0.7.4
http-client-tls-0.3.5.3
http-client-0.5.13.1
HTTP-4000.3.12
doctemplates-0.2.2.1
aeson-1.4.1.0
pandoc-types-1.17.5.1
texmath-0.11.1.1
aeson-pretty-0.8.7
Use --force-reinstalls if you want to install anyway.
make: *** [install-bin] Error 1
```

```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.2.1
```

**Comment by andreasabel** [comment]
I solved my problem by hand-installing a few packages and then trying again.
```
cabal install ListLike-4.6
cabal install tasty-hunit
cabal install tasty-quickcheck
cabal install tasty-silver
```
The third installed `tasty`:
```
Installed tasty-1.1.0.4
```
Then I succeeded:
```
$ cabal install --disable-documentation --builddir=./dist-2.6.0 --disable-library-profiling -fenable-cluster-counting --enable-tests --program-suffix=-2.6.0 
Resolving dependencies...
In order, the following will be installed:
regex-tdfa-text-1.0.0.3 (via: Agda-2.6.0) (reinstall) (changes:
regex-tdfa-1.2.2 -> 1.2.3.1, text-1.2.2.2 -> 1.2.3.1)
tasty-hunit-0.10.0.1 (via: Agda-2.6.0) (reinstall) (changes: tasty-0.11.2.5 ->
1.1.0.4)
Agda-2.6.0 +enable-cluster-counting *test (reinstall) (changes:
QuickCheck-2.12.6.1 added, filemanip-0.3.6.3 added, process-extras-0.7.4
added, tasty-1.1.0.4 added, tasty-quickcheck-0.10 added, tasty-silver-3.1.12
added, temporary-1.2.1.1 added, text-icu-0.7.0.1 added, unix-compat-0.4.3.1
added)
```
I noticed that `tasty` has a major version jump: `tasty-0.11.2.5 -> 1.1.0.4`.

Is there a reason to not require the latest version of `tasty`?
It has an excellent build matrix:
https://matrix.hackage.haskell.org/#/package/tasty

**Comment by andreasabel** [comment]
@asr: My suggestion would be to bump the lower bound of `tasty`.
But since you are the expert here, I do not want to mess around.  Would you take a look?

**Comment by asr** [comment]
> Would you take a look?

Yes.

**Comment by nad** [comment]
FYI: This change made my latest build a little more complicated. (For some reason Cabal wanted to upgrade stm, even though the currently installed version was in range. This could have broken some installed packages. However, I could force Cabal to use the currently installed version of stm by using the `--constraint` flag.)

**Comment by nad** [comment]
After you bumped the lower bound of tasty I started getting problems with the test suite. In particular, some warnings disappeared from the output of test cases under `test/Succeed`. I tried to downgrade to tasty-1.0.1.1, and the problems disappeared.

**Comment by nad** [comment]
Note that tasty-1.0.1.1 does not build under GHC 8.6.1.

**Comment by nad** [comment]
> I tried to downgrade to tasty-1.0.1.1, and the problems disappeared.

As far as I know this was the only change. (Some libraries that depend on tasty were recompiled.)

**Comment by UlfNorell** [comment]
> After you bumped the lower bound of tasty I started getting problems with the test suite. In particular, some warnings disappeared from the output of test cases under test/Succeed.

cc #3245.

**Comment by asr** [comment]
> After you bumped the lower bound of tasty I started getting problems with the test suite. In particular, some warnings disappeared from the output of test cases under `test/Succeed`. I tried to downgrade to tasty-1.0.1.1, and the problems disappeared.

On which version of GHC did you get the problems?

**Comment by nad** [comment]
> As far as I know this was the only change.

I retract this statement, because I'm starting to think that I switched from 8.6.1 to 8.4.3. At least I failed to reproduce the problem with 8.4.3 now. Perhaps tasty is not to blame.
