### ISSUE TITLE
When refine leads to a termination error it should say so rather than "cannot refine"

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3264]
In the code below, trying to refine with `f` leads to the confusing error message `Cannot refine`. Giving `f ?` instead gives the expected error message `Termination checking failed […]`.

```agda
f : Set → Set
f A = {!f!}
```

**Comment by andreasabel** [comment]
This could be fixed by distinguishing termination errors from typing errors, or by just reimplementing refine in a sane way (it also does not work with projections at the moment).

**Comment by gallais** [comment]
In 2.6.0, refine seems to work in this case.

**Comment by andreasabel** [comment]
Great!  I just added a test case.

**Comment by guillaumebrunerie** [comment]
Ah indeed, thanks, I think I was on a cubical branch which I assumed was up-to-date with master.
