### ISSUE TITLE
Agda keeps rechecking already checked files.

### ISSUE THREAD

**Issue by semenov-vladyslav** [agda/agda#3266]
Regression between the commits 8cb764ba5a0062bc455db69d4ac9a1822d2a02ed (older, good) and 3df6f5e937b146deaea6f1ebf1a534b699796a99 (newer, bad).

Loading a module in emacs with a few imports from std-lib (Data.Nat, Data.Sum) takes much time (like 20 min or more). Log shows that many modules are being rechecked many times (I guess because of import dependencies). Reloading the module in emacs leads again to a complete recheck. Interactive Agda is unusable at this point.

Issue #2473 seem to be related.

**Comment by andreasabel** [comment]
> Regression between the commits 8cb764b (older, good) and 3df6f5e (newer, bad).

That must be commits by you, @nad, on #2473, if I read the commit sequence correctly.

**Comment by UlfNorell** [comment]
I can't reproduce this (on a5514a2). Do you have a concrete file and std-lib commit that shows the problem? Also can you check whether
- it's also a problem when calling Agda from the command line
- the problem persists if you delete all your `agdai` files

**Comment by semenov-vladyslav** [comment]
I have the same problem with a5514a2f728bd6f58c2a1efdbe7e2cc55e5ce928. Tried on the command line and deleting all `agdai` files - it's all the same. std-lib commits seem to be unrelated, but I used master. 
This is the test module:
```
module m where
open import Function using (id ; const ; _∘_)
open import Data.Nat as N using (ℕ ; zero ; suc ; _+_)
open import Data.Sum as S using (_⊎_ ; inj₁ ; inj₂)
```
Log looks like this (excerpt):
```
 Checking Data.Nat (C:\usr\agda\agda\std-lib\src\Data\Nat.agda).
  Checking Data.Nat.Base (C:\usr\agda\agda\std-lib\src\Data\Nat\Base.agda).
   Checking Relation.Binary (C:\usr\agda\agda\std-lib\src\Relation\Binary.agda).
    Checking Data.Product (C:\usr\agda\agda\std-lib\src\Data\Product.agda).
     Checking Relation.Nullary (C:\usr\agda\agda\std-lib\src\Relation\Nullary.agda).
      Checking Data.Empty (C:\usr\agda\agda\std-lib\src\Data\Empty.agda).
      Checking Data.Empty.Irrelevant (C:\usr\agda\agda\std-lib\src\Data\Empty\Irrelevant.agda).
      Checking Data.Empty.Irrelevant (C:\usr\agda\agda\std-lib\src\Data\Empty\Irrelevant.agda).
       Checking Data.Empty (C:\usr\agda\agda\std-lib\src\Data\Empty.agda).
       Checking Data.Empty (C:\usr\agda\agda\std-lib\src\Data\Empty.agda).
     Checking Agda.Builtin.Sigma (C:\usr\agda\agda\.stack-work\install\d1e81147\share\x86_64-windows-ghc-8.4.3\Agda-2.6.0\lib\prim\Agda\Builtin\Sigma.agda).
     Checking Relation.Nullary (C:\usr\agda\agda\std-lib\src\Relation\Nullary.agda).
      Checking Data.Empty (C:\usr\agda\agda\std-lib\src\Data\Empty.agda).
      Checking Data.Empty.Irrelevant (C:\usr\agda\agda\std-lib\src\Data\Empty\Irrelevant.agda).
      Checking Data.Empty.Irrelevant (C:\usr\agda\agda\std-lib\src\Data\Empty\Irrelevant.agda).
       Checking Data.Empty (C:\usr\agda\agda\std-lib\src\Data\Empty.agda).
       Checking Data.Empty (C:\usr\agda\agda\std-lib\src\Data\Empty.agda).
```
I use stack-8.4.3.yaml to build Agda, if that helps.

**Comment by semenov-vladyslav** [comment]
I've added a debug output before https://github.com/agda/agda/blob/master/src/full/Agda/Interaction/Imports.hs#L372.
Here's what it shows (`isCached = isJust cached`):
```
 unchanged False ignore False isCached True sourceH 3370326967968795547 ifaceH Just 6015113721108106836
  Agda.Builtin.Equality is not up-to-date.
cleanCachedLog
     Checking Agda.Builtin.Equality (C:\usr\agda\agda\.stack-work\install\77a492e6\share\x86_64-windows-ghc-8.6.1\Agda-2.6.0\lib\prim\Agda\Builtin\Equality.agda).
Creating interface for Agda.Builtin.Equality.
```
Hashes clearly differ. `iSourceHash` seems to be defined as `hashText source` (changed from `hashFile file`). I'm on Windows and my git is configured to checkout with CRLF, so these were the conditions that triggered the problem. So my guess for the cause of the problem is when the two hashes are compared one is calculated with `hashText` and the other with `hashFile` (not sure tho, didn't look deeper). I tried changing line-endings in `Data.Sum.Base` and it seemed to help:
```
 unchanged True ignore False isCached False sourceH 14071410011307391918 ifaceH Just 14071410011307391918
  Data.Sum.Base is up-to-date.
  no stored version, reading C:\usr\agda\agda\std-lib\src\Data\Sum\Base.agdai
```
Changing line-ending of `Agda.Builtin.Equality` within `.stack-work` directory also helped.

**Comment by semenov-vladyslav** [comment]
Ok. Changed `hashFile` in `Agda.Utils.Hash` into:
```
import Agda.Utils.IO.UTF8 (readTextFile)
hashTextFile :: AbsolutePath -> IO Hash
hashTextFile file = do
  s <- readTextFile (filePath file)
  return $ hashText s
```
`hashFile` was only used here https://github.com/agda/agda/blob/master/src/full/Agda/Interaction/Imports.hs#L365.

This fixed the problem. Can't create PR as don't have permissions to push.

**Comment by ice1000** [comment]
@semenov-vladyslav You can fork and create a PR.

**Comment by semenov-vladyslav** [comment]
Done https://github.com/agda/agda/pull/3269.

**Comment by nad** [comment]
This fix looks correct to me. A test case should be included. I think one can construct a test case that triggers the bug on all systems by using a file with, say, `\r` as a line ending. (Note that the whitespace checking program might need a special case for this test case.)

**Comment by semenov-vladyslav** [comment]
It's not actually a bug as a module will finally be typechecked. We can test it implicitly by checking that module `m is up-to-date` in log (need to pass `-v 5` to Agda) when it is imported for the second time. Or shall we instead test `hashTextFile` that it hashes files with and without `\r` to the same value? Also, is it possible to generate module with `\r` before running tests intead of having it fixed in the repo in order to avoid issues with git and fix-agda-whitespace?

I'm not sure how to do it. Would be grateful for any suggestions.

**Comment by nad** [comment]
There is already a test case that checks that a file is not re-checked, see `relocatable-interfaces` in `examples/Makefile`.

> issues with git and fix-agda-whitespace

It is easy to add an exception to `src/fix-agda-whitespace/FixWhitespace.hs'.

Does Git mess with line-endings? Note that `Agda.Utils.IO.UTF8.readTextFile` maps, for instance, `'\x2029'` (PARAGRAPH SEPARATOR) to `'\n'`. Perhaps this code point could be used in the test case.

**Comment by semenov-vladyslav** [comment]
Thanks @nad. Added a test case in `examples/uptodate` and also an exception to `FixWhitespaces.hs`.

> Does Git mess with line-endings?

I meant `git config core.autocrlf` so that CRLF is not autoconverted to LF which will make test incorrect. Please, check that module `examples/uptodate/C.agda` has CRLF line-ending and I didn't mess up uploading it.

**Comment by nad** [comment]
> Please, check that module `examples/uptodate/C.agda` has CRLF line-ending and I didn't mess up uploading it.

This seems to have worked fine. Please add some documentation to the module so that we know later that it is supposed to have this line ending.

Did you also include test cases for, say, `'\x2029'` and `'\r'`?

**Comment by semenov-vladyslav** [comment]
> Please add some documentation to the module

Do you mean a comment in the `C.agda`?

> Did you also include test cases for, say, '\x2029' and '\r'?

Not yet. Should it be a separate test case, or all cases in one module will do?

**Comment by nad** [comment]
Yes, in `C.agda`. You can put all test cases in one module.

**Comment by semenov-vladyslav** [comment]
Added description comment and test cases for various line-endings from `readTextFile`.

**Comment by nad** [comment]
Can this issue be closed now?

**Comment by semenov-vladyslav** [comment]
Yes. Looks good.
