### ISSUE TITLE
Auto should not print out-of-scope identifiers or add import statements

### ISSUE THREAD

**Issue by ice1000** [agda/agda#3267]
Like, I can use `_+_` and `Nat` defined in the builtin package in this way:

```agda
module FeatureRequest where

value10 : .Agda.Builtin.Nat.Nat
value10 = .Agda.Builtin.Nat._+_ 2 8
```

**Comment by andreasabel** [comment]
The following works, would that suit you?
```agda
import Agda.Builtin.Nat

value10 : Agda.Builtin.Nat.Nat
value10 = Agda.Builtin.Nat._+_ 2 8
```
The `import` is indicating that some external file is involved.  Do you suggest one should be able to refer to these names without an import statement?  That would mean that whenever a qualified name is not in scope, we would look in the file system (as indicated by the info in the`.agda-lib` file)?!

**Comment by ice1000** [comment]
> Do you suggest one should be able to refer to these names without an import statement? That would mean that whenever a qualified name is not in scope, we would look in the file system (as indicated by the info in the.agda-lib file)?!

Sure, because the Auto-Proof-Search is generating such kind of code.

![image](https://user-images.githubusercontent.com/16398479/46920806-8c0b7900-cfc1-11e8-853a-2b61914b99c2.png)

Which cannot compile (since there are no imports for the constructors but for the record type itself).

**Comment by ice1000** [comment]
Maybe I'm wrong. Such kind of generated full qualified name starts with `.`, updated the post.

**Comment by gallais** [comment]
I'd argue that the bug is that Auto generates code mentioning out of scope names
and that they are accepted as hole fillers, not that we should have a syntax for
out of scope names.

**Comment by ice1000** [comment]
It's also acceptable to me that Auto can add imports.

**Comment by andreasabel** [comment]
> It's also acceptable to me that Auto can add imports.

Unfortunately, it can't, since it can only fill holes, in which `import` statements are not legal. You will need to add the imports by hand.

I am closing this issue, mostly because Auto is unmaintained, and unless you volunteer to fix this issue yourself, things will stay as they are, I am afraid.

**Comment by ice1000** [comment]
Ok
