### ISSUE TITLE
make generalized variables implicit automatically

### ISSUE THREAD

**Issue by divipp** [agda/agda#3272]
Currently one should explicitly tell that a variable will be generalized as a hidden variable:

```agda
variable  {n} : Nat
```

It is a common error to omit the braces:

```agda
variable  n : Nat
```

which means that `n` is added as an *extra* explicit argument which is mostly not the intention.

This could be solved by transforming `variable  n : Nat` to `variable  {n} : Nat` automatically, for example.

**Comment by nad** [comment]
If the idea is to support generalisable variables of the implicit and instance kinds, but not the explicit kind, then I suggest that Agda should raise a (non-fatal) error when the latter kind is encountered.

**Comment by UlfNorell** [comment]
It seems really petty to force people to write the curlies around all generalizable variables. I would argue that the default expectation is anyway that generalised variables are implicit so it won't create a lot of confusion to just implement this.
