### ISSUE TITLE
Generalise over metas in solutions of generalisable metas

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#3274]
If a generalisable meta is partially solved, it would make sense to generalise over metas in the solution, even when those metas weren't originally generalisable. For instance:

```agda
open import Agda.Builtin.Nat

data Vec (A : Set) : Nat → Set where

variable
  A  : Set
  x  : A
  n  : Nat
  xs : Vec A n

postulate
  IsHead : A → Vec A (suc n) → Set

-- The `n` is not generalizable!
foo : IsHead {n = _} x xs → Nat
foo = {!!}
```
Here the meta created for the length of `xs` is generalisable, but it gets instantiated with `suc n`, where `n` is the implicit argument to `IsHead`, which is not generalisable.

**Comment by nad** [comment]
I wonder how brittle this approach is. Does the result, for instance, depend on implementation choices in the conversion checker?

**Comment by UlfNorell** [comment]
Allowing this make things less brittle. Without it, it would matter whether a generalisable meta is instantiated to a non-generalisable meta or the other way around.
