### ISSUE TITLE
Bump lower bound version of text library to 1.2.3.1

### ISSUE THREAD

**Issue by asr** [agda/agda#3277]
GHC 8.4.4 includes a new version of the `text` library (version 1.2.3.1) fixing several serious bugs (see the announce [here](https://mail.haskell.org/pipermail/glasgow-haskell-users/2018-October/026809.html)). I'll require this version of the library everywhere.

**Comment by asr** [comment]
After closing the issue, all the current versions of GHC supported are using `text` >=1.2.3.1 except GHC 8.4.1, 8.4.2 and 8.4.3.

I made the exception for keeping "not-official" support for those versions of GHC.

**Comment by andreasabel** [comment]
Why is it that the [release notes for GHC 8.6.1](https://downloads.haskell.org/~ghc/8.6.1/docs/html/users_guide/8.6.1-notes.html#included-libraries) mention already `text-1.3.2.1` as shipped with GHC?
