### ISSUE TITLE
cascading generalized variables

### ISSUE THREAD

**Issue by divipp** [agda/agda#3281]
(This issue was extracted from discussion #3117)

Consider

```agda
variable
      i : Level
      X : Set i

postulate
      f : X -> Set i 
      -- actual type: {i0 i1} {X : Set i0} -> X -> Set i1
      -- expected:  {i} {X : Set i} -> X -> Set i
```

The point is that `i` was named in the variable declaration `X`, so `X` should have type `Set i` in any context.

If one wants the current behavior then one could write either of the following two solutions:

```agda
variable
      i : Level
      X : Set _

postulate
      f : X -> Set i             --   {i0 i} {X : Set i0} -> X -> Set i
```

Second solution (a bit more verbose):

```agda
variable
      i0 i1 : Level
      X : Set i1

postulate
      f : X -> Set i0             --   {i0 i1} {X : Set i1} -> X -> Set i0
```

**Comment by UlfNorell** [comment]
> The point is that i was named in the variable declaration X, so X should have type Set i in any context.

I don't think this is a reasonable expectation. It seems like naming the level would make the variable all but useless if we enforce this.

I read
```agda
variable
  X : Set i
```
as "`X` should be generalised `Set i`, *for some level `i`*". Not that the level of `X` must always be called `i`.
