### ISSUE TITLE
`make internal-test`  does not rebuild the internal test suite

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3284]
Reproduce:
1. `make install-bin` 
2. modify some files under `test/Internal`, like commenting out some tests
3. `make internal-tests`

This does not recompile the internal test suite, thus, does not take changes in 2. into account.

**Comment by UlfNorell** [comment]
Easy fix: add `install-bin` as a make dependency of `internal-tests`. Might be annoying when running the test suite though, since it would rebuild Agda in the middle of the tests.

**Comment by andreasabel** [comment]
> Easy fix: add install-bin as a make dependency of internal-tests.

I imagine this won't work since then for `make install-bin test` cabal will be called twice, and each call to `cabal install` costs me 20sec.  (Since cabal unconditionally runs the linker even if nothing has changed.)

**Comment by UlfNorell** [comment]
I think your imaginary `make` is not the same as the real `make` and you'll find that it will only call `cabal install` once.

**Comment by nad** [comment]
Sometimes I edit the source code while running the test suite, and I want to decide by myself whether or not to recompile.

**Comment by andreasabel** [comment]
Ok, then maybe this is just a FAQ.
