### ISSUE TITLE
Internal error for syntax declaration

### ISSUE THREAD

**Issue by ice1000** [agda/agda#3285]
![image](https://user-images.githubusercontent.com/16398479/47055347-089a8500-d185-11e8-9f15-961167ff5148.png)
This works fine, but:
![image](https://user-images.githubusercontent.com/16398479/47055358-17813780-d185-11e8-84f2-1513e21838b8.png)

This code causes the parser internal error.

**Comment by ice1000** [comment]
I know the code is invalid, but it can't be the reason for the compiler to crash.

**Comment by gallais** [comment]
Note that it's easier for us if you submit *code* rather than just screenshots.
This way we don't have to transcribe whatever is in the image into text.

**Comment by ice1000** [comment]
```agda
open import Data.List
open import Data.Bool

postulate _>>=_ : {A B : Set} -> List A
                -> (A -> List B) -> List B

filter : {A : Set} -> (A -> Bool) -> List A -> List A
filter p xs = do x    <- xs
                 true <- p x ∷ [] where false -> []
                 x ∷ []

syntax filter a = a
```

**Comment by fredrikNordvallForsberg** [comment]
Minimal example:
```
f : Set -> Set
f x = x

syntax f a = a
```
results in

```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/Syntax/Concrete/Operators/Parser.hs:296
```

**Comment by ice1000** [comment]
Great!
