### ISSUE TITLE
Postfix projections should not have hiding information

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#3289]
Something is not quite right:

```agda
record R : Set where
  field
    x : Nat

open R {{...}}

f₁ f₂ f₃ : R
g₁ g₂ : R → Nat

-- This is fine.
x ⦃ f₁ ⦄ = 0

-- THIS WORKS BUT MAKES NO SENSE!!!
f₂ ⦃ .x ⦄ = 0

-- Error: Wrong hiding used for projection  R.x
f₃ .x = 0

-- Error: No instance of type R was found in scope
-- when checking that r is a valid argument to a function of type
-- ⦃ r : R ⦄ → Nat
g₁ r = r .x

-- Same error as g₁
g₂ r = r ⦃ .x ⦄
```

I propose that it should not be allowed to put postfix projections in (any kind of) braces, and consequently not complain about wrong hiding for postfix projections.

**Comment by jespercockx** [comment]
I'll take a look at this.

**Comment by jespercockx** [comment]
I fixed the problem where postfix projections could have hiding information. The patch by @andreasabel allowed postfix projections for instance-opened records on the LHS, but it's still not allowed on the RHS. I'll bump the milestone but leave this open for the remaining enhancement.

**Comment by jespercockx** [comment]
Interactive case splitting still puts curly braces around the postfix projections, this should be fixed before the release.

**Comment by jespercockx** [comment]
Example:
```agda
{-# OPTIONS --postfix-projections #-}

open import Agda.Builtin.Nat

record R : Set where
  field
    x : Nat → Nat

open R {{...}}

f : R
f .x = {!!}
```
Case splitting on result produces the following nonsense:
```agda
f : R
f ⦃ .x ⦄ x₁ = ?
```

**Comment by jespercockx** [comment]
I fixed the interactive case split and improved the message for when the user writes this nonsense manually. Again bumping to 2.6.1 for the RHS enhancement.

**Comment by andreasabel** [comment]
Remaining problem is:
```agda
record R : Set₁ where
  field
    p : Set

open R {{...}}

works test : R → Set
works r = p ⦃ r ⦄

test r = r .p

-- ERROR
-- Nat should be a function type, but it isn't
-- when checking that r is a valid argument to a function of type
-- ⦃ r = r₁ : R ⦄ → Nat
```

**Comment by andreasabel** [comment]
The type checker sends expression `r .p` through `Syntax.Abstract.Views.appView` which puts `Proj Postfix p` in the head and `r` as `defaultNamedArg`.  The `checkApplication` phase then treats this as just `p r`.  
I think the proper solution is to have an `elimView` for abstract syntax and then a `checkElimination` phase that treats postfix-projections differently from prefix-projections.

Interestingly enough, `test` checks fine if `p` is ambiguous, since then `inferOrCheckProjApp` takes over.

**Comment by andreasabel** [comment]
> The `checkApplication` phase then treats this as just `p r`.

I patched this so that `checkApplication` will see `p {{ r }}`, retrieving the correct `ArgInfo` from the definition of `p`.
