### ISSUE TITLE
Allow generalization in module telescopes

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#3291]
```agda
module _ where

variable A : Set

module _ (x : A) where -- generalizable variable not allowed here
  y = x
```

**Comment by ice1000** [comment]
An off-topic question but I don't know where else can I ask:

Where can I find documentation related to telescopes? https://agda.readthedocs.io/en/latest/language/telescopes.html This page is empty.

**Comment by UlfNorell** [comment]
The [mailing list](https://lists.chalmers.se/mailman/listinfo/agda) is a better place for questions like this.
