### ISSUE TITLE
Generalized variables in applied modules don't work

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#3292]
```agda
open import Agda.Builtin.Equality

module Vars (A : Set) where
  variable
    x : A

-- Panic: Unbound name: Issue3121._.x [0,10,12]@8066984681118411118
-- when checking that the expression
-- {A : Set} (let open Vars A) → ;Issue3121.x ≡ ;Issue3121.x has type _2
r : {A : Set} (let open Vars A) → x ≡ x
r = {!!}

-- An internal error has occurred. Please report this as a bug.
-- Location of the error: src/full/Agda/TypeChecking/Reduce/Fast.hs:148
record R : Set₁ where
  field
    A : Set
  open Vars A
  field
    f : x ≡ x
```

**Comment by UlfNorell** [comment]
Module application in general seems to be broken:
```agda
module _ where

open import Agda.Builtin.Equality
open import Agda.Builtin.Nat

module Vars (A : Set) where
  variable
    x : A

data It {A : Set} : A → Set where
  it : ∀ x → It x

open Vars Nat
ret : It x
ret {x = x} = it x
-- An internal error has occurred. Please report this as a bug.
-- Location of the error: src/full/Agda/TypeChecking/Reduce/Fast.hs:148
```

**Comment by UlfNorell** [comment]
It seems hard to give a reasonable semantics to generalisable variables from let-opened modules. The only thing that makes sense is to do the generalisation at the point of the let, but this leads to hard questions about nested generalisations which I'm pretty sure we don't want to worry about. I've fixed this issue by given a nice error message if you try to use generalisable variables from let-opened modules.

If we get around to a proper fix of #434, we could allow `variable` declarations between fields directly.

**Comment by nad** [comment]
The following code no longer works:
```agda
module Example where

module M where

  variable
    A : Set

module _ (open M) where

  postulate
    x : A
```
Is this intended? I don't see any semantic problems with this code.

**Comment by UlfNorell** [comment]
This is intended. Supporting it is not worth the complication of having let-opened generalisable variables sometimes be allowed and sometimes not.
