### ISSUE TITLE
Use of irrelevant arguments with copatterns and irrelevant fields

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3309]
The code below doesn’t type check with the error `Variable b is declared irrelevant, so it cannot be used here when checking that the expression b has type ;B (fst (f a _))` at the last character.

That doesn’t make sense to me, we are defining the second projection of `f a b`, and `snd` is an irrelevant field, so it should not be a problem that `b` is declared irrelevant, right?

And defining `f a b = (a , b)` instead works fine.

```agda
record Σ (A : Set) (B : A → Set) : Set where
  constructor _,_
  field
    fst : A
    .snd : B fst
open Σ

f : {A : Set} {B : A → Set} (a : A) .(b : B a) → Σ A B
fst (f a b) = a
snd (f a b) = b
```

**Comment by andreasabel** [comment]
This checks fine in Agda-2.5.4.1.  
agda-bisect blames it on commit e12b34845025f3e1e8a7361bbb52b9f9dec986b2 :
```
Date:   Wed Apr 25 13:11:56 2018 +0200
    [ refactor ] Update the context relevance at the start of LHS checking instead of at the recursive call
```

**Comment by andreasabel** [comment]
Fixed by also updating the clause telescope using `inverseApplyRelevance`.  Necessary since the refactoring removed that update in https://github.com/agda/agda/commit/e12b34845025f3e1e8a7361bbb52b9f9dec986b2#diff-eead6d9c75712f58755e483984d87ed3L748
