### ISSUE TITLE
agda-bisect: Cannot interrupt with C-c

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3311]
On Mac OS X at least, `agda-bisect` cannot be cancelled with Ctrl-C.

**Comment by nad** [comment]
It works fine for me under a different OS.

I've observed that if I type Ctrl-C once, then the program typically shuts down in an orderly way, but if I type it twice, then I might have to do some cleanup afterwards to get the repository back to its original state (more or less).

**Comment by andreasabel** [comment]
Cannot reproduce now.  I will reopen if I can reproduce it.
