### ISSUE TITLE
Crash in Substitute.hs

### ISSUE THREAD

**Issue by useronym** [agda/agda#3312]
Using the definition of `DList` from [1]:
```agda
open import Data.List
open import Data.Fin

data ListD {I : Set} (T : I → Set) : List I → Set where
  nilD  : ListD T []
  consD : ∀ {x xs} → (elem : T x) → (rest : ListD T xs) → ListD T (x ∷ xs)
```
I am trying to define a lookup function, but having trouble with the return type for some reason:
```agda
lookupD : {I : Set} {T : I → Set} {xs : List I} → ListD T xs → (at : Fin (length xs)) → {!lookup ? ?!}
lookupD xs at = {!!}
```
Attempting to fill the hole in the type, I get an error message:
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Substitute.hs:72
```

[1] https://arxiv.org/abs/1808.09234

This is on Agda 2.5.4.1.

**Comment by nad** [comment]
This bug seems to have been fixed in the development version.

**Comment by asr** [comment]
@nad, why did you add the `not-in-changelog` label?

**Comment by asr** [comment]
Also fixed in 2.5.4.2.

**Comment by nad** [comment]
Because this had already been fixed. However, this does not guarantee that there is another ticket for it, so feel free to remove the label if you want to.

**Comment by asr** [comment]
You shouldn't use the `not-in-changelog` label on issues on *released versions* but already fixed in upstream. I removed the label.

**Comment by nad** [comment]
If an issue is reported twice, then I don't think we should include the duplicate report in the changelog.

(However, in this case I couldn't be bothered to find out if the problem in the OP had actually been reported before.)
