### ISSUE TITLE
Result type is non-fibrant when pattern matching on multiple elements of a HIT

### ISSUE THREAD

**Issue by fsestini** [agda/agda#3314]
I'm hitting an error when defining n-ary (with n > 1) functions out of HITs by pattern matching on more than one argument. I'm on a21ac60 of Agda and 9fda0c8 of the cubical library.

Consider Z:

```agda
data Z : Set where
  pos      : ℕ → Z
  neg      : ℕ → Z
  sameZero : pos 0 ≡ neg 0
```

I get the following error when trying to write down addition directly, with no auxiliary functions, by pattern matching on both arguments:

```agda
_+Z_ : Z → Z → Z
pos x +Z pos x₁ = ?
pos x +Z neg x₁ = ?
pos x +Z sameZero x₁ = ?
neg x +Z z' = {!!}
sameZero x +Z z' = {!!}
```

```
The result type is non-fibrant when generating hcomp clause: 
{φ : I} (_ : I → Partial φ Z) (_ : Z) → Z
when checking the definition of _+Z_
```

Is this intended behaviour? How should we handle pattern matching on n-ary functions when more than one arguments involve path constructors?

**Comment by Saizan** [comment]
Hi, thanks for the report. This looks like a bug to me.

It's funny I can only trigger it by that specific configuration of patterns, e.g. splitting on both x and y at the same time works fine.
```agda
_+Z_ : Z → Z → Z
pos x +Z pos x₁ = { }0
pos x +Z neg x₁ = { }1
pos x +Z sameZero x₁ = { }2
neg x +Z pos x₁ = { }3
neg x +Z neg x₁ = { }4
neg x +Z sameZero x₁ = { }5
sameZero x +Z pos x₁ = { }6
sameZero x +Z neg x₁ = { }7
sameZero x +Z sameZero x₁ = { }8
```

From the type error it sounds like it's trying to generate a clause for the case where both arguments are ```hcomp```, I need to think more about that case.

**Comment by potato4444** [comment]
Here is a slightly simpler case that manifests the same bug, only needs the interval instead of the integers.
```agda
{-# OPTIONS --cubical #-}

module bugreport-2 where

open import Agda.Builtin.Cubical.Path

data Interval : Set where
  pos : Interval
  neg : Interval
  zeroes-identified : pos ≡ neg 

bad : Interval → Interval → Interval
bad pos pos = ?
bad pos neg = ?
bad pos (zeroes-identified j) = ?
bad neg y = {!!}
bad (zeroes-identified i) y = {!!}
```
