### ISSUE TITLE
Internal error frequently showing

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#3317]
I just updated Agda for the first time in a while, and get this internal error all the time, although weirdly, it... seems to work, type check the file, color everything in emacs, and then display the internal error:

```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Serialise/Instances/Common.hs:178
```

Looking at the logs, it says it can't find the paths for any of the Agda files used, but... when I try opening these files, they're definitely there, and they're absolute paths, so I'm not sure why it says it can't find them. And as I said above, it's saying this after it's already type checked everything, so clearly it did find all those files since it used them for typechecking.

**Comment by nad** [comment]
This sounds like #3199. Are you using the development version, or 2.5.4.1?

**Comment by identicalsnowflake** [comment]
I think the dev version, `agda --version` shows `Agda version 2.7.0-de976e2`.

**Comment by nad** [comment]
Are you using the `future` branch? The problem seems to be fixed on the `master` branch.

**Comment by identicalsnowflake** [comment]
Ya, I'm on `future`. I'll try `master`.

**Comment by UlfNorell** [comment]
@identicalsnowflake `future` is actually `2.5.4` right now. Since we haven't got any features that shouldn't go in `2.6.0` we're not bothering to keep `future` up-to-date. You'd be better off picking either `2.5.4.1` (or soon `2.5.4.2` I guess) or `master`.

**Comment by identicalsnowflake** [comment]
Ok, ya I've switched to `master` and everything works.
