### ISSUE TITLE
Lots of primitives and builtins are not declared in the primitive/builtin modules

### ISSUE THREAD

**Issue by nad** [agda/agda#3318]
Lots of (mostly but not only cubical) primitives and builtins are not declared in the primitive/builtin modules. I guess most or all of them should be.

The following primitives are missing:
* `primFaceForall`
* `primGlue`
* `primIdElim`
* `primLevelMax`
* `primLevelSuc`
* `primLevelZero`
* `primPushOutElim`
* `primPushOutForward`
* `primPushOutHComp`
* `primSetOmega`
* `prim^glue`
* `prim^unglue`

The following builtins are also missing:
* `COMPGLUE`
* `EQUIVFUN`
* `EQUIVPROOF`
* `EQUIV`
* `PATHTOEQUIV`
* `PUSHOUTINL`
* `PUSHOUTINR`
* `PUSHOUTPUSH`
* `PUSHOUT`
* `REWRITE`

**Comment by nad** [comment]
For some reason there are both builtins and primitives for levels. Is this the reason for not binding the primitives in the builtin modules?

@jespercockx and @andreasabel, is there a reason for not binding `REWRITE` in the builtin modules?

@Saizan, is there a reason for not binding the various cubical builtins and primitives?

**Comment by jespercockx** [comment]
There's no particular reason why there's no binding for `REWRITE` afaik. Sometimes you want to bind it to a different constant than the builtin equality (e.g. for heterogeneous rewriting), but as a default I think it's fine to bind it to the builtin equality.

**Comment by nad** [comment]
OK, then it could be bound in `Agda.Builtin.Rewrite` or perhaps `Agda.Builtin.Equality.Rewrite`.

**Comment by gallais** [comment]
I vote for `Agda.Builtin.Equality.Rewrite` (and we should move `Agda.Builtin.EraseEquality` to `Agda.Builtin.Equality.Erase`).

**Comment by nad** [comment]
> and we should move `Agda.Builtin.EraseEquality` to `Agda.Builtin.Equality.Erase`

I've already done this. (But perhaps I hadn't pushed when you wrote that comment.)

**Comment by nad** [comment]
Two questions remain:

* For some reason there are both builtins and primitives for levels. Is this the reason for not binding the primitives in the builtin modules?

* @Saizan, is there a reason for not binding the various cubical builtins and primitives?

**Comment by UlfNorell** [comment]
The level primitives are for implementation purposes and should not be bound by the user. They should be added to this list:
https://github.com/agda/agda/blob/ffecec4a177270c0144c94b7b43cd5f51e9c3580/src/full/Agda/TypeChecking/Rules/Decl.hs#L623-L627

**Comment by nad** [comment]
I removed the level primitives.

**Comment by UlfNorell** [comment]
ping @Saizan Is there a plan for the cubical builtins not currently declared?

**Comment by Saizan** [comment]
I have removed some and bound the remaining cubical builtins.
I assume we can close this now.
