### ISSUE TITLE
The QuickLaTeX backend handles field labels in record expressions incorrectly

### ISSUE THREAD

**Issue by nad** [agda/agda#3322]
The QuickLaTeX backend does not handle field labels in record expressions correctly. The following document is compiled without problems (by XeLaTeX) when the LaTeX backend is used, but not when the QuickLaTeX backend is used:
```latex
\documentclass{article}

\usepackage{agda}

\renewcommand{\AgdaField}[1]{\ensuremath{#1}}

\usepackage{amsmath}
\usepackage{newunicodechar}
\newunicodechar{₁}{\ensuremath{{}_{\text{1}}}}
\newunicodechar{₂}{\ensuremath{{}_{\text{2}}}}
\newunicodechar{⊥}{\bot}

\pagestyle{empty}

\begin{document}

\begin{code}
record R : Set₂ where
  field
    ⊥ : Set₁

r : R
r = record { ⊥ = Set }
\end{code}

\end{document}
```
The QuickLaTeX backend currently generates the following code for the last line:
```latex
\>[0]\AgdaFunction{r}\AgdaSpace{}%
\AgdaSymbol{=}\AgdaSpace{}%
\AgdaKeyword{record}\AgdaSpace{}%
\AgdaSymbol{\{} ⊥ \AgdaSymbol{=}\AgdaSpace{}%
\AgdaPrimitiveType{Set}\AgdaSpace{}%
\AgdaSymbol{\}}\<%
```
Note that `\AgdaField` is not applied to `⊥`. My guess is that no aspect is generated for this token.

**Comment by nad** [comment]
This is a regression, presumably related to #3120 (see 209639d927054a4e88cecc820fc6c7ff0d3813ea).

**Comment by andreasabel** [comment]
In #3120, I removed the highlighting of record fields coming from the scope checker.  This is actually not necessary, since the disambiguation information from the type checker will overwrite the aspects produced by the scope checking highlighting pass.

Fixed by restoring the removed lines for extracting highlighting info of fields.
