### ISSUE TITLE
Make BUILTIN EQUALITY more permissive

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3330]
I would like to be able to use rewrite on an identity type obtained by wrapping a record around the normal identity type. But `BUILTIN EQUALITY` is not allowed for such an identity type, even though it is just as usable as a normal one.

```agda
data _≡'_ {A : Set} (a : A) : A → Set where
  refl' : a ≡' a

record _≡_ {A : Set} (a b : A) : Set where
  constructor make≡
  field
    box : a ≡' b

pattern refl = make≡ refl'

--{-# BUILTIN EQUALITY _≡_ #-}

postulate
  N : Set
  _+_ : N → N → N
  n n' m m' : N
  p : n ≡ n'
  q : m ≡ m'

test : (n + m) ≡ (n' + m')
--test rewrite p | q = refl  -- This is what I want to write
test = helper p q where
  helper : {x y : N} (x= : x ≡ n') (y= : y ≡ m') → (x + y) ≡ (n' + m')
  helper refl refl = refl
```
Uncommenting the BUILTIN EQUALITY gives:
```
Builtin EQUALITY must be a data type with a single constructor
when checking the pragma BUILTIN EQUALITY _≡_
```

**Comment by andreasabel** [comment]
Mmh there was a BUILTIN REFL before, but this got removed.  Now, without the REFL builtin, there is no easy way to make Agda understand what you intend to use for reflexivity.

**Comment by UlfNorell** [comment]
This would complicate things a lot in the implementation and the workaround is very simple:
```agda
test rewrite p .box | q .box = refl
```

**Comment by guillaumebrunerie** [comment]
Ah, thanks for the workaround!
