### ISSUE TITLE
Strange termination error with the identity type in Prop

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3332]
The code below should work but it says `Termination checking failed` for the function `test`.
It works if the identity type is `Set`-valued instead.
It also works if `test` is written using `cong`/`ap` instead of `rewrite`.

```agda
{-# OPTIONS --prop #-}

data _≡_ {A : Set} (a : A) : A → Prop where
  refl : a ≡ a
{-# BUILTIN EQUALITY _≡_ #-}
  
data List (A : Set) : Set where
  [] : List A
  _∷_ : A → List A → List A

_++_ : {A : Set} → List A → List A → List A
[] ++ l = l
(x ∷ xs) ++ l = x ∷ (xs ++ l)

test : {A : Set} (l : List A) → (l ++ []) ≡ l
test [] = refl
test (x ∷ xs) rewrite test xs = refl
```

**Comment by jespercockx** [comment]
I think we shouldn't support `Prop`-valued `BUILTIN EQUALITY` since, at least at the moment, it is impossible to implement `J` for it (which is used implicitly by `rewrite`).

**Comment by guillaumebrunerie** [comment]
Well, rewrite could still work as long as you are always building a `Prop` (which is the case here).

By the way, are there plans for making it possible to implement `J` for the `Prop`-valued identity type?

**Comment by jespercockx** [comment]
> Well, rewrite could still work as long as you are always building a Prop (which is the case here).

True, but it seems safer to turn off the possibility of having `Prop`-valued equality as the built-in equality until someone checks that it actually makes sense in all cases where the built-in equality is used. I can leave this issue open in case someone wants to do the work, but it's currently not high on my priority list.

> By the way, are there plans for making it possible to implement J for the Prop-valued identity type?

I know Gaëtan has been working on adding this to `sProp` in Coq. One problem that this implies a strong version of `UIP`, unless you restrict it to equality for types in some universe of 'strict h-sets'. The actual implementation of such a feature would have to work similarly to `primEraseEquality`/`primTrustMe` in Agda, since it's not allowed to actually look at the proof of equality. So far I haven't implemented it yet because I first wanted the basic form of `Prop` to get some more testing before going wild with new extensions.

**Comment by guillaumebrunerie** [comment]
Actually the original issue had nothing to do with `rewrite`. Using `with` instead triggers the same error:
```agda
{-# OPTIONS --prop #-}

data _≡_ {A : Set} (a : A) : A → Prop where
  refl : a ≡ a
  
data List (A : Set) : Set where
  [] : List A
  _∷_ : A → List A → List A

_++_ : {A : Set} → List A → List A → List A
[] ++ l = l
(x ∷ xs) ++ l = x ∷ (xs ++ l)

test : {A : Set} (l : List A) → (l ++ []) ≡ l
test [] = refl
test (x ∷ xs) with xs ++ [] | test xs
... | _ | refl = refl
```
```
Termination checking failed for the following functions:
  test
Problematic calls:
  test (x ∷ xs) (xs ++ []) (test xs)
```

> True, but it seems safer to turn off the possibility of having Prop-valued equality as the built-in equality until someone checks that it actually makes sense in all cases where the built-in equality is used.

I thought the only thing the built-in equality is used for is the `rewrite` construct, which is just syntactic sugar for `with`. So I don’t see how turning off rewrite for it is any safer.

**Comment by guillaumebrunerie** [comment]
And here is the same example using only `Squash` and the usual identity type instead of a `Prop`-valued identity type (it still doesn’t pass the termination checker)

```agda
{-# OPTIONS --prop #-}
open import Agda.Builtin.Equality
open import Agda.Builtin.List

data Squash (A : Set) : Prop where
  sq : A → Squash A

postulate
  A : Set

_++_ : List A → List A → List A
[] ++ l = l
(a ∷ l) ++ l' = a ∷ (l ++ l')

test : (l : List A) → Squash (l ++ [] ≡ l)
test [] = sq refl
test (x ∷ l) with test l
... | sq eq with l ++ [] | eq
...   | _ | refl = sq refl
```

**Comment by jespercockx** [comment]
The error message is complete bonkers:
```
Termination checking failed for the following functions:
  test
Problematic calls:
  test (x ∷ xs) (xs ++ []) (test xs)
```
and the manual expansion of `with`  works just fine:
```agda

mutual
  test : {A : Set} (l : List A) → (l ++ []) ≡ l
  test [] = refl
  test (x ∷ xs) = test-with xs (xs ++ []) (test xs) x

  test-with : {A : Set} (xs w : List A) → w ≡ xs → (x : A) → (x ∷ w) ≡ (x ∷ xs)
  test-with xs _ refl x = refl
```
The only possible explanation is that this has to do something with the with-inlining in the termination checker. Summoning @andreasabel to see if he can explain what's going on.

**Comment by jespercockx** [comment]
> I thought the only thing the built-in equality is used for is the rewrite construct, which is just syntactic sugar for with. So I don’t see how turning off rewrite for it is any safer.

Besides for `rewrite`, builtin equality is also used for `primErase` and `primForceLemma`. But I don't see how it would hurt to have these use a `Prop` instead of a `Set` for equality, so perhaps I was just being overly cautious. So I'll revert my patch prohibiting builtin equality in Prop, since it didn't actually fix the issue here.

**Comment by andreasabel** [comment]
I wonder whether the removal of the ellipsis can shed some light on the termination issue:
```agda
  test : (l : List A) → Squash (l ++ [] ≡ l)
  test [] = sq refl
  test (x ∷ l) with test l
  test (x ∷ l) | sq eq     with l ++ [] | eq
  test (x ∷ l) | .(test l) | .l | refl = sq refl
```
There is a recursive call in a dot pattern which might not be handled correctly.  It is not present for a hand-unrolling of `with`:
```agda

mutual

  test : (l : List A) → Squash (l ++ [] ≡ l)
  test [] = sq refl
  test (x ∷ l) = aux (test l)

  aux : ∀ {l x} → Squash ((l ++ []) ≡ l) → Squash (x ∷ (l ++ []) ≡ x ∷ l)
  aux {l} (sq eq) = aux2 (l ++ []) eq

  aux2 : ∀ {l x} w → w ≡ l → Squash (x ∷ w ≡ x ∷ l)
  aux2 {l} .l refl = sq refl
```
Brings memories of #142 back...  Didn't you finally clean up that issue, @jespercockx ?  I dimly remember that your refactoring simplified the handling of such "2nd generation dot patterns".

**Comment by andreasabel** [comment]
Note: `--without-K` makes the problem go away, hinting and with-inlining.

It was indeed a problem with the with-inliner, choking on a `DontCare` inserted due to `Prop`.
