### ISSUE TITLE
Confusing error message when a file without --prop imports a file with --prop

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3333]
I’m not exactly sure what is the intended semantics of having a file with `Prop` disabled importing a file with `Prop` enabled, but there seems to be some unexpected behaviour (or at least a very confusing error message).

First file:
```agda
{-# OPTIONS --prop #-}

module M where

data _≡_ {A : Set} (a : A) : A → Prop where
  refl : a ≡ a
```
Second file:
```agda
open import M

ap : {A B : Set} (f : A → B) {a a' : A} → a ≡ a' → f a ≡ f a'
ap f refl = refl
```
Error message:
```
Cannot split on datatype in Prop unless target is irrelevant
when checking that the pattern refl has type a ≡ a'
```
It works if we add `{-# OPTIONS --prop #-}` to the second file.

**Comment by jespercockx** [comment]
Well, let it be on record that I was against hiding `Prop` under a flag ;)

I guess the right thing to do is to refuse using any `Prop`s unless the flag is enabled (so in your example, there would be an error when stating the type of `ap` already).

**Comment by jespercockx** [comment]
I see a few options here:

- Keep track for each definition whether it uses `Prop` in some way and give an error message when such a definition is used in a file without `--prop`
- Refuse to import any file with `--prop` from a file that doesn't use `--prop` itself
- Allow the *usage* of `Prop`s even when `--prop` is disabled, the flag would then only control whether it is allowed to define *new* `Prop`s
- Just remove `--prop` and make `Prop` default again (my preferred solution ;) ).

@andreasabel since you are the advocate of hiding `Prop` under the `--prop` flag, what solution do you prefer?

**Comment by fredrikNordvallForsberg** [comment]
From a user's point of view, isn't this similar to the situation with `--cubical`? I would vote for allowing using Props, but not defining new ones (or mentioning `Prop`) unless `--prop` is on. 

My plan for #2487 when I have more time next week is to track what features a file actually uses in the interface, which is different from what options are turned on. Importing a file using `--prop` from a file using `--no-prop` would then be an error, while importing it from a file with no explicit option would just record that also the importing file is (implicitly) using `--prop`.

**Comment by jespercockx** [comment]
Actually that's not really a possibility since the constraint solved currently assumes there are **no** occurrences of `Prop` at all when `--prop` is not enabled. And having this rule in the constraint solver was the whole reason for hiding `Prop` under a flag in the first place...

**Comment by guillaumebrunerie** [comment]
Maybe in such cases `--prop` could be enabled automatically together with a warning
```
The option --prop was automatically enabled because the imported file F.agda already uses --prop
```

**Comment by andreasabel** [comment]
@fredrikNordvallForsberg wrote:
> Importing a file using --prop from a file using --no-prop would then be an error, while importing it from a file with no explicit option would just record that also the importing file is (implicitly) using --prop.

This does make sense but is a quite drastic change of the semantics of flags.  Now they are boolean, then it would be 3-valued: yes, no, I-dont-mind.

**Comment by andreasabel** [comment]
@jespercockx and I constructed another problematic case:

File 1, with Prop enabled:
```agda
{-# OPTIONS --prop #-}

module ImportProp where

postulate
  F : Prop → Set
```
File 2, Prop not enabled, importing file 1:
```agda
open import ImportProp

Brace : Set₁  -- start mutual

X : Set₁
data D (A : X) : Set
X = {!!}

data D (A : X) where
  c : A → D A

postulate
  foo : (A : X) → F A

Brace = Set  -- end mutual
```
Since Prop is not enabled, a heuristics kicks in to solve `X` to the bottom sort which is `Set`.  The later use in `foo` leads then to error:
```
Set != Prop
when checking that the expression A has type Prop
```
While in the OP a better error message could be easily given, this error message is more subtly referring to Prop (just in the terms it prints).

**Comment by UlfNorell** [comment]
I was never a fan of the `--prop` flag, but it's starting to look like it's really not worth the hassle. The only reason it was introduced was to be able to keep the "`Set` is the smallest sort"-heuristic, and I don't think that's terribly important. The workaround is very simple and we are moving towards a more interesting sort system so it's unreasonable to be able to keep that heuristic forever.

**Comment by nad** [comment]
> Importing a file using `--prop` from a file using `--no-prop` would then be an error,

Sounds good to me.

> while importing it from a file with no explicit option would just record that also the importing file is (implicitly) using `--prop`.

I don't think this is a good idea. I would prefer sticking to default values for flags.

**Comment by ice1000** [comment]
I like the issue number

**Comment by jespercockx** [comment]
Removing `--prop` seems to be the easiest way to fix this issue. Anyone against?

**Comment by nad** [comment]
Are there any interesting models or axioms that are ruled out by the addition of `Prop`?

**Comment by jespercockx** [comment]
I would guess any model like that would also be ruled out by irrelevance, which is enabled by default.

**Comment by guillaumebrunerie** [comment]
Also it seems to me that it is impossible to use `Prop` by accident, you have to actually write down the keyword `Prop` (or use a library that does). So someone concerned about such models could just not use `Prop` (unlike for instance `--with-K/--without-K` which is much more subtle to detect).

**Comment by nad** [comment]
Generally speaking I think we should make it possible to turn off more features, not less, to cater to those who want their code to be compatible with as many theories as possible. I would thus suggest that we make it possible to turn off irrelevance, just like we can turn off universe polymorphism, sized types, pattern matching, and other features.

**Comment by nad** [comment]
> I was never a fan of the `--prop` flag, but it's starting to look like it's really not worth the hassle. The only reason it was introduced was to be able to keep the "`Set` is the smallest sort"-heuristic, and I don't think that's terribly important.

I don't have a strong opinion on this heuristic, but I still think it should be possible to turn off `Prop`. I don't mind if the default is `--prop`.

For those interested in minimal theories we could perhaps include a flag that turns off as many features as possible, `--minimal`, and then they can pick and choose between the features that they want/need.

**Comment by jespercockx** [comment]
Ok, then I'll leave the `--prop` flag in. That leaves us with two choices:
- If we want to keep the current heuristic, then we should make `--no-prop` 'infective', i.e. you should not be able to import files using `--prop` from a file using `--no-prop`. 
- If we remove the heuristic, then we can choose to make it infective or non-infective, or we could even have different flags for both options.

**Comment by jespercockx** [comment]
Now `--prop` is infective thanks to @fredrikNordvallForsberg , so can this issue be closed?

**Comment by fredrikNordvallForsberg** [comment]
Indeed, I now get the error message
```
/tmp/second.agda:1,1-18
Importing module M using the --prop flag from a module which
does not.
when scope checking the declaration
  open import M
```
instead of the confusing error message reported.
