### ISSUE TITLE
Remove `ImpossiblePragma`?!

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3336]
We have the `ImpossiblePragma` in concrete syntax that triggers an `__IMPOSSIBLE__`.  
While it might have been useful in the initial implementation of Agda, I am not sure we need it anymore.  We have plenty of bugs now that trigger internal errors. :D

It is a bit annoying when one does a case distinction over pragmas.

It is used in #2447, but we have lots of means to trigger errors, thus it is not vital here.

**Comment by ice1000** [comment]
Sounds like you're treating bugs as features :D

**Comment by andreasabel** [comment]
Not sure this was worth opening an issue.

**Comment by andreasabel** [comment]
@ice1000  
> Sounds like you're treating bugs as features :D

And the other way round:
```agda
{-# IMPOSSIBLE #-}
```
leads to 
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/ImpossibleTest.hs:9
```
asking to report the feature as a bug.

**Comment by andreasabel** [comment]
> Not sure this was worth opening an issue.

Yeah, it wasn't.
