### ISSUE TITLE
Display elements of propositions as underscores?

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3337]
I switched some project from using irrelevance to using `Prop` and one thing I noticed is that in goals, irrelevant arguments were displayed simply as an underscore, which helped reduce the clutter.

Given that arguments in `Prop` are supposed to correspond to irrelevant arguments, maybe the same feature should be implemented for `Prop`?

**Comment by jespercockx** [comment]
Good idea, I'll look into it.

**Comment by jespercockx** [comment]
We currently have no infrastructure for printing terms differently based on their type, so this is not so easy to implement.

**Comment by guillaumebrunerie** [comment]
I noticed that they are sometimes printed with a prefix dot (even though I use only `Prop`, no irrelevance). I’m not sure where the dot comes from, but whatever prints the dot should probably be able to print it as an underscore. The dot isn’t always there though…

**Comment by jespercockx** [comment]
I implemented printing apllications of *defined symbols* in `Prop` as `_` (unless `--show-irrelevant` is enabled). This does not quite cover all cases, but hopefully proofs that don't use any definitions are not very large anyway. Feel free to reopen if there is still too much clutter.

**Comment by jespercockx** [comment]
With the fix of #4120 all elements of a proposition should now be printed as `_`, not just the `Def`s.

**Comment by nad** [comment]
#4120 is still open. Did you mean some other issue?

**Comment by jespercockx** [comment]
It's part of a series of issues that is *hopefully* fixed by https://github.com/agda/agda/commit/7383b7e4b637a3371524abeebc76c66659573067, but I'm waiting for confirmation by @guillaumebrunerie since I cannot run the test myself due to limited RAM.
