### ISSUE TITLE
Can’t give generalized variables

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3341]
```agda
postulate
  A : Set
  B : A → Set

variable
  {a} : A

postulate
  f : (b : B a) (b' : B {!a!}) → {!!}
```
In the code above, it should be possible to give `a` but instead we get the error
```
Generalizable variable file.a is not supported here
when scope checking a
```

**Comment by UlfNorell** [comment]
This one is a bit tricky. There are two cases

- giving an already generalised variable
- giving a generalisable variable not mentioned in the type

In the latter case we would have to recheck the type and reload the file, something which the current give has no support for. In the former case, we would need to do some special magic to figure out which bound variable a generalisable variable maps to. This would take some nontrivial amount of work.

For now, both cases can be worked around by disabling the goal highlighting (<kbd>C-c C-x C-d</kbd>), deleting the `{!` `!}`, and reloading the file. If it comes up a lot, you might even consider writing some elisp to do it for you.

**Comment by martinescardo** [comment]
This does happen a lot to me, and I am currently forced to do the deletion, rewriting and reloading, which is why I ended up here. If you do ctrl-c-ctrl-s in a hole in a situation such as this, then the contents of the hole is inferred, but it is not given, with the message that a generalizable variable is not supported in the hole. I would be very convenient to have this fixed one way or another.

**Comment by martinescardo** [comment]
In the cases I am considering and where I have a problem, the generalizable variable is in scope, and so doesn't have to be introduced as something freshly new to the scope when filliing the hole (automatically or manually).

**Comment by martinescardo** [comment]
NB. Sometimes (a very small proportion of the cases I've tried) ctrl-c-ctrl-s does fill a hole with generalizable variables that are in scope (I've just hit one case now).

**Comment by UlfNorell** [comment]
Already generalised variables are now in scope in holes. If you want to write something that introduces new generalisations into the hole you have to <kbd>C-c C-x C-d</kbd> as before.
