### ISSUE TITLE
Disable compilation with GHC 8.6.1

### ISSUE THREAD

**Issue by m0davis** [agda/agda#3344]
In emacs, load the following file twice (C-c C-l):
```agda
data D : Set where
  d1 : D
  d2 : D

foo : D → D
foo d1  = d1
foo _   = d1
```
After the first load, there are no errors or warnings, as expected. However, upon loading the second time, agda reports:
```
Exact splitting is enabled, but the following clause could not be
preserved as definitional equalities in the translation to a case
tree:
  foo _ = d1
when checking the definition of foo
```
I have checked that my `Agda2 Program Args` are set to `STANDARD` in emacs. If I add `{-# OPTIONS --no-exact-split #-}` to the top of the file, then there are no warnings. So interactive mode is setting a global `--exact-split`?

**Comment by gallais** [comment]
Could be related to #3187.

Which version of Agda are you using? I couldn't reproduce the issue with any of the
versions I have installed (2.5.4 to 2.5.4.2 and some version of 2.6.0).

**Comment by m0davis** [comment]
The version I was using was, I believe, from yesterday. Just now, I rebuilt using the lastest on master (12afa483a6f820251edf0986a76681a418dce427) via stack and the 8.6.1 yaml. 

It is tricky to reproduce! I am now getting the opposite behavior: now, the first load (after deleting the `agdai` file) gives a warning about exact-splitting, but subsequent loads do not have the warning. Steps to reproduce:

```
emacs --version
GNU Emacs 26.1
agda --version
Agda version 2.6.0-12afa48
rm AgdaBugExactSplit.agdai 
emacs AgdaBugExactSplit.agda
C-c C-l
(exact-split warning displayed)
C-c C-l
(no warning displayed)
```
I also found that if I include a top-level module declaration (`module AgdaBugExactSplit where`), then the exact-split warning displays on every load. While toying around I still noticed the originally-reported behavior but I have not figured out how to reproduce it consistently. I look forward to hearing if you have any luck reproducing a fallacious exact-split warning.

**Comment by m0davis** [comment]
Btw, my .emacs is simply:
```
(load-file (let ((coding-system-for-read 'utf-8))
                (shell-command-to-string "agda-mode locate")))
```

**Comment by m0davis** [comment]
Actually, I can get the exact-split warning without emacs at all: delete the agdai file and then run `agda AgdaBugExactSplit.agda`. (The file is the same as that in the OP.)

**Comment by asr** [comment]
> via stack and the 8.6.1 yaml.

Agda is ignoring the warnings on GHC 8.6.1. It seems that the issue is related to a serious bug in GHC 8.6.1 (see https://github.com/agda/agda/issues/3245). I suggest to use other version of GHC.

**Comment by m0davis** [comment]
Thanks @asr. I rebuilt using the yaml for GHC 8.4.4, problem solved.

**Comment by andreasabel** [comment]
I suppose `working-as-intended` implies `not-in-changelog`.  Removing the latter.

**Comment by asr** [comment]
> I suppose `working-as-intended` implies `not-in-changelog`.  Removing the latter.

Right. I added [this](https://github.com/agda/agda/blob/ac38171335f3cdd4be92326c1b3aace484320803/HACKING.md#closing-issues) information to `HACKING.md`.

**Comment by andreasabel** [comment]
Can we do something about ghc 8.6.1 here?  I imagine some pragma in the source could that makes compilation of ghc 8.6.1 crash with a suitable error like  "Agda cannot be built with ghc 8.6.1 due to a compiler bug".

**Comment by asr** [comment]
I suggest to wait the release of GHC 8.6.2 for disabling the compilation with 8.6.1 (which actually is tested on Travis).

**Comment by asr** [comment]
We don't support GHC 8.6.1 so I'm closing the issue.

**Comment by asr** [comment]
Back-ported into 2.5.4.3.
