### ISSUE TITLE
Generalization for variables bound in the type signature

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3349]
```agda
postulate
  A : Set
  a : A
  P : A → Set

variable
  x : A

postulate
  Q : P x → Set
  test : ∀{p} → Q p → Q p

-- the first Q is yellow
-- _x_14 : A  [ at 11,17-18 ]
```
I'd expect the generalized implicit arguments to `Q` to be solved.  Currently one is unsolved, which looks like a bug.

**Comment by UlfNorell** [comment]
This is working as intended.
- There is no notion of generalizable implicit arguments. Defining `Q` as above or as `∀ {x} → P x → Set` is equivalent in every way.
- (corollary) No generalization happens unless you use at least one declared generalizable variable.

**Comment by andreasabel** [comment]
Sorry, I forgot the `variable` declaration for `p`.
```agda
postulate
  A : Set
  a : A
  P : A → Set

variable
  x : A
  p : P x

postulate
  Q : P x → Set
  test : ∀{p} → Q p → Q p  -- first Q is yellow

-- Unsolved metas
-- _x_15 : A  [ at 12:17-18 ]
```
(Doesn't cause a difference in behavior, thus, I did not notice.)

We can take Twelf as a model for comparison (even though it is different in many aspects.)
```twelf
A : type.
P : A -> type.
Q : P X -> type.
test : {p} Q p -> Q p.
```
You can try Twelf at http://twelf.plparty.org/live/
It infers the types as
```
A : type.
P : A -> type.
Q : {X:A} P X -> type.
test : {X1:A} {p:P X1} Q p -> Q p.
```

**Comment by UlfNorell** [comment]
If you actually use `p` it does work:
```agda
variable
  x : A
  p : P x

postulate
  Q : P x → Set
  test : Q p → Q p
```

**Comment by andreasabel** [comment]
What I want here is to give an argument explicitly (for the obvious purpose of passing it explicitly to the function later) or implicitly (for the purpose of fixing its position), but still omit its type and have it figured out by generalization.

Without such a feature, my code will inevitably look as follows, if I want to make full use of generalization:
```agda
substLem' : EqDEN (⦅ lookup σ x ⦆ γ) (lookupEnv x (evalS σ γ))
substLem' {x = vz}   {σ = u ∷ σ} = reflDEN (⦅ u ⦆ _)
substLem' {x = vs x} {σ = u ∷ σ} = substLem' {x = x} {σ = σ}

substLem : EqDEN (⦅ subst σ t ⦆ γ) (⦅ t ⦆(evalS σ γ))
substLem {t = var x} {σ = σ} = substLem' {x = x} {σ = σ}
substLem {t = app t u} {σ = σ} =
  ...
   (substLem {t = t} {σ = σ})
   (substLem {t = u} {σ = σ})
```
I would like to give generalized variables explicitly, to get code like this:
```agda
substLem' : ∀ x σ → EqDEN (⦅ lookup σ x ⦆ γ) (lookupEnv x (evalS σ γ))
substLem' vz     (u ∷ σ) = reflDEN (⦅ u ⦆ _)
substLem' (vs x) (u ∷ σ) = substLem' x σ

substLem : ∀ t σ → EqDEN (⦅ subst σ t ⦆ γ) (⦅ t ⦆(evalS σ γ))
substLem (var x)   σ = substLem' x σ 
substLem (app t u) σ =
  ...
   (substLem t σ)
   (substLem u σ)
```

**Comment by andreasabel** [comment]
Duplicate of #3352.
