### ISSUE TITLE
Implicit generalized arguments should not be given by position

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3350]
This should work:
```agda
postulate
  A : Set
  a : A

data P : A → Set where
  isA : P a

variable
  x : A

postulate
  Q : P x → Set

test : ∀{p : P x} → Q p → Q p
test {p} x = {!p!}  -- C-c C-c

-- Cannot split on argument of non-datatype A
-- when checking that the expression ? has type Q ;p
```
Hidden arguments inserted by generalization should not be positional hidden arguments, thus, be skipped when a positional hidden argument is up next.

**Comment by UlfNorell** [comment]
Duplicate(ish) of #3280. Let's keep the discussion to that issue.

**Comment by asr** [comment]
@UlfNorell, please add the `language-change` label to #3280.
