### ISSUE TITLE
Fields should shadow generalizable variables, no?

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3351]
```agda
postulate A : Set
variable  x : A

record R : Set where
  field x : A

-- 5,9-14
-- Multiple definitions of x. Previous definition at
-- 2,11-12
-- when scope checking the declaration
--   field x : A
```
It is surprising that fields cannot shadow generalizable variables.

**Comment by UlfNorell** [comment]
Fields cannot shadow other declarations. I see no reason why generalizable variables should behave differently. If the suggestion is to allow fields to shadow arbitrary definitions please open another issue for that.

**Comment by andreasabel** [comment]
Indeed, it is a general questions if declaration in a module can shadow declarations of the parent module. [Link to #359 as umbrella issue for shadowing.]

However, in the case of `variable`, which are declarations for administrative purposes only (or can they be exported and imported!?), it seems even more surprising that they cannot be shadowed.

**Comment by UlfNorell** [comment]
They can be imported and exported just like any other definition.

**Comment by ajrouvoet** [comment]
I understand the rationale here, but I agree that the behavior is surprising, if not annoying.
E.g in the following example we use the "shadowing field" to make explicit how this thing should be quantified. Analogue to explicit `forall` quantification in function definitions.

```Agda
  record R : Set where
    field
      {s}       : ℕ
      x         : X s
      y         : Y s

  f : ∀ {s} → (x : X s) → (y : Y s) → Rel x y
```

Forcing the user to chose a non-standard name for the field {s} or to jump through hoops to only bring the generalization in scope for the rest of the module.

Is this really working "as intended"?

**Comment by andreasabel** [comment]
> They can be imported and exported just like any other definition.

Aha!
Well, this is a bit unexpected as well, but may be useful.  
Yet I am thinking that `variable` declarations should be `private` by default.  
We should have `public` blocks to override the default.  (This could be useful in other situations as well, e.g., in a `private` block.)

**Comment by UlfNorell** [comment]
No. Treating all declarations uniformly is a better design. Maybe you mostly want them to be private (although I'm not sure), but it's not worth adding a whole new dimension of public-by-default vs private-by-default declarations for people to remember.

**Comment by nad** [comment]
> Treating all declarations uniformly is a better design.

I agree.

**Comment by andreasabel** [comment]
This issue (fields cannot shadow variables) is really obnoxious.
It is a bit funny to change the shadowing rules for /all/declaration forms just because of this issue here.  (I was much less annoyed by not being able to shadow a definition in a local module.)
But if we have to, then change the shadowing rules in general.

**Comment by nad** [comment]
> This issue (fields cannot shadow variables) is really obnoxious.

Why? In the OP you gave an example showing that they cannot, but you didn't explain why this is a problem. Is it because you use short, non-descriptive names both for generalisable variables and for fields? Perhaps you should try to use descriptive names for fields.

**Comment by andreasabel** [comment]
It is not unreasonable to use short names for hidden record fields.

**Comment by andreasabel** [comment]
Issue continued in #3801 in generalized form, concerning shadowing of outer declarations.
