### ISSUE TITLE
The wiki should support HTTPS

### ISSUE THREAD

**Issue by alexvong243f** [agda/agda#3363]
Hi,

The description of the project writes `Agda is a dependently typed programming language / interactive theorem prover. https://wiki.portal.chalmers.se/agda/pmwiki.php`. However, when I visit https://wiki.portal.chalmers.se/agda/pmwiki.php, I get the following error:
```
The requested URL was not found on this server. The link on the ">referring page seems to be wrong or outdated. Please inform the author of ">that page about the error. If you entered the URL manually please check your spelling and try again. 
```
Is it because the home page of agda has been moved to somewhere else? If so, what is the new official home page?

**Comment by UlfNorell** [comment]
The wiki doesn't do `https`. As far as I can see we don't have any `https` links though.

**Comment by alexvong243f** [comment]
Ulf Norell <notifications@github.com> writes:

> The wiki doesn't do https. As far as I can see we don't have any https links though.
>
Thanks for the quick reply! So the underlying reason must be the fact
that I've enable the option to block all unencrypted requests...

Btw, I really hope the site would switch to use HTTPS as HTTP is not
secure (it's vulnerable to MITM attacks). For examples, by using
Let's Encrypt[0]. Also, both mozilla[1] and google[2] have plans to
deprecate HTTP eventually.

[0]: https://letsencrypt.org/
[1]: https://blog.mozilla.org/security/2015/04/30/deprecating-non-secure-http/
[2]: https://www.chromium.org/Home/chromium-security/marking-http-as-non-secure

**Comment by jespercockx** [comment]
Wait, why don't we serve the wiki over https??! I know it is old-school, but that is really something we should fix. If it's too hard with the current hosting, then I see that as (another) good reason to move it somewhere else.

**Comment by ice1000** [comment]
BTW there're a lot of outdated materials on Agda wiki. Like, the instance argument parts say Agda will search for type constructors, but

```agda
open import Agda.Builtin.Nat
postulate f : {{ Nat }} -> Nat
_ : Nat
_ = f
```

doesn't work.

**Comment by jespercockx** [comment]
It seems counterproductive to keep both the wiki and the official documentation on readthedocs up-to-date. I think it would be better to go over all the old wiki pages with documentation, move everything that's still relevant to the docs, and then remove them.

**Comment by nad** [comment]
You're discussing several distinct issues above:
* Enable HTTPS.
* Move the wiki to some other host. (And switch to different wiki software?)
* Merge relevant wiki material into the user manual, and remove outdated material.

I'd like to add that, if we move to some other host, then I'd like to see the wiki history preserved in some way. I wouldn't want to lose, say, the documentation of all the old Agda meetings.

**Comment by ice1000** [comment]
I wonder if the domain name www.agda-lang.org is owned by someone in the team?

**Comment by UlfNorell** [comment]
Yes, me.

**Comment by ice1000** [comment]
@UlfNorell Any plan to create a website with the domain name? We can make use of GitHub Page's custom domain name functionality.

**Comment by UlfNorell** [comment]
No immediate plans, but some vague long-term ambitions. I'm a bit daunted by the prospect of migrating the wiki though...

**Comment by alexvong243f** [comment]
Ulf Norell <notifications@github.com> writes:

> No immediate plans, but some vague long-term ambitions. I'm a bit daunted by the
> prospect of migrating the wiki though...
>
Long-term ambitions are of course great in the long run, but is it
possible to apply a quick / temporary fix like using Let's Encrypt for
the current wiki?

**Comment by nad** [comment]
@UlfNorell, have you asked the Chalmers support team whether they are willing to enable HTTPS?

**Comment by nad** [comment]
> Btw, I really hope the site would switch to use HTTPS as HTTP is not secure (it's vulnerable to MITM attacks).

Given that anyone can update the wiki I think there are other attack vectors.

**Comment by UlfNorell** [comment]
> have you asked the Chalmers support team whether they are willing to enable HTTPS?

I have not.

**Comment by alexvong243f** [comment]
Nils Anders Danielsson <notifications@github.com> writes:

>  Btw, I really hope the site would switch to use HTTPS as HTTP is not secure (it's
>  vulnerable to MITM attacks).
>
> Given that anyone can update the wiki I think there are other attack vectors.
>
Yeah, you are right that there are certainly other attack vectors. But I
think MITM are more "stealthy" (editing the wiki would leave traces
visible to everyone, while MITM would only leave traces to those being
targeted). I could be overlooking other factors though ...

**Comment by ice1000** [comment]
So come on, let's build a github.io website and use `CNAME` to map our custom domain to it!

When I see my friends (I'm an undergrats freshman) see www.idris-lang.org or www.fstar-lang.org and go to learn those languages I feel really jealous!

**Comment by ice1000** [comment]
> So come on, let's build a github.io website and use CNAME to map our custom domain to it!

I mean I just want to see a website, which is in any sense better than simply a wiki.
We can by the way have https then.

**Comment by jespercockx** [comment]
I have sent a mail to Chalmers support to ask if they can enable https for the current wiki.

**Comment by jespercockx** [comment]
I got an email back from the support:

> Hi Jesper
> 
> This is in my incredibly long queue of upgrades and updates I need to make.
> 
> Can you send me the source(s) of your information so I can read the article(s) myself to determine the exact course of events that will happen and when.

I sent them the two links that @alexvong1995 posted here. However, I do not have great confidence that anything will happen anytime soon, so if we are serious about https we should look into other solutions.

**Comment by jespercockx** [comment]
Good news: I just got an email back from support saying that they have enabled https on the wiki, and any http requests should now be redirected to https automatically. I still think it's a good idea to have a nice front page for Agda which is not a wiki, but at least this issue can be closed now.

**Comment by ice1000** [comment]
Please update the link here
![image](https://user-images.githubusercontent.com/16398479/50048213-217dd300-0101-11e9-9808-0ccae2c830d0.png)

**Comment by ice1000** [comment]
And here
![image](https://user-images.githubusercontent.com/16398479/50048221-335f7600-0101-11e9-9d8b-8c505ca87b2e.png)

**Comment by jespercockx** [comment]
It seems I don't have the permission to change these links. @UlfNorell can you do it?

**Comment by UlfNorell** [comment]
Done.
