### ISSUE TITLE
Funny scope error when trying to import as qualified

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3364]
```agda
import Agda.Builtin.Nat as Builtin.Nat
```
gives the funny error:
```
Not in scope:
  as at 1,25-27
when scope checking as
```

**Comment by andreasabel** [comment]
See also #481, in particular https://github.com/agda/agda/issues/481#issuecomment-129023545.

**Comment by andreasabel** [comment]
Now a warning is issued:
```
`as' must be followed by an unqualified name
when scope checking the declaration
  open import Agda.Builtin.Nat as Builtin.Nat
```
and the part `as Builtin.Nat` is highlighted as dead code.

**Comment by ice1000** [comment]
Is `as` treated as a keyword during lexing/parsing? I see it's not highlighted as a keyword in the HTML backend.

**Comment by gallais** [comment]
You are free to use `as` pretty much anywhere. It's quite common to find it used as
the variable name for a value of type `List A`.

**Comment by ice1000** [comment]
Get it.

**Comment by andreasabel** [comment]
See also #3457.
