### ISSUE TITLE
Provide some simple LaTeX backend templates

### ISSUE THREAD

**Issue by nad** [agda/agda#3372]
@gallais suggests (https://github.com/agda/agda/issues/2452#issuecomment-436244106) that we should provide some templates for use with the LaTeX backend. I think this sounds like a good idea. We could include:
* Templates for pdfLaTeX as well as LuaLaTeX/XeLaTeX.
* Templates for `article`, `beamer`, and perhaps some other commonly used class (like `acmart`).

Given that the options listed above are orthogonal this would be 4-6 templates.

I suggest that we set things up so that the templates are included in the user manual, but still part of the test suite.

**Comment by JacquesCarette** [comment]
Huge thumbs up. I can definitely offer to test the end results on my machines (I have Windows/Mac/Linux).

**Comment by nad** [comment]
I have written seven templates. The following items remain to be taken care of:

* The test suite should include some infrastructure for building and testing these templates. I have stated in the user manual that we have tested the templates using TeX Live 2018. This text might need to be modified.

* I saw that the makefile contains support for building a PDF version of the user manual. This PDF file currently does not contain links to the templates. This should be taken care of in some way.

Furthermore it is of course possible to modify the templates.

**Comment by ice1000** [comment]
BTW should we have a separated repo for lAtEx templates?

**Comment by nad** [comment]
I have not included any templates for LuaLaTeX. Perhaps the XeLaTeX ones work for LuaLaTeX as well.

**Comment by nad** [comment]
> BTW should we have a separated repo for lAtEx templates?

No, each template is linked from the user manual.

**Comment by ice1000** [comment]
> No, each template is linked from the user manual.

So it's not a part of the Agda compiler? I thought the compiler is supposed to output the template itself.

**Comment by nad** [comment]
It isn't. I don't even call them templates in the user manual, I call them examples.

**Comment by ice1000** [comment]
Ok. Please fix tests on the master branch. @nad

**Comment by nad** [comment]
I've fixed the test suite, and verified that some templates work under LuaLaTeX. (Not the acmart one: For some reason the version of acmart that I am using, v1.55, has a special case for XeLaTeX, but not for LuaLaTeX.)

I've also added a comment about how the file names do not link to the files in the PDF version of the manual.

**Comment by gallais** [comment]
Thanks a lot!

**Comment by ice1000** [comment]
Nice work!

**Comment by UlfNorell** [comment]
The xelatex tests don't work for me (MacOS). Some quick googling suggest (for instance [here](https://tex.stackexchange.com/questions/74383/fontspec-error-font-not-found-on-mac-os-x)) that xelatex will only use system fonts, and it's impossible to make it look in the TeX distribution.

To fix the problem I disabled the xelatex examples on MacOS.

**Comment by nad** [comment]
If you had this problem, then I can imagine that others might also encounter it. Could you write something about it in the "common pitfalls" (see #3371) section of the user manual?

**Comment by UlfNorell** [comment]
Don't think it's worth documenting. It's not something Agda specific, and I doubt we have many xelatex-MacOS users.

**Comment by nad** [comment]
At the time of writing none of the issues in [that section](https://agda.readthedocs.io/en/latest/tools/generating-latex.html#known-pitfalls-and-issues) are specific to Agda.

**Comment by asr** [comment]
> I have written seven templates. The following items remain to be taken care of:

> * I saw that the makefile contains support for building a PDF version of the user manual. This PDF file currently does not contain links to the templates. This should be taken care of in some way.

In the above commit, I added the templates to the PDF version of the user manual (using Sphinx directives `.. only:: builder_html` and `.. only:: builder_latex`).

**Comment by asr** [comment]
> The xelatex tests don't work for me (MacOS)

I had the same problem on Ubuntu. I fixed it by running

```
$ sudo apt-get install fonts-lmodern fonts-linuxlibertine
```

**Comment by nad** [comment]
Could you add some instructions to the reference manual?

**Comment by asr** [comment]
I didn't install LaTeX/LuaLaTeX/XeLaTeX from the Ubuntu packages but from TeX Live, so I don't want to add possibly very incomplete instructions for the users on Ubuntu.

**Comment by nad** [comment]
I added a warning about fonts.

**Comment by andreasabel** [comment]
@UlfNorell 
> Don't think it's worth documenting. It's not something Agda specific, and I doubt we have many xelatex-MacOS users.

Their number could be growing... #5133.
