### ISSUE TITLE
Support code fragments which are supposed to raise a compile error in literate mode

### ISSUE THREAD

**Issue by ice1000** [agda/agda#3374]
This is important for the literate mode, we can see error message and show it to the readers in this case.

I'm not sure about agda's current behavior and future plan about this feature, please correct me if I've made incorrect assumptions.

**Comment by nad** [comment]
The benefit/cost ratio of such a feature sounds rather small to me. It might be nice when writing a tutorial.

**Comment by ice1000** [comment]
Yes, that's what I mean! Especially for literate agda.

**Comment by ice1000** [comment]
Like you can add this in the generated HTML: when mouse hovered on an error/warning, the error message displays. This should be very nice

**Comment by nad** [comment]
I guess that you want to support code that is marked as being incorrect in some way, so that you can first present something that is incorrect, and then some correct code. See #2114. If we implement that kind of feature, then we should support it also in the LaTeX and HTML backends.

**Comment by ice1000** [comment]
Please add duplicate label

**Comment by ice1000** [comment]
Oh.
