### ISSUE TITLE
Too much erasure in strict backends

### ISSUE THREAD

**Issue by divipp** [agda/agda#3380]
I started to use the JS backend and I think I have found a bug.

Agda erases `(λ _ → tt)` but then later it tries to apply the erased function.

This is how to reproduce the bug  
(I only tried it with Agda 2.5.4.1 because I switched to NixOS and I could not install Agda from source yet):

Assume that `ErasureBug.agda` contains:

```agda
record ⊤ : Set where constructor tt

data ℕ : Set where
  zero : ℕ
  suc  : (n : ℕ) → ℕ

{-# BUILTIN NATURAL ℕ #-}

data Wrap (A : Set) : Set where wrap : A → Wrap A

appWrap : ∀ {A B : Set} → (A → B) → Wrap A → B
appWrap f (wrap a) = f a

app : ∀ {A B : Set} → (A → B) → A → B
app f a = appWrap f (wrap a)

works : ℕ
works = (λ _ → 42) ((λ _ → tt) 13)

-- (λ _ → tt) is erased but `app` tries to apply it
buggy : ℕ
buggy = app (λ _ → 42) (app (λ _ → tt) 13)
```

Assume that `index.html` contains:
```html
<!DOCTYPE html5>
<meta charset="UTF-8"></meta>
<html>
<body>
<button onclick='document.getElementById("display").innerHTML=exports["works"]'>works</button>
<button onclick='document.getElementById("display").innerHTML=exports["buggy"]'>buggy</button>
<div id="display"></div>
</body>
<script>
var exports = new Object;
function require(_) { return exports; }
exports.primIntegerFromString = function(x) { return parseInt(x); };
</script>
<script src="jAgda.ErasureBug.js"></script>
</html>
```

1.  Compile the Agda file with `agda --js --no-main ErasureBug.agda`
2.  Run `firefox index.html` (other browser should be OK)
3.  Clicking on `works` prints `42` but clicking on `buggy` prints `undefined`.
    In fact the bug can be detected in the javascript console already in step 2. because `buggy` is evaluated at load time.

**Comment by divipp** [comment]
The bug is present in the master branch.

**Comment by nad** [comment]
Do we still support this backend?

**Comment by UlfNorell** [comment]
It's still in there, so I guess it's at least "supported", if not actually supported. It's lacking a maintainer, though.

Regardless, I suspect this issue is a problem for any strict backend, and I do think we want to support people implementing those.

**Comment by xekoukou** [comment]
It segfaults on agda-ocaml.

**Comment by xekoukou** [comment]
Here is the treeless representation of buggy : 
```
TApp (TDef erasure.app) [TErased,TErased,TLam (TLit (LitNat _ 42)),TApp (TDef erasure.app) [TErased,TErased,TErased,TLit (LitNat _ 13)]]
```

and here is the same code with a ```main``` function that triggers the segmentation fault in agda-ocaml.

```agda

module erasure where

open import Agda.Builtin.IO 
open import Agda.Builtin.Int
open import Agda.Builtin.Nat
open import Agda.Builtin.String


show : Nat → String
show n = primShowInteger (pos n)

record ⊤ : Set where constructor tt


postulate
  putStrLn : String → IO ⊤

{-# FOREIGN OCaml 
  let printEndline y world = Lwt.return (print_endline y)
#-}

{-# COMPILE OCaml putStrLn = printEndline #-}



data Wrap (A : Set) : Set where wrap : A → Wrap A

appWrap : ∀ {A B : Set} → (A → B) → Wrap A → B
appWrap f (wrap a) = f a

app : ∀ {A B : Set} → (A → B) → A → B
app f a = appWrap f (wrap a)

works : Nat
works = (λ _ → 42) ((λ _ → tt) 13)

-- (λ _ → tt) is erased but `app` tries to apply it
buggy : Nat
buggy = app (λ _ → 42) (app (λ _ → tt) 13)


main : IO ⊤
main = -- putStrLn (show works)
          putStrLn (show buggy)


```

**Comment by UlfNorell** [comment]
I pushed a fix. @xekoukou can you check that it also works for the OCaml backend after updating it to pass the `EagerEvaluation` flag to the treeless compiler.

**Comment by xekoukou** [comment]
@UlfNorell It works now. Thanks.
