### ISSUE TITLE
No insertion of implicit arguments for definitions between fields of records

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3381]
The code below fails with the error
```
A !=< {C : Set} → A of type Set
when checking that the expression fst has type {C : Set} → A
```

This is rather unexpected, as for usual definitions, the `C` would be automatically abstracted over.

```agda
record _×_ (A B : Set) : Set where
  constructor _,_
  field
    fst : A

  fst' : {C : Set} → A
  fst' = fst

  field
    snd : B
```

**Comment by andreasabel** [comment]
See #434 (umbrella issue for problems with record type declarations that contain method definitions).

**Comment by guillaumebrunerie** [comment]
If someone runs into the same problem, note that as a workaround you can define `fst'` as
```agda
  fst' : {C : Set} → A
  fst' {_} = fst
```

**Comment by jespercockx** [comment]
I'm closing this in favour of #434
