### ISSUE TITLE
Rewriting and cubical

### ISSUE THREAD

**Issue by mortberg** [agda/agda#3382]
I'm trying to make the following Path into a rewrite rule:

https://github.com/agda/cubical/blob/master/Cubical/HITs/Circle.agda#L51

by adding the `--rewriting` flag and

```
{-# BUILTIN REWRITE _≡_ #-}

hcompIntEmpty : (n : Int) → hcomp (λ _ → empty) n ≡ n
hcompIntEmpty n i = hfill (λ _ → empty) (inc n) (~ i)

{-# REWRITE hcompIntEmpty #-}
```

But it doesn't seem to work. Any ideas? Maybe the rewriting rules don't work with `--cubical`? ( @jespercockx @Saizan )

**Comment by jespercockx** [comment]
It used to work but I think I may have broken something in one refactoring while fixing another bug in rewriting.

For example, at https://github.com/agda/agda/blob/bce8a456d4628756da94d08730eceeec9b6c32bf/src/full/Agda/TypeChecking/Rewriting/NonLinMatch.hs#L97 and https://github.com/agda/agda/blob/bce8a456d4628756da94d08730eceeec9b6c32bf/src/full/Agda/TypeChecking/Rewriting/NonLinMatch.hs#L305

Is your code triggering one of these `__IMPOSSIBLE__`s? If not, could you please submit a self-contained test case?

**Comment by guillaumebrunerie** [comment]
Here is a self-contained test case. It doesn’t trigger any ``__IMPOSSIBLE__``, it just doesn’t seem to rewrite. The last line should work but it fails with the error
```
primHComp (λ i → isOneEmpty) n != n of type Int
when checking that the expression id↦ has type
primHComp (λ _ → isOneEmpty) n ↦ n
```

```agda
{-# OPTIONS --cubical --rewriting #-}

open import Agda.Primitive.Cubical public

postulate
  Int : Set
  _↦_ : {A : Set} → A → A → Set
  id↦ : {A : Set} {a : A} → a ↦ a

{-# BUILTIN REWRITE _↦_ #-}

postulate
  hcompIntEmpty : (n : Int) → primHComp (λ _ → isOneEmpty) n ↦ n

{-# REWRITE hcompIntEmpty #-}

test : (n : Int) → primHComp (λ _ → isOneEmpty) n ↦ n
test n = id↦
```

**Comment by mortberg** [comment]
Great, thanks a lot for fixing this so fast! I will include self-contained test cases in future bug reports.
