### ISSUE TITLE
Document the DISPLAY pragma

### ISSUE THREAD

**Issue by ice1000** [agda/agda#3383]
Currently we didn't document that:
![image](https://user-images.githubusercontent.com/16398479/48382689-32759780-e6b0-11e8-9b9e-16018b13f9d3.png)

**Comment by nad** [comment]
If you search for `{-# DISPLAY` in the changelog, then you can find some documentation that can be copied to the user manual.

**Comment by nad** [comment]
@gallais, you only documented one kind of pragma, not all that were listed in the OP.

**Comment by gallais** [comment]
? The OP was a screenshot of the current state of the doc to demonstrate `DISPLAY`
is not listed. Am I missing something?

**Comment by ice1000** [comment]
I don't think so. The fix looks good to me.

**Comment by nad** [comment]
Oh, I read the text as "Currently we didn't document \[list of undocumented pragmas\]".

**Comment by andreasabel** [comment]
The fix broke the test suite:
```
make user-manual-test
```
Agda complains:
```
Invalid DISPLAY pragma. Should have form {-# DISPLAY LHS = RHS #-}.
#-}<ERROR>
instance
    NumNat : Num Nat
...
```
