### ISSUE TITLE
Generate a Jekyll-compatible website with HTML backend

### ISSUE THREAD

**Issue by ice1000** [agda/agda#3386]
This should make blogging with Literate Agda Markdown mode a lot easier.

### Motivation

Me myself tried to use lagda to blog long ago, failed because the generated HTML didn't preserve the non-code contents. My blog (https://ice1000.org/lagda/) is using [Jekyll](https://jekyllrb.com/) to generate static website which is natively supported by GitHub Pages service, which is very nice. With #3313, I can now generate Markdown with my Agda codes highlighted, and Jekyll render the Markdown blogs for me. This is nice, but I still feel uncomfortable with it due to:

+ The `{{` and `}}` tokens in Agda means instance arguments, it's used a lot in my blog, while Jekyll is using a template engine call [liquid](https://shopify.github.io/liquid/) which treats `{{` and `}}` reserved symbols for preprocessing, resulting in some conflicts.
  + As a temporary solution, I used pandoc locally to generate complete HTML files, preventing liquid from trying to execute codes between `{{`s and `}}`s.
  + Shortcomings:
    + I have an automatic Markdown renderer already, why render the Markdown myself? This also makes the repository very large
    + Some CSS problems (I hate this)
+ Jekyll supports putting metadata (to specify the blog title, description, whether to enable MathJax, custom permalink, etc) at the beginning of each Markdown files. However, pandoc simply removes them during HTML generation.
  + As a temporary solution, I given up writing metadata in `.lagda.md` files and created [a script](https://github.com/ice1000/ice1000.github.io/blob/bb8490d3a6326179983a8250f059ebaf167a7876/assets/lagda/compile.sh) to insert the metadata into each HTML files generated by pandoc.
  + Shortcomings:
     + No longer customizable
     + Need to run this script every time before preview my website

### Goal

I just want to find a solution to all these problems listed above.
The ideal solution will be generating a Jekyll-compatible website where the users just need very little work to customize it and it's ready to be deployed. For people like me, we just put the generated files under a folder of an existing Jekyll website and that's it.
This will be very very nice for those who want to use literate Agda to blog!

To achieve this maybe we need to put some data files in `src/data`, which should be copied into the `html-dir` along with `Agda.css`.

Created an issue to collect opinions.

**Comment by ice1000** [comment]
This is my ultimate goal, after #3137 #3313 #3366 #3367 #3373 #3384

**Comment by ice1000** [comment]
So that everyone will be able to use a nice Jekyll template + Literate Agda to blog!

+ Nice UI by Jekyll
+ Index page by a `lagda.md` file which `import`s every blog, click to jump to the blog
+ Blog cross-reference with `import`s
+ Chapter cross-reference with sub`module`s and `import`s

Oh, I'm so excited!

**Comment by jespercockx** [comment]
It would be very nice indeed if this would work nicely! I will also try to use literate markdown files for my blog (using Hakyll), I'll report back here if there are any problems.

**Comment by jespercockx** [comment]
ps: your blog seems to be down at the moment.

**Comment by ice1000** [comment]
> ps: your blog seems to be down at the moment.

Are you sure? It works for me.

**Comment by jespercockx** [comment]
Hmm, it seems it's just blocking the VPN I'm using, without it works fine.

**Comment by ice1000** [comment]
> It would be very nice indeed if this would work nicely! I will also try to use literate markdown files for my blog (using Hakyll), I'll report back here if there are any problems.

Yes I read all your blogs, they're awesome. I read your without K paper too

**Comment by ice1000** [comment]
> Hmm, it seems it's just blocking the VPN I'm using, without it works fine.

Wow. Does that block all GitHub Pages websites?

**Comment by jespercockx** [comment]
>      Wow. Does that block all GitHub Pages websites?

Nope, but apparently it was blocking IPv6 addresses. After turning them back on it works fine. Sorry for the false alarm.

**Comment by ice1000** [comment]
Nevermind!

**Comment by ice1000** [comment]
Personally, I'd recommend providing a command line flag like `--html-template=[plain,jekyll,hexo,hakyll]`, so we can add more target type in the future.
The flag name is not good, do you guys have some suggestions?

**Comment by nad** [comment]
I don't really understand what you're trying to do, but I have a question: Should this be part of Agda, or could it be a separate tool (that might depend on the Agda library)? I would rather not tie Agda to various tools (Jekyll, Hakyll and so on) that I don't know anything about.

**Comment by ice1000** [comment]
I consider #3389 a more general approach.
I'm closing this one.
