### ISSUE TITLE
Highlight soft keywords as keywords in HTML backend?

### ISSUE THREAD

**Issue by ice1000** [agda/agda#3388]
Currently there're treated as symbols.

![image](https://user-images.githubusercontent.com/16398479/48441620-0282ce80-e75a-11e8-993f-652aecdd7b99.png)
![image](https://user-images.githubusercontent.com/16398479/48441646-0a427300-e75a-11e8-8d43-7a802485337d.png)

**Comment by ice1000** [comment]
`to` in import renaming as well.

**Comment by ice1000** [comment]
Oh! All symbols are highlighted the same, `forall` is treated the same as non-alphabetical symbols `∀`.

Is this good?

**Comment by nad** [comment]
I think it makes sense to highlight these two symbols that mean exactly the same thing in the same way. If you want to highlight all symbols as keywords (or vice versa), then you can tweak your local copy of `Agda.css`.

**Comment by ice1000** [comment]
What I meant is to highlight alphabetical symbols to make it look nicer.

**Comment by nad** [comment]
As I wrote: I think it makes sense to highlight these two symbols that mean exactly the same thing in the same way.

**Comment by ice1000** [comment]
Oh, sorry for my bad English.
