### ISSUE TITLE
Better vim syntax highlighting: here is the vim half

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#339]
When I `agda --vim' this:
```agda
  data X : Set where
    x : X

  app : ∀ {A B : Set} → (A → B) → A → B
  app f a = f a

  _∙_ : ∀ {A B : Set} → (A → B) → A → B
  f ∙ a = f a
```
I get this vim syntax file:
```
  syn match agdaConstructor "x"
  syn match agdaFunction "X"
  syn match agdaInfixFunction "∙"
  syn match agdaFunction "_∙_\|app"
```
but this one would be more useful:
```
  syn match agdaConstructor "\v(^|\s|[.(){};])@<=(x)($|\s|[.(){};])@="
  syn match agdaFunction "\v(^|\s|[.(){};])@<=(X)($|\s|[.(){};])@="
  syn match agdaInfixFunction "\v(^|\s|[.(){};])@<=(∙)($|\s|[.(){};])@="
  syn match agdaFunction "\v(^|\s|[.(){};])@<=(_∙_|app)($|\s|[.(){};])@="
```
The extra stuff ensures that tokens occur in isolation, e.g., don't highlight "x" in "axe". In detail, it uses lookbehind (@<=) and lookahead (@=) patterns to check that the tokens are surrounded by whitespace (\s), line begin (^), line end ($), or agda syntax ([.(){};]). The opening \v puts the pattern in "very magic" mode, which avoids having to write lots of \ to escape things.

Here are a few easy test cases for the file above:
```
  -- Highlighting
  x X app ∙
  .x.X.app.∙.
  ;x;X;app;∙;
  (x(X(app(∙(
  )x)X)app)∙)
  {x{X{app{∙{
  }x}X}app}∙}

  -- No highlighting
  ixiXiappi∙i
  -x-X-app-∙-
  →x→X→app→∙→
```

Original issue reported on code.google.com by `jdanbr...@gmail.com` on 29 Sep 2010 at 8:02

**Comment by andreasabel** [comment]
Nothing happened here for 6 years...  Feel free to resurrect once you start working on this. (Whoever you are.)

**Comment by ice1000** [comment]
Why not put this into `icebox`?

**Comment by nad** [comment]
That label was added rather recently.
