### ISSUE TITLE
Reloading a file compiled with --allow-unsolved-metas does not show the goals

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3392]
Steps to reproduce:
- Open (create) two files `test.agda` and `test2.agda` in emacs with the content shown below.
- Load `test2.agda`.
- Attempt to load `test1.agda`.

The question mark isn’t made into a goal. As a workaround, modifing `test.agda` allows one to load it.
This happens rather often to me in practice, as everytime I modify `test2.agda` and then try to go back to `test.agda`, I can’t work on the goals there anymore.

`test.agda:`
```agda
{-# OPTIONS --allow-unsolved-metas #-}

A : Set
A = ?
```

`test2.agda:`
```agda
open import test
```

**Comment by nad** [comment]
See #2475.
