### ISSUE TITLE
Internal error in mutual block with unsolved implicit argument in termination checker

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3394]
The code below fails with
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/Termination/Monad.hs:177
```
Removing the `{X : A}` or moving down the typing declaration of `Ploop` removes the internal error.

```agda
postulate
  A : Set
  B : Set
  P : B → Set

loop  : {X : A} (u : B) → B
Ploop :         {u : B} → P (loop u)

loop u = loop u
Ploop = {!!}
```

**Comment by andreasabel** [comment]
This was a forgotten initialization of `terSizeDepth` in the new `termType` termination checking function for types.

Thanks for reporting!
