### ISSUE TITLE
With the option --allow-unsolved-metas, the unsolved metas are not shown, only yellow

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3398]
When loading the file below, the `u` in the type of `v` is turned yellow (as its argument `X` is an unsolved meta), but the unsolved meta isn’t shown at all in the AgdaInfo buffer, which makes it pretty hard to debug, and is also very confusing to see yellow and no corresponding unsolved meta.

```agda
{-# OPTIONS --allow-unsolved-metas #-}

postulate
  A : Set
  P : A → Set
  u : {X : A} → A
  v : P u
```

**Comment by gallais** [comment]
What is the expected behaviour here? No yellow highlighting at all?

**Comment by guillaumebrunerie** [comment]
I think there should be yellow and the unsolved meta should be shown in the AgdaInfo buffer, just like when we don’t use `--allow-unsolved-metas`.
My understanding is that when working in some file, there should be no difference in behaviour whether this file has `--allow-unsolved-metas` or not. The only difference should be when *importing* such a file.
