### ISSUE TITLE
Obscure parse error with copattern and infix field

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3400]
The last line of the code below fails with a rather cryptic error:
```
Don't know how to parse (return x) $ tt. Could mean any one of:
  ((return x) $) tt
  _$_ (return x) tt
Operators used in the grammar:
  $ (infix operator, level 20) [_$_ (/home/gubr5004/Dropbox/Agda/Initiality/bug.agda:4,5-8)]
when scope checking the left-hand side (return x) $ tt in the
definition of return
```
Also I’m not sure why there is an error at all, what is ambiguous about that last line? How can it mean `((return x) $) tt`?

```agda
record Partial (A : Set) : Set₁ where
  field
    isDefined : Set
    _$_ : isDefined → A
open Partial

record Unit : Set where
  constructor tt

return : {A : Set} → A → Partial A
isDefined (return x) = Unit
(return x) $ tt = x
```

**Comment by nad** [comment]
> How can it mean `((return x) $) tt`?

I don't know exactly how copatterns are parsed, but I guess that this piece of text stands for `return` applied to three arguments. Perhaps this kind of ambiguity was @andreasabel's reason for introducing postfix projections.

**Comment by andreasabel** [comment]
Yes, @nad has explained it.  The contributing factors are:
- `$` is a distinct name from `_$_`.
- There is no _syntactic_ separation of pattern variables from other identifiers allowed in patterns (constructors, projections).  Thus Agda has to resort to guessing what is a pattern variable, and the heuristics is that any name not in scope as a constructor qualifies to be a pattern variable.

The obvious work-arounds are:
```agda
_$_ (return x) tt = x
return x ._$_ tt = x
return x Partial.$ tt = x
```
All of these workaround tell the parser upfront that `$` cannot be a pattern variable.

Not sure anything can be done about this issue without big changes to either language or parser.
Thus, I am closing it as FAQ.  Feel free to reopen if you have suggestions.

P.S.: On the printing side, #3142 is related.

**Comment by nad** [comment]
> Thus Agda has to resort to guessing what is a pattern variable, and the heuristics is that any name not in scope as a constructor qualifies to be a pattern variable.

And we also complain if a pattern variable matches a constructor that is only in scope with a qualified name.

Now that we have copatterns, doesn't it make sense to treat projections in the same way as constructors? I have not checked, but perhaps it suffices to add `FldName` to the following lists:

https://github.com/agda/agda/blob/3161248c2dcde48c19246b125a7a2ad0785d9d7a/src/full/Agda/Syntax/Concrete/Operators.hs#L266

https://github.com/agda/agda/blob/3161248c2dcde48c19246b125a7a2ad0785d9d7a/src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs#L571

**Comment by nad** [comment]
I tried changing the first line, and with that in place the code in the OP is accepted. However, the following code is rejected:
```agda
record R : Set₁ where
  field
    _+_ : Set → Set → Set

open R

+ : Set → Set
+ A = A
```
The problem is that `+` is now only treated as an infix operator. This is in line with how constructors are treated at the moment, the following code is rejected:
```agda
data D : Set where
  _+_ : D → D → D

+ : Set → Set
+ A = A
```
What do you say, should we go ahead with this change? I think I'm in favour of it. (For 2.6.1?)

The second line probably shouldn't be changed in the way that I suggested without also performing other changes. @andreasabel, I think you implemented this logic (99aa81639bba6689c1ddda64db0bde2fba819c15). Should it be extended with support for projections?

> And we also complain if a pattern variable matches a constructor that is only in scope with a qualified name.

And the pattern variable's type is an application of the constructor's data type. The following code is rejected:
```agda
module _ where

module M where

  data D : Set where
    c : D

F : M.D → M.D
F c = c
```
I don't see an obvious corresponding test for projections. The following code is already rejected:
```agda
module _ where

module M where

  record R : Set₂ where
    field
      _A : Set₁

G : M.R
G A = Set
```

**Comment by andreasabel** [comment]
> What do you say, should we go ahead with this change? I think I'm in favour of it. (For 2.6.1?)

Sounds reasonable.  
It does not hurt if the choice of names for pattern variables is restricted a bit; it will give less opportunity for confusion.

> @andreasabel, I think you implemented this logic (99aa816). Should it be extended with support for projections?

A priori, yes. (Without thinking a lot about the consequences.)

**Comment by nad** [comment]
I have already implemented it, but I don't want to resurrect the `future` branch just for this (I think having two active branches is too much of a hassle), so I won't push my changes just yet.

> A priori, yes. (Without thinking a lot about the consequences.)

I opened a new issue for this question (#3402).

**Comment by nad** [comment]
Given that the release of 2.6.0 has been delayed I decided to push this now. The change did not seem to have any effect on the standard library or nine of my own projects, so I'm hoping that it won't have much of an impact.
