### ISSUE TITLE
No option to prevent Erasure makes use of IORef and FunPtr from Haskell not possible

### ISSUE THREAD

**Issue by GregoryMorse** [agda/agda#3408]
This code does not work because Agda detects erasable types which are not truly erasable as they are really being used to merely pass and encapsulate Haskell data types.  Is there a workaround?  Why not add a {#- NON-ERASABLE -#} compiler option for data types with no constructor so that the Haskell code will work?  Obviously this causes a runtime crash due to erased being effectively a null pointer which writeIORef will crash on after newIORef already created an erased and not null FunPtr.

Perhaps the code should all just be in a simple Haskell wrapper function but it would be more interesting if Agda could represent every detail down to foreign imports without exception.

```agda
postulate
  CtrlEvent : Set

BOOL : Set
BOOL = Bool
Handler : Set
Handler = CtrlEvent → Agda.Builtin.IO.IO BOOL
PHANDLER_ROUTINE : Set
PHANDLER_ROUTINE = FunPtr Handler

data FunPtr (A : Set) : Set where

data IORef : Set → Set where

  mkHandler : Handler → Agda.Builtin.IO.IO PHANDLER_ROUTINE
  c_SetConsoleCtrlHandler : PHANDLER_ROUTINE → BOOL → Agda.Builtin.IO.IO BOOL
  freeHaskellFunPtr : {a : Set} → FunPtr a → Agda.Builtin.IO.IO ⊤
  nullFunPtr : {a : Set} → FunPtr a
  newIORef : {A : Set} → A → Agda.Builtin.IO.IO (IORef A)
  readIORef : {A : Set} → IORef A → Agda.Builtin.IO.IO A
  writeIORef : {A : Set} → IORef A → A → Agda.Builtin.IO.IO ⊤


{-# COMPILE GHC FunPtr = data FunPtr () #-}
{-# COMPILE GHC CtrlEvent = type CtrlEvent #-}
{-# COMPILE GHC mkHandler = mkHandler #-}
{-# COMPILE GHC c_SetConsoleCtrlHandler = c_SetConsoleCtrlHandler #-}
{-# COMPILE GHC nullFunPtr = \_ -> nullFunPtr #-}
{-# COMPILE GHC freeHaskellFunPtr = \_ -> freeHaskellFunPtr #-}
{-# COMPILE GHC IORef = data IORef () #-}
{-# COMPILE GHC newIORef = \_ -> newIORef #-}
{-# COMPILE GHC readIORef = \_ -> readIORef #-}
{-# COMPILE GHC writeIORef = \_ -> writeIORef #-}

initConsole : IO.IO (IORef PHANDLER_ROUTINE)
initConsole = ((♯ lift (newIORef nullFunPtr)) >>=
  (λ ref → ♯ ((♯ (lift (mkHandler (handler ref)))) >>=
  (λ r → ♯ ((♯ lift (writeIORef ref r)) >> 
  ♯ ((♯ (setConsole false ref)) >> (♯ return ref)))))))

handler : IORef PHANDLER_ROUTINE → CtrlEvent → Agda.Builtin.IO.IO Bool
handler ref _ = run (♯ ((♯ (putStr ((sET_BKGND_COLOR cLR_BLACK) ++ (sET_CURSOR 999 999) ++ "\n" ++ sHOW_CURSOR))) >> (♯ (setConsole true ref))) >>
  ♯ return false)

setConsole : Bool → IORef PHANDLER_ROUTINE → IO.IO ⊤
setConsole bRestore ref = (♯ ((♯ (lift (hSetEcho stdin bRestore))) >> (if not bRestore then ♯ ((♯ (lift (system (toCostring " ")))) >> (♯ return false)) else ♯ return false))) >>
  ♯ ((♯ lift (readIORef ref)) >>= λ h → ♯ ((♯ lift (c_SetConsoleCtrlHandler h (not bRestore))) >>
  (if bRestore then ♯ lift (freeHaskellFunPtr h) else ♯ return _)))

```

**Comment by UlfNorell** [comment]
The problem is that you defined `FunPtr` to be an empty data type, which is a lie. The correct way to do it is
```agda
postulate FunPtr : Set
{-# COMPILE GHC FunPtr = type FunPtr #-}
```
Exactly what you do for `CtrlEvent`.

The compiler really should catch this lie though, but the FFI coverage check doesn't work for empty types. I'll open a separate issue for this.

**Comment by UlfNorell** [comment]
> Thank you very much for the reply there. But now I cannot compile because I get endless kind errors - I have not seen any examples of how to deal with data type constructors which have kinds but must be postulated as `Set`.

You don't have to postulate them as `Set`. I wasn't reading your code carefully enough when suggesting the fix. It should of course be

```agda
postulate FunPtr : Set → Set
{-# COMPILE GHC FunPtr = type FunPtr #-}
```

**Comment by GregoryMorse** [comment]
Thank you very much for the reply there.  But now I cannot compile because I get endless kind errors - I have not seen any examples of how to deal with data type constructors which have kinds but must be postulated as Set.  The manual mentions this for type class instances via a dictionary method.

`    * Expecting one more argument to `T14'
      Expected a type, but `T14' has kind `* -> *'
    * In the type signature:
        d555 :: Bool
                -> T14 -> MAlonzo.RTE.Infinity AgdaAny MAlonzo.Code.IO.T6
     |
1148 |   Bool -> T14 -> MAlonzo.RTE.Infinity AgdaAny MAlonzo.Code.IO.T6
     |           ^^^`

In fact I had done exactly as you had suggested at first but I did not realize the encapsulated part just needed to be totally forgotten about - I tried to start moving as much Haskell code into Agda as I said to try to get down to purely foreign imports.  But all of the special hash tag terminated internal types and such cannot really be eliminated either.  There is a limit as to where such a task can go - and I think these are the magic hash unboxed types and foreign imports.

**Comment by GregoryMorse** [comment]
At this moment I am unsure if this can be done with type synonyms - its impossible to parameterize them in Agda and I cannot even find a trick to use lambdas to jacket the Haskell function calls when this involves the return values.

This is what led me to resolve this route by realizing it had to be done with a data type and an empty constructor - I have seen examples of almost all the possibly situations between Agda and Haskell but so far I have come up with no resolution for this seemingly obvious issue.

I suppose:

```
postulate
  newIORef : PHANDLER_ROUTINE → Agda.Builtin.IO.IO IORef
  readIORef : IORef → Agda.Builtin.IO.IO PHANDLER_ROUTINE
  writeIORef : IORef → PHANDLER_ROUTINE → Agda.Builtin.IO.IO ⊤

{-# COMPILE GHC FunPtr = type FunPtr Handler #-}
{-# COMPILE GHC IORef = type IORef PHANDLER_ROUTINE #-}

```
Certainly it works okay - but its really defeating the generality of kinds in Haskell.  So you have to make a definition specifically for each kind.  It feels a bit inelegant of a solution.  But it type checks and runs without crashing in the prior case.

**Comment by GregoryMorse** [comment]
Well at least this inquiry led to a genuine bug report :D - appreciate your help.

**Comment by GregoryMorse** [comment]
I can confirm the Set -> Set approach also works - the cleanest most general elegant solution.  I suppose it should have been obvious - I just had some mistakes when I initially tried that approach which led me in some circles to the empty data type.  The single Set approach works but the whole point of using a type checking system is somewhat being defeated if the kinds are arbitrarily ignored even if multi-kind usage is never present.

**Comment by GregoryMorse** [comment]
The Set -> Set data type case should still be added to the reference manual - is there a place to make such a request?

**Comment by UlfNorell** [comment]
Ideally you would make a PR with the suggested additions, otherwise opening a new issue here is fine.
