### ISSUE TITLE
Add ghcomp to get rid of empty systems in cubical agda

### ISSUE THREAD

**Issue by mortberg** [agda/agda#3415]
It would be great if cubical agda would implement "ghcomp" to get rid of empty systems. This should make it easier to prove things and computing faster (especially for HITs).

This operation can be defined using the existing `hcomp` operation as follows (idea due to @Saizan ):
```
ghcomp^i A [ r -> u ] u0 := hcomp^i A [ r -> u, ~ r -> u0 ] u0
```
This should then be used in `transp` for `Glue` where the "forall" operation occurs (as this is in only in one place it might be better to inline the above definition of ghcomp). In order to ensure that there are no empty systems we should also add a "validity" constraint on systems. This can be done by checking that r in `[ r -> u ]` is a (classical) tautology (one can maybe implement this more efficiently, but I don't think it will make much of a difference as the r are usually very small).

**Comment by jespercockx** [comment]
@Saizan please add a milestone when you accept a new issue!

**Comment by mortberg** [comment]
It would be very nice to have this as soon as possible! I suspect that it might make some things a lot faster and it would be very interesting to see if it can help with computing the Brunerie number (which I will define some day). As a first step I think we can just ignore the validity check and add the extra `~ r` where we use forall in transp for Glue. If I understand the code correctly this should be in `a1`, `pe` and `t1'alpha` in:

https://github.com/agda/agda/blob/master/src/full/Agda/TypeChecking/Primitive.hs#L975

**Comment by jespercockx** [comment]
Well, we have declared a feature freeze for 2.6.0, so 2.6.1 is likely the earliest release that could have it.

**Comment by mortberg** [comment]
Ok, I'm fine with just having this in the development version for experimenting. If it is indeed much faster then we should make sure to get it into 2.6.1. I could try to implement it myself if @Saizan confirms that these three places are the only ones that need to be updated.

**Comment by Saizan** [comment]
Just changing the computation of comp for ```Glue``` wouldn't really be a new feature. 

@mortberg Those are the three spots where we use forall. We should probably add some tests for Glue's transp when this change is made though, it's easy to get such things wrong.

Also, I am a bit unconvinced by ```ghcomp``` implementation in terms of ```hcomp```, as ```u0``` gets duplicated. Though maybe it's good to experiment with this simpler option first.

**Comment by mortberg** [comment]
As `ghcomp` will only be used in 3 places I don't think the duplication will be too bad, but I guess you are thinking about taking ghcomp as primitive and defining it by cases on `A`?

Btw, redtt has ghcom (but implemented in a much more complicated way) and we tried disabling it which led to much worse performance. It is of course hard to compare the two systems, but I'm optimistic that this change will improve performance in cubical agda as well.

**Comment by gallais** [comment]
Have we given up on the feature freeze? Because I have 4 PRs I wouldn't mind merging
so that I don't have to deal with merge conflicts anymore.

**Comment by Saizan** [comment]
@gallais oh, i forgot about that! This PR is a small tweak so maybe I would have merged anyway though.

I suppose we're still gearing up to release, but in that case shouldn't new features be merged into `future` so then it's up to who commits on `master` to merge?
