### ISSUE TITLE
Warnings are printed before errors

### ISSUE THREAD

**Issue by nad** [agda/agda#3416]
Consider the following code:
```agda
A : Set
A = A

B : Set
B = Set
```
When I load this code in Emacs the cursor jumps to the final occurrence of `Set`, and the following text is printed in the information buffer:
```
———— Warning(s) ————————————————————————————————————————————
[...]/Bug.agda:1,1-2,6
Termination checking failed for the following functions:
  A
Problematic calls:
  A (at [...]/Bug.agda:2,5-6)
———— Error —————————————————————————————————————————————————
[...]/Bug.agda:5,5-8
Set₁ != Set
when checking that the expression Set has type Set
```
Given that the cursor jumps to the problem associated with the error I really think that the error should precede the warnings in the information buffer. The current output can be rather confusing.

This is a regression, Agda 2.5.4.2 prints the error before the warnings.

**Comment by fredrikNordvallForsberg** [comment]
@gallais Sorry, I should have assigned myself! Currently running the test suite after a fix.

**Comment by gallais** [comment]
@fredrikNordvallForsberg No problem!

**Comment by fredrikNordvallForsberg** [comment]
I'm not sure if "not-in-changelog" is needed in conjunction with "regression", but just in case.

**Comment by fredrikNordvallForsberg** [comment]
Also note that I didn't change the order of the warnings and the error for the command-line output; there, I think it makes sense to look to the last output to see what made us crash out with an error.

**Comment by jespercockx** [comment]
> I'm not sure if "not-in-changelog" is needed in conjunction with "regression", but just in case.

I think we *do* need it because if we actually released a version of Agda with the regression, it *should* be mentioned in the changelog that it is now fixed.
