### ISSUE TITLE
Inductive definitions live in a larger set --without-K

### ISSUE THREAD

**Issue by gallais** [agda/agda#3420]
Cf. [this example](https://github.com/agda/agda-stdlib/commit/2811a9b5989c5f06abfa86adba9696880d943583#r31456760)

If this is not necessary then we should make sure we can lower the definitions again,
otherwise we should document this in [the doc for `--without-K`](https://agda.readthedocs.io/en/v2.5.4.2/language/without-k.html)

**Comment by guillaumebrunerie** [comment]
I think this is the expected behaviour. One of the motivations for having `--without-K` is that it should be compatible with univalence, and from the point of view of HoTT if a type `A` lives in a universe `U`, then the identity type of `A` should live in the same universe, not in a lower one.

**Comment by nad** [comment]
Yes, this is intended. [Coq also does something like this](https://coq.inria.fr/refman/credits.html) (see the discussion of the `-indices-matter` flag).

I think the rule is that all index types must fit in the target universe. Does anyone know where in the Agda code base this is implemented?

**Comment by gallais** [comment]
Interesting. So `All` and `all` are not equivalent in HoTT?

```agda
{-# OPTIONS --without-K #-}

open import Level
open import Data.List.Base using (List; []; _∷_)
open import Data.Product
open import Data.Unit

module _ {a p} {A : Set a} (P : A → Set p) where

  data All : List A → Set (a ⊔ p) where
    []  : All []
    _∷_ : ∀ {x xs} → P x → All xs → All (x ∷ xs)

  all : List A → Set p
  all []       = Lift p ⊤
  all (x ∷ xs) = P x × all xs
```

**Comment by nad** [comment]
I have not checked the details, but I guess that you can prove that `All` is equal to `all` in HoTT with univalence and cumulativity.

**Comment by jespercockx** [comment]
> I think the rule is that all index types must fit in the target universe. Does anyone know where in the Agda > code base this is implemented?

The rule is that the types of the *constructor arguments* must all fit in the sort of the datatype. Usually forced arguments are excluded from this check, but if `--without-K` is enabled they are also included. It's implemented at https://github.com/agda/agda/blob/d57465aaa9b97dd9f3e1003f90ebf68fc31a4ee3/src/full/Agda/TypeChecking/Rules/Data.hs#L1160-L1164

**Comment by nad** [comment]
Isn't this too liberal? The following code is accepted:
```agda
{-# OPTIONS --without-K #-}

data _≡_ {a} {A : Set a} (x : A) : A → Set where
  refl : x ≡ x
```

**Comment by jespercockx** [comment]
Yeah, that should *probably* not be allowed.

**Comment by jespercockx** [comment]
I implemented the more restrictive check and added it to the documentation & CHANGELOG.

**Comment by jespercockx** [comment]
I had to disable some code in the documentation for `--cubical` since the equality type for interval elements is no longer legal Agda. Maybe @Saizan wants to take a look to see how to fix it more properly.

**Comment by nad** [comment]
> I implemented the more restrictive check

Thanks.
