### ISSUE TITLE
extended visualization of dependency graph

### ISSUE THREAD

**Issue by ivoysey** [agda/agda#3421]
Current versions of Agda  can produce a DOT file showing the module dependency graph. This feature could be extended to provide information that's more useful in the process of developing a collection of modules, rather than just the high level structure of a possibly complete development. Specifically, 

- if modules that use postulates, they are colored red,
- those that have unsolved metas are colored yellow
- some kind of "taint analysis", to show subgraphs of the dependency graph might seem to be complete but actually rely on unsolved metas or postulates

A more general approach might be to take the path to a binary conforming to a simple API on the command line, and then run that on each node in a DFS of the finished graph in a visitor pattern style.

**Comment by nad** [comment]
> A more general approach might be to take the path to a binary conforming to a simple API on the command line, and then run that on each node in a DFS of the finished graph in a visitor pattern style.

Perhaps this kind of thing could be developed as a separate application, or separate backend, rather than being part of Agda.

**Comment by ivoysey** [comment]
Yeah, that's certainly a fine approach too. A lot of the machinery to traverse the parse tree must already exist in Agda in order to produce the DOT output that it already can, though. It would be a shame to duplicate that work, especially as the syntax of the language changes and creates a chance for version skew. I was more trying to think of ways that would be a small extension to the existing code but allow more interaction with the result of static analysis.

**Comment by jespercockx** [comment]
It's possible for another application to use Agda as an API, so ideally it wouldn't be necessary to implement a new parser from scratch.
