### ISSUE TITLE
Implicit arguments with custom macro for resolution

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#3423]
It would be nice if we could annotate implicit arguments with a custom macro that is run when the implicit argument is inserted. We could make use of the new attribute syntax:
```agda
macro tac = ...

foo : {A : Set} {@(auto tac) x : A} -> A
foo {x} = x

bar : Nat
bar = foo    -- runs `tac` on goal `_x : Nat`
```
One obstacle to adding this feature is that it requires the `QName` of the macro to be part of the `ArgInfo`, but the `ArgInfo` is constructed before scope checking.

**Comment by jespercockx** [comment]
@UlfNorell what's the status of this feature? I remember you working on it but I cannot find it in the user manual yet :)

**Comment by nad** [comment]
https://github.com/agda/agda/blob/856415f51b60171f9799912cfc89622913783f88/CHANGELOG.md#L188-L203

**Comment by jespercockx** [comment]
Thanks, I was looking in the user manual. @UlfNorell could you please add something there as well?
