### ISSUE TITLE
Highlighting does not work for pattern synonyms in import lists

### ISSUE THREAD

**Issue by nad** [agda/agda#3432]
Highlighting does not work for pattern synonyms in import lists. Example:
```agda
module _ where

module M where

  data D : Set where
    c : D

  pattern c′ x = c x

open M using (c; c′)
```
In the `using` list `c` is highlighted, but not `c′`. (Tested using both non-interactive and interactive highlighting.)

**Comment by andreasabel** [comment]
Related: #1714.

**Comment by andreasabel** [comment]
I fixed this by also considering `stPatternSyns` when creating the `nameKinds` lookup function in Highlighting.Generate.  The underlying issue is that pattern synonyms are not stored in the signature but in their own little pet map.
