### ISSUE TITLE
Prop-valued equality not accepted anymore with --without-K

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3433]
The following code isn’t accepted anymore

```agda
{-# OPTIONS --prop --without-K #-}

data _≡_ {A : Set} (x : A) : A → Prop where
  refl : x ≡ x
```
```
Set is not less or equal than Prop when checking the definition of _≡_
```

I guess that this is due to 3316e456ca160fd6e5b465c3eef1b2f48a80e4f6, but is it intended? Is there another way to define the `Prop`-valued identity type?

**Comment by jespercockx** [comment]
This was not intended, no. Datatypes in `Prop` are interpreted as the squash of their equivalent definition in `Set`, so the equality type should also be definable in `Prop` (even if you currently cannot eliminate it).

**Comment by nad** [comment]
The following code is accepted:
```agda
{-# OPTIONS --without-K --prop #-}

open import Agda.Builtin.Equality

data [_] (A : Set) : Prop where
  ∣_∣ : A → [ A ]

_[≡]_ : {A : Set} → A → A → Prop
x [≡] y = [ x ≡ y ]
```
