### ISSUE TITLE
generalised variable in (data/record type) declaration not supported without accompanying definition

### ISSUE THREAD

**Issue by m0davis** [agda/agda#3436]
Generalised data parameters are now supported, but in version 424cf62360c26e133922abd1b50b06b84f50c263, the following code is not accepted:
```agda
postulate
  A : Set
  B : A → Set

variable
  a : A

data D : B a → Set
```
The error message is
```
Generalizable variable a is not supported here
when scope checking a
```
Adding a definition for `D` avoids the error.

**Comment by nad** [comment]
This and many other fixed issues related to generalisation should have the "not-in-changelog" label, right?

**Comment by nad** [comment]
I added this label to some of the issues.

**Comment by UlfNorell** [comment]
Tbh I'm not sure which issues rate a mention in the changelog and which don't. I'm sure @asr knows.

**Comment by asr** [comment]
> This and many other fixed issues related to generalisation should have the "not-in-changelog" label, right?

Right. Closed issues on non-released features should have the `not-in-changelog` label.
