### ISSUE TITLE
Add Propω

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3437]
As there is `Setω`, should there be a `Propω` as well?

**Comment by jespercockx** [comment]
The reason why we have `Setω` is to give a type to expressions like `∀ ℓ → Set ℓ`. Since `∀ ℓ → Prop ℓ` also lives in `Setω`, I don't see a real use-case for having `Propω`.

**Comment by zraffer** [comment]
The reason why we have `Setω` is to give a type to expressions like `∀ ℓ → S ℓ` where `S ℓ : Set ℓ`. Also, the reason to have `Propω` is to type expressions like `∀ ℓ → P ℓ` where `P ℓ : Prop ℓ`; e.g. the irrelevant type `∀ ℓ → True ℓ` which itself is inhabited by the unique member `λ ℓ → tt {ℓ}`. The distinctive property of `Propω` should garantee the irrelevance of such level-polymorphic `tt`.

**Comment by amp12** [comment]
I second the request to have Propωi -- if one makes developments using --prop (as I do), the moment one needs to use Setω, then the need for Propω usually arises as well.

**Comment by andreasabel** [comment]
@amp12 : Could you provide an example?
As @jespercockx said, `Prop i` lives in `Set (i+1)`, so `(i : Level) -> Prop i` lives in `Set\omega`.

**Comment by amp12** [comment]
Here is an example:

```agda
-- lists of elements of types at any finite level
data BigList : Setω where
  [] : BigList
  _::_ : ∀{l}{A : Set l}
    → -------------------
    A → BigList → BigList

--  some property of elements of types at any finite level
postulate
  Foo : ∀{l}{A : Set l} → A → Prop l

-- lift Foo to BigList
data BigListhasFoo : BigList → Setω where
  [] : BigListhasFoo []
  :: : ∀{l}{A : Set l}{x : A}{XS : BigList}
    → ------------------------------------------------
    Foo x → BigListhasFoo XS → BigListhasFoo (x :: XS)
```

At the moment `BigListhasFoo` has to have type `BigList → Setω`, but since it is giving a property of biglists, I would prefer it to have type `BigList → Propω` were that possible.

**Comment by andreasabel** [comment]
@amp12 Andrew, I am currently implementing this.

The example is a bit silly though, as `Foo` is necessarily a constant proposition (due to parametricity).

**Comment by amp12** [comment]
@andreasabel Great! (I am sure there are use examples that are non-trivial.)
