### ISSUE TITLE
Squashing of types in Setω

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3438]
I can’t find a way to define the squashing of a type in `Setω` (possibly with the `--omega-in-omega` option). I tried the following but it gives an error message that I don’t understand:
```agda
data Squash (A : Setω) : Prop where
  squash : A → Squash A
```
```
Setω != Set
when checking the constructor squash in the declaration of Squash
```
Then I tried with `Propω` but there is no `Propω` (#3437)

**Comment by jespercockx** [comment]
This works:
```agda
{-# OPTIONS --omega-in-omega --prop #-}

open import Agda.Primitive

{-# NO_UNIVERSE_CHECK #-}
data Squash (A : Setω) : Prop where
  squash : A → Squash A
```
I'm not sure why you get the error `Setω != Set` when you remove the `{-# NO_UNIVERSE_CHECK #-}`, though.

**Comment by jespercockx** [comment]
I think the current behaviour here is as expected. To squash `Setω` without `--type-in-type` or `{-# NO_UNIVERSE_CHECK #-}`, we would need to support `Propω` (#3437).
