### ISSUE TITLE
Setω doesn’t respect --type-in-type

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3439]
The following gives unsolved constraints, but I think it should just work.
```agda
{-# OPTIONS --type-in-type #-}

open import Agda.Primitive

test : Set
test = Setω
```
```
Failed to solve the following constraints:
  univSort Setω = Set
  univSort (univSort Setω) = Set₁
```
If we additionally add the `--omega-in-omega` options (which should presumably do nothing more in the presence of `--type-in-type`) then it fails:
```
Setω != Set
when checking that the expression Setω has type Set
```

**Comment by nad** [comment]
This is related to https://github.com/agda/agda/issues/2487#issuecomment-444498567: Is `--type-in-type` compatible with `--omega-in-omega`?

**Comment by guillaumebrunerie** [comment]
Two related questions are
- What is the semantics of `--type-in-type` with respect to sorts outside the `Set i` hierarchy? Should this flag disable sort checking altogether or just universe level checking? For instance I guess that `Set : Prop` should still be forbidden with `--type-in-type`.
- Should `Setω` be instead `Set ω` for `ω : Level`? In that way, the problem in the OP would go away even if `--type-in-type` only gets rid of checking equalities between universe levels, but maybe it brings other problems.

**Comment by jespercockx** [comment]
>     What is the semantics of --type-in-type with respect to sorts outside the Set i hierarchy? Should this flag disable sort checking altogether or just universe level checking? For instance I guess that Set : Prop should still be forbidden with --type-in-type.

Currently it only disables checking of constraints on universe levels but not on sorts in general, which is presumably what's causing the issue here.

>     Should Setω be instead Set ω for ω : Level? In that way, the problem in the OP would go away even if --type-in-type only gets rid of checking equalities between universe levels, but maybe it brings other problems.

No, having `ω : Level` would defeat the whole purpose of having `Setω`, which is giving a type to `∀ ℓ → Set ℓ` that is itself **not** a part of the `Set ℓ` hierarchy.

However, we could consider `Setω` to be equal to any `Set ℓ` when `--type-in-type` is enabled.

**Comment by guillaumebrunerie** [comment]
> No, having `ω : Level` would defeat the whole purpose of having `Setω`, which is giving a type to `∀ ℓ → Set ℓ` that is itself **not** a part of the `Set ℓ` hierarchy.

Ah yes, of course.

> However, we could consider Setω to be equal to any Set ℓ when --type-in-type is enabled.

I think that would make sense.
