### ISSUE TITLE
Generate Level expressions with fewer parentheses

### ISSUE THREAD

**Issue by gallais** [agda/agda#3441]
We have `infixl 6 _⊔_` in `Agda.Primitive` but we generate right-nested expressions
when solving metavariables. When they get printed we get a lot of useless parentheses.

```agda
open import Agda.Primitive

f : ∀ {a b c} → Set a → Set b → Set c → Set {!!} -- solution: (a ⊔ (b ⊔ c))
f A B C = A → B → C
```

We can either change `Agda.Primitive` to use `infixr` or change the way we generate
these expressions. Thoughts?

**Comment by JacquesCarette** [comment]
Yes please! I don't have a strong opinion on which change to make.

**Comment by nad** [comment]
Related: #2765.
