### ISSUE TITLE
"internal error" in Agda of December 7, 2018

### ISSUE THREAD

**Issue by mechvel** [agda/agda#3443]
This is on  Development Agda of December 7, 2018,
            ghc-7.10.2, Standard library of December 7, 2018.

Download 
                http://www.botik.ru/pub/local/Mechveliani/agdaNotes/bug-dec7-2018.zip

and unzip it. Then
```     
       > agda  -i $standardLibrary  Pol.agda
```
reports
```
Checking Pol (/home/mechvel/agda/tosave/bugs/dec7-2018/Pol.agda).
 Checking PPrelude (/home/mechvel/agda/tosave/bugs/dec7-2018/PPrelude.agda).
 Checking Nat0 (/home/mechvel/agda/tosave/bugs/dec7-2018/Nat0.agda).
  Checking Structures0  (... Structures0.agda).
An internal error has occurred. Please report this as a bug.
Location of the error:
                src/full/Agda/TypeChecking/CompiledClause/Compile.hs:126
```

It probably relates to the last two lines in Pol.agda :
```
  0-reducesNot :  {f g : Pol} →  IsZeroPol f →  ¬ PolReducesPol f g
  0-reducesNot {pol′ [] _ _} {_} _ (reduces _ _ ¬null[] _ _) =  ¬null[] isNull
```
If these two lines are commented out, then  Pol.agda  is type-checked.

**Comment by gallais** [comment]
I just hit the same one with a file that used to typecheck with a previous
version of 2.6.0 with support for `variable` (can't remember which commit).

I'm currently running 2.6.0-329b843

**Comment by gallais** [comment]
Shorter test case:

```agda
open import Agda.Builtin.List
open import Agda.Builtin.Equality

data Var {T : Set₂} (σ : T) : List T → Set₂ where
  z : ∀ {Γ} → Var σ (σ ∷ Γ)
  s : ∀ {τ Γ} → Var σ Γ → Var σ (τ ∷ Γ)

eq : ∀ {Γ} (b c : Var Set Γ) → b ≡ c → Set
eq z z _ = ?
eq (s m) (s n) _ = {!!}
```

If we spell out the following missing cases then the internal error goes away:

```agda
eq z (s n) ()
eq (s m) z ()
```

So it may be related to #3407

edit: reproduced after updating to 2.6.0 4c096a4
