### ISSUE TITLE
Strange error msg : src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs

### ISSUE THREAD

**Issue by xekoukou** [agda/agda#3448]
```: Irrefutable pattern failed for pattern GeneralizedVarsMetadata gvar```
Silly error that produces bizarre error msg.

```agda
 
module dd where

open import Data.Fin hiding (_+_ ; lift ; pred)


data LeaderMsg : Set where
  doCommit : LeaderMsg

lmsgToFin LeaderMsg : Fin ?
lmsgToFin x = ?

```

**Comment by jespercockx** [comment]
Minimal example:
```agda
data D : Set where
D : _
```

**Comment by jespercockx** [comment]
There is some `Inserted` name which does not have `GeneralizedVarsMetaData`, but the `bindGeneralizablesIfInserted` function expects it to have it. This check seems a bit too brittle to me, so I've just put in a `Map.empty` if there's no metadata attached.
