### ISSUE TITLE
Pattern matching on irrelevant arguments now disallowed even when only used in irrelevant contexts

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#3449]
```agda
open import Agda.Builtin.Nat renaming (Nat to ℕ)
open import Agda.Builtin.Equality renaming (_≡_ to _≡≡_)

record Σ (A : Set) (B : A → Set) : Set where
  constructor _,_
  field
    proj₁ : A
    proj₂ : B proj₁

open Σ public

∃ : ∀ {A : Set} → (A → Set) → Set
∃ = Σ _

record Fin (n : ℕ) : Set where
  constructor mkFin
  field
    m : ℕ
    .p : ∃ λ k → (ℕ.suc k Agda.Builtin.Nat.+ m) ≡≡ n

infixl 60 _+_
f : ∀ {m n} → Fin n → Fin n → Fin n
f {m} {n} record { m = a ; p = c₁ , p₁ } record { m = b ; p = c₂ , p₂ } = ?
```

I have a lot of code like this, and previously this was accepted, but now, Agda complains that I can't match on `p` because it's irrelevant, even though there's only one constructor and I'm not using the matched variables in any relevant contexts.

I tried rewriting a little of my code to match on the entire `p` and then use `proj₁` and `proj₂` instead, and this seemed to make the compiler happy, but it's going to take some effort for me to do this everywhere, and I want to make sure this is an intentional change before I do that.

**Comment by jespercockx** [comment]
This is a deliberate change, see https://github.com/agda/agda/issues/3056. The old situation did not make any sense since you could have (relevant) types depending on an irrelevant variable.

**Comment by jespercockx** [comment]
Now that #3452 is fixed, you can use copatterns and split on the irrelevant argument for constructing the second (irrelevant) projection of the result:
```agda
infixl 60 _+_
f : ∀ {m n} → Fin n → Fin n → Fin n
Fin.m (f (mkFin m p) (mkFin n q)) = {!!}
Fin.p (f (mkFin m (c₁ , p₁)) (mkFin n (c₂ , p₂))) = {!!}
```

**Comment by identicalsnowflake** [comment]
Hmm, ok I'll give that a shot!
