### ISSUE TITLE
The --no-sized-types option is broken

### ISSUE THREAD

**Issue by nad** [agda/agda#3451]
The following code is accepted:
```agda
{-# OPTIONS --no-sized-types #-}

{-# BUILTIN SIZE   Size   #-}
{-# BUILTIN SIZELT Size<_ #-}

record Stream (A : Set) (i : Size) : Set where
  coinductive
  field
    head : A
    tail : {j : Size< i} → Stream A j

open Stream

postulate
  destroy-guardedness : {A : Set} → A → A

repeat : ∀ {A i} → A → Stream A i
repeat x .head = x
repeat x .tail = destroy-guardedness (repeat x)
```
If the sizes are removed, then the code is rejected. Shouldn't `--no-sized-types` turn off sized types?

**Comment by nad** [comment]
A simple fix might be to disallow declaring the size builtins if `--sized-types` is not active, and to make `--sized-types` infective (see #2487).

**Comment by nad** [comment]
I'm not sure that the simple fix that I suggested is a good idea. I have a library that exports the size builtins from a "prelude" module that is marked as safe. If I'm not mistaken this module can no longer be used by safe code that uses constructor-based guarded corecursion.

Another way to fix this issue might be to disallow the use of sized types in the termination checker when `--no-sized-types` is active. I'm not sure how easy this is.

**Comment by nad** [comment]
The following comment should be addressed in some way:

https://github.com/agda/agda/blob/82a4fba610469583b2d830e5d07f1de19f48b886/test/Succeed/Issue1209-7.agda#L1-L3

**Comment by nad** [comment]
> Another way to fix this issue might be to disallow the use of sized types in the termination checker when `--no-sized-types` is active. I'm not sure how easy this is.

The current implementation might be less error prone, so perhaps we should stick with it.

**Comment by gallais** [comment]
I suggest we stick with the more conservative implementation at least for 2.6.0.

**Comment by nad** [comment]
> The following comment should be addressed in some way:

Done.
