### ISSUE TITLE
Highlighting for incomplete pattern matching should be above highliting for non-exact split

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3454]
In the code below, the two lines defining `and` are highlighted with two different colors. The first one is highlighted with the "incomplete pattern matching" color and the second one with the "non-exact split" color. I’d argue that "incomplete pattern matching" is much more important, so they should both be highlighted with that color.

```agda
data Bool : Set where
  true false : Bool


and : Bool → Bool → Bool
and x true = true
and true x = true
```

**Comment by andreasabel** [comment]
I suspect this fix broke the internal test suite.

```
      prop_monoid_Aspects from test/Internal/Interaction/Highlighting/Precise.hs:80:                                      FAIL (0.09s)
                                                                                                                          *** Failed! Falsifiable (after 7 tests and 12 shrinks):
        Aspects {aspect = Nothing, otherAspects = [UnsolvedConstraint,CatchallClause], note = Nothing, definitionSite = Nothing, tokenBased = NotOnlyTokenBased}
        Aspects {aspect = Nothing, otherAspects = [], note = Nothing, definitionSite = Nothing, tokenBased = NotOnlyTokenBased}
        Aspects {aspect = Nothing, otherAspects = [], note = Nothing, definitionSite = Nothing, tokenBased = NotOnlyTokenBased}
        Use --quickcheck-replay=341775 to reproduce.
```

**Comment by jespercockx** [comment]
Yeah, `Aspects` no longer forms a monoid because of my hack :( I don't know how to properly fix this issue: it feels like the catchall highlighting should be kept in the list of `OtherAspects` and dropped in a later phase, but I cannot find any 'later phase' except for the elisp code (which I am not going to touch). 

I will revert my patch to fix the build, could someone else who knows more about the highlighting and/or emacs mode please take a look at this?

**Comment by jespercockx** [comment]
Why does Github still not know how to deal with reverts containing [ fix #... ] in the message...

**Comment by gallais** [comment]
Given all the calls to `List.nub`, I'm trying to switch to `Set OtherAspect`.
Based on the `Ord` instance for `OtherAspect`, we ought to be able to get
`CatchallClause` first (or last, whichever works) meaning it'll hopefully get
overwritten by later aspects during rendering.

**Comment by asr** [comment]
@gallais, did you cancel the tests on Travis?

**Comment by gallais** [comment]
Yes I did because the run was successful in the PR (#3565). I don't know why travis
tries to re-run the builds after a (0-commit deep) rebase rather than merge.
