### ISSUE TITLE
Strange error messages related to "as"

### ISSUE THREAD

**Issue by nad** [agda/agda#3457]
The following code triggers a strange error message:
```agda
import Agda.Builtin.Nat as _
```
```
`as' must be followed by an unqualified name
when scope checking the declaration
  import Agda.Builtin.Nat as _
```
The following code also triggers a strange error message:
```agda
import Agda.Builtin.Nat Fresh-name as _
```
```
/tmp/Bug.agda:1,8-24
Duplicate definition of module
.#Agda.Builtin.Nat-12014055641079923239. Previous definition of
module .#Agda.Builtin.Nat-12014055641079923239 at
/tmp/Bug.agda:1,8-24
when scope checking the declaration
  module .#Agda.Builtin.Nat-12014055641079923239
    = .#Agda.Builtin.Nat-12014055641079923239 Fresh-name
```
Agda 2.5.4.2 responds with reasonable error messages for these pieces of code:
```
Not in scope:
  as at /tmp/Bug.agda:1,25-27
when scope checking as
```
```
Not in scope:
  Fresh-name at /tmp/Bug.agda:1,25-35
when scope checking Fresh-name
```

**Comment by andreasabel** [comment]
This is intended, see #3364.

Did you want to us an `as`-clause with `_` as module name here, or did you want `as` as a module parameter?

**Comment by nad** [comment]
I tried to use `_` as a module name, see #2579.

I guess the first error message makes sense, because `_` is not an unqualified name. However, I read the error message as "`as' must be followed by an unqualified name, and you gave a qualified name".

The second error message is terrible, though.

**Comment by andreasabel** [comment]
Fixed both problematic error messages.
1. Giving a more specific error in case you try to use `_` or a qualified name.
2. Not reusing the same hash-identifier in the parser makes this problem go away.
