### ISSUE TITLE
Unsolved metas when defining an element of a record

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3459]
Consider the code below which gives a lot of yellow currently.
I think it should be possible to solve the types of `a` and `b` (the two underscores) to `A` and `B a` respectively (I don’t see any other solution for those two metavariables).

For the type of `a`, the generated constraint is `_2 =< A : _1`, I’m not sure why this doesn’t solve `_2` to `A`.

For the type of `b` it’s a bit trickier, the constraint is `_5 =< B (fst u) : _4` but `u` is not in scope during the definition of `b`. Still, it should be possible to use the equality `fst u = a` to solve `_5` to `B a`.

This would be especially useful when constructing an element in a big record type and being able to give each field its own independent definition without having to write down all of their types again.

```agda
open import Agda.Builtin.Sigma

postulate
  A : Set
  B : A → Set

a : _
a = ?

b : _
b = ?

u : Σ A B
fst u = a
snd u = b
```

**Comment by nad** [comment]
Agda freezes meta-variables after mutual blocks.
