### ISSUE TITLE
Can't (interactively) bring some hidden variables into scope

### ISSUE THREAD

**Issue by m0davis** [agda/agda#3460]
Using the latest development version (b444550a0ea6976185fdd779ac61c25b5b996090), I can no longer bring some hidden variables into scope interactively (i.e. using `C-c C-c`). For example,
```agda
postulate A : Set
postulate B : A → Set
variable a : A

foo : B a → Set
foo x = {!a!} -- C-c C-c here reports "Not a variable: a"

{- C-c C-e reports
a : A  (not in scope)
x : B a
-}
```
It still works to bring the variable into scope manually. Viz:
```agda
foo {a} x = {!!} -- no error
```
I'm guessing this is related to https://github.com/agda/agda/pull/3446.

**Comment by guillaumebrunerie** [comment]
It works if you remove `variable a : A` and use `foo : {a : A} → B a → Set` instead, so this is an issue with generalization.
