### ISSUE TITLE
Regression, possibly related to instance resolution

### ISSUE THREAD

**Issue by nad** [agda/agda#3462]
I have some code that is accepted by Agda 2.5.4.2. Agda 2.6.0-fdb4315 rejects it with an error starting with `No instance of type Raw-monad _M_128 was found in scope`. If I replace parts of the code with holes, load the file, and then use "give" to fill the holes, then the code is accepted. Thus it seems to me as if something is broken.

Perhaps it is relevant that the code involves a macro.

I have not constructed a minimal test case. The following commands can be used to trigger the error message:
```
git clone http://www.cse.chalmers.se/~nad/repos/equality/
cd equality
git checkout c8b6831ab6a447780b21fc8c0e1fad7c181cbb98
cd src
cat > Bug.agda <<EOF
module _ where

open import Agda.Builtin.List

open import Equality.Propositional
open import Prelude using (Maybe; just)
open import Tactic.By

open import Maybe equality-with-J
open import Monad equality-with-J

postulate
  C : Set

data D : Set where
  c : C → List D → D

mutual

  f : D → D
  f (c x xs) = c x (f⋆ xs)

  f⋆ : List D → List D
  f⋆ []       = []
  f⋆ (x ∷ xs) = f x ∷ f⋆ xs

mutual

  g : D → Maybe D
  g (c x xs) = c x ⟨$⟩ g⋆ xs

  g⋆ : List D → Maybe (List D)
  g⋆ []       = return []
  g⋆ (x ∷ xs) = _∷_ ⟨$⟩ g x ⊛ g⋆ xs

postulate
  g∘f⋆ : (xs : List D) → g⋆ (f⋆ xs) ≡ just xs
  x    : D
  xs   : List D

foo =
  _∷_ ⟨$⟩ return x ⊛ g⋆ (f⋆ xs)  ≡⟨ by (g∘f⋆ xs) ⟩
  _∷_ ⟨$⟩ return x ⊛ return xs   ∎
EOF
agda --no-libraries -i. Bug.agda
```
If `_∷_ ⟨$⟩ return x ⊛ g⋆ (f⋆ xs)` and `_∷_ ⟨$⟩ return x ⊛ return xs` are replaced by holes and "given" after the file has been loaded, then the code is accepted.

**Comment by UlfNorell** [comment]
The problem is that your tactic is too eager to declare success. When you make the rhs a hole the tactic blocks and gets run after the give and the instance resolution. In the problematic case the tactic is run before instance resolution and solves the goal with `refl`, leaving some constraints.

If you add a check in `try-refl` that the goal was actually solved the problem goes away:
```agda
      try-refl (def (quote _≡_) (a ∷ A ∷ arg _ lhs ∷ _)) =
        unify t′ goal >>= λ _ → do
        con (quote refl) _ ← reduce goal where _ → ill-formed
        return t′
```

**Comment by nad** [comment]
Thanks!

Perhaps the ideal thing to do would be to block until one can figure out whether the unification succeeds completely or not. However, I am only aware of one way to block, and that is to use `blockOnMeta`. Could `blockOnMeta` be used here? Alternatively, could there be a builtin like, say, `unifyStrictly`, with the following specification:

* It succeeds if unification is successful and does not give rise to any new, unsolved constraints.
* It blocks if unification is successful but there are new, unsolved constraints, and there is at least one meta-variable to block on. I suppose that this meta-variable should have been introduced "early enough".
* Otherwise it fails.

Or can this kind of thing already be implemented using the current reflection API?

**Comment by UlfNorell** [comment]
Not at the moment, but see #2351.

**Comment by nad** [comment]
The `noConstraints` primitive raises a type error, it does not block. Is it possible to find a meta-variable to block on?

Perhaps it would be useful to have something like the `retry` primitive of GHC's STM monad. I think the STM implementation uses some heuristic to delay the new attempt (maybe something like "wait until at least one of certain variables have been modified").

**Comment by UlfNorell** [comment]
`blockOnMeta` is the "something like the `retry` primitive".

If `noConstraints` fails there should be a meta somewhere in the terms you're working with that you could block on.

**Comment by nad** [comment]
> `blockOnMeta` is the "something like the `retry` primitive".

Well, the point was that Agda might be able to figure out what to block on automatically, in order to make it easier to write tactics.

> If `noConstraints` fails there should be a meta somewhere in the terms you're working with that you could block on.

Doesn't figuring out which meta-variable to block on basically amount to replicating the (Haskell) implementation of parts of the computation that `noConstraints` is wrapped around?

**Comment by UlfNorell** [comment]
Right. We might consider adding a `blockIfConstraints` that wakes up if any of the metas in the offending constraints get solved.

**Comment by nad** [comment]
I've opened a new issue for `blockIfConstraints` (#3496).
