### ISSUE TITLE
Impossible to give certain instance arguments by name?

### ISSUE THREAD

**Issue by nad** [agda/agda#3463]
Consider the following code:
```agda
record R : Set₁ where
  field
    A : Set

open R ⦃ … ⦄
```
The inferred type of `A` is `⦃ r : R ⦄ → Set`. However, the following code is rejected:
```agda
X : R → Set
X r = A ⦃ r = r ⦄
```
Error message:
```
Function does not accept argument ⦃ r = r ⦄
when checking that ⦃ r = r ⦄ is a valid argument to a function of
type ⦃ r = r₁ : R ⦄ → Set
```
This is a regression. For some reason the following code is still accepted:
```agda
X : R → Set
X r = A ⦃ r ⦄
```

**Comment by nad** [comment]
The following code is accepted, so the problem might have something to do with `open R ⦃ … ⦄`:
```agda
postulate
  R : Set₁
  A : ⦃ r : R ⦄ → Set

X : R → Set
X r = A ⦃ r = r ⦄
```

**Comment by jespercockx** [comment]
I'm fixing this by setting the name of the final parameter of the record module to "r" when we instance-open it. However, we could consider to allow the user to choose their own name for the argument, for example like this:
```agda
open R ⦃ nameForTheArgument = … ⦄
```
That way we wouldn't have to rely on "magically" generated names like "r".

**Comment by nad** [comment]
I'm not a fan of the hard-wired name `r`, but in this case I don't think we should break existing code. Making it possible to optionally choose a name makes sense to me.
