### ISSUE TITLE
unquoteDef/unquoteDecl does not accept where-blocks

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3467]
Is there a reason why one cannot add where-blocks to `unquoteDef`/`unquoteDecl`?

```agda
unquoteDecl a = ? where
  b = ?
```
gives a parse error at the `where`.

**Comment by UlfNorell** [comment]
Currently only function clauses have where blocks and it doesn't seem worth it to add them also to `unquoteDecl`. Where blocks only really make sense if you have some kind of left-hand side binding things that would be in scope in the where (which `unquoteDecl` does, but `unquoteDef` doesn't).
