### ISSUE TITLE
Can't install via cabal-install on current Haskell Platform

### ISSUE THREAD

**Issue by peterb12** [agda/agda#3471]
STEPS:

(1) On a Mac running Mojave, install Haskell Platform from `https://www.haskell.org/platform/`.
(2) Per the instructions on the Agda wiki, do `cabal update` followed by `cabal install Agda`

Results:
```Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: Agda-2.5.4.2 (user goal)
[__1] next goal: base (dependency of Agda)
[__1] rejecting: base-4.12.0.0/installed-4.1... (conflict: Agda =>
base>=4.8.0.0 && <4.12)
[__1] rejecting: base-4.12.0.0, base-4.11.1.0, base-4.11.0.0, base-4.10.1.0,
base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0, base-4.8.1.0,
base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1,
base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0,
base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0,
base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from
non-upgradeable package requires installed instance)
[__1] fail (backjumping, conflict set: Agda, base)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, Agda
```

This is a pretty bad user experience.  Suggestion for a fix that doesn't require a code change: if there's a _specific version_ of either the haskell platform, GHC, or Cabal required, list those (right now it just says "GHC" and "Cabal" on the prerequisites page, which a reasonable reader would infer to be "grab the latest.")

**Comment by gallais** [comment]
Hi @peterb12, have you tried passing `cabal` the option `--allow-newer`?
This seems to be a problem of bleeding edge GHC vs. released Agda.

Edit: related #3369 #3442

**Comment by peterb12** [comment]
--allow-newer seems to work (but, this workaround is not documented on the wiki / install instructions page, so someone new to the language - who is the most likely to be using it) is going to be stuck.

**Comment by peterb12** [comment]
Oops, didn't mean to close.  Sorry.

**Comment by peterb12** [comment]
Also, whoops, I lied, --allow-newer doesn't actually work.

```cabal: Error: some packages failed to install:
Agda-2.5.4.2-9BhwKRqvgS4DEPWVey00og failed during the configure step. The
exception was:
dieVerbatim: user error (cabal: '/usr/local/bin/ghc' exited with an error:

/var/folders/rv/34syb8ts2bnc5rcjm4hnjvf00000gn/T/cabal-tmp-28425/Agda-2.5.4.2/dist/setup/setup.hs:23:56:
error:
• Couldn't match type ‘Distribution.System.Platform -> String’
with ‘[Char]’
Expected type: String
Actual type: Distribution.System.Platform -> String
• Probable cause: ‘exeExtension’ is applied to too few arguments
In the second argument of ‘(<.>)’, namely ‘exeExtension’
In the second argument of ‘(</>)’, namely ‘"agda" <.> exeExtension’
In the second argument of ‘(</>)’, namely
‘"agda" </> "agda" <.> exeExtension’
|
23 | agda = buildDir info </> "agda" </> "agda" <.> exeExtension
| ^^^^^^^^^^^^
)
```

**Comment by asr** [comment]
Agda 2.5.4.2 supports GHC 7.10.3, 8.0.2, 8.2.2 and 8.4.4. Agda 2.5.4.2 doesn't support GHC 8.6.*.

**Comment by nad** [comment]
@asr, perhaps this information is not sufficiently well documented. I don't think we should expect that people who want to try out Agda will read the Cabal file before choosing which version of the Haskell Platform to use.

**Comment by asr** [comment]
I added the GHC supported versions to the [user manual](https://agda.readthedocs.io/en/latest/getting-started/prerequisites.html?).

**Comment by banacorn** [comment]
I got the same error as @peterb12 did, with GHC 8.6.3. 

I noticed that 8.6.3 was later added to the list of tested versions in https://github.com/agda/agda/commit/bc6d4b6c2c8f3e9583f7ac24fd6d19c513c06bd6, is this correct?

**Comment by asr** [comment]
> I noticed that 8.6.3 was later added to the list of tested versions in https://github.com/agda/agda/commit/bc6d4b6c2c8f3e9583f7ac24fd6d19c513c06bd6, is this correct?

This commit was for the user manual of the upstream version (which supports GHC 8.6.3).

**Comment by asr** [comment]
Back-ported into 2.5.4.3.
