### ISSUE TITLE
Rewriting is applied to a different relation

### ISSUE THREAD

**Issue by mwageringel** [agda/agda#3473]
In the following example, rewriting is enabled for the relation `_∼₁_`, yet Agda seems to get confused with the relation `_∼₂_`. This allows to produce incorrect proofs about `_∼₂_` which, to my understanding, should only work for `_∼₁_`.

```agda
{-# OPTIONS --rewriting #-}

postulate
  A : Set

Rel = A -> A → Set

Reflexive : Rel → Set _
Reflexive _∼_ = ∀ {x} → x ∼ x

Associative : Rel → (A → A → A) → Set _
Associative _≈_ _∙_ = ∀ x y z → ((x ∙ y) ∙ z) ≈ (x ∙ (y ∙ z))

postulate
  _+_ : A → A → A
  _∼₁_ _∼₂_ : Rel
  refl₂ : Reflexive _∼₂_
  assoc₁ : Associative _∼₁_ _+_

{-# BUILTIN REWRITE _∼₁_ #-}
{-# REWRITE assoc₁ #-}

-- The following compiles even though it probably should not, as only assoc₁
-- with _∼₁_ should be rewritten.

assoc₂ : Associative _∼₂_ _+_
assoc₂ _ _ _ = refl₂
```

Tested with Agda 2.5.4.1 and 2.5.4.2.

**Comment by UlfNorell** [comment]
Rewriting introduces new *definitional* equalities, which relation you use doesn't really matter. In this case you introduced the rule `(x + y) + z --> x + (y + z)`, so the left-hand side in the `assoc₂` goal rewrites to the right-hand side. The `_~₂_` relation isn't involved at all.

**Comment by mwageringel** [comment]
Oh, I see, so my understanding of how rewriting works was wrong. Thanks for the quick response!
