### ISSUE TITLE
Undocumented behaviour of Unit in implicit arguments?

### ISSUE THREAD

**Issue by WorldSEnder** [agda/agda#3474]
This is mostly seaking clarification. I'm relatively new to the language so I was surprised this worked out of the box:

    ⊤-test : {some : ⊤} → ℕ
    ⊤-test = 42
    test : ℕ
    test = ⊤-test

If we try the same with a custom unit datatype:

```
data OwnTT : Set where instance tt : OwnTT
own-test : {some : OwnTT} → ℕ
own-test = 4
test : ℕ
test = own-test
```
this reports an unsolved implicit argument in test. Confusion arises, as it is unclear how the compiler solved the implicit argument in the former example in the first place. Is this just a special case from a previous version of the language that has not been removed?

**Comment by gallais** [comment]
This is a consequence of eta-equality for records (which is how unit is defined
rather than as an inductive type). [Cf. the manual](https://agda.readthedocs.io/en/v2.5.4.2/language/record-types.html#eta-expansion).

**Comment by WorldSEnder** [comment]
Indeed declaring
```
record OwnTT : Set where constructor tt
```
enables automatic insertion of the implicit argument
