### ISSUE TITLE
Instance field of opened record does not count as instance if it refers to a private value

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#3479]
In the example below, I would expect instance search to succeed with solution `theX` (which is in scope and can be given manually). Instead, I get an error `No instance of type Test.D was found in scope`.
```agda
it : ∀ {ℓ} {X : Set ℓ} {{_ : X}} → X
it {{x}} = x

record R : Set₁ where
  field
    X : Set
    {{theX}} : X

module _ where
  private
    data D : Set where
      instance c : D

  r : R
  r = λ where
    .R.X    → D
    .R.theX → c

open R r public

test : X
test = it
```

**Comment by nad** [comment]
This code is accepted by Agda 2.5.4.2.

**Comment by identicalsnowflake** [comment]
Can confirm - I'm hitting this too when trying to compile an old module.

**Comment by UlfNorell** [comment]
I believe this is working as intended. Note that marking `theX` field `{{ }}` doesn't make it available for instance search after `open R r`, which is why you need the `instance` on `c` to make it work when `D` is not private. For instance, this fails also on 2.5.4.2:

```agda
t : ∀ {ℓ} {X : Set ℓ} {{_ : X}} → X
it {{x}} = x

record R : Set₁ where
  field
    X : Set
    {{theX}} : X

postulate r : R

open R r public

test : X
test = it
```
The scope requirement on instances (see #2489 and #1913) requires the symbol that is declared `instance` to be in scope; it's not enough to have an alias of the symbol be in scope:
```agda
postulate X : Set
module _ where
  private postulate instance x : X
  y = x

fails : X
fails = it
```

**Comment by jespercockx** [comment]
Ok, I guess this is a situation where one should mark the field as `instance` rather than use `{{ }}`. This works and is very close to my use case:
```agda
it : ∀ {ℓ} {X : Set ℓ} {{_ : X}} → X
it {{x}} = x

data D (A : Set) : Set where
  c : D A

record R : Set₁ where
  field
    X : Set
    instance
      DX : D X

postulate A : Set

module _ where

  private
    x : D A
    x = c

  r : R
  r = λ where
    .R.X  → A
    .R.DX → x

open R r public

test : D X
test = it
```

**Comment by nad** [comment]
I think it would be a good idea to explain the difference between fields marked with the `instance` keyword and fields marked with `⦃`…`⦄` (confusingly called "instance fields") in the reference manual.

**Comment by jespercockx** [comment]
I'm not very sure myself, but I think it's like this:

- marking a field using `{{ }}` turns it into an instance argument of the *record constructor*. This also has some consequences, e.g. we can leave it out of a copattern split.
- marking a field as an `instance` turns the *projection* into an instance. This only makes sense if you either instance-open the record or open the record applied to a specific value.

I'm not sure whether this explanation is clear enough for the user manual though, the difference confuses me too sometimes.
