### ISSUE TITLE
Parse error at EOF should be reported before EOF (especially if there is a long comment before EOF)

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3480]
I often have this problem:  I comment out the rest of the file, get a parse error, which is reported at the EOF which is miles away from my working zone (because of the kilometers of commented-out code).

I am preparing a fix to report the error at the last token before the EOF.

**Comment by andreasabel** [comment]
Commit 46a2ac4 could be cherry-picked for the 2.4.5.3 release.

**Comment by jespercockx** [comment]
Why is this fix in particular more important/critical than any of the other pending changes for 2.6.0?

**Comment by andreasabel** [comment]
It isn't, but it is ready to be released, and simple to pick, thus, I gave the instruction how to.

**Comment by nad** [comment]
> It isn't, but it is ready to be released, and simple to pick, thus, I gave the instruction how to.

It seems to have broken the test suite.

**Comment by asr** [comment]
The fix hasn't been back-ported to 2.5.4.3.

**Comment by asr** [comment]
> Commit 46a2ac4 could be cherry-picked for the 2.4.5.3 release.

Done.
