### ISSUE TITLE
Absurd Pattern on Implicit Type Validation

### ISSUE THREAD

**Issue by fabianhjr** [agda/agda#3482]
While trying out Agda for type-level validations I stumbled upon an error I don't understand:

Minimum example

```agda
module test where

infixr 5 _∷_

data 𝕃 {n} (A : Set n) : Set n where
  []  : 𝕃 A
  _∷_ : A → 𝕃 A → 𝕃 A

data NonEmpty {n} {A : Set n} : 𝕃 A → Set n where
  IsNonEmpty : {x : A} {xs : 𝕃 A} → NonEmpty (x ∷ xs)

head : ∀ {n} {A : Set n} → (ℓ : 𝕃 A) → {ok : NonEmpty ℓ} → A
head (x ∷ _) {IsNonEmpty} = x
head [] {IsNonEmpty} ()
```

The error:

    test.agda:14,10-20
    The case for the constructor IsNonEmpty is impossible because unification ended with a conflicting equation
      x ∷ xs ≟ []
    Possible solution: remove the clause, or use an absurd pattern ().
    when checking that the pattern IsNonEmpty has type NonEmpty []

or if I change the implicit to bound the variable directly in the last line (`{ok=IsNonEmpty}`)I get:

    Cannot eliminate type A with absurd pattern () (did you supply too many arguments?)
    when checking that the clause head [] {ok=IsNonEmpty} () has type
    {n : ;Agda.Primitive.Level} {A : Set n} (ℓ : 𝕃 A) {ok : NonEmpty ℓ} → A

The first error is odd since the absurd pattern _is_ used afterwards, the second one I don't really understand.

Agda version: 2.6.0 (`agda --version`) from the Arch `agda 2.5.99.20181017-9` package. ( https://www.archlinux.org/packages/community/x86_64/agda/ )

**Comment by gallais** [comment]
The absurd pattern should mark the argument which can't possibly exist, not just any
part of the LHS.

Here with `head [] {IsNonEmpty} ()` you are telling Agda that there is a case with the
empty list `[]` and the `IsNonEmpty` constructor and then an argument which can't
possibly have a value. But `IsNonEmpty` demands that the list has shape `x ∷ xs` and
we independently constraint it to be `[]`. This leads to a unification error: as the error
message explains, there is no way to solve `x ∷ xs ≟ []`.

When you remove `{IsNonEmpty}`, you have `head [] ()` which tells Agda that there
is a case where the first argument is the empty list and the second (explicit) is impossible.
But the type tells you there is no explicit second argument to talk about!

The solution is quite close: you want to use an absurd pattern for the *implicit*
argument. This can be done by using either `{}` or `{()}`. And it does typecheck
when written this way:

```agda
head : ∀ {n} {A : Set n} → (ℓ : 𝕃 A) → {ok : NonEmpty ℓ} → A
head (x ∷ _) {IsNonEmpty} = x
head [] {}
```

**Comment by fabianhjr** [comment]
Thanks a lot for the help @gallais <3
