### ISSUE TITLE
Standard library - Colist doesn't type check

### ISSUE THREAD

**Issue by csetzer** [agda/agda#3489]
After installing the current version of Agda on github (#3372 from 8 Jan 2019)
the file
/usr/share/agda-stdlib/Data/Colist.agda
from the standard library doesn't type check, raises a lot of errors. I tried as well the latest version on the standard library, same problem

Anton

**Comment by jespercockx** [comment]
Did you try the `experimental` branch of the standard library? It contains the changes necessary to work with the latest development version of Agda.

**Comment by UlfNorell** [comment]
Please note that the standard library has its own issue tracker: https://github.com/agda/agda-stdlib/issues
