### ISSUE TITLE
Soundness of code for String.agda

### ISSUE THREAD

**Issue by csetzer** [agda/agda#3490]
I'm using the version of Agda #3372  8 Jan 2019.
The file 
/usr/share/agda-stdlib/Data/String.agda

starts with:

Costring : Set
Costring = Colist Char

------------------------------------------------------------------------
-- Operations

toVec : (s : String) → Vec Char (List.length (toList s))
toVec s = Vec.fromList (toList s)

I don't think that can work because you can't translate infinite lists into finite lists.

Anton

**Comment by gallais** [comment]
`String` is the type of finite strings. It's distinct from `Costring`.
