### ISSUE TITLE
Impossible to normalize elements in a proposition

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3493]
In the code below, running `agda2-compute-normalised-toplevel` of `test` returns
```agda
.(ap f refl)
```
instead of the expected `refl` (what does the dot mean, by the way?)
I guess this is by design, after all there is a priori no reason to normalize a term in a proposition, given that it is always going to be equal to anything else of the same type. But in some cases it would be useful to still be able to see the normalized form.
Or is there a workaround to make Agda normalize elements of a proposition anyway?

```agda
{-# OPTIONS --prop #-}

-- Prop-valued identity type
data _≡_ {A : Set} (a : A) : A → Prop where
  refl : a ≡ a

-- normal [ap]
ap : {A B : Set} (f : A → B) {a b : A} → a ≡ b → f a ≡ f b
ap f refl = refl

postulate
  A B : Set
  f : A → B
  a : A

test : f a ≡ f a
test = ap f refl
```

**Comment by nad** [comment]
One can make abstract definitions compute by using `C-u` followed by the normalisation command. Perhaps it would be possible to implement something similar for propositions.

**Comment by guillaumebrunerie** [comment]
This now works (since 65bda2a), but I’m now thinking that we rarely want to actually reduce elements of propositions, so maybe `C-c C-n` should not reduce them by default. An easy fix would be to automatically make `abstract` all definitions whose type is a proposition. This shouldn’t break anything (I think) as Agda should never have to inspect such definitions, and the user could use `C-u C-c C-n` to make them reduce anyway.

**Comment by jespercockx** [comment]
There is now the `--no-reduce-prop` flag to control reduction of definitions in `Prop`, so I'm closing this issue.
