### ISSUE TITLE
Internal error in activateLoadedFileCache

### ISSUE THREAD

**Issue by semenov-vladyslav** [agda/agda#3498]
Agda version 2.6.0-3b6fba1-dirty.
An internal error has occurred. Please report this as a bug.
Location of the error: src/full\\Agda\\TypeChecking\\Monad\\Caching.hs:131

Spotted this bug a few times today while working in emacs on Windows. After the bug occurs Agda can't typecheck anything. After Agda is restarted in emacs the error disappears. It's quite tricky to reproduce. Here is the module: 
```agda
module test where

open import Data.Nat using (ℕ ; zero ; suc)

module _ where
  _#_ : Set → ℕ → Set
  A # zero = A
  A # (suc n) = let A# = A # n in A# → A#

  id : {A : Set} → A # 1
  id x = x

  r : {A : Set} → A # 2 → A # 1
  r g = g (g id)

  s : {A : Set} → {!!} -- (A # 1 → A # 2) → A # 2
  s {A} h = r u where
    u : A # 2 → A # 2
    u w = h (w id)
```

Here is the sequence that leads to the error:

1. In the hole type `? → ?` and C-c C-space, the hole is replaced with `{!!} → {!!}` as expected.
2. Manually replace new `{!!} → {!!}` with `?`.
3. Reload the module with C-c C-l. Bug is triggered now.
4. Kill and restart Agda C-c C-x C-r.
5. Reload module with C-c C-l. Module is loaded OK.

The bug is triggered in other situations and with some other recent version of Agda.

**Comment by gallais** [comment]
With 2.5.3 I get a type error so it's a regression.

```agda
Cannot eliminate type ?0 with pattern h (did you supply too many
arguments?)
when checking that the clause
s {A} h = r u
  where
    syntax u ...
    postulate u : A # 2 → A # 2
    u w = h (w id)
has type {A : Set} → ?0
```

**Comment by nad** [comment]
Caching was not turned on by default in Agda 2.5.3.

**Comment by Saizan** [comment]
In the current model caching of what happens due to interactive commands does not make sense because we have a linear log that follows the typechecking of a file.

The new `CheckFunDef` constraint is what exposed the problem here, I will isolate its solution from the cache.
