### ISSUE TITLE
Internal error in BasicOps

### ISSUE THREAD

**Issue by gallais** [agda/agda#3503]
Bug found by @mietek

```agda
A : {!!}
A a = Set

-- Display constraints (C-c C-=):
-- An internal error has occurred. Please report this as a bug.
-- Location of the error: src/full/Agda/Interaction/BasicOps.hs:457
```

It's a regression. In 2.5.3, Agda rejects the file altogether:

> Cannot eliminate type ?0 with pattern a (did you supply too many arguments?)
> when checking that the clause A a = Set has type ?0

**Comment by andreasabel** [comment]
`git blame` points to c0ffd54a07.  Probably the author of the new `CheckFunDef` constraint postponed the implementation of `reify` to later when it would be forced for the first time, which is now.

**Comment by jespercockx** [comment]
Well, `CheckFunDef` constraints were never meant to actually show up to the user, only used internally as a mechanism for postponing checking a whole function definition. So the first question is why the constraint manages to survive in this case.

**Comment by andreasabel** [comment]
Maybe because the function checking could not complete because of the missing type signature?
