### ISSUE TITLE
Cannot eliminate heterogeneous equality

### ISSUE THREAD

**Issue by smimram** [agda/agda#3508]
Hi,

The code
```agda
open import Relation.Binary.HeterogeneousEquality

module _ (X : Set) (_⇒_ : X → X → Set) where

  test : {x x' y y' : X} {a : x ⇒ y} {a' : x' ⇒ y'} → (eq : a ≅ a') → X
  test refl = {!!}
```
raises the agda error
```
I'm not sure if there should be a case for the constructor refl,
because I get stuck when trying to solve the following unification
problems (inferred index ≟ expected index):
  {_} ≟ {_}
  a ≟ a'
when checking that the pattern refl has type a ≅ a'
```
whereas I would have expected that this would be valid with a unification identifying x with x' and y with y'. Am I missing something? Is there a way to circumvent this?

In case it matters, the version here is 2.5.4.1.

Thanks!

**Comment by gallais** [comment]
> I would have expected that this would be valid with a unification identifying x with x' and y with y'. Am I missing something?

There is no reason for Agda to believe that `_⇒_` is injective.

**Comment by smimram** [comment]
Ah of course, sorry about that. Thanks!
