### ISSUE TITLE
Cubical strange typechecking error

### ISSUE THREAD

**Issue by ice1000** [agda/agda#3509]
I'm playing with the agda/cubical library, using some primitive things. In the builtin module there's:

```agda
primitive
  primTransp : ∀ {a} (A : (i : I) → Set (a i)) (φ : I) → (a : A i0) → A i1
```

But when I copy the type signature and create a type-annotated alias for it, it gives me error:

```agda
transp′ : ∀ {ℓ} (A : (i : I) -> Set (ℓ i)) (φ : I) (a : A i0) -> A i1
transp′ {ℓ = ℓ} A φ a = primTransp {ℓ} A φ a
```

Saying that

```
i != i0 of type I
when checking that the expression transp {ℓ} A φ a has type A i1
```

Is this expected? How can we copy the type signature directly and pass the parameter one by one and see a type error? I'm new to cubical so feel free to close if it's in fact a stupid question (but links/explanations are appreciated, thanks in advance).

**Comment by ice1000** [comment]
Replacing `primTransp {ℓ} A φ a` with `primTransp {ℓ} A i0 a` (according to the error msg) resolves this.

**Comment by ice1000** [comment]
Same thing happens to `hcomp`

**Comment by ice1000** [comment]
Maybe because the `i`s are partial paths, while Agda requires complete path during type-checking

**Comment by ice1000** [comment]
BTW there's `variable i : Level; variable A : Set i` defined above.

**Comment by ice1000** [comment]
Does not happen to `Glue`.

**Comment by Saizan** [comment]
`primTransp`, `primHComp`, and `primComp` have side conditions in their typing rules, so just trying to make an alias like that will fail.

You can use the `Sub` type to capture these side conditions as is done in the `cubical` library for the `*fill` variants.

**Comment by nad** [comment]
> `primTransp`, `primHComp`, and `primComp` have side conditions in their typing rules, so just trying to make an alias like that will fail.

I think this sounds like a design flaw.
