### ISSUE TITLE
Constraint solving for irrelevant metas

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#351]
Related to issue #348.
```agda
record IR : Set1 where
  constructor mkIR
  field
    .fromIR : Set

reflIR : (r : IR) -> r == (mkIR _)
reflIR r = refl
```
The solution `fromIR r` is not found since this variable is unconstrained.  This is only a solution in the presence of the "irrelevant" axiom, or `--irrelevant-projections`.

Actually, any other `Set` would also be a solution.  Agda finds none.

This could be a show-stopper for internal erasure?!  Or an incentive to implement proof search.

Original issue reported on code.google.com by `andreas....@gmail.com` on 15 Oct 2010 at 6:14

Attachments:
- [Issue351.agda](https://storage.googleapis.com/google-code-attachments/agda/issue-351/comment-0/Issue351.agda)

**Comment by UlfNorell** [comment]
This seems to have been fixed. At least James' 50400 example now checks. Pushing test case shortly.
