### ISSUE TITLE
Path applications should be blocking when the interval is blocked or a meta.

### ISSUE THREAD

**Issue by caryoscelus** [agda/agda#3511]
This is probably known, but i haven't seen any similar issues around

```agda
{-# OPTIONS --cubical --safe #-}

open import Cubical.Core.Prelude

data [0-1] : Set where
  𝟎 𝟏 : [0-1]
  int : 𝟎 ≡ 𝟏

0=x : ∀ i → 𝟎 ≡ int i
0=x i j = int {!i ∧ j!} -- fails to load
-- 0=x i j = {!int (i ∧ j)!} -- loads with unsolved constraints, filling hole works fine
```

Agda complains
```
𝟎 != int (?0 (i = i) (j = i0)) of type [0-1]
when checking the definition of 0=x
```
and (unlike similar cases like in commented line) doesn't even load the file, let alone allow filling hole.

Another simple example (not involving HITs):

```agda
si : {n m : ℕ} → suc n ≡ suc m → n ≡ m
si p i = pred (p {!i!})
-- m != pred (x (?0 (p = x) (i = i1))) of type ℕ
```

(incidentally, more generic definition of cong works fine with holes, only complaining about unsolved constraints)

**Comment by ice1000** [comment]
I've found exactly the same problem when developing something in the cubical library.

**Comment by Saizan** [comment]
Thanks for the report. This was fixed in one reduction method but not the other.

**Comment by caryoscelus** [comment]
Thanks for the fixes.
