### ISSUE TITLE
Accidential language change in 2.5.3: hiding is now part of name when resolving hidden argument insertion

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3514]
Before Agda 2.5.3, the following code did _not_ type check:
```agda
test : {{X : Set}} {X : Set} → Set
test {X = X} = X
```
The error was:
```
Unexpected implicit argument
when checking that the clause test {X = X} = X has type
{{X : Set}} {X = X₁ : Set} → Set
```
Now it type checks; the hiding is considered part of the name when resolving hidden arguments: `{{X}}` is distinguished from `{X}`.

The change of behavior was introduced during work on #2597 by commit 31a5982f38, obviously a forgotten negation during a refactoring:
<img width="617" alt="screenshot 2019-01-21 at 08 45 50" src="https://user-images.githubusercontent.com/1155218/51459584-fa926c80-1d50-11e9-9896-1f4353c46420.png">

I think the new behavior makes sense, it is a feature rather than a bug.
This issue is just there to bring the new feature to attention, and to enable a discussion.

**Comment by UlfNorell** [comment]
I agree that this seems like a good, if accidental, change.

**Comment by andreasabel** [comment]
No objections, thus, considering this conversation as resolved.
