### ISSUE TITLE
error in src/full/Agda/Utils/Permutation.hs:68 (please report this as a bug)

### ISSUE THREAD

**Issue by martinescardo** [agda/agda#3516]
I am getting "An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/Utils/Permutation.hs:68"

Agda version 2.6.0-4e32f89

cabal-install version 2.2.0.0
compiled using version 2.2.0.0 of the Cabal library

Arises when doing "agda everything.lagda" in https://github.com/martinescardo/TypeTopology/tree/master/source (without any library).

$ agda everything.lagda 
Checking everything (/home/mhe/feathers/tudo/alive/TypeTopology/source/everything.lagda).
 Checking ADecidableQuantificationOverTheNaturals (/home/mhe/feathers/tudo/alive/TypeTopology/source/ADecidableQuantificationOverTheNaturals.lagda).
  Checking SpartanMLTT (/home/mhe/feathers/tudo/alive/TypeTopology/source/SpartanMLTT.lagda).
   Checking Universes (/home/mhe/feathers/tudo/alive/TypeTopology/source/Universes.lagda).
   Checking Sigma (/home/mhe/feathers/tudo/alive/TypeTopology/source/Sigma.lagda).
  Checking UF-FunExt (/home/mhe/feathers/tudo/alive/TypeTopology/source/UF-FunExt.lagda).
   Checking UF-Base (/home/mhe/feathers/tudo/alive/TypeTopology/source/UF-Base.lagda).
   Checking UF-Equiv (/home/mhe/feathers/tudo/alive/TypeTopology/source/UF-Equiv.lagda).
    Checking UF-Subsingletons (/home/mhe/feathers/tudo/alive/TypeTopology/source/UF-Subsingletons.lagda).
    Checking UF-Retracts (/home/mhe/feathers/tudo/alive/TypeTopology/source/UF-Retracts.lagda).
   Checking UF-LeftCancellable (/home/mhe/feathers/tudo/alive/TypeTopology/source/UF-LeftCancellable.lagda).
  Checking Two (/home/mhe/feathers/tudo/alive/TypeTopology/source/Two.lagda).
  Checking GenericConvergentSequence (/home/mhe/feathers/tudo/alive/TypeTopology/source/GenericConvergentSequence.lagda).
   Checking NaturalsAddition (/home/mhe/feathers/tudo/alive/TypeTopology/source/NaturalsAddition.lagda).
   Checking NaturalsOrder (/home/mhe/feathers/tudo/alive/TypeTopology/source/NaturalsOrder.lagda).
    Checking OrdinalNotions (/home/mhe/feathers/tudo/alive/TypeTopology/source/OrdinalNotions.lagda).
     Checking UF-Subsingletons-FunExt (/home/mhe/feathers/tudo/alive/TypeTopology/source/UF-Subsingletons-FunExt.lagda).
     Checking UF-Miscelanea (/home/mhe/feathers/tudo/alive/TypeTopology/source/UF-Miscelanea.lagda).
      Checking DiscreteAndSeparated (/home/mhe/feathers/tudo/alive/TypeTopology/source/DiscreteAndSeparated.lagda).
       Checking DecidableAndDetachable (/home/mhe/feathers/tudo/alive/TypeTopology/source/DecidableAndDetachable.lagda).
        Checking UF-PropTrunc (/home/mhe/feathers/tudo/alive/TypeTopology/source/UF-PropTrunc.lagda).
       Checking Two-Prop-Density (/home/mhe/feathers/tudo/alive/TypeTopology/source/Two-Prop-Density.lagda).
        Checking UF-Embedding (/home/mhe/feathers/tudo/alive/TypeTopology/source/UF-Embedding.lagda).
         Checking UF-Subsingletons-Equiv (/home/mhe/feathers/tudo/alive/TypeTopology/source/UF-Subsingletons-Equiv.lagda).
         Checking UF-EquivalenceExamples (/home/mhe/feathers/tudo/alive/TypeTopology/source/UF-EquivalenceExamples.lagda).
         Checking UF-Yoneda (/home/mhe/feathers/tudo/alive/TypeTopology/source/UF-Yoneda.lagda).
          Checking UF-Equiv-FunExt (/home/mhe/feathers/tudo/alive/TypeTopology/source/UF-Equiv-FunExt.lagda).
          Checking UF-Univalence (/home/mhe/feathers/tudo/alive/TypeTopology/source/UF-Univalence.lagda).
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/Utils/Permutation.hs:68

The last file UF-Univalence type checks. But e.g. UF-Yoneda doesn't.

I am sorry I am not able to isolate the error. I tried.

**Comment by fredrikNordvallForsberg** [comment]
Smaller test case:
```agda
module UF-Yoneda where

open import Agda.Primitive using (Level)

variable
 l : Level

postulate
  Σ : {l' : Level}{X : Set} (Y : X → Set l') -> Set
  _,_ : {l' : Level}{X : Set} {Y : X → Set l'} -> (x : X)(y : Y x) -> Σ Y
  is-universal-element : {l' : Level}{X : Set} {A : X → Set l'} -> Σ A → Set

  universality-section : {X : Set} {A : X → Set l}  -> (x : X) (a : A x)
                          → is-universal-element {X = X} (x , a)
```
Replacing the `variable` l with an ordinary argument, giving the implicit argument `{A}`, or replacing `(x, a)` with a hole all makes the error go away.

**Comment by UlfNorell** [comment]
Might be related to my fixes of #3340 and #3341.

**Comment by martinescardo** [comment]
With "git reset --hard f77b563" and "cabal install" we get "agda everything.lagda" to work. I randomly picked a version of Agda of early December, commit f77b563d328513138d6c88bf0a3e350a9b91f8ed

**Comment by martinescardo** [comment]
The version of 16th January commit 95f4a24 works, after I modify some of my files.

The modification is needed because the order in which the variables are put in the context seems to have changed (from the order in which they are declared as variables, to the order they occur in the type). 

I committed the version of my repository that works with Agda version 2.6.0-95f4a24.

**Comment by martinescardo** [comment]
So I think @UlfNorell is right.

**Comment by UlfNorell** [comment]
I pushed a fix. @martinescardo can you verify that it solves the problem in you library?

**Comment by martinescardo** [comment]
I compiled the new version of Agda successfully, but now my code fails because of the new handling of --safe (and its omission), and hence I can't yet test your commit. I will let you know when I am done.

**Comment by martinescardo** [comment]
I think there still is a problem. For example, in my module UF-Yoneda, with variables 𝓤 𝓥, I get an unsolved meta at line 162

```
universality-section : {X : 𝓤 ̇} {A : X → 𝓥 ̇} (x : X) (a : A x)
                     → is-universal-element (x , a)
                     → (y : X) → has-section (yoneda-nat x A a y)
universality-section = ...
```
but everything works fine with
```
universality-section : ∀ {𝓤} {𝓥} {X : 𝓤 ̇} {A : X → 𝓥 ̇} (x : X) (a : A x)
                     → is-universal-element (x , a)
                     → (y : X) → has-section (yoneda-nat x A a y)
universality-section = ...
```
That module is now getting 5 unsolved metas:
```
_453 : A x  [ at /home/mhe/feathers/tudo/alive/TypeTopology/source/UF-Yoneda.lagda:162,50-51 ]
_504 : A x  [ at /home/mhe/feathers/tudo/alive/TypeTopology/source/UF-Yoneda.lagda:173,50-51 ]
_1243 : A x  [ at /home/mhe/feathers/tudo/alive/TypeTopology/source/UF-Yoneda.lagda:332,48-49 ]
_1287 : A x  [ at /home/mhe/feathers/tudo/alive/TypeTopology/source/UF-Yoneda.lagda:340,48-49 ]
_2113 : x ≡ x  [ at /home/mhe/feathers/tudo/alive/TypeTopology/source/UF-Yoneda.lagda:531,62-66 ]
```

**Comment by UlfNorell** [comment]
I'm not sure why there's a difference with and without generalisation (I'll investigate further), but I suspect it has to do with the fact that some metas are not solved until you type check the definition. In this case the `A` argument to `is-universal-element` is not determined by the type signature alone (it could be either `A` or `λ _ → A x`). Giving it explicitly makes the yellow disappear:
```agda
universality-section : {X : 𝓤 ̇} {A : X → 𝓥 ̇} (x : X) (a : A x)
                     → is-universal-element {A = A} (x , a)
                     → (y : X) → has-section (yoneda-nat x A a y)
```

**Comment by martinescardo** [comment]
Spooky.

In any case, for some type now, for other reasons (which may be related), I have been entertaining making the this argument A of is-universal-element explicit.

**Comment by martinescardo** [comment]
Making this argument explicit makes the code more readable and side-steps this issue. So now my code works with this version (after also adapting it to the new handling of --safe).

Thanks.

**Comment by UlfNorell** [comment]
Reported the unsolved meta as a new issue (#3519) with a shrunk test case.

**Comment by martinescardo** [comment]
And: now I can do ctrl-x ctrl-s where the completion uses generalizables, which is great. Thanks!
