### ISSUE TITLE
Options consistency checking should not re-typecheck builtin files

### ISSUE THREAD

**Issue by fredrikNordvallForsberg** [agda/agda#3522]
[Elsewhere](https://github.com/agda/agda/commit/273689fecb5a56a2844036cb1c196bb61c32b40e#r32047284), @nad commented
> In that case [not checking option consistency when loading primitive modules], shouldn't we also make sure that primitive modules are always type-checked using the same set of options? Are we already doing that?

which made realize that we shouldn't re-typecheck primitive (already happening) and builtin modules because of changed options, because that would lead to problems as in #3128.

It makes sense to also address @nad's concern above at the same time.

**Comment by fredrikNordvallForsberg** [comment]
Not re-typechecking builtin modules is implemented in  https://github.com/agda/agda/commit/6fa083a641e276cea7c561129fb0419b6285a589 (oops, there was a space between # and the issue number).

Leaving this issue open a bit longer to discuss the following problem: can and should we always check the primitive and builtin modules with the default options?

* Are there any use cases where other options are needed? Currently it is no longer possible to check modules importing most builtin modules using a command line option such as `--type-in-type`, because the safe builtin modules are now declared `--safe`.
* The only way to currently re-typecheck the builtin modules (whose interfaces are generated at install time with default options) is to use `--ignore-interfaces`, so a cheap way to ensure that they are checked with the same options would be to make `--ignore-interfaces` not touch the builtin modules. However is it confusing if `--ignore-interfaces` is not ignoring the builtin interfaces? (The user can also delete the interface files manually, but then I think it is fair to say that they are on their own.)
* Related side remark: how does `--ignore-interfaces` fare with the builtin modules in a central, non-user-writable location? Based on making my `.cabal/share/x86_64-linux-ghc-8.0.2/Agda-2.6.0/lib/prim/Agda/Builtin/` non-writable, not very well, I suspect. This would also be fixed by the changed proposed above, assuming that the answer to the first question above is "no".

**Comment by nad** [comment]
> to make `--ignore-interfaces` not touch the builtin modules

Sounds good to me.

**Comment by Saizan** [comment]
> to make --ignore-interfaces not touch the builtin modules.

If you do so, please also add a flag that really ignores everything, it's useful for debugging.

**Comment by nad** [comment]
> If you do so, please also add a flag that really ignores everything, it's useful for debugging.

I don't think we should make such a flag available to users. It's easy to remove the `.agdai` files manually.

**Comment by fredrikNordvallForsberg** [comment]
> I don't think we should make such a flag available to users. It's easy to remove the .agdai files manually.

Perhaps it wouldn't be so bad to remove them manually, since one would only have to do it for the interface files in the `defaultLibDir`. You could even make an alias that first removed the files, then invoked ``agda --ignore-interfaces``:
```
alias agdaii='find ~/.cabal/share/[...]/prim/ -name "*.agdai" -type f -delete; agda --ignore-interfaces'
```

**Comment by Saizan** [comment]
@fredrikNordvallForsberg It's mainly an issue when it happens on someone else's machine, especially if they are not familiar with where the interface files are stored.

**Comment by nad** [comment]
Are the interface files for the builtin modules always regenerated when Agda is installed? If not, then I think they should be.

It is quite common that someone modifies Agda without modifying the magic number used in the interface files, and sometimes this leads to problems that can be fixed by removing all the interface files.

**Comment by nad** [comment]
> @fredrikNordvallForsberg  It's mainly an issue when it happens on someone else's machine, especially if they are not familiar with where the interface files are stored.

I assume that you are referring to people using the development version of Agda. In that case we can tell them to start by reinstalling Agda. (And finding the directory is easy, at least with a typical Linux machine: `echo $(dirname $(agda-mode locate))/../lib/`.)

**Comment by fredrikNordvallForsberg** [comment]
I've implemented the above suggestion, and added a "hidden" `--ignore-all-interfaces`: it's mentioned in the user manual and changelog (with warnings to avoid using it unless you know what you are doing), but does not show up in `agda --help`.

I didn't merge the pull request yet, in case there are strong opinions about this hidden middle ground.

**Comment by fredrikNordvallForsberg** [comment]
No strong opinions voiced, so I merged. That closes this issue.
