### ISSUE TITLE
Unable to install Agda on MAC

### ISSUE THREAD

**Issue by squera** [agda/agda#3528]
I am following these steps:
https://wiki.portal.chalmers.se/agda/pmwiki.php?n=Main.MacOSX

I got to the step:
- Install Agda by calling cabal install Agda . Now you can go and have a cup of coffee (or two).

And i get this error:
```
cabal: Could not resolve dependencies:
[__0] trying: Agda-2.5.4.2 (user goal)
[__1] next goal: base (dependency of Agda)
[__1] rejecting: base-4.12.0.0/installed-4.1... (conflict: Agda =>
base>=4.8.0.0 && <4.12)
[__1] rejecting: base-4.12.0.0, base-4.11.1.0, base-4.11.0.0, base-4.10.1.0,
base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0, base-4.8.1.0,
base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1,
base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0,
base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0,
base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from
non-upgradeable package requires installed instance)
[__1] fail (backjumping, conflict set: Agda, base)
```

any idea how to proceed? I haven't found how to revert to e.g., base 4.11, which seems like a possible solution to this mess?

I am using 
macOS Sierra, Version 10.12.6 (16G1710)

thanks!

**Comment by gallais** [comment]
> rejecting: base-4.12.0.0

Looks like you have a bleeding edge version of ghc installed. It will be supported after the next release (cf. #3369)

In the meantime the [release candidate](https://hackage.haskell.org/package/Agda-2.5.4.2.20190111/candidate) should (?) work. The easiest way to obtain it is probably
to clone the repo (`git clone https://github.com/agda/agda`) and then checkout the tag (`git checkout tags/v2.5.4.2.20190111`) before running `cabal install`.

**Comment by squera** [comment]
thanks for the explanation and for the suggested workaround, that did the trick :)
