### ISSUE TITLE
Refine does not work for functions with 10 arguments or more

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3532]
Is there a good reason for why `refine` does not work when a function has 10 arguments or more? It’s rather surprising, and the error message "Cannot refine" isn’t very clear. Try `C-c C-r` in the goal below.

```agda
postulate
  A : Set
  f : A → A → A → A → A → A → A → A → A → A → A

test : A
test = {!f!}
```

**Comment by UlfNorell** [comment]
Reason, yes. Good, no.

Refine is a bit of hack. It works by trying to give `f`, `f ?`, `f ? ?`, `f ? ? ?`, etc, up to 10 question marks. The number 10 was scientifically chosen<sup>[citation needed]</sup> to work for most cases without making it too slow in the case you can't refine.

**Comment by guillaumebrunerie** [comment]
Should the error message be improved, then? For instance if Agda sees that `f` has at least 10 arguments and that refine did not work, it could add some kind of warning to the message : 
```Cannot refine (note that refine does not work for functions with 10 arguments or more)```

**Comment by guillaumebrunerie** [comment]
I guess `refine` could also be made smarter. For instance by substracting the number of nested Pi-types in the goal from the number of nested Pi-types in the type of `f`, it should give a number of question marks worth trying.
