### ISSUE TITLE
Internal error evaluating instances

### ISSUE THREAD

**Issue by kirstin-rhys** [agda/agda#3542]
--This does go away upon a restart

    module InstanceArguments where

    open import Data.Bool

    record Eq {ℓ} (A : Set ℓ) : Set ℓ where
      field
        _==_ : A → A → Bool

    open Eq {{...}}

    record Ord (A : Set) : Set where
      field
        _<_ : A → A → Bool
        {{eqA}} : Eq A

    open Ord {{...}} hiding (eqA)

    _≤_ : {A : Set} {{_ : Ord A}} → A → A → Bool
    x ≤ y = x == y ∨ x < y

    {-
    An internal error has occurred. Please report this as a bug.
    Location of the error: src/full/Agda/TypeChecking/Serialise/Instances/Common.hs:178
    -}

**Comment by UlfNorell** [comment]
I can't reproduce this. It works for me on both `2.5.4.2` and current master (449d40b). What version of Agda are you using?

**Comment by gallais** [comment]
This does look exactly like #3199 which was fixed in 2.5.4.2

**Comment by UlfNorell** [comment]
Ok, closing as duplicate. Reopen if necessary.
