### ISSUE TITLE
JavaScript backend: mapping a function that returns Set fails

### ISSUE THREAD

**Issue by sanduteo95** [agda/agda#3545]
Given the following program:
```agda
module Test where
open import Data.Nat
open import Data.Vec

createElem : ℕ → Set
createElem n = ℕ

{-# NOINLINE createElem #-} -- force inlining

{-# COMPILE JS createElem = function (x0) {
    return x0;
} #-}

main : Vec Set 2
main = map (λ n → createElem n) (1 ∷ 1 ∷ [])
```
The JavaScript backend generates the following:
```js
var agdaRTS = require("agda-rts");
var z_jAgda_Data_Vec = require("jAgda.Data.Vec");

exports["createElem"] = function(x0) {
  return x0;
};
exports["main"] = z_jAgda_Data_Vec["map"](agdaRTS.primIntegerFromString("0"))(
  agdaRTS.primIntegerFromString("0")
)(agdaRTS.primIntegerFromString("0"))(agdaRTS.primIntegerFromString("0"))(
  agdaRTS.primIntegerFromString("0")
)(agdaRTS.primIntegerFromString("0"))( // this should be exports["createElem"]
  z_jAgda_Data_Vec["Vec"]["_∷_"](agdaRTS.primIntegerFromString("0"))(
    agdaRTS.primIntegerFromString("1")
  )(
    z_jAgda_Data_Vec["Vec"]["_∷_"](agdaRTS.primIntegerFromString("0"))(
      agdaRTS.primIntegerFromString("1")
    )(z_jAgda_Data_Vec["Vec"]["[]"])
  )
);
```

Although the `createElem` function was defined for JavaScript with the `COMPILE JS` pragma, and the `NOINLINE` pragma is enabled, when used within a map the function is replaced with `agdaRTS.primIntegerFromString("0")`. 

Agda version `2.5.4.2`

**Comment by gallais** [comment]
I think it's related to the fact that the codomain of `createElem` is something that
gets erased. If you give `createElem` a more sensible type (given that it is compiled
to the identity function) then the NOINLINE pragma is respected:

```agda
module Issue3545 where
open import Data.Nat
open import Data.Vec

createElem : ℕ → ℕ
createElem n = 0

{-# NOINLINE createElem #-} -- force inlining

{-# COMPILE JS createElem = function (x0) {
    return x0;
} #-}

main : Vec ℕ 2
main = map createElem (1 ∷ 1 ∷ [])
```

is compiled to (I've replaced `(agdaRTS.primIntegerFromString("0"))` with `X` to
make things more readable):

```js
var agdaRTS = require("agda-rts");
var z_jAgda_Data_Vec = require("jAgda.Data.Vec");

exports["createElem"] = (function (x0) { return x0; });
exports["main"] =
  z_jAgda_Data_Vec["map"]XXXXX(exports["createElem"])
  (z_jAgda_Data_Vec["Vec"]["_∷_"]X(agdaRTS.primIntegerFromString("1")) 
  (z_jAgda_Data_Vec["Vec"]["_∷_"]X(agdaRTS.primIntegerFromString("1")) 
  (z_jAgda_Data_Vec["Vec"]["[]"])));

exports["main"](function (x0) {
  return {};
})
```

**Comment by UlfNorell** [comment]
I'd say this is working as intended, or at least as expected. Types are erased before you get to the backend, so the `createElem` function (being `Set` valued) will be erased. Taking compile pragmas into account for erasure would be complicated and I don't see a good case for it. The example is quite non-sensical.

**Comment by gallais** [comment]
> Taking compile pragmas into account for erasure would be complicated and I don't see a good case for it.

:+1:

We could however warn the user that their `COMPILE` pragma will be ignored.

**Comment by sanduteo95** [comment]
Yes, I agree this example is nonsensical - it was made up to explain the issue in an easier manner. So it's not the actual program I encountered the problem in. The actual use case is for creating a heterogenous vector.

Since you seem to be aware of this and the problem is a bit of an edge case, I'm happy for you to close the issue.
