### ISSUE TITLE
Inference change

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#3559]
```agda
data Identity (t : Set) : Set where
  mkIdentity : t → Identity t

record Monad (f : Set → Set) : Set₁ where
  field
    _<$>_ : ∀ {a b} → (a → b) → f a → f b
    _>>=_ : ∀ {a b} → f a → (a → f b) → f b

open Monad {{...}}

postulate
  _∘_ : ∀ {a b c : Set} → (b → c) → (a → b) → (a → c)
  instance
    _ : Monad Identity

{-# TERMINATING #-}
go : ∀ {p : Set} → Identity p → Identity (Identity (Identity p))
go {p = p} n@(mkIdentity x) = do
  let -- f : ∀ {t : Set} → t → Identity t
      f = λ x → mkIdentity x

  _ ← (_<$>_ (_<$>_ (λ x → x >>= f)) ∘ go) n -- uncomment this line
  _ ← mkIdentity (mkIdentity (f x))          -- or this line
  
  mkIdentity (mkIdentity n)
```

The above previously type checked, but currently Agda fails to find solutions. If you uncomment either of the marked lines or the type signature for `f`, Agda will accept it, which means somehow these goals are interfering with each other, even though they both should resolve the signature for `f` to an mutually-agreeable solution.

Looking more at that first marked line, if you replace the use of `f` with `mkIdentity {_}`, Agda will accept it, but if you try to tell Agda the solution `mkIdentity {p}`, suddenly it will become confused again and say it can't find solutions!

**Comment by jespercockx** [comment]
There are two possible type signatures for `f`: `f : ∀ {t : Set} → t → Identity t` and `p → Identity p`. If you pick the second one, then you get unsolved metas on the first line even if you comment out the second one. So I'm not sure whether this is actually a bug or that Agda is now a bit more conservative in solving metavariables when they are multiple solutions.

**Comment by nad** [comment]
> So I'm not sure whether this is actually a bug or that Agda is now a bit more conservative in solving metavariables when they are multiple solutions.

It sounds to me as if the previous behaviour might have been buggy.

**Comment by identicalsnowflake** [comment]
> I'm not sure whether this is actually a bug or that Agda is now a bit more conservative in solving metavariables when they are multiple solutions.

Yeah that's what was surprising me: it seems to me like either it should reject the first line as unsolvable or it should use/refine the solution it found on the first line on subsequent metas. It seems very odd for the type checker to find a solution it's happy with, then subsequently re-decide that meta was unsolvable after all based on later code.

But it's certainly possible there are reasons for this I'm missing.

**Comment by jespercockx** [comment]
This seems to be an instance of the general problem where Agda doesn't know whether to insert an implicit function space or not (#2099).
