### ISSUE TITLE
Guardedness with no sized types should be safe

### ISSUE THREAD

**Issue by ice1000** [agda/agda#3564]
Currently, the `--safe` flag disables `--guardedness`. IMO `--guardedness` with `--no-sized-types` should be considered safe.

```agda
{-# OPTIONS --cubical --no-sized-types --guardedness --safe #-}
module GuardedBug where
record Stream (A : Set) : Set where
  coinductive
  field head : A
  field tail : Stream A
open Stream

data A : Set where a : A

someA : Stream A
head someA = a
tail someA = someA -- termination check failed
```

**Comment by gallais** [comment]
Note that you can write `{-# OPTIONS --safe --cubical --no-sized-types --guardedness #-}`
and Agda will be happy because `--guardedness` is turned on *after* `--safe`.

**Comment by ice1000** [comment]
I'm aware, but that's no longer safe. I need to import this guardedness-enabled module inside a safe module (as you may know in the cubical library).

**Comment by fredrikNordvallForsberg** [comment]
Isn't this what you mean?

`a.agda`:
```
{-# OPTIONS --safe --cubical --no-sized-types --guardedness #-}
module a where
record Stream (A : Set) : Set where
  coinductive
  field head : A
  field tail : Stream A
open Stream

data A : Set where a : A

someA : Stream A
head someA = a
tail someA = someA -- termination check ok
```

`b.agda`:
```
{-# OPTIONS --safe --cubical --guardedness #-}
module b where

import a
```
Both `a.agda` and `b.agda` are safe. (Note the order of the options in @gallais comment.)

**Comment by ice1000** [comment]
I suppose that means I'll need to enable `--guardedness` in all user modules. Is that really what we want?

**Comment by fredrikNordvallForsberg** [comment]
I agree that the situation is not ideal, especially since we hope to make `--sized-types` and `--guardedness` safe together in the future. As far as I can see, the alternative would be to allow a known construction of false under `--safe` though, which isn't ideal either... Or do you have another proposal?

In the meantime, I updated the documentation to make it clearer that one of `--guardedness` and `--sized-types` can be turned on again after `--safe`.

**Comment by gallais** [comment]
```
The ``--safe`` option turns off the ``--guardedness`` and
``--sized-types`` options that are both on by default. One of them
(but not both, see above) can be turned on again by giving either
``--guardedness`` or ``--sized-types`` *after* the  ``--safe`` option, e.g.
```

Oooh. Could ternary options (`data Flag = Default | Set | UnSet`) solve our problem
here? This way we would manage to distinguish between `{-# OPTIONS --safe #-}` and
`{-# OPTIONS --guardedness --safe #-}`!

In more details:

* `--safe` implies:

     + if `--guardedness` *and* `--sized-types` are `Set` then errorwarning + turning them off
     + otherwise make the `Default` one(s) `UnSet` and leave the (if any) `Set` one alone

* `--guardedness` implies:
    + if `--safe` and `--sized-types` are `Set` then error
    + otherwise change `--guardedness` to `Set`

* `--sized-types` basically the same as `guardedness`
