### ISSUE TITLE
Missing name when printing type of definition of a record

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3566]
```agda
postulate
  A : Set

record R : Set where
  field
    a : A
  b : A
  b = a
open R

test = {!b!}
```
Doing `C-c C-d` in the hole above gives the following nonsense
```agda
(: R) → A
```

**Comment by andreasabel** [comment]
The nonsense gets more fantastic if we have some actual dependency:
```agda
postulate
  A : Set
  P : A → Set
  p : (a : A) → P a

record R : Set where
  field
    a : A
  b : P _
  b = p a
open R

test : _
test = {!b!}
```
`C-c C-d` prints
```
(: R) → P (a)
```
This is a haunting coming back for us from a hackish fix of #208.

Related: #2868. 
And, of course, the root cause is, as so often, #434.

**Comment by andreasabel** [comment]
Without interaction:
```agda
postulate
  A : Set
  P : A → Set
  p : (a : A) → P a

record R : Set where
  field
    a : A
  b : P _
  b = p a

test : A
test = R.b
```
prints
```
(: R) → P (R.a) !=< A of type Set
when checking that the expression R.b has type A
```

**Comment by andreasabel** [comment]
I have a question about the fix as implemented in #3584, see there.

**Comment by jespercockx** [comment]
I changed the implementation to keep track of record names in the abstract names instead of the concrete ones. I also tried to change the name "r" to "self", but it causes a (small) backwards incompatibility in the reflected syntax, so I suggest we hold it off until after the release.

**Comment by andreasabel** [comment]
The current fix adds a field `nameIsRecordName :: Bool` to each `A.Name`, which feels a bit invasive. 
Alternatively, one could add a `Set NameId` to the `Signature` which remembers the record self names.  This would be serialized and deserialized with the signature.

**Comment by jespercockx** [comment]
I think the ship has sailed by now. Please create a new issue if you think the implementation should be changed.
