### ISSUE TITLE
Error message referring to Set instead of Prop

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3582]
```agda
{-# OPTIONS --prop #-}

postulate
  f : Prop → Prop
  P : Prop₁

x : Prop
x = f P
```
We get the error message
```
Set₁ != Set
when checking that the expression P has type Prop
```
instead of the expected `Prop₁ != Prop`.

**Comment by jespercockx** [comment]
I guess there is really a conflict between the levels `lsuc lzero` and `lzero` but Agda tries to display the error in a more readable form, which is however not valid in this example.
