### ISSUE TITLE
Internal error in ConcreteToAbstract.hs:2217

### ISSUE THREAD

**Issue by mcoblenz** [agda/agda#3586]
Agda 2.5.4.2 reports: 
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs:2217
```

when asked to compile this code:

```agda
open import Data.Nat

infixl 5  _,_⦂_
  
-- Internal type of contexts
data ctx : Set where
  ∅     : ctx
  _,_⦂_  : ctx → ℕ → ℕ → ctx


Id : Set
Id = ℕ

record StaticEnv : Set where
  field
    locEnv : ℕ


_,ₗ_⦂_ : StaticEnv → Id → ℕ → StaticEnv
Δ ,ₗ l ⦂ T = record Δ {locEnv = (StaticEnv.locEnv Δ)}

data _&_ok : ℕ → StaticEnv → Set where
  ok : ∀ {n : ℕ}
       → ∀ (Δ : StaticEnv)
       -------------------
       → n & Δ ok

foo : ∀ {n Δ} → n & Δ ok → ℕ

foo consis@(ok {n} (Δ ,ₗ l ⦂ T)) = zero
```

**Comment by gallais** [comment]
I think the internal error comes from the fact that `(Δ ,ₗ l ⦂ T)` is not a pattern.
And therefore `consis@(ok {n} (Δ ,ₗ l ⦂ T))` does not make sense.

If you drop the `consis@` then you do get an appropriate error:

```agda
Could not parse the left-hand side foo (ok {n} (Δ ,ₗ l ⦂ T))
Operators used in the grammar:
  ,ₗ_⦂ (infix operator, level 20) [_,ₗ_⦂_ (/home/gallais/languages/agda/Issue3586.agda:19,1-7)]
when scope checking the left-hand side foo (ok {n} (Δ ,ₗ l ⦂ T)) in
the definition of foo
```

but the `consis@` trips Agda when trying to generate a similar error message.
(The internal error occurs [line 2421](https://github.com/agda/agda/blob/99f0a7a21f3bc2584673deecb7e4c8a2484205f4/src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs#L2421) in the dev version).

**Comment by mcoblenz** [comment]
Aha, I wasn't sure if I could use that as a pattern. But this error message (when I avoided using that as a pattern) made me think the pattern was valid:

```
Incomplete pattern matching for progress. Missing cases:
  progress {simpleExpr (loc l₁)} (ok .(_ ,ₗ l₁ ⦂ _) x x₁)
    (locTy l₁ x₂)
```

**Comment by guillaumebrunerie** [comment]
@gallais If `_,ₗ_⦂_` is renamed to `_,ₗ_⦂'_`, then there is no internal error (instead we get the expected "could not parse the left-hand side"), so it has to do also with the fact `_,_⦂_` and `_,ₗ_⦂_` have a name part in common, apparently.

**Comment by gallais** [comment]
Yeah, this one is pretty nic(h)e! Simplified:

```agda
open import Agda.Builtin.Nat

infixl 5 ^_

data W : Set where
  ^_ : W → W

_^_ : Nat → Nat → Nat
m ^ n = zero

foo : Nat → Nat
foo consis@(Δ ^ T) = zero
```
