### ISSUE TITLE
Occurs check throws error when a solution is possible by eta expansion

### ISSUE THREAD

**Issue by 3abc** [agda/agda#3594]
In the following code snippet, I was trying to define a term `rotIsEquiv'`.

It seems to me this code should **not** work, but it passes type check.

If I inline the definition of `B0` (using that `rot (loop i0) x = x`) then it won't type check. However hiding things inside `pp` will fool the type checker.

```Agda
{-# OPTIONS --cubical --safe #-}
module rotIsEquiv where

open import Cubical.Core.Everything public
open import Cubical.HITs.S1.Base public
open import Cubical.Foundations.Everything public

S1 = S¹

rotIsEquiv' : (a : S1) → isEquiv (rot a)
rotIsEquiv' base = pathToEquiv refl .snd
rotIsEquiv' (loop i) = L i
  where
  pp : (i j : I) → (S1 → S1)
  pp i j x = transp (λ _ → S1) i (rot (loop j) x)
  B0 : I → Set
  B0 i = isEquiv (pp i i0)
  -- B0 i = isEquiv (λ x → transp (λ _ → S1) i x)
  -- uncomment this line and comment the line above to see the error message
  e2 : isEquiv (idfun S1)
  e2 = pathToEquiv refl .snd
  B1 : I → Set
  B1 i = isEquiv (rot (loop i))
  e3 : B0 i0
  e3 = isoToIsEquiv (λ x → x) (λ x → x) (λ z _ → z) (λ z _ → z)
  q : PathP B0 e3 e2
  q = { }0
  l : PathP B1 e3 e3
  l i = rotLoopEquiv i .snd
  L : PathP B1 e2 e2
  L i = hcomp (λ { j (i = i0) → q j
                 ; j (i = i1) → q j })
	      (l i)
```

**Comment by 3abc** [comment]
Here is a simpler version to reproduce this bug

```Agda
test : Set
test = { }11
  where
  A : Set
  A = { }0
  P : I → A ≡ A
  P = { }1
  B0 : A ≡ A
  B0 = { }2
  B1 : B0 i1 ≡ B0 i1
  B1 = { }3
  e2 : B1 i0
  e2' : B1 i1
  e2 = { }4
  e2' = { }5
  e3 e3' : B0 i0
  e3 = { }6
  e3' = { }7
  q : PathP (λ i → B0 i) e3 e2
  q' : PathP (λ i → B0 i) e3' e2'
  l : PathP (λ i → B1 i) e3 e3'
  q = { }8
  q' = { }9
  l = { }10
  L : PathP (λ i → B1 i) e2 e2'
  L i = hcomp (λ {j (i = i0) → q j ; j (i = i1) → q' j}) (l i)
```

With the definitions above, the whole definition of `L i` is marked red, with a lot of `Failed to solve the following constraints`, however if for the definition of `B0` I put in `P i0` (which shouldn't give any information in this case), the number of `Failed to solve` constraints is much less.

**Comment by Saizan** [comment]
@3abc can you explain why you think the first code block should not work?

As far as I can tell, what's going on is that some definitions lead to agda's unifier doing a better job at inferring the implicit `{A}` argument of `hcomp`. That's something to look into for sure but not quite the same as the typechecker being fooled.

Note that the following also gets accepted (pending definition of `q`, of course):

```agda
rotIsEquiv' : (a : S1) → isEquiv (rot a)
rotIsEquiv' base = pathToEquiv refl .snd
rotIsEquiv' (loop i) = L i
 where
  pp : (i j : I) → (S1 → S1)
  pp i j x = transp (λ _ → S1) i (rot (loop j) x)
  B0 : I → Set
  -- B0 i = isEquiv (pp i i0)
  B0 i = isEquiv (λ x → transp (λ _ → S1) i x)
  -- uncomment this line and comment the line above to see the error message
  e2 : isEquiv (idfun S1)
  e2 = pathToEquiv refl .snd
  B1 : I → Set
  B1 i = isEquiv (rot (loop i))
  e3 : B0 i0
  e3 = isoToIsEquiv (iso (λ x → x) (λ x → x) (λ z _ → z) (λ z _ → z))
  q : PathP B0 e3 e2
  q = { }0
  l : PathP B1 e3 e3
  l i = rotLoopEquiv i .snd
  L : PathP B1 e2 e2
  L i = hcomp {A = isEquiv ((rot (loop i)))} ( (λ { j (i = i0) → q j ; j (i = i1) → q j }) )
              (l i)
```

**Comment by 3abc** [comment]
> Note that the following also gets accepted (pending definition of `q`, of course):

Hmmm? If I put this version in I got 
```
Cannot instantiate the metavariable _66 to solution isEquiv (transp
(λ _ → S1) j) since it contains the variable j which is not in
scope of the metavariable or irrelevant in the metavariable but
relevant in the solution
when checking that the expression q j has type _A_66 (i = i0)
```

I'm on `Agda version 2.6.0-1becd2e`

**Comment by 3abc** [comment]
> Note that the following also gets accepted (pending definition of `q`, of course):

And I just upgraded to `Agda version 2.6.0-dfb04d5`, then it's a different error message:

```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Monad/Signature.hs:686
```

However when I did it again I got back the old error message.

**Comment by Saizan** [comment]
@3abc probably something is wrong with some of your interface files somewhere then. Which might also explain the weirdness about the example. Try loading the file with the `--ignore-interfaces` flag then.

**Comment by 3abc** [comment]
> @3abc probably something is wrong with some of your interface files somewhere then. Which might also explain the weirdness about the example. Try loading the file with the `--ignore-interfaces` flag then.

Actually when I did it again I got back the old error message. It was just weird.

**Comment by 3abc** [comment]
> --ignore-interfaces

Do you mean adding `{-# OPTIONS --ignore-interfaces #-}` to the file? I got `Unrecognized option: --ignore-interfaces`

**Comment by Saizan** [comment]
@3abc I meant calling the agda directly. `agda --ignore-interfaces Foo.agda" 

@3abc Also please make sure you are testing my code with the `{A = ...}` argument of `hcomp` given explicitly.

**Comment by 3abc** [comment]
> @3abc Also please make sure you are testing my code with the `{A = ...}` argument of `hcomp` given explicitly.

Hmmm didn't notice that.

**Comment by 3abc** [comment]
Adding {A = isEquiv ((rot (loop i)))} solves the problem. 

Let me think why I thought it shouldn't type check...

**Comment by 3abc** [comment]
@Saizan My concern was the following:

If you look at the type of the sides of the `hcomp`, it's this

```
                    B1
          *  - - - - - - - - > *
          ^                    ^
          |                    |
          |                    |
       B0 |                    | B0
          |                    |
          |                    |
          |                    |
          *  ----------------> *
                    B1
```

And `B0` is not constant. If I'm allow to do a `hcomp` to get the top, then think about the `hfill` of it, on each vertical line the type will be constant. However `B0` is not constant. On a horizontal line (fix `j`) the path `B1` would be a path from `B0 j` to `B0 j`, which is not true. 

It's tricky because some of the paths are loops. But the inside shouldn't be filled by a path constant along vertical line.

**Comment by Saizan** [comment]
@3abc `B0` is constant though, because `transp (λ _ → S1) i x` is definitionally `x`.

**Comment by 3abc** [comment]
> @3abc `B0` is constant though, because `transp (λ _ → S1) i x` is definitionally `x`.

Oh good point. In this case I've no concern.  I believe this can be closed.

**Comment by Saizan** [comment]
I'll keep it open for the unification problem.
What's happening is that eta-contraction is causing `transp` to be under-applied and not compute away. And the occurs check is not trying eta expansion when determining if a variable is in a strong position.

Similarly with record types:

```agda
   record Wrap (A : Set) : Set where
      constructor wrap
      field
        unwrap : A

    open Wrap

    postulate
      X : Set
      x : X
      P : Wrap X → Set


    f : ∀ (y : X) → Wrap X
    f y .unwrap = x

    postulate
      q : ∀ y → P (f y)
      g : ∀ (A : Set) → (∀ (y : X) → A) → X


    test = g ? (\ y → q y)
```

Leads to error:

```
Cannot instantiate the metavariable _84 to solution P (f y) since
it contains the variable y which is not in scope of the
metavariable or irrelevant in the metavariable but relevant in the
solution
when checking that the expression q y has type ?1
```

when we could instead fill the hole with `(P (wrap x))`

**Comment by andreasabel** [comment]
This suggests that the `Cannot instantiate` error should rather lead to a postponement than failing hard.

**Comment by andreasabel** [comment]
A long time ago we considered whether underapplied definitions by copattern matching for non-recursive records should reduce.  But we did not implement it.  Had we, then `f y = wrap x` and the problem would go away.  The question is of course, whether we should still implement it, or whether this would be hazardous to performance.

**Comment by Saizan** [comment]
Maybe we should make use of the ```Underapplied``` in ```NotBlocked``` to either postpone or expand.
