### ISSUE TITLE
Bad performance on pathToEquiv

### ISSUE THREAD

**Issue by 3abc** [agda/agda#3599]
For cubical mode, the following simple code is very slow to type check:

```Agda
{-# OPTIONS --cubical --safe #-}

module slow where

open import Cubical.Core.Everything public
open import Cubical.Foundations.Everything public

slow : (A B : Set) (f : A ≃ B)
  → pathToEquiv (ua f) ≡ pathToEquiv (ua f)
slow A B f i = pathToEquiv (λ i → Glue B (λ { (i = i0) → A , f ; (i = i1) → B , idEquiv B }))
```

```
$ agda -vprofile:7 slow.agda
Checking slow (./slow.agda).
Total           22,727ms       
Miscellaneous       40ms       
Coverage        21,891ms       
Deserialization    767ms       
Serialization       10ms (18ms)
Typing               1ms (18ms)
Parsing             15ms (18ms)
```

What I put in the definition is just `ua f` inlined, shouldn't be that slow.

And `pathToEquiv` is used quite often (for example when doing `hcomp` in `Set`), so it seems vital to have good performance on this.

**Comment by Saizan** [comment]
I agree it can be a problem. That is the main reason `pathToEquiv` is defined by copatterns, so that Agda expands it less often. What's something you were trying to prove where you encountered this?

Mainly the issue is that the normal form of `pathToEquiv (ua f) .snd .equiv-proof x .snd y` when printed out is over 42MB, and it's going to be computed 4 times to typecheck that definition. (All the types involved have eta rules, so we end up comparing the fields).

In an ideal world Agda wouldn't expand `pathToEquiv` at all, and just compare `ua f` and your expanded version, but that's not what happens atm.

It's also quite probable that the 42MB have a lot of redundancy or subterms we could skip when checking equality of terms. 

@mortberg Do you think we could optimize the following proof of `pathToEquiv` btw?

https://github.com/agda/agda/blob/master/src/data/lib/prim/Agda/Builtin/Cubical/Glue.agda#L104

**Comment by 3abc** [comment]
> What's something you were trying to prove where you encountered this?

So you know we have `ua` which send equivalences to paths and it is defined by 
```Agda
ua : ∀ {A B : Set ℓ} → A ≃ B → A ≡ B
ua {A = A} {B = B} e i = Glue B (λ { (i = i0) → (A , e)
                                   ; (i = i1) → (B , idEquiv B) })
```
However it's annoying that `ua (idEquiv A) ≡ refl {x = A}` is kinda hard to prove (is it? let me know if you have a easy proof.)

If I change the definition of `ua` to 
```Agda
ua' : ∀ {ℓ} {A B : Set ℓ} → A ≃ B → A ≡ B
ua' {A = A} {B = B} e i = Glue B (λ { (i = i0) → (A , e)
                                    ; (i = i1) → (B , pathToEquiv (λ _ → B)) })
```
I can easily prove
```Agda
h : (A : Set) → ua' (pathToEquiv (λ _ → A)) ≡ refl
h A i j = hcomp {φ = i ∨ j ∨ ~ j} (λ _ _ → A) A
```

Ideally I'd like to have a easy proof of `transport p ≡ transport q → p ≡ q`. It is true and can be proved but I'd like to find a simple one.

**Comment by guillaumebrunerie** [comment]
> Mainly the issue is that the normal form of `pathToEquiv (ua f) .snd .equiv-proof x .snd y` when printed out is over 42MB, and it's going to be computed 4 times to typecheck that definition. (All the types involved have eta rules, so we end up comparing the fields).

Is there a strong reason for having eta in the types involved?

**Comment by 3abc** [comment]
> the normal form of `pathToEquiv (ua f) .snd .equiv-proof x .snd y` when printed out is over 42MB

How do I ask Agda to show the full normal form? If I do `C-c C-n` it doesn't alway expand things in `where` clause. Isn't it supposed to expand everything? Sometimes normal forms end up containing things like `T.u` (where `T` is the name of the module). Is this a known issue?

**Comment by WolframKahl** [comment]
> So you know we have `ua` which send equivalences to paths and it is defined by
> 
> ```agda
> ua : ∀ {A B : Set ℓ} → A ≃ B → A ≡ B
> ua {A = A} {B = B} e i = Glue B (λ { (i = i0) → (A , e)
>                                    ; (i = i1) → (B , idEquiv B) })
> ```

At the source of my knowledge about Cubical, https://github.com/mortberg/agda/blob/cubicaldoc/doc/user-manual/language/cubical.lagda.rst, I find:

> Partial elements are introduced using pattern matching:
> ```agda
> partialBool : ∀ i → Partial (i ∨ ~ i) Bool
> partialBool i (i = i0) = true
> partialBool i (i = i1) = false
> ```
> The term partialBool should be thought of a boolean with different values when (i = i0) and (i = i1). Terms of type Partial φ A can also be introduced using a :ref:`pattern-lambda`.

I somehow have the impression that using a pattern lambda is quite some overkill, and would expect a more-efficient-and-easier-to-reason-about way to communicate those two endpoints, corresponding to:
```agda
mkPartial : {ℓ : Level} {A : Set ℓ} (x y : A) → ∀ i → Partial (i ∨ ~ i) A
mkPartial x y i (i = i0) = x
mkPartial x y i (i = i1) = y
```
(Are `i = i0` and `i = i1` special patterns for the new built-in type `IsOne`? Where should one ask questions about https://github.com/mortberg/agda/blob/cubicaldoc/doc/user-manual/language/cubical.lagda.rst ?)

**Comment by mortberg** [comment]
> I agree it can be a problem. That is the main reason `pathToEquiv` is defined by copatterns, so that Agda expands it less often. What's something you were trying to prove where you encountered this?
> 
> Mainly the issue is that the normal form of `pathToEquiv (ua f) .snd .equiv-proof x .snd y` when printed out is over 42MB, and it's going to be computed 4 times to typecheck that definition. (All the types involved have eta rules, so we end up comparing the fields).
> 
> In an ideal world Agda wouldn't expand `pathToEquiv` at all, and just compare `ua f` and your expanded version, but that's not what happens atm.
> 
> It's also quite probable that the 42MB have a lot of redundancy or subterms we could skip when checking equality of terms.
> 
> @mortberg Do you think we could optimize the following proof of `pathToEquiv` btw?
> 
> https://github.com/agda/agda/blob/master/src/data/lib/prim/Agda/Builtin/Cubical/Glue.agda#L104

I'll have to think about whether we can optimize the proof of `pathToEquiv`, but no matter what we should probably not use it at all internally. The idea is that instead of reducing hcomp in U to a Glue with pathToEquiv's we treat hcomp U as a value. We then have to explain transp in hcomp U and this follows the same algorithm as for Glue, except we can do some optimizations as we know exactly which equivalence we need to use. Here's the code in cubicaltt:

https://github.com/mortberg/cubicaltt/blob/pi4s3_dimclosures/Eval.hs#L893

`lemEqConst` is an optimized version of the most complicated part of `pathToEquiv` which uses the fact that we are extending a partial element in the fiber where the path is refl. Implementing this should hopefully make Cubical Agda quite a lot faster.

**Comment by mortberg** [comment]
> > So you know we have `ua` which send equivalences to paths and it is defined by
> > ```agda
> > ua : ∀ {A B : Set ℓ} → A ≃ B → A ≡ B
> > ua {A = A} {B = B} e i = Glue B (λ { (i = i0) → (A , e)
> >                                    ; (i = i1) → (B , idEquiv B) })
> > ```
> 
> At the source of my knowledge about Cubical, https://github.com/mortberg/agda/blob/cubicaldoc/doc/user-manual/language/cubical.lagda.rst, I find:
> 
> > Partial elements are introduced using pattern matching:
> > ```agda
> > partialBool : ∀ i → Partial (i ∨ ~ i) Bool
> > partialBool i (i = i0) = true
> > partialBool i (i = i1) = false
> > ```
> > 
> > 
> > The term partialBool should be thought of a boolean with different values when (i = i0) and (i = i1). Terms of type Partial φ A can also be introduced using a :ref:`pattern-lambda`.
> 
> I somehow have the impression that using a pattern lambda is quite some overkill, and would expect a more-efficient-and-easier-to-reason-about way to communicate those two endpoints, corresponding to:
> 
> ```agda
> mkPartial : {ℓ : Level} {A : Set ℓ} (x y : A) → ∀ i → Partial (i ∨ ~ i) A
> mkPartial x y i (i = i0) = x
> mkPartial x y i (i = i1) = y
> ```
> 
> (Are `i = i0` and `i = i1` special patterns for the new built-in type `IsOne`? Where should one ask questions about https://github.com/mortberg/agda/blob/cubicaldoc/doc/user-manual/language/cubical.lagda.rst ?)

You can comment and ask questions about the documentation on my pull request: https://github.com/agda/agda/pull/3571

I would very much appreciate comments about what is unclear in that thread.

**Comment by mortberg** [comment]
> > What's something you were trying to prove where you encountered this?
> 
> So you know we have `ua` which send equivalences to paths and it is defined by
> 
> ```agda
> ua : ∀ {A B : Set ℓ} → A ≃ B → A ≡ B
> ua {A = A} {B = B} e i = Glue B (λ { (i = i0) → (A , e)
>                                    ; (i = i1) → (B , idEquiv B) })
> ```
> 
> However it's annoying that `ua (idEquiv A) ≡ refl {x = A}` is kinda hard to prove (is it? let me know if you have a easy proof.)
> 

This has a very simple proof using a higher Glue: https://github.com/agda/cubical/blob/master/Cubical/Foundations/Univalence.agda#L44


> 
> Ideally I'd like to have a easy proof of `transport p ≡ transport q → p ≡ q`. It is true and can be proved but I'd like to find a simple one.

Can't you just use J twice?

**Comment by 3abc** [comment]
> > However it's annoying that `ua (idEquiv A) ≡ refl {x = A}` is kinda hard to prove (is it? let me know if you have a easy proof.)
> 
> This has a very simple proof using a higher Glue: https://github.com/agda/cubical/blob/master/Cubical/Foundations/Univalence.agda#L44

Oh I wasn't aware of this! Thanks for letting me know.

> 
> > Ideally I'd like to have a easy proof of `transport p ≡ transport q → p ≡ q`. It is true and can be proved but I'd like to find a simple one.
> 
> Can't you just use J twice?

Emmm, how?

**Comment by mortberg** [comment]
> Emmm, how?

Nevermind, I have to think more about this. You can prove that transport is invertible as follows:
```
transport^-1 : ∀ {ℓ} {A B : Set ℓ} → A ≡ B → B → A
transport^-1 p b = transp (λ i → p (~ i)) i0 b

transportEq : ∀ {ℓ} {A B : Set ℓ} → (p : A ≡ B) → (a : A) → transport^-1 p (transport p a) ≡ a
transportEq p a j = transp (λ i → p (~ i ∧ ~ j)) j (transp (λ i → p (i ∧ ~ j )) j a)
```

But I don't see how this helps with what you want to prove... Anyway, we should probably not discuss this further here but rather on the agda/cubical.

**Comment by 3abc** [comment]
> Anyway, we should probably not discuss this further here but rather on the agda/cubical.

OK. It would be great if we open a weekly (or biweekly) issue there for free discussion of cubical things. What do you think? Sometimes things like "how to simply prove `ua (idEquiv A) ≡ refl {x = A}`" feels too trivial to open a specific issue for it but having a place for it is good.

**Comment by molikto** [comment]
does hash consing mentioned in http://www.cse.chalmers.se/~nad/publications/danielsson-lopez-juan-types2017.pdf this paper might help the situation? (don't know if Agda have it or not

**Comment by Saizan** [comment]
> Is there a strong reason for having eta in the types involved?

We could easily try to disable eta for `isEquiv` and see how that impacts proofs. There shouldn't be a fundamental reason for it to have eta.

@mortberg That's fair, but then `hcomp {A = Set _}  u u0` will be its own type former, with introductions and eliminations, and semantics a priori independent from `Glue`.

@molikto I'm interested in more definitive results from that project :) My intuition is that If we recognized early that we really want to normalize both sides, hash consing could indeed cut this down to only two normalizations and probably make them faster.

**Comment by Saizan** [comment]
> > the normal form of `pathToEquiv (ua f) .snd .equiv-proof x .snd y` when printed out is over 42MB
> 
> How do I ask Agda to show the full normal form? If I do `C-c C-n` it doesn't alway expand things in `where` clause. Isn't it supposed to expand everything? Sometimes normal forms end up containing things like `T.u` (where `T` is the name of the module). Is this a known issue?

There's no command to get the eta-long normal form, if that's what you are referring to.

**Comment by mortberg** [comment]
> @mortberg That's fair, but then `hcomp {A = Set _} u u0` will be its own type former, with introductions and eliminations, and semantics a priori independent from `Glue`.

Yes, in cubicaltt we reused the glue/unglue constructors for this. But that is maybe a bit too much of a hack... In yacctt I just added intro/elim forms for `hcomp` in `Set` and it wasn't particularly hard to do. No matter what we do I think this is worth implementing as it should make Cubical Agda faster and the internals would not rely on `pathToEquiv`.

**Comment by Saizan** [comment]
The changes needed in the library for no-eta on ```isEquiv``` are very small, and that would already speed up the original example: https://github.com/agda/cubical/commit/0df744ad010e716e8fe81bac6ce244b160427455

It might still be more efficient to ```transport``` across a ```hcomp {A = Set}``` if we make it a canonical form, but I would try the smaller change first.

@mortberg What do you think?

**Comment by mortberg** [comment]
> eta

How do you disable eta for `isEquiv`? Is it a change internally to Agda or just to the Primitives (or something else)?

**Comment by Saizan** [comment]
It's a change in the definition of the record type, so in ```Agda.Builtin.Cubical.Glue``` for example.

```agda
record isEquiv {ℓ ℓ'} {A : Set ℓ} {B : Set ℓ'} (f : A → B) : Set (ℓ ⊔ ℓ') where
  no-eta-equality
  field
    equiv-proof : (y : B) → isContr (fiber f y)
```

**Comment by mortberg** [comment]
I see, that seems simple enough! Can it make it into the next release?

**Comment by Saizan** [comment]
I think so. I will push it now.

**Comment by nad** [comment]
> No matter what we do I think this is worth implementing as it should make Cubical Agda faster and the internals would not rely on `pathToEquiv`.

And perhaps we could also make progress on "`--cubical-without-glue`" (#3750). Have you decided how to proceed with this ticket? Is the implementation easy or hard?

**Comment by Saizan** [comment]
As of 47ad9b3dbdc2f4cfd36b4c6570c1ba593573409e Agda no longer relies on ```pathToEquiv``` or ```Glue``` for ```hcomp``` in  ```Set```.

**Comment by mortberg** [comment]
> As of [47ad9b3](https://github.com/agda/agda/commit/47ad9b3dbdc2f4cfd36b4c6570c1ba593573409e) Agda no longer relies on `pathToEquiv` or `Glue` for `hcomp` in `Set`.

Nice! Did you do any benchmarks? 

How did you implement this? hcomp in U is a value and hcomp/transp has an extra case for these values?

**Comment by mortberg** [comment]
PS: are you using the "Dagstuhl lemma"?

**Comment by Saizan** [comment]
> > As of [47ad9b3](https://github.com/agda/agda/commit/47ad9b3dbdc2f4cfd36b4c6570c1ba593573409e) Agda no longer relies on `pathToEquiv` or `Glue` for `hcomp` in `Set`.
> 
> Nice! Did you do any benchmarks?

Actually no, I suppose I could have benchmarked the cubical library.

> How did you implement this? hcomp in U is a value and hcomp/transp has an extra case for these values?

Yes.

> PS: are you using the "Dagstuhl lemma"?

Yep:

https://github.com/agda/agda/blob/master/src/data/lib/prim/Agda/Builtin/Cubical/HCompU.agda#L62

**Comment by mortberg** [comment]
Cool! 

What do you do for hcomp in nat?

**Comment by mortberg** [comment]
(or other closed datatypes)
