### ISSUE TITLE
`transp must be fully applied` complained even when it is fully applied

### ISSUE THREAD

**Issue by 3abc** [agda/agda#3601]
In the following snippet the result of `transp` is a function. But if I apply it to another variable I got the `transp must be fully applied` error. Putting the `transp` in a `where` clause can bypass this bug. 

Similar error also seems to happen to `primPOr`.

```Agda
{-# OPTIONS --cubical --safe #-}

module test where

open import Cubical.Core.Everything public

module _ (A : Set) (x y z t : A) (f : y ≡ z) (g : y ≡ x) (h : z ≡ t) where
  test : PathP (λ i → g i ≡ h i) f (transport (λ i → g i ≡ h i) f)
  test k = transp (λ i → g (i ∧ k) ≡ h (i ∧ k)) (~ k) f
  -- test k i = transp (λ i → g (i ∧ k) ≡ h (i ∧ k)) (~ k) f i
```

**Comment by andreasabel** [comment]
Thanks for the report.  Agda seems to reject overapplied `transp`.  However, there is no good reason to do so, @Saizan !?

**Comment by 3abc** [comment]
@andreasabel this bug also appears for `primPOr`, and maybe other primitives.

**Comment by 3abc** [comment]
@andreasabel Also I don't think `Glue` can be over-applied at all. The result of `Glue` is in `Set ℓ` and cannot be applied to anything.

**Comment by Saizan** [comment]
@andreasabel Indeed there's no problem with over-application, just a bug.

@3abc The relaxed check is on `glue`, which can be overapplied if the face is `i1`.

As `conid` cannot be overapplied I think we covered all the affected primitives.

**Comment by andreasabel** [comment]
I have some doubts that my simple fix can also be applied to `primPOr`.  In the cases that I fixed, the type `t1` of the application was not used, but for `primPOr` it is used.  But it is only the correct type to compare `u` and `v` at when the application ends in `v`.

Here a test:
```agda
  foo : ∀ {ℓ} (i : I) {A : .(IsOne i) → (Set ℓ)}
        → PartialP i (λ z → A z)
        → (r : IsOne i)
        → A r
  foo i {A} u r = primPOr i i {A} u (λ j → u j) r
```
Agda complains now:
```
u != λ .j → u _ of type A r
```
It seems to compare `u` and `v` at the wrong type.

**Comment by Saizan** [comment]
@andreasabel That's fair, we can use `A` then.
