### ISSUE TITLE
A term fills a hole, but Agda complains later

### ISSUE THREAD

**Issue by 3abc** [agda/agda#3602]
In the following snippet I encounter a weird bug, namely `refl` fills the hole (using `Ctrl-SPACE`), then later when I load the file it won't type check.

```Agda
module weird (A : Set) (x : A) where
open import Agda.Builtin.Equality public

t0 : A

t1 : x ≡ t0
t1 = { }0 -- refl

t0 = x
```

The error message is `x != t0 of type A`. 
It only happens when definition of `t0` comes after that of `t1`.

**Comment by guillaumebrunerie** [comment]
This is a well-known issue, see #118.

**Comment by 3abc** [comment]
> This is a well-known issue, see #118.

Oh, I didn't know this. So is it planned to be fixed?

**Comment by andreasabel** [comment]
Issue #118 has been open for 10 years.  Did you know that your life expectancy grows with your age?  Same for issues.  
It is unlikely that this issue will be fixed any time soon.  It would require a persistent implementation of Agda's `Signature`, with the risk of huge memory leaks.

**Comment by nad** [comment]
> It would require a persistent implementation of Agda's `Signature`, with the risk of huge memory leaks.

Could you elaborate on this?
