### ISSUE TITLE
File should be readonly when loading a file from emacs

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda#3609]
I think it would make sense, if agda-mode can turn the file readonly immediately after `C-c C-l` is pressed, then make it writable again once the file is fully loaded.

this is going to be helpful, because in a big file when loading takes noticeable time, editing the file before fully loaded will remove the syntactical highlight, and that will force me to reload the file again. furthermore, before the file is fully loaded, new holes are remained question marks and is not in a right state to modify, anyways.

**Comment by nad** [comment]
I really want to be able to edit the file while it, and its dependencies, are being loaded.

> that will force me to reload the file again.

Agda caches the result of typechecking the file, and the mutual blocks (roughly speaking) above the ones you have edited are not typechecked again.

**Comment by HuStmpHrrr** [comment]
does that mean I have some problems with my editing habits? 

normally when the file grows above 400 lines the delay starts to be noticeable. how do you, for example, realize a hole when a file is loading? or do you do a different kind of editing while loading?

**Comment by nad** [comment]
What do you mean by "realize a hole"?

> normally when the file grows above 400 lines the delay starts to be noticeable.

If it seems as if caching does not work, or works less well than it should, then you could report this. I recently reported such a problem (#3593).

**Comment by nad** [comment]
I'm closing this ticket, but feel free to ask more questions.
