### ISSUE TITLE
a != .(a) with Prop or irrelevance

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3618]
The code below fails to type-check with the unexpected error `a != .(a) of type A
when checking that the expression c has type P b`.
The issue is that somehow `b` does not reduce to `a` but to `.(a)`. If you change `Q : Prop` to `Q : Set` it works as expected.
```agda
{-# OPTIONS --prop #-}

postulate
  A : Set
  P : A → Prop
  a : A
  c : P a
  Q : Prop

x : Q
x = {!!} where
  b : A
  b = a

  d : P b
  d = c
```

**Comment by jespercockx** [comment]
Note that the same problem occurs for irrelevance, so this is no new problem introduced by `Prop`:
```agda

postulate
  A : Set
  P : A → Set
  a : A
  c : P a
  Q : Set

.x : Q
x = _ where
  b : A
  b = a

  d : P b
  d = c
```
gives the same error.

**Comment by jespercockx** [comment]
I'm working on a fix which involves weakening the interaction between irrelevance and `Prop`, which should resolve all these weird problems with dotted terms popping up when all you're using is `Prop`.

**Comment by jespercockx** [comment]
I pushed my fix (see https://github.com/agda/agda/commit/65bda2ad4bdc539266aea209c2542566be0a46bb), now you're no longer allowed to use irrelevant variables when proving a `Prop`, but you will (hopefully) never get dotted terms when you're only using `Prop`. @guillaumebrunerie could you please test this on your development using `Prop` to make sure I didn't break anything? Thanks!

**Comment by guillaumebrunerie** [comment]
I just tested it and everything still works. Thanks!
