### ISSUE TITLE
"Could not find module ‘Numeric.IEEE’" error when compiling Agda helloworld

### ISSUE THREAD

**Issue by VictorTaelin** [agda/agda#3619]
I'm trying to compile the example "Hello World" from [Agda 2.5.4 documentation](https://agda.readthedocs.io/en/v2.5.4/tools/compilers.html):
```agda
    module HelloWorld where
    
    open import Agda.Builtin.IO
    open import Agda.Builtin.Unit
    open import Agda.Builtin.String
    
    postulate
      putStrLn : String → IO ⊤
    
    {-# FOREIGN GHC import qualified Data.Text.IO as Text #-}
    {-# COMPILE GHC putStrLn = Text.putStrLn #-}
    
    main : IO ⊤
    main = putStrLn "Hello, World!"
```
When running the `agda --compile HelloWorld.agda` command, though, I get the following error:

    Calling: ghc -O -o /Users/v/vic/dev/agmoon/HelloWorld -Werror -i/Users/v/vic/dev/agmoon -main-is MAlonzo.Code.HelloWorld /Users/v/vic/dev/agmoon/MAlonzo/Code/HelloWorld.hs --make -fwarn-incomplete-patterns -fno-warn-overlapping-patterns
    [1 of 5] Compiling MAlonzo.RTE      ( MAlonzo/RTE.hs, MAlonzo/RTE.o )
    Compilation error:
    
    MAlonzo/RTE.hs:11:1: error:
        Could not find module ‘Numeric.IEEE’
        Use -v to see a list of the files searched for.
       |
    11 | import Numeric.IEEE ( IEEE(identicalIEEE) )
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Why?

**Comment by Blaisorblade** [comment]
The issue as reported is not a bug. The generated code uses a Haskell library, as mentioned in https://agda.readthedocs.io/en/v2.5.4/tools/compilers.html#required-libraries-for-the-built-ins, so that must be installed, e.g. via `cabal install ieee754`.
I expect PRs clarifying docs could be accepted? If you want an issue, I'd recommend a separate one.

**Comment by andreasabel** [comment]
Since everyone is stumbling over this problem, we should try and solve it.
* `ieee754` is already in the dependencies of the Agda library, why do we still get these glitches?
* Would it help to add it to the dependencies of the Agda executable?

We could fix the GHC backend to not require `Numeric.IEEE` unless the compiled Agda program uses floats.

**Comment by UlfNorell** [comment]
I believe the new-fangled package managers (stack and cabal-v2) are to blame for this problem. With old-style cabal v1-install, installing Agda would drop ieee in your global package database, but these days this is no longer the case. Don't know enough about stack/cabal-v2 to know if there's anything we can do.

If we break out the float parts from `MAlonzo.RTE` into `MAlonzo.RTE.Float` or somesuch, it might not be too hard to only import it when necessary.

**Comment by Blaisorblade** [comment]
👍 on on splitting out `MAlonzo.RTE.Float` as a workaround. And FWIW from my experience on #agda, most people running into this issue want to install Agda and try it out, not necessarily run programs. Most of the time, the solution is to ignore the Hello World section.

==
On the technical problem for people using floats, @UlfNorell is correct: you're not supposed to use the global package database.

The right way to build an Agda package is by writing a cabal file like https://github.com/cedille/cedille/blob/d0f69cc6fbfb69d7ef83a436b623d612328eb016/cedille.cabal.

Unfortunately, right now you must write it by hand and rely on Alonzo's name-mangling staying constant. A solution for that general problem would also solve this particular issue. The lowest-cost fix for that is to _document_ MAlonzo name mangling, how to write that `.cabal` file, include the actual .cabal file needed for the example program, and direct users to the instructions of their favorite package manager for the actual build.

**Comment by nad** [comment]
See #4627.

**Comment by syntoscat** [comment]
<details>
<summary>Click here for sad cat picture</summary>


![sadcat](https://user-images.githubusercontent.com/46231518/80894394-46e09200-8ca0-11ea-812d-e82caa240e1d.jpg)

</details>
Help me!!!!! I am not able to compile a thing. Version 2.6.1 Numeric.IEEE  I am a novice.

**Comment by Blaisorblade** [comment]
@cohradoesr I recommend asking https://gitter.im/agda/agda, but you will need to provide more details about your actual problem. I took the liberty of hiding the cat picture, as it provides no content. (People can still see it if they want).

**Comment by nad** [comment]
This seems to impact quite a few users now, so I changed the milestone.

**Comment by gallais** [comment]
> The right way to build an Agda package is by writing a cabal file like (...) Unfortunately, right now you must write it by hand and rely on Alonzo's name-mangling staying constant.

We could maybe use a templating engine such as [`mustache`](https://hackage.haskell.org/package/mustache) to appropriately
instantiate a `.cabal` file template.
Users could provide their own but we would ship Agda with a sane default.

**Comment by Blaisorblade** [comment]
@gallais That sounds excellent. Maybe the template could even include build instructions (not sure if Agda should run them, or the user), and anybody could provide alternative templates for cabal v2/stack/(maybe nix?)/different combos.

**Comment by capn-freako** [comment]
I got this (i.e. - compile and run of `hello-world.agda`) working by doing two things:

## 1. Combine my "split" GHC configuration.

I noticed that my GHC configuration seemed to be split between `~/` and `~/AppData/Roaming/`:

```
$ ls ~/.ghc/x86_64-mingw32-8.10.1/
environments/

$ ls ~/AppData/Roaming/ghc/x86_64-mingw32-8.10.1/
package.conf.d/
```

And I thought fixing this might get things working.
Alas...

```
$ cp -r ~/.ghc/x86_64-mingw32-8.10.1/environments/ ~/AppData/Roaming/ghc/x86_64-mingw32-8.10.1/

$ ls ~/AppData/Roaming/ghc/x86_64-mingw32-8.10.1/
environments/  package.conf.d/

$ ghc-pkg --user recache

$ ghc-pkg --user list
C:\Users\capnf\AppData\Roaming\ghc\x86_64-mingw32-8.10.1\package.conf.d
    (no packages)
```

## 2. Use an explicit `v1-install` command for the `ieee754` package.

OMG! I don't believe this: all I needed was a `v1-install` of the `ieee754` package; D'oh!

```
$ cabal v1-install ieee754
Resolving dependencies...
Starting     ieee754-0.8.0
Building     ieee754-0.8.0
Completed    ieee754-0.8.0

$ ghc-pkg describe ieee754
name:                 ieee754
version:              0.8.0
visibility:           public
id:                   ieee754-0.8.0-KMHK0GtLIS3IfVtQsAJj3f
key:                  ieee754-0.8.0-KMHK0GtLIS3IfVtQsAJj3f
license:              BSD-3-Clause
copyright:            (c) 2011-2016. Patrick Perry <patperry@gmail.com>
maintainer:           Patrick Perry <patperry@gmail.com>
author:               Patrick Perry
homepage:             http://github.com/patperry/hs-ieee754
synopsis:             Utilities for dealing with IEEE floating point numbers
description:
    Utilities for dealing with IEEE floating point numbers, ported
    from the Tango math library; approximate and exact equality
    comparisons for general types.

category:             Math
abi:                  c9ac6a633465a2e37cef504bf84407d4
exposed:              True
exposed-modules:      Data.AEq Numeric.IEEE
import-dirs:
    C:\Users\capnf\AppData\Roaming\cabal\x86_64-windows-ghc-8.10.1\ieee754-0.8.0-KMHK0GtLIS3IfVtQsAJj3f

library-dirs:
    C:\Users\capnf\AppData\Roaming\cabal\x86_64-windows-ghc-8.10.1\ieee754-0.8.0-KMHK0GtLIS3IfVtQsAJj3f

dynamic-library-dirs:
    C:\Users\capnf\AppData\Roaming\cabal\x86_64-windows-ghc-8.10.1

data-dir:
    C:\Users\capnf\AppData\Roaming\cabal\x86_64-windows-ghc-8.10.1\ieee754-0.8.0

hs-libraries:         HSieee754-0.8.0-KMHK0GtLIS3IfVtQsAJj3f
include-dirs:         C:\tools\msys64\mingw64\include
depends:              base-4.14.0.0
haddock-interfaces:
    C:\Users\capnf\AppData\Roaming\cabal\doc\x86_64-windows-ghc-8.10.1\ieee754-0.8.0\html\ieee754.haddock

haddock-html:
    C:\Users\capnf\AppData\Roaming\cabal\doc\x86_64-windows-ghc-8.10.1\ieee754-0.8.0\html
pkgroot: "C:\\Users\\capnf\\AppData\\Roaming\\ghc\\x86_64-mingw32-8.10.1"

$ agda --compile hello-world.agda
Calling: ghc -O -o C:\Users\capnf\Documents\Agda\hello-world -Werror -iC:\Users\capnf\Documents\Agda -main-is MAlonzo.Code.QhelloZ45Zworld C:\Users\capnf\Documents\Agda\MAlonzo\Code\QhelloZ45Zworld.hs --make -fwarn-incomplete-patterns -fno-warn-overlapping-patterns
Loaded package environment from C:\Users\capnf\AppData\Roaming\ghc\x86_64-mingw32-8.10.1\environments\default
[  1 of 123] Compiling MAlonzo.RTE      ( MAlonzo\RTE.hs, MAlonzo\RTE.o )
[  2 of 123] Compiling MAlonzo.Code.Agda.Primitive ( MAlonzo\Code\Agda\Primitive.hs, MAlonzo\Code\Agda\Primitive.o )
{snip}
[122 of 123] Compiling MAlonzo.Code.IO  ( MAlonzo\Code\IO.hs, MAlonzo\Code\IO.o )
[123 of 123] Compiling MAlonzo.Code.QhelloZ45Zworld ( C:\Users\capnf\Documents\Agda\MAlonzo\Code\QhelloZ45Zworld.hs, C:\Users\capnf\Documents\Agda\MAlonzo\Code\QhelloZ45Zworld.o )
Linking C:\Users\capnf\Documents\Agda\hello-world.exe ...

$ ./hello-world.exe
Hello, World!
```

Unfortunately, I neglected to do my experiment in a way, such that the effects of these two actions would've been separable.
So, I don't know if both are necessary or, if only one is necessary, which.
Sorry. :(

This was all done on a Windows-10 machine, using a _Git Bash_ shell to run the above commands.
(That's why you see forward slashes, instead of reverse slashes.)

My _Haskell Platform_ installation was redone from scratch, using the new _Chocolatey_ based installation flow recommended [here](https://www.haskell.org/platform/windows.html).

**Comment by andreasabel** [comment]
Changed the milestone since this fix was not released in 2.6.1.1.

**Comment by gallais** [comment]
I just hit this one on the CI for agda-stdlib. I'd argue it's still not very
satisfactory to launch a compilation using `agda -c` only to have it fail like
this.

**Comment by UlfNorell** [comment]
Yes, #4627 is still open.
