### ISSUE TITLE
Internal error at src/full/Agda/TypeChecking/Serialise/Instances/Internal.hs:314

### ISSUE THREAD

**Issue by martinescardo** [agda/agda#3622]
Agda version 2.6.0-66b8fc3 gives

```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Serialise/Instances/Internal.hs:314
```

I am unable to create a self-contained example. By binary search, I found that the error is in lines 347-352 of the code https://github.com/martinescardo/TypeTopology/blob/master/source/UF-StructureIdentityPrinciple.lagda

Agda version 2.6.0-1771bb2 doesn't give this error.

**Comment by gallais** [comment]
Looks like it's possibly @Saizan's f7db2bf171080e51e199ab17d2a2ff4974fb0aad

**Comment by martinescardo** [comment]
I checked out the version immediately before that commit, and it type checks my whole development. It seems faster than the version of a few weeks ago I had, by the way.

**Comment by martinescardo** [comment]
(It is not faster actually. I measured and it is slower than the version I was using.)

**Comment by martinescardo** [comment]
Thanks. I've tested it.
