### ISSUE TITLE
performance regression

### ISSUE THREAD

**Issue by martinescardo** [agda/agda#3623]
With https://github.com/martinescardo/TypeTopology/blob/master/source/AllModulesIndex.lagda in a core i5 machine with 8gb of ram.

1. Agda 2.6.0-069e51e (7 March) uses 66% of ram (by monitoring with top) and takes 4m25s 

2. The older Agda 2.6.0-95f4a2 (16 January) uses 14% of ram and takes slightly less time, 4m11s

With a core i3 laptop with 4gb ram and 4gb of swap,  (2) consistently uses 30% of ram, and takes 6m6s. With (1), it exhausts ram and then swaps for ever.

**Comment by WolframKahl** [comment]
Please mention the RTS settings you are using.

On the 8G machine, you will probably want to use something like:
````
+RTS -H5G -M5G -A128M -RTS
````
On the 4G machine, you will want to kill your web browser before you start Agda, and use:
````
+RTS -H3G -M3G -A64M -RTS
````
In either case, you probably also want `-S` in there to watch garbage collections and active heap size.

Also have htop running to see how tight memory is on the machine overall.

Once Agda starts swapping, it is slowed down by an astronomical factor: Kill it.

**Comment by martinescardo** [comment]
After https://github.com/agda/agda/commit/d6b522c9264eec098ce5744d8ac822f43c2fda96, I tested both machines, and they again use 15% and 30% of ram as they used to. I am not aware of changing any RTS option for the previous behaviour.

**Comment by martinescardo** [comment]
I am getting two problems with this version of Agda:

* Some functions now fail termination checking.
* I get Set i is not less or equal than Set j.

Has the universe checking specification changed? My definition seems fine to me (and is accepted by Agda 2.6.1).

**Comment by gallais** [comment]
You may try to add `--auto-inline` or strategically deploy `{-# INLINE #-}`
pragmas following #4685.

**Comment by martinescardo** [comment]
I wrote this comment in the wrong issue by mistake. It was supposed to be in the issue about experimental-lossy-unification, following up from Tom de Jong's comments.

**Comment by martinescardo** [comment]
Sorry.
