### ISSUE TITLE
Holes remain as "?" in .lagda.md literate files

### ISSUE THREAD

**Issue by martinescardo** [agda/agda#3625]
Example:

```agda

F : Set → Set
F X = ?
```
After ctrl-c-ctrl-l, we see "?0 L Set" in the bottom buffer, but the question mark remains as `?` instead of becoming a hole `{ }`.

Moreover, emacs doesn't activate the emacs mode, and one has to do this manually.

Am I doing something wrong? Agda version 2.6.0-d6b522c

(I did do `agda-mode compile` just in case.)

**Comment by nad** [comment]
See #2837.
