### ISSUE TITLE
Safe Agda with REWRITE?

### ISSUE THREAD

**Issue by ice1000** [agda/agda#3626]
Is it possible to use safe Agda (say, no `TERMINATING`, not `primTrustMe`) with only one unsafe feature that is `--rewriting`?
I tried enabling `--rewriting` after `--safe` but Agda says rewriting is unsafe and reject my code.

**Comment by guillaumebrunerie** [comment]
No. The idea of `--safe` is that you should not be able to prove false while `--safe` is active. Of course some postulates/rewrite rules/other potentially unsafe things may actually be safe, but Agda has no way of checking it, so this is not allowed.

**Comment by ice1000** [comment]
Thanks!

**Comment by guillaumebrunerie** [comment]
The word "rewriting" seems rather innocuous for someone who doesn't know Agda (unlike "safe" which is pretty transparent), so someone who is not very familiar with Agda could easily be fooled believing that `--safe --rewriting` is a safe combination. So I think it's good that it's not allowed.

**Comment by ice1000** [comment]
What if I want this unsafe combination intentionally?

I'm trying to make a programming exercise problem on www.codewars.com, I want people to use `REWRITE` but not `postulate`, `trustMe`, etc.

**Comment by ice1000** [comment]
This should not be `working-as-intended`, I'm not making a bug report but asking a "How to".

**Comment by guillaumebrunerie** [comment]
Do you mean that you want people to be able to use whatever `REWRITE` they want, or only one specific rewrite rule that you chose yourself? It’s trivial to prove false (or anything) using `REWRITE`.

**Comment by gallais** [comment]
> This should not be working-as-intended, I'm not making a bug report but asking a "How to".

You can't. And it's on purpose: `--safe` means that Agda *guarantees* that there is
no way to abuse the powers you are given to prove false. It simply is not the case
when `--rewriting` is turned on.

**Comment by ice1000** [comment]
I get it, thanks for the explanation!
