### ISSUE TITLE
Performance with --no-universe-polymorphism

### ISSUE THREAD

**Issue by rrose1** [agda/agda#3631]
Agda without universe polymorphism has noticeable difficulty type-checking parametrized modules as a function of the number of parameters. The following example takes more than a few minutes to load:

```agda
{-# OPTIONS --no-universe-polymorphism #-}

module _ where

  module M
    (X : Set)
    (x0  x1  x2  x3  x4  x5  x6  x7  x8  x9  : X)
    (x10 x11 x12 x13 x14 x15 x16 x17 x18 x19 : X)
    (x20 x21 x22 x23 x24 x25 x26 x27 x28 x29 : X)
    where
    f : X
    f = x0

```
Of course, without `no-universe-polymorphism`, this example loads almost instantly.

**Comment by guillaumebrunerie** [comment]
Out of curiosity, do you have a reason for using `--no-universe-polymorphism`? My impression is that there is essentially no reason for why one may want to use it, so it’s not very surprising that it might be buggy. Maybe this option should be removed altogether.

**Comment by rrose1** [comment]
> there is essentially no reason for why one may want to use it

Is your question rhetorical then? In any case, I wouldn't protest if you decided no longer to support the option.

**Comment by andreasabel** [comment]
Fixed, thanks for reporting.

This was a performance regression introduce in the makeover of sorts, introducing `PiSort` (Agda 2.5.3 -> 2.5.4).  The fix is to remember `NoAbs` once we checked for absence of occurrence of variable 0 in the smart `piSort` constructor.
