### ISSUE TITLE
Compiling side-effective functions to the JavaScript backend produces wrong results

### ISSUE THREAD

**Issue by VictorTaelin** [agda/agda#3634]
If we try to compile the following program to JavaScript:

```agda
module Hello where

open import Data.Unit
open import Data.Bool
open import Agda.Builtin.IO
open import Agda.Builtin.Unit
open import Agda.Builtin.String

postulate
  putStrLn : String → IO ⊤

{-# FOREIGN GHC import qualified Data.Text.IO as Text #-}
{-# COMPILE GHC putStrLn = Text.putStrLn #-}
{-# COMPILE JS putStrLn = function(str) { console.log(str); } #-}

main : ⊤ → IO ⊤
main test =
  if true
    then putStrLn "Hi"
    else putStrLn "Ho"
```

It outputs both `"Hi"` and `"Ho"`, despite both being in different branches. Seems like this is an issue due to the lack of laziness evaluation on JavaScript. This can be avoided by simply not exporting side-effective functions, but I wonder if this is the expected behavio.

**Comment by UlfNorell** [comment]
This is the intended behaviour. `if_then_else_` is just a function, so under strict evaluation both branches will be evaluated. You can change the code to
```agda
case_of_ : {A B : Set} → A → (A → B) → B
case x of f = f x

main : ⊤ → IO ⊤
main test =
  case true of λ where
    true  → putStrLn "Hi"
    false → putStrLn "Ho"
```

**Comment by phile314** [comment]
As the JS backend uses eager evaluation, you need to manually delay evaluation in all FFI IO definitions. E.g. this is how the Agda Test Library defines ``putStr``:
```
postulate
  putStr     : String -> IO Unit

{-# COMPILE GHC putStr = Data.Text.IO.putStr #-}
{-# COMPILE JS putStr = function (x) { return function(cb) { process.stdout.write(x); cb(0); }; } #-}
```

Source: https://github.com/agda/agda/blob/master/test/Common/IO.agda
