### ISSUE TITLE
Can we bind two variables on the same argument in a `syntax` declaration?

### ISSUE THREAD

**Issue by VictorTaelin** [agda/agda#3635]
I'm trying to define the following syntax in Agda:

```agda
syntax init-from-to n m v (λ i x → b) = init v for i from n to m do: x := b
```

This would allow writing procedural-like loops like:

```agda
n45 : Nat
n45 =
  init 0
  for i from 0 to 10 do:
    result := result + 1
```

For some reason, though, it fails to compile with the following error:

```
Parse error
x<ERROR>
 → b) = init v for i from n to...
```

I can, though, remove the `x`:

```
syntax init-from-to n m v (λ i → b) = init v for i from n to m do: b
```

And it works fine, allowing me to write it as:

```agda
n45 : Nat
n45 =
  init 0
  for i from 0 to 10 do:
    λ result → result + 1
```

But the former version was a little bit nicer. Is there some way to bind two variables in the same argument, or is it just a missing feature? If so, how can I help implementing it?

**Comment by UlfNorell** [comment]
See #394.
