### ISSUE TITLE
Polarity: Size index check crashes due to wrong parameter number calculation

### ISSUE THREAD

**Issue by gallais** [agda/agda#3640]
I am getting (with Agda 2.5.4.2):

```haskell
src/full/Agda/TypeChecking/Polarity.hs:313:9-46:
  Irrefutable pattern failed for pattern (pars, Apply ix : ixs)
```

However I have a hard time building a minimal example. I have pushed the file
leading to this error [on this fork of the stdlib](https://github.com/gallais/agda-stdlib/blob/irrefutable-error/README/Trie.agda#L17-L24)

Edit: moving the open out of the parametrised modules solves the issue for me.

**Comment by andreasabel** [comment]
Shrunk to:
```agda
{-# OPTIONS --sized-types #-}

module _ where

open import Agda.Builtin.Size

module M (_ : Set) where
  data U : Size → Set where
    node : ∀ {i} → U (↑ i)

module L (A B : Set) where
  open M A
```

**Comment by andreasabel** [comment]
`checkSizeIndex` used the number of data type parameters of `L.U` (2) when checking the target of constructor `node`, but this is `M.U A ...` with just a single parameter.
Solution: look up correct number of parameters. 

Presumably, this never worked correctly, I tested back to 2.4.2.5.
