### ISSUE TITLE
Error message without position

### ISSUE THREAD

**Issue by nad** [agda/agda#3644]
The following code triggers an error message, but the error message does not include information about the position of the offending code:
```agda
{-# OPTIONS --safe --rewriting #-}

module A where
```
Error message:
```
Checking A ([...]/A.agda).
Cannot set OPTIONS pragma --rewriting with safe flag.
```

If this module is imported from another module, then the error message points to the other module:
```agda
module B where

open import A
```
Error message:
```
Checking B ([...]/B.agda).
 Checking A ([...]/A.agda).
[...]/B.agda:3,1-14
Cannot set OPTIONS pragma --rewriting with safe flag.
when scope checking the declaration
  open import A
```

**Comment by andreasabel** [comment]
This is fixed by adding a suitable `setCurrentRange` with the range of the pragma options.
However, the location is not very precise, highlighting all the options.
A better fix would have to add ranges to the `PragmaOptions` type; seems to be an overkill.
