### ISSUE TITLE
Internal error in Agda.TypeChecking.Reduce.Monad

### ISSUE THREAD

**Issue by nad** [agda/agda#3647]
The following code triggers an internal error:
```agda
postulate
  A : Set
  P : A → Set

Q : A → A → Set
Q _ x = P x

record R (P : A → Set) : Set where
  field f : (x : A) → P x → P x

open R ⦃ … ⦄

module M {x : A} where

  instance
    postulate
      r₁ r₂ : R (Q x)

postulate
  q₁ : (x : A) → P x

q₂ : (x : A) → P x
q₂ x = f _ (q₁ x)
```
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Reduce/Monad.hs:111
```
This is a regression, Agda 2.5.4.2.20190310 rejects the code.

**Comment by nad** [comment]
Bisection points towards a78d7f54e447cadf039da81b50ff40c81aa93909 ("[ refactor ] use IntMap for MetaStore").

**Comment by andreasabel** [comment]
Oh, I forgot a negation when refactoring a set expression.  Constructive logicians are not good at negation...

**Comment by nad** [comment]
@andreasabel, your refactoring is currently not on the release branch.

**Comment by asr** [comment]
I'll include the refactoring in the release branch.
