### ISSUE TITLE
Generalisable variables cannot be "given" in type signatures

### ISSUE THREAD

**Issue by nad** [agda/agda#3656]
The following code is accepted:
```agda
module Bug where

variable
  A : Set

postulate
  F : A
```
However, if I replace the final occurrence of `A` with a hole and try to give `A`, then I get the following error message:
```
Generalizable variable Bug.A is not supported here
when scope checking A
```

**Comment by guillaumebrunerie** [comment]
See issue #3341 and Ulf’s comments there.

**Comment by nad** [comment]
I searched for similar tickets, but only among the open ones…

**Comment by UlfNorell** [comment]
There's also https://agda.readthedocs.io/en/latest/language/generalization-of-declared-variables.html#interaction

**Comment by nad** [comment]
The variable `A` cannot be "given" in the hole below:
```agda
postulate
  F : Set → Set
  P : (A : Set) → F A → Set
  f : (A : Set) → F A

variable
  A : Set

postulate
  p : P {!A!} (f A)
```
If I understood the user manual correctly this should be possible.

**Comment by UlfNorell** [comment]
This doesn't seem to be a problem with give, but a problem with the context of solved interaction points. I filed #4228.
