### ISSUE TITLE
Generalisation leads to a type with "orphan" implicit arguments

### ISSUE THREAD

**Issue by nad** [agda/agda#3666]
Consider the following code:
```agda
data Unit : Set where
  unit : Unit

F : Unit → Set₁
F unit = Set

data D {u : Unit} (f : F u) : Set where

variable
  u : Unit
  f : F u
  d : D f

postulate
  P : D f → Set
  p : P d
```
The inferred type of `p` (neither normalised nor simplified):
```agda
{d.f.u : Unit} {d.f : F d.f.u} {d.u : Unit} {d.4 d.5 : F d.u} {d : D d.5} → P d
```
Note that `d.f.u`, `d.f` and `d.4` could have been omitted from this type signature. This looks like a bug to me, but I don't know enough about generalisation to be able to tell for sure.

**Comment by jespercockx** [comment]
I guess Agda somehow creates some metavariables that are left unsolved, and the implementation of generalization automatically turns these unsolved metavariables into additional arguments without checking whether they are actually mentioned. Looks like a bug to me.

**Comment by UlfNorell** [comment]
This looks like the same problem as #3667. Somehow `d` is given two extra generalizable arguments.
