### ISSUE TITLE
Yet another internal error related to generalisable variables

### ISSUE THREAD

**Issue by nad** [agda/agda#3673]
Code:
```agda
postulate
  A : Set

data Unit : Set where
  unit : Unit

F : Unit → Set
F unit = A

postulate
  P : {A : Set} → A → Set
  Q : ∀ {x} → F x → Set
  f : ∀ {x} {y : F x} (z : Q y) → P z

variable
  x : Unit
  y : F x

g : (z : Q y) → P z
g z with f z
... | p = p
```
Error message:
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/CheckInternal.hs:203
```

Is the internal checker only used for `with`? Perhaps it would be a good idea to run the test suite with the internal checker turned on.

**Comment by jespercockx** [comment]
See https://github.com/agda/agda/issues/3099 for the issue concerning the `--double-check` option (enabling the internal double-checker in more places). Last time I tried to run the test suite with `--double-check` enabled, I ran into lots of unsolved constraint dealing with sized types.
