### ISSUE TITLE
Agda gives unnecessarily imprecise error messages for code involving instance arguments

### ISSUE THREAD

**Issue by nad** [agda/agda#3676]
Consider the following code:
```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Sigma

record Monad (M : Set → Set) : Set₁ where
  field
    return : {A : Set} → A → M A
    _>>=_  : {A B : Set} → M A → (A → M B) → M B

open Monad ⦃ … ⦄

postulate
  F G : Set → Set

instance

  postulate
    F-monad : Monad F
    G-monad : Monad G

f : Σ Nat (λ _ → Nat) → F Nat
f p = do
  m , n ← return p
  return (m n)
```
Here `m n` should be `m + n`. Agda 2.5.4.2 points to `m` and gives a reasonable error message:
```
Nat should be a function type, but it isn't
when checking that n is a valid argument to a function of type Nat
```
However, Agda 2.6.0-4241ac2 points to `return` on the previous line and gives a less readable error message:
```
No instance of type Monad _M_16 was found in scope.
- F-monad was ruled out because
  [...]/Bug.agda:23,11-12
  Nat should be a function type, but it isn't
  when checking that n is a valid argument to a function of type Nat
- G-monad was ruled out because
  [...]/Bug.agda:22,11-19
  G (Σ Nat (λ _ → Nat)) !=< F _A_14 of type Set
  when checking that the expression return p has type F _A_14
when checking that p is a valid argument to a function of type
{M : Set → Set} ⦃ r : Monad M ⦄ {A : Set} → A → M A
```
Why doesn't Agda commit to the `F` monad and give the error message that Agda 2.5.4.2 gave?

This bug can make it awkward to develop code using instance arguments, because when the Emacs mode jumps to the supposed location of the error you can end up pretty far from the actual error, and the actual error message can be buried somewhere in a rather large piece of text. I think this regression should be fixed before the release of Agda 2.6.0.

**Comment by UlfNorell** [comment]
The change from 2.5.4.2 is because we check instance constraints later (due to #3435). When we do check I don't see anything suggesting that the `F` instance is better than the `G` instance. But I guess you have something in mind?

**Comment by nad** [comment]
The type signature uses `F`, not `G`. If one instance uses the right type family and no other instances do, then I don't think we should include the others in the error message.

I see that you moved this to 2.6.1. In my opinion the user experience is significantly worse now. I really think we should fix this before the release.

**Comment by UlfNorell** [comment]
Currently we don't track where constraints are coming from, or give higher weight to certain constraints when reporting instance errors. When instance search attempts the goal in question there are two (relevant) constraints:
```
  [22] _M_16 (Σ Nat (λ _ → Nat)) =< F _A_14 : Set
  _21 := λ { (m , n) → return (m n) } :? _A_14 → F Nat
```
Trying `G` fails the first constraint and trying `F` passes the first constraint and fails the second. I'm not sure what a principled solution looks like here. Some possibilities:
- Commit to the error that solved the most constraints (not sure we can count that meaningfully though).
- Try all constraints that are not postponed type checking problems first, and only print errors from candidates that passes those, if any. That would fix this particular case, but might not work for other cases.
- Track which constraints come from the outside (how?) and rule out candidates that fail those.

None of these feel like something we should try to implement so close to release, so unless you have a simpler solution it won't make it in 2.6.0.

What we do now is print all the errors, so if you know what monad you expected it's not too hard to find it in the list and read the nice error. This is better than before in many cases, where you would just get a "Failed to find instance" error with no further explanation.

**Comment by nad** [comment]
> What we do now is print all the errors, so if you know what monad you expected it's not too hard to find it in the list and read the nice error.

I think this might be rather harrowing to some users. My user experience earlier today:

* Code, code, code. Reload.
* There was a type error. The cursor jumped ∼40 lines.
* There is some long error message that mentions lots of instances. I rarely try to decipher such error messages.
* Replace code with holes (starting in the vicinity of the supposed position of the error) until Agda stops complaining.

After a while I realised that there was some useful information in the error message, but I suspect that it is fairly common to only read the first few lines of an error message. Furthermore, in my experience Agda often points to the right location when there is a type error, but not in this case.

> Some possibilities:

I introduced an error into my code and inspected the error message. It has the following structure:
```
[…]:899,20-21
No instance of type […] was found in scope.
- […] was ruled out because
  […]:921,13-942,28
  […]
- […] was ruled out because
  […]:921,13-942,28
  […]
- […] was ruled out because
  […]:921,13-942,28
  […]
- […] was ruled out because
  […]:921,13-942,28
  […]
- […] was ruled out because
  […]:940,38-39
  […]
when checking that […]
```
Note that one of the instance errors is way more specific than all the others. Perhaps one could list that one first. However, it is more annoying for me that the cursor jumps to the wrong location. I wonder why the range of the top-level error (899,20-21) does not match the ranges of any of the instance errors (921,13-942,28 or 940,38-39).

**Comment by UlfNorell** [comment]
> Note that one of the instance errors is way more specific than all the others. Perhaps one could list that one first.

How would you decide which error is more specific?

> I wonder why the range of the top-level error (899,20-21) does not match the ranges of any of the instance errors (921,13-942,28 or 940,38-39).

The location of the error is the location of the instance meta and the location for a candidate is the location of the specific error message.

**Comment by jespercockx** [comment]
> How would you decide which error is more specific?

AFAIU, currently the candidate check works like follows:

1. Check if the type of the instance matches the type of the goal
2. Instantiate the instance meta with the actual instance
3. Solve constraints

Maybe we could do another "solve constraints" pass between 1. and 2. and distinguish candidates based on whether they were already ruled out during this first pass. If at least one candidate made it to the second pass, we shouldn't print any candidates that already failed on the first pass.

**Comment by UlfNorell** [comment]
This wouldn't make a difference in this particular case. Both candidates fail the first pass.

**Comment by nad** [comment]
> How would you decide which error is more specific?

I was referring to the range. The list could be sorted based on the lengths of the ranges.
