### ISSUE TITLE
Unicode slow

### ISSUE THREAD

**Issue by rogerbosman** [agda/agda#3680]
Hi,

On my machine, whenever there are unicode symbols (math symbols, auto-generated subscripts etc.) on-screen, emacs grinds to a halt. For example, displaying the current hole goal takes 3+ seconds, where it is instant in other cases.

The issue is not just in the "editor window": even if there are only unicode symbols in the "result window" (where goals etc. are shown) the experience is slow.

We are currently doing an assignment in Agda with our entire class and I think multiple people are reporting the issue in our Slack, I can get more info from them if desired.

Platform: Windows
Agda --version: 2.5.3

**Comment by nad** [comment]
My guess would be that this has nothing to do with Agda. A quick search [suggests](https://emacs.stackexchange.com/questions/33510/unicode-txt-slowness) that it might be possible to fix the problem by running `M-x (setq inhibit-compacting-font-caches t) RET`. Eli Zaretskii, an Emacs maintainer, has [asked](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=27350#8) for this kind of problem to be reported as an Emacs bug.

**Comment by rogerbosman** [comment]
This I should have found out by myself, d'oh! This is my first experience with emacs, so I figured the problem lied here. But now it is solved.

Just as a sidenote, running it in the `M-x` window does not let me set the variable, `(setq*space*` gives `(setq [No match]`, but including it in the .emacs init script worked without problem!

**Comment by nad** [comment]
Sorry, that should be `M-:`, not `M-x`.
