### ISSUE TITLE
Make error about non-existent record field a warning?

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3684]
Due to restructuring of the standard library I am getting the following error:
```
The record type Algebra.Structures.IsSemigroup does not have the
fields isEquivalence, cong
when checking that the expression
record
{ isEquivalence = ≅isEquivalence i
; assoc = λ x y z → union-assoc x
; cong = union-cong
}
```
Being in the state of error, jump-to-definition does not work, which in my case would make it easy to find out the new field names or the new organizational structure.

In principle, this error could be turned into a soft error (serious warning) which markes the code in the non-existing fields as dead (we have similar mechanisms e.g. for non-existing imports).  It would then give a lot of yellow, but hopefully a somewhat functioning state of the interaction, allowing me to jump to definitions.

Also, the actually existing fields could be easily listed in this case to give me a hint what is going on.

**Comment by MatthewDaggitt** [comment]
Seconded. Jump-to not working when in an error state is very irritating. Preserving the jump-to functionality where possible would be great! I remember thinking there are other places where this might (albeit in my limited experience) be possible as well. Though I can't remember them at the moment, I'll add them when I come across them again.

**Comment by nad** [comment]
It would also be possible to make jump-to-definition work better when an error is encountered.

**Comment by gallais** [comment]
Slight head-scratcher: when a record pattern on the LHS mentions a non-existing
field, the scope checker has already assumed that whatever it bound is now available
on the RHS. With my naïve patch, this leads to a panic in `test/Fail/RecordPattern2.agda`:

```agda
postulate A : Set

record R : Set where
  field f : A

record S : Set where
  field g : A

test : R → A
test record{g = a} = a
```

**Comment by andreasabel** [comment]
Ok, I did not think about the LHS at all.  It would be ok if the whole clause would be skipped if there was a type error in the record pattern.

**Comment by andreasabel** [comment]
> Also, the actually existing fields could be easily listed in this case to give me a hint what is going on.

I implemented this for record expressions now.

**Comment by andreasabel** [comment]
It seems that for copatterns the error message is already helpful, e.g.
```agda
record R : Set₁ where
  field
    foo {boo} moo : Set

test : (A : Set) → R
test A .moo = A
test A .bar = A
test A .far = A
```
```
Not in scope:
  moo at ...
    (did you mean
       'R.boo' or
       'R.foo' or
       'R.moo'?)
when scope checking moo
```
A bit surprisingly, record field tags are not looked at during scope checking, in contrast to projection patterns.  Record field tags are just strings (concrete names).

**Comment by andreasabel** [comment]
For copatterns, the improvement of the error seems harder to achieve, since we are handling the resolution of projection patterns in the scope checker already (while record field tags are checked later, during type checking).
```agda
record R : Set₁ where
  field
    foo {boo} moo : Set
open R

test : (A : Set) → R
test A .moo = A
test A .bar = A
test A .far = A
```
```
Not in scope:
  bar at ...
when scope checking bar
```

**Comment by andreasabel** [comment]
PR #4545 gathers the patches on this issue.  The feature is now implemented for record expressions and record updates.
For copatterns, we could have a more general mechanism in the scope checker that marks a clause as dead if the projection is not in scope.
Invalid record patterns leading to ill-formed clauses could be handled in the LHS checker, skipping such clauses as dead (also more general mechanism).

**Comment by andreasabel** [comment]
Fixed on day 16 of my voluntary COVID-19 quarantine.
