### ISSUE TITLE
Internal error at TypeChecking/Substitute.hs:109

### ISSUE THREAD

**Issue by andrejtokarcik** [agda/agda#3689]
```agda
data _≡_ {A : Set} (a : A) : A → Set where
  refl : a ≡ a

record Σ (A : Set) (B : A → Set) : Set where
  constructor _,_
  field
    fst : A
    snd : B fst
open Σ

_×_ : Set → Set → Set
A × B = Σ A λ _ → B

postulate τ : Set

record R : Set where
  field
    π : τ
open R

T : Set
T = Σ R λ r → (π r ≡ π r) × (π r ≡ π r)

fun : T → Set
fun (fst₁ , x) = {! !}
```

When I attempt to case-split the `x` variable in the definition of `fun` on the last line (e.g., by pressing `C-c C-c` in the Emacs mode) the following message is printed:
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Substitute.hs:109
```

The issue was discovered with a custom build of master, commit 709bda3. I just verified it still fails with the most recent commit d0afa8f. I have not tested the code with any other versions of Agda.

#3661 might be related.

**Comment by andrejtokarcik** [comment]
FWIW, it's possible to manually replace the offending `x` variable by a pattern involving the `_,_` constructor as expected without any problems.

**Comment by andreasabel** [comment]
This works fine with 2.5.4.2, thus, is a new regression that should be fixed before the release of 2.6.0.
```
-- conApp: constructor Issue3689.Σ._,_ with fields
-- Issue3689.Σ.fst
-- Issue3689.Σ.snd
-- and args
-- @1
-- @0
-- projected by Issue3689.R.π
```
Likely a bug introduced by new feature #3526 (PR #3533).

**Comment by andreasabel** [comment]
This is the MWE:
```agda
open import Agda.Builtin.Equality
open import Agda.Builtin.Sigma

record R (A : Set) : Set where
  field π : A

fun : {A : Set} (xyz : Σ (R A) λ r → Σ (R.π r ≡ R.π r) λ _ → R.π r ≡ R.π r) → Set
fun (x , y) = {!y !} -- C-c C-c
```

**Comment by andreasabel** [comment]
Problem was a missing `inContextOfT` at call to `isEmptyType`: https://github.com/agda/agda/blob/69ddcc096a55b111234ccb941b8e8002064c96b9/src/full/Agda/TypeChecking/Coverage.hs#L1272
Inserting it fixes this issue.
Thanks for reporting @andrejtokarcik
