### ISSUE TITLE
Generalise ignores renaming when opening modules

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda#3700]
Variables are incorrectly generalised over even when the name is already available via renaming. The following code raises the error `Ambiguous name A.` at `test`:
```agda
open import Relation.Binary using (Setoid)

variable A : Set

module _ {c ℓ} (S : Setoid c ℓ) where
  open Setoid S renaming (Carrier to A)

  test : A
  test = ?
```
Came across this while using `variable` for the first time in anger in the standard library. It's preventing me from using it in several modules.

**Comment by JacquesCarette** [comment]
Shouldn't the `rename` throw an error? This is indeed an ambiguous name, as it is both a record projector and a variable.  What are you expecting to happen here?

**Comment by MatthewDaggitt** [comment]
> Shouldn't the rename throw an error? This is indeed an ambiguous name, as it is both a record projector and a variable. What are you expecting to happen here?

I was expecting no generalisation to occur and for `A` to refer only to the renamed A when opening the setoid. Variables should only be generalised over when they are not otherwise defined in the scope right? But by opening the setoid and renaming we've now got A in scope so it shouldn't be generalised.

What's the difference between the example above and:
```agda
variable A : Set

module _ {A : Set a} where
  test : A
  test = ?
```
Would you expect the module parameter `{A : Set a}` to throw an error?

**Comment by UlfNorell** [comment]
It's the same behaviour as
```agda
open import Relation.Binary using (Setoid)

postulate A : Set

module _ {c ℓ} (S : Setoid c ℓ) where
  open Setoid S renaming (Carrier to A)

  test : A
  test = ?
```
Generalisable variables behave as top-level definitions when it comes to scoping rules. There's some discussion in #359.

**Comment by MatthewDaggitt** [comment]
Why is this behaviour desirable? I'd argue that this is similar to the discussion in #3351. 

I guess my point is that the reasoning behind the shadowing rules are unclear.
```agda
variable 
  a : Level
  A : Set

module Example1 (A : Set a) where

  test : A   -- No error
  test = ?

module Example2 {c ℓ} (S : Setoid c ℓ) where
  open Setoid S renaming (Carrier to A)

  test : A   -- Error
  test = ?
``` 
In the above two snippets `A` is introduced in two different ways, neither as a top-level definition. In the first snippet the A does shadow the top-level variable definition and in the second snippet it doesn't. I don't understand why there should be a difference in the two cases.

**Comment by MatthewDaggitt** [comment]
Just come across this again. Sorry, not sure how to phrase this without coming across as too obnoxious, but are you sure this behaviour is the right one? My understanding of generalised variables is that they should only activate when the name isn't already in scope. Hence hence why Example1 goes through as `A` is not generalised as it is already available via a module parameter. In Example2 it seems like once again `A` is in scope and therefore it shouldn't be generalised over.

Maybe I'm misunderstanding the point of variables or perhaps the way in which opening modules brings names into scope... Maybe my question is why do names introduced via opened modules clash with top-level definitions when names introduced via module parameters do not?

**Comment by UlfNorell** [comment]
Are you arguing that
```agda
module M where
  postulate A : Set
postulate A : Set
open M
postulate a : A
```
should type check and resolve to `a : M.A`? This seems like a terrible idea.

**Comment by MatthewDaggitt** [comment]
No I'm not, I agree that your example shouldn't type check. I'm proposing that:
```agda
module M where
  postulate A : Set
variable A : Set
open M
postulate a : A
```
should type check and resolve to `a : M.A`, i.e. that names introduced via `variable` should(?) behave differently from those introduced via `postulate` (or indeed any other method).

Hmm, okay thanks your example helped me understand why they don't work as above. In my head `variable`s were treated with more shadowing then top-level variables. I still think the behaviour above is desirable, but I understand why it's not included. Thanks.
