### ISSUE TITLE
Allow function types with explicit parameters as instance arguments

### ISSUE THREAD

**Issue by dylanede** [agda/agda#3702]
Currently, instance arguments must be of a record or data type. This precludes some uses of instance resolution as an automatic proof search. As a motivating example, consider negation of a proposition (taken from agda/cubical):
```agda
¬_ : Set ℓ → Set ℓ
¬ A = A → ⊥
```
Instances (and instance arguments) of `¬A` (for any particular `A`) are currently not allowed since it is a function type. This forces proof arguments of this form to be given explicitly, which in practice can be quite cumbersome, especially for functions such as (otherwise) binary operators.

P.S. I am not aware of the restrictions in the internals of the current instance resolution algorithm that force function types to be disallowed at the moment.

**Comment by andreasabel** [comment]
Your example is too vague.  In particular, cannot you wrap your function types into some record type to facilitate instance search?
