### ISSUE TITLE
nonterminating function between split datatype causes typechecker to freeze

### ISSUE THREAD

**Issue by ghost** [agda/agda#3703]
It seems like, whenever a nonterminating recursive function is used inside a datatype, the typechecker will happily enter it (and loop/freeze), but only if the datatype signature comes before the function.

```Agda
data X : Set
A = A
data X where x : A
```

**Comment by andreasabel** [comment]
Right, this is because the termination checker only runs _after_ the mutual block (consisting of X and A here).  See #1270.

**Comment by ghost** [comment]
@andreasabel, okay, so, since this is a duplicate, should I close it? Feel free to reopen it if you think it’s different enough for some reason I can’t see.

Either way, since it seems like the code I shared is much simpler to reproduce the issue, do you reckon it’d be of value to share it over at the issue report you shared?
