### ISSUE TITLE
Error while installing on windows 10

### ISSUE THREAD

**Issue by uhotspot4** [agda/agda#3708]
Getting following error while installing Agda on windows 10:

Resolving dependencies...
Starting     Agda-2.6.1
Failed to install Agda-2.6.1
Build log ( C:\Users\firouz\AppData\Roaming\cabal\logs\ghc-8.6.3\Agda-2.6.1-7JA3EIOSoGFBs6WdrrRl9u.log ):
cabal: Entering directory '.'
[1 of 1] Compiling Main             ( dist\setup\setup.hs, dist\setup\Main.o )
Linking .\dist\setup\setup.exe ...
Configuring Agda-2.6.1...
Error:
    Dependency on unbuildable (i.e. 'buildable: False') library from Agda

cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
Agda-2.6.1-7JA3EIOSoGFBs6WdrrRl9u failed during the configure step. The
exception was:
ExitFailure 1

**Comment by asr** [comment]
Agda 2.6.1 cannot be installed on Windows using GHC 8.6.3 (see #3657).

**Comment by uhotspot4** [comment]
Thanks and so does Agda 2.5 work with GHC 8.6.3 on windows?

**Comment by asr** [comment]
No. Agda 2.5.* does not work with GHC 8.6.*.

**Comment by uhotspot4** [comment]
Thanks a lot.
