### ISSUE TITLE
Do we have to worry about running out of issue numbers?

### ISSUE THREAD

**Issue by asr** [agda/agda#3709]

**Comment by asr** [comment]
Oops!

**Comment by UlfNorell** [comment]
Yes, we wouldn't want to run out of issue numbers... 🙄

**Comment by jespercockx** [comment]
Since when are we being economical with issue numbers? Are we at risk of running out?  Maybe GHC has used up all the issue numbers (they're at #16614!) and now there's none left for the new generation?

**Comment by UlfNorell** [comment]
Answer: no.

**Comment by UlfNorell** [comment]
There, issue reused!

**Comment by andreasabel** [comment]
Issue numbers are 16bit by definition, the GHC folks have already exhausted 25%.

**Comment by andreasabel** [comment]
Why does this issue have a milestone?

**Comment by jespercockx** [comment]
Are we running out of milestones as well?

**Comment by UlfNorell** [comment]
> @andreasabel self-assigned this 20 minutes ago

Did you just take credit for resolving this issue?? I'm pretty sure *I* answered the question in the title. Also what's with the `already-fixed`? Obviously there was some confusion about issue numbers that I (heroically) cleared up.
