### ISSUE TITLE
Rename inc/ouc everywhere

### ISSUE THREAD

**Issue by mortberg** [agda/agda#3714]
The cubical primitive `primSubOut` is currently called `ouc` in many of the builtin files and the reference manual. This was chosen to match its inverse primitive `inc`. However, this has caused quite a bit of confusion and I've lost track by how many times someone asked me what `ouc` stands for (maybe "ouclusion"?). Because of this we renamed them to `inS` and `outS` in the agda/cubical library. I would suggest that we make the naming consistent and use `inS`/`outS` everywhere unless someone has a better suggestion.

**Comment by jespercockx** [comment]
@mortberg do you have time to work on this before the release later this month? If not, please update the milestone to 2.6.2.

**Comment by nad** [comment]
@mortberg, do you still want to make this change?

**Comment by mortberg** [comment]
It would be good to do it, but I don't have the time to do it now. It should be very easy to fix though, just rename `inc` to `inS` and `ouc` to `outS`
