### ISSUE TITLE
Replace `__IMPOSSIBLE__` with throw + HasCallStack

### ISSUE THREAD

**Issue by rwe** [agda/agda#3718]
It would be useful to replace the [`__IMPOSSIBLE__` preprocessor macro](https://github.com/agda/agda/blob/47eecb71752536effba9f26b337a66f7b2c722a9/src/full/undefined.h#L1) by decorating [`throwImpossible`](https://github.com/agda/agda/blob/47eecb71752536effba9f26b337a66f7b2c722a9/src/full/Agda/Utils/Impossible.hs#L47) with [`GHC.Stack.HasCallStack`](https://hackage.haskell.org/package/base-4.9.0.0/docs/GHC-Stack.html) (introduced in `base-4.9.0.0`) for locating the error.

By doing that, in conjunction with #1875, the C preprocessor can be dropped from (nearly) all the Haskell source files. This simplifies use of source analysis, refactoring, and formatting tools.

(Which was/is a speed-bump for #3512; refactoring tools don't tend to work well in the presence of a preprocessor).

For example, in `src/full/Agda/Utils/Impossible.hs`:
```diff
+import GHC.Stack (CallStack, HasCallStack, callStack, freezeCallStack, prettyCallStack)
 
 data Impossible
-  = Impossible  String Integer
+  = Impossible CallStack
```
```diff
-throwImpossible :: Impossible -> a
-throwImpossible = throw
+throwImpossible :: HasCallStack => a
+throwImpossible = throw (Impossible (freezeCallStack callStack))
```

And the other random files:
```diff
-#include "undefined.h"
 import Agda.Utils.Impossible
```
```diff
 -- …
-  when (null cs) __IMPOSSIBLE__
+  when (null cs) throwImpossible
```

### Caveat: Depends on #3719
This suggestion cannot be implemented before dropping support for `ghc@7.10`, which uses `base-4.8.*`. I have implemented this `HasCallstack` change locally already—not well-tested—but decided to shelve the work when I realized the GHC restriction. So this issue is to serve as a reference point for whether/how/when to continue that work.

**Comment by jespercockx** [comment]
Yes please, I'm all in favour of removing dependencies on archaic tools in favour of build-in features of Haskell.

**Comment by gallais** [comment]
What would the new error messages look like?

**Comment by rwe** [comment]
@gallais — The error messages are identical, though it's possible to add more information (like the rest of the call stack, if available). The original error messages use the current line and filename via `__LINE__`, `__FILE__`. Here, they're pulled from the [`CallStack`](https://hackage.haskell.org/package/base-4.9.0.0/docs/src/GHC.Stack.Types.html#CallStack)'s  [`SrcLoc`](https://hackage.haskell.org/package/base-4.9.0.0/docs/src/GHC.Stack.Types.html#SrcLoc)'s `srcLocFile` and `srcLocStartLine` fields.

**Comment by nad** [comment]
Perhaps `throwImpossible` could be shortened to `impossible`.
