### ISSUE TITLE
Remove support for GHC 7.10 (aka base <4.9)

### ISSUE THREAD

**Issue by rwe** [agda/agda#3719]
Agda currently [maintains support for GHC 7.10](https://github.com/agda/agda/blob/47eecb71752536effba9f26b337a66f7b2c722a9/Agda.cabal#L36), which was released ~3.5 years ago. That version [corresponds with `base-4.8.*`](https://wiki.haskell.org/Base_package). It is the pre-GHC-8 version still supported.

A lot has changed in Haskell-world in that time, and continues to change, which makes supporting a range of versions difficult and limits what tooling can be used within the Agda codebase.

For example, new features of the GHC runtime and base library could facilitate removing the C preprocessor from most of the source files, which should improve compilation times, and will simplify use of source analysis, refactoring, and formatting tools. See #3718 and #1875.

What is the GHC version support policy for Agda?

Similar older issues for previously-dropped versions:
  * https://github.com/agda/agda/issues/2692 (7.8.4)
  * https://github.com/agda/agda/issues/1577 (7.4.2)
  * https://github.com/agda/agda/issues/1392 (7.0.4)
  * https://github.com/agda/agda/issues/1393 (7.0.x)

**Comment by jespercockx** [comment]
In the past we have used the following policies:

- support at least the latest 3 releases of GHC
- support the version of GHC that's in the repositories of the latest LTS release of Ubuntu
- don't remove support for a version of GHC unless there's a compelling reason to do so

In this case, all three checkboxes are ticked so I think it would be fine to drop support for 7.10.

**Comment by gallais** [comment]
> support the version of GHC that's in the repositories of the latest LTS release of Ubuntu

I'd speak out in favour of debian stable too; in this case it's not an issue either
(the current ghc is 8.0+).

**Comment by andreasabel** [comment]
We have in the past dropped support for older ghc versions if it was a hassle to maintain compatibility.  It was very much so for ghc-7.8, but ghc-7.10 wasn't so much of a problem yet.  However, if there is a strong incentive, like in this case getting mostly rid of CPP, we do not have to hold on to ghc 7.10.

**Comment by asr** [comment]
I have changed my opinion about supporting older GHC versions with the years. Nowadays, I want to keep the latest version of Agda available for *final* users as much as *necessary* and *possible*. To have information to make a decision, I'll ask in the mailing list about removing support for GHC 7.10.3.

> For example, new features of the GHC runtime and base library could facilitate removing the C preprocessor from most of the source files, which should improve compilation times

Could you share some figures about it? That is, how much is the reduction on compilation times?

**Comment by asr** [comment]
It seems we are going to release a bug-fix version (i.e. 2.6.0.1). Since 2.6.0 supports GHC 7.10.3, the bug-fix version must also support this version of GHC if possible.

**Comment by rwe** [comment]
> Could you share some figures about it? That is, how much is the reduction on compilation times?

Unfortunately I don't know without actually implementing it—hence the hedge with "should".

There are some references [here](http://blog.haskell-exists.com/yuras/posts/stop-abusing-cpp-in-haskell.html) and [here](https://stackoverflow.com/questions/26785036/why-the-presence-absence-of-the-hscolour-binary-forces-to-recompile-the-quickche) about modifications to `cabal_macros.hs` causing unnecessary recompilation, but as for straight compilation performance, I'm making a guess based on the fact that it strictly removes a step from the compiler, and so supposedly reduces intermediate output and possibly some pessimistic cache decisions.

My bigger motivation here is related to be able to do automated refactoring that is made difficult in the presence C's lexical preprocessor.

**Comment by UlfNorell** [comment]
Just making it possible to have single quotes and impossibles on the same line would make it worth it.

**Comment by nad** [comment]
> My bigger motivation here is related to be able to do automated refactoring that is made difficult in the presence C's lexical preprocessor.

I found 28 occurrences of `#if MIN_VERSION_base(4,11,0)` in the code base, and base-4.11 corresponds to GHC 8.4, so dropping support for 7.10 will not mean that we can stop using CPP.

If your refactoring tools work with one module at a time, then it might be useful to push some of these CPP directives into a project-specific prelude file (#1875).

**Comment by rwe** [comment]
@nad — Yep, I agree. #1875 is referenced in the description and in #3718 which motivated this issue and removes the most common use of the preprocessor otherwise.

I think the project-specific Prelude file (mainly just to deconflict `(<>)`) is a good next step. Or if there's a way to have Cabal to choose one source module versus another, that might avoid the preprocessor also for other currently-preprocessed features like ICU support.

**Comment by andreasabel** [comment]
There is one argument for keeping maximal compatibility that has not been voiced here yet:
The ability to run bisection to discover the cause of regressions.  

Say a regression was introduced between version A and version B, we need a GHC version that can compile both A and B.  In practice, this should not be a problem, as we can narrow down the boundaries to two subsequent releases of Agda without too much effort.  (Although one an old Agda binary has been deleted, it might take effort to get it back...)
