### ISSUE TITLE
Internal error with Prop and inductive-inductive type

### ISSUE THREAD

**Issue by AndrasKovacs** [agda/agda#3724]
The following snippet fails with `An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Forcing.hs:232` on Agda commit `c240843` (but on 2.6.0 as well).

```agda
data _≡_ {α}{A : Set α}(a : A) : A → Prop where
  refl : a ≡ a

data _≃_ {α}{A : Set α}(a : A) : ∀ {B} → B → Prop where
  refl̃ : a ≃ a

data ⊥ : Set where

data Con  : Set
data Con~ : Con → Con → Prop
data Ty   : Con → Set
data Ty~  : ∀ {Γ₀ Γ₁} → Con~ Γ₀ Γ₁ → Ty Γ₀ → Ty Γ₁ → Prop

data Con where
data Con~ where

data Ty where
  U  : ∀ {Γ} → Ty Γ

data Ty~ where
  U~  : ∀ {Γ₀ Γ₁ Γ₀₁} → Ty~ {Γ₀}{Γ₁} Γ₀₁ U U

Conᴹ  : Con → Set
Con~ᴹ : ∀ {Γ₀ Γ₁} → Con~ Γ₀ Γ₁ → Conᴹ Γ₀ ≡ Conᴹ Γ₁
Tyᴹ   : ∀ {Γ} → Ty Γ → Conᴹ Γ → Set
Ty~ᴹ  : ∀ {Γ₀ Γ₁ Γ₀₁ A₀ A₁} → Ty~ {Γ₀}{Γ₁} Γ₀₁ A₀ A₁ → Tyᴹ A₀ ≃ Tyᴹ A₁
Conᴹ  ()
Con~ᴹ ()

Tyᴹ U γ = ⊥

-- offending line: if I comment this out, the internal error goes away
-- If I use Set instead of Prop everywhere, the error also goes away
Ty~ᴹ U~ = ?
```

**Comment by andreasabel** [comment]
Please keep milestone 2.6.0.1 clear of issues that concern the new features of Agda 2.6.0.

**Comment by nad** [comment]
Why? I think it makes sense to fix serious bugs (like internal errors) before 2.6.0.1 is released.

**Comment by nad** [comment]
I saw that you added some motivation in another ticket (https://github.com/agda/agda/issues/3705#issuecomment-490872892).

**Comment by SimonBoulier** [comment]
We have the same bug. A minified version by Szumi Xie:
```
{-# OPTIONS --prop #-}

data ⊤ : Prop where
  tt : ⊤

data A : ⊤ → Set where
  a : (x : ⊤) → A x

f : A tt → ⊤
f (a x) = ?
```
With version 83a48d2 (yesterday) the error location is on line 230.

**Comment by andreasabel** [comment]
With the latest development version there is a workaround: disable the forcing optimization:
```agda
{-# OPTIONS --no-forcing #-}
```

**Comment by SimonBoulier** [comment]
Thanks!

**Comment by jespercockx** [comment]
Fixed by the new forcing translation.
