### ISSUE TITLE
Feature request: open import Module as _

### ISSUE THREAD

**Issue by strake** [agda/agda#3727]
Now `open import Module as Name` means the following:
```
import Module as Name
open Name
```

I sometimes want to bring into scope the contents of a module, but not the module itself.
I propose a minor extension of the syntax: `open import Module as _`, which does just so.

I am willing to implement, but would like to know whether the keepers of Agda think it a good (or at least minimally acceptable) idea first.

**Comment by nad** [comment]
Can your proposed syntax be explained in terms of currently existing syntax?

**Comment by jespercockx** [comment]
I guess `open import A as _` should mean the same thing as `open import A as SomeUnusedName`, which in turn means the same as
```
import A as SomeUnusedName
open SomeUnusedName
```

**Comment by strake** [comment]
@nad Yes, it's as @jespercockx said, with a guaranty `SomeUnusedName` is impossible to write (i.e. won't clash with any name anywhere in the source code).

**Comment by gallais** [comment]
What should happen in the following scenario:

* both `M` and `N` define a function named `f`
* We `open import M as _` and `open import N as M`
* We write `M.f`.

Following your spec, I assume that `M.f` should mean `N.f`. So `open import M as _`
would not only not declare `M`, it would also have to remember that `M` can't possibly
be referred to.

Additionally, I assume `import M as _` is just dead code?

**Comment by strake** [comment]
Sorry, forgot about this! @gallais Yes, both your conclusions are correct. However, that one can not refer to the original `M` already follows from the definition/desugarization of the syntax.

Edit: Ought we to warn on `import M as _`?

**Comment by rwe** [comment]
@gallais in your example, that sounds intuitive to me. Though the characterization of the logic here:
> `open import M as _` would not only not declare `M`, it would also have to remember that `M` can't possibly be referred to.

makes it seem like special exclusion effort, when it seems it should be more of a natural outcome of how names would be brought into scope.

This suggestion seems to have two parts, if I'm interpreting correctly:
  1. To *not* introduce the original module name into global scope when doing an aliased import. I think this is a good suggestion; the current behaviour is surprising. When I say, `import X as Y`, I expect the name `X` to be irrelevant thereafter.
  2. To support `_` as a black-hole module name, which I think may already happen? At least for declaring submodule names.

Is there a spec of Agda's import/scoping/desugaring rules somewhere?
  * `import X as Y`: introduces the name `Y` into global scope. The contents of that name refer to the module `X`.
  * `import X`: identical to `import X as X`
  * `open import X as Y`: Same as `import X as Y; open Y` (brings the name `Y` into global scope and all of the symbols directly in `Y.*` into global scope)
  * `open import X`: same as `open import X as X`

**Comment by nad** [comment]
> Additionally, I assume `import M as _` is just dead code?

i suppose it might bring instances into scope.

**Comment by strake** [comment]
@nad Yes, good point — as specified (and intended), yes, it would do so.

**Comment by jespercockx** [comment]
@strake I think we all agree that this would be a sensible feature to have (and also have the change to the current semantic of `open import ... as ...` that @erydo suggests). If you are still planning to work on this, let me know something so I can update the milestone.

**Comment by nad** [comment]
See also #4166.

**Comment by strake** [comment]
@jespercockx Yes, i will work on this now as it seems we have a consensus it's a good idea ☺

**Comment by sattlerc** [comment]
Relatedly, it would be nice if instead of
```
open module Dummy params = M args
```
one could write
```
open module _ params = M args
```
This should have the same meaning as
```
module _ where
  private
    module Dummy params = M args
  open Dummy public
```
where Dummy is a fresh module name.

I wonder if the changes introduced by the referenced pull request could be adapted to this situation.

EDIT: I guess a simpler translation is
```
module _ params where
  open Dummy args public
```
However, `open module Dummy params = M args` is a valid let-declaration (as would the nameless variant be), and the above is not.

**Comment by asr** [comment]
Missing entry in the CHANGELOG.

**Comment by asr** [comment]
I added the `documented-in-changelog` label.
