### ISSUE TITLE
Internal error resulting from unused implicit argument

### ISSUE THREAD

**Issue by mcoblenz** [agda/agda#3730]
Typechecking the attached test.agda file, which imports heapPropertiesReduced.agda, gives the error below:

```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Serialise/Instances/Internal.hs:148
```

The error occurs if and only if `o` is included as an (unused) implicit argument in `locationsInΔAreCompatibleWithFieldTypes`, which is declared at the end of heapPropertiesReduced.agda. Note that the latter file typechecks successfully; the internal error occurs only when typechecking a file that imports it.

This bug occurs in Agda 2.6.0.

**Comment by mcoblenz** [comment]
[bug.zip](https://github.com/agda/agda/files/3127869/bug.zip)

**Comment by andreasabel** [comment]
Thanks for reporting, @mcoblenz !
I am getting this error, unfortunately:
```
Checking test 
 Checking HeapPropertiesReduced 
Failed to find source of module Silica in any of the following
locations:...
when scope checking the declaration
  open import Silica
```

Could you please shrink the problem to a single file not relying on imports except for `Agda.Builtin.*`?  
This will greatly increase the chances of someone diving into this bug hunt.

**Comment by mcoblenz** [comment]
Sorry about that. I suspect that the problem requires imports to reproduce, since the error occurs only in a file that imports the file in question, not in the file itself. However, I'll attach a fixed package so you can reproduce this.
[bug.zip](https://github.com/agda/agda/files/3128699/bug.zip)

**Comment by andreasabel** [comment]
I can confirm this issue.
```
$ agda test.agda
Checking test (...).
 Checking HeapPropertiesReduced ().
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Serialise/Instances/Internal.hs:148
```
This bug already exists in 2.5.4.1.

It would be helpful to have a MWE, since this behavior is likely to be reproducible with a shorter test case.  Could you help shrinking this example?
- Remove definitions that are inessential to the bug.
- Inline imported modules as much as possible.

**Comment by UlfNorell** [comment]
The problem is `--allow-unsolved-metas` in the presence of sort metas that are allowed to be instantiated to `Setω`. These have a `dummyType` as their target, which the serialization doesn't like. Shorter test case:
```agda
{-# OPTIONS --allow-unsolved-metas #-}
module A where
X : _
X = _
```
```agda
module B where
import A
```

**Comment by jespercockx** [comment]
See also https://github.com/agda/agda/issues/1432
