### ISSUE TITLE
GHC backend thinks that a constructor called 'main' is the main program

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3731]
When testing my new BNFC Agda backend I was mystified by compiler errors like
```
The type of main should be Agda.Builtin.IO.IO A, for some A. The given type is ...
```
or
```
No binding for builtin thing IO, use {-# BUILTIN IO name #-} to bind it to 'name'
```
I found out that my Main program (with a proper main function) was importing some other module which declared a constructor `main`, like in
```agda
data D : Set where
  main : D
```
The GHC backend mistakes this as the `main` program, even though it is only an imported module, not the main module we are compiling, and even though a constructor usually cannot serve as main program. :D

**Comment by asr** [comment]
Since that I'm going to create `release-2.0.6.1` from the current `master`, I changed the milestone to `2.6.0.1.`
