### ISSUE TITLE
WARNING_ON_USAGE is not raised for constructors

### ISSUE THREAD

**Issue by gallais** [agda/agda#3734]
re agda/agda-stdlib#747

```agda
data A : Set where
  s : A → A
  a : A

b : A
b = a

{-# WARNING_ON_USAGE a "This should show up" #-}
{-# WARNING_ON_USAGE b "This does show up" #-}

_ : A
_ = a

_ : A → A
_ = λ where
  a → a
  x → x

_ : A
_ = s b

pattern c = s a

{-# WARNING_ON_USAGE c "This should show up too" #-}

_ : A
_ = c

_ : A → A
_ = λ { c → a; x → x }
```

**Comment by andreasabel** [comment]
The current solution is to trigger the warning on defined names in the scope checker. For constructors and fields, we would have to do this in the type checker, after disambiguation happened.

The fix for pattern synonyms should wait for the overhaul of pattern synonyms in PR #4680.

**Comment by andreasabel** [comment]
TODO: improve an error as discussed in https://github.com/agda/agda/commit/99494ae7599d15907450d62f1e5a198c67311555#commitcomment-40175432.

**Comment by jespercockx** [comment]
I don't see why this requires typed pattern synonyms to fix; can't we just throw the warning during typechecking/disambiguation?
