### ISSUE TITLE
Incorrect context when generalisable variable is used

### ISSUE THREAD

**Issue by nad** [agda/agda#3735]
Consider the following code:
```agda
open import Agda.Primitive

variable
  X : Level

postulate
  works : Set X → {X : Set} → X
  fails : Set X → {X : Set} → {!X!}
```
If I try to give `X`, then I get the following error:
```
Level should be a sort, but it isn't
when checking that the expression X has type _11
```
When I print the goal type and the context, then Agda claims that `X : Set` is not in scope:
```
Goal: _11
————————————————————————————————————————————————————————————
X = X₁ : Set  (not in scope)
X      : Level
```

**Comment by andreasabel** [comment]
Please keep milestone 2.6.0.1 clear of issues that concern the new features of Agda 2.6.0.

**Comment by nad** [comment]
Here is a similar example. Agda incorrectly rejects the following code:
```agda
module _ where

open import Agda.Primitive

variable
  a : Level

module _ (A : Set a) (a : A) where

  x : A
  x = a
```
Error message:
```
Level !=< A
when checking that the expression a₁ has type A
```
Agda claims that the context, at the place of the final occurrence of `a`, is as follows:
```
a      : Level
A      : Set a
a = a₁ : A   (not in scope)
```
Note that the module parameter `a` is claimed to not be in scope.
