### ISSUE TITLE
Safe decidability equality support for Name and Meta

### ISSUE THREAD

**Issue by L-TChen** [agda/agda#3736]
The current implementation of primitive equality for data types `Name` and `Meta` only gives a Boolean value. It seems impossible to me to define a safe decidable equality for them. 

Would it be possible to export an encoding or low-level representation for them with a primitive injectivity proof like https://github.com/agda/agda/pull/3701? Or anything similar? 

I am trying to use reflection in the cubical mode to automate tedious proofs, generation of eliminators, and so on. It would be really nice to have safe reflection with strong type safety.

**Comment by gallais** [comment]
`MetaId` is a `Nat` so that should be easy to do via an injective conversion function.

A `QName` has a `NameId` which is essentially a pair of `Word64` so maybe we
can get a well-behaved injective conversion function using that!

(I'll be too busy in the upcoming weeks to look at this; If you want to have a
go yourself, you should look into `src/full/Agda/TypeChecking/Primitives.hs`;
there is already a generic `mkPrimInjective` toplevel function so you'd only
have to work on the conversion primitives themselves and you can reuse the
`mkPrimInjective` for the proofs)

**Comment by L-TChen** [comment]
> `MetaId` is a `Nat` so that should be easy to do via an injective conversion function.
> 
> A `QName` has a `NameId` which is essentially a pair of `Word64` so maybe we
> can get a well-behaved injective conversion function using that!
> 
> (I'll be too busy in the upcoming weeks to look at this; If you want to have a
> go yourself, you should look into `src/full/Agda/TypeChecking/Primitives.hs`;
> there is already a generic `mkPrimInjective` toplevel function so you'd only
> have to work on the conversion primitives themselves and you can reuse the
> `mkPrimInjective` for the proofs)

Thanks for your prompt reply and the brief guideline. It looks pretty doable for beginners like me to hack in. I will try it!

**Comment by L-TChen** [comment]
Do you think it is okay to export the data type `NameId`? 

https://github.com/agda/agda/blob/adcd57d5a952b023a3c055d5d0310b479def1738/src/full/Agda/Syntax/Common.hs#L1305-L1308

**Comment by gallais** [comment]
> Do you think it is okay to export the data type `NameId`?

Alternatively you could export a function extracting the pair of `Word64`.
This way we are still not able to mess with a `NameId` from outside of the module.

**Comment by L-TChen** [comment]
Yes that's way better. I'll come back to this issue soon.

**Comment by gallais** [comment]
I have a bit of time today before switching back to deadline mode tomorrow so I
will try to get this one in.

**Comment by L-TChen** [comment]
Great. I can update the CHANGLOG today if you don’t have time.

**Comment by gallais** [comment]
Ah yeah sorry I forgot to.

**Comment by L-TChen** [comment]
I think this issue can be closed, and finish the project (hooray). Thanks so much.

**Comment by asr** [comment]
Removed whitespace issue in the title (detected when running the `closed-issues-for-milestone`).
