### ISSUE TITLE
Internal error related to abstract

### ISSUE THREAD

**Issue by nad** [agda/agda#3744]
The following code triggers an internal error:
```agda
abstract

  data D : Set where
    d : D

  data P : D → Set where
    p : P d

  d′ : D
  d′ = d

A : P d′
A = p′
  where

  abstract

    p′ : P d
    p′ = p
```
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Monad/Signature.hs:654
```
The following, similar code is accepted:
```agda
abstract

  data D : Set where
    d : D

  data P : D → Set where
    p : P d

A : Set₁
A = Set
  where

  abstract

    p′ : P d
    p′ = p
```
However, it shouldn't be: `d` should not be in scope in the type signature of `p′`.

The second piece of code is rejected by Agda 2.2.10 but accepted by Agda 2.3.0. Agda 2.5.2 reports an internal error for the first piece of code.

**Comment by andreasabel** [comment]
With option `-v impossible:10` we can see the error before the crash, but only with Agda-2.5.2:
```
$ agda-2.5.2 -v impossible:100 Issue3744.agda
Checking Issue3744 (Issue3744.agda).
Not in scope: Issue3744.D.d
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Reduce/Monad.hs:173
```
This error is thrown by `getConstInfo`: https://github.com/agda/agda/blob/176f92027ea31ca868480879164f4fc65bed0c41/src/full/Agda/TypeChecking/Monad/Signature.hs#L633-L647 
I have no clue why or where the debug text is swallowed.

**Comment by UlfNorell** [comment]
Without the `where`-block:
```agda
abstract

  data D : Set where
    d : D

  data P : D → Set where
    p : P d

  d′ : D
  d′ = d

private
  abstract
    p′ : P d
    p′ = p

A : P d′
A = p′
```

@nad 
> d should not be in scope in the type signature of p′.

Should abstract constructors not be in scope in private abstract type signatures? Should we then also not allow abstract function to reduce in these cases?

**Comment by nad** [comment]
[Yes](https://github.com/agda/agda/issues/418#issuecomment-245261194):

> HQ decision: remove feature "private type signatures can see through abstract definitions".
