### ISSUE TITLE
Inconsistency: Rounding op differentiates NaNs

### ISSUE THREAD

**Issue by L-TChen** [agda/agda#3749]
By testing #3740, I found a bug regarding `Float`. The following code produces inhabitants of the empty type using decidable equality for `Int` defined in the standard library. #2155 is also affected, I think. 

```agda
module _ where

open import Agda.Builtin.Float
  renaming ( primRound to round
           ; primFloor to floor
           ; primCeiling to ceiling
           ; primFloatNegate to -_
           ; primFloatDiv  to _/_)
open import Relation.Binary.PropositionalEquality hiding ([_])
open import Relation.Nullary
open import Data.Empty
open import Data.Integer.Properties using () renaming (_≟_ to _≟I_)

PNaN : Float
PNaN = 0.0 / 0.0

NNaN : Float
NNaN = - PNaN

f : ⊥
f with round PNaN ≟I round NNaN
... | no p = p (cong round {PNaN} {NNaN} refl)

g : ⊥
g with floor PNaN ≟I floor NNaN
... | no p = p (cong floor {PNaN} {NNaN} refl)

h : ⊥
h with ceiling PNaN ≟I round NNaN
... | no p = p (cong ceiling {PNaN} {NNaN} refl)
```

**Comment by nad** [comment]
One might argue that the problem is that `PNaN` is treated as equal to `NNaN`.

**Comment by L-TChen** [comment]
This NaN issue in IEEE754 is notorious. I think there are few possible solutions. 

1. Giving up identifying all NaNs, use their raw representation for propositional equality. If the user wants, she can use HIT to introduce identities and take care of the rest. Or she can use the exception monad to wrap Float. This approach  is easier for Agda implementers to maintain. 

2. Having a wrapper for functions from Float to check if the given input is NaN and return a canonical NaN. That is, every NaN is normalized before use. 

I have no strong opinion on this, since I just want a safe reflection to use in cubical mode.

**Comment by JacquesCarette** [comment]
I think option 1 is more consistent with how IEEE 754 is supposed to work.

**Comment by phile314** [comment]
Floats really are a can of worms ...

The current float implementation assumes that different float NaN values cannot be observed. Quote manual:

> Agda FLOAT values have only one logical NaN value. At runtime, there might be multiple different NaN representations present. All such NaN values must be treated equal by FFI calls.

However, if not even our own primitives adhere to that, I am not sure other people will follow that rule ...

Option 1 has the problem that NaN handling on different CPU architectures and compile targets can differ. E.g. JS only has one canonical NaN value and I faintly recall ARM processors also do something different from Intel x64 in some corner cases. See also https://github.com/WebAssembly/design/issues/619 and https://github.com/WebAssembly/design/issues/646 .

For Option 2, when would the NaNs be normalized? For all functions call or only for FFI calls?

Edit: How would option 2 work for FFI calls e.g. taking a list of floats (``squareAll :: List Float -> List Float``)?

**Comment by JacquesCarette** [comment]
I was not aware of that part of the manual. Option 1 does seem inconsistent with that -- which implies that Agda's implementation of floats is not consistent with IEEE 745 either.  Maybe that design decision was convenient at the time, but should be revisited?

**Comment by phile314** [comment]
What part of the Agda Float implementation are you referring to exactly? E.g. ``NaN != NaN`` or ``-0.0==0.0`` would make Agda incosistent (https://github.com/agda/agda/issues/2194, https://github.com/agda/agda/issues/2169 ), so just copying the standard / IEEE 745 float implementations into Agda is not possible.

What would an IEEE 745 - compliant Float implementation look like?

The "easy" way out here would be to just fix ``primRound`` to treat all NaNs equal.

**Comment by JacquesCarette** [comment]
Both of those came to mind.  Which is totally fine, as indeed IEEE 754 is 'mathematically broken' in that sense. So an IEEE 754 compliant implementation cannot be easily done in Agda.

There would be ways to do it, by having a wrapper for all Float values that would be abstract, so that `==` would not be applicable at all. Then one could export a relation from that module that is `==Float` a la IEEE 754.

**Comment by phile314** [comment]
I think the wrapper-question is orthogonal to the NaN problem. The big two NaN choices are:

* Multiple logical NaN values (=can be observed):
  + Works well & fast on x86
  - Every Agda interpreter/compiler target has to match the x86 Float implementation down to each bit (!)
  - Difficult to do in WebAssembly/JS (JS has only one NaN value)
  - Could make support for other CPU architectures such as ARM difficult

- Single logical NaN
  + Portable to many target architectures
  - Requires normalization of NaN at FFI boundaries and for primitives.
  - Has some performance overhead

As the single logical NaN approach is more portable and the "Multiple NaN" approach would break the JS backend with no clear way to fix it, I strongly favor the single NaN approach.

**Comment by JacquesCarette** [comment]
Very soundly argued. I am convinced by your position.

**Comment by L-TChen** [comment]
I am also in favour of single logical NaN now. 

It can be done easily by e.g., `mkPrimFun1 (round . normalise :: Double -> Integer)` or a safe 
`mkPrimFun`.

**Comment by copumpkin** [comment]
I’m not convinced IEEE 754 is compatible with logic, really. Take 0 and -0, which are “equal” in the standard. In almost all situations, the two behave identically, but not all. So say we have a proof that `0 == -0` in Agda: what should happen if we apply `cong (1/)` to it? Now we have a proof that `+Inf` and `-Inf` are equal, which they aren’t.

Edit: I see @phile314 already mentioned that, sorry I missed it

**Comment by rwe** [comment]
Is this a false choice? The discussion here is attempting to resolve three sets of semantics:
  * The language- and platform-specific semantics of float on the Agda compiler target (HS + your laptop)
  * The language- and platform-specific semantics of float types on an export target (JS or HS + an unknown machine)
  * An abstracted notion of "floating point numbers" (which refers to "some" implementation of IEE754)

via choosing a common baseline consistent with all of these. But that choice requires (potentially unnecessarily) conversions at all points before they can be safely used in proofs. (The _normalization of NaN at FFI boundaries_ bit @phile314 mentioned). Or alternatively, you risk that your proofs don't relate outside of Agda's model of floats.

Would it be more reasonable to do something like expose a `IEEE754` record with postulates that the spec itself guarantees independent of architecture, and perhaps optional properties for the compiler/extraction targets?

Then people could write propositions that are safe for general `IEE754` implementations; irrelevance of platform-specific behaviours is guaranteed (i.e. no "let's err on the safe side" normalizations). If they need platform-specific behaviours with extra axioms (like single/multiple `NaN`), then they could do so by specifying the implementation they're referring to.

For example, the property being discussed here is:
```agda
  NaN-injective : ∀ a b → isNaN a ≡ isNaN b → a ≡ b
```
That holds for some systems but not others; it shouldn't be "chosen" here, I think. It depends on the target, i.e. the particular choices of a target's IEEE754 behaviour.

As a sketch:
```agda
postulate Float : Set
{-# BUILTIN FLOAT Float #-}

record IEE754 (A : Set) : Set where
  isNaNInjective : Maybe NaN-injective {A = A}
  -- … all other props …

primitive primBuiltinFloat : IEE754 Float
instance 
  BuiltinFloatIEE754 : IEE754 Float
  BuiltinFloatIEE754 = primBuiltinFloat
```
Or could be done as sub-records ("`IsInjectiveNaNFloat`") or whatever…I'm not sure the best way to represent it.

This would allow you to define records for other targets (`Haskell-x86-Float`) and specialize proofs, if you cared to do so. And on the other end, if you do a proof for "all IEEE754 implementations, this holds", then the compiler could freely substitute its notion of floats for checking things and the target signatures for exporting things.

**Comment by JacquesCarette** [comment]
Oops, I forgot I was signed-in as drasil-bot! Sorry, that previous comment is mine.

**Comment by rwe** [comment]
@JacquesCarette I understand what you're saying but I think you might be misinterpreting my suggestion. I'm sorry I wasn't more clear.

> The thing that IEEE 754 calls 'equality' just isn't, and is not compatible with Agda's

I agree, Agda should not use "Haskell's floating point equivalence" as equality. Set aside Agda's current "Float" implementation for now.

> as it breaks `cong`
> […] That's why I would prefer to make `≡` "not applicable" to Floats at all.

I disagree. At the very least, there is a _bitwise_ equality that holds by definition. IEEE754 floats aren't totally abstract: they're defined by a set of bit patterns + semantics. That's why I referred to the spec by name.

IEEE754 guarantees a set of behaviours by definition, and leaves implementation-dependent many other properties. "General IEEE754" is a broader set than "Haskell Floats" or "WASM Number", which are specific implementations offering additional properties _about their types_. A Haskell Float isn't a JavaScript Float isn't a C `double`. But they are related.

So I'm suggesting making things very explicit: If you're writing a proof about IEEE754 floats in general, you have the properties guaranteed by the spec available. Only those. If you're relying on properties of Haskell's "Float" type, then you may need to explicitly rely on postulates. And those can natively exported to Haskell, but might require more transformations to map to JS floats. etc.

**Comment by rwe** [comment]
Section 3 ("Floating Point Formats") from the spec itself (Google "IEEE-754 spec") is very helpful here, by the way. It discusses the various format guarantees and how different representations and specification levels relate to each other. They don't need to be magical.

**Comment by phile314** [comment]
The explicit approach with records looks quite neat. However, I believe you also need to move the actual Float type and operations into the record. Else you would have expressions that compute to different values for different compiler targets. E.g. evaluating "primFloatAdd 0.0 nan" in Emacs should return exactly the same thing as when compiled to Haskell or JS.

On the other hand, from a maintenance perspective, having multiple float implementations doesn't sound so great ...

Is this actually an issue Agda itself needs to solve? Maybe this is a problem libraries should solve, as it already today is possible to package the Float implementation in a record and provide different implementations. Maybe Agda should just provide the single-nan primitives *for now* because they are the most portable ones and let libraries experiment with packaging it up or adding different implementations?

**Comment by identicalsnowflake** [comment]
What about simply declaring the float primitives unsafe? This way there's no need to untangle or formally model the float semantics, but users can still opt into them if they want for real-worldy reasons.

**Comment by gallais** [comment]
> What about simply declaring the float primitives unsafe?

This whole endeavour started in #3740 with the need for a safe proof of decidable
equality for Floats so that we could make the `Reflection` module of the standard
library safe.

**Comment by nad** [comment]
Is it important that floating-point primitives compute at compile-time? If not, then floats could be relegated to an unsafe library, and there would be no floating-point literals to worry about in the internal syntax. However, perhaps the answer to my question is [yes](https://github.com/agda/agda/issues/2194#issuecomment-251525747).

**Comment by L-TChen** [comment]
Floating-point arithmetic is important, but I don't find IEEE 754 equally important per se. There are other implementations, say [MFPR](https://dl.acm.org/citation.cfm?id=1236468), to improve/fix IEEE754. I also wonder if there is a type-theoretic floating-point arithmetic so that numerical computation can be done in a type-safe language while preserving efficiency. This is not a trivial task naively judging by the fact that a [formalisation](https://www.sciencedirect.com/science/article/pii/S0890540112000739) of floating-point arithmetic in Coq is published in a top journal.

IMO, it would be very hard to have a conclusion on the design of `float`, so we shall focus on how to fix the inconsistency based on @phile314's comment *for now*. I have pushed a commit in #3740 hopefully fixing this.

**Comment by JacquesCarette** [comment]
In the end, what matters most is that floats don't provide a way to prove false; also, it would be a pity if they introduced platform-visible differences (it would be a shame to be able to have computations yield different values on different platforms, even if I don't know how to leverage that to prove false).

They indeed don't have to be fully compliant with IEEE 754 to still be useful. And whenever my mood makes me want to prove false, I sure will know where to start poking!

**Comment by WolframKahl** [comment]
> (it would be a shame to be able to have computations yield different values on different platforms, even if I don't know how to leverage that to prove false).

As long as .agdai files are platfom-independent,
you could prove
```
  expr1 \== 1.0
```
on Machine1, and transport the proof together with its .agdai file onto Machine2,
where you also prove
```
  expr1 \== 1.1
```
...


Some day in the future, this could even be done on the same machine,
with one Agda implementation running on the GPU.  :wink:

**Comment by asr** [comment]
I realised this issue has milestone `2.6.0.1` but the fix wasn't cherry-pick into `release-2.6.0.1`. I'm trying of cherry-picking the fix.

**Comment by asr** [comment]
The fix depends of other changes don't include in `release-2.6.0.1`, so I'll change the milestone to `2.6.1`.

**Comment by xekoukou** [comment]
The test here only checks the haskell implementation of Floats, not the other backends , since other backends might have other definitions of primitives.

On another note, since during typechecking the haskell version is used, then any divergence from the haskell version will have quite unexpected results.

**Comment by L-TChen** [comment]
Urgh, I am not able to fix this and to add corresponding tests for it, as I am not aware of how other backends work. Assigning this task to backend maintainers, if any, would be a better choice, I believe.
