### ISSUE TITLE
HACKING.md: Wrong instruction for running certain tests

### ISSUE THREAD

**Issue by asr** [agda/agda#3755]
Let's suppose I want to run only the simple MAlonzo compiler tests. Following the instructions

https://github.com/agda/agda/blob/4bdc539eb50d6aaec98c6d82c2fd8f61c7a798f5/HACKING.md#L176-L186

I'm getting the error:

```
$ make AGDA_TESTS_OPTIONS="-i -j8 -p MAlonzo/simple" compiler-test
======================================================================
========================== Compiler tests ============================
======================================================================
option -p: Could not parse pattern
```

Could someone fix the the instructions, please.

**Comment by rwe** [comment]
I'm not familiar enough with the Makefile to update that, but the flag that I used with `stack` was `--regex-include`, so you might try that:
```
stack build Agda -j4 --test-arguments '--regex-include all/Compiler'
```

**Comment by asr** [comment]
The option `--regex-include all/Compiler` includes the `simple` and the `with-stdlib` tests. I only want to run the `simple` tests.

**Comment by UlfNorell** [comment]
```
make AGDA_TESTS_OPTIONS="-i -j8 -p MAlonzo.simple" compiler-test
```
