### ISSUE TITLE
Change the default RTS options?

### ISSUE THREAD

**Issue by nad** [agda/agda#3759]
@WolframKahl has argued several times that Agda should be run with non-default RTS options (see for instance https://github.com/agda/agda/pull/3589#issuecomment-467969770). I'm also often using non-default options. We could change the defaults by using [`-with-rtsopts`](https://downloads.haskell.org/~ghc/8.6.5/docs/html/users_guide/phases.html#ghc-flag--with-rtsopts=%E2%9F%A8opts%E2%9F%A9).

Should we change the defaults? In that case, what should we change them to?

Some considerations:
* Perhaps the defaults should be different depending on if a 32-bit or 64-bit kernel is used.
* Setting a maximum heap size can mean that Agda runs faster and needs less memory. However, it can also mean that Agda crashes when it otherwise wouldn't. Thus, if we change the default maximum heap size, then it might be a good idea to make Agda print a customised error message, informing the user of how to increase the maximum heap size, when the program runs out of heap (by catching the [`HeapOverflow`](https://hackage.haskell.org/package/base-4.12.0.0/docs/Control-Exception.html#t:AsyncException) exception; perhaps it makes sense to tweak the [`-Mgrace`](https://downloads.haskell.org/~ghc/8.6.5/docs/html/users_guide/runtime_control.html#rts-flag--Mgrace=%E2%9F%A8size%E2%9F%A9) RTS option).

**Comment by nad** [comment]
Due to lack of (expressed) interest I am closing this issue.

**Comment by JacquesCarette** [comment]
Which perhaps a good way to force people express interest.  I know I've changed my own setup to up the defaults. Sometimes people who agree because something just seems obvious won't say so. Hopefully this will force the issue, at least with people actively watching this repo.

**Comment by jespercockx** [comment]
Wait, why would we *not* change the default RTS options? Is there something magical about the current values that they should stay this way? I say we should change it to some reasonable default that works well for most users. I don't have an opinion on exactly what value it should be, but the current one isn't it.

**Comment by nad** [comment]
By default there is no maximum heap size. Unfortunately it seems as if this setting makes GHC use quite a bit more memory in some cases.

@jespercockx, did you forget to add this issue to some milestone?

**Comment by jespercockx** [comment]
I changed the default RTS options to `-H3.5G -M3.5G -A128M`. I do not know how to change the settings depending on 32/64 bit or on the total amount of memory available.

The current error message when the heap is exhausted is as follows:
```
agda: Heap exhausted;
agda: Current maximum heap size is 1048576 bytes (1 MB).
agda: Use `+RTS -M<size>' to increase it.
```
This looks acceptable to me.

**Comment by nad** [comment]
Did you intend to set a *minimum* heap size (`-H3.5G`)?
```
$ agda --help +RTS -H3.5G > /dev/null
agda: out of memory (requested 1048576 bytes)
```
And should the minimum allocation area be that large? The default is `1m`.

I use `-M1.5G` in the Emacs mode (on a 32-bit system).

**Comment by nad** [comment]
I think we can agree to set a *maximum* heap size. Perhaps we should leave it at that.

**Comment by jespercockx** [comment]
I just copied the settings that are used for the standard library tests (https://github.com/agda/agda-stdlib/blob/master/.travis.yml#L67) because they looked reasonable to me. This was very close to what whas also suggested by @WolframKahl and it seems to work well on my system, so I'm not sure what the problem is. Maybe if you know better default values you could adjust them yourself?

**Comment by UlfNorell** [comment]
Does setting a minimum heap size make a big difference? (ping @WolframKahl) It's seems silly to force people that don't have a lot of memory to fiddle with RTS options to be able to run Agda at all.

**Comment by nad** [comment]
> I'm not sure what the problem is.
```
$ agda --help +RTS -H3.5G > /dev/null
agda: out of memory (requested 1048576 bytes)
```

The point of setting a minimum heap size is presumably that you avoid growing the heap. However, always allocating gigabytes of heap (even for running `--help`, say) seems rather pessimistic to me.

**Comment by nad** [comment]
I have (temporarily?) removed the `-H` and `-A` options.

**Comment by WolframKahl** [comment]
I'd say that for general usage, a sizable minimum heap could indeed be wastful to harmful in many cases.

In general, increasing -A probably only makes sense with a larger heap.

And in my experience, every load has a different ``sweet spot'':
When I gave the standard library the options I used for my larger tasks,
it typechecked slower than necessary.

A few sample runs of a Haskell program invocation I happen to have lying around,
doing about 350G allocation, and reaching about 200M maximum residency: 
````
        RTS            Productivity    real       user
 -H512M -M4G           95.8%, 95.8%  1m45.170s  1m44.436s
 -H256M -M4G           92.3%, 92.3%  1m44.885s  1m44.068s
 -H256M -M256M         90.8%, 90.8%  1m47.714s  1m47.100s
 -H256M -M256M -A4M    90.8%, 90.8%  1m47.076s  1m46.431s
 -H256M -M4G   -A4M    94.5%, 94.5%  1m43.777s  1m43.071s
        -M4G           79.2%, 78.4%  1m53.517s  1m50.346s
        -M4G -A1M      84.4%, 84.4%  1m46.680s  1m45.437s
        -M4G -A2M      88.1%, 88.1%  1m44.247s  1m43.292s
        -M4G -A4M      91.5%, 91.5%  1m42.807s  1m41.992s
        -M4G -A8M      92.7%, 92.7%  1m46.421s  1m45.469s
        -M4G -A16M     93.5%, 93.5%  1m48.052s  1m47.327s
        -M4G -A32M     94.1%, 94.1%  1m48.078s  1m47.409s
        -M4G -A64M     94.7%, 94.7%  1m48.216s  1m47.561s
 -H512M -M4G -A64M     95.5%, 95.5%  1m47.316s  1m46.643s
 -H2G   -M4G -A64M     96.4%, 96.4%  1m45.868s  1m44.744s
````
(This is of course tiny in comparison with the Agda runs that I hope I will soon get back to...)

**Comment by nad** [comment]
OK, let's go with just `-M`, then.
