### ISSUE TITLE
Question about unification

### ISSUE THREAD

**Issue by molikto** [agda/agda#3766]
It seems to me meta variables must be solved inside the same closure/scoping where meta is introduced? So the code below is not a bug?

Is it true in general meta must be solved inside the scope they are in?

![1FFCB33379DE21121EAE14F4F0F00B20](https://user-images.githubusercontent.com/1373829/57567104-e7da9b00-7406-11e9-87a6-104d02c0cf4d.jpg)

**Comment by UlfNorell** [comment]
Yes. Metas are frozen after each mutual block, so the unsolved meta in the type of `b` cannot be solved by the use of `b` in `e`.
