### ISSUE TITLE
Incorrectly ordered generalised variables

### ISSUE THREAD

**Issue by nad** [agda/agda#3779]
Consider the following code:
```agda
open import Agda.Builtin.Equality

variable
  A B : Set
  f g : A

postulate
  F   : Set → Set
  map : (A → B) → F A → F B

lemma : (x : F A) → map (λ x → f (g x)) x ≡ map f (map g x)
lemma {g = g} {f = f} = ?
```
Note that `g` precedes `f` in the type signature of `lemma`. This is a bug. The documentation of generalisable variables [states](https://agda.readthedocs.io/en/latest/language/generalization-of-declared-variables.html#placement-of-generalized-bindings) that "Variables mentioned eariler are placed before variables mentioned later".

**Comment by UlfNorell** [comment]
Problem seems to be that our topological sort isn't stable.

**Comment by UlfNorell** [comment]
See https://gitlab.haskell.org/ghc/ghc/issues/14880 for the same issue in GHC, which @goldfirere had actually told me about, but I had forgotten.
