### ISSUE TITLE
confusing name choices related to hiding of dot patterns/different names in context and type of goal

### ISSUE THREAD

**Issue by jmchapman** [agda/agda#3781]
I was just presented with the following situation that really confused me. My mistake was to give a name "K" to a pattern which actually was a constructor pattern star. The thing I intended to give the name "K" to was called "K₁" by Agda and was out of scope. But, in the type of the hole I was trying to fill in, I believe "K" computed to star, my call to the function "extricateK K" computed to star and then Agda renamed "K₁" to "K" which confused me.

See below.

Goal: (Λ "x" (extricateK K) (extricate N) ·⋆ extricateNf⋆ W) SR.—→
      extricate (N AS.[ W ]⋆)
Have: (Λ "x" * (extricate N) ·⋆ extricateNf⋆ W) SR.—→
      (extricate N SS.[ extricateNf⋆ W ]⋆)
————————————————————————————————————————————————————————————
K  : Kind
N  : (Γ ,⋆ K₁) ⊢ B
Γ  : Ctx Φ  (not in scope)
W  : Φ ⊢Nf⋆ K₁
B  : Φ ,⋆ K₁ ⊢Nf⋆ *  (not in scope)
K₁ : Kind  (not in scope)
Φ  : Ctx⋆  (not in scope)

**Comment by jespercockx** [comment]
It's hard for me to understand from your description what exactly is the problem. Could you perhaps post a self-contained example where Agda chooses a bad name?

**Comment by jmchapman** [comment]
Yes, sorry, I will get back to you with a boiled down example.

**Comment by andreasabel** [comment]
> Yes, sorry, I will get back to you with a boiled down example.

Hopefully not famous last words. :D

**Comment by jespercockx** [comment]
In closing this in the assumption you found a solution, please reopen with a smaller example if needed.
