### ISSUE TITLE
Verbosity 0 and 1 do not work for debugPrint

### ISSUE THREAD

**Issue by L-TChen** [agda/agda#3783]
The following code does not print anything to Agda debug unless the verbosity for `debugPrint` is set to 2 or above. Is it intended? And why? 

```agda
{-# OPTIONS -v new:100 #-}

module Playground where

open import Agda.Builtin.Reflection
open import Agda.Builtin.List
open import Agda.Builtin.Unit

macro
  go : Term → TC _
  go hole = debugPrint "new" 0 (strErr "Hello World" ∷ [])

_ : ⊤
_ = go
```

**Comment by UlfNorell** [comment]
Level 0 and 1 are printed to the info buffer instead of the debug buffer in Emacs. It's cleared once the file loads though, so you don't have time to see it. You can see the command in the `*agda2*` buffer:

```
(agda2-info-action "*Type-checking*" "Hello World\n" t)
```

If you run it from the command line it prints as expected.

**Comment by L-TChen** [comment]
Thanks for your prompt reply! I will create a PR later for this as well as the purpose of the first argument to the user manual.
