### ISSUE TITLE
The fix for #3785 broke some code

### ISSUE THREAD

**Issue by nad** [agda/agda#3798]
The fix for #3785 (3c51ce531397bb2ebbd211b9418a7c7c2cc8b27b) broke some code for me:
```
git clone http://www.cse.chalmers.se/~nad/repos/equality/
cd equality
git checkout db52024deea67a24d42e6925ed7d7952f95a27b9
cat > Bug.agda <<EOF
open import Equality.Propositional
open import Prelude

open import Maybe equality-with-J
open import Monad equality-with-J

open import Tactic.By

test : (h : ℕ → Maybe ℕ) →
       ((xs : ℕ) → h xs ≡ just xs) →
       (xs : ℕ) → suc ⟨$⟩ h xs ≡ suc ⟨$⟩ return xs
test h hyp xs =
  suc ⟨$⟩ h xs       ≡⟨ by (hyp xs) ⟩∎
  suc ⟨$⟩ return xs  ∎
EOF
agda -i. Bug.agda
```
Result:
```
[…]/Bug.agda:13,11-15
No instance of type
Monad.Raw-monad (λ {z} {z = z₁} → Equality.J₀⇒J equality-with-J₀)
(λ v → _M_55 v)
was found in scope.
- raw-monad was ruled out because
  […]/Bug.agda:13,11-15
  fsuc xs != h xs of type (⊤ ⊎ ℕ)
  when checking that the expression h xs has type Maybe ℕ
- (λ {z} {z = z₁} {z = z₂} ⦃ z = z₃ ⦄ →
     Raw-monad-transformer.transform raw-monad-transformer)
    was ruled out because
  […]/Bug.agda:14,3-20
  ⊤ ⊎ ℕ !=<
  Maybe.MaybeT (λ {a} {p} → equality-with-J) (λ v → _M_87 v) ℕ of
  type Set
  when checking that the expression
  _⟨$⟩_ {lzero} {lzero} {Maybe {lzero}}
  ⦃ Maybe.raw-monad {congruence⁺} equality-with-J {lzero} ⦄ {ℕ} {ℕ}
  suc
  (Monad.Raw-monad.return {_} {_} {_} {_} {_}
   (Maybe.raw-monad {congruence⁺} equality-with-J {lzero}) {ℕ} xs)
  has type
  Maybe.MaybeT (λ {a} {p} → equality-with-J) (λ v → _M_87 v) ℕ
- Id-raw-monad was ruled out because
  […]/Bug.agda:14,3-20
  ⊤ ⊎ ℕ !=< Monad.Id (λ {a} {p} → equality-with-J) ℕ of type Set
  when checking that the expression
  _⟨$⟩_ {lzero} {lzero} {Maybe {lzero}}
  ⦃ Maybe.raw-monad {congruence⁺} equality-with-J {lzero} ⦄ {ℕ} {ℕ}
  suc
  (Monad.Raw-monad.return {_} {_} {_} {_} {_}
   (Maybe.raw-monad {congruence⁺} equality-with-J {lzero}) {ℕ} xs)
  has type Monad.Id (λ {a} {p} → equality-with-J) ℕ
when checking that suc (h xs) are valid arguments to a function of
type
{d c : Level} {M : Set d → Set c} ⦃ r : Raw-monad M ⦄
{A B : Set d} →
(A → B) → M A → M B
```
I don't know if this is a bug or not, but I think it makes sense to investigate the problem.

**Comment by nad** [comment]
A first analysis of the problem:

* The tactic tries to solve the goal `suc ⟨$⟩ _ ≡ suc ⟨$⟩ return xs` using reflexivity (where `_` is a meta-variable which I guess stands for a blocked term).

* Previously this failed: The tactic tried to unify the goal with reflexivity, but because the goal meta-variable did not reduce to an application of `refl` this attempt was aborted.

* Now this attempt is partially successful: The unification succeeds, and the goal meta-variable does reduce to an application of `refl`. Thus the attempt is not aborted, which later leads to a type error.

Should unification succeed here? Is the idea that a blocked term should unify with anything? My guess is that unification should not succeed.

**Comment by nad** [comment]
@jespercockx and I tried to analyse the problem. It seems as if his fix is not to blame.

> where `_` is a meta-variable which I guess stands for a blocked term

It seems as if this meta-variable was not blocked, but it was not solved. There was a solvable constraint that for some reason was not attempted before the tactic was invoked. What kind of internal invariants do Agda maintain? Here is a (perhaps simplified or incorrect) view of the problem:

* There is a constraint `?X = a` that has not been solved yet.
* Agda is asked to unify `?X = b`, for some term `b` that is not definitionally equal to `a`.

Is it then OK for Agda to solve `?X` with `b`? I guess the answer is "yes". If the type-correctness of any term depends on the constraint `?X = a`, then that term should be blocked.

Perhaps there is no bug, except in my own tactic code. However, I find it rather awkward that it is so easy to write brittle tactics that break due to small internal changes to Agda. I think it makes sense to try to construct an interface that is easier to use (perhaps taking inspiration from work done on other proof assistants).

**Comment by jespercockx** [comment]
I agree that the current reflection API is rather low-level and it would be nice to have something that's easier to use without understanding a lot of Agda's internals. However it's hard to see a concrete action here that we can take right now, so I'm closing this issue.
