### ISSUE TITLE
Agda prelude: Internal error at src/full/Agda/TypeChecking/Reduce/Fast.hs:1347

### ISSUE THREAD

**Issue by xekoukou** [agda/agda#3805]
The code is from [agda-prelude](https://github.com/UlfNorell/agda-prelude/blob/master/src/Data/TreeRep.agda)

Agda version 2.6.1-64218e5

**Comment by andreasabel** [comment]
Could maybe interest @UlfNorell .

**Comment by rwe** [comment]
Link to the exact line of that file at that revision: https://github.com/agda/agda/blob/64218e5358343dd9bc76bf7deba860e611f15933/src/full/Agda/TypeChecking/Reduce/Fast.hs#L1347

**Comment by UlfNorell** [comment]
Most likely the same (with shrunk test case): #3870.

**Comment by UlfNorell** [comment]
Closing as duplicate.
