### ISSUE TITLE
For open import M, Agda should remember that M is an external module

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda#3818]
Consider the following example:

File: Test.agda
```agda
module Test  where
record A : Set where
```

File: Test/A.agda
```agda
module Test.A where
record A : Set where
```

File: Bug.agda
```agda
module Bug where

-- open import Test using ()
open import Test.A using (module A)
```
As written the code type checks fine. If you uncomment the line in `Bug.agda` it fails with the message
```
Ambiguous module name Test.A. It could refer to any one of
  Test.A
  Test.A (record module)
```
Spent my afternoon chasing this error around the standard library with `Function.Injection` instead of `Test.A`.

**Comment by andreasabel** [comment]
This can be shrunk to these 3 files:

```agda
module Issue3818.M.N where
```

```agda
module Issue3818.M where

module N where
```

```agda
module Issue3818 where

open import Issue3818.M using ()
-- OK: import Issue3818.M.N
open import Issue3818.M.N using () -- ambiguous
```

Of course, a _file_ module like `import Foo` should not clash with a non-file module `Foo` in import-declarations.  However, the last declaration is likely desugared to
```agda
import Issue3818.M.N 
open Issue3818.M.N using () -- ambiguous
```
where the connection between the file system and module hierarchy is lost.  (This shows that this desugaring is not complete...)  
But even the desugaring should not give a scope error.  Here is an equivalent test:
```agda
open import Issue3818.M hiding (module N)
import Issue3818.M.N

module Test = Issue3818.M.N  -- error: ambiguous
```
The `hiding module N` seems to be silently ignored.  `C-c C-w` gives:
```
* a module Issue3818.M.N brought into scope by
    - its definition at Issue3818/M/N.agda:1,20-21
  * a module Issue3818.M.N brought into scope by
    - its definition at Issue3818/M.agda:3,8-9
```
(Here is also the problem that `C-c C-w` does not trace the `open` statements.)

**Comment by andreasabel** [comment]
My analysis was not entirely correct;
```agda
open import Issue3818.M hiding (module N)
```
or
```agda
open import Issue3818.M using ()
```
adds the following to the scope:
```agda
Issue3818.M  -- via import
Issue3818.M.N -- content of Issue3818.M
```
If we want to ban `N` entirely, we have to omit `open`; import directives such as `using` and `hiding` behave differently for `open` and `import`:
```agda
import Issue3818.M hiding (module N)
```
or
```agda
import Issue3818.M using ()
```
A weak point in the design here is that
```agda
open import M _directive_
```
could be read as either
```agda
import M
open M _directive_
```
or
```agda
import M _directive_
open M
```
which have different meanings.  The first reading is the one Agda implements.

**Comment by nad** [comment]
>  The first reading is the one Agda implements.

This is by design, not by accident.

**Comment by andreasabel** [comment]
What can be done about this issue is that in
```agda
open import M
```
the `open` not just gets the concrete name `M`, but also its previous resolution, which is non-ambiguous, as `M` must be a module with a incarnation as file in the file system.

**Comment by nad** [comment]
I'm not sure I agree that this is a bug, and I am not convinced that it makes sense to change the desugaring of `open import`.

**Comment by andreasabel** [comment]
Just remembering the resolution of a concrete name when calling `openModule`, instead of letting it resolve it again, fixes this issue, see PR #3822.

Without the fix, can you give an intuitive justification why
```agda
...
module M where
import M
```
is ok, while for
```agda
...
module M where
open import M
```
Agda suddenly complains that `M` is ambiguous?  What made it more ambiguous?

NB: I do recall my surprise years ago when seeing that the representation of module names in abstract syntax does not remember where the file-system part ends and the internal module structure begins.  (As a consequence, for instance, it is not easy to strip off the top-level module name from an abstract name.)

**Comment by JacquesCarette** [comment]
Question: are parens legal in the `open import` syntax? i.e. could one do
```agda
open (import M <directives>) <directives>
```
?

**Comment by andreasabel** [comment]
> `open (import M <directives>) <directives>`

Maybe we should think about making this legal, see also https://github.com/agda/agda/issues/3928#issuecomment-512825189 .
