### ISSUE TITLE
Case-split: don't generate pattern covered by unreachable clause

### ISSUE THREAD

**Issue by gallais** [agda/agda#3829]
It's quite common when refactoring to add a few extra constructors to a
datatype. It's also convenient to be able to throw in a catch-all clause
to existing functions and use case-splitting to generate the missing cases.

However if we threw in the catch-all clause anywhere but at the bottom,
the split will ignore the clauses below it and generate clauses for cases
which are already handled.

e.g. splitting on `t` in the following definition produces two equations
(one for `A` and one for `B`) instead of just the one for `A`.

```agda
data Type : Set where
  A B : Type

f : Type → Type
f t = {!!}
f B = {!!}
```

**Comment by jespercockx** [comment]
Here is the relevant code:

https://github.com/agda/agda/blob/2c5db56079d1a057e1baf272aa35c7aa23cf9edf/src/full/Agda/Interaction/MakeCase.hs#L299-L301

When I implemented this, I decided to only take into account the previous clauses because the later clauses are already unreachable. It shouldn't be hard to also consider the *following* clauses rather than just `prevClauses`, if that's what we want.

**Comment by gallais** [comment]
Looks like the refactoring introducing `getClauseZipperForIP` and thus returning
the preceding *and* following clauses is going to be useful after all! :D

Hmmm... if there's a catchall somewhere later in the list of clauses then the whole
split is thrown away which is not what we want. Trying to filter the catch-alls out
using `not . clauseCatchall` does not seem to have any effect. That's a shame.

```diff
diff --git a/src/full/Agda/Interaction/MakeCase.hs b/src/full/Agda/Interaction/MakeCase.hs
index 5815be780..8be74ee9d 100644
--- a/src/full/Agda/Interaction/MakeCase.hs
+++ b/src/full/Agda/Interaction/MakeCase.hs
@@ -298,7 +298,7 @@ makeCase hole rng s = withInteractionId hole $ do
 
     -- CLEAN UP OF THE GENERATED CLAUSES
     -- 1. filter out clauses that are already covered
-    scs <- filterM (not <.> isCovered f prevClauses . fst) scs
+    scs <- filterM (not <.> isCovered f (prevClauses ++ filter (not . clauseCatchall) follClauses) . fst) scs
     reportSLn "interaction.case" 70 $ "makeCase: survived filtering out already covered clauses"
     -- 2. filter out trivially impossible clauses not asked for by the user
     cs <- catMaybes <$> do
```

**Comment by jespercockx** [comment]
`clauseCatchall` only indicates whether the user wrote a `{-# CATCHALL #-}` pragma or not, so it's no surprise that it has no effect. However, we could remember whether the coverage checker marks the clause as an exact split or not, and maybe somehow use that information. Actually I already have some code on my machine at work for remembering this information (for a different purpose). I could push it on Monday if you're interested in using it.

**Comment by gallais** [comment]
Ok, it's a bit more subtle than a mere catchall: we want to ignore all the clauses
which are coming after the one the split is made at and which cover it.

E.g. if we split on `n` we want to only get `suc n` even though the last clause
(which is not a catchall) does cover the pattern `f (suc m) (suc n) _`.

```agda
f : Nat -> Nat -> Nat -> Nat
f m zero _ = zero
f (suc m) n _ = ?
f (suc m) _ _ = zero
```

PR incoming.

**Comment by jespercockx** [comment]
Ah so the new criterion would be that if a later clause already covered the clause before the case split, we don't want to take it into account for the filtering of the clauses after the case split. That does seem to make sense.
