### ISSUE TITLE
Should we normalise types in error messages?

### ISSUE THREAD

**Issue by gallais** [agda/agda#3836]
In agda/agda-stdlib#798, I try to ensure that error messages are helpful when
the string format is broken.

The problem I now have is that the error message for the following application
("%a" is not a valid type specification for a format string)

```agda
printf "%s: %u + %a ≡ %u" "example" 3 2 5
```
is as follows:

```
Error
(Text.Format.Error.InvalidType
 (fromList
  (reverse
   ('%' ∷ ' ' ∷ '+' ∷ ' ' ∷ 'u' ∷ '%' ∷ ' ' ∷ ':' ∷ 's' ∷ '%' ∷ [])))
 'a' (fromList (' ' ∷ '≡' ∷ ' ' ∷ '%' ∷ 'u' ∷ [])))
should be a function type, but it isn't
when checking that "example" 3 2 5 are valid arguments to a
function of type
Text.Printf.Printf (Text.Format.lexer "%s: %u + %a ≡ %u")
```

Ideally I would like to have:

```agda
Error (Text.Format.Error.InvalidType "%s: %u + %" 'a' " ≡ %u")
should be a function type, but it isn't
when checking that "example" 3 2 5 are valid arguments to a
function of type
Text.Printf.Printf (Text.Format.lexer "%s: %u + %a ≡ %u")
```

Hence the question in the title: should we normalise the types in error messages?

**Comment by L-TChen** [comment]
In some cases, normalised types are harder to understand.

A new option for normalised error messages would be better.

**Comment by andreasabel** [comment]
> Hence the question in the title: should we normalise the types in error messages?

Clearly no, not in general.  We have devoted some effort in the past to do minimal normalization during type checking, in order to give the least expanded types in error messages.

However, I am afraid, there is no one-size-fits-all.  A high hanging fruit is an interactive normalizer for things Agda prints.  Such has been suggested a number of times...

**Comment by xekoukou** [comment]
relevant :  #3414

**Comment by UlfNorell** [comment]
In this particular case you might be able to force normalisation by making `InvalidType` a defined function that's strict in its argument.

**Comment by banacorn** [comment]
@andreasabel @xekoukou https://github.com/agda/agda/pull/3811 is the PR that is inching towards a more interactive normalizer. 

Here's a demo when the editor knows a bit more about the error message. 

![Agda json demo](https://media.giphy.com/media/1vZ6Qs9PHeAn9INkUI/giphy.gif)

**Comment by gallais** [comment]
As @xekoukou indicates, this is somewhat a duplicate of #3414.
Plus following @UlfNorell's advice was enough to fix my use case.
