### ISSUE TITLE
Improve GHC backend

### ISSUE THREAD

**Issue by L-TChen** [agda/agda#3838]
> I think the efficiency of the backends have received less attention. In this case I assume that it is GHC that requires lots of resources, possibly because the generated Haskell code is huge. If that is the case, then a first step might be to figure out why that is the case. Perhaps you could open a separate ticket for this issue.

_Originally posted by @nad in https://github.com/agda/agda/pull/3815#issuecomment-497926095_

Compiler test uses lots of resource to finish. Simply updating the std-lib submodule forces me to increase the heap size to 3GB from 2.5GB for all GHC versions (not just 8.0.x) in order to run the compiler test on Travis. It will be nice to figure out why and possibly to improve the GHC backend. 

As suggested by @nad, I open a separate ticket for this.

**Comment by WolframKahl** [comment]
Are the tests running Agda (*.agdai --> *.hs) and GHC separately?

If you do not call Agda with `--ghc-dont-call-ghc`, then Agda and GHC compete for memory.

**Comment by L-TChen** [comment]
> Are the tests running Agda (*.agdai --> *.hs) and GHC separately?

No. 

https://github.com/agda/agda/blob/928fa9c1a5718eaf213e7a2c0f148af50c10a4f6/test/Compiler/Tests.hs#L113-L131

The change should go to Agda itself instead if it works. [ It seems so on my machine ... ]

**Comment by jespercockx** [comment]
There doesn't seem to be a concrete proposal here and no clear path forward, so I am closing this. A concrete way to reduce the code size of Haskell generated by Agda is to use erasure annotations, once https://github.com/agda/agda/issues/4193 has been fixed.
