### ISSUE TITLE
Suggestion for non-structurally decreasing function arguments analysis whilst termination checking

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda#3842]
Forgive me if this is yet another case a naive suggestion for the termination checker, but it seems to be me that a fairly simple structural analysis counting the number of constructors in the input and output could improve the termination checker in many cases. Consider the following example:  
```agda
open import Agda.Builtin.Nat

f : Nat → Nat
f zero    = zero
f (suc x) = suc (f x)

g : Nat → Nat
g zero    = zero
g (suc x) = g (f x)
```
A simple count of constructors during termination checking would show that `f`'s output is no bigger than it's input. This information could then kept and used when checking that `g` terminates. This would allow `g` to pass termination checking when at the moment it fails.

It's a little more complicated to identify which inputs should be compared to the output when you're considering parameterised families of types (as in my main motivating example):
```agda
↭-respˡ-≋ : ∀ {xs ys zs} → zs ≋ xs → ys ↭ xs → ys ↭ zs
↭-respˡ-≋ xs≋ys               (refl zs≋xs)         = refl (≋-trans (≋-sym xs≋ys) zs≋xs)
↭-respˡ-≋ (x≈y ∷ xs≋ys)       (prep eq zs↭xs)      = prep (≈-trans (≈-sym x≈y) eq) (↭-respˡ-≋ xs≋ys zs↭xs)
↭-respˡ-≋ (x≈y ∷ w≈z ∷ xs≋ys) (swap eq₁ eq₂ zs↭xs) = swap (≈-trans (≈-sym x≈y) eq₁) (≈-trans (≈-sym w≈z) eq₂) (↭-respˡ-≋ xs≋ys zs↭xs)
↭-respˡ-≋ xs≋ys               (trans ws↭zs zs↭xs)  = trans (↭-respˡ-≋ xs≋ys ws↭zs) zs↭xs
```
Here obviously `ys ↭ xs` is not the same type as `ys ↭ zs` but nonetheless the proof of the latter is clearly no bigger than the former again by simply counting constructors.  The initial heuristic would therefore be that only inputs that belongs to the same parameterised family as the output were analysed. Obviously the analysis wouldn't catch everything, but it appears to me a fairly easy win for the termination checker? I'm sure I'm probably missing something obvious though!

**Comment by andreasabel** [comment]
This is exactly what is made formal through the introduction of sized types:
```agda
open import Agda.Builtin.Size

data Nat (i : Size) : Set where
  zero : Nat i
  suc  : {j : Size< i} (n : Nat j) → Nat i

f : ∀{i} → Nat i → Nat i
f zero    = zero
f (suc x) = suc (f x)

g : ∀{i} → Nat i → Nat i
g zero    = zero
g (suc x) = g (f x)
```
The problem is that sized types are not a silent analysis behind the veal but an explicit syntax.  The explicit syntax was to get something to work, I never got to the stage where sizing of data is just happening automatically.

I suppose one could do a syntax analysis like with positivity for sizing and then store some input-output relations for functions in the signature.  Pragmatically, this might give the user what they wants.  However, heaping heuristics upon heuristics conflicts with the wish that Agda be _foundational_, resting on a few principles that self-evident or at least easy to explain.  A couple of pages of typing and equality rules should be all that is needed to specify the underlying type theory.  Somehow this seems unattainable in the Agda approach where the surface language is epsilon-distance from the type theory.  Other proof assistants (Isabelle, Lean) have a small core but an unlimited surface language that gets translated to the core.  Maybe this is the future, but it buys us other problems:  How to explain back to the user type errors happening in the core in terms of the surface syntax they wrote.

**Comment by MatthewDaggitt** [comment]
> This is exactly what is made formal through the introduction of sized types:

Whoops, yes it is. Apologies for not realising it.

> I suppose one could do a syntax analysis like with positivity for sizing and then store some input-output relations for functions in the signature. Pragmatically, this might give the user what they wants. However, heaping heuristics upon heuristics conflicts with the wish that Agda be foundational, resting on a few principles that self-evident or at least easy to explain. 

Thanks for the explanation, I can definitely see where your coming from and it seems like a reasonable philosophy.

The only problem I have with the introduction of explicit sized types, is that in all three examples where this has caused me problems is that sizes are only required in perhaps 1 out of 40 proofs. Adding in sizes just to get a couple proofs through would involve adding an enormous amount of boilerplate sized code, which not only bloats the presentation but also makes the datatypes much harder to use.

Bluesky thinking but maybe there's a halfway house where it would be possible to automatically generate a non-sized type from a sized type and then the sized/non-sized versions could be used as appropriate.

Note: For those interested also see the Agda mailing list thread [here](https://lists.chalmers.se/pipermail/agda/2019/011209.html) which is discussing a very similar issue.

**Comment by JacquesCarette** [comment]
@alhassy something to add to your list of things to consider.

**Comment by nad** [comment]
> Adding in sizes just to get a couple proofs through would involve adding an enormous amount of boilerplate sized code

An alternative is to use manual sizes, then you get to choose exactly where to use them:
```agda
open import Agda.Builtin.Equality
open import Agda.Builtin.Nat

f : Nat → Nat
f zero    = zero
f (suc x) = suc (f x)

size : Nat → Nat
size n = n

f-is-size-preserving : ∀ n → size (f n) ≡ size n
f-is-size-preserving zero    = refl
f-is-size-preserving (suc n)
  rewrite f-is-size-preserving n = refl

g : Nat → Nat
g n = g′ n _ refl
  where
  g′ : ∀ m n → size m ≡ n → Nat
  g′ zero    _       _  = zero
  g′ (suc m) zero    ()
  g′ (suc m) (suc n) eq =
    g′ (f m) n (lemma (f-is-size-preserving m) eq)
    where
    lemma : {m n o : Nat} → m ≡ n → suc n ≡ suc o → m ≡ o
    lemma refl refl = refl
```
Note that I chose not to match on the equality proof in `g′`. This way the computation does not get stuck if the proof has the wrong shape. The computation does depend on the structure of the size argument, though. In this case that is not a problem, but it might be in other cases.

**Comment by jespercockx** [comment]
I'm going to assume this question has been answered. Please open a new issue if you have a concrete proposal for an enhancement.
