### ISSUE TITLE
Add flag to WarningOnUsage and WarningOnImport to only fire for external libraries

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda#3844]
When deprecating an operation you also want to deprecate all the proofs associated with it as well. At the moment you can't attach a `WarningOnUsage` to the operation itself because it's reused by the proofs which you also want to deprecate. See for example 

https://github.com/agda/agda-stdlib/blob/f3b17f24ed136143dac80042d34b79aaed78a213/src/Data/Integer/Properties.agda#L1631

It'd be great if the two options could take a flag that toggles whether they only fire for external libraries. Not sure how easy that would be...

**Comment by gallais** [comment]
You can put `{-# OPTIONS --warn=noUserWarning #-}` at the top of the file where you
use the deprecated names.

**Comment by MatthewDaggitt** [comment]
Ooh neat, thanks! The option `userWarning` doesn't seem to documented [here](https://agda.readthedocs.io/en/v2.6.0.1/tools/command-line-options.html). It might also be worth adding that tip to [here](https://agda.readthedocs.io/en/v2.6.0.1/language/pragmas.html#warning-pragma) as well.

**Comment by gallais** [comment]
Fixed with 2b9c7e3e75b8f36dd6d3ec7463274b2f3cf6e3d1 and e6be097e1d6c8807de9d633a32b28a5a84434a02
