### ISSUE TITLE
Internal error when rewriting type constructors

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#3846]
This has been known for a while, but lately I have been reconsidering the kind of guarantees one should be able to expect from rewrite rules, and it bothers me that it's so easy to trigger internal errors:
```agda
{-# OPTIONS --rewriting #-}

open import Agda.Builtin.Equality
open import Agda.Builtin.Bool
open import Agda.Builtin.Nat

{-# BUILTIN REWRITE _≡_ #-}

not : Bool → Bool
not true = false
not false = true

postulate rew : Nat ≡ Bool
{-# REWRITE rew #-}

0' : Bool
0' = 0

test : not 0' ≡ true
test = refl
```
Error message:
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Reduce/Fast.hs:1347
```
I'm thinking that we should maybe not allow rewrite rules on type constructors by default.

**Comment by gallais** [comment]
I was reading your 'Type theory unchained' and was surprised that if this was
a problem then simply forbidding rules working over type constructors was enough.
And indeed it is possible to revive this internal error by adding one level of
indirection:

```agda
{-# OPTIONS --rewriting #-}

open import Agda.Builtin.Equality
open import Agda.Builtin.Bool
open import Agda.Builtin.Nat

{-# BUILTIN REWRITE _≡_ #-}

not : Bool → Bool
not true = false
not false = true

F : Bool → Set
F true = Bool
F false = Nat

0' : F false
0' = 0

postulate rew : false ≡ true
{-# REWRITE rew #-}

test : not 0' ≡ true
test = refl
```

yields

```agda
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Reduce/Fast.hs:1362
```

with Agda 2.6.1

**Comment by gallais** [comment]
In [Coq modulo theory](https://hal.inria.fr/file/index/docid/497404/filename/csl-2010.pdf), Strub insists that it is crucial to have two versions of the
conversion algorithm: the *strong* one enriched with the extra equalities of the
theory and the *weak* one without. To preserve consistency the weak conversion is
used when performing large elimination.

Not sure whether that would bring down any of the examples you have.

**Comment by jespercockx** [comment]
You need two properties: no rewriting of type constructors + global confluence of the rewrite system. Your example is not confluent (since `F false` rewrites to both `Nat` and `Bool`), but it seems the confluence checker (which can be enabled by `--confluence-check`) does not detect this.

But it would also be nice to have this not be an internal error even if the user *does* give a non-confluent rewrite system. However, I'm not sure how to do this without losing the ability to catch real bugs in Agda without `--rewriting` caused by defects in the coverage checker.

**Comment by jespercockx** [comment]
Well, I guess I could replace the `__IMPOSSIBLE__` with a `if rewritingEnabled then NoReduction else __IMPOSSIBLE__` or something of the sort. That way the example would break canonicity, but would not trigger an internal error at least.

**Comment by jespercockx** [comment]
I don't think we should reopen issues that have a milestone of a released version. I will create a new issue for this instead.
