### ISSUE TITLE
Implement (or at least document) @0

### ISSUE THREAD

**Issue by nad** [agda/agda#3855]
- [ ] Agda parses the `@0` attribute but it seems to be undocumented. 

A [commit comment](https://github.com/agda/agda/commit/5f5efa7406c90a63c700d9f3dfbd4d13af1317de) suggests that it has something to do with runtime erasure, but states that, at the time, it didn't "do anything yet".

What is the status of this attribute now? I saw that @jespercockx recently changed something related to `@0` (#3853), but quick testing suggests that the typing rules are not properly implemented (I have not checked if the backends make use of this attribute).

**Comment by nad** [comment]
> quick testing suggests that the typing rules are not properly implemented

- [X] Here is one example:
```agda
open import Agda.Builtin.Bool
open import Agda.Builtin.Nat

record Erased (A : Set) : Set where
  constructor [_]
  field
    @0 erased : A

open Erased public

module _
  (_≡_ : Bool → Bool → Set)
  (subst : {x y : Bool} (P : Bool → Set) → x ≡ y → P x → P y)
  where

  F : Bool → Set
  F true  = Nat
  F false = Bool

  -- rejected : (@0 _ : true ≡ false) → Bool
  -- rejected eq = subst F eq 4

  -- rejected : Erased (true ≡ false) → Bool
  -- rejected [ eq ] = subst F eq 4

  should-also-be-rejected : Erased (true ≡ false) → Bool
  should-also-be-rejected eq = subst F (erased eq) 4
```

**Comment by nad** [comment]
- [X] Here is another example:
```agda
variable
  @0 A : Set

f : A → A
f x = x
```
The inferred type of `f`: `{A : Set} → A → A`. Presumably it should be `{@0 A : Set} → A → A`.

**Comment by nad** [comment]
- [X] And another example:
```agda
open import Agda.Builtin.Equality

-- rejected : (@0 A : Set) → A ≡ A
-- rejected A = refl {x = A}

should-also-be-rejected : (@0 A : Set) → A ≡ A
should-also-be-rejected A = refl
```

- [X] Edit: @UlfNorell stated that the latter term should be accepted, because `refl` does not take any arguments. The following example should illustrate the problem in a better way:
```agda
module _
  (_≡_ : {A : Set₁} → A → A → Set)
  (refl : {A : Set₁} {x : A} → x ≡ x)
  where

-- rejected : (@0 A : Set) → A ≡ A
-- rejected A = refl {x = A}

should-also-be-rejected : (@0 A : Set) → A ≡ A
should-also-be-rejected A = refl
```
- [X] Or this one:
```agda
module _
  (_≡_ : {A : Set₁} → A → A → Set)
  (refl : {A : Set₁} (x : A) → x ≡ x)
  where

-- rejected : (@0 A : Set) → A ≡ A
-- rejected A = refl A

should-also-be-rejected : (@0 A : Set) → A ≡ A
should-also-be-rejected A = refl _
```

**Comment by nad** [comment]
- [ ] Either the following code should be rejected, or `@0` should not be allowed when `--without-K` is active:
```agda
open import Agda.Builtin.Equality

subst-erased : {A : Set} {x y : A} (P : A → Set) (@0 _ : x ≡ y) → P x → P y
subst-erased P refl p = p
```

Edit: Moved to #4172.

**Comment by nad** [comment]
- [x] The annotations `@0` and `@erased` are not highlighted in the same way: `0` is highlighted as a number, and `erased` is not highlighted. I think both should be highlighted in the same way (one option would be to highlight both as symbols, like `forall`, `=` and `@`).

**Comment by nad** [comment]
- [X] Here is another broken example:
```agda
data D : Set where
  c : D

@0 x : D
x = c

should-be-rejected : D
should-be-rejected = x
```

**Comment by andreasabel** [comment]
- [X] Currently, the following fails in the compiler:
```agda
open import Common.IO
open import Common.Unit
open import Common.String
open import Common.Bool

record Erased (A : Set) : Set where
  constructor erase
  field
    @0 gone : A

noWorld : Bool → Erased String
noWorld true  = erase "Hello world!"
noWorld false = erase "Hallo, Welt!"

-- Illegal definition, should raise a type error.

unerase : ∀{A : Set} → Erased A → A
unerase = Erased.gone

main = putStrLn (unerase (noWorld false))
```
Agda produces Haskell code with unbound identifiers (`gone`).

**Comment by nad** [comment]
- [X] Here is a piece of code that should not be rejected:
```agda
F : (@0 _ : Set) → Set₁
F A = Set
  where
  @0 Should-not-be-rejected : Set
  Should-not-be-rejected = A
```

**Comment by nad** [comment]
- [x] Consider the following code:
```agda
F : (@0 A : Set) → Set
F A = ?
```
Agda presents the goal's context in the following way:
```
A : Set
```
I think it would make sense to include the `@0` annotation in the presentation of the context (but perhaps not first on the line).

**Comment by nad** [comment]
I have developed some code that uses `@0`. I would not be surprised if this code stops working when the implementation of `@0` becomes more complete, but perhaps it could be used for testing:

* Some [theory](http://www.cse.chalmers.se/~nad/listings/equality/Erased.html) of a type family `Erased`.
* An [example](http://www.cse.chalmers.se/~nad/listings/equality/Nat.Binary.html) of how `Erased` can be used: an implementation of natural numbers that is intended to be compiled to binary natural numbers, but computes (almost) like unary natural numbers when the code is type-checked.

The code can be obtained from its [Git repository](http://www.cse.chalmers.se/~nad/repos/equality).

**Comment by nad** [comment]
> Either the following code should be rejected, or `@0` should not be allowed when `--without-K` is active:
> ```agda
> open import Agda.Builtin.Equality
> 
> subst-erased : {A : Set} {x y : A} (P : A → Set) (@0 _ : x ≡ y) → P x → P y
> subst-erased P refl p = p
> ```

In the development above I use Cubical Agda, I don't think `@0` should be disabled in that setting.

I also have code like the following function (where `[_]` has type `{a : Level} {@0 A : Set a} → @0 A → Erased A`):
```agda
to : Erased (W A P) → W (Erased A) (λ x → Erased (P (erased x)))
to [ sup x f ] = sup [ x ] λ { [ y ] → to [ f y ] }
```
Does it make sense to allow matching on single-constructor non-indexed data types in an erased context? One could almost rewrite the code above using projections instead of pattern matching:
```agda
to : Erased (W A P) → W (Erased A) (λ x → Erased (P (erased x)))
to [ x ] = sup [ headᵂ x ] λ { [ y ] → to [ tailᵂ x y ] }
```
This code is not accepted by the termination checker, and because `[_]` is a record constructor an application `to x` can be unfolded indefinitely. However, I don't think these problems matter at run-time, so my guess would be that it is fine to allow the first definition of `to` above.

**Comment by andreasabel** [comment]
@nad wrote:
> I would not be surprised if this code stops working when the implementation of @0 becomes more complete

Maybe a good moment to test now since @0 is now respected during meta variable solving.

> The code can be obtained from its Git repository.

How? HTTPS does not seem to work:
```
$ git clone https://www.cse.chalmers.se/~nad/repos/equality/ equality
Cloning into 'equality'...
fatal: repository 'https://www.cse.chalmers.se/~nad/repos/equality/' not found
```
HTTP seems to hang:
```
$ git clone http://www.cse.chalmers.se/~nad/repos/equality/ equality
Cloning into 'equality'...
^C
```

**Comment by andreasabel** [comment]
@nad writes:
> ```agda
> to : Erased (W A P) → W (Erased A) (λ x → Erased (P (erased x)))
> to [ sup x f ] = sup [ x ] λ { [ y ] → to [ f y ] }
> ```
> Does it make sense to allow matching on single-constructor non-indexed data types in an erased context? 

Good question.  If we allow this, then we blur the distinction between inductive and coinductive at runtime (which the GHC backend already does by compiling to Haskell).  Function `to` creates an infinitely deep (canonical) tree `to = sup λ _ -> to` out of nothing.

Another example is:
```agda
data ⊥ : Set where

data E : Set where
  c : E → E

magic : @0 E → ⊥
magic (c e) = magic e
```
At runtime, `magic` is an inhabitant of the empty type created by an infinite (busy) loop.

**Comment by nad** [comment]
> How? HTTPS does not seem to work:

I don't think HTTPS is enabled for our personal web pages…

> HTTP seems to hang:

Perhaps the web server was down. At least it works now.

I suppose I could move the repository to an external hosting service.

**Comment by nad** [comment]
> At runtime, `magic` is an inhabitant of the empty type created by an infinite (busy) loop.

Assuming that you can construct a value of type `E`, which should not be possible in the empty context (if we pretend that Agda is consistent).

**Comment by andreasabel** [comment]
> At least it works now.

No noticeable improvement from my side.  Maybe it only works from within Chalmers or Sweden.

> I suppose I could move the repository to an external hosting service.

Yes, please.

**Comment by nad** [comment]
> Maybe a good moment to test now

It was sufficient to modify one definition (I inlined `_∘_`).

> Maybe it only works from within Chalmers or Sweden.

I have tested that access is not restricted to the Chalmers network. Can you access the [code](http://www.cse.chalmers.se/~nad/listings/equality/Erased.html) [listings](http://www.cse.chalmers.se/~nad/listings/equality/Nat.Binary.html)? Those might be a bit more awkward to move.

**Comment by andreasabel** [comment]
Got it now.
I never had problems accessing the code listings.
Maybe the http access to your repo was just too slow from Germany.

**Comment by nad** [comment]
- [x] The following code should not be accepted:
  ```agda
  postulate
    P    : Set → Set
    p    : (A : Set) → P A
    @0 A : Set

  -- fails : P A
  -- fails = p A

  works : P A
  works = p _
  ```

**Comment by nad** [comment]
- [x] Here is another example that should not be accepted:
  ```agda
  open import Agda.Builtin.Equality

  record _↠_ (A B : Set) : Set where
    field
      to      : A → B
      from    : B → A
      to∘from : ∀ x → to (from x) ≡ x

  record Erased (@0 A : Set) : Set where
    constructor [_]
    field
      @0 erased : A

  open Erased

  -- fails : {A : Set} → A ↠ Erased A
  -- fails = record
  --   { to      = [_]
  --   ; from    = erased
  --   ; to∘from = λ _ → refl
  --   }

  works : {A : Set} → A ↠ Erased A
  works = record
    { to      = [_]
    ; from    = _
    ; to∘from = λ _ → refl
    }
  ```

**Comment by nad** [comment]
Consider the following code:
```agda
open import Agda.Builtin.Nat

record Erased (A : Set) : Set where
  constructor [_]
  field
    @0 erased : A

postulate
  id : {A : Set} → A → A

n : Erased Nat
n = id [ 0 ]
```
When I compile this code using the GHC backend I get the following output for `n`:
```haskell
name18 = "Test.n"
d18 :: T4
d18 = erased
```
It seems as if `n` is completely erased, even if it is only the argument to `[_]` that is marked as erased.

Is this something that I can rely on? Is everything of type `Erased A` erased? I noticed that I had some code of the form `subst … [ … ]`, and I would not like to see traces of this call to `subst` in the compiled output.

(This is something that could be discussed in the documentation of `@0`.)

**Comment by nad** [comment]
- [x] Should the following code be accepted?
  ```agda
  open import Agda.Builtin.Bool

  @0 F : @0 Bool → Set₁
  F true  = Set
  F false = Set
  ```

Edit: Moved to #4173.

**Comment by nad** [comment]
> @nad writes:
> 
> > ```agda
> > to : Erased (W A P) → W (Erased A) (λ x → Erased (P (erased x)))
> > to [ sup x f ] = sup [ x ] λ { [ y ] → to [ f y ] }
> > ```
> > 
> > 
> > Does it make sense to allow matching on single-constructor non-indexed data types in an erased context?
> 
> Good question. If we allow this, then we blur the distinction between inductive and coinductive at runtime (which the GHC backend already does by compiling to Haskell). Function `to` creates an infinitely deep (canonical) tree `to = sup λ _ -> to` out of nothing.

Yes, if you erase the argument completely. However, as far as I have understood Agda retains the argument, but applies the function to a dummy value (or something like that). Thus this kind of erased code should work also in a strict setting.

**Comment by nad** [comment]
- [ ] Another thing to take care of:

  https://github.com/agda/agda/blob/b8d673bc09bc50f4539114ea90e141127ab60bf4/src/full/Agda/TypeChecking/Rules/LHS/Unify.hs#L914-L921

Edit: Moved to #4174.

**Comment by UlfNorell** [comment]
Do we have a test case for that? (cc @andreasabel)

**Comment by nad** [comment]
> * [ ]  Should the following code be accepted?
>   ```agda
>   open import Agda.Builtin.Bool
>   
>   @0 F : @0 Bool → Set₁
>   F true  = Set
>   F false = Set
>   ```

I tried to make Agda accept this code by tweaking the following test:

https://github.com/agda/agda/blob/49ad0b3f0d39c01bc35123478b857e702b29fb9d/src/full/Agda/TypeChecking/Coverage.hs#L1394-L1396

However, I did not find a simple way to figure out if the pattern matching takes place in an erased context. The `envModality` field in the environment does not contain the quantity 0 when the code above is checked. Is the quantity supposed to be 0? The documentation suggests that it should be:

https://github.com/agda/agda/blob/49ad0b3f0d39c01bc35123478b857e702b29fb9d/src/full/Agda/TypeChecking/Monad/Base.hs#L2573-L2583

In fact, the quantity is `Quantityω QωInferred`, which according to the comment is not allowed.

**Comment by nad** [comment]
- [ ] I notice that the following code is accepted:
  ```agda
  postulate
    F : @0 Set → Set
    G : (Set → Set) → Set

  A : Set
  A = G F
  ```
  I guess this makes sense. Is the intention to have some kind of subtyping for `@0`, or is the code accepted by accident? My guess would be the latter, because the following code is also accepted:
  ```agda
  postulate
    F : Set → Set
    G : (@0 Set → Set) → Set

  A : Set
  A = G F
  ```
  This code should not be accepted. Here is an example without postulates that Agda compiles without complaints:
  ```agda
  open import Agda.Builtin.Bool

  not : Bool → Bool
  not true  = false
  not false = true

  magic : (@0 Bool → Bool) → @0 Bool → Bool
  magic f n = f n

  @0 b₁ : Bool
  b₁ = true

  b₂ : Bool
  b₂ = magic not b₁
  ```
  If you load this code in GHCi (8.6.5) and evaluate the term corresponding to `b₂`, then you get `True` as the result. If you remove the `@0` annotations and do the same experiment, then you get `False` instead.

Edit: Moved to #4175.

**Comment by nad** [comment]
I created separate tickets for some of the remaining problems. This ticket is now mainly about documentation.

**Comment by jespercockx** [comment]
@andreasabel Do you have time to work on this issue and the two related ones (#4137 and #4172) or do you need some help with them?

**Comment by nad** [comment]
Those two issues have been closed now. What remains is to document `@0`:
* What are the typing rules?
  * Some examples might be nice.
  * For the theory one could perhaps refer to Bob's paper, and mention the differences:
    * Erased definitions.
    * Unification (#4174).
    * Support for more data types, with pattern matching allowed in some cases (empty types, #4172).
    * Anything else?
* How do the two compiler backends treat the annotations?
  * Above I wrote that "It seems as if `n` is completely erased, even if it is only the argument to `[_]` that is marked as erased". It would be nice to document the erasure process well enough that users know what they can rely on.
  * Does the JS backend erase anything?
  * There is no support for compiling Cubical Agda, but we could mention that we do not know if it is possible to combine Cubical Agda with erasure in a reasonable way (even though we allow people to use `@0` in Cubical Agda).

**Comment by jespercockx** [comment]
Maybe some inspiration could be taken from today's blog post from @edwinb on erasure and linearity: https://www.type-driven.org.uk/edwinb/linearity-and-erasure-in-idris-2.html.

**Comment by UlfNorell** [comment]
I wrote some documentation

**Comment by asr** [comment]
I added the label `documented-in-changelog` because the issue was documented in the CHANGELOG (good) and it should not be listed by the `closed-issues-for-milestone` program.
