### ISSUE TITLE
Agda.TypeChecking.Free.Old is bit-rotting

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3860]
I had a look into `Agda.TypeChecking.Free` where it says that module `Old` https://github.com/agda/agda/blob/master/src/full/Agda/TypeChecking/Free/Old.hs serves as a specification and `Lazy` https://github.com/agda/agda/blob/master/src/full/Agda/TypeChecking/Free/Lazy.hs as the implementation.  Their congruence is tested by `test/Internal/TypeChecking/Free.hs` https://github.com/agda/agda/blob/master/test/Internal/TypeChecking/Free.hs .
However, `Old` is falling behind `Lazy`, e.g., for `Dom`:
https://github.com/agda/agda/blob/af3c1cf76c8c4e7f9d11102f8a7ec69ad403bea8/src/full/Agda/TypeChecking/Free/Lazy.hs#L349-L350
vs.
https://github.com/agda/agda/blob/af3c1cf76c8c4e7f9d11102f8a7ec69ad403bea8/src/full/Agda/TypeChecking/Free/Old.hs#L323-L324
This goes unnoticed because also the generators for internal syntax in https://github.com/agda/agda/blob/master/test/Internal/TypeChecking/Generators.hs also do not get extended with new syntax arriving.
But, further, the `Old` analysis has fallen back in precision, as flexible occurrences are now accounted for by meta variable in `Lazy`.

Question: is it worthwhile keeping `Old`?  It does not seem terribly useful as a specification, since follow the same pattern for free variable generation as `Lazy`.  In essence, the syntax traversal is just duplicated, once implemented in `Lazy`, once in `Old`.  No independent specification, really.

As can be read from my suggestive question, I am tending towards retiring `Old`.
@UlfNorell @nad @jespercockx @Saizan ?

**Comment by UlfNorell** [comment]
> I am tending towards retiring `Old`

👍

**Comment by jespercockx** [comment]
I'm fine with retiring `Old`, I never really saw the point of it (except maybe as some kind of migratory measure when the new free variable checker was still, well, new).

**Comment by andreasabel** [comment]
Ok, I remove it.
