### ISSUE TITLE
Semantics of `Flexible MetaSet` in free variable occurrence

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3861]
A flexible variable occurrence is decorated by a set of meta variables, see:
https://github.com/agda/agda/blob/af3c1cf76c8c4e7f9d11102f8a7ec69ad403bea8/src/full/Agda/TypeChecking/Free/Lazy.hs#L60-L63
This was originally introduced by @jespercockx in f305ee9d05b26dd5e4f74a12927e0eabd4988a8d to use in REWRITE pattern matching.  What is its intended semantics?

The `FlexRig` type is (supposed to be) a semiring with addition combining information from different subterms and multiplication combining the context of an occurrence with the occurrence.  Currently, multiplication `composeFlexRig` is explicitly implemented using the union of the metasets. https://github.com/agda/agda/blob/af3c1cf76c8c4e7f9d11102f8a7ec69ad403bea8/src/full/Agda/TypeChecking/Free/Lazy.hs#L79-L82
For example `x` occurs `Flexible [X,Y]` in `X (Y x)` (where capitals denote meta vars).  Spelled out, `x` occurs `Flexible ms` if there is a chain of meta-applications given by metas `ms` from `x` to the current point of view.  Is this the intended semantics ("and")?

The addition is currently just `Ord.max`, which does something random when the meta sets differ:
https://github.com/agda/agda/blob/af3c1cf76c8c4e7f9d11102f8a7ec69ad403bea8/src/full/Agda/TypeChecking/Free/Lazy.hs#L106-L109
How should `x` occur e.g. in `(X x , Y x)` ("or")?

The _free_ semantics would use a semiring instead of a meta set.  However, what we actually need here depends on the intended use.  @jespercockx?

P.S.: I am currently working on `Free`, so let me implement the solution we discuss here.

UPDATE: My commit 031a490c05cee4ec6153975b5931fec66efbbec6 contains a tentative replacement for `Ord.max` called `addFlexRig`, also using union of meta sets, but it does not form a semiring, naturally.

**Comment by jespercockx** [comment]
Well the comment of the constructor says `In arguments of metas.` The set is just there to keep track in the arguments of **which** metas the variable occurs. This allows us to retry the free variable check when one of these metas is instantiated, hopefully making the variable no longer free.

At least that's the theory, in practice most of this information is currently forgotten as there is only room for a single metavariable in a `Blocked` tag.

In theory, the `MetaSet` could be replaced by a richer (free?) semiring structure which allows us to keep track of precisely when we should retry the check (e.g. we should retry if `m1` AND `m2` are instantiated, OR if `m3` is instantiated). But this would currently be a complete waste because of the point above.

**Comment by andreasabel** [comment]
Thanks!  So then `x` should also occur `Flexible [X, Y]` in `(X x, Y x)`.  Addition and multiplication is the same operation on`MetaSet`.  The semantics is that the status of variable `x` can change when one of the metas gets instantiated.  I'll put that into the code documentation.

A test case where my new implementation of addition (`addFlexRig`) makes a difference is probably hard to cook up.

**Comment by andreasabel** [comment]
The `MetaSet` in `Flexible` sabotages the semiring properties of `VarOcc`, for example distributivity:
```
  Flex ms1 * (Flex ms2 + StronglyRigid) = Flex ms1 * StronglyRigid 
    = Flex ms1
```
but
```
  Flex ms1 * Flex ms2 + Flex ms1 * StronglyRigid = Flex (ms1 <> ms2) + Flex ms1 
    = Flex (ms1 <> ms2)
```
The laws could be salvaged if the `MetaSet` was a separate component that does not get destroyed by aggregation with `StronglyRigid`, but it would be less precise.  (Of course, the `MetaSet` would be ignored unless the final outcome was `Flexible`.


Another way to fix this could be to let `Flex ms1 * Flex ms2 = Flex ms1`, making `*` non-commutative (which is not unnatural).  This would mean that only the outermost flexible metas are recorded.  E.g., the occurrence of `x` in `X (Y x)` would be `Flex [X]`.  But maybe this is less useful w.r.t. the intended semantics, @jespercockx ? Does solving `Y` help to make progress in the REWRITE case?  The variable `x` can disappear, but if it remains it will still be blocked by `X`.  If you can only record one meta-variable in the blocking, maybe discarding `Y` would be as useful as keeping it...

**Comment by jespercockx** [comment]
Well, if we look at the occurrences of `x` in `c1 (_1 (_2 x) (c3 x))` and `c2 (_1 (_2 x)) (_1 (c3 x))`, then in both cases the free variable can only disappear when `_1` is instantiated, `_2` only comes into the picture later. But looking just at `c (_1 (_2 x))`, we should retry if EITHER of `_1` or `_2` is instantiated. So it seems that distributivity just doesn't hold here.

Of course we could do as you suggest and only keep the first meta, but this would be somewhat restrictive if we ever decide to make the blocking tags more precise.

**Comment by andreasabel** [comment]
I decided to stick to the current implementation, where `MetaSet`s are unioned for both semiring operations; thus, `FlexRig`is not distributive.
However, the types are now parametrized what to put in `Flexible`, and e.g. for `()` (equals the empty `MetaSet`) there is no problem with distributivity.
TODO: adapt internal tests for the parameterized versions (or some of their instances) `FlexRig'`, `VarOcc'`.

**Comment by andreasabel** [comment]
Fixed the TODO and added semiring/module properties to test/Internal/TypeChecking/Free.
