### ISSUE TITLE
Unicode input for symbols with multiple characters

### ISSUE THREAD

**Issue by pnlph** [agda/agda#3868]
## Description
Not possible to keep the unicode input mode for multiple characters.
## Current behavior
Eg `≡⟨⟩` consists of unicode symbols `\==`, `\<` and `\>`  and the sequence to introduce it in the keyboard is:
`\== <space> <backspace> \< <space> <backspace> \> <space>`
## Possible solutions
Allow to stay in unicode input mode by introducing a backslash. The introduction sequence would result in:
`\==\<\> <space>`

Allow symbols of multiple characters in the unicode palette. The introduction sequence would result in:
`\==<> <space>`

**Comment by guillaumebrunerie** [comment]
> Allow to stay in unicode input mode by introducing a backslash. The introduction sequence would result in:
> `\==\<\> <space>`

This already works for me and I haven’t changed anything to my Agda.

**Comment by pnlph** [comment]
OK, sorry i am not using emacs. Maybe is it an issue for @banacorn [agda-mode](https://github.com/banacorn/agda-mode) for Atom?

**Comment by guillaumebrunerie** [comment]
Ah ok, I guess you should report it to the bug tracker there then, as it is not an issue for the official agda-mode for emacs.

**Comment by gallais** [comment]
Oh, I misread the original issue and I thought the feature request was for
`\==<>` to result in `≡⟨⟩`.

**Comment by guillaumebrunerie** [comment]
> Oh, I misread the original issue and I thought the feature request was for
> `\==<>` to result in `≡⟨⟩`.

I don’t see how that could work, it would create way too many ambiguities.

**Comment by gallais** [comment]
We could at least support the cases where there is no ambiguity.
After typing `\==`, the only possible next characters according to the input mode
are `=` and `n`. Anything else (apart from a space) could be interpreted as the start
of a new token for a unicode symbol.

**Comment by guillaumebrunerie** [comment]
Right, but then it means that symbols consisting of both Unicode and ASCII characters would sometimes take longer to type, so it’s not clear if it would be better.
For instance names like `_≡_`, `_∙_`, `×-cong`, `x≈y` would take more keystrokes.

**Comment by nad** [comment]
> `\== <space> <backspace> \< <space> <backspace> \> <space>`

If you want to terminate the input of a symbol without inserting a new character into the buffer, then you can type `C-SPC` (at least with some configurations).

**Comment by nad** [comment]
And in this case you can just type `\==\<\> C-SPC`.
