### ISSUE TITLE
Type inference failure

### ISSUE THREAD

**Issue by palkarz** [agda/agda#3873]
In the following example Agda is unable to infer the type of the implicit argument `w`. 
``` Agda
open import Agda.Builtin.Nat

record World (A : Set) : Set₁ where
  field
    relation : A → A → Set
    sym : ∀ {x y} → relation x y → relation y x
open World

sym-implicit : ∀ {w} {x y : Nat} → relation w x y → relation w y x
sym-implicit {w} {x} {y} x~y = sym w x~y

example : ∀ {w} {x y : Nat} → relation w x y → relation w y x
example {w} {x} {y} eq =  sym-implicit {x = x} {y} eq 
```
I am not sure if this is a bug, but this kind of inference certainly seems (at least from a noob's perspective) like something Agda should be able to cope with.

**Comment by andreasabel** [comment]
It works if you make `w` an instance argument:
```agda
open import Agda.Builtin.Nat

record World (A : Set) : Set₁ where
  field
    relation : A → A → Set
    sym : ∀ {x y} → relation x y → relation y x
open World

sym-implicit : ∀ {{w}} {x y : Nat} → relation w x y → relation w y x
sym-implicit {{w}} {x} {y} x~y = sym w x~y

example : ∀ {{w}} {x y : Nat} → relation w x y → relation w y x
example {{w}} {x} {y} eq = sym-implicit {x = x} {y} eq
```
The reason it does not work with a hidden argument is that then only unique solutions are constructed.  However, the `relation` field alone does not determine the `World` record, there is also the `sym` field!
With an instance argument, Agda tries to construct the solution from existing instances in scope, and it finds instance parameter `{{w}}` of `example` that can be passed to `sym-implicit`.

**Comment by andreasabel** [comment]
@palkarz : The Agda mailing list is a good first source of inquiry in such questions!  There are lots of nice and helpful readers eager to answer.

**Comment by palkarz** [comment]
Thank you, @andreasabel. In the future I will use the mailing list for questions like this, but with your permission I would like to get through with this one here.

Ironically, this problem arose during a rewrite of a code that uses a lot of instance arguments in order to overcome some performance issues and limitations (like inability to provide functions as instances). But that's beside the point.

I didn't understand the uniqueness argument. Why does the `relation` field have to determine the `World` uniquely? Isn't it just a projection from the `World` that has been passed to a function as an [implicit] argument? Type signatures for `sym-implicit` and `example` seem to [definitionally] ensure that the world stays the same between the argument and the return value so to me it does seem to be uniquely determined and therefore I assumed that Agda would come to the same conclusion... What am I missing?

**Comment by palkarz** [comment]
OK, I think it finally dawned on me. Agda only infers implicit arguments if they are uniquely predetermined by the explicit ones and does not do it if there is any room for uncertainty. So if it deduces that there is one and only one way to build the AST of the implicit arguments from the explicit ones, it does the inference. So while with instance arguments we say, "Hey, there is a unique instance of this type that **I** must give  to you, with implicit arguments we say, "Hey, there is a unique instance of this type that **you** must give to me."

**Comment by UlfNorell** [comment]
To make it extra clear, here are two valid (and different!) solutions for the implicit argument:
```agda
example₁ : ∀ {w} {x y : Nat} → relation w x y → relation w y x
example₁ {w} {x} {y} eq =  sym-implicit {w = w} {x = x} {y} eq

example₂ : ∀ {w} {x y : Nat} → relation w x y → relation w y x
example₂ {w} {x} {y} eq =
  sym-implicit {w = record{ relation = relation w
                          ; sym      = λ x~y → sym w (sym w (sym w x~y)) }}
               {x = x} {y} eq
```
