### ISSUE TITLE
Proof search can not  split lambda

### ISSUE THREAD

**Issue by guilhermehas** [agda/agda#3875]
```haskell
data ¬f : Set where
  res : (f : Bool → Bool) → f true ≡ false → f false ≡ true → ¬f

getf : ¬f
getf = {!-c!}
```

I tried the proof search `Ctrl+C Ctrl+A` in emacs in this simple example and it can not find the solution because it has to split a lambda function.

**Comment by gallais** [comment]
No one is maintaining auto anymore because the code is basically incomprehensible.
So this probably will not happen anytime soon.

**Comment by andreasabel** [comment]
Agsy is being replaced by Mimer which does not case-split if I am not mistaken.
