### ISSUE TITLE
Dotted variables / not in scope variables

### ISSUE THREAD

**Issue by pnlph** [agda/agda#3876]
I think in old versions of Agda, there was this concept of dotted variables that was notated:
`.n : ℕ`
But now the notation for the latest Agda 2.6 is:
`n : ℕ  (not in scope)`
I could not find anything about this in the docs, have dotted and not in scope variables the same meaning? What was the background of this change?

**Comment by jespercockx** [comment]
From the [changelog](https://github.com/agda/agda/blob/master/CHANGELOG.md#interaction-and-error-reporting):

> Out-of-scope identifiers are no longer prefixed by a '.' dot [Issue #3127]. This notation could be confused with dot patterns, postfix projections, and irrelevance. Now Agda will do its best to make up fresh names for out-of-scope identifiers that do not conflict with any existing names. In addition, these names are marked as "(out of scope)" when printing the context.
> 
> The change affects the printing of terms, e.g. in error messages and interaction, and the parsing of out-of-scope variables for case splitting (C-c C-c in emacs).

**Comment by pnlph** [comment]
Thank you so much. This is exactly the information i was looking for.

**Comment by pnlph** [comment]
Just noticed that the changelog was split.
Here is the link where you can find the reference above:
[Release notes 2.6.0](https://github.com/agda/agda/blob/master/doc/release-notes/2.6.0.md)

And the split commit:
064095e
