### ISSUE TITLE
Case splitting should respect existing input

### ISSUE THREAD

**Issue by mietek** [agda/agda#3878]
Before case splitting on `m`:
```agda
open import Data.Fin using (Fin ; zero ; suc)
open import Data.Nat using (ℕ ; zero ; suc)

foo : ℕ → ℕ → ℕ
foo zero m = {!!}
foo (suc n) m = {!!}
```
After case splitting on `m`:
```agda
open import Data.Fin using (Fin ; zero ; suc)
open import Data.Nat using (ℕ ; zero ; suc)

foo : ℕ → ℕ → ℕ
foo Data.Fin.0F Data.Fin.0F = {!!}
foo Data.Fin.0F (suc m) = {!!}
foo (suc n) m = {!!}
```

There are at least three problems here.  **This issue is about problem 1.**

1. **Case splitting on `m` changes a part of the line that is not `m`.**
2. Pattern synonyms are imported even though they are not requested. (https://github.com/agda/agda/issues/3879)
3. The Agda standard library includes pattern synonyms in `Data.Fin` without considering the impact of problems 1 and 2. (https://github.com/agda/agda-stdlib/issues/830)

Related issues:
- https://github.com/agda/agda/issues/575
- https://github.com/agda/agda/issues/2414
- https://github.com/agda/agda/issues/2589
- https://github.com/agda/agda/issues/3178

Checked in Agda 2.6.0.1 with standard library 1.1.

**Comment by jespercockx** [comment]
With the fix of #3879 the problem here seems to be fixed as well.
