### ISSUE TITLE
Only unqualified pattern synonyms should be used for resugaring

### ISSUE THREAD

**Issue by mietek** [agda/agda#3879]
Before case splitting on `m`:
```agda
open import Data.Fin using (Fin ; zero ; suc)
open import Data.Nat using (ℕ ; zero ; suc)

foo : ℕ → ℕ → ℕ
foo zero m = {!!}
foo (suc n) m = {!!}
```
After case splitting on `m`:
```agda
open import Data.Fin using (Fin ; zero ; suc)
open import Data.Nat using (ℕ ; zero ; suc)

foo : ℕ → ℕ → ℕ
foo Data.Fin.0F Data.Fin.0F = {!!}
foo Data.Fin.0F (suc m) = {!!}
foo (suc n) m = {!!}
```

There are at least three problems here.  **This issue is about problem 2.**

1. Case splitting on `m` changes a part of the line that is not `m`. (https://github.com/agda/agda/issues/3878)
2. **Pattern synonyms are imported even though they are not requested.**
3. The Agda standard library includes pattern synonyms in `Data.Fin` without considering the impact of problems 1 and 2. (https://github.com/agda/agda-stdlib/issues/830)

Checked in Agda 2.6.0.1 with standard library 1.1.

**Comment by gallais** [comment]
The pattern synonyms are not actually imported here: if you try to use them,
you will get a scoping error. The problem is that Agda still uses them for
resugaring even though they are not in scope (hence the fully qualified name).

**Comment by gallais** [comment]
There clearly is the intention of filtering out the pattern synonyms which are
not in scope:

https://github.com/agda/agda/blob/4e989c1a0587e38cf35dd936b4e2dd699a9260b2/src/full/Agda/Syntax/Translation/AbstractToConcrete.hs#L1605

However `open import A using ()` does bring everything in scope in `A` in the
current scope under an `A.` qualifier. If only we had #3727!

**Comment by mietek** [comment]
Is there a method by which the user can prevent unrequested pattern synonyms from being brought into scope under a fully-qualified name?  If not, then can we refocus this issue on creating such a method?

**Comment by gallais** [comment]
This is why I mentioned #3727

**Comment by nad** [comment]
> Is there a method by which the user can prevent unrequested pattern synonyms from being brought into scope under a fully-qualified name?

```agda
import M hiding (pattern-synonym)
open M
```

**Comment by mietek** [comment]
Thanks, @nad.

So, hiding while importing, _then_ opening works:
```agda
import Data.Fin hiding (0F)
open Data.Fin using (Fin ; zero ; suc)
```
But, hiding and opening while importing doesn’t work:
```agda
open import Data.Fin hiding (0F) using (Fin ; zero ; suc)
-- Hiding 0F has no effect
-- when scope checking the declaration
--   open import Data.Fin using (Fin; zero; suc) hiding (0F)
```
Shouldn’t both methods work the same way?

**Comment by mietek** [comment]
Following discussion with @gallais and @Blaisorblade, I understand that identifiers can be in three states:
- accessible unqualified;
- accessible fully-qualified;
- inaccessible.

@nad shows the method to make an identifier inaccessible.

The error in my previous comment is caused by the use of `hiding` and `using` at the same time.  If we remove `using`, we get `open import Data.Fin hiding (0F)`, which makes the identifier available fully-qualified, and is equivalent to the following code:
```agda
import Data.Fin
open Data.Fin hiding (0F)
```

**Comment by mietek** [comment]
@Blaisorblade suggested that perhaps pattern synonyms that are accessible fully-qualified shouldn’t be used for resugaring.  Can we consider this suggestion?
