### ISSUE TITLE
Refactor: for Map/Set/HashSet `elem` is O(n) while `member` is O(logn)

### ISSUE THREAD

**Issue by gallais** [agda/agda#3881]
From https://chshersh.github.io/type-errors:

> The problem here is that elem for both Set and HashSet works in O(n) time while member works in O(log n) time and it’s quite easy to accidentally use slow elem instead of fast member function.

Worth checking how many of the occurences of `elem` can be replaced with `member`.

**Comment by L-TChen** [comment]
I didn't find any noticeable improvement after replacing `elem` by `member`. 

A related issue I can see here is that lists are used almost everywhere, but lists are rarely the right choice as a sequential container. The benchmark [here](https://github.com/haskell-perf/sequences) shows that `Data.Sequence`, i.e. finger tree, outperforms `List` in every test but two.

Try to use `Data.Sequence`?

**Comment by andreasabel** [comment]
I did some work in 7c6ca42965a4c8ffb4f9f8cccfe5cf7bf100d054 to replace linear lookup in list by the logarithmic lookup in sets.

**Comment by asr** [comment]
@andreasabel, for keeping record of this good practice, please add an entry for the new function `hasElem` in the CHANGELOG [API](https://github.com/agda/agda/blob/754423526350459a7cdbc876da7eec534c52e4af/CHANGELOG.md#api) section.
