### ISSUE TITLE
Forcing translation produces segfaulting program

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3903]
While trying to understand the forcing translation with @jespercockx, we found out that it actually does not work.  The forcing translation tries to relocate a match happening in a forced position to a non-forced position.  In the example below, we have a match `cons zero ...` but pattern `zero` is in a forced position.  The forcing translation now tries to reconstruct a match against `zero` by transforming (parts of) a dot pattern into an actual pattern.  However, it blindly grabs the first opportunity.  In the example below, there are two possibilities, and Agda takes the wrong one, leading to a segfaulting compiled code.  And in fact, without type information there is no way for Agda to decide which is the correct one.  So, if it works, it is pure luck.
```agda
open import Agda.Builtin.Unit
open import Agda.Builtin.Bool
open import Agda.Builtin.Nat
open import Agda.Builtin.Equality
open import Agda.Builtin.IO
open import Common.String

postulate
  putStr : String → IO ⊤

{-# FOREIGN GHC import qualified Data.Text.IO #-}
{-# COMPILE GHC putStr = Data.Text.IO.putStr #-}

data Sing : Nat → Set where
  sing : Sing zero

data Vec : Nat → Set where
  nil : Vec zero
  cons : ∀ n → Vec n → Vec (suc n)

isTailNil : ∀ m n → Sing m → Vec n → Bool
isTailNil .0 .1 sing (cons zero v) = true  -- two `zero`s are buried in the dot patterns, which to resurrect?
isTailNil _ _ _ _ = false

shouldBeFalse = isTailNil 0 2 sing (cons 1 (cons 0 nil))

isFalse : false ≡ shouldBeFalse
isFalse = refl

magic : false ≡ true → String
magic ()

f : (b : Bool) → false ≡ b → String
f false eq = "Phew!"
f true  eq = magic eq

main = putStr (f shouldBeFalse refl)
```
The compiled program crashes with:
```
FoolForcing: Agda: unreachable code reached.
CallStack (from HasCallStack):
  error, called at ./MAlonzo/RTE.hs:46:23 in main:MAlonzo.RTE
```
At least for this example, this seems to be a regression.  It worked correctly in Agda-2.5.4.2.  (How did previous Agda do this forcing translation?)

From Agda-2.6.0, the forcing translation produces a match on the wrong (first) argument of `d20`.
```haskell
name20 = "FoolForcing.isTailNil"
d20 :: Integer -> Integer -> T4 -> T8 -> Bool
d20 v0 v1 v2 v3 = du20 v0 v3
du20 :: Integer -> T8 -> Bool
du20 v0 v1
  = let v2 = MAlonzo.Code.Agda.Builtin.Bool.C8 in
    case coe v1 of
      C14 v4
        -> case coe v0 of
             0 -> coe MAlonzo.Code.Agda.Builtin.Bool.C10
             _ -> coe v2
      _ -> coe v2
```
Agda-2.5.4.2 produces the correct code, matching on the second argument of `d20`:
```haskell
name20 = "FoolForcing.isTailNil"
d20 :: Integer -> Integer -> T4 -> T8 -> Bool
d20 v0 v1 v2 v3 = du20 v1 v3
du20 :: Integer -> T8 -> Bool
du20 v0 v1
  = let v2 = MAlonzo.Code.Agda.Builtin.Bool.C8 in
    case coe v1 of
      C14 v4
        -> case coe v0 of
             1 -> coe MAlonzo.Code.Agda.Builtin.Bool.C10
             _ | coe (geqInt (coe v0) (coe (1 :: Integer))) -> coe v2
             _ -> coe v2
      _ -> coe v2
```

**Comment by andreasabel** [comment]
Blocking issue #3898.

**Comment by nad** [comment]
Now I encountered the following error message:
```
Uh oh. I can't figure out where to move the forced pattern
(nothing).
```
However, I have two occurrences of `nothing` in this clause, and the error's range includes both of them.

**Comment by martinescardo** [comment]
I am also getting "Uh oh" in patterns `refl (x , y)` where my `refl` has its argument explicit, with Agda 2.6.1-856415f. With Agda 2.6.0.1 it works fine.

**Comment by asr** [comment]
I added the label `documented-in-changelog` because the issue was documented in the CHANGELOG (good) and it should not be listed by the `closed-issues-for-milestone` program.
