### ISSUE TITLE
Turn off tasty ansi-tricks on travis

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3905]
tasty 1.2.2 now has an option `--ansi-tricks=false` that could improve rendering of our testsuite output on travis, see https://github.com/feuerbach/tasty/issues/250#issuecomment-492512782 .

Task: try this out for running our testsuite travis.  This should remove the garbling of the output.

**Comment by L-TChen** [comment]
After upgrading `tasty-silver` (which is actually the test runner used by `agda-test`) to 3.1.13, it works as expected (see https://travis-ci.org/agda/agda/jobs/557936795 for example). 

Closed now.
