### ISSUE TITLE
Only run stack test against the latest GHC version 

### ISSUE THREAD

**Issue by L-TChen** [agda/agda#3913]
Unlike cabal users who may be reluctant or not able to upgrade their system GHC, stack users install packages in an isolated environment by default and they (should be able to) compile Agda always with the latest GHC supported by Agda. 

Hence, to save some time on Travis CI, I propose to run the stack test against the latest GHC only on Travis. 

A more radical proposal is to urge users (and developers) to compile Agda through `stack` only so that we can save more time on testing and development. I know `cabal` is still popular among main Agda developers, though. :-)

**Comment by asr** [comment]
We use `stack` for testing different flags of Agda which are not tested with `Cabal`. So we need to run `stack` on all GHC versions supported by Agda.
