### ISSUE TITLE
Heterogeneous equality without-K

### ISSUE THREAD

**Issue by amp12** [agda/agda#3916]
I know that heterogeneous equality
```
data _≡≡_ {a}{A : Set a} (x : A) : {B : Set a} → B → Set a where
   refl : x ≅ x
```
is not very useful without Axiom K. But nevertheless I need it. Agda --without-K will not accept the above definition, complaining about universe levels, but will accept
```
data _≡≡_ {a} {A : Set a} (x : A) : {B : Set a} → B → Set (lsuc a) where
   refl : x ≅ x
```
But that makes it annoying to compare this with homogeneous equality
```
data _≡_ {a}{A : Set a}(x : A) : A → Set a where
  refl : x ≡ x
```
What has --with-K/--without-K got to do with the universe level of this definition? Surely it would not break things to allow the definition of ≡≡  without K to be at level l rather than suc l?

**Comment by jespercockx** [comment]
Heterogeneous equality is basically a (dependent) pair of a proof of equality between the types + a proof of equality between the terms (dependent on the first proof). But with `--without-K`, an equality has to live in the same universe level (or greater) as the elements being equated (this is a recent change, see https://github.com/agda/agda/issues/3420).

**Comment by amp12** [comment]
> On 15 Jul 2019, at 16:35, Jesper Cockx <notifications@github.com> wrote:
> 
> Heterogeneous equality is basically a (dependent) pair of a proof of equality between the types + a proof of equality between the terms (dependent on the first proof). But with --without-K, an equality has to live in the same universe level (or greater) as the elements being equated
> 
That is just _a_ way to define heterogeneous equality in terms of other things and clearly that definition should raise the universe level by one. 

However, I was referring to a specific inductive definition of heterogeneous equality, for which I can see no semantic reason for universe-level-raising (irrespective of univalence).
>  (this is a recent change, see #3420 <https://github.com/agda/agda/issues/3420>).
> 
> 
Indeed, and for me clearly not a very convenient one. Is there any chance it could be changed into something that can be switched off with a specific OPTION?

Andy

**Comment by jespercockx** [comment]
I don't really have a strong opinion either way; I guess we should ask @nad what he thinks since he suggested the change.

**Comment by andreasabel** [comment]
> However, I was referring to a specific inductive definition of heterogeneous equality, 
> ```
> data _≡≡_ {a}{A : Set a} (x : A) : {B : Set a} → B → Set a where
>    refl : x ≅ x
> ```
@amp12 : How do you model this as a parameterized inductive type?  Currently I am under the impression that for `--without-K` we do not accept inductive _families_ as primitive but seek to explain them by inductive types (of higher kind).

It should be possible to get your the definition through by turning the universe check off.  However, this does not work currently, which is a __bug__.  I am working on it.

**Comment by andreasabel** [comment]
@amp12 : With my latest patch, Agda accepts your definition under the pragma that disables universe checking for the following data definition:
```agda
  {-# NO_UNIVERSE_CHECK #-}
  data _≅_ {a}{A : Set a} (x : A) : {B : Set a} → B → Set a where
     refl : x ≅ x
```

**Comment by amp12** [comment]
> On 16 Jul 2019, at 06:07, Andreas Abel <notifications@github.com> wrote:
> 
> However, I was referring to a specific inductive definition of heterogeneous equality,
> 
> data _≡≡_ {a}{A : Set a} (x : A) : {B : Set a} → B → Set a where
>    refl : x ≅ x
> @amp12 <https://github.com/amp12> : How do you model this as a parameterized inductive type? Currently I am under the impression that for --without-K we do not accept inductive families as primitive but seek to explain them by inductive types (of higher kind).
> 

I was thinking of the classical set theoretic model of extensional type theory where x ≡≡ y is very small and could even live in Set lzero.

Andy

**Comment by amp12** [comment]
> On 16 Jul 2019, at 06:50, Andreas Abel <notifications@github.com> wrote:
> 
> @amp12 <https://github.com/amp12> : With my latest patch, Agda accepts your definition under the pragma that disables universe checking for the following data definition:
> 
>   {-# NO_UNIVERSE_CHECK #-}
>   data _≅_ {a}{A : Set a} (x : A) : {B : Set a} → B → Set a where
>      refl : x ≅ x


Is there documentation on NO_UNIVERSE_CHECK? — what is usually checked about universes that this switches off?

Andy

**Comment by jespercockx** [comment]
It seems to be missing from the documentation (my bad). From the changelog:

>     New pragma {-# NO_UNIVERSE_CHECK #-}.
> 
>     The pragma {-# NO_UNIVERSE_CHECK #-} can be put in front of a data or record type to disable universe consistency checking locally. Example:
> 
>       {-# NO_UNIVERSE_CHECK #-}
>       data U : Set where
>         el : Set → U
> 
>     Like the similar pragmas for disabling termination and positivity checking, {-# NO_UNIVERSE_CHECK #-} cannot be used with --safe.

So basically, it turns off the check that the sort of each of the constructor argument types should fit in the sort of the datatype.

**Comment by nad** [comment]
> I guess we should ask @nad what he thinks since he suggested the change.

I'm not an expert on this topic. The following discussion about the Coq option `-indices-matter` seems relevant: ["Do indices matter?"](https://github.com/HoTT/HoTT/issues/842).

**Comment by Saizan** [comment]
> > Andreas: [...] How do you model this as a parameterized inductive type? Currently I am under the impression that for --without-K we do not accept inductive families as primitive but seek to explain them by inductive types (of higher kind).

>I was thinking of the classical set theoretic model of extensional type theory where x ≡≡ y is very small and could even live in Set lzero. Andy

That's a fine model, but it's also one that would verify ```--with-K```: internally you can show that ```x ≡≡ y``` is equivalent to the pair of equalities formulation, so the semantics of the two can't be too different.

I think the confusion is that the ```--without-K``` flag is actually meant to keep you consistent with univalence, not just forbid things that directly rely on the K axiom or would imply it.

Maybe there should be two flags, with one just forbidding the LHS constraint solving strategies that rely on K?

**Comment by jespercockx** [comment]
How about the assumptions in the termination checker that rely on K (crf https://github.com/agda/agda/issues/1023)?

**Comment by Saizan** [comment]
> How about the assumptions in the termination checker that rely on K (crf #1023)?

That issue also seems to be more about consistency with some form of univalence rather than use of K. 
However it is a bit fuzzy what "relies on K" means since we never explicitly translate into J and K. I'm also not sure how much use this new flag would get.

**Comment by jespercockx** [comment]
It's not clear to me what the actual issue is here; at least Agda's current behaviour makes sense to me. So I'm going to close this now, please feel free to reopen if you have a concrete suggestion of what criterion `--without-K` should use instead.
