### ISSUE TITLE
cached type checking slow if comments are edited, but not if code is edited

### ISSUE THREAD

**Issue by martinescardo** [agda/agda#3921]
In a large literate file, if we change Agda code, type checking is reasonably fast, presumably because of caching. However, counter-intuitively, if we change something outside the code environments, then everything is type checked from scratch and takes a long time. My extended MGS lecture notes are an example (https://github.com/martinescardo/HoTT-UF-Agda-Lecture-Notes/blob/master/HoTT-UF-Agda.lagda).

**Comment by andreasabel** [comment]
A straightforward implementation of caching would roughly type-check everything below the point of the topmost edit, regardless whether code or comments are edited.  Is this the behavior you observe, or do you observe something different?
(A more detailed test report would be appreciated.)

**Comment by nad** [comment]
I failed to reproduce the reported behaviour.

Consider the following code:
```latex
First comment.

\begin{code}
open import Agda.Builtin.Equality
open import Agda.Builtin.Nat

fib : Nat → Nat
fib 0             = 0
fib 1             = 1
fib (suc (suc n)) = fib n + fib (suc n)

slow : fib 28 ≡ 317811
slow = refl
\end{code}

Second comment.
```
Loading the file takes a little time. Reloading after editing the first comment is slow, but reloading after editing the second comment is fast.

**Comment by jespercockx** [comment]
As this couldn't be reproduced, I'm closing this now.
