### ISSUE TITLE
Internal error when mixing implicit and explicit mutual blocks

### ISSUE THREAD

**Issue by JLimperg** [agda/agda#3932]
Code:

```agda
data Unit : Set where
  tt : Unit

f : Unit

mutual
  f = tt
```

Error message:

```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Monad/State.hs:303
```

Agda HEAD (`master@a9dc9bea224e86bbe46a42b89e72910522636e7c`).

**Comment by gallais** [comment]
Fails with "Missing definition for f" (pointing at the type declaration) in 2.5.4.2

**Comment by andreasabel** [comment]
Nice catch!

**Comment by andreasabel** [comment]
```agda
mutual
  A : Set1

  mutual
    A = Set
```
gives a different internal error:
```
Location of the error: src/full/Agda/Syntax/Concrete/Definitions.hs:1371
```

Bisecting* blames my commit 5ffac504f5a83d881013e333758bb096c010d44a

  Date:   Sun Oct 28 17:54:15 2018 +0100
  [ #3246 ] many more declarations allowed in mutual blocks

*I ran `agda-bisect --cabal-option '--ghc-options=-O0' --must-fail --no-internal-error --good v2.5.4.2 --bad v2.6.0 Issue3932.agda` which was reasonably fast thanks to `-O0`.

**Comment by andreasabel** [comment]
According to `agda-bisect`, the OP
```agda
A : Set1
mutual
  A = Set
```
triggers first the internal error for @gallais commit c7b17fc24533a857e0e062e7636c12aa9342a2da

    Date:   Fri Aug 24 16:45:47 2018 +0200

    [ new ] Turning MissingDefinition into a warning
    
    Functions, Datatypes, and Record types declarations are all
    replaced with Axioms if there is no corresponding definition.
    We raise a warning when doing so.
    
    These warnings are turned back into errors if the safe flag is set.

**Comment by gallais** [comment]
However note that:

```agda
mutual
  A : Set1
  A = ?

  mutual
    A = Set
```

fails in 2.5.4.2 with "Mutual blocks are not allowed in mutual blocks" but
with an internal error in 2.6.0.1

So it may be independent from the fact that `MissingDefinition` is now a warning.

**Comment by andreasabel** [comment]
I restored the error "mutual blocks are not allowed in mutual blocks", which fixes "my" internal errors which were all located in `Concrete.Definitions`.  This leaves the OP open.
