### ISSUE TITLE
`import` can remove definitions from scope

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3933]
Agda being a declarative language, the handling of `import` is way too imperative. Basically, `import M directives` overwrites module `M` in the current scope to the restriction of `M` by the `directives`.  This makes scope non-monotone, things can be __deleted__ from the scope.  Deleting symbols via an `import` statement is imho absurd.

Example from https://github.com/agda/agda/issues/3928#issuecomment-513544173:
```agda
open import Agda.Builtin.Nat using ()

Nat  = Agda.Builtin.Nat.Nat
zero = Agda.Builtin.Nat.zero

import Agda.Builtin.Nat using ()

works : Nat
works = zero

fails : Agda.Builtin.Nat.Nat
fails = Agda.Builtin.Nat.zero
```
For the type signature of `fails`,  Agda complains:
```
Not in scope:
  Agda.Builtin.Nat.Nat
```

A fix could be to complain about further imports of an already imported module if these imports are restricting (rather than enlarging) of what is in scope.

**Comment by nad** [comment]
> A fix could be to complain about further imports of an already imported module if these imports are restricting (rather than enlarging) of what is in scope.

Sounds good to me. (Feel free to use the "bug" label rather than "language-change", I don't think the present behaviour was intended.)
