### ISSUE TITLE
Document module keyword in using/hiding/renaming

### ISSUE THREAD

**Issue by msuperdock** [agda/agda#3955]
## Issue

The current module system allows control of which names are imported, via the `using` and `hiding` keywords. But these keywords do not seem to apply for modules defined within a file. For example, consider the following two files:

## Example

File `Test1.agda`:
```
module Test1 where

open import Agda.Builtin.Nat

module Inner where

  x : Nat
  x = 0
```

File `Test2.agda`:
```
module Test2 where

open import Agda.Builtin.Nat
open import Test1 using (Inner)

y : Nat
y = Inner.x
```

## Explanation

I expect both files to check correctly. But on running `agda Test2.agda`, I get the following error:
```
The module Test1 doesn't export the following: Inner
```

I get a similar error message when replacing the `using` keyword with `hiding`. It seems that `using` and `hiding` cannot be used with modules, which is inconvenient. This behavior surprised me because `using` and `hiding` do work correctly with datatype modules; importing the datatype with `using` also imports the module, and the module is not imported otherwise.

These tests are using Agda version 2.6.0.1 on NixOS.

**Comment by gallais** [comment]
Definitions and modules live in different scopes so in the using / hiding
statement, you need to explicitly say that you are talking about a module:

```agda
open import Test1 using (module Inner)
```

has the behaviour you are looking for.

**Comment by UlfNorell** [comment]
The [documentation](https://agda.readthedocs.io/en/latest/language/module-system.html) should mention this.

**Comment by msuperdock** [comment]
Great! Glad that this feature already exists.
