### ISSUE TITLE
Duplicate name in environment buffer with @-pattern

### ISSUE THREAD

**Issue by msuperdock** [agda/agda#3956]
## Issue

The interactive mode usually chooses fresh variable names when it needs to assign a name to a variable, but it seems to not be aware of names assigned by @-patterns.

## Example

```
module Test where

open import Agda.Builtin.Nat

data Fin : Nat → Set where
  zero : {n : Nat} → Fin (suc n)
  suc  : {n : Nat} → (k : Fin n) → Fin (suc n)

f : {n : Nat} → Fin n → Fin n
f zero      = zero
f k@(suc _) = {!!}
```

Loading the context/environment shows:

```
Goal: Fin (suc n)
Have: _13
----------
k : Fin (suc n)
k : Fin n  (not in scope)
n : Nat  (not in scope)
```

## Explanation

The unnamed variable is assigned the name `k`, even though `k` is already used. I would expect the unnamed variable to receive the name `k₁`, or something similar other than `k`.

This may be related to #2958, though the test code at https://github.com/agda/agda/blob/master/test/interaction/Issue2958.agda works without unexpected behavior.

This is using Agda 2.6.0.1, on NixOS, using the vim-agda plugin.

**Comment by gallais** [comment]
The fact that `VarP` and `AsP` do not receive the same treatment looks dodgy to
me but doing the same thing in both cases does not solve this problem so I have
dropped the changes.

https://github.com/agda/agda/blob/0a284d1070563150605080c55a0ce95791290e20/src/full/Agda/Syntax/Translation/AbstractToConcrete.hs#L1189-L1194

https://github.com/agda/agda/blob/0a284d1070563150605080c55a0ce95791290e20/src/full/Agda/Syntax/Translation/AbstractToConcrete.hs#L1210-L1212

**Comment by jespercockx** [comment]
This is fixed by https://github.com/agda/agda/commit/273b080874d542ee4c15cbd726ba6fa241a49b83
