### ISSUE TITLE
Names starting with an hyphen + instance arguments mess up goal detection

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3962]
Loading the following code in emacs does not change the question mark to a goal, despite properly detecting it as a goal in the info buffer.

```agda
postulate
  A : Set
  f : {{_ : A}} → Set
  -x : A

B : Set
B = f {{-x}}

C : Set
C = ?
```

**Comment by jespercockx** [comment]
This clearly has something to do with the emacs mode wrongly parsing `{-` as the beginning of a comment. If you use a hidden argument instead of an instance argument, you get an error:
```agda
postulate
  A : Set
  f : {_ : A} → Set
  -x : A

B : Set
B = f {-x}

C : Set
C = ?
```
Error:
```
 Unterminated '{-'
f<ERROR>
x}

C : Set
C = ?
...
```

**Comment by andreasabel** [comment]
I suppose `{{-` should also be interpreted as the start of a comment (inside a hidden argument). Then we can leave the emacs mode as it is.  My intuitive reading of `{{-foo-}}` is a comment `{-foo-}` inside braces. Rationale: `{ } ( ) {- -}` is punctuation which does not need space-separation. 
Opposition: `{{ }}` is also punctuation.  Alternative: make `{{-` and `-}}` lexer errors, requiring the user to disambiguate.

**Comment by andreasabel** [comment]
I fixed the lexer so that Agda treats `{{-` as beginning of a comment after a brace.
