### ISSUE TITLE
Missing import

### ISSUE THREAD

**Issue by EdNutting** [agda/agda#3981]
Hi,

When building manually on Windows, compilation of this line failed:

https://github.com/agda/agda/blob/e03e94977064d7eb5cdbe220b666795b85a074da/src/full/Agda/Utils/FileName.hs#L117

`and2M` not defined

I think the issue is that Agda.Utils.Monad is not imported? Adding the import made the build for that file work.

Thanks,
Ed

**Comment by andreasabel** [comment]
Seems like dc12aff892 was a bit too eager? It removed imports that were needed for compilation under Windows only.

@L-TChen , can you have a look at this, please?

**Comment by L-TChen** [comment]
As I don't have windows either, @EdNutting can you check if it works now? 

@andreasabel Maybe it is better to set up a Travis testing environment for Windows?

**Comment by andreasabel** [comment]
> Maybe it is better to set up a Travis testing environment for Windows?

That would be great!

**Comment by gallais** [comment]
Related: #2058
Also worth noticing that github is starting [actions](https://github.com/features/actions) which may give us
complementary CI abilities?

**Comment by EdNutting** [comment]
Can confirm, this now works using master 0511b11

**Comment by EdNutting** [comment]
Also, I don't know if this matters, but I'm using "stack install" rather than cabal or (Cygwin) make - because cabal gives me too much trouble on Windows on its own and the make script doesn't work when executed inside Cygwin.

If Agda could work inside Windows Subsystem for Linux (WSL) _and_ still work in emacs mode, now that would be good. Because then it'd just be Agda as a Linux tool but accessible from Windows.

**Comment by L-TChen** [comment]
`stack` should just work, although it is not documented in the official manual. `stack` uses `cabal` under the hood in an isolated environment, so I would actually recommend you to compile Agda by `stack` without worrying about system's ghc environment.

I have no idea about WSL. If you can open another ticket for it, then there might be someone using Windows who can address this, I guess.

**Comment by andreasabel** [comment]
I consider the OP closed, discussion CI for Windows should be on a new ticket.
