### ISSUE TITLE
Warn about duplicate bindings in a single telescope

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3989]
In a longer type signature I forgot an arrow, but get an operator parse error for this:
```agda
postulate
  A : Set
  _==_ : A → A → Set
  _+_~_ : A → A → A → Set
  foo : ∀ (a b c a' b' c' : A) -- forgotton → here
        a + b ~ c →
        a == a' →
        b == b' →
        c == c' →
        a + b ~ c
```
The error is located in the last line:
```
Don't know how to parse a + b ~ c. Could mean any one of:
  ((((a +) b) ~) c)
  _+_~_ a b c
```
However, the actual mistake is quite a bit further up.  Agda directs my attention to the wrong location.

The omitted arrow leads to a non-linear telescope, which is currently legal, but should at least throw a warning.  This warning could be seen in addition to the operator parse error, giving me a hint of the true error location.

**Comment by gallais** [comment]
> a non-linear telescope, which is currently legal, but should at least throw a warning

:+1:

Always puzzled by the level error when I write

```agda
data _~_ {a} {A : Set a} (a : A) : A -> Set a where
  refl : a ~ a
```

**Comment by gallais** [comment]
The easy way to implement this warning is to look at the `LocalVars` and raise
a warning in case there is a shadowing. But it may be a bit noisy, especially
when we have `where` clauses.

More concretely, what do you expect should happen in the following situations?

```agda
open import Agda.Primitive

data _~_ {a} {A : Set a} (a : A) : A -> Set where -- `a` already bound in `_~_ {a}`
  refl : a ~ a
```

```agda
module _ {a} {A : Set a} where

  data Eq (a : A) : (a : A) → Set where -- a already bound in `module _ {a}`
    refl : Eq a a
```

```agda
f : ∀ (a : Level) → ∀ {A : Set a} A ~ A → Set -- A already bound in `{A : Set a}`
f a = {!!}
```

```agda
f' : ∀ a → Set a
f' a = {!!} where

  g : ∀ a → Set a -- a is already bound in `f' a`
  g = {!!}
```

**Comment by andreasabel** [comment]
My take would be to only warn about shadowing in the _same telescope_.  That would be warnings for
```agda
data _~_ {a} {A : Set a} (a : A) : ...
∀ {A : Set a} A ~ A → ...
```
However, no warning for
```agda
(a : Level) (A : Set a) -> (a : A) -> 
```
since the user started a new telescope.  We would need to preserve telescopes carefully until scope checking, of course.

**Comment by nad** [comment]
> The omitted arrow leads to a non-linear telescope, which is currently legal, but should at least throw a warning.

That might lead to lots of warnings being raised in my code. Perhaps that warning could be turned off by default.

**Comment by gallais** [comment]
I just ran the current implementation of the warning on the whole stdlib and got
26 hits which is not too bad for ~70k LoC. Most (perhaps even all, I have not
checked thoroughly) of these are a lowercase letter being used both for a `Set`'s
level and then a value in that `Set`. Meaning that they would go away after a
simple cleanup of the file to use `variable` for levels.

If you have the time @nad, I would be curious to see the kinds of numbers you
would get on your big projects. And depending on the result we can decide whether
to let this one off by default or to actually turn it on.

**Comment by nad** [comment]
Issue #3960 affects a module that a fair amount of my code depends on…

> Most (perhaps even all, I have not checked thoroughly) of these are a lowercase letter being used both for a `Set`'s level and then a value in that `Set`.

That was the kind of code I was thinking of.

**Comment by nad** [comment]
One fairly large library (roughly 100 modules) triggers 19 occurrences of this warning. However, some of these warnings shouldn't have been triggered:
```
Shadowing in telescope, repeated variables: _
when scope checking ∀ _ _ → _
```
(I use this kind of code to inform Agda that a certain lambda is a regular lambda, and not an interval lambda.)

**Comment by WolframKahl** [comment]
````
Shadowing in telescope, repeated variables: _
when scope checking ∀ _ _ → _
````
This also demonstrates the the error message should say `repeated variable names`, because `_` is a nameless variable. :wink:

**Comment by gallais** [comment]
Strange given that [I explicitly filter out names which satisfy `isUnderscore`](https://github.com/agda/agda/commit/2a90ac810fc8c725c2c8da07e4d98f39094436ee#diff-1ba4da578c81df6cfc7553917faf0bd4R206).

**Comment by andreasabel** [comment]
See #2284 for the original issue, which also asks for a warning for lambdas, e.g. `\ x x -> x`.

**Comment by gallais** [comment]
With the following file I get warnings for the lambda. Am I missing something?

```agda
{-# OPTIONS -Wall #-}

_ : ∀ (A B : Set) → A → B → B
_ = λ A A → {!!}
```

```
———— Warnings ——————————————————————————————————————————————
/home/gallais/languages/agda/warndup.agda:4,7-10
Shadowing in telescope, repeated variable names: A
when scope checking λ A A → ?
```

**Comment by nad** [comment]
Consider the following code:
```agda
postulate
  F : (A A : Set) → Set
```
Now the first `A` is highlighted with the "dead code" background colour. Is there some way to turn off this highlighting without turning off the highlighting of dead code? I think this kind of highlighting should be turned off by default, mainly because it also appears in generated HTML code, where I think it draws too much attention to a minor detail.

**Comment by jespercockx** [comment]
This is not a critical issue, so I'm changing the milestone to 2.6.2.

@nad If you don't want to see the dead code highlighting in the generated HTML, can't you just change the color in the `css` file?

**Comment by nad** [comment]
I can, but I have lots of scripts that use `--html`, and changing all of them requires a fair amount of work. Furthermore the locally modified CSS files risk becoming out of date if the generation of HTML code is changed in some way. (Perhaps we could make it easier to override, rather than completely replace, the CSS code.)

**Comment by nad** [comment]
I have added a new `OtherAspect`, `ShadowingInTelescope`, for highlighting of shadowed repeated variables in telescopes. Furthermore the highlighting is only produced when the `ShadowingInTelescope` warning is active.
