### ISSUE TITLE
Some warnings are shown for already type-checked files, but not all

### ISSUE THREAD

**Issue by nad** [agda/agda#4009]
Consider the following code:
```agda
{-# OPTIONS --warning ShadowingInTelescope #-}

module A where

postulate

  F : (A A : Set) → Set
  G : (A A : Set) → Set
```
Let us type-check the code:
```$ agda --ignore-interfaces A.agda
Checking A ([…]/A.agda).
[…]/A.agda:7,8-11
Shadowing in telescope, repeated variables: A
when scope checking (A A : Set) → Set
[…]/A.agda:8,8-11
Shadowing in telescope, repeated variables: A
when scope checking (A A : Set) → Set

———— All done; warnings encountered ————————————————————————

[…]/A.agda:7,8-11
Shadowing in telescope, repeated variables: A
when scope checking (A A : Set) → Set

[…]/A.agda:8,8-11
Shadowing in telescope, repeated variables: A
when scope checking (A A : Set) → Set
```
Now let us type-check the code again:
```
$ agda A.agda

———— All done; warnings encountered ————————————————————————

[…]/A.agda:7,8-11
Shadowing in telescope, repeated variables: A
when scope checking (A A : Set) → Set
```
Note that the second warning has disappeared.

**Comment by nad** [comment]
If this bug only affects `ShadowingInTelescope`, then it is a bug in a feature that has not been released yet. In that case we should perhaps fix it before the release. @gallais, what do you think?

**Comment by gallais** [comment]
IIRC there is some logic in the serialiser to remove duplicated warning messages.
This may be it. I'll try to grab @fredrikNordvallForsberg to have a look at it
together.

**Comment by jespercockx** [comment]
@gallais did you manage to grab him already?

**Comment by gallais** [comment]
Nope, I had forgotten he was travelling. And now I too am away.

**Comment by jespercockx** [comment]
Then since this is not a critical issue, I'm bumping it to 2.6.2 (but please change the milestone back if you happen to fix it before the release).

**Comment by gallais** [comment]
This seems fixed in master. My guess is that @fredrikNordvallForsberg's 1624898b6722fc530c0e8f16b7fdb2c47995f4d1 did it.

**Comment by gallais** [comment]
I do believe this is fixed now.
