### ISSUE TITLE
Revise the Travis CI environment for more platforms and automatic upload

### ISSUE THREAD

**Issue by L-TChen** [agda/agda#4025]
As discussed in #3981, we should set up new build environments for Windows and perhaps for macOS, too, since Travis now supports them as well as multi-platform support. 

https://docs.travis-ci.com/user/multi-os/

As a by-product, we can also release nightly and stable builds automatically via Travis for all platforms we support. 

https://docs.travis-ci.com/user/deployment/releases/

I open this issue for further discussion on revising the CI environment and see what else we can benefit from Travis.

**Comment by andreasabel** [comment]
On a related note: We could make use of `travis stages` (see e.g. https://bytes.babbel.com/en/articles/2018-10-30-travis-build-stages.html) to abort a travis run more quickly if it is bound to fail.  For instance:

1. First stage runs the STACKAGE tests.  They complete usually in <10min.  We could add here the user-manual build which takes <2min.
2. Second stage runs the remaining CABAL tests which include the test suite run, and the HADDOCK test.

This would save resources, e.g. in case compilation fails on one GHC version; then the testsuite would never be attempted.  The latter can be a potential drawback as well.  However, if one wanted to try the testsuite in any case, there are ways to configure travis such that a special string added to the commit message executes the content of stage 2 no matter what.

**Comment by nad** [comment]
> there are ways to configure travis such that a special string added to the commit message executes the content of stage 2 no matter what.

I'd rather not pollute the commit history with Travis commands.

**Comment by andreasabel** [comment]
> I'd rather not pollute the commit history with Travis commands.

Too late, we already have `[ci skip]`.

**Comment by nad** [comment]
I'm not fond of that one either, but I see it as less bad, because it provides possibly useful information about the commit. A command like "run the second part of the test suite even if the first part fails" is more of an ephemeral command, unlikely to provide useful information to people reading the commit message a week later.

**Comment by andreasabel** [comment]
If we had a tag like `[ci full]`, couldn't you just ignore it when reading the commit message?

**Comment by nad** [comment]
Would these commands mostly be used for preliminary pull requests, not for commits going to the main repository? In that case the question of aesthetics is even less important than it would otherwise be.

**Comment by UlfNorell** [comment]
What situation would you use this tag though? If it doesn't pass the stack targets is there any reason to believe it will get to the test suite?

**Comment by L-TChen** [comment]
> Would these commands mostly be used for preliminary pull requests, not for commits going to the main repository?

I think it is mostly the case. We only need to *squash* commit histories for PRs instead of merging directly so that ci commands do not pollute the log.

**Comment by L-TChen** [comment]
By the way, does anyone know how to build the travis cache for dependencies while building via `cabal`?

`cabal` spends about 10 mins on building the whole dependencies every time, and it seems safe to cache these if possible. Can they be fetched via the apt system in advance?

**Comment by gallais** [comment]
Should we also have a zero-th stage checking for whitespace violations?
At the moment we run the first one and fail after 10 minutes on the second
when presumably this error could be raised almost immediately.

**Comment by L-TChen** [comment]
> Should we also have a zero-th stage checking for whitespace violations?
> At the moment we run the first one and fail after 10 minutes on the second
> when presumably this error could be raised almost immediately.

Working on it and Windows environment now...

**Comment by L-TChen** [comment]
It's done, but the script is a bit ugly. I will take some time to polish it. 

https://travis-ci.org/L-TChen/agda/builds/584994959

**Comment by L-TChen** [comment]
I give up automatic deployment for now...

**Comment by andreasabel** [comment]
I have the cabal builds failing strangely:
https://travis-ci.org/agda/agda/jobs/592075578
```
cabal: The file does not exist '(via:'.
The file does not exist 'equivalence-0.3.5)'.
The file does not exist '(new'.
The file does not exist 'package)'.
```
There seem to be problems with the build script!?  
(I cannot see how my commits could have causes that: https://github.com/agda/agda/compare/c18cf06731bd...ea0285235e4f )

**Comment by L-TChen** [comment]
That's really odd. The build script consists of essentially the same commands as the old one. I will take a look soon.

**Comment by L-TChen** [comment]
I re-started one of successful jobs in the past, and it also failed when building dependencies. 
See, https://travis-ci.org/agda/agda/jobs/591267479. 

Therefore, the sed parsing (also used in the original build scripts) fails probably due to a change of output format of `cabal install --dependencies-only --enable-tests --dry-run` so that `cabal fetch` does not get the list of dependencies correctly. This is really odd as the output format is different even for older versions of cabal.

I am not an expert of sed, so I will simply remove https://github.com/agda/agda/blob/14fa5f797017fbc275bcac7e19d397be739f18ed/.travis/cabal_install#L53-L54
so that packages are downloaded by `cabal install --dependencies-only` directly.

**Comment by andreasabel** [comment]
Thanks for fixing!
