### ISSUE TITLE
Rewriting sometimes fails to rewrite in the presence of unsolved metas

### ISSUE THREAD

**Issue by JasonGross** [agda/agda#4038]
The fact that `C-c C-n` does not fully normalize in the presence of unsolved metas results in extremely frustrating and confusing debugging sessions where things will sometimes magically start working when I fill in enough arguments, but when I use shorthand and `_`s, Agda will seemingly not recognize that I asked it to rewrite.

Consider the following code:
```agda
{-# OPTIONS --without-K --rewriting --confluence-check #-}

open import Agda.Primitive using (Level; _⊔_; Setω; lzero; lsuc)

module foooo where

infix 4 _≡_

data _≡_ {ℓ : Level} {A : Set ℓ} (a : A) : A → Set ℓ where
  refl : a ≡ a

{-# BUILTIN REWRITE _≡_ #-}

run : ∀ {ℓ} {A B : Set ℓ} → A ≡ B → A → B
run refl x = x

ap : ∀ {a b} {A : Set a} {B : Set b} (f : A → B) {a₁ a₂} → a₁ ≡ a₂ → f a₁ ≡ f a₂
ap f refl = refl

transport1 : ∀ {a b} {A : Set a} (B : A → Set b) {x y : A} (p : x ≡ y) → B x → B y
transport1 B p = run (ap B p)

ap-const : ∀ {a b} {A : Set a} {B : Set b} (f : B) {a₁ a₂ : A} (p : a₁ ≡ a₂) → ap (\ _ → f) p ≡ refl
ap-const f refl = refl
{-# REWRITE ap-const #-}

ap2 : ∀ {a b rv} {A : Set a} {B : A → Set b} {RV : Set rv} (fn : ∀ a → B a → RV) {a₁ a₂} (pa : a₁ ≡ a₂) {b₁ b₂} (pb : transport1 B pa b₁ ≡ b₂) → fn a₁ b₁ ≡ fn a₂ b₂
ap2 fn refl refl = refl

transport2 : ∀ {a b rv} {A : Set a} {B : A → Set b} (RV : ∀ a → B a → Set rv) {a₁ a₂} (pa : a₁ ≡ a₂) {b₁ b₂} (pb : transport1 B pa b₁ ≡ b₂) → RV a₁ b₁  → RV a₂ b₂
transport2 RV pa pb = run (ap2 RV pa pb)

ap2-const : ∀ {a b rv} {A : Set a} {B : A → Set b} {RV : Set rv} (fn : RV) {a₁ a₂} (pa : a₁ ≡ a₂) {b₁ b₂} (pb : transport1 B pa b₁ ≡ b₂) → ap2 {a} {b} {rv} {A} {B} {RV} (λ _ _ → fn) pa pb ≡ refl
ap2-const fn refl refl = refl
{-# REWRITE ap2-const #-}

ap-const' : ∀ {a b} {A : Set a} {B : Set b} (f : B) {a₁ a₂ : A} (p : a₁ ≡ a₂) → ap (\ _ → f) p ≡ refl
ap-const' f pa = {!ap (λ _ → f ≡ f) _!}

ap2-const' : ∀ {a b rv} {A : Set a} {B : A → Set b} {RV : Set rv} (fn : RV) {a₁ a₂} (pa : a₁ ≡ a₂) {b₁ b₂} (pb : transport1 B pa b₁ ≡ b₂) → ap2 {a} {b} {rv} {A} {B} {RV} (λ _ _ → fn) pa pb ≡ refl
ap2-const' {a} {b} {rv} {A} {B} {RV} fn pa pb = {!ap2 {a} {b} {_} {A} {B} {_} (λ _ _ → fn ≡ fn) pa _!}
```
Both terms in the holes normalize to `refl` under `C-c C-n`.  However, if I replace the `{B}` with `{_}` in passing arguments to `ap2`, the term in the second hole will instead normalize to `ap2 (λ _ _ → fn ≡ fn) pa _pb_247`, even though it *exactly* matches the LHS of a rewrite rule.  What's going on here?

cc @jespercockx ?

**Comment by JasonGross** [comment]
Also, I have occasionally gotten heisenbugs where the first time I ask Agda to normalize a term, it'll complain that the term is ill-typed because `rv != lsuc rv` or because `Set rv != Set (lsuc rv)`, but when I ask it to normalize the term again immediately after, the error message disappears.  I haven't managed to reproduce this reliably, so no idea if this is related.

I am using Agda version 2.6.1 - 037b495

**Comment by jespercockx** [comment]
I'm trying to reproduce the problem, but already with the code as given I'm getting a type error when normalizing the terms in the holes:
```
lsuc b != b
when checking that the inferred type of an application
  (f ≡ f) ≡ (f ≡ f)
matches the expected type
  ap (λ _ → f) pa ≡ refl
```
and
```
lsuc rv != rv
when checking that the inferred type of an application
  (fn ≡ fn) ≡ (fn ≡ fn)
matches the expected type
  ap2 (λ _ _ → fn) pa _255 ≡ refl
```

Could you please submit a corrected version of the code? Or maybe something has changed since the release?

**Comment by JasonGross** [comment]
It sounds like what was a heisenbug for me just occurs all the time for you?  I'm confused by the universe error, though l, too.  Can you explain why the universe error is correct for normalizing these terms?  (It seems possible to be that the universe error is just another way that the bug here is showing up.)

**Comment by jespercockx** [comment]
I tried again and now I don't get the level error anymore. Weird. Anyway, I have a fix incoming for the original problem (missing reduction for terms with metavariables). If you notice the problem with the levels again, please open a new issue for it.
