### ISSUE TITLE
Segmentation fault with 2.6.0.1

### ISSUE THREAD

**Issue by nad** [agda/agda#4039]
I've encountered reproducible segmentation faults using Agda 2.6.0.1:
```
git clone http://www.cse.chalmers.se/~nad/repos/equality/
cd equality
git checkout 460a16c55d551aa22a6782d7ae4b977d76b140ec
sed -ri -e 's/(\<comp\>[^;].*)$/\1 _/' src/Equality/Path.agda
agda-2.6.0.1 -i. README.agda
```
The final line of the output:
```
Segmentation fault (core dumped)
```
I rebuilt Agda 2.6.0.1 (using GHC 8.6.5), and the problem was still there. I checked which libraries were used, and the library version numbers seem to match those used for the development version exactly. However, I can't recall encountering any segfaults when using the development version (also built using GHC 8.6.5).

Can anyone else reproduce these segfaults?

**Comment by nad** [comment]
I managed to avoid the segfault for the example above by building Agda 2.6.0.1 using GHC 8.4.4.

**Comment by UlfNorell** [comment]
fwiw I don't get a segfault with 2.6.0.1 built using ghc-8.6.5.
