### ISSUE TITLE
Remove (deprecated) codata keyword

### ISSUE THREAD

**Issue by ggreif** [agda/agda#4046]
``` agda
codata Foo : Set where
  Bar : Foo
```
gives me the error message
```
The codata construction has been removed. Use the INFINITY builtin instead.
```

`test/Fail/Codata.err` is more than 4 years old.

See also #214 and #1271.

**Comment by ggreif** [comment]
I am working on a patch.

**Comment by andreasabel** [comment]
Thanks for your work, Gabor.  

We might have use for `codata` though when introducing higher coinductive types, which do not fit well with the current `record` syntax.  Thus, I like to keep `codata` as a keyword.

**Comment by ggreif** [comment]
I remember seeing an older entry in the CHANGELOG that the `codata` _keyword_ was removed. Not sure whether `codata` currently counts as a bona-fide keyword (that is reserved everywhere), or is just recognised as a terminal in certain grammar productions.

**Comment by jespercockx** [comment]
@ggreif What is the current status on this issue?

**Comment by ggreif** [comment]
It is mostly done from my viewpoint. I just asked for a little piece of information (in #4047), how to reformulate a comment (https://github.com/agda/agda/pull/4047#issuecomment-532202818). Then it needs to be rebased and merged. That's all.
