### ISSUE TITLE
Missing CHANGELOG entry for scoping of names of where-modules?

### ISSUE THREAD

**Issue by gallais** [agda/agda#4050]
I was surprised to notice in agda/agda-stdlib#878 that the (very sensible) fact
that the module corresponding to a named where-clause is available on the
RHS it is attached to is only a recent change.

The following code is invalid in all versions going back to 2.5.2 but works just
fine with master. Should this language change be documented in the CHANGELOG?
(Bonus question: which commit is responsible for this change?)

```agda
record Wrap : Set₂ where
  field wrapped : Set₁

f : Wrap
f = record { M } module M where

  wrapped : Set₁
  wrapped = Set
```

**Comment by andreasabel** [comment]
Might have been worked on in #3824: cc094ca21b906ad44b55773e29baf10a49c6ee13

**Comment by gallais** [comment]
Thanks!
