### ISSUE TITLE
Internal error when importing a module with a hole in a type

### ISSUE THREAD

**Issue by JLimperg** [agda/agda#4051]
Test case:

In `bug1.agda`:

```agda
{-# OPTIONS --allow-unsolved-metas #-}
module bug1 where

x : {!!}
x = {!!}
```

In `bug2.agda`:

```agda
module bug2 where

open import bug1
```

Loading `bug2` leads to an internal error with reported location `src/full/Agda/TypeChecking/Serialise/Instances/Internal.hs:148`.

Agda versions: 2.6.0.1 and master@957f54f8405c0add88391fca543a71fe14c89795.

**Comment by UlfNorell** [comment]
Duplicate of #3730
