### ISSUE TITLE
Two variants of irrefutable with?

### ISSUE THREAD

**Issue by nad** [agda/agda#4059]
I tried to use irrefutable with for some code of the following form (I):
```agda
f with e₁ ∣ e₂
f | p₁ | p₂ = …
```
However, the following code (II) does not work:
```agda
f with p₁ ← e₁ ∣ p₂ ← e₂ = …
```
Presumably the reason is that this code is not equivalent to the code above, but rather to the following code (III):
```agda
f with e₁
… | p₁ with e₂
…      | p₂ = …
```
Perhaps it would be more natural to use the following notation for (III), and let (II) mean (I):
```agda
f with p₁ ← e₁ with p₂ ← e₂ = …
```

**Comment by gallais** [comment]
I had recorded your suggestion in my #4041 megathread of with-related things I
want to work on during the upcoming AIM. I fully agree that giving users the
syntax to express these subtly different meanings would be a net improvement
over the current implementation.

**Comment by gallais** [comment]
When you write

```agda
f with p₁ ← e₁ ∣ p₂ ← e₂ = …
```

should the variables in `p₁` be in scope in `e₂`?

I do not think it is reasonable to expect so if we consider that `e₁` and `e₂`
get with'd over at the same time.

**Comment by nad** [comment]
I agree.
