### ISSUE TITLE
Missing error message (only error location given)

### ISSUE THREAD

**Issue by nad** [agda/agda#4065]
The following code triggers a rather uninformative error message:
```agda
postulate
  A : Set

record R (F : A → Set) : Set where

module M (r : (F : A → Set) → R F) where

  module T (F : _) = R (r (λ ℓ → F ℓ))
```
The error message:
```
[…]:8,3-39
when checking the module application module T F = R (r (λ ℓ → F ℓ))
```

**Comment by andreasabel** [comment]
Until 2.6.0 there is an error message:
```
Failed to solve the following constraints:
  [5] _6 := (_ : _4) [ℓ] :? Set
when checking the module application module T F = R (r (λ ℓ → F ℓ))
```
Probably caused by work on #3606?! @Saizan

**Comment by Saizan** [comment]
I mean, I wonder if `[5] _6 := (_ : _4) [ℓ] :? Set` contains any useful information, however I suppose we can print such constraints when they get elevated to an error?
