### ISSUE TITLE
A later abstract block can see through the definitions of a former one

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#4070]
I’m not sure if that’s a bug or a feature (it already works in 2.5.3 up to the dev version), but I was very surprised to discover that abstract definitions are not actually abstract in other abstract blocks.

```agda
open import Agda.Builtin.Equality

postulate
  A : Set
  a : A

abstract
  d : A
  d = a

somethingelse : Set
somethingelse = A

abstract
  works : a ≡ d
  works = refl
```

I would not have expected `works` to work, I thought that once we exit the first abstract block, then it is not possible to look inside `d` ever again. Note that it (obviously) doesn’t work if `d` is replaced with a postulate.
This makes `abstract` much less useful for performance as I thought it was, if something is put abstract for performance reasons, then those performance gains are lost when it is used in another abstract block.

The doc is also not exactly clear about that. The section "Scope of abstraction" doesn’t seem to mention that, but there is also the sentence "Outside of abstract blocks, abstract definitions do not reduce" which I guess is consistent with the example above.

Is this really how `abstract` is supposed to work?

**Comment by guillaumebrunerie** [comment]
One way to work around that seems to be to wrap `d` in a named module and open it immediately afterwards:

```agda
open import Agda.Builtin.Equality

postulate
  A : Set
  a : A

module Dummy where
  abstract
    d : A
    d = a
open Dummy public

somethingelse : Set
somethingelse = A

abstract
  fails : a ≡ d
  fails = refl
```

Is there a simpler way? Without having to come up with dummy names?

**Comment by nad** [comment]
> Is this really how `abstract` is supposed to work?

Yes.

I've [used](https://github.com/agda/agda/issues/2207#issuecomment-271815203) the dummy module trick (but I have made the module private, to avoid polluting the name space).
