### ISSUE TITLE
Ill-scoped code in error message

### ISSUE THREAD

**Issue by nad** [agda/agda#4071]
Consider the following code:
```agda
open import Agda.Primitive

postulate
  List : ∀ {ℓ} → Set ℓ → Set ℓ

record List-like (F : ∀ {ℓ} → Set ℓ → Set ℓ) ℓ : Set (lsuc ℓ) where
  field
    to-List   : {A : Set ℓ} → F A → List A
    from-List : {A : Set ℓ} → List A → F A

instance

  postulate
    List-is-list-like : ∀ {ℓ} → List-like List ℓ

module _
  {F : ∀ {ℓ} → Set ℓ → Set ℓ}
  ⦃ list-like : ∀ {ℓ} → List-like F ℓ ⦄
  where

  open module M {ℓ} = List-like (list-like {ℓ = ℓ}) public

module _
  (F : ∀ {ℓ} → Set ℓ → Set ℓ)
  ⦃ list-like : ∀ {ℓ} → List-like F ℓ ⦄
  where

  postulate
    A     : Set
    P     : List A → Set
    xs    : List A
    lemma : P (to-List (from-List xs))
```
Instance resolution fails on the last line, as intended. However, the error message contains ill-scoped code:
```
  Candidates
    F : {ℓ : Level} → List-like @3 ℓ
    List-is-list-like : {ℓ : Level} → List-like List ℓ
```
I suppose that the first candidate should be `list-like : {ℓ : Level} → List-like F ℓ`.

**Comment by andreasabel** [comment]
Is this just a problem of _error-reporting_ or rather a broken internal invariant?

**Comment by nad** [comment]
I don't know.

**Comment by jespercockx** [comment]
Minimal example:
```agda
postulate
  A : Set
  A-like : Set → Set
  instance
    A-is-A-like : A-like A
  to-A : (X : Set) ⦃ a-like : {_ : Set} → A-like X ⦄ → A
  X : Set

foo : {{list-like : A-like X}} → A
foo = to-A _
```

**Comment by UlfNorell** [comment]
Purely an error-reporting issue. When an instance goal is a function type with some number of implicit/instance arguments we add those to the context for the candidates (if they are instance arguments they can be candidates themselves). See #2577. We didn't extend the context in the same way when printing unsolved instance goals, hence the deBruijn failure.

Fix incoming.
