### ISSUE TITLE
Moving fix-agda-whitespace away

### ISSUE THREAD

**Issue by L-TChen** [agda/agda#4072]
This is another issue concerning the development of Agda. 

I propose to move the package `fix-agda-whitespace` to a new repository and upload it to hackage for the following reasons: 

1. `fix-agda-whitespace` can be installed without downloading Agda source code. Good for contributors to the standard library. 

2.  A precompiled binary can be released via GitHub. Good for testing---there is no need to compile it every time. 

I cannot think of any disadvantage...

**Comment by andreasabel** [comment]
If I remember correctly, there are corner-cases hardcoded in `FixWhitespace.hs`. If you want to move this as a standalone package to hackage, you should probably generalize it a bit and read the exclusions/inclusions from a config file.

**Comment by L-TChen** [comment]
Right, the first part of the program is essentially the configuration 

https://github.com/agda/agda/blob/6549537601848d9c27b1c1119d50978135a0abc3/src/fix-agda-whitespace/FixWhitespace.hs#L18-L66

I will first move this package to a new repository and release the compiled one on GitHub to use on Travis.

**Comment by L-TChen** [comment]
@andreasabel , @UlfNorell can you turn Travis on for this repository? https://travis-ci.org/agda/fix-whitespace

**Comment by UlfNorell** [comment]
> Hooray! Repository has been successfully activated.

**Comment by nad** [comment]
A possible disadvantage: If the program is moved to a separate Hackage package, then it becomes much harder to change it. What previously amounted to just pushing a commit now also involves the release procedure for a Hackage package, with testing on multiple platforms and so on (unless you are happy to release untested code).

**Comment by L-TChen** [comment]
I didn't find the license for `fix-agda-whitespace`, so I was not able to submit it to Hackage. 
Once it is submitted to Hackage, then it should be ready to close this issue. 

I also tried to release a binary via Travis, but the binary was not usable for unknown reason.

**Comment by Saizan** [comment]
`fix-agda-whitespace` could be kept fairly easy to change by having it as a submodule like the standard library.

Some care needs to be taken for agda's Makefile to use the specific version from the submodule, but cabal's `--program-suffix` should help.

**Comment by asr** [comment]
The standard library is using `fix-whitespace` from the Github repository. While the issue on the license is fixed, I'll do the same for Agda.

**Comment by L-TChen** [comment]
The license issue is only relevant if it is going to Hackage. As @Saizan suggested, it can be included as a submodule. I am making #4674  to close this issue.

**Comment by asr** [comment]
> I am making a PR to close this issue.

Does it mean that Agda will use `fix-whitespace`?

**Comment by L-TChen** [comment]
Yes.
