### ISSUE TITLE
Allow wildcards in rewrite

### ISSUE THREAD

**Issue by ggreif** [agda/agda#4076]
Consider the following (contrived) snippet:
``` agda
postulate mult-distributes-right : ∀ (a b c : Nat) -> mult a (plus b c) ≡ plus (mult a b) (mult a c)

mult-distributes-left : ∀ (a b c : Nat) -> mult (plus a b) c ≡ plus (mult a c) (mult b c)
mult-distributes-left a b c rewrite mult-commutes (plus a b) c
                                  | mult-commutes a c
                                  | mult-commutes b c 
                                  | mult-distributes-right c a b = refl
```

I suggest allowing `_` wildcard patterns in rewrite clauses. That would simplify the above code to
``` agda
mult-distributes-left : ∀ (a b c : Nat) -> mult (plus a b) c ≡ plus (mult a c) (mult b c)
mult-distributes-left a b c rewrite mult-commutes _ c
                                  | mult-distributes-right c a b = refl
```
since the wildcard rewrite rule would trigger three times.

N.B. Syntactically wildcards are *already* allowed in rewrite rules, but do something different. (I am not sure what.)

This is a follow up to https://www.reddit.com/r/agda/comments/cgeipq/rewrite_construct_with_wildcards/?utm_source=share&utm_medium=web2x

**Comment by nad** [comment]
Do you have a semantics in mind for this proposed new feature?

> N.B. Syntactically wildcards are *already* allowed in rewrite rules, but do something different. (I am not sure what.)

They have their usual meaning. See the [documentation](https://agda.readthedocs.io/en/v2.6.0.1/language/with-abstraction.html#with-rewrite) for more information about `rewrite`.

**Comment by andreasabel** [comment]
Currently, `rewrite` does not instantiate meta-variables when trying to find a match in the goal.
If you put a wildcard in the `rewrite` expression, it is subject to solving only during the type inference process for the rewrite expression.  In your example, the meta variable would remain unsolved, rendering the `rewrite` statement ineffective.  

We should maybe check for unsolved metas before attempting abstraction to alert the user that the `with` or `rewrite` is bound to fail. (I wonder if there are any use cases for abstracting terms with metas.)

**Comment by nad** [comment]
> Currently, `rewrite` does not instantiate meta-variables when trying to find a match in the goal.

That is not quite correct. The following code is accepted:
```agda
open import Agda.Builtin.Bool
open import Agda.Builtin.Equality

postulate
  lemma : (A : Set) (a : A) → a ≡ a

test : Bool
test rewrite lemma _ true = false
```

> If you put a wildcard in the `rewrite` expression, it is subject to solving only during the type inference process for the rewrite expression.

And you can help out by, for instance, providing a type signature:
```agda
open import Agda.Builtin.Bool
open import Agda.Builtin.Equality

postulate
  magic          : {A : Set} → A
  type-signature : (A : Set) → A → A

syntax type-signature A a = a ⦂ A

-- fails : true ≡ false
-- fails rewrite magic = refl

works : true ≡ false
works rewrite magic ⦂ (true ≡ false) = refl
```

However, there is currently no way to use a lemma at two different types at the same time (unless there is some bug).

**Comment by andreasabel** [comment]
> > Currently, `rewrite` does not instantiate meta-variables when trying to find a match in the goal.
> 
> That is not quite correct. The following code is accepted:
> 
> ```agda
> open import Agda.Builtin.Bool
> open import Agda.Builtin.Equality
> 
> postulate
>   lemma : (A : Set) (a : A) → a ≡ a
> 
> test : Bool
> test rewrite lemma _ true = false
> ```

This does not contradict my statement.  The meta in `lemma _ true` is solved to `Bool` by virtue of `true` __before__ matching in the goal type.

> > If you put a wildcard in the `rewrite` expression, it is subject to solving only during the type inference process for the rewrite expression.
> 
> And you can help out by, for instance, providing a type signature:
> 
> ```agda
> open import Agda.Builtin.Bool
> open import Agda.Builtin.Equality
> 
> postulate
>   magic          : {A : Set} → A
>   type-signature : (A : Set) → A → A
> 
> syntax type-signature A a = a ⦂ A
> 
> -- fails : true ≡ false
> -- fails rewrite magic = refl
> 
> works : true ≡ false
> works rewrite magic ⦂ (true ≡ false) = refl
> ```

Ditto. Confirms my statement.

**Comment by nad** [comment]
I guess I misinterpreted you.

**Comment by ggreif** [comment]
So this got closed because it is not possible to repetitively apply a rewriting equation (with a `_` inside)? Or would there be a conflict with the standard semantics of `_`?

**Comment by UlfNorell** [comment]
Yes, the way rewrite is implemented it's not possible to do what you are asking.
