### ISSUE TITLE
Order of clauses matters too much; equations should hold definitionally whenever possible.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#408]
(See attached file.)

In a definition of parallel substitution for strongly typed terms I wrote:
```agda
  subst : ∀ {m} {vt : VarTrm m} (tau : RenSub vt) → Tm → Tm
  subst {vt = Var} tau (var x)   = var (tau x) -- lookup in renaming
  subst {vt = Trm} tau (var x)   = tau x       -- lookup in substitution
  subst {vt = vt } tau (abs t)   = abs (subst (lift tau) t)
  subst {vt = vt } tau (app t u) = app (subst tau t) (subst tau u)
```
However, the last two equations did not hold definitionally, since Agda splits first on vt and then on the Tm argument.  This makes the subsequent proof fail.

Everything works fine if I put the last two clauses first, then Agda first splits on the Tm argument and then, only in case var, on vt.

For anyone but the expert this behavior is confusing (see messages on the Agda list).

Can we change Agda to enforce that equations hold definitionally?  The exception would of course be partially redundant clauses such as default cases, they can not hold definitionally.  But it should be visible in the syntax that a clause is not a definitional equality, to get WYSIWYG.  One way is to require permission by the user to split a variable that is not an implicit or underscore.

For instance, 
```agda
  max zero n = n
  max m zero = m
  max (suc m) (suc n) = suc (max m n)
```
could be rejected by Agda since no case tree has this behavior, definitionally. 
One would have to give a strictness annotation to either n or m in the first 
two equations:
```agda
  max zero !n = n
  max m zero = m
  max (suc m) (suc n) = suc (max m n)
```
This variant would enforce to first split on n and only in the successor case 
split on m, to preserve reduction behavior for the second equation.

It is then clear to the user that the first equation does not always hold but 
rather is only an abbreviation for
```agda
  max zero (suc n) = suc n
```
Comments?

Original issue reported on code.google.com by `andreas....@gmail.com` on 18 Apr 2011 at 11:59

Attachments:
- [ParallelSubstitution.agda](https://storage.googleapis.com/google-code-attachments/agda/issue-408/comment-0/ParallelSubstitution.agda)

**Comment by UlfNorell** [comment]
What's left here? We have the (no longer that) new split strategy and the `--exact-split` option. I don't see any test cases where equations could, but does not, hold definitionally.

**Comment by UlfNorell** [comment]
Closing. Reopen with test case if needed.

**Comment by andreasabel** [comment]
We never turned on the split strategy discussed in https://github.com/agda/agda/issues/408#issuecomment-129023160 but I agree we should keep things as they are...
