### ISSUE TITLE
Make it possible to rename Set?

### ISSUE THREAD

**Issue by nad** [agda/agda#4093]
@jespercockx [gave](https://github.com/agda/agda/pull/4091#issuecomment-531653874) me an idea.

I don't think that `Set` should be a hardwired name. Perhaps we can fix this without breaking any code:
* Export `Set` (an identifier without a type, like `Agda.Primitive.Cubical.I`) from `Agda.Primitive`, and allow this identifier to be renamed. If the identifier is in scope as `S`, then it should be possible to write `S` (this would mean `Set` using current syntax), `S e` (this would mean `Set e`) and `Sn`/`Sₙ` (this would mean `Setn`/`Setₙ`). I suggest that we (at least initially) disallow turning `Set` into an operator, and/or giving a `syntax` declaration for it.
* If this identifier is not in scope, and none of the variants of `Set` (`Set`/`Setn`/`Setₙ`) are in scope in any other way (qualified or unqualified), then the identifier is automatically brought into scope under the name `Set`.

With these rules I don't think we would break any currently accepted code. The trickiest part of the implementation might be handling the countably infinite set of names `Sn`/`Sₙ`.

We could also do something similar for `Prop`.

Any thoughts?

**Comment by ice1000** [comment]
This can supersede many existing hacks such as https://github.com/agda/cubical/blob/48bd72e073b11d7501342d88eede05974a616977/Cubical/Core/Primitives.agda#L32-L39, https://github.com/HoTT/HoTT-Agda/blob/1037d82edcf29b620677a311dcfd4fc2ade2faa6/core/lib/Base.agda#L33-L40

**Comment by jespercockx** [comment]
I've spent the weekend working on fixing this issue. It's not quite ready yet, but here's a screenshot of something that's working already to illustrate the design:

![million_dollar_mistake](https://user-images.githubusercontent.com/2910371/80318660-e8349780-880b-11ea-87d3-b92f67087f71.png)

**Comment by nad** [comment]
Good work. However, I don't want to write `--no-auto-import-primitive` in every file. This could be avoided if we fix #3118.

By the way, there is a Haskell language extension called `NoImplicitPrelude`. Perhaps we could use a similar name.

**Comment by jespercockx** [comment]
Yes, this was designed with #3118 being fixed in mind. The alternative is to try to detect if the module imports `Agda.Primitive` and disable the automatic import in that case, but (1) this would be brittle and (2) this would not work when a file imports `Agda.Primitive` *indirectly*, so it would not be very useful.

> By the way, there is a Haskell language extension called NoImplicitPrelude. Perhaps we could use a similar name.

Ah yes, perhaps we can name it `--no-implicit-primitive`? Although I think the meaning is clearer with `--no-auto-import-primitive`.

**Comment by andreasabel** [comment]
> Although I think the meaning is clearer with `--no-auto-import-primitive`.

My knee jerk reaction was also to imitate Haskell here, but thinking about it, `NoImplicitPrelude` was not the greatest choice of name.

Shorter alternatives for the flag name:
* `--no-primitives`
* `--bare`

`--bare` for the bare construct of the Agda matrix, without any preloaded program: https://www.youtube.com/watch?v=AGZiLMGdCE0

**Comment by zraffer** [comment]
Do you really need `Typen/Typeₙ` constants? It seems backward compatibility issue only for old code with `Setn/Setₙ`.
`Set 1`... with natural literals seems as good as `Setₙ`. People prefering renaming `Set` to `Type` doubtfully would use `Typeₙ`. Rather `Type 1`...

**Comment by ice1000** [comment]
Natural literal is related to the BUILTIN fromNat definition, and it's gonna be confusing to me if we use the same syntax for the `Level` type, which is unrelated to the BUILTIN.

**Comment by zraffer** [comment]
@ice1000 now me is happy with the current Agda version and the obvious instance of `Number Level`. But it was a surprise to found the absence of such instance in `Agda.Builtin` library.
