### ISSUE TITLE
GHC backend produces code that is wrongly compiled by GHC 8.4.* and 8.6.*

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#4100]
```agda
module Main where

open import Agda.Builtin.String using (String)
open import Agda.Builtin.IO     using (IO)

{-# FOREIGN GHC import qualified Data.Text #-}
{-# FOREIGN GHC import qualified System.Exit #-}
{-# FOREIGN GHC import qualified System.IO #-}

record ⊤ : Set where

postulate
  _>>=_       : ∀ {a b} {A : Set a} {B : Set b} → IO A → (A → IO B) → IO B
  putStrLn    : String → IO ⊤
  exitFailure : ∀{a} {A : Set a} → IO A

{-# COMPILE GHC ⊤           = data () (())                          #-}
{-# COMPILE GHC _>>=_       = \_ _ _ _ -> (>>=)                     #-}
{-# COMPILE GHC putStrLn    = System.IO.putStrLn . Data.Text.unpack #-}
{-# COMPILE GHC exitFailure = \ _ _ -> System.Exit.exitFailure      #-}

_>>_  : ∀ {b} {B : Set b} → IO ⊤ → IO B → IO B
_>>_ = λ m m' → m >>= λ _ → m'

main : IO ⊤
main = do
  putStrLn "Hello,"
  putStrLn "world!"
  exitFailure
```
The program compiled with the GHC backend for GHC versions 8.4 and 8.6 produces
```
Hello,
```
and exit code 0.  GHC 8.0, 8.2 and 8.8 produce a program that outputs correctly
```
Hello,
world!
```
and exit code 1.

This seems to be a problem of GHC 8.4 and 8.6: with optimizations `-O`, `unsafeCoerce` seems to be compiled wrongly. The GHC issue has been reported under https://gitlab.haskell.org/ghc/ghc/issues/17206.

If possible, we should find and implement a workaround on our side, as this GHC bug renders Agda unsound as well.

**Comment by andreasabel** [comment]
This problem could solve itself soon... we are already at GHC 9.0.

**Comment by nad** [comment]
Do we check that GHC 8.4 and 8.6 are not used to compile the generated code? We could perhaps use something like the following hack:

https://github.com/agda/agda/blob/8ec5d18a5a84b4e8545e9787965e39f77ab3eed9/src/full/Agda/Compiler/MAlonzo/Compiler.hs#L1263-L1269

**Comment by andreasabel** [comment]
Something like this would have been more useful when we still supported 8.6, but now we are dropping it from support.
But if you want, knock yourself off!
