### ISSUE TITLE
Add a pragma for telling agda that a definition is injective

### ISSUE THREAD

**Issue by canndrew** [agda/agda#4106]
Agda has REWRITE rules for turning a propositional equality into a definitional equality. Could we have something similar for injectivity? That is, agda's unifier can often use `foo x ≡ foo y` to infer `x ≡ y`, but this only works when it can see that `foo` is injective from the definition of `foo`. I'm in a situation where I can prove that `foo` is injective propositionally and I'd like to make use of the same inference behavior. It would be nice if it was possible to do this using something like:

```
foo-injective : {x y} -> (foo x ≡ foo y) -> x ≡ y
foo-injective = ...

{-# INJECTIVE foo foo-injective #-}
```

(Note: I'm an Agda noob so maybe this already possible in some way that I'm not familiar with, but it didn't seem that way based on my conversations on irc)

**Comment by jespercockx** [comment]
You're in luck, since there is already such a feature:
```
open import Agda.Builtin.Equality

postulate F : Set → Set

{-# INJECTIVE F #-}

test : {X Y : Set} → F X ≡ F Y → X ≡ Y
test refl = refl
```
Only it is not as safe as the version you are proposing, since it does not actually require you to prove injectivity first. It is also undocumented and mostly untested, so use it at your own risk (and please report any bugs you encounter).

**Comment by canndrew** [comment]
Oh cool! I'm curious why it doesn't require a proof of injectivity though? It wouldn't be any more restrictive since you could just postulate the proof if need be.

**Comment by jespercockx** [comment]
I guess the reason is just because it was easier to implement without the proof of injectivity.

**Comment by canndrew** [comment]
It's totally unsound though without the proof. Is it sound with the proof?

Also it doesn't appear to be working for me 😞. Here's my code:

```agda
module core where

open import Agda.Primitive

data Lev : Set where
    lev-zero : Lev
    lev-succ : Lev -> Lev

interp : Lev -> Level
interp lev-zero = lzero
interp (lev-succ lev) = lsuc (interp lev)

Ctx :
    (l : Lev) ->
    Set (lsuc (interp l))

Type :
    {ctx-l : Lev} ->
    (type-l : Lev) ->
    Ctx ctx-l ->
    Set ((interp ctx-l) ⊔ (lsuc (interp type-l)))

Ctx l = Set (interp l)
Type {ctx-l} type-l ctx = ctx -> Set (interp type-l)

{-# INJECTIVE interp #-}
{-# INJECTIVE Ctx #-}

data $cons
    {ctx-l}
    {type-l} :
    (ctx : Ctx ctx-l) ->
    (type : Type {- UNSOLVED META HERE -} type-l ctx) ->
    Set where
```

If you try to compile this it says there's an unsolved meta in the definition of `$cons` where I've written `UNSOLVED META HERE`. This should work if `Ctx` is injective - `ctx` has type `Ctx ctx-l`, so the `{ctx-l}` argument to `Type` must be `ctx-l`.

**Comment by nad** [comment]
There is some documentation of `INJECTIVE`:

https://github.com/agda/agda/blob/c8be152f58c1bda4713817de89458a37b8beda97/CHANGELOG.md#L2213-L2231

**Comment by canndrew** [comment]
@nad is it supposed to work with functions, like I've done in my code (declaring `Ctx` as injective)?

**Comment by jespercockx** [comment]
It is supposed to work with functions like in your example, yes. However, at the moment it only gives you *propositional* injectivity (so you can pattern match on a proof of `interp x ≡ interp y`, but not *definitional* injectivity (so the constraint solver still doesn't know how to solve the constraint `interp ctx-l = interp _ctx-l_17`). It would probably not be too hard to improve the constraint solver to also consider `INJECTIVE` pragmas.

**Comment by andreasabel** [comment]
Seems like the discussion has finished; thus, I am closing this issue.  Feel free to come back with a concrete proposal and reopen, if necessary.

**Comment by uhbif19** [comment]
@jespercockx 

> However, at the moment it only gives you propositional injectivity (so you can pattern match on a proof of interp x ≡ interp y, but not definitional injectivity (so the constraint solver still doesn't know how to solve the constraint interp ctx-l = interp _ctx-l_17).

Should not that be in pragma doc? I can create PR for this if that is right.

**Comment by jespercockx** [comment]
Yes, feel free to create a PR!
