### ISSUE TITLE
Changing parameter order increases typechecking time

### ISSUE THREAD

**Issue by bishboria** [agda/agda#4108]
I'm working on proving metatheory for Dependently typed lambda calculus and have noticed that changing the order of the input parameters has a big effect on the time it takes to typecheck the file.

For example, I originally had (ignoring `forall` implicits):

```
pres : G ~>>* G' ->
       T ~>>* T' ->
       t ~>> t' ->
       G |- T :: t -> -- pattern matching on this term
       G' |- T' :: t'
```
This takes 22 seconds to typecheck the whole file.

I changed the order to
```
pres : G |- T :: t -> -- was last input, now first input. pattern matching on this term
       G ~>>* G' ->
       T ~>>* T' ->
       t ~>> t' ->
       G' |- T' :: t'
```
and the typechecking time halved to 11 seconds!

I'm running the latest version of master (as of 26/9/19 11am).

I believe Agda currently uses a Left To Right checker… Would some sort of hint to Agda to say "case on this first" be useful?

**Comment by nad** [comment]
Perhaps it would be easier to look into this with a self-contained example.

**Comment by UlfNorell** [comment]
Nothing really actionable here.
