### ISSUE TITLE
cannot declare data types in Setω

### ISSUE THREAD

**Issue by canndrew** [agda/agda#4109]
On agda master branch this code no longer compiles:

```agda
open import Agda.Primitive

data Foo : Setω where
```

**Comment by UlfNorell** [comment]
Does this work with previous versions?

**Comment by andreasabel** [comment]
Before 2.6.0 the error was `Not in scope: Setω`, now it is `Failed to solve the following constraints:
  Has bigger sort: Setω`.

**Comment by dylanede** [comment]
Why is it invalid to define a data type in `Setω`? `Failed to solve the following constraints: Has bigger sort: Setω` does not mean much to me. Also, when that error message appears, there are no line numbers associated with it, making it hard to spot which part of a file is causing the error.

**Comment by jespercockx** [comment]
> Failed to solve the following constraints: Has bigger sort: Setω does not mean much to me.

It means that `Setω` is used somewhere as a term, but it cannot be assigned a type since there is no bigger sort that it in Agda. I agree that it would be useful to have a range to indicate where the constraint was generated.

**Comment by jespercockx** [comment]
See also https://github.com/agda/agda/issues/2285

**Comment by dylanede** [comment]
So why are records in `Setω` allowed but not `data` types? Seems inconsistent.
