### ISSUE TITLE
Re-enable use of Edison

### ISSUE THREAD

**Issue by asr** [agda/agda#4110]
The dependency in [EdisonCore](http://hackage.haskell.org/package/EdisonCore) was removed in [this](770fa53e9bee462484e74a6d3017962e6c731b9b) commit because #3725. In relation to the use of this library, @nad [wrote](https://github.com/agda/agda/issues/3725#issuecomment-512343829)

> My experience is that the `Data.Sequence` sequences can be rather slow in practice (they seem to come with high "hidden constants"). I ran some benchmarks when developing a previous variant of the code. The current code is not identical, but I would not be surprised if running `reachableFrom` and forcing the lists is sometimes substantially faster with banker's queues than with `Data.Sequence` sequences. (In my benchmarks I used a "linear" graph with 10000 nodes, and found all nodes reachable from the first one.)

> Perhaps these considerations are irrelevant for Agda: `reachableFrom` is currently only used by `walkSatisfying`, which is currently only used to produce error messages. However, I don't think we should make code slower unless there is a good reason for doing so.

and @L-TChen  [wrote](https://github.com/agda/agda/issues/3725#issuecomment-512513452)

> But, anyway, updating Edison is also a good option, since it is the only package I know containing a number of classic specialised containers and a good supplement to Okasaki's textbook.

I'm waiting the merge of https://github.com/robdockins/edison/pull/16 for re-enabling the use of Edison.

**Comment by UlfNorell** [comment]
Why would we want to add the Edison dependency back? If you're concerned about performance regressions from using `Data.Sequence`, please provide test cases.

**Comment by andreasabel** [comment]
There seem to be no strong arguments to reintroduce _Edison_, thus, I close this issue.  Feel free to reopen should there be need for further discussion.
