### ISSUE TITLE
Elements in a proposition are needlessly reduced when pattern matching

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#4115]
I’m having some performance issues with `Prop`, where it seems like sometimes Agda decides to reduce/normalize elements of propositions, even though it should never be needed. I reduced it to the following code, where the function `works` loads instantly whereas the function `loops` loops, which shows that it is somehow trying to reduce `tr` even though there is no reason to.

```agda
{-# OPTIONS --prop #-}

data Nat : Set where
  zero : Nat
  suc : Nat → Nat

data _==_ {A : Set} (x : A) : A → Prop where
  refl : x == x

{-# TERMINATING #-}
tr : {a b c : Nat} → a == b → b == c → a == c
tr p q = tr p q

works : Nat → zero == zero
works n = tr ? ?

loops : Nat → zero == zero
loops zero = tr ? ?
loops (suc n) = ?
```

**Comment by guillaumebrunerie** [comment]
Slightly simpler test case:

```agda
{-# OPTIONS --prop #-}

data Unit : Set where
  tt : Unit

postulate
  P : Prop

{-# TERMINATING #-}
p : P
p = p

works : Unit → P
works b = p

loops : Unit → P
loops tt = p
```

**Comment by jespercockx** [comment]
I can confirm the issue. The last message Agda gives before going into the loop is: `Checking injectivity of Issue4115.loops`.
