### ISSUE TITLE
Elements of a proposition needlessly reduced during positivity checking

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#4122]
Similar to #4115, #4118, #4120. Both the record and the datatype below loop when checking positivity. It loops after
```
checkDecl: checking positivity...
computeOccurrences X ConcreteDef ConcreteMode test
```
```agda
{-# OPTIONS --prop #-}

{-# TERMINATING #-}
makeloop : {P : Prop} → P → P
makeloop p = makeloop p

postulate
  P : Prop
  p : P
  Q : P → Set

record X : Set where
  field
    f : Q (makeloop p)

data Y : Set where
  f : Q (makeloop p) → Y
```

**Comment by guillaumebrunerie** [comment]
Issue #1899 seems related. The positivity checker fully normalize the telescope before checking for positivity, which is likely to cause a problem here.
Despite reading the comments at #1899, I’m not entirely convinced yet that we do need full normalization, though.

**Comment by jespercockx** [comment]
I wonder what is your actual use case for having a proof of a `Prop` marked as `{-# TERMINATING #-}`? Wouldn't  `{-# NON_TERMINATING #-}` do exactly what you want here (i.e. not reduce the proposition)?

**Comment by guillaumebrunerie** [comment]
My use case is simply that I have proofs of propositions that take quite a long time (and a lot of memory) to reduce. `{-# TERMINATING #-}` is just used here to simulate the fact that it takes a long time to reduce them (and find the places where Agda does try to reduce them), I don’t actually use `{-# TERMINATING #-}` in practice.

**Comment by guillaumebrunerie** [comment]
And so I can’t use `{-# NON_TERMINATING #-}`, as it makes Agda inconsistent.

But maybe the part of Agda that blocks reduction for definitions marked as `{-# NON_TERMINATING #-}` could be reused to automatically block reduction of elements of propositions?

**Comment by UlfNorell** [comment]
You should be able to use `abstract` for that.

**Comment by guillaumebrunerie** [comment]
> You should be able to use `abstract` for that.

I tried, that’s how I found out about #4070. Abstract definitions still do reduce in other abstract definitions, so it’s not ideal either.

**Comment by jespercockx** [comment]
> But maybe the part of Agda that blocks reduction for definitions marked as {-# NON_TERMINATING #-} could be reused to automatically block reduction of elements of propositions?

This would be possible, but I'm not sure if this will actually result in the proper behaviour for the checks that are now looping (occurs check, polarity check). I could set up a branch to experiment further with this idea.

**Comment by jespercockx** [comment]
I've added a flag `--no-reduce-prop` which seems to solve the problem. Could you please test out if it also helps with your performance problems? If it does and doesn't have too many negative side-effects, we could make it into the default behaviour.

**Comment by guillaumebrunerie** [comment]
It doesn’t seem to solve the performance problems :(
I think that I’m often dealing with terms (in Set) where some of the subterms are elements of propositions, but they don’t necessarily have a name themselves.

Also it seems to badly interact with `--no-fast-reduce` and importing modules. In some situations (somewhat unclear so far) I get:
```
agda-dev: src/full/Agda/TypeChecking/Reduce/Fast.hs:891:17-87:
  Irrefutable pattern failed for pattern CCon {cconSrcCon = c', cconArity = ar}
```

**Comment by jespercockx** [comment]
Another idea would be to wrap all elements of a `Prop` in a `DontCare` constructor as we do for irrelevance. In principle this ought not to be necessary for `Prop` so I didn't feel the need to do it, but perhaps it would actually make things easier (also e.g. #3337). I'll try and see if it works.

**Comment by guillaumebrunerie** [comment]
> Another idea would be to wrap all elements of a `Prop` in a `DontCare` constructor as we do for irrelevance. In principle this ought not to be necessary for `Prop` so I didn't feel the need to do it, but perhaps it would actually make things easier (also e.g. #3337). I'll try and see if it works.

Would that also solve #4120, about occursCheck? I profiled Agda (`-v profile:10`) on another file of the project on which we have performance issues (`totality.agda` from https://github.com/guillaumebrunerie/initiality, if you want to try it yourself, although you might need a lot of memory to make it work).
The results are the following:
```
Total                        618,752ms            
Miscellaneous                     64ms            
Positivity                   267,365ms            
Termination                   10,297ms (152,135ms)
Termination.Compare           94,890ms            
Termination.Graph             43,454ms            
Termination.RecCheck           3,493ms            
Typing                         6,378ms (139,287ms)
Typing.OccursCheck           113,066ms            
Typing.CheckRHS               16,022ms            
Typing.CheckLHS                1,201ms   (1,928ms)
Typing.CheckLHS.UnifyIndices     727ms            
Typing.Generalize              1,413ms            
Typing.TypeSig                   477ms            
Serialization                 30,165ms  (34,098ms)
Serialization.BuildInterface   3,027ms            
Serialization.BinaryEncode       754ms            
Serialization.Sort                91ms            
Serialization.Compress            58ms            
Scoping                        2,287ms   (7,397ms)
Scoping.InverseScopeLookup     5,110ms            
DeadCode                       5,851ms            
Parsing                          134ms   (4,410ms)
Parsing.OperatorsExpr          3,849ms            
Parsing.OperatorsPattern         426ms            
Coverage                       4,257ms            
Deserialization                3,525ms            
Highlighting                     326ms            
Import                            32ms            
```
As you can see, positivity checking and occurs check both take quite a lot of time (especially compared to CheckRHS or Serialization, which I think are the ones which usually take most of the time). I’m not really sure what positivity checking means, actually, as there are no records or datatypes in this file, only large mutual blocks. Termination checking is also quite long, maybe this is also due to normalization of elements of Prop, I’m not sure.

**Comment by nad** [comment]
"Positivity" includes the machinery that keeps track of how function arguments are used, in case a function is later used as part of a (co)inductive definition.

**Comment by jespercockx** [comment]
I pushed the new behaviour of wrapping all elements of a `Prop` in a `DontCare` constructor. @guillaumebrunerie could you do the performance test again with this change?

**Comment by jespercockx** [comment]
I tried to run the test myself but I ran out of memory. Apparently 16GB is not enough...

**Comment by guillaumebrunerie** [comment]
I’ll try it on Monday when I’ll have access to my work computer (with 32GB of memory…).

**Comment by guillaumebrunerie** [comment]
> I pushed the new behaviour of wrapping all elements of a `Prop` in a `DontCare` constructor. @guillaumebrunerie could you do the performance test again with this change?

This seems to have broken implicit arguments whose type is a proposition. I now have tons of yellow everywhere. For instance the following works in 2.6.0.1, but now Agda can’t guess the implicit argument of `f`
```agda
{-# OPTIONS --prop #-}

postulate
  P : Prop
  p : P
  A : P → Set
  f : {x : P} → A x

test : A p
test = f
```

**Comment by jespercockx** [comment]
Right, I guess the constraint solver now has to be a bit smarter and also solve equations of the form `DontCare x == u` when working in an irrelevant context. I'll see if I can fix it.

**Comment by jespercockx** [comment]
Fix = pushed! Hopefully this will also help with solving metavariables when using irrelevance.

**Comment by guillaumebrunerie** [comment]
Thanks!
The yellow is gone, although now I’m running into an issue when doing pattern matching on `refl`, when one side includes elements of propositions:
```agda
{-# OPTIONS --prop #-}

data _≡_ {X : Set} (a : X) : X → Prop where
  refl : a ≡ a

postulate
  A : Set
  P : Prop
  p : P
  u : P → A

f : {x : A} (q : u p ≡ x) → P
f refl = ?   -- works in 2.6.0.1
```
```
I'm not sure if there should be a case for the constructor refl,
because I get stuck when trying to solve the following unification
problems (inferred index ≟ expected index):
  u _ ≟ x
when checking that the pattern refl has type u _ ≡ x
```

**Comment by jespercockx** [comment]
Aha, this seems to be similar to the fix I made to the occurs check in https://github.com/agda/agda/commit/e3562449c1fd67d9005edccb9323af73ae35a9a0, only now for the LHS unifier. 

Apparently I unknowingly made a change to the semantics of `DontCare`: before it meant "this CAN only be used in an irrelevant context" (which has to be checked each time we encounter one), now it means "this WILL only be used in an irrelevant context" (which we should be able to trust without checking). This change in semantics does not cause immediate problems because irrelevant definitions and projections are no longer reduced (https://github.com/agda/agda/commit/73ac1513e6baa2af69af32c9098c79f40722159d), so there is no need anymore to "protect" the right-hand side with a `DontCare` wrapper. I hope @andreasabel can agree with this change! (In which case I should probably also document it somewhere.)

**Comment by guillaumebrunerie** [comment]
Here are the results. It definitely solved the performance issue about positivity checking, but occursCheck and termination checking still take a long time.
```
Total                        369,627ms            
Miscellaneous                     65ms            
Termination                   11,739ms (170,747ms)
Termination.Compare          113,273ms            
Termination.Graph             44,264ms            
Termination.RecCheck           1,469ms            
Typing                        11,083ms (142,468ms)
Typing.OccursCheck           111,049ms            
Typing.CheckRHS               16,365ms            
Typing.CheckLHS                1,189ms   (1,914ms)
Typing.CheckLHS.UnifyIndices     724ms            
Typing.Generalize              1,567ms            
Typing.TypeSig                   487ms            
Serialization                 31,455ms  (35,709ms)
Serialization.BuildInterface   3,285ms            
Serialization.BinaryEncode       830ms            
Serialization.Sort                78ms            
Serialization.Compress            60ms            
DeadCode                       7,036ms            
Parsing                          140ms   (4,543ms)
Parsing.OperatorsExpr          3,961ms            
Parsing.OperatorsPattern         441ms            
Deserialization                3,714ms            
Scoping                        2,275ms   (2,451ms)
Scoping.InverseScopeLookup       175ms            
Positivity                     1,392ms            
Coverage                       1,137ms            
Highlighting                     327ms            
Import                            33ms            
```

**Comment by jespercockx** [comment]
Great, it seems it really helped for the positivity checking! Thanks for running the tests. Since this issue is about positivity checking and the remaining problem is with the occurs check, let's move the discussion to #4120. (For the termination check, I'm not sure if there is much to be done with the current infrastructure. I'm certainly not eager to dive into it at the moment.)

**Comment by guillaumebrunerie** [comment]
I’m having another issue somewhat similar to https://github.com/agda/agda/issues/4122#issuecomment-544493991 (there is yellow where there wasn’t yellow before the change that wrapped every element of a proposition in a `DontCare`):

```agda
{-# OPTIONS --prop #-}

data _≡_ {A : Set} (a : A) : A → Set where
  refl : a ≡ a

postulate
  funextP : {A : Prop} {B : A → Set} {f g : (a : A) → B a} (h : (x : A) → f x ≡ g x) → f ≡ g

test      : {A : Prop} {B : A → Set} {f g : (a : A) → B a} (h : (x : A) → f x ≡ g x) → f ≡ g
test h = funextP h
```

In `test`, Agda does not figure out what `B` should be. It does find out `f` and `g` (of type `(a : A) → B _`) but cannot use that information to figure out that `B` should be `B`.

**Comment by jespercockx** [comment]
Fixed now, let me know if there's further issues.
