### ISSUE TITLE
Bug in the HTML backend

### ISSUE THREAD

**Issue by gallais** [agda/agda#4123]
Noticed by @laMudri: In [Relation.Binary.Rewriting](https://agda.github.io/agda-stdlib/v1.1/Relation.Binary.Rewriting.html) we get the following broken syntax highlighting:

![oops-agda-colours](https://user-images.githubusercontent.com/1094905/66402951-a8c46c00-e9dd-11e9-86a4-82d2e1bb2c17.png)

The corresponding html code is clearly not the right thing:

```html
<a id="608" class="Keyword">ope</a>
<a id="611" class="Bound">n</a>
<a id="613" class="Bound">i</a>
<a id="614" class="Keyword">m</a>
<a id="615" class="Bound">p</a>
<a id="616" class="Keyword">ort</a>
<a id="619" class="Bound"> </a>
<a id="620" href="Level.html" class="Module">L</a>
<a id="621" href="Level.html" class="Datatype">e</a>
<a id="622" href="Level.html" class="Module">v</a>
<a id="623" href="Level.html" class="Bound">e</a>
<a id="624" href="Level.html" class="Module">l</a>
<a id="625" class="Datatype">o</a>
<a id="627" class="Keyword">p</a>
<a id="628" class="Bound">e</a>
<a id="629" class="Keyword">n</a>
<a id="631" class="Keyword">import</a>
```

**Comment by nad** [comment]
I've also noticed this kind of thing, but I think I failed to reproduce the problem. Do you have a reproducible test case?

**Comment by gallais** [comment]
Travis seems to generate this for the dev version of [`Relation.Binary.Rewriting`](https://agda.github.io/agda-stdlib/Relation.Binary.Rewriting.html) too
so I would guess it is a (non-minimal) candidate.

Tried `agda --html --ignore-interfaces Relation/Binary/Rewrite.agda` just now
and I got the same problem

**Comment by nad** [comment]
I'm closing this issue now, because it seems to be the same as issue #4260.
