### ISSUE TITLE
Tactic modality for record fields

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#4124]
It would be nice if it was possible to have a record field with an `@tactic` modality. Currently this example parses but Agda silently drops the tactic:
```agda
open import Agda.Builtin.Unit
open import Agda.Builtin.Bool
open import Agda.Builtin.Reflection renaming (bindTC to _>>=_)

defaultTo : {A : Set} (x : A) → Term → TC ⊤
defaultTo x goal = do
  `x ← quoteTC x
  unify goal `x

record Class : Set where
  constructor con
  field
    x : Bool
    @(tactic defaultTo x) {y} : Bool
open Class

test : Class
test = con true
```

**Comment by UlfNorell** [comment]
Currently there's no place put the tactic in the abstract syntax. I think the `DefInfo` would be a good candidate.

**Comment by UlfNorell** [comment]
Question: when eta-expanding a meta with tactic fields, should the tactic run on the fresh metas? Example:
```agda
infix 0 such-that
syntax such-that a (λ x → P) p = a is x such-that p proves P
such-that : {A : Set} (x : A) (P : A → Set) → P x → A
such-that x _ _ = x

bla : Class
bla = _ is c such-that refl proves c .x ≡ true
```
Do we get unsolved meta for `y` or `y` = `true`?

I think we have to leave it unsolved, otherwise eta-expansion would lose solutions.
