### ISSUE TITLE
Coercion from irrelevant to relevant function space should eta-expand

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#4133]
While working on the (final remaining subproblem of) #2170, I (re)discovered that Agda allows the subtyping rule "if `f : .A -> B` then `f : A -> B`". This is obvious nonsense, `f : .A -> B` only implies that `\x -> f x : A -> B`. We could make use of the `coerce` function to insert this lambda when necessary.

Since this does not seem to be the *direct* cause of #2170, I'm creating this issue to avoid forgetting about it.

**Comment by andreasabel** [comment]
I agree with the action plan.  However, I disagree with

> This is obvious nonsense,

Since Agda does not fully erase irrelevant arguments in the compiler backend, but replaces them by a dummy argument, this subtyping rule is sound.

**Comment by jespercockx** [comment]
But it leads to the construction of ill-typed terms! If we have `f : .A -> B` but apply it as a function of type `A -> B`, then the argument gets a `relevant` argInfo instead of the expected `irrelevant`. This messes up several things, in the case of #2170 it causes trouble for the occurs check.

**Comment by andreasabel** [comment]
Ah, yes, this is #3986 (forgot about it). See also PR #3914.  
Closing as duplicate.
