### ISSUE TITLE
Constructor disambiguation picks non-unique solution

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#4135]
In connection to working on the refactoring 8d20d5575c2f863fb13fa445309b8d53ee8896d3 of the disambiguation introduced in fea1dd1f1889fb122320314c0bb7d6a6126f6dd5, I am finding that we can bring Agda to assign a non-unique solution to a meta through its (too eager) disambiguation mechanism.
```agda
module _ where

open import Agda.Builtin.Bool

module Foo (b : Bool) where

  data D : Set where
    c : D

open Foo true
open Foo false

test : Foo.D {!!} → Set
test c = {!!}

-- C-c C-=
```
Agda has decided on
```
?0 := true
```
via the course of constructor disambiguation.
This contradicts the principle of only assigning unique solutions to metas.

The current behavior exists since 2.5.4, before then Agda's reaction was:
```
Can't resolve overloaded constructors targeting the same datatype
(AmbiguousConstructor.Foo.D): AmbiguousConstructor._.c
AmbiguousConstructor._.c
when checking that the pattern c has type Foo.D ?0
```
I confess I prefer the current behavior over the old error, but ideally, Agda would not solve the meta to `true` when `false` is an equally justified solution.

**Comment by andreasabel** [comment]
Note that on the RHS we do get the `Can't resolve overloaded constructors targeting the same datatype`:
```
c' : Foo.D ?
c' = c
```

**Comment by andreasabel** [comment]
LHS constructor disambiguation is realized here:
https://github.com/agda/agda/blob/ab41ff6a63b0b153f588f2f58fa16f049b6f0ef1/src/full/Agda/TypeChecking/Rules/LHS.hs#L1651-L1665
I believe the problem is that when trying to disambiguate allowing new constraints we first succeed with constraint `?0 := true`, but when the second constructor is tested the generated constraint `?0 := false` contradicts the first constraint, leading to an exception.  This is interpreted as only the first constructor being well-typed under new constraints.

What we should do is to try each constructor in the original state, retaining the new state created by each constructor attempt.  If there is only one success, we continue with the state created there, otherwise we roll back.

**Comment by andreasabel** [comment]
After 2 hours of debug printing, it seems that the problem is that `noConstraints` is not sufficient:
https://github.com/agda/agda/blob/ab41ff6a63b0b153f588f2f58fa16f049b6f0ef1/src/full/Agda/TypeChecking/Rules/LHS.hs#L1710-L1711
We also need to disallow solving metas.
Kinda obvious.  However,  I intuitively read `noConstraints` as doing its job, meaning "no information gain" or "no further constraining".  Sigh.

**Comment by UlfNorell** [comment]
Its semantics is "either solve the problem completely or not at all". The "no constraints" refers to the fact that no constraints should be left unsolved after running the action.

**Comment by andreasabel** [comment]
> Its semantics is "either solve the problem completely or not at all". The "no constraints" refers to the fact that no constraints should be left unsolved after running the action.

Yes.  I misinterpreted it, believing in the correctness of the code using it.

I am going to introduce `nonConstraining` to express "no information gained on solutions".

UPDATE: Part of my confusion may stem from the fact that `C-c C-=` ("show constraints") shows the "constraint" `?0 := true`.  Yet internally this does not fall under "constraints" since it is already a solution.

**Comment by andreasabel** [comment]
The present problem is actually a regression in 2.5.4 possibly introduced by fea1dd1f1889fb122320314c0bb7d6a6126f6dd5.  Up to 2.5.3 the error message was a good one:
```
Can't resolve overloaded constructors targeting the same datatype
(Issue4135.Foo.D): Issue4135.True.c Issue4135.False.c
when checking that the pattern c has type Foo.D ?0
```
on 
```agda

data Bool : Set where
  true false : Bool

module Foo (b : Bool) where
  data D : Set where
    c : D

open module True  = Foo true
open module False = Foo false

test : Foo.D ? → Set
test c = ?
```
We should try to get this error message back.  At the moment (see also #4130 and #4602) the error is (when fixing disambiguation:
```
Ambiguous constructor c.
It could refer to any of
  Foo.D.c (introduced at /Users/abel/play/agda/bugs/Issue4135.agda:15,5-6)
  Foo.D.c (introduced at /Users/abel/play/agda/bugs/Issue4135.agda:15,5-6)
when checking that the pattern c has type Foo.D ?0
```

**Comment by andreasabel** [comment]
Getting there... but this silly little issue is consuming a full work day.  If you were just to fix all open issues we currently have by yourself, @UlfNorell, you'd have your next 7 years of Agda development filled... 😆 .

@andreasabel commented:
> The present problem is actually a regression in 2.5.4 possibly introduced by [fea1dd1](https://github.com/agda/agda/commit/fea1dd1f1889fb122320314c0bb7d6a6126f6dd5). Up to 2.5.3 the error message was a good one:

I don't even seem to read my own problem descriptions. 😆 
I already said this above, but did not seem to want it label a regression then.

**Comment by andreasabel** [comment]
We have the dual problem for projections, unsurprisingly:
```agda
data Bool : Set where
  true false : Bool

module Foo (b : Bool) where
  record R : Set where
    field f : Bool
  open R public

open module True  = Foo true
open module False = Foo false

test : Foo.R {!!}
test .f = {!!}

-- succeeds with constraint ?0 := true
```
However, for projections this was wrong from the beginning, meaning as soon as overloaded projections were allowed (2.5.2).  At that time, I did not care about this issue, except when I was forced to care (#1975, #1976).

**Comment by andreasabel** [comment]
Fixed the analogous problem for projections.  I did not enhance the disambiguation for projections for case `constraintsOk` to the same power as for constructors, only fixed the OP, keeping the status quo otherwise.

One down, may spawn three, in the battle of Hercules with the Hydra.
