### ISSUE TITLE
Overzealous pruning of metavariable with irrelevant argument

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#4136]
(issue found while working on a potential solution of #4134 while working on a solution of #2170)

```agda
postulate
  A : Set
  f : .A → A

data _≡_ (x : A) : A → Set where
  refl : x ≡ x

mutual
  X : .A → A
  X = _

  Y : A → A
  Y = {!λ x → x!}

  Z : A → A
  Z = {!λ x → x!}

  test : ∀ x → X (Y x) ≡ f (Z x)
  test x = refl
```
Try to give the solution `λ x → x` for `Z`, this is rejected with message:
```
Cannot instantiate the metavariable _18 to solution x
since it contains the variable x
which is not in scope of the metavariable or irrelevant in the metavariable but relevant in the solution
when checking that the expression λ x → x has type A → A
```
However, giving the solution `λ x → x` for `Y`, then reloading the file (important!), and *then* giving the solution for `Z` is accepted. 

What happens is that when solving the equation `X (Y x) ≡ f (Z x)`, `x` is not considered to be a dependency of `X` because it is (1) irrelevant and (2) not `Unguarded`. So in the pruning phase (which is run *before* checking that the arguments of `X` are in the pattern fragment), the dependency of `Z` on `x` is pruned. However, there is a solution for `Y` which makes the dependency of `X` on `x` into an `Unguarded` one (namely `Y := λ x → x`). So Agda should not be so eager to trust the outcome of the free variable analysis when there are still other unsolved metas involved.

**Comment by jespercockx** [comment]
I'm wondering whether we should even be doing any kind of pruning of metavariables that occur in irrelevant positions in the solution, since any solution that *does* use a certain variable can always be definitionally equal to a solution that *doesn't*.  In this sense this issue is similar to #2876. The difference is that the issue here might be easier to solve since it's easy to tell if we're in an irrelevant position, but not always easy to tell if we're in a "eta-unit" position.

**Comment by andreasabel** [comment]
> any solution that _does_ use a certain variable can always be definitionally equal to a solution that _doesn't_.

Except for that darn empty types!

**Comment by jespercockx** [comment]
There could still be *another* variable of the same empty type, no? So we can still not rely on any *particular* variable being present, even if we know that there must be *some* variable.
