### ISSUE TITLE
Printing of DontCare should not use dot syntax

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#4141]
Currently terms that are marked internally as `DontCare` are printed as a dotted term `.t`. I propose that they should be printed instead as either `_` or `t` (when `--show-irrelevant` is enabled). See also #316, #3337, and #4122.

**Comment by andreasabel** [comment]
Testcase?!

**Comment by jespercockx** [comment]
Two test cases in https://github.com/agda/agda/commit/7383b7e4b637a3371524abeebc76c66659573067
