### ISSUE TITLE
defCopatternLHS needs to be set when record expression were translated to copatterns

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda#4142]
consider the following program

```agda
open import Level
open import Relation.Binary.PropositionalEquality

record single : Set (suc 0ℓ) where
  -- eta-equality needs to enable to make the following proof work
  field
    A : Set

  pack : single
  pack = record { A = A }

lem : (x : single) → x ≡ single.pack x
lem x = {!refl!}
```

to make the proof to work, either

* turn on `eta-equality` in the definition of `single`, or
* case split on `x`.

however, [the doc](https://agda.readthedocs.io/en/v2.6.0.1/language/record-types.html#eta-expansion) seems to indicate that `eta-equality` is on by default. so why this program doesn't work? is this a bug or just some subtlety?

**Comment by andreasabel** [comment]
This seems to be another regression introduced by the record-expression-to-copattern-translation (ace8e0d099402a625ac460862ae0a81fcec538d4).  There, it was forgotten to mark the replaced definition of `pack` with flag `defCopatternLHS = True`, this is why eta-expansion for the equality of neutrals `w = pack w` does not kick in.

**Comment by andreasabel** [comment]
Fixed this by making the record-expression-to-copattern-translation remember whether a new copattern match was introduced, and if needed update the `defCopatternLHS` flag when the translation is revisited after positivity checking.

A quicker fix could have been to simply recompute the `defCopatternLHS` via `hasProjectionPattern` such as it is done in `Def.hs`.  Ideally, the `defCopatternLHS` could just memoize the `hasProjectionPattern` on the compiled clauses of a signature entry.  Here, OO techniques like protected access could ensure that the value of `defCopatternLHS` is always correct.
