### ISSUE TITLE
Loss of subject reduction with rewriting and abstract

### ISSUE THREAD

**Issue by sattlerc** [agda/agda#4147]
The following code is accepted by a recent version of master (1845cb0, Sep 16). 

```agda
{-# OPTIONS --rewriting --confluence-check #-}

data _==_ {i} {A : Set i} : (x y : A) → Set i where
  refl : {a : A} → a == a

{-# BUILTIN REWRITE _==_ #-}

data ⊥ : Set where

record ⊤ : Set where
  constructor tt

module Test (p : ⊥ == ⊤) where
  abstract
    A : Set
    A = ⊥

    q : A == ⊤
    q = p

    {-# REWRITE q #-}

  f : A
  f = tt

  abstract
    g : ⊥
    g = f
    -- g reduces to tt, which does not have type ⊥.
```

Note that it is rejected with --double-check:
```
The constructor tt does not construct an element of ⊥
when checking that the clause g = f has type ⊥
```

I'n not sure what the semantics of rewriting rules in abstract blocks are.

I would have expected to be forbidden from declaring the above rewriting rule inside the abstract block since the left-hand side reduces. Declaring the rewriting rule outside the abstract block makes more sense, but then leads to confluence problems when re-entering abstract. 

To be safe, it would seem the confluence checker would have to unfold abstract definitions when checking rewriting rules because the user can always re-enter abstract. That's a shame, because I often like to use abstract in combination with rewriting to reduce with an equality where the left-hand side head is a parameter (by creating an abstract duplicate of the parameter). A workaround is to postulate "every contractible type has an element" (certainly admissible) and then use this to produce the abstract (in the informal sense) copy of the parameter.

I guess this would be easier for a version of abstract where different abstract blocks do not relate to each other (that's how I would want to use it almost always).

**Comment by nad** [comment]
> because the user can always re-enter abstract.

It would be easy to check if there are any subsequent uses of `abstract` in the same "scope".

**Comment by jespercockx** [comment]
Thanks for reporting. There seem to be two main issues here:

- The confluence check should be able to look through `abstract` if a rewrite rule is added inside an abstract block (or if the abstract block could still be reopened).
- Rewrite rules declared *inside* an abstract block should not fire outside that abstract block (see #2335)

For the question about abstract blocks being related, @nad informed me that there *is* a way to make an abstract definition that is impossible to 'see through' by future abstract blocks, like this:

```agda
private
  module M where
    abstract
      f : A
      f = ...
open M public
```

Note that this doesn't work with anonymous modules, which is both quite surprising and annoying (see https://github.com/agda/agda/issues/2207).

**Comment by sattlerc** [comment]
That's great, I wasn't aware that private and abstract talk to each other. Thanks, that would solve my use cases. I guess the complexity is then shifted to the confluence checker in figuring out whether an abstract definition could still be reopened.

**Comment by nad** [comment]
The use of `private` in @jespercockx's example is only to avoid polluting the name space. See the [documentation](https://agda.readthedocs.io/en/latest/language/abstract-definitions.html) for more details.

**Comment by sattlerc** [comment]
I see, thanks for clarifying.

**Comment by jespercockx** [comment]
I fixed the former issue, the latter one is part of #2335.

**Comment by sattlerc** [comment]
Thanks!
