### ISSUE TITLE
Internal error with instance and variable

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#4149]
Split this bug out from https://github.com/agda/agda/issues/4137#issuecomment-544490634.
```agda
open import Agda.Primitive

postulate

  A : Set
  F : ∀ {ℓ} → Set ℓ → Set ℓ

record R (Q : ∀ {ℓ} → Set ℓ → Set ℓ) ℓ : Set (lsuc ℓ) where
  field
    f : {A : Set ℓ} → F A → Q A
    g : {A : Set ℓ} → Q A → F A

open R ⦃ … ⦄

module M (_ : Set₁) where

  postulate

    G : ∀ {ℓ} → Set ℓ → Set ℓ

module _ (_ : Set) where

  open M Set

  postulate

    instance

      _ : R G lzero

  g′ : G A → F A
  g′ = g

  variable

    x : F A

  postulate

    P     : F A → Set
    works : {x : F A} → P (g′ (f x))
    fails : P (g′ (f x))
```
Agda reports an internal error at https://github.com/agda/agda/blob/94392cd0248f803026ae22cdc7e891510ac3fd32/src/full/Agda/TypeChecking/Substitute.hs#L84

**Comment by andreasabel** [comment]
```
agda-bisect --simple-setup --bad HEAD --good v2.6.0 Issue4149.agda 
```
says:
2f6f0c3d70a209011b28e30015cc1593135c89d0 is the first bad commit
> Author: me
> Date:   Sun Aug 18 00:51:32 2019 +0200
>
>    [ #1346 ] Make renFixity field deep-strict
>    
>    Does not solve breakage of Issue #1829, though.

However, such a commit does not exist in master.  Probably my invocation of `agda-bisect` was wrong.

**Comment by nad** [comment]
My bisection (see #4137) pointed to 72c8afd53b7b3e6b0af2b73fb6066f9e4140fdfd ("[ #4125 ] Use unreduced type in checkExpr").

**Comment by andreasabel** [comment]
Same here now.  In my previous bisect, I was accidentially on some local branch, I think.  On a second try I also got:
72c8afd53b7b3e6b0af2b73fb6066f9e4140fdfd is the first bad commit
> Author: me
> Date:   Sun Oct 13 16:18:49 2019 +0200
>
>    [ #4125 ] Use unreduced type in checkExpr
>    
>    This prevents some unnecessary unfolding in types solved by conversion,
>    for the benefit of the interactive user of Agda and the readability of
>    context entries.

Bisection took only little more than 30 min.

**Comment by andreasabel** [comment]
My patch (less reduction in the type checker) exposed a flaw with generalization.  Here is a version of the test case with named bound variables:
```agda
{-# OPTIONS --show-implicit #-}
{-# OPTIONS -v impossible:100 #-}
{-# OPTIONS -v tc:30 #-}

open import Agda.Primitive

postulate

  A : Set
  F : ∀ {ℓ} (XF : Set ℓ) → Set ℓ

record R (Q : ∀ {ℓ} (XQ : Set ℓ) → Set ℓ) ℓ : Set (lsuc ℓ) where
  field
    f : {A : Set ℓ} (fa : F A) → Q A
    g : {A : Set ℓ} (qa : Q A) → F A

open R ⦃ … ⦄

module M (X : Set₁) where

  postulate

    G : ∀ {ℓ} (XG : Set ℓ) → Set ℓ

module N (Y : Set) where

  open M Set

  postulate

    instance

      _ : R G lzero

  g′ : (ga : G A) → F A
  g′ = g

  variable

    z : F A

  postulate

    P     : (p : F A) → Set
    works : {z : F A} → P (g′ (f z))

    fails : P (g′ (f z))
```
The debug printing says towards the end:
```
pruning
  _Q_54 : {ℓ : Level} → Set ℓ → Set ℓ
  GenRecTel is var 0
  Γ   = (Y : Set)
  Θ   = {z : Issue4149.F {lzero} Issue4149.A}
  Δ   =
  σ   = wkS 1 idS, Issue4149.N.mkGeneralizeTel {@0}
  γ   = idS
  δ   = idS
  ρ   = wkS 1 idS, Issue4149.N.mkGeneralizeTel {@0}
  ρ⁻¹ = wkS 1 idS, @0 .Issue4149.N..generalizedField-z
  Θγ  = {z : Issue4149.F {lzero} Issue4149.A}
  Δσ  =
  _A  = Just (Set @0 -> Set @0)
...
after kill analysis
  metavar = _Q_57
  kills   = [True,False]
  kills'  = [True, {False}, False]
  oldType = (Y₁ : Set) {z : F {lzero} A} →
            Set (record { .generalizedField-z = z }) →
            Set (record { .generalizedField-z = z })
  newType = {z : F {lzero} A} →
            Set (record { .generalizedField-z = z }) →
            Set (record { .generalizedField-z = z })
```
As you can see here, we have an illformed type here: `Set (record { .generalizedField-z = z })` which has been created by the generalization feature.

There seems to be a brittleness in the generalization engine which was exposed by my change.  However, as I am lacking theory and practice of generalization (in particular in connection with instance search), I am in no position to fix this problem.

**Comment by UlfNorell** [comment]
> ... exposed a flaw with generalization ...

> ... which has been created by the generalization feature ...

> There seems to be a brittleness in the generalization engine which was exposed ...

Or quite possibly, there is a bug somewhere else that gets exposed by generalize... Here is a test case without generalizable variables or instance arguments:

```agda

open import Agda.Primitive
open import Agda.Builtin.Equality

data begin : Set where end : begin

infix 5 _==_
_==_ : ∀ {a} (A B : Set a) → A ≡ B → Set
_==_ _ _ _ = Level

infix 0 _!
_! : ∀ {a} {A : Set a} → (A ≡ A → Set) → Set
F ! = F refl

- : begin

Y : Set → (l : Level) → Set → Set l
Y = _

Z : (l : Level) → Set → Set l
Z = _

postulate
  bad : (A : Set) (B : Set) (l : Level) (C : Set)
        (let X : Set l; X = _)
      → Y A l C == (X → Level) !  -- prune B
      → Z   l C == (X → Level) !  -- prune A
      → X

- = end

-- Unsolved meta:
-- _32 : Set B
```
The problem is in metavariable pruning. Specifically when pruning a meta multiple times. Here

https://github.com/agda/agda/blob/7c91c66e01e69f25402589646a1246483d1e8445/src/full/Agda/TypeChecking/MetaVars/Occurs.hs#L972-L977

we create the "permutation" for the new meta dropping the killed arguments, completely ignoring the permutation for the original meta.
