### ISSUE TITLE
Renaming declarations within a module may cause name clash

### ISSUE THREAD

**Issue by ysharoda** [agda/agda#4154]
Consider the following definition of a module with two type declarations
```agda
  module TwoTypes where
    postulate
      U : Set₀
      W : Set₀
```
It is possible to define a module which renames one of these two declarations to the other
```agda
  module NameClash = TwoTypes renaming (W to U)
```
Agda accepts this rename, until one of the declarations is referenced
```agda
  test : Set₀
  test = {!NameClash.U!}
```
When trying C-c C-w, we get the following error
```
NameClash.U is in scope as
  * a defined name bug_name_clash.NameClash.U brought into scope by
    - the application of Carrier at /Users/yasmine/Documents/gitlab/TheoryPresentations/papers/TPC/views/bug_name_clash.lagda:21,22-29
    - its definition at /Users/yasmine/Documents/gitlab/TheoryPresentations/papers/TPC/views/bug_name_clash.lagda:15,7-8
  * a defined name bug_name_clash.NameClash.W brought into scope by
    - the application of Carrier at /Users/yasmine/Documents/gitlab/TheoryPresentations/papers/TPC/views/bug_name_clash.lagda:21,22-29
    - its definition at /Users/yasmine/Documents/gitlab/TheoryPresentations/papers/TPC/views/bug_name_clash.lagda:16,7-8
```
Without attempting to access any of the declarations of the NameClash module, the file is loaded with no error or warning.

This corresponds to the Haskell treatment of name clashes in modules, which is documented in (https://www.haskell.org/onlinereport/haskell2010/haskellch5.html) Section 5.5.2. The following is a quotation from the source:
"It is not an error for there to exist names that cannot be so resolved, provided that the program does not mention those names."

**Comment by nad** [comment]
If you want to avoid the name clash, then you can use `hiding (U)`.

In some cases name clashes may be what is intended (because Agda supports overloading for constructors and projections), so I do not think this kind of thing should be ruled out entirely.

**Comment by andreasabel** [comment]
```agda
module M where
  postulate
    A B : Set

module N = M renaming (A to B)
```
Agda should reject the last statement, for the simple fact that it does so if one makes the `using` explicit:
```
module N = M using (B) renaming (A to B)
```
```
Ambiguous imports from module N for B
when scope checking the declaration
  module N = M using (B) renaming (A to B)
```

**Comment by andreasabel** [comment]
Related: #3057.

**Comment by asr** [comment]
Removed whitespace issue in the title (detected when running the `closed-issues-for-milestone`).
