### ISSUE TITLE
Printing implicit lambdas with --show-implicit

### ISSUE THREAD

**Issue by xekoukou** [agda/agda#4160]
```agda


data Bool : Set where
  true : Bool
  false : Bool

data D : Set where
  d : D

data E : Set where
  e : E

HSet : Set₁
HSet = {b : Bool} → Set

-- Here HA is HSet
-- The output of this function is the set E, for input HSet G.
⊨ : HSet → Set
⊨ HA = HA {true}

G : HSet
G {true} = E
G {false} = D

-- Here ⊨ accepts Set as input , not HSet.
boo : ⊨ (G {false})
boo = d

```

**Comment by UlfNorell** [comment]
The type checker inserts an implicit lambda so you get the HSet `λ {_} → G {false}`. You can see it using a bit of reflection:
```agda
open import Agda.Builtin.Reflection renaming (bindTC to _>>=_)
open import Agda.Builtin.Unit
open import Agda.Builtin.List
open import Agda.Builtin.Equality

macro
  typeOf : Name → Term → TC ⊤
  typeOf x hole = do
    t  ← inferType (def x [])
    `t ← quoteTC t
    unify hole `t

check : typeOf boo ≡
        def (quote ⊨)
          (arg (arg-info visible relevant)
            (lam hidden (abs "b"
              (def (quote G)
                (arg (arg-info hidden relevant)
                     (con (quote false) []) ∷ []))))
          ∷ [])
check = refl
```

**Comment by xekoukou** [comment]
I think that there are two problems here : 

A.

If I ask agda to show me the hidden arguments, and to not normalize, this is the info I get from the hole :
```
Goal: ⊨ (G {false})
```

This , to me, is obviously wrong. It should have been something like : 
```
Goal: ⊨ λ {_} -> (G {false})
```

So the first problem is the lack of documentation and the incorrect information given by agda.

B. 
The domain of ```⊨``` is greater than the one that is possible to use inside agda. All the HSets that it can get are constant with regards to the implicit argument.
Maybe the current formulation is necessary from a type theory point of view, but it is highly counter-intuitive from a use point of view.

So maybe we should improve the hole message and the documentation.

**Comment by UlfNorell** [comment]
A. Good point. I renamed and reopened the issue.
B. I don't understand. In this case you happened to get a constant HSet, but nothing stops you from writing the lambda explicitly: `boo : ⊨ λ {b} → G {b}`

**Comment by xekoukou** [comment]
B. I was wrong about B. I thought that the hole showed Set, but it showed HSet. So the point is mute.
```
Goal: HSet
```
