### ISSUE TITLE
Instances that are not in scope are candidates for instance resolution

### ISSUE THREAD

**Issue by nad** [agda/agda#4166]
Consider the following code:
* `A.agda`:
  ```agda
  open import Agda.Builtin.Bool

  module A {b : Bool} where

  instance

    i : Bool
    i = b
  ```
* `B.agda`:
  ```agda
  module B where

  open import Agda.Builtin.Bool

  open import A {b = true} as A′

  it : ⦃ Bool ⦄ → Bool
  it ⦃ b ⦄ = b

  b : Bool
  b = it
  ```
Note that there is only one instance in scope at the end of the file: `A′.i`. However, Agda treats `A.i` as being in scope, so the instance argument in the body of `b` is not resolved:
```
Failed to solve the following constraints:
  Resolve instance argument _3 : Bool
  Candidates
    true : Bool
    b₁ : {b = b₁ : Bool} → Bool
```

I noticed this problem when debugging some slow instance resolution. In that case the instances were resolved correctly, but the resolution engine had more candidates than necessary to filter out.

**Comment by jespercockx** [comment]
Could the problem be that `open import A {b = true} as A′` is desugared to something like
```agda
import A
module A' = A {b = true}
open A'
```
which *would* bring both instances into scope?

**Comment by nad** [comment]
@ulfn, @jespercockx and I discussed a possibly better desugaring:
```agda
module A' where
  import A
  private
    module Fresh = A {b = true}
  open Fresh public
open A'
```

**Comment by UlfNorell** [comment]
So the actual desugaring is
```agda
import Issue4166.Import as Fresh
module A' = Fresh {b = true}
open A'
```
and the problem is that instance search thinks that the contents of `Fresh` is in scope.
