### ISSUE TITLE
Restrict pattern matching for erased arguments of single-constructor data types

### ISSUE THREAD

**Issue by nad** [agda/agda#4172]
The following code should be rejected when the K rule is turned off:
```agda
open import Agda.Builtin.Equality

subst-erased : {A : Set} {x y : A} (P : A → Set) → @0 x ≡ y → P x → P y
subst-erased P refl p = p
```
Perhaps it could be allowed when the K rule is turned on.

The following code could perhaps be allowed even when the K rule is turned off:
```agda
record Erased (A : Set) : Set where
  constructor [_]
  field
    @0 erased : A

open Erased

data W (A : Set) (B : A → Set) : Set where
  sup : (x : A) → (B x → W A B) → W A B

lemma :
  {A : Set} {B : A → Set} →
  Erased (W A B) → W (Erased A) (λ x → Erased (B (erased x)))
lemma [ sup x f ] = sup [ x ] λ ([ y ]) → lemma [ f y ]
```

(This issue was broken out of #3855.)

**Comment by nad** [comment]
Here is an example [due to @andreasabel](https://github.com/agda/agda/issues/3855#issuecomment-505759769) that should perhaps always be accepted:
```agda
data ⊥ : Set where

data E : Set where
  c : E → E

magic : @0 E → ⊥
magic (c e) = magic e
```

**Comment by jespercockx** [comment]
I thought `@0` had no impact on the semantics of the function type, so why should it matter whether we have `K` or not? As long as the argument can be erased at runtime, everything is fine! (This could be different for `--cubical`, but that cannot be compiled ATM anyway.)

**Comment by nad** [comment]
The idea is to eventually have a compiler for Cubical Agda (#3753), and cubical code can depend on code that uses `--without-K`. I'd like to avoid introducing breaking changes to code written using `--without-K` when (if?) support is added for compiling Cubical Agda.

If we want to allow this kind of pattern matching when the K rule is turned off, then we could add a new flag for that, and make code that uses this flag incompatible with Cubical Agda.

**Comment by andreasabel** [comment]
I am adding the positive examples (which pass already) as `test/Succeed/Issue4172.agda`.

**Comment by nad** [comment]
Cubical Agda adds (or is planned to add) a new constructor `hcomp` to every data type, right? This means that one-constructor data types become two-constructor data types. However, I'm not sure if this means that pattern matching should always be disallowed for erased arguments of one-constructor data types in Cubical Agda. (Hopefully pattern matching is still OK for the empty type, at least.) The cases for `hcomp` are generated automatically, and I wonder if they can perhaps, in some cases, simply be discarded by the erasure machinery. @Saizan, can you enlighten us?

**Comment by Saizan** [comment]
Cubical Agda plans to add an hcomp for HITs and Indexed datatypes.
Indexed datatypes will actually have an extra `transp`-like constructor.
Datatypes that are only parametrized (in the agda sense) will not have extra constructors,
so the examples with `⊥` and  `W` shouldn't be affected.

Still `hcomp` itself shouldn't be a problem: if the type is otherwise one-constructor we could make hcomp reduce instead.

Being indexed by something whose path type is not "one-constructor" is definitely a problem though, as in the `subst-erased` example. I guess you could see this as the `transp` constructor getting in the way.

**Comment by nad** [comment]
Here is an example based on Figure 5.1 in @rnml's PhD thesis:
```agda
open import Agda.Builtin.Equality
open import Agda.Primitive

variable
  @0 a   : Level
  @0 A B : Set a

coerce : @0 A ≡ B → A → B
coerce refl x = x

sym : {@0 x y : A} → @0 x ≡ y → y ≡ x
sym refl = refl

loopy : {@0 A B : Set a} → @0 A ≡ (A → B) → B
loopy {A = A} {B = B} eq =
  w (coerce (sym eq) w)
  where
  w : A → B
  w x = coerce eq x x
```
The term `loopy` gets compiled to `d22`:
```haskell
d22 ::
  MAlonzo.Code.Agda.Primitive.T4 ->
  () -> () -> MAlonzo.Code.Agda.Builtin.Equality.T12 -> AgdaAny
d22 v0 v1 v2 v3 = du22
du22 :: AgdaAny
du22 = coe du34 (coe du34)
du34 :: AgdaAny -> AgdaAny
du34 v0 = coe v0 v0
```
GHC isn't entirely happy with the resulting code:
```
Compilation error:
Simplifier ticks exhausted
  When trying UnfoldingDone du34
  To increase the limit, use -fsimpl-tick-factor=N (default 100).
   
  If you need to increase the limit substantially, please file a
  bug report and indicate the factor you needed.
   
  If GHC was unable to complete compilation even with a very large factor
  (a thousand or more), please consult the "Known bugs or infelicities"
  section in the Users Guide before filing a report. There are a
  few situations unlikely to occur in practical programs for which
  simplifier non-termination has been judged acceptable.
   
  To see detailed counts use -ddump-simpl-stats
  Total ticks: 7521
```
Note that we get exactly the same Haskell code if the erasure annotations are removed:
```agda
open import Agda.Builtin.Equality
open import Agda.Primitive

variable
  a   : Level
  A B : Set a

coerce : A ≡ B → A → B
coerce refl x = x

sym : {x y : A} → x ≡ y → y ≡ x
sym refl = refl

loopy : {A B : Set a} → A ≡ (A → B) → B
loopy {A = A} {B = B} eq =
  w (coerce (sym eq) w)
  where
  w : A → B
  w x = coerce eq x x
```

**Comment by Saizan** [comment]
I believe that's just a known bug that they decided to not fix in ghc. See third bullet point here:

https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/bugs.html#bugs-in-ghc

**Comment by nad** [comment]
Yes.

**Comment by andreasabel** [comment]
@nad: you can report you implementation of \Omega using type casts to the GHC issue tracker.  Not sure they will accept it as a more realistic program than the one with the negative data type. :)

**Comment by andreasabel** [comment]
Is the integration of `@0` and `--without-K` urgent?  
(As I don't think so, I bump the milestone.)

**Comment by nad** [comment]
> you can report you implementation of \Omega using type casts to the GHC issue tracker.

Perhaps my comment above was unclear. I do not see this as a problem with GHC. Maybe it is not a problem for Agda either, because no problematic binary is generated. However, one might include this kind of code in an example that is not meant to be executed, as part of a development that includes other parts that should be compiled. That kind of problem could perhaps be fixed by not compiling unreachable private definitions.

> Is the integration of `@0` and `--without-K` urgent?

The next release of Agda will be the first with proper support for `@0`. I don't think we should plan to introduce breaking changes for the feature in later releases.

**Comment by UlfNorell** [comment]
> That kind of problem could perhaps be fixed by not compiling unreachable private definitions.

We already get rid of unused private definitions before compilation.

**Comment by nad** [comment]
Great.

**Comment by nad** [comment]
I think we should settle for something conservative now. I suggest that we allow pattern matching for erased arguments in non-erased contexts if the following conditions are satisfied:
* Either the type is not indexed, or `--with-K` is active.
* The case tree contains at most one case. This means that the following code is OK (if the K rule is active):
  ```agda
  open import Agda.Builtin.Bool

  data D : Bool → Set where
    true  : D true
    false : D false

  F : @0 D false → Set₁
  F false = Set
  ```
Does this sound reasonable, or should we be even more conservative? Another option would be to replace the first condition with "The option `--with-K` is active".

**Comment by jespercockx** [comment]
The first option looks reasonable to me.

**Comment by nad** [comment]
Another question: Should erasure annotations be allowed in Cubical Agda? Currently we [do not know](http://www.cse.chalmers.se/~nad/listings/equality/Bool.Very-stable.html) how to compile Cubical Agda in such a way that the annotations are respected. However, disallowing `@0` in Cubical Agda code (or code imported by Cubical Agda code) sounds drastic to me. I suggest that we allow erasure annotations in Cubical Agda for now, with the understanding that there might never be a compiler that supports them.
