### ISSUE TITLE
Allow pattern matching on erased arguments in an erased context

### ISSUE THREAD

**Issue by nad** [agda/agda#4173]
The following code should presumably be accepted:
```agda
open import Agda.Builtin.Bool

@0 F : @0 Bool → Set₁
F true  = Set
F false = Set
```

I tried to make Agda accept this code by tweaking the following test:

https://github.com/agda/agda/blob/49ad0b3f0d39c01bc35123478b857e702b29fb9d/src/full/Agda/TypeChecking/Coverage.hs#L1394-L1396

However, I did not find a simple way to figure out if the pattern matching takes place in an erased context. The `envModality` field in the environment does not contain the quantity 0 when the code above is checked. Is the quantity supposed to be 0? The documentation suggests that it should be:

https://github.com/agda/agda/blob/49ad0b3f0d39c01bc35123478b857e702b29fb9d/src/full/Agda/TypeChecking/Monad/Base.hs#L2573-L2583

In fact, the quantity is `Quantityω QωInferred`, which according to the comment is not allowed.

(This issue was broken out of #3855.)

**Comment by andreasabel** [comment]
Pattern matching is already allowed in the LHS checker, but the coverage checker has not been called in erased context and also does not respect it.  I am fixing this.
