### ISSUE TITLE
Missing modality check in unifier leads to segfaults

### ISSUE THREAD

**Issue by nad** [agda/agda#4174]
The following comment should be addressed in some way:

https://github.com/agda/agda/blob/b8d673bc09bc50f4539114ea90e141127ab60bf4/src/full/Agda/TypeChecking/Rules/LHS/Unify.hs#L914-L921

(This issue was broken out of #3855.)

**Comment by jespercockx** [comment]
@andreasabel since you wrote the comment in question, could you take a look at this?

**Comment by UlfNorell** [comment]
See #4195 for a test case that does lead to segfaults.

**Comment by UlfNorell** [comment]
PR #4281 adds the modality check. I think the check is doing the right thing. If you have a metavariable that could be instantiated with an erased term, we *should* refuse to solve a non-erased argument to a term containing this meta.

cc @andreasabel

**Comment by UlfNorell** [comment]
A few implicit arguments needed to be added in the standard library: agda/agda-stdlib#1008

**Comment by nad** [comment]
This change affects some old code of ours:
```agda
mutual

  data Nonterminal : NonTerminalType where
    e : Nonterminal _ Char

  grammar : Grammar Nonterminal Char
  grammar e = tok '0' ⊛> tok '+' ⊛> ! e
            ∣ tok '0'
```
The underscore is not solved "because the solution cannot be used at relevant, unrestricted modality". This can be fixed in the following way:
```agda
mutual

  private

    i = _

  data Nonterminal : NonTerminalType where
    e : Nonterminal i Char

  grammar : Grammar Nonterminal Char
  grammar e = tok '0' ⊛> tok '+' ⊛> ! e
            ∣ tok '0'
```
However, I think this is a bit ugly. Couldn't Agda be a little smarter?

> If you have a metavariable that could be instantiated with an erased term, we should refuse to solve a non-erased argument to a term containing this meta.

However, if the meta-variable is later instantiated to a term that does not contain any erased subterms, then this solution is fine. Could we postpone the solving until the meta-variable has been fully instantiated?

**Comment by UlfNorell** [comment]
Closing this. Please open a new issue for "maybe Agda could be smarter..."
