### ISSUE TITLE
Disallow or restrict subtyping for @0

### ISSUE THREAD

**Issue by nad** [agda/agda#4175]
The following code is accepted:
```agda
postulate
  F : @0 Set → Set
  G : (Set → Set) → Set

A : Set
A = G F
```
I guess this makes sense. Is the intention to have some kind of subtyping for `@0`, or is the code accepted by accident? My guess would be the latter, because the following code is also accepted:
```agda
postulate
  F : Set → Set
  G : (@0 Set → Set) → Set

A : Set
A = G F
```
This code should not be accepted. Here is an example without postulates that Agda compiles without complaints:
```agda
open import Agda.Builtin.Bool

not : Bool → Bool
not true  = false
not false = true

magic : (@0 Bool → Bool) → @0 Bool → Bool
magic f n = f n

@0 b₁ : Bool
b₁ = true

b₂ : Bool
b₂ = magic not b₁
```
If you load this code in GHCi (8.6.5) and evaluate the term corresponding to `b₂`, then you get `True` as the result. If you remove the `@0` annotations and do the same experiment, then you get `False` instead.

(This issue was broken out of #3855.)

**Comment by andreasabel** [comment]
The necessary check on quantity for subtyping has not been implemented yet, I am fixing this now.
