### ISSUE TITLE
Unifier ignores presence of abstract keyword

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#418]
``` agda
module Bug where

data _≡_ (A : Set₁) : Set₁ → Set₂ where
  refl : A ≡ A

abstract

  A : Set₁
  A = Set

  unfold-A : A ≡ _
  unfold-A = refl

-- I don't think we should solve the meta-variable corresponding to
-- the underscore above. We have two obvious choices, A and Set, and
-- these choices are not equivalent.

```

Original issue reported on code.google.com by `nils.anders.danielsson` on 25 May 2011 at 3:30

**Comment by andreasabel** [comment]
The fix is too restrictive.  It does not take into account, e.g., that in private type signatures metas should not be frozen, since abstract definitions are translucent there.

``` agda
abstract

  A : Set₁
  A = Set

  private
    works : A ≡ A
    works = refl

    test : A ≡ _
    test = refl

-- Since test is private, abstract definitions are transparent in its type.
-- The meta should be solved (by A or Set).
```

**Comment by nad** [comment]
>  It does not take into account, e.g., that in private type signatures metas should not be frozen, since abstract definitions are translucent there.

Why and since when are abstract definitions translucent in type signatures of private definitions (in the same abstract block/group)?

**Comment by andreasabel** [comment]
Since always, it seems.  See the ancient examples in agda/examples/AIM4/bag/.
But I did not know so, either...

**Comment by UlfNorell** [comment]
Doesn't it make sense though? Why wouldn't you be allowed to see through the abstraction in private definitions?

**Comment by nad** [comment]
> Why wouldn't you be allowed to see through the abstraction in private definitions?

The problem in the original post also applies to private definitions.

> Since always, it seems.

No, the following code is rejected when Agda 2.5.1.1 is used, but accepted by the current development version:

```agda
data _≡_ (A : Set₁) : Set₁ → Set₂ where
  refl : A ≡ A

abstract

  A : Set₁
  A = Set

  private

    unfold-A : A ≡ _
    unfold-A = refl
```

**Comment by andreasabel** [comment]
HQ decision: remove feature "private type signatures can see through abstract definitions".

**Comment by nad** [comment]
We came up with an example similar to the following one:

```agda
abstract

  A : Set₁
  A = Set

  private

    id : (X : A) → X → X
    id _ x = x

bad : {!(X : A) → X → X!}
bad = id
```

Note that the type of `bad` is ill-formed, because `A` is not equal to `Set <something>`.

**Comment by andreasabel** [comment]
Issue #2234 made me think about our decision to freeze metas of abstract definitions again.
Why don't we adopt the original alternative 1?  This means, if the user writes a meta variable in an abstract type signature, he gets a solution which is not necessarily unique.  Subsequent behavior in a non-abstract block might be random, depending on which solution Agda chose.  But this does not seem to violate the specification of the abstract function, e.g.

```
abstract
  A : Set1
  unfold-A : A ≡ _
```

This specification says that `A` is equal to something.  Both `A == A` and `A == Set` are valid instances of this specification.  The specification is fuzzy (and hence useless), but if the user wanted this, he can have it.
It seems the drawback of freezing metas in abstract type signatures are greater than the gains.

**Comment by jespercockx** [comment]
If the behaviour of a type signature is random, the type-checker shouldn't rely on it, since any internal change could change the behaviour. So I think freezing the type signatures of `abstract` definitions is the right thing to do.

> HQ decision: remove feature "private type signatures can see through abstract definitions".

I agree, who will finally implement this?

**Comment by nad** [comment]
> I implemented the propsed change: Freeze metas after checking the abstract type signatures, before checking the corresponding definitions.

The following code is accepted, which suggests that meta-variables in abstract type signatures are not always frozen before the bodies are checked:
```agda
abstract

  A : _
  A = Set

  B = Set
```
The following code is rejected:
```agda
abstract

  Abstract-variant-of-Set₁ : Set₂
  Abstract-variant-of-Set₁ = Set₁

  A : _
  A = Set

Rejected : Abstract-variant-of-Set₁
Rejected = A
```
However, the following variant, where the type of `A` is given explicitly, is accepted:
```agda
abstract

  Abstract-variant-of-Set₁ : Set₂
  Abstract-variant-of-Set₁ = Set₁

  A : Abstract-variant-of-Set₁
  A = Set

Not-rejected : Abstract-variant-of-Set₁
Not-rejected = A
```

**Comment by UlfNorell** [comment]
The reason this code is accepted is #655. There are three options:
1. Declare this working-as-intended (accept both `A` and `B`)
2. Don't use `checkAlias` for explicit signature with `_` (accept `B` but not `A`)
3. Don't use `checkAlias` for abstract definitions (accept neither `A` or `B`)

I don't really have a horse in this race, so I don't want to take a decision, but if pressed I would suggest option 2 or 3. @andreasabel what's your take?

**Comment by jespercockx** [comment]
I understand `abstract` as "I shouldn't have to look at the definition of this, the type signature has everything I need", so I'm favour of option 3.

**Comment by jespercockx** [comment]
Consider the following example:
```agda
open import Agda.Builtin.Bool
open import Agda.Builtin.Equality

abstract
  true' : Bool
  true' = true

  test = refl {x = true'}
```
This is currently accepted, and `test` has type `true' ≡ true'`. However, this is not a unique solution: it can have any type between `true ≡ true`, `true ≡ true'`, `true' ≡ true`, and `true' ≡ true'`. So it would be better to reject this definition.

**Comment by andreasabel** [comment]
I am OK with alternative 3.

**Comment by nad** [comment]
I guess that the following code will be rejected with @UlfNorell's most recent changes in place:
```agda
A : Set₁
A = B
  where
  abstract
    B = Set
```
I don't think we should make use of the body of `B` when checking its type signature, but perhaps we could make use of other parts of the code: code that is not abstract, or code in outer abstract blocks. Agda infers the type of `B` in the following piece of code, despite the absence of an implementation:
```agda
A : Set₁
A = B
  where
  B = ?
```

**Comment by UlfNorell** [comment]
Is it a common idiom to use local abstract definitions? If not, I don't think it's worth complicating things just to get a little bit more inference in this case.

**Comment by nad** [comment]
I sometimes use local abstract definitions, but I don't know how often the improved inference would actually help.

**Comment by nad** [comment]
> Agda infers the type of `B` in the following piece of code, despite the absence of an implementation:
> 
> ```agda
> A : Set₁
> A = B
>   where
>   B = ?
> ```
As noted elsewhere (#5304) the inferred type is not unique. Thus I do not think that Agda should infer the type of `B` in the following piece of code:
```agda
A : Set₁
A = B
  where
  abstract
    B = Set
```
However, perhaps it would make sense to infer the value of the underscore in the code below:
```agda
A : Set₁
A = B
  where
  abstract
    B : Set _
    B = Set
```

**Comment by UlfNorell** [comment]
This whole issue is about how we cannot do type inference for (private) abstract functions. Why do you think we should lift that restriction in this particular case?

**Comment by jespercockx** [comment]
Presumably it's because in this case you don't need to look at the *body* of the abstract definition, it is enough to look at the place where it is *used* to infer the metavariable. However, implementing this in a sensible way while ensuring that the definition itself does not influence the inference looks like it could be somewhat gnarly.

**Comment by nad** [comment]
I just noted one instance in which it might make sense for Agda to be a little smarter, in the absence of more compelling use cases I don't think we should take any action on this.

**Comment by martinescardo** [comment]
Perhaps abstract definitions should not be allowed to omit type signatures, given that the manual now says that abstract definitions should include type signature. Such an omission of a type signature caused infinitely long type checking time in an example given in #5279.

**Comment by nad** [comment]
> Perhaps abstract definitions should not be allowed to omit type signatures

That makes sense to me.

**Comment by UlfNorell** [comment]
Please open a new issue for this, with some discussion of the trade-offs. In general, we are moving towards more things being warnings or non-fatal errors, but here you're suggesting moving in the opposite direction. I'd like a bit more than "perhaps" and "makes sense to me".

**Comment by martinescardo** [comment]
The manual says that we should give type signatures of abstract definitions. Then why are we allowed not to give them, with the penality being an infinitely long computation rather than an outright error?
