### ISSUE TITLE
Finish the `EncodeTCM` instance for `DisplayInfo`

### ISSUE THREAD

**Issue by ice1000** [agda/agda#4183]
https://github.com/agda/agda/blob/ed526b5372fffb881d5b6c544be57125f2c7cf1f/src/full/Agda/Interaction/JSONTop.hs#L44-L110

And I need this for a toy I'm working on. Probably taking this myself.

**Comment by ice1000** [comment]
Reference: https://github.com/agda/agda/commit/f9915d9e0ebe6671e4bdc4dd2b44391b5d160ea0

**Comment by banacorn** [comment]
Hope that this will be useful https://github.com/banacorn/agda/blob/json/src/full/Agda/Interaction/JSONTop.hs#L80

Here's the serialization of all of the concrete syntax tree: https://github.com/banacorn/agda/tree/json/src/full/Agda/Interaction/JSON/Syntax

**Comment by ice1000** [comment]
> Here's the serialization of all of the concrete syntax tree: https://github.com/banacorn/agda/tree/json/src/full/Agda/Interaction/JSON/Syntax

Wow look at that. Is this thing ready or there's something missing?

**Comment by ice1000** [comment]
> Hope that this will be useful https://github.com/banacorn/agda/blob/json/src/full/Agda/Interaction/JSONTop.hs#L80

I've pushed a modified version of this into the current master Agda

**Comment by banacorn** [comment]
> Wow look at that. Is this thing ready or there's something missing?

I've built a prototype last year (with agda-mode on Atom as the frontend). 
You can do lots of fancy stuff if the frontend also has access to the AST (especially source locations). For example, when there's a type error, you can hover the cursor on those "code part" of the error message and it will highlight the corresponding source code.

**Comment by ice1000** [comment]
Cool, but you don't have access to the TCM do you? And does that mean you don't have contextual information?

**Comment by banacorn** [comment]
I have access to the TCM, and in fact most of the serialization would need to be done in the TCM.
IIRC that's because most information we need are not readily stored as *Concrete* syntax tree, you need to convert them from *Internal* or *Abstract* to *Concrete*, and that can only be done in the TCM

Edit: relevant PR https://github.com/agda/agda/pull/3192

**Comment by banacorn** [comment]
It would be nice if we can serialize stuff without the TCM, but that's a lot of work.

**Comment by ice1000** [comment]
> I have access to the TCM, and in fact most of the serialization would need to be done in the TCM.

I'm talking about when you're in Atom/Code. Of course you have access to TCM during serialization

**Comment by ice1000** [comment]
I tend to include (and keep it even after the entire AST serialization is implemented) a pretty-printed term because this interface can be used in many places and we shouldn't need to always impl full AST deserialization.

**Comment by banacorn** [comment]
> I tend to include (and keep it even after the entire AST serialization is implemented) a pretty-printed term because this interface can be used in many places and we shouldn't need to always impl full AST deserialization.

We can add some flags for different "depths" of serialization, but then there will be the problem of "where to draw the line".
Or perhaps we can simply just include the pretty-printed term in the serialized JSON.

**Comment by ice1000** [comment]
> We can add some flags for different "depths" of serialization, but then there will be the problem of "where to draw the line".

I'd say it's not necessary, we can simply include all the info. I believe modern deserializers will allow ignoring unknown fields :).

**Comment by jespercockx** [comment]
@ice1000 what's the status on this issue?

**Comment by ice1000** [comment]
> @ice1000 what's the status on this issue?

I'm not sure, there's a lot of thins can be made, but speaking of `instance EncodeTCM DisplayInfo` (`EncodeTCM` supersedes `ToJSON` to some extent), it's already finished (not including serializing the entire AST).
Maybe I should close this?

**Comment by ice1000** [comment]
Probably not, I just saw some `Null`s. Reopening

**Comment by ice1000** [comment]
Will be closed by #4213
