### ISSUE TITLE
Agda uses η-equality for record types defined with no-eta-equality

### ISSUE THREAD

**Issue by nad** [agda/agda#4185]
Consider the following code:
```agda
open import Agda.Builtin.Equality

record Box (A : Set) : Set where
  no-eta-equality
  constructor [_]
  field
    unbox : A

open Box

postulate
  A    : Set
  to   : (P : Box A → Set) →
         ((x : Box A) → P x) → ((x : A) → P [ x ])
  from : (P : Box A → Set) →
         ((x : A) → P [ x ]) → ((x : Box A) → P x)

  works :
    (P : Box A → Set)
    (f : (x : Box A) → P x) →
    from P (to P f) ≡ f
```
This code works fine, but I can make Agda behave strangely by tweaking `works`:
```agda
  fails₁ :
    (P : Box A → Set)
    (f : (x : Box A) → P x) →
    from _ (to P f) ≡ f
```
Here Agda complains about the final `f`:
```
x != [ unbox x ] of type Box A
when checking that the expression f has type
(x : Box A) → P [ unbox x ]
```
It seems as if Agda has instantiated the underscore with `λ x → P [ unbox x ]`. Here is another example:
```agda
  fails₂ :
    (P : Box A → Set)
    (f : (x : Box A) → P x) →
    from P (to _ f) ≡ f
```
Here Agda complains about the penultimate `f`:
```
x != [ unbox x ] of type (Box A)
when checking that the expression f has type
(x : Box A) → P [ unbox x ]
```
Again it seems as if Agda has instantiated the underscore with `λ x → P [ unbox x ]`.

Given that the code works with the underscores instantiated with `P` and that `P` is not definitionally equal to `λ x → P [ unbox x ]` it seems as if Agda has made some kind of mistake. My guess would be that Agda makes use of η-expansion for `Box` even though η-equality has been turned off for this type. The code works fine if `Box` is defined as a data type:
```agda
data Box (A : Set) : Set where
  [_] : A → Box A
```

**Comment by andreasabel** [comment]
Due to invalid η-expansion, the equation
```
  _P (box a) = P (box a)
```
is solved as
```
   _P x = P (box (unbox x))
```
resulting in a subsequent type error as Box has no η.

I have an easy fix: check for eta-equality enabled in `inverseSubst`.
