### ISSUE TITLE
`agda-mode setup' fails if ~/.emacs contains non-ascii characters

### ISSUE THREAD

**Issue by sliedes** [agda/agda#4187]
On Agda-2.6.0.1, running `agda-mode setup' gives me the following error:

agda-mode: /home/sliedes/.emacs: hGetContents: invalid argument (invalid byte sequence)

Temporarily removing a non-ASCII character from my .emacs file fixed this issue.

**Comment by nad** [comment]
Presumably your locale is not consistent with the contents of your `.emacs` file. The documentation of `agda-mode setup` includes the following text: "It is assumed that the .emacs file uses the character encoding specified by the locale."

The .emacs file can use many different character encodings, specified in [complicated ways](https://www.gnu.org/software/emacs/manual/html_node/emacs/Recognize-Coding.html). One could perhaps imagine asking Emacs what character encoding is used for `.emacs`, but there is [no guarantee](https://hackage.haskell.org/package/base-4.12.0.0/docs/System-IO.html#v:mkTextEncoding) that the standard Haskell functions for dealing with character encodings could handle the encoding that is used. Perhaps one could also ask Emacs to convert `.emacs` to and from UTF-8, if all coding systems supported by Emacs satisfy the relevant round-tripping property. However, this sounds rather complicated, so I suggest that we stick with the current solution.

**Comment by sliedes** [comment]
1) I believe my .emacs encoding in fact is consistent with my locale. My locale is generally en_US.UTF-8, with LC_CTYPE=fi_FI.UTF-8. The offending byte sequence in .emacs was 0xc2 0xa0, which is valid UTF-8 for Unicode character NO-BREAK SPACE.

2) For fixing this, it would have been immensely helpful if agda-mode had told where the problem was (I could guess that it was probably somewhere in .emacs...)

**Comment by nad** [comment]
If you want to get to the bottom of this I suggest that you try to create a minimal file that exhibits the problem, using the following code to read the file: `ghc -e 'readFile "<file>"'`.

> it would have been immensely helpful if agda-mode had told where the problem was

I guess one could catch the exception, and then read the file one character at a time and see if the exception is thrown again (the file might have been changed). Contributions are welcome, the [source code](https://github.com/agda/agda/blob/master/src/agda-mode/Main.hs) of `agda-mode` is fairly short.

**Comment by sliedes** [comment]
Hmm, I might have been wrong after all, it works now with that character in .emacs... Maybe I did have something different wrong there, and saving the file in emacs corrected it.
