### ISSUE TITLE
Using `mutual` block trickery, Agda accepts a datatype whose type depends on itself. Should it?

### ISSUE THREAD

**Issue by greatBigDot** [agda/agda#4188]
$ agda --version
    Agda version 2.6.0.1

Note: I think this is a bug, but I'm not 100% sure.

#### Motivation

So I'm trying to make a dependently typed lambda calculus with a universe `U0 :: U0`. (I'm using `::` for the language's typing relation here, reserving `:` for Agda's). To represent this in Agda, the idea is that I'm going to have a type family `U` of well-typed expressions in the language; `exp : U type` should represent `exp :: type`. But since I want no distinction between types and terms, it seems like we should just have `type : U U0`. So:

    data U : U U0 -> Set where
      U0 : U U0

This almost makes sense; the set of terms `U` should be indexed by types, but types are just terms of type `U0` (which itself is just a term of type `U0`. But it looks ridiculous, and Agda reasonably can't work it out, complaining that `U` and `U0` are out of scope in `U`'s definition.

#### The bug (?)

With a bit of tinkering, though, we can actually make something equivalent to the above work:

    mutual
      V = U
      V0 = W0
      data U : V V0 -> Set where
        U0 : U V0
      W0 = U0

Surprisingly, this typechecks! It's the same definition as the unacceptably self-referential one, but with a few copies of `U` and `U0` to make Agda think the right stuff is in scope. I asked about this elsewhere and someone said that it "looks like a bug -- factoring parts of a definition out into a mutual block like this shouldn't matter to the type checker". I think they're right.

Note that we _need_ to use the old `mutual` block syntax here; the newer way would require us to give a type to `V`, which we can't do without referencing `V` or `U`, which moves us back to square one. As such, maybe it's unfair to call this a bug; is the answer just "you aren't supposed to use mutual blocks anymore"?

#### And another thing

Weirdly enough, it breaks again if we further index `U`. (Motivation being that I wanted `exp : U ctx type` iff `ctx ⊢ exp :: type`.) E.g., this doesn't typecheck:

    mutual
      V = U
      V0 = W0
      data U (b : Bool) : V b V0 -> Set where
        U0 : U b V0
      W0 = U0

Agda's complaint isn't anything about circularity; instead it's unsolved metavariables:

    Cannot instantiate the metavariable _27 to solution V b V0 since it
    contains the variable b which is not in scope of the metavariable
    or irrelevant in the metavariable but relevant in the solution
    when checking that the expression V b V0 has type Set

It seems to me that this version and the one that works should either both typecheck or both fail; I don't get why adding a parameter is the deciding factor. (Note: it doesn't seem to matter if it's an index or a parameter.)

Even more weirdly, adding a parameter (or index) DOES work when that parameter is a unit type instead of `Bool`—but only if that unit type is defined with `record` instead of with `data`! What's going on here??

**Comment by UlfNorell** [comment]
This is #1556 I believe.
