### ISSUE TITLE
Record constructors sometimes in record modules, sometimes not

### ISSUE THREAD

**Issue by nad** [agda/agda#4189]
The following code is accepted:
```agda
record ⊤ : Set where
  constructor tt

tt′ : ⊤
tt′ = ⊤.tt
```
Thus it appears as if `tt` is defined in the module `⊤`. However, the following code is rejected:
```agda
open ⊤ using (tt)
```
```
The module ⊤ doesn't export the following: tt
when scope checking the declaration
  open ⊤ using (tt)
```
If I ask Agda to display the contents of the module `⊤`, then I get the following response:
```
Modules
Names
  tt : ⊤
```
The code above is accepted by Agda 2.2.10 (if a module header is added), but Agda 2.3.0 rejects it.

**Comment by andreasabel** [comment]
The release notes for 2.2.6 say:
> Note that the constructor is defined in the *outer* scope, so any fixity declaration has to be given outside the record definition. 
> The constructor is not in scope inside the record module.

Also there is an obscure attribute on concrete names called `OnlyQualified`:
https://github.com/agda/agda/blob/ed526b5372fffb881d5b6c544be57125f2c7cf1f/src/full/Agda/Syntax/Common.hs#L1821-L1827
https://github.com/agda/agda/blob/ed526b5372fffb881d5b6c544be57125f2c7cf1f/src/full/Agda/Syntax/Scope/Base.hs#L68-L70

**Comment by andreasabel** [comment]
Ha, the following variant of your testcase
```agda
record ⊤ : Set where
  constructor tt

module Unit = ⊤ renaming (tt to unit)
```
triggers an internal error:
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Substitute.hs:585
```
https://github.com/agda/agda/blob/ed526b5372fffb881d5b6c544be57125f2c7cf1f/src/full/Agda/TypeChecking/Substitute.hs#L580-L585

The internal error is a regression in 2.5.2.

**Comment by andreasabel** [comment]
Bisection gives:
>  Checking Issue4189 (/Users/abel/tmp/agda-bisect2/Issue4189.agda).
>  An internal error has occurred. Please report this as a bug.
>  Location of the error: src/full/Agda/TypeChecking/Substitute.hs:400
> Stderr:
>  piApply t = El {_getSort = Type (Max []), unEl = Def Issue4189.⊤ []}
>    args = [.(Var 0 [])]
> Verdict: Bad
> a06c2095c7668a34406c4c7f4c8f4be1ee17af86 is the first bad commit
> commit a06c2095c7668a34406c4c7f4c8f4be1ee17af86
> Date:   Wed Jun 8 10:33:23 2016 +0200
>
>    [ fixed #1985 ] eta expand underapplied module applications

My hijacking of this issue looks very similar to #2007.

**Comment by andreasabel** [comment]
`{-# OPTIONS -v tc.mod.apply:100 #-}` shows:
```
applying section ⊤
  args =
  ptel =
  tel  = .(r : ⊤)
  tel' = .(r : ⊤)
  tel''=
  eta  = .(r : ⊤)
  aTel = .(r : ⊤)
addSection Unit .(r : ⊤)
applySection Unit = ⊤
  renModules =
  renNames   = Issue4189.⊤.tt -> Issue4189.Unit.tt
also copying: [(Issue4189.⊤, Issue4189.⊤)]
applySection
new  = Issue4189.Unit
ptel = (r : Issue4189.⊤)
old  = Issue4189.⊤
ts   = [@0]
Common prefix: Issue4189
copyDef Issue4189.⊤ -> Issue4189.⊤
ts' = []
making new def for Issue4189.⊤ from Issue4189.⊤ with 0 args ConcreteDef
args = []
old type = Set
new type = Set
Common prefix: Issue4189.⊤
copyDef Issue4189.⊤.tt -> Issue4189.Unit.tt
ts' = [@0]
making new def for Issue4189.Unit.tt from Issue4189.⊤.tt with 1 args ConcreteDef
args = [Arg {argInfo = ArgInfo {argInfoHiding = NotHidden, argInfoModality = Modality {modRelevance = Irrelevant, modQuantity = Quantityω QωInferred, modCohesion = Continuous}, argInfoOrigin = UserWritten, argInfoFreeVariables = UnknownFVs}, unArg = Var 0 []}]
old type = Issue4189.⊤
Debug printing tc.mod.apply:80 failed due to exception:
  An internal error has occurred. Please report this as a bug.
  Location of the error: src/full/Agda/TypeChecking/Substitute.hs:585
```
Maybe the problem is really just that the record module contains the constructor and tries to apply it to the record value (as all other 0 fields and definitions in the record module).  Of course, the record constructor does not take the record value as argument.  Also, the record constructor does not belong into the record module which has the record value as parameter.

**Comment by andreasabel** [comment]
My recommendation: don't make the record constructor available as qualified by the record module (anyway unsound since it does not take the module parameter; but see also the open-public dispute). Then send the whole `OnlyQualified` hack to Hades.

**Comment by andreasabel** [comment]
Running the test suite after removing record-module qualified record constructors reveals that there is not a single use of that feature in the standard library.

**Comment by nad** [comment]
I have used that feature.

**Comment by andreasabel** [comment]
> I have used that feature.

If needed, one can qualify the record constructor by the parent module.

**Comment by guillaumebrunerie** [comment]
I’ve used that feature as well (e.g. defining Σ-types and product types, both with a constructor called `_,_`, and it is now impossible to unambiguously refer to one of the constructors). I worked around some issues by adding type annotations, and I also had an issue with reflection and `quote`, where it was impossible to quote the constructor of a particular record (as it was impossible to refer to it unambiguously). I did manage to work around this problem as well, but maybe more people will be affected.

I understand the motivation behind the removal of this feature, but it’s too bad that overloaded constructors cannot be disambiguated easily anymore.

**Comment by andreasabel** [comment]
> impossible to unambiguously refer to one of the constructors

Well, only you define both in the same module.

The present issue is that for constructor `c` of record `R` we may wish that `R.c` is a disambiguation of `c` without `c` being part of the record module `R` (because `R` is parameterized).  

As you can see from the original report, it is confusing to see `R.c` but then not finding `c` in `R`.

Everything cannot be salvaged, but most of the old functionality can be simulated as follows:
```agda
module R where
  record R : Set₁ where
    constructor c
    field f : Set
  open R public
open R using (R; c; f) renaming (module R to R')

test : Set → R
test = R.c

test' : Set → R
test' = c

test2 : R → Set
test2 = R.f

test2' : R → Set
test2' = f

test2'' : R → Set
test2'' r = g
  where open R' r renaming (f to g)
```
This separates the namespace `R` for the record by the record module `R'` that can be opened.

**Comment by andreasabel** [comment]
In a larger sense there is a confusion in Agda about _namespaces_ and _parameterized modules_, see #892.
```agda
module M (A : Set) where
  open N public -- "we just live in the namespace M and don't care about the parameter"
  postulate S : Set -- "but I live in the __module__ M and take the parameter onto myself"
```
(Read the utterance of the `N`s in a high pitched voice, and the one of `S` in a low one.)

Capitalizing on this existing confusion, we could see the record constructor in the same way as the open public:
```agda
module Parent where
  postulate R : Set1
  postulate c : Set -> R
  module R (r : R) where
    open Parent public using (c)
    postulate f : Set
```
Of course, you should not really refer to the parent module as it is not yet fully constructed.

But, in the Agda scope checker, modules are allocated before they are fully constructed, so we can actually implement this and have qualified record constructors back in a saner way. (PR #4219)

**Comment by nad** [comment]
@andreasabel, was there some problem with your fix?

**Comment by andreasabel** [comment]
> But, in the Agda scope checker, modules are allocated before they are fully constructed, so we can actually implement this and have qualified record constructors back in a saner way. (PR #4219)

Famous last words, I'd say.  The attempt #4219 brought back the problems described in #282, namely, the "cannot resolve ambiguous constructors targeting the same type".  If I coutinue from here, I will reinvent the `OnlyQualified` hack or something similar.  Thus, I shall leave this issue alone and settle with the removal of the qualified record constructor feature, the original solution to the OP.

The situation seems to be roughly like
```
c -> a : R
module R (r : R) where
  c -> <outer c> -- namespace element
```
where the arrow `->` denotes resolution of a concrete name `c` to an abstract name `a`.  After opening R, we end up with ambiguous constructor `c -> [a,a]`.
