### ISSUE TITLE
option to disable termination checking

### ISSUE THREAD

**Issue by ghost** [agda/agda#4204]
Hello, everyone! A couple months ago, I was writing an Agda library, and I was hoping to be able to continue resuming my “Agda misadventures” soon.

But, as a consequence, I begun wondering if it would be feasible to add an option to disable termination checking in Agda. I know certain pragmas exist, such as `{-# TERMINATING #-}`, but I feel like it would be convenient to have an option to disable it for all functions, instead of having to specify a pragma in each function.

In particular, I don’t really mind that my code wouldn’t work on a (supposed) eager (a.k.a. strict) backend for Agda, nor that Agda wouldn’t be a decidable language anymore. I personally feel like I mind the soundness of programs that have been decided correct, than the decidability of certain edge cases (i.e., I wouldn’t mind for typechecking to be nonterminating for some edge cases).

I would like to be able to write, e.g., infinite lists, and not have to deal with the awkward syntax of codata, nor to have to redefine a bunch of coinductive variants for inductive datatypes (and their appropriate proofs).

I imagine the options could be something along the lines of `--nonterminating` or `--non-terminating`.

I’m sorry if this is an inappropriate request, or if it is dumb/silly for some reason I don’t see.

**Comment by ice1000** [comment]
You may checkout the coinduction support, which allows you to have termination-checking non-terminating functions (well it's actually called "productivity-checking" for coinduction though): https://agda.readthedocs.io/en/v2.6.0.1/language/coinduction.html

**Comment by ghost** [comment]
I acknowledge coinduction in my fourth paragraph. Although, perhaps a more accurate way to have put it would have been:

> I would like to be able to […] not have to deal with the awkward syntax of [sized types], […]

I did not know about “guardedness”, though — I will definitely investigate it (even though the documentation seems to be lacking). But at the same time, my worries about having to redefine datatypes in both inductive and coinductive form (like the standard library does) still bother me a little.

**Comment by ice1000** [comment]
Ok, I missed that.

**Comment by jespercockx** [comment]
https://agda.readthedocs.io/en/v2.6.0.1/tools/command-line-options.html#errors-and-warnings

**Comment by ghost** [comment]
@jespercockx, oh neat! I guess maybe I should have looked a bit harder for it. Thank you! Sorry for the inconvenience.

**Comment by ice1000** [comment]
@jespercockx does that also allow Agda to reduce nonterminating functions?

**Comment by jespercockx** [comment]
It's equivalent to putting a TERMINATING pragma on each function iirc.

**Comment by nad** [comment]
Note that type soundness does not hold for Agda when you turn off the termination checker. Consider the following code:
```agda
module Bad where

open import Agda.Builtin.Bool
open import Agda.Builtin.Equality
open import Agda.Builtin.IO
open import Agda.Builtin.Unit

{-# NON_TERMINATING #-}

trivial : ∀ {a} {A : Set a} {x y : A} → x ≡ y
trivial = trivial

cast : {A B : Set} → A ≡ B → A → B
cast refl x = x

main : IO ⊤
main = cast trivial true
```
When I compile and run this code I get the following output:
```
Bad: internal error: stg_ap_v_ret
    (GHC version 8.6.5 for i386_unknown_linux)
    Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
Aborted (core dumped)
```
GHC handles this kind of code better. Here is a similar Haskell program:
```haskell
{-# LANGUAGE GADTs #-}

data Equal a b where
  Refl :: Equal a a

trivial :: Equal a b
trivial = trivial

cast :: Equal a b -> a -> b
cast Refl x = x

main = cast trivial True
```
When I compile and run this program I get the following output:
```
Bad: <<loop>>
```
The difference between GHC and Agda is that GHC tries to normalise the proof `trivial`. Agda assumes that the proof terminates, and does not even try to evaluate it.

**Comment by ghost** [comment]
I knew there must have been some fundamentality that I was missing that makes my entire issue description sound silly!

Either way, maybe I shouldn’t mind that, as I have (recently) enabled `--omega-in-omega` in my library anyway.

As the library is meant for programming (and not proving), unlike I said in the issue description, I have decided that it’s actually fine for it to be inconsistent, as long as the inconsistency doesn’t show up by accident on programs.

In this particular situation, I hope to be able to always write terminating functions (at least for lazy backends), it’s just that I don’t want to have to actually show Agda that my functions are terminating.

Thank you for the note/warning anyway.
