### ISSUE TITLE
Does Agda tell Emacs where the goals are?

### ISSUE THREAD

**Issue by ice1000** [agda/agda#4207]
I have this `Simplest.agda` file:

```agda
module Simplest where
_ = ?
```

I loaded it with Emacs interaction mode, and the log is:

```el
Agda2> IOTCM "Simplest.agda" NonInteractive Direct ( Cmd_load "Simplest.agda" [] )
(agda2-status-action "")
(agda2-info-action "*Type-checking*" "" nil)
(agda2-highlight-clear)
(agda2-info-action "*Type-checking*" "Checking Simplest (/home/ice1000/git-repos/TrashCan/Simplest.agda).\n" t)
(agda2-highlight-add-annotations 'nil '(1 7 (keyword) t) '(17 22 (keyword) t) '(23 24 (symbol) t) '(25 26 (symbol) t) '(27 28 (symbol) t))
(agda2-highlight-add-annotations 'nil '(1 7 (keyword) t) '(8 16 (module) nil nil ("/home/ice1000/git-repos/TrashCan/Simplest.agda" . 1)) '(17 22 (keyword) t) '(23 24 (function) nil nil ("/home/ice1000/git-repos/TrashCan/Simplest.agda" . 23)))
(agda2-highlight-add-annotations 'nil '(23 24 (function) nil nil ("/home/ice1000/git-repos/TrashCan/Simplest.agda" . 23)))
(agda2-highlight-add-annotations 'nil '(23 24 (function) nil nil ("/home/ice1000/git-repos/TrashCan/Simplest.agda" . 23)) '(25 26 (symbol) t) '(27 28 (symbol) t))
(agda2-highlight-add-annotations 'nil '(1 7 (keyword) t) '(8 16 (module) nil nil ("/home/ice1000/git-repos/TrashCan/Simplest.agda" . 1)) '(17 22 (keyword) t))
(agda2-highlight-add-annotations 'nil '(23 24 (unsolvedmeta)))
(agda2-status-action "")
(agda2-info-action "*All Goals*" "?0 : _1\nSort _0  [ at /home/ice1000/git-repos/TrashCan/Simplest.agda:2,1-2 ]\n_1 : _0  [ at /home/ice1000/git-repos/TrashCan/Simplest.agda:2,1-2 ]\n" nil)
((last . 1) . (agda2-goals-action '(0)))
```

However, I don't think this contains information about the location of the goals. `27 28 (symbol) t` is probably the goal, but I can't tell its difference among other `symbol`s.

Or is Emacs parsing the Agda file and find the goals itself?

**Comment by ice1000** [comment]
Current research -- the code goes here:
https://github.com/agda/agda/blob/eb493024b79640fa9560c355972547ad59cbdcda/src/data/emacs-mode/agda2-mode.el#L1552-L1564
Emacs can find all the goal tokens, and the goal number goes here `((last . 1) . (agda2-goals-action '(0)))`

**Comment by ice1000** [comment]
Thanks @ice1000

**Comment by ice1000** [comment]
No problem @ice1000, closing.

**Comment by banacorn** [comment]
Wait, what is happening XD?

**Comment by ice1000** [comment]
> Wait, what is happening XD?

I'm trying to implement an external tactic framework (a repl with commands that interact with Agda and somehow modifies an Agda file), and I was wondering how do those editors know where the goals are (so I can fill the goals XD). But it seems that the Emacs mode is using a very primitive way to handle this. Sounds like I'll have to implement something similar myself 😢

**Comment by jespercockx** [comment]
Internally there's the function `getInteractionRange` in `Agda.TypeChecking.Monad.MetaVars` that gives the source location of a hole.

There's lots of known bugs that come from Emacs not having precise enough information about source code locations (#575, #2628, #2672, #2800). If you're working on a better solution, it would be awesome if it could also be used for the Emacs mode itself :)

**Comment by banacorn** [comment]
Currently Agda only gives a list of goal indices on the load file command.
The editor would have to parse the whole file and figure out where the holes are, and rewriting those `?` into `{!!}` if there's any.
At least that's how it's done in Atom, and [it was no fun](https://github.com/banacorn/agda-mode/blob/master/src/Hole.re#L163).

It would be nice if Agda can also give the source locations.

**Comment by nad** [comment]
It is easy to give the locations of goals in a file that has just been loaded (assuming that it has not been changed; the Emacs mode keeps track of whether the file is edited while it is being type-checked). However, it is harder to support commands like give and refine.

**Comment by nad** [comment]
> Current research -- the code goes here:

See also `agda2-goals-action`:

https://github.com/agda/agda/blob/eb493024b79640fa9560c355972547ad59cbdcda/src/data/emacs-mode/agda2-mode.el#L1482-L1550

Ideally I'd like to get rid of this code (this has been discussed before).

**Comment by nad** [comment]
> However, it is harder to support commands like give and refine.

Perhaps it's not so hard to do this after all.

Currently the backend returns a list with all interaction points, in the order in which they appear in the buffer. However, perhaps it suffices to include information about which interaction points have disappeared, and ranges for new interaction points.

Furthermore the Emacs mode does not provide range information when terms are given using the minibuffer. This could be changed.

**Comment by ice1000** [comment]
> Furthermore the Emacs mode does not provide range information when terms are given using the minibuffer. This could be changed.

I'm still wondering why. Not passing range info doesn't seem to break anything.
