### ISSUE TITLE
Field named `_` in `genTel` record

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#4208]
See https://github.com/agda/agda/issues/4159#issuecomment-554934501.  PR #4206 turns projections `f` from `genTel` into new variables `f(genTel)`.  Currently, some fields are given name `_`, which makes it hard to understand error messages, talking then about `_(genTel)`.

Task: give fields of `genTel` record names showing their provenance.  In the conrete case, I would have expected name `i`, giving me `i(genTel)`.

**Comment by andreasabel** [comment]
I don't see much `genTel` anymore when looking at the debug output of #4159.  Has this issue been fixed?

**Comment by jespercockx** [comment]
Let's assume this is fixed, please reopen if necessary.

**Comment by andreasabel** [comment]
I suppose closed issues should remain on the milestone.

**Comment by asr** [comment]
Right. We list the closed issues in the Changelog.
