### ISSUE TITLE
`with` abstraction fails with HIT constructors in the goal

### ISSUE THREAD

**Issue by Rotsor** [agda/agda#4214]
When checking this:

```agda
{-# OPTIONS --cubical #-}
module Test where

open import Agda.Primitive.Cubical
open import Agda.Builtin.Cubical.Path

data ⊤ : Set where
  tt : ⊤

data S : Set where
  base : S
  loop : base ≡ base

postulate
  P' : base ≡ base → Set

foo : P' loop
foo with tt
... | w = ?
```

I get an error:

> Checking Test (/home/rotsor/repos/cubical/Test.agda).
> /home/rotsor/repos/cubical/Test.agda:20,1-12
> The constructor loop does not construct an element of base ≡ base
> when checking that the type ⊤ → P' loop of the generated with
> function is well-formed

It seems that this shouldn't be an error.

**Comment by Saizan** [comment]
fixed by  de820498b36d2054ec22cf54414f1c0284b14c77
