### ISSUE TITLE
Replace Agda.Utils.NonemptyList with Data.List.NonEmpty

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#4235]
Since GHC 8.0, the `base` package includes a module for non-empty lists: https://hackage.haskell.org/package/base-4.12.0.0/docs/Data-List-NonEmpty.html. We could use this to replace our own implementation of non-empty lists at `Agda.Utils.NonemptyList`.

**Comment by andreasabel** [comment]
There are a lot of things that can be non-empty, nonempty lists, nonempty sets, nonempty maps, nonempty intmaps...  Also, there was recently a discussion on the haskell library list advocating the suffix `1` for non-empty collections.  
http://haskell.1045720.n5.nabble.com/Add-NonEmptyMap-and-NonEmptySet-to-containers-td5894493.html
Thus, I suggest these imports
```haskell
import qualified Data.List.NonEmpty as List1
type List1 = List1.NonEmpty
```

**Comment by jespercockx** [comment]
I think using the standard names from the Haskell libraries is probably more important, as this makes it easier for outsiders to understand the Agda codebase.

**Comment by andreasabel** [comment]
In the meantime, I have also added `List2`, but I refuse to call it `NonNonEmpty`. 😆 
I stand to my opinion that `<coll>n` is a good naming scheme for collections with at least `n` elements. 
Also I have added `Agda.Utils.List1` for complementing `Data.List.NonEmpty` with missing functions.
