### ISSUE TITLE
Providing per-commit binary download & installation

### ISSUE THREAD

**Issue by ice1000** [agda/agda#4244]
I wish Agda can be installed easily, say, without requiring a Haskell toolchain. Therefore I made #4243 as an initial attempt.

Agda requires stack/cabal not only for compilation, but also for the `lib/prim` stuffs, say, data directory. I've did a little research:

```
~/git-repos/agda/src/full|master λ> grep -rnE Paths_Agda
Agda/Compiler/MAlonzo/Compiler.hs:62:import Paths_Agda
Agda/Compiler/JS/Compiler.hs:20:import Paths_Agda
Agda/Version.hs:6:import qualified Paths_Agda as PA
Agda/Interaction/Options.hs:75:-- Paths_Agda.hs is in $(BUILD_DIR)/build/autogen/.
Agda/Interaction/Options.hs:76:import Paths_Agda ( getDataFileName )
Agda/Interaction/Highlighting/LaTeX.hs:37:import Paths_Agda
Agda/Interaction/Highlighting/HTML.hs:42:import Paths_Agda
Agda/Packaging/Database.hs:64:import Paths_Agda
```

I found that Agda is using `getDataDir` provided by `Paths_Agda`:

```
~/git-repos/agda/src/full|master λ> grep -irnE getdatadir
Agda/Compiler/MAlonzo/Compiler.hs:787:  dataDir <- lift getDataDir
Agda/Compiler/JS/Compiler.hs:522:  dataDir <- lift getDataDir
Agda/Packaging/Database.hs:65:  ( getDataDir )
Agda/Packaging/Database.hs:81:          <*> getDataDir
```

The implementation of `getDataDir` tries to find `Agda_datadir` environment variable before returning the hard-coded path:

```haskell
getBinDir, getLibDir, getDynLibDir, getDataDir, getLibexecDir, getSysconfDir :: IO FilePath
getBinDir = catchIO (getEnv "Agda_bindir") (\_ -> return bindir)
getLibDir = catchIO (getEnv "Agda_libdir") (\_ -> return libdir)
getDynLibDir = catchIO (getEnv "Agda_dynlibdir") (\_ -> return dynlibdir)
getDataDir = catchIO (getEnv "Agda_datadir") (\_ -> return datadir)
getLibexecDir = catchIO (getEnv "Agda_libexecdir") (\_ -> return libexecdir)
getSysconfDir = catchIO (getEnv "Agda_sysconfdir") (\_ -> return sysconfdir)
```

I wrote a shell & a batch script for setting up the proper environment variables (`Agda_datadir` and `PATH`) to make the downloaded (instead of stack/cabal initialized) Agda stuffs usable, but I'm not sure if it works for everyone.
I've tested the Linux one on an Ubuntu 18.04 machine, which works fine, and I'll test the Windows one soon.

Somehow related to #2617.

I'm opening this issue to collect issues/questions/bugs/problems related to this "new way of installation".

**Comment by ice1000** [comment]
Instructions: https://twitter.com/ice1000kotlin/status/1199930037031620608 (also #4243)

**Comment by UlfNorell** [comment]
Just a note that if you want to compile and run your Agda program, you still need a Haskell tool chain (unless you are using non-GHC compiler backend).

**Comment by ice1000** [comment]
I don't know about the Emacs and texticu parts. I don't yet have a computer with no texticu installed, can anyone help with that?

**Comment by ice1000** [comment]
Ok, I got this on Windows:
![image](https://user-images.githubusercontent.com/16398479/69790573-afc35b80-1190-11ea-8de5-2245f5dfa59a.png)

Does anyone know how can I resolve this? Like, statically linking texticu?

**Comment by ice1000** [comment]
Found SO question: https://stackoverflow.com/q/51860190/7083401

**Comment by ice1000** [comment]
Ok. After some hacks, it worked. The TODO is to do my hacks on the CI.

The thing is you'll need to add some dlls:
![image](https://user-images.githubusercontent.com/16398479/69791996-a982ae80-1193-11ea-8ffa-cd02ac0d7acf.png)

**Comment by ice1000** [comment]
It now works for me on Windows

**Comment by poscat0x04** [comment]
```
❯ agda-mode locate
/home/runner/work/agda/agda/.stack-work/install/x86_64-linux/f1b7935427742adc3bb4c9dfda3c077181f544ed7ac8b1ba1e2e6d18b8cb9825/8.8.1/share/x86_64-linux-ghc-8.8.1/Agda-2.6.1/emacs-mode/agda2.el
```
It seems that the `agda-mode locate` contains a reference to the build directory

**Comment by poscat0x04** [comment]
nvm, the problem got solved after correctly setting the environment variable `Agda_datadir`.

**Comment by ice1000** [comment]
I think there can be a better way to setup the executables, though

**Comment by ice1000** [comment]
I think this is done in general
