### ISSUE TITLE
copatterns not being reduced in interactive mode

### ISSUE THREAD

**Issue by alexarice** [agda/agda#4249]
Consider the following example:

```agda
{-# OPTIONS --without-K --safe --guardedness #-}

module Issue where

record GlobSet : Set₁ where
  coinductive
  field
    cells : Set
    morphisms : cells → cells → GlobSet

open GlobSet

record GlobSetMorphism (G H : GlobSet) : Set where
  coinductive
  field
    func : cells G → cells H
    funcMorphisms : (x y : cells G) → GlobSetMorphism (morphisms G x y) (morphisms H (func x) (func y))

open GlobSetMorphism

gComp : {G H I : GlobSet} → GlobSetMorphism H I → GlobSetMorphism G H → GlobSetMorphism G I
func (gComp ϕ ψ) x = func ϕ (func ψ x)
funcMorphisms (gComp ϕ ψ) x y = gComp (funcMorphisms {!!} {!!} {!!}) (funcMorphisms ψ x y)
```
This has the following constraint given by emacs:
```
[46, 48]
  (morphisms _H_20 (func ?0 ?1) (func ?0 ?2))
    =< (morphisms I (func (gComp ϕ ψ) x) (func (gComp ϕ ψ) y))
    : GlobSet
```
It seems that agda is not able to reduce `func (gComp ϕ ψ) x` to `func ϕ (func ψ x)` even though this is written on the line above. If I try to enter ϕ to the hole it complains that 
```
func ϕ (func ψ y) != func (gComp ϕ ψ) y of type cells I
when checking that the expression funcMorphisms ? ? ? has type
GlobSetMorphism (morphisms H (func ψ x) (func ψ y))
(morphisms I (func (gComp ϕ ψ) x) (func (gComp ϕ ψ) y))
```

Finally if I delete the hole and put ϕ there it happily type checks

**Comment by jespercockx** [comment]
The problem is that Agda doesn't reduce the definition of `gComp` because it doesn't pass the termination checker. If you put a `{-# TERMINATING #-}` pragma on the definition of `gComp`, then giving ϕ works (just observing that the termination checker is indeed the problem).

**Comment by alexarice** [comment]
In this case, is this actually a bug? I assumed `--guardedness` was not sufficient to show termination of this and so have moved to using `--sized-types`. I didn't realise that Agda will not reduce non terminating functions in interactive mode.

I think what confused me more is that interactive mode didn't let me put in the answer, yet if I manually put it in, it was fine. Does giving the hole do something more complicated than filling in the hole and then type checking, and is there a reason for this? I have had similar problems with sized types where I constantly need to delete a hole and manually write what should go there (I think this might be a bug in sized types that I saw mentioned somewhere and may already be fixed though)

**Comment by jespercockx** [comment]
Note that when you replace the hole manually, it is still not really fine since the termination checker complains.

The real bug here is that the code is accepted when you write the code manually: the typechecker should not do the reduction before it is verified to be terminating. But this is just good ol' #42.
