### ISSUE TITLE
Regression related to generalisable variables

### ISSUE THREAD

**Issue by nad** [agda/agda#4253]
The following code is accepted by Agda 2.6.0.1, but rejected by Agda 2.6.1-3ef9513:
```agda
open import Agda.Primitive

variable
  a : Level
  A : Set a
  f : A

postulate
  P : ∀ {a b} {A : Set a} {B : Set b} → (A → B) → Set
  p : P f
```
Error message:
```
Cyclic dependency between generalized variables
when checking that the expression P f has type _14
```
@UlfNorell, I think this is related to your recent changes.

**Comment by UlfNorell** [comment]
Indeed, the new sorting algorithm (#3779) fails to sort `f a A` given constraints `a → A → f`. Here's a test case where all three variables are explicit:
```agda
variable
  a : Level
  A : Set a
  x : A

postulate
  H : ∀ a (A : Set a) (x : A) → Set
  Id : ∀ {a} (A : Set a) → A → A → Set a
  h : (i : H _ _ x) (j : H a _ _) → Id (H _ A _) i j
```
I'll see if I can fix the implementation.
