### ISSUE TITLE
Order of arguments affects lambda pattern matching

### ISSUE THREAD

**Issue by m0davis** [agda/agda#4261]
In the following, Agda accepts one but not the other, yet the only difference is the order of arguments. I believe both should be accepted. Here's the MWE:
```agda
record Sg (A : Set) (B : A → Set) : Set where
  constructor _,_
  field
    fst : A
    snd : B fst

app : {A : Set} {B : A → Set} → ((x' : A) → B x') → (x : A) → B x
app f x = f x

ppa : {A : Set} {B : A → Set} → (x : A) → ((x' : A) → B x') → B x
ppa x f = f x

postulate
  Bool : Set
  bar : ((Sg Bool (λ _ → Bool)) → Bool) → Bool

foo : Bool
foo = app bar (λ (_ , _) → {!!}) -- accepted
foo = ppa (λ (_ , _) → {!!}) bar --rejected
```
The error is:
```
Cannot split on argument of non-datatype _23
when checking that the pattern _ , _ has type _23
```
I'm using the latest from `master`, compiled via `stack` with `GHC 8.6.5`.

**Comment by UlfNorell** [comment]
Surprisingly,
```agda
foo = ppa (λ x → let _ , _ = x in {!!}) bar
```
produces yellow (but no useful constraints) rather than the above error.

Related #4167

**Comment by jespercockx** [comment]
@andreasabel what's a maculata?

**Comment by andreasabel** [comment]
A feature that is buggy at its conception. :D https://en.wikipedia.org/wiki/Immaculate_Conception

**Comment by jespercockx** [comment]
The problem seems to be that Agda *tries* to postpone the typechecking of the lambda by blocking it on a meta, but the meta it tries to block on is not present in the meta store so Agda falls back to a hard failure instead. I'm not sure yet *why* the meta is not in the meta store, though.
