### ISSUE TITLE
Makefile loses exit codes

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#4282]
cc @L-TChen @jespercockx 

It looks like the standard library tests have been failing since 803aaae, but we haven't noticed since the Makefile doesn't fail properly on errors. Likely culprit: 621ef12e2.

**Comment by UlfNorell** [comment]
Fixed by changing `;` to `&&` in the Travis fold logic script. This means it won't print an "end fold" marker on failures, but at least it will fail. @L-TChen I'm not sure if this messes anything up on Travis, maybe you can devise a better fix?

**Comment by L-TChen** [comment]
Thanks for the fix. I think there is no need to print a marker to close the fold on failures. Since this exactly the point you want to figure out where to find the failure. 

Making these changes on Travis is really subtle ...
