### ISSUE TITLE
Agda loops during scope check

### ISSUE THREAD

**Issue by sattlerc** [agda/agda#4288]
On master (4fa3134).

```agda
a = b module M where private
```
Agda loops and allocates progressively more space. The `private` keyword is only to make the module non-empty. Any other block or declaration triggers the bug as well.

**Comment by asr** [comment]
This is a regression. Using Agda 2.6.0.1 the error is:

```
/some-path/Issue4288.agda:4,22-29
Empty private block.
when scope checking the declaration
  a = b
    module M where
      private
/some-path/Issue4288.agda:4,5-6
Not in scope:
  b
  at /some-path/Issue4288.agda:4,5-6

**Comment by jespercockx** [comment]
Bisection points towards 3972a9d2bd89d0a8ab15f803f3868666f0814c56 (yay, my first successful run of `agda-bisect`!)
