### ISSUE TITLE
datatype scope and import guidelines

### ISSUE THREAD

**Issue by pnlph** [agda/agda#4289]
When trying to solve goals i find a problem having to trace back imported datatypes.

At first i thought that it would make sense to include where the imported datatypes come from when showing the goal. Eg. ( i don't even know where is  ≡ defined in stdlib)
```
?0 : pow-sqr b (suc e) ≡ (b ^ suc e)
_≡_ imported from...
_^_ imported from Data.Nat.Base#L106
```
Then i though that the agda user who made the program (a problem with holes to be filled by a reader) could have used
`open import Data.Nat.Base using (_^_)`

instead of
`open import Data.Nat`

I understand that with the latter instruction, everything under Data.Nat is being brought into the agda scope, but only some datatypes from there are actually relevant and included in the 'human scope'.

Is this an abuse of the import functionality? Can it be solved with guidelines or it would be better to help the user with additional info when showing the goal?

Maybe when loading the file C-c C-l it would be good to inform about the number of datatypes brought to the agda scope which are not being used.

I don't know if some of you find it also annoying, i know that this happens also in other languages but precisely in Agda this style of importing is making the overall program weaker, as we have assumptions in scope that we do not actually need, is this interpretation right?

**Comment by gallais** [comment]
In the stdlib we try to explicitly list imports if we are not using much.
I think this is indeed good practice.

**Comment by nad** [comment]
> When trying to solve goals i find a problem having to trace back imported datatypes.

I'm not sure what you mean. You can typically use the "go-to-definition" feature of the Emacs mode to find a symbol's definition. (This does not work perfectly when `open` `public` is used.)

**Comment by UlfNorell** [comment]
I think the "Why in scope" (<kbd>C-c C-w</kbd>) command does what you want.
With `open import Data.Nat`:
```
_^_ is in scope as
  * a defined name Data.Nat.Base._^_ brought into scope by
    - the opening of Data.Nat at Issue4289.agda:4,13-21
    - the opening of Data.Nat.Base at stdlib/src/Data/Nat.agda:17,13-26
    - its definition at stdlib/src/Data/Nat/Base.agda:106,1-4
```
With `open import Data.Nat.Base using (_^_)`:
```
_^_ is in scope as
  * a defined name Data.Nat.Base._^_ brought into scope by
    - the opening of Data.Nat.Base at Issue4289.agda:4,13-26
    - its definition at stdlib/src/Data/Nat/Base.agda:106,1-4
```

**Comment by pnlph** [comment]
Yes, the C-c C-w why in scope command in context of a goal is exactly what i was looking for. I sent a #4296 user manual update.
