### ISSUE TITLE
Missing documentation: --confluence-check option

### ISSUE THREAD

**Issue by asr** [agda/agda#4298]
The option `--confluence-check option` will be added in 2.6.1 but it is not documented in the user manual.

**Comment by jespercockx** [comment]
Well, there is not even any documentation for `--rewriting`... I'll see if I can adapt the content of my recent blog posts on rewrite rules to the user manual.

**Comment by jespercockx** [comment]
It's annoying that the user manual uses `rst` rather than something more sensible like (pandoc-flavored) markdown.

**Comment by asr** [comment]
> Well, there is not even any documentation for `--rewriting`...

Right.

> I'll see if I can adapt the content of my recent blog posts on rewrite rules to the user manual.

Great! Please do it!

**Comment by L-TChen** [comment]
> It's annoying that the user manual uses `rst` rather than something more sensible like (pandoc-flavored) markdown.

Sphinx actually supports markdown! Not sure what else to do if you'd like to use this feature, though. 

http://www.sphinx-doc.org/en/master/usage/markdown.html
