### ISSUE TITLE
Fail in the GitHub `cabal build` workflow

### ISSUE THREAD

**Issue by asr** [agda/agda#4305]
The `cabal build` workflow is failing because it is necessary to checkout the std-lib submodule.

**Comment by L-TChen** [comment]
This should be fixed now by 00180cdca1a189ffa68810365ed2f60431bc352b. I will close this once CI is passed.

**Comment by L-TChen** [comment]
CI passed. Closed.

**Comment by asr** [comment]
Thanks!
