### ISSUE TITLE
Implicit/instance variables named _ are not shown in contexts

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#4307]
I’m not sure if it’s intended behavior, but implicit/instance variables named _ are not shown in contexts. For instance in the code below, nothing is displayed when asking for the context of the goal.

This is somewhat annoying for instance arguments, because even though one often does not need to name them, it’s still useful to know that they are available in the context.
```agda
postulate
  A : Set

f : {_ : A} → A
f = ?
```

**Comment by jespercockx** [comment]
Normally naming an argument `_` means you don't want to use it, so it would be a bit annoying if these arguments still popped up in the context. I agree that instance arguments are the exception, so perhaps Agda should only show the instance arguments that are named `_`.

**Comment by gallais** [comment]
Related to #4337 
If an argument does not have a (visible) name, we cannot easily bring it into
scope. We could maybe add a different goal + context command showing *everything*?
