### ISSUE TITLE
Keep track of blocking metavariables in PatternErr

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#4309]
Internally, Agda uses a special error `PatternErr` to signal that a computation is blocked on an unsolved metavariable and should be retried later. (This error used to be only for pattern violations, but now it is used in many other places.) However, it does not contain any information about *which* metavariable is blocking the computation, which means the code catching the error does not know when to retry the computation.

I propose to add this information to `PatternErr` and rename it to `TCBlocked` or something similar to better reflect its current usage. I made an attempt at doing this refactor some time ago (https://github.com/jespercockx/agda/commit/ca77e0124aa5db61835011b56f8ac2fbf45f1deb) but I never finished it.

**Comment by plt-amy** [comment]
Is this solved by 552987aa0119f2bca5eaf4dca7934e37209112f9?

**Comment by jespercockx** [comment]
Yes indeed!
