### ISSUE TITLE
Constructor-headed function makes type-checker diverge

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#431]
```agda
-- The following code makes the type-checker diverge. The bug was
-- reported by Brandon Moore:
--
-- "I think the problem is that the body has type ℕ × f n,
-- and unifying it with the expected type f n invokes the
-- constructor-headed function specialization to resolve
-- n to suc n', and the process repeats."

module Bug where

data ℕ : Set where
  zero : ℕ
  suc  : ℕ → ℕ

data _×_ (A B : Set) : Set where
  _,_ : A → B → A × B

F : ℕ → Set
F zero    = ℕ
F (suc n) = ℕ × F n

f : (n : ℕ) → F n
f zero    = zero
f (suc n) = n , f n

mutual

  n : ℕ
  n = _

  test : F n
  test = f (suc n)

```

Original issue reported on code.google.com by `nils.anders.danielsson` on 8 Aug 2011 at 11:23

**Comment by asr** [comment]
@UlfNorell, it is great you fixed this issue.

Please document the new option `--inversion-max-depth` in the CHANGELOG and [here](http://agda.readthedocs.io/en/latest/tools/command-line-options.html#command-line-and-pragma-options) in the user manual.

I reopened the issue for remembering the missing documentation.

**Comment by UlfNorell** [comment]
Also user manual.. coming shortly.

**Comment by andreasabel** [comment]
Hooray for fixing this ancient issue!
