### ISSUE TITLE
Refinement suggests code that doesn't type-check

### ISSUE THREAD

**Issue by conal** [agda/agda#4317]
I'm seeing [an example](https://github.com/conal/calculating-compilers-agda/commit/ea48fee450366766052f49ca7bd8b05e02d1b51d#commitcomment-36528875) in which `agda2-refine` generates code (`refl`) that then gets rejected.

**Comment by sattlerc** [comment]
I wasn't able to reproduce this. Please provide the following:
- the version of Agda you are using,
- a file with a hole for which the problem occurs.

**Comment by guillaumebrunerie** [comment]
This is most likely #1654 (more general issue: #118).
