### ISSUE TITLE
Interaction load time higher than expected with qualified import

### ISSUE THREAD

**Issue by msuperdock** [agda/agda#4318]
## Issue

I've been trying to reduce the amount of time it takes for agda's interaction mode to load in a certain project (within vim, though I believe this issue is not vim-specific). I've noticed that if module B imports module A, then module B takes at least as long to load as module A, regardless of how module A is imported. This means that if module A takes 5s to load, then any module depending on module A, even indirectly, takes at least 5s to load.

The example below shows the issue more specifically:

- The module B0 consisting of just the single import statement, `import A using ()` takes about a second longer to load than module A, despite not actually importing any definitions.
- The module C0 consisting of just the single import statement, `open import A using ()` takes about two seconds longer to load than module A, which I take to mean that about a second is spent moving the unusable definitions of A into the current namespace.

I would expect that there would be a way to import module A in a qualified way, so that we bring into context just the needed definitions, without incurring the time cost (in interaction mode) of loading all of module A, but it doesn't seem that the `using` modifier accomplishes this.

## Example

File `A.agda`:
```
module A where

data D1 : Set where
data D2 : Set where
...
data D5000 : Set where
```

File `B0.agda`:

```
module B0 where

import A using ()
```

File `B1.agda`:

```
module B1 where

import A using (D1)

Test : Set
Test = A.D1
```

File `B.agda`:

```
module B where

import A
```

File `C0.agda`:

```
module C0 where

open import A using ()

```

File `C1.agda`:

```
module C1 where

open import A using (D1)

Test : Set
Test = D1
```

Load times:

- Loading agda from within `A.agda`: 4.4s, 4.6s, 4.5s
- Loading agda from within `B0.agda`: 5.3s, 5.3s, 5.4s
- Loading agda from within `B1.agda`: 5.4s, 5.3s, 5.2s
- Loading agda from within `B.agda`: 6.2s, 6.2s, 6.1s
- Loading agda from within `C0.agda`: 6.3s, 6.3s, 6.1s
- Loading agda from within `C1.agda`: 6.2s, 6.3s, 6.1s

These were calculated on my wristwatch, using an old laptop (this is not essential; I get similar behavior on a faster desktop), using the following process:

- Open the file & load agda, to make sure the .agdai file is up to date.
- Close the file, reopen the file & load agda, timing how long it takes for the cursor to reappear. (We close & reopen the file, since the first load tends to be about twice as long as subsequent loads.)

For reference, it takes 0.8s on my laptop to load agda in an empty module, using this process.

If you'd like to reproduce these examples, you might start with the following bash command:

```
$ for i in {1..5000}; do echo data D$i : Set where; done > A.agda
```

## Notes

By comparing the load times of B0 and B, we see that qualifying imports reduces load time. However, I would expect that the load times of B0, B1, C0, and C1 would all be much less than the load time of A.

## Other details

I'm using agda version 2.6.0.1 from stackage, on NixOS. I'm using the agda mode for vim, though I'm not using the syntax highlighting provided by the agda compiler.

**Comment by UlfNorell** [comment]
What takes time is reading and decoding the interface file. Conceivably, we could change the interface format to make it possible to only decode the parts that you need, but that would be a challenge and the problem is that you don't know which parts you actually need. Consider
```agda
module A where
  foo = ...
  bar = foo
```

```
module B where
  import A using (bar)
```
Even though we are only importing `bar` we still need the definition of `foo` since we might need to evaluate `bar` at some point.

The way this problem is solved in the emacs mode is that we cache the decoded interfaces, so when you reload a file it doesn't have to do any work for imported modules.
