### ISSUE TITLE
Remove  the `cabal.project` file

### ISSUE THREAD

**Issue by asr** [agda/agda#4321]
I'm getting the following error using `cabal-install 3.0.0.0`:

```
$ cd src/agda-bisect/
$ cabal install
cabal: Unknown target '.'.
There is no component '.'.
The project has no package directory '.'.
```

I can fix the error by adding `agda-bisect` to the file `cabal.project`. However,  in addition to `agda` and `agda-mode`, we have different programs (i.e. `agda-bisect`, `closed-issues-for-milestone`, `fix-agda-whitespace`, `hTags` and `size-solver`) which are independent of each other. To use a global `cabal.project` file in this case is too complicate and it is unnecessary.

I'll remove the `cabal.project` file.

**Comment by andreasabel** [comment]
I am undoing this change (not for the first time).
- #6993 

I came to realize that it is more uniform if each independent project also has its `cabal.project` file, even if it only contains `packages: .`.  
This way, projects can be in subdirectories of directories that have a `cabal.project` file.
