### ISSUE TITLE
Imports are not confluence checked

### ISSUE THREAD

**Issue by sattlerc** [agda/agda#4333]
It is possible to break confluence of rewriting (with `--confluence-check`) by declaring competing rewrite rules in independent modules, later imported in the same module.

An example is as follows.
- M.agda:
```agda
{-# OPTIONS --rewriting --confluence-check #-}
module M where

postulate
  A : Set
  _==_ : A → A → Set
{-# BUILTIN REWRITE _==_ #-}
  
postulate
  a a₀' a₁' : A
  p₀ : a == a₀'
  p₁ : a == a₁'
  B : A → Set
  b : B a
```
- N0.agda:
```agda
{-# OPTIONS --rewriting --confluence-check #-}
module N0 where

open import M
{-# REWRITE p₀ #-}

b₀' : B a₀'
b₀' = b
```
- N1.agda:
```agda
{-# OPTIONS --rewriting --confluence-check #-}
module N1 where

open import M
{-# REWRITE p₁ #-}

b₁' : B a₁'
b₁' = b
```
- N.agda:
```agda
{-# OPTIONS --rewriting --confluence-check #-}
module N where

open import M
open import N0
open import N1

postulate
  of-type : (X : Set) (x : X) → Set

-- Subject reduction violated for b₁' = b.
_ = of-type (B a₁') b₁'
_ = of-type (B a₀') b
```

**Comment by jespercockx** [comment]
I've pushed a fix but I'm unable to create a good test case: instead of giving the confluence error that I get when I do the test manually, when running the test suite Agda complains that the LHS of `p₁` reduces to `a₀'` when checking `N1`. So somehow Agda checks `N1` with the signature from `N0` already added, but **only** when running the test suite with `make test`. Anyone has an idea how to properly create a test case?

**Comment by sattlerc** [comment]
This is analogous to #4267 and is another issue caused by #4272.

Even before applying your fix (or without confluence check), we get two different outcomes:
* Removing all interface files and running agda N.agda:
```
Checking N (N.agda).
 Checking M (M.agda).
 Checking N0 (N0.agda).
 Checking N1 (N1.agda).
N1.agda:5,1-19
p₁  is not a legal rewrite rule, since the left-hand side 
a  reduces to  a₀'
when checking the pragma REWRITE p₁
```
* Removing all interface files and running agda N1.agga followed by agda N.agda:
```
$ agda N1.agda 
Checking N1 (N1.agda).
 Checking M (M.agda).
$ agda N.agda 
Checking N (N.agda).
 Checking N0 (N0.agda).
```
This is a separate bug (even without confluence checking). Should we have a new issue for it or does it suffice to record it here?

**Comment by sattlerc** [comment]
To close this particular issue, I could write an interaction test case that forces the desired typechecking order.
