### ISSUE TITLE
internal error ... Rules/LHS.hs:767 in Agda 2.6.0.1

### ISSUE THREAD

**Issue by mechvel** [agda/agda#4334]
This is on the type checker of Agda 2.6.0.1, ghc-8.6.3, lib-1.2.                  
    
Please, download this small example from 
http://www.botik.ru/pub/local/Mechveliani/agdaNotes/bug-dec26-2019.zip
    
and see Readme.lagda.
                                                                          
  > agda $agdaLibOpt Structures.agda                                              
                                                                                  
reports                                                                           
"An internal error has occurred. Please report this as a bug.                     
 Location of the error: src/full/Agda/TypeChecking/Rules/LHS.hs:767               
"

**Comment by sattlerc** [comment]
This works fine on the current development version. So it has likely been fixed already. This might be another instance of #3652.
