### ISSUE TITLE
naming: go to definition / scope info

### ISSUE THREAD

**Issue by pnlph** [agda/agda#4342]
When testing the command `go to definition` the results refer to `Scope info`. Are these two concepts the same? If so, it may be good to unify the naming.

**Comment by nad** [comment]
This is not an Emacs mode command, right? Please be more specific.

**Comment by pnlph** [comment]
I am testing with [agda-mode on Atom](https://atom.io/packages/agda-mode), where the keymap is `C-alt-\` but i think it is accessible also on Emacs with keymap `M-.`

Reference: other Emacs commands on readthedocs:
https://agda.readthedocs.io/en/latest/tools/emacs-mode.html#other-commands

**Comment by nad** [comment]
I don't think the Emacs mode prints "Scope info", so perhaps this is a problem with the Atom mode.

**Comment by pnlph** [comment]
Thanks! If this is the case, i will ping @banacorn maybe i'm missing something here.

**Comment by banacorn** [comment]
Yes, I think `go to definition` is Atom mode only.
The two things are the same, `go to definition` is only a handy shorthand for "scope info" (in that you don't have to type the thing)

**Comment by pnlph** [comment]
OK, thanks for the explanation. This can continue in banacorn/agda-mode#119
