### ISSUE TITLE
Seemingly needless repetition of highlighting of warnings

### ISSUE THREAD

**Issue by nad** [agda/agda#4348]
Consider the following code:
```agda
{-# OPTIONS --warning ShadowingInTelescope #-}

Non-terminating : Set₁
Non-terminating = Non-terminating

postulate
  Shadowing : (A A : Set) → Set
```
Let us see what kind of highlighting is produced for this code (using `echo 'IOTCM "Test.Agda" NonInteractive Direct (Cmd_load "Test.agda" [])' | agda --interaction`):
```
(agda2-highlight-clear)
```
Clear everything.
```
(agda2-highlight-add-annotations 'nil '(1 4 (symbol) t) '(5 12 (keyword) t) '(13 22 (pragma) t) '(23 43 (pragma) t) '(44 47 (symbol) t) '(65 66 (symbol) t) '(67 70 (primitivetype) t) '(87 88 (symbol) t) '(106 115 (keyword) t) '(128 129 (symbol) t) '(130 131 (symbol) t) '(135 136 (symbol) t) '(137 140 (primitivetype) t) '(140 141 (symbol) t) '(142 143 (symbol) t) '(144 147 (primitivetype) t))
```
Token-based highlighting.
```
(agda2-highlight-add-annotations 'nil '(49 64 (function) nil nil ("/tmp/Test.agda" . 49)) '(71 86 (function) nil nil ("/tmp/Test.agda" . 49)) '(89 104 (function) nil nil ("/tmp/Test.agda" . 49)) '(118 127 (postulate) nil nil ("/tmp/Test.agda" . 118)) '(131 132 (bound) nil nil ("/tmp/Test.agda" . 131)) '(133 134 (bound) nil nil ("/tmp/Test.agda" . 133)))
```
Highllighting of the three occurrences of `Non-terminating`, the single occurrence of `Shadowing`, and the two occurrences of `A`. (I think this is the highlighting that is done after scope-checking.)
```
(agda2-highlight-add-annotations 'nil '(49 64 (function) nil nil ("/tmp/Test.agda" . 49)) '(65 66 (symbol) t) '(67 71 (primitivetype) t) '(132 133 (deadcode)))
(agda2-highlight-add-annotations 'nil '(49 64 (function) nil nil ("/tmp/Test.agda" . 49)) '(72 87 (function) nil nil ("/tmp/Test.agda" . 49)) '(88 89 (symbol) t) '(90 105 (function) nil nil ("/tmp/Test.agda" . 49)) '(132 133 (deadcode)))
(agda2-highlight-add-annotations 'nil '(49 64 (terminationproblem)) '(90 105 (terminationproblem)) '(119 128 (postulate) nil nil ("/tmp/Test.agda" . 119)) '(129 130 (symbol) t) '(131 132 (symbol) t) '(132 133 (deadcode bound) nil nil ("/tmp/Test.agda" . 132)) '(134 135 (bound) nil nil ("/tmp/Test.agda" . 134)) '(136 137 (symbol) t) '(138 141 (primitivetype) t) '(141 142 (symbol) t) '(143 144 (symbol) t) '(145 148 (primitivetype) t))
(agda2-highlight-add-annotations 'nil '(49 64 (terminationproblem)) '(90 105 (terminationproblem)) '(132 133 (deadcode)))
```
Presumably highlighting done during the type-checking of the code. Note that each of these four lines include `'(132 133 (deadcode))` or `'(132 133 (deadcode bound) nil nil ("/tmp/Test.agda" . 132))`.
```
(agda2-highlight-add-annotations 'nil '(1 4 (symbol) t) '(5 12 (keyword) t) '(13 22 (pragma) t) '(23 43 (pragma) t) '(44 47 (symbol) t) '(107 116 (keyword) t))
```
A final round of token-based highlighting.

Why is the `deadcode` highlighting repeated so many times? Note that the highlighting of the termination problem is also repeated.

**Comment by nad** [comment]
I suspect that the following code generates highlighting for all warnings encountered so far in the current file:

https://github.com/agda/agda/blob/4e6ef5bfc9a2a516c103384fbc348d8eb8780137/src/full/Agda/Interaction/Highlighting/Generate.hs#L195-L196

However, this code is placed inside `generateAndPrintSyntaxInfo`, which should generate highlighting for a single declaration:

https://github.com/agda/agda/blob/4e6ef5bfc9a2a516c103384fbc348d8eb8780137/src/full/Agda/Interaction/Highlighting/Generate.hs#L147-L163

**Comment by andreasabel** [comment]
My proposed solution in PR #4454 highlights warnings as they are created rather than postponing it to the next successfully checked declaration.

**Comment by asr** [comment]
I fixed a white-space issue in the title.

**Comment by nad** [comment]
> I fixed a white-space issue in the title.

Out of curiosity, what was the problem?

**Comment by asr** [comment]
The title with the trailing white-space was listed by the `closed-issues-for-milestone` tool and added to the CHANGELOG which is tested by the `fix-agda-whitespace` tool.
