### ISSUE TITLE
Scoping bug with let open in telescope

### ISSUE THREAD

**Issue by sattlerc** [agda/agda#4350]
On recent master (16aa61a).

```agda
private
  module M where

  module N (let open M) where
    A = Set

  -- Not in scope: N.A
  B = N.A

-- IS: fails
-- SHOULD: succeed
```
Output:
```
Bug.agda:8,7-10
Not in scope:
  N.A
  at Bug.agda:8,7-10
when scope checking N.A
```
Note that the file is accepted if `(let open M)` is removed or if we are not inside a private block.

**Comment by nad** [comment]
This bug goes back to at least Agda 2.4.0.2. Agda 2.3.2.2 does not parse the code above (even if a module header is added).

**Comment by sattlerc** [comment]
Note that `module M' = M` instead of `open M` will trigger the bug as well.

**Comment by UlfNorell** [comment]
This seems like the likely culprit:
https://github.com/agda/agda/blob/f9a922c5fdacc201ef186402f7d6b25dbc46b63b/src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs#L1119-L1126
Introduced by @andreasabel in f739b3d when fixing #1299.

**Comment by andreasabel** [comment]
> Introduced by @andreasabel in [f739b3d](https://github.com/agda/agda/commit/f739b3d7697a72c9ba2a30a80fe080d2a8f0909e) when fixing #1299.

The commit you point out only extends the solution for `let open` to module macros, so why should it be the culprit?

Probably this never worked.  It is a rare combination of `open`-in-telescope in a `private` block.

Wrapping an anonymous module (written out) does not produce the bug; this works:
```agda
private
  module M where

  module _ where
    open M
    module N' where
      A' = Set

  B' = N'.A'
```
So when inserting the anonymous module, its contents should not be declared `private`, but the nicifier already propagated this access mode from the enclosing `private` block.

A solution would be to undo the work of the nicifier and relabel the module as public.

P.S.: A minimal case seems to be:
```agda
module _ where

module M where
private
  module N (let open M) where
open N  -- No module N in scope
```

**Comment by andreasabel** [comment]
Summary:
```agda
private
  module M ...
```
is equivalent to
```agda
private
  module _ where
    module M ...
```
but was handled like
```agda
private
  module _ where
    private
      module M ...
```
Fix forthcoming.
