### ISSUE TITLE
Regression: Different splitting order leads to unsolved constraints

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#4353]
@martinescardo reports in #3960:

> More of my existing code now gives yellow with or without this fix, in the development version of 2.6.1. E.g. https://www.cs.bham.ac.uk/~mhe/dialogue/dialogue-lambda.html#15434 needs to add the implicit parameters in the use of `Rs` in the main lemma as follows:
> 
> ```
> Rs : ∀{n : ℕ} {Γ : Cxt n} → (Baire → 【 Γ 】) → B【 Γ 】 → Set
> Rs {n} {Γ} xs ys = ∀(i : Fin n) → R {Γ [ i ]} (λ α → xs α i) (ys i)
> 
> main-lemma : ∀{n : ℕ} {Γ : Cxt n} {σ : type} (t : T' Γ σ) (xs : Baire → 【 Γ 】)(ys : B【 Γ 】)
>           → Rs {n} {Γ} xs ys → R (λ α → ⟦ t ⟧' α (xs α)) (B⟦ t ⟧ ys)
> ```

> 
> Agda version 2.6.0.1.20191219 gives
> 
> ```
> _Γ_982 : Cxt n  [ at /home/mhe/feathers/public_html/dialogue/dialogue-lambda.lagda:546,13-15 ]
> _Γ_1255 : Cxt n  [ at /home/mhe/feathers/public_html/dialogue/dialogue-lambda.lagda:590,49-50 ]
> _1256 : B【 _Γ_1255 】  [ at /home/mhe/feathers/public_html/dialogue/dialogue-lambda.lagda:590,61-63 ]
> _1257 : 【 _Γ_1255 】  [ at /home/mhe/feathers/public_html/dialogue/dialogue-lambda.lagda:590,44-48 ]
> 
> ———— Errors ————————————————————————————————————————————————
> Failed to solve the following constraints:
>   R (λ α → xs α i) (ys i) =< R (λ α → xs α i) (ys i)
>   (_1256 (σ = σ) (τ = τ) (t = t) (xs = xs) (ys = ys) (x = x) (y = y)
>    (i = i)
>    ‚‚ y)
>   i = (ys ‚‚ y) i
>     : B〖
>       (_Γ_1255 (σ = σ) (τ = τ) (t = t) (xs = xs) (ys = ys) (x = x)
>        (y = y) (i = i)
>        ’ σ)
>       [ i ]
>       〗
>   (_1257 (σ = σ) (τ = τ) (t = t) (xs = xs) (ys = ys) (x = x) (y = y)
>    (i = i) (α = α)
>    ‚ x α)
>   i = (xs α ‚ x α) i
>     : 〖
>       (_Γ_1255 (σ = σ) (τ = τ) (t = t) (xs = xs) (ys = ys) (x = x)
>        (y = y) (i = i)
>        ’ σ)
>       [ i ]
>       〗
>   _Γ_982 (t = t) (xs = (λ α → xs α ‚ x α)) (ys = (ys ‚‚ y)) [ i ]
>     = (_Γ_1255 (σ = σ) (τ = τ) (t = t) (xs = xs) (ys = ys) (x = x)
>        (y = y) (i = i)
>        ’ σ)
>       [ i ]
>     : type
>   R (λ α → xs α i) (ys i)
>     =< R
>        (λ α →
>           (_1257 (σ = σ) (τ = τ) (t = t) (xs = xs) (ys = ys) (x = x) (y = y)
>            (i = (succ i)) (α = α)
>            ‚ x α)
>           (succ i))
>        ((_1256 (σ = σ) (τ = τ) (t = t) (xs = xs) (ys = ys) (x = x) (y = y)
>          (i = (succ i))
>          ‚‚ y)
>         (succ i))
>   _Γ_1255 (σ = σ) (τ = τ) (t = t) (xs = xs) (ys = ys) (x = x) (y = y)
>   (i = i)
>   [ i₁ ]
>     = Γ [ i₁ ]
>     : type
>   _Γ_1255 [ i₁ ] = Γ [ i₁ ] : type
>   ys i = ys i : B〖 _Γ_982 (t = (ν i)) (xs = xs) (ys = ys) [ i ] 〗
>   xs α i = xs α i : 〖 _Γ_982 (t = (ν i)) (xs = xs) (ys = ys) [ i ] 〗
>   _Γ_982 (t = (ν i)) (xs = xs) (ys = ys) [ i ] = Γ [ i ] : type
>   _Γ_982 [ i ] = Γ [ i ] : type
> ```

**Comment by jespercockx** [comment]
Here is a cut-down example:
```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Equality

data _^_ (X : Set) : Nat → Set where
  〈〉  : X ^ zero
  _’_ : {n : Nat} → X ^ n → X → X ^ (suc n)

data Fin : Nat → Set where
  zero : {n : Nat} → Fin (suc n)
  suc  : {n : Nat} → Fin n → Fin (suc n)

_[_] : {X : Set} {n : Nat} → X ^ n → Fin n → X
(xs ’ x) [ zero ] = x
(xs ’ x) [ suc i ] = xs [ i ]

postulate
  Baire : Set
  B : Set → Set

data type : Set where
 ι    : type
 _⇒_ : type → type → type

Cxt : Nat → Set
Cxt n = type ^ n

〖_〗 : type → Set
〖 ι 〗 = Nat
〖 σ ⇒ τ 〗 = 〖 σ 〗 → 〖 τ 〗

【_】 : {n : Nat} (Γ : Cxt n) → Set
【 Γ 】 = (i : Fin _) → 〖 Γ [ i ] 〗

postulate
  T' : {n : Nat} (Γ : Cxt n) (σ : type) → Set
  decode : ∀{X : Set} → Baire → B X → X

B〖_〗 : type → Set
B〖 ι 〗 = B(〖 ι 〗)
B〖 σ ⇒ τ 〗 = B〖 σ 〗 → B〖 τ 〗

B【_】 : {n : Nat} (Γ : Cxt n) → Set
B【 Γ 】 = (i : Fin _) → B〖 Γ [ i ] 〗

postulate
  B⟦_⟧ : {n : Nat} {Γ : Cxt n} {σ : type} → T' Γ σ → B【 Γ 】 → B〖 σ 〗

R : ∀{σ : type} → (Baire → 〖 σ 〗) → B〖 σ 〗 → Set
R {ι} n n' =  ∀(α : Baire) → n α ≡ decode α n'
R {σ ⇒ τ} f f' = ∀(x : Baire → 〖 σ 〗) (x' : B〖 σ 〗) → R {σ} x x' → R {τ} (λ α → f α (x α)) (f' x')

Rs : ∀{n : Nat} {Γ : Cxt n} → (Baire → 【 Γ 】) → B【 Γ 】 → Set
Rs {n} {Γ} xs ys = ∀(i : Fin n) → R {Γ [ i ]} (λ α → xs α i) (ys i)

X : ∀{n : Nat} {Γ : Cxt n} {σ : type} (t : T' Γ σ) (xs : Baire → 【 Γ 】)(ys : B【 Γ 】) → Set _
X t xs ys = Rs xs ys
```
The crucial unsolved constraint (the only one left over in this example) is:
```
  _[_] {type} {n} _Γ_97 i = _[_] {type} {n} Γ i : type
```
Looking at the debug output, it seems the problem is that `_[_]` uses a different case splitting order from before. We can also verify this by changing the definition of `_[_]` to force it to split on the natural number first:
```agda

case_of_ : {A B : Set} → A → (A → B) → B
case x of f = f x

_[_] : {X : Set} {n : Nat} → X ^ n → Fin n → X
xsx [ zero ] = case xsx of λ where
  (xs ’ x) → x
xsx [ suc i ] = case xsx of λ where
  (xs ’ x) → xs [ i ]
```
This change makes the example typecheck.

@UlfNorell could the different splitting order be a consequence of the new forcing analysis? It seems that the `Nat` argument to `_^_` is a forced index, so maybe the new algorithm postpones splitting on it until later.

**Comment by UlfNorell** [comment]
That seems likely.

**Comment by jespercockx** [comment]
In that case I don't think there's an easy fix for this problem, as the current splitting tree seems to be the correct one.

To make this example actually work with the current splitting tree, Agda would have to be able to detect when reduction of a term is blocked on a metavariable, but from the other arguments of the function we can deduce that any possible solution for this metavariable will anyway result in a neutral term, so it would be safe to consider the term to be neutral. There's several situations where this can happen:

- There is another argument of the function that each branch of the case tree splits on, which is neutral (any solution of the meta would lead to matching getting stuck later on anyway)
- The type of the metavariable is neutral (neutral types only have neutral terms as their elements)
- The type of the metavariable is an indexed datatype, and the index is a neutral term that does not match with the index of any of the constructors (such a type can also have neutral terms as its elements, as none of the constructors can be used)

It should be possible to extend Agda with capabilities to detect such cases and mark the term as neutral instead of blocked, which would solve the issue here. However, I'm not sure if it is realistic to try to do this before the release. So my proposal is to keep the current behavior and mention in the release notes that the new forcing analysis may lead to a different case tree and hence some arguments going unsolved.

**Comment by andreasabel** [comment]
Please submit an enhancement request if you are badly bitten by this change.
