### ISSUE TITLE
Get rid of SubstExpr?

### ISSUE THREAD

**Issue by nad** [agda/agda#4354]
The following comments suggest that `substExpr` might be buggy:

https://github.com/agda/agda/blob/baa36d2e29c177183bd730d52616ea8db621871b/src/full/Agda/Syntax/Abstract.hs#L1149-L1153

I noticed that `substExpr` is not used a lot in the code base. Could we get rid of it?

**Comment by andreasabel** [comment]
`substExpr` and `substPattern` are used exactly for pattern synonyms. 

> Could we get rid of it?

Well, yes, if we change the implementation of pattern synonyms.
