### ISSUE TITLE
Incorrect ranges for record pattern lambda patterns

### ISSUE THREAD

**Issue by nad** [agda/agda#4356]
Consider the following code:
```agda
open import Agda.Builtin.Sigma

F : Σ Set (λ _ → Set) → Set
F = λ (A , B) → B
```
If I invoke "go-to-definition" on the occurrences of `,` and `B` in the pattern I end up at the `A`. However, for the `B` in the right-hand side I end up at the `B` in the pattern.

The following code seems to be handled correctly:
```agda
F : Σ Set (λ _ → Set) → Set
F P = let (A , B) = P in B
```
This suggests that the problem discussed above is related to the new record pattern lambdas.

**Comment by gallais** [comment]
I don't understand why the pattern is not picked up by universeBi.


Related (I always struggle to find this discussion when I am looking for it):
https://github.com/agda/agda/commit/2fbef7d4bb4b2060aa10d0a14f0c42e53aa43cb2#r36632439

**Comment by nad** [comment]
> I don't understand why the pattern is not picked up by universeBi.

What do you expect to be picked up? How are these patterns represented in the abstract syntax?

**Comment by gallais** [comment]
They are represented as a [`Binder`](https://github.com/agda/agda/blob/master/src/full/Agda/Syntax/Abstract.hs#L249) that contains a `Maybe Pattern`.

So I would expect universeBi to pick up this `Pattern` for syntax highlighting.

**Comment by nad** [comment]
> They are represented as a [`Binder`](https://github.com/agda/agda/blob/master/src/full/Agda/Syntax/Abstract.hs#L249) that contains a `Maybe Pattern`.
> 
> So I would expect universeBi to pick up this `Pattern` for syntax highlighting.

Presumably it does. Perhaps the ranges of the pattern are incorrect. Have you tried to debug the code, perhaps by inserting some trace statement in `getPattern'`?

**Comment by nad** [comment]
For the first piece of code in the OP `getPattern` is applied to the following three patterns (I used `show`, which unfortunately does not produce proper Haskell code):
```haskell
VarP (BindName {unBind = B})
VarP (BindName {unBind = A})
ConP (ConPatInfo {conPatOrigin = ConOCon, conPatInfo = PatRange /tmp/Bug.agda:4,8-13, conPatLazy = ConPatEager}) (AmbQ {unAmbQ = Agda.Builtin.Sigma._,_ :| []}) [Arg {argInfo = ArgInfo {argInfoHiding = NotHidden, argInfoModality = Modality {modRelevance = Relevant, modQuantity = Quantityω QωInferred, modCohesion = Continuous}, argInfoOrigin = UserWritten, argInfoFreeVariables = UnknownFVs}, unArg = Named {nameOf = Nothing, namedThing = VarP (BindName {unBind = A})}},Arg {argInfo = ArgInfo {argInfoHiding = NotHidden, argInfoModality = Modality {modRelevance = Relevant, modQuantity = Quantityω QωInferred, modCohesion = Continuous}, argInfoOrigin = UserWritten, argInfoFreeVariables = UnknownFVs}, unArg = Named {nameOf = Nothing, namedThing = VarP (BindName {unBind = B})}}]
```
Note that the top-level constructor of the last pattern is `ConP`. There is no case for `ConP` in `getPattern'`:

https://github.com/agda/agda/blob/86cdfaca88b6fd1bd6846f586386c9595cd85075/src/full/Agda/Interaction/Highlighting/Generate.hs#L340-L359

This piece of code does not handle highlighting of constructors, see the following (out of date) comment:

https://github.com/agda/agda/blob/86cdfaca88b6fd1bd6846f586386c9595cd85075/src/full/Agda/Interaction/Highlighting/Generate.hs#L231-L233

I think highlighting of constructors is handled by the following two pieces of code (the comment is not entirely correct):

https://github.com/agda/agda/blob/86cdfaca88b6fd1bd6846f586386c9595cd85075/src/full/Agda/Interaction/Highlighting/Generate.hs#L181-L187

**Comment by nad** [comment]
Highlighting for the constructor is included in `nameInfo`, so I guess that some other highlighting (in `theRest`) takes precedence:

https://github.com/agda/agda/blob/86cdfaca88b6fd1bd6846f586386c9595cd85075/src/full/Agda/Interaction/Highlighting/Generate.hs#L202-L214

**Comment by nad** [comment]
When I replaced `bound n` with `mempty` in the following code, then highlighting worked fine for the example in the OP:

https://github.com/agda/agda/blob/4e6ef5bfc9a2a516c103384fbc348d8eb8780137/src/full/Agda/Interaction/Highlighting/Generate.hs#L321-L322

However, as expected highlighting did not work correctly for the following code:
```agda
open import Agda.Builtin.Sigma

F : Σ Set (λ _ → Set) → Σ Set (λ _ → Set)
F = λ P@(A , B) → P
```
The first occurrence of `P` was not highlighted properly.

I guessed that the problem with `getBinder` was that the range of the generated variable was set to the range of the pattern, and that seems to be the case:

https://github.com/agda/agda/blob/4e6ef5bfc9a2a516c103384fbc348d8eb8780137/src/full/Agda/Syntax/Parser/Parser.y#L987-L988

When I replaced the second occurrence of `(getRange $2)` with `noRange`, then both examples started working. Here is a test case:
```agda
open import Agda.Builtin.Sigma

F₁ : Σ Set (λ _ → Set) → Σ Set (λ _ → Set)
F₁ = λ P@(A , B) → P

F₂ : Σ Set (λ _ → Set) → Set
F₂ = λ (A , B) → A

F₃ : Σ Set (λ _ → Set) → Σ Set (λ _ → Set)
F₃ P = let Q@(A , B) = P in Q

F₄ : Σ Set (λ _ → Set) → Set
F₄ P = let (A , B) = P in B

F₅ : Σ Set (λ _ → Set) → Σ Set (λ _ → Set)
F₅ P@(A , B) = P

F₆ : Σ Set (λ _ → Set) → Set
F₆ (A , B) = B
```
@gallais, is there a reason for giving a range to a generated variable? (I might find out once I run `make test`.)

**Comment by gallais** [comment]
> is there a reason for giving a range to a generated variable?

I assumed it would make error reporting better by indicating that this
variable is implicitly bound in that bit of code.

**Comment by nad** [comment]
Can you construct a test case? Perhaps one could give a non-empty range that is zero characters wide.

**Comment by gallais** [comment]
The only thing I could currently think of is the use of a non-record pattern
such as `\ (suc n) -> n`. But the error points to the `suc n` pattern which is
perfectly fine. I think we can close this one for good.

Thanks for tracking this down!
