### ISSUE TITLE
Missing warning for declaring constructor instances for records with explicit fields

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#4360]
As far as I understand, the word `instance` in the first part of the code below has not effect, because the constructor has an explicit argument and functions can only be declared as instances if they do not have any explicit arguments. However there is no warning at all, unlike when actually declaring an function with explicit arguments in an instance block. There should be a warning and the code should be highlighted correspondingly.

```agda
-- No warning
record R (A : Set) : Set where
  instance constructor r
  field
    a : A

-- Warning
postulate
  R' : Set → Set
  instance r' : {A : Set} → A → R' A
```

**Comment by andreasabel** [comment]
Fixed that, was easy.

Ideally, such warnings would highlight the `instance` keyword in dead-code color, but for the time being, the `DefInfo` does not carry the error location of the instance keyword.

**Comment by gallais** [comment]
Does the fix also work for data constructors?

**Comment by andreasabel** [comment]
> Does the fix also work for data constructors?

Självklart. :)

I am now fixing the range of the warning to be the `instance` keyword.  Ok, have to be careful when several instances are in the instance block, then we would want the particular definition also to be highlighted.

**Comment by andreasabel** [comment]
For record constructors, the highlighting is on the `instance` keyword now.  For the other cases (data constructors, definitions, fields) it is on the identifier that does not qualify as instance.  Just highlighting the instance keyword would be ambiguous in case there are several definitions in one instance block.
