### ISSUE TITLE
Inconsistent highlighting of BUILTING EQUALITY/REWRITE

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#4361]
In the code below (in Emacs), the word `REWRITE` is highlighted but not `EQUALITY`.
```agda
{-# OPTIONS --rewriting #-}

data _==_ {A : Set} (x : A) : A → Set where
  instance refl : x == x
{-# BUILTIN EQUALITY _==_ #-}
{-# BUILTIN REWRITE _==_ #-}
```

**Comment by andreasabel** [comment]
This highlighting comes from the lexer.  For the lexer, `REWRITE` is a keyword (occurring in its own pragma `{-# REWRITE ... #-}`), but `EQUALITY` not.

The question is whether we should highlight all builtins as keyword.  I suppose yes.
