### ISSUE TITLE
Update test suite for working with what will be the standard library 1.3

### ISSUE THREAD

**Issue by asr** [agda/agda#4368]
After [this](https://github.com/agda/agda-stdlib/issues/1019#issuecomment-572905066) change, we need to update the submodule commit and the test suite for working with what will be the standard library 1.3.

**Comment by asr** [comment]
@MatthewDaggitt, after the merge of https://github.com/agda/agda-stdlib/pull/1045, I'm getting the following the error in the branch `issue-4368`:

```
make lib-succeed
...
Issue846:    FAIL (11.98s)
                   Diff between actual and golden value:
...
```

Could you push a fix into the above branch? (I'll squash all the changes before merging the branch).

**Comment by asr** [comment]
After the merge of https://github.com/agda/agda-stdlib/pull/1045, I'm getting the following the error in the branch `issue-4368`:

```
make std-lib-succeed
...
Issue846:    FAIL (11.98s)
                   Diff between actual and golden value:
...
```

Could someone push a fix into the above branch? (I'll squash all the changes before merging the branch).

**Comment by asr** [comment]
I'm also getting the error:

```
make std-lib-compiler-test
...
+ret > ExitFailure 1
+out > /Vec.agda:19,1-64
+out > Multiple definitions of transpose. Previous definition at
+out > /home/asr/src/agda/agda-upstream/std-lib/src/Data/Vec/Base.agda:294,1-10
+out > when scope checking the declaration
+out >   transpose : {n m : ℕ} {a : Set} → Matrix a m n → Matrix a n m
```

Any ideas or fixes?

Edit: Fixed by renaming the `transpose` function.

**Comment by MatthewDaggitt** [comment]
@asr apologies, I was meaning to do this yesterday but it completely slipped my mind. Thank you very much for picking up the slack :heart:
