### ISSUE TITLE
REWRITE with record field

### ISSUE THREAD

**Issue by conal** [agda/agda#4369]
Is it the case that Agda does not currently support `REWRITE` with record fields? As an example, please see https://github.com/conal/calculating-compilers-agda/issues/5 .

If indeed Agda is limited in this way now, can the limitation be lifted? This combination seems fairly compellingly useful to me: (a) describe constraints in a representation via equality proof fields (b) use these invariants to simplify automatically.

**Comment by conal** [comment]
@jespercockx: @Blaisorblade suggested asking you specifically.

**Comment by jespercockx** [comment]
It's correct that it's currently not yet supported, see #1981. I started working on it last year, but there were still a few things that were not working well, and I got distracted by other things. You can see my work so far on https://github.com/jespercockx/agda/tree/rewriting-projections.
