### ISSUE TITLE
Agda --doublecheck cannot resolve level

### ISSUE THREAD

**Issue by EdNutting** [agda/agda#4370]
Hi,

https://github.com/agda/agda-stdlib/blob/aa7c23b7561b99e15bb7572e5ddc64cf1e1deff8/src/Relation/Binary/Morphism/Definitions.agda#L30

Loading this module with `agda --safe --doublecheck ...` causes it to complain that it can't work out the output level. Not sure if this is expected/desired or not. The fix seems to be to replace `Set _` with `Set (a ⊔ ℓ₁ ⊔ ℓ₂)`.

Cheers,
Ed

**Comment by jespercockx** [comment]
I'm closing this due to lack of a MWE, feel free to reopen if you have a standalone example.
