### ISSUE TITLE
Less responsive Emacs mode in v2.6.1 release candidate 1

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda#4387]
Whilst using Emacs mode for the v2.6.1 release candidate I've noticed that the type checking command is less responsive than before. In 2.6.0.1 the ***All done*** message in the bottom buffer is instantly replaced by ***Type-checking*** after pressing `C-c C-l`. However in the release candidate there's approximately a 2 second delay before the ***Type checking*** message comes up. During those 2 seconds there's no visual indication that the command has been accepted and so I keep thinking something has gone wrong...

Edit: weirdly if you switch to another window and then switch back to emacs, the message then appears instantly when you next type-check it. All subsequent type-checks however have a 2 second delay...

**Comment by UlfNorell** [comment]
Does this happen also for tiny modules with no dependencies?

**Comment by MatthewDaggitt** [comment]
So if you kill and restart Agda and then type check the file:
```agda
module Test where
```
then it's instantaneous. However if you type check some big development, and then try to type check the module `Test` then it takes the standard 2 seconds...

**Comment by nad** [comment]
I've noticed something similar.

**Comment by nad** [comment]
@UlfNorell, did you look into this?

**Comment by UlfNorell** [comment]
Not further than being able to reproduce the issue:
- Load standard library `Everything.agda`
- Switch to empty `Test.agda`
- Reload (takes 2 seconds)
- Reload again (instant)

**Comment by nad** [comment]
Is `Test.agda` in the same directory as `Everything.agda`?

**Comment by UlfNorell** [comment]
No.

**Comment by nad** [comment]
I tried the same example. I noticed that Agda is busy after `Everything.agda` has been type-checked. If I wait until Agda settles down, then `Test.agda` loads quickly.

**Comment by nad** [comment]
I've tried to figure out what Agda does after the file has been type-checked. I think there are two threads, both of which are idle:
* The main thread is waiting for a command from the command queue:

  https://github.com/agda/agda/blob/24929e161b2951beff5cf5ba5a5450e3cc9d2107/src/full/Agda/Interaction/InteractionTop.hs#L327
* The thread that reads commands is waiting for input:

  https://github.com/agda/agda/blob/24929e161b2951beff5cf5ba5a5450e3cc9d2107/src/full/Agda/Interaction/AgdaTop.hs#L61

My current guess is that a major GC is triggered when the RTS notices that all threads are idle.

**Comment by nad** [comment]
I tried to use ThreadScope. I used three methods to run Agda (in all cases with all dependencies of `Everything.agda` already type-checked, but not cached in memory):
* Using `agda -i. Everything.agda +RTS -l`:

  ![noninteractive](https://user-images.githubusercontent.com/293222/74737516-4ade4580-5255-11ea-8b5e-15d0aaa54065.png)

* Using `runhaskell Main.hs agda` and the following script:
  ```haskell
  {-# LANGUAGE RecordWildCards #-}

  import RunAgda

  main :: IO ()
  main = runAgda ["-i.", "+RTS", "-l"] $ \(AgdaCommands { .. }) -> do

      -- Discard the first prompt.
      echoUntilPrompt

      -- Load the module.
      loadAndEcho "Everything.agda"

      return ()
  ```

  ![interactive-unsupervised](https://user-images.githubusercontent.com/293222/74739477-313efd00-5259-11ea-9615-5f07d4f7e50d.png)

* Using the Emacs mode (I waited until `top` indicated that the Agda process was spinning down, at which time I terminated Agda):

  ![interactive](https://user-images.githubusercontent.com/293222/74740102-83cce900-525a-11ea-9cfb-d7a51600e9fb.png)

  Agda was done type-checking after about 45 s (wall-clock time), and then it took perhaps 15-20 s more before I terminated Agda. However, ThreadScope presented me with roughly the same information if I terminated Agda right away when Agda claimed to be done, so the interesting part does not seem to be represented. The last element in the event log is "HEC 0: GC working", so I guess that some information is not included.

  Notice the gap: after what seems to be a major GC Agda is completely idle for a while, before it starts working again.

If anyone else wants to try: To use ThreadScope, compile Agda with `-eventlog` and run Agda with the RTS option `-l`.

**Comment by UlfNorell** [comment]
This matches my observations. What's interesting though is that it doesn't happen for 2.6.0.1. There I get about 2 seconds of 50% CPU after the `Checked` message, and even if I switch directly to `Test.agda` it loads instantly.

What versions of ghc are you running (@nad / @MatthewDaggitt)? I'm on 8.8.1, trying now with 8.4.3.

**Comment by nad** [comment]
I made it possible to terminate Agda gracefully from the Emacs mode, and got the following output (the process spun down a couple of seconds before I asked it to terminate itself):

![interactive](https://user-images.githubusercontent.com/293222/74817182-c941f280-52fc-11ea-85b6-920fb7457847.png)

**Comment by nad** [comment]
I'm using GHC 8.6.5.

Agda 2.6.0.1 is not compiled with `-threaded`, I suggest that you start by removing this flag.

**Comment by nad** [comment]
When the threaded RTS is used ["a major GC is automatically performed if the runtime has been idle (no Haskell computation has been running) for a period of time"](https://downloads.haskell.org/~ghc/8.8.2/docs/html/users_guide/runtime_control.html#rts-flag--I%20%E2%9F%A8seconds%E2%9F%A9). One can turn off this feature by using `-I0`. That seems to fix the problem.

**Comment by nad** [comment]
The documentation of `-I` includes the following text: "This is an experimental feature, please let us know if it causes problems and/or could benefit from further tuning".

**Comment by nad** [comment]
Has anyone figured out why there is a gap in the activity reports? Can you replicate the gap?

**Comment by UlfNorell** [comment]
I'm just eyeballing using top, but I'm not getting any gaps in CPU usage. After `Checked` appears there's another 15-20s of 100% CPU before it calms down. After that it stays idle.

The threaded flag was added in #3748, for no particularly compelling reason, so if that is indeed the problem I suggest we get rid of it again.

**Comment by nad** [comment]
I don't plan to add a regression test for this bug. However, I could trigger the problematic behaviour by using `runhaskell Main.hs agda`, where `Main.hs` is defined in the following way:
```haskell
{-# LANGUAGE RecordWildCards #-}

import Control.Concurrent
import RunAgda

main :: IO ()
main = runAgda ["-i.", "+RTS", "-l"] $ \(AgdaCommands { .. }) -> do

    -- Discard the first prompt.
    echoUntilPrompt

    -- Load the module and wait until Agda reports that it has
    -- finished.
    loadAndEcho "Everything.agda"

    -- Sleep for 0.5 seconds, to allow a major GC to start.
    threadDelay 500000
```
The ThreadScope output:
![interactive-unsupervised](https://user-images.githubusercontent.com/293222/74819891-60a94480-5301-11ea-86fd-44849cab4ef8.png)

**Comment by nad** [comment]
> The threaded flag was added in #3748, for no particularly compelling reason, so if that is indeed the problem I suggest we get rid of it again.

Using `-I0` seems to work fine. Have you tested this? I've added this to the `-with-rtsopts` flag (but I have not pushed yet).

**Comment by UlfNorell** [comment]
Yes `-I0` solves the problem for me as well. Is that available for all ghc versions we support?

**Comment by nad** [comment]
With the threaded runtime system we have the possibility to use multiple threads for GC. I tried this, and got the following output (using the previous script, with `-N2`, `-qg1` and `-I0` added to the RTS flags):
![multiple-cores](https://user-images.githubusercontent.com/293222/74821301-acf58400-5303-11ea-8b43-3109ad497fe4.png)
In this particular case the difference seems to be small.

**Comment by nad** [comment]
The `-I` flag is supported by GHC 6.6.

**Comment by nad** [comment]
> I'm just eyeballing using top, but I'm not getting any gaps in CPU usage. After `Checked` appears there's another 15-20s of 100% CPU before it calms down. After that it stays idle.

I did not observe the gap using top.

**Comment by MatthewDaggitt** [comment]
> What versions of ghc are you running (@nad / @MatthewDaggitt)? I'm on 8.8.1, trying now with 8.4.3.

Looks like you've found the cause, but just in case I'm on 8.0.2

**Comment by UlfNorell** [comment]
Adding `-I0` seems like the best way to fix the problem then.
