### ISSUE TITLE
[doc] document anonymous copattern syntax

### ISSUE THREAD

**Issue by MarcelineVQ** [agda/agda#4393]
I've just been exposed to 'anonymous syntax for constructing records by copatterns' and am unable to find it in the documentation. If it's missing it would be worthwhile to add it.
In particular for
```agda
mutual
  data Delay (A ∶ Set) (i ∶ Size) ∶ Set where
    now ∶ A → Delay A i
    later ∶ ∞Delay A i → Delay A i

  record ∞Delay (A ∶ Set) (i ∶ Size) ∶ Set where
    coinductive
    field
      force ∶ {j ∶ Size< i} → Delay A j
```
This
```agda
mutual
  never′ ∶ ∀ {i A} → Delay A i
  never′ = later ∞never′

  ∞never′ ∶ ∀ {i A} → ∞Delay A i
  force ∞never′ = never′
```
can be replace by
```agda
never ∶ ∀ {i A} → Delay A i
never {i} = later 𝜆 where .force {j} → never {j}
```
`where .force {j} → never {j}` is not an obvious thing, to me, and I'm unable to find this possibility being covered in either the copattern, record, or coinduction documentation. I'm told part of this syntax is called postfix projections, which is also not documented that I can tell.

**Comment by UlfNorell** [comment]
It can sort of be inferred from the [docs on pattern lambdas](https://agda.readthedocs.io/en/latest/language/lambda-abstraction.html), but it would be good to mention it explicitly there.

**Comment by MarcelineVQ** [comment]
Is that the best place to mention it? This may be because I don't know how coinductive records are created/translated behind the scenes but as a user I would not have thought to connect them to documentation for pattern lambda's.

I don't actually understand how the lambda-to-.extlam translation leads to knowing one can write that `.force` in a `where`, is there a fairly explainable direct connection? It could also make for good documentation.

**Comment by Blaisorblade** [comment]
After some discussion on IRC `##dependent`, it seems there's a few missing docs:
1. Copattern lambdas should also be shown, indeed.
2. `𝜆 where` is equivalent to `𝜆 {...}` (says @gallais), but I can't find that documented under pattern lambdas nor under https://agda.readthedocs.io/en/v2.6.0.1/language/lexical-structure.html#layout.
3. On pattern lambdas, why is the generated function called `.extlam` instead of `extlam`? Which of the 42 meanings of `.` is intended.

**Comment by gallais** [comment]
> On pattern lambdas, why is the generated function called .extlam instead of extlam? Which of the 42 meanings of . is intended.

It means: not in scope. Users should not be able to rely on the generated name.

**Comment by jespercockx** [comment]
I thought we are no longer using `.` to refer to out-of-scope names, or is it still in use for pattern-matching lambdas?

**Comment by gallais** [comment]
The names for generated functions are [here](https://github.com/agda/agda/blob/master/src/full/Agda/TypeChecking/Monad/Base.hs#L4125)

**Comment by Blaisorblade** [comment]
Since you're linking to sources, I'd propose to drop the dot from the documentation, and instead *say* that `extlam` is a fresh name — #4395 is an attempt (which does *not* close this issue).

**Comment by MarcelineVQ** [comment]
After being taken through this example by people in ##dependent I can pinpoint my confusion a little better and it was that I didn't know about `postfix projections` and what `𝜆 where` does. Because of not understanding postfix projections, the link to [lambdas](https://agda.readthedocs.io/en/latest/language/lambda-abstraction.html) was confusing because it has a different use of `.` which was clashing in my head with the one being used in postfix projections.

While I understand what is happening now with this anonymous copattern syntax it would be a good addition to have documentation for `postfix projections` and `𝜆 where` so that people have the puzzle pieces to assemble themselves and not have to rely on awesome people on irc.

**Comment by Blaisorblade** [comment]
@MarcelineVQ Hope #4396 answers those concerns.

**Comment by MarcelineVQ** [comment]
Yes I think that should let people parse the example code on their own.
