### ISSUE TITLE
Case split on unnamed argument produces non-sensical code

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#4399]
```agda
postulate
  A : Set

data T : Set where
  tt : T

f : {x : A} {{_ : T}} → A
f {{ p }} = {!p!}
```

Case-splitting on `p` in the hole above produces the following invalid clause
```agda
f ⦃ _ = tt ⦄ = ?
```
and an incomprehensible error message:
```
/home/gubr5004/Dropbox/Agda/GeneralInitiality/test.agda:8,5-11
Not a finite domain: Dom {domInfo = ArgInfo {argInfoHiding =
Instance NoOverlap, argInfoModality = Modality {modRelevance =
Relevant, modQuantity = Quantityω QωInferred, modCohesion =
Continuous}, argInfoOrigin = UserWritten, argInfoFreeVariables =
UnknownFVs}, domFinite = False, domName = Just (WithOrigin
{woOrigin = Inserted, woThing = Ranged {rangeOf =
/home/gubr5004/Dropbox/Agda/GeneralInitiality/test.agda:7,15-16,
rangedThing = "_"}}), domTactic = Nothing, unDom = El {_getSort =
Type (Max 0 []), unEl = Def test.T []}}
when checking that the pattern (_ = tt) has type T
```

_Edit: slightly simplified the code_

**Comment by jespercockx** [comment]
@Saizan are you perhaps using `show` directly to print the domain? That doesn't look very good. Also, `splitPartial` should probably not even be called when `--cubical` is not active.

**Comment by Saizan** [comment]
Yeah, the error message should be improved. And splitPartial should check the flag.

However case split shouldn't generate ```⦃ _ = ... ⦄``` as that's not a valid way to match against the right argument, in fact parsing does not recognize it as a named binding (otherwise it wouldn't trigger a partial split).

**Comment by andreasabel** [comment]
The printing as `{{_ = tt}}` was a regression in 2.5.1.1, the parsing as partial split a regression in 2.6.0.
