### ISSUE TITLE
TERMINATING pragma in where clause

### ISSUE THREAD

**Issue by gallais** [agda/agda#4400]
The following test case leads to

> Termination pragmas are not allowed inside where clauses
> when scope checking the declaration

```agda
f : Set → Set
f S = T where

  {-# TERMINATING #-}
  mutual

    T = F
    F = S → T
```

while this one leads to a termination error because the
TERMINATING pragma is neither rejected nor taken into account:

```agda
f : Set → Set
f S = T where

  mutual

    {-# TERMINATING #-}
    T = F
    F = S → T
```

**Comment by andreasabel** [comment]
See also #3008 and #3355.

**Comment by andreasabel** [comment]
See further #1137.

**Comment by gallais** [comment]
We need a fuzzer inserting pragmas in random places & trying to break things. :joy:
