### ISSUE TITLE
Panic: unbound variable with universe level arguments in parentheses in record

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#4402]
The code below fails with the error
```
Panic: unbound variable l (id: 10@8067455048520291618)
when checking that the expression l has type Level
```

```agda
open import Agda.Primitive

record R (l) : Set (lsuc l) where
  field
    A : Set l
```

Removing the parentheses around the `(l)` makes the error go away (!).

**Comment by gallais** [comment]
`(l)` means `_@(l)` and indeed the following raises the same error:

```agda
open import Agda.Primitive

record R a@l : Set (lsuc l) where
  field
    A : Set l
```

Edit: interesting that,

```agda
open import Agda.Primitive
open import Agda.Builtin.Sigma
open import Agda.Builtin.Equality

record R {A : Set} {B : A → Set} (p@(a , b) : Σ A B) : Set where
  field
    prf : p ≡ (a , b)
```

is rejected with

> p @ ((a , b)) is not allowed in a telescope here

**Comment by guillaumebrunerie** [comment]
Also the issue is not present in Agda 2.6.0.1, but it seems like as-patterns were not allowed in arguments of a record then?

**Comment by gallais** [comment]
It may have been introduced by my PR #3884.

**Comment by andreasabel** [comment]
@gallais, I am assuming you are taking this (and assigned you); if not, please unassign yourself.

**Comment by zraffer** [comment]
> ```agda
> open import Agda.Primitive
> open import Agda.Builtin.Sigma
> open import Agda.Builtin.Equality
> 
> record R {A : Set} {B : A → Set} (p@(a , b) : Σ A B) : Set where
>   field
>     prf : p ≡ (a , b)
> ```
> 
> is rejected with
> 
> > p @ ((a , b)) is not allowed in a telescope here

Whereas `Panic` has gone, we still have `not allowed in a telescope` error in record, as mentioned. Should it be considered as an issue? Should records understand patterns? The test code above can be even minimized into

```agda
open import Agda.Builtin.Unit
record Test ((tt) : ⊤) : Set where
```

**Comment by gallais** [comment]
This feature request should probably go in a different issue.
In the meantime, I'll refer you to [the comment explaining this design decision](https://github.com/agda/agda/blob/2895e438a06f2ca6be4e051b5edf1fa2cca775e6/src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs#L1098-L1104):

```agda
-- | We for now disallow let-bindings in @data@ and @record@ telescopes.
--   This due "nested datatypes"; there is no easy interpretation of
--   @
--      data D (A : Set) (open M A) (b : B) : Set where
--        c : D (A × A) b → D A b
--   @
--   where @B@ is brought in scope by @open M A@.
```
