### ISSUE TITLE
Can pattern-matching lambdas slow down Agda?

### ISSUE THREAD

**Issue by nad** [agda/agda#4412]
I have found an example of code that becomes faster if a pattern-matching lambda is replaced by regular pattern matching. Is this expected? If not, then one can perhaps optimise something.

The code can be obtained in the following way:
```
git clone http://www.cse.chalmers.se/~nad/repos/equality
cd equality
git checkout 41d373092b74ec83a35482d2f5ef0fca94a60630
```
Go to the file `src/Finite-subset/Listed.agda`. Observe (using interactive highlighting) roughly how much time it takes for Agda to type-check the definition `∣∣≡-functional`. Then find the local definition `r` in the function `Size`:
```agda
    r : Rec A (ℕ → Proposition a)
    r .[]ʳ n = ↑ _ (n ≡ 0) , ↑-closure 1 ℕ-set
    ⋮
```
Define `r` using a pattern-matching lambda in the following way:
```agda
    r : Rec A (ℕ → Proposition a)
    r = λ where
      .[]ʳ n → ↑ _ (n ≡ 0) , ↑-closure 1 ℕ-set
    ⋮
```
Now it should be possible to observe that it takes (a little) more time for Agda to type-check `∣∣≡-functional`.

**Comment by andreasabel** [comment]
> code that becomes faster if a pattern-matching lambda is replaced by regular pattern matching. Is this expected?

Well, pattern lambdas create a new definition.  Thus, it is to be expected that it is a bit slower.  Not sure how much, though.

Agda could internally optimize
```agda
f xs = \ where
  ps -> es
```
to
```agda
f xs p1 = e1
...
f xs pn = en
```

**Comment by UlfNorell** [comment]
Can you clarify whether it's the pattern lambda or the extra definition that's causing the slow-down? What's the performance of
```agda
r' : Rec A (ℕ → Proposition a)
r' .[]ʳ n = ↑ _ (n ≡ 0) , ↑-closure 1 ℕ-set
    ⋮
r : Rec A (ℕ → Proposition a)
r = r'
```
?

**Comment by nad** [comment]
I failed to reproduce the problem using recent versions of Agda and my code.
