### ISSUE TITLE
[unicode-input] multiple subscript characters allowed?

### ISSUE THREAD

**Issue by pnlph** [agda/agda#4413]
I am unsuccessfully trying to introduce a name with multiple characters as subscript using `agda-mode`. Is this allowed in Agda, or is it a Unicode restriction?

The documentation speaks about sub-/superscripted characters, but not words:
https://agda.readthedocs.io/en/latest/tools/emacs-mode.html#show-me-some-commonly-used-characters

**Comment by guillaumebrunerie** [comment]
Could you be more precise about what you are trying to do? Note that some letters do not exist as subscripts/superscripts, that is a Unicode restriction, Agda cannot do anything about that.

**Comment by guillaumebrunerie** [comment]
```agda
ₜₕᵢₛʷᵒʳᵏˢ : Set₁
ₜₕᵢₛʷᵒʳᵏˢ = Set
```

**Comment by pnlph** [comment]
Thanks! Now i got it.

I think that in order to get `ₙₐₘₑ` written down in the editor, the user has to introduce the following keyboard sequence:
`\_n\_a\_m\_e`

And I was expecting `\_name` to work. The problem is that when you type `\_n`, typing `a` right away results in escaping the unicode input method, so what you get is `ₙa`.
