### ISSUE TITLE
Union patterns ['Multi match' language extension suggestion] 

### ISSUE THREAD

**Issue by t-more** [agda/agda#4416]
Recently I've needed to write a lot of duplicated code in order to satisfy Agdas type checker when it comes to proofs on what should be 'catch all cases'. (see example below). I would like to suggest a possible language extension that removed the need for this duplication. 

``` agda
    contract∘uncontract≡id
      (stm@(assign _) ∷ rest)
      ( _ List.Linked.∷ alpha
      , _ List.All.∷ beta) =
      cong (stm ∷_) (contract∘uncontract≡id rest (alpha , beta))
    contract∘uncontract≡id
      (stm@(continue _) ∷ rest)
      ( _ List.Linked.∷ alpha
      , _ List.All.∷ beta) =
      cong (stm ∷_) (contract∘uncontract≡id rest (alpha , beta))
    contract∘uncontract≡id
      (stm@(break _) ∷ rest)
      ( _ List.Linked.∷ alpha
      , _ List.All.∷ beta) =
      cong (stm ∷_) (contract∘uncontract≡id rest (alpha , beta))
    contract∘uncontract≡id
      (stm@(return _ _) ∷ rest)
      ( _ List.Linked.∷ alpha
      , _ List.All.∷ beta) =
      cong (stm ∷_) (contract∘uncontract≡id rest (alpha , beta))
```
 et cetera et cetera.

In order to remove the need for all this duplication i would like to suggest some kind of syntax that  tells Agda that it should use the particular case if any of the statements match.
for example using the example above
``` agda
    contract∘uncontract≡id
      (stm@(assign _ | continue _ | break _ | return _ _) ∷ rest)
      ( _ List.Linked.∷ alpha
      , _ List.All.∷ beta) =
      cong (stm ∷_) (contract∘uncontract≡id rest (alpha , beta))
```
Internally this could of course be expanded to multiple different cases. This would only be syntactic sugar.

It should even be possible to extract  some information from all the pattern matches as long as the particular field has the same type. In the example all the first fields of the data types contains the same datatype therefore it could be possible to safely use the values of those fields like this:
``` agda
    contract∘uncontract≡id
      (assign same | continue same | break same | return same _) ∷ _)
      _ = ? -- we should be able to use 'same' here
```

**Comment by gallais** [comment]
Note that you can use a view to get catchalls that compute.

**Comment by nad** [comment]
What about goals (interaction points)? We have discussed similar things in the past, and I have not yet seen a reasonable treatment of goals in the right-hand side of such a clause.

**Comment by t-more** [comment]
You're right, it could possible get pretty nasty quickly doing something non-trivial. One idea could be to add extra notation to the interaction points in order to inspect them from the view a of a particular case?
Say `{  -case <num>}` (or  something similar) and always default to the first case? Errors could be reported case for case? That is internally each case would of course be handled separately, therefore if you open one interaction point, one is created for each match separately.

In my mind, the main purpose of such an extension would be to get rid of simple reductions. If one were to have a lot of trouble with some particular cases it it always possible to simply create an explicit case for the trouble maker.

**Comment by andreasabel** [comment]
With interaction, it gets messy.  If you only create the interaction point for the first alternative, then, then accepted refinements for this interaction point could be rejected upon reloading the files.  
To do this properly requires quite a bit of new infrastructure.

Most of what you want you could get already if we had `where`-blocks that scope over several clauses and contain definitions that are inlined in the rhss _before_ type checking, with the effect that these definitions can have different types for each use on a rhs (poor-man's polymorphism).  For your case:
```agda
let
  fallback stm rest alpha beta =
    cong (stm ∷_) (contract∘uncontract≡id rest (alpha , beta))
in
    contract∘uncontract≡id
      (stm@(assign _) ∷ rest)
      ( _ List.Linked.∷ alpha
      , _ List.All.∷ beta) = fallback stm rest alpha beta 
    contract∘uncontract≡id
      (stm@(continue _) ∷ rest)
      ( _ List.Linked.∷ alpha
      , _ List.All.∷ beta) = fallback stm rest alpha beta 
    contract∘uncontract≡id
      (stm@(break _) ∷ rest)
      ( _ List.Linked.∷ alpha
      , _ List.All.∷ beta) = fallback stm rest alpha beta 
    contract∘uncontract≡id
      (stm@(return _ _) ∷ rest)
      ( _ List.Linked.∷ alpha
      , _ List.All.∷ beta) = fallback stm rest alpha beta 
```
Or:
```agda
  group
    contract∘uncontract≡id
      (stm@(assign _) ∷ rest)
      ( _ List.Linked.∷ alpha
      , _ List.All.∷ beta) = fallback 
    contract∘uncontract≡id
      (stm@(continue _) ∷ rest)
      ( _ List.Linked.∷ alpha
      , _ List.All.∷ beta) = fallback 
    contract∘uncontract≡id
      (stm@(break _) ∷ rest)
      ( _ List.Linked.∷ alpha
      , _ List.All.∷ beta) = fallback 
    contract∘uncontract≡id
      (stm@(return _ _) ∷ rest)
      ( _ List.Linked.∷ alpha
      , _ List.All.∷ beta) = fallback 
  where
    fallback = cong (stm ∷_) (contract∘uncontract≡id rest (alpha , beta))
```

**Comment by nad** [comment]
How does this solve the problem with goals?

**Comment by andreasabel** [comment]
> How does this solve the problem with goals?

It doesn't.

Anyway, such a feature needs a solid proposal offering solutions for the problems we could face in type checking.
I am closing this issue, but please reopen if you have a proposal.
