### ISSUE TITLE
guardedness is too weak to handle M types

### ISSUE THREAD

**Issue by Soares** [agda/agda#4418]
The following code:

```agda
{-# OPTIONS --safe --guardedness #-}
module M {l}
  (Index : Set l)
  (Shape : Index -> Set l)
  (Position : (i : Index) -> Shape i -> Set l)
  (index : (i : Index) -> (s : Shape i) -> Position i s -> Index) where

record M (i : Index) : Set l where
  coinductive
  field shape : Shape i
  field children : (p : Position i shape) -> M (index i shape p)

open M

record MBase (Rec : Index -> Set l) (i : Index) : Set l where
  coinductive
  field shapeB : Shape i
  field childrenB : (p : Position i shapeB) -> Rec (index i shapeB p)

open MBase

unroll : (S : Index -> Set l) -> (∀ {i} -> S i -> MBase S i) -> ∀ {i} -> S i -> M i
shape (unroll S u s) = shapeB (u s)
children (unroll S u s) p = unroll S u (childrenB (u s) p)
```

Yields the following error:

```
Termination checking failed for the following functions:
  unroll
Problematic calls:
  shape (unroll S u s)
  unroll S u (childrenB (u s) p)
```

Unless I'm mistaken, the `guardedness` feature is fully general (setting aside coinduction-recursion) with respect to codata exactly insofar as it can handle the `unroll` function. If it can, then any shortcoming in the guardedness heuristics can in principle be patched over by the user manually translating their coinductive type into an `M`. If it cannot, then it seems to me that safe agda with `guardedness` doesn't *really* support coinduction, but rather supports some ad-hoc poorly-documented subset of it.

This looks to me like a bug -- my guess is that it's a bug in the guardedness checker, but it's at least a bug in the docs.

I'm on agda version 2.6.0.1, fwiw.

**Comment by gallais** [comment]
Did you forget to use musical notations to mark the infinite part of the
coinductive definition? This works:


```agda
{-# OPTIONS --safe --guardedness #-}
module guarded {l}
  (Index : Set l)
  (Shape : Index -> Set l)
  (Position : (i : Index) -> Shape i -> Set l)
  (index : (i : Index) -> (s : Shape i) -> Position i s -> Index) where

open import Agda.Builtin.Coinduction

record M (i : Index) : Set l where
  coinductive
  constructor _,_
  field shape : Shape i
        children : (p : Position i shape) → ∞ (M (index i shape p))
open M

record MBase (Rec : Index -> Set l) (i : Index) : Set l where
  constructor _,_
  field shapeB : Shape i
        childrenB : (p : Position i shapeB) -> Rec (index i shapeB p)
open MBase


module unroll (S : Index -> Set l) (ψ : ∀ {i} -> S i -> MBase S i) where

  unroll : ∀ {i} -> S i -> M i
  unroll s = let (sh , f) = ψ s in sh , λ p → ♯ unroll (f p)
```

**Comment by Soares** [comment]
Yep! Thanks. FWIW, from my (apparently erroneous) read of the coinduction docs, the musical notation was only related to the (dubiously safe) "old-style coinduction". Or perhaps this is "old-style coinduction" now, and the dubious unsafety was only related to a combination of old-style coinduction & sized types? Or perhaps this is a mix of old-style coinduction & coinductive records? I'm happy to have the incantation that makes this work on hand now, but I admit I still don't understand what's going on, and don't find [these docs](https://agda.readthedocs.io/en/v2.6.0.1/language/coinduction.html) particularly illuminating on the matter. I'd appreciate further explanation, but can also just go stare at related code and try to figure it out myself.

(Feel free to close and/or leave open as a docs bug, and thanks for the speedy reply :-))

**Comment by nad** [comment]
This might be related to #4391.

**Comment by andreasabel** [comment]
@Soares : there is nothing a priori wrong with your code in the OP, you are using coinduction and guardedness as intended.

> Problematic calls:
>   shape (unroll S u s)

This call seems to come from the type of `p`.  Maybe issue #906.

The termination error is already raised for the incomplete definition:
```agda

module _ (S : Index → Set l) (u : ∀ {i} → S i → MBase S i) where

  unroll : ∀ {i} → S i → M i
  unroll s .shape      = u s .shapeB
  unroll s .children p = unroll {!!}
```
```
Termination checking failed ...
Problematic calls:
  unroll s .shape
  unroll ?1
when checking that the expression unroll ? has type
M (index i (unroll s .shape) p)
```

The use of guardedness in definitions by copattern-matching has problems with dependent types, your case is just one instance.  This is why I always use sized types for coinduction.

In this case, the same workaround as for #906 applies: give the implicit argument `i` directly, avoiding the recursive call there, instead of letting Agda infer it (which puts the recursive call there):
```agda
  unroll : ∀ {i} → S i → M i
  unroll s .shape      = u s .shapeB
  unroll s .children p = unroll {i = index _ (u s .shapeB) p} (u s .childrenB p)
```

@gallais: You have introduced a second layer of coinduction using the infinity type constructor.  This should not be necessary.
