### ISSUE TITLE
Uncurrying behind the veil [Optimisation opportunity?]

### ISSUE THREAD

**Issue by nad** [agda/agda#4419]
I was developing some code that took a long time to type check. The code used eliminators, and I made the code a lot faster by changing the eliminators so that most of the arguments became record fields. As a simplified example, consider the following eliminator for natural numbers:
```agda
elim :
  (P : Nat → Set) →
  P zero →
  (∀ {n} → P n → P (suc n)) →
  ∀ n → P n
elim P z s zero    = z
elim P z s (suc n) = s (elim P z s n)
```
This eliminator can be replaced by the following one (given suitable variable declarations):
```agda
record Elim (P : Nat → Set) : Set where
  field
    z : P zero
    s : P n → P (suc n)

elim : Elim P → ∀ n → P n
elim {P = P} e = helper
  where
  helper : ∀ n → P n
  helper zero    = Elim.z e
  helper (suc n) = Elim.s e (helper n)
```
Given that this made my code faster I wonder if we can do something like this automatically.

First let me speculate about why the code became faster: I replaced several arguments with single definitions using copatterns. (Either pattern-matching lambdas or named definitions.) Thus, when Agda later compared things for equality, it could (more often?) do so by name. I tried to verify this using ` --no-syntactic-equality`, but unfortunately this option is broken (#4265).

Now, it appears to me as if the new code is functionally equivalent to the old one: the record types that I use come with η-equality, so if Agda would need to unfold anything it could do so. Thus I wonder if it would be possible and worthwhile to do this "uncurrying" transformation automatically behind the scenes for all or some code.

**Comment by Saizan** [comment]
So you mean that you also defined your functions like the following?

```agda
f x0..xn = elim args
  where
      args .Elim.z = ...
      args .Elim.s = ... 
```

**Comment by nad** [comment]
Yes, something like that.

**Comment by andreasabel** [comment]
>  if it would be possible and worthwhile to do this "uncurrying" transformation automatically behind the scenes for all or some code.

Frankly, I'd say this is a very high hanging fruit since you also need to take care to print things back to the user as they wrote it.  Thus, you need a faithful reverse translation and apply it before printing any errors.

As of now, we are not getting this right for the (simple?) case of module instantiations.  Before we understand this already existing transformation properly, it seems no good to add more of that sort.

Pie in the sky, I'd say.  But you should publish your technique so folks can learn the dark arts.
