### ISSUE TITLE
[doc] What are .agdai files?

### ISSUE THREAD

**Issue by pnlph** [agda/agda#4425]
I did not find information about `.agdai` files while searching in the latest readthedocs. I found some scattered information on the issues #3185 #3909 #3549

Let's answer at least the following:
* why when saving an `.agda` file in the editor, the `.agdai` file is automatically created
* what the `.agdai` file is
* fo which things the `.agdai` file can be used

Where in the documentation should this be added?

**Comment by andreasabel** [comment]
The `.agdai` "interface" files contain the type-checked version of the `.agda` files in compressed form:
- all implicit arguments have been resolved
- pattern matching definitions have been translated to case trees to speed up computation
- the compression run to create the .agdai file has introduced sharing in the expression trees to make code loaded from interface files more memory-efficient.

An external module is loaded by loading its interface file.  Interface files are also intermediate points when compiling through a backend to e.g. Haskell.

Is this information helpful for writing documentation on this? 

I think with the current structure of the documentation, you could create a section `Interface files` under `Tools`.

**Comment by nad** [comment]
>     * all implicit arguments have been resolved

Not necessarily (`--allow-unsolved-metas`).

> Is this information helpful for writing documentation on this?

I don't think we should include implementation details in the documentation. Perhaps it suffices to write that the interface files are a representation of the source files, intended to make some operations faster. We could also include information about user-visible things like the locations and names of these files.

**Comment by andreasabel** [comment]
> interface files are a representation of the source files

This does not sound right.  This misses the main point, saving the results from the type-checking process. The syntax represented in `.agdai` files significantly differs from the one of source files.  Formally, it is a compiled version of the source that can be executed by the Agda machine.  (Of course, one could compile even further into more primitive representations.)

**Comment by nad** [comment]
> > interface files are a representation of the source files
> 
> This misses the main point, saving the results from the type-checking process.

Well, you omitted "intended to make some operations faster".

**Comment by andreasabel** [comment]
> Well, you omitted "intended to make some operations faster".

I had no complaints about that part. ;)

**Comment by andreasabel** [comment]
> I don't think we should include implementation details in the documentation.

Giving the user a rough model of what goes on behind the curtain is beneficial, imho.  Understanding how a tool works helps to use the tool.  

In our case, knowning about case trees and how clauses are translated to case trees helps understanding complaints from the coverage checker.

The mere existence of this issue shows that there is need to get more information how things work.

**Comment by nad** [comment]
On the other hand, if we include implementation details and later change the implementation, then the manual risks becoming (more) out of date.

**Comment by UlfNorell** [comment]
This is also true for documenting language features. Common practice is to update the documentation when it becomes outdated, rather than not writing documentation.

**Comment by nad** [comment]
That is easy to miss if the documentation contains something that you did not expect it to contain. For instance implementation details.

> In our case, knowning about case trees and how clauses are translated to case trees helps understanding complaints from the coverage checker.

But is there a need to know how these things are stored in the interface files?

**Comment by UlfNorell** [comment]
Clearly there's no need to know how the case trees are stored in the interface file, but no one is suggesting that we document that.

**Comment by nad** [comment]
I don't think there is a need to know that we store case trees, it suffices to know that functions defined by pattern matching are stored in some way.

**Comment by UlfNorell** [comment]
Because if we abandon case trees it will be too much work to update the documentation?

**Comment by nad** [comment]
This particular example doesn't really matter, but in general I'd like it to be easier, not harder, to maintain Agda.

**Comment by L-TChen** [comment]
> This particular example doesn't really matter, but in general I'd like it to be easier, not harder, to maintain Agda.

I totally agree. On the other hand, making a good document also helps the development of Agda accessible to more people and perhaps may attract more people to work on it.

**Comment by nad** [comment]
It might be useful with more documentation of the implementation, but I don't think that should be mixed up with the user manual.

**Comment by L-TChen** [comment]
A document on the implementation sounds a terrific idea! 😉

Perhaps, we can use GitHub's wiki feature (or somewhere suitable) to deal with common questions about the implementation first, including the details of the interface file, how Agda type checks a file (raw text -> concrete syntax -> abstract syntax -> internal syntax), etc. 

IMO, the information discussed here is valuable, and the question should be where, instead of whether, we document this detail.

**Comment by pnlph** [comment]
Thank you for your comments! I will try to sum up everything in an upcoming PR as soon as i can.

Also, i just noticed that when an agda file is renamed, the old .agdai file is kept and a new created. This is the desired behavior, right?

**Comment by nad** [comment]
I don't think we should look for and delete orphan `.agdai` files anywhere in the user's file system.

**Comment by pnlph** [comment]
Yes, I agree, we just could explain roughly how it works so the user can decide.
