### ISSUE TITLE
Don't use lazy Maybe in strict fields

### ISSUE THREAD

**Issue by nad** [agda/agda#4428]
I found several instances of `!(Maybe something)` in `Agda.TypeChecking.Monad.Base`:

https://github.com/agda/agda/blob/f0422f159aedca2e987aba85d22421c2fba2a449/src/full/Agda/TypeChecking/Monad/Base.hs#L177

https://github.com/agda/agda/blob/f0422f159aedca2e987aba85d22421c2fba2a449/src/full/Agda/TypeChecking/Monad/Base.hs#L194

https://github.com/agda/agda/blob/f0422f159aedca2e987aba85d22421c2fba2a449/src/full/Agda/TypeChecking/Monad/Base.hs#L231

https://github.com/agda/agda/blob/f0422f159aedca2e987aba85d22421c2fba2a449/src/full/Agda/TypeChecking/Monad/Base.hs#L293

https://github.com/agda/agda/blob/f0422f159aedca2e987aba85d22421c2fba2a449/src/full/Agda/TypeChecking/Monad/Base.hs#L1807

Perhaps these uses of `Maybe` should be replaced by the strict `Maybe` type from `Data.Strict.Maybe`.

**Comment by andreasabel** [comment]
Yes.  The trouble is that Haskell conceives `Strict.Maybe` as a __absolutely new type totally unrelated to__ `Maybe`.  Thus, it is very inconvenient to use.  
The language solution Haskell offers is not well designed, some strictness polymorphism is missing.

**Comment by nad** [comment]
If we use lenses to access these fields, then perhaps we can use the lazy `Maybe` in the lens interfaces.

**Comment by andreasabel** [comment]
This is exactly how I am implementing it, at least where lenses are already in place.
