### ISSUE TITLE
The new mutual recursion syntax chokes on a minimal induction-recursion

### ISSUE THREAD

**Issue by Soares** [agda/agda#4430]
[These docs](https://agda.readthedocs.io/en/v2.6.0.1/language/mutual-recursion.html) cause me to believe that the following code should work:

```
module IR where

data A : Set
f : A -> Set

data A : Set where
f ()
```

However, this yields:

```
The following names are declared but not accompanied by a
definition: A
```

One hypothesis I had was that this induction-recursion was "too simple", and that agda was getting confused b/c while I tried to declare `A` and `f` mutually-recursively, neither actually mentions the other. Another hypothesis I had was that agda gets confused when you try to mix functions & data, in a way that it wouldn't if I tried to mix only data & data. However, this code:

```
module IR where

data A : Set
data f : A -> Set

data A : Set where
  base : A
  more : (a : A) -> f a -> A

data f : A -> Set where
  keep : ∀ a -> f a
```

Yields:

```
The following names are declared but not accompanied by a
definition: A, f
```

As such, I have no idea how to invoke induction-recursion without resorting to a `mutual` block.

My guess is that this is a bug. If instead it is by design, then I recommend updating the aforementioned docs to note that the old `mutual` syntax is still necessary when using induction-recursion :-)

**Comment by UlfNorell** [comment]
I think the problem is that you have a type signature on the data definitions. Try
```agda
data A where
```

**Comment by Soares** [comment]
Yep! My bad. Might be worth adding a note to the docs saying explicitly that if you say the type again then agda will assume it's a new def'n (which seems reasonable in hindsight but which I didn't understand in advance). Feel free to close, or to leave open & treat as a docs bug, and thanks for the speedy reply :-)

**Comment by andreasabel** [comment]
The docs already alert to this subtlety:

> ... -- Note the absence of ‘where’.

> ... That is, they should have no type signatures, 

If you think it is not explicit enough and want to improve the docs, you are welcome to reopen and submit a PR.
