### ISSUE TITLE
Termination check failed for coinductive record with sized types and eta equality.

### ISSUE THREAD

**Issue by alexarice** [agda/agda#4440]
I am unsure if this is related to eta reduction but the following does not terminate:
```agda
{-# OPTIONS --sized-types --safe #-}

module test where

open import Agda.Builtin.Size
open import Relation.Binary.PropositionalEquality
open import Axiom.Extensionality.Propositional as Ext
open import Level

record Thunk (F : Size → Set) (i : Size) : Set where
 coinductive
 field
  force : (j : Size< i) → F j
{-# ETA Thunk #-}

open Thunk

data Stream' (A : Set) (i : Size) : Set where
 _∷_ : A → Thunk (Stream' A) i → Stream' A i

hd' : {i : Size} {A : Set} → Stream' A i → A
hd' (x ∷ x₁) = x

tl' : {A : Set} → {i : Size} → Stream' A i → (j : Size< i) → Stream' A j
tl' (x ∷ x₁) j = x₁ .force j

record BiSim' {A : Set} {i : Size} (S T : Stream' A i) : Set where
 coinductive
 field
  hdEq' : hd' S ≡ hd' T
  tlEq' : (j : Size< i) → BiSim' (tl' S j) (tl' T j)

open BiSim'


module _ {e : Ext.Extensionality 0ℓ 0ℓ} where

 thunk-equality : {F : Size → Set} {i : Size} → (s t : Thunk F i) → ((j : Size< i) → force s j ≡ force t j) → s ≡ t
 thunk-equality {i = i} s t f = cong (λ x → record { force = x }) (e f)

 bisimToEq : {A : Set} {i : Size} (S T : Stream' A i) → BiSim' S T → S ≡ T
 bisimToEq {A} {i} (s ∷ S) (t ∷ T) b = helper (hdEq' b) (thunk-equality S T lem)
  where
   helper : s ≡ t → S ≡ T → s ∷ S ≡ t ∷ T
   helper refl refl = refl

   lem : (j : Size< i) → force S j ≡ force T j
   lem j = bisimToEq {A} {j} (force S j) (force T j) (tlEq' b j)
```

This gives error
```
/home/alex/university/coinduction/test.agda:41,2-48,65
Termination checking failed for the following functions:
  _.bisimToEq
Problematic calls:
  lem
    (at /home/alex/university/coinduction/test.agda:42,77-80)
  bisimToEq (force S j) (force T j) (tlEq' b j)
    (at /home/alex/university/coinduction/test.agda:48,12-21)
```

I am confused as to why termination checking does not work here as `biSimToEq` is only corecursively called on a strictly smaller size.

**Comment by andreasabel** [comment]
As far as I can tell, Agda is right to slap you on the fingers here, since what you are trying to do here, to define a function of type `BiSim' S T → S ≡ T`, ought not be possible.
Your function would have to eat up the whole infinite derivation of `BiSim` to produce the witness that the streams are equal.  
Als a rule of thump, you cannot recursively eliminate something coinductive into something inductive.  This is not productive.

Closing this, feel free to reopen if you think it is Agda's fault.

**Comment by gallais** [comment]
Eta for coinductive things also seems pretty dodgy.

**Comment by alexarice** [comment]
I agree that what I'm trying to prove seems quite false. I was hoping extensionality might help but I think this is still false. However I feel the error reported by agda isn't correct, or at least isn't in the right place

**Comment by andreasabel** [comment]
Well, Agda reports:
```
Termination checking failed for the following functions:
  _.bisimToEq
```
which is exactly what it should do.  And also, it correctly identifies that the problem stems from the calls `lem` and `bisimToEq`.  
The error messages do not go beyond that.  They do not tell you exactly what is going wrong here.

**Comment by Saizan** [comment]
@alexarice You can get it working like the following, though ETA for Thunk is still a problem wrt normalization.

```agda
{-# OPTIONS --sized-types --safe #-}

module Issue4440 where

open import Agda.Builtin.Size
open import Relation.Binary.PropositionalEquality
open import Axiom.Extensionality.Propositional as Ext
open import Level
open import Agda.Builtin.Sigma

record Thunk (i : Size) (F : Size< i → Set) : Set where
 coinductive
 field
  force : (j : Size< i) → F j
{-# ETA Thunk #-}

open Thunk


data Stream' (A : Set) (i : Size) : Set where
 _∷_ : A → Thunk i (Stream' A) → Stream' A i

hd' : {i : Size} {A : Set} → Stream' A i → A
hd' (x ∷ x₁) = x

tl' : {A : Set} → {i : Size} → Stream' A i → (j : Size< i) → Stream' A j
tl' (x ∷ x₁) j = x₁ .force j

record BiSim' {A : Set} {i : Size} (S T : Stream' A i) : Set where
 coinductive
 field
  hdEq' : hd' S ≡ hd' T
  tlEq' : (j : Size< i) → BiSim' (tl' S j) (tl' T j)

open BiSim'


module _ {e : Ext.Extensionality 0ℓ 0ℓ} where

 thunk-equality : {F : Size → Set} {i : Size} → (s t : Thunk i F) → (Thunk i (\ { j → force s j ≡ force t j })) → s ≡ t
 thunk-equality {i = i} s t f = cong (λ x → record { force = x }) (e \ { j → f .force j })

 bisimToEq : {A : Set} {i : Size} (S T : Stream' A i) → BiSim' S T → S ≡ T
 bisimToEq {A} {i} (s ∷ S) (t ∷ T) b = helper (hdEq' b) (thunk-equality S T lem)
  where
   helper : s ≡ t → S ≡ T → s ∷ S ≡ t ∷ T
   helper refl refl = refl

   lem : Thunk i \ { j → force S j ≡ force T j }
   lem .force j = bisimToEq {A} {j} (force S j) (force T j) (tlEq' b j)
```

**Comment by alexarice** [comment]
I am now very confused, should this be possible or not?
My intuition for how it might work is that while we can't view the entire stream we can view a "bounded above in length" stream which is how I understand the stream indexed by a sized type.

**Comment by andreasabel** [comment]
@Saizan: Andrea, what is the high-level explanation that something like
```
bisimToEq : {A : Set} {i : Size} (S T : Stream' A i) → BiSim' S T → S ≡ T
```
should be definable (outside of `--cubical`)?

**Comment by nad** [comment]
It seems as if the proof makes use of some kind of extensionality assumption.

**Comment by alexarice** [comment]
> 
> 
> It seems as if the proof makes use of some kind of extensionality assumption.

It makes use of function extensionality

**Comment by Saizan** [comment]
@andreasabel  Given extensionality for function types and coinductive records, the rest is well-founded recursion, because the equality of the tails is at a smaller size. 

These principles should make sense in a set model, where `Thunk` being `coinductive` does not affect its semantics (it's not recursive so the greatest fixpoint is just `(j : Size< i) → F j`), and Size for this example could just be the natural numbers.

The higher-level principle is that size quantification can make inductively defined types behave coinductively and vice versa. Then `data` vs. `inductive record` vs. `coinductive record` become only operational distinctions.

Operationally I'm not sure that my version is any more normalizing than @alexarice original version, as it still relies on function definitions to block reduction, specifically in this application: `e \ { j → f .force j }`. My version only makes `lem` a little more robust because of the `.force` projection.

One can replace definitional eta with just propositional eta for `Thunk`  (`thunk-eta` can actually be proven in `--cubical`):

```agda
{-# OPTIONS --sized-types --safe #-}

module Issue4440 where

open import Agda.Builtin.Size
open import Relation.Binary.PropositionalEquality
open import Axiom.Extensionality.Propositional as Ext
open import Level
open import Agda.Builtin.Sigma

record Thunk (i : Size) (F : Size< i → Set) : Set where
 constructor thunk
 coinductive
 field
  force : (j : Size< i) → F j

open Thunk

data Stream' (A : Set) (i : Size) : Set where
 _∷_ : A → Thunk i (Stream' A) → Stream' A i

hd' : {i : Size} {A : Set} → Stream' A i → A
hd' (x ∷ x₁) = x

tl' : {A : Set} → {i : Size} → Stream' A i → (j : Size< i) → Stream' A j
tl' (x ∷ x₁) j = x₁ .force j

record BiSim' {A : Set} {i : Size} (S T : Stream' A i) : Set where
 coinductive
 field
  hdEq' : hd' S ≡ hd' T
  tlEq' : (j : Size< i) → BiSim' (tl' S j) (tl' T j)

module _ {e : Ext.Extensionality 0ℓ 0ℓ}
         (thunk-eta : ∀ {i F} → {x : Thunk i F} → x ≡ thunk (x .force))
     where

 thunk-equality : {F : Size → Set} {i : Size} → (s t : Thunk i F) → (Thunk i (\ { j → force s j ≡ force t j })) → s ≡ t
 thunk-equality {i = i} s t f = trans thunk-eta (trans (cong thunk (e \ { j → f .force j })) (sym thunk-eta))

 bisimToEq : {A : Set} {i : Size} (S T : Stream' A i) → BiSim' S T → S ≡ T
 bisimToEq {A} {i} (s ∷ S) (t ∷ T) b = helper (hdEq' b) (thunk-equality S T lem)
  where
   helper : s ≡ t → S ≡ T → s ∷ S ≡ t ∷ T
   helper refl refl = refl

   lem : Thunk i \ { j → force S j ≡ force T j }
   lem .force j = bisimToEq {A} {j} (force S j) (force T j) (tlEq' b j)
```
