### ISSUE TITLE
Possible empty type of sizes in lambda expression

### ISSUE THREAD

**Issue by alexarice** [agda/agda#4441]
Agda does not seem to like lambda expressions involving sizes.

```agda
{-# OPTIONS --safe --sized-types #-}

module test2 where

open import Agda.Builtin.Size
open import Data.Unit

test : {i : Size} → (j : Size< i) → ⊤
test = λ j → tt

test2 : {i : Size} → (j : Size< i) → ⊤
test2 j = tt
```

`test2` typechecks fine but `test` does not with error
```
Possibly empty type of sizes  Size< i
when checking that the expression λ j → tt has type Size< i → ⊤
```

is test2 not just syntactic sugar for test. I'll admit I don't know why the check for empty size types is necessary but surely test and test2 should be treated the same way?

**Comment by andreasabel** [comment]
Agda is a bit too eager in complaining here, as there is no real problem.  However, not checking satisfyability of size constraints may lead to infinite reduction, consider the example `bad` in https://github.com/agda/agda/issues/1515#issue-99825023.

> is test2 not just syntactic sugar for test. 

In general, no, with regard to termination, arguments cannot always be moved from the lhs to the rhs.  The general idea is that a clause only reduces if the lhs matches.  If you move arguments from the lhs to the rhs, you get more reductions, which might break termination.

In your specific toy example, well, yes, nothing bad would happen.
