### ISSUE TITLE
Dark background highlighting in Emacs

### ISSUE THREAD

**Issue by goose121** [agda/agda#4443]
It seems that `agda-mode`'s faces were not designed for use with a dark background, as they don't have any alternatives defined for dark backgrounds and they don't tend to show up very well. This is closely related to #3321, as inheriting from the default font-lock faces would resolve the issue for many of the problematic faces, but there are also some highlighting faces, among others, that would probably need to be changed manually as they don't have an obvious equivalent in `font-lock`'s faces.

**Comment by L-TChen** [comment]
Have you used the dark theme introduced by https://github.com/agda/agda/pull/3852?

**Comment by goose121** [comment]
Oh, interesting; I'm not sure that I have, my installation must be out of date. Sorry for the inconvenience.
