### ISSUE TITLE
Should the ETA pragma be allowed in safe mode?

### ISSUE THREAD

**Issue by nad** [agda/agda#4450]
@gallais stated that "[Eta for coinductive things also seems pretty dodgy](https://github.com/agda/agda/issues/4440#issuecomment-585963879)". Should the ETA pragma be allowed in safe mode? Currently the two pieces of code below are accepted:
```agda
{-# OPTIONS --safe #-}

record R : Set where
 coinductive
 field
   force : R

{-# ETA R #-}
```
```agda
{-# OPTIONS --safe --sized-types #-}

open import Agda.Builtin.Size

record R (i : Size) : Set where
 coinductive
 field
   force : {j : Size< i} → R j

{-# ETA R #-}
```

**Comment by andreasabel** [comment]
If you try to do the same with an `eta-equality` declaration, you get the error:
```
Agda doesn't like coinductive records with eta-equality.
If you must, use pragma
{-# ETA R #-}
when checking the definition of R
```
Eta-equality for streams is incompatible with decidable definitional equality:  Consider
```agda
foo : Stream -> Stream
foo .head = bar
foo .tail .head = bar
foo .tail .tail = foo

test : foo .tail == foo
test = refl
```
With eta-equality, for testing `foo .tail = foo` it would be sufficient to look that equality of the projections, which leads to an infinite regress.  For instance, this code makes the type-checker loop:
```agda
{-# OPTIONS --safe #-}

open import Agda.Builtin.Equality

record R : Set where
 coinductive
 field
   force : R
open R

{-# ETA R #-}

foo : R
foo .force .force = foo

test : foo .force ≡ foo
test = refl
```
If safety should include the type-checker not looping, then, yes, `ETA` is not safe.  It is anyway a fringe feature, thus, it seems ok to exclude it from `--safe`.

**Comment by andreasabel** [comment]
To implement treating ETA as unsafe, start here:
https://github.com/agda/agda/blob/24929e161b2951beff5cf5ba5a5450e3cc9d2107/src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs#L1326-L1350

**Comment by andreasabel** [comment]
Added a new `Warning`: `SafeFlagEta`.

**Comment by asr** [comment]
I added the label `documented-in-changelog` because the issue was documented in the CHANGELOG (good) and it should not be listed by the `closed-issues-for-milestone` program.
