### ISSUE TITLE
No error highlighting for error warnings?

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#4456]
Working on #4450 I saw that warnings which are reported as errors do not get error highlighting in the file:
https://github.com/agda/agda/blob/bb680eb7e0dd2606289d8bdc33ca916b1bde1a2f/src/full/Agda/Interaction/Highlighting/Generate.hs#L630-L640
Is this intended or by accident?

**Comment by gallais** [comment]
My guess: no one bothered adding a new highlighting style for these.
I guess bright red background could work.

**Comment by andreasabel** [comment]
By default, we could use the `OtherAspect` `Error`, but we could also add a custom `OtherAspect`.  
https://github.com/agda/agda/blob/bb680eb7e0dd2606289d8bdc33ca916b1bde1a2f/src/full/Agda/Interaction/Highlighting/Precise.hs#L110-L124
There is no specific parts of an unsafe pragma to be highlighted specially, this is why the `Error` aspect might be sufficient.

**Comment by andreasabel** [comment]
> I guess bright red background could work.

For now, I settled for "light coral" in emcs light mode, and the `TerminationProblem` style in the dark mode and agda.sty.

> By default, we could use the `OtherAspect` `Error`, but we could also add a custom `OtherAspect`.

Seems to work better with a new aspect `ErrorWarning`, if only the background is changed.
