### ISSUE TITLE
The command agda2-measure-load-time is broken

### ISSUE THREAD

**Issue by nad** [agda/agda#4458]
When I changed the Emacs mode so that one can (in some cases) give a new command before the previous command has completed (ac5fca49d62070895c81b06bb05e6e34da606f1c), I broke `agda2-measure-load-time`. To reproduce the problem:
* Invoke the command `(progn (agda2-restart) (agda2-measure-load-time))`.
* Notice that you quickly get a response like "Load time: 0.02s.", even if type-checking takes a long time.

The problem is that `agda2-measure-load-time` activates the measuring infrastructure (by setting `agda2-measure-data`), but then the backend command initiated by `agda2-restart` completes, and this triggers the printing of the load time.

**Comment by nad** [comment]
One way to fix this problem is to remove `agda2-measure-load-time`. Is anyone using this command?

**Comment by UlfNorell** [comment]
I doubt it. I removed the command for now.
