### ISSUE TITLE
Inconsistent inferred universe in data constructor

### ISSUE THREAD

**Issue by kcsongor** [agda/agda#4461]
The following code is accepted (I tested on `2.6.1-0895178`):

```agda
data M : Set where
  m : (I : _) → (I → M) → M

-- inferred
-- m : (I : Set) → (I → M) → M
```

The code below is adapted from http://www.cs.nott.ac.uk/~psztxa/g53cfr/l20.html/l20.html and implements Russell's paradox, but without type-in-type.

```agda
{-# OPTIONS --safe --without-K #-}
module Bug where

open import Data.Product
open import Data.Empty
open import Relation.Binary.PropositionalEquality

data M : Set where
  m : (I : _) → (I → M) → M


_∈_ : M → M → Set
a ∈ m I f = Σ I (λ i → a ≡ f i)

_∉_ : M → M → Set
a ∉ b = (a ∈ b) → ⊥

R : M
R = m (Σ M (λ a → a ∉ a)) proj₁

lem-1 : ∀ {X} → X ∈ R → X ∉ X
lem-1 ((Y , Y∉Y) , refl) = Y∉Y

lem-2 : ∀ {X} →  X ∉ X → X ∈ R
lem-2 {X} X∉X = (X , X∉X) , refl

lem-3 : R ∉ R
lem-3 R∈R = lem-1 R∈R R∈R

contr : ⊥
contr = lem-3 (lem-2 lem-3)
```

Manually specifying the universe to be `Set` is rejected as expected.

**Comment by UlfNorell** [comment]
Leaves unsolved metas on 2.6.0.1

**Comment by UlfNorell** [comment]
Looks like the problem is here:

https://github.com/agda/agda/blob/172499021ae00f9669e8ce43789d7f5a632c8953/src/full/Agda/TypeChecking/Level.hs#L178-L182

This will give `Max 0 []` for `subLevel k (Max 0 [])` regardless of `k`. In this particular example it results in `Set` being considered a 1-step sub-universe of `Set`.

cc @jespercockx

**Comment by jespercockx** [comment]
I **just** was looking at the same piece of code. I'll push the fix soon.

**Comment by UlfNorell** [comment]
Removing that line triggers a flood of internal errors in the test suite, so I guess it was there for a reason...

**Comment by jespercockx** [comment]
I wouldn't remove the line but just add a condition that `ls` is not empty

**Comment by UlfNorell** [comment]
Right, that makes sense.

**Comment by kcsongor** [comment]
Thank you both for getting to the bottom of this so quickly!

**Comment by jespercockx** [comment]
Thank you for reporting the bug!
