### ISSUE TITLE
Question about building complex record instances with terms inbetween fields

### ISSUE THREAD

**Issue by MirceaS** [agda/agda#4463]
Hi!
I just wanted to pinpoint something that I find quite annoying when working with records in Agda.
I often find that it's useful to define terms in a record before defining additional fields of that record as the definition of those additional fields becomes much concise and simple when using the previously defined terms. However, when building an instance of that record (say via the record {module-with-definitions}), I don't have access to those intermediary terms unless I copy paste them over in my module...
Is there any standard practice to get around this?
Thanks!

**Comment by nad** [comment]
I guess you could put the fields that the defined terms depend on in a separate record type, but that might have other drawbacks.

**Comment by jespercockx** [comment]
This is more of a question for the mailing list or gitter and not an actual issue in Agda, so I'm closing this.
