### ISSUE TITLE
Change the implementation of Ren?

### ISSUE THREAD

**Issue by nad** [agda/agda#4467]
Are the following lists known to always be short?

https://github.com/agda/agda/blob/bf974270b72b13595272d7b54ab5ff503e2c8930/src/full/Agda/Syntax/Abstract.hs#L136-L137

If not, then it might make sense to switch to a different data structure:
https://github.com/agda/agda/blob/bf974270b72b13595272d7b54ab5ff503e2c8930/src/full/Agda/TypeChecking/Monad/Signature.hs#L320
https://github.com/agda/agda/blob/bf974270b72b13595272d7b54ab5ff503e2c8930/src/full/Agda/TypeChecking/Monad/Signature.hs#L364

**Comment by UlfNorell** [comment]
They contain all (public) names from an applied module, so I they can become arbitrarily long. This test case should give you something to experiment with:
```agda
module _ where

module A₀ where
  postulate
    X₁ X₂ X₃ X₄ : Set

module A₁ where
  module B₁ = A₀
  module B₂ = A₀

module A₂ where
  module B₁ = A₁
  module B₂ = A₁

module A₃ where
  module B₁ = A₂
  module B₂ = A₂

module A₄ where
  module B₁ = A₃
  module B₂ = A₃

module A₅ where
  module B₁ = A₄
  module B₂ = A₄

module A₆ where
  module B₁ = A₅
  module B₂ = A₅

module A₇ where
  module B₁ = A₆
  module B₂ = A₆

module A₈ where
  module B₁ = A₇
  module B₂ = A₇
```

**Comment by WolframKahl** [comment]
And if they stay lists, I would, for micro-optimisation, at least internally switch to difference lists, changing 
https://github.com/agda/agda/blob/bf974270b72b13595272d7b54ab5ff503e2c8930/src/full/Agda/TypeChecking/Monad/Signature.hs#L318
to
````haskell
        rename :: QName -> TCM (Ren QName -> Ren QName)
````
etc., returning `(:) x` instead of `[x]`, and `id` instead of `[]`.

Even if they turn into some kind of `Map`, I still would do the same with `Map.insert x` instead of `[x]`.

**Comment by andreasabel** [comment]
@UlfNorell, this used to be `Map a a` but in aa966fc3653d8bbba4beb4a2950bc18e5ed069ea you changed this to `[(a, a)]`.  Why?

**Comment by jespercockx** [comment]
I'm not Ulf, but the commit message says "Fixed by making renamings admit duplicate old names.", so I assume it was because `Map` does not allow duplicate keys, but `[(a, a)]` does. Of course, a more efficient implementation like `Map a (NonEmpty a)` might be more desirable.
