### ISSUE TITLE
The warning machinery does not work correctly when interface files are involved

### ISSUE THREAD

**Issue by nad** [agda/agda#4469]
I ran the test suite with `--compact-regions` turned on, and noted that some test cases related to warnings fail. These problems can be reproduced without using `--compact-regions`:
* Load `test/Succeed/ImportWarningsB.agda` in the Emacs mode (after having removed all related interface files). You get five warnings in the `*All Warnings*` buffer.
* Reload. You still get five warnings.
* Restart Agda and reload. Now you only get two warnings.

The file `test/Succeed/ImportWarnings.agda` can be used to trigger a similar problem.

Note that I plan to turn on `--compact-regions` by default (and remove the flag), which will make this problem worse. Thus I think it makes sense to fix the bug before the release of Agda 2.6.1.

**Comment by nad** [comment]
I also found some similar problems related to compilation:
```
$ cd test/compiler/Simple > /dev/null
$ rm -rf _build/ && agda -c Issue2909-5.agda
Checking Issue2909-5 (…/Issue2909-5.agda).
Compiling Issue2909-5 in …/_build/2.6.1/agda/Issue2909-5.agdai to …/MAlonzo/Code/Issue2909Z45Z5.hs
…/Issue2909-5.agda:8,22-23
"COMPILE GHC as" pragmas are not allowed for the FLAT builtin.
$ rm -rf _build/ && agda Issue2909-5.agda && agda -c Issue2909-5.agda
Checking Issue2909-5 (…/Issue2909-5.agda).
Compiling Issue2909-5 in …/_build/2.6.1/agda/Issue2909-5.agdai to …/MAlonzo/Code/Issue2909Z45Z5.hs
"COMPILE GHC as" pragmas are not allowed for the FLAT builtin.
```
Note that the line `…/Issue2909-5.agda:8,22-23` is only included for the first compilation command.

The file `Issue2909-6.agda` can be used to trigger a similar problem.

**Comment by nad** [comment]
Travis found another problem that might be related: The error message for `test/Fail/SafeFlagPrimTrustMe-2.agda` was changed from
```
SafeFlagPrimTrustMe-2.agda:3,1-33
Importing module Agda.Builtin.TrustMe not using the --safe flag
from a module which does.
when scope checking the declaration
  open import Agda.Builtin.TrustMe
```
to the following text:
```
agda-default-include-path/Agda/Builtin/TrustMe.agda:9,5-60
Cannot postulate unsafePrimTrustMe with safe flag
 when scope checking the declaration
  unsafePrimTrustMe : ∀ {a} {A : Set a} {x y : A} → x ≡ y
```
For some reason this problem is not triggered when I run the test suite locally. I'll disable this test.

**Comment by asr** [comment]
I couldn't reproduce the Travis problem describe [above](https://github.com/agda/agda/issues/4469#issuecomment-590078750) (see successfully build [here](https://travis-ci.org/agda/agda/jobs/654659499). So, I re-enabled the test case.

**Comment by nad** [comment]
@gallais, @fredrikNordvallForsberg: Can one of you take a look at this?

**Comment by fredrikNordvallForsberg** [comment]
Yes, I will do so, and try to get @gallais to help.

**Comment by nad** [comment]
Thanks.

**Comment by nad** [comment]
Your fix addressed the issue in the OP, but not the issue related to the GHC backend, right?

**Comment by nad** [comment]
Those tests also pass now. I'll enable them.

**Comment by nad** [comment]
I had forgotten that I had changed the test cases. The problem remains.

**Comment by fredrikNordvallForsberg** [comment]
For the GHC backend issue, I get the same output for both
```rm -rf _build/ && agda -c Issue2909-5.agda```
and
```rm -rf _build/ && agda Issue2909-5.agda && agda -c Issue2909-5.agda```
after my fix:
```
Checking Issue2909-5 (/home/nfb13227/agda/test/Compiler/simple/Issue2909-5.agda).
Compiling Issue2909-5 in /home/nfb13227/agda/test/Compiler/simple/_build/2.6.1/agda/Issue2909-5.agdai to /home/nfb13227/agda/test/Compiler/simple/MAlonzo/Code/Issue2909Z45Z5.hs
"COMPILE GHC as" pragmas are not allowed for the FLAT builtin.
```
Also note that the message in question actually is a [generic error](https://github.com/agda/agda/blob/master/src/full/Agda/Compiler/MAlonzo/Compiler.hs#L363-L364), not a warning, so I think the disappearing range information probably has some other cause?

**Comment by nad** [comment]
> For the GHC backend issue, I get the same output for both

After my fix of #4316 that's to be expected if you compile Agda using GHC 8.4 or later.

**Comment by fredrikNordvallForsberg** [comment]
I fixed this by setting the range before throwing the error. Note that the range is not the same as before: we now point to the `{-# COMPILE GHC ♭ as flat #-}` pragma, whereas according to the output by @nad above, we were previously pointing to just after the ♭ in `{-# BUILTIN FLAT     ♭  #-}`. I think this is an improvement.

Also I re-enabled the test case. If there is still a difference on GHC < 8.4, apologies, and please disable it again!

**Comment by asr** [comment]
> Also I re-enabled the test case. If there is still a difference on GHC < 8.4, apologies, and please disable it again!

Before merging into `master` you can test your changes on all the supported GHC versions by adding to the commit message the text `complete tests`.
