### ISSUE TITLE
Change the implementation of TopLevelModuleName?

### ISSUE THREAD

**Issue by nad** [agda/agda#4470]
The following map uses lists of strings as keys:

https://github.com/agda/agda/blob/8c21b6be0c98a7c87d0c65ac5c9242967b0e11b7/src/full/Agda/TypeChecking/Serialise/Base.hs#L153-L154

It is used when deserialising `AbsolutePath`s. I wonder if we could speed up deserialisation by, say, adding unique identifiers to `TopLevelModuleName`.

**Comment by andreasabel** [comment]
@nad, you could have thought about it 11 years ago: c92b79969253b3a97391ba28b850c934ea79c298

**Comment by nad** [comment]
Don't you mean 00a9116a9a455554ebb466ca1262e24ff12d3487?

I know that I defined `TopLevelModuleName`, and I know that I chose a representation that was easy to work with rather than one that was efficient. However, I don't plan to work on this right now.

**Comment by nad** [comment]
This has been fixed (e9399a1add3b82ff2fa45b976d39d05d4eccf4ce).
