### ISSUE TITLE
Disable all subtyping by default?

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#4474]
In the light of historic and current issues involving subtyping (e.g. #1579 #2170 #2440 #3986 #4175 #4390 #4401) I am starting to wonder whether it is a good idea to have subtyping enabled by default in Agda. All dependent type theories with subtyping that are know either use coercive subtyping or restrict it to a very specific setting (i.e. cumulativity). On the other hand, Agda now has a notion of material subtyping that is used for several features: irrelevance, erasure, sized types, cumulativity, and cohesion. In particular, it seems that we do not yet fully understand how constraint solving and metavariables in such a setting are supposed to work.

In this light, I would like to discuss whether it is a good idea to have (material) subtyping enabled by default. Maybe it would be better to have a general flag `--no-subtyping` that disables material subtyping across the board? Things like irrelevance and erasure should still function with this option, though it might be necessary to eta-expand some functions by hand. Sized types and cumulativity would obviously not be compatible with this flag.

What do you think? Is this a good idea or do we need a less radical solution?

**Comment by nad** [comment]
I just [asked you](https://github.com/agda/agda/pull/4432#issuecomment-590082315) a similar question.

> In particular, it seems that we do not yet fully understand how constraint solving and metavariables in such a setting are supposed to work.

Your recent pull request (#4432) suggests that we do not know how to implement these things *efficiently*. Are there further problems?

> Things like irrelevance and erasure should still function with this option, though it might be necessary to eta-expand some functions by hand.

Perhaps we could also implement coercive subtyping, but maybe not before 2.6.1 is released. Has anyone considered what coercive subtyping for sized types might look like?

> Maybe it would be better to have a general flag `--no-subtyping` that disables material subtyping across the board?

If material subtyping is broken and we do not know how to fix it, then perhaps users should be forced to ask for it. However, this might break quite a bit of code. If we go down this route, then we should perhaps make it possible to give options in `.agda-lib` files. (Wasn't there an issue for that?)

Should `--material-subtyping` be infective?

I guess `--material-subtyping` should not be available when `--safe` is active.

**Comment by jespercockx** [comment]
> > 
> 
> Your recent pull request (#4432) suggests that we do not know how to implement these things _efficiently_. Are there further problems?

There are no known unknowns AFAICT, but there might be other unknown unknowns (the proof of false that I just posted in #4390 is not a new problem, so it is not inconceivable that other problems with subtyping remain).

> If we go down this route, then we should perhaps make it possible to give options in .agda-lib files. (Wasn't there an issue for that?)

https://github.com/agda/agda/issues/3118

> Should --material-subtyping be infective?

`--no-subtyping` should be coinfective (same as for e.g. `--without-K`), I guess that's equivalent to `--subtyping` being infective?

> I guess --material-subtyping should not be available when --safe is active.

If we enable the check in my PR (https://github.com/agda/agda/pull/4432) only when `--subtyping` is enabled, then there would at least be no known inconsistencies, so one could argue that the flag would only be a matter of performance vs more powerful typing rules.

**Comment by nad** [comment]
OK, then the question is perhaps what the default should be:
* If subtyping is enabled by default, then people might experience slowdowns without knowing why.
* If subtyping is disabled by default, then code might break, but perhaps it would be a little easier to tell what is going on.

**Comment by L-TChen** [comment]
> All dependent type theories with subtyping that are know either use coercive subtyping or restrict it to a very specific setting (i.e. cumulativity).

Is it possible to declare coercions explicitly externally? I am thinking of something similar to Coq's implicit coercion (but hopefully not exactly the same) so users can tickle with these coercions.

**Comment by jespercockx** [comment]
I just realized that turning off subtyping by default would also mean turning off sized types by default, which is something we might not want to do.

> > 
> 
> Is it possible to declare coercions explicitly externally? I am thinking of something similar to Coq's implicit coercion (but hopefully not exactly the same) so users can tickle with these coercions.

No, there's currently no mechanism for coercive subtyping in Agda (except for some code dealing with implicit arguments). Instead, Agda relies on material subtyping, so there is no coercion function even in the internal representation of the term. Another solution to the problems we encounter would thus be to move away from material subtyping and towards coercive subtyping (but, as @nad said, this is not going to happen for 2.6.1).

**Comment by nad** [comment]
I see two options before the release:
* Fix #3118, turn off subtyping by default.
* Leave things as they are.

In either case one of the first items in the release notes should mention the problem and the tradeoffs, your fixes should be pushed, and there should be flags for turning subtyping on and off. Perhaps your fixes can also be optimised.

**Comment by jespercockx** [comment]
A third option: turn off subtyping for irrelevance and erasure by default, but leave subtyping for sized types enabled. The rationale for this change is that sized types are anyway inconsistent at the moment and in dire need of an overhaul, so adding one more inconsistency to the list does not change much (and my fix of #4390 anyway still needs to be extended to sized types).

**Comment by nad** [comment]
I'm turning off subtyping in the files under `src/data/lib/prim`. Perhaps this won't be necessary once your other changes land, but it makes it easier to change the defaults.

**Comment by Saizan** [comment]
`etaLam` probably needs to be updated to not contract in case the modality differs?

**Comment by jespercockx** [comment]
See https://github.com/agda/agda/pull/4432/commits/9837dbc810ecfd3014f0b0aa8c1a136050434b80

**Comment by jespercockx** [comment]
This was actually done in 2.6.1 and documented in the changelog, I only forgot to add the milestone and close this issue.

**Comment by nad** [comment]
> A third option: turn off subtyping for irrelevance and erasure by default, but leave subtyping for sized types enabled. The rationale for this change is that sized types are anyway inconsistent at the moment and in dire need of an overhaul, so adding one more inconsistency to the list does not change much (and my fix of #4390 anyway still needs to be extended to sized types).

Is there an open issue that documents this problem with sized types?

**Comment by Saizan** [comment]
It should be #4483
