### ISSUE TITLE
issues with relations on non-definitionally equal types

### ISSUE THREAD

**Issue by MirceaS** [agda/agda#4477]
Hi!
I've been having a lot of trouble lately trying to deal with types that are propositionally but not trivially equal.
Consider the simplified example:
```agda
open import Level renaming (zero to lzero)
open import Data.Nat
open import Data.Nat.Properties using (+-identityʳ)
open import Relation.Binary
open import Relation.Binary.PropositionalEquality

module unif
  {p r}
  (P : ℕ → Set p)
  (_~_ : ∀ {n} → Rel (P n) r)
  (n : ℕ)
  (x : P n)
  (y : P (n + zero))
  where

-- x~y : x ~ y
-- x~y = ?
```
What would be the best approach to express the fact that `x` and `y` are related by `~`?
I know I can use `subst` to get `x ~ (subst P (+-identityʳ n) y)` as a valid type for `x~y` but for some reason Agda doesn't evaluate the RHS to just `y` when I go ahead and try to actually prove that `x ~ y`.
I can also do something like:
```agda
coerced : (P n) → (P (n + zero)) → Set r
coerced rewrite (+-identityʳ n) = _~_

x~y : coerced x y
x~y = ?
```
which does type check but, as before, when I actually try to prove `x~y` the goal doesn't evaluate to `x ~ y` but instead stays `coerced x y` making proving the fact impossible.
I spent more time on this issue than would be advisable. Any tips would be much appreciated.

**Comment by Saizan** [comment]
`subst P (+-identityʳ n) y` and `coerced x y` will only compute to what you want when `+-identityʳ n` is made to be `refl`.

That could happen either by making `n` to be `0` (e.g. in an induction) or by a `rewrite +-identityʳ n`, in the definition of `x~y`.

I would try the following:

```agda
x~y : coerced x y
x~y rewrite +-identityʳ n = ?
```

If that fails it's going to depend on more details of `P` and `y`.

The documentation on `with` and `rewrite` might also be relevant:

https://agda.readthedocs.io/en/v2.6.0.1/language/with-abstraction.html

**Comment by MirceaS** [comment]
@Saizan 
You're right, that does work and I did try that in my main project but I still had issues. My example didn't properly showcase the issues that I was experiencing.
I managed to build however the following example that recreates the problem: (sorry about the previous bad example)
```agda
open import Level renaming (zero to lzero)
open import Data.Nat
open import Data.Nat.Properties using (+-identityʳ)
open import Relation.Binary
open import Relation.Binary.PropositionalEquality

module test
  {p r}
  (P : ℕ → Set p)
  (_~_ : ∀ {n} → Rel (P n) r)
  (f : ∀ {n} → P n → P (n + zero))
  where

coerced : ∀ {n} → (P n) → (P (n + zero)) → Set r
coerced {n} rewrite (+-identityʳ n) = _~_

-- works with no problems:
x~y : ∀ {n} → (x : P n) → (y : P (n + zero)) → coerced x y
x~y {n} x y rewrite (+-identityʳ n) = ?

-- complains:
x~y′ : ∀ {n} → (x : P n) → coerced x (f x)
x~y′ {n} x rewrite (+-identityʳ n) = ?
```

The issue seems to stem from the fact that `x` occurs twice in the call to `coerced` in the type of `x~y′`.
Do you know if there's an easy solution to this?

EDIT: if I postulate `postulate z : P (n + 0)` and replace `(f x)` by `z` in the definition of `x~y′` Agda still complains so the issue doesn’t seem to be related to the occurrences of `x` in the call to `coerced` which just makes the whole thing so much more puzzling...

EDIT2: If, on the other hand, I leave in `coerced x (f x)` but remove `rewrite (+-identityʳ n)` everything type checks again with no problems:
```
-- no longer complains:
x~y′ : ∀ {n} → (x : P n) → coerced x (f x)
x~y′ {n} x = ?
```
But as mentioned before, `coerced` doesn't simplify. I get why it doesn't simplify to `_~_` but what I don't get is why just adding that rewrite in the definition causes Adga to throw an error. This is very weird.

**Comment by Saizan** [comment]
@MirceaS the problem is that `f` return type makes sure `f x` and `x` do not have the same type: the rewrite tries to abstract `n + zero` into a variable `m` which can then be unified with `n`, however it cannot do that because `f x` won't have type `P m`.

As for suggestions on what to do it probably depends on `f` or `_~_`, you should try the mailing list for advice.

**Comment by nad** [comment]
I have not thought about this very carefully, but one local change that might make things easier is to change the definition of `coerced` to use `subst` instead, so that `coerced` does not get stuck. Note also that `subst` satisfies lots of laws.

**Comment by MirceaS** [comment]
I tried a bunch of things and I managed to reduce the problems to something seemingly simpler, yet I still got stuck....
Now I'm just trying to define a function from a predicate of a "subst'd" `x` to the same element in the predicate over `x`:
```agda
module test where

open import Data.Nat
open import Data.Nat.Properties using (+-identityʳ)
open import Relation.Binary.PropositionalEquality
open import Relation.Binary.HeterogeneousEquality as Het using (_≅_ ; ≡-subst-removable)

postulate P : ℕ → Set
postulate n : ℕ
postulate x′ : P (n + zero)
postulate sel : ∀ {n} → P n → Set

x : P n
x = subst P (+-identityʳ n) x′

-- not working:              (n + zero != lhs of type ℕ)
-- f : sel x → sel x′
-- f y rewrite (+-identityʳ n) = y


-- Heterogeneous Equality approach:

substx≅x : x ≅ x′
substx≅x = ≡-subst-removable P (+-identityʳ n) x′

-- still not working:        (n != n + zero of type ℕ)
-- f : sel x → sel x′
-- f = Het.subst (sel {n + zero}) substx≅x

```
Any ideas of how I can achieve this?...

**Comment by UlfNorell** [comment]
The problem is that `rewrite` cannot rewrite the type of `x'` (since it's a definition and not a bound variable). You can work around it by abstracting over it:

```agda
f y with x′
f y | z rewrite +-identityʳ n = y
```

**Comment by nad** [comment]
I'm not sure exactly what you want to do, but perhaps it makes sense to hide the index. Instead of working with `P n`, you could work with the following type (or `∃ P`):
```agda
record [P] : Set where
  constructor [_]
  field
    {n} : ℕ
    p   : P n
```
