### ISSUE TITLE
Named implicit arguments do not behave the same in anonymous lambdas & definitions

### ISSUE THREAD

**Issue by gallais** [agda/agda#4481]
The following definition is accepted:

```agda
_ : Set → {A : Set} → {B : Set} → Set
_ = λ _ {B = B} {A} → {!!}
```

while the one using a definition is not:

```agda
f : Set → {A : Set} → {B : Set} → Set
f _ {B = B} {A} = ?

-- Cannot eliminate type Set with variable pattern {A} (did you supply
-- too many arguments?)
-- when checking the clause left hand side
-- f _ {B = B} {A}
```

This is particularly annoying when dealing with variables introduced by a
`variable` block: to write robust code, it is much better to explicitly use
the names. This way if the generalisation algorithm changes and variables are
generalised in a different order, we get clean error messages pointing out
exactly the source of the issue.

So I would argue that anonymous lambdas should behave the same as definitions
when the arguments are explicitly named.

Note that a pattern lambda has the right behaviour:

```agda
_ : Set → {A : Set} → {B : Set} → Set
_ = λ { _ {B = B} {A} → {!!} }

-- Cannot eliminate type Set with variable pattern {A} (did you supply
-- too many arguments?)
-- when checking the clause left hand side
-- .extendedlambda0 _ {B = B} {A}
```

**Comment by nad** [comment]
The following code is also accepted:
```agda
_ : Set → {A : Set} → {B : Set} → Set
_ = λ _ {C = B} {A} → {!!}
```
The name seems to be ignored.

**Comment by jespercockx** [comment]
Please do not add non-critical issues to the 2.6.1 milestone as we are (hopefully) getting close to a release now (see https://github.com/agda/agda/issues/4212 for the definition of 'critical')

**Comment by gallais** [comment]
I would argue this is made worse by the introduction of implicit generalisation
but fair enough.

**Comment by andreasabel** [comment]
Up to 2.5.4.2 this was a parse error.  Ulf would object to the label "regression in 2.6.0", but one could argue that throwing a hard error is better behavior than silently ignoring the will of the user.  
It seems like updating the type checker for lambdas was forgotten when parsing named arguments for lambda was enabled in the implementation of #952.

**Comment by andreasabel** [comment]
Before #952, hidden lambdas would always map the current hidden pi, as there was no way to skip some hidden quantifiers and then resume with a hidden quantifier.  This functionality has to be added to fix this issue.  Should succeed:
```agda
_ : Set → {A B : Set} → Set
_ = λ _ {B = B} → Set
```
Note that by ignoring the binder names, Agda accepts the following code which will look like a proof of inconsistency to the user:
```agda
open import Agda.Primitive

data ⊥ : Set where
record ⊤ : Set where

proj2 : ∀ a {A B : Set a} → Set a
proj2 = λ _ {B = B} → B

agdaIsInconsistent : proj2 lzero {⊤} {⊥}
agdaIsInconsistent = _
```

**Comment by andreasabel** [comment]
Looks like this is dead code?
https://github.com/agda/agda/blob/f3a509441da8a2e4db0b71cc4ea7ab1e36b70247/src/full/Agda/TypeChecking/Rules/Term.hs#L1121
(Maybe already at its conception.)
The _domain-free_ named lambdas seem to arrive at the type checker as `DomainFull`.  Looks like #952 has introduced some confusion.

**Comment by UlfNorell** [comment]
>  Ulf would object to the label "regression in 2.6.0", but one could argue that throwing a hard error is better behavior than silently ignoring the will of the user.

No I think it's fine... as long as you are happy to fix it by reintroducing a hard error.

**Comment by gallais** [comment]
Thanks! <3

**Comment by andreasabel** [comment]
> as long as you are happy to fix it by reintroducing a hard error.

Hahaha! :D

I tried to fix it in a progressive way, but did at that point not do extensive testing, hoping for the crowd..

Maybe I should have labeled it instead "progression in 2.6.0".
