### ISSUE TITLE
Unification finds solution with bound variable of wrong size

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#4483]
This is what remains of #4390 in the case of sized types (example by @saizan):
```agda
open import Agda.Builtin.Size
open import Agda.Builtin.Equality

mutual
  X : ∀ i → Size< (↑ i) -> Size< i
  X i j = ?

  testX : {i : Size}{j : Size< i} → X i j ≡ j
  testX = refl
```

**Comment by jespercockx** [comment]
On current `master` the test case above gives me an error:
```
Cannot solve size constraints
[i, j] j < ↑ i |- ↑ ?0 ≤ i
Reason: inconsistent upper bound for 10
when checking that the expression ? has type Size< i
```
Also, I'm not sure how this example can be used to prove false, even if it would be accepted. @Saizan do you know?

**Comment by Saizan** [comment]
You can establish well-founded induction on sizes, and then use `X` to call the induction hypothesis without having to prove more.

**Comment by Saizan** [comment]
I guess now Agda is just preemptively recognizing that `Size< i` might be empty? Just declaring a goal like the following gives you an error

```agda
Y : ∀ i → Size< (↑ i) -> Size< i
Y i j = ?
```

I wonder if there more subtle ways to get around that.

**Comment by jespercockx** [comment]
Since the bad behaviour in this example can no longer be reproduced, I'm closing this issue. (The broader issues with sizes remain open of course.)
