### ISSUE TITLE
Absurd pattern accepts non-empty equality type

### ISSUE THREAD

**Issue by louisswarren** [agda/agda#4484]
Take the following code, in which we take a record type which encapsulates pairs of natural numbers, and we show that these types are all discrete.
```agda
open import Agda.Builtin.Equality
open import Agda.Builtin.Nat renaming (Nat to ℕ)
open import Agda.Builtin.Sigma

ℕ×ℕ : Set
ℕ×ℕ = Σ ℕ λ _ → ℕ

record Cont : Set where
  constructor cont
  field
    value : ℕ×ℕ

data ⊥ : Set where

data Dec (A : Set) : Set where
  yes : A       → Dec A
  no  : (A → ⊥) → Dec A

natEq : (n m : ℕ) → Dec (n ≡ m)
natEq zero    zero    = yes refl
natEq zero    (suc m) = no λ ()
natEq (suc n) zero    = no λ ()
natEq (suc n) (suc m) with natEq n m
...                   | yes refl = yes refl
...                   | no  n≢m  = no  λ { refl → n≢m refl }

pairEq : (a b : ℕ×ℕ) → Dec (a ≡ b)
pairEq (n , i) (m , j) with natEq n m | natEq i j
...                    | yes refl     | yes refl = yes refl
...                    | _            | no  i≢j  = no λ { refl → i≢j refl }
...                    | no  n≢m      | _        = no λ { refl → n≢m refl }


contEq : (x y : Cont) → Dec (x ≡ y)
contEq (cont a) (cont b)
    with natEq (fst a) (fst b) | pairEq a b
... | yes refl                 | yes ()  -- Huh?
... | _                        | no  a≢b = no λ { refl → a≢b refl }
... | no a₀≢b₀                 | _       = no λ { refl → a₀≢b₀ refl }
```

Clearly the latter proof is contrived (and a more typical proof goes through as normal), but it seems that the changes to with-abstraction in 2.6.1 are causing the wrong path to be deemed impossible.

This typechecks. Although `contEq (cont (0 , 0)) (cont (0 , 0))` just normalises to `contEq (cont (0 , 0)) (cont (0 , 0)) | yes refl | yes refl`, compiling the code produces a program that does show that this evaluates to `no _`.

A more detailed example can be found [here](https://gist.github.com/louisswarren/a6ef95e1f4b38b56eec96cec7a006a5e).

I have tested this against release 2.6.0.1.20191219 as well as aa58c68.

**Comment by UlfNorell** [comment]
It's not with-abstraction, but the emptiness checker that's broken:
```agda
open import Agda.Builtin.Equality
open import Agda.Builtin.Nat renaming (Nat to ℕ)
open import Agda.Builtin.Sigma

ℕ×ℕ : Set
ℕ×ℕ = Σ ℕ λ _ → ℕ

data ⊥ : Set where

bad : (a : ℕ×ℕ) (x : ℕ) → (fst a , x) ≡ a → ⊥
bad a x ()

loop : ⊥
loop = bad (0 , 0) 0 refl
```

**Comment by UlfNorell** [comment]
Bisection blames me: 74136a06c
Related issue: #1271

That commit aimed to let Agda discharge cyclic equations on non-eta inductive record constructors, but it looks like it doesn't check the non-eta part properly.

**Comment by UlfNorell** [comment]
Looks like the problem isn't with eta vs non-eta. The example doesn't rely on eta for `Σ`. I think the problem is that `fst a` (internally `a .fst`) counts as a strongly rigid occurrence of `a`.
