### ISSUE TITLE
Bisection instructions for test suite breakages?

### ISSUE THREAD

**Issue by jrp2014** [agda/agda#4490]
The HACKING.md document covers how to bisect stand-alone .agda files.  It would be helpful to include a worked example of how to bisect when a particular test or two break.  It should be trivial, but various tests have dependencies on, eg, Common, that mean that using the instructions given you can't run individual tests or do what you know you really want to do which is bisect running `make test` but can't because certain scripts expect to be run from the home of the repo, rather than a sandbox.

**Comment by gallais** [comment]
Has this been answered? If so, it would be nice to document the answer.

**Comment by jrp2014** [comment]
I just used the vanilla `git bisect`, with a run line of `git bisect run sh -c '(make && make test)'`.  This runs all the tests, which is painful, as some of them don't work with cabal -- the golden values are a bit out on the interaction tests, eg.  Maybe `make quicktest` would be adequate in some cases.

**Comment by andreasabel** [comment]
I suppose one could use `agda-bisect` with a script like https://github.com/agda/agda/blob/c6401a63e84caa495d74f4a5696b4628c306d5dc/test/interaction/Issue2174.sh
@nad, maybe you have a better idea?

One problem with such an approach is that `agda --interaction` does not report errors as system exit codes.  A suitable option that makes `agda` exit on the first interaction error would make bisection easier in some cases.

**Comment by nad** [comment]
I've used [`RunAgda.hs`](https://github.com/agda/agda/blob/87ea144139326ba922f9c19ad96f52a57944f1fe/test/interaction/RunAgda.hs) for this kind of thing. Here is one example that I had lying around (related to #4959):
```haskell
#!/usr/bin/env runhaskell

{-# LANGUAGE RecordWildCards #-}

import Data.List
import System.Directory
import System.Exit

import RunAgda

topLevel     = "Issue4959.agda"
importedName = "Issue4959-2"
imported     = importedName ++ ".agda"

main :: IO ()
main = runAgda [ "--ignore-interfaces"
               ] $ \(AgdaCommands { .. }) -> do

  -- Discard the first prompt.
  echoUntilPrompt

  -- Set up and load the imported file.
  writeFile imported "-- 0"
  loadAndEcho imported

  -- Edit and load the imported file.
  writeFile imported "-- 1"
  loadAndEcho imported

  -- Load the top-level module.
  output <- loadAndEcho topLevel

  -- Clean up.
  removeFile imported

  -- Check the output.
  if ("Checking " ++ importedName) `isInfixOf` unlines output
  then exitFailure
  else exitSuccess
```
(The file `Issue4959.agda` contains the following line: `open import Issue4959-2`.)

**Comment by jespercockx** [comment]
I'm assuming that the suggested workaround is good enough, feel free to reopen if it is not.
