### ISSUE TITLE
Compilation speedup?

### ISSUE THREAD

**Issue by jrp2014** [agda/agda#4492]
Is there any reason not to speed up compilation as below? (It doesn't help that much, but it's better than nothing.)

```
diff --git a/Makefile b/Makefile
index cb9f1b2aa..52b673a99 100644
--- a/Makefile
+++ b/Makefile
@@ -60,7 +60,7 @@ STACK_INSTALL           = $(STACK_INSTALL_HELPER) \
 # The following options are used in several invocations of cabal
 # install/configure below. They are always the last options given to
 # the command.
-GHC_OPTS           = "+RTS -M3G -RTS"
+GHC_OPTS           = "-j4 +RTS -M3G -RTS"
 CABAL_INSTALL_OPTS = -fenable-cluster-counting --ghc-options=$(GHC_OPTS) $(CABAL_OPTS)
 STACK_INSTALL_OPTS = --flag Agda:enable-cluster-counting --ghc-options $(GHC_OPTS) $(STACK_OPTS)
```

For syntax checking only, I suppose that there is no need for a `Makefile` entry, and `cabal repl` will do, although it is also possible to compile with `-fno-code` for that, and running Agda from the `repl` seems to be undocumented.

**Comment by L-TChen** [comment]
Give that the `Makefile` is used in different configurations, maybe `-j` is better.

I remember that there was an issue with Travis CI which failed to report the right number of processors. If it is still the case, `Makefile` needs to set the number manually by checking the environment variable `TRAVIS=true`.

Otherwise, I don't see why not.

**Comment by gallais** [comment]
`~/.cabal/config` allows you to specify how many `jobs` to run in parallel and
then that number (specific to your machine) is used whenever you build something.
Is there nothing equivalent for stack?

**Comment by asr** [comment]
In `~/.cabal/config` I use `jobs: 1` because https://github.com/haskell/cabal/issues/1554#issuecomment-33036734.

**Comment by L-TChen** [comment]
`GHC_OPTS` is used for both `stack` and `cabal in the `Makefile`. If it shows any improvement, should this be turned on by default anyway? 

As for the option for stack, it is also called `jobs`.

**Comment by nad** [comment]
I don't think we should change the makefile, because different users may have different preferences (and one person may even use different settings in different situations).

**Comment by jrp2014** [comment]
One thing that it would be helpful to do for the cabal case anyway is document the precedence between the various ghc compilation settings.  I have been bitten a couple of times with different cabal config settings on different machines.  In this case we also have settings from the Makefile, which can themselves be overridden, to add to the mix.

**Comment by jrp2014** [comment]
There are a couple of different case:

* Do we want cabal to run several different ghc jobs in parallel (as you typically do when building a library and its dependencies from package).  Here the `.cabal/config` `jobs` setting can be tuned to taste, with parallel builds usually enabled by default, although it doesn't seem to have much effect when building Agda.

* Do we want ghc itself to use a multi-core processor?  Here there is a `-j` options that works with `ghc-make`, and so doesn't really help with the current build approach.  There are a few other flags related to configuration of the heap, but there seem to be no universal recommendations on their use.

So I suspect that we are stuck with 30m builds, even in the era of multi-core processors

**Comment by nad** [comment]
> * Do we want ghc itself to use a multi-core processor?  Here there is a `-j` options that works with `ghc-make`, and so doesn't really help with the current build approach.

You can put the following lines in your Cabal configuration file:
```
program-default-options
  ghc-options: -j7
```

**Comment by andreasabel** [comment]
While developing, I invoke `make quicker-install-bin` which has acceptable compilation time.  The slow compilation is however needed to run the `std-lib-test` in reasonable time.

**Comment by L-TChen** [comment]
Given the discussion above, the proposal is unlikely to adopt. So I am closing it. Feel free to reopen it if needed.
