### ISSUE TITLE
Generate postfix copatterns

### ISSUE THREAD

**Issue by laMudri** [agda/agda#4493]
As far as I'm aware, while agda2-mode's automatic case-splitting will generate copatterns, it will only generate prefix projections, like the following.

```agda
open import Data.Nat
open import Data.Product

my-pair : ℕ × ℕ
proj₁ my-pair = {!!}
proj₂ my-pair = {!!}
```

There is no way to instead generate the following.

```agda
my-pair : ℕ × ℕ
my-pair .proj₁ = {!!}
my-pair .proj₂ = {!!}
```

This requires manual editing of the LHSes, but it would be nice if it didn't.

There are a couple of ways I can think of making this possible:

* In place of the name of the variable to split on, accept `.` (mnemonic: postfix projections begin with a `.`).
* Similar to `--no-unicode`, have an option `--postfix-copatterns`.

**Comment by guillaumebrunerie** [comment]
This option already exists and is called `--postfix-projections`
