### ISSUE TITLE
GitHub workflow `stack build` failure on Windows

### ISSUE THREAD

**Issue by asr** [agda/agda#4501]
The GitHub workflow `stack build` is [failing](https://github.com/agda/agda/actions?query=workflow%3A%22stack+build%22) on Windows with the error:

```
Install text-icu 58.2-3
Run wget -q http://repo.msys2.org/mingw/x86_64/${ICU_FILE}
##[error]Process completed with exit code 4.
```

Any ideas?

**Comment by UlfNorell** [comment]
The server seems to be down.

Could try a mirror temporarily: `http://mirror.yandex.ru/mirrors/msys2/msys/x86_64/`

**Comment by L-TChen** [comment]
It is odd that `msys2` does not provide the package `text-icu` anymore as I couldn't find it on the package website. Maybe it is just a temporary issue.

**Comment by UlfNorell** [comment]
Here: https://packages.msys2.org/package/icu?repo=msys&variant=x86_64

**Comment by L-TChen** [comment]
aha, no wonder I couldn't find it. I thought it was called `text-icu`...

**Comment by jrp2014** [comment]
.. and it's a different version from

**Comment by jrp2014** [comment]
This still seems to be broken. On which platforms is icu required?

**Comment by UlfNorell** [comment]
`icu` is required on all platforms when compiling with `-fenable-cluster-counting`. This flag makes the latex (and html?) backend count compound unicode characters correctly for layout purposes. You can compile and use Agda without it though.

**Comment by nad** [comment]
Not HTML, only LaTeX.

**Comment by asr** [comment]
The installation of `text-icu` is working again.
