### ISSUE TITLE
Lack of unicode support in locale may result in uncaught `IOException`

### ISSUE THREAD

**Issue by ajrouvoet** [agda/agda#4506]
I'm experiencing some type-checking performance issues (2.6.0.1, still present on the 2.6.1 release branch) that are hard to debug.

Running with the new -vprofile.definitions:10 reveals a mysterious note about <stdout> and 'commitBuffer', with a large portion of the total time missing:

```
Total                                                                             410,437ms 
Miscellaneous                                                                      90,003ms 
JVM.Defaults.Syntax.Bytecode.label                                                243,552ms 
JVM.Defaults.Syntax.Bytecode.<stdout>: commitBuffer: invalid argument (invalid character)

```

This seems to be at least a bug with the new profile flags? 

I think that the large amount of time used by type-checking here is (mostly) due to instance search.
Are there flags that help me get some more insight into how much time was spent *in this module/definition* on instance search?

**Comment by nad** [comment]
Agda uses the current locale settings for output (or something similar on Windows). I suspect that you can fix the output by switching to a locale with full Unicode support.

We get similar reports now and then. I wonder if we could catch the error and give a better error message.

**Comment by nad** [comment]
> I wonder if we could catch the error and give a better error message.

One can trigger the error message above in the following way (at least on my machine):
```
$ cat Test.hs
main = putStrLn "∀"
$ ghc --make Test.hs
[1 of 1] Compiling Main             ( Test.hs, Test.o )
Linking Test ...
$ LC_CTYPE=C ./Test
Test: <stdout>: commitBuffer: invalid argument (invalid character)
```

The error can be caught in a somewhat imprecise way:
```
$ cat Test.hs
{-# LANGUAGE ScopedTypeVariables #-}

import Data.List
import Control.Exception

main =
  putStrLn "∀" `catch` \(e :: IOException) ->
    let s = show e in
    if "invalid argument (invalid character)" `isSuffixOf` s
    then putStr $ s ++ "\n" ++ message
    else throw e

message = unlines
  [ ""
  , "This error may be due to the use of a locale or code page that does not"
  , "support some character used in the program being type-checked."
  , ""
  , "If you are using a Unix-like system, try <something>."
  , ""
  , "If you are using Windows, try <something else>."
  ]
$ ghc --make Test.hs
[1 of 1] Compiling Main             ( Test.hs, Test.o )
Linking Test ...
$ LC_CTYPE=C ./Test
<stdout>: commitBuffer: invalid argument (invalid character)

This error may be due to the use of a locale or code page that does not
support some character used in the program being type-checked.

If you are using a Unix-like system, try <something>.

If you are using Windows, try <something else>.
```

An alternative would be to use a [text encoding](https://hackage.haskell.org/package/base-4.12.0.0/docs/System-IO.html#v:mkTextEncoding) that drops all code points that trigger this problem. However, I think this might confuse users. An error message has the advantage that you know that something is wrong.

**Comment by nad** [comment]
Someone (the Reddit user Reddiberto) wrote a [Reddit post](https://www.reddit.com/r/agda/comments/rul1w5/where_can_i_look_for_help/) about a problem with a similar error message. I think we should "fix" this problem now. Do you think we should use the hack with the long error message, or the hack with dropped code points?

**Comment by andreasabel** [comment]
> Do you think we should use the hack with the long error message, or the hack with dropped code points?

Simply dropping code points does not sound like a good idea, it is rather hard to foresee what could go wrong...
I'd prefer the hack with parsing the error message.

**Comment by nad** [comment]
I tried to construct a test case for this problem, and noticed that Agda sometimes truncates its output:
```
$ cat Issue4506.agda
_ : Set
_ = Set
$ agda Issue4506.agda
Checking Issue4506 ([…]/Issue4506.agda).
[…]/Issue4506.agda:2,5-8
Set₁ != Set
when checking that the expression Set has type Set
$ LC_CTYPE=C agda Issue4506.agda
Checking Issue4506 ([…]/Issue4506.agda).
[…]/Issue4506.agda:2,5-8
Set$
```
I think that if an exception is encountered when Agda tries to print an error message, then this exception is ignored:

https://github.com/agda/agda/blob/a0b3eea0c19c47ffbe2be525316311f5795d760d/src/full/Agda/Main.hs#L253-L267

**Comment by andreasabel** [comment]
If I display some document in a web browser with the wrong text encoding, it is displayed as garbage, but it is displayed. Garbage in, garbage out.
Is there a similar mechanism available in Haskell?  
Some printer that does not whine about illegal characters?

**Comment by nad** [comment]
> I tried to construct a test case for this problem, and noticed that Agda sometimes truncates its output:

Apparently I also noticed this in [2018](https://github.com/agda/agda/issues/2922#issuecomment-360504242).

> Is there a similar mechanism available in Haskell?
> Some printer that does not whine about illegal characters?

Perhaps you could use `//TRANSLIT` instead of `//IGNORE` when [selecting](https://hackage.haskell.org/package/base-4.12.0.0/docs/System-IO.html#v:mkTextEncoding) the text encoding. I have not tested the following code, but it might work:
```haskell
mkTextEncoding (show localeEncoding ++ "//TRANSLIT")
```

**Comment by nad** [comment]
Do the following error messages seem reasonable?
```
$ cat Bug.agda
_ : Set
_ = Set
$ LC_CTYPE=C agda Bug.agda
Checking Bug ([…]/Bug.agda).
[…]/Bug.agda:2,5-8
Set

Error when handling error:
  <stdout>: commitBuffer: invalid argument (invalid character)

This error may be due to the use of a locale or code page that does not
support some character used in the program being type-checked.

If you are using Windows, try switching to a different code page (for
instance by running the command 'CHCP 65001').

If you are using a Unix-like system, try using a different locale. The
installed locales are perhaps printed by the command 'locale -a'. If you
have a UTF-8 locale installed (for instance sv_SE.utf8), then you can
perhaps make Agda use this locale by running something like
'LC_ALL=sv_SE.utf-8 agda <...>'.
```
```
$ cat Bug.agda
{-# OPTIONS -vtc.decl:5 #-}

A₁ : Set₁
A₁ = Set
$ LC_CTYPE=C agda Bug.agda
Checking Bug ([…]/Bug.agda).
Checking A[…]/Bug.agda:4,1-9
<stdout>: commitBuffer: invalid argument (invalid character)

This error may be due to the use of a locale or code page that does not
support some character used in the program being type-checked.

If you are using Windows, try switching to a different code page (for
instance by running the command 'CHCP 65001').

If you are using a Unix-like system, try using a different locale. The
installed locales are perhaps printed by the command 'locale -a'. If you
have a UTF-8 locale installed (for instance sv_SE.utf8), then you can
perhaps make Agda use this locale by running something like
'LC_ALL=sv_SE.utf-8 agda <...>'.
```
I'm not sure if the advice given for Windows is correct. I seem to recall reading somewhere that it might not suffice to change the code page, one should perhaps also change the locale (or something like that).

I have not added any test cases to the test suite.

**Comment by JacquesCarette** [comment]
I like those error messages.

When encountering a similar problem in my Drasil project on Windows (which is written in Haskell), the 'CHCP 65001' was enough to fix locale-related issues regarding printing on the console.

**Comment by nad** [comment]
I tried the `//TRANSLIT` approach as well, and got the following outputs for the two examples above:
```
Checking Bug ([…]/Bug.agda).
[…]/Bug.agda:2,5-8
Set? != Set
when checking that the expression Set has type Set
```
```
Checking Bug ([…]/Bug.agda).
Checking A?.
Checked A?.
```
If you get this output, then you might understand that something is wrong, but it might not be so easy to figure out how to fix it. I think I'll add a flag that enables this approach, and mention it in the long error message.

**Comment by nad** [comment]
I added the option `--transliterate`. I thought about activating this option in the calls to Agda in `Setup.hs`, but those calls should not fail, and they use `-v0`, so I decided not to do this.

**Comment by asr** [comment]
I removed a trailing whitespace in the title.
