### ISSUE TITLE
Module names restrictions

### ISSUE THREAD

**Issue by pnlph** [agda/agda#4512]
Are there any restrictions on module names?

I tried to create a file 20200314.agda with the content:
```
module 20200314 where
```
but i get a parse error when loading the file.

When i prepend a letter eg `K20200314.agda` it works:
```
module K20200314 where
```

**Comment by sattlerc** [comment]
The string `20200314` is lexed as an integer literal rather than an identifier. As should be expected, you cannot use integer literals for identifiers in general, as you can see by trying to declare '123 : Set'.
