### ISSUE TITLE
Missing GitHub workflow: Installation using Windows and Cabal

### ISSUE THREAD

**Issue by asr** [agda/agda#4513]
@L-TChen added  the GitHub workflow [cabal.yml](https://github.com/agda/agda/blob/fed2ee160bf899de1f56add611396781ff78e8e0/.github/workflows/cabal.yml) which test the installation on Linux using Cabal. This workflow should also test the installation on Windows using Cabal.

**Comment by L-TChen** [comment]
I would love to do this myself (since the additional maintenance burden to me is low), but I do not have a Windows environment to figure out the details. 

Can someone using Windows help?

**Comment by EdNutting** [comment]
I'll have a look

**Comment by EdNutting** [comment]
@asr @L-TChen Out of interest, given there is a `stack` build for Windows, why do we want a `cabal` CI test too? 

Seems like a waste of time and effort. As a Windows user, I stick to `stack` because `cabal` on Windows is even more of a nightmare than it is on Linux and `stack` is a solid wrapper for it. `stack` also uses `cabal` under the hood, so it seems pointless to duplicate the test? Unless there's something I'm missing.

**Comment by asr** [comment]
AFAIK, `stack` doesn't use `cabal-install` under the hood but the `Cabal` library. In addition, no every one uses `stack` including the majority of Agda developers.

**Comment by EdNutting** [comment]
It would be interesting to know first which Agda developers are using Windows - that's presumably already a small subset of the community? And of those, which are using Cabal vs Stack?

**Comment by L-TChen** [comment]
It is actually the right time to ask this question during AIM so that we can prepare the development environment better.

**Comment by JacquesCarette** [comment]
Do you mean developers who write in Haskell (and thus develop Agda-the-system), or developers who write in Agda itself?  I guess you mean the first?

BTW, I routinely use Mac and Windows and Linux. [I use cygwin on Windows, to keep the insanity to a reasonable level].  But I've got my hands full with doing Adga library work, I doubt I'll also dive in to the Haskell parts (even though one of my other projects is a large Haskell code base).

**Comment by EdNutting** [comment]
> Do you mean developers who write in Haskell (and thus develop Agda-the-system), or developers who write in Agda itself?

Good question. This kind of testing is going to impact both developers and users of the Agda system, since it relates to whether installing and running Agda works on Windows. It would be good to know how relevant it is to both groups.

**Comment by EdNutting** [comment]
@L-TChen Would you like to raise the question on the Slack?

**Comment by asr** [comment]
I remembered we have a GitHub workflow for testing the installation of Agda in Windows with `stack`. What is missing is the installation with `cabal-install`.

**Comment by EdNutting** [comment]
@asr @L-TChen This is now implemented - see PR #4694

**Comment by nad** [comment]
Unless I'm mistaken @UlfNorell and @andreasabel use MacOS, while @jespercockx and I use Linux.

**Comment by asr** [comment]
The workflow is failing because https://github.com/agda/agda/issues/4543, so I'll comment out it until GHC 8.10.2 is released.

**Comment by EdNutting** [comment]
Odd that it was passing on the PR when I submitted it!

**Comment by asr** [comment]
IIRC, you had the same behaviour in the first version of the PR. The issue is not completely deterministic, but it was fixed in GHC master and will'be fixed in GHC 8.10.2.

**Comment by asr** [comment]
The workflow is failing because https://github.com/agda/agda/issues/4543, so we need to wait GHC 8.10.3.

**Comment by L-TChen** [comment]
For the record, the current workaround with `stack` is to run the build command twice if it fails to compile. Compiling with 8.10.3 on Windows works fine with the option `-O0`, and it should also work without this option if `cabal build` is executed twice.
