### ISSUE TITLE
Confusing error message if missing import

### ISSUE THREAD

**Issue by strangeglyph** [agda/agda#4518]
Currently when missing the definition of some datatype constructor (e.g. the missing import of `Data.Sum` below), the error message does not mention this at all. Instead, it refers to some vague parse-related error.

```agda
open import Data.Nat
open import Data.Nat.Properties

min : ℕ -> ℕ -> ℕ
min a b with ≤-total a b
...     | inj₁ _ = a
...     | inj₂ _ = b
```

```
Could not parse the left-hand side min a b | inj₁ _
Operators used in this grammar:
  None
when scope checking the left-hand side min a b | inj₁ _ in the definition of min
```

It may be worth to add a note that `inj₁` is unknown to direct the user in the right direction.

**Comment by andreasabel** [comment]
Yeah, the error message given by the operator parser is leaving the user clueless.  
I think the crux is that the operator parser tries to construct a pattern directly.  Maybe a more robust approach would be to first construct an expression (variable inj1 applied to underscore) and then try to interpret it as pattern.  Then, an error could be given that the constructed expression isn't a pattern.

**Comment by andreasabel** [comment]
Actually, I found a way to report more information to the user without changing anything in the structure of the operator parser.

The new error will tell you that Agda could not interpret expression `inj₁ _`.  This might nudge you in the direction to check the status of `inj₁`.

**Comment by andreasabel** [comment]
> (e.g. the missing import of `Data.Sum` below), the error message does not mention this at all.

Agda does not know anything about the name `inj₁`, thus interprets it as a pattern variable.  Agda cannot know that you intended to import some module that makes `inj₁` be defined as a constructor.

There is also the question of library design, of course: If a library defines a function such as `≤-total` that returns something in a data type (here: the sum type), should it also export the data type itself and the constructors of that data type?  The library designers have decided against such cumulative exports.  Whether this make sense or not, is another question, there are arguments for and against.  Cumulative exports give you "batteries included", but may quickly pollute your name space, requiring you to switch to explicitly import the names you want.  And then, nothing is gained by cumulative exports.

**Comment by nad** [comment]
> Agda does not know anything about the name `inj₁`, thus interprets it as a pattern variable. Agda cannot know that you intended to import some module that makes `inj₁` be defined as a constructor.

In some cases Agda gives you more information:
```agda
open import Data.Bool using (Bool)

id : Bool → Bool
id true  = true
id false = false
```
```
The pattern variable true has the same name as the constructor
Bool.true
when checking the clause left hand side
id true
```

**Comment by andreasabel** [comment]
> In some cases Agda gives you more information:

Yes, but this information does not come from the operator parser, but is merely an afterthought, after Agda has "understood" the patterns (even not in the sense the user intended).  

The ideal Agda, which receives millions of sponsoring from Amazon, Facebook, and Google, will have a huge AI that creates likely suggestions what the user meant to write but didn't.  :D
