### ISSUE TITLE
Massive increase in memory required to install Agda 2.6.1

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda#4521]
When I installed both Agda 2.6.1 release candidate 2 and the official Agda 2.6.1 it maxed out the memory on my 8Gb laptop. I did eventually manage to install it after 3 hours, as the thrashing didn't completely halt progress. In contrast Agda 2.6.1 release candidate 1 installed fine while I had a ton of other processes running. I vaguely remember some discussion about GHC options which were added recently?

GHC version 8.0.2.

**Comment by andreasabel** [comment]
See the discussion starting at https://github.com/agda/agda/issues/4324#issuecomment-599173653 about GHC going into thrashing.

**Comment by nad** [comment]
Yes, I think we should have addressed this problem before the release.

> In contrast Agda 2.6.1 release candidate 1 installed fine

Can you verify that this is the case? If it is, then you could perhaps use bisection to find some kind of problem.

**Comment by asr** [comment]
I limited the memory to 4.5 GB by running

```
$ ulimit -Sd 4718592
```

After installing all the required libraries, I got the following error using [Agda 2.6.1 RC2](https://github.com/agda/agda/releases/tag/v2.6.0.1.20200307):

```
$ cabal v1-install --ghc-options="+RTS -M3G -RTS" --force-reinstalls
...
[364 of 369] Compiling Agda.Interaction.EmacsTop ( src/full/Agda/Interaction/EmacsTop.hs, dist/build/Agda/Interaction/EmacsTop.o )
ghc: internal error: Unable to commit 1048576 bytes of memory
```

I couldn't reproduce the error using [Agda 2.6.1 RC1](https://github.com/agda/agda/releases/tag/v2.6.0.1.20191219).

**Comment by nad** [comment]
It is not surprising that RC2 requires a little more memory than RC1. Can you test again using `-M3.2G` or something like that?

**Comment by WolframKahl** [comment]
And try to measure/estimate the non-heap memory GHC uses so that your `ulimit` does not bite before the heap space is exhausted.

(Perhaps also add `+RTS -S -RTS` to all `--ghc-options` so that people get a better idea of the resource picture even for succeeding runs.)

**Comment by andreasabel** [comment]
> It is not surprising that RC2 requires a little more memory than RC1. 

Is it just a drop that makes the bucket overflow or is there a significant increase for one particular change?

**Comment by nad** [comment]
> Is it just a drop that makes the bucket overflow or is there a significant increase for one particular change?

I don't know. My guess is that the main problem is the use of `-fexpose-all-unfoldings` and/or `-fspecialise-aggressively` (#3589).

I tested that I can build Agda from scratch with `-M3.2G` on my 32-bit setup. (This took about half an hour with all dependencies already installed and `-j3`.)

**Comment by nad** [comment]
> I tested that I can build Agda from scratch with `-M3.2G` on my 32-bit setup. (This took about half an hour with all dependencies already installed and `-j3`.)

However, when I used `-M3.5G`, then GHC ran out of memory. (In both cases I tested Agda 2.6.2-b1ecc72.)

**Comment by WolframKahl** [comment]
> However, when I used `-M3.5G`, then GHC ran out of memory.

This is interesting; was it running out of heap? (What was the error message?)

In a 32-bit setup, only 4G of memory are addressable by any single process, and on a true 32bit machine, at most 4G of memory are available.

Also, the 32-bit setup should require less heap than true 64bit setup, so if Agda builds with `-M3.2G` on 64-bit machines, I would try around `-M2G -S` on a 32bit setup.

**Comment by nad** [comment]
> I tested that I can build Agda from scratch with `-M3.2G` on my 32-bit setup. (This took about half an hour with all dependencies already installed and `-j3`.)

I tried it again later, and then GHC ran out of memory (`ghc: out of memory (requested 1048576 bytes)`).

> Also, the 32-bit setup should require less heap than true 64bit setup, so if Agda builds with `-M3.2G` on 64-bit machines, I would try around `-M2G -S` on a 32bit setup.

I would prefer if `make install` worked nicely on both kinds of systems. Is there a simple way (that works on all major platforms) to determine the number of bits?

**Comment by WolframKahl** [comment]
> I tried it again later, and then GHC ran out of memory (`ghc: out of memory (requested 1048576 bytes)`).

This means that the overall memory usage expanded beyond the available (4G) of memory; only heap settings that fit into memory make sense, because a trashing Agda process will require an unusual amount of patience.

> > Also, the 32-bit setup should require less heap than true 64bit setup, so if Agda builds with `-M3.2G` on 64-bit machines, I would try around `-M2G -S` on a 32bit setup.
> 
> I would prefer if `make install` worked nicely on both kinds of systems. Is there a simple way (that works on all major platforms) to determine the number of bits?

`arch` and `uname -m` might come close.

I am not sure that `getconf LONG_BIT` (POSIX) will pick up all kinds of 32-bit processes running on a 64bit kernel.

I dimly remember from my PowerPC days (9+ years ago, running 32bit processes on 64bit kernel) that there was something else, but cannot find it right now.

**Comment by nad** [comment]
> This means that the overall memory usage expanded beyond the available (4G) of memory; only heap settings that fit into memory make sense, because a trashing Agda process will require an unusual amount of patience.

Agda? Do you mean GHC?

**Comment by WolframKahl** [comment]
Yes, sorry! A trashing GHC might possibly (due to probably more locality) be slightly better than a trashing Agda, but still...

**Comment by andreasabel** [comment]
I looks like the compile time for Agda on travis has deteriorated from 30 min to 60 min:
- 30min: https://travis-ci.org/github/agda/agda/jobs/661979363
- 60min: https://travis-ci.org/github/agda/agda/jobs/664774547

30 min is the ordinary build time (from scratch) with vanilla contemporary hardware.

However, here is a very recent build in 35 min: https://travis-ci.org/github/agda/agda/jobs/664379813

**Comment by L-TChen** [comment]
A more recent build from scratch is finished in 30min https://travis-ci.org/github/agda/agda/jobs/671254264. Why...?

**Comment by chirsz-ever** [comment]
`cabal install Agda` ran out of my memory. The installation happend on a 64bit PC with Linux Mint 19.2 and 4GiB memory. The last log:
![图片](https://user-images.githubusercontent.com/31474766/80083095-cdea8780-8587-11ea-8789-7bbcbd0e9577.png)
This error did not stop the compliation but kept on expanding memory, if I don't kill the ghc process.

---
update: build successfully with `cabal install Agda --ghc-options="+RTS -M3G -RTS -j" -j`

**Comment by nad** [comment]
The build often runs out of memory on my system. However, `-M2G` seems to work fine.

> I am not sure that `getconf LONG_BIT` (POSIX) will pick up all kinds of 32-bit processes running on a 64bit kernel.

This command returns `32` on my system. Can someone with a 64-bit system test this?

**Comment by nad** [comment]
I found a better method (if we assume that the target word size matches the word size used by GHC):
```
ghc --info | grep 'target word size'
```

**Comment by nad** [comment]
I tried to remove `-fexpose-all-unfoldings` and `-fspecialise-aggressively` from the Cabal file. This made compilation about twice as fast and the compiled binary about 40 % smaller, but the standard library test was a little slower (perhaps something like 6 %). Afterwards I replaced `-M2.3G` with `-M1.5G`, and compilation was still about twice as fast as before.

Can anyone with a 64-bit setup repeat this test?

Perhaps it makes sense to turn off `-fexpose-all-unfoldings` and `-fspecialise-aggressively` by default. These options could be activated using a Cabal flag (`-foptimise-heavily`, or something like that). Any thoughts on this?

**Comment by jespercockx** [comment]
I'm voting against removing the flags by default; the run-time benefits outweigh the slowdown of compilation times IMO (and there's `quicker-install-bin` for quick testing). 

The proper solution to slow compilation would be to remove the two flags and add `{-# INLINEABLE #-}` and `{-# INLINE #-}` pragmas where needed. However, this would take a lot of manual work, and runs the risk of being destroyed accidentally by future patches.

**Comment by nad** [comment]
Above there is a report about how memory runs out when `cabal install Agda` is run. "I could not install Agda (without using the right flags)" is perhaps worse than "Agda is slightly slower (when compiled without the right flags)".

**Comment by andreasabel** [comment]
If you are using Agda seriously you want to compile it with agressive optimization.  But maybe if you are using Agda seriously, you might dig a bit deeper and discover such a cabal flag in the documentation.  As a newbie, you do not want to dig a lot just to get Agda installed.  This might be an argument for @nad's suggestion.

**Comment by smurfhat** [comment]
Case in point new user here, and in fact a new user after several years: Interestingly I have just waited 2 years for the install process to improve (I came back thinking it might have been ironed out), only to find myself turning off a build on my Linux machine after 3 hours for want of _not knowing_ whether it had crashed or not (was that a mistake? I have no idea whatsoever...what happens to config files when one does this??? I don't use Cabal regularly and am confused by issues there too). The issue isn't waiting overnight or waiting two minutes. The issue is _not knowing_ when one has a robust process going on to start ones learning process. By all means tell me it will take 24 hours and I'll set up a moment when I don't need my PC. But if it does take that sort of time I need to know, otherwise the itch to turn the machine off and on will get irresistable, as it just did. The issue is that I don't know what I'm doing, and never will if I can't get past the first stage of installing it and _trusting_ the install. Another example is the mention in the manual (which really does LOOK way better than two years ago) of fonts for EMACS. As a non-EMACS user I'm totally at sea on that comment. Especially when directed (as a Linux user) to an MSI file...

**Comment by nad** [comment]
Thanks for the feedback!

**Comment by rw111** [comment]
After days of experimentation with the advice here (and different versions and so on), this one finally worked with Ubuntu 20, GHC 8.10.3 and 4GB RAM:
cabal install --ghc-options="+RTS -M3G" -j1 --force-reinstalls Agda
and this one didn't:
cabal install --ghc-options="+RTS -M2G" -j1 --force-reinstalls Agda
Needless to say lots of other variants didn't work. For example I had to upgrade GHC to the latest version. I can't test if it _really_ works as I have install problems with both agda-mode and the standard library too.

**Comment by nad** [comment]
Hopefully the installation is easier or faster now. Feedback is welcome.

**Comment by andreasabel** [comment]
> Hopefully the installation is easier or faster now. Feedback is welcome.

What a relief to be able to rebuild Agda in a reasonable time (in many cases) again!!

**Comment by rw111** [comment]
Great! Seems to install on fairly old Ubuntu machine with only 4GB Ram via Cabal in something like an hour.
