### ISSUE TITLE
[reflection] quote is not a defined name

### ISSUE THREAD

**Issue by pnlph** [agda/agda#4534]
Hi,

i am trying this code, but agda does not recognize the keyword `quote` in this context, or maybe it is somehow prohibited its use like this?
```haskell
open import Agda.Builtin.Reflection
quote₀ : Set → Name
quote₀ X = quote X
```
Here is the error message:
```ldif
quote: not a defined name
when checking that the expression quote X has type Name
```

**Comment by jespercockx** [comment]
I think the real problem here is not that `quote` is not a defined name, but that `X` is not a defined name (local variables do not count as defined names, only top-level definitions do). However, the error message is misleading and should be improved.

**Comment by andreasabel** [comment]
Looking at where the error is generated, another problem is cut-and-paste programming...

**Comment by andreasabel** [comment]
In this case, the new error is `Cannot quote a variable X`.

**Comment by jespercockx** [comment]
Maybe the error message should include a suggestion to use `quoteTerm` instead?
