### ISSUE TITLE
changing the predefined precedence of an operator

### ISSUE THREAD

**Issue by pnlph** [agda/agda#4538]
I am reading the documentation about [Precedence](https://agda.readthedocs.io/en/v2.6.1/language/mixfix-operators.html#precedence) but i don't find this. Is it possible to change the precedence of an operator once imported?

Example, this does not seem to work:
```agda
open import Agda.Builtin.Sigma using (_,_)
infix 3 _,_
```

**Comment by gallais** [comment]
In the CHANGELOG for 2.6.1:

> Fixities can now be changed during import in a renaming directive, see Issue 
 #1346. Example:

```agda
open M using (_∙_)
open M renaming (_∙_ to infixl 10 _*_)
```

> After this, `_∙_` is in scope with its original fixity, and as `_*_ `as left associative operator of precedence 10.

This needs to be added to the manual.

**Comment by andreasabel** [comment]
The module `M` is not in scope!  Documentation doesn't type-check anymore.

**Comment by andreasabel** [comment]
Looks fixed now.
