### ISSUE TITLE
Code duplication in TypeChecking.Serialise.Base

### ISSUE THREAD

**Issue by gallais** [agda/agda#4544]
`icodeDouble`, `icodeInteger`, `icodeString`, `icodeNode`, etc. are all
copy/pasted instances of `icodeX`. Do we really need to keep all of them around?
The comment stating that inlining `icodeX` has adverse effects is 6 years old
so is probably based on a version of ghc we are not using anymore.

**Comment by andreasabel** [comment]
Well, you are free to repeat the experiment.
(I personally wouldn't want to spend a day benchmarking the std-lib for this, but no objection if you are motivated.)

**Comment by andreasabel** [comment]
No big interest in this issue.
