### ISSUE TITLE
Documentation build: malformed code-block

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#4550]
Building the documentation, I get this infamous error:
```
$ make user-manual-html 
...
Running Sphinx v1.8.5
.../doc/user-manual/getting-started/installation.rst:64: WARNING: Error in "code-block" directive:
1 argument(s) required, 0 supplied.

.. code-block::

  Compilation error:

  MAlonzo/RTE.hs:13:1: error:
      Failed to load interface for ‘Numeric.IEEE’
      Use -v to see a list of the files searched for.
```
The solution suggested in #2857 and #3619  is to run
``` 
cabal install ieee754
```
However,
```
All the requested packages are already installed:
ieee754-0.8.0
```

What is the fix here?
Can we solve this frequent issue in a robust way?

**Comment by asr** [comment]
> `cabal install ieee754`

`cabal-install` version?

**Comment by andreasabel** [comment]
```
$ cabal --version
cabal-install version 2.4.1.0
compiled using version 2.4.1.0 of the Cabal library 
```

**Comment by nad** [comment]
@andreasabel, I don't think the error you see has anything to do with your Haskell tool chain:

https://github.com/agda/agda/blob/57165760eeffdbf2aec92b636cb92075d79ac7a3/doc/user-manual/getting-started/installation.rst#L64-L70

**Comment by asr** [comment]
Which is the output of

```
$ ls ~/.cabal/store
```

?

(I expect the error ```"No such file or directory"```).

**Comment by nad** [comment]
I'm guessing that the problem is that `code-block::` should be followed by the name of a language, like `bash` or `emacs`.

**Comment by andreasabel** [comment]
@asr:
> Which is the output of
> 
> ```
> $ ls ~/.cabal/store
> ```

ghc-8.4.4 ghc-8.6.4 ghc-8.8.2

**Comment by andreasabel** [comment]
@nad:
> @andreasabel, I don't think the error you see has anything to do with your Haskell tool chain:
> 
> https://github.com/agda/agda/blob/57165760eeffdbf2aec92b636cb92075d79ac7a3/doc/user-manual/getting-started/installation.rst#L64-L70

Oh, I see, thanks.  I have been fooled, assuming this is an actual error rather than the quotation of an error.  This should be easily fixable then.
