### ISSUE TITLE
[reflection] α-conversion howto

### ISSUE THREAD

**Issue by pnlph** [agda/agda#4553]
This code is not typechecking. Agda tries to literally compare the strings "x" and "c":
```agda
_ : quoteTerm (λ (x y : Bool) → x) ≡ quoteTerm (λ (c d : Bool) → c)
_ = refl
```
Is there a way of expressing a lambda abstraction only with de Bruijn indexes? The constructor `abs` seems to require always a `String` element.

**Comment by nad** [comment]
> Is there a way of expressing a lambda abstraction only with de Bruijn indexes?

I guess you could traverse the terms and replace all the strings with `""`.

**Comment by jespercockx** [comment]
Other options that have a higher initial cost but might pay off in the future:

- Define your own datatype for representing terms that is better geared to what you want to do, and in particular do not include the names in binders.
- Define a custom relation `_≈_ : Term -> Term -> Set` that expresses when two terms are alpha-equivalent (you might also include other equivalences)

In general, the types that are built into Agda (in this case, `Term` and the equality type) are not necessarily the ones you'd want to use for any particular application.

**Comment by pnlph** [comment]
@jespercockx What is the best way to define a custom `Term` datatype?

I tried to duplicate the Reflection module in a new atom project, but it is not typechecking without disabling the `--safe` flag.

**Comment by jespercockx** [comment]
Well how you define your type of terms really depends on what you want to use the reflection *for*, the whole point of defining your own type is that you can specialize it to the application. For example, the ring solver in the standard library uses a syntax that only represents expressions consisting of the ring operations (and lumps together all the other terms in an "other" constructor).

I'm not sure what goes wrong when you try to use the `--safe` flag, can you post the error message?

**Comment by pnlph** [comment]
Thanks, I will take a look at that ring solver.

Yes, I get two errors:
```
.../reflection-lib-h.agda:53,1-131
COMPILE pragma not allowed in safe mode.
.../reflection-lib-h.agda:54,1-110
COMPILE pragma not allowed in safe mode.
```
It works when i remove `--safe`

**Comment by nad** [comment]
You can remove the `COMPILE` pragmas.
