### ISSUE TITLE
Documentation PDF build failure: agda.png is not a PNG file

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#4554]
I had this problem on python 2.7 with Sphinx 1.8.5.  Upgrading to python 3 and Sphinx 2.4.4 (latest?) did not help:
```
$ make user-manual-pdf
========================= User manual (PDF) ==========================
make[1]: Entering directory '.../doc/user-manual'
Running Sphinx v2.4.4
...
copying images... [100%] getting-started/../agda.svg  
...
Running 'pdflatex   -recorder  "Agda.tex"'
------------
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=pdflatex)
...
(./Agda.tex
...
libpng error: Not a PNG file
!pdfTeX error: pdflatex (file ./agda.png): libpng: internal error
 ==> Fatal error occurred, no output PDF file produced!
```
Indeed, the generated `agda.png` in `doc/user-manual/_build/latex` is not a PNG file, it starts like this:
```
push graphic-context
encoding "UTF-8"
viewbox 0 0 5217 1707
affine 1 0 0 1 0 0
#Created with Sketch.
push graphic-context
stroke 'none'
...
```   
Manually deleting this file I can build the documentation PDF without the logo.

**Comment by fredrikNordvallForsberg** [comment]
It works for me, and the generated PNG file is a PNG file... Do you have imagemagick `convert` properly installed? (This should probably be added to [the dependencies](https://agda.readthedocs.io/en/v2.6.1/contribute/documentation.html#rendering-documentation-locally).)

**Comment by andreasabel** [comment]
I have
```
$ convert --version
Version: ImageMagick 6.9.2-3 Q16 x86_64 2015-10-02 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules 
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png tiff xml zlib
```

**Comment by fredrikNordvallForsberg** [comment]
Does it understand SVG files?
```convert -list format```

**Comment by andreasabel** [comment]
It mentions in a long list:
```
      SVG  SVG       rw+   Scalable Vector Graphics (XML 2.9.0)
     SVGZ  SVG       rw+   Compressed Scalable Vector Graphics (XML 2.9.0)
```

**Comment by andreasabel** [comment]
It seems to understand SVG as the content of "agda.png" is a MVG file (imagemagick's own format).  It seems there are problems on MAC OS with support for PNG though.
PNG is conspicuously missing from the list.

**Comment by andreasabel** [comment]
Thanks @fredrikNordvallForsberg , upgrading imagemagick solved the problem!

**Comment by andreasabel** [comment]
> (This should probably be added to [the dependencies](https://agda.readthedocs.io/en/v2.6.1/contribute/documentation.html#rendering-documentation-locally).)

Done.
