### ISSUE TITLE
custom pragmas, built-ins

### ISSUE THREAD

**Issue by pnlph** [agda/agda#4555]
Is it possible to define custom pragmas eg, built-ins in Agda?

I tried to bind the `Even` datatype like this:
```agda
open import Data.Nat using (ℕ; suc)
data Even : ℕ → Set where
  zero : Even 0
  suc-suc : ∀ {n} → Even n → Even (suc (suc n))

{-# BUILTIN NATURAL Even #-}
```
But is not working, the error thrown is:
```
ℕ → Set !=< Set when checking that the expression Even has type Set
```
I read in the Language Reference -> [Built-ins](https://agda.readthedocs.io/en/v2.6.1/language/built-ins.html#built-ins) that:
> ...in order to use the special treatment of natural numbers (say) you define an appropriate data type and then bind that type to the natural number concept using a BUILTIN pragma.

Is `primNat` this _natural number concept_, and can it be reused to define a built-in for even numbers?

The objective would be that when evaluating the normal form of `suc-suc zero`, agda resolves to `2`, similar to what is done for elements of the Nat datatype when is bound via the `{-# BUILTIN NATURAL Nat #-}`pragma.

**Comment by gallais** [comment]
The builtin `NATURAL` expects a datatype of the form `data N = Z | S N`.
You cannot throw in additional parameters and argument (implicit or not).

You may want to write an erasure function and normalise `erase (suc-suc zero)` instead?

```agda
erase : Even n -> Nat
erase {n} _ = n
```

**Comment by guillaumebrunerie** [comment]
No, you cannot use the pragma `NATURAL` on `Even`.
I’m not really sure what you are trying to do, but you may be able to use the `FROMNAT` builtin, see https://agda.readthedocs.io/en/v2.6.1/language/literal-overloading.html.
This allows you to use natural number literals for other datatypes like finite types and so on. It would allow you to use `2` to mean `suc-suc zero`, although you need to figure out how it works and be somewhat familiar with instance arguments. It won’t allow you to "reduce `suc-suc zero` to `2`" though, whatever that means.
