### ISSUE TITLE
activate github's discussions beta

### ISSUE THREAD

**Issue by pnlph** [agda/agda#4557]
Hi,

would it be possible to activate the discussions beta for agda/agda? I see that sometimes the issues are about asking something or discussing about a feature, like this issue itself.

Now filing an issue is the only alternative. I would find discussons very useful, how about you?

You can see an [example of the discussions module](https://github.com/zeit/next.js/discussions) in production. There are also [some drawbacks](https://github.com/microsoft/microsoft-ui-xaml/issues/2013#issuecomment-592689659) to be considered, but in my opinion it would be a very good fit for the Agda Community.

**Comment by guillaumebrunerie** [comment]
Well, the other alternative is to send an email to the mailing list, it usually works pretty well.

**Comment by andreasabel** [comment]
The combination of "email" and "works well" in once sentence is paradoxical, imho.  ;-)

Email is an archaic idea from the physical world.  There are many solutions now that structure and organize communication better (an issue tracker being a good example).

"Discussions" seem to add to the ordinary issue tracking the possibility to reply to a specific comment (not just post a new comment).  There is also some up-voting facility, at least for discussions as a whole in the list of discussions.

I'd say we try it out.

**Comment by nad** [comment]
Email has some advantages:
* It is standardised.
* You can use lots of different tools.

I would have liked to see similar standards for, say, issue trackers.

**Comment by andreasabel** [comment]
Which sort of tools do you suggest that bring to email the features of a bug tracker:
* already sorted by topic when you write the comment
* archived
* one-click linkable from other issues, even across projects
* one-click links to the relevant code
?

**Comment by nad** [comment]
I did not suggest that we should use email instead of an issue tracker.

**Comment by pnlph** [comment]
Thank you all for taking the time to answer. I can only share my experience with the community by describing the problems that I found and explaining how I think a discussion module would help.

### Duplicate check
The first problem is checking for duplications before submitting an issue.

To do this, Github provides a beneficial `Similar issues` tool, but I have to look also for a possible similar questions in the agda list. I do this by searching in my email client, but only to find results not prior the date I joined the agda list.

A third step is to look for old possible similar questions in the [Agda archive](https://lists.chalmers.se/pipermail/agda/). Then I feel ready to submit an issue. Due to time restrictions, I do often skip this third step.

### Question vs. Issue
The second problem is deciding where to post a question.

If it is a hands-on question, I use the [agda/agda Gitter chat](https://gitter.im/agda/agda), and I already got valuable answers there. Unfortunately, since all conversations in the channel are mixed, they are not easily searchable.

If it is a more theoretical question, I use the Agda list, but knowing that future agda list members will have the same trouble as I had when trying to find my question and its answer.

### Q&A unique repository
I wish that there could be a public and unique Q&A's of Agda, at least for hands-on questions, preferably that can also refer to issues and PRs. It is probably hard to get a catalog that includes all meaningful prior knowledge, but it is easy to get started from the current timestamp.

### Export current knowledge
The hard part. It would make sense also to classify, filter, and export all the old questions that could fit into this module. Like you were doing a long time ago with the Google code exporter for old issues.

### Resources
Another question is the resources that this would bind, especially the export part. I can only speak for myself and say that I would volunteer to help to perform such a task.

### An imperfect world
I am aware that we live in a world where everything is bound to available resources. Maybe there are some other considerations that makes the proposal impracticable, so I can also live without the discussion module, of course.

In the end, the ones who really want a question solved, they still will find the answer anyway. However, this would be a great help for the less proactive users and a time-saver for the rest.

**Comment by nad** [comment]
Can one easily export data from the discussion module, if something better appears in the future?

**Comment by pnlph** [comment]
> Can one easily export data from the discussion module, if something better appears in the future?

About it, I only found [this question](https://news.ycombinator.com/item?id=22389736) within the [Github Discussion Beta](https://news.ycombinator.com/item?id=22388639) page at YCombinator. [Github API](https://developer.github.com/v3/issues/) should allow it programmatically. Not sure how easy the process would be and if it is good enough to keep all metadata, but an example is mentioned there.

Anyway, thinking about the portability of all the knowledge gathered around Agda is quite relevant.

**Comment by andreasabel** [comment]
There is also stackoverflow which is much more structured than email and could be an alternative.  I prefer stackoverflow over all other help pages.  Concerning Agda, I am not active on stackoverflow since I only go there when I _need_ help.
With stackoverflow the issue of conserving the knowledge would be similar than to github discussions, I suppose.  (I haven't checked, though.)

**Comment by gallais** [comment]
Stackoverflow has a reputation for being a fairly hostile place. [They're trying
to fix the culture](https://stackoverflow.blog/2018/04/26/stack-overflow-isnt-very-welcoming-its-time-for-that-to-change/) and I have not really encountered too many aggressive people
while answering Agda-related questions but the reputation alone could put some
people off even bothering to create an account to ask a question there.

**Comment by andreasabel** [comment]
@gallais : Indeed, one cannot "import" reputation into SO.  Even as Agda developer I would start with 0 reputation there.  Doesn't reflect the real world well.

**Comment by jespercockx** [comment]
Since we already have the official Zulip now, it seems like a bad idea to also use Github discussions, so I'll close this issue.
