### ISSUE TITLE
Build failure with dynamic linking (logic in Setup.hs broken)

### ISSUE THREAD

**Issue by mouse07410** [agda/agda#4569]
macOS Catalina 10.15.4, Xcode-11.4, `ghcup`-installed GHC-8.8.3, Cabal-3.2.0.0.

Cabal configured with
```
. . . . .
library-vanilla: True
library-profiling: False
shared: True
-- static:
executable-dynamic: True
. . . . .
```

Attempt to install Agda:
```
$ cabal install Agda
. . . . .
[369 of 369] Compiling Agda.Main        ( src/full/Agda/Main.hs, dist/build/Agda/Main.o )
Preprocessing executable 'agda' for Agda-2.6.1..
Building executable 'agda' for Agda-2.6.1..
[1 of 1] Compiling Main             ( src/main/Main.hs, dist/build/agda/agda-tmp/Main.dyn_o )
Linking dist/build/agda/agda ...
dyld: Library not loaded: @rpath/libHSAgd-2.6.1-bd0fa011-ghc8.8.3.dylib
  Referenced from: /private/var/folders/c6/lnc_0m093ys8w16md_fm1mnxhtfnj8/T/cabal-install.-23849/dist-newstyle/tmp/src-23849/Agda-2.6.1/dist/build/agda/agda
  Reason: image not found
Error: Failed to typecheck /private/var/folders/c6/lnc_0m093ys8w16md_fm1mnxhtfnj8/T/cabal-install.-23849/dist-newstyle/tmp/src-23849/Agda-2.6.1/src/data/lib/prim/Agda/Builtin/Bool.agda!
Generating Agda library interface files...
... /private/var/folders/c6/lnc_0m093ys8w16md_fm1mnxhtfnj8/T/cabal-install.-23849/dist-newstyle/tmp/src-23849/Agda-2.6.1/src/data/lib/prim/Agda/Builtin/Bool.agda
cabal: Failed to build Agda-2.6.1. See the build log above for details.

```

Log: [Agd-2.6.1-bd0fa011.log.txt](https://github.com/agda/agda/files/4435078/Agd-2.6.1-bd0fa011.log.txt)

**Comment by andreasabel** [comment]
I have not tried dynamic linking yet.
`dyld: Library not loaded: @rpath/`.  This `@rpath` looks suspicious.
I quickly googled and found this, e.g.:
https://stackoverflow.com/questions/28244468/dyld-library-not-loaded-rpath-with-ios8
Can you research your problem a bit and see if you can fix, and then report back here?
Thanks!

**Comment by mouse07410** [comment]
> Can you research your problem a bit and see if you can fix, and then report back here?

Sorry, I cannot fix it.

All I can say is that the library in question was not properly installed, if it was built at all. There is no presence of the library in question anywhere in the system.

Since the build deletes the intermediate directories, I can't dig deeper.

### Update
The problem you Googled seems about *running* a successfully-built executable, which fails to locate the *existing* library. In this case, the *linker* fails to locate the library to *build* the Agda executable - and I strongly suspect that this library has not been built (because I cannot find it anywhere on the system, not just where the executable would/should expect it).

### Update 2

> I have not tried dynamic linking yet

The simplest way to try it, if you don't want to edit your `~/.cabal/config` file, is to do
```
$ cabal install --enable-shared --enable-executable-shared --disable-static Agda
```
and observe the result.

**Comment by nad** [comment]
I tried using (roughly) `make install CABAL_OPTS="--enable-shared --enable-executable-dynamic"` (with GHC 8.10.1 on Linux i386), and this seems to have worked fine:
```
$ ldd $(which agda-2.6.1) | wc -l
17
$ ldd $(which agda) | wc -l
89
$ ls -sh $(which agda-2.6.1) | cut -d' ' -f1
55M
$ ls -sh $(which agda) | cut -d' ' -f1
24K
```

Why do you want to use dynamic linking?

**Comment by mouse07410** [comment]
> Why do you want to use dynamic linking?

Preserving disk space.

**Comment by nad** [comment]
Perhaps I should use dynamic linking when I use `agda-bisect --cache`:
```
$ du -sh .cabal-sandbox/bin/
8,4G    .cabal-sandbox/bin/
```

**Comment by andreasabel** [comment]
I observed that:
1. "installing the Agda executable" is the last thing that `cabal install` does. 
2. Before that, it calls the freshly compiled Agda from its temporary residence in `dist/build/...` to compile some `.agda` files.
3. If step 2. fails, Agda is not installed in the final location, say `.cabal/bin/`.

This workflow has greatly annoyed me as a developer, because it quite often happened to me that step 2 fails due to some change I did to Agda, and then 3 is skipped, meaning I have a harder time to debug what lead to the failure of 2.

I can _imagine_ the following is happening:
Since dynamic linking is an obscure feature, step 2 simply does not work with dynamic linking, and no one ever tried.  It might be that for 2., it is assumed that Agda is already installed in its final location, but this only happens at 3.

@mouse07410 :  Did you find out what this mysterious `@rpath` is supposed to be and how it is resolved to a real path?

**Comment by andreasabel** [comment]
@nad:
> I tried using (roughly) `make install CABAL_OPTS="--enable-shared --enable-executable-dynamic"` (with GHC 8.10.1 on Linux i386), and this seems to have worked fine.

Did you also try it in the virginal situation where no `agda` is on the system path and thus step 2 may fail?

**Comment by andreasabel** [comment]
@mouse07410 :
> Since the build deletes the intermediate directories, I can't dig deeper.

This can be prevented by going into a fresh directory and there do:
```
cabal unpack Agda
cd Agda-2.6.1
cabal install ...<options>
```
Then you can look in the `dist` subdirectory what has been created.

I tried (Mac OS X and ghc 8.4.4)
```
Agda-2.6.1$ cabal install -O0 --program-suffix=-2.6.1-dyn --enable-shared --enable-executable-dynamic --disable-static 
```
and end up with the same failure:
```
Generating Agda library interface files...
... /Agda-2.6.1/src/data/lib/prim/Agda/Builtin/Bool.agda
dyld: Library not loaded: @rpath/libHSAgda-2.6.1-JMPy8mlrADAFplhuDdI0pM-ghc8.4.4.dylib
  Referenced from: /Users/abel/tmp/foo/Agda-2.6.1/dist/build/agda/agda
  Reason: image not found
```
However, I am having difficulties to reproduce this in a MWE.

Useful information about `@rpath` here: https://medium.com/@donblas/fun-with-rpath-otool-and-install-name-tool-e3e41ae86172

**Comment by andreasabel** [comment]
I managed to construct a MWE in d1b41cc4d4c795a5b7e6cb084673dfa78c172fe8 that exhibits the same pathological behavior as the Agda `Setup.hs` script.  
Running `agda` from the build location (before built artefacts are copied to the install location) seems to work for a statically linked executable but fails for a dynamically linked one.  Since running `agda` has been made a prerequisite to installing Agda in the install location, we have a vicious circle here.

Regression likely introduced by 378020321a223d7057cd10b59b995ebac91c7a8b released in Agda 2.6.0.

**Comment by nad** [comment]
> Did you also try it in the virginal situation where no `agda` is on the system path and thus step 2 may fail?

No. See the following lines in `Setup.hs`:

https://github.com/agda/agda/blob/d1b41cc4d4c795a5b7e6cb084673dfa78c172fe8/Setup.hs#L65-L66

Did you try `make quicker-install-bin CABAL_OPTS="--enable-shared --enable-executable-dynamic"`?

**Comment by nad** [comment]
> Running `agda` from the build location (before built artefacts are copied to the install location) seems to work for a statically linked executable but fails for a dynamically linked one.

If the dynamic libraries (in particular the Agda library) have not yet been copied into the correct directory, then it makes sense that the program does not work correctly. If I rename a certain directory, then I get the following error:
```
$ agda
agda: error while loading shared libraries: libHSAgda-2.6.2-92cioxalLXSCrkj4L1FCmY-ghc8.10.1.so: cannot open shared object file: No such file or directory
```

Perhaps the problem can be solved by moving the code that type-checks the primitive and builtin files from `Setup.hs` to `src/main/Setup.hs`.

**Comment by mouse07410** [comment]
> If the dynamic libraries (in particular the Agda library) have not yet been copied into the correct directory, then it makes sense that the program does not work correctly

And that's exactly the error we (at least I) observe - the Agda library not moved to the place it's expected to reside (relative to the Agda program/executable itself).

**Comment by andreasabel** [comment]
@nad : Does my MWE (d1b41cc4d4c795a5b7e6cb084673dfa78c172fe8) also fail on linux?
```
cd test/Bugs/Issue4569
make
```

**Comment by nad** [comment]
Yes.

**Comment by andreasabel** [comment]
@mouse07410 @nad : I pushed a fix to master, please test.

**Comment by mouse07410** [comment]
```
. . . . .
Linking dist/build/agda/agda ...
Installing executable agda-mode in /Users/ur20980/.cabal/store/ghc-8.8.3/incoming/new-59693/Users/ur20980/.cabal/store/ghc-8.8.3/Agd-2.6.2-27647ce5/bin
Warning: The directory
/Users/ur20980/.cabal/store/ghc-8.8.3/incoming/new-59693/Users/ur20980/.cabal/store/ghc-8.8.3/Agd-2.6.2-27647ce5/bin
is not in the system search path.
Installing library in /Users/ur20980/.cabal/store/ghc-8.8.3/incoming/new-59693/Users/ur20980/.cabal/store/ghc-8.8.3/Agd-2.6.2-27647ce5/lib
Installing executable agda in /Users/ur20980/.cabal/store/ghc-8.8.3/incoming/new-59693/Users/ur20980/.cabal/store/ghc-8.8.3/Agd-2.6.2-27647ce5/bin
Warning: The directory
/Users/ur20980/.cabal/store/ghc-8.8.3/incoming/new-59693/Users/ur20980/.cabal/store/ghc-8.8.3/Agd-2.6.2-27647ce5/bin
is not in the system search path.
dyld: Library not loaded: @rpath/libHSAgd-2.6.2-27647ce5-ghc8.8.3.dylib
  Referenced from: /private/var/folders/c6/lnc_0m093ys8w16md_fm1mnxhtfnj8/T/cabal-install.-59693/dist-newstyle/tmp/src-59693/Agda-2.6.2/dist/build/agda/agda
  Reason: image not found
Error: Failed to typecheck /private/var/folders/c6/lnc_0m093ys8w16md_fm1mnxhtfnj8/T/cabal-install.-59693/dist-newstyle/tmp/src-59693/Agda-2.6.2/src/data/lib/prim/Agda/Builtin/Bool.agda!
Generating Agda library interface files...
... /private/var/folders/c6/lnc_0m093ys8w16md_fm1mnxhtfnj8/T/cabal-install.-59693/dist-newstyle/tmp/src-59693/Agda-2.6.2/src/data/lib/prim/Agda/Builtin/Bool.agda
cabal: Failed to build Agda-2.6.2. See the build log above for details.
```

**Comment by andreasabel** [comment]
@mouse07410 Are you sure you are not having other issues?
* Path
```
Warning: The directory
/Users/ur20980/.cabal/store/ghc-8.8.3/incoming/new-59693/Users/ur20980/.cabal/store/ghc-8.8.3/Agd-2.6.2-27647ce5/bin
is not in the system search path.
```
* Why `Agd` and not `Agda` in your case?
* What is that weird path `/Users/ur20980/.cabal/store/ghc-8.8.3/incoming/new-59693/Users/ur20980/.cabal/store/ghc-8.8.3/`??

Are you using `stack`?  I only tested `cabal install`.

I am getting:
```
[1 of 1] Compiling Main             ( src/main/Main.hs, dist/build/agda/agda-tmp/Main.dyn_o )
Linking dist/build/agda/agda ...
Installing executable agda-mode in /Users/abel/.cabal/bin
Installing library in /Users/abel/.cabal/lib/x86_64-osx-ghc-8.8.3/Agda-2.6.2-Akdu98FgvcdDHKiVvNiKHf
Installing executable agda in /Users/abel/.cabal/bin
Generating Agda library interface files...
... /Users/abel/agda-erasure/src/data/lib/prim/Agda/Builtin/Bool.agda
...
... /Users/abel/agda-erasure/src/data/lib/prim/Agda/Primitive.agda
... /Users/abel/agda-erasure/src/data/lib/prim/Agda/Primitive/Cubical.agda
Installing executable agda-mode in /Users/abel/.cabal/bin
Installing library in /Users/abel/.cabal/lib/x86_64-osx-ghc-8.8.3/Agda-2.6.2-Akdu98FgvcdDHKiVvNiKHf
Installing executable agda in /Users/abel/.cabal/bin
```

**Comment by mouse07410** [comment]
> Are you sure you are not having other issues?

Yes I am. At least in this case.

> Are you using `stack`? I only tested `cabal install`.

No, I'm testing only with Cabal (though my machine does have `stack` installed).

> 1. Why Agd and not Agda in your case?
> 2. What is that weird path /Users/ur20980/.cabal/store/ghc-8.8.3/incoming/new-59693/Users/ur20980/.cabal/store/ghc-8.8.3/??

1. Because Cabal shortens the original names, at least on Mac. In the example below, it shortened "haskell" to "hskll". I've no explanation for that behavior, except that for everything else it doesn't interfere, aka works.
2. Because the build was not completed successfully? Or maybe that's the result of v2 builds, which are now the default - everything is "sandboxed". Again, I don't know. 

An example of what a correct/successful dynamic build looks like (picking HIE as an example - a large complicated package with many hierarchical dependencies, so it looks real "enough"):
```
$ ll ~/.cabal/bin/hie
lrwxr-xr-x  1 ur20980  179427977  51 Apr 26 11:07 /Users/ur20980/.cabal/bin/hie@ -> ../store/ghc-8.8.3/hskll-d-ngn-1.3-17d75f10/bin/hie
$ otool -L ~/.cabal/bin/hie
/Users/ur20980/.cabal/bin/hie:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
	@rpath/libHShskll-d-ngn-1.3-ef6c58d2-ghc8.8.3.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libHSh-plgn-p-1.3-fefa6421-ghc8.8.3.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libHShskll-lsp-0.20.0.1-81a99cd1-ghc8.8.3.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libHShskll-lsp-typs-0.20.0.0-606216c4-ghc8.8.3.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libHSh-bs-0.4.0-b8111604-ghc8.8.3.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libHSyml-0.11.3.0-9cffab13-ghc8.8.3.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libHShslggr-1.3.1.0-e75649d9-ghc8.8.3.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libHStext-1.2.4.0-ghc8.8.3.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libHSghc-8.8.3-ghc8.8.3.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libHSdirectory-1.3.6.0-ghc8.8.3.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libHSfilepath-1.4.2.1-ghc8.8.3.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libHScontainers-0.6.2.1-ghc8.8.3.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libHSbase-4.13.0.0-ghc8.8.3.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libHSghc-prim-0.5.3-ghc8.8.3.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libHSrts_thr-ghc8.8.3.dylib (compatibility version 0.0.0, current version 0.0.0)
$ hie --version
Version 1.3 x86_64 ghc-8.8.3
$ 
```

`otool -L ...` => `ldd ...` on Linux

### Update
Is there a reason why your `README.md` does not cover building from the source at all?

### Update 2

First, could you please re-open this issue? It has **not** been resolved.

Running the build via Makefile:
```
. . . . .
Completed    tasty-silver-3.1.13
Completed    aeson-1.4.7.1
Starting     Agda-2.6.2
Building     Agda-2.6.2
Failed to install Agda-2.6.2
Build log ( /Users/ur20980/.cabal/logs/ghc-8.8.3/Agda-2.6.2-GwyUOxXzAmS4IIqUV6XB6g.log ):
cabal: Entering directory '.'
[1 of 1] Compiling Main             ( dist-2.6.2/setup/setup.hs, dist-2.6.2/setup/Main.o )
Linking ././dist-2.6.2/setup/setup ...
Configuring Agda-2.6.2...
Preprocessing executable 'agda-mode' for Agda-2.6.2..
Building executable 'agda-mode' for Agda-2.6.2..
[1 of 2] Compiling Paths_Agda       ( dist-2.6.2/build/agda-mode/autogen/Paths_Agda.hs, dist-2.6.2/build/agda-mode/agda-mode-tmp/Paths_Agda.dyn_o )
[2 of 2] Compiling Main             ( src/agda-mode/Main.hs, dist-2.6.2/build/agda-mode/agda-mode-tmp/Main.dyn_o )
Linking ./dist-2.6.2/build/agda-mode/agda-mode ...
Preprocessing library for Agda-2.6.2..
alex: /Users/ur20980/.stack/snapshots/x86_64-osx/lts-13.15/8.6.4/share/x86_64-osx-ghc-8.6.4/alex-3.2.4/AlexTemplate-ghc: openFile: does not exist (No such file or directory)
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
Agda-2.6.2-GwyUOxXzAmS4IIqUV6XB6g failed during the building phase. The
exception was:
ExitFailure 1
```

Here's the log: [agda-build-fail.txt](https://github.com/agda/agda/files/4536381/agda-build-fail.txt)

**Comment by asr** [comment]
> No, I'm testing only with Cabal (though my machine does have `stack` installed).

```
Linking ./dist-2.6.2/build/agda-mode/agda-mode ...
Preprocessing library for Agda-2.6.2..
alex: /Users/ur20980/.stack/snapshots/x86_64-osx/lts-13.15/8.6.4/share/x86_64-osx-ghc-8.6.4/alex-3.2.4/AlexTemplate-ghc: openFile: does not exist (No such file or directory)
```

Somehow you are mixing the `cabal-install` and the  `stack` installations (the error is about a version of `Alex` installed with `stack`).

**Comment by mouse07410** [comment]
If you're suggesting that I should install Alex via Cabal and try again - I'm willing to do so. Though I don't quite understand why it could matter what toolchain generated the Alex binary.

**Comment by asr** [comment]
> If you're suggesting that I should install Alex via Cabal and try again - I'm willing to do so.

Since Agda's`Makefile` uses `cabal-install` v1-commands I suggest use them for installing Alex.

> Though I don't quite understand why it could matter what toolchain generated the Alex binary.

Neither do I. I'm not familiar with `stack`. I don't know if using GHC 8.8.3 and Alex installed via `stack` on GHC 8.6.4 should work.

**Comment by mouse07410** [comment]
> I'm not familiar with `stack`. 

It's another Haskell build and package management system. Somewhat like `make`, `cmake`, `autotools` in the C world - all use different ways to configure, etc., but once the binary is produced - you can't even tell which of those did it.

> I don't know if using GHC 8.8.3 and Alex installed via `stack` on GHC 8.6.4 should work.

An executable is an executable - why would it matter what toolchain produced it, or even what programming language it's source was written in?

**Comment by nad** [comment]
> @mouse07410 @nad : I pushed a fix to master, please test.

```
dist/build/hello-world/hello-world: error while loading shared libraries: libHSHelloWorld-0.1.0.0-DVZjFDt1ZaY2ycqMGIOb7x-ghc8.8.3.so: cannot open shared object file: No such file or directory
```

Or did you want me to test a full build?

**Comment by mouse07410** [comment]
Current master:
```
[56 of 62] Compiling Internal.Interaction.Options ( test/Internal/Interaction/Options.hs, dist-2.6.2/build/agda-tests/agda-tests-tmp/Internal/Interaction/Options.dyn_o ) [Agda.Interaction.Options.Lenses changed]
[57 of 62] Compiling Internal.Tests   ( test/Internal/Tests.hs, dist-2.6.2/build/agda-tests/agda-tests-tmp/Internal/Tests.dyn_o ) [Internal.Compiler.MAlonzo.Encode changed]
[62 of 62] Compiling Main             ( test/Main.hs, dist-2.6.2/build/agda-tests/agda-tests-tmp/Main.dyn_o ) [Internal.Tests changed]
Linking ./dist-2.6.2/build/agda-tests/agda-tests ...
Undefined symbols for architecture x86_64:
  "_Agdazm2zi6zi2zmGwyUOxXzzAmS4IIqUV6XB6g_AgdaziTypeCheckingziSubstitute_piSortzqzuzdszdfFreeClausezuzdcfreeVarszq6_info", referenced from:
      _LcYUY_info in Generators.dyn_o
      _LcYV9_info in Generators.dyn_o
      _LcZ9A_info in Generators.dyn_o
      _Lc139K_info in TypeChecking.dyn_o
      _Lc139V_info in TypeChecking.dyn_o
      _Lc13om_info in TypeChecking.dyn_o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`clang' failed in phase `Linker'. (Exit code: 1)
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
Agda-2.6.2-GwyUOxXzAmS4IIqUV6XB6g failed during the building phase. The
exception was:
ExitFailure 1
```

> Or did you want me to test a full build?

If you can test it on your side, it would be nice - but not critical. I'm happy to run the builds here.

### Update
Actually, the current master seems worse than the one of yesterday: then the build succeeded after I re-installed `Alex` and `happy` with Cabal (they were previously installed via `stack` and were one year old). Today, as you can see above, the master fails to build.

**Comment by nad** [comment]
When I get errors like that I remove `dist-2.6.2` and restart the build.

**Comment by mouse07410** [comment]
Success, I think:
```
$ make
touch src/full/Agda/VersionCommit.hs
===================== Installing using Cabal with test suites ============
time cabal v1-install --disable-documentation --builddir=./dist-2.6.2 --enable-tests --disable-library-profiling -fenable-cluster-counting --ghc-options="+RTS -M3G -RTS" 
Resolving dependencies...
In order, the following will be installed:
Agda-2.6.2 *test (reinstall) (changes: QuickCheck-2.13.2 added,
filemanip-0.3.6.3 added, process-extras-0.7.4 added, tasty-1.2.3 added,
tasty-hunit-0.10.0.2 added, tasty-quickcheck-0.10.1.1 added,
tasty-silver-3.1.13 added, temporary-1.3 added, unix-compat-0.5.2 added)
Warning: Note that reinstalls are always dangerous. Continuing anyway...
Starting     Agda-2.6.2
Building     Agda-2.6.2
Completed    Agda-2.6.2

real	23m51.744s
user	23m24.204s
sys	0m24.321s
$ 
$ 
$ agda --version
Agda version 2.6.2-02cb18a
$ agda-mode
This program, which is part of Agda version 2.6.2, can be run
in three modes, depending on which option it is invoked with:

setup

  The program tries to add setup code for Agda's Emacs mode to the
  current user's .emacs file. It is assumed that the .emacs file
  uses the character encoding specified by the locale.

locate

  The path to the Emacs mode's main file is printed on standard
  output (using the UTF-8 character encoding and no trailing
  newline).

compile

  The program tries to compile Agda's Emacs mode's source files.

  WARNING: If you reinstall the Agda mode without recompiling the Emacs
  Lisp files, then Emacs may continue using the old, compiled files.
$ agda-mode locate
/Users/ur20980/.cabal/share/x86_64-osx-ghc-8.8.3/Agda-2.6.2/emacs-mode/agda2.el$ 
$ 
$ agda-mode setup
agda-mode: emacs: rawSystem: runInteractiveProcess: exec: does not exist (No such file or directory)
```

Comments? 

And a couple of questions:
1. How to get `agda-mode` do what it's supposed to?
2. Are there other IDE (ideally - a plugin for Visual Studio Code or JetBrains IDEA or such) to support Agda? I'm not that crazy about Emacs...

**Comment by nad** [comment]
I'm guessing that Emacs is not on your `PATH`.

**Comment by mouse07410** [comment]
Thank you (since it's MacOS, Emacs is started as an app `/Applications/Emacs.app`)! Indeed, getting `Emacs` executable on the `PATH` helped.

Now - is Emacs the only editor/IDE that can work with Agda? *Anything* for VSCode?

**Comment by nad** [comment]
I think some people are using Atom, which has [support](https://atom.io/packages/agda-mode) for Agda.

**Comment by mouse07410** [comment]
I found a VSCode module for Agda. Search for `language-agda` in the VSCode extensions. `language-agda` points at https://github.com/mokus0/Agda.tmbundle

**Comment by andreasabel** [comment]
@mouse07410 I am glad you could resolve the issue on your side, and thanks for reporting the problem.  Thanks to everyone (@asr @nad) who helped!

The development workflow has improved for me after fixing this issue.  Now I can build and install the Agda executable even if it breaks one of the library files, which often happens during development.
