### ISSUE TITLE
add PiSort and UnivSort to the documentation

### ISSUE THREAD

**Issue by pnlph** [agda/agda#4572]
> `piSort` is a constructor for sorts such that if `A : s1` and `x : A |- B : s2`, then `(x : A) -> B : piSort s1 (\x -> s2)`. It should never appear in a fully typechecked program, but it is used during constraint solving when we don't know yet whether a sort is of the form `Set l`, `Prop l`, `Setω`, or `SizeUniv`. I wrote a blog post about this a while ago at https://jesper.sikanda.be/posts/agdas-new-sorts.html, maybe it should also be added to the official documentation somewhere.

_Originally posted by @jespercockx in https://github.com/agda/agda/issues/3960#issuecomment-569135666_

I found this among the very long thread #3960, but still in the current version of the user-manual not a trace of either `PiSort` and `UnivSort` exist.

Where should this be located in the documentation? Maybe Language Reference -> Sorts? If there are other observations additional to Jesper's article, please post them in this issue.

I can also remove the self-assignment if someone wants to do it.

**Comment by jespercockx** [comment]
Yes, it would be great to have this in the documentation. Currently we have a page on universe levels as well as one on `Prop`, but I think it would be good to have a new page explaining the sort system in general. It would be great if you could write something based on your understanding, I can add things that are missing (if there's anything).
