### ISSUE TITLE
"Did you mean" mentions identifiers that are not in scope

### ISSUE THREAD

**Issue by mechvel** [agda/agda#4578]
If ``does`` is forgotten to import, the error message  mentions 
```
Dec.does, Relation.Nullary.does, ...
```
But the module ``Dec`` does not exist in the source root.

**Comment by andreasabel** [comment]
A MWE would be good here.

**Comment by UlfNorell** [comment]
I'm guessing `Dec` is a submodule (or datatype module) and that `Dec.does` *is* in scope. Reopen with test case if this in not the case.
