### ISSUE TITLE
In a macro, reducing a term in Setω produces a spurious constraint

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#4585]
Minimal example:
```agda
open import Agda.Builtin.Unit
open import Agda.Builtin.List
open import Agda.Builtin.Reflection

id : ∀ {a} {A : Set a} → A → A
id x = x

macro
  my-macro : Term → TC ⊤
  my-macro goal = bindTC
    (getType (quote id))
    λ idType → bindTC
      (reduce idType)
      λ _ → returnTC _

fails? : ⊤
fails? = my-macro
```
This produces an unsolved (and unsolvable) constraint:
```
Failed to solve the following constraints:
  Has bigger sort: Agda.Primitive.Setω
```
It would be nice to be able to reduce types in `Setω` (and do other reflection stuff to them), so I wonder if we could get rid of this constraint.

Related issue: https://github.com/agda/agda/issues/2119

**Comment by nad** [comment]
I encountered the same problem today. When I use the reflection machinery I tend to reduce types and terms before pattern-matching on them, but this fails for types of the form `{a : Level} → …`.
