### ISSUE TITLE
Github agda highlighting 'abstract' in names incorrectly

### ISSUE THREAD

**Issue by ajrouvoet** [agda/agda#4587]
I have no idea how the github highlighting of Agda works, and if anyone is interested in trying to fix this.
But the highlighting of 'abstract' when it is not a keyword is very confusing at first glance. My first instinct was that a space somehow got misrendered.

![image](https://user-images.githubusercontent.com/475738/79337495-e6bec180-7f25-11ea-83b2-b9604aa15817.png)

**Comment by MatthewDaggitt** [comment]
The syntax highlighting is done via https://github.com/agda/agda-github-syntax-highlighting. Best to open an issue on there I think.

**Comment by gallais** [comment]
Note that we can transfer issues between repos of the same organisation.
The magic link is in the RHS column, at the very bottom.

**Comment by ajrouvoet** [comment]
I've added the 'abstract' keyword issue to an existing issue on that repository for 'pattern'. But good to know.
