### ISSUE TITLE
Release nightly builds

### ISSUE THREAD

**Issue by L-TChen** [agda/agda#4589]
Following the discussion in #4328, I created a scheduled workflow script to release nightly builds with the default optimisation flags. ~Due to a bug of GHC, the nightly build for  Windows is still built with `--fast` (see below).~ A ghc bug preventing Agda from compiling remains unsolved but it still complies without `--fast` if ghc tries to compile after failing.

Here are some issues I found so far:

- [ ] ~The installation script introduced in https://github.com/agda/agda/pull/4243 puts Agda to `/usr/bin`, but I guess `/usr/local/bin` or `~/bin` are more popular locations. An interactive script might be better.~ A system-wide installation for a nightly build does not seem a good idea.

- [x] ~macOS 10.14 enforces notarization for all apps including  CLI apps. It is still possible to run nightly builds on macOS, but the user needs to go to "Security & Privacy" to authorise and click "OK" twice in total. I will check how to notarize an app, but if anyone knows how to do it please go ahead.~ By removing extended attributes `xattr -c`, the verification simply goes away. (Now I worries about the security issue on macOS ...) 

- [x] Stack with GHC 8.8.2 (or 8.10.1) on Windows is unable to compile Agda without `--fast`. This is currently blocked by https://github.com/agda/agda/issues/4543.

**Note that** I only checked the nightly builds for macOS.

**Comment by gallais** [comment]
Are all the people watching the repo going to get one notification per day
for this nightly release? Is it possible to turn that off?

![Notification](https://i.imgur.com/mFLdkVi.png)

**Comment by L-TChen** [comment]
Oops, it is pretty noisy. I don’t know how to turn it off.

By the way. the nightly build is not really built every night but every time the new commit on `master` changing the codebase passes all test suites.

**Comment by L-TChen** [comment]
It is not possible to unsubscribe these notifications :(

See https://github.community/t/stop-receiving-email-notification-about-new-prerelease/14170.
