### ISSUE TITLE
[wiki] Agda IRC logs down

### ISSUE THREAD

**Issue by ajrouvoet** [agda/agda#4592]
Not sure where to put this issue:

The wiki refers to http://agda.orangesquash.org.uk/2019/ for the Agda freenode IRC logs. This site seems to be down. It would be nice if logs of this channel are available.

**Comment by andreasabel** [comment]
Seems like the chat has moved to https://gitter.im/agda/agda

**Comment by gallais** [comment]
There are definitely still people on IRC.

**Comment by ajrouvoet** [comment]
I wasn't aware of the gitter. Bit of a shame that the community is split that way. I think I recall having seem some instances where IRC and gitter where synced to some extent. Would that be an idea?

There is at least a way to connect to a gitter channel using IRC (https://gitlab.com/gitlab-org/gitter/irc-bridge), but it might not be ideal to give up on freenode; there is certainly still a community out there that is worthwhile connecting to.

**Comment by andreasabel** [comment]
I do not know who maintains  http://agda.orangesquash.org.uk .  This issue should be raised with the maintainer.

**Comment by ajrouvoet** [comment]
Does anyone know? If not, perhaps it would be good/possible to host a reliable log on the same infrastructure as other community resources (mailinlist, wiki, etc..)?

**Comment by nad** [comment]
@iainlane.

**Comment by andreasabel** [comment]
No action has been suggested or committed to.  Closing.  Feel free to reopen should there be further desire for discussion.
