### ISSUE TITLE
The blocking machinery seems to be broken

### ISSUE THREAD

**Issue by nad** [agda/agda#4593]
I tried to figure out why one of my tactics is slow. Here is an example run for one call to the tactic:
* The tactic blocks on meta-variable _29.
* The tactic blocks on meta-variable _64.
* The tactic blocks on meta-variable _64 again. Is this a bug?
* The tactic blocks on meta-variable _40.
* The tactic does not block. Apparently the goal is solved. However, for some reason the tactic is restarted again.
* The tactic blocks on meta-variable _64 for the third time.
* The tactic blocks on meta-variable _63.
* The tactic blocks on meta-variable _64 for the fourth time.

Is the blocking machinery broken?

**Comment by nad** [comment]
I can reproduce the problem by running the following commands:
```
git clone --single-branch --branch Agda-issue-4593 https://github.com/nad/equality.git
cd equality
agda src/Tactic/By/Poor-performance.agda
```

**Comment by dylanede** [comment]
Does `commitTC` help at all?

**Comment by nad** [comment]
I don't think the tactic is responsible for solving the meta-variables, so I doubt that `commitTC` would make any difference in this case. Quick testing suggests that it doesn't.

**Comment by UlfNorell** [comment]
I suspect the repeated blocking on `_64` is because that meta is created during the tactic invokation. In that case we pick (arbitrarily) another meta to block on:

https://github.com/agda/agda/blob/faca04a71eca18ac5fba9857adc523f72b34c359/src/full/Agda/TypeChecking/Rules/Term.hs#L1331-L1345

The state is rolled back, so it's not surprising that you get the same meta id on subsequent calls.

I can't explain why it would restart the tactic once it's completed successfully. Are you sure this is what happens?

**Comment by nad** [comment]
> I suspect the repeated blocking on `_64` is because that meta is created during the tactic invokation. In that case we pick (arbitrarily) another meta to block on:

I just optimised my tactic (for some test cases) by blocking on the last meta instead of the first one, because the last meta tends to be solved later than the first one. Perhaps Agda could use the same heuristic.

> I can't explain why it would restart the tactic once it's completed successfully. Are you sure this is what happens?

The tactic succeeds, and in the later invocations debug printing indicates that it does not invoke `unify`.

**Comment by UlfNorell** [comment]
> I just optimised my tactic (for some test cases) by blocking on the last meta instead of the first one, because the last meta tends to be solved later than the first one. Perhaps Agda could use the same heuristic.

In what situation?

> The tactic succeeds, and in the later invocations debug printing indicates that it does not invoke `unify`.

What's the significance of `unify` not being called? Did you expect it to call it?

**Comment by nad** [comment]
> In what situation?

The code you quoted includes `firstMeta`, perhaps this could be changed to `lastMeta`.

> What's the significance of `unify` not being called? Did you expect it to call it?

The tactic solves the goal by unifying it with a term constructed by the tactic.

**Comment by UlfNorell** [comment]
I think it would help if you could articulate what the actual problem is here. The tactic is called when it's not supposed to be, but it doesn't execute all the way to the end?

**Comment by nad** [comment]
The tactic is called eight times, and at most one of those calls (the fifth) is successful, all the others block. Furthermore at least one invocation is successful, because the goal is solved. Thus my conclusion is that the tactic is called three times after it has completed successfully.

I also note that the tactic does not find unsolved meta-variables in the fifth invocation, but it does find at least one unsolved meta-variable in the final three invocations.

**Comment by nad** [comment]
> I suspect the repeated blocking on `_64` is because that meta is created during the tactic invokation. In that case we pick (arbitrarily) another meta to block on:

Debug printing suggests that the `Nothing` branch is not taken.

**Comment by UlfNorell** [comment]
The culprit here is instance search. If you look at the debug output you can see that the monad argument to `Monad.Raw-monad._⟨$⟩_ ` is different for each problematic invokation. I filed #4777 for discussing this problem and possible solutions.
