### ISSUE TITLE
Improve the blocking primitive

### ISSUE THREAD

**Issue by nad** [agda/agda#4594]
I tried to figure out why one of my tactics is slow. Here is an example run for one call to the tactic:
* The tactic is given the following term (well, this term is part of what you get if you reduce the goal type):
  ```agda
  Monad.Raw-monad._⟨$⟩_ {equivalence-relation⁺} {equality-with-J}
  {lzero} {lzero} {_52 h hyp xs} (_53 h hyp xs) {ℕ} {ℕ} suc
  (_59 h hyp xs)
  ```
  The tactic blocks on meta-variable `_52`.
* The tactic is given the following term:
  ```agda
  Monad.Raw-monad._⟨$⟩_ {equivalence-relation⁺} {equality-with-J}
  {lzero} {lzero} {λ v → _78 v} (_53 h hyp xs) {ℕ} {ℕ} suc
  (_59 h hyp xs)
  ```
  The tactic blocks on meta-variable `_78`. Note that `_52` seems to have been η-expanded to `λ v → _78 v`.
* The tactic is given the following term:
  ```agda
  Monad.Raw-monad._⟨$⟩_ {equivalence-relation⁺} {equality-with-J}
  {lzero} {lzero} {Maybe {lzero}}
  (Maybe.raw-monad {equivalence-relation⁺} equality-with-J {lzero})
  {ℕ} {ℕ} suc (_59 h hyp xs)
  ```
  The tactic blocks on meta-variable `_59`. Note that this meta-variable was part of the first term mentioned above.
* Finally the tactic is given a term without meta-variables, and completes successfully.

It seems wasteful for the tactic to repeatedly reduce and traverse the input in this way. Some suggestions for improvement:
* Make it possible to block on a set (list) of meta-variables. The tactic could traverse the first term and block on three meta-variables, `_52`, `_53` and `_59`. The tactic should not be restarted until all of these meta-variables have been solved.
* Make it possible to block "transitively", so that the tactic does not restart until the meta-variables have been solved, any meta-variables in the solutions have been solved, and so on.
* Make it possible to block until a specific term (like the goal type) does not contain any unsolved meta-variables (transitively).

**Comment by nad** [comment]
I can reproduce the problem by running the following commands:
```
git clone --single-branch --branch Agda-issue-4594 https://github.com/nad/equality.git
cd equality
agda src/Tactic/By/Poor-performance.agda
```

**Comment by jespercockx** [comment]
Yes, it would be great to improve the blocking machinery to be able to block on multiple metavariables at the same time.

> Make it possible to block on a set (list) of meta-variables. The tactic could traverse the first term and block on three meta-variables, _52, _53 and _59. The tactic should not be restarted until all of these meta-variables have been solved.

I've previously also needed to do the dual to this, i.e. block until *at least one* of a list of metavariables is solved (I believe this is needed for rewriting).

**Comment by nad** [comment]
We could perhaps borrow some ideas from the work on Tog.

**Comment by jespercockx** [comment]
Is the design of Tog written down somewhere?

**Comment by nad** [comment]
I'm leaving this question to @vlopezj.

**Comment by vlopezj** [comment]
@jespercockx The general idea is described in my licentiate thesis draft. 
Here is a PDF with the relevant pages: [constraint-blockers.pdf](https://github.com/agda/agda/files/4487344/constraint-blockers.pdf)

In the implementation, disjunctions of metavariables, and disjunctions of constants are  represented as bitsets. A pair of these is a `Guard`. Unblockers (called `Blockers`) in the implementation are a free lattice over those. Whether an unblocker unblocks is implemented as the function `shouldAttempt`, which acts recursively on the unblocker. The setup seems to work fast enough in our tests, but we haven't benchmarked different implementation choices.

The implementation details are in [Tog.Unify.Common](https://framagit.org/vlopez/togt/-/blob/master/src/Tog/Unify/Common/Scheduler.hs), where `Blockers` are implemented, [Tog.Term.Core](https://framagit.org/vlopez/togt/-/blob/master/src/Tog/Term/Core.hs), where Guard is implemented; and [Tog.Unify.Class](https://framagit.org/vlopez/togt/-/blob/master/src/Tog/Unify/Class.hs), where `shouldAttempt` is implemented.

**Comment by jespercockx** [comment]
Thanks, that looks like a sensible design. I'm looking forward to read the full text when it is finished.

If I were to implement Agda again from scratch, I would try to seperate out the constraint machinery for solving and postponing in a separate module that is parametric in the representation of terms and constraints as well as the methods to solve them. Currently the logic for postponing and resuming stuff is spread around all parts of the code, and it seems like this would reduce complexity of the remaining code by a lot and make the actual algorithms simpler to follow. Such a generic constraint solving framework could even be exposed through the reflection API so tactics can plug in their own constraints as well.

Edit: After looking a bit at the code for Tog, it seems that this is the same idea as what you're doing. Is that correct? Would it be possible to plug in the actual representation of Agda terms into Tog's machinery?

**Comment by nad** [comment]
@vlopezj, did you see the question above?

**Comment by vlopezj** [comment]
@nad: Thanks for the heads up.
@jespercockx: I missed your question… It seems that GitHub does not send an e-mail notification for edits, regardless of their extent :/
Yes, it should be possible to use the same machinery as it is parameterize on the term type and the constraint type. However, the Haskell type of unblockers and the code that checks whether they unblock *does* depend on the Haskell types of metavariables, declaration names, etc. The unblockers must be generated by the constraint solving code itself.
Changing the postponing machinery could also affect performance, as the order in which constraints are solved might not be the same as in the current Agda implementation.

**Comment by jespercockx** [comment]
@UlfNorell any chance the new fine-grained blocking will be exposed to the reflection API for the next release? I assume not, so I'll bump this to 2.6.3. Feel free to unbump if I'm wrong.
