### ISSUE TITLE
Should Setω be a type?

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#4595]
I'm starting to reconsider my answer I gave to the question by @nad in https://github.com/agda/agda/pull/4579#issuecomment-613371249. It used to be the case that `Setω` was a valid *sort*, but not a valid *type*. This would mean that 
```
  quoteωTC : ∀ {A : Setω} → A → TC Term
```
is not a valid type signature, since the type `∀ {A : Setω} → A → TC Term` cannot be assigned a sort. But apparently current Agda accepts definitions like this, so it seems we have (intentionally or unintentionally) moved to a situation where `Setω` is a valid type but not a valid term. However, this change has not yet been fully propagated, see for example https://github.com/agda/agda/issues/4109 and https://github.com/agda/agda/issues/4585.

So this leads to my question: should we further roll out this change officially and make `Setω` a valid type, or should we roll back this change and move back to the old situation? I'm personally in favour of the former, as `Setω` has many usecases especially when writing reflection-based code. However, introducing it as a type would also mean making `univSort Setω` into a valid sort (but not a valid type), which means someone might be here again next month or year with another issue to make *that* into a valid type.

One thing I *do* know is that we should make a conscious decision rather than letting things evolve organically, as this only leads to issues where something is a valid type in some cases, but not in others.

**Comment by jespercockx** [comment]
See also https://github.com/agda/agda/issues/1151 and https://github.com/agda/agda/issues/2119 for more cases where having `Setω` as a type would be useful.

**Comment by gallais** [comment]
Also allows to write module interfaces as records (as long as they themselves do
not use `Setω`).

**Comment by jespercockx** [comment]
> Also allows to write module interfaces as records (as long as they themselves do
> not use `Setω`).

Yes, this was the point of #1151 I think.

**Comment by jespercockx** [comment]
On the following program:
```agda
{-# OPTIONS -v tc:50 #-}

open import Agda.Primitive

test : Setω
test = ∀ {ℓ} → Set ℓ
```
Agda reports
```
...
checked type signature test : Setω of sort  univSort Setω
...
```
so it seems that at least in some places `univSort Setω` is already accepted as a valid sort (or rather, in the general spirit of Agda, it is not explicitly ruled out).

**Comment by andreasabel** [comment]
The next natural border is `Set2ω`:
1. We can start by adding `Setω`, `Setω 1`, `Setω 2`, ...
2. This naturally generalizes to `Setω l` for `l : Level`.
3. At some point someone wants `forall l -> Setω l`.
4. Thus `Set2ω` is born.
5. Which needs a type... :-)

More seriously, I think we should implement only step 1 and then wait.

**Comment by jespercockx** [comment]
Why not move straight up to `Setε0`?

**Comment by jespercockx** [comment]
On a more serious note: having one polymorphic hierarchy (indexed by a type of finite `Level`s) and one non-polymorphic hierarchy on top indeed seems like it could be a reasonable sweet-spot between simplicity and expressivity.

**Comment by AndrasKovacs** [comment]
What about having `ω²` universes, which could be canonically represented with a pair of `Nat`-s as `Set(i*ω+j)`? The current `Set_i` could be shorthand for `Set(0, i)`. I think this gives us lots of universes for a relatively small extra complexity of representation. I don't know though what additional complications could arise in unification. 

(I've personally only encountered situations where I wanted `Set(ω+1)` and maybe `Set(ω+2)` as well, when formalizing things related to type theories with `ω` universes. )

**Comment by jespercockx** [comment]
One thing I like about having one polymorphic + one non-polymorphic hierarchy is that it is the smallest extension of current Agda where both `piSort` and `univSort` are totally defined functions on sorts (currently `piSort` is total but `univSort Setω` is not defined). This would allow us to get rid of the "Has bigger sort" constraint. I honestly do not see any use-cases for universes beyond that.

**Comment by andreasabel** [comment]
@jespercockx 
> Why not move straight up to Setε0?

You want to deal with the ordinal notations for ε0  (Cantor normal forms)?  Seems like quite some overkill...

@AndrasKovacs 
> What about having ω² universes

Let's wait for applications before going there.  We could also have omega^omega...

The rational behind 2ω is that this is the minimal ordinal where we have 
1. quantification over the levels in ω,
2. each sort has a sort.

**Comment by jespercockx** [comment]
> > 
> 
> You want to deal with the ordinal notations for ε0 (Cantor normal forms)? Seems like quite some overkill...

This was an attempt at humor, if it wasn't clear. Making jokes on the internet is hard...

**Comment by gallais** [comment]
> You want to deal with the ordinal notations for ε0 (Cantor normal forms)? Seems like quite some overkill...

Just dump the content of @fredrikNordvallForsberg's recent paper in `Agda/Primitive/`

https://arxiv.org/abs/1904.10759

**Comment by zraffer** [comment]
It's greate. Very greate. It's even working! Now we can compile all old `omega-in-omega` proofs in safe (?) mode. Thank you. `ε0` (if were implemented) would allow smooth and consistent level polymorphism for levels behind `ω`. By the costs of solver sofistications.
