### ISSUE TITLE
Keyword 'auto'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#460]
Add a new keyword 'auto' to Agda.  It will run Agsy on the current goal.
```agda
lemma : proposition
lemma = ... auto ...   --- solve subgoal automatically, but do not put result into source code
```

Original issue reported on code.google.com by `andreas....@gmail.com` on 16 Sep 2011 at 1:42

**Comment by andreasabel** [comment]
It seems pointless to keep this issue open for another 6 years. :)
A solution to this issue would involve some caching of solutions found by agsy.  And a reliable, specified Agsy.

**Comment by ice1000** [comment]
I think it refers to using `_`s

**Comment by ice1000** [comment]
> I think it refers to using _s

It's not. `_` solves goals by unifier, while agsy is a separated tool
