### ISSUE TITLE
What is a large time spent in Typing.TypeSig a symptom of?

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda#4601]
In `Categories.Enriched.NaturalTransformation`, there is a single definition, `UnderlyingNT` that takes the bulk of the typechecking time for that file.  And the bulk of that, 12s out of 16s spent in typechecking, is allocated to `Typing.TypeSig` in the profile.

I have tried to read the code to understand what that indicates, to no avail.  If I comment out that one definition, that whole file then checks very fast.

[Agda 2.6.1 on MacOS]

**Comment by nad** [comment]
https://github.com/agda/agda/blob/faca04a71eca18ac5fba9857adc523f72b34c359/src/full/Agda/TypeChecking/Rules/Decl.hs#L772-L782

**Comment by JacquesCarette** [comment]
Yes, I had found that code.  And that it must be `checkAxiom'` that is taking that time, as that seems to be the only thing `checkTypeSignature'` calls. But in reading that code (https://github.com/agda/agda/blob/faca04a71eca18ac5fba9857adc523f72b34c359/src/full/Agda/TypeChecking/Rules/Decl.hs#L565) it's still not clear where the time is spent.  I did also output `tc.decl.ax` to witness that the time does seem to happen in
https://github.com/agda/agda/blob/faca04a71eca18ac5fba9857adc523f72b34c359/src/full/Agda/TypeChecking/Rules/Decl.hs#L596-L601
My case is where `gentel` is `Nothing`.

By looking at the output, I can't see any difference between that definition's signature (`UnderlyingNT`) from the others around it that would cause a big difference. And I wasn't sure where **next** to go chasing things down (`isType_`? `workOnTypes` ?  something else I'm not seeing?)

**Comment by nad** [comment]
I'm guessing that a lot of time is spent checking some type signature. Can you confirm that by replacing the definition's body with a hole?

**Comment by JacquesCarette** [comment]
Yes.  If I replace that single definition's body with a hole, I get
```
Checking Categories.Enriched.NaturalTransformation (/Users/carette/agda-categories/src/Categories/Enriched/NaturalTransformation.agda).
Total                        22,125ms           
Miscellaneous                   358ms           
Typing                          386ms (14,490ms)
Typing.TypeSig               11,331ms           
Typing.CheckRHS               2,516ms           
Typing.OccursCheck              244ms           
Typing.CheckLHS                  11ms           
Deserialization               5,714ms  (6,320ms)
Deserialization.Compaction      606ms           
Import                          327ms           
Positivity                      183ms           
DeadCode                        174ms           
Parsing                          44ms     (99ms)
Parsing.OperatorsExpr            53ms           
Serialization                     0ms     (75ms)
Serialization.BuildInterface     75ms           
Scoping                          38ms     (60ms)
Scoping.InverseScopeLookup       21ms           
Coverage                         23ms           
Highlighting                     12ms           
Accumulated statistics
max-open-constraints     0
metas                2,428
```
That's a nice number of metas, isn't it?

Within noise levels of timing measurements, that's the same as the hole filled
```
Total                        22,908ms           
Miscellaneous                   342ms           
Typing                          389ms (14,555ms)
Typing.TypeSig               11,149ms           
Typing.CheckRHS               2,611ms           
Typing.OccursCheck              393ms           
Typing.CheckLHS                  11ms           
Deserialization               5,757ms  (6,386ms)
Deserialization.Compaction      629ms           
Serialization                   488ms    (686ms)
Serialization.BinaryEncode       88ms           
Serialization.BuildInterface     83ms           
Serialization.Compress           16ms           
Import                          352ms           
Positivity                      193ms           
DeadCode                        181ms           
Parsing                          50ms    (110ms)
Parsing.OperatorsExpr            58ms           
Scoping                          58ms     (73ms)
Scoping.InverseScopeLookup       14ms           
Coverage                         24ms           
Highlighting                     12ms           
Accumulated statistics
A.Name  (fresh)       1,249
A.QName  (fresh)        950
Double  (fresh)          13
Integer  (fresh)          3
Node  (fresh)        39,118
Shared Term  (fresh)      0
String  (fresh)         525
Text  (fresh)             1
max-open-constraints      0
metas                 2,742
pointers  (fresh)         0
```
and wildly different than the same file with just that one definition commented out
```
Total                        11,858ms          
Miscellaneous                   394ms          
Deserialization               5,785ms (6,408ms)
Deserialization.Compaction      622ms          
Typing                          353ms (3,129ms)
Typing.CheckRHS               2,348ms          
Typing.OccursCheck              249ms          
Typing.TypeSig                  167ms          
Typing.CheckLHS                  10ms          
Serialization                   450ms   (622ms)
Serialization.BinaryEncode       76ms          
Serialization.BuildInterface     74ms          
Serialization.Compress           10ms          
Serialization.Sort               10ms          
DeadCode                        460ms          
Positivity                      342ms          
Import                          309ms          
Parsing                          44ms   (101ms)
Parsing.OperatorsExpr            55ms          
Scoping                          42ms    (54ms)
Scoping.InverseScopeLookup       12ms          
Coverage                         24ms          
Highlighting                     10ms          
Accumulated statistics
A.Name  (fresh)       1,217
A.QName  (fresh)        931
Double  (fresh)          13
Integer  (fresh)          3
Node  (fresh)        35,945
Shared Term  (fresh)      0
String  (fresh)         521
Text  (fresh)             1
max-open-constraints      0
metas                 2,368
pointers  (fresh)         0
```

So, as the name indicates, checking that one signature takes a huge amount of time. But I don't really see what makes that signature really different than others.

**Comment by gallais** [comment]
> But I don't really see what makes that signature really different than others.

Have you tried passing the implicit `C` & `D` arguments of type `Category` explicitly?

**Comment by JacquesCarette** [comment]
What I did try was to un-embed `UnderlyingNT` from the anonymous module, forcing me to make everything explicit.  That didn't change anything.

**Comment by JacquesCarette** [comment]
Ok, I found what it was: figuring out what all the implicits needed to be (which were mostly all `Level`s). When I give them by hand, that 11,000ms goes down to 150ms. I have to give pretty much all of them.

If there were some kind of agda profile setting that would make it clear what unification problems are 'hard' (like there are settings to see the positivity problems), that would make tracking these things down a lot easier.

**Comment by Saizan** [comment]
@JacquesCarette What settings are there for the positivity problems? specific verbosity flags?

**Comment by JacquesCarette** [comment]
"-v tc.pos:5" is helpful.  Looking through the Agda sources for `reportSDoc` and `reportSLn` is a very helpful way to discover all sorts of verbosity flags. Careful though, the output can get huge very very fast.  I had a file that took 11s to process that too 90minutes to run (and produced 21Megs of output) when I asked for too much verbosity!
