### ISSUE TITLE
Do not highlight projection functions in expressions as fields

### ISSUE THREAD

**Issue by nad** [agda/agda#4604]
Now (presumably due to #4574) lots of identifiers in my code which used to be highlighted as functions are highlighted as fields. I don't think it is helpful to highlight projection functions in expressions as fields, it just makes the code harder to read. However, perhaps it makes sense to highlight copatterns as fields.

I suggest that by default projection functions in expressions (postfix or not) are highlighted in the same way as regular functions, and that copatterns are highlighted as fields. It might make sense to introduce one or more new highlighting categories, so that users have the opportunity to, say, highlight postfix projection functions differently from "regular" ones.

**Comment by andreasabel** [comment]
This regression was not intended, I have to have a look at this.
From https://github.com/agda/agda/pull/4574#issuecomment-613422422 :
```agda
record R : Set₁ where
  field
    A : Set

postulate
  r : R

open R r

r₁ : R
r₁ = record { A = A }

r₂ : R
r₂ = record { A = R.A r }
```

**Comment by nad** [comment]
Note that my suggestion is not simply to fix the regression, but to make things better. If we take the example above, previously the expressions `A` and `R.A` where highlighted differently, but I think they should be highlighted in the same way.

**Comment by andreasabel** [comment]
> I don't think it is helpful to highlight projection functions in expressions as fields, it just makes the code harder to read.

Here, I wonder why?  In the same league, we should not highlight constructors in expressions as such...

**Comment by nad** [comment]
Consider the following proof:
![subst-subst-sym](https://user-images.githubusercontent.com/293222/79591356-af444680-80d8-11ea-8ed4-6daf57b3b284.png)
It is almost like someone randomly chose one of the colours blue and pink for each name, and I find it distracting.

Record fields and data type constructors tend to be used rather differently, so I do not want to extrapolate this observation to constructors. If it turns out that this is an issue also for constructors, then we could address that problem later.

**Comment by andreasabel** [comment]
These would all be blue if the regression was fixed.  They are not actually projection _functions_ but values coming from fields, and I agree that these should not be colored like projections.

The case of projections would arise if you kept the equality structure `Eq` visible, having expressions like `Eq .== x y` and `Eq .sym x==y` etc.

**Comment by andreasabel** [comment]
@nad, please check if highlighting is ok again.

**Comment by nad** [comment]
A quick check suggests that the regression may have been fixed.
