### ISSUE TITLE
The combination of Cubical Agda with inductive families is logically inconsistent

### ISSUE THREAD

**Issue by amp12** [agda/agda#4606]
As the following example shows, the cubical mode of the current version (2.6.1) of Agda allows a proof of falsity :-(

```agda
{-# OPTIONS --cubical #-}

module cubical-bug where

open import Cubical.Core.Everything
open import Cubical.Foundations.Prelude

----------------------------------------------------------------------
-- Well-Founded Recursion
----------------------------------------------------------------------
data Acc {A : Set}(R : A → A → Set)(x : A) : Set where
  acc : (∀ y → R y x → Acc R y) → Acc R x

iswf : {A : Set}(R : A → A → Set) → Set
iswf R = ∀ x → Acc R x

----------------------------------------------------------------------
-- A logical contradiction
----------------------------------------------------------------------
data A : Set where
  O : A
  S : A → A
  E : ∀ x → S x ≡ x

data _<_ (x : A) : A → Set where
  <S : x < S x

O<O : O < O
O<O = transport (cong (O <_) (E O)) <S

-- Given that O < O holds, we should not be able to prove that < is 
-- well-founded, but we can!
iswf< : iswf _<_
iswf< i = acc (α i)
  where
  α : ∀ x y → y < x → Acc _<_ y
 -- I don't think the following clause should pass 
 -- the termination checker
  α .(S y) y <S = acc (α y) 

data ⊥ : Set where

AccO→⊥ : Acc _<_ O → ⊥
AccO→⊥ (acc f) = AccO→⊥ (f O O<O)

contradiction : ⊥
contradiction = AccO→⊥ (iswf< O)
```

**Comment by andreasabel** [comment]
It seems that not only indexed hits are problematic, but also inductive types indexed on hits.  If you spell out type `_<_`, it becomes:
```agda
data _<_ (x y : A) : Set where
  <S : S x ≡ y → x < y
```
With this elaboration, you cannot fool the termination checker.

A brute fix for this issue would be to turn off the use of dot patterns for termination certification, maybe not only for `--cubical`, but also `--without-K`.

**Comment by nad** [comment]
The code in the OP uses inductive families as well as cubical features. I think there is some work under way to add proper support for inductive families to Cubical Agda (#3733). I wonder if the problem still exists in that setting.

**Comment by Saizan** [comment]
I should be able to test it out this week, but the generated clause to address #3733 should not have `.(S y)` as a dot pattern, since you could see it as an automated version of the transformation @andreasabel proposed. That way the termination checker should not have a reason to believe `y` is smaller than `x`.

**Comment by andreasabel** [comment]
My hunch was that computed dot-patterns are no longer unique with QITs and HITs, so they should not be counted toward termination.  However, this is a naive perspective.

@Saizan Do you say that @jespercockx 's _pattern matching without K_ needs to be updated when there is an equation at a type that is a HIT?

**Comment by jespercockx** [comment]
Dot patterns computed by unification are unique up to definitional equality, even with `--without-K` and/or `--cubical`. However, the theory of pattern matching in my papers does *not* support recursion on dot patterns, so if you are looking for a culprit that's where I'd look.

**Comment by Saizan** [comment]
@andreasabel The way I am approaching this is to extend _Elaborating dependent (co)pattern matching_ to handle constructors other than `refl`.

@jespercockx 's (and others) work shows how to turn the unification rules into (well-behaved) equivalences, but if you assume you only need to handle `refl` most of the equivalence is not actually needed.

For `--cubical` I have to make more use of the equivalence, exactly because we can't assume some arguments get refined as a definitional equality.

I can work out what `α` would get elaborated to, if you'd like.

**Comment by andreasabel** [comment]
@Saizan : I can wait until you are done.  Should there be a need to turn off dot-pattern-termination for cubical, it is very easy to do this; just skip this second pass:
https://github.com/agda/agda/blob/c0b4c610f81b1e0a37616a3869cbe9adf3a322d0/src/full/Agda/Termination/TermCheck.hs#L247-L251

**Comment by andreasabel** [comment]
@Saizan : I see you settled for the solution to disable dot-pattern termination.

**Comment by Saizan** [comment]
@andreasabel Yeah, no point having the termination checker try again with dot patterns only to discover they will not help.
