### ISSUE TITLE
Records without constructors cannot be instances.  Why?

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#4608]
One can declare a record constructor an instance, but only if it has a name.
```agda
record R (A : Set) : Set where
  instance constructor r
  field
    {{a}} : A
```
Logically, there is no reason why a name is mandatory, is there?  The nameless record constructor `\ x -> record { a = x }` could be used during instance search.  (Internally, each record has a named constructor, but some of these names are unutterable.)
We could have
```agda
record R (A : Set) : Set where
  instance
  field
    {{a}} : A
```
(which currently warns about empty instance block).

I wonder whether `instance constructor` isn't anyway an obsolete fringe feature.  In the standard library I found null uses.  In the test suite, I find the sole use for records without fields.
```agda
record Unit : Set where
  instance constructor tt
```
But this is pointless since such a record has eta and needs no instance search for its inhabitant.

Any sensible uses?

**Comment by jespercockx** [comment]
Note that the `instance` keyword for the `tt` constructor is no longer optional. From the 2.6.0 release notes (https://github.com/agda/agda/blob/master/doc/release-notes/2.6.0.md):

> Instance arguments that are already solved by conversion checking are no longer ignored by instance search. Thus the constructor of the unit type must now be explicitly be declared as an instance in order to be considered by instance search:
> ```
>   record ⊤ : Set where
>     instance constructor tt
> ```

I do not know about other sensible uses, but I do not see why `instance` should not be allowed for a record constructor either.

**Comment by jespercockx** [comment]
Two more points:
- It is not surprising that there are no uses of `instance constructor` in the standard library since it uses almost no instances to begin with.
- The lone `instance` syntax you propose looks like you are making the *fields* into instances, which is probably not intended. If you really want to add syntax for an anonymous instance constructor, I propose `instance constructor` by itself.

**Comment by UlfNorell** [comment]
I would argue against allowing unnamed instance constructors. There are a number of issues where people are asking for ways to limit the scope of instances, and it's not clear how you would go about importing a record type, but not it's unnamed instance constructor. Of course, some syntax could be devised, but this really does not seem like it would be worth it.

**Comment by andreasabel** [comment]
> Instance arguments that are already solved by conversion checking are no longer ignored by instance search.

Ah, interesting.  Does this mean that eta-equality is not interleaved with instance search?  I do not fully understand what "no longer ignored by instance search" means.  One interpretation would be that eta is not used to solve/advance instance problems.

**Comment by andreasabel** [comment]
> and it's not clear how you would go about importing a record type, but not it's unnamed instance constructor.

Yeah, this makes sense.

**Comment by jespercockx** [comment]
> > Instance arguments that are already solved by conversion checking are no longer ignored by instance search.
> 
> Ah, interesting. Does this mean that eta-equality is not interleaved with instance search? I do not fully understand what "no longer ignored by instance search" means. One interpretation would be that eta is not used to solve/advance instance problems.

It means that even if the instance meta has already been solved by eta-expansion or unification, Agda will still run the instance search algorithm and check that the solution found by instance search agrees with it. In particular you still get a "no instance found" error for an instance meta that's solved by eta-expansion.

**Comment by andreasabel** [comment]
> It means that even if the instance meta has already been solved by eta-expansion or unification, Agda will still run the instance search algorithm and check that the solution found by instance search agrees with it. In particular you still get a "no instance found" error for an instance meta that's solved by eta-expansion.

Ah, interesting.  What is the rationale behind that?  If something can be solved by eta-expansion, then the solution is unique, isn't it?  Why also require instance search to succeed?

**Comment by jespercockx** [comment]
Because the specification of instance search is that there should be a unique *instance* in scope. Hence if there is no instance, it would be misleading to not report an error.

**Comment by andreasabel** [comment]
> Because the specification of instance search is that there should be a unique _instance_ in scope. Hence if there is no instance, it would be misleading to not report an error.

Ok.  My intuition would be that there is a unique solution given instances and unification.  We lack a unified theory of these two solvers yet, though.  But this should be the goal, otherwise instance search will be a playground for smart hacks.
