### ISSUE TITLE
Why does this hole cause an error?

### ISSUE THREAD

**Issue by masaeedu** [agda/agda#4614]
Hello. I'm a Haskell programmer trying to learn Agda. One common pattern I use in Haskell is to write a function piece by piece using holes. So I might start by writing a function like this:

```haskell
foo :: Bool -> Nat
foo b = _
```

The inferred type of the hole is reported to me as `_ :: Nat`. Now presumably I need to do something with the `b` argument to obtain the final result. So I take `b` and apply the hole to it.

```haskell
foo :: Bool -> Nat
foo b = _ b
```

Now the hole is `Bool -> Nat` (which is rather silly in this example, because it is the overall type of the function). Maybe I have a function `bar :: Bool -> String` in scope that I know is the next step, so the next expression I have is:

```haskell
bar :: Bool -> String

foo :: Bool -> Nat
foo b = _ (bar b)
```

For which the hole has type `String -> Nat`. And so on. I just keep processing the argument until the overall hole is `Nat -> Nat`, at which point I am done.

---

When I try an analogous approach in Agda:

```agda
data bool : Set
  where
  true : bool
  false : bool

data nat : Set
  where
  zero : nat
  succ : nat → nat

foo : bool → nat
foo b = ? b
```

I get the following error in the "metas" window:

```
?0 : _99
Sort _98  [ at /mnt/data/depot/git/agda/experiments/naryapplicatives/naryapplicative.agda:70,9-12 ]
_99 : _98  [ at /mnt/data/depot/git/agda/experiments/naryapplicatives/naryapplicative.agda:70,9-12 ]
_102 : nat  [ at /mnt/data/depot/git/agda/experiments/naryapplicatives/naryapplicative.agda:70,9-12 ]

———— Errors ————————————————————————————————————————————————
Failed to solve the following constraints:
  _101 := (_ : _99) [b] :? nat
```

I discussed this a bit at functionalprogramming.slack.com with @TOTBWF and @gallais \*. They pointed out that if we substitute implicit function application with either the dependently typed or non-dependently-typed function application operators (`$` or `$'`), the compiler no longer complains:

```agda
-- non-dependently typed function application
_$_ : ∀ { κ ℓ } { a : Set κ } { b : Set ℓ } → (a → b) → a → b
f $ v = f v

foo : bool -> nat
foo b = ? $ b
```

With the snippet above, the metas window now reports something similar to Haskell:

```
?0 : bool → nat
```

Would it be possible to make implicit function application of a hole to an argument "just work", or maybe just explain to me why it is not sensible to expect it to work like in Haskell?

---

\* Unfortunately I didn't really understand all of what @TOTBWF and @gallais were discussing, hopefully they can add their thoughts to this issue.

**Comment by jespercockx** [comment]
The reason for this behaviour is that Agda doesn't know whether the function you will give in the hole takes any implicit arguments or not. For example, this solution is accepted by Agda:
```agda

T : bool → Set
T true = bool
T false = nat

bar : {x : bool} → bool → T x
bar {x = true}  b = true
bar {x = false} b = zero

foo : bool → nat
foo b = bar b
```
Here the hole is filled with a function of type `{x : bool} → bool → T x`, not `bool → nat`. So if Agda were to decide that the type must be `bool → nat` in advance, then this would rule out this solution without a good reason.

**Comment by gallais** [comment]
> then this would rule out this solution without a good reason.

It would rule out `bar` but not `bar {false}` which is what the solution
ultimately is. So I am not sure I understand this statement.

**Comment by jespercockx** [comment]
Hmm, you're right. However, the implicit argument could also come *after* the explicit one, so we would have:
```agda
bar : bool → {x : bool} → T x
bar b {x = true}  = true
bar b {x = false} = zero

foo : bool → nat
foo b = bar b
```
Still, Agda should maybe be able to figure out at least that the hole should be something of a function type taking one explicit argument of type `bool`, even if it doesn't know the return type yet.

**Comment by andreasabel** [comment]
Agda does not speculate on how many implicit arguments and unknown in function position has.  Thus, the piecewise refinement approach described in the OP does not work.

> Would it be possible to make implicit function application of a hole to an argument "just work"

Something more could be done if we had first-class telescopes.  But this would be a major innovation.

**Comment by nad** [comment]
One way to do this kind of thing in Agda is to build up the expression inside the hole. For instance, you can write `bar b` inside the hole and ask Agda to infer its type.

Given that there is already a way to do this I don't see the point of working hard to support the method discussed in the OP.
