### ISSUE TITLE
Enable --no-sort-comparison by default?

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#4615]
> I think morally the correct thing to do is to always use `--no-sort-comparison`, but since this is a big change I imagine it would lead to quite a few failing test cases at first.

_Originally posted by @jespercockx in https://github.com/agda/agda/issues/4345#issuecomment-575572806_

This would also likely solve https://github.com/agda/agda/issues/4265, and maybe improve performance as well.

**Comment by jespercockx** [comment]
Currently this leads to the following error in `Data.List.Membership.Propositional` in the standard library:
```
_ℓ_45 : Agda.Primitive.Level  [ at /home/jesper/agda/std-lib/src/Data/List/Membership/Propositional.agda:32,42-47 ]
_P_46 : A → Set _ℓ_45  [ at /home/jesper/agda/std-lib/src/Data/List/Membership/Propositional.agda:32,48-49 ]

———— Errors ————————————————————————————————————————————————
Failed to solve the following constraints:
  P x =< _P_46 x
  _P_46 y =< P y
```

**Comment by jespercockx** [comment]
It is kind of suspicious that these constraints are not solved with `--no-sort-comparison`, since (without cumulativity) there is no subtyping at universes so they should really be solved directly.

**Comment by jespercockx** [comment]
I am trying to understand why certain files fail to typecheck with `--no-sort-comparison`. Here is the smallest example I've been able to come up with so far:
```agda

open import Agda.Primitive

postulate
  A : Set
  B : A → Set

  S : (l : Level) (P : A → Set l) → Set l
  p : (l : Level) (P : A → Set l) (x : A) → P x → S l P

  I : (l : Level) (P : A → Set l) → S l P → S l P → Set l

module _ (x₁ x₂ : A) (y₁ : B x₁) (y₂ : B x₂) where

  foo = I _l _P (p _l _P x₁ y₁) (p _l _P x₂ y₂)
    where
      _l : Level
      _l = _

      _P : A → Set _l
      _P z = _
```
This checks fine without any flags, but with `--no-sort-comparison` it produces unsolved constraints:
```
_18 : Level  [ at ...:21,12-13 ]
_20 : Set (_18 (x₁ = x₁) (x₂ = x₂) (y₁ = y₁) (y₂ = y₂))  [ at ...:24,14-15 ]

———— Errors ————————————————————————————————————————————————
Failed to solve the following constraints:
  B x₂ =< _20 (z = x₂)
  B x₁ =< _20 (z = x₁)
```
These constraints are left unsolved because of a non-linearity: in the constraint `B x₁ =< _20 (z = x₁)`, the metavariable `_20` depends twice on `x₁`: once explicitly and once implicitly through the context. So while I understand why these constraints are not solved with `--no-sort-comparison`, I *don't* see how Agda manages to solve them without this flag. Does anyone have an explanation?

**Comment by jespercockx** [comment]
After thinking about it some more, I may have an idea of how Agda solves this: the constraint `B x₁ =< _20 (z = x₁)` cannot be solved directly, however attempting to solve it teaches Agda that whatever the solution of `_20` might be, it will *not* depend on `x₂` since `x₂` does not appear in `B x₁`. So Agda can prune away the dependency of `_20` on `x₂`, which removes the non-linearity in the *other* constraint and makes it solvable. Could someone with a better understanding of the pruning machinery say whether this is indeed how things are supposed to work (@andreasabel or @UlfNorell)? Because then I can try to investigate why this pruning fails when `--no-sort-comparison` is enabled.

**Comment by UlfNorell** [comment]
That sounds plausible.

**Comment by jespercockx** [comment]
I think I finally understand the problem: Agda *does* try to prune the metavariable, but it is blocked from doing so because the *type* of the metavariable still contains the unsolved level `_l` which still depends on the variable we want to prune. Under Agda's default behaviour `_l` gets solved to `lzero` by the sort comparison, but with `--no-sort-comparison` this does not happen and thus the whole constraint is blocked.

To fix this, we should move the check on the sort of type-metas (which is only used for `--no-sort-comparison`) to *before* the occurs check, since this way the extra information from the type of the solution can also be used for pruning. This seems to fix my toy example at least, I'm now compiling Agda properly so I can see if it also fixes the standard library with `--no-sort-comparison`.

**Comment by jespercockx** [comment]
With this change I now managed to get the standard library to pass using `--no-sort-comparison`. It has a small positive effect on typechecking performance: time went down from 329,664ms to 322,921ms (about 2%). It might just be noise, though. Still, it feels that the behaviour of `--no-sort-comparison` is morally the right thing to do. I'll make a PR and see what people have to say.

**Comment by jespercockx** [comment]
I tried enabling it by default but while the standard library passes, the test suite still gives me trouble. Specifically:

- `test/Succeed/Issue2650` gives an unsolved constraint (something to do with cubical that I don't understand)
- `test/Succeed/Issue3695` variable generalization fails
- `test/Fail/Issue1428` succeeds unexpectedly, but since that issue is actually still open I think it is mostly unrelated (#1428)
- `test/Interaction/Issue731` produces a bunch of duplicate constraints `Set1 = _2`, which is weird
- A few other error messages have changed, but the new errors still seem to make sense.

I'll push the improvements to `--no-sort-comparison` I've made but I'll leave turning it on by default for when these issues have been resolved.

**Comment by Saizan** [comment]
The `Issue2650` failure is likely due to the use of `piApplyM'` in the `sort check on type metas` logic.

We should have a `piOrPathApplyM'` equivalent.

**Comment by jespercockx** [comment]
Is there any situation where we want to use `piApplyM` but we do *not* want to include path types? If not, it would be better to simply update the implementation of `piApplyM`.

**Comment by Saizan** [comment]
The only danger is that it would forget the information about the path boundary, which is often relevant but not here. To be fair so far I have mostly found `telView` calls need to updated to do something with the boundary.

**Comment by jespercockx** [comment]
`piApplyM` already loses information (the type of the domain) so I don't really see why this should be different for path types.

**Comment by jespercockx** [comment]
The issues with cubical have been solved, thanks @Saizan !

However, there is still one more test that fails coming from the Latex/HTML tests. Here's a minimized version:

```agda
open import Agda.Primitive
open import Agda.Builtin.Nat

Type : (i : Level) -> Set (lsuc i)
Type i = Set i

postulate
  P : (i : Level) (A : Type i) → A → Type i

postulate
  lemma : (a : Nat) -> P _ _ a
```

With `--no-sort-comparison`, Agda manages to find out that the second underscore must be `Nat`, but **not** that the first underscore must be `lzero`.

**Comment by Saizan** [comment]
Funny, it seems that some constraint gets dropped, because filling the underscore with some different level does rise an error.

One would expect that comparing sorts is not needed here, as the constraint should be clear just by the type of the second underscore.

**Comment by jespercockx** [comment]
Ah, I found the problem: https://github.com/agda/agda/blob/3a688b0fbc5a40d44bf5cf6123e309e218a0ac9f/src/full/Agda/TypeChecking/MetaVars.hs#L677-L690

This code checks that the solution of a metavariable has the right type, but only when the type of that metavariable is a sort. The rationale for this is that the conversion checker keeps the invariant that it always compares terms of the same type, except when comparing types themselves. So when we come to the instantiation of a metavariable, we only need to check that the solution has the correct type if it is a type-level metavariable.

However, the way the code detects type-level metavariables is by checking if the type of the meta is syntactically a sort, which is not the case for `Type i`. It should be easily fixable by instead making use of `ifIsSort`.
