### ISSUE TITLE
Type error `l0 != lzero` when l0 is defined as `l0 = lzero`

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#4618]
This behaviour is very confusing to me. Found while trying to minimize an example for #4615.
```agda
open import Agda.Primitive

postulate
  A : Set
  B : A → Set

  S : (l : Level) (P : A → Set l) → Set l
  p : (l : Level) (P : A → Set l) → S l P

  I : S lzero B → Set

l0 : Level

postulate
  foo : I (p l0 B)

l0 = lzero
```
Error message:
```
Set != (Set l0)
when checking that the expression B has type A → Set l0
```
EDIT: minimized the example a bit further.

**Comment by jespercockx** [comment]
It looks like this is just https://github.com/agda/agda/issues/1113 again ...

**Comment by jespercockx** [comment]
However, even defining `l0` first does not fix the problem:
```agda

mutual
  l0 : Level
  l0 = _

  postulate
    foo : I (p l0 B)
```
gives the same error still.

@andreasabel could this have something to do with the new automatic reordering of mutual blocks?

**Comment by nad** [comment]
> the new automatic reordering of mutual blocks?

What does this refer to?

**Comment by jespercockx** [comment]
https://github.com/agda/agda/issues/3246, and specifically the new reordering of declarations in mutual blocks implemented in https://github.com/agda/agda/commit/5ffac504f5a83d881013e333758bb096c010d44a#diff-0b7e48bb5afea395722b5d68912f2064R1491-R1588

**Comment by andreasabel** [comment]
Why is this confusing?  It is just how type-checking of mutual blocks is specified: first the type signatures, then the implementations.  And yes, it is #1113.
If you remove the `mutual` keyword, it should check fine.

**Comment by jespercockx** [comment]
No, if I remove the mutual keyword then the metavar gets frozen before Agda starts to check `foo`, so I am left with unsolved metas (and unsolved constraints).

**Comment by andreasabel** [comment]
Oh sorry, indeed.  That is why there is also the fake mutual block technique:
```agda
MUTUAL : Set1

l0 : Level
l0 = _

postulate foo : I (p l0 B)

MUTUAL = Set
```

**Comment by andreasabel** [comment]
This can be perfected:
```agda
data Begin : Set where
  End : Begin

Mutual : Begin

foo 
bar

Mutual = End
```
I should file a patent on how to make a mutual block in Agda when things are actually not mutual. :D

**Comment by jespercockx** [comment]
Well, it seems I have to brush up my fake-mutual-block technique. I think we can close this issue then. I just want to put it on record that I am not happy with the current situation of #1113 (but I don't have a concrete proposal, which is why I haven't reopened it yet).

**Comment by andreasabel** [comment]
Disclaimer:  The fake `Mutual = End` might not end the mutual block if there are pending unsatisfied type signatures...

**Comment by andreasabel** [comment]
Maybe we have now the tools to address #1113 using the `NotBlocked MissingClauses` interpretation for type signatures like `l0` whose definition we have not seen yet, or add a new `NotBlocked` alternative, @jespercockx ?

**Comment by jespercockx** [comment]
The issue in #1113 is not that it is impossible or even hard to fix, it is that relying on later clauses leads to "insanely dependent" types, and we do not have a good way to rule those out as far as I know.
