### ISSUE TITLE
Installation failure, hGetContents: invalid argument

### ISSUE THREAD

**Issue by vincent-prz** [agda/agda#4625]
Trying to install agda via
```
cabal update
cabal install Agda
agda-mode setup
```

But the `cabal install Agda` command fails with this error:

```
Failed to build boxes-0.1.5.
Build log (
/home/vincent/.cabal/logs/ghc-8.8.3/boxes-0.1.5-40a7e6da2f575e928aaa126d95505f0e7a57faaeab1b52e915d60186e0b9bddd.log
):
Configuring library for boxes-0.1.5..
Preprocessing library for boxes-0.1.5..
Building library for boxes-0.1.5..
[1 of 1] Compiling Text.PrettyPrint.Boxes ( Text/PrettyPrint/Boxes.hs, dist/build/Text/PrettyPrint/Boxes.o )

Text/PrettyPrint/Boxes.hs:104:1: error:
/home/vincent/.cabal/logs/ghc-8.8.3/boxes-0.1.5-40a7e6da2f575e928aaa126d95505f0e7a57faaeab1b52e915d60186e0b9bddd.log: hGetContents: invalid argument (invalid byte seque
nce)
```

Does someone have a fix for this? Thanks.
OS: Arch linux
cabal version: 3.0.0.0

**Comment by gallais** [comment]
What's in the `.log` file?

**Comment by vincent-prz** [comment]
```
Text/PrettyPrint/Boxes.hs:104:1: error:
    Could not find module ‘Data.List.Split’
    There are files missing in the ‘split-0.2.3.4’ package,
    try running 'ghc-pkg check'.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
    |
104 | import Data.List.Split (chunksOf)
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Not sure yet what to make of this, the `split` package seems installed, but there seem to be some missing files.

**Comment by gallais** [comment]
I have seen similar issues on github actions for other haskell projects.
I don't know why and how packages end up broken like this. :/


If I were you I would run `ghc-pkg check` as suggested and see whether it
suggests a way to fix the issue. If not you could always try to reinstall
`split` by using something like `cabal install --reinstall split-0.2.3.4`
(you may even need to pass `--force-reinstalls` but a priori `cabal` is
helpful in suggesting adding these kind of extra flags if needed).

**Comment by vincent-prz** [comment]
Thanks for your help. I've tried the above, with no luck. Then I tried to install agda via `stack`, and it seemed to work. But then when trying to compile a file,I got this error:
```
MAlonzo/RTE.hs:11:1: error:
    Could not find module ‘Numeric.IEEE’
    There are files missing in the ‘ieee754-0.8.0’ package,
    try running 'ghc-pkg check'.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
11 | import Numeric.IEEE ( IEEE(identicalIEEE) )
```

**Comment by nad** [comment]
See #3619.

**Comment by vincent-prz** [comment]
Thanks. Running `cabal install ieee754` or `stack install ieee754` doesn't solve the problem. Running `cabal v2-install --lib Agda ieee754` brings me back to the initial problem. I suspect my cabal setup is broken somehow ...

**Comment by asr** [comment]
Why is the output of `cabal install split-0.2.3.4`?

**Comment by gallais** [comment]
May be of interest to you @vincent-prz: https://github.com/haskell/cabal/issues/5913#issuecomment-468990043

**Comment by nad** [comment]
> I suspect my cabal setup is broken somehow ...

Perhaps you could delete everything and start from scratch.

**Comment by nad** [comment]
Related: #4627.

**Comment by vincent-prz** [comment]
> Why is the output of cabal install split-0.2.3.4?

No particular output.

> May be of interest to you @vincent-prz: [haskell/cabal#5913 (comment)](https://github.com/haskell/cabal/issues/5913#issuecomment-468990043)

Indeed @gallais ! So the problem is that I seem to only have a dynamic build of the `ieee754` library (This seems to be Arch specific). Hence I am able to compile by providing the flag `--ghc-flag=-dynamic` to Agda:
```
agda --ghc-flag=-dynamic --compile <agda_file>
```

Do you think it might make sense to add this in the documentation for Arch users ?

Thanks for the help folks.
