### ISSUE TITLE
Cannot pass ghc flags via emacs variable `agda2-program-args`

### ISSUE THREAD

**Issue by vincent-prz** [agda/agda#4630]
I am getting a similar issue as https://github.com/agda/agda/issues/3235, but creating a new one since it was closed.

I am trying to pass a `--ghc-flag=-dynamic` argument, but getting `Unrecognized option: --ghc-flag=-dynamic` when compiling in Emacs (while in works on the CLI).

Here is my emacs conf (I'm using Spacemacs):
```elisp
     (agda :variables
           agda2-backend "GHC"
           agda2-program-args '("--ghc-flag=-dynamic")
     )
```
Agda version: 2.5.4.2

**Comment by andreasabel** [comment]
See my reply in #3235, this issue was fixed in Agda 2.6.0.
