### ISSUE TITLE
Non-linear patterns handled in a buggy way

### ISSUE THREAD

**Issue by EdNutting** [agda/agda#4631]
Hi,

I get an internal error from this line.

https://github.com/agda/agda/blob/077b5ef1bac2e14b4b5657ef9632db29597c11d6/src/full/Agda/TypeChecking/Records.hs#L611

when code of the following form is used:

```agda
record SomeRecord0 : Set₁ where
  constructor someRecord0
  field
    f1 : Set
    f2 : Set

record SomeRecord1 : Set₁ where
  constructor someRecord1
  field
    f1 : SomeRecord0
    f2 : Set

someFunction1 : SomeRecord1 → Set
someFunction1 f1@(someRecord1 f1 f2) = ?
```

This should result in a simple naming error, not an internal error. 

In the following simpler case, the name error is correctly produced:

```agda
someFunction0 : SomeRecord0 → Set
someFunction0 f1@(someRecord0 f1 f2) = ?
```

**Comment by andreasabel** [comment]
This seems to be a twofold regression.
`@`-patterns are first supported in 2.5.2 which (as 2.5.3) complains about
```
Repeated variables in pattern: f1
when scope checking the left-hand side
someFunction1 f1@(someRecord1 f1 f2)
```
This seems the right behavior.

In 2.5.4, the definition is accepted without complained (regression I).

From 2.6.0, we get the internal error (regression II).

**Comment by andreasabel** [comment]
The scope checker for as-pattern seems broken.  It does not resolve the as-name, but takes the user at face-value that it is a fresh bound variable.  For instance, the following is accepted:
```agda
open import Agda.Builtin.Bool

test : Set → Set
test true@A = true
```
Seems like the fix of #3147 did not go far enough.

**Comment by andreasabel** [comment]
The OP can be simplified to this:
```agda
record R0 : Set₁ where
  constructor c0
  field f0 : Set

record R1 : Set₁ where
  constructor c1
  field f1 : R0

test : R1 → Set₁
test x@(c1 x) = Set
```
The field names are irrelevant, the problem is the duplicate use of pattern variable `x`.

> Seems like the fix of #3147 did not go far enough.

Actually, pattern linearity is no longer established in the scope checker since @jespercockx 's restructuring of the LHS checker.  It think what Agda is instead trying to do is to check whether the equality `x = c1 x` holds, but then it chokes because `x` has both type `R0` (inner use) and `R1` (outer use).  It tries to eta-expand `c1 x` at the wrong type `R0` which gives `c0...` and it crashes since the constructors are different, which is deemed impossible.

**Comment by andreasabel** [comment]
@jespercockx What is done to prevent ambiguous typing from non-linearity in the LHS checker?
(over to you)

**Comment by andreasabel** [comment]
Interesting is also that Agda swallows the following without complaint:
```agda
record ⊤ : Set where

data D : Set where
  c : D → ⊤ → D  -- If I reverse the two arguments, Agda complains.

test : D → Set
test (c x x) = D
```
It seems to check that the two de Bruijn indices are equal at type `⊤`, which succeeds.

**Comment by jespercockx** [comment]
I can fix the issue by adding an extra check that the types of the two occurrences of a variable are equal. However, the error message you get from this is perhaps not the best:
```
R0 != R1
when checking the clause left hand side
test x@(c1 x)
```
I'm starting to think that perhaps this feature of allowing non-linear variables when all but one can be dot patterns was not the greatest of my ideas. It does help to avoid having to write a dot in some cases, but (1) it looks weird to people familiar with pattern-matching syntax in other languages and (2) it leads to significantly worse error messages on repeated pattern variables. So perhaps in hindsight, avoiding one or two dots was not worth the price (and you can always write `_` when that's too much work). Is there anyone opposed to the removal of this feature?

**Comment by gallais** [comment]
You could check single patterns for linearity in `x` when we have `x@p`.
Are there any cases where we can write `x@p` and have `x` show up in `p`
without a term being infinite (except for `p = x`)?

Edit: oh, hadn't seen Andreas' example that does not involve `@`.

**Comment by andreasabel** [comment]
>  the error message you get from this is perhaps not the best:
> 
> ```
> R0 != R1
> when checking the clause left hand side
> test x@(c1 x)
> ```

It could be improved by a new `Call` form that will print as
```
when checking that all occurrences of pattern variable x have the same type
```

> Is there anyone opposed to the removal of this feature?

Not me, but we should get a feel for the breakage of user code if we row back here.  (People might have removed dots in the belief of progress and may be frustrated to have to undo this.)

+ The advantage of the feature is that the user does not have to make the decision where to place the dot.
- The disadvantage is that linearity is more complicated, since it is now semantic rather than syntactic. E.g., this is fine (albeit useless) as `x = true` in both cases.
```agda
open import Agda.Builtin.Bool

test : Bool → Bool → Bool
test x@true x@true = x
test _ _ = false
```

@jespercockx 
> but (1) it looks weird to people familiar with pattern-matching syntax in other languages

Why do you think that?

**Comment by nad** [comment]
Is the idea to allow shadowing in patterns, or to turn this into some kind of error?

**Comment by jespercockx** [comment]
> > but (1) it looks weird to people familiar with pattern-matching syntax in other languages
> 
> Why do you think that?

People might think there is an actual conversion check happening during matching to check that the two `x`s are equal, which is not the case.

> Is the idea to allow shadowing in patterns, or to turn this into some kind of error?

The example in the OP should definitely be an error, the only question is whether this error should be thrown during scope checking or during type checking.

**Comment by andreasabel** [comment]
> People might think there is an actual conversion check happening during matching to check that the two `x`s are equal, which is not the case.

Well, this check does happen, statically.  Thus, it is redundant dynamically.  There is no confusion for the reader of a program.  The writer of a program may wonder why a definition is rejected, but can look up the documentation.

Some rewriting tools may have non-linear matching, but is there a programming language that has this feature?

**Comment by jespercockx** [comment]
> Some rewriting tools may have non-linear matching, but is there a programming language that has this feature?

Not really. You have convinced me that it might be better to keep this feature and add the missing check that the types are equal, and also add "... when checking that all occurrences of pattern variable x have the same type" and "... when checking that all occurrences of pattern variable x are forced to be equal by typing" to the error message.
