### ISSUE TITLE
Pattern inconsistency?

### ISSUE THREAD

**Issue by martinescardo** [agda/agda#4632]
I am not sure whether this is an issue or my misunderstanding.

Consider the following, which works:

```agda
data _≡_ {ℓ} {X : Set ℓ} : X → X → Set ℓ where
  refl : {x : X} → x ≡ x

pattern reflp x = refl {x}
pattern reflv x = refl {_} {_} {x}

J : ∀ {i j} (X : Set i) (A : (x y : X) → x ≡ y → Set j)
  → ((x : X) → A x x (reflv x))
  → (x y : X) (p : x ≡ y) → A x y p
J X A f x x (reflp x) = f x
```

The idea is to make the argument of refl explicit if we wish, via the pattern definition.

However, the definitions behave differently "as patterns" and "as values". For instance, the following doesn't work:

```agda
J : ∀ {i j} (X : Set i) (A : (x y : X) → x ≡ y → Set j)
  → ((x : X) → A x x (reflp x))  -- error here
  → (x y : X) (p : x ≡ y) → A x y p
J X A f x x (reflp x) = f x
```

This doesn't work either:

```agda
J : ∀ {i j} (X : Set i) (A : (x y : X) → x ≡ y → Set j)
  → ((x : X) → A x x (reflv x))
  → (x y : X) (p : x ≡ y) → A x y p
J X A f x x (reflv x) = f x -- error here
```

It would be desirable to have a definition that works both as a pattern and as a value. Is that possible? (I have a concrete situation where this is needed, to integrate two different developments so that some of their independent definitions are definitionally equivalent and hence each development can use the other (to some extent).)

**Comment by gallais** [comment]
Note that you can use a named implicit and it will work in both situations:

```agda
pattern refln x = refl {x = x}
```

I suspect it's a problem between parameters vs. indices. You can see the
same thing with lists: patterns on the left cannot bind the `A` parameter.

```agda
open import Agda.Builtin.List

id : {A : Set} → List A → List A
id ([] {A}) = ? -- Too many arguments to constructor []
```

**Comment by martinescardo** [comment]
Excellent idea. I will try this!

**Comment by martinescardo** [comment]
Fantastic. It works exactly as I wanted. 40k + 8k lines of code now live harmoniously. Thanks!
