### ISSUE TITLE
agda2-mode.el: better interact with undo in evil mode

### ISSUE THREAD

**Issue by iblech** [agda/agda#4635]
I'm using agda2-mode together with evil, to have standard Vi keybindings available. This combination works beautifully.

However, `C-c C-l` and similar commands do not break the undo sequence. Right now, the behavior is as follows:

1. Enter insert mode with `i`.
2. Enjoy Agda, using `C-c C-l` and similar commands repeatedly.
3. Exit insert mode with `ESC`.
4. Press `u` for undo.
5. All the Agda code entered since step 1 vanishes.

The expected behavior is:

5. Only the Agda code entered since the last `C-c C-l` command vanishes/resets to how it looked like before.

I think we want to call `evil-execute-in-normal-state` just before executing the body of `agda2-load` or similar, of course only if evil is loaded and activated. This should have the effect that `C-c C-l` becomes `C-o C-c C-l`, hence adding a new entry to the undo stack.

I'm not familiar with Emacs programming, but if people are interested I might try to work on this. Of course a patch should be as non-intrusive to `agda2-mode.el` as possible.

**Comment by nad** [comment]
I am reluctant towards changing the Emacs mode to support this kind of extension, because it might make it harder to maintain the Emacs mode. Can't you set up your own key bindings that do what you want?

**Comment by iblech** [comment]
Sure, I could, but then this improvement won't reach other users of emacs+evil+agda. :-) (I'm on a quest to simplify the user experience of Agda for newcomers. I argue that fixing this issue will be a (very small) step in that direction.)

But in any case this issue should really not be considered to be important. I certainly don't mind if this issue is closed without a fix. :-) I'm hoping that a fix will add just one function to agda2-mode.el and a couple of easy calls of this function, not complicating the control flow.

**Comment by guillaumebrunerie** [comment]
@iblech Did you investigate how other Emacs modes deal with this issue? For instance when compiling instead of `C-c C-l`, or something similar.

**Comment by iblech** [comment]
Good question, @guillaumebrunerie! I'm afraid it didn't occur to me, as I'm using Emacs exclusively for Agda development.

I did now. When compiling C files, the same issue arises.

Hence one could very well argue that this issue should be solved by modifications to evil-mode, as it affects more than one language. However it's not clear to me that it's possible to fix this issue in evil-mode. Also I guess the situation with Agda is a little bit different than with C, because the Agda experience is very tightly linked with agda2-mode, while the coupling between C and its editors, tools and frameworks is much looser.

**Comment by nad** [comment]
Are you sure that the behaviour that you observe is not the intended one? There seems to be a variable called `evil-want-fine-undo` that you can customise to change the behaviour of the undo command.

**Comment by iblech** [comment]
Okay, `(setq evil-want-fine-undo 't)` does most of what I had in mind. It's not perfect but definitely good enough :-) Sorry for letting this issue linger for so long!
