### ISSUE TITLE
Erased constructors

### ISSUE THREAD

**Issue by nad** [agda/agda#4638]
Perhaps it makes sense to support erased constructors. The idea would be that they can only be used in erased contexts, and that if one matches on an erased constructor, then the right-hand side of the clause is treated as erased.

Here is an example of how this feature could be used:
```agda
data ∥_∥ (A : Set a) : Set a where
  ∣_∣        : A → ∥ A ∥
  @0 trivial : Is-proposition ∥ A ∥

rec : @0 Is-proposition B → (A → B) → ∥ A ∥ → B
rec p f ∣ x ∣           = f x
rec p f (trivial x y i) = p (rec p f x) (rec p f y) i
```
If we ignore the issue of how to compile Cubical Agda code (with or without erasure), does this make sense? Is there any way in which the code in the right-hand side of the final clause above could leak into a non-erased context?

**Comment by UlfNorell** [comment]
Are you thinking this would only be for higher constructors? I don't see how it would make sense for point constructors.

**Comment by nad** [comment]
I haven't thought of any use cases for point constructors. Are you suggesting that we should only implement this feature for higher constructors?

**Comment by UlfNorell** [comment]
I'm saying I'm not sure what it means for point constructors.

**Comment by nad** [comment]
The constructors would only be allowed in erased contexts, and run-time terms would only contain non-erased constructors. (At least that is the idea.) Note that higher constructors can be used as point constructors by applying them to one or more elements of the interval.

One question is whether something like the following should be allowed:
```agda
data D : Set where
  run-time        : D
  @0 compile-time : D → D

f : @0 D → D
f run-time         = run-time
f (compile-time x) = compile-time (f x)
```

**Comment by Saizan** [comment]
It would be nice if we knew how to interpret these in the realizability models of QTT.

It could be something like `!_0 a |= compile-time d <=> a |= d`, with a tuple instead of a single "a" if the constructor has more arguments.

By the way, you would want the erased constructors to show up even for non-erased function spaces, because `f` might be called in an erased context.

e.g. you do need the `compile-time` clause even in a definition like this:
```
f : D → D
f run-time         = run-time
f (compile-time x) = compile-time (f x)
```

**Comment by andreasabel** [comment]
Parsing of erased constructors is already supported, a starting point for this issue would be to remove the restriction here: https://github.com/agda/agda/blob/adfc12d40aeb149cb0cd4e2546047b4fff60c463/src/full/Agda/TypeChecking/Rules/Data.hs#L212-L215

The check whether using an erased constructor is legal should go here, probably:
https://github.com/agda/agda/blob/adfc12d40aeb149cb0cd4e2546047b4fff60c463/src/full/Agda/TypeChecking/Rules/Application.hs#L778-L792

The LHS checker already stores information about the modality of the clause:
https://github.com/agda/agda/blob/adfc12d40aeb149cb0cd4e2546047b4fff60c463/src/full/Agda/TypeChecking/Rules/LHS/Problem.hs#L231-L235

The splitter already has the facility of setting the modality of the pattern vars.  We only need to integrate the modality of the constructor here, and set the modality of the target:
https://github.com/agda/agda/blob/adfc12d40aeb149cb0cd4e2546047b4fff60c463/src/full/Agda/TypeChecking/Rules/LHS.hs#L1223-L1226

**Comment by Saizan** [comment]
I would say that the following definition should be allowed: 

```agda
h : D → @0 D → D
h run-time  d       = run-time
h (compile-time x) run-time = ?
h (compile-time x) (compile-time d) = ?
```

but this requires extending the coverage checker.

**Comment by andreasabel** [comment]
> but this requires extending the coverage checker.

In what sense?  Isn't this a covering definition anyway?
UPDATE: Ah, I see, splitting on an erased argument should be allowed if the clause is compile-time only.

**Comment by andreasabel** [comment]
Concerning the coverage checker:  The `SplitClause` has field `scTarget` which contains a modality.  However, the `Maybe` is a bit worrying; we have to make sure this information is always available. https://github.com/agda/agda/blob/adfc12d40aeb149cb0cd4e2546047b4fff60c463/src/full/Agda/TypeChecking/Coverage.hs#L101-L104
The `fixTargetType` could update the modality:
https://github.com/agda/agda/blob/adfc12d40aeb149cb0cd4e2546047b4fff60c463/src/full/Agda/TypeChecking/Coverage.hs#L1409-L1411
The check for `erased` should then include the information of the target type.
https://github.com/agda/agda/blob/adfc12d40aeb149cb0cd4e2546047b4fff60c463/src/full/Agda/TypeChecking/Coverage.hs#L1427

**Comment by Saizan** [comment]
It seems that there should be special case about `Quantityω` here, since `ω <> 1 = ω` but we do not want `ω` in envModality.

https://github.com/agda/agda/blob/adfc12d40aeb149cb0cd4e2546047b4fff60c463/src/full/Agda/TypeChecking/Irrelevance.hs#L193-L198

**Comment by nad** [comment]
Now we have a first prototype that "works". I think we should consider the following improvements:
* Fix #4727.
* Add `--omit-unreachable-code` (#4733).
* Refuse to compile the program if any code reachable from `main` uses unsupported features (if we are not in `--safe` mode we could emit a warning). Note that GHC currently complains when compiling a pattern involving a higher constructor.

**Comment by nad** [comment]
> I haven't thought of any use cases for point constructors.

I may have found a use case for erased point constructors. Here is a variant of the sequential colimit used by @fpvandoorn in [Constructing the Propositional Truncation using Non-recursive HITs](https://arxiv.org/abs/1512.02274):
```agda
data Colimitᴱ
       (P₀ : Set p₀)
       (@0 P₊ : ℕ → Set p₊)
       (@0 step₀ : P₀ → P₊ zero)
       (@0 step₊ : ∀ {n} → P₊ n → P₊ (suc n)) :
       Set (p₀ ⊔ p₊) where
  ∣_∣₀       : P₀ → Colimitᴱ P₀ P₊ step₀ step₊
  @0 ∣_∣₊    : P₊ n → Colimitᴱ P₀ P₊ step₀ step₊
  @0 ∣∣₊≡∣∣₀ : (x : P₀) → ∣ step₀ x ∣₊ ≡ ∣ x ∣₀
  @0 ∣∣₊≡∣∣₊ : (x : P₊ n) → ∣ step₊ x ∣₊ ≡ ∣ x ∣₊
```
I've constructed a variant of the propositional truncation operator using this colimit:
```agda
∥_∥ᴱ : Set a → Set a
∥ A ∥ᴱ = Colimitᴱ A … … …
```
I could prove that this operator is pointwise equivalent (with erased proofs) to the following one:
```agda
data ∥_∥ᴱ (A : Set a) : Set a where
  ∣_∣                          : A → ∥ A ∥ᴱ
  @0 truncation-is-proposition : Is-proposition ∥ A ∥ᴱ
```

**Comment by nad** [comment]
@Saizan, your commit 7cbb67e97067b2420a63c2a22d8029add0e57813 broke the test case for #2918. You wrote that inlining of recursive pattern-matching lambdas "caused the compiler to loop". Do you recall under what circumstances this happened? Could we allow inlining in more cases?

**Comment by nad** [comment]
> I would say that the following definition should be allowed:
> 
> ```agda
> h : D → @0 D → D
> h run-time  d       = run-time
> h (compile-time x) run-time = ?
> h (compile-time x) (compile-time d) = ?
> ```
> 
> but this requires extending the coverage checker.

I guess this has been taken care of, that kind of code seems to be accepted now.

**Comment by nad** [comment]
>     * Refuse to compile the program if any code reachable from `main` uses unsupported features (if we are not in `--safe` mode we could emit a warning). Note that GHC currently complains when compiling a pattern involving a higher constructor.

Now the GHC and JS backends complain if you try to compile higher inductive types or (at least some) cubical primitives.

**Comment by nad** [comment]
TODO: Documentation.

**Comment by nad** [comment]
I noticed that the JS backend generates code for erased constructors. For instance, consider the following Agda code:
```agda
{-# OPTIONS --without-K --safe #-}

data D : Set where
  run-time        : D
  @0 compile-time : D

f : @0 D → D
f compile-time = compile-time
f run-time     = run-time
```
The JS backend generates the following code for `D`:
```javascript
exports["D"] = {};
exports["D"]["run-time"] = a => a["run-time"]();
exports["D"]["compile-time"] = a => a["compile-time"]();
```
The code for `f` seems to be correct:
```javascript
exports["f"] = a => agdaRTS.primSeq(a,exports["D"]["run-time"]);
```

**Comment by andreasabel** [comment]
I'll look into the JS compilation issue.

**Comment by andreasabel** [comment]
Done.

**Comment by nad** [comment]
The following code is accepted:
```agda
data D : Set where
  @0 c : D

f : @0 D → D
f c = c

x : D
x = f c
```
There is no reasonable way to compile `x`. I think the problem is that Agda currently treats the right-hand side as erased if there is a match on an erased constructor in an *erased* position.

**Comment by Saizan** [comment]
Yeah, if the argument is erased then erased constructors shouldn't make the RHS an erased position, good catch.

**Comment by nad** [comment]
I may have fixed this problem, but I found another one. Consider the following code:
```agda
data D : Set where
  c₁    : D
  @0 c₂ : D

f : @0 D → D
f c₁ = c₁
f c₂ = c₁
```
This code should not be allowed: both `f c₁` and `f c₂` are valid applications.

**Comment by nad** [comment]
Here is another problem:
```agda
open import Agda.Builtin.Bool

data D : Set where
  @0 c : D

f : @0 D → Bool
f c = true
```
This code can be allowed, but the GHC backend generates the following code:
```haskell
name2 = "Test3.D"
d2 = ()
data T2
name6 = "Test3.f"
d6 :: T2 -> Bool
d6 = erased
```
The function `d6` should return something corresponding to `true`. I guess the problem is that the GHC backend removes the clause because of the match on the erased constructor.
