### ISSUE TITLE
Fixity problem when importing with renaming directive

### ISSUE THREAD

**Issue by pnlph** [agda/agda#4641]
I am trying to rename two operators and use them without round brackets.

This code works:
```agda
open import Agda.Builtin.Equality using (_≡_ ; refl)
open import Agda.Builtin.Nat using (_+_ ; _*_)
-- Reminder: _+_ has infix 6 and _*_ has infix 7
_ : 5 + 6 * 7 ≡ 47
_ = refl
```
and allows avoid round brackets and writing `5 + 6 * 7` instead `5 + (6 * 7)`

But this other code does not work:
```agda
open import Agda.Builtin.Nat renaming (_+_ to plus ; _*_ to times)
_ : plus 5 times 6 7 ≡ 47
_ = refl
```
So it is not possible to write `plus 5 times 6 7` instead `plus 5 (times 6 7)`

Should not renaming preserve the fixity when nothing is specified in the `renaming` directive? See #4538

Error:
```
(Nat → Nat → Nat) !=< Nat
when checking that the expression times has type Nat
```

**Comment by gallais** [comment]
Fixities only makes sense for mixfix operators. Here your new names are usual
identifiers and cannot take advantage of fixities.

**Comment by pnlph** [comment]
Then how can priorities be set for non-mixfix operators?

**Comment by jespercockx** [comment]
They can't, function application of non-mixfix operation has a fixed precedence and is always left-associative. You can cheat by naming the function `f_` instead of `f` and giving it a lower fixity, but this does not work for functions that take multiple arguments.

**Comment by pnlph** [comment]
OK, I can explain what I was trying to do, maybe there is indeed a workaround.

I was trying to express `5 + 6` in the assembly-like notation `bipush 5 bipush 6 iadd` reusing the definition `_+_` from the standard library, but I only arrive to `iadd (bipush 5) (bipush 6)`. I can not even get rid of the round brackets. to get the intermediate result `iadd bipush 5 bipush 6`.

Here is [a gist](https://gist.github.com/pnlph/0917aea6b634b56bcced03564d3e5784) with a self-contained code.

**Comment by JacquesCarette** [comment]
If you're willing to use 'do' notation (or explicit `>>`), that can be done.  See `tagless/stack-symantics.hs` in the https://github.com/JacquesCarette/finally-tagless repo. You'll need to 'lift' `_+_` as it has the wrong signature, you need to change it so that it operates on stacks.
