### ISSUE TITLE
Overly lenient parser

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda#4644]
I tried to write a comment next to a module parameter but only wrote `-` rather than `--` and was surprised to see that Agda accepted it as valid syntax, and proceeded to interpret the would-be comment as individual terms. For example:
```agda
module Test
 (A : Set) - The set
 where
```
gives the error
```
Sort _0  [ at /home/matthew/Code/agda-stdlib/main/src/Test.agda:3,12-13 ]
_1 : _0  [ at /home/matthew/Code/agda-stdlib/main/src/Test.agda:3,12-13 ]
Sort _2  [ at /home/matthew/Code/agda-stdlib/main/src/Test.agda:3,14-17 ]
_3 : _2  [ at /home/matthew/Code/agda-stdlib/main/src/Test.agda:3,14-17 ]
Sort _4  [ at /home/matthew/Code/agda-stdlib/main/src/Test.agda:3,18-21 ]
_5 : _4  [ at /home/matthew/Code/agda-stdlib/main/src/Test.agda:3,18-21 ]
```

**Comment by jespercockx** [comment]
What do you mean? You just defined a module with 4 parameters called `A`, `-`, `The`, and `set`. Since these are all valid identifiers, I don't really see what Agda could do to rule out mistakes like this.

**Comment by andreasabel** [comment]
Yes, I am afraid that is the status quo, unless someone wants to train an AI to detect improbable programs.

**Comment by MatthewDaggitt** [comment]
Ah yes, of course. I've never seen anyone provide explicit module arguments without a type before! Hadn't really considered it was possible.

> unless someone wants to train an AI to detect improbable programs.

I'm afraid I'm not volunteering :smile:
