### ISSUE TITLE
Universe Polymorphic Data.Unit, take 2

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda#4646]
Some time back, I added a universe polymorphic unit to the standard library -- https://github.com/agda/agda-stdlib/issues/839. It "works", but it's flawed: it does not inter-operate well with `Data.Unit`. The core of that is really `Agda.Builtin.Unit` (which is why the issue is here instead of over in the stdlib repo).

So I would like to make these two units "play well" together. I see two options:
1. change `Agda.Builtin.Unit` to be universe polymorphic and change `Data.Unit.Base` to *define* `⊤` to be a specialization of level 0.
2. change `Data.Unit.Polymorphic.Base` to not define a new record, but instead use `Lift` to define an 'alias'.  Might be able to use `pattern` declarations to make this smoother.

I am, of course, also proposing that I do the work. But as this involves a non-trivial change, I'd rather ask before I sink the time in to doing it.

I personally prefer option 1. Of course, for that to be viable as an option, the change should be essentially invisible to the standard library (including no new unsolved metas). But there may be other reasons to not do this -- hence this question.

**Comment by UlfNorell** [comment]
Can you elaborate on what the interoperability problems are?

I wouldn't want to make the builtin unit level polymorphic without very strong reasons. If we make unit polymorphic, why not also booleans and natural numbers?

**Comment by JacquesCarette** [comment]
Yes, of course. What I tried to do (and failed), was to hunt down all uses of `Lift` in the library that applied to either `⊤` or `⊥` and replace them with uses of the polymorphic versions. And that was a horrible failure.  [To be honest, I think I encountered a lot more problems with `⊥`]

Part of the problem is that even though the definition is almost the same
https://github.com/JacquesCarette/agda-stdlib/blob/f4105be514a5e52c7f5189346d83d0a3d2026d6a/src/Data/Unit/Polymorphic/Base.agda#L16-L17 those records are still not equal, even when specialized to Level 0.  Same with `⊥`.

There are a variety of places in the library that will produce a level 0 `⊥`, then lift it. But that is not the same type as the polymorphic `⊥`, leading to things not typechecking. And because it is done in 2 steps, I'd have to insert an explicit conversion from one to the other, which is seriously ugly.

The library (and some of my own code) have had to `Lift` `⊤` and`⊥` fairly often, thus the proposal to make them polymorphic. I think I've only ever encountered a (temporary) need to lift `Fin` once, and never `Bool` or the natural numbers.

Code like
```agda
⊎-identityˡ : ∀ ℓ → LeftIdentity _↔_ (Lift ℓ ⊥) _⊎_
```
in the standard library seems to be a symptom that the default definition isn't quite right.

Does that constitute 'very strong reasons'? Probably not. Thus the discussion!

**Comment by nad** [comment]
I sometimes lift `Bool`. Here are some (counter)examples:
* [⊆-not-antisymmetric](http://www.cse.chalmers.se/~nad/listings/up-to/Relation.html#⊆-not-antisymmetric).
* [¬-Set-set-↑](http://www.cse.chalmers.se/~nad/listings/equality/Univalence-axiom.html#¬-Set-set-↑).
* [no-first-projection-lens](http://www.cse.chalmers.se/~nad/listings/dependent-lenses/Lens.Non-dependent.html#no-first-projection-lens).
* [¬-Very-stable→Is-proposition](http://www.cse.chalmers.se/~nad/listings/equality/Erased.Stability.html#¬-Very-stable→Is-proposition).
* [not-always-contractible₂](http://www.cse.chalmers.se/~nad/listings/equality/Equivalence.html#not-always-contractible₂).

**Comment by JacquesCarette** [comment]
Thanks @nad. This seems to argue for option 2, as that is what you use in your own code.

**Comment by JacquesCarette** [comment]
Option 2 worked surprisingly smoothly after all.
