### ISSUE TITLE
Evaluate private definitions (toplevel interaction)

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#4647]
Private definitions cannot be evaluated in interaction top level:
```agda
open import Agda.Builtin.Nat
private n = 5
```
Then `C-c C-n n` gives an error complaining that `n` is not in scope.
The same problem arises with non-`public` `open`. 

Here is Thorsten Altenkirch's original feature request:

I have come across this little nuisance when using agda especially when doing life hacking in lectures or talks.

I try to evaluate an expression which depends on opening some modules which I have opened in my file but agda is not aware of this. E.g.
```agda
record Stream (A : Set) : Set where
  constructor _∷_
  coinductive
  field
    hd : A
    tl : Stream A

open Stream

from : ℕ → Stream ℕ
hd (from n) = n
tl (from n) = from (suc n)
```
 
And then I say `C-c C-n hd (from 0)` and agda responds
```
1,1-3
Not in scope:
  hd at 1,1-3 (did you mean 'Stream.hd'?)
when scope checking hd
```
Ok I can just introduce a shed
```
x = {!!}
```
and evaluate inside there but this is a bit clumsy. Isn’t there a better way to do this?

Ok I can say `open Stream public` – but do I want this?

**Comment by gallais** [comment]
May be worth having a distinct command "evaluate in context at cursor".
This way we can evaluate things on the RHS or inside a local module with
local `let`-bound definitions.

**Comment by jespercockx** [comment]
> May be worth having a distinct command "evaluate in context at cursor".
> This way we can evaluate things on the RHS or inside a local module with
> local `let`-bound definitions.

That would require us to store the context of every subterm, which I don't think is really feasible.

**Comment by UlfNorell** [comment]
I do believe we have the "inside scope" available, that is the scope that would be used for any new definitions at the end of the module. It ought not be too difficult to use this instead of the "outside scope", which is what other modules importing this module sees.

**Comment by xekoukou** [comment]
I mean, what @gallais proposes is the holy grail of interactive theorem provers.
Which means that all the internal data structures need to be reconsidered with this in mind.

**Comment by nad** [comment]
Related: #317. I wrote that 'I think the parameters should be in scope when "top-level" commands are executed, because these commands should behave in the same way as commands executed in a top-level goal at the end of the module'.

**Comment by andreasabel** [comment]
@UlfNorell :
> I do believe we have the "inside scope" available, that is the scope that would be used for any new definitions at the end of the module. It ought not be too difficult to use this instead of the "outside scope", which is what other modules importing this module sees.

We do use the inside scope.  However, the private definitions are removed from the `insideScope`:
https://github.com/agda/agda/blob/bc8feec71e61a4c4369aa0ee93b77bf027c0f7f1/src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs#L1232-L1236

You changed this in the course of the "deadcode" optimizations:
* In c823aa9a0e84816d3e36ea86e04e9f9caa536c4a you include a test case that defines "Not in scope" for evaluating private definitions as the specified behavior of Agda.
* In 7f47d51c06b8d2d3ff7b55a70b21e5f75ca4a7fc the release notes for Agda 2.4.4 state:
> Private definitions of a module are no longer in scope at the Emacs mode top-level.
> The reason for this change is that .agdai-files are stripped of unused private definitions (which can yield significant performance improvements for module-heavy code).
> To test private definitions you can create a hole at the bottom of the module, in which private definitions will be visible.

So while the OP used to work, there was a decision made to sacrifice it for the sake of performance.  

It seems there are three interest pursued which cannot all be integrated with the current architecture:
1. The OP.
2. To use the current module in its optimized form after serialization and deserialization.
3. The deadcode optimization in interface files to reduce the memory consumption.

A possible fix (Alt A) could look like this: There are two different formats of the interface file, one that includes the private definitions (2) (say `.agdatop`) and one that doesn't (1) (`.agdai`).  In interaction mode, the current module is then deserialized from the interface file (2), but recursive deserialization refers to the interfaces of type (1).  The interactive command `C-c C-l` (load) would create an interface of type (2), all other instances of processing a file would create an ordinary interface (1).

An alternative fix (Alt B) would drop goal 2 and remove private definition only just before serialization.  The current main module (in its internal representation) would then always be created from source, rather than loaded from an interface.  However, this has the drawback that switching file in emacs would always mean that the whole file is type-checked again from scratch.  @nad has complained about such behavior in the past. Yet currently, rechecking is anyway often needed because the highlighting is not reliably loaded from the interface file, see issue #3549.  

Input needed from @UlfNorell (defined the current specified behavior) and @nad (expertise on import and interaction logic).

**Comment by UlfNorell** [comment]
What about Alt B, but we add an emacs command to switch between "evaluation mode" (not using the interface for the current file) and "regular mode" (the normal behaviour). This should solve the drawback when switching files, if we reset the to regular mode when changing buffer.

**Comment by andreasabel** [comment]
`C-c C-n` could switch automatically to evaluation mode.
Automatically resetting to regular mode when changing buffer makes sense, but keeping in mind that the first `C-c C-n` requires rechecking then.  Anyway, I suppose `C-c C-n` is more used in demonstration situations of Agda than in serious development (I very very rarely use it at all), thus extra checking caused by `C-c C-n` is likely harmless!?

**Comment by UlfNorell** [comment]
Also checking should be quick due to caching, no?

**Comment by andreasabel** [comment]
Note: It seems the present issue is a duplicate of #1804.

**Comment by txa** [comment]
The other option seems to be not to strip private definitions. Why is this so important?

**Comment by andreasabel** [comment]
For performance: https://github.com/agda/agda/issues/1804#issuecomment-181994452

**Comment by nad** [comment]
Another option is perhaps to switch to some kind of structured signature so that the optimisation is not necessary. This may also have other performance benefits (#4331).

**Comment by andreasabel** [comment]
@nad:
> Another option is perhaps to switch to some kind of structured signature so that the optimisation is not necessary. This may also have other performance benefits (#4331).

The problem isn't in the signature but in the scope.  The private declarations get removed from the `ScopeInfo` when the top level module is finished scope checking.  This is what I am addressing here.

@UlfNorell : 
> What about Alt B, but we add an emacs command to switch between "evaluation mode" (not using the interface for the current file) and "regular mode" (the normal behaviour). This should solve the drawback when switching files, if we reset the to regular mode when changing buffer.

I am implementing this, but this will be disruptive to some interaction tests that accumulate solutions for metas (e.g. `Long`).  A top-level command, triggering a reload, will now lose these solutions since they are not written to a file.  Maybe this isn't such a problem.  We have a similiar problem already with the case-splitting command, which does not actually feed back to the state since it would require a reload from the updated source file.

**Comment by andreasabel** [comment]
PR #4652 for review.

**Comment by nad** [comment]
With this change in place, if I load the file, edit it, and use a top-level command to (say) normalise an expression, will Agda reload the file (and possibly fail)? In that case I am opposed to this change.

**Comment by nad** [comment]
> The problem isn't in the signature but in the scope. The private declarations get removed from the `ScopeInfo` when the top level module is finished scope checking. This is what I am addressing here.

If I understand you correctly the solution you have opted for involves recomputing things, and making Agda's already complicated loading logic even more complicated. Wouldn't it be easier to not throw away the information in the first place?

I understand that you have sunk some time into your fix, but you did not give us much time to discuss it.

**Comment by xekoukou** [comment]
The only meaningful reason not to load an interface is the change of the source, or the change of the pragmas.

A more radical approach is to have a database with cache, and load information per need. Thus, one does not need to choose which information is useful or not, and thus keep all information.

**Comment by pnlph** [comment]
Maybe I am missing something, but is not this already available?

When using `Open Stream`, then <kbd>C-c C-n</kbd> `Stream.hd (from 0)` evaluates to `0`.

When using `Open Stream public`, then <kbd>C-c C-n</kbd> `hd (from 0)` evaluates to `0`.

So I guess that the feature request is actually being able to evaluate `Stream.hd (from 0)` by executing <kbd>C-c C-n</kbd> `hd (from 0)`, i.e. without having to type the prefix `Stream.` every time, and without the obligation of exposing the record `Stream` to other modules that may import the current one.

I understand that now the only options are "no keyword", which prevents re-export and evaluation and `public`, which allows both the re-export and the evaluation.

Maybe what is needed here to solve the use case is a new keyword that allows the evaluation and not the re-export.

**Comment by pnlph** [comment]
For example, if the new keyword was `interactive`, it could allow interaction with the emacs/REPL mode and would look like this:
```haskell
open Stream               -- not interactive, no re-export
open Stream interactive   -- interactive, no re-export
open Stream public        -- remains the same
```
Alternatively the interactive option could be the default, reserving a new keyword for the former default behaviour, but this is not backwards-compatible:
```haskell
open Stream               -- interactive, no re-export
open Stream private       -- not interactive, no re-export
open Stream public        -- remains the same
```

**Comment by andreasabel** [comment]
@nad:
> With this change in place, if I load the file, edit it, and use a top-level command to (say) normalise an expression, will Agda reload the file (and possibly fail)? 

Yes.

However, as you keep working on the same file, it is not reloaded again.  I would suppose that a single additional reload per file (the first time you use a top-level command) isn't disrupting your workflow much.

If this is not wanted, we can make the switch to `TopLevelInteraction` mode manual.  This would mean that e.g. one has to type some prefix with a top-level interaction command to induce the switch.  However, it is hard to imagine that working well with less-sophisticated users (bad _discoverability_).  How would we hint them towards this switch?

Another alternative is to have a _PRO_ user mode for people like you @nad that use top-level commands a lot and do not want such automatic switching.  (I don't use them regularly and thus don't have a feeling for the workflows involving them.)

> If I understand you correctly the solution you have opted for involves recomputing things, and making Agda's already complicated loading logic even more complicated. Wouldn't it be easier to not throw away the information in the first place?

This was my alternative proposal (Alt A).  It also makes the loading logic more complicated.  We will have two versions of the interface file.

**Comment by nad** [comment]
> However, as you keep working on the same file, it is not reloaded again. I would suppose that a single additional reload per file (the first time you use a top-level command) isn't disrupting your workflow much.

If I'm in the process of editing something and the file currently does not type-check, then I can't use the top-level commands at all. This does not sound like an improvement to me.

> This was my alternative proposal (Alt A). It also makes the loading logic more complicated. We will have two versions of the interface file.

Can't we have a single version that includes all the information? If I understand correctly the dead-code optimisation was introduced because things like `module M = M' args` are represented very inefficiently. Can't we fix this problem instead of complicating things?

**Comment by UlfNorell** [comment]
+1 on adding a flag for the automatic switching. That will let us play around with it for a while to see how it works out in practice.

**Comment by andreasabel** [comment]
@UlfNorell 
> +1 on adding a flag for the automatic switching. That will let us play around with it for a while to see how it works out in practice.

This needs some more fleshing out.  Name of the flag? Pragma or commandline option?  Name of the command for manual switching?  Key binding of this command?

@nad 
> If I'm in the process of editing something and the file currently does not type-check, then I can't use the top-level commands at all. This does not sound like an improvement to me.

Well, you can if this is not the first top-level command you are issuing.

Alternative is to always retypecheck the main module upon the first load.  We have decided against this in the past.

@nad 
> If I understand correctly the dead-code optimisation was introduced because things like `module M = M' args` are represented very inefficiently. Can't we fix this problem instead of complicating things?

If we could, we could have done it 5 years ago.  No one wants to touch the fundamentals of Agda, this is a historic _fact_. We have to be realistic here.

@nad 
> Can't we have a single version that includes all the information?

By practical means, no.  There are conflicting goals, as I explained in my analysis https://github.com/agda/agda/issues/4647#issuecomment-627822562 .

What I have suggested in Alt A is to have ordinary `.agdai` files for fast batch-processing, and an `.agdatop` file with the full scope, which may be slower to create.  When working interactively,  an`.agdatop` file is created from the main module (but `.agdai` files for all recursively chased modules).  If you only have the `.agdai` file and load the resp. module interactively, Agda will retypecheck and create an `.agdatop` module.

**Comment by nad** [comment]
> Well, you can if this is not the first top-level command you are issuing.

I guess you agree that this change will break some workflows.

> If we could, we could have done it 5 years ago. No one wants to touch the fundamentals of Agda, this is a historic _fact_. We have to be realistic here.

Can we at least discuss what this would entail? @jespercockx has proposed that we should discuss this kind of thing during the upcoming Agda meeting.

> > Can't we have a single version that includes all the information?
> 
> By practical means, no. There are conflicting goals, as I explained in my analysis [#4647 (comment)](https://github.com/agda/agda/issues/4647#issuecomment-627822562) .

@UlfNorell [stated](https://github.com/agda/agda/issues/1804#issuecomment-181994452) that "The dead-code elimination reduced some of Wolfram's interfaces by a factor 5". Perhaps it is fine to make certain interface files five times larger. Or perhaps it is fine to leave things as they were.

> What I have suggested in Alt A is to have ordinary `.agdai` files for fast batch-processing, and an `.agdatop` file with the full scope, which may be slower to create.  When working interactively,  an`.agdatop` file is created from the main module (but `.agdai` files for all recursively chased modules).  If you only have the `.agdai` file and load the resp. module interactively, Agda will retypecheck and create an `.agdatop` module.

I think I would prefer the following variant: Always put the private things in the interface file, but put them at the end. Only read in the private things if there is a chance that they will be used.

However, perhaps it makes more sense to spend our effort on "touching the fundamentals of Agda".

**Comment by andreasabel** [comment]
@nad 
> I guess you agree that this change will break some workflows.

I do agree.  I can reduce the breakage by only switching to `TopLevelInteraction` when a top-level command resulted in a not-in-scope error.

Later refinements can then switch to loading extra scope information when a non-in-scope error occurs.  But the interaction logic will stay the same, thus, the infrastructure I created in the PR makes sense.

> Can we at least discuss what this would entail?

Discussions are useless if no one pledges to implement the solution found in the discussion.

> perhaps it makes more sense to spend our effort on "touching the fundamentals of Agda".

"Perhaps" won't do it.  _(Rest of comment censored due to reference to satanic practices.)_

**Comment by jespercockx** [comment]
Maybe we can all agree that when we are faced with a problem that is troubling users of Agda *now*, we should look into solutions that can alleviate this problem in the short term, while keeping our eyes and minds open for possible structural improvements that would solve those problems in a more fundamental way. Despite what we might *want* it to be, the reality is that Agda in its current shape is still mostly a research artifact, so research on both incremental and foundational approaches to improve Agda should always be welcome.

**Comment by txa** [comment]
I think we also need to make sure not to overcomplicate things and produce behaviour one would intuitively expect. That is if I can write a top level definition:
`
x = hd (from 0)
`
then I expect that I can evaluate `hd (from 0)` on the top-level. Any explanation of the form _for efficiency reasons we needed to strip private definition_ doesn't hold water. The decision to do this in the first place was flawed. The simple solution is not to strip them (instead of complicating things even further) but introduce a flag advanced users who are concerned about the size of their agdai files can use to reduce their size.

I am using agda in teaching and I would like it to help to spread type theory. Awkward behaviour like this has the opposite effect!

**Comment by andreasabel** [comment]
@txa:  I agree that intuitively, one wants to evaluate also private definitions, this is why I am working on this issue.

> Any explanation of the form _for efficiency reasons we needed to strip private definition_ doesn't hold water. The decision to do this in the first place was flawed.

The problem is that when the optimization was introduced, the specification (= testsuite) of Agda was broken and then simply altered (see release notes for 2.5.1, see #1804).

> The simple solution is not to strip them (instead of complicating things even further) but introduce a flag advanced users who are concerned about the size of their agdai files can use to reduce their size.

A proliferation of flags is also not the answer.  E.g., I want to get efficient Haskell programs without studying the manual of GHC for weeks and experimenting with all kinds of optimization flags.  Analogously, as Agda user I want to be able to do something more than a couple of simple files before running into performance problems that force me into playing with the flags.

**Comment by andreasabel** [comment]
@nad : I updated the PR which allows you to use `C-c C-n` and the like on a dirty file (unless you trigger a not-in-scope error).  I suggest you try it out for a while and see what the actual disruption of your workflows is.

**Comment by txa** [comment]
> A proliferation of flags is also not the answer. E.g., I want to get efficient Haskell programs without studying the manual of GHC for weeks and experimenting with all kinds of optimization flags. Analogously, as Agda user I want to be able to do something more than a couple of simple files before running into performance problems that force me into playing with the flags.

Proliferation of flags is a minor issue. The default behaviour needs to be intuitive. The advanced user may have to dig deeper into the manual. Even in Haskell -O2 or whatever.

**Comment by andreasabel** [comment]
@txa: Please try my PR #4652 and tell me whether it fixes the problem for you.

**Comment by nad** [comment]
@andreasabel, you did not address the following suggestion:

> I think I would prefer the following variant: Always put the private things in the interface file, but put them at the end. Only read in the private things if there is a chance that they will be used.

This would not break any current workflows, and it seems to me as if the interaction logic would be less complicated than with your suggested changes. It would mean that Agda spends more time *writing* interface files, but *reading* should be roughly as fast as it is today, except for the top-level module. This sounds like a good compromise to me, but I don't know if @WolframKahl's problems were mainly related to reading or writing. (I guess that disk space was not an issue.)

**Comment by andreasabel** [comment]
I intended to address it here:
> Later refinements can then switch to loading extra scope information when a non-in-scope error occurs. But the interaction logic will stay the same, thus, the infrastructure I created in the PR makes sense.

Still, there needs to be a trigger when the extra information should be read.  But maybe you want to read it eagerly.

I am worried about serializing the scope twice, once abridged and once unabridged.  One of the optimizations to the serializer I did with Makoto 5-6 years ago at AIM XXI was to delete another copy of the scope; at that time both `insideScope` (for top-level interaction) and "outsideScope" (for importing the module) were serialized.  We got rid of the "outsideScope" by reconstructing it from the `insideScope`.  What you suggest would basically turn back the clock to before that optimization.
Related: #1580.

**Comment by nad** [comment]
> But maybe you want to read it eagerly.

Yes, for the top-level module (in the Emacs mode and `agda -I`).

> I am worried about serializing the scope twice, once abridged and once unabridged.

I'm not familiar with the representation of the scope. Isn't it possible to serialise the currently omitted parts separately, and then combine the two scopes into one?

**Comment by andreasabel** [comment]
@nad 
> I'm not familiar with the representation of the scope. Isn't it possible to serialise the currently omitted parts separately, and then combine the two scopes into one?

In some way or the other, yes, it is possible.  How should it be impossible?  (We are dealing with classical information, which can be deleted and duplicated at will.)

The question is whether it affects @UlfNorell : https://github.com/agda/agda/issues/1804#issuecomment-181994452
> The dead-code elimination reduced some of Wolfram's interfaces by a factor 5, so I'd say pretty important.

**Comment by andreasabel** [comment]
I have merged the PR to subject it to testing in practice.

@nad : Please use Agda "naturally" (as you always use it) and see if any disruption of your workflows happens in practice.  There is an "emergency brake", option `--top-level-interaction-no-private` that brings back the old behavior, should you get irritated by the new one.  Please report situations where the new behavior is disrupting.

**Comment by andreasabel** [comment]
I undid the fix.  A workaround (in many cases) is to leave a hole in the file one wants to issue top-level interaction commands.
