### ISSUE TITLE
Proofs about generalizable variables?

### ISSUE THREAD

**Issue by pnlph** [agda/agda#4648]
```agda
open import Agda.Builtin.List
```
It is possible to prove that `a ∷ as` is a `List`of `A` for all sets, elements of a given set, and lists of a given `List`type:
```agda
a∷as:ListA : ∀ {A : Set} → ∀ {a : A} → ∀ {as : List A} → List A
a∷as:ListA {X} {x} {xs} = x ∷ xs
```
But when declaring variables:
```agda
variable
  I : Set
  τ : I
  Δ : List I
```
One cannot prove that `τ ∷ Δ` is a `List` of `I` as scope checking `τ` fails:
```agda
-- fails: Generalizable variable σ is not supported here
τ∷Δ:ListI₁ : List I
τ∷Δ:ListI₁ = τ ∷ Δ
```
Is not `τ∷Δ:ListI₁` a particular case of `a∷as:ListA`? Should it not be proveable? I tried also to apply `a∷as:ListA` to the declared variables:
```agda
-- fails: Generalizable variable σ is not supported here
τ∷Δ:ListI₂ : List I
τ∷Δ:ListI₂ = a∷as:ListA {I} {τ} {Δ}
```
But the same error appears. Only when postulating the variables involved on the right side of the clause, everything works.
```agda
postulate
  σ : I
  Γ : List I

σ∷Γ:ListI : List I
σ∷Γ:ListI = σ ∷ Γ
```
Is there a workaround for proving things about variables?

**Comment by UlfNorell** [comment]
Variables are not entities in their own right in the type theory, so it doesn't make sense to prove things about them. Rather they are schematic variables on the meta-level. Generalization happens only at type signatures, which is why you get the "not allowed here" error when you use one in a definition right-hand side. This means that you need to mention the variables in the type signature for it to work. I think this is what you want (the example is a bit silly, so it's hard to know exactly what you are after):

```agda
open import Agda.Builtin.List
open import Agda.Builtin.Unit

variable
  I : Set
  τ : I
  Δ : List I

IsList : List I → Set
IsList _ = ⊤

τ∷Δ:ListI : IsList (τ ∷ Δ)
τ∷Δ:ListI = tt
```

See more details here: https://agda.readthedocs.io/en/latest/language/generalization-of-declared-variables.html

**Comment by andreasabel** [comment]
@pnlph 
> It is possible to prove that a ∷ as is a List of A for all sets, elements of a given set, and lists of a given List type

Philosophically, I need to object to such a formulation. 
In fact `a ∷ as` is the _construction_ of a list, thus, it is a list _a priori_.  Your formulation suggests that being a list is an _a posteriori_ property of `a ∷ as`.  However, `a ∷ as` does not have an existence prior to being a list.

**Comment by pnlph** [comment]
Thank you both for your time and the explanation!

I naively thought that I could simplify the implicit parameters of this code:
```agda
τ∷Δ : ∀ {I : Set} → ∀ {τ : I} → ∀ {Δ : List I} → List I
τ∷Δ {X} {x} {xs} = x ∷ xs
```
by declaring variables:
```
variable
  I : Set
  τ : I
  Δ : List I

τ∷Δ : List I
τ∷Δ = τ ∷ Δ
```
From your words, I guess that τ∷Δ is just a restaging (Reinszenierung) from append and has no other meaning on its own.

Then, asserting that "appending an element to a list results in a list" is not provable, and it amounts to just asserting the construction of the list itself, is that correct?

**Comment by andreasabel** [comment]
Yes.  In contrast to NuPrl, Agda is not a _type assignment system_ where terms have their independent existence and you can proof that they inhabit certain types.  Rather, Agda's terms are _intrinsically typed_ as soon as Agda accepts their definition.

Wrt. to generalization: As @UlfNorell  explained generalization happens only for type signatures `:`, not for definitions `=`.  In other words, generalization inserts `∀` abstractions, but no lambda-abstractions.
