### ISSUE TITLE
Repair Agda's REPL (agda -I) to work with --safe flag

### ISSUE THREAD

**Issue by txa** [agda/agda#4649]
Especially for teaching it would be nice if agda had a top-level REPL (read-eval-print loop) so that one can evaluate expressions interactively without always having to go via C-c C-n. Also I would like to print streams using costrings. 

Has this been discussed before? What would be the effort and possible issues?

**Comment by nad** [comment]
Agda already has a REPL, but it is unmaintained. Try `agda -I`. Currently it does not work very well with code that uses `--safe`, but I guess that could be fixed.

> Also I would like to print streams using costrings.

I'm not sure exactly what you mean. Can't you use the following [function](https://github.com/agda/agda-stdlib/blob/041fd896be22045262fb5d53ef10fc779f827bcc/src/IO.agda#L112) from the standard library?
```agda
putStr∞ : Costring → IO ⊤
```

**Comment by pnlph** [comment]
To add some information, there is a [recent comparison](https://ice1000.org/2020/05-04-ReplWithGoals.html) among several programming languages with REPLs and typed holes put up together by @ice1000

**Comment by txa** [comment]
Ok, first of all as you already indicated there seem to be some issues with agda -I. Just trying to load Data.Nat doesn't seem to work:
```
txa@sean agda-src % agda -I test.agda  
 
The interactive mode is no longer under active development. Use at your own risk.
Checking test (/Users/txa/agda-src/test.agda).
 Checking Data.Nat (/Users/txa/agda/std-lib/src/Data/Nat.agda).
  Checking Data.Nat.Base (/Users/txa/agda/std-lib/src/Data/Nat/Base.agda).
   Checking Level (/Users/txa/agda/std-lib/src/Level.agda).
/Users/txa/agda/std-lib/src/Data/Nat/Base.agda:14,1-29
Cannot set OPTIONS pragma --allow-unsolved-metas with safe flag.
when scope checking the declaration
  open import Level using (0ℓ)

```
Also I would like to be able to open a REPL in a separate buffer after loading the current buffer via an emacs command.

**Comment by nad** [comment]
If you want to play around with the REPL right now you can comment out two lines:

https://github.com/agda/agda/blob/a9d6c1dca937d5145a34613ed52fdcaf15163f64/src/full/Agda/Interaction/Options.hs#L770

https://github.com/agda/agda/blob/a9d6c1dca937d5145a34613ed52fdcaf15163f64/src/full/Agda/Interaction/Options.hs#L772

However, I guess that this may break some part of the REPL.

**Comment by andreasabel** [comment]
Fixing this by allowing `--safe` and `--allow-unsolved-metas` to coexist in `-I` mode.

**Comment by nad** [comment]
Now `--allow-unsolved-metas` is turned on also in imported modules. Test case:
```agda
{-# OPTIONS --safe #-}

module B where

bad : {A : Set} → A
bad = ?
```
```agda
{-# OPTIONS --safe #-}

module A where

import B
```
Is this intended?

**Comment by andreasabel** [comment]
I didn't change the existing logic, which turns on `--allow-unsolved-metas` globally.  I only silenced the conflict with `--safe`.

**Comment by andreasabel** [comment]
@nad You reopened the issue.  What is it that you want to see implemented?

**Comment by nad** [comment]
I don't think Agda should accept code with holes when `--safe` is used. Perhaps it is fine to leave it as it is for now, because we do advertise that `agda -I` is not supported. However, there seems to be interest in actually supporting `agda -I`, so I don't think we should close this issue.

Does anyone know why `--allow-unsolved-metas` is turned on? Apparently it has been like this since 2006 (ff2ccf61c4ef89f7722bd24ae119c7f6cdd6cf33), but back then this setting was used also for the Emacs mode. I suggest that we turn off `--allow-unsolved-metas`. Perhaps something breaks, but I would assume that it breaks in a "safe" way: fewer programs are accepted, not more.

**Comment by andreasabel** [comment]
I wouldn't say that `agda -I` needs to speak with authority on what is safe and what not.  It is a REPL to tinker around and evaluate stuff.

> Does anyone know why `--allow-unsolved-metas` is turned on?

I suppose to enable to interactively give solutions to metas.

> However, there seems to be interest in actually supporting `agda -I`, so I don't think we should close this issue.

Users can always open issues when they seek functionality or find bugs.  The OP here was fixed, thus, I do not see a reason why to keep this issue in limbo.

**Comment by nad** [comment]
I don't think we should ignore issues related to `--safe`.

If there are no objections I can revert your change and turn off `--allow-unsolved-metas`.

**Comment by ice1000** [comment]
I would ask why does the REPL forcibly requires `--allow-unsolved-metas`. We can work with `--safe` files with unsolved metas in Emacs, right?

**Comment by nad** [comment]
This code has been unmaintained for a long time. I guess that it was not updated when the Emacs mode was changed.

One practical consequence of using `--allow-unsolved-metas` that has not been mentioned above is that in many cases Agda decides that the options have changed and decides to typecheck everything from scratch.

**Comment by andreasabel** [comment]
This issue has been closed as fixed but the OP persists:
> Cannot set OPTIONS pragma --allow-unsolved-metas with safe flag.

**Comment by andreasabel** [comment]
A never mind, I got confused by the error message (that seems to be ignored):  `agda -I` does complain about `--safe --unsolved-metas` but still lets me work with open metas.
