### ISSUE TITLE
Function name not wrapped in `\AgdaFunction` in generated LaTeX

### ISSUE THREAD

**Issue by ayberkt** [agda/agda#4656]
I have tested this with f92c37e2b44cc6c3d9d2ced76b3b53f39b8322d6.

Here is a minimal example illustrating the problem.

```agda
\begin{code}
module Foo where

open import Level

module Bar (ℓ : Level) where

  data Unit : Set where
    tt : Unit

  ⟪_⟫ : Unit → Unit
  ⟪ tt ⟫ = tt

open Bar zero using (⟪_⟫)
\end{code}
```

The open involving the `using` clause corresponds to the following in the generated LaTeX:

```
%
\\[\AgdaEmptyExtraSkip]%
\>[0]\AgdaKeyword{open}\AgdaSpace{}%
\AgdaModule{Bar}\AgdaSpace{}%
\AgdaPrimitive{zero}\AgdaSpace{}%
\AgdaKeyword{using}\AgdaSpace{}%
\AgdaSymbol{(}⟪\AgdaUnderscore{}⟫\AgdaSymbol{)}\<%
```

Neither `⟪` nor `⟫` is wrapped in a syntactic sort marker. This is problematic when trying to change, for instance, the font used in the generated LaTeX.

**Comment by andreasabel** [comment]
`(⟪_⟫)` has not highlighting information in the `using` clause.  While in #1714 this was fixed for `open M using`, it does not seem to work with applied modules like `open Bar zero` in the OP.

A workaround is to name the module, e.g. `open module M = Bar zero using (⟪_⟫)`.

**Comment by ayberkt** [comment]
> A workaround is to name the module, e.g. `open module M = Bar zero using (⟪_⟫)`.

Thanks, this is really useful.

**Comment by andreasabel** [comment]
Seems like I have found the problem; preparing a fix.
https://github.com/agda/agda/blob/f92c37e2b44cc6c3d9d2ced76b3b53f39b8322d6/src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs#L320-L325
https://github.com/agda/agda/blob/f92c37e2b44cc6c3d9d2ced76b3b53f39b8322d6/src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs#L341-L343
In the last line, we are giving back the "boring" import directive if `isNoName x`, meaning the module macro is anonymous; as a result, we lose the information needed for highlighting.  The problem seems to be fixed when returning `adir'` instead in this case.

**Comment by nad** [comment]
Agda should wrap all code (except for whitespace) in some macro like `\AgdaFunction`. @andreasabel, are you aware of other omissions of this kind?

**Comment by andreasabel** [comment]
These macros come from highlighting information.  If there is no highlighting information (as it was in this case), no macros.

**Comment by nad** [comment]
I know. Do you know of other examples in which Agda does not generate any highlighting?

**Comment by andreasabel** [comment]
Not off the top of my head.  I'd expect these will eventually get reported to the issue tracker.
Highlighting problems do creep in all the time due to incorrect ranges, new language features, refactorings...

**Comment by ayberkt** [comment]
> Highlighting problems do creep in all the time due to incorrect ranges, new language features, refactorings...

Actually, now that I think about it, I did encounter some other bizarre highlighting issues recently. Maybe I should file reports for them as well.
