### ISSUE TITLE
Could Level be a datatype in Agda.Primitive?

### ISSUE THREAD

**Issue by pnlph** [agda/agda#4658]
`Level`, `lzero`, `lsuc` and `_⊔_` are postulated in `Agda.Primitive`.

Could not `Level` be a datatype, `lzero` and `lsuc` its constructors, and `_⊔_` defined as a function? I read the [Built-ins documentation](https://agda.readthedocs.io/en/latest/language/built-ins.html?highlight=level#universe-levels) but I could not find an explanation for the `postulate` choice.

I only found this hint in `Agda.Primitive` but I did not understand it, does it mean that if we define `Level`as a datatype it would not be safe? Does `()` here refer to the absurd pattern?
```
-- MAlonzo compiles Level to (). This should be safe, because it is
-- not possible to pattern match on levels.
```

**Comment by guillaumebrunerie** [comment]
The primitive `_⊔_` has various additional properties, like being definitionally commutative and associative.

If you do what you propose, you could then construct functions between `Level` and `Nat` back and forth the obvious way, and that would give you the possibility to define a definitionally commutative and associative `max` function on `Nat`. This is something that is known to be impossible in Martin–Löf type theory, and it probably creates various type-theoretical problems.

For your last question, `()` refers to Haskell’s unit type.

**Comment by pnlph** [comment]
Thank you @guillaumebrunerie !

If someone thinks this should be documented, please reopen the issue.
