### ISSUE TITLE
Type inference fails when there are two constructors with the same name

### ISSUE THREAD

**Issue by halfaya** [agda/agda#4659]
In the following code the function `f` has unsolved metavariables even though `suc` must be the constructor for `Pos`. Making the constructor name unique solves the problem as shown by `g`. Although this example is simplified I want to do more sophisticated things (such as declaring a type `suc (Pos→ℕ (ℕ→Pos n)) ≡ suc n`) and have to work around it by assigning local variables with explicit types, so it would be nice if this can be fixed.

```agda
module Bug where

data ℕ : Set where
  zero : ℕ
  suc  : ℕ → ℕ

data Pos : Set where
  one : Pos
  suc : Pos → Pos

data Pos' : Set where
  one  : Pos'
  suc' : Pos' → Pos'

ℕ→Pos : ℕ → Pos
ℕ→Pos zero    = one
ℕ→Pos (suc n) = suc (ℕ→Pos n)

ℕ→Pos' : ℕ → Pos'
ℕ→Pos' zero    = one
ℕ→Pos' (suc n) = suc' (ℕ→Pos' n)

-- unsolved metavariables
f : ℕ → ℕ
f n = let a = suc (ℕ→Pos n) in zero

-- works if we explicitly declare the type
f' : ℕ → ℕ
f' n = let a : Pos; a = suc (ℕ→Pos n) in zero

-- works fine
g : ℕ → ℕ
g n = let a = suc' (ℕ→Pos' n) in zero
```

**Comment by gallais** [comment]
I'd say this is #3227
