### ISSUE TITLE
Access let-bindings using reflection

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#466]
`unquote` has no way to reach a `let` binding, here is two tries:

``` agda
t = let x = 42 in unquote (var 0 [])
t = let x = 42 in unquote (def (quote x) [])
```

However it works fine with `where` blocks:

``` agda
t = unquote (def (quote x) []) where x = 42
```

Original issue reported on code.google.com by `nicolas....@gmail.com` on 20 Sep 2011 at 3:19

**Comment by jespercockx** [comment]
I'm closing this due to a lack of a concrete proposal. Reflection is always going to be somewhat dependent on how things are represented internally in Agda, and for let there just isn't anything there in the internal syntax.
