### ISSUE TITLE
Current module contents

### ISSUE THREAD

**Issue by pnlph** [agda/agda#4662]
`C-c C-o` shows the contents of a module (e.g. imported and opened?), but does not work with the current module. Is this behavior intended?

Are the shown contents of a module equivalent to the elements of that module that we brought to the current scope?

**Comment by andreasabel** [comment]
Related: #1141 (absolute module references).
Without changing too much, we could an empty input `C-c C-o RET` have print the contents of the top-level module (currently gives a parse error).
In my own workflows, I only use `C-c C-o` on  complicated modules I import.

**Comment by pnlph** [comment]
Yes, I also think that printing the top-level module with `C-c C-o RET` would be a perfect solution to this.

Also, currently `C-c C-o` prints the same independently from how the module was imported. Would it be easy to annotate the scope in the print?
```agda
-- everything in scope
open import Agda.Builtin.Equality
-- only module in scope
open import Agda.Builtin.Equality using ()
-- only module _≡_ in scope
open import Agda.Builtin.Equality using ()
-- module _≡_ and name _≡_ in scope
open import Agda.Builtin.Equality using ()
-- module not in scope
open import Agda.Builtin.Equality as _
```

**Comment by pnlph** [comment]
I am right now realizing that under `Modules` are not really modules, but datatypes listed, could we change the wording? This is the output of `C-c C-o Agda.Builtin.Equality RET`
```
Module Contents
Modules
_≡_
Names
_≡_ : {a : Level} {A : Set a} → A → A → Set a
refl : {a : Level} {A : Set a} {x : A} → x ≡ x
```

**Comment by guillaumebrunerie** [comment]
`_≡_` is actually a module as well. See [the doc](https://agda.readthedocs.io/en/v2.6.1/language/module-system.html#datatype-modules-and-record-modules):

> When you define a datatype it also defines a module so constructors can now be referred to qualified by their data type.

**Comment by pnlph** [comment]
> `_≡_` is actually a module as well.

:bulb: Thank you for pointing this out!

I was not aware that data types and records are defining modules.

In that case, and if I understood, I think this would be clearer, because one can not evaluate `_≡_._≡_` anyway; it throws a `Not in scope` error. Otherwise, it seems like the module and the data type are two different things, don't you think?
```
Module Contents
Modules
_≡_ : {a : Level} {A : Set a} → A → A → Set a
Names
refl : {a : Level} {A : Set a} {x : A} → x ≡ x
```

I also noticed that the print is sometimes not the same, for example:
```agda
import Agda.Builtin.Nat using (Nat)
```
`C-c C-o Agda.Builtin.Nat RET` prints only the scope:
```
Module Contents
Modules
Nat
Names
Nat : Set
```
but the same declaration with `agda-stdlib`:
```agda
import Data.Nat using (ℕ)
```
prints the whole list of modules and names, in and out of scope.

**Comment by guillaumebrunerie** [comment]
> In that case, and if I understood, I think this would be clearer, because one can not evaluate `_≡_._≡_` anyway; it throws a `Not in scope` error. Otherwise, it seems like the module and the data type are two different things, don't you think?

`_≡_` is also in scope as a name, names and modules are two different namespaces, so not putting it in the `Names` part would be wrong (the module and the datatype *are* two different things).

Nothing in the current output says that `_≡_._≡_` should work, it simply says that `_≡_` is in scope both as a module and as a name. If you want to know the content of the module named `_≡_`, you can do `C-c C-o Agda.Builtin.Equality._≡_`, and you’ll see that it only contains `refl`.

**Comment by andreasabel** [comment]
> ```agda
> import Data.Nat using (ℕ)
> ```
> prints the whole list of modules and names, in and out of scope.

`C-c C-o Data.Nat` prints for me just
```
Modules
  ℕ
Names
  ℕ : Set
```

**Comment by pnlph** [comment]
@banacorn can you please take a look? Maybe it is an issue of the agda-mode in Atom?

**Comment by andreasabel** [comment]
> Without changing too much, we could an empty input `C-c C-o RET` have print the contents of the top-level module (currently gives a parse error).

I implemented this.
