### ISSUE TITLE
free anonymous import from open

### ISSUE THREAD

**Issue by pnlph** [agda/agda#4663]
PR #4270 implemented the *anonymous import* feature solving #3727, which brings into scope the module's contents, but not the module itself:
```agda
open import Agda.Builtin.Nat as _
```
It is also working with modifiers like `using`:
```agda
open import Agda.Builtin.Nat as _ using (Nat ; zero ; _+_)
```
The feature is excellent, but it seems to be working only with `open` and `import` together. The following code loads but is impracticable:
```agda
import Agda.Builtin.Nat as _ using (Nat ; zero ; _+_)
```
How to open one of the selected elements afterward in code *and* maintaining the anonymity? What I would expect is something like:
```
import Agda.Builtin.Nat as _ using (Nat ; zero ; _+_)
-- some agda code here
open Nat
-- some more agda code
open zero
-- ...
```
The problem is that `open` seems to look only after modules:
```
No module Nat in scope when scope checking the declaration open Nat
```
Could the keyword `open` work also to implement the opening of the imported identifiers at a later position in the file?

**Comment by UlfNorell** [comment]
What problem are you trying to solve with this proposal? Making `open` bring single identifiers into scope adds a bunch of extra complexity and I don't see any benefits. If you want to bring names from a module into scope at later times it's not unreasonable that you name the module.

**Comment by pnlph** [comment]
Thanks! I think you're right.

I don't have a particular problem in mind; I was just exploring the `import` feature and wanted to be sure that the behavior is known.

We can close the issue, and if someone comes up with a compelling use case for this in the future (having in mind that the solution may be complex), it can be re-opened.
