### ISSUE TITLE
Documentation: add install instructions for stack

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#4665]
The instructions https://agda.readthedocs.io/en/v2.6.1/getting-started/installation.html currently do not mention installation via stack.

Relevant file is: https://github.com/agda/agda/blob/master/doc/user-manual/getting-started/installation.rst

**Comment by EdNutting** [comment]
Can I suggest using the CI system as documentation for this? The commands in the stack.yaml file now cover all platforms and will (nearly) always work at any given point in time. In contrast, documentation written separately is likely to go out of date.

The documentation would still need a note on dependencies / installing dependencies.

This also relates to #4672 - Add Agda to Stackage

**Comment by andreasabel** [comment]
> Can I suggest using the CI system as documentation for this?

That would be perfect, if the documentation of the install instruction was CI-tested.
However, I was thinking of a couple of lines written for Joe User, along the lines of
```
cabal install update
cabal install alex happy Agda
```
or the like, only for stack.
How would these lines look like if I used the CI system as you suggest?

**Comment by andreasabel** [comment]
It seems that now this command works:
```
stack install --resolver nightly Agda
```
Until Agda is in some LTS, it seems that the `--resolver nightly` part cannot be omitted.  See also https://github.com/commercialhaskell/stackage/pull/5715#issuecomment-721260644

**Comment by asr** [comment]
I want to add the missing instructions. For example, I use the following commands for installing 2.6.1.2 from Hackage using GHC 8.10.2:

```
$ cabal get Agda-2.6.1.2
$ cd Agda-2.6.1.2
$ stack --stack-yaml stack-8.10.2.yaml install
```

Can I avoid the firsts two steps by adding the url in the third step?

**Comment by jespercockx** [comment]
For me, this command actually works (tested on both linux and windows):
```
stack install Agda-2.6.1.2 --resolver lts-16.31
```
This uses GHC 8.8.4 rather than 8.10.3, but otherwise seems quite robust. Using the lts-17.1 resolver (which uses 8.10.3) fails with an error while building Agda due to a missing dependency on `transformers`:
```
Agda                 > /tmp/stack-e1dec30b0612ce63/Agda-2.6.1.2/src/full/Agda/Utils/Maybe.hs:13:1: error:
Agda                 >     Could not load module ‘Control.Monad.Trans.Maybe’
Agda                 >     It is a member of the hidden package ‘transformers-0.5.6.2’.
Agda                 >     Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
Agda                 >     Use -v (or `:set -v` in ghci) to see a list of the files searched for.
Agda                 >    |
Agda                 > 13 | import Control.Monad.Trans.Maybe
Agda                 >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Agda                 > 
```
Using the nightly resolver also fails because of the same reason.

**Comment by asr** [comment]
Thanks! We know that 2.6.1.2 fails with GHC 8.10.3. For this reason we shall release 2.6.1.3 (see #5136).

**Comment by asr** [comment]
What about if I need to use GHC 8.6.5? Replacing `lts-16.31` by `lts-14.27` didn't work:

```
$ stack install Agda-2.6.1.2 --resolver lts-14.27

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for Agda-2.6.1.2:
    data-hash must match >=0.2.0.0 && <0.3, but the stack configuration has no specified version  (latest matching version is 0.2.0.1)
    equivalence must match >=0.3.2 && <0.4, but the stack configuration has no specified version  (latest matching version is 0.3.5)
    geniplate-mirror must match >=0.6.0.6 && <0.8, but the stack configuration has no specified version  (latest matching version is 0.7.7)
    regex-tdfa-1.2.3.2 from stack configuration does not match >=1.3.1.0 && <1.4  (latest matching version is 1.3.1.0)
needed since Agda is a build target.
...
```

Note that the missing dependencies are in the `stack-8.6.5.yaml` file.

**Comment by L-TChen** [comment]
Those dependencies are not part of the resolver `lts-14.27`.

**Comment by asr** [comment]
I know. So,  do I need first download 2.6.1.2 and use its `stack-xyz.yaml` file?

**Comment by jespercockx** [comment]
> I know. So, do I need first download 2.6.1.2 and use its `stack-xyz.yaml` file?

Yes, I think that's the only way that's guaranteed to work. The fact that the `lts-16.31` resolver works seems more like a coincidence than anything.

**Comment by asr** [comment]
In 384cafd0cc18df8380b75c47d912e8085d25b5e1 I added instructions for installing Agda from Hackage using `stack` to the user manual.
