### ISSUE TITLE
devel branch forked agda in mac howto

### ISSUE THREAD

**Issue by pnlph** [agda/agda#4668]
Hi,

I am trying to figure out how if it is possible to get `SSet` in scope.

At the time, I did a normal installation `brew install agda` via Homebrew and I update agda always with `brew update`.

I am trying to load this file:
https://github.com/jespercockx/agda/blob/2ltt/test/Succeed/SST.agda

But it does not work, somehow the PR #4091 was not merged. I think that I would need to run agda from this branch:
https://github.com/jespercockx/agda/tree/2ltt

Therefore, my question is whether it is possible to run agda using a branch from a forked repository downloaded with Github Desktop?

---
My rig:
macOS 10.13.6
Agda version 2.6.1

**Comment by UlfNorell** [comment]
These kinds of questions are not really appropriate for the issue tracker. Please direct them to the mailing list or the gitter instead. If there are actionable improvement suggestions for the documentation, they can go here.

To answer your question, this is the relevant section of the documentation: https://agda.readthedocs.io/en/latest/getting-started/installation.html#installation-of-the-development-version

**Comment by pnlph** [comment]
Thank you Ulf. I already read that section but it was not helping. I will give it a try in the list.

I agree that these kind of questions do not belong to the issue tracker, I still think that it would be great to activate github's discussions beta #4557
