### ISSUE TITLE
Add Agda to Stackage. We need a Stackage maintainer for Agda.

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#4672]
From stack users I guess the easiest is to add Agda to Stackage. In the past Agda was in Stackage, but Agda 2.6.1 is not. We need a Stackage maintainer for Agda.

_Originally posted by @asr in https://github.com/agda/agda/pull/4664#issuecomment-633236470_

**Comment by andreasabel** [comment]
@asr: You seem to maintain the `stack-n.n.n.yaml` files.  What would it take to add Agda to Stackage?  What would be the job of the Stackage maintainer?

**Comment by wenkokke** [comment]
Please assign this to me.

**Comment by asr** [comment]
> @asr: You seem to maintain the `stack-n.n.n.yaml` files.

No really. I need to create them when I add support for a new version of GHC.

> What would it take to add Agda to Stackage? What would be the job of the Stackage maintainer?

See [Add your maintained packages to stackage](https://github.com/fpco/stackage/blob/master/MAINTAINERS.md#adding-a-package).

**Comment by andreasabel** [comment]
I checked what is missing to add Agda to stackage:
```
$ ./verify-package Agda-2.6.1.1
...
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- ./

Selected resolver: nightly-2020-10-10
Resolver 'nightly-2020-10-10' does not have all the packages to match your requirements.
    aeson version 1.5.4.1 found
        - Agda requires >=1.1.2.0 && <1.5
    data-hash not found
        - Agda requires >=0.2.0.0 && <0.3
    equivalence not found
        - Agda requires >=0.3.2 && <0.4
    geniplate-mirror not found
        - Agda requires >=0.6.0.6 && <0.8
    strict version 0.4 found
        - Agda requires >=0.3.2 && <0.4
    Using package flags:
        - Agda: FlagName "cpphs" = False, FlagName "debug" = False, FlagName "enable-cluster-counting" = False
```
- [ ] `aeson` and `strict`: The upper bound has already been relaxed in master (see #4838) commits 292f7d8c3def7e69ce9e79c67c895d6a4956dc5f and 0497ec9fdde159a56ee42821e500b52d66374201 can be cherry-picked to Agda 2.6.1.2.
  <del>Maybe we can just edit the bounds on hackage to spare us from going through the release procedure.</del>
- [ ] `data-hash`: The newest version 0.2.0.1 still builds with ghc 8.10, not sure why it is no longer in stackage nightly.
  I ran it through `verify-package` without problems.
- [ ] `equivalence` depends on `STMonadTrans`: I pinged both maintainers, see https://github.com/pa-ba/equivalence/issues/11 and https://github.com/josefs/STMonadTrans/issues/21 .
- [x] `geniplate-mirror`: We have to add this, I suppose (no one else uses it...).
  Runs through `verify-package` without problems.

**Comment by andreasabel** [comment]
@L-TChen : Could you please (as maintainer) add `geniplate-mirror` to stackage nightly, or tell me to do it.  It runs through `verify-package` without problems.

**Comment by L-TChen** [comment]
> @L-TChen : Could you please (as maintainer) add `geniplate-mirror` to stackage nightly, or tell me to do it. It runs through `verify-package` without problems.

Sure I will do it tomorrow. By the way, are we actually using `Data.Generics.Geniplate` anywhere? I remember some commit by you tried to remove many Template Haskell. Maybe I am mistaken.

**Comment by andreasabel** [comment]
> By the way, are we actually using `Data.Generics.Geniplate` anywhere? I remember some commit by you tried to remove many Template Haskell. 

Indeed, it will be obsolete from 2.6.2.  However, 2.6.1.2 (#4749) will be basically 2.6.1(.1) with only some obstacles to compilation removed (and maybe 1-2 critical bug fixes).

**Comment by L-TChen** [comment]
`geniplate-mirror` will be available on Stackage soon, see https://github.com/commercialhaskell/stackage/issues/5692.

**Comment by andreasabel** [comment]
I now can install Agda from stackage with
```
stack install --resolver nightly Agda
```

However, without the explicit `resolver` flag I failed, see https://github.com/commercialhaskell/stackage/pull/5715#issuecomment-721260644 .

**Comment by andreasabel** [comment]
To add Agda to LTS, I filed
- STMonadTrans: https://github.com/commercialhaskell/lts-haskell/issues/306
- equivalence: https://github.com/commercialhaskell/lts-haskell/issues/307
- data-hash: https://github.com/commercialhaskell/lts-haskell/issues/308
- geniplate-mirror: https://github.com/commercialhaskell/lts-haskell/issues/309

**Comment by asr** [comment]
The current stack files for the different versions of GHC are used for developing Agda. We should add stack files only for using Agda. We do it for `Agda.cabal` in release time.

**Comment by L-TChen** [comment]
@asr: Can you explain a bit what the non-development version should be?

**Comment by asr** [comment]
@L-TChen, for example, `stack-8.4.4.yaml` includes

```
extra-deps:
- QuickCheck-2.13.2
- tasty-silver-3.1.13
- filepattern-0.1.2
```

The above libraries are not need for installing Agda with `stack` from a released version on Hackage (the two first libraries are used for the test suite and the last one is used for installing the `fix-whitespace` program).

**Comment by L-TChen** [comment]
I think that’s fine. These packages are not needed unless the option `--test` is specified. The section `extra-deps` is used to resolve the dependency as the specified resolver may not include desired packages.

One particular change I’d like to have is to move `size-solver` to `extra-deps` so that `stack build` does not build `size-solver`. I am not sure why it has been in the section of `packages`.

**Comment by asr** [comment]
See also #5112.

**Comment by jespercockx** [comment]
TIL that I should add `--resolver nightly` to `stack install Agda` to make it work without any further configuration (see https://agda.zulipchat.com/#narrow/stream/238741-general/topic/.22configuration.20has.20no.20specified.20version.22.20with.20stack.20install/near/223663802). Should we add this to the documentation somewhere (at least until this issue is solved)? Or can we expect `stack install Agda` to just work with the default resolver in the near future?

**Comment by jespercockx** [comment]
Note that all four issues created by @andreasabel are now closed, so perhaps we can move forward on this issue now?

**Comment by asr** [comment]
> Please assign this to me.

@wenkokke, had you some problem adding 2.6.1.3 to Stackage?

**Comment by andreasabel** [comment]
I filed https://github.com/commercialhaskell/stackage/pull/5865.

> > Please assign this to me.
> 
> @wenkokke, had you some problem adding 2.6.1.3 to Stackage?

Since Wen didn't work on this, I effectively took it over in October.
@wenkokke, I unassign you now, as I have some routine with stackage now.  If you want to get back into business, no problem.

**Comment by asr** [comment]
When this issue be closed, I suggest to make an announce on the mailing lists.

**Comment by andreasabel** [comment]
Hooray, Agda is in stackage nightly! https://www.stackage.org/nightly-2021-02-09/package/Agda-2.6.1.3

I'll file an issue to get Agda into LTS, too.

**Comment by andreasabel** [comment]
> I'll file an issue to get Agda into LTS, too.

Filed: https://github.com/commercialhaskell/lts-haskell/issues/312

**Comment by andreasabel** [comment]
We are part of LTS 17.5! https://www.stackage.org/lts-17.5/package/Agda-2.6.1.3
