### ISSUE TITLE
Injectivity analysis performs fatal reduction of rhs 

### ISSUE THREAD

**Issue by tomdjong** [agda/agda#4676]
Consider the following code.

```Agda
data ℕ : Set where
  zero : ℕ
  succ : ℕ → ℕ

-- For simulating a term that is very slow to typecheck.
{-# TERMINATING #-}
stuck : ℕ
stuck = stuck

induction : (A : (n : ℕ) → Set)
          → A zero
          → ((n : ℕ) → A (succ n))
          → (n : ℕ) → A n
induction A a h zero = a
induction A a h (succ n) = h n

-- Agda is OK with this.
f : ℕ → ℕ
f n = stuck

-- Agda is also OK with this.
g : ℕ → ℕ
g = induction (λ _ → ℕ) stuck (λ _ → stuck)

-- Typechecking this takes forever.
h : ℕ → ℕ
h zero = stuck
h (succ n) = stuck

-- Typechecking this takes forever.
h : ℕ → ℕ
h zero = stuck
h (succ n) = n
```

I find it confusing that `f` and `g` are fine, both `h` and `h'` aren't. Why does this happen exactly? Is this intended or a bug?

**Comment by andreasabel** [comment]
Agda analyses `h` to see whether it is invertible, i.e., whether from e.g. `h a = zero` we could learn something about `a`.  To this end, Agda checks whether the rhss of `h` are all headed by distinct constructors.  To check this, Agda reduces the rhss.  Which is fatal in case of `stuck`. 

There is currently no option/pragma to turn off the inversion ("injectivity") analysis.
Would this be essential for what you are doing?

**Comment by nad** [comment]
Apparently `--inversion-max-depth=0` is not sufficient to make Agda accept the code in the OP.

**Comment by tomdjong** [comment]
> Agda analyses `h` to see whether it is invertible, i.e., whether from e.g. `h a = zero` we could learn something about `a`. To this end, Agda checks whether the rhss of `h` are all headed by distinct constructors. To check this, Agda reduces the rhss. Which is fatal in case of `stuck`.
> 
> There is currently no option/pragma to turn off the inversion ("injectivity") analysis.
> Would this be essential for what you are doing?

I see, thank you! I don't think I really need such an option, but out of curiosity: is anything like it planned for future releases of Agda?

**Comment by UlfNorell** [comment]
> Apparently --inversion-max-depth=0 is not sufficient to make Agda accept the code in the OP.

This option affects the number of times inversion invoked on a problem, it doesn't affect whether the analysis is performed. Since it can be different in different modules, it doesn't make sense to turn off the analysis even if it's set to zero. Adding a flag would be easy enough though.

**Comment by andreasabel** [comment]
> I see, thank you! I don't think I really need such an option, but out of curiosity: is anything like it planned for future releases of Agda?

Well, then, no. 😉   We are busy enough implementing features people need...
