### ISSUE TITLE
Cubical: giving seems to skip the boundary condition check for extended lambdas

### ISSUE THREAD

**Issue by ayberkt** [agda/agda#4679]
Here is an example:

```agda
{-# OPTIONS --safe --cubical #-}

open import Cubical.Core.Everything
open import Cubical.Foundations.Prelude
open import Cubical.Data.Unit
open import Cubical.Data.Empty
open import Cubical.Data.Unit

data Foo : Type₀ where
  bar    : Unit → Foo
  baz    : Unit → Foo
  squash : (x y : Foo) → x ≡ y

bar≢baz : (x y : Unit) → bar x ≡ baz y → ⊥
bar≢baz tt tt p =
  {! subst (λ { (bar _) → Unit ; (baz _) → ⊥ ; _ → ⊥ }) p tt !}
```

When this proof is given using `C-c C-SPC`, Agda accepts it. When the file is loaded afterwards, errors are reported.

**Comment by andreasabel** [comment]
It seems like some conditions are not checked on the extended lambda when you give it.  For comparison, if you try to define the extended lambda as function, it is rejected.
```agda
{-# OPTIONS --safe --cubical #-}

open import Cubical.Core.Everything using (Type₀; _≡_)
open import Cubical.Foundations.Prelude using (subst)
open import Cubical.Data.Empty using (⊥)
open import Cubical.Data.Unit using (Unit; tt)

data Foo : Type₀ where
  bar    : Unit → Foo
  baz    : Unit → Foo
  squash : (x y : Foo) → x ≡ y

bar≢baz : (x y : Unit) → bar x ≡ baz y → ⊥
bar≢baz tt tt p =
   subst {! λ { (bar _) → Unit ; (baz _) → ⊥ ; _ → ⊥ } !} p tt
   -- where
   -- P : Foo → Type₀
   -- P (bar _) = Unit
   -- P (baz _) = ⊥
   -- P _  = ⊥
   -- -- P p x != ⊥ of type Set
   -- -- when checking the definition of P
```
Btw, the error is rather incomprehensible, there should be a better localization than `when checking the definition of P`.  Something like `when checking the end-point conditions of definitions P`.

**Comment by Saizan** [comment]
Does give skip some part of coverage checking?

**Comment by andreasabel** [comment]
I do not think so.  Give invokes the type checker, and for extended lambdas this invokes `checkFunDef'` which includes coverage checking (which succeeds).

Is `P p x != ⊥ of type Set` coming from the coverage checker or rather some other boundary check?!

**Comment by Saizan** [comment]
Why the interrobangs?

it's coming from `checkIApplyConfluence_`

**Comment by andreasabel** [comment]
> interrobangs

Ah, learned a new word.  Is there also a word for "!?"?   😆 

> it's coming from `checkIApplyConfluence_`

This is explicitly invoked in `checkExtendedLambda` (after coverage checking is complete).

**Comment by andreasabel** [comment]
Ah, but it is not executed since it is under condition `whenNothingM (asksTC envMutualBlock) $`!

**Comment by andreasabel** [comment]
The fix is to clear `envMutualBlock` before invoking `checkExpr` in the `giveExpr` function.

**Comment by Saizan** [comment]
How does this work for other `mutualChecks` ? 

I mean, the reason there a `whenNothingM (asksTC envMutualBlock) $` condition here is that in a mutual block you'll normally get `checkIApplyConfluence_` checked by the `mutualChecks`.

**Comment by Saizan** [comment]
Apparently other `mutualChecks` are also skipped by `give`, e.g. giving in the hole below does not report an error until reload.

```agda
data D : Set where
  con : {! (D → D) !} → D
```

I suppose this is less of a problem in practice.

**Comment by andreasabel** [comment]
Yes, this is old issue #118.
In your comment for `checkExtendedLambda` you ask if there should be more checks. 
But `give` also does some checks, e.g. termination (in function `BasicOps.redoChecks`).  We have not included positivity here yet (but I think for no real reason).
