### ISSUE TITLE
Type error due to --no-syntactic-equality

### ISSUE THREAD

**Issue by nad** [agda/agda#4684]
Is the idea that code that typechecks without `--no-syntactic-equality` should also typecheck with this option, given enough time and space? I tried to type-check the standard library using `--no-syntactic-equality`, but encountered an error:
```
Data/Vec/N-ary.agda:105,21-22
Unexpected implicit argument
when checking the clause left hand side
uncurry-∀ⁿ {a} {A} {ℓ} n
```

**Comment by UlfNorell** [comment]
I would assume this is #525. Do you have reason to believe it's not?

**Comment by nad** [comment]
I don't know.

**Comment by nad** [comment]
Why did you close this issue? If code that typechecks without `--no-syntactic-equality` should also typecheck with this option, given enough time and space, then I have identified a bug.

**Comment by jespercockx** [comment]
I think @UlfNorell 's point was that since it's a likely duplicate, we do not need a separate issue for it. OTOH issue numbers are free, so I don't see the harm in leaving this open.

**Comment by jespercockx** [comment]
However, in order to actually fix this issue it would be useful to have a smaller example that still exhibits the problem.

**Comment by UlfNorell** [comment]
Issue numbers are free, but open issues does have an attention cost. Without a smaller test case that suggests this isn't a duplicate I see no point in keeping it open.

**Comment by nad** [comment]
The other issue does not mention `--syntactic-equality`, and is not a bug report but an enhancement request (from 2011).

We can close this issue if we decide that syntactic equality is not just an optimisation.

**Comment by jespercockx** [comment]
I believe the fact that Agda currently relies on the conversion checker to insert hidden arguments is a bad design. Inserting implicit arguments is part of the elaboration process from the surface language into the core language, while conversion checking should act only on fully elaborated core syntax (except for the possible presence of unsolved metas). I wonder if fixing this design flaw would also fix this issue.

**Comment by jespercockx** [comment]
Actually the insertion of implicit arguments during conversion checking does not seem to be the problem here. Rather, there seems to be a problem with the generalized arguments of `curryⁿ` and `_$ⁿ_`. For some reason, in the types of these two functions, Agda does manage to generalize over `A` and `B` but not over their levels. This produces unsolved metas that cause the error later on in the file. So there is no relation to #525 after all.

**Comment by UlfNorell** [comment]
I can check `Data.Vec.N-ary` with `--no-syntactic-equality` now, so it looks like this has been fixed.
