### ISSUE TITLE
[Github Actions] Installing wget is unnecessary on Windows

### ISSUE THREAD

**Issue by EdNutting** [agda/agda#4691]
The following installs are unnecessary steps - Windows runners already include MSYS2 which includes wget.

* Nightly: https://github.com/agda/agda/blob/c5a36ee4ef4780d0c2980a4e1a04355239c42f34/.github/workflows/nightly.yml#L112
* Stack: https://github.com/agda/agda/blob/c5a36ee4ef4780d0c2980a4e1a04355239c42f34/.github/workflows/stack.yml#L110

See https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md#MSYS2

### Suggested fix

Use `C:\msys64\usr\bin\wget.exe` instead. Note: MSYS2 is not included in the path by default, so the full path should be used. Alternatively, you could use an earlier run step to add MSYS2 to the path, but this is not recommended as potential conflicts are unknown.

**Comment by EdNutting** [comment]
It may also be possible to eliminate the installation of haskell-stack, since stack is already included in the build. I'm not sure whether there's a concern about stack versions though?

**Comment by EdNutting** [comment]
I've got a draft of this latter point - which uses the latest Stack as per Github - on https://github.com/EdNutting/agda/tree/ci-windows-stack

However, for some reason `stack` rejects the `--flag Agda:enable-cluster-counting` option. I can't understand why stack behaves differently on Windows to Linux. This happens on my local machine too - Stack rejects the flag option for no apparent reason. ~~I am starting to wonder whether the package being called 'Agda' with a capital 'A' might be causing some kind of hidden case-sensitivity issue? That's wild speculation though. Anyone with a brighter idea please let me know!~~

**Comment by EdNutting** [comment]
It appears that placing the flag into the stack config works. So there's some kind of issue with specifying flags on the Windows / Powershell command line.

**Comment by EdNutting** [comment]
Okay, I think I figured out the cause and a hacky-fix. I don't understand Powershell too well but basically, when you call something like `stack build ${ARGS}` the command that actually gets issued is `stack build "the args"` - the extra double-quotes cause stack to treat everything as a single argument which it thinks is a package path, thus the confusing error message. If anyone knows how to stop Powershell from being too clever like this, please let me know. I'm sure there must be a better way than splitting every argument by spaces and "splatting" them into the command (yes, splatting is apparently a real Powershell thing...)

**Comment by andreasabel** [comment]
I suppose this issue is still open as I only merged one PR.  The semantics of linking several PRs to one issue seems to be disjunctive rather than conjunctive.

**Comment by EdNutting** [comment]
This issue was resolved with the merge of #4695

**Comment by aryairani** [comment]
> but this is not recommended as potential conflicts are unknown.

Note: for anyone else with the same problem who finds this top hit and tries this solution, and is super confused like I was, 
`C:\msys64\usr\bin\wget.exe` has a different notion of `/tmp` (and probably other file system mounts) than the rest of the stuff on the path.

So you can `C:\msys64\usr\bin\wget.exe` something to `/tmp` and then it doesn't appear to be in `/tmp`.

I just switched to `curl -L` instead.
