### ISSUE TITLE
Transient internal error

### ISSUE THREAD

**Issue by nad** [agda/agda#4697]
I have recently started encountering the following internal error:
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Monad/Signature.hs:726
```
With `-vimpossible:10` on I got a little more information:
```
Ambiguous name: recCon-NOT-PRINTED
```
So far the error has disappeared when I have restarted Agda.

**Comment by andreasabel** [comment]
Can we maybe finally get rid of this `recCon-NOT-PRINTED` hack?

**Comment by andreasabel** [comment]
Is this issue still observable?  (ping @nad)

**Comment by nad** [comment]
I don't recall seeing this recently.
