### ISSUE TITLE
Constraint solving in heterogenous situations

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#470]
```agda
module Solve where

data Bool : Set where
  true false : Bool

_and_ : Bool → Bool → Bool
true  and x = x
false and x = false

infixr 5 _∷_

data Foo : Bool → Set where
  []  : Foo true
  _∷_ : ∀ {b} (x : Bool) → Foo b → Foo (x and b)

Baz : Bool → Set
Baz true = Bool
Baz false = Foo false

data Bar : ∀ {b} → Foo b → Set where
  []  : Bar []
  _∷_ : ∀ {b} {foo : Foo b} {x} (g : Baz x) → (bar : Bar foo) → Bar (x ∷ foo)

foo : Foo false
foo = false ∷ true ∷ []

bar : Bar foo
bar = (false ∷ []) ∷ false ∷ [] -- ← is yellow

{-
_59 := _55 ∷ false ∷ [] [blocked by problem 75]
[75] ["apply" (_53 ∷ true ∷ [])] == ["apply" (false ∷ true ∷ [])] : Foo 
(_53 and (true and true)) → Set [blocked by problem 76]
[76] (_53 and (true and true)) = false : Bool
_54 := false ∷ [] :? Baz _53
-}
```
Here, the solver's equation 75 is blocked by 76, but 76 can't be solved in isolation, so things turn yellow. However, if the solver ignored 76 and unified _53 with false, then it could solve 76. Ulf and I spoke about it on 
IRC and he said it might be possible to have the solver first check that the "shape" of things being unified in 75 could be checked to make sure the unification makes sense, then they could be unified, then 76 could be attempted.

Original issue reported on code.google.com by `pumpkingod@gmail.com` on 22 Sep 2011 at 3:33

**Comment by andreasabel** [comment]
For the new example I get:
```
_25 : Bool 
_30 : Foo (_25 and true) 

Failed to solve the following constraints:
  _30 := false ∷ [] [blocked on problem 32]
  [32, 33] false = _25 and true : Bool
```
Could the proposal be fleshed out to see what it takes to implement this?

**Comment by vlopezj** [comment]
The test case given in https://github.com/agda/agda/issues/470#issuecomment-129023473 seems to type-check at least since commit ba4354f2c47a534ff9fc543fc7824eff222181f6.

**Comment by gallais** [comment]
Can you please add it to the test suite?
