### ISSUE TITLE
Case-split generates invalid code

### ISSUE THREAD

**Issue by gallais** [agda/agda#4704]
For some reason Agda does not bother generating a fresh name for `xs` in `xs ∷ʳ′ x`.

```agda
open import Agda.Builtin.List
open import Agda.Builtin.Nat

infixl 6 _∷ʳ_

_∷ʳ_ : {A : Set} → List A → A → List A
[]        ∷ʳ x = x ∷ []
(hd ∷ tl) ∷ʳ x = hd ∷ tl ∷ʳ x

infixl 5 _∷ʳ′_

data InitLast {A : Set} : List A → Set where
  []    : InitLast []
  _∷ʳ′_ : (xs : List A) (x : A) → InitLast (xs ∷ʳ x)

initLast : {A : Set} (xs : List A) → InitLast xs
initLast []               = []
initLast (x ∷ xs)         with initLast xs
... | []       = [] ∷ʳ′ x
... | ys ∷ʳ′ y = (x ∷ ys) ∷ʳ′ y

f : (xs : List Nat) → Set
f xs with initLast xs
... | p = {!!}
```

```agda
-- splitting on `p` generates the following
-- ... | [] = ?
-- ... | xs ∷ʳ′ x = ?

-- and that leads to a type error coming from the bad naming
-- xs != xs ++ x ∷ [] of type List Nat
-- when checking the clause left hand side
-- splitView.with-8 xs (xs ∷ʳ′ x)
```

**Comment by andreasabel** [comment]
2.6.0 still produces the valid:
```agda
f : (xs : List Nat) → Set
f xs with initLast xs
f .[] | [] = {!!}
f .(xs ∷ʳ x) | xs ∷ʳ′ x = {!!}
```
The release notes for 2.6.1 say:
> Agda will now try to preserve the ellipsis (`...`) during case splitting when possible. To manually expand the ellipsis, you may ask Agda to case split on the special identifier `.`.

Unfortunately, this does not lead me to a commit since `doc/release-notes/2.6.1.md` has no history.

**Comment by andreasabel** [comment]
Because of #4705 there seems to be no direct way to trace this change back to the commits that introduced it.  There is also no issue number for this change linked in the release notes...

The issue would have been #2589.

**Comment by andreasabel** [comment]
This is a unfortunate side effect of restoring the ellipsis: the dot patterns get lost, thus, the original lhs does not get refined and keeps its original names, which then clash with the names in the patterns.

I think rather than modifying the fix of #2589, we should modify the somewhat naive handling of the ellipsis.  We should allow to shadow pattern variables which are covered by the ellipsis.

**Comment by jespercockx** [comment]
What do you mean with "the somewhat naive handling of the ellipsis"? I agree that it should be allowed to shadow variables from the parent clause in the `with` clause, rather than assuming that one of them is a dot pattern (as Agda does now).

**Comment by andreasabel** [comment]
> What do you mean with "the somewhat naive handling of the ellipsis"? I agree that it should be allowed to shadow variables from the parent clause in the `with` clause, rather than assuming that one of them is a dot pattern (as Agda does now).

Exactly that.

The naive handling of ellipses is that we literally replace them by the parent clause lhs in the nicifier.  We have more leeway if we let them survive until scope checking.  Then we can create shadowed abstract names for the names stemming from the ellipsis that are shadowed by the pattern variables.

**Comment by andreasabel** [comment]
I propose to fix it like this:
* Ellipses survive the nicifier that only attaches their resolution, but does not replace them.
* The scope checker processes `AppP` right to left so that ellipses are processed last.  This means that all the with-pattern variables are in scope when we come to the ellipsis.
* While checking the ellipsis, we replace shadowed pattern variables by fresh abstract names which are bound to concrete name `_`. This mode switching is facilitated by a flag in `TCEnv`.

UPDATE: Unfortunately, there is a complication: We parse lhss into `LHSCore`, which cannot hold an ellipsis at the moment.
Also, it is a bit silly that we operator-parse the same lhs over and over again, in each expansion of an ellipsis.
```agda
complicated lhs with byte
... | b0 = ?
... | b1 = ?
...
```
This will operator-parse the `complicated lhs` 256 times.

**Comment by jespercockx** [comment]
We already keep all the information from ellipsis in the current representation, so there is no need to preserve it any further. In particular, after my fix of #2589, there is a `lhsExpandedEllipsis` field that remembers how many of the patterns were created by expansion of an ellipsis (if any). This is preserved in the abstract and internal syntax through the `LHSInfo` of the clause.

To handle the shadowing properly, we also have a mechanism for that already: the `scopeVarsToBind` in the scope checker gathers all the variables that should be bound "in one go" (so without any shadowing between them). To enable shadowing, we just need to process the patterns block by block (using `isWithP` from `Agda.Syntax.Concrete.Pattern` to detect the boundaries between blocks) and insert calls to `bindVarsToBind` in between to empty the `scopeVarsToBind`.

**Comment by andreasabel** [comment]
> We already keep all the information from ellipsis in the current representation, so there is no need to preserve it any further. In particular, after my fix of #2589, there is a `lhsExpandedEllipsis` field that remembers how many of the patterns were created by expansion of an ellipsis (if any). This is preserved in the abstract and internal syntax through the `LHSInfo` of the clause.

Yes, maybe this would be sufficient.  In general, I do not like the collapsing of structures to numbers in auxiliary fields.  I would like the structure of the AST represent the structure directly.  This is why I turned `EllipsisP` into a parenthesis around the expanded ellipsis.  This is easier to understand.  Further, I equipped the `LHSWith` constructor of `LHSCore` with a flag whether the core came from an ellipsis.

> To handle the shadowing properly, we also have a mechanism for that already: the `scopeVarsToBind` in the scope checker gathers all the variables that should be bound "in one go" (so without any shadowing between them). To enable shadowing, we just need to process the patterns block by block (using `isWithP` from `Agda.Syntax.Concrete.Pattern` to detect the boundaries between blocks) and insert calls to `bindVarsToBind` in between to empty the `scopeVarsToBind`.

I wish I had known about this indirection for the pattern variables.  I found it out the hard way.  You should document this better!  E.g. comment the `scopeVarsToBind` field.

**Comment by andreasabel** [comment]
I got stuck on this...

**Comment by jespercockx** [comment]
I can't reproduce this issue on current master: if I split on `p` in the example from the OP, I get
```agda
f : (xs : List Nat) → Set
f xs with initLast xs
... | [] = {!!}
... | xs₁ ∷ʳ′ x = {!!}
```
as expected. If I first expand the ellipsis and then do the case split, the result is likewise correct. So it seems there is nothing left to do but to add a test case.

**Comment by jespercockx** [comment]
Ah never mind, I had the new flag `--keep-pattern-variables` enabled in my Emacs configuration. If I remove it, I can reproduce the problem. I'll investigate further.

**Comment by jespercockx** [comment]
I have found a fix for the problem by using `bindVarsToBind`( PR incoming). With this fix, the following code is accepted:
```agda
f : (xs : List Nat) → Set
f xs with initLast xs
... | [] = {!!}
... | xs ∷ʳ′ x = {!!}
```
However, I still have a question: should the following also be accepted or not?
```agda
f : (xs : List Nat) → Set
f xs with initLast xs
f xs | [] = {!!}
f xs | xs ∷ʳ′ x = {!!}
```
In other words, should it be possible to shadow variables that come from the same clause if they were bound "before the with"?

**Comment by JacquesCarette** [comment]
I'm not so keen on such shadowing - it leads to hard to debug code, especially when both variables are of the same type and the line of code in question is much longer.  [I must admit I'm not that keen on the shadowing in the accepted code either...]

Having said that, I'm keenest on consistency. So if Agda has a particular set of (simple) shadowing rules, they should be followed consistently, even if that consistency would imply going in the direction that I'm less keen on.

**Comment by jespercockx** [comment]
I agree. As I understand the rule we use is that variables from the same clause cannot be shadowed, but other variables (e.g. module parameters) can be. If that's the rule then my second example shouldn't be accepted. That's more difficult to implement, but I think its worth it to preserve consistency, as you say.

**Comment by andreasabel** [comment]
I think it makes sense that variables not visible to the eye can be shadowed, like those only existing internally from the expansion of an ellipsis.  Actually, not allowing these to be shadowed would be irritating.

For the second example, I think we shouldn't allow shading within one clause, even if there are separate (`with`) compartments.

**Comment by jespercockx** [comment]
Yes, I now see the second example shouldn't be accepted. I have pushed my proposed fix to https://github.com/jespercockx/agda/tree/issue4704, this accepts the first example and rejects the second one. It is *almost* working, but there is still a bad interaction with `rewrite` which causes the stdlib test to fail. I'll try to find what's the cause.

**Comment by JacquesCarette** [comment]
I use `...` more as "don't repeat information that's obvious" so, to me, those variables are there. My eyes don't work on a line-by-line basis! So I disagree. [More as a point of information from how some users do things, rather than really as a system-building recommendation.]
