### ISSUE TITLE
Internal error in TypeChecking/Records.hs

### ISSUE THREAD

**Issue by endobson** [agda/agda#4706]
I got the following error message:

```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Records.hs:611
```

I don't have a minimized reproduction

But the following seemed to be the issue

```
   antisym-Subset {as} {bs} s1@(squash-inj s1) (squash s2 s2' j) =
    trunc _ _ (antisym-Subset s1 s2) (antisym-Subset s1 s2') j
```

If I change this to
```
   antisym-Subset {as} {bs} s1@(squash-inj _) (squash s2 s2' j) =
    trunc _ _ (antisym-Subset s1 s2) (antisym-Subset s1 s2') j
```

the error goes away. So the two 's1's in the pattern seem to be the cause.

**Comment by andreasabel** [comment]
Looks like #4631.  Do you get the error also on the development version (latest master from github).
