### ISSUE TITLE
Ambiguous module name when the file has the same name as the library's module

### ISSUE THREAD

**Issue by pnlph** [agda/agda#4708]
I have a project with a folder named `reflection`. How can I specify that I want to refer to the `Agda.Builtin.Reflection`module?
```agda
module reflection where
open import Agda.Builtin.Reflection
```

Throws this error:
```
Ambiguous module name. The module name reflection could refer to any of the following files:
.../Documents/GitHub/agda-stdlib/src/Reflection.agda
.../Documents/Agda/agda-experiments/reflection.agda
```

**Comment by pnlph** [comment]
I think that the clash is not because the name of the folder, but because of the name of the file itself. This means that one cannot name a file with the same name as a library's module?

**Comment by guillaumebrunerie** [comment]
Could you give a self-contained example? I tried to create a file called `reflection.agda` with the two lines you gave above and it loads correctly for me.

**Comment by pnlph** [comment]
That was self-contained, I thought... 😅 

I have also the `agda-stdlib` in my `.agda-lib` file.

**Comment by gallais** [comment]
What's your OS? Is it another instance of macOS being confusing because its
file system is case insensitive?

**Comment by guillaumebrunerie** [comment]
Oh, good point, I can reproduce it now (on Linux) by calling the file and the module `Reflection`.

**Comment by pnlph** [comment]
> What's your OS? Is it another instance of macOS being confusing because its
> file system is case insensitive?

High Sierra

**Comment by guillaumebrunerie** [comment]
Which part of the code is highlighted with the error? Do you also get the error if you have only the first line `module reflection where`? Or even just with an empty `reflection.agda` file?

**Comment by guillaumebrunerie** [comment]
If you have the standard library loaded by default, that means you have a `Reflection` module already available (try `import Reflection` in a brand new file somewhere else and it should work). So it is not especially surprising that Agda forbids you to create a new file with the same name, because then there would be no way for you to import your `Reflection` module from a different file. Of course, the case-insensitivity of the file system adds to the confusion.

**Comment by pnlph** [comment]
> Which part of the code is highlighted with the error?

Row 1 and columns 8-18 are highlighted for me. That corresponds to the name `reflection` of the module.

> Do you also get the error if you have only the first line `module reflection where`?

Yes.

> Or even just with an empty `reflection.agda` file?

Yes.

**Comment by pnlph** [comment]
Thanks! I think that now I get it, but then we have two problems when a library, e.g. `agda-stdlib`, is loaded:

First, the case-insensitivity of my OS does not allow me to have a `reflection` module. I think this has to do with #4678.

Second, even if it works, I cannot define a module `Reflection` _and_ load the `agda-stdlib`. But for me it is indeed surprising, because I expect that some kind of _absolute naming_ works and distinguishes my `Reflection` module from the `Agda.Builtin.Reflection` so that I could have names from both in a single scope. Maybe it has to do with #4083 ?

The second maybe could be solved with @andreasabel  [scoping proposal](https://github.com/andreasabel/agda-scope)?

**Comment by guillaumebrunerie** [comment]
I think that #4029 is the relevant issue here (for the second problem).

**Comment by gallais** [comment]
Oh if you're loading the stdlib then it makes a lot of sense: the library
is already defining such a module: http://agda.github.io/agda-stdlib/Reflection.html

**Comment by pnlph** [comment]
> Oh if you're loading the stdlib then it makes a lot of sense: the library
> is already defining such a module: http://agda.github.io/agda-stdlib/Reflection.html

But the user may want to load the `agda-stdlib` file _and_ define an own `Reflection`module.

**Comment by andreasabel** [comment]
Did it really say this?
> Ambiguous module name. The module name reflection could refer to any of the following files:
> .../Documents/GitHub/agda-stdlib
> .../Documents/Agda/agda-experiments/reflection.agda

The first alternative does not mention "reflection".

**Comment by pnlph** [comment]
> Did it really say this?

No, sorry 🤦 I updated the original error above.

**Comment by andreasabel** [comment]
Currently you cannot locally overwrite a module from a library.  If you have module `X.Y.Z` in one of your dependencies (field `depend:` in your local `.agda-lib` file), you cannot have a module `X/Y/Z` in you local development (field `include:` in your local `.agda-lib`file).
