### ISSUE TITLE
Emacs command to show goal with constraints on it

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#471]
```
Sometimes it's very frustrating to be told my goal is e.g., a Nat, and then to 
provide a Nat, and then to have Agda tell me "nope, wrong Nat, try again!".

I just discovered the wonders of the C-c C-= view, and was wondering if it 
could be magically integrated with the goal viewer, so that we can see the 
goal, the context, and any constraints (even transitive ones, maybe) that 
involve the goal. This would make interactive proving enormously more 
intuitive, I think.
```

Original issue reported on code.google.com by `pumpkingod@gmail.com` on 22 Sep 2011 at 3:57

**Comment by jespercockx** [comment]
I wanted to submit the enhancement request below but Github notified me of the existence of this existing issue.

> When you load a file, you get a list of all unsolved constraints in that file. However, the constraints are hidden after you ask for more information about a particular goal with `C-c C-,`. Perhaps we could list all constraints that are somehow related to the current goal (either because the constraint mentions the interaction meta, or because it is blocked on it).

**Comment by jespercockx** [comment]
Feature added in https://github.com/agda/agda/commit/abb4bbd56d54ee06232476ffbfbe83fd8f97d4cc
