### ISSUE TITLE
Regression in instance search due to normalization

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#4710]
Some code of mine uses a lot more memory since #4531 was merged. Unfortunately, I haven’t been able to minimize it and the code is somewhat complicated, but I can try to explain a bit what is going on. The code is available at https://github.com/guillaumebrunerie/general-type-theories/tree/debug-instance-arguments, and I’m going to be looking at the file `examples.agda`.

The code is using instance arguments quite heavily, in particular the `apr` function takes an instance argument which is typically a tree made of nested Σ-types, with either Unit or an identity type of the form `a ≡ a` at each leaf. Pairing, reflexivity, and tt are marked as instances, so instance search should work. For instance, one of those instance arguments in `TypingRuleBeta` is `{{((tt , (tt , tt)) , ((tt , refl) , tt)) , ((tt , refl) , (refl , tt)) , tt}}`. Those nestings of Σ-types are themselves generated by Agda code, so they depend on the other arguments of `apr`.

In Agda 2.6.0.1 I can type check `examples.agda` and its dependencies in ~40 seconds and ~450M of memory, but in current Agda I killed it after memory usage reached 5G. I can make it work with current Agda by explicitly giving the two biggest instance arguments in `TypingRuleBeta` (commented out in the file), but it still takes 4.8G of memory.

**Comment by jespercockx** [comment]
In general it seems like a better strategy to not normalize things eagerly, but unfortunately in this particular case it seems to lead to worse performance. It's not clear there's anything we can do to address this in general. However, if you have a small test case then we might be able to find a different way to improve the performance.
