### ISSUE TITLE
error when computing primQNameToWord64s of a Name

### ISSUE THREAD

**Issue by pnlph** [agda/agda#4714]
`C-c C-n primQNameToWord64s (quote _≡_) RET` computes `12 , 1335258922519917603` but the following self-contained code fails:
```agda
open import Agda.Builtin.Reflection using (primQNameToWord64s)
open import Agda.Builtin.Equality using (_≡_; refl)
open import Agda.Builtin.Sigma using (_,_)
_ : primQNameToWord64s (quote _≡_) ≡ (12 , 1335258922519917603)
_ = refl
```
with error:
```
Agda.Builtin.Nat.Nat != Agda.Builtin.Word.Word64
when checking that the expression 12 has type
Agda.Builtin.Word.Word64
```

**Comment by gallais** [comment]
The type error is legitimate: you are trying to compare ~~apples to oranges~~
words to natural numbers.

You can make it go away by converting the natural literals to words:

```agda
open import Agda.Builtin.Reflection using (primQNameToWord64s)
open import Agda.Builtin.Equality using (_≡_; refl)
open import Agda.Builtin.Sigma using (_,_)
open import Agda.Builtin.Word
_ : primQNameToWord64s (quote _≡_)
  ≡ (primWord64FromNat 12 , primWord64FromNat 1335258922519917603)
_ = refl
```

**Comment by pnlph** [comment]
Thanks!

But why is not the result of the `C-c C-n` something like `Agda.Builtin.Word.primWord64FromNat 12 , Agda.Builtin.Word.primWord64FromNat 1335258922519917603`?

**Comment by pnlph** [comment]
I think I know now, the result of `C-c C-l primWord64FromNat 12 RET` is `12`.

But how can `12` be the same value of the normal form for both the natural and the word?

**Comment by gallais** [comment]
Well... Technically you could use [`FromNat`](http://agda.github.io/agda-stdlib/Agda.Builtin.FromNat.html) to make it work? :angel: 

Should we print overloaded literals using the associated `primXXX` function?

**Comment by guillaumebrunerie** [comment]
Indeed, there seems to be an inconsistency in the way words are printed and parsed.
Another alternative would be to use `FromNat` in the `Agda.Builtin` modules, so that `12` can be parsed both as a natural number and as a word by default, but I’m not sure if that’s a good idea.

**Comment by pnlph** [comment]
Let's take the raw definition of the natural numbers:
```agda
data Nat : Set where
  zero : Nat
  suc  : (n : Nat) → Nat
```
Here, we can evaluate a natural but only in a form that includes `zero` and `suc` to the same representation. In particular, we cannot evaluate any decimal representation eg. `3`. With this definition, `3` has no meaning, it is unknown to Agda.

If we want that Agda knows `3`, we need to add this:
```agda
{-# BUILTIN NATURAL Nat #-}
```
Then, any decimal (or hexadecimal adding a prefix `0x`) representation can be evaluated. But every representation stays in its "space". Evaluating `suc (suc (suc (suc (suc zero))))` returns a natural number in the `zero-suc` representation and evaluating a decimal or hexadecimal input results in a decimal representation. This seems to be the current behaviour of the `BUILTIN` pragma, which the user cannot tweak.

Maybe it would be good to let the user more freedom in the representation choice, so one can decide which representations to use and how they should be evaluated. For example it could be allowed:
- `zero-suc` evaluates to `zero-suc` and  `hex` evaluates to `hex`, no `dec`
- `dec` and `hex` evaluate to `hex`, no `zero-suc`
- `zero-suc` and `dec` evaluate to `zero-suc`, no `hex`
- `zero-suc`, `dec` and `hex` evaluate to `hex`
- ...

That is, allowing more expressivity for the `BUILTIN` pragma. I don't know if this could be a solution for machine words also.

**Comment by gallais** [comment]
> Evaluating `suc (suc (suc (suc (suc zero))))` returns a natural number in the `zero`-`suc` representation 

I get `5`.

Test file:

```agda
open import Agda.Builtin.Nat

five : Nat
five = suc (suc (suc (suc (suc zero))))
```

`C-c C-n five RET`

**Comment by andreasabel** [comment]
> Evaluating `suc (suc (suc (suc (suc zero))))` returns a natural number in the `zero-suc` representation and evaluating a decimal or hexadecimal input results in a decimal representation.

Internally, there are two representations: via constructors (`zero-suc`) and literal (represented as `Integer` and printed decimally).  Literals are expanded to constructors e.g. for pattern matching, but constructors are not systematically folded (back) to literals.  This gives the behavior you observe.  Hexadecimal representation is only parsed, never printed.

To print a hexadecimal literal back to the user as hexadecimal, we would need to store some kind of `Origin` information with the literals.

**Comment by pnlph** [comment]
> I get `5`.

I tested with this code to get it:
```agda
data Nat : Set where
  zero : Nat
  suc  : (n : Nat) → Nat
open import Agda.Builtin.Word using (primWord64FromNat)
```
Then `suc (suc (suc (suc (suc zero))))` computes to `suc (suc (suc (suc (suc zero))))` and `5` computes to `5`.

**Comment by gallais** [comment]
Because you haven't bound it to a BUILTIN.

`suc (suc (suc (suc (suc zero))))` is a term in your *local* `Nat` but `5` is
a term in `Agda.Builtin.Nat`'s `Nat` that is implicitly in scope because you
have imported `Agda.Builtin.Word`.

**Comment by pnlph** [comment]
Yes, you are right! In that example, this code:
```agda
_ : 5 ≡ suc (suc (suc (suc (suc zero))))
_ = refl
```
does not typecheck because my local type is different from the builtin type:
```
Nat !=< Agda.Builtin.Nat.Nat
```
But I _explicitly_ imported with `using` 😲 
Somehow, even when importing with `using`, my scope is implicitly built in a way I cannot tame.

**Comment by gallais** [comment]
Even if you cannot write these terms down, the types & constructors need to be
in scope because in general the machine may need to "write" such terms when
solving unification problems.

Think of e.g. calling `toList : Vec A n -> List A` on `"a" :: "b" :: []` having
only imported `Data.Vec` and `Data.String`: Agda still needs to be able to write
the implicit argument `2` of type `Nat` that is passed to `toList`.

**Comment by pnlph** [comment]
OK, I see, thank you for the thorough explanation.

But still when trying to compute `Agda.Builtin.Nat.Nat` in the example above, Agda says that it is not in scope. Maybe we could at least change that error to a warning that explains that it is not in scope but, it is implicitly in scope because of an imported item?

I mean, I am still confused about getting an error when `C-c C-c Agda.Builtin.Nat.Nat RET` and at the same time being able to `C-c C-d 5 RET` and getting `Agda.Builtin.Nat.Nat`.

**Comment by andreasabel** [comment]
It used to be that out-of-scope identifiers like `Agda.Builtin.Nat.Nat` were printed with a `.` prefix: `.Agda.Builtin.Nat.Nat`.  Some people didn't like this.  I changed this prefix to `;` to avoid clashing with dot patterns and irrelevance.  Some didn't like this either.  Agreeably, it looked very ugly.

Not marking not-in-scope identifiers seems also confusing (ping @jespercockx).

**Comment by jespercockx** [comment]
I'm not really sure what's confusing here; you get a clear error that says the thing is not in scope, so you know what module you have to import to bring it into scope.

The only thing that could make things perhaps more intuitive would be to implicitly import all recursive dependencies under their fully qualified name. However, I' not sure if we actually want module names to be in scope without there being an explicit `import` for them. Also, even this would not be a perfect answer because of `private` names that the user cannot refer to but can still appear in the output of Agda.

**Comment by pnlph** [comment]
At the end, and if I understood well, what is confusing for me is the fact that there seems to be a "user scope" and an "Agda scope".

Agda uses the "Agda scope" to compute things, and the user is _implicitly_ building it by importing things, but only being able to act explicitly on the "user scope". The result of some computation may be out of the "user scope". Therefore the result of a computation could be known to Agda, but _unknown_ to the user. I think this is what could generate a cognitive confusion, at least in some users or even in experienced users when dealing with unfamiliar libraries or complex code.

I think the `private` declarations are not cognitively a problem because the user explicitly declared them and therefore committed to the responsibility of knowing them.

I agree, implicitly import all recursive dependencies under their fully qualified name is probably not the solution.

A possible solution could be that the users have the option of acting explicitly on both scopes.

**Comment by andreasabel** [comment]
Seems like the discussion has ended.
