### ISSUE TITLE
Faulty reconstruction of ellipsis in debug printing

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#4724]
@jespercockx 
```agda
{-# OPTIONS -v tc.with:20 #-}

data Nat : Set where
  suc : Nat → Nat

postulate f g : Nat → Nat

_test : Nat → Nat
suc n test with f n
... | n1 with g n1
... | n2 = n2
```
With 2.6.0 (before the fix of #2589) this printed:
```
...
buildWithClause returns Issue4704a.with-14 n n1 | n2 = n2
buildWithClause returns Issue4704a.with-14 n n1 with g n1
                        Issue4704a.with-14 n n1 | n2 = n2
...
buildWithClause returns Issue4704a.with-22 n1 n2 n = n2
```
With 2.6.1 this prints:
```
buildWithClause returns ... = n2
buildWithClause returns ... with g n1
                        ... = n2
buildWithClause returns ... = n2
```
Too much of the lhs (the whole lhs) is gobbled up in the ellipsis.

It is very hard now to see what is going on.

I wonder how safe the ellipsis reconstruction is; does it check the conditions under which it applies correctly?

**Comment by jespercockx** [comment]
The ellipsis reconstruction works by remembering how many of the vertical bars `|` were introduced by the expansion of the `...`. I'm not sure why the number seems to be wrong here. Maybe there is a problem in the `isWithP` function that is used to detect the vertical bars?

**Comment by andreasabel** [comment]
The code for `reintroduceEllipsis` seems to preserve only `WithP`s.
https://github.com/agda/agda/blob/68a270bbab084d971db550f3065bfd9c6111da68/src/full/Agda/Syntax/Concrete/Pattern.hs#L351-L364
But in the with-function `Issue4704a.with-22 n1 n2 n = n2` these are no longer `WithP`s.  Thus, `reintroduceEllipsis` gobbles all.  A machine spinning out of control (a popular movie theme).
> I wonder how safe the ellipsis reconstruction is; does it check the conditions under which it applies correctly?

**Comment by andreasabel** [comment]
Thanks!
