### ISSUE TITLE
Erased modules

### ISSUE THREAD

**Issue by nad** [agda/agda#4743]
I think we should support erased modules, because I would like to be able to use erased identifiers in module applications:
```agda
module @0 Erased = Other-module erased-identifier
```

**Comment by andreasabel** [comment]
With the semantics being that all definitions in the `Erased`module should be tagged as erased?

**Comment by nad** [comment]
Yes.

**Comment by jespercockx** [comment]
How about modules with other modalities (e.g. irrelevant or flat)?

**Comment by nad** [comment]
Does it always make sense to first type check all the definitions without the modality and then add the modality, without any extra checks?

**Comment by UlfNorell** [comment]
That sounds dangerous, why wouldn't you push the modality from the module header inside?

**Comment by nad** [comment]
Was that a response to me?

**Comment by nad** [comment]
> Yes.

We currently do not support erased data or record types, so that should also be supported. Have I forgotten something?

**Comment by UlfNorell** [comment]
> Does it always make sense to first type check all the definitions without the modality and then add the modality, without any extra checks?

> That sounds dangerous, why wouldn't you push the modality from the module header inside?

> Was that a response to me?

Yes

**Comment by nad** [comment]
When we type-check a module application we do not re-check the definitions of the original module from scratch, right?

**Comment by UlfNorell** [comment]
Oh right, my bad. I was thinking we were checking a module definition for some reason.

**Comment by nad** [comment]
For module definitions it makes sense to push the modality into the module.

**Comment by jespercockx** [comment]
When developing a backend for Agda (e.g. Agda2Hs) it would be very useful to be able to mark various top-level definitions as being erased: modules but also individual datatypes and record types. Likewise, it would be good to be able to add an erasure annotation to a module import, so as to avoid having that import in the code generated by the backend.

**Comment by nad** [comment]
Currently Agda always treats (for instance) a pattern-matching lambda as non-erased, unless the lambda itself is explicitly marked as erased. One might think that a pattern-matching lambda that is defined in an erased context should be treated as erased, but in that case the following code, which does not mention `@0`, is rejected:
```agda
open import Agda.Builtin.Equality

data Unit : Set where
  unit : Unit

mutual

  f : Unit → Unit
  f = _

  f≡ : f ≡ λ { unit → unit }
  f≡ = refl
```
If the pattern-matching lambda is erased, then the meta-variable in the body of `f` cannot be unified with the lambda.

Agda currently treats (at least) the following constructions in this way:
* Pattern-matching lambdas.
* Absurd lambdas.
* The generated "sharp" functions.
* Section applications.
* Some reflection primitives.

I think it would be counter-intuitive if an erased module could contain non-erased things. I wonder if we should change things so that everything in an erased definition becomes erased, but keep the present behaviour for type signatures of non-erased definitions. Then the code above is still accepted, but the following two variants are rejected:
```agda
mutual

  f : Unit → Unit
  f = _

  @0 f≡ : f ≡ λ { unit → unit }
  f≡ = refl
```
```agda
mutual

  f : Unit → Unit
  f = _

  @0 g : Unit → Unit
  g = λ { unit → unit }

  f≡ : f ≡ g
  f≡ = refl
```
What do you think?

**Comment by jespercockx** [comment]
I think it makes sense to treat all auxiliary functions that are generated while typechecking an erased definition should also be treated as erased, yes.

**Comment by nad** [comment]
> Likewise, it would be good to be able to add an erasure annotation to a module import, so as to avoid having that import in the code generated by the backend.

You can import Cubical Agda code from Erased Cubical Agda code. The Cubical Agda code is erased, and not compiled. This might work, but consider the following code:
```agda
{-# OPTIONS --cubical-compatible #-}

module Cubical-compatible where

open import Agda.Builtin.Bool public

elim : (P : Bool → Set) → P true → P false → (b : Bool) → P b
elim _ t f true  = t
elim _ t f false = f
```
```agda
{-# OPTIONS --cubical #-}

module Cubical where

import Cubical-compatible

Bool : Set
Bool = Cubical-compatible.Bool

true : Bool
true = Cubical-compatible.true

false : Bool
false = Cubical-compatible.false

elim : (P : Bool → Set) → P true → P false → (b : Bool) → P b
elim = Cubical-compatible.elim
```
```agda
{-# OPTIONS --erased-cubical #-}

module Erased-cubical where

open import Agda.Builtin.Cubical.Path
import Cubical

refl : ∀ {a} {A : Set a} {x : A} → x ≡ x
refl {x = x} = λ _ → x

mutual

  Bool : Set
  Bool = _

  _ : Bool ≡ Cubical.Bool
  _ = refl

mutual

  true : Bool
  true = _

  _ : true ≡ Cubical.true
  _ = refl

mutual

  false : Bool
  false = _

  _ : false ≡ Cubical.false
  _ = refl

mutual

  elim : (P : Bool → Set) → P true → P false → (b : Bool) → P b
  elim = _

  _ : elim ≡ Cubical.elim
  _ = refl

not : Bool → Bool
not = elim (λ _ → Bool) false true

true′ : Bool
true′ = not false
```
The following Haskell code is generated when `Erased-cubical` is compiled:
```haskell
{-# LANGUAGE BangPatterns #-}
{-# LANGUAGE EmptyCase #-}
{-# LANGUAGE EmptyDataDecls #-}
{-# LANGUAGE ExistentialQuantification #-}
{-# LANGUAGE NoMonomorphismRestriction #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE ScopedTypeVariables #-}

{-# OPTIONS_GHC -Wno-overlapping-patterns #-}

module MAlonzo.Code.ErasedZ45Zcubical where

import MAlonzo.RTE (coe, erased, AgdaAny, addInt, subInt, mulInt,
                    quotInt, remInt, geqInt, ltInt, eqInt, add64, sub64, mul64, quot64,
                    rem64, lt64, eq64, word64FromNat, word64ToNat)
import qualified MAlonzo.RTE
import qualified Data.Text
import qualified MAlonzo.Code.Agda.Builtin.Bool
import qualified MAlonzo.Code.CubicalZ45Zcompatible

-- Erased-cubical.Bool
d_Bool_2 :: ()
d_Bool_2 = erased
-- Erased-cubical.true
d_true_6 :: Bool
d_true_6 = coe MAlonzo.Code.Agda.Builtin.Bool.C_true_10
-- Erased-cubical.false
d_false_10 :: Bool
d_false_10 = coe MAlonzo.Code.Agda.Builtin.Bool.C_false_8
-- Erased-cubical.elim
d_elim_18 :: (Bool -> ()) -> AgdaAny -> AgdaAny -> Bool -> AgdaAny
d_elim_18 v0 v1 v2 v3
  = coe MAlonzo.Code.CubicalZ45Zcompatible.du_elim_6 v1 v2 v3
-- Erased-cubical.not
d_not_22 :: Bool -> Bool
d_not_22 = coe d_elim_18 erased d_false_10 d_true_6
-- Erased-cubical.true′
d_true'8242'_26 :: Bool
d_true'8242'_26 = coe d_not_22 d_false_10
```
Note that the module `MAlonzo.Code.CubicalZ45Zcompatible` is imported, even though `Erased-cubical` only depends on `Cubical-compatible` via the Cubical Agda module `Cubical`.

If we add erased import statements, then I think their semantics should imply that everything that can be reached only via an erased import statement is erased.

**Comment by nad** [comment]
I have implemented support for erased data and record types and modules.

Please open a new issue for erased import statements.

**Comment by nad** [comment]
My implementation rejects `open public` in erased modules. If `open public` were allowed, then I think that all definitions that are re-exported should be erased. However, `open public` is handled by the scope-checker, right? Modalities are handled by the type-checker, and I didn't want to bring modalities into the scope-checker.
