### ISSUE TITLE
Unification failure in 2.6.1 and the master branch

### ISSUE THREAD

**Issue by uncle-betty** [agda/agda#4750]
The following code results in a unification failure for `lemma`, which doesn't seem right to me. Strangely (at least to me), the issue goes away when I move the line marked `(AAA)` to the spot marked `(BBB)`. Note that the data type `Three` isn't even used anywhere. Also, the very similar `lemma′` does not have this issue.

I'm now wondering whether it's me or Agda who's being unreasonable.

The code:

```agda
module Repro where

open import Data.Nat
open import Relation.Binary.PropositionalEquality

data Three : Set -- (AAA) To fix things, move this line...

data One : Set where
  one : ℕ → One

data Two : Set where
  two : One → Two 

lemma′ : ∀ (m n : ℕ) → (one m) ≡ (one n) → m ≡ n
lemma′ m .m refl = refl

lemma : ∀ (m n : ℕ) → (two (one m)) ≡ (two (one n)) → m ≡ n
lemma m .m refl = refl

-- (BBB) ... to here.

data Three where
  three : Three
```

The failure:

```
Checking Repro (/home/tlo/agda-test/Repro.agda).
/home/tlo/agda-test/Repro.agda:18,12-16
I'm not sure if there should be a case for the constructor refl,
because I get stuck when trying to solve the following unification
problems (inferred index ≟ expected index):
  two (one m) ≟ two (one n)
when checking that the pattern refl has type
two (one m) ≡ two (one n)
```

Also: Thank you for maintaining Agda.

**Comment by jespercockx** [comment]
Thank you for reporting. This is definitely Agda being unreasonable and not you. It seems there is a missing reduction at https://github.com/agda/agda/blob/3fc80c1dea53d1806ae3555cd279444a72dec297/src/full/Agda/TypeChecking/Rules/LHS/Unify.hs#L664.

**Comment by UlfNorell** [comment]
Note: The difference between `AAA` and `BBB` is that in the former case `One`, `Two`, and the lemmas are in a mutual block.

**Comment by uncle-betty** [comment]
Oh, wow, this was fast! Thank you very much.

I'm happy to report that the fix on master also fixes my original instance of the issue in addition to the above test case. Awesome!
