### ISSUE TITLE
Conversion checker should not insert implicit arguments

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#4751]
In #4684, I wrote:

> I believe the fact that Agda currently relies on the conversion checker to insert hidden arguments is a bad design. Inserting implicit arguments is part of the elaboration process from the surface language into the core language, while conversion checking should act only on fully elaborated core syntax (except for the possible presence of unsolved metas). I wonder if fixing this design flaw would also fix this issue.

This turned out to be unrelated to the actual issue there, but I still believe it would be a good idea to get rid of the insertion of implicits during conversion checking. I tested out removing this step from the conversion checker on `make succeed` and `make fail`, and the only test case that failed was the one for #2412, which deals with the (anyway broken) check for "possibly empty size type" and can be fixed easily by eta-expanding one implicit function. So it seems like it would be a good idea to try to remove this step from Agda.

**Comment by nad** [comment]
Can you explain the difference between the current approach and what you suggest?

**Comment by jespercockx** [comment]
I think I just misunderstood what the code is actually doing, the usages of insertImplicit in the coverage checker are actually quite innocent.
