### ISSUE TITLE
Travis error on GHC 8.0.2: Unable to locate package cabal-install-1.24

### ISSUE THREAD

**Issue by asr** [agda/agda#4770]
We are getting the error `Unable to locate package cabal-install-1.24` in Travis when using GHC 8.0.2. In 93c7db4a03f670a3e245ab87fa168b9b41998821 we moved from Ubuntu 16.04 (Xenial) to Ubuntu 18.04 (Bionic). The error is due to `cabal-install-1.24` is not available for 18.04.

**Comment by asr** [comment]
I filed https://github.com/haskell-CI/haskell-ci/issues/399.

**Comment by andreasabel** [comment]
See #4753 (issue discovered at https://github.com/agda/agda/issues/4736#issuecomment-646650618).

**Comment by L-TChen** [comment]
The issue https://github.com/agda/agda/issues/4799 occurs to me, so giving up cabal 1.24 as well as GHC 8.0.2 might be an option.

**Comment by asr** [comment]
It seems we are moving from cabal to stack (and I agree). What about of only remove cabal support for older versions of GHC?

**Comment by jespercockx** [comment]
FYI, Ubuntu Bionic Beaver (18.04, the previous LTS release) comes with ghc 8.0.2-11 and cabal-install 1.24.0.2-2. Ubuntu Focal Fossa (20.04, the latest LTS release) comes with ghc 8.8.1 and cabal-install 2.4.0.0-2. So for both ghc 8.0.2 and cabal 1.24 the question is essentially the same: do we still want to support the 2018 LTS release of Ubuntu or do we expect people to have upgraded to the 2020 release already?

**Comment by gallais** [comment]
> do we expect people to have upgraded to the 2020 release already?

May be worth asking on the mailing list?

**Comment by andreasabel** [comment]
> It seems we are moving from cabal to stack (and I agree). What about of only remove cabal support for older versions of GHC?

We could stop supporting older cabal versions while keeping cabal support for older GHCs in general.  E.g. we could support GHC 8.0 with cabal 2.0 rather than giving up on GHC 8.0 altogether already. (See https://github.com/haskell-CI/haskell-ci/issues/399#issuecomment-683980085.)

**Comment by asr** [comment]
> We could stop supporting older cabal versions while keeping cabal support for older GHCs in general. E.g. we could support GHC 8.0 with cabal 2.0 rather than giving up on GHC 8.0 altogether already.

Each version of GHC is shipped with a version of Cabal (the library) which is used by `cabal-install`. I guess that requiring a different version of `cabal-install` will be a mess for the user. For this reason, I suggested only support `stack` for GHC 8.0.2.

**Comment by asr** [comment]
Since GHC 8.0.2 won't be added to https://launchpad.net/~hvr/+archive/ubuntu/ghc and we are moving out from Travis, I'm closing this issue.

**Comment by andreasabel** [comment]
Shouldn't 8.0.2 be deleted from `.travis.yml` then?

**Comment by asr** [comment]
Of course! Done in the commit above.
