### ISSUE TITLE
Interaction between tactics and instance search

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#4777]
Instance search does speculative type checking of the available candidates for an instance goal. This can involve running tactics (as happened in #4593). I suspect in most cases you don't want this, but I can imagine there might be exceptions.

Some options:
1. Never run tactics during instance search
2. Provide a function to abort a tactic if invoked during instance search
3. Status quo
4. ??

**Comment by andreasabel** [comment]
You got the 777, @UlfNorell!

The question you raise is a very fundamental one:  How the different methods to solve metas should interact.

I could imagine a hierarchy (from lower to higher):
1. Unification
2. Instance search
3. Tactics

where "higher" methods utilize "lower" ones but not vice versa. 

However, I lack practical experience with 2 and 3, thus my view isn't grounded in practice but rather a high-level view from principles.

**Comment by nad** [comment]
Perhaps we can try option 1 first, and see if anything breaks.

**Comment by JorisCeulemans** [comment]
It would be nice if in the definition of a macro you can get information on whether instance search for some metavariable succeeded or not. I tried working with `noConstraints` in the example below, but that doesn't work.
```Agda
open import Data.Bool using (Bool; true; false; not)
open import Data.List using (List; [])
open import Data.Maybe using (Maybe; nothing; just)
open import Reflection
open import Reflection.Argument using (_⟨∷⟩_)

record Eq {a} (A : Set a) : Set a where
  constructor mkEq
  field
    _==_ : A → A → Bool
open Eq {{...}} public

instance
  bool-eq : Eq Bool
  _==_ {{bool-eq}} false false = true
  _==_ {{bool-eq}} false true = false
  _==_ {{bool-eq}} true false = false
  _==_ {{bool-eq}} true true = true

macro
  equal? : Term → Term → Term → TC _
  equal? t1 t2 hole =
    catchTC
      (noConstraints (unify hole (con (quote just) (def (quote _==_) (t1 ⟨∷⟩ t2 ⟨∷⟩ []) ⟨∷⟩ []))))
      (unify hole (con (quote nothing) []))

true=true? : Maybe Bool
true=true? = equal? true true

not=not? : Maybe Bool
not=not? = {!equal? not not!}
{- I would have liked this to return nothing, but instead I get:
   No instance of type Eq (Bool → Bool) was found in scope.
   when checking that not not are valid arguments to a function of
   type
   {a : Agda.Primitive.Level} {A : Set a} ⦃ r : Eq A ⦄ → A → A → Bool
-}
```
As noted by @UlfNorell on the mailing list, the problem seems to be that "instance search runs after the macro, and there's currently no way to force it to happen during the macro call."

**Comment by jespercockx** [comment]
I agree with Ulf's option number 1, and with the hierarchy proposed by Andreas.

**Comment by UlfNorell** [comment]
I'm revisiting this after getting bitten writing some `deriving`-style tactics. We have the `getInstances` primitive which allows you to run instance search manually, but it's a bit of a pain to have to do the recursive searches manually.

I suggest adding a `solveInstanceConstraints : TC ⊤` primitive that wakes up all the instance constraints and try to solve them.
