### ISSUE TITLE
Make erasure compatible with univalence

### ISSUE THREAD

**Issue by nad** [agda/agda#4784]
I managed to prove `(A ≃ᴱ B) ≃ᴱ Erased (A ≃ B)`, where `A ≃ᴱ B` is a type of equivalences with erased proofs, using an erased univalence axiom. If we could compile Cubical Agda this would mean that we could obtain a function of type `A → B` from nothing at run-time. This should not be possible.

Perhaps this is due to some bug in Agda, like #4727. However, perhaps Agda's current approach to erasure is incompatible with univalence. Note that, because the proof only relies on erased univalence, the idea to implement a compiler for Cubical Agda programs where all cubical parts have been marked as erased (#4701) might have to be rethought. However, I hope that we can fix the problem.

Here is a sketch of the proof (simplified to the case where `A` and `B` have the same type):
```
A ≃ᴱ B          ≃
[ A ] ≡ [ B ]   ≃
Erased (A ≡ B)  ≃
Erased (A ≃ B)  
```
The last step uses erased univalence, and the second step uses an equivalence that I discuss in [Logical properties of a modality for erasure](http://www.cse.chalmers.se/~nad/publications/danielsson-erased.html). The first step uses the following functions, which can be proved to be inverses of each other in an erased context:
```agda
to : A ≃ᴱ B → [ A ] ≡ [ B ]
to A≃B = []-cong [ ≃⇒≡ univ (≃ᴱ→≃ A≃B) ]

from : [ A ] ≡ [ B ] → A ≃ᴱ B
from [A]≡[B] = subst (λ ([ X ]) → A ≃ᴱ X) [A]≡[B] id
```
Here `[]-cong` is the right-to-left direction of the equivalence I mention above, `≃⇒≡ univ` converts an equivalence to an equality, and `≃ᴱ→≃` converts an equivalence with erased proofs to an equivalence (in erased contexts).

In a setting with univalence, and where `_≡_` stands for paths, the `from` function looks problematic to me: at run-time it gets a path between erased things, and returns two functions. Note that `from` relies on the fact that the type arguments of `_≃ᴱ_` are marked as erased. Does this make sense in this setting?

Currently we allow the following definition:
```agda
record Σ (@0 A : Set) (@0 B : A → Set) : Set where
  field
    proj₁ : A
    proj₂ : B proj₁
```
Perhaps this should not be allowed unless the K rule has been turned on. Note that the following code is rejected:
```agda
Π : (@0 A : Set) → @0 (A → Set) → Set
Π A B = ∀ x → B x
```
However, I think it makes more sense to allow the following definition, where `A` is only used in an erased context:
```agda
record Erased (@0 A : Set a) : Set a where
  constructor [_]
  field
    @0 erased : A
```

**Comment by nad** [comment]
Consider the following type:
```agda
record R : Set₁ where
  field
    @0 A : Set
    a    : A
```
The following code is rejected:
```agda
open import Agda.Builtin.Sigma

record Erased {a} (@0 A : Set a) : Set a where
  constructor [_]
  field
    @0 erased : A

open Erased

R : Set₁
R = Σ (Erased Set) λ A → erased A
```
It would have been accepted if the type arguments of `Σ` had been marked as erased.

Not being able to convert record types to nested Σ-types might in some cases be awkward.

**Comment by nad** [comment]
I realised that the following code is still allowed, even if parameters are not always allowed to be erased:
```agda
record Σ (A : Erased Set) (B : Erased (erased A → Set)) : Set where
  field
    proj₁ : erased A
    proj₂ : erased B proj₁
```
The problem with this definition, as I currently see it, is that the implementation of the type function `Σ` uses erased inputs to construct its (not necessarily erased) output.

Perhaps it does not make sense to unconditionally allow erased names to be mentioned in the types of constructors and projections (unless the K rule has been turned on). I wonder if it is fine to mention erased names bound in the type signature itself, or if the following definitions should be disallowed:
```agda
record R : Set₁ where
  field
    @0 N : Set
    z    : N
    s    : N → N
    to-ℕ : N → ℕ

data D : Set₁ where
  c : (@0 N : Set) → N → (N → N) → (N → ℕ) → D
```
I currently do not see a problem with these definitions, but that does not necessarily mean that they are fine.

**Comment by nad** [comment]
> Not being able to convert record types to nested Σ-types might in some cases be awkward.

If definitions like `R` are allowed, then there is a workaround:
```agda
record Σ₀ (@0 A : Set a) (B : A → Set b) : Set (a ⊔ b) where
  field
    @0 proj₁ : A
    proj₂    : B proj₁

R : Set₁
R = Σ₀ Set λ A → A
```
However, I am not keen on duplicating all the theory I have developed for Σ-types for `Σ₀` (with extra lemmas for properties like `(Σ A λ x → Σ₀ B λ y → C x y) ≃ (Σ₀ B λ y → Σ A λ x → C x y)`).

With some kind of modality polymorphism the duplication could presumably be avoided:
```agda
record Σ (m : Either-0-or-ω) (@m A : Set a) (B : A → Set b) : Set (a ⊔ b) where
  field
    @m proj₁ : A
    proj₂    : B proj₁
```
However, I do not (yet?) want to make Agda more complicated by introducing this kind of feature.

Note that we can already define a generalisation of `Σ` and `Σ₀`:
```agda
pattern gone    = true
pattern present = false

Erased? : Bool → Set a → Set a
Erased? gone    A = Erased A
Erased? present A = A

@0 erased? : ∀ e → Erased? e A → A
erased? gone    = erased
erased? present = id

Σ[_] :
  (e : Bool)
  (A : Erased? e (Set a)) →
  (erased? e A → Set b) →
  Set (a ⊔ b)
Σ[ present ] A = Σ A
Σ[ gone ]    A = Σ₀ (erased A)
```

**Comment by Saizan** [comment]
It seems to me that to be compatible with univalence types like `Σ₀` and `D` and `_≃ᴱ_` should be marked as erased, so that they can be part of a path only in an erased context. Otherwise it won't make sense to assume they can be transported with.

On the other hand, --with-K should be compatible with an axiom saying that `Erased Set` is isomorphic to `Set`.

**Comment by nad** [comment]
> It seems to me that to be compatible with univalence types like `Σ₀` and `D` and `_≃ᴱ_` should be marked as erased, so that they can be part of a path only in an erased context. Otherwise it won't make sense to assume they can be transported with.

This makes sense to me, if `_≃ᴱ_` refers to the variant with erased type arguments. Do you think the other variant is fine? This one can be expressed using `Erased` and regular type formers.

I assume that currently field and constructor types are treated in the same way as type signatures. For the purposes of erasure they should perhaps be treated like regular expressions.

> On the other hand, --with-K should be compatible with an axiom saying that `Erased Set` is isomorphic to `Set`.

Well, we erase all types even if they are not marked as erased. I guess that this axiom could be something that computes at compile-time.

**Comment by Saizan** [comment]
> Do you think the other variant is fine? This one can be expressed using `Erased` and regular type formers.

It should be, `Erased` is fine because the field is erased, so an erased type is enough to do the transport.

> I assume that currently field and constructor types are treated in the same way as type signatures. For the purposes of erasure they should perhaps be treated like regular expressions.

Yeah, we need something like that. 

In fact I think the following is problematic too

```agda
Π0 : (A : Set) → (A → Set) → Set
Π0 A B = (@0 x : A) → B x
```

and we should only allow

```agda
@0 Π0 : (A : Set) → (A → Set) → Set
Π0 A B = (@0 x : A) → B x
```

**Comment by nad** [comment]
> In fact I think the following is problematic too
> 
> ```agda
> Π0 : (A : Set) → (A → Set) → Set
> Π0 A B = (@0 x : A) → B x
> ```
> 
> and we should only allow
> 
> ```agda
> @0 Π0 : (A : Set) → (A → Set) → Set
> Π0 A B = (@0 x : A) → B x
> ```

Presumably the following code is also fine:
```agda
Π0 : (A : Set) → (@0 A → Set) → Set
Π0 A B = (@0 x : A) → B x
```
Is it still fine to mention erased things in non-erased contexts in actual type signatures, as in the following example?
```agda
_ : {A : Set} {B : A → Set} → ((@0 x : A) → B x) → (x : A) → B x
_ = λ f x → f x
```

**Comment by Saizan** [comment]
Yes, both of those are fine. The second example works because type signatures are an erased context.

**Comment by nad** [comment]
OK. The problem with Π-types seems to have been introduced with the fix of #3853.

**Comment by Saizan** [comment]
So the plan would be:

- [ ] Allow declaring a whole data/record definition as erased, this puts fields/constructor types in an erased context.
- [ ] field/constructor types should be type-checked at the current erasure level, not necessarily "as types"
- [ ] same goes for codomains of pi types.

**Comment by Saizan** [comment]
I suppose none of the above when we have `--with-K` though.

**Comment by nad** [comment]
> Allow declaring a whole data/record definition as erased, this puts fields/constructor types in an erased context.

Do you have a use case for this?

**Comment by Saizan** [comment]
This definition should not be allowed:
```agda
record Σ₀ (@0 A : Set a) (B : A → Set b) : Set (a ⊔ b) where
  field
    @0 proj₁ : A
    proj₂    : B proj₁
```

but this one could:
```agda
record @0 Σ₀ (@0 A : Set a) (B : A → Set b) : Set (a ⊔ b) where
  field
    @0 proj₁ : A
    proj₂    : B proj₁
```

**Comment by nad** [comment]
What is the point of the latter definition? If it can only be used in erased contexts, then you can just as well use the regular Σ-type, can't you?

**Comment by Saizan** [comment]
Indeed I guess you could encode `Σ₀` like this
```agda
@0 Σ₀ : (@0 A : Set) (B : A -> Set) -> Set
Σ₀ A B = Σ (Erased A) (\ e -> B (erased e))
```

**Comment by Saizan** [comment]
The current plan would outlaw the following when `--without-K`

```agda
data Vec (A : Set) : Nat → Set where
  zero : Vec A zero
  suc : {@0 n : Nat} → A → Vec A n → Vec A (suc n)
```

it might be sound to take into consideration the forcing analysis though.

**Comment by nad** [comment]
> The current plan would outlaw the following when `--without-K`
> 
> ```agda
> data Vec (A : Set) : Nat → Set where
>   zero : Vec A zero
>   suc : {@0 n : Nat} → A → Vec A n → Vec A (suc n)
> ```

Would the following code, with an erased index, be accepted?
```agda
data Vec (A : Set) : @0 Nat → Set where
  []  : Vec A zero
  _∷_ : {@0 n : Nat} → A → Vec A n → Vec A (suc n)
```

**Comment by Saizan** [comment]
Yes, it would be accepted with an erased index.

**Comment by nad** [comment]
In that case I don't think this is much of a problem, because the latter variant of `Vec` is more general than the former one.

**Comment by nad** [comment]
Now the following code is rejected:
```agda
{-# OPTIONS --without-K #-}

record R : Set₁ where
  field
    F : (@0 A : Set) → @0 A → Set
```
I guess this was not intended.

**Comment by nad** [comment]
Perhaps I've found a fix. Consider the following code:

https://github.com/agda/agda/blob/05d0e8752f3ffc80b78981e79264ef415017b064/src/full/Agda/TypeChecking/Irrelevance.hs#L414-L416

The code is accepted if the definition of `domMod` is changed to either of the following expressions:
```haskell
mapQuantity (composeQuantity (getQuantity a)) $
mapCohesion (composeCohesion (getCohesion a)) mod
```
```haskell
getModality a <> mod
```
The `Relevance` of the second expression might be different from that of `mod`. Should the `Relevance` stay unchanged?

**Comment by nad** [comment]
The following code is also rejected (when I use a variant of Agda with support for erased constructors):
```agda
{-# OPTIONS --without-K #-}

postulate
  @0 A : Set

data D : Set where
  @0 c : A → D
```

**Comment by nad** [comment]
I looked into the second problem. The implementation of `fitsIn` contains the following code:

https://github.com/agda/agda/blob/05d0e8752f3ffc80b78981e79264ef415017b064/src/full/Agda/TypeChecking/Rules/Data.hs#L1125

I tried to replace it with the following code:

```haskell
        q <- asksTC getQuantity
        usableAtModality
          (setQuantity (getQuantity dom <> q) defaultModality)
          (unEl $ unDom dom)
```
However, it seems as if the quantity in the context is not `Quantity0 something` when the type signature of an erased constructor is checked. Is this intended?

The `envModality` field is documented in the following way:

https://github.com/agda/agda/blob/05d0e8752f3ffc80b78981e79264ef415017b064/src/full/Agda/TypeChecking/Monad/Base.hs#L2680-L2690

Is the reason for not keeping proper track of whether we are in an erased context that there are plans to add support for linear types in the future?

**Comment by Saizan** [comment]
We should really keep `usableMod` consistent with the typing rules at the appropriate modality.

In particular we have that the following does not typecheck:
```agda
{-# OPTIONS --without-K #-}

T : Set _
T = (@0 A : Set) → @0 A → Set
```

Error:
```
Variable A is declared erased, so it cannot be used here
when checking that the expression A has type _1
```

For the cubical semantics I would expect that the more general typing rule you expect would be fine though.

About locally setting `envModality` to `0` when working with the types of erased constructors I would agree.

**Comment by Saizan** [comment]
The relevant function for checking the domain of a pi type is this one btw

https://github.com/agda/agda/blob/05d0e8752f3ffc80b78981e79264ef415017b064/src/full/Agda/TypeChecking/Rules/Term.hs#L322

**Comment by nad** [comment]
> We should really keep `usableMod` consistent with the typing rules at the appropriate modality.
> 
> In particular we have that the following does not typecheck:
> 
> ```agda
> {-# OPTIONS --without-K #-}
> 
> T : Set _
> T = (@0 A : Set) → @0 A → Set
> ```

Are you saying that this should type-check, or that it shouldn't?

**Comment by nad** [comment]
Note that the following code is accepted:
```agda
{-# OPTIONS --without-K #-}

record Erased (@0 A : Set) : Set where
  constructor [_]
  field
    @0 erased : A

T : Set₁
T = (@0 A : Set) → Erased A → Set
```

**Comment by nad** [comment]
The error for `T` is raised by the following piece of code:

https://github.com/agda/agda/blob/05d0e8752f3ffc80b78981e79264ef415017b064/src/full/Agda/TypeChecking/Rules/Application.hs#L285-L291

If the quantity in the environment had been "0" here, then the code would have been accepted.

**Comment by nad** [comment]
It seems reasonable to me to "always" keep track of whether or not we are in an erased context. However, I guess this would involve lots of changes, because the internal syntax is traversed by lots of different functions. We do have functions like `underAbstraction`, but my impression is that they are not always used.

**Comment by nad** [comment]
I think I managed to fix the problem with `T`:

https://github.com/agda/agda/blob/05d0e8752f3ffc80b78981e79264ef415017b064/src/full/Agda/TypeChecking/Rules/Term.hs#L115-L116

I changed the final line:
```haskell
      a <- setArgInfo info . defaultDom <$>
             applyQuantityToContext info (isType_ t)
```

I also changed the corresponding code for Π:

https://github.com/agda/agda/blob/05d0e8752f3ffc80b78981e79264ef415017b064/src/full/Agda/TypeChecking/Rules/Term.hs#L332-L335

New code:
```haskell
    let (q :| qs) = fmap getQuantity xps
    unless (all (q ==) qs) $ __IMPOSSIBLE__

    t <- applyQuantityToContext q $
         applyCohesionToContext c $
         modEnv lamOrPi $ isType_ e
```

I wonder if the case for non-dependent functions should also do something about the cohesion.

Here is a test case that has both a dependent and a non-dependent function space:
```agda
{-# OPTIONS --without-K #-}

T : Set₁
T = (@0 A : Set) → @0 A → (@0 x : A) → Set
```

**Comment by nad** [comment]
I managed to also get the following code to type-check:
```agda
{-# OPTIONS --without-K #-}

data D : Set₁ where
  @0 c : (@0 A : Set) → A → (x : A) → D
```
I added `applyQuantityToContext ai $` before `do` in the following code:

https://github.com/agda/agda/blob/05d0e8752f3ffc80b78981e79264ef415017b064/src/full/Agda/TypeChecking/Rules/Data.hs#L199-L200

I wonder how many other problems exist in the code, especially problems that make too many programs type-correct…

**Comment by nad** [comment]
@Saizan, I do not plan to make any changes related to other modalities, which I know little about.

**Comment by Saizan** [comment]
Oh, wow, we should definitely refactor the code so that `A.Fun` and `A.Pi` are kept in sync.

**Comment by Saizan** [comment]
@nad 
 > I added `applyQuantityToContext ai $` before `do` in the following code:
> 
> https://github.com/agda/agda/blob/05d0e8752f3ffc80b78981e79264ef415017b064/src/full/Agda/TypeChecking/Rules/Data.hs#L199-L200
> 

This breaks the `params <- getContextTelescope` call below. I would only put `applyQuantityToContext ai $` around the `fitsIn` call below.

**Comment by nad** [comment]
Sometimes I use a record type to pack up some arguments of a function. Now this works less often than before. Here is a contrived example:
```agda
{-# OPTIONS --without-K #-}

works : ((@0 A : Set) → A → A) → (@0 A : Set) → A → A
works g A x = g A x

record Fails : Set₁ where
  field
    f : (@0 A : Set) → A → A

fails : Fails → (@0 A : Set) → A → A
fails r A x = r .Fails.f A x
```

**Comment by Saizan** [comment]
@nad things like your `Fails` example is why I brought up erased type declarations in this comment https://github.com/agda/agda/issues/4784#issuecomment-707676985

**Comment by nad** [comment]
If `Fails` were erased, then presumably its field would also be erased, and then you couldn't define `fails`.

**Comment by Saizan** [comment]
No, the fields wouldn't need to be erased: given that you wouldn't be able to use use `Fails` in a non-erased `transport`, the types of fields can be checked in an erased context.

**Comment by nad** [comment]
I meant that (unless I misunderstood you) it would not be possible to use `.Fails.f` in the body of `fails`.

**Comment by Saizan** [comment]
Yes, it was clear that was what you meant, which is why I said the fields would not need to be erased, which implies you could use `.Fails.f` in the body of `fails`.

In fact, similarly to what I show in https://github.com/agda/agda/issues/4784#issuecomment-707690441, you can emulate what you need already with erased type definitions:

```agda
record Id {l} (A : Set l) : Set l where
  field
    f : A

@0 Works : Set₁
Works = Id ((@0 A : Set) → A → A)

works : Works → (@0 A : Set) → A → A
works r A x = r .Id.f A x
```

For more arguments you could use nested `Σ` rather than `Id`, or some other variation on that.

**Comment by nad** [comment]
> This breaks the `params <- getContextTelescope` call below. I would only put `applyQuantityToContext ai $` around the `fitsIn` call below.

Doesn't it make sense to do this for the call to `checkConstructorType` as well?

I noticed that there is also some code that generates projections:

https://github.com/agda/agda/blob/88222ed563e399dafffcd552b38c1adaaa3888ae/src/full/Agda/TypeChecking/Rules/Data.hs#L242-L243

I don't know what these projections are used for, the documentation doesn't really say anything:

https://github.com/agda/agda/blob/88222ed563e399dafffcd552b38c1adaaa3888ae/src/full/Agda/TypeChecking/Monad/Base.hs#L2023

If the constructor is erased, should these projections be marked as erased?

**Comment by nad** [comment]
@Saizan?

**Comment by Saizan** [comment]
Sounds correct.  Although it shouldn't really affect `checkConstructorType` because of the `workOnTypes` use in there.

**Comment by nad** [comment]
Should the projections be marked as erased?

**Comment by Saizan** [comment]
Sounds correct.

**Comment by nad** [comment]
@Saizan, your commit 7cbb67e97067b2420a63c2a22d8029add0e57813 broke the test case for #2918. You wrote that inlining of recursive pattern-matching lambdas "caused the compiler to loop". Do you recall under what circumstances this happened? Could we allow inlining in more cases?

**Comment by nad** [comment]
I am not aware of any more problems right now. If we find one, then this issue can be reopened.

Perhaps it makes sense to add erased type declarations. If we decide to do this, then we can open a new issue for it.

**Comment by nad** [comment]
I edited the user manual. @Saizan, can you check if things look OK?

**Comment by Saizan** [comment]
Yeah, I think it looks ok.

**Comment by nad** [comment]
> It seems to me that to be compatible with univalence types like `Σ₀` and `D` and `_≃ᴱ_` should be marked as erased, so that they can be part of a path only in an erased context. Otherwise it won't make sense to assume they can be transported with.

@Saizan, can you construct a concrete counterexample that shows that (for instance) the following type without any parameters is incompatible with univalence?
```agda
record R : Set₁ where
  field
    @0 A : Set
    x    : A
```
