### ISSUE TITLE
Feature request: a  keyword for synonyms

### ISSUE THREAD

**Issue by jonaprieto** [agda/agda#4801]
Hi, 

Is there any keyword that I'm not aware of to keep a list of synonyms for naming a term?
Naming things is difficult and keeping a standard  for naming is hard. 

To be specific, the scenario is something like the following:

```agda
  isEquiv : ...
  isEquiv = ...

  synonym isEquiv
    is-equiv
    _is-equivalence
    is-vv-equiv
    isContrMap
    is-contr-map
    ... 
````

We can do the following for every single synonym, which I want to avoid.

```agda
  isEquiv is-equiv : ...
  isEquiv = ...
  is-equiv = isEquiv
```

I can imagine the type-checker could maintain a kind of map of these names with the value, the proper term and its type,
while type checking. Or even much simpler, it could translate names to the actual name just before type-check.

**Comment by andreasabel** [comment]
For simple aliases, you do not need a type declaration.
```agda
is-equiv = isEquiv
_is-equivalence = isEquiv
...
```
But in general, I think deciding on a naming discipline and following it will improve readability of your code (rather than having many different names for the same thing).

**Comment by jonaprieto** [comment]
I agree to some extent, of course. But this feature is more about improving the usability.

**Comment by rwe** [comment]
As an outsider opinion: this seems like it would be a slightly harmful misfeature with unclear, if any, benefit.

Certainly the underlying motivation:
> Naming things is difficult and keeping a standard for naming is hard

will not be helped by attempting to use all conventions at once.

Supporting that style would encourage wasted time of module writers: the _example_ even gives up on the combinatorial exercise with an ellipsis. Subsequently it would waste the time of module consumers: it's already hard enough to learn the names of things, and the _encouraged_ proliferation of aliases just makes things worse.

This isn't unique guidance to programming: imagine being told a story about a group of people, but the storyteller keeps using different nicknames for them, or different pronunciations, and you can't tell who's doing what anymore. That gets super confusing and annoying fast. You'd rather they just stick to a name under a given context.

**Comment by andreasabel** [comment]
I agree with @rwe : My recommendation would be to set in stone a naming convention, and follow it with utter discipline.
