### ISSUE TITLE
Installer script for nightly build doesn't work: size-solver binary only exists for Windows

### ISSUE THREAD

**Issue by alan-j-hu** [agda/agda#4803]
Hello. I want to install Agda without building it from source with Cabal. I found this PR: https://github.com/agda/agda/pull/4243 I downloaded the Linux build artifact from https://github.com/agda/agda/actions/runs/177978016 and attempted to run the included installation script (https://github.com/agda/agda/blob/master/.github/install_agda_user.sh). However, I encountered an error because the `size-solver` binary, which the installation script attempts to give executable permissions, wasn't in the bin directory.

According to the GitHub workflow file: https://github.com/agda/agda/blob/master/.github/workflows/nightly.yml, the `size-solver` binary is only uploaded for Windows.

Thank you all for your time. I would love to have an accessible way to download an up-to-date Agda binary.

**Comment by rwe** [comment]
That looks easy enough to fix. I'll take a quick stab. @dosaylazy thank you for the very clear bug report + investigation!

**Comment by rwe** [comment]
@dosaylazy — This is now fixed and the latest nightly artifacts (https://github.com/agda/agda/actions/runs/180713073) now include `size-solver`

**Comment by asr** [comment]
Well, if the binary is for the final users it shouldn't include the `size-solver` program.

**Comment by rwe** [comment]
@asr I marginally suspected that, but wasn't sure. It was included in the install script (per this issue) which was breaking because it was missing, and it was included in the Windows distribution. Perhaps another issue to remove it entirely?

**Comment by asr** [comment]
> Perhaps another issue to remove it entirely?

Yes, please. There are some things we should improve if we want to distribute a binary for Agda.

**Comment by rwe** [comment]
@asr Ok, I've created an issue to track that.
