### ISSUE TITLE
avoiding listing all cases

### ISSUE THREAD

**Issue by lclem** [agda/agda#4804]
Consider the following piece of code, an abstracted version of a programming pattern I recently came across:

```agda
data Data : Set where
  Case1 : Data
  Case2 : Data
  ManyMoreCases : Data

f : Data → Data
f _ = Case1

f-lemma : ∀ (d : Data) → f d ≡ Case1 ∨ f d ≡ Case2
f-lemma _ = left refl

g : Data → Data
g Case1 = Case1
g _ = Case2

g-lemma : ∀ (d : Data) → g d ≡ Case1 ∨ g d ≡ Case2
g-lemma Case1 = left refl
g-lemma _ = right refl
```

While the definition of `f-lemma` is fine, the last line about `g-lemma` gives the following error:

```
(g d) != Case2 of type Data when checking that the expression refl has type g d ≡ Case2
```

I understand this can be fixed by adding ```Case2``` and ```ManyMoreCases``` to the definition of ```g-lemma```, however it seems to me that the compiler should be able to figure it out as it did with `f-lemma`. In the original problem I'm working on, ```ManyMoreCases``` stands for really a lot of cases and expanding it would not be practical.

Is there some established programming pattern to deal with problems like this one?

**Comment by andreasabel** [comment]
This is a frequent complaint.  Agda does not split a catch-all pattern `_` into the possible constructor patterns when type checking the catch-all clause like `g-lemma _ = right refl`.  The standard answer is to use /views/.

In your case, a solution could be the predicate `G` that classifies the output of `g'`.
```agda
data G : Data → Set where
  case1 : G Case1
  case2 : G Case2

g' : Data → Σ Data λ d → G d
g' Case1         = _ , case1
g' Case2         = _ , case2
g' ManyMoreCases = _ , case2

g'-lemma : ∀ (d : Data) → fst (g' d) ≡ Case1 ∨ fst (g' d) ≡ Case2
g'-lemma d with g' d
... | _ , case1 = left refl
... | _ , case2 = right refl
```

**Comment by lclem** [comment]
Many thanks for the quick reply!
For a moment I thought that we are just replicating the same issue in the definition of `g'`,
but in fact it can be compressed as follows: 

```agda
g' : Data → Σ Data λ d → G d
g' Case1 = _ , case1
g' _     = _ , case2
```
In this way we avoid the lengthy enumeration of all cases other than Case1.

**Comment by gallais** [comment]
I would call `g'` a view only if it had this type:

```agda
g' : (d : Data) → G d
```
