### ISSUE TITLE
Let "open import" pass parameters to parametrized modules

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#481]
We currently have to write
```agda
import X; open X parameter
```
instead of the more obvious
```agda
open import X parameter
```

Is there a reason for this or is it just syntactically inconvenient?

Original issue reported on code.google.com by `pumpkingod@gmail.com` on 1 Oct 2011 at 2:26

**Comment by andreasabel** [comment]
Some relevant commits (dating 2012 Oct 17-20) in reverse chronological order:
49d21f62ad7806271a6f0225d1d5dfc5ba0a9b6f
```
    Added syntax 'import Path.Mod args as M'.
```
e5409549062e496f38fa21f8dff52f19e6d130ec
```
    Fixed highlighting of 'as' in open import M args as M'.
    Only works in non-interactive highlighting.  Still broken in interactive h.
```
2d3e61a926b172ebf7013b348c91f53b319422a3
```
    Allowed syntax 'open import Path.Module args as M'.
    This is expanded to
    
      import Path.Module as .#Fresh-123
      private open module M' = .#Fresh-123 args
```
34d9b524b75e7953131f6434ca568f14d02f79e1
```
    Updated release notes for 'open import M args'.
```
2f4f19bc492a4461b11ef0d3e984639c8c939dd2
```
    Modified semantics of 'open import M args' such that M does not get added to the scope.
```
240a09d524a3d90f95680d200ad2ab5c4ea93858
```
    Parse 'open import Module args using/hiding/renaming'.
    I could not make 'open import Module args as M' work, so it is disallowed.
```
b7694129a70bd325800aea3fc506f4278218b6ea
```
    Rolled back rollback of open import M args.
```
38301e500994383c3d59261fcb5eee19ab7a451b
```
    Test case exhibiting potential ambiguity of open module M as as (Issue 481).
```
