### ISSUE TITLE
Remove `size-solver` from nightly assets and user/system install scripts

### ISSUE THREAD

**Issue by rwe** [agda/agda#4812]
Previously, the `size-solver` binary asset was uploaded only for Windows, but the scripts such as https://github.com/agda/agda/blob/dc099484ce3af04922b3b8540411d8caebad5105/.github/install_agda_system.sh expected it to exist for all build variations. This was reported in #4803.

#4806 added the `size-solver` to the nightly assets to fix those scripts.

However as noted by @asr here: https://github.com/agda/agda/issues/4803#issuecomment-663731842
> Well, if the binary is for the final users it shouldn't include the `size-solver` program.

So it appears the binary should be removed from the asset uploads and fixed by removing it also from the scripts.

**Comment by L-TChen** [comment]
Huh, why was `size-solver` included in the very beginning anyway? @ice1000

**Comment by ice1000** [comment]
I thought it was a part of the Agda project, so I just included it.

**Comment by ice1000** [comment]
Sorry about that.

**Comment by rwe** [comment]
No need to apologize! It's not really clear (to me) exactly what size-solver is or why it's in the build at all.

**Comment by asr** [comment]
The `size-solver` program is only used for the test suite. See `test-size-solver` in the `Makefile`.

**Comment by rwe** [comment]
Ah, thanks. To clarify my understanding, looking closer it seems `size-solver` is basically a (standalone) test-suite runner for `Agda.TypeChecking.SizedTypes.WarshallSolver` (and friends). I wonder if that should be moved into `test/` somehow. I like the idea of standalone test utilities like that, though it is a bit confusing that it's the only one.

**Comment by andreasabel** [comment]
I think the fix for the present issue (#4812) was labeled to fix #4814 and closed it by accident.

**Comment by rwe** [comment]
@andreasabel — You're right. I must have fat-fingered the issue number. Thanks for tracking that down!
