### ISSUE TITLE
Current master fails compilation: binding for 'error' shadows the existing binding

### ISSUE THREAD

**Issue by mouse07410** [agda/agda#4815]
Weird. Of two platforms, one exhibits this behavior consistently, the other one doesn't. Still, it would be nice to get help determining which one of the installed packages seems to interfere here:
```
cabal: Entering directory '.'
Configuring Agda-2.6.2...
Preprocessing executable 'agda-mode' for Agda-2.6.2..
Building executable 'agda-mode' for Agda-2.6.2..
Preprocessing library for Agda-2.6.2..
Building library for Agda-2.6.2..
[  1 of 371] Compiling Agda.Interaction.ExitCode ( src/full/Agda/Interaction/ExitCode.hs, dist-2.6.2/build/Agda/Interaction/ExitCode.o, dist-2.6.2/build/Agda/Interaction/ExitCode.dyn_o )

src/full/Agda/Interaction/ExitCode.hs:30:34: error: [-Wname-shadowing, -Werror=name-shadowing]
    This binding for ‘error’ shadows the existing binding
      imported from ‘Prelude’ at src/full/Agda/Interaction/ExitCode.hs:2:8-32
      (and originally defined in ‘GHC.Err’)
   |
30 |                                | error  <- [minBound..maxBound]
   |                                  ^^^^^
cabal: Leaving directory '.'
``` 

MacOS Catalina 10.15.6, Xcode-11.6, Cabal-3.2.0.0, GHC-8.10.1, Agda current master, build with provided `Makefile`.

**Comment by rwe** [comment]
Do you have `-Wname-shadowing` somewhere in your `~/.cabal/config` like `program-default-options` → `ghc-options`, or similar? Grepping in the Agda source isn't turning anything up, so I don't think that option is set here.

Also, `error` is defined in `Prelude`, and hasn't changed in forever, so it's not a GHC version issue; and the file mentioned in that message only uses explicit imports.

**Comment by mouse07410** [comment]
> Do you have `-Wname-shadowing` somewhere in your `~/.cabal/config`

I'm certain that I don't.

On the other hand, I do have `ghc-options: -Wall` there.

Thus, two questions:
1. Why is there a name shadowing in the code? and
2. Who/where set `-Werror`, because without it (as I understand) warnings should remain just that - warnings, and not cause the compilation to fail.

**Comment by jespercockx** [comment]
Agda sets `-werror` in its `.cabal` file: https://github.com/agda/agda/blob/dc099484ce3af04922b3b8540411d8caebad5105/Agda.cabal#L614

**Comment by mouse07410** [comment]
> Agda sets `-Werror` in its `.cabal` file...

So, Agda *wants* to hard-fail the build upon a warning?

Well, in that case let's fix this one. An alternative is removing `-Werror`.

**Comment by asr** [comment]
> So, Agda wants to hard-fail the build upon a warning?

Yes! We want to fail in the warnings we *chose*.

**Comment by mouse07410** [comment]
> Yes! We want to fail in the warnings *we chose*

Well, and in my projects I want to see *all* the warnings, but *not* hard-fail in general.

@asr , how do we reconcile? Comments in `Agda.cabal` seem to suggest that `-w ` flag there should disable *all* the warnings - so why did it not disable `-Wall` in `~/.cabal/config`? Is there another way - or do I need to muck with `~/.cabal/config` if I want Agda build to succeed?

**Comment by jespercockx** [comment]
Failing hard on certain kinds of warnings is absolutely essential for the development process of Agda, e.g. changing anything to Agda would not be feasible without the coverage checker.

> Is there another way - or do I need to muck with ~/.cabal/config if I want Agda build to succeed?

You could remove `-Werror` from `Agda.cabal` locally.

**Comment by mouse07410** [comment]
> We want to **fail in the warnings *we chose***

In that case why don't you do it the right way, and explicitly state exactly that:
```diff
diff --git a/Agda.cabal b/Agda.cabal
index 5c9561593..d13e502f8 100644
--- a/Agda.cabal
+++ b/Agda.cabal
@@ -611,39 +611,34 @@ library
   ghc-options: -fexpose-all-unfoldings
                -fspecialise-aggressively
                -fprint-potential-instances
-               -- Initially, we disable all the warnings.
-               -w
-               -Werror
-               -- This option must be the first one after disabling the
-               -- warnings. See Issue #2094.
-               -Wunrecognised-warning-flags
-               -Wdeprecated-flags
-               -Wderiving-typeable
-               -Wdodgy-exports
-               -Wdodgy-foreign-imports
-               -Wdodgy-imports
-               -Wduplicate-exports
-               -Wempty-enumerations
-               -Widentities
-               -Wincomplete-patterns
-               -Winline-rule-shadowing
-               -Wmissing-fields
-               -Wmissing-methods
-               -Wmissing-pattern-synonym-signatures
-               -Wmissing-signatures
-               -Wnoncanonical-monad-instances
-               -Wnoncanonical-monoid-instances
-               -Woverflowed-literals
-               -Woverlapping-patterns
-               -Wsemigroup
-               -Wtabs
-               -Wtyped-holes
-               -Wunrecognised-pragmas
-               -Wunticked-promoted-constructors
-               -Wunused-do-bind
-               -Wunused-foralls
-               -Wwarnings-deprecations
-               -Wwrong-do-bind
+               -Werror=unrecognised-warning-flags
+               -Werror=deprecated-flags
+               -Werror=deriving-typeable
+               -Werror=dodgy-exports
+               -Werror=dodgy-foreign-imports
+               -Werror=dodgy-imports
+               -Werror=duplicate-exports
+               -Werror=empty-enumerations
+               -Werror=identities
+               -Werror=incomplete-patterns
+               -Werror=inline-rule-shadowing
+               -Werror=missing-fields
+               -Werror=missing-methods
+               -Werror=missing-pattern-synonym-signatures
+               -Werror=missing-signatures
+               -Werror=noncanonical-monad-instances
+               -Werror=noncanonical-monoid-instances
+               -Werror=overflowed-literals
+               -Werror=overlapping-patterns
+               -Werror=semigroup
+               -Werror=tabs
+               -Werror=typed-holes
+               -Werror=unrecognised-pragmas
+               -Werror=unticked-promoted-constructors
+               -Werror=unused-do-bind
+               -Werror=unused-foralls
+               -Werror=warnings-deprecations
+               -Werror=wrong-do-bind
 
   -- NOTE: If adding flags, also add to `.ghci-8.2`
   if impl(ghc >= 8.2)
@@ -880,39 +875,34 @@ test-suite agda-tests
   ghc-options: -fexpose-all-unfoldings
                -fspecialise-aggressively
                -threaded
-               -- Initially, we disable all the warnings.
-               -w
-               -Werror
-               -- This option must be the first one after disabling the
-               -- warnings. See Issue #2094.
-               -Wunrecognised-warning-flags
-               -Wdeprecated-flags
-               -Wderiving-typeable
-               -Wdodgy-exports
-               -Wdodgy-foreign-imports
-               -Wdodgy-imports
-               -Wduplicate-exports
-               -Wempty-enumerations
-               -Widentities
-               -Wincomplete-patterns
-               -Winline-rule-shadowing
-               -Wmissing-fields
-               -Wmissing-methods
-               -Wmissing-pattern-synonym-signatures
-               -Wmissing-signatures
-               -Wnoncanonical-monad-instances
-               -Wnoncanonical-monoid-instances
-               -Woverflowed-literals
-               -Woverlapping-patterns
-               -Wsemigroup
-               -Wtabs
-               -Wtyped-holes
-               -Wunrecognised-pragmas
-               -Wunticked-promoted-constructors
-               -Wunused-do-bind
-               -Wunused-foralls
-               -Wwarnings-deprecations
-               -Wwrong-do-bind
+               -Werror=unrecognised-warning-flags
+               -Werror=deprecated-flags
+               -Werror=deriving-typeable
+               -Werror=dodgy-exports
+               -Werror=dodgy-foreign-imports
+               -Werror=dodgy-imports
+               -Werror=duplicate-exports
+               -Werror=empty-enumerations
+               -Werror=identities
+               -Werror=incomplete-patterns
+               -Werror=inline-rule-shadowing
+               -Werror=missing-fields
+               -Werror=missing-methods
+               -Werror=missing-pattern-synonym-signatures
+               -Werror=missing-signatures
+               -Werror=noncanonical-monad-instances
+               -Werror=noncanonical-monoid-instances
+               -Werror=overflowed-literals
+               -Werror=overlapping-patterns
+               -Werror=semigroup
+               -Werror=tabs
+               -Werror=typed-holes
+               -Werror=unrecognised-pragmas
+               -Werror=unticked-promoted-constructors
+               -Werror=unused-do-bind
+               -Werror=unused-foralls
+               -Werror=warnings-deprecations
+               -Werror=wrong-do-bind
 
   -- ASR (2017-04-11). TODO: Using -Wmissing-home-modules generates an
   -- error.
```

No offense meant, but the way it's currently done in `Agda.cabal` is tail-end-first, to put it politely. You want specific warnings to fail the build - then just say so, rather than disable all the warnings, make *all* the warnings fail, and enable specific warnings.

I've tested this patch, and it works fine. Attaching for your convenience.

[agda.cabal.diff.txt](https://github.com/agda/agda/files/5002350/agda.cabal.diff.txt)

**Comment by guillaumebrunerie** [comment]
Does it work with GHC 8.0.2? The `-Werror=` syntax is not mentioned in the docs for 8.0.2 and Agda still explicitly supports that version of GHC.

**Comment by mouse07410** [comment]
> Does it work with GHC 8.0.2? 

Hmm... Glad you didn't ask about GHC-7.10.3... I've no clue (and, I'm afraid, am not about to find out).

If you worry so much about 8.0.2 - why don't you add something like 
```
if impl(ghc <= 8.0.2)
. . . . .
```
doing warning the "weird" way? And switch the rest to what normal GHC compilers support with something like `if impl(ghc >= 8.2.2)`?

> Agda still explicitly supports that version of GHC

In that case *you* should be able to tell whether it works with 8.0.2 as-is, or the above-described workaround is required.

But it is, er, unwise to make life harder for (I assume) the majority of the users for the sake of a several-years-obsolete compiler, whose needs can be trivially addressed with a fairly minor change to `Agda.cabal`.

**Comment by asr** [comment]
> I've tested this patch, and it works fine. Attaching for your convenience.
> 
> [agda.cabal.diff.txt](https://github.com/agda/agda/files/5002350/agda.cabal.diff.txt)

Why you didn't include all the warnings in your patch?

**Comment by asr** [comment]
The `-Werror=` syntax didn't work on GHC 8.0.2. Please add to your patch the `if impl(ghc <= 8.0.2)` you mentioned before.

**Comment by mouse07410** [comment]
> Why you didn't include all the warnings in your patch?

Not sure what you meant. I've turned the set of warnings you wanted the build to fail upon, into a set of `-Werror=<that warning>`.

I suspect I missed the warnings at the very end of `Agda.cabal`:
```
. . . . .
 -- ASR (2017-04-11). TODO: Using -Wmissing-home-modules generates an
  -- error.
  -- NOTE: If adding flags, also add to `.ghci-8.2`
  if impl(ghc >= 8.2)
    ghc-options: -Wcpp-undef
                 -Wsimplifiable-class-constraints
                 -Wunbanged-strict-patterns

  -- NOTE: If adding flags, also add to `.ghci-8.6`
  if impl(ghc >= 8.6)
    ghc-options: -Winaccessible-code
                 -Wstar-binder
                 -Wstar-is-type
```

This is the patch that includes them as well:
```diff
diff --git a/Agda.cabal b/Agda.cabal
index 5c9561593..1103dda5e 100644
--- a/Agda.cabal
+++ b/Agda.cabal
@@ -611,39 +611,34 @@ library
   ghc-options: -fexpose-all-unfoldings
                -fspecialise-aggressively
                -fprint-potential-instances
-               -- Initially, we disable all the warnings.
-               -w
-               -Werror
-               -- This option must be the first one after disabling the
-               -- warnings. See Issue #2094.
-               -Wunrecognised-warning-flags
-               -Wdeprecated-flags
-               -Wderiving-typeable
-               -Wdodgy-exports
-               -Wdodgy-foreign-imports
-               -Wdodgy-imports
-               -Wduplicate-exports
-               -Wempty-enumerations
-               -Widentities
-               -Wincomplete-patterns
-               -Winline-rule-shadowing
-               -Wmissing-fields
-               -Wmissing-methods
-               -Wmissing-pattern-synonym-signatures
-               -Wmissing-signatures
-               -Wnoncanonical-monad-instances
-               -Wnoncanonical-monoid-instances
-               -Woverflowed-literals
-               -Woverlapping-patterns
-               -Wsemigroup
-               -Wtabs
-               -Wtyped-holes
-               -Wunrecognised-pragmas
-               -Wunticked-promoted-constructors
-               -Wunused-do-bind
-               -Wunused-foralls
-               -Wwarnings-deprecations
-               -Wwrong-do-bind
+               -Werror=unrecognised-warning-flags
+               -Werror=deprecated-flags
+               -Werror=deriving-typeable
+               -Werror=dodgy-exports
+               -Werror=dodgy-foreign-imports
+               -Werror=dodgy-imports
+               -Werror=duplicate-exports
+               -Werror=empty-enumerations
+               -Werror=identities
+               -Werror=incomplete-patterns
+               -Werror=inline-rule-shadowing
+               -Werror=missing-fields
+               -Werror=missing-methods
+               -Werror=missing-pattern-synonym-signatures
+               -Werror=missing-signatures
+               -Werror=noncanonical-monad-instances
+               -Werror=noncanonical-monoid-instances
+               -Werror=overflowed-literals
+               -Werror=overlapping-patterns
+               -Werror=semigroup
+               -Werror=tabs
+               -Werror=typed-holes
+               -Werror=unrecognised-pragmas
+               -Werror=unticked-promoted-constructors
+               -Werror=unused-do-bind
+               -Werror=unused-foralls
+               -Werror=warnings-deprecations
+               -Werror=wrong-do-bind
 
   -- NOTE: If adding flags, also add to `.ghci-8.2`
   if impl(ghc >= 8.2)
@@ -880,50 +875,45 @@ test-suite agda-tests
   ghc-options: -fexpose-all-unfoldings
                -fspecialise-aggressively
                -threaded
-               -- Initially, we disable all the warnings.
-               -w
-               -Werror
-               -- This option must be the first one after disabling the
-               -- warnings. See Issue #2094.
-               -Wunrecognised-warning-flags
-               -Wdeprecated-flags
-               -Wderiving-typeable
-               -Wdodgy-exports
-               -Wdodgy-foreign-imports
-               -Wdodgy-imports
-               -Wduplicate-exports
-               -Wempty-enumerations
-               -Widentities
-               -Wincomplete-patterns
-               -Winline-rule-shadowing
-               -Wmissing-fields
-               -Wmissing-methods
-               -Wmissing-pattern-synonym-signatures
-               -Wmissing-signatures
-               -Wnoncanonical-monad-instances
-               -Wnoncanonical-monoid-instances
-               -Woverflowed-literals
-               -Woverlapping-patterns
-               -Wsemigroup
-               -Wtabs
-               -Wtyped-holes
-               -Wunrecognised-pragmas
-               -Wunticked-promoted-constructors
-               -Wunused-do-bind
-               -Wunused-foralls
-               -Wwarnings-deprecations
-               -Wwrong-do-bind
+               -Werror=unrecognised-warning-flags
+               -Werror=deprecated-flags
+               -Werror=deriving-typeable
+               -Werror=dodgy-exports
+               -Werror=dodgy-foreign-imports
+               -Werror=dodgy-imports
+               -Werror=duplicate-exports
+               -Werror=empty-enumerations
+               -Werror=identities
+               -Werror=incomplete-patterns
+               -Werror=inline-rule-shadowing
+               -Werror=missing-fields
+               -Werror=missing-methods
+               -Werror=missing-pattern-synonym-signatures
+               -Werror=missing-signatures
+               -Werror=noncanonical-monad-instances
+               -Werror=noncanonical-monoid-instances
+               -Werror=overflowed-literals
+               -Werror=overlapping-patterns
+               -Werror=semigroup
+               -Werror=tabs
+               -Werror=typed-holes
+               -Werror=unrecognised-pragmas
+               -Werror=unticked-promoted-constructors
+               -Werror=unused-do-bind
+               -Werror=unused-foralls
+               -Werror=warnings-deprecations
+               -Werror=wrong-do-bind
 
   -- ASR (2017-04-11). TODO: Using -Wmissing-home-modules generates an
   -- error.
   -- NOTE: If adding flags, also add to `.ghci-8.2`
   if impl(ghc >= 8.2)
-    ghc-options: -Wcpp-undef
-                 -Wsimplifiable-class-constraints
-                 -Wunbanged-strict-patterns
+    ghc-options: -Werror=cpp-undef
+                 -Werror=simplifiable-class-constraints
+                 -Werror=unbanged-strict-patterns
 
   -- NOTE: If adding flags, also add to `.ghci-8.6`
   if impl(ghc >= 8.6)
-    ghc-options: -Winaccessible-code
-                 -Wstar-binder
-                 -Wstar-is-type
+    ghc-options: -Werror=inaccessible-code
+                 -Werror=star-binder
+                 -Werror=star-is-type
```

But if you really worry about GHC-8.0.2, you'd have to modify that patch, and not only change those, e.g., last `-Wstar-binder` to `-Werror=star-binder` - but also add the `if impl(ghc >= ???)` guards around those, and add the clause with the appropriate warning treatment for `if impl(ghc <= 8.0.2)`.

**Comment by guillaumebrunerie** [comment]
> > Does it work with GHC 8.0.2?
> 
> Hmm... Glad you didn't ask about GHC-7.10.3... I've no clue (and, I'm afraid, am not about to find out).

GHC 8.0.2 is the version shipped with Ubuntu 18.04 LTS, which is still used by many people (at least until 20.04.1 gets released and people on 18.04 get the upgrade). It is not a random old version as you seem to assume.

> If you worry so much about 8.0.2 - why don't you add something like
> 
> ```
> if impl(ghc <= 8.0.2)
> . . . . .
> ```
> 
> doing warning the "weird" way? And switch the rest to what normal GHC compilers support with something like `if impl(ghc >= 8.2.2)`?
> 
> > Agda still explicitly supports that version of GHC
> 
> In that case _you_ should be able to tell whether it works with 8.0.2 as-is, or the above-described workaround is required.

I personally don’t know much about GHC flags, why should _I_ be able to tell? I’m just pointing out that at the moment, Agda supports GHC 8.0.2. On the other hand you’re the one proposing a patch, so it is your responsibility to make sure it actually works with all the versions of GHC that Agda supports.

> But it is, er, unwise to make life harder for (I assume) the majority of the users for the sake of a several-years-obsolete compiler, whose needs can be trivially addressed with a fairly minor change to `Agda.cabal`.

Feel free to discuss dropping support for GHC 8.0.2 in the corresponding issue #4799.

**Comment by asr** [comment]
> But if you really worry about GHC-8.0.2, you'd have to modify that patch, and not only change those, e.g., last `-Wstar-binder` to `-Werror=star-binder` - but also add the `if impl(ghc >= ???)` guards around those, and add the clause with the appropriate warning treatment for `if impl(ghc <= 8.0.2)`.

I cannot apply your patch because we support GHC 8.0.2.

**Comment by mouse07410** [comment]
> I cannot apply your patch because we support GHC 8.0.2.

Please consider this one: [agda.cabal.diff.txt](https://github.com/agda/agda/files/5002709/agda.cabal.diff.txt)

It should support GHC-8.0.2.

> I personally don’t know much about GHC flags, why should I be able to tell?

Because you claim to support that specific compiler?

> you’re the one proposing a patch, so it is your responsibility to make sure it actually works with all the versions of GHC that Agda supports

OK, that's fair. See above - the latest/current patch should support 8.0.2 and above.

**Comment by asr** [comment]
Before applying a patch it should pass our CI (Travis and GitHub). I don't know if your patch pass our CI. I suggest create a pull request.

**Comment by mouse07410** [comment]
~~I'd rather not clone Agda. I've provided everything that's needed - would you be able to create a branch, apply the patch to it, and see if CI passes?~~

*Turned out simple enough, and I don't mind looking at the CI results myself. PR #4817 submitted.*

Tests I ran locally all passed, but I don't have 8.0.2.

**Comment by asr** [comment]
We can not look for the CI results of every submitted PR...

**Comment by mouse07410** [comment]
> > > I suggest create a pull request.
> >
> > *Turned out simple enough, and I don't mind looking at the CI results myself. PR #4817 submitted*
>
> We can not look for the CI results of every submitted PR...

??? Explain yourself, please ???

**Comment by mouse07410** [comment]
@asr Regardless, all the CI passed.

**Comment by asr** [comment]
Tell me when your PR passed the CI.

**Comment by mouse07410** [comment]
@asr It already has, as far as I can tell.

**Comment by rwe** [comment]
@mouse07410 — I appreciate that you like having warnings turned on: I'd created the tracking issue #4799 (drop support for 8.0.2) specifically with the intention of re-introducing some other warnings once that can be done.

On a separate note, from an outside perspective: Please try to be a bit more polite in your interactions here. It's great that you're contributing patches and concrete suggestions here, and I can see that they're taken seriously and appreciated. But deriding a project and repeatedly demanding other people to explain themselves to you is very abrasive. You'll find that collaboration becomes a _lot_ easier if you start with the recognition that people don't owe you anything, and then figure out how to work with them anyway. Just a little more sensitivity to tone and context would help.

Best of luck.

**Comment by mouse07410** [comment]
> Please try to be a bit more polite in your interactions here.

Good point. 

But I'm tired, hungry (religious fast), and under pressure at work (something unexpected popped up that required urgent attention). Not an excuse - just an explanation. 

### Update
As I owe an apology - here it is. Will try to be more "palatable" in the future.

**Comment by asr** [comment]
@rwe, thank you for writing the separate note. I had planned to write something about it.

**Comment by andreasabel** [comment]
Thanks for your contribution @mouse07410 and the good reviewing work, @rwe and @asr.
