### ISSUE TITLE
"Violation detected" message...?

### ISSUE THREAD

**Issue by mouse07410** [agda/agda#4816]
```
src/fix-whitespace/dist/build/fix-whitespace/fix-whitespace --check
[ Violation detected ] Agda.cabal
make: *** [check-whitespace] Error 1
```

How do I interpret this? What violation? Where in the 996-lines-long file?

**Comment by jespercockx** [comment]
You can fix all violations to the whitespace policy automatically by running `fix-agda-whitespace`. Perhaps the error message could be improved to mention this.

**Comment by mouse07410** [comment]
> Perhaps the error message could be improved to mention this.

Yes please! 

And it would be nice if it provided the location(s) of the discovered error(s).

**Comment by asr** [comment]
You can file/create an request/issue/PR on https://github.com/agda/fix-whitespace.

**Comment by mouse07410** [comment]
Created an issue: https://github.com/agda/fix-whitespace/issues/7
