### ISSUE TITLE
Symlinks are incorrectly followed during compilation

### ISSUE THREAD

**Issue by endobson** [agda/agda#4828]
I'm trying to use agda in an environment where the source code is a symlink to actual files stored elsewhere. It seems that agda is following the symlink and treating the target as the actual file, instead of just using the directory where the command was run from.

Example: https://github.com/endobson/examples/tree/agda-symlink

Run command in dir2
```
endobson@valhalla () ~/proj/examples/dir2 % agda foo.agda
Checking foo (/Users/endobson/proj/examples/dir1/foo.agda).
```

Observe `.agdai` file created in dir1.
```
endobson@valhalla () ~/proj/examples % ls -R
dir1 dir2

./dir1:
foo.agda  foo.agdai

./dir2:
foo.agda
```

**Comment by rwe** [comment]
I'd agree that this is a bug. (At minimum, it is inconsistent with unix tooling convention: for example `cc` and `ghc` do not do this; there are good reasons not to.)

This behaviour still occurs if you provide the absolute path, as demonstrated below. It also occurs with or without `--local-interfaces`.

I suspect this is related to some of the discussion in #4526.

Repro script for other developers:
```sh
issue_dir="${PWD}/issue-4828"

mkdir -p "${issue_dir}"/{src,sym}
echo 'module Foo where' > "${issue_dir}"/src/Foo.agda
ln -s ../src/Foo.agda "${issue_dir}"/sym/Foo.agda

echo "Before:"
tree --noreport issue-4828
echo ''
echo "Executing 'agda ${issue_dir}/sym/Foo.agda'"
(cd "${issue_dir}"/sym && agda "${issue_dir}/sym/Foo.agda")
echo ''
echo "After:"
tree --noreport issue-4828
```

Yields:
> ```
> Before:
> issue-4828
> ├── src
> │   └── Foo.agda
> └── sym
>     └── Foo.agda -> ../src/Foo.agda
> 
> Executing 'agda /Users/rwe/Code/ext/agda/issue-4828/sym/Foo.agda'
> Checking foo (/Users/rwe/Code/ext/agda/issue-4828/src/Foo.agda).
> 
> After:
> issue-4828
> ├── src
> │   ├── Foo.agda
> │   └── Foo.agdai
> └── sym
>     └── Foo.agda -> ../src/Foo.agda
> ```

However it's expected that `Foo.agdai` would be placed under `sym`, which was the invoked target location.

If you replace `.agda` with `.hs` and call with `ghc`, you'll see the output placed in `sym` as expected. If you replace it with `.c` and `module Foo where` with `int main() { return 0; }` and call with `cc`, that also places under `sym`.

**Comment by andreasabel** [comment]
I also agree that this is a bug.  The normalization of paths to obtain unique identification of modules is one of the ancient mechanisms inside Agda and should be revised for the sake of this issue.
