### ISSUE TITLE
Cannot report bug because installation runs out of memory

### ISSUE THREAD

**Issue by nickcollins** [agda/agda#4832]
I have a bug I want to report, but before I do so, I want to make sure it repros on the latest version of Agda. I'm on 2.6.0.1, so I thought I would `cabal install agda`, but that hits an out of memory error after using over 6 GB of ram. There is clearly a memory leak. Since I can't update, I can't repro, and so it's not really feasible to report the agda bug I found. This may be a problem for bug discovery, since many people may be withholding bug reports for the same or similar reasons.

**Comment by asr** [comment]
GHC version? Duplicated #4521.

**Comment by andreasabel** [comment]
One more reason to release 2.6.1.1.
