### ISSUE TITLE
NameId clash caused by default Set and Prop import in cached type check log

### ISSUE THREAD

**Issue by uncle-betty** [agda/agda#4835]
I encountered a rare issue in current `master` (e4842b2): I manage to get Agda into a state where type-checking my project fails as follows:

```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Monad/Signature.hs:727
```

I can get out of this state again by removing the `_build` directory, which I currently use as a workaround.

I am only able to reproduce this issue via Emacs interaction, not via command line invocations of Agda. Unfortunately, so far, I also have been unable to reproduce this issue with a shorter source code excerpt.

As reproducing the issue requires Emacs interaction, I thought that it might make things clearer, if I provided a screen recording of me reproducing the issue. It's here:

https://asciinema.org/a/AhwJdumn7QbVxXsaUKYYUVZWZ

In the recorded session I use a source code archive, `repro.tar.gz`, which is available here:

https://lopatic.de/repro.tar.gz

Here's how I reproduce the issue in the above recorded session:

* 0:00 - extract source code archive, `repro.tar.gz`, start Emacs
* 0:14 - open file `Test.agda` (my top-level source code file) to start Agda mode
* 0:24 - show Agda version
* 0:30 - load / type-check `Test.agda` (and, transitively, all other source code files)
* 1:22 - open file `SMT.agda`, insert new definition: `foo = true`.
* 1:41 - load / type-check modified `SMT.agda`
* 1:50 - switch back to `Test.agda` buffer
* 1:55 - add definition inserted into `SMT.agda` (`foo`) to imports from `SMT.agda`
* 2:03 - load / type-check `Test.agda` - which produces the error
* 2:10 - leave Emacs, show that type-checking fails on command line as well (I use the `-git` program name suffix for the Agda version from current `master`)
* 2:44 - remove `_build`, show that type-checking now succeeds

Apologies for the unusual submission format. I just ran out of ideas on how to narrow this down a little more. Please let me know, if you would like me to do something different for you. Happy to help investigate this.

This issue isn't a big deal for me, as there is a simple workaround. I am also aware that reproducing this is a little involved. Moreover, it's `master` and not an official release. So please do feel free to simply close this issue, if it doesn't seem worth an investigation. I just thought that I'd let you know.

Thank you for maintaining Agda. After years of imperative programming, it feels like a breath of fresh air to me.

**Comment by uncle-betty** [comment]
I found the following simplifications to the procedure outline above:

* After switching from `SMT.agda` back to the `Test.agda` buffer, it is enough to simply load / type-check `Test.agda`. I.e., it is not necessary to add `foo` to the list of definitions imported by `Test.agda` from `SMT.agda`.

* Instead of completely removing the `_build` directory to fix the situation, it is enough to remove `_build/2.6.2/agda/SMT.agdai`.

**Comment by uncle-betty** [comment]
Reproducing the issue with `--verbose impossible:10` yields the following additional information:

```
tlo@carol:~/repro$ agda-git --verbose impossible:10 Test.agda
Checking Test (/home/tlo/repro/Test.agda).
Ambiguous name: Name {nameId = NameId 6 14152749608738415985, nameConcrete = Name {nameRange = NoRange, nameInScope = InScope, nameNameParts = Id "Lit" :| []}, nameCanonical = Name {nameRange = NoRange, nameInScope = InScope, nameNameParts = Id "Lit" :| []}, nameBindingSite = Range (Just (AbsolutePath {byteStringPath = "/home/tlo/repro/SAT.agda"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 1240, posLine = 34, posCol = 6}, iEnd = Pn {srcFile = (), posPos = 1243, posLine = 34, posCol = 9}}]), nameFixity = Fixity' {theFixity = Fixity {fixityRange = NoRange, fixityLevel = Unrelated, fixityAssoc = NonAssoc}, theNotation = [], theNameRange = NoRange}, nameIsRecordName = False}
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Monad/Signature.hs:727
```

Odd. Seems unrelated to the inserted definition. Even unrelated to the file into which the definition was inserted (`SAT.agda` vs. `SMT.agda`). And yet, removing `SMT.agdai` fixes the issue.

**Comment by uncle-betty** [comment]
Looks like removing `SMT.agdai` makes Agda rebuild `SMT.agdai` as well as `Test.agdai`. I added a `show` to the Agda code to dump the deserialized `Instance`s in textual form after having triggered the error:

* https://lopatic.de/err-test.txt - the dumped contents of the broken `Test.agdai`
* https://lopatic.de/err-smt.txt - the same for `SMT.agdai`

I then removed `SMT.agdai` and type-checked everything again to make the issue go away. Then I dumped the `Instance`s from the working files:

* https://lopatic.de/ok-test.txt - the dumped contents of the working `Test.agdai`
* https://lopatic.de/ok-smt.txt - the same for `SMT.agdai`

I figured that maybe looking at the differences between the non-working and working files might be valueable to someone who knows their way around `.agdai` files.

**Comment by uncle-betty** [comment]
Here are the same four files split into lines and indented using a simple heuristic:

https://lopatic.de/pretty-err-test.txt
https://lopatic.de/pretty-err-smt.txt
https://lopatic.de/pretty-ok-test.txt
https://lopatic.de/pretty-ok-smt.txt

(The files are pretty big. Maybe right-click the links and save the files instead of having the browser display them.)

One thing I noticed: In the broken `Test.agdai` all `NameId`s for definitions in `SMT.agda` are off by 2. The second component (module ID) looks OK, but the first component is off. For instance, the `NameId` for `Formula`:

* `pretty-err-test.txt` (broken `Test.agdai`) says `nameId = NameId 2 14677862825608656242`
* `pretty-ok-test.txt` (working `Test.agdai`) says `nameId = NameId 4 14677862825608656242`
* Both, `pretty-err-smt.txt` (broken `SMT.agdai`) as well as `pretty-ok-smt.txt` (working `SMT.agdai`) say `nameId = NameId 4 14677862825608656242`

So, maybe when I insert the `foo = true` definition into `SMT.agda` and type-check this file, then this changes the `NameId`s in `SMT.agdai`. However, it doesn't change the `NameId`s in `Test.agdai`. When I then type-check `Test.agdai`, the `NameId`s in there still don't get fixed.

Just noticed this when diffing the `err` and `ok` files. I can't tell, though, whether this could lead to the observed error about an ambiguous name in a different file, `SAT.agda`. Maybe it's a red herring. It doesn't seem right, though.

**Comment by uncle-betty** [comment]
Ah, never mind `Test.agdai`. I'm type-checking `Test.agda`, which means that I'm re-creating `Test.agdai`. So, the contents of `Test.agdai` should not factor into any of this.

And of course the `NameId`s in `Test.agdai` would be off - in the failure case I don't manage to type-check `Test.agda` and hence the existing `Test.agdai` is never overwritten and retains its old contents.

I guess the key to all of this then lies solely in `SMT.agdai`. I'll sleep it over. This is quite the learning experience for me.

**Comment by uncle-betty** [comment]
Oh, and I should have provided the ambiguous result of the lookup:

* https://lopatic.de/defs.txt - the lookup in `defs`
* https://lopatic.de/idefs.txt - the lookup in `idefs`

The `QName` in `idefs.txt` looks a little odd to me. The module ID in the `qnameModule` (`NameId 0 14677862825608656242`) does not match the module ID in the `qnameName` (`NameId 23 10189251152579365012`). The former is the module ID for the `SMT` module, the latter is the module ID for the `Test` module.

Similarly, when I look at the differences between the broken `SMT.agdai` and the working `SMT.agdai`, the former contains a lot of `10189251152579365012` module IDs (i.e., the `Test` module's), all of which have been changed to `14677862825608656242` (i.e., the `SMT` module's) in the working `SMT.agdai`.

**Comment by uncle-betty** [comment]
Maybe the mismatching module ID actually has something to do with the issue. When I rename `Test`, say, to `Bob` then this also fixes the issue:

```
tlo@carol:~/repro$ agda-git Test.agda
Checking Test (/home/tlo/cvc4agda/Test.agda).
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Monad/Signature.hs:727
tlo@carol:~/repro$ sed -e 's/module Test/module Bob/' <Test.agda >Bob.agda
tlo@carol:~/repro$ agda-git Bob.agda
tlo@carol:~/repro$
```

Maybe `Test`'s module ID ending up in `SMT` leads to a `NameId` clash between `Test` and `SMT`, which can also be resolved by renaming `Test`.

**Comment by uncle-betty** [comment]
The more you learn... Some new data about the issue:

* I don't even have to add a new definition (`foo = true`) to `SMT.agda` to trigger the issue. I don't even have to change any "real" code, either. It's enough to change a single character in a comment in `SMT.agda`.  To change the file's hash value, I guess.

* Also, the **module IDs are the only differences** between a broken and a working `SMT.agdai` file.

So, what I'm doing right now to reproduce the issue:

* Open `Test.agda` in Emacs. Type-check the file and, transitively, all other files.
* Open `SMT.agda` in Emacs. Change a character in a comment. Type-check the file.
* Switch back to the `Test.agda` buffer. Type-check the file and get the error.

I now also have a little Haskell tool to dump `.agdai` files:

```
import Agda.Interaction.Options
import Agda.TypeChecking.Monad.Base
import Agda.TypeChecking.Monad.Options
import Agda.TypeChecking.Serialise

main = do
  res <- runTCMTop $ do
    setCommandLineOptions $ defaultOptions {optIncludePaths = ["../agda/git/std-lib/src"]}
    decodeFile "SMT.agdai"
  putStrLn $ show res
```

Note that it requires `SMT.agda` side-by-side with `SMT.agdai` for some reason, both in the current directory. `optIncludePaths` points to the standard library.

I used it to dump a broken `SMT.agdai` file (broken by said single-character change to a comment) and a working `SMT.agdai` file. The results are here - two files of exactly the same size:

* https://lopatic.de/dump-err.txt
* https://lopatic.de/dump-ok.txt

The order in which things are dumped seems a little non-deterministic, but using `sort` on the files and then `diff`ing the resulting two sorted files proves that the only differences are the module IDs.

**Comment by uncle-betty** [comment]
Oh, and to pretty-print the dumped `.agdai` files I use this Python script. Just in case anybody wants to run their own experiments.

```
#!/usr/bin/env python3

import sys

out = ""
ind = ""
lf = False

while True:
    x = sys.stdin.read(1)

    if x == "":
        break

    if x == "}" or x == "]":
        ind = ind[:-2]
        lf = True

    if lf:
        out += "\n" + ind
        lf = False

    if x == "{" or x == "[":
        ind = ind + "  "
        lf = True

    out += x

print(out)
```

**Comment by uncle-betty** [comment]
Holy moly! I think that I figured it out. Here's what I believe is happening:

* I type-check `Test.agda`, which transitively type-checks all imports and, finally, `Test.agda` itself. This leaves the `Test` module in the cached type check log.

* I then type-check `SMT.agda`. As this is a different module, the cached type check log should be purged. However, the first declaration in the `SMT` module is identical to the first declaration in the `Test` module: it's the import for `Set` and `Prop` that Agda now automatically inserts by default at the very beginning of a module.

* So, the first declaration in the `SMT` module is identical to the first declaration in the cached type check log. This means that Agda runs `restorePostScopeState` with the first declaration in the cached type check log. So, we're now type-checking the `SMT` module with a post scope state created while type-checking `Test`.

* Among other things, the post scope state contains the module ID used to generate fresh `NameId`s while type-checking. This means that we're now generating `NameId`s with `Test`'s module ID instead of `SMT`'s. In my case, `NameId`s are generated during type-checking, for example, for the projection functions for data constructor arguments. These now all carry `Test`'s module ID. That's where the wrong module IDs come from that I saw in the `.agdai` files.

* This leads to a clash in my case. Both, `Test` as well as `SMT` use `NameId 27 m`, where `m` is `Test`'s module ID. Which then leads to the issue.

I'm not entirely sure how to fix this. To double-check the above analysis, I took out a big hammer:

```
diff --git a/src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs b/src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs
index 347474ed7..9a6bdbf4c 100644
--- a/src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs
+++ b/src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs
@@ -67,6 +67,7 @@ import Agda.TypeChecking.Monad.State
 import Agda.TypeChecking.Monad.MetaVars (registerInteractionPoint)
 import Agda.TypeChecking.Monad.Debug
 import Agda.TypeChecking.Monad.Env (insideDotPattern, isInsideDotPattern, getCurrentPath)
+import Agda.TypeChecking.Monad.Caching (cleanCachedLog)
 import Agda.TypeChecking.Rules.Builtin (isUntypedBuiltin, bindUntypedBuiltin, builtinKindOfName)

 import Agda.TypeChecking.Patterns.Abstract (expandPatternSynonyms)
@@ -1263,6 +1264,7 @@ instance ToAbstract (TopLevel [C.Declaration]) TopLevelInfo where
                   checkModuleName (C.toTopLevelModuleName m0) (SourceFile file) $ Just expectedMName
                   return m0
           setTopLevelModule m
+          cleanCachedLog
           am           <- toAbstract (NewModuleQName m)
           noImportSorts <- not . optImportSorts <$> pragmaOptions
           -- Add implicit `open import Agda.Primitive using (Set; Prop)`
```

The above fixes the issue for me, but it also slows down type-checking. Maybe only clean the cache, if `setTopLevelModule m` actually changes the current top-level module, i.e., if the current top-level module is not `m`?

**Comment by uncle-betty** [comment]
Oh, I think that this might be the same as #4697. I should have looked harder. Sorry about that.

**Comment by andreasabel** [comment]
Thanks for investigating and the PR!  I asked @Saizan for a review since he is the author of the caching feature and knows it best.

**Comment by Saizan** [comment]
Thanks from me too!

I would be in favor of doing the module ID check in `cachingStarts`, so it's going to happen once and do the right thing even if we add more uses of `restorePostScopeState` somewhere. 

One could even add an assertion in `restorePostScopeState` that the module IDs must match, and otherwise throw an `__IMPOSSIBLE__`.

**Comment by uncle-betty** [comment]
I'm glad I can help!

Oh, right, yes. Agreed. `cachingStarts` would be a more central place. Let's do this. I pushed an updated proposal to the pull request's branch.

I tested the new fix and it still resolves the issue.
