### ISSUE TITLE
Agda.Syntax.Common: Modality and Quantity inconsistent Null.empty ↔︎ Monoid.mempty

### ISSUE THREAD

**Issue by rwe** [agda/agda#4845]
*Note:* This may be a non-bug. It's the only inconsistency of this type for this class that I've noticed, but due to varied use of `empty`/`mempty` elsewhere, could manifest as other issues.

## Summary

`Modality`'s `Null.empty` is defined to be `defaultModality` which is defined in terms of `defaultQuantity` which is `Quantityω`. However `Modality`'s `Monoid.mempty` is defined in terms of `mempty` which is `Quantity1`. Meaning for those types, `mempty` vs. `empty` are different, and these are the only types where this is the case. (Though it applies indirectly to types which may contain them).

https://github.com/agda/agda/blob/1545b6756e6fd16665fd17143b026f8d99ba903a/src/full/Agda/Syntax/Common.hs#L366-L370
https://github.com/agda/agda/blob/1545b6756e6fd16665fd17143b026f8d99ba903a/src/full/Agda/Syntax/Common.hs#L377-L378
https://github.com/agda/agda/blob/1545b6756e6fd16665fd17143b026f8d99ba903a/src/full/Agda/Syntax/Common.hs#L703
https://github.com/agda/agda/blob/1545b6756e6fd16665fd17143b026f8d99ba903a/src/full/Agda/Syntax/Common.hs#L767
https://github.com/agda/agda/blob/1545b6756e6fd16665fd17143b026f8d99ba903a/src/full/Agda/Syntax/Common.hs#L730-L731

## Background

I was looking at the `Agda.Utils.Null` class to understand whether its `empty` member always corresponded to `Monoid.mempty`/`Alternative.empty`/`MonoidPlus.mempty` when those existed. Mainly because I wanted to understand the expected semantics of that class, and understand the implication/resolution of those several instances with `null = __IMPOSSIBLE__`, and in which cases they might be redundant. (i.e. able to replace `empty` with `mempty` due to existing `Monoid` constraint).

Going through the `Null` instances brought me to the definitions of `Modality`/`Relevance`/`Quantity`/`Cohesion`.

Some areas of code initialize `Modality`-and-friends with `defaultModality` or `defaultQuantity`, and others with `mempty`. However because those are different, it's easy to imagine unintentional misuse. Especially in abstract cases, where some other type might initialize like `Null a => Null (Foo a) where null = mkFoo empty` or `Monoid a => Monoid (Foo a) where mempty = mkFoo mempty` and that difference propagates; or e.g. `unlessNull` which uses `Null.empty`, versus `Data.Foldable.fold` which uses `mempty`.

Because these types actually support both additive and multiplicative monoids, I'm not sure they should support bare `Monoid` instances at all (versus perhaps under something like `instance Monoid (Add Modality)`/`instance Monoid (Comp Modality)` `newtype` wrappers); but since they do, it's surprising to have the `empty` value correspond to neither the additive nor multiplicative identity.

Tagging @andreasabel and @jespercockx as potentially knowledgeable based on git logs. (Though, this is probably not important).

**Comment by jespercockx** [comment]
Since different parts of the Agda codebase were written by different people at different times, it seems rather likely that this inconsistency has crept in by mistake and not by intentional design. So it would indeed be a good idea to fix it so `empty` and `mempty` are equal at types where both are defined.

Regarding types with multiple possible `Monoid` instances, it indeed seems like a good idea to follow conventional Haskell wisdom and not implement any instance directly.

**Comment by andreasabel** [comment]
The original idea behind `Null` was to overload `List.null` for other collection types.  This has been extended to characterize the element(s) that represent "no information" (typically, the default elements).
For collections that implement `Monoid`, we should have `empty == mempty`.  Note that some collections, like `Maybe`, do not have a canonical implementation of concatenation, but a canonical notion of emptiness.

**Comment by rwe** [comment]
@andreasabel I wonder if the `Null` class predates the generalization of `List.null` to `Foldable.null`? That was another inconsistency I haven't dug into yet. Some classes derive `Foldable` _and_ `Null`, and the two `null` methods don't always match in those cases.

The derived `Foldable.null` is a little subtle:
```ghci
> data X a = NoX | HasX a deriving (Foldable)
> null (HasX [])
False
> data X a = NoX | HasX [a] deriving (Foldable)
> null (HasX [])
True
```

I think it's clear that the `Null` class is doesn't completely overlap any existing class.

As you said it doesn't require concatenation like `Monoid`/`MonadPlus`/`Alternative`, yet it _does_ require a kind of decidable equivalence which seems to sometimes denote the same kind of "emptiness" as `Foldable.null`.

My interpretation is the implementations of `null` basically form an equivalence class. Like a pointed set, but specifically one whose naming implies that the basepoint `empty` corresponds to emptiness in some other context, but that context is never named and is sometimes not entirely consistent. I'm looking into it still.
