### ISSUE TITLE
Termination checker fails on mixed copattern/pattern with No-K 

### ISSUE THREAD

**Issue by txa** [agda/agda#4846]
The following code passes the termination checker but fails when we enable `--without-K`:
```agda
f : (ℕ → ℕ) × ℕ

proj₁ f zero = zero

proj₁ f (suc x) = suc (proj₁ f x)

proj₂ f = zero
```

[bug.zip](https://github.com/agda/agda/files/5079048/bug.zip)
#2890

**Comment by andreasabel** [comment]
This problem has been reported before and a solution would be that the call graph generator recognizes `proj₁ f` as a function `g` on its own, and thus can "tighten the loop":  The second equation would be a recursive call on `g`.

For similar issues see https://github.com/agda/agda/issues?q=+label%3Atermination+label%3Awithout-K+ .  The reason that Agda rejects your code is #1023, if I am not mistaken.
