### ISSUE TITLE
Regression: Internal error in Signature.hs

### ISSUE THREAD

**Issue by wenkokke** [agda/agda#4855]
I've been triggering an internal error recently:
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Monad/Signature.hs:731
```
I don't currently have a minimized test case which triggers this error, but I'll add one if I get around to it.

**Comment by andreasabel** [comment]
The MWE is actually `test/Fail/Issue4671` containing just
```agda
import Agda.PRIMITIVE
```

**Comment by rwe** [comment]
For quick reference, the referenced line is the `__IMPOSSIBLE_VERBOSE__` line here: https://github.com/agda/agda/blob/201015fa97b9423833047240706e66c11b616980/src/full/Agda/TypeChecking/Monad/Signature.hs#L722-L731

**Comment by fredrikNordvallForsberg** [comment]
Is this perhaps https://github.com/agda/agda/issues/4835? It's the same `__IMPOSSIBLE_VERBOSE__`. Worth checking if the commit 6 hours ago fixed this already :slightly_smiling_face:.

**Comment by wenkokke** [comment]
@fredrikNordvallForsberg removing `_build` solves the issue, so it's likely a duplicate of #4835. Rebuilding Agda now.
