### ISSUE TITLE
Primitive conversion from Float to Rational

### ISSUE THREAD

**Issue by wenkokke** [agda/agda#4860]
I'd like to use floating-point notation in Agda to denote rational number. However, the only way to convert *out of* a floating-point number in Agda is by using `primShowFloat`, and then parsing the number, which probably isn't ideal.

I propose adding `primFloatToRat` function, which converts a floating-point number to a numerator (using `Agda.Builtin.Int`) and a denominator (using `Agda.Builtin.Nat`). We could that use this function to construct a conversion from floating-point to rational numbers.

However, there's some issues with regards to `NaN`, `+∞`, and `−∞`, which is why this is an issue and not a pull-request...

**Comment by UlfNorell** [comment]
The simplest solution would be `NaN -> 0/0`, and `±Inf -> ±1/0`.

**Comment by wenkokke** [comment]
Ohh, that would work, yes. I'll submit a pull request for `primFloatToRat`.

Should we add type classes akin to `FromNat` for integers and floats as well, so we can overload that syntax? (For the future, I'm not adding that.)

**Comment by nad** [comment]
We have encountered problems in the past when we have treated different representations of equal floating-point numbers differently. Is it currently the case that `NaN`, `Inf` and `-Inf` are mutually distinct and distinct from all other floating-point numbers? (I have not paid much attention to the changes related to floating-point numbers.)

**Comment by wenkokke** [comment]
Alternatively, I could attempt to implement this in terms of `primFloatToWord64` and `primWord64ToNat`? That might be a difficult representation to work with, though, so for clarity it's probably still best to do this as a primitive.

**Comment by UlfNorell** [comment]
That sounds like fun...

@nad `NaN` is not even equal to itself, so that's not an issue. I'm also fairly confident that `Inf != -Inf`..

**Comment by wenkokke** [comment]
> We have encountered problems in the past when we have treated different representations of equal floating-point numbers differently. Is it currently the case that `NaN`, `Inf` and `-Inf` are mutually distinct and distinct from all other floating-point numbers? (I have not paid much attention to the changes related to floating-point numbers.)

```agda
open import Data.Bool
open import Data.Float

NaN +∞ -∞ : Float
NaN =  0.0 ÷ 0.0
+∞  =  1.0 ÷ 0.0
-∞  = -1.0 ÷ 0.0

_ : T (NaN ≡ᵇ NaN)
_ = _
_ : T (+∞ ≡ᵇ +∞)
_ = _
_ : T (-∞ ≡ᵇ -∞)
_ = _
_ : T (not (NaN ≡ᵇ +∞))
_ = _
_ : T (not (NaN ≡ᵇ -∞))
_ = _
_ : T (not (+∞ ≡ᵇ -∞))
_ = _

_ : T (not (NaN ≈ᵇ NaN))
_ = _
_ : T (+∞ ≈ᵇ +∞)
_ = _
_ : T (-∞ ≈ᵇ -∞)
_ = _
_ : T (not (NaN ≈ᵇ +∞))
_ = _
_ : T (not (NaN ≈ᵇ -∞))
_ = _
_ : T (not (+∞ ≈ᵇ -∞))
_ = _
```

**Comment by wenkokke** [comment]
I think there's two primitive equalities for floats for exactly this reason, and the latter comes with some warnings about not using it to induce propositional equality.

**Comment by wenkokke** [comment]
What's the purpose of these? I'm guessing I'll have to add one of these?
```haskell
primFloatToWord64Injective :: TCM PrimitiveImpl
primFloatToWord64Injective = do
  float  <- primType (undefined :: Double)
  word   <- primType (undefined :: Word64)
  toWord <- primFunName <$> getPrimitive "primFloatToWord64"
  mkPrimInjective float word toWord
```
In general, what are the steps these days for adding a primitive?

1. Add entry to `Agda.TypeChecking.Primitive.primitiveFunctions`.
2. ...

**Comment by wenkokke** [comment]
With respect to my first question, I can see that `primFloatToWord64Injective` is exposed, but not defined in `Agda.Builtin.Float`, nor  re-exported by the standard library. Is that a bug?

**Comment by wenkokke** [comment]
Guess I'll have to patch the Haskell behaviour of `toRational`:
```
> toRational (0.0/0.0)
(-269653970229347386159395778618353710042696546841345985910145121736599013708251444699062715983611304031680170819807090036488184653221624933739271145959211186566651840137298227914453329401869141179179624428127508653257226023513694322210869665811240855745025766026879447359920868907719574457253034494436336205824) % 1
> toRational (1.0/0.0)
179769313486231590772930519078902473361797697894230657273430081157732675805500963132708477322407536021120113879871393357658789768814416622492847430639474124377767893424865485276302219601246094119453082952085005768838150682342462881473913110540827237163350510684586298239947245938479716304835356329624224137216 % 1
> toRational (-1.0/0.0)
(-179769313486231590772930519078902473361797697894230657273430081157732675805500963132708477322407536021120113879871393357658789768814416622492847430639474124377767893424865485276302219601246094119453082952085005768838150682342462881473913110540827237163350510684586298239947245938479716304835356329624224137216) % 1

```

**Comment by gallais** [comment]
How about a `Rational` instance instead just like we have `Number` and `Negative` for
overloaded naturals & negative numbers?

Cf. these instances in the stdlib to write down literals & have them interpreted as
rational literals: http://agda.github.io/agda-stdlib/Data.Rational.Literals.html
It relies on the `Agda.Builtin.From*` modules.


Seems silly to go the Rational -> Float -> Rational route.

**Comment by wenkokke** [comment]
> How about a `Rational` instance instead just like we have `Number` and `Negative` for overloaded naturals & negative numbers?

Makes sense. I guess slowly the name of the `Number` instance is seeming sillier and sillier, but that's a problem for future bikeshedding, I guess.

**Comment by wenkokke** [comment]
Closing as duplicate of #4868.

**Comment by wenkokke** [comment]
Closing as duplicate of #4868.
