### ISSUE TITLE
Primitive equality on Float is unintuitive

### ISSUE THREAD

**Issue by wenkokke** [agda/agda#4865]
The primitive equality on floats, induced via `toWord`, is deeply unintuitive, featuring greatest hits such as:
```agda
_ : False (-1312.0 <? 1312.0)
_ = _
_ : True (1312.0 <? -1312.0)
_ = _
_ : False (-0.0 <? 0.0)
_ = _
_ : True (0.0 <? -0.0)
_ = _
```
I understand that the numeric equality induces a broken propositional equality, but it may be better to just patch up the numeric order, and face the fact that we don't have a total order, rather than constructing a deeply unintuitive total order, based on the bit representation.

My guess is that if folks are going to start programming with Agda floating-point numbers, they'll use `_<?_`, and will end up being very surprised.

If we'd to have an order, our best option is probably to translate floating-point numbers to a dedicated datatype...
```agda
data Float : Set where
  nan    : Float
  posinf : Float
  neginf : Float
  number : (coefficient exponent : Int) -> Float
```
...and induce a partial order on that type.

**Comment by wenkokke** [comment]
One good solution might be to expose the datatype above to the user, but internally represent floating-point numbers using Haskell's Double, and convert on-the-fly.

**Comment by gallais** [comment]
Should I transfer this issue to the stdlib tracker?
This seems unrelated to Agda's builtins.

**Comment by wenkokke** [comment]
I think the best solution is to overhaul floating-point numbers, representing them using the proposed datatype in Agda, and backing them either with Haskell's Double and (past a certain size) with, e.g., [scientific](https://hackage.haskell.org/package/scientific)?

**Comment by wenkokke** [comment]
However, at very least, we'd need to add a primitive to convert primitive Float to the proposed datatype.

**Comment by wenkokke** [comment]
Closing as duplicate of #4868.
