### ISSUE TITLE
list literals and list comprehensions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#487]
I would like to see a better support for lists in Agda.

While we can almost fake list literals with infix operators, I would rather devotes the square brackets to list literals and list comprehensions as it is in Haskell.

Is this just a matter of development time? Is there better plans? Who strongly oppose to this?

Original issue reported on code.google.com by `nicolas....@gmail.com` on 3 Oct 2011 at 7:14

**Comment by andreasabel** [comment]
There is not any concrete proposal here.  I close this.
