### ISSUE TITLE
Internal error src/full/Agda/TypeChecking/Monad/Signature.hs:731

### ISSUE THREAD

**Issue by txa** [agda/agda#4871]
I frequently get this error:

> An internal error has occurred. Please report this as a bug.
> Location of the error: src/full/Agda/TypeChecking/Monad/Signature.hs:731

The workaround is to delete the .agdai files.

The version is

> Agda version 2.6.2-2dea7f2-dirty

**Comment by gallais** [comment]
Seems like a duplicate of #4855

**Comment by txa** [comment]
Indeed I googled for 731 but didn't fund this.
