### ISSUE TITLE
Strange reports for "unsolved" in 2.6.1

### ISSUE THREAD

**Issue by mechvel** [agda/agda#4879]
Agda 2.6.1 type checker often reports things like

_snd_1179 : Subsetoid.Member nzSubsetoid (proj₁ x)   [ at /home/Foo/Foo.agda:455,58-71 ]

It looks frightening and unclear - at least for a newbie.
I do guess that this is about some type unsolved, and it is easy to find the place, because the line number is printed.
But why does not Agda report any regular explanatory words, like, say  "the type of ... is not solved" ?

**Comment by andreasabel** [comment]
This is an unsolved (non-interaction) meta, which is displayed along the unsolved interaction metas (if there are any).  When you run Agda in non-interaction (batch) mode, then it will print `Unsolved metas at the following locations:`.

**Comment by mechvel** [comment]
(Now I only fix typos)
I understand it this way: in the batch mode the report is reasonable, and in the interactive mode the report is frightening and unclear.
I do not know of whether the thing is easy to fix. Personally I do not care, but this may frighten newbies.
