### ISSUE TITLE
"Illegal declaration(s) before top-level module" in Agda 2.6.1

### ISSUE THREAD

**Issue by mechvel** [agda/agda#4888]
Some typos (like "impor " instead of "import ") lead to this report.
But the report does not show the responsible line No, while there may be, say, 
100 lines of import declarations before the top level module.

**Comment by gallais** [comment]
At the point where we raise the error we do not know which of the
declarations is malformed. We could however do a bit more work and
try to convert them from concrete to abstract on the hope that this
will trigger an error!

I'll have a look at what this gets us.

**Comment by mechvel** [comment]
I thought that this is easy to fix.
But if it is difficult, then there are many other more important problems ...

**Comment by andreasabel** [comment]
Please remember to set the milestone when closing issues for the sake of the automatic changelog generation.
