### ISSUE TITLE
Give accepts term which is refuted by reload

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#489]
```
What's the problem? Cut-and-pasted program examples are preferred over
attachments (if reasonably short).

Load Types.agda.
Typing C-c C-SPACE in hole 0 succeeeds, but reload of file then fails.

What version of Agda are you using? On what operating system (if relevant)?
darcs version of 2011-10-04
```

Original issue reported on code.google.com by `andreas....@gmail.com` on 5 Oct 2011 at 7:57
- Merged into: #118

Attachments:
- [GiveBug.tgz](https://storage.googleapis.com/google-code-attachments/agda/issue-489/comment-0/GiveBug.tgz)

**Comment by andreasabel** [comment]
The original report (test case) has been lost here, `GiveBug.tgz`no longer exists.
