### ISSUE TITLE
Regression related to non-fibrant types

### ISSUE THREAD

**Issue by nad** [agda/agda#4899]
The following code is accepted by Agda 2.6.1, but rejected by Agda 2.6.2-d30045f:
```agda
{-# OPTIONS --cubical #-}

open import Agda.Builtin.Equality

data Unit : Set where
  unit : Unit

f : (x : Unit) → _

g : (x : Unit) → x ≡ x

f unit = refl

g x = f x
```
```
Cannot eliminate fibrant type Unit
unless target type is also fibrant
when checking that the pattern unit has type Unit
```
Three comments:
* It seems to me as if Agda is too eager to reject the definition of `f`.
* I don't see anything about support for non-fibrant types in the changelog.
* Perhaps there should be a flag that activates support for non-fibrant types.

**Comment by andreasabel** [comment]
bfc886e03a69571f84a8788699a606daa5e8ee7d is the first bad commit
@UlfNorell, bisection blames commit bfc886e03a69571f84a8788699a606daa5e8ee7d
```
Date:   Wed Aug 5 13:36:13 2020 +0200

    [ constraints ] Treat MetaV as Blocked
```
