### ISSUE TITLE
Release 2.6.1.1 with ghc-8.10.2 support

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#4904]
Since the Haskell Platform comes with ghc-8.10.2 and Agda-2.6.1 doesn't build with ghc-8.10.2 it would make sense to release a new version that does. I suggest we make only the minimal changes required for ghc-8.10.2. Thoughts?

cc @asr

**Comment by UlfNorell** [comment]
I pushed a `release-2.6.1.1` branch on top of `v2.6.1` with a relaxed bound in the `if`.

**Comment by UlfNorell** [comment]
It failed github actions with
```
cabal: filepath wildcard 'doc/user-manual.pdf' does not match any files.
```
Is the `v2.6.1` tag not good?

**Comment by asr** [comment]
> I pushed a `release-2.6.1.1` branch on top of `v2.6.1` with a relaxed bound in the `if`.

The version of `Agda.cabal` in `v2.6.1` is the version released. This version cannot be used with our CI (e.g. the test-suite `agda-tests` is not included). You should create the `release-2.6.1.1` branch on the top of the `release-2.6.1` branch.

**Comment by asr** [comment]
> I suggest we make only the minimal changes required for ghc-8.10.2.

Agda 2.6.1 was not released with support for GHC 8.10.1. Agda 2.6.1 compiles with 8.10.1 because it included some commits related to the support of 8.10.1. Off the top on my head, it is necessary to include the files `stack-8.10.1.yaml`, `stack-8.10.2.yaml` (mentioned in `Agda.cabal`) and `.ghci-8.10`.

**Comment by nad** [comment]
Perhaps it makes sense to try to reduce the resources required to compile Agda using GHC 8.10.2.

**Comment by asr** [comment]
A release supporting GHC 8.10.1 and 8.10.2 also should support 8.8.4.

**Comment by UlfNorell** [comment]
Yes, indeed. Does 2.6.1 not build with ghc-8.8.4?

**Comment by asr** [comment]
Agda 2.6.1 builds with GHC 8.8.4 on Ubuntu. I don't know if it builds on macOS or Windows.

**Comment by UlfNorell** [comment]
So no reason to believe there are any problems. I can try `cabal install Agda` with 8.8.4 on MacOS to check.

I don't want to get bogged down in _when-we're-anyway-doing-a-release-we-should-also-fix-such-and-such_ though. Currently you can't install Agda with the latest Haskell platform, and the only reason is that we explicitly wrote in the cabal file that compilation should fail with ghc > 8.10.1. This is especially bad since we're at beginning of term and lots of students are going to try to install Agda for various courses.

**Comment by asr** [comment]
> So no reason to believe there are any problems.

We couldn't test `master` with GHC 8.8.4 on Windows because https://gitlab.haskell.org/ghc/ghc/-/issues/18634. Also from the discussion on https://gitlab.haskell.org/ghc/ghc/-/issues/18550 it seems GHC 8.10.2 is broken on Windows.

**Comment by UlfNorell** [comment]
2.6.1 installs out of the box on Mac OS with ghc-8.8.4.

**Comment by nad** [comment]
> Perhaps it makes sense to try to reduce the resources required to compile Agda using GHC 8.10.2.

See https://github.com/agda/agda/issues/4521#issuecomment-687141175.

**Comment by UlfNorell** [comment]
> Off the top on my head, it is necessary to include the files stack-8.10.1.yaml, stack-8.10.2.yaml (mentioned in Agda.cabal) and .ghci-8.10.

Can I copy these (and `stack-8.8.4.yaml`) from `master`? I'm worried that dependencies have changed since the 2.6.1 release. How do you generate them?

**Comment by asr** [comment]
> Can I copy these (and `stack-8.8.4.yaml`) from `master`?

I don't know.

> I'm worried that dependencies have changed since the 2.6.1 release. How do you generate them?

For each new version of GHC, I start from a file without dependencies, run `stack` multiple times until I fix all the errors.

**Comment by asr** [comment]
If you are planning release first a release candidate you can follow the procedure in [agda-releases-candidates.txt](https://github.com/agda/agda/blob/73405f70bced057d24dd4bf122d53f9548544aba/notes/agda-releases-candidates.txt), if not, you can follow the procedure in [agda-releases.txt](https://github.com/agda/agda/blob/73405f70bced057d24dd4bf122d53f9548544aba/notes/agda-releases.txt). For supporting a new version of GHC you can follow the procedure in [ghc-releases.md](https://github.com/agda/agda/blob/73405f70bced057d24dd4bf122d53f9548544aba/notes/ghc-releases.md).

**Comment by UlfNorell** [comment]
We don't need a release candidate for this, since it only change the condition in the cabal file that prevents compilation with 8.10.2. The instructions say to

> Create stack-X.Y.Z.yaml using as resolver ghc-X.Y.Z.

and I don't know how to do that.

**Comment by asr** [comment]
For GHC 8.10.1 it means:

```
resolver: ghc-8.10.1
compiler: ghc-8.10.1
compiler-check: match-exact
```

**Comment by UlfNorell** [comment]
`stack-8.10.1.yaml` (on `master`) lists a whole bunch of specific libraries. Are you saying I don't need to write down any `extra-deps` and just put the above in the yaml file? In that case why do we have them on master?

**Comment by asr** [comment]
> Are you saying I don't need to write down any `extra-deps` and just put the above in the yaml file?

No. I meant, you start with the above three lines and you added the extra dependencies pointed out by the command `stack` when installing Agda using it.

**Comment by UlfNorell** [comment]
I think I got everything done correctly. The sdist-ball installs cleanly on my machine and on Travis (Travis fails on standard library since I didn't mess with the submodule commit to get something that works with 2.6.1.1 and ghc-8.10). Would appreciate an extra pair of eyes on it before I push to hackage (see https://github.com/agda/agda/releases/tag/v2.6.1.1).

**Comment by asr** [comment]
I'll review it.

**Comment by asr** [comment]
I didn't find any problem so far. I want to test the `.tar` file which will be upload to Hackage. I suggest to upload a candidate to Hackage.

**Comment by UlfNorell** [comment]
How do I do this?

Edit: I mean should I just cabal upload the sdist I made from v2.6.1.1?

**Comment by asr** [comment]
I couldn't see the compilation with 8.8.4 and 8.10.2 in [Travis](https://www.travis-ci.org/github/agda/agda/builds/724913868) due to the missing `doc/user-manual.pdf` (note that the other versions of GHC hadn't this problem).

**Comment by andreasabel** [comment]
If you choose not to release any bug fixes scheduled for 2.6.1.1, you should bump these to a new milestone 2.6.1.2.  (I am fine with only fixing the ghc 8.10.2 compilation problem with 2.6.1.1 and postponing the other problems, if that helps getting the release out.)

**Comment by asr** [comment]
> How do I do this?
> 
> Edit: I mean should I just cabal upload the sdist I made from v2.6.1.1?

In Hackage it is possible to upload a `candidate` or a `final` version. Using a recent version of `cabal-install` by default it is uploaded a `candidate` (in previous versions was the other way around).

Using `cabal-install >= 2.4.0.1` you can upload a candidate version using the following steps 

https://github.com/agda/agda/blob/1d80a3d8161a8c8f40fff194107a85c379f96d99/notes/agda-releases-candidates.txt#L84-L93


https://github.com/agda/agda/blob/1d80a3d8161a8c8f40fff194107a85c379f96d99/notes/agda-releases-candidates.txt#L112-L116

**Comment by UlfNorell** [comment]
I uploaded the sdist. For some reason `cabal haddock --for-hackage` didn't give me a tar ball. I'll see if I can work out what went wrong later.

**Comment by asr** [comment]
The last time I used `cabal-install 2.4.0.1`. I have the idea I had some problems with `cabal-install 3.*` but I didn't remember the details. I was writing this message but you were faster.

**Comment by asr** [comment]
> I uploaded the sdist.

The new `*.yaml` files are missing.

**Comment by UlfNorell** [comment]
Oh, I forgot to add them to the cabal file 😊. Should be fixed now.

**Comment by asr** [comment]
Thanks!

I built without problems the Hackage candidate with GHC 8.8.4 and 8.10.2.

**Comment by UlfNorell** [comment]
Updating to cabal-install-3.2.0.0 made it work. Candidate documentation uploaded.

**Comment by asr** [comment]
The file `Agda.cabal` in tag `v.2.6.1.1` is different to the one in Hackage.

**Comment by UlfNorell** [comment]
Oh, yeah I had to fix a couple of things and I didn't update the tag. Fixed now.

**Comment by asr** [comment]
I haven't more comments.

**Comment by UlfNorell** [comment]
I'll run `cabal upload --publish` then.

**Comment by asr** [comment]
And `cabal upload --publish -d` for the documentation.

**Comment by UlfNorell** [comment]
Done.

**Comment by asr** [comment]
Missing tasks:

https://github.com/agda/agda/blob/076bd40cfe6ba61109ea11596ba3df05c9dcd8d5/notes/agda-releases.txt#L125-L132

https://github.com/agda/agda/blob/076bd40cfe6ba61109ea11596ba3df05c9dcd8d5/notes/agda-releases.txt#L145-L178

**Comment by UlfNorell** [comment]
Fixed everything except readthedocs (I'm not an admin).

**Comment by andreasabel** [comment]
I made you maintainer at readthedocs.org for agda, @UlfNorell, built the v2.6.1.1 and made it default.

**Comment by asr** [comment]
From the release procedure:

https://github.com/agda/agda/blob/076bd40cfe6ba61109ea11596ba3df05c9dcd8d5/notes/agda-releases.txt#L174-L175

@ulf, I think it is a good idea to deprecate 2.6.1 in Hackage.

**Comment by UlfNorell** [comment]
I don't know how to do that.

**Comment by asr** [comment]
Log in as maintainer from the page of Agda in Hackage and follow the `Preferred versions` link.

**Comment by UlfNorell** [comment]
Done.

**Comment by asr** [comment]
From the release procedure:

https://github.com/agda/agda/blob/076bd40cfe6ba61109ea11596ba3df05c9dcd8d5/notes/agda-releases.txt#L140-L141

I couldn't find the file `doc/release-notes/2.6.1.1.md`.

**Comment by asr** [comment]
Also add `doc/release-notes/2.6.1.md` and `doc/release-notes/2.6.1.1.md` to the `extra-source-files` field in `Agda.cabal`.
