### ISSUE TITLE
issue with REWRITE

### ISSUE THREAD

**Issue by lclem** [agda/agda#4912]
I get the following error "drop-map-cons  is not a legal rewrite rule, since the following variables are not bound by the left hand side:  a", while it seems to me that `a` is pretty much bound in the code below:

```agda
{-# OPTIONS  --rewriting --confluence-check #-}

module example where

data _* {ℓ} (A : Set ℓ) : Set ℓ where
    ε : A *
    _∷_ : A → A * → A *

data ℕ : Set where
  zero : ℕ
  suc : ℕ → ℕ

{-# BUILTIN NATURAL ℕ #-}

infix 4 _≡_
data _≡_ {ℓ} {A : Set ℓ} (x : A) : A → Set ℓ where
    refl : x ≡ x

{-# BUILTIN EQUALITY _≡_ #-}
{-# BUILTIN REWRITE _≡_ #-}

map : ∀ {ℓ m} {A : Set ℓ} {B : Set m} → (A → B) → A * → B *
map _ ε = ε
map f (a ∷ as) = f a ∷ map f as

drop : ∀ {ℓ} {A : Set ℓ} → ℕ → A * → A *
drop _ ε = ε
drop zero as = as
drop (suc m) (_ ∷ as) = drop m as

drop-zero : ∀ {ℓ} {A : Set ℓ} (as : A *) → drop zero as ≡ as
drop-zero ε = refl
drop-zero (_ ∷ _) = refl

{-# REWRITE drop-zero #-}
                        
drop-map : ∀ {ℓ m} {A : Set ℓ} {B : Set m} (f : A → B) (n : ℕ) (as : A *) → drop n (map f as) ≡ map f (drop n as)
drop-map f zero as = refl
drop-map f (suc n) (_ ∷ as) = drop-map f n as
drop-map f (suc n) ε = refl

{-# REWRITE drop-map #-}

drop-map-cons : ∀ {ℓ m} {A : Set ℓ} {B : Set m} (f : A → B) (n : ℕ) (as : A *) (a : A) → drop n (f a ∷ map f as) ≡ map f (drop n (a ∷ as))
drop-map-cons _ zero _ _ = refl
drop-map-cons f (suc n) as a = refl

{-# REWRITE drop-map-cons #-}
```
The original motivation to have `drop-map-cons` as a REWRITE is that, by omitting it, there is a local confluence problem, which I also don't know how to address: "Confluence check failed: drop n (map (λ z → f z) (a ∷ as))
reduces to both map f (drop n (a ∷ as)) and
drop n (f a ∷ map (λ z → f z) as) which are not equal because
map f (drop n (a ∷ as)) != drop n (f a ∷ map f as) of type B *
when checking confluence of the rewrite rule drop-map with
example.map-clause2".

Any help would be appreciated!

**Comment by jespercockx** [comment]
The problem is that `a` does not occur in a pattern position in the left-hand side of the rewrite rule. In the rule, the function `f` is an argument, so it could be in particular a constant function, which would leave Agda with no way to determine the value of `a` on the right-hand side of the rewrite rule. Hence the rule is rejected.

To fix the problem, you can maybe try to add a rewrite rule with left-hand side `map f (drop n (a ∷ as))` instead, which should be accepted. But it's also possible that there's no simple way to make the rewrite system confluent, I'm not sure.

**Comment by lclem** [comment]
thanks for the quick reply, I now have a better understanding where the problem with `a` was, so I can avoid it in the future.
I tried with your suggestion and I flipped the equality in `drop-map-cons` as follows:

```agda
drop-map-cons : ∀ {ℓ m} {A : Set ℓ} {B : Set m} (f : A → B) (n : ℕ) (as : A *) (a : A) → map f (drop n (a ∷ as)) ≡ drop n (f a ∷ map f as)
drop-map-cons _ zero _ _ = refl
drop-map-cons f (suc n) as a = refl

{-# REWRITE drop-map-cons #-}
```

but now together with the other code above it has two confluence issues:

1) "Confluence check failed: drop n (map (λ z → f z) (a ∷ as))
reduces to both map f (drop n (a ∷ as)) and
drop n (f a ∷ map (λ z → f z) as) which are not equal because
map f (drop n (a ∷ as)) != drop n (f a ∷ map f as) of type B *
when checking confluence of the rewrite rule drop-map with
example.map-clause2" and

2) "Confluence check failed:
drop n (map (λ z → f z) (drop n₁ (a ∷ as))) reduces to both
map f (drop n (drop n₁ (a ∷ as))) and
drop n (drop n₁ (f a ∷ map (λ z → f z) as))
which are not equal because
map f (drop n (drop n₁ (a ∷ as))) !=
drop n (drop n₁ (f a ∷ map f as)) of type B *
when checking confluence of the rewrite rule drop-map with
drop-map-cons"

My original motivation was to simplify some equational reasoning involving `drop-map`,
since I cannot overcome this technical difficulty, I will just not use REWRITE in this case.

Many thanks for the quick and helpful answer :)
