### ISSUE TITLE
should flat be off by default?

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda#4927]
it is strange to me that flat is on by default. I always think of Agda's type system as something around MLTT but the flat modality itself seems kicking it off the range. I am wondering why flat is on by default? I would expect a special option to turn it on as it is an addon feature.

**Comment by nad** [comment]
We have [discussed](https://github.com/agda/agda/commit/3b4121d35abafe45935b9057d282769b1f537140#commitcomment-34559112) this before. I am not opposed to a flag.

**Comment by Saizan** [comment]
You need special syntax for it, and it doesn't add to the power of the type system unless you postulate things.

**Comment by jespercockx** [comment]
> You need special syntax for it, and it doesn't add to the power of the type system unless you postulate things.

The same is true for `Prop` (at least if you already have irrelevance), yet *somehow* it's still hidden under a flag.

**Comment by Saizan** [comment]
I thought `Prop` was under a flag because of backwards incompatibilities wrt inference?

**Comment by Saizan** [comment]
Irrelevance itself does not need a flag btw, and it's not something you have in plain MLTT.

**Comment by nad** [comment]
I would not mind having a flag for irrelevance as well.

In order to make it easier to fix broken code I suggest that we do not add such flags until #3118 has been implemented.

**Comment by HuStmpHrrr** [comment]
I would say we should have flags for every addon features.

**Comment by jespercockx** [comment]
> In order to make it easier to fix broken code I suggest that we do not add such flags until #3118 has been implemented.

It is now implemented, so go nuts with adding more flags I guess ;)

**Comment by nad** [comment]
I noticed that the type `Cohesion` has *three* constructors:

https://github.com/agda/agda/blob/bd2afa1e98a12efebc674a1fc32b1cec19da65b3/src/full/Agda/Syntax/Common.hs#L1338-L1345

Should the flag for turning off this modality be called `--flat`, `--cohesion`, or something else? If it is called `--cohesion`, then it could perhaps be used also for the sharp modality, which is commented out above, if support for such a modality is added in the future (#5459).

@plt-amy suggested that one could refuse to parse `@flat`/`@♭` unless the flag is on. Given that there are three constructors, does that suffice? There is only syntax for `Flat`:

https://github.com/agda/agda/blob/bd2afa1e98a12efebc674a1fc32b1cec19da65b3/src/full/Agda/Syntax/Concrete/Attribute.hs#L90-L94

The default seems to be `Continuous`:

https://github.com/agda/agda/blob/bd2afa1e98a12efebc674a1fc32b1cec19da65b3/src/full/Agda/Syntax/Common.hs#L1493-L1495
https://github.com/agda/agda/blob/bd2afa1e98a12efebc674a1fc32b1cec19da65b3/src/full/Agda/Syntax/Common.hs#L1501-L1503

Can one guarantee that `Squash` will never interfere with anything just by not parsing `Flat`? Note that `Squash` is part of `zeroModality`:

https://github.com/agda/agda/blob/bd2afa1e98a12efebc674a1fc32b1cec19da65b3/src/full/Agda/Syntax/Common.hs#L1489-L1491

https://github.com/agda/agda/blob/bd2afa1e98a12efebc674a1fc32b1cec19da65b3/src/full/Agda/Syntax/Common.hs#L500-L502

**Comment by nad** [comment]
I added `--cohesion`.

**Comment by plt-amy** [comment]
Well, aiui Squash is just what Continuous becomes when we go into a Flat context, right? Are there any other cases where we apply zeroModality to the context?
