### ISSUE TITLE
Accept using/hidden/renaming qualifiers on module opens in arbitrary orders

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#493]
```
I can never remember which order they should go in, and it seems 
counterintuitive that we'd get a syntax error for writing them in the wrong 
order.
```

Original issue reported on code.google.com by `pumpkingod@gmail.com` on 16 Oct 2011 at 2:03

**Comment by andreasabel** [comment]
Fixed by 49ef966679a4bc4f75beb93e7f88fc49eea3cac6.

The flaw (`mergeImportDirectives` in the parser) in the ointment is that the error is not using the user-formulation of the import directive, but its merged form:
```agda
import Agda.Builtin.Nat using (zero) using (zero)
```
```
Duplicates in `using` directive: zero
when scope checking the declaration
  import Agda.Builtin.Nat using (zero; zero)
```
