### ISSUE TITLE
agda --interaction-json doesn't give bindings for implicit arguments

### ISSUE THREAD

**Issue by msuperdock** [agda/agda#4932]
## Issue

Bindings for implicit arguments often (always?) appear as `{_}` when using `--interaction-json`. The emacs mode shows bindings for implicit arguments, so I assume this is not the case for the ordinary `--interaction` mode. The example below shows that this issue affects various types of implicit arguments, not just set-valued ones.

## Example

```
module Test where

data ⊤
  : Set
  where

  tt
    : ⊤

f
  : {A : Set}
  → {x : ⊤}
  → ⊤
f
  = ?
```

After loading emacs and asking for the context, the JSON response is:

```
{ "kind": "DisplayInfo"
, "info":
  { "kind": "GoalSpecific"
  , "goalInfo":
  { "typeAux":
    { "kind": "GoalOnly"
    }
  , "entries":
  [ { "reifiedName": "A"
    , "inScope": false
    , "originalName": "A"
    , "binding": "{_}"
    }
  , { "reifiedName": "x"
    , "inScope": false
    , "originalName": "x"
    , "binding": "{_}"
    }
  ]
  , "boundary": []
  , "kind": "GoalType"
  , "outputForms": []
  , "rewrite": "Normalised"
  , "type": "⊤"
  }
, "interactionPoint": ...
}
```

When loading the context in emacs, the displayed output is:

```
A : Set    (not in scope)
x : ⊤    (not in scope)
```

The JSON output gives no way of knowing that `A` is a Set and that `x` has type `⊤`.

## Version

I'm running Agda 2.6.1 for the tests above.

**Comment by msuperdock** [comment]
Tagging a few people who are knowledgable about interaction-related code: @ice1000 @banacorn @rwe

**Comment by msuperdock** [comment]
Here are a couple relevant code points, for now:

- [Agda.Interaction.EmacsTop](https://github.com/agda/agda/blob/master/src/full/Agda/Interaction/EmacsTop.hs), lines 395-438. These lines contain the definition of a function `prettyResponseContext`, which the emacs interaction mode uses to pretty-print a context. In particular note line 427.
- [Agda.Interaction.JSONTop](https://github.com/agda/agda/blob/master/src/full/Agda/Interaction/JSONTop.hs), lines 72-78. These lines contain the `EncodeTCM` instance of `ResponseContextEntry`. The printed type is computed as `encodePrettyTCM (respType entry)`. I believe `respType entry` has type `Arg` (or rather `Arg a` for some `a`). This seems to differ from the emacs code, which explicitly unpacks the `Arg` value via pattern matching in `prettyResponseContext` and pretty-prints what's inside.

**Comment by nad** [comment]
I think that we should merge `EmacsTop` and `JSONTop`, so that we do not have to keep the files in sync. I assume that it is not so hard to make Emacs parse the JSON data, using [`json.el`](https://github.com/emacs-mirror/emacs/blob/master/lisp/json.el).

**Comment by msuperdock** [comment]
@nad: I agree, though one challenge to merging the two is that they seem to have different philosophies. The `--interaction` mode seems to prefer to produce fully formatted output, while the `--interaction-json` mode seems to prefer to produce pieces of that output and leave it to the editor plugin to do the formatting.

**Comment by banacorn** [comment]
The very reason why `--interaction-json` was created was to delay the formatting as much as possible.
I think `--interaction` can use whatever data format Emacs sees fit, but the distinction mentioned above should be preserved some how.

**Comment by msuperdock** [comment]
I just created a pull request; see #4939.

Only one line of code is changed; I replaced `encodePrettyTCM (respType entry)` with `prettyATop (unArg (respType entry))`. The `respType entry` term has type `Arg Expr` (that's the abstract syntax `Expr` type). Here are a few thoughts:

- I used `prettyATop` rather than `prettyA` or `encodePrettyTCM` (which for `Expr` is just `prettyA`), since this matches more closely what the emacs mode does. According to the Haddock documentation for `prettyATop`, the difference is that `prettyATop` does not include outermost parentheses.
- An alternative fix would be to adjust the `PrettyTCM` instance for `Arg`, which is what's producing the output `{_}`, but I assume this instance is the way it is for a reason.

I'm on NixOS, and I haven't been able to get Agda to build locally (with or without this fix); using `make quicker-install-bin` I get the error:

```
setup: filepath wildcard 'lib/prim/Agda/Builtin/Bool.agdai' does not match any files.
```

And sure enough, the file `Bool.agdai` is missing. I'm not sure how to fix this issue other than type-checking `Bool.agda` with a working version of Agda, but I assume there is a better way. Does anyone have advice?

(EDIT: I figured out the build issue; see #4151.)

So the fix in my pull request type-checks, but I haven't verified that it fixes the issue. It would be great if someone could check this.

**Comment by nad** [comment]
> The very reason why `--interaction-json` was created was to delay the formatting as much as possible.
> I think `--interaction` can use whatever data format Emacs sees fit, but the distinction mentioned above should be preserved some how.

I think we should aim to make maintenance of Agda easier, and in this case I don't think we should have two modules that do roughly the same thing. One option is to merge the two options, and use the JSON output for all frontends, instead of having two different protocols.

**Comment by msuperdock** [comment]
This can be closed. Pull request #4939 is open due to issues around improving the test suite, but the commit fixing this issue has been cherry-picked onto master:

https://github.com/agda/agda/commit/18b8c6dd776ad41107b9a86b0921e38774cd941d
