### ISSUE TITLE
test/Succeed/ExecAgda makes subsequent tests fail with non-standard agda binary

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#4940]
```
$ touch test/Succeed/ExecAgda.agda 
$ make AGDA_BIN=agda-fast succeed
...
all
  Succeed
    ExecAgda:                                                     Golden value differs from actual value.
AGDA_UNEXPECTED_FAIL

ret > ExitFailure 42
out >  Executable 'agda-fast' not found.
out > ExecAgda.agda:19,5-9
out > Could not find 'agda' in list of trusted executables:
out > when checking that the expression unquote test has type _A_9
                                                                  Accept actual value as new golden value? [yn] n
                                                                  FAIL
                                                                  Golden value does not match actual output.
    Issue1210:                                                    Golden value differs from actual value.
AGDA_UNEXPECTED_FAIL

ret > ExitFailure 42
out >  Executable 'agda-fast' not found.
                                                                  Accept actual value as new golden value? [yn] n
                                                                  FAIL
                                                                  Golden value does not match actual output.
```
All tests after `ExecAgda` fail with the complaint `Executable 'agda-fast' not found.`.

Content of `test/Succeed/ExecAgda.vars`:
```
AGDA_DIR=$PWD/test/Succeed/exec-tc/
```
Content of `test/Succeed/exec-tc/executables` (put there by `make succeed`):
```
agda-fast
```

The faulty behavior would be caused if the `AGDA_DIR` that is set in `ExecAgda.vars` is not reset to its previous value after `ExecAgda` failed.

**Comment by jespercockx** [comment]
@andreasabel was this fixed by your commits?

**Comment by UlfNorell** [comment]
I think the problem is that you don't have the full path in `AGDA_BIN`. When I do
```
$ AGDA_BIN=`which agda-quicker` make succeed
```
It fails for the `ExecAgda` test (since it tries to call `agda`), but all the other tests work.

**Comment by andreasabel** [comment]
So there must be a problem with the test runner; the individual tests are not cleanly separated if some environment change from one test can spill over to the subsequent tests.

**Comment by andreasabel** [comment]
I think I tracked it down to the following lines:
https://github.com/agda/agda/blob/2bab72d99ae3330cbf3a94450a647158838a1d1b/test/Utils.hs#L92
https://github.com/agda/agda/blob/2bab72d99ae3330cbf3a94450a647158838a1d1b/test/Utils.hs#L119

The environment reset mechanism here will reset existing variables to their own value, but _will not delete new variables_.  Since `ExecAgda.vars`, sets `AGDA_DIR`, this setting will remain if there was no previous setting of this variable in the env.  So the default Agda-directory will be replaced to whatever `ExecAgda.vars` set it, for all subsequent test cases.

The message
```
>  Executable 'agda-fast' not found.
```
comes actually from parsing the `executables` file in the `AGDA_DIR`.

**Comment by andreasabel** [comment]
> I think the problem is that you don't have the full path in `AGDA_BIN`. When I do
> 
> ```
> $ AGDA_BIN=`which agda-quicker` make succeed
> ```

I can automate this `which`-trick in the `Makefile`....
