### ISSUE TITLE
Termination checking failed raising a "Problematic calls"

### ISSUE THREAD

**Issue by d-plaindoux** [agda/agda#4941]
Context: **Agda version 2.6.1**

I wrote the following code (taken from the paper **Dependently Typed Programming in Agda**):
```agda
open import Data.Nat using (ℕ; zero; suc)
open import Data.Bool using (Bool; true; false)

infix 30 _=?_

data Type : Set where
    nat  : Type

▲_ : Type → Set
▲ nat  = ℕ

_=?_ : {a : Type} → ▲ a → ▲ a → Bool

_=?_ {nat} zero zero       = true
_=?_ {nat} (suc m) (suc n) = m =? n
_=?_ {nat} _ _             = false
```

The compilation raises an obscure message:
```
Termination checking failed for the following functions:
  _=?_
Problematic calls:
  m =? n
```

I don't see why `=?` is problematic because no clear explanation is given by the compiler.

**Comment by nad** [comment]
Are you using `--without-K` or `--cubical`?

**Comment by d-plaindoux** [comment]
Yes. If I remove `--without-K` the compilation terminates.

**Comment by jespercockx** [comment]
Related issues: https://github.com/agda/agda/issues/1680 https://github.com/agda/agda/issues/4527
