### ISSUE TITLE
short-circuit evaluation on both arguments

### ISSUE THREAD

**Issue by lclem** [agda/agda#4943]
Is there a way to define the function `_∨𝔹_` in such a way that both `lemma1` and `lemma2` have the two one-liner proofs below?
In the current definition, when the first argument is `tt` evaluation does not need to look at the second argument to compute the result, and I would like to achieve the same, simultaneously, for the second argument.

Thanks a lot in advance!

```agda
infix 10 _≡_
data _≡_ {ℓ} {A : Set ℓ} (x : A) : A → Set ℓ where
    refl : x ≡ x

data 𝔹 : Set where
  tt : 𝔹
  ff : 𝔹

_∨𝔹_ : 𝔹 → 𝔹 → 𝔹
tt ∨𝔹 _ = tt
_ ∨𝔹 tt = tt
ff ∨𝔹 ff = ff

lemma1 : ∀ a b → a ≡ tt → a ∨𝔹 b ≡ tt
lemma1 _ _ refl = refl

-- ERROR: a ∨𝔹 tt != tt of type 𝔹
lemma2 : ∀ a b → b ≡ tt → a ∨𝔹 b ≡ tt
lemma2 _ _ refl = refl 
```

**Comment by jespercockx** [comment]
This is not possible in standard Agda, since all definitions by pattern matching are translated to case trees (see https://agda.readthedocs.io/en/v2.6.1.1/language/function-definitions.html#case-trees)

However, you can use rewrite rules to get this effect (see https://agda.readthedocs.io/en/v2.6.1.1/language/rewriting.html):
```agda
{-# OPTIONS --rewriting #-}

open import Agda.Builtin.Equality
open import Agda.Builtin.Equality.Rewrite

data 𝔹 : Set where
  tt : 𝔹
  ff : 𝔹

_∨𝔹_ : 𝔹 → 𝔹 → 𝔹
tt ∨𝔹 _ = tt
_  ∨𝔹 tt = tt
ff ∨𝔹 ff = ff

rew : ∀ a → a ∨𝔹 tt ≡ tt
rew tt = refl
rew ff = refl

{-# REWRITE rew #-}

lemma1 : ∀ a b → a ≡ tt → a ∨𝔹 b ≡ tt
lemma1 _ _ refl = refl

lemma2 : ∀ a b → b ≡ tt → a ∨𝔹 b ≡ tt
lemma2 _ _ refl = refl
```

**Comment by lclem** [comment]
Thank you! I will try by sparingly use this kind of rewriting in the hope it will not break more complicated code :)

**Comment by jespercockx** [comment]
Using the (still experimental) `--confluence-check` flag might help with avoiding bad usage of the `--rewriting` feature.

**Comment by lclem** [comment]
For now it works like a charm. Complete code:

```agda
{-# OPTIONS --confluence-check --rewriting #-}

module Booleans where

infix 10 _≡_
data _≡_ {ℓ} {A : Set ℓ} (x : A) : A → Set ℓ where
    refl : x ≡ x

{-# BUILTIN REWRITE _≡_ #-}

data 𝔹 : Set where
  tt : 𝔹
  ff : 𝔹

_∨𝔹_ : 𝔹 → 𝔹 → 𝔹
tt ∨𝔹 _ = tt
_ ∨𝔹 tt = tt
ff ∨𝔹 ff = ff

∨𝔹-rew : ∀ a → a ∨𝔹 tt ≡ tt
∨𝔹-rew tt = refl
∨𝔹-rew ff = refl

{-# REWRITE ∨𝔹-rew #-}

lemma1 : ∀ a b → a ≡ tt → a ∨𝔹 b ≡ tt
lemma1 _ _ refl = refl

lemma2 : ∀ a b → b ≡ tt → a ∨𝔹 b ≡ tt
lemma2 _ _ refl = refl
```
