### ISSUE TITLE
2.6.1: Refused to invert pattern matching of Data.List.foldl

### ISSUE THREAD

**Issue by mechvel** [agda/agda#4948]
This is on  Agda 2.6.1, ghc-8.8.3, lib-1.4, Ubuntu Linux 18.04.
Bug.agda.zip attached.

  > agda $agdaLibOpt Bug.agda

reports a strange thing for the last line of the attached program:
"
Checking Bug (/home/mechvel/agda/toSave/bugs/sept1-2020/Bug.agda).
/home/mechvel/agda/toSave/bugs/sept1-2020/Bug.agda:60,15-45
Refusing to invert pattern matching of Data.List.foldl because the maximum depth (50) has been reached. Most likely this means you have an unsatisfiable constraint, but it could also mean that you need to increase the maximum depth using the flag
--inversion-max-depth=N  when checking that the inferred type of an application
  All (_≤ n)
  (reverse
   (_x_114 ∷
...
<a very long expression follows>
"

What might all this mean?

[Bug.agda.zip](https://github.com/agda/agda/files/5288554/Bug.agda.zip)

**Comment by UlfNorell** [comment]
Most likely this means you have an unsatisfiable constraint.

**Comment by mechvel** [comment]
I am sorry. The program is wrong.
 
Because  the right hand side  ``xs≤⇒rev-xs≤ n (downFrom-n-≤n n)``  
in the last line has not the needed type. 
Usually Agda reports in such cases something like  "foo has not type Foo". 
But now it reports of "unsatisfiable constraint".
Please, close the issue.
