### ISSUE TITLE
Turn abstract into "a block thing"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#496]
See issue #278 for some context.

I suggest that abstract should work as follows:
- Everything in the textual block started by a given abstract keyword
  belongs to the same abstract block. (Maybe we should call them
  "abstract groups".)
- Abstract blocks defined in the same scope are merged.
- Nested abstract keywords are allowed, but the inner block is merged
  with the outer one.

Original issue reported on code.google.com by `nils.anders.danielsson` on 19 Oct 2011 at 2:08

**Comment by andreasabel** [comment]
@nad I am closing this.  Feel free to reopen if you still have interest to implement this.

**Comment by nad** [comment]
I see no problem with closing this issue, it seems to be out of date. I don't even remember what kind of `abstract` keyword we had when I opened it.

Perhaps you could replace the `abandoned` label with `no longer applicable`, or something like that.

**Comment by UlfNorell** [comment]
We haven't changed the way abstract works since you opened this issue.

**Comment by nad** [comment]
I think the only point of contention is how to handle nesting, and the discussion above does not contain a clear specification of how nesting should be treated. Furthermore we have been discussing and changing this more recently (see, for instance, #2207).

**Comment by andreasabel** [comment]
We also have the label "status: already-fixed" or the new label "status: working-as-intended" in the menu today. ;)
