### ISSUE TITLE
Outdated --without-stdlib and --without-ghc brew install options mentiond in docs

### ISSUE THREAD

**Issue by berndlosert** [agda/agda#4964]
These options were removed a while ago. The documentation (https://agda.readthedocs.io/en/latest/getting-started/installation.html) still mentions them though.

**Comment by berndlosert** [comment]
Also, the  Nix-style Local Builds link is broken.

**Comment by andreasabel** [comment]
Who contributed or maintains the homebrew / nix installers?

**Comment by berndlosert** [comment]
Here's the brew formula for reference: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/agda.rb

**Comment by UlfNorell** [comment]
I don't see those options in the current documentation, so I guess this is fixed.

**Comment by andreasabel** [comment]
Fixed by 4ee9b273f31ab26e1ae4b97445e4487fa863f83b, I suppose.
