### ISSUE TITLE
Crazy bug when defining Ord instances for Int

### ISSUE THREAD

**Issue by berndlosert** [agda/agda#4967]
In the program below, I define an Ord class and create an instance for Int. The check n function basically does 0 < n. When I call check 0 and print it out, I erroneously get True. If I change the Ord instance to the commented out one, the program prints out False (which is correct). The code for both instances is exactly the same though!

I am using Agda 2.6.1 on macOS Mojave.

```agda
 open import Agda.Builtin.Unit public
 open import Agda.Builtin.Bool public
 open import Agda.Builtin.Nat public renaming (_<_ to natLessThan)
 open import Agda.Builtin.Int public
 open import Agda.Builtin.String public
 open import Agda.Builtin.IO public

 record Ord (a : Set) : Set where
   field _<_ : a -> a -> Bool
 open Ord {{...}} public

 intLessThan : Int -> Int -> Bool
 intLessThan = \ where
   (pos m) (pos n) -> natLessThan m n
   (negsuc m) (negsuc n) -> natLessThan n m
   (negsuc _) (pos _) -> true
   (pos _) (negsuc _) -> false

 instance
   --Ord-Int : Ord Int
   --Ord-Int ._<_ = intLessThan

   Ord-Int : Ord Int
   Ord-Int ._<_ = \ where
     (pos m) (pos n) -> natLessThan m n
     (negsuc m) (negsuc n) -> natLessThan n m
     (negsuc _) (pos _) -> true
     (pos _) (negsuc _) -> false

 check : Int -> Bool
 check n = _<_ (pos 0) n

 postulate printBool : Bool -> IO ⊤
 {-# COMPILE GHC printBool = print #-}

 main : IO ⊤
 main = printBool (check (pos 0))

**Comment by nad** [comment]
My guess, based on looking at the generated Haskell code, is that Agda does some partial evaluation, and that there is a bug in the code that does this.

**Comment by andreasabel** [comment]
If I eta-contract `check`, the output of the compiled program is correct:
```agda
check : Int -> Bool
check = _<_ (pos 0)
```

Using `-v treeless:35`, the false optimization can be caught red-handed:
```haskell
-- converted
Issue4967.check =
  λ a →
    (λ b c →
       case b of
         _ | b >= 0 →
           case c of
             _ | c >= 0 → b < c
             _ → Agda.Builtin.Bool.Bool.false
         _ → let d = -1 - b in
             case c of
               _ | c >= 0 → Agda.Builtin.Bool.Bool.true
               _ → let e = -1 - c in e < d)
      (Agda.Builtin.Int.Int.pos 0) a
-- simplification
Issue4967.check =
  λ a →
    let b = Agda.Builtin.Int.Int.pos 0
        c = -1 - b in
    case a of
      _ | a >= 0 → Agda.Builtin.Bool.Bool.true
      _ → let d = -1 - a in d < c
```
The wrong branch is taken.

**Comment by andreasabel** [comment]
Haha, what a fool I have been, to think I could fix this issue.
This is the simplification function:
https://github.com/agda/agda/blob/08191e66e65a4870bf43e21007909fc03150eabf/src/full/Agda/Compiler/Treeless/Simplify.hs#L73-L449
@UlfNorell : If you want someone to help you with maintenance, you need to apply at least the most basic technique of software engineering: documentation.  Not speaking of assertions or unit tests...

**Comment by UlfNorell** [comment]
The problem was that the instance gets inlined and the simplifier can't handle partially builtin-translated code. In this case the pattern matching in the instance implementation had been translated to Haskell integers instead of `pos` and `negsuc` constructors, but the `pos 0` argument in `check` had not. Solution: do builtin-translation as the first step in the pipeline.
