### ISSUE TITLE
Generalisation regression

### ISSUE THREAD

**Issue by nad** [agda/agda#4968]
The following code is accepted by Agda 2.6.1, but a recent development version fails to find the type of the generalisable variable `f` in the last postulate:
```agda
open import Agda.Primitive

variable
  a   : Level
  A B : Set a
  f   : A → B
  x y : A

id : A → A
id x = x

postulate

  _≡_  : {A : Set a} → A → A → Set a
  cong : (f : A → B) → x ≡ y → f x ≡ f y

  _ :
    (f≡id : f ≡ id) →
    cong (λ g → g (f x)) f≡id ≡
    cong (λ g → f (g x)) f≡id
```

**Comment by UlfNorell** [comment]
#4902? Can you check the debug output to see if there are constraints on `f`?

**Comment by nad** [comment]
The debug output includes `setting name of meta _54 to f` and the following pieces of text:
```
waking boxed constraint _73 = g (_f_54 _x_57) : _f.A_51
                          (blocked on _72)
```
```
adding constraint _f_54 (_81 (g = _x_78)) = _f_54 (_f_54 _x_57)
                    : _f.A_51
                    (belongs to problems 50, 53)
```
```
adding constraint _f_54 (_81 (g = _y_79)) = id (_f_54 _x_57)
                    : _f.A_51
                    (belongs to problems 50, 54)
```
```
adding constraint _f_54 (_81 (g = id)) = _f_54 _x_57 : _f.A_51
                    (belongs to problems 50, 54)
```
```
adding constraint _f_54 (_81 (g = _f_54)) = _f_54 (_f_54 _x_57)
                    : _f.A_51
                    (belongs to problems 50, 53)
```
```
adding constraint _f_54 (_81 (g = _f_54)) = _f_54 (_f_54 _x_57)
                    : _f.A_51
                    (belongs to problems 50, 53)
```
```
adding constraint _f_54 (_81 (g = id)) = _f_54 _x_57 : _f.A_51
                    (belongs to problems 50, 54)
```
```
adding constraint _f_54 (_81 (g = id)) = _f_54 _x_57 : _f.A_51
                    (belongs to problems 50, 54)
```
```
adding constraint _f_54 (_81 (g = _f_54)) = _f_54 (_f_54 _x_57)
                    : _f.A_51
                    (belongs to problems 50, 53)
```
```
adding constraint _f_54 (id _x_57) = _f_54 _x_57 : _f.A_51
                    (belongs to problems 50, 54)
```
```
adding constraint _f_54 (id _x_57) = _f_54 _x_57 : _f.A_51
                    (belongs to problems 50, 54)
```
```
adding constraint _82
                    := λ genTel f≡id →
                         cong (λ g → _f_54 (genTel = genTel) (g (_x_57 (genTel = genTel))))
                         f≡id
                    (blocked on problem 50)
```
```
adding constraint _83 = _82
                    : _f_54 (_f_54 _x_57) ≡ id (_f_54 _x_57)
                    (blocked on _82)
```
```
adding constraint _f_54 (id _x_57) = _f_54 _x_57 : _f.A_51
                    (belongs to problems 50, 54)
```
```
adding constraint _f_54 (id _x_57) = _f_54 _x_57 : _f.A_51
                    (belongs to problems 50, 54)
```
```
completed assignment of _54
```
I wonder why some of the messages above are identical. Is this due to backtracking?

**Comment by nad** [comment]
Bisection points to b371b546c6e0cfb3cad11efa7ad14a255d612edc ("[ blocking ] Use MonadBlock to get more precise blocking information out of `runPureConversionM`"). For #4902 bisection pointed to a different commit, also related to blocking.

**Comment by UlfNorell** [comment]
You need to check if these constraints that you found are unsolved at the point of generalization. It would probably help you to actually look at the debug output produced by generalize...

**Comment by nad** [comment]
Can you tell me which flag to use?

**Comment by UlfNorell** [comment]
`-v tc.generalize:50` maybe? Generalization is implemented in `Agda.TypeChecking.Generalize`. You can check the source code for calls to `reportSDoc`.

**Comment by nad** [comment]
There does not seem to be any "awake" constraints remaining:
```
Solving awake constraints. 0 remaining.
generalized
  t = {f : _f.A_85 → _f.A_85} {x : _f.A_85} (f≡id : f ≡ id) →
      cong (λ g → g (f x)) f≡id ≡ cong (λ g → f (g x)) f≡id
```

**Comment by UlfNorell** [comment]
A constraint is awake if we need to try to solve it, so would be very strange if there were still awake constraints. Once we try to solve it and fail it turns into a sleeping constraint.

**Comment by nad** [comment]
OK, is there a simple way to find out if there are any sleeping constraints related to `_54` that are unsolved when generalisation takes place?

**Comment by UlfNorell** [comment]
You could start by looking at the debug output from generalization...

**Comment by nad** [comment]
I added `debugConstraints` to `Agda.TypeChecking.Generalize.generalizeType'`:
```
waking up         []
  still sleeping: []
Solving awake constraints. 0 remaining.
generalized
  t = {f : _f.A_85 → _f.A_85} {x : _f.A_85} (f≡id : f ≡ id) →
      cong (λ g → g (f x)) f≡id ≡ cong (λ g → f (g x)) f≡id
```

**Comment by UlfNorell** [comment]
You could try looking at the debug output from generalization to find out why it's not getting generalized over despite being unconstrained.

**Comment by nad** [comment]
```
computing generalization for type _49
  constrainedMetas     =  _f.A.a_50, _f.A_51, _f_54, _x_57, _A_65,
                          _82, _83
  generalizable        =  _f.B.a_52, _f.B_53, _f_54, _x.A.a_55,
                          _x.A_56, _x_57
  generalizableOpen    =  _f_54, _x_57
  openSortMetas        = 
  alsoGeneralize       = 
  reallyDontGeneralize =  _f.A.a_50, _f.A_51, _82, _83
we're generalizing over _f_54, _x_57
created genRec B..generalizedField-f, B..generalizedField-x
created genRecordType
  genRecName   =  B.GeneralizeTel
  genRecCon    =  B.mkGeneralizeTel
  genRecFields =  f, x
solving generalized meta _f_54 := f
solving generalized meta _x_57 := x
genTel = {f
          : _f.A_51
            (genTel =
             (record { .generalizedField-f = _ ; .generalizedField-x = _ })) →
            _f.A_51
            (genTel =
             (record { .generalizedField-f = _ ; .generalizedField-x = _ }))}
         {x
          : _f.A_51
            (genTel =
             (record { .generalizedField-f = _ ; .generalizedField-x = _ }))}
```
```
assignTerm _f.A_51  :=  _f.A_85
```
Should `_f.A_51` be in the set with the label `reallyDontGeneralize`?

**Comment by UlfNorell** [comment]
Generalization claims it's constrained at the time of generalization. Are you saying that it's solved before that?

**Comment by nad** [comment]
The two blocks of debug output above are ordered as in Agda's output.

**Comment by UlfNorell** [comment]
Then, yes. Unsolved constrained metavariables should not be generalized over. Why were you expecting it to be generalized?

**Comment by nad** [comment]
The meta-variable `_f.A_85` is in the final term, and if the idea is that generalisation should work for the program in the OP, then there should not be a meta-variable in the final term. The meta-variable `_f.A_85` is in the term because `_f.A_51` is instantiated to `_f.A_85`. I wonder why Agda does not generalise over `_f.A_85`. Does generalisation happen too early?

**Comment by UlfNorell** [comment]
I see no indication that there are any bugs here. `_85` isn't generalized over because it doesn't exist when doing the generalization. `_51` is not generalized since it's constrained, which means that is can be instantiated to `_83` after generalization. Once generalization is finalized more things can be solved since some metas have turned into variables.

**Comment by nad** [comment]
The code was accepted until about two weeks ago (b371b546c6e0cfb3cad11efa7ad14a255d612edc). Was the old behaviour buggy? Or should we expect that the outcome of generalisation changes now and then? I don't think that is very nice.

**Comment by UlfNorell** [comment]
Clearly we are not in a situation where the constraint solver is completely stable and it does happen that you get unsolved metas in situations where you didn't previously. In that case the outcome of generalization will inevitably change, as does the outcome of most other activities in the type checker. This is indeed not very nice, but hardly something you can blame generalization for.

**Comment by nad** [comment]
I've mostly stopped reporting regressions related to unification. I guess I'll do the same for generalisation.
