### ISSUE TITLE
`variable` use adds explicit argument

### ISSUE THREAD

**Issue by dolio** [agda/agda#4970]
Consider the following code:

```agda
open import Data.Product
open import Data.Nat.Base

NEX : Set₁
NEX = Σ[ A ∈ Set ] (ℕ → A)

variable
  A : NEX
  B : A .proj₁ → NEX

[Σ] : (A : NEX) → (B : A .proj₁ → NEX) → NEX
[Σ] A B .proj₁ = Σ[ x ∈ A .proj₁ ] B x .proj₁
[Σ] A B .proj₂ n = A .proj₂ n , B _ .proj₂ n

_[→]_ : (A B : NEX) → NEX
(A [→] B) .proj₁ = A .proj₁ → B .proj₁
(A [→] B) .proj₂ n x = B .proj₂ n

[π₁] : ([Σ] A B [→] A) .proj₁
[π₁] snd x = {!!}

[pi₁] : ∀{A B} → ([Σ] A B [→] A) .proj₁
[pi₁] x = {!!}
```

It was pointed out to me that `[π₁]` is ambiguous, because `A .proj₁ = A' .proj₁` does not lead to `A = A'`. However, for some reason, this leads Agda to decide that `[π₁]` should have an extra _explicit_ argument than in the declared type. This seems like unintended behavior.

I'm on pretty much the latest Agda from git as of the posting of this issue.

**Comment by UlfNorell** [comment]
The ambiguity is what's causing the extra `snd` argument, but as you say, it should be implicit not explicit.

**Comment by dolio** [comment]
I didn't mention it, but the type of the extra argument is pretty odd. It's `ℕ → A .proj₁`, but there are no variable declarations of that type in scope. In fact, the whole type specified by Agda is odd given the ambiguity:

    {A = x₁ : NEX} {B = B₁ : x₁ .proj₁ → NEX}
    (snd : ℕ → x₁ .proj₁) →
    Σ-syntax (x₁ .proj₁) (λ x₂ → B₁ x₂ .proj₁) → x₁ .proj₁

So, it isn't quantifying over two whole `NEX` values due to the ambiguity, it's just quantifying an extra second part. I think it's using eta equality to simplify the needed quantifiers.

**Comment by UlfNorell** [comment]
The way it works is that if a meta you wanted to generalize over is solved with a term containing other metas we generalize over those instead. So in this case `B.A` is solved with `A .proj₁ , _snd` for a fresh meta `_snd : ℕ → A .proj₁`.
