### ISSUE TITLE
No executable generated when compiling hello-world

### ISSUE THREAD

**Issue by vitvakatu** [agda/agda#4979]
Hello

I installed Agda 2.6.1.1 on Arch Linux and tried to compile simple hello world program (straight out from official docs)

```
module hello-world where

open import IO

main = run (putStrLn "Hello, world!")
```

The problem is, if I run `agda --compile hello-world.agda`, I only got `hello-world.agdai` + `MAlonzo` directory, no executable file is actually generated.

**Comment by gallais** [comment]
Can you run `agda --compile hello-world.agda > log` and share the content of
the `log` file with us?

**Comment by vitvakatu** [comment]
Well, I deleted all files except for source code, run your command and guess what? It actually worked and created a working executable. Not sure what changed since I tried last time (some environment variable update after I logged out/in ?)

Anyway, the issue solved, thank you
