### ISSUE TITLE
Multiple λ's lose types when unquoting

### ISSUE THREAD

**Issue by alhassy** [agda/agda#4997]
Agda's `Term` type models untyped lambda terms,  as such when we want to splice in a type and provide a value of it, things are okay when there is one spliced lambda, but when there  are two, things seem to fail with an error.

Any help would be appreciated!

Here is a minimal example.
```agda
     open import Relation.Binary.PropositionalEquality
     open import Data.List
     open import Reflection
     open import Data.Bool renaming (Bool to 𝔹)
     
     works : let τ = quoteTerm (λ (A : Set) → A)
             in unquote (λ goal → unify goal τ) 𝔹
     works = true

     -- If I recall correctly, this worked in Agda 2.6.0.1     
     crashes : let τ = quoteTerm (λ (A : Set) (a : A) → A)
               in unquote (λ goal → unify goal τ) 𝔹 true
     crashes = true
```
During quotation, types are lost,
`quoteTerm (λ (A : Set) (a : A) → A) ≡ lam visible (abs "A" (lam visible (abs "a" (var 1 []))))`,
and so we can do silly stuff like this:
```agda
     wat! : let τ = quoteTerm (λ (A : Set) (a : A) → A)
            in unquote (λ gl → unify gl τ) ≡ (λ (A : Set₆₆₆) (a : A) → A)
     wat! = refl
```
Perhaps this has something to do with it?

The full error is as follows.

     Sort _26  [ at /Users/musa/thesis-proposal/Context.agda:11,14-52 ]
     _27 : _26  [ at /Users/musa/thesis-proposal/Context.agda:11,14-52 ]
     
     ———— Errors ————————————————————————————————————————————————
     Failed to solve the following constraints:
       Set = _26 (x = 𝔹)
       𝔹 =< _27 (x = 𝔹)

**Comment by UlfNorell** [comment]
Indeed the reflected syntax is untyped so the type annotations on the lambdas are lost when quoting. Without knowing what it is you are trying to do it's hard to say what an appropriate work-around is, but the following checks without problems:
```agda
macro
  tac : Term → TC ⊤
  tac goal = do
    checkType goal (quoteTerm ((A : Set) → A → Set))
    unify goal (quoteTerm (λ (A : Set) (a : A) → A))

works₂ : tac 𝔹 true
works₂ = true
```
Here we nail down the type of the goal explicitly since the call do unify doesn't provide enough information.

**Comment by alhassy** [comment]
I'm working with types `∀ ℓ → ℕ → Set ℓ`, such as `X` below.
My macro Π→λ turns types-of-functions into functions-on-types,
and it worked in 2.6.0.1, but I'm having little success atm.

I've tried to add homemade typing annotations, including calling `checkType` at various places, but have had no success.
Any help would be appreciated.

```agda
    open import Relation.Binary.PropositionalEquality
    open import Data.Nat
    open import Data.Product
    open import Data.Unit
    open import Reflection
    open import Data.Bool renaming (Bool to 𝔹)
    
    --------------------------------------------------------------------------------
    {-  Π→λ “∀ (a : A) → B a”  =  “λ (a : A) → B a”  -}
    
    Π→λ-helper : Term → TC Term
    Π→λ-helper (pi  a b)         = return (lam visible b)
    -- Π→λ-helper (pi  a b)         = checkType (lam visible b) (pi a b)
    Π→λ-helper (lam a (abs x y)) = do τ ← Π→λ-helper y; return (lam a (abs x τ))
    {-# CATCHALL #-}
    Π→λ-helper x = return x
    
    macro
      Π→λ : Term → Term → TC ⊤
      Π→λ tm goal =  do tm′ ← normalise tm
                        tm″ ← Π→λ-helper tm′
                        unify goal tm″
    
    --------------------------------------------------------------------------------
    {- Example -}
    X : ℕ → Set₁
    X 0 = Σ Set λ A → Σ A λ a → Σ Set λ B → B
    X 1 = (A : Set) → Σ A λ a → Σ Set λ B → B
    X 2 = (A : Set) → (a : A) → Σ Set λ B → B
    X _ = (A : Set) → (a : A) → (B : Set) → B
    
    works : Π→λ (Π→λ (X 2) 𝔹) false
    works = ℕ , 7
    
    crashes₁ : ∀ (A : Set) → A → Set₁
    crashes₁ = Π→λ (Π→λ (X 2))
    
    crashes₂ : (Π→λ (Π→λ (X 2))) 𝔹 true
    crashes₂ = ℕ , 7
```

I have also tried to do as your `tac`: To get the type parameters that become lambda arguments but I've had trouble there as well.

```agda
    getΠs : Term → TC Term
    getΠs (pi a (abs s b)) = do p ← getΠs b; return (pi a (abs s p))
    getΠs (lam a (abs s b)) = do p ← getΠs b; return (lam a (abs s p))
    getΠs x = inferType x
    
    macro
      getΠs′ : Term → Term → TC ⊤
      getΠs′ t g = do t′ ← getΠs t; unify g t′
    
    -- fails : getΠs′ (∀ (A : Set) (a : A) → A) ≡ ((A : Set) (a : A) → Set)
    -- fails = refl
```
    
Thanks for looking into this Ulf ^_^

**Comment by UlfNorell** [comment]
Is it important that it only does one pi at a time, and that you can nest them? Making sense of `Π→λ (Π→λ (X 2))` makes my head hurt. If not this works:
```agda
Π→λ-type : Term → Term
Π→λ-type (pi a (abs x b)) = pi a  (abs x (Π→λ-type b))
Π→λ-type x = unknown

Π→λ-helper : Term → Term
Π→λ-helper (pi a (abs x b)) = lam visible (abs x (Π→λ-helper b))
Π→λ-helper x = x

macro
  Π→λ : Term → Term → TC ⊤
  Π→λ tm goal =  do tm′ ← normalise tm
                    checkType goal (Π→λ-type tm′)
                    unify goal (Π→λ-helper tm′)

--------------------------------------------------------------------------------
{- Example -}
X : ℕ → Set₁
X 0 = Σ Set λ A → Σ A λ a → Σ Set λ B → B
X 1 = (A : Set) → Σ A λ a → Σ Set λ B → B
X 2 = (A : Set) → (a : A) → Σ Set λ B → B
X _ = (A : Set) → (a : A) → (B : Set) → B

works : Π→λ (X 2) 𝔹 false
works = ℕ , 7

works₁ : ∀ (A : Set) → A → Set₁
works₁ = Π→λ (X 2)

works₂ : Π→λ (X 2) 𝔹 true
works₂ = ℕ , 7
```

**Comment by alhassy** [comment]
You're the best Ulf!! (•̀ᴗ•́)و

The nesting was in the way and I don't use it at all, your fix is brilliant! Thanks so much man!!

( I plan to read your reflection code in your github repo and hopefully I can learn from that, do you recommend anything else to read to learn more about reflection in Agda? )
