### ISSUE TITLE
`primStringFromList` is not injective because of surrogate code points

### ISSUE THREAD

**Issue by gullcomb** [agda/agda#4999]
Out of curiosity (I am not even a regular Agda user), I have just spent some time exploring the built-in text support of Agda by reading the documentation and source and I think I have found a subtle inconsistency there.

If I am following correctly, Agda's `Char` type is backed by Haskell's `Char` type, which represents a [Unicode code point](https://www.unicode.org/glossary/#code_point) i.e. an integer in the range 0 to `0x10ffff` inclusive. All these values can be constructed using `primNatToChar`.

However, Agda's `String` type uses Haskell's `Text` type from the `text` package and, according to [the documentation](https://hackage.haskell.org/package/text-1.2.4.0/docs/Data-Text.html#g:2), that type can only represent sequences of [Unicode scalar values](https://www.unicode.org/glossary/#unicode_scalar_value), which exclude the [surrogate code points](https://www.unicode.org/glossary/#surrogate_code_point) (range `0xd800` to `0xdfff` inclusive). To deal with this discrepancy the conversion functions of the package, including [`Data.Text.pack`](https://hackage.haskell.org/package/text-1.2.4.0/docs/Data-Text.html#v:pack) which underlies Agda's `primStringFromList` primitive, map the surrogate code points to the replacement character (U+FFFD, �).

Not having access to an Agda-enabled editor (an online playground would be very nice), I can't show an actual proof of false using the above reasoning but I believe it is possible to write one.

My preferred fix would be to follow [Rust's tracks](https://doc.rust-lang.org/1.47.0/std/primitive.char.html) and remove the surrogate code points from the allowed values of the `Char` type, restricting it to Unicode scalar values only instead of all the Unicode code points. I think that can be achieved just by restricting the range of `primNatToChar` (but _**beware** of character and string literals_). The obvious fix would be to change its type to `Nat → Maybe Char` (and get rid of the reduction modulo `0x110000` in passing) but that equally obviously breaks backward compatibility. For now, I propose to mimic what the `text` package does and map the range `0xd800` to `0xdfff` inclusive to the replacement character U+FFFD.

**Comment by gallais** [comment]
> Not having access to an Agda-enabled editor (an online playground
  would be very nice), I can't show an actual proof of false using
  the above reasoning but I believe it is possible to write one.

Could you expand on the proof you have in mind? This is what I got
but the last hole cannot be filled because the types don't match up
(precisely because taking the head of the returned lists yields
'�' on both sides):

```agda
module Oops where

open import Agda.Builtin.Char
open import Agda.Builtin.List
open import Agda.Builtin.Equality
open import Agda.Builtin.String

cong : ∀ {A B : Set} (f : A → B) {x y} → x ≡ y → f x ≡ f y
cong f refl = refl

oops : "\xD800" ≡ "\xD801"
oops = refl

∷⁻¹ : ∀ {A : Set} {x y : A} {xs ys} →
      x ∷ xs ≡ y ∷ ys → x ≡ y
∷⁻¹ refl = refl

argh : '\xD800' ≡ '\xD801'
argh = ∷⁻¹ {!cong primStringToList oops!}
```

**Comment by UlfNorell** [comment]
You need to use the (fake) primitive proof that `primStringFromList` is injective:
```agda
open import Agda.Builtin.Char
open import Agda.Builtin.List
open import Agda.Builtin.Equality
open import Agda.Builtin.String
open import Agda.Builtin.String.Properties

data ⊥ : Set where

yeah : '\xD800' ≡ '\xD801' → ⊥
yeah ()

argh : '\xD800' ∷ [] ≡ '\xD801' ∷ []
argh = primStringFromListInjective _ _ refl

∷⁻¹ : ∀ {A : Set} {x y : A} {xs ys} → x ∷ xs ≡ y ∷ ys → x ≡ y
∷⁻¹ refl = refl

boom : ⊥
boom = yeah (∷⁻¹ argh)
```

**Comment by gallais** [comment]
Wait. Does this primitive exist? I can only find [`primStringToListInjective`](http://agda.github.io/agda-stdlib/Agda.Builtin.String.Properties.html#223)!

Edit: oh, it's a recent addition that has landed in [`experimental`](http://agda.github.io/agda-stdlib/experimental/Agda.Builtin.String.Properties.html) :(

**Comment by UlfNorell** [comment]
Added in #4790, which you merged 😄

**Comment by nad** [comment]
> My preferred fix would be to follow [Rust's tracks](https://doc.rust-lang.org/1.47.0/std/primitive.char.html) and remove the surrogate code points from the allowed values of the `Char` type, restricting it to Unicode scalar values only instead of all the Unicode code points. I think that can be achieved just by restricting the range of `primNatToChar` (but _**beware** of character and string literals_). The obvious fix would be to change its type to `Nat → Maybe Char` (and get rid of the reduction modulo `0x110000` in passing) but that equally obviously breaks backward compatibility.

I don't think we need to worry too much about backward compatibility for surrogate code points.
