### ISSUE TITLE
Allow creation of implicit parameters in with blocks

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#500]
It'd be nice if we could write something like
```
f <stuff> with {some expression I need to add that will just be a dot pattern when I match on another parameter}
f <stuff> = ...
```
so the with block would bring something into a pattern scope but not force us to include it in our pattern matches.

Original issue reported on code.google.com by `pumpkingod@gmail.com` on 27 Oct 2011 at 4:12

**Comment by andreasabel** [comment]
The given use case is covered by the `rewrite` keyword.  Please provide a new use case.
This issue is related to #858.

**Comment by UlfNorell** [comment]
```agda
open import Agda.Builtin.Nat

data Vec (A : Set) : Nat → Set where
  []  : Vec A 0
  _∷_ : ∀ {n} → A → Vec A n → Vec A (suc n)

infixr 5 _∷_ _++_

_++_ : ∀ {A m n} → Vec A m → Vec A n → Vec A (m + n)
[]       ++ ys = ys
(x ∷ xs) ++ ys = x ∷ xs ++ ys

T : ∀ {A n} → Vec A n → Set
T [] = Nat
T (x ∷ xs) = Vec Nat 0

foo : ∀ {A} m n (xs : Vec A m) (ys : Vec A n) → T (xs ++ ys)
foo m n xs ys with m + n | xs ++ ys
... | _ | []     = 0
... | _ | z ∷ zs = []
```
Abstracting over the length is required to allow pattern matching on `xs ++ ys`, but is otherwise not interesting.
