### ISSUE TITLE
Bad JavaScript generated

### ISSUE THREAD

**Issue by GregoryMorse** [agda/agda#5002]
Latest Version 2.6.1.1 with Agda Standard Library 1.4

jAgda.Function.Metric.Nat.Structures.js:
```
exports["IsMetric"] = {};
exports["IsMetric"]["_NameId 46 18364208626971903049"] = {};
...
exports["IsUltraMetric"] = {};
exports["IsUltraMetric"]["_NameId 130 18364208626971903049"] = {};
...
exports["IsMetric"] = agdaRTS.primIntegerFromString("0");
exports["IsMetric"]["_NameId 46 18364208626971903049"]["antisym"] = agdaRTS.primIntegerFromString("0");
...
exports["IsUltraMetric"] = agdaRTS.primIntegerFromString("0");
exports["IsUltraMetric"]["_NameId 130 18364208626971903049"]["antisym"] = agdaRTS.primIntegerFromString("0");
```
Yields:
```
jAgda.Function.Metric.Nat.Structures.js:296 Uncaught TypeError: Cannot set property 'antisym' of undefined
    at jAgda.Function.Metric.Nat.Structures.js:296
```

Relevant code: https://github.com/agda/agda-stdlib/blob/master/src/Function/Metric/Nat/Structures.agda
```
------------------------------------------------------------------------
-- Metrics

IsMetric : Rel A ℓ → DistanceFunction A → Set _
IsMetric _≈_ = Base.IsGeneralMetric _≈_ _≡_ _≤_ 0 _+_

module IsMetric {_≈_ : Rel A ℓ} {d : DistanceFunction A}
                (M : IsMetric _≈_ d) where
  open Base.IsGeneralMetric M public

------------------------------------------------------------------------
-- Ultra-metrics

IsUltraMetric : Rel A ℓ → DistanceFunction A → Set _
IsUltraMetric _≈_ = Base.IsGeneralMetric _≈_ _≡_ _≤_ 0 _⊔_

module IsUltraMetric {_≈_ : Rel A ℓ} {d : DistanceFunction A}
                     (UM : IsUltraMetric _≈_ d) where
  open Base.IsGeneralMetric UM public
```

This bug should be fixed, as after more testing, a large amount of modules in the library seem to be perfectly valid javascript code and this is the only real bug though its repeated in one other place.

**Comment by andreasabel** [comment]
#4962 complains about problems of the JS backend as well.  This one seems due to some printing has gone wrong: `NameId 46 18364208626971903049`.

**Comment by GregoryMorse** [comment]
Yes looking at that issue they could very well be the same issue.

Removing or commenting out : `exports["IsMetric"] = agdaRTS.primIntegerFromString("0");` and `exports["IsUltraMetric"] = agdaRTS.primIntegerFromString("0");` seems to fix things.  I do not know the details but the long string though does not seem to be the problem as much as its overwriting the whole function dictionary it previously created with an integer.

**Comment by GregoryMorse** [comment]
Another bug this time in jAgda.Relation.Nullary.Decidable.Core.js:
```
exports["map′"] = function (x0) {
    return function (x1) {
      return function (x2) {
        return function (x3) {
          return function (x4) {
            return function (x5) {
              return function (x6) {
                return z_jAgda_Relation_Nullary["_because_"](z_jAgda_Relation_Nullary["Dec"]["does"](x6))(x6["_because_"]({
                  "_because_": function (x7, x8) {
                    return (function (x,v) { return ((x)? v["true"]() : v["false"]()); })(x7, {
                      "false": function () {
                        return z_jAgda_Relation_Nullary["Reflects"]["ofⁿ"](agdaRTS.primIntegerFromString("0"));
                      },
                      "true": function () {
                        return z_jAgda_Relation_Nullary["Reflects"]["ofʸ"](x4(z_jAgda_Relation_Nullary_Reflects["invert"](agdaRTS.primIntegerFromString("0"))(agdaRTS.primIntegerFromString("0"))(agdaRTS.primIntegerFromString("0"))(x8)));
                      }
                    });
                  }
                }));
              };
            };
          };
        };
      };
    };
  };
```

The `x4(...)` call is obviously not going to work.  e.g. in jAgda.Data.Nat.Properties.js:

```
exports["_≟_"] = function (x0) {
    return function (x1) {
      return z_jAgda_Relation_Nullary_Decidable_Core["map′"](agdaRTS.primIntegerFromString("0"))(agdaRTS.primIntegerFromString("0"))(agdaRTS.primIntegerFromString("0"))(agdaRTS.primIntegerFromString("0"))(agdaRTS.primIntegerFromString("0"))(agdaRTS.primIntegerFromString("0"))(z_jAgda_Data_Bool_Properties["T?"]((agdaRTS.uprimIntegerEqual)(x0, x1)));
    };
  };
```

Obviously a biginteger class instance will not be callable as a function.  Just removing the wrong and unnecessary x4 call fixes it.  The JavaScript library is looking difficult at this point to do interesting practical things with it.

I noticed that jAgda.Agda.Builtin.Char.js has all undefined functions for even simple things e.g.: `exports["primCharToNat"] = undefined;` should be something like `function(x) { return biginteger.BigInteger(x.charCodeAt(0)); };`

**Comment by andreasabel** [comment]
Unfortunately, we do not have a maintainer for the JS backend at the moment.

I wonder what the point is in emitting statements like
```
exports["IsMetric"] = agdaRTS.primIntegerFromString("0");
```
in the first place.  Doesn't JS have all sorts of default values so you need not initialize everything?  Maybe I am just displaying my factual ignorance of JS here...

**Comment by GregoryMorse** [comment]
It was correctly initialized here `exports["IsMetric"] = {};` as a dictionary object to contain a bag or methods.  Then the dictionary is just overridden by a biginteger value for no apparent reason.

The "map′" function having a spurious x4 in it is also a sure bug.  I got a reasonable sized project working though in browser client-side non-node-JS javascript having to write some special async loading functions, custom dependency sorting, and filling in undefined functions having to do with builtins.  Everything works perfectly at long last and I learned some interesting details.

So I hope someone with expertise in the JS is able to address these two bug reports as this is not thorough testing but at least hundreds of agda stdlib modules are loading and initializing successfully.

**Comment by andreasabel** [comment]
These initializations to `Exp`ression `Integer 0` printed by https://github.com/agda/agda/blob/7b4209a050d5a73828df991c257625f119a5fef8/src/full/Agda/Compiler/JS/Pretty.hs#L222
likely come from https://github.com/agda/agda/blob/7b4209a050d5a73828df991c257625f119a5fef8/src/full/Agda/Compiler/JS/Pretty.hs#L248-L262 . The only place where `Module`s are created seems to be https://github.com/agda/agda/blob/7b4209a050d5a73828df991c257625f119a5fef8/src/full/Agda/Compiler/JS/Compiler.hs#L154-L161 so one should try to find out how these initializations to 0 enter there.

**Comment by andreasabel** [comment]
Er, I tried compilation with latest Agda (2.6.2 development version).  The JS output is now:
```
exports["IsMetric"] = {};
exports["IsMetric"]["_NameId 46 18364208626971903049"] = {};
...
exports["IsMetric"] = null;
exports["IsMetric"]["_NameId 46 18364208626971903049"]["antisym"] = null;
```
Still no better, but using `null` instead of `0` now.  No wonder I was on a wild goose chase...

It is easier to search for `Null` and this is quite often produced, e.g. whenever something is erased or a type.  We can simply filter out exports of the form `= null` I suppose.

**Comment by andreasabel** [comment]
The current JS compilation testsuite has the problem that it just runs the main module in `node`.  Not all compiled files are run eagerly through `node` to spot compiler errors like the OP.  Maybe Agda should, when creating the `.js` files, already run them through `node` (but not execute the main function, of course).  This could slow compilation a bit.  Files that do not pass `node` should trigger only a warning, I suppose to allow workarounds (ideally, with a superduper maintained JS backend, an error).

**Comment by andreasabel** [comment]
I close this one, continuation at #4962 which is hitting the same problems.
