### ISSUE TITLE
One can override --safe

### ISSUE THREAD

**Issue by nad** [agda/agda#5029]
Agda accepts the following code:
```agda
{-# OPTIONS --safe -WnoSafeFlagNoCoverageCheck #-}

open import Agda.Builtin.Bool
open import Agda.Builtin.Equality

data ⊥ : Set where

{-# NON_COVERING #-}

f : ∀ b → b ≡ true → ⊥
f false ()

bad : ⊥
bad = f true refl
```
I guess one way to fix this would be to raise an error if an attempt is made to turn off a non-benign warning when `--safe` is used.

**Comment by andreasabel** [comment]
Shouldn't `{-# NON-COVERING #-}` be an error always with `--safe`?  Why is there a warning? @gallais @fredrikNordvallForsberg ?

Proposed solution: `{-# OPTIONS --safe -WnoSafeFlagNoCoverageCheck #-}` shouldn't be a valid combination of options.

**Comment by gallais** [comment]
Looks like it's missing from the `errorWarnings` list.

**Comment by fredrikNordvallForsberg** [comment]
In general one shouldn't be allowed to turn off non-benign warnings when `--safe` is on, surely?

```agda
{-# OPTIONS --safe -W noTerminationIssue #-}

data ⊥ : Set where

bad : ⊥
bad = bad
```

**Comment by gallais** [comment]
```haskell
   Just str' -> (over warningSet . Set.delete) <$> string2WarningName str'
```

should check that the warning does not belong to `errorWarnings`.
I have a meeting right now but I can look at it afterwards.

**Comment by andreasabel** [comment]
Thanks for fixing @gallais !
I have a improvement request for the new error, see https://github.com/agda/agda/pull/5172#discussion_r571876965.
