### ISSUE TITLE
Should --no-qualified-instances be the default?

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#5030]
In https://github.com/agda/agda/pull/4522, I added a new flag `--no-qualified-instances` that restricts the scope of instance search to instances that are in scope under an unqualified name only (see the original issue for the motivation). @ajrouvoet has previously reported his positive experience with using this flag. If anyone else has an opinion on whether this should be the default behaviour, please say so!

Some arguments in favour of making this the default:

@ajrouvoet :
> Before this flag, the only way to control instance search is by splitting of instances into separate files. If you want to be able to use a definition without it also being available to instance search, you need two definitions. That is quite frustrating.

@UlfNorell :
> Using a library designed assuming the flag is on would be completely unusable without the flag if it provides multiple conflicting instances. The other way around is less problematic, so making the new behaviour the default is maybe not a bad idea.

@jespercockx :
> I don't think the problem is so much that the current behaviour is confusing, but rather that it is very awkward to make sure an instance is not in scope. Basically, it completely negates the usual module structure and forces you to use separate files to hide instances.

Some arguments against enabling this flag by default:

@UlfNorell :
> Putting performance considerations aside, I think the most natural design is to consider qualified instances (the current behaviour without the flag). The user can refer to qualified names, so why shouldn't instance search? 

@jespercockx :
> The main argument in favour of allowing qualified instances is that it allows you to write things like open import Data.List using (List; []; _∷_) and this also gives you access to the relevant instances for Functor, Applicative, Monad, ...

@UlfNorell :
> It's quite common that you use modules qualified to avoid polluting the namespace. 
It would be annoying if you were forced to make all instances available in the 
top-level scope for them to be used.

**Comment by UlfNorell** [comment]
I have no strong preferences in either direction, but coming from Haskell I find having more than one instance available for a type a little bit scary, and not turning on the flag by default would make this case more pleasant to work with.

However, I'm open to the possibility that working with conflicting instances and `--no-qualified-instances` actually works well in practice, in which case making it the default would be a good choice. What are people's (@ajrouvoet?) experience with using the flag?

**Comment by ajrouvoet** [comment]
RE the two last arguments against (about opening modules with explicit import lists and using qualified modules): In Haskell you write `import M ()` to only import instances from a module. The jump to some special syntax like `import M (instances)` in Agda seems not that large.

**Comment by ajrouvoet** [comment]
@UlfNorell Yeah, I understand the hesitation. At the same time it feels like Scala and Agda have demonstrated that there are many useful applications of instance search that go beyond that which is covered by Haskell. What was originally "poor man's type classes" has developed into an interesting design choice. I believe that many of those violate the Haskell restrictions.

I think that the [application](https://github.com/ajrouvoet/ternary.agda) that I have for multiple conflicting instances is *not* a hack, and does not fall in the category of abusing instances for proof search. Designing the library was impossibly frustrating before the flag and became a breeze with it. The usual caveats of good design using implicits still apply (and are not entirely figured out) but were certainly not more pronounced.

**Comment by ajrouvoet** [comment]
Ah, another reason for this: I think recently there was some rollback of Agda trying to take 'same instance' into account during disambiguation. Possibly as a consequence of this, some ambiguities appear now when I create an alias of a module with instance declarations and without the flag.

**Comment by jespercockx** [comment]
After some discussion among the devs, we decided to keep the default behaviour as it is because it is the least surprising to new users. If there's an issue with ambiguous instances created by module aliases, please report it as a new issue.
