### ISSUE TITLE
Windows nightly build workflow fails to pack

### ISSUE THREAD

**Issue by L-TChen** [agda/agda#5040]
The nightly build workflow for Windows has been broken, since the path to `msys2` provided by `stack` is different now. See the log file https://github.com/agda/agda/runs/1369386316?check_suite_focus=true.

Another way to solve this is to build a statically linked binary instead of one dynamically linked to `msys2`. 

I am not familiar with Windows, so I cannot fix this myself. @ice1000 would you be able to look after this?

**Comment by ice1000** [comment]
The reason why I made stack to use dynamic linking, is because I found static linking with Haskell & Windows is hard.
I'd suggest upgrading the paths :(

**Comment by ice1000** [comment]
FYI, I guess the new path is 20200903, according to https://github.com/commercialhaskell/stackage-content/blob/master/stack/stack-setup-2.yaml#L73-L83

**Comment by ice1000** [comment]
Let's watch https://github.com/agda/agda/pull/5041/checks?check_run_id=1373052590

**Comment by L-TChen** [comment]
Is it possible to get this path from `stack path`?

**Comment by ice1000** [comment]
Good question, but unfortunately I no longer use stack on Windows. Instead I use WSL + ghcup. Maybe we can ask someone else
