### ISSUE TITLE
Double-check modalities

### ISSUE THREAD

**Issue by nad** [agda/agda#5042]
I don't think the double-checker checks that modalities (except for relevance) are correct. Here's one example:

https://github.com/agda/agda/blob/bc327151a92f20b0ff2e2d3b18270e4b4797bca8/src/full/Agda/TypeChecking/CheckInternal.hs#L281-L285

**Comment by jespercockx** [comment]
This will be fixed by https://github.com/agda/agda/pull/5007/commits/5501950d439d948b95a05c4098f9d56a0aa30177 (which is part of PR https://github.com/agda/agda/pull/5007)
