### ISSUE TITLE
Cannot alter appearance of LaTeX output for {! term !} 

### ISSUE THREAD

**Issue by ajrouvoet** [agda/agda#5043]
Compiling a literate Agda file to LaTeX with a (partially) filled hole in it generates code without the \AgdaHole macro used.
Instead the code will just contain something like this:

```
\AgdaSymbol{\{!term!\})}\<%
```

This seems wrong, because this means that one cannot alter how these holes are highlighted.

**Comment by ajrouvoet** [comment]
Briefly looked at this today to see if this was a low-hanging-fruit/good first issue. I did not manage to find out how Agda represents `{! term !}` holes in concrete syntax at the moment. Since `{` and `{{` are tokens and you cannot use start a name with `{`, I expected `{!` to be a token, but that doesn't seem to be the case.

I'll try to find out if I can incentivize Agda to give me the result of parsing an Agda program with a hole and go from there.

**Comment by gallais** [comment]
IIRC the editor modes are responsible for highlighting holes themselves.
We don't store that information & do not set an `(Other)Aspect` corresponding
to it. I may have a somewhat dirty solution.

**Comment by gallais** [comment]
With

```diff
diff --git a/src/full/Agda/Interaction/Highlighting/LaTeX/Base.hs b/src/full/Agda/Interaction/Highlighting/LaTeX/Base.hs
index b80f13b4d..c139af234 100644
--- a/src/full/Agda/Interaction/Highlighting/LaTeX/Base.hs
+++ b/src/full/Agda/Interaction/Highlighting/LaTeX/Base.hs
@@ -485,8 +485,9 @@ processCode toks' = do
             -- to its aspect (if any) and other aspects (e.g. error, unsolved meta)
             foldr (\c t -> cmdPrefix <+> T.pack c <+> cmdArg t)
                   (escape tok)
-                  $ map fromOtherAspect (toList $ otherAspects $ info tok') ++
-                    concatMap fromAspect (toList $ aspect $ info tok')
+                  $ specialAspect tok
+                  ++ map fromOtherAspect (toList $ otherAspects $ info tok')
+                  ++ concatMap fromAspect (toList $ aspect $ info tok')
 
     -- Non-whitespace tokens at the start of a line trigger an
     -- alignment column.
@@ -495,6 +496,11 @@ processCode toks' = do
           registerColumnZero
           output . Text . ptOpen =<< columnZero
 
+    specialAspect :: Text -> [String]
+    specialAspect t
+      | "{!" `T.isPrefixOf` t = ["Hole"]
+      | otherwise             = []
+
     -- Translation from OtherAspect to command strings. So far it happens
     -- to correspond to @show@ but it does not have to (cf. fromAspect)
     fromOtherAspect :: OtherAspect -> String
```

I get

```tex
\begin{code}%
\>[0]\AgdaFunction{latex}\AgdaSpace{}%
\AgdaSymbol{:}\AgdaSpace{}%
\AgdaPrimitive{Set}\<%
\\
\>[0]\AgdaFunction{latex}\AgdaSpace{}%
\AgdaSymbol{=}\AgdaSpace{}%
\AgdaHole{\AgdaSymbol{\{!!\}}}\<%
\end{code}
```

from

```agda
\begin{code}
latex : Set
latex = {!!}
\end{code}
```

If y'all are happy with that solution, I can write a test case & open a PR.

**Comment by ajrouvoet** [comment]
> We don't store that information & do not set an (Other)Aspect corresponding to it. 

Do you prefer this 'hacky' solution because changing the representation would be a backwards incompatible change on the editor 'api'?

**Comment by gallais** [comment]
After double checking, it looks like it would not be too much work to
introduce a new aspect. I'll try that.

**Comment by ajrouvoet** [comment]
If this is a good first issue I can also have a go at it? Unless anyone needs this ASAP :)

**Comment by andreasabel** [comment]
FORGOT TO SUBMIT: Maybe understanding where the current behavior comes from is the first step to change it.

Agda lexes `{!term!}` as a single token `TokSymbol SymQuestionMark <interval>`:
https://github.com/agda/agda/blob/19c1dec8f7fe3029d68d99b7506bb2e1fd3104c7/src/full/Agda/Syntax/Parser/Comments.hs#L53-L62
Agda is oblivious to the contents of the whole.  The interacting editor will send the contents to Agda upon certain interaction commands.
The highlighter marks the region associated with that token with the `Symbol` aspect.  It does not remember that it came from a hole:
https://github.com/agda/agda/blob/19c1dec8f7fe3029d68d99b7506bb2e1fd3104c7/src/full/Agda/Interaction/Highlighting/Generate.hs#L223
The LaTeX backend will then output the whole token as `Symbol`:
https://github.com/agda/agda/blob/19c1dec8f7fe3029d68d99b7506bb2e1fd3104c7/src/full/Agda/Interaction/Highlighting/LaTeX/Base.hs#L483-L489
and
https://github.com/agda/agda/blob/19c1dec8f7fe3029d68d99b7506bb2e1fd3104c7/src/full/Agda/Interaction/Highlighting/LaTeX/Base.hs#L503-L509

If you want to do something about it, you could make the highlighter smarter so it does not just attach the aspect `Symbol` but maybe something more specific like `Hole`.  This aspect could than be processed by the LaTeX backend in some smarter way.

**Comment by ajrouvoet** [comment]
> Maybe understanding where the current behavior comes from is the first step to change it.

I think we are on the same page on that one.

**Comment by ajrouvoet** [comment]
@gallais Except for my comment that commit looks good to me and also seems in line with what @andreasabel describes. 
To editors need to update their interaction or is this backwards compatible?

**Comment by gallais** [comment]
> If this is a good first issue I can also have a go at it? Unless anyone needs this ASAP :)

Sorry, I did not realise you wanted to fix it yourself & was away
working on it at the same time.

**Comment by ajrouvoet** [comment]
That is OK, plenty of issues. I shouldn't be too eager to not work on my thesis anyways.
