### ISSUE TITLE
.agda-lib files are not reloaded automatically

### ISSUE THREAD

**Issue by nad** [agda/agda#5045]
It seems as if changes to `.agda-lib` files are not picked up automatically by the Emacs mode. I guess this has something to do with the new caching of `.agda-lib` files. I think that `.agda-lib` files should be treated in the same way as `.agda` files:
* If a `.agda-lib` file has changed, then it should be reloaded, just like imported `.agda` files are reloaded if they have changed.
* When a module is loaded any `.agda-lib` files should be read at most once, just like imported `.agda` files are read at most once.

**Comment by andreasabel** [comment]
> new caching of .agda-lib files

Which commit would that be?

**Comment by jespercockx** [comment]
https://github.com/agda/agda/commit/96af1a15733f0b52db9ce0fcb6379298409629c2

**Comment by andreasabel** [comment]
I confirm that this is not an issue with 2.6.1, but an issue with the present master.
