### ISSUE TITLE
Disturbing names in normalised reflected type

### ISSUE THREAD

**Issue by ashinkarov** [agda/agda#5048]
Given the following Agda code (using agda 2.6.1)
```agda
open import Agda.Builtin.Unit
open import Agda.Builtin.Reflection renaming (bindTC to _>>=_)
macro
  m : Name → Term → TC ⊤
  m f hole = do
     ty ← getType f
     ty ← normalise ty
     quoteTC ty >>= unify hole

module stdlib where
  open import Data.Nat

  bar : ℕ → ℕ
  bar x = x + 1
  a : _
  a = m bar

module nostdlib where
  open import Agda.Builtin.Nat
  bar : Nat → Nat
  bar x = x + 1
  a : _
  a = m bar
```
When normalising `nostdlib.a` I get:
```
pi
(arg (arg-info visible relevant)
 (def (quote Agda.Builtin.Nat.Nat) Agda.Builtin.List.List.[]))
(abs "n"
 (def (quote Agda.Builtin.Nat.Nat) Agda.Builtin.List.List.[]))
```
which is fine.
When normalising `stdlib.a` I get:
```
pi
(arg (arg-info visible relevant)
 (def (quote Agda.Builtin.Nat.ℕ) Agda.Builtin.List.List.[]))
(abs "ℕ"
 (def (quote Agda.Builtin.Nat.ℕ) Agda.Builtin.List.List.[]))
```
which is weird because of:
* the name `ℕ` assigned to the argument
* the type `Agda.Builtin.Nat.ℕ` (there is no `ℕ` in `Agda.Builtin.Nat`)

The weird name appears only if the call to `normalise` after `getType` in `m` is present.  If I remove it, the name would be "_" in both cases.  The wired type would be the same with and without normalisation.

**Comment by UlfNorell** [comment]
This looks like a more benign variant of #4735. The fix of that issue did not fix this problem. Note that you don't need the macro, simply quoting the name shows the problem:
```agda
module stdlib where
  open import Data.Nat
  a = quote ℕ

module nostdlib where
  open import Agda.Builtin.Nat
  a = quote Nat

-- C-c C-n stdlib.a    --> quote Agda.Builtin.Nat.ℕ
-- C-c C-n nostdlib.a  --> quote Agda.Builtin.Nat.Nat
```
It's just the printing that's broken, the names are definitionally equal:
```agda
check : stdlib.a ≡ nostdlib.a
check = refl
```

**Comment by ashinkarov** [comment]
@UlfNorell , for the second problem you don't need a macro.  But I don't know whether you can get the name `ℕ` in the pi type without a macro.  However, it would be great if your fix would resolve both issues.

**Comment by UlfNorell** [comment]
Wait, what's the first problem? I only saw the problem with reflected names being printed incorrectly.

**Comment by ashinkarov** [comment]
The name of the variable in the pi type coincides with the name of the type.  It is set to `ℕ` after the type is normalised.

One can argue whether this is a bug or not, but it is definitely quite annoying.  One cannot really write:
```agda
foo : (ℕ : ℕ) → ℕ
```
You'd at least have to write something like
```agda
foo : (ℕ : ℕ) → Data.Nat.ℕ
```
But given that a more sane name is picked in nostdlib case, maybe it is worth fixing?

**Comment by UlfNorell** [comment]
Oh, I missed that. I'll check if my fixed made a difference.

**Comment by UlfNorell** [comment]
It did not. There's some heuristics for picking the variable name (not sure where it lives actually), that simply tries to turn the first letter of the type to lowercase. This fails for `ℕ` so it stays unchanged. For instance,

```agda
open import Agda.Builtin.Nat renaming (Nat to Hombre)

bar : Hombre → Hombre
bar x = x + 1

a = m bar
```
gives you
```
pi
(arg (arg-info visible relevant)
 (def (quote Hombre) Agda.Builtin.List.List.[]))
(abs "h" (def (quote Hombre) Agda.Builtin.List.List.[]))
```
I'm not sure this is worth fixing (or what the fix should be).

**Comment by gallais** [comment]
We could check the [`generalCategory`](https://hackage.haskell.org/package/base-4.14.0.0/docs/Data-Char.html#v:generalCategory) and only use that heuristics
if the letter is any of `UppercaseLetter`, `LowercaseLetter`, or `TitlecaseLetter`
and pick something else otherwise?

Doesn't look like there is a function to try to convert to the closest ASCII letter
which would be convenient here :(

**Comment by UlfNorell** [comment]
Reopening for the binder name choice.

**Comment by UlfNorell** [comment]
The category of `ℕ` is `UppercaseLetter` (and it satisfies `isAlpha` which is what we checked before), so that doesn't help. Settling for picking `toLower` of the first letter if it's a character with distinct upper/lower case forms, unless the type name is a single lower case letter.

For future reference the logic is in `Agda.TypeChecking.Unquote.pickName`.
