### ISSUE TITLE
Internal error related to pattern synonyms

### ISSUE THREAD

**Issue by nad** [agda/agda#5055]
The following code triggers an internal error:
```agda
open import Agda.Builtin.Sigma

data Shape : Set where
  c : Shape → Shape

pattern p (s , v) = c s , v
```
```
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/Syntax/Concrete/Name.hs:300:23 in Agda-2.6.2-BWiZcZqc7cf2XNtJAyhpNo:Agda.Syntax.Concrete.Name
```

**Comment by andreasabel** [comment]
The internal error is raised here: https://github.com/agda/agda/blob/5069efa1c60f13fb074d3288714b5ae27686c761/src/full/Agda/Syntax/Concrete/Name.hs#L292-L300
But the invariant
https://github.com/agda/agda/blob/5069efa1c60f13fb074d3288714b5ae27686c761/src/full/Agda/Syntax/Concrete/Name.hs#L36-L39
must be violated somewhere else.
Maybe the invariant (alternating identifiers and holes) should be enforced statically.
We could implement `NameParts` as follows:
```haskell
type IdParts = List1 RawName
data NameParts = NameParts { nameType :: NameType, idParts :: IdParts }
data NameType
  = NonfixName   -- ^ foo_bar
  | PrefixName   -- ^ foo_bar_
  | PostfixName  -- ^ _foo_bar
  | InfixName    -- ^ _foo_bar_
```

**Comment by andreasabel** [comment]
However, the OP is caused by the too liberal parser.  It accepts `LamBinds` as lhs variables, but these include now record patterns.
https://github.com/agda/agda/blob/5069efa1c60f13fb074d3288714b5ae27686c761/src/full/Agda/Syntax/Parser/Parser.y#L1322-L1331
Before 2.6.0, this was a parse error, then the error got a bit more obscure, now we have an internal error:
```
$ agda-2.6.1 Issue5055.agda 
Issue5055.agda:6,1-28
Unused variable in pattern synonym.
when scope checking the declaration
  pattern p _ = c s , v

$ agda-2.6.0 Issue5055.agda 
Issue5055.agda:6,1-28
Unused variable in pattern synonym.
when scope checking the declaration
  pattern p s , v = c s , v

$ agda-2.5.4.2 Issue5055.agda 
Issue5055.agda:6,17: Parse error
)<ERROR>
 = c s , v
...
```

**Comment by andreasabel** [comment]
See also 2fbef7d4bb4b2060aa10d0a14f0c42e53aa43cb2 that allowed constructor patterns in telescopes (`LamBinds`).
