### ISSUE TITLE
Generalisation does not always respect modalities

### ISSUE THREAD

**Issue by nad** [agda/agda#5058]
Every `variable` declaration in the following piece of code uses `@0`:
```agda
postulate
  I : Set

data Box (A : Set) : Set where
  [_] : A → Box A

variable
  @0 i : I
  @0 b : Box I

data D : @0 Box I → Set where
  d : D [ i ] → D [ i ]

variable
  @0 x : D b

data P : @0 D b → Set where
  p : P (d x)

works : ∀ {i} {@0 x : D [ i ]} → P (d x)
works = p

fails : ∀ {@0 i} {@0 x : D [ i ]} → P (d x)
fails = p
```
However, the type that Agda constructs for `p` is `{i : I} {@0 x : D [ i ]} → P (d x)`. The argument `i` should be erased.

**Comment by UlfNorell** [comment]
What you'd like to happen here is that `i` is generalized as `@0` since it's created as a meta for the `i` argument to `d` (which is marked `@0`). The problem is that *all* metas created in types are tagged as erasable since types counts as erased contexts. Now we do track the origin of quantities so in theory this should be easy. The problem is this code:

https://github.com/agda/agda/blob/5269bc648a7f256a55413d01487fb3d5ca22a59b/src/full/Agda/Syntax/Common.hs#L726-L731

The monoid instance for quantity picks the origin of the right argument (even though there is a monoid instance for origins). In this case it means ignoring the user origin of the `i` variable in favour of the inferred `Q0` origin from being in a type. 

@andreasabel is there a reason not to use the origin monoid instance here, or can I go ahead and change it (the `right-bias!` comments have me worried)?

Here's a test case to make sure only user annotated `@0`s get generalized as erased:
```agda
postulate
  I : Set
  D : I → Set
  E : ∀ {i} → D i → Set

variable
  A : Set
  x : A

-- Should not generate erased binding for i:
-- foo : {@0 i : I} {x : D i} → E x → I
foo : E x → I
foo {i = i} = i
```

**Comment by UlfNorell** [comment]
Ping @andreasabel. Any feedback on the right-biased thing?

**Comment by nad** [comment]
Now the following code is rejected:
```agda
postulate
  A : Set
  F : A → Set
  P : {@0 x : A} → F x → Set

variable
  B : Set
  f : B

works : {x : A} {f : F x} → P f → A
works {x = x} _ = x

fails : P f → A
fails {x = x} _ = x
```
(I don't think it should be possible to bind the variable `x` in `fails`, but that is a different issue. I encountered this problem in some code in which a use of something like `x` was inferred automatically.)

The code is rejected because `x` is marked as erased in the body of `fails`. I guess this is because `x` is marked as erased in the type signature of `P`.

I have some code in which I tried to ensure that all variables that are not bound explicitly are erased. (I think Idris 2 takes this approach.) I did this by marking each generalisable variable with `@0`. However, this approach (no longer?) works. The following code is not rejected:
```agda
postulate
  A : Set
  F : A → Set
  P : {x : A} → F x → Set

variable
  @0 B : Set
  @0 f : B

does-not-fail : P f → A
does-not-fail {x = x} _ = x
```
I think this code should be rejected.

**Comment by UlfNorell** [comment]
If you don't think we should generalize over `x` you can change `inherited` to `Set.empty` here:
https://github.com/agda/agda/blob/62dc18ef2f3628ae05db0b132ce40060229df523/src/full/Agda/TypeChecking/Generalize.hs#L223
and see how your developments fare.

If I interpret the examples correctly, your proposed rule is that when we generalize over metas appearing in the solutions of generalizable metas they should get the modality of the original meta and ignore their own modality. In that case, what should the modality of `x` be in this example:
```agda
postulate
  A : Set
  F : A → Set
  H : {x : A} → (F x → F x) → Set

variable
  B    : Set
  @0 C : Set
  f    : B → C

hmm : H f → A
hmm {x = x} _ = x
```

**Comment by nad** [comment]
I want things to be predictable. I do not want to have to inspect the inferred type signature to know whether an argument is marked as erased or not. Perhaps the following design would work:
* For generalisable variables, use their declared modality.
* For other variables, use a default that can be set using a keyword. The default default is the "empty" modality (not erased, and so on).

Example:
```agda
postulate
  A : Set
  P : A → Set
  Q : {x : A} → P x → P x → Set

variable
  modality @0
  B    : Set
  @0 q : B

postulate
  F : ∀ p → Q p q → Set
```
Here the type of `F` should be `{@0 fresh : A} {@0 q : P fresh} (p : P fresh) → Q p q → Set`. If `modality @0` is removed, then the type should be `{fresh : A} {@0 q : P fresh} (p : P fresh) → Q p q → Set`.

If the `modality` keyword is only allowed in `variable` blocks, then it can still be used as a regular name. The scope of the default modality should be the same as that of a private declaration made in the same place. It should be possible to override the default modality in inner modules. Example:
```agda
variable
  modality @0

  -- Default: @0.

module _ where

  variable
    modality

    -- Default: The "empty" modality.
```

I have not tested this design in practice, so I do not know how well it would work, but at least it should be predictable.

**Comment by UlfNorell** [comment]
This seems more like a new feature request than the bug in the OP.

**Comment by nad** [comment]
A simple first step might be to do what I suggested, but without support for the `modality` keyword. I think that would work for most of my code. Would this be easy to implement? I can test this locally if you tell me how to change the implementation (or push a branch with the changes).

**Comment by UlfNorell** [comment]
Here
https://github.com/agda/agda/blob/62dc18ef2f3628ae05db0b132ce40060229df523/src/full/Agda/TypeChecking/Generalize.hs#L293
you could check if `m` is one of the metas in `alsoGeneralize` and if so `setModality defaultModality`.

**Comment by nad** [comment]
This seems to work fine for my code.

With this change in place, is there any difference compared to the original behaviour? I want to know if I should write anything in the changelog.

**Comment by UlfNorell** [comment]
Since you're going for predictable behaviour it might be nice to write something in the user manual and the changelog....
