### ISSUE TITLE
Manual eta-expansion of functions speeds up typechecking

### ISSUE THREAD

**Issue by sstucki** [agda/agda#5060]
I'm reporting this after a recent discussion with @JacquesCarette (see PR agda/agda-categories#220) about the following code
https://github.com/agda/agda-categories/blob/97686247e74ae3265a486a585ed31d5f8f955abe/src/Categories/Category/Instance/Monoidals.agda#L39-L42

Without the manual eta-expansion, this takes ages to type check, with the eta-expansion it type checks almost immediately.  I assume that this is because Agda is performing the eta-expansion internally anyway, but then needs to infer the implicit arguments which involves (weakly) normalizing some large terms involving record creations and projection, etc.

I'd love to provide a minimal example that triggers this, but of course this this sort of performance issue tends not to show up in small code snippets.

**Comment by andreasabel** [comment]
I'd say the speed goes up thanks to the hidden arguments you supply yourself, rather than having Agda figure them out.  It is
```agda
; assoc     = λ {_ _ _ _ F G H} → associator {F = F} {G} {H}
```
vs.
```agda
; assoc     = λ {_ _ _ _ F G H} → associator {F = _} {_} {_}
```
Finding the seemingly trivial solutions to the three metas in the latter case can take long since Agda uses higher-order unification modulo eta and might eta-expand these three metas to big nested records of metas.

**Comment by JacquesCarette** [comment]
Is there any chance we could get some debugging tools related to such issues? Surely there are ways to measure how complex a unification problem is (was?), and past some threshold (user-provided?) a debug message would be emitted.

In time, I'd be willing to do it myself. I just know that I wouldn't get to it until May at the earliest. I think performance debugging is one of the few really non-trivial 'pain points' I have with Agda.

**Comment by nad** [comment]
Please open a new feature request for this.
