### ISSUE TITLE
The termination checker reduces with non-exact clauses

### ISSUE THREAD

**Issue by nad** [agda/agda#5065]
The following code is accepted:
```agda
open import Agda.Builtin.Bool

bad : Bool → Bool
bad b with bad b
… | true = bad b
… | _    = true
```
This seems to have something to do with `tryReduceNonRecursiveClause`: if I remove the call to this function, then the code is rejected.

**Comment by andreasabel** [comment]
Looking at the implementation, it seems that there is some unsoundness in connection to catch-all clauses:
https://github.com/agda/agda/blob/bb7a99879e7688cce5e85f384337240af81e307d/src/full/Agda/Termination/TermCheck.hs#L860-L894
Debug output: (with `-v term.reduce:80`)
```
Trying to reduce away call:  bad b | bad b
This call is in the current SCC!
Function has 1 non-recursive clauses
... | _ = true
Termination checker: Successfully reduced away call:
  bad b | bad b
```
Excluding catch-all clauses would likely fix this regression.

**Comment by andreasabel** [comment]
Even worse, removing the catch-all, the termination checker loops:
```agda
open import Agda.Builtin.Bool

bad : Bool → Bool
bad b with bad b
… | true  = bad b
… | false = true
```
Seems like `bad_aux b (bad b)` is matched against clause `bad_aux _ false` which will match `bad b` against `false`.  Not sure why this loops, `bad` shouldn't reduce yet.
Last message with `-v 100`:
```
matchCopatterns
  ps = b, (false)
  vs = $ b, $ bad b
```
I pushed a fix for the loop issue: d5c7d56df70f826d544c4f3ebc9adc429f78b5aa

**Comment by andreasabel** [comment]
To fix the OP, we need to know which clauses are catch-all/non-exact.  The coverage checker computes this but does not store it.  We could store it like we store the unreachability bit:
https://github.com/agda/agda/blob/bb7a99879e7688cce5e85f384337240af81e307d/src/full/Agda/TypeChecking/Coverage.hs#L252-L256
Currently, we only generate warnings:
https://github.com/agda/agda/blob/bb7a99879e7688cce5e85f384337240af81e307d/src/full/Agda/TypeChecking/Coverage.hs#L275-L278

**Comment by andreasabel** [comment]
Further fixup needed:
- #6687 
- #6688
