### ISSUE TITLE
Map.fromList silently drops duplicates

### ISSUE THREAD

**Issue by gallais** [agda/agda#5070]
TIL: `Map.fromList` silently drops values associated to duplicated keys
(which is pretty self-evident from its type).

The behaviour is correct if we assume that the list contains unique keys
but it would be more appropriate for us to use `fromListWith __IMPOSSIBLE__`
to guarantee the invariant is enforced.

**Comment by andreasabel** [comment]
There was one TODO left, but I cannot remember it now...

Cherry-picked onto `maint-2.6.2`, scheduled for 2.6.2.1.
