### ISSUE TITLE
Deep pattern-matching is sometimes allowed for erased arguments

### ISSUE THREAD

**Issue by nad** [agda/agda#5079]
The following code is accepted:
```agda
open import Agda.Builtin.Bool

data D : Set where
  c : Bool → D

f : @0 D → Bool
f (c true)  = true
f (c false) = false
```
Pattern-matching is perhaps fine for the single-constructor data type `D`, but not for `Bool`: it should not be possible to make a decision based on erased data.

The GHC backend seems to ignore the `@0` annotation:
```haskell
name6 = "Bug.f"
d6 :: T2 -> Bool
d6 v0
  = case coe v0 of
      C4 v1 -> coe v1
      _ -> MAlonzo.RTE.mazUnreachableError
```

**Comment by nad** [comment]
With `-vtc.cover:100` I get the following message five times:
```
We are in erased context = False
```

**Comment by nad** [comment]
I found the following comment in the code:

https://github.com/agda/agda/blob/d20295b678fe0600630cd50ac5b51ab567e5462d/src/full/Agda/TypeChecking/Coverage.hs#L1130-L1132

Propagating the entire modality does not seem to fix the problem in the OP, but perhaps it makes sense to do this anyway.

**Comment by nad** [comment]
If you compile the following program using the GHC backend and then run it, then `True` is printed:
```agda
open import Agda.Builtin.Bool
open import Agda.Builtin.IO
open import Agda.Builtin.Unit

postulate
  print : Bool → IO ⊤

{-# COMPILE GHC print = print #-}

data D : Set where
  c : Bool → D

f : @0 D → Bool
f (c false) = false
f (c true)  = true

main : IO ⊤
main = print (f (c false))
```

**Comment by Saizan** [comment]
We also need to propagate the modality to `gamma0` above.
