### ISSUE TITLE
Support Bird-style literate Agda

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#508]
Currently .lagda files only support the TeX style, and it'd be nice to support the Bird style (introduced by >) too, particularly for use in blog posts and the like.

Original issue reported on code.google.com by `pumpkingod@gmail.com` on 6 Nov 2011 at 5:09

**Comment by andreasabel** [comment]
@vlopezj has implemented support for various literate agda formats now.  I am closing this.
If needed, a new issue can be opened starting that the current state-of-the art.
