### ISSUE TITLE
Weird instance propagation between parameterised modules

### ISSUE THREAD

**Issue by omelkonian** [agda/agda#5093]
I came across a rather peculiar issue when using instance arguments and (multiple) paramerised modules.

Let's assume we have an Eq typeclass in a separate file:
```Eq.agda
module Eq where
open import Agda.Builtin.Bool

record Eq (A : Set) : Set where
  field
    _==_ : A → A → Bool
open Eq {{...}} public
```

Then a module parameterised over some type A having (decidable) equality:

```M1.agda
open import Eq

module M1 (A : Set) {{_ : Eq A}} where

postulate
  B : Set
variable
  n : B
postulate
  P : B → Set

postulate
  p₁ : P n
```

All fine so far, but what if I want to split that file, e.g. to work on p₁ there:
```M2.agda
open import Eq
module M2 (A : Set) {{_ : Eq A}} where

open import M1 A

postulate p₂ : P n
```
But now there is an error:
```
No instance of type Eq A was found in scope.
when checking that n is a valid argument to a function of type
⦃ _ = x : Eq A ⦄ → M1.B A → Set
```

Amusingly, this is solved if we pass `it` as the instance argument!
```M2-workaround.agda
open import Eq
module M2 (A : Set) {{_ : Eq A}} where

open import M1 A {{it}}

postulate p₂ : P n
```

- Shouldn't all occurrences of `{{it}}` be meaningless?

**Comment by UlfNorell** [comment]
There's no need for separate files:
```agda
open import Agda.Builtin.Bool

postulate Eq : Set → Set

module M1 (A : Set) ⦃ _ : Eq A ⦄ where
  postulate B : Set
  variable  n : B
  postulate P : B → Set

module M2 (A : Set) ⦃ eqA : Eq A ⦄ where
  open M1 A
  postulate p : P n  -- No instance of type Eq A
```

**Comment by UlfNorell** [comment]
The problem here is that we incorrectly generalize over the `Eq A` argument to `n`, even though it is bound by the instance constraint for the argument to `P`. Fix is to not ignore instance constraints when computing which metas are constrained and cannot be generalized over. PR above.
