### ISSUE TITLE
Level-agnostic type paths

### ISSUE THREAD

**Issue by shlevy** [agda/agda#5097]
Following up from a [thread](https://agda.zulipchat.com/#narrow/stream/260790-cubical/topic/Cross-universe.20paths.3F/near/219075101) on Zulip: Would it be possible to have a special case path type for paths between types in any universe, e.g. `PathT : ∀ {ℓ₀ ℓ₁} → Type ℓ₀ → Type ℓ₁ → Type (ℓ-suc (ℓ-max (ℓ₀ ℓ₁)))`, and possibly have `PathP`'s first argument take a `PathT`. `_≃_` is already defined across universes, so presumably we could adjust glue types/univalence to the full generality here?

**Comment by Saizan** [comment]
It seems you would need `--cumulativity` to have sensible introduction and elimination rules, but in that case the original `PathP` should be enough.

**Comment by shlevy** [comment]
@Saizan Interesting, can you explain why cumulativity would be needed?

**Comment by Saizan** [comment]
Mostly the problem would be type preservation.
If we have `p : PathT {ℓ₀} {ℓ₁} A B` then I suppose we can take type application to have type `p r : Type (ℓ-max ℓ₀ ℓ₁)`.

However paths should also compute on endpoints, e.g. `p i0 = A` and `p i1 = B`, but neither `A` nor `B` have type `Type (ℓ-max ℓ₀ ℓ₁)` without cumulativity.

One way to fix this would be to make the level of a `PathT` application dependent on `r`, but universe levels are already quite complicated as it is. Also Level should really only have reflexivity paths, unless we are talking about directed type theory.

**Comment by shlevy** [comment]
> One way to fix this would be to make the level of a PathT application dependent on r, but universe levels are already quite complicated as it is.

Ah, I see, OK. That definitely complicates it

> Also Level should really only have reflexivity paths

We're not looking for a path in `Level` here though right? We're not asking to say that two levels are equivalent, just that two types (in different levels) are. If we allow `≃` across universes shouldn't we also allow `≡`?

**Comment by Saizan** [comment]
We'd be essentially looking for a path in `Level` if we wanted to make the level of a `PathT` application dependent on `r`, otherwise no.

I will close this as wontfix as I don't see a way forward which is not just `--cumulativity`.
