### ISSUE TITLE
Load (C-c C-l) does not check for change in .agda-lib file

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5102]
In the following situation,
- `/Main.agda-lib` containing `include: .`,
- `/Dir/Module.agda` containing `module Module where`,
loading `Module.agda` in emacs with `C-c C-l` gives the expected error "module name does not match filename".

Adding `/Dir/Main.agda-lib` containing `include: .` does not change the behavior of load (`C-c C-l`)---but should, imo.  
A restart of Agda is required (`C-c C-x C-r`) to make load succeed.

I'd expect "load" to not only look for changes in the current file, but also in the library file.

**Comment by jespercockx** [comment]
Oh, this is probably a regression that I introduced when I implemented caching of `.agda-lib` files in https://github.com/agda/agda/pull/4942/commits/69d5caf62a9d38259cda4141bbb5331285c32284. Maybe it would be better to invalidate `stProjectConfigs` and `stAgdaLibFiles` in the TCM state when we do a reload?

**Comment by jespercockx** [comment]
Actually I made it part of the `PersistentState` which seemed to be a logical choice at that time, but perhaps it would be better as part of the `PreScopeState` (which I assume *is* reset on a reload?)

**Comment by andreasabel** [comment]
Seem like the present issue is in the same ballpark as #5045.
Worked with 2.6.1, doesn't work on master.  Likely a duplicate of #5045.

**Comment by jespercockx** [comment]
Closing this as duplicate.
