### ISSUE TITLE
--js allows --allow-unsolved-metas, but --ghc not

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5103]
While investigating #5098, i realized that `--js` allows `--allow-unsolved-metas`, but `--ghc` not.
```
$ echo "S = Set" > Foo.agda

$ agda --js --allow-unsolved-metas Foo.agda 
Compiling Agda.Primitive 
Compiling Foo 

$ agda --ghc --allow-unsolved-metas Foo.agda 
Unsolved meta variables are not allowed when compiling.
```

`--js` crashes if there is an actual unsolved meta:
```
$ echo "S = ?" > Foo.agda
$ agda --js --allow-unsolved-metas Foo.agda 
Checking Foo 
Compiling Agda.Primitive 
Compiling Foo 
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/Compiler/ToTreeless.hs:430:20
```

Couldn't we simply compile metas to runtime errors, just like we do for postulates?
The `Treeless` syntax already has a `TError` case...

**Comment by jespercockx** [comment]
> Couldn't we simply compile metas to runtime errors, just like we do for postulates?

Sure we *could*, but I'd consider that quite unexpected behaviour. An error saying you can't compile files with unsolved metas definitely makes more sense to me. Perhaps we can make an exception for files with `--allow-unsolved-metas`? For files with that flag we already turn metas into postulates when serializing, so compiling them to errors (just as for postulates) would make sense.

**Comment by andreasabel** [comment]
> Perhaps we can make an exception for files with `--allow-unsolved-metas`? 

That's what I am after.  Without that flag, we do not even get to the compilation phase.

Btw, under 2.6.1 the OP does not exist, there, `--ghc` and `--js` behave the same, both refusing to compile.  The missing check in the JS backend is thus a new regression.
