### ISSUE TITLE
Problems with implicit arguments

### ISSUE THREAD

**Issue by yellowsquid** [agda/agda#5110]
I would expect `is-refl` and `is-refl′` to either both type check or both have unsolved constraints. Instead, `is-refl` has unsolved constraints but `is-refl′` type checks.

```agda
{-# OPTIONS --without-K --safe #-}

open import Agda.Primitive
open import Agda.Builtin.Unit

module test
  {a ℓ : Level}
  {A : Set a}
  where

⟨Set⟩ : Set (a ⊔ lsuc ℓ)
⟨Set⟩ = A → Set ℓ

_⊆_ : ⟨Set⟩ → ⟨Set⟩ → Set (a ⊔ ℓ)
X ⊆ Y = ∀ {x} → X x → Y x

⊆-refl : ∀ {X} → X ⊆ X
⊆-refl x∈X = x∈X

needs-refl : (∀ {X} → X ⊆ X) → ⊤
needs-refl _ = tt

-- _X_16 : ⟨Set⟩ [ at 30,22-28]
-- _X_17 : A [ at 30,22-28]
-- ———— Errors ————————————————————————————————————————————————
-- Failed to solve the following constraints:
--   _X_16 _x_17 =< X x
--   X x =< _X_16 _x_17
is-refl : ⊤
is-refl = needs-refl ⊆-refl

-- Works fine
is-refl′ : ⊤
is-refl′ = needs-refl λ z → z
```

There is a clear workaround to this issue (writing the lambda). However, from a user experience perspective, this is a major issue. A function name is far more descriptive than an inline lambda. Additionally, this leads to duplication of code across a file.

As far as I know, there is no documentation explaining why the lambda should behave differently from `⊆-refl`. In fact, [this page](https://agda.readthedocs.io/en/v2.6.1.1/language/lambda-abstraction.html#lambda-abstraction) suggests that `⊆-refl` and the lambda should be equivalent.

**Comment by andreasabel** [comment]
Since hidden arguments are inserted eagerly, your code is interpreted as
```agda
is-refl = needs-refl (⊆-refl {_})
```
This meta cannot be solved uniquely.  You need to write
```agda
is-refl = needs-refl (\ {X} -> ⊆-refl {X})
```
See also #1079.
