### ISSUE TITLE
Poor typechecking performance when there are many instance arguments

### ISSUE THREAD

**Issue by cruhland** [agda/agda#5117]
There appears to be quadratic behavior in the typechecker when there are many "awake" instance constraints. For example, I measured the typechecking time of [this 350 line file](https://github.com/cruhland/agda-axiomatic/blob/3a05ebd0de707a2ccffaa04e9ec8c40d6358e8c9/src/net/cruhland/models/Integers/Multiplication.agda) alone to be just over 3 minutes. More specifically, in the following term from that file (defined [here](https://github.com/cruhland/agda-axiomatic/blob/3a05ebd0de707a2ccffaa04e9ec8c40d6358e8c9/src/net/cruhland/models/Integers/Multiplication.agda#L71)) every call to the functions `_+_`, `_*_`, `_≃⟨_⟩_`, `_≃˘⟨_⟩_`, and `AA.subst` requires at least one instance argument apiece:

```
          [a₁⁺b⁺+a₁⁻b⁻]+[a₂⁺b⁻+a₂⁻b⁺]≃[a₂⁺b⁺+a₂⁻b⁻]+[a₁⁺b⁻+a₁⁻b⁺] =
            begin
              (a₁⁺ * b⁺ + a₁⁻ * b⁻) + (a₂⁺ * b⁻ + a₂⁻ * b⁺)
            ≃⟨ rearr {w = a₁⁺} {y = a₂⁺} ⟩
              (a₁⁺ + a₂⁻) * b⁺ + (a₂⁺ + a₁⁻) * b⁻
            ≃⟨ AA.subst (AA.subst a₁⁺a₂⁻≃a₂⁺a₁⁻) ⟩
              (a₂⁺ + a₁⁻) * b⁺ + (a₂⁺ + a₁⁻) * b⁻
            ≃˘⟨ AA.subst (AA.subst a₁⁺a₂⁻≃a₂⁺a₁⁻) ⟩
              (a₂⁺ + a₁⁻) * b⁺ + (a₁⁺ + a₂⁻) * b⁻
            ≃˘⟨ rearr {w = a₂⁺} {y = a₁⁺} ⟩
              (a₂⁺ * b⁺ + a₂⁻ * b⁻) + (a₁⁺ * b⁻ + a₁⁻ * b⁺)
            ∎
```

When that term is typechecked (with flags `-v tc.instance:20` and `-v tc.constr.solve:10`), here's a (condensed) view of the resulting logs:

```
Solving awake constraints. 84 remaining.        [A1]
Solving awake constraints. 85 remaining.        [B1]
Postponing possibly recursive instance search.
Solving awake constraints. 84 remaining.
Postponing possibly recursive instance search.
Solving awake constraints. 83 remaining.
Postponing possibly recursive instance search.
[...]
Solving awake constraints. 3 remaining.
Postponing possibly recursive instance search.
Solving awake constraints. 2 remaining.
Solving awake constraints. 1 remaining.
Solving awake constraints. 0 remaining.
Solving awake constraints. 85 remaining.        [B2]
Postponing possibly recursive instance search.
Solving awake constraints. 84 remaining.
Postponing possibly recursive instance search.
[...]
Solving awake constraints. 3 remaining.
Postponing possibly recursive instance search.
Solving awake constraints. 2 remaining.
Solving awake constraints. 1 remaining.
Solving awake constraints. 0 remaining.
[...]
[... several more blocks starting with "85 remaining" ...]
[...]
Solving awake constraints. 3 remaining.
Postponing possibly recursive instance search.
Solving awake constraints. 2 remaining.
Solving awake constraints. 1 remaining.
Solving awake constraints. 0 remaining.
Solving awake constraints. 83 remaining.        [A2]
Solving awake constraints. 84 remaining.        [B3]
Postponing possibly recursive instance search.
Solving awake constraints. 83 remaining.
Postponing possibly recursive instance search.
[...etc...]
```

The lines marked `[A1]` and `[A2]` are from the constraint solver working through each awake constraint for the term. But nested within each of those are several repetitions of the same process: `[B1]` and `[B2]` (and more) under `[A1]`, and `[B3]` under `[A2]`. It turns out that each of the B's for a given A occur when a candidate for an instance argument is found to be compatible with the expected type, i.e. "valid" in the code's terminology. This can be traced to the call to `solveAwakeConstraints` in the definition of the `newProblem` function ([defined in `Agda/Typechecking/Constraints.hs`](https://github.com/agda/agda/blob/c45dc6b2729a53653df2874b6ea8b3500793da78/src/full/Agda/TypeChecking/Constraints.hs#L165)):

```agda
-- | Create a fresh problem for the given action.
newProblem
  :: (MonadFresh ProblemId m, MonadConstraint m)
  => m a -> m (ProblemId, a)
newProblem action = do
  pid <- fresh
  -- Don't get distracted by other constraints while working on the problem
  x <- nowSolvingConstraints $ solvingProblem pid action
  -- Now we can check any woken constraints
  solveAwakeConstraints
  return (pid, x)
```

A rough "stack trace" starting from the above invocation of `solveAwakeConstraints` for one of the B-labeled lines and unwinding back towards the call that produced the corresponding A-labeled line is as follows:
- [`solveAwakeConstraints`](https://github.com/agda/agda/blob/c45dc6b2729a53653df2874b6ea8b3500793da78/src/full/Agda/TypeChecking/Constraints.hs#L165)
- [`newProblem`](https://github.com/agda/agda/blob/master/src/full/Agda/TypeChecking/Constraints.hs#L175)
- [`ifNoConstraints`](https://github.com/agda/agda/blob/master/src/full/Agda/TypeChecking/Constraints.hs#L179)
- [`ifNoConstraints_`](https://github.com/agda/agda/blob/master/src/full/Agda/TypeChecking/Constraints.hs#L186)
- [`guardConstraint`](https://github.com/agda/agda/blob/master/src/full/Agda/TypeChecking/InstanceArguments.hs#L483)
- [`checkCandidateForMeta`](https://github.com/agda/agda/blob/master/src/full/Agda/TypeChecking/InstanceArguments.hs#L417)
- [`checkCandidates`](https://github.com/agda/agda/blob/master/src/full/Agda/TypeChecking/InstanceArguments.hs#L257)
- [`findInstance'`](https://github.com/agda/agda/blob/master/src/full/Agda/TypeChecking/InstanceArguments.hs#L227)
- [`findInstance`](https://github.com/agda/agda/blob/master/src/full/Agda/TypeChecking/Constraints.hs#L290)
- [`solveConstraint_`](https://github.com/agda/agda/blob/master/src/full/Agda/TypeChecking/Constraints.hs#L248)
- [`solveConstraintTCM` (impl of `solveConstraint` for `instance MonadConstraint TCM`)](https://github.com/agda/agda/blob/master/src/full/Agda/TypeChecking/Constraints.hs#L239)
- `solveSomeAwakeConstraintsTCM`

The `checkCandidates` call is what results in the multiplicity of calls to `solveAwakeConstraints`: one for each valid candidate found by `checkCandidates`.

**Comment by UlfNorell** [comment]
Fixed by #5118.
