### ISSUE TITLE
Default build fails for ICU version 68 upward

### ISSUE THREAD

**Issue by jaycech3n** [agda/agda#5120]
(Arch Linux, ICU packages icu-68.2-1, lib32-icu-68.2-1; current Agda master)

Just a report that the text-icu-0.7.0.1 package will fail to build if you have ICU version 68.1 upwards due to a change in header definitions, see [here](https://github.com/unicode-org/icu/pull/1282), [here](https://unicode-org.atlassian.net/browse/ICU-21267).

Disabling cluster counting let me build again.

**Comment by andreasabel** [comment]
There seems to be a PR upstream to fix this: https://github.com/haskell/text-icu/pull/48

**Comment by L-TChen** [comment]
I doubt that this will be fixed, since the last commit is on 22 May 2017.

**Comment by andreasabel** [comment]
See https://github.com/haskell/text-icu/issues/30#issuecomment-757538841 : I emailed to haskell-libraries to inquire about the maintainer Bryan O'Sullivan.

**Comment by L-TChen** [comment]
@jaycech3n now running `make install-bin` uses the patched `text-icu` so it should work again.

**Comment by andreasabel** [comment]
Looks like after #5380 text-icu is broken again on CI.
