### ISSUE TITLE
Remove duplicated definition of `singleton` for non-empty lists

### ISSUE THREAD

**Issue by asr** [agda/agda#5122]
@andreasabel, was there a specific reason for adding the `singleton` function for non-empty lists in 9ad1a4a9ff91d4ad0df04c321a09e3354687ddcb, i.e. https://github.com/agda/agda/blob/dd784dde31dcd948c751a2612e5a8300f9fa451a/src/full/Agda/Utils/List1.hs#L53-L54

instead of using the definition from `Agda.Utils.Singleton.hs`?

I noted the duplicate definition while working in #4955 because in GHC 9.0.1-rc1 was added the `singleton` function for lists and non-empty lists.

**Comment by asr** [comment]
I didn't find any problem after removing the definition from `Agda.Utils.List1.hs`.

**Comment by asr** [comment]
Closed by #5123.

**Comment by asr** [comment]
Closed by #5123.

**Comment by andreasabel** [comment]
> @andreasabel, was there a specific reason for adding the `singleton` function for non-empty lists 

Well, to enable the qualified `List1.singleton`.

> instead of using the definition from `Agda.Utils.Singleton.hs`?

It is of course fine to use the polymorphic version `singleton`.

> I noted the duplicate definition while working in #4955 because in GHC 9.0.1-rc1 was added the `singleton` function for lists and non-empty lists.

Great!, then my definition is of course obsolete.
