### ISSUE TITLE
getDefinition sometimes loses patterns

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#5128]
Here's a minimal example:

```agda
open import Agda.Builtin.Unit
open import Agda.Builtin.Sigma
open import Agda.Builtin.List
open import Agda.Builtin.Equality
open import Agda.Builtin.Reflection renaming (bindTC to _>>=_)

macro
  quoteDef : Name → Term → TC ⊤
  quoteDef f hole = (getDefinition f >>= quoteTC) >>= unify hole

postulate
  A : Set
  B : A → Set

foo : (x : A) → B x → B x
foo x y = y

test : quoteDef foo ≡
  function
    (clause
     (("x" , arg (arg-info visible relevant) (def (quote A) [])) ∷
      ("y" , arg (arg-info visible relevant) (def (quote B) (arg (arg-info visible relevant) (var 0 []) ∷ [])))
      ∷ [])
     (arg (arg-info visible relevant) (var 0) ∷ [])
     (var 0 [])
     ∷ [])
test = refl
```

This file checks, but there should be one more pattern variable in the reflected clause ("x" is there in the telescope but there is no `var 1` in the list of patterns). Strangely, the problem occurs only under very specific circumstances: if the type of `y` is not dependent then the reflected patterns are correct.

I've tested on a recent build from master and on 2.6.1, both have the same issue.

**Comment by UlfNorell** [comment]
The problem is the projection-like optimisation. For projection-like functions `getDefinition` needs to fill in the dropped lhs vars. We do this correctly for applications, so it should be straightforward. I'll see what I can do.

**Comment by UlfNorell** [comment]
The first fix revealed another bug: clause telescopes were incorrect for module application wrappers of projections and projection-like functions. This was actually visible in the test case for #2226.
