### ISSUE TITLE
Agda fails test Issue4967

### ISSUE THREAD

**Issue by mouse07410** [agda/agda#5131]
MacOS-10.15.7, GHC-8.10.3, Cabal-3.2.0.0, current master.

<img width="555" alt="Screen Shot 2021-01-14 at 18 05 48" src="https://user-images.githubusercontent.com/5923577/104659906-89fa5e00-5693-11eb-8f7c-887371d5b4aa.png">

Complete logs:
[make-out-2021-01-14.txt](https://github.com/agda/agda/files/5817445/make-out-2021-01-14.txt)
[make-test-2021-01-14.txt](https://github.com/agda/agda/files/5817446/make-test-2021-01-14.txt)

**Comment by L-TChen** [comment]
That's odd. It runs without any problem on my machine (macOS 11.1, ghc 8.10.3 with stack) and also on the CI/CD platform provided GitHub ([log](https://github.com/agda/agda/runs/1690495133?check_suite_focus=true)).

Your build log doesn't look right to me, since there shouldn't be any warning unless you enable some flags globally.

Can you check the GHC version, the version of Agda (is it clean or dirty?), perhaps update the cabal database and clean the cabal cache?

**Comment by UlfNorell** [comment]
This is an issue with test suite dependencies. If I remember correctly if you run `make bugs` once everything will be ok.

**Comment by mouse07410** [comment]
Alas, running `make bugs` does not seem to alleviate this problem. The run still ends up with one failing test - "Issue4967":
<img width="678" alt="Screen Shot 2021-01-15 at 08 13 20" src="https://user-images.githubusercontent.com/5923577/104731491-c2d51a00-5709-11eb-8d4b-1458037c7938.png">

> Can you check the GHC version, the version of Agda (is it clean or dirty?), perhaps update the cabal database and clean the cabal cache?

- GHC-8.10.3
- Agda pulled from this repo via `git clone https://github.com/agda/agda.git --recurse-submodules`
- Cabal cache: how do I clean it? Also, any update on moving Agda build to `cabal v2`?

Almost forgot:
> there shouldn't be any warning unless you enable some flags globally

My environment builds everything dynamic:
- `shared: True` and `executable-dynamic: True` for Cabal
- `-dynamic` for Stack

But that shouldn't change anything.

**Comment by gallais** [comment]
I see these from time to time too but they disappear after a re-run
of the test suite like Ulf suggested.

**Comment by L-TChen** [comment]
> Cabal cache: how do I clean it? Also, any update on moving Agda build to cabal v2?

Although `Makefile` is not yet updated, the nix-style cabal is tested ([log](https://github.com/agda/agda/runs/1690117282?check_suite_focus=true)).

**Comment by mouse07410** [comment]
> I see these from time to time too but they disappear after a re-run of the test suite like Ulf suggested.

Interesting. Doing `make bugs` **a few times** indeed alleviated the "Issue4967" problem.

And brought me to the LaTeX-related problems *in the test suite* - for which I'll open a new issue #5133.
