### ISSUE TITLE
The repl crashes for expression \ x -> x

### ISSUE THREAD

**Issue by ice1000** [agda/agda#5132]
```
agda --interactive
                 _
   ____         | |
  / __ \        | |
 | |__| |___  __| | ___
 |  __  / _ \/ _  |/ __\     Agda Interactive
 | |  |/ /_\ \/_| / /_| \
 |_|  |\___  /____\_____/    Type :? for help.
        __/ /
        \__/

The interactive mode is no longer under active development. Use at your own risk.
Main> \ x -> x
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full\Agda\TypeChecking\Monad\Builtin.hs:449:31 in Agda-2.6.2-inplace:Agda.TypeChecking.Monad.Builtin
```

Agda version `2.6.2-c540034`

**Comment by jespercockx** [comment]
> The interactive mode is no longer under active development. Use at your own risk.

It seems things have degraded quite harshly since development of this feature was dropped.

**Comment by ice1000** [comment]
> > The interactive mode is no longer under active development. Use at your own risk.
> 
> It seems things have degraded quite harshly since development of this feature was dropped.

I know, but it seems to be related to error handling so I'm posting this

**Comment by ice1000** [comment]
Seems that all you need to do is to have builtinSet

**Comment by andreasabel** [comment]
> It seems things have degraded quite harshly since development of this feature was dropped.

Harsh degradation could be prevented by adding a few more test cases in `test/interactive`.

(Btw. maybe we should rename `interactive` to `repl` to distance it from `interaction`.  But then we should maybe deprecate `--interactive` in favor of `--repl` as well ...)

**Comment by andreasabel** [comment]
Likely broken by PR #4629.  Could maybe be fixed by running these declarations: 
https://github.com/agda/agda/blob/ad8a833ba65ca8be144ed81c2e48c8edd8752f57/src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs#L1346-L1358

UPDATE: indeed, this fixed it.

**Comment by ice1000** [comment]
Cool!
