### ISSUE TITLE
Is agda-licenses obsolete?

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5134]
The `agda-licences` tool requires Cabal-2.0 (limiting to ghc <= 8.6 it seems) to build and needs Agda to be build with Cabal-2.0, too, to run:
```
$ dist-newstyle/build/x86_64-osx/ghc-8.6.4/agda-licences-0.1/x/agda-licences/build/agda-licences/agda-licences ../../dist-2.6.2-ghc-8.10.3-no-code/
agda-licences: Saved package config file is outdated:
• the Cabal version changed from Cabal-3.2.1.0 to Cabal-2.0.1.1
• the compiler changed from ghc-8.10 to ghc-8.6
Re-run the 'configure' command.
```

I recently added a economic way to get the licenses using the `cabal-plan` tool, see [doc/license-report/README](https://github.com/agda/agda/blob/d6b08db36d68c87b97d37147b0b7a100ae62a073/doc/license-report/README.md).

Could we retire `agda-licences` from the codebase?  (Note that it is still picked up by e.g. `stack init`.)
Ping @nad

**Comment by nad** [comment]
If there is some other tool that supersedes `agda-licences`, then I don't mind if it is removed.

I tried to run `make` in `doc/license-report`, and got the following error:
```
cabal-plan: user error (missing "[...]/dist-newstyle" folder; do you need to run 'cabal new-build'?)
```

**Comment by andreasabel** [comment]
Yes, I suppose you have to run `cabal v2-build` for agda first.
For curiosity, would `cabal v2-configure` also suffice?

**Comment by andreasabel** [comment]
> For curiosity, would `cabal v2-configure` also suffice?

To answer my own question: yes!  (And that makes a lot of sense.)

**Comment by jespercockx** [comment]
I assume this should have the 2.6.2 milestone?
