### ISSUE TITLE
Release 2.6.1.3 because a hackage revision of 2.6.1.2 is not possible

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5136]
2.6.1.2 is already outdated since it does not support GHC 8.10.3:
https://github.com/agda/agda/blob/a63abbfda72f637a868855d06c58156d3d0461bd/Agda.cabal#L245-L246

- The problem is that we have no _unconditional_ constraint for `transformers`, so when none of the conditions on ghc is satisfied, cabal simply does not include transformers into the build plan.
- I cannot make a revision on hackage since modification of conditional constraints is not supported, and addition of new dependencies is also not supported.

It seems a new release is thus needed, just for the sake of relaxing that bound.

We should structure the cabal file better so that revisions are possible:
- include a basic constraint on `transformers` into the list
- in conditionals, only impose _additional_ constraints for older ghc versions

This way, we can relax the main constraints in revisions, but still keep the additional requirements for older ghc versions.

Along these lines, we should also have no `else` clauses, but have a basic dependency (here for `text`) with additional restrictions for certain ghc versions:
https://github.com/agda/agda/blob/a63abbfda72f637a868855d06c58156d3d0461bd/Agda.cabal#L258-L259

**Comment by asr** [comment]
The constraint in `transformers` is due to #2983 as pointed out in `Agda.cabal`. I don't see as follow your suggestion without breaking the fix for #2983.

 The modification of constraints in Hackage is not a problem of Agda. I suggest fill an request.

**Comment by UlfNorell** [comment]
Not that it helps, but for the 2.6.1.1 release I changed the constraint to
https://github.com/agda/agda/blob/fce01db8f9d2ceb9c3a4aa179330ea4aa7587a71/Agda.cabal#L246-L247
for this very reason.

**Comment by andreasabel** [comment]
> Not that it helps, but for the 2.6.1.1 release I changed the constraint to ...
> for this very reason.

Ah, and me rookie fell into the trap.

**Comment by asr** [comment]
I'll prepare the release of 2.6.1.3 after finishing the release of 2.6.1.2 (#4749).

**Comment by andreasabel** [comment]
> I'll prepare the release of 2.6.1.3 after finishing the release of 2.6.1.2 (#4749).

Great, thanks!  Then maybe I can finally get Agda into stackage...

**Comment by augustss** [comment]
Is there an ETA for 2.6.1.3?

**Comment by asr** [comment]
I'm planning to make the release this weekend.

**Comment by asr** [comment]
>     * The problem is that we have no _unconditional_ constraint for `transformers`, so when none of the conditions on ghc is satisfied, cabal simply does not include transformers into the build plan.

I fixed the problem in a37e79effa80271566a5759fe4542cca80db87f1.

**Comment by asr** [comment]
@andreasabel [wrote](https://github.com/agda/agda/issues/4749#issuecomment-717792275)

> Indeed, CI was not set up for GHC 8.10 (which was the point of releasing 2.6.1.1). I made some attempts to copy the more recent CI infrastructure to the release branch, but it does not work out-of-the-box, and I do not have the time (and knowledge) to fix this. A lot of effort has gone into the CI since 2.6.1, and did not appear to me a simple cherry-picking (I might be wrong). I rather tried to copy the CI stuff over from the master branch to the release branch and start cutting away unnecessary stuff, but to finish this will likely require many iterations of pushing-and-waiting-for-CI.

I had the same problem (not a big surprise), so I'll also test compilation on my machine.

**Comment by asr** [comment]
I'm testing the Hackage candidate with `stack` and different version of GHC on Linux right now.

For getting the Hackage candidate you can use
```bash
$ cabal get https://hackage.haskell.org/package/Agda-2.6.1.3/candidate/Agda-2.6.1.3.tar.gz
```

Could someone test the installation on macOS and Windows, please.

**Comment by asr** [comment]
I'll continue with the release of 2.6.1.3 supporting GHC 8.10.3. I guess 2.6.1.3 also compiles with GHC 8.10.4 (untested).

**Comment by asr** [comment]
2.6.1.3 builds with GHC 8.10.4 as expected.

**Comment by asr** [comment]
Done.

**Comment by andreasabel** [comment]
Great, big thanks, Andres!
