### ISSUE TITLE
Release 2.6.2

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5154]
First meeting 2021-01-27 Ulf, Nisse, Andrea, Jesper, Victor, Andreas

Release plan
============

Meet weekly Wed 2.30pm until release.

Triage until 2021-02-10
------------------------

- go through 'no milestone' issues and assign to 2.6.2 or to 2.6.3 or icebox
- go through 2.6.2 issues and bump to 2.6.3 or icebox
- assign 2.6.2 issues to someone aggressively or use release-blocker label

Prioritization
-------------

1. build problems
2. regressions on master (7)

   - in old features
   - in new features

3. regressions in recent releases of Agda

Release by 2021-04-01 (goal)

Discussion points:
------------------

- disable unfinished features?
- ok to release experimental features with bugs but with warning in the release notes

**Comment by asr** [comment]
I think there shouldn't be closed issues assigned  to `icebox` milestone. I'll reassign them to `2.6.2`.

**Comment by jespercockx** [comment]
I've posted some reminders in some of the issues that are still open. If there's no response I'll start bumping the non-critical ones in a few days.

**Comment by jespercockx** [comment]
It looks like we made quite a bit of progress in the last couple of weeks, great work everyone! There's just 10 open issues at the moment. Looking through the list, I think the only one that is really critical is https://github.com/agda/agda/issues/4959 (and perhaps https://github.com/agda/agda/issues/5378). Maybe once those are solved, we could prepare a first release candidate so people can test out the new release.

**Comment by asr** [comment]
> Maybe once those are solved, we could prepare a first release candidate so people can test out the new release.

I'll prepare the release candidate after those issues are closed.

**Comment by andreasabel** [comment]
The deadline for the release of 2.6.2 is [AIM XXXIV](https://wiki.portal.chalmers.se/agda/Main/AIMXXXIV).  I suggest we try to release by June 1st (Milestone 2.6.2 deadline).

**Comment by andreasabel** [comment]
I think we can start with a first release candidate. 
Issue #4613 is still open, but I don't know if anyone will work on this...

**Comment by asr** [comment]
I'll prepare the release candidate.

Could someone to add a `Highlights` section to the CHANGELOG, please (something like [Agda 2.6.0 Highlights]( https://github.com/agda/agda/blob/ed6730a1717a0e3ddc25a75de0c2e109371391c7/doc/release-notes/2.6.0.md#highlights)).

**Comment by jespercockx** [comment]
I've added the highlights section, and bumped the milestone on the two remaining open issues. So we are all set for the release (candidate)!

**Comment by asr** [comment]
Starting the preparation for the release candidate...

**Comment by asr** [comment]
> The deadline for the release of 2.6.2 is [AIM XXXIV](https://wiki.portal.chalmers.se/agda/Main/AIMXXXIV).  I suggest we try to release by June 1st (Milestone 2.6.2 deadline).

I'm planning to make the release on June 1st.

**Comment by asr** [comment]
I *don't want* to frozen `master` while 2.6.2 is released. So, if you pushed some commit to `master` which also should be in 2.6.2, please cherry-pick the commit into the `release-2.6.2` branch.

**Comment by jespercockx** [comment]
I'm working on addressing the comment by @nad at https://github.com/agda/agda/pull/5386#issuecomment-848785598, I'll cherry-pick it once it's finished.

Update: it's done now.

**Comment by nad** [comment]
I noticed that an entry in the changelog was out of date. I've pushed a fix to both `master` and `release-2.6.2`.

**Comment by jespercockx** [comment]
There were a few issues that came up with the first RC that are all fixed now (well, except for https://github.com/agda/agda/issues/5419 which is about the licenses), so perhaps we could prepare a second release candidate now?

**Comment by nad** [comment]
I'd like to merge [another](https://github.com/agda/agda/pull/5435) bug fix first.

**Comment by asr** [comment]
I'll release RC2. The `release-2.6.2` branch is frozen.

**Comment by nad** [comment]
@asr, we have now started adding new features to the `master` branch, so I renamed `CHANGELOG.md` to `doc/release-notes/2.6.2.md`.

**Comment by jespercockx** [comment]
The second release candidate has been out for over a week now and there haven't been any major complaints. Is there anything that we should still do before the release? Is there anything we should still do to add support for GHC 8.10.5 (https://github.com/agda/agda/issues/5436)? If not, I propose we do the release.

**Comment by asr** [comment]
> Is there anything we should still do to add support for GHC 8.10.5 (https://github.com/agda/agda/issues/5436)?

Yes. Everything in https://github.com/agda/agda/blob/ecdeda1c1e3bb8d178efa4b365aa02399375495c/notes/ghc-releases.md. I'm starting to work in #5436.

**Comment by asr** [comment]
I'm waiting for a fix of #5419 to make the release.

**Comment by nad** [comment]
I've closed #5419.

**Comment by asr** [comment]
Starting the release of 2.6.2.

**Comment by asr** [comment]
Great job everyone!

**Comment by jespercockx** [comment]
Thanks @asr and everyone who made this release possible!
