### ISSUE TITLE
`mutual` is deprecated in doc

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda#5176]
According to @UlfNorell , `mutual` is not deprecated, but the doc says otherwise: https://agda.readthedocs.io/en/v2.6.1.2/language/mutual-recursion.html

The text is quite organized so it doesn't seem a typo. Wondering what happened.

**Comment by jespercockx** [comment]
It's deprecated in the sense that `mutual` is the "old" way of doing things, the "new" way of mutual definitions works without a keyword (by simply declaring things before they are used). However, there are no plans to remove the old "mutual" blocks (and sometimes they are actually more powerful than the new style), so to avoid confusion it'd be better to remove the word 'deprecated' from the manual.

**Comment by gallais** [comment]
> so to avoid confusion it'd be better to remove the word 'deprecated' from the manual.

AFAICT the manual does not use the word deprecated. :smile:

**Comment by ajrouvoet** [comment]
If there is no intention to get rid of `mutual` blocks then the distinction of old vs new is not useful in documentation.

Although the word 'deprecated' is not used, it might has well been:

![image](https://user-images.githubusercontent.com/475738/107119096-997d5900-6885-11eb-880e-b281130b83dd.png)

**Comment by HuStmpHrrr** [comment]
yes, it seems I invented the word "deprecated", but indeed, the note gives me that impression. also I was told by someone else that we shouldn't  use `mutual` anymore because the doc asks to avoid it.

**Comment by andreasabel** [comment]
`mutual` is likely here to stay.  At least the new "mutual block sans keyword" isn't the perfect solution either, because it doesn't allow the user to declare where the mutual block should end.  Being able to outright limit the mutual block is both beneficial for documentation and stability (since inference algorithms can change).

So we should fix the docs, removing the note.
