### ISSUE TITLE
rewrite can't handle x == f x equalities

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#520]
``` agda
module Rewrite where

open import Relation.Binary.PropositionalEquality
data X : Set where
  a b : X

f : X -> X
f a = a
f b = b

f-id : ∀ x -> x ≡ f x
f-id a = refl
f-id b = refl

postulate
  P : X -> Set
  e : X
  p : P (f e)


proof : P e
proof rewrite f-id e = p

{-
Rewrite.agda:22,1-31
w != f w of type X
when checking that the pattern refl has type w ≡ f w
-}
```

It'd be great if the above could typecheck, since i can't find any nice workaround, especially when P and e are larger compound expressions.

Original issue reported on code.google.com by `sanzhi...@gmail.com` on 14 Nov 2011 at 3:31

**Comment by andreasabel** [comment]
I implemented Andrea's idea.

**Comment by andreasabel** [comment]
This has already been released in 2.4.2.5.
I cannot created milestone 2.4.2.5 as it has existed at some point and got deleted.

**Comment by asr** [comment]
> This has already been released in 2.4.2.5.

Really? The release was on 2015-12-18 and you fixed the issue on 2015-12-25.

> I cannot created milestone 2.4.2.5 as it has existed at some point and got deleted.

The milestone is closed. You can open it, label an issue and close it again.

**Comment by andreasabel** [comment]
You are right. I think I fixed #520 while I had not pulled the release, so I put the description in the wrong section in CHANGELOG.  Fixed.

**Comment by asr** [comment]
> The milestone is closed. You can open it, label an issue and close it again.

Correction: You don't need to open/close the milestone. Just choose the closed milestone from the milestone menu.

**Comment by andreasabel** [comment]
github does not offer me Milestone 2.4.2.5, only 2.4.4 and 2.4.2.6.  If I type 2.4.2.5 nevertheless, it suggests to create this milestone, and then reports an error:

```
 Something went wrong with that request. Please try again. 
```

So I guess what you said before is true: open m., assign issue to m., close m.

**Comment by asr** [comment]
I just changed the milestone without problems. You need to choose the 2.4.2.5 milestone in the 'Closed' tab from the Milestone menu in the right.

**Comment by andreasabel** [comment]
Ah, thanks for this eye-opener!  I must have been blind. ;)
