### ISSUE TITLE
acmart examples in (user-manual) fail to build with latest TeXLive

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5205]
Salvaged from https://github.com/agda/agda/issues/5133#issuecomment-761916315:

I am getting errors when pdflatexing/xelatexing the acmart-* examples in `test/LaTeXAndHTML/user-manual`.  I have this version of acmart.cls:
```
[2020/11/15 v1.75 Typesetting articles for the Association for Computing Machinery]
```
Error looks like:
```
! Undefined control sequence.
\@acmBooktitle ...ceedings of \acmConference@name 
                                                  \ifx \acmConference@name \...
l.94 \end{document}
```

**Comment by asr** [comment]
Note that the error is not in our side. For example, the file

```latex
\documentclass{acmart}

\begin{document}
Test.
\end{document}
```

generates the same error using the same version of `acmart.cls`.

**Comment by andreasabel** [comment]
Thanks for fixing!

**Comment by andreasabel** [comment]
Apparently, the bug was also fixed upstream in acmart now: https://github.com/borisveytsman/acmart/issues/421
