### ISSUE TITLE
Internal error when splitting on a proposition

### ISSUE THREAD

**Issue by ice1000** [agda/agda#5210]
```agda
{-# OPTIONS --prop #-}
open import Data.Nat
data T : ℕ → Prop where
  To : T zero
  Tn : ∀ n → T n

ummm : ∀ n → T n → {!   !}
ummm n t = {! t  !}
```

Splitting this variable triggers `__IMPOSSIBLE__`. Using the nightly build on GitHub release.

EDIT: added necessary imports and pragmas.

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/107918922-81a08600-6fa5-11eb-9e33-fcf6f7b4b643.png)

**Comment by ice1000** [comment]
Is this already fixed? Since the nightly release was created 12 days ago.

**Comment by UlfNorell** [comment]
Impossible is here: https://github.com/agda/agda/blob/be0040f10498aab7f71fe7ecafbc272bc0024c7f/src/full/Agda/TypeChecking/Coverage.hs#L1452-L1453

The coverage checker cannot handle the sort of the target type being unknown when splitting on a proposition. The sort matters because matching on propositions are fine as long as the result is also a proposition.

**Comment by UlfNorell** [comment]
> Is this already fixed? Since the nightly release was created 12 days ago.

Not as far as I can see. Why do you think that it might be fixed?

**Comment by ice1000** [comment]
Yes, so we could probably raise an error similar to 'I don't know if I can do this because I want the goal type to live in Prop'

**Comment by ice1000** [comment]
It's a situation similar to 'I don't know if there should be the case Bla, because I got stuck on the following unification problem'

**Comment by jespercockx** [comment]
> Impossible is here:
> 
> https://github.com/agda/agda/blob/be0040f10498aab7f71fe7ecafbc272bc0024c7f/src/full/Agda/TypeChecking/Coverage.hs#L1452-L1453
> 
> The coverage checker cannot handle the sort of the target type being unknown when splitting on a proposition. The sort matters because matching on propositions are fine as long as the result is also a proposition.

Err, isn't this check completely superfluous? The same check is done later by `checkSortOfSplitVar`, only this time there is a proper error message in case the sort of the target is blocked. So I'd be tempted to just remove those two lines.

**Comment by ice1000** [comment]
> > Is this already fixed? Since the nightly release was created 12 days ago.
> 
> Not as far as I can see. Why do you think that it might be fixed?

Sometimes I create issue about some known thing.... I was using a 12 days ago Agda so I think it's possible that it's fixed :thinking:
