### ISSUE TITLE
Inefficient code in Setup.hs

### ISSUE THREAD

**Issue by nad** [agda/agda#5225]
We type-check the builtin modules one by one, using `--ignore-all-interfaces`:

  https://github.com/agda/agda/blob/e564b701e81037875907b172ff4db19fec2f658a/Setup.hs#L110-L114

This means that some modules are type-checked repeatedly. Related: #4151.

**Comment by gallais** [comment]
I think this is related to #3950: we want to forcefully retypecheck
the files no matter whether there is an existing `.agdai` hence the
option but cannot call `agda` on all of the files at once.

An alternative would be to first `rm` the existing `.agdai` files
but I'm always a bit uneasy about writing code that automatically
deletes files...

**Comment by UlfNorell** [comment]
How much time are we talking about here? How long does it take to type check things with the current setup and how long would it take to check a `Agda.Builtin.Everything` with `--ignore-all-interfaces`?

**Comment by nad** [comment]
I tested this now on my machine: About 13 s with the current setup, and less than 3 s with two "Everything" files (one for the Cubical Agda modules plus `Agda.Builtin.Sigma`, and one with the rest).

**Comment by UlfNorell** [comment]
Thanks! That does indeed seem like enough of a gain to make it worth spending some effort here.
