### ISSUE TITLE
When `stack.yaml` exists, `make` calls `stack`, even on `make debug`

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5230]
Without `stack.yaml` it works as expected:
```
$ make debug
AGDA_BIN              = ...
... 
```

After `touch stack.yaml`:
```
$ make debug
Could not parse '/Users/abel/agda-erasure/stack.yaml':
Aeson exception:
Error in $: parsing ProjectAndConfigMonoid failed, expected Object, but encountered Null
See http://docs.haskellstack.org/en/stable/yaml_configuration/
Could not parse '/Users/abel/agda-erasure/stack.yaml':
Aeson exception:
Error in $: parsing ProjectAndConfigMonoid failed, expected Object, but encountered Null
See http://docs.haskellstack.org/en/stable/yaml_configuration/
AGDA_BIN              = ...
...
```

After `cp stack-8.10.4.yaml stack.yaml`:
```
$ make debug
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Preparing to download ghc-8.10.4 ...
ghc-8.10.4: download has begun
ghc-8.10.4:  233.09 KiB / 265.00 MiB (  0.09%) downloaded...
^C
```

**Comment by asr** [comment]
I just think that support both Cabal and stack in the same `Makefile`, for all our tool-chain, is going to be very very difficult. We should think in split the `Makefile` in `Makefile.cabal` and `Makefile.stack`, so every one (including CI) can choose the `Makefile` via something like `ln -s Makefile.tool Makefile`.

**Comment by asr** [comment]
I couldn't reproduce the problem:

```
$ ln -s stack-8.10.4.yaml stack.yaml
$ make debug

AGDA_BIN              = /.../dist-2.6.2-ghc-8.10.4/build/agda/agda
AGDA_TESTS_BIN        = /.../dist-2.6.2-ghc-8.10.4/build/agda-tests/agda-tests
AGDA_TESTS_OPTIONS    = -i -j2
BUILD_DIR             = ./dist-2.6.2-ghc-8.10.4
CABAL_BUILD_CMD       = v1-build
CABAL_CLEAN_CMD       = v1-clean
CABAL                 = cabal
CABAL_CONFIGURE_CMD   = v1-configure
CABAL_CONFIGURE_OPTS  = --builddir=./dist-2.6.2-ghc-8.10.4 --enable-tests -j1 --disable-library-profiling  -fenable-cluster-counting --ghc-options=+RTS -M6G -RTS 
CABAL_HADDOCK_CMD     = v1-haddock
CABAL_INSTALL_CMD     = v1-install
CABAL_INSTALL_OPTS    =  -fenable-cluster-counting --ghc-options=+RTS -M6G -RTS 
CABAL_OPTS            = 
GHC_VERSION           = 8.10
PARALLEL_TESTS        = 2
STACK                 = stack
STACK_INSTALL_OPTS    =  --flag Agda:enable-cluster-counting --ghc-options +RTS -M6G -RTS 

Run `make -pq` to get a detailed report.
```

**Comment by andreasabel** [comment]
Well, this doesn't prove anything yet, because if `stack` has the relevant `ghc` already downloaded (in your case `ghc-8.10.4`) it will be silent (also on my machine).

Try to put garbage into `stack.yaml` so it would give a parse error.

**Comment by asr** [comment]
Ah, I see.

**Comment by andreasabel** [comment]
I tried hard to locate the offending call to `stack` in the `Makefile`, but couldn't find it.  Maybe someone with better eyes can have a look, restating,
> why `make debug` calls `stack` if `stack.yaml` exists.

**Comment by asr** [comment]
> I tried hard to locate the offending call to `stack` in the `Makefile`, but couldn't find it.

`Makefile` includes `mk/paths.mk` and it includes `mk/ghc.mk` which runs `stack ghc` for getting the version of GHC if `stack.yaml` exists.

**Comment by andreasabel** [comment]
Thanks, @asr!  
I found relevant docs at https://docs.haskellstack.org/en/v2.5.1/faq/#what-version-of-ghc-is-used-when-i-run-something-like-stack-ghci.  So the content of `stack.yaml` determines the GHC version, and if that version is not installed, `stack` will download it.

That's quite a convoluted way to ask for the GHC version: 
- `stack` infers it from `stack.yaml`
- and downloads the respective version of GHC
- in order to run it
- so that it can print its version!

;-P

We could also parse it from `stack query`:
```
$ stack query
Stack has not been tested with ...
compiler:
  wanted: ghc-9.0.1
  actual: ghc-9.0.1
locals:
  Agda:
    path: /Users/abel/agda-erasure/
    version: 2.6.2
  size-solver:
    ...
```
This `awk` one-liner works for me:
```
stack query | awk 'match ($0, /actual: ghc-([0-9]+\.[0-9]+\.[0-9]+)/, ver) { print (ver[1]); }'
```
I'll try this, and hope it does not break CI.
