### ISSUE TITLE
No highlighting in dot patterns 

### ISSUE THREAD

**Issue by ajrouvoet** [agda/agda#5233]
I was trying to explain dependent pattern matching and forcing in the introduction of my thesis by revealing some dot patterns:

```agda
append : ∀ {A n m} → Vec A n → Vec A m → Vec A (n + m)
append {n = .zero}   []        ys  = ys
append {n = .suc k}  (x ∷ xs)  ys  = x ∷ (append xs ys)
```

As I understand it, `.suc` and `.zero` should both be read as forced constructor names by Agda.

Instead, Agda only highlights and hyperlinks `suc`, while `zero` appears to be checked as a variable name in both the editor and produced LaTeX:

![image](https://user-images.githubusercontent.com/475738/108861409-7970c800-75ef-11eb-9ec5-6704a1c5e39a.png)

This is `Agda version 2.6.2-155582f`

PS: If I remove the `.` and just write `zero` then it is checked as a constructor name, so everything required is in scope.

**Comment by andreasabel** [comment]
Well, `.zero` is syntactically ambiguous and could also mean `.(zero)`, that is, expression `zero` in a dot pattern.  But even then, it should be highlighted as constructor, since a variable `zero` is not in scope here.

I can confirm that constructors in dot patterns are not highlighted.
```agda
open import Agda.Builtin.Nat

data Vec (A : Set) : Nat → Set where
  nil  : Vec A zero
  cons : (n : Nat) (x : A) (xs : Vec A n) → Vec A (suc n)

append : ∀ {A n m} → Vec A n → Vec A m → Vec A (n + m)
append {n = .(zero)}   nil            ys  = ys
append {n = .(suc k)}  (cons k x xs)  ys  = cons _ x (append xs ys)
```
Neither `zero` nor `suc` is highlighted here.

This isn't specific to constructors:
```agda
data P : Set₁ → Set where
  isSet : P Set

test : (A : Set₁) → P A → Set
test .Set isSet = Nat
```
`Set` in `.Set` is not highlighted.

Worked fine in 2.6.1.
Related (ancient) issue: #976.

**Comment by andreasabel** [comment]
Possibly I introduced it when fixing #2038. 
No highlighting is produced for the expression: https://github.com/agda/agda/blob/72e3aac0d63f8a53ca77a8dce2e339363c550334/src/full/Agda/Interaction/Highlighting/FromAbstract.hs#L271-L273

**Comment by ajrouvoet** [comment]
Thank you for having a look and diagnosing the issue.

Just for my understanding: although syntactically ambiguous, `.(zero)` and `(.zero)` do mean the exact same, right?

**Comment by andreasabel** [comment]
A fix is forthcoming, but CI is broken, so after fixing CI I will open the PR.

> Just for my understanding: although syntactically ambiguous, `.(zero)` and `(.zero)` do mean the exact same, right?

Yes, this is why the ambiguity is ok.
