### ISSUE TITLE
`__IMPOSSIBLE__` from Agda.TypeChecking.Substitute

### ISSUE THREAD

**Issue by cnassau** [agda/agda#5237]
While playing with my own version of cubical/Cubical/HITs/Torus/Base.agda on master, a careless choice of variable names triggered an "__IMPOSSIBLE__" warning from agda: this is my file "torus-bug.agda":
```agda
{-# OPTIONS --cubical --without-K  --safe #-}
open import Cubical.Core.Everything
open import Cubical.Data.Sigma using (_×_)
data S1 : Set where
  base : S1
  loop : base ≡ base
data Torus : Set where
  point : Torus
  line1 : point ≡ point
  line2 : point ≡ point
  square : PathP (λ i → line1 i ≡ line1 i) line2 line2
t2c : Torus → S1 × S1
t2c point = ( base , base )
t2c (line1 i) = ( loop i , base )
t2c (line2 i) = ( base , loop i )
t2c (square i1 i2) = ( loop i1 , loop i2 )
```
Running `agda -c torus-bug.agda` gives 
> Checking torus-bug (/home/cn/agda/torus-bug.agda).
> An internal error has occurred. Please report this as a bug.
> Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/Substitute.hs:1146:14 in Agda-2.6.2-6yVYy20oGlp59nHZ0UJ5GK:Agda.TypeChecking.Substitute

The code compiles if the variables in the last line are changed from i1, i2 to i, j

**Comment by andreasabel** [comment]
I suppose `i1` is interpreted as endpoint of the interval, which you cannot match on.  Could be a missing check in the left-hand side checker.
