### ISSUE TITLE
Cannot define functions with implicit arguments using reflection

### ISSUE THREAD

**Issue by flupe** [agda/agda#5249]
I'm currently writing code that produces elements of some record type using reflection.
In said record types, _some fields are functions whose first argument is implicit_.

However I've been unable to define these functions with reflection, as Agda tells me the implicit argument is not in scope. If I make the argument explicit in the record definition,
and change every `Arg _` to `visible` in the function `Clause`, everything works fine.

Here is a minimal example:
- In `Box1`, the first argument of the field is explicit and there is no issue when defining an element with reflection (See example 1).
- In `Box2`, the first argument is now implicit, and if we use the same function definition (where visible arguments are now hidden), we're unable to proceed.
- Even if we try to manually "make the first argument implicit" given a function with an explicit argument, it fails. Which suggests it's in the internal reflection machinery that implicit arguments are made inaccessible.

Is this a bug or am I just using reflection wrong?

```agda
open import Agda.Builtin.Reflection

open import Function.Base
open import Agda.Builtin.Sigma
open import Agda.Builtin.Unit
open import Agda.Builtin.List

return : ∀ {A : Set} → A → TC A
return = returnTC

_>>=_ : ∀ {A B : Set} → TC A → (A → TC B) → TC B
_>>=_ = bindTC

_>>_ : ∀ {A B : Set} → TC A → TC B → TC B
_>>_ x = bindTC x ∘ const

[_] : ∀ {A : Set} → A → List A
[_] = _∷ []

pattern VRA x = arg (arg-info visible relevant) x
pattern HRA x = arg (arg-info hidden  relevant) x

record Box1 : Set₁ where
  constructor mkBox1
  field f : {A : Set} → A → A

record Box2 : Set₁ where
  constructor mkBox2
  field f : (A : Set) → A → A

fclause : (∀ {A : Set} → A → Arg A) → Clause
fclause ARG  =
  clause (("A" , ARG unknown) ∷ ("x" , VRA unknown) ∷ [])
         (ARG (var 1) ∷ VRA (var 0) ∷ [])
         (var 0 [])

implC explC : Clause
implC = fclause HRA
explC = fclause VRA

toImpl : ∀ {A B : Set} → (A → B) → {A} → B
toImpl f {x} = f x

macro
  defImpl : Name → Clause → Term → TC ⊤
  defImpl nm cl hole = do
    f ← freshName "f"
    declareDef (VRA f) unknown -- we let the typechecker infer the expected type
    defineFun f [ cl ]
    unify hole (con nm [ VRA (def f []) ])

-- EXAMPLE 1: if the first is argument is explicit, no issue
testExpl : Box2
testExpl = defImpl mkBox2 explC

-- EXAMPLE 2: if the first is argument is explicit, no issue
-- testImpl : Box1
-- testImpl = defImpl mkBox1 implC

{- "Cannot instantiate the metavriable _80 to solution A → A
    since it contains the variable A which is not in scope of the metavariable when checking
    that the expression reflection.f has type A → A"
 -}

-- EXAMPLE 3: making the argument implicit manually

macro
  defImpl′ : Term → TC ⊤
  defImpl′ hole = do
    f ← freshName "f"
    declareDef (VRA f) unknown -- we let the typechecker infer the expected type
    defineFun f [ explC ]
    unify hole (con (quote mkBox1) [ VRA (def (quote toImpl) [ VRA (def f []) ]) ])

-- testImplManual : Box1
-- testImplManual = defImpl′

{- same error as above -}

```

**Comment by UlfNorell** [comment]
This isn't a reflection problem. Here's what you are doing
```agda
noReflection : Box1
noReflection = mkBox1 f
  where
    f : _
    f {A} x = x
```
This results in the same *cannot instantiate meta* error. There are two reasons why this happens:

- we don't infer an implicit function type for `f` from the lhs, instead the checking of `f` is stuck on implicit argument insertion
- implicit lambdas are eagerly inserted (see #1079), so `mkBox1 f` is really `mkBox1 (λ {A} → f)`. We then try to unify the unknown type of `f` with `A → A` which produces the above error, since the `A` is not in scope of the meta

**Comment by flupe** [comment]
Thank you for the fast reply, I understand better why it couldn't work.
- Is this eager insertion of implicit lambdas documented/motivated somewhere? I don't really understand why this is a wanted behavior.
- Regarding what I'm trying to achieve, it thus seems impossible to provide functions with implicit arguments to record constructors with reflection. I get errors even if I apply `var 0` to the function (assuming implicit argument was bound outside). Can you confirm that it is indeed not possible, and whether a workaround exists?

**Comment by UlfNorell** [comment]
I don't think there's anything super-clear written down on it, but see the issue I linked and the issues merged into it.

Regarding getting it to work, simply providing the type for the function you are defining should do the trick:
```agda
noReflection : Box1
noReflection = mkBox1 f
  where
    f : {A : Set} → A → A
    f {A} x = x
```
