### ISSUE TITLE
Internal error when case splitting pattern-lambda with higher rank type

### ISSUE THREAD

**Issue by JakobBruenker** [agda/agda#5252]
```agda
{-# OPTIONS --cubical #-}
open import Cubical.Foundations.Everything
open import Cubical.Data.Fin

open Iso

foo : (∀ {a : Set} → a) ≃ Fin 2
foo = isoToEquiv λ where
  .fun → ?
  .inv n → ?
  .rightInv → ?
  .leftInv → ?
```
leads to
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/Interaction/MakeCase.hs:83
```
When case splitting on `n` in the second hole.

Agda version: 2.6.1.2

**Comment by andreasabel** [comment]
Shrank this to:
```agda
{-# OPTIONS -v interaction.case:20 #-}

open import Agda.Primitive
open import Agda.Builtin.Sigma

data Empty : Set where

_≃_ : ∀ {ℓ ℓ'} (A : Set ℓ) (B : Set ℓ') → Set (ℓ ⊔ ℓ')
A ≃ B = Σ (A → B) λ f → Empty

record Iso {ℓ ℓ'} (A : Set ℓ) (B : Set ℓ') : Set (ℓ ⊔ ℓ') where
  field
    inv : B → A

postulate
  isoToEquiv : ∀{ℓ ℓ'} {A : Set ℓ} {B : Set ℓ'} → Iso A B → A ≃ B

works : Iso (∀ {a : Set} → a) Empty
works = λ where
  .Iso.inv n → {!n!}

-- something like  (∀ {A : Set} → A)  seems to be necessary to trigger
test : (∀ {A : Set} → A) ≃ Empty
test = isoToEquiv λ where
  .Iso.inv n → {!n!}
```
It seems that some context isn't right, and we get an unbound de Bruijn index.

**Comment by andreasabel** [comment]
Crash here: https://github.com/agda/agda/blob/4f87d3902b5b33a4ad05277b3275170b9efd20e3/src/full/Agda/Interaction/MakeCase.hs#L82

**Comment by andreasabel** [comment]
The problem goes away if we supply the argument `A` to `isoToEquiv`:
```agda
test : (∀ {A : Set} → A) ≃ Empty
test = isoToEquiv {A = {A : Set} → A} λ where
  .Iso.inv n → {!n!}
```

**Comment by jespercockx** [comment]
Maybe it would be better to disable the current hacky code that rechecks a clause before case splitting, and instead just throw an error when the user tries to split on a variable in a forced position. This is not the nicest thing to do, but at least it would be principled.

**Comment by andreasabel** [comment]
Discussion 7 April 2021: Remove the hacky patch (rechecking the abstract clause) but only after the release.
For 2.6.2, replace the `__IMPOSSIBLE__` by a proper error.

**Comment by jespercockx** [comment]
In the end I was sufficienly horrified by the idea of just replacing the `__IMPOSSIBLE__` with an error message and instead I found a way to fix the issue that works well with the hacky workaround for rechecking clauses before splitting. As an added bonus, there is no more de Bruijn arithmetic used in case splitting, just simple lookups.
