### ISSUE TITLE
Declaring records structural rather than nominal?

### ISSUE THREAD

**Issue by JasonGross** [agda/agda#5255]
Is there a way to tell Agda that certain records should be treated as structural rather than nominal?  That is, I would like to be able to fill `test3` with `refl` in the following code given some appropriate annotation on `Functor`:
```agda
module test where
open import Agda.Primitive

record Cat : Set₁ where
  field
    Obj : Set
    Hom : Obj → Obj → Set

record Functor (A B : Cat) : Set where
  open Cat
  field
    fmap : Obj A → Obj B
    hmap : ∀ {s d} → Hom A s d → Hom B (fmap s) (fmap d)

record Unit : Set where
  constructor tt

* : Cat
* = record { Obj = Unit ; Hom = λ _ _ → Unit }

_ᵒᵖ : Cat → Cat
C ᵒᵖ = record { Obj = C.Obj ; Hom = λ s d → C.Hom d s } where
  module C = Cat C

record Σ (A : Set) (B : A → Set) : Set where
  constructor _,_
  field
    pr₁ : A
    pr₂ : B pr₁

FunctorΣ : Cat → Cat → Set
FunctorΣ A B = Σ (Obj A → Obj B)
                 (λ fmap → ∀ {s d} → Hom A s d → Hom B (fmap s) (fmap d)) where
  open Cat

data _≡_ {ℓ : Level} {A : Set ℓ} (x : A) : A → Set where
  refl : x ≡ x

test1 : ∀ {x : Unit} → x ≡ tt
test1 = refl

test2 : ∀ {C : Cat} → FunctorΣ * C ≡ FunctorΣ * (C ᵒᵖ)
test2 = refl

test3 : ∀ {C : Cat} → Functor * C ≡ Functor * (C ᵒᵖ)
test3 = {!refl!}
{- x != x₁ of type Cat.Obj C
when checking that the expression refl has type
Functor * C ≡ Functor * (C ᵒᵖ) -}
```

(Note, as above, that it already works if we use `Σ` rather than `record`, but it would be nice to not have to do this.)

**Comment by nad** [comment]
No.

**Comment by JasonGross** [comment]
Are there any plans to add this feature, or any hope of getting it at some point in the future?

**Comment by nad** [comment]
I'm not aware of any such plans. Can you explain in more detail what it is that you are after?

**Comment by jespercockx** [comment]
If you want structural record types, can't you just define your records as (iterated) sigma types?

**Comment by JasonGross** [comment]
There's some detail on the context in https://github.com/coq/coq/issues/5293#issuecomment-337550412 .  I've run into this in a couple of contexts now.  The first one I encountered this in was in trying to formalize global and pointwise Kan extensions and have them line up in a way such that I didn't have to duplicate the work for left and right Kan extensions.  This requires setting things up so that applying the "dual" twice gives back what you started with judgmentally.  Since some of the constructions talk about the functor category `1 -> C` whereas others talk about `C`, we also need `(1 -> C ᵒᵖ)` to be the same as `(1 -> C) ᵒᵖ`.  When functors and categories are formulated as sigma types, this is judgmentally true, and the construction lines up quite nicely.  When they're formulated as records, however, there's a mismatch pretty deep in the term, and it's quite painful to make things line up.

**Comment by JasonGross** [comment]
Indeed I can just use iterated sigma types, though it seems that the rules for implicit status of abstracting records, constructors, and fields over enclosing modules with arguments are different from the rules for abstracting definitions over those module arguments.  It's not that big a deal, though.  I think the main issues is the (in)convenience of notations (there's no analog to `record { name = blah ; name2 = blah }` for nested sigma types).  (There might also be an issue with blow-up in the size of the types if these get nested.)

**Comment by JacquesCarette** [comment]
We've actually gone out of our way in agda-categories to make as many of these things hold judgementally.  For `1 -> C` vs `C`, that is hopeless, as they are fundamentally different even if equivalent (though there might be odd things when `C` is not inhabited).  Certainly  `(1 -> C ᵒᵖ)` should be the same as `(1 -> C) ᵒᵖ`, and it something that can be fixed if it's not.  For Kan extension, it's possible we've erred, and we'd be glad to see a concrete bug report.

**Comment by JasonGross** [comment]
> Certainly `(1 -> C ᵒᵖ)` should be the same as `(1 -> C) ᵒᵖ`, and it something that can be fixed if it's not.

I've opened https://github.com/agda/agda-categories/issues/256

> For Kan extension, it's possible we've erred, and we'd be glad to see a concrete bug report.

https://github.com/agda/agda-categories/issues/257

**Comment by JasonGross** [comment]
Do projections carry the parameters to the record type?  If they don't this might be a reason that having structural records would be more efficient than nested sigma types.  (When I experimented with nested sigma types in Coq, there was a ~15% slowdown overall on the impacted files, with some files having a 3x--4x slowdown (see https://github.com/HoTT/HoTT/pull/849))

**Comment by jespercockx** [comment]
Projections from record types don't carry parameters in the internal syntax, but then projections from the sigma type also don't, so I don't see why that would cause a difference in performance (there's other possible performance considerations of course).

**Comment by jespercockx** [comment]
It's not clear what concrete action we can take here, so I'm closing this issue.
