### ISSUE TITLE
Copatterns: Hole Filling disagrees with Type Checker

### ISSUE THREAD

**Issue by m0rphism** [agda/agda#5262]
```
$ agda --version
Agda version 2.6.1.2
```

Here is a minimalized version of the problematic code:

```agda
open import Relation.Binary.PropositionalEquality using (_≡_; refl)

record Semiring (A : Set) : Set where
  field
    _*_ : A → A → A
    *-assoc : ∀ x y z → (x * y) * z ≡ x * (y * z)

data Usage : Set where
  [∞] : Usage
  [0] : Usage

Semiring-Usage : Semiring Usage

Semiring._*_       Semiring-Usage [∞] [∞] = [∞]
Semiring._*_       Semiring-Usage [0] y   = [0]
Semiring._*_       Semiring-Usage x   [0] = [0]

Semiring.*-assoc   Semiring-Usage [∞] [0] z = {!refl!}
Semiring.*-assoc   Semiring-Usage x   y   z = {!!}
```

For the first hole `{!refl!}`, Agda displays the goal `[0] ≡ [0]`, and hence allows filling the hole with `refl`. This is expected behavior.

However, subsequent type checking fails for `refl` with error:
```
[0] != [∞] of type Usage
when checking that the expression refl has type
(Semiring-Usage Semiring.* (Semiring-Usage Semiring.* [∞]) [0]) z ≡
(Semiring-Usage Semiring.* [∞]) ((Semiring-Usage Semiring.* [0]) z)
```

Note, that the type checker is happy, if `record`-syntax is used instead of copatterns:
```agda
Semiring-Usage : Semiring Usage
Semiring-Usage = record
  { _*_     = λ { [∞] [∞] → [∞]
                ; [0] y   → [0]
                ; x   [0] → [0]
                }
  ; *-assoc = λ { [∞] [0] z → refl
                ; x y z     → {!!}
                }
  }
```

The type checker is also happy if we use copatterns, but treat each case for `z` individually:
```agda
Semiring.*-assoc   Semiring-Usage [∞] [0] [∞] = refl
Semiring.*-assoc   Semiring-Usage [∞] [0] [0] = refl
Semiring.*-assoc   Semiring-Usage x   y   z = {!!}
```

**Comment by nad** [comment]
Apparently Agda does not use the same reduction behaviour while `Semiring-Usage` is being defined as it does after it has been defined. I think @andreasabel knows what is going on, and whether this is by design or not. A simple workaround is to reorder the clauses:
```agda
Semiring._*_       Semiring-Usage [0] y   = [0]
Semiring._*_       Semiring-Usage x   [0] = [0]
Semiring._*_       Semiring-Usage [∞] [∞] = [∞]

Semiring.*-assoc   Semiring-Usage [∞] [0] z = refl
Semiring.*-assoc   Semiring-Usage x   y   z = ?
```

**Comment by andreasabel** [comment]
_While_ `Semiring-Usage` is type-checked, you only have the literal reduction rules. The rule (1)
```agda
Semiring._*_       Semiring-Usage x   [0] = [0]
```
cannot fire because it is not universally valid; at least Agda does not assume this, since a preceding equation matches on `x`.
_After_ type-checking, the coverage checker computes a split tree, making a rule like
```agda
Semiring._*_       Semiring-Usage [0] [0] = [0]
```
available.  This is why you can fill the hole, but not re-typecheck it.

To reduce such kind of frustrations, I recommend @jespercockx's `{-# OPTIONS --exact-split #-}` which will reject equation (1) in the first place, forcing you to write equations that actually fire always.
Actually, without the option, you should see in Emacs that equation (1) has a slight "smoke" background, alerting of potential problems with this rule.

```agda
{-# OPTIONS --exact-split #-}

open import Agda.Builtin.Equality

record Semiring (A : Set) : Set where
  field
    _*_ : A → A → A
    *-assoc : ∀ x y z → (x * y) * z ≡ x * (y * z)

data Usage : Set where
  [0] : Usage
  [∞] : Usage

Semiring-Usage : Semiring Usage

Semiring._*_     Semiring-Usage [0] y   = [0]
Semiring._*_     Semiring-Usage [∞] [0] = [0]
Semiring._*_     Semiring-Usage [∞] [∞] = [∞]

Semiring.*-assoc Semiring-Usage [0] y   z   = refl
Semiring.*-assoc Semiring-Usage [∞] [0] z   = refl
Semiring.*-assoc Semiring-Usage [∞] [∞] [0] = refl
Semiring.*-assoc Semiring-Usage [∞] [∞] [∞] = refl
```

PS: See also #3054.  The additional advice (besides `--exact-split`) is to order the clauses such that those requiring the least matches come first.

**Comment by m0rphism** [comment]
Ah, I see. Thanks for the explanation!

If I understood correctly, then my example with `record`-syntax works, because it doesn't use one large copattern match, but instead two independent pattern matching lambdas, so the split tree for the first match is already available in the second match.

**Comment by nad** [comment]
> Actually, without the option, you should see in Emacs that equation (1) has a slight "smoke" background, alerting of potential problems with this rule.

I tried this now, with interactive highlighting turned on: When I load the file the first time I don't get such warnings, but I get them when the file is reloaded.

**Comment by andreasabel** [comment]
> I tried this now, with interactive highlighting turned on: When I load the file the first time I don't get such warnings, but I get them when the file is reloaded.

Highlighting seems to have its own mind.
