### ISSUE TITLE
Move `src/hTags` to its own repo at `agda/hTags`

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5271]
Like https://github.com/agda/fix-whitespace, we should also move `hTags` to its own home at `agda/hTags`, since it is independent of the Agda code base.  We might even release it.

`hTags` is a developer tool that is optional to have, even when working on Agda.  So it should not have an effect like #2983 on Agda or lead to a complication of `Agda.cabal`, see: https://github.com/agda/agda/blob/f9a181685397517b5d14943ca88a1c0acacc2075/Agda.cabal#L254-L267

**Comment by andreasabel** [comment]
`hTags` now has a home at https://github.com/agda/hTags.
Here is a release candidate: https://hackage.haskell.org/package/hTags-0.1.5/candidate

**Comment by andreasabel** [comment]
The TAGS test on travis still works (https://travis-ci.org/github/agda/agda/jobs/762827837#L9899), at least, where travis works (8.6 and 8.4 timed out; 8.2 is broken, failing at install-deps).

As long as the fate of our travis CI isn't clear, I am not touching the magic in the Agda.cabal file (see OP comment).

Any opinions on whether we should release `hTags` or not?

**Comment by UlfNorell** [comment]
I don't see any reasons not to release it. We are going to keep it up-to-date for ourselves, so might as well share it with the community.

**Comment by andreasabel** [comment]
Let's continue at https://github.com/agda/hTags/issues/1.

**Comment by nad** [comment]
Now I get an error message when I run `make TAGS`:
```
======================================================================
================================ TAGS ================================
======================================================================
make[1]: Entering directory '[…]/src/full'
make -C ../hs-tags
make[2]: Entering directory '[…]/src/full'
make[2]: *** ../hs-tags: No such file or directory. Stop.
make[2]: Leaving directory '[…]/src/full'
Makefile:97: recipe for target '../hs-tags/dist/build/hs-tags/hs-tags' failed
make[1]: *** [../hs-tags/dist/build/hs-tags/hs-tags] Error 2
make[1]: Leaving directory '[…]/src/full'
Makefile:310: recipe for target 'TAGS' failed
make: *** [TAGS] Error 2
```
Is the idea that `hs-tags` should be checked out manually?

**Comment by UlfNorell** [comment]
Did you `git submodule init` and `update`?

**Comment by nad** [comment]
The makefile takes care of that for `std-lib`, `cubical` and `fix-whitespace`, so I think it would make sense to take the same approach for `hs-tags`.

**Comment by asr** [comment]
I disagree, we should use the binaries  of `fix-whitespace` and `hs-tags`.

**Comment by andreasabel** [comment]
These tools are no longer Agda-specific.  Cannot we just ditch the submodules `hs-tags` and `fix-whitespace` and have the developer install these binaries?  Or, if these commands do not exist in the `PATH`, we could launch a `cabal install hs-tags` etc.

**Comment by andreasabel** [comment]
I pushed PR #5310 to remove the submodules `fix-whitespace` and `hs-tags`.
