### ISSUE TITLE
Fixity declarations in records are applied too late.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#528]
If I define the operators inside of my records together with fixity declarations, the fixity declarations only come into effect after the last declared field. The following records having 'Bad' in their name fail to compile, while the 'Good' one compiles successfully.

I'd expect the fixity declarations to apply immediately when the name is brought into scope.

``` agda
data A : Set where
  a : A
data P : A → Set where

record Good1 : Set where
  infixl 13 _+_
  infixl 18 _*_

  _*_ : A → A → A
  _*_ = λ x y → a

  _+_ : A → A → A
  _+_ = λ x y → a

  field
   zz : A

  kk = a + a * a


record Bad1 : Set where
  infixl 13 _+_
  infixl 18 _*_

  _*_ : A → A → A
  _*_ = λ x y → a

  _+_ : A → A → A
  _+_ = λ x y → a

  kk = a + a * a
    -- Could not parse the application a + a * a 

  field
   zz : A


record Bad2 : Set where
  infixl 13 _+_
  infixl 18 _*_

  _*_ : A → A → A
  _*_ = λ x y → a

  _+_ : A → A → A
  _+_ = λ x y → a

  field
   zz : P (a + a * a)
    -- Could not parse the application a + a * a 

  kk = a + a * a

```

Original issue reported on code.google.com by `rot...@gmail.com` on 18 Nov 2011 at 4:17

**Comment by UlfNorell** [comment]
Same as #2634. Now fixed.
