### ISSUE TITLE
Pattern matching lambdas are not alpha equivalent 

### ISSUE THREAD

**Issue by awkure** [agda/agda#5282]
I've been playing around denotational semantics for untyped lambdas and stuck upon the following issue, consider the code
```agda
module Bug where

data Typ : Set where
  ⋆ : Typ

data Val : Set where
  ⊥ : Val
  _⇒_ : Val → Val → Val

data Ctx : Set where
  ∅ : Ctx
  _,_ : Ctx → Typ → Ctx

variable
  Γ : Ctx

data _∈_ : Typ → Ctx → Set where
  top : ∀ {A} → A ∈ (Γ , A)
  pop : ∀ {A B} → A ∈ Γ → A ∈ (Γ , B)

Ctx' : Ctx → Set
Ctx' Γ = ∀ (x : ⋆ ∈ Γ) → Val

∅' : Ctx' ∅
∅' ()

_,'_ : Ctx' Γ → Val → Ctx' (Γ , ⋆)
γ ,' v =
  λ { top → v
    ; (pop xs) → γ xs
    }

data _⊢_ : Ctx → Typ → Set where
  wrap_ : ∀ {A}
        → A ∈ Γ
        → Γ ⊢ A

  ƛ_  : (Γ , ⋆) ⊢ ⋆
      → Γ ⊢ ⋆

data _⊢_↓_ : Ctx' Γ → Γ ⊢ ⋆ → Val → Set where
  var : ∀ (Γ) (γ : Ctx' Γ) (x)
      → γ ⊢ wrap x ↓ γ x

  ƛ-intro_ : ∀ {Γ} {γ : Ctx' Γ} {N v w}
           → (γ ,' v) ⊢ N ↓ w
           → γ ⊢ (ƛ N) ↓ (v ⇒ w)

-- id due to De-Brujin
id : ∅ ⊢ ⋆
id = ƛ (wrap top)

_ : ∅' ⊢ id ↓ (⊥ ⇒ ⊥)
_ = ƛ-intro (var (∅ , ⋆) {!!} top)
```

Here if we try to solve the whole via agsy the following error arises

```
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/Reduce/Fast.hs:1377:20 in Agda-2.6.2-BPMWqxqTbgN8f1oa1F0Q4F:Agda.TypeChecking.Reduce.Fast
```

Agsy suggests inserting 

```
(λ { top → ⊥ ; (pop xs) → ∅' xs })
```

Into the hole, but then compilation fails with

```
(λ { top → ⊥ ; (pop xs) → ∅' xs }) x !=
(λ { top → ⊥ ; (pop xs) → ∅' xs }) x of type Val
```

If I try to concretize it by adding `λ _ → {!!}` for the robot, it generates unacceptable code 

```
_ : ∅' ⊢ id ↓ (⊥ ⇒ ⊥)
_ = ƛ-intro (var (∅ , ⋆) (λ _ → (λ { top → ⊥ ; (pop xs) → ∅' xs }) x) top)
```

extracting `x` from the definition of `Ctx'`.

Interestingly, if we use default pattern matching in `_,'_` instead of pattern matching lambda, then everything compiles as expected (in both cases) 

```agda
_,'_ : Ctx' Γ → Val → Ctx' (Γ , ⋆)
(_ ,' v) top = v
(γ ,' _) (pop xs) = γ xs

_ : ∅' ⊢ id ↓ (⊥ ⇒ ⊥)
_ = ƛ-intro (var (∅ , ⋆) (∅' ,' ⊥) top)
```

This also compiles if `var` has implicit arguments and evoked via 

```
_ : ∅' ⊢ id ↓ (⊥ ⇒ ⊥)
_ = ƛ-intro var
```

**Comment by gallais** [comment]
I believe this is #4590

Edit: as mentioned in that other thread, this behaviour is intended and even
documented: https://agda.readthedocs.io/en/latest/language/lambda-abstraction.html?highlight=generative

If you need to be able to refer to this function later on you should name it.
As a consequence I'll close this issue.
