### ISSUE TITLE
Tactic command runs forever

### ISSUE THREAD

**Issue by guilhermehas** [agda/agda#5283]
When I try to compile this program, it never finishes:
```agda
data ⊥ : Set where

_ : ⊥
_ = tactic ?
```

**Comment by andreasabel** [comment]
MWE:
```agda
open import Agda.Builtin.Reflection

A : Set
A = tactic ?
```
This fails in 2.6.0 with unsolved constraints, starting with 2.6.1 it loops.

**Comment by andreasabel** [comment]
Turns out that the scope checker accepts `tactic ?` as expression, but the type checker never handles it.  (It is ping-ponged forever between `checkExpr` and `checkApplication`, I suppose.)
