### ISSUE TITLE
Very weird behaviour with compiled Data.Nat.Show.readMaybe

### ISSUE THREAD

**Issue by Taneb** [agda/agda#5288]
If I compile this little program with the GHC backend:

```agda
module ReadBaseTest where

open import Data.Maybe
open import Data.Nat.Show
open import IO
open import Level

main : _
main = run {0ℓ} (putStr (show (fromMaybe 0 (readMaybe 10 "100"))))
```

I expect it to output `100` but for me it's outputting `40001172323904`

Because every bit of this seems to be working fine if I `C-c C-n` in emacs, I think this is a bug with either some primitives or the compiler. It happens with `readMaybe` and any two-or-more-digit number

**Comment by Taneb** [comment]
Further investigation makes it seem like it's using some arbitrary number (here, `6324648`) rather than the given base

**Comment by nad** [comment]
The generated code for `readMaybe` throws away the base:
```haskell
name10 = "Data.Nat.Show.readMaybe"
d10 ::
  Integer ->
  AgdaAny -> MAlonzo.Code.Agda.Builtin.String.T6 -> Maybe Integer
d10 v0 v1 v2 = du10 v1 v2
```

**Comment by nad** [comment]
The code for `readMaybe` includes the following part:
```agda
    convert : List ℕ → ℕ
    convert = List.foldl (λ acc d → base * acc + d) 0
```
Here is the code that is generated for `convert`:
```haskell
name18 = "Data.Nat.Show._.convert"
d18 :: Integer -> AgdaAny -> [Integer] -> Integer
d18 v0 v1 = du18 v0
du18 :: Integer -> [Integer] -> Integer
du18 v0
  = coe
      MAlonzo.Code.Data.List.Base.du230
      (coe (\ v1 -> addInt (coe mulInt (coe v0) (coe v1))))
      (coe (0 :: Integer))
```
Here the base is included. However, when `du18` is called a bogus argument is used:
```haskell
du10 ::
  AgdaAny -> MAlonzo.Code.Agda.Builtin.String.T6 -> Maybe Integer
du10 v0 v1
  = let v2
          = coe
              MAlonzo.Code.Function.Base.du226
              (coe MAlonzo.Code.Data.Maybe.Base.du68 (coe du18 (coe v0)))
              (coe
                 MAlonzo.Code.Function.Base.du226
                 (coe
                    MAlonzo.Code.Data.List.Categorical.du86
                    (coe MAlonzo.Code.Data.Maybe.Categorical.du12) (coe du32 (coe v0)))
                 (coe MAlonzo.Code.Agda.Builtin.String.d12))
              (coe v1) in
    case coe v1 of
      l | (==) l ("" :: Data.Text.Text) ->
          coe MAlonzo.Code.Agda.Builtin.Maybe.C18
      _ -> coe v2
```
Here `v0` corresponds to the hidden second argument of `readMaybe`:
```agda
readMaybe : ∀ base {base≤16 : True (base ≤? 16)} → String → Maybe ℕ
```

**Comment by nad** [comment]
Here are some cut-down examples:
```agda
open import Agda.Builtin.Bool
open import Agda.Builtin.Nat

f : Nat → Nat → Nat
f _ zero = 0
f m      = λ _ → m

g : Nat → Bool → Nat
g _ true = 0
g m      = λ _ → m
```
The compiled code:
```haskell
name2 = "Bug.f"
d2 :: Integer -> Integer -> Integer
d2 v0 v1 = du2 v1
du2 :: Integer -> Integer
du2 v0 = coe v0
name8 = "Bug.g"
d8 :: Integer -> Bool -> Integer
d8 v0 v1 = du8 v1
du8 :: Bool -> Integer
du8 v0
  = case coe v0 of
      MAlonzo.Code.Agda.Builtin.Bool.C10 -> coe (0 :: Integer)
      _ -> coe v0
```

**Comment by nad** [comment]
The compilation to tree-less syntax seems to be buggy:
```
-- compiled clauses of f
  case 1 of
    Agda.Builtin.Nat.Nat.zero -> done[_] 0
    _ -> done[m] λ _ -> @1
-- common arity: 2
-- converted
Bug.f =
  λ _ a →
    let b = (λ _ → a) a in
    case a of
      Agda.Builtin.Nat.Nat.zero → 0
      _ → b
```

**Comment by andreasabel** [comment]
This MWE should print `123` but prints `1`, all the way through Agda 2.5.3 -- 2.6.2.
```agda
open import Agda.Builtin.IO
open import Agda.Builtin.Nat
open import Agda.Builtin.Unit

f : Nat → Nat → Nat
f _ zero = 0
f m      = λ _ → m

postulate
  printNat : Nat → IO ⊤

{-# COMPILE GHC printNat = print #-}

main = printNat (f 123 1)
```
@nad wrote:
> The compilation to tree-less syntax seems to be buggy:
> 
> ```
> -- compiled clauses of f
>   case 1 of
>     Agda.Builtin.Nat.Nat.zero -> done[_] 0
>     _ -> done[m] λ _ -> @1
> -- common arity: 2
> ```
I already do not understand the the second compiled clause.  The `λ _ ->` looks weird, imo.  The variable that is abstracted here is already in scope, because how could we otherwise case on it?  Maybe the compiled clauses are a slightly unusual concept...

**Comment by gallais** [comment]
I guess the assumption was that all of the vars introduced on the RHS were there
because of a refined type, not because of an unsaturated LHS compared to other
equations.

**Comment by Taneb** [comment]
Is there anything I can do to help resolve this issue?

**Comment by jespercockx** [comment]
That depends a lot on your familiarity with the Agda codebase. At the moment the big question seems to be what goes wrong in the construction of the case tree that @nad posted, and why this problem does not cause issues in other places. I haven't had the time yet to look at it myself.

**Comment by gallais** [comment]
> Is there anything I can do to help resolve this issue?

A PR to the stdlib making sure that all the clauses have the same number
of arguments ought to fix the issue initially reported (but not its root
cause). So if you have a project you want to compile and that's the only
instance of such a problem, that should work.

**Comment by nad** [comment]
> I already do not understand the the second compiled clause. The `λ _ ->` looks weird, imo. The variable that is abstracted here is already in scope, because how could we otherwise case on it? Maybe the compiled clauses are a slightly unusual concept...

I don't know how that thing should be interpreted, but the following code is accepted:
```agda
{-# OPTIONS --no-fast-reduce -vtc.reduce:95 #-}

open import Agda.Builtin.Equality
open import Agda.Builtin.Nat

f : Nat → Nat → Nat
f _ zero = 0
f m      = λ _ → m

_ : f 123 1 ≡ 123
_ = refl
```
The debug printout indicates that the "compiled clauses" are used:
```
unfoldDefinitionStep v0 Issue5288.f
reduceNormalE v0 = Issue5288.f
appDefE v =  Issue5288.f
    result 123
*** reduced definition:  Issue5288.f
```
Note the line with `appDefE`:
https://github.com/agda/agda/blob/044fba09d67771186e916446a3fefd22bd4f0bb5/src/full/Agda/TypeChecking/Reduce.hs#L753-L759

**Comment by nad** [comment]
> Is there anything I can do to help resolve this issue?

If the problem lies in the conversion to tree-less syntax, then you could take a look at the following code:

https://github.com/agda/agda/blob/044fba09d67771186e916446a3fefd22bd4f0bb5/src/full/Agda/Compiler/ToTreeless.hs#L221-L230

**Comment by nad** [comment]
> Is there anything I can do to help resolve this issue?

If the problem lies in the conversion to tree-less syntax, then you could take a look at the following code:

https://github.com/agda/agda/blob/044fba09d67771186e916446a3fefd22bd4f0bb5/src/full/Agda/Compiler/ToTreeless.hs#L221-L230

**Comment by andreasabel** [comment]
> > ```
> > -- compiled clauses of f
> >   case 1 of
> >     Agda.Builtin.Nat.Nat.zero -> done[_] 0
> >     _ -> done[m] λ _ -> @1
> > -- common arity: 2
> > ```
> 
> 
> I already do not understand the the second compiled clause.  The `λ _ ->` looks weird, imo.  The variable that is abstracted here is already in scope, because how could we otherwise case on it?  Maybe the compiled clauses are a slightly unusual concept...

Looking at the compiled clause matcher, it becomes clear that this works:
For instance in `f 123 1` the argument `1` does not match `zero`, so the respective `conFrame` is not put on the stack, only the catch-all frame `done[m] λ _ -> @1`.  So `123` is substituted for `m` (`@1`), and the rest `\ _ -> 123` is the applied to `1`, yielding `123`.  
So the problem is in the compilation to treeless.

Related: #2469

**Comment by andreasabel** [comment]
3 hours on a Saturday evening hunting for a de Bruijn problem...
