### ISSUE TITLE
Documentation for internal level properties

### ISSUE THREAD

**Issue by googleson78** [agda/agda#5313]
[It was just confirmed to me](https://lists.chalmers.se/pipermail/agda/2021/012565.html) that `Level`s do indeed have some "internal automatically solved" properties. 

Jesper also suggested that it would be nice to have this documented and I agree, since I couldn't figure these things out from just reading the manual.

I'll try to contribute a section in the [corresponding document](https://github.com/agda/agda/blob/master/doc/user-manual/language/universe-levels.lagda.rst) sometime this coming week.

**Comment by jespercockx** [comment]
I've set this to 2.6.3 milestone for now, but it can still be changed to 2.6.2 if it's done before the release.
