### ISSUE TITLE
The reflection machinery should support quantities

### ISSUE THREAD

**Issue by nad** [agda/agda#5317]
The commit comment for 4f5220383e4d5d2ee8b0e92382188aa44b742f56 states that something should be revisited:

> Re #2805 refactor: getRelevance for argInfoRelevance (REVISIT when adding Quantity)
>
> These occurrences need to be revisited once we put content into
> Quantity and actually implement run-time irrelevance.

It appears as if this has not been done:

https://github.com/agda/agda/blob/2bf7d55728e3b76d38d05b1c190e55ea57d1407b/src/full/Agda/TypeChecking/Quote.hs#L134-L138

The first line was added in the commit mentioned above.

Here is a concrete test case:
```agda
open import Agda.Builtin.Reflection
open import Agda.Builtin.List
open import Agda.Builtin.Unit

macro

  test : Term → TC ⊤
  test goal =
    bindTC (inferType goal) λ type → typeError (termErr type ∷ [])

_ : @0 Set → Set
_ = test
```
```
(A : Set₀) → Set₀
when checking that the expression unquote test has type
@0 Set → Set
```
The error message should start with `(@0 A : Set₀) → Set₀` (or something like that).

@andreasabel, can you take a look at this? I'm not sure exactly what you intended to revisit.

**Comment by nad** [comment]
I'll try to add quantities to the reflection machinery.

**Comment by nad** [comment]
I discussed this with @andreasabel and @jespercockx. We came to the conclusion that we should add a new type for modalities, including relevance and quantity, to the reflection API.

**Comment by L-TChen** [comment]
> I discussed this with @andreasabel and @jespercockx. We came to the conclusion that we should add a new type for modalities, including relevance and quantity, to the reflection API.

I am just curious if it is possible to use the internal syntax as reflected syntax directly. It appears that to make the reflection API fully reflective everything should be exposed.

**Comment by jespercockx** [comment]
How would you expose the internal syntax directly? Would you add FFI bindings to the Haskell types?

In general there are many implementation details in the Haskell codebase that are perhaps not crucial to expose to the user, or should only be exposed in a "safe" manner. In particular, any operation that modifies the TCM state should probably not be exposed directly in the reflection API.

**Comment by L-TChen** [comment]
I know it will take a lot effort to unify these two, and surely there are some unsafe operations which should not be used as part of reflection. However, we can have a fully exposed reflection API and a safe interface in Agda which only exports functions that should be used. Removing supports in the Agda primitive interfaces should be easier than adding supports in the Haskell codebase in general.

**Comment by L-TChen** [comment]
(I have been thinking about this every time there is a request of exposing xxx info to the reflection API...)
