### ISSUE TITLE
Why is relevance ignored by the reflection machinery?

### ISSUE THREAD

**Issue by nad** [agda/agda#5318]
The reflection machinery currently allows you to apply a function of type `Set → Set` to an argument which according to the `ArgInfo` value is irrelevant, and it allows you to apply a function of type `.Set → Set` to an argument which is relevant:
```agda
open import Agda.Builtin.Reflection
open import Agda.Builtin.List
open import Agda.Builtin.Unit

postulate
  F :  Set → Set
  G : .Set → Set

macro

  m₁ : Set → Term → TC ⊤
  m₁ A goal =
    bindTC (quoteTC A) λ A →
    unify goal
      (def (quote F) (arg (arg-info visible irrelevant) A ∷ []))

_ : Set → Set
_ = λ A → m₁ A

macro

  m₂ : Set → Term → TC ⊤
  m₂ A goal =
    bindTC (quoteTC A) λ A →
    unify goal
      (def (quote G) (arg (arg-info visible relevant) A ∷ []))

_ : Set → Set
_ = λ A → m₂ A
```
Is this intended? Does it lead to broken internal invariants? Does Agda fix the `ArgInfo` values when unquoting the terms?

I'm trying to add support for quantities to the reflection machinery (#5317), and I wonder if they should be treated in the same way.

**Comment by jespercockx** [comment]
I think this is working as intended. In general, the reflection API is quite liberal with the kind of syntax it accepts, for example by inserting missing implicit arguments. Inferring irrelevance annotations on arguments seems to me like it is in the same scope.

Though perhaps it would be better if the reflection API had a separate `unknown` relevance for when you want the relevance to be inferred, and actually raise an error if the relevance is wrong in other cases.

**Comment by jespercockx** [comment]
To answer the question whether it leads to broken invariants: no it doesn't, since all the reflected code passes again through the typechecker where the annotations are set to their correct values.
