### ISSUE TITLE
Minor improvements to Agda.Utils.Either (`groupByEither`, `swapEither`)

### ISSUE THREAD

**Issue by subttle** [agda/agda#5321]
Hi all, thank you so much for the work you do on this wonderful project. I recently wrote a function similar to `groupByEither` which carries out the same functionality but implemented in terms of an `unfoldr`. Here is the version [currently](https://github.com/agda/agda/blob/f50c14d3a4e92ed695783e26dbe11ad1ad7b73f7/src/full/Agda/Utils/Either.hs#L115) in use.
```Haskell
-- | Groups a list into alternating chunks of 'Left' and 'Right' values
groupByEither :: forall a b. [Either a b] -> [Either (List1 a) (List1 b)]
groupByEither = listCase [] (go . init) where

  go :: Either (List1 a) (List1 b) -> [Either a b] -> [Either (List1 a) (List1 b)]
  go acc         []              = adjust acc : []
  -- match: next value can be tacked onto the accumulator
  go (Left  acc) (Left  a : abs) = go (Left  $ a <| acc) abs
  go (Right acc) (Right b : abs) = go (Right $ b <| acc) abs
  -- mismatch: switch the accumulator to the other mode
  go acc         (ab      : abs) = adjust acc : go (init ab) abs
  
  adjust = bimap List1.reverse List1.reverse
  init   = bimap singleton singleton
```

What I'm proposing is updating the function to use the following definition:
```Haskell
groupByEither :: forall a b . [Either a b] → [Either (List1 a) (List1 b)]
groupByEither = unfoldr c
  where
    c :: [Either a b] → Maybe (Either (List1 a) (List1 b), [Either a b])
    c = listCase Nothing (either (\a -> Just . first (Left  . ((:|) a . concatMap (either pure (const [])))) . span isLeft)
                                 (\b -> Just . first (Right . ((:|) b . concatMap (either (const []) pure))) . span isRight))
```
I would argue my proposed implementation is fewer lines of code (while still being at least as easy to follow cognitively), avoids name shadowing of `abs`, avoids the need for `List1.reverse`, and some very preliminary/unofficial testing (I've only done some very basic testing with GHCi's `λ> :set +s`, not used any benchmarking suit) seems to be slightly more efficient.

Also, the [current](https://github.com/agda/agda/blob/f50c14d3a4e92ed695783e26dbe11ad1ad7b73f7/src/full/Agda/Utils/Either.hs#L134) implementation of `swapEither` could avoid the `LambdaCase`:
```Haskell
-- | Swap tags 'Left' and 'Right'.
swapEither :: Either a b -> Either b a
swapEither = \case
  Left a -> Right a
  Right b -> Left b
```
and just be a shorter, point-free definition:
```Haskell
-- | Swap tags 'Left' and 'Right'.
swapEither :: Either a b -> Either b a
swapEither = either Right Left
```
But perhaps the `LambdaCase` is just the preferred style.

If you prefer to keep things the way they are, then please close the ticket and I won't take offense, I'll appreciate any feedback. But if you are interested please let me know and I'll create a PR. Thank you for your consideration.

P.S.
I have read the [style-guide](https://github.com/andreasabel/haskell-style-guide/blob/master/haskell-style.md) and I realize one of my functions here extends the usual limit of characters per line, if that is a problem (it does say exceptions are made) I can break the function into several labelled components.

**Comment by gallais** [comment]
A `span isLeft` followed by a `either` seems like an antipattern to me.
Especially given that it forces you to throw in `concatMap`.

I think it'd make more sense to use `Agda.Utils.List`'s `spanJust` instead
to both test for being `Left` (resp. `Right`) *and* unpack the value at the same time.
That would also make the whole affair easier to understand IMO.

Edit: btw,

> I've only done some very basic testing with GHCi's λ> :set +s, not used any benchmarking suit

AFAIU this is basically meaningless as it's running a bytecode version of the program which is miles
away from what is actually produced by GHC after compilation.

**Comment by subttle** [comment]
Thank you for the feedback :)
I know what you mean, one could replace the `concatMap` portion with a partial `fmap (\(Left a) -> a)`, (resp. `fmap (\(Right b -> b)`) and even though I know  the context would let it work, I opted for the safer, total route. Thank you for the great suggestion with `spanJust`. If I understood correctly then this would be more toward what you suggested?
```Haskell
    c :: [Either a b] -> Maybe (Either (List1 a) (List1 b), [Either a b])
    c = listCase Nothing (either (\a -> Just . first (Left  . (a :|)) . spanJust maybeLeft)
                                 (\b -> Just . first (Right . (b :|)) . spanJust maybeRight))
```

**Comment by gallais** [comment]
The repetition of `Just` in both branches of the `either` suggests you ought
to be able to pull it out. To me it starts looking a lot more like an `fmap`
over an `uncons` rather than a `listCase`.

```haskell
    c :: [Either a b] -> Maybe (Either (List1 a) (List1 b), [Either a b])
    c = fmap (uncurry $ either (\a -> first (Left  . (a :|)) . spanJust maybeLeft)
                               (\b -> first (Right . (b :|)) . spanJust maybeRight))
      . uncons
```

I'm still not convinced this is more readable than "match: accumulate; mismatch: switch accumulator".

**Comment by subttle** [comment]
Funny! I was actually about to post that I was trying:
```Haskell
    c = listCase Nothing (Just <.> either (\a -> first (Left  . (a :|)) . spanJust maybeLeft)
                                          (\b -> first (Right . (b :|)) . spanJust maybeRight))
```

**Comment by andreasabel** [comment]
I think getting rid of a `reverse` is usually good, in particular if this means that a function can be generalized from finite lists to also work for infinite streams.

The definition seems to have improved by your interaction so far.  If I was to ask for style improvements, it would be:
- give name and type signature to the two anonymous functions (`\a -> first (Left  . (a :|)) . spanJust maybeLeft` ...) in order to improve readability
- (this also fixes the long-line problem)
- one should not overdo with point-free style, so defining `c` by cases ought to improve the readability.
My entry to the beauty contest:
```haskell
groupByEither :: forall a b. [Either a b] -> [Either (List1 a) (List1 b)]
groupByEither = unfoldr c
  where
  c :: [Either a b] -> Maybe (Either (List1 a) (List1 b), [Either a b])
  c []             = Nothing
  c (Left  a : xs) = Just $ first (Left  . (a :|)) $ spanJust maybeLeft  xs
  c (Right b : xs) = Just $ first (Right . (b :|)) $ spanJust maybeRight xs
```
Entry at https://github.com/agda/agda/pull/5322.
