### ISSUE TITLE
Regression: unsolved metas when using `variable`s in `Data.Container.Indexed.Combinator`

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda#5333]
There appears to have been a regression with respect to `variable`s since the last release. If you type-check [`Data.Container.Indexed.Combinator`](https://github.com/agda/agda-stdlib/blob/master/src/Data/Container/Indexed/Combinator.agda) from the `master` branch of the standard library at any commit after https://github.com/agda/agda-stdlib/commit/747351e1675e29e882fc65e6ce54b968567648cb then it type checks fine under Agda `2.6.1`.

However type-checking the same file on the latest version of Agda (6df366fc26bd802645724c05a495ba23e33efe44) on the `experimental` branch of the standard library, causes Agda to gobble a huge amount of memory and then spit out the huge "Unsolved metas" error visible [here](https://github.com/agda/agda/runs/2387264683?check_suite_focus=true#step:8:677).

This was first anecdotally observed by @andreasabel in his first comment in https://github.com/agda/agda-stdlib/pull/1458 and the error appears to disappear when removing the variable declarations for `I` and `O`.

This is blocking us bumping the standard library version to the new `v1.6`, see https://github.com/agda/agda/pull/5332.

**Comment by jespercockx** [comment]
I believe I independently discovered and fixed this issue in https://github.com/agda/agda/issues/5363. Please reopen if the problem persists.
