### ISSUE TITLE
Meta-variable in constructor type busts interleaved mutual

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5334]
@gallais 
Why cannot `interleaved mutual` blocks handle meta-variables when matching a constructor type against possible data types?
```agda
open import Agda.Builtin.Nat

variable
  n : Nat

module Works where
  data Fin : Nat → Set where
    zero : Fin {!!}

interleaved mutual

  data Fin : Nat → Set
  constructor
    zero : Fin ?
```
reports
```
Could not find a matching data signature for constructor zero
There was no candidate.
```
Why doesn't `Fin ?` match `Fin _`? 

In a complex mutual very-dependent signature, I would hope to get some help from Agda to fill in some indices...

**Comment by gallais** [comment]
Patterns cannot have holes in them and I am reusing the `couldBeCallOf`
logic that is used to group blocks of function clauses inside a single
definition to identify potential parent data types: 

https://github.com/agda/agda/blob/a96724385f3fd54f3a38a25ebeea69c6c598640c/src/full/Agda/Syntax/Concrete/Definitions.hs#L947-L957

(here `ns` is the list of names of datatypes declared in the interleaved
mutual block, and `e` is the type being considered).

**Comment by andreasabel** [comment]
@gallais: Thanks for the explanation.  This should not be too hard to mend.
(At some point we should throw out patterns from the concrete syntax altogether...)

[So, I am trying `interleaved mutual` for the first time, and it is mind boggling what kind of mutuality one can formulate with that... Fascinating!]

**Comment by andreasabel** [comment]
> Patterns cannot have holes in them and I am reusing the `couldBeCallOf`
> logic

Looking at `couldBeCallOf`, it actually does not make use of the pattern structure, only the names a pattern contains.  Thus, we can easily generalize `couldBeCallOf` to simply use a list of names.  Or we could patch the translation to pattern to map all non-pattern things to `WildP`.
