### ISSUE TITLE
Invalid case split for with ... in

### ISSUE THREAD

**Issue by uncle-betty** [agda/agda#5355]
I think that I ran into an issue with a `C-c C-c` case split on `x` in the goal in the following piece of code, using current `master`:

```
open import Data.Nat using (ℕ ; _<?_)
open import Relation.Nullary using (_because_ ; ofʸ ; ofⁿ)

test : (a b : ℕ) → ℕ
test a b with a <? b in eq
... | x = {!x!}
```
Doing the case split results in this:

```
test a b with a <? b in eq
... | does because proof | eq = ?
```

Which makes Agda say `Unexpected with patterns | eq`.

Manually removing `| eq` is an easy workaround.

```
tlo@carol:~/work/explore$ agda --version
Agda version 2.6.2-1bac879-dirty
```

**Comment by gallais** [comment]
Related: #513, #3995

**Comment by gallais** [comment]
I'll close this one as a duplicate too as I expect a fix for `rewrite` will also
fix this given these things are implemented using the same data structures.
