### ISSUE TITLE
`interleaved mutual`: `data _ where` instead of `constructor`

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5356]
The new `interleaved mutual` blocks introduced `constructor` blocks.  However, I noticed that for uniform constructor blocks, introducing just constructors for one data type `D`, one can use the existing notation `data D where` (https://github.com/agda/agda/issues/5336#issuecomment-828603619).

It seems more conservative to _not_ introduce a new syntax, i.e., `constructor` blocks (with layout-or-not confusion caused in #5236), but to reuse our existing syntax.

Introducing constructors for different data types can be done with several `data ... where` blocks.  We can also consider the concrete syntax `data _ where` to replace the current `constructor`.

If we release `constructor` blocks now, we cannot go back.  If we stick to `data ... where`, we could still introduce a new concrete syntax later.

Further, I found it awkward to discuss two just minimally different syntaxes for the same purpose, see my documentation attempt at https://github.com/agda/agda/pull/5351/commits/edacaf073f057491aec808323e6b40f93671a273.

@gallais @UlfNorell @jespercockx @nad

**Comment by jespercockx** [comment]
I vote in favour of re-using the existing syntax if possible.

**Comment by nad** [comment]
I have not paid much attention to this discussion. I generally prefer syntax that can be copied verbatim into papers: I think it is a positive sign if you can write a functional pearl in Literate Agda without having to explain the notation that you are using (and without too much hacking to hide parts of the code).

The mutual keyword is quite self-explanatory, and is easy to hide if you want to:
```latex
We define \AgdaFunction{f} and \AgdaFunction{g} mutually:
\begin{code}
mutual

  f : …
  f = …

  g : …
  g = …
\end{code}
```
```latex
We define \AgdaFunction{f} and \AgdaFunction{g} mutually:
\begin{code}[hide]
mutual
\end{code}
\begin{code}
  f : …
  f = …

  g : …
  g = …
\end{code}
```
The second kind of mutual blocks also works fine in papers:
```latex
The functions \AgdaFunction{f} and \AgdaFunction{g} do something:
\begin{code}
f : …
g : …
\end{code}
They are defined mutually:
\begin{code}
f = …
g = …
\end{code}
```

**Comment by UlfNorell** [comment]
+1 on dropping `constructor` blocks in favour of `data .. where`

**Comment by andreasabel** [comment]
@nad, what about the new `interleaved mutual`?  How would you rate this?  Also, your comment does not touch on `data` signatures and `data...where` blocks...

**Comment by nad** [comment]
I might write something like the following:
```latex
We define `A` and `f` mutually:
\begin{code}[hide]
  interleaved mutual
\end{code}
\begin{code}
    data A : Type

    f : (x : A) → P x
\end{code}
The constructor \AgdaInductiveConstructor{c} has some intended meaning:
\begin{code}[hide]
    constructor
\end{code}
\begin{code}
      c : A
\end{code}
The function \AgdaFunction{f} does something in this case:
\begin{code}
    f c = …
\end{code}
And so on…
```
I don't think `interleaved mutual` is self-explanatory, and writing `constructor` for each constructor could be rather noisy (and waste space), so I've hidden those parts of the code: the surrounding text explains what is going on. If I had to present actual Agda code I would prefer it there was at most a single, easily understandable keyword like `mutual`.

**Comment by andreasabel** [comment]
Ok, if you would hide `constructor`, it wouldn't matter for you whether it is written `data _ where` instead.

**Comment by nad** [comment]
I'd prefer if I didn't have to hide anything.

**Comment by gallais** [comment]
> writing `constructor` for each constructor could be rather noisy
  (...) If I had to present actual Agda code I would prefer it there
  was at most a single, easily understandable keyword like mutual.

That would require some guesswork like turning all of the type
declarations that end in an applied type constructor and that
do not have a definition in the block into constructors.
But this heuristics could mistake e.g. a smart constructor with a
missing definition for a new constructor.

In general I think it's better to have the users state what they
mean and assist them in debugging / filling up the missing part of
their program than attempting to divine a correct program that matches
the source and may or may not be the one they had in mind.

**Comment by UlfNorell** [comment]
@nad In your example you write `The constructor bla bla bla:` and then the constructor declaration, so clearly you feel the need to explain to the reader that the following declaration is of a constructor. Are you saying that in your ideal version of Agda the syntax for constructor blocks should be a literate comment containing the word constructor?

**Comment by nad** [comment]
Perhaps the `constructor` keyword, or the alternative notation discussed here, could be optional.

**Comment by UlfNorell** [comment]
But only if you have a literate comment explaining that it's a constructor of course.

**Comment by nad** [comment]
> That would require some guesswork like turning all of the type
> declarations that end in an applied type constructor and that
> do not have a definition in the block into constructors.

In another language one could perhaps treat everything of the form `name : type`, where there is no further definition of `name`, as a constructor declaration (and complain if the type does not make sense). However, in Agda it might be hard to tell what the defined name is in a function clause. Can we even do this in all cases now?

**Comment by nad** [comment]
> Can we even do this in all cases now?

No:
```agda
F : Set → Set₁
_G : Set → Set₁

F G = Set
F G = Set
```
```
More than one matching type signature for left hand side F G it
could belong to any of:
F (at […]:1,1-2)
_G (at […]:2,1-3)
```

By the way, the disambiguation code seems to be rather crude, neither of the following two clauses are accepted:
```agda
F (G) = Set
_G F = Set
```

**Comment by nad** [comment]
Consider the following code:
```agda
data D : Set where
  _c : D

f : D → D
c : D

f x = {!x!}
c = _c
```
Agda accepts this, but if you split on `x`, then the resulting code is rejected:
```
More than one matching type signature for left hand side f _c […]
```
I did not find any way to complete the code above (without changing anything but the clause of `f`, and having `f` applied to `_c` in the left-hand side). This is not a problem with `mutual` blocks, the following code is accepted:
```agda
mutual

  f : D → D
  f _c = _c

  c : D
  c = _c
```
I'm not sure this is actually a problem in practice, though.

**Comment by andreasabel** [comment]
So we go for `data _ where` instead of `constructor`.
