### ISSUE TITLE
tactic annotation on record field of function type drops domain in copattern definition

### ISSUE THREAD

**Issue by ecavallo** [agda/agda#5358]
I'm using a tactic to give a record field a default definition, as in #4225. When the field has a function type, like `Bool → Bool` below, and I try to define an element of the record type by copattern matching (but not by the constructor), Agda seems to think I should give something of type `Bool` instead. `Bool → Bool → Bool` and so on also want to become just `Bool`.
```agda
open import Agda.Builtin.Unit
open import Agda.Builtin.Bool
open import Agda.Builtin.Reflection renaming (bindTC to _>>=_)

defaultTo : {A : Set} (x : A) → Term → TC ⊤
defaultTo x goal = do
  `x ← quoteTC x
  unify goal `x

module Number0 where

  record Class : Set where
    constructor con
    field
      x : Bool → Bool
      @(tactic defaultTo x) {y} : Bool → Bool
  open Class

  {- Correctly succeeds -}
  testA : Class
  testA = con (λ b → b)

  {-
    Incorrectly fails with:
    Bool → Bool !=< Bool
    when checking that the inferred type of an application
      Bool → Bool
    matches the expected type
      Bool
  -}
  testB : Class
  testB .x = λ b → b

module Number1 where

  record Class : Set where
    constructor con
    field
      x : Bool
      @(tactic defaultTo x) {y} : Bool → Bool
  open Class

  {-
    Correctly fails
  -}
  testA : Class
  testA = con true

  {-
    Incorrectly succeeds, setting testB .y = (λ _ → true)
  -}
  testB : Class
  testB .x = true
```

**Comment by andreasabel** [comment]
What is happening here?
- The coverage checker detects a missing clause `testB .y : @(tactic defaultTo x) {Bool → Bool}`.
- It expands this to `testB .y b : @(tactic defaultTo x) {Bool}`, eliminating the function type.
- It then runs the tactic at the wrong type.

A fix is to not expand the clause if there is a tactic attached to the projections.
