### ISSUE TITLE
Parser regression involving `with` and `let`

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5367]
There is a parse error at the `let` now:
```agda
test : (f : Set → Set) (x : Set) → Set
test f x with let z = f x
              in  z
... | _ = x
```
This is accepted by 2.6.1 and before.

In the `CHANGELOG`, I do not see any alert that such code is no longer expected to parse.

Is this change necessary to make the new internalized inspect idiom work, or is it accidential? (The `in` keyword is now used in both `let` and `with`...)

If we agree to this change, there should be an alert in the changelog and a migration recommendation, I suppose.

**Comment by andreasabel** [comment]
The parser was changed in ecb93230ad9327991e542731756cbe1405c85d5f when implementing #4041.

**Comment by andreasabel** [comment]
I tried to understand for one hour why in
```haskell
WithExprs :: { List1 (Named Name Expr) }
WithExprs
  : Application3 'in' Id     '|' WithExprs { named $3  (rawApp $1) <| $5 }
  | Application3 {- empty -} '|' WithExprs { unnamed   (rawApp $1) <| $3 }
  | Application3 'in' Id                   { singleton (named $3 (rawApp $1)) }
  | Application3 {- empty -}               { singleton (unnamed  (rawApp $1)) }
```
I cannot replace `Application3` in the last line by `Application` (which includes `let...in...`).
But I did not understand the problem.  

I _think_ that part of the problem is that for the sake of the `do` notation, a `let` expression does not have to have a `in`-body.  So there is at least some ambiguity in `with let z = x in z` which could be understood as either `with (let z = x) in z` and `with (let z = x in z)`.  I don't happen to see this ambiguity in the grammar, but I do not claim to have an intuition for LALR...

If I have to choose between spending more time fixing the parser or accept this small tightening of the syntax, I opt for the latter.

**Comment by andreasabel** [comment]
It is not only `let`, but also lower precedence expression that do not parse as with-expressions any more.  E.g., this previously correct Agda code is now rejected by the parser, due to the `forall`:
```agda
test : Set₁
test with ∀ (A : Set) → A
... | _ = Set
```
However, such a pointless `with` expression is unlikely to appear in the wild...

**Comment by UlfNorell** [comment]
I had to fix a couple of `with λ` in agda-prelude, so there are some cases in the wild. It's easy to fix though and it's not unreasonable to bracket the lambdas. Probably deserves a changelog entry though.

**Comment by andreasabel** [comment]
So this is an official language change now rather than a regression.
