### ISSUE TITLE
The stack-8.4.4 build is broken on github actions

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5368]
The `stack` workflow breaks for ghc version 8.4.4 since recently, see https://github.com/agda/agda/actions/workflows/stack.yml, e.g. https://github.com/agda/agda/runs/2529451554?check_suite_focus=true. Probably something upstream changed...

**Comment by nad** [comment]
This seems to be a [GHC bug](https://gitlab.haskell.org/ghc/ghc/-/issues/15444) that can perhaps be [fixed](https://www.reddit.com/r/haskell/comments/an405v/ghc_up_installation_fails_with_error/) by installing `libnuma-dev`.
