### ISSUE TITLE
Inconsistency in agda --help

### ISSUE THREAD

**Issue by nad** [agda/agda#5370]
In the output of `agda --help`:
```
             --qualified-instances               use instances with qualified names (default)
             --no-qualified-instances            don't use instances with qualified names (default)
```
It seems as if `--qualified-instances` is the actual default. Is this also the intended default?

**Comment by jespercockx** [comment]
Yes, we had a discussion on this in https://github.com/agda/agda/issues/5030 and decided against changing the default from `--qualified-instances` to `--no-qualified-instances`.
