### ISSUE TITLE
Use GHC 9.0.1 on GitHub workflows

### ISSUE THREAD

**Issue by asr** [agda/agda#5372]
Since `stack 2.7.1` is not in GitHub [virtual environments](https://github.com/actions/virtual-environments) we cannot use GHC 9.0.1 on the GitHub workflows.

**Comment by andreasabel** [comment]
Seems like it is now: https://github.com/actions/virtual-environments/commit/0409144182dc17ad9bed72886ba4aa3506cf8a6d

**Comment by asr** [comment]
Thanks!
