### ISSUE TITLE
Efficient conversion between interaction points and meta-variables

### ISSUE THREAD

**Issue by nad** [agda/agda#5375]
I found the following comment:

https://github.com/agda/agda/blob/5dc884baedcfb4646bc1f4a651dde53c37922642/src/full/Agda/TypeChecking/Monad/MetaVars.hs#L453-L456

I guess it makes sense to make it possible to answer this question, and similar questions, more efficiently. Perhaps it also makes sense to improve the following code:

https://github.com/agda/agda/blob/5dc884baedcfb4646bc1f4a651dde53c37922642/src/full/Agda/TypeChecking/Monad/MetaVars.hs#L393-L398

**Comment by nad** [comment]
I did not optimise `findInteractionPoint_`.

**Comment by andreasabel** [comment]
The milestone needs to be adjusted since this is merged into master.
