### ISSUE TITLE
__IMPOSSIBLE_VERBOSE__ isn't verbose any more

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5379]
Somehow `__IMPOSSIBLE_VERBOSE__` doesn't work anymore, for quite a while already, says my stomach.
https://github.com/agda/agda/blob/b8f3916b107ada9a3b7376c2fccc0b147a2311b7/src/full/Agda/TypeChecking/Monad/Debug.hs#L193-L197
Agda does not actually print the message when instructed so via `-v impossible:10`:
```
$ agda -v impossible:10 Test3.agda 
Checking Test3 (/Users/abel/play/agda/bugs/Issue5378/Test3.agda).
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE_VERBOSE__, called at src/full/Agda/TypeChecking/Monad/Signature.hs:703:32 in Agda-2.6.2-5NrKPj0LeUQ9NGWz0nEnLL:Agda.TypeChecking.Monad.Signature
```
Did this functionality maybe get lost in your refactoring, @rwe ?

**Comment by andreasabel** [comment]
In simple settings, `__IMPOSSIBLE_VERBOSE__` works, but not e.g. in the OP of #5378.
So maybe some monads swallow debug printout?

**Comment by andreasabel** [comment]
Looks like I have found the culprit: `ReduceM`!  This `unsafePerformIO` does not seem to work as expected:
https://github.com/agda/agda/blob/98d4eb09bc23fae73ac93ce56397e514536d13f0/src/full/Agda/TypeChecking/Reduce/Monad.hs#L72-L78

**Comment by andreasabel** [comment]
It seems that fixing line
https://github.com/agda/agda/blob/98d4eb09bc23fae73ac93ce56397e514536d13f0/src/full/Agda/TypeChecking/Monad/Debug.hs#L194
to
```haskell
__IMPOSSIBLE_VERBOSE__ s = do { () <- reportSLn "impossible" 10 s ; throwImpossible err }
```
is enough to get the `unsafePerformIO` to be evaluated. 

I wonder whether we need to change the `Monad.>>` implementation for `ReduceM` to systematically force pure computations of result type `()` to be evaluated.  Something like
```haskell
m1 >> m2 = do
  u <- m1
  u `seq` m2
```

**Comment by jespercockx** [comment]
I've also noticed in the past that debug messages are sometimes dropped in the Reduce monad (this was already the case before my change I believe). The only reliable way I've found to get them to print is by using the CPS versions, so I've been using those in cases where I really needed to see the debug output in the Reduce monad. But if adding the `seq` to the monad instance works, that'd be great and would make debugging much nicer.

**Comment by UlfNorell** [comment]
That should be safe performance-wise, since basically only debugging should use `>>` in the reduce monad.

**Comment by andreasabel** [comment]
Making the `Applicative ReduceM` instance sequential seems to do the trick, e.g.:
```haskell
thenReduce :: ReduceM a -> ReduceM b -> ReduceM b
thenReduce (ReduceM x) (ReduceM y) = ReduceM $ \ e -> x e `seq` y e
```
I also ensure with `seq` that evaluation of idiomatic application `<*>` is left-to-right.

@UlfNorell : Is there something that speaks against
```haskell
-- Andreas, 2021-05-12, issue #5379:
-- It seems more stable to force to evaluate @mf <*> ma@
-- from left to right, for the sake of printing
-- debug messages in order.
apReduce :: ReduceM (a -> b) -> ReduceM a -> ReduceM b
apReduce (ReduceM f) (ReduceM x) = ReduceM $ \ e ->
  let g = f e
      a = x e
  in  g `seq` a `seq` g a
{-# INLINE apReduce #-}
```

**Comment by UlfNorell** [comment]
I'm a little bit worried that throwing seqs into `<*>`, which is used everywhere, might have unpredictable performance consequences. But, for all I know, it might make things a lot faster.

**Comment by andreasabel** [comment]
Here is a MWE demonstrating the effects of optimization levels on mixing `unsafePerformIO` with `Control.Exception.throw`:
```haskell
import Control.Exception
import Debug.Trace

data Foo = Foo deriving Show

instance Exception Foo

five :: Int
five = trace "test:" 5

test :: a
test = five `seq` throw Foo

regular :: IO ()
regular = test `seq` putStrLn "Regular"

main :: IO ()
main = regular `catch` \ Foo -> putStrLn "Exception"
```
Running this with optimizations will skip the debug message `test:`!
```
$ ghc -O0 UnsafePerformIO.hs
[1 of 1] Compiling Main             ( UnsafePerformIO.hs, UnsafePerformIO.o ) [Optimisation flags changed]
Linking UnsafePerformIO ...

$ ./UnsafePerformIO 
test:
Exception

$ ghc -O1 UnsafePerformIO.hs
[1 of 1] Compiling Main             ( UnsafePerformIO.hs, UnsafePerformIO.o )
Linking UnsafePerformIO ...

$ ./UnsafePerformIO 
Exception
```
So, just putting `seq` in is not enough to force `unsafePerformIO`!

**Comment by andreasabel** [comment]
It seems that `seq` isn't resistant to optimization.  It get the debug output if I pattern match on `five`:
```haskell
test = case five of
   5 -> throw Foo
```
So the promise that `seq a b` first evaluates `a` to whnf and then does `b` does not seems to hold in all contexts.  I'll probably never understand lazy evaluation.  Simply because it is contextual, so it never allows local reasoning...

**Comment by nad** [comment]
I tried your example. When I replaced `seq` with `pseq`, then I got the same output with `-O0` and `-O1`.

**Comment by andreasabel** [comment]
> I tried your example. When I replaced `seq` with `pseq`, then I got the same output with `-O0` and `-O1`.

Thanks @nad.

Porting this fix to Agda would mean that we `pseq` every sequence of computations in `ReduceM`... This will likely have a huge negative performance impact due to the overhead of parallelism...

Strangely, my attempts fix the problem on GHC 9.0.1 (not on GHC 8.10.4), but I am not sure that this fact is a bug or a feature of GHC 9.0.1.  E.g. there has been GHC regression https://gitlab.haskell.org/ghc/ghc/-/issues/19181.

Anyway, I am out of steam for this issue, so my plan is to push my first fix (that worked on GHC 9.0.1) and consider this developer-issue fixed by recommendation to develop under GHC 9.0.1.  Future GHCs might possibly bring the issue back...

**Comment by andreasabel** [comment]
I now realize that my MWE might be particular to `Debug.trace`, because the debug message is __not__ optimized away when I implement tracing myself:
```haskell
myTrace :: String -> a -> a
myTrace msg a = unsafePerformIO (putStrLn msg) `seq` a
```
So my MWE isn't actually the right one for the OP.

I filed a GHC issue: https://gitlab.haskell.org/ghc/ghc/-/issues/19841

**Comment by nad** [comment]
> This will likely have a huge negative performance impact due to the overhead of parallelism...

It might impact performance, but `pseq` does not make things run in parallel.

**Comment by andreasabel** [comment]
> > This will likely have a huge negative performance impact due to the overhead of parallelism...
> 
> It might impact performance, but `pseq` does not make things run in parallel.

Could you elaborate?  I thought `pseq` creates a spark...

**Comment by nad** [comment]
No, that is `par`. See the [documentation](https://hackage.haskell.org/package/parallel-3.2.2.0/docs/Control-Parallel.html) of these functions.

**Comment by andreasabel** [comment]
> No, that is `par`. See the [documentation](https://hackage.haskell.org/package/parallel-3.2.2.0/docs/Control-Parallel.html) of these functions.

Thanks for clarifying this for me.  That's good news!

> `pseq :: a -> b -> b infixr 0`
>
> Semantically identical to seq, but with a subtle operational difference: seq is strict in both its arguments, so the compiler may, for example, rearrange a `seq` b into b `seq` a `seq` b. This is normally no problem when using seq to express strictness, but it can be a problem when annotating code for parallelism, because we need more control over the order of evaluation; we may want to evaluate a before b, because we know that b has already been sparked in parallel with par.
>
> This is why we have pseq. In contrast to seq, pseq is only strict in its first argument (as far as the compiler is concerned), which restricts the transformations that the compiler can do, and ensures that the user can retain control of the evaluation order.

So I was mistaken about `seq`.  In particular, with exceptions in `b`, just `seq a b` isn't effective to force side effects in `a`,  if the compiler can rewrite this to `seq b (seq a b)`.
