### ISSUE TITLE
Support cyclic module dependencies

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#538]
Sometimes it's really annoying to factor your modules to avoid cycles. Or perhaps we could have a `.hs-boot`-style solution as a stopgap, if it's easier?

Original issue reported on code.google.com by `pumpkingod@gmail.com` on 5 Dec 2011 at 6:33

**Comment by andreasabel** [comment]
I think cyclic module dependencies are not going to happen anytime soon.
There is no detailed technical proposal here.
Closing...
