### ISSUE TITLE
TODO related to quantities

### ISSUE THREAD

**Issue by nad** [agda/agda#5391]
The TODO related to quantities in `checkPostponedLambda` should perhaps be addressed:

https://github.com/agda/agda/blob/4773470ceb0e8671e128109f4728d6416ff93fae/src/full/Agda/TypeChecking/Rules/Term.hs#L656-L682

@andreasabel, you wrote this comment. Do you know what you had in mind?

**Comment by jespercockx** [comment]
There are lots of TODO's in the source code, a quick grep suggests at least 280. Why are you worried about this one in specific? I'm a bit hesitant to label things as 'bug' unless there's an actual test case of it failing.

**Comment by nad** [comment]
I don't know whether it is a bug or not, I have not studied the code carefully. However, there have been some cases where Agda has not checked quantities correctly, so I think this should be investigated.

**Comment by nad** [comment]
That piece of code is dead. We could remove the `CheckLambda` constructor:

https://github.com/agda/agda/blob/989a13a3dc360f8355a1ea2ded9423b809b84ef6/src/full/Agda/TypeChecking/Monad/Base.hs#L1337-L1344

Is there a reason for keeping it around?

**Comment by nad** [comment]
I pushed a commit removing `CheckLambda` to a separate branch.

**Comment by nad** [comment]
I pushed a commit removing `CheckLambda` to a separate branch.
