### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by nad** [agda/agda#5392]
You can trigger an internal error by trying to "give" `a`:
```agda
open import Agda.Primitive

record R (a : Level) : Set (lsuc a) where
  field
    A : Set a

_ : ∀ a → R {!a!} → Set a
_ = λ _ → R.A
```
```
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/Interaction/BasicOps.hs:156:41 in Agda-2.6.2-DxrwxJHT4OKJYQqSGR9j0:Agda.Interaction.BasicOps
```
Using "solve constraints" also triggers the error. I have encountered this internal error several times.

This is a regression.

**Comment by jespercockx** [comment]
I think I probably broke this in my fix for https://github.com/agda/agda/issues/4727, I'll take a look
