### ISSUE TITLE
CI: user manual build fails, TeX installation too old?

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5394]
I notice that the user manual build fails on CI:
https://github.com/agda/agda/pull/5393/checks?check_run_id=2591398198
```
l.37 \usepackage
                {tgheros}^^M
```
Possible reason: `sphinx-4.x` expects something newer than `texlive-2017`?
[Locally, I am on `sphinx-2.4.4` and `texlive-2020`.]

Would it help to switch CI to ubuntu-20.04 in general?  
Why are we on ubuntu-18.04, btw?

**Comment by asr** [comment]
> Possible reason: `sphinx-4.x` expects something newer than `texlive-2017`?

I don't think so. I guess the problem is a missing TeX Live package.
