### ISSUE TITLE
Workflow `test.yml` fails because of problems with `Post Cache dependencies`

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5395]
Er, it is a bit of a problem if the testsuite isn't run on CI because of an administrative problem in the workflow...
https://github.com/agda/agda/runs/2598173866?check_suite_focus=true
Do we need to fail hard on these cleanup steps?

**Comment by L-TChen** [comment]
Other jobs depend on the cache to restore `stack`’s global store, and the cache is updated in this step.

It does not seem a problem with the workflow itself but GitHub though.

**Comment by andreasabel** [comment]
Fixed itself...
