### ISSUE TITLE
Problem with LaTeX code for multi-line comments with blank lines

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#5398]
In #2588 , @bafain reports the following:

There seems to be a problem with the LaTeX code generated for multi-line comments that contain blank lines.

Agda version: `2.6.2-292237b`
XeTeX version: `3.14159265-2.6-0.999991 (TeX Live 2019/Arch Linux)`
Literate Agda file `Test.lagda`:
```agda
\documentclass{article}
\usepackage{agda}
\begin{document}
\begin{code}
module Test where

{-
-}

{-
A
-}

{-
B
B
-}

{-
C

C
-}
\end{code}
\end{document}
```
Generated LaTeX file `latex/Test.tex`:
```
[..]
\>[0]\AgdaComment{\{-
C

C
-\}}\<%
[..]
```
Error:
```
$ agda --latex Test.lagda
$ cd latex
$ xelatex Test.tex 
[..]
Runaway argument?
{\textcolor {AgdaComment}{\{- C 
! Paragraph ended before \text@command was complete.
<to be read again> 
                   \par 
l.34 \end{code}

? 
```

**Comment by andreasabel** [comment]
A fix seems to be: 
- wrap each non-empty comment line into its own `\AgdaComment` macro,
- output empty comment lines as such.

This is basically https://github.com/agda/agda/issues/2588#issuecomment-607802569 (@nad):
> A simple fix might be to extend `stringLiteral` to handle comments as well.
