### ISSUE TITLE
cifm: Build error with GHC 9.0.1

### ISSUE THREAD

**Issue by asr** [agda/agda#5406]
I cannot install the `closed-issues-for-milestone` program with GHC 9.0.1 because

- [x] deepseq-generics (https://github.com/haskell-hvr/deepseq-generics/issues/10) 
- [x] cryptohash-sha1 (https://github.com/haskell-hvr/cryptohash-sha1/issues/10)
- [x] github (https://github.com/phadej/github/issues/460, https://github.com/phadej/github/pull/456)

**Comment by andreasabel** [comment]
Now, `cabal build --allow-newer=base` works.
