### ISSUE TITLE
Missing licences?

### ISSUE THREAD

**Issue by nad** [agda/agda#5419]
I noticed that the source tree contains some files that seem to have been copied from other projects:

https://github.com/agda/agda/blob/a4560307cb9e2ed30221294fabb870ff6f99f90a/src/data/JS/highlight-hover.js#L1-L3

https://github.com/agda/agda/blob/a4560307cb9e2ed30221294fabb870ff6f99f90a/src/data/JS/biginteger.js#L1-L11

I'm not convinced that the licence conditions associated with these files are satisfied. Perhaps this can be fixed by including the [Haddock](https://github.com/haskell/haddock/blob/ghc-8.8/LICENSE) and [BigInteger](https://github.com/silentmatt/javascript-biginteger/blob/master/LICENSE) licences in `LICENCE`.

**Comment by jespercockx** [comment]
@nad did you have an actual plan for doing something with this? As far as I can tell these licenses have been in Agda for a long time so I don't understand why it is suddenly an issue now.

**Comment by nad** [comment]
I reported this as soon as I saw it. I don't think we should "steal" the code of others without following their licences.

**Comment by nad** [comment]
@ice1000 and @phile314, can you verify that the licences that I added are correct?

**Comment by ice1000** [comment]
> @ice1000 and @phile314, can you verify that the licences that I added are correct?

I think the highlight-hover.js license is fine
