### ISSUE TITLE
Internal error in v2.6.2 release candidate 1

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda#5424]
Just been testing out my own [library](https://github.com/MatthewDaggitt/agda-routing) with the release candidate and I run into the following reproducible error whenever I try to type check [RoutingLib.Routing.Protocols.ShortestWidestPaths](https://github.com/MatthewDaggitt/agda-routing/blob/master/RoutingLib/Routing/Protocols/ShortestWidestPaths.agda) with v1.7-rc1 of the standard library:
```
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/Substitute.hs:136:33 in Agda-2.6.1.3.20210524-532d7bf5851283578419c02fbb50b4ffc0aa65ac0e2fac210b8cc48399568ee1:Agda.TypeChecking.Substitute
```

Will try and condense it down to a minimum example now.

**Comment by MatthewDaggitt** [comment]
I've got the following so far:
```agda
module Test where

open import Data.Maybe using (Maybe; just; nothing)
open import Data.Nat using (ℕ)
open import Data.Product using (_×_; _,_; proj₁; proj₂)
open import Agda.Builtin.Equality using (_≡_; refl)

record RawRoutingAlgebra : Set₁ where
  field
    PathWeight       : Set

module _ (A : RawRoutingAlgebra) where

  open RawRoutingAlgebra A

  postulate 0# : PathWeight
  postulate _≈_ : PathWeight → PathWeight → Set

  PathWeight⁺ : Set
  PathWeight⁺ = Maybe (PathWeight × ℕ)

  data _≈⁺_ : PathWeight⁺ → PathWeight⁺ → Set _ where
    [_] : ∀ {k l} → proj₁ k ≈ proj₁ l × proj₂ k ≡ proj₂ l → just k ≈⁺ just l

  path⁺ : PathWeight⁺ → Maybe ℕ
  path⁺ nothing         = nothing
  path⁺ (just (x , p)) = just p

  r≈0⇒path⁺[r]≈[] : ∀ {r} → r ≈⁺ just (0# , 0) → path⁺ r ≡ just 0
  r≈0⇒path⁺[r]≈[] [ _ , refl ] = refl
```
and I can't seem to make it any smaller.

This is actually giving a slightly different error than the original:
```agda
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/Substitute.hs:84:26 in Agda-2.6.1.3.20210524-532d7bf5851283578419c02fbb50b4ffc0aa65ac0e2fac210b8cc48399568ee1:Agda.TypeChecking.Substitute
```

**Comment by UlfNorell** [comment]
Further shrinking:
```agda
open import Agda.Builtin.Maybe
open import Agda.Builtin.Nat
open import Agda.Builtin.Sigma
open import Agda.Builtin.Equality

record RawRoutingAlgebra : Set₁ where
  field
    PathWeight : Set

module _ (A : RawRoutingAlgebra) where

  open RawRoutingAlgebra A

  PathWeight⁺ : Set
  PathWeight⁺ = Maybe (Σ PathWeight λ _ → Nat)

  data P : PathWeight⁺ → Set where
    [_] : ∀ {k} → snd k ≡ 0 → P (just k)

  badness : (r : PathWeight⁺) → P r → Set
  badness r [ refl ] = Nat
```

**Comment by UlfNorell** [comment]
Some preliminary analysis shows that the impossible is coming from the `conPType` of the instantiated pattern for `r`. With forcing turned on (without forcing the problem moves to the implicit `k` of `[_]`) `r` becomes a lazy match on a sigma:
```agda
  ~(@0 , .0)
```
and the `conPType` of the `_,_` is `Σ (0 .PathWeight) λ _ → Nat`, where somehow the literal `0` has been substituted for what should be the module parameter.

Possibly somewhere we are forgetting that `ConPatternInfo` contains types and mess up a substitution.

**Comment by MatthewDaggitt** [comment]
I've just tried my library with the latest version of the release branch and I can now type check the entire thing :+1: Thanks @UlfNorell!
