### ISSUE TITLE
Remove support for subtyping for erasure and irrelevance

### ISSUE THREAD

**Issue by nad** [agda/agda#5427]
As discussed elsewhere (#5251).

**Comment by andreasabel** [comment]
Options we remove should still parse, but result in an error, in this case `Option --subtyping has been removed in 2.6.3`.  The version when it has been removed isn't so important, we can forgo this.  But Agda shouldn't exhibit signs of Alzheimer's disease:
```
$ agda --subtyping
Error: Unrecognized option:
--subtyping
```
Prior art: https://github.com/agda/agda/blob/a524cbb6e82a5656f4245584e5e6d273acc37126/src/full/Agda/Interaction/Options/Base.hs#L1043-L1053
```
$ agda --sharing
Error: Feature --sharing has been removed (in favor of the Agda abstract machine).
```

**Comment by andreasabel** [comment]
I'll add back Agda's memory...
