### ISSUE TITLE
Agda installation failed

### ISSUE THREAD

**Issue by JW-Schuetz** [agda/agda#5430]
I tried to install agda with the command "cabal install Agda" but it failed. 
The content of the log-file:

[1 of 1] Compiling Main             ( /tmp/cabal-install.-8338/dist-newstyle/tmp/src-8338/Agda-2.6.1.3/dist/setup/setup.hs, /tmp/cabal-inst
all.-8338/dist-newstyle/tmp/src-8338/Agda-2.6.1.3/dist/setup/Main.o )
Linking /tmp/cabal-install.-8338/dist-newstyle/tmp/src-8338/Agda-2.6.1.3/dist/setup/setup ...
Configuring Agda-2.6.1.3...
Preprocessing executable 'agda-mode' for Agda-2.6.1.3..
Building executable 'agda-mode' for Agda-2.6.1.3..
[1 of 2] Compiling Paths_Agda       ( dist/build/agda-mode/autogen/Paths_Agda.hs, dist/build/agda-mode/agda-mode-tmp/Paths_Agda.o )
[2 of 2] Compiling Main             ( src/agda-mode/Main.hs, dist/build/agda-mode/agda-mode-tmp/Main.o )
Linking dist/build/agda-mode/agda-mode ...
Preprocessing library for Agda-2.6.1.3..
happy: src/full/Agda/Syntax/Parser/Parser.y: hGetContents: invalid argument (invalid byte sequence)

**Comment by JW-Schuetz** [comment]
I am using Debian-Linux 10 (Buster) kernel version 5.12.8 and ghc 9.01.

**Comment by asr** [comment]
Please note that Agda 2.6.1.3 does not support GHC 9.0.1 (not related to the above error). You can try Agda 2.6.2 release candidate by running

```
$ cabal get http://hackage.haskell.org/package/Agda-2.6.1.3.20210524/candidate/Agda-2.6.1.3.20210524.tar.gz
$ cd Agda-2.6.1.3.20210524
$ cabal install
```

**Comment by JW-Schuetz** [comment]
I removed ghc 9.0.1 and installed 8.10.4: same problem.

**Comment by asr** [comment]
Which is the output of running the `locale` command?

**Comment by JW-Schuetz** [comment]
Output of locale:
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

Seems to be a problem here?

**Comment by JW-Schuetz** [comment]
I tried "sudo dpkg-reconfigure locales". Maybe this helps.

**Comment by asr** [comment]
I didn't see any problem in your `locale`'s output. Which is the output of `file -i src/full/Agda/Syntax/Parser/Parser.y`?

**Comment by JW-Schuetz** [comment]
Sorry, but in the meantime I decided me to try coq instead. And so I don't have an agda installation anymore. Thank you very much for helping.

**Comment by asr** [comment]
Which are the output of running `cat /etc/default/locale` and `locale -a`?

**Comment by andreasabel** [comment]
Duplicate of #5465.
