### ISSUE TITLE
The JS backend "installs" highlight-hover.js

### ISSUE THREAD

**Issue by nad** [agda/agda#5433]
When you compile using the JS backend the file `highlight-hover.js` is copied into the output directory. @ice1000, is this file used by the JS backend? I guess the answer is no. This can presumably be fixed by moving this file to its parent directory and removing `"JS" </>` from the following code:

https://github.com/agda/agda/blob/914040984c26e827cbc4960f25ee5a7934cbda69/src/full/Agda/Interaction/Highlighting/HTML/Base.hs#L204-L205

**Comment by ice1000** [comment]
> I guess the answer is no.

You are right

**Comment by ice1000** [comment]
So the `JS` directory is for the JS backend only. I guess it's a good idea to document this behavior.

**Comment by nad** [comment]
> So the `JS` directory is for the JS backend only.

Well, the JS backend copies everything from that directory into the target directory:

https://github.com/agda/agda/blob/54dfa724cf496f0cd5a067d6bc8cb8a834445841/src/full/Agda/Compiler/JS/Compiler.hs#L158-L162

> I guess it's a good idea to document this behavior.

Perhaps a file with documentation could be put in the parent directory.
