### ISSUE TITLE
The user manual's explanation of how erasure is checked for constructors does not match the implementation

### ISSUE THREAD

**Issue by nad** [agda/agda#5434]
According to the user manual the type-checker does not enter compile-time mode when checking the types of non-erased constructors, unless the K rule is active. However, the implementation does enter compile-time mode, and instead checks after the fact that the types are OK:

https://github.com/agda/agda/blob/54dfa724cf496f0cd5a067d6bc8cb8a834445841/src/full/Agda/TypeChecking/Rules/Data.hs#L217-L218

https://github.com/agda/agda/blob/54dfa724cf496f0cd5a067d6bc8cb8a834445841/src/full/Agda/TypeChecking/Rules/Data.hs#L305-L307

https://github.com/agda/agda/blob/54dfa724cf496f0cd5a067d6bc8cb8a834445841/src/full/Agda/TypeChecking/Rules/Data.hs#L232-L234

https://github.com/agda/agda/blob/54dfa724cf496f0cd5a067d6bc8cb8a834445841/src/full/Agda/TypeChecking/Rules/Data.hs#L1117-L1141

A reason for doing things in this roundabout way might be that `isType_` does not check quantities. However, I wonder if the currently implemented check is sufficiently strong:

* It is not clear to me that the check handles types with uninstantiated meta-variables correctly (note the use of the pattern `Pi a b`). However, I failed to construct a counterexample.

* @Saizan, do you know why the quantity check is not performed for non-fibrant types? The following code is accepted:
  ```agda
  {-# OPTIONS --two-level --without-K #-}

  open import Agda.Primitive

  data D : SSet → SSet (lsuc lzero) where
    c : (@0 A : SSet) → A → D A
  ```
  This does not match the documentation in the user manual. Note that the following definition is rejected:
  ```agda
  {-# OPTIONS --two-level --without-K #-}

  open import Agda.Primitive

  data D : SSet → SSet (lsuc lzero) where

  _ : SSet (lsuc lzero)
  _ = (@0 A : SSet) → A → D A
  ```
* The current check only looks at domains, and thus accepts the following code:
  ```agda
  {-# OPTIONS --without-K #-}

  data D : Set → Set₁ where
    c : (@0 A : Set) → D A
  ```
  This does not match the documentation in the user manual. Note that the following definition is rejected:
  ```agda
  {-# OPTIONS --without-K #-}

  data D : Set → Set₁ where

  _ : Set₁
  _ = (@0 A : Set) → D A
  ```
  Similarly the following definition is accepted:
  ```agda
  {-# OPTIONS --cubical #-}

  open import Agda.Builtin.Cubical.Path

  data D : Set where
    c : (@0 x y : D) → x ≡ y
  ```

Either the implementation should be changed, or the user manual should be changed.

**Comment by nad** [comment]
> * It is not clear to me that the check handles types with uninstantiated meta-variables correctly (note the use of the pattern `Pi a b`). However, I failed to construct a counterexample.

The following code is rejected, which suggests to me that uninstantiated meta-variables might be handled correctly:
```agda
{-# OPTIONS --without-K #-}

mutual

  data D : Set → Set₁ where
    c : (@0 A : Set) → _ → D _

  _ : (@0 A : Set) → A → D A
  _ = c
```
```
A is not usable at the required modality
when checking that the type (@0 A : Set) → A → D A of the
constructor c fits in the sort Set₁ of the datatype.
```

**Comment by Saizan** [comment]
Yeah, we should check the result type and the boundaries as well.

But for non-fibrant types we should not need this check. The check is trying to make sure that transp/hcomp can be defined (as non-erased) for the type, but we don't define those for non-fibrant types.
