### ISSUE TITLE
Segfault with --ghc-strict

### ISSUE THREAD

**Issue by nad** [agda/agda#5441]
I noticed that one program using `--erased-cubical` segfaulted when compiled using the GHC backend and `--ghc-strict` (but not with `--ghc-strict-data`).

**Comment by nad** [comment]
I could trigger a segfault without using `--erased-cubical`.

**Comment by nad** [comment]
Here is a small test case:
```agda
open import Agda.Builtin.IO using (IO)
open import Agda.Builtin.String using (String)
open import Agda.Builtin.Unit using (⊤)

data D : Set where
  c₁ c₂ : D

f : D → Set → String
f c₁ = λ _ → "OK"
f c₂ = λ _ → "OK"

{-# FOREIGN GHC {-# NOINLINE d_f_8 #-} #-}

x : String
x = f c₁ ⊤

postulate
  putStrLn : String → IO ⊤

{-# FOREIGN GHC import qualified Data.Text.IO #-}
{-# COMPILE GHC putStrLn = Data.Text.IO.putStrLn #-}

main : IO ⊤
main = putStrLn x
```
(Note that the test case might be brittle: it refers to the generated Haskell name for `f`. This is related to issue #5447.)

Agda generates the following code:
```haskell
{-# NOINLINE d_f_8 #-}
-- Bug.D
d_D_2 = ()
data T_D_2 = C_c'8321'_4 | C_c'8322'_6
-- Bug.f
d_f_8 :: T_D_2 -> () -> MAlonzo.Code.Agda.Builtin.String.T_String_6
d_f_8 !v0
  = coe seq (coe v0) (coe (\ !v1 -> "OK" :: Data.Text.Text))
-- Bug.x
d_x_14 :: MAlonzo.Code.Agda.Builtin.String.T_String_6
d_x_14 = coe d_f_8 (coe C_c'8321'_4) erased
```
The segfault goes away if the strict lambda is made lazy. Here is some standalone Haskell code that also triggers a segfault (using GHC 8.10.5 and `-O`):
```haskell
{-# LANGUAGE BangPatterns, ScopedTypeVariables #-}

import Unsafe.Coerce
import GHC.Exts (Any)

erased :: a
erased = unsafeCoerce (\ _ -> erased)

data D = C

{-# NOINLINE f #-}

f :: D -> () -> String
f !_ = unsafeCoerce (\ !(_ :: Any) -> "OK")

main = putStrLn (f C erased)
```
If `Any` is replaced by `()`, then the code works fine.

I noticed that the code above works fine when GHC 9.0.1 is used. My larger piece of code also works fine in this case. Perhaps the problem is an instance of some GHC bug that has been fixed. One option might be to just document that `--ghc-strict` should not be used with older versions of GHC. Another option might be to generate lazy matches for lambdas if the arguments are erased. This is currently only done for top-level definitions. A third option might be to avoid generating any code at all for erased arguments, when possible (#4193).

**Comment by nad** [comment]
> I noticed that the code above works fine when GHC 9.0.1 is used.

It also works fine with GHC 9.2.1.

> One option might be to just document that `--ghc-strict` should not be used with older versions of GHC.

One could perhaps also generate code that is rejected by older versions of GHC. Here is one way to do it:
```haskell
{-# LANGUAGE TemplateHaskell #-}

#if !(MIN_VERSION_GLASGOW_HASKELL(9,0,1,0))
fail "GHC 9.0.1 or later required"
#endif
```
This gives a readable error message, but requires the use of CPP and Template Haskell. Here is an alternative without any extra requirements (`QualifiedDo` was introduced with GHC 9.0.1):
```haskell
{-# LANGUAGE QualifiedDo #-}
```
However, the error message is not very informative.

**Comment by andreasabel** [comment]
If you put `{-# LANGUAGE TemplateHaskell #-}` under an `#if`, it is not so invasive.

Alternatively, one might be able to hack something together with `TypeError`: https://www.youtube.com/watch?v=37uTCZqpqmk
(Also needs some language extensions.)

**Comment by nad** [comment]
I did not want to add a dependency on a C preprocessor, so I went with `QualifiedDo` plus some documentation.

**Comment by nad** [comment]
Is there some simple way to instruct the CI machinery to only run the test case for this issue when GHC 9 or later is used? If not, then I'll disable the test case.

**Comment by andreasabel** [comment]
The JS tests are disabled if `node.js` is not found: https://github.com/agda/agda/blob/05ea7e3a2b9bff07841fef6ba14129221c2a4bb7/test/Compiler/Tests.hs#L117-L128
I suppose something similar would work for `ghc`, evaluating the `--numeric-version`.  You should check that you get the right GHC, though, the one that Agda invokes for compilation.

**Comment by nad** [comment]
I noticed that, even though Agda was compiled using GHC 9, an older version of GHC was used for the GHC backend tests.

**Comment by andreasabel** [comment]
@nad Let me know when it is ready to be cherry-picked.

**Comment by nad** [comment]
The `--ghc-strict` tests are now disabled when `ghc` does not have version 9 or later. I guess this means that, currently, they are not run at all by the CI scripts.
