### ISSUE TITLE
Use names given in data type definitions for case splitting

### ISSUE THREAD

**Issue by googleson78** [agda/agda#5446]
Currently, if I have something like
```agda
k : {A : Set} -> (foo bar : A) -> A
k = {!!}
```
and I do a case split, I get
```agda
k : {A : Set} -> (foo bar : A) -> A
k foo bar = {!!}
```
which is good for UX imo, as it helps me reason about what I'm doing.

When I have
```agda
data Tup (A : Set) : Set where
  tup : (left right : A) -> Tup A

bla : {A : Set} -> Tup A -> A
bla x = {!!}
```
and I split on `x`, a similar nice thing happens:
```agda
bla : {A : Set} -> Tup A -> A
bla (tup left right) = {!!}
```

However, if I happen to have a recursive structure (not sure if this is the reason though):
```agda
data Tree (A : Set) : Set where
  node : (left right : Tree A) -> Tree A

bla1 : {A : Set} -> Tree A -> A
bla1 x = {!!}
```

and split on `x`:
```agda
bla1 : {A : Set} -> Tree A -> A
bla1 (node x x₁) = {!!}
```
the same isn't true.

Is there some reasoning behind this, and if not, would it be desirable for the "automatic naming" to also work in this case?

**Comment by UlfNorell** [comment]
The reason for this heuristic is for cases like natural numbers, where is quite nice to have `n` split into `suc n` and `k` split into `suc k`. But maybe an improvement could be to only do this when there's exactly *one* recursive argument.

**Comment by googleson78** [comment]
That would improve my use case, but it would still "fail" e.g. a list where you name the contained data `head` and `tail`.

Another compromise would be to always use the names, when they are present, but this would impact cases where you're actually using the names for a dependent type.

I don't have enough experience to confidently say which tradeoff is better.

(the "best" solution is to be able to have some annotation manually specifying what behaviour you want, I guess, but that seems to veer off into "overengineering")

**Comment by nad** [comment]
See #3214 and #815.
