### ISSUE TITLE
Agda falling out of stackage

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5449]
Stackage nightly is now switching to GHC 9.0, see https://www.stackage.org/blog/2021/05/2021-05-29-upcomming-ghc-9-on-nightlies

Agda has now been disabled on stackage:
https://github.com/commercialhaskell/stackage/blob/bdd6ae2ebbd0656db4c9ff4f7ae3fdc0616be091/build-constraints.yaml#L5116-L5119

Once we get 2.6.2 out, we need to reactivate Agda on stackage.

**Comment by ice1000** [comment]
> Once we get 2.6.2 out

It seems it's already out

**Comment by andreasabel** [comment]
Agda 2.6.2 is in LTS 18.2 and currently nightly: https://www.stackage.org/lts-18.2/package/Agda-2.6.2
