### ISSUE TITLE
Default vs absolute flags in the library file

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda#5456]
Version 2.6.2 introduced the ability to set flags in the library files, however as a discussion https://github.com/agda/agda-stdlib/issues/1524 has just raised, we have two use cases for this.
 1. To provide a guarantee that *all* files use that flag
 2. To cut-down on boilerplate when *most* files use that flag, and some files override it locally.

I propose we need to split the `flags` field in `agda-lib` files into two: `absolute-flags` (which can't be overridden locally) and `default-flags` (which can be overridden locally). Thoughts?

**Comment by MatthewDaggitt** [comment]
I should add that flags given via the command line would be treated as absolute flags.

**Comment by jespercockx** [comment]
Related: https://github.com/agda/agda/issues/5265

**Comment by nad** [comment]
I suggest that we move this discussion to the other ticket.
