### ISSUE TITLE
Agda incorrectly accepting *any* type

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda#5457]
Came across this fun little bug today in Agda 2.6.2 with Standard Library v1.7:

If you have the following:
```agda
module Test where

open import Agda.Primitive using (Level)
open import Agda.Builtin.Sigma using (_,_; fst)
open import Agda.Builtin.Equality using (_≡_)

open import Function.Definitions using (Injective; Surjective; Bijective)

module _ {a b ℓ₁ : Level} {A : Set a} {B : Set b} (≈ : A → A → Set ℓ₁) (f : A → B) where

  surjective : ((_ , surj) : Bijective ≈ _≡_ f) → Surjective _≡_ ≈ (λ x → fst (surj x))
  surjective (inj , surj) = {!!}
```
then Agda fails to infer the type of the implicit argument `A` in `_≡_`. A bit disappointing, but not a massive problem, let's just provide it:
```agda
  surjective : ((_ , surj) : Bijective ≈ _≡_ f) → Surjective {A = B} _≡_ ≈ (λ x → fst (surj x))
  surjective (inj , surj) = {!!}
```
and Agda stops complaining, great! However I originally made a mistake and typed `{A = A}`  rather than `{A = B}`, and Agda accepted it as well! In fact Agda seems to accept anything for the type of `A`:
```agda
  surjective : ((_ , surj) : Bijective ≈ _≡_ f) → Surjective {A = A} _≡_ ≈ (λ x → fst (surj x))
  surjective : ((_ , surj) : Bijective ≈ _≡_ f) → Surjective {A = Level} _≡_ ≈ (λ x → fst (surj x))
  surjective : ((_ , surj) : Bijective ≈ _≡_ f) → Surjective {A = Bijective ≈ _≡_ f} _≡_ ≈ (λ x → fst (surj x))
```
all type-check fine!

The problem seems to be a combination of things. If you get rid of the pattern matching in the type the problem disappears. If you move the definitions of `Injective`/`Surjective`/`Bijective` into the same file, the problem also disappears...

**Comment by UlfNorell** [comment]
I think this is a bug in the standard library. Here's the definition of `Surjective`:
```agda
module Function.Definitions.Core2  {b ℓ₂} {B : Set b} (_≈₂_ : Rel B ℓ₂) where
...
Surjective : ∀ {a} {A : Set a} → (A → B) → Set (a ⊔ b ⊔ ℓ₂)
Surjective f = ∀ y → ∃ λ x → f x ≈₂ y
```
Note how `A` is free. Here's where it's reexported in `Function.Definitions`:
```agda
module Function.Definitions
  {a b ℓ₁ ℓ₂} {A : Set a} {B : Set b}
  (_≈₁_ : Rel A ℓ₁) -- Equality over the domain
  (_≈₂_ : Rel B ℓ₂) -- Equality over the codomain
  where
...
open Core₂ _≈₂_ public using (Surjective)
```
Nothing pegs the free `A` in the definition of `Surjective` to the parameter `A` of `Function.Definitions`. Asking for the type of `Surjective` in the test module also shows the problem:
```agda
{a b ℓ₁ ℓ₂ : Level} {A : Set a} {B : Set b}
(_≈₁_ : Relation.Binary.Core.Rel A ℓ₁)
(_≈₂_ : Relation.Binary.Core.Rel B ℓ₂)
{a₁ : Level} {A₁ : Set a₁} →
(A₁ → B) → Set (b ⊔ ℓ₂ ⊔ a₁)
```

**Comment by MatthewDaggitt** [comment]
That is very embarrassing :facepalm: Thank you @UlfNorell .
