### ISSUE TITLE
The cabal-installed Agda on Debian looks for IO.agda in the wrong place

### ISSUE THREAD

**Issue by edrx** [agda/agda#5466]
This is a follow-up to this issue:

https://github.com/agda/agda/issues/5465

My file ~/AGDA/test1.agda has just this, plus comments:

```
module test1 where

open import IO

main = run (putStrLn "Hello, World!")
```

I've tried to compile this test.agda in several ways - for example:

```
agda -i. test1.agda
GHC_ENVIRONMENT=agda agda -c test1.agda
```

I always get this error:

```
Checking test1 (/home/edrx/AGDA/test1.agda).
/home/edrx/AGDA/test1.agda:6,1-15
Failed to find source of module IO in any of the following
locations:
  /home/edrx/AGDA/IO.agda
  /home/edrx/AGDA/IO.lagda
  /home/edrx/.cabal/store/ghc-8.8.4/Agda-2.6.2-b2f8eb43cd09b8b95a6e2958c006bc2f47b9966435e6f21d09b053b958e4fc43/share/lib/prim/IO.agda
  /home/edrx/.cabal/store/ghc-8.8.4/Agda-2.6.2-b2f8eb43cd09b8b95a6e2958c006bc2f47b9966435e6f21d09b053b958e4fc43/share/lib/prim/IO.lagda
when scope checking the declaration
  open import IO
```

I do have both an IO.agda and an IO.agdai here, but in a slightly different path... the first one below is the path of the existing IO.agda, and the second is the path that agda tries to use:

```
~/.cabal/store/ghc-8.8.4/Agda-2.6.2-b2f8eb43cd09b8b95a6e2958c006bc2f47b9966435e6f21d09b053b958e4fc43/share/lib/prim/Agda/Builtin/IO.agda
~/.cabal/store/ghc-8.8.4/Agda-2.6.2-b2f8eb43cd09b8b95a6e2958c006bc2f47b9966435e6f21d09b053b958e4fc43/share/lib/prim/IO.agda
```

can we pretend that this is at least a bug in the documentation, in the sense that section "Using cabal" in the manual should explain how to tell agda to look in the right place?

(P.S.: I did some reading and googling and IRCing and testing but I couldn't find a workaround that works. I am a beginner, sorry =/)

**Comment by gallais** [comment]
This looks suspicious as [Agda installs no such file](https://github.com/agda/agda/tree/master/src/data/lib/prim)

> ~/.cabal/store/ghc-8.8.4/Agda-2.6.2-b2f8eb43cd09b8b95a6e2958c006bc2f47b9966435e6f21d09b053b958e4fc43/share/lib/prim/IO.agda

Did you install the standard library too? The program you're trying to compile
[specifically relies on it](https://agda.readthedocs.io/en/v2.6.2/getting-started/a-taste-of-agda.html#building-an-executable-agda-program).

**Comment by edrx** [comment]
I did that a few minutes ago, after a long debugging session on IRC (many thanks to tomsmeding!), and everything works now... sorry for the noise!
