### ISSUE TITLE
Support user-defined implicit prelude? 

### ISSUE THREAD

**Issue by L-TChen** [agda/agda#5484]
It is a feature request about adding the support for user-defined implicit prelude via the existing library management mechanism. The reason is obvious, and it is particularly useful when the option `--no-import-sorts` is specified in a `.agda-lib`.

It should suffice to have a new field called `prelude` so that modules listed in `prelude` are loaded by default for every module. 

(I may try to implement it myself if I have enough time later, but don't expect this to happen soon.)

**Comment by andreasabel** [comment]
> It should suffice to have a new field called `prelude` so that modules listed in `prelude` are loaded by default for every module.

That would mean the user-defined prelude has to reside outside the project (otherwise it would try to load itself).  My user-defined preludes are usually _part of_ the project.

**Comment by L-TChen** [comment]
Good point. I didn't think very carefully. My user-defined preludes are also often part of the project. 

So we need to specify a *directory* or *directories* in a field, say `prelude-directories`, to indicate preludes should not be loaded for modules under those directories. Of course, the modules specified by `prelude` should not load preludes.  

Or maybe we can support a multiple-library project and use some library as a Prelude like Haskell?

**Comment by jespercockx** [comment]
I think it would make more sense in that case to just have two separate libraries (with separate .agda-lib files). We could then provide an option to import in each module of a library a specific (set of) modules from another library by default.

**Comment by L-TChen** [comment]
It sounds reasonable to me, although I'd like to have a local configuration so that I don't have to add another library to the global configuration.

**Comment by andreasabel** [comment]
I often define a module `Library.agda` which imports needed bits from the standard library and maybe defines some more functions absent from the standard library.  Then I `open import Library` in all the project modules, and I didn't find it such a nuisance to repeat this line in every module.  
I thought in Haskell the trend is to move away from an implicit prelude...
A standard prelude is mostly good for scripting where you want to quickly compute stuff without bothering about a lot of imports...

**Comment by L-TChen** [comment]
You have me convinced that an implicit prelude might be a bad idea. I am closing this issue.
