### ISSUE TITLE
Solvable implicit not solved

### ISSUE THREAD

**Issue by laMudri** [agda/agda#5498]
Example file: https://github.com/laMudri/generic-lr/blob/hash-bug/src/Generic/Linear/Example/HashBug.agda. This behaviour occurs with Agda version 2.6.2, and also occurred with the previous version. I have minimised this file, but not any of its dependencies. I can minimise the dependencies on request, but it might take some effort.

## Background

I have a type [`LTree`](https://github.com/laMudri/generic-lr/blob/hash-bug/src/Data/LTree.agda#L17) generated by leaves `[-]` and nullary and binary nodes `ε` and `_<+>_`. Pointers [`Ptr t`](https://github.com/laMudri/generic-lr/blob/hash-bug/src/Data/LTree.agda#L31) in such trees are paths to leaves. The size of a tree is the number of leaves it contains, so for a tree of size `n`, any number less than `n` uniquely identifies (a path to) a leaf. This gives rise to `#_`, reminiscent of and implemented via the `#_` in `Data.Fin`. Relevant definitions:

```agda
  data LTree : Set where
    [-] : LTree
    ε : LTree
    _<+>_ : (s t : LTree) → LTree

  #_ : ∀ {t} (m : ℕ) {m< : True (m <? size t)} → Ptr t
  #_ m {m<} = Fin→Ptr (F.#_ m {m<n = m<})
```

I then have a library for syntax with binding, similar to [`generic-syntax`](https://github.com/gallais/generic-syntax). [Contexts](https://github.com/laMudri/generic-lr/blob/hash-bug/src/Generic/Linear/Syntax.lagda.tex#L23) are a size `s : LTree` together with a vector of types and a vector of annotations, both of size `s`. [Variables](https://github.com/laMudri/generic-lr/blob/hash-bug/src/Generic/Linear/Variable.agda#L24) of type `Γ ∋ A` in such a context `Γ` (constructed by `lvar`) are a pointer into the size together with a proof that the pointed to type is equal to `A` and a proof about the annotations (in the example, I have trivialised everything about annotations by setting them to `⊤`). There is a type `System` of syntax descriptions (such as `Desc` in the example), and a type family [`[_,_]_⊢_`](https://github.com/laMudri/generic-lr/blob/hash-bug/src/Generic/Linear/Syntax/Term.agda#L28) interpreting such a description as a term. When building such terms, `#_` acts like an interpreter for de Bruijn levels, so the example term `lam (lam (app (var (# 1)) (var (# 0))))` is the encoding of λ-term `λx. λy. y x`.

## Behaviour

Many terms can be built perfectly well using `#_`. For example, `test₄` is doing the expected thing. However, `test₀` fails to infer the implicit argument `t` to `#_`. Explicitly providing `t` solves the problem, as does a type annotation (`test₁`). However, the annotation can be given by `C-c C-s`, implying that `_` would work just as well, except that `test₂` shows that this is not the case. Furthermore, `test₃` shows that if the variable's equality proof is not given, then `t` is inferred, even though we can see that `≡.refl` would be a good proof.

I imagine there's some order-sensitivity to the constraint-solving process. It feels like it's trying to solve for `≡.refl` first, failing, and then giving up on `# 1`. I don't really know, though.

**Comment by jespercockx** [comment]
We'll need a small example that clearly demonstrates the problem in order to do anything about this. I'm closing this now, feel free to reopen if you have a small example.
