### ISSUE TITLE
LaTeX backend does not use the \AgdaPragma command. 

### ISSUE THREAD

**Issue by ajrouvoet** [agda/agda#5504]
LaTeX backend does not use the \AgdaPragma command.
Instead it outputs \AgdaKeyword for pragmas in the source.

MWE:

```latex
\documentclass{article}
\usepackage{agda}

\begin{document}

Should display $\AgdaPragma{NON\_TERMINATING}$ but outputs
$\AgdaKeyword{NON\_TERMINATING}$:

\begin{code}
{-# NON_TERMINATING #-}
bad : {A : Set} → A
bad = bad
\end{code}

\end{document}
```

![image](https://user-images.githubusercontent.com/475738/128868321-779965b2-c61d-44b4-b62d-7af8a5160201.png)

**Comment by andreasabel** [comment]
I thought this is intentional.  These are actually keywords according to the lexer, see https://github.com/agda/agda/blob/8aec1e6d655c082de3a3239f528015760862fd2f/src/full/Agda/Syntax/Parser/Tokens.hs#L22-L30
I like the status-quo.

**Comment by ajrouvoet** [comment]
Thanks again for looking into these arguably small issues :)

Ah, that makes some sense from an implementation perspective, but aren't they really pragmas from a user perspective, because they are listed as such on readthedocs. Also, what is the `\AgdaPragma` used for then?

**Comment by andreasabel** [comment]
> Also, what is the `\AgdaPragma` used for then?

I think for additional text in pragmas which doesn't have other highlighting.

**Comment by jespercockx** [comment]
Closing this as working-as-intended.
