### ISSUE TITLE
Release 2.6.2.1

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5513]
It seems that atm we have a few bug fixes and not too many new features (only the erased-cubical compiler) on `master`, so we could cut a minor release.

- [x] move closed 2.6.3 issues to milestone 2.6.2.1
- [x] check that #5546 is included if #5522 is included
- [x] support aeson-2.0 (#5593)
- [x] support hashable-1.4 (see https://github.com/commercialhaskell/stackage/issues/6268)
- [x] support GHC 9.2 (#5442)

**Comment by asr** [comment]
I agree. Agda 2.6.2.1 should be include the "fix" for #5514.

**Comment by andreasabel** [comment]
I think we can release at any time now.  It does not matter too much whether some current bug fixes make it into 2.6.2.1 or have to wait for the next release.

**Comment by asr** [comment]
I created the branch `release-2.6.2.1` for preparing the release.

**Comment by asr** [comment]
As preparation for 2.6.2.1 I created a fresh CHANGELOG for 2.6.3.

**Comment by nad** [comment]
Is the idea to release `--erased-cubical` and `--ghc-strict`? I don't think these new features should be included in a point release, with only limited testing before the release. I am aware of at least one unresolved issue related to `--ghc-strict` (#5441).

**Comment by andreasabel** [comment]
But cannot these new features be released as "experimental", being behind options?

**Comment by nad** [comment]
They could have been part of 2.6.2, but we decided to wait. I think it makes less sense for them to be released with 2.6.2.1.

**Comment by andreasabel** [comment]
This would mean we have to revert the following commits on the release branch!?

- c7083badc [ #5431 ] Added --ghc-strict.
- e4da26c88 [ GHC backend ] Removed some unused code.
- 0606bf2ce [ #5431 ] Added --ghc-strict-data.
- ef2d3d095 [ GHC backend ] Tried to fix #5421.
- 35aa04807 [ JS backend ] Tried to fix #5420.
- 046089db0 [ GHC backend ] Replaced some uses of "erased" with mazErasedName.
- b1a7f085e [ #4701 ] Added support for --erased-cubical to the JS backend.
- d318cd736 [ GHC backend ] Stopped generating "name" definitions.
- cfb41edbd [ GHC backend ] Removed mazIncompleteMatch, which was unused.
- 398263bf3 [ GHC backend ] Added support for generating comments.
- 088661bdf [ GHC backend ] Made generated names more informative.
- 01b4db349 [ GHC backend ] Cleaned up the code a little.
- 7181c83f2 [ #4701 ] Added support for --erased-cubical to the GHC backend.
- 513833c2f [ GHC backend ] Cached the names of some builtins.
- 0134de27c [ GHC backend ] Replaced ReadHsModuleEnv with ReadGHCModuleEnv.
- 6c4ea8055 [ GHC backend ] Renamed GHCCompileEnv to GHCEnv.
- 98e734a0f [ GHC backend ] Moved some definitions to Misc.
- ed4584a1c [ #4701 ] Added --erased-cubical.
- 98251e6c5 [ #4701 ] The GHC and JS backends now reject cubical code.
- 07abb5aee [ #4701 ] Every Definition is now associated with a Language.

Note: this is a sequence of commits that came immediately after the release of 2.6.2.

**Comment by jespercockx** [comment]
Usually we do it the other way around, and cherry-pick the fixes we do want onto the release branch when we want to do a minor release.

**Comment by andreasabel** [comment]
I was hoping for quicker and more light-weight release process this time given we spent half a year on 2.6.2...  

Anyway, the question is maybe rather _who_ does it than exactly how (the person in charge can choose the most efficient way).

**Comment by jespercockx** [comment]
I'm not strongly in favour of either approach, I just mentioned how we did it before. Part of the question is also *why* we are releasing 2.6.2.1 now: is it to fix a few specific critical issues with e.g. the build, or is it just like a regular release but smaller (I get the sense you intended this to be like the latter, but previous minor releases have mostly been like the former.)

**Comment by andreasabel** [comment]
My thinking was we can release the accumulated bugfixes now rather cheaply, without having to worry a lot about regressions---since we didn't add much new features or see wild refactorings.
In general, I think it is good to roll out bugfixes quickly; atm, it may take us over a year to release a fix.

**Comment by nad** [comment]
I seem to recall that we used to have two main branches, one for maintenance and one for new features. With such a setup it might be easier to release bug-fixes. Do you remember why we abandoned this approach? Currently most features and bug-fixes are developed on separate branches and merged into `master` when they are deemed to be sufficiently mature. Merging bug-fixes into two branches instead of one would require more work, but perhaps this could be partially automated (and bug-fixes that did not apply cleanly to the maintenance branch could be delayed to the next major release).

**Comment by andreasabel** [comment]
> I seem to recall that we used to have two main branches, one for maintenance and one for new features. With such a setup it might be easier to release bug-fixes.

My inner pendulum is also swinging back to this setup.  We had it for 2.4.2.x but then abandoned it.  At that time, it became to laborious to merge `maint` into `master` since `master` had accumulated substantial changes (look at the long release notes for 2.5.1!).

I think the policy back then was:
- refactoring and bug fixes into `maint`, then merged into `master`
- new features into `master`

So, the workflow was more complicated, one had often reorganize commits to get the refactorings separately into `maint`.  One had to build everything twice and run the testsuite twice...  But now, with CI in place, this approach could be feasible again.

**Comment by nad** [comment]
Perhaps one could have a bot that pulled everything satisfying some conditions into the maintenance branch:
* The commit should be marked with some magic string.
* The commit should apply cleanly.
* The commit should pass the CI tests.

**Comment by asr** [comment]
I want to release 2.6.2.1 for including support to GHC 8.10.7 and for including some accumulated bug-fixes. I agree that this bug-fix release shouldn't include `--erased-cubical` nor `--ghc-strict`. I shall make some experiments on cherry-picking bug-fixes and reverting the `--erased-cubical` and `--ghc-strict` features.

**Comment by asr** [comment]
> After this message, I shall erase the current `release-2.6.2.1` branch.

I changed my mind. I shall keep the branch and I shall use a different branch for doing some tests.

**Comment by andreasabel** [comment]
@asr: Now that 8.10.7 support is in, do you have time to make the release?

**Comment by andreasabel** [comment]
We will soon need to release a version with `aeson-2` support (see #5593).  2.6.2.1 could be that version.

**Comment by asr** [comment]
> I shall make some experiments on cherry-picking bug-fixes and reverting the `--erased-cubical` and `--ghc-strict` features.

Cherry-pick bug-fixes in a clean release-2.6.2 branch was too complicated. I have not had time in try to revert the the `--erased-cubical` and `--ghc-strict` features but I guess it is also to complicated.

**Comment by andreasabel** [comment]
> Cherry-pick bug-fixes in a clean release-2.6.2 branch was too complicated. I have not had time in try to revert the the `--erased-cubical` and `--ghc-strict` features but I guess it is also to complicated.

Indeed, these features are included in the new `release-2.6.2.1` branch as well (#5662).  But since they are under a flag, I think it is not such a problem if they are released, with a disclaimer. 
I renamed your `release-2.6.2.1` branch to `asr-release-2.6.2.1`.

**Comment by asr** [comment]
> Indeed, these features are included in the new `release-2.6.2.1` branch as well (#5662). But since they are under a flag, I think it is not such a problem if they are released, with a disclaimer. 

I agree. If (correctly) someone says this branch isn't a bug-release because the new features, just let's call it a "release". If also (correctly) someone says the version shouldn't be 2.6.2.1 because this branch isn't a bug-release, I don't see any problem in releasing this branch as 2.6.3 and bumping the current version in `master` to 2.6.4.

> I renamed your `release-2.6.2.1` branch to `asr-release-2.6.2.1`.

Got it.

**Comment by nad** [comment]
> Indeed, these features are included in the new `release-2.6.2.1` branch as well (#5662).

In that case issue #5441 should be fixed before the release. (It is already fixed, but the test case doesn't quite work yet.)

**Comment by nad** [comment]
If `--erased-cubical` is released now, without the already existing fixes of #5448 and #5468, then I think we should document clearly in the changelog that these problems are known, and that they are fixed on the development branch.

I think that, if possible, we should also include the commit that makes `--erased-cubical` support all higher inductive types (#5601, 138f578c08b38be5b4e0a32e431a7d0a20d7e1d1). My guess is that this commit can be cherry-picked without any major problems.

**Comment by andreasabel** [comment]
> If `--erased-cubical` is released now, without the already existing fixes of #5448 and #5468, then I think we should document clearly in the changelog that these problems are known, and that they are fixed on the development branch.

Is any of these fixes causing the regression towards the standard library?

> I think that, if possible, we should also include the commit that makes `--erased-cubical` support all higher inductive types (#5601, [138f578](https://github.com/agda/agda/commit/138f578c08b38be5b4e0a32e431a7d0a20d7e1d1)). My guess is that this commit can be cherry-picked without any major problems.

Indeed, this one cherry-picks cleanly.

**Comment by nad** [comment]
> > If `--erased-cubical` is released now, without the already existing fixes of #5448 and #5468, then I think we should document clearly in the changelog that these problems are known, and that they are fixed on the development branch.
> 
> Is any of these fixes causing the regression towards the standard library?

I [wrote before](https://github.com/agda/agda/issues/5611#issuecomment-949646550) that "This is presumably related to @Saizan's fix (feb4fe4) of #5448 and #5468".

The underlying problem already exists in Agda 2.6.2. However, the problem is in my opinion really bad in the presence of `--erased-cubical`, because one can construct a [program](https://github.com/agda/agda/issues/5448#issuecomment-863963883) that should print `False` but that does print `True`.

Given that we know about this problem I am not in favour of releasing `--erased-cubical` now. If it is not possible to remove the corresponding commits from the release branch, then I suggest that we disable the option (in which case the changelog and the documentation should be updated).

**Comment by andreasabel** [comment]
> I suggest that we disable the option (in which case the changelog and the documentation should be updated).

I think this alternative is more feasible by now.  At least I would not volunteer to 

> remove the corresponding commits from the release branch

The error for option `--erased-cubical` could be:
> Feature --erased-cubical is not available in Agda <= 2.6.2.1.

**Comment by andreasabel** [comment]
I have released Agda 2.6.2.1 from #5678.
