### ISSUE TITLE
GitHub workflows: Missing GHC 8.10.6 test

### ISSUE THREAD

**Issue by asr** [agda/agda#5521]
At the moment, GHC 8.10.6 is not available in CI:
- [x] CI (yet too early: https://github.com/agda/agda/runs/3359722052?check_suite_focus=true)
- [x] https://github.com/haskell/actions/issues/69

**Comment by L-TChen** [comment]
The `haskell/actions/setup` is able to set up GHC 8.10.6 now: https://github.com/agda/agda/pull/5515/checks?check_run_id=3388383531. I will fix this ticket and close the PR later.
