### ISSUE TITLE
master fails to build agda-tests with GHC-9.0.1

### ISSUE THREAD

**Issue by mouse07410** [agda/agda#5528]
```
.  .  .  .  .
test/Fail/Tests.hs:75:3: error: [-Winvalid-haddock, -Werror=invalid-haddock]
    A Haddock comment cannot appear in this position and will be ignored.
   |
75 |   -- | Treats newlines or consecutive whitespaces as one single whitespace.
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

test/Fail/Tests.hs:81:3: warning: [-Wname-shadowing]
    This binding for ‘resDiff’ shadows the existing binding
      defined at test/Fail/Tests.hs:216:1
   |
81 |   resDiff t1 t2
   |   ^^^^^^^
Failed to install Agda-2.6.3
cabal: Error: some packages failed to install:
Agda-2.6.3-Jmf8C4FL9f76mgnQviRUta failed during the building phase. The
exception was:
ExitFailure 1
```

Here's the workaround:
```diff
diff --git a/Agda.cabal b/Agda.cabal
index 16582df04..18d861c61 100644
--- a/Agda.cabal
+++ b/Agda.cabal
@@ -1097,4 +1097,4 @@ test-suite agda-tests
   -- NOTE: If adding or removing flags, also change `.ghci-9.0`
   if impl(ghc >= 9.0)
     ghc-options: -Werror=compat-unqualified-imports
-                 -Werror=invalid-haddock
+                 -- -Werror=invalid-haddock
```

I don't know Haddock, so can't tell what's wrong with line 75 of `test/Fail/Tests.hs` and how to fix it.

**Comment by mouse07410** [comment]
There's also a problem with `size-solver`. The following patch takes care of both this issue and failure to copy built `size-solver` to where the test-scripts expect it to be (`dist/build/size-solver/` directory):
```diff
diff --git a/Agda.cabal b/Agda.cabal
index 16582df04..18d861c61 100644
--- a/Agda.cabal
+++ b/Agda.cabal
@@ -1097,4 +1097,4 @@ test-suite agda-tests
   -- NOTE: If adding or removing flags, also change `.ghci-9.0`
   if impl(ghc >= 9.0)
     ghc-options: -Werror=compat-unqualified-imports
-                 -Werror=invalid-haddock
+                 -- -Werror=invalid-haddock
diff --git a/src/size-solver/Makefile b/src/size-solver/Makefile
index 4167d22e3..c16835f50 100644
--- a/src/size-solver/Makefile
+++ b/src/size-solver/Makefile
@@ -9,12 +9,13 @@ CABAL_INSTALL_OPTS=
 
 .PHONY : install-bin
 install-bin :
+       mkdir -p dist/build/size-solver
 ifdef HAS_STACK
        $(STACK) build size-solver $(STACK_INSTALL_OPTS)
-       mkdir -p dist/build/size-solver
        cp $(shell $(STACK) path --local-install-root)/bin/size-solver dist/build/size-solver/size-solver
 else
        $(CABAL) $(CABAL_INSTALL_CMD) $(CABAL_INSTALL_OPTS)
+       cp $(shell type -p size-solver) dist/build/size-solver/size-solver
 endif
 
 # Tested with shelltestrunner 1.9.
```

**Comment by andreasabel** [comment]
@mouse07410, I cannot reproduce this issue:
1. (`invalid-haddock`):  Could it be that your `haddock` is too old, or the wrong `haddock` was picked up in your experiment?  I tried `cabal v2-test` and it succeeded to compile `agda-tests`.  The `make test` also works (using v1-cabal).
2. (`size-solver`): `make install-bin` uses v1-cabal which automatically places the binary in `dist/build/size-solver/size-solver`.

**Comment by mouse07410** [comment]
> Could it be that your `haddock` is too old?

```sh
$ haddock --version
Haddock version 2.24.0, (c) Simon Marlow 2006
Ported to use the GHC API by David Waern 2006-2008
```
Perhaps it's too new...???

> or the wrong haddock was picked up in your experiment?

```sh
$ type -all haddock
haddock is /Users/ur20980/.ghcup/bin/haddock
$ ll ~/.ghcup/bin/haddock
lrwxr-xr-x  1 ur20980  staff  24 Aug  9 08:01 /Users/ur20980/.ghcup/bin/haddock@ -> ../ghc/9.0.1/bin/haddock
```
There's no other `haddock` on my machine, AFAICT.

> (`size-solver`): make install-bin` uses v1-cabal

I strongly doubt this:
```make
$ bat mk/cabal.mk 
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: mk/cabal.mk
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ 
   2   │ CABAL=cabal
   3   │ 
   4   │ CABAL_VERSION := $(shell $(CABAL) --numeric-version | cut -d. -f1-2)
   5   │ 
   6   │ # Amazing hack to do =< comparison (due to https://stackoverflow.com/questions/3437160).
   7   │ # Relies on there being no cabal 2.10.x or above.
   8   │ ifeq ("2.4","$(word 1,$(sort 2.4 $(CABAL_VERSION)))")
   9   │     CABAL_BUILD_CMD=v1-build
  10   │     CABAL_CLEAN_CMD=v1-clean
  11   │     CABAL_CONFIGURE_CMD=v1-configure
  12   │     CABAL_HADDOCK_CMD=v1-haddock
  13   │     CABAL_INSTALL_CMD=v1-install
  14   │     CABAL_OLD_BUILD_CMD=$(CABAL_BUILD_CMD)
  15   │     CABAL_OLD_INSTALL_CMD=$(CABAL_INSTALL_CMD)
  16   │     CABAL_OLD_CONFIGURE_CMD=$(CABAL_CONFIGURE_CMD)
  17   │ else
  18   │     CABAL_BUILD_CMD=build
  19   │     CABAL_CLEAN_CMD=clean
  20   │     CABAL_CONFIGURE_CMD=configure
  21   │     CABAL_HADDOCK_CMD=haddock
  22   │     CABAL_INSTALL_CMD=install
  23   │     CABAL_OLD_BUILD_CMD=$(CABAL_BUILD_CMD)
  24   │     CABAL_OLD_INSTALL_CMD=$(CABAL_INSTALL_CMD)
  25   │     CABAL_OLD_CONFIGURE_CMD=$(CABAL_CONFIGURE_CMD)
  26   │ endif
───────┴───────────────────────────────────────────────────────
$ cabal --numeric-version | cut -d. -f1-2
3.4
$ 
```
If I interpret the above correctly, the `else` branch is executed.

>  which automatically places the binary in `dist/build/size-solver/size-solver`.

Sorry - no, it doesn't. Not the current/latest Cabal with GHC-9.0.1.

In any case, do you see a problem in applying my patch? It turned out necessary on my machines, and (hopefully!) won't break anything on yours...?

```sh
$ cabal --numeric-version | cut -d. -f1-2
3.4
$ ghc -V
The Glorious Glasgow Haskell Compilation System, version 9.0.1
$ cabal -V
cabal-install version 3.4.0.0
compiled using version 3.4.0.0 of the Cabal library 
$ haddock -V
Haddock version 2.24.0, (c) Simon Marlow 2006
Ported to use the GHC API by David Waern 2006-2008
$ gmake --version
GNU Make 4.3
Built for x86_64-apple-darwin20.1.0
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by andreasabel** [comment]
Do you have `stack.yaml` in the agda project root?  In this case `HAS_STACK` will be true and the cabal branches in the makefiles will not be used.

In `src/size-solver`, I did:
```
rm -rf dist
make install-bin
```
The latter recreated `dist` and also `dist/build/size-solver/size-solver`.

> In any case, do you see a problem in applying my patch? 

I would not object the second part (`mkdir -p dist/build/size-solver`), but we certainly want to keep the (`-Werror=invalid-haddock`), which was added recently, as you can see from the history.

**Comment by andreasabel** [comment]
> Perhaps it's too new...???

Turns out I have an older `haddock`...

But would that matter?  The warning `invalid-haddock` is checked by GHC, not `haddock`.

**Comment by mouse07410** [comment]
> Do you have `stack.yaml` in the agda project root?

Nope! I am not antagonistic to `stack` (like I used to be), but my tool of choice is Cabal.

```ls
$ ll
total 8040
drwxr-xr-x    64 ur20980  staff     2048 Aug 22 08:58 ./
drwxr-xr-x  1435 ur20980  staff    45920 Aug 21 20:41 ../
-rw-r--r--@    1 ur20980  staff     6148 Feb  2  2021 .DS_Store
-rw-r--r--     1 ur20980  staff     2292 Jul 28  2020 .authorspellings
-rw-r--r--     1 ur20980  staff     1557 May 24 22:07 .ghci
-rw-r--r--     1 ur20980  staff     1669 Mar 16 10:53 .ghci-8.0
-rw-r--r--     1 ur20980  staff      288 Jul 30 09:22 .ghci-8.10
-rw-r--r--     1 ur20980  staff      251 Jul 28  2020 .ghci-8.2
-rw-r--r--     1 ur20980  staff      238 Jul 30 09:22 .ghci-8.6
-rw-r--r--     1 ur20980  staff      205 Jul 30 09:22 .ghci-8.8
-rw-r--r--     1 ur20980  staff      232 Jul 30 09:22 .ghci-9.0
drwxr-xr-x    16 ur20980  staff      512 Aug 21 09:30 .git/
drwxr-xr-x     7 ur20980  staff      224 Jan 14  2021 .github/
-rw-r--r--     1 ur20980  staff     1631 Feb  3  2021 .gitignore
-rw-r--r--     1 ur20980  staff      181 May 24 22:07 .gitmodules
-rw-r--r--     1 ur20980  staff     5059 Mar 16 10:53 .hlint.yaml
-rw-r--r--     1 ur20980  staff     5643 Feb  3  2021 .mailmap
drwxr-xr-x     4 ur20980  staff      128 May 24 22:07 .travis/
-rw-r--r--     1 ur20980  staff     4835 Jul 30 09:22 .travis.yml
drwxr-xr-x     3 ur20980  staff       96 Aug  8  2020 .vscode/
-rw-r--r--     1 ur20980  staff    47486 Aug 20 21:57 Agda.cabal
-rw-r--r--     1 ur20980  staff     2763 Aug 19 22:22 CHANGELOG.md
-rw-r--r--     1 ur20980  staff    21218 Jul 30 09:22 HACKING.md
-rw-r--r--     1 ur20980  staff     6414 Jul 30 09:22 LICENSE
-rw-r--r--     1 ur20980  staff    25161 Aug 19 22:22 Makefile
-rw-r--r--     1 ur20980  staff     2021 May 24 22:07 README.md
-rw-r--r--     1 ur20980  staff     4801 Jan 14  2021 Setup.hs
drwxr-xr-x    19 ur20980  staff      608 Jan 14  2021 benchmark/
drwxr-xr-x    16 ur20980  staff      512 Aug 21 08:27 cubical/
drwxr-xr-x     6 ur20980  staff      192 Jul 30 09:33 dist-2.6.3-ghc-8.10.5/
drwxr-xr-x     6 ur20980  staff      192 Aug 20 22:02 dist-2.6.3-ghc-9.0.1/
drwxr-xr-x     4 ur20980  staff      128 Aug 22 08:58 dist-newstyle/
drwxr-xr-x     8 ur20980  staff      256 Aug 19 22:59 doc/
drwxr-xr-x    53 ur20980  staff     1696 Aug 21 08:18 examples/
-rw-r--r--     1 ur20980  staff     1894 Jul 28  2020 fix-whitespace.yaml
-rw-r--r--     1 ur20980  staff      966 Aug 19 22:22 flake.lock
-rw-r--r--     1 ur20980  staff     1512 Aug 19 22:22 flake.nix
-rw-r--r--     1 ur20980  staff      547 Aug  8  2020 hie.yaml
drwxr-xr-x     5 ur20980  staff      160 Jul 28  2020 macros/
-rw-r--r--     1 ur20980  staff      934 Jul 30 09:59 make-bugs-2021-07-30.txt
-rw-r--r--     1 ur20980  staff      934 Aug 20 22:56 make-bugs-2021-08-20.txt
-rw-r--r--     1 ur20980  staff      934 Aug 21 08:09 make-bugs-2021-08-21.txt
-rw-r--r--     1 ur20980  staff  1952172 Jul 30 09:58 make-out-2021-07-30.txt
-rw-r--r--     1 ur20980  staff    54605 Aug 20 22:03 make-out-2021-08-20.txt
-rw-r--r--     1 ur20980  staff    43758 Jul 30 10:31 make-pdf-2021-07-30.txt
-rw-r--r--     1 ur20980  staff    21474 Aug 20 19:25 make-pdf-2021-08-20.txt
-rw-r--r--     1 ur20980  staff   588525 Jul 30 10:31 make-test-2021-07-30.txt
-rw-r--r--     1 ur20980  staff   582565 Aug 20 23:28 make-test-2021-08-20.txt
-rw-r--r--     1 ur20980  staff   582291 Aug 21 08:42 make-test-2021-08-21.txt
drwxr-xr-x     9 ur20980  staff      288 Aug 19 22:22 mk/
drwxr-xr-x    25 ur20980  staff      800 Jul 30 09:22 notes/
-rwxr-xr-x     1 ur20980  staff     5708 Jul 28  2020 release.sh*
drwxr-xr-x    11 ur20980  staff      352 Mar 16 10:53 src/
-rw-r--r--     1 ur20980  staff      577 Jul 30 09:22 stack-8.0.2.yaml
-rw-r--r--     1 ur20980  staff      168 Aug 19 22:22 stack-8.10.5.yaml
-rw-r--r--     1 ur20980  staff      168 Aug 19 22:22 stack-8.10.6.yaml
-rw-r--r--     1 ur20980  staff      453 Jul 30 09:22 stack-8.2.2.yaml
-rw-r--r--     1 ur20980  staff      353 Jul 30 09:22 stack-8.4.4.yaml
-rw-r--r--     1 ur20980  staff      417 Jul 30 09:22 stack-8.6.5.yaml
-rw-r--r--     1 ur20980  staff      258 Jul 30 09:22 stack-8.8.4.yaml
-rw-r--r--     1 ur20980  staff     2384 Jul 30 09:22 stack-9.0.1.yaml
drwxr-xr-x    41 ur20980  staff     1312 Jul 30 09:26 std-lib/
drwxr-xr-x    20 ur20980  staff      640 Jul 30 09:22 test/
-rwxr-xr-x     1 ur20980  staff      303 Jul 28  2020 touchup.sh*
```

> > In any case, do you see a problem in applying my patch?
>
> I would not object the second part (`mkdir -p dist/build/size-solver`), 

May I ask to please do that? Including the `cp $(shell type -p size-solver) dist/build/size-solver/size-solver`?

> but we certainly want to keep the `-Werror=invalid-haddock`, which was added recently, as you can see from the history.

I've no problem with that. I employed that workaround simply because I didn't know how to resolve the "invalid haddock` issue. If you can - it would certainly be preferable.

> Turns out I have an older haddock...

Ha! You see? ;-)

> But would that matter? The warning `invalid-haddock` is checked by GHC, not `haddock`.

Obviously, between new `haddock` and new GHC-9.0.1, something fails that Haddock line. Last successful run was on Jul 30 with GHC-8.10.5, **when `-Werror=invalid-haddock` was not there yet**.

I've no idea what the problem is, not even whether it's an illegal Haddock or a bug in the new GHC that gives a false-positive. Still, either that .hs file needs fixing, or my workaround should be committed... Do you concur?

**Comment by andreasabel** [comment]
The problem is that I have not been able yet to reproduce your problem, I would like to see an independent verification.  Maybe @UlfNorell could try (I suppose you are on macOS, @mouse07410)?

I concur that the current CI does not test for `agda-tests` build with `cabal`.  Maybe this (#5302) is the more fundamental problem we should solve.
This would give us a reproducer for problems like the one you are describing.

**Comment by mouse07410** [comment]
@andreasabel yes, I run on MacOS. 

> I have not been able yet to reproduce your problem, I would like to see an independent verification

Are you saying that `make test` works fine for you with Cabal-3.4.0.0 and GHC-9.0.1 on other platforms??? Or with GHC-9.0.1?

Of course, if the proposed fix does not *break* it for those other platforms, it would still make sense to incorporate it, regardless of whether you can see the problem or not.

Yes, #5302 should be solved - but I think I'm already ahead of that problem, by forcing deletion of the old `fix-whitespace` and rebuilding from the source.

> I concur that the current CI does not test for `agda-tests` build with `cabal`.

Given that Stack enforces certain set of package versions that most certainly differ from those Cabal pulls from Hackage - how can you possibly expect to see the problem reproduced on your CI?

**Comment by andreasabel** [comment]
> Are you saying that `make test` works fine for you with Cabal-3.4.0.0 and GHC-9.0.1 on other platforms??? Or with GHC-9.0.1?

Well, I routinely run, on macOS Mojave, `make test` after `make v1-install`, on GHC-9.0.1 with various versions of Cabal.  I don't run into the problems you are describing.

> how can you possibly expect to see the problem reproduced on your CI?

Maybe you misunderstood me.  I said I agree that CI does at the moment _not_ test the problem.  But I think we should test it with CI, by fixing #5302.

**Comment by mouse07410** [comment]
> Well, I routinely run, on macOS Mojave, `make test` after `make v1-install`, on GHC-9.0.1 with various versions of Cabal. I don't run into the problems you are describing.

Ha! I'm on Big Sur, but honestly I can't see why or how this would make a difference.

Two things that could *potentially* make a difference: I install "other" packages, such as GNU Make, via Macports - not Home Brew. And *all* of my Haskell builds are dynamic.

But with the changes made above (disabling `-Werror=invalid-haddock` for `test-suite` target, and enforcing creation of `src/size-solver/dist/build/size-solver` directory and copying the `size-solver` executable to it), my script succeeds completely, and all the tests pass.

> Maybe you misunderstood me. I said I agree that CI does at the moment not test the problem. But I think we should test it with CI, by fixing #5302.

Yes I did, and I agree with the above. Hopefully, the script I posted [here](https://github.com/agda/agda/issues/5302#issuecomment-903771697) can be a starting point for you.

**Comment by andreasabel** [comment]
@mouse07410: At least your problem with building `agda-tests` _cannot_ be reproduced by the CI I set up (PR #5536), see https://github.com/agda/agda/runs/3450560096?check_suite_focus=true for the macOS instance.

**Comment by mouse07410** [comment]
Replicating your https://github.com/agda/agda/runs/3450560096?check_suite_focus=true, I also successfully built `agda`, `agda-mode`, **and** `agda-tests`, and successfully completed `cabal test`.
```
$ cabal test
Test suite agda-tests: RUNNING...
.  .  .  .  .Ignored 144 disabled tests.
All 3946 tests passed (4262.44s)
Test suite agda-tests: PASS

```

**Comment by andreasabel** [comment]
@mouse07410 wrote:
>  I also successfully built `agda`, `agda-mode`, **and** `agda-tests`, and successfully completed `cabal test`.

This is good news!  Let me know if there are other problems remaining pertaining to this issue.
