### ISSUE TITLE
agda-mode: menubar compile does not work

### ISSUE THREAD

**Issue by mouse07410** [agda/agda#5530]
### Config
macOS Big Sur 11.5.2, GNU Emacs 27.1, GHC-9.0.1, cabal-3.4.0.0, Agda-2.6.3-current-master. Same for `agda-mode` and all the files from `src/data/emacs-mode/`. 

Agda installation passes all the tests included in the repo.

### Problem
Attempt to compile an Agda file (e.g., `hello-world.agda`) fails when done within Emacs from menubar or via C-c C-x C-c. 
Here's the `*agda2*` buffer content:
```
IOTCM "/Users/ur20980/src/hello-world.agda" Interactive Indirect ( Cmd_load_highlighting_info "/Users/ur20980/src/hello-world.agda" )
Agda2> Agda2> (agda2-status-action "")
IOTCM "/Users/ur20980/src/hello-world.agda" Interactive Indirect ( Cmd_load "/Users/ur20980/src/hello-world.agda" [] )
Agda2> (agda2-status-action "")
(agda2-info-action "*Type-checking*" "" nil)
(agda2-status-action "Checked")
(agda2-info-action "*All Done*" "" nil)
((last . 1) . (agda2-goals-action '()))
IOTCM "/Users/ur20980/src/hello-world.agda" Interactive Indirect ( Cmd_compile /Users/ur20980/.ghcup/bin/ghc "/Users/ur20980/src/hello-world.agda" [] )
Agda2> cannot read: IOTCM "/Users/ur20980/src/hello-world.agda" Interactive Indirect ( Cmd_compile /Users/ur20980/.ghcup/bin/ghc "/Users/ur20980/src/hello-world.agda" [] )
IOTCM "/Users/ur20980/src/hello-world.agda" Interactive Indirect ( Cmd_compile /Users/ur20980/.ghcup/bin/ghc "/Users/ur20980/src/hello-world.agda" [] )
Agda2> cannot read: IOTCM "/Users/ur20980/src/hello-world.agda" Interactive Indirect ( Cmd_compile /Users/ur20980/.ghcup/bin/ghc "/Users/ur20980/src/hello-world.agda" [] )
```

Here's the `*Messages*` buffer content:
```
Loading display-line-numbers...done
Loading paren...done
Loading /Users/ur20980/.cabal/share/x86_64-osx-ghc-9.0.1/Agda-2.6.3/emacs-mode/agda2.el (source)...done
For information about GNU Emacs and the GNU system, type C-h C-a.
Loading quail/latin-ltx...done
End of buffer [3 times]
Beginning of buffer
End of buffer [2 times]
Beginning of buffer
```

Here's the source file (and the content of the `hello-world.agda` buffer):
```agda
module hello-world where

open import Agda.Builtin.IO using (IO)
open import Agda.Builtin.Unit using (⊤)
open import Agda.Builtin.String using (String)

postulate putStrLn : String → IO ⊤
{-# FOREIGN GHC import qualified Data.Text as T #-}
{-# COMPILE GHC putStrLn = putStrLn . T.unpack #-}

main : IO ⊤
main = putStrLn "Hello world of Agda!"
```

### Expected result
A successful compilation and execution of that file, like it works from the command line:
```sh
$ agda --compile hello-world.agda
Calling: ghc -O -o /Users/ur20980/src/hello-world -Werror -i/Users/ur20980/src -main-is MAlonzo.Code.QhelloZ45Zworld /Users/ur20980/src/MAlonzo/Code/QhelloZ45Zworld.hs --make -fwarn-incomplete-patterns -fno-warn-overlapping-patterns
Linking /Users/ur20980/src/hello-world ...
$ ./hello-world 
Hello world of Agda!
$
```

**Comment by nad** [comment]
> `cannot read: IOTCM "/Users/ur20980/src/hello-world.agda" Interactive Indirect ( Cmd_compile /Users/ur20980/.ghcup/bin/ghc "/Users/ur20980/src/hello-world.agda" [] )`

It appears as if you chose `/Users/ur20980/.ghcup/bin/ghc` as your compiler backend. You should give the name of the backend (`GHC` or `GHCNoMain`).

**Comment by andreasabel** [comment]
E.g.
```
IOTCM "/Users/abel/agda-erasure/test/Compiler/simple/HelloWorld.agda" NonInteractive Indirect ( Cmd_compile GHC "/Users/abel/agda-erasure/test/Compiler/simple/HelloWorld.agda" [] )
```

That said, we should kiss `Read` goodbye and implement a parser that can also say why it "cannot read".

**Comment by mouse07410** [comment]
@nad right you are! Fixing that took care of the problem.

That said, other editors etc. that I checked, seem to have a **menu choice** for this parameter (not a "free string"), which prevents mistakes like mine. Would be nice to see it here too.

**Comment by nad** [comment]
There is tab completion for the string. However, one can build Agda with extra backends, and there is currently no simple way to figure out which backends are available. If such a feature were added (`--list-backends`), then I guess one could have a menu with exactly those backends that are available.

**Comment by andreasabel** [comment]
> That said, we should kiss `Read` goodbye and implement a parser that can also say why it "cannot read".

We currently indirectly depend on packages `parsec` and `attoparsec`, so we could include one of these as direct dependency and use it as parser in replacement for `Read`.

**Comment by mouse07410** [comment]
> There is tab completion for the string. However, one can build Agda with extra backends, and there is currently no simple way to figure out which backends are available. If such a feature were added (`--list-backends`), then I guess one could have a menu with exactly those backends that are available.

In that case, may I suggest at least some guiding text in the help part of that option? And setting a default value to GHC, with explanation that if GHC is used, it should **not** be a path to the executable? I'm trying to find a way to prevent others from making the same mistake as I did.

**Comment by mouse07410** [comment]
Anyway, my issue is resolved (thanks, @nad ), so I guess I can close this.
