### ISSUE TITLE
Incomplete pattern matching when using instance fields

### ISSUE THREAD

**Issue by berndlosert** [agda/agda#5537]
Consider the following code:

```agda
data Void : Set where
record Unit : Set where
  instance constructor tt

record FooConstraint (a : Set) : Set1 where
  field Foo : a -> Set
open FooConstraint {{...}}

record Test (a : Set) : Set1 where
  field
    {{fooConstraint}} : FooConstraint a
    test : (x : a) {{_ : Foo x}} -> a
    Foo' : a -> Set
    test' : (x : a) {{_ : Foo' x}} -> a
open Test {{...}}

data Bar : Set where
  Bar0 Bar1 : Bar

instance
  FooConstraint-Bar : FooConstraint Bar
  FooConstraint-Bar .Foo Bar0 = Void
  FooConstraint-Bar .Foo Bar1 = Unit

  Test-Bar : Test Bar
  -- I have to pattern match on Bar0, otherwise I get an incomplete pattern matching error.
  Test-Bar .test Bar0 = Bar0
  Test-Bar .test Bar1 = Bar1

  --But not in this case.
  Test-Bar .Foo' Bar0 = Void
  Test-Bar .Foo' Bar1 = Unit
  Test-Bar .test' Bar1 = Bar1
```

If I change the last part of `Test-Bar` to this:

```agda
  Test-Bar .Foo' = Foo
  Test-Bar .test' Bar1 = Bar1
```

then I get an incomplete pattern match again. Something with instance fields is confusing Agda I think. Or maybe I'm confused about how instance fields work when doing this sort of thing.

This was tested on Agda 2.6.2

**Comment by berndlosert** [comment]
Oops, I made a mistake. Setting `Test-Bar .Foo' = Foo` does not produce an incomplete pattern match for `test'`.

**Comment by andreasabel** [comment]
@berndlosert I suppose you could close this issue then, or is there anything left to do?

**Comment by berndlosert** [comment]
Thanks for replying. Yes, I would still like to know why `Test-Bar .test` requires a complete pattern match in contrast to `Test-Bar .test`.

**Comment by berndlosert** [comment]
> in contrast to Test-Bar .test

I meant in contrast to `Test-Bar .test'`.

**Comment by andreasabel** [comment]
(Btw, you should be able to edit your comments to correct typos.)

**Comment by andreasabel** [comment]
Ok, here is a slightly shrunk version:
```agda
open import Agda.Builtin.Bool
open import Agda.Builtin.Nat

data Empty : Set where

record FooConstraint (a : Set) : Set1 where
  field Foo : a → Set
open FooConstraint {{...}}

record Test (a : Set) : Set1 where
  field
    {{fooConstraint}} : FooConstraint a
    test  : (x : a) {{_ : Foo x}} → a
open Test {{...}}

instance
  FooConstraint-Bool : FooConstraint Bool
  FooConstraint-Bool .Foo false = Empty
  FooConstraint-Bool .Foo true  = Nat

  Works-Bool : Test Bool
  Works-Bool .fooConstraint = FooConstraint-Bool
  Works-Bool .test true = true

  Test-Bool : Test Bool
  -- Let the fooConstraints be found by instance search
  Test-Bool .test true = true
  -- I have to pattern match on false, otherwise I get an incomplete pattern matching error.
  -- Test-Bool .test false = false
```

It seems that the heuristics that solves the missing clauses is not up to what you want here.  I think what it does is:
1. Find the clauses not covered by the user:
   ```agda
   Test-Bool .fooConstraint = ?
   Test-Bool .test true = ?
    ```
2. Try to solve these clauses by instance search.
3. Report the unsolved clauses.

Information found at step 2. is not fed back to the coverage checker to eliminate cases.
You can see this when you try to match on absurd in the `false` case:
```agda
  Test-Bool .test false {{()}}
```
Agda reports
```
FooConstraint.Foo (Test.fooConstraint Test-Bool) false should be 
empty, but that's not obvious to me
when checking the clause left hand side
Test-Bool .test false ⦃ () ⦄
```
Since the instance search starts only after coverage checking, the instance `Test.fooConstraint Test-Bool` has not been resolved yet, and the absurd pattern does not match at this point.

**Comment by berndlosert** [comment]
Thanks for the explanation. This is not so bad, so I will close this issue.
