### ISSUE TITLE
Syntax error when a file ends with a goal but no newline

### ISSUE THREAD

**Issue by decorator-factory** [agda/agda#5545]
## Version
I'm using Agda `2.6.3-b44a0b`

## Description
When the file ends with a goal (`{!   !}`) and the file doesn't have a new line character at the end, a syntax error is reported.

Example code:
```agda
_ : Set
_ = {!   !}
```
If the file ends with `\n`, It's parsed correclty:
```
$ agda _Test.agda
Checking _Test (/home/.../_Test.agda).
Unsolved interaction metas at the following locations:
  /home/.../_Test.agda:2,5-12
```
But if the file doesn't end with `\n`, I get a syntax error:
```
$ agda _Test.agda
/home/.../_Test.agda:2,5-5
/home/.../_Test.agda:2,5: Unterminated '{!'
=<ERROR>
   !}...
```

**Comment by andreasabel** [comment]
I introduced this regression in https://github.com/agda/agda/pull/5522.
Needs to be fixed before releasing 2.6.2.1, or the fix (#5522) for #5291 has to be excluded from the release.
