### ISSUE TITLE
Hooray issue 5555!

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5555]
Reserved this issue before #5555 is taken by some boring PR I am going to submit!

**Comment by jespercockx** [comment]
Will we ever run out of numbers? Only time will tell.

**Comment by wenkokke** [comment]
We've got 5554 problems but this isn't one of them.

**Comment by jespercockx** [comment]
Agreed, I'm closing this.

**Comment by andreasabel** [comment]
Using this issue as whiteboard for the latest issue statistics (2021-12-08):
1. Open vs. closed issues (x: days since migration to github, y: number of issues since migration to github)
![agda-issues-open-vs-closed-2015-2021](https://user-images.githubusercontent.com/1155218/145240585-af6522e8-3b62-473f-b01f-e214be351a32.png)

2. Lifetime of open issues (x: age, y: open issues of at most this age)
![agda-issues-age-open-2015-2021](https://user-images.githubusercontent.com/1155218/145240668-7d298be5-ede1-44c7-8878-d156c14a38de.png)

3. Lifetime of closed issues (x: issue lifetime, y: number of issues having lived at most x days)
![agda-issues-age-closed-2015-2021](https://user-images.githubusercontent.com/1155218/145240719-5cd3e112-b3c1-45d5-b6d3-b5776f460ad8.png)

**Comment by andreasabel** [comment]
2023-10-07: we reached 22.222 commits:
<img width="835" alt="Screenshot 2023-10-07 at 16 10 14" src="https://github.com/agda/agda/assets/1155218/a454fe9b-719b-4f9f-b485-ea5879545c97">
