### ISSUE TITLE
Docs (RST): replace `.. versionadded::` by `:since:`?

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5562]
I noticed that we use `.. versionadded:: 2.6.2` in the rst docs.  From the GHC docs, I know the tag `:since: 2.6.2` which would also work our setting and seems to be more standard.  Replace?

Ping @vlopezj and the other `rst` experts...

**Comment by andreasabel** [comment]
`.. versionadded` is documented here:
https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-versionadded
But I fail to google `:since:`.

**Comment by vlopezj** [comment]
I haven't 100% verified it, but it seems that `since` is a custom directive defined by the authors of the GHC docs themselves.

See https://gitlab.haskell.org/ghc/ghc/-/blob/64923cf295ea914db458547432237a5ed1eff571/docs/users_guide/conf.py#L287

**Comment by andreasabel** [comment]
I though I had run a successful experiment using `:since:` in our own docs.  But this is of minor importance.  Closing.
