### ISSUE TITLE
Allow syntax overloading

### ISSUE THREAD

**Issue by barrettj12** [agda/agda#5568]
```agda
postulate
  A B : Set

Fa : A → A
Fa a = a

Fb : B → B
Fb b = b

syntax Fa a = F a
syntax Fb b = F b

G : B → B
G b = F b  -- parse error
```
Agda complains on the last line, saying
```
Don't know how to parse F b. Could mean any one of:
  Fa b
  Fb b
```
However, only the interpretation as `Fb b` actually type-checks. Since it's already building a list of possible interpretations, would it be possible to (attempt to) type-check each of them, and if there is only one that type-checks, use that?

**Comment by barrettj12** [comment]
It looks like the relevant code is the part in [`Syntax/Concrete/Operators.hs`](https://github.com/agda/agda/blob/master/src/full/Agda/Syntax/Concrete/Operators.hs) where an `AmbiguousParseForLHS` or `AmbiguousParseForApplication` error is returned. I might be able to solve this one.

**Comment by jespercockx** [comment]
Thanks for the suggestion. However, I think that it's better to avoid having parsing rely on typechecking, except perhaps in specific well-defined cases (e.g. constructor overloading). Otherwise Agda code would become (even) harder to read and understand.

**Comment by gallais** [comment]
This can also have very important consequences in terms of performance when
ambiguities get nested: an *n* deep `F (... (F x)...)` will lead to *2ⁿ* possible
parses.

**Comment by barrettj12** [comment]
> Thanks for the suggestion. However, I think that it's better to avoid having parsing rely on typechecking, except perhaps in specific well-defined cases (e.g. constructor overloading). Otherwise Agda code would become (even) harder to read and understand.

Okay, fair enough. If you're concerned about understanding, I was thinking about cases such as: given
```agda
C D : Category
F : Functor C D
X Y : ob C
f : hom X Y
```
you could use both the syntax `F X : ob D` and `F f : hom (F X) (F Y)`. But of course, this leaves it up to the user to make sure their code is human-parseable. What about a command-line option that would be off by default?

> This can also have very important consequences in terms of performance when
> ambiguities get nested: an _n_ deep `F (... (F x)...)` will lead to _2ⁿ_ possible
> parses.

True, and if there are _m_ possible interpretations of `F _`, this becomes _mⁿ_. But I can't imagine _m_ and _n_ being very large in practice.

**Comment by JacquesCarette** [comment]
> True, and if there are _m_ possible interpretations of `F _`, this becomes _mⁿ_. But I can't imagine _m_ and _n_ being very large in practice.

If a human wrote the code, that's indeed usually the case. But code generators tend to break those rules quite handily. And yes, I've written an Agda generator, and planning to write more.

Editorial comment: I find it fascinating that in the context of Agda, which lets you be super-precise, you're asking for features that allow ambiguity. I find that forced-precision frees my brain to think about the interesting parts, rather than pre-stressing my short-term memory with overload resolution.

**Comment by barrettj12** [comment]
That's a good point, but on the other hand I think "abuse of notation" exists for a reason - it allows us to declutter notation and avoid explicitly typing things when we don't have to. I think one can also get some mental clarity this way. Certainly, one could use a feature like this to generate unreadable code, but that wouldn't be my intention.

**Comment by barrettj12** [comment]
Anyway, if there's no appetite for this, I am happy to make do without it.

**Comment by JacquesCarette** [comment]
> [...] but on the other hand I think "abuse of notation" exists for a reason - it allows us to declutter notation and avoid explicitly typing things when we don't have to. I think one can also get some mental clarity this way. 

Definitely. The Einstein summation convention always comes to mind as one such example of brilliant notation.

I think dependent types (and their elaborators) are a brilliant means by which to (re)discover how to declutter notation, by looking at what can safely be made implicit.

There is also a common mistake done here: to consider eliding those things that are legal to elide only when "everything is correct". What I mean is, if you write down something (subtly) wrong, then if your uncluttered notation inevitably leads to horrible errors, then maybe that was one step too far.

**Comment by jespercockx** [comment]
This discussion seems to have died out, so I'm closing this issue. Feel free to reopen if you have a concrete proposal and someone would like to implement it.
