### ISSUE TITLE
With on steroids generates wrong patterns on lhs

### ISSUE THREAD

**Issue by ajrouvoet** [agda/agda#5585]
C-c C-c in a hole on the rhs under a `with..in..` generates a pattern with an equation binder:

```agda
test : ∀ {A : Set} → (xs : List A) → Set
test xs with xs in eq
... | z = {!z!} -- C-c C-c
```
Generates:
```
test : ∀ {A : Set} → (xs : List A) → Set
test xs with xs in eq
... | [] | eq = ?
... | x ∷ z | eq = ?
```

I have vague recollections of similar issues perhaps involving rewrite, but couldn't find them in the open issues.

**Comment by gallais** [comment]
I believe this is #513 (and more directly #5355).

**Comment by ajrouvoet** [comment]
:+1: it appears I cannot search.

**Comment by gallais** [comment]
I tend to use labels rather than search by keywords.
