### ISSUE TITLE
Darkening "white smoke" highlight a little?

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda#5586]
It shows up well enough under Aquamacs, but on my Dell XPS running Ubuntu, and emacs' default light theme, the "white smoke" background can only be seen if you know that's it's there, else it's invisible.

Would it be ok to pick a slightly darker grey?  Like "light gray" perhaps?  Even "gainsborough" would be better. Or "AntiqueWhite2" ? "gray92" ?

**Comment by jespercockx** [comment]
I am sympathetic to this view. However, the current shade of white is already a carefully negotiated balance between parties who want it to be completely invisible and others who would like it to be more noticeable. So I think it's rather unlikely that we will change it again.

Just so you know, you can always change the color for yourself in Emacs by customizing the Agda2 group and going to `Agda2 > Agda2 Highlight > Agda2 Highlight Faces` (it's the `Agda2 Highlight Catchall Clause Face` you want to change).

**Comment by andreasabel** [comment]
I hope @jespercockx explanation helped, @JacquesCarette, so I am closing this.

**Comment by JacquesCarette** [comment]
Was the 'negotiation' not done on the tracker? I certainly would have liked to have read it.  In particular, I've found that functions that don't use exact-split end up being extremely difficult to reason about.

**Comment by jespercockx** [comment]
I don't remember where we had the discussion, possibly at one of the Agda meetings. If you really care about clauses holding definitionally, I'd recommend enabling the `--exact-split` flag which will require any non-exact clauses to be marked with a `{-# CATCHALL #-}` pragma.

**Comment by JacquesCarette** [comment]
I think I'm going to 'upgrade' my standard header from `--without-K --safe` to also include `--exact-split` indeed.
