### ISSUE TITLE
Automatic "with" elimination

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#560]
Agda currently appears to have very little automated support for "with" branches. This is inconvenient when creating a proof which invokes a number of functions which use "with". For instance if I had a goal p f g h, where f, g and h all perform a "with" split, it would make the user experience more pleasant if Agda had support for automatically detecting the required "with"s, inserting them and splitting into cases on request. For instance if we assume a function
```agda
f : ℕ → ℕ
f n with pred n
f _ | zero = zero
f _ | suc k = suc zero
```
and a function which proves something about it
```agda
-- before "with" insertion
factoid : (n : ℕ) → f n < suc (suc zero)
factoid n = {!!}
```
then Agda should be able to see that we need to following the same case scheme as f to defined factoid and can thus insert a suitable "with"
```agda
-- after "with" insertion but before case-split
factoid : (n : ℕ) → f n < suc (suc zero)
factoid n with pred n
factoid n | x = {!!}
```
then if we chained this with a case split we could get
```agda
-- after case-split
factoid : (n : ℕ) → f n < suc (suc zero)
factoid n with pred n
factoid n | zero = {!!}
factoid n | suc n' = {!!}
```
To achieve this for an arbitrary number of "with" parameters, we would additionally need a case split which could split on several arguments simultaneously (for valid interactions thereof). This is worthwhile as a 
feature in its own right. It could be exposed to the user: for example if entering "x | y" as an argument to the Ctrl-C Ctrl-C case split function meant "perform a case split on x, and then in all cases perform a case split on y".

Original issue reported on code.google.com by `simo...@gmail.com` on 30 Jan 2012 at 2:24

**Comment by nad** [comment]
The discussion seems to have migrated to #2768.
