### ISSUE TITLE
function application in mutual block considered neutral before adding clauses

### ISSUE THREAD

**Issue by smimram** [agda/agda#5600]
In the following baby example
```agda
{-# OPTIONS --cubical #-}

open import Cubical.Foundations.Prelude
open import Cubical.Data.Nat

data A : Type₁
f : ℕ → A → A

data A where
  s : A → A
  e : {k : ℕ} {n : A} → refl {x = f (suc zero) n} ≡ {!refl {x = s n}!}

f zero n = n
f (suc k) n = s (f k n)
```
we are defining a higher inductive type `A` and a function `f` by mutual induction. In the type `A`, we have an axiom `e` which states that which should have an equality betwen the identity on `f (suc zero) n` (which is _definitionally_ `s n`) and the identity on `s n`. When I typecheck the hole above, I indeed get
```
Goal: s n ≡ s n
Have: s n ≡ s n
```
However, when I fill the hole with what is indicated, the filling is accepted, but afterwards Agda complains that
```
s n != f 1 n of type A
when checking that the expression refl {x = s n} has type
f 1 n ≡ f 1 n
```
which seems to indicate that it is not normalizing terms enough.

Is there an easy workaround for this kind of situations?

**Comment by nad** [comment]
```agda
{-# OPTIONS --cubical #-}

open import Agda.Builtin.Cubical.Path
open import Agda.Builtin.Nat

refl : {A : Set₁} (x : A) → x ≡ x
refl x = λ _ → x

data A : Set₁

f : Nat → A → A

s′ : A → A

f zero    n = n
f (suc k) n = s′ (f k n)

data A where
  s : A → A
  e : {k : Nat} {n : A} → refl (f (suc zero) n) ≡ refl (s′ n)

s′ = s
```

**Comment by smimram** [comment]
Thanks! Your magic trick should help me get going for now, although I'd rather have Agda accept my original code :)

**Comment by Saizan** [comment]
It seems like a `NotBlocked` function application which is stuck on `MissingClauses` should maybe not be considered a neutral, at least for constraints generated during the same mutual block as the function declaration?

@andreasabel what do you think?

**Comment by andreasabel** [comment]
@Saizan : Sounds reasonable, worth trying it in any case!

**Comment by jespercockx** [comment]
I'm re-opening this as it is currently not clear to me whether we want to keep this language change for the release of 2.6.3 (see #1113 and #6113).

**Comment by jespercockx** [comment]
See also https://github.com/agda/agda/issues/118#issuecomment-129021821 for the original incarnation of this issue (which has little to do with cubical)
