### ISSUE TITLE
`make fast-forward-std-lib` does not give me the `master` of the standard library

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5605]
Atm, `make up-to-date-std-lib` and `make fast-forward-std-lib` both give me `v1.7` of the standard library.  I understand the description that the latter should give me the latest version (`master`), rather than giving me the same version.
https://github.com/agda/agda/blob/152efd679d3ab9d983e6f776d58b990904d52c99/HACKING.md#L181-L192
How to I then get the `master` into my submodule `std-lib`?

**Comment by MatthewDaggitt** [comment]
Hmm so there's no particular problem here. The submodule is pointing at the `experimental` branch (as it should):
https://github.com/agda/agda/blob/152efd679d3ab9d983e6f776d58b990904d52c99/.gitmodules#L1-L4

We haven't updated the experimental branch of the standard library since v1.7 as no one has introduced any code that requires incompatible changes in Agda itself. If you like I can merge `experimental` to bring it up to date with the current `master`?

**Comment by andreasabel** [comment]
I remember the logic to be (see my quote from HACKING.md above):
- `up-to-date...` gives me the version that has been verified to work with the current Agda master
- `fast-forward...` gives me the latest version.  If that should happen to work with the current Agda master, I can utter the magic incantation above to set the `up-to-date...` version to the latest one.

I suppose this logic was working as I expect it when the submodule pointed to the `master` branch.

Now as it is pointing to `experimental` it seems that there is an extra step needed in the `agda-stdlib` repo (merging `master` into `experimental`).

I don't know the exact policy for the `experimental` branch; I found just this one document: 
https://github.com/agda/agda-stdlib/blob/8db44892de4369ba73d96c30861642bee1079dae/notes/updating-experimental.txt.  The [release guide](https://github.com/agda/agda-stdlib/blob/8db44892de4369ba73d96c30861642bee1079dae/notes/release-guide.txt) also does not mention it.

>  If you like I can merge `experimental` to bring it up to date with the current `master`?

That would help.  (But it is a one-time shot, is it?)

We could also redirect the submodule to `master` as long as there is full compatibility, could we?  Of course, once Agda breaks compatibility with the standard library, it would have to be reset to `experimental`.  What do you think?

**Comment by MatthewDaggitt** [comment]
> That would help. (But it is a one-time shot, is it?)

Yes it would be.

> We could also redirect the submodule to master as long as there is full compatibility, could we? Of course, once Agda breaks compatibility with the standard library, it would have to be reset to experimental. What do you think?

That sounds like a reasonable course of action. When we get the first PR on experimental I'll change it back to `experimental` in the `.submodule` file.

**Comment by andreasabel** [comment]
OK, I will push a commit that sets `std-lib` to the `master` branch.

**Comment by andreasabel** [comment]
Seems like the `master` does not build with current Agda 2.6.3:
https://github.com/agda/agda/runs/3951728194?check_suite_focus=true#step:8:271
```
/home/runner/work/agda/agda/std-lib/src/Data/Nat/DivMod.agda:205,1-47
Agda.Primitive.Cubical.primTransp
(λ i →
   m /
   Agda.Primitive.Cubical.primComp (λ i₁ → ℕ)
   (λ i₁ .o →
      Agda.Primitive.Cubical.primPOr
      (Agda.Primitive.Cubical.primIMax
       (Agda.Primitive.Cubical.primINeg i) φ)
      i (λ .o₁ → suc m₁) (λ .o₁ → x i₁) _)
   (suc m₁)
   ≤ n / x₁ i)
φ (/-mono-≤ x₂ (s≤s x₃)) is not usable at the required modality
when checking the definition of /-mono-≤
```
I am a bit surprised about such an error though, because the `Data.Nat.DivMod` module does not use `--cubical`.

**Comment by andreasabel** [comment]
Blocked on:
- https://github.com/agda/agda-stdlib/issues/1614
