### ISSUE TITLE
Retire the JS backend?

### ISSUE THREAD

**Issue by nad** [agda/agda#5607]
I've found some bugs in the JS backend that suggest to me that this backend is not used a lot. When developing features like `--erased-cubical` it takes extra time to add support for the JS backend, so I think we should consider moving this backend to a separate repository, like we did with the Epic backend. (Or we could simply delete the code, if no one is interested in maintaining it.)

What do you think?

**Comment by L-TChen** [comment]
or backends can be moved to and maintained as a standalone repository…

**Comment by nad** [comment]
I don't follow you. Are you suggesting to move both the JS and the GHC backends to a single new repository? That would not solve my problem. Or are you suggesting to move the JS backend to a new repository, the GHC backend to another new repository, and the treeless code to a third one?

**Comment by L-TChen** [comment]
Oops, I didn’t see the first suggestion but the deleting part. I’d like to second the first option, anyway.

**Comment by andreasabel** [comment]
There has been interest in the JS backend not too long ago, see
- #3395
- #4962 
- #5002
- UPDATE: #5636

and I tried to improve the testing of the backend in
- #5027

Maybe we should poll on the Agda list to get a better feel for the user base?

**Comment by caryoscelus** [comment]
i'm interested in js backend . haven't figured how one is supposed to use it (though i remember i did that back in the day) , but i need it for my project so unless it's considered total mess that should be rewritten i would be willing to help with it (starting with updating docs on usage since there's virtually none atm)

**Comment by andreasabel** [comment]
Welcome, @caryoscelus !

> haven't figured how one is supposed to use it 

A starter would be how it is used in our testsuite: https://github.com/agda/agda/blob/ff82d4ab9009d5af8bd267661b65614564f63ed6/test/Compiler/Tests.hs#L161-L162

> unless it's considered total mess that should be rewritten

I would not think so, there just has not been much interest in it.

> (starting with updating docs on usage since there's virtually none atm)

PR welcome.  The current compiler docs is here: https://github.com/agda/agda/blob/ff82d4ab9009d5af8bd267661b65614564f63ed6/doc/user-manual/tools/compilers.lagda.rst

**Comment by caryoscelus** [comment]
> A starter would be how it is used in our testsuite:

> "No JS node binary found, skipping JS tests."

quick glance shows that those tests are using node.js . i'm interested in using js in browser setting (and unfortunately i don't know enough of node-browser porting to figure it out) . checking out whether https://github.com/agda/agda-frp-js still works atm

> I would not think so, there just has not been much interest in it.

i see . my current plan is to figure out whether i can use current js backend output or would it be more effective to write dsl js compiler using reflection

**Comment by andreasabel** [comment]
So, don't retire.
