### ISSUE TITLE
Hitting internal error in LHS.hs (2.6.2)

### ISSUE THREAD

**Issue by dorchard** [agda/agda#5612]
I'm sorry I haven't worked out exactly what is triggering yet as my code is so large but I am getting:
```
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/Rules/LHS.hs:322:32 in Agd-2.6.2-60185420:Agda.TypeChecking.Rules.LHS
```
When I expand some extra function equations (refining some pattern matches) this appears but the function equations I am adding are almost identical to the ones already there so I cannot tell what kind of feature is triggering this. All I can say really is that the code is large and has quite a few dot patterns in, although removing the dot patterns on these new cases still gives the error. If I can figure something out I will post more!

**Comment by andreasabel** [comment]
In current master, this error points to https://github.com/agda/agda/blob/d8145b921a95c659d0313c1b84500d73081572cc/src/full/Agda/TypeChecking/Rules/LHS.hs#L322
A MWE (or at least a smallish example) would be greatly appreciated so we can hunt for the bug!

**Comment by andreasabel** [comment]
Ping @dorchard : Did you save the code that produces this error?

**Comment by jespercockx** [comment]
Since we have no way to reproduce the issue, I'm closing this. Feel free to reopen if you encounter the problem again.
