### ISSUE TITLE
`COMPILED_DATA` pragma gives a parse error

### ISSUE THREAD

**Issue by freemagma** [agda/agda#5622]
While trying to get started with agda, I ran into an issue parsing `COMPILE_DATA` pragmas. I have a simple file, as below

```agda
data List (A : Set) : Set where
  []   : List A
  _::_ : A -> List A -> List A

{-# COMPILED_DATA List [] (:) #-}
```

When I run `agda -v 2 test.agda`, I get the following parse error:

```
/home/.../dev/learn_agda/test.agda:5,5-5
/home/.../dev/learn_agda/test.agda:5,5: Parse error
COMPILED_DATA<ERROR>
 List [] (:) #-}
```

I am using agda version 2.6.2 (according to `agda --version`)

**Comment by gallais** [comment]
You seem to be using an old version of the FFI pragmas.
The docs describe the current situation: https://agda.readthedocs.io/en/latest/language/foreign-function-interface.html

**Comment by andreasabel** [comment]
Mmh, yes, maybe we should not remove deleted features from the parser.  We cannot give a good error message this way.  It would be easy to keep obsolete pragmas in the parser and throw a more informative error there.  (So we do not even have to keep them in the concrete syntax!)

**Comment by freemagma** [comment]
Oops thanks! Guess some of the guides / books I was reading are out of date.
