### ISSUE TITLE
Agda does not accept example from documentation

### ISSUE THREAD

**Issue by mdnahas** [agda/agda#5627]
The Agda documentation on this webpage
https://agda.readthedocs.io/en/v2.6.2/language/syntax-declarations.html
has an example:
`syntax Σ A (λ x → B) = [ x ∈ A ] × B`

Agda does not accept it.  It generates the following error message:
 Malformed syntax declaration: syntax must alternate holes (A x B) and non-holes ([ ∈ ] ×)

I believe the " ×" should be removed from the documentation.

I'm running Agda 2.6.0.1 on Ubuntu 20.04.3 LTS.

**Comment by gallais** [comment]
The documentation you're linking to is for Agda 2.6.2 but you're running 2.6.0.1
This is a new feature that is not present in older versions of the compiler.
