### ISSUE TITLE
Emacs mode "C-c C-c Enter" deletes lines

### ISSUE THREAD

**Issue by mdnahas** [agda/agda#5628]
I was doing some simple proofs.  I tried

```
truecanbeproven : ⊤
truecanbeproven = ?

```
In the hole, I typed "C-c C-c Enter", I expected it to be solved, since there is only 1 constructor for ⊤.  But that didn't happen.  The line `truecanbeproven = ?` was deleted!

I don't think it should ever delete lines. 

This was in a literate Agda file with extension .lagda.md.   I'm running Agda 2.6.0.1 on Ubuntu 20.04.3 LTS.

**Comment by gallais** [comment]
What you want in this instance is `C-c C-r`.

By using `C-c C-c` you're attempting to use copattern matching but there is no
copattern to match on! That being said, this should produce an error rather than
simply deleting the line.

**Comment by jespercockx** [comment]
This is already fixed in the latest version of Agda in ~~#3006~~ #4536, in particular https://github.com/agda/agda/commit/6e17bfdf163dadf0491fc98c20897081e616f340.
