### ISSUE TITLE
"agda" on Ubuntu command-line doesn't find std-lib

### ISSUE THREAD

**Issue by mdnahas** [agda/agda#5631]
I have filed this bug with the Ubuntu package managers.  I'm just submitting it here so you all know about it and in case someone comes looking for it here.  It's fine to mark this bug "won't fix" or "not our problem" or whatever.

------------------------

I tried using literate Agda on Ubuntu.  I was able to run Agda perfectly in Emacs.  It loaded libraries without any problem.  But I tried to run agda on the command-line, it had trouble with finding libraries.

Both
`agda --html --html-highlight=code NahasTutorialModule.lagda.md`
and 
`agda NahasTutorialModule.lagda.md`
generated the following error:

```
Checking NahasTutorialModule (/mnt/mass_storage/Desktop/Home/projects/Math_DB/Tools/Agda/NahasTutorialModule.lagda.md).
/mnt/mass_storage/Desktop/Home/projects/Math_DB/Tools/Agda/NahasTutorialModule.lagda.md:701,8-51
Failed to find source of module
Relation.Binary.PropositionalEquality in any of the following
locations:
  /mnt/mass_storage/Desktop/Home/projects/Math_DB/Tools/Agda/Relation/Binary/PropositionalEquality.agda
  /mnt/mass_storage/Desktop/Home/projects/Math_DB/Tools/Agda/Relation/Binary/PropositionalEquality.lagda
  /usr/share/libghc-agda-dev/lib/prim/Relation/Binary/PropositionalEquality.agda
  /usr/share/libghc-agda-dev/lib/prim/Relation/Binary/PropositionalEquality.lagda
when scope checking the declaration
  import Relation.Binary.PropositionalEquality as Eq
```

After some searching, I found that the libraries were located at: /usr/share/agda-stdlib.  I was able to get around the problem with:
`agda -i /usr/share/agda-stdlib/ --html --html-highlight=code NahasTutorialModule.lagda.md`

I'm running Agda 2.6.0.1 on Ubuntu 20.04.3 LTS.

**Comment by gallais** [comment]
Hmmm. The package does not even seem to install the `.agda-lib` file:
https://packages.ubuntu.com/focal/all/agda-stdlib/filelist

So a potential workaround would be to:

1. Copy [this file](https://github.com/agda/agda-stdlib/blob/v1.1/standard-library.agda-lib) into `/usr/share/agda-stdlib`
1. Add the line `/usr/share/agda-stdlib/standard-library.agda-lib` in `~/.agda/libraries-2.6.0.1`
2. Add the line `standard-library` in `~/agda/defaults`

and this should allow you to bypass having to explicitly pass `-i ...`.

You can relay that info on the ubuntu bug report if that helps the packaging
team fix the issue upstream.

**Comment by mdnahas** [comment]
@gallais I forwarded your message.

For reference, here is the link to my bug report for the package:
https://bugs.launchpad.net/ubuntu/+source/agda/+bug/1949641

**Comment by jespercockx** [comment]
Since there's nothing we can do about this issue ourselves, I'm closing this issue.
