### ISSUE TITLE
Restricting the DOT backend to specific libraries

### ISSUE THREAD

**Issue by nad** [agda/agda#5634]
Dependency graphs can become rather large, and I think it would be nice if one could restrict attention to modules from one or more libraries. For this reason I think it would be nice if the following option were added to the DOT backend:
```
--dependency-graph-include=LIBRARY
  Include modules from the given library (default: all libraries).
```
It should be possible to use this option multiple times.

Is there currently a simple way to find out if a given top-level module belongs to a given library?

**Comment by jespercockx** [comment]
You can use `getAgdaLibFiles` from `Agda.TypeChecking.Monad.Options` to get the list of agda-lib files of a given top-level module (usually it's just one unless you have multiple .agda-lib files in the same directory).

**Comment by nad** [comment]
Like this?
```haskell
  let m = toTopLevelModuleName moduleName
  fileName <- findFile m
  libs     <- getAgdaLibFiles (filePath (projectRoot (srcFilePath fileName) m))
```

**Comment by nad** [comment]
I decided to also include modules that are not associated with any library, because often there is a module like `Everything` or `README` that is not re-exported from a library. However, this means that the builtin modules are always included. Apparently there is some problem (#4616) with putting the builtin modules in a library.

**Comment by nad** [comment]
> I decided to also include modules that are not associated with any library, because often there is a module like `Everything` or `README` that is not re-exported from a library.

I changed my mind: files can be considered to be part of a library even if they are not exported by that library.
