### ISSUE TITLE
Macro + instance search = infinite loop during typechecking

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#5637]
It is currently possible to write a macro that calls instance search to call that same macro again (I'm not sure if the example is minimal):
```agda
open import Agda.Builtin.List
open import Agda.Builtin.Reflection renaming (bindTC to _>>=_)
open import Agda.Builtin.Unit

record Macro : Set where
  field theMacro : Term → TC ⊤
open Macro

macro
  runTheMacro : {{Macro}} → Term → TC ⊤
  runTheMacro {{m}} = theMacro m

instance
  loop : Macro
  loop .theMacro hole = unify hole (def (quote runTheMacro) [])

test = runTheMacro
```
Is this intended behaviour? Macros are going through termination checking just like any other function, so I'd guess the answer is no.

**Comment by jespercockx** [comment]
After thinking about it, this is just a specific case of https://github.com/agda/agda/issues/1743, so I'm closing this.

**Comment by andreasabel** [comment]
Since this is a duplicate issue, it needs no milestone.  (The only sound milestone would be the one of its twin.)
