### ISSUE TITLE
Library (`.agda-lib`) files below the project root

### ISSUE THREAD

**Issue by nad** [agda/agda#5644]
Consider the following situation:
* The top-level directory contains the file `top.agda-lib`, and no other files:
  ```
  name:    top
  include: .
  flags:   --safe
  ```
* The subdirectory `A` contains the file `B.agda`:
  ```agda
  module A.B where

  {-# NON_TERMINATING #-}

  easy : (A : Set) → A
  easy = easy
  ```

Would you expect Agda to complain if you run `agda A/B.agda` in the top-level directory? I would have hoped so, but that is not necessarily the case. See what happens if the directory `A` contains `B.agda` and the empty file `sneaky.agda-lib` (and no other files):
```
$ agda A/B.agda
Checking A.B ([…]/A/B.agda).
```

In this case the module name of `A.B` suggests to me that any `.agda-lib` files for this module should be in a parent directory of `A`. I consider the current behaviour to be a bug.

**Comment by jespercockx** [comment]
Yep, I agree that this is a bug. We should probably have a check that the root of the hierarchy of top-level modules corresponds to the location of the .agda-lib file.

**Comment by nad** [comment]
That would mean that you could not have the source files in a subdirectory (like `src`). I've changed the code so that the `.agda-lib` files have to be in or above the root directory.

**Comment by nad** [comment]
I suggested a further change (#6465).

**Comment by nad** [comment]
I noticed that one part of the documentation should be updated:

https://github.com/agda/agda/blob/f926e3d0112026dbaa48d45df30e251765ad72e8/doc/user-manual/tools/interface-files.rst?plain=1#L31-L34

**Comment by andreasabel** [comment]
> I noticed that one part of the documentation should be updated:

Please open a new issue for this.  We should proceed with the release now.  Documentation shortcomings don't count as release-blockers at this stage.

**Comment by nad** [comment]
I have already created a pull request.
