### ISSUE TITLE
Termination checker rejects mutual functions on induction-recursion definition

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda#5646]
I am running agda 2.6.2 and here is an example:

```agda
{-# OPTIONS --without-K --safe #-}

open import Data.Nat

data Exp : Set where


mutual
  Env : Set
  Env = ℕ → D

  data D : Set where
    Π   : D → (t : Exp) → (ρ : Env) → D

variable
  T T′ : Exp
  A A′ : D
  B B′ : D
  a a′ : D
  b b′ : D
  ρ ρ′ : Env

_↦_ : Env → D → Env
(ρ ↦ d) zero    = d
(ρ ↦ d) (suc x) = ρ x

data ⟦_⟧_↘_ : Exp → Env → D → Set where

data _∙_↘_ : D → D → D → Set where

record ΠRT T ρ T′ ρ′ (R : D → D → Set) : Set where
  field
    ⟦T⟧   : D
    ⟦T′⟧  : D
    ↘⟦T⟧  : ⟦ T ⟧ ρ ↘ ⟦T⟧
    ↘⟦T′⟧ : ⟦ T′ ⟧ ρ′ ↘ ⟦T′⟧
    T≈T′  : R ⟦T⟧ ⟦T′⟧


record Π̂ (f a f′ a′ : D) (R : D → D → Set) : Set where
  field
    fa     : D
    fa′    : D
    ↘fa    : f ∙ a ↘ fa
    ↘fa′   : f′ ∙ a′ ↘ fa′
    fa≈fa′ : R fa fa′

mutual

  data 𝕌 : D → D → Set where
    Π  : (A≈A′ : 𝕌 A A′) →
         (∀ {a a′} →
            El A≈A′ a a′ →
            ΠRT T (ρ ↦ a) T′ (ρ′ ↦ a′) 𝕌) →
         -------------------------
         𝕌 (Π A T ρ) (Π A′ T′ ρ′)


  El : 𝕌 A B → D → D → Set
  El (Π A≈A′ RT)  = λ f f′ → ∀ {a b} (inp : El A≈A′ a b) → Π̂ f a f′ b (El (ΠRT.T≈T′ (RT inp)))


mutual

  𝕌-sym : 𝕌 A B → 𝕌 B A
  𝕌-sym (Π {_} {_} {T} {ρ} {T′} {ρ′} A≈A′ RT) = Π (𝕌-sym A≈A′) helper
    where helper : El (𝕌-sym A≈A′) a a′ → ΠRT T′ (ρ′ ↦ a) T (ρ ↦ a′) 𝕌
          helper a≈a′ = record
            { ⟦T⟧   = ⟦T′⟧
            ; ⟦T′⟧  = ⟦T⟧
            ; ↘⟦T⟧  = ↘⟦T′⟧
            ; ↘⟦T′⟧ = ↘⟦T⟧
            ; T≈T′  = 𝕌-sym T≈T′
            }
            where open ΠRT (RT (El-sym (𝕌-sym A≈A′) A≈A′ a≈a′))

  El-sym : ∀ (A≈B : 𝕌 A B) (B≈A : 𝕌 B A) → El A≈B a b → El B≈A b a
  El-sym (Π A≈B RT) (Π B≈A RT′) f≈f′ a≈a′
    with 𝕌-sym A≈B
  ...  | x = {!!}
```

As one can see after loading the file, Agda complains `𝕌-sym A≈B` on the second last line triggers a termination error. But this makes no sense because the same call is used in `𝕌-sym` itself. Is it the case that Agda does not consider `A≈B` as a substructure but only consider subterms of `f≈f` as substructures? If so, why? I really don't see any problem here, or is it a bug?

**Comment by HuStmpHrrr** [comment]
using `where` doesn't fix this problem:
```agda
  El-sym : ∀ (A≈B : 𝕌 A B) (B≈A : 𝕌 B A) → El A≈B a b → El B≈A b a
  El-sym (Π A≈B RT) (Π B≈A RT′) f≈f′ a≈a′ = helper (𝕌-sym A≈B)
    where helper : 𝕌 B A → Π̂ _ _ _ _ (El (ΠRT.T≈T′ (RT′ a≈a′)))
          helper = {!!}
```

**Comment by HuStmpHrrr** [comment]
I think I come up with a general workaround. For every call to `𝕌-sym` in `El-sym`, `El-sym` can take an extra argument instead. When `𝕌-sym` calls `El-sym`, these extra arguments can be filled with the recursive calls to `𝕌-sym` from within `𝕌-sym`. In this way, the termination checker should be happy. But if this method works, doesn't that mean this is a bug?

**Comment by nad** [comment]
The clause with `𝕌-sym (Π {_} {_} {T} {ρ} {T′} {ρ′} A≈A′ RT)` as the left-hand side contains the following nested recursive call: `El-sym (𝕌-sym A≈A′) A≈A′ a≈a′`. Here Agda can see that the argument `A≈A′` is smaller than the (explicit) argument of `𝕌-sym`, but Agda knows nothing about the size of `𝕌-sym A≈A′`. The clause with `El-sym (Π A≈B RT) (Π B≈A RT′) f≈f′ a≈a′` as the left-hand side contains a recursive call to `𝕌-sym A≈B`. Here Agda can see that `A≈B` is smaller than the first argument of `El-sym`, but this does not help, because as noted above there is a call from `𝕌-sym` to `El-sym` for which Agda knows nothing about the size of the first argument.

**Comment by HuStmpHrrr** [comment]
does that mean there is a change to handle problems like this by reordering the arguments? interesting, let me try with my real case.

**Comment by andreasabel** [comment]
It may help that you try to find a termination measure on paper and check whether it is structural (subterm orderings only).  If this is the case, we could pin a possible bug.  Maybe `{-# OPTIONS -v term:40 #-}` may give some insights into which information the termination checker is picking up (sorry, just messy debug output).

**Comment by jespercockx** [comment]
Since there has been no response, I'm closing this issue. Feel free to reopen if you still think there's a bug in Agda.
