### ISSUE TITLE
Fully migrate CI to GHC 9.2

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5649]
Left to do after #5648:
- [x] move workflow `test.yml` to GHC 9.2
- [x] fix stack build on Windows GHC 9.2 (has mysterious errors)
- [x] UPDATE: `.ghci-9.2` file (N.B.: I never use these; over to someone who does)

**Comment by jespercockx** [comment]
The log file includes the following messages:
```
Stack has not been tested with GHC versions above 9.0, and using 9.2.1, this may fail
Stack has not been tested with Cabal versions above 3.4, but version 3.6.0.0 was found, this may fail
```
Perhaps we should disable CI for 9.2.1 on Stack until it is properly supported?

**Comment by andreasabel** [comment]
Well, on my Windows machine, `stack build --stack-yaml=stack-9.2.1.yml --test --no-run-tests` succeeds without error. I have
```
$ stack --version
Version 2.7.3, Git revision 7927a3aec32e2b2e5e4fb5be76d0d50eddcc197f x86_64 hpack-0.34.4
```

@jespercockx @L-TChen If you have access to a Windows machine, can you try there?

> Perhaps we should disable CI for 9.2.1 on Stack until it is properly supported?

It is sort of disabled:
https://github.com/agda/agda/blob/6cb77e1a216098d6a4e273f6750dbf4445953272/src/github/workflows/stack.yml#L61

**Comment by fabianhjr** [comment]
Same warning on NixOS with same version:
```
stack --version                             Thu 18 Nov 2021 11:50:21 AM CST
2.7.3 x86_64 hpack-0.34.5
```

Though, including the revision on your version call seems to indicate additional patches.

EDIT: NVM, that is the commit of the release: https://github.com/commercialhaskell/stack/commit/7927a3aec32e2b2e5e4fb5be76d0d50eddcc197f

**Comment by andreasabel** [comment]
Ok, I disabled the stack/Win/9.2.1 workflow.  Github actions does not properly support _allowed failure_.
