### ISSUE TITLE
cifm: Support GHC 9.2

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5655]
Blocked on:
- [ ] `basement` (https://github.com/haskell-foundation/foundation/issues/554, https://github.com/haskell-foundation/foundation/pull/555) via `github` (https://github.com/phadej/github/issues/468)

**Comment by fabianhjr** [comment]
Seems like a new basement release won't happen soon; the following change (using the branch of the PR) makes agda compile and test on the stack-9.2.1.ymal config:

```
diff --git a/stack-9.2.1.yaml b/stack-9.2.1.yaml
index 0a5cfa7cd..72f29e198 100644
--- a/stack-9.2.1.yaml
+++ b/stack-9.2.1.yaml
@@ -20,6 +20,10 @@ extra-deps:
 - base-compat-0.12.1
 - base-compat-batteries-0.12.1
 - base-orphans-0.8.6
+- git: https://github.com/TomMD/foundation
+  commit: 0bb195e1fea06d144dafc5af9a0ff79af0a5f4a0
+  subdirs:
+    - basement
 - bifunctors-5.5.11
 - blaze-builder-0.4.2.2
 - blaze-html-0.9.1.2
```

**Comment by andreasabel** [comment]
Thanks @fabianhjr !  
Since it is only our internal release tool `closed-issues-for-milestone` that is blocked on `basement`, we can wait a few months.  Of course, it is not nice for a maintainer of a package like `basement` to let the community wait...
I might try your workaround at some time, though...

**Comment by andreasabel** [comment]
Actually, the `github` package can be used _now_ with flag `+openssl` (thanks!, @phadej).
Thus, we do not need to wait for `basement`.
