### ISSUE TITLE
Internal error with postfix projection

### ISSUE THREAD

**Issue by barrettj12** [agda/agda#5657]
I ran the code
```agda
open import Relation.Binary.PropositionalEquality using (_≡_)

record Magma : Set₁ where
  field
    A : Set
    _+_ : A → A → A

record CommMagmaFam (I : Set) : Set₁ where
  field
    M : I → Magma
    comm : (i : I) → let open Magma (M i) in
      (a b : M i .A) →
      a + b ≡ b + a
```
and Agda told me
```
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full\Agda\TypeChecking\Rules\Application.hs:968:23 in Agda-2.6.3-8qnHSysNZe1HBYMluPboCb:Agda.TypeChecking.Rules.Application
```

I am running agda/agda@6cb77e1, using VSCode's agda-mode on Windows 10.

**Comment by andreasabel** [comment]
Here is a version without the standard-library:
```agda
open import Agda.Builtin.Equality using (_≡_)

record Magma : Set₁ where
  field
    A : Set
    _+_ : A → A → A

record CommMagmaFam (I : Set) : Set₁ where
  field
    M : I → Magma
    comm : (i : I) → let open Magma (M i) in
      (a b : M i .A) →
      a + b ≡ b + a
```
The error given by Agda 2.5.2 - 2.6.1 is:
```
Set should be a function type, but it isn't
when checking that (M i) is a valid argument to a function of type Set
```
This is the correct error.
The crash happens starting in 2.6.2.
https://github.com/agda/agda/blob/058e350623c73c16b1149841f482fde20c73c53f/src/full/Agda/TypeChecking/Rules/Application.hs#L968
Seems I introduced this regression in https://github.com/agda/agda/commit/535da237c2aec18099b75071e05941e7899c5608 when fixing #3289.

**Comment by andreasabel** [comment]
This seems to be the MWE:
```agda
record R : Set₁ where
  field A : Set

postulate r : R
open R r

fail : Set
fail = r .A
```
The scope checker recognizes `.A` as projection, but then `isProjection` fails because the `open` statement brought `A : Set` into scope, which is clearly not a projection.
Seems like the solution is simply to not throw `__IMPOSSIBLE__` at loc.cit., since it is possible if the user made a mistake.
