### ISSUE TITLE
Documentation on the new sort system?

### ISSUE THREAD

**Issue by ice1000** [agda/agda#5667]
/cc @ecavallo @Saizan @jespercockx 

I want to learn about Agda's new `--two-levels` sort system, and I am particularly interested in the following questions:

+ `A : SSet i` and `B : Set j`, what's the type of `A -> B`?
+ `A : IUniv` and `B : SSet i`, what's the type of `A -> B`?
+ If `record A : SSet k`, can we add a field whose type is of type `Set j` to it?

There can be many, but can be summarized as "rules relevant to `SSet` and `IUniv`". I am having trouble navigating the relevant source code 😢

**Comment by jespercockx** [comment]
The core PTS rules of Agda's sort system can be found at https://github.com/agda/agda/blob/4173fd6ddc28ec2e0134c44da2e17b0f67c406d4/src/full/Agda/TypeChecking/Substitute.hs#L1492-L1504 and https://github.com/agda/agda/blob/4173fd6ddc28ec2e0134c44da2e17b0f67c406d4/src/full/Agda/TypeChecking/Substitute.hs#L1539-L1564 The rules for checking whether a type fits in a data/record type are implemented at https://github.com/agda/agda/blob/master/src/full/Agda/TypeChecking/Rules/Data.hs#L1667-L1714, which itself relies on the basic comparison `leqSort` implemented at https://github.com/agda/agda/blob/master/src/full/Agda/TypeChecking/Conversion.hs#L1152-L1274

To answer your questions:
- `(Type a        , SSet b       ) -> Just $ SSet $ levelLub a b`, so the type of `A -> B` is `SSet (a ⊔ b)`
- `(IntervalUniv  , SSet b       ) -> Just $ SSet $ b`, so the type of `A -> B` is `SSet b`
- `(Type a  , SSet b  ) -> leqLevel a b`, so the answer is yes, assuming `j =< k`.

There is some documentation that I wrote at https://agda.readthedocs.io/en/v2.6.2/language/sort-system.html#agda-s-sort-system, but it would be great if this could be extended with the sorts that were added more recently.

**Comment by ice1000** [comment]
Niiiice!!! Thank you!!

**Comment by L-TChen** [comment]
I believe it is based on the two-level type theory by Annenkov et al. (https://arxiv.org/abs/1705.03307), so perhaps a pointer to this arXiv paper or their earlier CSL paper is sufficient for now.

**Comment by ice1000** [comment]
Closing as answered -- this is actually just a question anyway.

**Comment by ice1000** [comment]
Update:

`funSort`:
https://github.com/agda/agda/blob/6a92d584c70a615fdc3f364975814d75a0e31bf7/src/full/Agda/TypeChecking/Substitute.hs#L1602-L1647
