### ISSUE TITLE
Remove `doc/user-manual.pdf` from the released tarball?

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5675]
In a49b8d869bd9d8261834030bc232f0b34b98b4f0 @L-TChen removed `doc/user-manual.pdf` from the extra-files in `Agda.cabal`, in connection with #4216.  Since then, adding it manually (and later remove it again) was part of the release procedure.  This is a complication in the release procedure, which is arguably too complicated already.

My suggestion is to simply not ship `user-manual.pdf` in the tarball.  I suspect hardly anyone looks for it there.  Most will install Agda without downloading the tarball explicitly, so get no knowledge that a user manual is sitting somewhere in the installation tree.  Actually, I do not even think it ends up in the installation tree at all, at least I cannot find it there:
```
~/.cabal$ find . -name "*.pdf" 
./share/doc/x86_64-osx-ghc-8.4.4/lhs2tex-1.22/doc/Guide2.pdf
```
(So there is only a single package on my system that comes with a `.pdf` documentation.  Agda actually does not.)

If there are no objections, I will not ship `user-manual.pdf` with 2.6.2.1, and remove the respective instructions from the release procedure.

**Comment by asr** [comment]
I disagree with the proposal. Arguably it is more convenient browse/search a PDF file than the online documentation.

> I suspect hardly anyone looks for it there. Most will install Agda without downloading the tarball explicitly, so get no knowledge that a user manual is sitting somewhere in the installation tree.

From the same reason we should also remove the release-notes from the tarball and I also disagree.

And the complication in the release procedure is too small.

**Comment by nad** [comment]
> Actually, I do not even think it ends up in the installation tree at all, at least I cannot find it there:
> 
> ```
> ~/.cabal$ find . -name "*.pdf" 
> ./share/doc/x86_64-osx-ghc-8.4.4/lhs2tex-1.22/doc/Guide2.pdf
> ```

I don't think the tar-ball uploaded to Hackage contains everything that is included in the tar-ball that we link to from the Agda Wiki.

**Comment by andreasabel** [comment]
@asr wrote:
> I disagree with the proposal. Arguably it is more convenient browse/search a PDF file than the online documentation.

The PDF is on readthedocs: https://agda.readthedocs.io/_/downloads/en/v2.6.2/pdf/

> From the same reason we should also remove the release-notes from the tarball and I also disagree.

We could.  I would not object.  They are also not ending up in the install tree.  Maybe that is intended?
The difference with the release-notes is that they don't cause extra work in the release.

> And the complication in the release procedure is too small.

Large enough to get it wrong.  E.g., the tag `v2.6.2` is broken because there `Agda.cabal` mentions `doc/user-manual.pdf`which does not exist.  See https://github.com/agda/agda/commit/246a229faea2ef2fa53caf491ff8a2d72dd7510c#r61060435.

Mainly I am bringing this issue up _because_ things have gone wrong in the past.

**Comment by andreasabel** [comment]
@nad wrote:
> I don't think the tar-ball uploaded to Hackage contains everything that is included in the tar-ball that we link to from the Agda Wiki.

github also creates a tarball from the sources when we push a tag: See e.g. https://github.com/agda/agda/releases/tag/v2.6.2.  This does not include generated files, of course.

**Comment by asr** [comment]
> The PDF is on readthedocs: https://agda.readthedocs.io/_/downloads/en/v2.6.2/pdf/

I didn't know it. So, we can remove the PDF from the tarball.

**Comment by andreasabel** [comment]
> So, we can remove the PDF from the tarball.

Excellent!
