### ISSUE TITLE
let: projecting behaves differently than pattern matching

### ISSUE THREAD

**Issue by omelkonian** [agda/agda#5680]
*AGDA: 2.6.2*

Projecting the first part of a dependent pair works fine, but pattern matching and ignoring the second part leads to internal error.
```agda
open import Agda.Builtin.Sigma

postulate X : Set
variable x : X
postulate
  _≺_ : X → X → Set
  H : ∀ x → Σ _ (_≺ x)

module M (x : X) where
  postulate z : X

data C : Set where
  _ :
    let
      -- y = fst (H x) -- works!
      y , _ = H x  -- raises internal error :S
      open M y
    in
    C
```
```
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/Serialise/Instances/Internal.hs:106:26 in Agda-2.6.2-5d92e0bc62f6513c7aa12fd932a1e27cdc986b039aa0267ec831a1bc44eb00c1:Agda.TypeChecking.Serialise.Instances.Internal
```

The bug strangely appears only when you mix generalized variables, modules and dependent products.
Similar issues (#5584, #5544) have been fixed in more recent versions, so this might be an obsolete issue.

**Comment by andreasabel** [comment]
Thanks for reporting!
This is fixed on the Agda 2.6.2.1 release candidate.  Hopefully we ship soon!
