### ISSUE TITLE
Record constructors not correctly preserving instances

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda#5686]
Consider the following code:
```agda
open import Agda.Builtin.Nat

module Test where

record B : Set where
  constructor ⟨_⟩
  field
    instance n : Nat

mkB : ∀ {{_ : Nat}} → B
mkB {{n}} = ⟨ n ⟩ 

id : B → B
id ⟨ n ⟩ = mkB
```
I would expect `id` to work as `n` is declared as an instance argument in the constructor field. However Agda appears to lose the fact that `n` is an instance argument when pattern matching on the constructor. You can see this by replacing `id` with:
```agda
id : B → B
id ⟨ n ⟩ = mkB {{?}}
```
and then checking the buffer which gives:
```
Goal: Nat
————————————————————————————————————————————————————————————
n : Nat
```
instead of the expected:
```
Goal: Nat
————————————————————————————————————————————————————————————
n : Nat              (instance)
```

**Comment by jespercockx** [comment]
To make a record field into an instance, you need to mark it with `{{ }}`, like this:
```agda
open import Agda.Builtin.Nat

record B : Set where
  constructor mkB
  field
    {{n}} : Nat
open B

pattern ⟨_⟩ x = mkB {{x}}

id : B → B
id ⟨ n ⟩ = mkB     -- works!
```

What you did is make the *projection* into an instance, which I'm not sure is something you ever actually want to do.

**Comment by MatthewDaggitt** [comment]
Ah okay, thank you very much. That clears it up. That is kind of confusing but unsure what can be done to warn the user... so closing.

**Comment by andreasabel** [comment]
@jespercockx wrote:
> What you did is make the projection into an instance, which I'm not sure is something you ever actually want to do.

If there is no reasonable use case for it, we should outlaw it, to avoid confusions as the OP.

What happens if you `open` a record with an `instance` field?  Do you get this instance into scope?

**Comment by jespercockx** [comment]
What I meant is not that I cannot think of a use case where it does something, just that I cannot think of a use case where it is actually *useful*. For example, this is perfectly valid:
```agda
open import Agda.Builtin.Nat

record B : Set where
  constructor mkB
  field
    instance n : Nat

instance
  myB : B
  myB = record { n = 42 }

open B myB

test = n   -- normalizes to 42
```
I don't think it makes sense that we would forbid this code. In general, I don't think we should outlaw things just because we currently lack the imagination to think of a use case.

**Comment by MatthewDaggitt** [comment]
Agda already uses it in the pretty much the most important definition of them all :laughing: 

https://github.com/agda/agda/blob/edd8334381f6c7a59f7a5f23eb668e62e1464aee/src/data/lib/prim/Agda/Builtin/Equality.agda#L6-L7

**Comment by jespercockx** [comment]
That's an instance constructor, not an instance projection though.

**Comment by MatthewDaggitt** [comment]
Doh of course. My Agda skills are obviously not the strongest this afternoon, myself and @wenkokke thought we'd proved false for about half an hour before realising Agda was behaving exactly as intended :man_facepalming:
