### ISSUE TITLE
v2.6.2.0.20211129 appears in tags but does not actually exist

### ISSUE THREAD

**Issue by fgaz** [agda/agda#5689]
To reproduce:

```bash
git clone https://github.com/agda/agda
git checkout v2.6.2.0.20211129
```

Could it be that it only exists in a fork (see https://github.com/agda/agda/commit/038dc2639017fe9fac037d6782edaff8e702ca54)?

**Comment by gallais** [comment]
You need to explicitly fetch tags:

```shell
git fetch --tags
git checkout tags/v2.6.2.0.20211129
```

**Comment by fgaz** [comment]
Oh.. I didn't know about this

> By default, any tag that points into the histories being fetched is also fetched; the effect is to fetch tags that point at branches that you are interested in. This default behavior can be changed by using the --tags or --no-tags options or by configuring remote.<name>.tagOpt. By using a refspec that fetches tags explicitly, you can fetch tags that do not point into branches you are interested in as well.

pretty counterintuitive on git's part :-/

Thanks for the pointer, closing

**Comment by andreasabel** [comment]
N.B.: The tag `v2.6.2.0.20211129` sits on a leaf that is not a branch anymore (the branch `release-2.6.2.1-candidate` has moved away from this tag).

**Comment by fgaz** [comment]
So in general -candidate branches get force pushed and can't be depended upon?

**Comment by andreasabel** [comment]
Atm, I am working with these branches for a release:
- `maint-2.6.2`: picks from master
- `release-2.6.2.1`: additional commits (e.g. to `CHANGELOG`), rebased onto `maint-2.6.2`
- `release-2.6.2.1-candidate`: destructive commits (to `Agda.cabal` and CI), rebased onto `release-2.6.2.1`

Fate of these branches (my current plan):
* The `-candidate` branch will end in the release tag `v2.6.2.1` and then be deleted.
* The `release-2.6.2.1` branch ~~will be extended by commits turning the `CHANGELOG` into `doc/release-notes/2.6.2.1.md` and then be merged into master~~.
* The `maint-2.6.2` will be preserved and could be used to prepare a 2.6.2.2 release.

**Comment by andreasabel** [comment]
@fgaz: Do you want some more time to evaluate 2.6.2.1-rc1?  Otherwise, I am ready to release 2.6.2.1.

**Comment by fgaz** [comment]
@andreasabel It works fine!
