### ISSUE TITLE
Inaccuracies or misunderstandings in the Cubical chapter in Docs

### ISSUE THREAD

**Issue by ShreckYe** [agda/agda#5698]
In the Cubical chapter in Language Reference in Docs ([site here](https://agda.readthedocs.io/en/latest/language/cubical.html) and [repo file here](https://github.com/agda/agda/blob/master/doc/user-manual/language/cubical.lagda.rst)) it says:

> Because of the way functions compute these satisfy some new definitional equalities compared to the standard Agda definitions:

From the context "standard Agda definitions" should refer to what's in `PropositionalEquality` here. If so, the three laws here are indeed provable with `PropositionalEquality` by matching `p`s with `refl`s, and then they shouldn't be referred to as "new".

```agda
open import Relation.Binary.PropositionalEquality

symInv : ∀ {ℓ} {A : Set ℓ} {x y : A} (p : x ≡ y) → sym (sym p) ≡ p
symInv refl = refl

congId : ∀ {ℓ} {A : Set ℓ} {x y : A} (p : x ≡ y) → cong (λ a → a) p ≡ p
congId refl = refl

congComp : ∀ {ℓ} {A B C : Set ℓ} (f : A → B) (g : B → C) {x y : A} (p : x ≡ y) →
             cong (λ a → g (f a)) p ≡ cong g (cong f p)
congComp f g refl = refl

```

**Comment by plt-amy** [comment]
These are propositional equalities: you have to prove them by pattern matching on `refl`. The equalities being referred to in that sentence **definitional**, meaning you don't need to do anything to prove them: they're just true by the way computation works.

**Comment by ShreckYe** [comment]
@plt-amy Thank you very much.

Sorry to have bothered then.
