### ISSUE TITLE
Explicit polarity annotation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#570]
This code does not work since polarity of `Nat` (monotone in `i`) is only inferred when the constructors are given. But it is already needed for checking sub.
```agda
  data Nat : {i : Size} -> Set

  sub : {i : Size} -> Nat {i} → Nat {↑ i}
  sub x = x

  data Nat where
    zero : {i : Size}            -> Nat {↑ i}
    suc  : {i : Size} -> Nat {i} -> Nat {↑ i}
```

Original issue reported on code.google.com by `andreas....@gmail.com` on 19 Feb 2012 at 10:21

Attachments:
- [NewMutualSized.agda](https://storage.googleapis.com/google-code-attachments/agda/issue-570/comment-0/NewMutualSized.agda)

**Comment by andreasabel** [comment]
For another example, see #2411.

**Comment by UlfNorell** [comment]
Syntax discussion in #2513.
