### ISSUE TITLE
Cabal workflow fails on Windows due to icu4c

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5710]
Something upstream must have changed that breaks our workflow:
https://github.com/agda/agda/runs/4616916745?check_suite_focus=true

**Comment by L-TChen** [comment]
It looks like `${APPDATA}/cabal/config` has been moved somewhere else or it is not set by default. Is there any way to fetch the location of the configuration?

**Comment by andreasabel** [comment]
We could use the command `cabal user-config update`, e.g.
```
$ cabal user-config update \
  --augment="extra-include-dirs: /usr/local/opt/icu4c/include" \
  --augment="extra-lib-dirs: /usr/local/opt/icu4c/lib"
```
