### ISSUE TITLE
Reflection: Use `Telescope` for `getContext`, `inContext`, and `extendContext`

### ISSUE THREAD

**Issue by L-TChen** [agda/agda#5715]
Currently, `getContext` and `inContext` only returns and takes a list of `Arg Type` without a name, and internally all variables are named `x`:

https://github.com/agda/agda/blob/9428b1db46b28a4a01706a9347091b09b7136388/src/full/Agda/TypeChecking/Unquote.hs#L780-L783

In order to print terms nicely, e.g. using `debugPrint` or `typeError` with `termErr`, I propose that they all should use `Telescope` (i.e. `List (Σ String λ _ → Arg Type)`) instead. For the same reason, `extendContext` should take an extra argument of type `String` in order to give a name to the variable introduced to the context. 

It would be a breaking change but this change allows programmers to easily print not only understandable but also more precise type information during macro expansion.

**Comment by andreasabel** [comment]
Note: this breaks `master` of `cubical`: 
- https://github.com/agda/cubical/issues/743

**Comment by asr** [comment]
I removed a trailing whitespace in the title.
