### ISSUE TITLE
Termination checker rejects recursive function on two well-founded trees

### ISSUE THREAD

**Issue by foones** [agda/agda#5724]
I'm trying to write a recursive function that takes two well-founded trees as arguments. In the recursive call, sometimes the first argument becomes structurally smaller, and sometimes the second one does. The non-decreasing argument remains untouched.

This function gets rejected by the termination checker, and I cannot understand why.

I have tried to reduce the example as much as possible. Concretely, the following definition of `combine` is **rejected** by the termination checker (but I'd hope Agda to **accept** it):

```agda
-- Terms
postulate T : Set

-- Rewriting relation on terms
postulate _▷_ : T → T → Set

-- Well founded trees rooted on a term t,
-- whose children are given by all steps t ▷ s.
-- (𝕎 t is inhabited iff t is strongly normalizing).
data 𝕎 : T → Set where
  W : {t : T} → ({s : T} → t ▷ s → 𝕎 s) → 𝕎 t

-- Pairs of terms
data T² : Set where
  _,_ : T → T → T²
  
-- Rewriting relation on pairs of terms
data _▷²_ : T² → T² → Set where
  L : {t t' s : T}
    → t ▷ t'
    ----------------------
    → (t , s) ▷² (t' , s)
  R : {t s s' : T}
    → s ▷ s'
    ----------------------
    → (t , s) ▷² (t , s')

-- Well founded trees rooted on a pair (t₁ , t₂),
-- whose children are given by all steps (t₁ , t₂) ▷² (s₁ , s₂).
data 𝕎² : T² → Set where
  W² : {t : T²} → ({s : T²} → t ▷² s → 𝕎² s) → 𝕎² t

-- This construction proves that, if t and s are strongly normalizing,
-- then (t, s) is strongly normalizing.
combine : {t s : T} → 𝕎 t → 𝕎 s → 𝕎² (t , s)
combine (W a) (W b) = W² λ {
    (L i) → combine (a i) (W b)
  ; (R i) → combine (W a) (b i)
  }
```
A point that may be worth of notice is that, if any of the two constructors of the type `_▷²_` is removed (as well the corresponding pattern-match branch in the definition of `combine`), the termination checker does accept the definition.

I have also tried to isolate this example further by removing the indices of the type families. However, the definition of the function `combine` below becomes accepted by the termination checker (rightly so):

```agda
data _⊎_ (A B : Set) : Set where
  L : A → A ⊎ B
  R : B → A ⊎ B

-- Indices
postulate 𝕀 : Set

-- Well-founded trees, where children are indexed by elements of 𝕀.
data 𝕎 : Set where
  W : (𝕀 → 𝕎) → 𝕎

-- Well-founded trees, where children are indexed by (𝕀 + 𝕀).
data 𝕎² : Set where
  W² : ((𝕀 ⊎ 𝕀) → 𝕎²) → 𝕎²

combine : 𝕎 → 𝕎 → 𝕎²
combine (W a) (W b) = W² λ {
    (L i) → combine (a i) (W b)
  ; (R i) → combine (W a) (b i)
  }
```
I'm using Agda version is 2.6.1-0ebc740. I haven't been able to find any related open issue, nor any related recent change in the release notes. (Apologies if I missed it).

**Comment by gallais** [comment]
Note that with a bit of manual inlining it's accepted:

```agda
combine : {t s : T} → 𝕎 t → 𝕎 s → 𝕎² (t , s)
aux : {t s : T} →
      𝕎 t → ({t′ : T} → t ▷ t′ → 𝕎 t′) →
      𝕎 s → ({s′ : T} → s ▷ s′ → 𝕎 s′) →
      {ts′ : T²} → (t , s) ▷² ts′ → 𝕎² ts′
combine wa@(W a) wb@(W b) = W² (aux wa a wb b)

aux wa a wb b (L i) = combine (a i) wb
aux wa a wb b (R i) = combine wa (b i)
```

I think it's the classic issue of deconstructing / reconstructing `W a` and `W b` that
confuses the termination checker.

**Comment by andreasabel** [comment]
@gallais won the race.  Here is my take, abstracting the recursive calls from the pattern-lambda:
```agda
combine : {t s : T} → 𝕎 t → 𝕎 s → 𝕎² (t , s)
combine {t = t} {s = s} v@(W a) w@(W b) = 
  W² (aux (λ i → combine (a i) w)
          (λ i → combine v (b i)))
  where
  aux
    : (∀{t'} (i : t ▷ t') → 𝕎² (t' , s))
    → (∀{s'} (i : s ▷ s') → 𝕎² (t , s'))
    → ∀{s₂} → (t , s) ▷² s₂ → 𝕎² s₂
  aux l r (L i) = l i
  aux l r (R i) = r i
```

**Comment by foones** [comment]
Thanks to both for your helpful alternatives!
