### ISSUE TITLE
Reducing universe levels before checking is not sufficient

### ISSUE THREAD

**Issue by L-TChen** [agda/agda#5727]
To check if two `Level` terms are equal, Agda first reduces them to check if they are syntactically equal (L1450) below 

https://github.com/agda/agda/blob/a0b3eea0c19c47ffbe2be525316311f5795d760d/src/full/Agda/TypeChecking/Conversion.hs#L1450-L1454

which however seems insufficient, if they do have the same normal form but different head normal form. 

### Example
Unfortnutely, I don't have a minimal working example, though. Here is the actual code of our working project exhibiting this insufficiency:

https://github.com/Zekt/Type-Embellishment/blob/3f75a36646afdbea2db1a0efd6d899fd6b401ab6/src/Generics/Safe/RecursionScheme.agda#L49

On line 49, the hole can be refined by `args` but consequently Agda complains that
```agda
Failed to solve the following constraints:
  foldr lzero _⊔_ (map (λ _ → ℓ) (PDataD.struct (DataD.applyL D ℓs)))
  ⊔
  foldr lzero _⊔_
  (map (λ x → foldr lzero _⊔_ (map ρ-level x))
   (PDataD.struct (DataD.applyL D ℓs)))
  ⊔
  foldr lzero _⊔_
  (map (λ x → foldr lzero _⊔_ (map σ-level x))
   (PDataD.struct (DataD.applyL D ℓs)))
    = foldr lzero _⊔_ (map max-π (PDataD.struct (DataD.applyL D ℓs))) ⊔
      foldr lzero _⊔_ (map max-σ (PDataD.struct (DataD.applyL D ℓs)))
      ⊔
      foldr lzero _⊔_ (map (λ _ → ℓ) (PDataD.struct (DataD.applyL D ℓs)))
    (blocked on _ℓ_165)
```
However, each subterm on the RHS, i.e.

1. `foldr lzero _⊔_ (map max-π (PDataD.struct (DataD.applyL D ℓs)))`
2. `foldr lzero _⊔_ (map max-σ (PDataD.struct (DataD.applyL D ℓs)))`
3. `foldr lzero _⊔_ (map (λ _ → ℓ) (PDataD.struct (DataD.applyL D ℓs)))`

normalises to

1. `foldr lzero _⊔_ (map (λ x → foldr lzero _⊔_ (map ρ-level x)) (PDataD.struct (DataD.applyL D ℓs)))` (equal to the 2nd subterm of the LHS)
2. `foldr lzero _⊔_ (map (λ x → foldr lzero _⊔_ (map σ-level x)) (PDataD.struct (DataD.applyL D ℓs)))` (equal to the 3rd subterm)
3.  the same term which is equal to the first subterm of the LHS

respectively (checked by `C-c C-n` inside the hole), so the LHS and the RHS are judgementally equal.

### Possible solution
Replacing `reduce` by `normalise` below does allow Agda to see they are the same term. 

https://github.com/agda/agda/blob/a0b3eea0c19c47ffbe2be525316311f5795d760d/src/full/Agda/TypeChecking/Conversion.hs#L1450

Indeed, these two terms are reported syntactically equal by turning on the verbose option ` -v tc.conv.level:60`
```agda
equalLevel
  (foldr lzero _⊔_
   (map (λ _ → ℓ) (PDataD.struct (DataD.applyL D ℓs)))
   ⊔
   foldr lzero _⊔_
   (map (λ x → foldr lzero _⊔_ (map ρ-level x))
    (PDataD.struct (DataD.applyL D ℓs)))
   ⊔
   foldr lzero _⊔_
   (map (λ x → foldr lzero _⊔_ (map σ-level x))
    (PDataD.struct (DataD.applyL D ℓs)))) ==
  (foldr lzero _⊔_ (map max-π (PDataD.struct (DataD.applyL D ℓs))) ⊔
   foldr lzero _⊔_ (map max-σ (PDataD.struct (DataD.applyL D ℓs)))
   ⊔
   foldr lzero _⊔_
   (map (λ _ → ℓ) (PDataD.struct (DataD.applyL D ℓs))))
checkSyntacticEquality returns True
```
Shall we use normalisation instead of reduction before syntactic checking?

**Comment by jespercockx** [comment]
This used to be normalization before I changed it to normal reduction in April 2020: https://github.com/agda/agda/commit/0348659e9f3e9f741dda2c751eb32ea29c2cb9c7 So I caused this regression.

The syntactic equality check is supposed to be "just" an optimization so the fundamental problem here is not that the levels are not enough normalized but that the logic for solving universe level constraints is unable to handle neutral levels involving defined functions such as `foldr`. Hence, while we could turn on the normalization again and have this particular case be solved, it does not feel very principled as there will still be other cases where the two sides are definitionally equal yet the equation is not solved. As a simple example, consider what would happen if the arguments of `⊔` were swapped on one side of the equation but not the other.

To really properly solve it, we would have to decompose equations like this into inequalities that each argument to `⊔` on the LHS must be below at least one argument to `⊔` on the RHS and vice versa. However this involves a lot of "or" constraints, i.e. backtracking, so it will probably blow up the performance. So I'm not sure what's the right solution here.

**Comment by L-TChen** [comment]
> As a simple example, consider what would happen if the arguments of ⊔ were swapped on one side of the equation but not the other.

I don’t understand this part. In the above example, arguments of ⊔ are not in the same order but it is still okay after normalisation. Did I miss something?

**Comment by jespercockx** [comment]
Oh, you're right, I didn't look closely enough at the example. It is the case that normalization (and in fact also reduction) of a level expression will sort the arguments to `⊔` in a predictable way, so the order does not actually matter. But that makes me wonder why this case in the level comparison does not kick in for your example:

https://github.com/agda/agda/blob/a0b3eea0c19c47ffbe2be525316311f5795d760d/src/full/Agda/TypeChecking/Conversion.hs#L1542-L1550

Do you perhaps have any unsolved metas in your example? If there are no metas, I would expect the above case to kick in and just solve it. I see there's `(blocked on _ℓ_165)` but the meta does not appear anywhere in the constraint, so it is a bit confusing. Maybe `--show-implicit` reveals it?

**Comment by L-TChen** [comment]
Oh, the metavariable `_ℓ_165` can be given explicitly. By checking the output of `tc.conv.level:60`, I can see that the above case does kick in, so there is no metavariable involved anymore and no postponing. However, I found that `as` and `bs` are compared in the order as they are given as reported by
https://github.com/agda/agda/blob/a0b3eea0c19c47ffbe2be525316311f5795d760d/src/full/Agda/TypeChecking/Conversion.hs#L1474-L1483

In particular, Agda tries to compare
```agda
foldr lzero _⊔_ (map (λ _ → ℓ) (PDataD.struct (DataD.applyL D ℓs)))
```
with
```
foldr lzero _⊔_ (map max-π (PDataD.struct (DataD.applyL D ℓs)))
```
instead of the third argument `foldr lzero _⊔_ (map (λ _ → ℓ) (PDataD.struct (DataD.applyL D ℓs)))` on the right-hand side. Then, certainly, the two `Level` terms are different. 

Shouldn't Agda try every possible combination on closed/neutral terms? I doubt sorting is enough.

**Comment by jespercockx** [comment]
You're correct again: sorting is not enough unless we first normalize the terms (in which case syntactic equality would kick in anyways) or we have a way to sort that is stable under reduction (which seems like it would involve normalization anyway). Trying every possible order is possible in theory but I doubt it will be more efficient than just normalizing (except for some degenerate cases). So perhaps the best thing to do is to restore the normalization after all.

**Comment by L-TChen** [comment]
By the way, there is also a similar problem with `leqLevel`. I guess this can be fixed by restoring normalization and using `equalLevel` for `leqLevel` by translating an inequation to an equation, so at least they would have the same logic under the hood. 

Does a syntactic equality check after normalisation suffice?

**Comment by andreasabel** [comment]
Relevant commits seem to be:
- https://github.com/agda/agda/commit/0348659e9f3e9f741dda2c751eb32ea29c2cb9c7
- https://github.com/agda/agda/commit/ba469e99d14e3b77e073fc04755739293d830f2d

**Comment by andreasabel** [comment]
`git revert` fails for these commits, and fixing merge conflicts is confusing and error prone, so maybe the best path is to fix this issue manually (restore normalization).
@L-TChen : can you fix this issue (you are assigned) and supply a regression test?

**Comment by L-TChen** [comment]
Yes, I just need some time to work it out.

**Comment by andreasabel** [comment]
> Yes, I just need some time to work it out.

Great, @L-TChen !  If you think it is too rushed for 2.6.2.2, welcome to set the milestone back to 2.6.3, then I unschedule it from 2.6.2.2.
