### ISSUE TITLE
Internal error when pattern matching on `...` in with statement without providing a pattern match

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda#5728]
```agda
test : Set
test with Set
... 
```
gives:
```
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/Rules/Def.hs:472:8 in Agda-2.6.2-0cbf819c7e87f75a40527d004b9f64ce3b0a75da0060e90d90777006adbc4e2c:Agda.TypeChecking.Rules.Def
```
Works with any `with` target, not just `Set`. 

Version: Agda 2.6.2

**Comment by andreasabel** [comment]
bisecting...
Previous errors:
- v2.6.1: `Missing with-clauses for function test`
- ccffe29fa: 
  ```
  The right-hand side can only be omitted if there is an absurd
  pattern, () or {}, in the left-hand side.
  ```

**Comment by andreasabel** [comment]
bisect says: ecb93230ad9327991e542731756cbe1405c85d5f is the first bad commit (ping @gallais)
Date:   Thu Mar 25 10:01:49 2021 +0000
[ re #4041 ] internalising the inspect idiom (#4084)

**Comment by jamestmartin** [comment]
Alternative example:
```agda
open import Agda.Builtin.Unit

foo : ⊤
foo with ⦃ tt ⦄
... = tt
```

Error log with latest master:
```
Checking bug2 (/data/code/tmp/bug2.agda).
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/Rules/Def.hs:485:8 in Agda-2.6.3-4066a36fa0edeadb7d1839a9a6fcdd1f93d2381dcf8a53c1fee8c4a75518aca8:Agda.TypeChecking.Rules.Def
```

Error log with 2.6.2.1:
```
Checking bug2 (/data/code/tmp/bug2.agda).
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/Rules/Def.hs:479:8 in Agda-2.6.2.1-58e3dc098a20086fb0ad394645db54abbe4d4b9dc2f98bd7aaed77514158538c:Agda.TypeChecking.Rules.Def
```

**Comment by andreasabel** [comment]
Can you have a look, Guillaume @gallais?

**Comment by andreasabel** [comment]
@gallais: Putting this on 2.6.3 since this can be worked around, but if there is an easy fix, we could aim for 2.6.2.2.

**Comment by gallais** [comment]
I tried to have a look but my naïve fix in `Agda.TypeChecking.Rules.Def` was too strict and
started rejecting a lot of well-formed programs. I guess I should try to catch these a lot earlier
in the pipeline.

**Comment by andreasabel** [comment]
Yes, at least the OP could already be caught in the parser.  I seems like an ellipsis `...` _must_ be followed by a bar `|`, or am I wrong about this?

**Comment by lawcho** [comment]
Another test case -- this time `with` is *after* the `...`

```.agda
open import Agda.Builtin.Unit


open import Agda.Builtin.Unit

ok : ⊤          -- Passes as expected
ok
    with tt
... | x
    with tt
... | y = tt

bad : ⊤         -- Internal error
bad
    with tt
... | x
... with tt
... | y = tt
```
(the first `with` is there to tell the parser that `bad` isn't a stand-alone absurd clause)

Error:
```
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/Rules/Def.hs:479:8 in Agda-2.6.2.1-3iYJFSRK38DIOELxjGwiJC:Agda.TypeChecking.Rules.Def
```

**Comment by andreasabel** [comment]
Note that Agda master accepts ellipsis in other situations, like
```agda
foo : Set₁
foo = Set
... = Set
```
This replaces `...` by `foo` and gives the expected error:
```
<file>:3,1-10
Unreachable clause
when checking the definition of foo
```
Maybe we can just accept `...` as repeating the parent clause, `with` or not, and give a proper error for the OP, like _lhs cannot be omitted_.
