### ISSUE TITLE
Preserve ellipsis (...) when case splitting in interaction

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#573]
``` agda
f (m e (s (s y)) with t
... | x = {! x !}
```

case splitting on x will replace ellipsis (...) by `f (m e (s (s y)))`.

Ellipsis was probably intended by user, should be preserved.

There could be a separate command for `expandEllipsis`, if needed.

Original issue reported on code.google.com by `andreas....@gmail.com` on 21 Feb 2012 at 5:26

**Comment by UlfNorell** [comment]
Some work has been started in #2589, so closing this one.
