### ISSUE TITLE
Optimise readTextFile

### ISSUE THREAD

**Issue by nad** [agda/agda#5740]
Consider the implementation of `readTextFile`:

https://github.com/agda/agda/blob/9399b3a05e56b9957265949d2eeaba64e004e799/src/full/Agda/Utils/IO/UTF8.hs#L32-L42

The documentation for [`Data.Text.Lazy.IO.readTextFile`](https://hackage.haskell.org/package/text-2.0/docs/Data-Text-Lazy-IO.html#v:readFile) suggests that it is "much faster and safer" to read a lazy byte string and then use `Data.Text.Lazy.Encoding.decodeUtf8`, instead of doing what we do above, if we ignore the use of `hSetNewlineMode` (which could be absorbed into `convertLineEndings`).

I wonder if the same applies to `writeFile` and `writeTextToFile`:

https://github.com/agda/agda/blob/9399b3a05e56b9957265949d2eeaba64e004e799/src/full/Agda/Utils/IO/UTF8.hs#L44-L58

**Comment by nad** [comment]
I tried to optimise `readTextFile`. I don't know if it made much of a difference, but I took the opportunity to change the error message that you get if Agda tries to read an Agda file that cannot be decoded. Before (with some changes related to #4506 in place):
```$ agda Bug.agda
[…]/Bug.agda: hGetContents: invalid argument (invalid byte
sequence)

This error may be due to the use of a locale or code page that does not
support some character used in the program being type-checked.

If it is, then one option is to use the option --transliterate, in which
case unsupported characters are (hopefully) replaced with something else,
perhaps question marks. However, that could make the output harder to
read.

If you want to fix the problem "properly", then you could try one of the
following suggestions:

* If you are using Windows, try switching to a different code page (for
  instance by running the command 'CHCP 65001').

* If you are using a Unix-like system, try using a different locale. The
  installed locales are perhaps printed by the command 'locale -a'. If
  you have a UTF-8 locale installed (for instance sv_SE.utf8), then you
  can perhaps make Agda use this locale by running something like
  'LC_ALL=sv_SE.utf-8 agda <...>'.
```
After:
```
$ agda Bug.agda
[…]/Bug.agda:1,1-1
Cannot read file […]/Bug.agda
Error: user error (Failed to read the file […]/Bug.agda.
Please ensure that this file uses the UTF-8 character encoding.)
```

The compiler backends can create rather large text files, so perhaps it would make sense to optimise `writeTextToFile` and/or `writeFile`, but I don't plan to do so now.

**Comment by andreasabel** [comment]
> Cannot read file […]/Bug.agda
> Error: user error (Failed to read the file […]/Bug.agda.
> Please ensure that this file uses the UTF-8 character encoding.)

Can we have this rendered more nicely?  I do not like it when `user error` leaks...

**Comment by nad** [comment]
I was also not happy with this, but it is not obvious to me how to fix it:

* We could use `error` instead of `ioError . userError`, but then the error is not caught by Agda, we get a different exit code (1 instead of 42), and a stack trace is included with the error message.

* We could make `readTextFile` return something like `Either String Text`. However, that would force all callers to handle this error explicitly.

* I think it would be nicer to change the type to something like `MonadError TCErr m => FilePath -> m Text`, so that we can use the usual error reporting mechanism, but I guess the idea is that we should not import `Agda.TypeChecking.Monad.Base` from modules under `Agda/Utils`.

One option is to rename the module, but I think the current name is fine. Another option is to use the approach with `Either` and add a wrapper module somewhere else, but that would make the code base more complicated.

Given that this error message is presumably not very common I am fine with keeping it.

**Comment by andreasabel** [comment]
>     * We could make `readTextFile` return something like `Either String Text`. However, that would force all callers to handle this error explicitly.

Good idea.  A standard error handling as suggested in the next point could be added by wrapping this function in a handler somewhere, e.g. in our sin-bin Agda.TypeChecking.Monad.Base.

>     * I think it would be nicer to change the type to something like `MonadError TCErr m => FilePath -> m Text`, so that we can use the usual error reporting mechanism, but I guess the idea is that we should not import `Agda.TypeChecking.Monad.Base` from modules under `Agda/Utils`.

**Comment by nad** [comment]
What you suggest would complicate the source code, for (in my opinion) little benefit.

**Comment by nad** [comment]
I pushed my change. It is still possible to change the code.

**Comment by jespercockx** [comment]
The main task here seems to be done, so I'm closing this. Please open a new issue if there is still other things you'd like to change.

**Comment by andreasabel** [comment]
The discussion wasn't resolved, why close the issue?

**Comment by nad** [comment]
Now `readTextFile` throws a custom exception, and all exceptions (except for those of type `ExitCode`) are caught in `runTCMPrettyErrors`.
