### ISSUE TITLE
Do not use readFile

### ISSUE THREAD

**Issue by nad** [agda/agda#5741]
I noticed that the code uses `readFile` to read certain files that are (or should be) required to use the UTF-8 text encoding:

https://github.com/agda/agda/blob/9399b3a05e56b9957265949d2eeaba64e004e799/src/full/Agda/Interaction/Library.hs#L255-L260

https://github.com/agda/agda/blob/9399b3a05e56b9957265949d2eeaba64e004e799/src/full/Agda/Interaction/Library.hs#L295-L304

https://github.com/agda/agda/blob/9399b3a05e56b9957265949d2eeaba64e004e799/src/full/Agda/Interaction/Library.hs#L368-L373

https://github.com/agda/agda/blob/9399b3a05e56b9957265949d2eeaba64e004e799/src/full/Agda/Interaction/Library/Parse.hs#L110-L112

These calls to `readFile` should all be fixed.

**Comment by andreasabel** [comment]
> These calls to `readFile` should all be fixed.

How? What do you suggest?
Use `readTextFile` from #5742?

**Comment by nad** [comment]
I guess you meant some other issue, but I think it is appropriate to use `Agda.Utils.IO.UTF8.readTextFile` to read these files.

**Comment by andreasabel** [comment]
> I guess you meant some other issue.

I think I meant #5740.
