### ISSUE TITLE
Use GHC_CHARENC=UTF-8 when calling GHC

### ISSUE THREAD

**Issue by nad** [agda/agda#5742]
We use `hGetContents` in `callCompiler'`:

https://github.com/agda/agda/blob/9399b3a05e56b9957265949d2eeaba64e004e799/src/full/Agda/Compiler/CallCompiler.hs#L55-L76

The handles `out` and `err` [use](https://hackage.haskell.org/package/process-1.6.13.2/docs/System-Process.html#t:StdStream) the default (locale) encoding. That is perhaps appropriate, if we know nothing about the encoding used by the process that we call. We only use `callCompiler'` to call GHC. Does GHC use the locale encoding when writing to stdout or stderr?

**Comment by nad** [comment]
If the environment variable `GHC_CHARENC` is set to `UTF-8`, then GHC appears to use UTF-8 for stdout and stderr:

https://github.com/ghc/ghc/blob/0dc723957d0fdb5909f145405b775efea0fe2f6e/ghc/Main.hs#L113-L118

https://github.com/ghc/ghc/blob/0dc723957d0fdb5909f145405b775efea0fe2f6e/libraries/ghc-boot/GHC/HandleEncoding.hs#L9-L17

The variable `GHC_CHARENC` does not seem to be mentioned in the GHC documentation, but I still think we should make use of it. It [seems](https://github.com/ghc/ghc/commit/1b56c40578374a15b4a2593895710c68b0e2a717) to be available from at least GHC 8.

**Comment by nad** [comment]
Perhaps `callCompiler` or `callCompiler'` are used by other packages. I suggest that we add an optional encoding argument to these procedures.

**Comment by andreasabel** [comment]
> [](https://github.com/ghc/ghc/blob/0dc723957d0fdb5909f145405b775efea0fe2f6e/libraries/ghc-boot/GHC/HandleEncoding.hs#L9-L17)
> 
> The variable `GHC_CHARENC` does not seem to be mentioned in the GHC documentation,

I reported this upstream: https://gitlab.haskell.org/ghc/ghc/-/issues/20963
