### ISSUE TITLE
Reflection: name confusion under module parameters

### ISSUE THREAD

**Issue by omelkonian** [agda/agda#5745]
Here are two simple macros defined in a parametrized module:
```agda
-- File1.agda
module File1 (A : Set) where

open import Function
open import Data.Unit; open import Data.List
open import Reflection; open import Reflection.Term

postulate
  P : Set → Set
  PA : P A

♯0 : Arg Term
♯0 = vArg (var 0 [])

macro
  _∙A : Name → Term → TC ⊤
  n ∙A = flip unify $ def n [ ♯0 ]

  P∙A : Term → TC ⊤
  P∙A = flip unify $ def (quote P) [ ♯0 ]

_ = P ∙A ∋ PA
_ = P∙A  ∋ PA
```
`_∙A` applies `A` to a given name and `P∙A` just returns the term `P A` using `quote P`.
Both macros work when trying to generate the type `P A` (to be inhabited by the postulated term `PA`).

In another file now, with the same parameters, only the name-generic macro works!
```agda
-- File2.agda
module File2 (A : Set) where

open import Function
open import File1 A

_ = P ∙A ∋ PA
_ = P∙A  ∋ PA -- ERROR: (Set → Set) !=< Set 
```
It turns out that the name `quote P` inside the macro is interpreted as requiring the module parameter `P : Set -> Set -> Set`, although we brought it in scope applied to A in File2.

Just to verify, the following macro that expects the above interpretation works:
```agda
-- File1.agda
macro
  P∙A∙A : Term → TC ⊤
  P∙A∙A = flip unify $ def (quote P) (♯0 ∷ ♯0 ∷ [])
  
-- File2.agda
_ = P∙A∙A  ∋ PA
```

**Comment by jespercockx** [comment]
Looks to me like an instance of https://github.com/agda/agda/issues/3819, feel free to reopen if you disagree.
