### ISSUE TITLE
Reflection: unexpected inferred type of goal

### ISSUE THREAD

**Issue by omelkonian** [agda/agda#5750]
The following macro just infers the type of the hole and prints it:
```agda
open import Data.Unit; open import Data.List
open import Reflection

macro
  printGoalType : Term → TC ⊤
  printGoalType hole = do
    ty ← inferType hole
    typeError [ termErr ty ]

_ : ⊤ → ⊤
_ = printGoalType
```
I would expect `ty` to be `⊤ → ⊤`, but the argument appears to be a meta-variable instead:
```
(z : _17) → ⊤
when checking that the expression unquote printGoalType has type
⊤ → ⊤
```

----
*agda: 2.6.2.1*
*stdlib: 1.7*

**Comment by jespercockx** [comment]
This would probably be fixed by https://github.com/agda/agda/issues/4198
