### ISSUE TITLE
Internal parser error using syntax rules

### ISSUE THREAD

**Issue by foones** [agda/agda#5763]
The following snippet produces an internal (`__IMPOSSIBLE__`) parser error at `src/full/Agda/Syntax/Concrete/Operators/Parser.hs:114:77` in Agda-2.6.2.1. I have tried it in a slightly older version (Agda-2.6.1) with similar results:
```agda
postulate X : Set
postulate Π : (X → X) → X
syntax Π  (λ A → B) = Π A , B
syntax Π' (λ A → B) = Π' A , B 
Π' : (X → X) → X
(Π' α , P α) = (Π α , P α)
```

**Comment by nad** [comment]
One cannot use lambda abstractions as patterns (excluding dot patterns), but the error message should be better.

**Comment by andreasabel** [comment]
The error is raised here (second `__IMPOSSIBLE__`): https://github.com/agda/agda/blob/798be60d51a56a8c74cfd309c1498b070240e686/src/full/Agda/Syntax/Concrete/Operators/Parser.hs#L109-L118

This never worked properly, there is an internal error all the way back to 2.4.2.6 (and probably further).

**Comment by andreasabel** [comment]
(Removed from 2.6.2.2 as it does not pick cleanly.)
