### ISSUE TITLE
Dummy terms are always treated as equal

### ISSUE THREAD

**Issue by nad** [agda/agda#5764]
Why are `Dummy` terms always treated as equal by the syntactic equality check, even if the `Elims` are not equal?

https://github.com/agda/agda/blob/0b71569945ba8cb0fefb7e9e450ed04b855b286a/src/full/Agda/TypeChecking/SyntacticEquality.hs#L100

Was this something that was missed when the `Elims` argument was added to `Dummy` (in which case it should be fixed), or is it fine (in which case I think some documentation would be nice)?

Note that `DummyS` is treated in the same way.

**Comment by UlfNorell** [comment]
Dummy terms are only supposed to be used in places where they will not be looked at (see for instance our recent discussion on generalise https://github.com/agda/agda/issues/5731#issuecomment-1022953478), so treating them as irrelevant for syntactic equality makes sense.

**Comment by nad** [comment]
In that case, what is the point of the `Elims`?

https://github.com/agda/agda/blob/0b71569945ba8cb0fefb7e9e450ed04b855b286a/src/full/Agda/Syntax/Internal.hs#L218-L224

Could they be removed?

**Comment by andreasabel** [comment]
They do help in debugging...  Are they harmful?  If they confuse, the documentation should be extended.

**Comment by nad** [comment]
Thanks. With the current implementation of `--save-metas` we sometimes store dummy terms in interfaces. The dead-code elimination looks for reachable names and meta-variables in the second argument of `Dummy`:

https://github.com/agda/agda/blob/ba99b8e1833946e43e7722e2e7d2c3a1dd40fc74/src/full/Agda/Syntax/Internal/Names.hs#L218

Perhaps one could replace the right-hand side with `mempty`.
