### ISSUE TITLE
Erasure check failure when pattern matching on refl in erased definition

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#5765]
The following file is currently not accepted:
```agda
open import Agda.Builtin.Equality

postulate @0 A : Set

@0 f : (X : Set) → A ≡ X → Set
f X refl = ?  -- FAILS
```
Error message:
```
I'm not sure if there should be a case for the constructor refl,
because I get stuck when trying to solve the following unification
problems (inferred index ≟ expected index):
  A ≟ X
Possible reason why unification failed:
  Cannot solve variable X of type Set with solution A because the
  solution cannot be used at relevant, unrestricted modality
when checking that the pattern refl has type A ≡ X
```
However, since the definition of `f` itself is marked as erased, I think this function should be completely fine and hence the error does not make sense. To justify this intuition, Agda accepts the file if we translate the pattern match on `refl` to an application of `J`:
```agda
J : ∀ {ℓ ℓ′} {A : Set ℓ} {x : A} (P : (y : A) → x ≡ y → Set ℓ′)
  → P x refl → (y : A) (eq : x ≡ y) → P y eq
J P p x refl = p

@0 f : (X : Set) → A ≡ X → Set
f X eq = J {x = A} (λ _ _ → Set) {!!} X eq  -- SUCCEEDS
```
To fix this, I believe it would be fine to just turn off all erasure checks while checking the LHS of an erased function.

**Comment by nad** [comment]
> To fix this, I believe it would be fine to just turn off all erasure checks while checking the LHS of an erased function.

That makes sense to me.

**Comment by nad** [comment]
It appears to me as if generated `with` functions have the default modality:

https://github.com/agda/agda/blob/cf7ea79a8e6cb8fc62dd5a258f1d6317c5314cdd/src/full/Agda/TypeChecking/Rules/Def.hs#L1215

(Note the use of `defaultArgInfo`.) If that is the case, then the following code should presumably not be accepted:
```agda
open import Agda.Builtin.Equality

postulate @0 A : Set

@0 F : (X : Set) → A ≡ X → Set
F X eq with eq
… | refl = ?
```
However, this code is now accepted. @jespercockx, can you investigate this?

**Comment by jespercockx** [comment]
This doesn't seem to be a problem with unification in particular: the following code is also accepted:
```agda
open import Agda.Builtin.Bool

postulate @0 b : Bool

@0 f : Bool
f = true
  module M where
    b' = b
```
Here `M.b'` is regarded as erased so there is no actual problem. It's just that all definitions in a `where` block of an erased definition are automatically also marked as erased, which makes sense to me. Perhaps this should be added to the documentation at https://agda.readthedocs.io/en/v2.6.2.1/language/runtime-irrelevance.html.

**Comment by nad** [comment]
Are the generated `with` functions associated to an erased function treated as erased? The use of `checkFunDefS withFunType defaultArgInfo`, as well as the following documentation, suggest to me that they are not:

https://github.com/agda/agda/blob/cf7ea79a8e6cb8fc62dd5a258f1d6317c5314cdd/src/full/Agda/TypeChecking/Rules/Def.hs#L234-L236
