### ISSUE TITLE
New flag `--profile` replaces verbosity option `-vprofile`

### ISSUE THREAD

**Issue by nad** [agda/agda#5781]
I noticed that `-vprofile:7` overrides `-vprofile.definitions:10` and `-vprofile.modules:10`:

https://github.com/agda/agda/blob/ff82d4ab9009d5af8bd267661b65614564f63ed6/src/full/Agda/TypeChecking/Monad/Benchmark.hs#L60-L64

Is this intentional? It is not [documented](https://agda.readthedocs.io/en/v2.6.2.1/tools/performance.html#measuring-typechecking-performance).

**Comment by nad** [comment]
I guess the reason is that the current implementation cannot handle several of these options at once: if you activate both `-vprofile:7` and `-vprofile.modules:10` (say), then the output for modules will be incorrect, because only the innermost call to `billTo` "counts".

I see some ways forward:
* Make the code work.
* Make Agda complain if two or more of these options are activated at the same time. However, that would mean that Agda complains if you use `-vprofile:10`. An alternative is to use dedicated options for profiling.
* Update the documentation.

Given that I think this bug has low priority I don't want to spend too much time on it. I suggest that we simply update the documentation.

**Comment by andreasabel** [comment]
The usual semantics if `-v` is cumulative, so more instances of this flag can only add more output.

**Comment by UlfNorell** [comment]
> The usual semantics if -v is cumulative, so more instances of this flag ~~can~~ **should** only add more output.

Indeed, the use of `-v` for profiling is a bit of a hack, and we really should have a separate flag for it. How about
```
--profile=internal|definitions|modules|...
```
Aside from those three we also have `sharing`, `serialize`, `metas`, `constraints`, `interactive`, `iface`, and `ticks`. I believe those aren't using the billing system so they can all coexist without problems.

**Comment by nad** [comment]
Sounds good to me.
