### ISSUE TITLE
Private record fields do not work like expected

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#580]
```agda
record R : Set where
  private
    field
      i : ℕ

r : R
r = record { i = 42 }

get-i : R → ℕ
get-i r = F r refl
  where
    F : {n : ℕ} (r : R) → (r ≡ record { i = n }) → ℕ
    F {n} .(record { i = n }) refl = n

k : ℕ
k = get-i r

k-is-42 : k ≡ 42
k-is-42 = refl
```
Jonathan Leivent complains one can get the content of a private record field, I suspect this is due to constraint solving not respecting the scope.

However, I wonder why one can *set* a private field in the first place.  In my opinion, the definition of r should fail as well.

Original issue reported on code.google.com by `andreas....@gmail.com` on 26 Feb 2012 at 11:26

**Comment by andreasabel** [comment]
We could also have decided to interpret `private` for a record field that the respective projection is not exported while the content of the field can still be obtained by matching.
Maybe this can be diametral to the user expectations on the concept of a "private field", but it can help with the problem of irrelevant projections.
In particular, we could make irrelevant projections private unless `--irrelevant-projections` is given.
- #6359
