### ISSUE TITLE
The irrelevance axiom is provable inside Agda with --irrelevant-projections

### ISSUE THREAD

**Issue by jamestmartin** [agda/agda#5807]
The [documentation on irrelevance claims](https://agda.readthedocs.io/en/v2.6.2.1/language/irrelevance.html#irrelevant-declarations) that:

> ```agda
> postulate
>   .irrAx : ∀ {ℓ} {A : Set ℓ} -> .A -> A
> ```
>
> This axiom is not provable inside Agda, but it is often very useful when working with irrelevance.

However, with `--irrelevant-projections` enabled, the irrelevance axiom is easy to prove:

```agda
record Squash {ℓ} (A : Set ℓ) : Set ℓ where
  constructor squash
  field
    .unsquash : A
open Squash

.irrAx : ∀ {ℓ} {A : Set ℓ} → .A → A
irrAx x = unsquash (squash x)
```

The documentation should be amended to clarify that the irrelevance axiom *is* provable, but only with `--irrelevant-projections`, and indeed, in #429 it was claimed the irrelevance axiom ["is how irrelevant projections are justified"](https://github.com/agda/agda/issues/429#issuecomment-129023287). 

Additionally, in #543, Jespr Cockx also claims that ["irrelevant projections [...] imply some form of non-constructive choice"](https://github.com/agda/agda/issues/543#issuecomment-469257443) which might also be worth documenting.

**Comment by jamestmartin** [comment]
The irrelevance axiom/`--irrelevant-projections` proves (at least?) something which looks like AC(infinity, -1) as described by the HoTT book:

```agda
choice : ∀ {ℓ₁ ℓ₂} {X : Set ℓ₁} {Y : X → Set ℓ₂} → (∀ x → Squash (Y x)) → Squash (∀ x → Y x)
choice f = squash λ x → unsquash (f x)
```

which is simple enough that it could probably even be included inline in the docs, if you think the non-constructive choice thing is worth noting (and if it actually is a form of non-constructive choice).

**Comment by gallais** [comment]
I think the accepted meaning of "provable in Agda" implies that `--safe` should be turned on.
And `--safe` is incompatible with `--irrelevant-projections`.

**Comment by jamestmartin** [comment]
Ah, you're right. I hadn't noticed. I disabled `--safe` so I could mess with `irrAx` but didn't try to re-enable it when adding `--irrelevant-projections`. That makes this a lot less of a problem if you want to just close the issue.

Though, it still could be informative to mention that `--irrelevant-projections` implies `irrAx` (and thus a form of non-constructive choice) if you think that's worthwhile. It might be obvious to most people but it wasn't to me (though it was trivial to prove once I knew you could). It wasn't obvious to me why the irrelevance axiom was unsafe until I saw the issues I referenced above, which I only was able to find when I searched the bug tracker for "irrelevance" when creating this issue.

**Comment by jamestmartin** [comment]
I documented my findings for anyone who ends up confused about the same topic [on Proof Assistants SE](https://proofassistants.stackexchange.com/a/932/788). The answer should get indexed by search engines whenever the site enters public beta. I also asked [a follow-up question](https://proofassistants.stackexchange.com/q/965/788) to try to contextualize the implications of adding the irrelevance axiom.
