### ISSUE TITLE
Panic at Cubical.hs:2265 with `--without-K` and `--prop`

### ISSUE THREAD

**Issue by jamestmartin** [agda/agda#5816]
Encountered while trying to convert some code from `Set` to `Prop`.

Example:
```agda
{-# OPTIONS --without-K --prop #-}

open import Agda.Builtin.Nat renaming (Nat to ℕ; zero to Z; suc to S)

data _≤_ : ℕ → ℕ → Prop where
  z≤x : ∀ {x} → Z ≤ x
  s≤s : ∀ {x y} → x ≤ y → S x ≤ S y

x≤Sy : ∀ {x y} → x ≤ y → x ≤ S y
x≤Sy z≤x = z≤x
x≤Sy (s≤s p) = s≤s (x≤Sy p)
```

Error log with latest master:
```
/data/code/tmp/bug.agda:10,1-11,28
Panic: Pattern match failure in 'do' block at
src/full/Agda/TypeChecking/Primitive/Cubical.hs:2265:7-21
when checking the definition of x≤Sy
```

Log with 2.6.2.1:
```
Checking bug (/data/code/tmp/bug.agda).
```

I wanted to run a bisect but `agda-bisect` does not work with recent versions of cabal and I don't have any old versions installed.

(Btw, what is `Issue5789.agda` doing at the root of the repo? Shouldn't that be in the test cases folder?)

**Comment by andreasabel** [comment]
> (Btw, what is `Issue5789.agda` doing at the root of the repo? Shouldn't that be in the test cases folder?)

Thanks for the alert!  Fixed in  5401dc157fa3dda3a1bac06c09f222436d81c3c4 .

**Comment by andreasabel** [comment]
bisection blames commit c9ff1cd53276921356e999c79340b1cc2f89047a (ping @Saizan).
> Date:   Tue Aug 3 11:30:37 2021 +0200
> [ re #3733 ] handle non-fibrant types and other small fixes

Crash site: https://github.com/agda/agda/blob/5401dc157fa3dda3a1bac06c09f222436d81c3c4/src/full/Agda/TypeChecking/Primitive/Cubical.hs#L2265
`toLType` does not cover `Prop`.  Is this intended?

**Comment by andreasabel** [comment]
@jamesstmartin wrote:
> I wanted to run a bisect but `agda-bisect` does not work with recent versions of cabal and I don't have any old versions installed.

The draft version of `agda-bisect` at https://github.com/agda/agda/pull/5820 works with cabal v2-style commands now.  I used it to run bisection on this issue.  However, you also need old GHCs, in this case 8.8.  (See the list at https://wiki.portal.chalmers.se/agda/Main/Download.)

**Comment by jamestmartin** [comment]
ghcup supports GHC 8.8 so that's a lot more convenient for me. I'll see if I can use it next time I find a regression between my oldest installed version of Agda and master. Thanks for letting me know.

**Comment by jamestmartin** [comment]
Another small example:

```agda
{-# OPTIONS --without-K --prop #-}
open import Agda.Builtin.Equality

data _≐_ {ℓ} {A : Set ℓ} (x : A) : A → Prop ℓ where
  refl' : x ≐ x

squash-≡ : ∀ {ℓ} {A : Set ℓ} {x y : A} → x ≡ y → x ≐ y
squash-≡ refl = refl'
```

**Comment by plt-amy** [comment]
Part of #6049

**Comment by plt-amy** [comment]
No longer a panic as of 569375ea62, now this is the same error message issue as #6001. Should this be closed as a duplicate?
