### ISSUE TITLE
Agsy/Auto panics with `-r` in the presence of a pattern synonym

### ISSUE THREAD

**Issue by kindaro** [agda/agda#5828]
See:

```agda
module x where

data X : Set
  where x : X

pattern y = x

theorem : X
theorem = {-r }0
```

_(You will need to erase the hole and make a new one in the same place for Agda to understand what you mean.)_

If you try to fill the hole with [automatic proof search][1], you will see an error like this:

```
Panic: Unbound name: x.y[0,6]@ModuleNameHash 15504699851561257075
```

Without `-r`, the hole is automatically filled with `y`.

I am on Agda 2.6.3 built recently from source.

[1]: https://agda.readthedocs.io/en/latest/tools/auto.html#auto

**Comment by andreasabel** [comment]
Thanks for reporting, @kindaro.  Auto has no maintainer, so there is little hope this is going to be fixed...

**Comment by kindaro** [comment]
Wow well good to know. I am learning Agda yet so I cannot solve this myself but maybe some time later I could!

**Comment by jespercockx** [comment]
This might be the same problem as https://github.com/agda/agda/issues/5551, so not a problem with auto itself after all.
