### ISSUE TITLE
Strange error message when mixing --safe and NO_TERMINATION_CHECK

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#586]
```
$ cat Test.agda
module Test where

{-# NO_TERMINATION_CHECK #-}

Foo : Set
Foo = Foo

$ agda --safe Test.agda
Checking Test (/tmp/Test.agda).
/tmp/Test.agda:5,1-10
Cannot postulate Foo with safe flag
when scope checking the declaration
  Foo : Set
```

There should perhaps be a note in the release notes documenting the interaction between these two features.

Original issue reported on code.google.com by `nils.anders.danielsson` on 12 Mar 2012 at 1:51

**Comment by asr** [comment]
The was fixed by 718b175fe81e9b9c4ffea3e270fdb40758c48dbf.
