### ISSUE TITLE
GHC 9.0.2 missing warning: -Wunicode-bidirectional-format-characters

### ISSUE THREAD

**Issue by asr** [agda/agda#5876]
GHC 9.0.2 adds the  [`-Wunicode-bidirectional-format-characters`](https://downloads.haskell.org/~ghc/9.0.2/docs/html/users_guide/using-warnings.html#ghc-flag--Wunicode-bidirectional-format-characters) to the standard warnings.

**Comment by andreasabel** [comment]
@asr: Please read https://github.com/agda/agda/commit/fe75c14b8c963ee0f1b3aeade49e8f0ba2eeb125#r72324051

**Comment by andreasabel** [comment]
Thanks!
