### ISSUE TITLE
Caching in the stack.yml CI workflow done correctly?

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5887]
Atm, we are restoring the cache after doing `stack update`:
https://github.com/agda/agda/blob/7bda16229ef4728761a9b538f17bb63e20777618/src/github/workflows/stack.yml#L150-L166
A few questions:
1. Is `stack update` actually needed?  Cannot find this step in e.g. https://github.com/freckle/stack-action/blob/605917bad6487161de15eea71f03163f9d37399f/action.yml
2. Does `stack update` write to the `~/.stack/` directory?  If yes, aren't we overwriting the effects of this update when restoring `~/.stack/` from the cache later?
3. Shouldn't we also cache `.stack-work/`?
4. Can we delegate the caching to a third-party action like https://github.com/freckle/stack-cache-action ?  (This caches all stack working directories.)

Ping @L-TChen .

**Comment by L-TChen** [comment]
1. `stack update` creates `${STACK_ROOT}/config.yaml` which is needed in the following step (`echo ...`) 
2. Yes, if cache succeeds. Otherwise, the stack index needs to be updated anyway. Changing the order and using a conditional may work as well.
3. This workflow checks if Agda can be built from scratch, except dependencies, using `stack`. Caching `.stack-work` may store older snapshots and increase the cache size out of control. 
4. I don't know `stack-cache-action`, so we give it a try? 

The cache setup is not perfect, as we spot some weird errors like `Agda.Version` cannot be loaded in the other workflow. Do you spot anything wrong with `stack.yaml`?

**Comment by andreasabel** [comment]
Re 4.: I tried `stack-cache-action` but found it isn't sufficiently mature:
- https://github.com/freckle/stack-cache-action/issues/68
- https://github.com/freckle/stack-cache-action/issues/69

Re 2.: Restoring an old `.stack/` _after_ `stack update` and `stack configure` does not feel safe.  E.g. where are the results of `stack update` stored if not inside `.stack/` somewhere?
I wonder whether this causes problems like:
- #5909

**Comment by andreasabel** [comment]
@L-TChen wrote:
> 3\. Caching `.stack-work` may store older snapshots and increase the cache size out of control.

This is a valid concern, I raised it to the author of https://raehik.github.io/2021/03/01/caching-stack-and-cabal-haskell-builds-on-github-actions.html at:
- https://github.com/raehik/raehik.github.io/issues/1

**Comment by andreasabel** [comment]
> 1. `stack update` creates `${STACK_ROOT}/config.yaml` which is needed in the following step (`echo ...`)

I think rather then putting `system-ghc: true` into `config.yaml` we can simply add `--system-ghc` to the `ARGS`.

If we hash `stack.yaml` instead of `stack.yaml.lock` for the cache-key we could also skip the `stack build --dry-run` step.

As you suggest, we could try skipping `stack update` if we get a cache hit.

**Comment by andreasabel** [comment]
Trivia:
- `stack.yml`: The cached `.stack` directory is [roughly 300MB](https://github.com/agda/agda/runs/6692465916?check_suite_focus=true#step:7:19) per instance, and we have 10 instances (8 Linux, 1 macOS, 1 Windows ([360MB](https://github.com/agda/agda/runs/6692466290?check_suite_focus=true#step:7:17))), totalling to ~3GB.
- `test.yml`: [Same 300MB](https://github.com/agda/agda/runs/6692456195?check_suite_focus=true#step:7:16), 4 workflows, totaling to 1.2GB.
- `cabal.yml`: The cached `.cabal/store` is [only 20MB](https://github.com/agda/agda/runs/6692465916?check_suite_focus=true#step:7:19), totalling to ~200MB.
- `cabal-test.yml`: The cached `.cabal/store` is [~76MB](https://github.com/agda/agda/runs/6692464531?check_suite_focus=true#step:6:12) per instance, and we have 2 (Linux, macOS), totalling to ~150MB.
- `haddock.yml`: [25MB](https://github.com/agda/agda/runs/6692455756?check_suite_focus=true#step:6:11)
- `deploy.yml`,  `hlint.yml`, `user-manual.yml` do not cache.

The total cache limit for a repo is [10 GB](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows) and unused cache entries are stored for 7 days max.

Or total caches (1 snapshot) sum to around 5GB.
So we do not have space to save several snapshots really, at least for the `stack` workflows.  This is to be taken into account when structuring the cache keys.  Currently things work fine: branches usually restore the cache from `master` and do not write a cache entry subsequently.  (If they did, they could bump the `master` cache out, breaking the cache logic.)

**Comment by andreasabel** [comment]
Implemented https://github.com/agda/agda/issues/5887#issuecomment-1129110313 in
- #5957

**Comment by andreasabel** [comment]
Since everything has gone well for the `stack.yml` workflow for a long time, I am not porting this to `test.yml` in:
- #6358
