### ISSUE TITLE
Use `emacs --batch` mode in `agda-mode` setup

### ISSUE THREAD

**Issue by catern** [agda/agda#5901]
agda-mode setup should just run "emacs --batch" and have Emacs write the results of the query to stdout, instead of using a temporary file. Besides greatly simplifying the current askEmacs function, it would also work properly when running "agda-mode setup" without a terminal, which currently doesn't work.

(I would just make this patch myself but I can't figure out how to get agda building inside a Nix development shell)

**Comment by andreasabel** [comment]
The relevant code snippet is this: https://github.com/agda/agda/blob/257a324006bc1758d58a0e4c2a132b2ab4c7ab05/src/agda-mode/Main.hs#L163-L177
Documentation of `emacs --batch` here: https://www.emacswiki.org/emacs/BatchMode

**Comment by andreasabel** [comment]
@catern, how does this work?
```sh
$ emacs --batch --eval "(expand-file-name user-init-file)"
Wrong type argument: stringp, nil
```
Maybe emacs in batch mode does not know about  `user-init-file`?
Bingo!:
```sh
$ emacs --batch --eval="(print user-init-file)" 

nil
```

So, I suppose this does not work... Closing...

**Comment by catern** [comment]
Ah, that's true. If you pass `--user=''` to set init-file-user to an empty string then Emacs will load the init file normally:
```
emacs --user='' --batch --eval  '(princ (expand-file-name user-init-file))'
```
prints `/home/catern/.emacs.d/init.el` to stdout for me (no newline)

**Comment by andreasabel** [comment]
On my system, this prints extra garbage:
```
$ emacs --user='' --batch --eval '(print (expand-file-name user-init-file))' 2> /dev/null
#[nil "\300C\207"
      [t]
      1]

"/Users/abel/.emacs"
```
However, what currently is done in `agda-mode` works correctly:
```
$ emacs --user='' --batch --eval '(with-temp-file "foo.txt" (insert (expand-file-name user-init-file)))' 2> /dev/null
#[nil "\300C\207"
      [t]
      1]
$ cat foo.txt 
/Users/abel/.emacs
```

**Comment by catern** [comment]
Hm, that's weird, but it's definitely something that it's important to be tolerant of - a user's init file could do anything, including printing random stuff to standard-output. So I guess sticking with the temp-file is best.

It's still good to switch to `--batch` even though it doesn't simplify the implementation, because it allows agda-mode setup to be run without a terminal - e.g. `M-& agda-mode setup` inside Emacs, or `ssh localhost agda-mode setup`, will start working. (Also it avoids the momentary flicker of Emacs starting up)

**Comment by andreasabel** [comment]
I switch to `--batch` in 
- #5908

Please test!

**Comment by nad** [comment]
> Please test!

The new code triggers a warning for me:
```
Warning (initialization): An error occurred while loading ‘[…]/.emacs’:
```
My current `.emacs` does not work properly together with `--no-site-file`. If we have to run the users' `.emacs` files, then I don't think we should use `--no-site-file`. However, the old code did not load `.emacs`, right?

An alternative might be to ensure that Emacs is run inside a terminal, but I don't know how to do that in a platform-independent way.

**Comment by andreasabel** [comment]
> However, the old code did not load `.emacs`, right?

Well, I think it did: https://github.com/agda/agda/pull/5908/files#r881547737

But we can of course load the site file.  Please test again:
- https://github.com/agda/agda/pull/5919

**Comment by nad** [comment]
I manually ran code similar to what is in your pull request, and that seems to have worked.
