### ISSUE TITLE
error using VSCode

### ISSUE THREAD

**Issue by jxxcarlson** [agda/agda#5902]
Below (1) is the error message I get on file (2).  Example: I opened the file in emacs, did ctrl-C, ctrl-L.  It did the syntax checking.  Then I did ctrl-C, ctrl-P and dismissed the dialogue that came up.  Then I did ctrl-C, ctrl-L again and got the error.

This after getting errors in VSCode.  It was working fine for a few hours, then stopped responding normally.  I quit, re-opened, and ran crl-C ctrl-L again.  This time I got the error below right away.

**(1)**
```
Emacs v2.6.1.1-fce01db
Error
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/Interaction/Highlighting/Emacs.hs:49
```

**(2)**
```agda
{-# OPTIONS --without-K --exact-split --safe #-}

module HoTT-UF-Agda where

open import Universes public

-- UNIT TYPE

data 𝟙 : 𝓤₀ ̇ where
  * : 𝟙

𝟙-induction : (A : 𝟙 → 𝓤₀ ̇) → A * → ( x : 𝟙) → A x
𝟙-induction A a * = a

𝟙-recursion : (B : 𝓤₀ ̇) → B → (𝟙 → B)
𝟙-recursion B b x = 𝟙-induction (λ _ → B) b x

!𝟙' : (X : 𝓤₀ ̇) → X → 𝟙
!𝟙' X x = *

!𝟙 : {X : 𝓤₀ ̇} → X → 𝟙
!𝟙 x = *
```

**Comment by andreasabel** [comment]
Thanks for the report!

> Emacs v2.6.1.1-fce01db

I see that you are not using the latest version of Agda.  This would be either 2.6.2.2 (released) or 2.6.3 (unreleased, from this repo).  We only fix bugs that appear in the latest version.
