### ISSUE TITLE
Locale-independent handling of filenames?

### ISSUE THREAD

**Issue by ncfavier** [agda/agda#5903]
On Linux, trying to check an Agda file that imports files with Unicode characters in their name fails when using a non-UTF-8 locale.

For example, the following Nix derivation

```nix
with import <nixpkgs> {};
let unicode = "⟨⟩"; in
runCommand "agda-unicode" {
  nativeBuildInputs = [ agda ];
} ''
  touch ${unicode}.agda
  echo "import ${unicode}" > Everything.agda
  agda -v2 Everything.agda
''
```

fails with 

```
Checking Everything (/build/Everything.agda).
Error raised at typeError, called at src/full/Agda/Interaction/FindFile.hs:132:17 in Agda-2.6.2.2-5acg4H9AdWxD2sJYwJjHkp:Agda.Interaction.FindFile
/build/Everything.agda:1,1-10
Failed to find source of module
```

or with `-v5`

```
  Getting interface for Everything
  Everything is not up-to-date because the interface has not been decoded and the interface file could not be found.
Checking Everything (/build/Everything.agda).
Creating interface for Everything.
Scope checking Agda.Primitive
Scope checking /build/Everything.agda:1,1-10
<stdout>: commitBuffer: invalid argument (invalid character)
```

and succeeds after adding `LANG = "C.UTF-8";`.

Why is that needed? According to the doc, Agda files are UTF-8 encoded.

More context at https://github.com/NixOS/nixpkgs/issues/172752

**Comment by greydot** [comment]
>Why is that needed? According to the doc, Agda files are UTF-8 encoded.

Just passing by. While Agda files _contain_ UTF-8, filenames aren't a part of file. Agda must call a C function to open a file and that's where it fails. So, it's more of a C bug and not Agda.

See, for example, this issue https://github.com/libarchive/libarchive/issues/587

**Comment by nad** [comment]
See #4678.
