### ISSUE TITLE
agda-mode compile not working (macOS 11.6.5)

### ISSUE THREAD

**Issue by GetContented** [agda/agda#5912]
Complete emacs noob here. Trying to get agda-mode working in emacs, but it seems to be failing with `agda-mode compile`. The setup seemed to work just fine, though. Wondering if someone could point me in the right direction if I'm doing something incorrectly.

reference: https://github.com/plfa/plfa.github.io/issues/644

```
In toplevel form:
~/code/agda/agda/.stack-work/install/x86_64-osx/2ea356db11ab153a6ba147b7da51aa71a671fd44c574cb318e18fbe51bafd587/8.8.3/share/x86_64-osx-ghc-8.8.3/Agda-2.6.1.3/emacs-mode/annotation.el:6:1:Error: Package cl is deprecated

In toplevel form:
~/code/agda/agda/.stack-work/install/x86_64-osx/2ea356db11ab153a6ba147b7da51aa71a671fd44c574cb318e18fbe51bafd587/8.8.3/share/x86_64-osx-ghc-8.8.3/Agda-2.6.1.3/emacs-mode/eri.el:7:1:Error: Package cl is deprecated

In toplevel form:
~/code/agda/agda/.stack-work/install/x86_64-osx/2ea356db11ab153a6ba147b7da51aa71a671fd44c574cb318e18fbe51bafd587/8.8.3/share/x86_64-osx-ghc-8.8.3/Agda-2.6.1.3/emacs-mode/agda-input.el:22:1:Error: Package cl is deprecated

In toplevel form:
~/code/agda/agda/.stack-work/install/x86_64-osx/2ea356db11ab153a6ba147b7da51aa71a671fd44c574cb318e18fbe51bafd587/8.8.3/share/x86_64-osx-ghc-8.8.3/Agda-2.6.1.3/emacs-mode/agda2-highlight.el:11:1:Error: Package cl is deprecated

In toplevel form:
~/code/agda/agda/.stack-work/install/x86_64-osx/2ea356db11ab153a6ba147b7da51aa71a671fd44c574cb318e18fbe51bafd587/8.8.3/share/x86_64-osx-ghc-8.8.3/Agda-2.6.1.3/emacs-mode/agda2-mode.el:17:1:Error: Package cl is deprecated
Unable to compile the following Emacs Lisp files:
  /Users/getcontented/code/agda/agda/.stack-work/install/x86_64-osx/2ea356db11ab153a6ba147b7da51aa71a671fd44c574cb318e18fbe51bafd587/8.8.3/share/x86_64-osx-ghc-8.8.3/Agda-2.6.1.3/emacs-mode/annotation.el
  /Users/getcontented/code/agda/agda/.stack-work/install/x86_64-osx/2ea356db11ab153a6ba147b7da51aa71a671fd44c574cb318e18fbe51bafd587/8.8.3/share/x86_64-osx-ghc-8.8.3/Agda-2.6.1.3/emacs-mode/eri.el
  /Users/getcontented/code/agda/agda/.stack-work/install/x86_64-osx/2ea356db11ab153a6ba147b7da51aa71a671fd44c574cb318e18fbe51bafd587/8.8.3/share/x86_64-osx-ghc-8.8.3/Agda-2.6.1.3/emacs-mode/agda-input.el
  /Users/getcontented/code/agda/agda/.stack-work/install/x86_64-osx/2ea356db11ab153a6ba147b7da51aa71a671fd44c574cb318e18fbe51bafd587/8.8.3/share/x86_64-osx-ghc-8.8.3/Agda-2.6.1.3/emacs-mode/agda2-highlight.el
  /Users/getcontented/code/agda/agda/.stack-work/install/x86_64-osx/2ea356db11ab153a6ba147b7da51aa71a671fd44c574cb318e18fbe51bafd587/8.8.3/share/x86_64-osx-ghc-8.8.3/Agda-2.6.1.3/emacs-mode/agda2-mode.el
```

**Comment by andreasabel** [comment]
> if I'm doing something incorrectly.

Well, you are not using the latest release of Agda, which is 2.6.2.2 (you use 2.6.1.3).
I suspect you are on Emacs > 26.  Emacs 27 does not tolerate package `cl` anymore, but we switched to `cl-lib` in aa5e3a127bf17a8c80d947f3c286758a36dadc36 in Sep 2020, and this patch was released with Agda 2.6.2 in June 2021.

Upgrading Agda could fix your problem.  
(General strategy: upgrade to the latest version of product X before reporting a bug in X, since it could have been fixed in the lastest release of X.)

**Comment by andreasabel** [comment]
@GetContented : I am closing this issue because I believe it is fixed by Agda 2.6.2.  Should you still experience the problem after updating, please reopen the issue.

**Comment by GetContented** [comment]
Aplogies @andreasabel — I was following the suggestions by the PLFA book, which locks it to a certain version (for pedagogical reasons, I'm fairly sure). Bit of an annoying conundrum, really! I'll see how I go.

**Comment by nad** [comment]
There is no need to run `agda-mode compile` in order to use Agda's Emacs mode. However, if Emacs can choose between byte-compiled files and source files, then the byte-compiled files are (by default) chosen, even if the source files are newer. (At least for some version of Emacs.)
