### ISSUE TITLE
Arrow notation a-la Haskell

### ISSUE THREAD

**Issue by Mr-Andersen** [agda/agda#5913]
Feature request: support arrow notation like Haskell does: https://downloads.haskell.org/ghc/latest/docs/html/users_guide/exts/arrows.html

**Comment by andreasabel** [comment]
Mr. Andersen, could you please provide a motivation in form of mouth-watering (fantasy) code snippets?  
Also, do we have an arrow library yet for Agda?  
What would be the killer app for the arrow notation?  (In Haskell, I rarely come across uses of this notation, and of Arrows in general.  They seem fringe in comparison to Applicative and Monad.)

**Comment by Mr-Andersen** [comment]
@andreasabel
Motivation: arrows syntax may represent a program that requires only Arrow typeclass (~Applicative), ArrowChoice (~Selective) or ArrowApply (~Monad). With Haskell's ApplicativeDo extension one can write code with do notation and expect it to only use Applicative. This doesn't extend to Selective class (because it's not in `base`), which would allow limited choice of following effect.
When you write Arrow code, you can use uniform syntax and require minimal instances for your code. Programs that require only Arrow or full ArrowApply would look alike, and differ only on call-site - depending of set of requirements, you would need to use different interpreters.
In couple of days I will write small parsing library and provide snippets that use Arrow notation.

**Comment by Mr-Andersen** [comment]
About arrow library for Agda: neither agda-stdlib nor agda-prelude seem to define needed types

**Comment by andreasabel** [comment]
I think before we change the Agda language, we need solid evidence that the new feature will see substantial following.
This does not seem the case at the moment, with no Arrow library known.

Also, notice that one can do monadic programming without the `do` notation, and Agda long did not have the `do` notation, but folks were using `>>=` (bind) directly.  Only after sufficient experience with Monads in a dependently type setting, and a plan how to generalize `do` to indexed monads etc., a `do`-notation was added.

So I presume we follow the same path for new sugar.  An arrow notation is not really necessary to program with arrows.  

But if/once there are convincing concepts of dependently-typed arrows with substantial applications, we can investigate arrow-notation for Agda.

**Comment by Mr-Andersen** [comment]
Well, was worth a try :)
