### ISSUE TITLE
agda-mode C-, and C-. and C-; not working

### ISSUE THREAD

**Issue by GetContented** [agda/agda#5914]
Context:

```
➜  plfa git:(dev) ✗ sw_vers
ProductName:	macOS
ProductVersion:	11.6.5
BuildVersion:	20G527
➜  plfa git:(dev) ✗ agda --version
Agda version 2.6.2.2-442c76b
➜  plfa git:(dev) ✗ emacs --version
GNU Emacs 27.2
Copyright (C) 2021 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

Code context:

```
from : Bin → ℕ
from ⟨⟩ = { }0
from (b O) = { }1
from (b I) = { }2
```

Within the first hole, if I try to use C-c C-, or C-c C-. or C-c C-; the punctuation character is not recognised as a command and agda beeps at me and displays C-c waiting for the next part of the command.

**Comment by andreasabel** [comment]
Does your Emacs work correctly in other situations when it comes to input control sequences?
How long have you been using Emacs?

**Comment by GetContented** [comment]
I've been using Emacs about 2 days, so I'm a total noob pretty much.

I'm not sure what you mean by "input control sequences", but everything else I've tried works, pretty much.

If I type `\bN` then agda mode prints `ℕ` just fine. If I use C-a and C-e it goes to beginning and end of line, and C-v goes to next page. C-c C-f and C-c C-b work for moving between holes just fine, and C-c C-l works for typechecking/loading just fine. Also C-c C-t (goal type) works.

**Comment by nad** [comment]
Are you using Emacs in a terminal?

**Comment by fredrikNordvallForsberg** [comment]
This seems to be a known problem when running Emacs in a terminal, see for example https://emacs.stackexchange.com/questions/1020/problems-with-keybindings-when-using-terminal and linked and answers therein. Looks like the most reliable solution is "Don't run Emacs in a terminal, but use the GUI version instead"... Or you could try and [rebind the keys for the commands in question](https://www.gnu.org/software/emacs/manual/html_node/emacs/Init-Rebinding.html) instead: `C-c C-,` is `agda2-goal-and-context`, `C-c C-.` is `agda2-goal-and-context-and-inferred`, and `C-c C-;` is `agda2-goal-and-context-and-checked`.

**Comment by GetContented** [comment]
> Are you using Emacs in a terminal?

Yes, because agda mode isn't working at all for me in Aquamacs. It also doesn't work in VSCode properly, but I have an issue open in the VSCode plugin for that.

So far I've just not been using those features.

**Comment by andreasabel** [comment]
On my mac, I use https://emacsformacosx.com/ (rather than Aquamacs).

**Comment by GetContented** [comment]
Acquamacs is the recommended approach on the mac on the recommended tutorial for learning Agda (PLFA). Just for some context as to why I was trying to use it.

I guess I'll close this.
