### ISSUE TITLE
Constraint solving does not honor singleton types

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#593]
```agda
bla7 : (F : Unit -> Set) ->
  let X : Set
      X = _
  in (z : Unit) -> X ≡ F z
bla7 F z = refl
```
Error
```
Cannot instantiate the metavariable _37 to solution F z since it
contains the variable z which is not in scope of the metavariable
or irrelevant in the metavariable but relevant in the solution
when checking that the expression refl has type _37 F ≡ F z
```
This error is unjustified.  The offending `z` can be eta-expanded away, giving solution `_37 F = F unit`.

Well this might be a constructed example, still Agda should be able to solve this.

Working on it...

Original issue reported on code.google.com by `andreas....@gmail.com` on 30 Mar 2012 at 1:51

**Comment by andreasabel** [comment]
See #2625 for the more general problem.
