### ISSUE TITLE
On `-Werror`

### ISSUE THREAD

**Issue by asr** [agda/agda#5934]
After adding `-Werror` to `Agda.cabal` as a workaround for #5932, CI reported [this](https://github.com/agda/agda/runs/6676023533) problem (which I'm planning to fix).

It seems `-Werror` was removed on 9365d0900f. Was there some specific reason for removing it and using the more verbose form `-Werror=warning-name` for setting on the warnings?

**Comment by andreasabel** [comment]
There may be some background at:
- https://github.com/agda/agda/pull/4817

(Seems plausible though that one actively decides which warnings should be errors.)
