### ISSUE TITLE
On workflow for GitHub workflows

### ISSUE THREAD

**Issue by asr** [agda/agda#5935]
I'm planning to fix [this](https://github.com/agda/agda/runs/6676023533) problem. Without changing the files in `src/github/workflows`, I followed the instructions in https://github.com/agda/agda/blob/46031e1435d323ef79de916bf7d985f7aa63729e/src/github/workflows/README.md#L6-L7

by running

```bash
$ cd .github/workflows
$ make
$ git status
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   deploy.yml
	modified:   stack.yml
	modified:   test.yml
```
Why there where changes in the above files? Shouldn't be the files on `.github/workflows` synchronized with the files on `src/github/workflows`?

**Comment by andreasabel** [comment]
Maybe you are using a different version of the converters?  I have
```
$ yaml2json --version
yaml2json version 0.11.6.0 https://github.com/snoyberg/yaml/
$ json2yaml --version
json2yaml version 0.11.6.0 https://github.com/snoyberg/yaml/
```

**Comment by asr** [comment]
Right, my version for both converts is 0.11.8.0. So?

**Comment by andreasabel** [comment]
You can push the changes, and I update to 0.11.8.0.

**Comment by andreasabel** [comment]
Mmh, it seems there is quite a change from the product of 0.11.6 to the product of 0.11.8.  But if CI still works, let's use 0.11.8.0.  Let me know your findings.

**Comment by asr** [comment]
In a fresh repository I'm running:

```bash
$ cd .github/workflows
$ make
aml2json ../../src/github/workflows/cabal-test.yml | json2yaml - >> cabal-test.yml
yaml2json ../../src/github/workflows/cabal.yml | json2yaml - >> cabal.yml
yaml2json ../../src/github/workflows/deploy.yml | json2yaml - >> deploy.yml
yaml2json ../../src/github/workflows/haddock.yml | json2yaml - >> haddock.yml
yaml2json ../../src/github/workflows/lint.yaml | json2yaml - >> lint.yaml
yaml2json ../../src/github/workflows/stack.yml | json2yaml - >> stack.yml
yaml2json ../../src/github/workflows/test.yml | json2yaml - >> test.yml
yaml2json ../../src/github/workflows/user_manual.yml | json2yaml - >> user_manual.yml
yaml2json ../../src/github/workflows/whitespace.yml | json2yaml - >> whitespace.yml

$ git status 
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   cabal-test.yml
	modified:   cabal.yml
	modified:   deploy.yml
	modified:   haddock.yml
	modified:   lint.yaml
	modified:   stack.yml
	modified:   test.yml
	modified:   user_manual.yml
	modified:   whitespace.yml

$ git reset --hard 
HEAD is now at 46031e143 Merge pull request #5933 from agda/issue-5932

$ make
make: Nothing to be done for 'all'.
```

Why the last command does not generate the `*.yaml` files?

**Comment by andreasabel** [comment]
> ```shell
> $ git reset --hard 
> ```

This changes timestamps (to "now"), and since `make` rules are triggered on timestamps, the rules might not run.  You can force making with:
```
$ make -B
```

(I think that `git` does not set the modification time to the time of the last commit is a bit silly and causes such problems.)
