### ISSUE TITLE
Date and time for files in the repository

### ISSUE THREAD

**Issue by asr** [agda/agda#5936]
I'm getting the following behaviour:

```bash
$ git clone git@github.com:agda/agda.git
$ cd agda
$ ls - l
total 244K
-rw-rw-r--  1 asr asr  48K Jun  1 07:43 Agda.cabal
drwxrwxr-x 12 asr asr 4.0K Jun  1 07:43 benchmark
-rw-rw-r--  1 asr asr 2.1K Jun  1 07:43 cabal.project.local.mtl23
-rw-rw-r--  1 asr asr  391 Jun  1 07:43 cabal.project.tc
-rw-rw-r--  1 asr asr 6.8K Jun  1 07:43 CHANGELOG.md
drwxrwxr-x  2 asr asr 4.0K Jun  1 07:43 cubical
drwxrwxr-x  6 asr asr 4.0K Jun  1 07:43 doc
drwxrwxr-x 23 asr asr 4.0K Jun  1 07:43 examples
-rw-rw-r--  1 asr asr 2.1K Jun  1 07:43 fix-whitespace.yaml
-rw-rw-r--  1 asr asr  966 Jun  1 07:43 flake.lock
-rw-rw-r--  1 asr asr 1.7K Jun  1 07:43 flake.nix
-rw-rw-r--  1 asr asr  22K Jun  1 07:43 HACKING.md
-rw-rw-r--  1 asr asr  547 Jun  1 07:43 hie.yaml
-rw-rw-r--  1 asr asr 5.2K Jun  1 07:43 LICENSE
drwxrwxr-x  2 asr asr 4.0K Jun  1 07:43 macros
-rw-rw-r--  1 asr asr  28K Jun  1 07:43 Makefile
drwxrwxr-x  2 asr asr 4.0K Jun  1 07:43 mk
drwxrwxr-x  8 asr asr 4.0K Jun  1 07:43 notes
-rw-rw-r--  1 asr asr 1.9K Jun  1 07:43 README.md
-rwxrwxr-x  1 asr asr 5.6K Jun  1 07:43 release.sh
-rw-rw-r--  1 asr asr 4.7K Jun  1 07:43 Setup.hs
drwxrwxr-x 10 asr asr 4.0K Jun  1 07:43 src
-rw-rw-r--  1 asr asr  577 Jun  1 07:43 stack-8.0.2.yaml
-rw-rw-r--  1 asr asr  169 Jun  1 07:43 stack-8.10.7.yaml
-rw-rw-r--  1 asr asr  453 Jun  1 07:43 stack-8.2.2.yaml
-rw-rw-r--  1 asr asr  353 Jun  1 07:43 stack-8.4.4.yaml
-rw-rw-r--  1 asr asr  417 Jun  1 07:43 stack-8.6.5.yaml
-rw-rw-r--  1 asr asr  258 Jun  1 07:43 stack-8.8.4.yaml
-rw-rw-r--  1 asr asr  669 Jun  1 07:43 stack-9.0.1.yaml
-rw-rw-r--  1 asr asr  167 Jun  1 07:43 stack-9.0.2.yaml
-rw-rw-r--  1 asr asr 2.9K Jun  1 07:43 stack-9.2.1.yaml
-rw-rw-r--  1 asr asr  114 Jun  1 07:43 stack-9.2.2.yaml
drwxrwxr-x  2 asr asr 4.0K Jun  1 07:43 std-lib
drwxrwxr-x 16 asr asr 4.0K Jun  1 07:43 test
-rwxrwxr-x  1 asr asr  303 Jun  1 07:43 touchup.sh
```

Why all the directories and files have the same date and time?

I'm using

```bash
$ git --version
git version 2.36.1
```

**Comment by andreasabel** [comment]
This is the creation time of these files.  `git` unfortunately does not set the last modification time to the time of the commit where they were last modified. 
See also discussion around:
- https://github.com/haskell/actions/issues/41#issuecomment-1120195000

**Comment by asr** [comment]
I feel stupid. All these years using `git` and I didn't know it. Thanks!

**Comment by andreasabel** [comment]
We live and learn...

**Comment by nad** [comment]
> `git` unfortunately does not set the last modification time to the time of the commit where they were last modified.

["Why isn't Git preserving modification time on files?"](https://git.wiki.kernel.org/index.php/Git_FAQ#Why_isn.27t_Git_preserving_modification_time_on_files.3F)

**Comment by andreasabel** [comment]
> > `git` unfortunately does not set the last modification time to the time of the commit where they were last modified.
> 
> ["Why isn't Git preserving modification time on files?"](https://git.wiki.kernel.org/index.php/Git_FAQ#Why_isn.27t_Git_preserving_modification_time_on_files.3F)

Building based on time stamps can go wrong in two ways:
1. If you date back the source, the target will not be rebuild.  This is what the git policy prevents.
2. If you date forward the target, the target will not be rebuild.  This is the problem here that the git policy _causes_.  

We are in some sense violating git policy since we are placing a target under VC. However, in this case, github workflows force us to do this, because AFAIK there is no pre-workflow hook that would _generate_ workflows from other sources in the repo.
