### ISSUE TITLE
The HTML user manual uses incorrect formatting

### ISSUE THREAD

**Issue by nad** [agda/agda#5942]
Some or all lists in the user manual are rendered incorrectly in the HTML document: there are no "bullets" or anything like that before the list items, and the items are not indented. See for instance the following list:

https://github.com/agda/agda/blob/ee8bf1d90086d46a567a4ad646e40c3d66fb9df3/doc/user-manual/language/runtime-irrelevance.lagda.rst?plain=1#L169-L181

**Comment by andreasabel** [comment]
@asr: Could you have a look?  Might be in connection with migrating to Sphinx 5...

**Comment by andreasabel** [comment]
Googling produced this:
- https://stackoverflow.com/questions/67542699/readthedocs-sphinx-not-rendering-bullet-list-from-rst-file
- https://sourceforge.net/p/docutils/bugs/417/

I'll try updating the RTD theme.

**Comment by andreasabel** [comment]
Seems to work.
