### ISSUE TITLE
Possible Termination Checker Error on HIT (cubical)

### ISSUE THREAD

**Issue by xekoukou** [agda/agda#5945]
In Cubical agda, it is common to use ```ElimProp``` in order to avoid proving on all the cases. This is possible if the goal is a proposition.

```agda

{-# OPTIONS --cubical #-}
open import Cubical.Foundations.Prelude


data HIT : Set where
  H1 H2 : HIT
  PR : H1 ≡ H2
  EQ : ∀ h1 h2 → h1 ≡ h2


postulate
  el : {B : HIT → Set} → ∀ x → B x

δ : HIT → HIT
δ H1 = H2
δ H2 = H1
δ (PR i) = PR (~ i)
δ (EQ x y i) = el {B = λ z → δ z ≡ δ y} x i

```

This on the other hand works : 

```agda

{-# OPTIONS --cubical #-}
open import Cubical.Foundations.Prelude


data HIT : Set where
  H1 H2 : HIT
  PR : H1 ≡ H2
  EQ : ∀ h1 h2 → h1 ≡ h2


δ : HIT → HIT
el : ∀ x y → δ x ≡ δ y

δ H1 = H2
δ H2 = H1
δ (PR i) = PR (~ i)
δ (EQ x y i) = el x y i

el x y = {!!}

```

**Comment by andreasabel** [comment]
> ```agda
> ...
> δ (EQ x y i) = el {B = λ z → δ z ≡ δ y} x i
> ```

So what should be the reason that this terminates?  The clause for `δ (EQ x y i)` makes a call to `δ z` where `z` is a bound variable of type `HIT`.  In what sense is `z` structurally smaller than `EQ x y i`?

**Comment by xekoukou** [comment]
The argument  ```B``` will not be used in the computation of function ```el```. I guess this is the reason the second case passes.

**Comment by andreasabel** [comment]
So, close this issue?

**Comment by andreasabel** [comment]
Closing, feel free to reopen if needed.
