### ISSUE TITLE
Recursor of inductive-inductive type does not pass termination check in Cubical Agda

### ISSUE THREAD

**Issue by szumixie** [agda/agda#5953]
The following code typechecks without the `--cubical` flag, but does not pass the termination checker with the flag:
```agda
{-# OPTIONS --cubical #-}

data Con : Set
data Ty : Con → Set

data Con where
  nil : Con
  ext : (Γ : Con) → Ty Γ → Con

data Ty where
  univ : (Γ : Con) → Ty Γ
  pi : (Γ : Con) (A : Ty Γ) → Ty (ext Γ A) → Ty Γ

module _
  (A : Set)
  (B : A → Set)
  (n : A)
  (e : (a : A) → B a → A)
  (u : (a : A) → B a)
  (p : (a : A) (b : B a) → B (e a b) → B a)
  where
  recCon : Con → A
  recTy : (Γ : Con) → Ty Γ → B (recCon Γ)

  recCon nil = n
  recCon (ext Γ A) = e (recCon Γ) (recTy Γ A)

  recTy Γ (univ Γ) = u (recCon Γ)
  recTy Γ (pi Γ A B) = p (recCon Γ) (recTy Γ A) (recTy (ext Γ A) B)
```

**Comment by andreasabel** [comment]
If you switch from `--cubical` to `--without-K`, the definition is accepted, because then _dot patterns_ are taken into consideration for termination certification.
- switching off dot pattern termination: #4606
- a regression reported in: #4725

**Comment by nad** [comment]
If the program should be rejected when `--cubical` is used, then it should also be rejected when `--without-K` is used, right?

**Comment by andreasabel** [comment]
Turning off dot-pattern termination for `--without-K` would mean that we could not do the usual proof by pattern matching that the successor relation is well-founded:
```agda
{-# OPTIONS --without-K #-}

open import Agda.Builtin.Nat using (Nat; zero; suc)

data Acc {A : Set} (R : A → A → Set) (x : A) : Set where
  acc : (∀ y → R y x → Acc R y) → Acc R x

data _<_ (x : Nat) : Nat → Set where
  <S : x < suc x

iswf< : ∀ x → Acc _<_ x
iswf< x = acc (h x)
  where
  h : ∀ x y → y < x → Acc _<_ y
  h .(suc y) y <S = acc (h y)
```

**Comment by andreasabel** [comment]
> If the program should be rejected when `--cubical` is used, then it should also be rejected when `--without-K` is used, right?

After the fix, it is accepted in both modes.  But see my previous comment for a violation of your principle.  Likely, the termination checker rejects too many programs under `--cubical`, just to be on the safe side. But with termination checking being undecidable, we accept that it is incomplete, and may also violate your principle.  (If you want your principle, we could e.g. have a check that `--cubical` is _actually necessary_, i.e. cubical features are positively used, because in this case, the type checker would already not succeed with just `--without-K`.)

**Comment by nad** [comment]
"My principle" is that code that is accepted when `--without-K` is used should be accepted also when `--with-K`, `--erased-cubical` or `--cubical` is used. Every extra check that is performed in Cubical Agda should also be performed when `--without-K` is used.

> Turning off dot-pattern termination for --without-K would mean that we could not do the usual proof by pattern matching that the successor relation is well-founded:

The code is accepted (with `--erased-cubical`) if the dot is moved:
```agda
iswf< : ∀ x → Acc _<_ x
iswf< x = acc (h x)
  where
  h : ∀ x y → y < x → Acc _<_ y
  h (suc y) .y <S = acc (h y)
```
However, Agda emits a warning:
```
Could not generate equivalence when splitting on indexed family,
the function will not compute on transports by a path.
  Reason: UnsupportedYet Injectivity
                           position:    0
                           type:        Nat
                           datatype:    Nat
                           parameters: 
                           indices:    
                           constructor: suc
when checking the definition of h
```

**Comment by nad** [comment]
> "My principle" is that code that is accepted when `--without-K` is used should be accepted also when `--with-K`, `--erased-cubical` or `--cubical` is used. Every extra check that is performed in Cubical Agda should also be performed when `--without-K` is used.

I realised that my statement is too strong. One could make Cubical Agda checks unnecessarily strict without the risk of breaking anything, and that may be the case for the check under discussion. @Saizan wrote the following:

https://github.com/agda/agda/blob/66643bc556c8d7b91a50a71a837e740c674f7309/src/full/Agda/Termination/TermCheck.hs#L243-L252

I'm not sure exactly how to interpret this. Would it make sense to include dot patterns when checking termination for a Cubical Agda definition that does not involve matching for HITs?

**Comment by andreasabel** [comment]
> Would it make sense to include dot patterns when checking termination for a Cubical Agda definition that does not involve matching for HITs?

I suppose so.
