### ISSUE TITLE
`interaction` testsuite requires `kpsewhich` installed

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5963]
Even though the interaction test `QuickLaTeX-Caching` does not call latex to compile the product, it needs the latex utility `kpsewhich` in the PATH, otherwise:
https://github.com/agda/agda/runs/6932943368?check_suite_focus=true#step:16:116
```
(agda2-info-action "*Error*" 
  "kpsewhich: readCreateProcessWithExitCode: posix_spawnp: does not exist (No such file or directory)" 
  nil)
```
The relevant code is here:
https://github.com/agda/agda/blob/fe6b24e4149ce006fed731c7de502617f42b8043/src/full/Agda/Interaction/Highlighting/LaTeX/Base.hs#L722-L727
Origin of the code: https://github.com/agda/agda/commit/748cdea4887e545fa05f673d4dfdaeae16d7f029#r76325757

It may be better to treat the exception (`kpsewhich` absent) like a non-successful execution (style file not found). 

Encountered while working on:
- #5962

**Comment by nad** [comment]
I don't think this change is a good idea. If kpsewhich is not installed and the file is already present in the target directory, then it is overwritten, even if the user has made local changes to the file.

**Comment by andreasabel** [comment]
Maybe we should have a simple check along `doesFileExist` in case the call to`kpsewhich` doesn't succeed?

**Comment by andreasabel** [comment]
> If kpsewhich is not installed and the file is already present in the target directory, then it is overwritten, even if the user has made local changes to the file.

Note that a user running the LaTeX backend (and actively making changes to `agda.sty`) will very likely have a TeX installation which includes `kpsewhich`.

**Comment by nad** [comment]
If the only reason for changing the code is that the test suite fails, then I think it is better to change the test suite than to change the code (and make it more complicated). Perhaps you could install a dummy program called kpsewhich.

**Comment by andreasabel** [comment]
Frankly, the error you used to get
```
kpsewhich: readCreateProcessWithExitCode: posix_spawnp: does not exist (No such file or directory)
```
wasn't a work of beauty, I had to grep the Agda source code to make sense of it.  Also, I found it hard to imagine that Agda would call a TeX utility even if TeX wasn't actually run.  
So, no, I do not want to go back to the previous state of the art.

**Comment by andreasabel** [comment]
@nad wrote:
> If kpsewhich is not installed and the file is already present in the target directory, then it is overwritten, even if the user has made local changes to the file.

Fixing that in #5965.
