### ISSUE TITLE
Changing .agda-lib file

### ISSUE THREAD

**Issue by guilhermehas** [agda/agda#5972]
I would like to run Agda outside the main directory because I am creating a tool [Bazel Agda](https://github.com/guilhermehas/rules_agda).

The idea is: instead of running `cd testing && agda a.agda`, I would run `agda --library-lib testing/testing.agda.lib -i testing testing/a.agda`.
I haven't found the answer in [Library Management](https://agda.readthedocs.io/en/v2.6.2.2/tools/package-system.html).

**Comment by andreasabel** [comment]
Would an option `--cwd testing` help here? (Run: `agda --cwd testing a.agda`.)
- #5915

**Comment by nad** [comment]
```
$ cat testing/testing.agda-lib
name: testing
include: .
$ cat testing/a.agda

$ tail -1 ~/.agda/libraries
/tmp/testing/testing.agda-lib
$ agda --library=testing testing/a.agda && echo "Success!"
Success!
```

**Comment by guilhermehas** [comment]
I think that I solved my problem with @nad idea and using a flag `--library-file` for my custom library file.

> Would an option `--cwd testing` help here? (Run: `agda --cwd testing a.agda`.)
> 
> * [Add option `--cwd DIR`  #5915](https://github.com/agda/agda/issues/5915)

This can be useful too.
