### ISSUE TITLE
Internal error on emacs mode with module name of different case than file name (WinXP)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#600]
To reproduce:

1. Create a file `aA.agda` with contents `module aa where` (notice the case difference)
2. Load the file on emacs

On Windows XP, with Agda-2.3.0, I get:
```
  An internal error has occurred. Please report this as a bug.
  Location of the error: src/full\Agda\Interaction\GhciTop.hs:646
```
Batch mode works fine, both with `agda aA.agda` and `agda aa.agda`.

Original issue reported on code.google.com by `josepedr...@gmail.com` on 3 Apr 2012 at 6:41

**Comment by andreasabel** [comment]
Commit: e46f6bf871db82ea20d4635ff3bd4f7c7686865e (unfortunately without regression test, which made #5508 possible).

I wonder why this was not an issue on macOS.  Maybe @UlfNorell had a case-sensitive FS or never tested this.
