### ISSUE TITLE
Bad error message when matching into unresolved sort with --cubical

### ISSUE THREAD

**Issue by plt-amy** [agda/agda#6001]
Related, but not identical to, #5816. This was accidentally stumbled upon by @tomdjong and minimized by @JakobBruenker; many thanks to both!

```agda
{-# OPTIONS --without-K #-}

data Foo {A : Set} : A → Set where
  con : (x : A) → Foo x

bug : ∀ {A : Set} {a : A} {p : Foo a} → ?
bug {p = con _} = {!!}
```

Type checking this explodes with

```
/home/amelia/default/Projects/etc/agda/test.agda:7,1-23
Panic: Pattern match failure in do expression at
src/full/Agda/TypeChecking/Primitive/Cubical.hs:2310:7-21
when checking the definition of bug
```

which is the call to `toLType` in `transpSys`. If we log the type that's being `toLType`'d, i.e.

```diff
@@ -2307,6 +2307,7 @@ transpSys ty sys phi u = do
   tComp <- fromMaybe __IMPOSSIBLE__ <$> getTerm' builtinComp
   l_ty <- bind "i" $ \ i -> do
       ty <- absApp <$> ty <*> i
+      reportSDoc "tc.transpsys" 20 $ "toLType" <+> prettyTCM ty
       Just (LEl l ty) <- toLType ty
       return (l,ty)
```

then we see that it's exploding after

```
transpSysTel'
delta  =
phi    = {- snip -}
args   = []
toLType Foo (@11 @0)
toLType Foo (@10 @0)
toLType Foo (@10 @0)
toLType ?0
```

**Comment by plt-amy** [comment]
Naïve solution idea (might be completely out of whack since I'm new to all this): @andreasabel can we block on any meta appearing in the type when `toLType` fails, to defer generating the trX-trX clause?

**Comment by andreasabel** [comment]
> to defer generating the trX-trX clause?

The question is, defer until _when_?  
You can defer the _production_ by having a new `Constraint` form that gets retried once the blocking metas are solved.  But you also need to block the _users_ of the trX-trX clauses.  Not sure what this means, but maybe this means you need to block the checking of the whole `bug` function above, does it?

**Comment by andreasabel** [comment]
The current error is:
```
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/EtaContract.hs:46:17 
```
https://github.com/agda/agda/blob/26c11b629cd60bc135ca87697cbf01ee03f094c6/src/full/Agda/TypeChecking/EtaContract.hs#L46
The new error is due to @jespercockx 's commit 0a75063e5f267486df45110adcd7767eec4bf557 which I think I will ~~promptly revert~~ revise: Bail out with a hard error (rather than casting the DUMMY bomb).

**Comment by plt-amy** [comment]
Bumping to 2.6.4; Since #6153 this doesn't panic anymore.

**Comment by andreasabel** [comment]
With `--cubical-compatible`, we now get the error:
```
Cubical Agda: cannot generate hcomp clauses at type ?0
when checking the definition of bug
```
Just `--without-K` we get unsolved metas.

I'd say this issue can be closed.  I opened a PR that adds the OP as test:
- #6230
