### ISSUE TITLE
Panic: Pattern match failure with Setω and --without-K

### ISSUE THREAD

**Issue by flupe** [agda/agda#6005]
There seem to be a regression in the current master of Agda.

The following code (where we define the equality type at Setω)

```agda
{-# OPTIONS --without-K #-}

open import Agda.Builtin.Equality
open import Agda.Primitive using (Setω)

data _≡ω_ {A : Setω} (x : A) : A → Setω where
  refl : x ≡ω x

congω : {A : Set} {B : Setω} (f : A → B)
      → ∀ {x y} → x ≡ y → f x ≡ω f y
congω f refl = refl
```

fails with the following message:

```
cong.agda:11,1-20
Panic: Pattern match failure in do expression at
src/full/Agda/TypeChecking/Primitive/Cubical.hs:2310:7-21
when checking the definition of congω
```

Can confirm this typechecks fine with the latest release (`2.6.2.2`) and with `--with-K`.

**Comment by flupe** [comment]
Just noticed the code fails at the same place as #6001. I also logged the types passed to `toLType`, giving:

```
toLType @14 ≡ @11 @0
toLType @14 ≡ @11 @0
toLType @13 ≡ @10 @0
toLType @13 ≡ @10 @0
toLType @11 @10 ≡ω @11 @9
```

As expected, the code fails because `toLType` does not handle things that live in `Setω`, just as for `Prop` (See #5816 and the fix #5897). I tried checking the example with the fix from #5897 and it no longer fails, so we can consider this issue to also be fixed by #5897.

**Comment by andreasabel** [comment]
Current error (after #5730 has been improved) is more benign:
```
Cannot generate inferred clause for congω. Case to handle:
  congω f
    (Agda.Primitive.Cubical.primHComp {.Agda.Primitive.lzero}
       {.(_ ≡ _)}
       {φ = φ}
       u
       a)
Cannot compose with type family: f x ≡ω f y.
when checking the definition of congω
```

**Comment by plt-amy** [comment]
Part of #6049, still an internal error to be fixed

**Comment by stschaef** [comment]
@plt-amy 

The message of [`2b4be2c`](https://github.com/agda/agda/commit/2b4be2cc1fff03adf1dfac04cea83f7ce940a86f) reads

> Closes https://github.com/agda/agda/issues/5816 and closes https://github.com/agda/agda/issues/6005: since cubical stuff is not generated when
just --without-K is specified, the examples there no longer panic. (They
don't panic with --cubical anymore either, but that's slightly beside
the point)

When compiling with Agda `2.8.0` the code

```
open import Agda.Builtin.Equality
open import Agda.Primitive using (Setω)

data _≡ω_ {A : Setω} (x : A) : A → Setω where
  refl : x ≡ω x

congω : {A : Set} {B : Setω} (f : A → B)
      → ∀ {x y} → x ≡ y → f x ≡ω f y
congω f refl = refl
```

gives the following error

```
error: [CannotGenerateHCompClause]
Cannot generate hcomp clause at type @7 @6 ≡ω @7 @5
when checking the definition of congω
```

when compiled with `--cubical` or `--cubical-compatible`. You mention that the previous commit fixing panics with `--cubical` was beside the point, so I'm not sure if this is actually a regression or if this is to be expected
