### ISSUE TITLE
Surprising semantics of `module` keyword in `using`/`renaming`/`hiding` clause

### ISSUE THREAD

**Issue by anuyts** [agda/agda#6037]
The [documentation](https://agda.readthedocs.io/en/v2.6.2.2/language/module-system.html#name-modifiers) states:

> To refer to a module M inside A you write module M. For instance,
> ```agda
> open A using (module M)
> ```

However if `M` is both the name of a definition and a module, then it turns out that mentioning `M` in a `using`/`renaming`/`hiding` clause affects _both_ the definition _and_ the module, _unless_ `module M` is also mentioned in such a clause.
Then again, if `M` is _only_ a module, then mentioning `M` without the `module` keyword raises a warning and is otherwise ignored.

Since data and record types are both definitions and modules, I can see where this comes from, but in that case:
* it should be documented as such,
* the following code should not yield a warning:

```agda
module _ where

module A where
  module B where
    postulate C : Set

  postulate B : Set

open A hiding (B) using (module B)

C' : Set
C' = B.C

B' : Set
B' = {!B!}
```

Perhaps, though, it would be more principled to let `M` only affect the definition and perhaps to allow `data M`/`record M` to affect both in the case of a data/record type.

There are too many combinations of clauses to be considered for it to be very useful that I provide code examples for everything, but I've been fiddling around with the above code and have been surprised several times.

**Comment by andreasabel** [comment]
The warning is:
```
Ignoring names in `hiding' directive: B
when scope checking the declaration
  open A using (module B) hiding (B)
```
Yeah, that's bogus.

**Comment by andreasabel** [comment]
> ```
> Ignoring names in `hiding' directive: B
> when scope checking the declaration
>   open A using (module B) hiding (B)
> ```
> 
> Yeah, that's bogus.

Actually no.  Since `using (module B)` restricts the import to just the `module B`, asking also for `hiding (B)` is pointless.  The user is confused about what they want, and should be alerted to this fact.

@anuyts: To make clear what you are actually missing/want, please submit a documentation PR.
