### ISSUE TITLE
Document the meaning of `pattern` without `no-eta-equality`

### ISSUE THREAD

**Issue by JasonGross** [agda/agda#6066]
The documentation at https://agda.readthedocs.io/en/v2.6.2.2/language/record-types.html?highlight=pattern#recursive-records says:
> However, inductive records without η-equality do not support both matching on the record constructor and construction of record elements by copattern matching. It has been discovered that the combination of both leads to loss of subject reduction, i.e., reduction does not preserve typing. For records without η, matching on the record constructor is off by default and construction by copattern matching is on. If you want the converse, you can add the record directive `pattern`:

As far as I can tell, the documentation does not specify what `pattern` does when either (or both) of the directives `inductive`, `no-eta-equality` are absent, despite the fact that Agda accepts it.  I expect this is a no-op (is it?), but I think in any case the behavior should be documented.

**Comment by nad** [comment]
Perhaps Agda could warn about certain combinations.

**Comment by andreasabel** [comment]
If you explicitly declare `eta-equality`, you get a warning for `pattern`:
```agda
record D : Set1 where
  eta-equality; pattern; constructor d
  field
    foo : Set
```
```
`pattern' attribute ignored for eta record
```
However, if eta is inferred for the record, you do not get this warning:
```agda
record D : Set1 where
  pattern; constructor d
  field
    foo : Set

match : D → Set
match (d A) = A

comatch : Set → D
comatch A .D.foo = A
```
I suppose we could throw this warning also in the type-checker, after inferring eta-equality for a record type.

**Comment by andreasabel** [comment]
The warning can be thrown when we turn on eta for a record after positivity checking:
https://github.com/agda/agda/blob/7183739a67afa5896e5d79a26023198595147727/src/full/Agda/TypeChecking/Records.hs#L464-L475
https://github.com/agda/agda/blob/7183739a67afa5896e5d79a26023198595147727/src/full/Agda/TypeChecking/Records.hs#L477-L486
If my eyes do not deceive me, these two functions do exactly the same!?

They used to be different until e7240e844e0d670eb471f983fd26922cdb4af3d0.

**Comment by andreasabel** [comment]
Ok, there are cases when `pattern` is needed for records that are later recognized as eta-worthy:
https://github.com/agda/agda/blob/7183739a67afa5896e5d79a26023198595147727/test/Succeed/Issue2308.agda#L13-L20
This record is classified by Agda as non-recursive.
So we have to keep track of whether `pattern` has been put to use.

**Comment by andreasabel** [comment]
I am in the process (#6154) of making Agda warn of a redundant `pattern` directive even when eta for a record is not declared, but inferred.  In the case of `Issue2308.agda` (see above), it is not redundant since eta is inferred to late.

@JasonGross @nad @jespercockx @gallais @UlfNorell : Would you want Agda to recommend to replace `pattern` by `eta-equality` in cases like `Issue2308.agda` where eta is inferred, but too late to enable the match in `G`?  The directive `pattern` correctly enables pattern matching on the record in the mutual block, but it might also wrongly suggest to the reader that copattern matching isn't available for `R`---yet which is, _after_ the mutual block when eta has been established.

**Comment by nad** [comment]
I think that the user should declare whether η-equality should hold or not (via the absence or presence of a keyword), I don't think this property should be inferred by Agda.

**Comment by jespercockx** [comment]
"Inferred" is perhaps a strong word here, but I would be fine with there being a simple syntactic rule for when a record has eta-equality. For example, a record has eta-equality unless it has any of the keywords `inductive`, `coinductive`, `pattern`, or `no-eta-equality`. This is the nicest solution that I can think of that does not break basically all existing Agda code. (If I did not care about breaking existing code at all, I would propose making `no-eta-equality` the default and only enabling eta when the user requests it explicitly with the `eta-equality` keyword).

**Comment by andreasabel** [comment]
@nad and @jespercockx : Thanks for your opinions. I agree that it would be clearer if eta was not inferred, but declared.  I second Jesper's proposal, with some modification:
- _no directive_ and [`inductive` default to `eta-equality`](https://agda--6160.org.readthedocs.build/en/6160/language/record-types.html#recursive-records)
- `coinductive` and `pattern` default to `no-eta-equality`
- option `--(no-)eta-equality` is removed  (this might break some code but it is easily fixable)
- if `eta-equality` is not given explicitly but inferred unsafe by the positivity checker, it is switched off with a warning; if it was given explicitly then it is kept with a similar warning unless `--safe`; with `--safe`, an error is raised
- the pragmas `ETA` (unsafe) and `NOETA` are removed

The ETA pragma was kept to allow unsafe eta equality without warning (unless `--safe`).  However, one can also suppress the warning by the usual warning mechanism.

**Comment by nad** [comment]
I don't think we should treat things as unsafe only because the type-checker might fail to terminate.

**Comment by andreasabel** [comment]
> I don't think we should treat things as unsafe only because the type-checker might fail to terminate.

If I understand Anton @csetzer correctly, eta for coinductive records also breaks subject reduction: https://www.cs.swan.ac.uk/~csetzer/articles/CMCS2018/bergerSetzerProceedingsCMCS18.pdf
