### ISSUE TITLE
Elaborate-and-give does not respect `--postfix-projections`

### ISSUE THREAD

**Issue by plt-amy** [agda/agda#6082]
```agda
{-# OPTIONS --postfix-projections #-}
module asdf where

open import Agda.Primitive
open import Agda.Builtin.Reflection
open import Agda.Builtin.Sigma
open import Agda.Builtin.Unit
open import Agda.Builtin.List

module _ {A : Set} {B : A → Set} (x : Σ A B) where
  ai : ArgInfo
  ai = arg-info visible (modality relevant quantity-ω)
  macro
    foo : Term → TC ⊤
    foo goal = unify goal (def (quote fst) (arg ai (var 0 []) ∷ []))

  _ : A
  _ = {! foo  !}
```

Elaborate-and-giving that interaction point should probably expand to `x .fst` rather than `fst x`, since the user asked for `--postfix-projections`.

**Comment by andreasabel** [comment]
I identified the source of the problem: the translation `ReflectedToAbstract` does not recover projections: https://github.com/agda/agda/blob/82b2b0fbea55c1716685d72cd8546b533d0f12dc/src/full/Agda/Syntax/Translation/ReflectedToAbstract.hs#L205-L209
It only distinguishes `A.Macro` from `A.Def`, not `A.Proj` and `A.Con`. Fixing this fixes this issue.
