### ISSUE TITLE
Better time profiles

### ISSUE THREAD

**Issue by nad** [agda/agda#6090]
If we use time profiling, then a large part of the time is attributed to bind, which is not very helpful. I found a blog post that seems to explain what is going on: [Locating Performance Bottlenecks in Large Haskell codebases](https://www.tweag.io/blog/2020-01-30-haskell-profiling/) by Juan Raphael Diaz Simões. Apparently bindings annotated with cost centres are never inlined, and when `-fprof-auto` is used every binding without an `INLINE` pragma gets annotated with a cost centre. The blog post includes an example in which a large part of the cost gets attributed to bind.

We use `-fprof-auto`:

https://github.com/agda/agda/blob/4e6428395398907a722e0563d2813d7eaeb32248/Agda.cabal#L778

The blog post suggests an approach which I interpreted as "add cost centres manually to definitions which do not need to be inlined, starting from the top". That might be a good idea, but would require some work.

Instead I tried to use [`-fprof-late`](https://downloads.haskell.org/ghc/9.4.2/docs/users_guide/profiling.html#ghc-flag--fprof-late), which is supposed to interfere less with optimisations. This flag is available from GHC 9.4.1. I compiled Agda using this flag (and `-foptimise-heavily`), and type-checked the standard library with `+RTS -p`. Here is an excerpt of the resulting time profile (`agda.prof`):
```
COST CENTRE              MODULE                           SRC                                                         %time %alloc

ifM                      Agda.Utils.Monad                 src/full/Agda/Utils/Monad.hs:48:1-44                         13.0    0.1
maybeM                   Agda.Utils.Maybe                 src/full/Agda/Utils/Maybe.hs:77:1-32                          4.7    0.1
lookup                   Agda.Utils.HashTable             src/full/Agda/Utils/HashTable.hs:50:1-33                      3.8    2.7
canonicalizeAbsolutePath Agda.Utils.FileName              src/full/Agda/Utils/FileName.hs:(90,1)-(91,63)                3.1   10.1
!                        Data.Vector.Hashtables.Internal  src/Data/Vector/Hashtables/Internal.hs:121:1-21               2.5    8.8
applySubstTerm           Agda.TypeChecking.Substitute     src/full/Agda/TypeChecking/Substitute.hs:(823,1)-(842,55)     1.9    3.6
$w$wgo7                  Agda.TypeChecking.Serialise.Base <no location info>                                            1.2    1.6
hasVerbosity             Agda.TypeChecking.Monad.Debug    src/full/Agda/TypeChecking/Monad/Debug.hs:(302,1)-(307,19)    1.0    1.1
$fInstantiateFull(,)1    Agda.TypeChecking.Reduce         <no location info>                                            0.7    1.1
wordsBy                  Agda.Utils.List                  src/full/Agda/Utils/List.hs:(481,1)-(488,36)                  0.6    1.9
insert                   Agda.Utils.HashTable             src/full/Agda/Utils/HashTable.hs:45:1-33                      0.6    1.1
lookupPath               Agda.Utils.Trie                  src/full/Agda/Utils/Trie.hs:(145,1)-(148,56)                  0.5    1.2
setFreeVariablesArgInfo  Agda.Syntax.Common               src/full/Agda/Syntax/Common.hs:1777:1-55                      0.4    1.2
getDefinedNames          Agda.Syntax.Concrete.Operators   src/full/Agda/Syntax/Concrete/Operators.hs:90:1-15            0.4    1.2
mergeNotations_go1       Agda.Syntax.Notation             <no location info>                                            0.3    1.1
```
Some things to note:
* Bind is not present in the list.
* We should perhaps mark small functions like `ifM`, `maybeM` and `lookup` as [`INLINABLE`](https://downloads.haskell.org/ghc/9.4.2/docs/users_guide/exts/pragmas.html#inlinable-pragma), so that they can be inlined or specialised in other modules.
* According to this profile about 10% of the allocations are performed by `canonicalizeAbsolutePath`:
  https://github.com/agda/agda/blob/4e6428395398907a722e0563d2813d7eaeb32248/src/full/Agda/Utils/FileName.hs#L89-L91
  Converting from `Text` to `String` and back many times (see #5673) is perhaps not a good idea.
* ~~Similarly a bit less than 10% of the allocations are, according to this profile, performed by the *lookup* function (not insertion) for hashtables. I wonder why. Lots of collisions? Is the implementation of hash tables [not sufficiently strict](https://github.com/klapaucius/vector-hashtables/blob/7dc17e11a2faddcf7e55e07ff84be081cba6c33f/src/Data/Vector/Hashtables/Internal.hs#L69-L76)?~~

I also tried to use `+RTS -p -l-au`, in order to be able to use [hs-speedscope](https://mpickering.github.io/posts/2019-11-07-hs-speedscope.html) and [speedscope.app](https://www.speedscope.app/), but whenever I've used `-p -l-au` together with Agda compiled with `-fprof-late` I have encountered errors like the following one:
```
double free or corruption (out)
Aborted (core dumped)
```

A disadvantage of `-fprof-late` is that ["if a function is inlined into a use site it’s costs will be counted against the caller’s cost center"](https://downloads.haskell.org/ghc/9.4.2/docs/users_guide/profiling.html#ghc-flag--fprof-late). I still think we should remove `-fprof-auto` from the Cabal file, and enable `-fprof-late` for GHC 9.4.1 and later. Are there any objections to this?

**Comment by asr** [comment]
> I still think we should remove `-fprof-auto` from the Cabal file, and enable `-fprof-late` for GHC 9.4.1 and later. Are there any objections to this?

I think these kind of options (and the warnings too) only should be enable from the last point release of major versions, that is GHC 9.4.2. We should encourage the use of the last point releases.

**Comment by nad** [comment]
If someone wants to use GHC 9.4.1, why should we make things more difficult for that person? And do you think we should edit the Cabal file if GHC 9.4.3 is released? I don't want to create more work for us.

**Comment by asr** [comment]
> And do you think we should edit the Cabal file if GHC 9.4.3 is released?

Yes.

> I don't want to create more work for us.

In this particular case, GHC 9.4.2 fixed some import issues in relation to GHC 9.4.1, and we only use the last point release versions in CI. So, by "supporting" only these versions we get less work for us.

**Comment by nad** [comment]
> So, by "supporting" only these versions we get less work for us.

We do not support anything that is not listed under `tested-with`. However, we do not actively prevent Agda from building under GHC 9.4.1. Furthermore the important issues that you mention might only affect certain platforms. Someone who uses a different platform might choose not to upgrade, and I don't think we should actively make things harder for such a person.

**Comment by nad** [comment]
> * Similarly a bit less than 10% of the allocations are, according to this profile, performed by the _lookup_ function (not insertion) for hashtables. I wonder why. Lots of collisions? Is the implementation of hash tables [not sufficiently strict](https://github.com/klapaucius/vector-hashtables/blob/7dc17e11a2faddcf7e55e07ff84be081cba6c33f/src/Data/Vector/Hashtables/Internal.hs#L69-L76)?

I thought that `(Data.Vector.Hashtables.Internal.!)` was a lookup function for hash tables, but [the function](https://hackage.haskell.org/package/vector-hashtables-0.1.1.1/docs/src/Data.Vector.Hashtables.Internal.html#%21) just calls [`readPrimArray`](https://hackage.haskell.org/package/primitive-0.7.4.0/docs/Data-Primitive-PrimArray.html#v:readPrimArray), and it is used to read from mutable unboxed arrays containing `Int`s. Do the numbers correspond to allocation of the `I#` constructor of the `Int` type? I checked the Core generated for `vector-hashtables`, and it looks as if there is some unnecessary boxing in there.

As an aside I noticed that [a key data type](https://hackage.haskell.org/package/vector-hashtables-0.1.1.1/docs/Data-Vector-Hashtables-Internal.html#t:Dictionary_) used by the hash table implementation does not use strict fields. However, I recompiled the library with strict fields, and obtained a profile similar to the previous one (the allocation percentages went up for `lookup` and `insert`):
```
COST CENTRE              MODULE                           SRC                                                         %time %alloc

ifM                      Agda.Utils.Monad                 src/full/Agda/Utils/Monad.hs:48:1-44                         12.0    0.1
maybeM                   Agda.Utils.Maybe                 src/full/Agda/Utils/Maybe.hs:77:1-32                          4.7    0.1
lookup                   Agda.Utils.HashTable             src/full/Agda/Utils/HashTable.hs:50:1-33                      3.9    4.6
canonicalizeAbsolutePath Agda.Utils.FileName              src/full/Agda/Utils/FileName.hs:(90,1)-(91,63)                3.1    9.8
!                        Data.Vector.Hashtables.Internal  src/Data/Vector/Hashtables/Internal.hs:121:1-21               2.7    8.6
applySubstTerm           Agda.TypeChecking.Substitute     src/full/Agda/TypeChecking/Substitute.hs:(823,1)-(842,55)     1.9    3.5
$w$wgo7                  Agda.TypeChecking.Serialise.Base <no location info>                                            1.2    1.6
hasVerbosity             Agda.TypeChecking.Monad.Debug    src/full/Agda/TypeChecking/Monad/Debug.hs:(302,1)-(307,19)    1.0    1.1
$fInstantiateFull(,)1    Agda.TypeChecking.Reduce         <no location info>                                            0.7    1.1
insert                   Agda.Utils.HashTable             src/full/Agda/Utils/HashTable.hs:45:1-33                      0.7    1.7
wordsBy                  Agda.Utils.List                  src/full/Agda/Utils/List.hs:(481,1)-(488,36)                  0.6    1.9
lookupPath               Agda.Utils.Trie                  src/full/Agda/Utils/Trie.hs:(145,1)-(148,56)                  0.5    1.1
setFreeVariablesArgInfo  Agda.Syntax.Common               src/full/Agda/Syntax/Common.hs:1777:1-55                      0.4    1.2
getDefinedNames          Agda.Syntax.Concrete.Operators   src/full/Agda/Syntax/Concrete/Operators.hs:90:1-15            0.4    1.1
mergeNotations_go1       Agda.Syntax.Notation             <no location info>                                            0.3    1.1
```

**Comment by nad** [comment]
> I checked the Core generated for `vector-hashtables`, and it looks as if there is some unnecessary boxing in there.

However, now I checked the Core code that is generated for `Agda.Utils.HashTable`. After specialisation much of the boxing seems to be gone, and I could not find any trace of `(Data.Vector.Hashtables.Internal.!)`.

**Comment by nad** [comment]
> I still think we should remove `-fprof-auto` from the Cabal file, and enable `-fprof-late` for GHC 9.4.1 and later.

A better alternative is perhaps to remove `-fprof-auto` from the Cabal file, without adding anything else. Then any profiling users are free to choose how the program/library should be profiled. We can instead add `-fprof-late` to the makefile.

**Comment by nad** [comment]
I compiled Agda (a different commit) using `--library-profiling-detail=none  --profiling-detail=none --ghc-options=-fprof-late` and obtained the following profile for the standard library:
```
COST CENTRE                        MODULE                           SRC                                                   %time %alloc

$s$wlookup2                        Agda.TypeChecking.Serialise.Base <no location info>                                      6.0    2.8
canonicalizeAbsolutePath1          Agda.Utils.FileName              <no location info>                                      5.9   11.6
!                                  Data.Vector.Hashtables.Internal  src/Data/Vector/Hashtables/Internal.hs:121:1-21         4.6   10.1
levelMax_$sapplySubstTerm          Agda.TypeChecking.Substitute     src/full/Agda/TypeChecking/Substitute.hs:803:1-14       3.1    4.8
$w$wgo7                            Agda.TypeChecking.Serialise.Base <no location info>                                      2.2    1.9
$fOrdModuleName_$ccompare          Agda.Syntax.Abstract.Name        src/full/Agda/Syntax/Abstract/Name.hs:294:3-9           1.5    0.0
hashWithSalt1                      Data.Hashable.Class              src/Data/Hashable/Class.hs:339:1-45                     1.5    0.7
$wpoly_go10                        Agda.TypeChecking.Monad.Context  <no location info>                                      1.2    0.0
$fInstantiateFull(,)1              Agda.TypeChecking.Reduce         <no location info>                                      1.2    1.3
$fMonadAddContextTCMT_$scheckpoint Agda.TypeChecking.Monad.Context  src/full/Agda/TypeChecking/Monad/Context.hs:99:1-10     1.1    2.5
$s$winsert2                        Agda.TypeChecking.Serialise.Base <no location info>                                      1.0    1.1
withShadowingNameTCM               Agda.TypeChecking.Monad.Context  src/full/Agda/TypeChecking/Monad/Context.hs:220:1-20    0.9    2.1
wordsBy                            Agda.Utils.List                  src/full/Agda/Utils/List.hs:480:1-7                     0.9    2.0
$w$cupdateContext                  Agda.TypeChecking.Reduce.Monad   <no location info>                                      0.7    1.3
getDefinedNames                    Agda.Syntax.Concrete.Operators   src/full/Agda/Syntax/Concrete/Operators.hs:90:1-15      0.6    1.4
$wencode                           Agda.TypeChecking.Serialise      <no location info>                                      0.6    1.1
$wtoBoolListZipWith                Agda.Utils.SmallSet              src/full/Agda/Utils/SmallSet.hs:148:1-17                0.4    1.0
hashInt                            Data.Hashable.LowLevel           src/Data/Hashable/LowLevel.hs:65:1-41                   0.4    1.1
mergeNotations_go1                 Agda.Syntax.Notation             <no location info>                                      0.4    1.2
$fBinaryListLike39                 Agda.TypeChecking.Serialise      <no location info>                                      0.3    1.1
```
I don't know why the profiles are so different, perhaps I didn't use `-foptimise-heavily` for the previous profile, even though I thought I did. Note that names from other packages are included, despite the use of `--library-profiling-detail=none`. I noted that already installed packages were not recompiled when I started using that option.

Inspection of the generated Core for `Agda.TypeChecking.Serialise.Base` suggests that `$s$wlookup2`, which is at the top of the list above, is a specialised variant of the hash table lookup function for `Double`:
```haskell
$s$wlookup2
  = \ @v ww k1 s ->
      case (readMutVar#
              ww (s `cast` <Co:3> :: State# RealWorld ~R# State# (PrimState IO)))
           `cast` <Co:12> :: (# State# (PrimState IO),
                                Dictionary_ (PrimState IO) MVector Double MVector v #)
                             ~R# (# State# RealWorld,
                                    Dictionary_ (PrimState IO) MVector Double MVector v #)
      of
      { (# ipv, ipv1 #) ->
      case ipv1 of { Dictionary ds2 ds3 ds4 ds5 ds6 ds7 ->
      case ds4 of { MutablePrimArray arr# ->
      case k1 of { D# ww1 ->
```
Note the presence of `D#`. This function is called from `$wicodeDouble`:
```haskell
$wicodeDouble
  = \ key ww ww1 eta ->
      case $s$wlookup2 ww key eta of { (# ipv, ipv1 #) ->
```
I suspect that the profile should be interpreted differently, I doubt that about 6% (not including time allocated to functions called by `$s$wlookup2`) of the time required to type-check the standard library is spent on looking up entries in a hash table with `Double` keys. Perhaps the generated names in the profile do not match those in the Core file. I failed to find `$w$wgo7` (or any definition starting with `$w$w`) in the core file for `Agda.TypeChecking.Serialise.Base`.

Now I also managed to create an event log. Here is one view created by [hs-speedscope](https://mpickering.github.io/posts/2019-11-07-hs-speedscope.html) and [speedscope.app](https://www.speedscope.app/) for an event log obtained by type-checking `Data.Nat` (using `+RTS -p -l-au`):
![Left heavy view](https://user-images.githubusercontent.com/293222/188969744-500dfe9a-2e39-4623-af02-83401a2458ee.png)
Here is a different view:
![Sandwich view](https://user-images.githubusercontent.com/293222/188970453-a35a6817-1c51-424d-9adb-4c5230f3e756.png)
It appears as if most of the time spent on canonicalising paths is spent in the serialiser. I did not know that the serialiser did that kind of thing:
https://github.com/agda/agda/blob/20e0d1dbf7fd1d5e8051219e52967398392242b9/src/full/Agda/TypeChecking/Serialise/Instances/Common.hs#L197-L214
The profile suggests that a substantial amount of time (perhaps 3%) is spent on the following call to `Map.difference`:
https://github.com/agda/agda/blob/20e0d1dbf7fd1d5e8051219e52967398392242b9/src/full/Agda/TypeChecking/Monad/Context.hs#L128
Things could perhaps be sped up if module names had unique identifiers instead of being lists of things with unique identifiers (about 1% of the time seems to be spent on comparing module names).
