### ISSUE TITLE
Different NaN on M1 mac

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#6093]
On `x86_64`:
```
GHCi, version 9.0.2: https://www.haskell.org/ghc/  :? for help
λ import GHC.Float
λ import Text.Printf
λ printf "%x\n" $ castDoubleToWord64 (0.0 / 0.0)
fff8000000000000
```
On `M1`:
```
GHCi, version 9.0.2: https://www.haskell.org/ghc/  :? for help
λ import GHC.Float
λ import Text.Printf
λ printf "%x\n" $ castDoubleToWord64 (0.0 / 0.0)
7ff8000000000000
```
That top bit is the sign bit (https://en.wikipedia.org/wiki/NaN#Floating_point) and `negate` flips it on either architecture. The tests for #4868 fails due to this discrepancy and to my mind it looks like the M1 is doing the "right" thing in returning a positive NaN for `0.0 / 0.0`.

The simplest fix would be more opinionated here:
https://github.com/agda/agda/blob/20e0d1dbf7fd1d5e8051219e52967398392242b9/src/full/Agda/Utils/Float.hs#L195-L196
and here:
https://github.com/agda/agda/blob/20e0d1dbf7fd1d5e8051219e52967398392242b9/src/data/MAlonzo/src/MAlonzo/RTE/Float.hs#L148-L149
and change it to
```haskell
nan = castWord64ToDouble 0x7ff8000000000000
```
(or possibly `0xfff8000000000000` if we want to keep the x86_64 behaviour)

Thoughts? @wenkokke @andreasabel

**Comment by wenkokke** [comment]
~~I'm in favour of picking an exact bit pattern.~~

**Comment by wenkokke** [comment]
Actually, no, I'm very against that. What test breaks? Anything that gives access to the bit pattern for a NaN should be removed from the builtins, and replaced with something that returns a maybe.

**Comment by wenkokke** [comment]
If we distinguish between `+NaN` and `-NaN`, then we should check whether `0.0 / 0.0` is positive or negative when assigning `nan`, and negate it if it's negative.

**Comment by UlfNorell** [comment]
This is the test that breaks:
https://github.com/agda/agda/blob/20e0d1dbf7fd1d5e8051219e52967398392242b9/test/Succeed/Issue4868.agda#L201-L202

What's the right way to check the sign of a NaN?

**Comment by wenkokke** [comment]
I think `toWord NaN` should return `nothing` rather than the underlying state. I don't think we should ever give the user access to the underlying state of a NaN, because it's platform dependent, and hence this test will never succeed consistencly.

**Comment by wenkokke** [comment]
I'd recommend against setting a specific bit pattern. It might work, but some platforms may be peculiar about what they see as (which kind of) nans, so it may result in some unexpected behaviour.

I'd rather see us enforce the contract that if a float is nan, you can never see its bit pattern.

**Comment by andreasabel** [comment]
@UlfNorell @wenkokke : Do you want to submit a PR soon?  That would help getting 2.6.3 out of the door.  Or shall this be bumped to 2.6.4?

**Comment by UlfNorell** [comment]
I will try to get it done this week.
