### ISSUE TITLE
Should n be size tel?

### ISSUE THREAD

**Issue by nad** [agda/agda#6096]
Consider what happens if the size of `tel` is less than `n` in the following code (I have verified that this can happen, see for instance `test/Succeed/Issue723.agda`):
https://github.com/agda/agda/blob/27ea7f2207c25d6f68387c264aaed9ffc1a733e8/src/full/Agda/TypeChecking/Rules/Application.hs#L653-L696
If the size of the telescope is less than `n`, doesn't it make sense to use `size tel` instead of `n` in `dep`?

**Comment by UlfNorell** [comment]
Yes, that looks like it should be `size tel` instead of `n`.

**Comment by nad** [comment]
The test suite does not complain.

**Comment by andreasabel** [comment]
(This issue does not have a reproducer, so we don't list it in the changelog.)
