### ISSUE TITLE
Irrelevance bug to prove false

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#610]
When we were fooling around with irrelevance in #agda today, James Deikun found 
that if you name your where modules in irrelevant contexts, you can make that 
which is irrelevant relevant again, with some other trickery:

``` agda
module RelevanceBug where

open import Level
open import Relation.Binary.PropositionalEquality

open import Data.Empty
open import Data.Unit

record A : Set₁ where
  constructor set
  field
    .a : Set

.get : A → Set
get x = helper x
  module R where
  helper : .A -> Set
  helper x = A.a x

ack : A → Set
ack x = R.helper x x

hah : set ⊤ ≡ set ⊥
hah = refl

.moo : ⊥
moo with cong ack hah
moo | q = subst (λ x → x) q _

baa : .⊥ → ⊥
baa ()

yoink : ⊥
yoink = baa moo
```

An odd aspect to this hack is that `cong ack hah` does not have type `⊤ ≡ ⊥`, 
but rather has type `.(⊤) ≡ .(⊥)` which is actually considered distinct and 
won't unify. Luckily, in the irrelevant moo function above, `.(⊤) ≡ .(⊥)`
magically turns into `⊤ ≡ ⊥` again, and we can do great evil again.

Original issue reported on code.google.com by `pumpkingod@gmail.com` on 16 Apr 2012 at 9:17

**Comment by Saizan** [comment]
Sometimes they come back:

``` agda
open import Data.Unit
open import Data.Empty
open import Relation.Binary.PropositionalEquality

data A : Set₁ where
  set : .Set -> A

module M .(x : Set) where

  .out : Set
  out = x

.ack : A → Set
ack (set x) = M.out x

hah : set ⊤ ≡ set ⊥
hah = refl

.moo : ⊥
moo with cong ack hah
moo | q = subst (λ x → x) q _

baa : .⊥ → ⊥
baa ()

yoink : ⊥
yoink = baa moo
```

**Comment by jespercockx** [comment]
I guess we'll have to reset the counter again. Note that this time, it isn't necessary to use `with`:

```agda
.moo : ⊥
moo = subst (λ x → x) (cong ack hah) tt
```

Is the application `cong ack` supposed to typecheck?

**Comment by UlfNorell** [comment]
I suspect that the problem is `out`. Note that if you try

``` agda
.out : .(x : Set) → Set
out x = x
```

you get an error. Although I have to admit I'm not exactly sure what the rules are for irrelevant definitions.

**Comment by andreasabel** [comment]
I'm not either.  But it feels like the bodies of irrelevant definitions have to be protected by a `DontCare` just as for irrelevant projections.  It fixes this issue.  The rationale is that adding a `DontCare` does no harm, as irrelevant terms are all equal in irrelevant context.  But the `DontCare` prevents us from tracelessly reducing away the constructor `set` whose argument is irrelevant.

**Comment by andreasabel** [comment]
Associated commits (2012): 
- f300ed77e00f5f6bf180320178bcbd7c657aa48b
```
Date:   Wed Apr 18 12:37:48 2012 +0000

    Declaration in irrelevant context (e.g. where modules) must be irrelevant as well.
    Fixes part of issue 610.
```
- 7c041573fe0ec0d4883fbb4b62146a60f5a2f351
```
Date:   Wed Apr 18 12:58:52 2012 +0000

    When checking a DontCare term, keep DontCare. (Fixes Issue 610-4).
```
