### ISSUE TITLE
Error with --erased-cubical: "Not usable at modality"

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#6114]
I am trying out `--erased-cubical` but I run into a problem with the following example:
```agda
{-# OPTIONS --erased-cubical #-}

data D (@0 A : Set) : Set where
  c : A → D A

```
The error message is the following:
```
A → D A is not usable at the required modality
when checking that the type A → D A of the constructor c fits in
the sort Set of the datatype.
```
I am not sure, but I think this type should be accepted. Even if the value of `A` is somehow needed by cubical stuff, with `--erased-cubical` all that stuff is itself erased so it should be fine to erase `A` as well. (cc @nad @plt-amy )

**Comment by plt-amy** [comment]
Can you import `--erased-cubical` modules from plain `--cubical` modules? Because if so, we can't skip the check: it would be possible for an importing module to use the Cubical Nonsense (In this case, I think, the projection functions for hcomp only) from your module in a non-erased context. But if this situation is impossible, then we can skip this:

https://github.com/agda/agda/blob/master/src/full/Agda/TypeChecking/Rules/Data.hs#L1735-L1737

**Comment by jespercockx** [comment]
No, you can import `--cubical` modules from `--erased-cubical` ones but not the converse. So I believe the check is only required with `--cubical`, not `--without-K` (that is, once https://github.com/agda/agda/issues/6049 is done). So this actually provides some additional motivation for #6049 (else we would need a separate `--erased-without-K` flag).

**Comment by nad** [comment]
The code in the OP should not be allowed, see issue #4784.

**Comment by nad** [comment]
> No, you can import `--cubical` modules from `--erased-cubical` ones but not the converse.

Yes you [can](https://github.com/agda/agda/blob/bc39cc25b5bb2c7ccbfbccc5eee530b017febbdf/doc/user-manual/language/cubical.lagda.rst#cubical-agda-with-erased-glue).

**Comment by jespercockx** [comment]
> The code in the OP should not be allowed, see issue https://github.com/agda/agda/issues/4784.

I've tried reading through that (very long) discussion but I am not sure I understand which part relates to the example I have here. Isn't it strange that the datatype is accepted if you either remove the `@0` or remove the `--erased-cubical`, but is rejected if you have both?

**Comment by jespercockx** [comment]
Here is another example that is rejected because of the `@0` but I do not understand why:
```agda
{-# OPTIONS --erased-cubical #-}

data D : Set₁ where
  c : ((@0 A : Set) → A) → D
```

**Comment by jespercockx** [comment]
My motivating example is trying to add `--erased-cubical` to the following file: https://github.com/agda/agda2hs/blob/master/lib/Haskell/Prim/Foldable.agda. The type `Foldable` looks basically like this:
```agda
record Foldable (t : Set → Set) : Set₁ where
  field
    foldMap : {@0 a b : Set} ⦃ Monoid b ⦄ → (a → b) → t a → b
```
and is rejected because of this restriction. If the restriction is essential, how could I work around it for this example? I'd like to use cubical agda to write some proofs about code using the Agda2Hs library.

**Comment by nad** [comment]
> I've tried reading through that (very long) discussion but I am not sure I understand which part relates to the example I have here.

The following code uses my library [equality](https://github.com/nad/equality):
```agda
{-# OPTIONS --erased-cubical --safe #-}

open import Equality.Path
open import Prelude hiding (swap)

-- Let us assume that D can be defined.

module _
  (D         : @0 Type → Type)
  (box       : {@0 A : Type} → A → D A)
  (unbox     : {@0 A : Type} → D A → A)
  (unbox-box : {A : Type} {x : A} → unbox (box x) ≡ x)
  where

open import Equality.Path.Univalence

import Bool equality-with-J as Bool
open import Equivalence equality-with-J as Eq using (_≃_)
open import Erased.Cubical equality-with-paths
open import Function-universe equality-with-J hiding (id; _∘_)
open import Univalence-axiom equality-with-J hiding (≃⇒≡)

private variable
  A B : Type

-- Using D we can define the following cast operation for erased
-- equalities.

cast-≡ : {@0 A B : Type} → @0 A ≡ B → A → B
cast-≡ {A = A} eq =
  unbox (subst (λ ([ X ]) → D (A → X)) (λ i → [ eq i ]) (box id))

-- If we also use erased univalence, then we can define a cast
-- operation for erased equivalences.

cast-≃ : {@0 A B : Type} → @0 A ≃ B → A → B
cast-≃ eq = cast-≡ (≃⇒≡ eq)

-- In erased contexts we can prove that cast-≃ eq is equal to the
-- forward direction of the equivalence eq.

@0 cast-≃-to : (eq : A ≃ B) → cast-≃ eq ≡ _≃_.to eq
cast-≃-to {A = A} eq =
  cast-≃ eq                                                            ≡⟨⟩
  unbox $ subst (λ ([ X ]) → D (A → X)) (λ i → [ ≃⇒≡ eq i ]) (box id)  ≡⟨ cong unbox $
                                                                          elim¹ (λ eq → subst (λ ([ X ]) → D (A → X)) eq (box id) ≡
                                                                                        box (subst (λ ([ X ]) → A → X) eq id))
                                                                                (
    subst (λ ([ X ]) → D (A → X)) (refl {x = [ A ]}) (box id)                    ≡⟨ subst-refl {x = [ A ]} (λ ([ X ]) → D (A → X)) _ ⟩
    box id                                                                       ≡⟨ cong box $ sym $ subst-refl {x = [ A ]} (λ ([ X ]) → A → X) _ ⟩∎
    box $ subst (λ ([ X ]) → A → X) (refl {x = [ A ]}) id                        ∎)
                                                                                (λ i → [ ≃⇒≡ eq i ]) ⟩
  unbox $ box $ subst (λ ([ X ]) → A → X) (λ i → [ ≃⇒≡ eq i ]) id      ≡⟨ unbox-box ⟩
  subst (λ ([ X ]) → A → X) (λ i → [ ≃⇒≡ eq i ]) id                    ≡⟨⟩
  subst (λ X → A → X) (≃⇒≡ eq) id                                      ≡⟨ (⟨ext⟩ λ x → subst-→ {x₁≡x₂ = ≃⇒≡ eq} {y = x} {f = id}) ⟩
  subst (λ X → X) (≃⇒≡ eq) ∘ subst (const A) (sym (≃⇒≡ eq))            ≡⟨ (⟨ext⟩ λ _ → cong (subst (λ X → X) (≃⇒≡ eq)) $
                                                                           subst-const (sym (≃⇒≡ eq))) ⟩
  subst (λ X → X) (≃⇒≡ eq)                                             ≡⟨ (⟨ext⟩ λ _ → subst-id-in-terms-of-≡⇒↝ equivalence {A≡B = ≃⇒≡ eq}) ⟩
  ≡⇒→ (≃⇒≡ eq)                                                         ≡⟨ cong _≃_.to $ _≃_.right-inverse-of (≡≃≃ univ) eq ⟩∎
  _≃_.to eq                                                            ∎

-- If we cast true using the identity equivalence for Bool, then the
-- result should be true.

should-be-true : Bool
should-be-true = cast-≃ Eq.id true

@0 is-true : should-be-true ≡ true
is-true = cong (_$ true) (cast-≃-to Eq.id)

-- If we instead cast true using the equivalence that swaps true and
-- false, then the result should be false.

swap : Bool ≃ Bool
swap = from-isomorphism Bool.swap

should-be-false : Bool
should-be-false = cast-≃ swap true

@0 is-false : should-be-false ≡ false
is-false = cong (_$ true) (cast-≃-to swap)

-- Note that cast-≃ only takes one argument that is not erased. After
-- erasure should-be-true and should-be-false are thus identical, but
-- these two expressions should evaluate to different booleans.
```

> Isn't it strange that the datatype is accepted if you either remove the `@0` or remove the `--erased-cubical`, but is rejected if you have both?

The type is not accepted if you use `--without-K`.

> The type `Foldable` looks basically like this:
> ```agda
> record Foldable (t : Set → Set) : Set₁ where
>   field
>     foldMap : {@0 a b : Set} ⦃ Monoid b ⦄ → (a → b) → t a → b
> ```

Where does `{@0 a b : Set}` come from? I did not see anything like that in the file.

> If the restriction is essential, how could I work around it for this example?

Could you remove `@0`? The `--erased-cubical` compiler erases all types, whether they are marked as erased or not.
