### ISSUE TITLE
Add `primXtoYInjective _ _ refl ≡ refl` lemmas

### ISSUE THREAD

**Issue by shiatsumat** [agda/agda#6118]
Agda's built-in library has a number of `primXtoYInjective` lemmas for functions for primitive types, such as the following.
```
primCharToNatInjective : ∀ a b → primCharToNat a ≡ primCharToNat b → a ≡ b
primStringToListInjective : ∀ a b → primStringToList a ≡ primStringToList b → a ≡ b
```

We can use these lemmas, especially for deriving decidable equalities over primitive types (e.g., [agda-stdlib's `≟` on `Char`](https://github.com/agda/agda-stdlib/blob/master/src/Data/Char/Properties.agda)).

However, under the `--without-K` flag, we can't prove that `primXtoYInjective _ _ refl` returns `refl`, which can be inconvenient, including when we use the derived decidable equalities.

So I'd like to propose adding to Agda's built-in library such `primXtoYInjective _ _ refl ≡ refl` lemmas, like:
```
primCharToNatInjective-refl : ∀ a → primCharToNatInjective a a refl ≡ refl
primStringToListInjective-refl : ∀ a → primStringToListInjective a a refl ≡ refl
```

**Comment by shiatsumat** [comment]
I believe this is safe because we can generally prove that `eq : x ≡ y` equals `refl` (roughly speaking) when we know the full construction of `eq`.

For a decidable equality `≟`, we often want to use the property that `(a ≟ a) ≡ yes refl`.
And when `≟` is derived from a primitive injection `primXtoY` (i.e., `a ≟ b` on `X` is derived from `primXtoY a ≟' primXtoY b` on `Y`), we need `primXtoYInjective _ _ refl ≡ refl` to prove `(a ≟ a) ≡ yes refl`.

P.S.
We also have one example of `primXfromYInjective`, `primStringFromListInjective`, and we can also add `primStringFromListInjective-refl`.

**Comment by gallais** [comment]
This is already provable using Hedberg's theorem

```agda
{-# OPTIONS --safe --without-K #-}

open import Agda.Builtin.Char.Properties
open import Data.Char as Char
open import Agda.Builtin.String.Properties
open import Data.String as String
open import Relation.Binary.PropositionalEquality

open import Axiom.UniquenessOfIdentityProofs

primCharToNatInjective-refl : ∀ a → primCharToNatInjective a a refl ≡ refl
primCharToNatInjective-refl a = Decidable⇒UIP.≡-irrelevant Char._≟_ _ _

primStringToListInjective-refl : ∀ a → primStringToListInjective a a refl ≡ refl
primStringToListInjective-refl a = Decidable⇒UIP.≡-irrelevant String._≟_ _ _
```

>  For a decidable equality ≟, we often want to use the property that (a ≟ a) ≡ yes refl.

The stdlib has [generic proofs of these results](http://agda.github.io/agda-stdlib/Relation.Binary.PropositionalEquality.html#4201):

```agda       
  ≡-≟-identity : (eq : x ≡ y) → x ≟ y ≡ yes eq
  ≡-≟-identity eq = dec-yes-irr (x ≟ y) (Decidable⇒UIP.≡-irrelevant _≟_) eq
                                                               
  ≢-≟-identity : (x≢y : x ≢ y) → x ≟ y ≡ no x≢y
  ≢-≟-identity = dec-no (x ≟ y)
```

**Comment by shiatsumat** [comment]
Wow I didn't know `≡-≟-identity` and `≢-≟-identity`, thanks a lot for the answer!
