### ISSUE TITLE
Agda seems to skip re-checking empty file when flags are changed

### ISSUE THREAD

**Issue by nad** [agda/agda#6135]
Consider the following sequence of commands:
```
$ touch M.agda
$ echo 'flags: --without-K' > .agda-lib
$ agda --no-default-libraries M.agda
Checking M ([…]/M.agda).
$ rm -f .agda-lib 
$ agda --no-default-libraries M.agda
Checking M ([…]/M.agda).
$ echo 'flags: --without-K' > .agda-lib
$ agda --no-default-libraries M.agda
$ 
```
Shouldn't Agda print `Checking M` when the flag `--without-K` is enabled?

I failed to reproduce the behaviour above with a non-empty file `M.agda`.

**Comment by andreasabel** [comment]
Why?  Isn't the `.agdai` file under `_build` up-to-date? 
(Cf. related issue #6134.)

**Comment by nad** [comment]
No, the `.agdai` file was produced using (effectively) `--with-K`.

**Comment by andreasabel** [comment]
> ```
> $ touch M.agda
> $ echo 'flags: --without-K' > .agda-lib
> $ agda --no-default-libraries M.agda
> Checking M ([…]/M.agda).
> ```
This will create `M.agdai` under `_build` with `--without-K`.

> ```
> $ rm -f .agda-lib 
> $ agda --no-default-libraries M.agda
> Checking M ([…]/M.agda).
> ```
This will crease `M.agdai` alongside `M.agda` with `--with-K`.

> ```
> $ echo 'flags: --without-K' > .agda-lib
> $ agda --no-default-libraries M.agda
> $ 
> ```
This will look at `M.agdai` under `_build` which is up-to-date, since we again require `--without-K`.

**Comment by nad** [comment]
Oh, right.

**Comment by andreasabel** [comment]
Good we converge.  Sorry, my first comment was a bit brief...
