### ISSUE TITLE
Preformance enhancement for large projects: Avoid recomputing `SourceToModule` maps

### ISSUE THREAD

**Issue by nad** [agda/agda#6145]
The computation `sourceToModule` is used in `generateAndPrintSyntaxInfo`, which is used repeatedly:

https://github.com/agda/agda/blob/82b2b0fbea55c1716685d72cd8546b533d0f12dc/src/full/Agda/TypeChecking/Monad/Base.hs#L876-L883

For large developments this could have a non-trivial cost.

**Comment by nad** [comment]
Fixed by the removal of `SourceToModule`.

**Comment by nad** [comment]
@andreasabel, have you verified that this particular change is a performance enhancement? The numbers that I presented (#6183) related to several changes.

**Comment by andreasabel** [comment]
> @andreasabel, have you verified that this particular change is a performance enhancement? The numbers that I presented (#6183) related to several changes.

No, but the alternative is to not mention this in the changelog at all.  After all, it is an internal refactoring, which _should_ be mentioned if it had performance benefits.

**Comment by nad** [comment]
I don't think this should be mentioned in the changelog without any evidence that it makes a difference.
