### ISSUE TITLE
Use relative paths?

### ISSUE THREAD

**Issue by nad** [agda/agda#6146]
Currently Agda uses "canonical" absolute paths. This can lead to performance problems (#5673) and has at least in the past led to a bug report related to symbolic links (#4828). Furthermore the use of absolute paths makes Agda's output more verbose than necessary. Would anything break if we switched to using relative paths (or absolute but not necessarily canonical paths)?

One situation to consider is that in which a user has set up symbolic links in such a way that two projects overlap. Here is one example of how Agda currently behaves:
```
$ (mkdir a && cd a && printf 'name: a\ninclude: src' > .agda-lib && mkdir src && touch src/M.agda) > /dev/null
$ (mkdir b && cd b && printf 'name: b\ndepend: a\ninclude: src' > .agda-lib && ln -s ../a/src) > /dev/null
$ printf "$PWD/a/.agda-lib\n$PWD/b/.agda-lib" > libraries
$ (cd b > /dev/null && agda --library-file=../libraries src/M.agda)
Checking M ([…]/a/src/M.agda).
```
Is this good? Let's try a different approach, using `mount` instead of `ln`:
```
$ (mkdir a && cd a && printf 'name: a\ninclude: src' > .agda-lib && mkdir src && touch src/M.agda) > /dev/null
$ (mkdir b && cd b && printf 'name: b\ndepend: a\ninclude: src' > .agda-lib && mkdir src && sudo mount -o bind ../a/src src) > /dev/null
$ printf "$PWD/a/.agda-lib\n$PWD/b/.agda-lib" > libraries
$ (cd b > /dev/null && agda --library-file=../libraries src/M.agda)
1,1-2
Ambiguous module name. The module name M could refer to any of the
following files:
  […]/a/src/M.agda
  […]/b/src/M.agda
```
I think I prefer this outcome over the other one. Furthermore this example shows that `canonicalizePath` does not actually return unique paths (as stated in its [documentation](https://hackage.haskell.org/package/directory-1.3.8.0/docs/System-Directory.html#v:canonicalizePath)).

So, could Agda switch to using relative paths? I did not find any use of `setCurrentDirectory` or `withCurrentDirectory` in the code base, so hopefully the meaning of a relative path does not change during program execution. I also investigated where in the code base `AbsolutePath`s are compared:
* `SourceToModule` maps use paths as keys:
  https://github.com/agda/agda/blob/82b2b0fbea55c1716685d72cd8546b533d0f12dc/src/full/Agda/TypeChecking/Monad/Base.hs#L871-L874
  `SourceToModule` maps are used to turn file names in ranges into module names. I wonder if it would make sense to replace the use of paths in `Position`s, `Interval`s and `Range`s with top-level module names (with a more efficient representation than the current one). This would complicate printing of ranges, but would perhaps otherwise be more clean. One could also add top-level module names but keep the file names, to avoid making printing more complicated.

  A `SourceToModule` map is also used by the serialiser. Paths are serialised as top-level module names, and then recreated (possibly with different prefixes) when an interface is deserialised. If top-level module names are used in `Position`s, `Interval`s and `Range`s, then we might get away with not serialising paths. We could still recreate the paths when the interfaces are decoded.
* The `Eq` and `Ord` instances for `Position`s, `Interval`s and `Range`s rely on comparison of paths. Do we ever compare positions (say) that come from different files? If not, then it may be better to skip comparing the paths. We could also switch to top-level module names, as discussed above.
* The generation of highlighting information includes more comparisons of paths that could be replaced by comparisons of top-level module names.
* In `createInterface` and `getStoredInterface` the warnings related to a given file are filtered out. One could use a given top-level module instead. (Is the filtering even necessary for `getStoredInterface`?)
* The following (orphan) `Semigroup` instance for `AbsolutePath` could be simplified to `const` and inlined into the `Semigroup` instance for `Range'`:
  https://github.com/agda/agda/blob/82b2b0fbea55c1716685d72cd8546b533d0f12dc/src/full/Agda/Syntax/Position.hs#L219-L221
  If paths are replaced by top-level module names, then the sanity check could be performed for module names instead.
* For some reason meta-variable literals include paths:
  https://github.com/agda/agda/blob/82b2b0fbea55c1716685d72cd8546b533d0f12dc/src/full/Agda/Syntax/Literal.hs#L26
  Wouldn't it make more sense to use (perhaps top-level) module names?
* The following function uses path equality:
  https://github.com/agda/agda/blob/82b2b0fbea55c1716685d72cd8546b533d0f12dc/src/full/Agda/TypeChecking/Monad/Base.hs#L890-L894
  I think use of this function could be avoided by including top-level module names in a few data types (for literal meta-variables and in `CurrentFile`), and using `envCurrentModule` instead of `envCurrentPath` in `topLevelModuleDropper`:
  https://github.com/agda/agda/blob/82b2b0fbea55c1716685d72cd8546b533d0f12dc/src/full/Agda/TypeChecking/Errors.hs#L292-L301
* In `findFile` file names are compared, and Agda complains if two or more file names correspond to a single top-level module name. If the user has set up symbolic links in such a way that two different paths point to the same file, then it might make sense to inform the user about this.
* Similarly, in `setIncludeDirs` duplicate include directories are discarded. One could perhaps stop doing this if issue [#2506](https://github.com/agda/agda/issues/2506) is fixed in a different way. In `setIncludeDirs` the state is also partly reset if the include directories have changed. I think the current logic works also with relative paths, but if a relative include path is changed to a different but equivalent relative path, then Agda might discard parts of the state that are not discarded today.
* In `runInteraction` a file is loaded if its name does not match that of the current file. I guess it makes sense to do this check (and a subsequent check in the same procedure) for relative paths. I expect that front-ends typically use the same path in successive command invocations for a given file.
* If `-vcheck.ranges:90` is used then paths are compared in the implementation of `traceClosureCall` for `TCM`. This comparison could use top-level module names instead.
* Agda also compares paths using `sameFile`, which uses `canonicalizePath` and `equalFilePath`. This comparison is done in `checkModuleName`: a type error is raised if the file name obtained from `findFile'` does not match the one given to `checkModuleName`. I guess we can stop using `canonicalizePath` for this test. The function `equalFilePath` is case-insensitive on Windows, but to avoid portability problems it might be better to use plain equality (see also issue [#5719](https://github.com/agda/agda/issues/5719)). One could perhaps use `equalFilePath` and/or `canonicalizePath` to make the error message more informative.

I think it makes sense to try to switch to relative paths.

**Comment by JacquesCarette** [comment]
My 2 cents: I think it would make most sense to use module names (likely behind an interface, so that library-relative module names could be used in the future) rather than file names for what you document above.

I don't have an opinion on the rest. I certainly didn't spot anything that felt like a "oh no, don't do that!" in any of the proposal.

**Comment by andreasabel** [comment]
A concrete first step could be to consistently maintain the project root in the state, and then file names could be local to this project root.  See:
- https://github.com/agda/agda/issues/6173#issuecomment-1272619564

**Comment by nad** [comment]
I don't follow you. Different files can belong to different projects.

**Comment by nad** [comment]
> I don't follow you. Different files can belong to different projects.

This was a reply to a comment made by @andreasabel. Was this comment deleted?

**Comment by nad** [comment]
When working on this I realised a potential problem:
```
$ cat B.agda
module A.B where
$ agda -i.. B.agda
B.agda:1,8-11
You tried to load B.agda which defines the module A.B. However,
according to the include path this module should be defined in
../A/B.agda.
$ agda -i.. ../A/B.agda
Checking A.B (../A/B.agda).
```
GHC has no problem with this:
```
$ cat B.hs
module A.B where
$ ghc -i.. B.hs
[1 of 1] Compiling A.B              ( B.hs, B.o )
```
However, GHC does not care what the module name is:
```
$ cat B.hs
module C.D where
$ ghc -i -i.. B.hs
[1 of 1] Compiling C.D              ( B.hs, B.o )
```
I see some ways forward:
* Accept the error message above. (I don't think this is a good idea.)
* Use `canonicalizePath` to avoid at least some instances of this kind of error message, despite the fact that `canonicalizePath` does not return canonical paths.
* Stop checking that the main module's top-level module name is correct, and just accept what the user has written. However, in the cases where the module name is not "correct" this might involve not caching the module (or something like that), to ensure that the module is not used when another module is imported, so I'm not too keen on this.

**Comment by nad** [comment]
Another problem: If you refer to the module `A.B` using the path `dir/A/C/../B.agda`, then the root directory (used to search for `.agda-lib` files) obtained from `projectRoot` is currently `dir/A/C`. How can this be addressed?
* Could `canonicalizePath` be used? In that case `dir` would also be affected. Furthermore, if `canonicalizePath` is used, then one gets the wrong result if `A.B` is stored in `A/B.agda`, where `A` is a symbolic link to `C/D`.
* Could `projectRoot` use `..`? In that case the root for the first example above would be `dir/A/C/../..`. However, the root for `A/B.agda` would be `A/..`, and if `A` is a symbolic link to `C/D`, then this refers to `C` (on at least some systems), so that would not work.
* One option is perhaps to check that the path suffix is correct in `projectRoot`, and raise an error if it is not.

**Comment by nad** [comment]
I went with the last option above ("check that the path suffix is correct"), and for the previous comment I went with the second option ("Use `canonicalizePath` to avoid at least some instances of this kind of error message").

I also changed the way in which Agda searches for `.agda-lib` files, using more or less an approach discussed [elsewhere](https://github.com/agda/agda/issues/5673#issuecomment-981708861): if the (absolute) root path is `/a/b/c`, then Agda now searches in `/a/b/c`, `/a/b`, `/a` and `/`, in that order. If the idea is to make it easier to use symbolic links, then I think this is better than the old approach, which could give different results in the presence of symbolic links.

However, I'm not certain that it is a good idea to perform these changes. Some pros and cons:
* Some paths printed by Agda are shorter (but that could be accomplished through the use of `makeRelative`).
* One can use symbolic links more freely. For instance, `A.B` can be placed in `C/D/B.agda` if there is a symbolic link from `A` to `C/D`. (Is this a good thing?)
* One cannot use the path `A/C/../B.agda` to refer to `A.B`.
* Limited testing suggests that the last commit had a limited impact on performance (335 s and 348 s for the standard library, compared to 347 s and 353 s).
* The last commit made the number of calls to `stat`/`lstat` for an empty file, with no `~/.agda` directory, go down from 275 to 59 (see [#5673](https://github.com/agda/agda/issues/5673)).

@andreasabel: The output changed for the test case for issue [#5268](https://github.com/agda/agda/issues/5268) under `test/interaction`, perhaps you'd like to take a look at that.

What do you think? Even if you are positive towards this change I suggest that it should not be part of the next release: I would not be surprised if there is something that I haven't thought of, and I think it makes sense to test the implementation, and consider the various design decisions, more carefully before the change is released.

**Comment by nad** [comment]
I should perhaps note that I have hardly tested the Emacs mode at all, and I expect that something will not work properly. However, I don't want to spend time on that if we decide to abandon these changes. I think the main question is whether we want to support more uses of symbolic links, at the cost of not allowing `..` in parts of the paths. (Some preliminary changes seem to have made Agda faster, but those have already been committed.)

**Comment by andreasabel** [comment]
@nad: I keep this on 2.6.4 for now, since work is ongoing.  Are you planning to finish this for `2.6.4` or `later`?

**Comment by andreasabel** [comment]
No reply, so I bump this to 2.6.5.

**Comment by nad** [comment]
No one replied when I asked for feedback, and now I'm working on other things.
