### ISSUE TITLE
Importing Agda.Primitive.Cubical without --cubical or --erased-cubical should fail

### ISSUE THREAD

**Issue by nad** [agda/agda#6155]
@jespercockx [reported](https://github.com/agda/agda/issues/3750#issuecomment-1266799994) that one can import `Agda.Primitive.Cubical` without enabling `--cubical` or `--erased-cubical`. That should not be possible.

This fails:
```agda
open import Agda.Builtin.Cubical.Glue
```
```
Importing module Agda.Builtin.Cubical.Glue using the
--cubical/--erased-cubical flag from a module which does not.
when scope checking the declaration
  open import Agda.Builtin.Cubical.Glue
```
This should also fail:
```agda
open import Agda.Primitive.Cubical
```
However, I guess that things from `Agda.Primitive.Cubical` are sometimes used behind the scenes when `--without-K` is used, that should still be possible.

**Comment by jespercockx** [comment]
But I like this feature :(

**Comment by plt-amy** [comment]
In light of #6049, `Agda.Primitive.Cubical` would be locked behind `--cubical-compatible`, rather than `--cubical` itself? As you mention we need stuff from that module to generate hcomp/transpIx helpers and clauses.

**Comment by nad** [comment]
@jespercockx, you could use `--with-K --cubical`:
```agda
{-# OPTIONS --with-K --cubical #-}

open import Agda.Builtin.Cubical.Glue
```

**Comment by nad** [comment]
I think we can close this in favour of #6582.
