### ISSUE TITLE
Internal error with `--no-load-primitives` and undefined `LEVEL` builtin

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#6168]
Agda crashes if there is no `LEVEL` builtin but we write level polymorphic type signatures.
```agda
{-# OPTIONS --no-load-primitives #-}

{-# BUILTIN TYPE Type #-}
{-# BUILTIN PROP Prop #-}
{-# BUILTIN SETOMEGA Typeω #-}
{-# BUILTIN STRICTSET SSet #-}
{-# BUILTIN STRICTSETOMEGA SSetω #-}

postulate IO : ∀ {a} → Type a → Type a
```
The crash is here: https://github.com/agda/agda/blob/1a8214f7408811478791233c500917087225040a/src/full/Agda/TypeChecking/Level.hs#L35-L36
(Is there a way to get the call stack?)

**Comment by andreasabel** [comment]
This can be fixed by using `getBuiltin` (proper error) rather than `getBuiltin'` (crash).
There is just one location where we do not have `MonadTCError` (but just `PureTCM`) so we have to use the unsafe version: https://github.com/agda/agda/blob/1a8214f7408811478791233c500917087225040a/src/full/Agda/TypeChecking/Rewriting/Confluence.hs#L872-L876
But this is in the confluence checker, and to get there we will have required BUILTIN LEVEL already.

**Comment by andreasabel** [comment]
The OP is probably just the tip of the iceberg.  
@jespercockx, the new flag `--no-load-primitives` invalidates a lot of work you did years ago where you generalized builtins to work in pure settings, because it was safe to assume they were defined. See e.g. aab8e9c2c8c4b243487eee2c12fa1d32216897b8.
However, now we have to roll back and scrutinize every use of `getBuiltin'` whether is is safe or whether we have to do `getBuiltin` (that raises an error if the builtin is undefined).  CC @UlfNorell.

**Comment by jespercockx** [comment]
I remember that when I implemented the pure builtins, we discussed this precise issue, and concluded that it should not be possible to skip importing `Agda.Primitive`, i.e. we should always be able to assume that the primitives in it are defined. The only reason for keeping `Agda.Primitive` as a module was then to allow renaming of the symbols defined in it. This new flag `--no-load-primitives` kind of goes directly against that idea, so it is no wonder that things break.

In https://github.com/agda/agda/pull/6020, you said:

> Why not? I am happy to give this a green light.

I guess this is your answer :)

**Comment by jespercockx** [comment]
This is going to make @plt-amy sad but I propose that we roll back the addition of the `--no-load-primitives` flag for the release of 2.6.3.

**Comment by andreasabel** [comment]
@jespercockx I am not against this feature, I just wanted to point out that we have to undo some of the simplification we performed when we could rely on the builtins to be defined.

> This is going to make @plt-amy sad but I propose that we roll back the addition of the `--no-load-primitives` flag for the release of 2.6.3.

Either that or we solidify this new feature with exhaustive test cases.  I suppose rolling back would amount to a commit that removes the flag and also all related changes and additions to the test suite, changelog, and documentation.  It should be easy then to bring the feature back after the release.
@plt-amy How important is it for you to have the feature in 2.6.3 rather than just on a branch (with the prospect of entering 2.6.4)?

**Comment by jespercockx** [comment]
It was not just "simplification", making things pure sometimes also gives a significant performance improvement. So if you want to undo my changes you should also test to make sure it doesn't have adverse effects on performance.

**Comment by andreasabel** [comment]
Looking at PR #6169 you can see that I didn't move any code out of `PureTCM` (or other pure variants).  My hope would be that I/we can continue like that, that it is sufficient to employ the safe `getBuiltin` (over the unsafe `getBuiltin'`) just in code that has `MonadTCError`.  This way, no performance degrading is expected.

**Comment by plt-amy** [comment]
> How important is it for you to have the feature in 2.6.3 rather than just on a branch (with the prospect of entering 2.6.4)?

@andreasabel I don't mind at all: the 1Lab is pinned to a specific Agda commit, since we use it as a library - so it's easy for me to stick with the branch.

**Comment by jespercockx** [comment]
In that case I do not have a problem with this addition, though I do not really see the point of it personally.

**Comment by plt-amy** [comment]
I wrote it so I could [attach docs to TYPE and friends](https://1lab.dev/1Lab.Prim.Type.html), and the cubical primitives too. Admittedly rather niche 🙂
