### ISSUE TITLE
Agda input `\<` should give `\langle` as first choice

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#6172]
I'd like `\<` to continue giving me `\langle` and `\>` resolve to `\rangle` as first choices in the emacs mode.  This has changed on master, presumably after:
- #6077 (ping @mikeshulman)

Not sure if this is the correct line to blame:
https://github.com/agda/agda/blob/10f735dec63c60729fa4ab13fc8736700759021e/src/data/emacs-mode/agda-input.el#L238-L239

**Comment by mikeshulman** [comment]
I agree those should be the first choices.  Presumably this has something to do with the order in which the line you cited appears in the file compared to wherever the `\langle`/`\rangle` lines are defined?  I don't know what the correct fix is.
