### ISSUE TITLE
Should README modules still be supported?

### ISSUE THREAD

**Issue by nad** [agda/agda#6220]
I have a README module which imports both a module that uses `--with-K` and a module that uses `--cubical`. After the recent change to the meaning of `--cubical-compatible` this module is rejected, because `--cubical` implies `--cubical-compatible`, which is coinfective, and the imported module which uses `--with-K` does not use `--cubical-compatible`.

We should decide whether this kind of README module should still be supported when Agda 2.6.3 is released, and in that case, how it should be supported:

* One option is to say that this kind of module is not supported. It could for instance be replaced by a makefile, plus an HTML file for the documentation.

* Another option is to introduce a new flag, `--only-imports`. When this flag is used Agda would only support `import` statements. The flag would be infective, and it should be possible to import all kinds of modules (including modules that use infective features, even if those features are not activated in the importing module), with one exception: if a module that uses `--only-imports` also uses `--safe`, then all imported modules must use `--safe`.

**Comment by nad** [comment]
If we do not allow README modules, then I think we should allow giving multiple Agda files on the command-line:
* Reloading interface files can be slow.
* The HTML backend generates HTML for the file given on the command-line plus all its dependencies. If two incompatible files have overlapping dependencies, and HTML is generated for both of these files, then HTML is generated twice for the overlapping dependencies.

The first problem can be addressed through the use of `--interaction`, but that can be fiddly. The file `Setup.hs` currently takes this approach, but my implementation was not quite correct (#6128). If Agda had accepted multiple Agda files on the command-line, then the code in `Setup.hs` could have been replaced by something more straightforward.

**Comment by nad** [comment]
An easy fix, shortly before the release, is to change `--cubical-compatible` so that it is not coinfective in modules that use `--with-K` (and not `--safe`).

**Comment by nad** [comment]
> An easy fix, shortly before the release, is to change `--cubical-compatible` so that it is not coinfective in modules that use `--with-K` (and not `--safe`).

I went with a slightly more restrictive variant. Here is the documentation:

```rst
Furthermore the option :option:`--cubical-compatible` is mostly
coinfective. If a module uses :option:`--cubical-compatible` then all
modules that this module imports (directly) must also use
:option:`--cubical-compatible`, with the following exception: if a
module uses both :option:`--cubical-compatible` and
:option:`--with-K`, then it is not required to use
:option:`--cubical-compatible` in (directly) imported modules that use
:option:`--with-K`. (Note that one cannot use
:option:`--cubical-compatible` and :option:`--with-K` at the same time
if :option:`--safe` is used.)
```

**Comment by andreasabel** [comment]
(Excluded from changelog; fixes a "regression" caused by a new feature.)
