### ISSUE TITLE
Links from user-manual, e.g. cubical.rst,  to github should be permalinks

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#6234]
The user manual contains links to movable targets, such as:
https://github.com/agda/agda/blob/c6f187a62f5966579e5ece0524804bef90184d23/doc/user-manual/language/cubical.lagda.rst?plain=1#L553-L555
This isn't good as these links may break when e.g. the `cubical` library is modified / restructured.
These should be permalinks at least in every release of Agda.
Probably a solution on the level of Python is best here: introduce special link form to link to the cubical library, and set this to a specific tag/commit in the `conf.py` file.  (We could of course also hardwire the permalinks, but these are harder to update.)

Grepping for `blob` in the user manual currently gives:
```
./team.rst�79:<https://github.com/agda/agda/blob/master/LICENSE>`_.
./language/guarded-cubical.lagda.rst�17:For its usage, see :ref:`[1] <cubical-refs>` or the `example <https://github.com/agda/agda/blob/master/test/Succeed/LaterPrims.agda>`_.
./language/cubical.lagda.rst�101:https://github.com/agda/cubical/blob/master/INSTALL.md. In order to
./language/cubical.lagda.rst�556:inverse): https://github.com/agda/cubical/blob/master/Cubical/Foundations/Isomorphism.agda.
./language/cubical.lagda.rst�626:https://github.com/agda/cubical/blob/master/Cubical/Core/Glue.agda and
./language/cubical.lagda.rst�627:https://github.com/agda/cubical/blob/master/Cubical/Foundations/Univalence.agda. For
./language/cubical.lagda.rst�630:https://github.com/agda/cubical/blob/master/Cubical/Data/BinNat/BinNat.agda.
./language/cubical.lagda.rst�851:`an example from the Cubical library <https://github.com/agda/cubical/blob/2131b6c08e32fdcf5b9292e5c6d6f23e4bf80fcd/Cubical/Structures/Macro.agda>`_.
./language/cubical.lagda.rst�871:https://github.com/agda/cubical/blob/master/Cubical/Core/Id.agda file
./language/cubical.lagda.rst�878:univalence). Using this we have implemented an `interface to HoTT/UF <https://github.com/agda/cubical/blob/5de11df25b79ee49d5c084fbbe6dfc66e4147a2e/Cubical/Experiments/HoTT-UF.agda>`_
./getting-started/tutorial-list.rst�24:  <https://github.com/jespercockx/agda-lecture-notes/blob/master/agda.pdf>`__.
./getting-started/tutorial-list.rst�104:  (CS410), Conor McBride, Strathclyde, `notes from 2015 <https://github.com/pigworker/CS410-15/blob/master/CS410-notes.pdf>`__, `videos from 2017 <https://github.com/pigworker/CS410-17/>`__.
./getting-started/a-taste-of-agda.lagda.rst�23:<https://github.com/agda/agda-stdlib/blob/master/notes/installation-guide.md>`_.
./getting-started/installation.rst�76:https://github.com/haskell/text-icu/blob/master/README.markdown#prerequisites
./getting-started/installation.rst�211:is an additional step using `a separate repository <https://github.com/agda/agda-stdlib/blob/master/notes/installation-guide.md>`_.
./contribute/index.rst�10:A code of conduct and other considerations are described in the `HACKING.md <https://github.com/agda/agda/blob/master/HACKING.md>`_
```
(Some of these might be movable targets by intention.)

**Comment by andreasabel** [comment]
This seems to mostly affect `cubical.lagda.rst`.  @mortberg , any chance you can fix that before the release?

**Comment by andreasabel** [comment]
This looks like a low-hanging fruit fixable for 2.6.4.
Ping @mortberg @plt-amy

**Comment by andreasabel** [comment]
No progress, so, bumping to 2.6.5.

**Comment by andreasabel** [comment]
**Wake-up call!**
`cubical.lagda.rst` has broken links to the cubical library.
> (language/cubical: line  948) broken    https://github.com/agda/cubical/blob/master/Cubical/Core/Id.agda - 404 Client Error: Not Found for url: https://github.com/agda/cubical/blob/master/Cubical/Core/Id.agda

This needs fixing ASAP!  
This issue has been open for over a year now. 
I might find a simple but mostly unpleasant solution if this issue does not get attention. _And now also the ax is laid to the root of the trees: therefore every tree which brings not forth good fruit is hewn down, and cast into the fire. (Matthew 3:10)_
 
ATTN: @mortberg @plt-amy 

Pinging `cubical` experts that could help out here: @ecavallo @felixwellen

**Comment by mortberg** [comment]
I vote for just deleting all links to the library as this will keep on breaking and have links to agda/cubical and the 1lab at the top of the file. I also vote fore deleting the section "Cubical identity types and computational HoTT/UF" as it is now completely outdated (unless I'm mistaken?)

Anyone against? @plt-amy @ecavallo @felixwellen

**Comment by plt-amy** [comment]
That works for me as well.

**Comment by ecavallo** [comment]
Agreed.

**Comment by felixwellen** [comment]
Yes - good.

**Comment by andreasabel** [comment]
@mortberg Anders, can you submit a PR today that makes the changes you intend?

**Comment by mortberg** [comment]
> @mortberg Anders, can you submit a PR today that makes the changes you intend?

Yes, on it now! Sorry for taking so long to fix this.

**Comment by mortberg** [comment]
PR ready. @felixwellen @ecavallo Please take a quick look at it as well

**Comment by ecavallo** [comment]
LGTM

**Comment by felixwellen** [comment]
LGTM now
