### ISSUE TITLE
Migration guide to `--cubical-compatible`

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#6241]
We need to spell out explicitly somewhere (I suggest in the CHANGELOG) simple steps to migrate from `--without-K` to `--cubical-compatible`.  I suppose that these steps would be the following, assuming you want everything to work just as in 2.6.2:
- replace `--without-K` by `--cubical-compatible` (in your OPTIONS pragmas or library flags)
- add option `-WnoNoEquivWhenSplitting`.

(Btw. any chance to rename this warning to not start with `No`?)

**Comment by nad** [comment]
Perhaps the warning could even have a more self explanatory name.

**Comment by andreasabel** [comment]
New warning name suggestion: `UnsupportedIndexedMatch`.
- update docs
- update standard-library: flags

**Comment by plt-amy** [comment]
(Did we appoint anyone to rename the warning?)

**Comment by andreasabel** [comment]
> (Did we appoint anyone to rename the warning?)

(No, at that point, no one volunteered directly.)
