### ISSUE TITLE
The dead-code analysis could skip generated clauses

### ISSUE THREAD

**Issue by nad** [agda/agda#6245]
During the developer meeting today I asked whether the dead-code analysis could skip the clauses that are generated to support matching on inductive families in Cubical Agda, and according to @plt-amy that is the case.

**Comment by plt-amy** [comment]
Justification: the generated clauses only mention Cubical Agda primitives (which are no longer considered for deadness: #6152) and the function currently being coverage-checked.

**Comment by nad** [comment]
A simple fix might be to add a flag to the `Clause` type which indicates whether the clause was generated, and to add a variant of `namesAndMetasIn` with a predicate of type `Clause -> Bool`.

**Comment by nad** [comment]
Could more clauses be skipped? I found the following ones that seem to be related to Cubical Agda:
* In `defineKanOperationR`:
  https://github.com/agda/agda/blob/c72b29a31eca24554167981cc2d8f8b00a2ddd4b/src/full/Agda/TypeChecking/Rules/Record.hs#L506
  https://github.com/agda/agda/blob/c72b29a31eca24554167981cc2d8f8b00a2ddd4b/src/full/Agda/TypeChecking/Rules/Record.hs#L524
* In `checkFunDefS`:
  https://github.com/agda/agda/blob/c72b29a31eca24554167981cc2d8f8b00a2ddd4b/src/full/Agda/TypeChecking/Rules/Def.hs#L332
* In `defineCompData`:
  https://github.com/agda/agda/blob/c72b29a31eca24554167981cc2d8f8b00a2ddd4b/src/full/Agda/TypeChecking/Rules/Data.hs#L597
* In `defineConClause`:
  https://github.com/agda/agda/blob/c72b29a31eca24554167981cc2d8f8b00a2ddd4b/src/full/Agda/TypeChecking/Rules/Data.hs#L1268
* In `createMissingTrXTrXClause`:
  https://github.com/agda/agda/blob/c72b29a31eca24554167981cc2d8f8b00a2ddd4b/src/full/Agda/TypeChecking/Coverage/Cubical.hs#L373
* In `createMissingTrXHCompClause`:
  https://github.com/agda/agda/blob/c72b29a31eca24554167981cc2d8f8b00a2ddd4b/src/full/Agda/TypeChecking/Coverage/Cubical.hs#L641
* In `createMissingTrXConClause`:
  https://github.com/agda/agda/blob/c72b29a31eca24554167981cc2d8f8b00a2ddd4b/src/full/Agda/TypeChecking/Coverage/Cubical.hs#L875
* In `createMissingConIdClause`:
  https://github.com/agda/agda/blob/c72b29a31eca24554167981cc2d8f8b00a2ddd4b/src/full/Agda/TypeChecking/Coverage/Cubical.hs#L1121
* In `createMissingHCompClause`:
  https://github.com/agda/agda/blob/c72b29a31eca24554167981cc2d8f8b00a2ddd4b/src/full/Agda/TypeChecking/Coverage/Cubical.hs#L1367

Which of these can be skipped by the dead-code analysis?

**Comment by nad** [comment]
I tried to omit the clauses created in `createMissingTrXTrXClause`, `createMissingTrXHCompClause` and `createMissingTrXConClause` from the dead-code analysis, and quick testing suggests that this does not make Agda faster.

I've pushed the changes to the issue6245 branch, in case anyone wants to investigate this further.
