### ISSUE TITLE
Document options `--prop`, `--guarded`, and `--two-level`.

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#6257]
@nad writes in https://github.com/agda/agda/issues/6049#issuecomment-1293844473:
> No, some are missing, including at least --prop, --guarded, and --two-level.

These options should be documented in the user manual.

**Comment by nad** [comment]
I found two more undocumented options: `--keep-covering-clauses`, `--lossy-unification`.

**Comment by andreasabel** [comment]
I agree these should also be documented, so feel free to open a new issue.  (But I achieved what I set out to do in this issue.)

**Comment by nad** [comment]
See #6269.
