### ISSUE TITLE
Make -v import.chase official

### ISSUE THREAD

**Issue by mikeshulman** [agda/agda#6261]
The undocumented verbosity flag `-v import.chase` displays a notification when compilation of each imported file is completed, in addition to when it is started.  I think this is a useful feature that regular users (such as myself) may want, and it would be nice to make it official and documented.  (In fact, I was told that this used to be the default behavior.)

It would also be nice if when this flag is enabled, the information it displays would go in the regular `AgdaInfo` buffer, rather than the hidden `*Agda debug*` buffer.

**Comment by nad** [comment]
I think that `-v` should be reserved for debugging information. A different flag could be used for the suggested feature, especially if the semantics should be different.

**Comment by mikeshulman** [comment]
Makes sense.
