### ISSUE TITLE
Some options should be listed in `restartOptions`

### ISSUE THREAD

**Issue by nad** [agda/agda#6265]
The following options are not listed in `restartOptions`:
* `optCopatterns`
* `optFirstOrder`
* `optFlatSplit`
* `optForcing`
* `optKeepCoveringClauses`
* `optPatternMatching`
* `optProjectionLike`

The following options related to backends are also not included, but perhaps that is fine, if the idea is that the backends should take care of recompilation logic:
* `optCompileNoMain`
* `optCountClusters`

Perhaps the following options related to performance could be removed from the list:
* `optCallByName`
* `optFastReduce`
* `optSaveMetas`

It is apparently easy to forget to add a new option to `restartOptions`. Perhaps we could instead use a function that blanks out options that should not trigger a "restart".

**Comment by nad** [comment]
> The following options are not listed in `restartOptions`:

If the changes in my pull request are included changes to these options should trigger a recheck.

> The following options related to backends are also not included, but perhaps that is fine, if the idea is that the backends should take care of recompilation logic:

> Perhaps the following options related to performance could be removed from the list:

I did not change the treatment of these options (except that I removed an occurrence of `reportSLn`).

I also noted that a change to `optUnicode` triggers a recheck. I did not change this behaviour.

> It is apparently easy to forget to add a new option to `restartOptions`. Perhaps we could instead use a function that blanks out options that should not trigger a "restart".

I made the functionality safer in the sense that, if one forgets to update the functionality when a new option is added, then one risks getting too many rechecks rather than too few.

**Comment by andreasabel** [comment]
> I made the functionality safer in the sense that, if one forgets to update the functionality when a new option is added, then one risks getting too many rechecks rather than too few.

Yes, this seems the safer way round.
