### ISSUE TITLE
Irrelevance in the type of a record module definition

### ISSUE THREAD

**Issue by nad** [agda/agda#6270]
Consider the following code:
```agda
record R : Set where
  A : Set₁
  A = Set
```
The type of `R.A` uses irrelevance:
```
Modules
Names
  A : .R → Set₁
```
Why is this the case? If you add a trivial field to `R`, then the type of `R.A` no longer uses irrelevance:
```agda
open import Agda.Builtin.Unit

record R : Set where
  field
    x : ⊤

  A : Set₁
  A = Set
```
```
Modules
Names
  A : R → Set₁
  x : R → ⊤
```
Ordinary modules are not treated in this way:
```agda
module _ where

module M (_ : Set) where
  A : Set₁
  A = Set
```
```
Modules
Names
  A : Set → Set₁
```

**Comment by andreasabel** [comment]
> Why is this the case?

Records that have only irrelevant fields (e.g. zero fields) are considered irrelevant as a whole.
https://github.com/agda/agda/blob/e6ab653d89b329394eb36c5ca1311878091dd564/src/full/Agda/TypeChecking/Rules/Record.hs#L194-L201

See:
- #392

**Comment by nad** [comment]
> Records that have only irrelevant fields (e.g. zero fields) are considered irrelevant as a whole.

This means that irrelevance can sneak into a development even if `.` is not used explicitly. I think this feature should be hidden behind a flag. (Either there could be a flag for all kinds of irrelevance, or such a flag plus a separate flag for this feature.)

**Comment by jespercockx** [comment]
Having a flag for turning on/off irrelevance as a whole makes more sense from a user perspective I believe.

**Comment by andreasabel** [comment]
Cubical uses irrelevance, so `--cubical` would imply `--irrelevance`.

**Comment by UlfNorell** [comment]
Why do we need to mark (eta) records with zero fields as irrelevant? Any two elements of the record are already equal by eta expansion..
