### ISSUE TITLE
Our feedback on GHC medium-term priorities

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#6274]
Dear Agda team,

I got a message from the Haskell foundation asking for our feedback on GHC.  We are recognized as "key customer" of GHC so our input will count or at least be responded upon.

We are asked to respond within 2 weeks, so roughly by the last days of the Agda meeting.  Thus, there is a bit of time to collect our feedback, we could even have a little session during AIM on this.

When I think about where I hit the wall with Haskell/GHC it is there:

1. I'd like to have **pointer equality** for short-cutting `Eq` comparison.

2. **Default method implementations for type classes**: There is only one default implementation possible per method, but I have needed **several**:
   - A `DefaultSignatures` one: implementing a whole instance in terms of other instances.
   - Implementing a method in terms of a sibling.
  
   See e.g. https://github.com/agda/agda/blob/ee2047a61a211c7333192a524f94728018202e91/src/full/Agda/TypeChecking/Monad/Debug.hs#L99-L103
   Maybe `DerivingVia` from GHC 8.6 is an alternative we have not explored yet (since it wasn't available for us).

3. **`SPECIALISE`** being automatically determined by a whole program analysis so that you do not get punished for increasing abstraction.  (Maybe this is partly/already addressed by `-fspecialise-aggressively`?)

4. Performance tweaking is hard due to call-by-need, but I don't have an actionable item there, maybe Nisse @nad has?

These points came to my mind rather soon but there could be more with longer thinking.  What are your thoughts here?

Our feedback should be crisp, actionable, referring to existing GHC issues where possible, and concern _medium-term_ goals that can be addressed within 3-6 months.

I suppose we do some brainstorming, discussion and prioritization here and then I write an answer to the Haskell foundation.

On 2022-11-01 22:04, David Christiansen wrote:
> I'm writing on behalf of the GHC team, who would like to invite a small 
> set of key "customers" for GHC to share their advice about what the 
> medium term priorities for GHC should be. They would like to be sure 
> that work on urgent day-to-day tasks does not eclipse other important 
> bigger-picture issues. In order to make GHC an excellent tool for you, 
> its users, they would like you to tell them what is important to you. 
> I'm not a GHC developer - my role here is to run a structured process to 
> free up the GHC team's time so they can focus on GHC itself as much as 
> possible.
> 
> Rather than running an open survey of thousands of Haskell users, at 
> this time we are seeking thoughtful advice from a small number of 
> well-informed groups, such as:
>   * HLS team
>   * Cabal team
>   * Stack and stackage team
>   * GHCUp team
>   * Core Libraries Committee
>   * Haddock team
>   * A few library developers who are active, prolific, and/or with very 
> widely-used libraries.
> 
> We would like to invite responses from you on behalf of your project 
> (e.g. "Here's what the Agda team thinks") rather than from you as an 
> individual. In effect, we are inviting you to do some internal 
> prioritization of issues.
> 
> In return we will respond with a "you asked, we did" report, so that you 
> know how we have responded -- or not -- to your suggestions.
> 
> The questions that we'd like you to answer are:
> 
> What do you need from GHC that you aren't getting at the moment?  What 
> are your primary pain points, or lost opportunities?
> 
> Please respond with one or more suggestions, including
>   * A sense of priority, and order of importance among your 
> suggestions.  Is it
>     * Critical: outright prevents me using GHC for a particular purpose
>     * Non-critical: workarounds exist, but nice to have fixed.
>   * As actionable as possible. Saying "better documentation" is very 
> hard to turn into action.  Similarly "don't break our build" is hard to 
> turn into action, except by freezing every function in every module of 
> GHC and its libraries.
>   * As crisp and precise as possible.
>   * Something that might reasonably be tacked on a 3-6 month timescale.
>   * If there is a specific issue in GHC's issue tracker that 
> characterizes what you need, please refer to it. If not, please consider 
> creating one.
> 
> Please send your answers in the next two weeks, that is, by November 15. 
> I'll put together a small working group to process the answers and 
> produce a report for the GHC team. If you're willing and able to serve 
> in this group, please let me know this as well.
> 
> Thank you very much for helping make Haskell better!
> 
> On behalf of the GHC team,
> David Thrane Christiansen
> Executive Director
> The Haskell Foundation

**Comment by jespercockx** [comment]
On top of my list would definitely be a smarter way of having type class specialization without the cost of either having to add `SPECIALIZE` pragmas by hand (and thus risk forgetting them in places) or the explosion in compilation time and size of the final executable associated with `specialize-aggressively` and `expose-all-unfoldings`.

Also a better way of dealing with **circular module dependencies** than `.hs-boot` files (again, ideally one that doesn't affect incremental compilation times so much as the status quo).

I'll try to think of other ideas so we can discuss them at the Agda meeting! Having a discussion session dedicated to this is definitely a good idea, I'll add it to the wiki page.

**Comment by nad** [comment]
> When I think about where I hit the wall with Haskell/GHC it is there:
> 
> 1. I'd like to have pointer equality for short-cutting `Eq` comparison.

Have you looked at [`System.Mem.StableName`](https://hackage.haskell.org/package/base-4.17.0.0/docs/System-Mem-StableName.html)?

**Comment by gallais** [comment]
I talked a little bit with Adam Gundry at the last SPLS and I did mention that compiling
`Agda.TypeChecking.Serialise.*` takes an awful lot of time, so much so I'm tempted
to rip out the type-level magic I put in there to avoid having `valu1` ... `valu30`.
He told me that he's working on **making type-level computations faster** (IIRC the
internal representation grows quadratically in the number of reduction steps).

So that would have been my one comment but it's already being looked at apparently. 😃

**Comment by andreasabel** [comment]
@jespercockx wrote:
> Also a better way of dealing with circular module dependencies than `.hs-boot` files

Apparently, such are not very common. Matthew Pickering told me in https://gitlab.haskell.org/ghc/ghc/-/issues/22017#note_448845 that GHC and Agda are the "main projects" using boot-files.

That said, I agree, would be nice not to have to write these boot files.

**Comment by andreasabel** [comment]
@nad wrote:
> > 1. I'd like to have pointer equality for short-cutting `Eq` comparison.
> 
> Have you looked at [`System.Mem.StableName`](https://hackage.haskell.org/package/base-4.17.0.0/docs/System-Mem-StableName.html)?

I had a look and this does not appeal to me.  I want pointer equality at every type without placing everything in `IO`.

**Comment by nad** [comment]
> I had a look and this does not appeal to me. I want pointer equality at every type without placing everything in `IO`.

Pointer equality is not referentially transparent, so I'm not quite sure what you are looking for. Perhaps you can hack something together using `unsafePerformIO`.

**Comment by nad** [comment]
This is probably too vague, but I wonder how cautious GHC's optimiser is for the Haskell code that Agda's GHC backend generates, with its liberal use of `unsafeCoerce`. Perhaps it could do a better job.

**Comment by andreasabel** [comment]
> Pointer equality is not referentially transparent, so I'm not quite sure what you are looking for.

Isn't it reasonable to assume that at two addresses that are the same the same value is stored?  Even if a closure is stored there...
A function like `eq x y = pointerEq x y || (x == y)` can yield true on `eq x x` in O(1), while `x == x` can take arbitrarily long in Haskell.

**Comment by szumixie** [comment]
There's a [`reallyUnsafePtrEquality`](https://hackage.haskell.org/package/base-4.17.0.0/docs/GHC-Exts.html#v:reallyUnsafePtrEquality) in base, containers uses it so it shouldn't be too unsafe.

**Comment by andreasabel** [comment]
> There's a [`reallyUnsafePtrEquality`](https://hackage.haskell.org/package/base-4.17.0.0/docs/GHC-Exts.html#v:reallyUnsafePtrEquality) in base, containers uses it so it shouldn't be too unsafe.

Thanks for the pointer.  The name is a bit discouraging, though, likely by intention.

**Comment by andreasabel** [comment]
Here is our final list, not ordered by priority:

1. **Pointer equality** for short-cutting `Eq` comparison, so that we can implement `eq x y = pointerEq x y || (x == y)` safely, saving us expensive structural comparison when looking at literally the same thing.

2. **Default method implementations for type classes**: There is only one default implementation possible per method, but I have needed **several**:
   - A `DefaultSignatures` one: implementing a whole instance in terms of other instances.
   - Implementing a method in terms of a sibling.
  
   See e.g. https://github.com/agda/agda/blob/ee2047a61a211c7333192a524f94728018202e91/src/full/Agda/TypeChecking/Monad/Debug.hs#L99-L103

3. **`SPECIALISE`** being automatically determined by a whole program analysis so that you do not get punished for increasing abstraction.  We wish for a smarter way of having type class specialization without the cost of either having to add `SPECIALIZE` pragmas by hand (and thus risk forgetting them in places) or the explosion in compilation time and size of the final executable associated with `specialize-aggressively` and `expose-all-unfoldings`.

4. A better way of dealing with **circular module dependencies** than `.hs-boot` files (again, ideally one that doesn't affect incremental compilation times so much as the status quo).

5. **Making type-level computations faster** such as we define in this module: https://github.com/agda/agda/blob/bac6a3782ef214f7638e599f9e8f96329023f210/src/full/Agda/TypeChecking/Serialise/Base.hs#L381-L392 IIRC the internal representation grows quadratically in the number of reduction steps.  (Maybe Adam Gundry is already working on it.)

**Comment by andreasabel** [comment]
Thanks for the feedback.  I answered to David Christiansen (Haskell foundation).

**Comment by UlfNorell** [comment]
Why did you put pointer equality on the list? What is it you want that `reallyUnsafePtrEquality` doesn't do?

**Comment by andreasabel** [comment]
> Why did you put pointer equality on the list? What is it you want that `reallyUnsafePtrEquality` doesn't do?

I want it to be safe and this name is discouraging.  Here is a reddit that claims that it is safe: https://www.reddit.com/r/haskell/comments/e1l329/reallyunsafeptrequality_but_safe/  
So, if it is safe, then why is it discouraged _twice_ with _unsafe_ and _really_.

**Comment by nad** [comment]
Presumably because it breaks referential transparency. In pure Haskell you typically expect that if `e₁` has the same denotation as `e₂`, then `C[e₁]` has the same denotation as `C[e₂]`, for some definition of "denotation" that does not distinguish values only because they reside in different parts of the heap.

You can perhaps construct a safe variant of `reallyUnsafePtrEquality` by pairing it up with `(==)` as you suggest above, given some assumptions:
* The function `(==)` is "safe" (respects the denotational semantics).
* The function `(==)` returns `True` for inputs with the same denotation. Note that this can be hard to ensure for recursive, non-strict data types.
* The function `reallyUnsafePtrEquality` is sufficiently atomic. If the first pointer is read, but then a garbage collection happens which moves both objects, and then the second pointer is read, then you could get false positives.

**Comment by UlfNorell** [comment]
Indeed. This feels like something you wrap up in a library only exporting the pointer-short-cutting-equality. I don't see that there's a better "safer" primitive the ghc team could provide that would help.

**Comment by jespercockx** [comment]
Isn't "add a pointer-shortcutting equality check to an easily accessible library on Cabal" a reasonable suggestion to make to the GHC developers then?

**Comment by UlfNorell** [comment]
Not sure why that's something the GHC developers should do rather than us doing it ourselves.

**Comment by andreasabel** [comment]
See:
- https://github.com/agda/agda/issues/6351
