### ISSUE TITLE
LaTeX/HTML generation doesn't properly render parameters of pre-declared records

### ISSUE THREAD

**Issue by Lysxia** [agda/agda#6276]
Example:

```
\begin{code}
record F (A : Set) : Set

record F A where
\end{code}
```

Run `agda --latex A.lagda.tex`. The second `A` is not wrapped as `\AgdaBound{A}`, and is just a naked string.

```
\begin{code}%
\>[0]\AgdaKeyword{record}\AgdaSpace{}%
\AgdaRecord{F}\AgdaSpace{}%
\AgdaSymbol{(}\AgdaBound{A}\AgdaSpace{}%
\AgdaSymbol{:}\AgdaSpace{}%
\AgdaPrimitive{Set}\AgdaSymbol{)}\AgdaSpace{}%
\AgdaSymbol{:}\AgdaSpace{}%
\AgdaPrimitive{Set}\<%
\\
%
\\[\AgdaEmptyExtraSkip]%
\>[0]\AgdaKeyword{record}\AgdaSpace{}%
\AgdaRecord{F}\ A\ \AgdaKeyword{where}\<%
\end{code}
```

```
Agda version 2.6.2.2
```

**Comment by nad** [comment]
I'm guessing that this problem is closely related to one I reported recently (#6273).

**Comment by andreasabel** [comment]
Yeah, highlighting is also broken for the OP in the non-interactive mode.  So, it isn't connected to *`interleaved`* `mutual`.

**Comment by nad** [comment]
> I'm guessing that this problem is closely related to one I reported recently (#6273).

[Not really.](https://github.com/agda/agda/issues/6273#issuecomment-1302263801)

> Yeah, highlighting is also broken for the OP in the non-interactive mode. So, it isn't connected to _`interleaved`_ `mutual`.

The problem I reported in issue #6273 is connected to `interleaved mutual`, see my analysis of that problem.

**Comment by nad** [comment]
This problem seems to be easy to fix, just replace `A.noDataDefParams` with `ps` in the following piece of code:

https://github.com/agda/agda/blob/fc4e2fa5d866b3fa55f944c8ca17c54f8db35b7f/src/full/Agda/TypeChecking/Rules/Decl.hs#L409
