### ISSUE TITLE
Document interaction between reflection and erasure

### ISSUE THREAD

**Issue by nad** [agda/agda#6292]
The user manual section about run-time irrelevance currently does not cover reflection. I think we should specify when the reflection machinery makes the type-checker enter or leave compile-time mode.

@jespercockx, perhaps you have the best understanding of this part of the implementation. Can you write something?

I labelled this as a bug, because what is currently in the user manual is presumably not quite correct.

**Comment by andreasabel** [comment]
@jespercockx : This should probably be fixed for 2.6.4.

**Comment by jespercockx** [comment]
I'm looking at this but I'm not sure what's actually wrong with the current documentation. @nad could you let me know what part of the interaction between reflection and erasure should be documented?

**Comment by andreasabel** [comment]
No progress, so, bumping this to 2.6.5.

**Comment by nad** [comment]
> I'm looking at this but I'm not sure what's actually wrong with the current documentation. @nad could you let me know what part of the interaction between reflection and erasure should be documented?

The two pieces of text that start with "The type checker enters compile-time mode when" and "The type-checker switches from compile-time mode to run-time mode for" might have to be edited (and in that case the final note can be removed).

**Comment by jespercockx** [comment]
I added some documentation in https://github.com/agda/agda/pull/7310
