### ISSUE TITLE
Hidden argument puns

### ISSUE THREAD

**Issue by nad** [agda/agda#6325]
Recently I wrote the following code:
```agda
  {R = R} {x₁ = x₁} {x₂ = x₂} {y₁ = y₁} {y₂ = y₂}
  {xs₁ = xs₁} {e₁ = e₁} {xs₂ = xs₂} {e₂ = e₂} {e₁′ = e₁′}
```
I have lots of code of this highly redundant form. I could perhaps use positional matching for some of the arguments, but with generalisable variables it might not be clear in what order the arguments appear, and perhaps the order changes if Agda's unification algorithm changes.

I would like to be able to write the following instead:
```agda
  {R} {x₁} {x₂} {y₁} {y₂} {xs₁} {e₁} {xs₂} {e₂} {e₁′}
```
I suggest that we add a flag called something like `--implicit-argument-puns` (the name is based on GHC's feature [`NamedFieldPuns`](https://downloads.haskell.org/ghc/9.4.2/docs/users_guide/exts/record_puns.html)). If that flag is used, then `{x}` in a binding position means `{x = x}`.

In analogy with GHC's record wildcards one might also consider supporting something like `{…}`, where this would mean, roughly, "`{x}` for each implicit argument `x` that has not been explicitly bound". However, I don't want to mix scope-checking and type-checking, so I do not suggest that we should implement this.

**Comment by andreasabel** [comment]
With `--implicit-argument-puns` on, should something like `f {g x}` be an error?  (You would have to pass that argument by name, like `f {z = g x}`.)

**Comment by nad** [comment]
I only intended this change to affect left-hand side binders.

**Comment by andreasabel** [comment]
> I only intended this change to affect left-hand side binders.

So, should `{suc x}` be an error as or in a pattern?  

And what if my variable name clashes with a constructor?
```agda
open import Agda.Builtin.Nat

foo : {zero : Nat} -> Nat
foo {zero} = 43
```

**Comment by nad** [comment]
> So, should `{suc x}` be an error as or in a pattern?

Do you want Agda to reject `f {x y} = …`? I only suggested to change the meaning of `{x}`, not `{x y}` or `{(x)}`.

> And what if my variable name clashes with a constructor?

Good point. When you expand `{x}` to `{x = x}`, then I think the second occurrence of `x` should be treated as a bound variable. If there is also a constructor called `x` in scope, then I think Agda should warn about this.

**Comment by nad** [comment]
I think it should also be possible to have instance argument puns, so I suggest that the flag is called `--hidden-argument-puns` instead.

> When you expand `{x}` to `{x = x}`, then I think the second occurrence of `x` should be treated as a bound variable. If there is also a constructor called `x` in scope, then I think Agda should warn about this.

I've changed my mind. The pattern `{constructor}`, with `constructor` interpreted as a pun, does not correspond to a pattern without puns, so I think we should disallow it.

**Comment by andreasabel** [comment]
@nad: Anything left to be done here for 2.6.4?

**Comment by nad** [comment]
I don't think so.
