### ISSUE TITLE
Some errors when install Agda use Cabal

### ISSUE THREAD

**Issue by learn-man** [agda/agda#6328]
how can i slove the problem from following:

![install-agda](https://user-images.githubusercontent.com/84730871/201742447-f3fd0f02-7d37-4d89-a9e1-ea70d633d139.png)

![install-cabal](https://user-images.githubusercontent.com/84730871/201742457-327de13a-cecf-447c-86a6-2c9c5c05c1a5.png)

![install-caballist](https://user-images.githubusercontent.com/84730871/201742459-b5961b58-de1b-4733-a321-c4d57239b953.png)

![install-ghc](https://user-images.githubusercontent.com/84730871/201742462-2a29948c-afd0-40da-b380-edb0023f4c0a.png)

**Comment by gallais** [comment]
Looks like you're using a recent version of GHC which is not supported by 2.6.2.2
(that's what the error message about `base` is).
Try installing the release candidate for 2.6.3 instead: https://github.com/agda/agda/releases/tag/v2.6.2.2.20221106

**Comment by andreasabel** [comment]
Agda-2.6.2.2 does support GHC 9.2.x (even GHC 9.4.x), so you should be able to install it.

Did you do `cabal update`?
Something looks weird in your system:  Why is `base-4.10.0.0` the "default available version"?  This is `base` for an old GHC (I think 8.2).  On my system, the "default available version" is the same as the "installed version".  You also have a mismatch for "Cabal".  Looks like your system is in a somewhat inconsistent state...

**Comment by andreasabel** [comment]
I speculate `cabal update` before `cabal install Agda` could fix this.  I am closing this issue, but welcome to continue the discussion here, or to reopen it should problems persist.

**Comment by learn-man** [comment]
@gallais Thanks first. But result the same error message from source build.

@andreasabel Thanks first. Yes, i **did** `cabal udpate` first. then, you are guessed wrong.

I'll use **Coq**. 
Thanks.

**Comment by gallais** [comment]
Andreas is correct that the ghc install just seems weirdly broken.
The [`base` library version does not match the ghc version](https://wiki.haskell.org/Base_package).
That should never happen.

It's not Agda specific so even if you decide to use Coq for your project,
I think you'll still need to fix your install to work with any other haskell project.

**Comment by andreasabel** [comment]
@learn-man wrote:
> I'll use **Coq**.

I don't expect any more feedback from the reporter at this point, so I book this under "invalid" (problem with the Haskell setup).
