### ISSUE TITLE
`--lossy-unification` in Agda 2.6.3

### ISSUE THREAD

**Issue by martinescardo** [agda/agda#6337]
Agda developers, thanks for accommodating the renaming of `--experimental-lossy-unification` to `--lossy-unification`, which I asked for in a separate issue.

Which I now realize will cause a problem for a few of us, not only in my project `TypeTopology`, but (at least) the cubical library.

I wonder if we could still keep `--experimental-lossy-unification` as "deprecated" but still functional for a while, until everybody transitions from 2.6.2.2 to 2.6.3, which, of course, is going to take a while. We don't want to give trouble to our library users. Thank you.

**Comment by andreasabel** [comment]
Yeah, makes sense to not bluntly remove syntax from one release to another, and this also applies to command-line and pragma syntax.  (With some hesitation whether this principle should also apply to experimental, undocumented features like `--lossy-unification`.)

Shouldn't be hard to add a mechanism for the substitution `old-flag --> new-flag` that comes with a deprecation warning.

**Comment by andreasabel** [comment]
Chefsache.

**Comment by andreasabel** [comment]
Price tag on this issue: 5000 SEK 
(One of my hours costs GU 1000 SEK.)

**Comment by martinescardo** [comment]
> Price tag on this issue: 5000 SEK (One of my hours costs GU 1000 SEK.)

Thanks a lot for doing this. I am applying for a grant to pay for this. But I can also pay you with my hours in the future.

**Comment by asr** [comment]
@andreasabel, I suggest to create an issue with `milestone 2.6.4` for removing the `--experimental-lossy-unification` option.
