### ISSUE TITLE
Add `--erased-matches` and `--erasure`

### ISSUE THREAD

**Issue by nad** [agda/agda#6349]
We don't currently have a flag for erasure, and the reason is that parameters are always erased in the types of constructors and projections for non-indexed data types and record types. However, we could disallow users from writing `@0` unless an infective flag `--erasure` is used. In that case erasure is still present in the type system if `--erasure` is not used, but in a (presumably) very limited way. What do you think, should we add such a flag?

I at least want to add a second flag, `--single-constructor-matching`. Agda currently allows matching in erased positions for non-indexed data types that have one constructor. Given that this feature is less well-explored than some other things I think we should hide it behind a flag. The flag should be infective, and I think it should be implied by `--with-K` (because we currently allow this kind of matching also for indexed types when `--with-K` is used).

**Comment by nad** [comment]
We could allow single-constructor matching without a flag for record types with η-equality, because something like `f (x , y) = e[x, y]`, where the argument of `f` is erased, means the same thing as `f p = e[p .fst, p .snd]`.

**Comment by nad** [comment]
> We don't currently have a flag for erasure, and the reason is that parameters are always erased in the types of constructors and projections for non-indexed data types and record types. However, we could disallow users from writing `@0` unless an infective flag `--erasure` is used. In that case erasure is still present in the type system if `--erasure` is not used, but in a (presumably) very limited way. What do you think, should we add such a flag?

Does anyone have any opinions about this?

**Comment by jespercockx** [comment]
I support it, from the general perspective that it makes vanilla Agda simpler and it is easy enough to add `--erasure` to my agda-lib files.

**Comment by nad** [comment]
I implemented `--erasure`. If the flag is not active, then two things are prevented:
* The use of erasure attributes.
* The use of names coming from Cubical Agda in Erased Cubical Agda. (Because such names are mostly treated as erased.)

Once these changes have been committed it should be easy to disallow `@lock` and `@tick` attributes (#5034), polarity attributes (#6385), and optionally also irrelevance attributes.

**Comment by nad** [comment]
It should not be possible to use `--erase-record-parameters` without `--erasure`. I suggest that the former flag should imply the latter. One might argue that we should take the same approach for `--single-constructor-matching` (which will probably be called something else). However, `--with-K` implies `--single-constructor-matching`, and I don't want `--with-K` (which is on by default) to imply `--erasure`. Perhaps one could say that only explicit use of `--single-constructor-matching` implies `--erasure`, but I don't want to complicate things too much.

**Comment by nad** [comment]
I noticed that some builtin modules use `--erase-record-parameters` (ab7a323210385dad9b41d7234cc918768743b2aa): `Agda.Builtin.FromNat`, `Agda.Builtin.FromNeg` and `Agda.Builtin.FromString`. This change has not been released yet.

@jespercockx, is this change essential? Should we force all users of these modules to use erasure (and `--erasure`)?

I turned off `--erase-record-parameters` in `Agda.Builtin.FromNat` and could define a variant of `fromNat` that matches the type of the currently exported function:
```agda
{-# OPTIONS --cubical-compatible --erasure --safe #-}

open import Agda.Builtin.FromNat hiding (fromNat)
open import Agda.Builtin.Nat
open import Agda.Primitive

fromNat :
  {@0 a : Level} {@0 A : Set a}
  ⦃ r : Number A ⦄ (n : Nat) ⦃ _ : Number.Constraint r n ⦄ →
  A
fromNat ⦃ r ⦄ = Number.fromNat r
```
However, the `BUILTIN FROMNAT` pragma still refers to the variant of `fromNat` from `Agda.Builtin.FromNat`:

https://github.com/agda/agda/blob/d0eaeead3610aea56bc0bbcf5e5482040ea23383/src/data/lib/prim/Agda/Builtin/FromNat.agda#L15

Does anything break if the level and type arguments of `fromNat` are not erased? I assume that this change has something to do with the agda2hs backend. Would it help to make `fromNat` `STATIC`, so that applications of `fromNat` are normalised before being sent to agda2hs, or would this hurt (say) performance in some way?

**Comment by jespercockx** [comment]
I'm currently no longer using `--erase-record-parameters` for agda2hs, since it did not play well together with `--erased-cubical` (see https://github.com/agda/agda2hs/pull/111). So perhaps the easiest solution is to just remove the flag from these builtin files again. I apologize for perhaps being a bit too quick with making changes to Agda itself when my problem could be solved as well by thinking a bit more careful about the structure of the backend.

**Comment by nad** [comment]
> So perhaps the easiest solution is to just remove the flag from these builtin files again.

In that case I suggest that we do this before releasing Agda 2.6.3. I'll open a new issue for this.

**Comment by nad** [comment]
After some discussion (#6350) I renamed `--single-constructor-matching` to `--erased-matches`.

**Comment by nad** [comment]
Furthermore the flag `--erase-record-parameters` now requires the use of `--erasure`.
