### ISSUE TITLE
Internal error when using irrelevant projection inside a parametrized module

### ISSUE THREAD

**Issue by omelkonian** [agda/agda#6360]
The following code:
```agda
module _ (A : Set) where

record R : Set where
  field .a : A

.FAIL : R → A → A
FAIL r _ = a
  where open R r
```
produces the following **internal error**:
```
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/Substitute.hs:319:46 in Agda-2.6.2.1-c5068201a10d9285dc344713ee6c215e819665e00f0b2826d55e5698f0605714:Agda.TypeChecking.Substitute
```
It relies on bypassing the `--irrelevant-projections` flag by opening the record-module (c.f. #6359).

---
Agda: 2.6.2.1
*(sorry if this has already been fixed in a more recent version)*

**Comment by nad** [comment]
This problem seems to have been fixed already. Thanks for your report!
