### ISSUE TITLE
Confusing warning about turning instances into instances

### ISSUE THREAD

**Issue by felixwellen** [agda/agda#6380]
This:
```agda
postulate B C : Set
postulate b : B
postulate c : C


record A : Set where
  instance
    irrelevantInstance = b

  something : C → C
  something c = c


postulate a : A
open A {{...}}

instance _ = a

_ = something c
```
produces this warning:
```
Instance declarations with explicit arguments are never considered
by instance search, so making test.A.irrelevantInstance into an
instance has no effect.
when checking that c is a valid argument to a function of type
.⦃ r : A ⦄ → C → C
```
When `irrelevantInstance` is removed, the warning goes away. I think there should be no warning in this situation.

**Comment by andreasabel** [comment]
This warning was not produced in Agda 2.5.2/3/4, it first appeared in Agda 2.6.0.  (Agda < 2.5.2 also does not throw this warning, but another one on the butlast declaration: "Instance applies only to declarations that introduce new identifiers".)
This warning is thrown from `addTypedInstance`, and likely through `getInstanceDefs` (via `resolveUnknownInstanceDefs`): https://github.com/agda/agda/blob/dc2478c35eb0e0f995a9dedd6bb7f2ac3fed6a24/src/full/Agda/TypeChecking/Telescope.hs#L664-L676
Looks like colateral damage of 2bbb52ac28efd2ed82b5c6d5cc3ac9425e850485 (ping @jespercockx) in the context of:
- #3534

**Comment by andreasabel** [comment]
#6383 fixes this issue by using a version of `addTypedInstance` used in `getInstanceDefs` that does not cast any warnings.
