### ISSUE TITLE
Windows line ending messes up syntax highlighting, code ranges and error-jumps

### ISSUE THREAD

**Issue by anuyts** [agda/agda#6398]
I've received some Agda files from a windows user which I've been trying to type-check. Syntax highlighting in emacs was completely messed up and the error messages I got did not have correct code ranges (in the Agda output) and clicking them in emacs sent me to a *different* but still wrong code range.
Opening the concerned files in gedit and resaving them with Linux/Unix line ending encoding solved the issue. (Gedit can also save with Windows encoding, which may help out to reproduce the bug.)

I'm on Agda version 2.6.4-2f0ea06

---

Please make sure it is actually a problem with Agda or its documentation. For user questions, the [mailing list](https://lists.chalmers.se/mailman/listinfo/agda) or the [chat](https://agda.zulipchat.com) are better fora.

Please take some time to search through the exising issues whether the problem has already been reported.  If it is already an open issue, you might confine yourself with just adding your problem instance as a comment there.

For opening a new issue, please make sure you can check the following boxes:

* [X] My report includes the version of Agda (and Emacs, GHC, and OS versions where relevant).

* [X] The issue can be reproduced with the _latest version_ of Agda (either [released](https://wiki.portal.chalmers.se/agda/Main/Download) or `master` branch).
      Note: We do not fix issues in older versions of Agda.

* [ ] I have supplied all information so the bug can be easily reproduced (in particular, the reproducer is a complete Agda file).

Note: The best reproducers are those only using the `Agda.Builtin` and `Agda.Primitive` modules shipped with Agda.

**Comment by nad** [comment]
I can reproduce the problem using the following code (with "CR LF" line endings):
```agda
A : Set₁
A = Set
```

**Comment by szumixie** [comment]
It's a regression, it works correctly in 2.6.2.

**Comment by nad** [comment]
Bisection points to 8d75579c41308fc33671a96235a83f72add316c2. Previously we used `String`-based IO with the following newline conversion settings:

https://github.com/agda/agda/blob/4b76fbf46ea2cbec350834949a5786024aa5e1e7/src/full/Agda/Utils/IO/UTF8.hs#L40-L41

Now we use `ByteString` and `Text`, and convert "LF CR" to "LF", but we should convert "CR LF" to "LF":

https://github.com/agda/agda/blob/557681d04aae2100ccde2e045a8afcf30528c3a5/src/full/Agda/Utils/IO/UTF8.hs#L26-L27
