### ISSUE TITLE
Stop using HLint?

### ISSUE THREAD

**Issue by nad** [agda/agda#6411]
I suggest that we stop using HLint, because I think it creates too much noise.

Consider a recently closed pull request, #6347. Under the "Files changed" tab there is currently a section called "Unchanged files with check annotations" containing a bunch of suggestions from HLint that are not related to the pull request.

**Comment by jespercockx** [comment]
I don't think I've ever found the outputs all that useful, so from me this gets a thumbs up.

**Comment by andreasabel** [comment]
Yes, no one is maintaining that, e.g. in terms of adding exceptions to the hlint config, or cleaning up the code.  I'll remove it.

**Comment by philderbeast** [comment]
> Yes, no one is maintaining that, e.g. in terms of adding exceptions to the hlint config, or cleaning up the code. I'll remove it.

I'd be prepared to maintain the hlint config and follow some of the hlint suggestions in a cautious way (like what I did for https://github.com/ucsd-progsys/liquid-fixpoint/issues/552).

**Comment by andreasabel** [comment]
> I'd be prepared to maintain the hlint config and follow some of the hlint suggestions in a cautious way (like what I did for [ucsd-progsys/liquid-fixpoint#552](https://github.com/ucsd-progsys/liquid-fixpoint/issues/552)).

I am happy to merge uncontroversial and small ("salami-slice") PRs triggered by hlint refactorings, like your PR:
- #6438 

However, we have to make sure we stay clear of hlint suggestions that make the code less readable (like introducing `foldr/l`) or less robust to edits (like removing redundant `do`).  We had such in the past.  I can't find the worst examples, but here are some:
- https://github.com/agda/agda/pull/4479/files#r1072770545
- https://github.com/agda/agda/pull/4479/files#r1072772209

There were, of course also good edits in the process.  Overall, though, I didn't think that `hlint` would increase productivity.

**Comment by philderbeast** [comment]
@andreasabel thanks for the guidance.
