### ISSUE TITLE
Apparent infinite loop in cubical with --lossy-unification

### ISSUE THREAD

**Issue by dolio** [agda/agda#6415]
I was trying to test out an example of regularity failing in cubical, and the result seems to be an infinite loop on the trunk version of Agda. Here's a simple test case:

```agda
open import Cubical.Foundations.Prelude
open import Cubical.Foundations.Univalence
open import Cubical.HITs.S1

G : Type
G = Glue S¹ {i0} empty

g : G
g = glue empty base

hmm : transport (λ _ → G) g ≡ g
hmm = refl
```

My expectation was that `hmm` would quickly fail with a unification error. However, it seems that Agda is stuck in a loop that quickly consumes a lot of memory. In some cases I might chalk this up to things actually expanding into giant cubical terms, but I don't think this example is big enough for that. So I suspect it's just in some kind of trivial loop.

**Comment by tomjack** [comment]
Hmm, I cannot reproduce, on 39cc3079c6b4ef46f64868c7146fd7bc3aa4ef23 I get the following error:

```agda
hcomp (λ i → empty)
(hcomp
 (λ i →
    primPOr
    (i0 ∨ Agda.Builtin.Cubical.HCompU.primFaceForall (λ i₁ → i0))
    (~ (i0 ∨ Agda.Builtin.Cubical.HCompU.primFaceForall (λ i₁ → i0)))
    (λ .o →
       transp (λ i₁ → S¹) i
       (primPOr i0
        (Agda.Builtin.Cubical.HCompU.primFaceForall (λ i₁ → i0))
        (λ .o₁ → Agda.Builtin.Cubical.Glue.prim^unglue g)
        (λ .o₁ →
           Agda.Builtin.Cubical.Glue.equivFun (empty _ .snd)
           (transp (λ j → empty _ .fst) (i0 ∨ ~ i) g))
        _))
    (λ .o →
       transp (λ i₁ → S¹) i0 (Agda.Builtin.Cubical.Glue.prim^unglue g)))
 (transp (λ i → S¹) i0 (Agda.Builtin.Cubical.Glue.prim^unglue g)))
!= base of type S¹
when checking that the expression refl has type
transport (λ _ → G) g ≡ g
```

**Comment by dolio** [comment]
Ah hah. So, here's the difference. I was running with `--lossy-unification`. When I remove that, I get an actual error. So this is some kind of bad interaction between the two.

**Comment by andreasabel** [comment]
> I was running with `--lossy-unification`.

Yeah, don't use this hack.  There are no guarantees for it whatsover.

**Comment by jespercockx** [comment]
> Yeah, don't use this hack. There are no guarantees for it whatsover.

I think that's a bit harsh. I think it is more fair to say that by using it, you lose the guarantee that metavariable solutions are unique, and this can lead to certain other issues such as getting type errors too eagerly. But you should still have most other guarantees that Agda provides, such as type-safety and termination. So I would still consider this a bug worth solving.

One experiment you could do is to make *all* implicit arguments in your example explicit. That way there should not be a difference in whether you use `--lossy-unification` or not.

**Comment by dolio** [comment]
I tried filling in all the implicit arguments, and it still seems to loop.

When I was doing this, I noticed that it appears that `empty` takes implicit arguments that could also, I think, be `empty`, so I thought perhaps it was possible that the lossy unifier would just spend forever building larger implicit chains of `empty` applied to `empty`. However, I've also tried changing from `empty` to `λ()`, and it _still_ loops. So, unless `λ()` turns into `empty` for cubical systems and causes the same problem, I don't really have any ideas on what it's doing.

Also, if the above _is_ the explanation, I don't really understand how the normal unifier could fully solve the problem with no ambiguities, since it seems like the full, explicit term would be infinite anyway.

Also, I think you should seriously think about `--lossy-unification` as a genuine feature. I've been using it a lot since hearing about it, and the *significant* majority of the time it does what I want, and I rarely run into problems with it. For instance, I think induction-recursion is often a chore to use with the normal unification algorithm, because it requires cluttering your code with explicit arguments that `--lossy-unification` is able to solve correctly 99% of the time.

If it's not just a switch for the entire algorithm, I think Agda could really use *something* that accomplishes similar behavior for some cases (like inferring `t` from `El t`), because I think my practical experience with `--lossy-unification` shows that there are a lot of situations where the unifier would just be picking (what happens to be) the right solution, but won't normally because of technicalities.

**Comment by jespercockx** [comment]
Note that the PR in https://github.com/agda/agda/pull/6354 is also (partly) about a more principled way to control when a symbol is considered as injective. It's still experimental, but it might be worth looking at.

**Comment by plt-amy** [comment]
This is #5955 again. Fix incoming.

**Comment by plt-amy** [comment]
Actually, I'll be damned, it's not #5955. Well, it's related, but not exactly:

We compare

```
transport (λ _ → G) g = g (-> by eta for glue)
unglue (transport (λ _ → G) g) = unglue g (-> first-order shortcut/lossy unification)
transport (λ _ → G) g = g
```

so really the "problem" is that the first-order shortcut is interfering with the optimisation making it so that `transp` along `Glue` won't compute until it's unglued, because the ungluing evaporated. The _actual_ problem, which is that the cubical code treats `prim^unglue` and `prim^unglueU` as "projections" (and `transp`/`hcomp` for Glue/hcompu as "defined by copatterns"), but lossy unification.. doesn't.
