### ISSUE TITLE
Forward declaration breaks eta for unit type

### ISSUE THREAD

**Issue by akaposi** [agda/agda#6417]
The following code does not typecheck, refl is not accepted as a proof for `η t`.
```agda
data _≡_ {A : Set}(a : A) : A → Set where
  refl : a ≡ a

A : Set₁

record ⊤ : Set where constructor tt
open ⊤

η : (t : ⊤) → t ≡ tt
η t = refl

A = Set
```

If you move the declaration of `A` down or the definition of `A` up, the problem disappears.

**Comment by andreasabel** [comment]
Yes, while you are inside a mutual block (spanned by declaration and definition of `A` here), the positivity checker hasn't run yet, and eta hasn't been switched on automatically.

Please switch eta on manually, like:
```agda
record ⊤ : Set where eta-equality; constructor tt
```

**Comment by andreasabel** [comment]
Is this a shortcoming in the documentation of record-eta/mutual blocks?  If yes, where (which chapter) should relevant documentation for this issue be added?

**Comment by akaposi** [comment]
Thanks, so it is not a bug at all, one just needs to explicitly declare the record to have eta-equality.

This information is already implicitly in the documentation: in the [chapter on records](https://agda.readthedocs.io/en/v2.6.2.2.20221128/language/record-types.html) it says that record types automatically have eta once the positivity checker allows it, and the [positivity checker](https://agda.readthedocs.io/en/v2.6.2.2.20221128/language/positivity-checking.html) works on mutual blocks. Maybe in the latter section it could be said that the positivity checker runs after typechecking the block?

**Comment by akaposi** [comment]
Sorry for my ignorance, but why isn't eta-equality always implicitly there? What is an example of a record type where the positivity checker turns eta-equality off?

**Comment by andreasabel** [comment]
It needs to turn of eta in some recursive records, e.g. this one (simplest case):
```agda
record R : Set where
  field unR : R
```

**Comment by akaposi** [comment]
This is also accepted:
~~~~
record R : Set where
  inductive
  eta-equality
  field unR : R
~~~~

Is `eta-equality` ignored here?

**Comment by andreasabel** [comment]
No it isn't because you declared it explicitly:
```agda
test : {x : R} → x ≡ record { unR = R.unR x }
test = refl
```
If Agda switched it off against the explicit will of the user (which Agda doesn't), it would warn.

**Comment by andreasabel** [comment]
@akaposi Shall we close this or do you think the documentation is lacking?  If yes, please point to the section that should be extended...

**Comment by akaposi** [comment]
I think it can be closed.
