### ISSUE TITLE
Erased arguments not usable in pattern-matching lambda

### ISSUE THREAD

**Issue by viktorcsimma** [agda/agda#6430]
I've found out that writing a completely erased function, some of the operations with erased arguments are allowed when using pattern matching clauses, but not when writing a pattern-matching lambda (with curly braces).

Here is a simple example:
```
open import Agda.Builtin.Nat

@0 f : @0 Nat → Nat
f = λ {zero → zero; (suc n) → suc n}
-- but this would work:
-- f zero = zero
-- f (suc n) = suc n
```
This gives:
```
erasure_bug.agda:4,35-36
Variable n is declared erased, so it cannot be used here
when checking that the expression n has type Nat
```
I reproduced the issue with Agda 2.6.2.2 on Ubuntu 20.04 with Emacs 26.3.

I assume this should be allowed (as the pattern matching clauses work on it and a wholly erased function would not exist in runtime anyway), but I don't really know the internals. I haven't found any already existing issues related to this problem.

Could you check it out? Thank you in advance:)

**Comment by nad** [comment]
This works if you use an erased pattern-matching lambda:
```agda
@0 f : @0 Nat → Nat
f = λ @0 {zero → zero; (suc n) → suc n}
```
If you switch to the current development version of Agda then the code works without changes, as long as you use `--erasure`:

https://github.com/agda/agda/blob/c71e83595629789b963fa5a8a1c42180f05a6956/doc/release-notes/future.md?plain=1#L7-L39

**Comment by viktorcsimma** [comment]
Oh, I see... I didn't know that; thank you very much:)
