### ISSUE TITLE
Erased import statements

### ISSUE THREAD

**Issue by nad** [agda/agda#6431]
Perhaps it makes sense to support erased import statements:
```agda
import @0 M
open import @erased N
```
@jespercockx [wrote](https://github.com/agda/agda/issues/4743#issuecomment-1025961462) that "it would be good to be able to add an erasure annotation to a module import, so as to avoid having that import in the code generated by the backend". However, it is not quite clear to me what the semantics of an erased import statement should be.

Currently Agda supports something similar to erased import statements. One can import Cubical Agda code from Erased Cubical Agda code, and the Cubical Agda code is erased, and not compiled. Now consider the following code:
```agda
{-# OPTIONS --cubical-compatible #-}

module Cubical-compatible where

open import Agda.Builtin.Bool public

elim : (P : Bool → Set) → P true → P false → (b : Bool) → P b
elim _ t f true  = t
elim _ t f false = f
```
```agda
{-# OPTIONS --cubical #-}

module Cubical where

import Cubical-compatible

Bool : Set
Bool = Cubical-compatible.Bool

true : Bool
true = Cubical-compatible.true

false : Bool
false = Cubical-compatible.false

elim : (P : Bool → Set) → P true → P false → (b : Bool) → P b
elim = Cubical-compatible.elim
```
```agda
{-# OPTIONS --erased-cubical --erasure #-}

module Erased-cubical where

open import Agda.Builtin.Cubical.Path
import Cubical

refl : ∀ {a} {A : Set a} {x : A} → x ≡ x
refl {x = x} = λ _ → x

mutual

  Bool : Set
  Bool = _

  _ : Bool ≡ Cubical.Bool
  _ = refl

mutual

  true : Bool
  true = _

  _ : true ≡ Cubical.true
  _ = refl

mutual

  false : Bool
  false = _

  _ : false ≡ Cubical.false
  _ = refl

mutual

  elim : (P : Bool → Set) → P true → P false → (b : Bool) → P b
  elim = _

  _ : elim ≡ Cubical.elim
  _ = refl

not : Bool → Bool
not = elim (λ _ → Bool) false true

true′ : Bool
true′ = not false
```
Note that `Bool`, `true`, `false` and `elim` get bound to names which are not in scope, that come from a module that has not been explicitly imported. The following Haskell code is generated when `Erased-cubical` is compiled using the GHC backend:
```haskell
{-# LANGUAGE BangPatterns #-}
{-# LANGUAGE EmptyCase #-}
{-# LANGUAGE EmptyDataDecls #-}
{-# LANGUAGE ExistentialQuantification #-}
{-# LANGUAGE NoMonomorphismRestriction #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE ScopedTypeVariables #-}

{-# OPTIONS_GHC -Wno-overlapping-patterns #-}

module MAlonzo.Code.ErasedZ45Zcubical where

import MAlonzo.RTE (coe, erased, AgdaAny, addInt, subInt, mulInt,
                    quotInt, remInt, geqInt, ltInt, eqInt, add64, sub64, mul64, quot64,
                    rem64, lt64, eq64, word64FromNat, word64ToNat)
import qualified MAlonzo.RTE
import qualified Data.Text
import qualified MAlonzo.Code.Agda.Builtin.Bool
import qualified MAlonzo.Code.Agda.Primitive
import qualified MAlonzo.Code.Agda.Primitive.Cubical
import qualified MAlonzo.Code.CubicalZ45Zcompatible

-- Erased-cubical.refl
d_refl_8 ::
  MAlonzo.Code.Agda.Primitive.T_Level_14 ->
  () ->
  AgdaAny -> MAlonzo.Code.Agda.Primitive.Cubical.T_I_8 -> AgdaAny
d_refl_8 ~v0 ~v1 v2 ~v3 = du_refl_8 v2
du_refl_8 :: AgdaAny -> AgdaAny
du_refl_8 v0 = coe v0
-- Erased-cubical.Bool
d_Bool_14 :: ()
d_Bool_14 = erased
-- Erased-cubical.true
d_true_18 :: Bool
d_true_18 = coe MAlonzo.Code.Agda.Builtin.Bool.C_true_10
-- Erased-cubical.false
d_false_22 :: Bool
d_false_22 = coe MAlonzo.Code.Agda.Builtin.Bool.C_false_8
-- Erased-cubical.elim
d_elim_30 :: (Bool -> ()) -> AgdaAny -> AgdaAny -> Bool -> AgdaAny
d_elim_30 v0 v1 v2 v3
  = coe MAlonzo.Code.CubicalZ45Zcompatible.du_elim_6 v1 v2 v3
-- Erased-cubical.not
d_not_34 :: Bool -> Bool
d_not_34 = coe d_elim_30 erased d_false_22 d_true_18
-- Erased-cubical.true′
d_true'8242'_38 :: Bool
d_true'8242'_38 = coe d_not_34 d_false_22
```
Note that the module `MAlonzo.Code.CubicalZ45Zcompatible` is imported, even though `Erased-cubical` only depends on `Cubical-compatible` via the Cubical Agda module `Cubical`.

The Agda implementation supports this mixture of Cubical and Erased Cubical Agda code through the following code in `getConstInfo`, which makes a definition erased if it was defined in a Cubical Agda module and the current module uses Erased Cubical Agda (as long as `--erasure` is used):

https://github.com/agda/agda/blob/743dbf9f4dca89f97841092c4e24f838b67ad5ac/src/full/Agda/TypeChecking/Monad/Signature.hs#L958-L971

I can think of two not very good ways to handle erased import statements:
* We could keep track of which names end up in the generated code, and skip compiling modules from which nothing is needed. However, then things that are only reachable via erased import statements might be compiled. This is reminiscent of #4733, but on the level of modules instead of individual definitions.
* We could ensure that modules that are only reachable via erased import statements are not compiled by making Agda complain if a definition that is needed is not reachable via non-erased import statements.

  A problem with this approach is that abstract code might become brittle: if you have a module `M` that only contains abstract code, and you change the import statements (for imports that do not have anything to do with the type signatures of the abstract code), then I don't think that this should affect the result of type-checking a module that imports `M`. Perhaps this could be addressed by also having abstract import statements: names brought into scope by such a statement would only be available in the bodies of abstract definitions (at the same level), and the imported modules would only be added to the reachability graph for the current module, not for importing modules. However, I would prefer a less complicated design.

  Note that non-abstract code might also become (more) brittle: if `import M using ()` is removed from a module, then a module that imports this module might be rejected.

What do you think? Can you come up with a better design?

(I intentionally skipped discussing `open public` above.)

**Comment by jespercockx** [comment]
This indeed a tricky problem. I agree that the first option is not very desirable, since things that are *only* reachable via an erased import should not appear in the generated code.

I think there is some merit to the second option, but in order to implement it we should be more careful about the import path through which a symbol is imported. In particular, we should distinguish occurrences of a symbol that are imported through a path with at least one erased import from the occurrences that are imported in a non-erased way.

In a hypothetical core theory of Agda, this would mean that symbols from an erased import (including transitive imports) are automatically wrapped in an `Erased` box, so that they are guaranteed to not occur in the generated code. If the same symbol is also imported directly, then there

Practically, the most feasible way to implement this would be by having an erasure annotation for each `def` and `con` in the internal syntax. Two `def`s with the same name but different erasure annotations would still be considered to be equal by the conversion checker, but only the non-erased one would actually be able to be used in compiled code.

I believe this would solve the brittleness issue that you describe, without having to add things such as `abstract` imports (though that might be a feature that would be independently valuable to have).

**Comment by nad** [comment]
> Practically, the most feasible way to implement this would be by having an erasure annotation for each `def` and `con` in the internal syntax. Two `def`s with the same name but different erasure annotations would still be considered to be equal by the conversion checker, but only the non-erased one would actually be able to be used in compiled code.

What should happen if an erased `Def` is reduced? Is the idea to mark everything in the reduct as erased? One could do this eagerly, but that might be inefficient. One could also do it lazily if a constructor `Erased` is added to the internal syntax, but that might require substantial changes to Agda, and could have other implications (perhaps it would affect the syntactic equality shortcut).

When a non-erased meta-variable is instantiated I guess one should check that the instantiation does not contain anything that is erased. What should happen if the instantiation contains something erased, but the corresponding non-erased thing is available? One option is to complain, but perhaps that would be annoying. Another option is to switch from the erased to the non-erased thing.

I'm not convinced that erased import statements are sufficiently important to warrant changes of this kind.

**Comment by jespercockx** [comment]
> I'm not convinced that erased import statements are sufficiently important to warrant changes of this kind.

I don't know the answer to these questions, so I tend to agree. Another option would be to not allow erased modules in general, but still allow importing a specific symbol in an erased way.

**Comment by nad** [comment]
> Another option would be to not allow erased modules in general

Did you mean erased import statements? Erased modules are already implemented, and the following code works:
```agda
{-# OPTIONS --erasure #-}

import Agda.Builtin.Unit

module @0 M = Agda.Builtin.Unit
```

**Comment by jespercockx** [comment]
Ah I did not realize that this already existed, in that case: great!
