### ISSUE TITLE
Compilation of Agda 2.5.2 with GHC 8.0.2 fails due to monadplus-1.4.3

### ISSUE THREAD

**Issue by wenkokke** [agda/agda#6436]
The new monadplus-1.4.3 was uploaded on 2023-01-06 has a breaking change, but only a patch version bump, which causes compilation of Agda 2.5.2 with GHC 8.0.2 to fail.

```
Failed to build monadplus-1.4.3.
Build log (
/home/runner/.cabal/logs/ghc-8.0.2/monadplus-1.4.3-fb5e7153f9a71a0d8f2701b97d4eb935eaf0a1cdb751bff9f15caa2c623874ef.log
):
Configuring library for monadplus-1.4.3..
Preprocessing library for monadplus-1.4.3..
Building library for monadplus-1.4.3..
[1 of 2] Compiling Control.Monad.Plus ( src/Control/Monad/Plus.hs, dist/build/Control/Monad/Plus.o )

src/Control/Monad/Plus.hs:270:15: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Sem.<>’,
                             imported from ‘Data.Semigroup’ at src/Control/Monad/Plus.hs:67:1-28
                          or ‘Data.Monoid.<>’,
                             imported from ‘Data.Monoid’ at src/Control/Monad/Plus.hs:68:1-18
Error: cabal: Failed to build monadplus-1.4.3 (which is required by
Agda-2.5.2). See the build log above for details.
```
Can we tighten the version bound to `monadplus >= 1.4 && < 1.4.3`? (Unless this is fixed upstream, of course.)

**Comment by asr** [comment]
You can use the following command: 

```
cabal install --constraint=monadplus==1.4.2
```

**Comment by ocharles** [comment]
Does Agda really need to support GHC 8.0? Nonetheless this wasn't meant to break anything, so I'll try and release another point release and deprecate 1.4.3

**Comment by asr** [comment]
Note that the OP is about Agda 2.5.2 released six year ago. We are planning to remove support for GHC 8.0.* after the release of Agda 2.6.3 (see #6309).

**Comment by wenkokke** [comment]
> Does Agda really need to support GHC 8.0? Nonetheless this wasn't meant to break anything, so I'll try and release another point release and deprecate 1.4.3

This is mostly about continuing to be able to build legacy versions of the language. GHC 8.0 is the latest GHC version that still builds Agda 2.5.2.

**Comment by asr** [comment]
> Can we tighten the version bound to `monadplus >= 1.4 && < 1.4.3`?

I'll wait for the new point release of `monadplus`.

**Comment by andreasabel** [comment]
In my analysis (https://github.com/hanshoglund/monadplus/issues/8), `monadplus-1.4.3` just lacked bound `base >= 4.11` which I supplied in a revision: https://hackage.haskell.org/package/monadplus-1.4.3/revisions/

This should fix the problem at hand, with no further changes needed from either side: No revision of our bounds on `monadplus` necessary, no rerelease of `monadplus` necessary.

@wenkokke : Would you confirm the problem is solved (after a `cabal update`)?

**Comment by andreasabel** [comment]
Fixed upstream.

**Comment by wenkokke** [comment]
Can confirm this fixed the issue!
