### ISSUE TITLE
Don't define dependencies for elisp files included in the agda2-mode package

### ISSUE THREAD

**Issue by khibino** [agda/agda#6448]
Sorry if I misunderstood the behavior of `package.el`.

Even though the elisp files (`eri.el` and `annotation.el`) are included in the agda2-mode package, is it a good practice to define the dependencies as follows?

https://github.com/agda/agda/pull/4858/commits/93f8a58d994dee30c61f3d02bcb1ae592db44417
https://github.com/agda/agda/pull/4858/commits/c4971af30032c922093a9de7e33dc6f42bad35ec
https://github.com/agda/agda/pull/4858

Probably because `package.el` assumes that `eri.el` and `annotation.el` are outside the agda2-mode package, which triggered the following loading error on Debian systems, for example.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1017415

To solve this issue, a change has been made in the Debian system to remove the dependency definitions.

https://salsa.debian.org/haskell-team/DHG_packages/-/blob/0bd9a38ae10e14ad1f9c2a03583e7d9bb18536c6/p/agda/debian/patches/agda-mode-deps

**Comment by andreasabel** [comment]
I am lacking the expertise here.
@jappeace : Would you like to comment?

**Comment by jappeace** [comment]
I added those in light of the comments of the melpa maintainer, this discussion: https://github.com/melpa/melpa/pull/7080

so yes, if eri and annotation are considered seperate on their own.
but since agda mode is no longer on melpa, you may as well remove these if it causes trouble for debian.

**Comment by andreasabel** [comment]
@khibino : Please open a PR with changes if you think we should change `package.el` here.  (Won't make it into 2.6.3, but could be in the next release then.)

**Comment by khibino** [comment]
I am in the hospital for a sudden illness and have not yet received a PC that I can work on, so I need to wait a couple of days.

**Comment by andreasabel** [comment]
@khibino wrote:
> I am in the hospital for a sudden illness

Sorry to hear.  I hope the doctors take good care of you.  Speedy recovery!
Don't worry about this issue now.

**Comment by phikal** [comment]
On this topic, it is actually not necessary (or even idiomatic) to manually write the `-pkg.el` file manually.  GNU and NonNGU ELPA will generate it automatically from the package metadata contained in the main file, which is the right place to specify the dependency list.   I do not know if Debian requires this file to be given?

**Comment by andreasabel** [comment]
I merged @khibino 's PR now so we can test it in the community.
