### ISSUE TITLE
Is `patternToExpr` correctly defined?

### ISSUE THREAD

**Issue by nad** [agda/agda#6451]
I wonder if the following undocumented function is correctly defined:

https://github.com/agda/agda/blob/1fd9e2693beec154cc3c188f5c12f2af0ed254e1/src/full/Agda/Syntax/Abstract.hs#L995-L1010

Should the pattern `x@_` really be translated to a meta-variable?

**Comment by jespercockx** [comment]
Where is this function actually used?

**Comment by andreasabel** [comment]
Here: :-P
```
find .  -exec grep  -nH --null -e patternToExpr \{\} 
./TypeChecking/Rules/Application.hs:152:          let p' = A.patternToExpr p
./Syntax/Abstract/Pattern.hs:268:substPattern s = substPattern' (substExpr $ map (second patternToExpr) s) s
./Syntax/Translation/InternalToAbstract.hs:398:                   then return $ A.patternToExpr $ namedArg $ indexWithDefault __IMPOSSIBLE__ ps n
```
@nad: Where do you experience problems "in the wild" or in a constructed test?

**Comment by jespercockx** [comment]
As long as it is only used for pretty-printing I do not really see the harm.

**Comment by nad** [comment]
> @nad: Where do you experience problems "in the wild" or in a constructed test?

I don't.

The use of `patternToExpr` in `reifyDisplayFormP` was added by you (9f8cf6c440efed0d2017978c85fcbb5199a59bbd), but I don't think any test case was added. The relevant issue (#1177) includes some attachments, but the links to those attachments are broken.

> As long as it is only used for pretty-printing I do not really see the harm.

The function is used by `expandPatternSynonyms`, which is used when translating concrete syntax to abstract syntax. It is also used by `checkApplication`, in the case for pattern synonyms. As patterns are not allowed in pattern synonyms, so perhaps that is fine.
