### ISSUE TITLE
Switch Agda versioning scheme to odd-only

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#6467]
Lifted from https://github.com/agda/agda/issues/6445#issuecomment-1396638834:

Our `2.6.3` RC versioning is slightly confusing.  E.g. `2.6.2.2.20230105` could also mean this is a RC for `2.6.2.3`.
If version numbers were lists of integers rather than naturals, there would be no ambiguity as one could have `x.y.z.-1.date` as a RC  for `x.y.z`.

I think we have discussed this problem on and off in the past without satisfactory solution.  The only systematic approach was to only use odd version numbers (`2.any.odd[.odd]`) so that the even ones can be used for RCs.  We did this in `2.5.1.1` but then immediately dropped this solution in the next release `2.5.2`.

I think `stack` uses the odd-only versioning scheme.

Switching to odd-only would mean that now
- `2.6.4` is a dev version
- `2.6.4.date` could be release candidates for next major version `2.6.5`
- `2.6.5.0.date` could be release candidates for `2.6.5.1`
- subsequent minor releases would be `2.6.5.1`, `2.6.5.3` etc
- next dev version would be `2.6.6` etc.

If we switch this "in flight", meaning in 2.6, it might look odd that we have `2.6.0` and `2.6.2`, but then no `2.6.4` but only the odd ones [`2.6.1`,] `2.6.3`, `2.6.5`, `2.6.7`,...  It might be less confusing if we also do a 2nd digit bump next time, so `2.7.0.date` as RC and `2.7.1` as next release.

**Comment by asr** [comment]
Does it mean that after releasing 2.6.3 the version in the `master` branch should be `2.7.0`?

**Comment by andreasabel** [comment]
> Does it mean that after releasing 2.6.3 the version in the `master` branch should be `2.7.0`?

No, let's first have a discussion.  There is no need to rush this bump.

**Comment by andreasabel** [comment]
Alternatively, we could use large minor numbers (e.g.`10` or `100`) to indicate a major number switch:
| RC | next |
|---|---|
| 2.6.3.10.date | 2.6.4
| 2.6.4.0.date | 2.6.4.1
| 2.6.4.1.date | 2.6.4.2
| 2.6.4.10.date | 2.6.5
| 2.6.10.date | 2.7.0
| 2.7.0.0.date | 2.7.0.1
| 2.7.0.10.date | 2.7.1

Ping @asr @jespercockx @plt-amy @nad

**Comment by andreasabel** [comment]
Actually, we could just continue as we did with some discipline:
| RC | next |
|---|---|
| 2.6.3.0.date | 2.6.3.1
| 2.6.3.date | 2.6.4
| 2.6.4.0.date | 2.6.4.1
| 2.6.4.1.date | 2.6.4.2
| 2.6.4.date | 2.6.5
| 2.6.date | 2.7.0
| 2.7.0.0.date | 2.7.0.1
| 2.7.0.date | 2.7.1

Because "date" (e.g. 20230327) is a large number acting somewhat as infinity, we can regard e.g. `2.6.date` as the immediate predecessor of `2.7.0`.
