### ISSUE TITLE
Internal error due to display pragma which is not type-correct

### ISSUE THREAD

**Issue by nad** [agda/agda#6476]
When I load the following code and normalise `r` I get an internal error:
```agda
open import Agda.Builtin.Nat

record R : Set where
  constructor c
  field
    m n : Nat

{-# DISPLAY c m = m #-}

r : R
r = c zero zero
```
```
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/Substitute.hs:87:26 in Agda-2.6.4-…
```
It seems as if Agda tries to apply a literal to something:

https://github.com/agda/agda/blob/4f6a502210fec599501f4e695006047ec9706a2a/src/full/Agda/TypeChecking/Substitute.hs#L67-L97

**Comment by andreasabel** [comment]
Display forms are not type-checked. You get GIGO, garbage-in-garbage-out.  If you look at how you want to display `r`, it is exactly `0 0` which applies a literal.

**Comment by andreasabel** [comment]
Here is a version that does not need interaction:
```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Equality

record R : Set where
  constructor c
  field
    m n : Nat

{-# DISPLAY c m = m #-}

r : R
r = c zero zero

test : c 0 0 ≡ c 1 1
test = refl
```

**Comment by nad** [comment]
> Display forms are not type-checked.

Yes, but is there a good reason for this? In fact, should one not check that the two sides are definitionally equal?

**Comment by andreasabel** [comment]
That would defeat the purpose of display forms, I think.  It is a hack to simplify Agda's output in away you want to read it.  
If it was up to me, I'd remove the DISPLAY pragma tomorrow.

**Comment by andreasabel** [comment]
Your example produces the same error back to 2.5.1.1, and a parse error for 2.4.2.5.  It is not a regression.

**Comment by andreasabel** [comment]
Btw the docs clearly state that `DISPLAY` pragmas are not type-checked: https://agda.readthedocs.io/en/v2.6.2.2/language/pragmas.html#display-pragma
However, they don't say that ill-typed display forms can make Agda crash.  Maybe stating this is enough to fix this issue.

This is the line where the application of the display-form rhs (`0`) to the remaining arguments (`0`) happens: https://github.com/agda/agda/blob/4f6a502210fec599501f4e695006047ec9706a2a/src/full/Agda/TypeChecking/DisplayForm.hs#L134
Maybe you find a way to throw an error here without much effort that is not an internal error.

**Comment by nad** [comment]
> If it was up to me, I'd remove the DISPLAY pragma tomorrow.

I'm fine with this.

**Comment by andreasabel** [comment]
It not just up to us two, I am a afraid...
