### ISSUE TITLE
Restrict workflow `stack.yml` to release branches?

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#6480]
The `stack.yml` workflow produces a 300 MB cache entry per instance.  We are currently running 11 instances (9 Linux, 1 macOS, 1 Windows), amounting to around 3.5 GB.  So open each PR needs alone 3.5 GB only for `stack.yml`, adding to the 3.5 GB for the `master` branch.  We have only 10 GB in total.  So with 2 PRs open we are busted already.

<img width="578" alt="Screenshot 2023-01-25 at 22 10 56" src="https://user-images.githubusercontent.com/1155218/214691773-1125a9fb-2a1b-4a5f-b0af-6c7b84aaa423.png">

We are planning to drop support for GHC 8.0/2/4 but this will only reduce the space need for a `stack.yml` instance by 1 GB.

How about dropping the `stack.yml` from `master` and only run in on `release-*` and maybe some special trigger like `ci-stack-*`?
The `stack-*.yaml` files might get stale, but they could be brought up-to-date just before the release.

What do you think? @asr @L-TChen 

Note that multi-GHC buildability is already covered by the `cabal.yml` workflows.

**Comment by nad** [comment]
Would it suffice to run the Stack tests when Agda.cabal or one of the Stack configuration files have changed, or a new Stack config file has been added?

**Comment by andreasabel** [comment]
> Would it suffice to run the Stack tests when Agda.cabal or one of the Stack configuration files have changed, or a new Stack config file has been added?

This would be an option we can try first, expecting that these files are rather stable.

**Comment by andreasabel** [comment]
The cabal workflow needs to do all the special builds now that were only happening in the stack workflow (cpphs, debug, ...).
