### ISSUE TITLE
Unnecessary `stack.yml` workflow instances

### ISSUE THREAD

**Issue by asr** [agda/agda#6486]
In relation to reduce the cache used by the `stack.yml` workflow (see #6480), I only modified the files `stack-9.2.5.yaml` and `stack-9.4.yaml` in PR #6485, but the `stack.yml` workflow ran *all* the 11 instances (9 Linux, 1 macOS, 1 Windows) instead of running *only* the instances related to GHC 9.2.5 and 9.4.4.

**Comment by andreasabel** [comment]
> running _only_ the instances related to GHC 9.2.5 and 9.4.4.

This should be somehow possible, but github actions are an awkward programming language.
There might be actions that can help with that: e.g. https://github.com/dorny/paths-filter
Let me give it a try...

**Comment by andreasabel** [comment]
Ok so what should the specs be exactly?  When do we want to run which build?
1. When `stack-x.y.z.yaml` changed, build Agda with stack and GHC `x.y.z` on Linux (or all three OSs?).
2. When any other of the trigger files changed (like `Agda.cabal`)  build the whole matrix.
3. On `workflow_dispatch`, build the whole matrix.

One solution would be to separate 1 from 2+3.  The latter would be the workflow we have no with the `stack*.yaml` trigger removed.  The former would get its matrix from the changed `stack-*.yaml` files (that we have to parse into GHC versions).
In this solution, there could be duplicate effort if both `Agda.cabal` and a `stack -*.yaml` file changed.

Another solution would be to prefix _every step_ of the current `stack.yml` action with a conditional mentioning a suitable boolean combination of triggers 1-3.  This would be quite ugly code and prone to introduction of errors.  It is really a pity that GHA does not support early exits from jobs.

Maybe there is an elegant solution.  Atm, I am not convinced to implement any of my proposed solutions.
