### ISSUE TITLE
Limit `stack` support to GHC 9.x

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#6496]
Now that we do the bulk CI on `cabal` rather than `stack`, we can drop `stack` support for GHC 8.x and just test it on GHC 9.x.  Reason:
- Agda development should take place on GHC 9 only, because important warnings are switched off on GHC 8
- To get into Stackage, we only need to support the GHC version for Stackage nightly (GHC 9.4.4)
- Users that want to install Agda from Stackage are GHC-version independent (because stack can install GHC), so there is no need to support old GHC versions for them
- CI using `stack` is expensive in terms of cache usage; the less GHC versions we test routinely with the `stack` CI, the better our CI will behave e.g. in case of multiple parallel PRs (each of which has their own cache instance, but our total cache is limited to 10 GB)

The only reason for retaining stack support on old GHCs is for developers that want to use _Agda as a library_ on an old GHC.  However, I find it improbable that someone wants the latest Agda API but a GHC that is older than the last 3 major versions.  I would be happy to disregard such exotic cases and wait for complaints.

A less revolutionary step would be to limit CI for GHC 8.x to `stack build --dry-run` so that it only checks whether all of the dependencies are in the snapshots.  (Buildability is already checked with `cabal`.)

**Comment by L-TChen** [comment]
Yes, it sounds good to me. More radically, we may only leave the stack configuration files for the most recent Stackage LTS and nightly in the codebase.
