### ISSUE TITLE
Lossy Unification Fails with Universe Level?

### ISSUE THREAD

**Issue by DKXXXL** [agda/agda#6512]
I have tried this in 
1. nightly agda just downloaded -- Agda version 2.6.4-8d4416a
2. my local Agda (version 2.6.2.2) 
3. and the current Agda pad (version 2.6.3), 
all fail.

TBH I am not sure if this is expected behaviour of lossy unification or not. 

```agda
{-# OPTIONS --lossy-unification #-}
module hello where

open import Level 
open import Agda.Builtin.Equality
open import Agda.Primitive

coe :  ∀{ℓ}{A B : Set ℓ} → A ≡ B → A → B 
coe refl a = a

infixl 5 _▷_
infixl 7 _[_]T 
infix  6 _∘_


variable 
  i j k l : Level


postulate
  Con   : ∀ i → Set (suc i)
  Ty    : ∀ (j : Level)(Γ : Con j) i → Set (suc i ⊔ j)
  _▷_   : ∀ {i}(Γ : Con i){j}(A : Ty _ Γ j) → Con (i ⊔ j)
  Tms   : ∀ {i}(Γ : Con i){j}(Δ : Con j) → Set (i ⊔ j)
  -- Tm    : ∀ {i}(Γ : Con i){j}(A : Ty _ Γ j) → Set (i ⊔ j)
  _[_]T : ∀ {i}{Δ : Con i}{j}(A : Ty _ Δ j){k}{Γ : Con k}(σ : Tms Γ Δ) → Ty _ Γ j
  Π : ∀{i}{Γ : Con i}{j}(A : Ty _ Γ j){k}(B : Ty _ (Γ ▷ A) k) → Ty _ Γ (j ⊔ k)

variable 
  Γ  : Con _

postulate
  _∘_   : ∀{i}{Θ : Con i}{j}{Δ : Con j}{l}{Γ : Con l}
          (σ : Tms Θ Δ)(δ : Tms Γ Θ) → Tms Γ Δ
  p₁ :  ∀{i}{Γ : Con i}{k}{A : Ty _ _ k} → Tms (Γ ▷ A) Γ


-- this one succeed
level_equal : {i j k : Level} (Γ : Con k) → 
                 (Ty _ Γ (i ⊔ j)) ≡ (Ty _ Γ (i ⊔ (i ⊔ j ⊔ j)))
level_equal Γ =  refl

RecSig1 : (A : Ty _ Γ i) → (B : Ty _ (Γ ▷ A) i) → (R : Ty _ Γ j) → Ty _ Γ (i ⊔ j)
          -- this one fails
RecSig1 A B R =  (Π A ( Π (Π B (R [ p₁ ∘ p₁ ]T)) (R [ p₁ ∘ p₁ ]T)))

RecSig2 : (A : Ty _ Γ i) → (B : Ty _ (Γ ▷ A) i) → (R : Ty _ Γ j) → Ty _ Γ (i ⊔ (i ⊔ j ⊔ j))
          -- this one works
RecSig2 A B R = Π A ( Π (Π B (R [ p₁ ∘ p₁ ]T)) (R [ p₁ ∘ p₁ ]T))

RecSig3 : (A : Ty _ Γ i) → (B : Ty _ (Γ ▷ A) i) → (R : Ty _ Γ j) → Ty _ Γ (i ⊔ j)
          -- this one also succeed, just by adding coe refl
RecSig3 A B R = coe refl (Π A ( Π (Π B (R [ p₁ ∘ p₁ ]T)) (R [ p₁ ∘ p₁ ]T)))

 

``` 
I also make the code piece in this [gist](https://gist.github.com/DKXXXL/e0ca99b58729a61911381c79a1d47615).

This above code can pass once I commented out RecSig1 or just do not use lossy-unification

**Comment by DKXXXL** [comment]
Side note : In case of the possible implicit in Ty (that is causing difference), I printed out the implicit here
<img width="467" alt="image" src="https://user-images.githubusercontent.com/16682424/219984432-ba935790-a97e-4363-855e-9c2534a5bf5b.png">
refl can be filled in, and gives us RecSig3.

**Comment by jespercockx** [comment]
Lossy unification is called lossy because it means it might lose some solutions. Do you have a reason why you think it should work in this case in particular?

**Comment by DKXXXL** [comment]
> Lossy unification is called lossy because it means it might lose some solutions. Do you have a reason why you think it should work in this case in particular?

The main reason for me is the behaviour inconsistency. 
1. The two types `Ty Γ (i ⊔ j)` and `Ty Γ (i ⊔ (i ⊔ j ⊔ j))` are sometimes judgementally equal (at `level_equal`) and sometimes not (at `RecSig1` vs. `RecSig2`).  
2. I also think `coe refl a` should be judgementally equal to `a`, but it is not (`RecSig3` pass type check but `RecSig1` doesn't).

Though I do have very limited knowledge of the specification and the implementation of Lossy Unification. 
But in my understanding of Lossy Unification, the problem is when unify `Ty Γ (i ⊔ j)` and `Ty Γ (i ⊔ (i ⊔ j ⊔ j))` it should directly goes to `Γ = Γ` and `(i ⊔ j) = (i ⊔ (i ⊔ j ⊔ j))`, but the latter will try to further unify `j` with ` (i ⊔ j ⊔ j)` and thus failed. However, this doesn't explain why the Top level `level_equal` succeeded. If the reason makes `level_equal` succeed can also make `RecSig1` pass type check, it would be great.

**Comment by jespercockx** [comment]
Are you actually getting a type error saying that `Ty Γ (i ⊔ j)` and `Ty Γ (i ⊔ (i ⊔ j ⊔ j))` are not equal? That would definitely be considered to be a bug, regardless of whether `--lossy-unification` is enabled. The same holds for `coe refl a` being unequal to `a`. In particular, you could try to fill in the implicit arguments in your code with explicitly given terms, and see if that makes the problem disappear.

**Comment by DKXXXL** [comment]
> Are you actually getting a type error saying that `Ty Γ (i ⊔ j)` and `Ty Γ (i ⊔ (i ⊔ j ⊔ j))` are not equal? 

Not exactly. _In this example_, no, I get something like this
<img width="502" alt="image" src="https://user-images.githubusercontent.com/16682424/220144074-d95a1bb5-df79-4710-80fd-4ec2cfa59e8a.png">

Now I see your point. It is possible that the "problem" lies in type inference, where without `coe refl` the inferred type is incorrect because the implicit argument filled in `Π` is incorrect. I think you are right, with appropriate implicit argument filled in, this problem will go away. 

***
However, in my original workload it does have this kind of error. 
But still it is possible due to unprinted implicit.
<img width="482" alt="image" src="https://user-images.githubusercontent.com/16682424/220149301-fa7d45bb-d15a-41c4-b6a0-47449332d1dd.png">
![image](https://user-images.githubusercontent.com/16682424/220149365-5455512b-9d8c-4d42-921e-a94eddee803e.png)
let me take a close look at them and carve a better minimal example if there is one. I will reopen this issue for sure. Thanks for the help!
