### ISSUE TITLE
Soundness bug: Tick constraints not properly propogated in Guarded Cubical

### ISSUE THREAD

**Issue by JoeyEremondi** [agda/agda#6523]
* [x] My report includes the version of Agda (and Emacs, GHC, and OS versions where relevant).

Agda 2.6.3

* [x] The issue can be reproduced with the _latest version_ of Agda (either [released](https://wiki.portal.chalmers.se/agda/Main/Download) or `master` branch).
      Note: We do not fix issues in older versions of Agda.

Yes (see above)

* [x] I have supplied all information so the bug can be easily reproduced (in particular, the reproducer is a complete Agda file).

See below

---

There is a soundness bug in guarded cubical Agda.
Essentially, you can pass a `Tick` as an argument outside of the `@tick` modality. This lets you circumvent the context checks that the `@tick` modality does access things in the future sooner than should be possible.

The consequence of this is that you can implement a monadic join for the Later modality, which is supposed to be forbidden.

Here's a complete working example showing how join can be implemented.

Expected behavior: the call to `untic` raises an error about using a `@tick` argument in the wrong context.

Actual behavior: file type checks successfully.

The file:

```agda
{-# OPTIONS --cubical --guarded #-}
module GuardedBug where

----------------------------------
-- Guarded primitives from https://github.com/agda/agda/blob/172366db528b28fb2eda03c5fc9804f2cdb1be18/test/Succeed/LaterPrims.agda

open import Agda.Primitive
open import Agda.Primitive.Cubical renaming (itIsOne to 1=1)
open import Agda.Builtin.Cubical.Path
open import Agda.Builtin.Cubical.Sub renaming (Sub to _[_↦_]; primSubOut to outS)

module Prims where
  primitive
    primLockUniv : Set₁

open Prims renaming (primLockUniv to LockU) public

private
  variable
    l : Level
    A B : Set l

-- We postulate Tick as it is supposed to be an abstract sort.
postulate
  Tick : LockU

▹_ : ∀ {l} → Set l → Set l
▹_ A = (@tick x : Tick) -> A

▸_ : ∀ {l} → ▹ Set l → Set l
▸ A = (@tick x : Tick) → A x

next : A → ▹ A
next x _ = x

_⊛_ : ▹ (A → B) → ▹ A → ▹ B
_⊛_ f x a = f a (x a)

----------------------------------
-- The bug

untic : ∀ {ℓ} {X : Set ℓ} → (x : Tick) → ▹ X → X
untic tic x = x tic

-- This shouldn't be possible for Later
-- The call to untic should be forbidden
join : ∀ {A : Set} → ▹ (▹ A) → ▹ A
join x tic = untic tic (x tic)

```

**Comment by andreasabel** [comment]
Mmh, I wonder who is maintaining Guarded Cubical Agda now? @Saizan @plt-amy @jespercockx @nad

**Comment by plt-amy** [comment]
I think nobody is. I can look into this one, but I'm not too familiar with the tick modality.. yet(?) @JoeyEremondi is the bug really with using an `@tick` argument in an unmarked context? Or is using an unmarked argument in an `@tick` context suspicious too? That hapens in the definition of `untic`, as I see it.
