### ISSUE TITLE
Guarded can block on solved metas

### ISSUE THREAD

**Issue by plt-amy** [agda/agda#6528]
```agda
{-# OPTIONS --guarded #-}
module Test55 where

primitive primLockUniv : Set₁
postulate Tick : primLockUniv

ex : ∀ {A : Set} → (@tick Tick → A) → @tick Tick → A
ex f x = f {! x !}
```

Giving the value in the hole results in the `__IMPOSSIBLE__` from blocking on a solved meta since (I'm guessing, I didn't investigate yet) the lock-argument constraint gets added, instead of discharged, regardless of the interaction point being solved.

**Comment by andreasabel** [comment]
@plt-amy : Are you intending to fix this for 2.6.4?

**Comment by plt-amy** [comment]
Yes.

**Comment by andreasabel** [comment]
Is the following issue related?
- #6693

**Comment by andreasabel** [comment]
@plt-amy says "No, that's different".
