### ISSUE TITLE
Type checker performance regression surfacing in `cubical`

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#6535]
The `cubical` library has balooned to a checking time of 40-50 minutes in CI, see e.g. https://github.com/agda/agda/actions/runs/4431902203/jobs/7775631935.
This seems unsustainable. We need to find a solution.

**Comment by andreasabel** [comment]
@ecavallo @felixwellen : Is a build time of >40min for `cubical` the norm or is it a recent regression in Agda?

**Comment by andreasabel** [comment]
@jespercockx: It seems like after https://github.com/agda/agda/pull/6516 the type-checking time for cubical degraded by 50% , 
- from 27min https://github.com/agda/agda/actions/runs/4357166652 
- to 40min https://github.com/agda/agda/actions/runs/4373684915
- https://github.com/agda/agda/pull/6516

**Comment by jespercockx** [comment]
Ah, I'll take a look and see if I can find the cause.

**Comment by jespercockx** [comment]
It's back to 29 minutes with https://github.com/agda/agda/actions/runs/5016375238/jobs/8993896433?pr=6647

**Comment by andreasabel** [comment]
Great, only that it is sad to having to revert your work. :-(
