### ISSUE TITLE
Internal error in Agda.TypeChecking.Reduce.Fast

### ISSUE THREAD

**Issue by nad** [agda/agda#6541]
Using Agda 2.6.4-35a4fbf48b508e1b5a2eddd7dcc5f330d42ab510:
```
$ mkdir fresh && cd fresh > /dev/null
$ (git clone https://github.com/agda/agda-stdlib.git && cd agda-stdlib && git checkout v1.7.2) >& /dev/null
$ (git clone https://github.com/fhlkfy/logrel-mltt && cd logrel-mltt && git checkout d528b80aebec2268a11818cf125253e9ea83f672) >& /dev/null
$ printf '\nname: logrel-mltt' >> logrel-mltt/logrel-mltt.agda-lib
$ cat > libraries <<EOF
$PWD/agda-stdlib/standard-library.agda-lib
$PWD/logrel-mltt/logrel-mltt.agda-lib
EOF
$ cat > Bug.agda <<EOF
module _ (_ _ _ _ _ _ : Set) where

open import Definition.Modality.Instances.Erasure
open import Definition.Typed.EqualityRelation
open import Tools.Nat
open import Tools.Product

open import Definition.LogicalRelation Erasure′
open import Definition.LogicalRelation.Properties.Escape Erasure′
open import Definition.LogicalRelation.Substitution Erasure′
open import Definition.LogicalRelation.Substitution.Properties Erasure′
open import Definition.LogicalRelation.Substitution.Introductions.Pi
  Erasure′
open import Definition.Typed Erasure′
open import Definition.Untyped Erasure

instance
  postulate
    eq : EqRelSet Erasure′

postulate
  ⊩ℕ′ : ε ⊩ᵛ⟨ ⁰ ⟩ ℕ / ε
  ⊩ℕ″ : ε ∙ ℕ ⊩ᵛ⟨ ⁰ ⟩ ℕ / ε ∙ ⊩ℕ′

⊩Πℕℕ : ε ⊩ᵛ⟨ ⁰ ⟩ Π 𝟘 , 𝟘 ▷ ℕ ▹ ℕ / ε
⊩Πℕℕ = Πᵛ ε ⊩ℕ′ ⊩ℕ″

postulate
  ⊩ℕ‴  : ε ∙ (Π 𝟘 , 𝟘 ▷ ℕ ▹ ℕ) ⊩ᵛ⟨ ⁰ ⟩ ℕ / ε ∙ ⊩Πℕℕ
  ⊩λ[] : ε ⊩ˢ (λ ()) ∷ ε / ε / ε

⊩Πℕℕ′ : ε ⊩⟨ ⁰ ⟩ subst {n = 0} (λ ()) (Π 𝟘 , 𝟘 ▷ ℕ ▹ ℕ)
⊩Πℕℕ′ = ⊩Πℕℕ .unwrap {σ = λ ()} ε ⊩λ[] .proj₁

⊢Πℕℕ : ε ⊢ subst {n = 0} (λ ()) (Π 𝟘 , 𝟘 ▷ ℕ ▹ ℕ)
⊢Πℕℕ = escape ⊩Πℕℕ′

_ : Set₁
_ = Set
  where
  _ = ⊩ℕ‴ .unwrap (ε ∙ ⊢Πℕℕ) (liftSubstS ε ε ⊩Πℕℕ ⊩λ[])
EOF
$ agda --no-default-libraries --library-file=libraries -lstandard-library -llogrel-mltt -i. --trace-imports=0 -vimpossible:10 Bug.agda
Incomplete pattern matching when applying Definition.LogicalRelation.Substitution._⊩ˢ_∷_/_/_
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/Reduce/Fast.hs:1394:20 in Agda-2.6.4-LNnNZYoVuOO7ZmhWM1BAdv:Agda.TypeChecking.Reduce.Fast
```
Using Agda 2.6.3:
```
$ agda --no-default-libraries --library-file=libraries -lstandard-library -llogrel-mltt -i. -vimport:0 -vimpossible:10 Bug.agda
Incomplete pattern matching when applying Definition.LogicalRelation.Substitution._⊩ˢ_∷_/_/_
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/Reduce/Fast.hs:1394:20 in Agda-2.6.3-bbbb4a42bdf9f34de5eb61018ec610b9f7c62624ae34e0ec31e7e39cba9e898e:Agda.TypeChecking.Reduce.Fast
```

**Comment by andreasabel** [comment]
Happy shrinking!

**Comment by nad** [comment]
Here is another piece of code that triggers the error (using Agda 2.6.3 and the same library dependencies as above):
```agda
module _ (_ _ _ _ : Set) where

open import Definition.Modality.Instances.Erasure
  using (Erasure; Erasure′; 𝟘)
open import Definition.Typed.EqualityRelation
  using (EqRelSet)

open import Definition.Typed Erasure′
  using (ε)
open import Definition.Untyped Erasure
  using (Term; ℕ; Π_,_▷_▹_; ε; _∙_; Subst)

instance postulate
  eq : EqRelSet Erasure′

open import Definition.LogicalRelation Erasure′ ⦃ eqrel = eq ⦄
  using (⁰)
open import Definition.LogicalRelation.Substitution Erasure′
  using (_⊩ᵛ⟨_⟩_/_; unwrap; _⊩ˢ_∷_/_/_; ε; _∙_)
open import Definition.LogicalRelation.Substitution.Introductions.Pi
  Erasure′ ⦃ eqrel = eq ⦄
  using (Πᵛ)

postulate
  ⊩ᵛℕ′ : ε ⊩ᵛ⟨ ⁰ ⟩ ℕ / ε
  ⊩ᵛℕ″ : ε ∙ ℕ ⊩ᵛ⟨ ⁰ ⟩ ℕ / ε ∙ ⊩ᵛℕ′

Πℕℕ : Term 0
Πℕℕ = Π 𝟘 , 𝟘 ▷ ℕ ▹ ℕ

⊩ᵛΠℕℕ : ε ⊩ᵛ⟨ ⁰ ⟩ Πℕℕ / ε
⊩ᵛΠℕℕ = Πᵛ ε ⊩ᵛℕ′ ⊩ᵛℕ″

postulate
  σ    : Subst 0 1
  ⊩ᵛℕ‴ : ε ∙ Πℕℕ ⊩ᵛ⟨ ⁰ ⟩ ℕ / ε ∙ ⊩ᵛΠℕℕ
  ⊩ˢσ  : ε ⊩ˢ σ ∷ ε ∙ Πℕℕ / ε ∙ ⊩ᵛΠℕℕ / ε

_ = ⊩ᵛℕ‴ .unwrap {σ = _} ε ⊩ˢσ
```
Some observations:
* The code is accepted if the final underscore is replaced by `σ`.
* If one underscore is removed from the parameter list `(_ _ _ _ : Set)`, then the internal error is not triggered.
* If the `instance` keyword is removed and the argument `⦃ eqrel = eq ⦄` is added after `open import Definition.LogicalRelation.Substitution Erasure′`, then the internal error is not triggered. Thus this error could have something to do with instance arguments.
* The error message points to the following code:

   https://github.com/agda/agda/blob/30f95d2de12cd19a4180a8172493413f9ebfe37c/src/full/Agda/TypeChecking/Reduce/Fast.hs#L1382-L1394

  Note the words "Bad work-around". When @UlfNorell closed issue #3870 he [wrote](https://github.com/agda/agda/issues/3870#issuecomment-788783666) the following:
  
  > A proper fix would be @vlopezj 's twin variable stuff, so closing this.
  
  The [commit](https://github.com/agda/agda/commit/237aa1f9ab2b5bead729d7d6c3695569186b4d8b) message contains more information:

  > Not blocking conversion checking when we should leads to ill-typed meta solutions. This sometimes manifests as missing case errors during reduction. To make the problem less severe (without actually fixing anything), I've disabled the impossible during reduction if we are currently doing instance search. This should mean that you can still hit the impossible in ill-typed code, but not in well-typed programs doing instance search.

  Note that the code above is not ill-typed: Agda accepts it if the final underscore is replaced by `σ`.

**Comment by liesnikov** [comment]
It seems that after #6626 the minimized example doesn't trigger IMPOSSIBLE anymore, but merely fails to solve constraints related to the implicit sigma-argument.

```
_σ_100
  : Definition.Untyped.Subst
    (Relation.Binary.Bundles.Setoid.Carrier Erasure′) 0 1
———— Errors ————————————————————————————————————————————————
Failed to solve the following constraints:
  σ (Data.Fin.Base.Fin.suc x) = _σ_100 (Data.Fin.Base.Fin.suc x)
    : Definition.Untyped.Term
      (Relation.Binary.Bundles.Setoid.Carrier Erasure′) 0
    (blocked on _σ_100)
  _σ_100 (Data.Fin.Base.Fin.suc x) = σ (Data.Fin.Base.Fin.suc x)
    : Definition.Untyped.Term
      (Relation.Binary.Bundles.Setoid.Carrier Erasure′) 0
    (blocked on _σ_100)
  σ Data.Fin.Base.Fin.zero = _σ_100 Data.Fin.Base.Fin.zero
    : Definition.Untyped.Term
      (Relation.Binary.Bundles.Setoid.Carrier Erasure′) 0
    (blocked on _σ_100)
```

The failure goes away if the sigma is filled in with a postulate, as it did previously.

**Comment by jespercockx** [comment]
I think the reason this error went away is because after my change the reduction machinery does no longer know or care about whether --rewriting is enabled, but if it is then Agda does not fail hard when it encounters an incomplete pattern match. Given that there are other known ways to trigger incomplete pattern matching without rewrite rules (see for example #3027), I think the new behavior is probably better anyway.
