### ISSUE TITLE
Doc: the keywords `hiding`,`public`, `renaming`, and `using` are always reserved

### ISSUE THREAD

**Issue by fredrik-bakke** [agda/agda#6551]
In the latest docs on lexical structure (https://agda.readthedocs.io/en/latest/language/lexical-structure.html), the words
`hiding`, `public`, `renaming`, `to`, and `using` are listed as only reserved keywords in connection with the `open` and `import` keywords.
However, testing this I found that this is only true for `to`. I.e., none of the following programs type check with Agda 2.6.3:
- ```agda
  hiding = Set
  ```
- ```agda
  public = Set
  ```
- ```agda
  renaming = Set
  ```
- ```agda
  using = Set
  ```
but this one does:
- ```agda
  to = Set
  ```

**Comment by andreasabel** [comment]
@fredrik-bakke Thanks for the report!
Indeed, this is already so since 2007! https://github.com/agda/agda/commit/9485444ae048f8f203b48c781845c24447966770#r106211321
