### ISSUE TITLE
A strange unsolved metas in Agda 2.6.3

### ISSUE THREAD

**Issue by mechvel** [agda/agda#6559]
This is on the type checker of  Agda 2.6.3 under ghc-9.2.1 (Ubuntu Linux 18.04).
See the attached file.

In the module Test1 there are proved `` (All P rows), (r ∈≋ rows), (P Respects _≋_)``,
and the functions  ``test, test'``  fail to derive  `(P r)`  from this.
Agda reports of  unsolved metas.
I do not see any argument to add to the function calls to help it to solve
the types, it looks like everything is already given.
This looks like a bug in Agda.

There is a composition of depth 3 of the type constructors Pol and List.
With changing this to a simpler type, everything becomes solved.
[Test.zip](https://github.com/agda/agda/files/11105705/Test.zip)

**Comment by andreasabel** [comment]
This isn't a bug, this is just the usual eager insertion of hidden arguments problem:
- #1079

This is how far I got in solving your problem (using standard library 1.7.1), you should be able to take it from here.
```agda
open import Algebra   using (Op₂)
open import Data.List using (List; []; _∷_)
import      Data.List.Membership.Setoid as Membership
open import Data.List.Relation.Binary.Pointwise as Pointwise using (_∷_)
open import Data.List.Relation.Unary.All using (All; []; _∷_; lookupₛ)
open import Data.List.Relation.Unary.Any using (Any)
open import Data.Nat                     using (ℕ)
open import Data.Nat.Properties using (<-cmp)
                                renaming (<-strictTotalOrder to natSTO)
open import Data.Product    using (_,_; ∃)
open import Level           using (0ℓ; _⊔_)
open import Function        using (flip; _on_)
open import Relation.Binary using (REL; Rel; Setoid; _Respects_;
                                                     StrictTotalOrder)
import      Relation.Binary.Construct.On as On
open import Relation.Binary.PropositionalEquality as PE using (_≡_)
open import Relation.Unary using (Pred)



-- **************************************************************************
module Ordered {α α= α<} (sto : StrictTotalOrder α α= α<)
  where
  -- About lists decreasing in any StrictTotalOrder.

  open StrictTotalOrder sto using (Carrier; _<_)

  _>_ :  Rel Carrier _
  _>_ =  flip _<_

  data DecrOrdered :  List Carrier → Set (α ⊔ α= ⊔ α<)
       where
       nil    : DecrOrdered []
       single : ∀ x → DecrOrdered (x ∷ [])
       cons   : ∀ {x y xs} → x > y → DecrOrdered (y ∷ xs) →
                                       DecrOrdered (x ∷ y ∷ xs)

-- ===========================================================================
module OfPol     -- About Pol. A contrived thing.
  where
  open Ordered natSTO using (DecrOrdered)

  record Pol :  Set
    where
    constructor mkPol

    field exps    : List ℕ
          ordered : DecrOrdered exps   -- e₁ > ... > eₙ

  polSetoid :  Setoid 0ℓ 0ℓ
  polSetoid =  On.setoid (PE.setoid (List ℕ)) Pol.exps

  infixl 2 _=ₚ_

  _=ₚ_ :  Rel Pol _
  _=ₚ_ =  Setoid._≈_ polSetoid

  0ₚ = mkPol [] DecrOrdered.nil

  infixl 6 _+ₚ_

  _+ₚ_ :  Op₂ Pol
  _ +ₚ _ =  0ₚ      -- a dummy thing, to demonstrate a bug

  _∣_ :  Rel Pol 0ℓ
  f ∣ g =  ∃ (\h → h +ₚ f =ₚ g)

  ∣-respˡ :  {f : Pol} → (_∣ f) Respects _=ₚ_
  ∣-respˡ {f} {g} {h} g=h (q , q+g=f) =  (q , q+g=f)


-- ===========================================================================
open Any
open OfPol

module Test1 (fs : List Pol)
  where
  Row : Set
  Row = List Pol

  setoid-Row :  Setoid 0ℓ 0ℓ
  setoid-Row =  Pointwise.setoid polSetoid
                -- setoid on rows with the pointwise equality

  open Setoid setoid-Row using ()
              renaming (_≈_ to _≋_; refl to ≋refl; sym to ≋sym)

  open Membership polSetoid using (_∈_)
                            -- for "f ∈ (list of pol-s)"

  open Membership setoid-Row using () renaming (_∈_ to _∈≋_)
                                   -- for "row ∈≋ (list of row-s)"

  _∈I_ : REL Pol Row 0ℓ
  f ∈I gs =  Any (_∣ f) gs   -- any in gs "divides" f

  _⊆I_ : Rel Row 0ℓ
  bs ⊆I cs =  {f : Pol} → f ∈I bs → f ∈I cs

  ∈I-resp≋ :  {f : Pol} → (f ∈I_) Respects _≋_

  ∈I-resp≋ {f} {g ∷ _} {h ∷ _} (g=h ∷ _) (here g∣f) =  here h∣f
                                where
                                h∣f =  ∣-respˡ {f} {g} {h} g=h g∣f
  ∈I-resp≋ {f} (_ ∷ gs≈hs) (there any-gs∣f) =
                           there (∈I-resp≋ {f} gs≈hs any-gs∣f)


  ⊆I-respˡ≋ :  ∀ {fs : Row} → (_⊆I fs) Respects _≋_
  ⊆I-respˡ≋ {fs} {gs} {hs} gs≋hs gs⊆I-fs {x} x∈I-hs =
                          gs⊆I-fs {x} x∈I-gs
                     where
                     x∈I-gs :  x ∈I gs
                     x∈I-gs =  ∈I-resp≋ {x} (≋sym gs≋hs) x∈I-hs

  P :  Pred Row 0ℓ
  P f =  f ⊆I fs

  P-resp≋ :  {r r' : Row} → r ≋ r' → P r → P r'    -- P Respects _≋_
  P-resp≋ =  ⊆I-respˡ≋


  test :  (row : Row) (rows : List Row) → All P rows →
                                           row ∈≋ rows → P row

  test r (r' ∷ rs) (P[r'] ∷ allPx-rs) (here r≋r') {f = f} f∈R = P[r] {f = f} f∈R
                   where
                   r'≋r :  r' ≋ r
                   r'≋r =  ≋sym {r} {r'} r≋r'

                   P[r] :  P r
                   P[r] {f = f'} =  P-resp≋ {r'} {r} r'≋r (P[r'] {f = {!!}}) {f = f'}

  test r (r' ∷ rs) (P[r'] ∷ allP-rs) (there r∈≋rs) {f = f} =
                                     test r rs allP-rs r∈≋rs {f = f}
```

**Comment by mechvel** [comment]
> This is how far I got in solving your problem (using standard library 1.7.1), you should be able to take i
> it from here.

Thank you. I failed with filling the hole for {!!} by C-c C-a. It reports "Not implemented".
I do not see what to set for {!!}.
Generally, the subject with hidden arguments becomes here brain-twisting.
Therefore I change my definition for  `_⊆I_` to  
```
    bs ⊆I cs =   (f : Pol) → f ∈I bs → f ∈I cs,
```
where  `f` is now explicit. Than Agda reports of several points where it is needed either to remove an implicit argument in a call or to change it to explicit. After this, Agda type-checks the initially intended goal of 
```
  test' :  (row : Row) (rows : List Row) → All P rows →  row ∈≋ rows → P row
  test' row rows all-P-rows row∈rows =
                           lookupₛ setoid-Row  {P = P}   (\{r r' : Row} → P-resp≋ {r} {r'})
                                                                all-P-rows {row} row∈rows
```
My approach is now:  meeting a difficult problem with unsolved metas, one needs to change to explicit argument in the last user definition before the goal.
?
But there are many Standard definitions that use implicits. So the user has to hope that he would not  need to add their explicit analogues.

**Comment by mechvel** [comment]
This is not a bug, but it probably frighten the programmers.  
They would think that they need to search for some different style with using implicit arguments.

**Comment by andreasabel** [comment]
A good strategy to help the Agda unifier is to use `data` types or `no-eta-equality` `record` types like Haskell uses `newtype`:
```agda
record _⊆I_ : (bs cs : Row) : Set 0ℓ where
  no-eta-equality; constructor mk⊆I 
  field use⊆I : {f : Pol} → f ∈I bs → f ∈I cs
```
In my experience, this helps Agda with hidden arguments.

In general, here is a nice tutorial on Agda's inference capabilities: https://github.com/effectfully/inference-in-agda/blob/master/InferenceInAgda.lagda.md

**Comment by mechvel** [comment]
Thank you for explanation.
I try `data` in this example. First, 
(I) was  ``bs ⊆I cs =  {f : Pol} → f ∈I bs → f ∈I cs``,  and this lead to failing to fix unsolved metas, to complications.
(II) was making  `f` explicit.  This solves unification, under a certain complication of the code.
Finally 
(III) is 
```
data _⊆I_ (bs cs : Row) :  Set
    where
    ⊆i :   ({f : Pol} → f ∈I bs → f ∈I cs) → bs ⊆I cs
```
Is this your idea?
Now,  ``⊆I-respˡ≋ :  ∀ {fs : Row} → (_⊆I fs) Respects _≋_``
is implemented as
```
⊆I-respˡ≋ {fs} {gs} {hs} gs≋hs (⊆i gs⊆I[fs]) =
                                     ⊆i (\{x} → hs⊆I[fs] {x})
     where
     hs⊆I[fs] =  \{x} x∈I[hs] →
                        let x∈I[gs] =  ∈I-resp≋ {x} (≋sym gs≋hs) x∈I[hs]
                       in   gs⊆I[fs] {x} x∈I[gs]
```
This uses `_⊆I_` and also its constructor `⊆i` to pattern-match.
To my mind, (III) looks a bit better than (II).
Generally, simplicity is very important in application programs. 
For example, the author has sometimes to read one's own program ...

**Comment by andreasabel** [comment]
Yes, this the idea (III).
Also, if Agda regularly cannot infer a hidden argument of a function, I make it explicit.
