### ISSUE TITLE
Case split a `where` pattern matching lambda fails

### ISSUE THREAD

**Issue by L-TChen** [agda/agda#6563]
On Emacs, if case split is invoked within a `where` pattern matching lambda, then everything before `where` is erased regardless of its layout. For example, in the following example, if I invoke case split inside the hole
```agda
open import Agda.Builtin.Nat

_ : Nat → Nat
_ = λ where n → {! !}
```
then I get

```agda
open import Agda.Builtin.Nat

_ : Nat → Nat
zero → ?
(suc n) → 
```
instead of 
```agda
_ : Nat → Nat
_ = λ where zero    → {!!}
            (suc n) → {!!}
```
or anything valid. 
 
Tested with Agda 2.6.3 and Emacs 28.2 (9.0) on macOS 13.3.

---

Please make sure it is actually a problem with Agda or its documentation. For user questions, the [mailing list](https://lists.chalmers.se/mailman/listinfo/agda) or the [chat](https://agda.zulipchat.com) are better fora.

Please take some time to search through the existing issues whether the problem has already been reported.  If it is already an open issue, you might confine yourself with just adding your problem instance as a comment there.

For opening a new issue, please make sure you can check the following boxes:

* [x] My report includes the version of Agda (and Emacs, GHC, and OS versions where relevant).

* [x] The issue can be reproduced with the _latest version_ of Agda (either [released](https://wiki.portal.chalmers.se/agda/Main/Download) or `master` branch).
      Note: We do not fix issues in older versions of Agda.

* [x] I have supplied all information so the bug can be easily reproduced (in particular, the reproducer is a complete Agda file).

Note: The best reproducers are those only using the `Agda.Builtin` and `Agda.Primitive` modules shipped with Agda.

**Comment by andreasabel** [comment]
Would be great if someone tried to improve the situation here, because this bug is reported over and over again:
- #2672

**Comment by L-TChen** [comment]
lol. 

Thanks. I didn't find the previous issues. Closing it now.

**Comment by andreasabel** [comment]
Closing this instead with the "we haven't done anything about it" flavor.
