### ISSUE TITLE
Check on presence of `--erasure` in `--erase-record-parameters` comes too early

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#6573]
The test for presence of `--erasure` in the activation code for `--erasure-record-parameters` 
https://github.com/agda/agda/blob/e4b6c53966b7c6a73ea573a1a7e6eb2572db2dce/src/full/Agda/Interaction/Options/Base.hs#L1036-L1039
isn't lazy enough:
```shell-session
$ agda --erase-record-parameters 
Error: The option --erase-record-parameters requires the use of --erasure
...
$ agda --erase-record-parameters --erasure
Error: The option --erase-record-parameters requires the use of --erasure
```

@nad, you introduced this check in 1e5dd291479f5ff4eed1efbed9fad3c300b6468a.  Before this commit, `--erasure-record-parameters` would _imply_ `--erasure`.  You didn't give a reason for this change in the option logic in this commit.  However, I found some discussion in https://github.com/agda/agda/pull/6350#issuecomment-1370315438. 
There you complain (rightfully) that if `X` implies `Y`, then `X` followed by `no-X` will turn on `Y` without `X` being on in the end.
This problem exists still for `--flat-split` implying `--cohesion`, so maybe we need a systematic solution and a uniform strategy.

An improvement would be to only check for option consistency _after_ we parsed all command line options.  
However, maybe implication should in general be resolved at _use site_ only, so, much more lazily and _declaratively_.  E.g. whenever we query whether we have `--cohesion`, we check whether we have either `--cohesion` or `--flat-split`.

Note: I am currently working on a refactoring of the options, this is where I came across this issue.
- #6556

**Comment by andreasabel** [comment]
> This problem exists still for `--flat-split` implying `--cohesion`,

P.S.: Atm, we do not have `--no-flat-split` but #6556 might add it.
@nad explicitly removed it in 2.6.3 (because of this problem) in 
- https://github.com/agda/agda/issues/6263#issuecomment-1296322231
- https://github.com/agda/agda/pull/6268/commits/1da5d0c89c38dd494402dea6ac27e1ed6e513e98
- https://github.com/agda/agda/pull/6268/commits/f047dc76324904a11033d752f813e838d4b359fa

**Comment by nad** [comment]
> The test for presence of `--erasure` in the activation code for `--erasure-record-parameters`
> 
> https://github.com/agda/agda/blob/e4b6c53966b7c6a73ea573a1a7e6eb2572db2dce/src/full/Agda/Interaction/Options/Base.hs#L1036-L1039
> 
> isn't lazy enough:
> 
> ```
> $ agda --erase-record-parameters 
> Error: The option --erase-record-parameters requires the use of --erasure
> ...
> $ agda --erase-record-parameters --erasure
> Error: The option --erase-record-parameters requires the use of --erasure
> ```

I think this is a matter of taste. However, I don't have strong opinions about this, I think other issues related to options are more important (#3570, #5265).
