### ISSUE TITLE
Sort out `--exact-split` vs. `-WCoverageNoExactSplit`

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#6574]
This is a follow up to #6556 (so don't PR while #6556 is still open); PR #6556 will preserve the status quo.

From the user perspective, `--exact-split` activates some a warning about non-exact splits with some special highlighting.
And then there is `-WCoverageNoExactSplit` that is responsible for _reporting_ this warning.
Currently it is switched in sync with `--(no-)exact-split`.

I think we should reorganize the code so that `--exact-split` and `-WCoverageNoExactSplit` do the same thing, and communicate in the docs and help text that this is the case and the former is just a nicer name for the latter.

@jespercockx : as the expert, what is your take on this?

**Comment by jespercockx** [comment]
`--exact-split` was implemented before the warning machinery, so it's not integrated with it. I agree that the two flags should probably just do the same.

**Comment by andreasabel** [comment]
Similar, only that these are not benign warnings:

*    `-WTerminationIssue` iff `--termination-check`

*    `-WNotStrictlyPositive` iff `--positivity-check`

**Comment by andreasabel** [comment]
Currently:
```agda
{-# OPTIONS -WnoTerminationIssue #-}

f : Set
f = f
```
Error:
```
You may only turn off benign warnings. The warning TerminationIssue
is a non-fatal error and thus cannot be ignored. See --help=warning.
```
Non-benign warnings follow a different logic, so, at the moment they do not identify with their respective option.

It seems that `-WTerminationIssue` is ignored in general:
```
{-# OPTIONS --no-termination-check -WTerminationIssue #-}

f : Set
f = f
```
And `-WnoTerminationIssue` is always an error, even with `--no-termination-check`:
```
$ agda --no-termination-check -WnoTerminationIssue
Error: You may only turn off benign warnings. The warning TerminationIssue is a non-fatal error and thus cannot be ignored. See --help=warning.
```
Should `TerminationIssue` maybe be a warning that is hidden altogether from the users? (It appears completely dead.)

**Comment by andreasabel** [comment]
Don't include this is the list of closed issues since this isn't status quo anymore.
- #6738
