### ISSUE TITLE
Rewrite pragma broken in Cubical Agda

### ISSUE THREAD

**Issue by wadler** [agda/agda#6576]
Thorsten Altenkirch and Philip Wadler are attempting to define a higher inductive type with path constructors and would like to rewrite using path constructors while adding constructors.

Example (sorry we don't have a short one) below.
[rewrite-problem.agda](https://agda.zulipchat.com/user_uploads/23881/cTCHHUuYsGtiepgG0YJ57vWf/rewrite-problem.agda)

Versions of the bug appear in both 2.6.4 and 2.6.3.

Error message in 2.6.3:
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/Rewriting.hs:313:33 in Agd-2.6.3-d4728884:Agda.TypeChecking.Rewriting

Error message in 2.6.4:
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/Rewriting.hs:313:33 in Agda-2.6.4-AaqUL8yc5eSHmpvxMF3NAp:Agda.TypeChecking.Rewriting

Is there a chance that this sort of thing gets enabled? Would it be difficult to implement?

Jesper Cockx thinks the issue might be fixed as follows:

"I think this could be fixed relatively easy by adding a case for Constructor{} -> allVars to this place in the code (which is where the internal error that Phil reports points to): https://github.com/agda/agda/blob/e4b6c53966b7c6a73ea573a1a7e6eb2572db2dce/src/full/Agda/TypeChecking/Rewriting.hs#L313."

---

Please make sure it is actually a problem with Agda or its documentation. For user questions, the [mailing list](https://lists.chalmers.se/mailman/listinfo/agda) or the [chat](https://agda.zulipchat.com) are better fora.

Please take some time to search through the existing issues whether the problem has already been reported.  If it is already an open issue, you might confine yourself with just adding your problem instance as a comment there.

For opening a new issue, please make sure you can check the following boxes:

* [x] My report includes the version of Agda (and Emacs, GHC, and OS versions where relevant).

* [x] The issue can be reproduced with the _latest version_ of Agda (either [released](https://wiki.portal.chalmers.se/agda/Main/Download) or `master` branch).
      Note: We do not fix issues in older versions of Agda.

* [x] I have supplied all information so the bug can be easily reproduced (in particular, the reproducer is a complete Agda file).

Note: The best reproducers are those only using the `Agda.Builtin` and `Agda.Primitive` modules shipped with Agda.

**Comment by andreasabel** [comment]
Thanks for the report!

@wadler wrote:
> Example (sorry we don't have a short one) below.
> [rewrite-problem.agda](https://agda.zulipchat.com/user_uploads/23881/cTCHHUuYsGtiepgG0YJ57vWf/rewrite-problem.agda)

Phil, could you attach this file to this issue?  The current link `https://agda.zulipchat.com/user_uploads/23881/cTCHHUuYsGtiepgG0YJ57vWf/rewrite-problem.agda` says:
> You are not authorized to view this file

**Comment by andreasabel** [comment]
I fetched this from zulip:
```agda
{-# OPTIONS --cubical --rewriting #-}
open import Agda.Primitive
open import Cubical.Core.Everything hiding (Sub)
open import Cubical.Foundations.Prelude hiding (Sub)
open import Cubical.Foundations.HLevels
{-# BUILTIN REWRITE _≡_ #-}

data UU : Type
data EL : UU → Type

Con : Type
Sub : Con → Con → Type
Ty  : Con → Type
Tm  : (Γ : Con) → Ty Γ → Type

data UU where
  Con' : UU
  Sub' : Con → Con → UU
  Ty'  : Con → UU
  Tm'  : (Γ : Con) → Ty Γ → UU

Con     = EL Con'
Sub Γ Δ = EL (Sub' Γ Δ)
Ty Γ    = EL (Ty' Γ)
Tm Γ A  = EL (Tm' Γ A)

data EL where
  ConSet      : isSet Con
  SubSet      : ∀{Γ Δ} → isSet (Sub Γ Δ)
  _∘_         : ∀{Γ Θ Δ} → Sub Θ Δ → Sub Γ Θ → Sub Γ Δ
  ass         : ∀{Γ Θ Ξ Δ}(σ : Sub Ξ Δ)(δ : Sub Θ Ξ)(ν : Sub Γ Θ) →
                (σ ∘ δ) ∘ ν ≡ σ ∘ (δ ∘ ν)
  id          : ∀{Γ} → Sub Γ Γ
  idl         : ∀{Γ Δ}{σ : Sub Γ Δ} → id ∘ σ ≡ σ
  idr         : ∀{Γ Δ}{σ : Sub Γ Δ} → σ ∘ id ≡ σ

  ◆           : Con
  ε           : ∀{Γ} → Sub Γ ◆
  ◆η          : ∀{Γ}(σ : Sub Γ ◆) → σ ≡ ε

  -- Ty : Con^op → Set
  TySet       : ∀{Γ} → isSet (Ty Γ)
  _[_]T       : ∀{Γ Δ} → Ty Δ → Sub Γ Δ → Ty Γ
  _[_∣_]T     : ∀{Γ Θ Δ}(A : Ty Δ)(σ : Sub Θ Δ)(δ : Sub Γ Θ) → A [ σ ∘ δ ]T ≡ A [ σ ]T [ δ ]T
  _[id]T      : ∀{Γ}(A : Ty Γ) → A [ id ]T ≡ A


  -- Tm : (∫ Ty)^op → Set
  -- category of elements ∫ Ty
  -- obj : Σ Γ:Con . Ty Γ
  -- mor (Γ , A) (Δ , B) = Σ δ : Sub Γ Δ . A ≡ B [ δ ]T
  -- Tm : (Σ Γ:Con . Ty Γ)^op → Set
  TmSet       : ∀{Γ A} → isSet (Tm Γ A)
  _[_]t       : ∀{Γ Δ}{A : Ty Δ} → Tm Δ A → (σ : Sub Γ Δ) → Tm Γ (A [ σ ]T)
  _[_∣_]t     : ∀{Γ Θ Δ}{A : Ty Δ}(t : Tm Δ A)(σ : Sub Θ Δ)(δ : Sub Γ Θ) →
                PathP (λ i → Tm Γ ((A [ σ ∣ δ ]T) i)) (t [ σ ∘ δ ]t) (t [ σ ]t [ δ ]t)

  -- t [ σ ∘ δ ]t : Tm Γ (A [ σ ∘ δ ]T)
  -- (t [ σ ]t [ δ ]t) : Tm Γ (A [ σ ]T [ δ ]T)

  _[id]t      : ∀{Γ A}(t : Tm Γ A) →
                PathP (λ i → Tm Γ ((A [id]T) i)) (t [ id ]t) t

  _▹_         : (Γ : Con) → Ty Γ → Con
  _,s_        : ∀{Γ Δ A}(σ : Sub Γ Δ) → Tm Γ (A [ σ ]T) → Sub Γ (Δ ▹ A)
  π₁          : ∀{Γ Δ A}(σ : Sub Γ (Δ ▹ A)) → Sub Γ Δ
  π₂          : ∀{Γ Δ A}(σ : Sub Γ (Δ ▹ A)) → Tm Γ (A [ π₁ σ ]T)
  ▹β₁         : ∀{Γ Δ A}{σ : Sub Γ Δ}{t : Tm Γ (A [ σ ]T)} → π₁ (σ ,s t) ≡ σ
  ▹β₂         : ∀{Γ Δ A}{σ : Sub Γ Δ}{t : Tm Γ (A [ σ ]T)} → PathP (λ i → Tm Γ (A [ ▹β₁ {σ = σ}{t} i ]T)) (π₂ (σ ,s t)) t
  ▹η          : ∀{Γ Δ A}{σ : Sub Γ (Δ ▹ A)} → σ ≡ π₁ σ ,s π₂ σ
  π₁∘         : ∀{Γ Δ A}{σ : Sub Γ (Δ ▹ A)}{Θ}{δ : Sub Θ Γ} → π₁ σ ∘ δ ≡ π₁ (σ ∘ δ)
  _[π₁_∣_]T   : ∀{Γ Δ} A (σ : Sub Γ (Δ ▹ A)){Θ}(δ : Sub Θ Γ) → A [ π₁ σ ]T [ δ ]T ≡ A [ π₁ (σ ∘ δ) ]T
  π₂[]        : ∀{Γ Δ A}{σ : Sub Γ (Δ ▹ A)}{Θ}{δ : Sub Θ Γ} → PathP (λ i → Tm Θ ((A [π₁ σ ∣ δ ]T) i)) (π₂ σ [ δ ]t) (π₂ (σ ∘ δ))
  _^_         : ∀{Γ Δ}(σ : Sub Γ Δ)(A : Ty Δ) → Sub (Γ ▹ A [ σ ]T) (Δ ▹ A)
  id^_        : ∀{Γ}(A : Ty Γ) → PathP (λ i → Sub (Γ ▹ (A [id]T) i) (Γ ▹ A)) (id ^ A) id
  ∘^          : ∀{Δ}{A : Ty Δ}{Θ}(σ : Sub Θ Δ){Γ}(δ : Sub Γ Θ) → PathP (λ i → Sub (Γ ▹ (A [ σ ∣ δ ]T) i) (Δ ▹ A)) ((σ ∘ δ) ^ A) (σ ^ A ∘ δ ^ A [ σ ]T)
  _[id^]T     : ∀{Γ}{A : Ty Γ} B → PathP (λ i → Ty (Γ ▹ (A [id]T) i)) (B [ id ^ A ]T) B
  _[∘^]       : ∀{Δ}{A : Ty Δ}{Θ}{σ : Sub Θ Δ}{Γ}{δ : Sub Γ Θ} B → PathP (λ i → Ty (Γ ▹ (A [ σ ∣ δ ]T) i)) (B [ (σ ∘ δ) ^ A ]T) ( B [ σ ^ A ]T [ δ ^ A [ σ ]T ]T )
  ^=₁         : ∀{Γ Δ}{σ : Sub Γ Δ}{A : Ty Δ} → π₁ (σ ^ A) ≡ σ ∘ π₁ id
  _[π₁^]      : ∀{Γ Δ}{σ : Sub Γ Δ}{A : Ty Δ} B → B [ π₁ (σ ^ A) ]T ≡ B [ σ ]T [ π₁ id ]T
  ^=₂         : ∀{Γ Δ}{σ : Sub Γ Δ}{A : Ty Δ} → PathP (λ i → Tm (Γ ▹ A [ σ ]T) ((A [π₁^]) i)) (π₂ (σ ^ A)) (π₂ id)

  Π           : ∀{Γ}(A : Ty Γ)(B : Ty (Γ ▹ A)) → Ty Γ
  lam         : ∀{Γ A B} → Tm (Γ ▹ A) B → Tm Γ (Π A B)
  app         : ∀{Γ A B} → Tm Γ (Π A B) → Tm (Γ ▹ A) B
  Πβ          : ∀{Γ A B}{t : Tm (Γ ▹ A) B} → app (lam t) ≡ t
  Πη          : ∀{Γ A B}{t : Tm Γ (Π A B)} → lam (app t) ≡ t
  Π[]         : ∀{Γ} A B {Θ}(σ : Sub Θ Γ) → Π A B [ σ ]T ≡ Π (A [ σ ]T) (B [ σ ^ A ]T)
  lam[]       : ∀{Γ A B}(t : Tm (Γ ▹ A) B){Θ}(σ : Sub Θ Γ) → PathP (λ i → Tm Θ (Π[] A B σ i)) (lam t [ σ ]t) (lam (t [ σ ^ A ]t))

  U           : ∀{Γ} → Ty Γ
  U[_]        : ∀{Γ Θ}(σ : Sub Θ Γ) → U [ σ ]T ≡ U
  {-# REWRITE U[_] #-}
  _[_]U       : ∀{Γ} → Tm Γ U → ∀{Θ} → Sub Θ Γ → Tm Θ U

  _[_]U=      : ∀{Γ}(a : Tm Γ U){Θ}(σ : Sub Θ Γ) → PathP (λ i → Tm Θ (U[ σ ] (~ i))) (a [ σ ]U) (a [ σ ]t)
  -- a [ σ ]U : Tm Θ U
  -- a [ σ ]t : Tm Θ (U [ σ ]T)


  _[id]U      : ∀{Γ}(a : Tm Γ U) → a [ id ]U ≡ a
  _[_∣_]U     : ∀{Γ}(a : Tm Γ U){Θ}(σ : Sub Θ Γ){Ω}(δ : Sub Ω Θ) → a [ σ ∘ δ ]U ≡ a [ σ ]U [ δ ]U
  El          : ∀{Γ} → Tm Γ U → Ty Γ
  El_[_]      : ∀{Γ}(a : Tm Γ U){Θ}(σ : Sub Θ Γ) → El a [ σ ]T ≡ El (a [ σ ]U)
  El_[_]'      : ∀{Γ}(a : Tm Γ U){Θ}(σ : Sub Θ Γ) → El a [ σ ]T ≡ El (a [ σ ]t)

  ΠU          : ∀{Γ} → (A : Ty Γ)(b : Tm (Γ ▹ A) U) → Tm Γ U
  El-ΠU       : ∀{Γ} → (A : Ty Γ)(b : Tm (Γ ▹ A) U) → El (ΠU A b) ≡ Π A (El b)

infixl 5 _▹_
infixl 40 _[_]T
infixl 40 _[_∣_]T
infixl 40 _[id]T
infixl 5 _,s_
infixr 8 _∘_
infixl 40 _[_]t
infixl 40 _[_∣_]t
infixl 40 _[π₁_∣_]T

-- Setoid Type Theory = SetTT
{-# REWRITE U[_] #-}
{-# REWRITE _[id]T   #-}
{-# REWRITE El_[_]   #-}
--{-# REWRITE _[_]U=    #-}

wk : ∀ {Γ}{A : Ty Γ} →  Sub (Γ ▹ A) Γ
wk = π₁ id

zero : ∀ {Γ}{A : Ty Γ} → Tm (Γ  ▹ A) (A [ wk ]T)
zero = π₂ id

suc : ∀ {Γ}{A B : Ty Γ} → Tm Γ A → Tm (Γ  ▹ B)(A [ wk ]T)
suc t = t [ wk ]t

_$_ : ∀{Γ}{A : Ty Γ}{B : Ty (Γ ▹ A)} → Tm Γ (Π A B) → (u : Tm Γ A) → Tm Γ (B [ id ,s u ]T) --  id ,s u
t $ u = (app t) [ id ,s u ]t

-- Pi X.X -> X
IdT : ∀ {Γ} → Ty Γ
IdT = Π U (Π (El zero) (El (suc zero)))

-- id = λ X x → x

idt : ∀ {Γ} → Tm Γ IdT
idt {Γ} = lam (lam {!zero {Γ = Γ ▹ U}{A = El zero} !})

-- Pi X.(X → X) → X → X
-- λ f z → f (f z)

{-
Goal: Tm (Γ ▹ U ▹ El zero) (El (suc zero))
Have: Tm (Γ ▹ U ▹ El zero) (El zero [ wk ]T)
-}

-- id : Tm Γ (Π U
```
The error is:
```
Illegal declaration in data type definition 
  {-# REWRITE U[_] #-}
when scope checking the declaration
```

**Comment by andreasabel** [comment]
@jespercockx : Maybe you know something about this issue?

**Comment by jespercockx** [comment]
I don't think the combination of rewriting and cubical was ever properly supported, as I think no-one has thought very deeply on how it should work. 

In this case the problem is that a REWRITE pragma is not allowed in the middle of a datatype definition, which is not a feature you'd ever need without cubical since normally constructors cannot introduce new equalities. Even with cubical I'd say that you would not want to use the path type as the rewrite relation, as rewrite rules are *strict* equalities.

For the concrete use case here, that means I don't think it is something we want to support (unless someone can explain to me how rewriting by path equalities is supposed to work without breaking soundness).

**Comment by wadler** [comment]
"In this case the problem is that a REWRITE pragma is not allowed in the middle of a datatype definition"

Jesper, I don't think that is correct. If you look at the failing example, all the REWRITEs appear *after* the data type declaration.

We are keen to use Cubical Agda to define type theory in type theory. This will be *much* harder without REWRITE---possibly so hard that it will not be possible in practice. It would be great if you could resurrect the issue and fix the problem.

**Comment by wadler** [comment]
PS. We'd be happy to supply any additional needed information. Andreas did indeed find the relevant code. I'm sorry if we were slow in responding to a request, we'll try to do better in future.

**Comment by wadler** [comment]
PPS. On looking a second time, I see there is one rewrite in the middle of the data declaration, and indeed it would be nice if this was supported. But I don't think that was the major problem.

**Comment by andreasabel** [comment]
@wadler wrote:
> PPS. On looking a second time, I see there is one rewrite in the middle of the data declaration, and indeed it would be nice if this was supported. But I don't think that was the major problem.

```agda
  U[_]        : ∀{Γ Θ}(σ : Sub Θ Γ) → U [ σ ]T ≡ U
  {-# REWRITE U[_] #-}
```
If you remove this rewrite rule, one of the subsequent constructor signatures fails:
```agda
  El_[_]'      : ∀{Γ}(a : Tm Γ U){Θ}(σ : Sub Θ Γ) → El a [ σ ]T ≡ El (a [ σ ]t)
```
```
U [ σ ]T != U of type EL (Ty' Θ)
when checking that the expression a [ σ ]t has type Tm Θ U
```
The rewrite `U [ σ ]T --> U` is indeed needed here to type check this.

**Comment by jespercockx** [comment]
> Jesper, I don't think that is correct. If you look at the failing example, all the REWRITEs appear after the data type declaration.
>
> We are keen to use Cubical Agda to define type theory in type theory. This will be much harder without REWRITE---possibly so hard that it will not be possible in practice. It would be great if you could resurrect the issue and fix the problem.

The real problem is the semantic concern: what does it even *mean* to rewrite by a path equality? There is an obvious interpretation (just treat path equality like any other rewriting relation) but that is unsound, as it assumes that the path is `refl`. If there's a good answer to this question I'd be happy to reopen this. Otherwise, there is an easy (but verbose) workaround, which is to postulate the equalities you want to rewrite with as regular equalities rather than cubical ones, which also makes it explicit that you are doing something unsafe.
