### ISSUE TITLE
Doc: comments in "libraries" file

### ISSUE THREAD

**Issue by anuyts** [agda/agda#6605]
Is it possible to comment out lines in the "libraries" file?
The answer should be documented [here](https://agda.readthedocs.io/en/v2.6.3/tools/package-system.html), and if it is negative, I have a feature request :-)

**Comment by andreasabel** [comment]
My mantra would be: _comments and let-bindings (non-recursive) should be the base ingredient to any software language_.
But we are good: `--` line comments should work. https://github.com/agda/agda/blob/c2d4a7e9962e89ff465f6e593680da44e419e8ab/src/full/Agda/Interaction/Library.hs#L327
