### ISSUE TITLE
Agda 2.6.3  compiles application on Debian 10 much worse than on Ubuntu 18.04

### ISSUE THREAD

**Issue by mechvel** [agda/agda#6620]
---
This is on  Agda-2.6.3, MAlonzo, ghc-9.2.1, Debian Linux 10.
```
set  $agdaFlags = --auto-inline --guardedness

> agda    $agdaLibOpt $agdaFlags +RTS -M17G -RTS GenAlgebra-III.agda
> agda -c $agdaLibOpt $agdaFlags +RTS -M17G -RTS GenAlgebra-III.agda
```
(This module is on top of a certain library, not so large in its .agda source, but the code can be complicated).

The last command reports after about 30 minutes:
...
...
[171 of 171] Compiling MAlonzo.Code.GenAlgebraZ45ZIII
( /home/mechvel/agda/tosave/bugs/may11-2023/MAlonzo/Code/GenAlgebraZ45ZIII.hs,
/home/mechvel/agda/tosave/bugs/may11-2023/MAlonzo/Code/GenAlgebraZ45ZIII.o )
No main function defined in GenAlgebra-III. Use --no-main to suppress this warning.
Compilation error:
/tmp/ghc1470_0/ghc_512.s:  _message from assembly_
(transation from Russian):
/tmp/ghc1470_0/ghc_512.s:6325433:0: error:
     Critical error: bfd_make_empty_symbol: memory exhausted
        |
6325433 | .globl MAlonzzoziCodeziGenAlgebraZZ45ZZIII_zdwduzuisMonoidzu1082_closure
        | ^
`cc' failed in phase `Assembler'. (Exit code: 1)

1544.574u 

* Also for   -M14G,
  it reports of internal error (of GHC) of failing to commit a certain piece of memory.
So that to use this application under Debian Linux 10 is practically impossible. 

* For  Ubuntu Linux 18.04  (with the same versions of Agda and ghc),
  it is compiled under  -M14G  in 20-30 minutes without any error.

It somehow likes old Ubuntu more than relatively new Debian.

And it is highly desirable for the application to work under any system, preferably under all Linux-es.

I am not sure, may be this is a bug in GHC.

**Comment by andreasabel** [comment]
Reproducer needed.

Is it using the same GHC version on both systems?

**Comment by mechvel** [comment]
Yes:
>> For Ubuntu Linux 18.04 (with the same versions of Agda and ghc),
>> it is compiled under -M14G in 20-30 minutes without any error.

> Reproducer needed.

Do you mean the full source text  of the example?
It is large.
May be I shell try to reduce it, a bit later.  
It will be difficult, because with each change one has to somehow wait 40 minutes of running ghc.

**Comment by andreasabel** [comment]
If you want to use GHC 9.2, why not the latest minor version 9.2.7 (instead of 9.2.1)?

**Comment by mechvel** [comment]
Currently I would like to use the GHC version which is better to use with  the current official Agda.
What GHC version do you recommend?
On the other hand, the users of the application would have to use Agda-2.6.3 + MAlonzo 
(if a newer official Agda  is not given), 
and I have to add recommendation to the application Readme about the ghc versions.

**Comment by mechvel** [comment]
I meant: what is the most reliable ghc version to use together with the current official Agda ?

**Comment by andreasabel** [comment]
> I meant: what is the most reliable ghc version to use together with the current official Agda ?

We have no data on this.  But as a general heuristic, use the latest minor version of a GHC major version which contains the bug fixes for the previous minor versions.

If in doubt use the generally recommended version which is atm 9.2.7:
```
$ ghcup list
....
  ghc   9.2.7          recommended,base-4.16.4.0 
...
```

I encourage you to make your own experiments which ghc version compiles your code best.  If you find something out, please let us know here!

**Comment by mechvel** [comment]
Does it matter what ghc version was used in the process of installing Agda (2.6.3) ?
(I do not recall, is it used there?).
Now I run the same installation of Agda-2.6.3 with  ghc-9.2.7:
```
agda -c $agdaLibOpt $agdaFlags +RTS -M14G -RTS Pol/Univariate/KTest.agda
...
[266 of 266] Compiling MAlonzo.Code.Pol.Univariate.KTest ( /home/mechvel/inAgda/doconA/3.2/source/MAlonzo/Code/Pol/Univariate/KTest.hs, /home/mechvel/inAgda/doconA/3.2/source/MAlonzo/Code/Pol/Univariate/KTest.o )
Compilation error:
/home/mechvel/inAgda/doconA/3.2/source/MAlonzo/Code/Pol/Univariate/KTest.hs:1:1: error:
    The IO action ‘main’ is not defined in module ‘MAlonzo.Code.Pol.Univariate.KTest’
  |
1 | {-# LANGUAGE BangPatterns #-}
  | ^
```
This IO action is defined in   KTest.agda,  because it is type-checked and compiled  to  KTest.hs.
But  ghc  do not find it when trying to compile to   KTest.o.

This is both on Ubuntu Linux 18-04 and Debian Linux 10 
(both use ghc-9.2.7, but the 64-bit machines probably are slightly different). 

The example has many modules, the code is complicated.
When I compile simpler examples in this application, that use a smaller set of modules, then this IO runs all right.
 
I could try ghc-9.4.5, but i suspect some persistent bug in ghc, may be, in memory management,
when it reaches memory higher than, say, 12 Gb.
?

**Comment by mechvel** [comment]
The process is not  stable. Next session, it  type-checked by new and then compiled successfully
(under Ubuntu Linux 18.04). 
Now I am going to test it under Debian Linux 10.
I do not know what to think.

**Comment by mechvel** [comment]
Sorry, it is disappeared.
When all the application is type-checked and compiled by new only by two commands
``` 
  agda .. TypeCheckAll
  agda -c ../Test.agda
```
then it works all right under ghc-9.2.7 and under both systems.
Errors can appear when some its part is compiled and its example test, then a larger set of modules is compiled for another example test.
But now this is not for sure for ghc-9.2.7, and it is difficult to trace and reproduce.

**Comment by andreasabel** [comment]
Optimistically closing this issue.
