### ISSUE TITLE
Bad error for `mutual` in implicit mutual block

### ISSUE THREAD

**Issue by plt-amy** [agda/agda#6622]
`mutual` can't participate in mutual recursion, but if the mutual block is _inferred_, as in the code below,

```agda
open import Agda.Builtin.Nat

test : Nat
mutual
  foo : Nat
  foo = test
test = 2
```

then the error message is simply "Duplicate definition for test".

**Comment by andreasabel** [comment]
Thinking this over, a `mutual` cannot participate in a `mutual` (1), but it can participate in implicit or interleaved mutual blocks (2).  
1. The order of decls inside explicit `mutual`  blocks is shuffled around, so it is not clear where to place the inner `mutual` block.
2. The order of decls inside implicit or interleaved mutual blocks is just the order of appearance.  A mutual block inside such a stream could simply be locally reordered and then added to the stream.  It would not receive its own `MutualId`, but simply flattened away.
