### ISSUE TITLE
Allow co-pattern matches in `syntax` declarations

### ISSUE THREAD

**Issue by lawcho** [agda/agda#6658]
Allowing `syntax` declarations to sugar co-pattern matching lambdas would allow functions like `nats` to pass the termination checker:

```.agda
record Stream (A : Set) : Set where
    coinductive
    constructor stream
    field head : A
    field tail : Stream A
open Stream

syntax λ {.head → a; .tail → b} = a ∷ b

nats : Nat → Stream Nat
nats n = n ∷ nats (1 + n)
```

I suggest using `syntax` declarations to control the expansion to co-patterns, because...

* `syntax` declarations can be encapsulated inside a library
* `syntax` declarations do not change the unification properties of existing constructors (e.g. `stream`),
    so this proposal shouldn't break existing code

Supporting this might also resolve #3251, #3345, #4740

**Comment by andreasabel** [comment]
NB: We have used the label "syntax" also for `syntax` declarations.

Thanks for the feature request.

The problem with your proposal is that it will need a new mechanism, as pattern lambdas aren't first-class syntax, they are translated to local definitions.  Also, `syntax` atm only allows a new notation for a name applied to variables (or some binders).

**Comment by lawcho** [comment]
Perhaps it would be easier to implement `{-# INLINE #-}`-ing an ordinary definition with co-patterns. Closing in favor of #6660.
