### ISSUE TITLE
`{-# INLINE #-}` for copattern constructors

### ISSUE THREAD

**Issue by lawcho** [agda/agda#6660]
In the following code (Agda v2.6.3-b499d12), `nats₁` passes termination checking, but `nats₂` fails with a "problematic calls" error:

```.agda
{-# OPTIONS --guardedness #-}

record Stream (A : Set) : Set where
    coinductive
    constructor stream
    field head : A
    field tail : Stream A
open Stream

open import Agda.Builtin.Nat

nats₁ : Nat → Stream Nat
nats₁ n = λ {.head → n; .tail → nats₁ (1 + n)}

_∷_ : ∀{A} → A → Stream A → Stream A
a ∷ s = λ {.head → a ; .tail → s}
{-# INLINE _∷_ #-}

nats₂ : Nat → Stream Nat
nats₂ n = n ∷ nats₂ (1 + n)
```

I would like the `{-# INLINE _∷_ #-}` to either fail with a specific error message, or (even better) succeed so that `nats₂` is accepted.

The code responsible for applying (or ignoring) `{-# INLINE #-}` pragmas appears to be at https://github.com/agda/agda/blob/af88ea6747b9eab944e70d731de0bd9b25e4f452/src/full/Agda/TypeChecking/Reduce.hs#L834-L842

**Comment by andreasabel** [comment]
I think that would need inlining at the level of abstract syntax rather than inlining a type-checked definition.  With current inlining, you can only get this:
```agda
  extlam : ∀{A} → A → Stream A → Stream A
  extlam a s .head = a
  extlam a s .tail = s

  _∷_ : ∀{A} → A → Stream A → Stream A
  a ∷ s = extlam a s

  nats₂ : Nat → Stream Nat
  nats₂ n = extlam n (nats₂ (1 + n))
```
The last equation allows infinite unfolding...

**Comment by lawcho** [comment]
Here is an updated example without extended lambdas:
```.agda
{-# OPTIONS --guardedness #-}

record Stream (A : Set) : Set where
    coinductive
    constructor stream
    field head : A
    field tail : Stream A
open Stream

open import Agda.Builtin.Nat

nats₁ : Nat → Stream Nat
nats₁ n .head = n
nats₁ n .tail = nats₁ (1 + n)

_∷_ : ∀{A} → A → Stream A → Stream A
(a ∷ s) .head = a
(a ∷ s) .tail = s
{-# INLINE _∷_ #-}

nats₂ : Nat → Stream Nat
nats₂ n = n ∷ nats₂ (1 + n)
```
As before, `nats₁` passes but `nats₂` fails with a "problematic calls" error.

I'd expect the `{-# INLINE _∷_ #-}` pragma to rewrite `nats₂` to `nats₁`, but I can see why this is difficult to implement -- the `unfoldInlined` function returns an `m Agda.Syntax.Internal.Term`, which can't contain extended lambdas or co-patterns.

**Comment by andreasabel** [comment]
Agda has a "record expression to copattern" translation, see https://github.com/agda/agda/commit/ace8e0d099402a625ac460862ae0a81fcec538d4, which is similar to what you want here.  However, this translation works on the `CompiledClause`s rather than the `Clause`s, thus, it runs only _after_ termination checking.  (Also, it does not run with the record constructor, only with record expressions.)  
Maybe something like this could be implemented for coinductive constructors, on the clauses, so that the termination checker picks it up.  However, this would have the side effect that the equation `nats₂ n = n ∷ nats₂ (1 + n)` is no longer definitional, i.e., there is no reduction from this lhs to the rhs.  In this particular case, this would be intended, but I am not sure it would be intended whenever a coinductive constructor is used.  (Maybe?)

**Comment by lawcho** [comment]
Here is a larger example:
```.agda
{-# OPTIONS --guardedness #-}

open import Agda.Builtin.String
open import Agda.Builtin.Unit

data Cmd : Set where
    put-str-ln : String → Cmd
    get-str-ln : Cmd

cmd-ret-ty : Cmd → Set
cmd-ret-ty (put-str-ln _) = ⊤
cmd-ret-ty get-str-ln = String

record ITree : Set where
    coinductive
    field head : Cmd
    field tail : (cmd-ret-ty head) → ITree
open ITree

_>>=_ : (head : Cmd) → (cmd-ret-ty head → ITree) → ITree
(c >>= t) .head = c
(c >>= t) .tail = t
{-# INLINE _>>=_ #-}

_>>_ : Cmd → ITree → ITree
c >> t = c >>= λ _ → t
{-# INLINE _>>_ #-}

greet = do
    put-str-ln "Who are you?"
    name ← get-str-ln
    put-str-ln (primStringAppend "Hello, " name)
    greet

```
The `greet` function currently fails with a "problematic calls" error, because `_>>=_` does not inline.

**Comment by andreasabel** [comment]
Work started in branch: https://github.com/agda/agda/tree/inline-coinductive-constructor-rhs

**Comment by nad** [comment]
I don't think we should merge new features close to the release of Agda 2.6.4. Please revert this change.

**Comment by andreasabel** [comment]
This feature is orthogonal to the rest of Agda in the sense that if you do not use it, you cannot experience a regression.  So the worst that can happen to you using this feature is that it is malfunctioning.  I do not see the harm here.

**Comment by nad** [comment]
I'm [not convinced](https://github.com/agda/agda/pull/6682#issuecomment-1602829312) that this feature is a good idea, so I don't think we should release it without discussing it properly first.

**Comment by andreasabel** [comment]
Concerns addressed by 
- #6702
