### ISSUE TITLE
`Opaque unfolding` does not work with parameterised modules

### ISSUE THREAD

**Issue by L-TChen** [agda/agda#6665]
If an `opaque` block is declared in a parametrised module `M`, then `unfolding` does not unfold given opaque names if the module `M` is given some module arguments.

For instance, consider the module `M2` in the following example:

```agda
open import Agda.Builtin.Nat
  using (Nat; zero; suc)
open import Agda.Builtin.Equality

module Opaque where

module M1 where
  opaque
    _+_ : Nat → Nat → Nat
    zero  + m = m
    suc n + m = suc (n + m)

module _ where
  open M1

  opaque
    unfolding _+_
  
    _ : 1 + 1 ≡ 2
    _ = refl

module M2 (A : Set) where
  opaque
    _+_ : Nat → Nat → Nat
    zero  + m = m
    suc n + m = suc (n + m)

module _ where
  open M2 Nat
  
  opaque
    unfolding _+_

    _ : 1 + 1 ≡ 2
    _ = {! refl !}
```
If names in `M2` are imported with an argument `Nat`, then `_+_` is not unfolded even if declared so. If the argument `Nat` is not given, then it works fine. 

Tested with Agda 2.6.4-ebe7ed1 (the commit https://github.com/agda/agda/commit/ebe7ed170dba079cc6b825c222079706c73dbae6)

---

Please make sure it is actually a problem with Agda or its documentation. For user questions, the [mailing list](https://lists.chalmers.se/mailman/listinfo/agda) or the [chat](https://agda.zulipchat.com) are better fora.

Please take some time to search through the existing issues whether the problem has already been reported.  If it is already an open issue, you might confine yourself with just adding your problem instance as a comment there.

For opening a new issue, please make sure you can check the following boxes:

* [x] My report includes the version of Agda (and Emacs, GHC, and OS versions where relevant).

* [x] The issue can be reproduced with the _latest version_ of Agda (either [released](https://wiki.portal.chalmers.se/agda/Main/Download) or `master` branch).
      Note: We do not fix issues in older versions of Agda.

* [x] I have supplied all information so the bug can be easily reproduced (in particular, the reproducer is a complete Agda file).

Note: The best reproducers are those only using the `Agda.Builtin` and `Agda.Primitive` modules shipped with Agda.

**Comment by andreasabel** [comment]
The warning at the last `unfolding` is:
```
warning: -W[no]UnfoldTransparentName
The name Issue6665._+_, mentioned by an unfolding clause, does not
belong to an opaque block. This has no effect.
```
