### ISSUE TITLE
An internal error occurrs when (mis)using syntax declarations

### ISSUE THREAD

**Issue by Soares** [agda/agda#6667]
<details>
* [✓] My report includes the version of Agda (and Emacs, GHC, and OS versions where relevant).

* [✓] The issue can be reproduced with the _latest version_ of Agda (either [released](https://wiki.portal.chalmers.se/agda/Main/Download) or `master` branch).
      Note: We do not fix issues in older versions of Agda.

* [✓] I have supplied all information so the bug can be easily reproduced (in particular, the reproducer is a complete Agda file).
</details>

```
> agda --version
Agda version 2.6.3
> nixos-version
22.11.20230219.0cf4274 (Raccoon)
```
```
> cat ~/Repro.agda
```
```agda
id : ∀ {A : Set} -> (A -> A)
id = λ{ a -> a }
syntax id = ι

record Arr* A1 A2 (B1 : A1 -> Set) (B2 : A2 -> Set) (f : A1 -> A2) : Set where
  field run : ∀ (a : A1) -> B1 a -> B2 (f a)

id* : ∀ {A : Set} {B : A -> Set} -> Arr* A A B B ι
id* = record
  { run = λ{ a b -> b }
  }
```
```
> agda ~/Repro.agda
Checking Repro (/home/<user>/Repro.agda).
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs:3095:30 in Agda-2.6.3-IodRPUWhXmb829dMFrGuRz:Agda.Syntax
.Translation.ConcreteToAbstract
```
---

The trouble is the `ι` (rather than `id`) at the end of the type signature in `id*`.

(It's probably possible to distill further.)

(Yes I'm aware that `syntax id = ι` is something of an abuse of the syntax declaration feature. In my defense, I'm later going to define `compose` and `compose*` which want mixfix operators, and then a one-step-more-complicated version where the associated syntax would have to take dependent arguments out-of-order, and I won't be able to use mixfix operators in that case[^1], so I must use syntax in my most-complicated version of compose, and I decided to try using syntax instead of mixfix everywhere for symmetry, and ran into this issue.)

Reporting as requested.

[^1]: kinda like how the syntax `a <[ P ] b` can't possibly route through a mixfix operator `_<[_]_ : Carrier P -> (P : Preorder) -> Carrier P -> Set`.

**Comment by andreasabel** [comment]
The error is raised here: https://github.com/agda/agda/blob/c7d8abe69f34ed8236448858584080797b7476a4/src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs#L3281
(Line dates from 2007, but probably has a new semantics since the 2010 addition of `syntax`.)

**Comment by szumixie** [comment]
Agda doesn't support syntax declarations with one identifier at all, the following code results in S not in scope:
```agda
postulate A : Set
syntax A = S
B = S
```
S being anywhere in a list of raw applications results in internal error:
```agda
postulate A : Set
syntax A = S
postulate F : Set → Set
B = F S
```

**Comment by andreasabel** [comment]
So we should throw a warning when a user declares a nullary `syntax` operator and mark it as dead code.

**Comment by szumixie** [comment]
It works just fine if the nullary operator is made up of more than one identifier:
```agda
postulate A : Set
syntax A = [ ]
postulate F : Set → Set
B = F [ ]
```

**Comment by andreasabel** [comment]
Ok, maybe better fix the bug then without removing a feature.
