### ISSUE TITLE
A strange compilation cost

### ISSUE THREAD

**Issue by mechvel** [agda/agda#6684]
This is not precisely on a bug, but it is a certain problem of the compilation cost.
This is on                                                                        
Agda 2.6.3, ghc-9.2.7, MAlonzo, Ubuntu Linux 18.04.                               
Agda is installed from source by                                                  
> cabal {-foptimise-heavily} install                                              
                                                                                  
Test  is built by                                                                 
agdaFlags =  --auto-inline --guardedness
> agda    $agdaLibOpt $agdaFlags +RTS -M7G -RTS Test.agda                         
> agda -c $agdaLibOpt $agdaFlags +RTS -M7G -RTS Test.agda                         
                                                                                  
On a 3 GHz machine with 32 Gb RAM,                                                                                      
  type checking takes               110 sec,                                      
  after this,                                                                     
  compilation to executable takes  1404 sec.                                      
                                                                                  
Almost all of time takes compiling                                                
  GenAlgebra-III.agdai --> GenAlgebra-III.hs                                                 
  and                                                                             
  GenAlgebra-III.hs --> GenAlgebra-III.o.                                                 
                                                                                  
GenAlgebra-III.agda   has      39.240 byte                                        
GenAlgebra-III.agdai  has   6.710.481 byte                                        
GenAlgebra-III.hs     has  17.900.858 byte                                        
GenAlgebra-III.o      has  44.120.416 byte                                                                      
                                                                                  
The application mainly presents the definition for the generic GCD notion  in algebra, and several simple proofs related to this notion,                     
the instances of all this for Natural.  This also requires defining several abstract domains extending the bundles of           
Setoid, ..., CommutativeRing of Standard library.                                 
                                       
The GHC compiler is usually fast enough.                                            
Why compiling to GenAlgebra-III.hs and then to GenAlgebra-III.o  is so expensive?                    
What is so difficult in GenAlgebra-III compared to other modules?

So far, I do not think that this is crucial. But it is curious. 
And also maybe there there is possible some simple optimization trick.
I can provide the source archive, 75K byte.

**Comment by mechvel** [comment]
I have managed to reduce the compilation time 1.5 times by splitting the guilty GenAglebra-III.agda to
GenAglebra-III.agda, OfCancellativeComSemiring,agda, GenAglebra-IIIa.agda,
where the second was a large parametric module inside the first file.
The time spent by MAlonzo + GHC has reduced 1.5 times. 

The sizes of the guilty  .hs and .o  files also have reduced 1.5 times.
And the time of type checking  _does not change_.
But compilation costs 10 times more, so that the effect is considerable. 

I wonder of whether unnecessary "open import" items effect the type check cost or compilation cost
(when the module source changes, it takes a considerable effort to get free of unused import).
  
Mainly, I think, my request can be withdrawn.

**Comment by andreasabel** [comment]
OK, closing.
