### ISSUE TITLE
Termination checker bug with CATCHALL

### ISSUE THREAD

**Issue by marvin-meller** [agda/agda#6687]
I think I found a bug in the termination checker in combination with the `{-# CATCHALL #-}` pragma. I stumbled across this using `2.6.3` but the bug persist when using the nightly build `38bd179@master`.

The following code is accepted both without options and with `--exact-split`. If the `{-# CATCHALL #-}` line is removed, the termination checker rightfully complains. (I made the implicit `n` explicit to show that `bad` really calls itself with unchanged arguments.)

```agda
module Bad where

open import Agda.Primitive public renaming (Set to Type)
open import Agda.Builtin.Nat public

private variable
  n m : Nat

data Vect {ℓ} (A : Type ℓ) : Nat → Type ℓ where
  [] : Vect A 0
  _∷_ : A → Vect A n → Vect A (suc n)

postulate
  Fin : Nat → Type
  Term : Nat → Type

data Val (n : Nat) : Type where
  vclos : Vect (Val n) m → Term (suc m) → Val n

bad : Val n → Val n
bad {n} v@(vclos (_ ∷ _) _) = bad {n} v
{-# CATCHALL #-}
bad (vclos vs t) = vclos vs t
```

In order to keep the example short I postulated `Fin` and `Term`. However, the example also (doesn't) work with the standard definition for `Fin` and any boring definition for `Term`. I can't seem to find any issue related to this. Is this a known bug or am I missing something obvious?

**Comment by andreasabel** [comment]
It seems that the termination checker does not see the recursive call when `{-# CATCHALL #-}`.
```agda

open import Agda.Primitive renaming (Set to Type)
open import Agda.Builtin.Nat

data Vect {ℓ} (A : Type ℓ) : Nat → Type ℓ where
  nil  : Vect A 0
  cons : (n : Nat) → A → Vect A n → Vect A (suc n)

data Val (n : Nat) : Type where
  vclos : (m : Nat) → Vect (Val n) m → Val n

bad : (n : Nat) → Val n → Val n
bad n v@(vclos _ (cons _ _ _)) = bad n v
{-# CATCHALL #-}
bad _ (vclos _ vs) = vclos _ vs

-- termination checking clause of bad
--   lhs: n (vclos (suc n₁) (cons n₁ x x₁))
--   rhs: bad (vclos (suc n₁) (cons n₁ x x₁))
-- termination checking clause of bad
--   lhs: n (vclos m vs)
--   rhs: vclos m vs
-- Calls (no dot patterns):
-- {Issue6687.bad} does termination check

-- Analysis: Termination checker does not see any recursive calls.
-- In contrast, everything works as expected without CATCHALL.

loop : (n : Nat) → Val n → Val n
loop n v@(vclos _ (cons _ _ _)) = loop n v
loop _ (vclos _ vs) = vclos _ vs

-- termination checking clause of loop
--   lhs: n (vclos (suc n₁) (cons n₁ x x₁))
--   rhs: loop (vclos (suc n₁) (cons n₁ x x₁))
-- termination checking clause of loop
--   lhs: n (vclos m vs)
--   rhs: vclos m vs
-- kept call from Issue6687.loop n (vclos (suc n₁) (cons n₁ x x₁))
--   to Issue6687.loop (n) (vclos (suc n₁) (cons n₁ x x₁))
--   call matrix (with guardedness):
--      =    ?    ?
--      ?    =    ?
--      ?    ?    =
```

**Comment by andreasabel** [comment]
Judging from the release notes for 2.6.1, this behavior was likely introduced by this PR:
- https://github.com/agda/agda/pull/4424

https://github.com/agda/agda/blob/38bd179d17d2eedd8f7ebeefde3ffc36eab444fd/doc/release-notes/2.6.1.md?plain=1#L405-L406

If the second clause rewrites the rhs of the first, the recursive call is indeed gone:
```agda
bad n v@(vclos _ (cons _ _ _)) = bad n v
{-# CATCHALL #-}
bad _ (vclos _ vs) = vclos _ vs
```
Maybe a fix is to _not_ reduce with catchall clauses.

**Comment by andreasabel** [comment]
Indeed, with `-v term.reduce:40` we see the following report:
```
termination checking clause of bad
  lhs: n (vclos (suc n₁) (cons n₁ x x₁))
  rhs: bad n (vclos (suc n₁) (cons n₁ x x₁))
Trying to reduce away call:  bad n (vclos (suc n₁) (cons n₁ x x₁))
This call is in the current SCC!
Function has 1 non-recursive exact clauses
Termination checker: Successfully reduced away call:
  bad n (vclos (suc n₁) (cons n₁ x x₁))
```

> Maybe a fix is to not reduce with catchall clauses.

We already do this:
https://github.com/agda/agda/blob/38bd179d17d2eedd8f7ebeefde3ffc36eab444fd/src/full/Agda/Termination/TermCheck.hs#L991-L996

> `Function has 1 non-recursive exact clauses`

Is maybe `{-# CATCHALL #-}` labelling a clause as exact?  Because this would be a lie.

**Comment by andreasabel** [comment]
The coverage checker somehow does not report a non-exact clause:
```
cover computed!
used clauses: fromList [0,1]
non-exact clauses: []
generated split tree for bad
split at 1
|
`- Issue6687.Val.vclos -> split at 2
   |
   +- Issue6687.Vect.nil -> done, 1 bindings
   |
   `- Issue6687.Vect.cons -> lazy split at 1
      |
      `- Agda.Builtin.Nat.Nat.suc -> done, 4 bindings

covering patterns for Issue6687.bad
  [_, vclos _ nil]
  [n, v@(vclos (suc n₁) (cons _ _ _))]
```

> Is maybe `{-# CATCHALL #-}` labelling a clause as exact? Because this would be a lie.

Look like this is the case: https://github.com/agda/agda/blob/38bd179d17d2eedd8f7ebeefde3ffc36eab444fd/src/full/Agda/TypeChecking/Coverage.hs#L307

This code stems from https://github.com/agda/agda/commit/cab4c8f93962149e6e5d388350bdef9b3702388b which fixed a previous issue with the "reduce with non-recursive clauses" feature and introduced the restriction to exact clauses:
- #5065

In this patch I retained the classification of CATCHALL clauses as exact.  This was wrong, as the present bug shows.
