### ISSUE TITLE
Shape-irrelevant variables marked as irrelevant in human-readable context

### ISSUE THREAD

**Issue by anuyts** [agda/agda#6706]
Agda version: 2.6.3-b499d12

In the following code, we can simply give the content of the hole, but `C-c` `C-,` reports that `n` is irrelevant.

```agda
{-# OPTIONS --experimental-irrelevance #-}

postulate
  Nat : Set
  SList : ..Nat → Set → Set
  [] : {X : Set} → .{n : Nat} → {!SList n X!}
```

```
Goal: _2
————————————————————————————————————————————————————————————
n : Nat   (irrelevant)
X : Set
```

**Comment by andreasabel** [comment]
Er, sorry, didn't look closely before.  Isn't this working as intended?
`n` is indeed irrelevant in the context of the hole.  It is still allowed as argument of `SList` because of `--experimental-irrelevance`.

**Comment by anuyts** [comment]
...because it is *shape-irrelevant* in the context of the hole.

We should have
```
Γ, ..(x : A) |– B x : Set
--------------------------------
Γ |– .(x : A) -> B x : Set
```

**Comment by anuyts** [comment]
A more basic example:
```agda
{-# OPTIONS --experimental-irrelevance #-}

postulate
  test : ..(X : Set) → {!!}
```
```
Goal: _27
————————————————————————————————————————————————————————————
X : Set   (irrelevant)
```
It's just labelling shape-irrelevant variables as irrelevant.

**Comment by andreasabel** [comment]
Thanks for the explanation.  I already forgot how it works. :$

**Comment by andreasabel** [comment]
The responsible code (added exactly 4 years ago on 2019-06-26) is here: https://github.com/agda/agda/blob/7ccefa4e252d1821dd16b4d128f44c9f3c603955/src/full/Agda/Interaction/EmacsTop.hs#L350-L351
- #3855

**Comment by anuyts** [comment]
Will the code in PR #6385 already rectify this?
@jorisceulemans @jpoiret

Edit: Clearly [no](https://github.com/agda/agda/pull/6385/files), but maybe @jorisceulemans 's code is not actually part of the PR?

**Comment by andreasabel** [comment]
Wasn't hard to do a PR for this:
- #6709 

This one can go into 2.6.4 as it is a small change.

**Comment by anuyts** [comment]
FWIW, @jorisceulemans reports that they only worked on how polarities are printed.
