### ISSUE TITLE
Internal error on `primStringUncons` when no builtin Sigma provided

### ISSUE THREAD

**Issue by caryoscelus** [agda/agda#6711]
> An internal error has occurred. Please report this as a bug.
> Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/Primitive.hs:96:25 in Agda-2.6.3-4SMRUe9PON5ygCFeXLsDJ:Agda.TypeChecking.Primitive

basically i've copypasted builtin string definition from documentation (w/o having default imports)

```
primitive
  primStringUncons : String → Maybe (Σ Char (λ _ → String))
```

other primitive referencing built-ins seem to work properly (reporting lack of builtin bindings), but lack of Sigma reports internal error instead

here is self-contained file to reproduce this: https://github.com/caryoscelus/chunks-of-agda/blob/main/ImpossiblePrimitive.agda

Agda is installed from NixOS (23.05, using `(unstable.agda.withPackages [agdaPackages.standard-library])`)
Agda version: 2.6.3
GHC version: 9.2.8

**Comment by andreasabel** [comment]
The internal error is raised here: https://github.com/agda/agda/blob/8068dbf5d0650ced15310ee7b67a57299f7ed057/src/full/Agda/TypeChecking/Primitive.hs#L94-L96
Issue still exists on `master`.
