### ISSUE TITLE
infinite type checking due to "with" ?

### ISSUE THREAD

**Issue by mechvel** [agda/agda#6712]
This is on Agda-2.6.3 under ghc-9.2.7, Ubuntu Linux 18.04,
Agda installed by
```
> cabal install -foptimise-heavily
```
Type checking is by
``` 
> agda $agdaLibOpt --auto-inline --guardedness  Test.agda  +RTS -M14G
```
The machine is of 32 Gb RAM, 3 GHz.

The below module takes kind of infinite time to type-check (looks like an infinite loop).
Changing `with` to `case` makes it type-checked in several seconds.

Here Polynomial (Pol) is defined over the structure DecCommutativeRing for coefficients.
Pol-Read defines parsing of a polynomial via the structure C-Read for parsing coefficients.
Here the coefficient domain is put ℚ - rational numbers.
In this application, ℚ is defined via the general constructor Fraction, when it is applied to Integer.
ℚ-Read is a structure defining parsing to rational.
So, the below Pol-Read defines parsing to Pol via parsing to ℚ.

Probably, the `with` construct expands these definitions of ℚ-Read, Pol-Read so greatly that type checking looks like an infinite loop.
Also Pol-Read relies on arithmetic functions defined for Pol, which is not so simple.

Generally, I rely on `with` --- following the recommendation found somewhere, probably in Standard library.
It is often simpler than `case_of_`.
But now, I wonder.
Type checking of Application takes 12 minutes under -M7G on a 3 GHz machine.
Now, what I need to try?
To change `with` to `case_of_` almost everywhere (a thousand of places) in a hope to reduce the time to 2 minutes?

I set `with` and `where` everywhere where this makes the program look simple and is allowed by the type checker.
And all the application is type-checked in 12 minutes.
Now, I add this Test.agda, and the approach is broken.
This is the first attempt with parsing a data constructed with more than two constructors.
For example, Pol over ℤ has two domain constructors.
And Test.agda has  Pol over Fraction over ℤ.
And currently, I need  Residue over Pol over Fraction over ℤ.

So, "if the last module hangs type checking, then consider changing `with` with `case_of_` in this module" ?

```
module Test where
open import Data.String using (String)
open import Data.Sum    using (_⊎_; inj₁; inj₂)
open import Function    using (case_of_)

-- of Application ---
open import ReadShow.OfRead   using (Read)
open import Fraction.Rational using (ℚ; ℚ-decCommutativeRing; ℚ-Read; ℚ-Show)
import Pol.Univariate.OverDecComRing as PolOverDecComm
import Pol.Univariate.ReadAndShow    as PolReadShow

open PolOverDecComm ℚ-decCommutativeRing "x" using (Pol; 0ₚ)
open PolReadShow    ℚ-decCommutativeRing "x" ℚ-Read ℚ-Show  using (Pol-Read; Pol-Show)

readPol : String → Pol
readPol str  with Read.readSTo⊎ Pol-Read str
... | inj₁ f = f
... | inj₂ _ = 0ₚ

{-
     =  case Read.readSTo⊎ Pol-Read str  of \  { (inj₁ f) → f
                                               ; (inj₂ _) → 0ₚ  }
-}

**Comment by plt-amy** [comment]
Hi @mechvel! Could you include a complete reproducer for the issue you're seeing? If you can't minimize it, please include a link to a Git repository where we can find all of the relevant code. Thanks!

**Comment by mechvel** [comment]
The code is about half of the library which I am going to publish this year.
I have reduced the test a bit. it is  213 K byte archive.
It can be reduced further, but I have not time now to do this.
For example, I could send the archive by `email` to some leader in the Agda team that manages bug processing.
The matter is that it is only for debugging, not for publication - so far.

Another way could be to finish the library and to publish it, and then to public here the source for the above report. 
But this may take 2-4 months.
?

**Comment by UlfNorell** [comment]
`with` is more expensive than `case` so without further information I see no reason to suspect this is a bug. Closing for now, reopen if you have a concrete (preferably minimised) example.
