### ISSUE TITLE
Type checking loops on certain pattern match in cubical (regression in 2.6.3)

### ISSUE THREAD

**Issue by mkm** [agda/agda#6715]
Using Agda 2.6.3, type checking the following program seemingly loops forever.
```agda
    {-# OPTIONS --cubical #-}
    module Diverge where

    open import Agda.Builtin.Cubical.Path
    open import Agda.Primitive.Cubical
      renaming (primTransp to transp; primIMin to _∧_; primINeg to ~_)

    data U : Set
    data IsA : U → Set

    data U where
      a : U
      squash : ∀ x y → x ≡ y

    data IsA where
      is-a : IsA a

    t : {x : U} → IsA x → IsA x
    t is-a = transp (λ i → IsA (squash a a i)) i0 is-a

    lemma : {x : U} (p : IsA x) → PathP (λ i → IsA (squash x x i)) p (t p)
    lemma is-a i = transp (λ j → IsA (squash a a (i ∧ j))) (~ i) is-a
```
I'm not quite sure if the program ultimately should be accepted or rejected. Small variations like specialising `lemma` with `x = a` instead lead to "not sure if there should be a case for `is-a`".

**Comment by andreasabel** [comment]
Works fine with Agda 2.6.0 - 2.6.2, starts failing at 2.6.3.

The mutual block is not necessary to produce the loop, this also works:
```agda
{-# OPTIONS --cubical #-}

open import Agda.Builtin.Cubical.Path
open import Agda.Primitive.Cubical
  renaming (primTransp to transp; primIMin to _∧_; primINeg to ~_)

data U : Set where
  a : U
  squash : ∀ x y → x ≡ y

data IsA : U → Set where
  is-a : IsA a

t : {x : U} → IsA x → IsA x
t is-a = transp (λ i → IsA (squash a a i)) i0 is-a

lemma : {x : U} (p : IsA x) → PathP (λ i → IsA (squash x x i)) p (t p)
lemma is-a i = transp (λ j → IsA (squash a a (i ∧ j))) (~ i) is-a
```

@plt-amy : Could you take a look?

**Comment by andreasabel** [comment]
There were only two relevant commits to `IApplyConfluence` in the period before the 2.6.3 release, and none looked very promising to be responsible.  But bisection claims:
1fd6b9fdfdfa143b3b4b2b71ae13c008a267190e is the first bad commit
Date:   Mon Oct 24 19:03:08 2022 -0300
> re #6017: add a Call for IApplyConfluence (#6218)
    
> Improves error messages when matching on a higher constructor, and the
> cause of failure is non-obvious (e.g. some arbitrary subterm of a big hcomp is printed).

Ran `agda-bisect --with-cabal cabal-3.2 -w ghc-9.0.2 --good v2.6.2 --bad v2.6.3 --timeout=5 --cabal-option=-O0  Issue6715.agda`.
