### ISSUE TITLE
Cubical: internal error in `Reduce.hs` (regression in 2.6.3)

### ISSUE THREAD

**Issue by dolio** [agda/agda#6725]
Here's another IMPOSSIBLE error. I was able to minimize it a bit better this time.

The reported error is in Agda.TypeChecking.Reduce, line 220.

I'm not certain if cubical is actually important, but I wasn't able to get the problem to occur without an eliminator with a `PathP` involved. Note that actually implementing `case` below is important. If you just replace the definition with a hole, the error doesn't happen.

I also tried using the circle type instead of the interval, and it didn't occur in that case.

Tested with the latest version of agda as of a few minutes ago.

```agda
{-# OPTIONS --cubical #-}

module Minimize where
open import Agda.Primitive
open import Agda.Builtin.Cubical.Path

variable
  ℓ : Level
  A : Set

data 𝕀 : Set where
  zero one : 𝕀
  seg : zero ≡ one

record R : Set₂ where
  field
    Φ : Set₁
    ze : Φ
    on : Φ
    se : ze ≡ on

record C : Set₂ where
  field
    Φ : 𝕀 -> Set₁
    ze : Φ zero
    on : Φ one
    se : PathP (λ i → Φ (seg i)) ze on

-- implementation doesn't matter
rec : (a : R) -> 𝕀 -> R.Φ a
rec a = ?

case : (a : C) -> (i : 𝕀) -> C.Φ a i
-- replacing this definition with a ? avoids the problem
case a = λ where
    zero -> ze
    one  -> on
    (seg i) -> se i
  where open C a

whoa : 𝕀 -> 𝕀 -> Set
whoa = rec alg where
  open R
  open C

  alg : R
  alg .Φ = 𝕀 -> Set
  alg .ze = case λ where
    .Φ _ → Set
  alg .on = case λ where
    .Φ _ → Set
  -- commenting this case avoids the problem
  alg .se i = case λ where
    .Φ _ → {!!}
    .ze → ?
    .on → ?
```

**Comment by andreasabel** [comment]
@dolio, thanks for the report!

Agda 2.6.0/1/2 report:
```
Issue6725.agda:48,5-9
Incomplete pattern matching for .extendedlambda0. Missing cases:
  ze .extendedlambda0
  on .extendedlambda0
  se .extendedlambda0
when checking the definition of .extendedlambda0
Issue6725.agda:50,5-9
Incomplete pattern matching for .extendedlambda1. Missing cases:
  ze .extendedlambda1
  on .extendedlambda1
  se .extendedlambda1
when checking the definition of .extendedlambda1
Issue6725.agda:53,5-55,8
Incomplete pattern matching for .extendedlambda2. Missing cases:
  se (.extendedlambda2 i)
when checking the definition of .extendedlambda2
Issue6725.agda:45,3-6
se (λ { .Φ _ → Set }) i !=
se
(λ { .Φ _ → Set
   ; .ze → ?2 (i = Agda.Primitive.Cubical.i0)
   ; .on → ?3 (i = Agda.Primitive.Cubical.i0)
   })
i
of type Set
when checking the definition of alg
```
So, it is a regression in 2.6.3.

**Comment by andreasabel** [comment]
Bisection blames the same commit: 1fd6b9fdfdfa143b3b4b2b71ae13c008a267190e is the first bad commit
Date:   Mon Oct 24 19:03:08 2022 -0300

  re #6017: add a Call for IApplyConfluence (#6218)
    
@plt-amy : Maybe this is already fixed by your recent PR?

**Comment by plt-amy** [comment]
I see what happened: I forgot to reset to the state packed in the `TypeError` when deciding whether or not to add the error message details, so trying to print any meta created during conversion checking results in fireworks.. Easy fix, 14 lines of diff; but it _is_ 5 in the morning, so I'll write the PR after I get some sleep.
