### ISSUE TITLE
Alias in constructor index foils the forcing analysis

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#6744]
Consider the following file:
```agda
open import Agda.Builtin.Nat

suc' = suc

data D : Nat → Set where
  c : (@0 n : Nat) → D (suc' n)

foo : (n : Nat) → D n → Set
foo n (c _) = ?
```
Agda complains:
```
I'm not sure if there should be a case for the constructor c,
because I get stuck when trying to solve the following unification
problems (inferred index ≟ expected index):
  suc' n ≟ n₁
Possible reason why unification failed:
  Cannot solve variable n of type Nat with solution suc' n₁ because
  the solution cannot be used at relevant, unrestricted modality
when checking that the pattern c _ has type D n
```
However, replacing `suc'` by `suc` in the type of `c` makes the file pass the typechecker.

**Comment by jespercockx** [comment]
The problem seems to be caused by the fact that normally Agda recognizes `n` as forced, but this analysis is easily foiled by making the constructor into an alias. Should we reduce indices during the forcing analysis?

**Comment by andreasabel** [comment]
Maybe this issue is back:
- #3898

However the OP is (also) triggered by the erasure annotation `@0 n`.

**Comment by andreasabel** [comment]
For some reason, we decided against normalization:
https://github.com/agda/agda/blob/632954bf442192276ca9c84ca95991d1ffc7a410/src/full/Agda/TypeChecking/Forcing.hs#L97-L106
- https://github.com/agda/agda/issues/1469

**Comment by andreasabel** [comment]
> However the OP is (also) triggered by the erasure annotation `@0 n`.

Which does not affect the forcing analysis but triggers the error in the LHS checker.
