### ISSUE TITLE
Strange interaction between `opaque` and `let open`

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#6745]
Consider the following Agda file:
```agda
module _ where

module M (A : Set₂) where

  opaque
    X : Set₂
    X = A

module N (let open M Set₁) where

  opaque
    unfolding X

    Y : X
    Y = Set
```
Agda rejects this:
```
Set₁ !=< X
when checking that the expression Set has type X

———— Warning(s) ————————————————————————————————————————————
warning: -W[no]UnfoldTransparentName
The name ModuleAppUnfolding.X, mentioned by an unfolding clause,
does not belong to an opaque block. This has no effect.
```
This is fixed by changing the unfolding clause to `unfolding M.X`, or by moving the `open M Set₁` from the module telescope to a standalone declaration.

(As a side note, I've been using `opaque` for two days now and this is the first real issue I ran into with it. Great job @plt-amy on the implementation of this feature!)

**Comment by plt-amy** [comment]
Thanks for the report @jespercockx! I finally got a chance (and the energy..) to look into this one. The issue is essentially the same as for #6665, except since this copy happens in a section telescope, it doesn't survive the scope checker to get picked up by my fix for that.
