### ISSUE TITLE
Order of deserialization depends on build of Agda (version of `hashable`)

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#6750]
`test/Succeed/ImportWarnings` sees a different order of warnings when Agda is built with stack, at least since `nightly-2023-08-04`: https://github.com/agda/agda/actions/runs/5765129591/job/15631277883#step:10:25
I can reproduce this locally if I run the testsuite with a `stack-9.6.2.yaml`-built Agda
```diff

+Issue708quote.agda:9,1-29
+warning: -W[no]UnreachableClauses
+Unreachable clause
+when checking the definition of example
+
 Unreachable.agda:21,1-23,19
 warning: -W[no]UnreachableClauses
 Unreachable clauses
 when checking the definition of unreachable
 
-Issue2243.agda:9,1-12
-warning: -W[no]UnreachableClauses
-Unreachable clause
-when checking the definition of f
-
 RewritingEmptyPragma.agda:3,1-16
 warning: -W[no]EmptyRewritePragma
 Empty REWRITE pragma
 when scope checking the declaration
   {-# REWRITE #-}
 
-Issue708quote.agda:9,1-29
+Issue2243.agda:9,1-12
 warning: -W[no]UnreachableClauses
 Unreachable clause
-when checking the definition of example
+when checking the definition of f
```
The relative order
1. `Unreachable` / `unreachable`
2. `Issue2243` / `f`
3. `RewritingEmptyPragma`
4. `Issue708quote` / `example`

changes to 
1. `Issue708quote` / `example`
2. `Unreachable` / `unreachable` 
3. `RewritingEmptyPragma`
4. `Issue2243` / `f`

Observe that neither corresponds to the order of `import`s in `ImportWarningsB`:
```agda
import Issue2243
import Issue708quote
import RewritingEmptyPragma
import Unreachable
```

This issue might or might not be related to a permutation of messages I see for `test/interaction/Issue6261`:
https://github.com/agda/agda/actions/runs/5765129591/job/15631277728#step:11:224
```diff
 (agda2-info-action "*Type-checking*" "Loading Issue6261 (_build/2.6.4/agda/Issue6261.agdai). " t)
-(agda2-info-action "*Type-checking*" " Loading Issue6261a (_build/2.6.4/agda/Issue6261a.agdai). " t)
 (agda2-info-action "*Type-checking*" " Loading Issue6261b (_build/2.6.4/agda/Issue6261b.agdai). " t)
 (agda2-info-action "*Type-checking*" " Loading Issue6261c (_build/2.6.4/agda/Issue6261c.agdai). " t)
+(agda2-info-action "*Type-checking*" " Loading Issue6261a (_build/2.6.4/agda/Issue6261a.agdai). " t)
 (agda2-status-action "Checked")
```

**Comment by andreasabel** [comment]
I think the order of deserialization is the cause of these effects.  I put blame on e9399a1add3b82ff2fa45b976d39d05d4eccf4ce (ping @nad) for organizing the imported module in a `HashSet` that does not have a well-defined linearization to lists.  So, depending on which hashing algorithm we get from upstream, Agda will now deserialize imports in a different order.  `hashable` recently changed its algorithm from 1.4.2.0 to 1.4.3.0 (why is this just a minor version bump?):
- https://github.com/haskell-unordered-containers/hashable/issues/270
- https://github.com/haskell-unordered-containers/hashable/compare/v1.4.2.0...v1.4.3.0

Here is my reconstruction:
- `stImportedModules` gives a `HashSet TopLevelModuleName`: https://github.com/agda/agda/blob/1763ac7c498b3638b0a5a26addfd18b6d05b8568/src/full/Agda/TypeChecking/Monad/Base.hs#L481-L482
- this is turned into a list and stored in `iImportedModules` https://github.com/agda/agda/blob/1763ac7c498b3638b0a5a26addfd18b6d05b8568/src/full/Agda/Interaction/Imports.hs#L1235-L1237 https://github.com/agda/agda/blob/1763ac7c498b3638b0a5a26addfd18b6d05b8568/src/full/Agda/Interaction/Imports.hs#L1272
- we iterate over `iImportedModules` to deserialize: https://github.com/agda/agda/blob/1763ac7c498b3638b0a5a26addfd18b6d05b8568/src/full/Agda/Interaction/Imports.hs#L735-L738 https://github.com/agda/agda/blob/1763ac7c498b3638b0a5a26addfd18b6d05b8568/src/full/Agda/Interaction/Imports.hs#L1321-L1322 https://github.com/agda/agda/blob/1763ac7c498b3638b0a5a26addfd18b6d05b8568/src/full/Agda/Interaction/Imports.hs#L479-L483

**Comment by sattlerc** [comment]
> `hashable` recently changed its algorithm from 1.4.2.0 to 1.4.3.0 (why is this just a minor version bump?):

From the documentation of the `Hashable` type class:

> Note: the hash is not guaranteed to be stable across library versions, operating systems or architectures. For stable hashing use named hashes: SHA256, CRC32 etc.

**Comment by andreasabel** [comment]
> > Note: the hash is not guaranteed to be stable across library versions, operating systems or architectures. For stable hashing use named hashes: SHA256, CRC32 etc.

Thanks, but we don't have a choice since `unordered-containers` makes the choice of hash function.  
Maybe `HashSet.toList` (and similar) should have a disclaimer like above.
- https://github.com/haskell-unordered-containers/unordered-containers/issues/481

**Comment by sattlerc** [comment]
It does say that:

> A [HashSet](https://hackage.haskell.org/package/unordered-containers-0.2.19.1/docs/Data-HashSet.html#t:HashSet) makes no guarantees as to the order of its elements.

**Comment by andreasabel** [comment]
The `HashSet` itself is an abstract data types, so "the order of its elements" isn't even something I'd consider defined.  An order only becomes manifest in the folding operations the interface provides.  Doesn't hurt to point it out there.
Anyway, why are we discussing this here?  
Implementors have been using folds like `toList` for hash collections too carelessly.
I despise hashing.

**Comment by nad** [comment]
> I think the order of deserialization is the cause of these effects. I put blame on [e9399a1](https://github.com/agda/agda/commit/e9399a1add3b82ff2fa45b976d39d05d4eccf4ce) (ping @nad) for organizing the imported module in a `HashSet` that does not have a well-defined linearization to lists.

Good catch. I guess I didn't think the order of the modules mattered.
