### ISSUE TITLE
Hackage rejects our license setting

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#6755]
https://github.com/agda/agda/blob/9b09d72f5ccea2675b0435168e670e2fe978f580/Agda.cabal#L5-L6
```
Error uploading
/Users/abel/agda-erasure/dist-newstyle/sdist/Agda-2.6.3.20230805.tar.gz: http code 400
Error: Invalid package

This server does not accept packages with 'license' field set to e.g.
AllRightsReserved. See https://hackage.haskell.org/upload for more information
about accepted licenses.
```
https://hackage.haskell.org/upload

**Comment by andreasabel** [comment]
But we are actually MIT, so let's name it like that! https://choosealicense.com/licenses/mit/

**Comment by nad** [comment]
> But we are actually MIT

The following part of the licence is not an MIT licence:

https://github.com/agda/agda/blob/826a8014083d1d9f8050850b569fad639172dcf5/LICENSE#L49-L74

**Comment by andreasabel** [comment]
Rewriting this 20 line JS script from scratch will solve this licence conundrum once and for all.
