### ISSUE TITLE
Our interface format implicitly depends on the version of `hashable`

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#6761]
https://github.com/agda/agda/blob/f5d989919362f86049212922bd9fb869a3fd405c/src/full/Agda/TypeChecking/Serialise/Instances/Common.hs#L468-L470
To order of `HMap.toList` is undefined, in particular, it depends on the version of `hashable` Agda is built against.
Thus, either we need to make the version of `hashable` part of our interface version, or we need to make ourselves independent of the latter.  This means, sorting before serialization.
CC: @UlfNorell @SquidDev

Cf:
- #6750
- https://github.com/haskell-unordered-containers/hashable/issues/277 (hashing algorithm not subject to PVP)

**Comment by SquidDev** [comment]
Probably being silly here, but in what cases does this matter? While two different versions of hashable will produce different interface files, I'd expect the two files to be compatible with each other - the order doesn't matter when deserialising.

**Comment by andreasabel** [comment]
Er, right. So maybe this isn't a problem.

The question is whether we want the interface file to be bit-determined by inputs and the interface version, or whether we allow a quotient.  

Atm, there isn't a written spec on what exactly the semantics of `currentInterfaceVersion` is, there is just this comment: https://github.com/agda/agda/blob/f5d989919362f86049212922bd9fb869a3fd405c/src/full/Agda/TypeChecking/Serialise.hs#L11-L17 https://github.com/agda/agda/blob/f5d989919362f86049212922bd9fb869a3fd405c/src/full/Agda/TypeChecking/Serialise.hs#L83-L85
