### ISSUE TITLE
Refine doesn't find proof of refl=refl without K

### ISSUE THREAD

**Issue by Sean-Watters** [agda/agda#6787]
**Agda version:** 2.6.3

## Code
```agda
{-# OPTIONS --safe --without-K -v tc.cover.split:50 #-}

open import Agda.Builtin.Equality

foo : ∀ {ℓ} {X : Set ℓ} {x : X} → _≡_ {A = x ≡ x} (refl {x = x}) (refl {x = x})
foo = {!!}
```

```
Goal: refl ≡ refl
————————————————————————————————————————————————————————————
n : X   (not in scope)
X : Set ℓ   (not in scope)
ℓ : Agda.Primitive.Level   (not in scope)
```

## Steps to reproduce
* Load the above code with `C-c C-l`.
* Attempt to refine the empty goal with `C-c C-r`.

## Expected behaviour
Agda fills the goal with `refl`.

## Actual behaviour
```
No introduction form found.
```
Agda does not see that `refl` is a proof of `refl ≡ refl`, and the goal is not filled. After manually typing "refl" into the goal, both `C-c C-r` and `C-c C-SPC` work as expected, and the proof is accepted.

When `--without-K ` is replaced by `--with-K`, this issue does not exist.

## Debug output
[debug.log](https://github.com/agda/agda/files/12429486/debug.log)

**Comment by Sean-Watters** [comment]
From further in-person discussions: philosophically speaking, this may not be a bug. With Cubical Agda, there may be multiple different proofs of `refl ≡ refl`, and you wouldn't want to privilege one over the others. But from that PoV, the error message currently isn't great; `refl` is definitely a valid proof, it just may not be unique, so "no introduction form found" is a bit misleading. (Whether that's actually what's happening under the hood, I don't know).

On the other hand, this issue talks about merely being `--without-K`, not `--cubical` - in this scenario, always choosing `refl` may be justified?

**Comment by gallais** [comment]
I am happy to relax the #6789 patch so that it only suggests `refl` if we are in anything
"below" `--cubical` (i.e. any mode up to and including `--cubical-compatible` mode).

**Comment by fredrikNordvallForsberg** [comment]
Trying to think though the situation: if we are below `--cubical`, we are also promising to be `--with-K` compatible, so it is right that `refl` is the only thing we can give. That is, the patch seems to me to do the right thing in that case.

**Comment by gallais** [comment]
Thanks for the confirmation! Done.
