### ISSUE TITLE
With-clause causes greedy introduction of implicit

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#679]
When using a with-clause whilst there is an implicit on the right, it makes it disappear which prevents the user from being able to name it the way she wanted to (using a lambda).

A dumb example where the implicit cannot be introduced everywhere because it does not appear in some of the case (namely the `eq-sym ♭ h` one).

``` agda
module implicit-disappeared where

data ty : Set where
  ♭ : ty
  _`→_ : ty → ty → ty

⟦_⟧ : ty → Set
⟦ ♭ ⟧ = ⊤
⟦ A `→ B ⟧ = ⟦ A ⟧ → ⟦ B ⟧

eq : ∀ (σ : ty) (a b : ⟦ σ ⟧) → Set
eq ♭ a b = a ≡ b
eq (A `→ B) f g = ∀ {a : ⟦ A ⟧} → eq B (f a) (g a)

eq-sym : ∀ σ {a b} (h : eq σ a b) → eq σ b a
eq-sym ♭ h = refl
eq-sym (A `→ B) h with B
... | B' = {!!}
```

Original issue reported on code.google.com by `sble...@gmail.com` on 20 Jul 2012 at 8:41

**Comment by UlfNorell** [comment]
Slight variation

``` agda
data Ty : Set where
  _=>_ : (a b : Ty) → Ty

⟦_⟧ : Ty → Set
⟦ a => b ⟧ = ⟦ a ⟧ → ⟦ b ⟧

eq : (a : Ty) → ⟦ a ⟧ → ⟦ a ⟧ → Set
eq (a => b) f g = ∀ {x y : ⟦ a ⟧} → eq a x y → eq b (f x) (g y)

-- Too few arguments in with clause!
bad : (a : Ty) (x : ⟦ a ⟧) → eq a x x
bad (a => b) f h with b
bad (a => b) f h | _ = {!!}
```

**Comment by andreasabel** [comment]
My patch fixes the "Slight variation" example of UlfNorell.

**Comment by Blaisorblade** [comment]
@andreasabel Because of your patch, this should be closed (IIUC). Doing that to tidy up.
