### ISSUE TITLE
Safe Agda accepts `{-# TERMINATING #-}` pragma in `interleaved mutual` block

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#6794]
The final line in the following traversal is a catch-all forbidden by our style guide. 
https://github.com/agda/agda/blob/049b1954fdaba9ca113b5fc27f3ea6bc0da33ae6/src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs#L1458-L1472
 It has lead to bit-rot of the fix for
- #3983

Agda now accepts `{-# TERMINATING #-}` in `--safe` mode again, in the new block forms `interleaved mutual` and `opaque`.
```agda
{-# OPTIONS --safe #-}

data ⊥ : Set where

interleaved mutual

  {-# TERMINATING #-}
  k : ⊥
  k = k

opaque

  {-# TERMINATING #-}
  l : ⊥
  l = l
```
 This costs you a beer, @gallais, unless you have a good excuse. 😄

**Comment by andreasabel** [comment]
After I did several rewrites of this recursive check for unsafe pragmas over the weekend I started wondering why it is _here_ in the first place, and not part of the nicifier.  In particular: we do traversals over the concrete syntax touching the pragmas (in the nicifier and in the scope checker), so why do we need a independent traversal here?  Can we check this "along the way"?
@gallais, do you remember?

**Comment by gallais** [comment]
It seems to go back to #1614 which itself references a commit by a certain Andreas Abel: https://github.com/agda/agda/commit/718b175fe81e9b9c4ffea3e270fdb40758c48dbf

:smile:

**Comment by andreasabel** [comment]
Mmpf.

BUT, back then it was non-recursive, not looking into subdeclarations.
Since you pimped it up, it looks into subdeclarations, but not all, e.g. not inside modules.  That's why I cannot use a generic fold looking at all subdeclarations.  

I suppose it is better to handle unsafe pragmas in the nicifier, because they are forbidden with `--safe` in any context, so we can cast the warnings before we nicify the pragmas.
