### ISSUE TITLE
Missing warning about discarded `{-# TERMINATING #-}` pragma in `where` block inside `interleaved mutual` block

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#6795]
The final line in the following traversal is a catch-all forbidden by our style guide. 
https://github.com/agda/agda/blob/9f2292c4ea35d55ad54b8502f3dbbf88f9c46d94/src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs#L2751-L2763
It has lead to bit-rot of the fix for
- #4400 

Agda now silently ignores `{-# TERMINATING #-}` in `record` declarations and `where` blocks again, if hidden in the new block forms `interleaved mutual` and `opaque`.
```agda
record M : Set where
  interleaved mutual
    {-# TERMINATING #-}
    m : ⊥
    m = m

record N : Set where
  opaque
    {-# TERMINATING #-}
    n : ⊥
    n = n

O : Set₁
O = Set where
  interleaved mutual
    {-# TERMINATING #-}
    o : ⊥
    o = o

  opaque
    {-# TERMINATING #-}
    o' : ⊥
    o' = o'
```
All these raise termination errors, not warning about `{-# TERMINATING #-}` being ignored.
 This costs you a beer, @UlfNorell, unless you have a good excuse. 😄

**Comment by andreasabel** [comment]
This test became incomplete with the introduction of `interleaved mutual` in 2.6.2.

**Comment by UlfNorell** [comment]
I'm innocent! The function was introduced in Agda@74c84cd, moved to the top level (by you!) in Agda@424d61a, and finally refactored by me in Agda@cecbc02. The catch-all was there from the beginning.

**Comment by andreasabel** [comment]
Nice try, but...

> and finally refactored by me in [cecbc02](https://github.com/agda/agda/commit/cecbc02).

This introduced the recursion (deep check for termination pragmas) and the catch-all when deciding whether to go into subdeclarations.  It was bound to break whenever more declaration forms where introduced that grouped subdeclarations.
