### ISSUE TITLE
Incorrect warning for `module` inside an `opaque` block

### ISSUE THREAD

**Issue by MatthiasHu** [agda/agda#6802]
When I check this code with Agda version 2.6.3.20230805
```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Equality

opaque
  module _ where
    foo : Nat
    foo = zero

-- test : foo ≡ zero
-- test = refl  -- error: foo != zero of type Nat
```
I get these two warnings:
```
/home/matthias/dev/Agda/module-inside-opaque-test/test.agda:5,1-8,15
warning: -W[no]UselessOpaque
This `opaque` block has no effect.
when scope checking the declaration
  opaque
    unfolding {}
    module _ where
      foo : Nat
      foo = zero

/home/matthias/dev/Agda/module-inside-opaque-test/test.agda:6,3-8,15
warning: -W[no]NotAffectedByOpaque
Only functions and primitives can be marked opaque. This
declaration will be treated as transparent.
when scope checking the declaration
  module _ where
    foo : Nat
    foo = zero
```

But it is not true that "This `opaque` block has no effect.", as the error on the commented-out test shows. The code seems to behave just the same as defining `foo` in the `opaque` block without the module.

It is not clear to me how a `module` inside an `opaque` block *should* behave; the [documentation](https://agda.readthedocs.io/en/latest/language/opaque-definitions.html) does not mention it.
- It would seem reasonable if all functions in an `opaque` block, whether inside (possibly nested) modules or not, belong to that single `opaque` block (i.e., can only be made `unfolding` together), as it seems to be the case already. Then I would expect to see none of the two warnings for the example code.
- On the other hand, it might also be reasonable if a `module` inside an `opaque` block is simply forbidden, that is, raises an error instead of a warning.

**Comment by jespercockx** [comment]
I believe the intention for the design was that (for now) modules inside an `opaque` block should not be allowed. @plt-amy can you confirm or did you change it?

**Comment by jespercockx** [comment]
Putting this on 2.6.4 since `opaque` is a new feature.

**Comment by plt-amy** [comment]
It _should_ be disallowed (and have no effect!), but clearly something slipped past me.

Looking over the code, it's _obvious_, since going under an unaffected definition doesn't forget the opaque block, it just complains. Fix incoming...
