### ISSUE TITLE
Mutual recursion and `opaque`

### ISSUE THREAD

**Issue by nad** [agda/agda#6804]
I was trying to replace some uses of `abstract` with `opaque`, and encountered the following error:
```
The following names are declared, but not accompanied by a
definition: […].
Since `opaque` blocks can not participate in mutual recursion,
their definition must be given before this point.
```
If this works for `abstract`, then perhaps it can be made to work also for `opaque`.

**Comment by jespercockx** [comment]
I think this was an intentional design decision since it's not clear what the semantics should be, but perhaps @plt-amy can confirm.

**Comment by plt-amy** [comment]
That's correct. I don't quite remember the details now (perhaps we should've opened this issue during the AIM?), but it was decided that the way `abstract` interacts with mutual recursion was undesirable for `opaque`, and nothing better was proposed at the time. I'll try to remember...
