### ISSUE TITLE
Remove `GenericWarning`

### ISSUE THREAD

**Issue by nad** [agda/agda#6806]
I think that `GenericWarning` should be removed. One can turn off warnings using `-Wno`, and I think `-WnoGenericWarning` is too coarse-grained:
```agda
{-# OPTIONS -WnoGenericWarning #-}

opaque

  A = Set
```

**Comment by andreasabel** [comment]
Grepping returns only 2 uses of this warning, and both are for the same purpose:
From b839eb771bcf0780069894d2ead5f687cbc44dd8:
https://github.com/agda/agda/blob/20c0eff5bd9f518b91b3ba4f300080d8284645ca/src/full/Agda/Compiler/MAlonzo/Compiler.hs#L570-L571
From 1eec63b1c5566b252c0a4a815ce1df99a772c475:
https://github.com/agda/agda/blob/20c0eff5bd9f518b91b3ba4f300080d8284645ca/src/full/Agda/Compiler/MAlonzo/Compiler.hs#L585-L586
(The latter has a cut-and-paste error that should be fixed along the way.)

I am renaming this warning to `UselessGHCPragma`.

The proper way of handling this warning would likely be to introduce a warning mechanism in backends, however, this might be more relevant when there are more warnings...

**Comment by andreasabel** [comment]
Oops, there are more uses after all:
GHC backend:
https://github.com/agda/agda/blob/20c0eff5bd9f518b91b3ba4f300080d8284645ca/src/full/Agda/Compiler/MAlonzo/Compiler.hs#L1343-L1346
Builtins:
https://github.com/agda/agda/blob/20c0eff5bd9f518b91b3ba4f300080d8284645ca/src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs#L2476-L2479
`abstract`/`opaque`:
- #6805

https://github.com/agda/agda/blob/20c0eff5bd9f518b91b3ba4f300080d8284645ca/src/full/Agda/TypeChecking/Rules/Def.hs#L121-L125
Confluence checker:
https://github.com/agda/agda/blob/20c0eff5bd9f518b91b3ba4f300080d8284645ca/src/full/Agda/TypeChecking/Rewriting/Confluence.hs#L103-L105
https://github.com/agda/agda/blob/20c0eff5bd9f518b91b3ba4f300080d8284645ca/src/full/Agda/TypeChecking/Rewriting.hs#L156-L159
Duplicate rewrite rule:
https://github.com/agda/agda/blob/20c0eff5bd9f518b91b3ba4f300080d8284645ca/src/full/Agda/TypeChecking/Rewriting.hs#L390-L394

**Comment by nad** [comment]
Can this issue be closed now (see #7119)?

**Comment by jespercockx** [comment]
I'd like to petition this change to be reversed so that `GenericWarning` is still available to backends. With this change, it is no longer possible to raise a new warning in a sensible way.

**Comment by UlfNorell** [comment]
Perhaps we can add a generic `BackendWarning` constructor that takes the backend name and a `Doc`, to make sure we don't fall to temptation and start using `GenericWarning` again. And same for `GenericError` I suppose.
