### ISSUE TITLE
Pattern variables may not shadow data constructors, but may shadow record constructors

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#6829]
Commit 5d5095ba080b04f16867d4ed5af4ba7091f1a773 introduced a check that a pattern variable does not show a `data` constructor.  However, it does not check whether the variable shadows a `record` constructor.  This passes:
```agda
module A where

  record B : Set where
    constructor x; no-eta-equality; pattern

  data C : Set where
    c : B → C

open A using (C; c)

f : C → C
f (c x) = c x
```
In particular, no-eta pattern record constructors are similar to single data constructors so it feels odd that one should be allowed and the other not.

The original code implementing the shadowing check is mostly in place at: https://github.com/agda/agda/blob/283730b392d7c21c54b53b0f486802ec143e4af7/src/full/Agda/TypeChecking/Rules/LHS.hs#L357-L371
Neither code nor commit message comment on record constructors.  (It links to http://thread.gmane.org/gmane.comp.lang.agda/720 but gmane is dead.)
I cannot find an issue for this.
Maybe the code predates record constructors and was never updated?

Found this issue by reading Agda source code.

**Comment by andreasabel** [comment]
The check is from 2009; and record pattern matching was introduced in 2.2.8 in 2010:  https://github.com/agda/agda/blob/283730b392d7c21c54b53b0f486802ec143e4af7/doc/release-notes/2.2.8.md#L7-L9
So the check got outdated after a year and stayed like this for 13 years. 😆 

It also predates the warning mechanism.  It seems more appropriate to turn it into a warning, as it is just a hygiene issue.

When extending it to record constructors, the question is whether to raise it for all record constructors or only the `pattern` ones (which you can actually match on).  I suppose the latter is more correct.

**Comment by nad** [comment]
> It also predates the warning mechanism. It seems more appropriate to turn it into a warning, as it is just a hygiene issue.

The problem that this feature addresses is that the semantics of code can change (well-typed code can stay well-typed but get different semantics) if a private symbol is made public or vice versa in an imported module. Perhaps that falls under what you call "hygiene".
