### ISSUE TITLE
Follow XDG Base Directory Specification

### ISSUE THREAD

**Issue by 4e554c4c** [agda/agda#6852]
Currently, agda uses the legacy [`getAppUserDataDirectory`](https://hackage.haskell.org/package/directory-1.3.8.1/docs/System-Directory.html#v:getAppUserDataDirectory) to find `$AGDA_DIR` for its defaults and libraries files.

Instead, Agda should use `getXdgDirectory XdgConfig`, as these are user-modifiable configuration files, and fall back to `~/.agda` if necessary.

**Comment by andreasabel** [comment]
This should be coordinated with https://github.com/wenkokke/setup-agda @wenkokke.

**Comment by 4e554c4c** [comment]
as long as setup-agda creates `~/.agda` it should not need any coordination, since this directory will be fallen back to

**Comment by wenkokke** [comment]
I almost implemented this using `getXdgDirectory` by accident the first time around, so this is fine by me.
