### ISSUE TITLE
Agda rejects identity function on indexed datatype with erased index

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#6867]
Consider the following example:
```agda
postulate A : Set

data This : A → Set where
  this : (x : A) → This x

id-this : ∀ {@0 x} → This x → This x
id-this (this x) = this x
```
Agda complains:
```
Variable x is declared erased, so it cannot be used here
when checking that the expression x has type A
```
Without the `@0` in the type signature of `id-this`, the definition is accepted. Intuitively, it feels wrong that marking something in the type signature (which is anyway erased) with `@0` makes Agda consider a constructor argument to be erased.

This reminds me of a general issue with modalities in the LHS unifier that I remember discussing with @anuyts a long time ago, so perhaps he has an opinion on the matter.

**Comment by jespercockx** [comment]
Making things more explicit, Agda starts from the LHS `id-this {x} (this y)` which raises the unification problem `(@0 x : A) (y : A) |- x =?= y : A`. Agda decides to solve this problem by instantiating `y := x`, which feels like it is the wrong way around and is actually ill-typed: `x` is erased so we should not use it as the value of the non-erased variable `y`! I wonder if we can abuse this to break subject reduction. EDIT: I guess not, since the problem is that Agda is currently being too conservative.

**Comment by anuyts** [comment]
> Intuitively, it feels wrong that marking something in the type signature (which is anyway erased) with `@0` makes Agda consider a constructor argument to be erased.

This `@0` marking does not just concern the type signature. This is the type of functions taking an erased argument `x`.

**Comment by jespercockx** [comment]
> This `@0` marking does not just concern the type signature. This is the type of functions taking an erased argument x.

Well yes, but the argument to the `this` constructor is not marked as erased so I feel like I should be able to use it in non-erased positions on the RHS, even if the unifier happens to unify it with an erased variable.

**Comment by jespercockx** [comment]
Interesting observation: if you enable the `--no-forcing` flag, then the example is accepted. So the problem is somehow related to the forcing analysis doing something wrong. This makes me strongly suspect that there is indeed a bug here, since `--forcing` is not supposed to change whether something typechecks or not.

**Comment by anuyts** [comment]
The following works (although the content of the hole is not accepted):

```agda
postulate
  A B : Set
  f : A → B

data This : A → Set where
  this : (x : A) → This x

id-this : ∀ {@0 x} → This x → This x
id-this {.x} (this x) = {!this x!}

data That : B → Set where
  that : (x : A) → That (f x)

id-that : ∀ {@0 y} → That y → That y
id-that (that x) = that x

id : A → A
id a = a

data This' : A → Set where
  this' : (x : A) → This' (id x)

id-this' : ∀ {@0 x} → This' x → This' x
id-this' {.x} (this' x) = this' x
```

Conceptually, there is a coercion `A -> (@0 A)`, so indeed the correct thing to do in order to solve the unification problem `(@0 x : A) (y : A) |- x =?= y : A` is instantiating `x := y`, not the other way around.
A bit to my surprise, putting a dot on the erased implicit argument does not achieve this effect (does Agda currently ignore dots altogether?), but when we throw in a function `f` so that the wrong-way unification becomes impossible, the function does typecheck.
Again to my surprise, throwing in the identity function also does the job!

**Comment by jespercockx** [comment]
The problem seems likely to be introduced by @UlfNorell in https://github.com/agda/agda/commit/0539818a58dd049ccb2ede79ed304bc669fa1bf2 (fixing https://github.com/agda/agda/issues/3903).

**Comment by jespercockx** [comment]
Also relevant history: https://github.com/agda/agda/issues/4174

**Comment by jespercockx** [comment]
What I think is going on here is that Agda marks the argument to the `this` constructor as forced, which means that whenever we bind a pattern variable in its position, internally Agda will try to move that binding to "somewhere else" because *the argument is not actually stored*. The issue here is that that "somewhere else" happens to be a place marked with `@0`, which means that the variable can only be used in erased positions even though it was not marked as erased.

In this case I actually did *not* want the forcing analysis to kick in for this datatype. Two things that would be helpful for me:
- A way to turn off the forcing analysis for a specific datatype or constructor
- A way to restrict the forcing analysis to only consider arguments that are marked with `@0` (perhaps this should be the default behavior when `--erasure` is enabled).

**Comment by anuyts** [comment]
> A way to restrict the forcing analysis to only consider arguments that are marked with `@0` (perhaps this should be the default behavior when `--erasure` is enabled).

Does that mean that the constructor argument in
```agda
data This : A → Set where
  this : (x : A) → This x
```
would not be marked as forced, but in
```agda
data This : A → Set where
  this : (@0 x : A) → This x
```
it would? That seems like a very sensible solution.

**Comment by jespercockx** [comment]
Yes, that's what I'm proposing.
