### ISSUE TITLE
Markdown→HTML pipeline mishandles empty code blocks

### ISSUE THREAD

**Issue by ncfavier** [agda/agda#6873]
#### bug.lagda.md

````md
```agda
```

```agda
-- some code
```

some text
````

#### html/bug.md

```html
<pre class="Agda">
</pre><a id="22" class="Comment">-- some code</a>
<pre class="Agda">
some text
</pre>
```

Does not happen if the code block contains a blank line.

**Comment by ncfavier** [comment]
[`tokenStream`](https://github.com/agda/agda/blob/9e6776225a0ec19ce0cb4b047cc3b6c8a2a826c4/src/full/Agda/Interaction/Highlighting/HTML/Base.hs#L282) produces a single token for the whole empty code block:

```hs
(1,"```agda\n```\n",Aspects {aspect = Just Markup, otherAspects = fromList [], note = "", definitionSite = Nothing, tokenBased = TokenBased})
```

but then [`code`](https://github.com/agda/agda/blob/9e6776225a0ec19ce0cb4b047cc3b6c8a2a826c4/src/full/Agda/Interaction/Highlighting/HTML/Base.hs#L308) splits on these `Markup` tokens and treats the result as alternating code and markup, which is wrong in this case.

I think the right thing to do here would be to split `Markup` into `MarkupStart` and `MarkupEnd`.

**Comment by andreasabel** [comment]
`tokenStream` is https://github.com/agda/agda/blob/82f34279d20c07540a4e1084c023d0031e922df5/src/full/Agda/Interaction/Highlighting/HTML/Base.hs#L283-L293
`code` is https://github.com/agda/agda/blob/82f34279d20c07540a4e1084c023d0031e922df5/src/full/Agda/Interaction/Highlighting/HTML/Base.hs#L307

**Comment by andreasabel** [comment]
> I think the right thing to do here would be to split `Markup` into `MarkupStart` and `MarkupEnd`.

@ncfavier , thanks for this analysis!  
I am not familiar with the code, could you submit a PR implementing this idea?

**Comment by ncfavier** [comment]
> I think the right thing to do here would be to split `Markup` into `MarkupStart` and `MarkupEnd`.

That turned out not to be necessary: https://github.com/agda/agda/pull/6880
