### ISSUE TITLE
Contradictory constraints should yield error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#689]
```agda
open import Common.Equality

data D : Set1 where
  abs : ∀ E → D ≡ E → (E → D) → D
```
In batch mode, we get the message "Failed to solve the following constraints" plus a constraint without metas stating that 2 <=1 (in terms of levels).

Rather, I would expect an error message since these constraints are contradictory.

In interactive mode, I just get a buffer displaying these contradictory, without comment. 

Original issue reported on code.google.com by `andreas....@gmail.com` on 6 Sep 2012 at 1:38

**Comment by andreasabel** [comment]
Ported test case:
```agda
open import Agda.Primitive

data L {a} (A : Set a) : Set a where
  [] : L A
  _∷_ : A → L A → L A

data S {a} {A : Set a} : L A → Set₁ where
  [] : S []
  _∷_ : ∀ x xs → S (x ∷ xs)
```
displays (without highlighting):
```
Failed to solve the following constraints:
  @2 =< lsuc lzero
  a =< lsuc lzero
```
Note the out-of-scope de Bruijn index.  Which is apparently created by `TypeChecking.Forcing.force`.

**Comment by andreasabel** [comment]
Irgendwie wird hier die `ProblemId` verschlampert.
The problem id gets lost while solving level constraints!?  If I understand the log correctly:
```
{ working on problems [18]
adding constraint [18] a =< lsuc lzero
no simplification
waking up         []
  still sleeping: [[]]
problem 18 was solved!
waking up         []
  still sleeping: [[]]
}
Solving awake constraints. 0 remaining.
{ working on problems [19]
adding constraint [19] @2 =< lsuc lzero
simplifying level constraint @2 =< lsuc lzero
  using [a =< lsuc lzero]
no simplification
waking up         []
  still sleeping: [[],[]]
problem 19 was solved!
waking up         []
  still sleeping: [[],[]]
}
Solving awake constraints. 0 remaining.
checking that the type fits in Set₁
does (x : A) (xs : L A) → S (x ∷ xs)
of sort Set (lsuc lzero ⊔ a)
fit in Set₁ ?
does (xs : L A) → S (x ∷ xs)
of sort Set (lsuc lzero ⊔ a)
fit in Set₁ ?
does S (x ∷ xs) of sort Set₁ fit in Set₁ ?
adding constructor _∷_ : (x : A) (xs : L A) → S (x ∷ xs)
waking up         [[],[]]
  still sleeping: []
Solving awake constraints. 2 remaining.
{ working on problems []
{ solving constraint
[] @2 =< lsuc lzero
adding constraint [] @2 =< lsuc lzero
simplifying level constraint @2 =< lsuc lzero
  using [a =< lsuc lzero]
no simplification
waking up         []
  still sleeping: [[]]
}
}
Solving awake constraints. 1 remaining.
{ working on problems []
{ solving constraint
[] a =< lsuc lzero
adding constraint [] a =< lsuc lzero
simplifying level constraint a =< lsuc lzero
  using [@2 =< lsuc lzero]
no simplification
waking up         []
  still sleeping: [[],[]]
}
}
```
Mysterious how Agda declares that `Problem 18 is solved!` after having achieved `no simplification` only to get the same constraint back later in anonymous form (no problem id).

**Comment by andreasabel** [comment]
Another absurdity about this case: it should pass, because `x` and `xs` are forced.  An indeed it passes if `S` is placed in `Set` and not in `Set1`. Magic 0?!
```agda
data L {a} (A : Set a) : Set a where
  _∷_ : A → L A → L A

data S {a} {A : Set a} : L A → Set where
  _∷_ : (x : A) → (xs : L A) → S (x ∷ xs)  -- x and xs are forced!
```
Ok, the explanation must be somehow that `max 0 a` simplifies to `a`, while `max 1 a` does not simplify.

It seems I introduced the weird behaviors in 5e9ec5f208ecb184f55e0bb0aec4f81f9e453469 which added the Big/Small distinction to Forced.  This is obsolete and shall be removed.
