### ISSUE TITLE
Positivity checker too liberal

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#690]
The following definition of D should be rejected:

``` agda
{-# OPTIONS --type-in-type #-}

data _≡_ {A : Set} (x : A) : A → Set where
  refl : x ≡ x

data ⊥ : Set where

data D : Set where
  abs : ∀ {E : Set} → D ≡ E → (E → ⊥) → D
```

D should not be strictly positive in equality.

Original issue reported on code.google.com by `andreas....@gmail.com` on 6 Sep 2012 at 3:29

**Comment by andreasabel** [comment]
Email exchange mentioned above starts with: https://lists.chalmers.se/pipermail/agda/2012/004297.html,
titled `Forget Hurken's Paradox, Agda has a quicker route to success`.
