### ISSUE TITLE
Bug in attaching warnings to record declarations

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda#6908]
Version: `Agda-2.6.4`. 

In the following code, with a warning attached to a record field, in the first example where we use the qualified projection, Agda successfully raises a warning. However, the second example where we open the parameterised module record, there is unexpectedly no warning raised.
```
record Test : Set₁ where
  field
    A : Set

  B : Set
  B = A
  {-# WARNING_ON_USAGE B "Warning: B used." #-}

warning : Test → Set
warning t = Test.B t

noWarning : Test → Set
noWarning t = B
  where open Test t
```

As an aside I've also seen people write:
```
record Test : Set₁ where
  field
    A : Set

  B : Set
  B = A
  
{-# WARNING_ON_USAGE Test.B "Warning: B used." #-}
```
whose behaviour I haven't tested, but I guess should behave the same as the above.

**Comment by gallais** [comment]
I think this may just be #5617

**Comment by MatthewDaggitt** [comment]
Yes you're right.
