### ISSUE TITLE
Constraint solver is oblivious to constant functions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#691]
The meta-variable X is solved to true but should left unsolved.
```agda
assert : (A : Set) → A → Bool → Bool
assert _ _ true  = true
assert _ _ false = false

g : Bool -> Bool -> Bool
g x true  = true
g x false = true

unsolved : Bool -> Bool
unsolved y =
  let X : Bool
      X = _
  in  assert (g X y ≡ g true y) refl X
```
Proposed fix: make Agda aware of constant functions (polarity 'Nonvariant').

Original issue reported on code.google.com by `andreas....@gmail.com` on 7 Sep 2012 at 12:20

**Comment by andreasabel** [comment]
Patch: 41e59c645710fb5a8dad8d3ad2395a0539fc6910
