### ISSUE TITLE
Internal error on `primLockUniv`-sorted functions

### ISSUE THREAD

**Issue by ionathanch** [agda/agda#6913]
_Agda version: v2.6.4 (from Hackage)_

For context, I'm trying to reproduce some basics from Clocked Type Theory, in particular postulating a forcing tick that works for any clock.

```agda
{-# OPTIONS --guarded #-}

primitive primLockUniv : Set₁
postulate ⋄ : {κ₀ : primLockUniv} → κ₀
```

I get the following type error,

> funSort Set₁ primLockUniv is not a valid sort
when checking that the expression {κ₀ : primLockUniv} → κ₀ is a type

which is fair, since according to the [docs on the sort system](https://agda.readthedocs.io/en/v2.6.4/language/sort-system.html#id7) I'm not allowed to do that. But if I try to cheat and assume a clock as a variable,

```agda
variable κ₀ : primLockUniv
postulate ⋄ : κ₀

force : {P : primLockUniv → Set} → (∀ κ → (@tick t : κ) → (P κ)) → (∀ κ → P κ)
force f κ = f κ ⋄
```

I get a more serious error:

> An internal error has occurred. Please report this as a bug.
Location of the error: \_\_IMPOSSIBLE\_\_, called at src/full/Agda/TypeChecking/Constraints.hs:71:11 in Agda-2.6.4-CPwNw3CagtPFruYK76yMGr:Agda.TypeChecking.Constraints

Explicitly setting the implicit argument gives what I assume is a more reasonable error:

```agda
force : {P : primLockUniv → Set} → (∀ κ → (@tick t : κ) → (P κ)) → (∀ κ → P κ)
force f κ = f κ (⋄ {κ₀ = κ})
```

> The term ⋄, given as an argument to the guarded value
  f κ : κ → P κ
can not be used as a @​tick argument, since it does not mention any @​tick variables.
when checking that the expression f κ (⋄ {κ₀ = κ}) has type P κ

Interestingly, as an aside, I can write down the type of `⋄` as long as I let Agda infer the missing sort:

```agda
⋄′ : {κ₀ : _} → κ₀
⋄′ = ⋄
```

**Comment by jespercockx** [comment]
Congratulations with finding the first new internal error in Agda 2.6.4!

**Comment by andreasabel** [comment]
Or, rather an old friend: 😉 
https://github.com/agda/agda/blob/5c8116227e2d9120267aed43f0e545a65d9c2fe2/src/full/Agda/TypeChecking/Constraints.hs#L66-L71

**Comment by ionathanch** [comment]
If it helps, it seems to be resolved by changing `instantiate` to `instantiateFull` here:
https://github.com/agda/agda/blob/be28b6e2edc3961292eb9e56f80080289d90c61f/src/full/Agda/TypeChecking/Lock.hs#L46-L48

**Comment by andreasabel** [comment]
@ionathanch Thanks for the analysis.  I turned your suggested fix into PR 
- #6938
