### ISSUE TITLE
CI deploy Windows: `strip` utility not found

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#6926]
This fails now, maybe because GHC is not necessarily installed via Chocolatey anymore:
https://github.com/agda/agda/blob/33be1c7e98878dbd5345efe2c363dad23961ab43/src/github/workflows/deploy.yml#L225
See workflow run: https://github.com/agda/agda/actions/runs/6563356428/job/17827400764#step:14:50

@L-TChen: Why is the `strip` util from Chocolatey used here?  Is there a particular reason? Could we just use the MSYS2 one instead?
https://packages.msys2.org/package/mingw-w64-x86_64-binutils

Originally introduced in https://github.com/agda/agda/blob/5883777d450e0959bfcfa638ec536b327668cc38/.github/workflows/deploy.yml#L126

**Comment by L-TChen** [comment]
This step can be removed. It was used to reduce the size of binary and potentially improves its performance. It can done via linker as well. 

https://en.m.wikipedia.org/wiki/Strip_(Unix)

**Comment by andreasabel** [comment]
> This step can be removed. It was used to reduce the size of binary and potentially improves its performance. It can done via linker as well.

Ok, I remove it.
NB: I didn't find any GHC option that would pass `-s` to the linker, so I assume it happens automatically or it is not of concern anyway: https://downloads.haskell.org/ghc/latest/docs/users_guide/phases.html#options-affecting-linking
