### ISSUE TITLE
Please replace deprecated 'peano' package

### ISSUE THREAD

**Issue by iliastsi** [agda/agda#6935]
Commit dd89d485c introduced a dependency on the `peano` Haskell package (https://hackage.haskell.org/package/peano). This package is deprecated, and I would like to avoid packaging it in Debian. Please consider replacing the `peano` package with another maintained package.

Thanks!

**Comment by andreasabel** [comment]
@iliastsi : Thanks for the alert.  I will try to take over this package and undeprecate it.

**Comment by andreasabel** [comment]
I took over this package, this should fix this issue.
