### ISSUE TITLE
Emacs 30 breaks agda mode

### ISSUE THREAD

**Issue by kutsurak** [agda/agda#6953]
A relatively recent [change](https://github.com/emacs-mirror/emacs/commit/a9c962be961) in `pp.el` in the development branch of emacs breaks the function `agda2-send-command` by adding newlines at the end of filenames. 

To reproduce open any agda file in a recent emacs 30 build running version 2.6.4 or master (the issue is reproducible in both), and call `agda2-load`. This results in the following errors in the `*agda2*` buffer:

```
IOTCM "/tmp/hello-world-dep.agda"
 NonInteractive Indirect ( Cmd_load "/tmp/hello-world-dep.agda"
 [] )
Agda2> cannot read: IOTCM "/tmp/hello-world-dep.agda"
Agda2> cannot read:  NonInteractive Indirect ( Cmd_load "/tmp/hello-world-dep.agda"
Agda2> cannot read:  [] )
```

I used the following as a minimal emacs configuration after installing agda using stack:

```
;;; -*- lexical-binding: t -*-

(load-file (let ((coding-system-for-read 'utf-8))
             (shell-command-to-string "agda-mode locate")))

;; auto-load agda-mode for .agda and .lagda.md
(setq auto-mode-alist
   (append
     '(("\\.agda\\'" . agda2-mode)
       ("\\.lagda.md\\'" . agda2-mode))
     auto-mode-alist))
```

I am not entirely convinced that the change in the behavior of `pp-to-string` is correct, but I have a simple workaround until the issue has been investigated/resolved on the emacs side. A PR with it follows.

**Comment by andreasabel** [comment]
> A relatively recent [change](https://github.com/emacs-mirror/emacs/commit/a9c962be961) in `pp.el` in the development branch of emacs breaks the function `agda2-send-command` by adding newlines at the end of filenames.

Oh, but this is also an explanation for the malformed strings in https://github.com/agda/agda/issues/6983#issuecomment-1808377325 which have additional line-breaks after filenames.

So this issue is not fully fixed with 
- #6954 

More string-trimming is needed after we invoke `pp-` functions.
