### ISSUE TITLE
Agda stdlib installation instructions broken link

### ISSUE THREAD

**Issue by patrick-nicodemus** [agda/agda#6957]
This page
https://agda.readthedocs.io/en/v2.6.4/getting-started/a-taste-of-agda.html#a-taste-of-agda
links to installation instructions for the standard library but the link is broken.

**Comment by jamesmckinna** [comment]
Specifically, v1.7.* releases of the library do point to the `notes/` subdirectory for additional ancillary documentation, but this is being moved to `doc/` for the v2.0 release, and that change has already been propagated on `master` by https://github.com/agda/agda-stdlib/pull/2184

**Comment by andreasabel** [comment]
Thanks for the heads up!

We should only use time-resistant links...  These don't rot as references per se, only as pointers to relevant content. 😆

**Comment by jamesmckinna** [comment]
Re: time-resistant links. how would that cash out in terms of the `stdlib` documentation? or is this comment local to the `user-manual/` documentation (it would in any case be nice, for developers and end-users/readers alike, if we can try to keep these as loosely coupled as possible...)
