### ISSUE TITLE
Opaque primitives?

### ISSUE THREAD

**Issue by nad** [agda/agda#6958]
Agda's output suggests that primitives can be made opaque:

https://github.com/agda/agda/blob/4b23885ef10786f2c1d57d40888339df741914ef/src/full/Agda/TypeChecking/Pretty/Warning.hs#L356

However, this does not seem to be the case, the following code is accepted:
```agda
open import Agda.Builtin.Equality

postulate Char : Set

{-# BUILTIN CHAR Char #-}

opaque primitive
  primToUpper : Char → Char

_ : primToUpper 'a' ≡ 'A'
_ = refl
```
I don't really care if primitives can be made opaque or not, but I think the warning message should match the implementation. (The current statement is perhaps technically correct, because primitives can apparently be *marked* as opaque, but I think the text is misleading.)

**Comment by nad** [comment]
Is the decision that primitives cannot be made opaque? In that case the user manual should be updated:

https://github.com/agda/agda/blob/f6dc8b82edda8365a3b6df3759ca5fac638efe5c/doc/user-manual/language/opaque-definitions.lagda.rst?plain=1#L28

**Comment by nad** [comment]
And the source code:

https://github.com/agda/agda/blob/f6dc8b82edda8365a3b6df3759ca5fac638efe5c/src/full/Agda/TypeChecking/Monad/Base.hs#L2692-L2693

**Comment by plt-amy** [comment]
> And the source code:
> 
> https://github.com/agda/agda/blob/f6dc8b82edda8365a3b6df3759ca5fac638efe5c/src/full/Agda/TypeChecking/Monad/Base.hs#L2692-L2693

The code for `abstract` should probably also be killed, then? Your code continues to puzzlingly work perfectly if we replace opaque by abstract:

```agda
abstract primitive
  primToUpper : Char → Char

_ : primToUpper 'a' ≡ 'A'
_ = refl
```

> Is the decision that primitives cannot be made opaque? In that case the user manual should be updated:
> 
> https://github.com/agda/agda/blob/f6dc8b82edda8365a3b6df3759ca5fac638efe5c/doc/user-manual/language/opaque-definitions.lagda.rst?plain=1#L28

On it.

**Comment by nad** [comment]
I think it makes sense to complain also about abstract primitives.

**Comment by UlfNorell** [comment]
Closing as completed.

**Comment by andreasabel** [comment]
@UlfNorell What about:
> I think it makes sense to complain also about abstract primitives.

**Comment by UlfNorell** [comment]
What about it? Do you have a test case where we don't?
