### ISSUE TITLE
How to make Agda Emacs Mode to show output in the same window?

### ISSUE THREAD

**Issue by yaitskov** [agda/agda#6961]
I just configured agda env via nix-env. It works, but due some reason Emacs commands such as `C-c C-l` or `C-c C-` by default output results into a separate window. It is less ergonomic than what I observer on youtube tutorials. New window hides window with source code. 
Consequent commands (`c-c c-l`) don't put the window with result on top and I have to switch manually or close the window every time.

Emacs installed with commands: `$ nix-env -f "<nixpkgs>" -iA emacs`
and `$ nix-env -f "<nixpkgs>" -iA agda-mode`

```
GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.16.0, Xaw3d scroll bars)
```

**Comment by xekoukou** [comment]
You first create only one window with your code. Then you do C-c C-l. A new window is created with the output.

Then you create more windows with code, without closing the previous windows.

**Comment by nad** [comment]
I've seen similar behaviour on MacOS, possibly limited to those who use Aquamacs. However, I don't think I've seen this on Linux. Perhaps the Nix setup is different than the default one.

Agda uses [`display-buffer`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Displaying-Buffers.html) to display the information buffer:

https://github.com/agda/agda/blob/f6dc8b82edda8365a3b6df3759ca5fac638efe5c/src/data/emacs-mode/agda2-mode.el#L988-L1064

Emacs makes it possible to tweak how `display-buffer` works. I wonder if you have some customisations in `display-buffer-alist` or `display-buffer-base-action`. If you do, then you could try to remove those customisations. (Use `M-x customize-variable `*variable*` RET` to inspect and modify the customisations for *variable*.)

**Comment by jespercockx** [comment]
Closing this due to a lack of response by the OP.
