### ISSUE TITLE
Keep user-facing debug printing for reflection

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#6963]
Currently debug printing is disabled unless you compile with `-f debug`. However, there are a few cases where we want to expose debug printing to the user without recompiling Agda:

- We export a `debugPrint` reflection primitive
- Printing the code generated by `unquoteDecl` is sometimes very important for debugging reflection code.

We should change these to use the always-on debug printing.

**Comment by nad** [comment]
I think the fact that some debug printing is available by default should be documented in the user manual.
