### ISSUE TITLE
Allow referring to unnamed record constructors

### ISSUE THREAD

**Issue by plt-amy** [agda/agda#6964]
Right now a record

```agda
record R : Set where
  field
    x : Nat
```

has a constructor which is internally named `R.constructor` but the user can't refer to this directly. (They can still get their hands on this name using reflection, since a `record-type` definition includes the constructor name). This makes it a bit annoying to construct records using reflection, since you can't `quote R.constructor`, and it also blocks the use of a few features e.g. #6660 or the upcoming #6721, since you can't refer to this name in pragmas either.

**Comment by jespercockx** [comment]
@plt-amy Since work on this issue seems to have stalled, I am moving it to the `later` milestone. When the issue is resolved, please change it to the current milestone at the time of fixing.

**Comment by plt-amy** [comment]
(This was fixed by #7510.)

**Comment by andreasabel** [comment]
@plt-amy: please also correct the milestone for this issue.
