### ISSUE TITLE
Termination checking issue on rewrite & useless error message

### ISSUE THREAD

**Issue by floofnoodlecode** [agda/agda#6969]
Agda versions: 
  - 2.6.2.2 (the one at https://homepage.divms.uiowa.edu/~astump/agda/)
  - 2.6.3 (the one on [agdapad](https://agdapad.quasicoherent.io))

I get a termination checking failed error even though the recursion is on a term strictly smaller...
The error message is completely unhelpful!

```agda
import Relation.Binary.PropositionalEquality as Eq
open Eq using (_≡_; refl; cong)
open import Data.Nat using (ℕ; zero; suc; _+_; _≤_; z≤n; s≤s)
open import Data.Nat.Properties using (+-comm; +-identityʳ; +-suc)


data Bin : Set where
  ⟨⟩ : Bin
  _O : Bin → Bin
  _I : Bin → Bin

inc : Bin → Bin
inc ⟨⟩ = ⟨⟩ I
inc (b O) = b I
inc (b I) = (inc b) O

to : ℕ → Bin
to zero = ⟨⟩ O
to (suc n) = inc (to n)

to-2*n≡to-nO : ∀ (n : ℕ) → (1 ≤ n) → to (n + n) ≡ (to n) O
to-2*n≡to-nO (suc zero) _ = refl
to-2*n≡to-nO (suc (suc n)) _ rewrite +-suc n (suc n) | to-2*n≡to-nO (suc n) {!!} = {!!}
```

Error:
```
?0 : 1 ≤ suc n
?1 : inc (inc (inc (to n) O)) ≡ (inc (inc (to n)) O)

———— Errors ————————————————————————————————————————————————
/home/guest/hello.agda:21,1-23,88
Termination checking failed for the following functions:
  to-2*n≡to-nO
Problematic calls:
  to-2*n≡to-nO (suc (suc n)) x | n + suc (suc n) | +-suc n (suc n)
  to-2*n≡to-nO (suc n) (?0 (n = n) (x = x))
    (at /home/guest/hello.agda:23,56-68)
```

**Comment by andreasabel** [comment]
The cure is to use `{-# OPTIONS --termination-depth=2 #-}`.
Or to reorganize your function so that it works with depth-1 termination checking.

**Comment by andreasabel** [comment]
While I am here, I may suggest a canonical representation of binary numbers, so that you do not need to quotient by `(0 ...(n times)... 0) = 0`.  Then your lemma could more generally hold for _all_ `n`.

**Comment by andreasabel** [comment]
Like:
```agda
data Bin₁ : Set where
  I  : Bin₁
  _O₁ : Bin₁ → Bin₁
  _I₁ : Bin₁ → Bin₁

data Bin : Set where
  O₂ : Bin
  _₂ : Bin₁ → Bin

inc₁ : Bin₁ → Bin₁
inc₁ I = I O₁
inc₁ (b O₁) = b I₁
inc₁ (b I₁) = inc₁ b O₁

inc : Bin → Bin
inc O₂ = I ₂
inc (b ₂) = inc₁ b ₂

to : ℕ → Bin
to zero = O₂
to (suc n) = inc (to n)

_O : Bin → Bin
O₂ O = O₂
(b ₂) O = b O₁ ₂

lem : ∀ b → inc (inc (b O)) ≡ inc b O
lem O₂    = refl
lem (b ₂) = refl

to-2*n≡to-nO : ∀ n → to (n + n) ≡ (to n) O
to-2*n≡to-nO zero = refl
to-2*n≡to-nO (suc n) rewrite +-suc n n rewrite to-2*n≡to-nO n = lem (to n)
```
This also fixes the termination-depth issue.

I hope I haven't done someone's homework here...

**Comment by floofnoodlecode** [comment]
Thank you for responding.

I am simply learning Agda for fun in my spare time. The idea of mathematical proofs verifiable by a computer sounds really interesting to me for some reason. I considered other proof assistants, but settled on Agda due to its simplicity and nice syntax.

This exercise is from https://plfa.github.io/Relations/. It is the very last exercise where it asks you to prove
```
1 ≤ n
---------------------
to (2 * n) ≡ (to n) O
```

The non-canonical representation for `Bin` is also intended, and is given in the previous chapters. My expectation was that if I can prove something on paper, I could also do it in Agda, assuming the proof was correct. So I am not really interested in rewriting things.

That being said, can I suggest an improvement to the documentation? I checked out [Termination checking](https://agda.readthedocs.io/en/v2.6.4/language/termination-checking.html) before submitting the issue and I still claim that I followed the structural recursion rule.

I also checked out [--termination-depth](https://agda.readthedocs.io/en/v2.6.4/tools/command-line-options.html#cmdoption-termination-depth) and I am still not sure what it means. It also links back to [Termination checking](https://agda.readthedocs.io/en/v2.6.4/language/termination-checking.html) which makes no mention of "depth"...

So was it because my base case starts from `(suc zero)` instead of `zero`? But even then, Agda is the one that split the cases like that, after two splits on the same variable... Since it recognized that `zero` was impossible, I expected the termination checker to do that as well.

**Comment by andreasabel** [comment]
> So was it because my base case starts from `(suc zero)` instead of `zero`?

No, it is because of the `rewrite` which is just sugar for introducing a mutual function (thus, you get the unreadable error).
Basically you end up with the pattern
```agda
f (suc (suc n)) = g n
  where
  g n = f (suc n)
```
which the termination checker only accepts with termination-depth 2, to record the difference between `(suc (suc n))` and `n` accurately.

> That being said, can I suggest an improvement to the documentation?

Sure we are open to PRs!
The documentation is still in a somewhat incomplete state.  It has been and is sourced from volunteer contributions.

**Comment by floofnoodlecode** [comment]
Thank you. I finally understand now what the issue was.

> Sure we are open to PRs!

By "suggest" I actually meant "request". As you can see, I don't understand enough how Agda functions to be writing documentation for it. It would be helpful if [Termination Checking](https://agda.readthedocs.io/en/v2.6.4/language/termination-checking.html) had a section explaining the "termination depth".
