### ISSUE TITLE
Feature request: Definitions that fail successfully

### ISSUE THREAD

**Issue by wilbowma** [agda/agda#7002]
I beg a boon from great clown maintainer (@plt-amy):

I’d like a feature for checking examples of things that *fail* to type check, similar tom Coq’s `Fail` vernac (https://coq.inria.fr/doc/V8.10.2/refman/proof-engine/vernacular-commands.html#coq:cmd.fail), or Lean’s guard_msg (https://yaeldillies.github.io/LeanAPAP/docs/Std/Tactic/GuardMsgs.html), or Idris’s fail blocks (https://github.com/idris-lang/Idris2/blob/d6aa70dbe16005fbbf68e7525be3784525f4f2ec/docs/source/reference/failing.rst)

I'd suggest a pragma, but maybe a keyword or new block would be appropriate.

The definition following the pragma, or definitions in the block, should raise an error *only if it does type check*, and silently *succeed if it fails to type check*. The definition should not be in scope in the rest of the module if it fails successfully. The definition shouldn't appear in generated code. It should act as if commented out.

I suggest a syntax like the following.

```
{-# FAILS_SUCCESSFULLY #-}
foo : Set
foo = Set
```

If feeling ambitious, we might add an optional ability to specify the expected error message, and an error should also be raised (and possibly a diff produced) if the definition fail to type check for some other reason than the expected one. I'd probably specify a regex rather than a string literal.

```
{-# FAILS_WITH "Can't unify succ with zero" #-}
foo : 0 = 1
foo = refl
```

**Comment by andreasabel** [comment]
Or MiniAgda's [fail](https://github.com/andreasabel/miniagda/blob/b36128aa495ca243fed423f26d5b6f61dc6c1df1/src/Parser.y#L100-L101) (since 2011).

I think this would be most sensible when we have names for all errors (@AlexHarsani is working on this).
However, one could start with a makeshift implementation that supports both error names and error message string matching.

**Comment by gallais** [comment]
In Idris we have a `failing` block rather than pragma because this allows you to introduce
intermediate definitions that do not fail but you don't want to see pollute the scope.

**Comment by wilbowma** [comment]
Keeping the namespace clean is a good idea, but it seems like the Agda module (namespace) system could already handle that.But I wonder if the pragma approach would scale to eg a mutual definition. I guess then it would prefix the mutual block instead of a single definition?I also wonder about non-terminating definitions—Agda seems to continue past these, so are they not like other errors? I’d like to be able to consider them “failing successfully” as well.On Nov 19, 2023, at 05:52, G. Allais ***@***.***> wrote:﻿
In Idris we have a failing block rather than pragma because this allows you to introduce
intermediate definitions that do not fail but you don't want to see pollute the scope.

**Comment by nad** [comment]
See #2114.
