### ISSUE TITLE
report about Agda-2.6.4.1-candidate

### ISSUE THREAD

**Issue by mechvel** [agda/agda#7005]
I have tested Agda-2.6.4.1-candidate
on my large library of computer algebra on Debian Linux, ghc 9.2.7, MAlonzo.
Its behavior is the same as of  Agda-2.6.4.

The only difference is in the report of   ``agda-mode compile``.
agda-mode  does work, but the message differs from what it was for  2.6.4,
and probably agda-mode has not been compiled:
 
> cabal update
..
> cabal install -foptimise-heavily -j1

Installing executable agda in /home/mechvel/.cabal/store/ghc-9.2.7/incoming/new-1\
0973/home/mechvel/.cabal/store/ghc-9.2.7/Agda-2.6.4.1-1190f8d06143368e15b2475de20\
5bc9005b2edb6a1370c13afe8ed4557846bb6/bin
Warning: The directory
/home/mechvel/.cabal/store/ghc-9.2.7/incoming/new-10973/home/mechvel/.cabal/store\
/ghc-9.2.7/Agda-2.6.4.1-1190f8d06143368e15b2475de205bc9005b2edb6a1370c13afe8ed455\
7846bb6/bin
is not in the system search path.
Warning: installdir is not defined. Set it in your cabal config file or use
--installdir=<path>. Using default installdir: "/home/mechvel/.cabal/bin"
Symlinking 'agda' to '/home/mechvel/.cabal/bin/agda'
Symlinking 'agda-mode' to '/home/mechvel/.cabal/bin/agda-mode'

> agda-mode compile
Loading quail/latin-ltx...

In toplevel form:
~/.cabal/store/ghc-9.2.7/Agda-2.6.4.1-1190f8d06143368e15b2475de205bc9005b2edb6a13\
70c13afe8ed4557846bb6/share/emacs-mode/agda2-mode.el:2065:1:Error: the function ‘\
string-trim’ is not known to be defined.
Unable to compile the following Emacs Lisp files:
  /home/mechvel/.cabal/store/ghc-9.2.7/Agda-2.6.4.1-1190f8d06143368e15b2475de205b\
c9005b2edb6a1370c13afe8ed4557846bb6/share/emacs-mode/agda2-mode.el

**Comment by gallais** [comment]
Introduced by #6995 ?

What's your emacs version @mechvel ?

**Comment by mechvel** [comment]
> emacs --v
says
GNU Emacs 26.1 ...
(this all happens under Debian Linux).

**Comment by andreasabel** [comment]
> Introduced by #6995 ?

Yes, both of these use `string-trim`:
- #6954 
- #6995 

@kutsurak Maybe you are more of an emacs programmer than me.  Could we use some Emacs < 27 compatible function instead?

**Comment by kutsurak** [comment]
We can probably check the version and use `string-trim` only if it is >= 30. I will take a look this afternoon if nobody beats me to it.

**Comment by nad** [comment]
Could we get rid of `string-trim` by replacing `pp-to-string` with [`prin1-to-string`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Output-Functions.html#index-prin1_002dto_002dstring) and `pp-escape-newlines` with [`print-escape-newlines`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Output-Variables.html#index-print_002descape_002dnewlines)?

**Comment by kutsurak** [comment]
> Could we get rid of `string-trim` by replacing `pp-to-string` with [`prin1-to-string`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Output-Functions.html#index-prin1_002dto_002dstring) and `pp-escape-newlines` with [`print-escape-newlines`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Output-Variables.html#index-print_002descape_002dnewlines)?

Yes, this should work. I am preparing a patch along these lines. I will test it on emacs-30 and emacs-26 before opening the pull request against the master branch, but I don't have easy access to other versions of emacs.

**Comment by mechvel** [comment]
It occurs that this is not only  of  ``agda-mode compile`` message.
When type-checking under emacs, the command Clrl - c  Ctrl-l  does not work, it reports something about `trim`.

**Comment by kutsurak** [comment]
> It occurs that this is not only of `agda-mode compile` message. When type-checking under emacs, the command Clrl - c Ctrl-l does not work, it reports something about `trim`.

with the PR #7007 applied? I think I removed all the references to trim in it. _Also which emacs version?_

Edit: no need for the version number I mistook you for @nad :)

**Comment by mechvel** [comment]
> with the PR https://github.com/agda/agda/pull/7007  applied? 

No, this is an addition to my first report.
I do not apply any PR. I am not a developer of Agda, 
If you announce `candidate-2`, then I would probably test it and report.

**Comment by andreasabel** [comment]
> If you announce `candidate-2`, then I would probably test it and report.

I announced it.  @mechvel, did you have time to try it?

**Comment by mechvel** [comment]
No, because I do not understand where to download it from.
Your write
"
The Agda Team is pleased to announce a 2nd release candidate for Agda  2.6.4.1.
Fix in RC2 over RC1:
- Restore support for Emacs 26
   https://github.com/agda/agda/pull/7007
[..]
1. Getting the release candidate
       $ cabal get 
https://hackage.haskell.org/package/Agda-2.6.4.1/candidate/Agda-2.6.4.1.tar.gz
[..]

Is it  candidate-2  for  2.6.4.1 ?
I had an impression that this is candidate-1, which I have already tested.  
If you add the suffix  "-rc2" to the file name, it would be much more clear.
Please, advise.

**Comment by andreasabel** [comment]
So I have simply replaced the RC1 by the RC2 on hackage, using the hackage candidate mechanism.  Thus, there is no suffix given to the archive.  If you follow the instructions you mentioned, you will get the latest RC.

**Comment by mechvel** [comment]
The archives for  rc1 and rc2 have the same name and the same size (!), 
and ``agda  -V`` issues the same report.
Luckily,  the cmp command finds a difference in the archives. 
All right, I have started to test rc2
(Debian Linux with GNU Emacs 26.1).
So far, it type-checks all right, under emacs too.
I shall see further.

**Comment by jwaldmann** [comment]
in my tests, I am building Agda from source, and I start with a checkout of a specific tag, see instructions at https://gitlab.imn.htwk-leipzig.de/waldmann/cetera/-/blob/main/.gitlab-ci.yml

but of course, if developers call for "test the new rc", then we should probably get the thing-to-test in the recommended way (which is - from hackage?)

my actual Agda code is small, and simple, so compiling it is not providing much information. well, except that it works, which is always nice to know.
