### ISSUE TITLE
Factor out `agda-mode/Main.hs` and `data/emacs-mode/*.hs` in a separate package?

### ISSUE THREAD

**Issue by omelkonian** [agda/agda#7012]
In order to have an interactive experience for the [agda2hs backend](https://github.com/agda/agda2hs), we had to [copy-paste 5k LOC](https://github.com/agda/agda2hs/pull/198/files#diff-7b6fdf37fdd69854f56807ce153a98e883669316aaca436a92591466a06e3a13) and just rename `agda~>agda2hs` which seems tedious...

Would it be worth it to factor these parts in a separate package that we can import in isolation?

**Comment by UlfNorell** [comment]
What is the actual problem that you want to solve here? You should be able to use `agda2hs` for emacs interaction out of the box (just change the emacs setting for which agda binary to use). If you need to change interaction I'm not sure how the proposed split would help.

**Comment by omelkonian** [comment]
Hmm, so that means copy-pasting these 5k LOC was entirely unnecessary, right? (I was a bit sceptic myself, but did not investigate thoroughly). 

I will make sure this is the case soon and then close this issue.

**Comment by omelkonian** [comment]
Indeed the code duplication on `agda2hs` was completely unnecessary, hence it is reasonable to close this issue.
