### ISSUE TITLE
Agda-2.6.4.1 Compilation error

### ISSUE THREAD

**Issue by mechvel** [agda/agda#7019]
This is on   Agda-2.6.4.1, MAlonzo,  ghc-9.2.7, lib-1.7.3,  Ubuntu Linux 18.04
installed by 
  $ cabal install -foptimise-heavily

I apply

> agda -c $agdaLibOpt $agdaFlags --ghc-flag="-rtsopts"  Pol/Univariate/KTest.agda +RTS -M7G

where  $agdaFlags =  --auto-inline --guardedness

By this command, first, the needed modules have been type-checked.
Then it goes compilation:
...
[218 of 270] Compiling MAlonzo.Code.GenAlgebraZ45ZIV ( MAlonzo/Code/GenAlgebraZ45ZIV.hs, MAlonzo/Code/GenAlgebraZ45ZIV.o )
Compilation error:

MAlonzo/Code/GenAlgebraZ45ZIV.hs:126698:1: error:
    The type signature for ‘du_'8739'all'45'resp'8776'_15192’
      lacks an accompanying binding
      Perhaps you meant one of these:
        ‘d_'8739'all'45'resp'8776'_15192’ (Defined at MAlonzo/Code/GenAlgebraZ45ZIV.hs:126696:1),
        ‘du_'8739'all'45'resp'8776'_10130’ (Defined at MAlonzo/Code/GenAlgebraZ45ZIV.hs:55303:1),
        ‘du_'8739'all'45'resp'8779'_10132’ (Defined at MAlonzo/Code/GenAlgebraZ45ZIV.hs:55350:1)
       |
126698 | du_'8739'all'45'resp'8776'_15192 ::
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

MAlonzo/Code/GenAlgebraZ45ZIV.hs:126705:3: error:
    Not in scope: type constructor or class ‘MAlonzo.Code.Data.List.Re’
    No module named ‘MAlonzo.Code.Data.List’ is imported.
       |
126705 |   MAlonzo.Code.Data.List.Re
       |   ^^^^^^^^^^^^^^^^^^^^^^^^^

I understand this as follows.
There is the module  GenAlgebra-IV.agda  in my program.  its   .agdai   is ready.
MAlonzo/.../GenAlgebraZ45ZIV.hs   is also ready, which I guess corresponds to  GenAlgebra-IV.agda.
But  ghc fails to compile it.

Please, tell me of whether this report is sufficient to fix this in Agda.

**Comment by andreasabel** [comment]
Did you remove the `MAlonzo` folder before compilation?
Unfortunately, Agda cannot handle its old build products very well, so the `MAlonzo` folder has to be remove manually.

**Comment by mechvel** [comment]
Indeed removing the MAlonzo/ folder helps.

I have an impression that Agda-2.6.4 is free of this fisfeature in compilation to .o (this needs testing).

This feature  looks like important.
Because on a 3 GHz machine and 32 Gb RAM,
my large applied library is type-checked in  18 minutes,
Then, I apply
```
agda -c $agdaLibOpt $agdaFlags --ghc-flag="-rtsopts" CertainMainTest.agda
        +RTS -M7G
```
Its compiling to  .hs  files takes 6 minutes.
There appear large  .hs  files,
in particular,  GenAlgebraZ45ZIV.hs  has about 18 M bytes.
Compiling with  ghc  from .hs to .o  files takes 50 minutes.

The matter is that if I add a small new module that imports something from my library, and compile it in order to run its executable,
this small operation will require removing MAlonzo/ and compiling all the library by new, spending 1 hour.
Am I missing something?

Other related notes:
most people use Agda only to check proofs.
I suspect that I am the only one who pretends to also compile a program and to obtain a fast executable.

My aim was to test on practice of whether Agda allows one to write mathematically nice code (mainly in representing mathematical statements), to apply proof checking, and also to produce a fast code
(only 3-5 times slower than the Haskell program for the same method and run under Glasgow Haskell).
My impression was that Agda-2.6.4 satisfies this, more or less.
In my experience, the compilation cost looks like linear in the program volume, with the coefficient about 10.

Only it takes a great effort to write formal proofs. But this is currently an unavoidable expense for reliable proofs
(I think, in other systems too).

So, this requirement of "each time, remove MAlonzo/ and compile all the library by new"
looks like destroying a lot in the goal.

Am I missing something?

**Comment by andreasabel** [comment]
MAlonzo uses only timestamps to decide whether to recreate the `.hs` file from an `.agda`: https://github.com/agda/agda/blob/82c19372d78133e386467b4ad92f4cb13dcc058d/src/full/Agda/Compiler/MAlonzo/Compiler.hs#L393-L400
So if you update your Agda version, and it makes changes to the compilation process, you might have to remove `.hs` files generated by the old Agda, because the timestamp mechanism does not take the version of Agda into account.  
(This should of course be improved.)
- #6914

Similarly, if you update an Agda library you depend on, you might have to remove old `.hs` compilation products.

But in general, there should not be needed to remove `MAlonzo`.
I would just try first without removing `MAlonzo`, and if you get weird errors like above, you remove `MAlonzo`.

**Comment by andreasabel** [comment]
I am closing this as duplicate of #6914.

**Comment by mechvel** [comment]
> So if you update your Agda version, and it makes changes to the compilation process, you might have to remove .hs files 
> generated by the old Agda, because the timestamp mechanism does not take the version of Agda into account.
> (This should of course be improved.)

If the user changes Agda version or Standard library version, or  GHC version, 
then it looks natural to require that the folder  MAlonzo/  in the user's application source Foo to be removed.
My question was different.
Suppose that Agda version, Standard library version, and  GHC version are preserved,
and the user program Foo has MAlonzo/ inside its source, with all .hs and .o files produced for Foo.
And then the user edits  and changes M.agda in this  Foo program, where M imports some modules from Foo. 
Then one commands   ``agda -c ... M.agda`` in order to obtain the new .o file for M or executable for M.
Then, M.agdai  is changed by type checker. But MAlonzo does not change  .hs  files besides M.hs.
And if  M.agda  is correct, then M.agdai is correct, and it must not occur any error when producing new M.hs and new M.o. 
Right?

**Comment by andreasabel** [comment]
> And if M.agda is correct, then M.agdai is correct, and it must not occur any error when producing new M.hs and new M.o.
> Right?

I think so, if I understood you correctly.
