### ISSUE TITLE
question: haskell backend extraction of `Data.Nat.DivMod.DivMod`?

### ISSUE THREAD

**Issue by jamesmckinna** [agda/agda#7020]
What are the consequences/implications, if any, for the haskell backend in terms of irrelevant instances in the types of functions and the definition of (record) types?

Specifically, see also [stdlib issue 2221](https://github.com/agda/agda-stdlib/issues/2221), and the [comment in the current v2.0 `CHANGELOG`](https://github.com/agda/agda-stdlib/blob/42b2a1a77992f030d3b98d2401dd615735b7f63a/CHANGELOG.md?plain=1#L1082-L1086)

**Comment by andreasabel** [comment]
Not answering your question, but a comment on the specific issue: https://github.com/agda/agda-stdlib/issues/2221#issuecomment-1837402956

**Comment by jamesmckinna** [comment]
Given your solution to the specific question, is there nevertheless an answer to the general one? Or is that moot, given (what I understand to be) the transition away from `MAlonzo` as a ghc backend?

**Comment by andreasabel** [comment]
Is there a MWE that demonstrates that MAlonzo does not function as expected with irrelevant fields/arguments?
(I think your OP is a bit too fuzzy that I would know an answer.)

**Comment by jamesmckinna** [comment]
Apologies for the "fuzzy" OP: there's no suggestion that  "MAlonzo does not function as expected with irrelevant fields/arguments"... more a request for information about "how should I understand better how it behaves on such examples" without reading the source code... because the [relevant section of the User Manual](https://agda.readthedocs.io/en/v2.6.4/tools/compilers.html) gives no indication... 

... but happy to take a cue to look elsewhere, and mark this 'issue' as `status:invalid`...

**Comment by UlfNorell** [comment]
Irrelevant and erased fields are completely removed in the compiled data type. The above PR adds a note to the documentation.
