### ISSUE TITLE
`opaque` in Agda-2.6.4.1 is not type-checked 

### ISSUE THREAD

**Issue by mechvel** [agda/agda#7022]
I failed with using `opaque` in Agda-2.6.4.1 (ghc-9.2.7, Ubuntu Linux 18.04).
I added `opaque`  in several places to a working code like this: 
```
opaque                                                                            
   ε^ᵇ :  ∀ n → ε ^ᵇ n ≈ ε                                                         
   ε^ᵇ zero     = refl                                                             
   ε^ᵇ 2[1+ n ] = 
              begin⟨ setoid ⟩                                                  
                   ε ^ᵇ 2[1+ n ]                    ≈⟨ refl ⟩                         
                   (ε ∙ ε ^ᵇ n) ∙ (ε ∙ ε ^ᵇ n)   ≈⟨ ∙-cong (ε∙ _) (ε∙ _) ⟩         
                   (ε ^ᵇ n) ∙ (ε ^ᵇ n)             ≈⟨ ∙-cong (ε^ᵇ n) (ε^ᵇ n) ⟩       
                   ε ∙ ε                               ≈⟨ ε∙ ε ⟩                          
                   ε                                                              
               ∎                                                                
    ε^ᵇ 1+[2 n ] = 
              begin⟨ setoid ⟩                                                  
                   ε ^ᵇ 1+[2 n ]            ≈⟨ refl ⟩                              
                   ε ∙ (ε ^ᵇ n ∙ ε ^ᵇ n)   ≈⟨ ∙-congˡ (∙-cong (ε^ᵇ n) (ε^ᵇ n)) ⟩  
                   ε ∙ (ε ∙ ε)                 ≈⟨ ε∙ _ ⟩                               
                   ε ∙ ε                        ≈⟨ ε∙ _ ⟩                               
                   ε                                                              
              ∎                                                                 
```
This is a proof for the statement 
"powering unity to any degree by a binary method produces the result equal to unity".
I hoped that the further code will use this   ε^ᵇ  as a postulated statement, so that the whole  .agdai  code will become smaller in size, and type checking will become faster, and may be  the .hs files will be smaller.
Is this a wrong idea?

Agda is installed by 
``> cabal install -foptimise-heavily -j1``
,
type check is by 
``> agda $agdaLibOpt --auto-inline --guardedness OfMonoids.agda +RTS  -M7G``

And it loops long time, looks like infinite, while it was faster than 1 minute when without `opaque`.
Anyway, if my program is incorrect, still the type checker needs to issue a report (?).

Am I missing something?

**Comment by UlfNorell** [comment]
Without a running test case to look at it's very hard to say anything about what's going on.

It's possible that you have some code that relies on `ε^ᵇ` actually computing and when it doesn't the type checking problem  becomes much harder to the point where it looks like an infinite loop. You can figure out where type checking gets stuck by loading the code in Emacs and turning on interactive highlighting (see [here](https://agda.readthedocs.io/en/latest/tools/performance.html#measuring-typechecking-performance)). Once you know which definition you get stuck on, you could either try to figure out why or make that definition `opaque` as well and add an `unfolding` for `ε^ᵇ`.

**Comment by mechvel** [comment]
The head file is   OfMonoids.agda,   and without any `opaque` in the example project, it is type-checked. 
Then I set only a single `opaque` to  OfMonoids.agda : 
``` 
module ... 
... 
  opaque
     partition-Π :  ∀ {p}{P : Pred C p} (P? : Decidable P) → (xs : List C) →
                          Π xs ≈ (Π (filter P? xs)) ∙ (Π (filter (¬? ∘ P?) xs))

     partition-Π         _  []        =  sym (ε∙ ε)
     ...
  
     powΠ-+ : (xs : List C) (js ks : List ℕ) → lng js ≡ lng ks →
                    let pPr = powΠ xs
                    in   pPr (js +ₗ ks) ≈ pPr js ∙ pPr ks
     powΠ-+ []        _        _          _           = sym (ε∙ ε)
     ...
  -- end-opaque
```
These are two functions under the same opaque.
And here the file ends.
And these two functions are proofs, and are not used anywhere, neither in each other.
a) And Agda reports  of unsolved things in the last two lines, with a long list of unsolved constraints.  
b) The same happens when `opaque` is applied separately to each the above two functions.
c) If the first function is under `opaque` and the second is not, then the file is type-checked in a moment.
d) If both are under `opaque`, and the tail of the file is un-commented, then  type-checking process looks like infinite,
    with coloring all the text and without marking unsolved things. 
     And these two functions are proofs, and are not used anywhere, neither in each other.

If this is not enough for you to guess of what is happening, then I could try to provide the code.

But I am not sure, though, because currently the code is large and because I doubt greatly about whether my expectation about the `opaque` optimization is correct. Because, may be, it  still will not  unfold these two proof functions without any `opaque'. Because once a proof function is checked probably there is not any reason to unfold it in any further code, it suffices only to substitute their type expressions (I do not know the details of the type checker concept).
?

**Comment by UlfNorell** [comment]
I suspect your problem is that when you make a definition `opaque` metavariables in the types cannot use information in the body of the definition. This is because the type needs to make sense outside the opaque block. You can check if this is the problem by turning `powΠ-+` into a postulate and seeing if you get unsolved metas in the type.

**Comment by mechvel** [comment]
I attach a simple example of two small modules. 
The last function in the first module is   `powΠ-+`.   It proves a certain statement about any `CommutativeMonoid`.
This function is under `opaque`.
This time Agda reported about necessity to declare several types explicitly there.
Now I understand what is needed for correctness.
Then,
the module `Test.agda` proves two small theorems about Nat. Each theorem is proved by calling the function  `powΠ-+`.  
Now, is `powΠ-+` unfolded in `Test` when used in `theorem-I` and `theorem-II` ?
Is it unfolded there when `opaque` is removed?
I do not see any essential difference in the sizes of .agdai files between the cases of "without opaque" and "with opaque".
Is this because the `opaque` part is much smaller here than take the import declarations from Standard library and the remaining code?

[opaqueExample.zip](https://github.com/agda/agda/files/13653389/opaqueExample.zip)

**Comment by mechvel** [comment]
I have an impression that in this example `opaque` does not change the unfolding mode in Test.agda.
Because I added to the first module the tree copies of powΠ-+ under different names, all them under `opaque`,
and apply them to prove four similar theorems in Test.agda,
and the sizes of the .agdai  files occur
```
96818 Test.agdai      without opaque,
96800 Test-o.agdai   with opaque.
```
The ratio is smaller than 1.0002.
 Either the things are unfolded in both cases or not unfolded in both cases - something like this.
?

**Comment by UlfNorell** [comment]
Agda doesn't unfold things aggressively so in your example there's no difference because there's nothing in your use of `powΠ-+` that would require it to be unfolded. Somewhat simplified:

- type checking a call `powΠ-+ xs js ks p` does not require unfolding
- checking that two calls `powΠ-+ xs js ks p` and `powΠ-+ xs' js' ks' p'` are equal does require unfolding

Unfolding can affect the size of the interface file, but in many cases it doesn't.

**Comment by mechvel** [comment]
I suspected all this. 
The matter is that I do not understand in what places in my project  proofs are unfolded.
I suspect that almost nowhere.
