### ISSUE TITLE
Switch to flat versioning

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#7030]
(Discussion at Agda dev meeting 2023-12-13 St. Lucia:)
Traditionally, we have not respected any versioning policy (Nisse looked and this decision dates from 2009 at least).  However, there are more uses of Agda-as-a-library now (backends, agda-language-server) that might need to be able to distinguish API versions reliably.

GHC offers the `MIN_VERSION_Agda(x,y,z)` macro only that takes the first three positions of the version string (`List Nat`) into account.  Each API change should at least bump the position `z` (Haskell PVP would even require bumping `y`).  

Since `x=2` is fixed, we should increase `y` on every proper release, so that we can bump `z` for API-changing patch releases.  (In practice, almost every one of our releases is API-breaking...)

So the next release will not be 2.6.5 but 2.7.  
(We could have an API-changing patch release as 2.6.5, but not 2.6.4.2.)

**Comment by jespercockx** [comment]
The next milestone is now named 2.7 so I'm closing this!
