### ISSUE TITLE
Internal error with --two-level due to blocking on solved meta

### ISSUE THREAD

**Issue by sattlerc** [agda/agda#7034]
On master (ee876ee229cdc2f3b1ff80f6d60568a1869f9385).

```agda
{-# OPTIONS --two-level #-}
module Issue7034 where

open import Agda.Primitive using (SSet)

postulate
  A : SSet
  x : A

foo : {!(y : A) → ?!}
foo = x
```

Filling the hole gives:
```
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/Constraints.hs:71:11 in Agda-2.6.5-ec51c49b804662559b10509859f950f6b1a84575acb5950875806501b569d6c0:Agda.TypeChecking.Constraints
```

This references a case in `addConstraintTM`:
```haskell
      forM_ (allBlockingMetas unblock) $ \ m ->
        whenM (isInstantiatedMeta m) $ do
          reportSDoc "tc.constr.add" 5 $ "Attempted to block on solved meta" <+> prettyTCM m
          __IMPOSSIBLE__
```

**Comment by andreasabel** [comment]
https://github.com/agda/agda/blob/fe4337982fc3a097ab6ee27554caefdcf934f281/src/full/Agda/TypeChecking/Constraints.hs#L66-L71
This is another instance of
- https://github.com/agda/agda/issues/6758

**Comment by andreasabel** [comment]
With `-v tc:30` the last words of Agda are:
```
solving _9 := _10
completed assignment of _9@14618456326245523507
Postponing constraint
  funSort SSet _10 == SSet
adding constraint funSort SSet _10 = SSet
                    (blocked on _7, belongs to problem 6) unblocker:  _7
Attempted to block on solved meta _7
```
The diff between `Set` and `SSet` seems to be the unsolvability of `funSort SSet _10 == SSet` (the equivalent for `Set` solves `_10 := Set`).

**Comment by andreasabel** [comment]
Could be related:
- #2978 

Relevant debug print seems to be:
```
equalSort _7 (y = y) == _9
term _9 := _7 (y = y)
...
initOccursCheck: we look into the following definitions:
(none)
offending variable:  y
  of type  A
  (after singleton test)
error during flexible occurs check, we are StronglyRigid
Pattern violation (you shouldn't see this)
oops, pattern violation for _7@14618456326245523507
attempting kills
  m'    = _7@14618456326245523507
  vs    = [y]
  kills = [True]
after kill analysis
  metavar = _7
  kills   = [True]
  kills'  = [True]
  oldType = (y₁ : A) →
            "dummyType: __DUMMY_TYPE__, called at src/full/Agda/TypeChecking/MetaVars.hs:197:25 in Agda-2.6.5-4ATBkX6jZbSGAWG421gpPu:Agda.TypeChecking.MetaVars"
  newType = "dummyType: __DUMMY_TYPE__, called at src/full/Agda/TypeChecking/MetaVars.hs:197:25 in Agda-2.6.5-4ATBkX6jZbSGAWG421gpPu:Agda.TypeChecking.MetaVars"
...
actual killing
  new meta: _10@14618456326245523507
  kills   : True
  inst    : _7@14618456326245523507 := _10
completed assignment of _7@14618456326245523507
passed occursCheck
...
solving _9 := _10
completed assignment of _9@14618456326245523507
funSortEquals
  s0 = SSet
  s1 = SSet
  s2 = _10
Postponing constraint
  funSort SSet _10 == SSet
adding constraint funSort SSet _10 = SSet
                    (blocked on _7, belongs to problem 6) unblocker:  _7
Attempted to block on solved meta _7
```
`_7` is solved by pruning, so it is not a valid blocker anymore.  The logic of blockers does not seem to expect a meta suddently solved by pruning.  

Relevant code:
https://github.com/agda/agda/blob/fe4337982fc3a097ab6ee27554caefdcf934f281/src/full/Agda/TypeChecking/Conversion.hs#L1690-L1704
https://github.com/agda/agda/blob/fe4337982fc3a097ab6ee27554caefdcf934f281/src/full/Agda/TypeChecking/Conversion.hs#L1711
https://github.com/agda/agda/blob/fe4337982fc3a097ab6ee27554caefdcf934f281/src/full/Agda/TypeChecking/Conversion.hs#L1741-L1743
https://github.com/agda/agda/blob/fe4337982fc3a097ab6ee27554caefdcf934f281/src/full/Agda/TypeChecking/Conversion.hs#L1880-L1883

**Comment by andreasabel** [comment]
I might have introduced this regression when I refactored some code related to sorts during AIM XXXVI Delft and after.
Could be:
- #6623

**Comment by andreasabel** [comment]
Unfortunately, bisection only produces the usual suspect:
> 536b73f65801362f0217573b28f106af29014829 is the first bad commit
> Author: Jesper Cockx 
> Date:   Fri Nov 11 11:34:05 2022 +0000
> [ re #6211 ] Pull off the band-aid

This does not provide any interesting information...

Only that I could have been wrong about blaming myself...
