### ISSUE TITLE
hcomp symbols in interface not hidden under --cubical-compatible

### ISSUE THREAD

**Issue by sattlerc** [agda/agda#7048]
From #7044 ([comment](https://github.com/agda/agda/issues/7044#issuecomment-1873395839_)):

> When printing the signatures of the interface, I see `Inner.hcomp-T`. Why is that generated without `--cubical-compatible`?

Test case:
```agda
module Inner where

data T : Set where
  t : T
```
Running
```shell
agda-quicker Inner.agda -v 5 | grep hcomp
```
shows that cubical-related code is executed:
```
Generated name: [...] "hcomp-T" [...]
```

**Comment by andreasabel** [comment]
I suppose a check for `--cubical-compatible` is missing here: https://github.com/agda/agda/blob/5e47be63595e70eb901a477b2c18adca8df5b419/src/full/Agda/TypeChecking/Rules/Data.hs#L333-L335
and here: https://github.com/agda/agda/blob/5e47be63595e70eb901a477b2c18adca8df5b419/src/full/Agda/TypeChecking/Rules/Record.hs#L377-L379
