### ISSUE TITLE
confusing error message for ambiguous datatype module name

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#705]
Typechecking this
```agda
module test where

module A where
  data A : Set where

open A

open A
```
gives the error
```
Ambiguous module name A. It could refer to any one of
  A.A
  test.A
when scope checking the declaration
  open A
```
It would be nice to know that A.A is a datatype module. 

Original issue reported on code.google.com by `jmchap...@gmail.com` on 3 Oct 2012 at 8:23

**Comment by andreasabel** [comment]
Finally found a low-hanging fruit! :)  Fixing this 5 years later...  I still remember the original fix session with @jmchapman in the Wakeup-hotel during the Copenhagen AIM 2012.
