### ISSUE TITLE
Don't recompile if --keep-pattern-variables option changes

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#7059]
`--keep-pattern-variables` only affects interaction and should not require recompilation, but it's missing from

https://github.com/agda/agda/blob/561fdc2f87e732cc8ea8c3a2223041efef3a63d3/src/full/Agda/Interaction/Options/Base.hs#L1075-L1091

**Comment by nad** [comment]
I was going to ask you to update the user manual, but apparently this option was incorrectly not included in the following list:

https://github.com/agda/agda/blob/45146aac0e6ef20484c4e897a0519a6236586700/doc/user-manual/tools/command-line-options.rst?plain=1#L1701-L1759

**Comment by UlfNorell** [comment]
You mean it was *correctly* not added to the list, but *incorrectly* missing from the list in `recheckBecausePragmaOptionsChanged`.
