### ISSUE TITLE
Mimer triggers __IMPOSSIBLE__ in my homework assignment

### ISSUE THREAD

**Issue by ice1000** [agda/agda#7084]
Agda version 2.6.5-a445e3b

Error message:

```
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/Telescope.hs:668:24 in Agda-2.6\
.5-inplace:Agda.TypeChecking.Telescope
```

https://github.com/agda/agda/blob/master/src/full/Agda/TypeChecking/Telescope.hs#L668

For obvious reasons I can't share the reproduction publicly, but I can send a link to a private gist file to those who work on Mimer through emails.

EDIT: managed to simplify it by a LOT and does not contain my solutions:
https://gist.github.com/ice1000/0b0730d4b57d23ad974c060ef8a748f4

**Comment by UlfNorell** [comment]
Thanks for the report. Here is a further simplified test case:

```agda
module _ (Term : Set) where

  record QPER : Set₁ where
    field
      R : (M M' : Term) → Set
  open QPER public

  record QPERClosedTerm (Y : QPER) : Set where
    field
      M : Term

  _~_ : {Y : QPER} (tM tN : QPERClosedTerm Y) → Set
  _~_ {Y} tM tN = R Y (QPERClosedTerm.M tN) (QPERClosedTerm.M tM)

  ~-trans : (Y : QPER) (tM tN tP : QPERClosedTerm Y) → (tM ~ tN) → (tN ~ tP) → (tM ~ tP)
  ~-trans Y tM tN tP h h' = {!!}
```
