### ISSUE TITLE
REWRITE rule with confluence, inconsistencies with documentation and error messages

### ISSUE THREAD

**Issue by buggymcbugfix** [agda/agda#7090]
I was following the documentation on rewriting, specifically [confluence checking](https://agda.readthedocs.io/en/v2.6.4.1/language/rewriting.html#confluence-checking), which states

> [...] For example, if there are two rules suc m + n = suc (m + n) and m + suc n = suc (m + n), then there should also be a rule suc m + suc n = suc (suc (m + n)).

I tried this via the following code (note `--local-confluence-check`):

```agda
{-# OPTIONS --rewriting --local-confluence-check  #-}

module RewriteTest0 where

open import Agda.Builtin.Equality
open import Agda.Builtin.Equality.Rewrite
open import Data.Nat
open import Data.Nat.Properties
open import Relation.Binary.PropositionalEquality

+-suc-suc : ∀ (m n : ℕ) → suc m + suc n ≡ suc (suc (m + n))
+-suc-suc m n rewrite +-suc m n = refl

{-# REWRITE +-identityʳ +-suc +-suc-suc #-}

```

This gives me the following error message:

```
+-suc-suc  is not a legal rewrite rule, since the left-hand side 
suc m + suc n  reduces to  suc (m + suc n)
when checking the pragma REWRITE +-identityʳ +-suc +-suc-suc
```

I think this implies a bug or that the documentation is wrong or misleading. Any feedback would be appreciated.

The following works fine:

```agda
{-# OPTIONS --rewriting --local-confluence-check #-}

module RewriteTest1 where

open import Agda.Builtin.Equality
open import Agda.Builtin.Equality.Rewrite
open import Data.Nat
open import Data.Nat.Properties
open import Relation.Binary.PropositionalEquality

{-# REWRITE +-identityʳ +-suc #-}

+comm : ∀ {m n : ℕ} → m + n ≡ n + m
+comm {zero} = refl
+comm {suc m} = cong suc (+comm {m})
```

When changing `--local-confluence-check` to `--confluence-check` in `RewriteTest1` , I get the following error messages:

```
Global confluence check failed: suc n + suc n₁ can be rewritten to
either suc (suc n + n₁) or suc (n + suc n₁).
Possible fix: add a rewrite rule with left-hand side suc n + suc n₁
to resolve the ambiguity.
when checking confluence of the rewrite rule +-suc with
Agda.Builtin.Nat._+_-clause2

Global confluence check failed: zero + suc n can be rewritten to
either suc (zero + n) or suc n.
Possible fix: add a rewrite rule with left-hand side zero + suc n
to resolve the ambiguity.
when checking confluence of the rewrite rule +-suc with
Agda.Builtin.Nat._+_-clause1

Global confluence check failed: suc n + 0 can be rewritten to
either suc n or suc (n + 0).
Possible fix: add a rewrite rule with left-hand side suc n + 0 to
resolve the ambiguity.
when checking confluence of the rewrite rule +-identityʳ with
Agda.Builtin.Nat._+_-clause2
```

Changing my code to include the equalities suggested by the error messages makes Agda accept the program. (I am confused, however, as two of them seem to just be special cases of existing rules, see code comments below. Also, the documentation does not mention these being needed.)

```agda
{-# OPTIONS --rewriting --confluence-check #-}

module RewriteTest2 where

open import Agda.Builtin.Equality
open import Agda.Builtin.Equality.Rewrite
open import Data.Nat
open import Data.Nat.Properties
open import Relation.Binary.PropositionalEquality

-- the documentation mentioned, that this rule was needed
+-suc-suc : ∀ (m n : ℕ) → suc m + suc n ≡ suc (suc (m + n))
+-suc-suc m n rewrite +-suc m n = refl

-- we already know this from the definition of ℕ, not sure why we need this
zero+suc-n : ∀ (n : ℕ) → 0 + suc n ≡ suc n
zero+suc-n n = refl

-- a specialisation of identityʳ, not sure why we need this
suc-n+zero : ∀ (n : ℕ) → suc n + 0 ≡ suc n
suc-n+zero n rewrite +-identityʳ n = refl

{-# REWRITE +-identityʳ +-suc +-suc-suc zero+suc-n suc-n+zero #-}

+comm : ∀ {m n : ℕ} → m + n ≡ n + m
+comm {zero} = refl
+comm {suc m} = cong suc (+comm {m})

```

Changing the flag in `RewriteTest2` to `--local-confluence-check`, however, gives an error message:

```
+-suc-suc  is not a legal rewrite rule, since the left-hand side 
suc m + suc n  reduces to  suc (m + suc n)
when checking the pragma
REWRITE +-identityʳ +-suc +-suc-suc zero+suc-n suc-n+zero
```
This, despite the documentation saying that `--local-confluence-check` is less restrictive.

##### Addenda

This came from me trying to minimise an error I was getting while using `REWRITE` in a project, which unfortunately I cannot share at this moment. In that project, enabling `--confluence-check` gives the following error:
```
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/Rewriting/Confluence.hs:606:19 in Agd-2.6.4.1-d9da44fe:Agda.TypeChecking.Rewriting.Confluence
```
When using holes in a theorem that uses the rewrite rules, I get the following error:
```
Panic: uncaught pattern violation
```

```
$ agda --version     
Agda version 2.6.4.1
```

**Comment by jespercockx** [comment]
```
+-suc-suc  is not a legal rewrite rule, since the left-hand side 
suc m + suc n  reduces to  suc (m + suc n)
when checking the pragma REWRITE +-identityʳ +-suc +-suc-suc
```

This error doesn't have anything to do with the confluence checker, it appears also without `--local-confluence-check`. The reason is that rewrite rules are only applied to *neutral* terms, but here the LHS is not. If you do want to have this rule, you should replace the LHS with `suc (m + suc n)`.

The (global) confluence check requires additional "ghost" rewrite rules to be added that are specialized versions of the existing rewrite rules but are needed to guide the confluence checker. These rules do not always have a neutral LHS but still need to be given, so the check that rules have a neutral LHS is disabled when `--confluence-check` is enabled.

Since the error for a rewrite rule with a non-neutral LHS is really a very limited version of a confluence check, I think it would perhaps be best to turn it into a warning instead. Or even better, we could remove the check completely and enable `--local-confluence-check` by default. In your example, you would then get a warning saying that `suc m + suc n` reduces to both `suc (m + suc n)` and `suc (suc (m + n))` but these two don't have a common reduct. What do you think?

Regarding the internal error: unfortunately there is not much I can do about that without a (preferably small) test case. Maybe you could try to minimize it by deleting stuff from the project and rename the remaining functions to obscure the code?

**Comment by jespercockx** [comment]
Actually, perhaps the internal error is the same as in https://github.com/agda/agda/issues/7029. Could you try if my fix in https://github.com/agda/agda/pull/7031 also fixes your issue?

**Comment by buggymcbugfix** [comment]
> If you do want to have this rule, you should replace the LHS with suc (m + suc n)

Changing the LHS of the rule to `suc(m + suc n)` only seems to make the confluence checker even more angry!

```agda
{-# OPTIONS --rewriting --confluence-check #-}

module RewriteTest3 where

open import Agda.Builtin.Equality
open import Agda.Builtin.Equality.Rewrite
open import Data.Nat
open import Data.Nat.Properties
open import Relation.Binary.PropositionalEquality

+-suc-suc : ∀ (m n : ℕ) → suc (m + suc n) ≡ suc (suc (m + n))
+-suc-suc m n rewrite +-suc m n = refl

{-# REWRITE +-identityʳ +-suc +-suc-suc #-}
```
gives
```
Global confluence check failed: suc (m + suc n) + 0 can be
rewritten to either suc (m + suc n) or suc (suc (m + n)) + 0.
Possible fix: add a rewrite rule with left-hand side
suc (m + suc n) + 0 to resolve the ambiguity.
when checking confluence of the rewrite rule suc-n+zero with
+-suc-suc

Global confluence check failed: 0 + suc (m + suc n) can be
rewritten to either suc (m + suc n) or 0 + suc (suc (m + n)).
Possible fix: add a rewrite rule with left-hand side
0 + suc (m + suc n) to resolve the ambiguity.
when checking confluence of the rewrite rule zero+suc-n with
+-suc-suc

Global confluence check failed: suc (m + suc (m₁ + suc n)) can be
rewritten to either suc (suc (m + (m₁ + suc n))) or
suc (m + suc (suc (m₁ + n))).
Possible fix: add a rewrite rule with left-hand side
suc (m + suc (m₁ + suc n)) to resolve the ambiguity.
when checking confluence of the rewrite rule +-suc-suc with itself

Global confluence check failed: suc (suc n + suc n₁) can be
rewritten to either suc (suc (suc n + n₁)) or
suc (suc (n + suc n₁)).
Possible fix: add a rewrite rule with left-hand side
suc (suc n + suc n₁) to resolve the ambiguity.
when checking confluence of the rewrite rule +-suc-suc with
Agda.Builtin.Nat._+_-clause2

Global confluence check failed: suc (zero + suc n) can be rewritten
to either suc (suc (zero + n)) or suc (suc n).
Possible fix: add a rewrite rule with left-hand side
suc (zero + suc n) to resolve the ambiguity.
when checking confluence of the rewrite rule +-suc-suc with
Agda.Builtin.Nat._+_-clause1

Global confluence check failed: suc n + suc n₁ can be rewritten to
either suc (suc n + n₁) or suc (n + suc n₁).
Possible fix: add a rewrite rule with left-hand side suc n + suc n₁
to resolve the ambiguity.
when checking confluence of the rewrite rule +-suc with
Agda.Builtin.Nat._+_-clause2
```

---

> Or even better, we could remove the check completely and enable --local-confluence-check by default.

This might make REWRITE rules less confusing to use. Is there any downside to this approach? Non-confluent rewrite rules sound like a problem to me. Or is there a use case for them?

Having read the documentation, I confess that I don't understand the difference between local and global confluence.

---

> Actually, perhaps the internal error is the same as in https://github.com/agda/agda/issues/7029. Could you try if my fix in https://github.com/agda/agda/pull/7031 also fixes your issue?

I tried to run the nightly release for macOS, which I think contains your fix, but am getting the following error message:

```
The lib directory /Users/runner/.cabal/share/x86_64-osx-ghc-9.8.1/Agda-2.6.5/lib does not exist
CallStack (from HasCallStack):
  error, called at src/full/Agda/Interaction/Library.hs:148:8 in Agda-2.6.5-inplace:Agda.Interaction.Library
```

I'm not sure what to do with this.

**Comment by jespercockx** [comment]
> Changing the LHS of the rule to suc(m + suc n) only seems to make the confluence checker even more angry!

Oh yeah, in this case it's best to add a rewrite rule from `m + suc n` to `suc (m + n)`. In general it's best to formulate rewrite rules as generally as possible. 

The exception to this rule is when you are using `--global-confluence-check`, as I explained above.
