### ISSUE TITLE
Agda build flags appear as "automatic", but they are all "manual"

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#7095]
Is there a reason why the cabal build flags of Agda are mostly "automatic"?  (I think none of it is switched on by the cabal constraint solver...)
https://github.com/agda/agda/blob/34ada52dc8d85ebf5e16c585a2af79bdea75488d/Agda.cabal#L164-L191

Automatic flags are hidden on hackage:

<img width="546" alt="Screenshot 2024-02-07 at 13 54 17" src="https://github.com/agda/agda/assets/1155218/0df48d31-8475-48c1-a8d8-bc6720d398e4">

This is how it looks when you show them:

<img width="550" alt="Screenshot 2024-02-07 at 13 49 26" src="https://github.com/agda/agda/assets/1155218/8cf9dc12-2321-448e-b549-fb94283070c5">

**Comment by nad** [comment]
I think it makes sense to make all flags manual.
