### ISSUE TITLE
Pattern overlap detector doesn't do the right thing on Char

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#711]
I would expect the following snippet to report an "Unreachable clause" error:

``` agda
module Char where

open import Data.Char

ex : Char → Set₁
ex 'c' = Set
ex 'c' = Set
ex _ = Set
```

But it just typechecks with no complaint.

Original issue reported on code.google.com by `pumpkingod@gmail.com` on 11 Oct 2012 at 12:15
- Merged into: #708

**Comment by andreasabel** [comment]
Duplicate of #2243.
