### ISSUE TITLE
Citation.cff

### ISSUE THREAD

**Issue by anuyts** [agda/agda#7123]
This repository needs a [citation.cff](https://citation-file-format.github.io/) file so people can easily cite it in papers.

See also [this stackexchange answer](https://academia.stackexchange.com/a/172780/144474).

Here's a handy generator: <https://citation-file-format.github.io/cff-initializer-javascript/#/>.

The standard and cubical libraries have examples:
* <https://github.com/agda/agda-stdlib/blob/master/CITATION.cff>
* <https://github.com/agda/cubical/blob/master/CITATION.cff>

**Comment by lawcho** [comment]
Done in PR #6444
