### ISSUE TITLE
Mimer internal error when querying `recRecursive`

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#7133]
```agda
open import Agda.Primitive
open import Relation.Binary.Bundles using (Setoid)

module _ {ℓ₁ ℓ₂ : Level} (sto : Setoid ℓ₁ ℓ₂) where

data D : Set {!!} where  -- C-c C-a
  c : D
```
Mimer in the hole gives an internal error here: https://github.com/agda/agda/blob/7eb6303e0c9777a70de565c5de1f78c656817283/src/full/Agda/TypeChecking/Monad/Base.hs#L2961-L2964

**Comment by UlfNorell** [comment]
We hit the impossible because `recMutual` is `Nothing` for `Relation.Binary.Bundles.Setoid`. The docs say it should only be `Nothing` if it hasn't yet been computed by the positivity checker, so not sure what's going on here.

Here's a self-contained test case:

```agda
module _ where

open import Agda.Primitive

record Point (A : Set) : Set where
  field
    pt : A

record PointedSet : Set₁ where
  field
    Carrier : Set
    point   : Point Carrier

module _ (sto : PointedSet) where

  foo : Set
  foo = {!!}
```
