### ISSUE TITLE
Non-sensical error since 2.5.4 when applying a non-function

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#7158]
Reported by @plt-amy in https://github.com/agda/agda/issues/7156#issuecomment-1971894991
```agda
open import Agda.Builtin.Nat

record T : Set where
  field
    f : Nat → Nat

foo : T
foo .T.f = suc

test : Nat
test = foo 123
```
Agda 2.5.3 said (good):
```
T should be a function type, but it isn't
when checking that 123 is a valid argument to a function of type T
```
Since 2.5.4 Agda says (bad):
```
T !=< Nat of type Set
when checking that the inferred type of an application
  T
matches the expected type
  Nat
```

@plt-amy wrote:
> I suspect that this would be fixable by checking that length tel >= sArgsLen in [Application.hs](https://github.com/agda/agda/blob/d959b19d84f6ed61cb4f9e47c6e719c1404a8113/src/full/Agda/TypeChecking/Rules/Application.hs#L681).

It seems that `telViewUpTo'` here is not sufficient, correct would be a "telViewExactly" that asks for exactly `sArgsLen` visible arguments:
https://github.com/agda/agda/blob/d959b19d84f6ed61cb4f9e47c6e719c1404a8113/src/full/Agda/TypeChecking/Rules/Application.hs#L658
So, yes, we need to check `length tel >= sArgsLen` otherwise the target type is bogus and checking it is moot.

**Comment by andreasabel** [comment]
Possibly this regression originates from e49d1ca276e5adbf2eb9f6cd33926b786cef78f7.  Unfortunately, we didn't seem to have a test like the OP back then, so the regression went unnoticed.

**Comment by andreasabel** [comment]
I wonder whether one could find a meaner counterexample, e.g. where the checking against the bogus target instantiates some meta variables which make type checking fail with an even more obscure error.

**Comment by andreasabel** [comment]
Fixed by 084dd4dc20c48d08cfba99e845de5cd614feb5ec.

**Comment by plt-amy** [comment]
That was speedy, thank you!

**Comment by andreasabel** [comment]
Well, I just implemented the fix you outlined...
