### ISSUE TITLE
Incorrect goal type when hole is in a data declaration

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#717]
Agda version = darcs head on August 2nd, 2012

It looks like this bug was fixed for "record", but still exists for "data":
http://code.google.com/p/agda/issues/detail?id=387&can=1&q=goal

In the example below, the goal type in the first pattern clause is actually the 
goal type of the hole in the data declaration.

``` agda
module Bug where

data Foo (A : Set) : Set where
  foo : Foo A

data Bar : Set where
  bar baz : Foo {!!} → Bar

fun : (x : Bar) → Foo Bar
fun (bar y) = {!!} -- goal is "Set" (incorrect, should be "Foo Bar")
fun (baz z) = {!!} -- goal is "Foo Bar" (correct)
```

Original issue reported on code.google.com by `Larrythe...@gmail.com` on 18 Oct 2012 at 3:51
- Merged into: #707

**Comment by andreasabel** [comment]
This was not fixed yet.
