### ISSUE TITLE
Interactive highlighting does not color comments

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#726]
When I turn on interactive highlighting, and I load a file, and it is interactively colored, the comments stay black.  I can make them red with font-lock-fontify-buffer.

My emacs version:

GNU Emacs 22.3.1 (i386-apple-darwin9.5.0, Carbon Version 1.6.0)
 of 2008-11-01 on leopard.local

Original issue reported on code.google.com by `andreas....@gmail.com` on 21 Oct 2012 at 5:14

**Comment by asr** [comment]
We currently don't support GNU Emacs 22.3 which was [released](https://www.gnu.org/software/emacs/history.html) 10 years ago, so I'm closing the issue.
