### ISSUE TITLE
Different arity of clauses

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#727]
The following does not compile:

```agda
module Test where

data ℕ : Set where
  O : ℕ
  S : ℕ → ℕ

type : ℕ → Set
type O = ℕ
type (S n) = ℕ → type n

fun : (n : ℕ) → type n
fun O = O
fun (S n) m = fun n
```

The error message point on the last line and says:
```
Left hand side gives too many arguments to a function of type
(n : ℕ) → type n
when checking that the clause fun (S n) m = fun n has type
(n : ℕ) → type n
```
It works if I replace the last line by
```
fun (S n) = λ m → fun n
```
Given that [type (S n)] is syntactically a function type, I would expect the 
first pattern to work.

Original issue reported on code.google.com by `guillaum...@gmail.com` on 22 Oct 2012 at 9:52

**Comment by phile314** [comment]
All known clause-arity issues in the MAlonzo & UHC compiler backends have been fixed, closing this issue.

**Comment by andreasabel** [comment]
Thanks.
