### ISSUE TITLE
Builtins ZERO and SUC should not be needed

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#730]
I guess that `{-# BUILTIN NATURAL N #-}` checks that `N` is a datatype with exactly two constructors of type `N` and `N -> N`.

Hence I don’t see the need for the builtins `ZERO` and `SUC`, Agda should be able to deduce them from the type `N` given in the builtin `NATURAL`.

Perhaps there are others builtins with similar redundancy.

Original issue reported on code.google.com by `guillaum...@gmail.com` on 23 Oct 2012 at 4:02

**Comment by andreasabel** [comment]
In the same way, REFL is not needed by implicit in EQUALITY.  See #2389.
