### ISSUE TITLE
Search for project root crashes when (parent) directory lacks permissions

### ISSUE THREAD

**Issue by lonetech** [agda/agda#7331]
Tested on Nix-on-Droid with Agda 2.6.4 and Debian trixie/sid with Agda 2.6.3-1, Debian trixie/sid with cabal built Agda 2.6.4.3. 

Sample setup (to emulate problem on a typical Linux system):

    sudo chmod o-r /     # Remember later to revert with sudo chmod +r /
    mkdir -p testdir/hello
    chmod -r testdir
    cd testdir/hello
    echo 'main = putStrLn "hello"' > hello.agda

Tried to run agda hello.agda. Immediately errors with:

    /some/path/above: getDirectoryContents:openDirStream: permission
    denied (Permission denied)

Note the complete absence of indication what Agda is looking for. This isn't indicated in the installation or hello world instructions. Searched around and found documentation hinting at a "project root" and .agda-lib files, so tried creating a hello.agda-lib:

    echo >hello.agda-lib name: hello

Result:

    /: getDirectoryContents:openDirStream: permission denied
    (Permission denied)

I can only guess this isn't the project root search because it's targeting the directory differently. The compiler just expects global system access without motivation. There's no indication where in the compiler this is or why it's not handled.

**Comment by andreasabel** [comment]
We do not catch exceptions when looking for the project root: https://github.com/agda/agda/blob/37718bf47402201b56475ed4d4ae961d05a6b090/src/full/Agda/Interaction/Library.hs#L191-L198
We should catch `isPermissionError`:
https://hackage.haskell.org/package/directory-1.3.8.5/docs/System-Directory.html#v:listDirectory
