### ISSUE TITLE
MAlonzo bug: `unreachable code reached`

### ISSUE THREAD

**Issue by WhatisRT** [agda/agda#7380]
Here's a piece of code that generates faulty Haskell code:

```agda
module Test where

open import Agda.Builtin.IO
open import Agda.Builtin.Unit
open import Agda.Builtin.Nat
open import Agda.Builtin.Sigma

record R : Set where
  field x : Nat

variable r : R

data D : R → Nat → Set where
  c : let open R r in D r x

f : R → Nat
f r = fst g
  where
    g : Σ Nat (D r)
    g = (_ , c)

postulate print : Nat → IO ⊤
{-# COMPILE GHC print = print #-}

main = print (f (record { x = 3 }))
```

When compiled (with `agda --compile`, Agda version 2.6.4) and ran, it produces the following error message:
```
Test: Agda: unreachable code reached.
CallStack (from HasCallStack):
  error, called at ./MAlonzo/RTE.hs:44:23 in main:MAlonzo.RTE
```

Making this fail is quite delicate. Binding `r` without the `variable` block, replacing the `let open` with anything else or replacing the `_` in `g` make the code compile correctly. The `print` part at the bottom doesn't really matter, I just needed something to force the application of `f` & make compilation easy.

**Comment by andreasabel** [comment]
@WhatisRT Hereby I honor you with the _Improbable Bug Award_!

**Comment by andreasabel** [comment]
What is worse is that your MWE causes a crash in 2.7.0-rc1 if run with an existing interface:
```
$ agda-2.7.0-rc1 -c Issue7380.agda
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE_VERBOSE__, called at src/full/Agda/TypeChecking/Reduce.hs:224:18 
```

**Comment by WhatisRT** [comment]
Is there any chance this can get fixed in 2.7? It's not super important, but we'll need to put a workaround in our code until this is fixed.

**Comment by andreasabel** [comment]
Ok.  Maybe it is related to #7382.

**Comment by AndrasKovacs** [comment]
This example compiles fine for me after fixing #7382.

**Comment by andreasabel** [comment]
> This example compiles fine for me after fixing #7382.

Well, compilation was never the problem.  The exception occurs when running the compiled code.

**Comment by andreasabel** [comment]
This might be an instance of the problem of combining generalization with parametrized modules:
- #6916 
- #6770

These issues have been bumped to 2.8.0, so I am afraid this issue will follow suit.  (The hope that #7383 would fix this has been dispelled.)

**Comment by UlfNorell** [comment]
The problem was that we forgot to add clauses to the projections from the generalised telescope record that holds all the generalised variables. Normally this isn't a problem because the projections get beta-reduced away before we need any clauses, but in this case the `let open` produces a definition that contains a reference to the generalised field projection.

Fixed by the PR above.

**Comment by UlfNorell** [comment]
Not related to 6916 or 6770 by the way.
