### ISSUE TITLE
.cabal description "...: It ..."

### ISSUE THREAD

**Issue by juhp** [agda/agda#7384]
The Agda.cabal description [has](https://github.com/agda/agda/blob/master/Agda.cabal#L15):

> Agda is a dependently typed functional programming language: It has inductive families, 

This should be either two sentences (ie `s/:/./`) or the "It" should be changed "it", I think, to be grammatically correct :-)
(I was going to open a PR for the latter, but thought I would ask which option is preferred first.)

((Possibly a new paragraph could also work...))

**Comment by andreasabel** [comment]
Probably the status quo is correct American English.

https://www.grammarbook.com/blog/commas/capitalization-with-colons/
> Capitalization rule with sentences after colons: If only one sentence follows the colon, it is often not necessary to capitalize the first word of the new sentence. If two or more sentences follow the colon, capitalize the first word of each sentence following.

https://libguides.royalroads.ca/punctuation-capitalization/capsemicolons
> When using a colon to join two clauses, capitalize the first word of the clause after the colon if it is a complete sentence (American Psychological Association [APA], 2020, p. 156)

**Comment by juhp** [comment]
Okay thank you, I stand corrected then - I will sync to the Fedora package.

**Comment by juhp** [comment]
If you then change the spelling of "parameterised" to use American "z", I could use the upstream description directly in the Fedora package.

**Comment by andreasabel** [comment]
Mhm, yes, we have some AE/BE inconsistencies.  E.g. in the Agda code base `generalize` dominates (but is not used exclusively), the standard library seems to prefer `generalise`.
I guess spelling variants are caused by different preferences of the different authors.

Do we need to streamline the spelling?  Or should we just embrace diversity?
