### ISSUE TITLE
Is pattern `AnnP` unused?  (added in Oct 2020 as "not usable yet")

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#7389]
I was wondering what `AnnP` meant and did a grep that showed no producers of this constructor.  It is just juggled around but never created.
Blame gets me to commit 22e9a1241651bdb64d57b7ce390f8e4857eabdec:
- #5006 

> [ patterns ] Add type annotations to abstract syntax for patterns (not usable yet)

@jespercockx  Is there a use for `AnnP` now?  Or can we remove it?

**Comment by jespercockx** [comment]
I think I had a plan for this once, but whatever it was it's long gone now. So yes, removing it seems like a good idea.

**Comment by andreasabel** [comment]
@jespercockx : It seems that it is produced from `Reflected` syntax (I overlooked this).
So maybe you intended to use it in reflection.
