### ISSUE TITLE
Mimer internal error in hole with constraint

### ISSUE THREAD

**Issue by szumixie** [agda/agda#7402]
```agda
postulate
  A : Set
  x : A
  f : (P : A → Set) → P x

g : (P : ((A → A) → A) → Set) → P (λ k → k x)
g P = f (λ x → P {! !})
```
Running `C-c C-a` in the hole results in:
```
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/Telescope.hs:688:24 in Agda-2.8.0-8OtZvJ9h6Mn4rrWgQM63zA:Agda.TypeChecking.Telescope
```
which is at: https://github.com/agda/agda/blob/5da3f3f2be5fc0d4ed6a2b828bd751e44e29292f/src/full/Agda/TypeChecking/Telescope.hs#L688 called from: https://github.com/agda/agda/blob/5da3f3f2be5fc0d4ed6a2b828bd751e44e29292f/src/full/Agda/Mimer/Mimer.hs#L1141

There's no internal error if `P : ((A → A) → A) → Set` is a postulate instead of a parameter.

**Comment by andreasabel** [comment]
Thanks for the report.

This also affects `2.7.0-rc1` but it was decided to release Mimer as-is, so we will not block 2.7.0 on this issue.
