### ISSUE TITLE
Trigger failure of `checkModalityArgs`

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#7416]
The error "Telescope variable..." has no reproducer in our testsuite.
https://github.com/agda/agda/blob/a7edb851ddbd2eff62fab399542a22fdb68b909e/src/full/Agda/TypeChecking/Modalities.hs#L99-L105
Could someone add a reproducer?  @jpoiret maybe you can find one?

**Comment by jpoiret** [comment]
I'll have a look!

**Comment by jpoiret** [comment]
Here is a reproducer:
```agda
{-# OPTIONS --cohesion #-}

module _ where

postulate A : Set

module M (a : A) where
  b : A
  b = a

  @♭ c : A
  c = b
```

Where should this be added?

**Comment by andreasabel** [comment]
Thanks!
This should go under `test/Fail`. 
(Remember to commit the  generated`.err` file also.)

Also, we want to get rid of _Generic[Doc]Error_, so if you have some time to spare to turned this into a named error (with a dedicated constructor), that would be extra great!

**Comment by jpoiret** [comment]
Done with #7447, LMK if that's good!
