### ISSUE TITLE
`cabal install Agda` fails -- missing files in multiple pacakges

### ISSUE THREAD

**Issue by sp1ff** [agda/agda#7420]
Arch linux, GHC 9.2.8. `cabal install Agda` fails with the following build log:

<details>
<summary>Click to expand</summary>

Resolving dependencies...
Build profile: -w ghc-9.2.8 -O1
In order, the following will be built (use -v for more details):
 - Agda-2.6.4.3 (lib:Agda, exe:agda, exe:agda-mode) (requires build)
Starting     Agda-2.6.4.3 (all, legacy fallback)
Building     Agda-2.6.4.3 (all, legacy fallback)

Failed to build Agda-2.6.4.3.
Build log (
/home/mgh/.cabal/logs/ghc-9.2.8/Agda-2.6.4.3-8b1aba1e2943ef3513d475cc7c871709b4f82c784d7c6756f0b83edaee754556.log
):
[1 of 1] Compiling Main             ( /tmp/cabal-install.-1562472/dist-newstyle/tmp/src-1562472/Agda-2.6.4.3/dist/setup/setup.hs, /tmp/cabal-install.-1562472/dist-newstyle/tmp/src-1562472/Agda-2.6.4.3/dist/setup/Main.o )
Linking /tmp/cabal-install.-1562472/dist-newstyle/tmp/src-1562472/Agda-2.6.4.3/dist/setup/setup ...
Configuring Agda-2.6.4.3...
Preprocessing executable 'agda-mode' for Agda-2.6.4.3..
Building executable 'agda-mode' for Agda-2.6.4.3..
[1 of 2] Compiling Paths_Agda       ( dist/build/agda-mode/autogen/Paths_Agda.hs, dist/build/agda-mode/agda-mode-tmp/Paths_Agda.o )
[2 of 2] Compiling Main             ( src/agda-mode/Main.hs, dist/build/agda-mode/agda-mode-tmp/Main.o )
Linking dist/build/agda-mode/agda-mode ...
Preprocessing library for Agda-2.6.4.3..
Building library for Agda-2.6.4.3..
[  1 of 427] Compiling Agda.Interaction.ExitCode ( src/full/Agda/Interaction/ExitCode.hs, dist/build/Agda/Interaction/ExitCode.o, dist/build/Agda/Interaction/ExitCode.dyn_o )
[  2 of 427] Compiling Agda.Termination.CutOff ( src/full/Agda/Termination/CutOff.hs, dist/build/Agda/Termination/CutOff.o, dist/build/Agda/Termination/CutOff.dyn_o )
[  3 of 427] Compiling Agda.Termination.Semiring ( src/full/Agda/Termination/Semiring.hs, dist/build/Agda/Termination/Semiring.o, dist/build/Agda/Termination/Semiring.dyn_o )
[  4 of 427] Compiling Agda.TypeChecking.Monad.Debug[boot] ( src/full/Agda/TypeChecking/Monad/Debug.hs-boot, dist/build/Agda/TypeChecking/Monad/Debug.o-boot, dist/build/Agda/TypeChecking/Monad/Debug.dyn_o )
[  5 of 427] Compiling Agda.Utils.AffineHole ( src/full/Agda/Utils/AffineHole.hs, dist/build/Agda/Utils/AffineHole.o, dist/build/Agda/Utils/AffineHole.dyn_o )
[  6 of 427] Compiling Agda.Utils.Applicative ( src/full/Agda/Utils/Applicative.hs, dist/build/Agda/Utils/Applicative.o, dist/build/Agda/Utils/Applicative.dyn_o )
[  7 of 427] Compiling Agda.Utils.Boolean ( src/full/Agda/Utils/Boolean.hs, dist/build/Agda/Utils/Boolean.o, dist/build/Agda/Utils/Boolean.dyn_o )
[  8 of 427] Compiling Agda.Syntax.Internal.Univ ( src/full/Agda/Syntax/Internal/Univ.hs, dist/build/Agda/Syntax/Internal/Univ.o, dist/build/Agda/Syntax/Internal/Univ.dyn_o )
[  9 of 427] Compiling Agda.Utils.CallStack.Base ( src/full/Agda/Utils/CallStack/Base.hs, dist/build/Agda/Utils/CallStack/Base.o, dist/build/Agda/Utils/CallStack/Base.dyn_o )
[ 10 of 427] Compiling Agda.Utils.Char  ( src/full/Agda/Utils/Char.hs, dist/build/Agda/Utils/Char.o, dist/build/Agda/Utils/Char.dyn_o )
[ 11 of 427] Compiling Agda.Utils.Environment ( src/full/Agda/Utils/Environment.hs, dist/build/Agda/Utils/Environment.o, dist/build/Agda/Utils/Environment.dyn_o )
[ 12 of 427] Compiling Agda.Utils.Fail  ( src/full/Agda/Utils/Fail.hs, dist/build/Agda/Utils/Fail.o, dist/build/Agda/Utils/Fail.dyn_o )
[ 13 of 427] Compiling Agda.Utils.Function ( src/full/Agda/Utils/Function.hs, dist/build/Agda/Utils/Function.o, dist/build/Agda/Utils/Function.dyn_o )
[ 14 of 427] Compiling Agda.TypeChecking.SizedTypes.Utils ( src/full/Agda/TypeChecking/SizedTypes/Utils.hs, dist/build/Agda/TypeChecking/SizedTypes/Utils.o, dist/build/Agda/TypeChecking/SizedTypes/Utils.dyn_o )
[ 15 of 427] Compiling Agda.Utils.Functor ( src/full/Agda/Utils/Functor.hs, dist/build/Agda/Utils/Functor.o, dist/build/Agda/Utils/Functor.dyn_o )
[ 16 of 427] Compiling Agda.Utils.HashTable ( src/full/Agda/Utils/HashTable.hs, dist/build/Agda/Utils/HashTable.o, dist/build/Agda/Utils/HashTable.dyn_o )

src/full/Agda/Utils/HashTable.hs:18:1: error:
    Could not find module ‘Data.Hashable’
    There are files missing in the ‘hashable-1.4.3.0’ package,
    try running 'ghc-pkg check'.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
18 | import Data.Hashable
   | ^^^^^^^^^^^^^^^^^^^^

src/full/Agda/Utils/HashTable.hs:19:1: error:
    Could not find module ‘Data.Vector.Hashtables’
    There are files missing in the ‘vector-hashtables-0.1.2.0’ package,
    try running 'ghc-pkg check'.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
19 | import qualified Data.Vector.Hashtables as H
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/full/Agda/Utils/HashTable.hs:20:1: error:
    Could not find module ‘Data.Vector.Mutable’
    There are files missing in the ‘vector-0.13.1.0’ package,
    try running 'ghc-pkg check'.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
20 | import qualified Data.Vector.Mutable as VM
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/full/Agda/Utils/HashTable.hs:21:1: error:
    Could not find module ‘Data.Vector’
    There are files missing in the ‘vector-0.13.1.0’ package,
    try running 'ghc-pkg check'.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
21 | import qualified Data.Vector as V
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build Agda-2.6.4.3. See the build log above for details.
</details>

**Comment by UlfNorell** [comment]
This looks like you have broken packages on your system, unrelated to Agda. See if the suggested `ghc-pkg check` tells you anything interesting. Another option is to install a fresh version of ghc (for instance 9.6.6) and try again.

**Comment by sp1ff** [comment]
Thanks for the quick response. `ghc-pkg check` was unhelpful.

My Haskell toolchain was installed via the native Arch packages. I removed them all & started over with `ghcup`. I was then able to install Agda using my new `cabal` install.
