### ISSUE TITLE
Erasure and irrelevance forbid deeper absurd patterns

### ISSUE THREAD

**Issue by Jesin** [agda/agda#7428]
It seems obviously consistent to allow arbitrarily deep matching on erased or irrelevant arguments on lines that contain absurd patterns, because if those lines are ever evaluated then we must have some other source of inconsistency. But for some reason Agda (as of 2.6.4.3) forbids this anyway. Here is a toy example that compiles if the `@0` and `@irr` annotations are both removed, but is rejected if either annotation remains in use:
```agda
<⊎≡⇒≤ : {n k : ℕ} → @0 @irr (n < k ⊎ n ≡ k) → n ≤ k
<⊎≡⇒≤ {0} _ = z≤n
<⊎≡⇒≤ {suc _} {0} (inj₁ ())
<⊎≡⇒≤ {suc _} {0} (inj₂ ())
<⊎≡⇒≤ {suc _} {suc _} p = s≤s (<⊎≡⇒≤ (down p)) where
  down : {n k : ℕ} → suc n < suc k ⊎ suc n ≡ suc k → n < k ⊎ n ≡ k
  down (inj₁ (s≤s p)) = inj₁ p
  down (inj₂ refl) = inj₂ refl
```
This particular example is a relatively minor annoyance in the irrelevance case, because the offending lines can be refactored into `<⊎≡⇒≤ {suc _} {0} p = contradiction-irr p λ{(inj₁ ()); (inj₂ ())}` or `<⊎≡⇒≤ {suc _} {0} p = ⊥-elim-irr (case p of λ{(inj₁ ()); (inj₂ ())})`, but I still feel this should not be necessary. This fix is also rejected in the erasure case due to #6765, and the stdlib contains no `contradiction-erased` or `⊥-elim-erased`, so that needs to be user-defined.

(It would also be nice if `--erased-matches` were usable in cases where 1 constructor is valid but the other constructors need deeper absurd patterns to refute. This change may need a bit more care, but I would be surprised if the precise shallowness of the matching were actually used anywhere in the argument for the consistency of `--erased-matches` in any detail beyond "it needs to be finite", so I am pretty confident it is equiconsistent with the existing behavior of `--erased-matches`.)

**Comment by Jesin** [comment]
I said "seems obviously consistent", but we can go further than that. The refactor of `funcname other-patterns absurd-patterns` into `funcname other-patterns impossible-arg = ⊥-elim-irr (case impossible-arg of λ{absurd-patterns})` is such a general dead-simple mechanical transformation that I believe it constitutes a constructive proof that the main proposal here (the part that does not touch `--erased-matches`) does not change the expressive power of the language and would only be a convenience.

**Comment by Jesin** [comment]
I believe the main proposal here (the one that **does not touch** the case where 1 constructor is still valid with `--erased-matches`) is equivalent to automatically transforming `funcname other-patterns absurd-patterns` to `funcname other-patterns erased-irr-arg = ⊥-elim-erased-irr (case erased-irr-arg of λ{absurd-patterns})` during elaboration to case trees. Since this transformation could be done purely syntactically without touching the core language, that should guarantee it is safe.

**Comment by Jesin** [comment]
I suppose the existence of a relatively easy refactor that only needs a simple helper function makes this matter less, but it would be nice for ease-of-use.

The change to `--erased-matches` is more interesting because there's no easy obvious refactor, but harder to prove safe for the same reason. I'm considering a larger transformation that defines an indexed datatype with precisely 1 constructor per branch of the function that's being compiled, with 1 slot per variable that's matched on, then splitting the function into 2 parts: a `pack-args` which takes all the original arguments at relevant modality and uses them to construct the new datatype, then an `unpack-args` which uses the packed args in the erased positions while matching on the original args in the relevant positions, which may make this easier to analyze.

**Comment by nad** [comment]
> I believe the main proposal here (the one that **does not touch** the case where 1 constructor is still valid with `--erased-matches`) is equivalent to automatically transforming `funcname other-patterns absurd-patterns` to `funcname other-patterns erased-irr-arg = ⊥-elim-erased-irr (case erased-irr-arg of λ{absurd-patterns})` during elaboration to case trees. Since this transformation could be done purely syntactically without touching the core language, that should guarantee it is safe.

When Agda reduces expressions at compile-time the `@0` annotations are basically ignored, and your transformation would affect such reductions. I think it could make more expressions definitionally equal.

Perhaps it would make sense to not only allow the code, but also implement the transformation. However, I suspect that this problem is not very common, so I'm reluctant to implement support for it, and in the process make Agda more complicated.

**Comment by Jesin** [comment]
Hmm, ok. It's not too difficult to work around it manually, so if it would substantially increase implementation complexity I suppose it's fine to not support this. I am curious how it could possibly introduce definitional equality between terms that are not already definitionally equal, though.

**Comment by nad** [comment]
Take two distinct terms that are both stuck if the transformation is not applied, `f x` and `g x`. If the transformation is applied, then these terms might reduce to equal terms.
