### ISSUE TITLE
Code only reachable from display forms not serialised in Agda 2.7.0                                 

### ISSUE THREAD

**Issue by mechvel** [agda/agda#7436]
This is on  Agda 2.7.0,  MAlonzo, on Debian Linux 12                            
installed by                                                                    
 $ cabal install -foptimise-heavily -j1,                                        
                                                                                
lib-2.1                                                                         
                                                                                
All the application modules are type-checked by type-checking CheckAll.agda.    
CheckAll.agda  consists of many lines of kind                                   
  open import Foo                                                               
And there is only one module in this list that applies the `main' function:                  
  Pol.Univariate.KTest.                                                         
It is the example that uses other modules and needs to be compiled to executable.                                                                     
                                                                                
Type checking:                                                                  
 $ agda $agdaLibOpt $agdaFlags  CheckAll.agda  +RTS -M12G                       
 where                                                                          
 $agdaFlags = "--auto-inline --guardedness"                                     
                                                                                
Compilation to executable example:                                              
 $ agda -c $agdaLibOpt $agdaFlags Pol/Univariate/KTest.agda +RTS -M12G          
                                                                                
It reports                                                                      
"                                                                               
An internal error has occurred. Please report this as a bug.                    
Location of the error: __IMPOSSIBLE_VERBOSE__, called at src/full/Agda/         
TypeChecking/Monad/Signature.hs:869:32 in                                       
Agda-2.7.0-5b1c26af24f71478be7921bfd690317a6888da853b10d78f399aa31cab72a91e:    
Agda.TypeChecking.Monad.Signature                                               
"       

Call the above approach (I).                                                            
a) In a strange way, this error does not appear for other executable examples set instead of  Pol/Univariate/KTest.agda.                                    
b) I also recall (not very surely) that  Agda 2.6.4.3  is free of this effect.   
c) There was some explanation about the effect, may be about year ago, which I did not understand.                                                         
                        
Anyway, I apply the following approach instead.                                 
                                                                                
Approach (II)                                                                   
-------------                                                                   
(1) Start with only *.agda files of application.                                
   Comment out in CheckAll.agda all the lines for the modules that have `main' . 
   This is only to remember the list of examples to be compiled separately.           
(2) Type-check  CheckAll.agda.                                                  
(3) Choose the needed example  Foo.agda  among the commented out lines and      
    command                                                                     
    $ agda -c ... Foo.agda                                                      
(4) Process other examples in this way by repeating (3)  (without type-checking CheckAll.agda).                                      
                                                                                
This compiles the examples correctly.                                           
                                                                                
I write this because users will be frightened by this "internal error"  message and will doubt of how to organize usage of their applications  when such have examples to be compiled to executables.                          
I wonder of whether it is possible to fix Agda in such a way that the above effect would not appear at all.

**Comment by andreasabel** [comment]
So the error would be here: https://github.com/agda/agda/blob/df1a26d96683ebb06aa8476e4af6bbeddf23efbe/src/full/Agda/TypeChecking/Monad/Signature.hs#L866-L869
With option `-v impossible:100` you can get a bit more information about the crash reason, but only if Agda was compiled with cabal flag `-f debug`.

To reproduce the error, we need more context, e.g. the repo that contains `Pol/Univariate/KTest.agda`.

Did you get the error with any of the Agda 2.7.0 release candidates?

**Comment by mechvel** [comment]
> Did you get the error with any of the Agda 2.7.0 release candidates?

Yes, with all candidates. For RC1 and RC2 I reported this, but not to the bug tracker.
And now I recall that a correct place is the bug tracker.

> you can get a bit more information about the crash reason, but only if Agda
> was compiled with cabal flag -f debug.

I did this as
 $ cabal install -foptimise-heavily -j1 -f debug

 $ agda -V
reports
 Agda version 2.7.0
 Built with flags (cabal -f)   - optimise-heavily: extra optimisations
    - debug: enable debug printing ('-v' verbosity flags)

Type-checking
 $agda $agdaLibOpt $agdaFlags -v impossible:100     CheckAll.agda  +RTS -M12G
produces the same effect as earlier.
Compiling example 
 $ agda -c $agdaLibOpt $agdaFlags -v impossible:100 Pol/Univariate/KTest.agda  +RTS -M12G
reports only this: 
"
Unbound name: Pol.Univariate.KTest._.Pre-DCR.MonOverDecSetoid.mkMon[0,2,4,564,1\
0536,11154,11286]@ModuleNameHash 8367522181124982759
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE_VERBOSE__, called at src/full/Agda/TypeChec\
king/Monad/Signature.hs:869:32 in Agda-2.7.0-545f13ff179fe6e71283f53a5641d0a1ac\
f07155c4e4df6511b314415cd174bf:Agda.TypeChecking.Monad.Signature
"
This relates to the definition
```
 record Mon : Set α where constructor mkMon
      field 
        coef : C
	exp  : PowerProduct
```
given in  Pol/Univariate/Monomial/OverDecSetoid.

This error happens when CheckAll.agda is type-checked together with Pol/Univariate/KTest.agda, 
and then  Pol/Univariate/KTest.agda  is tried to compile separately by another command.

And it compiles correctly when  Pol/Univariate/KTest  is initially removed from CheckAll.agda.


> To reproduce the error, we need more context, e.g. the repo that contains
> Pol/Univariate/KTest.agda.

Do you mean to upload to this place of GitHub the source archive of the whole test application? 
or to provide a link on Web to this archive?

It is very large, somewhat 30.000 lines of the source code,
KTest.agda depends on many modules in the application.
Evidently the example can be reduced greatly, may be to 1000 lines.
But I doubt about doing this reduction right now. This will take much of time.
Are you ready to deal with these 30.000 lines?

**Comment by mechvel** [comment]
The code has two places with the words `postulate` and  `anything` , they are set in order to reduce the set of the used modules. This does not effect the performance of KTest, and probably this  preserves the validity of the bug report.

**Comment by andreasabel** [comment]
> or to provide a link on Web to this archive?

Yes, this would be sufficient!

**Comment by mechvel** [comment]
I am preparing a bit reduced example. 

Meanwhile may be the following notice can help you.
1) In the Approach I, the error message appears within 20 seconds after the compilation command,
   and the MAlonzo folder does not appear at all.
2) In the Approach II, the compilation command for KTest.agda compiles many modules during more than 30 minutes,    
and it appears MAlonzo/  with many files in it, and then a correct executable is set.

**Comment by mechvel** [comment]
As soon as you find the source of this bug,  please inform me, 
in order to save my effort in preparing the example archive.

**Comment by andreasabel** [comment]
> As soon as you find the source of this bug, please inform me, in order to save my effort in preparing the example archive.

It is unlikely that we stumble over this bug without your reproducer.
But as I said, it is fine _for a start_ to just make available your Agda code where this happens (without shrinking).

**Comment by mechvel** [comment]
Please, take the example code from 
  http://www.botik.ru/pub/local/Mechveliani/agdaBug-aug2024.zip

First read the instruction and explanations in  Readme.lagda
(they have changed, a bit).
The example is reduced, 2-3 times
(without this reduction the compilation could last 1 hour).

**Comment by andreasabel** [comment]
Thanks for providing the reproducer, @mechvel.
This problem seems independent of `--save-metas`.
I'd suspect this is another instance of the new deadcode elimination procedure.
@AndrasKovacs : Could you have a look?

P.S.: One can use this `.agda-lib` file to pass the flags:
```
include: .
depend: standard-library-2.1
flags:
  --auto-inline
  --guardedness
```

**Comment by AndrasKovacs** [comment]
I'll look.

**Comment by mechvel** [comment]
include: .
Andreas wrote
> ... 
> depend: standard-library-2.1
> flags:
> ...

Currently I have 
$agdaLibOpt = /home/mechvel/agda/stLib/2.1.1-rc2/src/

So I set  in  ~/.agda-lib  
this:
```
include: .
depend:  /home/mechvel/agda/stLib/2.1.1-rc2/src
 flags:
  --auto-inline
  --guardedness
```

Then, $ agda Nat/FactorizationTest.agda 
reports 
```
Library '/home/mechvel/agda/stLib/2.1.1-rc2/src' not found.
Add the path to its .agda-lib file to
  '/home/mechvel/.config/agda/libraries'
to install.
Installed libraries:   (none)
```
Please, what is wrong?
Currently I need to set the values $agdaLibOpt, $agdaFlags in a certain one file, and write about this in install.txt for users.
And now the user has to create  ~/.agda-lib  and also to create a certain other file in ~/.config/
I also wonder of whether this  relates to the command 'cabal install' when installing the library.
It looks like both approaches are equally complicated (because the first needs to write a longer command each time).
I do understand the old one and I am not sure that I understand the new one.
Can you please, explain?

**Comment by andreasabel** [comment]
@mechvel wrote:
> depend:  /home/mechvel/agda/stLib/2.1.1-rc2/src

`depend` does not list include paths, but `name`s of libraries that are registered in the `/home/mechvel/.config/agda/libraries` file.  This file is a list of paths to `.agda-lib` files which define the libraries.
See also: https://agda.readthedocs.io/en/v2.7.0/tools/package-system.html

> And now the user has to create ~/.agda-lib

Does not have to but its is more convenient, imo.

**Comment by AndrasKovacs** [comment]
@mechvel I was able to compile your PolTest on PR  #7444.

**Comment by mechvel** [comment]
> @mechvel I was able to compile your PolTest on PR https://github.com/agda/agda/pull/7444.

Thank you.
Probably users (I) need somewhat  announced Agda-2.7.1-rc1.zip  to test it.
?

**Comment by AndrasKovacs** [comment]
@andreasabel to be precise, it's not that display forms were not serialized, it's that some of them were not traversed for reachability.

**Comment by mechvel** [comment]
[AndrasKovacs] wrote
> @mechvel I was able to compile your PolTest on PR https://github.com/agda/agda/pull/7444.

For any occasion:
the error effect depends on the order of type-checking and compiling commands.
(1) agda -c ... PolTest.agda
type-checks and compiles.
(2)   agda  ... PolTest;      agda -c ... PolTest.agda 
-- two commands. This also must work. For large applications it is better to do these two commands.
(3) agda ... CheckAll;  agda -c ... PolTest.agda
-- the first command  type-checks everything including PolTest, the second command compiles PolTest.
Naturally, this pair of commands is used in installing large applications.
At least (1),(2),(3) must work.

**Comment by mechvel** [comment]
Correction: there are two places in the above message in which  `.agda` needs to be suffixed
(I could not edit the message because the "Edit" command of GitHub failed).

**Comment by AndrasKovacs** [comment]
@mechvel (1) and (2) both worked for me, I haven't tried (3) but it should be the same as (2).

**Comment by andreasabel** [comment]
I shrank away @mechvel's library, so only two files remain with a dependency on the standard library:

`Import.agda`
```agda
module Import (_ : Set1) where

open import Level using (0ℓ)
open import Algebra using (Magma)
import Algebra.Properties.Magma.Divisibility as MD

postulate
  m : Magma 0ℓ 0ℓ

module N = MD m
```

`Test.agda`
```agda
{-# OPTIONS --no-main #-}

module Test where

open import Import Set
```

Trigger:
```
$ agda Test.agda && agda Test.agda -c -v impossible:10
Checking Test (...).
Unbound name: Test._.N._,_[0,2,6,10]@ModuleNameHash 10189251152579365012
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE_VERBOSE__, called at src/full/Agda/TypeChecking/Monad/Signature.hs:891:32
```

**Comment by AndrasKovacs** [comment]
Wow, thanks a lot! I'll look at this more closely.

**Comment by andreasabel** [comment]
I also cut the standard lib now:

`Base.agda`:
```agda
module Base where

record R : Set where
  constructor cons
```

`Import.agda`:
```agda
module Import (_ : Set1) where

open import Base public using (cons)
```

`Test.agda` (as before):
```agda
{-# OPTIONS --no-main #-}

module Test where

open import Import Set
```

Trigger (as before): `agda Test.agda && agda Test.agda -c -v impossible:10`

Total time spend on shrinking:  Around 3.5 hours.
