### ISSUE TITLE
[bug?] `WARNING_ON_USAGE` in parameterised module/record fails to fire after module instantiation

### ISSUE THREAD

**Issue by jamesmckinna** [agda/agda#7472]
Typechecks under v2.6.4.3 and v2.7.0:
```agda
module MWE where

open import Agda.Builtin.Unit using (⊤)

module M (A : Set) where

  record R : Set where
    field
      new : A
    old : A
    old = new
    {-# WARNING_ON_USAGE old
      "Warning: old was deprecated.
      Please use new instead. "
    #-}

open M ⊤

testM : R → ⊤
testM r = old where open R r
```
(Similarly, exchanging `new` and `old`... so the problem is agnostic as to the distinction declared/defined `field` names)

This a very common pattern in `agda-stdlib`, but the failure to trigger the `WARNING_ON_USAGE` is definitely a UX problem!

**Comment by andreasabel** [comment]
Previous/all reports of this issue in this list: https://github.com/agda/agda/issues?q=sort%3Aupdated-desc+is%3Aopen+label%3Awarning-on-usage
Unfortunately no one picked it up...

**Comment by jamesmckinna** [comment]
Ah! But still: sigh...
Conclusion: `status:duplicate` of #5617
