### ISSUE TITLE
Add coercions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#750]
I’d like to have coercions in Agda. I don’t know much about coercions apart from what is implemented in Coq (see http://coq.inria.fr/refman/Reference-Manual023.html).

As far as I understand, there are basically three types of coercions:

- Sort coercions, you have a family of types [D params], a term [coerce] of 
type [forall params -> D params -> Set i], and you have declared [coerce] to be 
a coercion from [D] to [Sortclass] (in Coq terminology)
Now if you have [A : D params], you can write [x : A] and this is automatically 
translated to [x : coerce params A]

- Function coercions, you have a family of types [D params], a term [coerce] of 
type [forall params -> D params -> (A -> B)], and you have declared [coerce] to 
be a coercion from [D] to [Funclass] (in Coq terminology)
Now if you have [f : D params] and [x : A], you can write [f x] and this is 
automatically translated to [(coerce params f) x]

- Other coercions, you have two families of types [D params] and [E params'], a 
term [coerce] of type [forall params -> D params -> E params'], and you have 
declared [coerce] to be a coercion from [D] to [E]
Now if you have [x : D params] and you need something of type [E params'], you 
can just write [x] and this is automatically translated to [coerce params x]
```

Original issue reported on code.google.com by `guillaum...@gmail.com` on 6 Nov 2012 at 4:53

**Comment by UlfNorell** [comment]
I strongly suspect adding coercions would completely wreck constraint solving. Coq isn't as picky about unique solutions and can get away with more clever heuristics.

**Comment by jespercockx** [comment]
Funny, I was just discussing coercions with the Coq people here in Nantes as a possible way to implement cumulativity. It seems to me that we could get away with having some coercions if we would distinguish more carefully in the typechecker when we expect the type to match exactly and when any supertype will do (for example, by adopting a more bidirectional approach). 

Do you have any hard evidence that this would destroy Agda's constraint solver irredeemably, or is it just a suspicion?

**Comment by UlfNorell** [comment]
No hard evidence, no. But let's do a little exploratory example:

```agda
postulate
  A B : Set

postulate
  coerce : A → B

id : (A : Set) → A → A
id x = x

foo : A → B
foo x = let X = _ in id X x
```
Now what's the value of `X`? Doesn't matter? What if there are be other constraints on `X`?

As an aside, I suppose we already have a limited form of coercions for overloaded literals. That case is a lot simpler though, since coercions are triggered by syntax.

**Comment by andreasabel** [comment]
Well, just arbitrary coercions wouldn't work.  I guess we would have similar restrictions as for instances, that the types you coerce between must be named types.
