### ISSUE TITLE
2.7.0.1 missed on `https://wiki.portal.chalmers.se/agda/pmwiki.php`

### ISSUE THREAD

**Issue by mechvel** [agda/agda#7506]
The page  `https://wiki.portal.chalmers.se/agda/pmwiki.php`
suggests the version 
Agda 2.7.0,
but misses 2.7.0.1.

**Comment by andreasabel** [comment]
Thanks, fixed now.
(I had only put it on https://wiki.portal.chalmers.se/agda/Main/Download).
