### ISSUE TITLE
Broken CI/haskell installation on GitHub?

### ISSUE THREAD

**Issue by jamesmckinna** [agda/agda#7507]
Two failed attempts to merge [PR #2479](https://github.com/agda/agda-stdlib/pull/2479), most recently [this one](https://github.com/agda/agda-stdlib/actions/runs/11030950764/job/30636656269), on `agda-stdlib/master` seem to founder on failed attempts to build `alex` and `happy`, even before the pre-merge-commit tests run...

... could someone who knows more about this than the core `stdlib` maintenance team please take a look?

**Comment by andreasabel** [comment]
@jamesmckinna That's interesting, thanks for the alert!
https://github.com/agda/agda-stdlib/actions/runs/11030950764/job/30636656269#step:6:37
> /home/runner/.cabal/lib/x86_64-linux-ghc-9.8.2/happy-lib-2.0.2-EgcIv144oLmqXufj3QhQk/Happy/Backend/LALR.hi
> Declaration for lalrBackendDataDir
> Unfolding of lalrBackendDataDir:
>   getDataDir1 ErrorWithoutFlag
>                 Something is amiss; requested module  happy-lib-2.0.2-EgcIv144oLmqXufj3QhQk-backend-lalr:Paths_happy_lib differs from name found in the interface file happy-lib-2.0.2-EgcIv144oLmqXufj3QhQk-backend-glr:Paths_happy_lib (if these names look the same, try again with -dppr-debug)
>
> error: Cannot continue after interface file error

Very recently, happy-2.0 was released, and this seems to be one more of its infancy issues (there was already two patches, 2.0.1 and 2.0.2).

I reported this upstream for now:
- https://github.com/haskell/happy/issues/315

We need to either work around this problem or find the cause.

**Comment by andreasabel** [comment]
This can hopefully be worked around in the CI of the agda-stdlib:
- https://github.com/agda/agda-stdlib/pull/2484
