### ISSUE TITLE
Non-unifiable terms defined by pattern matching are not detected as such

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#751]
```agda
module Test where

data ℕ : Set where
  O : ℕ
  S : ℕ → ℕ

prop : (n : ℕ) → (Set → Set)
prop O A = A
prop (S n) A = A

postulate
  B : Set
  B-prop : {n : ℕ} → prop n B

x : (P : Set → Set) (A : Set) → P A
x P A = B-prop
```

This code shouldn’t compile at all but it only gives an unsolved meta at the last line, the unsolved constraint being
```
(prop (_n_7 P A) B) =< (P A) : Set
```
If I define [prop] without pattern matching I do get an error as expected
```
B !=< P A of type Set
when checking that the expression B-prop has type P A
```
Would it make sense to try to solve the constraint by trying both constructors for _n_7 and noticing that none of them fits?

(the actual code is using instance arguments and Agda complains that there are 
several candidates because the [B-prop] is not rejected)

Original issue reported on code.google.com by `guillaum...@gmail.com` on 6 Nov 2012 at 9:55

**Comment by andreasabel** [comment]
One could imagine to write a procedure that tries to lead constraints to inconsistency with all kinds of heuristics, like case splitting etc.  But nothing has happened here for 5 years and no concrete proposal has been discussed. I close this one.
