### ISSUE TITLE
`quote Set` is accepted since 2.6.2, but `quote Set1` is still rejected

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#7514]
Consider:
```agda
_ = quote Set
```
Until 2.6.1, this is an error:
```
quote: not a defined name
when checking that the expression quote Set has type Name
```
When in 2.6.2, `Set` became a `A.Def`, `quote Set` got accepted, but `quote Set1` is still an error, because it is a `A.Def'` with a suffix. Note: `A.Def` is since 2.6.2 a synonym for `A.Def' NoSuffix`.  (CC: @jespercockx )

Exactly the suffix-free universes are accepted atm:
```agda
_ = quote Prop
_ = quote Propω
_ = quote Set
_ = quote Setω
_ = quote SSet
_ = quote SSetω
_ = quote LevelUniv
_ = quote IUniv
_ = quote SizeUniv
```

So what is actually the intention?  Accept universes in `quote` (then maybe all of them, not just the suffix-free ones), or reject them?
ATTN: @plt-amy @UlfNorell

**Comment by UlfNorell** [comment]
The suffixed ones don't have corresponding `QName`s so can't be quoted without changing the reflected representation of names, which does not seem warranted just to allow quoting them. I guess we could disallow quoting the others, but I don't really see why. It's not hard to explain that `Set₁` is short-hand for `Set (lsuc lzero)` and thus isn't `quote`able.

**Comment by plt-amy** [comment]
It's a bit strange to allow quoting `Set` as a name since we also have `agda-sort (set ...)`, IMO

**Comment by UlfNorell** [comment]
I don't really see that it's worth the effort to figure out which names refer to universes just to forbid quoting them.

Currently we don't allow reflection to manipulate scope, but if we ever wanted to add that we'd need to allow referring to the names of the non-suffixed universes. For instance:

```agda
open import Agda.Primitive renaming (Set  to Foo) -- ok
open import Agda.Primitive renaming (Set₁ to Foo) -- fails
```
