### ISSUE TITLE
`quote x` is accepted for a generalized `variable x`, but rejected for a bound variable

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#7515]
`quote A` is accepted for a generalized `variable A`, but rejected for a bound variable:
```agda
open import Agda.Builtin.Reflection

variable
  A : Set

postulate
  P : Name → Set

-- This should probably be rejected:

test : P (quote A) → Set₁
test x = Set

-- Because this fails:

fails : {A : Set} → P (quote A) → Set₁
fails x = Set

-- `quote' expects an unambiguous defined name,
-- but here the argument is a variable: A
-- when checking that the expression quote A has type Name
```
ATTN: @UlfNorell

**Comment by UlfNorell** [comment]
I don't understand the reasoning. Generalized variables are not the same as bound variables and quoting them could make sense. Are you claiming there could never be any use for building types with generalized variables using reflection?

**Comment by andreasabel** [comment]
The reasoning is that Agda elaborates `test` to `fails` so they should behave the same.
Otherwise, I don't know what elaboration actually is.

**Comment by UlfNorell** [comment]
That's not what elaboration does. How could it since `quote A` doesn't make sense for a bound variable?

Elaboration of generalization works on internal syntax, not abstract syntax, and is perfectly happy to leave the quoted name in there. The point where this could be useful is if you are passing the name to a macro, since that will get elaborated before generalization.

**Comment by andreasabel** [comment]
Well, this means that generalization is not syntactic sugar, but _something else_.  Probably few have a mental model for what that something else is.  

At least I thought that generalization isn't a language extension, but just sugar I can expand away manually with some boring boilerplate work.
That is, I can manually perform a _syntactic translation_ (even though we implement it as a transformation on our internal representation).

If this is a feature we want to keep, we should have an application of this feature somewhere in our testsuite.  That would be the first step towards a spec of this feature.

**Comment by UlfNorell** [comment]
Which part is it that's unclear? How generalization interacts with reflection?

Here's an extremely silly example if you want one for the test suite:

```agda
open import Agda.Builtin.Reflection
open import Agda.Builtin.Unit
open import Agda.Builtin.List

variable
  A B : Set

vArg : Term → Arg Term
vArg = arg (arg-info visible (modality relevant quantity-ω))

fun : List Name → Term
fun [] = def (quote ⊤) []
fun (x ∷ []) = def x []
fun (x ∷ xs) = pi (vArg (def x [])) (abs "_" (fun xs))

macro
  fn : List Name → Term → TC ⊤
  fn xs hole = unify (fun xs) hole

foldr : fn (quote A ∷ quote B ∷ quote B ∷ []) → fn (quote B ∷ []) → List A → B
foldr f z []       = z
foldr f z (x ∷ xs) = f x (foldr f z xs)
```

**Comment by andreasabel** [comment]
If I understand your example correctly, then it defines a function `foldr` that works for two specific uninterpreted types `quote A` and `quote B`.  In particular, it is not polymorphic and it could as well be defined for `postulate A B : Set` (instead of `variable`).
Maybe I do not understand this example correctly, but how does this argue for the feature?  What is the advantage over postulated `A` and `B`?

**Comment by UlfNorell** [comment]
The type is `foldr : {A B : Set} → (A → B → B) → B → List A → B`. As I said above, macros are elaborated before generalization.

**Comment by UlfNorell** [comment]
Also you need to check your mental model here. Were you really expecting `variable A B : Set` to introduce two new uninterpreted types? What if I had said `variable oops : ⊥`?

**Comment by andreasabel** [comment]
> Also you need to check your mental model here. Were you really expecting `variable A B : Set` to introduce two new uninterpreted types? What if I had said `variable oops : ⊥`?

Introduce, well, not really into the main Agda universe, but into `Term`.

Ok, so if `quote A` goes away by unquoting before generalization, then it could be useful (although the example does not present a killer app yet).  

My mental model of reflection is likely underdeveloped.

**Comment by UlfNorell** [comment]
It wasn't meant as a killer app. We're not talking about adding a new feature that needs strong motivation, but simply not removing an existing feature. I think the example demonstrates that it's something that makes sense and thus shouldn't be removed arbitrarily.

**Comment by andreasabel** [comment]
Ok, I added the test.
