### ISSUE TITLE
`DISPLAY` pragmas should treat any defined name as matchable

### ISSUE THREAD

**Issue by jamesmckinna** [agda/agda#7533]
Agda version v2.7.0 (also v2.6.4.3, it seems)
stdlib version: `master` branch

Interactive attempt to check the following MWE causes a weird error, which I don't even know how to localise as to cause (failure in the `variable` generalisation mechanism? in the `DISPLAY` pragma?):
```agda
module IrrelevantBug where

open import Level
open import Data.Empty using (⊥)
open import Data.Irrelevant
open import Relation.Nullary.Recomputable

private
  variable
    a : Level
    A : Set a

recompute-irrelevant : Recomputable (Irrelevant A)
recompute-irrelevant p = {!p!}
```

Emacs interaction, instead of printing `?0 : Irrelevant A` prints `?0 : ⊥`?

NB 
* if quantification is explicit, rather than generalisation via the above `private` variables, then interaction is as expected.
* similarly, if the `import` of `Data.Empty` is excluded, and with it the `{-# DISPLAY Irrelevant Empty = ⊥ #-}` pragma, then again the example is OK.

Any ideas how to avoid this? `Data.Empty` has been stable in the stdlib for a while now, so it seems to be only the interaction with the explicit import of `Data.Irrelevant`/`Relation.Nullary.Recomputable` (or: irrelevance annotaions?) causing the bug?

**Comment by szumixie** [comment]
> if quantification is explicit, rather than generalisation via the above private variables, then interaction is as expected.

I can reproduce the problem without generalized variables.

The `DISPLAY` pragma only matches on data constructors in the left hand side arguments, not type constructors (see #2004).

So in the pragma `{-# DISPLAY Irrelevant Empty = ⊥ #-}`, `Empty` is a new pattern variable, and `Irrelevant` applied to any argument gets rewritten to `⊥`.

Minimized example:
```agda
data Empty : Set where

postulate
  F : Set → Set
  X : Set
  A : Set

{-# DISPLAY F Empty = X #-}

_ : F A
_ = {!!} -- ?0 : X
```

**Comment by jamesmckinna** [comment]
Oh!? Wow...

**Comment by jamesmckinna** [comment]
Oh!? Wow... thanks for the pointer back to #2004 . 

Accordingly, I think I'll close this issue now, and re-raise an issue for `stdlib` as to how to deal with our current (clearly broken!) approach to `DISPLAY`ing `⊥`... sigh.

**Comment by andreasabel** [comment]
This is indeed a duplicate of
- #2004 

DISPLAY pragmas are still a prototypical feature and have not matured much since their introduction. 
Maybe some REWRITE technology could be transferred to make DISPLAY better behaved.

**Comment by andreasabel** [comment]
> So in the pragma `{-# DISPLAY Irrelevant Empty = ⊥ #-}`, `Empty` is a new pattern variable, and `Irrelevant` applied to any argument gets rewritten to `⊥`.

The least that Agda should do here is to warn about unused pattern variables, i.e., variables bound on the lhs that are not used on the rhs.

Rededicating this issue...

**Comment by andreasabel** [comment]
We seem to have an invalid DISPLAY pragma in our code base ourselves: https://github.com/agda/agda/commit/b290d0bce9b042d01841c7d9b9a485b04627a0be#r147631053
https://github.com/agda/agda/blob/1e9725ee8a334de816fff39ce1bd32f91b6714e4/src/data/lib/prim/Agda/Builtin/TrustMe.agda#L15
And the documentation sounds misleading: https://github.com/agda/agda/blob/1e9725ee8a334de816fff39ce1bd32f91b6714e4/doc/user-manual/language/pragmas.lagda.rst?plain=1#L98-L100
