### ISSUE TITLE
No highlighting for syntax declarations

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#758]
```agda
data ℕ : Set where
  O : ℕ
  S : ℕ → ℕ

pattern one = S O
```
Neither lhs nor rhs of the pattern declaration are highlighted.  (Should be colored with constructor color.)

Original issue reported on code.google.com by `andreas....@gmail.com` on 17 Nov 2012 at 11:57

**Comment by andreasabel** [comment]
Patches: 279e65fe0437cfbbedcc61249ecfeeb933aa6f1e and 6f3e3a66627630997be53c748e9fbde731b10b8e

**Comment by andreasabel** [comment]
Current status (2017-07-28):
```agda
data ℕ : Set where
  O : ℕ
  S : ℕ → ℕ

syntax S x = suc x

test = suc O
```
In the `syntax` declaration, `suc` is not highlighted.  In `test`, it is highlighted with constructor color.
I think the syntax should inherit the color of what it stands for.

**Comment by UlfNorell** [comment]
This shouldn't be terribly hard to fix. We'd need to add ranges to `GenPart`s in `Agda.Syntax.Notation` and dig them out when generating highlighting.

**Comment by jespercockx** [comment]
@UlfNorell since you seem to have an idea what to do here, can you take a look at it before the release? (or else bump the milestone)

**Comment by UlfNorell** [comment]
Will do
