### ISSUE TITLE
Canonical types defined as functions into universe (feature request)

### ISSUE THREAD

**Issue by cmcmA20** [agda/agda#7582]
## Problem
There's a tension between two desires: to have seamlessly composable code gadgets and to have proper abstraction barriers.

Postulating a new name is a form of human communication, names usually signal that the denoted concepts are important in some way. Specifying computational behaviour of these things is a completely unrelated activity. Currently Agda presents you with three principal options for animating a named thing in a universe:
- type is canonical, no values (`postulate`)
- type is canonical, values compute as prescribed by a least/greatest fixpoint of an implicitly defined functor (`data` / `record`)
- type is not canonical, it computes like a function into universe, values compute accordingly

Transparent functions into universe create unpleasant goals and hide interesting structure in a soup of lower-level primitives. Opaque functions into universe restrict computation for both name _and_ its' values.

## Solution
We should also have the ability to create canonical types with values that compute according to a function definition. These **canonical type aliases** don't explode under reduction in goals and don't force you to have a ton of `opaque` blocks.

Authors of Narya [express this idea](https://github.com/mikeshulman/narya?tab=readme-ov-file#canonical-types-defined-by-case-trees) as
>This sort of "recursively defined canonical type" helps maintain information about the meaning of a type, just like using a custom record type rather than a nested Σ-type; eventually we hope it will be helpful for unification and typeclass inference.

### Parameterized `data` types
Antimodularity at its finest. Usually we stick to inductive definitions with nice names like `List` and prove (by pattern matching) a myriad of trivial lemmas about functoriality etc. Compositional framework of polynomial functors or descriptions solves trivial stuff once and for all, but sigma pie is a bit too messy in goals. `pattern` synonyms are a band-aid, the wound shouldn't be inflicted in the first place.

### Subcategories
All kinds of subcategories (vanilla, full, wide) deserve to have distinct names but may also benefit from computing as a total category for some displayed category.

### h-levels
Consider [1lab's H-Level definition](https://1lab.dev/1Lab.HLevel.Closure.html#10455). Having a wrapper record with a hierarchy of instances duplicating the corresponding theorems is a direct consequence of the current state of affairs. Making `is-hlevel` opaque would not help as opaque definitions are transparent for instance resolution.

### Vectors
```
Vec : Type ℓ → (n : ℕ) → Type ℓ
Vec _ 0       = ⊤
Vec A (suc n) = A × Vec A n
```
Reduction to product frequently breaks argument inference and instance resolution , `map`/`fold` usability is unnecessarily lacking in comparison to inductive `Vec`.

## Notes on implementation
IIUC constructor type should never be inferred so we don't lose anything when checking constructor against an alias type. If `opaque` infrastructure can be reused, most (all?) of this feature can also be done with minimal effort inside the elaborator.

**Comment by UlfNorell** [comment]
Can you give some more fleshed out concrete examples of what you are suggesting. For instance, I don't understand how properties get lifted from the underlying type if all we do in the implementation is changing type checking of constructors.

**Comment by nad** [comment]
> Making `is-hlevel` opaque would not help as opaque definitions are transparent for instance resolution.

Some of us discussed something similar in a recent meeting: should opaque definitions be treated as transparent by the positivity checker? I think most agreed that opaque definitions should be opaque. If that is not the case when it comes to instance resolution, then I think we should fix that. I suggest that you open a separate issue for this.

**Comment by cmcmA20** [comment]
`data` example mentioned above boils down to a generative type abstraction like Haskell `newtype`.
```agda
canonical -- imaginary syntax
  List : {ℓ : Level} → Type ℓ → Type ℓ
  List = ⟦ Nat ▶ Fin ⟧

cons : A → List A → List A
cons x xs = {!  !}
```
After normalization goal looks like `Σ ℕ (λ n → Fin n → A)` in current Agda. With new feature enabled, `List A` shouldn't reduce anymore (just like if it was defined with `data`), but we should be still able to fill the hole with any term of type `Σ ℕ (λ n → Fin n → A)`.

Let me use more simple nonrecursive [example](https://www.seas.upenn.edu/~sweirich/papers/popl163af-weirich.pdf)
```agda
canonical
  Age : Type
  Age = Nat

_ : Age ≡ Nat
_ = {! refl !} -- should fail with Age != Nat error

_ : Age
_ = 4 + 4 -- OK, term of type Nat checks at Age

coerceNatToAge : Nat → Age
coerceNatToAge n = n -- OK, term of type Nat checks at Age

```



Sorry, changing type checking of constructors is probably not enough, we should be able to silently coerce term `t : T` to any alias of `T`. Other direction seems less clear to me, we can either do a silent coercion or something like

```agda
opaque
  unfolding Age
  coerceAgeToNat : Age → Nat
  coerceAgeToNat a = a -- OK, Age reduces to Nat inside this block
```

So it should be possible to prove that type and its' alias are isomorphic, but not definitionally equal.

**Comment by cmcmA20** [comment]
@nad Sorry, I'm not really sure if it needs a fix, current way works fine IMO.

As for properly recursive examples
```agda
is-hlevel : ∀ {ℓ} → Type ℓ → Nat → Type _
is-hlevel A 0       = is-contr A
is-hlevel A 1       = is-prop A
is-hlevel A (suc n) = (x y : A) → is-hlevel (Path A x y) n
```
It should be possible to both write instances for this definition (if it's marked as canonical) and apply terms of such a type without having to manually coerce anything.

**Comment by UlfNorell** [comment]
This sounds like a request for full-fledged subtyping, which is problematic in our setting. Having subtyping means you can no longer solve metavariables by unification, you always have to consider whether to solve with a super type of the inferred type. Consider
```agda
a : Age
n : Nat
foo = id {_X} n ... id {_X} a
```
Here we can't solve `_X` with `Nat` when checking the first call to `id`, because that will make the second call to `id` fail. Making this work would (as far as I can see) take a complete reengineering of the constraint solver. I would be interested if you have some examples of how this plays out in Narya.

**Comment by cmcmA20** [comment]
I understand that requiring real subtyping is not an option. Though `foo` example breaks as you say if `Age` is opaque, and works fine when `Age` is unfolded. Shouldn't canonical/alias things behave exactly the same regarding unification?

```agda
opaque
  -- unfolding Age
  foo : Nat
  foo =
    let X = {!!}
        a : Age
        a = id {A = X} {! !}
        n : Nat
        n = id {A = X} {! !}
    in {! !}
```

**Comment by UlfNorell** [comment]
The difference is that you want `n` to check at type `Age`, which isn't the case with `opaque`. The fleshed out example is
```agda
  foo : Age → Nat → Age
  foo a n =
    let X = _
        a₁ = id {A = X} n
        a₂ : Age
        a₂ = id {A = X} a
    in a₁
```
With your feature request this ought to type check, since you can solve `X = Age` and `n : Age` should be valid.

**Comment by jespercockx** [comment]
I don't see how you could implement this feature in terms of `opaque`: an opaque definition is either equal to its body (when inside another opaque block that is `unfolding` it) or not equal to anything (outside of such a block). However, this feature would require a distinction between the definition being used *as a type* and *as a term*.

Perhaps one way to make sense of this feature request is to make a distinction between comparing two *terms* and two *types*. Currently, internally Agda's `compareType` function basically just calls `compareTerm`, but you could imagine a system where `compareType` equates *more* things than `compareTerm`. However, before we consider implementing such a thing I'd first like to see a theoretical development of such a system, in particular a proof of subject reduction. 

Additionally, we'd also need an answer to how this feature should interact with constraint solving. In particular, it would probably require us to internally distinguish between type-level and term-level metavariables (see https://github.com/agda/agda/issues/1432 for the related question of whether we should distinguish *sort*-level metavariables).

Finally, a more practical question is how such types should interact wrt parametrized types. E.g. should you also be able to use a `List Nat` as a `List Age` and vice versa?

**Comment by cmcmA20** [comment]
@UlfNorell 
>The difference is that you want `n` to check at type `Age`, which isn't the case with opaque.

Thank you! I'll have to think some more about this feature.

---------

@jespercockx

I had an impression that if current unfolding control is implementable without using extension types, maybe it can also be updated to accommodate a new use case. Seems like I was mistaken.

> this feature would require a distinction between the definition being used as a type and as a term
> where compareType equates more things than compareTerm

Yes, that's what I'm tinkering with right now.

>Additionally, we'd also need an answer to how this feature should interact with constraint solving
> #1432

Thank you!

>Finally, a more practical question is how such types should interact wrt parametrized types. E.g. should you also be able to use a `List Nat` as a `List Age` and vice versa?

Yes, I thought that `t : F Nat` should be unconditionally usable in any place where `F Age` is expected. Unsure if it should also be vice versa, but probably yes. As you noticed, this feature is about creating more atomic things in universe, affecting anything else is not a goal.

Update:
Taking `F` to be `Nat ≡_` makes `refl : Nat ≡ Nat` typecheck at `Nat ≡ Age`, so the current form of this proposal doesn't make sense, aliasing is basically a no-op.
