### ISSUE TITLE
__IMPOSSIBLE__, called at src/full/Agda/Compiler/JS/Compiler.hs:596:45

### ISSUE THREAD

**Issue by lawcho** [agda/agda#7588]
This Agda code crashes the JS backend:

```agda
data Cell : Set where
  [-] [o] [x] : Cell

data Board : Set where
  mk-Board : Cell → Cell → Board

winner : Board → Cell
winner = λ where
  (mk-Board [x] [x]) → [x]
  (mk-Board  _  [x]) → [x]
  (mk-Board  _   _ ) → [-]

step : Board → Board
step b with winner b  
... | [-] = b
... |  _  = mk-Board [-] [-]
```

Here is a log:

```shellsession
/tmp/tmp.4DeC6lEc31$ agda --js bugreport.agda
Checking bugreport (/tmp/tmp.4DeC6lEc31/bugreport.agda).
Compiling Agda.Primitive in /nix/store/8pqr8xp07v8xd4kj99wpkziq5zd2famd-Agda-2.8.0-data/share/ghc-9.6.5/x86_64-linux-ghc-9.6.5/Agda-2.8.0/lib/prim/_build/2.8.0/agda/Agda/Primitive.agdai to /tmp/tmp.4DeC6lEc31/./jAgda.Agda.Primitive.js
Compiling bugreport in /tmp/tmp.4DeC6lEc31/bugreport.agdai to /tmp/tmp.4DeC6lEc31/./jAgda.bugreport.js
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/Compiler/JS/Compiler.hs:588:45 in Agda-2.8.0-JMDOmoIw0FQAlAv1YIAPME:Agda.Compiler.JS.Compiler
```

I get an `__IMPOSSIBLE__` error on these Agda revisions:

* df1a26d: Agda 2.7.0

The example compiles without errors on these Agda revisions:

* b499d12: Agda 2.6.3
* 3356568: current tip of #7573
* 3425ed5: recent `master`

The error disappears after any of these edits:

* Delete the `[o]` constructor
* Delete the 1nd case of `winner`
* Delete the 2nd case of `winner`
* Replace `λ where` with a top-level pattern match
* Delete the 1st with-clause of `step`
* Replace the 2nd RHS of `step` with `b`

**Comment by szumixie** [comment]
I get an internal error in both 2.7.0 and 2.6.4.3.

**Comment by lawcho** [comment]
Oops, I tried again with 2.7.0 and it does indeed crash.

**Comment by lawcho** [comment]
I tried again with:

* 3425ed5543d2e6f98094b834fedcdec3a2fb67a6: current `master`
* 33565687d1035a76747986bcf6c971d3395dcb83: current tip of #7573

And it does not crash there either.

I think I mixed up the versions when testing, and that the fix is already in `master`.
Apologies for the noise.

**Comment by szumixie** [comment]
> I tried again with:
>
> * 3425ed5543d2e6f98094b834fedcdec3a2fb67a6: current `master`
> * 33565687d1035a76747986bcf6c971d3395dcb83: current tip of #7573

I can reproduce the internal error in both of those commits.

**Comment by szumixie** [comment]
The regression is introduced in 3abef8d4b01b4badf8b1acda989b3c5f044f0e6e (#7122).

**Comment by szumixie** [comment]
Adding `{-# INLINE winner #-}` makes it crash on versions before 2.6.4.2. 3abef8d4b01b4badf8b1acda989b3c5f044f0e6e causes the expression in `with` to be inlined in the compiled code without the pragma, which I'm not sure is intended.
