### ISSUE TITLE
Warning for open public in an abstract block

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#760]
Agda allows the keyword private where it does not have any effect.  For example:
```agda
  private
    open import Common.Prelude
```
This should yield an error, to help the user understand the concept of 'private' better.

Original issue reported on code.google.com by `andreas....@gmail.com` on 17 Nov 2012 at 4:37

**Comment by gallais** [comment]
What should happen in the #759 case with `open Wrap public`?

```agda
module Issue759 where

import Common.Level

abstract
  record Wrap (A : Set) : Set where
    field wrapped : A
  open Wrap public

  wrap : {A : Set} → A → Wrap A
  wrap a = record { wrapped = a }
```

**Comment by nad** [comment]
> What should happen in the #759 case with `open Wrap public`?

This is related to #2715.

One option is to disallow `open Wrap public` inside the `abstract` block. This is a conservative design that can be changed later.

How are definitions inside abstract record modules treated? Are they allowed?

**Comment by gallais** [comment]
> How are definitions inside abstract record modules treated? Are they allowed?

This is the current situation:

```agda
module abstractrecord where

open import Agda.Builtin.Equality

abstract

  record F : Set₁ where
    field A : Set

    B : Set
    B = A

  C : Set₁
  C = F

  D : Set₁
  D = C

{- -- not true because of `abstract`
_ : C ≡ D
_ = refl
-}

-- true despite `abstract`
_ : ∀ f → F.A f ≡ F.B f
_ = λ f → refl
```

**Comment by nad** [comment]
That looks like a bug to me.
