### ISSUE TITLE
Discrepancy in test output for Issue2248_COMPILED_TYPE

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#7637]
With the latest master version of Agda (installed with GHC 9.4.8 and Cabal 3.12.1.0) I get a failure when running `make fail`. Specifically for `test/Fail/Issue2248_COMPILED_TYPE` my local machine complains about a hidden package:
```
 Compilation error:
-«path»/MAlonzo/Code/Issue2248_COMPILED_TYPE.hs:«line»:«col»: error: [GHC-25897]
-    • Couldn't match expected type ‘T_IO_6 xA’ with actual type ‘xA’
-      ‘xA’ is a rigid type variable bound by
-        the type signature for:
-          d_toIO_16 :: forall xA. () -> xA -> T_IO_6 xA
-        at «path»/MAlonzo/Code/Issue2248_COMPILED_TYPE.hs:«line»:«col»-45
-    • In the expression: x
-      In the expression: / _ x -> x
-      In an equation for ‘d_toIO_16’: d_toIO_16 = / _ x -> x
-    • Relevant bindings include
-        x :: xA
-          (bound at «path»/MAlonzo/Code/Issue2248_COMPILED_TYPE.hs:«line»:«col»)
-        d_toIO_16 :: () -> xA -> T_IO_6 xA
-          (bound at «path»/MAlonzo/Code/Issue2248_COMPILED_TYPE.hs:«line»:«col»)
-   |
-37 | d_toIO_16 = / _ x -> x
-   |                      ^
 
+«path»/MAlonzo/Code/Issue2248_COMPILED_TYPE.hs:«line»:«col»: error:
+    Could not load module ‘Data.Text’
+    It is a member of the hidden package ‘text-2.0.2’.
+    You can run ‘:set -package text’ to expose it.
+    (Note: this unloads all the modules in the current scope.)
+    Use -v (or ':set -v' in ghci) to see a list of the files searched for.
+   |
+19 | import qualified Data.Text
+   | ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

On a different machine (of one of my students) the error message is closer but still different, in particular the part `[GHC-25897]` is missing in the error message. I'm not sure if these are different problems or the same, but either way the local setup should not influence the error messages, should it?

**Comment by andreasabel** [comment]
Yes, we have come across some discrepancy in the GHC error format across versions  (CC @digama0 ).
CI uses GHC 9.10 so this is the gold standard.
If your student does not want to see this error when running the testsuite locally, they can
1. either upgrade to GHC 9.10
2. or modify the test runner so it filters out the instable parts of the GHC error message. (PR welcome!)

However, your problem with the hidden package is some problem with the default GHC environment on your installation.  Your default environment does not even publish the GHC-shipped packages (such as `text`).
Have a look at `~/.ghc/<GHC_VERSION>/environments/default`.
I deactivated this file so I do not run into such issues.

**Comment by jespercockx** [comment]
Thanks for the answer.
