### ISSUE TITLE
Better not claim "Level should be a function type"

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#7642]
With standard library:
```agda
import Level
open Level using (Level; 0ℓ)

1ℓ : Level
1ℓ = Level.zero 0ℓ
```
Error is:
```
error: [ShouldBePi]
Level should be a function type, but it isn't
when checking that 0ℓ is a valid argument to a function of type Level
```
One would expect a complaint that `Level.zero` is not a function type...

**Comment by UlfNorell** [comment]
`Level.zero` is not a type at all, so it wouldn't make sense to expect it to be a function type. Of course, we could work on the wording to make it easier to understand, but it is correctly formulated.

**Comment by andreasabel** [comment]
Ah, I was thrown off completely by this error message.  My brain couldn't make sense at all of "Level should be a function type".
If Agda had told me that "`Level.zero` is not a function", I would have understood what the problem is.
We can check the other cases of `ShouldBePi` whether they would also benefit from this reformulation.

**Comment by UlfNorell** [comment]
I think the reason it's formulated like this is that we don't have the term readily available when we throw the error. Some refactoring may be required, but I agree that the error message could be improved a lot.
