### ISSUE TITLE
Agent Smith proves False

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#7658]
https://youtu.be/m-nPQQWIf3c?si=L_2TTLPBIWV187By&t=202
```agda
module _ where

module Oracle where
  data ⊥ : Set where

open import AgentSmith as Oracle

boom : ⊥
boom = _
```

**Comment by jespercockx** [comment]
What's bad about this example? You just used the name `⊥`  for the unit type (and also had an unrelated empty type `Oracle.⊥` in scope).

**Comment by andreasabel** [comment]
I was too quick :-(
```agda
module _ where

module Oracle where
  data ⊥ : Set where

import AgentSmith as Oracle

boom : Oracle.⊥
boom = _
```
> Ambiguous name Oracle.⊥.
