### ISSUE TITLE
Unsolvable constraints should give error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#776]
Take the following example:
```agda
module LeibnizEquality where

open import Level

-- Note Set₁ instead of Set (suc l)
data _:=:_ {l : Level} (A : Set l) (B : Set l) : Set₁ where 
  proof : {F : Set l → Set l} → F A → F B → A :=: B
```
On typechecking, no error is signaled by Emacs and Agda just prints:
```agda
l =< (suc zero)
l =< (suc zero)
(suc l) =< (suc zero)
```
The main bug is that no error is shown by Emacs while no sensible error message 
is reported by Agda. I guess Emacs (or rather, Emacs Agda mode) has no fault, 
it's just that Agda doesn't report the error correctly.

What version of Agda are you using? On what operating system (if relevant)?
Agda 2.3.2 with standard library 0.6 with fixes from development version. This 
is in fact with both Aquamacs and GNU Emacs 22.1.1 (as distributed by Apple) on 
OS X 10.8.

Original issue reported on code.google.com by `p.giarrusso` on 30 Dec 2012 at 9:39

**Comment by andreasabel** [comment]
This issue appears to be fixed.  I am adding the test case.
