### ISSUE TITLE
Agda does not find definition clause in a record if it is a with clause and a field declaration follows

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#779]
``` agda
record R : Set1 where

  Bla : Set1
  Bla with Set
  ... | _ = Set

  field
    F : Set
```

Agda reports: 

```
Missing definition for Bla
```

Original issue reported on code.google.com by `andreas....@gmail.com` on 3 Jan 2013 at 10:01
- Merged into: #434

**Comment by andreasabel** [comment]
Error is now better, pointing out that functions with `with` are illegal before the last `field`.

**Comment by andreasabel** [comment]
Rest of the problem should be handled with #434.
