### ISSUE TITLE
Indicate unsolved meta coming from a missing field in a record

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#781]
Forgetting to implement a field in a record leads to a report of   "Unsolved metas"
For example,
```agda
   record Foo : Set  where field foo1 : Bool
                                                  foo2 : Bool
                                                  foo3 : Bool
  rec = record{ foo1 = true                  -- line No 14
                     ; foo3 = true }
```
yields the report
```
Unsolved metas at the following locations:  .../reports/3/Main.agda:14,7-17,14 
```

In a similar situation, I thought a long of what is wrong about  _+p_  in  ` record {foo1 = _+p_;      ...}`
Finally it has occured that one of the further fields has been forgotten to set.

Suggestion for the type cheker:

It will be more helpful to report in such a case     "Missing implementation for the field  foo2 ...".

Of course, this is not for the case when the type checker _derives_ the values for the skipped fields. 

This is on  Agda-2.3.2 - MAlonzo.

Original issue reported on code.google.com by `mech...@botik.ru` on 14 Jan 2013 at 10:12

**Comment by andreasabel** [comment]
We could keep track when a meta comes from a record field and include this info when printing the unsolved metas.

**Comment by andreasabel** [comment]
```agda
open import Agda.Builtin.Nat

record Foo : Set where
  field
    foo1 : Nat
    foo2 : Nat
    foo3 : Nat

rec = record{ foo1 = 1 ; foo3 = 3 }
```
In emacs, this gives:
```
_foo2_5 : Nat  [ at /.../Issue781.agda:9,7-36 ]
```
The name of the meta indicates it comes from record field `foo2`.

On the command line, we just get:
```
Unsolved metas at the following locations:
  /.../Issue781.agda:9,7-36
```
This info could be improved.

**Comment by andreasabel** [comment]
Maybe a candidate for an AIM bugfix-sprint session.

**Comment by andreasabel** [comment]
Maybe this issue is sufficiently fixed by naming the meta-variable after the record field.

**Comment by asr** [comment]
Since this is issue is 'not planned' I removed the milestone `later`.

**Comment by andreasabel** [comment]
> Since this is issue is 'not planned' I removed the milestone `later`.

@asr: I'd like to have closed issues also on a milestone.  Otherwise there will be a lot of closed issue without milestone to check when searching for closed issues that should go on e.g. `2.6.3` but folks forgot to set the milestone when closing it.  Thus, we have now milestone `never` for things "not planned" (and @nad correctly put it there, thanks!).
