### ISSUE TITLE
Agda-2.3.2 parser misses error in  ``renaming (ε to e; Carrier tofoo)''

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#782]
Agda-2.3.2 - MAlonzo  does not report of missing ` to`  after  `Carrier`  in
```agda
f : {c l : Level} -> (M : Monoid c l) -> Monoid.Carrier M
f M = let open Monoid M renaming (ε to e; Carrier tofoo)  
      in  e
```
(a blanc forgotten in `tofoo').

Original issue reported on code.google.com by `mech...@botik.ru` on 15 Jan 2013 at 3:39

**Comment by andreasabel** [comment]
Fixed in commit e6bd5d702114d0e547365c97db96e5882f743689 .
