### ISSUE TITLE
UnusedArg machinery causes internal error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#784]
1. When I try to type check this file (https://github.com/dima-starosud/Uniqueness-typing-in-Agda/blob/master/RefAPITest.agda) with commented line 9 (type definition for new) I get "An internal error has occurred. Please report this as a bug. Location of the error: src/full/Agda/TypeChecking/Substitute.hs:607"

2. Also when I add main function and try to compile it to executable I got GHC error: possibly incorrect indentation.

Thanks in advance!
Best regards,
Dmytro 

Original issue reported on code.google.com by `d.staro...@gmail.com` on 17 Jan 2013 at 10:07

**Comment by asr** [comment]
Fixed by ab03a3384e97e51b3cbeeda91ef7c39f0e8157c2.
