### ISSUE TITLE
"Refuse to construct infinite term" in an innocent-looking code

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#795]
The code:
```agda
    module test where

    data Q (A : Set) : Set where

    F : (N : Set → Set) → Set₁
    F N = (A : Set) → N (Q A) → N A

    postulate N : Set → Set
    postulate f : F N
    postulate R : (N : Set → Set) → Set
    postulate funny-term : ∀ N → (f : F N) → R N

    qqq : R N
    qqq = funny-term ? (λ A → f ?)
```

The error message:
```
    Refuse to construct infinite term by instantiating _9 to Q (?1 A)
    when checking that the expression f ? has type
    N (?1 (Q A)) → N (?1 A)
```
The error can be fixed in one of the following ways:

    * Change Q to be a postulate instead of a data type
    * Fill the first hole with N.
    * Fill the second hole with A.

I can't explain why any of those changes fix the error or what the error is, 
but it sure looks like a bug to me!

Original issue reported on code.google.com by `rot...@gmail.com` on 18 Feb 2013 at 3:35

**Comment by andreasabel** [comment]
Commits:
-  19b3e30840911ad6d69a63b8f3677a978228e9fd
- d331260a5d4fb157d9099cd936d35d894bdb49df
-  5c21d55d6dab1da47d753297fef4facba9268d6c
