### ISSUE TITLE
No error message for incorrectly placed NO_TERMINATION_CHECK

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#804]
``` agda
module Bug where

mutual

  {-# NO_TERMINATION_CHECK #-}

  Foo : Set
  Foo = Foo

-- The pragma above doesn't apply to Foo. An informative error message
-- could be helpful.

```

Original issue reported on code.google.com by `nils.anders.danielsson` on 28 Feb 2013 at 12:50

**Comment by asr** [comment]
The issue was fixed by b4c5797a6849ec1de4b97713ba42bc0a74626979.

**Comment by asr** [comment]
> Or rather, it should apply to the whole mutual block.

Is there some description of what does Agda consider a mutual block?

**Comment by UlfNorell** [comment]
Yes: https://github.com/agda/agda/blob/master/CHANGELOG#L2964
