### ISSUE TITLE
Should feature "data/record types qualify their constructors/projections" be removed?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#836]
``` agda
module Bug where

module M where

  record R : Set₁ where
    field
      X : Set

open M using (R)

X : R → Set
X = R.X

-- The open directive did not mention the /module/ R, so (I think
-- that) the code above should be rejected.

-- The following directive is (and should be) rejected:

open R

-- Bug.agda:19,6-7
-- No such module R
-- when scope checking the declaration
--   open R

```

Original issue reported on code.google.com by `nils.anders.danielsson` on 22 Apr 2013 at 4:16

**Comment by andreasabel** [comment]
Here is a proposal:
- Remove qualification by data/record type name.
- default to applying renaming/using/hiding also to the module
  
  E.g.,

``` agda
    open M1 using (N)
    open M2 hiding (O)
    open M3 renaming (P to Q)
```

  will be what was

``` agda
    open M1 using (N; module N)
    open M2 hiding (O; module O)
    open M3 renaming (P to Q; module P to Q)
```
- if renaming/using/hiding is given for a module name explicitly, it overrides the default behavior
  
  E.g.,

``` agda
    open M4 using (N) hiding (module N)
    open M5 hiding (O) using (module O)
```

  will be what was

``` agda
    open M4 using (N)
    open M5 hiding (O) 
```

**Comment by UlfNorell** [comment]
I implemented Andreas' proposal. This had the nice side effect that the parser has to allow both using and hiding (since you might need to say `open M using (R) hiding (module R)`), so the error when you mix using and hiding in a non-sensical way is a nice scope error instead of an ugly parse error.

**Comment by andreasabel** [comment]
Nice!
Did this trigger #1657?

**Comment by UlfNorell** [comment]
Yes, I had to add a few `using (R) hiding (module R)` and forgot to push.

**Comment by asr** [comment]
Starting to back-port into maint-2.4.2...
