### ISSUE TITLE
Bug in coverage checker

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#849]
I think I have found a bug in the coverage checker. I defined the following data type
```agda
data Bool : Set where
  true false : Bool

¬ : Bool → Bool
¬ true = false
¬ false = true

data D : Bool → Set where
  d1 : (x : Bool) → D x
  d2 : (x : Bool) → D (¬ x)
```
The following function passes the coverage checker
```agda
f x      (d1 .x) = ?
f true   y       = ?
```
even though the case for `f false (d2 true)` is not covered. This leads to a proof of ⊥ as follows:
```agda
data ⊥ : Set where

data Test : (x : Bool) → (y : D x) → Set where
  c1 : (x : Bool)   → Test x (d1 x)
  c2 : (y : D true) → Test true y

f : (x : Bool) → (y : D x) → Test x y
f x      (d1 .x) = c1 x
f true   y       = c2 y

impossible : Test false (d2 true) → ⊥
impossible ()

error : ⊥
error = impossible (f false (d2 true))
```
I'm using the Agda 2.3.3 development version from the darcs repository on Ubuntu 12.04.

Original issue reported on code.google.com by `jesper.c...@gmail.com` on 14 May 2013 at 1:19

**Comment by andreasabel** [comment]
Fixed by 90b9615f43ac3cf747ac8726958aabb162448ff0.
