### ISSUE TITLE
Nonstrict irrelevance violated by implicit inference

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#875]
``` agda
module Bug where

postulate
  A : Set
  P : ..(_ : A) → Set
  f : {x : A} → P x 

g : ..(x : A) → P x
g x = f
```

Here the implicit for `f` is infered to be `x`, but if one tries to give it explicitly then Agda complains. If instead of using `..` irrelevance one uses `.` Agda complains don't infer `x`.

Original issue reported on code.google.com by `Daniel.G...@gmail.com` on 25 Jun 2013 at 1:27

**Comment by andreasabel** [comment]
No attachments here.

**Comment by asr** [comment]
Other example of https://github.com/agda/agda/issues/2565#issuecomment-330030472?, that is, the email automatically sent when this issue was closed says

> Closed #875 via 3bac8cb.

but I cannot find which commit closed the issue here in the bug tracker.

**Comment by andreasabel** [comment]
@asr: Must be a recent github bug.

**Comment by asr** [comment]
> @asr: Must be a recent github bug.

It is fixed now, i.e. I can see which commit closed the issue.
