### ISSUE TITLE
Singleton record types block case splitting

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#895]
``` agda
    foo : ⊤ → ⊤
    foo x = {!!}
```

trying to split on x here gives me the error

```
    Right hand side must be a single hole when making a case
    distinction.
    when checking that the expression ? has type ⊤
```

Similar things happen for other record types like ⊤ that have only one possible value.

```
    bar : ⊤ → ⊤ × ⊤
    bar x = {!!}
```

Every variation on this theme yields the same result. Put it through a wrapper, 
put it through a function, use phantom types, make singleton types, and as long 
as the goal type  is fully determined, Agda chokes with that sort of error.

Dan Peebles (copumpkin) also reports the error

```
    Since goal is solved, further case distinction is not supported;
    try `Solve constraints' instead
    when checking that the expression ? has type ⊤
```

which I can't replicate.

Original issue reported on code.google.com by `psygnisf...@gmail.com` on 2 Sep 2013 at 10:37
- Merged into: #289

**Comment by andreasabel** [comment]
Fixed with #289 (duplicate issue).
