### ISSUE TITLE
Copatterns: values that do not produce anything coinductive should not have to be guarded

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#906]
``` agda
{-# OPTIONS --copatterns #-}

module Test where

{- Globular types as a coinductive record -}
record Glob : Set1 where
  coinductive
  field
    Ob : Set
    Hom : (a b : Ob) → Glob
open Glob public

record Unit : Set where

data _==_ {A : Set} (a : A) : A → Set where
  refl : a == a

{- The terminal globular type -}
Unit-glob : Glob
Ob Unit-glob = Unit
Hom Unit-glob _ _ = Unit-glob

{- The tower of identity types -}
Id-glob : (A : Set) → Glob
Ob (Id-glob A) = A
Hom (Id-glob A) a b = Id-glob (a == b)
```

(now I’m using the new copatterns implementation)
The definition of Unit-glob is accepted but the definition of Id-glob is 
rejected (it should be accepted as well).

Original issue reported on code.google.com by `guillaum...@gmail.com` on 18 Sep 2013 at 2:48

**Comment by jespercockx** [comment]
@andreasabel Why did you change the milestone to 2.6.1? We're (hopefully) still planning to release soon, no?

**Comment by asr** [comment]
I added the label `documented-in-changelog` because the issue was documented in the CHANGELOG (good) and it should not be listed by the `closed-issues-for-milestone` program.
