### ISSUE TITLE
bad interaction with copatterns and termination checker

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#942]
In the following module, ex'' is marked as potentially not terminating so the 
goal will not reduce P (fst ex'') to P x.

``` agda
{-# OPTIONS --copatterns #-}
module Bug3 where

record Sigma (A : Set)(P : A → Set) : Set where
  constructor _,_
  field
    fst : A
    snd : P fst
open Sigma

postulate
  A : Set
  x : A
  P Q : A → Set
  Px : P x
  f  : ∀ {x} → P x → Q x

ex : Sigma A Q
ex = record
       { fst = x
       ; snd = f {!!} -- goal: P x
       }

ex' : Sigma A Q
ex' = x , f {!!} -- goal: P x

ex'' : Sigma A Q
fst ex'' = x
snd ex'' = f {!!} -- goal: P (fst ex'')
```

Original issue reported on code.google.com by `Daniel.G...@gmail.com` on 6 Nov 2013 at 6:36
- Merged into: #906

**Comment by andreasabel** [comment]
I could not see any attachment here...  Why do we actually have the label has-attachments?

**Comment by asr** [comment]
> Why do we actually have the label has-attachments?

My bad.

**Comment by andreasabel** [comment]
I know you added them.  But my question is why, or termed otherwise, what is the intended use/benefit?

**Comment by asr** [comment]
After the migration from Google code, as Nils wrote, attachment links use URLs like

```
https://storage.googleapis.com/google-code-attachments/agda/issue-<m>/comment-<n>/<attachment>
```

As Nils also pointed out, we don't know for how long such links will work correctly. I labelled the issues with attachments in Google code, while deciding what to do with them.

Note I renamed the label to `had-attachments-in-google-code`.

**Comment by andreasabel** [comment]
Github does not seem to propagate the renaming to references of `has-attachments`.  So when I click on `has-attachments` (see instances above) I get no search results.  Maybe there is no need to rename the tag...

**Comment by andreasabel** [comment]
So, the plan is to inline the attached counter-examples (at least for open issues)?

**Comment by asr** [comment]
I also noted that the propagation is not complete, but the issues with the label `has-attachments` were correctly re-labelled, so I will keep the new label.

**Comment by asr** [comment]
> So, the plan is to inline the attached counter-examples (at least for open issues)?

We can inline the code or use GitHub (new) attachments feature. In any case, we should remove the `had-attachments-in-google-code` label after removing the URL to Google code.
