### ISSUE TITLE
Auto missing support for Copatterns

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#957]
```
git clone git@github.com:andreasabel/cubical.git -b 0.0.0.1

Load cubical/src/Control/Auto-Bug-in-Goal-2.agda

Fix the module name (should be Control.Auto-Bug-in-Goal-2).
Go to the second goal (?1).
Press C-c C-a.

An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/Auto/Convert.hs:585
```

Original issue reported on code.google.com by `andreas....@gmail.com` on 13 Nov 2013 at 10:03

**Comment by isovector** [comment]
Without knowing anything about the internals, this feels like a rather arbitrary limitation. What would be necessary to get copatterns supported here?

**Comment by andreasabel** [comment]
> What would be necessary to get copatterns supported here?

Understand and extend the `Agda.Auto.*` implementation.  No one has been willing to do that; Auto is bit-rotting.  If you look at the code, you might understand why.
@UlfNorell has a student working on a new term synthesizer.
