### ISSUE TITLE
Easier way to bring data type with all constructors into scope

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#96]
In Haskell you can type

``` agda
import M qualified (D(..))
```

in order to bring the data type `D` along with all its constructors into scope. In Agda you have to write

```
open import M using (D; d₁; d₂; d₃…).
```

This is mildly annoying. Some shorthand notation would be nice.

The syntax is not very important. One (not very good) suggestion:

``` agda
open import M using (all of D).
```

However, the semantics is important. If one of D's constructors is overloaded, then

```
open import M using (all of D)
```

should only bring that instance into scope, even if M exports several constructors of the same name. The fact that there is currently no way to import just one of the constructors in such a situation is a bit of a wart; feel free to address that problem as well.

Original issue reported on code.google.com by `nils.anders.danielsson` on 11 Aug 2008 at 5:20

**Comment by andreasabel** [comment]
On master, one can now write

``` agda
open M e using (D); open D
```

I suggest the shorthands

``` agda
open M e using (D opened)
open M e renaming (D to D' opened)
```

or maybe

``` agda
open M e using (open D)
open M e renaming (D to open D')
```

**Comment by UlfNorell** [comment]
I would prefer the latter, to avoid introducing extra keywords.

**Comment by UlfNorell** [comment]
An argument against the syntax extension is that I predict we would quickly get the feature request that you should be able to say

``` agda
open M e using (open D using (c) renaming (d to d'))
```

I don't think it's really that inconvenient to split it over two module statements.

**Comment by andreasabel** [comment]
I guess the current syntax is not too verbose, so we can postpone this issue and such recursive import declarations until some screams again.

**Comment by ajrouvoet** [comment]
I'd like to request reopening this issue.

It is still pretty verbose to import multiple data-types from a module with their constructors.
If one has to be particular about which data-types to import from a module, this already feels like a chore. Having to repeat the same names to then also import their constructors is not fun.

Another big difference is that dedicated syntax for "including constructors" would inherit the 'public' flag of the import. In the desugaring proposed above this needs to be done manually.

Then, in addition, there seems to be some discrepancy between record modules and data-modules, in that opening a record module does not bring the constructor into scope? Is there a good reason for this? Some syntax to import a type with its constructors could solve this I suppose?

**Comment by andreasabel** [comment]
> opening a record module does not bring the constructor into scope? Is there a good reason for this? 

Yes, the record constructor is not part of the record module, which is parametrized by a record value.  Wouldn't make sense to parametrize the constructor by a value of what is constructed.

A problem with a dedicated syntax for constructor import is that then there is a difference between constructors and pattern synonyms.  This is a problem in GHC:  There, you have to import in the style
```haskell
import M (Err(Ok,Bad))
```
but when the implementor of `M` changes the representation of `Err` and makes former constructors `Ok` and `Bad` pattern synonyms, the client's code breaks.

**Comment by ajrouvoet** [comment]
> Wouldn't make sense to parametrize the constructor by a value of what is constructed.

Of course :) all the more reason to consider some special import syntax then.

> A problem with a dedicated syntax for constructor import is that then there is a difference between constructors and pattern synonyms

Right, but that just means that there is a separate problem related to pattern synonyms, no? Because the current approach also fails there. Or is there already a way to put things into the data module that I'm unaware of?

**Comment by nad** [comment]
> Or is there already a way to put things into the data module that I'm unaware of?

I'm not sure what you mean. I have used the following pattern to work around problems with record modules (#3592, #4251):
```agda
private
 module Dummy where

  record R … : … where
    …

open Dummy public using (R) hiding (module R)

module R … (r : R …) where

  open Dummy.R r public

  …
```

**Comment by ajrouvoet** [comment]
Yet another reason to have some special syntax for "a type with its constructors" is that it could be used for `hiding` them in one big sweep :)
