### ISSUE TITLE
Allow unsolved metas in imported files

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#964]
File A.agda

``` agda
module A where

B : Set1
B = Set

C : Set
C = ?
```

File B.agda

``` agda
open import A

module B where

D : Set1
D = B
```

In the previous situation, when loading the file B.agda in emacs, the Agda mode complains about unsolved metas in A.agda, which is a bit annoying because C is not even used in B.agda.
I think Agda should allow importing files containing unsolved metas (as long as they are not used elsewhere).

Original issue reported on code.google.com by `guillaum...@gmail.com` on 15 Nov 2013 at 2:54

**Comment by andreasabel** [comment]
A simple solution is this one:  Before serialization, create a new postulate for each open meta and solve the meta with this postulate.
Works, except that in interaction mode, we build the interface before we let the user work on interaction points.  They should not have been solved my postulate at this point.

**Comment by andreasabel** [comment]
I implemented this: metas are replaced by postulates in file imported from the main file, but not in the main file itself.  This allows interaction on the main file.

**Comment by andreasabel** [comment]
The problem with the present solution is that unsolved metas from a different file are treated as injective (since they are postulates).  Thus, one might get an error where one expected yellow.

File M.agda:
```agda
{-# OPTIONS --allow-unsolved-metas #-}

module M where

K : {A B : Set} -> A -> B -> A
K = ?
```

File Main.agda:
```agda
module Main where

open import Agda.Builtin.Equality
open import M

test : {A : Set} {x y z : A} -> K x y ≡ K x z
test = refl
```
Error:
```
.y != .z of type .A
when checking that the expression refl has type K .x .y ≡ K .x .z
```
A solution would be to have postulates that are flexible (non-injective) like metas.
(Original milestone was 2.5.2.)

**Comment by nad** [comment]
@andreasabel, did you intend to reopen this issue? (I would prefer a fresh issue.)
