### ISSUE TITLE
Wrong fixity applied for overloaded constructor

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#978]
Having an overloaded constructor in scope with different fixity for its different instances bears trouble:

``` agda
module A where

  infixr 4 _,_

  record _×_ (A B : Set) : Set where
    constructor _,_
    field
      fst : A
      snd : B

module B where

  infixl 2 _,_

  data Ty : Set where

  data Cxt : Set where
    ε   : Cxt
    _,_ : (Γ : Cxt) (a : Ty) → Cxt

open A
open B

test : (Γ : Cxt) → Set₁
test ε = Set
test (Γ , a) = {!Γ!}  -- press C-c C-c here
```

Agda splits

``` agda
test (ε , a) = ?
test (Γ , a , a₁) = ?  
```

but then cannot parse it

```
_,_ is not a constructor of the datatype Ty
when checking that the pattern a , a₁ has type Ty
```

In the current design of Agda, this cannot be made to work.  Overloaded constructors with different fixity cannot be parsed before resolving the overloaded, which happens at type-checking. This shows that phase separation parsing/scope checking/type-checking is impossible for the current design.

Question:  Why is the first fixity taken for _,_ and not the second?  

Answer: None should be taken, instead an error "fixity clash" should be raised (similar to when we use a name that is in scope from two different modules)!

Original issue reported on code.google.com by `andreas....@gmail.com` on 23 Nov 2013 at 8:55

**Comment by nad** [comment]
This issue seems to have been fixed.
