### ISSUE TITLE
Change \AgdaIndent from \;\; to $\;\;$

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#982]
For some reason I can't explain the following code:

``` latex
\documentclass{article}

\usepackage{agda}

\begin{document}

%\renewcommand{\AgdaIndent}{\;\;}

\begin{code}
record Sigma (A : Set) (B : A → Set) : Set where
  constructor _,_
  field
    proj₁ : A
    proj₂ : B proj₁

open Sigma public
\end{code}

\begin{code}
uncurry : {A : Set} {B : A → Set} {C : Sigma A B → Set} →
          ((x : A) → (y : B x) → C (x , y)) →
          ((p : Sigma A B) → C p)
uncurry f (x , y) = f x y
\end{code}

\end{document}
```

Does not compile with the old \;\; value of \AgdaIndent. Changing it to $\;\;$ 
fixes this.

The attached patch changes \AgdaIndent in agda.sty and adds the above test case 
to the test suite.

Original issue reported on code.google.com by `stevan.a...@gmail.com` on 27 Nov 2013 at 6:15

Attachments:
- [agda-latex-backend-agdaindent.patch](https://storage.googleapis.com/google-code-attachments/agda/issue-982/comment-0/agda-latex-backend-agdaindent.patch)

**Comment by asr** [comment]
The test case (in test/LaTeXAndHTML/succeed) is failing using a recent version of `lualatex`:

```
$ agda --latex Issue982.lagda
$ cd latex
$ lualatex Issue982.tex
...
l.357 {\sffamily
              \xdef\@sffamilyname{\f@family}}
```

```
$ lualatex --version
This is LuaTeX, Version 0.95.0 (TeX Live 2016)
```

Pinging @stevana.

**Comment by asr** [comment]
I reported in #2179 the current problems with `LuaLateX`, so I'm closing the issue.
