### ISSUE TITLE
Internal error in Agda.Interaction.InteractionTop

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#983]
I admit this error is somewhat obscure, but it still cost me quite some time trying to find out what's wrong. How to reproduce on latest darcs version of agda:
1. Create the following 3 files in an empty directory:

``` agda
--- Test1.agda ---

{-# OPTIONS --without-K #-}

module Test1 where

data _≡_ {A : Set} (x : A) : A → Set where
  refl : x ≡ x

K : {A : Set} {x : A} (p : x ≡ x) → p ≡ refl
K refl = refl
```

``` agda
--- Test2.agda ---

module Test2 where

open import Test1

K' = K
```

``` agda
--- Test3.agda ---

module Test3 where

open import Test2
```
1. Open `Test3.agda` in emacs and load it. You get an error in `Test1.agda` (this is still as expected).
2. Comment out the definition of `K` and reload `Test1.agda`. The error should now be gone.
3. Return to `Test3.agda` and try to load it again. 

What I expect that would happen: An error telling me `K` is no longer in scope in `Test2.agda`

What I get instead:

```
An internal error has occurred. Please report this as a bug.
Location of the error:
src/full/Agda/Interaction/InteractionTop.hs:852
```

Original issue reported on code.google.com by `jesper.c...@gmail.com` on 28 Nov 2013 at 2:33

**Comment by andreasabel** [comment]
Fixed by commit 32543b4820df1ba266a26cfbdb4c33433d556356

```
Author: ulfn <ulfn@chalmers.se>
Date:   Fri Nov 29 12:31:13 2013 +0000

    [ issue 983 ] fixed: reset theCurrentFile if an independent command fails
```
