### ISSUE TITLE
Print a shadowed indentifier as such

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#998]
```agda
postulate
  A : Set
  a : A

data D : A → Set where
  d : (a : A) → D a

f : D a → Set
f (d a) = A

-- Bad error:
-- a != a of type A
-- when checking that the pattern d a has type D a
```
Perplexing even to me, could drive a beginner nuts...

Original issue reported on code.google.com by `andreas....@gmail.com` on 16 Dec 2013 at 12:43

**Comment by nad** [comment]
Commit: c834e1c581071d9010054cf1ceac2a95a8c65b93.

**Comment by UlfNorell** [comment]
The error message is fixed by the above commit. The rest is #572.
